### ISSUE TITLE
Nuxt Generate : more options in generate script

### ISSUE THREAD

**Issue by TakCastel** [nuxt/nuxt#10023]
### Is your feature request related to a problem? Please describe.

> ### TL;DR
> Nuxt generate 30K+ pages is too slow. Please provide clear information wether or not Nuxt.js is capable of deploying such amount of static pages. And if yes, how to configure deployment commands.

Hello,

This issue isn't related to any problem but it is more a feature needed for a project. Here's the story : I work for an e-commerce company and we have chosen Nuxt.js for the frontend development. Everything is just perfect with this framework and it is such a good tool. I've set up routing, product pages, home pages, CMS based pages with some dynamic components etc, etc. 

I'm now in the deployment process, and things start to go off the grid. 
I think something is missing in the documentation for my case 😕

We are using Nginx as we are hosting the site in our servers, we can't use Vercel or Netlify. For the deployment strategy, I've selected the `generate` method as we need the site to be static for SEO purposes and to increase performance. Here's the problem. For me, it is really unclear wether Nuxt is able to generate a static site or not. I'm assuming for a little blog with few articles that can be easy. 

But we have **30K+ pages to generate**. One for each product, each categories of products and each custom content pages.

I've encountered several issues regarding the generation process. First it was memory usage that has been fixed with this command in the `package.json` : 

```json
 "generate:limitless": "node --max-old-space-size=4096 node_modules/nuxt/bin/nuxt.js generate",
```

I really think you should say in the documentation that we need to increase RAM allocation (if I understand correctly what this script does lol).

Then I'm using a custom API endpoint where all the routes are listed like this inside `nuxt.config.js` : 

```js
  generate: {
    concurrency: 100,
    fallback: '404.html',

    async routes() {
      console.log('⏳ Fetching routes')

      const routes = await axios
        .get(`${process.env.BASE_URL}/allpages`)
        .then((res) => {
          return res.data.map((item) => {
            return {
              route: item,
            }
          })
        })

      console.log('⌛️ Routes fetched')

      return routes
    },
  },
```

And now I have to generate 30K+ pages and it's taking literally several **HOURS** to process which make me think Nuxt.js wasn't made for such project size. I think maybe we can warn people in the documentation that there is a limit and Nuxt.js is designed for small projects ? Or if we can use Nuxt.js for large project like mine, maybe warn people about the generate time ?

So I tried to fix this load time using the [nuxt-generate-cluster](https://github.com/nuxt-community/nuxt-generate-cluster) dependency but it hasn't been updated since 2 years and I'm encountering a lot of problems regarding this library. I don't understand what I'm doing wrong here.

Plus, at some point I will probably need to generate single pages from edited products/pages. I've found [this issue (#6138)](https://github.com/nuxt/nuxt.js/issues/6138) is really helping but it took me days before knowing it was possible.

### Describe the solution you'd like

I think the documentation needs more clarity on how to serve the project on generate strategy. 
If I don't use `generate` and only `build` with PM2 to run the website, will it still be ok for SEO ?

Also, what could be interesting is adding more options in generate script like so : 

| Option | What it does |
| --- | ----------- |
| --ignore-memory, -i | Generate website and ignoring JS memory limit |
| --page, -p page-slug-1 page-slug-2 | Generate single page passing arguments as name of the page |
| --cluster, -w 4 | Generate on multi-thread using processors amount as arguments|

### Describe alternatives you've considered

There is no alternative, I want to deploy using Nuxt.js but the generate time is taking too long 🙂

Thanks for all the work and contributors, making dev faster and simpler 🙏

**Comment by Spreizu** [comment]
How often do you need to re-generate all of the pages? nuxt-generate-cluster does work, but you're right about the part that it requires some work on your part. However, from my experience it will literally scale almost linearly, if your code is optimized. For example, if it currently takes 2 hours, then with 4 cores it will take approximately 35 minutes.
To start with, I'd recommend disabling some or all of the HTML minify options. You can test this out by first disabling all of the options (minifyJS, minifyCSS), for example. This will reduce the time by a lot. And I mean a lot.

https://nuxtjs.org/docs/configuration-glossary/configuration-build/#htmlminify

**Comment by TakCastel** [comment]
I need to re-generate the pages every week, but also everytime a data has been updated in the CMS. But for this second scenario, I would like Nuxt to handle it directly. I saw how to do it in some issue, but what I am suggesting is that maybe we can add these specs in the documentation for the future ? Directly inside the `generate` script.

Thanks for the advice, I will try what you suggested.

**Comment by cetchells** [comment]
@TakCastel Have you considered passing in a --date to the generate, to just generate the updated pages from the previous week? How to do that is discussed here -> #6138 I believe the date hashing for the payload filenames can be turned off with
` staticAssets: {
      version: 'prod' // Will overwrite the timestamp used in static asset versioning
    },`

**Comment by TakCastel** [comment]
No I haven't, I used the solution by @emiliobondioli, generating single page like so :

`yarn generate:single /category/123` 

Which will generate the page of category 123. 

But I don't understand the logic here : 

> (...) If doing an incremental build, instead of passing the routes to generate, an API call will be made to query the backend for any changes that has happen since a given date, and then return those routes along with their payload.

Is it saying the pages generation is handled on the Backend side and Nuxt no longer makes the API calls inside the `generate` property ?

Thank you.

**Comment by TakCastel** [comment]
After days of trying to make it work, we decided to go back to SSR and abandoned the SSG strategy for deploying the app. I would like this to be a warning : Nuxt **IS NOT** ready for deploying such big applications (remember : 30K+ pages and daily updates / single pages content being updated multiple times a day). Thank you for your time.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
