### ISSUE TITLE
Multiple Nuxt instances on the same page conflict

### ISSUE THREAD

**Issue by tdeea** [nuxt/nuxt#10064]
### Is your feature request related to a problem? Please describe.

I spent days debugging an issue I came across in one of the projects I work on where we use multiple Nuxt instances in the same page. Using globalName was not enough in this scenario because one webpack function was not namespaced. 
The solution was this https://v4.webpack.js.org/configuration/output/#outputjsonpfunction.

### Describe the solution you'd like

I think it would be very helpful to use globalName for this purpose too. To use globalName value to set webpack config related to webpackJsonP function to prevent multiple instances of this function to clash. I know Nuxt is not build for this usage (microfrontends) but for SPAs, but this change is a nice feature with no impact for SPAs and there is not much documentation for devs to easily reach to this solution by themselves so the magic will happen behind the scenes.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
