### ISSUE TITLE
Add dev or `--watch` version of `nuxt generate`

### ISSUE THREAD

**Issue by colearendt** [nuxt/nuxt#10072]
### Is your feature request related to a problem? Please describe.

When working with `nuxt dev`, some behavior is functional that breaks when switching to `nuxt generate`. As a result, my dev workflow requires running `nuxt generate` often

### Describe the solution you'd like

A way to run a "dev" version of `nuxt generate` that "watches for changes" and "regenerates files that change." This way I can get a more surgical / quick `nuxt generate` output for a better dev workflow. Something like:
```
nuxt dev --generate
nuxt generate --watch
nuxt generate --dev
```

### Describe alternatives you've considered

Running `nuxt generate` all the time along with `nuxt start` 🙈

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
