### ISSUE TITLE
Add option to add additional directories to generate.cache snapshot

### ISSUE THREAD

**Issue by weotch** [nuxt/nuxt#10080]
### Is your feature request related to a problem? Please describe.

We often use nuxt in a yarn workspace based monorepo like:

```
/library
/nuxt-app
  /nuxt.config.js
/shopify-theme
yarn.lock
```

When we push a commit up to Netlify and there is only changes to the `library` directory, we'll see a message like this in the deploy log:

```
11:03:26 AM: [success] Skipping webpack build as no changes detected
```

When `nuxt-app` depends on those changes to `library`, this means that the new build doesn't contain the fresh code change.

### Describe the solution you'd like

I think this could be fixed with a nuxt.config.js option to provide our own patterns to `globby` here: 

https://github.com/nuxt/nuxt.js/blob/853439ddf945b6ee358d5912e6e5a68009633c27/packages/cli/src/utils/generate.js#L162-L167

Since globby supports an array for its first argument, I think we could pass a value like:

```js
await globby(['**/*.*', '../library/**/*.*'], {
  ...
}
```

### Describe alternatives you've considered

We _could_ move the `rootDir` out to the parent.

**Comment by IsraelOrtuno** [comment]
This is needed specially for monorepo applications. Could be great to be able to specify other folders from the `nuxt.config.js` file.

@weotch have you found an alternative? I have been dealing with this for a while now.

**Comment by IsraelOrtuno** [comment]
@weotch and others, I solved this issue by adding a symlink to that external folder. You can either do it manually or create it from a module:

```javascript
  const coreCacheFolder = this.nuxt.options.srcDir + '/_libcache';

  this.nuxt.hook('generate:cache:ignore', () => {
    if (!fs.existsSync(coreCacheFolder))
      fs.symlink(path.resolve(__dirname, '../'), coreCacheFolder, 'dir', () => {});
  });
```

I have tested this on Netlify and it works perfectly!

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
