### ISSUE TITLE
layouts css style

### ISSUE THREAD

**Issue by kouxin** [nuxt/nuxt#10083]
layout element具有默认class _nuxt和_layout，但是没有地方修改，导致我的page使用height:100%的时候并没有任何作用，目前只能使用
*{height:inherit}或者div{positon:absolute}改变对照父级，来处理这种情况

**Comment by lucpotage** [comment]
I see two options:

1. Add a custom `app.html` file? https://nuxtjs.org/docs/concepts/views/#document-apphtml inline style with a head `<style>` element in `<head>`
2. Import a global stylesheet in `nuxt.config.js`

For both cases, add your CSS properties to `__nuxt` and `__layout`.

**Comment by selimdoyranli** [comment]
you said it hasn't been changed, does that work for you? you can change as custom selector, check this https://nuxtjs.org/docs/configuration-glossary/configuration-global-name/

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
