### ISSUE TITLE
Loading indication isn't started if it was stopped less than 500ms beforehand

### ISSUE THREAD

**Issue by arikw** [nuxt/nuxt#10085]
### Versions

- nuxt: v2.15.8
- node: v14.17.5

### Steps to reproduce
Do the following:
```javascript
$nuxt.$loading.start();
$nuxt.$loading.finish();
$nuxt.$loading.start();
```

### What is Expected?
loading indication should be shown

### What is actually happening?
loading indication is finished after 500ms since calling `finish()` even if `start()` was called shortly afterwards

**Comment by shachar-langer** [comment]
We're experiencing the same issue.

**Comment by arikw** [comment]
I've posted the reproduction steps. Any update on the issue?

**Comment by Atinux** [comment]
It was actually intended to avoid having the progress bar starting again.
