### ISSUE TITLE
nuxt generate execute nuxt.config.js twice when set target=static

### ISSUE THREAD

**Issue by zcqno1** [nuxt/nuxt#10098]
### Versions

- nuxt: v2.15.7
- node: v12.14.0

### Reproduction
![image](https://user-images.githubusercontent.com/11766057/144248256-c71c3b6d-6a78-4cb3-8933-eacc6e634c76.png)

### Steps to reproduce

1. set `target: 'static'` in `nuxt.config.js`
2. add log in `nuxt.config.js` just under the module: `console.log('hello')`
3. build with `nuxt generate` 
4. the shell would show two `hello` 

### What is Expected?
`nuxt.config.js` only executes once.

### What is actually happening?

https://github.com/nuxt/nuxt.js/blob/853439ddf945b6ee358d5912e6e5a68009633c27/packages/cli/src/commands/generate.js#L71-L75

https://github.com/nuxt/nuxt.js/blob/ab1c6cb442c9418128c85ad2cb14ed162af44933/packages/cli/src/utils/generate.js#L130-L131

`ensureBuild()` and `generate()` both call `getNuxt()` which calls the `cmd.getNuxtConfig()`. `getNuxtConfig` method calls `loadNuxtConfig()` later, which would clear the require cache before loading `nuxt.config.js`. As a result, `nuxt.config.js` would run twice.

**Comment by nachoadjust** [comment]
Also happening to me, as I am trying to bump up from Nuxt 2.14.X to 2.15:

- Nuxt: v2.15.8
- Node: v14.17.1

It is also doubling all calls to nuxt.hooks and running the modules and build modules twice (those using "generate.before" in my case)

**Comment by juanjcardona13** [comment]
This should open again

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️
