### ISSUE TITLE
Best practice: place <meta charset> before <title>

### ISSUE THREAD

**Issue by maxdup** [nuxt/nuxt#10127]
### Is your feature request related to a problem? Please describe.

`<head>` generation from nuxt.config.js places `<title>` before `<meta charset>`, this goes against best practices.
For `<meta charset>` to affect `<title>`, `<meta charset>` needs to appear first (may vary from browser to browser but this is the basis for the best practice).

### Describe the solution you'd like

The simplest way that preserves backward compatibility would be to render metas before the title.

### Additional context

Documentation about charset best practices:
https://code.google.com/archive/p/doctype-mirror/wikis/MetaCharsetAttribute.wiki

> In order for all browsers to recognize a `<meta charset>` declaration, it must be
> - Within the <head> element,
> - Before any elements that contain text, such as the <title> element, AND
> - Within the first 512 bytes of your document, including DOCTYPE and whitespace

**Comment by danielroe** [comment]
This is now implemented in https://github.com/unjs/unhead, which is used to render tags in Nuxt 3.
