### ISSUE TITLE
Usage of excerpt and body objects in template

### ISSUE THREAD

**Issue by glodov** [nuxt/nuxt#10169]
### Is your feature request related to a problem? Please describe.

There is no documentation about using excerpt or body in the template to render as it is.  
I could not find out how it works in nuxtjs source code and over the internet.

### Describe the solution you'd like

As a final solution, it should be the ability to insert such rendered HTML into a template.
```html
<template>
  <div class="container-sm my-5">
    <section id="blog">
      <h1>Blog</h1>
      <article v-for="post in posts" :key="post.slug">
        <h2>
          <nuxt-link :to="post.path">{{ post.title }}</nuxt-link>
        </h2>
        <div v-html="post.excerpt.html"></div>
      </article>
    </section>
  </div>
</template>
```

### Describe alternatives you've considered

As an alternative, it could be a render/parser plugin for excerpt/body objects.

### Additional context

`post.excerpt.constructor.name` is an object how is this possible?

**Comment by danielroe** [comment]
If this is still relevant, would you raise an issue at https://github.com/nuxt/content? 🙏
