### ISSUE TITLE
Nuxt Auth: Refresh token only on Requests

### ISSUE THREAD

**Issue by nickelnext** [nuxt/nuxt#10162]
💚 Thanks for the amazing Nuxt Library. I love it and I hope this project will keep on growing 💚

I want to discuss a particular but very common problem (i guess) with Refresh Token auth schemas in nuxt.js

I'm currently using:

```
    "@nuxtjs/auth-next": "^5.0.0-1620457172.0cf714c",
    "@nuxtjs/axios":  #"^5.13.1",
...
    "nuxt": "^2.15.3",
```
my `nuxt.config.js` strategies has

```
local: {
        scheme: 'refresh',
        endpoints: {
              login: { url: '/User/Authenticate', method: 'post'},
              refresh: { url: '/User/RefreshToken', method: 'post', },
              logout : false,
              user:  {url: '/User/ContextUser', method : 'get'},
            },
            token: {
              type: 'Bearer',
              maxAge: 100,
              property: 'jwtToken',
            },
            user: {
              property: false,
              autoFetch: true
            },
            refreshToken: {
              property: 'refreshToken',
              data:  'refreshToken',
            },
      }
```

I tested the functionality of Axios/Nuxt Auth and I realized that the module is ALREADY checking, at every single `axios` request (thanks to interceptors I guess), if the jwtToken is expired, and if yes, it calls the refreshToken endpoint to refresh it, then it carries on with the axios request.
This way, basically, we are sure that every axios request gets carried out with a refreshed jwt token.

Although, I expected that the library would have something like a SetInterval or SetTimeout function that would run EVEN IF there were no axios calls in the meantime.

What I mean is that, for example in my code, I need to use the jwt OUTSIDE the axios calls, but i need it to be updated to the latest refresh.
In my particular case I have a getter in my modular store that needs to call an Endpoint with the jwtToken passed not in the headers but as a GET parameter.

My workaround was the following (which works, but it looks ugly)

`store > media > getters.js`

```
let isRefreshing = false

const getters = {
  getMedia: (state) => state.media,
  fetchMediaUrl: (state, getters, rootState) => (mediaId) => {
    if (process.client) {
      if ($nuxt.$store.$auth.strategy.token.status().expired() && !isRefreshing) {
        //isRefreshing is needed not to get million calls right away
        isRefreshing = true

        setTimeout(() => {
                isRefreshing = false
                console.log('isRefreshing set to false')
        }, 10000);

        let oldDecodedToken = rootState.token.decodedToken;
        let oldStrategyToken = $nuxt.$store.$auth.strategy.token.get();
        let oldStrateyRefreshToken = $nuxt.$store.$auth.strategy.refreshToken.get();

        $nuxt.$auth.refreshTokens();

        let storetoken = $nuxt.$auth.strategy.token
          .get()
          .replace("Bearer ", "");
        $nuxt.$store.dispatch("token/setAccessToken", storetoken);

        let newDecodedToken = rootState.token.decodedToken;
        let newStrategyToken = $nuxt.$store.$auth.strategy.token.get();
        let newStrateyRefreshToken = $nuxt.$store.$auth.strategy.refreshToken.get();

        if (oldDecodedToken !== newDecodedToken)
                console.log("decodedToken has changed");
                console.log(oldDecodedToken);
                console.log(newDecodedToken)
        if(oldStrategyToken !== newStrategyToken)
                console.log("strategytoken has changed");
        if(oldStrateyRefreshToken !== newStrateyRefreshToken) {
                console.log("refresh has changed");
        }
      }
    }
    return `Media/${mediaId}/BytesToken?token=${rootState.token.accessToken?.replace(
      "Bearer ",
      ""
    )}`;
  },
};

export default getters;
```
In the code above the 3 `ifs` are just for debugging purpose, and the only token that changes is the "decodedToken". The other two if are never true. That's something i don't understand.

Again, this is just because the Auth/axios module doesn't automatically refresh the token after a given time (which should be read by the `exp` property of the token, minus a 10/25% for safety.

Is there a clearer, cleaner and nicer way (maybe via middleware, maybe via nuxtServerInit) to tell Axios to refresh the tokens after a certain amount of time?

I tried to use interceptors such as `$axios.onRequest` but the `$auth.refreshTokens()` or the `$auth.strategy.token.sync()` make the app crash because, I guess, you can't send out headers multiple times while in an interceptor.

Note: i read these links
[link-1](https://question-it.com/questions/1647088/nuxtjs-auth-token-obnovlenija-jwt)
[link-2](https://stackoverflow.com/questions/63436923/nuxt-js-auth-jwt-refresh-token)
but I'm not sure they are exactly what I'm looking for.

Thank you for your understanding and your help

**Comment by wesley3295** [comment]
Any updates on this or how you went about doing it?
Currently working on a project that requires a refresh of the jwt apon every axios call. Im using Nuxt Auth and Axios. 

Currently trying to use the axios plug-in, but I'm having issues calling $auth.refreshTokens() and $auth.seUserToken(token). Any examples would be great.

**Comment by danielroe** [comment]
If this is still relevant, would you raise this upstream at https://github.com/nuxt-community/auth-module? (It might be worth waiting also for the upcoming nuxt/auth module.)
