### ISSUE TITLE
Unguarded `window.sessionStorage` throws under certain Chromium configurations

### ISSUE THREAD

**Issue by sarayourfriend** [nuxt/nuxt#10279]
### Versions

- nuxt:  v2.15.8 
- node:  any

### Reproduction

I'm not sure how to force reproduction of it but I can share screenshots of Sentry reports of this happening to Chrome users.

Here is a public link for one, but it has scant details: https://sentry.io/share/issue/5b04b3dc45504c569403daac59a549f1/

Here is a screenshot of the full error with stacktrace and browser information:

![image](https://user-images.githubusercontent.com/24264157/154118533-04def9dd-ff9c-4203-8e40-5958510c2d59.png)

I've been able to consistently reproduce the error by opening chrome://settings/cookies in Chromium based browser and setting the "Block all cookies (not recommended)" setting. Then open the devtools and simply try to access `window.sessionStorage` property and the SecurityError with throw.

The block of code at fault is here:

https://github.com/nuxt/nuxt.js/blob/777a4b7f5033c86c37cbd93008f3ca792e4af8bc/packages/vue-app/template/utils.js#L158

I believe the `if` condition and the call to `setItem` need to be wrapped in their own try/catch. **I'm happy to open a PR for this** but I'm unsure what to do in the `catch` clause. Should it just force a reload?

**Comment by sarayourfriend** [comment]
This still happens in our production app on a regular basis. Can a maintainer give advise on the correct solution so I can open a PR?

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by sarayourfriend** [comment]
As far as I can tell from [a quick search of sessionStorage access in the current codebase](https://github.com/search?q=repo%3Anuxt%2Fnuxt+sessionStorage&type=code) instances of it are wrapped in try/catch, so I don't think this is relevant for Nuxt 3.

The issue remains in Nuxt 2, and does ostensibly cause a crash, but is presumably not that common considering no one else has reported the issue (or left a :+1: or anything here). 

https://github.com/nuxt/nuxt/blob/2.x/packages/vue-app/template/utils.js#L153-L167
