### ISSUE TITLE
Layout options

### ISSUE THREAD

**Issue by Kolobok12309** [nuxt/nuxt#10299]
### Is your feature request related to a problem? Please describe.

We have site and a lot of modules like forum, shop, questions, etc All of them use visually similar layouts, but sidebars can be little differents. Because of this, we have layout for each module. This is not the best solution. Another solution i see is change sidebars by `$route` and is too not the best variant.

### Describe the solution you'd like

By the test, i add property `layoutOptions: {}` to page components and pass it to `layouts`. It's a `data` property which updates while page is switching(`pageTransition.beforeEnter`).
Best solution is update this prop in this place, but without `$nextTick`
https://github.com/nuxt/nuxt.js/blob/777a4b7f5033c86c37cbd93008f3ca792e4af8bc/packages/vue-app/template/components/nuxt-child.js#L49-L56

It's can be some analogue of `layout slots` from nuxt3

### Additional context

Adding of `pageTransition.beforeEnter` addition required due to update options between switching pages without flashes(i change some classes between pages for for convenience, and update by `watch: $route` give flashes)

**Comment by Kolobok12309** [comment]
If maintainers approve this feature, i create pr with tests, doc and realization

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉

**Comment by arily** [comment]
I got into this problem recently,

instead of having something like this:
```ts
definePageMeta({
  layout: 'default',
  layoutProps: {
    navbar: 'hidden'
  }
})
```
only option I found was like
```vue
<script>
definePageMeta({
  layout: false,
})

// ...
</script>
<template>
  <div>
    <NuxtLayout name="default" navbar="hidden">
// ...
```
and by doing this way it will also trigger unnecessary layout shifts, and layout transitions.

can we make this happen?
