### ISSUE TITLE
Optional parameter route generated when page is kebab-case

### ISSUE THREAD

**Issue by existe-deja** [nuxt/nuxt#10334]
### Versions
- nuxt: 2.15.8
- node: v16.13.2

### Reproduction
https://codesandbox.io/s/modest-turing-3tsnzy?file=/pages/index.vue

### Steps to reproduce
In pages directory, create a kebab-case folder with dynamic parameter inside 

### What is Expected?
[Following the doc,](https://nuxtjs.org/docs/features/file-system-routing#dynamic-routes) if I want to have a parameter not optional, I have to create a dynamic folder (`_id`) with an `index.vue` file inside.
Nothing prevents me to name my pages in kebab-case, so I expect non optional parameter routes to be generated.

### What is actually happening?
Routes are generated with optional parameter.

### Additional infos
Maybe related to https://github.com/nuxt/nuxt.js/issues/1008, https://github.com/nuxt/nuxt.js/issues/2716

**Comment by existe-deja** [comment]
:/

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
