### ISSUE TITLE
Head Scripts not being cleared between pages

### ISSUE THREAD

**Issue by danspratling** [nuxt/nuxt#10342]
### Versions

- nuxt: ?? (using nuxtjs/prismic@^1.4.0 - prismic seems to be including nuxt automatically as it's not listed)
- nuxt-bridge: ^0.10.1
- node: 16.13.2

### Reproduction

Unfortunately, I don't have reproduction as this is using client code, however, this is really more of a question on intended functionality.

### What is Expected?
When navigating (prismic-link/nuxt-link) to a page that adds a script via nuxt head, that script is added to the page and run.
When navigating to another page that does not include the script, this script should then be removed.

Page A (has no script) -> Page B (has script) -> Return to Page A (has no script)

### What is actually happening?
When navigating to a page that adds a script via nuxt head, that script is added to the page and run - this part works as expected.
When navigating to another page that does not include the script, the script from the previous page still exists.

Page A (has no script) -> Page B (has script) -> Return to Page A (now showing the script that appeared on Page B)

My assumption is that Nuxt's caching is saving this script between pages as it is being loaded, and I can see why this would make sense in a lot of use cases. However, when the script only needs to be applied on specific pages (like a context-sensitive external feedback script, for example) this causes the loaded script to then be shown on pages where it makes no sense.

I have tried disabling prefetching globally, but this does not help.

Is there a method to force a refresh of the scripts in Nuxt Head to ensure that page scripts aren't accidentally carried across to pages that shouldn't have them?

**Comment by rchl** [comment]
It's not a Javascript and not Nuxt-specific behavior. Nuxt can (and probably does) remove the script element but that won't and can't undo any changes to the script environment that the script might do.

You'd have to ensure that the script won't do anything bad on pages that it's not supposed to run on and maybe also expose some API so that you can invoke its functionality whenever navigating to the page that is supposed to us it.
