### ISSUE TITLE
Vuetify root stylesheet import error

### ISSUE THREAD

**Issue by shadrqen** [nuxt/nuxt#10349]
### Versions

- nuxt: 
- node: 

### Reproduction
https://github.com/shadrqen/petshop/tree/bug-nuxt-root-stylesheet

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce

1. Create a nuxt app with Vuetify.
2. Create a component that dynamically accepts image sources (as a prop, for example).
```html
    <img
      :src="require(`@/assets/${imageSrc}`)"
      :alt="imageAlt"
    >
```
4. Pass the dynamic prop to the component
```html
<my-component
  image-alt="Profile"
  image-src="profile.jpg" />
```

### What is Expected?
It should render the image dynamically, given it exists under the given directory (the assets directory, for example)

### What is actually happening?
It throws an error:
```bash
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):                                                                                                                       friendly-errors 14:17:19
SassError: This file is already being loaded.
  ╷
2 │ @import '~/assets/variables.scss';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  assets/variables.scss 2:9  root stylesheet
```

Apparently, the error goes away once you remove the `~/assets/variables.scss` import under the `~/nuxt.config.js` `vuetify` configuration.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
