### ISSUE TITLE
No error raised when non-existing layout is set

### ISSUE THREAD

**Issue by phanect** [nuxt/nuxt#10351]
When you set non-existing layout in pages by mistake, I expect Nuxt to raise an error so that you can find your mistake easily.
However, Nuxt does not raise any errors, and use default layout instead.

### Versions

- nuxt: v2.15.8
- node: v16.14.2

### Reproduction

https://github.com/phanect/repro-nuxt-layout

### Steps to reproduce

1. Create [layout/default.vue](https://github.com/phanect/repro-nuxt-layout/blob/main/layouts/default.vue) and [pages/index.vue](https://github.com/phanect/repro-nuxt-layout/blob/main/pages/index.vue)
2. Set non-existing layout in pages/index.vue (like `layout: "non-existing-layout"`, [repro](https://github.com/phanect/repro-nuxt-layout/blob/main/pages/index.vue#L10))
3. Run `npm run generate` (or `npx nuxt generate --fail-on-error`)

### What is Expected?

Error raised because you are trying to use non-existing layout

### What is actually happening?

The dist directory is generated successfully.
pages/index.vue extends layouts/default.vue instead of the non-existing layout.

**Comment by phanect** [comment]
Posting to keep this issue open.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by phanect** [comment]
Closing since this issue was not awared while Nuxt 2 was active version.
