### ISSUE TITLE
whether nuxt.js support different domain names to jump directly to different routes 

### ISSUE THREAD

**Issue by winterZhao** [nuxt/nuxt#10356]
I'd like to ask nuxt Does JS support different domain names to visit different pages

For example. I have a website https://atoolonline.com 。I want users to access https://www.atoolonline.com forward http://localhost:2333 ; User access https://localhost:2333/md5 When visiting https://md5.atoolonline.com。

But in fact, nginx configures proxy_ pass https://localhost:2333/md5 ; Error 404 will be reported in JS. 

When proxy_ pass https://localhost:2333/ If yes, it will jump to the home page, that is https://localhost:2333 。 This puts me in a dilemma.

This is my nginx conf 

```
    location / {      
       proxy_pass http://127.0.0.1:2333/md5;
    }
```

if I add md5 to location, Then all requests will be prefixed with MD5, which will inevitably lead to other resources 404。If 
I do not add MD5, you will inevitably jump to the home page。

could you please tell me what is right?

**Comment by danielroe** [comment]
This is supported in Nuxt 3 via `app/router-options`. For example, you can see https://zernonia.keypress.blog/why-keypress.
