### ISSUE TITLE
use Storage(like localStorage) have problem in test environment

### ISSUE THREAD

**Issue by ILfengzi** [nuxt/nuxt#10353]
in test environment, I use window.open(window.location.origin + myRouter) to create new page， the new page can not handle the same storage item

eg: A page ==> localStorage.setItem('youAreHandsome', true)
     ==> window.open(window.location.origin + '/B')
     ==> B page  localStorage.removeItem('youAreHandsome')

==>B page  localStorage.getItem('youAreHandsome')==>true

**Comment by ILfengzi** [comment]
已收到！

**Comment by ILfengzi** [comment]
已收到！

**Comment by danielroe** [comment]
This isn't related to Nuxt. You can find out more info on how localStorage works here: https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage.

You may also find joining https://discord.nuxtjs.org helpful, where you can ask questions of other developers who also use Nuxt.
