### ISSUE TITLE
publicRuntimeConfig variables on client side always equals undefined

### ISSUE THREAD

**Issue by nestle49** [nuxt/nuxt#10368]
### Versions

- nuxt: @nuxt/cli v2.15.8
- node: v12.22.10

### Reproduction
PROBLEM:
Env variables in publicRuntimeConfig sections works on server, but client always are undefined, **if use in vuex process.env**

CASE:
1. Fill .env file, for example:
TEST=1
2. store/index
```
if (process.browser) {
    console.log(process.env.TEST);
}
```
3. On server it works, but on client env.TEST is undefined
4. if use dotenv module, it works on server and client

It stops migrate from dotenv to native publicRuntimeConfig environments variables

**Comment by pghorpade** [comment]
@nestle49 
Are you defining publicRuntimeConfig in nuxt.config.js like this
publicRuntimeConfig: {
        testPublicenv: process.env.TEST,
       
    },
once you have this you can use 
nuxt config to access this like $config.testPublicenv

**Comment by nestle49** [comment]
> @nestle49 Are you defining publicRuntimeConfig in nuxt.config.js like this publicRuntimeConfig: { testPublicenv: process.env.TEST, }, once you have this you can use nuxt config to access this like $config.testPublicenv

It is begin of store/index.ts file.
I haven't access to $config here and can't use context. I can use only process.env, but on client process.env.example equal undefined

**Comment by pghorpade** [comment]
In vuex store you could use nuxtservereinit to access nuxt $config.

**Comment by nestle49** [comment]
No, I can't. It's outside hooks! In plugins!

```
if (debug) {
    pluginsBeforeExport.push(
        createLogger({
            // do not output on the server (because they're shitting)
            logMutations: process.browser && !process.env.VUEX_LOGGER_HIDE_MUTATIONS,
            logActions: process.browser && !process.env.VUEX_LOGGER_HIDE_ACTIONS
        })
    );
}

....

export const state = () => {
    return {};
};

....

NuxtServerInit
```

It's reason why i can't use nuxtServerInit, context, other hooks!
I can use only process.env here!

And it's work on server, but doen't work on client side for runtimePublicConfig, the same time it's correct work server and client for dotenv module

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
