### ISSUE TITLE
Two different routes having same route names causes conflict in router

### ISSUE THREAD

**Issue by Apperk274** [nuxt/nuxt#10363]
### Versions

- nuxt:  v2.15.7
- node: v14.18.1

<details open>
<summary>Additional Details</summary>
<br>
I found this workaround: Change the default routeNameSplitter in nuxt.config.js to another character (preferrably a character that cannot be used in urls e.g. "|" )
</details>

### Steps to reproduce

Create the following structure in the pages folder without changing the default routeNameSplitter ("-"):

project-root/
--| pages/
-----| first/second.vue
-----| first-second.vue

### What is Expected?

2 different page routes with paths: "/first/second" and "first-second"

### What is actually happening?

Can reach neither of the pages

**Comment by danielroe** [comment]
This can't be resolved without a breaking change for Nuxt 2 users, but a PR to add this workaround to the docs would be welcome.
