### ISSUE TITLE
Opt-out for payload.js generation on static websites

### ISSUE THREAD

**Issue by vloss3** [nuxt/nuxt#10367]
### Is your feature request related to a problem? Please describe.

I'd like to have a way to disable the payload.js generation for static websites, I have all the data saved in store so for my project it essentially just duplicates ~30kb of JS, and blocking time goes from 1ms -> 47ms.

### Describe the solution you'd like

A boolean to disable payload.js on generate, eg:
`
generate: {
  savePayload: false
}
`

**Comment by fago** [comment]
but it will need payload.js for client side navigation when using full static.
Problem is payload.js mutation data contains a copy of the initial state data. Instead of skiping payload.js data, maybe the state.js store data is not needed, since it's covered by the payload.js mutation?

**Comment by fago** [comment]
After digging a bit more into this, I think it should skip loading payload.js on initial load for routes where no page-data (asyncData, fetchState) got recored, but it's still needed to stay there for client-side navigation.

**Comment by danielroe** [comment]
I think you should be able to do this by removing `target: 'static'` and falling back on 'legacy generation'.

Note that in Nuxt 3 this is possible by setting `experimental.payloadExtraction` to `false`.
