### ISSUE TITLE
Dynamic loaded Async component event listener not work on SSR first rendered

### ISSUE THREAD

**Issue by serialine** [nuxt/nuxt#10361]
### Versions

- nuxt: 2.15.3
- node: stable

### Reproduction

https://stackblitz.com/edit/nuxt-starter-lzv1me?file=pages%2Findex.vue

### Steps to reproduce

`Index.vue`
```vue
<DynamicComp @click.native="handleClick" />

<script>
import DynamicComp from './DynamicComp.vue'
export default {
  components: { DynamicComp }
  methods: { handleClick() { window.alert('clicked') } }
}
</script>
```
`DynamicComp.vue`
```vue
<component is="AsyncComp" />

<script>
export default {
  components: { AsyncComp: () => import('AsyncComp.vue') }
}
</script>
```
`AsyncComp.vue`
```vue
<div>click me</div>
```

### What is Expected?

click event work first SSR rendered

### What is actually happening?

click event not works first SSR rendered, works only CSR rendered (wrap `<ClientOnly>` or change component key to re-render)
https://stackblitz.com/edit/nuxt-starter-lzv1me?file=pages%2Findex.vue

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
