### ISSUE TITLE
nuxt.js generate Bug

### ISSUE THREAD

**Issue by 188229624** [nuxt/nuxt#10374]
nuxt.js 在 nuxtConfig 中 配置自定义的router路由，清除pages自动生成的路由，使用generate打包后，只有index.htm生成

**Comment by xzfnn** [comment]
![image](https://user-images.githubusercontent.com/58756175/217502518-0a032472-b4c9-4e84-a555-dd900b9336a5.png)
nuxt打包后这个头部乱码，内容不乱，请问要在哪里配置

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by xzfnn** [comment]
> Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

![image](https://user-images.githubusercontent.com/58756175/217692811-c27d823f-3e4e-4e3a-90ea-c6854f41f853.png)
本地不乱码，但是放到服务器上面网页源码也是乱的

**Comment by danielroe** [comment]
When I say a reproduction, I'm hoping for something minimal that I can run either on stackblitz or locally to reproduce the issue.
