### ISSUE TITLE
Scrolling behaviour in Firefox

### ISSUE THREAD

**Issue by ayacheva** [nuxt/nuxt#10379]
### Versions

- nuxt:  2.15.8
- node: 16.x

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### What is actually happening?
Hi, guys, I am experiencing strange issue with a static website. I have some nuxt-links in the footer of the website and when I scroll down and try to use them, nuxt is not always scrolling to the top of the page. It happens only sometimes and only on Firefox. Do you have any idea what could be causing the issue? I am using the latest version of Firefox 99

**Comment by narduin** [comment]
This is likely the same issue as this one: https://github.com/nuxt/nuxt.js/issues/9515
The bug comes from the css `scroll-behavior: smooth`
