### ISSUE TITLE
SSG: Invalid route items cause broken static assets (e.g. `state.js`) for base route `/`

### ISSUE THREAD

**Issue by abernh** [nuxt/nuxt#10377]
### Preamble
As the title states the following problem is not actually a bug in Nuxt.
But because this has caused me months of headaches I wanted to share this problem with you and maybe it even results in an adjustment of the code base so that the problem can be avoided completely.

### The "bug"
With `target: "static"` a badly formed route submitted via `generate.routes()` in the config causes the index route `/` to be generated twice and due to a race condition the output to e.g. `static.js` is [written twice at the same time](https://stackoverflow.com/q/26517356/2182191) causing it to be a half-concatenated version of both outputs and therefore being completely broken and not parse-able later on.

There is no error in the build process and the bug is not happening consistently which makes it very hard to track down.

### The details
When using the configuration option `generate.routes()` there is no check done on the returned route array. 

But the generator expects during `decorateWithPayloads()` the route to be

https://github.com/nuxt/nuxt.js/blob/dfcc26e3b71a893ef04d49f9bd3adbbf235a0b15/packages/generator/src/generator.js#L297

In my case I missed to destructure an array of routes before I `splice`d it into my `routes` array.

```javascript
...,
generate: {
  async routes(){
    const routes = []

    await someAsyncApiCall().then(routeArr => {
      routes.splice(0, 0, routeArr) // should have been " ...routeArr"
    })

    return routes
  }, ...
}, ...
```
The problem comes up when the generator tries to "normalize" the route path for this bad formed route element.

https://github.com/nuxt/nuxt.js/blob/dfcc26e3b71a893ef04d49f9bd3adbbf235a0b15/packages/generator/src/generator.js#L298

Because the `route`is now an `Array` and not a `String` the variable `path` holds `undefined` and that results in the "normalized" route `/ ` and now we have the index route twice in the generated routes array.

### Versions

- nuxt: 2.15.8
- node: v14

### Steps to reproduce
 - default nuxt setup with demo template and setup with `target: "static"`
 - add the following to your `nuxt.config.js`
 
 ```
 generate: {
   routes(){ return [[]] }
 }
 ```
 - generate via "nuxt generate" 
 - test via "nuxt start"
 --> sometimes the state or payload is broken and the index page can not be loaded

### What is Expected?
If a badly formed route is pushed via `generate.routes()` there should be a warning.
Alternatively `path` should not try to normalize an `undefined` route but simply fail / throw an exception or (see below) `normalizeSlash` should only accept strings.

### What is actually happening?
Nothing.
The "bad" route is processed silently and sometimes the `state.js` or `payload.js` is messed up because the generator tries to write the same file twice at the same time

### Proposed fix
Update [`normalizeSlash()`](
https://github.com/nuxt/nuxt.js/blob/dfcc26e3b71a893ef04d49f9bd3adbbf235a0b15/packages/generator/src/generator.js#L285) not to accept anything but strings for the `route` paramter

```diff
  normalizeSlash (route) {
+    if(!isString(route)){
+      throw Error('Expect route to be of type string, not ' + typeof route)
+    }     
    return this.options.router && this.options.router.trailingSlash ? withTrailingSlash(route) : withoutTrailingSlash(route)
  }
```

**Comment by abernh** [comment]
I just fell again in that trap. This time I used `path` instead of `route` in my extended-route-array items and without any error I encountered the broken `state.js` file again.

```JS
//# nuxt.config.js
...,
generate: {
  routes(){ return [{
    path: '/info/:id', // <-- BAD
//  route: /info/blueberries', // <-- should be `route` and a full path instead
    payload: {id: 'blueberries'}
  }] }
},
...
```

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
