### ISSUE TITLE
Add cache busting config to nuxt config

### ISSUE THREAD

**Issue by Shalashtein** [nuxt/nuxt#10386]
### Is your feature request related to a problem? Please describe.

I run NuxtJs in production, and I always have an issue with old versions of the site being cached, especially when major changes have been I'd have to tell users to clear their cache to see the new version of the site that includes the bug fixes they've asked for

### Describe the solution you'd like

Cache busting should be as simple as flipping a boolean with some minor config parameters

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
