### ISSUE TITLE
内联 CSS 时，TaiwindCSS 会打包两次

### ISSUE THREAD

**Issue by xbf321** [nuxt/nuxt#10381]
nuxt.config.js 中，不配置提取 CSS 到单独文件。

但应用 TailWindCSS 时，即向 html 中注入内联的 CSS ，同时在打包 js 中也会出现同样的CSS，在运行时注入到 header 中。

请问这个问题如何解决？

预期：不在 js 中包含重复的 css 。

Nuxt版本：2.15.4

tailwind.config.js 配置如下：
```
const path = require('path');
module.exports = {
  mode: 'jit',
  purge: {
    enabled: true,
    content: [
      path.join(__dirname, './src/app.html'),
      path.join(__dirname, './src/**/*.vue'),
    ],
    options: {
      whitelist: ['html', 'body', 'nuxt-progress'],
    },
  },
};
```

**Comment by danielroe** [comment]
This is a feature of Nuxt 2 - inlining CSS needed to render the page, but including it also in JS for subsequent navigations. You can enable extractCSS to disable this behaviour.
