### ISSUE TITLE
immediate async watchers are run, but effect not present in generated output of 'nuxt generate'

### ISSUE THREAD

**Issue by Fabioni** [nuxt/nuxt#10385]
### Versions

- nuxt: v2.15.18
- node: v16.14.0

### Reproduction

component that show `foo` in the template with 
```js
  data() {
    return {
      foo: "foo_data",
    };
  },
  props: {
    blok: {
      type: Object,
      required: true,
    },
  },
  watch: {
    "blok": {
      handler: async function (val, oldVal) {
        console.log("handler is run");
        //do some api call that needs time
        this.foo = "foo_watcher";
      },
      immediate: true,
    },
  },
```

### Steps to reproduce

Now after nuxt generate I get the console logs `"handler is run"` but the generated files show "foo_data" and not "foo_watcher"

### What is Expected?

Nuxt generate should wait for the async immediate watcher to finish before recording the generated output.

### What is actually happening?

I think nuxt generate just *records* the generated output before the watcher function finishes.

**Comment by Fabioni** [comment]
Workaround:

don't use immediate but call the watcher function in async fetch.

```js
  data() {
    return {
      foo: "foo_data",
    };
  },
  props: {
    blok: {
      type: Object,
      required: true,
    },
  },
  watch: {
    "blok": {
      handler: async function (val, oldVal) {
        this.whatever(val, oldval)
      },
      //immediate: true,
    },
  },
  async fetch(){
    await this.whatever("...", undefined);
  },
  methods: {
    async whatever(val, oldval){
        console.log("whatever is run");
        //do some api call that needs time
        this.foo = "foo_watcher";
    }
  }
```

**Comment by marianoweber** [comment]
@Fabioni 
I rebuilt exactly what you did and after running `nuxt generate` and `nuxt start` it worked as expected.
How did you run your generated content?

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
