### ISSUE TITLE
Error icon has been mispositioned

### ISSUE THREAD

**Issue by nemorize** [nuxt/nuxt#10392]
### Is your feature request related to a problem? Please describe.
![스크린샷 2022-04-18 오전 12 20 29](https://user-images.githubusercontent.com/51209191/163721097-c41bbb95-893c-4b15-aedf-4e696613eb26.png)

Error icon is on the left.

### Describe the solution you'd like
![스크린샷 2022-04-18 오전 12 23 11](https://user-images.githubusercontent.com/51209191/163721117-d36c6d7a-8ddf-4617-a15e-46ba0baccc78.png)

Error icon should on the center.

### Additional context

Nah;

**Comment by danielroe** [comment]
I can't reproduce this. Please do feel free to provide a reproduction and I'll have a look.
