### ISSUE TITLE
loader: 'ES2020' return error

### ISSUE THREAD

**Issue by andysay** [nuxt/nuxt#10407]
* /root/pax/.nuxt/client.js in multi ./node_modules/eventsource-polyfill/dist/browserify-eventsource.js (webpack)-hot-middleware/client.js?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js
  
from nuxt.config.js
```


 build: {
        extend(config, { isDev, isClient }) {
      // ..
      config.module.rules.push({
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loader: 'ES2020'
      })
      // Sets webpack's mode to development if `isDev` is true.
      // if (isDev) {
      //   config.mode = 'development'
      // }
    }
}
```

Cannot find module '/root/pax/.nuxt/server.js'

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
