### ISSUE TITLE
Cannot print page in Safari

### ISSUE THREAD

**Issue by wtpalexander** [nuxt/nuxt#10404]
### Versions

- nuxt: 2.15.8
- node: 16.14.2
- macOS: 12.3
- Safari: 15.4

### Reproduction

Attempt to print a page using any of these buttons in Safari:
```
<template>
  <div>
    <button onclick="window.print()">Print</button>
    <button @click="window.print()">Print</button>
    <button @click="print()">Print</button>
  </div>
</template>

<script>
export default {
  methods: {
    print() {
      window.print()
    },
  },
};
</script>
```

<details open>
<summary>Additional Details</summary>
See this [link](https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_print) for the example code which works in basic HTML.
</details>

### Steps to reproduce
Tap the print button added to any Nuxt page.

### What is Expected?
Safari will open the system print dialog with the page ready to print.

#### `<button onclick="window.print()">Print</button>`
Works fine in vue, but nothing happens in Nuxt
#### `<button @click="window.print()">Print</button>`
This error is shown: 'undefined is not an object (evaluating '_vm.window.print')`.
#### `<button @click="print()">Print</button>`
Nothing happens. My thoughts are that this is since Safari requires the print function to be called directly by the button.

**Comment by marianoweber** [comment]
Did you only try this in dev mode?
After building solutions one and three work as expected. 
That has something to do with the window context in dev mode.

**Comment by wtpalexander** [comment]
Yes agreed - appears to be a dev mode issue only!

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
