### ISSUE TITLE
After nuxt static mode is packaged, use live-server to run under ie9 and refresh infinitely

### ISSUE THREAD

**Issue by liuweiyibai** [nuxt/nuxt#10401]
### Versions

- nuxt: v2.15.8
- node: v14.17.6

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce

Create a new project with the script on the document, Then use `yarn generate` to generate static files, then open with `live-server ./dist`,Then use the ie9 browser to check in, the page has been refreshed infinitely

### What is Expected?

Hope it can be accessed normally in ie9 mode

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/9730
