### ISSUE TITLE
[minor issue] I am not able to read links from the documentation

### ISSUE THREAD

**Issue by carlotm** [nuxt/nuxt#10409]
### Versions

- nuxt: v3

### Steps to reproduce

Visit https://v3.nuxtjs.org/guide/concepts/introduction/ on a light theme mode.

### What is Expected?

The links text does pass the minimux contrast diff defined by WCAG

### What is actually happening?

I am struggling reading the content of those links.
The green used does not pass contrast diff with the white background.

![Screenshot_2022-04-27_07-42-02](https://user-images.githubusercontent.com/64407038/165448969-e26ae33e-22f3-47ef-a44d-de56b3231926.png)

**Comment by danielroe** [comment]
I believe this is resolved.
