### ISSUE TITLE
Some CSS rules removed by PostCSS

### ISSUE THREAD

**Issue by jsakalos** [nuxt/nuxt#10410]
The bug was discovered by a user of [Bryntum Scheduler](https://www.bryntum.com/products/scheduler/) and reported it in [this forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=21016).

However, it can be easily reproduced w/o Bryntum libraries by adding the following styles to `index.vue` of the application newly created by `npx create-nuxt-app`:

```
pages/index.js:

<style>
  .logo {
    margin-inline-end:1em;
    border:10px solid red;
  }
</style>
```

That results in the markup shown on the screenshot-1:
<img width="1076" alt="screenshot-1" src="https://user-images.githubusercontent.com/204844/165484473-9c2f8753-d095-4f86-8c00-2d1e00c84c14.png">

It can be remedied by disabling PostCSS but that's not a real fix, just a workaround:
```
nuxt.config.js:

  build: {
    postcss: false
  }
```

That leads to the expected result on the screenshot-2:
<img width="1074" alt="screenshot-2" src="https://user-images.githubusercontent.com/204844/165484999-ea0c889f-8779-4bb1-a0f0-1464e395004e.png">

I'm also attaching the showcase application.
[nuxt.zip](https://github.com/nuxt/nuxt.js/files/8570669/nuxt.zip)

**Comment by marianoweber** [comment]
This behavior has something to do with how postcss processes rules according to their cssdb stages.

[Logical Properties and Values](https://cssdb.org/#logical-properties-and-values)
are considered "unstable and subject to change" (e.g. stage 2)

Following changes to `nuxt.config.js` will make these rules work:

```
nuxt.config.js

build: {
  postcss: {
    preset: {
      features: {
        stage: 2,
        'logical-properties-and-values': false
      }
    }
  }
}
```

Source: [https://stackoverflow.com/questions/64565180/how-to-prevent-postcss-preset-env-from-removing-css-logical-properties](url)

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
