### ISSUE TITLE
Accessing getters from different modules inside actions blocks execution

### ISSUE THREAD

**Issue by nhh** [nuxt/nuxt#10417]
### Versions

- nuxt: ^2.15.7
- node: v14.16.0

### Steps to reproduce

1. Write two modules auth.js and messages.js
2. Write a getter inside one module
3. Access cross-module getters like this:

```js
console.log(context.getters["mod1/getter1"]["some"]["data_that_does_not_exist"])
console.log("I will never be printed")
```

### What is Expected?

Accessing cross modules without `rootGetter` should throw an error like "Cannot access root getter from scoped module".

### What is actually happening?

The whole execution is being blocked, everything after this code wont be executed

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
