### ISSUE TITLE
Multi-zones in Nuxt.js

### ISSUE THREAD

**Issue by alisanie** [nuxt/nuxt#10415]
Hi

Multi Zone is helping to separate large nextjs application into small applications.The benefit of using this feature is separate teams and they can work together without  interfere with each other codes.

Is there any plan to have and idea like Multi Zone in nuxtjs or any idea to implement it to nuxtjs app.

Thanks 🙏

**Comment by danielroe** [comment]
This is now implemented with the extends/layouts feature in Nuxt 3: see https://github.com/nuxt/framework/issues/3222 and https://nuxt.com/docs/getting-started/layers#layers.
