### ISSUE TITLE
能否在nuxt.config.js增加开关来控制是否要在页面上写入<base href="{{ router.base }}"/>

### ISSUE THREAD

**Issue by gogochiken** [nuxt/nuxt#10412]
从2.13.0起，在nuxt.config.js设置了router.base后会自动在head中写入<base href="{{ router.base }}"/> ，假设 router.base设置为"/" ，

那么在点击 路径 /something 下的a标签，例如《a href="#abc"》TEST《/a》会跳转到 /#abc ， 这样造成页面刷新。

能否在nuxt.config.js增加开关来控制是否要在页面上写入base href， 让开发者自己控制是否需要此标签

many thanks!!!

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
