### ISSUE TITLE
browser render error content of chinese path when static mode

### ISSUE THREAD

**Issue by cellargalaxy** [nuxt/nuxt#10428]
### Versions

- nuxt: v2.15.8
- node: v16.14.0

### Reproduction

I try to use nuxt to build a blog. Using markdown to render html.

I found that if path contain chinese, browser will render html by default value of component instead of markdown.

### Steps to reproduce

I created a page with path contain chinese, browser will render html by default value of component.

At first I suspected that url encoding has some problem, I tried url encoding and decoding the path, but problem not solved.

Later, I suspected that markdown content writed error. But same markdown content was rendered in chinese or english path. English work, chinese not work.

+ `https://cellargalaxy.github.io/blog-vue/view/%E6%A0%87%E9%A2%98_markdown/`, path contain chinese, error render page
+ `https://cellargalaxy.github.io/blog-vue/view/$E6$A0$87$E9$A2$98_markdown/`, same markdown, english path
+ `https://github.com/cellargalaxy/blog-vue/`, code repository

### What is Expected?

If path contain chinese, browser will render html by default value of component instead of markdown.

### What is actually happening?

Browser render html using the value of father component.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
