### ISSUE TITLE
Allow setting the loadIndicator per page/layout

### ISSUE THREAD

**Issue by ibdf** [nuxt/nuxt#10421]
### Is your feature request related to a problem? Please describe.

Right now the loadingIndicator (client side) is set in the nuxt.config, which is applied on every route change. There does not seem to be a way to change this option or simply disable it on a per page/layout/route basis.

### Describe the solution you'd like
Follow the same pattern as the "loading" option  (progress bar) and let this option be set in a page, layout or router middleware.

in a page.vue or layout.vue allow:
```
loadingIndicator: {} //some config
or
loadingIndicator: false;
```

### Describe alternatives you've considered
Alternatively have a way to disable it in the router middleware, or in the app.html template, or via lifecycle hook.

### Additional context
This problem came about when using chrome in headless mode for taking screenshots. At times the loading animation is screenshotted instead of the rendered page. This happens even though chrome is set to await for the dom event document loaded, and it also awaits for networkidle. The short-term solution is to make chrome await a set amount of time before taking the screenshot.

**Comment by danielroe** [comment]
This is now granularly possible using the `useLoadingIndicator` in Nuxt 3.
