### ISSUE TITLE
NUXT_HOST env usage type error

### ISSUE THREAD

**Issue by vilyansky** [nuxt/nuxt#10430]
### Versions

- nuxt: 2.15.8
- node: 18.1.0

### Reproduction

1. Create minimal nuxt application - like this [https://nuxtjs.org/docs/get-started/installation](url)
2. Dockerize it - like this [https://dockerize.io/guides/docker-nuxtjs-guide](url)
3. set NUXT_HOST environment variable to 0.0.0.0

result:
```
/app # env
NODE_VERSION=18.1.0
HOSTNAME=3bc2597bb451
YARN_VERSION=1.22.18
SHLVL=2
HOME=/root
NUXT_HOST=0.0.0.0
NODE_OPTIONS=--openssl-legacy-provider
NUXT_PORT=3000
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/app

/app # npm run start

> nuxt-express@1.0.0 start
> nuxt start


 FATAL  details.family.toLowerCase is not a function                                         15:06:24

  at node_modules/ip/lib/ip.js:385:39
  at Array.filter (<anonymous>)
  at node_modules/ip/lib/ip.js:384:37
  at Array.map (<anonymous>)
  at ip.address (node_modules/ip/lib/ip.js:379:37)
  at Listener.computeURL (node_modules/@nuxt/server/dist/server.js:469:60)
  at Listener.listen (node_modules/@nuxt/server/dist/server.js:510:10)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Server.listen (node_modules/@nuxt/server/dist/server.js:973:5)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-start.js:124:5)


   ╭─────────────────────────────────────────────────────────────╮
   │                                                             │
   │   ✖ Nuxt Fatal Error                                        │
   │                                                             │
   │   TypeError: details.family.toLowerCase is not a function   │
   │                                                             │
   ╰─────────────────────────────────────────────────────────────╯
```
5. unset NUXT_HOST variable
```
/app # unset NUXT_HOST
/app # env
NODE_VERSION=18.1.0
HOSTNAME=3bc2597bb451
YARN_VERSION=1.22.18
SHLVL=2
HOME=/root
NODE_OPTIONS=--openssl-legacy-provider
NUXT_PORT=3000
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/app
/app # npm run start

> nuxt-express@1.0.0 start
> nuxt start


   ╭────────────────────────────────────────╮
   │                                        │
   │   Nuxt @ v2.15.8                       │
   │                                        │
   │   ▸ Environment: production            │
   │   ▸ Rendering:   server-side           │
   │   ▸ Target:      server                │
   │                                        │
   │   Memory usage: 33 MB (RSS: 83.2 MB)   │
   │                                        │
   │   Listening: http://localhost:3000/    │
   │                                        │
   ╰────────────────────────────────────────╯
```

**Comment by alisspers** [comment]
I had the same problem locally with Node v18. Works fine when downgraded to Node v16.

**Comment by IksanAR** [comment]
> I had the same problem locally with Node v18. Works fine when downgraded to Node v16.

ya it works for me to solve this issue

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
