### ISSUE TITLE
Resolve layout from subfolder in the layouts folder

### ISSUE THREAD

**Issue by romeomihalovics** [nuxt/nuxt#10433]
Hi!

Please make the builder able to resolve layouts from subfolders in the layouts folder.

currently it's only able to resolve .vue files which are directly under the layouts folder, e.g.:
```
root/
  layouts/
    default.vue
```

in the pages folder, the builder is able to resolve paths like this as well:
```
root/
  pages/
    about/
      index.vue
```

would it be possible to make the layout resolving to behave similarly?

**Comment by romeomihalovics** [comment]
Also, it would be nice (as it's not possible at the moment as far as I know) to make the "index.vue" file, under the pages folder parsed like this as well, and not hardcoded in.

The reasoning behind this is that it would allow a much nicer project structure, and would allow separating the js / ts and styling files from the template files [which is pretty recommended in my opinion for heftier projects]

**Comment by louia** [comment]
any updates ?

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
