### ISSUE TITLE
Nuxt2 axios CancelToken WARN Cannot stringify arbitrary non-POJOs CancelToken

### ISSUE THREAD

**Issue by n0ch4t** [nuxt/nuxt#10437]
### Version

- nuxt: ^2.15.8
- node: v16.13.2
- @nuxtjs/axios : ^5.13.6

### Reproduction

Sample repo : https://github.com/n0ch4t/nuxt2-non-POJOs
Code SandBox: https://codesandbox.io/s/brave-wildflower-3mvbu6?file=/pages/index.vue

### Steps to reproduce

The following warn log occurs when accessing the top-level address after running the sample project.
refresh 

**======================================================
 WARN  Cannot stringify arbitrary non-POJOs CancelToken

 WARN  Cannot stringify a function cancel
======================================================**

### What is Expected?

Warn logs should not occur.

**Comment by danielroe** [comment]
the issue here is that you are trying to set something which can't be serialised. Instead, ensure that any property of your component that you are setting in `fetch()` is serialisable.
