### ISSUE TITLE
Nuxt stops after using mongoose method

### ISSUE THREAD

**Issue by ilijanovic** [nuxt/nuxt#10445]
### Versions

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v14.17.6`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `npm@8.9.0`
- Builder:          `vite`
- User Config:      `buildModules`, `build`, `css`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

In my app, i using mongoose https://mongoosejs.com/.

Whenever i run this query:

```
    await Author.updateOne(
      { _id: authorId },
      {
        $push: {
          tempImages: {
            ...image,
          },
        },
      }
    );
```

My Nuxt app just stops. No error, nothing. It just stopped. Whenevery i insert something into my database, i have to reload my app. This is really annoying.

The query is fine, it works. My data gets inserted into the DB. Just my nuxt app stops.

**Comment by Jopchumba** [comment]
@ilijanovic it's hard to reproduce please give more context anyways.
 Think of it this way Nuxt is a frontend framework and most of the time you will need to fetch data probably by using a click event or watch functions. My suggestion would be to try to use Axios or fetch and handle the errors if they occur.

**Comment by ilijanovic** [comment]
> @ilijanovic it's hard to reproduce please give more context anyways. Think of it this way Nuxt is a frontend framework and most of the time you will need to fetch data probably by using a click event or watch functions. My suggestion would be to try to use Axios or fetch and handle the errors if they occur.

Its not related to mongodb. It actually happens when you write a new file to one of your folder, like `image.jpg` then it suddenly stops. I guess it has something to do with Vite

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
