### ISSUE TITLE
Nuxt 2 Broken Typescript Typings when Specifying head

### ISSUE THREAD

**Issue by tokidoki11** [nuxt/nuxt#10468]
### Versions

- nuxt: 2.15.8
- @nuxt/types: 2.15.8
- Visual Code Studio + Vetur

### Reproduction
I currently implementing nuxt + typescript via Vue.extend

When creating head function that returns MetaInfo, the typings of default items in vue instance ($el, $mount, blablabla) become any
<img width="357" alt="image" src="https://user-images.githubusercontent.com/7564844/170006203-d93ab2ad-2ddd-43ce-9b44-9eae9b28baa4.png">

But when implementing the head as a member of JSON type or function that returns MetaInfo the typings are working as expected

<img width="317" alt="image" src="https://user-images.githubusercontent.com/7564844/170007116-fbac0c02-c4b5-411b-88d7-5625433a3432.png">
<img width="346" alt="image" src="https://user-images.githubusercontent.com/7564844/170006905-84f12d96-c976-4909-8264-5196f97b4a25.png">

More info
head is indeed written like a member of JSON type or function that returns MetaInfo 
I tried to change it similar to asyncData and restarted the Vetur
It is still no good
<img width="518" alt="image" src="https://user-images.githubusercontent.com/7564844/170007627-54a5e756-9554-46ef-adc8-f4d9ab28d779.png">

### What is Expected?
Typings should be the one as stated in Vue

### What is actually happening?
typings becomes any

@nuxt/types redirects me here, so i think the project is managed by the same team
kindly refer me to the appropriate room if this is a mistake

**Comment by tokidoki11** [comment]
https://nuxtjs.org/docs/components-glossary/head/

One thing I found out Nuxt use hid in metaInfo meta instead vmid which is not available
merging metainfo type will fix this



```
declare module 'vue-meta/types/vue-meta' {
  interface MetaDataProperty {
    hid: string
  }
}
```

**Comment by danielroe** [comment]
With the latest updates on 2.x, this is no longer replicable for me. Let me know if you still experience it with v2.16.3 after its release later today and I'll happily reopen.
