### ISSUE TITLE
Improve coding performance

### ISSUE THREAD

**Issue by littlegreay** [nuxt/nuxt#10462]
test('removed when not loading', async () => {
    const str = await renderToString(Component)
    expect(str).toBe('')
  })

after build the project,The source code contains a large number of <! --- >,

test('removed when not loading', async () => {
    const str = await renderToString(Component)
if(str ) {
expect(str).toBe('')
}
    
  })

**Comment by manniL** [comment]
> after build the project,The source code contains a large number of <! --- >,

These are placeholders for components not rendered due to v-if but are necessary and act as placeholders

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
