### ISSUE TITLE
asyncData not using server-fetched data when no preceeding slashes in nuxt-config generate

### ISSUE THREAD

**Issue by HalfBloody** [nuxt/nuxt#10469]
### Versions

- nuxt: v2.15.8
- node: v16.4.2

### Reproduction

Static Nuxt with with is supposed to fetch asyncData on a dynamic page. It doesn't work when the preceeding slash is missing.

Instead I can see the server-fetched data flicker for a second and then no data is displayed for a generated route missing the preceeding slash.
```
// nuxt.config.js

...
target: static,
generate: {
  routes: [
    '/with-preceeding-slash',
    'without-preceeding-slash'
  ]
}
```

```
// pages/_dynamic_page.vue
...
async asyncData(context) {
  let response = await context.$axios.get('articles')
  return { articles: response.articles }
}
...
```

### What is Expected?
Both dynamic routes would fetch the data in `asyncData`.

### What is actually happening?
In development everything works with and without slash in front of the route.

In production however, only `/with-preceeding-slash` uses the serverside-fetched data correctly. In `without-preceeding-slash` dynamic route I see the prefetched data for a second and then it disappears and no data is displayed.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
