### ISSUE TITLE
nuxt-link导航客户端渲染调用接口404

### ISSUE THREAD

**Issue by lcnoobmystery** [nuxt/nuxt#10464]
### Versions

- nuxt:  v2.15.8 
- node:  v14.17.0 

### Steps to reproduce

1、服务端渲染列表完成后。
2、通过 nuxt-link 导航到详情页，详情页客户端渲染调用接口获取数据。
3、当我未设置 extendRoutes 时接口返回 404，数据为nuxt 默认404界面 。
4、当我设置 extendRoutes 后接口返回 200，数据为我设置的404界面。

不是一直存在这种情况，只是有几率。

### What is Expected?

正常客户端渲染接口获取数据并渲染界面。

### What is actually happening?

```
pages/
--| article/
-----| _articleId.vue
--| index.vue
```

```
<nuxt-link :to="{ name: 'article-articleId', params: {articleId: item.articleId} }">
</nuxt-link>
```

```
async fetch () {
      const { articleId } = this.$route.params
      if (!articleId) {
        this.$router.push('/')
        return
      }
      const { status, data } = await this.$axios.get(`/articles/detail?articleId=${articleId}`)
      if (status === 200) {
          this.articleDetail = data?.data || {}
      }
  }
```

事实上确实调用了客户端渲染接口获取数据，但是返回404（服务端渲染好的 nuxt 默认404界面）（不出现这种情况时能正常获取数据），当我设置
```
extendRoutes (routes, resolve) {
      routes.push({
        name: '404',
        path: '*',
        component: resolve(__dirname, 'layouts/NotFound.vue')
      })
    }
```
此时出现这种情况时接口中返回我设置的界面，我只能强制刷新来让它恢复正常，当我试着用 a 来替换 nuxt-link 只进行服务端渲染而不进行客户端渲染这不是我想要的结果。

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
