### ISSUE TITLE
After I installed DiasyUI in large project with NuxtJS I got ERROR (Javascript heap out of memory)

### ISSUE THREAD

**Issue by MuhammadMoftah** [nuxt/nuxt#10470]
### Versions

- nuxt: V2
- node: V16.14

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### What is Expected?
just need the project to keep running 

### What is actually happening?
After I installed DiasyUI in large project with NuxtJS I got ERROR (JavaScript heap out of memory)
like every 15 mints
and I should do yarn dev the project again

any help !

**Comment by danielroe** [comment]
There's not enough information to resolve this issue. If you can provide a minimal reproduction we could look into it, but this may not be caused by Nuxt.
