### ISSUE TITLE
Router hooks not invoked in middleware when link with target _blank used

### ISSUE THREAD

**Issue by Aybee5** [nuxt/nuxt#10481]
I am trying to access `app.router.beforeResolve` in nuxt middleware, which is succeding, but if the said link is open with `target="_blank"`, the function is not being invoked. 

### Versions

- nuxt: v2.15.3

### Reproduction
https://codesandbox.io/s/great-stonebraker-q3fdfd

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
Create a middleware and register it in nuxt.config.js router option, use a normal nuxt-link to open a page, create another and use `target="blank"`

```
export default function ({ app }) {
  app.router.beforeResolve((to, from, next) => {
     console.log({ to, from }); 
     next();
   });
 }
```

`<nuxt-link to="/about" target="_blank">About</nuxt-link>`

### What is Expected?
The code inside the middleware to execute

### What is actually happening?
Nothing

**Comment by rchl** [comment]
This is obviously not supposed to work. Newly opened tab will not be trigger router hook in the current page since it's completely separate page load.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️
