### ISSUE TITLE
Asyncdata is executed twice when switching pages

### ISSUE THREAD

**Issue by 123KITTY** [nuxt/nuxt#10487]
### Versions

- nuxt: v2.15.8.0
- node: v14.19.1

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>
Asyncdata is executed twice when switching pages
</details>

### Steps to reproduce
Asyncdata is executed twice when switching pages，

### What is Expected?
Asyncdata is executed one time when switching pages

### What is actually happening?
Asyncdata is executed twice when switching pages

**Comment by danielroe** [comment]
If you're still experiencing this, feel free to add a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction) and I'll reopen.
