### ISSUE TITLE
Lot's of deprecation warning after fresh create-nuxt-app

### ISSUE THREAD

**Issue by mrleblanc101** [nuxt/nuxt#10490]
Run nuxt start with the configuration below.
There is lot's of deprecation warning from npm.
<img width="1912" alt="Capture d’écran, le 2022-06-09 à 21 22 28" src="https://user-images.githubusercontent.com/17392251/172971522-3c3e7fba-ba47-40ee-bd58-3cbc64611a5d.png">
<img width="1800" alt="Capture d’écran, le 2022-06-09 à 21 22 22" src="https://user-images.githubusercontent.com/17392251/172971524-6cbc04e2-a7e5-4966-822a-de880750cac7.png">
<img width="1594" alt="Capture d’écran, le 2022-06-09 à 21 13 05" src="https://user-images.githubusercontent.com/17392251/172971525-e029078f-174f-4151-b210-b679b8852257.png">

**Comment by danielroe** [comment]
With the release of 2.16.0, we've upgraded quite a lot (as much as we can without breaking support for Node 14 + webpack 4). But sadly webpack 4 depends on quite a lot of these deprecated packages, which we can't resolve in Nuxt 2.

**Comment by mrleblanc101** [comment]
@danielroe Thanks, even if it's late. I recently moved to Nuxt 3 and I have a similar issue.
Not deprecation warning, but hundred of annoying info log from `yarn`.
Any idea why ? I'll probably open a new issue for this:
<img width="968" alt="Capture d’écran, le 2023-02-17 à 00 25 39" src="https://user-images.githubusercontent.com/17392251/219556939-83551957-012b-4006-8659-c0e08a452178.png">
