### ISSUE TITLE
async 获取到的数据通过return 在template上使用 ts提示错误

### ISSUE THREAD

**Issue by jiahui336** [nuxt/nuxt#10491]
类型“object & Record<never, any> & { info: string; } & Vue”上不存在属性“users”。ts(2339
![1654849886232](https://user-images.githubusercontent.com/54309037/173025217-c777bd5c-8e11-4815-b9eb-0b07156cb945.jpg)
)

**Comment by davinma** [comment]
Hi, jiahui336. You can try it like this:

```html
<script lang="ts">
import { defineComponent } from '@nuxtjs/composition-api'
import { listCompanyApi } from '~/common/api'

interface UsersItem {
  id: string
  name: string
}

export default defineComponent({
  name: 'IndexPage',
  layout: 'navigation',
  async asyncData() {
    const { data } = await listCompanyApi()
    this.users = data
  },
  data() {
    return {
      info: '这是info',
      users: [] as UsersItem[]
    }
  }
})
</script>
```

And, `UsersItem` is just an example, it depends on the data structure returned by your `listCompanyApi()`.

**Comment by manniL** [comment]
Can't reproduce anymore. https://stackblitz.com/edit/nuxt-issues-10491
