### ISSUE TITLE
Issue with Nuxt & DaisyUI (JavaScript heap out of memory)

### ISSUE THREAD

**Issue by MuhammadMoftah** [nuxt/nuxt#10495]
### Versions

- nuxt: 2.15.7
- node: +14

### Reproduction

after I installed DaisyUI [DaisyUI](https://github.com/saadeghi/daisyui)
like every 3 hours of working the nuxt server is down and console print error `JavaScript heap out of memory`
I tried this in multilabel projects and same result 

<details open>
<summary>Additional Details</summary>
<br>

</details>

### What is Expected?
buildling server should work well

**Comment by danielroe** [comment]
Closing as there is no minimal reproduction.
