### ISSUE TITLE
Unable to set `publicPath` when using `worker-loader` with webpack

### ISSUE THREAD

**Issue by scmmishra** [nuxt/nuxt#10516]
### Versions

- nuxt: v2.15.0
- node: v14.19.1

### Reproduction

https://github.com/scmmishra/data-worker-loader-bug

<details open>
<summary>Additional Details</summary>
<br>

[Worker loader `publicPath` docs](https://v4.webpack.js.org/loaders/worker-loader/#publicpath)

```js
export default {
  head: {
    title: "Nuxt.js starter for CSB",
    meta: [
      { charset: "utf-8" },
      { name: "viewport", content: "width=device-width, initial-scale=1" },
      {
        hid: "description",
        name: "description",
        content: "Official Nuxt.js starter for CodeSandBox"
      }
    ],
    link: [{ rel: "icon", type: "image/x-icon", href: "/favicon.ico" }]
  },

  components: true,
  plugins: ["~/plugins/worker.client.js"],
  build: {
    // publicPath: "https://cdn.nuxtjs.org/",
    extend(config, { isClient }) {
      config.output.globalObject = "this";

      if (isClient) {
        config.module.rules.push({
          test: /\.worker\.(c|m)?js$/i,
          use: [
            {
              loader: "worker-loader",
              options: {
                publicPath: "/worker-not-from-default/"
              }
            }
          ],
          exclude: /(node_modules)/
        });
      }
    }
  }
};
```

</details>

### Steps to reproduce

1. Build the repository and run `nuxt start`
2. Open the terminal to find the data worker in the network tab, see where it is loaded from

### What is Expected?

We expect it to be loaded from the specified `publicPath`. For the reproduction link provided, the path should be `/worker-not-from-default/` but it is still served from default public path

### What is actually happening?

The `publicPath` provided in the [property build is being used](https://github.com/scmmishra/data-worker-loader-bug/blob/7bfc20d3fe7e283d6a968bb35a68fc9e2041199e/nuxt.config.js#L23), instead of the [one specified in the loader options](https://github.com/scmmishra/data-worker-loader-bug/blob/7bfc20d3fe7e283d6a968bb35a68fc9e2041199e/nuxt.config.js#L30-L37)

### Why is this bug problematic

All JS assets are served via a CDN, like `cdn.nuxtjs.org` but workers cannot be served from a different domain.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
