### ISSUE TITLE
nuxt start this node process，As time goes on (or the number of visits increases), more and more memory is used

### ISSUE THREAD

**Issue by galaxy-s10** [nuxt/nuxt#10539]
### Versions

- nuxt: v2.15.3 
- node: v14.19.1

### Reproduction

this is my blog: [https://hsslive.cn/](https://hsslive.cn) ,memory leak is happen it

fitst start,memory useage is small
2022/6/23 15:30:00: node /node/nuxt-blog-client/node_modules/.bin/nuxt start memory useage:3.0%
...
but memory usage will more and more
2022/6/25 15:30:00: node /node/nuxt-blog-client/node_modules/.bin/nuxt start memory useage:45%

### Steps to reproduce

I suspect so fetch or asyncData cause memory leak？i no use nuxtServerInit

### What is Expected?

no memory leak 

### What is actually happening?

memory leak

**Comment by galaxy-s10** [comment]
i has a friend，his project is nuxt too，also have this problem

**Comment by galaxy-s10** [comment]
Does anyone encounter similar problems，The source code is here: https://github.com/galaxy-s10/nuxt-blog-client

**Comment by galaxy-s10** [comment]
@antfu ,大佬请问下nuxt2会有啥地方会导致内存泄漏吗，我nuxt部署的博客随着时间或者访问量的增加，nuxt start这个node进程占用的内存就一直增加，原本刚启动是占了3%内存，后面过一两天就占了4,50%内存，导致服务器内存不足卡死，

**Comment by tanglongyan** [comment]
> @antfu ,大佬请问下nuxt2会有啥地方会导致内存泄漏吗，我nuxt部署的博客随着时间或者访问量的增加，nuxt start这个node进程占用的内存就一直增加，原本刚启动是占了3%内存，后面过一两天就占了4,50%内存，导致服务器内存不足卡死，

请问问题解决了吗？我现在使用的nuxt3 将项目build后通过PM2启动后，也是进程的内存占用率会随着页面的访问量明显上升

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

**Comment by hucoooo** [comment]
> > ，大佬请问下nuxt2会有啥地方会导致内存泄漏吗，我nuxt部署的博客随着时间或者访问量的增加，nuxt start这个node进程占用的内存就一直增加，原本刚启动是占了3%内存，后面过一两天就占了4,50%内存，导致服务器内存不足卡死，
> 
> 请问问题解决了吗？我现在使用的nuxt3 将项目build后通过PM2启动后，也是进程的内存占用率会随着页面的访问量明显上升

请问你们解决了内存泄漏的问题吗？我也遇到了一样的问题
