### ISSUE TITLE
How to import stylus-css variables?

### ISSUE THREAD

**Issue by Venegrad** [nuxt/nuxt#10553]
In nuxtjs 3 resourse-loader is not working.
But how without resouce-loader module i can import stylus variables for every component?

My old code was:
```
styleResources: {
    stylus: [
      '@/assets/styl/nib/index.styl',
      '@/assets/styl/_setting.styl'
    ]
  },
```

No i cant find in vite documentation or nuxtjs3 documentation, how i can import variables?

**Comment by OldGattsu** [comment]
have the same problem

**Comment by Venegrad** [comment]
> have the same problem

I was solve this problem

**Comment by Venegrad** [comment]
> have the same problem

https://venegrad.com/webblog/manuals/109-import-stylus-mixins-and-variables-in-nuxtjs-3.html

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
