### ISSUE TITLE
Vuex ORM state is lost on hydration

### ISSUE THREAD

**Issue by StaymanHou** [nuxt/nuxt#10562]
### Versions

- nuxt: v2.15.8
- node: v14.19.1

### Reproduction

We cannot deterministically reproduce the problem yet.

We have a Nuxt application running in universal mode. We are also using Vuex, Vuex ORM, and Vuex ORM Axios to manage the state data and the transactions between the API endpoints. In most of the pages we have the fetch hook defined to load data from the API for server-side rendering using the Vuex ORM Axios plugin.

In the dev environment, it's all good. However, in the prod environment, we noticed that the vuex orm data stored in state would be partially lost on hydration at random. The funny thing is that the html code that's rendered on server side would still be correct despite the fact that the data is missing in the state. So when that happens, in the browser, the server-side rendered page would render correctly but just for a split second. Then the client side vue app starts to load the hydrated state, and everything dependent on the data would vanish.

The state loss is just partial. We have fetch defined in the layout to globally fetch data from API and load it for the navigation menu. And another fetch defined for each page to fetch and load data for the main content of the corresponding page. So far I've only seen the state loss for the page specific data, never the state data for navigation.

Also there's no error observed in association with the problem.

So I initially thought it has something to do with a race condition. However, after briefly reading the code of the Vuex ORM Axios plugin as well as the fetch hook documentation. It appears everything is executed in sequence with the correct async/await implementation.

I'm kinda stuck here to further the investigation. Any idea would be appreciated like how I possibly could reliably reproduce the problem.

### Steps to reproduce

- Setup a Nuxt application in universal mode.
- Install and configure Vuex, Vuex ORM, and Vuex ORM Axios plugin
- Define fetch in the layout to use vuex orm axios to fetch and load data from API
- Define fetch in a page such as homepage to also use vuex orm axios to fetch and load data from another API
- Deploy the app in prod mode
- Hit the page over and over again

### What is Expected?

The server rendered page should always have the fetched data rendered in the html code as well as the __NUXT__ hydrated state

### What is actually happening?

Sometimes (roughly 1 in every 10-100 requests) the server rendered page would have the html code correctly rendered but have the data partially lost in __NUXT__

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
