### ISSUE TITLE
Nuxt does not end localhost after stopping

### ISSUE THREAD

**Issue by hslee2008** [nuxt/nuxt#10563]
### Versions

- nuxt: v2.15.8
- node: v16.15.1
- OS: Windows 11

### Details

Not sure if I am the only one experiencing this issue, but after stopping Nuxt command line through `ctrl + c` or closing the terminal, `localhost:3000` is still occupied.

After starting Nuxt, pressing `ctrl + c`, and starting nuxt again (`dev` command), the app opens in random number port other than 3000.

Trying to open 3000 shows a page loading and not showing anything.

![화면 캡처 2022-07-06 165535](https://user-images.githubusercontent.com/78584173/177499554-1593f1c8-800b-4a9e-b785-d9c91258dfde.png)

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by hslee2008** [comment]
I'm sorry but this was Nuxt 2 and it happened a long time ago. I think it doesn't happen anymore at least for me.
