### ISSUE TITLE
Scroll behavior not working when hash is UTF-8 string

### ISSUE THREAD

**Issue by PlusA2M** [nuxt/nuxt#10585]
### Versions

- nuxt: 2.15.8
- node: v16.15.1

### Reproduction

```
<nuxt-link to="#按紙質效果選購">按紙質效果選購</nuxt-link>
```

### Steps to reproduce
1. Have a link to the hash `按紙質效果選購` 
2. Click on it, it will be encoded to `#%E6%8C%89%E7%B4%99%E8%B3%AA%E6%95%88%E6%9E%9C%E9%81%B8%E8%B3%BC`
3. Scroll behavior is not working due to encoded URI. 

### What is Expected?
Scroll behavior is working as usual

### What is actually happening?
No scroll at all.

### Solution
https://github.com/nuxt/nuxt.js/blob/4ae7c089cb12fae5ed128ffad2c308da8e44c22e/packages/vue-app/template/router.scrollBehavior.js#L63
change `let hash = to.hash` to `let hash = decodeURIComponent(to.hash)`

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
