### ISSUE TITLE
I'm trying to implement FullCalendar on a Nuxt3 Project , keep getting errors

### ISSUE THREAD

**Issue by amine-elghazali** [nuxt/nuxt#10586]
My package.json : 
![AX9Lb](https://user-images.githubusercontent.com/81489914/179753495-285e3159-2ec4-4af4-97eb-1815d60d1471.png)

Calendar component : 
![HgVmy](https://user-images.githubusercontent.com/81489914/179753652-ca0993e9-ed44-4304-b3b0-97f89c05f28a.png)

My Plugin/fullCalendar.js : 
![7PBhB](https://user-images.githubusercontent.com/81489914/179753723-9011f22a-b74c-498b-b9e3-831d6741619a.png)

nuxt.config.ts : 
![iuGPn](https://user-images.githubusercontent.com/81489914/179753753-73c789f7-8cde-4f4c-8c45-5cc673d912b1.png)

the error msg : 
![1gAUX](https://user-images.githubusercontent.com/81489914/179753823-736e6bf3-191d-4838-afe8-1da7d8a4195f.png)

That's all I have . Please help ^^'

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
