### ISSUE TITLE
postcss插件使用时不生效，提示请使用 postcss.config.js进行配置，配置之后nuxt提示请在nuxt.config.js中配置postcss，导致无法配置

### ISSUE THREAD

**Issue by huajingbucengyuankesao** [nuxt/nuxt#10601]
### Versions

- nuxt:  v2.15.7
- node: v16.14.2 

### Reproduction

<details open>
<summary>
nuxt.config.js

`{
build:{
postcss: {
      // Add plugin names as key and arguments as value
      // Install them before as dependencies with npm or yarn
      plugins: {
        // Disable a plugin by passing false as value
        'postcss-url': false,
        'postcss-nested': {},
        'postcss-responsive-type': {},
        'postcss-hexrgba': {},
        'postcss-pxtorem': {
          remUnit: 75,
          remPrecision: 2,
          selector_black_list: ['vant'],
          exclude: '/node_modules|vant/i'
        }
      },
      preset: {
        // Change the postcss-preset-env settings
        autoprefixer: {
          grid: true
        }
      }
    }
}`

提示：

 You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on h
ttps://www.postcss.parts/ and use them in postcss.config.js.

添加 postcss.config.js后，提示
 Please use build.postcss in your nuxt.config.js instead of an external config file. Support for such files will be re
moved in Nuxt 3 as they remove all defaults set by Nuxt and can cause severe problems with features like alias resolving ins
ide your CSS.
</summary>
<br>

</details>

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
