### ISSUE TITLE
Can client-side rendering and server-side rendering be supported at the same time

### ISSUE THREAD

**Issue by Y00z** [nuxt/nuxt#10603]
In a nuxt project of server-side rendering, can you set the specified route page to render for the client, and how to operate and configure it? Thank you.

**Comment by silvesterwali** [comment]
hi @Y00z if you have problem with some plugins that only work on the client site just register them and use mode client only according [docs](https://nuxtjs.org/docs/directory-structure/plugins/#object-syntax) here.

**Comment by serdartepeyurt** [comment]
create a file in server/middleware named nossr.js (or whatever you'd like)

insert the code below and change url's according to your project.

```
const urls = ["/url1", "/url2, "/url3/path", "/url4"];

export default defineEventHandler((event) => {
    if (urls.includes(event.req.url)) {
        event.req.headers["x-nuxt-no-ssr"] = "true";
    }
});
```

This way, nuxt renders selected paths only on client. You can write much more detailed version (like wildcards, filtering out querystrings, etc.)

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/24866.
