### ISSUE TITLE
extendRoutes fails to import script at runtime with ReferenceError

### ISSUE THREAD

**Issue by davidbielik** [nuxt/nuxt#10607]
### Versions

- nuxt: v2.15.8
- node: v16.14.2

### Reproduction

[Reproduction.zip](https://github.com/nuxt/nuxt.js/files/9210243/Archive.zip)

<details open>
<summary>Additional Details</summary>
<br>

**nuxt.config.js**
```javascript
import extendRoutes from './scripts/extendRoutes';


const config = {
  router: {
     base: process.env.BASE_URL,
    extendRoutes: extendRoutes,
  },
  // Global page headers: https://go.nuxtjs.dev/config-head
  head: {
    title: 'import-bug',
    htmlAttrs: {
      lang: 'en'
    },
    meta: [],
    link: []
  },
  // Auto import components: https://go.nuxtjs.dev/config-components
  components: true,
  // Modules: https://go.nuxtjs.dev/config-modules
  modules: [
    // https://go.nuxtjs.dev/axios
    '@nuxtjs/axios'
  ],
}

export default config;
```

**extendRoutes.js**
```javascript
import editRoute from './editRoute';
export default function (routes) {
  routes.push(
    {
      path: '/from',
      redirect: (route) => {
        editRoute('');
        return '/to';
      },
    }
  );
}
```

**editRoute.js**
```javascript

export default (path) => {
  return path;
};
```

</details>

### Steps to reproduce

I'm importing my `extendRoutes` to push new routes to the nuxt router.

This `extendsRoutes.js` file imports another script.  Run `nuxt`.

I've attached a sample file: [Reproduction.zip](https://github.com/nuxt/nuxt.js/files/9210243/Archive.zip)

Just run `yarn`, and then `nuxt`

### What is Expected?

Scripts can be imported without error, or I should see a reasonable error when running `nuxt`

### What is actually happening?

When I load the site and `extendRoutes` is evaluated, I get a ReferenceError that the module I'm importing is not defined.

<img width="1464" alt="image" src="https://user-images.githubusercontent.com/7410770/181359995-4cad0e0b-69cf-48fd-b9ff-c5709f09384d.png">

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
