### ISSUE TITLE
<NuxtLink :to="$route.path"> creates <a> which only links to "/child", not "/parent/child" – despite correct data shown in Vue devtools

### ISSUE THREAD

**Issue by simonhrogers** [nuxt/nuxt#10614]
### Versions

nuxt: v2.15.7
node: v16.13.1

### Reproduction

[https://62ea4489e332eb0008df7682--middle-plane.netlify.app/stories/christo-jeanne-claude-me](https://62ea4489e332eb0008df7682--middle-plane.netlify.app/stories/christo-jeanne-claude-me)

Click on "cart" at the above link. It should link to `/stories/christo-jeanne-claude-me?cart=open` but it only links to `/christo-jeanne-claude-me?cart=open`

### Steps to reproduce

`<NuxtLink :to="$route.path">` creates `<a>` which only links to `"/child"`, not `"/parent/child"` – despite correct data shown in Vue devtools. For evidence, please see below screenshot of the slug in `mappedSubheader`, vs. the url revealed by Chrome for the hovered cart link. 

<img width="2133" alt="Screenshot 2022-08-02 at 17 52 58" src="https://user-images.githubusercontent.com/12583581/182432439-4985b79d-5345-4d7c-ba1e-0b8a98f04bd2.png">

**Comment by houdiini** [comment]
Hi! In this case,  `$route.fullPath` would be more suitable.

**Comment by simonhrogers** [comment]
Thanks @houdiini! But actually either should work for my needs in this use-case and neither does.

**Comment by simonhrogers** [comment]
Please note – this happens even if I just do:

`<nuxt-link class="navigation-link" :to="$route.fullPath">`

i.e. no computed properties, nothing – referencing the `$route` directly.  Vue Devtools still reports the correct value for $route.fullPath, but the `<nuxt-link>` does not.

**Comment by simonhrogers** [comment]
As a workaround I’m using `@click="$router.replace(`${$route.fullPath}?cart=open`)"` on a `span` tag, but this feels like a bug with Nuxt that I can’t use `<NuxtLink>` in the way described above.

**Comment by manniL** [comment]
[Can't reproduce](https://stackblitz.com/edit/nuxt-issues-10614?file=pages%2Findex.vue,pages%2Fstories%2F_slug.vue) this anymore.
