### ISSUE TITLE
Self Contained Build Folder

### ISSUE THREAD

**Issue by kane-mason** [nuxt/nuxt#10618]
### Is your feature request related to a problem? Please describe.

Currently when building in server mode a `.nuxt` folder is created with 99% of needed artifcated for your website. However we are still required to deploy the entire project which includes the `.nuxt` folder, `node_modules` and all the source code. 

This is not ideal for a variety of reasons:

1. Lots of file duplication
2. Lots of node modules that will not be used after build
3. The above 2 points mean that when storing artifacts for every build, the artifacts are huge, and becomes a problem when you are dealing with storage quotas

### Describe the solution you'd like

I believe the best solution is to copy whatever remaining dependencies that exist outside the `.nuxt` folder to be copied into the `.nuxt` folder so that everything is self contained and run in the `.nuxt` folder. I will also only need to store the `.nuxt` folder artifacts. 

Perhaps a bespoke package.json for the `.nuxt` folder can be generated to ensure all dependencies of dependcies make their way in too. This might also be useful for people who want to further reduce their artifacts size and wont need to store `node_modules`

**Comment by danielroe** [comment]
This is now done in Nuxt 3 - the `.output` folder is self-contained and has everything neeeded to deploy your site, including 'tree-shaken' node_modules based on usage.
