### ISSUE TITLE
Child Meta tags in head() gets added at the bottom of head tag

### ISSUE THREAD

**Issue by VampishWolf** [nuxt/nuxt#10610]
### Versions

- nuxt: v2.15.8
- node: v14.18.2

### Reproduction
File - nuxt.config.js
```
head: {
    title: 'Global title',
    titleTemplate: '%s  -  Aura',
    htmlAttrs: {
      lang: 'en',
    },
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: 'Global Description' },
      { hid: 'og:image', property: 'og:image', content: 'https://auracdn.fra1.digitaloceanspaces.com/logo-sign-white-bg.png' },
      { property: "og:image:width", content: "740" },
      { property: "og:image:height", content: "300" },
      { name: 'format-detection', content: 'telephone=no' },
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' },
      { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css?family=Inter:wght@300;400;500;600;700&display=swap"', onload:"this.rel='stylesheet'"}
    ],
  }
```

Child _id.vue inside Pages Folder
```
head() {
      return {
        title:
          this.horseInfo && this.horseInfo.name
            ? `${this.horseInfo && this.horseInfo.name}`
            : 'Aura Horse Info',
        meta: [
          {
            hid: 'description',
            name: 'description',
            content:
              this.horseInfo && this.horseInfo.name
                ? `Zed Run Horse ${this.horseInfo.name} on Aura`
                : 'Zed Run Horse on Aura',
          },
          {
            hid: 'og:image',
            property: 'og:image',
            content:
              this.horseInfo && this.horseInfo.image
                ? this.horseInfo.image
                : "",
          },
          {
            hid: 'twitter:title',
            property: 'twitter:title',
            content:
              this.horseInfo && this.horseInfo.name
            ? this.horseInfo.name
            : 'Aura Horse Info',
          },
        ],
    }
}
```

### Steps to reproduce
In the child _id.vue, you can see the description & og:image meta tags which have the same hid and name as in the global config.

### What is Expected?
The child component _id.vue meta tags should override and replace the global meta tags from nuxt.config.js file

### What is actually happening?
The meta tags are getting added but they are at the very end of </head> tag which has a lot of style and script imports above the child meta tags. Probably this is why the meta tags at the bottom are getting skipped by the crawlers and global meta tags from _nuxt.config.js_ show up on all the social platforms as well as the Facebook Sharing Debugger tool.

**Following is what I get in the page source -** 

**_Beginning of head tag_**

<img width="551" alt="Screenshot 2022-08-03 at 6 39 14 PM" src="https://user-images.githubusercontent.com/25270853/182615901-a340b87b-c8d3-4b08-a1ff-18fb459e3dcf.png">

**_Ending of head tag_**

<img width="540" alt="Screenshot 2022-08-03 at 6 38 25 PM" src="https://user-images.githubusercontent.com/25270853/182615947-7d812acf-2f7c-407f-ac7b-8855b952bca6.png">

**Comment by deCodeIt** [comment]
I too am facing the same issue. The child meta tags are not being picked up by opengraph crawlers and instead the global ones are being picked up.

**Comment by VitorMarques** [comment]
Me too. 
"nuxt": "^2.14.6"

**Comment by harlan-zw** [comment]
This likely won't get fixed in Nuxt 2, it shouldn't be an issue in Nuxt 3.

I've made this issue https://github.com/nuxt/vue-meta/issues/794 to track the problem for Nuxt 2. Please add any additional context to that if you run into this problem.

If you're on Nuxt 3 please make a new issue.
