### ISSUE TITLE
Head information disorder accidental

### ISSUE THREAD

**Issue by 449770779** [nuxt/nuxt#10620]
**The header information of page A is displayed as page B,It often happens when the server is busy**

**Page A head info like this**
![image](https://user-images.githubusercontent.com/67248185/182756041-f4dba3b0-e4e3-48c3-9ce0-f636d9b7c712.png)

**Page B head info like this**

![image](https://user-images.githubusercontent.com/67248185/182756108-d52aa1b3-48a7-4680-8f9e-b3cbe1c7a7b5.png)

**Occasionally, when visiting A page, the title will be displayed as follows.**

![image](https://user-images.githubusercontent.com/67248185/182756210-a100dac3-e822-4eb0-aa53-d237958007cb.png)

**Comment by silvesterwali** [comment]
hi @449770779 maybe you can use computed rather then you try direct access the data from server (if you asyncData). so when API server already return the response the computed will be handle this for you.

for example: 

```js
computed:{
  productName(){
     return this.productInfo?.name?? ''
  }
}
head(){
 return {
   title:`Wholesale ${this.productName}`
 }
}
```

**Comment by harlan-zw** [comment]
I believe the solution to this issue is above and isn't a Nuxt or Vue Meta problem.

Going to close this off, if you'd like us to investigate further can you please provide a reproduction.
