### ISSUE TITLE
fetch hook is called on deactivated page with keep-alive on nuxt-child

### ISSUE THREAD

**Issue by mme-htkw** [nuxt/nuxt#10648]
I use the async fetch() hook to fetch the data from the backend. 
To reduce the backend calls, i activated the keep-alive in the default layout.
So the cache works fine, but in some cases, the fetch is executed on a page, which is not active anymore.

### Versions

- nuxt: v2.15.4

### Reproduction

Link to a minimal test case based on one of:
https://codesandbox.io/s/nuxt-keep-alive-fetch-from-wrong-subpage-jiqokm

### Steps to reproduce
- Open the Page and show the Debug tools for the console log
- Press on `Nested`
- Press on `Child 1`
- Press on `Child 2`
- Press on `Index` to return to index page

### What is Expected?
- Press on `Child 1` -> console: Fetch on child1.vue from /parent/child1
- Press on `Child 2` -> console: Fetch on child2.vue from /parent/child2
- Press on `Index` to return to index page

### What is actually happening?
- Press on `Child 1` -> console: Fetch on child1.vue from /parent/child1
- Press on `Child 2` -> console: Fetch on child2.vue from /parent/child2
- Press on `Index` to return to index page -> console: Fetch on child2.vue from /

Actually i use `this.$route` to extract a child parameter, which leads to unexpected behavior, when the fetch method is called with a wrong route value.

**Comment by silvesterwali** [comment]
hi @mme-htkw  have you try use [Store](https://nuxtjs.org/docs/directory-structure/store/)  instead ?. so you want the data fetch only once at the time  you can use [Nuxt Server Init](https://nuxtjs.org/docs/directory-structure/store/#the-nuxtserverinit-action) to call action to fetch data and save the data in the state then you can use the data to all your component.

**Comment by mme-htkw** [comment]
Hi @silvesterwali 

Actually i have to setup a Dashboard, where on all pages, different data is fetched from the backend. So i tried to implement it with the fetch() hook, which have some really nice features. Like fetch status to show a Loading text or an error message, when the fetch fails.
With the keep-alive it would automatically cache the pages, and not fetch it again while navigate through different pages.

Actually i already used the Store and tried to switch over to fetch instead and found this issue. So if there isn't a solution i will stay on the store.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
