### ISSUE TITLE
ie11 bug URLSearchParams 

### ISSUE THREAD

**Issue by bbhxwl** [nuxt/nuxt#10649]
![image](https://user-images.githubusercontent.com/26525599/184817229-7d2004fd-65c6-472b-854a-289b9529fdc4.png)

**Comment by wyfer** [comment]
hello, this bug hava fixed ?

**Comment by nicecue** [comment]
I think "ssr: false" option causes error.
any body solved this problem?

**Comment by bbhxwl** [comment]
> hello, this bug hava fixed ?

did not. Does nuxt not support ie11?

**Comment by changjingli** [comment]
in my experience, don't use `@nuxtjs/composition-api` in Vue2 project will be OK. just use options api with JS.

**Comment by danielroe** [comment]
There's not enough information here to investigate, but Nuxt itself does not use `URLSearchParams`.
