### ISSUE TITLE
Server-side fetch / route only

### ISSUE THREAD

**Issue by goodpixels** [nuxt/nuxt#10669]
I would like to create a route (`/articles`) which only fetches data server-side. Is this possible with Nuxt 2?

I tried wrapping my `asyncData` in a conditional `if(process.server)` statement, but it only works if the route servers as a main entry point to the app (that is the user requests `/articles` URL explicitly via their browser), but it breaks when you reach the route via other client-side page (ie. you go from `/about` &srarr; `/articles`).

I also fiddled with Axios request cancellation, but it produces a network error.

Is there a nice way to achieve this?

**Comment by a-toms** [comment]
Hi there,
If I understand you correctly, check out https://nuxtjs.org/docs/configuration-glossary/configuration-servermiddleware#the-servermiddleware-property

By using the server middleware, you can use your client-side component to call the server middleware (e.g., `/articles`). This server middleware can then fetch data, before returning it to the client side.

This effectively allows you to use nuxt as a frontend and backend.

Side note: I think that this is more of a question than a feature request.

**Comment by danielroe** [comment]
We plan to support server pages in Nuxt 3: https://github.com/nuxt/nuxt/issues/19772. We can track there.
