### ISSUE TITLE
[npm run build] creates a JS file that references another JS file - but this other JS file does not exist!

### ISSUE THREAD

**Issue by danielrhodeswarp** [nuxt/nuxt#10674]
### Versions

- nuxt: v2.15.8
- node: v14.20.0

### Reproduction

(I'll come back to this if needed - this will be time-consuming and delicate.)

I have attached the nuxt.config.js

### My issue

I look after an app where the front-end uses Nuxt. I got a call on Friday that one of the pages (that is important and is known to work ) had stopped working. Clicking the tab to launch this page resulted in a kind of "no operation". Nothing happened and it was almost like a dead link.
Now, this had passed testing on our staging box and so I was very curious and concerned.
Here's what I found to be the cause of the issue:

- One of the generated JS files (dist/_nuxt/b2a2463.js) references another JS file that did not exist!

The dist/_nuxt/b2a2463.js file contains a large dictionary object like {1:"5b7234a", 2:"8e356b2",...} where the hashes represent JS files in dist/_nuxt). But, just for this one particular referenced file - it was not on disk!

Now, I have checked my repository and my deployment flow - the files isn't even in the repository and so this isn't a case of the file getting lost in transit.
The [npm run build] for production blatantly does not produce this file! But [npm run build] for staging is fine (I use dotenv files).

This is quite scary for me as I'll now have to keep an eye on every deploy that I do with Nuxt and I'll have to check if every refernced file exists.

Is this a known or explainable issue?

### What is Expected?

I would of course expect the Nuxt build process to create all of the JS files that it references

### What is actually happening?

One particular JS file is NOT being generated - though it is referenced - and this breaks one page of the application (it becomes a dead link)

### My nuxt.config.js:
`require('dotenv').config()

export default {
    mode: 'spa',
    publicPath: '/',
    // Global page headers: https://go.nuxtjs.dev/config-head
    head: {
        titleTemplate: '%s - My Cool App',
        meta: [
            { charset: 'utf-8' },
            {
                name: 'viewport',
                content: 'width=device-width, initial-scale=1',
            },
            {
                hid: 'description',
                name: 'description',
                content: 'My Cool App',
            },
        ],
        link: [{ rel: 'icon', type: 'image/png', href: '/favicon.png' }],
    },

    // Global CSS: https://go.nuxtjs.dev/config-css
    css: ['@/assets/main.scss'],

    // Plugins to run before rendering page: https://go.nuxtjs.dev/config-plugins
    plugins: ['~/plugins/axios', '~/plugins/vue-moment.js', '~/plugins/gmap', '~/plugins/notifier.js'],

    // Auto import components: https://go.nuxtjs.dev/config-components
    components: true,

    // Modules for dev and build (recommended): https://go.nuxtjs.dev/config-modules
    buildModules: [
        // https://go.nuxtjs.dev/eslint
        '@nuxtjs/eslint-module',
        // https://go.nuxtjs.dev/vuetify
        '@nuxtjs/vuetify',
    ],

    // Modules: https://go.nuxtjs.dev/config-modules
    modules: [
        // https://go.nuxtjs.dev/axios
        '@nuxtjs/axios',
        // https://go.nuxtjs.dev/pwa
        '@nuxtjs/pwa',
        // Doc: https://github.com/nuxt-community/dotenv-module
        '@nuxtjs/dotenv'
    ],

    // Axios module configuration: https://go.nuxtjs.dev/config-axios
    axios: {
        baseURL: process.env.API_BASE_URL,
        headers: {
            common: {
                Accept: 'application/json',
                'Content-Type': 'application/json',
            },
        },
    },
    vue: {
        config: {
            overlay: false,
        },
    },

    // PWA module configuration: https://go.nuxtjs.dev/pwa
    pwa: {
        manifest: {
            lang: 'en',
        },
    },
    router: {
        base: '/',
        routeNameSplitter: '/',
        middleware: 'access',
    },

    // Vuetify module configuration: https://go.nuxtjs.dev/config-vuetify
    vuetify: {
        customVariables: ['~/assets/variables.scss'],
        treeShake: true,
        theme: {
            themes: {
                light: {
                    primary: {
                        base: '#E33326',
                        lighten1: '#EC3F32',
                        lighten2: '#F24C40',
                        lighten3: '#FB5D52',
                        lighten4: '#FD7168',
                        lighten5: '#FE857D',
                        darken1: '#D12B1F',
                        darken2: '#C21F14',
                        darken3: '#A9180E',
                        darken4: '#98130A',
                    },
                    secondary: {
                        base: '#8AE1F0',
                        lighten1: '#4ACAE1',
                        lighten2: '#61D4E8',
                        lighten3: '#8AE1F0',
                        lighten4: '#B7EDF6',
                        lighten5: '#E2F8FC',
                        darken1: '#3EC1DC',
                        darken2: '#39B1C8',
                        darken3: '#339CAE',
                        darken4: '#2D8896',
                        darken5: '#21646A',
                        darken6: '#1dbbe4',
                    },
                    green: {
                        base: '#009C74',
                        lighten1: '#9DE4D4',
                    },
                    yellow: {
                        base: '#FFCA28',
                        lighten1: '#FFF3CE',
                    },
                    grey: {
                        base: '#F4F4F4',
                        lighten1: '#D9D9DB',
                    },
                    error: {
                        base: '#C21F14',
                        darken1: '#CF6679',
                    },
                    pink: {
                        base: '#E7304E',
                    },
                    purple: {
                        base: '#6070d7',
                    },
                    accent: '#007F58',
                    info: '#CF6679',
                    warning: '#B00020',
                    success: '#4ED2B8',
                    anchor: '#303030',
                    white: '#ffffff',
                },
            },
        },
        icons: {
            iconfont: 'mdiSvg',
        },
    },

    // Build Configuration: https://go.nuxtjs.dev/config-build
    build: {
        hotMiddleware: {
            client: {
                // turn off client overlay when errors are present
                overlay: false,
                // faster build on save
                parallel: true,
                cache: true,
                hardSource: true,
            },
        },
    },

    // Faster Webpack build on save, ignore node_modules on save
    webpackDevMiddleware: (config) => {
        config({
            watchOptions: {
                ignored: /node_modules/,
            },
        })
    },
}
`

**Comment by wfq1095745112** [comment]
我也遇到这种问题

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
