### ISSUE TITLE
enablePreview does not call all fetch hooks in layout level

### ISSUE THREAD

**Issue by fabianwohlfart** [nuxt/nuxt#10675]
### Versions

- nuxt: v2.16.0-27616340.013f051b
- node: 14.19.0

### Reproduction

https://github.com/fabianwohlfart/test__nuxt-2-preview

### Steps to reproduce

generate / start with ?preview=true

### What is Expected?

All fetch functions get called, no matter if they are inside the `<Nuxt>` component or on layout level (e.g. layouts/default.vue)

### What is actually happening?

Only components in `<Nuxt>` are calling fetch, layout level components are ignored.

### Related issues

https://github.com/nuxt/nuxt.js/issues/10483

**Comment by drewbaker** [comment]
I'm seeing this also but with `asyncData` not being called client side when `enablePreview` has been called.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
