### ISSUE TITLE
any parameter you specify in a window.location.reload() call will be ignored and have no effect of any kind

### ISSUE THREAD

**Issue by spencer1994** [nuxt/nuxt#10706]
**scene:** 
in the SPA mode, if the [hash].js of the next page load fail, it will trigger the code `window.location.reload(true)`.

However, in all other browsers, any parameter you specify in a location.reload() call will be ignored and have no effect of any kind.

if load the js always fail, it will reload page and no message are notified to the developer each time.

---
**reason:**
in the [file](https://github.com/nuxt/nuxt.js/blob/2ec62617ced873fef97c73a6d7aa1271911ccfd5/packages/vue-app/template/jsonp.js), line 42
``` js
  const onScriptComplete = script.onerror = script.onload = (event) => {
    // Cleanups
    clearTimeout(timeout)
    delete chunksInstalling[chunkId]

    // Avoid mem leaks in IE
    script.onerror = script.onload = null

    // Verify chunk is loaded
    if (chunks[chunkId]) {
      return resolve(chunks[chunkId])
    }

    // Something bad happened
    const errorType = event && (event.type === 'load' ? 'missing' : event.type)
    const realSrc = event && event.target && event.target.src
    error.message = 'Loading chunk ' + chunkId + ' failed.\n(' + errorType + ': ' + realSrc + ')'
    error.name = 'ChunkLoadError'
    error.type = errorType
    error.request = realSrc
    failedChunks[chunkId] = error
    reject(error)
  }
```
in the [file](https://github.com/nuxt/nuxt.js/blob/a3b2fd86ad3cc573c7e075429207fd9a02af55bf/packages/vue-app/template/client.js)，line 209
``` js
// Handle chunk loading errors
// This may be due to a new deployment or a network problem
if (/^Loading( CSS)? chunk (\d)+ failed\./.test(message)) {
  window.location.reload(true /* skip cache */)
  return // prevent error page blinking for user
}
```
[mdn link](https://developer.mozilla.org/en-US/docs/Web/API/Location/reload)
![image](https://user-images.githubusercontent.com/19463934/190143620-ccc88b56-3a99-4d33-b9f5-b5813cec9d0a.png)

---
**expect:**
Can you expose a configuration item to control whether `window.location.reload(true)` is triggered?

**Comment by danielroe** [comment]
I'm not sure what the issue is here. If the browser isn't Firefox, it doesn't force reload, but it still reloads the page. Is there a bug with this?

Please feel free to comment with more info/a reproduction and I will happily reopen.
