### ISSUE TITLE
Trailing Slash when setting router.base in nuxt config

### ISSUE THREAD

**Issue by simonmaass** [nuxt/nuxt#10704]
### Versions

- nuxt: v2.15.8
- node:  v16.14

### Reproduction

in nuxt.config.js set
`router: { trailingSlash: false, base: '/suche' }`

![image](https://user-images.githubusercontent.com/32599710/190136308-b336acf0-3849-4077-acb9-64caf1090ad2.png)

Default route will be /suche/ - with trailing slash... also if you visit "/suche" you will get a redirect to "/suche/" 

### Steps to reproduce
Visit page root... with and without slash

### What is Expected?
I would expect that the default root route will be "/suche" -> without a trailing slash... and not get a 301

### What is actually happening?
I am getting a 301 and get redirect to "/suche/"

**Comment by eakoriakin** [comment]
Having the same issue, I'd like to avoid having a trailing slash on my routes. Would be nice to have it fixed.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
