### ISSUE TITLE
Nuxt server retrieve deleted cookies on server when duplicate tab

### ISSUE THREAD

**Issue by starofsky** [nuxt/nuxt#10716]
### Discussed in https://github.com/nuxt/nuxt.js/discussions/10712

<div type='discussions-op-text'>

<sup>Originally posted by **starofsky** September 20, 2022</sup>
I created one example at https://286q7d-3000.preview.csb.app/
I used package cookie-universal-nuxt
Follow steps:
1/ Create cookie
2/ Go to index2
3/ Delete cookie
4/ Back to index
5/ Duplicate tab
6/ Open console will see cookie deleted show on Nuxt server

https://user-images.githubusercontent.com/5322431/191172484-2921b88d-2548-4dd7-acdd-d38ef8beb01f.mp4

</div>

**Comment by danielroe** [comment]
I can't reproduce this. Would you provide a reproduction? For example, the link to that CSB. :pray:

**Comment by starofsky** [comment]
> I can't reproduce this. Would you provide a reproduction? For example, the link to that CSB. 🙏

Thank you for your reply.
[Link to CSB](https://codesandbox.io/p/github/starofsky/codesandbox-template-nuxt/draft/infallible-aj?import=true&file=%2Fcomponents%2FTutorial.vue&selection=%5B%7B%22endColumn%22%3A34%2C%22endLineNumber%22%3A15%2C%22startColumn%22%3A34%2C%22startLineNumber%22%3A15%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cl89ocp0e02p12a6bdj76jeh6%2522%252C%2522openFiles%2522%253A%255B%2522%252Fnuxt.config.js%2522%252C%2522%252Fpages%252Findex.vue%2522%252C%2522%252Fpages%252Findex2.vue%2522%252C%2522%252Fplugins%252Ftestplugin.js%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522url%2522%253A%2522286q7d-3000.preview.csb.app%2522%252C%2522key%2522%253A%2522cl89oqh4v00vy2a6ct8q951f4%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cl89oprfu000blod2f7exf76n%2522%252C%2522key%2522%253A%2522cl89opqcc00iz2a6c6mcsiygw%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D)

**Comment by starofsky** [comment]
@danielroe can you please help, I have urgent problem with login/logout. When I logout and login again, open new tab will get old account login before.

**Comment by danielroe** [comment]
I believe this is either browser behaviour or should be raised at cookie-universal-nuxt rather than in the nuxt framework. Nuxt 2 doesn't change the behaviour of setting/retrieving cookies.
