### ISSUE TITLE
Nuxt build error?

### ISSUE THREAD

**Issue by bluemoon-i** [nuxt/nuxt#10713]
<img width="1106" alt="IMG_0450" src="https://user-images.githubusercontent.com/65477955/191246256-74a7e4af-91b3-4073-917c-098a183b506c.PNG">
<img width="897" alt="IMG_0449" src="https://user-images.githubusercontent.com/65477955/191246262-da97abd0-1cca-4f39-ab9c-60fa5703759a.PNG">

**Comment by danielroe** [comment]
Closing as there's no reproduction. Feel free to provide a reproduction and I'll happily reopen.
