### ISSUE TITLE
For some old models, browser runtime report errors.

### ISSUE THREAD

**Issue by cy920820** [nuxt/nuxt#10726]
- Brief description
It can be rendered normally under modern browsers and Android machines with high-version systems. On some old models and browsers with low-version systems, an error will be reported, blocking style rendering and subsequent JS code execution.

- Model browser information：

![image](https://user-images.githubusercontent.com/21211512/192424490-95b7f480-1e06-400c-9102-e9851279da85.png)

- Error info：

```console
Unexpected token =
at Object.push../node_modules/crypto-js/enc-base64url.js (http://10.100.63.16:3000/_nuxt/vendors/app.js:171:1)
at __webpack_require__ (http://10.100.63.16:3000/_nuxt/runtime.js:854:30)
at fn (http://10.100.63.16:3000/_nuxt/runtime.js:151:20)
at eval (webpack-internal:///./node_modules/crypto-js/index.js:4:445)
at Object.eval (webpack-internal:///./node_modules/crypto-js/index.js:7:2)
at Object.push../node_modules/crypto-js/index.js (http://10.100.63.16:3000/_nuxt/vendors/app.js:226:1)
at __webpack_require__ (http://10.100.63.16:3000/_nuxt/runtime.js:854:30)
at fn (http://10.100.63.16:3000/_nuxt/runtime.js:151:20)
at Object.eval (webpack-internal:///./helper/util.js:34:68)
at Object.push../helper/util.js (http://10.100.63.16:3000/_nuxt/app.js:1116:1)

```

### Versions

- nuxt:  2.15.8
- node:   v16.15.1

### Reproduction

<details open>
<summary>Additional Details</summary>
I found that our nuxt official website also reported syntax errors when rendering on this model of browser

![image](https://user-images.githubusercontent.com/21211512/192425856-c715f4be-d7c0-44bb-b505-de12d001356b.png)

<br>

</details>

### What is actually happening?

Deploy the build using the `nuxt generate` packaging command

nuxt config target value is `static`

**Comment by cy920820** [comment]
No `legacy build ` description was found in the documentation

**Comment by cy920820** [comment]
@danielroe Ask about nuxt compatibility?  please

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
