### ISSUE TITLE
Dynamic routes with required parameters are not generated correctly when router.trailingSlash is true

### ISSUE THREAD

**Issue by ozgurg** [nuxt/nuxt#10733]
### Versions

- nuxt: 2.15.8
- node: 16.17.0

### Reproduction
[router-test.zip (Sample project)](https://github.com/nuxt/nuxt.js/files/9693131/router-test.zip)

### Steps to reproduce
1) Download the sample project that I created for this issue
2) Run `npm run build` command (Of course `npm install` first)
3) Go to `.nuxt/routes.json`
4) The route was generated with the path `/users/:id`
5) Go to `nuxt.config.js` and set `trailingSlash` to `true` in `router` config
6) Go to step 2 and repeat from there until step 4
7) When you reach 4. step, the route was generated with the path `/users/:id?/` instead `/users/:id/`

### What is Expected?
A route should be generated with the path `/users/:id/`

### What is actually happening?
A route was generated with the path `/users/:id?/` (with question mark)

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
