### ISSUE TITLE
是所有vue的组件都能nuxt服务端渲染么?

### ISSUE THREAD

**Issue by bbhxwl** [nuxt/nuxt#10758]
我这个项目不能使用,出错.
https://github.com/DataV-Team/DataV
![image](https://user-images.githubusercontent.com/26525599/195489069-035f2da1-409b-4a6a-aaab-bf31aa16b625.png)

**Comment by wusongliang** [comment]
可能你使用的组件不支持服务端渲染

**Comment by manniL** [comment]
This seems to be an issue with the respective plugin, not with Nuxt. You might want to add it to `build.transpile` though.
