### ISSUE TITLE
Navigation Don't Respect Scroll Margin CSS

### ISSUE THREAD

**Issue by aliftaufik** [nuxt/nuxt#10750]
### Versions

- nuxt: 2.15.8
- node: v16.16.0

### Reproduction

https://codesandbox.io/s/exciting-rain-d3r42i?file=/components/Tutorial.vue

### Steps to reproduce
- Ensure the current URL doesn't have "#target"
- Click the nuxt-link that navigates to #target

### What is Expected?
Browser scrolls to target element, but since there's scroll margin style in place, scrolling will respect those style

### What is actually happening?
Browser scrolls to the target element with no respect to the scroll margin style. Try refreshing the page and the correct behavior occurs. So must be because of nuxt/vue interferes with the default behavior.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
