### ISSUE TITLE
Can not access Nuxt loading screen with progress bars during build

### ISSUE THREAD

**Issue by sebbayer** [nuxt/nuxt#10767]
### Versions

- nuxt: 2.15.0 - 2.15.8
- node: 16.15.0

### Reproduction

I have a large-scale project where running the build process in dev mode takes a while (in my case about a minute).

While the build progress is updating in console, the `@nuxt/loading-screen` app that comes with nuxt is never sent from the connect webserver and the browser just presents a blank page and is stuck in loading state, waiting for the http server to respond. The loading-screen only shows in the browser when you open `http://localhost:3000` very quickly (1-2 seconds) after starting dev mode. This has been the case since 2.15.0, in 2.14.12 the bug was not present and I could access the loading-screen any time during the build process.

I tracked down the problem and found that the hook `server:nuxt:renderLoading` which `node_modules/@nuxt/loading-screen/lib/module.js` is waiting for is only executed once when the webserver is starting and when build is complete, but not during build.

Other devs in the project have the same issue, OS independent and with the same node/nuxt versions set up.

### Steps to reproduce

- Use a large project where the webpack build takes some time
- Run `nuxt`
- Go to `http://localhost:3000` when about half the build progress is done
- Blank page in browser and stuck in loading state until build is completed

### What is Expected?

The nuxt webserver should send the loading-screen to browsers immediately when requested.

### What is actually happening?

The loading-screen is only sent to browsers if accessed very quickly as the build process starts.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
