### ISSUE TITLE
Cannot read properties of undefined (reading 'data')   

### ISSUE THREAD

**Issue by bbhxwl** [nuxt/nuxt#10781]
Why does this error occur when refreshing the page? I see that my page defines data, but it does not respond to use.

![image](https://user-images.githubusercontent.com/26525599/198969454-115305e2-5b91-4f0a-8f65-80354d6ec886.png)

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by danielroe** [comment]
Closing as there's no reproduction. Feel free to provide a reproduction and I'll happily reopen.
