### ISSUE TITLE
nuxt博客部署到服务器，插件报错。找不到。Plugin not found: /www/server/nginx/html/blog/plugins/element-ui

### ISSUE THREAD

**Issue by mryangsen** [nuxt/nuxt#10805]
### Versions

- nuxt: 
- node: 

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
最近使用nuxt搭建了一个博客，把需要部署的文件放到服务器，安装好依赖，一启动项目报错，安装的库和插件都找不到。
然后我又使用nuxt重新初始化一个项目，安装选项选择安装了 element-ui  然后打包放到服务器启动也是报错、不能使用插件和库。
报错如下。
 Plugin not found: /www/server/nginx/html/blog/plugins/element-ui                    15:46:32
  at node_modules/@nuxt/builder/dist/builder.js:740:15
  at async Promise.all (index 2)
  at async Builder.build (node_modules/@nuxt/builder/dist/builder.js:324:5)
  at async Object._buildDev (node_modules/@nuxt/cli/dist/cli-dev.js:107:5)
  at async Object.startDev (node_modules/@nuxt/cli/dist/cli-dev.js:65:7)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-dev.js:52:5)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:413:7)

版本：
 "element-ui": "^2.15.9",
 "nuxt": "^2.15.8",
### What is Expected?
希望可以解决下。

o pages directory found in /www/server/nginx/html/blog. Using the default built-in page.
✔ Builder initialized                                                                       15:46:32
✔ Nuxt files generated                                                                      15:46:32
 ERROR  Plugin not found: /www/server/nginx/html/blog/plugins/element-ui                    15:46:32
  at node_modules/@nuxt/builder/dist/builder.js:740:15
  at async Promise.all (index 2)
  at async Builder.build (node_modules/@nuxt/builder/dist/builder.js:324:5)
  at async Object._buildDev (node_modules/@nuxt/cli/dist/cli-dev.js:107:5)
  at async Object.startDev (node_modules/@nuxt/cli/dist/cli-dev.js:65:7)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-dev.js:52:5)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:413:7)

**Comment by ghostsatan** [comment]
我也遇到类似情况  开发环境没问题 但是正式环境上
swiper  选项卡 很多效果都失效

**Comment by mryangsen** [comment]
> 我也遇到类似情况 开发环境没问题 但是正式环境上 swiper 选项卡 很多效果都失效

后来怎么 解决的，我的就卡这了进行不下去了。准备换next.js重新写呢

**Comment by ghostsatan** [comment]
> > 我也遇到类似情况 开发环境没问题 但是正式环境上 swiper 选项卡 很多效果都失效
> 
> 后来怎么 解决的，我的就卡这了进行不下去了。准备换next.js重新写呢

<client-only></client-only>
我是用这个试了试

**Comment by mryangsen** [comment]
> 

你解决了？？还是换其他框架写的

**Comment by ghostsatan** [comment]
> > 
> 
> 你解决了？？还是换其他框架写的

重写来不及了  公司项目

我排查了一下问题，问题就出在数据上 按照官方文档的 client-only 包裹了  template的所有div内容 你可以试试 

就解决了

**Comment by mryangsen** [comment]
> 

就离谱，试了不行。

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
