### ISSUE TITLE
If the CDN is used to import Vue, the meta and page title cannot be reloaded when switching pages

### ISSUE THREAD

**Issue by 1029800858** [nuxt/nuxt#10815]
### Versions

- nuxt: 
- 2.15.8
- node: 
- 16.13.2
### Reproduction

<details open>
<summary>Additional Details</summary>
In the process of project optimization, Vue CDN is introduced after component CDN is introduced. After recompiling the project, it was found that the meta and title of another page could not be reloaded when switching pages. This is the configuration in my nuxt.config.js
<br>
` head: {
    titleTemplate:"%s",
    link: [
      {
         rel: 'stylesheet',
         href: 'https://unpkg.com/vant@2.12/lib/index.css'
       }
    ],
    script: [
     {
        src:"https://unpkg.com/vue@2.6/dist/vue.min.js"
      },
       {
         src:"https://unpkg.com/vant@2.12/lib/vant.min.js"
        },
    ],
    meta: [
      { name: "viewport", content: "initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, width=device-width"},
    ],
  },
  build: {
    extend(config, { isClient,isDev}) {
      if (isClient) {
        config.externals={
           vue: 'Vue',
          vant: "vant",
          "vue-router":"VueRouter",
          swiper: "Swiper",
          "vue-awesome-swiper":"VueAwesomeSwiper",
        }
      }
    }
  },
`

</details>

### What is Expected?
Hopefully, switching pages after vue is introduced will also reload another meta and title

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
