### ISSUE TITLE
I plan to combine tailwindcss in nuxt, but I get some mistakes

### ISSUE THREAD

**Issue by shanyi-front** [nuxt/nuxt#10827]
The project is generated by “npx nuxt-create-app xxx”。

The error is as follows：
![image](https://user-images.githubusercontent.com/56287833/202998979-2ae3b339-571c-41e9-9bf9-7b081b5981e8.png)

I guess this error comes from the @nuxt/postcss8 module。Then I went to see the source code。

![image](https://user-images.githubusercontent.com/56287833/203001629-b68eaa48-1f36-417c-b8a0-74e73d2f24c7.png)

![image](https://user-images.githubusercontent.com/56287833/203002314-d7704871-29e7-46e6-b7da-b50cc3e1d914.png)

When the code is executed to this location, I find that the method of nuxtModule is the method of postcss8Module。
The nuxtModule passes two parameters, but the postcss8Module method does not receive parameters。

The error originated from this statement in the postcss8Module method：
`const {nuxt} = this;`
I print "this" here and get undefined, and it matches the error message。
So you can't deconstruct nuxt from undefined。
When I modify the postcss8Module function like this：
![image](https://user-images.githubusercontent.com/56287833/203004186-0df22064-bf49-4e7c-9b18-8ae20c1c79b6.png)

I executed npm run dev again and it ran successfully：
![image](https://user-images.githubusercontent.com/56287833/203004283-e9ba7d6c-edde-4303-8758-1f505de62412.png)

I want to know if this is a bug in Nuxt.js?

### Versions

- nuxt: v2.15.8
- node: v16.13.0
- @nuxt/postcss8: v1.1.3

**Comment by jessekalil** [comment]
same here

**Versions**
nuxt: ^2.15.8
vue: ^2.7.10
node: v18.12.1

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/15507.
