### ISSUE TITLE
privateRuntimeConfig lost after $nuxt.refresh()

### ISSUE THREAD

**Issue by RyamBaCo** [nuxt/nuxt#10833]
### Versions

- nuxt: 2.15.8
- node: 16.17.0

### Reproduction

Setup privateRuntimeConfig with officeRNDClientId and officeRNDClientSecret. Load the data in asyncData using $config with the following code snippet

```
<script lang="ts">
import { Context } from "@nuxt/types";
import { TokenData } from "./../types";
import { Component, Vue } from "nuxt-property-decorator";

@Component({
  asyncData: async ({
    $config: { officeRNDClientId, officeRNDClientSecret },
    $axios,
  }: Context): Promise<{ tokenData: TokenData }> => {
    const tokenResponse = (
      await $axios.post(
        "/token",
        new URLSearchParams({
          client_id: officeRNDClientId,
          client_secret: officeRNDClientSecret,
          grant_type: "client_credentials",
          scope: "officernd.api.read",
        }),
        { headers: { "Content-Type": "application/x-www-form-urlencoded" } }
      )
    ).data;

    return {
      tokenData: {
        token: tokenResponse.access_token,
        expiresIn: +tokenResponse.expires_in,
      },
    };
  },
})
export default class IndexPage extends Vue {
  tokenData!: TokenData;

  created() {
    setTimeout(() => this.$nuxt.refresh(), 2000);
  }
}
</script>
```

officeRNDClientId and officeRNDClientSecret are set in nuxt.config.js:
```
privateRuntimeConfig: {
    officeRNDClientId: process.env.OFFICERND_CLIENT_ID,
    officeRNDClientSecret: process.env.OFFICERND_CLIENT_SECRET,
  },
```

After calling $nuxt.refresh() after 2 seconds asyncData is called a second time but officeRNDClientId and officeRNDClientSecret are undefined then. Therefore, the POST request fails.

### Steps to reproduce
- Run Code Snippet
- Open Dev Tools
- POST to token endpoint with officeRNDClientId and officeRNDClientSecret (set in privateRuntimeConfig)
- After 2 seconds page is reloaded through $nuxt.refresh()
- But in asyncData both officeRNDClientId and officeRNDClientSecret are undefined

### What is Expected?

- After calling $nuxt.refresh() $config values should be set (as in initial page load)

### What is actually happening?

- After calling $nuxt.refresh() $config values are undefined

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
