### ISSUE TITLE
empty $route.meta

### ISSUE THREAD

**Issue by titouandk** [nuxt/nuxt#10837]
### The context

I have a layout containing a header and the page content.
I need to access current page's metadata inside the header, to know which tab to activate.

```vue
<template>
  <Header /> <!-- Website banner with tabs. -->
  <NuxtChild /> <!-- Include current page. Each page has metadata indicating which tab to activate. -->
</template>
```

### The problem

The route metadata are accessible from middlewares, but not from components.
My Header component cannot access current page's metadata.

See how the `meta` property differs below, for the same route `/` :

![console](https://user-images.githubusercontent.com/5413308/204107980-74f3320c-c088-4e50-a447-b143ecda3bad.png)

I have Nuxt v2.15.8.

---

_layouts/default.vue_
```vue
<template>
  <Header /> <!-- website banner with tabs -->
  <NuxtChild /> <!-- page content -->
</template>
```
_pages/index.vue_
```vue
<template>
  <h1>Welcome on this homepage</h1>
</template>

<script>
export default {
  meta: {
    activeTab: "home" // the header tab to activate on this page is "home"
  }
}
</script>
```

---

✅  _middleware/test.js_
```js
export default ({ route, store }) => {
  console.log(route.meta[0].activeTab) // home
}
```

---

❌ _components/Header.vue_

```vue
<template>
  <nav>
    {{ activeTab }}
  </nav>
</template>

<script>
export default {
  computed: {
    activeTab() {
      console.log(this.$route.meta[0]) // undefined
      return this.$route.meta[0].activeTab
    }
  }
}
</script>
```

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
