### ISSUE TITLE
Redirect to full URL decodes url query params

### ISSUE THREAD

**Issue by lucianholt97** [nuxt/nuxt#10834]
### Versions

- nuxt: v2.15.8
- node: v16.14.2
- vue-router v3.5.3

### Reproduction

```js
asyncData({ redirect }) {
    const url = 'https://auth.test.com?returnTo='+encodeURIComponent('https://test.com?token=abc')
    // https://auth.test.com?returnTo=https%3A%2F%2Ftest.com%3Ftoken%3Dabc
    redirect(url, {})
}
```

Same results for this method
```js
asyncData({ redirect }) {
    const url = 'https://auth.test.com'
    return redirect(url, { returnTo: 'https://test.com?token=abc' })
}
```

### Steps to reproduce
Setup simple redirect with full url and encoded url as query param.

### Related Reports
- https://forum.vuejs.org/t/redirect-in-middleware-decodes-query-parameter-partially/124615/2
- https://github.com/nuxt/nuxt.js/issues/8680#issuecomment-767697406

### What is Expected?
Redirect to exact url with encoding

### What is actually happening?
nuxt decodes url and redirect to https://auth.test.com?returnTo=https://test.com?token=abc
This results in issues since the url cannot be read correctly by most frameworks.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
