### ISSUE TITLE
Nuxt2 default setup doesn't work with latest node LTS version 18.12.1

### ISSUE THREAD

**Issue by michael-pfister** [nuxt/nuxt#10844]
The default Nuxt2 project setup runs into an error `Error: error:0308010C:digital envelope routines::unsupported` when starting the development environment (`yarn dev`) using node v18.12.1.

> **Reason For The Error**
In Node.js v17, the Node.js developers closed a security hole in the SSL provider. This fix was a breaking change that corresponded with similar breaking changes in the SSL packages in NPM. [Webpack 4.46.0](https://www.npmjs.com/package/webpack/v/4.46.0) (a module currently used by nuxt2 for serving) is using a deprecated hashing algorithm `md4` for it's SSL encryption, which I assume was patched out in Node.js v17.

# ⚠️ DANGER 
Almost all threads found online regarding this issue are suggesting to either downgrade Node.js to pre v17 or to use the legacy SSL provider. Both of those solutions are hacks that leave your builds open to security threats.

This is a big issue because the [prerequisites](https://nuxtjs.org/docs/get-started/installation#prerequisites) in the current nuxt installation guide are telling newcomers [to get the latest node LTS version](https://nuxtjs.org/docs/get-started/installation#:~:text=node%20%2D%20We%20recommend%20you%20have%20the%20latest%20LTS%20version%20installed), which is currently 18.12.1. Googling the error message (which they will definitely get) will lead them to either set `NODE_OPTIONS=--openssl-legacy-provider`  or downgrade Node.js to pre v17.

### Versions

- nuxt: v2.15.8
- node: v18.12.1

### Reproduction

GitHub repository: https://github.com/michael-pfister/nuxt2-node-demonstrations

<details open>
<summary>Additional Details</summary>
<br>
Make sure you have the currently latest node LTS version (v18.12.1) installed before running any build commands.
</details>

### Steps to reproduce
```bash
# clone git repository
$ git clone https://github.com/michael-pfister/nuxt2-node-demonstrations

# cd into the repository
$ cd nuxt2-node-demonstrations

# install dependencies
$ yarn install

# serve with hot reload at localhost:3000
$ yarn dev
```

### What is Expected?

The Nuxt2 default setup, which newcomers install using `yarn create nuxt-app <project-name>` after getting the latest node LTS version [as mentioned in the prerequisites](https://nuxtjs.org/docs/get-started/installation#:~:text=node%20%2D%20We%20recommend%20you%20have%20the%20latest%20LTS%20version%20installed) should work without throwing an error, that is leading them to implement a potential security risk.

### What is actually happening?
```bash
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\admin\Desktop\nuxt2-node-demonstrations\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\admin\Desktop\nuxt2-node-demonstrations\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\admin\Desktop\nuxt2-node-demonstrations\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\admin\Desktop\nuxt2-node-demonstrations\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\admin\Desktop\nuxt2-node-demonstrations\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\admin\Desktop\nuxt2-node-demonstrations\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\admin\Desktop\nuxt2-node-demonstrations\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (C:\Users\admin\Desktop\nuxt2-node-demonstrations\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Users\admin\Desktop\nuxt2-node-demonstrations\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Users\admin\Desktop\nuxt2-node-demonstrations\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at C:\Users\admin\Desktop\nuxt2-node-demonstrations\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

**Comment by michael-pfister** [comment]
After further reflection, I noticed that not only do the newly created Nuxt2 projects have to have this issue. ALL OF THE NUXT2 PROJECTS EVER CREATED are leaving themselves open to security threats if they don't patch it accordingly.

This is a big issue, imagine bigger companies getting hacked because they were using Nuxt2 as their framework of choice!

We should patch this immediately and warn all users to upgrade to the newer version.

**Comment by michael-pfister** [comment]
[you can read this article about the insecurity of the deprecated `md4` algorithm if you'd like](https://cryptography.fandom.com/wiki/MD4#:~:text=The%20security%20of,attack%20also%20exists.)

**Comment by hartmut-co-uk** [comment]
I can also confirm my nuxt2 app does no longer _build_ on vercel because of this.

**Comment by danielroe** [comment]
To be clear, the reason you're not able to build is that webpack 4, which is used by Nuxt 2, depends on that algorithm for hashing build outputs. But that is a _build-time_ dependency, not a runtime dependency. Nor is it a security risk at build time, as what is being hashed is just the filenames of the generated files..

More importantly, this is not a vulnerablity in a deployed nuxt site. Once built, a nuxt server can run on node 18 just fine as it has no ongoing dependency on webpack.

That said, if there is an issue on node v18, we do need to update our docs to indicate preferred installation in node 16 for now, which will not release EOL until 2023-09-11, and also consider other options.

**Comment by bungandy** [comment]
Add `--openssl-legacy-provider` after the `nuxt build` on package.json should fix the issue, at least for now 🚧

<img width="605" alt="Screen Shot 2022-12-08 at 12 30 43" src="https://user-images.githubusercontent.com/290786/206364701-11ffbc46-38db-4026-94c3-828afa575804.png">

**Comment by WikiWookie** [comment]
I just tried creating a new nuxt project and ran into this issue.  Any work arounds or fixes in the works?

**Comment by danielroe** [comment]
The current workaround is to use Node 16 to build your Nuxt 2 project; you can run the resulting dist files on newer node versions if necessary.

**Comment by MichaelSchober** [comment]
> To be clear, the reason you're not able to build is that webpack 4, which is used by Nuxt 2, depends on that algorithm for hashing build outputs. But that is a _build-time_ dependency, not a runtime dependency. Nor is it a security risk at build time, as what is being hashed is just the content of the generated files..
> 
> More importantly, this is not a vulnerablity in a deployed nuxt site. Once built, a nuxt server can run on node 18 just fine as it has no ongoing dependency on webpack.
> 
> That said, if there is an issue on node v18, we do need to update our docs to indicate preferred installation in node 16 for now, which will not release EOL until 2023-09-11, and also consider other options.

Thanks so much for clarifying the actual security risk!

**Comment by NWRichmond** [comment]
> The current workaround is to use Node 16 to build your Nuxt 2 project; you can run the resulting dist files on newer node versions if necessary.

In practice, this will be an obstacle for `target: 'static'` sites that are deployed with many of the popular Jamstack hosting providers, because at some point those hosting providers will drop support build images that use Node.js 16. I don't think it's Nuxt's problem to solve, but it's a problem that Nuxt practitioners should keep in mind when planning project upgrades from Nuxt 2 to Nuxt 3.

**Comment by pkerschbaum** [comment]
Appears to be re-introduced in 2.17.2.

The same build worked with 2.17.1 but does not with 2.17.2 anymore, `Error: error:0308010C:digital envelope routines::unsupported` is happening again.

Node 18.16.1

**Comment by danielroe** [comment]
Make sure you refresh your lockfile and are on the latest webpack version, which solves this issue natively.

**Comment by pkerschbaum** [comment]
> Make sure you refresh your lockfile and are on the latest webpack version, which solves this issue natively.

Thanks for the fast response!  
I verified that we (@hokify) have webpack 4.47.0 in use, the latest version.

But I noticed that the error message is coming from `compression-webpack-plugin` coming from `nuxt-compress`, which we have added in `buildModules` - I could imagine its a problem there, and not nuxt itself.

```
@hokify/website-app:raw:build:app:  FATAL  error:0308010C:digital envelope routines::unsupported
@hokify/website-app:raw:build:app: 
@hokify/website-app:raw:build:app:   at new Hash (node:internal/crypto/hash:71:19)
@hokify/website-app:raw:build:app:   at Object.createHash (node:crypto:133:10)
@hokify/website-app:raw:build:app:   at /home/pkerschbaum/workspace/hokify/hokify/node_modules/.pnpm/compression-webpack-plugin@6.1.1_webpack@4.47.0/node_modules/compression-webpack-plugin/dist/index.js:230:42
@hokify/website-app:raw:build:app:   at CompressionPlugin.compress (/home/pkerschbaum/workspace/hokify/hokify/node_modules/.pnpm/compression-webpack-plugin@6.1.1_webpack@4.47.0/node_modules/compression-webpack-plugin/dist/index.js:319:9)
@hokify/website-app:raw:build:app:   at /home/pkerschbaum/workspace/hokify/hokify/node_modules/.pnpm/compression-webpack-plugin@6.1.1_webpack@4.47.0/node_modules/compression-webpack-plugin/dist/index.js:340:12
@hokify/website-app:raw:build:app:   at _next2 (eval at create (/home/pkerschbaum/workspace/hokify/hokify/node_modules/.pnpm/tapable@1.1.3/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:46:17)
@hokify/website-app:raw:build:app:   at eval (eval at create (/home/pkerschbaum/workspace/hokify/hokify/node_modules/.pnpm/tapable@1.1.3/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:65:1)
@hokify/website-app:raw:build:app:   at /home/pkerschbaum/workspace/hokify/hokify/node_modules/.pnpm/@nuxt+webpack@2.17.2_prettier@2.8.8_typescript@5.1.6_vue@2.7.15_webpack-cli@4.10.0/node_modules/@nuxt/webpack/dist/webpack.js:284:7
@hokify/website-app:raw:build:app:   at _next1 (eval at create (/home/pkerschbaum/workspace/hokify/hokify/node_modules/.pnpm/tapable@1.1.3/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:61:1)
@hokify/website-app:raw:build:app:   at eval (eval at create (/home/pkerschbaum/workspace/hokify/hokify/node_modules/.pnpm/tapable@1.1.3/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:77:1)
@hokify/website-app:raw:build:app:   at /home/pkerschbaum/workspace/hokify/hokify/node_modules/.pnpm/html-webpack-plugin@4.5.2_webpack@4.47.0/node_modules/html-webpack-plugin/index.js:303:11
@hokify/website-app:raw:build:app:   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
@hokify/website-app:raw:build:app: 
@hokify/website-app:raw:build:app: 
@hokify/website-app:raw:build:app:    ╭──────────────────────────────────────────────────────────────────╮
@hokify/website-app:raw:build:app:    │                                                                  │
@hokify/website-app:raw:build:app:    │   ✖ Nuxt Fatal Error                                             │
@hokify/website-app:raw:build:app:    │                                                                  │
@hokify/website-app:raw:build:app:    │   Error: error:0308010C:digital envelope routines::unsupported   │
@hokify/website-app:raw:build:app:    │                                                                  │
@hokify/website-app:raw:build:app:    ╰──────────────────────────────────────────────────────────────────╯
```

**Comment by Aurion72** [comment]
Same issue here,  nuxt@2.17.1 works

**Comment by vitr-nindeco** [comment]
Same issue here after yarn.lock file and recreate\update, but it's prodlem only in production mode, dev mode without errors.
Nuxt 2.17.1\2.17.2
Node 20.8\18.14
Webpack 4.47.0\4.46.0

![Nuxtjs error](https://github.com/nuxt/nuxt/assets/40595943/f28b563d-50b0-4b37-8e56-be0e75eb3ec0)

**Comment by riekusvm** [comment]
Same issue here: 
Node 18, 
Nuxt 2.17.2 
Webpack 4.47.0

Downgrading to nuxt 2.17.1 fixes the issue

**Comment by freefri** [comment]
@danielroe I think we should reopen this issue or create a new issue. If this is a general problem  after nuxt 2.17.1 we are stuck in this version and we cannot upgrade to the latest 2.17.x, so this could be an important issue to fix in 2.x before finishing nuxt 2.x support.

I can confirm the same issue:
Node 18.20.3 (latest node v18.x)
Nuxt [2.17.4](https://github.com/nuxt/nuxt/releases/tag/v2.17.4) (latest from v2.x)
Webpack [4.47.0](https://github.com/webpack/webpack/releases/tag/v4.47.0) (latest from v4.x)

Downgrading to nuxt 2.17.1 fixes the issue

**Comment by danielroe** [comment]
Though it’s not a Nuxt issue bear in mind you can do exactly the same in your Nuxt config.
