### ISSUE TITLE
the way using cached server data without using asyncData or Fetch when i use history.back() in SSR

### ISSUE THREAD

**Issue by bysxx** [nuxt/nuxt#10841]
I may not have found it, but when I returned to the previous page using history.back() in Nuxt, there seems to be no proper way not to go through asyncData.

I think there is a way to handle it using middleware and stores, but I think you can support it more simply with Nuxt's option..

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/6451.
