### ISSUE TITLE
When passing bodyAttrs in meta, attribute value is not supporting as true. e.g. I want to set <body dark-mode="true">

### ISSUE THREAD

**Issue by engrmamun66** [nuxt/nuxt#10846]
### Versions

- nuxt: 
- node: 

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

**Comment by harlan-zw** [comment]
Per the HTML spec `dark-mode="true"` and `dark-mode` are equivalent. You should modify whatever code you have to accommodate that.
