### ISSUE TITLE
`fetch` hook has no effect on client side if the parent component has a `fetch` function and is a page component

### ISSUE THREAD

**Issue by myeungdev** [nuxt/nuxt#10850]
### Versions

- nuxt: v2.15.8
- node: v16.8.1

### Reproduction

https://codesandbox.io/s/broken-cdn-ufr3d8

### Steps to reproduce

- Create a brand new Nuxt project with SSR enabled
- Add an empty `fetch` function into the page-level component (i.e. pages/index.vue)
- Define a state in the child component (i.e. Tutorial.vue)
- Add a `fetch` function into a child component of the page and update the state in the function

### What is Expected?

The state in the child component should be updated correctly on both server and client sides.

### What is actually happening?

I can see that the state in the child component is updated correctly by `fetch` on the server but as soon as the hydration kicks in the state is reset to its initial state. Anything set in `fetch` does not have any effects in the child component. Removing the `fetch` function from the page-level component fixes the issue.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
