### ISSUE TITLE
Nuxt 2 : Error layout not rendered Server Side

### ISSUE THREAD

**Issue by Erilan** [nuxt/nuxt#10868]
### Versions

- nuxt: 2.15.8
- node: 16.15.0

### Reproduction

In any page, during the fetch, if I throw a 404 error, the HTTP response code is right, 404, the error layout is rendered on the client side, but not during SSR. Even the "head()" methode is not executed server side.

In my case, I cannot use the "validate()" method, because my 404 depends on the existence of a content in a CMS.

Here is a reproduction in codesandbox : https://codesandbox.io/p/sandbox/reverent-lucy-q9y6wu?file=%2Flayouts%2Ferror.vue&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A19%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A19%7D%5D

Result : https://q9y6wu-3000.preview.csb.app/

### What is Expected?
If you go on https://q9y6wu-3000.preview.csb.app/, which return 404, you should see the error template and the error title (Error title) in the source code, or with disabled javascript

### What is actually happening?
If you go on https://q9y6wu-3000.preview.csb.app/, you see the error template with the right title (Error title), but if you inspect or disable javascript on your browser, there is the html of the index page, not the error layout.

**Comment by bumbuledin** [comment]
I am facing the same problem and getting hydration problem. Any solution for this?

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
