### ISSUE TITLE
Deploy to Windows Server / IIS documentation 

### ISSUE THREAD

**Issue by brunotourinho** [nuxt/nuxt#10863]
I'm trying to deploy a Nuxt app to my Windows Server environment with IIS.

I have quite a few apps and APIs running asp.net core 6 on different endpoints i.e.: "domain.com/application1", "domain.com/api1"...

My goal is to launch a Nuxt app (must be server side not SPA) on "domain.com/nuxt_app1" which will request data to the same APIs as asp.net APIs (domain.com/api1)

I've tried reverse proxy using URL rewrite. Tried some solutions using IISNode with no success, also tried some tweaking on web.config file but again, no success.

Didn't find any documentation on IIS deployment in [https://nuxtjs.org/deployments](https://nuxtjs.org/deployments)

If anyone can help would be greatly appreciated.

Thanks in advance

**Comment by danielroe** [comment]
Let's track upstream in https://github.com/unjs/nitro/issues/371.
