### ISSUE TITLE
Pipeline is crashing using Nuxt v2 - FATAL  Cannot find module 'node:module'

### ISSUE THREAD

**Issue by dulcetti** [nuxt/nuxt#10889]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.20.0`
- Nuxt Version:     `2.15.8`
- Nitro Version:    `-`
- Package Manager:  `yarn@1.22.19`
- Builder:          `webpack`
- User Config:      `head`, `css`, `env`, `publicRuntimeConfig`, `server`, `plugins`, `components`, `buildModules`, `modules`, `axios`, `vuetify`, `build`, `auth`, `router`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`, `@nuxtjs/auth-next@5.0.0-1618898588.9655d0e`
- Build Modules:    `@nuxtjs/vuetify@1.12.3`

### Reproduction

We're using version 2 of Nuxt here. Locally it works fine, but now this week the Pipeline on Gitlab has failed every time. We use Terraform with Docker in the Pipeline and run the two commands: `npm install` and `npm build`, The first one runs without problems, but the build doesn't.

Last week the Pipeline worked fine, but now it crashes every time

### Describe the bug

The Pipeline shows the following errors

```bash
> nuxt build
 FATAL  Cannot find module 'node:module'
Require stack:
- /home/node/node_modules/jiti/dist/jiti.js
- /home/node/node_modules/jiti/lib/index.js
- /home/node/node_modules/@nuxt/utils/dist/utils.js
- /home/node/node_modules/@nuxt/cli/dist/cli-index.js
- /home/node/node_modules/@nuxt/cli/dist/cli.js
- /home/node/node_modules/nuxt/bin/nuxt.js
  Require stack:
  - node_modules/jiti/dist/jiti.js
  - node_modules/jiti/lib/index.js
  - node_modules/@nuxt/utils/dist/utils.js
  - node_modules/@nuxt/cli/dist/cli-index.js
  - node_modules/@nuxt/cli/dist/cli.js
  - node_modules/nuxt/bin/nuxt.js
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
  at Function.Module._load (internal/modules/cjs/loader.js:725:27)
  at Module.require (internal/modules/cjs/loader.js:952:19)
  at require (internal/modules/cjs/helpers.js:88:18)
  at node_modules/jiti/dist/jiti.js:1:215[165](https://gitlab.mosaico.com.br/mosaico/ooppa/squad-plugin/plugin-dashboard/-/jobs/556318#L165)
  at node_modules/jiti/dist/jiti.js:1:249320
  at Object.<anonymous> (node_modules/jiti/dist/jiti.js:1:249367)
  at Module._compile (internal/modules/cjs/loader.js:1063:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
  at Module.load (internal/modules/cjs/loader.js:928:32)
   ╭───────────────────────────────────────────────────────────╮
   │                                                           │
   │   ✖ Nuxt Fatal Error                                      │
   │                                                           │
   │   Error: Cannot find module 'node:module'                 │
   │   Require stack:                                          │
   │   - /home/node/node_modules/jiti/dist/jiti.js             │
   │   - /home/node/node_modules/jiti/lib/index.js             │
   │   - /home/node/node_modules/@nuxt/utils/dist/utils.js     │
   │   - /home/node/node_modules/@nuxt/cli/dist/cli-index.js   │
   │   - /home/node/node_modules/@nuxt/cli/dist/cli.js         │
   │   - /home/node/node_modules/nuxt/bin/nuxt.js              │
   │                                                           │
   ╰───────────────────────────────────────────────────────────╯
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zoom-adm@1.0.0 build: `nuxt build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zoom-adm@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/[202](https://gitlab.mosaico.com.br/mosaico/ooppa/squad-plugin/plugin-dashboard/-/jobs/556318#L202)3-01-05T22_38_00_841Z-debug.log
The command '/bin/sh -c npm run build' returned a non-zero code: 1
Cleaning up project directory and file based variables
00:00
ERROR: Job failed: exit code 1
```

### Additional context

I've tried to put the code in my package.json, but don't worked:
```json
"resolutions": {
  "jiti": "1.12.7"
}
```

My package.json is here:
```json
{
  "name": "zoom-adm",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "test": "jest"
  },
  "dependencies": {
    "@nuxtjs/auth-next": "5.0.0-1618898588.9655d0e",
    "@nuxtjs/axios": "^5.13.1",
    "@nuxtjs/proxy": "^2.1.0",
    "core-js": "^3.9.1",
    "nuxt": "^2.15.3",
    "vue-json-csv": "^1.2.12",
    "vue-json-pretty": "^1.8.1"
  },
  "devDependencies": {
    "@nuxtjs/vuetify": "^1.11.3",
    "@vue/test-utils": "^1.1.3",
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "^26.6.3",
    "cz-conventional-changelog": "^3.3.0",
    "jest": "^26.6.3",
    "vue-jest": "^3.0.4"
  },
  "config": {
    "commitizen": {
      "path": "./node_modules/cz-conventional-changelog"
    }
  },
  "resolutions": {
    "jiti": "1.12.7"
  }
}

```

**Comment by NoushadBug** [comment]
hello, is there any update on the issue? I'm facing the same issue


 FATAL  Cannot find module 'node:module'                              01:07:20
Require stack:
- F:\nomanzi\energiewechsel\node_modules\jiti\dist\jiti.js
- F:\nomanzi\energiewechsel\node_modules\jiti\lib\index.js
- F:\nomanzi\energiewechsel\node_modules\@nuxt\utils\dist\utils.js
- F:\nomanzi\energiewechsel\node_modules\@nuxt\cli\dist\cli-index.js
- F:\nomanzi\energiewechsel\node_modules\@nuxt\cli\dist\cli.js
- F:\nomanzi\energiewechsel\node_modules\nuxt\bin\nuxt.js

  Require stack:
  - node_modules\jiti\dist\jiti.js
  - node_modules\jiti\lib\index.js
  - node_modules\@nuxt\utils\dist\utils.js
  - node_modules\@nuxt\cli\dist\cli-index.js
  - node_modules\@nuxt\cli\dist\cli.js
  - node_modules\nuxt\bin\nuxt.js
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
  at Function.Module._load (internal/modules/cjs/loader.js:725:27)
  at Module.require (internal/modules/cjs/loader.js:952:19)
  at require (internal/modules/cjs/helpers.js:88:18)
  at node_modules\jiti\dist\jiti.js:1:215165
  at node_modules\jiti\dist\jiti.js:1:249320
  at Object.<anonymous> (node_modules\jiti\dist\jiti.js:1:249367)
  at Module._compile (internal/modules/cjs/loader.js:1063:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
  at Module.load (internal/modules/cjs/loader.js:928:32)


   ╭────────────────────────────────────────────────────────────────────────╮
   │                                                                        │
   │   ✖ Nuxt Fatal Error                                                   │
   │                                                                        │
   │   Error: Cannot find module 'node:module'                              │
   │   Require stack:                                                       │
   │   - F:\nomanzi\energiewechsel\node_modules\jiti\dist\jiti.js           │
   │   - F:\nomanzi\energiewechsel\node_modules\jiti\lib\index.js           │
   │   -                                                                    │
   │   F:\nomanzi\energiewechsel\node_modules\@nuxt\utils\dist\utils.js     │
   │   -                                                                    │
   │   F:\nomanzi\energiewechsel\node_modules\@nuxt\cli\dist\cli-index.js   │
   │   - F:\nomanzi\energiewechsel\node_modules\@nuxt\cli\dist\cli.js       │
   │   - F:\nomanzi\energiewechsel\node_modules\nuxt\bin\nuxt.js            │
   │                                                                        │
   ╰────────────────────────────────────────────────────────────────────────╯

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by NoushadBug** [comment]
hello, is there any update on the issue? I want to know the reason of the issue exactly.

I have tried this
```
"resolutions": {
  "jiti": "1.12.7"
}
```
 and then `yarn install`
 
 it is working now. Thanks

**Comment by disolaterX** [comment]
Any updates team ?

**Comment by dvdgitman** [comment]
Having same issue. Any updates regarding this?

**Comment by xingxiangchao** [comment]
> I've upgrade the node from 14.7 to 16-alpine in the dockerfile and it work for me.

I upgraded the Nodejs Docker image to 16.16, which has been resolved

**Comment by kevinrieger** [comment]
I'm facing the same issue with Node 14.17.1. Due to other dependencies I can not upgrade Node yet. With Node 16 it seems to work, unfortunately that's not an option for me...

**Comment by hjardines** [comment]
+1 on this. All of the sudden the deployments are not working.

**Comment by MrsPolly** [comment]
I tried everything, started with version 14.17.3, cloned the repo again, downloaded the node version, upgraded it to version 16.xx.xx, downgraded it again to version 15.xx.xx and nothing worked, finally I put it on version 14.19.3 and it finally worked fine.

**Comment by freezyh** [comment]
> hello, my issue is solved. But is there any update on the issue? I want to know the reason of the issue exactly.
> 
> My node is : 14.16.1 npm: 6.14.12
> 
> for other dependencies, I can not upgrade the node. So, I was expecting nuxt to be worked in this version. I have tried this
> 
> ```
> "resolutions": {
>   "jiti": "1.12.7"
> }
> ```
> 
> and then `yarn install`
> 
> it is working now. Thanks
if I use npm, how to savle it

**Comment by freezyh** [comment]
I had update the node version 16.13.0, but i run npm run sit nuxt build error
 FATAL  Nuxt build error                                                                                                                                                                                                       12:50:26  

  at WebpackBundler.webpackCompile (node_modules\@nuxt\webpack\dist\webpack.js:2127:21)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async WebpackBundler.build (node_modules\@nuxt\webpack\dist\webpack.js:2076:5)
  at async Builder.build (node_modules\@nuxt\builder\dist\builder.js:327:5)
  at async Object.run (node_modules\@nuxt\cli\dist\cli-build.js:110:7)
  at async NuxtCommand.run (node_modules\@nuxt\cli\dist\cli-index.js:413:7)

**Comment by freezyh** [comment]
> hello, my issue is solved. But is there any update on the issue? I want to know the reason of the issue exactly.
> 
> My node is : 14.16.1 npm: 6.14.12
> 
> for other dependencies, I can not upgrade the node. So, I was expecting nuxt to be worked in this version. I have tried this
> 
> ```
> "resolutions": {
>   "jiti": "1.12.7"
> }
> ```
> 
> and then `yarn install`
> 
> it is working now. Thanks



> hello, my issue is solved. But is there any update on the issue? I want to know the reason of the issue exactly.
> 
> My node is : 14.16.1 npm: 6.14.12
> 
> for other dependencies, I can not upgrade the node. So, I was expecting nuxt to be worked in this version. I have tried this
> 
> ```
> "resolutions": {
>   "jiti": "1.12.7"
> }
> ```
> 
> and then `yarn install`
> 
> it is working now. Thanks

if I use npm install, how to solve it

**Comment by lucasalvesp1** [comment]
Aqui a versão 14.19 do node resolveu

sudo npm cache clean -f
sudo npm install -g n
sudo n 14.19

**Comment by danielroe** [comment]
This was an issue with a dependency using the 'new' `node:` protocol. You can work around this kind of thing in future by using the latest node 14, which supports it, or a newer node version.

This particular issue was resolved upstream, so I'm closing here.
