### ISSUE TITLE
Cannot import module '@nuxt/builder'

### ISSUE THREAD

**Issue by bbhxwl** [nuxt/nuxt#10882]
Nuxt @ v2.15.8

<img width="752" alt="image" src="https://user-images.githubusercontent.com/26525599/210800419-1a8016c5-699a-4c02-8b6a-90781c75f726.png">

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by liqingyi123** [comment]
Check your dependencies, I'll just remove and reinstall it once, and empty the npm cache if necessary`npm cache clean --force`

**Comment by bbhxwl** [comment]
> Check your dependencies, I'll just remove and reinstall it once, and empty the npm cache if necessary`npm cache clean --force`

I seem to know that there is already a program running, and this will happen.
