### ISSUE TITLE
Do not use built-in or reserved HTML elements as component id: s   

### ISSUE THREAD

**Issue by bbhxwl** [nuxt/nuxt#10896]
I have this error, but I have checked all the. vue files and found no naming problems. There are only 10 vue files in total. It is easy to check all of them, but I just don't know why this error occurs. How do I know which file it is?

![image](https://user-images.githubusercontent.com/26525599/211994662-02067f90-fa2e-4186-939c-975888b53923.png)

**Comment by danielroe** [comment]
If you provide a reproduction I am happy to take a look.
