### ISSUE TITLE
vuex is not installed automatically

### ISSUE THREAD

**Issue by wonkyungup** [nuxt/nuxt#10898]
![스크린샷 2023-01-15 오후 10 52 15](https://user-images.githubusercontent.com/34180230/212544755-12fe905b-f5a1-4afd-9396-cc8d8de7e37f.png)

If I want to use vuex, do I have to install it separately?

**Comment by wonkyungup** [comment]
nuxt version is "2.7.10"

**Comment by Baroshem** [comment]
Hey,

I think it should come by default but you have to enable it by creating a simple index.js file inside store directory

The store directory contains your Vuex Store files. The Vuex Store comes with Nuxt out of the box but is disabled by default. Creating an index.js  file in this directory enables the store.


https://nuxtjs.org/docs/directory-structure/store/

**Comment by wonkyungup** [comment]
@Baroshem 
It's been resolved. Thank you for your help. I will close the resolved issue. happy new year
