### ISSUE TITLE
Custom path for static directory

### ISSUE THREAD

**Issue by tomardern** [nuxt/nuxt#10904]
### Is your feature request related to a problem? Please describe.
We'd like to change directory which is used for "static" files.

On the https://nuxtjs.org/docs/directory-structure/static/ it outlines "This directory cannot be renamed without extra configuration.", although does not go into detail which extra configuration is required to do this.

### Describe the solution you'd like
Some way of setting the static folder directory

### Describe alternatives you've considered
N/a

### Additional context
N/a

**Comment by danielroe** [comment]
This is now possible in Nuxt 3 via the `dir.public` option in nuxt.config: https://nuxt.com/docs/api/configuration/nuxt-config#public

**Comment by tomardern** [comment]
Thanks - I should have clarified this is for Nuxt 2.

**Comment by danielroe** [comment]
You should be able to do that as well using the `dir.static` folder.

**Comment by carbdias** [comment]
Do you know how to do it for Nuxt 3 ?

**Comment by danielroe** [comment]
Set `dir.public` as I commented above.

**Comment by codeDevStory** [comment]
> Set `dir.public` as I commented above.

Incorrect, we're talking about the folder that static resources should go to when they're packaged.
And you're talking about the folder where the static resources folder is when it's being developed

**Comment by danielroe** [comment]
@codeDevStory I don't believe anyone has asked about that yet, but that is also configurable via `nitro.output.publicDir`.
