### ISSUE TITLE
app/router.options pages are not in `page:extend` hook

### ISSUE THREAD

**Issue by huang-julien** [nuxt/nuxt#12335]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `2.0.0-27860563.409fe2b`
- Package Manager:  `pnpm@7.8.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/nuxt/framework/blob/main/packages/nuxt/src/pages/module.ts

### Describe the bug

Hi :wave: , I'm not sure if this is a bug or if this should be converted into a discussion.

  Currently i'm using the `router.options.ts` on one project to define my routes. I've tried to use `@nuxtjs/i18n` for lang translation but i've been struggling to make it work. 

  i18n use `page:extends` to prefix routes. However, `router.options.ts` routes are being added after the `page:extend` hook as you can see [here ](https://github.com/nuxt/framework/blob/9de94c21cf7fa7008c75f859e0299e3f1c0b445c/packages/nuxt/src/pages/module.ts#L187-L211) .
  We also can't add it through the nuxt config due to the type `RouterConfigSerializable`.

  Can we maybe merge the routes generated from the `page` dir and those provided by `router.options.ts` ?

**Comment by danielroe** [comment]
`router.options.ts` allows _runtime_ extension, but `pages:extend` is a build-time extension. So I don't think it's possible to merge routes from these two different contexts. I think this is probably more a feature request for i18n but I'm very happy to be in that discussion to see if there's anything missing from the framework side to make it possible.
