### ISSUE TITLE
export `@nuxt/kit` utils from `nuxt/kit` for direct use

### ISSUE THREAD

**Issue by HigherOrderLogic** [nuxt/nuxt#12339]
### Describe the feature

When implementing modules locally within a project, developers would have to explicitly install `@nuxt/kit` package for things like `defineNuxtModule`, `createResolver`,... (of course you can use it without installing because it's `nuxt`'s direct dependency, but using something not listed in `package.json` probably isn't a good idea). So my proposal is to export it in `nuxt` package,  ex: `nuxt/kit`.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by Baroshem** [comment]
I think having it exported is a good idea as well :) 

I can definitely find use cases for local modules like that.

**Comment by Strift** [comment]
I agree with @HigherOrderLogic and @Baroshem.

In Nuxt 3, modules seems like the better fitted solution for encapsulating logic to handle external services. 

It feels weird to me that I need to include a package that seems designed for publishing modules (`@nuxt/kit`), just to be able to create local modules. 

Plugins utilities like `defineNuxtPlugin` are currently exported, and it's useful for everyone, not just package maintainers. I think we could have a similar approach for modules.

Now, it's totally possible that I'm misusing modules. If that's the case I'd love to know alternative solutions. :)
