### ISSUE TITLE
Failed to use `generate` when extends from a GitHub repo

### ISSUE THREAD

**Issue by esoubiran-aneo** [nuxt/nuxt#12347]
### Environment

RootDir: C:/Users/esoubiran/dev/ArmoniK.Api/.docs                                                                                                                               15:19:52
Nuxt project info:                                                                                                                                                              15:19:52

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `app`, `extends`, `studio`, `content`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

- Create a project
- Push it to GitHub
- Create another command
- Extends the second from the first using `extends: "github:<1_project_name>"
- Run `npm run generate` in the second project

### Describe the bug

```txt
 ERROR  [vite]: Rollup failed to resolve import "vue/server-renderer" from "../../../.cache/c12/github_esoubiran-aneo_armonik-docs-theme/components/global/Logo.vue".           15:19:42  
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`


 ERROR  [vite]: Rollup failed to resolve import "vue/server-renderer" from "../../../.cache/c12/github_esoubiran-aneo_armonik-docs-theme/components/global/Logo.vue".           15:19:42  
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`

  This is most likely unintended because it can break your application at runtime.
  If you do want to externalize this module explicitly add it to
  `build.rollupOptions.external`
  at onRollupWarning (/C:/Users/esoubiran/dev/ArmoniK.Api/.docs/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:45832:19)
  at onwarn (/C:/Users/esoubiran/dev/ArmoniK.Api/.docs/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:45603:13)
  at Object.onwarn (/C:/Users/esoubiran/dev/ArmoniK.Api/.docs/node_modules/rollup/dist/es/shared/rollup.js:23263:13)
  at ModuleLoader.handleResolveId (/C:/Users/esoubiran/dev/ArmoniK.Api/.docs/node_modules/rollup/dist/es/shared/rollup.js:22158:26)
  at /C:/Users/esoubiran/dev/ArmoniK.Api/.docs/node_modules/rollup/dist/es/shared/rollup.js:22119:26
```

**Comment by miclgael** [comment]
Just a note that if you clone the repo locally and point directly to it the generate command works as expected.

**Comment by baixiaoyu2997** [comment]
@danielroe , sorry to bother you, I need to choose a scheme between `git submodule` and `extends with github` as `base repo`, and need work with `vercel`. so, will this problem be fixed in the near future, if not, then I can only choose `submodule`

**Comment by nossienl** [comment]
> Hi @danielroe, reproduction for `nossie` on Discord.
> 
> 1. Project extending: https://stackblitz.com/edit/nuxt-starter-supewq?file=nuxt.config.ts,pages%2Findex.vue
> 2. The nuxt layer: https://stackblitz.com/edit/nuxt-starter-mrvhpg?file=README.md,components%2Fcool-component.vue
> 3. The nuxt layer (repo): https://github.com/miclgael/nuxt-repro-layers-2
> 
> A different (better?) error is produced on Stackblitz with Nuxt 3.6.1
> 
> ```
> ❯ npm run generate
> 
> > generate
> > nuxt generate
> 
> Nuxi 3.6.1                                                          7:02:08 pm
> Nuxt 3.6.1 with Nitro 2.5.1                                         7:02:08 pm
> 
> [7:02:10 pm]  ERROR  request to https://github.com/miclgael/nuxt-repro-layers-2/archive/main.tar.gz failed, reason: socket hang up
> 
>   at FetchBaseError (node_modules/node-fetch-native/dist/shared/node-fetch-native.d7878b77.mjs:4707:9)
>   at FetchError (node_modules/node-fetch-native/dist/shared/node-fetch-native.d7878b77.mjs:4735:3)
>   at fetch/</< (node_modules/node-fetch-native/dist/shared/node-fetch-native.d7878b77.mjs:6405:11)
>   at EventEmitter.prototype.emit (https://nuxtstartersupewq-zip2.w-corp.staticblitz.com/blitz.a19575a2.js:35:143926)
>   at v.prototype.emit (https://nuxtstartersupewq-zip2.w-corp.staticblitz.com/blitz.a19575a2.js:35:2139960)
>   at socketOnEnd (https://nuxtstartersupewq-zip2.w-corp.staticblitz.com/blitz.a19575a2.js:35:1419556)
>   at EventEmitter.prototype.emit (https://nuxtstartersupewq-zip2.w-corp.staticblitz.com/blitz.a19575a2.js:35:144042)
>   at v.prototype.emit (https://nuxtstartersupewq-zip2.w-corp.staticblitz.com/blitz.a19575a2.js:35:2139960)
>   at endReadableNT (https://nuxtstartersupewq-zip2.w-corp.staticblitz.com/blitz.a19575a2.js:35:545422)
>   at _0x3ddf8a (https://nuxtstartersupewq-zip2.w-corp.staticblitz.com/blitz.a19575a2.js:42:151241)
>   at _0x4ea91e/< (https://nuxtstartersupewq-zip2.w-corp.staticblitz.com/blitz.a19575a2.js:42:150983)
> ```

thanks for tagging me ! @miclgael 

so to be sure there is no issue when using a mono repo or npm package (because the code is  located next or inside your project ), but when using the external github/gitlab repo extend it breaks on build

**Comment by miclgael** [comment]
AFAIK, that sounds about correct to me @nossienl :)
