### ISSUE TITLE
I'm not able to install nuxt and nuxi getting errors

### ISSUE THREAD

**Issue by anujkamboj7** [nuxt/nuxt#12354]
### Environment

Nuxt project info:                                                                                                                                                                                               19:38:27

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.13.0`
- Nuxt Version:     `0.0.0`
- Nitro Version:    `-`
- Package Manager:  `unknown`
- Builder:          `webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

#

### Describe the bug

I can't install nuxt 3 by using npx, npm or pnpm. Getting error like can't fetch something. Can you please help me in installation. I've updated everything given in the docs.

### Additional context

#

### Logs

```shell
error-while-creating-nuxt3-project-failed-to-download-template-from-registry
```

**Comment by mfazail** [comment]
![image](https://user-images.githubusercontent.com/80394548/215750558-5b0551f2-0a7f-4356-b09a-9d6b9cd4a8e5.png)

```
platform: Windows 11 (22H2)
node: v18.13.0
pnpm: 7.25.1
```

Same error with both npm and pnpm, tried on cmd and powershell.

**Comment by saatana97** [comment]
I got same error.
Tried changing DNS or using a VPN and setting up a proxy, but to no avail.
Maybe cause  by China's network env?

**Comment by mfazail** [comment]
I tried with ad guard dns  👇🏻

"Method №2: Configure AdGuard DNS manually"
 https://adguard-dns.io/en/public-dns.html#:~:text=Method%20%E2%84%962%3A%20Configure%20AdGuard%20DNS%20manually

Give it a try hopefully it will work 😊
