### ISSUE TITLE
Pages are rendered before fetching data from api

### ISSUE THREAD

**Issue by MarreKs** [nuxt/nuxt#12363]
### Environment

Operating System: Linux
Node Version: v16.14.2
Nuxt Version: 3.0.0
Nitro Version: 1.0.0
Package Manager: npm@7.17.0
Builder: vite
User Config: -
Runtime Modules: -
Build Modules: -

### Reproduction

Same as here: [#9908](https://github.com/nuxt/nuxt.js/issues/12487)

### Describe the bug

This bug has already been reported but has gone unanswered. Maybe I can shed more light on this problem, because it just happened to me too and there is no easy way to fix it

If you are on a nested route (e.g. /users/1/posts) and you click on a link leading to a specific post (e.g. /posts/1001) the page is rendered before fetching data from the api.

Before the function is await and there is no lazy parameter.

```js
const { data: post } = await useAsyncData(() =>
  useApi(`/posts/${route.params.id}`)
)
```

However, when entering the post's address directly through the browser - everything works fine. Nuxt waits for input from the api then renders the post page.

**Comment by niklasfjeldberg** [comment]
I am experiencing the same issue, and it seems like there is a similar issue here: [SSR & Await (directus example) #18565](https://github.com/nuxt/nuxt/issues/18565)

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/12487.
