### ISSUE TITLE
Ability to add your own keyed functions 

### ISSUE THREAD

**Issue by cawa-93** [nuxt/nuxt#12369]
### Describe the feature

Several composable functions ( `useState`, `useFetch`, `useAsyncData`, `useLazyAsyncData`, `useLazyFetch`) provide auto-key generation that is unique to the file name and line number of the instance of function call. However, this makes it impossible to create your own wrappers around these functions, because then the auto-generated key will always be the same for any wrapper-function call.

```ts
// composables/useAsyncSpecifiedData.ts
export function useAsyncSpecifiedData(params) {
	// ... do some work
	const handler = createHandler( params )
	const options = createOptions( params )
	return useAsyncData(handler, options) // <- the unique key always generated exactly for this file+line
}
```
I would like to have oportynity to somehow expand keyed functions with myown
https://github.com/nuxt/framework/blob/51bc6e44fef6e4a249946ba910a497089b089a64/packages/vite/src/plugins/composable-keys.ts#L15-L17

So that nuxt will generates a unique key directly for the wrapper function call, which will be passed down in `useAsyncData`. Since it is work for `useLazyAsyncData`
https://github.com/nuxt/framework/blob/51bc6e44fef6e4a249946ba910a497089b089a64/packages/nuxt/src/app/composables/asyncData.ts#L263-L274

### Additional information

- [x] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by Baroshem** [comment]
I think wrapping built in functionalities is not a good practise to be honest. 

I am closing this issue as there was no further attention in over a month. 

Feel free to reopen it though if needed :)

**Comment by pi0** [comment]
Related: https://github.com/nuxt/nuxt/issues/14736

**Comment by danielroe** [comment]
I think this would be a nice feature, and we'd welcome contribution on this. Maybe we could also consider configuration for other magic names, as in unctx transform or pure function annotation plugins.

Thoughts welcome on where the configuration should live.
