### ISSUE TITLE
Extending nitro server using pnpm fails 

### ISSUE THREAD

**Issue by yassilah** [nuxt/nuxt#12394]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.16.1`
- Builder:          `vite`
- User Config:      `extends`, `api`, `hooks`, `sentry`, `tailwindcss`, `runtimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

I tried to make a reproduction extending from a simple Github repo but I get a `socket hang up` error...

### Describe the bug

When extending a Nuxt config using an NPM package and due to the way `node_modules` are stored when using Pnpm, the current RegExp used for Nitro's `esbuild.options.exclude` and for `imports.exclude` options won't include/transform the layer's files.

### Additional context

To fix the issue, I had to change the RegExp to `/(?<=\/)(?:.+\.pnpm\/.+\/)?node_modules\/(.+)$/` in: https://github.com/nuxt/framework/blob/da38c620005596d71f3ae22f33fb2653312515d0/packages/nuxt/src/core/nitro.ts#L30 
and override the default `/[\\/]node_modules[\\/]/` exclude pattern of `unimport` to the same RegExp.

**Comment by danielroe** [comment]
Would you be able to provide a reproduction/ :pray
