### ISSUE TITLE
Prop completion does not work for `<NuxtPage>`

### ISSUE THREAD

**Issue by miosenpai** [nuxt/nuxt#12395]
### Environment

```
- Operating System: `Windows_NT`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `typescript`
- Runtime Modules:  `-`
- Build Modules:    `-`
```

### Reproduction

https://stackblitz.com/edit/github-lbhhuu?file=app.vue

(Since this issue is related to autocomplete behavior, I originally reproduced it in VS Code)

### Describe the bug

`<NuxtPage>`'s props does not appear to be detectable by IDEs such as VS Code. For example, [pageKey](https://nuxt.com/docs/api/components/nuxt-page#example) is valid prop for `<NuxtPage>` but does not show up under completion menu.

![image](https://user-images.githubusercontent.com/5713101/210854660-726eee90-c7cd-4f3c-9593-27fae0c01ceb.png)

### Additional context

I've tried switching between Volar's Take Over Mode and TypeScript Vue Plugin, along with re-enabling the shim in `nuxt.config.ts`, but could not resolve this issue.

**Comment by MikeBellika** [comment]
Seems to also be an issue on `<ClientOnly>`.
`<Teleport>`,`<NuxtLoadingIndicator>`,`<NuxtLayout>,<NuxtLink>` all seem to have working auto complete in my IDE.

**Comment by MikeBellika** [comment]
Is this fixed by https://github.com/nuxt/framework/pull/9204?

**Comment by danielroe** [comment]
Yes, this should be resolved in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/), or in the next release.

Let me know if not and I'll reopen.

**Comment by miosenpai** [comment]
I created a project using the edge channel and the issue appears to still be present.
```
- Operating System: `Windows_NT`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.0.1-rc.0-27909450.eac787e`
- Nitro Version:    `2.0.0-27909319.113d31e`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
```
![image](https://user-images.githubusercontent.com/5713101/214340721-03835908-8449-4d48-b28e-692d348ce43a.png)
