### ISSUE TITLE
Bug: bad error page on dev server

### ISSUE THREAD

**Issue by kaname-png** [nuxt/nuxt#12392]
### Environment

Nuxi 3.0.0                                                                                                                                                                                   12:06:36
                                                                                                                                                                                             12:06:37
RootDir: C:/Users/inmor/Documents/Proyectos/biscuit/biscuit-web                                                                                                                              12:06:37
Nuxt project info:                                                                                                                                                                           12:06:37

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v19.3.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.0.0`
- Builder:          `vite`
- User Config:      `modules`, `build`, `app`, `runtimeConfig`, `routeRules`, `nitro`, `tailwindcss`, `colorMode`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.2.0`, `nuxt-icon@0.1.8`, `@nuxt/image-edge@1.0.0-27840416.dc1ed65`, `@nuxtjs/fontaine@0.2.4`, `@nuxtjs/color-mode@3.2.0`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new                                                                                                                             12:06:37

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org

### Reproduction

https://github.com/oasisjs/biscuit-web

## Steps
1. Clone repository
2. Run `pnpm dev`
3. Go to `/utilities/core` route and change to for example `/utilities/x`

Code: https://github.com/oasisjs/biscuit-web/blob/main/pages/utilities/%5Bname%5D.vue#LL195-L197C2

### Describe the bug

When trying to display the 404 error page, it appears below the current view, and is not displayed at full size even if the fatal option is used.

### Additional context

In production the error does not appear, but in development it does.

# Error video

https://user-images.githubusercontent.com/56084970/212559075-0de21ca0-192d-42a5-97bf-7af5c726c352.mp4

### Logs

```shell
No errors in console.
```

**Comment by oritwoen** [comment]
You don't have `await` before `useFetch` which makes the code execute simultaneously, so checking if the page exists is performed simultaneously with fetching the content, and that's why it happens :)

And better to use `throw createError` instead `showError`. I created pull request for you ;)

https://github.com/oasisjs/biscuit-web/pull/44
