### ISSUE TITLE
AsyncData with a shallow ref

### ISSUE THREAD

**Issue by P4sca1** [nuxt/nuxt#12406]
### Describe the feature

Right now, `useAsyncData` uses a `ref` to store the data. This means that, when returning an object (or an array), the whole object will be made reactive. This can have unwanted performance penalties, depending on the size of the data that is fetched, and depending on the use-case, is often unneeded when returning static data from an API call that is not meant to be changed.
It would be great if you could use a `shallowRef` instead.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by Baroshem** [comment]
This could really make a significant difference IMO. I can work on this in the upcoming weeks once we decide that it should be implemented @danielroe 🙂
