### ISSUE TITLE
Missing required prop / Cannot read properties of undefined. To summarize: problem with useAsyncData/useFetch or with premature rendering

### ISSUE THREAD

**Issue by mblachlov24** [nuxt/nuxt#12487]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-6ep3af?file=pages/users/[id].vue

### Describe the bug

When entering a specific task by directly entering the url, the problem does not occur (domain.com/todos/3).

However, when using nuxt navigation, there is a problem when wanting to go to a specific task from the user's page.

1) Click on any user
2) Click on any todo in user page
3) You will get many errors in the console

![image](https://user-images.githubusercontent.com/109919875/210217879-f3d37cf6-dda2-4ba8-be8d-c15cc5efdc03.png)

![image](https://user-images.githubusercontent.com/109919875/210217904-6eeb8a1f-a245-4b2a-b3ed-8832482a9134.png)

This seems like a fairly common case and a basic thing that doesn't work though.

**Comment by k16e-me** [comment]
I'm experiencing this issue, pretty similarly but having to do with loading data from Storyblok. I put it as an issue here https://github.com/storyblok/storyblok-nuxt/issues/211#issuecomment-1401957011 on the Storyblok Github.

**Comment by niklasfjeldberg** [comment]
I am experiencing the same issue, and it seems like there is a similar issue here: https://github.com/nuxt/nuxt/issues/18565

**Comment by toniengelhardt** [comment]
I also see this error in Sentry, but without any data fetching. I think it can happen when an item that is used in a component is deleted from the store. The component somehow still tries to access it, which should not happen, bc according to typescript the object can never be undefined if it is required...

**Comment by danielroe** [comment]
This is now resolved with the latest suspense fixes.
