### ISSUE TITLE
Auto add `.nojekyll` to `.output/public` on generate for Github Pages hosting

### ISSUE THREAD

**Issue by mrleblanc101** [nuxt/nuxt#12480]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `2.15.8`
- Nitro Version:    `-`
- Package Manager:  `npm@8.3.1`
- Builder:          `webpack`
- User Config:      `target`, `router`, `head`, `loading`, `css`, `plugins`, `components`, `buildModules`, `modules`, `toast`, `image`, `content`, `styleResources`, `eslint`, `stylelint`, `generate`, `build`
- Runtime Modules:  `@nuxtjs/svg@0.4.0`, `@nuxt/content@1.15.1`, `cookie-universal-nuxt@2.2.1`, `vue-toastification/nuxt`, `@nuxt/image@0.7.1`
- Build Modules:    `@nuxtjs/style-resources@1.2.1`, `@nuxtjs/eslint-module@3.1.0`, `@nuxtjs/stylelint-module@4.1.0`
------------------------------

### Reproduction

.

### Describe the bug

I've been trying all night to figure out why my deploy to Github Pages wasn't working.
Seems like Nuxt 3 does not add `.nojekyll` to `.output/public` automatically.
Nuxt 2 added it automatically to the `dist/` folder.

**Comment by danielroe** [comment]
This is now implemented with the new `github-pages` present in Nitro 2.4+.

**Comment by gosferano** [comment]
How is it used?

**Comment by esoubiran-aneo** [comment]
> How is it used?

Can you tell more? I'm not sure to understand

**Comment by gosferano** [comment]
I think I had a regular case of duck debugging happening. Was wondering how to apply this `github-pages` preset that was mentioned above and wasn't really clear with my question. I've resolved it myself.
