### ISSUE TITLE
executing defineCachedEventHandler() multiple times in Nuxt's nitro built in api server results in JSON parse error on result.

### ISSUE THREAD

**Issue by yabuking84** [nuxt/nuxt#12508]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.17.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Fresh install. 

app.vue

```
<template>
  <div>
<h1>test</h1>
  </div>
</template>

<script setup lang="ts">
const route = useRoute();
const id = route.query.id;
const go1 = async () => {
  const data = await useFetch(
    "/api/test?id="+id
  );
  console.log("data1",data.data.value)
};

const go2 = async () => {
  const data = await useFetch(
    "/api/test?id=2"
  );
  console.log("data2",data.data.value)
};

const go3 = async () => {
  const data = await useFetch(
    "/api/test?id=3"
  );
  console.log("data3",data.data.value)
};

const go4 = async () => {
  const data = await useFetch(
    "/api/test?id="+id
  );
  console.log("data4",data.data.value)
};

await go1();
await go2();
await go3();
await go4();
</script>
```

server/api/test.ts
```
export default defineCachedEventHandler(
  async (event) => {
    const query = getQuery(event);
    const id = query.id;

    const result = await $fetch('https://fakestoreapi.com/products/'+id);

    return result;
  },
  { swr: true }
);
```

### Describe the bug

If you keep reloading (http://localhost:3000?id=1 in browser) multiple times  like maybe 20 to 30 times. This error occurs:

`[nuxt] [request error] [unhandled] [500] Cannot create property 'expires' on string '{"value":{"code":200,"headers":{"etag":"W/\"EPJ1Dcb7kt\"","last-modified":"Wed, 28 Dec 2022 14:45:48 GMT","cache-control":"stale-while-revalidate"},"body":{"id":3,"title":"Mens Cotton Jacket","price":55.99,"description":"great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.","category":"men's clothing","image":"https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg","rating":{"rate":4.7,"count":500}}},"mtime":1672238748634,"integrity":"4ACUlfKyBJ"}"expires":1672238749567}'`

Seems like issue inserting expires property. Then when you clear .nuxt folder and rerun 'npm run dev' seems to go away then comes back again after multiple reloads.

**Comment by danielroe** [comment]
This should be resolved in https://github.com/unjs/nitro/pull/861. I can no longer reproduce.

Let me know if you are still experiencing this and we can reopen.

**Comment by alexrodriguezjob** [comment]
Hi we are having this error in production, we have not been able to reproduce in another environment:

```[nuxt] [request error] [unhandled] [500] Cannot create property 'expires' on string '{"expires":1687625881621,"value":{"code":200,"headers":{"etag":"W/\"lWuAVzWlVV\"","last-modified":"Sat, 24 Jun 2023 16:57:02 GMT","cache-control":"s-maxage=60, stale-while-revalidate"},"body":{"total":6,"limit":15,"data":```

We are running nuxt v3.5.2 in a Azure App server running Linux with Node - 16-lts
