### ISSUE TITLE
Nuxt takes a long time to run tests

### ISSUE THREAD

**Issue by EduardoMateos** [nuxt/nuxt#12537]
### Environment

dev

### Reproduction

```
import { describe, test, expect } from 'vitest'
import { setup, $fetch } from '@nuxt/test-utils'

describe('example', async () => {
  await setup({
    // test context options
  })
  test('my test', async () => {
    const html = await $fetch('/')
    expect(html).toMatch('futbol')
  })
})



```

### Describe the bug

Hello, we are migrating from nuxt 2 to nuxt 3 and we want to incorporate tests into the application but for some unknown reason it takes a long time to execute a test.

Our application has around 250 components. Is there a way to not take 72 seconds to run a test? Creating tests like this is very tedious.

PD : thanks for working on nuxt. At futbolfactory.es we trust in the progression of this framework.

### Logs

```shell
✓ tests/product.test.js (1) 71651ms

 Test Files  1 passed (1)
      Tests  1 passed (1)
   Start at  13:39:38
   Duration  72.21s
```

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by madebyfabian** [comment]
Depending on what you're components do, 72s actually is pretty reasonable for 250 components, in my perspective. But yeah as @danielroe said, please add a [minimal reproduction](https://nuxt.com/docs/community/reporting-bugs) so we can look into that properly, thank you 🙏🏻💚
