### ISSUE TITLE
Module Federation Support

### ISSUE THREAD

**Issue by phoenix-ru** [nuxt/nuxt#12638]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3.0.0-27252573.ad7e755`
- Package Manager:  `npm`
- Bundler:          `Webpack`
- User Config:      `buildModules`, `vite`, `nitro`
- Runtime Modules:  `-`
- Build Modules:    `./modules/build/ModuleFederationModule.ts`

### Describe the bug

Module Federation has been [implemented](https://github.com/nuxt/framework/discussions/870) on server-side (also see attached [repository](https://github.com/phoenix-ru/nuxt3-module-federation-example)).

However, the client needs an async boundary to function, such as converting:
```js
// main.ts
import { createApp } from 'vue'
import App from './App.vue'
```

to

```js
// main.ts
import('./bootstrap')

// bootstrap.ts
import { createApp } from 'vue'
import App from './App.vue'
```

As Nuxt is doing a lot of magic under the hood, I think it is best to implement the boundary there rather than doing unstable hacks with the builds. An easy way is to produce an async entry which dynamically imports the current entry, and use an async entry on the client instead. The server builds already have such mechanic.

Unfortunately, I haven't had much time to inspect the sources, so I don't have a PR solving the issue.

It is a critical issue for our company and definitely a killer feature for Nuxt (e.g. Next only offers CSR MF support using a paid package :wink:)

### Reproduction

Took me a long time, here it is :tada: 
https://github.com/phoenix-ru/nuxt3-module-federation-example

**Comment by manniL** [comment]
Fixed via https://github.com/nuxt/framework/pull/2223
