### ISSUE TITLE
Support unenv for client to polyfill Node.js imports

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt#12786]
[unjs/unenv](https://github.com/unjs/unenv) provides a powerful shimming framework for Node.js internals and other dependencies to be Node-free. We are already using it for server and nitro while we can use preset in webpack and vite to avoid issues when a library is depending on Node.js imports or wrongly importing from node built-ins

**Comment by ennioVisco** [comment]
I believe this has been resolved long ago @pi0 :)

**Comment by pi0** [comment]
We might cancel the idea but unenv is not integrated for vite's client-side build yet. Node.js dependencies won't be mocked.

**Comment by pi0** [comment]
(updated to focus on client-only. server-side, nitro should bundle with platform aware presets)

**Comment by manniL** [comment]
FWIW: This works "manually" already, but a neat auto-integration would be lovely 👍🏻
