### ISSUE TITLE
exports is not defined is ES module scope - still not working

### ISSUE THREAD

**Issue by sweepy84** [nuxt/nuxt#12803]
### Environment

Nuxt project info:                                                                                                                                                                           20:15:00

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27292434.d68318f`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `build`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/sweepy84/nuxt3

### Describe the bug

A fresh nuxt3 project fails when installing 'aws-amplify' as a plugin.

### Replication of Bug

Steps performed
1. npx nuxi init nuxt3
2. yarn install
3. yarn add aws-amplify
4. Added 'amplify.ts' to /plugins directory
5. Added transpiling config to 'nuxt.config.ts'
6. yarn dev

### Additional context

I know this was logged here https://github.com/nuxt/nuxt.js/issues/12688
and was supposed to be fixed with mlly fix but this did not solve problem for me even with latest fixes!

### Logs

```shell
exports is not defined in ES module scope
  at $id_8b3bdae3 (file://./.nuxt/dist/server/server.mjs:3539:23)  
  at __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:31429:9)  
  at __ssrLoadModule__ (file://./.nuxt/dist/server/server.mjs:31376:25)  
  at ssrImport (file://./.nuxt/dist/server/server.mjs:31401:13)  
  at $id_d9f142a1 (file://./.nuxt/dist/server/server.mjs:3206:37)  
  at async __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:31429:3)
```

**Comment by manniL** [comment]
Tracked in https://github.com/nuxt/nuxt/issues/13277#issuecomment-1397293299
