### ISSUE TITLE
Auto import for types like `Ref`

### ISSUE THREAD

**Issue by webfansplz** [nuxt/nuxt#12808]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.16.1`
- Nuxt Version:     `3.0.0-27277498.850ef69`
- Package Manager:  `pnpm@6.17.1`
- Bundler:          `Vite`
- User Config:      `env`, `alias`, `srcDir`, `dev`, `build`, `publicRuntimeConfig`, `buildModules`, `css`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `@vueuse/core/nuxt@6.8.0`, `@pinia/nuxt@0.1.2`, `./app/t5-ui/nuxt`

### Reproduction

-

### Describe the bug

I want to use `Ref` to type assertions, But: 

![image](https://user-images.githubusercontent.com/22515951/141795858-5d992bcf-9c53-46d4-b0ab-51112e551bf1.png)

**Comment by madebyfabian** [comment]
Hey, due to the TS limitation being something upstream, is still still relevant, or can it be closed?

**Comment by madebyfabian** [comment]
@ennioVisco True thing, https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#support-for-export-type

Let's keep it open then 😊

**Comment by manniL** [comment]
Upstream label removed - maybe we can tinker with an implementation for TS5 🤔
