### ISSUE TITLE
Dynamic glob imports does not work with vite

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt#12806]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.16.0`
- Nuxt Version:     `3.0.0-27265876.3cd4494`
- Package Manager:  `npm@7.17.0`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Describe the bug

Unpredictable dynamic imports like `import(`~/data/${name}json)` does not work with vite (dev-bundler)

### Reproduction

https://stackblitz.com/edit/github-obezmd?file=app.vue

### Additional context

As a workaround, one can use webpack using `vite: false` in `nuxt.config`.

Missing implementation is [here](https://github.com/nuxt/framework/blob/9b8d44d130fb85397053185924f3b6b86243b362/packages/vite/src/dev-bundler.ts#L158) but we probably need more to fix this.

### Logs

```shell
Cannot read properties of undefined (reading 'stubModule')
at __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:1771:11)
at __ssrLoadModule__ (file://./.nuxt/dist/server/server.mjs:1762:25)
at ssrImport (file://./.nuxt/dist/server/server.mjs:1787:13)
at ssrDynamicImport (file://./.nuxt/dist/server/server.mjs:1798:12)
at eval (file://./.nuxt/dist/server/server.mjs:1678:70)
at Module.withAsyncContext (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7295:21)
at setup (file://./.nuxt/dist/server/server.mjs:1678:47)
at _sfc_main.setup (file://./.nuxt/dist/server/server.mjs:1708:23)
at callWithErrorHandling (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6615:22)
at setupStatefulComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6241:29)
```

**Comment by NeoPrint3D** [comment]
This issue is still plaguing my production codebase in 2023 is there any ergonomic fixes. I found a way by importing the images in the script tag, but it feels like there should be a better way.

**Comment by NeoPrint3D** [comment]
### I found a solution to the issue on nuxt v3.12
```html
<img :src="`/_nuxt/assets/icons/${tab.icon}`" alt="" />
```

I first imported the image then console.log the component and it spits out "/_nuxt/assets/icons/something.svg"

which I put into the img tag

**Comment by AnzhiZhang** [comment]
This is bothering me, I can't even import the function of the Nuxt module
Example: https://stackblitz.com/edit/github-wtjope

**Comment by manzolidev** [comment]
Is there is any update on this issue? :(

**Comment by danielroe** [comment]
@AnzhiZhang I think that might be an issue to raise upstream with `@nuxt/content` - it's not related to this issue.

**Comment by caoxiemeihao** [comment]
Actually, It is limited by [Vite's `resolve` function](https://github.com/vitejs/vite/blob/b5a24851fb2ea779464bf850bb4e5ff6f45edd78/packages/vite/src/node/plugins/dynamicImportVars.ts#L98-L101), which has certain restrictions.
If we force try to match paths as mush as possible, will this break Vite's design? @poyoho

**Comment by poyoho** [comment]
use the resolve function to replace the alias paths in `importSource`. Do you mean try to match paths as mush as possible before `vite/dynamicImportVars` plugin? I think it is ok.

**Comment by caoxiemeihao** [comment]
At present, [vite-plugin-dynamic-import](https://github.com/vite-plugin/vite-plugin-dynamic-import) implements its own `resolve` function, only it looks i bit ugly.
`vite/dynamicImportVars` Care to re-implement the resolve function?

**Comment by poyoho** [comment]
IMO, vite plugin also can get the `ctx.resolve`, the `vite/resolve` is had too many feature. And now `vite/dynamicImportVars` no support alias?

**Comment by caoxiemeihao** [comment]
Here some cases:
```js
// With out ends slash
import(`./foo${id}`)

// Only alias here
import(`@/${id}`)

// node_modules's module and mybe load the `style` files.
import('npm-lib/theme' + themePath)
```

**Comment by danielroe** [comment]
I think this can be closed. Vite has its own syntax for glob imports: https://vitejs.dev/guide/features.html#glob-import.

@antfu Feel free to reopen if you are investigating this at all or have ideas for improving it 🙏
