### ISSUE TITLE
HMR does not pick up updates to data

### ISSUE THREAD

**Issue by radusuciu** [nuxt/nuxt#12822]
### Environment

Running on WSL but have had the same issue in a containerized application..

Tested in latest Firefox and Chrome with identical results.

Nuxt CLI v3.0.0-27288761.d3fb512                                                                                                                                                                           
RootDir: ...                                                                                                                                                   
Nuxt project info:                                                                                                                                                                                         
------------------------------
- Operating System: `Linux`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27288761.d3fb512`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/radusuciu/nuxt3-app

![repro](https://user-images.githubusercontent.com/1108600/142737550-6fe65eeb-c800-4f4c-b496-c81080e5c9a4.gif)

### Describe the bug

Updated data is not picked up by HMR. Updating the template is. Data updates are reflected after a full refresh only.

Potentially related to nuxt/nuxt.js#11956 but I don't see any errors and it isn't sporadic - it just doesn't work even though Vite does seem to pick up the updates judging by the "Vite server built in XXms" logs messages and "[vite] hot updated: /app.vue" output in the console.

### Additional context

I have no issues with HMR in nuxt2, nor if I use vite by itself.

**Comment by madebyfabian** [comment]
Is this still an issue with current stable nuxt releases? Or can it be closed?

**Comment by radusuciu** [comment]
I just verified that this is fixed with the latest version of nuxt! Thank you!
