### ISSUE TITLE
Polyfill cjs globals for vite

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt#12830]
Ref nuxt/framework#1835, nuxt/bridge#190

Vite considers source input as native ESM while some dependencies might depend on Node.js/CJS globals like `module` and `global`. Doing polyfill can mitigate this potential issue (also making it more consistent with webpack that handles CJS at some level)

We can do it with unenv (#1502) or before that...

**Comment by Ibochkarev** [comment]
+1

**Comment by bmulholland** [comment]
FYI, this is preventing nuxt/storybook from adding Nuxt 3 support: https://github.com/nuxt-community/storybook/pull/385
