### ISSUE TITLE
Navigating away and back looses the styling of the root component element from its parent page (using style scoped and fragments)

### ISSUE THREAD

**Issue by kevhof** [nuxt/nuxt#12921]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27303148.ac98373`
- Package Manager:  `npm@8.1.0`
- Bundler:          `Vite`
- User Config:      `publicRuntimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://codesandbox.io/s/zealous-dust-8ilwp?file=/pages/index.vue

### Describe the bug

[It should be possible to style the root element in a child component from the parent one - here a page](https://vue-loader.vuejs.org/guide/scoped-css.html#child-component-root-elements) using `<style scoped>`. However, when using [fragments](https://v3.vuejs.org/guide/migration/fragments.html#fragments) in the child component, it doesn't work anymore after navigating away from the page and back to the page again.

I am not sure if it's a bug or if it's me making some mistake ?

**Comment by manniL** [comment]
A workaround might be using `getCurrentInstance()?.vnode.scopeId` 🤔

Example: https://github.com/youzan/vant/pull/12327/files

**Comment by danielroe** [comment]
Let's track in the upstream vue issue. 🙏
