### ISSUE TITLE
hydration error with JSX + spaces

### ISSUE THREAD

**Issue by yanstars** [nuxt/nuxt#12998]
### Environment

Nuxt CLI v3.0.0-27319101.3e82f0f
RootDir: /home/projects/github-l11tqv
Nuxt project info: 

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.16.0`
- Nuxt Version:     `3.0.0-27319101.3e82f0f`
- Package Manager:  `npm@7.17.0`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-l11tqv

### Describe the bug

this is something wrong in nuxt with jsx when i render a var

![image](https://user-images.githubusercontent.com/49805955/145686093-484388c5-eb5c-427f-a13b-a47857216aed.png)

![image](https://user-images.githubusercontent.com/49805955/145686045-ad7c20dd-7bec-49b3-af23-84900355ec29.png)

**Comment by inomata137** [comment]
I'm using v3.5.0 and have the same issue.
The code below results in hydration mismatch.
```tsx
// pages/index.vue
export default defineComponent({
  setup() {
    const world = ref('world')
    return () => (
      <div>
        Hello, {world.value}!
      </div>
    )
  },
})
```
This is probably because the server somehow fails to handle several consecutive text nodes.
These are working examples:
```tsx
export default defineComponent({
  setup() {
    const world = ref('world')
    return () => (
      <div>
        Hello, <>{world.value}</>!
      </div>
    )
  },
})
```
```tsx
export default defineComponent({
  setup() {
    const world = ref('world')
    return () => (
      <div>
        {'Hello, ' + world.value + '!'}
      </div>
    )
  },
})
```

**Comment by danielroe** [comment]
Just to be clear, this is an upstream Vue issue: https://github.com/vuejs/babel-plugin-jsx/issues/568.

**Comment by manniL** [comment]
Closing this issue. As Daniel mentioned, there is https://github.com/vuejs/babel-plugin-jsx/issues/568 to track it in the vue org.
