### ISSUE TITLE
When SSR disabled, useFetch does not work properly

### ISSUE THREAD

**Issue by gabjauf** [nuxt/nuxt#13223]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.17.3`
- Nuxt Version:     `3.0.0-27366343.1d741cb`
- Package Manager:  `npm@8.3.0`
- Bundler:          `Vite`
- User Config:      `publicRuntimeConfig`, `typescript`, `ssr`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://codesandbox.io/s/hardcore-bush-6hvrx?file=/pages/index.vue

The code is inside the index.vue
```js
<script>
export default {
  async setup() {
    const { data: token } = await useFetch(
      "https://raw.githubusercontent.com/atom/atom/master/README.md" // example text/plain request
    );
    console.log("TOKEN RECEIVED", token);
    return { token };
  },
  async mounted() {
    console.log("MOUNTED", this.token); // null value
    await new Promise((resolve) => setTimeout(resolve, 1000));
    console.log("MOUNTED AFTER 1s delay", this.token); // value is filled as expected
  },
};
</script>
```

### Describe the bug

When SSR is activated => it works normally.

However when disabled:
The "token" variable is not set right after awaiting the useFetch request, leading to a workaround with a delay.

Expected behavior:
The "token" variable should be set right away after the `await useFetch(...)`

**Comment by danielroe** [comment]
This is no longer reproducible with the latest version of Nuxt.
