### ISSUE TITLE
Browser polyfill for `process.env`

### ISSUE THREAD

**Issue by KaelWD** [nuxt/nuxt#13264]
### Environment

```
Nuxt CLI v3.0.0-27375427.d07d572
RootDir: /home/kael/Documents/vuetifyjs/test-projects/nuxt3/nuxt3-app
Nuxt project info:
------------------------------
- Operating System: `Linux`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-27375427.d07d572`
- Package Manager:  `yarn@1.22.5`
- Bundler:          `Vite`
- User Config:      `css`, `build`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

### Reproduction

Create a plugin with

```js
console.log(typeof process)
console.log(process.env.NODE_ENV)
```

and look at the browser console. 

### Describe the bug

`process` is `{ dev: true, server: false, client: true }`, should be `undefined`
`process.env.NODE_ENV` throws `TypeError: Cannot read properties of undefined (reading 'NODE_ENV')`, should be `'development'`

### Additional context

This works with just vite, idk what you're doing to disable that. It looks like this is also set up correctly for builds with `@rollup/plugin-replace`, so it's only a problem during dev.

**Comment by madebyfabian** [comment]
Hey there, not reproducable in Nuxt 3.1.2 anymore, would close this.

https://stackblitz.com/edit/github-qvmoey?file=nuxt.config.ts
