### ISSUE TITLE
local https server randomly auto refreshes the page

### ISSUE THREAD

**Issue by jyotirmaybarman** [nuxt/nuxt#13276]
### Environment

Node Js : 17.1.0
OS : Fedora 35
Kernel: 5.15.14-200.fc35.x86_64

### Reproduction
```bash
npx nuxi init nuxt3-app
cd nuxt3-app
npm install
npm run dev -- --https
```

### Describe the bug

The page refreshes automatically in a random manner.

**Comment by danielroe** [comment]
This is no longer reproducible. Let me know if you are still experiencing it and we can reopen.
