### ISSUE TITLE
Add hydration caveats section

### ISSUE THREAD

**Issue by doomspec** [nuxt/nuxt#13326]
### Environment

All versions

### Reproduction

See below

### Describe the bug

``` html
<p>
Begin
<div>
  Middle
</div>
End
</p>
```
The above code will cause a hydration mismatch when using SSR but it will be good if SSR is turned off. 

I know it is caused by putting `<div>` in `<p>`, but it is really hard to debug this without proper error information. I thought this is a SSR bug of Nuxt or Vue for a long time. 

Maybe we can provide better reminder in the future versions? Also, we may make the code not work even when SSR is turned off so that people can be aware of this issue in their code.

**Comment by madebyfabian** [comment]
@danielroe also built the `@nuxtjs/html-validator` for nuxt3. Can be closed since this is invalid html.
