### ISSUE TITLE
LayoutTransition inconsistent behaviour

### ISSUE THREAD

**Issue by mwohlan** [nuxt/nuxt#13370]
### Environment

See Stackblitz

### Reproduction

https://stackblitz.com/edit/nuxt-starter-kjrnss?file=pages%2Findex.vue

### Describe the bug

I was using the new definePageMeta function and tried out the transition properties and noticed an unexpected behaviour when transition between layouts. When transitioning from layout a to layout b, the b-leave-transition is applied  and then the b-enter-transition. Imo it should be from a-leave-transition to b-enter-transition. When transitioning between pages within the same layout the transition works as expected ( also in the example)

**Comment by madebyfabian** [comment]
Can anyone confirm that this is still an issue within the currently newest version of nuxt? Or if this was fixed in the RC cycle?

**Comment by mwohlan** [comment]
The issue still persists with the latest edge release (3.2.1). I have update the reproduction lockfile @madebyfabian

**Comment by huang-julien** [comment]
I believe this has been fixed since with the nested Suspense feature/fix
