### ISSUE TITLE
firebase-js-sdk 9 behaviours different in nuxt 3 prod build and dev mode

### ISSUE THREAD

**Issue by niklv** [nuxt/nuxt#13393]
### Environment

Nuxt CLI v3.0.0-27417467.467ab69
RootDir: /Users/niklvov/Projects/nuxt3_firebase_bug
Nuxt project info:

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-27417467.467ab69`
- Package Manager:  `npm@8.3.1`
- Bundler:          `Vite`
- User Config:      `publicRuntimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Minimal repoduction repo: https://github.com/niklv/nuxt3_firebase9_ssr_bug
Instructions and detailed bug description in readme.md.

### Describe the bug

Nuxt3 handles plugin with `firebase-js-sdk` differently in production build and development modes.

**Comment by Hebilicious** [comment]
@danielroe we can close this as we have the nitro firebase preset, and it's working https://github.com/nuxt/nuxt/issues/13962#issuecomment-1616163256

**Comment by danielroe** [comment]
I think this issue is meant to track an issue with the JS package `firebase-js-sdk` and not the firebase preset. Is this still occurring for you @niklv?

**Comment by posva** [comment]
AFAIK this got fixed since https://github.com/vitejs/vite/issues/11114 and the new versions of Firebase
