### ISSUE TITLE
socket hang up when using file watchers

### ISSUE THREAD

**Issue by ilouHD** [nuxt/nuxt#13401]
### Environment

Nuxt CLI v3.0.0-27419629.87eb7d0
RootDir: D:\develop\nuxt3-app
Nuxt project info:

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.11.1`
- Nuxt Version:     `3.0.0-27419629.87eb7d0`
- Package Manager:  `npm@8.0.0`
- Bundler:          `Vite`
- User Config:      `css`, `nitro`, `vue`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

1. If using IntelliJ install the plugin "File Watchers" and add a watcher for SCSS files. May also work with other IDEs.
2. Create a .scss-file (e.g. `/assets/styles/main.scss`)
3. start Vite dev-server
4. edit the created scss-file

### Describe the bug

If using a file watcher for transpiling scss to css and then changing the scss, the watcher generates a new css file. When registering file changes (may be the change of the .scss file) Vite dev-server rebuilds its files and then the following error occurs.

I think the error occurs, because the filewatcher is writing the css-file while Vite dev-server tries to read it.

### Logs

```shell
ERROR  [proxy] socket hang up

  at connResetException (node:internal/errors:691:14)
  at Socket.socketOnEnd (node:_http_client:471:23)
  at Socket.emit (node:events:402:35)
  at Socket.emit (node:domain:475:12)
  at endReadableNT (node:internal/streams/readable:1343:12)
  at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by madebyfabian** [comment]
What's the state on this? Transfer to vite? Close due to being upstream?

**Comment by Atinux** [comment]
I think it can be closed IMO
