### ISSUE TITLE
nuxi dev breaks ANSI escape sequence when run in `concurrently` through `yarn`

### ISSUE THREAD

**Issue by OJFord** [nuxt/nuxt#13415]
### Environment

------------------------------
[updated to reflect simple reproduction]
- Operating System: `Linux`
- Node Version:     `v17.6.0`
- Nuxt Version:     `3.0.0-27439932.78761c2`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

[updated, see first few comments]

```shell
mkdir my-app
cd my-app
yarn init # [enter enter enter... all defaults]
yarn add nuxi
yarn add nuxt3
yarn add concurrently
yarn concurrently 'nuxi dev'
```
then Ctrl-C to SIGINT.

### Describe the bug

After exiting, pressing an arrow key for example (say 'up' to repeat the command) renders `^[[A`.

The exact appearance and whether it functions correctly on then pressing enter (despite looking wrong) may depend on terminal emulator. I tested with Alacritty and rxvt; in both fish & bash.

### Additional context

`yarn concurrently 'ls'` is fine, as is `yarn nuxi dev` and `npx concurrently 'nuxi dev'`.

i.e. `yarn` works; `concurrently` works; `nuxi dev` works; just not their combination.

This isn't a `concurrently` bug because it works both with `yarn` and some other executable, and with `nuxi dev` under `npx`. I suppose I can't rule out `yarn` as the culprit without something similar to `concurrently` to swap in like `yarn athesametime 'nuxi dev'`. (`yarn npm-run-all test` where `"test": "nuxi dev"` is in `scripts` works, but that's a bit different.)

### Logs

```shell
yarn run v1.22.17
$ [...]/node_modules/.bin/concurrently 'nuxi dev'
[0]
Nuxt CLI v3.0.0-27374259.21b664c
^C⏎                                                                                                       [0] nuxi dev exited with code SIGINT
```

**Comment by madebyfabian** [comment]
What's the state on this with the newest CLI versions? 😊

**Comment by danielroe** [comment]
Checking, this basically requires an extra Ctrl-C to close the app. I'm not convinced this is a Nuxt bug (it's more likely a `concurrently` one) and in any case it's quite a minor one.

![CleanShot 2023-04-14 at 21.31.15.gif](https://volta.s3.fr-par.scw.cloud/Clean_Shot_2023_04_14_at_21_31_15_216de8a916.gif)
