### ISSUE TITLE
Dynamic add routes

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt#13467]
Reference: nuxt/framework#2057, nuxt/nuxt.js#13054

The idea is dynamically to register router routes on runtime via a plugin. A new `addRoute` utility could be helpful to handle the required logic. 

---- 

it looks like you are adding the route after the router is used by app with `app.use(router)` which triggers the initial navigation on the client to a still non existent route.
That is okay, but ideally, some navigation guard should detect that the route must be added dynamically, add the route, and then trigger a new navigation with `next(to.fullPath)` or by returning the location.

_Originally posted by @posva in https://github.com/nuxt/framework/pull/2057#r753847873_

**Comment by danielroe** [comment]
I think adding routes _before_ the router is initialised can be done in `app/router.options.ts`: https://nuxt.com/docs/guide/recipes/custom-routing#using-approuteroptions. We can use https://github.com/nuxt/nuxt/issues/23678 to track adding them asynchronously.

Adding them after the router is initialised can be done with `useRouter().addRoute()`.
