### ISSUE TITLE
AWS Lambda deployment not serving files from public/_nuxt folder

### ISSUE THREAD

**Issue by KaziSadmanAhmed** [nuxt/nuxt#13478]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.19.0`
- Nuxt Version:     `3.0.0-27447229.20f3171`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

- Create a new project using `npx nuxi init nuxt3-app`
- Install the necessary dependencies
- Build using the nitro lambda preset (`export NITRO_PRESET=lambda`)
- Create a AWS Lambda function with the build output files
- Connect API Gateway with the Lambda function

### Describe the bug

The deployed function will not serve anything from the `/_nuxt` path. Either it will return the default welcome page or the 404 error page if you setup pages.

**Comment by kublasean** [comment]
> Don't want to be a pain, but could anybody create an example repo until the documentation is better? It would be greatly appreciated!

For future readers in addition to the example from @ffxsam here is an example using AWS CDK to deploy to Lambda and S3. I also was not able to get it working until using a CDN for assets. 

https://github.com/kublasean/nuxt3-cdk-lambda-hello-world

**Comment by danielroe** [comment]
If anyone is still encountering this, please open an issue [in the nitro repository](https://github.com/unjs/nitro/issues/new/choose)? 🙏
