### ISSUE TITLE
`<NuxtLink>` prefetch support

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt#13482]
Ref: #2086, nuxt/framework#3544

Smartly prefetch next pages with `<NuxtLink>`.

Considerations:
- Support payload prefetching for static routes
- Lower priority and disable for slow connections
- Consider using Link Prefetching

References:
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Link_prefetching_FAQ
Nuxt 2 prefetch: https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/components/nuxt-link.client.js

**Comment by christianlmc** [comment]
> [@danielroe](https://github.com/danielroe) Manifest idea is nice but it probably needs a full prerendering stage to have predicates. Since nitro is already allowing use of `X-NITRO-PREFETCH`, maybe we can enhance when prefetching next pages to respect this header and prefetch all of relevant links of next?
> 
> Example:
> 
> * User loads `/profiles`
> * We observe links to `/user/anna` and `/user/bob` (NuxtLink prefetch)
> * For prefetching we use background fetch to both `/user/{anna/bob}`
> * Page handler for `/user/:name` adds a prefetch header `X-NITRO-PREFETCH: '/img/users/:name.png'`
> * We also prefetch their dependencies in the background (BFS prefetch) and can also control the depth
> 
> Using headers, we can remove need of full static and a beforehand manifest. We can also use `app:prefetch` to implement it.

@danielroe not sure if it this one can be marked as completed. When there is a route change and that `to` page has a top level await, it does that fetching only when that link is clicked, and when it resolves it changes the page. What @pi0 was saying (from what I understand) is to make that async request as soon as the link is visible (or when network is idle) which I would improve user experience a lot, making route changes feel way more responsive

**Comment by plcdnl** [comment]
Totally agree with @christianlmc and @pi0. Do you think it will be possible?
