### ISSUE TITLE
component name visible in chunk names

### ISSUE THREAD

**Issue by Aareksio** [nuxt/nuxt#13499]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-27456065.f38cace`
- Package Manager:  `npm@8.5.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

```bash
git clone git@github.com:Aareksio/nuxt3-chunk-naming-strategy.git
cd nuxt3-chunk-naming-strategy
npm ci
npm run build
ls -l .output/public/_nuxt/ | grep "my-component"
```

As you can see, a chunk was generated for `my-component`, `my-component-15e4fa4c.mjs` in my case.

### Describe the bug

The chunk name may be blocked by adblocker software, some keywords commonly blocked:

- banner -> hero-banner.vue
- tracking -> usage-tracking-widget.vue
- ad -> ad-space.vue

Failing to load **any** of those chunks results in complete app failure. Not only the blocked component, but whole app becomes unusable.

### Additional context

Escalating from [discussion](https://github.com/nuxt/framework/discussions/3378) as it did not get any traction and the issue is critical for any production deployment. Read the discussion post for additional context if necessary.

**Comment by danielroe** [comment]
Yes, you can pick your chunk names:

```ts
export default defineNuxtConfig({
  vite: {
    build: {
      rollupOptions: {
        output: {
          chunkFileNames: '_nuxt/[hash].js',
          assetFileNames: '_nuxt/[hash][extname]',
          entryFileNames: '_nuxt/[hash].js'
        }
      }
    }
  }
})
```

**Comment by bharatmajority** [comment]
The entryFileNames seems to break the application. 

`Error: Could not load /..../.nuxt/dist/server/server.mjs (imported by node_modules/nuxt/dist/core/runtime/nitro/renderer.js): ENOENT: no such file or directory, open '/..../.nuxt/dist/server/server.mjs'`

chunk and asset file names seem to work just fine. We don't really need to change the entryFileNames. Just bringing up the error for your reference @danielroe .

**Comment by manniL** [comment]
@danielroe Should we close this issue or do you think there is more discussion needed?

**Comment by danielroe** [comment]
I think no more discussion is needed. We could document the solution for those for whom it matters.

**Comment by Aareksio** [comment]
Bumping with ref: https://github.com/rollup/rollup/issues/5374

People run into real production issues and waste hours because of this default, which could be easily improved.
A single bad word in any component (including dependencies), from any blacklist, in any language, kills the bundle.

**Comment by danielroe** [comment]
You're right, and I would welcome an improvement here in a future minor version. But it feels like this should be solved at the rollup level.

**Comment by Aareksio** [comment]
Thank you for acknowledging the issue!

The problem with _known block lists_ is that there are many of them and they constantly evolve:
```
! Last modified: 22 Feb 2024 12:51 UTC
! Expires: 4 days (update frequency)
```

Furthermore, there are all sort of minor lists, which are installed by default depending on users geo and locale. I was prompted to start the mentioned discussion ([new link](https://github.com/nuxt/nuxt/discussions/17905), migration from nuxt/framework broke the old one) after one of our team members saw blank page because their ad block extension by default installed some obscure, local list, which blocked `footer-social`.

The main point is **not** about the known lists. These are mostly tested by devs.

This is about the % of users who still see blank page. % of 0 users may not matter. % of 10,000,000 does. Why stick to named chunks in **production** when we have all the tools necessary to track the error down to the very character in source. How about **opt-in** friendly naming strategy, with scrambled default?

---

About addressing in rollup. It would probably be better overall. However, we can address the issue in userland as is properly documented and even suggested in [comment above](https://github.com/nuxt/nuxt/issues/13499#issuecomment-1642285419). With rollup it is 2nd level option, fairly easy to reach. Rollup is not branded as batteries included web framework. Rollup is a build tool and should be configured accordingly. Nuxt is supposed to have best practices baked in. Deferring the patch to rollup does not seem proper in this position.
