### ISSUE TITLE
Reactivity transform for built-in composables

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt#13525]
@pi0 @antfu `$useState` / `$useCookie` will be? ❤️

_Originally posted by @misaon in https://github.com/nuxt/framework/pull/3737#issuecomment-1072361460_

**Comment by madebyfabian** [comment]
Still relevant? Considering the Reactivity Transform RFC is being discontinued. https://www.youtube.com/watch?v=OrT0tHGXyqE&t=844s

**Comment by antfu** [comment]
Close as Reactivity Transform is dropped. In the future, We might discuss if we could have Vue Macros in Nuxt via a flag or so to re-enable such usage.
