### ISSUE TITLE
Shortcuts for `useHead`

### ISSUE THREAD

**Issue by Atinux** [nuxt/nuxt#13555]
Following a part of https://github.com/nuxt/framework/discussions/1823

Some ideas of something more elegant for meta tags IMO:

- `useLang(lang)`
- `useTitle(title, template)`
- `useMetaDescription(description, options?)` -> we could define options for `og:`, `twitter:`, etc
- `useMetaImage(url, options?)` -> we could define options for `og:`, `twitter:`, etc
- `useMetaCharset(charset)`
- `useMetaAuthor(author)`

Open to any suggestions 😊

**Comment by danielroe** [comment]
I think this might be able to be closed with `useSeoMeta`. What do you think @harlan-zw?

**Comment by harlan-zw** [comment]
For now, I would say useSeoMeta covers this issue.

The only one to consider would be `useTitle()` as it could be useful to have a reactive copy of the title and there are certain optimisations that could be done when only using this (verse useHead).

Better to park it for now though until the other head optimisations are ready and to see if users are asking for this

**Comment by the94air** [comment]
@harlan-zw It makes sense that all these composables are provided as one composable. I agree about the title composable being a particular case since it is the most important detail and sometimes its the only info needed on a page,
