### ISSUE TITLE
Error when trying to use useFetch with headers

### ISSUE THREAD

**Issue by lucassimines** [nuxt/nuxt#13560]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.11.0`
- Nuxt Version:     `3.0.0-27456065.f38cace`
- Package Manager:  `npm@8.0.0`
- Builder:          `vite`
- User Config:      `app`, `publicRuntimeConfig`, `components`, `typescript`, `css`, `meta`, `vite`, `dir`, `postcss`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

```
<script lang="ts" setup>
const { pending, data: user } = await useFetch<{
  id: '';
  name: '';
}>('/api/auth/user', {
  credentials: 'include',
  baseURL: 'http://localhost:3000',
  headers: useRequestHeaders(['cookie'])
});
</script>
<template>
  <div class="app">
    <div v-if="pending">Loading...</div>
    <div v-else>
      {{ user.name }}
    </div>
  </div>
</template>
```

### Describe the bug

When using `headers: useRequestHeaders(['cookie'])`, I can't call a property from my response on the template.

The bug just occurs when I try to call on template a property from `user`, E.g: `user.name`.

If I call on my template, just `user`, no errors are displayed.

### Additional context

Error when trying to call `user.name` on template.

```
runtime-core.esm-bundler.js:569 TypeError: Cannot read properties of null (reading 'name')
    at Proxy._sfc_render (app.vue:17:9)
    at renderComponentRoot (runtime-core.esm-bundler.js:893:44)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5098:34)
    at ReactiveEffect.run (reactivity.esm-bundler.js:167:25)
    at runtime-core.esm-bundler.js:491:18
    at Array.forEach (<anonymous>)
    at rerender (runtime-core.esm-bundler.js:483:27)
    at Object.rerender (runtime-core.esm-bundler.js:566:20)
    at app.vue:15:14
    at client.ts:428:52
```

**Comment by danielroe** [comment]
We no longer hash headers for the key for useFetch.
