### ISSUE TITLE
Global Middleware on first load both side

### ISSUE THREAD

**Issue by shinguweb96** [nuxt/nuxt#13679]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-27484505.9f6eff7`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `vite`, `privateRuntimeConfig`, `publicRuntimeConfig`, `css`, `buildModules`, `intlify`, `vueuse`
- Runtime Modules:  `-`
- Build Modules:    `@intlify/nuxt3@0.1.10`, `@pinia/nuxt@0.1.8`, `@vueuse/nuxt@8.2.5`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-dypzgk

### Describe the bug

On first load, the global middleware get executed on both side (server and client).
In Nuxt 2, if the app is in universal mode, at first load the middleware get executed only by server side.

**Comment by patrickyue** [comment]
may I ask global middleware are those inside server/middleware folds？

**Comment by AloisSeckar** [comment]
> may I ask if global middleware are those inside server/middleware folds？

no...to make middleware "global", you name the file `/middleware/foo.global.ts` - then it runs **before every navigation to a route**...and  you use `defineNuxtRouteMiddleware` method to define the contents

files inside `/server/middleware` are sort of "global" themselves by nature - they run **on every request before any other server route**...their method is `defineEventHandler`

here I did a quick example - https://stackblitz.com/edit/github-kskzrh - first `/middleware/route.global.ts` runs as the routing happens, then initial fetch to server is made, which triggers `/server/middleware/server.ts`...then upon every button click `/server/middleware/server.ts` is triggered again along with a new date fetch...clicking the link re-starts the sequence

**Comment by danielroe** [comment]
Thanks for the really helpful response @AloisSeckar ❤️ 

I think we can close this issue. It's deliberate that middleware run on both server + client by default. If you want to prevent this, you can check whether it's client (or whether it's running on the initial load):

```js
export default defineNuxtRouteMiddleware(to => {
  // always return on client side
  if (process.client) return
  // or only return on initial load
  if (process.client && useNuxtApp().isHydrating) 
})
```

I would also be up for a feature enhancement issue proposing `.client` or `.server` suffixes for global middleware.

**Comment by Atinux** [comment]
You can use this in order to only run it once:

```ts
export default defineNuxtRouteMiddleware(() => {
    // or only skip middleware on initial client load
    if (process.server || (process.client && !useNuxtApp().isHydrating)) {
      console.log('GLoabl middleware')
    }
})
```

https://stackblitz.com/edit/github-dypzgk-1u8knt?file=pages%2Findex.vue,pages%2Fabout.vue,middleware%2Falways-run.global.ts
