### ISSUE TITLE
Browser debugging sourcemap issue on SFC .vue files that have an auto-import

### ISSUE THREAD

**Issue by markgibbons25** [nuxt/nuxt#13674]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v14.19.0`
- Nuxt Version:     `3.0.0-27487836.540e23c`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `publicRuntimeConfig`, `css`, `modules`, `typescript`
- Runtime Modules:  `@formkit/nuxt@1.0.0-beta.6`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-4adlhf?file=components/Test.vue

### Describe the bug

If a file is auto imported, and also has a nested auto-import, you can't debug it in chrome.

Steps:
1. open https://stackblitz.com/edit/github-4adlhf?file=components/Test.vue
2. click Open in New Window
3. Open chrome dev tools and go to the Sources tab
4. Find Test.vue
5. Note that you cannot add a debug break point in the code withing the mounted() section

![image](https://user-images.githubusercontent.com/3212534/162097605-294c1c1a-c50e-40d7-8954-512d71878ef1.png)

### Additional context

Checked with both `yarn` and `npm` package managers (npm 8.5)

**Comment by karthickthangasamy** [comment]
Hi @markgibbons25 ,

To debug the script, we can include lang="ts" in the script tag.

```ts
<script lang="ts">
<<codes here>>
</script>
```
