### ISSUE TITLE
Sass Variables not available in pages / layouts / components

### ISSUE THREAD

**Issue by Noxdor** [nuxt/nuxt#13690]
### Environment

Nuxt project info:                                                                                                                           22:39:51

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27375427.d07d572`
- Package Manager:  `npm@8.3.1`
- Bundler:          `Vite`
- User Config:      `components`, `meta`, `css`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

I am trying to load sass from `assets/sass/global.sass`. Add the file and fill it with:

```sass
@forward "colors"
@use "colors" as c

body
  background-color: c.$secondary
```

Add a partical sass file `_colors.sass` and fill it with:

```sass
$primary: #264653
$secondary: #e76f51
$black: #171717
$white: #e7e7e7

```
Add the sass file into the `nuxt.config.ts` config.

```typescript
import { defineNuxtConfig } from 'nuxt3'

// https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
export default defineNuxtConfig({
    components: true,
    meta: {
        script: [
            { src: "https://unpkg.com/phosphor-icons" }
        ],
    },
    css: [
        "@/assets/sass/global.sass",
    ]
})
```

See that the variable is valid and is applied as the background-color for the body. Now try to access any of the color variables inside a component, page or layout. Both with namespacing (@use) and without (@import) didn`t work for me.

### Describe the bug

The Sass variables should be loaded into every vue file to be globally available. They aren`t as far as I can see.

### Additional context

The Nuxt 3 docs are yet sparsely filled so there might be something missing I could not read up, that is necessary to make the variables load.

**Comment by v3nt** [comment]
Hell - I still can't use SASS variables in pages or components?

Tried all of the above. Can't believe this is still so tricky.

```
  css: ["~/assets/styles/default.scss"],
  vite: {
    css: {
      preprocessorOptions: {
        sass: {
          additionalData:
            '@import "~/assets/styles/variables"; @import "@yapily/global-styles/sass/abstracts/variables"',
        },
      },
    },
  },
```

```
"node-sass": "^7.0.3",
"sass": "^1.58.3",
```

**Comment by manniL** [comment]
[Works as expected](https://stackblitz.com/edit/nuxt-issues-13690) and [is documented](https://nuxt.com/docs/getting-started/styling#using-preprocessors) 👍🏻

**Comment by iamthismarvin** [comment]
The error shows up when you try to read variables in an `.scss` files in a Vue component with a `<style lang="sass">` style tag. In the [example](https://stackblitz.com/edit/nuxt-issues-13690) you provided, changing:
```vue
<style lang="scss">
* {
  color: $primary;
}
</style>
```
to 
```vue
<style lang="sass">
*
  color: $primary
</style>
```
Returns the error: 
<img width="840" alt="image" src="https://github.com/nuxt/nuxt/assets/47439212/940fe394-bfa5-43fe-8efd-d22c2a17d0e0">

Reversing the conditions (`.sass` variables, and updating Nuxt configuration, with Vue `scss` style tag) returns the same error.

Haven't found a solution so far.

**Comment by 1226085293** [comment]
Use global css:[plugin:vite:css] [sass] Undefined variable.
Using preprocessorOptions: works fine! !
