### ISSUE TITLE
nested router - doesnt work

### ISSUE THREAD

**Issue by mihail727** [nuxt/nuxt#13696]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-27460146.2ad93eb`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-zvowq4-gj7iuh?file=pages/index.vue

### Describe the bug

with latest version of nuxt 3 and follow the [documentation](https://v3.nuxtjs.org/guide/features/server-routes#using-a-nested-router) i cant create nested route
when i'm trying to get data from api i get error: 
```
handle is not a function
  at eval (file://./node_modules/h3/dist/index.mjs:57:24)  
  at new Promise (<anonymous>)  
  at callHandle (file://./node_modules/h3/dist/index.mjs:54:10)  
  at eval (file://./node_modules/h3/dist/index.mjs:50:12)  
  at eval (file://./node_modules/h3/dist/index.mjs:78:34)  
  at async handle (file://./node_modules/h3/dist/index.mjs:318:19)  
  at async ufetch (file://./node_modules/unenv/runtime/fetch/index.mjs:22:17)  
  at async $fetchRaw2 (file://./node_modules/ohmyfetch/dist/chunks/fetch.mjs:144:20)  
  at async setup (file://./.nuxt/dist/server/server.mjs:2442:176)
[Vue Router warn]: No match found for location with path "/test"
```

**Comment by obust** [comment]
the following does not register the route `/api/users`
```
// @/server/api/users/[...].ts

import { createRouter, defineEventHandler, useBase } from 'h3';

const router = createRouter();
router.get('', defineEventHandler(event => 'all users'));
router.get('/:id', defineEventHandler(event => 'one user'));

export default useBase('/api/users', router.handler);
```

could it be done like this please:
```
// @/server/api/users.ts

import { createRouter, defineEventHandler, useBase } from 'h3';

const router = createRouter();
router.get('', defineEventHandler(event => 'all users'));
router.get('/:id', defineEventHandler(event => 'one user'));

export default useBase('/api/users', router.handler);
```

**Comment by Zebnastien** [comment]
Same as @obust.

What would be the recommended Nuxt way to handle /api/users and /api/users/[id] in the same file ?

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/18571.
