### ISSUE TITLE
Display public files and size after `nuxi build`

### ISSUE THREAD

**Issue by Atinux** [nuxt/nuxt#13764]
We do it for the server but it would be nice to display the same informations for the client chunks as well.

Could be displayed after "Generated public `.output/public`"

![Screenshot 2022-04-20 at 16.48.19@2x.png](https://volta.s3.fr-par.scw.cloud/Screenshot_2022_04_20_at_16_48_19_2x_4f6b60dc9b.png)

**Comment by danielroe** [comment]
closing in favour of https://github.com/unjs/nitro/issues/130
