### ISSUE TITLE
`addRouterMiddleware` is not working with `@intlify/nuxt3`

### ISSUE THREAD

**Issue by aloulouamine** [nuxt/nuxt#13794]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-27495046.0d5ec20`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `ssr`, `buildModules`, `pageTransition`, `typescript`, `intlify`
- Runtime Modules:  `-`
- Build Modules:    `@intlify/nuxt3@0.1.10`

### Reproduction

https://stackblitz.com/edit/github-9wkf8t-t2us5t?file=plugins/middleware.ts

### Describe the bug

When adding a global middleware from plugin, it doesn't trigger in the first page hit with @intlify/nuxt3 module installed.

**Comment by productdevbook** [comment]
same problem all plugin same problem

**Comment by danielroe** [comment]
@productdevbook What do you mean?

**Comment by danielroe** [comment]
Let's track in https://github.com/intlify/nuxt3/issues/51 if this is still relevant.
