### ISSUE TITLE
on initial client side load with `server: false`, useFetch does not await data fetching

### ISSUE THREAD

**Issue by siddharth223437** [nuxt/nuxt#13805]
### Environment

Operating System: Darwin
Node Version: v17.2.0
Nuxt Version: 3.0.0-27491748.3186841
Package Manager: yarn@1.22.10
Builder: vite
User Config: -
Runtime Modules: -
Build Modules: -

### Reproduction

https://codesandbox.io/s/unruffled-rain-zzuixq?file=/app.vue

### Describe the bug

When using useFetch composable inside setup method or inside any lifecycle hook then it directly shows error. It does not even hit the backend api.

### Logs

```shell
RefImpl {
  __v_isShallow: false,
  dep: undefined,
  __v_isRef: true,
  _rawValue: null,
  _value: null
}
RefImpl {
  __v_isShallow: false,
  dep: undefined,
  __v_isRef: true,
  _rawValue: null,
  _value: null
}
```

**Comment by mihul87** [comment]
I want to document this issue.

**Comment by gslin** [comment]
Although it's already mentioned in documents, I would like to share some ideas for clearer logic.

In this case I use `watch()` to watch whether `status` is updated, and I specify `immediate` to make sure this code will be run at least once.  So no matter what `ssr` and `server` are, it should be able to process API response, correctly.

```js
const res = await useFetch('https://nekos.best/api/v2/neko', {server: false});
watch(res.status, () => {
  if (res.status.value === 'success') {
    const v = res.data.value;
    // ...
  }
}, {immediate: true});
```

I am not sure if there are any other side effects, but it works on my project so far.

**Comment by bradley-varol** [comment]
Bumped into this trying to client-side fetch data for one page that didn't need SSR.

In the end I just disabled SSR for that route with [Hybrid Rendering](https://nuxt.com/docs/guide/concepts/rendering#hybrid-rendering).

**Comment by bagaskarala** [comment]
> I used the immediate option.
> 
> ```ts
> const fetch = useFetch(url, { immediate: false })
> await fetch.execute({ _initial: true })
> ```

works as expected, thanks

**Comment by parsajiravand** [comment]
**If you don't find a clean solution, you can set a timeout.**

```vue
<script setup>
const result = ref({});
const fetchData = async () => {
  const res = await useFetch("https://jsonplaceholder.typicode.com/posts", {
    method: "GET",
  });
  result.value = res;
};
//Client side rendering
setTimeout(() => {
  fetchData();
}, 0);
</script>
```
