### ISSUE TITLE
$fetch is broken on post FormData

### ISSUE THREAD

**Issue by ozancakir** [nuxt/nuxt#13839]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `npm@8.5.0`
- Builder:          `vite`
- User Config:      `ssr`, `css`, `typescript`, `runtimeConfig`, `buildModules`, `components`, `intlify`, `unocss`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `@intlify/nuxt3@0.2.1`, `@unocss/nuxt@0.31.17`
------------------------------

### Reproduction

* Open a clean project
* Try post form data
* body is stringified

### Describe the bug

There is a known bug in ohmyfetch link:https://github.com/unjs/ohmyfetch/pull/36#discussion_r767707178
Body is getting stringified on FormData posts. Since Nuxt3 using ohmyfetch by default client, It is now impossible to use native client for formdata requests.

**Comment by Shooteger** [comment]
Issue can be closed, no longer relevant
