### ISSUE TITLE
script ran twice in Nested Pages when there is a useFetch/useAsyncData

### ISSUE THREAD

**Issue by weeuwee** [nuxt/nuxt#13842]
### Environment

nil

### Reproduction

https://stackblitz.com/edit/github-qgu6p8?file=pages%2F[id].vue

### Describe the bug

Script in child page (Index) will run twice when there is a await useFetch/useAsyncData in parent page

**Comment by danielroe** [comment]
This is no longer replicable in Nuxt 3.4.3: https://stackblitz.com/edit/github-qgu6p8-zprvxb
