### ISSUE TITLE
how to use hooks pages.extend to config named route view?

### ISSUE THREAD

**Issue by TangsWang** [nuxt/nuxt#13854]
### Environment

node 16.14
nuxt3 rc

### Reproduction

none

### Describe the bug

nuxtpage type only have {name,path,file,meta,children}, it's diffrent from vue route.
how can i config named route view use nuxt?

**Comment by gspgsp** [comment]
same issue!
I want to access local html in an iframe, so I want to use this property,
but there is no demo！

**Comment by danielroe** [comment]
The way to do this is with the runtime `app/router.options.ts`.

It allows fine grained customisation of the route objects. 

https://nuxt.com/docs/guide/recipes/custom-routing#using-approuteroptions
