### ISSUE TITLE
Dev server frequently freezes when using NX and Prisma

### ISSUE THREAD

**Issue by rdmchr** [nuxt/nuxt#13860]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `npm@8.3.1`
- Builder:          `vite`
- User Config:      `typescript`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/rdmchr/Rose/tree/vite

- Clone the repo
- Switch to the `vite` branch
- Run `npm i`
- Create a .env file with the following content:
```
DATABASE_URL="postgresql://postgres:postgres@localhost:5432/postgres?schema=public"
```
- Run `npm run dev`
- Open the index page in your browser
- Wait ~2 minutes
- Reload the tab

### Describe the bug

After some time the Vite dev server no longer responds to requests. Requests sent to the server neither load nor time out.
This affects both frontend and server URLs.

There are no errors in the vite console nor in the browser console.

**Comment by okxiaoliang4** [comment]
Mac OS has same problem, any progress?

**Comment by joshmossas** [comment]
Hey all,

I came across this bit of documentation in the Prisma docs for NextJS 
https://www.prisma.io/docs/guides/other/troubleshooting-orm/help-articles/nextjs-prisma-client-dev-practices

I tried following this method in my Nuxt Prisma app and this issue completely went away. (I'm on Windows 11). So maybe others will find this useful 😄

**Comment by joshmossas** [comment]
Also I had to change the implementation slightly this is what my new implementation looks like

```ts
import { prismaClient } from '@prisma/client';

declare global {
    let prismaClient: PrismaClient | undefined;
}
let prismaClient: PrismaClient | undefined;
const prisma = prismaClient || new PrismaClient();

if (process.env.NODE_ENV !== 'production') global.db = prisma

export default prisma
```

**Comment by danielroe** [comment]
Closing as this seems like it's not an issue with Nuxt or Nitro, and we have a good implementation that resolves the issue.
