### ISSUE TITLE
provide auto-import for sendError

### ISSUE THREAD

**Issue by sasial-dev** [nuxt/nuxt#13912]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-rc.2`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `meta`, `css`, `modules`
- Runtime Modules:  `@vueuse/nuxt@8.3.1`, `@nuxtjs/tailwindcss@5.0.3`, `nuxt-typed-router@1.1.2`
- Build Modules:    `-`
------------------------------

### Reproduction

N/A

### Describe the bug

sendError (from h3) is not globalised.

### Additional context

N/A

### Logs

```shell
N/A
```

**Comment by danielroe** [comment]
This is now done.
