### ISSUE TITLE
SSR fails when using aws amplify libraries

### ISSUE THREAD

**Issue by danielroe** [nuxt/nuxt#13979]
Here you go:

https://stackblitz.com/edit/github-qcrjhw

Some context:

Server Side Rendering is disabled, when enabled it crashes instantly on an issue with amplify. As you can see in the `nuxt.config.ts` a define global is present. In dev it works, if you use `yarn build` it will crash.

When you remove the define from `nuxt.config.ts` you will see the errors we encounter with amplify libs.

Thanks in advance.

_Originally posted by @rvmourik in https://github.com/nuxt/nuxt.js/issues/13941

**Comment by ennioVisco** [comment]
The new amplify V6 should be more SSR friendly, and also supports it out of the box for nextjs: https://docs.amplify.aws/javascript/build-a-backend/server-side-rendering/#pageMain
