### ISSUE TITLE
Docs: Elaborate the "Rendering an error page" section

### ISSUE THREAD

**Issue by LLCampos** [nuxt/nuxt#13987]
Hello :)

From reading [this section](https://v3.nuxtjs.org/guide/features/error-handling#rendering-an-error-page) is unclear exactly when the error page is rendered. 

> When Nuxt encounters a fatal error, whether during the server lifecycle, or when rendering your Vue application (both SSR and SPA)

First, it's not clear what a "fatal error" is. [Doesn't seem to be a standard term](https://www.google.com/search?q=fatal+error+javascript&ei=ioV-YqnRB-yMlwTsz4CgBQ&ved=0ahUKEwipvpuJ8dz3AhVsxoUKHewnAFQQ4dUDCA4&uact=5&oq=fatal+error+javascript&gs_lcp=Cgdnd3Mtd2l6EAMyBQgAEIAEMgUIABCABDIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMgYIABAWEB46BwgAEEcQsAM6CwguEMcBENEDEJECOgUIABCRAjoECAAQQzoLCC4QgAQQxwEQ0QM6CwguEIAEEMcBEKMCOgUILhCABDoNCC4QxwEQ0QMQ1AIQQzoECC4QQzoHCC4Q1AIQQzoICC4QgAQQ1AI6DgguEIAEEMcBEK8BENQCSgQIQRgASgQIRhgAUO4MWLcuYIsvaAZwAXgBgAHZAYgB8BKSAQcxMi4xMC4xmAEAoAEByAEGwAEB&sclient=gws-wiz)?

Also unclear what is included inside the "server lifecycle". I've tried to throw an error in the `mounted()` hook, and I didn't got to the error page, but I did when throwing an error in the `created()` hook.

**Comment by mihul87** [comment]
I would like to document this issue.

**Comment by mihul87** [comment]
I would like to document this issue.
