### ISSUE TITLE
disallow non-JSON-serialisable types in `options.runtimeConfig`

### ISSUE THREAD

**Issue by msdsk** [nuxt/nuxt#13992]
### Environment

- Operating System: `Linux`
- Node Version:     `v17.2.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@8.1.4`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

in `nuxt.config.ts` add:

```
...
  runtimeConfig: {
    public: {
      someMap: new Map()
    }
  },
...
```

### Describe the bug

The map is transformed into an empty object (regardless if the map was empty or not) instead of being passed to the browser as-is.

### Additional context

The expected behavior was working in rc1

**Comment by danielroe** [comment]
We might be able to do some interesting things with serialising different data types between server -> client but I think that we should not support them between nuxt.config -> build. Rather, we should update the types for `runtimeConfig` and `appConfig` input in nuxt.config to disallow non-JSON-serialisable types from being set as an early-warning flag for users.

**Comment by danielroe** [comment]
A warning has been implemented upstream in nitro - should land in next patch.
