### ISSUE TITLE
runtimeConfig not parsing environment variables in cloudflare mode

### ISSUE THREAD

**Issue by srtonz** [nuxt/nuxt#14011]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@3.2.0`
- Builder:          `vite`
- User Config:      `runtimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/srtonz/nuxt3-runtime-config

Run with
1. `yarn dev` and observe console output when opening app: `public: { authDomain: '' }`
2. `NUXT_PUBLIC_AUTH_DOMAIN=foo yarn dev` and observe console output when opening app: `public: { authDomain: 'foo' }`
3. `NITRO_PRESET=cloudflare yarn build && npx miniflare --binding NUXT_PUBLIC_AUTH_DOMAIN=bar .output/server/index.mjs --site .output/public` and observe console output when opening app: `public: { authDomain: '' }`
4. . `yarn build && NUXT_PUBLIC_AUTH_DOMAIN=baz node .output/server/index.mjs` and observe console output when opening app: `public: { authDomain: 'baz' }`

### Describe the bug

Expected behavior: runtime configuration can be overridden with environment variables regardless of the build target.

Actual behavior: runtime configuration cannot be overridden with environment when using the cloudflare target. Suspect other targets may be affected.

### Additional context

If this is a nitro issue rather than a nuxt issue, suggest updating documentation accordingly.

**Comment by manniL** [comment]
This is resolved in Nitro via https://github.com/unjs/nitro/issues/272
