### ISSUE TITLE
Custom Error Properties Are Not Retained

### ISSUE THREAD

**Issue by bitmage** [nuxt/nuxt#14133]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@8.5.0`
- Builder:          `vite`
- User Config:      `buildModules`, `errorHandler`, `hooks`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/TorchlightSoftware/nuxt-bugs/tree/error-handling

### Describe the bug

Any custom fields that are on an error appear to vanish when it arrives at `errors.vue`.  The fields `message` and `data` get through, but only as a `String`.  I assume this is because somewhere in the error handling Nuxt is creating a new error and copying properties over.  I can see the original error in `plugins/errors.ts` but a different error arrives in `pages/errors.vue`.

Is there any way to override this process?  Or some other way to ensure that custom properties are retained?

[Error handling documentation](https://v3.nuxtjs.org/guide/features/error-handling/) mentions `onErrorCaptured` and `vue:error`.  I assume these are to be configured in `hooks` inside `nuxt.config.ts`?  But they seem to be ignored.  More details on how to configure these handlers would be helpful.

**Comment by mihul87** [comment]
I would like to document this issue.
