### ISSUE TITLE
importing via alias into js file with `type: module` doesn't work

### ISSUE THREAD

**Issue by xdewx** [nuxt/nuxt#14151]
### Environment

Nuxt CLI v3.0.0-rc.3                                                                                              15:33:06
Nuxt project info:                                                                                                15:33:07

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@8.10.0`
- Builder:          `vite`
- User Config:      `alias`, `ssr`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction
1. git clone https://github.com/whichdew/nuxt3-aborted.git
2. cd nuxt3-aborted && git checkout bug-import
1. rm -rf .nuxt
3. npm run dev

key points:
- `type:module` in `package.json`
- `.js` import `.ts`

if remove `type:module` from package.json or rename `service/sqlite-ex.js` to `service/sqlite-ex.ts` ,everything will be fine.

### Describe the bug

node[139794]: ../src/node_file-inl.h:160:node::fs::FSReqPromise<AliasedBufferT>::~FSReqPromise() [with AliasedBufferT = node::AliasedBufferBase<double, v8::Float64Array>]: Assertion `finished_' failed.
 1: 0xb00d90 node::Abort() [node]
 2: 0xb00e0e  [node]

 ERROR  [worker reload] [worker init] Cannot find package 'mylib' imported from /src/test/nuxt3-aborted/service/sqlite-ex.js

  at new NodeError (node:internal/errors:371:5)
  at packageResolve (node:internal/modules/esm/resolve:884:9)
  at moduleResolve (node:internal/modules/esm/resolve:929:18)
  at defaultResolve (node:internal/modules/esm/resolve:1044:11)
  at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
  at link (node:internal/modules/esm/module_job:75:36)

 3: 0xafbcda  [node]
 4: 0xb07512 node::fs::FSReqAfterScope::~FSReqAfterScope() [node]
 5: 0xb079fe node::fs::AfterOpenFileHandle(uv_fs_s*) [node]
 6: 0x1555bad  [node]
 7: 0x155a336  [node]
 8: 0x156c7a4  [node]
 9: 0x155ac68 uv_run [node]
10: 0xa3dfe5 node::SpinEventLoop(node::Environment*) [node]
11: 0xbc96c2 node::worker::Worker::Run() [node]
12: 0xbc9e58  [node]
13: 0x7f3591904ea7  [/lib/x86_64-linux-gnu/libpthread.so.0]
14: 0x7f3591834def clone [/lib/x86_64-linux-gnu/libc.so.6]
Aborted

**Comment by danielroe** [comment]
This is no longer replicable: https://stackblitz.com/edit/github-equw6w?file=nuxt.config.ts
