### ISSUE TITLE
Support `unplugin` option into Nuxt Config

### ISSUE THREAD

**Issue by Atinux** [nuxt/nuxt#14263]
Sometimes a module is not necessary, we created `unplugin` to create universal plugins for both Webpack, Vite and other bundlers.

It would be great to support an `unplugins` object in the `nuxt.config`:

```ts
import { defineNuxtConfig } from 'nuxt'

export default defineNuxtConfig({
  unplugin: {
    'unplugin-icons': { /* options */ }
  }
})
```

This way, Nuxt could call the `.vite(options)` or `.webpack(options)` automatically based on the provided `builder` option.

**Comment by danielroe** [comment]
This is a good example, for anyone looking in future: https://github.com/nuxtlabs/examples/issues/8.
