### ISSUE TITLE
Nuxt 3 does not respect layouts in separate folders

### ISSUE THREAD

**Issue by DannyAndres** [nuxt/nuxt#14275]
#### Nuxt Version

- nuxt:  v3.0.0 rc-4

#### Steps to reproduce

On a clean Nuxt 3 install.

Create a layout inside a folder like.

`layouts/mobile/custom.vue`

Use it in a page as follows.

`
<NuxtLayout name="mobile/custom">
    some code ...
</NuxtLayout>
`

### Describe the bug

When I create a layout inside a folder like "layouts/mobile/custom.vue" and use it inside of "pages/index.vue" on a clean install of Nuxt 3 as follows.

`
<NuxtLayout name="mobile/custom">
    some code ...
</NuxtLayout>
`

It does not work, I don't know if this feature is not supported yet or if it is a bug, because when I went through the Nuxt 2 info I found this which came out thanks to an issue of this exact same problem in Nuxt 2

[Adds support for folders in /layouts nuxt/nuxt.js#12765](https://github.com/nuxt/nuxt.js/pull/1865)

Normal layout use like Nuxt 3 documentation works just fine, "layouts/custom.vue" inside of "pages/index.vue" like this.

`
<NuxtLayout name="custom">
    some code ...
</NuxtLayout>
`

### What is Expected?

Is expected to work exactly as normal layouts would.

### What is actually happening?

Got an error in console as if the layout does not exists.

`Invalid layout "mobile/custom" selected.`

**Comment by seanfilimon** [comment]
Yep agreed this needs to be implemented

**Comment by Suv4o** [comment]
@danielroe I created a pull request for a fix on this issue. Please check it out in the following link. —>  https://github.com/nuxt/nuxt/pull/20190

**Comment by selimdoyranli** [comment]
@danielroe Any update? I need this enhancement to create the following structure;

```
layouts
 ┣ Corporate
 ┃ ┣ Corporate.layout.scss
 ┃ ┗ Corporate.layout.vue
 ┗ Default
 ┃ ┣ Default.layout.scss
 ┃ ┗ Default.layout.vue
```

it works on nuxt2:
```
<script>
...
layout: 'Corporate/Corporate.layout'
..
</script>
```

But it didn't work on nuxt3
`<NuxtLayout name="Corporate/Corporate.layout">`

In addition, it would be very useful if you could add this defining support for defining default and error layout

**Comment by danielroe** [comment]
https://github.com/nuxt/nuxt/pull/20190#issuecomment-1604336353

Feel free to open a new PR taking my comments into account if you have time.
