### ISSUE TITLE
Vite unable to load modules when components are outside project directory

### ISSUE THREAD

**Issue by uuf6429** [nuxt/nuxt#14295]
### Environment

Stackblitz, using components config:
```
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `components`
- Runtime Modules:  `-`
- Build Modules:    `-`
```

Local, using component:dirs hook:
```
- Operating System: `Darwin`
- Node Version:     `v14.19.3`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `npm@6.14.17`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `hooks`, `modules`, `app`, `css`
- Runtime Modules:  `@storyblok/nuxt@4.0.1`
- Build Modules:    `-`
```

### Reproduction

Repro: https://stackblitz.com/edit/github-tncnqa

What I did (things to note):
1. moved the nuxt project into a `nuxt` directory
2. configured stackblitz to be able to work with this structure by adding a `.stackblitzrc` file
3. imported the markdown dependency as a test case
4. configured nuxt/vue to globally load components from the parent (`/components`) directory (using `components` config, but same problem happens if I used `components:dirs` hook)
5. added an `Inner.vue` and `Outer.vue` components - they basically convert and display some markdown to html

### Describe the bug

When adding components from outside the project directory, loading modules in those components messes up. 
For example, if the `makrdown` module was supposed to be imported, this error pops up during build:
> Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/projects/github-tncnqa/nuxt/markdown' imported from /home/projects/github-tncnqa/nuxt/.nuxt/dist/server/server.mjs

### Additional context

I'm not sure if this relates to nuxt or is purely a vite problem, unfortunately I don't know enough to find the problem and I have no idea how to make a reproduction with vite only.

**Comment by danielroe** [comment]
For a workaround, you can add any directories outside your project to vite's allow list:

```diff
  export default defineNuxtConfig({
+   vite: {
+     server: {
+       fs: {
+         allow: ['..']
+       }
+     }
+   }
  });
```
