### ISSUE TITLE
Infinite redirect when the url contains ANY "+" character breaking the application

### ISSUE THREAD

**Issue by igortrinidad** [nuxt/nuxt#14316]
Hi guys, first of all thanks for the amazing job in this awesome tool!

I'm facing an several issue when the user tries to access the Nuxt application (SSR mode) using an url that contains any "+" character, the application apply an endless 302 redirect breaking all the application.

### Versions

- nuxt: [3.0.0-rc.4, 3.0.0-rc.5]
- node: [14.17.1, 16.14.2, 16x (Vercel)]

### Reproduction

Url to test:
https://test-nuxt-error.vercel.app/?asd=1231+

Example repo with the error:
https://github.com/igortrinidad/test-nuxt-error

### Steps to reproduce
Deploy an application on Vercel that contains vue-router (using Nuxt pages), if the application does not contains vue-router it won't happens...

### What is Expected?
The application been served normally

### What is actually happening?
Infinite redirects 302 breaking the application

### I tried
Update the vue-router to the latest version
Create a new installation of Nuxt and deploy it
If the installations doesn't have pages (router...) the error doesn't happens
If the application has pages (what is pretty normal to an web application) the error starts to happens..

### Why

Why i need to access an url that contains the"+" character in my application, im implementing Google auth and the redirect url from the provider come with the "+" character in it which i can't control or sanitize.

**Comment by Plinpod** [comment]
Can replicate the same behavior with Nuxt 3.1.2 deployed to Vercel

**Comment by igortrinidad** [comment]
@Plinpod Did you tried this solution ? [https://github.com/nuxt/nuxt/issues/14316#issuecomment-1397355124]

**Comment by Plinpod** [comment]
> 

No, I haven't tried that. That file's put into the project's root in a folder called `app` ? I wasn't aware of a directory structure like that.

**Comment by samrap** [comment]
@Plinpod I recommend you use [#14316 (comment)](https://github.com/nuxt/nuxt/issues/14316#issuecomment-1397355124) as your middleware solution only handles the `+` character while this issue will apply to any special characters in the URI. It's also a better catch all in case you end up with query params at other URLs in your site/app.

I wasn't aware of the `app` directory until now either, but it looks like a place in Nuxt to export/override default options with logic.

**Comment by re2005** [comment]
Hard to believe that this is hanging here for almost a year.

What solved for me was (Nuxt 3.3.1)

Added a middleware called `router.global.ts` added to `/src/middleware/router.global.ts`

router.global.ts:
```ts
export default defineNuxtRouteMiddleware((to) => {
    if (to.fullPath.includes('+')) to.fullPath = to.fullPath.replace(/\+/g, '%20');
});

```

`nuxt.config.ts` add:

```ts
router: {
     middleware: ['router'],
},
```

That worked well, but looks like a hack. Any other solutions ?

**Comment by cosbgn** [comment]
@danielroe should we open an issue on https://github.com/unjs/ufo ? Any ideas on how to get this fixed? I have currently all my projects on Vercel and they are all broken because of this as many sites automatically add ?ref=X and more. 

Or is this something much bigger internally which just can't be fixed that easily?

**Comment by alicard** [comment]
I am having same issue when deploying using **npm run generate** or **npm run build** and upload it to vercel and still with the issue for another hosting. I am using nuxt v3.0.0 and this is my url [](https://app.ourday.my.id/utari-syahrul?to=Khamad+Ali&tkn=e28809660ee2a36835cfb8ffb44e3795)
When I change the query **"+"** to others then it work fine. What's wrong with that?

**Comment by danielroe** [comment]
Please update your Nuxt version. This issue has been resolved.
