### ISSUE TITLE
Data not accessible through 'head' method in defineNuxtComponent

### ISSUE THREAD

**Issue by alexandreguedj** [nuxt/nuxt#14345]
### Environment

- Operating System: `Darwin`
- Node Version:     `v15.5.0`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `yarn@1.22.10`
- Builder:          `vite`
- User Config:      `head`, `modules`, `buildModules`, `css`, `build`
- Runtime Modules:  `@vueuse/motion/nuxt@2.0.0-beta.18`, `@nuxtjs/strapi@1.5.0`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-uqkrfk?file=app.vue

### Describe the bug

The title is not filled with the variable, but it works when applying a title without variable.

**Comment by harlan-zw** [comment]
Seems solved, going to close.
