### ISSUE TITLE
Scan plugins from top level `/plugins` folder only

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt#14358]
Similar to nuxt/framework#6025, this makes directory scanning simpler and more consistent between dirs. Plugins nested in dirs can be manually added with `plugins: []` in `nuxt.config` or a reexport to top level `plugins/` directory.

**Comment by manniL** [comment]
@danielroe Could this be a good candidate for a `future` option? 🤔

**Comment by danielroe** [comment]
It could 👌
