### ISSUE TITLE
Nuxt 3 app deployment error - firebase hosting and functions

### ISSUE THREAD

**Issue by himagiri06** [nuxt/nuxt#14439]
### Environment

"devDependencies": {
    "firebase-admin": "^11.0.0",
    "firebase-functions": "^3.22.0",
    "firebase-functions-test": "^2.2.0",
    "nuxt": "3.0.0-rc.6"
  }

### Reproduction

**Steps to reproduce:**
1. npx nuxi init nuxt3-app
2. cd nuxt3-app
3. npm install
4. npm run build
   This step created .output/public, .output/server
5. npm install -D firebase-admin firebase-functions firebase-functions-test
6. firebase-tools are already installed
7. firebase login
8. firebase init steps as below

You're about to initialize a Firebase project in this directory:

? Which Firebase features do you want to set up for this directory? Press Space to select features, then Enter to confirm your choices. (Press <space> to select, <a> to toggle all, <i> to invert selection
, and <enter> to proceed)
 ◯ Realtime Database: Configure a security rules file for Realtime Database and (optionally) provision default instance
 ◯ Firestore: Configure security rules and indexes files for Firestore
 ◉ Functions: Configure a Cloud Functions directory and its files
❯◉ Hosting: Configure files for Firebase Hosting and (optionally) set up GitHub Action deploys
 ◯ Hosting: Set up GitHub Action deploys
 ◯ Storage: Configure a security rules file for Cloud Storage
 ◯ Emulators: Set up local emulators for Firebase products
(Move up and down to reveal more choices)

9. ❯ Use an existing project (selected my existing project in firebase)
11.  What language would you like to use to write Cloud Functions? **Javascript**
12. Do you want to use ESLint to catch probable bugs and enforce style? **No**
13. Do you want to install dependencies with npm now? **No**
14. What do you want to use as your public directory? **.output/public**
15. Configure as a single-page app (rewrite all urls to /index.html)? **No**
16. Set up automatic builds and deploys with GitHub? **No**
✔  Wrote .output/public/404.html
✔  Wrote .output/public/index.html
i  Writing configuration info to firebase.json...
i  Writing project information to .firebaserc...
17. Replaced the below firebase.json file (as per https://nitro.unjs.io/deploy/providers/firebase.html)
{
  "hosting": {
    "public": ".output/public",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ]
  }
}
with 
{
  "functions": { "source": ".output/server" },
  "hosting": [
    {
      "site": "<my_project_id>",
      "public": ".output/public",
      "cleanUrls": true,
      "rewrites": [{ "source": "**", "function": "server" }]
    }
  ]
}
18. NITRO_PRESET=firebase npm run build
19. firebase deploy

### Describe the bug

Firebase deployment fails

### Logs

```shell
=== Deploying to 'my-project'...

i  deploying functions, hosting
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled...
✔  functions: required API cloudfunctions.googleapis.com is enabled
✔  artifactregistry: required API artifactregistry.googleapis.com is enabled
✔  functions: required API cloudbuild.googleapis.com is enabled
i  functions: preparing codebase default for deployment

Error: An unexpected error has occurred.

**firebase-debug.log file shows the below error:**
[debug] [2022-07-26T16:18:56.380Z] Building nodejs source
[debug] [2022-07-26T16:18:56.382Z] Could not find functions.yaml. Must use http discovery
[debug] [2022-07-26T16:18:56.393Z] Error: spawn ./node_modules/.bin/firebase-functions ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[error] 
[error] Error: An unexpected error has occurred.
```

**Comment by Hebilicious** [comment]
@danielroe this can be closed as this is working now. PR to improve the instructions upstream https://github.com/unjs/nitro/issues/1370
