### ISSUE TITLE
Request for more information on static hosting deployments and `.output/public` structure

### ISSUE THREAD

**Issue by GonzaloHirsch** [nuxt/nuxt#14444]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `npm@8.1.0`
- Builder:          `vite`
- User Config:      `modules`, `css`, `target`, `ssr`, `generate`, `nitro`, `router`, `app`, `tailwindcss`, `sourcemap`, `content`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.0`, `@nuxt/content@2.0.1`
- Build Modules:    `-`
------------------------------

I'm building a blog using `@nuxt/content`.

### Reproduction

I'm generating a fully static output by pre rendering using the `generate` command.

`nuxt.config.ts` settings for this are:
```
target: 'static',
ssr: true,
```

There's not specific reproduction required.

### Describe the bug

I'm generating a fully static version of a site and I'm having issues when deploying to static hosting (AWS S3 + AWS CloudFront). The problem is I'm not able to configure the proper `Cache-Control` headers because I'm unsure about what files can be cached or not.

The `.output/public` folder has the following structure:
```
.
├── 404
│   └── index.html
├── _nuxt
│   ├── 404-4705c76c.mjs
│   ├── ContentNavigation-88760be3.mjs
│   ├── Markdown-942069b5.mjs
│   ├── ProseA-9fc6e27e.mjs
│   ├── ProseBlockquote-58dac16e.mjs
│   ├── ProseCode-3eef1334.mjs
│   ├── ProseCode.be246c80.css
│   ├── ProseCodeInline-8f155f74.mjs
│   ├── ProseEm-35428eb7.mjs
│   ├── ProseH1-c1f2c1e2.mjs
│   ├── ProseH2-042a1fc8.mjs
│   ├── ProseH3-c4f6b586.mjs
│   ├── ProseH4-55125393.mjs
│   ├── ProseH5-0c46aa61.mjs
│   ├── ProseH6-eb12c56d.mjs
│   ├── ProseHr-89803d4f.mjs
│   ├── ProseImg-75a9bab5.mjs
│   ├── ProseLi-05b2153f.mjs
│   ├── ProseOl-6d24bb0b.mjs
│   ├── ProseP-30f8a251.mjs
│   ├── ProseStrong-84f3ea3f.mjs
│   ├── ProseTable-afe4c06c.mjs
│   ├── ProseTbody-381e66b5.mjs
│   ├── ProseTd-0ec5d05d.mjs
│   ├── ProseTh-4c47a5b2.mjs
│   ├── ProseThead-56d965d3.mjs
│   ├── ProseTr-cbadfad8.mjs
│   ├── ProseUl-a93d7eff.mjs
│   ├── _...slug_-e9791b50.mjs
│   ├── _number_-46e35957.mjs
│   ├── ai-ml.c4a9225e.webp
│   ├── button-68db10e0.mjs
│   ├── cambridge.d7182075.webp
│   ├── chevronDown-e2132830.mjs
│   ├── default-2ec97094.mjs
│   ├── default.226c8ec8.css
│   ├── edinburgh.0aa3b811.webp
│   ├── entry-07be5bdb.mjs
│   ├── entry.a9299293.css
│   ├── error-404-ed345ab1.mjs
│   ├── error-404.314f7075.css
│   ├── error-500-a8b9cdb1.mjs
│   ├── error-500.4e3461e5.css
│   ├── error-aab3252c.mjs
│   ├── error-component-c91afba9.mjs
│   ├── gamedev.e8e1acb9.webp
│   ├── github-b4232dfd.mjs
│   ├── gmail-e1ac1a93.mjs
│   ├── index-2aef775b.mjs
│   ├── index-884ff02f.mjs
│   ├── inter-v7-latin-100.0c744eeb.woff
│   ├── ... more fonts
│   ├── inter-v7-latin-regular.ec31daa3.woff
│   ├── manifest.json
│   ├── mountain.87874a3c.webp
│   ├── open-sans-v27-latin-300.312e8e9f.woff
│   ├── ... more fonts
│   ├── open-sans-v27-latin-regular.d7410996.woff
│   ├── pagination-b686f15b.mjs
│   ├── park.67c7c77f.webp
│   ├── redirect-api.5a751f80.webp
│   ├── section-4b1bee5e.mjs
│   ├── smart-nfts.819e2b9e.webp
│   ├── snippit.925463aa.webp
│   └── web-socket-a9035e9b.mjs
├── api
│   └── _content
│       ├── cache
│       └── query
│           ├── 0C11i0UqLt
│           ├── 0zlI3zcwFp
│           ├── 5kKk8PAbFS
│           ├── ... more of this
│           ├── sQK2ubrf8g
│           ├── w1uwhj2egL
│           └── woxWNLCbtW
├── blog
│   ├── blog-post-1
│   │   └── index.html
│   ├── blog-post-2
│   │   └── index.html
│   ├── index.html
│   └── page
│       └── 1
│           └── index.html
├── favicon.png
├── index.html
├── meta-img.jpg
├── robots.txt
└── sitemap.xml
```

I believe the static hosting section would be missing a small explanation of what each of the folders `_nuxt` and `api` (I'm not sure if `api` is added solely by `@nuxt/content`). It would be especially useful to mention which files can be cached and which ones cannot.

For the moment I'm certain that all `_nuxt` files can be cached, while `.html` cannot, but I get weird behaviors on production before and after deploying new content, when I refresh the site. Content doesn't update unless I hard refresh the cache.

**Comment by Hebilicious** [comment]
@danielroe This is still relevant and confusing, and we could use more documentation around the nitro static presets currently vercel/netlify/cfp static. The current [doc section](https://nuxt.com/docs/getting-started/deployment#static-hosting) is a little thin, and the [nitro docs](https://nitro.unjs.io/deploy/providers/vercel) isn't covering static either.

**Comment by danielroe** [comment]
Makes sense to me :+1:

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/21594.

There is also now: https://nuxt.com/docs/getting-started/deployment#static-hosting.
