### ISSUE TITLE
`nuxt generate` and `nuxt dev` silently hang when importing from `lodash-es` in Nuxt config

### ISSUE THREAD

**Issue by jerryjappinen** [nuxt/nuxt#14443]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

- Repo: https://github.com/jerryjappinen/nuxt-config-lodash-es
- Minimal changes required to blank repo after `npx nuxi init` on RC6: https://github.com/jerryjappinen/nuxt-config-lodash-es/commit/0654d60b64cde44d2427b5ccd3050035f887f304

https://user-images.githubusercontent.com/1101002/181611258-4bb7bf25-5c18-4b46-b9e8-94b38a665297.mp4

### Describe the bug

When importing a module from [`lodash-es`](https://www.npmjs.com/package/lodash-es) in `nuxt.config.ts`, both `nuxt generate` and `nuxt build` silently hang immediately with no output. There is no error message and the command also does not fail or exit.

### Additional context

Tried it on the Edge channel today as well, same thing. I'm not quite sure but I think the issue was introduced in RC6.

Not really sure what's going on, seems obviously related to module loading somehow. I've used `lodash-es` extensively in my Nuxt 3 project so far with no issues.

If there is something wrong there that Nuxt can't handle, there should be an error message. But I don't see why this module shouldn't work just fine, it's pretty common/basic in my opinion.

### Logs

```shell
nuxt-config-lodash-es/ npm run generate

> generate
> nuxt generate

Nuxt CLI v3.0.0-rc.6                                                                                                                              
```

No output after this, the command hangs without exiting.

**Comment by tanBeehexa** [comment]
Still meet with nuxt-rc.14

**Comment by manniL** [comment]
@tanBeehexa Probably also with latest v3 - which is why the issue is still open 😋

Also possibly related: https://github.com/nuxt/nuxt/issues/15179

**Comment by danielroe** [comment]
It's possible this might be an upstream bug within `jiti`. However, it doesn't reproduce with jiti alone:

**Nuxt (edge channel)**: https://stackblitz.com/edit/github-uzjz37
**jiti**: https://stackblitz.com/edit/node-ewzzae

Which makes me think it might be a product of how we're inlining jiti into `nuxi`.

cc: @pi0 in case you have any ideas.

**Comment by manniL** [comment]
This is resolved 👍🏻

Can't repro it with the latest nuxt version. Probably also related to the solution of https://github.com/unjs/jiti/pull/141 / https://github.com/unjs/jiti/pull/142

<img width="1398" alt="image" src="https://github.com/nuxt/nuxt/assets/640208/61a40287-f0a7-42b2-bc44-101ec9654492">
