### ISSUE TITLE
`nuxi preview` for SSG serves `index.html` for all pages

### ISSUE THREAD

**Issue by codeflorist** [nuxt/nuxt#14454]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `css`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-ejjmoq?file=pages/page.vue

Then request the path `/page` directly in the browser-preview

### Describe the bug

When using `nuxt generate` the prerendered pages do not have the correct `router-link-active` and `router-link-exact-active` classes applied. 

It seems, that the classes for all pages are generated on the assumption that the current route is `/`, meaning `<NuxtLink to="/">` always has the active-classes, while links to the actual current route have not.

This is only when directly requesting the prerendered page (e.g. `/page`). Once one uses a link to navigate within the app, the classes are appllied correctly.

**Comment by garyo** [comment]
I'm glad to see this is being worked on -- took me many hours to figure out this was what was going on, rather than a bug in my app.

**Comment by danielroe** [comment]
This should be resolved in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/), or in the next release.

Let me know if not and I'll reopen.
