### ISSUE TITLE
allow trying branches on external projects

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt#14500]
Sometimes it is useful to test changes in nuxt monorepo against an external project and it is a tricky task as symlinking is not only buggy but does not produce identical behavior of final released package which is why we introduced nuxt-edge channel.

There are two ideas to do this:
- A CLI script that prepacks tarball and linked them to external project
- A CI script that released npm packages

I would go with second approach because it is easier to reproduce and not depends on a dev machine.

In order to release npm packages, we use `nuxt-edge` for nuxt 2 and `nuxt3` for nuxt 3. If we want to publish every PR or branch, it would be lots of releases and tags. For this we can have two ideas:

- Conditional github action step with a magic comment that triggers npm release
- Use Github Action artifacts to host tarball and link monorepo packages with the github URL

I would go again with second approach since it ensures artifacts get cleaned up after trial (default is one week), we do not mess up with lots of npm releases, we can release _every_ commit and more importantly security of not releasing untested code to npm but a clear temporary package.

**Comment by danielroe** [comment]
We currently have the ability to run `/trigger release` which I think resolves this.
