### ISSUE TITLE
Pass resolve.fallback to webpack config (nuxt3, nuxt.config)

### ISSUE THREAD

**Issue by rhrn** [nuxt/nuxt#14521]
### Describe the feature

Can I pass resolve.fallback data to webpack config?
```
...
  webpack: {
    resolve: {
      fallback: {
        crypto: false,
        fs: false,
        assert: false,
        process: false,
        util: false,
        path: false,
        stream: false,
      }
    }
  },
  ...
```

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
We discussed this and think the current recommendation (modifying the webpack config within a hook) makes sense for this feature, rather than extending the Nuxt config.
