### ISSUE TITLE
Enabling vite server dynamic imports

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt#14525]
Context: nuxt/nuxt.js#13819 > vitejs/vite#8641 > nuxt/framework#5506 > nuxt/framework#5506 > nuxt/framework#6412 > nuxt/framework#6423 > nuxt/framework#6433

Enabling dynamic chunks for vite server output, allows lazy loading page chunks in production and reducing startup time but due to reported issues, we currently disable this behavior until stablize and fixing hydration issues and their cause.

**Comment by danielroe** [comment]
This has been enabled by default.
