### ISSUE TITLE
 v-text on custom component with slot work in SPA but not in SSR

### ISSUE THREAD

**Issue by max5432112345** [nuxt/nuxt#14530]
### Environment

nuxt3 lates
linux

### Reproduction

https://github.com/max5432112345/nuxt-error-2/

### Describe the bug

If use v-text on custom component with slot when in SPA text is displayed in page but in SSR not displayed (hot reload only sometime make it to display but after refresh page disappear).

Index.vue
```
<template>
  <div>
    <CustomText v-text="'test'" />
     <CustomText> TEST </CustomText>
  </div>
</template>
```

CustomText.vue
```

<template>
  <span>
    <slot name="default" />
  </span>
</template>
```

**Comment by manniL** [comment]
As comments are deleted here - linking the related issue in vue core https://github.com/vuejs/core/issues/6435

**Comment by danielroe** [comment]
let's track upstream then 🙏
