### ISSUE TITLE
Windows 10 nuxt-3.0.0-rc.7 does not recompile on file changes

### ISSUE THREAD

**Issue by MichelJonkman** [nuxt/nuxt#14542]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.7`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/99michel99/auditorium The project I'm having this issue with

### Describe the bug

The project doesn't get recompiled nor hot reloaded when a file (even a page) gets changed.

### Additional context

The console does display a CSS error though that shouldn't matter
`[vite:css] Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.`

**Comment by manniL** [comment]
This should work fine in the latest release. If not, please create a new issue with a reproduction ☺️

**Comment by ojvribeiro** [comment]
For non Electron apps with the `v3` it doesn't seem to be a problem anymore. :)
