### ISSUE TITLE
Global style imports

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt#14545]
### Describe the feature

Nuxt 2 had a nice module for [style resources module](https://github.com/nuxt-community/style-resources-module) made by @manniL. I believe we could either upgrade the module to Nuxt 3 and link from official docs to support both vite and webpack or add it as a built-in and opt-in feature since seems common enough.

Related: @AngeloSchulerPiletti made a PR to docs (https://github.com/nuxt/framework/pull/6490) to add similar usage with vite.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by manniL** [comment]
Somehow I totally missed that issue  🙈 I was searching for it multiple times 😂

Anyway - https://github.com/nuxt-community/style-resources-module/ is updated to Nuxt 3 to support webpack. For Vite, we have that document in https://nuxt.com/docs/getting-started/assets#global-styles-imports.

IMO that's fine. DX could maybe be improved a little bit by setting the data in e.g. `additionalData` but not sure if that's worth the effort 🤔
