### ISSUE TITLE
document `getSSRProps` for directives

### ISSUE THREAD

**Issue by danielroe** [nuxt/nuxt#14568]
I believe the documentation is missing something or there is a bug about getSSRProps: https://v3.nuxtjs.org/guide/directory-structure/plugins/#vue-directives

When I copy the content and paste it into `/plugins/focus.ts` or `/plugins/focus.client.ts` (in a project without any directives just with pages) I get the same getSSRProps missing error as anyone above - but the besides the error, it seems to work on most mounted elements.

(To check, the `.focus()` changed to `.style.color = 'green'` did its job)

_Originally posted by @BananaAcid in https://github.com/nuxt/nuxt.js/issues/13351

**Comment by sr-mothership** [comment]
Encountered the same error following [the docs](https://nuxt.com/docs/guide/directory-structure/plugins#vue-directives) for a simple focus directive.

Only after adding
```ts
// nuxt.config.ts
export default defineNuxtConfig({
  vue: {
    compilerOptions: {
      directiveTransforms: {
        focus: () => ({
          props: [],
          needRuntime: true
        })
      }
    }
  }
});
```
from #13351 once (!) it worked.
Interestingly after removing it afterwards from the config file, the directive still works.

**Comment by floatingdino** [comment]
The SSR error is also triggered if you have an unknown directive and a Nuxt layout.
https://stackblitz.com/edit/github-kbax54?file=pages/index.vue

**Comment by snowdream** [comment]
I have met the same problem.

```
export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.vueApp.directive('focus', {
      mounted (el, { value }) {
        if(value == undefined){
            el.focus()
        }else if(value){
            el.focus()
        }
      },
      updated (el, { value }) {
        if(value == undefined){
            el.focus()
        }else if(value){
            el.focus()
        }
      },
      getSSRProps (binding, vnode) {
        // you can provide SSR-specific props here
        return {}
      }
    })
  })
  
```

**Comment by YouMixx** [comment]
How's it going? I have the same problem

**Comment by SvenWesterlaken** [comment]
Also here unfortunately still stuck with the problem. I am using a directive or a globally installed plugin to add a directive.

**Comment by akumanara** [comment]
This is super annoying. Any updates on that?

**Comment by BananaAcid** [comment]
> Also here unfortunately still stuck with the problem. I am using a directive or a globally installed plugin to add a directive.

Workaround: add a abc.client.ts with the logic and a stub with abc.server.ts to at least ignore the problem for the moment …

**Comment by Kram-V** [comment]
@BananaAcid how can we register the plugin for both client and server side? using Nuxt App? TIA

**Comment by Kram-V** [comment]
I have the same error 
![500](https://github.com/nuxt/nuxt/assets/85568722/4f5c5bb5-e2b8-491d-9e09-12afa29578e9)

**Comment by Kram-V** [comment]
and here's how I implement my registration of my plugin 

![plugin](https://github.com/nuxt/nuxt/assets/85568722/3c86cc55-6f8c-4bb2-a6ac-46e917729bf5)
![plugin-nuxt-config](https://github.com/nuxt/nuxt/assets/85568722/4db5c71e-1278-4f57-b410-125d214b2271)
![template](https://github.com/nuxt/nuxt/assets/85568722/3483f771-e4f9-410e-bb18-5e1461aeb520)

**Comment by Kram-V** [comment]
sir @danielroe

**Comment by Kram-V** [comment]
how can we register the plugin for both client/server? sir @danielroe

**Comment by BananaAcid** [comment]
@Kram-V just use filename.ts (no .client) to be loaded for both. You may check with if statements inside, it it got loaded on client or server side.

**Comment by kalnode** [comment]
For client-only directive, @BananaAcid 's solution works for me.

**Re-cap:**

**Make your directive:**
`plugins/my-directive.client.ts` // My client-only directive code

**Then copy it, rename "client" to "server" and strip out any logic:**
`plugins/my-directive.server.ts` // This file needs to exist, with logic or not

Moreover, Nuxt docs describes this exactly:
https://nuxt.com/docs/guide/directory-structure/plugins#vue-directives

>If you register a Vue directive, you must register it on both client and server side unless you are only using it when rendering one side. If the directive only makes sense from a client side, you can always move it to `~/plugins/my-directive.client.ts` and provide a 'stub' directive for the server in `~/plugins/my-directive.server.ts`.
