### ISSUE TITLE
AWS Serverless-Integration corrupts assets

### ISSUE THREAD

**Issue by gregor-poloczek** [nuxt/nuxt#14578]
### Environment

Deploying an application with nuxt version ``3.0.0-rc.6`` as a lambda function, integration in an AWS REST-API (not HTTP API).

### Reproduction

* Deploy an application with AWS lambda function serving a PNG file as an asset.
* Set it up in an AWS Rest API (Api Gateway v1)
* Set up ``binaryTypes`` with ``*/*``. 
* Access the asset via a browser.

### Describe the bug

Accessing any asset (e.g. an PNG file) causes broken data to be returned. I could track down the reason for this, and ended up in ``nitropack`` (https://github.com/unjs/nitro/blob/main/src/runtime/entries/aws-lambda.ts).

<img width="1088" alt="Bildschirmfoto 2022-08-13 um 15 43 16" src="https://user-images.githubusercontent.com/111186525/184497023-be4e27fb-c00c-4c31-bcb0-c027f300291b.png">

The ``nitroApp`` returns an ``utf8`` encoded string of the assets (which is not reasonable in this case), and not a ``base64`` encoded one. Further, the return value of the method should have included ``isBase64Encoded: true``, when an asset is returned.

If I alter the code by hand (in a deployed lambda function) the assets are returned correctly.
<img width="423" alt="Bildschirmfoto 2022-08-13 um 15 53 10" src="https://user-images.githubusercontent.com/111186525/184497219-dde552ce-5170-44a6-9bb3-80b4e6c8ac77.png">
<img width="352" alt="Bildschirmfoto 2022-08-13 um 15 52 38" src="https://user-images.githubusercontent.com/111186525/184497221-4b100a6b-182e-4e21-85fc-dd78c4e5f544.png">

I have a hard time finding flaws in my setup, when I cannot figure out, how the ``nitropack`` code would work properly for assets in the first place.

**Comment by danielroe** [comment]
This should be resolved upstream. If not, please do open a new issue there.
