### ISSUE TITLE
Pinia not working

### ISSUE THREAD

**Issue by mblachlov24** [nuxt/nuxt#14585]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `modules`, `buildModules`, `colorMode`, `typescript`, `experimental`, `vite`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.2`, `@nuxtjs/color-mode@3.1.4`, `@vueuse/nuxt@9.1.0`
- Build Modules:    `@pinia/nuxt@0.4.0`

### Reproduction

I installed the pinia, added it to buildModule and got an error when starting nuxt.
It worked fine on the RC 6.

### Describe the bug

```
 ERROR  Cannot start nuxt:  Cannot find module 'pinia/dist/pinia.mjs'                                                                                                                                                10:34:41
Require stack:
- /home/nuxt3/index.js

  Require stack:
  - index.js
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
  at Function._resolve [as resolve] (node_modules/jiti/dist/jiti.js:1:108181)
  at resolveModule (node_modules/@pinia/nuxt/node_modules/@nuxt/kit/dist/index.mjs:276:29)
  at setup (node_modules/@pinia/nuxt/dist/module.mjs:22:32)
  at Object.normalizedModule (node_modules/@pinia/nuxt/node_modules/@nuxt/kit/dist/index.mjs:607:29)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:448:3)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:1495:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6768:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6813:5)
```

**Comment by timothymarois** [comment]
I am having same issue as @Lyokolux when trying to put stores into compostables. It doesn't appear to work. And yes, pinia is installed and the same stores are working elsewhere just fine. 

```
[nuxt] [request error] [unhandled] [500] [🍍]: getActivePinia was called with no active Pinia. Did you forget to install pinia?
```

**Comment by cerino-ligutom** [comment]
I tried using `pnpm` for a change and I didn't encounter this anymore unlike with `npm`.

**Comment by madebyfabian** [comment]
Hey there, I'd suggest we can close this, not being a nuxt issue but an issue on how to properly configure pinia and or upgrade nuxt to the latest versions. Or this there anything in here that nuxt can fix I may have missed?

**Comment by BayBreezy** [comment]
For those getting the error while installing, did we add the overrides object to the package.json file?

**Comment by danielroe** [comment]
I realise people are still having trouble configuring pinia with Nuxt and would love to help solve this. If you are able, would you instead create an upstream issue in the pinia repository? Feel free to tag me and I will do my best to help.

Having said that, I don't believe this is an issue with Nuxt so I'm closing here, for now at least. 🙏

**Comment by vedmant** [comment]
In my case I started to have error: `Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/project/.output/server/node_modules/pinia/dist/pinia' imported from /Users/project/.output/server/index.mjs
`
After I tried to use pinia store from server nitro plugin. I don't think it's a pinia issue, it works with `yarn dev` but doesn't work when project is built.

**Comment by darren-h-gill** [comment]
I had this problem too. It came from "nowhere".

I have now resolved it after trying all of the above without success.

In ny case I decided to try and replicate a working setup from scratch. I started a new project using:-
> npx nuxi create

then as soon as I ran yarn install I got the "name" error!

So, the conclusion for me was my Node installation was bad.

I ran 
`> node --version `
and found that I had 19.7!!

The moral of the story is stick to using lates LTS.

So, after getting myself to node 18.15.0 , running 
`npx nuxi prepare`

all is well for me. So, my advice is if strange errors like this then check your Node version.

Also, dont run this:
`nvm install latest`

Always install the version you want!

**Comment by AuroraTea** [comment]
Same Node version, same code, at first it worked fine for me, my coworker gets this error. Today I'm working on another project with the same code, and it's my turn to get this error.

```
"nuxt": "^3.6.5",
"@pinia/nuxt": "^0.4.11",
```
Then after I updated nuxt to nuxt 3.8.0 everything worked also not fine!
```
"@pinia/nuxt": "^0.5.1",
"nuxt": "^3.8.0",
```
( I updated nuxt first but it didn't work. )

**Comment by Bobakanoosh** [comment]
With:
- pnpm
- nuxt 3
- cloudflare pages

I fixed this by:
- deleting node_modules
- deleting lock file
- installing `pinia^2.1.6` (i believe this was the key)
- `@pinia/nuxt^0.5.1`
- `nuxt^3.8.1`

**Comment by steffolino** [comment]
Hi, I am also experiencing the error
`Cannot find module 'pinia' or its corresponding type declarations.`
when trying to do this:
`import {defineStore} from 'pinia';`
with these packages:
`"devDependencies": {
    "@nuxt/devtools": "latest",
    "@nuxt/eslint-config": "^0.2.0",
    "@nuxtjs/eslint-module": "^4.1.0",
    "@nuxtjs/i18n": "^8.0.0-rc.5",
    "@nuxtjs/tailwindcss": "^6.10.1",
    "@pinia/nuxt": "^0.5.1",
    "eslint": "^8.54.0",
    "nuxt": "^3.8.2",
    "sass": "^1.69.5",
    "vue": "^3.3.8",
    "vue-router": "^4.2.5"
  }`

is it intended to use both packages 'pinia' and '@pinia/nuxt' when working with nuxt or should '@pinia/nuxt' be sufficient?

**Comment by zee-shan000** [comment]
Please add this into your nuxt.config.js/ts

`  alias: {
    pinia: "/node_modules/@pinia/nuxt/node_modules/pinia/dist/pinia.mjs",
  },`

**Comment by moonkinology** [comment]
You need to install both pinia  and @pinia/nuxt
yarn add pinia @pinia/nuxt
# or with npm
npm install pinia @pinia/nuxt
from https://pinia.vuejs.org/ssr/nuxt.html#Installation
