### ISSUE TITLE
Split dev and production output inside `buildDir`

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt#14607]
We have a special directory in nuxt called `buildDir` and by default is `${rootDir}/.nuxt` used for 
generated files such as templates, types, caches and build output.

Currently, we combine both into the same top-level directory structure which causes issues if at the same time build and start the development server they override each other. There are also directories that can leverage caching if left intact and separated including `.nuxt/cache` and `.nuxt/dist` (see nuxt/nuxt.js#14605 useful for smart rebuild and project hashes) 

This is a semi-breaking change if modules were implicitly depending on filesystem structure **with full path** of buildDir and hardcoded dirs (while they shouldn't) but probably worth doing this before final 3.0.0 release to improve long term caching of this directory.

**Comment by ruslankonev** [comment]
How about to implement this feature, because in some situations references from dev env like `import from 'file://'` get into the production builds.
