### ISSUE TITLE
when devBundler: 'vite-node'， hydration node mismatch appears in hot updates 

### ISSUE THREAD

**Issue by amihhs** [nuxt/nuxt#14610]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-rc.8-27677607.a3a8706`
- Package Manager:  `pnpm@7.5.2`
- Builder:          `vite`
- User Config:      `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

[https://github.com/amihhs/github-sj1zbq](https://github.com/amihhs/github-sj1zbq)

Reproduce
issue 1：Modify nuxt.config as needed

issue 2:change file components/comment.vue

### Describe the bug

1. An unimportant question
When I explicitly set vite config `devBundler: 'vite-node'`(I know is the default), it will appear it.
```
[Vue Router warn]: No match found for location with path "/_nuxt/D:/..../github-sj1zbq/node_modules/.pnpm/nuxt3@3.0.0-rc.8-27677607.a3a8706_rollup@2.78.0+vite@3.0.8/node_modules/nuxt3/dist/app/entry.async"
```

2. when devBundler: 'vite-node'， hydration node mismatch appears in hot updates 
![image](https://user-images.githubusercontent.com/59364234/185032540-12491480-12fc-4401-9d74-e2395f8d9c6a.png)

**Comment by danielroe** [comment]
Apologies for the long delay on this one. I'm closing issue as the reproduction is no longer available. Please feel free to comment with an updated link and we can reopen it.
