### ISSUE TITLE
Restart nuxt server when local module files are updated

### ISSUE THREAD

**Issue by max5432112345** [nuxt/nuxt#14660]
### Environment

Linux

### Reproduction

https://github.com/max5432112345/nuxt-custom

### Describe the bug

If I put that modules `https://github.com/max5432112345/nuxt-custom` in folder modules and use it in `nuxt.config` file and update file `https://github.com/max5432112345/nuxt-custom/blob/master/http/dist/runtime/templates/http.plugin.mjs` the changes are not have any effect under i not restart nuxt. Changes in other files have effect.

**Comment by danielroe** [comment]
implemented in https://github.com/nuxt/nuxt/pull/19394
