### ISSUE TITLE
Route accessibility announcer

### ISSUE THREAD

**Issue by sanjaiyan-dev** [nuxt/nuxt#14673]
### Describe the feature

Adding Route Announcer to Nuxt js for better accessibility.
Inspired by https://nextjs.org/docs/accessibility#route-announcements.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by ivan-kalachikov** [comment]
Is anybody working on it?
If no could I be assigned on the issue?
