### ISSUE TITLE
generate: Autoimported $fetch not type friendly

### ISSUE THREAD

**Issue by some-user123** [nuxt/nuxt#14677]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `pnpm@7.8.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

```js
interface Article {
  id: number
}
const article = await $fetch<Article>(`/api/article/42`)
```

### Describe the bug

According to [ohmyfetch docu](https://github.com/unjs/ohmyfetch#%EF%B8%8F-type-friendly) `$fetch` accepts a type parameter.

Using it in `nuxi generate` with auto import yields a type error:  `Expected 0 type arguments, but got 1. (ts2558)`

If explicitly imported (`import { $fetch } from 'ohmyfetch'`) the type parameter is accepted.

### Additional context

Bug occurs only when using `nuxi generate`!

**Comment by danielroe** [comment]
This should have been resolved in https://github.com/nuxt/framework/pull/8848.

See https://stackblitz.com/edit/github-hdikgx.
