### ISSUE TITLE
fail nitro build if there are errors prerendering pages

### ISSUE THREAD

**Issue by fieteboerner** [nuxt/nuxt#14676]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.3.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-6hv1ba?file=package.json,app.vue

* take a look at `package.json` & `app.vue`
* execute `npm run generate`
* run `echo $?` to get the exit code (not working inside stackblitz)
  * this should return non zero but it returns 0

### Describe the bug

The `--fail-on-error` is ignored by the `nuxi generate` command so the generate command is not backwards compatible to nuxt2.
The lack of considering this feature can lead to broken website deployments because it is not possible to differentiate between a succeed and failed generation. 

### Additional context

* https://github.com/nuxt/nuxt.js/issues/4991
* https://nuxtjs.org/docs/get-started/commands/#fail-on-error

**Comment by danielroe** [comment]
This is now implemented upstream in Nitro. You can set `nitro.prerender.failOnError` to true to enable the behaviour.
