### ISSUE TITLE
Support regex in routes

### ISSUE THREAD

**Issue by warflash** [nuxt/nuxt#14720]
### Describe the feature

This has been mentioned in nuxt/nuxt.js#13408 before, notably

> specify a route pattern in definePageMeta, which would allow full-control of the route pattern, including custom regex (e.g. /:orderId(\\d+))

but the linked pr nuxt/framework#4537 does not touch on it and I can't seem to find that sort of functionality at https://v3.nuxtjs.org/api/utils/define-page-meta/ either. 

I feel like this would be a very handy addition and remove many cases where otherwise only route hooks would lead to the desired outcome. 

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by stafyniaksacha** [comment]
> Regex in file-based routing isn't a feature afaik.

Yes, I think the [nuxt documentation](https://nuxt.com/docs/guide/directory-structure/pages#dynamic-routes) has to be updated to specify that this will not work.

Also, not sure if the `extendPages` from nuxi allows to use vue-router syntax

```ts
export default defineNuxtModule({
  setup () {
    extendPages((pages) => {
      // Add /test page
      pages.push({
        name: 'Test',
        path: '/test/:custom([a-zA-Z\S]+)', // here
        file: resolve(__dirname, './pages/test.vue')
      })
    })
  }
})
```

**Comment by HigherOrderLogic** [comment]
> Also, not sure if the `extendPages` from nuxi allows to use vue-router syntax

I think it's possible since the path got passed directly to the router.

See https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/pages/utils.ts#L243.

**Comment by stafyniaksacha** [comment]
> I think it's possible since the path got passed directly to the router.

Interesting, maybe your plugin `nuxt-params-regex` should use this instead of a runtime plugin? What do you think?

**Comment by HigherOrderLogic** [comment]
> Interesting, maybe your plugin `nuxt-params-regex` should use this instead of a runtime plugin? What do you think?

I originally tried that approach first, but somehow the page meta is always undefined inside `pages:extend` hooks so it isn't possible.

**Comment by danielroe** [comment]
This is now possible by defining the `path` within `definePageMeta`.

**Comment by HigherOrderLogic** [comment]
> This is now possible by defining the `path` within `definePageMeta`.

I still don't think this is a complete solution since user would have to re-type full route, ex: `/foo/bad/:id(\\d+)/`.

**Comment by danielroe** [comment]
It is the best we have as it's not possible to support regexp using FS API. I would have loved to, but the characters required are not supported by many file systems.

**Comment by johnson0903** [comment]
> This is now possible by defining the `path` within `definePageMeta`.

Hi, is it possible to use this with i18n with locale prefix?

Currently I have `/User/[alphabetical].vue` and `/User/[numerical].vue`, and I set pagemeta in `/User/[numerical].vue` to match the url like /User/1
```
definePageMeta({
  path: '/User/:numerical(\\d+)'
})
```
It works,  but if the url is `/us/Use/1`, Nuxt will render the `/User/[alphabetical].vue` instead

**Comment by Tofandel** [comment]
Maybe it would be better with an api like

```
definePageMeta({
  routeMatch: {
    paramName: /\d+/
  },
});
```

Then we just need to replace parameters regex with what's provided in the meta without overriding the full route
