### ISSUE TITLE
`nuxi upgrade` for Nuxt 2

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt#14741]
(Made out of PR nuxt/framework#6998)

Since `nuxi` CLI is compatible with Nuxt 2 and bridge too, we shall add support for Nuxt 2 upgrade operations as well at least until we are officially supporting Nuxt 2.

The main thing to do is checking major version of currently installed Nuxt and instead of using `<pm> upgrade nuxt@rc` use proper dist-tag based on _current major_ version.

In Next step, we could also support edge opt-in/opt-out and upgrade operations (#7027) for Nuxt 2 as well. The different is Nuxt 2 edge releases, are on `nuxt-edge` and Nuxt 3 on `nuxt3` npm package. There is high chance we deprecate `nuxt3` and use `nuxt-edge` for Nuxt 3 edge releases too eventually so that it is important this feature is built on top of major version detection

**Comment by AndreyYolkin** [comment]
@pi0 should it also be transfered to [@nuxt/cli](https://github.com/nuxt/cli) repo? I've built new PR with support for Nuxt 2 and edge packages, which will be good foundation for the second feature with channel (edge/stable) switching
