### ISSUE TITLE
Improve custom routes docs

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt#14787]
It is possible to add custom routes in multiple ways with Nuxt 3 but docs could be improved. (Routing or pages directory)

Ref: https://github.com/nuxt/framework/discussions/7211?converting=1#discussioncomment-3545577

**Comment by adrienZ** [comment]
@danielroe I think I could do this :)

**Comment by danielroe** [comment]
Amazing! ❤️

**Comment by SuleymanQ** [comment]
Hi. Is is posible to write vue router entire project without using pages directory? Thanks

**Comment by adrienZ** [comment]
@SuleymanQ you should be able to do that by passing a `RouterConfig` in your nuxt config (routes method):  https://nuxt.com/docs/guide/directory-structure/pages#custom-routes
