### ISSUE TITLE
allow modifying public assets after build (or in hook)

### ISSUE THREAD

**Issue by kstraszewski** [nuxt/nuxt#14788]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.0`
- Package Manager:  `npm@8.19.0`
- Builder:          `vite`
- User Config:      `app`, `ssr`, `postcss`, `generate`, `nitro`, `buildModules`, `css`, `meta`, `modules`, `sitemap`, `image`, `unocss`, `publicRuntimeConfig`, `vite`, `nuxtTypedRouter`, `plugins`
- Runtime Modules:  `@unocss/nuxt@0.45.15`, `@nuxt/image-edge@1.0.0-27703611.03cc029`, `nuxt-jsonld@2.0.4`, `@funken-studio/sitemap-nuxt-3@3.2.0`
- Build Modules:    `@pinia/nuxt@0.4.1`, `@vueuse/nuxt@8.9.2`, `()`

### Reproduction

I have purgecss running from CLI after building and app. Like on the top of the build process, after updating it to rc9 purgecss (which clears vuetify styles) generate `ERR_CONTENT_LENGTH_MISMATCH` error. But I couldn't manage to reproduce it on stackblitz.

1. build the app
2. use purgecss CLI `purgecss -c purgeCSSConfig.js`
3. serve the app

### Describe the bug

Purging css after build by using purgecss breaks fetching CSS.
purgecss -c purgeCSSConfig.js

**Comment by danielroe** [comment]
@burgeroften you are probably modifying them too late. you can raise an issue if you are modifying them in the `nitro:build:public-assets` hook.
