### ISSUE TITLE
RC9 Dependency Break - CJS Imports

### ISSUE THREAD

**Issue by MohammadKhalaji** [nuxt/nuxt#14790]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@pinia/nuxt@0.4.1`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-vmafic-tphsbu?file=app.vue,plugins%2Ftoastification.client.js

### Describe the bug

after `npx nuxi build` and `npx nuxi start` I get this error: 

```
[nuxt] [request error] [unhandled] [500] Named export 'useToast' not found. The requested module 'vue-toastification' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'vue-toastification';
const { useToast } = pkg;
```

### Additional context

It did NOT happen with RC8

It also happens with `vue-final-modal` on my machine

**Comment by manniL** [comment]
Closing here as main points (using `build.transpile`) have been mentioned. If there are still problems, please provide a reproduction and create a new issue! ☺️
