### ISSUE TITLE
SPA loading placeholder

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt#14796]
When SSR is false, while the initial page is being loaded, there is a white page (and if any error happens on the initial render it remains white). 

In Nuxt 2, we have [loadingIndicator](https://nuxtjs.org/docs/configuration-glossary/configuration-loading-indicator/) option with a preset of ready-to-use templates.

In Nuxt 3, it is possible to use a nitro plugin to replace the blank page.

In the meantime, we can use a Nitro plugin to have same effect:

https://stackblitz.com/edit/github-jvjkpp?file=nuxt.config.ts,server%2Fplugins%2Fplaceholder.ts

```ts
// server/plugins/placeholder.ts

export default defineNitroPlugin((nitroApp) => {
  nitroApp.hooks.hook('render:response', (res) => {
    res.body = res.body.replace(
      '<div id="__nuxt"></div>',
      `<div id="__nuxt">Loading....</div>`
    );
  });
});
```

**Comment by Atinux** [comment]
The default could be the Nuxt Logo spinner:

https://codepen.io/iamnuxt/pen/BaPyxwr
