### ISSUE TITLE
`nuxtApp.call`

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt#14805]
### Describe the feature

Context: https://github.com/nuxt/nuxt.js/issues/14269 and https://github.com/nuxt/nuxt.js/issues/14723

While we try to restore context on best efforts, It is not always possible or convenient. There is an (intended to be internal) util `callWithNuxt` from `#app` can be used to use to restore context for async composables:

```ts
import { callWithNuxt } from '#app'

// unsupported transform context
const nuxtApp = useNuxtApp()
await something()
await callWithNuxt(navigateTo, ['/route', { replace: true }])
```

It is not convenient for DX because for performance reasons, we chose to accept second arg as arg array and that also it is not auto-imported. This utility is fundamentally bound to `nuxtApp` instance and can be exposed to public API:

```ts
const nuxtApp = useNuxtApp()
await something()
await nuxtApp.call(navigateTo, '/route', { replace: true })
```

Alternatives:
- We also have `defineAsync` to resolve issue but still there is no guarantee transform method works everyever.
- We have `callWithNuxt` which could be exposed as an auto import but it is not user friendly nor makes sense to use another auto import when nuxtApp is main context

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by antfu** [comment]
For reference, @posva proposed a similar concept for Vue core: https://github.com/vuejs/core/pull/7451. I think we could align with the naming convention and maybe use it underneath later.

**Comment by danielroe** [comment]
Agreed. Might be worth waiting until the vue core PR is merged so we can align on the name.
