### ISSUE TITLE
Remove default aliases

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt#14816]
### Describe the feature

Right now, default path aliases like `~` or `@@` can't be deleted, only overridden.

Would it make sense to alter the code so setting them to a falsy value like `undefined` or `''` in the `nuxt.config.ts` would remove them entirely?

Related: https://github.com/nuxt/framework/discussions/7274

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by ddahan** [comment]
@danielroe may I suggest another solution? Adding this code to `nuxt.config.ts`:

```js
  typescript: {
    tsConfig: {
      compilerOptions: {
        paths: {
          '@': ['.'],
          '@/*': ['./*'],
        },
      },
    },
  },
```

will not modify existing aliases but the ordering in .nuxt/tsconfig.json will be changed like this:

```json
    "paths": {
      "@": [
        "."
      ],
      "@/*": [
        "./*"
      ],
      "~~": [
        "."
      ],
      "~~/*": [
        "./*"
      ],
```

Then VS code autocomplete will suggest `@` instead of `~~`.

Not sure how this solution compares to the one you provided though.

**Comment by danielroe** [comment]
Nice idea! Opened PR: https://github.com/nuxt/nuxt/pull/19937.
