### ISSUE TITLE
change vite.server.port not work

### ISSUE THREAD

**Issue by xdewx** [nuxt/nuxt#14828]
### Environment

Nuxt project info:                                                                                                  18:48:43

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.1`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `alias`, `ssr`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

1. git clone https://github.com/4tst/nuxt3-starter.git
2. change nuxt.config.ts, set vite.server.port=3001
3. npm run dev

### Describe the bug

always use port 3000 & _nuxt (hmr.path)

**Comment by danielroe** [comment]
Vite doesn't listen on a server at all with Nuxt. Instead it is Nuxt's server/port that matter. These are configurable in a number of ways including `devServer.port` and `devServer.host` (in config) and CLI arguments...

You can configure Vite's HMR details as you've done in your reproduction.
