### ISSUE TITLE
Allow Cache-Control for filetypes to boost on Lighthouse

### ISSUE THREAD

**Issue by BananaAcid** [nuxt/nuxt#14822]
### Describe the feature

Being able to set cache duration via header `Cache-Control` would be great, specifically for svgs, jpgs, pngs, mp4, webm, ... and more media types, to boost website performance massively and get better lighthouse scores.

I am kind of confused, why only E-Tags can be enabled.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by BananaAcid** [comment]
> See [unjs/nitro#18 (comment)](https://github.com/unjs/nitro/issues/18#issuecomment-1090452352). This is planned to be implemented with https://github.com/nuxt/framework/discussions/560.

Thanks for the info, note: the discussion link is dead.

**Comment by danielroe** [comment]
This should be possible now with `routeRules`:

```ts
export default defineNuxtConfig({
  routeRules: {
    '/_nuxt/**': {
      headers: {
        // number here chosen for its recognisability not for use
        'cache-control': 'public, max-age=1000999, immutable'
      }
    }
  }
})
```
