### ISSUE TITLE
navigating from one nested route to another nested route isn't synchronous

### ISSUE THREAD

**Issue by 4Kazelot** [nuxt/nuxt#14860]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.10-27710894.0cc49e2`
- Nitro Version:    `0.5.2-27709289.11cc5cd`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `experimental`, `typescript`, `vite`

### Reproduction

Go to the website and navigate between the links.

https://stackblitz.com/edit/github-lgscbs?file=pages/users/[id].vue

### Describe the bug

When we go from one page to the other (which has a child with prop from api), we get the aforementioned warning.

**Comment by champ7champ** [comment]
@danielroe I'm still suffering from this problem from project to project, I don't understand why the vue team can't fix it for so long

**Comment by danielroe** [comment]
@antfu and I are discussing another possible solution within Nuxt itself. We appreciate how frustrating this is and will see what can be done.

**Comment by mblachlov24** [comment]
https://github.com/nuxt/nuxt/issues/12487

This looks like the same bug. Can anything be done about it? I see this problem has been going on for a long time. After all, that's a pretty basic application use case. I have a lot of nested pages and it's really annoying. Navigating between nested routes is broken even in production mode (the data only changes after the page is rendered).

**Comment by danielroe** [comment]
@mblachlov24 Please read above: https://github.com/nuxt/nuxt/issues/14860#comment-1725744

**Comment by champ7champ** [comment]
Because of such problems, Nuxt 3 becomes simply useless....

**Comment by tberk** [comment]
> Having the same issue trying to navigate from one nested route to another nested router.

I am having this issue still with 3.6.0

I have lots of nested pages too, this makes them unusable, any work around available for this except not using nested pages at all?

**Comment by Luffyyy** [comment]
> > Having the same issue trying to navigate from one nested route to another nested router.
> 
> I am having this issue still with 3.6.0
> 
> I have lots of nested pages too, this makes them unusable, any work around available for this except not using nested pages at all?
> 
> 

#20798
