### ISSUE TITLE
esm - import modules (mjs, mts,..) or setting package.json's type to "module" not working as exepcted

### ISSUE THREAD

**Issue by simllll** [nuxt/nuxt#14875]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.9.0`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.1`
- Package Manager:  `npm@8.19.1`
- Builder:          `vite`
- User Config:      `srcDir`, `typescript`, `head`, `loading`, `css`, `middleware`, `runtimeConfig`, `tailwindcss`, `modules`, `env`, `build`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.3`, `~/modules/dashboardcore.mts`, `~/modules/auto-import-eslint.ts`
- Build Modules:    `-`
------------------------------

### Reproduction

(will update later)

### Describe the bug

I'm running into different issues when trying to use modules inside of the nuxt3 project.

this one is the one I'm struggling the most: I'm importing a module (mts), but it says I cannot use import statements outside a module. This doesn't make sense in any way.

e.g. [jiti] [unknown] /home/simon/Dev/hokify/hokify-dashboard/src/modules/dashboardcore.**mts**                                                                                                                                13:38:16

 ERROR  Cannot start nuxt:  Cannot use import statement **outside a module**                                                                                                                                              13:38:16

  import fs from 'fs';

### Additional context

Shoudl it be possible to use mts / mjs, or is there anything that I'm missing here?

**Comment by madebyfabian** [comment]
Hey there! Please add a [minimal reproduction](https://nuxt.com/docs/community/reporting-bugs) so we can look into that properly, thank you 🙏🏻💚

Going to mark this as can be closed for now, feel free to reopen if it still persists!

**Comment by danielroe** [comment]
I'm closing this as we don't have a reproduction. But please feel free to add one and I'll happily reopen. We have, however, made considerable improvements to https://github.com/unjs/jiti 🤞
