### ISSUE TITLE
v3 dynamic pageTransition

### ISSUE THREAD

**Issue by acidjazz** [nuxt/nuxt#14874]
### Describe the feature

in a Nuxt v2 page you could pass a function to `transition` and have a `from` and a `to` ready - this allows you to dynamically decide page transitions, in v3 I don't see how this is possible:

I tried something basic like :

```ts
const router = useRouter()
const route = useRoute()
const step =  Array.isArray(route.params.step) ? 0 : parseInt(route.params.step)
const prev = router.options.history.state.back
const prevStep = prev && typeof prev === "string" ? parseInt(prev.replace('/step/', '')) : 0
const transition = prevStep < step ? 'page-left-to-right' : 'page-right-to-left'

definePageMeta({
  pageTransition: {
    name: transition,
  },
})
```

this results in 

```
[nuxt] [request error] [unhandled] [500] transition is not defined
```

Is this at all possible? and if so how? 

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by Atinux** [comment]
Happy to close this issue then @acidjazz ?

**Comment by acidjazz** [comment]
sure @Atinux ! funny i keep coming back to this for other projects as the example - simpler version might be useful on the docs
