### ISSUE TITLE
auto imported `ref` will not trigger `vue/no-ref-as-operand` warning from eslint-plugin-vue

### ISSUE THREAD

**Issue by dsvgl** [nuxt/nuxt#14882]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.0`
- Package Manager:  `pnpm@7.11.0`
- Builder:          `vite`
- User Config:      `typescript`, `css`, `components`, `modules`, `runtimeConfig`, `vglStore`
- Runtime Modules:  `~/nuxt-modules/routes-module.ts`, `@pinia/nuxt`, `@vueuse/nuxt@9.2.0`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-cyy9sn?file=app.vue

### Describe the bug

I'm constantly forgetting to add `.value` when working with refs and wondered why eslint is not helping me – no visual hints in VS Code and no error when running eslint in terminal.
There is a rule from `eslint-plugin-vue` to catch this: [vue/no-ref-as-operand](https://eslint.vuejs.org/rules/no-ref-as-operand.html)
Turns out, the auto imported `ref` from `#imports` is somehow "different" than directly importing from `vue`.
If I do `import { ref } from 'vue'`, I get squiggly lines in VS Code and `.value` is automatically added when I save the file.
See also simple reproduction above.

```vue
<script setup lang="ts">
// uncomment this will throw vue/no-ref-as-operand
// import { ref } from 'vue';

// uncomment this will not help
// import { ref } from '#imports';

const count = ref(1);

// NOTE: should be count.value
const foo = count + 1;

console.log(foo);
</script>
```

Not sure if this should be fixed in `eslint-plugin-vue` or here.

**Comment by antfu** [comment]
PR is here: https://github.com/vuejs/eslint-plugin-vue/pull/2422

After it gets merged, we will update the nuxt config and https://github.com/antfu/nuxt-module-eslint-config

**Comment by dsvgl** [comment]
Works perfectly, thank you very much! ❤️
