### ISSUE TITLE
support a component to capture component ssr failed and then automatically render it on client

### ISSUE THREAD

**Issue by keven-wang** [nuxt/nuxt#14885]
### Describe the feature

suggest support a new build-in component: **client-only-if-ssr-failed**。through this feature，we can avoid the page ssr process was interrupted by errors from some not important components. 

i have tried to implement it myself, but i can not find the way to capture the error throwed by slot components.

```html
<client-only>
  <client-compoent-1/>
</client-only>

<ssr-render-component-1/>
<ssr-render-component-2/>  

<client-only-if-ssr-failed>
  <!-- if this compoent ssr failed, it while not interrupte the page ssr，some components  render result can used -->
  <ssr-render-component-3 />
</client-only-if-ssr-failed>
```

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
merged in https://github.com/nuxt/framework/pull/8216
