### ISSUE TITLE
How to get correct types for NUXT auto imported components?

### ISSUE THREAD

**Issue by zoey-kaiser** [nuxt/nuxt#14916]
### Environment

- vscode 
- volar (in take over mode)

### Reproduction

```sh
npx nuxi init nuxt
```

open nuxt folder in vscode
open nuxt config -> red squiggle appear

### Describe the bug

As of [RC.10](https://github.com/nuxt/framework/releases/tag/v3.0.0-rc.10) it is said we can skip importing `defineNuxtConfig`, as it should get auto imported into the nuxt config.

When I tested it in a local project, my VSCode was showing me that:

![image](https://user-images.githubusercontent.com/30908158/190373035-bcfa424c-2b45-45fc-929b-d3b927d8ad88.png)

How can we fix this?

**Comment by danielroe** [comment]
This was subsequently resolved.
