### ISSUE TITLE
dependency alias is not working using pnpm

### ISSUE THREAD

**Issue by sxzz** [nuxt/nuxt#14930]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.1`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `meta`, `build`, `typescript`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Minimum Reproduction: https://github.com/sxzz/nuxt-issue

Full Reproduction: https://github.com/element-plus/element-plus-nuxt-starter

### Describe the bug

When using pnpm (`shamefully-hoist`), dependency alias (`"@popperjs/core": "npm:@sxzz/popperjs-es@^2.11.7"`) is not working. But it works using npm.

```
Cannot find module '/path/nuxt-issue/.output/server/node_modules/@popperjs/core/dist/index.mjs' imported from /path/nuxt-issue/.output/server/node_modules/element-plus/es/components/popper/src/content.mjs
```

**pnpm:** Doesn't work. The directory of `.output/server/node_modules` is broken. There is only one file 
`package.json` in `.output/server/node_modules/@popperjs/core`. And `dist/index.mjs` goes to `.output/server/node_modules/@sxzz/popperjs-es/dist/index.mjs`

<img width="254" alt="image" src="https://user-images.githubusercontent.com/6481596/190619366-f7a8fcca-c8f2-43d7-b0a3-a2fb2dbea431.png">

---

**npm:** Works. `.output/server/node_modules/@sxzz/popperjs-es` is not existing. There are `package.json` and `dist` in `.output/server/node_modules/@popperjs/core`

<img width="255" alt="image" src="https://user-images.githubusercontent.com/6481596/190619042-83490ae1-1ca2-4702-8852-2037ee9893ee.png">

### Additional context

Relate #939

**Comment by RayJason** [comment]
edit `.npmrc`:
```
shamefully-hoist=true
node-linker=hoisted
public-hoist-pattern=*
```

**Comment by danielroe** [comment]
cc: @pi0 - I wonder if we need to resolve this in the nft tracing algorithm, particularly as we move towards full support for pnpm without `--shamefully-hoist` (https://github.com/nuxt/nuxt/issues/14146).

**Comment by danielroe** [comment]
let's track upstream in https://github.com/unjs/nitro/issues/1573
