### ISSUE TITLE
[RC 9] [RC 10] `Cannot read properties of undefined (reading 'modules')` when `vue` is installed in parent dir

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt#14952]
### Related issues

- nuxt/nuxt.js#14907 
- nuxt/nuxt.js#14802
- nuxt/nuxt.js#14928
- https://github.com/nuxt/nuxt.js/issues/14923
- sidestream-tech/sidebase#16

### Reproduction

Minimal reproduction: https://stackblitz.com/edit/github-2yn1ze?file=app%2Fpackage.json,app%2Fnuxt.config.ts

### Describe the bug

How it happens: If vue dependency is installed outside of project directory in an adjutant directory (usually home directory with `node_modules`), `vite-node` that is enabled by default for RC.9+ makes issues. (issue is with nuxt custom external options)

## Workaround 1

Try switching to the [edge channel](https://v3.nuxtjs.org/getting-started/upgrade-guide/edge-channel). It should have been solved with nuxt/framework#7612.

## Workaround 2

Check your home directory. If there is any `node_modules` dir, remove it or rename it. It is probably created wrongly in the past.

## Workaround 3

It might be also because of a monorepo setup that has `../node_modules/vue` dependency. In this case, switch to the legacy vite bundler:

```ts
export default defineNuxtConfig({
  vite: {
    devBundler: 'legacy',
  },
});
```

### Remarks

The root cause of this issue is having **multiple instances of vue in externals**. In the future similar issue might happen with different causes as vue does not support multiple version instances.

**Comment by danielroe** [comment]
We've not had recent reports of this issue. Do you think this is still something we need to track @pi0?

**Comment by ennioVisco** [comment]
> We've not had recent reports of this issue. Do you think this is still something we need to track @pi0?

I'm having a similar issue in installing a local monorepo package as a nuxt module, not sure if it is the same issue though

**Comment by ermish** [comment]
> We've not had recent reports of this issue. Do you think this is still something we need to track @pi0?

Just got this today 😓

**Comment by danielroe** [comment]
Closing as I've not seen this or heard this reported recently. But please do open a new issue with reproduction if you encounter it 🙏
