### ISSUE TITLE
[RC 10] "nuxt generate" not logging errors

### ISSUE THREAD

**Issue by lucassonsinlima** [nuxt/nuxt#14957]
### Environment

Nuxi 3.0.0-rc.10                                                                                                                                                                    15:25:59
Nuxt project info:                                                                                                                                                                  15:26:00

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.10`
- Nitro Version:    `0.5.3`
- Package Manager:  `npm@7.24.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

reproduction repository branch: https://github.com/lucassonsinlima/nuxt-reproduce/tree/bump/rc-10

In this example after running `npm run generate` with `target: 'static'` /`ssr: true`, some routes are not generated successfully and not logging any errors.

- `pages/get-started/index.vue`: using [navigateTo](https://v3.nuxtjs.org/api/utils/navigate-to/) instead of `this.$router.push` makes this route to not be prerendered.

- `pages/schedule/index.vue`: using `scss` without setting `experimental: { inlineSSRStyles: true }` isn't showing any errors too, and not prerendering correctly

- `404.vue`: after updating to `rc.10`, this catch all example https://v3.nuxtjs.org/guide/directory-structure/pages/#catch-all-route doesn't works with SSG, already tried to create the root `error.vue`. If I add this `/404.html` route to `nitro.prerender.routes` generates an empty default 404 view too.

- root `index.vue`: always prerender's correctly, even when following this "bug's" reproduction bullets above

![Captura de tela de 2022-09-19 15-50-24](https://user-images.githubusercontent.com/25435624/191093192-65e37c83-0e5e-453f-9bf7-5c18f9d40361.png)

### Describe the bug

Some pages are not being generated successfully and not logging errors.

**Comment by danielroe** [comment]
Latest Nuxt + Nitro should log errors generate routes. If not, let me know and I'll happily reopen.

**Comment by lucassonsinlima** [comment]
> 

Thankss @danielroe, I'll update my apps and test those scenarios. Btw I'm having a great experience with nuxt 3 since the first rc's 🎉
