### ISSUE TITLE
Offline Page to be used in PWA

### ISSUE THREAD

**Issue by jgupta** [nuxt/nuxt#14956]
### Describe the feature

Build process should be able to generate an offline page e.g. `offline.html` similar to `index.html` or `200.html` page that is built when `ssr` is false. This offline page can be used by PWA / Service Worker so that application may fallback to SPA when user is offline.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
This is already implemented - you can configure like this:

```js
export default defineNuxtConfig({
  nitro: {
    prerender: {
      routes: ['/200.html']
    }
  }
})
```
