### ISSUE TITLE
disabling transitions within a route change prevents fully suspended navigation

### ISSUE THREAD

**Issue by warflash** [nuxt/nuxt#14996]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.8`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-dfgsnr?file=pages%2Fother.vue

### Describe the bug

Setting
```
definePageMeta({
  pageTransition: false,
});
```
skips the blocking useFetch is supposed to do and shows a blank view instead

### Additional context

Repro uses rc8 due to stackblitz issues with rc11, tested with rc11 locally tho and same issue

**Comment by danielroe** [comment]
This is now resolved - see https://stackblitz.com/edit/github-dfgsnr-cdm2r8?file=package.json,nuxt.config.ts
