### ISSUE TITLE
cannot send FormData in `$fetch` body

### ISSUE THREAD

**Issue by RijaCloud** [nuxt/nuxt#15003]
### Environment

Operating System: Windows 10
Node Version: v14.16.1
Nuxt Version: 3.0.0-rc.08
Builder: vite
Runtime Modules: -
Build Modules: -

### Reproduction

- Create a new nuxt3 project ( doesn't matter if you are using rc10 )
- Create a new simple component to upload an image 
- Put in the component an input type file like as follows :
`<input type="file" id="file-input" multiple @change="onInputChange" />`
- Add a script tag and create a new method `onInputChange` like this : 
````
onInputChange (e) {
  const file = e.target.files
  await $fetch('/api/uploadFile', {
    method: "POST",
   body: {
     files: file
   },
   headers : {
     "Content-Type": "multipart/form-data"
   }
  })
}
````
- After that create a new ssr api in the `server/api` directory like this : 

````
import FormData from "form-data";
import { manageErrorServer } from "~~/utils/manageErrorServer";
export default defineEventHandler(async (event) => {
    const config = useRuntimeConfig();
    const body = await useBody(event);
    try{
      const res: Record<string, any> = await $fetch(
          ${config.API_BASE_URL}+"smart-product",{ 
            method: 'POST',
            body: body,
            headers: {
               "Content-Type": "mutlipart/form-data"
             }
          }
        )
      return res
    } catch (e) {
       console.log("erreur " + e.response)
       manageErrorServer(e);
    }
  });
````
### Describe the bug

The multipart/form-data is not sent by $fetch, either on the first call to the ssr api or on the second call to the backend

**Comment by ytechcsl** [comment]
```
   const formData = new FormData();
    formData.append("file", file);

    return await $fetch('/api/media/upload', {
      method: "POST",
      body: formData,
    });
```

*Note: Above code is working fine, no need to set header content type, $fetch will auto detect the right content type to the request header.

**Comment by mmartinsolisdev** [comment]
> ```
>     const formData = new FormData();
>     formData.append("file", file);
>     return await $fetch('/api/media/upload', {
>       method: "POST",
>       body: formData,
>     });
> ```
> 
> *Note: Above code is working fine, no need to set header content type, $fetch will auto detect the right content type to the request header.

Thank you very much, it worked!!!

**Comment by VISHNU-P-M** [comment]
I've a dynamic url contains reference model id, How can I proxy that?

**Comment by mehmet-zahid** [comment]
> ```
>     const formData = new FormData();
>     formData.append("file", file);
>     return await $fetch('/api/media/upload', {
>       method: "POST",
>       body: formData,
>     });
> ```
> 
> *Note: Above code is working fine, no need to set header content type, $fetch will auto detect the right content type to the request header.

thanks, this really helped. everyone do not set header then it works good. otherwise it fails .

**Comment by Bidijoe45** [comment]
I am having a related issue. I am getting a 400 (Bad request) from the server.

`const formData = new FormData();
        formData.append('file', file);
        
        $fetch("/api/activities/image", {
            method: "POST",
            "headers": {
                "Authorization": "Bearer XXXXXX",
            },
            body: formData
        })`

The error that I get, it looks like is something related with the XSS Validator.
`{
    "url": "/api/activities/image",
    "statusCode": 400,
    "statusMessage": "Bad Request",
    "message": "Bad Request",
    "stack": "<pre><span class=\"stack internal\">at createError (./node_modules/h3/dist/index.mjs:79:15)</span>\n<span class=\"stack internal\">at Object.handler (./node_modules/nuxt-security/dist/runtime/server/middleware/xssValidator.mjs:30:19)</span>\n<span class=\"stack internal\">at process.processTicksAndRejections (node:internal/process/task_queues:95:5)</span>\n<span class=\"stack internal\">at async ./node_modules/h3/dist/index.mjs:1962:19</span>\n<span class=\"stack internal\">at async Object.callAsync (./node_modules/unctx/dist/index.mjs:72:16)</span>\n<span class=\"stack internal\">at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:2249:7)</span></pre>"
}`

Thanks!
