### ISSUE TITLE
Retrieve auto-imported component / function names

### ISSUE THREAD

**Issue by MorevM** [nuxt/nuxt#15015]
### Describe the feature

Hi, I'm not sure if this is a feature request or just a question, but I didn't find any related issues / docs.

**Context:** 

I have an ESLint configuration and it contains rules [`no-undef`](https://eslint.org/docs/latest/rules/no-undef) and [`vue/no-undef-components`](https://eslint.vuejs.org/rules/no-undef-components.html) that report undeclared functions/variables/components.

![some-component vue - cardplace local_220925161713](https://user-images.githubusercontent.com/49679666/192145538-050c7716-2be9-4ad4-a25c-5a71baa89df6.jpeg)

Nuxt automatically imports many things and I like it, I don't want to import them explicitly.
[This is slightly related issue](https://github.com/nuxt/nuxt.js/issues/13413), but I don't need to import them explicitly, I need an option to retrieve a **names** of all auto-imported components/functions to declare them as global in `.eslintrc` file.

**My current workaround** is define them manually and declare as global like that:

![● Untitled-1 - cardplace local_220925163652](https://user-images.githubusercontent.com/49679666/192146406-41cadd35-b9d9-46d4-9667-53d341cba37d.jpeg)

Although this is a working solution, there are some limitations:
- It needs to be filled manually
- It doesn't update automatically if I register a new module that adds a global component (such as `@nuxt/image`) or new composables (such as `@vueuse/nuxt`)
- It doesn't update if I set custom dirs to import in `nuxt.config.ts` via `imports.dirs` and create a new file inside it.
- It doesn't update if new release of Vue/Nuxt includes a new features

So, a lot of manual work every time something was changed.
This can be done using custom module, but I believe it should be done by Nuxt itself.

**Feature request:**

Expose an auto-imported functions / components names to allow import them and mark as global in `.eslintrc`

![● Untitled-1 - cardplace local_220925170128](https://user-images.githubusercontent.com/49679666/192147619-3812b9f0-84f9-40df-84e1-171b2de61335.jpeg)

**Additional info**

I know it's recommended to disable `no-undef` for TypeScript at all, but currently, as far I know, there is no robust way to separate `<script lang="ts">` and `<script>` in ESLint confgurations for `.vue` files. 

Also Nuxt isn't only TypeScript framework. and global components still needs to be configured

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
We discussed this and think a good solution would be to write a file with components metadata based on setting an option in `nuxt.config` (maybe `components.generateMetadata`). However, note that we wouldn't recommend using eslint without TypeScript integration as there are likely to be other issues as well if it is not aware of the full Nuxt TS environment.

**Comment by BernardoSM** [comment]
I don't know the relationship between nuxt and this plugin here https://github.com/antfu/unplugin-auto-import

But if we add this config below on [nuxt import configs](https://nuxt.com/docs/api/configuration/nuxt-config#imports) will solve the globals issues

```js
  eslintrc: {
    enabled: false, // If we set this true is going to generate a file with all eslint globals
    filepath: './.eslintrc-auto-import.json',
    globalsPropValue: true,
  },
```
