### ISSUE TITLE
[ERR_MODULE_NOT_FOUND] /@vite/dynamic-import-helper

### ISSUE THREAD

**Issue by warflash** [nuxt/nuxt#15018]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.13.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction
Doesnt happen on stackblitz, so may be windows related

https://github.com/warflash/nuxt3_7794 

[Stackblitz](https://stackblitz.com/edit/github-zf3abf?file=README.md)

### Describe the bug

Adding a dynamic vite import like this:
```const messages = await import(`./locales/${newLocale}.json`);```
in rc10 or 11 throws the following error
```[vite-node] [ERR_MODULE_NOT_FOUND] /@vite/dynamic-import-helper```

### Additional context

Sorry if this is a dupe of https://github.com/nuxt/nuxt.js/issues/14995, the error seemed different tho so I figured I'd open an issue to be save

### Logs

```shell
500
[vite-node] [ERR_MODULE_NOT_FOUND] /@vite/dynamic-import-helper

at /@vite/dynamic-import-helper
```

**Comment by danielroe** [comment]
This is no longer reproducible with the latest version of Nuxt.
