### ISSUE TITLE
.env values not updating properly

### ISSUE THREAD

**Issue by Floppy012** [nuxt/nuxt#15040]
### Environment

Nuxi 3.0.0-rc.11                                                                                                  17:25:14
RootDir: /home/projects/github-gdfemr                                                                             17:25:16
Nuxt project info:                                                                                                17:25:16

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-gdfemr?file=.env

### Describe the bug

When updating values in `.env`, Nuxt will restart automatically but the changes aren't applied.

**Comment by Yolley** [comment]
> This is possibly a consequence of using disk cache for the `nuxt.config` file in c12: [unjs/c12@bb4a710](https://github.com/unjs/c12/commit/bb4a710ab8b90430767d977c44268b79a0e0fe96).
> 
> (cc: @pi0 - might it be worth revisiting my 'sync memory cache' idea instead?)

The still persists, also I've tried to disable `cache` in c12 locally, didn't help.

**Comment by pi0** [comment]
Disk cache is the transformed version of config (not evaluated version with applied env). Cause might be different. Will investigate.

**Comment by avdwio** [comment]
Is this being actively worked on?

When the .env file is updated, the line `.env updated. Restarting nuxt...` is printed to terminal. In the interim, can we remove this, or replace it with something more accurate? It's currently quite confusing and implies that `.env` is hot reloaded when it isn't, as per this issue.

I think the line should be removed, but if anyone has a better interim solution, let me know :)

**Comment by ghislaingirardeau** [comment]
I had this issue as well, nuxt version 3.2.3. I upgrade for the last version. Now it's work
