### ISSUE TITLE
nitro api code and vue component code in one file

### ISSUE THREAD

**Issue by n4an** [nuxt/nuxt#15051]
### Describe the feature

remix has nice feature to write server api and reactjs code in one file and not to have two dirs for pages (vue and nitro)

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by manniL** [comment]
This is possible in userland already - see e.g. https://github.com/Hebilicious/server-block-nuxt
