### ISSUE TITLE
error page not shown after abortNavigation

### ISSUE THREAD

**Issue by vis97c** [nuxt/nuxt#15053]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v14.19.1`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-i5nygk?file=error.vue

### Describe the bug

When throwing an error or aborting navigation from middleware nuxt does not render the error.vue page but instead shows the default nuxt error page. If this is not the intended usage of abortNavigation please provide an alternative.

using showError on a page using middlewares would trigger the same issue.

**Comment by jahidanowar** [comment]
I am having the same issue. 

@danielroe  The same is not working if we use <NuxtLink> instead of <a> 

How would it work if we use <NuxtLink>?

Here's the repro [https://stackblitz.com/edit/github-i5nygk-gnbczq?file=pages%2Findex.vue](https://stackblitz.com/edit/github-i5nygk-gnbczq?file=pages%2Findex.vue)

**Comment by danielroe** [comment]
@jahidanowar You are using 3.0.0-rc11. Here's an updated stackblitz: https://stackblitz.com/edit/github-i5nygk-tpvqbg.

Note also this linked issue: https://github.com/nuxt/nuxt/issues/15432.

**Comment by xanderbarkhatov** [comment]
> @jahidanowar You are using 3.0.0-rc11. Here's an updated stackblitz: https://stackblitz.com/edit/github-i5nygk-tpvqbg.
> 
> Note also this linked issue: #15432.

Well, it seems like it's working fine. I think the issue could be closed.

**Comment by danielroe** [comment]
I think the remaining edge case is that perhaps a _fatal_ error thrown in middleware with `abortNavigation` should show an error page.
