### ISSUE TITLE
ssrContext in render:html hook

### ISSUE THREAD

**Issue by Tahul** [nuxt/nuxt#15061]
### Describe the feature

Currently, we have to use `event` to pass some data from `app:rendered` hook to `render:html`.

As module writer, I think this is misleading, could we have access to `ssrContext` there instead which seems more suited to pass some data between those two contexts?

Also, does passing data via `event` has some side-effects? Doesn't increasing the size of the payload passed to web server could make it slower?

As for example, here is a reproduction of the pattern that currently needs to be implemented:
https://stackblitz.com/edit/nuxt-starter-igyakg?file=nuxt.config.ts,app.vue,server%2Fnitro.ts

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
~> you can now access the renderResult from the `app:rendered` hook: https://github.com/nuxt/nuxt/pull/18610
