### ISSUE TITLE
[test-utils] Hanging on windows using `useTextContext`

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt#15065]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Minimal repro: https://github.com/manniL/nuxt-test-utils-vitest-windows
Action (cancelled): https://github.com/manniL/nuxt-test-utils-vitest-windows/actions/runs/3160622271/jobs/5145286074

Also: https://github.com/Developmint/nuxt-purgecss/actions/runs/3160440554/jobs/5144897984

### Describe the bug

When using `useTestContext()` in a test on a windows environment or CI pipeline together with `vitest` >= v0.22.0, it will finish all tests but never stop the process itself, leading to hours of CI time that will never finish.

```ts
import { fileURLToPath } from 'url'
import { it, expect } from 'vitest'
import { setup, useTestContext } from '@nuxt/test-utils'

await setup({
  rootDir: fileURLToPath(new URL('../playground', import.meta.url))
})

it('should finish on windows', () => {
  const _ctx = useTestContext()
  expect(true).toBe(true) // Tests run but it never finishes
})

```

![grafik](https://user-images.githubusercontent.com/640208/193325838-d17e2d5b-0075-4bee-8a72-05e9d6b32370.png)

**Comment by danielroe** [comment]
This is no longer reproducible for me with latest Nuxt.
