### ISSUE TITLE
cannot find client.manifest.mjs when adding or removing package while dev server is up

### ISSUE THREAD

**Issue by huang-julien** [nuxt/nuxt#15069]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `yarn@3.2.3`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

- start nuxt dev 
- on another terminal , install any package using yarn (not tested with npm or pnpm)
- try to go on any page 
- error 500 

### Describe the bug

Hi :wave: ,

adding a package while the dev server is on cause `.nuxt/dev` and `.nuxt/dist` being deleted.

stopping and reloading the server solves the issue since it regenerate `.nuxt` directory.

I reproduced this on window and WSL(ubuntu)

### Logs

```shell
Cannot find module '/mnt/d/GIT/test/.nuxt/dist/server/client.manifest.mjs' imported from /mnt/d/GIT/test/.nuxt/dev/index.mjs
```

**Comment by sreenivasanac** [comment]
I also had this problem. Resting the dev server fixed the problem

**Comment by cpres** [comment]
> postinstall

I restarted the dev server to get out of this temporarily, but it kept coming back daily until I removed the postinstall script. Thanks!
