### ISSUE TITLE
Improve loading sequence of hydration `<script />` 🚀 

### ISSUE THREAD

**Issue by sanjaiyan-dev** [nuxt/nuxt#15072]
### Describe the feature

Hi,

### Current Problem
Nuxt js currently preload then execute the scripts at the bottom of the body for priority boosting. But `link:rel=preload` doesn't have greater browser support so I'm browser which doesn't support it will take long time to fetch and execute it.

![without-defer-async-body](https://user-images.githubusercontent.com/88643231/193379491-acad4a05-22a9-4b21-82d7-905ce6e36198.png)

### Solution

I propose an alternate approach to load first party script with defer, where `<script defer>` will be added to the , with the objective of streamlining the overall loading sequence, modeling web-performance best practices, and moving away from preload as a crutch for signal boosting.

Browser compatibility (MDN) -:

`<link rel="preload" />`
![Screenshot_2022-09-23-12-37-12-744_com android chrome](https://user-images.githubusercontent.com/88643231/193379578-3192faec-b37d-448a-b284-d1493e3bca60.png)

`<script defer>`
![Screenshot_2022-09-23-12-36-40-735_com android chrome](https://user-images.githubusercontent.com/88643231/193379595-99304c1a-fa8b-42da-a32b-75a73c0b1d06.png)

### Advantages 

- Scripts wont block the HTML parsing as intended.
![with-defer](https://user-images.githubusercontent.com/88643231/193379649-9ea0fc7c-5af6-4964-a47e-fd775a832860.png)

- Improvements in FCP, LCP metric, faster time to visual-completeness.

- Additional optimization and predictability given the guaranteed order of execution of defer scripts.

### Issue when implementing

This works perfectly fine for `type=module`(automatically adds defer attr) scripts too but for them preloading having some benefits so we need to conditionally add preload tag if it is targeted to new module based syntax.

### References

Current Next js implementation (Please check this out for better understanding)-: https://github.com/vercel/next.js/discussions/24938

About scripts loading-: https://gist.github.com/jakub-g/385ee6b41085303a53ad92c7c8afd7a6

Issues of preloading-: https://docs.google.com/document/d/1ZEi-XXhpajrnq8oqs5SiW-CXR3jMc20jWIzN5QRy1QA/
___

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
This is not the case in Nuxt 3. We render scripts within `<head>`. There's also no explicit `defer` required for module scripts; this is how they execute by default.
