### ISSUE TITLE
Document that user should not use separate `nitro.config.ts` (and other configs like webpack/vitest/...)

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt#15085]
### Describe the feature

When using Nuxt, the nitro config should live inside the `nuxt.config.{js,ts}` instead of a separate `nitro.config.{js,ts}`. Same for a custom webpack or vite config. Ideally this should be documented.

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
I think we might be able to close this as completed in https://github.com/nuxt/nuxt/pull/22521. What do you think?

We can also add to docs...

**Comment by pi0** [comment]
I think the warning is enough to close this. Nice idea for docs it can be an appendix in [here](https://nuxt.com/docs/getting-started/configuration#vue-configuration) to help users onboard in next steps if they see any (external) docs referring to `nitro.config` how to translate.
