### ISSUE TITLE
Nested API routes don't work with slash

### ISSUE THREAD

**Issue by frbuceta** [nuxt/nuxt#15109]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.9.1`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `css`, `watch`, `postcss`, `build`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

```js
const router = createRouter()
  .get('/', async () => {})
  .post('/', async (evt) => {})
  .patch('/:id', async (evt) => {})
  .delete('/:id', async (evt) => {})

export default useBase('/api/banners', router.handler)
```

![image](https://user-images.githubusercontent.com/13822438/194344572-75ba415e-0b62-429a-9698-a78326dbecc1.png)
![image](https://user-images.githubusercontent.com/13822438/194344685-f5f9848f-d6c3-4eb8-bbc8-bd393ba5c083.png)

### Describe the bug

Nested routes with backslash do not work. For example:

![image](https://user-images.githubusercontent.com/13822438/194343872-0d530d04-c41c-4494-b052-47e928e9f937.png)

`/api/banners` does not load but `/api/banners/` does load.

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/15109.
