### ISSUE TITLE
non-ascii character in page path fails build, but only for scripts with `lang="ts"`

### ISSUE THREAD

**Issue by dargmuesli** [nuxt/nuxt#15113]
### Environment

- Operating System: `Linux`
- Node Version:     `v14.19.3`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://codesandbox.io/s/teapot-lfnl4w?file=/pages/%F0%9F%AB%96/index.vue

### Describe the bug

Having a non-ascii character in a page path, e.g. `ä` or `😆`, makes the build fail, **but only with `<script lang="ts">`** and not with `<script>`.

Run a `yarn build` in the linked codesandbox. Took me hours to find, I'm a teapot 🫖.

### Additional context

This must be an upstream issue, but I need pointers to the correct one to issue a ticket on. I'm pretty sure it is neither vite nor rollup directly as the `lang` makes the difference.

### Logs

```shell
ERROR  [vite:vue] Could not load /sandbox/pages//u{1FAD6}/index.vue?macro=true&vue&type=script&lang.ts (imported by pages/🫖/index.vue?macro=true): ENOENT: no such file or directory, open '/sandbox/pages//u{1FAD6}/index.vue'


 ERROR  Could not load /sandbox/pages//u{1FAD6}/index.vue?macro=true&vue&type=script&lang.ts (imported by pages/🫖/index.vue?macro=true): ENOENT: no such file or directory, open '/sandbox/pages//u{1FAD6}/index.vue'

  at Object.openSync (fs.js:498:3)
  at Object.readFileSync (fs.js:394:35)
  at getDescriptor (node_modules/@vitejs/plugin-vue/dist/index.mjs:84:10)
  at Object.load (node_modules/@vitejs/plugin-vue/dist/index.mjs:2611:28)
  at node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:22710:40
  at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by loicpennequin** [comment]
I've also encountered this exact same issue when trying to build a project on my local machine as my user folder has a special character in it
