### ISSUE TITLE
Type inference on useLazyFetch with formatted string not working

### ISSUE THREAD

**Issue by GionRubitschung** [nuxt/nuxt#15116]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.17.1`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `pnpm@7.12.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

I tried to recreate a [codesandbox](https://codesandbox.io/s/fast-bush-4jl1xg?file=/pages/index.vue) but it doesn't really work. The route and response type is build the same way as in my project.

But since the issue is quite simple you just need a nuxt 3 project with typescript and a server route wit a parameter that returns something with a type.

### Describe the bug

I am using nuxt 3 with typescript and the composition api. I have noticed something with the type inference on the fetch composables. I don't receive the the inferred type when using formatted strings for parameters.

When typing in the route into `useLazyFetch` I get the correct recommendations for the existing routes:
![image](https://user-images.githubusercontent.com/43574999/194820324-81c1368a-3fe4-4b14-8690-128796048a10.png)

The type gets inferred correctly when not used a formatted string:
![image](https://user-images.githubusercontent.com/43574999/194820443-c4d3a03b-77a5-4e0a-a618-7c063c3010b1.png)

However when I use the formatted string the type inference does not work anymore:
![image](https://user-images.githubusercontent.com/43574999/194820723-b756a36e-11aa-44ae-8fc0-345c40d55e5c.png)

When hovering over the useLazyFetch method the type contains the given route and when used with the formatted string this is `/api/rpa/${string}`:
![image](https://user-images.githubusercontent.com/43574999/194821377-d3459f4d-e2c1-45ea-979d-112fb22db87f.png)

I can define the response type manaully with `useLazyFetch<T>` or in my example ```useLazyFetch<ApiResponse<rpa>>(`/api/rpa/${route.params.id}`)```

I haven't found an explanation in the docs, is there a way to achieve type inference wihtout declaring the type manually?

**Comment by danielroe** [comment]
Method based typing is now implemented.
