### ISSUE TITLE
Server built on Windows not handling simultaneous requests

### ISSUE THREAD

**Issue by JeffreyTan1** [nuxt/nuxt#15164]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`, `privateRuntimeConfig`, `publicRuntimeConfig`, `build`, `vite`, `typescript`, `dev`
- Runtime Modules:  `@pinia/nuxt@0.4.2`, `@nuxtjs/tailwindcss@5.3.3`
- Build Modules:    `-`

### Reproduction

- Clone https://github.com/JeffreyTan1/nuxt-bug-reproduction

I scaffolded the project like so https://v3.nuxtjs.org/getting-started/installation/ and the api from here https://v3.nuxtjs.org/guide/directory-structure/server/

- I use JMeter to simulate multiple users hitting the server at once. You can get JMeter from here: https://archive.apache.org/dist/jmeter/binaries/ I have the distribution found at apache-jmeter-5.4.3.zip.

As a quick tutorial of how to setup a JMeter stress test on Windows:

- Unzip the download
- Go into the bin folder
- Open the ApacheJMeter JAR file (opens the GUI)
- [Create thread group](https://i.stack.imgur.com/hjXG6.png) and set the following [properties](https://i.stack.imgur.com/i1KFf.png).
- [Create a HTTP Request sampler](https://i.stack.imgur.com/e3AVh.png) and set the following [properties](https://i.stack.imgur.com/9kZ66.png)
- [Create a View Results Tree listener](https://i.stack.imgur.com/rkCKt.png) and stay in this window
- Click the green play button to run the test and the gear+broomstick button to clear the output

You should see 200 responses interspersed by 503 responses. 
![image](https://user-images.githubusercontent.com/67099352/195734695-813f7e47-22ae-4664-a58c-881b58342eb6.png)

### Describe the bug

The Nuxt server is not handling simultaneous requests and is only happening on Windows.

Sometimes, when two or more requests hit the server at the same time, only one of them gets served, and the other requests return with a 503 Server Unavailable response instead of being added to the queue.

I have tested on ARM and Intel MacOS systems as well as WSL - all of which do not have the same problem. I have also tried Node v14.16 and LTS (v16.17.1). 

This seems to me like a very low-level framework issue. The last version of Nuxt3 I've used is `'nuxt3': 3.0.0-27376943.f219f63` which did not have this problem.

**Comment by teamboot88** [comment]
I have same problem..

**Comment by sbittmann** [comment]
I'm facing the same problem. I think this issue is related to https://github.com/nuxt/nuxt/issues/15188. The error seems to occure here in the generated ".nuxt/dev/index.mjs":

``` javascript
if (!address || address.socketPath && !existsSync(address.socketPath)) {
  return errorHandler$1(lastError, event);
}
```
The dev proxy-server uses named-pipes on Windows and sometimes, but mostly under load `fs.existsSync()` returns `false` and that means nuxt thinks the dev-proxy-server is not up. After deleting mentioned code above in my tests I didn't got any 503 error message anymore.
I'm looking more detailed into it later.

**Comment by danielroe** [comment]
So, to be clear, this is only happening for dev server, not built server?

**Comment by sbittmann** [comment]
@danielroe 
I think so, as the returned html is only available inside in https://github.com/nuxt/nuxt/issues/15164#issuecomment-1397373069
is only avaible in https://github.com/unjs/nitro/blob/main/src/dev/error.ts and there is no other place then the devServer this is used. 

The real lower level bug must be inside nodejs it self as `fs.existsSync()` and `await fs.promises.access().then(() => true, () => false)`  should always return the same, but I don't know how to fix it there ...

**Comment by csprance** [comment]
Yes I have noticed it happening only on windows dev server in my tests as well

**Comment by timb-103** [comment]
Same happening here. Not happening all the time, just randomly.

**Comment by tinawng** [comment]
It keeps happening randomly.
The only way around I found is to use WSL 😐

**Comment by WolfVector** [comment]
I'm on windows and I have the same issue. It just happens randomly.

**Comment by Hebilicious** [comment]
@tinawng @WolfVector 
There's a fix available [here](https://github.com/unjs/nitro/pull/1115/files)

You can try it by writing a pnpm patch for nitropack (or equivalent) .

```ini
- if (!address || (address.socketPath && !existsSync(address.socketPath)))

+ if (!address || (address.socketPath && !fs.accessSync(address.socketPath))
```

**Comment by csprance** [comment]
It's been released to nitro in 

https://github.com/unjs/nitro/releases/tag/v2.5.2
https://github.com/unjs/nitro/pull/1115

Just missed the 3.6.1 release though so hopefully soon!

**Comment by mythshuazi** [comment]
> Thanks for the ping. This should be resolved in nitropack v2.5.2, which you can get with `yarn upgrade nuxt` or `npm upgrade nuxt` (or `npx nuxi upgrade --force`). There's no need to wait for the next Nuxt upgrade.
> 
> Let me know if not and I'll reopen.

this issue is not resolved in v2.5.2
`
// comment this code, this problem is resolved
if (worker.address.socketPath && existsSync(worker.address.socketPath)) {
    await promises.rm(worker.address.socketPath).catch(() => {
    });
  }`

**Comment by danielroe** [comment]
Any chance you could raise an issue on the nitro repository?

**Comment by jongmin4943** [comment]
I don't think it is resolved in nuxt 3.6.3 even with `nuxi upgrade --force`.

![image](https://github.com/nuxt/nuxt/assets/77711322/ba96c7f0-0684-4b96-9085-c505c211e8e7)

If I call api many times at once, some of them fails with status code 503, try again it self, and return with status code 200.
I made a middleware to check it, the server middleware doesn't get the request that has status code 503.

![image](https://github.com/nuxt/nuxt/assets/77711322/aff00de4-e9cf-4a3d-a265-c837e1aa9608)

**Comment by Hebilicious** [comment]
@danielroe just re-opened https://github.com/unjs/nitro/issues/1338 for upstream tracking

**Comment by danielroe** [comment]
Updating as we've moved issues. Let's track in https://github.com/nuxt/nuxt/issues/22150 (as it's not solely a Windows issue) and upstream in https://github.com/unjs/nitro/issues/1454.
