### ISSUE TITLE
`nuxt build` makes it impossible to configure logging

### ISSUE THREAD

**Issue by BrankoKrstic** [nuxt/nuxt#15175]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.17.1`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

JSONReporter works when ran with `nuxt dev` but doesn't with `nuxt build`.
[Stackblitz](https://stackblitz.com/edit/github-rhycbx?file=nuxt.config.ts,package.json)

### Describe the bug

The code in the reproduction successfully outputs logs in json format when run with `nuxt dev`. However, an app built with `nuxt build` outputs all logs in standard format - not even one produced by a different consola reporter but the same as making a console call. Even logs created by the logger instance have the same format.

I tried to use `logger.wrapConsole` and a custom reporter, but the result is the same. It's like consola is not processing the logs when the app is built. 

### Additional context

The middleware file might be a poor place to change the logger config, but that's th location I found that applies the JSONReporter to all log calls

### Logs

`nuxt dev` log format:
```json
{"date":"2022-10-17T17:35:08.376Z","args":["Incoming request to /"],"type":"info","level":3,"query":{},"tag":""}
{"date":"2022-10-17T17:35:08.376Z","args":["Incoming request to /","(repeated 2 times)"],"type":"info","level":3,"query":{},"tag":""}
```

`nuxt build` log format:

```
{ message: 'Incoming request to /', query: {} }
{ message: 'Incoming request to /', query: {} }
```

**Comment by danielroe** [comment]
I've updated your reproduction slightly for the recent consola major upgrade - this should be possible: https://stackblitz.com/edit/github-rhycbx-5erah3.
