### ISSUE TITLE
v3.0.0-rc.12 - Google Firebase functions no longer generated by Nitro

### ISSUE THREAD

**Issue by Sandlens** [nuxt/nuxt#15185]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `npm@8.5.0`
- Builder:          `vite`
- User Config:      `modules`, `ssr`, `nitro`, `app`
- Runtime Modules:  `@nuxt/content@2.1.1`, `@nuxtjs/tailwindcss@5.3.5`, `@pinia/nuxt@0.4.3`, `@nuxt/image-edge@1.0.0-27719579.87dcdf2`
- Build Modules:    `-`
------------------------------

### Reproduction

.

### Describe the bug

I am hosting my Nuxt project on Google Firebase.

Since upgrading to v3.0.0-rc.12, `npx nuxi build` no longer generates functions properly in .output\server, despite setting the preset to Firebase with the following:

```
export default defineNuxtConfig({
  nitro: {
    preset: 'firebase'
  }
})
```

The issue also occurs if using `NITRO_PRESET=firebase npm run build`.

When attempting preview the project locally with `firebase emulators:start`, the following error occurs:

```
i  functions: Watching "C:\Users\<...>\<repo-name>\.output\server" for Cloud Functions...
The system cannot find the path specified.

Error: An unexpected error has occurred.
```

Hence, the project cannot be previewed locally or deployed.

### Logs

From `firebase-debug.log`:

```
[debug] [2022-10-19T01:36:21.196Z] Building nodejs source
[debug] [2022-10-19T01:36:21.197Z] Analyzing nodejs backend spec
[debug] [2022-10-19T01:36:21.198Z] Could not find functions.yaml. Must use http discovery
[debug] [2022-10-19T01:36:21.223Z] Error: spawn ./node_modules/.bin/firebase-functions ENOENT
    at notFoundError (C:\Users\louis\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\louis\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\louis\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
[error] 
[error] Error: An unexpected error has occurred.
```

**Comment by davidstackio** [comment]
For me, after I updated to recent versions of Nuxt and Firebase, using the `firebase deploy` command no longer works. I got an error when deploying the function about package-lock having mismatched versions. I spent a few hours trying to figure out what was wrong until I came up with the below solution.

Now I use `npm run deploy` to deploy. Excerpt from my `package.json`:
```
"scripts": {
    "build": "nuxt build",
    "deploy": "npm run build && npx firebase deploy",
```

This successfully deployed my 'server' Node18 fuction.

**Comment by Hebilicious** [comment]
@danielroe this is tracked here https://github.com/unjs/nitro/issues/628

**Comment by Chuiantw1212** [comment]
Somehow wont work on windows recently?

![image](https://github.com/nuxt/nuxt/assets/10844438/ab3d4dfc-7038-4afc-b432-b15c4519c611)

**Comment by danielroe** [comment]
let's close to track in https://github.com/unjs/nitro/issues/628
