### ISSUE TITLE
with `treeshakeClientOnly`, scoped style attributes don't match between server + client builds

### ISSUE THREAD

**Issue by Sopamo** [nuxt/nuxt#15227]
### Environment

Nuxi 3.0.0-rc.12
RootDir: /home/projects/github-xq94aj-dtefps
Nuxt project info: 

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `webpack`
- User Config:      `builder`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

 - Open [the reproduction](https://stackblitz.com/edit/github-xq94aj-dtefps?file=Component.vue)
 - Run `npm run generate`
 - Run `cd .output/public`
 - Run `npx serve`
 - The line on the bottom has no styles. When running `npm run dev` it does.

### Describe the bug

When:

 - Using the webpack builder
 - And using a `<client-only>` component somewhere in a component
 - And using scoped styles in that component
 - And using `npm run generate`

Then:
 - Only the elements inside of the `<client-only>` component have the scoped styles applied
 - It appears as if the data attributes that make scoped styles work are assigned incorrectly to all the elements that are not inside of the client-only component

I would expect:
 - The behaviour to be the same between `npm run dev` and `npm run generate`
 - Scoped styles to be applied for all elements in a component, no matter if `<client-only>` is used or not

### Additional context

It works as expected when using the default vite builder.

**Comment by danielroe** [comment]
resolved in https://github.com/nuxt/nuxt/issues/8713
