### ISSUE TITLE
🚀 Feature Request: ability to access nuxt indicator start/stop for when we call fetch/await/etc on pages

### ISSUE THREAD

**Issue by acidjazz** [nuxt/nuxt#15232]
### Describe the feature

Say I have a page with pagination, and I'd like the indicator to fire when I'm loading data for my next page, currently I do something like this:

```ts
const get = async ({page = 1}) => {
  const nuxtApp = useNuxtApp()
  nuxtApp.callHook('page:start')
  tokens.value = await $api.index<models.TokenResults>('/token', { page: page })
  nuxtApp.callHook('page:finish')
}
```
> `$api.index` is an api lib wrapper around `$fetch`

this is currently a bit dangerous since i don't know what else is  listening to these hooks.

 **It would be nice to be able to start/stop the loading indicator**
 
I'm not quite sure how this would work.. maybe we can set aside a couple other hooks for the loading indicator:

```ts
nuxtApp.hook('loading:start', indicator.start)
nuxtApp.hook('loading:finish', indicator.finish)
```

maybe you can let us specify optional hooks via props?

```html
    <nuxt-loading-indicator start="loading:start" finish="loading:finish" />
```

or maybe some easier/better way - but it would be awesome!

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by sky-code** [comment]
Another option is to expose `indicator` from `NuxtLoadingIndicator` so it can be accessed from other components or make `useLoadingIndicator` exported composable.
nuxt2 provides `$nuxt.$loading.start()` and `$nuxt.$loading.finish()`, but nuxt3 does not offer any alternative to this API.

**Comment by danielroe** [comment]
depending on https://github.com/nuxt/nuxt/issues/14221
