### ISSUE TITLE
Make NuxtLink scroll to anchor by default

### ISSUE THREAD

**Issue by iBobik** [nuxt/nuxt#15238]
### Describe the feature

```
<NuxtLink to="/#shop">Buy now</NuxtLink>
```

Currently we have to use [inconvenient workaround](https://github.com/nuxt/nuxt.js/issues/14033), but it should by default scroll to anchor.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
We could implement this but it feels like this should be an upstream fix to `vue-router` directly. I might be missing some context, but I'm happy to implement upstream if you agree @posva.

**Comment by posva** [comment]
This should work by default when adding a `scrollBehavior()` that returns the element to scroll to. It can fail if using transitions or anything that delays the mounting of the incoming page. Maybe that's where this is failing? This is working on vue-router

**Comment by danielroe** [comment]
In fact, it seems to work fine: https://stackblitz.com/edit/github-cslzpy.

I think this must have been resolved subsequent to the creation of the issue. If you're still encountering this, please feel free to provide a reproduction and I'll look into it.
