### ISSUE TITLE
`nuxi build` produces different output depending on OS

### ISSUE THREAD

**Issue by Minecraftschurli** [nuxt/nuxt#15244]
### Ubuntu (WSL)
Nuxi 3.0.0-rc.12
Nuxt project info:

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `npm@8.1.2`
- Builder:          `vite`
- User Config:      `dev`, `telemetry`, `modules`, `content`, `nitro`
- Runtime Modules:  `@nuxt/content@2.2.0-27769557.42fffc9`, `@nuxt/image@1.0.0-27769790.4b27db3`
- Build Modules:    `-`
------------------------------

### Windows
Nuxi 3.0.0-rc.12
Nuxt project info:

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.11.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `npm@8.1.3`
- Builder:          `vite`
- User Config:      `dev`, `telemetry`, `modules`, `content`, `nitro`
- Runtime Modules:  `@nuxt/content@2.2.0-27769557.42fffc9`, `@nuxt/image@1.0.0-27769790.4b27db3`
- Build Modules:    `-`
------------------------------

### Reproduction

- create project with nuxt/content
- build on windows
- build on linux (make sure to re-install all dependencies)
- compare output directories

### Describe the bug

Running `nuxi build` on Ubuntu makes a folder structure inside `.output/server/chunks`. 
Run the same command in the same project on Windows and the chunks are all in the chunks folder (except the content of the raw folder)

**Comment by danielroe** [comment]
This should be resolved in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/) via the linked PR upstream in Nitro, and the fix should be included in the next release.
