### ISSUE TITLE
Ability to inject build config, auto-imports, global funcs etc. in another Node env (Storybook, Jest)

### ISSUE THREAD

**Issue by fabis94** [nuxt/nuxt#15265]
### Describe the feature

Currently if you want to use Nuxt with Storybook or Jest you can't really do it unless you introduce hacks that replicate global functions and auto-imported component behaviors which is not only very time consuming, but as I already mentioned - very hacky.

Not just that, but the Vite build config is encapsulated pretty deeply inside Nuxt internals so it's also not possible to re-use the same build config for other tools like Storybook.

# Extracting the build config

I did some debugging and found out that you can use `loadNuxt()` from `@nuxt/kit` to initialize a Nuxt instance, subscribe to the "vite:extend" hook which receives the final vite config and invoke `bundle()` from `@nuxt/vite-builder`, which will then build the final vite config and put it through the aforementioned hook.

You have to throw an error in that hook to kill the actual bundling process, but at least this way you can actually access the vite config from an external script.

Actually running this logic from within the Storybook builder is practically impossible, however, cause there's some transpilation going on (by Storybook/Esbuild?) which does something that breaks various imports in `@nuxt/vite-builder`/`@nuxt/kit`.

Errors like:
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in ./node_modules/@nuxt/vite-builder/node_modules/estree-walker/package.json
```

or if you downgrade estree-walker to v2 and get past that error, then you get the next one:
```
Error: Package subpath './transform' is not defined by "exports" in ./node_modules/unctx/package.json
```

(unctx/package.json actually does define a ./transform sub-path, but I think this happens cause storybook/esbuild convert all ESM modules to CJS for some reason)

I don't know how to solve these issues properly, but it's clear that it's possible to get the Vite config out and thus it shouldn't be too hard to implement.

# Setting up a Node.js/Vue environment to be like the Nuxt one

Haven't done much investigation in this area, but this would involve:
* Setting up global directives & components (auto-imports)
* Setting up global functions

Maybe one of the Nuxt packages could export a function that sets this up in any kind of environment, whether its Jest or Storybook?

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
This is definitely somethiing I'd love to help set up and get working for anyone who is working on an integration like Storybook, Jest, Histoire, etc.

You can see the approach I'm currently using in https://github.com/danielroe/nuxt-vitest.

**Comment by fabis94** [comment]
@danielroe Didn't look through it very thoroughly, but it looks like you're doing the inverse of what I was attempting - instead of injecting Nuxt into X (Storybook/Vitest), you're injecting X into Nuxt. That does seem like a better idea, cause then you don't actually need to mock anything as everything's running inside a real Nuxt environment.

Not sure how that would work for Storybook, however, considering that we want the Storybook app frame to be its own app and only the preview/canvas iframe to be ran with Nuxt 🤔

**Comment by danielroe** [comment]
No, it does inject Nuxt into X. We only start Nuxt briefly to grab the configuration.

**Comment by fabis94** [comment]
> No, it does inject Nuxt into X. We only start Nuxt briefly to grab the configuration.

Ah, alright I'll have a deeper look into it at some point

**Comment by yassilah** [comment]
Hi! I've recently been working on integrating Storybook with Nuxt as well and came up with this module: https://github.com/yassilah/nuxt-storybook It's very much wip but it basically just merges the Nuxt and Storybook vite configs. The only thing of course is that you don't have access to the actual Nuxt intance (e.g. app.config, runtime config)...

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/14534.

We currently do this in https://github.com/danielroe/nuxt-vitest and the new storybook module does similarly.
