### ISSUE TITLE
onMounted 为什么执行两遍？

### ISSUE THREAD

**Issue by horizon188** [nuxt/nuxt#15273]
### Environment

？

### Reproduction

。

### Describe the bug

从上一个页面进来当前页面时候，onMounted的代码执行了两遍；但是刷新当前页面时候，onMounted的代码就执行一遍，请问怎么解决onMounted的代码执行两遍问题？是什么导致的？

**Comment by manniL** [comment]
Hey! No reproduction was provided for a month. I'll close this issue here.
If it issue persists, feel free to add a reproduction and ping again ☺️
