### ISSUE TITLE
Setting port (and possibly host) via Nuxt config

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt#15341]
> As a newcomer to Nuxt (V3 in particular) I have to express my surprise that something as simple as setting the host port is not part of the configuration and even requires extra logic if you want to keep it in a `.env` file.

_Originally posted by @mikehaertl in https://github.com/nuxt/framework/discussions/1290#discussioncomment-3455211_
    

@pi0's reply:

> It was because how nuxi cli works by starting a listener ahead of time (before loading nuxt and config). But we changed that since I initially answered. I think we can sort out something for config support.

**Comment by danielroe** [comment]
resolved in https://github.com/nuxt/nuxt/pull/19055
