### ISSUE TITLE
Server-side HMR for virtual modules / templates

### ISSUE THREAD

**Issue by tobiasdiez** [nuxt/nuxt#15373]
### Describe the feature

Not sure if this is a bug or feature request, but if one uses the new `updateTemplates` to update a template that is imported server-side, then it doesn't seem to trigger HMR.

Reproduction: https://github.com/tobiasdiez/nuxt-graphql-server/pull/13
- Run `pnpm dev`
- Open `localhost:3000` (the webpage) and `localhost:3000/api/GetSchema` (api route)
- Change something in `playground/server/schema.graphql`
- Observe that the webpage is updated, but refreshing server api route still prints the old schema

As can be seen in the linked PR, I tried to manually trigger the HMR by calling the `viteServer.reloadModule(module)` method (introduced in vite 3.2), but that doesn't seem to work either because the server-side import is not registered correctly in the virtual module (the only `importer` is the `app.vue` file).

Btw: what is the difference between `addTemplate` with `nuxt.alias` vs `nitro.virtual`? I guess the later is only for server-side virtual modules, but are there other differences? When should one use which option?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
Looking at this, I'm pretty sure this would need to be a Nitro change, as Nitro templates are not related to Nuxt templates and adding a virtual file for use in Nitro should not be done with `addTemplate`, but with the new `addServerTemplate` util which modifies `nitro.options.virtual`.

If this is still relevant for you, would you be able to open an issue on https://github.com/nitrojs/nitro ? 🙏
