### ISSUE TITLE
treeshake module does not treeshake .client components

### ISSUE THREAD

**Issue by huang-julien** [nuxt/nuxt#15396]
### Environment

all

### Reproduction

https://stackblitz.com/edit/nuxt-starter-bgopmh?file=components%2FTest.client.vue,app.vue,components%2FBreakServer.ts

### Describe the bug

Currently treeshake module does not treeshake .client components due to https://github.com/nuxt/framework/pull/7412 .

**Comment by danielroe** [comment]
closed in https://github.com/nuxt/framework/pull/8789
