### ISSUE TITLE
Error 500 on Windows trying to resolve file paths with custom buildDir

### ISSUE THREAD

**Issue by indiehjaerta** [nuxt/nuxt#15421]
### Environment

Nuxt project info:                                                                                           

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `pnpm@7.13.4`
- Builder:          `vite`
- User Config:      `buildDir`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Use a Windows laptop use a non-standard buildDir
Install depdencies with pnpm and start the dev environment. 

### Describe the bug

Running `pnpm run dev` gives this output in the terminal

![image](https://user-images.githubusercontent.com/14825674/200852777-7630906a-fc93-49b9-80d7-ed57c707d8eb.png)

This is on a clean repo with only "nuxt": "^3.0.0-rc.13" in the package.json

### Additional context

Didn't create a Codesandbox or Stackblitz since I'm guessing they don't run Windows OS.

I checked the .nuxt output and some file output is missing the file:// but this is the same with the standard or any other buildDir so I don't know if this could be causing this bug. I don't know if I can get a better stacktrace for more information.

**Comment by danielroe** [comment]
This is no longer reproducible for me.
