### ISSUE TITLE
`throw createError` does not show error page on client-side (in development)

### ISSUE THREAD

**Issue by nhatimme** [nuxt/nuxt#15432]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `yarn@1.22.10`
- Builder:          `vite`
- User Config:      `build`, `modules`, `loadingIndicator`, `app`, `css`
- Runtime Modules:  `nuxt-windicss@2.5.2`, `@pinia/nuxt@0.4.3`
- Build Modules:    `-`

### Reproduction

When I enter a page directly via the browser e.g: 192.168.1.1/test (it shows me an 404 page error, which is fine). But when I navigate to an existing page (which loads normally) and then click on a button with a internal link like: 192.168.1.1/hello it provides an error. It is unable to create an error.

https://stackblitz.com/edit/github-dk8jtl?file=app.vue

Click on the two buttons named "Team" and "Contact". Everything working fine. Click then on "Error" button. Please check console for the error message which I provided.

### Describe the bug

Uncaught (in promise) Error: Page Not Found
    at createError (index.mjs?v=f2c40dfc:35:15)

`const err = new H3Error(input.message ?? input.statusMessage, input.cause ? { cause: input.cause } : void 0);`

### Additional context

I generate the error with the following line; `throw createError({ statusCode: 404, statusMessage: 'Page Not Found' })`

**Comment by un1t** [comment]
> if (error.value) {
>   // This will trigger an error page server side
>   throw createError({ message: 'Page not found', statusCode: 404 })
> }
> ```

I noticed that you using **message** instead of **statusMessage** and it really works:

`throw createError({ message: 'Page not found', statusCode: 404 })`

But in the documentation there is an example with **statusMessage**. Is the documentation outdated? Not sure what is the difference and when should I use **message** and when **statusMessage**. Could not find it in documentation.

**Comment by frasza** [comment]
@danielroe Same problem on my side.

**Comment by hkiame** [comment]
I had the same issue but when I restarted the server it fixed the issue.

**Comment by kaname-png** [comment]
I had the same problem, restarting the server solved it.

**Comment by martinsjek** [comment]
I have an issue in version 3.2.3 where it does show 404 page when using this code:
`throw createError({ statusCode: 404, fatal: true })`, but the actual server response status code is 200 not 404.
What might be the issue?

**Comment by iotronlab** [comment]
Hello, kindly let us know about any planned update on this bug? It's not possible to show error page on client side as the fatal: true parameter doesn't work as mentioned in the docs. The only workaround is to make a custom error component and display it in case of error from useFetch()
https://nuxt.com/docs/getting-started/error-handling#createerror

**Comment by danielroe** [comment]
Just to be clear, this issue exists to track a problem in dev mode but not in production. Example: https://stackblitz.com/edit/nuxt-starter-eecxbg.

If you are experiencing something in production, please let me know with a minimal reproduction.

**Comment by mbadr2200** [comment]
when i use `statusMessage` the error passed to the client-side in error in useFetch but when I use the message the error not sent in the error in useFetch

**Comment by Austio** [comment]
@danielroe https://github.com/nuxt/nuxt/issues/15432#issuecomment-1490336678

Not happening in production but this behavior will cause some weird inconsistencies between development, staging and production where devs will think they have a broken page but things will actually work.

What is the best path to return a status code similar to how one would handle this in express or connect for status codes like 403 and 500?

**Comment by danielroe** [comment]
@Austio We closed this when the difference in development was removed. If you are still encountering a difference, please do open a new issue with a reproduction.

**Comment by Austio** [comment]
@danielroe I see that it was closed but the behavior between development and not development is something that at least to me is unexpected and seems more like a bug or design issue based on the discussion above where it is not expected by others.

How do we handle ensuring that we render the same pages in development and production?

The flow as an example
 - Authentication library that throws a 403 forbidden error
 - Wrapping middleware throws the exception in a way that will should in the new nuxt3 system

I've tried this with and without fatal: true

```
  throw createError({statusCode: e.statusCode, fatal: true})
```

**Comment by vejja** [comment]
@danielroe The issue only appears in *async/await functions*
- if you `throw createError({fatal: true})` from a regular function of the `<script setup>` script, it works fine and the `error.vue` component is displayed
- if you `throw createError({fatal: true)` from an **async function** of the `<script setup>` script, it does not work. The `error.vue` component is not displayed, and instead the console displays a message of `Uncaught (in promise) Error`. 

The initial bug report at the top of this issue correctly reported that the debugger points to the line where an H3Error object is being created by the createError function.
This was also hinted in https://github.com/nuxt/nuxt/issues/15754

**Comment by danielroe** [comment]
@vejja would you give me an example of what you mean?

**Comment by vejja** [comment]
Sure
Here is a simple script block that would fail.
The `login` async function is being invoked on clicking a button in the Vue template

```js
definePageMeta({ layout: 'centered' })
const email = ref(null)
const password = ref(null)

async function login() {
  const supabase = useSupabaseClient()
  const { error } = await supabase.auth.signInWithPassword({
    email: email.value,
    password: password.value
  })
  if (error) {
    throw createError(error)
  } else {
    navigateTo('/')
  }
}
```

In that case, clicking on the Login button with invalid credentials should throw an error and display the `error.vue` component, which it fails to do.

Instead, the page stays stuck with nothing happening, and the console shows the following output:
![Capture d’écran 2023-09-12 à 17 44 43](https://github.com/nuxt/nuxt/assets/7295259/5993e1a1-88c3-4b53-afb8-80d8873572c2)

Clicking on the index.mjs debugger link brings up the following tab:
![Capture d’écran 2023-09-12 à 17 53 55](https://github.com/nuxt/nuxt/assets/7295259/1ff69142-f392-4306-ac8d-cd97dedd9706)

**Comment by danielroe** [comment]
Okay, I see you're throwing that error in a function. That's not going to trigger a nuxt error page. Instead you would use `showError` in that context.

**Comment by vejja** [comment]
Ok and thanks for the explanation
As a side note though, the docs (https://nuxt.com/docs/getting-started/error-handling#createerror) clearly recommend to use `throw createError` on the client side and advise to avoid `showError`
Not clear why they say that

**Comment by danielroe** [comment]
The issue is possibly related to when you are calling the function and throwing the error, right?

I can't see your whole code but basically if you throw an error and it doesn't get captured by the normal vue error handler, Nuxt has no way to know about that error.

**Comment by crunchwrap89** [comment]
I got the same issue in nuxt 3.7.1 but, i've never made it work really. 
Same issue in production and dev environment for me:

this does not work:
```js
throw createError({ fatal: true, statusCode: 101, statusMessage: 'my custom error message' });
```

this works:
```js
          showError({
            fatal: true,
            statusCode: 101,
            statusMessage: `my custom error message`,
          });
```

**Comment by lupus78** [comment]
Please update documentation, because this is very confusing

**Comment by lmiller1990** [comment]
> I got the same issue in nuxt 3.7.1 but, i've never made it work really. Same issue in production and dev environment for me:
> 
> this does not work:
> 
> ```js
> throw createError({ fatal: true, statusCode: 101, statusMessage: 'my custom error message' });
> ```
> 
> this works:
> 
> ```js
>           showError({
>             fatal: true,
>             statusCode: 101,
>             statusMessage: `my custom error message`,
>           });
> ```

This worked for me, too - `showError` and `statusMessage` combo. I could not get `createError` to work on the client or server. I am not using the production build, just development.

**Comment by quroom** [comment]
To be clarify, as I tested in my dev env, showError works in client side.
And creatError works in serverside ssr.
So I check whether code is run in client or server like example.
```
      if (process.client) {
        throw showError({
          fatal: true,
          statusMessage: JSON.stringify(response),
          statusCode: response.status,
        });
      } else {
        throw createError({
          statusMessage: JSON.stringify(response),
          statusCode: response.status,
        });
      }
```

**Comment by sanba-anass** [comment]
fatal:true is working fine now on version  3.7.1 of nuxt !

**Comment by hecktarzuli** [comment]
using throw `createError` even using `fatal: true` inside useAsyncData in Nuxt 3.8.0 is still a problem.

**Comment by danielroe** [comment]
useAsyncData will never throw an error. You need to handle the contents of `error.value`.

**Comment by MooseSaeed** [comment]
Error page stopped working for me too

**Comment by danielroe** [comment]
If you are experiencing an issue, please do open an issue with a reproduction 🙏

**Comment by rockfang** [comment]
> If you are experiencing an issue, please do open an issue with a reproduction 🙏

hope to take a look at my issue https://github.com/nuxt/nuxt/issues/24601
and the reproduction https://stackblitz.com/edit/nuxt-starter-kpbeu1?file=app.vue

**Comment by tomsqueiroz** [comment]
Hi, I am facing a similar issue. When the error.vue is shown, instead of replacing the index page, I am getting the error.vue rendered **below** the indexPage. This way instead of having a fullscreen error Page I still have the index Page displayed together with the error Page.

**Comment by ituyakpaev** [comment]
``For my case the problem was in the `lazy=true` setting. I use it as I wanted to use preloader inside the page component for case when user goes to the page without reloading the page.

So i use `throw createErrror` after awaiting for `useAsyncData`. But when it's lazy, status may be `idle` after awaiting. The problem was solved when i add extra watcher on status which was returned from `useAsyncData` and throw error when it's changed to 'error' status.

And to resolve it, I've created composable:
```
import type {AsyncDataRequestStatus, NuxtError} from "#app";
import type {Ref} from "vue";

export function useErrorWatcher(status: Ref<AsyncDataRequestStatus>, error: Ref<NuxtError<unknown> | null>) {
    if (status.value === 'error') {
        throw createError({
            statusCode: error.value?.statusCode || 500,
            message: error.value?.message || 'Internal server error',
            fatal: true
        })
    } else {
        watch(
            status,
            () => {
                throw createError({
                    statusCode: error.value?.statusCode || 500,
                    message: error.value?.message || 'Internal server error',
                    fatal: true
                })
            }
        )
    }
}
```

**Comment by Tofandel** [comment]
There still seems to be a small disparity between dev and prod, here is an example of a code that shows the error on dev but not on prod

```js
const { data, error } = await useFetch('/api/blabla');
watchEffect(() => {
  if (error.value) {
     throw createError({ fatal: true, statusCode: 404 });
  }
});
```

It seems this is a problem when the throw is coming from inside watchEffect on the server

Converting to this

```js
const { data, error } = await useFetch('/api/blabla');
if (error.value) {
   throw createError({ fatal: true, statusCode: 404 });
}
watch(error, () => {
  if (error.value) {
     throw createError({ fatal: true, statusCode: 404 });
  }
});
```

Fixes the issue

**Comment by simonmaass** [comment]
I am also a bit confused on how to throw an error and redirect to 404 page... for example here on a prismic doc page this will not work right?:
https://prismic.io/docs/nuxt-3-template-content#rendering-the-slice-zone
