### ISSUE TITLE
Undefined route in Nuxt layout component in prod build

### ISSUE THREAD

**Issue by misaon** [nuxt/nuxt#15434]
### Environment

```
- Operating System: `Linux`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `pnpm@7.15.0`
- Builder:          `vite`
- User Config:      `modules`, `oxyshopNuxt`, `i18n`, `experimental`
- Runtime Modules:  `normalizedModule()`, `normalizedModule()`
- Build Modules:    `-`
```

### Reproduction

Build to prod

### Describe the bug

In the dev environment everything works fine, once the application build to production. on the client side Nuxt RC-13 crashes on the error that the route is undefined.
https://github.com/nuxt/framework/blob/59d8c51b5bd8d8f7de66f83494d9d39110e43c44/packages/nuxt/src/app/components/layout.ts#L73
On Nuxt RC-12 it works fine.

### Additional context

![image](https://user-images.githubusercontent.com/15806356/201121574-38366738-1d2d-4889-ae41-2a534cf3afb2.png)

### Logs

```shell
TypeError: Cannot read properties of undefined (reading 'meta')
    at zc.fn (entry.6b774f36.js:78:63198)
    at zc.run (entry.6b774f36.js:1:4282)
    at get value [as value] (entry.6b774f36.js:1:12410)
    at Proxy.<anonymous> (entry.6b774f36.js:78:63258)
    at fl (entry.6b774f36.js:1:15833)
    at St (entry.6b774f36.js:1:49906)
    at zc.V [as fn] (entry.6b774f36.js:1:49994)
    at zc.run (entry.6b774f36.js:1:4282)
    at G.T.update (entry.6b774f36.js:1:50299)
    at G (entry.6b774f36.js:1:50325)
nE @ entry.6b774f36.js:1
```

**Comment by victorgarciaesgi** [comment]
Hello! I'm still having the error on e2e tests fixtures. Strange thing is on fixture run correctly while the other fails. Exactly like said before, the content appears then disappears with the error.
I'm using `@nuxt/test-utils`
Repo here: https://github.com/victorgarciaesgi/nuxt-typed-router/tree/v2.1.3
Steps:
- Go to `test/e2e/complex.spec.ts` and decomment all comments
- Run pnpm run test

Tried `auto-install-peers=true` as @littlejon85 said but no luck

**Comment by victorgarciaesgi** [comment]
Also worth noting that I had the same problem with docs/docus, and fixed the problem by switching to yarn. But here even switching to yarn/npm didn't fixed the issue

**Comment by misaon** [comment]
@danielroe I finally managed to create a reproduction of this infernal bug! https://stackblitz.com/edit/github-ecbwau?file=package.json

**Comment by danielroe** [comment]
The issue seems to be that `@gtm-support/vue-gtm` is pulling in a separate copy of `vue-router`.

For now you can workaround with:

```ts
// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  vite: {
    resolve: {
      dedupe: ['vue-router']
    }
  }
})
```
