### ISSUE TITLE
Custom block for defining server side functions in components

### ISSUE THREAD

**Issue by KamilBartczak03** [nuxt/nuxt#15453]
### Describe the feature

I was thinking about an option to define SSR function inside SFC.

```vue
<script server lang="ts">
import someLogModule from 'somelogmodule'

onMounted(() => console.log('logging: connection established'))

export default {
   fetchSomeData(value: string) {
      return { some: value }
    }
 }
</script>

<script setup lang="ts">
const dataFromServer = ref(null)
const handleFetch(data: string) = > fetchSomeData(data)
</script>

<template>
{{ dataFromServer }}
<button @onclick="handleFetch">click me</buttom>
</template>
```

We could import and export these functions from other components or javascript files or even perform some server side operations on some component lifecycle hooks.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by florian-lefebvre** [comment]
May this issue be closed in favor of this community module? https://github.com/Hebilicious/server-block-nuxt

**Comment by KamilBartczak03** [comment]
@florian-lefebvre Yes, we can close it
