### ISSUE TITLE
How to use "extendRoutes" in nuxt3?

### ISSUE THREAD

**Issue by alterhu2020** [nuxt/nuxt#15469]
### Discussed in https://github.com/nuxt/framework/discussions/1523

<div type='discussions-op-text'>

<sup>Originally posted by **crotanite** October 27, 2021</sup>
nuxt 2 documentation for modules says there is an `extendRoutes` function, but this doesn't seem to be importable at all through nuxt3

Is it currently possible to use this in nuxt3?</div>

also tried this way: in `nuxt.config.ts` file
```
 hooks: {
        'pages:extend': (pages: NuxtPage[]) => {
            pages.push({
                redirect: (to) => {
                    
                }
            })
        }
    }

```
but the `redirect` property is only string type supported

**Comment by danielroe** [comment]
If you want to set a function, you can do that in `definePageMeta` within the page directly, or via `app/router.options.ts`.
