### ISSUE TITLE
Server imports missing file extension

### ISSUE THREAD

**Issue by brtinney** [nuxt/nuxt#15460]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `yarn@3.1.1`
- Builder:          `vite`
- User Config:      `app`, `css`, `build`, `modules`, `publicRuntimeConfig`, `nitro`
- Runtime Modules:  `@pinia/nuxt@0.4.3`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-wvuvnj?file=app.vue,server%2Froutes%2Froute.ts

### Describe the bug

As per reported in nuxt/nuxt.js#14597 (specifically, [my comment](https://github.com/nuxt/nuxt.js/issues/14597)), importing `pinia` on the server results in an improperly set path.

### Additional context

This only occurs when `build` is used, and does not occur in `dev`.

### Logs

```shell
[nuxt] [request error] [unhandled] [500] Cannot find module '/home/projects/nuxt-starter-wvuvnj/.output/server/node_modules/pinia/dist/pinia' imported from /home/projects/nuxt-starter-wvuvnj/.output/server/chunks/route.mjs
  at InternalError.get (https://nuxt-starter-wvuvnj.w-credentialless.staticblitz.com/blitz.bba8d0a5a025db74852964077975228459d6d20b.js:6:292488)  
  at H3Error.get (./server/node_modules/h3/dist/index.mjs:134:22)  
  at normalizeError (./server/chunks/nitro/node-server.mjs:381:24)  
  at Object.errorhandler [as onError] (./server/chunks/nitro/node-server.mjs:400:57)  
  at toNodeHandle (./server/node_modules/h3/dist/index.mjs:787:27)  
  at async ufetch (./server/node_modules/unenv/runtime/fetch/index.mjs:28:17)  
  at async $fetchRaw2 (./server/node_modules/ohmyfetch/dist/shared/ohmyfetch.d1948a88.mjs:161:20)  
  at async setup (./server/chunks/app/server.mjs:1609:94)
```

**Comment by danielroe** [comment]
This is no longer reproducible: https://stackblitz.com/edit/nuxt-starter-gbviad?file=server%2Froutes%2Froute.ts,package.json,nuxt.config.ts

However, please note that you should take great care not import files in your Vue app into your nitro server routes and I would not recommend creating a pinia store in a nitro route.

**Comment by brtinney** [comment]
In case anyone stumbles across this in the future (since I still have this issue with Nuxt 3.3.1), a more reliable solution that worked for me was:

```
nitro: {
    alias: {
      pinia: 'pinia/dist/pinia.mjs'
    }
}
```

**Comment by NisuSan** [comment]
> I am still stack on this issues I am using joi validator on the server. joi has dependencies like @hapi/hoek which doesn`t import well after build but works in dev. (yarn dev)
> 
> `import * as assert from @hapi/hoek/lib/assert`
> 
> nuxt version 3.0.0

Have you found the solution? I'm faced with this problem too.

**Comment by clopezpro** [comment]
> 
Yes in production mode not working Joi 
I use nuxt 3.7
![image](https://github.com/nuxt/nuxt/assets/27446663/aabd2cd2-9d0c-415c-a783-299d94ca35d8)

**Comment by clopezpro** [comment]
> > I am still stack on this issues I am using joi validator on the server. joi has dependencies like @hapi/hoek which doesn`t import well after build but works in dev. (yarn dev)
> > `import * as assert from @hapi/hoek/lib/assert`
> > nuxt version 3.0.0
> 
> Have you found the solution? I'm faced with this problem too.

I have solved it this way

```js
export default defineNuxtConfig({
  devtools: { enabled: true },

  build: {
    transpile: ['@hapi', '@sideway'],
  },
})
```
