### ISSUE TITLE
Nuxt breaks Vite plugins that need `rollupOptions.input` (e.g. Telefunc)

### ISSUE THREAD

**Issue by brillout** [nuxt/nuxt#15475]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.0.0`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `pnpm@7.9.5`
- Builder:          `vite`
- User Config:      `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

1. Clone https://github.com/brillout/nuxt-telefunc
2. `pnpm install`
3. `pnpm build`

Observe the error:

```
ERROR  [@brillout/vite-plugin-import-build:Telefunc] /home/romuuu/tmp/nuxt-telefunc/.nuxt/dist/server/
telefuncFilesGlob.mjs is missing: make sure your Rollup config doesn't change the name of the file
telefuncFilesGlob.mjs
```

This error occurs because Telefunc's `rollupOptions.input` entry is lost. It seems like Nuxt removes it.

### Describe the bug

@wobsoriano and myself are trying to use Nuxt with Telefunc, but Nuxt seem to remove the `rollupOptions.input` entries set by other Vite plugins (in this case Telefunc's Vite plugin).

There is no workaround on Telefunc's side since it needs to use `rollupOptions.input`.

### Additional context

AFAICT any Vite plugin that needs `rollupOptions.input` won't work with Nuxt. So I think it's quite a serious bug. I also don't see any possible workaround here.

**Comment by brillout** [comment]
The problem is that the entry cannot be found in `bundle`.

Telefunc adds a Rollup entry (i.e. `rollupOptions.input`) called `telefuncFilesGlob` but cannot find it in `bundle`. I suspect Nuxt is renming the entry name making it impossible for Telefunc to retetrieve it from `bundle`.

**Comment by JBustin** [comment]
Hello @danielroe, 

If I understand this thread, it is possible to add inputs in rollupOptions since the merge of #19842.
But I'm experimenting a bad behavior when I add a new entry:
```js
  hooks: {
    'vite:extendConfig'(config, { isServer }) {
      if (!isServer) return
      config.build.rollupOptions.input = {
        ...config.build.rollupOptions.input,
        appConfig: resolve(__dirname, '../cli/app-config/index.ts'),
      }
    },
  },
```
My built app is in 500
```
[nuxt] [request error] [unhandled] [500] [nuxt] instance unavailable
  at useNuxtApp (./.output/server/chunks/app/server.mjs:295:13)
```

```js
// @__NO_SIDE_EFFECTS__
function useNuxtApp() {
  {
    {
      throw new Error("[nuxt] instance unavailable");
    }
  }
}
```
My goal is just to build a script that uses some of the nuxt app sources.
Any idea ?

Regards
