### ISSUE TITLE
Malformed types in the API documentation parts 

### ISSUE THREAD

**Issue by SirMishaa** [nuxt/nuxt#15486]
![image](https://user-images.githubusercontent.com/42717232/202223488-c48cae53-6c76-437f-963b-5d9d3a5607dc.png)

There is some pages with missing ``:`` for types. 

- https://nuxt.com/docs/api/composables/use-async-data
- https://nuxt.com/docs/api/composables/use-fetch
- https://nuxt.com/docs/api/composables/use-head

**Comment by manniL** [comment]
Should be resolved by now 👍🏻
<img width="792" alt="image" src="https://github.com/nuxt/nuxt/assets/640208/d32600c5-cab9-4990-93a5-ab6900601d81">
