### ISSUE TITLE
New nuxt.com dark/light toggle defaults to light when system is dark

### ISSUE THREAD

**Issue by acidjazz** [nuxt/nuxt#15497]
### Environment

<img width="325" alt="image" src="https://user-images.githubusercontent.com/967369/202313850-1f0c1f76-cfea-4936-8209-67c88fe9c053.png">

### Reproduction

Sorry I couldnt find the repo to nuxt.com - feel free to move this issue

### Describe the bug

visit nuxt.com in dark mode as system, check the toggle, still set to light mode.

**Comment by manniL** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/15511 ☺️
