### ISSUE TITLE
Lodash plugin templates are no longer working after upgrade

### ISSUE THREAD

**Issue by connect2fayis** [nuxt/nuxt#15509]
### Environment

OS : macOS
NodeJS : 18 LTS
Nuxt : Nuxt 3.0.1 stable

### Reproduction

Just upgrade to latest nuxt3 and run yarn dev and you could see errors as shown in the screenshor

[https://prnt.sc/cpOW2Ebo1MxT](url) 

### Describe the bug

Hello, I've upgraded the nuxt to rc14 and then to the stable release and found my plugins that were added dynamically using addPlugin method from nuxt kit are no longer compiled. they do have lodash templates and on building vite reporting errors and could not compile them.

**Comment by danielroe** [comment]
`addPluginTemplate` is the way to go for lodash templates, yes.
