### ISSUE TITLE
Colorscheme of code blocks in light mode seems unclear

### ISSUE THREAD

**Issue by JiantingFeng** [nuxt/nuxt#15501]
Hi,

I noticed that the colorscheme of the code block in the documents of modules doesn't display well in light mode.

For example, in [@nuxt/tailwindcss](https://nuxt.com/modules/tailwindcss),

The color of the code is the same as the background, for example:

In light mode, I can't see any code but comments
![image](https://user-images.githubusercontent.com/36693163/202350160-9248ee20-db71-4fd7-b800-f841c42a071e.png)

However, in dark mode, it works well
![image](https://user-images.githubusercontent.com/36693163/202350514-ceacd236-3736-424b-b3fd-21230c4dc6a5.png)

The braces in the code block have a similar issue as well, 

In light mode, all the braces disappear:
![image](https://user-images.githubusercontent.com/36693163/202350728-6a8a2f9b-d98d-4d36-a686-969be8eb072c.png)

Compared with dark mode:
![image](https://user-images.githubusercontent.com/36693163/202350769-eedad53b-f2d8-420e-9c21-153ff06a381e.png)

**Comment by danielroe** [comment]
I believe this is now resolved.
