### ISSUE TITLE
Is there a way to type a fetch response picked?

### ISSUE THREAD

**Issue by BenWaNH** [nuxt/nuxt#15527]
Hi everyone!

First, thanks so much to the team for this great work! Congrats for this release!

I was asking me something about useFetch, if it's possible, working in typescript...
See below:

I've a test interface:
```javascript
interface test {
    prop1: string;
    prop2: string;
    prop3: string;
}
```

I've a test api endpoint: (server/api/test.ts)
```javascript
export default () => {
    return {
        prop1: 'PROP1',
        prop2: 'PROP2',
        prop3: 'PROP3',
    }
}
```

I'm fetching it:
```javascript
const { data } = await useFetch<test>('/api/test', {pick: ['prop1', 'prop3']})
```

So data is typed as Ref<test | null>, that's mean my autocompletion suggest prop2 is possible yet

I would like force response type with a second interface corresponding to my picked option (for a better completion! No way in my template to use a bad prop which was not picked)
```javascript
interface testPicked {
    prop1: string;
    prop3: string;
}
```

1st interface is a full model, picked values are keys of it, 2nd interface is my output for a better completion.
Is it possible to do something like this? In wich way?

Thanks
BenWa

**Comment by danielroe** [comment]
I can't reproduce this in VS Code:

![CleanShot 2023-04-14 at 22.52.07@2x.png](https://volta.s3.fr-par.scw.cloud/Clean_Shot_2023_04_14_at_22_52_07_2x_5b1fe40f48.png)

![CleanShot 2023-04-14 at 22.52.50@2x.png](https://volta.s3.fr-par.scw.cloud/Clean_Shot_2023_04_14_at_22_52_50_2x_e652e1a279.png)

It seems like this might be a WebStorm issue.

But yes, you can workaround by providing the return type (once picked) as the first generic of `useFetch`.
