### ISSUE TITLE
docs: markdown badly rendered

### ISSUE THREAD

**Issue by huang-julien** [nuxt/nuxt#15526]
### Environment

all 

### Reproduction

https://nuxt.com/docs/api/composables/use-fetch
https://nuxt.com/docs/api/composables/use-async-data

### Describe the bug

A lot of characters are not rendered in the code block for useFetch and useAsyncData type

### Additional context

 \o/ nuxt 3 finally released \o/ thank you for all your hard work ! \o/

**Comment by danielroe** [comment]
This is now resolved.
