### ISSUE TITLE
SWR routes do not follow time parameters (netlify)

### ISSUE THREAD

**Issue by cfab** [nuxt/nuxt#15549]
### Environment

RootDir: /Users/f/Downloads/nuxt-3-test                                                                                18:02:36
Nuxt project info: (copied to clipboard)                                                                               18:02:36

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `modules`, `nitro`, `routeRules`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/cfab/nuxt-3-test.git
https://cozy-palmier-4624d4.netlify.app

### Describe the bug

RouteRules with { swr: true } or { swr: 21600 } are indeed cached but regardless of parameters, and all revalidated after about a minute.
In the case of 21600 the cache should last about 6 hours but it is revalidated after 1 or 2 minutes. 
Same with smaller numbers like 10 for example.
Is this a syntax pbl of mine or a bug ?
Thank you !

**Comment by danielroe** [comment]
Netlify has a minimum TTL of 60 seconds. But it's not _guaranteed_ to take as long as you specify in the swr as it is (IIRC) per edge handler (ie. if you are routed to a different handler then the timer will reset). You'll probably be best off asking the Netlify team to confirm.
