### ISSUE TITLE
using private repository on extends, 404 Not Found

### ISSUE THREAD

**Issue by console0811** [nuxt/nuxt#15547]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.9.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `extends`, `modules`, `security`
- Runtime Modules:  `nuxt-security@0.8.0`
- Build Modules:    `-`

### Reproduction

Create nuxt app A and B, upload repository B as private repository on github. Use nuxt app B (private repo) link to extend nuxt app A.

### Describe the bug

 ERROR  Cannot start nuxt:  {                                                                                                      10:03:04
  code: 404,
  message: 'Not Found'
}

**Comment by danielroe** [comment]
Would you try setting the `GIGET_AUTH` environment variable?

https://nuxt.com/docs/guide/going-further/layers#git-repository
