### ISSUE TITLE
Generate concurrency and interval configuration

### ISSUE THREAD

**Issue by Siilwyn** [nuxt/nuxt#15543]
### Describe the feature

With Nuxt 2 we could prevent hitting rate limits while generating pages with a concurrency limit and interval configuration, would be great to have this available in Nuxt 3 too.

### Additional information

- [x] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by romain-trspt** [comment]
I am struggling with this issue, now when I generate my site I get 429 errors due to the rate limits on the server side. Using Interval and Concurrency options with Nuxt 2 was working fine. Would anybody has a workaround for Nuxt 3 ?
Thanks

**Comment by danielroe** [comment]
We've implemented this now upstream in Nitro. This should be resolved in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/), or in the next release.

Let me know if not and I'll reopen.

**Comment by arcataroger** [comment]
@danielroe , sorry to bring this back up, but could you please explain how to utilize these settings in Nuxt 3?

The v3 docs do not mention concurrency or interval: https://nuxt.com/docs/api/nuxt-config#generate

Unlike the v2 docs: https://v2.nuxt.com/docs/configuration-glossary/configuration-generate/#concurrency

It's also not clear whether the config is a Nitro setting (and how to access that in Nuxt): https://github.com/unjs/nitro/pull/1223#issuecomment-1689054473

**Comment by danielroe** [comment]
You are very welcome 😊
