### ISSUE TITLE
add kit utilities for augmenting app and runtime config

### ISSUE THREAD

**Issue by Vinccool96** [nuxt/nuxt#15553]
### Describe the feature

Right now, there's no way to get a module options defined in `nuxt.config.ts`.

The only way currently is to write `nuxt.config.ts` like this:

```ts
import { defineNuxtConfig } from "nuxt/config"
import MyModule from ".."

const config = {
  foo: "bar",
  toto: "tata",
}

export default defineNuxtConfig({
  modules: [MyModule ],
  moduleConfig: config,

  runtimeConfig: {
    public: {
      moduleConfig: config,
    },
  },
})
```

It is extremely redundant. And it's made even *worse* if `MyModule` has default properties, because they will not be put in the runtime config.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
We think it makes sense to expose utilities from kit to make it straightforward to augment app and runtime config. Plus, down the line, we have some nice improvements coming for app config: https://github.com/nuxt/nuxt/issues/14670 😊

**Comment by danielroe** [comment]
resolved in https://github.com/nuxt/nuxt/pull/27117
