### ISSUE TITLE
Unstyled when entering the page

### ISSUE THREAD

**Issue by ElYaiko** [nuxt/nuxt#15554]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.14`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.18.0`
- Builder:          `vite`
- User Config:      `css`, `build`, `vite`, `modules`, `runtimeConfig`
- Runtime Modules:  `@pinia/nuxt@0.4.1`, `()`
- Build Modules:    `-`

### Reproduction

When loading a SCSS style in a vite plugin via nuxt.config modules

Reproduction: https://stackblitz.com/edit/github-hqux23?file=nuxt.config.ts
You can see that when you remove the styles property in the vuetify() plugin it loads normally when entering the page.

### Describe the bug

Makes the site look unstyled for a moment when entering the page.

### Additional context

I'm using vuetify@next and vite-plugin-vuetify with this guide.
https://next.vuetifyjs.com/en/features/sass-variables/

Thanks.

**Comment by manniL** [comment]
The [vuetify docs](https://next.vuetifyjs.com/en/features/sass-variables/#basic-usage) say that you then should import your scss file and not the precompiled styles.

See my [fixed StackBlitz](https://stackblitz.com/edit/nuxtissues15554?file=nuxt.config.ts,app.vue) - only changes in the nuxt config.
