### ISSUE TITLE
Using custom in `***.tsx`.

### ISSUE THREAD

**Issue by 516310460** [nuxt/nuxt#15564]
### Environment

- Operating System: MacOS
- Node Version: v16.16.0
- Nuxt Version: 3.0.0
- Nitro Version: 1.0.0
- Package Manager: pnpm@7.13.6
- Builder: vite
- User Config: extends, build, nitro, vite
- Runtime Modules: -
- Build Modules: -

### Reproduction

[Error litelement Failed to execute 'define' on 'CustomElementRegistry'](https://stackblitz.com/edit/github-cr9hwc-cg3wk8?file=nuxt.config.ts,app.vue,package.json,components%2FTestApp.tsx)

### Describe the bug

When using custom components in `components/TestApp.tsx`, an error will be reported in `server`. but there is no problem when using custom components in `.vue`

Added `nuxt.config.ts`
```ts
build: {
        transpile: ['bg']
},
vue: {
    compilerOptions: {
            isCustomElement: (tag) => tag.includes('bg-')
    }
}
```

**Comment by danielroe** [comment]
Resolved in https://github.com/nuxt/nuxt/pull/19053.
