### ISSUE TITLE
overwrite layout component style no work 

### ISSUE THREAD

**Issue by YIngChenIt** [nuxt/nuxt#15572]
### Environment

Nuxt Version: 3.0.0

### Reproduction

https://stackblitz.com/edit/github-hcvfnh?file=components/MainHeader.vue

### Describe the bug

i want to overwrite  <NuxtLayout name="header" /> style, but it is no work

``` 
<template>
  <NuxtLayout name="header" />
</template>

<style lang="scss" scoped>
.header {
  color: black;
}
</style>
``` 

![image](https://user-images.githubusercontent.com/53081460/203201450-db767a04-b2d2-473d-b61f-1ffc5a9be334.png)

**Comment by manniL** [comment]
This does not work because scoped styles only work for the root component of the direct child. In this case, there are multiple internal components in between:
<img width="387" alt="image" src="https://user-images.githubusercontent.com/640208/214314718-594a7746-b24c-4fb8-b86e-45106315ef81.png">
