### ISSUE TITLE
Fallback for when custom layout is missing

### ISSUE THREAD

**Issue by SebbeJohansson** [nuxt/nuxt#15570]
### Describe the feature

Hi. I have an application where the layout selected is based on a request to an API. Sometimes that API might request a layout that doesn't exist (yet or it wont ever exist) and I want to show an error page or a fallback. This doesn't seem to exist currently.

I have read most of the top results on google and I've read through any related issues on github that I could find.

![image](https://user-images.githubusercontent.com/5083273/203122549-3aa094b7-420b-4f5f-a9ab-6f5586e9f18e.png)

Ideally would be a config and/or a named layout you can create.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
We think this API would be a good idea, which would require opting-in:

```vue
<NuxtLayout fallback="default">
  <NuxtPage />
</NuxtLayout>
```

**Comment by SebbeJohansson** [comment]
@danielroe I think that makes a lot of sense. Thanks!
