### ISSUE TITLE
Use Nuxt component in vue app

### ISSUE THREAD

**Issue by maximepvrt** [nuxt/nuxt#15584]
### Describe the feature

Can you allow import nuxt component into a basic vue app

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by maximepvrt** [comment]
same as this old nuxt2 module https://nuxt-custom-elements.grabarzundpartner.dev/

**Comment by manniL** [comment]
IMO this should be part of a module and not part of the core.
