### ISSUE TITLE
Nested "useAsyncData" fails on SSR and works on the client

### ISSUE THREAD

**Issue by nemtsov** [nuxt/nuxt#15596]
### Environment

```
------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.21.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@6.14.17`
- Builder:          `vite`
- User Config:      `modules`, `apollo`, `app`, `css`
- Runtime Modules:  `@nuxtjs/apollo@5.0.0-alpha.4`
- Build Modules:    `-`
------------------------------
```

### Reproduction

`/pages/test.vue`
```vue
<template>
  <NuxtLink to="/testAsync">GO</NuxtLink>
</template>
```

`/pages/testAsync.vue`
```vue
<script setup lang="ts">
  import useTestAsync from '~~/composables/testAsync';
  const {data, error} = await useTestAsync();
</script>

<template>
  <div>DATA: "{{ data }}"</div>
  <div>ERR: "{{ error }}"</div>
</template>
```

`/composables/testAsync.ts`
```ts
export default async function useTestAsync() {
  return useAsyncData(async () => {
    const {data: a} = await useAsyncData<number>('k1', async () => Math.random());
    const {data: b} = await useAsyncData<number>('k2', async () => Math.random());

    return ((a.value || -1) + (b.value || -1));
  });
}
```

1. Go to `/test`
2. Click on the "GO" link
3. Notice that the "DATA: <random>" is filled with a random num
4. Refresh the page (to render this page on the server)
5. Notice that the "DATA" is empty and the "ERROR" says, `"ERR: "Error: nuxt instance unavailable"`

### Describe the bug

The code above returns an error `Error: nuxt instance unavailable` on the server but works as expected on dynamic navigation to this page on the client.

**Comment by danielroe** [comment]
Let's track documentation improvements to this in https://github.com/nuxt/nuxt/issues/14723.
