### ISSUE TITLE
Date type remains after json serialization, causing problems in typescript strict mode

### ISSUE THREAD

**Issue by Gerbuuun** [nuxt/nuxt#15590]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@3.2.3`
- Builder:          `vite`
- User Config:      `app`, `modules`, `typescript`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.1.3`, `nuxt-icon@0.1.8`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-zk2q2e?file=app.vue

Although typechecks in stackblitz does not work for me (I'm a first time user)

### Describe the bug

When returning a `Date` from an api route, the `Date` becomes a `string` (because `json` does not support `Date`). However, the type is still `Date` when using `useFetch`. When using typescript in strict mode this discrepancy makes it unusable.

**Comment by manniL** [comment]
Let's track in https://github.com/unjs/nitro/issues/804

**Comment by Gerbuuun** [comment]
As a workaround, I wrap my return type with the following:
```Typescript
type MapDateToString<T> = T extends Date
  ? string
  : T extends Record<any, any>
  ? { [K in keyof T]: MapDateToString<T[K]> }
  : T;
```
