### ISSUE TITLE
Page not updating when SWR route times out on Netlify

### ISSUE THREAD

**Issue by DaZiYuan** [nuxt/nuxt#15598]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `routeRules`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/DaZiYuan/swr-test

### Describe the bug

I set the routing rules as below, it works in `yarn dev` and updates every 3 seconds. But when I deploy it on Netlify, it doesn't update the cache.

```
export default defineNuxtConfig({
    routeRules: {
        "/**": { swr: 3 },
    },
})
```

### Additional context

https://harmonious-panda-fc384b.netlify.app/
![image](https://user-images.githubusercontent.com/80653/209332863-c8805e82-15d8-40c3-be9f-d79351146f75.png)

**Comment by danielroe** [comment]
Netlify SWR TTL has a minimum length of 60 seconds: https://docs.netlify.com/configure-builds/on-demand-builders/#time-to-live-ttl.

A PR to improve the docs at https://github.com/unjs/nitro would be welcome.
