### ISSUE TITLE
Hard to animating elements in dev mode

### ISSUE THREAD

**Issue by ivodolenc** [nuxt/nuxt#15602]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@9.1.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://nuxt.com/docs/getting-started/installation#new-project

1. Create nuxt default app.

2. Install `gsap`, `animejs` or any other animation lib

3. Start animating!

### Current behavior

When we want to animate elements via javascript in dev mode, live reloading is not responsive as it should be so it's really annoying that we need to explicitly refresh page to restart animations.

Simple example:

```html
<template>
  <div>
    <h1 class="title">Title</h1>
  </div>
</template>

<script setup lang="ts">
  import { onMounted } from 'vue'
  import { gsap } from 'gsap'

  onMounted(() => {
    gsap.fromTo(
      '.title',
      { transform: 'translateY(0%)' },
      { transform: 'translateY(200%)', color: 'blue' }
    )
  })
</script>
```

This works fine, but as soon as we start adding new animations or manipulating the content, the live reload doesn't automatically respond.

For example, when the animation ends, element stays in that place even if we made new changes in the template and saved the file.

Animations reruns only if we explicitly restart browser.

### Expected behavior

After we make new changes in the template and save the files, the live reload should automatically refresh and rerun all animations from the beginning.

**Comment by manniL** [comment]
Can't repro this anymore!
https://github.com/nuxt/nuxt/assets/640208/5c249714-64f0-4e87-ba1f-fa82cd54a938
