### ISSUE TITLE
Error when starting a Project using "http-proxy-middleware" with "npm run start"

### ISSUE THREAD

**Issue by marekachilles** [nuxt/nuxt#15608]
### Versions

- nuxt: v3.0.0 
- node: v18.12.1

### Reproduction

<details open>
<summary>Error occuring  when starting a Project using "http-proxy-middleware" to implement a proxy and Websockets with "npm run start". We are using the “http-proxy-middleware 3.0.0-beta.0”. In the attached Repository you will find a small Project which is not working with "npm run start" but with "npm run dev". The Error seems to occur in “Bug_Reproduction-\.output\server\chunks\node-server.mjs” in Line 688. </summary>
<br>
</details>

### Steps to reproduce
When you have downloaded the Repository: 
Run "npm install"
Run "npm run build"
Run "npm run start"

### What is Expected?
Project is building normaly without Errors using "npm run build". "npm run start" launches the localhost. On "http://localhost:3000" a page shows up saying "Hello World"

### What is actually happening?
Project is building normaly without Errors using "npm run build". When using "npm run start" the following Error shows up in the Terminal: 

const debug$5 = debug_1$6.Debug.extend("debug-proxy-errors-plugin");
                                ^
TypeError: debug_1$6.Debug.extend is not a function
    at file:///C:/Users/xxx/Repo/Bug_Reproduction-/.output/server/chunks/node-server.mjs:688:33
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)

Node.js v18.12.1

**Comment by oemer-sellwerk** [comment]
Is there any alternative or workaround to get this working in the meantime while the module is supporting to ESM?

**Comment by oemer-sellwerk** [comment]
I could make my build go through with a temporary workaround:
1. `yarn patch http-prox-middleware`
2. Follow what's stated in the console
3. change `dist/debug.js` according to this patch diff:
```diff
diff --git a/dist/debug.js b/dist/debug.js
index 31f4e4bf1b81f0914d29e8ef839eab9dfd9d3fb9..862daf8e7446f23b965bd6d3ce22a3fcfc4ed205 100644
--- a/dist/debug.js
+++ b/dist/debug.js
@@ -5,4 +5,4 @@ const createDebug = require("debug");
 /**
  * Debug instance with the given namespace: http-proxy-middleware
  */
-exports.Debug = createDebug('http-proxy-middleware');
+exports.Debug = Object.assign(createDebug('http-proxy-middleware'), {extend: ()=>{return ()=> {}}});
```
4. commit the patch (see console for the command from 1.)
5. run `yarn install` again
6. `yarn build` then `yarn start`
=> No errors anymore. 

Afaik, this shouldn't break anything since the debug module only affects logging.

**Comment by danielroe** [comment]
Thanks for the pointer @oemer-sellwerk. I've raised a PR to fix upstream in `unenv`: https://github.com/unjs/unenv/pull/69.

**Comment by yisibell** [comment]
you can try this proxy module https://github.com/yisibell/nuxt-proxy-request

**Comment by yisibell** [comment]
> 

Here's an alternative， https://github.com/yisibell/nuxt-proxy-request
Works well in both production and development environments.

**Comment by yisibell** [comment]
> Is there any alternative or workaround to get this working in the meantime while the module is migrating to ESM? How to add proxies in nuxt 3 for dev + production?
> 
> This seems to be the only thing left that is blocking me from migrating to nuxt-bridge.

Here's an alternative， https://github.com/yisibell/nuxt-proxy-request
Works well in both production and development environments.

**Comment by fikrihanda** [comment]
i still got error this when i use type "module" when running preview

```
file:///D:/projects/walipay/.output/server/chunks/nitro/node-server.mjs:2631
const debug$5 = debug_1$6.Debug.extend('debug-proxy-errors-plugin');
                                ^

TypeError: debug_1$6.Debug.extend is not a function
    at file:///D:/projects/walipay/.output/server/chunks/nitro/node-server.mjs:2631:33
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async ESMLoader.import (node:internal/modules/esm/loader:541:24)
    at async loadESM (node:internal/process/esm_loader:83:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
```

**Comment by TimGuendel** [comment]
I am still having this problem in production mode 🤔

`yarn build`

`node .output/server/index.mjs`

(Node.js v18.17.1, "http-proxy-middleware": "^3.0.0-beta.1", "nuxt": "^3.7.2")

**Comment by marekachilles** [comment]
> This should be resolved in the latest `unenv` release. You can update your dependencies with `npx nuxi upgrade --force`. Let me know if not and I'll happily reopen.

I unfortunatly, still got the same problem when using "npm run start".

**Comment by Akgurban** [comment]
mee too

**Comment by manniL** [comment]
This issue was closed a year ago. Please consider opening a [new issue](https://github.com/nuxt/nuxt/issues/new/choose) instead of leaving a comment here. @Akgurban

**Comment by Akgurban** [comment]
> This issue was closed a year ago. Please consider opening a [new issue](https://github.com/nuxt/nuxt/issues/new/choose) instead of leaving a comment here. @Akgurban
thanks but it is only not works on windows
