### ISSUE TITLE
Page duplication in latest nuxt build with docker

### ISSUE THREAD

**Issue by NADESHIKON** [nuxt/nuxt#15609]
### Environment

Docker

### Reproduction

Clone https://github.com/Enime-Project/enime.moe.git
Run ``pnpm run docker:build``
Run the container

### Describe the bug

The pages are rerendered twice in SSR mode in docker only.

### Additional context

https://enime.moe/

**Comment by billyovo** [comment]
still a problem on the latest release 3.2.2

**Comment by billyovo** [comment]
seems to only affect pages using a layout when first enter a site. If initial enter page is a page without layout (index page for me), subsequent navigations are normal with no duplication.
