### ISSUE TITLE
create a simple breadcrumb composable utility for core nuxt 

### ISSUE THREAD

**Issue by cpreston321** [nuxt/nuxt#15617]
### Describe the feature

# Feature
There has never been an elegant way to to get breadcrumbs without creating custom code. It would be nice to see a simple utility that creates basic breadcrumbs that has the title from meta title information, if not fallbacks to name of route. Maybe this sounds silly but it would nice to have it baked in so then we use it on our projects.

## Ideas

- Use meta title as main source of truth, as this can be added and customized using `useHead()` which everyone uses. 
- Make the first item in array the `index` *(Home) then next route, next route etc. 

For dynamic routes it might be a little more tricky but I am open to ideas. 

```ts
interface Breadcrumb {
   title: string
   path: string
}[]
```

```ts
const breadcrumbs = useRouteBreadcrumbs()
```

Name space can be modified to liking but would like to see a utility built in the core of nuxt vs creating a utilty every project. 

Ideas are welcome!

Thanks 💚

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by harlan-zw** [comment]
I think this is something that can and should be solved in module land.

There are certain limitations to it as well which make it unsuitable for a core framework feature:
- needs to use route meta for the data which is not the convention (you can't use useHead without pre-fetching the other pages)
- it doesn't work on dynamic routes

The module [Nuxt SEO Kit](https://github.com/harlan-zw/nuxt-seo-kit) ships with these automated Breadcrumbs. It also publishes the Schema.org needed for them. I'll be revamping the API on it soon but is works.

Going to close this off
