### ISSUE TITLE
Document successor of preview mode

### ISSUE THREAD

**Issue by pascalwengerter** [nuxt/nuxt#15639]
### Describe the feature

I've not managed to find an equivalent for https://nuxtjs.org/docs/features/live-preview/ in the Nuxt3 codebase and am wondering if there's similar functionality/plans to add them/a successor (potentially in a module)?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by SebbeJohansson** [comment]
@danielroe could we get something more convenient to use than the suggestions in @JonathanDoelan's link? For example https://github.com/nuxt/nuxt/discussions/18407#discussioncomment-5997866 seems pretty complicated for "end-users". Im thinking that this could be something that we could use in `useAsyncStoryblok` to automatically fetch new data when in preview for https://github.com/storyblok/storyblok-nuxt.

**Comment by algora-pbc** [comment]
💎 **$500** bounty created by @drewbaker
👉 To claim this bounty, [submit your pull request on Algora](https://console.algora.io/bounties/cliqbypki001emo0fj3bxwd4j)
📝 Before proceeding, please make sure you can [**receive payouts**](https://docs.algora.io/bounties/payments#country-support) in your country
💵 Payment arrives in your account 2-5 days after the bounty is rewarded
💯 You keep 100% of the bounty award
🙏 Thank you for contributing to nuxt/nuxt!

**Comment by drewbaker** [comment]
> 💎 **$500** bounty created by @drewbaker
> 👉 To claim this bounty, [submit your pull request on Algora](https://console.algora.io/bounties/cliqbypki001emo0fj3bxwd4j)
> 📝 Before proceeding, please make sure you can [**receive payouts**](https://docs.algora.io/bounties/payments#country-support) in your country
> 💵 Payment arrives in your account 2-5 days after the bounty is rewarded
> 💯 You keep 100% of the bounty award
> 🙏 Thank you for contributing to nuxt/nuxt!

Obviously this is for the actual successor to enablePreview() and documentation, not just documentation of the above interim solutions.

**Comment by SebbeJohansson** [comment]
@jwgatt did you link the wrong thing? That just links to this issue :)

**Comment by jwgatt** [comment]
> @jwgatt did you link the wrong thing? That just links to this issue :)

Isn't that how we declare that we are working on an issue with a bounty?

**Comment by jwgatt** [comment]
Is it best to ask questions and get requirements here, or in the Discord channel?

**Comment by jwgatt** [comment]
So we want the same functionality as the enablePreview() method in Nuxt 2;
- Token-based preview
- Updating the URL
- Rendering preview content
- Disabling preview mode

Anymore that i've missed?

**Comment by drewbaker** [comment]
> Updating the URL

What do you mean by that?

If you are curious, this is how we use the Nuxt2 `enablePreview()`:
https://github.com/funkhaus/fuxt/blob/master/plugins/preview.client.js

**Comment by jwgatt** [comment]
Apologies I meant 'Generate preview URL'.
Thanks for the link.

**Comment by formfcw** [comment]
If anyone needs a working solution right away, for me [this approach](https://github.com/nuxt/nuxt/discussions/18407#discussioncomment-5997866) works well.

**Comment by HawtinZeng** [comment]
hi, @drewbaker, I think @logotip4ik's work (https://github.com/nuxt/nuxt/pull/21705) is great, it worth $500 bounty.

**Comment by drewbaker** [comment]
> hi, @drewbaker, I think @logotip4ik's work (#21705) is great, it worth $500 bounty.

Yeah I'm still waiting on this to be merged, it seems really solid!

**Comment by drewbaker** [comment]
@logotip4ik I paid this today, thanks so much!

![Screenshot 2024-03-08 at 5 22 49 PM](https://github.com/nuxt/nuxt/assets/475015/518961a2-0183-41b9-854c-86b62069a4c8)

**Comment by logotip4ik** [comment]
Huge thanks @drewbaker !
