### ISSUE TITLE
New pages 404 unless server is restarted

### ISSUE THREAD

**Issue by mohasi** [nuxt/nuxt#15651]
### Environment

------------------------------
- Operating System: `Windows_NT` (Windows 10 latest update)
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `telemetry`, `modules`, `css`, `hooks`, `vite`
- Runtime Modules:  `nuxt-icon@0.1.8`
- Build Modules:    `-`
------------------------------

```
export default defineNuxtConfig({
  telemetry: false,
  modules: [
    'nuxt-icon'
  ],
  css: [
    'bulma',
  ],
  hooks: {
    'builder:watch': console.log
  },
  vite: {
    server: {
      watch: {
        usePolling: true
      }
    }
  }
})
```
```
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "nuxt": "3.0.0",
    "nuxt-icon": "^0.1.8",
    "sass": "^1.57.0",
    "sass-loader": "10"
  },
  "dependencies": {
    "bulma": "^0.9.4"
  }
}
```

### Reproduction

1. Have this in `app.vue` : `<template><NuxtPage /></template>` do not make a "pages" directory yet
3. Start server using `yarn dev -o`
4. Add pages/hello.vue with `<template>Hello world!</template>` -- this will work
5. Now add pages/test.vue with `<template>Test</template>` -- this will 404

Demo:
![nuxt issue2](https://user-images.githubusercontent.com/47725053/208981353-bcbac8a9-f7dc-4d1a-800c-c1f12ce42248.gif)

### Describe the bug

New pages require server start, otherwise you get a 404. It breaks the whole point of HMR and productivity. Such a critical issue has been raised (and closed) at least 5 times, over a year without lasting fix. 

https://github.com/nuxt/nuxt.js/issues/13307 (raised Jan 26!)
https://github.com/nuxt/nuxt.js/issues/13725
https://github.com/nuxt/nuxt.js/issues/13791
https://github.com/nuxt/nuxt.js/issues/15045
https://github.com/nuxt/nuxt.js/issues/15141

Having to stop and start the server takes up to 30 seconds (avg. 20s+) for me on an almost empty project. Please fix.

**Comment by bastianhilton** [comment]
I'm having this issue as well on Nuxt 3.0.0. Every time i add a new page I get the 404 error page saying a page doesn't exist. Only way to resolve it is through restarting the server.
