### ISSUE TITLE
`useHeadSafe` composable to sanitise head metadata

### ISSUE THREAD

**Issue by belomx** [nuxt/nuxt#15668]
### Environment

https://codesandbox.io/s/new-haze-rmtleo?file=/app.vue

### Reproduction

Open the page and the alert will pop-up.

### Describe the bug

The useHead can be used for XSS Attack.
In my application, the user's inputs are part of the 'application/ld+json' script for SEO purposes. And a users can insert a malicious script.

### Additional context

Good to notice, the xss attack will work only if the script passed as a prop to a component.

**Comment by danielroe** [comment]
This is now implemented.
