### ISSUE TITLE
Add a 'from' property to the route object

### ISSUE THREAD

**Issue by nathanchase** [nuxt/nuxt#15661]
### Describe the feature

I'd like to see a `from` property available on the Nuxt route object provided at: https://github.com/nuxt/framework/blob/3839dba06a3680936e90619dfdb27580230a6f69/packages/nuxt/src/app/plugins/router.ts#L9

```
interface Route {
  /** Percentage encoded pathname section of the URL. */
  path: string
  /** The whole location including the `search` and `hash`. */
  fullPath: string
  /** The previous location. */
  from: string  // <-- this is the new value I'd like to see
  /** Object representation of the `search` property of the current location. */
  query: Record<string, any>
  /** Hash of the current location. If present, starts with a `#`. */
  hash: string
  /** Name of the matched record */
  name: string | null | undefined
  /** Object of decoded params extracted from the `path`. */
  params: Record<string, any>
  /**
   * The location we were initially trying to access before ending up
   * on the current location.
   */
  redirectedFrom: Route | undefined
  /** Merged `meta` properties from all of the matched route records. */
  meta: Record<string, any>
}
```

This would be the value of **where the router was previously** - the same value you'd get from the `from` inside `addRouteMiddleware`.

Note: this is different from `redirectedFrom`, as that is for when there was a redirect. I simply want the router's most recent history of which route the app was previously on before the route it's currently on.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
I think this would be a good upstream feature request for https://github.com/vuejs/router directly - would you consider raising it there? If implemented there we can add the same property to the universal route you've linked in the code.

**Comment by manniL** [comment]
As [mentioned by Eduardo](https://github.com/vuejs/router/discussions/1791#discussioncomment-5571098), this can be done via router guards in userland. 

> So the question would be if there are enough common use cases for this to be a default feature in router

Same question would apply to Nuxt ☺️

**Comment by danielroe** [comment]
I think given the length of time this has been open, and there's a straightforward workaround provided by Eduardo, we can close this.

Feel free to reply if that changes. 🙏
