### ISSUE TITLE
$fetch and useFetch SSR error with proxy request

### ISSUE THREAD

**Issue by palaxius** [nuxt/nuxt#15679]
### Environment

```
- Operating System: `Windows_NT`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@3.2.4`
- Builder:          `vite`
- User Config:      `ssr`, `app`, `telemetry`, `build`, `modules`, `experimental`, `components`, `vueuse`, `runtimeConfig`, `vite`, `nitro`
- Runtime Modules:  `@vueuse/nuxt@9.6.0`, `@pinia/nuxt@0.4.6`
- Build Modules:    `-`
```

### Reproduction

https://stackblitz.com/edit/github-8lgefy-kdefyk?file=app.vue,nuxt.config.ts

### Describe the bug

When I try to send an ssr proxy request to the backend when using $fetch, I get an `Error: Invalid URL () at async setup`. When I use useFetch the request is also not executed and ignored. Everything works fine on the client side

### Additional context

app.vue:
```
<script setup>
const fetchResponse = ref(null);

// Working as intended with full url
// fetchResponse.value = await $fetch('https://dog.ceo/api/breeds/image/random');

// Working only on client side with proxy url (check nuxt.config.ts)
  fetchResponse.value = await $fetch('test/breeds/image/random');
</script>
```

nuxt.config.ts:
```
export default defineNuxtConfig({
  ssr: true,
  nitro: {
    devProxy: {
      '/test': {
        target: 'https://dog.ceo/api',
        changeOrigin: true,
        cookieDomainRewrite: '',
        secure: false,
      },
    },
  },
});
```

**Comment by manniL** [comment]
Because `$fetch` (and thus also `useFetch`) will only "emulate" a call if it goes to an internal API and instead call the event handler directly, proxying won't work. Instead, you want to use the runtime proxy (either routeRules or an API endpoint).
