### ISSUE TITLE
uncorrect link to /public resourсes in dev mode with non-default baseURL

### ISSUE THREAD

**Issue by Gringo675** [nuxt/nuxt#15689]
### Environment

- Operating System: `Windows_NT`                                                                                                                                                       
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.3.1`
- Builder:          `vite`
- User Config:      `app`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

`nuxt dev`

### Describe the bug

In dev mode, links to /public directory don't take into account value of baseURL, so static resourсes unavailable.

For example, let's define in nuxt.config

```baseURL: '/test/'```

and insert image in some vue component:

```<img src="/img/logo.svg">```

and take a look on created html (in dev mode):

`<img src="/img/logo.svg">`

Fine, but we have 404 error, because our image from `/public/img/logo.svg` is now available on `/test/img/logo.svg`

In production mode links create correctly, and we have html element `<img src="/test/img/logo.svg">`. So, workaround is to define:

```baseURL: process.env.NODE_ENV === 'production' ? '/test/' : '/'```

**Comment by danielroe** [comment]
This issue is no longer replicable: https://stackblitz.com/edit/github-3rdcdw.
