### ISSUE TITLE
Extends - override page can hide some child route

### ISSUE THREAD

**Issue by slarrasoain** [nuxt/nuxt#15687]
### Environment

nuxt3

### Reproduction

https://stackblitz.com/edit/nuxt-3-kpuboq?file=pages/index.vue

### Describe the bug

If a parent page is overriden then the chid page ar not inherrited anymore
If a child page is overriden it is not take in account if the parent is not overriden

Check the minimal reproduction for more use case

### Additional context

Related: #13367

**Comment by IsraelOrtuno** [comment]
Facing the same issue. Found a workaround by adding those pages manually from a module:

```ts
import { defineNuxtModule, extendPages } from '@nuxt/kit'
import { resolve } from 'pathe'

export default defineNuxtModule({
  setup () {
    extendPages((pages) => {
      const accountPage = pages.find(p => p.name === 'account')

      if (accountPage) {
        accountPage.file = resolve(__dirname, './overrides/pages/account.vue')

        accountPage.children.push({
          name: 'AccountAgency',
          path: 'agency',
          file: resolve(__dirname, './overrides/pages/account/agency.vue')
        })
      }
    })
  }
})
```

Very less obvious but works until this can be fixed.
