### ISSUE TITLE
Cannot use fp-ts: module not found

### ISSUE THREAD

**Issue by louwers** [nuxt/nuxt#15699]
### Environment

```
------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
```

### Reproduction

https://stackblitz.com/edit/github-ieqgfw?file=app.vue

### Describe the bug

Installing fp-ts and importing it results in:

```
[vite-node] [ERR_MODULE_NOT_FOUND] fp-ts/Either
```

**Comment by manniL** [comment]
You have to install the package. 😋

[Updated StackBlitz](https://stackblitz.com/edit/nuxtnuxtissues15699?file=package.json,app.vue)
