### ISSUE TITLE
.value is not resolved in template when use Nuxt plugin

### ISSUE THREAD

**Issue by misaon** [nuxt/nuxt#15709]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.18.0`
- Builder:          `vite`
- User Config:      `modules`, `oxyshopNuxt`, `i18n`
- Runtime Modules:  `normalizedModule()`, `normalizedModule()`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-xxv6jq?file=app.vue

### Describe the bug

If I define a `computed` with value in the **plugin**, then use the plugin in `<template>`, the `.value` does not contain any data. 
If I **inject** the plugin in `<script setup>` via `useNuxtApp`, computed is defined in the template.

**Comment by Baroshem** [comment]
@danielroe is this issue a feature request? I think you have added an answer so maybe this can be closed if no further work is needed?

**Comment by andreasvirkus** [comment]
Just helping out some future Googlers – if you get a 500 `unref() is not a function`, this could be the culprit.
