### ISSUE TITLE
`useAsyncData` return value that `pending` is `true` at server side when `server: false`

### ISSUE THREAD

**Issue by Mini-ghost** [nuxt/nuxt#15714]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-qorbrt?file=app.vue

Open DevTool, `<NuxtWelcome />` not render at server side.

### Describe the bug

When we use `useAsyncData()` and set `server: false`. the return value `pending` will get `true` at server side. It should be `false`? because this will not invoke at server side.

**Comment by Quineone** [comment]
> My suggestion is a new `fetching` property. It should be `true` only when the handler's promise is pending.
> 
> I've been exploring this idea in a module I'm working on, you can check it out in [nuxt-query](https://github.com/mahdiboomeri/nuxt-query).

Yes, indeed, I agree.  `pending ` is more like whether the data is fetched complete or not. act as the 
vueuse `isReady` did,   `https://vueuse.org/core/useAsyncState/` , so we also need the `isLoading` property

**Comment by manniL** [comment]
We decided to introduce a `status` property for more fine-grained control as `pending` is a mix-up of a few statuses here as discussed.

Closing this discussion here 👍🏻
Thanks everyone for your input

Follow-up on #18810
