### ISSUE TITLE
devServer config do not work in nuxt.config

### ISSUE THREAD

**Issue by Alex237** [nuxt/nuxt#15710]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `debug`, `ssr`, `srcDir`, `serverDir`, `dir`, `alias`, `app`, `css`, `devServer`, `runtimeConfig`, `router`, `modules`, `plugins`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

In nuxt config add :
`devServer` attribute like in the doc
https://nuxt.com/docs/api/configuration/nuxt-config/#devserver
Try to customise `port` and `host` with custom `port` and/or custom `ip`.
Run dev command.
It will show Local: `http://localhost:3000/ `in Terminal no  matter which custom port or ip you set.

https://stackblitz.com/edit/github-upsjtw?file=nuxt.config.ts

### Describe the bug

The configuration of devserver is in the docs, but do not seems to work :
 https://nuxt.com/docs/api/configuration/nuxt-config/#devserver
 All related issues say to use `NITRO_PORT` or `PORT`; `NITRO_HOST` or`HOST` if we want to customize those values.
 I feel confused to not be able to use nuxt.config. Setting the host port is not part of the configuration

**Comment by reslear** [comment]
same problem

**Comment by Quineone** [comment]
use the .env workaround for me, but when the port is not 3000 (eg. 6800), then there will throw an error:
```js
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.

WebSocket connection to 'ws://localhost:24679/_nuxt/' failed: 
```
nuxt: ^3.1.2

**Comment by Verequies** [comment]
I would say this should be marked as P4 Important. Especially when you have documentation that is saying it can be used.

Just spend hours today trying to figure out why the `devServer` options do not workin `nuxt.config.ts`, regardless of what the current documentation states. Doing a bit of investigation, if you take a look at the `dev` command [source](https://github.com/nuxt/nuxt/blob/main/packages/nuxi/src/commands/dev.ts), it isn't even implemented.

As of now, Nuxt currently only reads in variables from the supplied command line arguments.
Or optionally for setting only the host and port, using the `NUXT_HOST` and `NUXT_PORT` environment variables.

Unfortunately I am in the same boat as others, using the environment variables does not work as I require to dynamically set the TLS certificate and private key automatically.

Looking at the code, if I am not mistaken, it should not take long for someone to implement this feature.
If not, then I would highly recommend updating the documentation to warn people that it currently does not function as expected.
