### ISSUE TITLE
problem ssr with api and nuxt content

### ISSUE THREAD

**Issue by frs99** [nuxt/nuxt#15715]
### Describe the feature

Hello, how are you
I am working on a project and testing the project on static hosting.
In the project, I am using "api" and nuxt content

The problem is with: ssr
1- When you are in a situation: true
Which is the default setting: nuxt content does not run when npm run generate and exactly all articles or .md files are never generated and an error appears that there is nothing.

2- When you are in: false
Which is the recommended mode for static plugins, the problem here is with the api and I am saving the json files inside /public/api, and when npm run generate the articles in nuxt content appear but the api data is not present

The problem is between content and api and inverted in each case of ssr

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
You can use `routeRules`:

```js
export default defineNuxtConfig({
  routeRules: {
    '/**': { ssr: false }
  }
})
```

(This route rule only applies to Nuxt and will disable HTML generation for Vue pages.)

However, I would strongly advise that you enable SSR even for static hosting - I do not know where that recommendation came from but it is certainly not mine.
