### ISSUE TITLE
readBody gives different response in different preset

### ISSUE THREAD

**Issue by truc0** [nuxt/nuxt#15726]
### Environment

Nuxt project info:

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.17.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.17.1`
- Builder:          `vite`
- User Config:      `nitro`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/truc0/nuxt3-nitro-readBody-different-response-reproduction

### Describe the bug

The `readBody` function returns different value for the input in different environments (Cloudflare worker and development environment).

In development environment (`pnpm run dev -o`), the `readBody` returns an JSON object while it returns a buffer in cloudflare worker(`wrangler dev`) for the same request. The request is dispatched as following:

```js
  $fetch('/api/ping', {
    method: 'POST',
    body: { 'hello': 'world' },
  })
```

The `console.log` info when using `pnpm`:

```js
{ hello: 'world' }
```

The `console.log` info when using `wrangler`:

```js
<Buffer 7b 22 68 65 6c 6c 6f 22 3a 22 77 6f 72 6c 64 22 7d>
```

### Additional context

Running cloudflare worker version requires compiling the app. The reproduction steps is listed in the reproduction repo (https://github.com/truc0/nuxt3-nitro-readBody-different-response-reproduction).

I'm not sure whether it is a bug of `nitro` or `nuxt3`, thanks for reading.

**Comment by trapcodeio** [comment]
> 

Please which env variable did you add? I currently have this error but the @samohub solution does not work for me.

**Comment by zenojunior** [comment]
I'm facing the same bug

**Comment by zenojunior** [comment]
I'm facing the same bug
It's related to https://github.com/unjs/nitro/issues/912

**Comment by danielroe** [comment]
I believe this should be resolved in the latest h3 release - see https://github.com/unjs/nitro/issues/912#issuecomment-1486816149.
