### ISSUE TITLE
Enable `extend`, `include` or `mixin` in a pug vue template

### ISSUE THREAD

**Issue by toyopilgrim** [nuxt/nuxt#15746]
### Describe the feature

When you have  `extend`, `include` or `mixin` in a vue pug template,  the following error happens. 

`[vite] Internal server error: the "basedir" option is required to use includes and extends with "absolute" paths`

In Vue3, you can avoid this error by giving `basedir ` value to `vitejs/plugin-vue`  as below.

```
import {defineConfig} from 'vite'
import vue from '@vitejs/plugin-vue'


export default defineConfig({
    plugins: [
        vue({
            template: {
                preprocessOptions: {
                    basedir: __dirname
                }
            }
        }),
    ],
})
```

But in nuxt project, there seems no way.

I tried to configure the same way. 
```
export default defineNuxtConfig({
  vite: {
    plugins: [
      vue({
        template: {
          preprocessOptions: {
            basedir: __dirname,
          },
        },
      }),
    ],
  },
});
```

But it ended up with this error.

```ERROR At least one <template> or <script> is required in a single file component. #2```

It happens because of the same vue plugin being injected twice. 

My suggestion is that we add the addressed option to the vite setting
https://github.com/nuxt/framework/blob/837c93849941e49a90da627f6d31f3d4bd0d4d4d/packages/vite/src/vite.ts#L81

Although my example sets the root dir to `basedir`, it could be __dirname  +`/assets` instead for example.

A use case in which `extend`, `include` or `mixin` is needed is migration projects from traditional web sites which utilize those techniques. 

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
In general you can configure these options in the `vite.vue` configuration:

```js
import { createResolver } from '@nuxt/kit'

export default defineNuxtConfig({
  vite: {
    vue: {
      template: {
        preprocessOptions: {
          basedir: createResolver(import.meta.url).resolve('./')
        }
      }
    }
  }
})
```

Would you provide an example project so I can see whether we should be setting this by default for all Nuxt users? 🙏

**Comment by toyopilgrim** [comment]
Thank you for replying.  Following your advice, I have made it work as intended. 

Demo :  https://github.com/toyopilgrim/pug-nuxt-demo

```
    // Wrong (my previous config)
      vue({
        template: {
          preprocessOptions: {
            basedir:  './some_path',
          },
        },
      })

   // Correct (your proposal)
    vue: {
      template: {
        preprocessOptions: {
          basedir: createResolver(import.meta.url).resolve('./some_path')
        }
      }
    }

```

**Comment by danielroe** [comment]
Thank you for the example! It seems like maybe it makes sense to leave this for individual users to configure.
