### ISSUE TITLE
cannot load correctly in component styles when have nested css

### ISSUE THREAD

**Issue by hdw0504** [nuxt/nuxt#15744]
### Environment

- Operating System: `Linux`
- Node Version:     `v14.19.3`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://codesandbox.io/s/romantic-chandrasekhar-vjbsef?file=/app.vue

```vue
<template>
  <div>
    test button
    <el-button type="primary"> BTN </el-button>
  </div>
</template>

<script lang="ts" setup>
import { ElButton } from "element-plus";
// Invalid or unexpected token
// import "element-plus/lib/components/button/style/css";

// Unknown file extension ".css"
// import "element-plus/es/components/button/style/css";

// is work
import 'element-plus/theme-chalk/base.css';
import 'element-plus/theme-chalk/el-button.css';
</script>
```

### Describe the bug

import component style throw error
it work in vue3 but error in nuxt3

error:
`Invalid or unexpected token`
and
`Unknown file extension ".css"`

in nested file has some problem
```
// element-plus/es/components/button/style/css

import 'element-plus/es/components/base/style/css';
import 'element-plus/theme-chalk/el-button.css';
```

**Comment by manniL** [comment]
This is not a nuxt issue as [it is reproducible with Vue + Vite SSR too.](https://stackblitz.com/edit/nuxt-issues-15744-vue-ssr?file=src%2Fpages%2FHome.vue&terminal=dev)

I'd also suggest to raise an issue in https://github.com/element-plus/element-plus/ 🤔
