### ISSUE TITLE
Invalid types for `ModuleOptions` in `NuxtModule`

### ISSUE THREAD

**Issue by posva** [nuxt/nuxt#15750]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

The official template shows this problem out of the box:

```bash
npx nuxi init -t my-module
cd my-module
npm i
```

### Describe the bug

In the `nuxt.config.ts` you should find this typing error:

```
Type 'NuxtModule<ModuleOptions>' is not assignable to type 'string | NuxtModule<ModuleOptions> | [(string | NuxtModule<ModuleOptions> | undefined)?, ({ [x: string]: any; } | undefined)?] | undefined'.
```

Additionally, the types seem to be too loose and not autocomplete:

```ts
import MyModule from '..'

export default defineNuxtConfig({
  modules: [
    [MyModule, {
      // no autocompletion here
    }]
  ],
  myModule: {
    // or here
    addPlugin: true
  }
})
```

**Comment by danielroe** [comment]
A PR to add autocomplete for array types has just been merged (https://github.com/nuxt/nuxt/pull/18416).

I can no longer replicate the original issue (`Type 'NuxtModule<ModuleOptions>' is not assignable to type 'string | NuxtModule<ModuleOptions>`), and I've updated the starter to directly use module path for better type hinting: https://github.com/nuxt/starter/commit/f6affff4a622bf9bcab0fbba5f9a382a308fe785.

I'm closing this issue but if there's anything else that should be captured here, please do let me know - or raise a new issue.
