### ISSUE TITLE
bug: `extend` theme-config from node module with `defineEventHandler`

### ISSUE THREAD

**Issue by cpreston321** [nuxt/nuxt#15768]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.9.0`
- Nuxt Version:     `3.0.1-rc.0-27821553.ab125bd`
- Nitro Version:    `1.0.0-27809308.dc3383b`
- Package Manager:  `pnpm@7.17.1`
- Builder:          `vite`
- User Config:      `extends`, `unocss`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-yp6e9h?file=nuxt.config.ts

### Describe the bug

When I extend the my private npm package theme-config and it has custom server endpoints -- I get a an error saying `defineEventHandler is not defined`. 

### Additional context

Looking further into the `index.mjs`

``` js
import { eventHandler, setHeaders, sendRedirect as sendRedirect$1, defineEventHandler as defineEventHandler$1, handleCacheHeaders, createEvent, getRequestHeader, getRequestHeaders, setResponseHeader, createApp, createRouter as createRouter$1, lazyEventHandler, toNodeListener, getQuery, createError } from '...../node_modules/.pnpm/registry.npmjs.org+h3@1.0.1/node_modules/h3/dist/index.mjs';
```

then when it extends those endpoints it doesn't wrap that `defineEventHandler` into `defineEventHandler$1`.

Just keeps it the same.

```js
const _8p4oa8 = defineEventHandler((event) => {});
```

The npm module to extend server: https://github.com/cpreston321/nuxt-extends-bug

### Logs

```shell
[worker reload] [worker init] defineEventHandler is not defined                                                                                   14:36:04

  at .nuxt/dev/index.mjs:486:17
  at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:527:24)
  at async loadESM (node:internal/process/esm_loader:91:5)
  at async handleMainPromise (node:internal/modules/run_main:65:12)
```

**Comment by danielroe** [comment]
This has since been resolved: https://stackblitz.com/edit/github-yp6e9h
