### ISSUE TITLE
Custom JSON serializer&deserializer support in useState

### ISSUE THREAD

**Issue by Thaumy** [nuxt/nuxt#15760]
### Describe the feature

I noticed that the BigInt type will be serialized to Number in useState and it causes loss of precision.
Can we support a user-defined JSON serializer&deserializer in useState to solve this?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by manniL** [comment]
This works since https://github.com/nuxt/nuxt/pull/19205, enabling `experimental.renderJsonPayloads`

Example: https://stackblitz.com/edit/nuxt-issues-15760
