### ISSUE TITLE
Load a external font failed the server response is incorrect

### ISSUE THREAD

**Issue by yyyanghj** [nuxt/nuxt#15765]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction
[https://github.com/yyyanghj/nuxt-issue-9357](https://github.com/yyyanghj/nuxt-issue-9357)

### Describe the bug

Importing a CSS file to load a font failed. The server responds with an html file instead of a font file.

If I import the font.css in the `<script>`, everything is fine.

```vue
<script>
// uncomment next line works well.
// import "@fontsource/lora";
</script>

<style>
/* this does not work. */
@import "@fontsource/lora";

body {
  font-family: "Lora";
  font-size: 100px;
}
</style>

```

https://user-images.githubusercontent.com/34713301/204149097-89818bda-76e4-4d54-bf31-563142e19702.mov

**Comment by RomanHrynevych** [comment]
Took this issue, when reloading with default reload (ctrl+R) catch MIME type error with TailwindCSS, but when shift + f5, everything is ok (See the video to look for a difference between what vite response for main.css. (New project, just started it 2 days ago)

Nuxt v3.1.0
Tailwind v.3.2.4

https://user-images.githubusercontent.com/82209198/214557015-45981fac-75ab-4589-a56c-1ffd10991ad3.mp4

**Comment by mahsarajabpour** [comment]
I have the same issue.

**Comment by samydoesit** [comment]
Hello not sure if i am right here but i am experiencing some similar issue.

But in our case it's a bit different we do get this error on local development with an service worker. We hava a multipage setup some sites of our project will be rendered with nuxt3 where as some other parts of our site will still remain on a webpack build.
This requires us to share a service worker between both frontends. Atm we will use the service worker from the old webpack build and copy it to nuxt3.

If i do a production build there are no errors.
But if i run the nuxt3 app in dev mode i am also getting these strict mime type errors.
Reloading using CTRL + SHIFT + F5 is working.

```
__uno.css:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.
fonts.css:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.
``` 

Is there any way we can fix this?

**Comment by danielroe** [comment]
Still reproducible at https://stackblitz.com/edit/github-wszjkt (and not with Vite on its own at https://stackblitz.com/edit/github-lajxyf).
