### ISSUE TITLE
CSS and JS loading twice for static sites

### ISSUE THREAD

**Issue by daveish** [nuxt/nuxt#15763]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.8.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.18.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-wrfic5?file=package.json

Run with: `npm run build && npm run preview` (same behaviour if used with `npm run generate` and deployed to a web server)

### Describe the bug

In the Network Tab of the DevTools you can see that CSS and JS for `VBtn`, `default` and `tag` is loaded twice. That appears to be a bug, maybe due to prefetching.

A fix could possibly cut the load time for static sites in half.

**Comment by danielroe** [comment]
For a start, you should probably set `ssr: true` for a static site. (Otherwise you'll be generating empty pages.)

Looking at the issue, it seems it was caused by vuetify CSS not being transpiled:

Here's a working reproduction: https://stackblitz.com/edit/github-wrfic5-tvdjva.

**Comment by qgustavor** [comment]
Seeing the example I noticed what I was doing wrong: I was loading the CSS by adding a `@import './style.css'` to app.vue caused it to duplicate, I should have used the `css` config instead, when I changed that the issue got solved.
