### ISSUE TITLE
Allow nuxt-modules to set (server) middleware priority

### ISSUE THREAD

**Issue by BracketJohn** [nuxt/nuxt#15764]
### Describe the feature

Nuxt modules can expand nuxt applications in different ways. One such way is to add additional server middlewares using `@nuxt/kit`:
```ts
addServerHandler({
  middleware: true,
  handler
})
```

I would like to see a feature that allows module authors to (reasonably well) ensure server handler order. This is useful when module middlewares alter the `event.context` to contain a new property that can then be used by subsequent middlewares / server-handlers:
- authentication module middlewares may add user object: `event.context.user`,
- session  module middlewares may add session information: `event.context.session`,
- database module middlewares may add a db-connection that can then be used to query things: `event.context.db.$query('SELECT 1');`

At the moment, adding these properties via a middleware works reliably for endpoints that consume the event as endpoints always run after the middlewares. It does not work for chained middlewares. What happens is something like:
1. project-middleware runs, tries to access `event.context.session` but it doesn't exist yet
2. module-middleware runs, adds `event.context.session`
3. endpoint runs, it now has access to `event.context.session`

---

Different ways of resolving this that were already tried:
- rename module-middleware to `0.session` 
- use `nuxt.options.serverHandlers.unshift({ middleware: true, ... })` to add the middleware to the beginning of the server handler stack, run in the `module.ts`
  - likely failed because this happens at builld time before the user project middlewares are even added
- add a nitro plugin like [1]
  - unsure why this failed

[1] nitro plugin:
```ts
export default defineNitroPlugin(async (nitroApp) => {
  // something like this, but unsure if the timing here is correct.
  nitroApp.h3App.stack.push({
    handler: theSessionMiddleware
  })
})
```
---

Design approach 1 for feature: Make the name-based solution work where `0.session` will run before something like `checkSession.ts` or `1.checkSession.ts`

Design approach 2 for feature:
```ts
addServerHandler(handler, { priority: 0 })
```

Where then at runtime this is added _before_ everything with a higher priority.

I'm also sure that there's a workaround for this that I haven't figured out yet, so if there's any pointers on that, that would be greatly appreactiated.

---

Related:
- https://github.com/nuxt/framework/discussions/9094
- https://github.com/sidebase/nuxt-session/issues/44

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
Would love your thoughts on this @pi0. This seems like a reasonable thing to do but maybe should be implemented in Nitro directly - we could add a priority flag to `NitroEventHandler` and then sort by this?

**Comment by then3rdman** [comment]
Bumping this, currently causing me some issues I have to work around.

**Comment by Atinux** [comment]
Hi @BracketJohn 

I would go against the middleware road here but instead leverage server utils instead like I did on github.com/atinux/nuxt-auth-utils

- `getUserSession(event)`
- `requireUserSession(event)`

Instead of writing to the event context, you can also make it faster for the second call by storing into the event.

There are also Nitro hooks you can use if necessary. Hope this helps 😊
