### ISSUE TITLE
new URL().href returns wrong url if using nuxi generate

### ISSUE THREAD

**Issue by DaniGTA** [nuxt/nuxt#15784]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v19.1.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `sourcemap`, `target`, `buildModules`, `vite`, `configureWebpack`, `loaders`, `proxy`, `experimental`, `extensions`, `router`, `app`, `head`, `css`, `plugins`, `components`, `modules`, `i18n`, `build`, `sitemap`, `schemaOrg`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.4`, `@nuxt/image-edge@1.0.0-27809804.194d2d6`, `@nuxtjs/tailwindcss@6.1.3`, `@pinia/nuxt@0.4.5`, `nuxt-proxy@0.3.4`, `@vueuse/nuxt@9.6.0`, `@nuxtjs/partytown@1.2.2`, `nuxt-jsonld@2.0.7`
- Build Modules:    `@nuxt/image`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-djaoib?file=app.vue,nuxt.config.ts

### Describe the bug

On `windows` the image path is wrongly generate with the command `nuxi generate`

The image path is `file:///C:/mypath/img.png`
expected path is:  `/.../img.png`

### Additional context

Its propably a bug with `new URL`. 

`new URL(
  "path",
  import.meta.url
).href;` generate wrong **href** in `nuxi generate`

**Comment by danielroe** [comment]
This doesn't sound like a Nuxt issue. `import.meta.url` (on server-side) is not going to point to the host + path of a page, but to the local file path, which is not what you want anyway. (Note that you don't really care about rendering an og url on client-side.)

For example, in your repro it is `'file:///home/projects/github-djaoib/~/public/test.png` - that's expected.

I think for what you want you'll need to get the host from the request headers and add `/test.png`.
