### ISSUE TITLE
NuxtLoadingIndicator remains active in case of navigation errors

### ISSUE THREAD

**Issue by stenet** [nuxt/nuxt#15788]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.18.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-vfkizu-uvbg8x

### Describe the bug

If an error occurs in a page with top level await, then the page:finish hook is not triggered and thus the NuxtLoadingIndicator remains active.

In the example, this can be recreated by clicking on the About link.

Would it make sense to provide a page:error hook in addition to page:finish?

**Comment by madebyfabian** [comment]
Would be a great enhancement in my opinion, what do you think about a `page:error` hook @danielroe?

**Comment by xanderbarkhatov** [comment]
Fix has been merged. Can it be closed now?
