### ISSUE TITLE
Using `extends` on a project with nuxt modules causes an error

### ISSUE THREAD

**Issue by CernyMatej** [nuxt/nuxt#18369]
### Environment

CHILD:
- Operating System: `Darwin`
- Node Version:     `v14.21.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `extends`
- Runtime Modules:  `-`
- Build Modules:    `-`

PARENT:
- Operating System: `Darwin`
- Node Version:     `v14.21.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@vueuse/nuxt@9.11.0`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-nzvnvt?file=project/nuxt.config.ts

### Describe the bug

I'm trying to use `extends` to auto import components, modules, composables etc. from another nuxt project in a different directory, however, when the project I'm extending includes a nuxt module module, I get an error that it could not find the module and the build fails.

**Comment by slarrasoain** [comment]
As mentioned in the layer [documentation ](https://nuxt.com/docs/guide/going-further/layers), if a layer has npm dependencies, you will have to install them manually in the target project.
In your reproduction project you need to add  
 "dependencies": {
    "@vueuse/nuxt": "^9.11.0"
 }
 in package.json

**Comment by CernyMatej** [comment]
> As mentioned in the layer [documentation ](https://nuxt.com/docs/guide/going-further/layers), if a layer has npm dependencies, you will have to install them manually in the target project. In your reproduction project you need to add "dependencies": { "@vueuse/nuxt": "^9.11.0" } in package.json

There should be a link to the documentation page you referenced in the nuxt.config section about `extends`.

However, if I didn't miss anything, it only says that the dependencies should be added to `package.json` in the section about **publishing** an npm package. Where exactly does it say that I should add the modules into the project extending the base one?
And also, didn't it use to work like I expected earlier? Have a look at this video: https://youtu.be/HvTui3P0w-o

Furthermore, one of the highlighted features of Layers is `Create Nuxt module presets` as mentioned [here](https://nuxt.com/docs/getting-started/layers). How is this creating a "module preset" when I have to think about the dependencies used in the base layer & add them to every project extending it?

**Comment by slarrasoain** [comment]
I'm sorry if my turn of phrase seemed aggressive, I'm French and my English is not perfect. It is possible that the documentation has evolved (in my memory the remark was more global). But indeed I initially encountered the same problem as you and I had found without the documentation after a lot of research. So I hope I helped you a little.  The work of the Nuxt team is enormous so let's give them time to perfect things. I think their project is good and moving fast but nuxt3 is still young and when you get into a more advanced operation you find a few things to improve. This is the game and thanks again to them for their work.

**Comment by CernyMatej** [comment]
No, you didn't seem aggressive at all :) I am acutally very grateful for your comment because I can continue working thanks to your solution. It is undeniable that the accomplishments of the Nuxt team are truly remarkable. I am deeply appreciative of their efforts.
However, I do think this is a bug 😅
If not, I hope that someone from the team will clarify it a little better than the documentation.

**Comment by DylandeBruijn** [comment]
I'm having the same problem, did you find a solution?

**Comment by CernyMatej** [comment]
> I'm having the same problem, did you find a solution?

Yeah, you need to add the dependencies of the layer you are extending to the child layers and make sure you run the dev server in the layer you are extending.
