### ISSUE TITLE
Sourcemaps for css/sass are not working

### ISSUE THREAD

**Issue by Ghustavh97** [nuxt/nuxt#18377]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `telemetry`, `ssr`, `devServer`, `typescript`, `components`, `css`, `webpack`, `sourcemap`, `dev`, `postcss`, `modules`, `plugins`
- Runtime Modules:  `@pinia/nuxt@0.4.6`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-x4a2um 

Steps to reproduce:

1. Try to enable css/scss sourcemaps in `nuxt.config.ts`

### Describe the bug

I'm using sass in the project and sourcemaps are not toggling on. All the sass and css are all being converted to inline styles.

![no-sourcemaps-style](https://user-images.githubusercontent.com/20132952/213657411-9b8e8ddf-0076-4b45-9793-ed045c2629b4.PNG)

![no-sourcemaps-elements](https://user-images.githubusercontent.com/20132952/213657441-75072aec-1e33-4dfd-bf16-3934b039b880.PNG)

Here's my  `nuxt.config.ts`

```js
export default defineNuxtConfig({
  ssr: false,
  devServer: {},
  typescript: {
    strict: false,
    typeCheck: true
  },
  components: {
    dirs: [
      {
        path: "~/components/global",
        global: true,
        pathPrefix: false
      }
    ]
  },
  css: ["@/css/application.css", "@/scss/application.scss"],

  webpack: {
    cssSourceMap: true,
    loaders: {
      scss: {
        sourceMap: true
      }
    }
  },

  sourcemap: {
    server: true,
    client: true
  },

  dev: true,

  postcss: {
    plugins: {
      tailwindcss: {},
      autoprefixer: {}
    }
  },

  modules: [
    // "nuxt-typed-router"
    "@pinia/nuxt"
  ],

  plugins: []
});
```

**Comment by manniL** [comment]
Hey! Could you kindly provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by Ghustavh97** [comment]
@manniL https://stackblitz.com/edit/github-x4a2um  👍

**Comment by danielroe** [comment]
Sourcemaps in CSS are not currently supported in `vite`. The issue is being tracked in https://github.com/vitejs/vite/issues/2830.

**Comment by Ghustavh97** [comment]
@danielroe Thanks for linking that issue, found a temporary fix there that is working. Added this to the config,

```js
  vite: {
    css: {
      devSourcemap: true
    }
  },
```
