### ISSUE TITLE
Wrong payload loaded for sub pages when using SSG/Full Static Mode/`nuxt generate`

### ISSUE THREAD

**Issue by JonathanDoelan** [nuxt/nuxt#18402]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.20.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.25.0`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `modules`, `i18n`, `directus`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.2.0`, `@nuxtjs/i18n@8.0.0-beta.7`, `nuxt-directus@3.2.2`
- Build Modules:    `-`

### Reproduction

Create a page (other than an index page) in the pages directory and fetch some data, to provide some data for the `_payload.js`. Then run `nuxt generate` and recognize that there is no data for the page.

OR clone https://github.com/JonathanDoelan/nuxt-payload-issue

OR just visit https://stackblitz.com/edit/github-qiqtjg?file=README.md,pages%2Findex.vue,pages%2Fabout.vue

### Describe the bug

When using SSG and viewing sub pages like `pages/about.vue` in the browser the wrong payload is loaded. `nuxt generate` will generate the `_payload.js` files in the correct directories like `/_payload.js, /about/_payload.js` and they seem to have the correct data in it, but when viewing `/about` in the browser, you will get an error like:

```
TypeError: Cannot read properties of null (reading '…')
```

If you look at the network tab, you will recognize, that the `/_payload.js` is loaded instead of `about/_payload.js` — that‘s why we get this error.

**This makes it impossible to use Nuxt 3.0.0 in Full Static/SSG mode!**

A workaround could be to fetch all needed data globally, for example in the `default.vue` layout, but I haven’t tried it yet.

:(

**Comment by manniL** [comment]
Hey! Could you kindly provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by JonathanDoelan** [comment]
> Hey! Could you kindly provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

@manniL I’ve created one (with GitHub Codespaces): https://github.com/JonathanDoelan/nuxt-payload-issue

Do have the same bug?

**Comment by provok-it** [comment]
@JonathanDoelan I also use Nuxt i18n.

I did some debugging. When generating the _payload.js files, `useI18n().locale` returns the wrong locale.
For me it switches `en` to `fr` and vice versa.

To be clear, when generating it looks like this:
- `/mentions-legales` => `fr`
- `/en/legal-notice` => `en`
- `/mentions-legales/_payload.js` => `en`
- `/en/legal-notice/_payload.js` => `fr`

It seems that it is a i18n/Nuxt-related problem.
Can you also confirm by logging `useI18n().locale.value` to the console while generating your project.

Poke @kazupon ✌️

**Comment by JonathanDoelan** [comment]
@provok-it I don’t use Nuxt i18n in this [app](https://github.com/JonathanDoelan/nuxt-payload-issue)

And in my real project, I only use one locale … (because I like to separate content from the template)

**Comment by provok-it** [comment]
@kazupon @pi0 do I need to recreate an issue for the i18n/Nuxt SSG locale problem?

**Comment by kazupon** [comment]
> do I need to recreate an issue for the i18n/Nuxt SSG locale problem?

I hope you would like to transfer to i18n module repo. 🙏 
https://github.com/nuxt-modules/i18n

**Comment by kazupon** [comment]
@provok-it 
>I hope you would like to transfer to i18n module repo. 🙏

Sorry, That mean, I mentioned for your comment. I think that issue is different from this issue.

**Comment by JonathanDoelan** [comment]
@manniL I’ve published the repo also on [stackblitz](https://stackblitz.com/edit/github-qiqtjg?file=README.md,pages%2Findex.vue,pages%2Fabout.vue) which should make it easier to review.

I now don’t think that the problem is with the _payload.js … but somehow sub pages aren’t working. I mean, it works client side, but not when I (re)load the `/about` page directly.

Any ideas?

**Comment by manniL** [comment]
@JonathanDoelan might it be related to https://github.com/nuxt/nuxt/issues/14454? If not, I'll have a look in a bit :)

**Comment by danielroe** [comment]
Yes, you're exactly right @manniL. This only occurs when running `nuxi preview`, which is only for local development preview (you should never deploy your applications this way). 

To avoid the `-s` argument, you can always run `npx serve .output/public` without the `-s`.

Let's track the improvement to the local preview in https://github.com/nuxt/nuxt.js/issues/14454.

**Comment by JonathanDoelan** [comment]
@manniL @danielroe Thanks for the clarification. I am just wondering if we should mention this somewhere in the docs? Because I thought SSG simply doesn’t work for Nuxt 3. But it does and I am quite happy about this. Thanks!
