### ISSUE TITLE
Middleware not executed when validate() is present

### ISSUE THREAD

**Issue by toniengelhardt** [nuxt/nuxt#18412]
### Environment

See Stackblitz, nothing special.

### Reproduction

https://stackblitz.com/edit/nuxt3-validate-middleware-bug

### Describe the bug

When `validate()` is present in `definePageMeta` middleware is not executed.

**Comment by danielroe** [comment]
This should be resolved in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/), or in the next release.

Let me know if not and I'll reopen.
