### ISSUE TITLE
SSG useFetch makes request to nitro server instead of using the generated payloads

### ISSUE THREAD

**Issue by provok-it** [nuxt/nuxt#18438]
### Environment

- Operating System: `Darwin`
- Node Version:     `v19.2.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `typescript`, `modules`, `generateSvgsViewboxes`, `i18n`, `svgo`, `image`, `robots`, `sitemap`, `runtimeConfig`, `vite`, `nitro`, `css`, `app`
- Runtime Modules:  `~~/modules/download-routes-params/index.ts`, `~~/modules/generate-svgs-viewboxes/index.ts`, `~~/modules/cms-redirections/index.ts`, `@nuxtjs/i18n@8.0.0-beta.7`, `nuxt-svgo@1.1.0`, `@nuxt/image-edge@1.0.0-27840416.dc1ed65`, `@nuxtjs/robots@3.0.0`, `@funken-studio/sitemap-nuxt-3@4.0.4`
- Build Modules:    `-`

### Reproduction

- Use `useFetch` to get data from nitro server with a computed or ref as body parameter.
- Make sur to update the ref or computed value at some point.
- `nuxi generate && npx serve .output/public`
- Interact with the website to update ref/computed
- Get the error in the console.

On the reproduction sandbox you can use `yarn generate && yarn preview:hack`.
[Reproduction link](https://stackblitz.com/edit/github-4luw1y?file=layouts/default.vue)

### Describe the bug

`useFetch` is trying to get data from the server and not from the generated payload when a computed or ref passed in the body updates.

**Comment by danielroe** [comment]
If you do not want it to request updates when the values change, which I imagine you do not with a static site, you should not pass a ref or computed value into the options/body.

Nuxt's data fetching composables allow loading the data from payload by default but you can always force a refresh by updating the query/body or manually calling `refresh` or `execute`. In this case it's intentional that it doesn't load the data from the payload (as, in fact, the data is not present in the payload).

**Comment by provok-it** [comment]
@danielroe I want it to request an update but get the associated payload instead of calling the server.

In my case, it is an i18n problem.
My `layout/default.vue` has a Footer component with links leading to FR pages.
I get the Footer's data from the server using useFetch in the Footer component.

When I change the page language with the lang switcher, I want my Footer's data to be updated with new locale code passed as a body parameter. 

How would you do it if you don't use a computed as body param?

It makes no sense to download all the locales data just in case the user selects another language because "what if one does not". This user would be loading another locale's data for nothing.

So, how do you handle i18n in the layout components the right way?

**Comment by tesla3327** [comment]
You have two options for getting locale data:
1. Include _everything_ in the initial payload
2. Fetch from a server as needed

If it doesn't make sense to include everything in the payload, then you have to fetch it from the server. If you can't have a server, then you need to include all locale data.
