### ISSUE TITLE
Module import using extends from remote source

### ISSUE THREAD

**Issue by luigigorlero** [nuxt/nuxt#18448]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

[CodeSandbox](https://codesandbox.io/p/sandbox/wispy-pond-uq22j9)

### Describe the bug

We are trying to create a layer with shared components, but are having troubles when it comes to extending – **from a github repository** – components with a module import. This happens regardless of the import being explicit (in the example, using `import { useToggle } from '@vueuse/core'`) or auto-imported by a nuxt module (e.g, including `modules: ['@vueuse/nuxt']` inside NuxtConfig)

### Additional context

**Note:** the same dependencies have been installed in the target project.
**Note:** extending the same layer from a local folder works flawlessly

### Logs

```shell-script
Failed to resolve import "@vueuse/core" from "../../.cache/c12/github_luigigorlero_private-test/components/TestButton.vue". Does the file exist?
```

**Comment by nonlinearcom** [comment]
Same here!

**Comment by nonlinearcom** [comment]
I'm also getting: 
```
[plugin:vite:import-analysis] Failed to resolve import "swiper" from "../../../.cache/c12/github_nonlinearcom_private-test/components/gallery/Cards.vue". Does the file exist?
```

Does anyone know how to make imported modules work with extends from github repos? 🤔

**Comment by pi0** [comment]
Hi. This is an strange issue. Meanwhile we don't install dependencies of remote sources, it seems search path is also broken somehow. I will investigate better but meanwhile, as a quick workaround you can use an alias in target project like this:


```ts
export default defineNuxtConfig({
  extends: "github:luigigorlero/private-test#codesandbox",
  modules: ["@vueuse/nuxt"],
  alias: {
    "@vueuse/core": require.resolve("@vueuse/core/index.mjs"),
  },
});
```

**Comment by luigigorlero** [comment]
> Hi. This is an strange issue. Meanwhile we don't install dependencies of remote sources, it seems search path is also broken somehow. I will investigate better but meanwhile, as a quick workaround you can use an alias in target project like this:
> 
> ```ts
> export default defineNuxtConfig({
>   extends: "github:luigigorlero/private-test#codesandbox",
>   modules: ["@vueuse/nuxt"],
>   alias: {
>     "@vueuse/core": require.resolve("@vueuse/core/index.mjs"),
>   },
> });
> ```

Fascinating! That helped, thank you!

**Comment by luigigorlero** [comment]
Reopening since the problem still occurs on build, even with simpler components without any import

`[vite]: Rollup failed to resolve import "vue/server-renderer" from "../../../.cache/c12/github_nonlinearcom_yac-ui/components/block/FullImage.vue?vue&type=script&setup=true&lang.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
'build.rollupOptions.external'`

**Comment by nonlinearcom** [comment]
Did anyone got `extends/layers` working with different github repos + nuxt modules (installed on both projects)? without this option we are basically forced to use the monorepo integration.

**Comment by nonlinearcom** [comment]
I think I found a temporary workaround for this issue:

```
// TestButton.vue (base repo)
import { useDark, useToggle } from '@/node_modules/@vueuse/core';
```
```
// nuxt.config.ts on extended layer 
alias: {
  "@Components": "./components",
},
```

**Comment by warflash** [comment]
> Hi. This is an strange issue. Meanwhile we don't install dependencies of remote sources, it seems search path is also broken somehow. I will investigate better but meanwhile, as a quick workaround you can use an alias in target project like this:
> 
> ```ts
> export default defineNuxtConfig({
>   extends: "github:luigigorlero/private-test#codesandbox",
>   modules: ["@vueuse/nuxt"],
>   alias: {
>     "@vueuse/core": require.resolve("@vueuse/core/index.mjs"),
>   },
> });
> ```

Hey @pi0 - just ran into this exact issue, thanks for the workaround!
Though I was wondering if there's some sort of fix on the horizon? Having to manually alias all the packages that are being imported in the project that's extended off of is quite the pain and quite ugly with the index path hardcoding etc.

Thanks!

**Comment by bureaubox** [comment]
> Hi. This is an strange issue. Meanwhile we don't install dependencies of remote sources, it seems search path is also broken somehow. I will investigate better but meanwhile, as a quick workaround you can use an alias in target project like this:
> 
> ```ts
> export default defineNuxtConfig({
>   extends: "github:luigigorlero/private-test#codesandbox",
>   modules: ["@vueuse/nuxt"],
>   alias: {
>     "@vueuse/core": require.resolve("@vueuse/core/index.mjs"),
>   },
> });
> ```

Thanks for this workaround! I agree with @warflash that it is not perfect, but it works (which is great after messing around with this issue for a couple of hours). At least, when importing from vue components and such. But it doesn't fix the imports for my tailwind.config.ts file (which is in my base layer). Such as

```
const plugin = require('tailwindcss/plugin')
const { createThemes } = require('tw-colors');
const debugScreens = require('tailwindcss-debug-screens')
```

This works fine when running `dev` from the layer itself, but not when running `dev` from the app that's extending the layer. Then I get:

```
Nuxi 3.4.3                                                                                                                                                                                                                             6:45:01 PM
Nuxt 3.4.3 with Nitro 2.4.0                                                                                                                                                                                                            6:45:01 PM

 ERROR  Cannot find module 'tailwindcss/plugin'                                                                                                                                                                                        6:45:02 PM
Require stack:                                                                                                                                                                                                                         6:45:01 PM
- /Users/remihuigen/.cache/c12/github_onderwijsin_layers-nuxt_base/tailwind.config.ts

  Require stack:
  - /Users/remihuigen/.cache/c12/github_onderwijsin_layers-nuxt_base/tailwind.config.ts
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1021:15)
  at Function.resolve (node:internal/modules/cjs/helpers:114:19)
  at _resolve (node_modules/jiti/dist/jiti.js:1:241025)
  at jiti (node_modules/jiti/dist/jiti.js:1:243309)
  at /Users/remihuigen/.cache/c12/github_onderwijsin_layers-nuxt_base/tailwind.config.ts:5:16
  at jiti (node_modules/jiti/dist/jiti.js:1:245784)
  at /Users/remihuigen/.cache/c12/github_onderwijsin_layers-nuxt_base/nuxt.config.ts:3:17
  at Object.jiti (node_modules/jiti/dist/jiti.js:1:245784)
  at resolveConfig (node_modules/c12/dist/index.mjs:279:24)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async extendConfig (node_modules/c12/dist/index.mjs:217:21)
  at async loadConfig (node_modules/c12/dist/index.mjs:159:5)
  at async loadNuxtConfig (node_modules/@nuxt/kit/dist/index.mjs:491:18)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:124:20)
  at async _main (node_modules/nuxi/dist/cli.mjs:48:20)
```

Anybody have a workaround for this? I would really love to include tailwind in my layers, since I have multiple apps sharing a theme....

**Comment by Liliane97** [comment]
Mine also gives the same error with vuetify

**Comment by nonlinearcom** [comment]
I guess the only way to make it work for now is extending layers inside a monorepo :(

**Comment by miclgael** [comment]
Linking to my repros from this similar issue: https://github.com/nuxt/nuxt/issues/12347#issuecomment-1609095022

**Comment by Liliane97** [comment]
I managed to solve my problem, in my case I had set treeshaking as true, I only found out after I redid it by calling only the vuetify module in nuxt.config, so I debugged to find out what was going wrong, and I set treeshaking as false which in this case is your default.

**Comment by danielroe** [comment]
We do now support installing dependencies of remote sources:

```ts
export default defineNuxtConfig({
  extends: [
    ['github:username/repoName', { install: true }]
  ]
})
```
