### ISSUE TITLE
Add `routeNameSplitter` option from Nuxt 2

### ISSUE THREAD

**Issue by adamndev** [nuxt/nuxt#18457]
### Discussed in https://github.com/nuxt/nuxt/discussions/15906

<div type='discussions-op-text'>

<sup>Originally posted by **adamndev** January 17, 2023</sup>
Hey guys

I'm in the process of migrating a fairly large app over to Nuxt 3 and can't find any mention of the `routeNameSplitter` option from Nuxt 2.

Our routes match the naming conventions from other frameworks including Laravel, so instead of `events-attendees-create`, we'd generate this route as `events.attendees.create`. I think this is much cleaner as routes are likely to contain dashes themselves.

Is there any way to replicate this at the moment? And is this likely to be added back in?

Thanks for all the hard work 👌🏻</div>

I got a bit further in and realised that the simple regex used in a hook isn't gonna work and would need quite a bit of logic to figure out. This is a blocker to us migrating our Nuxt 2 app to Nuxt 3. Do you think we could get this added, please?

**Comment by manniL** [comment]
Added a draft PR. From my POV it could make sense to add the feature back as a normal regex might not be enough here to "fix" it, e.g. via hooks.

**Comment by danielroe** [comment]
On reflection, it seems to be quite an involved piece of coding (that we will need to maintain within Nuxt) for an edge case. Something like this might work if you want to keep the Nuxt page name algorithm:

```js
import { createResolver } from '@nuxt/kit';

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  hooks: {
    'pages:extend'(pages) {
      const root = createResolver(import.meta.url).resolve('./pages');
      function updateName(pages) {
        if (!pages) return;
        for (const page of pages) {
          let name = page.name.replace(/-/g, '.');
          for (const match of page.file.matchAll(/[\w\-]+/g)) {
            name = name.replace(match[0].replace(/-/g, '.'), match[0]);
          }
          page.name = name;
          updateName(page.children);
        }
      }
      updateName(pages);
    },
  },
});
```

https://stackblitz.com/edit/github-h24slc

Otherwise you can just set whatever name you want for your pages, based on the file path.

**Comment by pi0** [comment]
ّI also agree that adding customizable conventions adds the burden of long-term maintenance for Nuxt and also makes it harder to integrate with toolings outside of Nuxt lifecycle to consider customized conventions (ie: a devtools or CLI extension that generates pages).

Using hooks is a nice idea! (perhaps expose as a migration-helper module/nuxt2-3-bridge?)

In general, re using dots for names, we also use them for suffixes (`component.server.vue`) which can be potentially conflicting however i respect that you might like the alternative convention, it can be opt-in via a module.

**Comment by manniL** [comment]
Good points @danielroe and @pi0! 
Given that there is a suitable workaround, would you vote for not introducing the feature to reduce maintenance effort in the future?

**Comment by manniL** [comment]
Closing here as there is a workaround possible for user land and to reduce maintenance burden as discussed before ☺️
