### ISSUE TITLE
`useLazyFetch` for fetching public resources fails when using SSR

### ISSUE THREAD

**Issue by tex0l** [nuxt/nuxt#18452]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.3`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Here is a repo: https://stackblitz.com/edit/github-puvkc8?file=app.vue

If you leave `server: true` which is the default behavior, it fails, sometimes with a `[nuxt] [request error] [unhandled] [500] Body is unusable` a few minutes after the server is started, sometimes with a `404 Page not found`.

If you change it to `server: false`, it works as expected, but extra requests are made.

### Describe the bug

When you try to fetch a resource located in the `public/` directory of your Nuxt project, it works when fetched from the client side, but apparently the optimization that `$fetch` does of `pre-fetching resources on the backend directly seems to fail`(https://nuxt.com/docs/api/utils/dollarfetch).

**Comment by manniL** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/13857
