### ISSUE TITLE
Support allowing module libraries to provide types for module-written built-in middlewares

### ISSUE THREAD

**Issue by Q16solver** [nuxt/nuxt#18463]
### Describe the feature

It is currently possible for nuxt modules to add their own custom middleware for users, however, this is not detected by typescript when nuxt 3 generates the types when building/running in dev environment. A workaround could be for the user to add a stub middleware to force nuxt 3 to generate the types as it still seems to be using the middleware defined by the module when running `definePageMeta({ middleware: 'customModuleBuiltInThing' })` but it would be great if there could be some option for modules to declare what middleware it's providing so nuxt 3 can generate it.

Related discussion: https://github.com/nuxt/nuxt/discussions/18462

Some use cases:
- Auth middleware: https://github.com/sidebase/nuxt-auth/issues/157

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
We now have support for `addRouteMiddleware` with full support for typing.
