### ISSUE TITLE
Unexpected token 'export' when importing moment locale

### ISSUE THREAD

**Issue by RijaCloud** [nuxt/nuxt#18468]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@9.2.0`
- Builder:          `vite`
- User Config:      `app`, `build`, `modules`, `proxy`, `css`, `vite`, `i18n`, `runtimeConfig`, `plugins`, `components`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.7`, `nuxt-proxy@0.3.4`
- Build Modules:    `-`
------------------------------

### Reproduction

I'm trying to translate the dates on my application via moment but for some reason when I import any locale from moment/dist/ I have a problem.

`components/Date.vue`

````vue
<script>
import moment from "moment"
import 'moment/dist/locale/fr';
import 'moment/dist/locale/en-ca';
import 'moment/dist/locale/nl';
export default {
  mounted() {
    console.log(moment().format("MMM-YY").replace(".", ""))
  },
// The rest of the code 
    stackReviewData() {
      const data = this.reviewChart.stack[this.useDashboardStore.getComparaisonReview.periodType];
        
      if (data) {
        const { labels } = data;
        if (this.currentPeriodType === dataPeriode.ONE_MONTH) {
          data.labels = labels.map((l) => {
            return setDateCompareCustomerReview(
              moment(l, "MMM yy").format("MMM-yy")
            ).replace(/<br>/g, "");
          });
        } else {
          const currentDay = moment().format("dd");
          if (currentDay !== "01") {
            data.labels[data.labels.length - 1] = `01-${moment()
              .subtract(1, "day")
              .format("dd MMM yy")}`;
          } else {
            data.labels[data.labels.length - 1] = moment()
              .subtract(1, "day")
              .format("dd MMM yy");
          }
        }
      }
      return _.cloneDeep(data) || {};
    },
    month() {
      return {
        current: capitalize(moment().format("MMM-YY").replace(".", "")),
        previous: capitalize(
          moment().subtract(1, "month").format("MMM-YY").replace(".", "")
        ),
      };
    },
}
</script>
<template>
<div>
Hello
</div>
</template>
````

I am using "moment": "^2.29.4". 

### Describe the bug

Here is the issue : 

````
500
Unexpected token 'export'

at wrapSafe (node:internal/modules/cjs/loader:1088:15)
at Module._compile (node:internal/modules/cjs/loader:1123:27)
at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
at Module.load (node:internal/modules/cjs/loader:1037:32)
at Module._load (node:internal/modules/cjs/loader:878:12)
at ModuleWrap. (node:internal/modules/esm/translators:169:29)
at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Promise.all (index 0)
````

it only happens when I import the locales of moments only.

Thanks for your help.

**Comment by manniL** [comment]
Friendly reminder that moment is considered *legacy* and you should use a library like [Luxon](https://moment.github.io/luxon/), [date-fns](https://date-fns.org/) or [Day.js](https://day.js.org/).

**Comment by Baroshem** [comment]
Have you tried importing it like this?

```ts
await import(<YOUR_LIB_HERE>).then(lib => lib.default || lib)
```

**Comment by RijaCloud** [comment]
Hi @manniL 

Here is a reproduction for this issue : https://stackblitz.com/edit/rijacloud-moment-nuxtv3?file=app.vue

**Comment by Baroshem** [comment]
For some reason, while importing from `moment/dist/locale` it breaks.

Can you try to import them directly from moment like this?

```vue
<script>
import moment from 'moment';
import 'moment/locale/fr';
import 'moment/locale/en-ca';
import 'moment/locale/nl';
export default {
  async mounted() {
    moment.locale('fr');
    console.log(moment().format('MMM-YY').replace('.', ''));
  },
};
</script>
<template>
  <div>Hello</div>
</template>

```

**Comment by RijaCloud** [comment]
Hi @Baroshem 
Thank you for your answer. I have tried your proposal, there is no more error but I I tried to change the locale nothing happens. It remains in English

**Comment by madebyfabian** [comment]
Hey there! @Baroshem due to the module being legacy, I'd suggest closing this, but feel free to reopen. Thank you 🙏🏻💚

**Comment by manniL** [comment]
Even though moment is legacy, it should work.

**Comment by manniL** [comment]
The solution here is to `transpile` all `moment` modules.
See my [updated stackblitz](https://stackblitz.com/edit/nuxtissues18468).
