### ISSUE TITLE
Automatic module setup via nuxi cli

### ISSUE THREAD

**Issue by mat2ja** [nuxt/nuxt#18478]
### Describe the feature

It would be great if `nuxi` gets the functionality similar to [Astro Integrations (astro-add)](https://docs.astro.build/en/guides/integrations-guide/) for setting up external integrations/modules. Svelte Ecosystem has its own version as well ([svelte-add](https://github.com/svelte-add/svelte-add)).

The module system in Nuxt is pretty straightforward as it currently stands, but it would be a great addition if it automatically installed the module, added it to the `nuxt.config`, and set up required config options and files, straight from the CLI, using `nuxi add`.

It should show a preview of what's about to be added, and require a confirmation for every step (as Astro does it), as well as offer a flag to automatically accept all prompts.

### Example:
`npx nuxi add module unocss`

### Astro-add functionality:
![image](https://user-images.githubusercontent.com/46557266/214321269-cfd450bb-1d08-42a5-a165-cc13eb6476c9.png)
![image](https://user-images.githubusercontent.com/46557266/214321709-88748841-14cb-45f4-8f5f-46ad9c091514.png)

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
Related: https://github.com/nuxt/nuxt/issues/13552, https://github.com/nuxt/nuxt/issues/13550

**Comment by Baroshem** [comment]
Also, related to https://github.com/nuxt/framework/pull/4001

**Comment by danielroe** [comment]
I very much agree and this is on our roadmap - let's track in the issues @manniL linked.
