### ISSUE TITLE
support change instance of $fetch for using in useFetch and ...

### ISSUE THREAD

**Issue by DJafari** [nuxt/nuxt#18489]
### Describe the feature

Suppose we need add automatically some headers for all requests ( for example Bearer token ) how can doing it without pass in all requests ?

i think we must have api to change default $fetch instance to using it on all useFetch requests

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by HigherOrderLogic** [comment]
You can wrap `useFetch` in another composable.

```ts
async function fetchApi(...) { return await useFetch(...);}
```

**Comment by manniL** [comment]
Indeed, creating your own composable based on useFetch (or useAsyncData) is the way to go here ☺️
