### ISSUE TITLE
Error message is "undefined" when import paths in server/api files are broken

### ISSUE THREAD

**Issue by arvl130** [nuxt/nuxt#18481]
### Environment

Here is the output of `npx nuxi info` from my linked Stackblitz reproduction:

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-sht6qg?file=README.md

### Describe the bug

If you have a broken import path in any of your `server/api` files, the error message that will be show will be as follows:

```
Nuxi 3.0.0                                                                  22:33:29
Nuxt 3.0.0 with Nitro 1.0.0                                                 22:33:30
                                                                            22:33:36
  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.1.104:3000/

ℹ Vite client warmed up in 10499ms                                          22:33:56

 ERROR                                                                nitro 22:33:56

undefined

✔ Nitro built in 1434 ms
```

This isn't a very helpful error message when you have tens or hundreds of `server/api` files, and you have to find which file has a broken import. At the very least, the error message should tell which file in the project has the broken import.

### Additional context

I believe the `next` CLI has a good example of what an appropriate error message for this scenario would be:

```
wait  - compiling...
error - ./src/pages/api/hello.ts:3:0
Module not found: Can't resolve 'path/to/nowhere'
  1 | // Next.js API route support: https://nextjs.org/docs/api-routes/introduction
  2 | import type { NextApiRequest, NextApiResponse } from "next"
> 3 | import { someObj } from "path/to/nowhere"
  4 | 
  5 | type Data = {
  6 |   name: string

https://nextjs.org/docs/messages/module-not-found
```

The output doesn't have to be as fancy. It just needs to be helpful and let the user know where the error is coming from, so they can fix it.

**Comment by manniL** [comment]
This is improved now and shows a rollup error 👍🏻

<img width="820" alt="image" src="https://github.com/nuxt/nuxt/assets/640208/f2ecceca-e519-476d-9c1a-b9a07f9dae7c">
