### ISSUE TITLE
Correctly type `useFetch` based on the method 

### ISSUE THREAD

**Issue by genu** [nuxt/nuxt#18492]
### Describe the feature

Distinguishing types has been has been implemented in: https://github.com/unjs/nitro/pull/686 I'm wondering if a similar feature should be added to `useFetch`?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/15280.
