### ISSUE TITLE
Nuxt 3 swallows log output after building

### ISSUE THREAD

**Issue by dword-design** [nuxt/nuxt#18498]
### Environment

Nuxi 3.1.0                                                                                                                00:58:57
                                                                                                                          00:58:57
RootDir: /workspace/tester-plugin-nuxt-config                                                                             00:58:57
Nuxt project info:                                                                                                        00:58:57

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.21.2`
- Nuxt Version:     `3.1.0`
- Nitro Version:    `2.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                               00:58:57

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Reproduction

Write two Mocha tests. In the first, build Nuxt 3. In the second, do anything.

### Describe the bug

When building Nuxt 3 programmatically, all console output is wrapped. But this has side effects since also all outputs after the build is wrapped. Currently, when using Nuxt 3 programmatically in a Mocha test, the Mocha test cases aren't output.

I think this is related to the `logger.restoreAll()` and `logger.wrapAll()` calls.

**Comment by pascalwengerter** [comment]
Just found about this as well because I wanted to check how often a component would run its JS (because my headless CMS has API-call quota I want to not exceed). I see why logs should be "swallowed" (so the build output can be displayed  nicely), but a suggestion would be to maybe display all "happened in the meantime"-log output below that?

**Comment by dword-design** [comment]
My issue is also that not only the log output during Nuxt run is swallowed but also the one after that. Doesn't seem to be intended.

**Comment by dword-design** [comment]
Can be closed
