### ISSUE TITLE
Quiet mode

### ISSUE THREAD

**Issue by dword-design** [nuxt/nuxt#18497]
### Describe the feature

In Nuxt 2 you could make the logs quiet by setting `build.quiet` to `true` in `nuxt.config.js`. But I can't find such an option for Nuxt 3. I use it programmatically a lot and want to mute the logs.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by Baroshem** [comment]
What about using logLevel option from Vite config and set it to silent?

https://nuxt.com/docs/api/configuration/nuxt-config/#loglevel

**Comment by manniL** [comment]
Also another option is to send the logs straight to `/dev/null` (in case of standalone usage), e.g. `pnpm dev &>/dev/null`

**Comment by dword-design** [comment]
@Baroshem As far as I remember there were two loggers in use by Nuxt, the one from Vite and another one when setting up Nitro. `logLevel` only sets the one for Vite, so there is still log output.

@manniL Yes that's possible if it is run standalone 🙂. But I run it during tests and I pass the Nuxt config directly as a JS object and this isn't possible with the CLI if I'm not mistaken.
