### ISSUE TITLE
pages folder name first letter register

### ISSUE THREAD

**Issue by isgleb** [nuxt/nuxt#18502]
### Describe the feature

Project with pages folder named as "Pages" works fine with dev and production mode. But things change when project is packed into docker container, then pages of app don't load without any exceptions, etc. There might have been a kind of foolproof check which won't let dev and prod modes load pages with wrong folder register.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by Laruxo** [comment]
@isgleb I believe the `pages` folder has to be lower-case. Could it be an issue with your OS being case insensitive, while docker container is probably case-sensitive?

**Comment by isgleb** [comment]
> @isgleb I believe the `pages` folder has to be lower-case. Could it be an issue with your OS being case insensitive, while docker container is probably case-sensitive?

I've got macOs BigSur 11.6.7. I've never noticed if it is insensitive.

**Comment by danielroe** [comment]
Great. I've added an item to https://github.com/nuxt/nuxt/issues/14980; we can track there for a feature to detect this.
