### ISSUE TITLE
async server components are not rendered in initial HTML

### ISSUE THREAD

**Issue by madebyfabian** [nuxt/nuxt#18500]
### Environment

RootDir: /home/projects/github-aegvia        
Nuxt project info:                                    

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.1.0`
- Nitro Version:    `2.0.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `experimental`, `modules`
- Runtime Modules:  `nuxt-graphql-client@0.2.24`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-aegvia

### Describe the bug

When using the new server islands, as soon as you use a method from a module, it results in a hydration mismatch, even if the html template is not using the data. Check the reproduction for a working and not-working example.

![Bildschirm­foto 2023-01-25 um 08 07 36](https://user-images.githubusercontent.com/32813692/214501434-4da7d7c5-ecc2-499f-ba42-c7148b113d39.jpg)

Works fine:
```vue
<template>
	<div>This component will only be rendered on the server.</div>
</template>

<script setup lang="ts">
	console.log('Server only!')
</script>
```

Also works fine:
```ts
// utils/example.ts
export const example = () => { return true }
```
```vue
<template>
	<div>This component will only be rendered on the server.</div>
</template>

<script setup lang="ts">
	const exampleRes = example()
	console.log('Server only!', { exampleRes })
</script>

```

Hydration mismatch (e.g. using another packages method, e.g. `nuxt-graphql-client`'s `useAsyncGql` method).
```vue
<template>
	<div>This component will only be rendered on the server.</div>
</template>

<script setup lang="ts">
	const { data, error } = await useAsyncGql({
		operation: 'ListPosts',
	})
	console.log('Server only!', { data: data.value, error: error.value })
</script>
```

So it seems that there are issues in server-components when using composables from other packages. The `useAsyncGql` composable should work here because it is one that runs on the server + client normally. So it should not be the cause.

Let me know what to add to the reproduction to test when a hydration error happens and when not.

**Comment by madebyfabian** [comment]
Info: Not resolved in current edge, so it's indeed something different than https://github.com/nuxt/nuxt/issues/18491

```
Nuxi 3.1.1-rc.0-27910725.fdb31f4
Nuxt 3.1.1-rc.0-27910725.fdb31f4 with Nitro 2.0.0-27909628.d73998e  
```

**Comment by danielroe** [comment]
Yes, we certainly need to fix this. The root cause is an upstream Vue bug (https://github.com/vuejs/core/issues/6207) - until we work around this, your server components will need to be non-async.

**Comment by madebyfabian** [comment]
@danielroe Thanks for the info, I've created a PR to add an info into the docs: https://github.com/nuxt/nuxt/pull/18513
