### ISSUE TITLE
babel plugin(babel-plugin-istanbul) is not work in nuxt3

### ISSUE THREAD

**Issue by sunnywanggit** [nuxt/nuxt#18503]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/sunnywanggit/babel-plugin-in-nuxt3

### Describe the bug

babel plugin(babel-plugin-istanbul) is not work in nuxt3。nuxt.config.ts below:

```js

export default defineNuxtConfig({
  ......   
  babel: {
    plugins: ['istanbul',]
  },
  ......
})
```

babel-plugin-istanbul version is 6.1.1。

**Comment by danielroe** [comment]
Nuxt 3 does not use babel by default, and does not have a `babel` config option.

**Comment by sunnywanggit** [comment]
Does webpack loader support ？ @danielroe

**Comment by manniL** [comment]
@sunnywanggit You can use webpack5 instead of vite, yes.
