### ISSUE TITLE
baseURL not taking effect on component props

### ISSUE THREAD

**Issue by Tragio** [nuxt/nuxt#18508]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.1.0`
- Nitro Version:    `2.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `ssr`, `app`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/Tragio/nuxt3-baseurl-props with `yarn deploy`

**Live Test:**
https://tragio.github.io/nuxt3-baseurl-props/index.html

### Describe the bug

Using the following:

```js
export default defineNuxtConfig({
  ssr: false,
  app: {
    buildAssetsDir: "app/",
    baseURL: "/nuxt3-baseurl-props/",
  },
});
```

The `baseUrl` is taking effect on all assets except on component props.

**Comment by danielroe** [comment]
How would Nuxt/Vite know to inject the base url in a particular component prop? There is no way to tell that that prop is meant to refer to a public file. So I don't think this is a bug, but you are welcome to do it in your own component, by checking `useRuntimeConfig().app.baseURL`, and maybe using the `joinURL` utility from `ufo`.

**Comment by Tragio** [comment]
> How would Nuxt/Vite know to inject the base url in a particular component prop? There is no way to tell that that prop is meant to refer to a public file. So I don't think this is a bug, but you are welcome to do it in your own component, by checking `useRuntimeConfig().app.baseURL`, and maybe using the `joinURL` utility from `ufo`.

Hmmm ok, I thought that by detecting a relative path in a prop (and in this case in an src of an image) it should append the baseUrl. Anyway, you already gave me the light of a workaround. Thank you very much for your amazing work and support!
