### ISSUE TITLE
Root div class of layout child component missing

### ISSUE THREAD

**Issue by tada5hi** [nuxt/nuxt#18509]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.1.0`
- Nitro Version:    `2.0.0`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-cg71hh?file=package.json

### Describe the bug

The class of the root div of a child component  (`sidebar.vue`) , which is served by  the layout component (`default.vue`),  disappears aka is not rendered when upgrading from nuxt v3.0.0 to v3.1.0.

**Comment by tamutus** [comment]
Seems to be relevant to which element the root is. If you change the `<div>` to a `<p>` then the class is properly applied.

**Comment by manniL** [comment]
This should be resolved in v3.1.1 via https://github.com/nuxt/nuxt/pull/18494

**Comment by tada5hi** [comment]
can confirm :thumbsup:
