### ISSUE TITLE
Using defineNuxtComponent and components:false causes hydration mismatches error

### ISSUE THREAD

**Issue by sugitata** [nuxt/nuxt#18511]
### Environment

- Operating System: Darwin
- Node Version: v16.14.2
- Nuxt Version: 3.1.0
- Nitro Version: 2.0.0
- Package Manager: npm@7.17.0
- Builder: vite
- User Config: components
- Runtime Modules: -
- Build Modules: -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-ffmmnf?file=package.json

### Describe the bug

When using `defineNuxtComponent` and `components: false` manually causes Hydration error like above reproduction.
This error doesn't appear at 3.0.0.

```vue
// e.g. layout
<template>
  <div>
    layout
    <Foo />
  </div>
</template>

<script lang="ts">
import { defineNuxtComponent } from '#imports';
import Foo from '~/components/Foo.vue';

export default defineNuxtComponent({
  name: 'default',
  components: {
    Foo,
  },
});
</script>

// foo component
<template>
  <div>foo</div>
</template>

<script lang="ts">
import { defineNuxtComponent } from '#imports';

export default defineNuxtComponent({
  name: 'Foo',
});
</script>

```

### Logs

```shell-script
vue.js?v=4752a486:1355 [Vue warn]: Hydration text content mismatch in <div>:
- Client: 
- Server: foo 
  at <Foo> 
  at <Default > 
  at <LayoutLoader key="default" name="default" hasTransition=false > 
  at <FragmentWrapper > 
  at <NuxtLayout> 
  at <App key=2 > 
  at <NuxtRoot>
```
```

**Comment by lucassimines** [comment]
@sugitata This issue has been resolved in https://github.com/nuxt/nuxt/pull/18494, to fix it, try the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/).

**Comment by sugitata** [comment]
@lucassimines 
Oh, got it. Thank you for letting me know!
