### ISSUE TITLE
Root element of .client components missing own data scope on site load

### ISSUE THREAD

**Issue by tamutus** [nuxt/nuxt#18521]
### Environment

Nuxt project info:                                                                                                                                                                  14:07:45

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.12.0`
- Nuxt Version:     `3.1.0`
- Nitro Version:    `2.0.0`
- Package Manager:  `npm@8.12.1`
- Builder:          `vite`
- User Config:      `app`, `components`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

[Repro Repo](https://github.com/tamutus/nuxt3-clientonly-missing-data)

### Describe the bug

What follows below is the same as the repo readme:

### Nuxt 3 bug reproduction: Client-only component's root element missing data attribute for itself.

To reproduce this bug, I created a new nuxt 3 project, set up two pages with links to each other, and added two components: one with a root element that has a class, which successfully applies relevant styles, and a clone of that component suffixed with `.client.vue` . When you load the app or manually enter a URL, both data nonces (for the parent and child component style scopes) load correctly for the root element of the normal component in question. The .client-suffixed component fails to do this on app load, and instead has only the style scope data attr from the parent component/page. Yet, the behavior will be the same as the regular component upon file-save HMR or navigation between pages. As refreshing resets the app, the orange text will lose its style.

I noticed that this can be solved by simply not applying scoped styles to the root component - making the current easiest workaround to wrap the contents of the component in a plain old `<div>`.
![image](https://user-images.githubusercontent.com/6070594/214666817-53fac037-b4df-4e36-bf58-2636e940f163.png)

**Comment by niklaswolf** [comment]
I see exactly the same when using `<client-only> ...</client-only` in a template of a component.
But when I changed it to `<clientOnly>...</clientOnly>` it works again...
But with `<ClientOnly>...</ClientOnly>` it does not work... super strange behaviour!

**Comment by danielroe** [comment]
I think this is the same issue as https://github.com/nuxt/nuxt/issues/15227. There is a PR pending to resolve it, which we should merge soon.
