### ISSUE TITLE
hope nuxt3 support webpack loader

### ISSUE THREAD

**Issue by sunnywanggit** [nuxt/nuxt#18531]
### Describe the feature

hope nuxt3 support webpack loader

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Yes, there's a webpack builder. Install it (`@nuxt/webpack-builder`) and enable it by setting `builder: 'webpack'` in your Nuxt config.
