### ISSUE TITLE
Nuxt 3 useFetch - nuxt instance unavailable when using useFetch at least twice in one function

### ISSUE THREAD

**Issue by mkierdev** [nuxt/nuxt#18539]
### Environment

Nuxt 3.0 / Nuxt 3.1
Linux
Node 16

### Reproduction

https://stackblitz.com/edit/github-qe9ulj?file=app.vue

### Describe the bug

When we try to use useFetch at least twice in a function, we often get server error in console saying:

```
[nitro] [dev] [unhandledRejection] Error: nuxt instance unavailable    
```

**Comment by kuohuanhuan** [comment]
Don't mix `async` and `await`.

Simply use ```vue
<template>
  <div>
    <NuxtWelcome />
  </div>
</template>

<script setup>
const { data, error } = await useFetch('https://api.publicapis.org/entries');
const { data: data2, error: error2 } = await useFetch(
  'https://api.publicapis.org/entries'
);
</script>
```

**Comment by danielroe** [comment]
After calling `useFetch` within a function the context is lost - it should be called either directly within your setup block (in which case the context will be preserved - or you can use `callWithNuxt`. More info here: https://github.com/nuxt/nuxt/issues/14269#issuecomment-1397352832.

**Comment by mkierdev** [comment]
> Don't mix `async` and `await`.
> 
> Simply use
> 
> ``
> <template>
>   <div>
>     <NuxtWelcome />
>   </div>
> </template>
> 
> <script setup>
> const { data, error } = await useFetch('https://api.publicapis.org/entries');
> const { data: data2, error: error2 } = await useFetch(
>   'https://api.publicapis.org/entries'
> );
> </script>
> ```

[kuohuanhuan](https://github.com/kuohuanhuan) it doesn't change anything, the app will start but you will still get error in console as I said in the reproduction..

**Comment by mkierdev** [comment]
> After calling `useFetch` within a function the context is lost - it should be called either directly within your setup block (in which case the context will be preserved - or you can use `callWithNuxt`. More info here: [#14269 (comment)](https://github.com/nuxt/nuxt/issues/14269#issuecomment-1397352832).

@danielroe so why it's working with one useFetch call? Shouldn't we use useFetch inside functions?

**Comment by danielroe** [comment]
No. You can use `$fetch` instead - useFetch is a composable that is meant to be used within a setup function. Do read the comment I linked - it explains this in more detail.

**Comment by kuohuanhuan** [comment]
> > Don't mix `async` and `await`.
> > Simply use
> > ``
> > 
> >   
> >     
> >   
> > 
> > <script setup>
> > const { data, error } = await useFetch('https://api.publicapis.org/entries');
> > const { data: data2, error: error2 } = await useFetch(
> >   'https://api.publicapis.org/entries'
> > );
> > </script>
> 
> [kuohuanhuan](https://github.com/kuohuanhuan) it doesn't change anything, the app will start but you will still get error in console as I said in the reproduction..

It works, actually. Put the `useFetch()` method **outside** of a function.

**Comment by mkierdev** [comment]
@danielroe Ok let's assume we switch to $fetch inside function. 
What happens right now is that first when server renders page, the request is made server side. Server returns document with fetched data. However when application mounts, the request is also made client-side. 
When we used useFetch, the request on initial load was made only on server side and it wasn't visible in network tab. Is this correct behavior?

**Comment by danielroe** [comment]
Yes, that is the expected behaviour.

If you are trying to show a composable in your repro, then something like this would likely be better:

```js
function myFunc() {
  const [res1, res2] = await Promise.all([
    useFetch(/* */),
    useFetch(/* */)
  ])
}
```

If you really need the result of first before calling second one (bear in mind this will cause a waterfall and performance cost) then you can use `callWithNuxt` as spelled out in the issue I linked.

**Comment by mkierdev** [comment]
Yes, I am aware of Promise.all, repro was made, well, just for repro ;)

Would approach below (and callWithNuxt in general) incur unwanted performance costs?

```
function myFunc() {
  const [res1, res2] = await Promise.all([
    useApi(endpoint),
    useApi(another_endpoint)
  ])
}

// useApi function
const nuxtApp = useNuxtApp();
const { data } = await callWithNuxt(nuxtApp, useFetch, [`/api/${endpoint}`]);
return data
```

**Comment by danielroe** [comment]
No, that would be fine 👌

**Comment by mkierdev** [comment]
@danielroe it seems that callWithNuxt is still not resolving issue with nuxt instance unavailable.. (initial page load)

```js
// useApi composable
const nuxtApp = useNuxtApp();
const { data } = await callWithNuxt(nuxtApp, useFetch, [`/api/${endpoint}`]);
return data.value

// function inside pinia setup store
const fetchListing = async () => {
  const res1 = await useApi('...')
  // now some logic that has to be performed before res2 call
  const res2 = await useApi('...')
}

// listing.vue (script setup) in pages folder 
await fetchListing()
```

```
[nitro] [dev] [unhandledRejection] Error: nuxt instance unavailable  
```

**Comment by danielroe** [comment]
No, more like this:

```js
// useApi composable
const { data } = await useFetch(`/api/${endpoint}`);
return data.value

// function inside pinia setup store
const fetchListing = async () => {
  const nuxtApp = useNuxtApp();
  const res1 = await useApi('...')
  // now some logic that has to be performed before res2 call
  const res2 = await callWithNuxt(useApi, '...')
}

// listing.vue (script setup) in pages folder 
await fetchListing()
```

**Comment by mkierdev** [comment]
@danielroe Page is getting loaded, however we now can observe this type of warn in console:

```
[Vue warn]: onServerPrefetch is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.   
```
