### ISSUE TITLE
Hyper Fetch (hyper-fetch) got import_events4.default is not a constructor

### ISSUE THREAD

**Issue by johngerome** [nuxt/nuxt#18532]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.1.0`
- Nitro Version:    `2.1.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

1. Go to [hyperfetch-nuxt-demo](https://stackblitz.com/edit/hyperfetch-nuxt-demo?file=pages%2Findex.vue)
2. See error on the preview

### Describe the bug

No error should show

### Additional context

Not sure if this is **Nuxt** or **Hyper Fetch** related issue though.

**Comment by Baroshem** [comment]
Hey,

You should change the way of importing the package like this:

```vue
<script setup>
const { Client } = await import('@hyper-fetch/core').then(
  (lib) => lib.default || lib
);
const client = new Client({ url: 'https://catfact.ninja' });
console.log(res);
</script>
<template>
  <h1>Nuxt + HyperFetch</h1>
</template>
```

Also, Stackblitz link -> https://stackblitz.com/edit/hyperfetch-nuxt-demo-jxgcyv?file=pages%2Findex.vue

**Comment by danielroe** [comment]
You can work around this by telling vite that this module shouldn't be optimised:

```js
export default defineNuxtConfig({
  vite: {
    optimizeDeps: {exclude: ['@hyper-fetch/core'] }
  },
  // or, which will do a little more but will also solve the issue
  build: {
    transpile: ['@hyper-fetch/core']
  }
});
```

Even after doing that, however, it's also true that hyper-fetch doesn't seem to be compatible with browser environment - it imports 'node:events': https://unpkg.com/browse/@hyper-fetch/core@3.2.1/dist/index.esm.js
