### ISSUE TITLE
The requested module 'vue' does not provide an export named 'default'

### ISSUE THREAD

**Issue by stephenjason89** [nuxt/nuxt#18544]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.0`
- Package Manager:  `pnpm@7.26.0`
- Builder:          `vite`
- User Config:      `buildDir`, `srcDir`, `css`, `build`, `vite`, `imports`, `modules`
- Runtime Modules:  `@pinia/nuxt@0.4.6`, `()`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/stephenjason89/nuxt-vuetify-graphql-pinia
just pnpm install then pnpm dev

### Describe the bug

After installing @pinia/nuxt, running pnpm dev produces
<img width="891" alt="image" src="https://user-images.githubusercontent.com/3810177/214812873-35840739-08bc-4166-aa4f-080839b90cb1.png">

### Logs

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/3810177/214813307-affabde8-df00-4c49-bd2a-2be32c7d2256.png">

_No response_

**Comment by danielroe** [comment]
Would you raise this as an issue with pinia instead with a more minimal repro (e.g. no vueitfy)? I don't think this is an issue with Nuxt.

**Comment by stephenjason89** [comment]
Thank you @danielroe

**Comment by stephenjason89** [comment]
@danielroe I tried switching to Yarn instead of PNPM like in the ones on their demo 
https://stackblitz.com/github/piniajs/example-nuxt-3

And it fixes the problem.
Is this behavior still a problem on their end?
I have opened an issue on their github btw

https://github.com/vuejs/pinia/issues/1953

Thank you so much for looking on this matter
