### ISSUE TITLE
Nuxt extends doesn't work with self hosted Gitlab instance

### ISSUE THREAD

**Issue by kewinzaq1** [nuxt/nuxt#18540]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.1.0`
- Nitro Version:    `2.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `extends`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-wfxuxw?file=nuxt.config.ts

### Describe the bug

Currently isn't possible to extend the Nuxt project by remote source from self-hosted Gitlab instance

**Comment by danielroe** [comment]
Let's track the upstream issue in https://github.com/unjs/giget/issues/78.

**Comment by trdln** [comment]
@danielroe There is no information about this in docs, is there a way to implement in nuxt now?
