### ISSUE TITLE
useStorage().getItem not working. 

### ISSUE THREAD

**Issue by leosin** [nuxt/nuxt#18549]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-3s2e1z?file=app.vue

### Describe the bug

![image](https://user-images.githubusercontent.com/3676670/214839773-6214eea1-a494-4bff-96c5-89d229687c2d.png)

After upgrading to 3.1.1, the method of using the server to read the json file cannot work. Is it a bug or is there another new way?

As of v3.0, it is working

**Comment by harlan-zw** [comment]
Not sure what has changed exactly, but you can use the key `'root:server:assets:db.json'`

Also you can always debug the keys by using the getKeys() function. See https://stackblitz.com/edit/github-3s2e1z-phu4tf?file=server/api/index.ts

**Comment by leosin** [comment]
It does work using 'root:server:assets:db.json'
thank you very much 👍

**Comment by sewalsh** [comment]
I just ran into this same error.

Whilst the `'root:server:assets:` prefix works in dev, the production build of the application omits these assets.
