### ISSUE TITLE
Feat: Expose `defineNitroPlugin` from `#imports`.

### ISSUE THREAD

**Issue by codebender828** [nuxt/nuxt#18556]
### Describe the feature

Currently, when creating a new Nuxt module using `npx nuxi init -t module my-module`, the developer may choose to create a nitro plugin as part of the module runtime.

However `defineNitroPlugin` is not exposed by the `#imports`, albeit defined in the docs. As a workaround, in order to define a server-side nitro plugin, one needs to manually stub the function's type from `"nitropack"`. For example:

**In server runtime: `<root>/src/runtime/my-nitro-plugin.server.ts`**
```ts
import type { NitroApp } from "nitropack"

// type stub
type NitroAppPlugin = (nitro: NitroApp) => void

function defineNitroPlugin(def: NitroAppPlugin): NitroAppPlugin {
  return def
}

// Export runtime plugin
export default defineNitroPlugin((nitroApp) => {
  console.log("my module nitro logic runs here")
})
```
**In nuxt module: `<root>/src/module.ts`**
```ts
import { defineNuxtModule, createResolver, addServerPlugin } from "@nuxt/kit"

export default defineNuxtModule({
  meta: {
    name: "my-module",
    configKey: "myModule",
    compatibilty: ">=3.0.0",
  },
  setup(_, nuxt) {
    const { resolve } = createResolver(import.meta.url)
    const runtimeDir = resolve("./runtime")
    nuxt.options.build.transpile.push(runtimeDir)

   // Adds server-side plugin to module.
    addServerPlugin(resolve(runtimeDir, "my-module.server"))
  },
})

```

A live example can be found [here](https://github.com/nuxt-modules/emotion/blob/6b541d9645418e8bd9b6822723e977c54ed38b20/src/runtime/emotion.server.ts#L4-L23) and [here](https://github.com/nuxt-modules/emotion/pull/21#issue-1551241885)

The desired solution would be to simply import `defineNitroPlugin` without stubbing the module.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by harlan-zw** [comment]
You need to import it from `#internal/nitro`, ideally it would be more intuitive though

**Comment by pi0** [comment]
This seems like an unintended bug if global types of nitro are not already exposed with internal typedef helper.

**Comment by danielroe** [comment]
The global types of nitro are exposed but what would be helpful is for nitro to expose an alias of `#imports` in its generated `tsconfig.json` paths, so we can directly import from there.
