### ISSUE TITLE
SSR redirect to same route without trailing slash returns 302 but no Location header

### ISSUE THREAD

**Issue by ydnar** [nuxt/nuxt#18561]
### Environment

- Operating System: `Darwin`
- Node Version:     `v19.0.1`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.0.0`
- Package Manager:  `pnpm@7.26.0`
- Builder:          `vite`
- User Config:      `modules`, `vite`, `runtimeConfig`, `css`, `app`, `hooks`, `content`, `i18n`
- Runtime Modules:  `@nuxt/content@2.3.0`, `@nuxtjs/i18n@8.0.0-beta.7`
- Build Modules:    `-`

### Reproduction

Minimal reproduction middleware that fails to produce a valid HTTP 301 or 302 response during server-side rendering:

```js
// Redirect trailing slashes, preserving query string: /foo/ -> /foo
export default defineNuxtRouteMiddleware((to, from) => {
	if (to.path.length > 1 && to.path.slice(-1) === '/') {
		const path = to.path.replace(/\/+$/, '') || '/'
		return navigateTo({ path, query: to.query, hash: to.hash }, { redirectCode: 301 })
	}
}
```

### Describe the bug

The current Nuxt version (3.1.1) will return an invalid HTTP response during SSR if a redirect to the same route happens within `defineNuxtRouteMiddleware`. The HTTP response contains a status code of `301` or `302`, but no `Location` header.

### Additional context

It seems like the issue is here, where the router plugin uses `ufo.isEqual` in non-strict mode, which considers `/about/` and `/about` to be the same:

https://github.com/nuxt/nuxt/blob/64b835c70701c8f27debe8a534ec99034bda812b/packages/nuxt/src/app/plugins/router.ts#L251-L256

### Logs

```shell-script
❯ curl -vvv http://localhost:3000/about/
*   Trying 127.0.0.1:3000...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /about/ HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.86.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Access-Control-Allow-Origin: *
< content-type: text/html;charset=utf-8
< x-powered-by: Nuxt
< date: Thu, 26 Jan 2023 16:27:36 GMT
< connection: close
< content-length: 22456
<
<!DOCTYPE html>
<html >
...
```

**Comment by manniL** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/18561 because it has a pending PR 🙏
