### ISSUE TITLE
show 404 error page when client-side navigation fails due to `validate()` function

### ISSUE THREAD

**Issue by noriyuki-shimizu** [nuxt/nuxt#18567]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.0`
- Package Manager:  `pnpm@7.26.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

In the pages vue file, I used definePageMeta and declared validate.

* pages/example/index.vue
```ts
definePageMeta({
  validate: (route) => {
    return false
  }
})
```

At that time, if you try to page transition (NuxtLink) with a URL that violates the validate constraint, there is no response.

* pages/index.vue
```vue
<NuxtLink to="example">Example page</NuxtLink>
```

Also the middleware defined in the pages vue file and the global middleware doesn't work either.

* pages/index.vue
```ts
definePageMeta({
  validate: (route) => {
    return false
  },
  middleware: (to) => {
    console.log('Do not work.')
  }
})
```

* middleware/example.global.ts
```ts
export default defineNuxtRouteMiddleware((to) => {
  console.log('Do not work.')
})
```

### Describe the bug

I think that the processing in `packages/nuxt/src/pages/runtime/validate.ts` is probably doing something wrong.

```ts
import { defineNuxtRouteMiddleware } from '#app'

export default defineNuxtRouteMiddleware(async (to) => {
  if (!to.meta?.validate) { return }

  const result = await Promise.resolve(to.meta.validate(to))
  if (result === true) {
    return
  }
  return result
})
```

I think the problem will be solved if showError is returned only when there is an error.

```ts
import { showError, defineNuxtRouteMiddleware } from '#app'
export default defineNuxtRouteMiddleware(async (to) => {
  if (to.meta?.validate) {
    const result = await Promise.resolve(to.meta.validate(to))
    if (result === false) {
      return showError({ statusCode: 404, message: 'This page could not be found' })
    }
  }
})
```

If there is no problem with this fix, I will file a PR, is there any problem?

### Additional context

I am currently upgrading from Nuxt2 to Nuxt3.
If there is a problem that the screen transition is not possible and the middleware does not work when the validate limit is violated, the amount of modification of the project will be very large.:bow:

**Comment by danielroe** [comment]
The description [from the docs](https://nuxt.com/docs/getting-started/routing#route-validation) is:

> If you return false, and another match can't be found, this will cause a 404 error. You can also directly return an object with statusCode/statusMessage to respond immediately with an error (other matches will not be checked).

Is this not working for you?

I do understand that clicking an internal link to a page that does not exist, simply does not navigate to it. I imagine you would like instead a 404 error to be thrown? Is there a reason that returning an object as indicated is not working for you?

**Comment by noriyuki-shimizu** [comment]
> Is this not working for you?

I'm having trouble getting it to work as described in the documentation when I actually run it.
The behavior when defining a validate of definePageMeta in the vue file of pages is as follows.

* For page transitions from `NuxtLink`.
  * Returns false, no other matches found, but no 404 error
* If you enter the URL directly and browse the screen
  * Returns false and no other matches are found, resulting in a 404 error

Sorry if this is not an answer to your question.
Please confirm. :bow:

**Comment by noriyuki-shimizu** [comment]
Let me confirm about the correct move!
If a screen transition from <NuxtLink> violates a validation limit, is it correct that the screen transition cannot occur?
Or is the correct behavior to display a 404 screen when a validation limit is violated?
(I believe Nuxt2 displays a 404 screen when a validation limit is violated.)

**Comment by danielroe** [comment]
Probably the most intuitive behaviour should be:

- For page transitions from NuxtLink.
   > ✅ Returns true, successfully navigates to that page page
   > ✅ Returns false, other matches found, successfully navigates to other page
   > ❌ Returns false, no other matches found, 404 error
- If you enter the URL directly and browse the screen
   > ✅ Returns false and no other matches are found, resulting in a 404 error

Having said that, this is not what happens at the moment with `vue-router` when navigating to a non-existent route, so this would be uniquely nuxt behaviour.

The challenge in implementing this is the second condition I added above: we do need to successfully navigate to another page that _also_ matches the path, even if the `validate` middleware returns false. That is, we can't short-circuit navigation as soon as `validate()` fails. We would somehow have to add another check at the end of processing middleware.
