### ISSUE TITLE
Execution halts when useState is used after awaited function in useAsyncData

### ISSUE THREAD

**Issue by MikeAltinget** [nuxt/nuxt#18568]
### Environment

My pc:
------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.1.0`
- Nitro Version:    `2.0.0`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

Also happens in stackblitz:
------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.1.0`
- Nitro Version:    `2.0.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-zrc5sy?file=components/StateGetter.vue

In this example there are two components that set the state, and one that reads the state.
The only difference between the setters is that useState is called after the awaited function in `StateSetterAfterAwait.vue` and before the awaited function in `StateSetterBeforeAwait.vue`.

Notice that the `console.log` in `StateSetterAfterAwait.vue` is never reached, nor is the state set.

### Describe the bug

When `useState` is called after an awaited function in `useAsyncData`, execution halts.

**Comment by danielroe** [comment]
You should not use `useState` within your `useAsyncData` fetcher function (or indeed, any Nuxt composables). Instead, it should be called in your setup function directly.

**Comment by MikeAltinget** [comment]
Is this mentioned in the docs anywhere? Also I would expect an error/warning, when using them in the wrong place

**Comment by danielroe** [comment]
Yes, we have an open issue to document this: https://github.com/nuxt/nuxt/issues/14723

**Comment by leccyril** [comment]
link to this
https://github.com/nuxt/nuxt/issues/19382
Same issue with useFetch

**Comment by leccyril** [comment]
> You should not use `useState` within your `useAsyncData` fetcher function (or indeed, any Nuxt composables). Instead, it should be called in your setup function directly.

How to use because i use it in vue page for setting user data after getting data, or in init server, have you an exemple how it should be called in await call (useFetch, useLazyFetch etc ?)

**Comment by leccyril** [comment]
finally i made a workaround

```
let username: String;
	let role: String;
	let isConnected: boolean = false;

	//useState('username', ()=>'test');
	if (token !== null && token?.length > 0) {
		await useFetch(REST_API_URL + '/auth/validate', {
			method: 'POST',
			headers: {
				'Authorization': 'Bearer ' + token,
				'Content-Type': 'Application/json'
			},
			onResponse({request, response, options}) {
				// Process the response data
				if (response.status === 200) {
					const payload = parseJwt(token)
					username = payload.username
					role = payload.role
					isConnected = true
				}
			},
			onResponseError({request, response, options}) {
				console.log('token is not valid or expired');
				if (response.status === 400) {
					console.error('token expired or invalid');
				} else {
					console.error('internal issue problem');
				}
				router.push("/")
			},
		});

		if (isConnected) {
			useState('isConnected', () => isConnected);
			useState('username', () => username);
			useState('role', () => role);
		}

	} else {
		console.log('No token registered')

	}
```
