### ISSUE TITLE
Dynamic route navigation triggers onMounted before onUnmounted of previous page

### ISSUE THREAD

**Issue by denys119** [nuxt/nuxt#18569]
### Environment

- Operating System: Linux
- Node version: v16.14.2
- Nuxt Version: 3.1.1
- Nitro Version: 2.1.0
- Package Manager: npm@7.17.0
- Builder: vite
- User Config: app
- Runtime Modules: -
- Build Modules: -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-qnk4ux?file=pages%2F[foo].vue,nuxt.config.ts

### Describe the bug

![image](https://user-images.githubusercontent.com/72434901/215059999-6e18a648-22cb-4a26-b44d-84fc69c71cae.png)

Navigating using dynamic routes (same page component) triggers onMounted of new page before the onUnmounted of previous page.

### Logs

```shell-script
[foo].vue:14 onMounted 5
[foo].vue:18 onUnmounted 4
[foo].vue:14 onMounted 6
[foo].vue:18 onUnmounted 5
[foo].vue:14 onMounted 7
[foo].vue:18 onUnmounted 6
[foo].vue:14 onMounted 8
[foo].vue:18 onUnmounted 7
```

**Comment by danielroe** [comment]
This is a consequence of how Suspense works in Vue 3, which is being tracked as an upstream bug here: https://github.com/nuxt/nuxt/issues/13471
