### ISSUE TITLE
Make `showError()` work with Nitro on `/server/api`

### ISSUE THREAD

**Issue by nakorndev** [nuxt/nuxt#18578]
### Describe the feature

I think it will be better if Nitro in directory `/server/api` can use `showError()` to render `/error.vue` 

Because I faced an issue with getting a callback from login in with Facebook. and then sometimes the user made an error like not providing email and I must tell the user should accept and get an email to me. What I can do is redirect to `/pages/custom-error.vue` with some query string to show an error message instead.

Or it has some solution to make `/server/api` can render `/error.vue` ?

Example of error when trying using `showError()`: https://stackblitz.com/edit/nuxt-starter-da7ien?file=server%2Fapi%2FcreateError.get.ts,server%2Fapi%2FshowError.get.ts

This is caused `showError is not defined`. I know this should be normal because any API must call `throw createError()` but I think It should better if API also can render `/error.vue`

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
An error page will automatically be rendered with `error.vue` if you throw an error. Just `throw createError({})` and you should be good to go.

**Comment by nakorndev** [comment]
> An error page will automatically be rendered with `error.vue` if you throw an error. Just `throw createError({})` and you should be good to go.

I just trying to make a new example: https://stackblitz.com/edit/nuxt-starter-da7ien?file=pages%2Findex.vue I want to make any API to render an `/error.vue` and it won't or am I just missing something? or Nitro can't render this? sometimes I don't want the error to be `application/json` but to be `html/text` instead.

**Comment by danielroe** [comment]
You will get HTML if you visit it in a browser, JSON if you are getting it with httpie or curl.

**Comment by nakorndev** [comment]
I don't know but seem my web browser showing this:

![image](https://user-images.githubusercontent.com/5706431/215114748-85615e21-6e5c-421d-b4b3-15effbaa51d6.png)

**Comment by danielroe** [comment]
Oh, sorry, I didn't realise you were directly hitting the api endpoint. Yes, we explicitly exclude those from rendering a HTML response as we assume that you don't want users explicitly visiting them in a browser. If you move your endpoint to `~/server/routes/some-other-path.ts` then it should work.

**Comment by nakorndev** [comment]
> Oh, sorry, I didn't realise you were directly hitting the api endpoint. Yes, we explicitly exclude those from rendering a HTML response as we assume that you don't want users explicitly visiting them in a browser. If you move your endpoint to `~/server/routes/some-other-path.ts` then it should work.

Thanks, it works! I updated the example in: https://stackblitz.com/edit/nuxt-starter-da7ien

By the way. I think the document should tell this about using `showError()` or `createError()` on `/server/routes` I didn't know about these `/server/routes` and `/server/api` can handle errors like this.

- https://nuxt.com/docs/guide/directory-structure/server#server-routes
- https://nuxt.com/docs/api/utils/create-error#throwing-errors-in-api-routes

**Comment by manniL** [comment]
> By the way. I think the document should tell this about using `createError()` on `/server/routes` I didn't know about these `/server/routes` and `/server/api` can handle errors like this.
> 
>     * [nuxt.com/docs/guide/directory-structure/server#server-routes](https://nuxt.com/docs/guide/directory-structure/server#server-routes)
> 
>     * [nuxt.com/docs/api/utils/create-error#throwing-errors-in-api-routes](https://nuxt.com/docs/api/utils/create-error#throwing-errors-in-api-routes)

PR welcome!

**Comment by nakorndev** [comment]
> > By the way. I think the document should tell this about using `createError()` on `/server/routes` I didn't know about these `/server/routes` and `/server/api` can handle errors like this.
> > ```
> > * [nuxt.com/docs/guide/directory-structure/server#server-routes](https://nuxt.com/docs/guide/directory-structure/server#server-routes)
> > 
> > * [nuxt.com/docs/api/utils/create-error#throwing-errors-in-api-routes](https://nuxt.com/docs/api/utils/create-error#throwing-errors-in-api-routes)
> > ```
> 
> PR welcome!

I want to but my writing skill in English is not strong. 🥲

I hope someone will PR for this on https://nuxt.com/docs/api/utils/create-error#throwing-errors-in-api-routes
