### ISSUE TITLE
Download CMS assets when generating static sites

### ISSUE THREAD

**Issue by pascalwengerter** [nuxt/nuxt#18579]
### Describe the feature

When building my Nuxt site for production, it fetches all the data from a headless CMS (which is a pretty standard use case, I'd say). 
However, images that were uploaded to the headless CMS will reference the CMS's url in the `<img>`'s source attribute, which is not ideal since a) the CMS may charge extra for that usage and/or a custom CDN/asset subdomain and b) it reveals whatever CMS I'm using to someone digging around the source code. 

It would be super cool if Nuxt provided some functionality/guide on how to first download those assets into the `.output/public/` folder and then replace the CMS's urls within the HTML files

### Additional information

- [ ] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
This should be possible with `@nuxt/image`: see https://image.nuxtjs.org/getting-started/static. If you experience any issues, please do raise an issue in https://github.com/nuxt/image directly.

**Comment by pascalwengerter** [comment]
> This should be possible with `@nuxt/image`: see https://image.nuxtjs.org/getting-started/static. If you experience any issues, please do raise an issue in https://github.com/nuxt/image directly.

Damn, wasn't aware of its existance. Thanks for the hint, and sorry for the noise!
