### ISSUE TITLE
typecheck error Cannot find type definition file for 'node'.

### ISSUE THREAD

**Issue by SheetJSDev** [nuxt/nuxt#18572]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `typescript`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

```bash
npx nuxi init nuxtissue
cd nuxtissue
npx yarn install
npx nuxi typecheck
```

### Describe the bug

```
error TS2688: Cannot find type definition file for 'node'.
  The file is in the program because:
    Entry point of type library 'node' specified in compilerOptions


Found 1 error.


 ERROR  Command failed with exit code 2: npx -p vue-tsc -p typescript vue-tsc --noEmit
```

**Comment by pi0** [comment]
A reproduction would be nice. Generally you can fix it by adding `@types/node` as a dev dependency.

**Comment by SheetJSDev** [comment]
The commands to reproduce the issue are in the "Reproduction" section.  To be explicit:

1) open a new terminal window

2) create a new project:

```bash
npx nuxi init nuxtissue
```

3) enter the project directory 

```bash
cd nuxtissue
```

4) install dependencies

```bash
npx yarn install
```

5) try to typecheck

```bash
npx nuxi typecheck
```

https://nuxt.com/docs/api/commands/typecheck#nuxi-typecheck mentions the `typescript` and the `vue-tsc` requirement but not `@types/node`.

**Comment by danielroe** [comment]
💯 Done inhttps://github.com/nuxt/starter/commit/c16b3201c3f70cba9a9eabd49d04cbcacfba5864.

**Comment by danielroe** [comment]
I've also added a comment in the docs: 6b2bc680b06ffbbc7383c428f7e535bdbf1754b9. When we add new `nypm` integration it would be nice to offer to auto-install these dependencies.
