### ISSUE TITLE
Unhandled promise rejection when `asyncData` throws

### ISSUE THREAD

**Issue by rchl** [nuxt/nuxt#18584]
### Environment

```
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  npmPackages:
    @nuxt/postcss8: ^1.1.3 => 1.1.3
    @nuxt/types: ^2.15.8 => 2.15.8
    nuxt: ^2.15.8 => 2.15.8
```

### Reproduction

https://stackblitz.com/edit/github-bxdb1b?file=pages%2Findex.vue

### Describe the bug

When exception is thrown during handling of `asyncData`, Nuxt catches it and shows server error but it also chains returned promise without using `catch`. This results in unhandled promise rejection.

https://github.com/nuxt/nuxt/blob/e5efc259401204888d7bd9aebbc4a7cf646851b6/packages/vue-app/template/server.js#L320-L325

One note: this issue does not manifest in any way whatsoever in plain Nuxt. Node doesn't report unhandled promise error. I'm not sure if that's because vue-server-renderer captures that output or maybe Node 16 just doesn't report those. That said, the promise is in fact unhandled and causes issues when in combination with `@nuxtjs/sentry` where it will make the app crash (whether that's a Sentry issue or not is not really relevant IMO).

**Comment by danielroe** [comment]
resolved in https://github.com/nuxt/nuxt/pull/18585
