### ISSUE TITLE
[request error] [unhandled] [500] Cannot read properties of undefined (reading 'modules')  

### ISSUE THREAD

**Issue by stephenjason89** [nuxt/nuxt#18583]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v19.5.0`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.0`
- Package Manager:  `pnpm@7.26.1`
- Builder:          `vite`
- User Config:      `buildDir`, `srcDir`, `css`, `build`, `imports`, `apollo`, `modules`
- Runtime Modules:  `@nuxtjs/apollo@5.0.0-alpha.5`, `@pinia/nuxt@0.4.6`, `()`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/stephenjason89/nuxt-vuetify-graphql-pinia

### Describe the bug

Using the provided repo,
upgrade nuxt 3.0.0 to 3.1.1 using

nuxt upgrade --force

then pnpm dev
<img width="1710" alt="image" src="https://user-images.githubusercontent.com/3810177/215163149-8b9ad2ef-2518-4729-ac08-063bea7e483f.png">

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/3810177/215160214-297df18e-c687-45a0-916a-7e127ae06dbe.png">

This error happens only on some of my machines like some of my windows laptop and macos laptop.
But weirdly working with my mac studio desktop, last time i checked.

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/18563.
