### ISSUE TITLE
Vercel preset shows the `cloned` page below the current page

### ISSUE THREAD

**Issue by sawa-ko** [nuxt/nuxt#18582]
### Environment

Nuxi 3.1.1                                                                                                                                                                           11:00:29
                                                                                                                                                                                     11:00:30
RootDir: C:/Users/inmor/Documents/Proyectos/biscuit/biscuit-web                                                                                                                      11:00:30
Nuxt project info:                                                                                                                                                                   11:00:30

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v19.3.0`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.0`
- Package Manager:  `pnpm@7.25.0`
- Builder:          `vite`
- User Config:      `modules`, `app`, `runtimeConfig`, `nitro`, `colorMode`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.3.0`, `nuxt-icon@0.2.10`, `@nuxt/image-edge@1.0.0-27907872.f4dd19d`, `@nuxtjs/fontaine@0.2.4`, `@nuxtjs/color-mode@3.2.0`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/oasisjs/biscuit-web

### Describe the bug

The page is displayed cloned below the current page. When I build and run my application using the node-server preset the problem does not appear, but when I deploy with vercel, the problem happens.

So I came to the conclusion that it would be a problem with the vercel preset that nitro uses when deploying with vercel.

### Additional context

![image](https://user-images.githubusercontent.com/56084970/215149161-743abd60-af1d-40f0-848f-52071ff5f6d9.png)

![image](https://user-images.githubusercontent.com/56084970/215149234-0e11b5bd-b766-409e-b6f7-c3fe937a1d12.png)

**Comment by devhus** [comment]
That bug also happens with me a lot dev mode on localhost.

**Comment by sawa-ko** [comment]
@danielroe Hi, can you check this problem?

**Comment by sawa-ko** [comment]
Fixed with latest version ([3.5.3](https://www.npmjs.com/package/nuxt/v/3.5.3))
