### ISSUE TITLE
Not support dynamic slot names

### ISSUE THREAD

**Issue by zc1342303** [nuxt/nuxt#18588]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `build`, `modules`, `hooks`, `proxy`, `vue`, `components`, `typescript`, `vite`, `plugins`, `css`
- Runtime Modules:  `@nuxtjs-alt/proxy@2.1.0`, `@fullpage/nuxt-fullpage@0.2.3`, `@pinia-plugin-persistedstate/nuxt@1.0.0`, `@pinia/nuxt@0.4.5`
- Build Modules: 

### Reproduction

https://stackblitz.com/edit/github-xbmezj?file=components/custom-button.vue

### Describe the bug

According to the Vue3 documentation [dynamic slot names](https://vuejs.org/guide/components/slots.html#dynamic-slot-names) section, I wrote the following line:

``<template v-slot:[slot[0]]>``

But I got some error:

`` [vite] Internal server error: Codegen node is missing for element/if/for node. Apply appropriate transforms first. ``

**Comment by madebyfabian** [comment]
This is not a nuxt issue, but wrong syntax, see https://github.com/vuejs/core/issues/5748. Can be closed.

**Comment by manniL** [comment]
@madebyfabian Could you briefly explain your reasoning? I don't see the connection between the linked issue an this one yet, as no `v-if` is in use here.
