### ISSUE TITLE
Default `favicon.ico`

### ISSUE THREAD

**Issue by Atinux** [nuxt/nuxt#18595]
Nuxt could give a default `/favicon.ico` is not present in user `public/` directory.

Default: https://raw.githubusercontent.com/nuxt/nuxt.new/main/src/public/favicon.ico

**Comment by danielroe** [comment]
Nitro should already be rendering a transparent gif as a favicon (preventing a second render of HTML page when users do not yet have `pages` directory): https://github.com/unjs/nitro/blob/917c7e6fec1aaa24640312a0eaf8e793721ef0a2/src/runtime/renderer.ts#L18-L24

Are you suggesting instead we have a little Nuxt logo if a user hasn't created their own?

**Comment by pi0** [comment]
If we want to use Nuxt logo as default, I think we might explicitly add a Nuxt logo to the starter boilerplate instead. There are various ways to define (or render) web app icon.

**Comment by Atinux** [comment]
Added in the starters
