### ISSUE TITLE
build(cloudflare): assets bundled in server entrypoint

### ISSUE THREAD

**Issue by oritwoen** [nuxt/nuxt#18608]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.19.0`
- Nuxt Version:     `3.1.0`
- Nitro Version:    `2.1.0`
- Package Manager:  `pnpm@7.26.2`
- Builder:          `vite`
- User Config:      `app`, `modules`, `css`, `i18n`, `build`, `vite`, `routeRules`, `experimental`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.6`, `@nuxtjs/strapi@1.7.1`, `@nuxtjs/fontaine@0.2.4`, `@nuxtjs/web-vitals@0.2.2`, `@unocss/nuxt@0.49.1`, `@vueuse/nuxt@9.11.1`, `@formkit/nuxt@1.0.0-beta.11`
- Build Modules:    `-`
------------------------------

### Reproduction

Upgrade `Nuxt` from `3.0.0` to `3.1.0` in the client application and run:

`NITRO_PRESET=cloudflare pnpm build`

Unfortunately I can't share the code because it's private. Later I will try to check if the deployments with [nuxt.new](https://nuxt.new/) and versions 3.0.0 and 3.1.0 are the same size.

### Describe the bug

I updated Nuxt to 3.1.0 in the client app and Gitlab CI stopped working. After checking, it turned out that the size of the bundle has increased by over 1000 percent and cloudflare returns an error with such a large deployment.

#### Nuxt 3.0.0
- Bundle size: 1.21 MB

#### Nuxt 3.1.0
- Bundle size: 13.7 MB

![Zrzut ekranu z 2023-01-29 23-30-21](https://user-images.githubusercontent.com/18102267/215359653-26a321d3-d41b-46c2-a8cd-edd567e631e6.png)
![Zrzut ekranu z 2023-01-29 23-30-53](https://user-images.githubusercontent.com/18102267/215359654-ca6bea79-4090-44ff-8499-84c356a90591.png)

**Comment by danielroe** [comment]
cc: @pi0

**Comment by danielroe** [comment]
Would you let me know the difference between `.nuxt/dist` between 3.0.0 and 3.1.0 for you?

**Comment by pi0** [comment]
Mainly i think Rollup 3 / Vite behavior might have affected and build missed to mock an unused server dependency for CF. An output of `nuxt analyize` command (`NITRO_PRESET=cloudflare pnpm nuxt analyze playground`) would be helpful if you cannot share your current codebase as reproduction.

**Comment by oritwoen** [comment]
@danielroe in `.nuxt/dist` version 3.1.0 the difference is that there are no files other than javascript in the `.nuxt/dist/server` folder. No folders with CSS files, images or any other extensions. Apparently everything was compiled to JS when there were separate image files/assets and folders in 3.0.0.

@pi0 A very strange thing. After performing the analysis you asked for, it appears that all image files have been included in the server bundle and increased size several times for some reason.

For example, the file marked in the screenshot normally takes ~500kb.

![Zrzut ekranu z 2023-01-30 13-06-10](https://user-images.githubusercontent.com/18102267/215472987-fa0e3021-7163-4614-967d-9f6cb6fc239f.png)

![Zrzut ekranu z 2023-01-30 13-09-13](https://user-images.githubusercontent.com/18102267/215473413-b7fdb9f5-66f2-4924-a44d-2638bcc18e37.png)

**Comment by pi0** [comment]
Do you by any chance store them in top level `assets/` dir?

**Comment by pi0** [comment]
Please upgrade Nuxt and Nitro using `npx nuxi upgrade --force`.

Nitropack `2.1.1` (https://github.com/unjs/nitro/pull/893) is likely to resolve it.

**Comment by oritwoen** [comment]
Yes, and indeed all the assets from `/assets` were bundled into the server bundle in `3.1.0` and apparently they weren't in `3.0.0`.

I confirm that nitropack 2.1.1 (https://github.com/unjs/nitro/pull/893) resolve the problem after: `npx nuxi upgrade --force`

Thank you!
