### ISSUE TITLE
nuxt-icon module in parent page makes setup script runs twice when child's route changes.

### ISSUE THREAD

**Issue by teamboot88** [nuxt/nuxt#18604]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.19.0`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.0`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `app`, `modules`, `imports`, `css`, `proxy`
- Runtime Modules:  `nuxt-icon@0.2.10`, `nuxt-proxy@0.3.12`, `@pinia/nuxt@0.4.6`
- Build Modules:    `-`

### Reproduction

[https://stackblitz.com/edit/github-dgdjfn-hhmxav?file=pages/[username]/index/posts.vue](https://stackblitz.com/edit/github-dgdjfn-hhmxav?file=pages/%5Busername%5D/index/posts.vue)

### Describe the bug

Icon in parent page makes setup script runs twice when child route.

**Comment by Atinux** [comment]
Can you please open the issue on nuxt-modules/icon?
