### ISSUE TITLE
How to disable modulepreload/prefetch or limit the amount of requests?

### ISSUE THREAD

**Issue by sh0ber** [nuxt/nuxt#18600]
### Discussed in https://github.com/nuxt/nuxt/discussions/16231

<div type='discussions-op-text'>

<sup>Originally posted by **jshimkoski** December  1, 2022</sup>
After a production build, over 100 `<link rel="modulepreload">...` and `<link rel="preload">...` tags are injected into the head of the page. They are killing initial page load performance of the app in a major way.

For reference, the Nuxt 2 version of the app can load in about 1 second (with a bundle about 3 times the size of the Nuxt 3 bundle). In Nuxt 3, the same app takes close to 4 seconds to load. I've isolated the issue to the excessive inclusion of these preload `link` elements.

Is there a quick configuration option or some other solution that will disable or limit the amount of these elements that are generated?</div>

**Comment by sh0ber** [comment]
This is a critically necessary feature to prevent Nuxt 3 from killing performance scores / LCP. In my testing, Nuxt 3 underperforms a similarly structured Nuxt 2 app despite being smaller and having fewer requests. It's damaging my Lighthouse scores considerably.

Please give an option to disable preload/prefetch on everything so I don't have to do it manually.

**Comment by edwh** [comment]
There has been quite a lot of related discussion, and I don't know much about Nuxt/Vite internals.  So it's possible I've missed or misunderstood something, but it does appear to be that everything is being preloaded.  

I can see the advantage of preload, but in larger apps where there are many pages which may never be accessed in a particular site visit, this doesn't seem at all ideal.  Even if it is done when the browser thinks it is idle it's extra CPU and network load.  For example, on mobile networks it will use up people's data allowance retrieving stuff they'll never need.

It would be better if it was possible to control what was preloaded, though I don't understand the internals well enough to know what's feasible.  For example:
- Turn it off entirely (a sledgehammer)
- Identify a set of routes to preload, along with components below them.
- Specify limits or depth limits on reloading.
- Specify a set of resources to be preloaded based on the entry point.

I tried the change in https://github.com/nuxt/nuxt/discussions/16231#discussioncomment-4293410 from @jshimkoski using patch package, but I couldn't get that to work.

**Comment by manniL** [comment]
Closing here in favor of	https://github.com/nuxt/nuxt/issues/14584
