### ISSUE TITLE
Define $fetch default values in the Nuxt Config

### ISSUE THREAD

**Issue by Semvrij** [nuxt/nuxt#18607]
Define $fetch default values, such as HTTP headers, in the Nuxt Config.

See: [ofetch  - Create fetch with default options](https://github.com/unjs/ofetch#%EF%B8%8F-create-fetch-with-default-options)

https://github.com/nuxt/nuxt/blob/1211f62d41b54592dd3bc0d9db62ef9ca0296177/packages/nuxt/src/app/entry.ts#L18

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/14936.
