### ISSUE TITLE
in dev mode, `x-forwarded-for` header value is rewritten

### ISSUE THREAD

**Issue by Irelynx** [nuxt/nuxt#18609]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v18.6.0`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `typescript`, `runtimeConfig`, `modules`, `content`
- Runtime Modules:  `@nuxt/content@2.4.2`
- Build Modules:    `-`

### Reproduction

Can't reproduce on StackBlitz or CodeSandbox, so here is the code:

```typescript
// file: /server/middleware/log.ts
export default defineEventHandler((event) => {
  console.log(
    'New request:',
    event.node.req.url,
    'from:',
    {
      cRemoteAddress: event.node.req.connection.remoteAddress,
      sRemoteAddress: event.node.req.socket.remoteAddress,
      hForwardedFor: event.node.req.headers['x-forwarded-for'],
    }
  );
});
```
```typescript
// file: /server/api/count.ts
export default defineEventHandler((event) => {
  return { hello: 'world' };
});
```
---
```javascript
// file: /node.server.js
const http = require('http');

const server = http.createServer((req, res) => {
  console.log('native node server', {
    cRemoteAddress: req.connection.remoteAddress,
    sRemoteAddress: req.socket.remoteAddress,
    hForwardedFor: req.headers['x-forwarded-for'],
  });
  res.end();
});
server.listen(3000, () => {
  console.log('server is listening');
});
```

### Describe the bug

I was trying to get Client IP address behind Nginx proxy.
The main issue is:
`event.node.req.headers['x-forwarded-for']` was rewritten by nuxt (or other dependency, i can't figure out), so it is not possible to determine original request IP address.

Reproduction flow:
Client (Global IP: 1.2.3.4) -> Nginx proxy (local IP: 192.168.40.4) -> Nuxt server

* Nuxt middleware (`/server/middleware/log.ts`) output:
  ```bash
  New request: /api/counter from: {
    cRemoteAddress: undefined, # event.node.req.connection.remoteAddress
    sRemoteAddress: undefined, # event.node.req.socket.remoteAddress
    hForwardedFor: '::ffff:192.168.40.4' # rewritten by something! event.node.req.headers['x-forwarded-for']
  }
  ```
* Node.js http server (`/node.server.js`) output:
  ```bash
  native node server {
    cRemoteAddress: '::ffff:192.168.40.4', # req.connection.remoteAddress
    sRemoteAddress: '::ffff:192.168.40.4', # req.socket.remoteAddress
    hForwardedFor: '1.2.3.4' # real header value from Nginx, req.headers['x-forwarded-for']
  }
  ```

**Comment by danielroe** [comment]
This is only the case in dev mode, and it is caused by these lines of code in nitro, with a helpful TODO already in place:

https://github.com/unjs/nitro/blob/2ce4edbc6d44aba79b35b64447fc557e79221031/src/dev/server.ts#L160-L171

**Comment by danielroe** [comment]
This is resolved upstream. ❤️
