### ISSUE TITLE
:deep is not usefull in pages

### ISSUE THREAD

**Issue by xjccc** [nuxt/nuxt#18601]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.0`
- Package Manager:  `npm@8.9.0`
- Builder:          `vite`
- User Config:      `typescript`, `app`, `nitro`, `experimental`, `sourcemap`, `build`, `runtimeConfig`, `css`, `vite`, `ignore`, `hooks`, `modules`, `errorCacheConfig`
- Runtime Modules:  `nuxt-error-and-cache@1.0.3`, `nuxt-custom-fetch@1.0.6`, `@pinia/nuxt@0.4.6`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-lpxqx7?file=layouts%2Fdefault.vue,app.vue,pages%2Findex.vue

### Describe the bug

:deep is not usefull at nuxt@3.1.1

**Comment by dsvgl** [comment]
`:deep` is meant the other way around -> target elements of child components. See: https://vuejs.org/api/sfc-css-features.html
You could use the `:global` selector for reaching it:

```css
:global(.content) {
  background: red;
}
```

**Comment by xjccc** [comment]
> `:deep` is meant the other way around -> target elements of child components. See: https://vuejs.org/api/sfc-css-features.html You could use the `:global` selector for reaching it:
> 
> ```css
> :global(.content) {
>   background: red;
> }
> ```

thanks **:global** is work for me.
but  **:deep** is works earlier.😂
