### ISSUE TITLE
Can't persist data between routes with useNuxtData() when using npm nuxi generate

### ISSUE THREAD

**Issue by idflood** [nuxt/nuxt#18615]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.0`
- Package Manager:  `npm@8.19.3`
- Builder:          `vite`
- User Config:      `ssr`, `experimental`, `modules`, `runtimeConfig`
- Runtime Modules:  `nuxt-graphql-client@0.2.25`
- Build Modules:    `-`

### Reproduction

1. Clone https://github.com/idflood/nuxt3-static-test
2. run `npm i`
3. run `npx nuxi generate`

For each routes it will console.log `no data found for key, loading again featuredpokemon`.

### Describe the bug

When generating a static website I would like to be able to load some static data only once so that it can be shared across pages. This can be useful for global settings, menu, … And loading these once could considerably decrease build time.

In the [example provided](https://github.com/idflood/nuxt3-static-test), I've added a <[FeaturedPokemon](https://github.com/idflood/nuxt3-static-test/blob/main/components/FeaturedPokemon.vue)> component in the default layout. In that component I use a [useCachedData](https://github.com/idflood/nuxt3-static-test/blob/main/composables/useCachedAsyncData.ts) composable which make use of `useNuxtData`.

Then, running `npx nuxi generate` I see that it fetch this static data for every routes instead of reusing the data.

Note that in the useCachedAsyncData composable if I try to add a `useNuxtApp()` and log the values of `nuxt.payload` and `nuxt.static` they both always return empty content. I've also tried to set directly the `nuxt.static.value` with some data but it seems to have the same behavior as payload.

### Additional context

For reference, the global data storage is also being discussed here: https://github.com/nuxt/nuxt/discussions/16479

**Comment by danielroe** [comment]
`useNuxtData` isn't meant for persisting data between requests, but only within a single request.

I do think it's worth improving the generation experience, particularly when there's data you fetch once but need many times. There are a number of different ways of doing this already within Nuxt 3, so I'll have a think and get back to you with an example.

**Comment by idflood** [comment]
I think I've found one way to pass the shared payload between routes. 

@danielroe Was this what you had in mind?

```javascript
// plugins/cache-static-data.ts
const cachedData = {}
const dataToCache = ['featuredpokemon']

export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.hook('app:rendered', (ssrContext) => {
        dataToCache.forEach((key) => {
            if (ssrContext.ssrContext.payload.data[key]) {
                cachedData[key] = ssrContext.ssrContext.payload.data[key]
            }
        })
    })

    nuxtApp.hook('app:created', (vueApp) => {
        dataToCache.forEach((key) => {
            if (cachedData[key]) {
                vueApp.$nuxt.payload.data[key] = cachedData[key]
            }
        })
    })
})
```

**Comment by manniL** [comment]
This will be resolved by https://github.com/nuxt/nuxt/pull/24894
