### ISSUE TITLE
npm run dev is too slow！

### ISSUE THREAD

**Issue by xdewx** [nuxt/nuxt#18619]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `buildModules`, `build`, `fetch`, `env`, `runtimeConfig`, `nitro`, `alias`, `ssr`, `modules`, `strapi`, `vite`, `meta`
- Runtime Modules:  `@vueuse/nuxt@8.9.4`, `@nuxtjs/strapi@1.6.3`
- Build Modules:    `@nuxtjs/tailwindcss@6.2.0`

### Reproduction

1. npm run dev
2. cost nearly 1 minute

### Describe the bug

slow

**Comment by danielroe** [comment]
You're on rc9 - please upgrade to v3.1.1 and see how things go! If that doesn't resolve things for you, feel free to post a reproduction and I'll very happily have a look.
