### ISSUE TITLE
404 statusCode for static site generated

### ISSUE THREAD

**Issue by kami16ru** [nuxt/nuxt#18628]
### Environment

"nuxt": "2.15.8"

### Reproduction

issue is obvious and the provided information is enough to understand the problem

1. Create error layout, provide error prop to it.
2. npm run generate
3. npm start
4. go to yourdomain/somenotrealpage

Expected: http get request for not existant page responses with 404 status code

Actual: it respnose with 200 code

### Describe the bug

in packages/cli/src/utils/serve.js script it sends wrong status code for generated fallback page.

404 status works fine if to hardcode it

![image](https://user-images.githubusercontent.com/50907665/215522155-0e13ba67-6778-43b2-a513-442cbf4c23a4.png)

**Comment by manniL** [comment]
This is expected behavior for SSG with Nuxt 2. Because the web server does not know if the site exists or not (as it always serves the fallback file and only nuxt is aware), there are two ways of handling the scenario:

* Always return 404 -> will also return 404 for existing and valid "fallback"-sites that are generated dynamically
* Always return 200 -> will also return 200 for non-existing pages ("soft-404s")

**Comment by kami16ru** [comment]
its bad for seo returning 200 status code for not existing page.

can I make pr for extending config?

**Comment by manniL** [comment]
> its bad for seo returning 200 status code for not existing page.

Yes, but it is also bad for SEO to return 404 for existing pages 🙈 

> also in my case it's ok to return 404 for existing and non-existing pages. also by logic if to turn off generate fallback property, fallback page will be generated into 200.html. So it will be nice if it will return 200 status for 200.html and 404 status for 404.html.

that is up to your web server / platform then.

> by the way if to change 200 to 404 everything works fine. also if to serve via nginx or express and return 404 status code for 404.html also everything works fine for us. But we want still use web server out of box since it fast enough
> can I make pr for extending config?

After generating your pages via `generate`, you should rely on your web server / proxy, and *not*  on `nuxt start`. This only acts as "preview" command. You should be fine by pulling the static files on your server and configure your NGINX.
