### ISSUE TITLE
NuxtLoadingIndicator not working anymore

### ISSUE THREAD

**Issue by mcrapts** [nuxt/nuxt#18630]
### Environment

Nuxt project info:                                                                                                                                                           17:11:46

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.0`
- Package Manager:  `npm@8.5.5`
- Builder:          `vite`
- User Config:      `typescript`, `nitro`, `app`, `alias`, `css`, `vite`, `runtimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

StackBlitz from the docs: https://nuxt.com/docs/api/components/nuxt-loading-indicator#nuxtloadingindicator

https://stackblitz.com/github/nuxt/nuxt/tree/main/examples/routing/pages?file=package.json&terminal=dev

### Describe the bug

Loading indicator never appears

### Additional context

After updating to Nuxt 3.1.1, the NuxtLoadingIndicator component stopped working.

**Comment by mcrapts** [comment]
Setting the throttle property to 0 makes the loading indicator appear again. However, this is not how I interpret what throttle behavior should be. I would expect the throttle function only to kick in when the loading bar is already visible, not already on the first appearance. The behavior from 3.0.0 made more sense to me. Not sure if this is a bug or intendend behavior?

**Comment by danielroe** [comment]
I think it's desired behaviour not to display the loading indicator when the transition is less than a given amount of time: https://github.com/nuxt/framework/pull/9832. (This was also how it worked in Nuxt 2.)

**Comment by Arecsu** [comment]
Exactly. That's the purpose of the throttle. If your page loads instantly, a flashing NuxtLoadingIndicator doesn't really make that much sense from a UI/UX perspective, compared to a quick, elegant page transition. I would expect a loading bar to appear if something is taking more than normal to load, so I won't think I missed clicking the button/link or that my web browser broke. 

Nonetheless, as you mentioned, you can force it to appear always by setting the throttle to 0.

The default throttle value is stated [in the docs](https://nuxt.com/docs/api/components/nuxt-loading-indicator), which is `200ms`.

Maybe it comes as a surprise for people used to always expect it to appear from previous Nuxt versions and now updating it to the last version. At the same time, it will be a surprise for other people who no matter what throttle value they set, it never worked :)

**Comment by Arecsu** [comment]
Mmm. If the page takes more than the throttle time, it will show the loading bar. I'm confused. Have you checked an escenario where it takes > `throttle time` to load?

**Comment by danielroe** [comment]
The issue is that the example linked to in the docs isn't actually designed to show the loading indicator in action and the transitions are instant. We do need to fix that.

The change in behaviour is in the nature of a bug fix, but apologies if it has affected you negatively.

**Comment by mcrapts** [comment]
> The issue is that the example linked to in the docs isn't actually designed to show the loading indicator in action and the transitions are instant. We do need to fix that.
> 
> The change in behaviour is in the nature of a bug fix, but apologies if it has affected you negatively.

No worries, all I needed to know was if it's a bug or intended behavior. Updating the docs/example is also fine.

**Comment by Arecsu** [comment]
Oh sorry I didn't understand the issue. Yes, agree 100% with updating the docs with a full working example

**Comment by lafllamme** [comment]
Guys any updates on this? Why do I have to look inside the component code to understand and set it rather looking in the [offical documentation](https://nuxt.com/docs/api/components/nuxt-loading-indicator) lol?


```
declare const _default: import("vue").DefineComponent<{
    throttle: {
        type: NumberConstructor;
        default: number;
    };
    duration: {
        type: NumberConstructor;
        default: number;
    };
    height: {
        type: NumberConstructor;
        default: number;
    };
    color: {
        type: (BooleanConstructor | StringConstructor)[];
        default: string;
    };
    errorColor: {
        type: StringConstructor;
        default: string;
    };
    estimatedProgress: {
        type: () => (duration: number, elapsed: number) => number;
        required: false;
    };
}, () => import("vue").VNode<import("vue").RendererNode, import("vue").RendererElement, {
    [key: string]: any;
}>, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").PublicProps, Readonly<import("vue").ExtractPropTypes<{
    throttle: {
        type: NumberConstructor;
        default: number;
    };
    duration: {
        type: NumberConstructor;
        default: number;
    };
    height: {
        type: NumberConstructor;
        default: number;
    };
    color: {
        type: (BooleanConstructor | StringConstructor)[];
        default: string;
    };
    errorColor: {
        type: StringConstructor;
        default: string;
    };
    estimatedProgress: {
        type: () => (duration: number, elapsed: number) => number;
        required: false;
    };
}>>, {
    color: string | boolean;
    height: number;
    duration: number;
    throttle: number;
    errorColor: string;
}, {}>;
export default _default;

```
