### ISSUE TITLE
Server side not updating when in dev mode on Windows

### ISSUE THREAD

**Issue by igayamaguchi** [nuxt/nuxt#18635]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.1`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Create a minimal environment with the following command.

- `npx nuxi init dev-watch`
- `cd dev-watch`
- `npm i`
- `npm run dev`

### Describe the bug

I created a minimal environment and ran the dev command.
I have updated files like app.vue, but server side files are not updated.
It was confirmed that the client-side files were updated.

As shown below, I updated the values in console.log, but only the client side was updated, not updated the server side

```vue
<template>
  <div>
    <NuxtWelcome />
  </div>
</template>

<script lang="ts">
export default defineNuxtComponent({
  created() {
    console.log('app.vue 1')
  },
})
</script>
```

### Additional context

Doesn't reproduce in Nuxt@3.0.0.
Doesn't reproduce on WSL.

**Comment by i4j5** [comment]
> Воспроизводится ли это, если вы добавите следующее в свою конфигурацию nuxt?
> 
> ```js
> vite { (defineNuxtConfig экспорт по умолчанию
>   : {
>     devBundler: 'legacy'
>   }
> })
> ```

I have the same problem. Did not help

**Comment by i4j5** [comment]
> Воспроизводится ли это, если вы добавите следующее в свою конфигурацию nuxt?
> 
> ```js
> vite { (defineNuxtConfig экспорт по умолчанию
>   : {
>     devBundler: 'legacy'
>   }
> })
> ```

I have the same problem. Did not help

**Comment by i4j5** [comment]
> Does this reproduce if you add the following to your nuxt config?
> 
> ```js
> export default defineNuxtConfig({
>   vite: {
>     devBundler: 'legacy'
>   }
> })
> ```

I have the same problem. Did not help

**Comment by danielroe** [comment]
How strange. I can reproduce, but only using vite-node, not with legacy dev bundler. I'm tentatively guessing it might be an issue with cache again via `vite-node`.

cc: @antfu

**Comment by igayamaguchi** [comment]
https://github.com/nuxt/nuxt/issues/18635#issuecomment-1410244974
I tried it and the problem is solved.
I will try to apply this only on Windows until the problem is resolved.

**Comment by teamboot88** [comment]
- workaround works in 3.1.1 only.
- in 3.1.2, the below error occurs
```
[nuxt] [request error] [unhandled] [500] require is not defined in ES module scope, you can use import instead                                                                                         10:56:31
  at $id_jliaSA3QKS (/C:/Users/hyeonsu/IdeaProjects/teamboot88/repply-web/.nuxt/dist/server/server.mjs:191:3)
  at __instantiateModule__ (/C:/Users/hyeonsu/IdeaProjects/teamboot88/repply-web/.nuxt/dist/server/server.mjs:14958:9)
  at __ssrLoadModule__ (/C:/Users/hyeonsu/IdeaProjects/teamboot88/repply-web/.nuxt/dist/server/server.mjs:14896:25)
  at ssrImport (/C:/Users/hyeonsu/IdeaProjects/teamboot88/repply-web/.nuxt/dist/server/server.mjs:14921:13)
  at $id_w4M3WWtjnW (/C:/Users/hyeonsu/IdeaProjects/teamboot88/repply-web/.nuxt/dist/server/server.mjs:173:37)
  at __instantiateModule__ (/C:/Users/hyeonsu/IdeaProjects/teamboot88/repply-web/.nuxt/dist/server/server.mjs:14958:9)
  at __ssrLoadModule__ (/C:/Users/hyeonsu/IdeaProjects/teamboot88/repply-web/.nuxt/dist/server/server.mjs:14896:25)
  at ssrImport (/C:/Users/hyeonsu/IdeaProjects/teamboot88/repply-web/.nuxt/dist/server/server.mjs:14921:13)
  at $id_F4GnetaxWd (/C:/Users/hyeonsu/IdeaProjects/teamboot88/repply-web/.nuxt/dist/server/server.mjs:17:37)
  at __instantiateModule__ (/C:/Users/hyeonsu/IdeaProjects/teamboot88/repply-web/.nuxt/dist/server/server.mjs:14958:9)
```

**Comment by zenflow** [comment]
Workaround that worked for me in 3.1.2 is to use webpack instead of vite:

nuxt.config.ts
```
export default defineNuxtConfig({
    builder: 'webpack'
})
```

**Comment by antfu** [comment]
Just fired up my VM, and tried with the starter template `npx nuxi init` (Nuxt v3.2.2) - HMR works fine and I can not reproduce the error.

I think we would need a stable reproduction repo to move forward.

**Comment by teamboot88** [comment]
After updating to 3.2.2, I checked that it works normally without workaround. Thank you!

**Comment by teamboot88** [comment]
cc: @antfu
I'm sorry, but it hasn't been resolved yet.
Set with the command `npx nuxi init` and still occurs in 3.2.2.

![image](https://user-images.githubusercontent.com/54491002/220262615-c50f1710-e44f-4830-9800-ae5b6a2a87d7.png)

**Comment by danielroe** [comment]
This should be resolved in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/), or in the next release.

It is not included in 3.2.2.

**Comment by teamboot88** [comment]
I checked that it was resolved on the edge channel. Thank you very much for your quick feedback.

**Comment by RifatMahmudno-1** [comment]
There is a problem in `Nuxi 3.2.3-rc.0-27949872.7479d46`
If you remove any element from that vue file and reload in the browser, it throws error.
Like if you add an <style> element and then remove it, it will throw error.
To fix it you've to restart server.
![image](https://user-images.githubusercontent.com/62827535/220709999-90769d98-8738-4ecd-9dd9-5f8122ca7433.png)

**Comment by danielroe** [comment]
@RifatMahmudno-1 That is a different issue - see https://github.com/nuxt/nuxt/issues/14976.
