### ISSUE TITLE
sync types from code base into docs

### ISSUE THREAD

**Issue by madebyfabian** [nuxt/nuxt#18637]
### Describe the feature

In https://nuxt.com/docs/api/composables/use-fetch#usefetch, there are some types statically written in markdown, which are outdated (if you compare them to the types in nuxt 3.3.1). e.g. the `header` property accepts different values now.

I could add a PR to fix these static types, or maybe it would be better to not include them into the docs hand-written, and refer to the file in the git? Or maybe it's possible to include the file dynamically from git?

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by madebyfabian** [comment]
Maybe also other type docs are related to this, just found that by accident

**Comment by danielroe** [comment]
I think that's a good idea. Maybe we could use something like https://shikijs.github.io/twoslash/ to pull type information directly from source.

**Comment by manniL** [comment]
With [twoslash support for Shikiji](https://twitter.com/antfu7/status/1734320207521313169) this should be even better to realize 👍🏻
