### ISSUE TITLE
Cannot find package '@vueuse/shared'

### ISSUE THREAD

**Issue by lucaspottersky** [nuxt/nuxt#18632]
### Environment

- firefox

### Reproduction

- https://nuxt.com/docs/

### Describe the bug

I couldn't find the appropriate place to report this website/docs error. 

```
Page not found
Cannot find package '@vueuse/shared' imported from /var/task/node_modules/@vueuse/core/index.mjs

```

![image](https://user-images.githubusercontent.com/1385118/215546631-6242a01b-d693-491c-8784-168bb092c607.png)

**Comment by Baroshem** [comment]
Hey, does this happen on any particular page/endpoint?

I tried searching for it but could not find any.

Or maybe it is related to particular browser?

**Comment by manniL** [comment]
Can not reproduce it in Firefox on the mentioned link

**Comment by danielroe** [comment]
We rolled back the nuxt.com deployment for this reason - apologies team!

Related: https://github.com/nuxt/nuxt/issues/18448#issuecomment-1409128884

**Comment by madebyfabian** [comment]
I guess this could be closed then?
