### ISSUE TITLE
Symptoms of server rendering when adding plugins without server or client prefixes

### ISSUE THREAD

**Issue by zestlee1106** [nuxt/nuxt#18638]
### Environment

- nuxt: 3.1.1
- node: v16.13.1
- package manager: yarn 1.22.11

### Reproduction

https://github.com/zestlee1106/nuxt3-starter
From the repository above
`yarn install`
`yarn dev`
<img width="143" alt="image" src="https://user-images.githubusercontent.com/47649108/215712897-e23d8313-f3f5-424e-91ba-0372f37c50be.png">
Click Nuxtlink (one, two) in the header to move the page

### Describe the bug

When adding a plugin without a server or client prefix, the server renders it unconditionally when routing and moving.
Is this intended?

(For example, plugins/cookies.ts instead of plugins/cookies.server.ts.)

**Comment by madebyfabian** [comment]
Yes, as nuxt is SSR by default, I would presume this is the default and correct behaviour.

**Comment by zestlee1106** [comment]
> Yes, as nuxt is SSR by default, I would presume this is the default and correct behaviour.

Thank you for the comment. However, if I attach the server prefix to the plugin file, the page will be moved in the SPA manner as I intended.

**Comment by madebyfabian** [comment]
@zestlee1106 So, is this a particular issue with nuxt or more of a understanding question? 😄 Otherwise we could close the GitHub issue and you could join the discord community where we can discuss all questions https://discord.com/invite/ps2h6QT

**Comment by zestlee1106** [comment]
I found a way to reproduce the problem.

1. Create an empty file "plugins/~~~.ts" or "plugins/~~~.client.ts" in the Nuxt3 project.
2. Click NuxtLink.

This seems to move the page in the "location.href" manner.
I don't know the cause, but if you add content to the plugin file or name the file "plugins/~~~.server.ts", it works fine.

**Comment by danielroe** [comment]
I suspect the issue is that it's an invalid plugin and is breaking the Vue app's hydration. As I said, every plugin has to have a default export that is a function. You should see an error/warning in your browser.
