### ISSUE TITLE
useFetch and useLazyFetch export incorrect typescript type from api

### ISSUE THREAD

**Issue by tiborpino** [nuxt/nuxt#18639]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.1`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `modules`, `typescript`, `plugins`, `namedRoutes`, `build`, `css`, `app`, `schemaOrg`, `experimental`, `runtimeConfig`
- Runtime Modules:  `@formkit/nuxt@1.0.0-beta.14`, `@scr-nuxt/named-routes@1.0.6`, `@scr-nuxt/robots-txt@1.0.5`, `nuxt-schema-org@2.1.0`
- Build Modules:    `-`
------------------------------

### Reproduction

We use typed api points on the server side

```
export interface ApiHomepage {
    data: Data
}

export default defineEventHandler<ApiHomepage | undefined>(
    async (event: H3Event): Promise<ApiHomepage | undefined> => {
        ...
    }
)
```

and use the api point in vue

`const { data: page } = await useLazyFetch('/api/homepage')`

### Describe the bug

There is an incorrect type with default key. The image below shows the problem

![typescript](https://user-images.githubusercontent.com/169465/215718227-bbe7adaa-28dc-4975-bd17-55f6cadd38e9.png)

**Comment by Baroshem** [comment]
Hey, isnt it caused by union ts type that tries to search for common values between ApiHomepage and undefined?

**Comment by Baroshem** [comment]
Also, a Stackblitz repro would be useful :)

**Comment by danielroe** [comment]
I think we can track this in https://github.com/nuxt/nuxt/issues/15280.
