### ISSUE TITLE
Router View Transition into Dynamic routes does not capture route details

### ISSUE THREAD

**Issue by StevenJPx2** [nuxt/nuxt#18644]
### Environment

Nuxi 3.1.1

RootDir: */vue-resume-website
Nuxt project info: (copied to clipboard)

------------------------------
- Operating System: `Darwin`
- Node Version:     `v19.4.0`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.0`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `routeRules`, `app`, `modules`, `css`, `directus`
- Runtime Modules:  `@vueuse/nuxt@9.11.1`, `@nuxtjs/tailwindcss@6.3.0`, `@nuxtjs/fontaine@0.2.4`, `nuxt-directus@3.2.2`, `nuxt-icon@0.1.8`, `nuxt-svgo@1.1.0`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-csbyj6-kg9mio

Navigate to blog and click any of the numbers. This will take you to the slug page with the number as the param. The page SHOULD have the number on the page but doesn't. Reload the page and it will appear.

### Describe the bug

Because I want the page transition happening at the layout level, I can't use `definePageMeta` for the layout.

So replacing `<slot />` in `default.vue`, I use:

```vue
<router-view v-slot="{ Component, route }">
  <transition mode="out-in" @enter="enterFunction" @before-leave="leaveFunction">
    <component :is="Component" :key="route.fullPath" />
  </transition>
</router-view>
```

However, when I **NAVIGATE** to any dynamic routes, (in this example, it would be `/blog/[slug].vue`) the params are undefined. But if I'm directly loading into the page it works fine, or if I reload the page.

**Comment by danielroe** [comment]
The issue here is that you should use `NuxtPage` and not `RouterView` - we do some important things in that component. You can manually pass the transition to `<NuxtPage>` via the `transition` prop.

See https://github.com/nuxt/nuxt/issues/14595, which explains more about what `<NuxtPage>` does, and where we can track the issue you're experiencing (using `<RouterView>` within Nuxt).
