### ISSUE TITLE
Using  '@nuxtjs/pwa' dont working on nuxt 3

### ISSUE THREAD

**Issue by JosukeH** [nuxt/nuxt#18649]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.1`
- Package Manager:  `yarn@3.3.1`
- Builder:          `vite`
- User Config:      `vite`, `modules`, `pwa`, `imports`, `typescript`, `rootDir`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.1.3`, `nuxt-headlessui@1.0.4`, `@pinia/nuxt@0.4.6`, `@kevinmarrec/nuxt-pwa@0.15.0`
- Build Modules:    `-`
------------------------------

### Reproduction

I CAN'T

### Describe the bug

When adding 
 buildModules: [
    '@nuxtjs/pwa',
  ]

it throws a error and I cant add my servieWorker.js 

as any way to work on service worker on nuxt 3 with typescript?

### Additional context

Argument of type '{ vite: { plugins: Plugin_2[]; }; buildModules: string[]; modules: string[]; pwa: { workbox: { enabled: true; templatePath: string; }; }; imports: { dirs: string[]; }; typescript: { strict: true; }; rootDir: string; }' is not assignable to parameter of type 'NuxtConfig'.   Object literal may only specify known properties, and 'buildModules' does not exist in type 'NuxtConfig'

### Logs

```shell-script
Argument of type '{ vite: { plugins: Plugin_2[]; }; buildModules: string[]; modules: string[]; pwa: { workbox: { enabled: true; templatePath: string; }; }; imports: { dirs: string[]; }; typescript: { strict: true; }; rootDir: string; }' is not assignable to parameter of type 'NuxtConfig'.   Object literal may only specify known properties, and 'buildModules' does not exist in type 'NuxtConfig'
```

**Comment by vhoyer** [comment]
> I CAN'T

Why can't you provide a reproduction?

**Comment by madebyfabian** [comment]
The @nuxtjs/pwa module is a nuxt2-only module, it won't run in nuxt 3. Can be closed
