### ISSUE TITLE
i18n issues when running "node .output/server/index.mjs", while "nuxt dev" and "nuxt preview" works fine

### ISSUE THREAD

**Issue by martinsjek** [nuxt/nuxt#18655]
### Environment

- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.1`
- Package Manager:  `npm@8.19.3`
- Builder:          `vite`
- User Config:      `modules`, `css`, `vite`, `nitro`, `runtimeConfig`, `router`, `app`, `image`, `i18n`, `telemetry`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.9`, `@nuxt/image-edge@1.0.0-27919678.2f5b64b`, `@pinia/nuxt`, `@vueuse/nuxt@9.12.0`
- Build Modules:    `-`

### Reproduction

in app.vue:

const runtimeConfig = useRuntimeConfig();
const nuxtApp = useNuxtApp();

const { data } = await useFetch(`${runtimeConfig.apiBaseUrl}/api/translations`);

const translationsData = data.value;

nuxtApp.$i18n.warnHtmlMessage = false;

for (const i in translationsData) {
  const translations = translationsData[i];
  nuxtApp.$i18n.setLocaleMessage(i, translations);
}

### Describe the bug

While running "nuxt dev" or "nuxt preview" everything works fine without any issues, but when running "node .output/server/index.mjs", then i get this error in console "[intlify] The message format compilation is not supported in this build. Because message compiler isn't included. You need to pre-compilation all message format.". And half of my translations show keys instead of translation in UI.

**Comment by danielroe** [comment]
Would you raise this in https://github.com/nuxt-modules/i18n instead? 🙏
