### ISSUE TITLE
CLI commands quiet mode

### ISSUE THREAD

**Issue by rcerljenko** [nuxt/nuxt#18656]
### Describe the feature

Nuxt v2 had the `-q` flag on the `build` command which only outputed errors if happened.
That would be nice to have for Nuxt v3 - usefull for CI/CD builds.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
I realise it's not exactly the same, but I wonder if we could combine this with https://github.com/nuxt/nuxt/issues/18497.

**Comment by rcerljenko** [comment]
I see... what about wrapping lines [20](https://github.com/nuxt/nuxt/blob/main/packages/nuxi/src/commands/build.ts#L20) and [45](https://github.com/nuxt/nuxt/blob/main/packages/nuxi/src/commands/build.ts#L45) in the build command with a boolean --quiet param?

Something like:
```js
if (! args.quiet) {
    writeTypes(nuxt)
}
```

**Comment by danielroe** [comment]
We do need to write the types either way, but if the user passes a `-q` or `--quiet` flag on the command line, we could enable quiet mode in nuxt (via an override), and `writeTypes` can respect quiet mode.

**Comment by rcerljenko** [comment]
sure that would be nice also  :)

**Comment by Baroshem** [comment]
@danielroe can I take this one? :)

**Comment by danielroe** [comment]
@Baroshem Absolutely. Happy for you to go ahead. Here are my thoughts on implementation goals:

I think we could do both this and https://github.com/nuxt/nuxt/issues/18497 in the same PR. (If not, we need to do https://github.com/nuxt/nuxt/issues/18497 first.) For that, I would add a top level `quiet` option here:

https://github.com/nuxt/nuxt/blob/5037dd687649645de04ef862f804d740ec79778c/packages/schema/src/config/build.ts#L22-L23

This could be the basis for enabling quiet mode in vite + webpack. (There may be also other areas where we could respect this flag.)

We could default it to quiet if `!hasTTY` from `std-env`, maybe, or leave it disabled by default to prevent behaviour change. Thoughts welcome on this.

Then, for the CLI part, we would basically add this to everywhere we call `loadNuxt` within the cli:

```js
overrides: { quiet: args.quiet || args.q }
```

**Comment by Baroshem** [comment]
Awesome! I will start working on this :)

**Comment by danielroe** [comment]
related: https://github.com/nuxt/nuxt/issues/8915
