### ISSUE TITLE
Nuxt is adding all extracted css files both to head and to end of html

### ISSUE THREAD

**Issue by SebbeJohansson** [nuxt/nuxt#18669]
### Environment

  System:
    OS: Windows 10 10.0.22622
    CPU: (16) x64 Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz
    Memory: 40.69 GB / 63.75 GB
  Binaries:
    Node: 16.18.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.586.0), Chromium (109.0.1518.61)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @nuxt/babel-preset-app: 2.15.8 => 2.15.8
    nuxt: 2.15.8 => 2.15.8

### Reproduction

https://github.com/SebbeJohansson/nuxtjs-compostion-api-computed

### Describe the bug

We are seeing an issue where we have the same CSS files added twice to the application, which means that the CSS within certain components is written over by the CSS added to the bottom of the DOM.

![image](https://user-images.githubusercontent.com/5083273/216072892-ee7d0a32-0ad7-409b-b7f6-3b4b05288e3e.png)

Is there a way to disable this completely?

### Additional context

I have a feeling that this might just be how nuxt2 handles `extractCss`.

**Comment by Baroshem** [comment]
Hey, 

I checked your github repository but I cannot see any styles there. Could you create a reproduction in stackblitz so that it is easier testable? :)

**Comment by SebbeJohansson** [comment]
@Baroshem not sure what you mean, https://github.com/SebbeJohansson/nuxtjs-compostion-api-computed/blob/main/components/NewComponent.vue has styling. But made a stackblits for your convenience!
Stackblitz:
https://stackblitz.com/edit/github-eakrpp?file=package.json

I should also have specified that this issue only happens in a built situation.

In dev:
![image](https://user-images.githubusercontent.com/5083273/216125534-6a0e2a58-37c1-4a2e-aa95-d1c8c4c17fbb.png)
In built:
![image](https://user-images.githubusercontent.com/5083273/216126376-c74152ab-e44e-4c50-bf1e-ead6b12cb449.png)

Showing that it is in fact in the code twice:
![image](https://user-images.githubusercontent.com/5083273/216126545-40eb7038-087e-4271-88bc-93b30886ff2b.png)

**Comment by Baroshem** [comment]
I see now. 

The styles in the reproduction repository were not matching the screenshot in the issue. Thanks for the reproduction in stackblitz!

I will take a look at it.

**Comment by SebbeJohansson** [comment]
@Baroshem oh shit true. sorry for that confusion. The screenshot was showing the production issue here: 
https://www.revolutionrace.co.uk/
![image](https://user-images.githubusercontent.com/5083273/216138455-6aba02f8-29c7-4e21-821b-a57bd03ae70b.png)

Thanks for checking!

**Comment by Baroshem** [comment]
Hey,

I did some research and I think that it is indeed beeing duplicated both in head and end of html.

However, I have also found a configuration option that fixes this:

```ts
  build: {
    extractCSS: true,
    optimization: {
      splitChunks: {
        cacheGroups: {
          styles: {
            name: 'styles',
            test: /\.(css|vue)$/,
            chunks: 'all',
            enforce: true,
          },
        },
      },
    },
  },
```

Reference here -> https://nuxt.com/docs/api/configuration/nuxt-config/#extractcss

![image](https://user-images.githubusercontent.com/37120330/216266138-7cbb9530-b5e1-4d63-b0bb-1a5c590699e9.png)

Stackblitz as well -> https://stackblitz.com/edit/github-eakrpp-dyot4n?file=nuxt.config.js

Let me know if that works for you

**Comment by SebbeJohansson** [comment]
@Baroshem hmm thanks for looking. I'll try it both in the test application and in the production application.

Scoped css has nothing to do with it, correct? Noticed you changed that too.

**Comment by Baroshem** [comment]
Yes, 

I was just testing out whether some of the changes actually make a change. The `optimization` object in build configuration is crucial here :)

**Comment by SebbeJohansson** [comment]
@Baroshem, sadly it looks like this didn't fully fix our issue, but we are not sure why. We might end up just living with the double import until we upgrade to nuxt3.

**Comment by Baroshem** [comment]
Could you share more light what is the remaining issue?

Or if there i no more help needed from my side you can also close the issue as well :)

**Comment by SebbeJohansson** [comment]
@Baroshem, we were still getting double includes. It also seemed like it was changing the bundling in fundamental ways.
We will leave it for now and maybe keep going later! Closing.
