### ISSUE TITLE
Registering a root-scoped service worker in Nuxt3 not working with nitro header configuration

### ISSUE THREAD

**Issue by eliaSchenker** [nuxt/nuxt#18661]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.1`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `typescript`, `nitro`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

A reproduction of this issue can be found here: https://github.com/eliaSchenker/nuxt-webworker

The reproduction contains a simple service worker script, the plugin registering the service worker and a sample page with basic service worker interactions (sending messages, making a request, updating, etc.)

### Describe the bug

I am trying to register a service worker in Nuxt. I am importing the url of the service worker as mentioned in the vite-docs [Vite Features - Web Workers](https://vitejs.dev/guide/features.html#web-workers) like so:
```typescript
  import MyWorker from '~/worker/serviceworker.ts?worker&url'
```

This results in the following url when running a dev build (`yarn dev`):
```
/_nuxt/worker/serviceworker.ts?type=module&worker_file
```
And this url when running a preview of the node build (`yarn build`)
```
/_nuxt/serviceworker-4409edbe.js
```

Because this url is not located in the root directory of the project, when trying to register the service worker with a scope  of `/` the following error message is printed:
```
Service worker registration failed DOMException: 
Failed to register a ServiceWorker for scope ('http://localhost:3000/') with script ('http://localhost:3000/_nuxt/serviceworker-4409edbe.js'): 
The path of the provided scope ('/') is not under the max scope allowed ('/_nuxt/'). 
Adjust the scope, move the Service Worker script, or use the Service-Worker-Allowed HTTP header to allow the scope.
```
So fair enough, we need to set the header to configure the correct scope. This is where the issues start.

The core of the problem is in setting this header for the service workers script file. After some research I found that Nitro has a way of setting headers for certain files using the `routeRules`. I've tried to implement this by setting the required header for all files in the worker directory (location of `serviceworker.ts`):
```
  nitro: {
    routeRules: {
      '/worker/**': { headers: {'Service-Worker-Allowed': '/'} },
    }
  }
```
Similarily, I've tried moving the worker to the asset directory and add this rule for all files in the asset directory (as mentioned in the nitro docs):
```
  nitro: {
    routeRules: {
      '/assets/**':  { headers: {'Service-Worker-Allowed': '/'} },
    }
  }
```

As I've noticed, the **routeRules** do not seem to behave very well with nuxt and seem to only work for the server api and middle ware, and the pages, all rules for assets are simply ignored.

Is this an issue with Nitro's routeRules not working correctly with Nuxt? If so, is there another way to configure file-specific (or global) headers in Nuxt or modify the incoming requests in another way?

## Possible Workaround
I almost found a workaround for this problem, which is unfortunately invalidated due to the way vite bundles the files: By creating a server endpoint in `server/api` and fetching the service workers compiled file and outputting it (therefore the contents of the server endpoint and the service worker script are the same). Because the content of the service worker script is now located in a server endpoint, I could set the headers using Nitro. This solution only works when running the application locally though, as the url of the script differs (and also contains a hash) when building for production. Because the url changes it is not possible to fetch the file.

**Comment by danielroe** [comment]
This should be possible for assets - but note that `routeRules` applies on the _final_ route of the outputted file not on the location of the source files. But it obviously won't work as you don't know the path in advance. So you would likely need to add a directory for service worker exports:

```js
export default defineNuxtConfig({
  vite: {
    build: {
      rollupOptions: {
        output: {
          chunkFileNames (chunkInfo) {
            if (chunkInfo.name.includes('workers')) { return '_nuxt/workers/[name].[hash].js' }
            return '_nuxt/[name].[hash].js'
          }
        }
      }
    }
  }
})
```

Then you could set the routeRules accordingly:

```ts
  nitro: {
    routeRules: {
      '/_nuxt/workers/**': { headers: {'Service-Worker-Allowed': '/'} },
    }
  }
```

**Note**: I've not tested this but I think it should work.

**Comment by eliaSchenker** [comment]
@danielroe 
Thanks for your quick response!

I've tried the configuration option you provided, and as it seems, the `serviceworker.ts` file (or the folder path) is never passed through the function and therefore the path is never altered.
I have tried to console.log all the `chunkInfo.name` and the `workers/serviceworker.ts` path is not listed:
![image](https://user-images.githubusercontent.com/78470999/216053225-15e80a62-b151-4f93-9016-4c0ef327cd0c.png)
As you can see, the serviceworker script is never passed through the function. The script is currently located in the `workers` folder in the asset directory (though I have also tried placing the `workers` folder outside of the assets directory, with the same results):
![image](https://user-images.githubusercontent.com/78470999/216053905-0922c243-a193-4f05-9aaa-3cbbb23f00a3.png)

On that note: This should still work when run on dev, even if the path is not replaced, right? Because, even if I have the serviceworker on `/_nuxt/workers/serviceworker.ts?type=module&worker_file` and the routeRules set to
```
  nitro: {
    routeRules: {
      '/_nuxt/workers/**': { headers: {'Service-Worker-Allowed': '/'} },
    }
  }
``` 
the header is still not added, even though all the paths seem to match. Is something wrong with my configuration or is this an issue with Nitro?

**Comment by eliaSchenker** [comment]
@danielroe Any update on this?

**Comment by carlosmouracorreia** [comment]
@eliaSchenker I've successfully integrated a custom service worker to deal with push notifications with this Vite-PWA library - just out with the Nuxt3 extension and supported by Nuxt Labs.

https://vite-pwa-org.netlify.app/frameworks/nuxt.html

Also, check this for a simple integration with your own service worker:
https://vite-pwa-org.netlify.app/guide/service-worker-without-pwa-capabilities.html

(More details):
https://vite-pwa-org.netlify.app/guide/inject-manifest.html

**Comment by danielroe** [comment]
This isn't really an issue with Nuxt. The issue is that the service worker integration is emitting the file as an _asset_ - it's not quite the same kind of thing as normal runtime code.

This should do the trick for you:

```js
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  vite: {
    plugins: [{
      name: 'vite-plugin-serviceworker',
      generateBundle (_options, bundle) {
        for (const file in bundle) {
          if (file.includes('serviceworker')) {
            bundle[file].fileName = bundle[file].fileName.replace(/.*\//, '_nuxt/workers/')
          }
        }
      }
    }],
  },
  routeRules: {
    '/_nuxt/workers/**': { headers: { 'Service-Worker-Allowed': '/' } },
  }
})
```
