### ISSUE TITLE
useLazyAsyncData can't use in onMounted

### ISSUE THREAD

**Issue by baixiaoyu2997** [nuxt/nuxt#18671]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.1`
- Package Manager:  `pnpm@7.26.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://codesandbox.io/s/38o2xs?file=/app.vue

### Describe the bug

don't fetch data

### Additional context

the docs show that can use in lifecycle hooks https://nuxt.com/docs/getting-started/data-fetching

**Comment by danielroe** [comment]
Composables like `useAsyncData` and `useAsyncData` should not be run in mounted but instead should be run in the `setup` function. If you want to perform a programmatic fetch, use `$fetch`.

**Comment by baixiaoyu2997** [comment]
interesting，i test with `onBeforeMount` hook， it‘s worked , other hook  won't work

**Comment by danielroe** [comment]
Yes. `useLazyAsyncData` registers a callback to be run in before mount, and if you use it in mounted, that's too late.
