### ISSUE TITLE
Add hook to restart the nuxt server

### ISSUE THREAD

**Issue by Atinux** [nuxt/nuxt#18678]
I think it can be done right after this line with a `hookOnce('restart')`:
https://github.com/nuxt/nuxt/blob/434d36b532f564638d39029525d0b40d97bfe85f/packages/nuxi/src/commands/dev.ts#L78

This will let modules such as Tailwind to restart the server on config changes: 
https://github.com/nuxt-modules/tailwindcss/blob/12de7311aa1fe5f8877ad622a95278dc86303703/src/module.ts#L125-L126

**Comment by Baroshem** [comment]
@Atinux @danielroe can I work on this one? 🙂

**Comment by manniL** [comment]
Just assigned you - can't think of anything that speaks against rn ☺️

**Comment by danielroe** [comment]
For reference: https://github.com/nuxt/nuxt/pull/18641, which is a nice solution to restarting CLI but currently pending release of `citty`. This issue is for reloading Nuxt but not restarting CLI.

**Comment by pi0** [comment]
For context, these two are not the same requirements (we made this issue once on call to reproduce Nuxt 2 compatible behavior).

For implementation, nuxi should hook into a hook from current nuxt instance (in `dev.ts`) and call `load(true)`
