### ISSUE TITLE
[Nuxt 3.1.1] `nuxt generate`, deployed 404 pages return HTTP 200

### ISSUE THREAD

**Issue by madebyfabian** [nuxt/nuxt#18683]
### Environment

```
- Operating System: `Darwin`
- Node Version:     `v16.18.1`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.1`
- Package Manager:  `pnpm@7.26.3`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
```

### Reproduction

https://github.com/madebyfabian/nuxt3-generated-reprod

### Describe the bug

Check out this empty nuxt 3 project:

https://github.com/madebyfabian/nuxt3-generated-reprod

If you clone it locally, install deps and run `nuxt generate` and `nuxt preview`, and you hit any route that is not defined, you get a visual 404 page (the nuxt default one). Checking the network tab, you also get a real HTTP 404.

Deploy it to vercel using the `nuxt generate` command (or use my test deploy: https://nuxt3-generated-reprod.vercel.app/)

Check a undefined route. You'll still see the 404 page visually, but Vercel outputs a HTTP 200 Found. According to their docs at https://vercel.com/guides/custom-404-page#static-site-generator-ssg , there must be a 404.html in the output root. There actually is, if you check the output. Which is very interesting.

**Comment by madebyfabian** [comment]
Same behaviour when deploying a `error.vue` page:

https://github.com/madebyfabian/nuxt3-generated-reprod/tree/with-error-vue

https://nuxt3-generated-reprod-git-with-error-vue-madebyfabian.vercel.app/blahh

**Comment by danielroe** [comment]
This sounds like Vercel behaviour (and not one we can control from the Nuxt side, given that it's a purely static site). I would check with them to see if it's intended that a `404.html` is served up with `200.html`. (It may be.)

**Comment by madebyfabian** [comment]
@danielroe Yes, sounds reasonable, just wanted to raise this maybe this is actually intentional by nuxt.

**Comment by danielroe** [comment]
Also worth linking https://github.com/unjs/nitro/issues/818 - it may be possible to output rules using Vercel's Build Output API that let us configure these things more appropriately for static sites also.

**Comment by hecktarzuli** [comment]
@madebyfabian I just ran into this myself, did you find a solution?

**Comment by madebyfabian** [comment]
> @madebyfabian I just ran into this myself, did you find a solution?

Hey there, actually haven't found a solution for that currently.

**Comment by hecktarzuli** [comment]
@madebyfabian i just discovered that removing 200.html post-build seems to fix the problem.
![image](https://github.com/nuxt/nuxt/assets/2112282/33bc2c84-228d-4349-b0bc-5eebc043e61b)

https://deltener-com-nuxt3-kndhp90g7-hecktarzuli.vercel.app/crap/

**Comment by vedmant** [comment]
@danielroe By removing 200.html all dynamic pages will stop working.
