### ISSUE TITLE
@click event on <NuxtLink> with headlessui not working

### ISSUE THREAD

**Issue by nazar1ua** [nuxt/nuxt#18682]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.1`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-kturhm?file=app.vue

### Describe the bug

No click event on click

**Comment by madebyfabian** [comment]
Check a similar question in the Discord, this maybe solves your issue: https://discord.com/channels/473401852243869706/1067122685039091772/1067122685039091772

> So I'm using a HeadlessUI menu and by default the MenuItem component should listen for its child's click events and close itself and I find myself having to add a @click="$emit('click') tag to the NuxtLink that I nest in this menu. It's not the end of the world but I'm just curious as to why Nuxt (or VueRouter) might hijack these events and prevent them from bubbling up.

**Comment by nazar1ua** [comment]
@madebyfabian This is [documented](https://headlessui.com/vue/menu#closing-menus-manually) in headlessui docs, but it works only on 3.0.0 version of nuxt. For latest version @click event doesn't working in general, I determined, that it is because of the conflict of `<MenuItem>` @click binding with `<NuxtLink>` click binding, because when I added `as="div"` to `<MenuItem>` component, @click event on `<NuxtLink>` started working, but keyboard navigation stopped work. I am not sure, but I think it is issue on nuxt side, because all was working on nuxt 3.0.0 with the same version of headlessui

**Comment by madebyfabian** [comment]
@nazar1ua Yeah I see what you mean, in this case the `<NuxtLink />` should be optimized to follow some "standard". 
Could you create a second reproduction that runs on 3.0.0 wich the same code but working? Not sure if the `<NuxtLink />` has changed between 3.0.0 and 3.1.1, will check if I find some commits on https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/app/components/nuxt-link.ts

**Comment by nazar1ua** [comment]
@madebyfabian I'm sorry, when I was updating dependencies with nuxt, headlessui also updated from 1.7.4 to 1.7.8, and that update causes the issue

**Comment by nazar1ua** [comment]
I opened issue on headlessui repo: https://github.com/tailwindlabs/headlessui/issues/2243

**Comment by danielroe** [comment]
Thank you ❤️

**Comment by wtzr** [comment]
> because when I added `as="div"` to `<MenuItem>` component, @click event on `<NuxtLink>` started working,


This worked for me. @click also not working on latest nuxt and headless ui. Only after adding as=div to menuitem.
