### ISSUE TITLE
[Nuxt 3.1.1] Defining `runtimeConfig.public.myValue = ''` is not injected with `.env` at runtime of a module

### ISSUE THREAD

**Issue by madebyfabian** [nuxt/nuxt#18692]
### Environment

RootDir: /home/projects/github-qrbpqh                                                 05:30:19
Nuxt project info:                                                                    05:30:19

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.1`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `runtimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-qrbpqh?file=app.vue,nuxt.config.ts

1. Add a `.env` to the base dir:

```bash
NUXT_PUBLIC_SITE_URL="http://mysite.com"
```

Run `npm install && npm run dev`.

You see that the `nuxt-simple-sitemap` module, which depends on the `runtimeConfig.public.siteUrl` being defined, throwing an error.

### Describe the bug

The docs say you can write env variables like this:

https://nuxt.com/docs/guide/going-further/runtime-config#environment-variables

```ts
export default defineNuxtConfig({
  runtimeConfig: {
    apiSecret: '', // can be overridden by NUXT_API_SECRET environment variable
    public: {
      apiBase: '', // can be overridden by NUXT_PUBLIC_API_BASE environment variable
    }
  },
})
```

and `.env`

```
NUXT_API_SECRET=api_secret_token
NUXT_PUBLIC_API_BASE=https://nuxtjs.org
```

In the newest nuxt version, this does not work anymore. The string stays empty after build, so the `.env` variables are not injected.

What works is setting it manually like

```ts
export default defineNuxtConfig({
  runtimeConfig: {
    apiSecret: process.env.NUXT_API_SECRET,
    public: {
      apiBase:  process.env.NUXT_PUBLIC_API_BASE,
    }
  },
})
```

If this is by intention, I would add a PR to the docs to make it clear that modules do not have access to the config if you are using the empty-string syntax. Or I think it would actually be even clearer to get rid of that syntax and suggest always use the `process.env.NUXT_...` directly.

**Comment by danielroe** [comment]
Ahh, I see what you mean. Yes, the runtime config override happens when the Nitro server starts up, which is well after the modules initialise. Normally they should respect runtime config in their runtime handlers, which means it should be fine. But if the module is trying to check that the config already exists (or to normalise it) this might create nonintuitive results.

Would be great to get @harlan-zw's thoughts on what we could do in Nuxt to make this more intuitive.

**Comment by harlan-zw** [comment]
Thanks for clarifying @danielroe 

I'll see about moving anything I can into the runtime to avoid this issue. If there's anything I'm blocked on I'll have a think about what could be done about it

**Comment by harlan-zw** [comment]
Hm actually pretty easy to solve at a module level.

`hostname: process.env.NUXT_PUBLIC_SITE_URL || nuxt.options.runtimeConfig.public?.siteUrl,`

maybe there's a way to make this easier though
