### ISSUE TITLE
Add an option to `useFetch` to not consider non-5xx status codes as errors

### ISSUE THREAD

**Issue by roamiiing** [nuxt/nuxt#18713]
### Describe the feature

When developing a rest API, it's considered good to use semantic status codes for different response types. So I do in my API routes:

```ts
import { setResponseStatus } from 'h3'

const enum OperationResultKind {
  Created       = 'Created',
  AlreadyExists = 'AlreadyExists',
  InvalidData   = 'InvalidData',
}

type OperationResult =
| { kind: OperationResultKind.Created; user: User }
| { kind: OperationResultKind.AlreadyExists }
| { kind: OperationResultKind.InvalidData; problems: ValidationProblem[] }

export default defineEventHandler(event => {
  const unvalidatedData = readBody(event)
  const validationResult = // some validation stuff

  if (!validationResult.success) {
    setResponseStatus(event, 400)
    return { kind: OperationResultKind.InvalidData, problems: validationResult.problems }
  }

  const { data } = validationResult
  
  try {
    const insertedUser = await insertIntoDb(data)
    setResponseStatus(event, 203)
    return { kind: OperationResultKind.Created; user: insertedUser }
  } catch (e) {
    if (/* some error checking */) {
      setResponseStatus(event, 409)
      return { kind: OperationResultKind.AlreadyExists }
    }
    
    throw e
  }
})
```

However, when fetching this route with `useFetch`, I end up with `InvalidData` and `AlreadyExists` errors being in the `error` ref. The thing is that these variants are some type of domain errors and I get no typings for them. The other thing is that the `data` ref is of type `OperationResult`, but it only may contain the `Created` variant so I end up using `as` to convert types which is not good. 

I could return only 2xx status codes to resolve this issue, but I might want to reuse this API in many different projects in the future so status codes must be semantic.

I think that one option for resolving that may be adding some interceptor concept such as in Axios:
```ts
axios.get('/user/12345', {
  validateStatus: function (status) {
    return status < 500; // Resolve only if the status code is less than 500
  }
})
```

Also one would want to use this validation interceptor globally, so it's worth adding this to `nuxt.config.ts`.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by madebyfabian** [comment]
According to HTTP, 5xx is always a server error, so accepting those as a valid response only to get non-runtime relevant types would be kind of semantically wrong, in my opinion. But I understand the struggle, let's what other people think about that.

**Comment by pi0** [comment]
Lets track in https://github.com/unjs/ofetch/issues/207

**Comment by danielroe** [comment]
This is now implemented.
