### ISSUE TITLE
navigateTo redirecting to current url

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/nuxt#18729]
### Environment

Nuxi 3.1.1                                                                                                                                               10:10:16
                                                                                                                                                         10:10:16
RootDir: /home/foticos/var/www/wanapix_next                                                                                                              10:10:16
Nuxt project info: (copied to clipboard)                                                                                                                 10:10:16

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.3`
- Builder:          `vite`
- User Config:      `srcDir`, `modules`, `tailwindcss`, `vite`, `schemaOrg`, `telemetry`, `algolia`, `head`, `auth`, `viewport`, `css`, `build`, `runtimeConfig`
- Runtime Modules:  `genesis-design-system/nuxt`, `@nuxtjs/algolia@1.5.0`, `@nuxtjs/tailwindcss@6.3.1`, `formidable@2.1.1`, `nuxt-viewport@2.0.3`, `@nuxtjs/partytown@1.3.0`, `@vueuse/nuxt@9.12.0`, `@nuxtjs/i18n-edge@8.0.0-beta.4-27812700.b832f07`, `nuxt-schema-org@1.1.0-beta.6`, `nuxt-icon@0.1.8`, `@pinia/nuxt@0.4.6`, `@nuxtjs/i18n@8.0.0-beta.9`, `@sidebase/nuxt-auth@0.3.4`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                                                              10:10:16

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Reproduction

when i use navigateTo at the same url that i am, the page doesnt refresh

### Describe the bug

when i use navigateTo at the same url that i am, the page doesnt refresh

**Comment by agracia-foticos** [comment]
There is any parameter to force the refresh?

**Comment by danielroe** [comment]
I would use `window.location.href = ''` in this situation.

**Comment by agracia-foticos** [comment]
ok thank you! :)

**Comment by agracia-foticos** [comment]
i close the issue
