### ISSUE TITLE
Auto key for `useFetch` applies to non-Nuxt composable

### ISSUE THREAD

**Issue by chrislee973** [nuxt/nuxt#18724]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@vueuse/nuxt@9.11.1`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-dcsx2u?file=app.vue

### Describe the bug

Nuxt's autoimported useFetch is taking precedent over the Vueuse useFetch even though it was explicitly imported (ie 
`import { useFetch } from '@vueuse/core'` ). A solution would be to rename the import, like 
`import { useFetch as useFetchVueUse } from '@vueuse/core' `, but if it's already explicitly imported shouldn't the expected behavior be for it to take priority?

**Comment by danielroe** [comment]
cc: @antfu

**Comment by antfu** [comment]
Oh actually, it's imported the right entry. The problem is that Nuxt automatically injected a magic key for `useFetch` causing the argument mispositioned. /cc @danielroe do you see a way to detect that in the macro?

**Comment by danielroe** [comment]
Nice find. It's tricky. There are a fair number of edge cases with regard to shadowing, for example. But I think detecting a top-level import is reasonable, and we have the tools for it.
