### ISSUE TITLE
Dynamically imported get's preloaded

### ISSUE THREAD

**Issue by fmoessle** [nuxt/nuxt#18723]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.1`
- Package Manager:  `yarn@1.22.19`

### Reproduction

https://stackblitz.com/edit/github-mwmwdh?file=app.vue

### Describe the bug

When dynamically importing a module (dayjs as an example) it get's added to the head of the page with `rel="prefetch"`.

<img width="560" alt="image" src="https://user-images.githubusercontent.com/17830282/216454883-6a91889a-5fd0-4e4f-b623-a7c3ef2d153c.png">

Code:

```html
<template>
  <div>
    <button @click="loadScriptDynamically">Load</button>
  </div>
</template>

<script setup>
async function loadScriptDynamically() {
  await import('dayjs');
}
</script>

```

This only happens when running: `npx nuxi build` and not with `npx nuxi dev`

This can cause trouble when done a lot or when using a relatively large module. 

Is this behavior intended or is it possible to mitigate?

**Comment by manniL** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/18376
