### ISSUE TITLE
`.dev.ts` suffix for dev-only `server` routes 

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt#18730]
### Describe the feature

Hey all 👋🏻

We have the `<DevOnly>` component for a while now. An equivalent for the `server` folder could be the `.dev.ts` suffix. All routes (API and server routes) having a `.dev` suffix would only be loaded during development and would not be present in production. 

Benefits would be automatic removal on production and being able to define e.g. debug endpoints in your dev environment 🙌 

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by madebyfabian** [comment]
+1 makes sense. 

And didn't even know we have <DevOnly />, that's great.

**Comment by jodyhoonstarr** [comment]
A use case here would be for graphql IDEs used only during dev. Postgraphile v5 has some [recipes for nuxt integration](https://grafast.org/grafserv/servers/nuxt) and a graphiql-like IDE called [ruru](https://github.com/graphile/crystal/blob/main/grafast/ruru/README.md) that can be served in dev via nuxt server routes:

```js
import type { H3Event } from 'h3'
import { ruruHTML } from 'ruru/server'

export default defineEventHandler((event: H3Event) => {
  event.node.res.setHeader('Content-Type', 'text/html')
  return ruruHTML({
    endpoint: '/api/graphql',
  })
})
```

This works in dev but bombs during `build` runtime because some packages need to be copied to `.output`. A dev only server route would be great for this use case.

**Comment by evrys** [comment]
This would be a helpful feature! Is there currently a workaround to stop nitro trying to build dev routes?

**Comment by evrys** [comment]
Ah, it's currently possible to do this by moving your dev endpoint files out of the autoscanned dir and then manually importing the event handlers into config for use with nitro's `devHandlers` option, like so:

```ts
import listImages from './dev/api/listImages.get'
import uploadImage from './dev/api/uploadImage.post'
import deleteImage from './dev/api/deleteImage.post'

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  nitro: {
    devHandlers: [
      {
        route: '/api/dev/listImages',
        handler: listImages
      },
      {
        route: '/api/dev/uploadImage',
        handler: uploadImage
      },
      {
        route: '/api/dev/deleteImage',
        handler: deleteImage
      }
    ]
  },
})
```

**Comment by danielroe** [comment]
I think this is a promising issue but I suspect we should be tracking in https://github.com/unjs/nitro instead....

**Comment by manniL** [comment]
Reopened under https://github.com/unjs/nitro/issues/1849

Closing here for now to track upstream in the linked issue

**Comment by sandros94** [comment]
What about dev only `pages`? 🤔

**Comment by manniL** [comment]
@sandros94 can be resolved via hooks and $development/$production nuxt config ☺️

**Comment by sandros94** [comment]
@manniL I finally had some free time to dig into this and noticed [`ignorePrefix`](https://nuxt.com/docs/api/nuxt-config#ignoreprefix) in `nuxt.config.ts`.

But while studying how a `ignoreSuffix` could be implemented I'm understanding very little about `ignorePrefix` itself, the only place where it is mentioned is here
https://github.com/nuxt/nuxt/blob/b676722d2f25430f563e3d0492f3d0a43ccb1470/packages/schema/src/config/common.ts#L461-L469

But I don't see it being used anywhere, not even in the ignore implementation in `@nuxt/kit`
https://github.com/nuxt/nuxt/blob/b676722d2f25430f563e3d0492f3d0a43ccb1470/packages/kit/src/ignore.ts#L33
