### ISSUE TITLE
PnPM support request!

### ISSUE THREAD

**Issue by 1216892614** [nuxt/nuxt#18755]
### Describe the feature

When I use `create nuxt-app`, I can't find `PnPm` as a option from Package managers list.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by madebyfabian** [comment]
`create-nuxt-app` is Nuxt 2, you've created an issue for Nuxt 3. Which version do you mean?

**Comment by danielroe** [comment]
I think we can track support for Nuxt 3 in https://github.com/nuxt/framework/issues/5411.

We can track the `create-nuxt-app` issue in https://github.com/nuxt/create-nuxt-app/issues/367.

**Comment by 1216892614** [comment]
Sorry I got the version wrong.
