### ISSUE TITLE
component slots end up as comments

### ISSUE THREAD

**Issue by tasiotas** [nuxt/nuxt#18754]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `2.1.1`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `modules`, `vuestic`
- Runtime Modules:  `@vuestic/nuxt@1.0.9`
- Build Modules:    `-`
------------------------------

### Reproduction

1. create component as below

Btn.vue
```vue
<template>
  <div>
    <slot name="header"></slot>
    <slot></slot>
    <slot name="slot1"></slot>
    <slot name="slot2"></slot>
    <slot name="footer"></slot>
  </div>
</template>

<script setup></script>

<style lang="scss" scoped></style>
```

2. build project `yarn build`
3. run `yarn preview`
4. inspect DOM

### Describe the bug

this is resulting html of built project

```html
<div id="__nuxt">
  <div>
    <!--[-->
    <!--]-->
    <!--[-->
    im a button
    <!--]-->
    <!--[-->
    <!--]-->
    <!--[-->
    <!--]-->
    <!--[-->
    <!--]-->
  </div>
</div>
```

Is it possible to get rid of generated comments in place of empty slots?

**Comment by madebyfabian** [comment]
This is not from Nuxt, but a feature from Vue. These comments act as placeholders for Vues reactive shadow DOM to easily switch these out with the real DOM content as soon as vue needs them.

**Comment by tasiotas** [comment]
Thank for explaining.
Could you elaborate why Vue generates html without those comments, given the same component?

Just want to save some bytes in prod code.

**Comment by madebyfabian** [comment]
> Thank for explaining.
> 
> Could you elaborate why Vue generates html without those comments, given the same component?
> 
> 
> 
> Just want to save some bytes in prod code.

Not in particular, but if you want my two cents, saving even if you could, saving those few characters of text does not solve/save anything in real life 😄. It's like 0.001% of your code, if even. Try to use a good Dom syntax and as less 3rd party modules as possible if you really want to reduce bundle size.

**Comment by manniL** [comment]
> Thank for explaining. Could you elaborate why Vue generates html without those comments, given the same component?

This is Vue's syntax for fragments (components with no root element but multiple). Because Nuxt uses some wrappers before rendering the page components (or app.vue), it looks like it does 😋.

> Just want to save some bytes in prod code.

As @madebyfabian said, it is not worth optimizing this at all. HTML is eventually compressed (Brotli/GZIP), so this will have no significant impact on page speed
