### ISSUE TITLE
 [Vue warn]: Do not use built-in or reserved HTML elements as component id: s  

### ISSUE THREAD

**Issue by bbhxwl** [nuxt/nuxt#18761]
### Environment

"nuxt": "^2.15.8",
"vue": "^2.6.14",

### Reproduction

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/26525599/216768984-1bdae6ea-6cb7-4ead-89c9-aadc0c3a6d5f.png">

### Describe the bug

I have deleted all the. vue files and failed to solve this problem. I don't know how to troubleshoot the problem, which file has the problem, and there will be no error in startup. As long as I visit a page, I will be prompted with this error, but the second visit will not occur again. Only the first visit will have this error.

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/26525599/216768979-9747d91a-a19a-4bf8-9c7a-1141c86ad97b.png">

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by bbhxwl** [comment]
> Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

I checked which file was wrong, but I didn't see where the error was?
···
import Vue from "vue";
import { registerLicense } from '@syncfusion/ej2-base';
registerLicense('**********');
import { AppBarPlugin } from "@syncfusion/ej2-vue-navigations";
import { ButtonPlugin } from '@syncfusion/ej2-vue-buttons';
Vue.use(ButtonPlugin);
Vue.use(AppBarPlugin);

import "@syncfusion/ej2-base/styles/material.css";
import "@syncfusion/ej2-buttons/styles/material.css";
import "@syncfusion/ej2-navigations/styles/material.css";
···
<img width="918" alt="image" src="https://user-images.githubusercontent.com/26525599/216772045-baf48d1d-fa70-4f45-905f-89abde4fc6e1.png">

<img width="893" alt="image" src="https://user-images.githubusercontent.com/26525599/216772141-a2db36f5-1276-45ec-b189-950a5623d6dc.png">

**Comment by bbhxwl** [comment]
> Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

Are there any bugs in third-party components?

**Comment by danielroe** [comment]
By reproduction, check the link I provided - I'm hoping for a minimal reproduction via https://stackblitz.com/github/nuxt/starter/tree/v2 so I can identify the issue, if any, in Nuxt. I can't tell from the screenshot.

**Comment by bbhxwl** [comment]
> By reproduction, check the link I provided - I'm hoping for a minimal reproduction via https://stackblitz.com/github/nuxt/starter/tree/v2 so I can identify the issue, if any, in Nuxt, and this is more likely to be a 3rd-party issue. I can't tell from the screenshot.

Do you know how I can solve this warning? Do you have discord? I have several nuxt questions that many people will not solve.


<img width="1209" alt="image" src="https://user-images.githubusercontent.com/26525599/216773326-ac521d1d-9493-485a-9faf-2b5ee25a6641.png">

**Comment by danielroe** [comment]
The Nuxt Discord is https://discord.nuxtjs.org. And in general it's best to keep each issue on a single topic. In order to help you best, try following the instructions on https://nuxt.com/docs/community/getting-help. If you do raise a bug report, please do include a reproduction.

**Comment by bbhxwl** [comment]
> The Nuxt Discord is https://discord.nuxtjs.org. And in general it's best to keep each issue on a single topic. In order to help you best, try following the instructions on https://nuxt.com/docs/community/getting-help. If you do raise a bug report, please do include a reproduction.

It is not an error, but a use skill. At present, I don't know whether nuxt can be implemented more easily. If not, I can only use more code to implement it. Can I ask you this question now?

**Comment by danielroe** [comment]
The best thing is to raise a GitHub Discussion or come into the Nuxt Discord. That way the discussion can help other people, and others might also be able to answer it.

**Comment by danielroe** [comment]
Closing as there's no reproduction. Feel free to provide a reproduction and I'll happily reopen.
