### ISSUE TITLE
 `useHead` is exported from two modules

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt/nuxt#18766]
### Environment

RootDir: C:/Users/esoub/Dev/Barbapapazes/le-classement.fr                                                     16:24:59
Nuxt project info:                                                                                            16:24:59

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.1`
- Package Manager:  `yarn@3.4.1`
- Builder:          `vite`
- User Config:      `extends`, `modules`, `runtimeConfig`, `content`, `app`, `nitro`, `routeRules`
- Runtime Modules:  `@vueuse/nuxt@9.12.0`, `@nuxtjs/tailwindcss@6.3.0`, `@nuxtjs/fontaine@0.2.4`, `@nuxt/content@2.4.2`, `nuxt-icon@0.2.10`
- Build Modules:    `-`
------------------------------

### Reproduction

/

### Describe the bug

During my CI, I got this warning

```
4:22:24 PM: Export "useHead" of module "node_modules/nuxt/dist/head/runtime/composables.mjs" was reexported through module "node_modules/nuxt/dist/app/index.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
```

**Comment by madebyfabian** [comment]
Hey, can you add a [minimal reproduction](https://nuxt.com/docs/community/reporting-bugs#create-a-minimal-reproduction)?

**Comment by daniluk4000** [comment]
Same error in 3.1.2
