### ISSUE TITLE
Reload nitro server after error when file changed.

### ISSUE THREAD

**Issue by sugoidesune** [nuxt/nuxt#18792]
### Describe the feature

When nitro encounters an error on a page and new changes have been made to the file nitro doesn't reload.
One has to manually quit the server and run it again.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
Related: https://github.com/nuxt/nuxt/pull/18641

**Comment by danielroe** [comment]
Possibly we would need to resolve this upstream in Nitro.

cc: @pi0

**Comment by manniL** [comment]
This should happen by default now and provide a better DX 👍🏻

<img width="802" alt="image" src="https://github.com/nuxt/nuxt/assets/640208/2c0d2026-8dd1-41bc-8ec5-4ace13daa3de">
