### ISSUE TITLE
@nuxt/types@2 brings webpack@5

### ISSUE THREAD

**Issue by shrpne** [nuxt/nuxt#18817]
### Environment

@nuxt/types@2.16.0

### Reproduction

`npm i nuxt@2 && npm list webpack`

### Describe the bug

@nuxt/types@2.16.0 has dependencies of webpack types which have webpack@5 as dependency

![image](https://user-images.githubusercontent.com/392907/216997974-4412e175-21d0-4798-8cb3-bd88472e6832.png)

Looks like it doesn't break build, but it brings extra redundant webpack node modules, and maybe break typings

**Comment by danielroe** [comment]
resolved in https://github.com/nuxt/nuxt/pull/18827
