### ISSUE TITLE
`inheritAttrs: false` disables `fetch` hydration

### ISSUE THREAD

**Issue by KonRatt** [nuxt/nuxt#18811]
### Environment
nuxt: 2.15.8
vue: 2.7.10

### Reproduction

https://codesandbox.io/p/sandbox/nuxt-fetch-hydration-inheritattrs-7rngoy

### Describe the bug

When using `inheritAttrs: false` in any component (or page), the hydration of fetch data doesn't work because the `data-fetch-key` Attribute isn't set during SSR. This triggers a second fetch on the client side.

### Additional context

In my case, i could solve it by just using `inheritAttrs: true`.

Setting the `data-fetch-key` attribute manually unfortunately doesn't work:
```
:data-fetch-key="$attrs['data-fetch-key']"
```

A warning in the documentation would be an option if no nice solution is available.

**Comment by KonRatt** [comment]
I just noticed that this is a duplicate of #7372, which was closed due to inactivity.

**Comment by danielroe** [comment]
Yes, this is a limitation of the Nuxt 2 `fetch()` hook. A PR to add this to the docs at https://github.com/nuxt/nuxtjs.org would be welcome.

**Comment by adrienZ** [comment]
@danielroe I think I could do this one
