### ISSUE TITLE
`status` property for `useAsyncData`/`useFetch` (+ lazy equivalents)

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt#18810]
### Describe the feature

Follow-up of https://github.com/nuxt/nuxt/issues/15714

This feature request should provide a more fine-grained check of the status of `useFetch`/`useAsyncData` (and the lazy equivalents) by introducing a `status` ref that contains the status a a string.

## `Status` values

* `IDLE` -> Request did not start yet, e.g. because:
	* `{ immediate: false }` and `execute` was not called ye.
	* `{ server: false }` and status is logged during SSR
* `PENDING` -> Requesting data did start
* `SUCCESS` -> Requesting data succeeded
* `ERROR` -> Requesting data failed.

**Any other kinds of `status`es needed?**

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by Mini-ghost** [comment]
How about using a number like XMLHttpRequest.readyState ? I'm not sure if it's going to be like a magic number.
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/readyState

**Comment by manniL** [comment]
> How about using a number like XMLHttpRequest.readyState ? I'm not sure if it's going to be like a magic number. [developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/readyState](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/readyState)

Nice idea - but I think e.g. `OPENED` and `HEADERS_RECEIVED` might not be applicable here. But I can align with the terminology if it makes sense. The original one was based on common state machine pattern 😋

**Comment by YuriFontella** [comment]
@Baroshem i agree, I would like only the pending to start false if the immediate is also false. It would make more sense.

**Comment by manniL** [comment]
@Baroshem 

I am more than sure that this feature will be used mainly by people who want to have granular control over their fetch flow. For (I guess) 80+% of the users, `pending` should be enough.

**Comment by Baroshem** [comment]
I see @manniL . Then it makes sense to work on that as a more advanced sokution to geting the status of the request.

You convinced me 😉

**Comment by beyer-johannes** [comment]
A simple property of type boolean whould be nice. Therefor it's pretty simple usable as `pending` is. Like `<input :disabled="loading"/>`. 

With a more complex status object, it breaks the simple and clear dx of useFetch. It's just my view :) 

Please tell me if I can help to implement this feature, it's a good first issue for me.

**Comment by danielroe** [comment]
@beyer-johannes We'd prefer to implement as `status` with a text value instead of adding another boolean. But you'd be very welcome to tackle it 😊

**Comment by BlackYuzia** [comment]
What if we just use numbers?
Then we could use like:

`:loading="pending === 2"` or `:loading="state >= 2 && state <= 5"` or `state > 0`
just like example

Anyway, we also could define custom statuses if we required them? ~~Hope not. I just want `pending` as well with `false` value by default :c~~
```ts
// useFetch options
cons {myState} = await useFetch("...", {
 myState: (state) => state  > 0 && state < 2 // pending 
})
```

**Comment by beyer-johannes** [comment]
@BlackYuzia my problem with number is, if i don't know them by rote, I don't know which number does mean what. I give me a try to implement this feature with text values.

**Comment by manniL** [comment]
Exactly, no magic numbers, so strings are a bit more explicit in case you do not use the enum straight away 😋 

As explained in https://github.com/nuxt/nuxt/issues/18810#issuecomment-1433502074, setting ` pending` to `false` would be a breaking change

**Comment by trandaison** [comment]
@manniL Do you have any release plan for this feature?

**Comment by manniL** [comment]
This is up for grabs to implement as a good first issue @trandaison ☺️

**Comment by Lukiticas** [comment]
Hi guys, i'm facing the same problem, i have to implement a loading state in my app, how can i work around this issue while the feature is being implemented? @manniL

**Comment by zephyr-66** [comment]
@manniL When are you planning to add a new status?, There are many requirements to track the status of requests

**Comment by zephyr-66** [comment]
Now we can only: loading="pending&&!! data", which makes it unattractive. @manniL

**Comment by manniL** [comment]
@zephyr-66 @Lukiticas As this is a good first issue, I'd prefer leaving the implementation up to a new (or rather new) contributor ☺️

**Comment by nicolaspayot** [comment]
@manniL is this still up for grabs? I'd like to give a shot if no one is trying already.

**Comment by danielroe** [comment]
@nicolaspayot Go for it!

**Comment by howard-tzw** [comment]
@manniL @danielroe 


I believe that you haven't addressed the problem based on the requirements but instead provided a more complex and impractical solution. This requirement stems from issue #15714, which I consider to be a bug that needs to be resolved. Most people intuitively interpret "pending" as equivalent to "sending a request."

> @feelixe
> Let's say you want to display a loading spinner while the handler is being executed with immediate: false. You obviously don't want that spinner to be visible before the handler has been called, which will be the case if you condition the rendering of the spinner on "pending."

I don't think a breaking change would be a hindrance because it is indeed a bug and a poor developer experience that needs to be addressed. I believe the current approach is not a good solution, and the Nuxt team should give more importance to this issue.

**Comment by danielroe** [comment]
@howard-tzw I would be interested to know why you find a `status` property to be 'more complex and impractical'?

**Comment by feelixe** [comment]
I'm not sure it applies but I guess you could combine both, keep status, and add computed properties liks `isLoading`, `isPending`. Kind of like how react-query is doing it.

**Comment by trandaison** [comment]
@howard-tzw  With new proposal, you hav to change like this
```diff
- v-if="pending"
+ v-if="status === 'pending'"
```
A little more longer.

@danielroe For me (and most developers I guess), status `idle` is useless, what we really care is `pending` (loading) or not, that's it.
Checking `status === 'pending'` is okay, but we should make it shorter, cuz we can, we already have `data` stands for the success status, `error` stands for the error status.
