### ISSUE TITLE
How create subdomains routes in Nuxt 3 ?

### ISSUE THREAD

**Issue by Andrey1906** [nuxt/nuxt#18829]
### Describe the feature

Is it currently possible to implement subdomain routing as it was in Nuxt 2 via @nuxt/router ?

### Additional information

- [x] Would you be willing to help implement this feature?
- [x] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
Please refer to the [discussions we have about the topic](https://github.com/nuxt/nuxt/discussions?discussions_q=subdomain).
