### ISSUE TITLE
defineNuxtRouteMiddleware 'from' route equals 'to' route at first navigation

### ISSUE THREAD

**Issue by Alphamarine** [nuxt/nuxt#18826]
### Environment

Nuxi 3.1.2

RootDir: /home/projects/github-tzjxjx
Nuxt project info: 

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `2.1.1`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-tzjxjx?file=pages%2Findex.vue,middleware%2Frouter.global.js

### Describe the bug

https://nuxt.com/docs/guide/directory-structure/middleware#format

Nuxt middlewares are the suggested way to implement vue router navigation guards. 
The 'from' route in a global route middleware is exactly the same as the 'to' route when navigating to the app for the first time. With a normal vue + vue-router installation, instead, the 'from' route is empty, allowing to detect the first navigation, for example through 'from.name'

**Comment by danielroe** [comment]
This is the case because the router is initialised first, then plugins run to allow them to interact with the router and add any middleware they want, and _then_ the initial route is re-pushed/replaced. If you want to detect the first navigation, you can check `nuxtApp.isHydrated` - it will be false while the app initialises.

**Comment by terion-name** [comment]
> This is the case because the router is initialised first, then plugins run to allow them to interact with the router and add any middleware they want, and _then_ the initial route is re-pushed/replaced. If you want to detect the first navigation, you can check `nuxtApp.isHydrated` - it will be false while the app initialises.

@danielroe  but what I do — is strictly from documentation https://nuxt.com/docs/api/utils/define-nuxt-route-middleware

I need a route middlware, global, with access to route params.
If the docs are misleading — how to make this correctly and update the docs please
