### ISSUE TITLE
SSG doesnt work

### ISSUE THREAD

**Issue by loremru** [nuxt/nuxt#18822]
### Environment

Nuxt project info:                                                                                                                                                        18:30:44

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `2.1.1`
- Package Manager:  `yarn@3.2.1`
- Builder:          `vite`
- User Config:      `ssr`, `modules`, `css`, `windicss`, `nitro`
- Runtime Modules:  `nuxt-windicss@2.6.0`
- Build Modules:    `-`
------------------------------

### Reproduction

`npx nuxi generate`

### Describe the bug

Actually there is empty body without content and it is same spa mode)
![image](https://user-images.githubusercontent.com/66596500/217013216-cff487b0-bc7f-447c-afc7-cd4a165884f7.png)

![image](https://user-images.githubusercontent.com/66596500/217013818-0341ae08-3f82-47fd-bdd6-5e8fbcee1ee7.png)

### Additional context

please expand docs if i did something wrong

**Comment by manniL** [comment]
If you set `ssr: false`, you won't receive prerendered routes.
Remove the option and everything should be fine.

**Comment by loremru** [comment]
> If you set `ssr: false`, you won't receive prerendered routes. Remove the option and everything should be fine.
> 
> [Docs](https://nuxt.com/docs/getting-started/deployment#static-hosting):
> 
> > Using `ssr: false` to produce a pure client-side output.

@manniL
yeah its fine. This description in docs is so confusing...

**Comment by loremru** [comment]
@manniL is there is a way to remove "/" in path before "_nuxt"

**Comment by manniL** [comment]
Not sure what the idea is *but* you can change the baseURL during runtime.
