### ISSUE TITLE
Provide in server plugin

### ISSUE THREAD

**Issue by ElYaiko** [nuxt/nuxt#18833]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.1`
- Package Manager:  `npm@9.4.1`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `css`, `build`, `modules`, `vite`, `experimental`, `nitro`
- Runtime Modules:  `()`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-bn6hoo?file=plugins/test.server.ts

### Describe the bug

I'm trying to provide a variable to be used later on the client but when using `provide` in a server plugin doesn't let me with `return.provide` neither `nuxtApp.provide`. 

### Additional context

For the moment I can pass a variable later on the client only with `nuxtApp.payload` but this is not automatically typed like provide.

**Comment by danielroe** [comment]
providing something on the server makes it available everywhere on the server via `useNuxtApp()` but it does not transfer it to the client. Instead, you can pass it to the client via payload and then provide it again from the plugin on the client .

**Comment by ElYaiko** [comment]
> providing something on the server makes it available everywhere on the server via `useNuxtApp()` but it does not transfer it to the client. Instead, you can pass it to the client via payload and then provide it again from the plugin on the client .

It works well but when you have functions in the object you want to pass in `payload`, they're parsed as `Proxy(object)` I tried using hooks but they cannot provide too to the client, also tried with the rest of props of the `nuxtApp` but none works... any help please?

**Comment by manniL** [comment]
> It works well but when you have functions in the object you want to pass in `payload`, they're parsed as `Proxy(object)` I tried using hooks but they cannot provide too to the client, also tried with the rest of props of the `nuxtApp` but none works... any help please?

Serializing and de-serializing functions is not intended, so you should not pass them but instead re-create them on the client-side.

**Comment by ElYaiko** [comment]
> > It works well but when you have functions in the object you want to pass in `payload`, they're parsed as `Proxy(object)` I tried using hooks but they cannot provide too to the client, also tried with the rest of props of the `nuxtApp` but none works... any help please?
> 
> Serializing and de-serializing functions is not intended, so you should not pass them but instead re-create them on the client-side.

I cannot re-create them in the client-side because the idea I'm trying to do is to prepare this functions from the server side to the client side, I cannot neither load plugins from the server side to the client using `use`, any idea please?
