### ISSUE TITLE
`preloadRouteComponents` allows passing values of type `RouteLocationRaw`

### ISSUE THREAD

**Issue by Mini-ghost** [nuxt/nuxt#18845]
### Describe the feature

Currently, `preloadRouteComponents()` only allows the first parameter to be a string, but sometimes we may pass an object for `to` of `<NuxtLink />`. This can cause many of the same routes path to be considered not preloaded, like bellow:

```html
<!-- Passing a string -->
<NuxtLink to="/home"> Home </NuxtLink>

<!-- Passing a string with query string -->
<!-- `router.resolve('/home?year=2023').path` is `/home` -->
<NuxtLink to="/home?year=2023"> Home </NuxtLink>

<!-- Passing a object -->
<!-- `router.resolve({ name: 'home', query: { year: '2023' } }).path` is `/home` -->
<NuxtLink :to="{ name: 'home', query: { year: '2023' } }"> Home </NuxtLink>
```

These routing paths are all '/home', but all of them will run preload without early return, although the request will not actually be sent.

---

Maybe we can allow passing an object or string of type `RouteLocationRaw` and use the `path` returned by `router.resolve()` as the preloaded record?

The `preloadRouteComponents()` will like bellow:

```ts
function preloadRouteComponents(to: RouteLocationRaw, router?: Router): Promise<void>
```

I don't know if it fits the core team's thinking.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
Sounds reasonable to me 👍🏻
