### ISSUE TITLE
Response status code is not 404 but 200 with custom pages/404.vue

### ISSUE THREAD

**Issue by abbas-91** [nuxt/nuxt#18844]
### Environment

Operating System: windows
Node Version: v16.13.2
Nuxt Version: 2.15.8
Package Manager: npm@8.4.0
Bundler: webpack
User Config: -
Runtime Modules: -
Build Modules: -
target: 'static'

### Reproduction

similar this: 
https://stackblitz.com/edit/github-tpmisr

but in nuxt 2

### Describe the bug

When using a pages/ directory and navigating to non existent page, result is a default nuxt 404 page and statusCode = 404. This is expected
After adding a custom pages/404.vue page, the content of the page is returned as expected, but statusCode = 200 which is not expected*

Additional context
this issue is fixed in [#12913](https://github.com/nuxt/nuxt/issues/12913) but in nuxt 3, how can i fix in nuxt 2?

**Comment by zeelrupapara** [comment]
I think this solution might be helpful because it works for me in vue2:
##### Create layout  (ex: `layouts/error.vue`)
```javascript
<template>
  <div class="mt-5">
    <div>
      <h4 v-if="error.statusCode.toString().startsWith('4')">Page not found</h4>
      <h4 v-if="error.statusCode.toString().startsWith('5')">Oops, something went wrong</h4>
    </div>
    <div class="mt-3">
      <button to="/">Back to Home</button>
    </div>
  </div>
</template>
<script>
export default {
  props: {
    error: {
      type: Object,
      required: true,
    },
  },
}
</script>
```

**Comment by mokey1991** [comment]
@zeelrupapara 
thanks for your response , But I have created this file (layouts/error.vue) and when requesting a page(ex: mysite.com/fake-url) that does not exist ,get response (mysite.com/fake-url) with status code '200' from (ServiceWorker) wich show my error.vue  content.

**Comment by agracia-foticos** [comment]
Same issue

**Comment by Likilee** [comment]
Same issue.. (Actually, I'm using unplugin-vue-router in my Vue 3 project without Nuxt and encountered the same issue.)

**Comment by ellie-jones** [comment]
I just had had to set
`fallback: '404.html',`

in generate in nuxt.config.js (using nuxt 2) https://v2.nuxt.com/docs/configuration-glossary/configuration-generate/#fallback

**Comment by manniL** [comment]
FYI:

When prerendering the whole page (CDN only, no "running Nuxtu server"), you have two options when serving files via SPA fallback (which you should):

* All 200s, also "invalid" / 404 pages
* All 404s, also "dynamic" non-prerendered pages

This is simply because only Nuxt knows if the pages are valid or not, but not the web server that serves the content.
