### ISSUE TITLE
Prerendering server component with `<component :is="prop">` fails

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt#18855]
### Environment

Stackblitz

### Reproduction

1. Open https://stackblitz.com/edit/nuxtissues18855
2. Run `npm run generate`
3. See the error `str.replace is not a function`.

<img width="798" alt="image" src="https://user-images.githubusercontent.com/640208/223403460-ab3ebbc6-a555-4bad-ba50-a2c8b182caa1.png">

### Describe the bug

When using a `.server.vue` component which uses a prop as tag via `<component :is="">`, pre-rendering via `nuxi generate` fails.

Example component:

```html
<script setup lang="ts">
const props = defineProps<{
  tag: 'h1' | 'h2';
}>();
</script>

<template>
  <component :is="tag">Szia!</component>
</template>
```

`nuxt.config.ts`

```ts
export default defineNuxtConfig({
  experimental: {
    componentIslands: true,
  },
  nitro: {
    prerender: {
      routes: ['/'],
    },
  },
});
```

**Comment by harlan-zw** [comment]
I tried replicating this one. The specific issue seems to be if you provide an undefined value to `:is`, which understandably throws an error. Providing an actual value seems to work correctly.

https://stackblitz.com/edit/nuxtissues18855-zw16uy?file=app.vue

Could you confirm or have I missed something

**Comment by manniL** [comment]
@harlan-zw My bad - played too much with it 😂 Fixed!

**Comment by alex-key** [comment]
@manniL cannot reproduce as there is a syntax bug in the provided stackblitz snippet.
```
<template>
  <div>
    <TheHeading :tag="h1" /> // in the snippet
    <TheHeading tag="h1" /> // as it should be
  </div>
</template>
```

Also works for me like this
```
// app.vue
<template>
  <div>
    <TheHeading :tag="h1" />
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const h1 = ref('h1');
</script>
```

Please, clarify the issue

**Comment by manniL** [comment]
@alex-key Indeed, thanks. Fixed that in the reproduction ☺️

As written above, run `pnpm generate` to see the error
