### ISSUE TITLE
Server components do not support `<slot>`s

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt#18853]
Document that experimental server components do not support slots but could be in the future.

**Comment by MiniDigger** [comment]
is there a tracking issue for improvements to server components? I couldn't find anything, should I open one? 
I am particular interested in allowing server components to have client components as children, like next.js explains here https://beta.nextjs.org/docs/rendering/server-and-client-components#moving-client-components-to-the-leaves, for the same benefits as explained on that page (less js to client while still having interactivity where you need it)
