### ISSUE TITLE
node14+ compatibility seems broken in nuxt 2.16.0

### ISSUE THREAD

**Issue by tyriis** [nuxt/nuxt#18868]
### Environment

  System:
    OS: Linux 6.0 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 1.24 GB / 15.32 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.17.4 - ~/.nvm/versions/node/v14.17.4/bin/node
    npm: 8.3.2 - ~/.nvm/versions/node/v14.17.4/bin/npm
  npmPackages:
    nuxt: 2.16.0 => 2.16.0

### Reproduction

starting the application with a systemd service file

```
ExecStart= ****/.nvm/versions/node/v14.17.4/bin/node ****/node_modules/nuxt/bin/nuxt start
```

results in:

```
internal/modules/cjs/loader.js:892
throw err;
^
Error: Cannot find module 'node:fs'
Require stack:
- ****/node_modules/rc9/dist/index.cjs
- ****/node_modules/@nuxt/config/dist/config.js
- ****/node_modules/@nuxt/cli/dist/cli-index.js
- ****/node_modules/@nuxt/cli/dist/cli.js
- ****/node_modules/nuxt/bin/nuxt.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
at Function.Module._load (internal/modules/cjs/loader.js:745:27)
at Module.require (internal/modules/cjs/loader.js:961:19)
at require (internal/modules/cjs/helpers.js:92:18)
at Object.<anonymous> (****/node_modules/rc9/dist/index.cjs:3:17)
at Module._compile (internal/modules/cjs/loader.js:1072:14)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
```

based on this entry: https://stackoverflow.com/a/72378898/21042484 it seems that functionality has been backported but this mean that not all versions are compatible.

It would be great to specify the minimum required version for node14 or node16 for the current version. here: https://github.com/nuxt/nuxt/releases/tag/v2.16.0

### Describe the bug

The minimum required node version is not 14+

**Comment by pi0** [comment]
Do you have issue on latest 14.21.2 as well?

**Comment by tyriis** [comment]
@pi0 I have had `v14.18.1` in my devenv there it worked already, as written in the linked StackOverflow the `node:` prefix has been backported to node 14 and 16. They are just not general available in all node 14 or 16 versions.

**Comment by font-size** [comment]
same issues. But I use nutx@2.15.8, and fix it.
`"dependencies": {
    ...
    "nuxt": "2.15.8",
    ...
  },`

**Comment by tyriis** [comment]
@font-size for sure I can just pin dependency or update node to a newer version.

@pi0 could you provide feedback if this will be added to the documentation/changelog?

**Comment by pi0** [comment]
I think we should. Also inrease 14.x in the engines (+ cli check) to the minimum supporting `node:` protocol. /cc @danielroe

**Comment by danielroe** [comment]
Thanks for reporting this, and apologies for the inconvenience! I've added an engines constraint and updated the runtime check.

**Comment by tyriis** [comment]
@danielroe thank you for the solution.
