### ISSUE TITLE
Why can nuxt3 be accessed normally long after it is started?

### ISSUE THREAD

**Issue by sunnywanggit** [nuxt/nuxt#18860]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.14`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.8.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/sunnywanggit/coverage

This is just an example, not a real project. The real project will be larger than this

### Describe the bug

Why can nuxt3 be accessed normally long after it is started?

**Comment by danielroe** [comment]
I'm not sure what you are asking.

**Comment by sunnywanggit** [comment]
@danielroe  Why nuxt3 cannot be accessed long after  yarn dev ?
