### ISSUE TITLE
[intlify] The message format compilation is not supported in this build. Because message compiler isn't included. You need to pre-compilation all message format. So translate function return 'calendar.days.lun'.

### ISSUE THREAD

**Issue by RijaCloud** [nuxt/nuxt#18866]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `2.1.1`
- Package Manager:  `npm@8.19.3`
- Builder:          `vite`
- User Config:      `app`, `build`, `modules`, `proxy`, `css`, `vite`, `i18n`, `runtimeConfig`, `plugins`, `components`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.9`, `nuxt-proxy@0.3.12`
- Build Modules:    `-`
------------------------------

### Reproduction

This is a minimal reproduction for you to see how I implemented i18n on my application
https://stackblitz.com/edit/i18n-nuxt-warn

### Describe the bug

The problem occur when the project is built. I have several logs.
My question is how can I resolve these warning  ?

### Additional context

Here is my real pm2 log from the project

### Logs

```shell-script
[intlify] The message format compilation is not supported in this build. Because message compiler isn't included. You need to pre-compilation all message format. So translate function return 'calendar.days.lun'.
[intlify] The message format compilation is not supported in this build. Because message compiler isn't included. You need to pre-compilation all message format. So translate function return 'calendar.days.mar'.
[intlify] The message format compilation is not supported in this build. Because message compiler isn't included. You need to pre-compilation all message format. So translate function return 'calendar.days.mer'.
[intlify] The message format compilation is not supported in this build. Because message compiler isn't included. You need to pre-compilation all message format. So translate function return 'calendar.days.jeu'.
[intlify] The message format compilation is not supported in this build. Because message compiler isn't included. You need to pre-compilation all message format. So translate function return 'calendar.days.ven'.
[intlify] The message format compilation is not supported in this build. Because message compiler isn't included. You need to pre-compilation all message format. So translate function return 'calendar.days.sam'.
[intlify] The message format compilation is not supported in this build. Because message compiler isn't included. You need to pre-compilation all message format. So translate function return 'calendar.days.dim'.
[intlify] The message format compilation is not supported in this build. Because message compiler isn't included. You need to pre-compilation all message format. So translate function return 'statut.label.DEFINITIVELY_CLOSED'.
[intlify] The message format compilation is not supported in this build. Because message compiler isn't included. You need to pre-compilation all message format. So translate function return 'statut.label.TEMPORARY_CLOSED'.
```

**Comment by AloisSeckar** [comment]
Might be similar situation to this issue from **nuxt/i18n** repo  https://github.com/nuxt-modules/i18n/issues/1833 ?

**Comment by danielroe** [comment]
Thank you for raising this, and for the excellent reproduction. I think this should probably be raised upstream in https://github.com/nuxt-modules/i18n if it doesn't already exist.

**Comment by learntheropes** [comment]
@RijaCloud did you find a solution for this?  
I have the same issue with `nuxt@3.3.1` and `@nuxtjs/i18n@8.0.0-beta.10`

**Comment by elzodxon** [comment]
Hi I have the same issue.

**Comment by urbgimtam** [comment]
To me, this only happens if in nuxt.config.ts the i18n modules is configured using this format:
```
modules: [
  ["@nuxtjs/i18n", 
     { options }
  ]
]
``` 

Errors don't show up If its configured using: 
```
modules: ["@nuxtjs/i18n"],

i18n: { options }
```

The issue still exists, on nuxt 3.5.3 and @nuxtjs/i18n 8.0.0-beta.11 (beta.12 has a prerendering issue)

**Comment by srabieb** [comment]
I also have the same issue.
