### ISSUE TITLE
Mounted lifecycle hook is triggered when switching between params of a dynamic route.

### ISSUE THREAD

**Issue by roguesherlock** [nuxt/nuxt#18871]
### Environment

```
Nuxi 3.1.2                                                                                                                                               22:27:14
                                                                                                                                                         22:27:15
RootDir: /home/projects/nuxt-starter-ckk3wd                                                                                                              22:27:15
Nuxt project info:                                                                                                                                       22:27:15

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `2.1.2`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `app`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                                                              22:27:15

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com
```

### Reproduction

https://stackblitz.com/edit/nuxt-starter-ckk3wd

### Describe the bug

I'm not sure if it's the intended behaviour so let me know if it is.
When switching between a route parameters of a dynamic route, the component lifecycle event's aren't triggered correctly (at least according to my mental model).
It follows this lifecycle which I think is a bit incorrect, `deactivated`, `mounted`, `activated`. It causes problems for me cause it doesn't clear the even listeners and re-registers new ones.

I think it should either **_not_** trigger a mounted lifecycle or it should trigger a unmounted lifecycle

Note that I have keepalive set to true on the nuxt config.

**Comment by AloisSeckar** [comment]
This exact behaviour is pointed out in [Vue.js docs](https://vuejs.org/guide/built-ins/keep-alive.html#lifecycle-of-cached-instance)

But we would need someone more skilled in the ecosystem to tell us both why.

**Comment by VladStepanov** [comment]
This happens because the components are created and mounted on first render.
In case the component is wrapped in KeepAlive, component will be created, mounted and stored in cache and it won't be rerender again as long as there is KeepAlive.
If you need `mount` and `unmount` lifecycle, either remove KeepAlive or add `:key` to `NuxtPage` `<NuxtPage :key="$route.params.type">`. But if you add a :key, you lose a point of KeepAlive.

**Comment by roguesherlock** [comment]
@VladStepanov I get that lifecycle. i.e. `Created`, `Mounted`, `Activated`. And then the cycle of `Deactivated`, `Activated`. 

But in this case, it goes from `Deactivated` to `Mounted`, `Activated`. I think `Mounted` here is a bug?

**Comment by VladStepanov** [comment]
:roguesherlock No. `Mounted` fires only on first component render. It works as expected. If you render same component again, lifecycle would be `Deactivated`, `Activated`.

As i get you care about remove some listeners in `unmount` event. You could remove listeners in `Deactivated` callback as well.

**Comment by roguesherlock** [comment]
@VladStepanov if you check the stackblitz I linked above, you'd see that it re-fires `Mounted` again when I switch between routes of a dynamic route. 
Ideally I would remove listeners but I use other vueuse which mounts the listeners. I currently have found a workaround by wrapping the hook in effect scope but just kept this here cause I wanted to know if it's a bug or an expected behaviour. 

<img width="129" alt="image" src="https://user-images.githubusercontent.com/5683543/217484903-74d3ee14-f065-4e9b-a32b-6076f2af0e4a.png">

**Comment by AloisSeckar** [comment]
I'll repeat myself about the docs: "When a component instance is removed from the DOM but is part of a component tree cached by `<KeepAlive>`, **it goes into a deactivated state instead of being unmounted**."

When I think about it, it makes perfect sense, because act of unmounting means you are getting rid of all component's state (it will be re-created upon next mount). If you want to keep your component cached, you cannot **_unmount_**  and thus destroy it.

So then only question is, whethe  `onMounted` is necessary when you want to display cached component again. The docs ain't very clear, I'd say. But using common sense: The component probably has to be physically **_mounted_** into DOM to be displayed again. So it makes sense that `onMounted` hook is triggered (along with `onActivated`).

**Comment by roguesherlock** [comment]
@AloisSeckar iirc the default behaviour components inside in keep alive is to activate/deactivate, here's an [example](https://sfc.vuejs.org/#eNrNVlFvmzAQ/isWfUgqBWjXaQ8sqRZpD5OmSXvYnso0EWMSt2Aj26Stovz3fbaBkDTNsu1liYTsu/N333cHB5tgXtfRumFBEkw1Vbw2RDPT1Lep4FUtlSGfZMVIoWRFRlFsNzZ81Lu/Sm1073e7/YC5oiu+3kG0+/2gDVGsINs2yLtIKqgU2hDaKMWE+ZYtyMzGjUeWxugyFV2EyRYavg0OOb4Tu3Bc3KpNmYptKqaxlwmB2BhW1WVmGHaETHO+JrTMtJ6lQc4qmQbODs+iMUbigN3gtw4LqRA0/jmxuS8JF45DGvQhyQN7RgSsQ2OHfjeCI/SoownkZ9SAYbKndTazoGT7Y4DwgZacPgBhryjDLC1lQjYbfxyinYbYp+skfWasnpdI2hpSAyOV6IcALkm45WlF3e1SgUlfIJfzdhr3R1xFfaZ97GmMwmI1jQflxlab59IuI1tr37xCChMWWcXL54ToTOhQM8WL99a3kCpnKiHX9RPRsuQ5uWCMDVyhynLe6IS8qZ+cuc7ynIslDFc4c4OLM1eZWnIRGlkDjFVD20KiRFVC3naxDfKDQ8moSYiATmeVa6aKUj6GTwnJGiNhRJWhZNdVr6dn8A4ErjvQli4IhCUrTM/75qVf8eXqtYC9UlBKnQvN0hKuWnJhmPLhGX1YKtmIPCEXxZX9HxMdAm5od7l7MwQO5CUrWwMvcg+eXdn/i/jI3+BnHGhDXlfY17Stp3+o3b0UTAI/UMIqq6N7LQXmmsNLWwce0cRnsDYMGrtPg5UxtU7iWBfUDqZ7HUm1jLGKVCMMx9BjugoXSj7ifgBwGrjB0mLEMKIaIZ4SkGbqFOZB6AtcCwtFW0jphu3hbCZlJpb2CUT4bk5vpJjbGuPxyidEii+ob7v8Lqrd5iNzrbBh7bxt6+DKZG/u7uh4fElmt1217KSVJYtKuRynQQvopm0aYBSDtbva8z2PUwg9i+MYPedTGE0XdBxjIPUUSr4LO8Q5923hh6EHdy/Mfiq+MgDR3v5d+T/315H81wYfB/nDDh8H+YsWHwINenxmh/03zxktHnzr2Cafh959MP0Wf/sLGvxGXQ==),

**Comment by roguesherlock** [comment]
here's what the docs say,

> When a component is toggled inside <KeepAlive>, its activated and deactivated lifecycle hooks will be invoked accordingly, providing an alternative to mounted and unmounted, which are not called. This applies to the direct child of <KeepAlive> as well as to all of its descendants.

**Comment by AloisSeckar** [comment]
Now I am delving deeper into your example. I start believing it actually works as that, but the messages from different components are mixing up in the console.

I tried adding `useRoute().params.type` into the log messages. Initially there is some "empty" component without any type - it gets `mounted` and `activated` when the app starts. Then if you click `Route 1` this unnamed component gets `unmounted`, component 1 gets `mounted` and `activated`. And so on. Thats why you read _unmounted-mounted-activated_ sequence, but it is not from one lifecycle. Once all three components get mounted for the first time, the message won't ever appear again.

Try with this - https://stackblitz.com/edit/nuxt-starter-696yxp?file=pages%2F[[type]]%2Findex.vue

**Comment by manniL** [comment]
FYI_ This seems to be [a valid upstream behavior](https://stackblitz.com/edit/nuxt-issues-18871-ssr?file=src%2Fpages%2FRoute.vue,src%2Frouter.ts,src%2Fpages%2FItem.vue,src%2FApp.vue)!

The only difference is that nuxt actually remounts/re-activates components for dynamic routes and vue router does not by default.
