### ISSUE TITLE
`nuxt build --standalone` fails on 2.16

### ISSUE THREAD

**Issue by erikuit** [nuxt/nuxt#18873]
### Environment

System:
OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
Memory: 4.01 GB / 15.43 GB
Container: Yes
Shell: 5.0.17 - /bin/bash

Binaries:
Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm

npmPackages:
nuxt: ^2.15.8 => 2.16.0

### Reproduction

The problem occurs on a fresh Nuxt 2 install after `npm init nuxt-app <project-name>`

### Describe the bug

`npx nuxt build --standalone` fails with a fatal error:

```
ERROR in ./node_modules/node-fetch-native/dist/index.cjs 69:2
Module parse failed: Unexpected character '#' (69:2) 
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  */
| class BlobDataItem {
>   #path
|   #start
| 
 @ ./node_modules/node-fetch-native/lib/index.cjs 1:18-46
 @ ./.nuxt/server.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./.nuxt/server.js
```

### Additional context

A simple `npx nuxt build` does work without problems. However, @nuxtjs/vercel-builder uses the standalone option so right now I can't deploy 2.16 on Vercel.

**Comment by GelsDEV** [comment]
I'm currently stuck on the same error with Vercel.

`nuxt: 2.16.0`
`@nuxtjs/vercel-builder: 0.22.1`

Also on my local machine `npx nuxt build` works, but `npx nuxt build --standalone` fails with a fatal error.
Node.js: 16.19.0
npm: 8.19.3

**Comment by volk234** [comment]
same error
![Screenshot_1](https://user-images.githubusercontent.com/22075711/217335165-c2d3c3fa-60d7-4f92-9cf7-65ea539979ae.png)

**Comment by mbellogularte** [comment]
same here

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/10751.
