### ISSUE TITLE
SSG create a browser freez site

### ISSUE THREAD

**Issue by StefanoTesla** [nuxt/nuxt#18876]
### Environment

Nuxt project info:                                                                                                                                                                  10:29:22

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v19.4.0`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `2.1.2`
- Package Manager:  `npm@9.2.0`
- Builder:          `vite`
- User Config:      `pages`, `css`, `modules`, `i18n`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.9-27926914.891e694`
- Build Modules:    `-`
------------------------------

### Reproduction

You can check here https://test.stefanotesla.it

### Describe the bug

Once I generate the Project and I load static files on the server, the site seems to have an infinite load loop.
Some times is impossible to open dev tool olso, no errors in console.

**Comment by StefanoTesla** [comment]
> Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

https://github.com/StefanoTesla/nuxtproject

Yo can take the whole project...there'ere just 2 pages

**Comment by danielroe** [comment]
This seems to be coming from `@nuxtjs/i18n`. Would you raise an issue there instead? 🙏

**Comment by StefanoTesla** [comment]
Thank you for your time 🙂
