### ISSUE TITLE
nuxt preview path error

### ISSUE THREAD

**Issue by xjccc** [nuxt/nuxt#18879]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `2.1.1`
- Package Manager:  `pnpm@7.24.3`
- Builder:          `vite`
- User Config:      `typescript`, `app`, `nitro`, `experimental`, `sourcemap`, `build`, `runtimeConfig`, `css`, `vite`, `ignore`, `hooks`, `modules`, `errorCacheConfig`
- Runtime Modules:  `nuxt-error-and-cache@1.0.4`, `nuxt-custom-fetch@1.0.7`, `@vueuse/nuxt@9.12.0`, `@pinia/nuxt@0.4.6`
- Build Modules:    `-`

### Reproduction

in nuxt.config.ts
`
nitro: {
    output: {
      dir: '~/node-server'
    }
  }
`

### Describe the bug

the server code in node-server
then use preview
the error is
Cannot find nitro.json. Did you run nuxi build first? Search path:
 [
  '~/.output/nitro.json',
  '~/nitro.json'
]

**Comment by danielroe** [comment]
I think you should be able to run `nuxi preview node-server` in this case - does this work for you?

**Comment by xjccc** [comment]
> 

yes . i know this thanks😁

**Comment by xjccc** [comment]
> I think you should be able to run `nuxi preview node-server` in this case - does this work for you?

yes, i know this thanks😁
