### ISSUE TITLE
useCookies updates only on nextTick

### ISSUE THREAD

**Issue by Flashantik** [nuxt/nuxt#18881]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `2.1.2`
- Package Manager:  `npm@8.11.0`
- Builder:          `webpack`
- User Config:      `srcDir`, `builder`, `modules`, `app`, `proxy`, `image`, `runtimeConfig`, `webpack`, `build`, `router`, `css`
- Runtime Modules:  `@pinia/nuxt@0.4.6`, `@nuxt/image-edge@1.0.0-27919678.2f5b64b`, `@nuxtjs/tailwindcss@6.3.1`, `@nuxt-alt/proxy@2.2.0`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-yhreot?file=app.vue

### Describe the bug

If you change value on useCookie() and after that try to get the same cookie you will get old value of cookie. But on nextTick value will change

**Comment by smilosevic** [comment]
This is expected behavior from Vue. 
From vue [documentation](https://vuejs.org/guide/essentials/reactivity-fundamentals.html#dom-update-timing):

> However, it should be noted that the DOM updates are not applied synchronously. Instead, Vue buffers them until the "next tick" in the update cycle to ensure that each component updates only once no matter how many state changes you have made.

I think the same principle applies to `useCookie`. If you want to read a value from a variable, you can use `username.value`. no need to initialize a new one.

**Comment by danielroe** [comment]
This is the case - we use watch to set the cookie.

I think nuxt/nuxt#13020 is the issue to follow, however - a shared cookie state should resolve the issue.
