### ISSUE TITLE
Composable auto-imports break when modified, `useXXX` is not defined (`pnpm run dev`/`npm run dev`)

### ISSUE THREAD

**Issue by dodo021** [nuxt/nuxt#18897]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `2.1.2`
- Package Manager:  `pnpm@7.17.1`
- Builder:          `vite`
- User Config:      `css`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

1. Start the dev server with `pnpm dev` or `pnpm run dev`
2. Edit a composable return
3. Refresh your web page and an error 500 should appear saying your composable useXXX is not defined

pnpm: https://stackblitz.com/edit/github-ywg4lu?file=composables%2FuseFoo.ts
npm: https://stackblitz.com/edit/github-1hay52-amtd8x?file=composables%2FuseNetwork.js _(edit @lihbr)_

If you stop and restart the server with `pnpm dev` or `pnpm run dev` it work again until you edit your composable again.

### Describe the bug

Starting the dev server with `pnpm dev` or `pnpm run dev` break the auto-load or something related when a composable is modified.
Everything work as expected if I use `pnpm nuxi dev` _(edit @lihbr `npx nuxi dev` doesn't seem to fix it the same way)_

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by dodo021** [comment]
Sure !
https://stackblitz.com/edit/github-ywg4lu?file=composables%2FuseFoo.ts

I added some comments to reproduce the problem. I hope the instructions are clear. 😄

**Comment by danielroe** [comment]
I can't reproduce this in stackblitz - can you?

**Comment by dodo021** [comment]
I have made a video. Hope this will help.

https://streamable.com/kvbved

**Comment by manniL** [comment]
Can reproduce 👍🏻

**Comment by dodo021** [comment]
Hello everyone,
I don't know if something was fixed in the last updates, but now when I use `export default function() {}` to create my composable, the error 500 never happens.
The error only occurs when `export const useFoo = () => {}` is used.
I hope it will help 😄

**Comment by tammai** [comment]
I have a same issue too. If HMR several times (by edited any files in /composables), random '<composable_name> is not defined' error happened. Stop and restart it will back to normal.

**Comment by danielroe** [comment]
cc: @antfu

**Comment by danielroe** [comment]
@manniL Can you provide any more information about how to reproduce? 🙏

**Comment by alessioraggioli** [comment]
Sorry I don't understand if you need more information to reproduce it or not.
The issue is still persisting for me.

**Comment by binhntfiber** [comment]
Any solution for this issue? It is annoying when you just edit one line in composable and need to stop and restart the dev server again

**Comment by jorge-vnarvaez** [comment]
> Any solution for this issue? It is annoying when you just edit one line in composable and need to stop and restart the dev server again

For me work this

`const useNetworkLatencyComposable = async (url) => {
    console.log(url)
}

export function useNetworkHealth() {
    return {
        useNetworkLatencyComposable
    }
}`

you should define each function as an arrow function and export a global function with variables, function inside composable js file.

I tried to use export function functionName() {} but having some problems.

**Comment by manniL** [comment]
> @manniL Can you provide any more information about how to reproduce? 🙏

@danielroe I can exactly reproduce as described in the StackBlitz ☺️ 
But only when I fork the original repo by changing the content first. (that part is not in the video)

[nuxt-18897.webm](https://github.com/nuxt/nuxt/assets/640208/93355707-caa4-46d7-a6a0-10fabc65c6f9)

**Comment by lihbr** [comment]
As demonstrated in #21673, this might not be related to pnpm only(?) I've updated the title to better reflect that for visibility.
