### ISSUE TITLE
Import json inside `nuxt.config.ts` has no default

### ISSUE THREAD

**Issue by zumm** [nuxt/nuxt#18899]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.1.3`
- Builder:          `vite`
- User Config:      `vite`, `app`, `modules`, `postcss`, `css`, `imports`, `runtimeConfig`, `nitro`
- Runtime Modules:  `@vueuse/nuxt@9.4.0`, `nuxt-simple-sitemap@1.0.7`
- Build Modules:    `-`
------------------------------

### Reproduction

-

### Describe the bug

Dynamic import json inside `nuxt.config.ts` returns deserialized content directly without `default` wrapper. Meanwhile type of returning value contains `default`.

```ts
import('./package.json').then((v) => console.log(v)) // { version: 'x.x.x', ... }

typeof v // { default: { version: 'x.x.x', ... } }
```

**Comment by danielroe** [comment]
This is likely an upstream issue with https://github.com/unjs/jiti.

cc: @pi0

**Comment by pi0** [comment]
Thanks for issue. Fixing in https://github.com/unjs/jiti/pull/114

**Comment by danielroe** [comment]
This should be resolved in the latest Nuxt release (or in previous releases you can update your lockfile to pull in the latest `jiti`.)
