### ISSUE TITLE
Vue Router Warn on Node server (too much)

### ISSUE THREAD

**Issue by nickryz** [nuxt/nuxt#18898]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `2.1.2`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

[>>Reproduction Link](https://stackblitz.com/edit/github-7zeqqg?file=pages%2Findex.vue,app.vue)

Steps:
 1. Buid project SSR ('npm run build')
 2. Start the server in inspect mode ('node --inspect .output/server/index.mjs')
 3. Open DevTools for node

### Describe the bug

 I got a lot of warnings in the console in DevTools with the flag --inspect for node. This is a started project (v3.1.2) just with one page (it has just one title h1). If I remove a 'pages' directory - warnings are gone.
 
<img width="1432" alt="Знімок екрана 2023-02-08 о 19 14 41" src="https://user-images.githubusercontent.com/32298719/217614394-8886f239-e776-4a10-9db0-259f0ac10e39.png">

**Comment by danielroe** [comment]
I can't reproduce. It looks to me like somehow there are links to `/json` and `/json/version` in your page, which vue-router is attempting to resolve. I would guess maybe you have a service worker installed that's serving up a page from another site?
