### ISSUE TITLE
Nested route does not wait for parent route to finish setup

### ISSUE THREAD

**Issue by adamcikado** [nuxt/nuxt#18906]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `2.1.2`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-k2bwh5

1. Click "Go to clients"
2. Click "Go to client" on /clients page
3. Rendering breaks as the nested route is being rendered before useAsyncData is resolved and result provided to children route

If you would click on "Go to client" from index page, it works perfectly fine, as it's not nested route.

### Describe the bug

The nested route is being rendered before parent route's setup is done (when using async setup) if navigating from other nested route.

**Comment by danielroe** [comment]
Let's track this in https://github.com/nuxt/nuxt/issues/13814.
