### ISSUE TITLE
Nuxt3: run build / start has no host

### ISSUE THREAD

**Issue by gregg-cbs** [nuxt/nuxt#18913]
### Environment

Windows 11
nuxt: "^3.1.1
node: v16.14.0

### Reproduction

This is a brand new nuxt install, there is no funny business happening.

### Describe the bug

When doing `npm run build` and then running the server using the command from the documentation `node .output/server/index.mjs` the host is empty when the server runs:
`Listening http://[::]:3000`

This happens on my pc and the server that I deploy to.

According to the documentation this should run on localhost. The documentation does not tell you how to specify the host or port in the terminal command or how to set it in nuxt config.

https://nuxt.com/docs/getting-started/deployment

**Comment by StefanoTesla** [comment]
:: is the IPv6 manienra to say localhost

**Comment by gregg-cbs** [comment]
Thats so blind!! lol im such a dweeb. Thanks. I ended up modifying the pm2 config to this and i now have it working as I want. The config in the docs didnt quite cut it.
```
module.exports = {
  apps : [
    {
      name: 'orders-dashboard',
      exec_mode: 'fork',
      instances: 1,
      script: './.output/server/index.mjs',
      env: {
        NODE_ENV: "production",
        HOST: "127.0.0.1",
        PORT: '3002'
      },
    }
  ]
}
```
