### ISSUE TITLE
Nuxt3: Copy static files into .output directory

### ISSUE THREAD

**Issue by gregg-cbs** [nuxt/nuxt#18918]
### Describe the situation

I am trying to copy static files into the .output directory using vite plugins but it seems the plugins run in between the build and the files it copies get removed.

The file will show in the .ouput directory for a second or two and then gets overwritten.. probably because nuxt build is removing the .output folder.

Any other ideas on how to do this?
```js
// https://nuxt.com/docs/api/configuration/nuxt-config
import { viteStaticCopy } from 'vite-plugin-static-copy'
import { normalizePath } from 'vite'
import path from 'node:path'

export default defineNuxtConfig({
  pages: true,
  modules: ["nuxt-windicss"],
  vite: {
    plugins: [
      viteStaticCopy({
        targets: [
          {
            src: normalizePath(path.resolve(__dirname, 'data/orders.json')),
            dest: path.resolve(__dirname, '.output/server')
          }
        ]
      })
    ] 
  }
})

```

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
Related: https://github.com/nuxt/nuxt/issues/15779#issuecomment-1397418353

**Comment by danielroe** [comment]
You can add your directory to `nitro.publicAssets` and nitro will copy the files for you...:

```js
export default defineNuxtConfig({
  nitro: {
    publicAssets: [
      // your directory
    ]
  }
})
```

**Comment by gregg-cbs** [comment]
I appreciate this but the data is not a public assets, its private server only data.
To achieve what I wanted I added a shell command after the build script in package.json:

```js
"build": "nuxt build && cp server/data/orders.json .output/server/",
```

and then I had to specify the path to the file on dev and prod:
```js
const ORDERS_FILE_LOCATION = process.env.NODE_ENV === 'development' ? 'server/data/orders.json' : `${__dirname}/orders.json`
```

**Comment by manniL** [comment]
> I appreciate this but the data is not a public assets, its private server only data so i want to put it in the server folder.
To achieve what I wanted I added a shell command after the build script in package.json:

Then you can use the [server assets folder](https://nitro.unjs.io/guide/introduction/assets) for it ☺️

**Comment by madebyfabian** [comment]
Hi @manniL,
I have a similar issue, and it seems that the nitro serverAssets config does not work in my case.

My repo structure:

- apps/web/**_my nuxt app_**
- packages/mail/mails/**_some stuff I need in my server build_**

So I tried this config:
```ts
nitro: {
  serverAssets: [
    {
      baseName: 'emails',
      dir: '../../../packages/mail/emails', // relative to `/apps/web/server`
    },
  ],
},
``` 

With this code inside an api handler.
```
import { readdir } from 'fs/promises'
const dirData = await readdir('./server/assets/mails', { withFileTypes: true })
```

After build, it errors, saying that the `/server/assets` folder does not exist. Which is true:
![Bildschirmfoto 2023-10-15 um 19 16 46](https://github.com/nuxt/nuxt/assets/32813692/4f928585-143f-4861-b3f0-a674cfa42390)

Am I missing something? Thanks in advance!

**Comment by madebyfabian** [comment]
@felixranesberger unfortunately not, I ended moving those files from my package into the Nuxt app directly.

**Comment by grexen** [comment]
Using 'fs' didn't work for me either. Did you try using the use `useStorage().getItem()` composable function? @madebyfabian

**Comment by madebyfabian** [comment]
@grexen not yet, let me know if this solves it :)

**Comment by grexen** [comment]
Hey @madebyfabian, yes did work out out for me - hope this helps!

**Comment by KyleXie** [comment]
I managed to figure it out by using Nuxt [hooks](https://nuxt.com/docs/api/advanced/hooks#app-hooks-runtime):

```
import { cpSync } from 'node:fs';
import path from 'node:path';

export default defineNuxtConfig({
 hooks: {
    'nitro:build:public-assets': (nitro) => {
      // copy email templates to .output/server/emails
      const targetDir = path.join(nitro.options.output.serverDir, 'emails');
      cpSync('./emails', targetDir, { recursive: true });
    }
  }
});
```

**Comment by vanminhquangtri** [comment]
Hello All, it's now Apr 2024, is there a solution for this?
My problem is all file that I copy to folder .output after run build, they all error 404.
Thanks

**Comment by danielroe** [comment]
@vanminhquangtri see https://volta.net/nuxt/nuxt/issues/18918#comment-1812722.

If you have more specific needs, feel free to raise in Discord or open a discussion. It's surely possible 😊

**Comment by Harm-Nullix** [comment]
The problem is that ViteStaticCopy does the copy AFTER the build to _.nuxt_ folder, but BEFORE the build folder (in my case _.output_) is cleaned.
So either the hook of ViteStaticCopy should be change-able, or this is a no fix, at least for Nuxt.

**Comment by danielroe** [comment]
@Harm-Nullix This is definitely currently working with `nitro:build:public-assets`. If you have an issue please open a new issue/discussion with a reproduction 🙏

**Comment by kylebuch8** [comment]
> > I appreciate this but the data is not a public assets, its private server only data so i want to put it in the server folder.
> > To achieve what I wanted I added a shell command after the build script in package.json:
> 
> Then you can use the [server assets folder](https://nitro.unjs.io/guide/introduction/assets) for it ☺️

Looks like the URL ^^ is now a 404. I think this link is where your URL should point now.
https://nitro.unjs.io/guide/assets#server-assets

**Comment by typed-sigterm** [comment]
But `nitro.publicAssets` is for dir copying, it doesn't work when copying a single file
