### ISSUE TITLE
Nuxt history state

### ISSUE THREAD

**Issue by alexkarpen** [nuxt/nuxt#18916]
### Describe the feature

The follows refers to 2.x
I had a problem with back and forward history transitions. They retrigger asyncData which was bad for performance, ux for positional ui and more.
I have found https://github.com/hidekatsu-izuno/nuxt-history-state and i think a feature like this should be in native nuxt package for ssr targets.

If you find it obsolete ignore me, it certainly saved my state management.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Thank you for this suggestion. We're not looking to add new features to Nuxt 2.x at this point. If you encounter any issues with this in Nuxt 3, please feel free to open a feature request or bug report.
