### ISSUE TITLE
Nuxt plugin does not provide an export named executeAsync, from unctx lib

### ISSUE THREAD

**Issue by calebeaires** [nuxt/nuxt#18924]
### Environment

Node 19
Nuxt: 3.1.2
@nuxt/kit: 3.1.2
@nuxt/schema: 3.1.2
@nuxt/module-builder: ^0.2.1

### Reproduction

Giving the files above, While create a Nuxt Module, after "**publish**" on npm

Plugin: locale.ts
```js
import { defineNuxtPlugin, useRuntimeConfig } from '#imports';
import { $fetch } from 'ohmyfetch';
import { get } from 'lodash-es';

export default defineNuxtPlugin(async (nuxt) => {
    const generateEndpoint = (url: string) => {
        return useRuntimeConfig().public.endpoint + '/core/' + url;
    };

    const labels = await $fetch(generateEndpoint('label/render'), {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            envApi: useRuntimeConfig().public.envApi
        },
        body: {}
    });

    nuxt.vueApp.config.globalProperties.$l = (v: string) => (get(labels, v) ? get(labels, v) : v);
});


```

Module

```js
     addPlugin(resolve(runtimeDir, 'plugins/locale.server'));
```

### Describe the bug

In a brand new Nuxt project, after installed the module, here is the error I've got

```bash
Uncaught SyntaxError: The requested module '/_nuxt/node_modules/my-module/node_modules/unctx/dist/index.mjs?v=171c68dd' does not provide an export named 'executeAsync' (at locale.mjs?v=171c68dd:2:1)
```

**Comment by calebeaires** [comment]
unctx version: 2.1.1

It is there, but not installed by me! My guess is that it is a nuxt kit dependence

**Comment by calebeaires** [comment]
I found out that in the module project, when importing "computed", onMounted and others Vue function, we cant do it with "#import", after changed that the error gone and the module has been fixed.

```js

import {computed} from "#imports" // wrong
import {computed} from "vue" // made it work


```

**Comment by danielroe** [comment]
The dependency is fine, and the right version. Would you provide a minimal reproduction please?
