### ISSUE TITLE
Module parse failed: Unexpected character '#' (69:2) You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. 

### ISSUE THREAD

**Issue by jbmarflo** [nuxt/nuxt#18928]
### Environment

NUXT 

`"dependencies": {
    "@nuxtjs/auth": "^4.9.1",
    "@nuxtjs/axios": "^5.5.4",
    "@nuxtjs/gtm": "^2.3.0",
    "axios": "^0.19.2",
    "cookie-parser": "^1.4.6",
    "core-js": "^2.6.5",
    "lodash": "^4.17.15",
    "nuxt": "^2.13.3",
    "nuxt-jsonld": "^1.4.5",
    "nuxt-property-decorator": "2.3.0",
    "postcss-import": "^15.1.0",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.2",
    "v-autocomplete": "^1.8.2",
    "vue-affix": "^0.5.2",
    "vue-count-to": "^1.0.13",
    "vue-multiselect": "^2.1.6",
    "vue-observe-visibility": "^0.4.6",
    "vue-scrollto": "^2.15.0",
    "vue-style-loader": "^4.1.2",
    "vuex": "^3.5.1",
    "vuex-class-modules": "^1.1.2"
  },
  "devDependencies": {
    "@expo/webpack-config": "^18.0.1",
    "@nuxt/types": "^2.15.8",
    "@nuxt/typescript": "^2.8.1",
    "@nuxt/typescript-build": "^2.1.0",
    "@nuxt/typescript-runtime": "^0.3.8",
    "@nuxtjs/imagemin": "^0.1.0",
    "@types/node": "10.14.8",
    "@types/webpack-env": "1.13.9",
    "bootstrap": "^4.4.1",
    "bootstrap-vue": "^2.2.2",
    "nuxt-purgecss": "^0.2.1",
    "sass-loader": "^7.1.0",
    "webpack": "^4.39.0",
    "webpack-cli": "^3.3.6",
    "webpackbar": "^3.2.0"
  },
  "engines": {
    "npm": "8.5.1",
    "node": "12.13.1"
  }`

### Reproduction

I have differents proyects with     "nuxt": "^2.13.3", but now all my projects not work. 

### Describe the bug

Before today All was working good, but when a installed all the dependencies again today I  had this kind of error. 

### Logs

```shell-script
Module parse failed: Unexpected character '#' (69:2) You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders | */ | class BlobDataItem { > #path | #start |
server.js
Missing stack frames 
Js
./node_modules/node-fetch-native/dist/index.cjs@39118:7
server.js:39118:7
./node_modules/node-fetch-native/dist/index.cjs
webpack/bootstrap:25:
__webpack_require__
webpack/bootstrap:25:
__webpack_require__
.nuxt/server.js:1:
./.nuxt/server.js
webpack/bootstrap:25:
__webpack_require__
server.js:60516:18
0
webpack/bootstrap:25:
__webpack_require__
server.js:118:18
server.js:121:10
```

**Comment by danielroe** [comment]
We can track in https://github.com/nuxt/nuxt/issues/10751.
