### ISSUE TITLE
useRuntimeConfig can not be used in the defineNuxtPlugin,

### ISSUE THREAD

**Issue by mao-shonen** [nuxt/nuxt#18939]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.19.0`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.1.1`
- Package Manager:  `pnpm@7.22.0`
- Builder:          `vite`
- User Config:      `runtimeConfig`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-vykbia

`nuxt.config.ts`
```js
export default defineNuxtConfig({
  runtimeConfig: {
    customId: 123,
  },
});
```

`./plugins/custom.ts`
```js
export default defineNuxtPlugin((nuxtApp) => {
  const config = useRuntimeConfig();

  return {
    provide: {
      getRuntimeConfigCustomId: () => {
        return config.customId;
      },
    },
  };
});
```

`app.vue`
```js
<template>
  <div>customId: {{ $getRuntimeConfigCustomId() }}</div>
  <div>
    customId is undefined: {{ $getRuntimeConfigCustomId() === undefined }}
  </div>
  <div>cdnURL is undefined: {{ $getRuntimeConfigCdnURL() }}</div>
</template>
```

result
```html
customId:
customId is undefined: true
```

### Describe the bug

[Based on the documentation](https://nuxt.com/docs/api/composables/use-runtime-config#appbaseurl), useRuntimeConfig can be used in the defineNuxtPlugin,
however, in practice its value is undefined (IDE type hinting is normal).

**Comment by danielroe** [comment]
In your case `customId` will be defined on the server but not the client. You need to add it via `runtimeConfig.public.customId` to declare it as public, which will mean nuxt will pass it from server to client.
