### ISSUE TITLE
Global Javascript transition

### ISSUE THREAD

**Issue by BenjaminOddou** [nuxt/nuxt#18941]
### Discussed in https://github.com/nuxt/nuxt/discussions/18834

<div type='discussions-op-text'>

<sup>Originally posted by **BenjaminOddou** February  6, 2023</sup>
As for now I didn't succeed to implement correctly nuxt transition with JS hooks in a "nuxt" way inside the `app.vue` component.

For now I have in my `app.vue` :

```vue
<script setup lang="ts">
const onBeforeLeave = (el) => {}
const onLeave = (el, done) => {}
const onEnter = (el, done) => {}
const onAfterEnter = (el) => {}
</script>

<template>
        <router-view v-slot="{ Component }">
          <Transition
            mode="out-in"
            :css="false"
            @before-leave="onBeforeLeave"
            @leave="onLeave"
            @enter="onEnter"
            @after-enter="onAfterEnter"
          >
            <component :is="Component" />
          </Transition>
        </router-view>
</template>
```

After testing a bit, I think the correct syntax should be this as explained in the [docs](https://nuxt.com/docs/getting-started/transitions#transition-with-nuxtpage) for global transition but its not working. Is my syntax incorrect ?

`app.vue` :

```vue
<script setup lang="ts">
const onBeforeLeave = (el) => {}
const onLeave = (el, done) => {}
const onEnter = (el, done) => {}
const onAfterEnter = (el) => {}
</script>

<template>
  <div>
        <NuxtPage
          :transition="{
            mode: 'out-in',
            css: false,
            onBeforeLeave,
            onLeave,
            onEnter,
            onAfterEnter,
          }"
        />
  </div>
</template>
```

`errors` :
![errors](https://user-images.githubusercontent.com/85166574/217097621-debd0f14-c391-46a8-8849-426854b84253.png)

**Comment by madebyfabian** [comment]
Hi! I think this is not an issue per-se but more a question on how to implement something. Therefore it would may be a better fit for the Community Discord at https://discord.com/invite/ps2h6QT :)

**Comment by BenjaminOddou** [comment]
Hello @madebyfabian and thanks for the discord link. I think this might be an issue or a limitation of Nuxt as I used the syntax described in the docs. I'll will also ask some help in the discord server 😄

**Comment by madebyfabian** [comment]
@BenjaminOddou yeah since you also created a discussion, maybe lets validate if this is a nuxt problem and then come back to this issue.

**Comment by danielroe** [comment]
Yes, let's track this in the discussion for now ❤️

**Comment by BenjaminOddou** [comment]
Hey @madebyfabian, @danielroe, did you see this ? [#18834](https://github.com/nuxt/nuxt/discussions/18834)

**Comment by BenjaminOddou** [comment]
Hey @madebyfabian, @danielroe, did you see this ? [#18834](https://github.com/nuxt/nuxt/discussions/18834)
