### ISSUE TITLE
ClientOnly treeshake error with async components

### ISSUE THREAD

**Issue by oleghalin** [nuxt/nuxt#18949]
### Environment
------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-732ozv?file=app.vue

### Describe the bug

When you wrap async component in client-only nuxt throws error

**Comment by danielroe** [comment]
Thank you. You can disable `experimental.treeshakeClientOnly` for now to avoid this issue.
