### ISSUE TITLE
TypeScript kinda broken in 3.2.0 with Volar

### ISSUE THREAD

**Issue by michaelpumo** [nuxt/nuxt#18946]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.14.0`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `npm@9.3.1`
- Builder:          `vite`
- User Config:      `app`, `modules`, `runtimeConfig`, `ssr`, `tailwindcss`, `typescript`, `vite`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.3.1`, `@pinia/nuxt@0.4.6`, `@pinia-plugin-persistedstate/nuxt@1.0.0`, `@storyblok/nuxt@5.1.0`
- Build Modules:    `-`

### Reproduction

Reproduction not applicable.

### Describe the bug

When upgrading from v3.1.2 to v3.2.0, TypeScript seems to be broken when used in VS Code + Volar v1.0.24.

v3.1.2 (correct)

<img width="705" alt="Screenshot 2023-02-10 at 13 23 01" src="https://user-images.githubusercontent.com/4269460/218107333-0309d066-d99a-4bd9-b093-f22d1ac5e326.png">
<img width="491" alt="Screenshot 2023-02-10 at 13 22 48" src="https://user-images.githubusercontent.com/4269460/218107336-08ee1372-9640-433c-aaca-9de50dd46401.png">

v3.2.0 (broken)

<img width="393" alt="Screenshot 2023-02-10 at 13 40 39" src="https://user-images.githubusercontent.com/4269460/218107480-c674de96-004b-4e01-8a68-ec48f9ed895d.png">
<img width="687" alt="Screenshot 2023-02-10 at 13 40 51" src="https://user-images.githubusercontent.com/4269460/218107483-0cdbb03a-6c1d-4278-a0eb-2f5023bef071.png">
<img width="472" alt="Screenshot 2023-02-10 at 13 41 02" src="https://user-images.githubusercontent.com/4269460/218107486-b7b802e1-86d5-4955-802c-5e71d0305d98.png">

### Additional context

I have downgraded and upgraded several times to check this problem and it only happens with latest v3.2.0.

On Twitter it was discussed that this may be due to the upgrade of @types/node but I'm unsure. I found the diff here though:
https://github.com/nuxt/nuxt/compare/v3.1.2...v3.2.0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R51

**Comment by awdr74100** [comment]
Agreed that the upgrade of @types/node caused problems.

**Comment by manniL** [comment]
Does adding an override / a resolution to downgrade `@types/node` work?

**Comment by awdr74100** [comment]
Adding @types/node (v18.13.0) manually does solve the problem!

```ts
import { createSigner } from 'fast-jwt';

export const createAccessToken = (payload: object) => {
  const config = useRuntimeConfig();

  const signWithPromise = createSigner({ key: async () => config.accessTokenSecret });

  return signWithPromise(payload);
};

console.log(createAccessToken({})) // return a "Promise<string>" recognized as correct instead of a "string"
```

**Comment by michaelpumo** [comment]
> Adding @types/node (v18.13.0) manually does solve the problem!
> 
> ```ts
> import { createSigner } from 'fast-jwt';
> 
> export const createAccessToken = (payload: object) => {
>   const config = useRuntimeConfig();
> 
>   const signWithPromise = createSigner({ key: async () => config.accessTokenSecret });
> 
>   return signWithPromise(payload);
> };
> 
> console.log(createAccessToken({})) // return a "Promise<string>" recognized as correct instead of a "string"
> ```

Manually installing `@types/node` to my project's dependencies does not appear to make a difference and doesn't fix the issue (for me at least).

`"@types/node": "^18.13.0"`

I have restarted TS, VC Code and re-installed but nothing has made it work again.

**Comment by danielroe** [comment]
Would you try fixing your `vue` version to `3.2.45`? I've noticed a regression here with Vue 3.2.47, which the latest Nuxt will pull in.

**Comment by michaelpumo** [comment]
> Would you try fixing your `vue` version to `3.2.45`? I've noticed a regression here with Vue 3.2.47, which the latest Nuxt will pull in.

Unfortunately, this does not work either. Here's my entire `package.json` file for clarity (in case I've done something wrong?).

```
{
  "name": "parallel",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "dev:ssl": "local-ssl-proxy --source 3010 --target 3000 --cert localhost.pem --key localhost-key.pem",
    "generate": "nuxt generate",
    "preview": "nuxt preview"
  },
  "overrides": {
    "vue": "3.2.45"
  },
  "dependencies": {
    "@heroicons/vue": "^2.0.15",
    "@nuxtjs/tailwindcss": "^6.4.0",
    "@pinia-plugin-persistedstate/nuxt": "^1.0.0",
    "@pinia/nuxt": "^0.4.6",
    "@storyblok/nuxt": "^5.1.0",
    "@vueuse/core": "^9.12.0",
    "nuxt": "^3.2.0",
    "pinia": "^2.0.30"
  },
  "devDependencies": {
    "@nuxtjs/eslint-config-typescript": "^12.0.0",
    "@tailwindcss/forms": "^0.5.3",
    "@tailwindcss/typography": "^0.5.9",
    "del-cli": "^5.0.0",
    "eslint": "^8.34.0",
    "eslint-plugin-tailwindcss": "^3.8.3",
    "prettier": "^2.8.4",
    "vite-svg-loader": "^4.0.0"
  }
}
```

**Comment by danielroe** [comment]
I believe this is resolved upstream in volar. I don't get any issues with a new Nuxt project.
