### ISSUE TITLE
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by zouhangwithsweet** [nuxt/nuxt#18956]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `pnpm@7.13.2`
- Builder:          `vite`
- User Config:      `modules`, `unocss`
- Runtime Modules:  `@unocss/nuxt@0.49.4`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-vgyh5u-anvs91?file=server%2Fapi%2Findex.ts

### Describe the bug

I want to use SSE in nuxt server.But there is an error
```bash
 [nitro] [dev] [unhandledRejection] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
```
 And when broswer page closed, the `req` cannot emit close event.

**Comment by Baroshem** [comment]
Hey,

Could you provide some reproduction details? 
I cannot reproduce the error you linked in the issue :(

**Comment by zouhangwithsweet** [comment]
I just run it in local. It will log that message

**Comment by Baroshem** [comment]
Not sure if I can reproduce the issue still.

I tried reloading the page and closing the app and I am getting these results: 
![image](https://user-images.githubusercontent.com/37120330/218988549-b6fdc985-a881-49f2-ab0d-814259cddf41.png)

Could you add more details to the issue like the steps that you do to make the issue appear?

**Comment by zouhangwithsweet** [comment]
Sorry for that, I will test it at local again.
