### ISSUE TITLE
`<NuxtLoadingIndicator>` not working on `3.2.0`

### ISSUE THREAD

**Issue by ojvribeiro** [nuxt/nuxt#18969]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.4.0`, `@nuxtjs/fontaine@0.2.4`, `nuxt-icon@0.2.11`, `@nuxt/devtools@0.1.2`, `@nuxt/image-edge@1.0.0-27919678.2f5b64b`, `@nuxtjs/google-fonts@3.0.0-1`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-tvjuvn?file=app.vue

### Describe the bug

It seems that `NuxtLoadingIndicator` is not setting its opacity to `1` when it needs to be shown. This is a screenshot of the moment the loading indicator should appear:

![image](https://user-images.githubusercontent.com/8026741/218292296-275db089-832e-4cfe-a2b5-777e59100187.png)

![dwadfwa](https://user-images.githubusercontent.com/8026741/218292277-b243939a-d38e-4f77-89aa-31f80b75f2db.gif)

### Additional context

Not working on v3.1.2 and edge either.

**Comment by danielroe** [comment]
You can set `throttle` to 0. By default we only show it for transitions longer than 200ms.

**Comment by ojvribeiro** [comment]
> You can set `throttle` to 0. By default we only show it for transitions longer than 200ms.

Oh I see. Thanks a lot!
