### ISSUE TITLE
Nuxt Layers doubles the CSS in dev and prod builds

### ISSUE THREAD

**Issue by timothymarois** [nuxt/nuxt#18963]
### Environment

- Operating System: MacOS
- Node Version: v16.15.1
- Nuxt Version: >3.2.0

Install Nuxt3 on two projects (parent and child)

This example, utilizes the Nuxt Layers [found in this documentation](https://nuxt.com/docs/getting-started/layers) 

### Reproduction

- Install Nuxt3 on 2 projects, a parent and child 
- Add `assets/css/main.css` to parent  and use a CSS class 
- Add this class to a div on the main app.vue file on parent 
- Install `@nuxt/kit` and in your config with parent, use this setup:

_Note: Nuxt Kit here is required as per Nuxt Layers documentation_ 

```
import { createResolver } from '@nuxt/kit'
const { resolve } = createResolver(import.meta.url)

export default defineNuxtConfig({
    css: [
        resolve('./assets/css/main.css')
    ]
})
```

- Inside Nuxt Config of your child project, add the following 

```
export default defineNuxtConfig({
    extends: [
        '../path-to-parent-project'
      ]
})
```

- Run `npm run dev` on child, and load up in the browser

### Describe the bug

Once in browser, open view source, notice you will see double prefetching of the exact same CSS files, if you inspect, you will see double CSS files

_Example:_ 
![Screen Shot 2023-02-11 at 2 08 36 PM](https://user-images.githubusercontent.com/2489333/218276874-c7d61423-f35e-44fb-ae97-93ffaa6f98e1.png)

Now, run `npm run build` 

You will notice there is double CSS being created in your build. 

### Additional context

To me, it looks like Nuxt is loading twice because its a double project, but its expected only to load once as the parent project is acting as source and the child should act as its own with the ability to override whatever the parent has. 

This increases the build significantly.

**Comment by timothymarois** [comment]
The current state of **Nuxt Layers can not be used for production** due to these underlying issues. This feature is so powerful, but you can not use this for production.

**Comment by manniL** [comment]
Can't reproduce in https://stackblitz.com/edit/github-gcwlmm
`cd base && npm i && cd ../main && npm i && npm run build && node .output/server/index.mjs`

**Comment by timothymarois** [comment]
@manniL My reproduction setups were missing adding tailwindcss (or any other design framework) which the module on nuxt with layers requires it to be installed on both packages. Unless I'm doing it wrong, but I was able to reproduce, here is the fork version:

https://stackblitz.com/edit/nuxtissues18963-atzuk5?file=base/nuxt.config.ts

![Screen Shot 2023-02-17 at 3 41 27 PM](https://user-images.githubusercontent.com/2489333/219788935-a1a1c6e9-2ab3-471a-a714-aa64d0a1df42.png)

**Comment by manniL** [comment]
@timothymarois In dev mode yes (as before) but not in production mode.

<img width="1715" alt="image" src="https://user-images.githubusercontent.com/640208/219809373-9e61b539-75bc-427b-a455-74c4416b5990.png">
