### ISSUE TITLE
Issue with useCookie in production

### ISSUE THREAD

**Issue by toniengelhardt** [nuxt/nuxt#18977]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.11.0`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `pnpm@7.27.0`
- Builder:          `vite`
- User Config:      `extends`, `runtimeConfig`, `experimental`, `modules`, `typescript`, `css`, `postcss`, `app`, `pwa`, `colorMode`, `plausible`, `linkChecker`
- Runtime Modules:  `@kevinmarrec/nuxt-pwa@0.16.2`, `@nuxtjs/color-mode@3.2.0`, `@nuxtjs/plausible@0.2.0`, `@unocss/nuxt@0.49.4`, `@vueuse/nuxt@9.12.0`, `nuxt-icon@0.2.11`
- Build Modules:    `-`

### Reproduction

You can see the issue at https://webapicheck.com when you toggle the mode from grid to rows on the top right (see gif) and reload the page.

![useCookie bug](https://user-images.githubusercontent.com/2703233/218336573-2804f581-341f-4411-b29b-0f30bd3c91ae.gif)

### Describe the bug

It seems like there is an issue with retrieving and setting cookies via `useCookie()`. It only appears in production, dev server works fine. You can see the source code here: https://github.com/toniengelhardt/webapicheck.

Console errors:

<img width="722" alt="Screenshot 2023-02-14 at 18 07 25" src="https://user-images.githubusercontent.com/2703233/218821284-75666874-3294-4cf4-8575-a9a65ca9a79c.png">

Relevant code is in `pages/index.vue`

```ts
const mode = useCookie('mode', { default: () => 'grid' })
```

and in `components/api/ModeSelector.vue`.

**Comment by toniengelhardt** [comment]
The issue was that the page got pre-rendered, which resulted in the bug, closing...
@danielroe fixed it live in 2mins in a Twitch stream, absolute legend!

**Comment by LeonBuchner** [comment]
How did  you fix it? Have the same problem...
