### ISSUE TITLE
Vite meta environment variables are NOT accessible in Nuxt 3

### ISSUE THREAD

**Issue by lautiamkok** [nuxt/nuxt#18973]
### Environment

I am using Nuxt 3.2

### Reproduction

```
// .env
APP_BASE_URL=http://localhost:3000
API_BASE_URL=http://localhost:5000
```

```
// ./utils/utils.js
const apiBaseUrl = import.meta.env.API_BASE_URL
console.log('apiBaseUrl =', apiBaseUrl)

```

```
// ./pages/index.vue
<script setup>
import { ... } from '@/utils/utils'
</script>
```

### Describe the bug

You will get `undefined`:

`apiBaseUrl = undefined`

### Additional context

We should get `http://localhost:5000`, not `undefined`. 

If it is how it works in Nuxt 3, how do we access Vite meta environment variables without relying on the `nuxt.config.ts` file?

**Comment by danielroe** [comment]
This is how to do this in Nuxt 3: https://nuxt.com/docs/guide/going-further/runtime-config

**Comment by TLovers** [comment]
> This is how to do this in Nuxt 3: https://nuxt.com/docs/guide/going-further/runtime-config

Is this usage above deprecated? What should I do if I do want to use an env file?

**Comment by Tofandel** [comment]
The problem with `useRuntimeConfig()` is that it is only usable in a vue component for some reason, why is that?

Why can't we use the runtime config outside of vue components?
