### ISSUE TITLE
Nuxt3 not honoring Components pathPrefix setting

### ISSUE THREAD

**Issue by lynxionxs** [nuxt/nuxt#18986]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `npm@8.5.0`
- Builder:          `vite`
- User Config:      `target`, `typescript`, `modules`, `piniaPersistedstate`, `components`, `css`, `devServer`, `experimental`, `app`
- Runtime Modules:  `@pinia/nuxt@0.4.6`, `@pinia-plugin-persistedstate/nuxt@1.0.0`, `@vueuse/nuxt@9.10.0`, `nuxt-icon@0.1.8`, `@nuxtjs/color-mode@3.2.0`, `@nuxtjs/google-fonts@3.0.0-1`
- Build Modules:    `-`
------------------------------

### Reproduction

None

### Describe the bug

When setting **pathPrefix: true/false** for multiple component folders, it does not create the path based component when pathPrefix is set to true. 
Like here: The Header in portfolio components folder should be **PortfolioHeader**, but Nuxt sees it as **Header**, with **pathPrefix: true**
_nuxt.config.js_
![Screenshot_2023-02-13_09-28-42](https://user-images.githubusercontent.com/7606938/218432373-7706b1ae-2d96-475a-9ed3-5bc985d48422.png)
_.nuxt/components.d.ts_
![Screenshot_2023-02-13_09-26-15](https://user-images.githubusercontent.com/7606938/218434069-a6ef4242-a8e6-4388-9f6e-99242bb7c409.png)

`[Vue warn]: Failed to resolve component: PortfolioHeader`

Deleting **.nuxt/** folder doesn't help. **V3.0.0** has the same problem as **V3.2.0**

**Comment by danielroe** [comment]
The path is calculated relative to the `path` you set - so there is no path to speak of in your case. But you can set the `prefix` to add the 'starting' prefix for the directory, e.g.:

```js
export default defineNuxtConfig({
  components: {
    dirs: [
      { path: '~/components/portfolio', prefix: 'Portfolio' }
    ]
  }
})
```
