### ISSUE TITLE
NuxtWelcome is present in build

### ISSUE THREAD

**Issue by avinean** [nuxt/nuxt#18997]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.6.0`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.1`
- Package Manager:  `pnpm@7.11.0`
- Builder:          `vite`
- User Config:      `alias`, `extends`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Didn't manage to reproduce on https://stackblitz.com/

### Describe the bug

Component [NuxtWelcome](https://github.com/nuxt/ui/blob/main/packages/templates/templates/welcome/index.html) uses nowhere. But it is present in build. 
<img width="1785" alt="image" src="https://user-images.githubusercontent.com/22274408/218479536-aac44c84-7417-4a7c-b394-5e8233197054.png">
<img width="1790" alt="image" src="https://user-images.githubusercontent.com/22274408/218479665-d8995821-ed5c-422a-87de-a250b5ebdb14.png">

**Comment by danielroe** [comment]
This shouldn't be the case unless you actually use it in your app. I'll very happily reopen and have a look if you can provide a reproduction 🙏

**Comment by avinean** [comment]
@danielroe Thanks! You helped me a lot.

**Comment by danielroe** [comment]
I can't do much with a screenshot.

In this case opening a discussion or trying on discord might be better, but even there you'll need to provide more info...

**Comment by madebyfabian** [comment]
Can confirm this happened in my app too when doing a `nuxt analzye`. I've spent like 2 hrs trying to create a reproduction, but it was impossible. Seems like it maybe get's included by some side effect and or package. Does that PR #19008 fixes this issue? Or should I try to provide more info.

**Comment by danielroe** [comment]
Were you importing from `#components`?

**Comment by madebyfabian** [comment]
@danielroe after checking again, also cannot reproduce it locally. Upgraded to 3.2.0 and all packages used to their latest version a few days ago. So seems fine. But I am/was not using the `#components` import FYI.

**Comment by harlan-zw** [comment]
@danielroe 

I believe this is from modules, I could reproduce it and pinned it down to @nuxt/ui, see https://github.com/nuxt/ui/blob/main/packages/ui/src/components/NButton.vue. Have sent a PR https://github.com/nuxt/ui/pull/199

If the issue is caused by importing `#components`, should we be recommending it in the [docs](https://nuxt.com/docs/guide/directory-structure/components#direct-imports)? We should at least add a warning

Seems like `resolveComponent` should be the recommendation, although not sure how that goes with types?

**Comment by danielroe** [comment]
Fix is almost complete: https://github.com/nuxt/nuxt/pull/19008

**Comment by harlan-zw** [comment]
Oh nice, missed that PR! Will close off my @nuxt/ui PR

**Comment by avinean** [comment]
Just for history.
I really have one direct import from #components.
After removing it welcome.js/css disappears

**Comment by Envoy49** [comment]
I wish Nuxt.js to be forgotten, deprecated, deleted like Backbone.js and Angular.js
Too many bugs, so sick of working with it on daily basis.

**Comment by grandgeorg** [comment]
Sorry, but the problem still persists within `nuxt: ^3.4.2`, (installed today with `npx nuxi init ...`). Scoped styles from `node_modules/@nuxt/ui-templates/dist/templates/welcome.vue` will be loaded no matter what. (Of course I removed `<NuxtWelcome>` but that has no effect on the styles ...)

**Comment by danielroe** [comment]
@grandgeorg It's a different issue, and there is an open PR to resolve it.
