### ISSUE TITLE
NuxtLoadingIndicator doesn't work in Nuxt 3.2.0

### ISSUE THREAD

**Issue by elpeyotl** [nuxt/nuxt#18996]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `yarn@1.22.4`
- Builder:          `vite`
- User Config:      `modules`, `app`, `vite`, `i18n`, `build`, `runtimeConfig`, `telemetry`
- Runtime Modules:  `@pinia/nuxt@0.4.6`, `@nuxtjs/tailwindcss@6.2.0`, `@nuxtjs/i18n@8.0.0-beta.7`
- Build Modules:    `-`

### Reproduction

- Install the latest nuxt version (3.2.0)
- create at least 2 pages for navigating
- Add **NuxtLoadingIndicator** to your app.vue file like state [here](https://nuxt.com/docs/api/components/nuxt-loading-indicator#nuxtloadingindicator)

### Describe the bug

When adding **nuxtLoadingIndicator** to app.vue it will not show up. This only happens in Nuxt version 3.2.0. In Nuxt version 3.0.0 it works fine.

**Comment by danielroe** [comment]
You can set `throttle` to 0. By default we only show it for transitions longer than 200ms.

**Comment by dadaguai-git** [comment]
I'm also experiencing this problem，but I don't understand what **throttle** does 。 Must be 0 or it will not take effect

**Comment by AloisSeckar** [comment]
> I'm also experiencing this problem，but I don't understand what **throttle** does 。 Must be 0 or it will not take effect

**throttle** will surpress the indicator for given amount of millis. So according to my understanding - if the navigation ends before it (default is 200), you won't see an indicator at all

**Comment by elpeyotl** [comment]
As described above. 
It will always show up if you set trottle to 0. 

`      <NuxtLoadingIndicator :throttle="0" />
`
