### ISSUE TITLE
Nitro preset for Netlify generates errors when using auth module

### ISSUE THREAD

**Issue by raducretu** [nuxt/nuxt#18999]
<img width="1243" alt="Screenshot 2023-02-13 at 17 11 12" src="https://user-images.githubusercontent.com/85927/218502269-9dc14b87-ee84-4ca3-9f6d-154d7e963cea.png">
### Environment

Cannot generate info as it is live on the Netlify server but for local machine where everything works as expected:

- Operating System: `Darwin`
- Node Version:     `v16.11.0`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.1`
- Package Manager:  `npm@8.0.0`
- Builder:          `vite`
- User Config:      `css`, `app`, `runtimeConfig`, `modules`, `i18n`, `algolia`, `image`, `auth`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.2.0`, `@nuxtjs/i18n@8.0.0-beta.4-27816734.493bb8f`, `@nuxtjs/algolia@1.2.0`, `nuxt-lodash@2.4.1`, `@sidebase/nuxt-auth@0.4.0-alpha.5`
- Build Modules:    `-`

### Reproduction

Build a website on netlify with https://nuxt.com/modules/nuxt-auth
Set the provider to Auth0 and try to sign-in.

### Describe the bug

This bug appears when trying to sign in with Auth0

### Additional context

ssr: true

### Logs

```shell-script
Feb 13, 03:48:41 PM: ed16c2a5 ERROR  [next-auth][error][OAUTH_CALLBACK_ERROR]Feb 13, 03:48:41 PM: ed16c2a5 ERROR  https://next-auth.js.org/errors#oauth_callback_error invalid_request (Parameter 'code_verifier' is required) {Feb 13, 03:48:41 PM: ed16c2a5 ERROR    error: OPError: invalid_request (Parameter 'code_verifier' is required)Feb 13, 03:48:41 PM: ed16c2a5 ERROR        at processResponse (/var/task/node_modules/openid-client/lib/helpers/process_response.js:38:13)Feb 13, 03:48:41 PM: ed16c2a5 ERROR        at Client.grant (/var/task/node_modules/openid-client/lib/client.js:1327:22)Feb 13, 03:48:41 PM: ed16c2a5 ERROR        at processTicksAndRejections (node:internal/process/task_queues:96:5)Feb 13, 03:48:41 PM: ed16c2a5 ERROR        at async Client.callback (/var/task/node_modules/openid-client/lib/client.js:476:24)Feb 13, 03:48:41 PM: ed16c2a5 ERROR        at async oAuthCallback (/var/task/node_modules/next-auth/core/lib/oauth/callback.js:129:16)Feb 13, 03:48:41 PM: ed16c2a5 ERROR        at async Object.callback (/var/task/node_modules/next-auth/core/routes/callback.js:52:11)Feb 13, 03:48:41 PM: ed16c2a5 ERROR        at async AuthHandler (/var/task/node_modules/next-auth/core/index.js:201:28)Feb 13, 03:48:41 PM: ed16c2a5 ERROR        at async file:///var/task/chunks/nitro/netlify.mjs:425:24Feb 13, 03:48:41 PM: ed16c2a5 ERROR        at async Object.handler (file:///var/task/node_modules/h3/dist/index.mjs:840:19)Feb 13, 03:48:41 PM: ed16c2a5 ERROR        at async toNodeHandle (file:///var/task/node_modules/h3/dist/index.mjs:915:7) {Feb 13, 03:48:41 PM: ed16c2a5 ERROR      name: 'OAuthCallbackError',Feb 13, 03:48:41 PM: ed16c2a5 ERROR      code: undefinedFeb 13, 03:48:41 PM: ed16c2a5 ERROR    },Feb 13, 03:48:41 PM: ed16c2a5 ERROR    providerId: 'auth0',Feb 13, 03:48:41 PM: ed16c2a5 ERROR    message: "invalid_request (Parameter 'code_verifier' is required)"Feb 13, 03:48:41 PM: ed16c2a5 ERROR  }
```

**Comment by harlan-zw** [comment]
Seems like an issue with the @sidebase/nuxt-auth module? 

If so, please move the issue there. If you're sure it's a Nuxt / Nitro issue feel free to comment and I'll re-open it.
