### ISSUE TITLE
Calling $fetch with .native modifier always throws error (Illegal invocation)

### ISSUE THREAD

**Issue by viniciuspinatti** [nuxt/nuxt#19004]
### Environment

nuxt version -> 3.2.0
node version -> 18.13.0

### Reproduction

A simple example showing the error:
https://stackblitz.com/edit/nuxt-starter-ofetch-native-error?file=app.vue

### Describe the bug

I was trying to get a native response payload from fetch using `$fetch.native()` but always get an error: TypeError: Failed to execute 'fetch' on 'Window': Illegal invocation
With other modifier like `.raw()` works normally.
There are some situations where we want to get the native response object from fetch instead of the wrapped created by ofetch. So for now it's not possible with the modifier that is offered.

### Logs

```shell-script
app.vue:10 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'Window': Illegal invocation
    at doFetch (app.vue:10:1)
    at callWithErrorHandling (vue.js?v=2ccf23c0:1580:18)
    at callWithAsyncErrorHandling (vue.js?v=2ccf23c0:1588:17)
    at HTMLParagraphElement.invoker (vue.js?v=2ccf23c0:8198:5)
doFetch @ app.vue:10
callWithErrorHandling @ vue.js?v=2ccf23c0:1580
callWithAsyncErrorHandling @ vue.js?v=2ccf23c0:1588
invoker @ vue.js?v=2ccf23c0:8198
Promise.catch (async)
callWithAsyncErrorHandling @ vue.js?v=2ccf23c0:1590
invoker @ vue.js?v=2ccf23c0:8198
```

**Comment by pi0** [comment]
Normally you can use `fetch` (without `$fetch.`) prefix to use native fetch universally

this seems an upstream issue with ofetch.

**Comment by viniciuspinatti** [comment]
@pi0 One question: in this cases, is it better to create an issue also in the ofetch repository or do you from the Nuxt team have some kind of near contact with someone there?

**Comment by danielroe** [comment]
In general it's always good to create upstream issues as long as you can minimally reproduce them without Nuxt. In this case @pi0 has very good contact with the upstream maintainer.

**Comment by danielroe** [comment]
This seems to be resolved for me. If you're still encountering it, please do raise an issue upstream in https://github.com/unjs/ofetch.
