### ISSUE TITLE
Upgrade to 3.2.0 from 3.1.1 causes error: `ERROR: Could not resolve "#app/nuxt"`

### ISSUE THREAD

**Issue by vedmant** [nuxt/nuxt#19005]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.19.0`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `imports`, `modules`, `sourcemap`, `runtimeConfig`
- Runtime Modules:  `@pinia/nuxt@0.4.6`, `@nuxtjs/tailwindcss@6.4.0`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-yabkao?file=composables%2FuseToast.js,app.vue

### Describe the bug

Upgrade to 3.2.0 from 3.1.1 causes error: `ERROR: Could not resolve "#app/nuxt"`

```
 ERROR  12:38:42 PM [vite] error while updating dependencies:
 Error: Build failed with 1 error:
 node_modules/nuxt/dist/head/runtime/composables.mjs:2:27: ERROR: Could not resolve "#app/nuxt"
     at failureErrorWithLog (/Users/me/project/node_modules/vite/node_modules/esbuild/lib/main.js:1604:15)
     at /Users/me/project/node_modules/vite/node_modules/esbuild/lib/main.js:1056:28
     at runOnEndCallbacks (/Users/me/project/node_modules/vite/node_modules/esbuild/lib/main.js:1476:61)
     at buildResponseToResult (/Users/me/project/node_modules/vite/node_modules/esbuild/lib/main.js:1054:7)
     at /Users/me/project/node_modules/vite/node_modules/esbuild/lib/main.js:1166:14
     at responseCallbacks.<computed> (/Users/me/project/node_modules/vite/node_modules/esbuild/lib/main.js:701:9)
     at handleIncomingPacket (/Users/me/project/node_modules/vite/node_modules/esbuild/lib/main.js:756:9)
     at Socket.readFromStdout (/Users/me/project/node_modules/vite/node_modules/esbuild/lib/main.js:677:7)
     at Socket.emit (node:events:513:28)
     at Socket.emit (node:domain:489:12)
```

**Comment by Smef** [comment]
I've experience the same thing and was about to post this. Thanks!

**Comment by danielroe** [comment]
For now, you can either import directly from '#app' or add 'nuxt/app' to your `build.transpile`:

```diff
- import { callWithNuxt } from 'nuxt/app'
+ import { callWithNuxt } from '#app'
```

**Comment by Smef** [comment]
The import is in a Nuxt package directly, so we can't (should't) modify it ourselves.

Adding a `build.transpile` property to `nuxtconfig.ts` as directed resolved this error as a workaround. Thanks!

```
    build: {
        transpile: [
            'nuxt/app'
        ]
    },
```

**Comment by danielroe** [comment]
You have an import from `nuxt/app` in your app. Updating that is what I'm referring to.

**Comment by vedmant** [comment]
I think this all auto-imports and import aliases makes more problems. Why not to give people option to explicitly import everything from packages directly? I would prefer this option instead of aliases magic.

**Comment by Smef** [comment]
Yup. That was definitely the better fix. I didn't realize that was in use in our code. Fixing it in our code was definitely the better solution.
