### ISSUE TITLE
Getting a lot of 404s and other errors whenever I deploy a new version of website

### ISSUE THREAD

**Issue by jastaffen** [nuxt/nuxt#19003]
### Environment

Running "npm run build"
--
04:32:24.196 |  
04:32:24.197 | > build
04:32:24.197 | > nuxt build
04:32:24.197 |  
04:32:24.298 | [log] Nuxi 3.1.1
04:32:24.317 | [log] Nuxt 3.1.1 with Nitro 2.1.1

### Reproduction

I am not doing any sort of special async component logic or anything of that sort.

### Describe the bug

Hi all, while I myself haven't been able to reproduce the issue, I have noticed a pattern where whenever I deploy updates to a nuxt3 site hosted on Vercel, I'm seeing a spike in 404s on the website to what I'm assuming are preloaded files such as (/_nuxt/NavLink.fcf30ecc.js or  /_nuxt/GalleryImage.ce51e2e2.css). Not sure if related but I've also seen this error message in Sentry at times—Failed to fetch dynamically imported module. Please help!

### Logs

```shell-script
via Sentry—

TypeError TypeError: Failed to fetch dynamically imported module: (error-component)
Failed to fetch dynamically imported module: https://​pinklily.​com/​_nuxt/​error-comp­onent.​c0fcbfdc.​js
Feb. 13, 2023, 4:14:25 p.m. UTC
```

**Comment by danielroe** [comment]
This will be true of any SPA - it's trying to download files that have been replaced on the server and no longer exist. We plan to provide support for detecting new deploys and allowing a prompt to reload (or maybe a seamless update), and we can track in https://github.com/nuxt/nuxt/issues/14739.
