### ISSUE TITLE
Pinia state change from middleware isn't updated on initial page load

### ISSUE THREAD

**Issue by AlexLavoie42** [nuxt/nuxt#19010]
### Environment

Nuxi 3.2.0

RootDir: /home/projects/nuxt-starter-rqbcyr
Nuxt project info: 

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `-`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@pinia/nuxt@0.4.6`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-rqbcyr?file=pages/index.vue

### Describe the bug

When clicking on a link, state changes to pinia that are done in a middleware are visible. However, when you visit the url directly it is not.

You can reproduce in [this example](https://stackblitz.com/edit/nuxt-starter-rqbcyr?file=pages/index.vue) by adding ```/secure``` directly to the url instead of clicking on the link.

**Comment by madebyfabian** [comment]
I would guess this is because pinia never inits before you change the value for the first time, but correct me if I'm wrong here.

**Comment by AlexLavoie42** [comment]
Shouldn't it throw `getActivePinia was called with no active Pinia.` in that case?

I noticed when testing that it seems to change the state on the server side but not on the client.

**Comment by madebyfabian** [comment]
Yeah I think it should throw if this was the case, you're right. Does the middleware even run on the client, have you checked that?

**Comment by AlexLavoie42** [comment]
No I don't believe so. Putting a breakpoint in chrome dev tools doesn't trigger but it does when using the link. If you put a breakpoint on the server it seems to be the opposite.

**Comment by danielroe** [comment]
Pinia data is reactive and not scoped to a particular route. While we suspend the change to the route, we can't control or suspend the pinia state while navigating (in other words, allow rendering two different states - one visible and one in a suspense fork) though this is something pinia might be able to do (or you could handle this in your own logic). So I would expect changes to reactive data in middleware would be visible before the navigation completes.
