### ISSUE TITLE
Nuxt3 cannot use tailwindcss in dynamic class

### ISSUE THREAD

**Issue by FatNerdPeng** [nuxt/nuxt#19013]
### Environment

node: v16.15.1
nuxt: ^3.2.0
tailwindcss: ^6.2.0

### Reproduction

https://stackblitz.com/edit/github-ky7itr

### Describe the bug

Hello team,I want to use the style of tailwindcss: https://tailwindcss.com/docs/gradient-color-stops
![image](https://user-images.githubusercontent.com/33616855/218634502-d5355b67-27e2-4e0c-8384-f8b1b1ed1385.png)
so I wrote this:
![image](https://user-images.githubusercontent.com/33616855/218634900-2f6dc7bc-b64f-4198-91b9-d65f7e7104b9.png)
result:
![image](https://user-images.githubusercontent.com/33616855/218634938-c2be1158-d84c-4d52-9dc1-3f975a44d7bb.png)
It's right,now I use dynamic class:
![image](https://user-images.githubusercontent.com/33616855/218635135-da158776-592d-4478-9335-fe5097608ab0.png)
reuslt:
![image](https://user-images.githubusercontent.com/33616855/218635251-5d4470b6-8b4b-40fb-86f5-cec6f66d87e6.png)
![image](https://user-images.githubusercontent.com/33616855/218635291-94917206-671f-4c5d-966d-fcb1eec6c5d2.png)
It can be seen from the console that the style is indeed written into the class,so what did I wrong?If you can see right style,please  
restart the project,thanks.

**Comment by madebyfabian** [comment]
Hey, Tailwind needs to have all class name listed as actual values somewhere in your code. Where are those class names generated? If you need to have them dynamic, consider adding all variants of them to the tailwind `safelist` config. See https://tailwindcss.com/docs/content-configuration#safelisting-classes 

Not a Nuxt issue though, so can be closed.

**Comment by manniL** [comment]
As @madebyfabian said 👍🏻
