### ISSUE TITLE
useCookie update problem

### ISSUE THREAD

**Issue by isgleb** [nuxt/nuxt#19023]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@6.14.18`
- Builder:          `vite`
- User Config:      `vite`, `build`, `runtimeConfig`, `modules`
- Runtime Modules:  `@vueuse/nuxt@9.12.0`
- Build Modules:    `-`

### Reproduction

```
<template>
  <div>
    <div>
      <div>firstCookie: {{firstCookie}}</div>
      <div>secondCookie: {{secondCookie}}</div>
      <button @click="update">update</button>
    </div>
  </div>
</template>

<script setup lang="ts">
import {useCookie} from "nuxt/app";

const firstCookie = useCookie<any>('first')
firstCookie.value = firstCookie.value || {'1': 1}

const secondCookie = useCookie<any>('second')
secondCookie.value = secondCookie.value || {'1': 1}

function update() {
  const newFirstObject = getNewObject(firstCookie.value)
  firstCookie.value = Object.assign(firstCookie.value, newFirstObject )

  const  newSecondObject = getNewObject(secondCookie.value)
  secondCookie.value = {...secondCookie.value, ...newSecondObject }
}

function getNewObject(current: any) {
  const valArray :number[] = Object.values(current)
  const nextValue :number = Math.max(...valArray) + 1
  const key :string = nextValue.toString()

  const newObject :any = {};
  newObject[key] = nextValue
  return newObject
}

</script>
<style scoped>
</style>
```

### Describe the bug

If I use Object.assign() to update value of useCookie, then value seems to be updated, but on the page reload this update is lost.
If I use Spread operator  ( {...obj, ...obj2}) , everything works fine
tested in dev mode

**Comment by isgleb** [comment]
> Hey,
> 
> Could you please create a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction) :)
> 
> I will take a look at it

Well...
https://stackblitz.com/edit/github-dpfobc-xu1xdh?file=app.vue

there It works in an opposite way... Spread operator is not saved, Object.assign works

**Comment by Baroshem** [comment]
In my case (from the reproduction link) both cases are not saved. Is it correct?
