### ISSUE TITLE
'npx nuxi info' command actual version not display

### ISSUE THREAD

**Issue by yeonjulee1005** [nuxt/nuxt#19025]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.0.0-rc.14`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `ssr`, `target`, `routes`, `app`, `css`, `vite`, `build`, `components`, `imports`, `modules`, `buildModules`, `nitro`, `i18n`, `image`, `vueuse`, `typescript`, `facebook`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.9`, `@pinia/nuxt@0.4.6`, `@nuxt/image-edge@1.0.0-27919678.2f5b64b`, `@vueuse/nuxt@9.12.0`, `@element-plus/nuxt@1.0.3`, `@nuxtjs/robots@3.0.0`, `@nuxtjs/device@3.1.0`, `nuxt-jsonld@2.0.7`, `nuxt-simple-sitemap@1.0.7`
- Build Modules:    `nuxt-facebook-pixel-module@1.5.0`, `unplugin-icons/nuxt`

### Reproduction

[reproduction link](https://stackblitz.com/edit/github-jumn8q-t2bsfq?file=app.vue)

`npx nuxi upgrade --force`

and run 
`npx nuxi info`

then, 
The actual used version and the displayed version
are displayed differently like the screenshot.

(nuxt  version, nitro version)

<img width="419" alt="스크린샷 2023-02-14 오후 10 25 48" src="https://user-images.githubusercontent.com/57179957/218751914-da0e8d73-2281-4d6a-a571-f0db8ef5c424.png">

### Describe the bug

`npx nuxi info` actual using version and displayed version is difference.
(nuxt, nitro version)

**Comment by Baroshem** [comment]
Hey, could you please paste here your `package.json`?

It seems to me that the nuxi info might be returning a content of package.json while the actual used version (from lock file) is the one that is updated from nuxi update --force.

**Comment by yeonjulee1005** [comment]
@Baroshem 

here it is my project 'package.json'
i also use 'npx nuxi upgrade --force'
🥲

'''

{
  "private": true,
  "engines": {
    "node": ">=18.12.0"
  },
  "scripts": {
    "dev": "nuxt dev --dotenv .env.dev",
    "stage": "nuxt dev --dotenv .env.stage",
    "build": "nuxt build --dotenv .env.stage",
    "generate": "nuxt generate -dotenv .env.stage",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@element-plus/nuxt": "^1.0.3",
    "@intlify/unplugin-vue-i18n": "^0.8.1",
    "@nuxt/image-edge": "^1.0.0-27919678.2f5b64b",
    "@nuxt/typescript-build": "^2.1.0",
    "@nuxtjs/device": "^3.0.0",
    "@nuxtjs/eslint-config-typescript": "^12.0.0",
    "@typescript-eslint/eslint-plugin": "^5.50.0",
    "@typescript-eslint/parser": "^5.50.0",
    "eslint": "^8.33.0",
    "eslint-plugin-vue": "^9.9.0",
    "firebase": "^9.16.0",
    "nuxt": "^3.2.0",
    "nuxt-simple-sitemap": "^1.0.6",
    "typescript": "^4.9.5",
    "vue-i18n": "^9.2.2"
  },
  "dependencies": {
    "@element-plus/icons-vue": "^2.0.10",
    "@nuxt/typescript": "^2.8.1",
    "@nuxtjs/robots": "^3.0.0",
    "@pinia/nuxt": "^0.4.6",
    "@vueuse/core": "^9.12.0",
    "@vueuse/nuxt": "^9.12.0",
    "element-plus": "^2.2.29",
    "json-hash": "^1.2.0",
    "nuxt-facebook-pixel-module": "^1.5.0",
    "nuxt-jsonld": "^2.0.7",
    "pinia": "^2.0.30",
    "qs": "^6.11.0",
    "sass": "^1.58.0",
    "sass-loader": "^13.2.0",
    "unplugin-icons": "^0.15.2",
    "unplugin-vue-components": "^0.23.0",
    "vue-dragscroll": "^4.0.5",
    "vue-gtag": "^2.0.1",
    "vue-social-sharing": "^4.0.0-alpha4",
    "vue3-touch-events": "^4.1.0"
  }
}
'''

**Comment by yeonjulee1005** [comment]
humm. i see i'ill try again! 

i try reproduction, but, in stackbliz this phenomenon has not been reproduced.

(try re install `nuxt:v3.0.0-rc.14`) -> `npx nuxi info` -> but, not updated `nuxi info` below

i'll update my reproduction :) !!

<img width="791" alt="스크린샷 2023-02-15 오전 6 35 51" src="https://user-images.githubusercontent.com/57179957/218868558-c65a7835-c0a9-4175-a404-9ad7997ef056.png">

**Comment by yeonjulee1005** [comment]
@Baroshem  It might be cache problem, my office project is fine :)
I'll closed Issue! Thanks ❤️
