### ISSUE TITLE
Layout doesn't inherit scoped-hash data attribute

### ISSUE THREAD

**Issue by zumm** [nuxt/nuxt#19029]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-yhsjem?file=pages/index.vue

### Describe the bug

If layout transaction is off then layout doesn't inherit `data-v-<hash>` attribute for scoped css.

**Comment by danielroe** [comment]
This is now working with the latest Nuxt v3.5: https://stackblitz.com/edit/github-yhsjem-nbdh9z
