### ISSUE TITLE
Cannot read properties of null (reading 'data')

### ISSUE THREAD

**Issue by ADBrusov-SERPTOP** [nuxt/nuxt#19030]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.14.0`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `app`, `modules`, `components`, `build`, `googleFonts`, `headlessui`, `runtimeConfig`
- Runtime Modules:  `@nuxt/devtools@0.1.2`, `@nuxtjs/tailwindcss@6.4.0`, `@nuxt/image-edge@1.0.0-27919678.2f5b64b`, `@nuxtjs/google-fonts@3.0.0-1`, `@vueuse/nuxt@9.12.0`, `nuxt-headlessui@1.1.1`, `nuxt-icon@0.1.8`
- Build Modules:    `-`
------------------------------

### Reproduction

app/router.options.ts
```ts
import type { RouterConfig } from "@nuxt/schema";
export default <RouterConfig>{
  routes: () => [
    {
      name: "repair",
      path: "/:brand/repair/",
      component: () => import("~/pages/repair/index.vue"),
    },
    {
      name: "repair-model",
      path: "/:brand/repair/model/:model/",
      component: () => import("~/pages/repair/model.vue"),
    },
  ],
};
```

pages/repair/index.vue
```js
<template>
   <div>
    <SectionA :data="getSectionData('hero')" />
    <SectionB :data="getSectionData('prices')" />
  </div>
</template>

<script setup>
const brand = useBrand();

const { data, error } = await useFetch("/api/v1/repair", {
  params: { brand },
});

const getSectionData = (sectionId) => {
  return data.value.data.blocks.find((block) => block.id === sectionId);
};
</script>
```

server/api/v1/repair/index.get.js
```js
import hero from "@/data/hero.json";
import prices from "@/data/prices.json";

export default defineEventHandler(async (event) => {
  const { brand } = getQuery(event);

  /* ... use brand ... */

  return {
    data: {
      blocks: [
        {
          id: "hero",
          title: hero.title,
          data: hero.data,
        },
        {
          id: "prices",
          title: prices.title,
          data: prices.data,
        },
      ],
    },
  };
});
```

### Describe the bug

After update page i get error and strange behavior of data - caching. After refresh page i get old data. Helps - restarting the project, but the error with extracting data remains.

### Additional context

```js
runtime-core.esm-bundler.js:40 [Vue warn]: Unhandled error during execution of render function 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouteProvider key="/tesla/repair/" routeProps= {Component: {…}, route: {…}} pageKey="/tesla/repair/"  ... > 
  at <FragmentWrapper > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <App key=2 > 
  at <NuxtRoot>

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'data')
    at Proxy.getSectionData (index.vue:89:1)
    at Proxy._sfc_render (index.vue:96:1)
    at renderComponentRoot (runtime-core.esm-bundler.js:914:44)
    at hydrateSubTree (runtime-core.esm-bundler.js:5621:44)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5642:25)
    at ReactiveEffect.run (reactivity.esm-bundler.js:190:25)
    at instance.update (runtime-core.esm-bundler.js:5763:56)
    at setupRenderEffect (runtime-core.esm-bundler.js:5777:9)
    at runtime-core.esm-bundler.js:1506:17
```

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by ADBrusov-SERPTOP** [comment]
Sure - https://stackblitz.com/edit/github-fcgytc?file=pages%2Frepair%2Findex.vue

**Comment by danielroe** [comment]
What do you need to do to trigger the error?

**Comment by amihhs** [comment]
I have the same problem. The data of asycnData will be null after the request is completed.
Appears when requested by the client

add some code
```js
async function test() {
  const { data, error } = await useFetch('/api/v1/repair', {
    params: { brand },
  });
  console.log('data', data);
}

if (typeof window !== 'undefined') {
  test();
}
```
![image](https://user-images.githubusercontent.com/59364234/218915289-05032c2d-ec47-4ed9-b746-f55c269934b5.png)

**Comment by ADBrusov-SERPTOP** [comment]
Problems with caching and not updated without reload project - https://www.loom.com/share/7f1317bb841c4457883d9e4de2d1799e

On stackblitz or codesandbox no such behavior. 
[StackBlitz](https://stackblitz.com/) `npx nuxi info` 
```
------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

local environment `npx nuxi info`
```
------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.14.0`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

**Comment by manniL** [comment]
> I have the same problem. The data of asycnData will be null after the request is completed. Appears when requested by the client
> 
> add some code
> 
> ```js
> async function test() {
>   const { data, error } = await useFetch('/api/v1/repair', {
>     params: { brand },
>   });
>   console.log('data', data);
> }
> 
> if (typeof window !== 'undefined') {
>   test();
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/59364234/218915289-05032c2d-ec47-4ed9-b746-f55c269934b5.png)

This is different. You don't `await` `test()` here.

**Comment by danielroe** [comment]
the issue here is that you are triggering the fetch for the first time on the client. To avoid a hydration mismatch, on initial load, we defer client-only calls of useFetch (like this one) to after the component has mounted. This is the correct behaviour and in this case you should check if data is null before accessing it.

**Comment by ADBrusov-SERPTOP** [comment]
This problem is observed only on the local machine, there is no such behavior on Stackblitz. Perhaps it is related to OS Windows.

A similar problem is seen in - #18964

**Comment by danielroe** [comment]
so you're saying that cloning the stackblitz on windows exhibits the bug?

**Comment by ADBrusov-SERPTOP** [comment]
@danielroe, yes

**Comment by danielroe** [comment]
I think this is the same issue as https://github.com/nuxt/nuxt/issues/18635. Let's track there.

**Comment by poldelgado** [comment]
I 've the same problem using node v18.17.1 in ubuntu 22.04, but using node v16.17.0 works fine

**Comment by RezaErfani67** [comment]
i have too...
check this link
https://doctorjs.ir/article/fastApi-websocket-send-recieve-file
