### ISSUE TITLE
failed to resolve NuxtLink when used in dependency

### ISSUE THREAD

**Issue by TimvdEijnden** [nuxt/nuxt#19037]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.19.0`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-h59wrv?file=pages/index.vue

- press the button
- the page does not navigate to /about

### Describe the bug

The nuxt-link inside the dependency example-lib does not work. it's not connected to the nuxt-link component.

### Additional context

Code
https://github.com/TimvdEijnden/example-nuxt
https://github.com/TimvdEijnden/example-lib

### Logs

```shell-script
chunk-3NMN3MUW.js?v=e2403010:1381 [Vue warn]: Failed to resolve component: nuxt-link
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <MyRouterLink to="/about" is-nuxt="" > 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouteProvider key="/" routeProps= Object pageKey="/"  ... > 
  at <FragmentWrapper > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <App key=2 > 
  at <NuxtRoot>
```

**Comment by manniL** [comment]
Please link to the main stackblitz not the webcontainer address ☺️

**Comment by TimvdEijnden** [comment]
> Please link to the main stackblitz not the webcontainer address ☺️

Updated 👍🏻

**Comment by danielroe** [comment]
You need to ensure that:

1. your library is transpiled
2. you import `NuxtLink` from `#components`

We do not auto-import into library code as the performance cost would be high, and it's reasonable for library authors to import explicitly.

**Comment by TimvdEijnden** [comment]
I solved it by creating a plugin:

plugins/fix-nuxt-link.ts
``` ts
import {defineNuxtPlugin} from "#app";
import {NuxtLink} from "#components";

// without this the nuxt-link inside our Component Library is not working
export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component('NuxtLink', NuxtLink)
})
```

add this to nuxt.config.ts:
```ts
plugins: [
    '~/plugins/fix-nuxt-link.ts',
]
  ```
