### ISSUE TITLE
useFetch的几个钩子现在是函数，希望变成数组形势

### ISSUE THREAD

**Issue by f754699** [nuxt/nuxt#19046]
### Describe the feature

我重新封装了一下useFetch，在使用的时候，通过onRequest添加Authorization。
等我在组件内使用的时候，为了不触发依赖改变的自动请求，我就在onRequest函数内注入body参数，这样表单数据修改的时候，不会触发自动请求。

由于onRequest是一个函数，所以我需要自己进行嵌套函数。
如果是一个数组，就可以在数组随便push了。

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by madebyfabian** [comment]
Hello, please be so kind and write in english, so we can read your issue. Thanks!

**Comment by f754699** [comment]
> 

$fetch  do not change headers.
i want change header-Authorization  to auth user.

**Comment by manniL** [comment]
@f754699 You can apply headers to `$fetch` too.
