### ISSUE TITLE
Simplify the Nuxt app loading screen

### ISSUE THREAD

**Issue by TakCastel** [nuxt/nuxt#19066]
### Describe the feature

I beg you please consider users with older computers and for the sake of our mother earth remove the heavy CSS Nuxt loading screen loads please please please 🙏🙏🙏

<img width="930" alt="Capture d’écran 2023-02-15 à 17 06 53" src="https://user-images.githubusercontent.com/11198968/219084005-6b014f54-0868-4957-bdca-106570376941.png">

Best regards!

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
If you hover over the top right corner, you can disable it - your preference is saved in local storage 😊

**Comment by TakCastel** [comment]
I purge my localStorage about 5 times a day plus I don't think it is green IT solution. 
Would you please consider setting this by default ?

Thank you for your time :)
