### ISSUE TITLE
Nuxt JS Cannot read properties of undefined (reading 'has') on page load custom plugin

### ISSUE THREAD

**Issue by sts-ryan-holton** [nuxt/nuxt#19067]
### Environment

```
  System:
    OS: macOS 12.6.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 555.04 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 9.2.0 - /usr/local/bin/npm
  npmPackages:
    @nuxt/components: 2.2.1 => 2.2.1 
    nuxt: 2.16.1 => 2.16.1 
```

### Reproduction

N/A

### Describe the bug

I've written a plugin in my Nuxt JS 2.16.x project called permission. I'll use it to return a boolean value of whether a user has permissions to do something.

If I try to add this to a div and refresh my page, I get the following Nuxt error:

> Cannot read properties of undefined (reading 'has')

### Additional context

My markup is:

```html
<template>
  <div>
    ...
    <section v-if="$permission.has('country_index')">
      has permission
    </section>
    ...
  </div>
</template>
```

My `permission.js` plugin file:

```javascript
export default function ({ app, store, context }, inject) {
  inject('permission', {

    /*
    ** has permission
    */
    has (permission) {
      return true
    }

  })
}
```

It's being imported:

```javascript
{ mode: 'client', src: '@/plugins/permissions.js' },
```

My mode:

```javascript
/*
  ** Nuxt rendering mode
  ** See https://nuxtjs.org/api/configuration-mode
  */
  ssr: true,
  /*
  ** Nuxt target
  ** See https://nuxtjs.org/api/configuration-target
  */
  target: 'static',
```

**Comment by danielroe** [comment]
the issue is that this is only added on the client, but you are using `$permission.has` on the server as well.

**Comment by sts-ryan-holton** [comment]
@danielroe What would you suggest?

**Comment by danielroe** [comment]
Inject the plugin on the server too?

**Comment by sts-ryan-holton** [comment]
Okay, I just tried both of the following approaches, both of which still give me the same error:

```javascript
plugins: [
    { mode: 'client', src: '@/plugins/permissions.js' },
    { mode: 'server', src: '@/plugins/permissions.js' },
],
```

and

```javascript
plugins: [
    { src: '@/plugins/permissions.js' },
],
```

I don't think I'm missing anything else?

**Comment by danielroe** [comment]
No, that should work. Would you make a minimal reproduction?
