### ISSUE TITLE
Type definition for `v-model` directive on native input is wrong

### ISSUE THREAD

**Issue by andrei-gheorghiu** [nuxt/nuxt#19079]
### Environment

{}

### Reproduction

https://codesandbox.io/p/sandbox/agitated-mendeleev-ypytew

### Describe the bug

`v-model` on native `<input />` tags should not be treated as an alias of `:value`. Firstly, because it's a directive. In essence, a function. In some cases, it has the same effect as 
```html
<input :value="text"
       @input="event => text = event.target.value />
```
but not in all cases (e.g: `type`s of `'checkbox' | 'radio'`, where `v-model` can be set to a selection array and `:value` points the individual item).

### Additional context

The bug can be circumvented:
```html
<input
  v-model="selection"
  v-bind="{ value: option, type }"
/>
```
or ignored:
```html
<input
   v-model="selection"
   :data-foo="/* ts-ignore */"
   :value="option"
   :type="type"
/>
```
but that doesn't change the fact the type definition for `v-model` directive is wrong.
___
Initially encountered it on [SO](https://stackoverflow.com/questions/75452800/typescript-error-on-input-value-in-template-loop-through-object-keys-in-vue-3-n) (I'm tao in that discussion - I thought it would be a good idea if I reported the bug back to you).

**Comment by danielroe** [comment]
Thank you for letting me know. In future, type errors would be worth reporting instead to https://github.com/vuejs/language-tools or https://github.com/vuejs/core.

But in this case I think the issue is a change in behaviour in Vue 3 with regard to form inputs rather than a bug: see https://vuejs.org/guide/essentials/forms.html. For example:

> v-model will ignore the initial value, checked or selected attributes found on any form elements. It will always treat the current bound JavaScript state as the source of truth. You should declare the initial value on the JavaScript side, using the data option.

**Comment by danielroe** [comment]
The tooltip isn't coming from Nuxt but from Volar.

**Comment by andrei-gheorghiu** [comment]
I'll post it on their repo then. Thank you.

**Comment by danielroe** [comment]
It's not a dependency of Nuxt. It's an IDE extension/language server in use in the code sandbox and used widely by Vue devs.
