### ISSUE TITLE
nuxt2，打包以后css重复加载问题！

### ISSUE THREAD

**Issue by th74100** [nuxt/nuxt#19071]
![1](https://user-images.githubusercontent.com/100682190/219241666-bf2bff38-6c09-48b3-86e6-31f8982e6625.png)
![2](https://user-images.githubusercontent.com/100682190/219241679-53df80cf-448b-4082-b66a-8f3add0f0e28.png)

nuxt ^2.15.8，打包以后浏览器重复加载导致样式代码片段重复，请问怎么解决这个问题？？

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by th74100** [comment]
> 你能提供[复制品](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)吗？🙏

https://github.com/th74100/nuxt2.15.8_test

**Comment by manniL** [comment]
Repro is not available anymore. Closing here.
