### ISSUE TITLE
Make path and file name of "app/router.options.ts" customizable

### ISSUE THREAD

**Issue by TokugawaTakeshi** [nuxt/nuxt#19081]
### Describe the feature

I opening this issue with permission got in [How to rename the "app" directory and "router.options.ts"?](https://github.com/nuxt/nuxt/discussions/18954) discussion. 

I am very grateful about Nuxt development team has provided the [free organizing of the project structure](https://nuxt.com/docs/api/configuration/nuxt-config/#dir).
But would you please to allow to organize the "router.options.ts" file (to change its name and directory)? 
Currently, its path [has been hardcoded](https://github.com/nuxt/nuxt/blob/dda0cebc761c00042ad82bb4c2a47b679581755a/packages/nuxt3/src/pages/module.ts#L87).

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Linked: https://github.com/nuxt/nuxt/issues/18966. What about just allowing to configure the `app/` directory path? Is there any use-case for needing to change the `router.options.ts` file name?

**Comment by TokugawaTakeshi** [comment]
@danielroe 

Thank you for the reaction on my issue.

> Is there any use-case for needing to change the router.options.ts file name?

* If this file is been used only for defining of the custom routes, the "CustomRoutes.ts" is more exact name for this file.
* If there are only custom routes in the project, the "Routes.ts" is  is more exact name for this file.

**Comment by AloisSeckar** [comment]
if to change it, I would rather make it similar to other configuration files, so everyone is aware at first sight, that it has something to do with configuration...it should be `router.config.ts` then...it is even importing an object called **`RouterConfig`**, but for some reason the file was called "options"

**Comment by danielroe** [comment]
The directory is now configurable via `dir.app` - which defaults to `srcDir` in the new v4 directory structure: https://github.com/nuxt/nuxt/issues/26444.

**Comment by TokugawaTakeshi** [comment]
Thank you for the support!
Just one more question left: what the `app` directory is intended for?
Currently, no such directory explained in "Directory structure" of the documentation.
Maybe, it means the "configuration"?
