### ISSUE TITLE
Throwing an error on pages with /api/ in the path renders a JSON response instead of HTML

### ISSUE THREAD

**Issue by ydnar** [nuxt/nuxt#19093]
### Environment

- Operating System: `Darwin`
- Node Version:     `v19.6.0`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `pnpm@7.27.0`
- Builder:          `vite`
- User Config:      `telemetry`, `modules`, `vite`, `runtimeConfig`, `css`, `app`, `content`, `i18n`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.9`, `@nuxt/content@2.4.3`
- Build Modules:    `-`

### Reproduction

Create a page, e.g. `pages/docs/api/[...slug].vue` and load content or throw an error with `createError()`.

Nuxt will render a JSON 404 response instead of correctly rendering error.vue in HTML with the error.

### Describe the bug

Nuxt uses Nitro’s `isJsonRequest` to determine if it should render a JSON response, regardless of the underlying content.

`isJsonRequest` assumes that if the request path contains `/api/`, then it’s a JSON request. Except it’s not.

We use these for our API docs, e.g.: <https://domainr.com/docs/api/v2/search>

The correct behavior for a 404 is to render an HTML 404 page: <https://domainr.com/docs/api/v2/does-not-exist>

### Additional context

https://github.com/unjs/nitro/blob/f7eed65069f02904a58b7c97f2da55c55c39d4f5/src/runtime/utils.ts#L39-L47

**Comment by danielroe** [comment]
This should be resolved in nitropack v2.2.2. which you can get with `yarn upgrade nuxt` or `npm upgrade nuxt` - or in the next Nuxt patch, which we expect to release shortly.

**Comment by chrisnoden** [comment]
Is there a way to ensure JSON is returned rather than HTML? If I want to return a specific error status with a JSON body, how might I do this from within a NUXT project (specifically in the `/api/` directory?

**Comment by Arkadipta1998** [comment]
@danielroe can you answer the comment from @chrisnoden above. I used createError in all of my API routes and relied on the JSON error response for toast messages in my application. Please advise.

**Comment by danielroe** [comment]
@Arkadipta1998 It should still render JSON if you are fetching the API with $fetch in your app - is this not the case?

**Comment by Arkadipta1998** [comment]
@danielroe Nope. Checked now. error.data gives the error page HTML not the JSON.

**Comment by danielroe** [comment]
It should certainly be JSON. The upstream PR was right but we need to resolve this issue too.

**Comment by maxdzin** [comment]
Same for me. I tried `npm upgrade nuxt` but still, it returns HTML instead of JSON.

**Comment by Arkadipta1998** [comment]
@maxdzin please recheck once with `npx nuxi upgrade -f`. Because the issue is resolved in my case

**Comment by maxdzin** [comment]
@Arkadipta1998 yes, it works now with `npx nuxi upgrade -f`. Thank you, mate!
