### ISSUE TITLE
Auto-import of utils function not working in api route

### ISSUE THREAD

**Issue by Ragura** [nuxt/nuxt#19091]
### Environment

```
- Operating System: `Darwin`
- Node Version:     `v18.14.0`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `pnpm@7.26.3`
- Builder:          `vite`
- User Config:      `modules`, `app`, `i18n`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.9`, `@nuxt/image-edge@1.0.0-27919678.2f5b64b`, `@vueuse/nuxt@9.12.0`, `nuxt-icon@0.2.11`, `@nuxtjs/tailwindcss@6.4.0`, `@pinia/nuxt@0.4.6`, `@nuxtjs/google-fonts@3.0.0-1`
- Build Modules:    `-`
```

### Reproduction

https://stackblitz.com/edit/github-4t2gwe?file=server/api/hello.get.ts

### Describe the bug

I'm trying to use an auto-imported function inside a server API route (`server/api`), but Nuxt is returning a 500 error and says the function is not definied. VSCode doesn't complain and recognizes the function and its type. The function also seems to be properly imported in the corresponding files within the `.nuxt` folder. It's important to note that everything works correctly if I manually import the function, so it doesn't seem to be related to any of my own (minimal) code.

You can check it out yourself in the reproduction link. It's a very minimal reproduction of a function called `createAtlasUrl` which returns a mock URL. It is called (with auto-import) from the `server/api/hello.get.ts` file. The API route is then called with `$fetch` inside the `index.vue` page. Visiting this page will show the 500 error.

**Comment by manniL** [comment]
Auto-imports will only work from `server/utils` in the `server` folder. See https://github.com/nuxt/nuxt/pull/18848/files

**Comment by Ragura** [comment]
> Auto-imports will only work from `server/utils` in the `server` folder. See #18848

Ah, I wasn't aware of that! Thank you for the explanation and link.
