### ISSUE TITLE
esbuild: The platform "darwin" is incompatible with this module.

### ISSUE THREAD

**Issue by mrleblanc101** [nuxt/nuxt#19104]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.2`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `srcDir`, `app`, `modules`, `content`, `colorMode`, `postcss`, `vite`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.4.0`, `@nuxtjs/color-mode@3.2.0`, `@nuxt/content@2.4.3`, `@vueuse/nuxt@9.12.0`, `@nuxt/image-edge@1.0.0-27919678.2f5b64b`
- Build Modules:    `-`
------------------------------

### Reproduction

Using `yarn`, I get hundred of info log from saying:
> info @esbuild/android-arm@0.17.8: The platform "darwin" is incompatible with this module.

<img width="968" alt="Capture d’écran, le 2023-02-17 à 00 25 39" src="https://user-images.githubusercontent.com/17392251/219557597-718de2bb-f476-4263-bcd2-8d0b5070d8e3.png">

Here is my package.json:
```
{
    "private": true,
    "scripts": {
        "build": "nuxt build",
        "dev": "nuxt dev",
        "generate": "nuxt generate",
        "preview": "nuxt preview",
        "postinstall": "nuxt prepare"
    },
    "devDependencies": {
        "@nuxt/content": "^2.3.0",
        "@nuxt/image-edge": "^1.0.0-27907872.f4dd19d",
        "@nuxtjs/color-mode": "^3.2.0",
        "@nuxtjs/tailwindcss": "^6.2.0",
        "@tailwindcss/typography": "^0.5.8",
        "@types/node": "^18.11.19",
        "nuxt": "^3.1.0",
        "postcss-import": "^15.1.0",
        "prettier": "^2.8.1",
        "remark-reading-time": "^2.0.1",
        "vite-svg-loader": "^4.0.0"
    },
    "dependencies": {
        "@vueuse/components": "^9.10.0",
        "@vueuse/core": "^9.10.0",
        "@vueuse/nuxt": "^9.10.0",
        "vue-disqus": "^5.1.0"
    }
}
```

### Describe the bug

I should not have these message.

**Comment by danielroe** [comment]
Apologies for the console spam, but this is how esbuild has chosen to install the correct binaries for each system. It's safe to ignore, and outside our control.

**Comment by mrleblanc101** [comment]
@danielroe Wow that's horrible, thanks for the tip.

**Comment by mrleblanc101** [comment]
Oops, i had not seen your edit as I read the message from the GitHub email. I guess I'll see if I update my yarn as I don't know if there is breaking change in Yarn 2+ that would impact my workflow. 

Thanks for the tip !

**Comment by danielroe** [comment]
It sounds like you can also upgrade to a higher version of yarn 1 to resolve. (see one of the last comments in the linked issue).
