### ISSUE TITLE
issue with ssr, html class not update when i refresh page ( f5 )

### ISSUE THREAD

**Issue by ERIS-VN** [nuxt/nuxt#19109]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `modules`, `build`, `ssr`, `css`, `postcss`
- Runtime Modules:  `nuxt-swiper@1.0.0`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/node-mbapcr

### Describe the bug

https://user-images.githubusercontent.com/69683870/219596000-c7948a28-4ca5-4768-8156-db794ac0d12c.mp4

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by ERIS-VN** [comment]
Hmm, it works fine in StackBlitz, but not on my computer.
https://stackblitz.com/edit/node-mbapcr

**Comment by ADBrusov-SERPTOP** [comment]
same problem - #19030

**Comment by danielroe** [comment]
I think this is the same issue as https://github.com/nuxt/nuxt/issues/18635. Let's track there.
