### ISSUE TITLE
Defining a route (NuxtPage) requires a `file`, but a redirect does not need a file

### ISSUE THREAD

**Issue by marcdix** [nuxt/nuxt#19115]
### Describe the feature

The `pages:extend` hook gets an array of `NuxtPage` items passed. When adding another item, the `file` property is mandatory. That makes sense for routes that actually render something, but doesn't make sense for routes that are just meant to redirect to another route.

So currently, one needs to provide a file even though it's not used

A full example:
```
'pages:extend': async (routes) => {
  routes.push({
    name: 'index',
    path: '/',
    redirect: '/home',
    file: '~/pages/home.vue' // Needs to be provided here
  })
  routes.push({
    name: 'index',
    path: '/home',
    file: '~/pages/home.vue'
  })
}
```

The type definition of `NuxtPage`:
```
type NuxtPage = {
    name?: string;
    path: string;
    file: string;  // <-- This should be optional (in case of a redirect)
    meta?: Record<string, any>;
    alias?: string[] | string;
    redirect?: string;
    children?: NuxtPage[];
};
```

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by rebyatyonok** [comment]
Can I take this?

**Comment by danielroe** [comment]
Sure, why not?
