### ISSUE TITLE
(Pinia) Store contains incorrect value after the value is set and redirect is performed on the server.

### ISSUE THREAD

**Issue by ironexdev** [nuxt/nuxt#19114]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.14.0`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@pinia/nuxt@0.4.6`
- Build Modules:    `-`

### Reproduction

https://github.com/ironexdev/nuxt3-pinia-issue

- yarn
- yarn dev

Go to "<localhost>/" in order to reproduce the issue using middleware.

Go to "<localhost>/foo" in order to reproduce the issue using page.

### Describe the bug

Hello, I have an issue with (Pinia) store value that is unexpectedly reset when I set in on the server and redirect user to another page.

When the "/" route is loaded, a middleware is triggered that sets the value of fooBarStore.code to "bar" and redirects an user to navigateTo("bar").
  - _Note that I also appended current value as a query parameter to show that value in store is correct before redirection_

**However, after the redirection, the value of fooBarStore.code is reset and on the "/bar" page, the original value "foo" is displayed instead of "bar".**

Without the redirection in the middleware, everything works as expected (the value of code in fooBarStore is changed from "foo" to "bar").

**My question is - is this a bug? And if so, is it a Nuxt or Pinia bug?**

**Middleware (middleware/foo.global.ts)**
![image](https://user-images.githubusercontent.com/24256329/219664997-f07c7759-1df4-4802-9578-a558fc949fd6.png)

**Store (stores/FooBarStore.ts)**
![image](https://user-images.githubusercontent.com/24256329/219665113-215e5921-aa1a-4bb2-923a-df3765436071.png)

**Page (pages/bar.vue)**
![image](https://user-images.githubusercontent.com/24256329/219666015-cdfb6337-9bea-44dc-b631-76a6631bbfe6.png)

**Output (<localhost>/bar)**
![image](https://user-images.githubusercontent.com/24256329/219664832-46f87d7c-6299-4386-8036-114ee7577c64.png)

### Additional context

I also added page "/foo" to the project to show that this issue also occurs when using page instead of middleware for redirection.

Page "/foo" sets value fooBarStore.code to "bar" and redirects user to "/bar" (same as the middleware).

However, after the redirection, the value of fooBarStore.code is reset and on the "/bar" page, the original value "foo" is displayed instead of "bar" (same as with the middleware).

On the "/foo" page I commented out onMounted hook, because if the app redirects user in the onMounted hook, then everything works as expected.

**Page (pages/foo.vue)**
![image](https://user-images.githubusercontent.com/24256329/219668205-f097feac-b2ac-4d80-a7f4-9fb754d3122e.png)

**Store (stores/FooBarStore.ts)**
![image](https://user-images.githubusercontent.com/24256329/219665113-215e5921-aa1a-4bb2-923a-df3765436071.png)

**Page (pages/bar.vue)**
![image](https://user-images.githubusercontent.com/24256329/219666015-cdfb6337-9bea-44dc-b631-76a6631bbfe6.png)

**Output**
![image](https://user-images.githubusercontent.com/24256329/219664885-f89231f7-5c62-4ee4-9e3f-d1e4747f9eb7.png)

**Comment by danielroe** [comment]
When you redirect on the server side, the server sends a response to the client that only contains the new URL. The client then performs a fresh request to the new URL. This means that nothing persists between these two requests in the form of store data. (Though you could set a cookie or use the new session support to persist some data.)

**Comment by ironexdev** [comment]
@danielroe That was fast :D Thank you it is good to know. I will look into new session support (https://github.com/unjs/h3/pull/315) you mentioned.
