### ISSUE TITLE
Throwing an error on pages with /api/ in the path renders a JSON response instead of HTML

### ISSUE THREAD

**Issue by tuananh924** [nuxt/nuxt#19110]
### Environment

let port = 3333;
let host = "192.168.1.40";
module.exports = {
  dev: false,
  ssr: false,
  target: "static",
  server: { port, host },
  crypt: {
    key: "ibsd83ibu20isdbe043a89sdhf7wfh79feksdfhdu2erh9221ffb389fn920cdsn",
    index: 43,
  },
  axios: {
    baseURL: "http://" + host + ":" + port,
  },
  limit_log: 10,
  router: {
    middleware: ["guest"],
  },
  auth: {
    strategies: {
      local: {
        endpoints: {
          login: {
            url: "/api/user/login",
            method: "post",
            propertyName: "token",
          },
          logout: { url: "/api/checkuser/logout", method: "post" },
          user: {
            url: "http://" + host + ":" + port + "/api/checkuser/info",
            method: "get",
            propertyName: "id",
          },
        },
        tokenRequired: true,
        tokenType: "",
        // autoFetchUser: true
      },
    },
  },
  head: {
    title: "Business Information",
    meta: [
      { charset: "utf-8" },
      { name: "viewport", content: "width=device-width, initial-scale=1" },
      { hid: "description", name: "description", content: "Nuxt.js project" },
    ],
    link: [
      //{ rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' },
      {
        rel: "stylesheet",
        href: "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons",
      },
    ],
    script: [],
  },
  loading: false,
  srcDir: "client/",
  css: ["element-ui/lib/theme-chalk/index.css"],
  modules: ["@nuxtjs/axios", "@nuxtjs/auth"],
  plugins: ["@/plugins/element-ui", "@/plugins/excel"],
  build: {
    postcss: null,
    transpile: [/^element-ui/],
    extend(config, ctx) {},
  },
};

### Reproduction

https://github.com/AngelMunoz/sails-nuxt.git

### Describe the bug

Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'token' in <!doctype html>

**Comment by danielroe** [comment]
See https://github.com/nuxt/nuxt/issues/19093. This should be resolved in nitropack v2.2.2. which you can get with `yarn upgrade nuxt` or `npm upgrade nuxt` - or in the next Nuxt patch, which we expect to release shortly.
