### ISSUE TITLE
Dependencies from local package layer not installed/found

### ISSUE THREAD

**Issue by niklaswolf** [nuxt/nuxt#19124]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.1`
- Package Manager:  `npm@8.19.3`
- Builder:          `vite`
- User Config:      `extends`, `shopware`, `modules`, `i18n`
- Runtime Modules:  `modules/domainRuntimeInfo`
- Build Modules:    `-`

### Reproduction

See bug report

### Describe the bug

When using a local package as a nuxt layer, the dependencies do not get installed. Because of that, a module installed and registered in the layer will not be available in the project using the layer and result in the error message

>  ERROR  Cannot find module 'XYZ' 

I tried adding the layer package also a local dependency of the project, [like so ](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#local-paths), but no success either.

I could obviously add the dependency to the project itself, too, but that's not the point of layers am I right? 

### Additional context

Layer package nuxt.config.js
```js
modules: [
    'the-module-package',
  ],
```

Project using the layer nuxt.config.js
```js
extends: ['../my-layer']
modules: [],
```

**Comment by danielroe** [comment]
This is a currently documented limitation of layers: https://nuxt.com/docs/getting-started/layers#layers. We can track support in https://github.com/nuxt/nuxt/issues/13367.

**Comment by samuveth** [comment]
@danielroe sorry, but where exactly is that documented on the page you linked?

**Comment by danielroe** [comment]
Sorry, should have linked https://nuxt.com/docs/guide/going-further/layers

**Comment by basemkhirat** [comment]
Thanks for awesome Layers feature of Nuxt. I have a question.

Is auto-installing feature working in Nuxt modules?

As example, If the module is placed in a relative path in filesystem, Nuxt - in this case - will auto install the module depencies with base project?

**Comment by avxkim** [comment]
@danielroe do i understand correctly, that we have to manually install packages are being used in a layer on our main app, that extends that layer?

For example:
Layer: has @nuxtjs/tailwind module installed,
App: must install @nuxtjs/tailwind either

That's expected behavior?

**Comment by avxkim** [comment]
@pi0 i just removed dependency from `App` and tried to start it `pnpm dev`: 
got an error: "Cannot start nuxt:  Cannot find module '/Users/alexanderkim/Sites/bazarjoq-new/nuxt-icon' "

this `nuxt-icon` is installed in layer in `dependencies`.

**Comment by DanCuatro** [comment]
I also have 

```
extends: [
  ['../my-layer', { install: true }]
]
```

but it's throwing this error: 

`Cannot find module 'C:/laragon/www/test-layer/nuxt-icon'`

**Comment by dsvgl** [comment]
It would be very great to have this. We want to migrate our nuxt2 monorepo with 20 apps to nuxt 3 and managing 20 package.json deps is not something I'm looking forward to 🫣

**Comment by pi0** [comment]
@avxkim @DanCuatro if you can reproduce, please make a new issue 🙏🏼

**Comment by oripka** [comment]
I have made a reproduction one can test it using these two nuxt.config.js

`nuxt.config.js`

```
export default defineNuxtConfig({
  devtools: { enabled: true },
  extends: [
    ['github:oripka/nuxt-bug-extends-1#main', { install: true}]
  ]
})
```

The error is:

```
pnpm install
Lockfile is up to date, resolution step is skipped
Already up to date

> nuxt-app@ postinstall /Users/otr/code/reproduce/oripka
> nuxt prepare

Lockfile is up to date, resolution step is skipped
Packages: +1312
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 1312, reused 1311, downloaded 0, added 1312, done

dependencies:
+ @aws-sdk/client-ses 3.540.0
+ @fontsource/inter 5.0.17
+ @heroicons/vue 2.1.3
+ @iconify-json/flag 1.1.49
+ @iconify-json/ph 1.1.11
+ @iconify-json/simple-icons 1.1.97
+ @morev/vue-transitions 2.3.6
+ @nuxt/content 2.12.1
+ @nuxt/ui-pro 1.1.0
+ @nuxthq/studio 0.14.1
+ @nuxtjs/fontaine 0.4.1
+ @nuxtjs/google-fonts 3.2.0
+ @nuxtjs/plausible 0.2.4
+ @nuxtjs/supabase 1.2.0
+ @paddle/paddle-js 0.5.5
+ @paddle/paddle-node-sdk 0.3.0
+ @vercel/kv 1.0.1
+ @vueuse/core 10.9.0
+ @vueuse/nuxt 10.9.0
+ mermaid 10.9.0
+ nuxt-icon 0.5.0
+ openai 4.32.1
+ stripe 14.23.0
+ unique-names-generator 4.7.1
+ v-calendar 3.1.2
+ vue3-marquee 4.2.0

devDependencies: skipped because NODE_ENV is set to production

Done in 4.7s

 ERROR  Error while requiring module nuxt-time: Error: Cannot find module '/Users/otr/code/reproduce/oripka/nuxt-time'      8:58:19 PM
Require stack:
- /Users/otr/code/reproduce/oripka/index.js


 ERROR  Cannot find module '/Users/otr/code/reproduce/oripka/nuxt-time'                                                     8:58:19 PM
Require stack:
- /Users/otr/code/reproduce/oripka/index.js

  Require stack:
  - index.js
  at Module._resolveFilename (node:internal/modules/cjs/loader:1142:15)
  at Function.resolve (node:internal/modules/helpers:190:19)
  at Function._resolve [as resolve] (node_modules/.pnpm/jiti@1.21.0/node_modules/jiti/dist/jiti.js:1:251148)
  at resolveModule (node_modules/.pnpm/@nuxt+kit@3.11.2/node_modules/@nuxt/kit/dist/index.mjs:2210:29)
  at requireModule (node_modules/.pnpm/@nuxt+kit@3.11.2/node_modules/@nuxt/kit/dist/index.mjs:2215:24)
  at loadNuxtModuleInstance (node_modules/.pnpm/@nuxt+kit@3.11.2/node_modules/@nuxt/kit/dist/index.mjs:2451:92)
  at async installModule (node_modules/.pnpm/@nuxt+kit@3.11.2/node_modules/@nuxt/kit/dist/index.mjs:2407:47)
  at async initNuxt (node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.0_floating-vue@5.2.2_unocss@0.59.0_vite@5.2.8/node_modules/nuxt/dist/index.mjs:4233:7)
  at async loadNuxt (node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.0_floating-vue@5.2.2_unocss@0.59.0_vite@5.2.8/node_modules/nuxt/dist/index.mjs:4331:5)
  at async loadNuxt (node_modules/.pnpm/@nuxt+kit@3.11.2/node_modules/@nuxt/kit/dist/index.mjs:2570:19)
  at async Object.run (node_modules/.pnpm/nuxi@3.11.1/node_modules/nuxi/dist/chunks/prepare.mjs:53:18)
  at async runCommand$1 (node_modules/.pnpm/nuxi@3.11.1/node_modules/nuxi/dist/shared/nuxi.9edf0930.mjs:1648:16)
  at async runCommand$1 (node_modules/.pnpm/nuxi@3.11.1/node_modules/nuxi/dist/shared/nuxi.9edf0930.mjs:1639:11)
  at async runMain$1 (node_modules/.pnpm/nuxi@3.11.1/node_modules/nuxi/dist/shared/nuxi.9edf0930.mjs:1777:7) 



 ERROR  Cannot find module '/Users/otr/code/reproduce/oripka/nuxt-time'                                                     8:58:19 PM
Require stack:
- /Users/otr/code/reproduce/oripka/index.js
```

Not sure why NODE_ENV is set to production, but ok, I move all the dependencies from `devDependencies` to `dependencies`, just to try to get it working (btw. it works fine without this in the original repo). 



Using this I can get rid of that error but run into another one. Here the repo from the branch `icons` (as we run into problems with ui-pro and the icons packages)

```
export default defineNuxtConfig({
  devtools: { enabled: true },
  extends: [
    ['github:oripka/nuxt-bug-extends-1#icons', { install: true}]
  ]
})
```

```
pnpm install
Lockfile is up to date, resolution step is skipped
Already up to date

> nuxt-app@ postinstall /Users/otr/code/reproduce/oripka
> nuxt prepare

Lockfile is up to date, resolution step is skipped
Already up to date

devDependencies: skipped because NODE_ENV is set to production

Done in 1s

 WARN  Missing supabase url, set it either in nuxt.config.js or via env variable                                            9:01:38 PM


 WARN  Missing supabase anon key, set it either in nuxt.config.js or via env variable                                       9:01:38 PM


 ERROR  Icon collection "heroicons" not found. Please install @iconify-json/heroicons or @iconify/json                      9:01:38 PM

  at node_modules/.c12/github_oripka_nuxt_R9fl2pEn9N/node_modules/.pnpm/@egoist+tailwindcss-icons@1.7.4_tailwindcss@3.4.3/node_modules/@egoist/tailwindcss-icons/dist/index.js:83:19
  at Array.reduce (<anonymous>)
  at getIconCollections (node_modules/.c12/github_oripka_nuxt_R9fl2pEn9N/node_modules/.pnpm/@egoist+tailwindcss-icons@1.7.4_tailwindcss@3.4.3/node_modules/@egoist/tailwindcss-icons/dist/index.js:79:22)
  at setup (node_modules/.c12/github_oripka_nuxt_R9fl2pEn9N/node_modules/.pnpm/@nuxt+ui@2.15.1_nuxt@3.11.1_rollup@4.14.0_vite@5.2.8_vue@3.4.21/node_modules/@nuxt/ui/dist/module.mjs:397:96)
  at async normalizedModule (node_modules/.c12/github_oripka_nuxt_R9fl2pEn9N/node_modules/.pnpm/@nuxt+kit@3.11.1_rollup@4.14.0/node_modules/@nuxt/kit/dist/index.mjs:2112:17)
  at async installModule (node_modules/.pnpm/@nuxt+kit@3.11.2/node_modules/@nuxt/kit/dist/index.mjs:2415:95)
  at async initNuxt (node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.0_floating-vue@5.2.2_unocss@0.59.0_vite@5.2.8/node_modules/nuxt/dist/index.mjs:4233:7)
  at async loadNuxt (node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.0_floating-vue@5.2.2_unocss@0.59.0_vite@5.2.8/node_modules/nuxt/dist/index.mjs:4331:5)
  at async loadNuxt (node_modules/.pnpm/@nuxt+kit@3.11.2/node_modules/@nuxt/kit/dist/index.mjs:2570:19)
  at async Object.run (node_modules/.pnpm/nuxi@3.11.1/node_modules/nuxi/dist/chunks/prepare.mjs:53:18)
  at async runCommand$1 (node_modules/.pnpm/nuxi@3.11.1/node_modules/nuxi/dist/shared/nuxi.9edf0930.mjs:1648:16)
  at async runCommand$1 (node_modules/.pnpm/nuxi@3.11.1/node_modules/nuxi/dist/shared/nuxi.9edf0930.mjs:1639:11)
  at async runMain$1 (node_modules/.pnpm/nuxi@3.11.1/node_modules/nuxi/dist/shared/nuxi.9edf0930.mjs:1777:7) 



 ERROR  Icon collection "heroicons" not found. Please install @iconify-json/heroicons or @iconify/json                      9:01:38 PM

 ELIFECYCLE  Command failed with exit code 1.
```

Maybe I have an error in my config or I missing something fundamental about how this feature should work. @pi0  is this a bug?

**Comment by bitmonti** [comment]
@pi0 https://stackblitz.com/~/github.com/bitmonti/layer-not-installed

```
❯ cd repo-extend-install
❯ pnpm install
```
Thank you for your help! 🙏🏼

**Comment by ricardoprins-paqt** [comment]
Hey @pi0, it looks like @MuhammadM1998 has made a new issue with example repositories: https://github.com/nuxt/nuxt/issues/26479

I'm running into the same problem, even with completely fresh repositories. Could someone look into this? It would be greatly appreciated. :)

**Comment by Brads3290** [comment]
The ongoing issue here seems to be about dev dependencies specifically. Runtime dependencies do work fine as @pi0 said.

See [my comment here](https://github.com/nuxt/nuxt/issues/13367#issuecomment-2081659386) and #26980

**Comment by MuhammadM1998** [comment]
@Brads3290 It's not about `devDeplendencies`. I saw your issue and that's actually the expected & documented behavior as others commented in the issue and not a bug. I created an issue with reproductions for this https://github.com/nuxt/nuxt/issues/26479

**Comment by Brads3290** [comment]
@MuhammadM1998 My mistake. 

I assumed since it was a module that you were trying to depend on in your layer, that it was installed as a dev dependency (since `nuxi module add` does that by default). I see you've added it under `dependencies` in your layer, though.

**Comment by federicoibba** [comment]
If you have a local layers folder that declare dependencies not available in the main `package.json`, an easy way to force the installation of those dependencies could be to declare the layer as a dapendency.

Sorry for the poor explanation, I will describe here an example.

```
main-application
├── layers/              # Layers folder
│   ├── layer-project    # Layer project
│      ├── package.json  # Layer package.json
├── package.json         # Main application package.json
```

 **Layers package.json** `layers/layer-project/package.json`
```
{
  "name": "@layer/project",
  "dependencies": {
    "sass": "^1.92.0"
  }
}
```

**Main application package.json** :`main-application/package.json`:
```
{
  // other properties
  "dependencies": {
    "@layer/project": "file:layers/layer-project"
  }
}
```

This will force the main project to access to the `sass` dependency and install it.
 
Hope someone will find this helpful 😄
