### ISSUE TITLE
Also allow `<NuxtLink>` to execute prefetch when `to` type props are `RouteLocationRaw`

### ISSUE THREAD

**Issue by Mini-ghost** [nuxt/nuxt#19136]
### Describe the feature

In earlier issue, I mention a feature request that `preloadRouteComponents` allows passing values of type `RouteLocationRaw`👉 #18845 .

But I fund that the `<NuxtLink>` prefetch (or preload) just only execute when the props `to` type is string,

```html
<!-- Passing a string -->
<!-- It will prefetch -->
<NuxtLink to="/home"> Home </NuxtLink>

<!-- Passing a string with query string -->
<!-- It will prefetch -->
<NuxtLink to="/home?year=2023"> Home </NuxtLink>

<!-- Passing a object -->
<!-- It will no prefetch -->
<NuxtLink :to="{ name: 'home', query: { year: '2023' } }"> Home </NuxtLink>
```

That's because of the following code:
https://github.com/nuxt/nuxt/blob/524426ed64087d750fd6f9ee8c160d2e39a8a428/packages/nuxt/src/app/components/nuxt-link.ts#L179-L180

One of the conditions for `shouldPrefetch` is `typeof to.value === 'string'`. 

Is this expected? Or can this limit be remove?

If allow prefetch when `<NuxtLink>` to passing a value type of `RouteLocationRaw`, the  app runtime lifecycle hook `link:prefetch` type must also be updated together

https://github.com/nuxt/nuxt/blob/524426ed64087d750fd6f9ee8c160d2e39a8a428/packages/nuxt/src/app/nuxt.ts#L38

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
resolved in https://github.com/nuxt/nuxt/pull/19144
