### ISSUE TITLE
Ambiguous error notification in Nuxt 3.2.2 with typeScript: { typeCheck: true }

### ISSUE THREAD

**Issue by mcrapts** [nuxt/nuxt#19145]
### Environment

❯ npx nuxi info
Nuxi 3.2.2

RootDir: /home/projects/nuxt-starter-5vb8p7
Nuxt project info: 

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.2`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `typescript`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

1. Define { typeScript: { typeCheck: true } } in nuxt.config.ts
2. Run `npm run dev`
3. Weird error notification without any message pops up

![image](https://user-images.githubusercontent.com/16231555/219884115-d4191580-e151-4ae1-ad14-33a4e10f366a.png)

Reproduction sandbox:
https://stackblitz.com/edit/nuxt-starter-5vb8p7?file=nuxt.config.ts

### Describe the bug

Error badge shouldn't appear without any error message

**Comment by Ayoazeez26** [comment]
Hi @danielroe I would like to work on this. I have gone through the contribution guide as this is my first time contributing so any helping tips would be appreciated

**Comment by danielroe** [comment]
You would be very welcome to do so! The first thing I would check is whether it's an upstream issue with vite-plugin-checker.

Feel free to DM me on discord if I can be of help or you have any questions.

**Comment by ziadsarour** [comment]
I still have this error in ```Nuxt 3.2.3 with Nitro 2.2.3```

**Comment by ludioao** [comment]
same error with nuxt 3.3.1 / nitro 2.3.1

:/

**Comment by danielroe** [comment]
This is now resolved in the latest version of `vite-plugin-checker`, which you can pull in by `npm upgrade vite-plugin-checker`.

**Comment by mcrapts** [comment]
Great! Upgrading to the latest vue-tsc (`npm i vue-tsc@latest`) also did the trick for me.

**Comment by mcfarljw** [comment]
I can open a new issue for this but I'm seeing this issue again. Might be related to https://github.com/fi3ework/vite-plugin-checker/issues/238.

**Comment by mcrapts** [comment]
This issue is also happening again for me.

**Comment by oniice** [comment]
Happening for me with nuxt 3.8.2 on a fresh install/setup

**Comment by 1cor13** [comment]
Happening to me on nuxt 3.9.3
