### ISSUE TITLE
Possible to render default slot in `<NuxtErrorBoundary>` on error

### ISSUE THREAD

**Issue by OlaAlsaker** [nuxt/nuxt#19140]
### Describe the feature

If you use the current `<NuxtErrorBoundary>` it will always render the `error`-slot on error, even if you do not provide a template to the slot. So if an error occurs inside the boundary, and no slot is provided, the component will just render a blank slot.

Would it be smart to have an option to disable this, so that `<NuxtErrorBoundary>` can be used to just catch the errors without doing any changes in the template? 😄 

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by huang-julien** [comment]
Hi :wave: I wanted a similar bahavior with a `ClientOnly` only if it failed in SSR. 
Here's the PR : 
https://github.com/nuxt/framework/pull/8216
Is this what you want ? 🤔
