### ISSUE TITLE
The option "default" type of useAsyncData should be ReturnType<Transform>

### ISSUE THREAD

**Issue by green-mike** [nuxt/nuxt#19153]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.2`
- Package Manager:  `pnpm@7.9.0`
- Builder:          `vite`
- User Config:      `modules`, `experimental`, `vite`, `content`, `runtimeConfig`, `css`, `elementPlus`, `routeRules`
- Runtime Modules:  `@vueuse/nuxt@9.12.0`, `@unocss/nuxt@0.49.7`, `@pinia/nuxt@0.4.6`, `@nuxt/content@2.4.3`, `@element-plus/nuxt@1.0.3`
- Build Modules:    `-`
------------------------------

### Reproduction

https://codesandbox.io/p/sandbox/small-sun-wcwk4o?file=%2Fapp.vue&selection=%5B%7B%22endColumn%22%3A3%2C%22endLineNumber%22%3A18%2C%22startColumn%22%3A3%2C%22startLineNumber%22%3A18%7D%5D

### Describe the bug

Sometimes the transform function may change the return type and it may no longer be DataT. In this case, having DataT as the default will cause TypeScript to report a type error.

AsyncDataOptions define default would be DataT
```typescript
export interface AsyncDataOptions<
  DataT,
  Transform extends _Transform<DataT, any> = _Transform<DataT, DataT>,
  PickKeys extends KeyOfRes<_Transform> = KeyOfRes<Transform>
> {
  server?: boolean
  lazy?: boolean
  default?: () => DataT | Ref<DataT> | null
  transform?: Transform
  pick?: PickKeys
  watch?: MultiWatchSources
  immediate?: boolean
}
```

use ReturnType<Transform> might be a solution.
```typescript
export interface AsyncDataOptions<
  DataT,
  Transform extends _Transform<DataT, any> = _Transform<DataT, DataT>,
  PickKeys extends KeyOfRes<_Transform> = KeyOfRes<Transform>
> {
  server?: boolean
  lazy?: boolean
  default?: () => ReturnType<Transform>
  transform?: Transform
  pick?: PickKeys
  watch?: MultiWatchSources
  immediate?: boolean
}
```

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/14437.
