### ISSUE TITLE
ability to configure glob pattern used to match pages

### ISSUE THREAD

**Issue by joel-wenzel** [nuxt/nuxt#19155]
### Environment

------------------------------        
- Operating System: `Windows_NT`      
- Node Version:     `v16.17.0`        
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.2`
- Package Manager:  `npm@8.18.0`      
- Builder:          `vite`
- User Config:      `app`, `router`, `ssr`, `css`, `build`, `nitro`, `typescript`, `modules`, `srcDir`, `imports`, `runtimeConfig`, `components`        
- Runtime Modules:  `@pinia/nuxt@0.4.6`
- Build Modules:    `-`
------------------------------        

### Reproduction

https://github.com/joel-wenzel/nuxt3-exclude-pages

### Describe the bug

It seems .nuxtignore or `ignore` property in nuxt.config is the only way to exclude pages. It works great but it also excludes HMR updates which isnt ideal.

The specific scenario is keeping components or composables closer to the page index. Changes to these should trigger HMR updates but not generate a page.

The only way to update these ignore files is restarting the dev server. This was possible in nuxt 2.

### Additional context

To reproduce:

- clone provided repo
- npm run dev
- navigate to the `test` page
- try changing anything in pages/test/components/HelloTest.vue component
- no HMR update triggers

**Comment by joel-wenzel** [comment]
Created https://github.com/nuxt/nuxt/pull/19181
Not sure if it is really the right spot in nuxt.config for it but seemed to be the least invasive

**Comment by danielroe** [comment]
This was my comment the last time we discussed this: https://github.com/nuxt/nuxt/issues/12333#issuecomment-1418944966.

How do you feel about that solution?

**Comment by joel-wenzel** [comment]
I think it will be more common actually for larger apps, but I am fine with the hook approach also. I update the PR to just include a doc update with your provided example

**Comment by danielroe** [comment]
Okay, let's document and merge it for now. I'm very happy to revisit later on.

Thank you for your work on this. ❤️
