### ISSUE TITLE
[nuxt] [request error] [unhandled] [500] Cannot find module './lib/axios'  

### ISSUE THREAD

**Issue by stephenjason89** [nuxt/nuxt#19157]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.2`
- Package Manager:  `pnpm@7.27.1`
- Builder:          `vite`
- User Config:      `buildDir`, `srcDir`, `css`, `build`, `imports`, `modules`, `runtimeConfig`
- Runtime Modules:  `@pinia/nuxt@0.4.6`, `()`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/stephenjason89/nuxt-vuetify-graphql-pinia-starter/tree/feat/apollo

### Describe the bug

This is working in my Mac Studio Ultra

Not working on my Mac Laptop throwing error
<img width="1695" alt="image" src="https://user-images.githubusercontent.com/3810177/219969425-fea36813-b078-4a76-90d0-810f2780842d.png">
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/3810177/219969449-0746f87c-c79b-4e34-a154-f91ed89ce9b6.png">

Anyway, I changed axios to $fetch now. 
Leaving this issue open for other people.

**Comment by harlan-zw** [comment]
Would it be possible to provide a minimal reproduction with stackblitz?

**Comment by stephenjason89** [comment]
Unfortunately, I can't recreate the issue at stackblitz @harlan-zw .
As i've stated earlier, it works in my mac studio ultra and doesn't work on my macbook laptop.
I just tested on stackblitz and it is also working.

**Comment by Baroshem** [comment]
> Unfortunately, I can't recreate the issue at stackblitz @harlan-zw .
> 
> As i've stated earlier, it works in my mac studio ultra and doesn't work on my macbook laptop.
> 
> I just tested on stackblitz and it is also working.
> 
> 
> 
> I think it would be hard without a reproduction.
> 
> 
> 
> Should I close this issue now?

If it cannot be reproduced I would recommend to close the issue. If you will manage to reproduce it, feel free to reopen the issue :)
