### ISSUE TITLE
antdv [Vue warn]: Hydration node mismatch

### ISSUE THREAD

**Issue by codingcn** [nuxt/nuxt#19161]
### Environment

```
- Operating System: `Darwin`
- Node Version:     `v18.14.0`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `typescript`, `telemetry`, `experimental`, `app`, `css`, `alias`, `build`, `postcss`, `modules`, `components`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`

```

### Reproduction

https://stackblitz.com/edit/github-ilbkqd?file=app.vue

open console and `hover`  dropdown

### Describe the bug

When using both antdv and nuxt3, an error ` Hydration node mismatch` is generated

https://www.antdv.com/components/dropdown

### Logs

```shell-script
chunk-3WQO23Z4.js?v=45f46078:1411 [Vue warn]: Hydration node mismatch:
- Client vnode: Symbol(Comment) 
- Server rendered DOM: "" (text) 
  at <AMenuItem> 
  at <Anonymous> 
  at <ResizeObserver disabled=true onResize=fn<onOverflowResize2> > 
  at <Overflow onMousedown=undefined prefixCls="ant-dropdown-menu-overflow" component="ul"  ... > 
  at <AMenu mode="vertical" selectable=false expandIcon=fn<expandIcon2>  ... > 
  at <Align target=fn<bound getRootDomNode> key="popup" ref=Ref< undefined >  ... > 
  at <BaseTransition onBeforeEnter=fn<onBeforeEnter> appear=false persisted=false  ... > 
  at <Transition ref=Ref< undefined > onBeforeEnter=fn<onShowPrepare2> > 
  at <PopupInner prefixCls="ant-dropdown" point=null align= {points: Array(2), overflow: {…}, offset: Array(2), targetOffset: Array(2), ignoreShake: true}  ... > 
  at <Popup prefixCls="ant-dropdown" destroyPopupOnHide=false visible=true  ... > 
  at <Portal key="portal" getContainer=fn<bound getContainer4> didUpdate=fn<bound handlePortalUpdate> > 
  at <Trigger openClassName=undefined minOverlayWidthMatchTrigger=undefined alignPoint=undefined  ... > 
  at <Anonymous arrow=undefined trigger="hover" visible=undefined  ... > 
  at <ADropdown> 
  at <App key=2 > 
  at <NuxtRoot>
```

**Comment by danielroe** [comment]
You are trying to register the individual components as Vue plugins, which isn't working. Instead, you can globally register them as components, or simply import them into your setup function

```js
// ❌ this is how you register a vue plugin
app.use(Dropdown);
// ✅ this is how you register a Vue component
app.component('ADropdown', Dropdown);
// ✅ this is also done automatically for the component if you simply import it
import { Dropdown as ADropdown } from 'ant-design-vue';
```

**Comment by codingcn** [comment]
<img width="1916" alt="image" src="https://user-images.githubusercontent.com/16743078/220104683-c8925beb-a906-42bf-801f-6f98464914d1.png">

@danielroe Sorry, my previous code was written incorrectly. But my main problem here is `Hydration node mismatch`. I don't know whether it's Nuxt3 or andv.

https://stackblitz.com/edit/github-ilbkqd?file=app.vue

**Comment by danielroe** [comment]
You can add it to your `build.transpile`. Likely the issue is the need to deduplicate the `vue` import:

```js
  build: {
    transpile: [/ant-design/]
  }
```

**Comment by daomiaru** [comment]
> <img alt="image" width="1916" src="https://user-images.githubusercontent.com/16743078/220104683-c8925beb-a906-42bf-801f-6f98464914d1.png">
> 
> @danielroe Sorry, my previous code was written incorrectly. But my main problem here is `Hydration node mismatch`. I don't know whether it's Nuxt3 or antdv.
> 
> https://stackblitz.com/edit/github-ilbkqd?file=app.vue

bro,I have encountered the same problem as you on my end. Have you resolved it

**Comment by chipdisko** [comment]
try wrapping `<ClientOnly>...</ClientOnly>`to your Icon.

**Comment by fskarmeta** [comment]
Hi there, i guess i brought the same issue up in the ant design module. Transpiling did sadly not work and using ClientOnly isn't the optimal solution of course. 
https://github.com/vueComponent/ant-design-vue-nuxt/issues/21
