### ISSUE TITLE
{pending} from useAsyncData always true though set { immediate: false }

### ISSUE THREAD

**Issue by gezichenshan** [nuxt/nuxt#19189]
### Environment

Nuxt project info:                                                    18:58:57

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `npm@8.1.0`
- Builder:          `vite`
- User Config:      `srcDir`, `modules`, `alias`, `app`, `components`, `vite`, `pinia`, `ssr`
- Runtime Modules:  `@unocss/nuxt@0.49.4`, `@pinia/nuxt@0.4.6`
- Build Modules:    `-`
------------------------------

### Reproduction

I will provide tomorrow in office

### Describe the bug

```
const { data, refresh, pending } = useAsyncData(
  `taxstatus-${props.rfc}`,
  () =>
    props.type === "PM"
      ? getPMTaxStatus(props.rfc, props.password)
      : getPFTaxStatus(props.rfc, props.password),
  { immediate: false }
);
```
The pending is always true.

**Comment by oleghalin** [comment]
useAsyncData returns Promise, you forgot prepend await. 
```
const { data, refresh, pending } = await useAsyncData(..
```

**Comment by danielroe** [comment]
I think the issue is the same as https://github.com/nuxt/nuxt/issues/15714.

Here's our plan and reasoning: https://github.com/nuxt/nuxt/issues/18810.

**Comment by gezichenshan** [comment]
@danielroe Oh sorry I've searched the pending issue but not found that one already exists.
Thanks.
