### ISSUE TITLE
beforeRouteEnter has been trigger twice time with ssr:false

### ISSUE THREAD

**Issue by decba78b** [nuxt/nuxt#19195]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.2`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `ssr`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-ayd4su-kgsang?file=pages%2Ftest.vue,pages%2Ftest1.vue,app.vue,nuxt.config.ts

### Describe the bug

I try to make some authentication before I enter specific page, such as the sample page `test1.vue`.
If I enter `/test1` to access, `beforeRouteEnter` has twice log, one is from `/test` page.I try to make a new vite project, it can't be reproduced.
Is there any problem with `ssr:false`?

**Comment by danielroe** [comment]
The route will be pushed twice, from the vue router point of view, once on page load, and again after plugins have run (to give them a chance to add middleware). In a Nuxt project, you can add router middleware which will only be run once, in the right place, using `addRouteMiddleware`: https://nuxt.com/docs/api/utils/add-route-middleware#addroutemiddleware.
