### ISSUE TITLE
nuxt instance unavailable

### ISSUE THREAD

**Issue by sebhofmann** [nuxt/nuxt#19196]
### Environment

RootDir: /home/projects/github-pq8e17                                                                             15:59:18
Nuxt project info:                                                                                                15:59:18

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.2`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

[Stackblitz Example](https://stackblitz.com/edit/github-pq8e17?file=app.vue)

```
<template>
  <div>
    <h1>Test</h1>
  </div>
</template>
<script setup lang="ts">
let load = async (slug: string) => {
  const result1 = await useFetch('http://echo.jsontest.com/key/value/one/two', {
    key: 'one',
  });

  const result2 = await useFetch(
    'http://echo.jsontest.com/key/value/three/four',
    { key: 'two' }
  );
};

await load('example');
</script>

```

### Describe the bug

In my app i need to first fetch a JSON which i then use to fetch a Second JSON. 
I want to wrap the code for loading into an extra function, to reuse them. 
The first fetch in the example gets executed, but the second one throws the following error:
```
500
nuxt instance unavailable

at Module.useAsyncData (./node_modules/nuxt/dist/app/composables/asyncData.mjs:24:38)
at Module.useFetch (./node_modules/nuxt/dist/app/composables/fetch.mjs:54:43)
at load (./app.js:14:51)
at async setup (./app.js:20:90)
```

**Comment by danielroe** [comment]
You can read more about why this is occuring here: https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables

**Comment by sebhofmann** [comment]
The documentation states `... except within <script setup> blocks ...` does this mean all child blocks, like the load function in my example do not work?

**Comment by danielroe** [comment]
You have some alternatives, like `Promise.all` and `callWithNuxt`, for those cases. But really you should not create async composables as a rule.

**Comment by sebhofmann** [comment]
I rewrote my code to
```
<template>
  <div>
    <h1>Test</h1>
  </div>
</template>
<script setup lang="ts">
let load1 = async (slug) => {
  const result1 = await useFetch('http://echo.jsontest.com/key/value/one/two', {
    key: 'one',
  });
  return 'fine';
};

let load2 = async (slug) => {
  const result2 = await useFetch(
    'http://echo.jsontest.com/key/value/three/four',
    { key: 'two' }
  );
  return 'two';
};

let one = await load1('example');
await load2(one);
</script>
```
Which now works, but the behaviour of the composables seems to be inconsistent to me.
