### ISSUE TITLE
I haven't cookie in SSR mode

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/nuxt#19194]
### Environment

Nuxi 3.2.2                                                                                                        15:03:15
                                                                                                                  15:03:15
RootDir: /home/projects/nuxt-starter-agg7l3                                                                       15:03:15
Nuxt project info:                                                                                                15:03:16

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.2`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                       15:03:16

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Reproduction

https://stackblitz.com/edit/nuxt-starter-agg7l3

### Describe the bug

i want create a cookie ('fapid') when i start the application, and spread it in all requests.

I see the cookies in VUE mode, but not in SSR node mode

**Comment by agracia-foticos** [comment]
Any Solution?

**Comment by danielroe** [comment]
You need to provide a leading slash:

```diff
- await useFetch('api/test');
+ await useFetch('/api/test');
```
