### ISSUE TITLE
`nuxi generate` doesn't prerender dynamic pages

### ISSUE THREAD

**Issue by Intevel** [nuxt/nuxt#19191]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.7.0`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.2`
- Package Manager:  `pnpm@7.5.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/Intevel/nuxt-netlify-404

### Describe the bug

A strange bug reported on the Discord, related Post: https://discord.com/channels/473401852243869706/1077514559839010886

In the project there is a Dynamic Route, in the Reproduction under `pages/packages/[slug].vue`.

With `nuxi generate` the page is not prerendered, in a Netlify deployment this leads to Netlify setting a 404 response status code but rendering the page anyway.

At first we thought it was a Netlify problem because the 404 error did not occur locally. And the 404 error was the reported problem.
I tried deploying it to Vercel, and it worked there. With the only difference that Vercel deploys with `nuxt build`, and I think then nitro adds `routeRules` for static routes.

Also, no HTML file is created for the dynamic page, and `view-source:` in the browser does not show the direct markup content either, which is definitely bad for SEO.

/cc @madebyfabian @sharkfin009

**Comment by danielroe** [comment]
You will need to have a link to dynamic pages within a page that Nuxt is crawling, or you can add them to your `nitro.prerender.routes` array. Otherwise Nuxt doesn't know what paths to generate.
