### ISSUE TITLE
Error in console when typeCheck enabled

### ISSUE THREAD

**Issue by mcfarljw** [nuxt/nuxt#19202]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `typescript`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-mfcerh?file=package.json,nuxt.config.ts

### Describe the bug

Running `npm run dev` with `typeCheck: true` shows error text with no additional context despite.

<img width="380" alt="Screenshot 2023-02-21 at 4 00 31 PM" src="https://user-images.githubusercontent.com/4167341/220457377-aba8fddb-e78c-48b7-996d-13f46ead755d.png">

### Additional context

It doesn't seem to actually break anything and settings `typeCheck: false` does resolve the issue. This seems to have popped up in the last release or so.

### Logs

```shell-script
Nuxi 3.2.2                                                                                          15:52:08
Nuxt 3.2.2 with Nitro 2.2.3                                                                         15:52:08
                                                                                                    15:52:09
  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.1.104:3000/

ℹ Vite client warmed up in 776ms                                                                    15:52:11
✔ Nitro built in 325 ms                                                                       nitro 15:52:12

 ERROR                                                                                              15:52:14
[vue-tsc] Found 0 errors. Watching for file changes.
```

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/19145.
