### ISSUE TITLE
Switch back to devalue mainstream

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt#19201]
Context: [Tweet](https://twitter.com/rich_harris/status/1628054361095000069?s=46&t=UOhaZgoecAWFwMnbm4WjDA) shared by @Atinux.

For serializing and restoring SSR state, we started using [devalue](https://github.com/Rich-Harris/devalue) in Nuxt 2. We made a fork [@nuxt/devalue](https://github.com/nuxt-contrib/devalue) in order to prevent hard errors about non-serializable objects plus few security fixes. Since this issue happens less often, we might switch back to upstream. (new [custom types](https://github.com/Rich-Harris/devalue#custom-types), could be also integrated via nuxt plugins)

**Note:** Newer version requires **runtime parser** function to be added to app if we want to switch to pure JSON.

**Comment by pi0** [comment]
@danielroe i am working on it :)

**Comment by danielroe** [comment]
I already had a local implementation.

**Comment by danielroe** [comment]
@pi0 I didn't mean to stop you - feel free to implement!

Of course, we can collaborate on landing the PR if there are any challenges (plus, from my reading, there will also be some fun next steps, so I expect this is more than a single PR).
