### ISSUE TITLE
useRoute().query params only update on page refresh

### ISSUE THREAD

**Issue by dentych** [nuxt/nuxt#19204]
### Environment

➜  workspace git:(master) npx nuxi info
Nuxi 3.2.2                                                                 23:09:20
                                                                           23:09:21
RootDir: /project/home/dentych/workspace                                   23:09:21
Nuxt project info:                                                         23:09:21

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.3`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://codesandbox.io/p/sandbox/clever-shirley-tndlev

1. Click one of the two links (message or HERE) on the page.
2. See that it says `The message is:` with no message after
3. Refresh page
4. See that it now says `The message is: <whatever is in the query parameter message>`
5. Click Back
6. Refresh the index page
7. Click the other link
8. See that the message is again empty
9. Refresh page
10. Message is now displayed
11. Click `Back` (and do not refresh this time)
12. Click the opposite link
13. See that the message is still the previous one
14. :exploding_head: 

### Describe the bug

useRoute().query doesn't update until the page is refreshed. I tried with both SSR = false and the default SSR = true.

I also tried both `router.push({path:"/test", query: {message: "test"}})` and `<NuxtLink to="...">`. (see reproduction link).

**Comment by danielroe** [comment]
The issue you're experiencing is that Nuxt's `useRoute` composable and `<NuxtPage>` component are meant to be used together. (They work around an upstream Vue limitation.)

We can track DX improvements here in https://github.com/nuxt/nuxt/issues/14595.

**Comment by dentych** [comment]
Answer is much appreciated! I changed my real app to use NuxtPage, and now it works as it should! Thank you! :pray:
