### ISSUE TITLE
`useFetch/useAsyncData`: BUG: when `immediate: false`, then `pending` is `true` before call `execute/refresh` (must to be false)

### ISSUE THREAD

**Issue by vasilyman** [nuxt/nuxt#19218]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.17.1`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.2`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `modules`, `css`, `app`, `experimental`, `imports`, `nitro`, `typescript`
- Runtime Modules:  `@pinia/nuxt@0.4.7`, `@nuxtjs/tailwindcss@6.4.1`
- Build Modules:  

### Reproduction

```
// before refresh call asyncData a pending must be false
const { pending: isLoadingOne, refresh: fetchOne } = useFetch('https://jsonplaceholder.typicode.com/todos/1', { immediate: false });

// before refresh call asyncData a pending must be false | perhaps a controversial case
const { pending: isLoadingTwo, refresh: fetchTwo } = await useFetch('https://jsonplaceholder.typicode.com/todos/2', { immediate: false });
```

See full code: https://stackblitz.com/edit/nuxt-starter-9uxzmd?file=app.vue

### Describe the bug

Until the request is forcibly invoked, it is assumed that the waiting status should be false.

**Comment by vasilyman** [comment]
@danielroe see, please

**Comment by vasilyman** [comment]
my current solution is:

```
const useFetchCustom = useFetch(url, options)
  /**
   * TODO: костыль связанный с багом, useFetch (useAsyncData) pending всегда true, если immediate:true
   */
    .then((res) => {
      const pending = res.pending;
      pending.value = !!options.immediate;
      return {
        ...res,
        pending, 
      };
    });
```

**Comment by danielroe** [comment]
I think the issue is the same as https://github.com/nuxt/nuxt/issues/15714.

Here's our plan and reasoning: https://github.com/nuxt/nuxt/issues/18810.

**Comment by vasilyman** [comment]
> I think the issue is the same as #15714.
> 
> Here's our plan and reasoning: #18810.

o, sorry, it is. #18810 will nice feature

**Comment by VladimirCores** [comment]
Why not just set `pending` to false when `immediate: false`?

**Comment by danielroe** [comment]
Because that would be a breaking change.
