### ISSUE TITLE
NuxtConfig typescript not detecting modules options

### ISSUE THREAD

**Issue by RodrigoProjects** [nuxt/nuxt#19214]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `modules`, `i18n`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.9`, `@nuxtjs/apollo@5.0.0-alpha.5`, `@pinia/nuxt`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-ly14ux?file=nuxt.config.ts,package.json,README.md

### Describe the bug

- Installing this 3 modules seem to trigger the bug, could be one individually (i18n, apollo, pinia)
- defineNuxtConfig when we add, for example, i18n options says that those options don't exist inside the NuxtConfig type.

### Additional context

https://discord.com/channels/473401852243869706/1077187385667899422

### Logs

```shell-script
Argument of type '{ modules: string[]; i18n: { noTypescriptWorkingHere: string; }; }' is not assignable to parameter of type 'NuxtConfig'.
  Object literal may only specify known properties, and 'i18n' does not exist in type 'NuxtConfig'.(2345)
```

**Comment by RodrigoProjects** [comment]
Solution: After upgrading to i18n-edge version the issue dissapeared this may be related with an issue they have with the vue-i18n package. Still, its weird the nuxi prepare is not failling on the reproduction

**Comment by martio** [comment]
After creating a new Nuxt application and installing the latest packages, I'm having trouble with TypeScript in "nuxt.config.ts" for "i18n". The command "pnpm dlx nuxi prepare" doesn't help. Deleting the ".nuxt" directory doesn't help either. For object literals, you can only specify known properties, and the "i18n" property does not exist in type "InputConfig<NuxtConfig, ConfigLayerMeta>".

nuxt: 3.10.2,
nuxtjs/i18n: 8.1.1

Updating to edge did not solve the problem.

<img width="751" alt="Zrzut ekranu 2024-02-15 o 09 53 46" src="https://github.com/nuxt/nuxt/assets/133636/2b87e5ff-701e-4efa-8bd5-e2fabba285a4">

**Comment by danielroe** [comment]
@martio This issue was closed almost a year ago. Would you create a new issue with a reproduction? 🙏

**Comment by martio** [comment]
It started working and I don't know how I did it. It seems to be OK. Sorry for the confusion :confounded:

**Comment by dingdangdog** [comment]
> After creating a new Nuxt application and installing the latest packages, I'm having trouble with TypeScript in "nuxt.config.ts" for "i18n". The command "pnpm dlx nuxi prepare" doesn't help. Deleting the ".nuxt" directory doesn't help either. For object literals, you can only specify known properties, and the "i18n" property does not exist in type "InputConfig<NuxtConfig, ConfigLayerMeta>".
> 
> nuxt: 3.10.2, nuxtjs/i18n: 8.1.1
> 
> Updating to edge did not solve the problem.
> 
> <img alt="Zrzut ekranu 2024-02-15 o 09 53 46" width="751" src="https://private-user-images.githubusercontent.com/133636/305011818-2b87e5ff-701e-4efa-8bd5-e2fabba285a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1NTY2NTIsIm5iZiI6MTcyMTU1NjM1MiwicGF0aCI6Ii8xMzM2MzYvMzA1MDExODE4LTJiODdlNWZmLTcwMWUtNGVmYS04YmQ1LWUyZmFiYmEyODVhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMVQxMDA1NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYTEyOGExYTBiZTU3NTRmNGEzNGI1MWIzYmFlMDNiYjliNWNlMGU5YjZmNjQ0ZmU5ZTU5MzFmOGU2M2RiYTYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Xdy1o8k6KVYJzhsy7sZ60inKqo8zgfbexCC3QiPoAS4">

I recently created a new project and this error message appeared after adding `i18n` for the first time, but after running `npm run dev` once, this error will disappear. This seems to be a problem with type checking.

**Comment by danielroe** [comment]
It’s expected you need to run dev server or nuxi prepare to update the types.
