### ISSUE TITLE
Can't create a <Link> component.

### ISSUE THREAD

**Issue by ideafm** [nuxt/nuxt#19221]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.14.0`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `css`, `postcss`, `modules`
- Runtime Modules:  `@pinia/nuxt@0.4.6`, `@vueuse/nuxt@9.12.0`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-obfcsk?file=pages%2Findex.vue,pages%2Ffoo.vue,components%2FLink.vue,components%2FMyLink.vue

### Describe the bug

I get a next warning:
`WARN  Overriding Link component.`
and generated html is `<!-- -->`

### Additional context

I need to add extra prefix to all Links.
It works fine with Nuxt 2, but on migration process on Nuxt 3 it caught an issue

**Comment by danielroe** [comment]
There is a built in Link component in Nuxt for rendering `<link>`s in the head.
