### ISSUE TITLE
SWR not working with nuxt-links

### ISSUE THREAD

**Issue by marco-land** [nuxt/nuxt#19224]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.19.0`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `nitro`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://loquacious-trifle-ebcf45.netlify.app

[GitHub Repo](https://github.com/marco-land/nuxt-route-rules)

### Describe the bug

When using `nuxt-link` with SWR mode they will cause the page to refetch data on every route. What I would expect instead is a cached / static version of that page.

In my example I set up two different links, one with `nuxt-link` and one regular `a` tag. The `a` tags behave as what I expect the `nuxt-link` to behave as well.

In addition to that, `static` option seems to be ignored and seems to behave as `swr`, too.

### Additional context

I tested on Netlify, Vercel and regular node server.

**Comment by danielroe** [comment]
`swr` and `static` are server features and do not currently affect the behaviour of the client-side Vue application. The reason `<a>` behaves differently is that it forces a server-side request.

**Comment by marco-land** [comment]
Does that mean that `swr` is working as expected? I thought the idea was to serve a cached, faster version of the HTML which does not require to wait for `asyncData` to be fetched.

**Comment by danielroe** [comment]
It is working as expected. It's possible we could build in future enhancements but right now the way to implement it would be to move the contents of your asyncData call into a server route (with swr route rule), and then call _that_ route from asyncData.

**Comment by marco-land** [comment]
I see, thank you for clarifying!
