### ISSUE TITLE
Building Nitro Server (preset: cloudflare) Error

### ISSUE THREAD

**Issue by cinob** [nuxt/nuxt#19237]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.3`
- Package Manager:  `pnpm@7.27.1`
- Builder:          `vite`
- User Config:      `app`, `modules`, `css`, `unocss`, `postcss`, `i18n`, `vant`
- Runtime Modules:  `@vueuse/nuxt@9.13.0`, `@unocss/nuxt@0.50.0`, `@pinia/nuxt@0.4.7`, `@nuxtjs/i18n@8.0.0-beta.10`, `@huntersofbook/naive-ui-nuxt@0.6.0`, `@vant/nuxt@1.0.0`
- Build Modules:    `-`

### Reproduction

https://github.com/cinob/nuxt3-cloudflare-preset-issue

### Describe the bug

`NITRO_PRESET=node-server pnpm build` is working fine

Here is the console error message when using `NITRO_PRESET=cloudflare pnpm build`
```
RollupError: Unexpected keyword 'this' (Note that you need plugins to import files that are not JavaScript)


 7: import { checkConfigValid } from '../utils/checkConfigValid';
 8: 
 9: export function getReqUrl(this: any, params) {
                              ^
10:   const ep: any = {};
11:   const isCname = this.options.cname;
```

**Comment by danielroe** [comment]
let's track this in https://github.com/nuxt/nuxt/issues/19017.
