### ISSUE TITLE
server middleware run in reverse order

### ISSUE THREAD

**Issue by rizen** [nuxt/nuxt#19234]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.19.0`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `npm@8.19.3`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/rizen/server-middleware-order

Start it up and hit the / endpoint. You'll see the middleware output in the dev console.

### Describe the bug

This may not be a bug, but if it is not a bug then it is at least unexpected. Nuxt3 server middleware sorts in reverse order.

999                                                                                                                                                                                           
300                                                                                                                                                                                           
111                                                                                                                                                                                           
005                                                                                                                                                                                          
001    

rather than starting with 001 and ending with 999

**Comment by BghinC** [comment]
Looks like this is solved in `3.3.1`
