### ISSUE TITLE
Nuxt Link does not scroll to top on new page...

### ISSUE THREAD

**Issue by GuillaumeDgr** [nuxt/nuxt#19239]
### Environment

- Operating System: `Darwin`
- Node Version:     `v19.1.0`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `pages`, `modules`, `plugins`, `build`, `googleFonts`, `i18n`, `strapi`, `vite`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.3.0`, `@nuxtjs/google-fonts@3.0.0-1`, `@nuxtjs/strapi@1.7.1`, `@nuxtjs/i18n@8.0.0-beta.9`
- Build Modules:    `-`

### Reproduction

Simply add normal `<NuxtLink :to"newPage"></NuxtLink>` or in my situation with i18n :
`<NuxtLink :to="localePath({ name: newPage })"></NuxtLink>`

### Describe the bug

Hi,
I know this was already added in bugs, but none of solutions I found here worked for me...
When clicking a classical NuxtLink, page does not scroll to top.

Solutions I found and tried but not working :

Plugin use : `/plugins/router.ts`
```
import { defineNuxtPlugin } from "#app";

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.$router.options.scrollBehavior = () => {
    return { left: 0, top: 0 };
  };
});
```

Middleware use : `/middleware/route.global.ts`
```
export default defineNuxtRouteMiddleware((to, from) => {
  useNuxtApp().hook("page:finish", () => {
    if (history.state.scroll) {
      setTimeout(() => window.scrollTo(history.state.scroll), 0);
    } else {
      setTimeout(() => window.scrollTo(0, 0), 0);
    }
  });
});
```

And finally router options use : `/app/router.options.ts`
```
import type { RouterConfig } from "@nuxt/schema";

export default <RouterConfig>{
  scrollBehavior(to, _from, savedPosition) {
    return new Promise((resolve, _reject) => {
      setTimeout(() => {
        if (savedPosition) {
          resolve(savedPosition);
        } else {
          if (to.hash) {
            resolve({
              el: to.hash,
              top: 80,
            });
          } else {
            resolve({ top: 0 });
          }
        }
      }, 100);
    });
  },
};
```

or :

```
import type { RouterOptions } from "@nuxt/schema";

export default <RouterOptions>{
  scrollBehavior(to, from, savedPosition) {
    if (savedPosition) {
      return savedPosition;
    } else {
      return {
        top: 0,
        behavior: "smooth",
      };
    }
    return { top: 0 };
  },
};
```

Non of these solutions are working and page never goes top after nuxt link click.

**Comment by GuillaumeDgr** [comment]
Hi, any help on this pls?
Here is my `package.json` file, if could help:
```
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxtjs/google-fonts": "^3.0.0-1",
    "@nuxtjs/i18n": "^8.0.0-beta.9",
    "@nuxtjs/strapi": "^1.7.1",
    "@nuxtjs/tailwindcss": "^6.3.0",
    "@tailwindcss/forms": "^0.5.3",
    "@tailwindcss/typography": "^0.5.9",
    "@types/markdown-it": "^12.2.3",
    "markdown-it": "^13.0.1",
    "nuxt": "npm:nuxt3@latest"
  },
  "dependencies": {
    "@nuxtjs/markdownit": "^2.0.0",
    "daisyui": "^2.49.0",
    "vue-agile": "^2.0.0",
    "vue-easy-lightbox": "^1.12.0",
    "vue-recaptcha": "^2.0.3",
    "vue3-google-map": "^0.15.0"
  }
}
```

**Comment by mario-neuhold** [comment]
I think this is mentioned in the docs, with a link to a workaround: https://nuxt.com/docs/migration/component-options#scrolltotop

**Comment by mario-neuhold** [comment]
your last option is working for me:

```javascript
import type { RouterConfig } from "@nuxt/schema"

export default <RouterConfig>{
    scrollBehavior(to, from, savedPosition) {
        if (savedPosition) {
            return savedPosition;
        } else {
            return {
                top: 0
            };
        }
    }
}
```

can you reproduce the problem in a fresh nuxt3 install?

**Comment by GuillaumeDgr** [comment]
Hi, thanks for your answer but still not working.

**Comment by mario-neuhold** [comment]
can you reproduce the problem in a fresh nuxt3 install? that might help you to narrow down the problem.

**Comment by jpengelbrecht** [comment]
can confirm this a issue all nuxt3 sites.   using vue telescope i found a few.   open a new tab then scroll to top as soon as you can,  you will it it jumps back up.  

https://smartdogcollar.com/
https://dih.telekom.com/en
https://paladium-pvp.fr/

though i think this is being fixed here 
https://github.com/nuxt/nuxt/issues/19664

**Comment by manniL** [comment]
It'd be great if someone could attach a StackBlitz or CodeSandbox as reproduction 👍🏻

**Comment by jpengelbrecht** [comment]
@manniL I am not convinced this would be easily reproducible on stack blitz,  for me this issue is most prominent on new tabs and fast loads.    stackblitz has its own little deploy loader and is a lot slower.

**Comment by Draccano** [comment]
For me does not work neither.

**Comment by manniL** [comment]
> For me does not work neither.

See my comment above please ☺️

**Comment by dargmuesli** [comment]
Also, besides a minimal reproduction, please mention the browser / os you're experiencing the issue in :pray: I think there could potentially be differences between browsers in scrolling behavior.

**Comment by mingtheanlay** [comment]
I also experienced this issue on https://movies.nuxt.space/ also where I tried to click on the movie and the position of the screen does not reset to top, it statyed on where I clicked.

https://github.com/nuxt/nuxt/assets/39415776/785580c5-9c50-4d25-983c-9e97f8809df3

System: MacOS Ventura 13.3.1 
Browser: Brave v1.51.118 (Chromium to 113.0.5672.126)

**Comment by mingtheanlay** [comment]
I found this code on nuxt/movies. I hope it help.

https://github.com/nuxt/movies/commit/20a859bd14d5d80673ea03722aa46ad72d24abe6

**Comment by helltraitor** [comment]
> I found this code on nuxt/movies. I hope it help.
> 
> [nuxt/movies@20a859b](https://github.com/nuxt/movies/commit/20a859bd14d5d80673ea03722aa46ad72d24abe6)

I have this problem too, but in my case 'page:transition:finished' didn't fix the problem, but 'page:finished' did

I wrote next plugin which scrolls page to top. It simulates `definePageMeta({ scrollToTop: true })` behaviour.
So all is you need is to install this plugin and use `definePageMeta` as usual.
In some case,  you can change hook to transition (which is not works for me but may be for you), or set similar code on different hooks

```ts
// scroll.client.ts
export default defineNuxtPlugin({
  name: 'scroll-client',
  hooks: {
    'page:finish': () => {
      if (!useRouter().currentRoute.value.meta.scrollToTop)
        return

      document.scrollingElement?.scrollTo({ left: 0, top: 0 })
      document.body?.scrollTo({ left: 0, top: 0 })
    },
  },
})
```

I don't really expected that Nuxt will be such broken `:(`

* Hope that 3.6.0 will release as soon as possible, because as I understand `definePageMeta` is fixed there

**Comment by Muslihiddin** [comment]
https://github.com/nuxt/nuxt/issues/19239#issuecomment-1564551022

This helped me

**Comment by shiny** [comment]
Happens to me too

**Comment by Stozen-spb** [comment]
CSS scroll-behavior: smooth; Can cuse this behavior

**Comment by danielroe** [comment]
If you are encountering this, please let me know with a minimal reproduction and I'll happily reopen and investigate. 🙏

**Comment by aaronbuckner** [comment]
@danielroe this issue does seem to be an issue when the CSS for smooth-scrolling is set:

html { scroll-behavior:smooth; }

If you set this, it causes NuxtLink to do weird things on new routes, setting the scroll depth of the resulting page to the value of the originating page.  I really think Nuxt should fix this issue as it causes a serious usability problem.  I've looked at this problem on various sites since Nuxt 2.0 and didn't realize the problem was so basic.

Thank you @fos7er for the insight!

**Comment by Chalks** [comment]
holy christ, yes. I just spent forever trying to fix this and this thread is the one that finally clued me in on the `scroll-behavior: smooth` issue. It's bad.

@danielroe here's a minimal reproduction in stackblitz: https://stackblitz.com/edit/nuxt-starter-4f9fpe?file=app.vue It doesn't seem to happen in Chrome, but it definitely hoses Firefox. Here's what it looks like for me:


https://github.com/nuxt/nuxt/assets/6187555/124b872f-1bd3-4e76-8311-e8462587b99b

**Comment by danielroe** [comment]
@Chalks Would you open a new issue, and first check whether it's reproducible without Nuxt (i.e. an upstream vue-router issue?)

https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter

**Comment by Chalks** [comment]
Done. I think there's an easy fix though, so I'll open a PR shortly as well.
