### ISSUE TITLE
Environment Variables don't update.

### ISSUE THREAD

**Issue by sugoidesune** [nuxt/nuxt#19247]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v18.14.0`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `2.1.1`
- Package Manager:  `npm@9.3.1`
- Builder:          `vite`
- User Config:      `css`, `build`, `modules`, `imports`, `runtimeConfig`
- Runtime Modules:  `@pinia/nuxt@0.4.6`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-twwcda?file=.env

### Describe the bug

So i have an .env file. I export the variables via 
```js
    runtimeConfig: {
        public: {
          TEST: process.env.TEST
      }}

```
The variables work, and when I change the .env files content i get this message

`.env updated. Restarting nuxt...`

Nuxt restarts, rebuilds but the variable inside $config.TEST does not get updated.

**Comment by ExEr7um** [comment]
Yeah, same here.

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/15040.
