### ISSUE TITLE
Empty error on 3.2.2 after upgrade

### ISSUE THREAD

**Issue by ziadsarour** [nuxt/nuxt#19246]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v19.2.0`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.3`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `ssr`, `build`, `typescript`, `modules`, `content`, `css`, `sourcemap`, `vite`, `nitro`, `app`, `image`, `pwa`, `runtimeConfig`
- Runtime Modules:  `@nuxt/content@2.2.2`, `@nuxt/image-edge@1.0.0-27919678.2f5b64b`, `@kevinmarrec/nuxt-pwa@0.14.0`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-cdxtzt?file=package.json

### Describe the bug

It was working well before I've upgraded to Nuxt 3.2.2 with ```npx nuxi upgrade``` and fixed my versions packages by removing the ```^``` before each package version.
The problem is that I've no error message, I've tried to set ```debug: true``` in nuxt.config.ts but it doesn't show more information about the error.

<img width="298" alt="Capture d’écran 2023-02-23 à 17 26 59" src="https://user-images.githubusercontent.com/8212468/220972672-4bd9dd71-2afb-467c-afe4-939475252c22.png">

Everything seems to work correctly despite the error.

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/19145.
