### ISSUE TITLE
Composables function undefined

### ISSUE THREAD

**Issue by RijaCloud** [nuxt/nuxt#19257]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.2`
- Package Manager:  `npm@8.19.3`
- Builder:          `vite`
- User Config:      `app`, `build`, `modules`, `proxy`, `css`, `vite`, `i18n`, `runtimeConfig`, `plugins`, `components`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.9`, `nuxt-proxy@0.3.12`
- Build Modules:    `-`
------------------------------

### Reproduction

I created this repo to reproduce my code behavior : https://stackblitz.com/edit/setup-composables?file=app.vue,composables%2FuseSecondStore.ts

But I couldn't reproduce the error. In fact sometimes my composables are not accessible TypeError: XXXStore is not a function.

They are called in the setup function of each components. 

### Describe the bug

I am stuck with this random error for weeks now and I trully don't understant why my code does this. 

````javascript
setup() { 
 const nuxt = useNuxApp() // this is undefined sometimes
 // so goes for the other composables
}
````

why ?

**Comment by danielroe** [comment]
cc: @antfu

**Comment by antfu** [comment]
Thanks for reporting. However, your reproduction seems to work fine - I think we are not able to help without being able to identify the root cause. I suggest you try harder to see what's going wrong or how they differ from the reproduction you make. Let us know if you are able to stability reproduce it in Stackblitz. Thanks.

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/18897.
