### ISSUE TITLE
No way to set sourcemap.client = hidden

### ISSUE THREAD

**Issue by VladStepanov** [nuxt/nuxt#19253]
### Environment

No need

### Reproduction

No need

### Describe the bug

`vite` allows to set sourcemap to `boolean | 'inline' | 'hidden'` https://vitejs.dev/config/build-options.html#build-sourcemap
But in `nuxt.config.ts` it is possible to set only to boolean. 
It would be great to implement at least `'hidden'`.
For webpack can be used `hidden-source-map` https://webpack.js.org/configuration/devtool/#production

**Comment by danielroe** [comment]
This should be possible to handle by manually setting `vite.sourcemap` in your Nuxt config, which we will respect. We might possibly also support a 'hidden' option for `sourcemap.client`. (But likely not for `server` unless we update nitro too.)

**Comment by pi0** [comment]
LGTM to support hidden in nitro too (however sourcemap strategy for app/client can always be different from server. they live in different contexts so should be fine either way)

**Comment by alex-key** [comment]
Waiting for the next Nitro release, where related fix should be included
