### ISSUE TITLE
Simple page hydration problem

### ISSUE THREAD

**Issue by niddu85** [nuxt/nuxt#19258]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.14.1`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@9.3.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-ptvy33?file=layout/default.vue

### Describe the bug

I'm trying to print the page title in every page in a div inside the default layout
The title is obviously set in the page during the setup
What happens is on client the title is not rendered leading in a "Hydration text content mismatch"

### Logs

```shell-script
[Vue warn]: Hydration text content mismatch in <h1>:
- Client: 
- Server: Index Title 
  at <Default > 
  at <LayoutLoader key="default" name="default" hasTransition=false > 
  at <FragmentWrapper > 
  at <NuxtLayout> 
  at <App key=2 > 
  at <NuxtRoot>
```

**Comment by manniL** [comment]
This is expected. When the content is rendered on the server-side, it will render from top to bottom (App -> Layouts -> Pages -> components in the pages -> children, ...)

If you now change a value in a `page` component which should have an effect on the `layout` component, it can't reflect the change because the layout is already rendered.

The value will be transmitted "as changed" to the client though and the client assumes the content would be also part of the server response, which it isn't.

Thus, it will cause a hydration error.

**Comment by niddu85** [comment]
I partially agree with you. I understood what you mean, but why the head section is correctly rendered during SSR?

<Head>
      <Title>{{ titleValue }}</Title>
</Head>

after SSR is

<head>
<title>Index Title</title>
</head>

if SSR follows your flow, the head section should be rendered way before the body.
Maybe it follows a different flow?

**Comment by niddu85** [comment]
All right! Thanks for the explanation

**Comment by blowsie** [comment]
I ran into a similar issue and created a good reproduction,
https://stackblitz.com/edit/github-8fmev3?file=pages%2Findex.vue

You can work around this by using middleware's, but it creates a lot of extra code and handling if you were to be fetching data to populate components used by your layout.

**Comment by blowsie** [comment]
My assumption here is that this SSR strategy would also break / not resolve vue's provide/inject pattern

**Comment by bitbytebit1** [comment]
I feel like there should be some sort of escape hatch here as it seems like quite a common issue to run into. One idea would be to have a function similar to useHead that allows passing miscellaneous data from the page to the layout. This wouldn't need to be reactive necessarily. I do feel like definePageMeta is a prime candidate for this.

@blowsie nice job coming up with a workaround, really creative. I wonder if this can be wrapped up into a module that would provide a composable called defineLayoutData. I have a swing at this when I find time. Not sure if I can call definePageMeta from inside a composable but I guess I'll find out soon enough

**Comment by bitbytebit1** [comment]
This composable allows you to pass data from the page component to the layout component via definePageMeta and middleware. 
``` ts
export default function (key: string, value: any) {
  definePageMeta({
    middleware () {
      useState(key, () => value)
    },
  })
}
```
