### ISSUE TITLE
Ambiguous Indirect Export error when using lodash in nuxt layer

### ISSUE THREAD

**Issue by chrisfoss1** [nuxt/nuxt#19267]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.19.0`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `2.1.2`
- Package Manager:  `npm@9.2.0`
- Builder:          `vite`
- User Config:      `ssr`, `srcDir`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/chrisfoss1/nuxt-ambiguous-indirect-export

### Describe the bug

If you extend the provided project in a consuming application using a relative path, everything works fine.
However, if you push it up as an npm package and extend it that way, you get the following error when navigating to the root index.vue page:
```
SyntaxError: ambiguous indirect export: cloneDeep
```

### Additional context

This issue along with https://github.com/nuxt/nuxt/issues/19117 makes it very hard to use a provider other than one of the already supported providers.

**Comment by chrisfoss1** [comment]
I discovered I can make it work if I use 'lodash-es' instead of lodash, the difference being exporting an ES module instead of a UMD.

I'm not sure where that leaves this issue in terms of being a real bug, known limitation, or just a configuration issue I missed somewhere, but it has a perfectly fine workaround for me so I will leave it up to you to decide if it needs closed.

**Comment by mao-shonen** [comment]
https://nuxt.com/docs/guide/concepts/esm
```js
export default defineNuxtConfig({
  build: {
    transpile: ['lodash']
  }
})
```

**Comment by chrisfoss1** [comment]
That makes sense, thank you!
