### ISSUE TITLE
incorrect escaping of text for useHead

### ISSUE THREAD

**Issue by xiongsongsong** [nuxt/nuxt#19262]
### Environment

incorrect escaping of text for useHead

### Reproduction

https://stackblitz.com/edit/github-wiicqd?file=app.vue

### Describe the bug

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/342509/221172210-cec53983-5636-4bec-8d54-07a0e009d01e.png">

**Comment by danielroe** [comment]
cc: @harlan-zw

**Comment by harlan-zw** [comment]
> cc: @harlan-zw

This is technically valid in terms of SEO and the rendered page title. v1.1.0 changed the encoding to be less strict, see https://stackblitz.com/edit/github-wiicqd?file=package-lock.json

If anyone is stuck on this, clear your lock file & re-install.

Going to close

**Comment by slow-sheep** [comment]
hello, i want know this issueHello, I want to know if this problem has been resolved? How to solve it? After reading the official link, it seems that there is no solution. how to do?

**Comment by slow-sheep** [comment]
Hello, I want to know if this problem has been resolved? How to solve it? After reading the official link, it seems that there is no solution.

**Comment by slow-sheep** [comment]
@xiongsongsong  大哥，你的这个问题解决了吗？

**Comment by harlan-zw** [comment]
Please provide a reproduction and new issue if you have problems :pray:
