### ISSUE TITLE
DefineExpose not working for page components. Transition property causing issues with console log

### ISSUE THREAD

**Issue by JasonGotGithub** [nuxt/nuxt#19268]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.14.1`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `npm@9.3.1`
- Builder:          `vite`
- User Config:     `app`, `modules`, `runtimeConfig`,`vite`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Page Transition with console.log in route navigation guard causing an error
https://stackblitz.com/edit/github-wrkvqn

Page Transition with defineExpose and setup functions
https://stackblitz.com/edit/github-ams2ou

### Describe the bug

The transitions property in the app.vue component causes an error when using a console log within a navigation guard. For example, within onEnter. It seems that it's also affected when using the names of navigation guards within the console log string

There seems to be an issue with the defineExpose function when using it on a page component instead of a “regular” component. On a regular component it works fine, but for a page component that’s being accessed in app.vue in the transitions property via a ref it fails.  I’ve gone back and forth with @daniele in direct messages to investigate the issue and find a solution for this, but this has been unsuccessful. Some of the things that were tried are: disabling the layout transitions, checking root nodes.

**Comment by huang-julien** [comment]
Hi :wave: that's because `<NuxtPage>` is a component wrapper (and there's 1 or 2 more components before your page component). So `defineExpose()` in your page component won't expose anything to `App.vue` but to the `<RouterView>`. I'll see if something can be done for this
