### ISSUE TITLE
`.nuxtrc` is not interpreted in a monorepo context

### ISSUE THREAD

**Issue by nicolaspayot** [nuxt/nuxt#19266]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.3`
- Package Manager:  `pnpm@7.13.6`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-hqairf?file=README.md

### Describe the bug

Hello 👋 

**In the context of a monorepo, it looks like `.nuxtrc` files are not interpreted.**

Here, in the reproduction repository, we have a simple monorepo with pnpm workspaces. There are 2 nuxt modules and each of them contains a `.nuxtrc` file. Both `.nuxtrc` files contain these lines: 
```
imports.autoImport=false
typescript.includeWorkspace=true
``` 
To my understanding, the 2nd line means that we want to include what's outside of the `playground` directory (basically the `src/` directory), inside the `include` array of the generated `playground/.nuxt/tsconfig.json` file.

Thus, the `include` array should contain this:
```json
"include": [
    "./nuxt.d.ts",
    "../**/*",
    "../../**/*"
],
```

However, as you can see when running `pnpm --filter="*" dev:prepare`, the `include` array only contains this:
```json
"include": [
    "./nuxt.d.ts",
    "../**/*"
],
```

The `.nuxtrc` file is only interpreted when it's at the root of the monorepo, but then, the `include` array is wrong: 
```json
"include": [
    "./nuxt.d.ts",
    "../**/*",
    "../../../**/*"
],
```

**Comment by victorgarciaesgi** [comment]
Having this problem too with a pnpm monorepo!

**Comment by danielroe** [comment]
The `.nuxtrc` file is read from the Nuxt project (ie. the playground) or the global context, rather than any other directories in a monorepo.

You can see this forked repo: https://stackblitz.com/edit/github-hqairf-eabvob.

We might consider some other options, but is there a reason you want to read `.nuxtrc` files from other directories?

**Comment by pi0** [comment]
@danielroe when ready, feel free to move this issue directly to c12. if there is enough merits, (and we think of safe locations to pick), I am 💯 to support 3 level (home, workspace, root)

**Comment by danielroe** [comment]
I think we see the merits but I'm worried about the effect this would have on module development: a root level `.nuxtrc` file meant to apply only to the module would also then override the module playground configuration.

I think as long as it's understood that this is how the configuration is inherited, then this is fine. It's not a particular monorepo limitation.

**Comment by nicolaspayot** [comment]
Thank you for getting back on this @danielroe 🙌 

I actually don't clearly remember why I was trying to use the `.nuxtrc` file from outside of the nuxt project. Using it from the playground is fine 👍
