### ISSUE TITLE
Nuxt pa

### ISSUE THREAD

**Issue by kriskw1999** [nuxt/nuxt#19270]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

The way to reproduce it is written in this [CODE EXAMPLE](https://stackblitz.com/edit/github-8f29jq?file=pages%2Ftest.vue,app.vue,pages%2Ftest%2Fchild.vue,pages%2Ftest2.vue,pages%2Findex.vue).

Take a look inside the homepage there is a detailed description of how to reproduce the bug.

### Describe the bug

I have 2 pages. The first one has a NuxtPage inside containing some content. The second one has an async setup that waits for 5s. When I go from the first page to the second, during the 5s of transition I see only the first page without the inner NuxtPage that disappears. In Nuxt 2 this was working correctly but in Nuxt 3 is not working anymore.

In Nuxt 2 I was using asyncData for example and until the page was not ready I was seeing the previous page without any changes.

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/13814
>
