### ISSUE TITLE
Provide functions from server to client

### ISSUE THREAD

**Issue by ElYaiko** [nuxt/nuxt#19284]
### Describe the feature

Related #18833

Sometimes is necessary passing specific functions to client-side from server-side, for example you want to only load specific package when going to a route to not overload the client with packages in other requests, this could be done using `nuxtApp.provide` or via `nuxtApp.payload` which in the moment don't lets passing functions.

Thanks!.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by VladStepanov** [comment]
You can load that package by dynamic import i.e `() => import('foo')` https://vitejs.dev/guide/features.html#async-chunk-loading-optimization
I could give you more related answer if you provide your case

**Comment by danielroe** [comment]
We may have support coming soon for custom serialisable types (https://github.com/nuxt/nuxt/pull/19205) but in general I think this is very doable at the moment by pairing a `.client.ts` and `.server.ts`. However, it's difficult to say without more information. What kind of functions are you hoping to provide?

Would you provide some more information about your use case and suggested enhancement? 🙏

**Comment by ElYaiko** [comment]
> We may have support coming soon for custom serialisable types (#19205) but in general I think this is very doable at the moment by pairing a `.client.ts` and `.server.ts`. However, it's difficult to say without more information. What kind of functions are you hoping to provide?
> 
> Would you provide some more information about your use case and suggested enhancement? 🙏

I'm trying to do a simple `i18n` implementation, where I define the translations as objects and some translations can have simple functions like ex:

``
{
elements: n => `This text has ${n} element(s)`
}``

Loading all the translation files/objects to the client can be something overloading so that's why I'm trying to load this simple object from a `plugin.server.ts` depending the client lang to latter be used in the client like: `$i18n.elements(2)...`

**Comment by danielroe** [comment]
This is now possible with https://github.com/nuxt/nuxt/pull/19205, which is now enabled by default (https://github.com/nuxt/nuxt/pull/20770).
