### ISSUE TITLE
setPageLayout generates unhandledRejection when used with async await in middleware or plugin

### ISSUE THREAD

**Issue by pitambar-jha** [nuxt/nuxt#19286]
Hello, I am new to nuxt 3. Pardon me if this is not an actual bug and might be me doing something wrong..
As per the [documentation](https://nuxt.com/docs/api/utils/set-page-layout#setpagelayout) and the conversation [here](https://github.com/nuxt/nuxt/issues/15176). The right way to call setPageLayout is to do it inside either a middleware or a plugin. I tried doing the same inside a plugin  but it throws an unhandledRejection in nitro when i do it inside an async block. here is my code:

```
export default defineNuxtPlugin((nuxtApp) => {
let sd = ref('')

async function fetchSiteDetails() {
    const response = await fetch(<server_endpoint>);
    const siteDetail = await response.json();
    sd.value = siteDetail;
    }

(async function () {
    // wait to http request to finish
    await fetchSiteDetails();
    if (sd.value.....) {
       setPageLayout('custom')
   }
})();
});
```
I want to set the page layout based on the theme set by the user, hence setting it inside async block after awaiting the network call. This is generating an exception:
```
[nitro] [dev] [unhandledRejection] Error: nuxt instance unavailable
```
I tried doing the same inside a __middleware__ , that gave the same error as above. 

if i use __setPageLayout__ outside async block then it works fine but then it can't be used to change the layout dynamically. 
Am i missing something or is it a bug ?

Thanks

**Comment by Baroshem** [comment]
Hey,

I looked at the docs and I believe that this composable's intention is to work like this:

1. You have default.vue layout
2. User navigates to /account
3. You add a route middleware (as shown here https://nuxt.com/docs/api/utils/set-page-layout#setpagelayout) where you are setting a different layout
4. Different layout is rendered.

So, I would guess that you cannot put this composable inside an async block like this.

However, have you maybe tried to refactor your code to something like this and see if it works?

```ts
export default defineNuxtPlugin(async (nuxtApp) => {
  const siteDetail = await fetch(<server_endpoint>).json();

  if (siteDetail) {
    setPageLayout('custom')
  }
});
```

**Comment by danielroe** [comment]
@Baroshem is right here 👍 There's some more information at https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables that explains a little bit about utilities that need the Nuxt context and where they may be used.
