### ISSUE TITLE
Plugin intelisense is not working when using `useNuxtApp`

### ISSUE THREAD

**Issue by brpaz** [nuxt/nuxt#19281]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.3`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `ssr`, `build`, `typescript`, `modules`, `nitro`, `app`, `css`, `runtimeConfig`, `image`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.4.1`, `@nuxt/image-edge@1.0.0-27954023.4cee565`, `@pinia/nuxt@0.4.7`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-y5a3ze?file=app.vue

### Describe the bug

Hello. I have created a plugin in the `plugins` folder to setup a trpc client.

But the autocomplete is not working on VSCode, when I try to use the plugin, like:

``` ts
const { $trpcClient } = useNuxtApp();
$trpcClient. (does nothing)
```

```ts
# plugins/trpc-client.ts
import { defineNuxtPlugin } from 'nuxt/app';
import { loggerLink } from '@trpc/client';
import { createTRPCNuxtClient, httpBatchLink } from 'trpc-nuxt/client';
import type { AppRouter } from '~/server/trpc/routers';

export default defineNuxtPlugin(() => {
  /**
   * createTRPCNuxtClient adds a `useQuery` composable
   * built on top of `useAsyncData`.
   */
  const trpcClient = createTRPCNuxtClient<AppRouter>({
    links: [
      loggerLink({
        enabled: (opts) =>
          process.env.NODE_ENV === 'development' ||
          (opts.direction === 'down' && opts.result instanceof Error),
      }),
      httpBatchLink({
        url: '/api/trpc',
      }),
    ],
  });

  return {
    provide: {
      trpcClient,
    },
  };
});
```

set up

**Comment by manniL** [comment]
Can't reproduce locally with the example given above 
![grafik](https://user-images.githubusercontent.com/640208/221604662-2e8ce347-38be-4ab1-aec2-860775022c9a.png)

Don't forget to let the dev server (or `nuxi prepare`) run to update Nuxt's dynamically generated types


PS: Vue files in StackBlitz do not have TS support at all which is a StackBlitz limitation

**Comment by gustawdaniel** [comment]
I have the same problem. This issue should not be closed.

Steps to reproduce:

```
import { defineNuxtPlugin } from 'nuxt/app';
import { loggerLink } from '@trpc/client';
import { createTRPCNuxtClient, httpBatchLink } from 'trpc-nuxt/client';
// import { createTRPCUntypedClient, httpBatchLink } from '@trpc/client';
import type { AppRouter } from '../../trpc';

export default defineNuxtPlugin(() => {
  const trpcClient = createTRPCNuxtClient<AppRouter>({
    links: [
      loggerLink({
        enabled: (opts) =>
          process.env.NODE_ENV === 'development' ||
          (opts.direction === 'down' && opts.result instanceof Error),
      }),
      httpBatchLink({
        url: '/api/trpc',
      }),
    ],
  });

// THERE Autocompletion works

  return {
    provide: {
      trpcClient,
    },
  };
});
```

but in other file after

```
const { $trpcClient } = useNuxtApp();

// autocompletion does not works
```

I mean I can write `$trpcClient.translate.query` and there is autocompletion but when I writing

```
$trpcClient.translate.query({
   // there autocomplete does not works
})
```
