### ISSUE TITLE
Middleware causes redirect loop on Vercel

### ISSUE THREAD

**Issue by andresmeidla** [nuxt/nuxt#19297]
### Discussed in https://github.com/nuxt/nuxt/discussions/19193

<div type='discussions-op-text'>

<sup>Originally posted by **andresmeidla** February 21, 2023</sup>
Got a weird problem that I can reproduce only with a vercel serverless function deployment and only when query parameters are used for the sendRedirect location.
I'm not a 100% sure whether it is a Nuxt, nitro or Vercel issue but got to start from somewhere.

I have a barebones `npx nuxi init` project to which I added 2 pages - index.vue and login.vue with only some static text.

I have defined a server middleware which should:
* allow /login path thereby showing the login page
* otherwise redirect to /login?initial={initialPath} with HTTP 307 (note the query parameter and HTTP code)

The code:
```
export default defineEventHandler((event) => {
  const parsedUrl = new URL(event.node.req.url ?? '/', 'http://localhost');
  const pathname = parsedUrl.pathname;
  if (pathname.startsWith('/login')) {
    console.log(pathname, 'Allow');
    return;
  }
  console.log(pathname, 'Redirecting to login');
  // redirecting
  return sendRedirect(event, `/login?initial=${event.node.req.url}`, 307);
});
```

Everything works great when I run it locallly:
* `/login` just shows me the `/login` page,
* /xxxxxxxxxxxx redirects to `/login?initial=/xxxxxxxxxxxx`,
* `/` redirects to `/login?initial=/`

But when I deploy it to Vercel, however, then:
* `/login` shows `/login` page,
* `/xxxxxxxxxxxx` redirects to `/login?initial=/xxxxxxxxxxxx`,
* but `/` goes into a redirection loop:
`/` redirect 307 to `/login?initial=/`,
`/login?initial=/` redirect 302 to `/login?initial=/`,
`/login?initial=/` redirect 302 to `/login?initial=/`
... and so on.

One would think that we might be causing the loop with the sendRedirect.
Maybe because pathname for some reason is not /login, but something else, but:
Vercel function log shows:
```
[GET] /
/ Redirecting to login

[GET] /login?initial=/
/login Allow

[GET] /login?initial=/
/login Allow

[GET] /login?initial=/
/login Allow
```
So it seems to me like the middleware is working correctly by allowing /login path.
The thing to note here is that only the first redirection is HTTP 307, the other ones are 302 and we dont have any other redirects in our code.
Also - the initial URL is / for all of the requests.
I would expect it to be /login after the first redirects.

The "workaround" for this, is to not use query parameters with sendRedirect like so:
```
return sendRedirect(event, '/login', 307);
```
...then everyting works as expected.

Im sure I'm doing something wrong but cannot figure out what it is so any help is much appreciated!

The repro code is available at: https://github.com/andresmeidla/nuxt-redirect-loop
The deployment can be tested at: https://nuxt-redirect-loop.vercel.app/
The case with the "workaround" can be tested at: https://nuxt-redirect-loop-git-withoutqueryparams-andresmeidla.vercel.app/</div>

**Comment by smaeda-ks** [comment]
Have you checked https://github.com/nuxt/nuxt/issues/14316 ? might be the same reason

**Comment by danielroe** [comment]
This is now resolved with the latest version of Nuxt. I've tested with v3.1.2 (with bug) and confirmed bug was missing on v3.4.0, once deployed to Vercel.

Let me know if not and I'll happily reopen.

**Comment by andresmeidla** [comment]
cannot reproduce with 3.4.0 🎉
Thank You!
cheers!
