### ISSUE TITLE
in fact it's good, it's the server side that I want to recover so I passed `ssr: true`

### ISSUE THREAD

**Issue by krxdow** [nuxt/nuxt#19298]
in fact it's good, it's the server side that I want to recover so I passed `ssr: true`
and it works
thank  you

_Originally posted by @krxdow in https://github.com/nuxt/nuxt/discussions/19276#discussioncomment-5117262_

**Comment by Baroshem** [comment]
Hey, 

Glad that it works after the discussion you participated in. I am closing the issue then :)
