### ISSUE TITLE
`defineCachedEventHandler` headers

### ISSUE THREAD

**Issue by ElYaiko** [nuxt/nuxt#19295]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-yvyydz?file=app.vue

### Describe the bug

When using `defineCachedEventHandler` in server api don't returns the request headers, just `{}`.

**Comment by Baroshem** [comment]
@pi0 I believe this can be an upstream issue with nitro.

**Comment by pi0** [comment]
@Baroshem Sure. Can you please upstream one?

**Comment by danielroe** [comment]
@Baroshem He means, would you create one in https://github.com/unjs/nitro? As far as I know, GitHub does not allow issues to be transferred across organisations.

**Comment by Baroshem** [comment]
@danielroe Ahh I see.

Then for the future tasks I will be able now to upstream them to nitro/h3 and more. Thanks for clarification!

**Comment by pi0** [comment]
Sorry i initially misundrestood PR description.

This is an expected (actually feature! [src](https://github.com/unjs/nitro/blob/d2b34e02131de9435bc01443e8a5a00ee2cc434f/src/runtime/cache.ts#L204)) of Nitro. By removing incoming headers, we can make sure cache entries are not depending and varying based on incoming request. 

We might improve docs for this.

**Comment by danielroe** [comment]
I think probably the documentation PR would need to be upstream to https://github.com/unjs/nitro, right? I think we can close this issue.

**Comment by pi0** [comment]
Sure! (checking [server dir](https://nuxt.com/docs/guide/directory-structure/server) we are not documenting anything about caching)
