### ISSUE TITLE
Cannot find `client.manifest.mjs`

### ISSUE THREAD

**Issue by phpmac** [nuxt/nuxt#19296]
### Environment

I get an error when I run the package

<img width="1552" alt="截屏2023-02-27 06 49 39" src="https://user-images.githubusercontent.com/86544347/221442214-29beb35c-51c3-4edd-90c8-e71cb6f0ffe3.png">

### Reproduction

I get an error when I run the package

<img width="1552" alt="截屏2023-02-27 06 49 39" src="https://user-images.githubusercontent.com/86544347/221442214-29beb35c-51c3-4edd-90c8-e71cb6f0ffe3.png">

### Describe the bug

I get an error when I run the package

<img width="1552" alt="截屏2023-02-27 06 49 39" src="https://user-images.githubusercontent.com/86544347/221442214-29beb35c-51c3-4edd-90c8-e71cb6f0ffe3.png">

**Comment by theguriev** [comment]
I got the same after the update for some reason. :(

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by danielroe** [comment]
Looking at your screenshot, I suspect this is caused by building your site while you are also running the dev server.

We can track support for this in https://github.com/nuxt/nuxt/issues/14607.
