### ISSUE TITLE
useFetch ssr not working when use same function in page setup and click event on an element after upgrade nuxt to 3.2.2 from 3.0.0

### ISSUE THREAD

**Issue by Alireza1996Sh** [nuxt/nuxt#19292]
### Environment

Nuxt project info:

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`, `buildModules`, `pwa`, `css`, `purgecss`, `vite`, `nitro`, `runtimeConfig`, `experimental`, `app`, `sourcemap`
- Runtime Modules:  `@vueuse/nuxt@9.13.0`, `@pinia/nuxt@0.4.7`
- Build Modules:    `@nuxtjs/eslint-module@3.1.0`, `nuxt-purgecss@2.0.0`
------------------------------

### Reproduction

I have a home page and I want to call two fetch requests and pass the results to a component.

pages/Index.vue
```vue
<template>
  <LazyHome
    :categories-request="categoriesRequest"
    :locations-request="locationsRequest"
  />
</template>

<script setup>
import {fetchCategories, fetchLocations} from '~/services/home';

const categoriesRequest = ref({pending: true, error: null, data: null});
const locationsRequest = ref({pending: true, error: null, data: null});

const res = await Promise.all([fetchCategories(), fetchLocations({filter: 0})]);

if (res[0].error.value || res[1].error.value) {
  showError(res[0].error.value || res[1].error.value);
} else {
  categoriesRequest.value = res[0];
  locationsRequest.value = res[1];
}
</script>
```

now let's see what are `fetchCategories` and `fetchLocations` functions

services/home.js
```js
import {useEnv} from '~/utils/use-env';

export const fetchCategories = () => {
  const mainApi = useEnv('mainApi');

  return useFetch(
    `${mainApi}/homepage/categories`,
    {
      method: 'POST',
      server: true,
    }
  );
};

export const fetchLocations = (payload = {}) => {
  const mainApi = useEnv('mainApi');

  return useFetch(
    `${mainApi}/homepage/locations`,
    {
      method: 'POST',
      body: payload,
      server: true,
    }
  );
};
```

and this is the component we used in home page:

components/home/Index.vue
```vue
<template>
  <div class="categories-wrapper">
    <div
      v-for="category in categories"
      :key="category.key"
      @click="setActiveCategory(category.id)"
    >
      {{ category.title }}
    </div>
  </div>
</template>

<script setup>
import {fetchLocations} from '~/services/home';

const props = defineProps({
  categoriesRequest: {type: Object, required: true},
  locationsRequest: {type: Object, required: true},
});

const categories = computed(() => {
  const items = [];

  if (props.categoriesRequest.data) {
    items.push(...props.categoriesRequest.data.items);
  }

  return [
    {
      id: 0,
      key: 'ALL',
      title: 'همه تورها',
    },
    ...items,
  ];
});

const currentLocationsRequest = ref(props.locationsRequest);

const setActiveCategory = async (categoryId) => {
  currentLocationsRequest.value = await fetchLocations({filter: categoryId});
};
</script>
```

### Describe the bug

we are expecting `fetchCategories` and `fetchLocations` have been called in server side once and nothing else happens in client side.
and when we click on each category element, `fetchLocations` should be called.

but this is not the behavior we actually see.
we see both function just have been called in client side.
and this happens after upgrading nuxt from `3.0.0` to `3.2.2`.
before that it worked fine.
and i have to mention that this behavior happens only in production.
if i change `setActiveCategory` to:
```js
const setActiveCategory = async (categoryId) => {
  console.log(categoryId);
};
```
it works fine again

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏 While I can see your code above, I can't run it, nor do I see all of the code necessary to reproduce the issue (for example, useEnv).

One comment - give you say the issue only happens with `setActiveCategory` defined as it is, it might possibly be a vue bug. What if you change the line in the template to:

```diff
- @click="setActiveCategory(category.id)"
+ @click="() => setActiveCategory(category.id)"
```

Ideally you should not use `useFetch` to _perform_ fetches on demand on the client side. For that, you should use `$fetch` directly. It is only meant to be called within a setup function.  Additionally, using `fetchLocations` the way you are, you probably want to give it a key that is based on the location.

Finally, the way you are updating the `locationsRequest` and `categoriesRequest` is a bit confusing to me. Is there a reason you are doing that?

**Comment by Alireza1996Sh** [comment]
I tried your suggestion to use `@click="() => setActiveCategory(category.id)"` and nothing changes.
But I have good news. I thought "hey, let's reproduce the bug in a fresh start"

So here is all files:

nuxt.config.ts
```js
export default defineNuxtConfig({
  runtimeConfig: {
    mainApi: process.env.MAIN_API_SERVER,

    public: {
      mainApi: process.env.MAIN_API_CLIENT,
    },
  },
  nitro: {
    compressPublicAssets: true,
  },
  experimental: {
    writeEarlyHints: false,
  },
  app: {
    pageTransition: false,
    layoutTransition: false,
  },
  sourcemap: {
    client: true,
  },
})
```

.env
```env
MAIN_API_CLIENT="http://api.mos.test"
MAIN_API_SERVER="http://api.mos.test"
HOST="172.20.20.52"
NUXT_HOST="172.20.20.52"
PORT="3001"
NUXT_PORT="3001"
```

utils/use-env.js
```js
export const useEnv = (name) => {
  const config = useRuntimeConfig();

  return config[name] ?? config.public[name] ?? null;
};
```

services/home.js
```js
import { useEnv } from '~/utils/use-env';

export const fetchCategories = () => {
  const mainApi = useEnv('mainApi');

  return useFetch(
    `${mainApi}/homepage/categories`,
    {
      method: 'POST',
      server: true,
    }
  );
};

export const fetchLocations = (payload = {}) => {
  console.log('fetch Locations Ran.');

  const mainApi = useEnv('mainApi');

  return useFetch(
    `${mainApi}/homepage/locations`,
    {
      method: 'POST',
      body: payload,
      server: true,
    }
  );
};
```

app/router.options.js
```js

export default {
  routes: () => [
    {
      name: 'home.index',
      path: '/',
      component: () => import('~~/pages/home/Index.vue'),
      meta: {
        layout: 'home',
      },
    },
  ],
};
```

app.vue
```vue
<template>
  <NuxtLayout>
    <NuxtPage />
  </NuxtLayout>
</template>
```

layouts/Home.vue
```vue
<template>
  <div>
    <div>header</div>

    <main>
      <slot />
    </main>
    
    <div>footer</div>
  </div>
</template>
```

pages/home/Index.vue
```vue
<template>
  <LazyHome
    :categories-request="categoriesRequest"
    :locations-request="locationsRequest"
  />
</template>

<script setup>
import {fetchCategories, fetchLocations} from '~/services/home';

const categoriesRequest = ref({pending: true, error: null, data: null});
const locationsRequest = ref({pending: true, error: null, data: null});

const res = await Promise.all([fetchCategories(), fetchLocations({filter: 0})]);

if (res[0].error.value || res[1].error.value) {
  showError(res[0].error.value || res[1].error.value);
} else {
  categoriesRequest.value = res[0];
  locationsRequest.value = res[1];
}
</script>
```

components/home/Index.vue
```vue
<template>
  <HomeLocations
    :categories-request="categoriesRequest"
    :locations-request="locationsRequest"
  />

  <div>
    best locations ever
  </div>
</template>

<script setup>
defineProps({
  categoriesRequest: {type: Object, required: true},
  locationsRequest: {type: Object, required: true},
});
</script>
```

components/home/locations/Index.vue
```vue
<template>
  <BContainer>
    <div class="categories-wrapper">
      <div
        v-for="category in categories"
        :key="category.key"
        @click="setActiveCategory(category.id)"
      >
        {{ category.title }}
      </div>
    </div>
  </BContainer>
</template>

<script setup>
import BContainer from '~/components/global/b/Container.vue';
import {fetchLocations} from '~/services/home';

const props = defineProps({
  categoriesRequest: {type: Object, required: true},
  locationsRequest: {type: Object, required: true},
});

const categories = computed(() => {
  const items = [];

  if (props.categoriesRequest.data) {
    items.push(...props.categoriesRequest.data.items);
  }

  return [
    {
      id: 0,
      key: 'ALL',
      title: 'همه تورها',
    },
    ...items,
  ];
});

const currentLocationsRequest = ref(props.locationsRequest);

const setActiveCategory = async (categoryId) => {
  currentLocationsRequest.value = await fetchLocations({filter: categoryId});
};
</script>
```

components/global/b/Container.vue
```vue
<template>
  <div :class="containerClass">
    <slot />
  </div>
</template>

<script setup>
const props = defineProps({
  fluid: {
    type: [Boolean, String],
    default: () => false,
    validator: (v) => {
      if (v) {
        return [
          true,
          false,
          'sm',
          'md',
          'lg',
          'xl',
          'xxl',
        ].includes(v);
      }
      return true;
    },
  },
});

const containerClass = computed(() => {
  if (!props.fluid) {
    return 'container';
  }
  if (typeof props.fluid === 'boolean') {
    return 'container-fluid';
  }
  return `container-${props.fluid}`;
});
</script>
```

these files are all you need to reproduce this bug.

I also did some tests and changes to see when bug is disappeared:
- if you use `nuxt@3.0.0` the bug will be disappeared.
- if you use file based routing & don't use `router.options.js`, the bug will be disappeared. (but I don't want to do that at all)
- if you replace `<BContainer>...</BContainer>` with a simple `<div>...</div>`, the bug will be disappeared. (I think this is the main hint. maybe something wrong is with `@click` inside of `slot` after 3.0.0 version. i don't know)
- if you comment `currentLocationsRequest.value = await fetchLocations({filter: categoryId});` inside `setActiveCategory` function. (and everybody knows this is not solution :)

**Comment by Alireza1996Sh** [comment]
Hi @danielroe is there any chance to find out what is really happening under the hood?

**Comment by danielroe** [comment]
I'm happy to look into this if you can provide a [minimal reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction).

**Comment by Alireza1996Sh** [comment]
https://stackblitz.com/edit/nuxt-issue-19292

**Comment by TheNaschkatze** [comment]
Help us, is blocking our production

**Comment by danielroe** [comment]
The issue here is not `useFetch` but rather with your dynamic import in `router.options.js`. Make this change and you should be fine:

```diff
- component: () => import('~/pages/home/Index.vue'),
+ component: () => import('~/pages/home/Index.vue').then(r => r.default),
```

**Comment by Alireza1996Sh** [comment]
it works fine now.
thank you
