### ISSUE TITLE
Props state is not synced to the client from SSR when changed in onBeforeMount hook

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [nuxt/nuxt#19314]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.3`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-9ukebr-cgwhes?file=pages/index.vue

### Describe the bug

When **onBeforeMount** hook is used to update reactive property it's not propagated properly to VDOM state, which results in the incorrect application of properties such as **css class**. What is strange though is that actual node text value is updated correctly. This behavior can be easily observed on the provided reproduction.

### Additional context

When **onMounted** hook is used though - the state is updated accordingly.

### AC

**Actual Result**: Props state is not synced to the client from SSR when onBeforeMount is used
**Expected Result**: Props state is synced to the client from SSR when onBeforeMount is used

**Comment by danielroe** [comment]
I think this is expected and is a Vue hydration behaviour. I would consider it a hydration mismatch - you should ensure that when the component mounts, it will match the rendered HTML.

If you don't think so, feel free to raise an upstream issue in https://github.com/vuejs/core.
