### ISSUE TITLE
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.

### ISSUE THREAD

**Issue by sunny-repo88** [nuxt/nuxt#19310]
### Environment

Nuxi 3.2.2                                                                                 
------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.14.1`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@9.3.1`
- Builder:          `vite`
- User Config:      `components`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Reproduce Link: https://stackblitz.com/edit/github-tznxrd

1. npx nuxi init demo
2. cd demo
3. npm install
4. mkdir -p components/layouts
5. edit nuxt.config.ts
    **nuxt.config.ts**
    ```
    export default defineNuxtConfig({
        components: [
            { path: '~/components/layouts', prefix: 'Special' },
            '~/components'
        ]
    })
    ```

6. create **header.vue** under components/layouts
    ```
    <template>
        <div>
            Header
        </div>
    </template>
    ```

7. import header.vue in **app.vue**
    ```
          <template>
            <div>
              <Header />
              <NuxtWelcome />
            </div>
          </template>
      
          <script>
          import Header from '~/components/layouts/header.vue';
          </script>
    ```

8. npm run dev

### Describe the bug

[Vue warn]: Failed to resolve component: Header
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.

**Comment by danielroe** [comment]
Your imported component isn't exposed to the template. You can either:

1. Use the auto imported component as `<SpecialHeader>`
2. Rename `<script>` to `<script setup>` (which auto-exposes import to the template)
3. add a setup function `export default defineComponent({ setup () { return { Header } } })` to expose it manually
