### ISSUE TITLE
How to make useFetch not block navigation transition after SSR rendering?

### ISSUE THREAD

**Issue by lmy1991** [nuxt/nuxt#19326]
```
<template>
  {{ bannerData }}
</template>
<script setup lang="ts">
const bannerData = ref<any>(null)
const { data }: any = await useFetch('/api/index/banner')
bannerData.value = data.value.data.banner
</script>
```

There is no problem with waiting for the useFetch request to finish when the page is first visited. However, when the page is switched, it will still wait for the useFetch to finish before navigating.

I would like to achieve the same effect as adding the rule ssr: false in the routeRules of nuxt.config.ts to not block navigation when switching pages. How can I do this?

I know that setting lazy:false in useFetch can solve this problem, but this requires writing the same business logic twice to be accomplished. Is there any way to achieve this through configuration?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by Baroshem** [comment]
I would say that using `useLazyFetch` -> https://nuxt.com/docs/api/composables/use-lazy-fetch#uselazyfetch is the recommended approach here.

I dont have any other ideas in mind.

**Comment by szulcus** [comment]
...or use `{ lazy: true }` in options

**Comment by s1mpLyy** [comment]
Same issue here, I'm using SSR and prerendering the home page after that the first client side useFetch or useLazyFetch both block the navigation.

***This happened on the first request only.
