### ISSUE TITLE
Nuxt 3 not working on iOS <= 12

### ISSUE THREAD

**Issue by JonathanDoelan** [nuxt/nuxt#19328]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.20.1`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.3`
- Package Manager:  `pnpm@7.28.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Created a [minimal reproduction on stackblitz](https://stackblitz.com/edit/github-6y4iab?file=app.vue), while the problem is, that stackblitz (and codesandbox) does not work on iOS (12). So I hope this is not a problem!

But basically all you need to do is installing Nuxt 3 and open the page with an iOS device on iOS 12 or below.

In the stackblitz example above, I’ve created this simple counter app, to demonstrate, that no interaction works (on iOS <=12):

```vue
<template>
  <div>
    <!-- <NuxtWelcome /> -->
    <h1>count: {{ count }}</h1>
    <button @click="count++">+</button>
  </div>
</template>

<script setup>
const count = ref(0);
</script>
```

But the same error occurs, when you stay with the default app.vue (`<NuxtWelcome />`).

### Describe the bug

First: I think this is the same bug as described [here](https://github.com/nuxt/nuxt/issues/12577), but somehow the issue was closed.
No, not vite: I’ve tested it, and it has nothing to do with [vite as builder](https://github.com/nuxt/nuxt/issues/12577#issuecomment-1397219367), because I’ve tested it also with [webpack as builder](https://github.com/nuxt/nuxt/issues/12577#issuecomment-1397219410) and you can verify this too by trying it with webpack. And if you have a look at can i use ([es6-module](https://caniuse.com/es6-module), [dynamic-import](https://caniuse.com/es6-module-dynamic-import), [import.meta](https://caniuse.com/mdn-javascript_operators_import_meta)), [vite is supported](https://vitejs.dev/guide/#browser-support) on iOS 12.

Here is a video of the app running on an iPad with iOS 12 (via browserstack.com):

---

https://user-images.githubusercontent.com/2291224/221809915-5077d637-f7e0-45b4-bbc6-e90d473373a9.mp4

---

As you can see, the problem is that an error is thrown, that stops the app from working (both vite and webpack):

```
SyntaxError: Unexpected token '?'       (program):1
promiseReactionJob @ (program):1
```

Safari on iOS 12 (from 2018/19) is still a relevant browser with `0.42%`, as you can see on [usage tables](https://caniuse.com/usage-table). So I hope we can fix this!

**Comment by ennioVisco** [comment]
To clarify, we are talking about `iPhone 5S`, `iPhone 6/6 Plus` and `iPod touch (6th generation)`, i.e. 2015 and older devices (or ones that didn't update).

It can make sense to precisely track the library/feature that is causing the failure, although it must be noted that we are talking about 8-years-ago internet, and it might not be worth changing them.

**Comment by JonathanDoelan** [comment]
> To clarify, we are talking about `iPhone 5S`, `iPhone 6/6 Plus` and `iPod touch (6th generation)`, i.e. 2015 and older devices (or ones that didn't update).
> 
> 
> 
> It can make sense to precisely track the library/feature that is causing the failure, although it must be noted that we are talking about 8-years-ago internet, and it might not be worth changing them.
> 
> 
> 
> P.s. Note also that Vue 3 requires ES2015, i.e. iOS 10.x+

I really do not know where you found this information, but it simply is **not true**. iOS 12 (as mentioned above) was released in September 2018 and of course, it is still relevant.

**Comment by ennioVisco** [comment]
> > To clarify, we are talking about `iPhone 5S`, `iPhone 6/6 Plus` and `iPod touch (6th generation)`, i.e. 2015 and older devices (or ones that didn't update).
> > It can make sense to precisely track the library/feature that is causing the failure, although it must be noted that we are talking about 8-years-ago internet, and it might not be worth changing them.
> > P.s. Note also that Vue 3 requires ES2015, i.e. iOS 10.x+
> 
> I really do not know where you found this information, but it simply is **not true**. iOS 12 (as mentioned above) was released in September 2018 and of course, it is still relevant.

I apologize if the message was received badly, I didn't want to say that it's not relevant in any way!
I was just clarifying the affected devices. It has been released in September 2018, but all the devices except the ones I mentioned (and the older ones) could be updated to iOS13, according to [Wikipedia](https://en.wikipedia.org/wiki/IOS_13#Supported_devices).

**Comment by manniL** [comment]
As noted in https://github.com/nuxt/nuxt/issues/12577#issuecomment-1397219391, please follow along the issues for the vite legacy plugin.

* https://github.com/nuxt/nuxt/issues/15464
* https://github.com/nuxt/nuxt/issues/14634

Consolidating there 👍

**Comment by JonathanDoelan** [comment]
@manniL Please read my issue once more, but carefully. It has nothing to do with vite and it has nothing todo with desktop safari. 

Please reopen!

**Comment by manniL** [comment]
> It has nothing todo with desktop safari

I never referred to Desktop safari here. But what you want is support for older browser versions (=legacy) that are not able to understand constructs like optional chaining or nullish coalescing.

> It has nothing to do with vite

Not "directly" but somewhere you have to set up the level of transpilation - usually in an extra config or via bundler 😋 

One more thing you can try is setting vite's build target to es2015 via:

```
export default defineNuxtConfig({
  vite: {
    build: {
      target: 'es2015'
    }
  }
})
```

**Comment by manniL** [comment]
Quickly ran the above mentioned config over a default nuxt setup and it should work fine 👍 
no `?.` in the file, except for `y=40+(n.sensitive?.25:0)` which is actually a ternary and won't throw issues.

**Comment by JonathanDoelan** [comment]
@manniL Thanks a lot for checking again! Wow, this is great.

I will use the following solution according to https://esbuild.github.io/api/#target and https://esbuild.github.io/content-types/#javascript

```js
    vite: {
        build: {
            target: ["esnext", "ios12"],
        },
    },
```

What do you mean by
> Be aware though: You might want to add 3rd party libraries to build.transpile to ensure they will be transpiled too.

?

**Comment by JonathanDoelan** [comment]
> Be aware though: You might want to add 3rd party libraries to build.transpile to ensure they will be transpiled too.

@manniL Oh, you mean, that it could be that 3rd party libs don’t support ios12, because they use modern syntax?

**Comment by manniL** [comment]
> > Be aware though: You might want to add 3rd party libraries to build.transpile to ensure they will be transpiled too.
> 
> @manniL Oh, you mean, that it could be that 3rd party libs don’t support ios12, because they use modern syntax?

I am not entirely sure but I think yes, this is a possible scenario.

**Comment by ckhatton** [comment]
Ar ok, unfortunately it is not possible to build for `es5` 😢 I guess I could drop Nuxt for a straight up Vue setup, and utilise `browserlist`.

```shell
[vite:esbuild-transpile] Transform failed with 9 errors:
_nuxt/app.config.!~{005}~.js:6:47: ERROR: Transforming default arguments to the configured target environment ("es5" + 2 overrides) is not supported yet
```
```shell
Transforming default arguments to the configured target environment ("es5" + 2 overrides) is not supported yet
4  |    return value !== null && typeof value === "object";
5  |  }
6  |  function _defu(baseObject, defaults, namespace = ".", merger) {
   |                                                 ^
7  |    if (!isObject(defaults)) {
8  |      return _defu(baseObject, {}, namespace, merger);

Transforming const to the configured target environment ("es5" + 2 overrides) is not supported yet
8  |      return _defu(baseObject, {}, namespace, merger);
9  |    }
10 |    const object = Object.assign({}, defaults);
   |    ^
11 |    for (const key in baseObject) {
12 |      if (key === "__proto__" || key === "constructor") {

Transforming const to the configured target environment ("es5" + 2 overrides) is not supported yet
9  |    }
10 |    const object = Object.assign({}, defaults);
11 |    for (const key in baseObject) {
   |         ^
12 |      if (key === "__proto__" || key === "constructor") {
13 |        continue;

Transforming const to the configured target environment ("es5" + 2 overrides) is not supported yet
13 |        continue;
14 |      }
15 |      const value = baseObject[key];
   |      ^
16 |      if (value === null || value === void 0) {
17 |        continue;

Transforming array spread to the configured target environment ("es5" + 2 overrides) is not supported yet
21 |      }
22 |      if (Array.isArray(value) && Array.isArray(object[key])) {
23 |        object[key] = [...value, ...object[key]];
   |                       ^
24 |      } else if (isObject(value) && isObject(object[key])) {
25 |        object[key] = _defu(

Transforming array spread to the configured target environment ("es5" + 2 overrides) is not supported yet
21 |      }
22 |      if (Array.isArray(value) && Array.isArray(object[key])) {
23 |        object[key] = [...value, ...object[key]];
   |                                 ^
24 |      } else if (isObject(value) && isObject(object[key])) {
25 |        object[key] = _defu(

Transforming rest arguments to the configured target environment ("es5" + 2 overrides) is not supported yet
36 |  }
37 |  function createDefu(merger) {
38 |    return (...arguments_) => (
   |            ^
39 |      // eslint-disable-next-line unicorn/no-array-reduce
40 |      arguments_.reduce((p, c) => _defu(p, c, "", merger), {})

Transforming const to the configured target environment ("es5" + 2 overrides) is not supported yet
40 |      arguments_.reduce((p, c) => _defu(p, c, "", merger), {})
41 |    );
42 |  }
   |    ^
43 |  const defuFn = createDefu((object, key, currentValue) => {
   |  ^
44 |    if (typeof object[key] !== "undefined" && typeof currentValue === "function") {

Transforming const to the configured target environment ("es5" + 2 overrides) is not supported yet
51 |    return useNuxtApp()._useHead(input, options);
52 |  }
53 |  
   |   ^
54 |  const inlineConfig = {};
   |  ^
55 |  
```

**Comment by manniL** [comment]
@ckhatton ES5 has no proxy support (they came with ES2015, which is ES6), so it won't support Vue3 and Nuxt3

**Comment by ckhatton** [comment]
Ar ok, thank you for letting me know @manniL 👍

**Comment by lww555** [comment]
Have you solved your problem？  now i use nuxt3.1.2 in ios12  and i set  
```
vite: {
 build: {
      // target: 'es2015'
      target: ["esnext", "ios12"],
    },
}

```
It still reports an error  like this
ReferenceError: Can't find variable: globalThis
ReferenceError: Cannot access uninitialized variable.

**Comment by duc2019** [comment]
I'm using this in my nuxt.config.js

``` text
vite: {
 build: {
    target: [ 'es2020', 'edge88', 'firefox78', 'chrome87', 'safari12' ],
  }
}
```

The default value of vite.build.target is safari14 which require atleast iOS 14, change it to safari12 makes my app able to run on iOS 12.

@vitejs/plugin-legacy also works (#20087) but it will increase the javascript file size by atleast 1MB and it will introduce `System is not defined` error (https://github.com/vitejs/vite/discussions/6581).

**Comment by Ludidi** [comment]
After i setup safari12, got this error
```
undefined is not a function (near '...Object.fromEntries...')
```
Is there any other solution?

**Comment by BunnyMan1** [comment]
> After i setup safari12, got this error
> 
> ```
> undefined is not a function (near '...Object.fromEntries...')
> ```
> 
> Is there any other solution?

+1

**Comment by JonathanDoelan** [comment]
> ReferenceError: Can't find variable: globalThis

@lww555 (How) Did you solve this issue? In a new app I am also getting this error with `globalThis` …

**Comment by alejandro-valencia14** [comment]
how to resolve globalThis in safari 11 with nuxt 3 please

**Comment by kirylvarykau** [comment]
> how to resolve globalThis in safari 11 with nuxt 3 please

> > ReferenceError: Can't find variable: globalThis
> 
> @lww555 (How) Did you solve this issue? In a new app I am also getting this error with `globalThis` …

Hi, I resolved an issue using the following approach. You may check an example of my `nuxt.config`.

So, you may add as many polyfills as required by your concrete case. In dev tools (console) you will see errors. Most likely, they could be solved by polyfills. 

Pay attention, that your polyfill must be loaded before nuxt/vue application is bootstrapped. Also, it should be run on browser (not on your server)

Good luck :) 


```
export default defineNuxtConfig({
  devtools: { enabled: false },
  devServer: {
    port: 3000,
    host: '0.0.0.0'
  },
  app: {
    head: {
      script: [
         {
           src: 'https://polyfill.io/v3/polyfill.min.js?features=globalThis'
         }
       ],
    }
  },
  vite: {
    build: {
      target: ['es2015', 'chrome87', 'safari12']
    }
  },
})
```

**Comment by oneyoung19** [comment]
简单说一下我的测试结果：
1、我这边的旧版本浏览器支持 `?.` 操作符，但是不支持 `??` 操作符；
2、因此我设置了 `vite` 的相关配置：
```js
// nuxt.config.js
export default defineNuxtConfig({
  vite: {
     target: ['es2015', 'ios12', 'chrome87', 'safari12']
  }
})
```
设置之后，**打包**之后的项目，运行正常。我没有遇见 `globalThis` 相关的报错。

**Comment by obronov** [comment]
I also had problems with `globalThis` and `Object.fromEntries` [I fixed it ](https://github.com/nuxt/nuxt/issues/15464#issuecomment-2142112599)
