### ISSUE TITLE
useFetch method patch is not work,explicit bug

### ISSUE THREAD

**Issue by weiyidechicheng** [nuxt/nuxt#19329]
### Environment

Nuxi 3.2.2
Nitro 2.2.3
Nodejs:19.6.0

### Reproduction

I build a repo to Test this bug.
https://github.com/weiyidechicheng/TestPatch.git

### Describe the bug

// app.vue
```
<template>
  <div>
    <button @click="upd">Test Patch</button>
  </div>
</template>

<script setup lang="ts">
const upd = async () => {
  const fileInfo = {
    name: 'testfile',
    ext: '.docx',
    size: 1024,
    sha1: 'B4C8BE74F084A2CE432654DA027419E8FAF7740B'
  }
  const { data, error, pending, refresh } = await useFetch('api/file/1', { method: 'patch', body: fileInfo })
  console.log('data', data)
  console.log('error', error)
  console.log('pending', pending)
  console.log('refresh', refresh)
}
</script>
```

// nuxt.config.ts
```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  vite: {
    server: {
      proxy: {
        "/api": {
          target: "http://biaozhun.online:88", 
          changeOrigin: true, 
          rewrite: path => path.replace(/^\/api/, ""),
        },
      },
    },
  },
})
```

when i click "Test Patch" button, the console will show:"400 Bad request"，but the api is work well in ApiPost.
I think the problem is the body of the request, but i don't know how to fix it.

**Comment by Baroshem** [comment]
Hey,

Could you create a reproduction in Stackblitz? Looking at the code I do not know what the issue can be

**Comment by weiyidechicheng** [comment]
> Hey,
> 
> Could you create a reproduction in Stackblitz? Looking at the code I do not know what the issue can be

I'll try it. I haven't used Stackblitz

**Comment by weiyidechicheng** [comment]
> Hey,
> 
> Could you create a reproduction in Stackblitz? Looking at the code I do not know what the issue can be

I create a reproduction in Stackblitz，but i this bug should reappear in browser console, i don't know hov to show browser  console in Stackblitz, and it seems not work well in Stackblitz.so i suggest you test this repo in vs code.

https://stackblitz.com/edit/nuxt-starter-wldbqb

**Comment by kurashina-design** [comment]
useFetch, useLazyFetch, useAsyncData and useLazyAsyncData only work during setup or Lifecycle Hooks. So please use $fetch.

**Comment by weiyidechicheng** [comment]
> useFetch, useLazyFetch, useAsyncData and useLazyAsyncData only work during setup or Lifecycle Hooks. So please use $fetch.

I have use it during setup, and i just write 50 lines code in the test repo, but it just not work, the api work well in ApiPost.
https://github.com/weiyidechicheng/TestPatch.git
400 Bad request
![](https://github.com/weiyidechicheng/TestPatch/blob/master/assets/Snipaste_2023-02-28_18-00-16.png)

work well or 401 Unauthorized(when have no token,this is right)
![](https://github.com/weiyidechicheng/TestPatch/blob/master/assets/Snipaste_2023-02-28_18-06-08.png)

**Comment by kurashina-design** [comment]
You seem to have used useFetch in the  "upd" method, not during setup or lifecycle. 

And perhaps [vite server proxy](https://vitejs.dev/config/server-options.html#server-proxy) only works in development ?
using [server routes](https://nuxt.com/docs/guide/directory-structure/server#server-routes) will be fine instead.



```
<template>
<button @click="someMethod">btn</button>
</template>


<script lang="ts" setup>

// during setup
const { data, error, pending, refresh } =  await useFetch('/api/someurl/', { method: 'GET' });

onMounted(async () => {
    // mounted lifecyle
    const { data, error, pending, refresh } =  await useFetch('/api/someurl/', { method: 'GET' });
});


const someMethod = async () => {
    // in the method
    const data = await $fetch('/api/someurl/', { method: 'GET' });
}

</script>
```

**Comment by weiyidechicheng** [comment]
> 

I don't think so, in my real projects,i declare many function as like this. This function always use useFetch with different "method" post/get/patch/delete, only "patch" is not work,  post/get/delete work very well, so i think it is bug.

**Comment by weiyidechicheng** [comment]
> You seem to have used useFetch in the "upd" method, not during setup or lifecycle.
> 
> And perhaps [vite server proxy](https://vitejs.dev/config/server-options.html#server-proxy) only works in development ? using [server routes](https://nuxt.com/docs/guide/directory-structure/server#server-routes) will be fine instead.
> 
> ```
> <template>
> <button @click="someMethod">btn</button>
> </template>
> 
> 
> <script lang="ts" setup>
> 
> // during setup
> const { data, error, pending, refresh } =  await useFetch('/api/someurl/', { method: 'GET' });
> 
> onMounted(async () => {
>     // mounted lifecyle
>     const { data, error, pending, refresh } =  await useFetch('/api/someurl/', { method: 'GET' });
> });
> 
> 
> const someMethod = async () => {
>     // in the method
>     const data = await $fetch('/api/someurl/', { method: 'GET' });
> }
> 
> </script>
> ```

I don't think so, in my real projects,i declare many function as like this. This function always use useFetch with different "method" post/get/patch/delete, only "patch" is not work, post/get/delete work very well, so i think it is bug.

**Comment by MehrdadKhnzd** [comment]
This is indeed a bug. I faced it some time ago but didn't find the time to open the issue.
The problem is that Nuxt `useFetch` and `$fetch` understand both `post` and `POST` as the method, but for `patch` requests, they only understand `PATCH`, although the typings don't suggest so.
The temporary solution would be to replace `patch` with `PATCH`, but it needs to be fixed.

**Comment by weiyidechicheng** [comment]
> This is indeed a bug. I faced it some time ago but didn't find the time to open the issue. The problem is that Nuxt `useFetch` and `$fetch` understand both `post` and `POST` as the method, but for `patch` requests, they only understand `PATCH`, although the typings don't suggest so. The temporary solution would be to replace `patch` with `PATCH`, but it needs to be fixed.

Thank you! you are right. I can definitely show that this is a bug. Like you say, just when I replace patch with PATCH, my program work very well.

**Comment by danielroe** [comment]
This is not a bug in Nuxt but rather an unusual detail in the HTTP spec - `patch` is the only HTTP method that is not normalised to all caps: https://github.com/github/fetch/issues/37#issuecomment-64010454. If your API requires it to be all caps, then you need to do that yourself.

**Comment by MehrdadKhnzd** [comment]
In my case, my API was created using Nuxt itself. When I'm using `useFetch` or `$fetch`, Typescript typings suggest that I can put both `PATCH` and `patch` as the method, but only `PATCH` works. This in the best case is misleading and it definitely needs to be fixed in someway, at least the typings.
