### ISSUE TITLE
UseFetch pending is initial true with {immediate: false} option

### ISSUE THREAD

**Issue by beyer-johannes** [nuxt/nuxt#19333]
### Environment

Nuxt project info:                                                                                                                                                12:42:28

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/beyer-johannes/use-fetch-pending-initial-true

### Describe the bug

Using useFetch with {immediate:false} option is initial true.

```
const { pending, execute } = useFetch(
  "https://api.chucknorris.io/jokes/random",
  {
    immediate: false,
  }
);

// pending.value === true without execute call.
```

It should be `false` initial to make it useable. If its true, and I use it in a `<input type="text" :disabled="pending"/>`, the input field is disabled on first visible moment, which's a wrong ux.

### Additional context

I tested vueUse's isFetching property in a empty vue environment and it is false per default.

```
import { useFetch } from "@vueuse/core";

const { isFetching, execute } = useFetch(
  "https://api.chucknorris.io/jokes/random",
  {
    immediate: false,
  }
);

// isFetching.value === false
```

**Comment by rozbo** [comment]
+1

**Comment by nikkorejz** [comment]
Any  updates???

**Comment by danielroe** [comment]
Instead you should use `status` ref returned from `useAsyncData`.

**Comment by ddahan** [comment]
I spent hours on this...
I wish the Nuxt documentation had a visible warning on this.
