### ISSUE TITLE
Render blocking layout CSS loads as last one

### ISSUE THREAD

**Issue by kstraszewski** [nuxt/nuxt#19334]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.1.0`
- Nitro Version:    `2.0.0`
- Package Manager:  `npm@8.19.0`
- Builder:          `vite`
- User Config:      `typescript`, `app`, `ssr`, `experimental`, `routeRules`, `postcss`, `css`, `modules`, `sitemap`, `image`, `unocss`, `runtimeConfig`, `vite`, `nuxtTypedRouter`, `plugins`, `build`
- Runtime Modules:  `nuxt-typed-router@2.3.5`, `@unocss/nuxt@0.50.1`, `@nuxt/image-edge@1.0.0-27954023.4cee565`, `nuxt-jsonld@2.0.7`, `@funken-studio/sitemap-nuxt-3@4.0.4`, `@pinia/nuxt@0.4.7`, `@vueuse/nuxt@9.13.0`, `()`
- Build Modules:    `-`
------------------------------

### Reproduction

1. going to https://www.experimental.qa.lendi.pl/
2. going to chrome dev console
3. runing performance insight

![image](https://user-images.githubusercontent.com/10195995/221854112-8f025115-528b-4198-8b93-a5473ef701cd.png)

### Describe the bug

Hi I'm having a problem with using Nuxt3. In my NuxtLayout which is named (lendi-basic). When I check the performance score. Im getting huge FCP coz of render-blocking CSS. As u can see here: (https://www.experimental.qa.lendi.pl/) layouts css file (lendi_basic.css) loads on the very end of the stack, which generates huge FCP and LCP. In my opinion, this css should load on the beginning, is there any way to change it? Also, weird thing is that this CSS loads after requests are made by JS.

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by danielroe** [comment]
Are you still experiencing this?

**Comment by danielroe** [comment]
The reproduction no longer links to a reproduction relevant to this issue.

I'll close this for now, but feel free to reopen with a new reproduction if you are still experiencing it.
