### ISSUE TITLE
Run dev server programmatically

### ISSUE THREAD

**Issue by dword-design** [nuxt/nuxt#19347]
### Describe the feature

It currently doesn't seem to be possible to run the dev server programmatically since it is tightly coupled to the console command. Or did I miss something?

If so, imho this is a step back from Nuxt 2 where you could run everything programmatically.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Yes, it is possible to run the dev server programmatically. You can check the implementation to see how to do it!

https://github.com/nuxt/nuxt/blob/a8f0a6d643f5d18cb12b1cdc8aa370e015522afc/packages/nuxi/src/commands/dev.ts#L37

**Comment by dword-design** [comment]
@danielroe Yes I found that and I actually tried to implement this as an npm package. But it uses a lot of shared functions that are not exported, so I'd have to basically copy-paste a lot of the logic from nuxi. If things would be exported anywhere this would already help 🙂.

**Comment by danielroe** [comment]
FWIW, the Nuxt commands are exported so you can invoke them programmatically if you don't need to customise things...

**Comment by dword-design** [comment]
@danielroe Would it be somehow possible to pass a config through to [this](https://github.com/nuxt/nuxt/blob/a8f0a6d643f5d18cb12b1cdc8aa370e015522afc/packages/nuxi/src/commands/dev.ts#L91) line?
