### ISSUE TITLE
CI Workflows running on windows

### ISSUE THREAD

**Issue by ennioVisco** [nuxt/nuxt#19346]
### Describe the feature

To avoid some regressions on windows (for the core, as well as for modules), I think it would be nice if the workflows are run not only through ubuntu but also through Linux. At this link, there are the (very simple) instructions for running the workflows on multiple operating systems: https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#using-a-matrix-strategy.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by Baroshem** [comment]
Hey,

In general I would agree however, I am not sure what are the limits for Nuxt organization on GitHub Actions minutes. Running the same tests as for another operating systems may cause the limit to run out really fast.

@danielroe what do you think about it?

**Comment by ennioVisco** [comment]
> Hey,
> 
> In general I would agree however, I am not sure what are the limits for Nuxt organization on GitHub Actions minutes. Running the same tests as for another operating systems may cause the limit to run out really fast.
> 
> @danielroe what do you think about it?

AFAIK there are no limits on public repositories... That said, it would be reasonable to at least run them on new releases, don't you think?

**Comment by Baroshem** [comment]
I think there are limits.

Regarding the on release. I would say that it should be done before release. So that we wont push a new version that brakes something.

**Comment by danielroe** [comment]
We already use a matrix to test Nuxt against Windows, Linux and MacOS.
