### ISSUE TITLE
Global Javascript transition not working

### ISSUE THREAD

**Issue by BenjaminOddou** [nuxt/nuxt#19359]
### Discussed in https://github.com/nuxt/nuxt/discussions/18834

I created a small repro of the problem [here](https://stackblitz.com/edit/nuxt-starter-bxqwv5?file=app.vue).

**Comment by BenjaminOddou** [comment]
Hello @danielroe, do you have an idea of what's causing the bug ? I'd love to investigate more but I would need some insights 😄 Many thanks in advance

**Comment by BenjaminOddou** [comment]
Hello @danielroe , @manniL , do you have an idea of what's causing the bug ? I'd love to investigate more but I would need some insights 😄 Many thanks in advance

**Comment by barelyhuman** [comment]
As a workaround for this specific issue with gsap you could change the scope that gsap uses to init the transitions in.

It still does require you to watch the element to exist due to the `onMount` + Suspense issue

```vue
<script setup>
import gsap from 'gsap';

// create a ref for the wrapper that the _element to be animated_ is in
const container = ref();

// watch on it
watch(container, (node) => {
  if (!node) return;

  gsap.context(() => {
    gsap
      .timeline()
      .to("#link1", {
        y: 150,
        duration: 1.2,
      })
      .to("#link1", {
        y: 0,
        duration: 1,
      });
  }, node); // <= define the resolved node as the source of the gsap context


});
</script>

<template>
  <div id="el" ref="container">
    <div class="wrapper">
      <NuxtLink id="link1" to="/page2">Page2</NuxtLink>      
    </div>
  </div>
</template>

```
