### ISSUE TITLE
Nuxt Deployment on Vercel Caches All API Requests

### ISSUE THREAD

**Issue by MehrdadKhnzd** [nuxt/nuxt#19353]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.19.0`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.3`
- Package Manager:  `pnpm@7.22.0`
- Builder:          `vite`
- User Config:      `components`, `ssr`, `app`, `routeRules`, `nitro`, `css`, `build`, `modules`, `pwa`
- Runtime Modules:  `@vite-pwa/nuxt@0.0.6`, `()`
- Build Modules:    `-`

### Reproduction

It can't be reproduced in a local environment.

### Describe the bug

I faced this strange behavior that my login page didn't act correctly when I first deployed my app using Vercel.
Then I realized Vercel caches my API requests, although it was a `POST` request.
Then I did every kind of config to prevent this behavior:
* Tried to add cache-control response and request headers on a server middleware
* Tried to set the `cache` property of `$fetch` to `no-store` and also added `Cache-Control` header directly to the request
* Added `vercel.json` config file and added header settings to prevent caching
* Added an empty `Authorization` header to the request
* Removed PWA module to make sure it's not its fault
* Added a timestamp to query string to force it not to cache, and surprisingly it didn't work
* Even added a timestamp property to the body to force the operation but shockingly it didn't work again
* The only thing that worked was that I added a timestamp slug to the route path and it finally worked

After fixing the problem for auth this way, I checked other pages and they also just return the cached value every time. I can't verify it for `GET` requests as they are already cached by the browser (`304`) but Vercel itself caches `POST` and `PATCH` requests.

### Additional context
There's not much more I know. I can just confirm that I see Vercel cache headers (`x-vercel-cache: HIT`) and the associated `age` in the response. I haven't tried any other deployment method other than Vercel.

**Comment by Baroshem** [comment]
Hey,

It looks to me a bit like a problem with caching fro vite pwa package. Have you tried removing it and seeing if your app is still cached?

**Comment by MehrdadKhnzd** [comment]
Hi,

As I mentioned in the description, I tried removing it but it didn't help. Upon your request, I did it one more time to make sure, and again, it didn't work. It still caches everything.

**Comment by Baroshem** [comment]
Ahh apologize, I havent noticed that.

Could you paste here the content of your routeRules? Maybe there are some cache rules set there that are causing it?

**Comment by danielroe** [comment]
`static: true` _is_ a cache rule. It specifically instructs Nuxt to cache every response permanently. What are you intending instead?

**Comment by MehrdadKhnzd** [comment]
Ah, I didn't know that. I want SSG for all pages, but it seems I must manually exclude API routes, right?
Just to make sure, what would be the correct configuration for that? Thanks!

**Comment by danielroe** [comment]
(Note that you have disabled rendering HTML with `ssr: false` so what is rendered will be blank pages without content.)

This might work for you:

```js
  routeRules: {
    '/**': { static: true }, // or maybe { prerender: true } might be more what you want
    '/api/**': { static: false, cache: false },
  },

**Comment by MehrdadKhnzd** [comment]
That did the trick, thanks for your help!

**Comment by davidparys** [comment]
> (Note that you have disabled rendering HTML with `ssr: false` so what is rendered will be blank pages without content. I generally advise against setting `ssr: false` unless you have a good reason.)
> 
> This might work for you:
> 
> ```js
>   routeRules: {
>     '/**': { static: true }, // or maybe { prerender: true } might be more what you want
>     '/api/**': { static: false, cache: false },
>   },
> ```

I don't care if it's old, you just saved me 3 hours of passing my code to client side only because I was getting frustrated I had no idea why this was happening until I added a unique ID to every of my calls and saw that it was always the same. 

Thanks! 💚

**Comment by SultanDino** [comment]
Have you been able to solve this? I am currently facing the same issue.
All of my api route responses is being cached and returned to browser.

**Comment by davidparys** [comment]
> Have you been able to solve this? I am currently facing the same issue. All of my api route responses is being cached and returned to browser.

Seems like it has solved itself, I no longer hit the vercel cache on my api routes even on a default setup. 

![Image](https://github.com/user-attachments/assets/330fcf94-bd4f-446b-b256-9d78807e54b2)
