### ISSUE TITLE
Any router property to define path prefix?

### ISSUE THREAD

**Issue by gezichenshan** [nuxt/nuxt#19364]
### Describe the feature

Our app is deployed on a site url is https://${domain}/aaa/bbb/
The root path is '/aaa/bbb'.
After deployed the nuxt app online, we visit the site https://${domain}/aaa/bbb/ and it says `Page not found: /aaa/bbb/`. 

I want when the user visit https://${domain}/aaa/bbb/, the nuxt app should return page '/' instead of '/aaa/bbb/'.

So the `/aaa/bbb/` should be just the prefix of the root path of the router.

I didn't find any configurations about this. If there already has one, please help me find where it is.
Is this possible or we can only implement this feature in server side?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
You can do this with `app.baseURL` in your nuxt config file.

**Comment by gezichenshan** [comment]
@danielroe Ah, what a shame me.
Thank you.
