### ISSUE TITLE
set headers doesnot work

### ISSUE THREAD

**Issue by zouhangwithsweet** [nuxt/nuxt#19362]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.18.0`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.3`
- Package Manager:  `pnpm@7.2.1`
- Builder:          `vite`
- User Config:      `modules`, `unocss`
- Runtime Modules:  `@unocss/nuxt@0.50.1`
- Build Modules:    `-`

### Reproduction

```ts
// nuxt.config.ts
vite: {
  server: {
    headers: {
      'Cross-Origin-Embedder-Policy': 'require-corp',
      'Cross-Origin-Opener-Policy': 'same-origin',
    },
  },
}
```

### Describe the bug

set headers doesnot work

### Additional context

<img width="434" alt="image" src="https://user-images.githubusercontent.com/21095710/222102040-e2c1da98-b84a-4681-96a5-46b7645b2beb.png">

**Comment by danielroe** [comment]
In Nuxt, the Vite dev server doesn't have the same role it does in a Vite project and configuring it is generally not advised (because it may not work as you expect). Instead, you should set Nuxt route rules:

```js
export default defineNuxtConfig({
  routeRules: {
    '/**': {
      headers: {
        'Cross-Origin-Embedder-Policy': 'require-corp',
        'Cross-Origin-Opener-Policy': 'same-origin'
      }
    }
  }
})
```

**Comment by zouhangwithsweet** [comment]
Thanks :)
