### ISSUE TITLE
Process.env not populated in defineNuxtConfig

### ISSUE THREAD

**Issue by JohnTipping** [nuxt/nuxt#19373]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.14.2`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@9.5.0`
- Builder:          `vite`
- User Config:      `app`, `css`, `build`, `modules`, `publicRuntimeConfig`
- Runtime Modules:  `nuxt-icon@0.1.6`
- Build Modules:    `-`

### Reproduction

console.log("in config", process.env);   // this gives the expected output

export default defineNuxtConfig({
    publicRuntimeConfig: {
          somevariable: process.env.SOME_VARIABLE        // this is undefined
    }

### Describe the bug

process variable don't seem to be available any more. this is upgrading app from version next 3.0.0-rc11 where this worked just fine

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by oleghalin** [comment]
```
  runtimeConfig: {
    public: {
      someVariable: process.env.ENV
    }
  }
```

**Comment by JohnTipping** [comment]
> runtimeConfig: {
>     public: {
>       someVariable: process.env.ENV
>     }
>   }

I thank you. i was still using the publicRuntimeConfig key. every thing i found in google say this way and even chatgpt (lol it got it wrong) see screen shot so thanks again for the spot on advice


![Screenshot from 2023-03-01 15-26-10](https://user-images.githubusercontent.com/3382190/222185004-3867ea78-d9c8-4060-a21b-ce499cedf984.png)
