### ISSUE TITLE
<NuxtLink custom ...> throws a warning in Nuxt 3.2.3 due to explicit rel attribute

### ISSUE THREAD

**Issue by ydnar** [nuxt/nuxt#19375]
### Environment

- Operating System: `Darwin`
- Node Version:     `v19.7.0`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `pnpm@7.28.0`
- Builder:          `vite`
- User Config:      `telemetry`, `modules`, `vite`, `runtimeConfig`, `css`, `app`, `content`, `i18n`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.10`, `@nuxt/content@2.4.3`
- Build Modules:    `-`

### Reproduction

https://github.com/nuxt/nuxt/pull/19309#issuecomment-1448885808

> ```
> 	<NuxtLink custom v-slot="{ href, navigate }" :to="targetRoute">
> 		<component :is="tag" :href="href" @click="navigate" role="link" class="domain"
> 			><slot>{{ displayDomain(domain, status) }}</slot></component>
> 	</NuxtLink>
> ```

### Describe the bug

The explicit `rel` attr/prop introduced in Nuxt 3.2.3 (https://github.com/nuxt/nuxt/pull/19309) is incompatible with `NuxtLink custom` (to use a tag other than `<a>`).

**Comment by lihbr** [comment]
Thanks for opening an issue! I'll be investigating it.

In the meantime, this can be quick-fixed by explicitly declaring attributes with `v-bind="$attrs"` (see: https://vuejs.org/guide/components/attrs.html#attribute-inheritance-on-multiple-root-nodes)

```
<NuxtLink custom v-slot="{ href, navigate }" :to="targetRoute">
	<component :is="tag" :href="href" @click="navigate" role="link" class="domain" v-bind="$attrs">
		<slot>{{ displayDomain(domain, status) }}</slot>
	</component>
</NuxtLink>
```

**Comment by ydnar** [comment]
Thanks! We ended up using `RouterLink` directly. Any problem with that?

**Comment by lihbr** [comment]
Glad you had a workaround! Using `RouterLink` directly is *fine-ish*, however, this opts you out of some Nuxt optimization, namely route prefetching.

**Comment by lihbr** [comment]
Related:
- PR: https://github.com/nuxt/nuxt/issues/14897
- Issue: https://github.com/nuxt/framework/pull/7522
