### ISSUE TITLE
Vuetify Support 

### ISSUE THREAD

**Issue by Didza** [nuxt/nuxt#19380]
### Describe the feature

Please provide support for Vuetify 3.

Thank you

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by harlan-zw** [comment]
Vuetify support is not something the Nuxt core would support out of the box, this is what modules are for.

There already exists a Vuetify module as well: https://github.com/nuxt-alt/vuetify
