### ISSUE TITLE
nirto throw Error `[ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client` in SSE API 

### ISSUE THREAD

**Issue by zouhangwithsweet** [nuxt/nuxt#19384]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.18.0`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.3`
- Package Manager:  `pnpm@7.2.1`
- Builder:          `vite`
- User Config:      `modules`, `unocss`
- Runtime Modules:  `@unocss/nuxt@0.50.1`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-vgyh5u-anvs91?file=server%2Fapi%2Fhello.ts

### Describe the bug

- create a SSE api `/api/hello`
- fetch('/api/hello')
- got an error
```bash
[nitro] [dev] [unhandledRejection] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (internal/errors.js:322:7)
    at ServerResponse.setHeader (_http_outgoing.js:561:11)
    at Object.errorhandler [as onError] (file:///Users/didi/Desktop/work/test-nuxt/.nuxt/dev/index.mjs:457:20)
    at Server.toNodeHandle (file:///Users/didi/Desktop/work/test-nuxt/node_modules/.pnpm/h3@1.5.0/node_modules/h3/dist/index.mjs:1278:27)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```
- and it cannot be trigger `event.nodereq.onclose` event.

**Comment by danielroe** [comment]
Would you open an upstream issue at https://github.com/unjs/nitro? 🙏  This is likely something we would need to make possible there.

**Comment by odranoelBR** [comment]
I have exactly same cenario.

@zouhangwithsweet for now i'm using a custom error handler to hide this particular url api error.
https://nitro.unjs.io/config#errorhandler

**Comment by zouhangwithsweet** [comment]
> I have exactly same cenario.
> 
> @zouhangwithsweet for now i'm using a custom error handler to hide this particular url api error. https://nitro.unjs.io/config#errorhandler

Oh, thanks. Do you found that the `req` cannot be trigger `close` event ?

**Comment by danielroe** [comment]
Closing here - we can track upstream in unjs/nitro#1005.

**Comment by odranoelBR** [comment]
@zouhangwithsweet no.
My close event is working good.

```ts
  source.addEventListener('message', ({ data }: { data: string }) => {
    const task : Task = JSON.parse(data)

    if (task?.status === 'INICIAL') {
      source.close()
      event.node.res.end(JSON.stringify(task))
    }
  })
```

**Comment by odranoelBR** [comment]
@zouhangwithsweet no.
My close event is working good.

```ts
  source.addEventListener('message', ({ data }: { data: string }) => {
    const task : Task = JSON.parse(data)

    if (task?.status === 'INICIAL') {
      source.close()
      event.node.res.end(JSON.stringify(task))
    }
  })
```
