### ISSUE TITLE
Azure preset, reference to compiled assets failing. 

### ISSUE THREAD

**Issue by bootsmann1995** [nuxt/nuxt#19385]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.19.1`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@8.19.3`
- Builder:          `vite`
- User Config:      `app`, `nitro`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

minimal reproduction: https://stackblitz.com/edit/github-cz6c3f

steps: 
- download project from stackblitz
- install swa (link: https://azure.github.io/static-web-apps-cli/docs/use/install)
- run command: npm run build-and-run.

### Describe the bug

When running azure preset, it gets 404 on assets from the server. 

![image](https://user-images.githubusercontent.com/65391517/222374497-195132d3-137b-4466-aa5e-cdd546c6a313.png)

It seems like the azure preset doesn't get the right path for destribution.

this is the HTTP request for the file: 
![image](https://user-images.githubusercontent.com/65391517/222375015-86a5bd45-b6da-4fac-b978-919f26ff88a4.png)

this is were it succeeds
![image](https://user-images.githubusercontent.com/65391517/222375235-4937197b-f47f-44ea-ad59-631d643ebd3f.png)

so it is missing the /ventilation/ path

**Comment by danielroe** [comment]
Reproduces by modifying provided reproduction to add `app.baseURL`

**Comment by danielroe** [comment]
This is now resolved upstream.
