### ISSUE TITLE
UseState not working in plugin and useFetch

### ISSUE THREAD

**Issue by leccyril** [nuxt/nuxt#19382]
### Environment

Nuxi 3.2.3                                                                                                                       16:50:41
Nuxt 3.2.3 with Nitro 2.2.3     

Stackblitz

### Reproduction

https://stackblitz.com/edit/nuxt-starter-czyl17?file=pages/index/index.vue

just execute code and check content displayed

We try to use useState to put value a init file (in plugins folder) and reuse it later in a menu, we are calling useFetch and in the response (200) we want to set value, but nothing more happen, no error message, no data put, and moreover we don't go further in the code. we exit the useFetch then we go on the end of file

PS: outside the useFetch it was working

### Describe the bug

We should see 

_Home page
this is a test TEST
this is a test test value2_

but we see only 

_Home page
this is a test test value2_

in log we should see : 

```
useState will be set
useState was set
end of init
```

but we see only 

```
useState will be set
end of init  
```

### Logs

```shell-script
✔ Nitro built in 1013 ms                                                                        nitro 09:52:12
ℹ Vite client warmed up in 5048ms                                                                     09:52:12
✔ Vite server hmr 24 files in 1746.06ms                                                               09:52:15
useState will be set                                                                                  09:52:15
end of init                                                                                           09:52:15
useState will be set                                                                                  09:52:15
end of init
```

**Comment by leccyril** [comment]
So following previous issue :

```
let username: String;
	let role: String;
	let isConnected: boolean = false;

	//useState('username', ()=>'test');
	if (token !== null && token?.length > 0) {
		await useFetch(REST_API_URL + '/auth/validate', {
			method: 'POST',
			headers: {
				'Authorization': 'Bearer ' + token,
				'Content-Type': 'Application/json'
			},
			onResponse({request, response, options}) {
				// Process the response data
				if (response.status === 200) {
					const payload = parseJwt(token)
					username = payload.username
					role = payload.role
					isConnected = true
				}
			},
			onResponseError({request, response, options}) {
				console.log('token is not valid or expired');
				if (response.status === 400) {
					console.error('token expired or invalid');
				} else {
					console.error('internal issue problem');
				}
				router.push("/")
			},
		});

		if (isConnected) {
			useState('isConnected', () => isConnected);
			useState('username', () => username);
			useState('role', () => role);
		}

	} else {
		console.log('No token registered')

	}
```
do the trick, but is it the best solution to do ... i don't know

**Comment by danielroe** [comment]
`useState` should not be called in a response handler: see https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables. (And also, you should not use `useFetch` in this case, but `$fetch`.)

```diff
  export default defineNuxtPlugin(async () => {
+   const test = useState('test');
-   await useFetch('https://httpbin.org/get', {
+   await $fetch('https://httpbin.org/get', {
      onResponse({ request, response, options }) {
        // Process the response data
        if (response.status === 200) {
          console.log('useState will be set');
-         useState('test', () => 'test value');
+         test.value = 'test value'
          console.log('useState was set');
        }
      },
      onResponseError({ request, response, options }) {
        //We don't care
      },
    });
    console.log('end of init');
  });
```

**Comment by leccyril** [comment]
> `useState` should not be called in a response handler: see https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables. (And also, you should not use `useFetch` in this case, but `$fetch`.)
> 
> ```diff
>   export default defineNuxtPlugin(async () => {
> +   const test = useState('test');
> -   await useFetch('https://httpbin.org/get', {
> +   await $fetch('https://httpbin.org/get', {
>       onResponse({ request, response, options }) {
>         // Process the response data
>         if (response.status === 200) {
>           console.log('useState will be set');
> -         useState('test', () => 'test value');
> +         test.value = 'test value'
>           console.log('useState was set');
>         }
>       },
>       onResponseError({ request, response, options }) {
>         //We don't care
>       },
>     });
>     console.log('end of init');
>   });
> ```

hi, thanks
what is the difference using $fetch and useFetch i am always lost...

**Comment by danielroe** [comment]
useFetch is a Vue composable that handles moving data from server -> client, reactively updating data when the inputs change, etc. And crucially it should only be called in a Vue setup function. Whereas `$fetch` is the underlying fetch call that powers `useFetch` and can be used standalone when you simply need to programmatically fetch from an endpoint.

**Comment by leccyril** [comment]
Really clear



Envoyé depuis mon appareil Galaxy



-------- Message d'origine --------
De : Daniel Roe ***@***.***>
Date : 02/03/2023 14:26 (GMT+04:00)
À : nuxt/nuxt ***@***.***>
Cc : leccyril ***@***.***>, Author ***@***.***>
Objet : Re: [nuxt/nuxt] UseState not working in plugin and useFetch (Issue #19382)


useFetch is a Vue composable that handles moving data from server -> client, reactively updating data when the inputs change, etc. And crucially it should only be called in a Vue setup function. Whereas $fetch is the underlying fetch call that powers useFetch and can be used standalone when you simply need to programmatically fetch from an endpoint.
