### ISSUE TITLE
Plugin types resolve with useNuxtApp(), but not in defineNuxtPlugin((nuxtApp) => ...)

### ISSUE THREAD

**Issue by bradlis7** [nuxt/nuxt#19396]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v18.14.0`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@9.3.1`
- Builder:          `vite`
- User Config:      `app`, `modules`, `devServer`, `routeRules`, `runtimeConfig`, `devServerHandlers`
- Runtime Modules:  `bootstrap-vue-next/nuxt`, `@nathanchase/nuxt-dayjs-module@1.0.11`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-n95cg9?file=app.vue

StackBlitz doesn't show you the resolved types in the .vue file, but it shows up in VS Code.

### Describe the bug

When in a .vue page or component, if I import the plugin, it resolves in VS Code.

```
// $anotherPlugin resolves with { callTwo(): string }
const { $anotherPlugin } = useNuxtApp();
```

But if I use one plugin in another plugin, it doesn't resolve.

```
export default defineNuxtPlugin((nuxtApp) => {
  return {
    provide: {
      anotherPlugin: {
        callTwo() {
          // $basePlugin resolves as any
          const result = nuxtApp.$basePlugin.callOne();
          console.log(result);
          return result;
        }
      }
    }
  }
})
```

**Comment by danielroe** [comment]
This is deliberate, to avoid an infinitely recursive type loop. If you need to access the typed version, you can use `useNuxtApp()`.
