### ISSUE TITLE
NuxtLink render href='/' for only one account ?

### ISSUE THREAD

**Issue by ImJustLucas** [nuxt/nuxt#19391]
### Environment

Nuxt: 2.14.8
node: 14.20.1

### Reproduction

clasic `<NuxtLink></NuxtLink>`

### Describe the bug

Everything works correctly on the app, etc. Except on an account, where all my nuxt link seems to generate badly. All the href returns to "/" and has the active class (Example with my Dev/Prod bottom bar).

I also noticed that locally everything worked perfectly with yarn generate

Only when it’s online, I host with netlify, on the production environment

Dev bottom bar (the good one) 
![image](https://user-images.githubusercontent.com/74179788/222411767-9af62e88-a58b-4162-a2a6-e16e68a42090.png)

Prod online bottom bar (this is the bug)
![image](https://user-images.githubusercontent.com/74179788/222411975-3e0d3864-3c83-4b7f-945c-0b922e726158.png)

I repeat myself, I got this bug only when I'm using an account (configured like all other accounts)

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by ImJustLucas** [comment]
There is no such a reproduction I'm afraid

because it is working when I'm logged on an another account

But when I'm using this account (the 'official' of the app), I got this bug

`<NuxtLink :to="localePath(`/users/${loggedInUser.slug}`)">
   <Avatar :avatar="loggedInUser.avatar" :user-id="loggedInUser.id" />
</NuxtLink>`

this is what a nuxtlink look like

but whatever the code in, this will render as the image above

**Comment by danielroe** [comment]
Perhaps it's an issue with `localePath`? Or maybe a hydration issue if you aren't handling difference between logged out (SSG HTML) and logged in (client)?

Either way, we need a reproduction to look into this.

**Comment by ImJustLucas** [comment]
It seems it was due to localePath, strange because it is working fine on all other accounts, I'll search why
