### ISSUE TITLE
HTTPS过期也会导致nuxt项目报错空白！The expiration of HTTPS will also cause the nuxt project to report a blank error!

### ISSUE THREAD

**Issue by Haiwar** [nuxt/nuxt#19406]
### Environment

 "nuxt": "^2.15.3",

### Reproduction

https://liuhai.work/

### Describe the bug

![image](https://user-images.githubusercontent.com/35055270/222626607-bdbc9fc7-465a-4363-be8c-c6e4e094aee1.png)
![image](https://user-images.githubusercontent.com/35055270/222626627-6ba4cb9a-b8ef-4105-9cef-6e034336dc06.png)

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by Haiwar** [comment]
> 
Thank you for your reply. I want to know what's wrong. Here is the address of GitHub：
https://github.com/Haiwar/nuxtjs-blogvue

**Comment by Haiwar** [comment]
I found the problem, the https of my domain name expired. Found by checking axios😶‍🌫️😶‍🌫️😶‍🌫️
