### ISSUE TITLE
Mismatching childNodes vs. VNodes when using <template> tag

### ISSUE THREAD

**Issue by edsonfeimberg** [nuxt/nuxt#19401]
### Environment

I faced a problem that i believe is a bug. I was facing a Mismatching childNodes vs. VNodes error when trying to render the following block of code:

```
<client-only>
        <template v-if="!loggedIn">
          <nuxt-link to="/register">
            <v-btn>Register</v-btn>
          </nuxt-link>
          <nuxt-link to="/login">
            <v-btn>login</v-btn>
          </nuxt-link>
        </template>
        <template v-else>
          <v-btn @click="logout">Logout</v-btn>
        </template>
      </client-only>
```

After a day trying different things, for my surprise, everything worked perfectly just by using a <div> tag instead of <template>:

```
<client-only>
        <div v-if="!loggedIn">
          <nuxt-link to="/register">
            <v-btn>Register</v-btn>
          </nuxt-link>
          <nuxt-link to="/login">
            <v-btn>login</v-btn>
          </nuxt-link>
        </div>
        <div v-else>
          <v-btn @click="logout">Logout</v-btn>
        </div>
      </client-only>
    </v-navigation-drawer>
```

Additional info: The rendering was controlled by the following computed property:

```
loggedIn() {
      if (this.$auth.$storage.getState('user')) {
        return true
      } else {
        return false
      }
    }, 
```

And a page reload while being logged in was the action that triggered the mismatch. 

Since i was using <client-only> tag, is of my understanding that mismatches between server and client shouldn't exist.

### Reproduction

Create project using nuxt and vuetify
Use nuxt auth to store login status in browser
implement code above

### Describe the bug

Explained in main post

**Comment by manniL** [comment]
IIRC that occurs because the [`<ClientOnly>`](https://github.com/egoist/vue-client-only/blob/master/src/index.js) component expects an actual top-level root element in Nuxt 2.
