### ISSUE TITLE
How to Enable gzip on nuxt3?

### ISSUE THREAD

**Issue by capraynor** [nuxt/nuxt#19411]
Hello. 
Could you please introduce how to enable gzip on nuxt3 applications, or we should implement the gzip logic on front-end servers (like nginx and apache)? 

Kindly Regards
Raynor

**Comment by Baroshem** [comment]
Hey,

I think that you can use the nitro compression as shown here -> https://stackoverflow.com/a/73670394

Or use vite compression module https://github.com/vbenjs/vite-plugin-compression

**Comment by capraynor** [comment]
Hello, @Baroshem 
Thanks for your quick reply. 
We've did the following configuration: 

```
import { defineNuxtConfig } from 'nuxt'

export default defineNuxtConfig({
  nitro: {
    compressPublicAssets: true,
  },
})
```

And *.js.br files generated after build (OK)
But the requests still not being gzipped. (Not Good) 

Could you please provide more instructions, thank you so much. 

Kindly Regards
Raynor

**Comment by Baroshem** [comment]
Hey,

Compression works only for static assets. You cannot compress requests AFAIK.

https://en.m.wikipedia.org/wiki/Gzip

**Comment by manniL** [comment]
@Baroshem You can compress the HTML sent from the server.

@capraynor That depends on where you host your app. Ideally, your platform provider (Netlify/Vercel/...) takes care of that *or* if you use a VPS, you have NGINX/Traeffik/... in front to deal with that.

Happy to open an issue to support compression for the node preset of nitro out of the box (if possible)

**Comment by Baroshem** [comment]
@manniL You are right. Thanks for clarifying that :)

**Comment by praxxys** [comment]
We were getting errors with `npx nuxi build` so we decided to use https://github.com/gios/gzipper package to do the gzipping. Once the package is installed compressing is as simple as running:

```
npx nuxi generate
npm run compress // which is a configured shorthand for gzipper compress .output/public
```

On a Mac Mini M2, `gzipper` is blazing fast as it uses all 8 CPU cores. 🤩

Hope this helps future readers.
