### ISSUE TITLE
Vercel prerender breaks Nuxt file system router.

### ISSUE THREAD

**Issue by bokub** [nuxt/nuxt#19418]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.19.1`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Not a repository, but a script to create the minimal reproduction project, and deploy it 2 times on Vercel

```bash
## Init project
npx nuxi init vercel-nuxt
cd vercel-nuxt
yarn
rm app.vue
mkdir pages
echo '<script setup>
const {data} = await useAsyncData(() => ({
  params: useRoute().params,
  now: new Date().toISOString()
}))
</script>
<template>
  <pre>
<client-only>path (client-side): /{{ $route.params.path }}</client-only>
<client-only>client time: {{  new Date().toISOString() }}</client-only>
path (server-side): /{{ data.params.path }}
build time: /{{ data.now }}
  </pre>
</template>' > 'pages/[[path]].vue'

## Build and deploy project on Vercel
NITRO_PRESET=vercel yarn build
vercel deploy --prebuilt # accept all default options when prompted

## Add prerender config and deploy again on Vercel
echo '{
  "expiration": 10
}' > .vercel/output/functions/__nitro.prerender-config.json
vercel deploy --prebuilt
```

### Describe the bug

Hi,

I'm trying to use the [Vercel Build Output API](https://vercel.com/docs/build-output-api/v3) to deploy a Nuxt 3 application that can keep the SSR output in a cache.

The problem is that when I setup the prerender configuration, it completely breaks the file system router of Nuxt.

As an example, I created a script (read above) to create a minimal reproduction project and deploy it 2 times on Vercel (the first one without cache, the other with a 10 seconds cache).

Here are the results:
- Without caching: https://vercel-nuxt-m1l9xucwe-bokub.vercel.app/hello
- With a 10s cache: https://vercel-nuxt-evkas78q1-bokub.vercel.app/hello

Here is the code of the page in both these deployments:

```vue
<script setup>
const {data} = await useAsyncData(() => ({
  params: useRoute().params,
  now: new Date().toISOString()
}))
</script>

<template>
  <pre>
<client-only>path (client-side): /{{ $route.params.path }}</client-only>
<client-only>client time: {{  new Date().toISOString() }}</client-only>
path (server-side): /{{ data.params.path }}
build time: /{{ data.now }}
  </pre>
</template>
```

As you can see, the second build cannot read the path and always thinks the path is `__nitro`, which is the name of the serverless function.

Are you aware of this problem ? Is this a Nuxt bug or a Vercel bug ?

Thanks ! :+1:

**Comment by danielroe** [comment]
You shouldn't need to pass a custom prerender config. Instead, use `routeRules`, and nitro will correctly configure the prerender config for you:

```js
export default defineNuxtConfig({
  routeRules: {
    '/**': { swr: 60 }
  }
})
```

**Comment by bokub** [comment]
Thank you for your answer Daniel, you're so fast ! :zap: 

The `routeRules` definitely solved my problem!

However, it looks like whatever I put in `swr`, the generated prerender config always says `"expiration":60`, but in the end, the actual cache time is what I put in my Nuxt config. What kind of magic is this ?

**Comment by bokub** [comment]
I'm not sure to understand how it works.. If I put `10` or `500` in my nuxt config, the cache duration is really 10 or 500 seconds, but the generated file always say 60, no matter what! But nevermind, as long as it works, I'm happy :+1: 

______

Now I have another problem, but I'm not sure there is (yet) a solution

If I use the following Nuxt config, and run `yarn build`

```js
export default defineNuxtConfig({
    routeRules: {
        '/**': { static: true }
    }
})
```
Then the generated prerender config is the following (looks good to me):

```
{"expiration":false,"allowQuery":["url"]}
```

I'd like to have a way to purge the cache manually, to I add a `bypassToken` to this file before deploying:

```
{"expiration":false,"allowQuery":["url"], "bypassToken": "03326da8bea31b919fa3a31c85747ddc"}
```

Now, if I run `curl https://vercel-nuxt-i03r9nry2-bokub.vercel.app/prerender i -H "x-prerender-revalidate: 03326da8bea31b919fa3a31c85747ddc"`, I can see in the response headers that the cache has been purged, as expected (`x-vercel-cache: REVALIDATED`).

But when I visit https://vercel-nuxt-i03r9nry2-bokub.vercel.app/prerender, the "build time" always stays the same (13:42:46 today)

It this a bug on Vercel's side?

**Comment by bokub** [comment]
Nevermind, everything works now!

Thank you so much for your time Daniel, have a good day :pray:
