### ISSUE TITLE
Possible type regression in `v3.2.3`

### ISSUE THREAD

**Issue by pascalwengerter** [nuxt/nuxt#19416]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.3`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `sanity`, `app`, `components`, `css`, `imports`, `modules`, `routeRules`, `hooks`, `runtimeConfig`, `meta`, `vite`
- Runtime Modules:  `@nuxt/image-edge@1.0.0-27913696.5d122a3`, `@nuxtjs/sanity@1.6.0`, `@pinia/nuxt@0.4.6`, `@pinia-plugin-persistedstate/nuxt@1.0.0`, `@vueuse/nuxt@9.12.0`, `nuxt-icons@3.1.0`, `nuxt-schema-org@2.1.2`, `vite-plugin-vue-type-imports/nuxt`
- Build Modules:    `-`

### Reproduction

Will add later

### Describe the bug

I've tried updating to `v3.2.3` this morning and was faced with `Type instantiation is excessively deep and possibly infinite` in my nuxt config (culprint are the `modules` afaik) - looking at https://github.com/nuxt/nuxt/issues?q=is%3Aissue+Type+instantiation+is+excessively+deep+and+possibly+infinite+is%3Aclosed this was fixed in the past, so potentially creeped back in somehow?

**Comment by jontybrook** [comment]
Also seeing this in 3.2.3.

Modules in use are:

```
    modules: [
        'nuxt-lodash', 
        '@nuxtjs/tailwindcss', 
        '@pinia/nuxt', 
        '@formkit/nuxt',
        'nuxt-headlessui',
        '@nathanchase/nuxt-dayjs-module',
        '@nuxtjs/google-fonts',
        '@vueuse/nuxt',
        '@vueuse/motion/nuxt',
        '@nuxtjs/web-vitals',
        'nuxt-icon'
    ],
```


![Screenshot 2023-03-03 at 14 38 37](https://user-images.githubusercontent.com/542319/222748418-518f7ba4-2a7f-43f2-bd0e-26f9fd54b9c9.png)

**Comment by danielroe** [comment]
I believe this to be an issue with `nuxt-config-schema` (a dependency of `nuxt-icon`) which has been resolved in https://github.com/nuxt-experiments/nuxt-config-schema/pull/6. Try refreshing your lockfile or pinning your version of `nuxt-config-schema` to v0.4.5. If that doesn't work, I'd appreciate a reproduction and I'll reopen. 🙏

**Comment by jontybrook** [comment]
Thanks. Refreshing lockfile resolved this for me.
