### ISSUE TITLE
Server render incorrectly when nesting `<a>` tags

### ISSUE THREAD

**Issue by otomad** [nuxt/nuxt#19413]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v19.0.1`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `plugins`, `modules`, `alias`, `css`, `vite`, `vue`, `i18n`, `content`, `imports`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.9`, `@nuxt/content@2.4.3`, `nuxt-icons@3.1.0`, `@vueuse/nuxt@9.12.0`, `modules/theme/module.ts`, `modules/noscript/module.ts`, `modules/components-globalized/module.ts`, `@nuxtjs/robots@3.0.0`, `nuxt-simple-sitemap@1.0.6`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-zg6e6i?file=app.vue

### Describe the bug

When nesting `<a>` tags, server will render incorrectly, however client render correctly.

For example:
```html
<a style="display: block;">
    foo
    <a>bar</a>
</a>
```

server rendered:
```html
<a style="display: block;"> foo </a>
<a>bar</a>
```

Refresh the page, and you'll see it instantly displayed as
```
foo
bar
```

After the page loaded, it will display correctly
```
foo bar
```

If the actual page layout is more complex, this may even lead to page layout disorder.

### Additional context

Make a card link component, click the card to navigate to one link, click a text on the card to navigate to another link. Due to this bug, this will make it difficult to do.

**Comment by danielroe** [comment]
It's not valid HTML to nest `<a>` tags, and your browser is 'fixing' this for you by ending the first `<a>` tag before the next. But unfortunately this breaks Vue hydration and is causing the issue: see https://vuejs.org/guide/scaling-up/ssr.html#hydration-mismatch. You can use a library like https://github.com/nuxt-modules/html-validator to detect invalid HTML usage, which may help.
