### ISSUE TITLE
File not found when creating/removing files in `~/server/api` folder

### ISSUE THREAD

**Issue by ozum** [nuxt/nuxt#19425]
### Environment

- Operating System: `Darwin`
- Node Version:     `v19.6.1`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@9.4.0`
- Builder:          `vite`
- User Config:      `typescript`, `vite`, `imports`, `modules`, `build`, `ionic`, `prisma`, `runtimeConfig`
- Runtime Modules:  `./modules/nuxt-vue-query`, `nuxt-prisma@0.0.2`, `@nuxtjs/supabase@0.3.1`, `@nuxtjs/ionic@0.8.1`, `nuxt-icons@3.1.0`, `@formkit/nuxt@1.0.0-beta.15`, `nuxt-lodash@2.4.1`, `@pinia/nuxt@0.4.7`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-gn63da?file=modules/my-module/src/module.ts

Reporduce:
- Stop nuxt server.
- `cd modules/my-module`
- `npm install`
- `npm run dev:prepare`
- Start nuxt server.
- Create a file in `/server/api` directory: `/server/api/x.ts`
- Delete created file: `/server/api/x.ts`
- Watch the console to see the error. See video below.

### Describe the bug

If I delete a file from `/server/api` directory, `builder:watch` event in the Nuxt module generates an error given below as an example:

Error: Could not load /home/projects/github-gn63da/server/api/x.ts: ENOENT: no such file or directory, open '/home/projects/github-gn63da/server/api/x.ts'

### Additional context

https://user-images.githubusercontent.com/1497060/222873368-25a6293b-3ea8-4da6-8b92-3bb9cfa26875.mov

**Comment by danielroe** [comment]
I don't experience this issue with the reproduction you linked. Do you?

However, it feels like we might consider ignoring paths in the nitro serverDir anyway for perf - wdyt @pi0? It would be a breaking-ish change as users couldn't share code in `~/server` with their Vue apps ....

**Comment by ozum** [comment]
@danielroe, did you build `my-module` using `npm install` and `npm run dev:prepare` in the my-module directory?

I updated the reproduction section accordingly. Also added a video to the first post. Please see.

**Comment by danielroe** [comment]
This can be triggered directly by creating/removing files in the `~/server/api` folder - I don't think it requires a module. It's coming from Nitro and seems harmless - I think it's a race condition as nitro rebuilds before it's updated the list of scanned handlers.

**Comment by danielroe** [comment]
If you're still experiencing this, would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏

If it only recurs with Nuxt, let me know and I'll reopen it here.
