### ISSUE TITLE
Auto imported component types do not work

### ISSUE THREAD

**Issue by ymansurozer** [nuxt/nuxt#19427]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@9.4.0`
- Builder:          `vite`
- User Config:      `alias`, `app`, `build`, `imports`, `modules`, `naiveUI`, `ssr`, `supabase`, `runtimeConfig`, `tailwindcss`, `typescript`
- Runtime Modules:  `@vueuse/nuxt@9.13.0`, `@nuxtjs/tailwindcss@6.4.1`, `@pinia/nuxt@0.4.7`, `@nuxtjs/critters@0.4.0`, `@nuxtjs/fontaine@0.2.4`, `@nuxtjs/google-fonts@3.0.0-1`, `@nuxt/image-edge@1.0.0-27954023.4cee565`, `nuxt-headlessui@1.1.1`, `@nuxtjs/supabase@0.3.1`, `@formkit/nuxt@1.0.0-beta.15`, `@huntersofbook/naive-ui-nuxt@0.7.1`  
- Build Modules:    `-`

### Reproduction

I am sorry to open this without a reproduction, but I simply cannot reproduce this. It happens in a specific repo, and I have tried thousands of things, though cannot find what causes the issue. 

I am opening this issue so that people can weigh in and if there are others experiencing this, they can use the hack I've found (see below).

### Describe the bug

Auto import of my components work great. But their types are not recognized in VS Code. Whenever I hover over a component in the `<template>` section of an SFC, its type is indicated as `any`. 

It is very weird but I've found a hack: When I reference the `.nuxt/components` path anywhere in the project, the types start working. So I added this line to my `app.vue` file:

```
import {} from ".nuxt/components";
``` 

I think something is causing Nuxt to ignore the `.nuxt/components` path but when I reference it somewhere, Nuxt starts recognizing it back.

I'd be forever grateful if someone knows what is going on here and suggest where to look.

**Comment by danielroe** [comment]
Do you have a tsconfig.json extending from the Nuxt-generated config? https://nuxt.com/docs/guide/directory-structure/tsconfig

**Comment by ymansurozer** [comment]
Thanks @danielroe! I do have that. But it seems I've found the reason now.

The types are apparently lost when I define a custom FormKit component in my `formkit.config.js`.  I am using the official FormKit Nuxt module but the issue persists. I'll open an issue in their repo now.

**Comment by danielroe** [comment]
Feel free to tag me in it. We fixed a similar issue recently...
