### ISSUE TITLE
The requested module '/_nuxt/node_modules/.vite/deps/vue.js does not provide an export named 'Component'

### ISSUE THREAD

**Issue by palachX** [nuxt/nuxt#19443]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@8.19.0`
- Builder:          `vite`
- User Config:      `ssr`, `runtimeConfig`, `experimental`, `app`, `nitro`, `css`, `vite`, `modules`, `apiParty`
- Runtime Modules:  `nuxt-jsonld@2.0.7`, `@nuxt/image-edge@1.0.0-27954023.4cee565`, `nuxt-api-party@0.9.4`
- Build Modules:    `-`

### Reproduction

Sorry i can't give u links on project

### Describe the bug

When i update 3.1.2 on 3.2.0 i have error
The requested module '/_nuxt/node_modules/.vite/deps/vue.js?v=f21a0b11' does not provide an export named 'Component'  (at imports.mjs:4:716)

### Additional context

my packages:
  "dependencies": {
    "bootstrap": "^5.2.3",
    "dotenv": "^16.0.3",
    "nuxt-jsonld": "^2.0.7",
    "sass": "^1.58.3",
    "sass-loader": "^13.1.0",
    "swiper": "^9.1.0"
  },
  "devDependencies": {
    "@intlify/unplugin-vue-i18n": "^0.8.2",
    "@nuxt/image-edge": "^1.0.0-27954023.4cee565",
    "nuxt": "3.2.3",
    "nuxt-api-party": "^0.9.4",
    "vue-i18n": "^9.2.2"
  }

### Logs

```shell-script
vue-router.js?v=f21a0b11:2494 SyntaxError: The requested module '/_nuxt/node_modules/.vite/deps/vue.js?v=f21a0b11' does not provide an export named 'Component' (at imports.mjs:4:716)
triggerError @ vue-router.js?v=f21a0b11:2494
(anonymous) @ vue-router.js?v=f21a0b11:2281
Promise.catch (async)
pushWithRedirect @ vue-router.js?v=f21a0b11:2272
push @ vue-router.js?v=f21a0b11:2208
install @ vue-router.js?v=f21a0b11:2556
use @ chunk-UZOEE643.js?v=f21a0b11:3861
(anonymous) @ router.mjs?v=f21a0b11:46
fn @ nuxt.mjs?v=f21a0b11:149
callWithNuxt @ nuxt.mjs?v=f21a0b11:154
applyPlugin @ nuxt.mjs?v=f21a0b11:100
applyPlugins @ nuxt.mjs?v=f21a0b11:109
await in applyPlugins (async)
initApp @ entry.mjs:39
(anonymous) @ entry.mjs:55
nuxt.mjs?v=f21a0b11:74 [nuxt] error caught during app initialization SyntaxError: The requested module '/_nuxt/node_modules/.vite/deps/vue.js?v=f21a0b11' does not provide an export named 'Component' (at index.mjs?v=f21a0b11:128:15)
(anonymous) @ nuxt.mjs?v=f21a0b11:74
(anonymous) @ index.mjs?v=f21a0b11:39
Promise.then (async)
(anonymous) @ index.mjs?v=f21a0b11:39
serialCaller @ index.mjs?v=f21a0b11:39
callHookWith @ index.mjs?v=f21a0b11:158
callHook @ index.mjs?v=f21a0b11:148
showError @ error.mjs?v=f21a0b11:9
fn @ nuxt.mjs?v=f21a0b11:149
callWithNuxt @ nuxt.mjs?v=f21a0b11:154
(anonymous) @ router.mjs?v=f21a0b11:80
executeAsync @ index.mjs?v=f21a0b11:92
(anonymous) @ router.mjs?v=f21a0b11:80
await in (anonymous) (async)
fn @ nuxt.mjs?v=f21a0b11:149
callWithNuxt @ nuxt.mjs?v=f21a0b11:154
applyPlugin @ nuxt.mjs?v=f21a0b11:100
applyPlugins @ nuxt.mjs?v=f21a0b11:109
await in applyPlugins (async)
initApp @ entry.mjs:39
(anonymous) @ entry.mjs:55
vue-router.js?v=f21a0b11:2494 SyntaxError: The requested module '/_nuxt/node_modules/.vite/deps/vue.js?v=f21a0b11' does not provide an export named 'Component' (at imports.mjs:4:716)
triggerError @ vue-router.js?v=f21a0b11:2494
(anonymous) @ vue-router.js?v=f21a0b11:2281
Promise.catch (async)
pushWithRedirect @ vue-router.js?v=f21a0b11:2272
push @ vue-router.js?v=f21a0b11:2208
replace @ vue-router.js?v=f21a0b11:2211
(anonymous) @ router.mjs?v=f21a0b11:149
_function @ index.mjs?v=f21a0b11:102
(anonymous) @ index.mjs?v=f21a0b11:39
Promise.then (async)
(anonymous) @ index.mjs?v=f21a0b11:39
serialCaller @ index.mjs?v=f21a0b11:39
callHookWith @ index.mjs?v=f21a0b11:158
callHook @ index.mjs?v=f21a0b11:148
initApp @ entry.mjs:45
await in initApp (async)
(anonymous) @ entry.mjs:55
nuxt.mjs?v=f21a0b11:74 [nuxt] error caught during app initialization SyntaxError: The requested module '/_nuxt/node_modules/.vite/deps/vue.js?v=f21a0b11' does not provide an export named 'Component' (at index.mjs?v=f21a0b11:128:15)
(anonymous) @ nuxt.mjs?v=f21a0b11:74
(anonymous) @ index.mjs?v=f21a0b11:39
Promise.then (async)
(anonymous) @ index.mjs?v=f21a0b11:39
serialCaller @ index.mjs?v=f21a0b11:39
callHookWith @ index.mjs?v=f21a0b11:158
callHook @ index.mjs?v=f21a0b11:148
showError @ error.mjs?v=f21a0b11:9
fn @ nuxt.mjs?v=f21a0b11:149
callWithNuxt @ nuxt.mjs?v=f21a0b11:154
(anonymous) @ router.mjs?v=f21a0b11:156
await in (anonymous) (async)
_function @ index.mjs?v=f21a0b11:102
(anonymous) @ index.mjs?v=f21a0b11:39
Promise.then (async)
(anonymous) @ index.mjs?v=f21a0b11:39
serialCaller @ index.mjs?v=f21a0b11:39
callHookWith @ index.mjs?v=f21a0b11:158
callHook @ index.mjs?v=f21a0b11:148
initApp @ entry.mjs:45
await in initApp (async)
(anonymous) @ entry.mjs:55
```

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by palachX** [comment]
> Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

excuse me, I understand how much you need the code, but I cannot disclose and transfer the code according to the rules of my company.

**Comment by danielroe** [comment]
I'm not asking for your company's code, but rather, you can follow the steps in the link I posted to reproduce the issue.

**Comment by palachX** [comment]
I will try to find out which of the components the error is in myself, using the exception method and let you know)

**Comment by palachX** [comment]
> I'm not asking for your company's code, but rather, you can follow the steps in the link I posted to reproduce the issue.

Yes, it says the minimum code to reproduce the error, but I do not know which of the components is loaded incorrectly.
I will try to find out which of the components the error is in myself, using the exception method and let you know)

**Comment by palachX** [comment]
Yeap i find
I use in one file import

import {useAppConfig} from "#build/imports";

Sorry for wasting your time, I hope this will help someone. It made me sweat)

**Comment by danielroe** [comment]
I'm glad you were able to find it 😊❤️
