### ISSUE TITLE
Duplicate meta with same property when using app.head.meta/useHead for OGP arrays (og:locale:alternate)

### ISSUE THREAD

**Issue by MusicOnline** [nuxt/nuxt#19456]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-zrkkt5?file=app.vue

### Describe the bug

When attempting to recreate the following using `app.head.meta` or `useHead`, undesired duplicates occur.
How tags are selected to be duplicated is unknown.

Reproduction:
```vue
<script setup>
useHead({
  meta: ['en_US', 'ja_JP', 'ko_KR', 'zh_CN', 'zh_TW'].map((locale) => ({
    property: 'og:locale:alternate',
    content: locale,
  })),
});
</script>
```

Desired output:
```html
<meta property="og:locale:alternate" content="en_US">
<meta property="og:locale:alternate" content="ja_JP">
<meta property="og:locale:alternate" content="ko_KR">
<meta property="og:locale:alternate" content="zh_CN">
<meta property="og:locale:alternate" content="zh_TW">
```

Result as in reproduction link:
```html
<meta property="og:locale:alternate" content="en_US">
<meta property="og:locale:alternate" content="ja_JP">
<meta property="og:locale:alternate" content="ko_KR">
<meta property="og:locale:alternate" content="zh_CN">
<meta property="og:locale:alternate" content="en_US">
<!-- Other head children... -->
<meta property="og:locale:alternate" content="ja_JP">
<meta property="og:locale:alternate" content="ko_KR">
<meta property="og:locale:alternate" content="zh_CN">
<meta property="og:locale:alternate" content="zh_TW">
```

Another possible result (not in reproduction link):
```html
<meta property="og:locale:alternate" content="en_US">
<meta property="og:locale:alternate" content="ja_JP">
<meta property="og:locale:alternate" content="ko_KR">
<meta property="og:locale:alternate" content="zh_CN">
<meta property="og:locale:alternate" content="en_US">
<!-- Other head children... -->
<meta property="og:locale:alternate" content="zh_TW">
```

When using `<Meta>` components, only the last component with the same property name takes effect.

**Comment by danielroe** [comment]
You can use a `key` to deduplicate these.

**Comment by MusicOnline** [comment]
> You can use a `key` to deduplicate these.

Sorry, where do I use `key`? I don't think it's in the docs and `<Meta key="...">` doesn't show each uniquely keyed meta tag with the same property name (the last takes effect).

**Comment by danielroe** [comment]
Like this:

```vue
<script setup>
useHead({
  meta: ['en_US', 'ja_JP', 'ko_KR', 'zh_CN', 'zh_TW'].map((locale) => ({
    key: locale,
    property: 'og:locale:alternate',
    content: locale,
  })),
});
</script>
```

**Comment by manniL** [comment]
As a small addendum: When possible, meta duplication is already happening, but whenever multiple values are allowed (e.g. for favicons or for alternate og locales), it will not and you have to use the `key` if you expect duplicates ☺️
