### ISSUE TITLE
type auto-imports from user directories

### ISSUE THREAD

**Issue by katerlouis** [nuxt/nuxt#19467]
### Environment

- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@8.1.2`
- Builder:          `vite`
- User Config:      `srcDir`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/katerlouis/nuxt-auto-import-types

### Describe the bug

A function exported from file `@/utils/tonal.ts` is auto-imported correctly and working as expected,
but a type exported from the same file is causing an error

**Comment by danielroe** [comment]
Type auto-imports are not yet implemented except for the following core vue types:

https://github.com/nuxt/nuxt/blob/9a035a15c5035e609ba20ef3106c79d733992e86/packages/nuxt/src/imports/presets.ts#L146-L158

**Comment by katerlouis** [comment]
Thx @danielroe – Good to know. I assume "yet" implies that it's coming. Would you mind explaining why that is? What makes this more complex than auto importing the "other exports" in these files? (As you can see, I just started dipping my toes into actually using TypeScript)

**Comment by citriqa** [comment]
Am I correct in my assumption that this is also why Enums have to be manually imported in components to be usable as prop definitions?
