### ISSUE TITLE
Question - useAsyncData always return null if  api returns object instead of list

### ISSUE THREAD

**Issue by sunny-repo88** [nuxt/nuxt#19464]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v18.14.1`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@9.3.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:

### Reproduction

Link to reproduce: https://stackblitz.com/edit/github-zqny2p

### Describe the bug

correct way to use `useAsyncData ` if api return object of list instead of list?

```
<script setup>
const { data: posts } = await useAsyncData(() => $fetch('/api/posts'));
</script>
```

`'/api/posts'`  
return `['post1', 'post2'] `- working fine

`'/api/posts2'`  
return `{'result':['post1', 'post2']}` - how to use `useAsyncData`

**Comment by danielroe** [comment]
This is a JS syntax question:

```js
export default defineEventHandler(() => {
  results: [
    {
      userId: 1,
      id: 1,
      title:
        'sunt aut facere repellat provident occaecati excepturi optio reprehenderit',
      body: 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto',
    }
  ];
});
```

should be:


```js
export default defineEventHandler(() => ({
  results: [
    {
      userId: 1,
      id: 1,
      title:
        'sunt aut facere repellat provident occaecati excepturi optio reprehenderit',
      body: 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto',
    }
  ];
}));
```
