### ISSUE TITLE
useSeoMeta ogSiteName uses wrong property (og:site:name instead of og:site_name)

### ISSUE THREAD

**Issue by MusicOnline** [nuxt/nuxt#19460]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-kxskl5?file=app.vue

### Describe the bug

The [Open Graph protocol](https://ogp.me/) specifies `property="og:site_name"`, and yet Nuxt writes `og:site:name` to the head when using `useSeoMeta`. I assume this is due to automatic conversion, but this unexpected behavior should be fixed considering there's typing available for `ogSiteName`.

**Comment by danielroe** [comment]
cc: @harlan-zw

**Comment by manniL** [comment]
@danielroe already on it
