### ISSUE TITLE
payloadExtraction does not work for alternate URL (with/without trailing slash) when using catchall

### ISSUE THREAD

**Issue by fahmifitu** [nuxt/nuxt#19478]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Run the following:
```
npm run generate
npm run preview
```
- Set browser network to Slow 3G to make the issue clearer

https://stackblitz.com/edit/github-d1s7rg?file=pages/[...slug].vue

### Describe the bug

Journey 1: navigating "No Trailing Slash links"
navigation is snappy. no api calls on initial visits or internal routing.
No issues here. 

Journey 2: navigating from "No Trailing Slash links" to "Trailing Slash links" internally
- Request is executed. page waits for the payload to be fetched from the api.  this seems to only happen with dynamic pages. 
- Browsing a static page will not cause a fetch request. check /test and /test/
--  I noticed that in the fetch, the `pending` flag of `useFetch` is never true even though the request is fetching in the background.

- Going back and forth to trailing slash dynamic pages will fetch the page request each time. but note that this is not consistent. 
-- Reproduce by: index page => trailing /blog/ => trailing /support/ => trailing /blog/
<img width="488" alt="Screenshot 2023-03-06 at 12 05 45 PM" src="https://user-images.githubusercontent.com/24812043/223079321-c7c0a9bf-7f77-45a1-8416-12de79cfbed6.png">
-- But sometimes it doesn't do that for some reason: try index page => trailing /blog/ => trailing /support/ => trailing /careers/. requests are only executed on initial visits. going back to any page after this journey will load instantly.

- Doesn't reproduce on static pages.

Journey 3: Initially visiting Trailing Slash link
- Page payload exists in the beginning. but the request is executed anyway.
- Fetch flag is set to true as it should.
- Doesn't reproduce on static pages.

I have another reproduction [here](https://wp-frontend.surge.sh)
details and reproduction steps: [Discord thread](https://discord.com/channels/473401852243869706/1078259283579387954/1078259283579387954)

@manniL tagged based on your request

**Comment by danielroe** [comment]
oops 😆

**Comment by manniL** [comment]
It seems that the auto key from `useAsyncData` does not match the payload data key in these cases.

**Comment by fahmifitu** [comment]
Thanks for investigating the issue and providing a workaround. I will definitely apply to my project.

I think the issue boils down to the following:

- if `/careers` payload key is different than `/careers/`. the payload shouldn't be instantly available in the page while also a request is happening.
- if both links exist in the markup, shouldn't both urls be crawled and pre-generated? since they're treated as different pages internally while crawling.

**Comment by manniL** [comment]
> if both links exist in the markup, shouldn't both urls be crawled and pre-generated? since they're treated as different pages internally while crawling.

I just wanted to add that this is the case (hence the different keys), but only one represantation will be actually saved. So for prerendering, trailing and non-trailing versions are treated the same (and they *should* be the same), but when using the `fullPath`, for parameters, this is not the case.

**Comment by fahmifitu** [comment]
You're absolutely right. I think I get it now. I confused myself thinking the data in the pre tag is an indicator that the payload is loaded instantly. but it's just an html generated from the /careers/ (or /careers) payload which is never matched later when visiting the page.

**Comment by danielroe** [comment]
Yes, this is a tricky one. I think where people are manually providing their own key then there is little we can do to handle a trailing slash in the URL. (I don't think we want to manipulate the route object to remove the trailing slash, for example.) Other ideas would be very welcome though.

**Comment by manniL** [comment]
> (I don't think we want to manipulate the route object to remove the trailing slash, for example.)

I agree, this seems too risky in terms of side effects to me too.

**Comment by manniL** [comment]
Closing here for now as any ideas on how to interfere/rectify would be more disruptive than helpful. If **you** are reading this and have an idea - comment please!
