### ISSUE TITLE
Nuxt doesn't recognize newly created files inside `pages`

### ISSUE THREAD

**Issue by zerosdev** [nuxt/nuxt#19479]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.1.2`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `modules`, `device`, `auth`
- Runtime Modules:  `@nuxt-alt/auth@2.1.9`, `@pinia/nuxt@0.4.6`, `@nuxtjs/device@3.0.0`, `bootstrap-vue-next/nuxt`
- Build Modules:    `-`
------------------------------

### Reproduction

- Run `npm run dev`
- Create new file inside `pages` an fill it as normal page
- Access that page in the browser

### Describe the bug

I'm running `npm run dev`, when any files are updated it will rebuild nuxt so the changes are shown in the browser. But when i create a new file inside `pages` it seems nuxt doesn't recognize the new page until i restart nuxt so i get error 404 when accessing that page

**Comment by zerosdev** [comment]
i use Nuxt 3.0.0 as in the environment info

**Comment by danielroe** [comment]
I mean, it has been resolved _after_ 3.0.0. We're now on 3.2.3.
