### ISSUE TITLE
Content loading behavior of page transitions

### ISSUE THREAD

**Issue by noriyuki-shimizu** [nuxt/nuxt#19471]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.1.0`
- Package Manager:  `pnpm@7.26.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

The screen transition behavior differs depending on the layout component specified in the following pages.

* When the same layout component is used for the page transition source and the page transition destination
* When different layout components are used for the page transition source and the page transition destination

### Describe the bug

Please allow me to confirm the behavior of screen transitions with `<NuxtLink>`!
When I was developing with Nuxt3, I found the following differences in behavior during screen transitions.

* When the same layout component is used for both the page transition source and the page transition destination
  * The page transition source reads the content of the page transition destination before transitioning to the next page.

```ts
// AComponent.vue
definePageMeta({
  layout: 'layout-1'
})

// BComponent.vue
definePageMeta({
  layout: 'layout-1'
})
```

* If different layout components are used for the source and destination of a page transition
  * After the page transition, the content of the destination page is loaded and displayed on the screen.

```ts
// AComponent.vue
definePageMeta({
  layout: 'layout-1'
})

// BComponent.vue
definePageMeta({
  layout: 'layout-2'
})
```

The difference in the above behavior was not present in Nuxt2.
Is it a specification that the above behavior is the same from Nuxt3?
If possible, I would like the behavior of screen transitions to be the same as in Nuxt2.

Please check :bow:

**Comment by mwohlan** [comment]
Could this be related to #13370 ?

**Comment by noriyuki-shimizu** [comment]
@mwohlan 
Thanks for the reply!
I'm not sure if this is related to #13370, but I will check with the version that fixes that issue!
If it is fixed, would it be a problem to go through the process of closing this issue?

**Comment by noriyuki-shimizu** [comment]
It was fixed, so I'm closing this issue.
