### ISSUE TITLE
Modules being disabled due to incompatibility @edge-channel

### ISSUE THREAD

**Issue by mwohlan** [nuxt/nuxt#19488]
### Environment

Stackblitz using nuxt3@edge

### Reproduction

https://stackblitz.com/edit/github-8oct97?file=nuxt.config.ts

### Describe the bug

I used the pinia and fontaine module to demonstrate the issue. Both modules
are being disabled with the following kind of message:
> Module pinia is disabled due to incompatibility issues:
> [nuxt] Nuxt version `^2.0.0 || ^3.0.0-rc.5` is required but currently using `3.3.0-27968571.4f61e36c6`

**Comment by danielroe** [comment]
This should already be resolved in the latest edge channel kit, but I think we could also update the release script to avoid this.

**Comment by mwohlan** [comment]
You already mentioned it in your stream, thats why i wondered. The reproduction is using the latest 4f61e36 commit which includes the commit hash fix.

**Comment by danielroe** [comment]
Ah. Likely the issue is that there are multiple versions of kit in the project, some without the fix. More and more, I think we probably have to override the generated hash to conform to one that old kit versions will work with.
