### ISSUE TITLE
Enable `injectAtEnd` from `unimport`

### ISSUE THREAD

**Issue by antfu** [nuxt/nuxt#19480]
### Describe the feature

Currently, `unimport` always injects the imports at the beginning of the file. This sometimes creates confusing circular reference errors, or alters the order of the imports.

To improve this, I implemented `injectAtEnd` feature (https://github.com/unjs/unimport/commit/6b1ba9149f519742ffafe91497bc3feec905b1b7) on unimport but not enabled by default yet.

https://github.com/unjs/unimport/blob/1be4b7baba7af772ea863f2bfe529daa2830bc12/src/types.ts#L256-L261

Enabled on https://github.com/antfu/unplugin-auto-import by default and it does solve some circular reference issues. So far, I guess it works for most of the cases, and only a potential bug needs to be investigated: https://github.com/antfu/unplugin-auto-import/pull/327

Creating this issue to raise this up, and see if you think it something worth to have in the next minor or so.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Let's go ahead with this for v4.
