### ISSUE TITLE
app/router.options.ts

### ISSUE THREAD

**Issue by Dinuz** [nuxt/nuxt#19491]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@9.4.0`
- Builder:          `vite`
- User Config:      `debug`, `ssr`, `css`, `build`, `vite`, `hooks`, `sourcemap`, `modules`, `googleFonts`, `apollo`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/apollo@5.0.0-alpha.5`, `@nuxtjs/google-fonts@3.0.0-1`, `@vueuse/nuxt@9.13.0`
- Build Modules:    `-`

### Reproduction

no needed

### Describe the bug

The bug is very simple, and easy to understand.
I have a pages folder, where I placed 3 pages: index, terms, privacy.
The automatic routing system works properly and everything is fine, until I decide to rename the index page.
To rename the index page I add an app folder and place inside the file router.options.ts (following the nuxt documentation) with the following code:

```
import type { RouterConfig } from '@nuxt/schema'
// https://router.vuejs.org/api/interfaces/routeroptions.html
export default <RouterConfig>{
  routes: (_routes) => [
    {
      name: 'home',
      path: '/',
      component: () => import('~/pages/home.vue'),
    },
  ],
}
```

This allows me to rename the index page home, and the app continues to work, except now I get a warning that the routes /terms and /privacy don't exist. Indeed if I try to navigate to the same pages I receive the 404 message.

If I add for example the terms route to the router.options.ts file, the warning for the page terms disappears and I can navigate to the page normally.

Shouldn't the file router.options.ts only overwrite some routes optionally? or it is designed in a way that when used for one route it must be used for all the other too?
If it is the latest I do feel it is a bug.

**Comment by danielroe** [comment]
The file must return _all_ routes. You receive them as an array (`_routes` in your example above) and must return an array. This allows full flexibility.

You can also use the `pages:extend` hook which might be more appropriate for your use case.

**Comment by Dinuz** [comment]
@danielroe Thank you so much:)) I was going insane lol! Would be opportune adding this in the documentation? It is not so explicit and clear

**Comment by danielroe** [comment]
For sure!
