### ISSUE TITLE
`/server/api/[slug].post.ts` returns 405 Method Not Allowed while using $fetch in `netlify-builder`

### ISSUE THREAD

**Issue by varna** [nuxt/nuxt#19505]
### Environment

production build on fresh `netlify-builder`:
```
1:55:41 PM: [log] Nuxi 3.2.3
1:55:42 PM: [log]
1:55:42 PM: [log] RootDir: /opt/build/repo
1:55:42 PM: [log] Nuxt project info:
1:55:42 PM: ------------------------------
1:55:42 PM: - Operating System: `Linux`
1:55:42 PM: - Node Version:     `v16.19.1`
1:55:42 PM: - Nuxt Version:     `3.2.3`
1:55:42 PM: - Nitro Version:    `2.2.3`
1:55:42 PM: - Package Manager:  `npm@8.19.3`
1:55:42 PM: - Builder:          `vite`
1:55:42 PM: - User Config:      `-`
1:55:42 PM: - Runtime Modules:  `-`
1:55:42 PM: - Build Modules:    `-`
1:55:42 PM: ------------------------------
```

### Reproduction

repro: https://stackblitz.com/edit/nuxt-starter-tocoqh?file=app.vue
repo: https://github.com/varna/nuxt-api-post-405
demo: https://idyllic-faloodeh-fdaff1.netlify.app/

### Describe the bug

While using `NITRO_PRESET=netlify-builder`

When deployed (in dev mode bug doesn't reproduce) to Netlify with `netlify-builder` using POST method $fetch on server api with suffix `.post` fails with `405 Method Not Allowed`.

- `/server/api/message.post.ts`
- `useFetch('/api/message', { method: 'POST', body })` :white_check_mark:
- `$fetch('/api/message', { method: 'POST', body })` :x:

### Additional context

This is probably nitro bug, not nuxt. I'm suspicious why `useFetch` works while `$fetch` doesn't.

**Comment by danielroe** [comment]
I wonder if this reproduces if you use `useRequestEvent().$fetch`?

cc: @pi0

**Comment by varna** [comment]
My "quick hack" was to rename `message.post.ts` to `message.ts`. Unfortunately, I got a new bug report, that it keeps failing with 405.

**Comment by varna** [comment]
I updated the repro. It seems that this is a CORS issue.

After deploying to Netlify `access-control-allow-methods` and `access-control-allow-origin: *` headers are missing.

**Comment by varna** [comment]
Closing this issue because it is only a side affect of another issue https://github.com/nuxt/nuxt/issues/19774
