### ISSUE TITLE
problems using Nitro with Pinia + PiniaPersist

### ISSUE THREAD

**Issue by JosukeH** [nuxt/nuxt#19512]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `yarn@3.4.1`
- Builder:          `vite`
- User Config:      `vite`, `modules`, `imports`, `typescript`, `rootDir`, `alias`, `tailwindcss`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.3.1`, `nuxt-headlessui@1.1.1`, `@pinia/nuxt@0.4.7`, `@vueuse/nuxt@9.12.0`, `@pinia-plugin-persistedstate/nuxt@1.0.0`, `@nuxtjs/device@3.1.0`
- Build Modules:    `-`
------------------------------

### Reproduction

na

### Describe the bug

Hi i´m facing some problems creating my auth middleware on nuxt using pinia and JWT  the problem is when I use a protected.ts middleware where I need to protect (you need to log in to see this pages)

but in nested deep routes this middleware don´t works. seem like the Pinia is providing my initial state instead of the session who I set before login.

**Comment by JosukeH** [comment]
This is my middleware who protecs my routes.
```
export default defineNuxtRouteMiddleware(async () => {
  const authStore = useAuthsStore();
  console.log(authStore.$state);

  const { data } = await useFetch(`/api/read/${authStore.id}`, {
    method: "POST",
  });

  console.log(authStore.id);
  console.log(data);

  if (!data.value.auth) {
    return navigateTo({ path: "/" }, { replace: true });
  }
  return true;
});

```

making the instance it brings me the default state of my pinia this looks like this.


```
export const useAuthsStore = defineStore("auth", {
  state: (): Auth => ({
    name: "",
    id: 0,
    auth: false,
    error: false,
  }),
  actions: {
    setUser(newUser) {
      this.$patch(newUser);
    },
  },
  persist:
    {
      storage: persistedState.localStorage,
    },
});

```
hope anyone can help me. as I mentioned this works on the main routes but in the nested and deep routes of my /pages this don´t works.

**Comment by adrienZ** [comment]
from the [docs](https://prazdevs.github.io/pinia-plugin-persistedstate/frameworks/nuxt-3.html): 
![image](https://user-images.githubusercontent.com/10186993/233773696-e3f885c6-2ff0-4dbc-b28f-8e44232f9c0a.png)

You're middleware is server side so it can't access your state, you want to use cookies instead.

That being said, I don't think your issue is related to Nuxt itself
