### ISSUE TITLE
`v-html` on component only works in HMR

### ISSUE THREAD

**Issue by DrJume** [nuxt/nuxt#19516]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.19.1`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.3`
- Package Manager:  `pnpm@7.29.0`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `typescript`, `modules`, `css`, `schemaOrg`, `imports`, `nitro`, `hooks`, `app`, `vite`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.4.1`, `@vueuse/nuxt@9.13.0`, `nuxt-schema-org@2.1.2`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-f4jttv?file=app.vue

1. Comment `<NuxtWelcome />`
2. Uncomment `<NuxtWelcome v-html="html" />`
3. The preview should HMR and show "Hello World"
4. Reload the preview --> No "Hello World"

### Describe the bug

Overriding the innerHTML of a component with `v-html` (which works in Vue.js) only applies the innerHTML on HMR. When reloading the page, Nuxt ignores the `v-html`.

**Comment by danielroe** [comment]
This is a Vue 3 SSR bug and can be tracked here: https://github.com/vuejs/core/issues/6435.
