### ISSUE TITLE
The requested page still loads when making a redirection via route middleware (nuxt 3.2.2 with ssr disabled)

### ISSUE THREAD

**Issue by duc2019** [nuxt/nuxt#19549]
### Environment

Nuxt 3.2.2 with ssr: false and nitro.preset: 'service-worker'

### Reproduction

- Create a project with nuxt 3.2.2
- Set ssr: false and nitro.preset: 'service-worker'
- Add a.vue and b.vue
- Add a global middleware redirects a to b
- add alert('a executed') in a.vue's setup script
- open a
It will show the alert before redirect to b.

### Describe the bug

Several people has encounted this issue:

https://github.com/nuxt/nuxt/discussions/16124
https://github.com/nuxt/nuxt/discussions/16968
https://github.com/nuxt/nuxt/issues/14468

This is still not fixed.
I may create a minimum reproduce code later if you guys can't reproduce it.

**Comment by danielroe** [comment]
This is not reproducible for me: https://stackblitz.com/edit/github-3enzca.

Let me know with a reproduction and I'll happily reopen.
