### ISSUE TITLE
3.2.2 npm run build linux server success,3.2.3 npm run build linux server error,

### ISSUE THREAD

**Issue by 15844229646** [nuxt/nuxt#19552]
### Environment

- Operating System: `Linux`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `yarn@1.22.4`
- Builder:          `vite`
- User Config:      `webpack`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

x

### Describe the bug

I have written two projects with nuxt3, one of which is version 3.2.2. The project has been launched and can run normally (Thank the maintenance personnel again),

Last Friday, I upgraded 3.2.3 to write the second project. npm run dev was successful and npm run build was successful. When I deployed the project on the same server
```
ubuntu@VM-4-10-ubuntu:/node/newTeam$ node server/index.mjs
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'node-fetch-native' imported from /node/newTeam/server/index.mjs
    at new NodeError (node:internal/errors:393:5)
    at packageResolve (node:internal/modules/esm/resolve:860:9)
    at moduleResolve (node:internal/modules/esm/resolve:909:20)
    at defaultResolve (node:internal/modules/esm/resolve:1124:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v18.12.1
```
My solution, I have tried in. output/server/ npm i node-fetch-native -- save

After solving the node-fetch-native, other modules may need to be installed.

I need official assistance

我是用nuxt3写过2个项目，一个版本为3.2.2，项目已经上线且可以正常运行.（再次感谢维护人员），
我在上周五，升级了3.2.3，来写第二个项目，npm run dev 成功，npm run build 成功，当我在同一台服务器，部署项目时，出现
```
ubuntu@VM-4-10-ubuntu:/node/newTeam$ node server/index.mjs
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'node-fetch-native' imported from /node/newTeam/server/index.mjs
    at new NodeError (node:internal/errors:393:5)
    at packageResolve (node:internal/modules/esm/resolve:860:9)
    at moduleResolve (node:internal/modules/esm/resolve:909:20)
    at defaultResolve (node:internal/modules/esm/resolve:1124:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v18.12.1
```
我的解决，我尝试过 在。output/server/下 npm i node-fetch-native --save 
解决 node-fetch-native 后，有会出现其他模块需要安装。
我需要官方的协助

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by 15844229646** [comment]
@danielroe https://gitee.com/WangJingXuan/new-team

**Comment by danielroe** [comment]
I can't reproduce using that repository. `.output/server/node_modules/node-fetch-native` is present as expected.

**Comment by tsulatsitamim** [comment]
same here
nuxt 3.2.3
node v18.14.0

```Cannot find module '/var/www/puzzle/node_modules/dayjs/plugin/utc' imported from /var/www/puzzle/.output/server/chunks/play.get.mjs\nDid you mean to import dayjs/plugin/utc.js```

dayjs package is present in node_modules

![Screenshot 2023-03-10 at 03 52 23](https://user-images.githubusercontent.com/5946791/224155401-c8193f50-9959-43e7-acbc-632bcfc7476f.jpg)

**Comment by alimozdemir** [comment]
I'm facing the same issue.

index.mjs file has the following 'node-fetch-native/polyfill' import
```index.mjs
globalThis._importMeta_={url:import.meta.url,env:process.env};import 'node-fetch-native/polyfill';
....
//# sourceMappingURL=index.mjs.map
```

And when I try to run `node ./output/server/index.mjs` it can't find the polyfill.js file in `node-fetch-native` package.

I have cleaned my repository and rebuilt it but it is the same.

Repository main `node_modules` has that file

![image](https://user-images.githubusercontent.com/4493134/224169272-2a22019f-4b80-4b8a-86e5-c779519d5ffb.png)

It does not exist in `.output/server/node_modules`

![image](https://user-images.githubusercontent.com/4493134/224169477-61b31485-a2f3-40be-86bb-cd62f240de7e.png)

**Comment by danielroe** [comment]
You may be able to work around by clearing your lockfile and reinstalling.

cc: @pi0

**Comment by alimozdemir** [comment]
Thank you @danielroe 

I deleted the lockfile and regenerate it, then it started to work,

**Comment by 15844229646** [comment]
当我在windows npm run build之后 直接运行 node ./output/server/index.mjs 是成功的，但是当我把.output 放到llinux服务器上时，会出现 Cannot find package 'node-fetch-native' imported from /node/newTeam/server/index.mjs

是否linux 中还需要什么操作吗

**Comment by 15844229646** [comment]
When I run node directly after Windows npm run build/ Output/server/index.mjs is successful, but when I put. output on the linux server, the package 'node fetch native' imported from/node/newTeam/server/index.mjs will not be found



Is there any other operation required in Linux

**Comment by 15844229646** [comment]
稍等我会发布一个视频，来复现我的操作，以及出现此问题。

**Comment by 15844229646** [comment]
@danielroe 
https://wwpc.lanzouf.com/i9pIu0pqn9aj //www
https://wwpc.lanzouf.com/i3JPz0pqn9la// arco


https://cloud.06dn.com/s/YVMMf7  //There are some problems with the online preview of the complete operation video download address and the local place to download.

The above is the packaged file of the two projects I demonstrated


https://cloud.06dn.com/s/YVMMf7//完整的操作视频下载地址，需要下载的本地，在线预览有些问题。

上面是我演示的2个项目打包后的文件.

**Comment by stj8888** [comment]
请问博主解决了吗

**Comment by stj8888** [comment]
![image](https://user-images.githubusercontent.com/106759204/231741342-45962ffa-e2c8-49d1-b1e3-f199151c6552.png)

**Comment by stj8888** [comment]
![image](https://user-images.githubusercontent.com/106759204/231741403-df4a15cd-b1d8-4f8a-ad48-c3aa535589d3.png)
我就是这个问题，请问怎么解决

**Comment by 15844229646** [comment]
@stj8888 
@danielroe 
没有解决，我更换版本就可以
后来我又找了下问题，
发现打包后，依赖包的名字变了，导致的错误
正常的打包 
axios.mjs
错误的结果
_axios.mjs
前缀多了一个 _ ，并且入口文件引入的 axios.mjs
所以导致找不到包 ，就会出现这个错误

**Comment by manniL** [comment]
It'd be great to have an up-to-date reproduction of this issue if it still exists
