### ISSUE TITLE
hello, why in production mode not work the 404 page iam set [...slug].vue in folder pages

### ISSUE THREAD

**Issue by ibrahim-990** [nuxt/nuxt#19554]
### Environment

hello, why in production mode not work the 404 page iam set [...slug].vue in folder pages

### Reproduction

hello, why in production mode not work the 404 page iam set [...slug].vue in folder pages

### Describe the bug

hello, why in production mode not work the 404 page iam set [...slug].vue in folder pages

**Comment by ibrahim-990** [comment]
nuxt3

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by ibrahim-990** [comment]
[](url)iam create [...slug].vue in folder page
and this page contain code to show 404 page
in development  mode the 404 page shown but when in production mode not shown i get.

/////
Not Found
The requested URL was not found on this server.

Apache/2.4.54 (Debian) Server at dce.sa Port 80
/////

**Comment by ibrahim-990** [comment]
just this work on development but on production not work,

**Comment by danielroe** [comment]
I would guess that you do not have a Nuxt server running in production but are probably running `nuxt generate` to deploy a static site?

**Comment by ibrahim-990** [comment]
yes just nuxt generate deploy a static site.

**Comment by danielroe** [comment]
In that case, Nuxt isn't responsible for sending a 404 page. You will need to configure your server to return `/200.html` to requests that don't match any files.

**Comment by ibrahim-990** [comment]
this just my code
[https://codesandbox.io/p/github/nuxt/starter/v3-codesandbox?file=%2FREADME.md&workspace=%257B%2522activeFileId%2522%253A%2522clf0y31du02oh356iyr8mg5sh%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%252C%2522%252Fpages%252F%255B...slug%255D.vue%2522%252C%2522%252Fnuxt.config.ts%2522%252C%2522%252Fpages%252Findex.vue%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clf0xu7l10013356jeb8ntoef%2522%253A%257B%2522key%2522%253A%2522clf0xu7l10013356jeb8ntoef%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522key%2522%253A%2522clf0y18dc000y356i2nqm3vq0%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clf0xu7l10013356jeb8ntoef%2522%252C%2522spacesOrder%2522%253A%255B%2522clf0xu7l10013356jeb8ntoef%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D](url)
