### ISSUE TITLE
page or component add to ignored list

### ISSUE THREAD

**Issue by productdevbook** [nuxt/nuxt#19577]
### Describe the feature

example
`components/app`, `pages/app`

When I add them to ignored and run with web, I don't want the structures I wrote for the app to work on build and dev.

![image](https://user-images.githubusercontent.com/38668796/224226129-43d5ab82-6346-4021-ab7f-3f0444b703b3.png)

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Would you explain a bit more about what you want and what you've tried?

**Comment by productdevbook** [comment]
```
  pages: {
    ignore: ['app'],
  },
```

For example, I want to block the app on pages. Because I only use it when building ionic and capacitor. If I can cancel /pages/app when I do pnpm generate, the page will shrink in mb.

It is also valid for components.

**Comment by danielroe** [comment]
Have you tried using `.nuxtignore` or the `ignore` property in Nuxt config?

**Comment by productdevbook** [comment]
Thank you, wow i like

```
  ignore: [
    'components/app/**/*',
    'pages/app/**/*',
  ],
```

**Comment by productdevbook** [comment]
`public/firebase-messaging-sw.js`

general files, this does not work, the file comes while building.

![image](https://user-images.githubusercontent.com/38668796/224557353-5c3d7ccf-8428-42a3-82e0-c47db3e337ba.png)
