### ISSUE TITLE
Nuxt 3 option to set localIdentName for css modules to reduce build size

### ISSUE THREAD

**Issue by lynxionxs** [nuxt/nuxt#19579]
### Describe the feature

Theres' no option in the Nuxt 3 documentation to set the ```localIdentName``` for css modules in ```.module.css``` files and vue component styles. To modify css class/id names and shorten them from ```.this-long-class-name``` to ```.m5_Uw``` to reduce build size. In Nuxt 2 it was possible. 
![Screenshot_2023-03-10_09-12-08](https://user-images.githubusercontent.com/7606938/224249615-09040293-664e-481f-86a8-d8e5fc5ef357.png)

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Have you tried `vite.css.modules.generateScopedName`?

**Comment by lynxionxs** [comment]
@danielroe so it has to be set in Vite config ? I will try that option. Thanks.

**Comment by danielroe** [comment]
You would set that in your `nuxt.config` file like this:

```js
export default defineNuxtConfig({
  vite: {
    css: {
      modules: {
        generateScopedName (name, filename, css) {
          //
        }
      }
    }
  }
})
```

**Comment by lynxionxs** [comment]
@danielroe that was helpful. Thanks.

**Comment by darbaoui** [comment]
@lynxionxs could you please share with us,  the body code of `generateScopedName` function, if it's worked with you.

**Comment by JoeTheCookie217** [comment]
> @lynxionxs could you please share with us, the body code of `generateScopedName` function, if it's worked with you.

bit late but here is an example
`generateScopedName: '[hash:base64:8]'`

**Comment by darbaoui** [comment]
But with tailwindcss and postCss doesnt works

**Comment by Vasily257** [comment]
Another option:
```
import crypto from 'crypto';
import { basename } from 'path';
```


```
export default defineNuxtConfig({
  ...,
  vite: {
    css: {
      modules: {
        generateScopedName: (name, filename, css) => {
          const fullName = basename(filename);
          const componentName = fullName.split('.vue')[0];
          const hash = crypto.createHash('md5').update(css).digest('hex').slice(0, 8);

          return componentName + '__' + name + '__' + hash; // TheHeader__header__0869a72e
        },
      },
    },
  },
});
```
