### ISSUE TITLE
Errore in compiled index.mjs while using bridge to upgrade

### ISSUE THREAD

**Issue by Alegalen** [nuxt/nuxt#19581]
### Environment

Nuxi 3.1.2

RootDir: *******
Nuxt project info:

------------------------------
- Operating System: ****
- Node Version:     `v16.13.2`
- Nuxt Version:     `2.16.2`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.1.2`
- Builder:          `webpack`
- User Config:      `bridge`, `head`, `css`, `plugins`, `components`, `buildModules`, `bootstrapVue`, `styleResources`, `ssr`, `target`, `modules`, `proxy`, `axios`, `auth`, `router`, `serverMiddleware`, `i18n`, `build`, `runtimeConfig`, `static`, `server`, `serverHandlers`, `devServerHandlers`, `devServer`, `typescript`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`, `@nuxtjs/proxy@2.1.0`, `@nuxtjs/i18n@7.3.1`, `nuxt-prometheus-module@0.1.4`, `nuxt-datadog-trace@0.1.2`, `bootstrap-vue/nuxt`, `nuxt-session@1.0.3`, `express-session@1.17.3`, `express@4.18.2`, `cookie-universal-nuxt@2.2.2`
- Build Modules:    `()`, `@nuxtjs/stylelint-module@4.2.0`, `@nuxt/bridge@3.0.0-27928371.c30fa0f`
------------------------------

### Reproduction

Updated configuration and dependencies and tried to start server using bridge, as in the guide on nuxtjs page

### Describe the bug

The server compile but cannot be started due to an error, even if compilation was succesfull

### Additional context

After compiling the index.mjs file appear to have a problem even if it was not reported any error (only a warning due to a import of jsPDF that should not be a problem

```
√ Server: Compiled successfully in 1.50m
√ Client: Compiled successfully in 2.36m

 WARN  Compiled with 1 warnings


 WARN  in ./node_modules/fflate/esm/index.mjs

Module not found: Error: Can't resolve 'worker_threads' in '*****\node_modules\fflate\esm'

√ Nitro built in 5581 ms
i Waiting for file changes

 ERROR  [worker reload] [worker init] require$$1 is not a function

  at ******/.nuxt/dev/index.mjs:443:13
  at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
  at async loadESM (node:internal/process/esm_loader:88:5)
  at async handleMainPromise (node:internal/modules/run_main:65:12)
```

Inside file index.mjs I find (line 438 -443):

```
const require$$0 = /*@__PURE__*/getDefaultExportFromNamespaceIfNotNamed(bodyParser$1);

const require$$1 = /*@__PURE__*/getDefaultExportFromNamespaceIfNotNamed(express);

const bodyParser = require$$0;
const app = require$$1();
```

that is giving the error, the require$$1 is called as a function.

**Comment by danielroe** [comment]
This is probably an issue with one of your dependencies. Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
