### ISSUE TITLE
Nuxt 3 guide step by step for nginx

### ISSUE THREAD

**Issue by cibarra95** [nuxt/nuxt#19591]
### Describe the feature

I hope that Daniel Roe, in the next release adds documentation for nginx configuration to the dev and production environment

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by ennioVisco** [comment]
I don't see the need, couldn't you just run `npx nuxt generate` and copy the files there?

**Comment by cuebit** [comment]
> I don't see the need, couldn't you just run `npx nuxt generate` and copy the files there?

The OP is referring to SSR apps, not necessarily statically generated apps.

**Comment by danielroe** [comment]
I think we can track in https://github.com/nuxt/nuxt/issues/12003.
