### ISSUE TITLE
The child route navigates to the page where the server loads data. After the navigation starts, the child route is destroyed

### ISSUE THREAD

**Issue by yinfoyuan** [nuxt/nuxt#19595]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `pnpm@7.1.0`
- Builder:          `vite`
- User Config:      `routeRules`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-9csc2q?file=pages/index.vue

### Describe the bug

Click user to navigate to the user route. When returning to the home page, the user page child route is destroyed in the data request

**Comment by danielroe** [comment]
I think this is probably the same issue as https://github.com/nuxt/nuxt/issues/13814.

**Comment by danielroe** [comment]
I think we can track in https://github.com/nuxt/nuxt/issues/20798.
