### ISSUE TITLE
Nuxt instance unavailable

### ISSUE THREAD

**Issue by artem-kostylev** [nuxt/nuxt#19603]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.12.0`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@9.4.2`
- Builder:          `vite`
- User Config:      `imports`, `components`, `runtimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

x

### Describe the bug

Sorry for my english,
I have a wrapper over $fetch in which I catch a 401 error and try to request a new token and repeat the original request

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/26843077/224509954-6c5cdc5d-47c6-4b9f-8ead-242e11b7a7f3.png">

but when I call the http function again in the catch I get a nuxt instance unavailable error

<img width="895" alt="image" src="https://user-images.githubusercontent.com/26843077/224510220-f611d25f-389b-4c5b-8978-eeb132e90afd.png">

**Comment by huang-julien** [comment]
Hi :wave: that's probably because it is called within or after a promise

**Comment by manniL** [comment]
Related: https://github.com/nuxt/nuxt/issues/14723, https://github.com/nuxt/nuxt/issues/14269#issuecomment-1397352832
