### ISSUE TITLE
Type support for Node16 module resolution

### ISSUE THREAD

**Issue by danielroe** [nuxt/nuxt#19606]
Follow on from https://github.com/nuxt/nuxt/issues/18426.

In order to have full support for Node16 format are:
 - [x] the output format of our internal runtime directories, which will need to be fixed upstream in https://github.com/unjs/mkdist and https://github.com/unjs/unbuild, for example in https://github.com/unjs/mkdist/pull/134
 - [ ] emitted type declaration files - e.g. `imports.d.ts` upstream in https://github.com/unjs/unimport (cc: @antfu)
 - [ ] our generated aliases in `~/.nuxt/tsconfig.json` need to include a file extension and `/index` path
 - [ ] there may be more locations in the codebase and in particular in runtime directories where we rely on implied `/index` paths
 - [ ] need to either default to `type: module` in starter `package.json` or otherwise provide recommendations on importing in CJS context

**For testing**:

```ts
export default defineNuxtConfig({
  typescript: {
    tsConfig: {
      compilerOptions: {
        moduleResolution: 'Node16'
      }
    }
  }
})
```

**Comment by Nugine** [comment]
Needs this for [@hpcc-js/wasm/graphviz](https://github.com/hpcc-systems/hpcc-js-wasm#-typescript-notes)

**Comment by fabis94** [comment]
Any updates on this?

**Comment by gjedlicska** [comment]
Thanks @danielroe, we're testing the `bundler` option, so far it seams to solve our compatibly issues.

**Comment by nopeless** [comment]
Works like a charm, thank you

I'm having problems with vuetify though, leaving a link here just in case someone stumbles upon this issue

Related vuetify link: https://github.com/vuetifyjs/vuetify/issues/15885

**Comment by danielroe** [comment]
We've now landed internal support for `bundler` module resolution in v3.5 and I think it's probably not needed to attempt Node16 mode. I'll close this as completed, but feel free to comment if there's something that you still need and we can reopen if necessary.
