### ISSUE TITLE
Multiple extends from the same remote source only applies the last extend

### ISSUE THREAD

**Issue by BobbieGoede** [nuxt/nuxt#19614]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `extends`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Unfortunately using remote sources in stackblitz doesn't seem to work, so it will need to be checked locally, reproduction here https://github.com/BobbieGoede/nuxt-layers-build

### Describe the bug

I ran into this while setting up a reproduction for #19613, and maybe this is an edge case that wouldn't be practical in a regular project.

When extending from the same remote source, but extending from a directory within that remote source, only the last defined extend will be used.

* multiple local layers:  `npm run dev:multiple`, both `page-regular` and `page-setup`  are included in the project.

* multiple remote layers: `npm run dev:multiple-remote`, both `page-regular` and `page-setup` should be included in the project, but only `page-setup` (from the last extended layer) works.

* single remote layer: `npm run dev`, only `page-regular` is included in the project, and works as expected.

**Comment by pi0** [comment]
Upstream tracker: https://github.com/unjs/c12/issues/63

**Comment by pi0** [comment]
> Unfortunately using remote sources in stackblitz doesn't seem to work,

Thanks for reporting this. I have made a [minimal reproduction](https://stackblitz.com/edit/node-9zvngk?file=index.mjs) and will ran it to the stackblitz team!

**Comment by danielroe** [comment]
Let's track in upstream issue.
