### ISSUE TITLE
Unable to build when extending pages with remote layer

### ISSUE THREAD

**Issue by BobbieGoede** [nuxt/nuxt#19613]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `extends`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Unfortunately using remote sources in stackblitz doesn't seem to work, so it will need to be checked locally, reproduction here https://github.com/BobbieGoede/nuxt-layers-build

### Describe the bug

It seems like it isn't possible to build a project that uses a remotely sourced layer to extend pages (nuxt config seems to work, haven't tested other features).

Run `npm run build:remote` to see that the build fails throwing the following error:
```console
[vite]: Rollup failed to resolve import "vue/server-renderer" from "/home/bobbie/.cache/c12/github_BobbieGoede_nuxt-layers-build/pages/page-regular.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```
Run `npm run build:local` to see the build succeed using the same layer, except referenced locally.

### Additional context

It sounds similar to #18448 but this issue happens without any other dependencies, a comment later in that thread does run into the same issue https://github.com/nuxt/nuxt/issues/18448#issuecomment-1413447912

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/12347. (I think it's the same issue.)
