### ISSUE TITLE
Default setup doesn't work with yarn 3

### ISSUE THREAD

**Issue by nicoduesing** [nuxt/nuxt#19618]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `yarn@3.4.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

I wanted to create a new nuxt3 project with the [getting started guide](https://nuxt.com/docs/getting-started/installation). I'm using node `18.15.0` and yarn `3.4.1`. I executed 
```
npx nuxi init nuxt3
cd nuxt3
yarn install
yarn dev
```
and expected to have a running project, but it showed the error, that the required package `@nuxt/kit` is missing, so I installed it. After that, it is missing `@nuxt/ui-templates`, which I also installed. Then it shows the error `Cannot start nuxt:  Cannot find any nuxt version`.

### Describe the bug

With yarn `3.4.1` the created project is not starting. It showed the error, that the required package `@nuxt/kit` is missing, so I installed it. After that, it is missing `@nuxt/ui-templates`, which I also installed. Then it shows the error `Cannot start nuxt:  Cannot find any nuxt version`. With yarn `1.22.19` it worked.

### Logs

```shell-script
ERROR  Cannot start nuxt:  Cannot find any nuxt version from /home/myUser/projects/nuxt3                                                                                           17:03:06

  at loadNuxt (.yarn/cache/@nuxt-kit-npm-3.2.3-b1bd87d016-e52482e84c.zip/node_modules/@nuxt/kit/dist/index.mjs:516:11)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async load (.yarn/cache/nuxi-npm-3.2.3-1e0b064d43-181c087a34.zip/node_modules/nuxi/dist/chunks/dev.mjs:6795:23)
  at async Object.invoke (.yarn/cache/nuxi-npm-3.2.3-1e0b064d43-181c087a34.zip/node_modules/nuxi/dist/chunks/dev.mjs:6871:5)
  at async _main (.yarn/cache/nuxi-npm-3.2.3-1e0b064d43-181c087a34.zip/node_modules/nuxi/dist/cli.mjs:50:20)
```
```

**Comment by manniL** [comment]
You need to use the [`node-modules` linker](https://yarnpkg.com/configuration/yarnrc#nodeLinker) as Yarn PnP is not supported. More @ https://github.com/nuxt/nuxt/issues/14146
