### ISSUE TITLE
Any exception from asyncData will be discard in Nuxt 3

### ISSUE THREAD

**Issue by duc2019** [nuxt/nuxt#19625]
### Environment

Nuxt 3.2.2

### Reproduction

- Create a project with Nuxt 3.2.2
- Set `ssr: false` in `nuxt.config.ts`
- Create a page

```
<template>
</template>
<script lang="ts">
export default defineNuxtComponent({
  async asyncData () {
    throw "error 123"
  }
})
</script>
```

### Describe the bug

In Nuxt 2 the excepton occurs in asyncData will be catch and pass to the error page, we can handle the error properly.

In Nuxt 3 it simply gone, we can't even see the error in console 🤣🤣🤣
The only output in console is `[nuxt] asyncData should return an object` and we know we get fucked something wrong in the asyncData function.

Is option api and asyncData no longer supported?
Can you guys save programers migrating from Nuxt 2? We are in the hell.

For people has same issue, here is a workround for this ridiculous bug:

- Add isReady to data()
- Add `v-if="isReady"` to the root element
- Move all logic from asyncData to created
- Add `this.isReady = true` at the end of created
- Exceptions from created will be well handled not like asyncData, I think this function may no longer supported

**Comment by fahmifitu** [comment]
related to  https://github.com/nuxt/nuxt/issues/15616
