### ISSUE TITLE
navigateTo in defineNuxtRouteMiddleware done not work

### ISSUE THREAD

**Issue by Mr-prudent** [nuxt/nuxt#19626]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v18.12.0`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-3axmwt?file=middleware/mobile.global.js
Simply add navigateTo in `middleware/mobile.global.js`

### Describe the bug

Middleware use : /middleware/mobile.global.js
```javascript
// middleware/mobile.global.js
export default defineNuxtRouteMiddleware((to, from) => {
  const route = useRoute();
  if (process.server) {
    const isMobile = true;
    if (isMobile && route.path !== '/mobile') {
      return navigateTo('/mobile', {
        replace: true,
      });
    }
  }
});
```
I try to use route middleware in `middleware/mobile.global.js`  and nuxt@3.2.3, but it done not work.
it works in nuxt@3.0.0.

**Comment by danielroe** [comment]
The issue here is that you are calling `useRoute()`. In middleware, the route hasn't yet changed, so you need to use `to`, not the current route.

Here's an updated sandbox: https://stackblitz.com/edit/github-3axmwt-cfhkss.

**Comment by dargmuesli** [comment]
Maybe there could be a warning when use of `useRoute` inside a middleware is detected?

**Comment by danielroe** [comment]
Implemented ✅
