### ISSUE TITLE
fail to create nuxt 3 project.

### ISSUE THREAD

**Issue by acche** [nuxt/nuxt#19639]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `0.0.0`
- Package Manager:  `npm@9.5.0`
- Bundler:          `Webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

pnpm dlx nuxi init test

### Describe the bug

.../Library/pnpm/store/v3/tmp/dlx-23587  | Progress: resolved 1, reused 0, downl.../Library/pnpm/store/v3/tmp/dlx-23587  | Progress: resolved 1, reused 1, downl.../Library/pnpm/store/v3/tmp/dlx-23587  |   +2 +
.../Library/pnpm/store/v3/tmp/dlx-23587  | Progress: resolved 1, reused 1, downl.../Library/pnpm/store/v3/tmp/dlx-23587  | Progress: resolved 2, reused 1, downl.../Library/pnpm/store/v3/tmp/dlx-23587  | Progress: resolved 2, reused 2, downloaded 0, added 2, done
Nuxi 3.2.3                                                            19:10:51

 ERROR  Error: Failed to download template from registry: fetch failed

 ERROR  Command failed with exit code 1: nuxi init test

pnpm: Command failed with exit code 1: nuxi init test
    at makeError (/opt/homebrew/Cellar/pnpm/7.29.1/libexec/dist/pnpm.cjs:23074:17)
    at handlePromise (/opt/homebrew/Cellar/pnpm/7.29.1/libexec/dist/pnpm.cjs:23645:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler [as dlx] (/opt/homebrew/Cellar/pnpm/7.29.1/libexec/dist/pnpm.cjs:219303:7)
    at async /opt/homebrew/Cellar/pnpm/7.29.1/libexec/dist/pnpm.cjs:227043:21
    at async main (/opt/homebrew/Cellar/pnpm/7.29.1/libexec/dist/pnpm.cjs:227010:34)
    at async runPnpm (/opt/homebrew/Cellar/pnpm/7.29.1/libexec/dist/pnpm.cjs:227242:5)
    at async /opt/homebrew/Cellar/pnpm/7.29.1/libexec/dist/pnpm.cjs:227234:7

**Comment by danielroe** [comment]
I think we can track in https://github.com/nuxt/nuxt/issues/15101.

**Comment by acche** [comment]
I think this should be added as a prompt in the guidelines to save developers in certain regions the time of debugging."

**Comment by danielroe** [comment]
Would welcome a PR! 🙏
