### ISSUE TITLE
Nuxt 2.15.8 modern build issues on IE11/Edge (function* unescaped)

### ISSUE THREAD

**Issue by llqqun** [nuxt/nuxt#19633]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.18.0`
- Nuxt Version:     `2.15.8`
- Nitro Version:    `-`
- Package Manager:  `npm@8.19.2`
- Builder:          `webpack`
- User Config:      `target`, `head`, `server`, `css`, `plugins`, `router`, `components`, `buildModules`, `styleResources`, `modules`, `axios`, `proxy`, `privateRuntimeConfig`, `build`, `vue`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`
- Build Modules:    `@nuxtjs/eslint-module@3.1.0`, `@nuxtjs/style-resources@1.2.1`

### Reproduction

Open link in either IE11 . Open the developer tools and click on console tab. Script error should appear in console.

### Describe the bug

IE11 receive a script error which halts the app's progress in loading
function* is not escaped when building the project

### Additional context

![2023-03-13_174816](https://user-images.githubusercontent.com/36347513/224666054-bd571c7f-c21a-4b62-b940-384f72237b35.png)

function* Display error

This is my configuration
![2023-03-13_174816](https://user-images.githubusercontent.com/36347513/224666607-163386e8-2434-452e-b845-8ca11c034547.png)

**Comment by llqqun** [comment]
![2023-03-13_175022](https://user-images.githubusercontent.com/36347513/224666845-29353dd2-51e1-4146-97d6-68e54d97b4eb.png)

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

That dependency is not provided by nuxt, and I'm guessing it might be axios. You could try adding axios to your `build.transpile` array.

**Comment by llqqun** [comment]
> Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
> 
> That dependency is not provided by nuxt, and I'm guessing it might be axios. You could try adding axios to your `build.transpile` array.

I tried to reproduce my problem
![2023-03-14_101421](https://user-images.githubusercontent.com/36347513/224875351-4ab2b280-a98a-49f6-8b7b-8a2d54bdbeaf.png)

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
