### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/nuxt#19632]
### Environment

Nuxi 3.2.3                                                                                                        09:47:55
                                                                                                                  09:47:56
RootDir: /home/projects/nuxt-starter-x6zwzs                                                                       09:47:56
Nuxt project info:                                                                                                09:47:56

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                       09:47:56

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Reproduction

https://stackblitz.com/edit/nuxt-starter-x6zwzs

### Describe the bug

We are implementing Winston with Syslog in nuxt 3

If i try it in local (with vite server) the app runs OK.

But if i put it in out staging environment (without vite, with a compiled version) the app throws "require is not defined"

**Comment by danielroe** [comment]
You should not use `require()` within your code. See https://nuxt.com/docs/guide/concepts/esm.
