### ISSUE TITLE
Add content-encoding to SSR generated HTML 

### ISSUE THREAD

**Issue by mkierdev** [nuxt/nuxt#19645]
### Describe the feature

I can't seem to find any option to enable content-encoding for SSR generated pages. Is this feature not implemented in Nuxt 3?
Request-headers contain header: ```Accept-Encoding: gzip, deflate, br```, however returned html is not compressed at all.

Enabling compression would improve performance and reduce transfer-size.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
Related upstream-issue (nitro): https://github.com/unjs/nitro/issues/1007

As mentioned there, it is recommended to let your reverse proxy or platform do that for your.
