### ISSUE TITLE
Can't render website on server side on Vercel if url has `+` (space) char

### ISSUE THREAD

**Issue by lukaszflorczak** [nuxt/nuxt#19657]
### Environment

Vercel with node 18.x
Nuxt 3.2.2 

### Reproduction

[nuxt-playground-six.vercel.app](https://nuxt-playground-six.vercel.app/)

https://github.com/lukaszflorczak/nuxt-playground

1. Visit the project hosted on Vercel
2. Click the link and then refresh the website to use server-side rendering

### Describe the bug

If the URL contains a space (automatically converted to `+` char), it's impossible to open it with server-side rendering on Vercel. 

In Vercel logs there are multiple `302` redirections:

<img width="552" alt="Zrzut ekranu 2023-03-13 o 23 49 55" src="https://user-images.githubusercontent.com/1818979/224851423-0840eaa9-6df7-4da7-82d6-b6f55a472820.png">

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/14754
