### ISSUE TITLE
UC browser And Google Chrome on mobile，The browser only returns static prerendering, with no functionality

### ISSUE THREAD

**Issue by a992964603** [nuxt/nuxt#19658]
### Environment

nuxt 3.2.2

### Reproduction

use

### Describe the bug

UC browser And Google Chrome on mobile，The browser only returns static prerendering, with no functionality。

**Comment by a992964603** [comment]
Version 3.0.0 does not have this bug

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by a992964603** [comment]
create new nuxt3.2.3 app，alert('test') is executed on onMounted， npm run build，and Open it on your phone with Google Chrome.

**Comment by cuebit** [comment]
@a992964603, your instructions do not reproduce the issue. Please follow [this link](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction), take a moment to read, and consider providing a minimal reproduction 👍

**Comment by a992964603** [comment]
This bug requires a real phone to reproduce. You can simply create a new nuxt3.2.2 app and execute “alert('x')” in “onMounted”.
that he would not execute on a real phone using google Browser。

**Comment by danielroe** [comment]
Nuxt runs fine on any number of web pages and on a real phone. I can't speak for running `alert` as I suspect it might be possible to configure your phone not to display that kind of thing. But client-side JavaScript certainly works.

**Comment by CaptKraken** [comment]
facing the same problem. the javascript is not loading at all on UC browser. there's no error (according to v-console) the javascript just wont load.

**Comment by danielroe** [comment]
What version of UC Browser are you on?

**Comment by CaptKraken** [comment]
> What version of UC Browser are you on?

V13.4.2.1307 running on a Samsung S21 Ultra.

**Comment by CaptKraken** [comment]
Update:
it was totally my fault. it works fine after setting the build config to this. 
```ts
build: {
  target: ["esnext", "ios12"],
}
```

there's probably some css build config i have to do, but the site is functional on uc browser android. bless!
