### ISSUE TITLE
Failed to resolve module specifier 

### ISSUE THREAD

**Issue by manzolidev** [nuxt/nuxt#19656]
### Environment

Operating System: MacOS
Node Version: v16.14.2
Nuxt Version: ^3.2.3
Package Manager: yarn
Builder: vite

### Reproduction

https://stackblitz.com/edit/github-gceovx?file=app.vue

### Describe the bug

I'm trying to create a simple icon component, but I got some errors in console.log

![Screenshot 2023-03-13 at 18 05 43](https://user-images.githubusercontent.com/26907629/224832422-695782c1-4d08-4c16-b871-448ea3456723.png)

**Comment by manzolidev** [comment]
> You have added `/* @vite-ignore */` which prevents creating a dynamic chunk and will literally fetch that path from the network.

I deleted that line and the error still happens...

**Comment by danielroe** [comment]
change your backticks to normal quotes and you should be good to go

**Comment by manzolidev** [comment]
> change your backticks to normal quotes and you should be good to go

If I need a dynamic import? like this
```
const name = "add";
const path = `@/components/${name}.vue`;
const vueIcon = await import(path).then((r) => r.default);
```

how can I fix that error?

**Comment by manzolidev** [comment]
I fixed this erro using `resolveComponent`, thanks!
