### ISSUE TITLE
`useLoading` composable to control `<NuxtLoadingIndicator />` ?

### ISSUE THREAD

**Issue by mrleblanc101** [nuxt/nuxt#19650]
### Describe the feature

Maybe I'm missing something, I see the `<NuxtLoadingIndicator />` component, but how can I start/stop the loading manually like in Nuxt 2 ? 

In Nuxt 2 I could do this:
```
this.$nuxt.$loading.start();
await somePromise();
this.$nuxt.$loading.finish();
```
In Nuxt 3, could we get a composable to do the same ?
```
const loading = useLoading();
loading.start();
await somePromise();
loading.finish();
```

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by mrleblanc101** [comment]
Maybe useLoader would be a better name ?

**Comment by mrleblanc101** [comment]
There is a `useLoadingIndicator` but it's not exposed
https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/app/components/nuxt-loading-indicator.ts

**Comment by danielroe** [comment]
I think we can track events + controller api in https://github.com/nuxt/nuxt/issues/14221.
