### ISSUE TITLE
Generic type of useFetch composable does not work if the method option is other than GET

### ISSUE THREAD

**Issue by kaname-png** [nuxt/nuxt#19651]
### Environment

RootDir: C:/Users/Kaname/Documents/naeko/dashboard                                                                                                          13:10:51
Nuxt project info:                                                                                                                                          13:10:51

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v19.7.0`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `pnpm@7.27.1`
- Builder:          `vite`
- User Config:      `modules`, `experimental`, `css`, `htmlValidator`, `app`, `runtimeConfig`, `colorMode`, `security`, `i18n`, `content`, `nuxtTypedRouter`, `devtools`, `ogImage`, `pinia`, `robots`, `auth`
- Runtime Modules:  `@nuxt/content@2.5.2`, `@nuxtjs/html-validator@1.2.4`, `@nuxtjs/fontaine@0.2.4`, `@nuxtjs/tailwindcss@6.4.1`, `@nuxtjs/color-mode@3.2.0`, `@nuxtjs/i18n@8.0.0-beta.10-27964275.182098b`, `@nuxt/image-edge@1.0.0-27968280.9739e4d`, `@nuxt/devtools@0.2.5`, `nuxt-security@0.12.0`, `nuxt-icon@0.3.2`, `nuxt-typed-router@3.0.6`, `@sidebase/nuxt-auth@0.4.3`, `nuxt-og-image@1.5.2`, `@pinia/nuxt@0.4.7`, `@nuxtjs/robots@3.0.0`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-gtgxbf?file=app.vue

### Describe the bug

When you try to use a generic type in the useFetch composable `useFetch<{ type }>('https://www.google.com')`, it does not allow you to select any HTTP method type other than GET in its options.

> Error

![image](https://user-images.githubusercontent.com/56084970/224806362-96042b2d-863d-41b4-899b-b10d0d48fdbb.png)

> No Error

![image](https://user-images.githubusercontent.com/56084970/224811245-f7712ad6-6fc9-4861-a110-e32757aa9497.png)

### Additional context

TypeScript types error.

**Comment by hi-reeve** [comment]
+1

**Comment by AloisSeckar** [comment]
Already being discussed in #19077

**Comment by danielroe** [comment]
okay, let's track it there.
