### ISSUE TITLE
app.pageTransition Refreshing page scrolls will to the top

### ISSUE THREAD

**Issue by jheng-jie** [nuxt/nuxt#19664]
### Environment

mac m1

### Reproduction

- [stackblitz](https://stackblitz.com/edit/nuxt-starter-8svbbt?file=nuxt.config.ts)

On the right window, there is a refresh button on the left of the URL

### Describe the bug

- `nuxt.config.js`

If pageTransition is set. Refreshing page scrolls will to the top

```ts
export default defineNuxtConfig({
  app: {
    pageTransition: { name: 'page', mode: 'out-in' },
  },
});
```

But disable pageTransition. the scroller will be at the position before refreshing

**Comment by abhishek-kumar-91** [comment]
I want to work on this issue, please assign me.

**Comment by jpengelbrecht** [comment]
++

**Comment by DanielRivers** [comment]
@abhishek-kumar-91 are you still intending to look at this one?  I could look I am looking for a nice first issue to get going with
