### ISSUE TITLE
setCookie not seted Cookie

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/nuxt#19668]
### Environment

Nuxi 3.2.3                                                                                                        13:18:47
                                                                                                                  13:18:48
RootDir: /home/projects/nuxt-starter-6clqyq                                                                       13:18:48
Nuxt project info:                                                                                                13:18:48

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@pinia/nuxt@0.4.7`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                       13:18:48

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Reproduction

https://stackblitz.com/edit/nuxt-starter-6clqyq

### Describe the bug

I have opened other issues related with cookies.

We are trying to create a session id cookie in the start of app.

I'm ussing Pinia for share the session id between the components of application.

But for the persistence, the cookie is not saved in first load.
If i click in the "refresh" button, the cookie is setted.

**Comment by danielroe** [comment]
I think you just need to add a leading slash:

```diff
- const { data: test, refresh } = await useFetch('fapi/test');
+ const { data: test, refresh } = await useFetch('/fapi/test');
```

**Comment by agracia-foticos** [comment]
cierto! cierro incidencia
TRUE! I close incident
