### ISSUE TITLE
useLazyFetch does not behave like useLazyAsyncData

### ISSUE THREAD

**Issue by alexanderhorner** [nuxt/nuxt#19665]
### Environment

- Operating System: `Darwin`
- Node Version:     `v19.5.0`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@9.3.1`
- Builder:          `vite`
- User Config:      `modules`, `runtimeConfig`, `content`, `image`, `googleFonts`
- Runtime Modules:  `@nuxt/content@2.5.2`, `@nuxtjs/google-fonts@3.0.0`, `@nuxt/image-edge@1.0.0-27968280.9739e4d`
- Build Modules:    `-`

### Reproduction

The following code fetches search results. It's automatically refreshed when the searchquery ref is changed.

```javascript
const navSearchAPICall = useLazyAsyncData(
    'searchWorking',
    () => $fetch('/api/search', {
        params: {
            query: searchquery.value
        }
    }),
    { 
        server: false,
        watch: [searchquery]
    }
)
```

This works as expected. But the following code, wich should behave the same according to the documentation, does not work. The request is refreshed when the searchquery ref changes, but the query parameters stay the same.

```javascript
const searchAPICall = useLazyFetch('/api/search', {
        key: 'searchNotWorking',
        params: {
            query: searchquery.value
        },
        server: false,
        watch: [searchquery]
    }
)
```

### Describe the bug

As described in the reproduction, when using `useLazyAsyncData`, the request is refreshed with updated query parameters according to the searchquery ref. 

But when using `useLazyFetch`, the request is refreshed but sent with unchanged query parameters.

**Comment by danielroe** [comment]
You should pass the ref directly, or it will be 'frozen' at the moment you call `useLazyFetch`, and unable to update:

```js
const searchAPICall = useLazyFetch('/api/search', {
        key: 'searchNotWorking',
        params: {
            query: searchquery
        },
        server: false,
        watch: [searchquery]
    }
)
```

**Comment by alexanderhorner** [comment]
Thank you.
