### ISSUE TITLE
Docs feedback - Setup store

### ISSUE THREAD

**Issue by titouandk** [nuxt/nuxt#19696]
Hello,

Just a feedback on the documentation from a beginner at Nuxt3 (with a little bit of experience on Nuxt2).
I find the doc to be too abstract on the subject of the store, and its initialization.

With Nuxt2, I used to create a "store" folder and place my JS files inside it.

What about Nuxt3 ?

- Should I use [this way](https://nuxt.com/docs/getting-started/state-management#shared-state) of centralized state management in Nuxt 3, instead of VueX or Pinia ?
- If I need to use Pinia, should I create a "store" folder and place my JS files inside it, like for Nuxt 2 ? It seems the "store" folder [disappeared](https://nuxt.com/docs/guide/directory-structure/server) in the folder structure of Nuxt 3.

Thanks for your help

**Comment by danielroe** [comment]
This could be added to the Migration section of the docs: https://github.com/nuxt/nuxt/tree/main/docs/7.migration.

**Comment by adrienZ** [comment]
@danielroe I'm tempted to write documentation for this if that's ok

**Comment by danielroe** [comment]
you ⭐

**Comment by titouandk** [comment]
Thanks ! 👍

**Comment by BrianDriscollCode** [comment]
My understanding of the differences after looking at both Nuxt 2 and Nuxt 3 docs: 

1. Nuxt 2 has a store folder that implements Vuex for shared state.
2. Nuxt 3 provides a way to provide a way to implement shared state using auto-imported composables. 

But there is no documentation that states "create a store folder then install Pinia etc..." But there is a [little blurb here](https://nuxt.com/docs/migration/configuration#vuex) in migration about VueX and Pinia then points to their docs. 

So the information is there, just a little hidden away.

According to Daniel's recommendation to include the documentation in the migration area and titouandk's need, the solution:

1. I think the differences could be explained in migration.
2. BUT, I do think [state management](https://nuxt.com/docs/getting-started/state-management) could add an example using Pinia to make it more clear.

I think it would be hard for new users to find state-related information tucked away in migration. So I'll take a stab at adding both but I'm unsure the mindset of others on it. We will see, curious myself as I just "assumed" pinia works within Nuxt and Pinia had documentation on it.

**Comment by BrianDriscollCode** [comment]
I see that AdrienZ is assigned so I'll let him have at it. Hope my suggestions give you some ideas =)

**Comment by adrienZ** [comment]
Made a PR, feel free to take a look :)
