### ISSUE TITLE
server return type error

### ISSUE THREAD

**Issue by hminghe** [nuxt/nuxt#19692]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `pnpm@6.21.1`
- Builder:          `vite`
- User Config:      `nitro`, `ssr`, `modules`, `app`
- Runtime Modules:  `@pinia/nuxt@0.4.7`, `@vueuse/nuxt@9.13.0`, `@element-plus/nuxt@1.0.3`, `@unocss/nuxt@0.50.4`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-xbwzpm?file=server%2Fapi%2Ftest.ts

### Describe the bug

server return type why add `SerializeObject` ?  
接口返回类型为什么要添加 `SerializeObject` ?

**Comment by danielroe** [comment]
This is actually a feature. All that you return from an event handler is going to be serialised to JSON, so this ensures that the return type accurately matches what you actually get when calling `$fetch`. That is, you won't have actual Date objects, but Dates that have been stringified.

**Comment by hminghe** [comment]
> This is actually a feature. All that you return from an event handler is going to be serialised to JSON, so this ensures that the return type accurately matches what you actually get when calling `$fetch`. That is, you won't have actual Date objects, but Dates that have been stringified.

Ok, can I export SerializeObject？

**Comment by newclarityex** [comment]
> This is actually a feature. All that you return from an event handler is going to be serialised to JSON, so this ensures that the return type accurately matches what you actually get when calling `$fetch`. That is, you won't have actual Date objects, but Dates that have been stringified.

Is there an easy way to retrieve objects including dates? Or adding some sort of serialization in between?

**Comment by Chudesnov** [comment]
@danielroe this feature is really confusing and i could not find any mention of SerializeObject literally anywhere in the docs or even this repo using GitHub’s search, could you link to a documentation page or at least the module that creates these type definitions?

**Comment by danielroe** [comment]
Yes, this is coming from Nitro directly. Please do feel free to open an issue [there](https://github.com/unjs/nitro) if you are encountering any issues with the accuracy of the type inference you're getting.

**Comment by eriksLapins** [comment]
Just in case anyone has this issue as well, I found that this utility function helps for arrays or objects that are returned from the server api routes. Seems to work for me

```
import type { SerializeObject } from 'nitropack';

type Flatten<T> = T extends Array<SerializeObject<infer R>> ? Array<R> : T extends SerializeObject<infer R> ? R : T;

export default function jsonParse <T> (data: T): Flatten<T> {
    const deserialized = JSON.parse(JSON.stringify(data));

    return deserialized;
}
```
