### ISSUE TITLE
Modules can't add pages when pages directory not exist 

### ISSUE THREAD

**Issue by mercs600** [nuxt/nuxt#19699]
### Environment

just stackblitz, there is no issue with environment 
``` 
  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    nuxt: ^2.16.2 => 2.16.2 
```

### Reproduction

https://stackblitz.com/edit/github-a2pdyd?file=modules/addpage/_.vue

### Describe the bug

I'm not sure if it is a bug but,  when there is no 'pages' directory in the Nuxt.js application, modules cannot add or extend routes. 

Please check reproduction. There is no pages directory and we can see 
```
 WARN  No pages directory found in /home/projects/github-a2pdyd. Using the default built-in page.
```

But if you add pages directory then page file from module will be applicable. 

I have an idea to check if the 'pages' directory doesn't exist and then change the pages directory. 
## Is there any other option to force enabling it?

Here is my temporary solution
```js
if (!fs.existsSync(this.options.srcDir + '/' + this.options.dir.pages)) {
    this.options.dir.pages = relative(
      this.options.srcDir,
      resolve(__dirname, './pages/')
    );
  }
```

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
