### ISSUE TITLE
Nuxt 3.3.2 navigateTo() not working in routeMidleware

### ISSUE THREAD

**Issue by nosizejosh** [nuxt/nuxt#19695]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.17.1`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `postcss`, `css`, `modules`
- Runtime Modules:  `@formkit/nuxt@1.0.0-beta.9-f64c966`, `@vueuse/nuxt@9.13.0`, `@pinia/nuxt@0.4.7`, `@nuxtjs/supabase@0.3.1`, `@nuxtjs/tailwindcss@6.4.1`, `@pinia-plugin-persistedstate/nuxt@1.0.0`, `nuxt-icon@0.2.11`, `@nuxt/devtools@0.1.6`
- Build Modules:    `-`
------------------------------

### Reproduction

Simple app with supabaseand nuxt/supabase

### Describe the bug

navigateTo has no effect but router().push() works with error ![image](https://user-images.githubusercontent.com/392227/225267863-d1f26da0-a80f-416e-b4e0-7b04972530cf.png).

Code for my routeMiddleware below:

```
export default defineNuxtRouteMiddleware((to, from) => {
  const user = useSupabaseUser();
  watchEffect(async () => {
    // if not signed in and attemting to visit private route
    // reroute to login saving the current destination in the redirect query param
    if (!user.value ) {
      console.log("must be redirecting to signin now");
      router.push("/signin");
      // await navigateTo({ name: "signin", query: { redirect: to.path } });
    }
  });
});
```

Is there something wrong with my code or is this a bug? there are many issues around navigateTo here, but none conclusive to help with my particular issue. 
Is there a fix or workaround for this issues please?

Thanks

**Comment by danielroe** [comment]
Your code here is not running within the middleware but instead is running within `watchEffect`, which will not work as you expect on the server. `navigateTo` is only getting called after the response has been sent to the end user.
