### ISSUE TITLE
Way to detect Nuxt framework from library during SSR / CSR

### ISSUE THREAD

**Issue by mklueh** [nuxt/nuxt#19698]
### Describe the feature

I'm currently using a component library that has a BaseButton.

This button changes it's implementation based on the framework where the ui library is used.

Ex.: if the library is used in Nuxt, it should use **nuxt-link**, otherwise **router-link** or even plain **button**

```
<template>
  <nuxt-link v-if="nuxt && to" :to="to" class="base-button button-primary" :disabled="disabled">
    <slot/>
  </nuxt-link>
  <router-link v-else-if="!nuxt && to" :to="to" class="base-button" :disabled="disabled">
    <slot/>
  </router-link>
  <button v-else type="button" @click="$emit('click')" class="base-button" :disabled="disabled">
    <slot/>
  </button>
</template>
```

See https://stackoverflow.com/questions/74593611/detect-in-vue-component-if-its-used-in-nuxt-3-or-somewhere-else

**This worked perfectly in Nuxt 2** because there was a global nuxt object you could use to check against, but this does not exist anymore.

I've seen there is a **__NUXT__** property in the browser, but you can't address the window object when using SSR.

Also, process.env.NUXT_VITE_NODE_OPTIONS can't be used to check against in the browser.

**There needs to be a way to detect the framework from within components without requiring imports from Nuxt, that would fail when used outside of Nuxt.**

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by mklueh** [comment]
Hi @pi0 , thanks a lot, it seems to work. Would you like to add your answer to stackoverflow as well or don't you mind if I do it?

**Comment by pi0** [comment]
Feel free to repost it in StackOverflow 👍🏼

**Comment by davidnknight** [comment]
> Hi. You can directly use tiny [unctx](https://github.com/unjs/unctx) library in your integrations and this way detect existence of nuxt context:
> 
> ```ts
> import { useContext } from 'unctx'
> 
> const isNuxt = () => !!useContext('nuxt-app')
> ```
> 
> We might also think about static injected flags to specifically detect nuxt but context is probably safest way and possible today.

This isn't working for me. I'm also looking for a way to determine if a component is running in a Nuxt 3 or Vue app. Did the key change, or any better way to detect this?

**Comment by Hai-San** [comment]
> Reference in

It didn't work for me. Always returns true, regardless of the application or value inside `useContext()`

**Comment by Hai-San** [comment]
> Hi. You can directly use tiny [unctx](https://github.com/unjs/unctx) library in your integrations and this way detect existence of nuxt context:
> 
> ```ts
> import { useContext } from 'unctx'
> 
> const isNuxt = () => !!useContext('nuxt-app')
> ```
> 
> We might also think about static injected flags to specifically detect nuxt but context is probably safest way and possible today.

It didn't work for me. Always returns true, regardless of the application or value inside `useContext()`

**Comment by brunopbarbosa** [comment]
Also not working for me, same as mentioned above.
