### ISSUE TITLE
useFetch useAsyncData no cache

### ISSUE THREAD

**Issue by 289997171** [nuxt/nuxt#19707]
### Environment

Operating System: Windows_NT
Node Version: v18.13.0
Nuxt Version: "^3.3.1"   "^3.2.3"
Package Manager: yarn@1.22.19
Builder: vite
User Config: -
Runtime Modules: -
Build Modules: -

### Reproduction

https://github.com/289997171/nuxt-data.git

### Describe the bug

Nuxt Version: "^3.3.1"   "^3.2.3" useFetch and useAsyncData data cache not work.
Whenever pages are switched, nuxt will always send a request to the server, and the caching function is invalid.

but "nuxt": "3.0.0-rc.12" is ok

```
pages/test1.vue
<template>
  <div>
    test1 - {{data}}
  </div>
</template>

<script setup>
definePageMeta({
  keepalive: true
})
const {data} = useFetch('/api/test1')
</script>
```

```
pages/test2.vue
<template>
  <div>
    test2 - {{data}}
  </div>
</template>

<script setup>
definePageMeta({
  keepalive: true
})
const { data/*, pending, error, refresh*/ } = await useAsyncData(
    'test2',
    () => $fetch('/api/test2')
)
</script>
```

```
server/api/test1.js
export default defineEventHandler(() => {
    console.log('request test1')
    return 'test1 xxxxx'
})
```
```
export default defineEventHandler(() => {
    console.log('request test2')
    return 'test2 yyyyy'
})
```

**Comment by manniL** [comment]
The `cache` was deliberately removed. See https://github.com/nuxt/nuxt/issues/15445.
