### ISSUE TITLE
Options to remove console.log from build.

### ISSUE THREAD

**Issue by Timtendo12** [nuxt/nuxt#19702]
### Describe the feature

Just like the title says, Adding the build option to remove all console.log from the build so they only show up in your webdev environment! 

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
I think this (if implemented) should be implemented in user-land rather than as a core Nuxt feature.

**Comment by pi0** [comment]
@Baroshem maybe a `nuxt-security` feature flag can do this?

**Comment by Baroshem** [comment]
Hey @pi0 

I am not sure what the use case is here. NuxtSecurity should be responsible for implementing security related functionalities and removal of console log is more like a clean up rather than security practise IMO.

Unless you have something specific in mind. Let me know

**Comment by pi0** [comment]
Honestly, i'm not sure the scope of log removal. There is small bundle size reduction but i guess same as `x-powered-by` removal, no logs reduce the chances of application exposure. Otherwise normal users won't have to look at devtools. Maybe worth it's own module. Was just a suggestion.

**Comment by Baroshem** [comment]
Sounds interesting . I will create an issue and think about it more. Thanks for that idea @pi0 ;)

**Comment by dipbhi** [comment]
Vite already supports this esbuild minifier (which is the default value).

```
export default defineNuxtConfig({
...
    vite: {
        esbuild: {
            drop: ["console"],
        },
    },
...
});
```

For Nitro server code, console removal is supported as well.

```
export default defineNuxtConfig({
...
    nitro: {
        esbuild: {
            options: {
                drop: ["console"],
            },
        },
    },
...
});
```
