### ISSUE TITLE
useNuxtData setting overwriting data doesn't work

### ISSUE THREAD

**Issue by 94726** [nuxt/nuxt#19704]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.11.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `pnpm@7.13.6`
- Builder:          `vite`
- User Config:      `modules`, `srcDir`, `ssr`, `nitro`, `devServer`, `typescript`, `devtools`, `runtimeConfig`
- Runtime Modules:  `@unocss/nuxt@0.50.4`, `@vueuse/nuxt@9.13.0`, `@nuxt/devtools@0.2.5`, `nuxt-typed-router@3.0.6`
- Build Modules:    `-`

### Reproduction

I've recreated the [optimistic update example from the docs](https://nuxt.com/docs/api/composables/use-nuxt-data#optimistic-updates):
https://stackblitz.com/edit/github-a2zxx3?file=requests/todos.ts
1. Click add button
2. Click add button again (every second add will fail)
3. See that the data doesn't get overwritten.

### Describe the bug

When using `useNuxtData`, it is not possible to overwrite the data directly:

```ts

const {data: todos} = useFetch('/api/todos', {key: 'todos'})

const {data: nuxtDataTodos} = useNuxtData<string[]>('todos') // array of todo
nuxtDataTodos.value = ["replace all todos"] // won't update todos from useFetch/useAsyncData
```

From looking at [useNuxtData docs](https://nuxt.com/docs/api/composables/use-nuxt-data#optimistic-updates), I'd expect this to work.

**Comment by danielroe** [comment]
In your case I think the issue is that you haven't awaited `useFetch`. So probably `useNuxtData` _does_ overwrite the value of the todos, but then it is almost immediately overwritten by the succeeding request to `/api/todos`.

But maybe I am misunderstanding your reproduction, which seems to be working fine to me.

**Comment by 94726** [comment]
I'm sorry, for forgetting the await on `useFetch` . But there still seem to be some issues with `useNuxtData`. I've played around with it a bit more and found something rather peculiar.

New reproduction: https://stackblitz.com/edit/github-a2zxx3-k3hqlr?file=app.vue

1. Click `Add Todo` (works fine)
2. Click `Replace Todos`
3. Click `Add Todo` (no longer works)

---

I also wanted to mention that my example above inside **Describe the bug** would have actually worked, kinda.

```ts
const {data: todos} = await useFetch('/api/todos', {key: 'todos'})

const {data: nuxtDataTodos} = useNuxtData<string[]>('todos')
nuxtDataTodos.value = ['replace all todos'] // actually updates todos, but leads to a hydration mismatch
```
Not sure if the hydration mismatch is a "works as intended". But it doesn't happen if you do the exact same thing with todos.value directly. This isn't really my exact issue, simply wanted to let you know.

</details>

**Comment by RomanSkrypnik** [comment]
Facing the same issue, cached data appears to be useless in such situations...

**Comment by RomanSkrypnik** [comment]
Forgot to show code example ( list of roles not supplemented ):
<img width="754" alt="image" src="https://github.com/nuxt/nuxt/assets/44501848/3b187048-05aa-4e12-a8c1-5025a8f34966">

**Comment by RomanSkrypnik** [comment]
Seems I have figured out the problem. Item which has been appended is not transformed into proxy:

<img width="348" alt="image" src="https://github.com/nuxt/nuxt/assets/44501848/8cb994e2-829b-4ecf-b260-19655e26ba82">

**Comment by danielroe** [comment]
Interesting. That may be an upstream Vue issue. Can you reproduce without Nuxt?

**Comment by RomanSkrypnik** [comment]
> Interesting. That may be an upstream Vue issue. Can you reproduce without Nuxt?

My last comment doesn't give an answer. 

I have decided to dig deeper, it seems that `useNuxtData('admin-roles')` and `const { data } = await useAsyncData('admin-roles', () => cb)` - different variables.

useNuxtData('admin-roles') - updates but const { data } = .... - doesn't

**Comment by akbarnafisa** [comment]
hi, I think I'm facing the same issue, my problem is that updating the `tasks` is not possible by overwriting it by using `filter`, but when using an Array method like `.pop` or `.push ` it's working and trigger the UI render

```
const { data: tasks } = useNuxtData<Task[]>('tasks')
 const { data } = await useFetch<Task[]>(
    url,
    {
      method: 'DELETE',
      headers: {
        'Content-Type': 'application/json',
      },
      onRequest() {
        if (tasks.value === null) {
          tasks.value = []
        }
        previousTasks.value = tasks.value
        // tasks.value = tasks.value.filter((task) => task.id !== id) // -> not update the UI
        tasks.value.pop() // -> update the UI
      }
    },
  )
  ```
