### ISSUE TITLE
404 link in documentation (custom router)

### ISSUE THREAD

**Issue by adrienZ** [nuxt/nuxt#19708]
### Environment

https://nuxt.com/docs/guide/directory-structure/pages#custom-routing

### Reproduction

Go to https://nuxt.com/docs/guide/directory-structure/pages#custom-routing and the :ReadMore{link="/docs/guide/going-further/custom-router"} block from documentation leads to a 404 page

### Describe the bug

It should redirect to  /docs/guide/going-further/custom-routing instead of /docs/guide/going-further/custom-router, might be a bug caused by the filename of the document

**Comment by danielroe** [comment]
my mistake! sorry 🤦

**Comment by danielroe** [comment]
resolved in https://github.com/nuxt/nuxt/commit/8d644903bc0b62085dc0de4cd1148f9cadc78ae8
