### ISSUE TITLE
Head (<Title>) components should validate input better

### ISSUE THREAD

**Issue by BD103** [nuxt/nuxt#19716]
### Environment

Reproduced with minimum Nuxt 3 environment on StackBlitz, as well as locally on a MacOS computer with Node 19.

### Reproduction

Link can be found here: https://stackblitz.com/edit/github-umca8w?file=app.vue

A `<Title>` component will use a comment, if specified first, as the actual title.

```vue
<Title><!-- this will be the title --> not this</Title>
```

### Describe the bug

A `<Title>` component will read the first element, even if it is a comment. This causes comments to be displayed as a title, not the intended text afterwords.

**Comment by danielroe** [comment]
The `<Title>` component is only meant to contain text. HTML comments are rendered by Vue as comment vnodes.

**Comment by BD103** [comment]
That's a fair point, but it seems unintuitive and against the design philosophy of Nuxt that this should just be allowed without any warning.

`<Title>` isn't documented anywhere at nuxt.com, and it doesn't seem to be re-exported from Vue either. While you say that the component is only meant to contain text, I could not find any other reference to that in the related documentation.

The one reference I _did_ find was directly in the code, which an error message.

https://github.com/nuxt/nuxt/blob/8d644903bc0b62085dc0de4cd1148f9cadc78ae8/packages/nuxt/src/head/runtime/components.ts#L153-L155

I hope that you can agree that this is should at least be documented better, if not handled by the `setup` code for the component.

While realistically this issue doesn't affect production environments (due to comment stripping being on by default), it still feels like it would be a source of confusion for developers.

**Comment by BD103** [comment]
Is there a specific page that documents the `<Title>` component? I only found mentions on the Nuxt docs when searching for them.
