### ISSUE TITLE
Crash when using %s placeholder in titleTemplate

### ISSUE THREAD

**Issue by command-tab** [nuxt/nuxt#19715]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.17.1`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `app`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

1. Run `npx nuxi@latest init myapp` to create a stock Nuxt app
2. Run `cd myapp`
3. Run `npm i`
4. Remove `app.vue`
5. Add `titleTemplate: 'MyApp'` to the `nuxt.config.ts` app.head section
6. Create `pages/index.vue` containing a template tag and `<script setup lang="ts">useHead({ title: 'Home' })</script>` to set the page title
7. Run `npm run dev` and visit http://localhost:3000
8. Observe that the page's title is "MyApp", reflecting the titleTemplate in `nuxt.config.ts`
9. In `nuxt.config.ts`, change the titleTemplate to `titleTemplate: '%s - MyApp'` to use "%s" as indicated in [the docs](https://nuxt.com/docs/getting-started/seo-meta#title-template) to interpolate the `title` from `index.vue` to set the index page title to "Home - MyApp"
10. Nuxt crashes into the debugger with exception `URIError: URI malformed` in `processTemplateParams` http://localhost:3000/_nuxt/node_modules/unhead/dist/index.mjs

Minimal repro of the above:

https://github.com/command-tab/nuxt331titleTemplateBug

(I tried to create a repro using Stackblitz, and Nuxt indeed crashed there as well, but not in the right place. I think maybe Stackblitz's code is getting in the way.)

### Describe the bug

Nuxt raises a `URIError: URI malformed` exception instead of properly interpolating the page title.

### Additional context

Interestingly, and perhaps critically, the exception happens under Chrome Version 111.0.5563.64 (current), but not Firefox 111.0 (current) or Safari 16.3 (current).

The crash also occurs if the `titleTemplate` containing %s is in `layouts/default.vue` instead of `nuxt.config.ts`, or even just `index.vue` itself right beside the `title`.

**Comment by danielroe** [comment]
cc: @harlan-zw

**Comment by harlan-zw** [comment]
Hey @command-tab, thank you for this amazingly detailed issue :clap: 

I've tried my best to replicate this issue using the steps provided and pulling in your repo and it runs fine for me. (Chrome 111.0.5563.64 (Official Build) (64-bit))

What's strange is that location of the error is quite clear in this bug report, this line would throw it: https://github.com/unjs/unhead/blob/main/packages/unhead/src/plugin/templateParamsPlugin.ts#L20

```ts
 let decoded = s
  try {
    decoded = decodeURI(s)
  }
  catch {}
```

Which is basically just making sure that we don't interpret encoded URI entities as template params, not sure how Chrome would escape the empty catch :thinking: 

Would you mind confirming that you can in fact still reproduce this?

**Comment by command-tab** [comment]
Yup, I can still make it happen. If I do a fresh clone of the above linked repo, `npm i`, `npm run dev`, then visit http://localhost:3000, Chrome again lands in the debugger. Maybe this screenshot will be enlightening with some variable values shown. I see Nuxt is effectively calling `decodeURI("%s - MyApp")`, which when run independently in the console does raise the same exception 🤔  Should the value of `s` at this point include the `%s`, making it seem to Chrome like an invalid escape sequence?

<img width="1535" alt="image" src="https://user-images.githubusercontent.com/3069/225685527-44b9f13d-41ef-49a3-b369-3d89f6148610.png">

**Comment by command-tab** [comment]
Oh, there's my problem right there: I have "Pause on caught exceptions" checked 🤦🏻
