### ISSUE TITLE
about netlify functions MultiValueHeaders 

### ISSUE THREAD

**Issue by KeJunMao** [nuxt/nuxt#19710]
### Describe the feature

I am using `@sidebase/nuxt-auth`, and deploy to netlify.

but the `__Secure-next-auth.state` and `__Secure-next-auth.session-token` in one 'set cookie'

moreinfo :https://answers.netlify.com/t/multiple-set-cookie-headers-cause-netlify-lambda-to-throw-an-error/975/3

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
This sounds like it's a Nitro issue. Would you see if you can reproduce with a minimal nitro setup? 🙏

cc: @pi0
