### ISSUE TITLE
auto-imported utils starting with $ not available inside template

### ISSUE THREAD

**Issue by Mohamadhassan98** [nuxt/nuxt#19718]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.19.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `alias`, `build`, `css`, `components`, `imports`, `modules`, `reactivityTransform`, `runtimeConfig`, `ssr`, `vite`
- Runtime Modules:  `@pinia/nuxt@0.4.6`, `@vue-macros/nuxt@1.2.1`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-mkumh3

### Describe the bug

Utility functions (inside `utils` directory) that includes `$` not working directly inside templates without explicit import (i.e. with auto-import).

I'm not sure if it's intended or not, but at least it should be mentioned in the docs.

### Additional context

The repro tests utils just starting with `$`, but utilities with `$` in the middle don't work either.

**Comment by danielroe** [comment]
cc: @antfu

**Comment by antfu** [comment]
`$` is a reserved prefix in Vue, mainly for global injected context. I'd suggest avoiding using such naming conventions for auto imports. If `$` is strongly preferred, you use a plugin to inject it into the Vue app.
