### ISSUE TITLE
nitro.prerender.ignore outputs javascript code that should be ignored

### ISSUE THREAD

**Issue by hidekatsu-izuno** [nuxt/nuxt#19725]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@9.6.0`
- Builder:          `vite`
- User Config:      `modules`, `historyState`
- Runtime Modules:  `vue-history-state/nuxt`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-d3ixjd?file=package.json

It is set up as below.
```ts:nuxt.config.ts
  nitro: {
    prerender: {
      ignore: ["/restrict/"]
    }
  }
```

Then executes these commands.

```
npm run generate
cat .output/public/_nuxt/private*
```

You can show a private page code.

### Describe the bug

The nuxt configuration page says:
```
exclude: This option is no longer used. Instead, use nitro.prerender.ignore.
```

So. I set up nitro.prerender.ignore option for restricted pages. Indeed HTML is not generated but js code is.

I need a partial generation for confidencial pages.

**Comment by danielroe** [comment]
For this, you can use `ignore` at the top level in your Nuxt config. Any files or patterns specified there will be entirely absent from your build.

**Comment by hidekatsu-izuno** [comment]
@danielroe Thank you for your idea. I was able to implement the next code.

```ts
const isGenerateMode = process.argv.includes('generate')
export default defineNuxtConfig({
  ...(isGenerateMode ? {
    ignore: [
      "**/restrict/**/*",
      "**/*.stories.{js,ts,jsx,tsx}",
      "**/*.{spec,test}.{js,ts,jsx,tsx}",
      "**/*.d.ts",
      ".output",
      "**/-*.*"
    ]
  } : {})
})
```
