### ISSUE TITLE
net::ERR_ABORTED 504 (Gateway Timeout)

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/nuxt#19729]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@9.5.0`
- Builder:          `vite`
- User Config:      `srcDir`, `modules`, `tailwindcss`, `vite`, `nitro`, `schemaOrg`, `telemetry`, `algolia`, `head`, `auth`, `viewport`, `css`, `build`, `runtimeConfig`
- Runtime Modules:  `genesis-design-system/nuxt`, `@nuxtjs/algolia@1.5.0`, `@nuxtjs/tailwindcss@6.6.0`, `formidable@2.1.1`, `nuxt-viewport@2.0.3`, `@nuxtjs/partytown@1.3.0`, `@vueuse/nuxt@9.13.0`, `nuxt-schema-org@2.1.2`, `nuxt-icon@0.1.8`, `@pinia/nuxt@0.4.7`, `@nuxtjs/i18n@8.0.0-beta.10`, `@sidebase/nuxt-auth@0.3.4`
- Build Modules:    `-`

### Reproduction

Vite not runs correctly

![image](https://user-images.githubusercontent.com/77386602/225540721-2892b88e-d5e2-481e-8464-e859a1443f7e.png)

If i press CTRL + F5

![image](https://user-images.githubusercontent.com/77386602/225540823-53d9d8dc-1fe0-498a-8877-197d1c42a285.png)

### Describe the bug

Vite not runs correctly

![image](https://user-images.githubusercontent.com/77386602/225540721-2892b88e-d5e2-481e-8464-e859a1443f7e.png)

If i press CTRL + F5

![image](https://user-images.githubusercontent.com/77386602/225540823-53d9d8dc-1fe0-498a-8877-197d1c42a285.png)

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by agracia-foticos** [comment]
I can't reproduce it in stackblitz.

I see that many files doesn't create in ".vite" folder

![image](https://user-images.githubusercontent.com/77386602/225561950-fa860e0c-7678-4d4a-8729-8ab1a9496ba1.png)

![image](https://user-images.githubusercontent.com/77386602/225561993-f0c274b0-2528-4132-baec-2c3e1ef1ddcc.png)

But i don't know what is the cause

**Comment by agracia-foticos** [comment]
Fail its related with https://www.npmjs.com/package/winston-syslog, i close the issue. Thanks @danielroe !!!

**Comment by babakfp** [comment]
Sorry, but why did I get a notification for this issue? That doesn't make sense.
