### ISSUE TITLE
Throws "nuxt instance unavailable" exception on useState after calling async function 

### ISSUE THREAD

**Issue by alex401401** [nuxt/nuxt#19731]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

1. Create new project:  npx nuxi init bugproject
2. Install the dependencies: npm install
3. Create myclass.ts:
   export class MyClass{
    async func1(){
        useState("h");//OK
        await this.func2();
        useState("h");//Exception nuxt instance unavailable
    }
    async func2(){
    }
}

4. Create plugin plugin.ts:
   import {MyClass} from "@/myclass"
export default defineNuxtPlugin(async (nuxtApp) => {
    const myclass=new MyClass();
    await myclass.func1();
});
       5. Run: npm run dev

### Describe the bug

When executing on a server throws "nuxt instance unavailable" exception on useState after awaiting an async function.
When ssr mode is disabled("ssr":false)  the code work

**Comment by danielroe** [comment]
See https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables for more info at why this is happening.
