### ISSUE TITLE
Nuxt 3 Server Storage with Redis - problem with / in key

### ISSUE THREAD

**Issue by AloisSeckar** [nuxt/nuxt#19744]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v18.14.2`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `npm@8.19.0`
- Builder:          `vite`
- User Config:      `ssr`, `css`, `build`, `hooks`, `modules`, `vite`, `runtimeConfig`, `vue`, `nitro`
- Runtime Modules:  `@pinia/nuxt@0.4.7`
- Build Modules:    `-`

### Reproduction

I don't know how to provide a reproduction of this, because it depends on Redis. Also I think the issue is pretty straightforward.

### Describe the bug

I have Redis integration implemented as shown in the docs:
https://nuxt.com/docs/guide/directory-structure/server#example-using-redis

Basically it works as intented, but we have spotted that for certain object keys

```
useStorage().getItem('redis:key')
```

fails to return value, although the object is present (confirmed through Redis CLI). But we only get `null` in Nuxt.

We are constructing partly artificial keys with some Base64 encoded part. This is legacy and we have to stick with it.

The examples of working keys:
- dmav|xxnovive|AGSPAOCtsWD410JpgCGVhVDlsY0cGA0PBcU3idPesRs=
- dmav|xxnovive|AFkAr7bjQ+rb6tb5yV5wBVDlsY0cGA0PBcU3idPesRs=
- dmav|xxnovive|ADBMajkT+nQEmjpeVi4UIFDlsY0cGA0PBcU3idPesRs=

The examples of failed keys are:
- dmav|xxnovive|AL1nCr5UvG1ZP/pbykebilDlsY0cGA0PBcU3idPesRs=
- dmav|xxnovive|ALSaAlmY/55VTtCQlTVwEFDlsY0cGA0PBcU3idPesRs=
- dmav|xxnovive|AO4qD/sWKgPQcL67mrvYuFDlsY0cGA0PBcU3idPesRs=

I am nearly 100% sure it is because of the slash `/` character inside the Base64 part. When it is here, `useStorage().getItem()` fails to parse it and returns `null`. 

For now we decided to construct another key for our Redis object to aviod encountering `/` in it, but I wanted to ask here whether there is something that can be done about it or if it is intended to work like that? Might be also an issue belonging to some underlaying system rather than here, but I don't know the ecoystem enough yet.

**Comment by danielroe** [comment]
cc: @pi0

**Comment by pi0** [comment]
Both `:` and `/` are reserved as path separators. you might want to consider using `encodeURIComponent` to escape the `/` char.
