### ISSUE TITLE
when build, and open with safari, got 500 Cannot access uninitialized variable.

### ISSUE THREAD

**Issue by KeJunMao** [nuxt/nuxt#19743]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.18.1`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.2.3`
- Package Manager:  `pnpm@7.15.0`
- Builder:          `vite`
- User Config:      `app`, `runtimeConfig`, `typescript`, `modules`, `css`, `colorMode`, `i18n`, `vite`, `elementPlus`, `nitro`
- Runtime Modules:  `@unocss/nuxt@0.50.4`, `@nuxtjs/color-mode@3.2.0`, `@vueuse/nuxt@9.13.0`, `@nuxtjs/i18n@8.0.0-beta.10`, `@element-plus/nuxt@1.0.4`, `nuxt-icon@0.3.3`, `@sidebase/nuxt-auth@0.4.3`
- Build Modules:    `-`

### Reproduction

https://github.com/KeJunMao/ai-anything

### Describe the bug

in dev, it is ok

only use safari(macOS or iPhone), got 500 `Cannot access uninitialized variable.`

**Comment by KeJunMao** [comment]
demo: https://aianything.netlify.app

**Comment by danielroe** [comment]
Would you provide a [_minimal_ reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by azmatzuberi** [comment]
Happening to me to
