### ISSUE TITLE
Images are not loading when we use nuxtLink in nuxt 3

### ISSUE THREAD

**Issue by amantiwari1** [nuxt/nuxt#19746]
### Environment

RootDir: /home/projects/nuxt-starter-cskl2p                                                                22:26:35
Nuxt project info:                                                                                         22:26:35

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                22:26:35

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Reproduction

1) go to https://stackblitz.com/edit/nuxt-starter-cskl2p
2) wait for installation and showing the preview
3) copy website ex `*.webcontainer.io` 
4) create new tab and paste it
5) click `go to image`
6) as you see image is not display
7) refresh this page and image is showing which is expected

### Describe the bug

The image is not loading after click nuxtLink and click refresh image is loading

**Comment by danielroe** [comment]
This isn't a Nuxt issue. Just update the html and you should be good to go:

```diff
      <img
        src="https://clipground.com/images/small-flower-images-1.jpg"
        alt="Cost logo"
-       width="200px"
+       width="200"
+       height="200"
      />
```
