### ISSUE TITLE
useFetch is not executed on init - missing Cookie header

### ISSUE THREAD

**Issue by mateusz-wyka** [nuxt/nuxt#19759]
### Environment

- Operating System: macOS
- Node Version: v16.16.0
- Nuxt Version: 3.2.0
- Package Manager: yarn 1.22.19
- Builder: Vite
- User Config:
- Runtime Modules: 
- Build Modules:

### Describe the bug

I'm using useFetch to fetch data that needs token and session cookies to fetch data properly (for logged user). Data downloads without a problem but only when changing the route. After directly entering the view from the URL or after refreshing the page, nothing happens. I tried fetching data with Axios and there were no problems with it, but I noticed that Axios adds a "Cookie" header and useFetch does not (when changing the route this "Cookie" header exists), so this header does not load on view initialization. I'm not sure somehow adding this header to useFetch for initialization will do anything but I have no idea what to do with it.

Below is a screenshot with the "Cookie" header, which is added to the request every time, but only with the use of Axios.

![obraz](https://user-images.githubusercontent.com/89961396/225829051-56f9e2b2-fff8-415d-a1cc-4828104ab7df.png)

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by agracia-foticos** [comment]
Any Solution?
