### ISSUE TITLE
The html generated by Nuxt 3 is not valid: prefetch cannot be used as a script or style in the link element

### ISSUE THREAD

**Issue by timoanttila** [nuxt/nuxt#19752]
### Environment

- Operating System: `Darwin`
- Node Version: `v16.16.0`
- Nuxt Version: `3.3.1`
- Nitro Version: `2.3.1`
- Package Manager: `yarn@1.22.19`
- Builder:  `vite`
- User Config: `target`, `modules`, `css`, `unocss`, `routeRules`
- Runtime Modules: `@nuxt/content@2.3.0`, `@unocss/nuxt@0.48.4`
- Build Modules: `-`

### Reproduction

https://github.com/timoanttila/timoanttila

### Describe the bug

A link element with an as attribute must have a rel attribute that contains the value preload or the value modulepreload.

The same problem exists in two different projects. Most components / javascripts are preload + module or modulepreload, but for example these three files are loaded differently and this is not correct way to do that.

The same issue exists in two separate projects. Most components / javascripts are preload + module or modulepreload, but these three files are loaded differently, which is incorrect. Perhaps all of the custom components are loaded incorrectly?

My personal website has only these three:
```html
<link rel="prefetch" as="script" crossorigin href="/_nuxt/web-socket.215ff2e0.js">
<link rel="prefetch" as="script" crossorigin href="/_nuxt/asyncData.f44093df.js">
<link rel="prefetch" as="script" crossorigin href="/_nuxt/error-component.542c25fa.js">
```

Another project has 13 incorrectly loaded files.
```html
<link rel="prefetch" as="script" crossorigin href="/_nuxt/Price.cda37566.js">
<link rel="prefetch" as="script" crossorigin href="/_nuxt/ProductCart.c9696fae.js">
```

**Comment by danielroe** [comment]
I believe `as` is a valid attribute for `rel="prefetch"`. What leads you to think differently?

**Comment by timoanttila** [comment]
I use the [W3C html validator](https://validator.w3.org/) to check the source code of the web page.

https://validator.w3.org/nu/?doc=https%3A%2F%2Ftimoanttila.com%2F  
https://validator.w3.org/nu/?doc=https%3A%2F%2Ftuspe.com%2F

**Comment by harlan-zw** [comment]
The validator is strict to the HTML specification which is good, but this particular feature `as="script"` was introduced through chromium to resolve some content security policy issues / accept issues.

Seems like there has been a number of discussions on the topic (i.e https://github.com/validator/validator/issues/901, https://github.com/whatwg/html/issues/5229)

Overall, it does do what is expected of it per MDN docs https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#attributes. 

I don't think there's anything Nuxt can action related to this issue so I'm going to close it. Happy to discuss this further if you have any input though.

**Comment by Ameskosu** [comment]
Is there any way to solve this problem?
