### ISSUE TITLE
Cannot restart nuxt:  Cannot destructure property 'nuxt' of 'undefined' as it is undefined. 

### ISSUE THREAD

**Issue by codekuu** [nuxt/nuxt#19751]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `npm@9.5.0`
- Builder:          `vite`
- User Config:      `ssr`, `app`, `build`, `components`, `css`, `dir`, `experimental`, `imports`, `modules`, `nitro`, `srcDir`, `vite`
- Runtime Modules:  `@pinia/nuxt@0.4.7`, `@vueuse/nuxt@9.13.0`, `~/modules/primevue`, `@nuxtjs/device@3.1.0`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-x32cwg

### Describe the bug

So it seems like hooks.'build:before' can not provide the nuxt like it did before in the router.ts file?
This started to happen after upgrading from 3.1.0 to 3.3.0 in a already established project.

### Logs

```shell-script
=== NPM INSTALL ===
1423 timing command:install Completed in 6428ms
1424 verbose stack Error: command failed
1424 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
1424 verbose stack     at ChildProcess.emit (node:events:513:28)
1424 verbose stack     at maybeClose (node:internal/child_process:1091:16)
1424 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
1425 verbose pkgid project@1.0.0
1426 verbose cwd /home/XXXX/project
1427 verbose Linux 4.19.0-17-amd64
1428 verbose node v18.15.0
1429 verbose npm  v9.6.2
1430 error code 1
1431 error path /home/XXXX/project
1432 error command failed
1433 error command sh -c nuxi cleanup && nuxi prepare 





=== NPM RUN DEV (nuxi dev)) =====
ERROR  Cannot start nuxt:  Cannot destructure property 'nuxt' of 'undefined' as it is undefined.                                                                                                                              21:07:36

  at build:before (src/modules/router.ts:37:33)
  at node_modules/hookable/dist/index.mjs:48:66
  at Object.run (node_modules/hookable/dist/index.mjs:41:43)
  at node_modules/hookable/dist/index.mjs:48:56
  at async build (node_modules/nuxt/dist/index.mjs:2925:3)
  at async Promise.all (index 1)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6850:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6873:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:49:20)
```

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

It sounds like you are using a Nuxt 2 module that is not compatible with Nuxt 3.

**Comment by codekuu** [comment]
@danielroe 
> Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
> 
> It sounds like you are using a Nuxt 2 module that is not compatible with Nuxt 3.

Updated the bug report with a link to stackblitz where the error occur (router.ts) is the problem

**Comment by danielroe** [comment]
Thank you. `build:before` is not called with any arguments in Nuxt 3. This has been the case since v3.0.0.

**Comment by codekuu** [comment]
Weird, it worked on 3.1.0. Did it get replaced by something which also provides the { nuxt }?

**Comment by codekuu** [comment]
@danielroe that is not true.
Downgraded the reproduction stackblitz from 3.3.0 to 3.1.0 and it works. So I guess this is a bug.

If it got removed, did it get replaced with something?

**Comment by danielroe** [comment]
Here is the code where that hook is called in v3.0.0: https://github.com/nuxt/nuxt/blob/v3.0.0/packages/nuxt/src/core/builder.ts#L33-L37.

You can see the documentation here: https://nuxt.com/docs/api/advanced/hooks.

This hook does not receive any arguments.

The difference in the previous repo is that now in v3.3, modules are automatically registered. Previously, that module was never running so it did not throw an error. Just add the following code to your `nuxt.config` to see the same issue:

```js
  modules: [
    '~/modules/router'
  ]
```
