### ISSUE TITLE
Nuxi 3.3.1 error on nuxt prepare Windows 11

### ISSUE THREAD

**Issue by zayaserg** [nuxt/nuxt#19764]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.14.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `pnpm@7.29.3`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

pnpm dlx nuxi init <project-name>
![image](https://user-images.githubusercontent.com/27950837/225881840-e9bc07bc-1f84-4195-978f-b8d3b8efdb71.png)

### Describe the bug

after init project on version 3.3.1 I get an error on postinstall script
on version 3.3.0 I have another error
on version 3.2.3 all works fine

**Comment by danielroe** [comment]
I cannot reproduce this on Windows. Would you provide more info? Does it also do this if you run `npx nuxi@latest`?

**Comment by zayaserg** [comment]
with npx nuxi@latest all works, thk

**Comment by danielroe** [comment]
I also cannot reproduce with `pnpm dlx nuxi@latest` either, so I think it might be a cache issue.

**Comment by zayaserg** [comment]
pnpm dlx nuxi@latest also works I checked, it might be a cache
