### ISSUE TITLE
middleware is loaded before plugins

### ISSUE THREAD

**Issue by productdevbook** [nuxt/nuxt#19766]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `pnpm@7.29.3`
- Builder:          `vite`
- User Config:      `ignore`, `ssr`, `modules`, `ionic`, `imports`, `huntersofbookI18n`, `pinia`, `i18n`, `tailwindcss`, `colorMode`, `vite`, `typescript`, `css`, `build`
- Runtime Modules:  `@pinia/nuxt@0.4.7`, `@nuxtjs/i18n@8.0.0-beta.10`, `@nuxtjs/tailwindcss@6.6.0`, `nuxt-icon@0.3.3`, `nuxt-headlessui@1.1.1`, `@nuxtjs/color-mode@3.2.0`, `@nuxtjs/fontaine@0.2.4`, `@huntersofbook/plausible-nuxt@0.5.2`, `@vueuse/nuxt@9.13.0`, `@nuxtjs/ionic@0.8.1`, `@huntersofbook/i18n/nuxt@0.5.1`, `@nuxt/content@2.5.2`, `@nuxt/devtools@0.2.5`, `@vue-macros/nuxt@1.2.3`, `@huntersofbook/naive-ui-nuxt@0.7.1`
- Build Modules:    `-`
------------------------------

### Reproduction

**Github** https://github.com/productdevbook/nuxt3bug1

### Describe the bug

pnpm dev

console.log see first middleware after plugin.

but it should be the other way around. Plugins should come first and then middleware should come.

### Additional context

![image](https://user-images.githubusercontent.com/38668796/225905618-ee25749e-0cb6-48b8-85ce-2dee02967b24.png)

**Comment by productdevbook** [comment]
update mini reproduction commit.

**Comment by productdevbook** [comment]
i hink problem nuxt/ionic https://github.com/nuxt-modules/ionic/issues/287

**Comment by RealDyllon** [comment]
@danielroe Is there a reason this has been marked as not planned?

**Comment by danielroe** [comment]
this is not a bug - middleware are not loaded before plugins

**Comment by RealDyllon** [comment]
@danielroe Thanks for clarifying! I can also confirm that middleware is working as expected. Appreciate the prompt response!
