### ISSUE TITLE
In a nested route, the child route cannot disable the layout used by the parent route

### ISSUE THREAD

**Issue by hanpandeng** [nuxt/nuxt#19762]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.18.1`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `app`, `css`, `postcss`, `typescript`, `build`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

[https://stackblitz.com/edit/github-bzckfe?file=pages/index.vue](url)

### Describe the bug

In a nested route, the child route cannot disable the layout used by the parent route

code :
pages/parent.vue
`<template>
  <div>
    <NuxtLayout name="parentLayout">
      <p>parent route</p>
      <NuxtLink to="/parent/child1">child1</NuxtLink>
      <NuxtLink to="/parent/child2">child2</NuxtLink>
      <NuxtPage />
    </NuxtLayout>
  </div>
</template>
`
pages/parent/child1.vue
`<template>
  <div>child 1</div>
</template>`

pages/parent/child2.vue
`<template>
  <div>child 2</div>
</template>

<script setup lang="ts">
definePageMeta({
  layout: false,
});
</script>`

layouts/parentLayout.vue
`<template>
  <div>
    <h1>LAYOUTS</h1>
    <slot></slot>
  </div>
</template>`

**Comment by danielroe** [comment]
The issue is that you are taking over full control of layouts with `<NuxtLayout name="parentlayout">`. You will need to write your own logic in this case to decide the layout that component renders.

By default, Nuxt does allow child routes to disable the layout, if using `<NuxtLayout>` without specifying a layout name.

**Comment by hanpandeng** [comment]
> The issue is that you are taking over full control of layouts with `<NuxtLayout name="parentlayout">`. You will need to write your own logic in this case to decide the layout that component renders.
> 
> By default, Nuxt does allow child routes to disable the layout, if using `<NuxtLayout>` without specifying a layout name.

What can I do in this case to disable the layout used by the parent route in the child route

**Comment by danielroe** [comment]
You could do something like `<NuxtLayout :name="$route.meta.layout !== false ? 'parentlayout' : false">`.

**Comment by hanpandeng** [comment]
> You could do something like `<NuxtLayout :name="$route.meta.layout !== false ? 'parentlayout' : false">`.

thanks

**Comment by danielroe** [comment]
You are welcome.
