### ISSUE TITLE
Nitro `netlify-builder` preset is incompatible with Nuxt

### ISSUE THREAD

**Issue by varna** [nuxt/nuxt#19774]
### Environment

1:55:41 PM: [log] Nuxi 3.2.3
1:55:42 PM: [log]
1:55:42 PM: [log] RootDir: /opt/build/repo
1:55:42 PM: [log] Nuxt project info:
1:55:42 PM: ------------------------------
1:55:42 PM: - Operating System: `Linux`
1:55:42 PM: - Node Version:     `v16.19.1`
1:55:42 PM: - Nuxt Version:     `3.2.3`
1:55:42 PM: - Nitro Version:    `2.2.3`
1:55:42 PM: - Package Manager:  `npm@8.19.3`
1:55:42 PM: - Builder:          `vite`
1:55:42 PM: - User Config:      `-`
1:55:42 PM: - Runtime Modules:  `-`
1:55:42 PM: - Build Modules:    `-`
1:55:42 PM: ------------------------------

### Reproduction

Any POST request to deployed version of https://euphonious-toffee-792022.netlify.app with `NITRO_PRESET=netlify-builder` fails with `405 Method Not Allowed`.

https://stackblitz.com/edit/github-dyha25?file=package.json

### Describe the bug

The current implementation of Nitro `netlify-builder` preset is incompatible with Nuxt. 

> [On-demand Builders accept GET requests only.
They don’t provide access to HTTP headers or query parameters from incoming requests.](https://docs.netlify.com/configure-builds/on-demand-builders/)

This means that On-demand Builders should only be used on **pages** without query params. This explains why any other request than GET gets refused by `405 Method not Allowed` https://github.com/nuxt/nuxt/issues/19505. This also explains why modules like `@nuxt/image-edge` and `@nuxtjs/i18n` fail when deployed.

**Comment by danielroe** [comment]
The default `netlify` preset will use Netlify builder routes for all routeRules marked as `swr: true`. This may assist you.

**Comment by varna** [comment]
Cool, it works. Thanks @danielroe

Do I need anything more than `swr: false` to disable it for all child routes? Because 
```
  routeRules: {
    '/**': { swr: true },
    '/api/**': { cors: true, swr: false },
  },
```
seems to keep failing while 
```
  routeRules: {
    '/blog/**': { swr: true },
    '/api/**': { cors: true },
  },
  ```
works properly

**Comment by danielroe** [comment]
You do need to set `cache: false, swr: false` to disable swr.

**Comment by danielroe** [comment]
Adding more tests would be very welcome, either upstream in https://github.com/unjs/nitro directly or perhaps in https://github.com/unjs/nitro-deploys. Maybe also some more documentation for the netlify preset upstream in nitro repository? I think this issue can be closed, however.

**Comment by Stiropor** [comment]
@danielroe Here is a reproduction:
https://github.com/EngageFactory/swrtest

Also built on Netlify: https://swrtest.netlify.app/

By default compatibilityDate was 2024-11-01, build fails. When changed to 2024-04-01 build works but when doing a POST returns 504. When doing normal deploy without preset it works.

As I understood `swr: false` should render /api routes normaly. But it doesn't.

This might be similar issue to:
https://github.com/nuxt/nuxt/issues/25418
https://github.com/nitrojs/nitro/issues/2617

**Comment by danielroe** [comment]
@Stiropor  would you mind opening a new issue? this one is 2 years old and unlikely to be the same one even if the symptoms seem similar

In particular, would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏
