### ISSUE TITLE
When trying to install npx nuxi@latest init myproj I got a typeError fetch failed

### ISSUE THREAD

**Issue by lfazliev** [nuxt/nuxt#19780]
![image](https://user-images.githubusercontent.com/72712408/226074644-40f5dbda-7ae7-4291-a7db-a5f8fc4b8a2e.png)
![image](https://user-images.githubusercontent.com/72712408/226074737-4bb2b988-c672-4968-8e2c-1f399aeef518.png)
Hi I have problems installing, there were attempts to change dns to 1.1.1.1, 8.8.8.8, 8.8.4.4 and 114.114.114.114, also tried vpn. 
Firewall disabled. Nothing helped.
I will be grateful for your help

**Comment by danielroe** [comment]
Do you have a proxy?

**Comment by lfazliev** [comment]
No, I don't use a proxy

> Do you have a proxy?

**Comment by UchVuch** [comment]
i faced the same problem
![image](https://user-images.githubusercontent.com/85136486/228962461-af1d3042-aead-4bdc-8287-4c87503edd45.png)

**Comment by aaliboyev** [comment]
Any news on this problem? I'm also facing this problem on windows

**Comment by manniL** [comment]
This is usually an issue with your firewall/VPN or proxy. There were a few issues around that, e.g. https://github.com/nuxt/nuxt/issues/21853

**Comment by lfazliev** [comment]
Translating the user folder name from Russian to English helped
