### ISSUE TITLE
Loading 3rd party scripts with custom attribute

### ISSUE THREAD

**Issue by johnexzy** [nuxt/nuxt#19788]
How can i add external scripts with custom attributes in the script tag

```html
<script src="https://utteranc.es/client.js"
        repo="[ENTER REPO HERE]"
        issue-term="title"
        theme="github-dark"
        crossorigin="anonymous"
        async>
</script>

```

I have tried this, but properties ``repo``, ``issue-term,`` and ``theme`` does not exist in type ``Script`` 
```ts
useHead({
    script: [
        {
            src: 'https://utteranc.es/client.js',
            crossorigin: 'anonymous',
            async: true,
            "issue-term": 'title',
            repo: 'johnexzy/utterances',
            theme: 'github-dark',
        }
    ]
})
```

**Comment by danielroe** [comment]
cc: @harlan-zw

**Comment by danielroe** [comment]
It looks like this is just about the types - the rendered HTML is as you wish:

```html
<script src="https://utteranc.es/client.js" crossorigin="anonymous" async="" issue-term="title" repo="johnexzy/utterances" theme="github-dark">
```

I think the types are right to complain, as these attributes are not spec-compliant for a `<script>` tag, but you can choose to ignore them by adding `as any` after the script object:

```ts
useHead({
  script: [
    {
      src: 'https://utteranc.es/client.js',
      crossorigin: 'anonymous',
      async: true,
      'issue-term': 'title',
      repo: 'johnexzy/utterances',
      theme: 'github-dark'
    } as any
  ]
})
```

@harlan-zw may have another point of view.

**Comment by johnexzy** [comment]
Cool @danielroe

**Comment by harlan-zw** [comment]
That looks correct @danielroe 

This intentionally throws a type issue as you shouldn't use arbitrary keys for custom attributes, you should prefix them with `data-`, according to the HTML spec (IIRC).
