### ISSUE TITLE
Cloudflare  workers.api.error.script_too_large [code: 10027]

### ISSUE THREAD

**Issue by aligzl** [nuxt/nuxt#19790]
### Environment

Hi All,

I am having issue while deploying to cloudflare as falow;
![cloudflare](https://user-images.githubusercontent.com/25938285/226115871-055cf199-747b-4521-8d05-d5daf6a03fda.png)

Thanks

### Reproduction

https://stackblitz.com/edit/github-wu5ioh?file=wrangler.toml

### Describe the bug

 workers.api.error.script_too_large [code: 10027]

### Logs

```shell-script
Here are the 2 largest dependencies included in your script:

  - .output/server/index.mjs - 2010.18 KiB
  - wrangler-module-CompiledWasm:./26c174f66255792aa5c733cf3ab740b54120c2b7-svg2png.wasm - 0.56 KiB
  If these are unnecessary, consider removing them



X [ERROR] A request to the Cloudflare API (/accounts/adasdasdasdasdasdasd/workers/scripts/meypa-ricaret) failed.

  workers.api.error.script_too_large [code: 10027]

  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose
```

**Comment by danielroe** [comment]
The linked reproduction does not reproduce your issue.
