### ISSUE TITLE
useAsyncData not executed after change query param with navigateTo function

### ISSUE THREAD

**Issue by kaboume** [nuxt/nuxt#19803]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `modules`, `css`, `build`, `vite`, `app`, `auth`
- Runtime Modules:  `@pinia/nuxt@0.4.7`, `@pinia-plugin-persistedstate/nuxt@1.0.0`, `@sidebase/nuxt-auth@0.4.2`
- Build Modules:    `-`
------------------------------

### Reproduction

Hi,
I have a video list with a pagination system.
When, the user change the page number with the pagination component, I want to change the query param of the page and I wonder that useAsyncData will be executed after but it's not the case.

```
<script setup>
const config = useRuntimeConfig()
const route = useRoute()
const router = useRouter()
const page = ref(route.query.page ? parseInt(route.query.page) : 1)

const { data: videos, refresh, error } = await useAsyncData('videos', async () => {
  const url = `${config.API_BASE_URL}videos?page=${page.value}`
  return $fetch(url, { server: false })
},
)

const changePage = async () => {
  await navigateTo({
    path: '/my-videos',
    query: {
      page: page.value,
    },
  })
}
</script>

<template>
  <v-container>
    <h1>Vidéos</h1>
    <v-row>
      <v-col cols="12" lg="8">
        <div>
          <v-pagination v-model="page" :length="videos.totalPages" @update:modelValue="changePage" />
          <video-preview v-for="video in videos.results" :key="video.id" :video="video" />
....
```

### Describe the bug

The query param page has been updated but behind the useAsyncData with the new page number is not executed

**Comment by danielroe** [comment]
For this, we have a `watch` option you can pass to `useAsyncData`.
