### ISSUE TITLE
Error while running "nuxt prepare": The "name" argument must be specified

### ISSUE THREAD

**Issue by sshwy** [nuxt/nuxt#19806]
### Environment

- Operating System: `Linux`
- Node Version:     `v19.6.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `yarn@3.4.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

run "nuxi prepare" using node v19.6.0 at startup's v3

### Describe the bug

as the title says.

### Additional context

After inspecting the code at `node_modules/@nuxt/kit/dist/index.mjs:168:30`，I add a arbitrary name to the parameter of `performance.mark` method, and it works.

### Logs

```shell-script
# This file contains the result of Yarn building a package (root-workspace-0b6124@workspace:.)
# Script name: postinstall

Nuxi 3.3.1

 ERROR  The "name" argument must be specified

  at new NodeError (node:internal/errors:399:5)
  at Performance.mark (node:internal/perf/performance:125:13)
  at normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:168:30)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:451:15)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:2469:7)
  at async loadNuxt (node_modules/nuxt/dist/index.mjs:2523:5)
  at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:539:19)
  at async Object.invoke (node_modules/nuxi/dist/chunks/prepare.mjs:37:18)
  at async _main (node_modules/nuxi/dist/cli.mjs:49:20)
```

**Comment by Jonashr** [comment]
Similar problem here, I am not sure if it the same but it looks like it is coming from the same source. I tried redeploying a build on Vercel from last week that was already working. I changed an environment variable and triggered a redeploy, and now it won't deploy.

I have tried deploying other working branches as well, but it isn't working.

Here's the output from the build step:

```
> build
--
10:14:47.810 | > nuxi build
10:14:47.810 |  
10:14:47.928 | [log] Nuxi 3.3.1
10:14:47.962 | [log] Nuxt 3.3.1 with Nitro 2.3.1
10:14:49.890 | [error] Cannot read property 'name' of undefined
10:14:49.890 | at normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:170:122)
10:14:49.891 | at async installModule (node_modules/@nuxt/kit/dist/index.mjs:451:15)
10:14:49.891 | at async initNuxt (node_modules/nuxt/dist/index.mjs:2469:7)
10:14:49.891 | at async loadNuxt (node_modules/nuxt/dist/index.mjs:2523:5)
10:14:49.891 | at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:539:19)
10:14:49.891 | at async Object.invoke (node_modules/nuxi/dist/chunks/build.mjs:41:18)
10:14:49.892 | at async _main (node_modules/nuxi/dist/cli.mjs:49:20)
10:14:49.920 | Error: Command "npm run build" exited with 1
10:14:50.172 | BUILD_UTILS_SPAWN_1: Command "npm run build" exited with 1

```

**Comment by joulev** [comment]
Same here as well, on macOS. The error is thrown in Node.js v19, switching Node.js version to v18 makes it work.

**Comment by danielroe** [comment]
See https://github.com/nuxt/nuxt/issues/19682 for more details. This has been resolved in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/), or in the next release.

For now you can downgrade to node 18.
