### ISSUE TITLE
What is the implementation of nuxtServerInit in nuxt3?

### ISSUE THREAD

**Issue by gllinzbk1** [nuxt/nuxt#19810]
### Describe the feature

Vuex's nuxtServerInit, anything in Pinia

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [ ] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [ ] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
You can create a `~/plugins/myplugin.server.ts`. This will run once, on the server.

**Comment by gllinzbk1** [comment]
> You can create a `~/plugins/myplugin.server.ts`. This will run once, on the server.

by hook,or others,can you give me a code demo,ths

**Comment by mavrick** [comment]
how to set the vuex state using server only plugin like we could with `nuxtserverinit` ?

**Comment by gllinzbk1** [comment]
> how to set the vuex state using server only plugin like we could with `nuxtserverinit` ?

just ~/plugins/myplugin.server.ts. This will run once, on the server.

 i need get header and footer data ,just once on `npm run generate` 
but now i see get data once every page ,data by contentful, so `npm run generate`  slow,and maybe fail
 @marr
