### ISSUE TITLE
document `event.$fetch`/`useRequestFetch`

### ISSUE THREAD

**Issue by danielroe** [nuxt/nuxt#19815]
follow up from https://github.com/nuxt/nuxt/pull/19357

**Comment by mihul87** [comment]
I want to look at it

**Comment by adamdehaven** [comment]
@danielroe just resurfacing this issue I stumbled upon after we spoke a few weeks ago. 

If the documentation for `event.fetch` and `useRequestFetch` can be added to the Nuxt docs (even something simple for now just documenting that they even exist 😬), I think it would be very beneficial, especially for those trying to implement their own auth flows, etc.

**Comment by mihul87** [comment]
I want to look at it
