### ISSUE TITLE
Seems to have a memory leek

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt/nuxt#19824]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `pnpm@7.29.0`
- Builder:          `vite`
- User Config:      `app`, `extends`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

A normal repo https://github.com/aneoconsulting/ArmoniK.Admin.GUI/tree/main/.docs
The working CI https://github.com/aneoconsulting/ArmoniK.Admin.GUI/actions/workflows/deploy-docs.yml

A repo with potential memory leaks https://github.com/aneoconsulting/armonik-docs-theme
The broken CI https://github.com/aneoconsulting/armonik-docs-theme/actions/workflows/deploy-docs.yml

### Describe the bug

Hello,

Since I update to Docus 1.9.9 and to Nuxt 3.3.1, I noticed a huge usage of ram.

With the normal repo, my computer use up to 1.5Go of RAM but with the broken repo, I use up to 3Go (and the GitHub runner failed). Not sure if it come from Nuxt or from Docus. I will continue to investigate but I will be unable to resolve this.

Thanks

**Comment by Barbapapazes** [comment]
Reverting nuxt to 3.2.3 and Docus to 1.9.0 works well.

**Comment by Barbapapazes** [comment]
With Docus 1.9.0 and Nuxt 3.3.1, max RAM usage at 3.5Go
With Docus 1.9.9 and Nuxt 3.2.3, max RAM usage at 3.5Go
With Docus  1.9.0 and Nuxt 3.2.3, max RAm usage at 3.5Go

Use the build command in my armonik-docs-theme repo on windows.

Using GitHub Runner, 
With Docus 1.9.9, Nuxt 3.2.3, https://github.com/esoubiran-aneo/armonik-docs-theme-1/actions/runs/4470709281/jobs/7854625085, it's work
With Docus 1.9.9, Nuxt 3.3.1, https://github.com/esoubiran-aneo/armonik-docs-theme-1/actions/runs/4470741942/jobs/7854699682,it's failed with a core dump (JavaScript heap out of memory)

@Atinux

**Comment by danielroe** [comment]
This might be linked to https://github.com/nuxt/nuxt/issues/19783, which is caused by an upstream issue in rollup. Would you try pinning rollup to 3.18.0?

**Comment by Barbapapazes** [comment]
It works with rollup 3.18.0 https://github.com/esoubiran-aneo/armonik-docs-theme-1/actions/runs/4471070531/jobs/7855462227 @danielroe
