### ISSUE TITLE
[nuxt] [layer] cannot build layer when <picture> <source> srcset uses image from public/ folder

### ISSUE THREAD

**Issue by akasection** [nuxt/nuxt#19838]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `pnpm@7.29.0`
- Builder:          `vite`
- User Config:      `alias`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Add some image to `public/` folder, and then use that in any component (for example: `public/img/something.png`

```
<template>
  <section>
    <h1>Hello World!</h1>
    <picture>
      <source
        srcset="/img/something.png"
        type="image/png"
      >
      <img src="/img/something.png">
    </picture>
  </section>
</template>
```

Sandbox 1: https://stackblitz.com/edit/nuxt-starter-6ohvtk?file=README.md
Sandbox 2: https://codesandbox.io/p/sandbox/agitated-cache-66k961

### Describe the bug

The error is:

```
 ERROR  [vite]: Rollup failed to resolve import "/img/something.png" from "/home/user/git/sample-nuxt-layer/components/HelloWorld.vue?vue&type=script&setup=true&lang.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
build.rollupOptions.external
```

### Additional context

It seems there is a workaround, by registering alias and use the alias instead, but it raises another error.

```typescript
// nuxt.config.ts
import { createResolver } from '@nuxt/kit'

const { resolve } = createResolver(import.meta.url)

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  alias: {
    '#layer/img': resolve('./public/img'),
  }
})
```

```vue
// component.vue
<template>
  <section>
    <h1>Hello World!</h1>
    <picture>
      <source
        srcset="#layer/img/something.png"
        type="image/png"
      >
      <img src="#layer/img/something.png">
    </picture>
  </section>
</template>
```

The error: 
```
Unexpected "const"
2  |  import { createElementVNode as _createElementVNode, unref as _unref, toDisplayString as _toDisplayString, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"
3  |  
4  |  const _hoisted_1 = 
   |                      ^
5  |  const _hoisted_2 = /*#__PURE__*/_createElementVNode("h1", null, "Hello World!", -1)
   |  ^
6  |  const _hoisted_3 = /*#__PURE__*/_createElementVNode("picture", null, [
```

**Comment by fyyyyy** [comment]
maybe related
https://github.com/vitejs/vite/issues/7300

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by mvdschee** [comment]
@danielroe I got the same issue, so here is a demo [nuxt layer demo](https://stackblitz.com/edit/nuxt-starter-6ohvtk?file=README.md). The problem is only happening with a `pnpm build`. I hope the demo helps.

**Comment by AlissonRA** [comment]
Same error with me, any updates?

**Comment by akasection** [comment]
It's not reproducible on dev, but same as above, it happens on build.

Here's the sandbox link: https://codesandbox.io/p/sandbox/agitated-cache-66k961

**Comment by Julien-Martin** [comment]
Still a bug in 3.6.5

https://stackblitz.com/edit/github-xpbysw?file=nuxt.config.ts

**Comment by danielroe** [comment]
@Julien-Martin That's a different issue. (It's sort of the inverse.) Would you raise a new issue with that repro?
