### ISSUE TITLE
[nuxt] [request error] [unhandled] [500] Maximum call stack size exceeded

### ISSUE THREAD

**Issue by nzuyanov** [nuxt/nuxt#19837]
### Discussed in https://github.com/nuxt/nuxt/discussions/19742

<div type='discussions-op-text'>

<sup>Originally posted by **nzuyanov** March 16, 2023</sup>
Hi all! I need to manually split chunks in my project. Following the rollup documentation I used the `vite.build.rollupOptions.output.manualChunks` property of nuxt config.
But after running ```npm run generate```, I see a lot of errors in the console.

```
 ERROR  [nuxt] [request error] [unhandled] [500] Maximum call stack size exceeded
  at getModuleDependencies (file://./node_modules/vue-bundle-renderer/dist/runtime.mjs:56:24)  
  at getModuleDependencies (file://./node_modules/vue-bundle-renderer/dist/runtime.mjs:77:21)  
  at getModuleDependencies (file://./node_modules/vue-bundle-renderer/dist/runtime.mjs:77:21)  
  at getModuleDependencies (file://./node_modules/vue-bundle-renderer/dist/runtime.mjs:77:21)  
```

I decided to test the behavior on the latest version of nuxt and separate `vue` (for example) into a separate chunk, and the rest of `node_modules` into `vendors` chunk. The same error appeared in the console.

Maybe I'm doing something wrong, but it could be a bug.

### Environment
Nuxt Version: `3.3.1`
Nitro Version: `2.3.1`
Builder: `vite`

### Reproduction
https://stackblitz.com/edit/github-qwhmub?file=nuxt.config.ts</div>

**Comment by hi-reeve** [comment]
any workaround on this?

**Comment by voskresla** [comment]
fixed in vue-bundle-renderer@1.03 -> @nuxt@3.3.2

**Comment by voskresla** [comment]
@danielroe i think this fix broke production build https://github.com/nuxt/nuxt/issues/20058 (

**Comment by sonofmagic** [comment]
related https://github.com/unjs/jiti/issues/89#issuecomment-1566076052
