### ISSUE TITLE
SSR'd HTML attributes do not change order when the order of parent elements changes client-side

### ISSUE THREAD

**Issue by juliesaia** [nuxt/nuxt#19836]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `routeRules`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-wqxm4s?file=pages/index.vue

### Describe the bug

Pretty weird bug, I'll try my best to clearly explain:

If you server-side render a list of elements with `v-for`, then change the order of the list on the client side, the elements and their contents will change order, but any HTML attributes will not.

For example in the minimal repro I render 3 cards with URLs in `<a>` tags. There's a sort call that happens only on the server side, inside `if (process.server)`. So what should happen is that the server renders the cards in reverse order, but the client renders them in normal order.

What actually happens is that the cards render in the normal order, but the `href` attributes don't change places. The card for google.com has an href of youtube.com:
![image](https://user-images.githubusercontent.com/76669473/226515166-426a4ce0-05ac-4432-9537-2f503c84327a.png)

### Additional context

I came across this bug working on my site https://www.rivalsesports.com/, it has a list of weekly tournaments sorted as a function of the current date. It gets server side rendered one way, and over time the order changes but the image/link src/href's don't change accordingly.

**Comment by danielroe** [comment]
Looking at this, I think this is Vue hydration behaviour. Basically server + client HTML should match, at least on first render. But things like randomisation or sorting can change that, as in your case. When they don't match, you can get odd behaviour, like HTML attributes appearing to belong to the wrong elements.

The solution is to ensure that any changes to data (such as sorting) happen in `onMounted`, _after_ the initial hydration step.
