### ISSUE TITLE
baseURL breaks dynamic img src to public directory in production

### ISSUE THREAD

**Issue by warflash** [nuxt/nuxt#19833]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `app`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/warflash/nuxt-baseURL-dynamic-public-path

build for production and run

### Describe the bug

Static path declarations are correctly prefixed with the baseURL, however the same issue as mentioned [here](https://github.com/nuxt/nuxt/issues/15689) arises when combining a dynamic :src and setting baseURL 

### Additional context

![image](https://user-images.githubusercontent.com/22006082/226451180-cafe6a7a-9ea0-4e7f-b235-38ab5d373e19.png)

Img 1:
![image](https://user-images.githubusercontent.com/22006082/226452410-46770831-9af0-4f8f-8cb2-f17406b77e5a.png)

Img 2:
![image](https://user-images.githubusercontent.com/22006082/226452368-677279eb-3095-4cda-86ef-c878da573fc0.png)

**Comment by danielroe** [comment]
This is upstream vite behaviour. Because `'/img/' + 1 + '.webp'` can't be statically analysed as a public asset (by vite's analyser anyway), vite leaves it untouched and Nuxt can't prefix it with `baseURL`. This might be worth investigating in https://github.com/vitejs/vite if this is a feature you need.

**Comment by warflash** [comment]
Ah I see, good to know it's a vite thing.
We ended up creating a composable that pulls in $config.app.baseURL from nuxt and prepends that to the src, maybe that's useful for future readers.
The solution proposed by vite [here](https://github.com/vitejs/vite/issues/10601) is for sure not something we want to do so guess we'll stick to the composable.
Thanks @danielroe 😊
