### ISSUE TITLE
scrollBehavior does not scrollToTop between regular and nested page

### ISSUE THREAD

**Issue by mrleblanc101** [nuxt/nuxt#19848]
### Environment

  System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 69.81 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: 1.22.19 - ~/www/showbizz/frontend/node_modules/.bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Chrome Canary: 113.0.5665.2
    Firefox: 110.0.1
    Safari: 16.3
    Safari Technology Preview: 16.4
  npmPackages:
    nuxt: ^2.15.8 => 2.16.3

### Reproduction

Coming

### Describe the bug

A) When navigating between sibblings nested pages, Nuxt should not scrollToTop. This is currently the correct behavior. ✅ 
![2023-03-21 14 36 33](https://user-images.githubusercontent.com/17392251/226709185-641bd30b-faca-4865-872f-878e2b801867.gif)

B) When I navigate between a regular page to a nested page, Nuxt should scrollToTop.
Currently incorrect, nuxt doesn't scrollToTop. 🛑 
![2023-03-21 14 36 13](https://user-images.githubusercontent.com/17392251/226709387-540f132e-75fe-4911-949d-d5aef5e81842.gif)

C) If I add `scrollToTop: true`, then it break behavior A because it will scrollToTop even when navigating between nested pages which are Tabs in my case. 🛑 
![2023-03-21 14 46 04](https://user-images.githubusercontent.com/17392251/226710819-b5886297-9fd6-4cc9-b47c-e8fe644c5e38.gif)

### Additional context

This is probably related to `scrollBehavior`, because the `some` will now always return true even if I added `scrollToTop` to the parent page only and non of the children pages.
```
function shouldScrollToTop(route) {
    const Pages = getMatchedComponents(route);
    console.log(Pages);
    if (Pages.length === 1) {
        const { options = {} } = Pages[0];
        return options.scrollToTop !== false;
    }
    return Pages.some(({ options }) => options && options.scrollToTop);
}
```

**Comment by mrleblanc101** [comment]
I've changed ` const isRouteChanged = to !== from` to `const isRouteChanged = to.matched[0] !== from.matched[0];` inside `router.scrollBehavior.js` and I added `scrollToTop: true` to my nested route parent route.
```
 {
    path: '/series/:slug',
    component: FicheSerie, // <--- FIX: Add `scrollToTop: true` inside this component.
    meta: { section: 'tele', series: true },
    children: [
        {
            path: '',
            name: 'serie-apercu',
            component: SerieApercu,
        },
        {
            path: 'distribution-et-equipe',
            name: 'serie-distribution',
            component: SerieDistribution,
        },
        {
            path: 'episodes',
            name: 'serie-episodes',
            component: SerieEpisodes,
        },
        {
            path: 'prix-et-distrinctions',
            name: 'serie-prix',
            component: SeriePrix,
            meta: {
                type: 'tvshows',
            },
        },
        {
            path: 'actualites-et-critiques',
            name: 'serie-actualites',
            component: SerieActualites,
        },
        {
            path: 'photos-et-videos',
            name: 'serie-medias',
            component: SerieMedias,
            meta: {
                type: 'tvshows',
            },
        },
    ],
},
```
![2023-03-21 15 05 51](https://user-images.githubusercontent.com/17392251/226714988-ee384ad3-7492-41fd-925c-8e8e281ad870.gif)

**Comment by awacode21** [comment]
i am dealing with the same topic, but i need different behavior.

I have a parent page and a nested page view which should render a dialog on top of the parent page.
so i have a nuxt page within a nuxt page.
navigating between parent and nested page works fine. Dialog opens and closes correctly,... BUT everytime i navigate to the nested page (opens dialog) the parent page view underneath gets scrolled to the top, but i want to keep scroll position, as the user is just opening a dialog but should stay in page where he was.

any idea how to achieve this?

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

**Comment by gbissolli** [comment]
Hi @danielroe I am using nuxt3 and still facing the same issue as @awacode21 reported above, shall we reopen the issue?

**Comment by danielroe** [comment]
@gbissolli Would you raise a new issue with a reproduction? 🙏

**Comment by awacode21** [comment]
my problem was also when using nuxt 3.
@gbissolli i did not found a way to solve it.
