### ISSUE TITLE
Headers not proxied to sever handler when request made on backend (evaluated as function) 

### ISSUE THREAD

**Issue by oleghalin** [nuxt/nuxt#19843]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.19.1`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `pnpm@7.27.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

1. Create any server handler
2. run useFetch from setup function
3. no `host` header passed to nitro handler

### Describe the bug

1. Create any server handler
2. run useFetch from setup function
3. no `host` header passed to nitro handler

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by oleghalin** [comment]
Sure, here its @danielroe 
https://stackblitz.com/edit/github-qtfkw3

**Comment by danielroe** [comment]
It seems to be working for me?

![CleanShot 2023-03-21 at 10 09 41](https://user-images.githubusercontent.com/28706372/226575279-88aeb51d-40d1-486b-aaa2-7f5dc66ceebc.png)

**Comment by danielroe** [comment]
The rest of the headers are proxied - not sure yet whether the `host` change is intended behaviour, but it might be.

cc: @pi0

**Comment by oleghalin** [comment]
I think host should be proxied too because safari doesnt pass referer if privacy settings is turned on

**Comment by chenyuncai** [comment]
A SSR request includes multiple request, we said the first and the others.

The First is a real request user send, it has all valid headers.
The Others is internal fetch in back-end when ssr need data in setup or anything else, it set the host to 'localhost'

Both the First and Others share a same Event params.

So I add a middleware to set the real host (getHeader(event, 'host')) to event context, and in the next internal api request（calledd Others) will get the host from event.context first. For now every api get the right host. 

That works for  me  now.

**Comment by PoteznyGracz** [comment]
> A SSR request includes multiple request, we said the first and the others.
> 
> The First is a real request user send, it has all valid headers. The Others is internal fetch in back-end when ssr need data in setup or anything else, it set the host to 'localhost'
> 
> Both the First and Others share a same Event params.
> 
> So I add a middleware to set the real host (getHeader(event, 'host')) to event context, and in the next internal api request（calledd Others) will get the host from event.context first. For now every api get the right host.
> 
> That works for me now.

Doesn't work. Each request has a new event context. You can set any value there, but it will not be passed to the new event.

To use this solution that doesn't work at all ;) first you need to recognize the original request. Then you will be able to set values in its context. This can be done by checking the client field in the event node.
`
 const url  = event.node.req.url
console.log( event.node.req.client ? `Orginal request -> ${url}` : `SSR request -> ${url}` )
`

I am currently creating two applications, one loads its configuration depending on the host, the other is SAAS, so I had to find a solution to this problem or change my job and become a welder.

I made a facade on $fetch

`export default class Request {

     public static async do ( url: string, options: any = {} ): Promise<any> {

          await this.initOptions( options )
          return $fetch( url, options )
     }

     private static async initOptions ( options: any ): Promise<any> {

          this.setDefaultValue( options )
          this.setHost( options )
          await this.setAuthorization( options )

          return options
     }

     private static setDefaultValue ( options: any ) {

          if ( !options.method )
               options.method = 'GET'

          if ( !options.headers )
          {
               options.headers = {}
               options.headers["Content-Type"] = "application/json; charser=utf-8"
          }
     }

     private static setHost ( options: any ) {

          options.headers['host'] = useRequestHeaders( ['host'] )
     }

     private static async setAuthorization ( options: any ) {

          const userStore = ( await import( '@/stores/User' ) ).useUser()
          options.headers.Authorization = `Bearer ${userStore.JWT}`
     }
}
`
My class always setsthe correct host for me

`
private static setHost ( options: any ) {

           options.headers['host'] = useRequestHeaders( ['host'] )
}
`
At the same time, I will set other things that I do not want to repeat and I have control. I can always change the implementation. Usage looks like this:

`
 return Request.do( '/api/public/active-products' )
`

Complete use case

Script section
`
const { data } = await useAsyncData(
    () => {
        return ActiveProducts.getAll()
    } )

`
ActiveProducts class
`
import Request from '../util/Request'

export default class ActiveProducts {

     public static getAll (): Promise<any> {

          return Request.do( '/api/public/active-products' )
     }

     public static getProduct ( productId: number ): Promise<any> {
          
          return Request.do( `/api/public/product/${productId}` )
     }
}
`

Of course, you can improve it by adding types and other crap, but it depends on your individual approach.

**Comment by danielroe** [comment]
For this, we now have `useRequestFetch` which returns a configured `$fetch` function that enables proxying headers to server handler in this situation.
