### ISSUE TITLE
Improved `pick` API for `useAsyncData` and `useFetch`

### ISSUE THREAD

**Issue by Atinux** [nuxt/nuxt#19844]
RFC: https://github.com/nuxt/nuxt/discussions/16831

The solution the community voted the most is the following:

```ts
const { data: user } = await useFetch('/api/user/100', {
  pick: [ 'name', 'info.url', 'info.like.status' ]
})
```

Also a note regarding the data returned as Array, we shall be able to smartly identify if it is an array of objects to apply the pick on each item.

To note, a potential improvement if `pick` is a string: #19545

**Comment by danielroe** [comment]
I think we decided to recommend `transform` instead, right?

https://github.com/nuxt/nuxt/pull/19545#comment-1987993

**Comment by pi0** [comment]
I think we can do transform + a (treeshakable) `pick` composable if we still wanna do this (and it is kinda a common enough usage).


```ts
const { data: user } = await useFetch('/api/user/100', {
  transform: obj => (pick(obj, ['name', 'info.url', 'info.like.status'])
})
```

or

```ts
const { data: user } = await useFetch('/api/user/100', {
  transform: createPick(['name', 'info.url', 'info.like.status'])
})
```

**Comment by danielroe** [comment]
Personally, I think a `pick` composable should not really be part of Nuxt core, any more than other utility functions. I'd suggest letting libraries like `lodash` or just [native code](https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore) handle it.

**Comment by pi0** [comment]
Agree. I might introduce some object utils in unjs then :) If at some point we want to introduce ad-hoc auto imports similar to `@vueuse/core` we can enable it without core maintenance addition.
