### ISSUE TITLE
Change in component only gets reflected in last component

### ISSUE THREAD

**Issue by LukasHechenbergerID** [nuxt/nuxt#19856]
### Environment

- Operating System: Win 11
- Nuxt: 3.3.1
- Browser: Chrome, Firefox

### Reproduction

https://stackblitz.com/edit/github-nwauuu?file=components/TestCard.vue

### Describe the bug

If you change something in a component and use it multiple times (v-for or just multiple components) only the last one gets updated. When you reload, all components are correctly updated. When you change something, there is a correct HMR update in the console.

Reproduction on stackblitz: change the text in the TestCard component, only the last TestCard component gets updated.

Observation: If there is only one div (so no nested elements) it works.

**Comment by LukasHechenbergerID** [comment]
Thanks for the quick response!
Yes, I can replicate it:
https://stackblitz.com/edit/github-39do8i?file=src/components/TestCard.vue

**Comment by danielroe** [comment]
Great work. Would you raise an upstream issue to track, then? It might be https://github.com/vuejs/core or possibly https://github.com/vitejs/vite-plugin-vue.

**Comment by LukasHechenbergerID** [comment]
I raised an upstream issue for Vite: https://github.com/vitejs/vite-plugin-vue/issues/134
Could not reproduce it with  Vue alone, but with the recommended setup with Vite.
