### ISSUE TITLE
Use the named slot templates with default layout

### ISSUE THREAD

**Issue by hermesalvesbr** [nuxt/nuxt#19859]
### Describe the feature

Only home is a different layout, all the internals of the site are the same, so I would like to use: <NuxtLayout name="home"> for initial, but in the internals I would like to use the default layout.

But it doesn't work:

```
<template #preContent>
       <div class="sum-class">
        SomeContent here
       </div>
     </template>
```

If this functionality already exists, I haven't found it in the documentation.
```

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `directus`, `modules`, `app`, `imports`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.6.3`, `nuxt-icon@0.3.3`, `nuxt-directus@5.1.1`, `@pinia/nuxt@0.4.7`
- Build Modules:    `-`
------------------------------

```

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
In order to do this, you need to use `<NuxtLayout>` within your page: https://nuxt.com/docs/guide/directory-structure/layouts#overriding-a-layout-on-a-per-page-basis
