### ISSUE TITLE
npx nuxi build fails random with @splidejs/splide/dist/css/themes/splide-default.min.css

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/nuxt#19855]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@9.5.0`
- Builder:          `vite`
- User Config:      `srcDir`, `modules`, `tailwindcss`, `vite`, `i18n`, `nitro`, `schemaOrg`, `telemetry`, `algolia`, `head`, `auth`, `viewport`, `css`, `build`, `runtimeConfig`
- Runtime Modules:  `genesis-design-system/nuxt`, `@nuxtjs/algolia@1.5.1`, `@nuxtjs/tailwindcss@6.6.0`, `formidable@2.1.1`, `nuxt-viewport@2.0.3`, `@nuxtjs/partytown@1.3.0`, `@vueuse/nuxt@9.13.0`, `nuxt-schema-org@2.1.2`, `nuxt-icon@0.1.8`, `@pinia/nuxt@0.4.7`, `@nuxtjs/i18n@8.0.0-beta.10`, `@sidebase/nuxt-auth@0.3.4`
- Build Modules:    `-`

### Reproduction

i'm having problems when we compile our project

If we use this line, compiling was wrong
![image](https://user-images.githubusercontent.com/77386602/226857986-4a41ff1f-a01a-4d4d-9916-984da7f42ece.png)

but if we use an assets file, the compiling was correct in all compilations.
![image](https://user-images.githubusercontent.com/77386602/226856490-d39c40fd-385f-42d7-9c3a-a45ca44e24d3.png)

The strangest thing yet is that I am using the import of "import '@splidejs/splide/dist/css/themes/splide-default.min.css'" in several files and it only fails in this file

I have tryed build.rollupOptions.external with this file, but fails also

### Describe the bug

i'm having problems when we compile our project

If we use this line, compiling was wrong
![image](https://user-images.githubusercontent.com/77386602/226857986-4a41ff1f-a01a-4d4d-9916-984da7f42ece.png)

but if we use an assets file, the compiling was correct in all compilations.
![image](https://user-images.githubusercontent.com/77386602/226856490-d39c40fd-385f-42d7-9c3a-a45ca44e24d3.png)

The strangest thing yet is that I am using the import of "import '@splidejs/splide/dist/css/themes/splide-default.min.css'" in several files and it only fails in this file

I have tryed build.rollupOptions.external with this file, but fails also

**Comment by danielroe** [comment]
Would you provide a reproduction? A note - if you are importing `.css` files within node_modules, you should probably add that package to your `build.transpile` list.

**Comment by agracia-foticos** [comment]
I put 

` build: {        
        transpile: ['chart.js', 'vue-chart-3', "@headlessui/vue", "vue-tel-input","vue-easy-lightbox", "@splidejs/splide"], 
    },    `

But the error persist,

I prepare an environment link, but in this environment doesnt crash
https://stackblitz.com/edit/nuxt-starter-rxaqzx

**Comment by agracia-foticos** [comment]
> Just in case, try instead a RegExp: `/@splidejs[\\/]splide/`. Does that make a difference?

 build: {        
        transpile: ['chart.js', 'vue-chart-3', "@headlessui/vue", "vue-tel-input","vue-easy-lightbox", /@splidejs[\\/]splide/], 
    }, 

Same error 
![image](https://user-images.githubusercontent.com/77386602/226893454-fa26c3db-26e7-4677-87cb-9718faf0641e.png)

**Comment by danielroe** [comment]
Okay. I'll have a look at your reproduction. Would you confirm that it reproduces the issue when you download that reproduction to your machine?
