### ISSUE TITLE
Cannot use `$fetch` within`defineEventHandler` without http host for `nitro.publicAssets`

### ISSUE THREAD

**Issue by WolfgangDrescher** [nuxt/nuxt#19868]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `npm@9.5.1`
- Builder:          `vite`
- User Config:      `app`, `ssr`, `srcDir`, `modules`, `vite`, `nitro`, `googleFonts`, `i18n`, `content`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.6.4`, `@pinia/nuxt@0.4.7`, `@nuxtjs/google-fonts@3.0.0`, `nuxt-icon@0.3.3`, `@nuxtjs/i18n-edge@8.0.0-beta.10-27985006.4ff543e`, `@nuxt/content@2.5.2`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-xbvfav

### Describe the bug

I serve static files with `nitro.publicAssets` that I need to fetch within `defineEventHandler` of an api endpoint. If I use the following function `$fetch('/scores/test.krn')` will not find the static file but instead the 404 html page gets returned.

```js
export default defineEventHandler(async (event) => {
  const response = await $fetch('/scores/test.krn');
  return await response.text();
});
```

If I add the http host to the url it works fine but this is not compatible with the domain of the deployed version:

```js
export default defineEventHandler(async (event) => {
  const response = await $fetch('http://localhost:3000/scores/test.krn');
  return await response.text();
});
```

Is `$fetch` supposed to work within `defineEventHandler` with an absolute path?

**Comment by ruoxi-zhao** [comment]
same question

**Comment by danielroe** [comment]
I think this should work fine when using `nitro.serveStatic: true`.
