### ISSUE TITLE
setResponseStatus wrong type definition

### ISSUE THREAD

**Issue by MateiNenciu** [nuxt/nuxt#19867]
### Environment

`- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-``

### Reproduction

Access https://stackblitz.com/edit/github-xuiv1i-jfyl16?file=server%2Fapi%2Fwithout-event.ts,server%2Fapi%2Fwith-event.ts . Navigating to /api/with-event works as intended. Navigating to /api/without-event throws error.

 Also go to server/api/with-event and remove the @ ts-ignore line to see the type error.

### Describe the bug

setResponseStatus function has wrong typing when used in defined nitro api (/server/api/...). Using without event param leads to unhandled error, adding event parameter the typescript complains about having too many parameters.

This might be because nuxt also has setResponseStatus function (that has only 2 paremeters) ?

**Comment by danielroe** [comment]
Linking https://github.com/nuxt/nuxt/issues/13920.
