### ISSUE TITLE
 ERROR  RollupError: Unexpected token

### ISSUE THREAD

**Issue by gllinzbk1** [nuxt/nuxt#19877]
├── blueblocksui-footer@2.0.1
└── nuxt@3.3.1
ssr:true

app.vue:

```vue
<template>
  <div>
    <NuxtWelcome />
    <Footer />
  </div>
</template>
<script setup>
import Footer from 'blueblocksui-footer'
</script>
``` 

do:
npm run generate 

### Describe the bug

 WARN  rollup-plugin-inject: failed to parse /data/user/lbadmin/develop/project/nuxt3/ok/ntest1/starter-3/node_modules/blueblocksui-footer/src/footer.vue. Consider restricting the plugin to particular files via options.include

 ERROR  RollupError: Unexpected token (Note that you need plugins to import files that are not JavaScript)                                                                                                      nitro 14:25:07

```code
1: <template>
   ^
2: this is footer
3: <\/template>
```

**Comment by Bharadwajshivam28** [comment]
@gllinzbk1 I want to work on this can you assign me

**Comment by gllinzbk1** [comment]
> @gllinzbk1 I want to work on this can you assign me

sorry,this is a bug

**Comment by gllinzbk1** [comment]
[Library Authors](https://nuxt.com/docs/guide/directory-structure/components#library-authors)

Making Vue component libraries with automatic tree-shaking and component registration is super easy ✨

You can use the components:dirs hook to extend the directory list without requiring user configuration in your Nuxt module.

Imagine a directory structure like this:
```
| node_modules/
---| awesome-ui/
------| components/
---------| Alert.vue
---------| Button.vue
------| nuxt.js
| pages/
---| index.vue
| nuxt.config.js
```
Then in awesome-ui/nuxt.js you can use the components:dirs hook:
```
import { defineNuxtModule, createResolver } from '@nuxt/kit'
export default defineNuxtModule({
  hooks: {
    'components:dirs': (dirs) => {
      const { resolve } = createResolver(import.meta.url)
      // Add ./components dir to the list
      dirs.push({
        path: fileURLToPath(resolve('./components')),
        prefix: 'awesome'
      })
    }
  }
})
```
That's it! Now in your project, you can import your UI library as a Nuxt module in your nuxt.config file:
nuxt.config.ts
```
export default defineNuxtConfig({
  modules: ['awesome-ui/nuxt']
})
```
... and directly use the module components (prefixed with awesome-) in our pages/index.vue:
```
<template>
  <div>
    My <AwesomeButton>UI button</AwesomeButton>!
    <awesome-alert>Here's an alert!</awesome-alert>
  </div>
</template>
```
It will automatically import the components only if used and also support HMR when updating your components in node_modules/awesome-ui/components/.
