### ISSUE TITLE
useFetch runs twice if using layout and dynamic component

### ISSUE THREAD

**Issue by milelazar** [nuxt/nuxt#19887]
### Environment

------------------------------
- Operating System: `OSX`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.3.1`
- Package Manager:  `npm@8.15.0`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-mujaqc?file=pages/[...slug].vue

### Describe the bug

On the first load, useFetch is executed twice. On the server and once again on the client.

The problem occurs when the following three conditions are met:
1. Page uses dynamic components
2. A dynamic component uses a variable

This doesn't work (useFetch is executed on the server and client side):
```
<component :is="component" />
const template = 'CustomPageTemplate';
const component = resolveComponent(template);
```

This works (useFetch is not executed on the client):
```
<component :is="component" />
const component = resolveComponent('CustomPageTemplate');
```

3. The dynamic component uses NuxtLayout component

### Additional context

Possibly related to https://github.com/nuxt/nuxt/issues/13369

**Comment by 35grain** [comment]
I'm experiencing useFetch firing twice within a component which uses a form submission handler method to run useFetch. I've checked and the method itself is run once, so useFetch must be at fault.

**Comment by manniL** [comment]
Can't reproduce this anymore ☺️
