### ISSUE TITLE
Unable to extend layer to external repo: 406 Not Acceptable

### ISSUE THREAD

**Issue by dextersiah** [nuxt/nuxt#19882]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@9.5.0`
- Builder:          `vite`
- User Config:      `extends`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-ewxmt8?file=nuxt.config.ts

### Describe the bug

Received error when ran `npm run dev`

`node:9) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)`

`Failed to download https://gitlab.com/dextersiah/nuxt-base/-/archive/main.tar.gz: 406 Not Acceptable`

Initially attempted to try with private repository and encountered the error. Then proceed to set repo to public and attempted once again. However still receiving the same error

**Comment by dextersiah** [comment]
@danielroe May I know with that PR will it solve the second error? 

I have tried running `npm run dev` with an older version of node `16.18.1`. Instead of receiving a 406 Not Acceptable. I'm receiving 404 not found.

I'm using a public repo on GitLab 
https://gitlab.com/dextersiah/nuxt-base

and the path I use in the config file is `gitlab:dextersiah/nuxt-base.git`.

**Comment by professorhaseeb** [comment]
The issue still exists. 

```bash
$ npm run dev

Nuxi 3.5.3
Nuxt 3.5.3 with Nitro 2.4.1
Failed to download: 406 Not Acceptable 
```

```cmd
$ node -v
v18.12.0
```

**Comment by derHodrig** [comment]
![image](https://github.com/nuxt/nuxt/assets/53934248/733db0e6-41d4-4c57-ae47-1d64ebb50bb6)

![image](https://github.com/nuxt/nuxt/assets/53934248/931abed3-9e60-4287-acf6-2b790b079f8c)

Maybe its the problem of the naming? its not main.tar.gz its [repoName]-main.tar.gz

**Comment by hermesalvesbr** [comment]
Did you find any solution? Over here same problem.

**Comment by derHodrig** [comment]
@hermesalvesbr no, i switched to the gitlab package registry. So the package is on our selfhosted gitlab instance. You can use the layer like normal npm

https://docs.gitlab.com/ee/user/packages/npm_registry/index.html#publishing-a-package-via-a-cicd-pipeline

That works like charm. Also you dont need to worry about other npm deps. The base layer deps can stay in the package json of the base layer.
I prefer this "workaround". Its the best from both, npm and selfmanaged gitlab.

**Comment by morgan-massamba** [comment]
I'm facing the same issue..

**Comment by danielroe** [comment]
If you're still encountering this, would you be able to raise this upstream on https://github.com/unjs/c12 ?

cc: @pi0

**Comment by andreymart-test** [comment]
I solved this problem with gitlab, the giget package is the problem. I made a PR with a fix to this library
https://github.com/unjs/giget/issues/97
