### ISSUE TITLE
Vercel Deployment with Nuxt-Content create three built directories

### ISSUE THREAD

**Issue by ArthurDanjou** [nuxt/nuxt#19883]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.14.2`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `srcDir`, `build`, `modules`, `devtools`, `supabase`, `colorMode`, `content`, `tailwindcss`, `vite`, `nitro`, `css`, `components`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/color-mode@3.2.0`, `@vueuse/nuxt@9.13.0`, `@nuxt/content@2.5.2`, `nuxt-icon@0.3.3`, `@nuxtjs/supabase@0.3.1`, `@pinia/nuxt@0.4.7`, `@pinia-plugin-persistedstate/nuxt@1.0.0`, `@nuxtjs/robots@3.0.0`, `@nuxtjs/tailwindcss@6.6.0`, `@nuxt/devtools@0.2.5`
- Build Modules:    `-`

### Reproduction

https://github.com/ArthurDanjou/artdanj-website-v2

### Describe the bug

I want to deploy my project to Vercel using the preset vercel-edge in nitro.

I run the command `yarn nuxi generate` to build the project. The output directory is `.vercel/output/functions/__nitro.func` for the nitro's server and `.vercel/output/static` for the nitro's public directory. I have any errors during the build process. 

I can find three different build directories: 

- `.output` containing the `nitro.json` file with incorrect preset

```json
{
  "date": "2023-03-23T12:46:28.209Z",
  "preset": "nitro-prerender",
  "commands": {
    "preview": "npx serve ./public"
  }
}
```

- `.vercel/output` containing the `nitro.json` file with the correct preset

```json
{
  "date": "2023-03-23T12:46:43.539Z",
  "preset": "vercel-edge",
  "commands": {
    "preview": "",
    "deploy": ""
  }
}
```

- `dist` containing nuxt files and .html files

The `nuxi generate` preview:
<img width="250" alt="Capture d’écran 2023-03-23 à 13 48 24" src="https://user-images.githubusercontent.com/29738535/227209302-cdecc480-180b-4c68-9868-1fbddab9181c.png">

When I run the `yarn nuxi preview` command, nitro is running from `.output` directory with the incorrect information
This is the information in my terminal: 
```
Nuxi 3.3.1                                                                                                                                                           13:53:54
ℹ Node.js version: 18.14.2                                                                                                                                           13:53:54
ℹ Preset: nitro-prerender                                                                                                                                            13:53:54
ℹ Working dir: .output                                                                                                                                               13:53:54
ℹ Loading .env. This will not be loaded when running the server in production.                                                                                       13:53:54
ℹ Starting preview command: npx serve ./public
```

### Additional context

I have followed the vercel documentation and the nitro and nuxt documentations to deploy my project

**Comment by ArthurDanjou** [comment]
Hello Daniel, I've seen that you have mentioned my issue in a pull request. Can you tell me if I miss something or if I have to wait for a fix? Thank you for your work

**Comment by danielroe** [comment]
@ArthurDanjou If you've upgraded to the latest version of Nuxt (with Nitro v2.3.3) you will no longer have `.output` generated. But you will still have `dist` and `.vercel`.

When we merge https://github.com/unjs/nitro/pull/1073, I think it will be perfect for your use case.

**Comment by danielroe** [comment]
Static presets are now merged and enabled upstream.
