### ISSUE TITLE
Process Shutdown Hooks not Triggered in Nitro Plugins

### ISSUE THREAD

**Issue by BakoviDagi** [nuxt/nuxt#19888]
### Environment

Nuxi 3.3.1

RootDir: /home/projects/github-yqqs2f 
Nuxt project info: 

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `hooks`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-yqqs2f?file=server/plugins/nitro-shutdown.js

- Run the app
- Go to the console and type Ctrl+C
- Note that there are "Listen" shutdown logs but none for "Nitro"

### Describe the bug

Process shutdown events are not triggered from inside a nitro plugin

At [this recommendation](https://github.com/nuxt/nuxt/discussions/19033#discussioncomment-4997697) I am initializing a Eureka discovery server client from a nitro plugin, but I would also like to add some logic to automatically unregister from Discovery when the application is shutdown. Unfortunately, these events don't work in a nitro plugin. They work from a listen hook, but that only runs in Dev mode

### Logs

```shell-script
WARN  In the listen hook!                                                                                                             08:50:23

ℹ Vite client warmed up in 1129ms                                                                                                      08:50:25
✔ Nitro built in 1332 ms                                                                                                         nitro 08:50:26
This is the nitro shutdown plugin!                                                                                                     08:50:27
^C
                                                                                                                                       08:50:20
 ERROR  Listen - Shutdown -- SIGINT!                                                                                                   08:50:48


 ERROR  Listen - Shutdown -- exit!
```

**Comment by trylovetom** [comment]
Hi @danielroe and @BakoviDagi.

Firstly, I want to extend my thanks to the Nuxt team for your continual efforts in advancing this framework. Your work is truly making a significant difference in web development.

Now, onto the matter at hand. I've come up with a workaround, which involves modifying the `.output/server/chunks/nitro/node-server.mjs` file. After the server starts listening, you can add the following code:

```js
{
  process.on(
    "unhandledRejection",
    (err) => console.error("[nitro] [dev] [unhandledRejection] " + err)
  );
  process.on(
    "uncaughtException",
    (err) => console.error("[nitro] [dev] [uncaughtException] " + err)
  );

  // gracefully shutdown
  const signals = ['SIGTERM', 'SIGINT']
  async function handler(signal) {
    signals.forEach(sig => process.removeListener(sig, handler))
    await s.close()
    await nitroApp.hooks.callHook('close')
  }
  signals.forEach(sig => process.on(sig, handler))
}
```

This allows you to add a close hook in your nitro plugins (you can do this in the Nuxt directory like so: `/server/plugins/your-nitro-plugin`). This way, you can confidently carry out tasks like closing databases or queues:

```ts
export default defineNitroPlugin((nitro) => {
  nitro.hooks.hookOnce('close', async () => {
    console.log('doing')
    // await something you want to do, such like disconnected the database, or wait the task is done
    console.log('done')
  })
})
```

Please be aware, however, that this is only applicable for the `node-server` nitro preset. Currently, the nuxt `dev-cli`, `node-cluster` and other presets do not support this functionality.

I'm pleased that an afternoon's work led me to this workaround. Yet, it's also a gentle reminder - a 'big red flag', if you will - that when using Nuxt for full-stack projects, some essential backend server tasks might not be the primary consideration of Nuxt. If these backend aspects could be prioritized by the Nuxt team, I believe it would enhance the framework's completeness significantly.

Thank you for your ongoing efforts in improving Nuxt! I look forward to seeing how this aspect evolves.

**Comment by pi0** [comment]
Thanks for nice example and kind words @trylovetom. Would you like to try a PR in nitro to support built-in hook for `node-*`, `dev` and `prerender` presets?

**Comment by trylovetom** [comment]
@pi0 I was wondering if you could provide me with clearer instructions on what needs to be done? For instance, could you specify which hook events need to be handled, or provide some insights into the lifecycle of Nuxt? I'm new to the Nuxt3 community and would appreciate your guidance. Thanks in advance!

**Comment by pi0** [comment]
~> https://github.com/unjs/nitro/issues/1224

**Comment by danielroe** [comment]
Closing here to follow there - thank you all for your great work on this one ❤️
