### ISSUE TITLE
Nuxt 3 SSR mode, manually refresh the browser page, prompting Cannot read properties of null (reading 'posts'), how to solve this

### ISSUE THREAD

**Issue by Rhin0cer0s2022** [nuxt/nuxt#19897]
### Environment

- Operating System: `Darwin`
- Node Version:     `v19.4.0`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`, `sitemap`, `css`, `postcss`, `mode`, `ssr`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.4.1`
- Build Modules:    `-`

### Reproduction

```javascript
<script setup>
const { tag } = useRoute().params
const page = ref(1)
const limited = ref(20)
const uri = 'https://.../tags/' + tag
const { data: tagnames, pending, error, refresh } = await useFetch(uri, {
  query: { page, limited },
  onCompleted: () => {
    refresh()
  },
  onError: () => {
    refresh()
  }
});
</script>
```

The returned data should be:：
```json
{
"posts":[
      {
        "id":"",
        "category":"",
        "date":"",
        "title":"",
        "image":"",
        "tags":""
      },
  ]
}
```

I have been looking for documents for a long time, and I have searched for a long time. I really can’t get it done, and I haven’t found a good solution. Please let me know, thank you

### Describe the bug

Nuxt 3 SSR mode, manually refresh the browser page, prompting Cannot read properties of null (reading 'posts'), that is, there is no new API to obtain data, how to solve this

One more thing, the homepage manual refresh can still get new data from the API, but other pages can’t, I don’t understand why

Nuxt 3 SSR模式，手动刷新浏览器页面，提示Cannot read properties of null (reading 'posts')，就是没有重新API获取数据，这个怎么解决

补充一句，首页是正常的，手动刷新还是能重新从API获取新数据，其他页面都不行，没搞懂是为什么

**Comment by warflash** [comment]
I think you might have to provide more context/a proper [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction).
Also sounds more like a question in the discussion tab or on [discord](https://discord.com/invite/ps2h6QT) to me instead of an issue with nuxt itself @Rhin0cer0s2022

**Comment by Rhin0cer0s2022** [comment]
> I think you might have to provide more context/a proper [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction). Also sounds more like a question in the discussion tab or on [discord](https://discord.com/invite/ps2h6QT) to me instead of an issue with nuxt itself @Rhin0cer0s2022

```vue
<template>
...
 <NuxtLink class="ml-1 text-sm font-medium text-gray-700 hover:text-blue-600 md:ml-2"
            :to="`/tags/${tag.split(',')[0].replace('{', '').replace('}', '')}`">
            #{{ tag }}</NuxtLink>
...
<div
      class="self-center mx-auto border rounded-2xl hover:scale-110 active:scale-90 transition-transform ease-in-out duration-500"
      v-for="tagname in tagnames.posts" :key="tagname.id">
      <NuxtLink :to="`/colorpages/${tagname.id}`">
        <img class="w-64" :src="`${tagname.image}`" :alt="`${tagname.title}`">

      </NuxtLink>

    </div>
...
<span class="text-sm text-gray-700">
      <span class="font-semibold text-gray-700">第 {{ tagnames.page }} 页 </span>
      <span class="font-semibold text-gray-700">共 {{ tagnames.total_pages }} 页</span>
    </span>
...
<button v-if="page > 1" @click="page--"
        class="inline-flex items-center px-4 py-2 text-sm font-medium text-gray-800 bg-white rounded-l hover:bg-gray-900 hover:bg-gray-700 hover:text-white">
        <svg aria-hidden="true" class="w-5 h-5 mr-2" fill="currentColor" viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd"
            d="M7.707 14.707a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l2.293 2.293a1 1 0 010 1.414z"
            clip-rule="evenodd"></path>
        </svg>
        上一页
      </button>
      <button @click="page++"
        class="inline-flex items-center px-4 py-2 text-sm font-medium text-gray-800 bg-white border-0 border-l border-white rounded-r hover:bg-gray-600 hover:bg-gray-700 hover:text-white">
        下一页
        <svg aria-hidden="true" class="w-5 h-5 ml-2" fill="currentColor" viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd"
            d="M12.293 5.293a1 1 0 011.414 0l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-2.293-2.293a1 1 0 010-1.414z"
            clip-rule="evenodd"></path>
        </svg>
      </button>
</template>
```


Are these contexts enough?
what else is needed

**Comment by Rhin0cer0s2022** [comment]
SSR mode manual refresh returns
```
Cannot read properties of null (reading 'posts')
```
@warflash

**Comment by warflash** [comment]
A proper reproduction would make looking into things a lot easier.
Have you tried whether `v-for="tagname in tagnames?.posts"` fixes your issue?

**Comment by Rhin0cer0s2022** [comment]
It's amazing, thank you so much
What is the principle? I haven't found this solution after searching for a long time.

**Comment by Rhin0cer0s2022** [comment]
Awesome, this is a great idea
This problem has troubled me for several days, and finally solved it
Thanks again

**Comment by poldelgado** [comment]
I've the same issue, in ubuntu 22.04 with node v18.17.1. But when i switch to node v16.17.0 it works fine.

this is the error:
Cannot read properties of null (reading 'data')

at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:683:9)
at ./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:629:25
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async unrollBuffer$1 (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:870:16)
at async unrollBuffer$1 (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:875:16)
at async unrollBuffer$1 (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:875:16)
at async unrollBuffer$1 (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:875:16)
at async unrollBuffer$1 (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:875:16)
at async unrollBuffer$1 (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:875:16)
