### ISSUE TITLE
Nuxt Installation failed

### ISSUE THREAD

**Issue by slaetthult** [nuxt/nuxt#19891]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `2.15.8`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@9.5.0`
- Builder:          `webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Just trying to install Nuxt 3 (3.3.1). Nothing added or changed in package.json.

### Describe the bug

Just trying to install Nuxt 3 (3.3.1). Nothing added or changed in package.json.

```
npx nuxi@latest init my-app
npm i
```

Results to an error:

```
Vue packages version mismatch:

- vue@2.6.12
- vue-server-renderer@2.6.14

This may cause things to work incorrectly. Make sure to use the same version for both.
```

<img width="872" alt="Bildschirmfoto 2023-03-23 um 17 47 25" src="https://user-images.githubusercontent.com/22275417/227275807-017a8224-510d-4bb4-ada5-9677cce91106.png">

**Comment by slaetthult** [comment]
If I try to install an older Nuxt-Version
`"nuxt": "3.1.2"`
I also get  
`ERROR  No "exports" main defined in /my-app/node_modules/@nuxt/kit/package.json   `
like the other person

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/19866.
