### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by Mnigos** [nuxt/nuxt#19892]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `meta`, `modules`
- Runtime Modules:  `nuxt-windicss@2.6.0`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/Mnigos/biuro-makowska

### Describe the bug

Application is building fine, but not in vercel deployment.

### Additional context

`nuxt.config.ts`
```ts
// https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
export default defineNuxtConfig({
  meta: {
    title: 'Biuro Makowska',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      {
        hid: 'description',
        name: 'description',
        content:
          'Biuro Rachunkowe Joanna Makowska to certyfikowane biuro, które zapewnia swoim klientom profesjonalną obsługę oraz rzetelne i fachowe świadczenie usług księgowych.',
      },
      {
        name: 'msapplication-TileColor',
        content: '#000000',
      },
      {
        name: 'theme-color',
        content: '#ffffff',
      },
    ],
    link: [
      { rel: 'icon', type: 'image/png', sizes: '32x32', href: '/favicon-32x32.png' },
      { rel: 'icon', type: 'image/png', sizes: '64x64', href: '/favicon-64x64.png' },
      { rel: 'manifest', href: '/site.webmanifest' },
    ],
  },
  modules: ['nuxt-windicss'],
})
```

### Logs

```shell-script
$ nuxt prepare
--
18:05:05.374 | [log] Nuxi 3.3.1
18:05:06.986 | [info] [@nuxtjs/web-vitals] Auto detected provider: vercel
18:05:06.991 | [error] Cannot read property 'name' of undefined
18:05:06.991 | at normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:170:106)
18:05:06.991 | at async installModule (node_modules/@nuxt/kit/dist/index.mjs:451:15)
18:05:06.991 | at async initNuxt (node_modules/nuxt/dist/index.mjs:2469:7)
18:05:06.992 | at async loadNuxt (node_modules/nuxt/dist/index.mjs:2523:5)
18:05:06.992 | at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:539:19)
18:05:06.992 | at async Object.invoke (node_modules/nuxi/dist/chunks/prepare.mjs:37:18)
18:05:06.992 | at async _main (node_modules/nuxi/dist/cli.mjs:49:20)
```

**Comment by moldedjelly** [comment]
I'm also seeing this when trying to run nuxt inside docker container - using  node:14-alpine

**Comment by rejkee** [comment]
Update this:
```
const perf = performance.measure(`nuxt:module:${uniqueKey || Math.round(Math.random() * 1e4)}`, mark.name);
const setupTime = Math.round(perf.duration * 100) / 100;
```

to this:
const perf = performance.measure(`nuxt:module:${uniqueKey || Math.round(Math.random() * 1e4)}`, mark?.name);
const setupTime = perf ? Math.round((perf.duration * 100)) / 100 : 0

**Comment by moldedjelly** [comment]
thanks @rejkee that got it working for me

**Comment by moldedjelly** [comment]
in case this helps someone else working in docker, I noticed that updating docker to base from node:18-alpine also fixed the issue for me - with the added bonus that I don't have to manually edit the file

**Comment by danielroe** [comment]
This has already been resolved on the edge channel and will be present in 3.3.2, or alternatively you can upgrade to node 16/18.
