### ISSUE TITLE
 useHead is not overwriting the head of nuxt.config

### ISSUE THREAD

**Issue by dev02iggy** [nuxt/nuxt#19906]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `yarn@1.22.10`
- Builder:          `vite`
- User Config:      `ssr`, `app`, `css`, `windicss`, `build`, `buildModules`, `modules`, `experimental`, `components`, `vite`, `runtimeConfig`, `vueuse`
- Runtime Modules:  `@pinia/nuxt@0.4.7`, `@vueuse/nuxt@9.13.0`, `nuxt-windicss@2.6.0`, `nuxt-icon@0.3.3`
- Build Modules:    `@nuxtjs/google-fonts@2.0.0`
------------------------------

### Reproduction

<img width="566" alt="Captura de Tela 2023-03-24 às 15 12 13" src="https://user-images.githubusercontent.com/83841469/227607680-b88a7937-e1e8-4d5e-8b4e-3a42369a427a.png">
<img width="566" alt="Captura de Tela 2023-03-24 às 15 12 25" src="https://user-images.githubusercontent.com/83841469/227607826-70674973-9f86-4c4f-bad6-5341fcd9ce53.png">
<img width="566" alt="Captura de Tela 2023-03-24 às 15 12 38" src="https://user-images.githubusercontent.com/83841469/227607929-b6292c42-eefb-4a82-a2ef-aeeedde3e182.png">
<img width="566" alt="Captura de Tela 2023-03-24 às 15 13 32" src="https://user-images.githubusercontent.com/83841469/227607937-9afc757c-404a-4b01-9add-9b4e8a6e77d5.png">

### Describe the bug

useHead is not overwriting the head of nuxt.config. In production you can't overwrite anything. The only change is in the title of the page, but the Seo remains the same as in nuxt.config.
I've tried useHead() and useSeoMeta(), as well as <Head>, but none of them managed to override nuxt.config.
This is nuxt.config:
![Captura de Tela 2023-03-24 às 15 22 20](https://user-images.githubusercontent.com/83841469/227608591-e6c32f33-4591-4272-a8d7-c69c686f854f.png)

### Additional context

I would like in addition to the answer to have a tip on how to do Seo in Nuxt 3

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by dev02iggy** [comment]
@danielroe
[playback link](https://stackblitz.com/edit/github-x6dths?file=layouts/default.vue)
I made a minimal reproduction conserving the entire package.json. The error continues where only the title is overwritten.

**Comment by danielroe** [comment]
I believe you should use a `key` to deduplicate these tags between your nuxt.config and your layout.

**Comment by harlan-zw** [comment]
Yes as Daniel mentioned you need to provide a key to dedupe the link tags.

You should _avoid_ adding keys to meta tags unless you plan to use the key for further overrides. I pushed up a fix in Unhead 1.1.25 to handle this a bit nicer but it's still not a great idea.

See this reproduction https://stackblitz.com/edit/github-x6dths-v667ew?file=app.vue

**Comment by dev02iggy** [comment]
Thanks @danielroe and @harlan-zw (Mainly because I sent a reproduction of the project)!
In development it's working. In production I'll have to wait because an unforeseen event happened, but anything comes back here

**Comment by dev02iggy** [comment]
I don't know if it was right to answer here or create a new one, but I opted for it right here.
The other issue is resolved, but the part that is related to social networks is not working.
When I share the link, the title, description and image do not appear. Either with useHead or useSeoMeta
![Captura de Tela 2023-03-29 às 10 03 52](https://user-images.githubusercontent.com/83841469/228544167-76f17294-6e40-4bde-baf2-252a0b5a2dd1.png)
There's an example of how I use useSeoMeta. In this case, the data remains the same as the last playback

**Comment by dev02iggy** [comment]
@harlan-zw haha, the last time I tested it was two hours ago and it wasn't working. Now I went to check before finishing the reproduction to send you and it's working. I don't know if it takes time or something, but thanks for everything.
All problems are resolved.

**Comment by jlemonz** [comment]
Hi all. I got this issue. Title does update but description in meta doesnt work. It keeps the description that is in nuxt.config. What to do?

**Comment by Champjiwrd** [comment]
> Hi all. I got this issue. Title does update but description in meta doesnt work. It keeps the description that is in nuxt.config. What to do?

I have same problem too.

**Comment by harlan-zw** [comment]
Please make a new issue with a reproduction if you'd like some help.
