### ISSUE TITLE
pagemeta keepalive and page key

### ISSUE THREAD

**Issue by minkoonim** [nuxt/nuxt#19925]
### Environment

node lts
newest nuxt3
centos

### Reproduction

https://stackblitz.com/edit/github-fnupnd?file=pages/index.vue

### Describe the bug

I'm not sure if it's a bug or my lack of understanding,

1. I have a page where I list photos with infinite scroll
2. it also needs to be filtered by query parameters
3. watch query parameters, when changed, navigateTo('/list', {query})
4. but I want to make sure scroll position stays and data fetch doesn't fire again while navigating back and forth to detail pages and different query pages
5. so I keepalive: true for "keeping it alive" and set page key for differentiating pages with differnt queries.
6. then reproduction happens.
It only happens if **both keepalive and page key** is set, and also **page transition** is set.

### Additional context

thanks for any advice in advance

**Comment by danielroe** [comment]
Setting a page key forces a full refresh when the key changes (that's the purpose of it). This will mean the component will not be kept alive. The two are not compatible with each other. You can handle this [with a custom scrollBehavior,](https://nuxt.com/docs/guide/going-further/custom-routing#using-router-config) though there are already a couple of issues to improve things with the default scrollBehavior.
