### ISSUE TITLE
404 page nuxt3 html, error in google page speed

### ISSUE THREAD

**Issue by ibrahim-990** [nuxt/nuxt#19923]
### Environment

404 page nuxt3 html, error in google page speed

### Reproduction

404 page nuxt3 html, error in google page speed

### Describe the bug

![Screenshot 2023-03-26 140205](https://user-images.githubusercontent.com/65185082/227771441-0e612d51-ebcb-45b5-99bd-db3bc8787143.png)

**Comment by ibrahim-990** [comment]
How I can solve this?

**Comment by manniL** [comment]
Hey! Could you kindly provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by ibrahim-990** [comment]
https://codesandbox.io/p/github/nuxt/starter/v3-codesandbox?file=%2FREADME.md&workspace=%257B%2522activeFileId%2522%253A%2522cl7rh39as0001lngta5o46xuw%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%252C%2522%252Fnuxt.config.ts%2522%252C%2522%252Ferror.vue%2522%252C%2522%252Fpages%252Findex.vue%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clf0xu7l10013356jeb8ntoef%2522%253A%257B%2522key%2522%253A%2522clf0xu7l10013356jeb8ntoef%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522key%2522%253A%2522clfparu9t0014356il5hxycr3%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clf0xu7l10013356jeb8ntoef%2522%252C%2522spacesOrder%2522%253A%255B%2522clf0xu7l10013356jeb8ntoef%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D

**Comment by ibrahim-990** [comment]
this nuxt config

**Comment by ibrahim-990** [comment]
https://codesandbox.io/p/github/nuxt/starter/csb-bsfblc/draft/great-dubinsky?file=%2Fnuxt.config.ts&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A66%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A1%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cl7rh39as0001lngta5o46xuw%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%252C%2522%252Fnuxt.config.ts%2522%252C%2522%252Ferror.vue%2522%252C%2522%252Fpages%252Findex.vue%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clf0xu7l10013356jeb8ntoef%2522%253A%257B%2522key%2522%253A%2522clf0xu7l10013356jeb8ntoef%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522key%2522%253A%2522clfpaxc6a0016356i7yqm958t%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clf0xu7l10013356jeb8ntoef%2522%252C%2522spacesOrder%2522%253A%255B%2522clf0xu7l10013356jeb8ntoef%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D

**Comment by ibrahim-990** [comment]
how i can solve this please ?

**Comment by ibrahim-990** [comment]
@danielkellyio

**Comment by ibrahim-990** [comment]
@danielroe

**Comment by manniL** [comment]
1. Please stop pinging maintainers and be patient
2. Elaborate what your issue is. The CodeSandbox does not run for me and you didn't add any description. If HTTPS is missing from one of your nuxt pages, you should get an HTTPS certificate or ask your hoster. Platforms like Netlify or Cloudflare will provision certificates for free.
