### ISSUE TITLE
The requested module '/_nuxt/node_modules/.vite/deps/vue.js' does not provide an export named 'Component'

### ISSUE THREAD

**Issue by volk234** [nuxt/nuxt#19920]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.3.2`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@1creator/frontend@1.1.41`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-9btn28-2ycvfm?file=app.vue

### Describe the bug

After updating to version 3.3.2 I get this error when using npm module:

![image](https://user-images.githubusercontent.com/22075711/227735659-02556d9c-464c-44d7-9dd6-8eda33d10c30.png)

Module repository:
https://bitbucket.org/1creator/1creator-utils/src/master/packages/frontend/

With Nuxt version 3.1.* it works fine:
https://stackblitz.com/edit/github-9btn28-4mkjqp?file=package.json

**Comment by danielroe** [comment]
Would you try refreshing your lockfile? There's a possibility this issue is occurring because an older version of unimport is being hoisted up by your package manager.

**Comment by volk234** [comment]
@danielroe hello and thanks for your work!

Deleting node_modules and lockfile didn't work. I saw a similar error here https://github.com/nuxt/nuxt/issues/19443. But I checked several times, I don't use import from #build anywhere

**Comment by volk234** [comment]
If it matters, the local module works fine. The problem only occurs when I use NPM module

**Comment by chris-visser** [comment]
Search your codebase for explicit imports on '#imports'. In my case I got this error a number of times when my editor automatically added import statements to this folder/alias. Here's the line from my code that triggered this error:

```js
import { watchEffect } from '#build/imports'
```

Simply removing this/these or similar should do the trick

**Comment by danielroe** [comment]
Thanks! Checking, `unimport` is generating `#build/imports.mjs` including _type_ exports:

```js
export { withCtx, withDirectives, withKeys, withMemo, withModifiers, withScopeId, onActivated, onBeforeMount, onBeforeUnmount, onBeforeUpdate, onDeactivated, onErrorCaptured, onMounted, onRenderTracked, onRenderTriggered, onServerPrefetch, onUnmounted, onUpdated, computed, customRef, isProxy, isReactive, isReadonly, isRef, markRaw, proxyRefs, reactive, readonly, ref, shallowReactive, shallowReadonly, shallowRef, toRaw, toRef, toRefs, triggerRef, unref, watch, watchEffect, isShallow, effect, effectScope, getCurrentScope, onScopeDispose, defineComponent, defineAsyncComponent, resolveComponent, getCurrentInstance, h, inject, nextTick, provide, useAttrs, useCssModule, useCssVars, useSlots, useTransitionState, Component, ComponentPublicInstance, ComputedRef, InjectionKey, PropType, Ref, VNode } from 'vue';
```

cc: @antfu
