### ISSUE TITLE
Nuxt config types failing on VSCode installed typescript version

### ISSUE THREAD

**Issue by angelhdzmultimedia** [nuxt/nuxt#19921]
### Environment

------------------------------
- Operating System: `Windows 10 Home 10.0.19044 Build 19044`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.3.2`
- Nitro Version:    `2.3.2`
- Package Manager:  `pnpm@7.30.3`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

None

### Describe the bug

A fresh Nuxt app, nothing would complete on the config, only `modules` and `telemetry`.

I thought this was a Nuxt related issue, so before I opened an issue, I tried to diagnose myself and filter out all I could:

Changing nuxt version from 3.3.2 to 3.3.1, deleting .nuxt, deleting node_modules, reloading VSCode, restarting TS language server, changing Node version, etc.

Until I had an idea and checked VSCode installed TS version, and yup, that was it.
My latest VSCode version is using TS v4.8.4. 

So I had to create the `.vscode/settings.json` (I rarely have to do this), and set a TS version for the workspace, forcing it to use v5.0.2, and just like that the config props appeared again.

Until now, all the Nuxt 3 apps I've made have been working beautifully (only 2 times where there were reported bugs and were fixed later).

Any kind information will be appreciated.

**Comment by danielroe** [comment]
I can reproduce by installing TS 4.8.4, but not with the current version of VSCode which contains 4.9.5. I'll need to investigate more but for now I'd recommend updating your version of VSCode.

**Comment by angelhdzmultimedia** [comment]
> I can reproduce by installing TS 4.8.4, but not with the current version of VSCode which contains 4.9.5. I'll need to investigate more but for now I'd recommend updating your version of VSCode.

Sorry to have wasted your time. I opened this issue only after I checked if VSCode was updated, and didn't get any notification of a new update.

But now I'm comparing, and I have an old version 1.72 and latest is 1.76!!!

What happened with VSCode's auto update!? No idea...

As always, I wish you health and peace! 🔥🤝

**Comment by angelhdzmultimedia** [comment]
### Update 
The issue turned out to be, my VSCode stopped auto-updating after I set it to run As Admin.
Today I noticed there's a new version and I was on an old version and I investigated and had a hunch, so I disabled run as admin and now the `Check for updates` appeared again! 

Hope this helps someone in the future.
