### ISSUE TITLE
`Modules` and `Showcase` pages are down

### ISSUE THREAD

**Issue by pascalwengerter** [nuxt/nuxt#19939]
### Environment

The nuxt.com website

### Reproduction

https://nuxt.com/modules
https://nuxt.com/showcase

### Describe the bug

When trying to navigate:

![Screenshot 2023-03-27 at 16-50-37 Not found · Nuxt](https://user-images.githubusercontent.com/16822008/227977162-de960071-ce95-470b-83b9-de132595f427.png)

When refreshing the page:

![Screenshot 2023-03-27 at 16-50-43 500 INTERNAL_SERVER_ERROR](https://user-images.githubusercontent.com/16822008/227977177-92ad2439-13ce-4b24-8358-df439426cc61.png)

**Comment by AndrisValisins** [comment]
Same issue here, but looks that whole website is down, only page that is rendered correctly is index for me

**Comment by AndrisValisins** [comment]
Back to normal for me

**Comment by pascalwengerter** [comment]
Same, closing here 🤷🏽
