### ISSUE TITLE
Defining a route (NuxtPage) does not permit `component` property though documentation uses it

### ISSUE THREAD

**Issue by septatrix** [nuxt/nuxt#19940]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `pnpm@7.8.0`
- Builder:          `vite`
- User Config:      `modules`, `quasar`, `vite`, `runtimeConfig`, `typescript`, `hooks`
- Runtime Modules:  `nuxt-quasar-ui@1.0.4`, `@vueuse/nuxt@9.13.0`
- Build Modules:    `-`

### Reproduction

Occurrence in documentation: https://nuxt.com/docs/guide/going-further/custom-routing#using-the-pagesextend-hook

Corresponding type definition: https://github.com/nuxt/nuxt/blob/main/packages/schema/src/types/hooks.ts#L22-L30

### Describe the bug

The documentation adds a route using a `component`. While this should work for directly adding it to the router (`RouteRecordRaw[]`), it does not work for adding routes within the `pages:extend` hook and in my testing lead to errors.

**Comment by danielroe** [comment]
Thanks for spotting! Updated the documentation.
