### ISSUE TITLE
Allow to set global middlewares from `nuxt.config.ts`

### ISSUE THREAD

**Issue by trandaison** [nuxt/nuxt#19948]
### Describe the feature

Use case:
I have created an auth module, my module already added a middleware by calling `addRouteMiddleware`

```ts
addRouteMiddleware('auth', authMiddleware);
```

The problem is I have to set options `{ global: true }`. However, I would like to let user choose to set `auth` middleware global or not themself.

I can add an option in the `auth` property of my module, to set check if global option is `true` or `false`. But in nuxt 2.x, we do have an option `router.middleware` to do this. It could be useful in case some modules add their middleware without `global: true` but user really want to set that middleware to be global.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
I think it makes sense to support this kind of thing and as a team we felt the most configurable way to do this is via `routeRules`, which also allows granular opting-in to named middleware. Let's track in https://github.com/nuxt/nuxt/issues/21913.
