### ISSUE TITLE
The Nuxt3 project reported a 500 error when it was opened on Baidu APP, and other browsers were running normally.

### ISSUE THREAD

**Issue by OnePsycho** [nuxt/nuxt#19946]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@8.2.0`
- Builder:          `vite`
- User Config:      `css`, `app`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

GitLink: https://gitee.com/OnePsycho/xlmy_nuxt
OnlineUrl : http://onepsycho.com

### Describe the bug

The following error occurred:
This problem occurs only when Baidu APP accesses the online address. Other browsers are accessed normally, and there is no problem with local debugging.

![image](https://user-images.githubusercontent.com/43296632/228105699-00cb2b2f-4f21-432d-b6f8-1e694c213c8a.png)

![image](https://user-images.githubusercontent.com/43296632/228105243-f76437bc-739f-4359-b3f2-6564aa4c99d2.png)

![image](https://user-images.githubusercontent.com/43296632/228105328-a11a9da5-d806-4294-9561-02b0afc2132f.png)

![image](https://user-images.githubusercontent.com/43296632/228105336-1d5b1af3-50c7-4ff1-baef-065cff58fd23.png)

**Comment by danielroe** [comment]
Would you provide more information, for example how you have deployed your app, or server logs from Baidu accessing it? What is the full URL accessed? Do you have any way of replicating this, or are you just viewing screenshots from the Baidu crawler?

**Comment by OnePsycho** [comment]
> Would you provide more information, for example how you have deployed your app, or server logs from Baidu accessing it? What is the full URL accessed? Do you have any way of replicating this, or are you just viewing screenshots from the Baidu crawler?

1. My deployment method is the same as the process of this article [deploy action](https://juejin.cn/post/7110115159695163406)
2. You only need to download a Baidu app in your AppStore, and then visit my online address at a 50%chance that there can be errors, and other browsers are normal.
3. Because it is an occasional problem, I cannot locate the wrong position, so I don’t know which part of the information should be provided for you. I have provided the environment, source code and other information. If you still need other information, you can Please tell me the detailed needs. Thanks!!!!

**Comment by OnePsycho** [comment]
Can you give me some hints ?

**Comment by OnePsycho** [comment]
Is it possible that it has something to do with me using lazy loading?

> Would you provide more information, for example how you have deployed your app, or server logs from Baidu accessing it? What is the full URL accessed? Do you have any way of replicating this, or are you just viewing screenshots from the Baidu crawler?

**Comment by OnePsycho** [comment]
I fix it !  The error is  Vite build Target !!!
