### ISSUE TITLE
[module] useFetch is not defined at Module.withAsyncContext

### ISSUE THREAD

**Issue by lucpotage** [nuxt/nuxt#19953]
### Environment

Nuxi 3.3.2

RootDir: /home/projects/github-vumiet
Nuxt project info: 

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.3.2`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-vumiet?file=src/module.ts

### Describe the bug

I add the following server handler to my module (with the corresponding file of course):

```ts
addServerHandler({
  route: '/api/hello',
  method: 'post',
  handler: resolver.resolve('./runtime/server/api/hello')
})
```

In the `app.vue` file, I fetch the new API endpoint:

```vue
<script setup>
const { data } = await useFetch('/api/hello')
</script>
```

I get a 500 server error: `useFetch is not defined`:

```
at Module.withAsyncContext (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7592:21)
at setup (./playground/app.js:12:47)
at _sfc_main.setup (./playground/app.js:43:23)
at callWithErrorHandling (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:171:22)
at setupStatefulComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7194:29)
at setupComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7149:11)
at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:628:17)
at Module.ssrRenderComponent (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:94:12)
at default (./node_modules/nuxt/dist/app/components/nuxt-root.js:67:37)
```

**Comment by danielroe** [comment]
In the module template, we disable auto-imports by default: https://github.com/nuxt/starter/blob/module/.nuxtrc#L1. This is to prevent you from accidentally failing to import dependencies in your module code. (Improvement planned on this one!)

So you will need to import explicitly in the module playground. This does not affect your built application.

**Comment by lucpotage** [comment]
I’m sorry but I don’t understand what you mean by explicitly importing in the module playground.

I tried with the `$fetch` method and it worked, following [your comment](https://github.com/nuxt/nuxt/issues/19292#issuecomment-1445412312) on another issue. So I suppose it’s not an auto-import issue? Where can I understand the difference between `useFetch` and `$fetch`?

````
const res = await $fetch('/api/hello', {
  method: 'POST'
})
```

**Comment by danielroe** [comment]
I mean:
```vue
<script setup>
import { useFetch } from '#imports'
const { data } = await useFetch('/api/hello')
</script>
```

**Comment by lucpotage** [comment]
Ah OK, it makes sense. Thanks. I will dig into the Data Fetching page: https://nuxt.com/docs/getting-started/data-fetching#using-fetch-directly. There are some info about `useFetch` vs `$fetch`.
