### ISSUE TITLE
duplicate <main></main> in body when deploy product.

### ISSUE THREAD

**Issue by devhoangkien** [nuxt/nuxt#19950]
### Environment

npm run build
npm run start

### Reproduction

https://github.com/afsakar/vcard-portfolio

### Describe the bug

# duplicate <main></main> khi deploy product.
## when deploying on netlify 
- the application works normally. But when performing domain pointer, the application displays duplicate `<main></main>` html
example: 
- ok: https://earnest-palmier-afdcdf.netlify.app/
- error: https://cv.devhoangkien.com
## When deploying vps and setting nginx. 
- I enter the IP address the app works normally. but when pointing the domain with nginx the app is duplicated
- ok: https://earnest-palmier-afdcdf.netlify.app/
- error when is setting with nginx: https://about.devhoangkien.com

```
# my nginx
server {
        listen 80;
        listen [::]:80;
        server_name  about.devhoangkien.com;
        # SSL configuration
        listen 443 ssl http2;
        listen [::]:443 ssl http2;
        ssl_certificate         /etc/ssl/cert.pem;
        ssl_certificate_key     /etc/ssl/devhoangkien.key;
        ssl_client_certificate /etc/ssl/cloudflare.crt;
        ssl_verify_client on;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;

    location / {
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_cache_bypass $http_upgrade;
        proxy_read_timeout 1m;
        proxy_connect_timeout 1m;
        proxy_pass http://localhost:5000;
    }
}
```

**Comment by devhoangkien** [comment]
when is duplicate![image](https://user-images.githubusercontent.com/46822388/228165079-d1b23fc1-f3d6-4431-868c-b81f8413e171.png)

**Comment by devhoangkien** [comment]
![image](https://user-images.githubusercontent.com/46822388/228165403-715dc0dc-c8d3-41f7-83a3-00c0c3350c26.png)
duplicate <main></main>

**Comment by manniL** [comment]
<img width="855" alt="image" src="https://user-images.githubusercontent.com/640208/228183467-b820f521-8e82-4980-a1a3-e865f52ebce2.png">

This is an hydration error. 

See https://vuejs.org/guide/scaling-up/ssr.html#hydration-mismatch and https://blog.lichter.io/posts/vue-hydration-error/
