### ISSUE TITLE
How to get the proper value from useFetch

### ISSUE THREAD

**Issue by acche** [nuxt/nuxt#19956]
Try to use useFetch to fetch an API:
```
async send() {
    const response = await useFetch('https://jsonplaceholder.typicode.com/todos/1', { 
        headers: {
            'Content-Type': 'application/json'
         },
    })
    console.log(response);
}
```
but could not get the proper return value, the console shows:
<img width="624" alt="image" src="https://user-images.githubusercontent.com/1592763/228226098-657fe44e-cdf7-4539-a33c-294787882880.png">

At the same time to check the web network, it return the API content:
<img width="548" alt="image" src="https://user-images.githubusercontent.com/1592763/228226339-13736f4f-0966-4c1f-a6e4-8c625c676672.png">

Can you help me get the real value of this function?

**Comment by danielroe** [comment]
`response.data.value`.

`useFetch` returns an object with a number of utilities, including `data`, `error`, etc. `data` is a Vue ref, which means you have to access `data.value` to get the underlying value.

**Comment by acche** [comment]
@danielroe 
```
async send() {
    const data = await useFetch('https://jsonplaceholder.typicode.com/todos/1', { 
        headers: {
            'Content-Type': 'application/json'
         },
    })
    console.log(data.value);
}
```
get:
undefined

Sorry can not understand it. Please give me more detail.

**Comment by acche** [comment]
@danielroe
1  I will add some query, mode and auth header on next step, will $fetch be able to fix it?
2 And this is Nuxt knowledge, I want to  study it.
Many thanks.

**Comment by danielroe** [comment]
Both `$fetch` and `useFetch` can take those options, yes.

**Comment by acche** [comment]
@danielroe After changing to $fetch, the result same as above.

console:
<empty string>

Quit wired.

**Comment by danielroe** [comment]
https://stackblitz.com/edit/github-du3uvb?file=app.vue

**Comment by acche** [comment]
I realized I missed a detail and didn't write it in my issue.

I had add
```
 mode: 'no-cors'
```
Is this will cause some problem?

**Comment by danielroe** [comment]
Yes, that is not compatible with that API.

<img width="776" alt="CleanShot 2023-03-28 at 13 59 18@2x" src="https://user-images.githubusercontent.com/28706372/228243982-b2a9f90a-5c84-4fdb-94a2-f81c7cf0884a.png">

https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

**Comment by acche** [comment]
@danielroe  So does that mean we can't use 'no-cors' on the Nuxt side to solve the cross-domain issue?

**Comment by danielroe** [comment]
Not if you are wanting to fetch JSON, no. That's a browser limitation.

**Comment by acche** [comment]
> Not if you are wanting to fetch JSON, no. That's an (intended) browser limitation.

OK，thanks @danielroe. I try Next.

**Comment by danielroe** [comment]
It's not a Nuxt limitation. It is how web browsers work.

**Comment by acche** [comment]
> It's not a Nuxt limitation. It is how web browsers work. You cannot bypass CORS restrictions with `no-cors` unless it is a certain type of request.
> 
> 
> 
> Nuxt does provide built-in utilities for adding CORS headers for your API routes, if that is relevant for you.

@danielroe Could you please provide any solutions to resolve the CROS error either?
