### ISSUE TITLE
Different wildcard variables in same api folder crash routes

### ISSUE THREAD

**Issue by tamutus** [nuxt/nuxt#19965]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.3.2`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@9.6.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

[Minimum reproduction](https://github.com/tamutus/Nuxt-3-routes-with-different-slug-names): any nuxt project, create files `/server/api/[a].get.ts` and `/server/api/[b].post.ts` and neither route will work, even though they don't semantically conflict.

### Describe the bug

If you use different variables for the different methods of a route, none of those routes will work.

I don't see why this shouldn't be allowed, but if it's a struggle to fix, it should at least be mentioned in the documentation that slug names have to be identical in a given route, and error messages should reflect this at compile time. I ran into this problem when making mutative API routes require id, while the get route uses a wildcard in a containing folder (i.e. `/[bucket]/file/[title].get.ts` ) and the title to uniquely fetch something.

### Logs

```shell-script
Console error: `Failed to load resource: the server responded with a status of 405 (Method get is not allowed on this route.)`

Response (trimmed directory names but they start with `C:/` ): 


{
url: "/api/a",
statusCode: 405,
statusMessage: "Method get is not allowed on this route.",
message: "Method get is not allowed on this route.",
stack: "<pre><span class="stack internal">at createError .../node_modules/h3/dist/index.mjs:128:15)</span>
<span class="stack internal">at Object.handler (/C:/.../node_modules/h3/dist/index.mjs:1424:13)</span>
<span class="stack internal">at Object.handler (/C:/...node_modules/h3/dist/index.mjs:1247:31)</span>
<span class="stack internal">at process.processTicksAndRejections (node:internal/process/task_queues:95:5)</span>
<span class="stack internal">at async Server.toNodeHandle (/C:/.../node_modules/h3/dist/index.mjs:1322:7)</span></pre>"
}
```
```

**Comment by danielroe** [comment]
let's track upstream in https://github.com/unjs/nitro/issues/1093.
