### ISSUE TITLE
Nuxt module addComponent from a dependency import results in `The requested module is a CommonJS module`

### ISSUE THREAD

**Issue by VividLemon** [nuxt/nuxt#19974]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v19.4.0`
- Nuxt Version:     `3.3.2`
- Nitro Version:    `2.3.2`
- Package Manager:  `pnpm@7.25.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

I can't really figure out the best way to expose a "minimal" reproduction. The issue relies on a dependency. 
You can view the code that I'm using to addComponent here -> https://github.com/VividLemon/bootstrap-vue-next/blob/main/packages/nuxt/src/composables/useComponents.ts

& The whole package -> https://github.com/VividLemon/bootstrap-vue-next/tree/main/packages/nuxt

### Describe the bug

The playground dev environment works fine. However, when trying to run `pnpm prepack`, the library throws: 
```
Named export 'Components' not found. The requested module 'bootstrap-vue-next' is a CommonJS module, which may not support all module.exports as named exports.               20:54:27
CommonJS modules can always be imported via the default export, for example using:
```
This is a bit strange as the dist exposes umd.js & es.js files. I'm not certain why it would be attempting to use the CommonJs module specifically, but maybe it's because JS module resolution confuses me.

The suggestion, 
```
import pkg from 'bootstrap-vue-next';
  const { Components } = pkg;
```
Doesn't quite work as the file has a default export. So 'pkg' in this case doesn't provide pkg.Components. It might do something, but it doesn't show intellisense that it exists.

I believe the issue stems from when Nuxt is compiling the cjs variant. As the dist/mjs file is made and seemingly works fine.

I'm not quite sure how to fix the issue. It's more likely that I am doing something wrong here and it's not a @nuxt/kit issue. Any insight on fixing the issue would be appreciated.

**Comment by danielroe** [comment]
It looks like `bootstrap-vue-next` is not a valid ESM module. (`.es.js` is not a permitted file extension for ESM unless `type: module` is set in the package.json.)

I think you will need to use the workaround, with perhaps some console-logging to work around the fact that intellisense won't tell you the keys of `pkg`.

**Comment by VividLemon** [comment]
Okay, a couple of questions arise when thinking about this.

> It looks like bootstrap-vue-next is not a valid ESM module. (.es.js is not a permitted file extension for ESM unless type: module is set in the package.json.)

Are you saying this because the extension is not exactly "mjs"/"cjs", instead "es.js" & "umd.js" respectively? The issue in this case would not be that they are not valid files, but that Nuxt is not recognizing them because they aren't the standard structure? -- Specifically the es.js file. I believe umd.js is the Vite default format that is built in library mode.

> is not a permitted file extension for ESM unless type: module is set in the package.json.)

But would it not be permitted if the package.json was:

```json
  "main": "./dist/bootstrap-vue-next.umd.js",
  "module": "./dist/bootstrap-vue-next.es.js",
  "exports": { ".": { "import": "...es.js", "require": "...umd.js" }
```

Would files that enter through automatically get told that the module is file "...es.js"? Which begs a further question, if everyone else works, is it simply that @nuxt/kit ignores these properties defined in the targets the package.json? Could it not be a feature to have it scan first in order to get the correct values?

Overall this has been helpful. I had changed Vites config 

from: `fileName: (format) => `bootstrap-vue-next.${format}.js`,`
to: `fileName: `bootstrap-vue-next`,

And the dist creates a mjs file, and as such, prepack is working as expected.

**Comment by danielroe** [comment]
The issue here wasn't caused by Nuxt but by Node. There is a little bit more here: https://nuxt.com/docs/guide/concepts/esm. Because your module is being compiled to native Node ESM, it can't import from `.es.js` - the file extension matters in this case. (The complaint isn't about the content of the file.)
