### ISSUE TITLE
Firebase Deploy dotenv Variables not Available on Server

### ISSUE THREAD

**Issue by chrisspiegl** [nuxt/nuxt#19988]
Hello,  I just tried deploying a SSR site to Firebase which uses different `.env` / `.env.staging` etc… files.

When deploying to Firebase, firebase usually picks up the files named based on the `firebase use…` command (named environment).

However, it seems that for the deploy for the server function it would expect the `.env.{env-name}` to be inside the `./.output/server` folder? 

By default, the variables where not defined / falling back to my defaults set in the `nuxt.config.ts` file.
But when I was copying the `.env.staging` into `.output/server` file, then the deploy to firebase did work.

Is there a way to work this out? Am I missing something? I tried googling / stackoverflow / etc. but did not find a good solution yet besides copying my `.env.{env}` into the `.output/server` folder.

I'd appreciate any help or ideas.

Cheers, Chris

### Reproduction

Deploy to firebase with a dedicated named `.env.staging` or similar file in the root directory of the nuxt project and notice the values in `useRuntimeConfig()` not to be present.

**Comment by edwinhuish** [comment]
Here is the doc:  [Nuxi CLI has built-in support for reading your .env file in development, build and generate. **_But when you run your built server, your .env file will not be read._**](https://nuxt.com/docs/guide/going-further/runtime-config#environment-variables)

**Comment by chrisspiegl** [comment]
@edwinhuish Thanks for the link. But how shall one handle the deploy to firebase then?

Firebase uses the structure of: `.env.staging` or `.env.whatever` as setup with `firebase use` (basically to link an `.env` to a dedicated firebase project.

Then when using `firebase deploy` it uploads those `.env` files which are located usually in the `/functions` folder to set the variables on the server.

With nuxt or rather nitro, it builds the functions folder (which ends up being `.output/server` and when deploying, it does not make the `.env` variables part of the deploy.

So, I understand that the variables "are not available" when ruing the built server, but we need a way to deploy them to firebase? A workaround is the one I already wrote about in my initial post (copy the `.env.watever` into the `.output/server` folder) but that feels more like a hack than a "good solution".

**Comment by edwinhuish** [comment]
I'm also looking for the solution similar. But seems only way is rebuild again. 

[Here is the doc related to it.](https://nuxt.com/docs/guide/directory-structure/env#env-file)

Add one script to your package.json
```json
  "scripts": {
    "build": "nuxt build --dotenv .env.staging"
  }
```

**Comment by chrisspiegl** [comment]
@edwinhuish The `nuxi build --dotenv .env.stagin` works for the frontend `.env variables` (and I already use it), but not for the server side.

> However, after your server is built, you are responsible for setting environment variables when you run the server. Your .env file will not be read at this point. How you do this is different for every environment. On a Linux server, you could pass the environment variables as arguments using the terminal DATABASE_HOST=mydatabaseconnectionstring node .output/server/index.mjs. Or you could source your env file using source .env && node .output/server/index.mjs.

So, still different from what I am talking about.

What I am talking about might be specific to nitro (I think that's why @danielroe sent it upstream). To me, it seems this would be a great point for the build presets of nitro to support a way to pull the .env in somehow. But who knows 🙈.

**Comment by danielroe** [comment]
I may have misunderstood. I thought you were suggesting that _firebase_ read in any .env files present at runtime into the environment. In that case, we could ensure we move them across into the appropriate location when preparing the firebase output (and that was the upstream issue I meant to create).

But if your point is that you are expecting _nitro_ to read them in at runtime, then I think that is a separate issue. Related: https://github.com/unjs/nitro/issues/1079.

**Comment by chrisspiegl** [comment]
Hi @danielroe , I meant the first thing: moving them to the appropriate location so that the `firebase deploy` picks them up correctly while doing the deploy.

**Comment by edwinhuish** [comment]
I didn't use firebase before, but I think you are looking for env variable in production. 

If you are in linux server, you could run in this way:
```bash
DATABASE_HOST=mydatabaseconnectionstring node .output/server/index.mjs
```

Or one bash file `.env.sh` like:
```bash
export DATABASE_HOST=mydatabaseconnectionstring
export DATABASE_PASS=mydatabasepassword
```

And run 
```bash
source .env.sh && node .output/server/index.mjs
```

**Comment by chrisspiegl** [comment]
@edwinhuish This issue specifically is about Firebase deploy. Nothing dodo with running a `node .output/server/index.mjs` process. It's a very different environment.

**Comment by igorjacauna** [comment]
And if we increment the Firebase preset [here](https://github.com/unjs/nitro/blob/main/src/presets/firebase.ts#L18)? Where we could check if a .env file exists and copy to server output dir?

**Comment by Hebilicious** [comment]
Hello, the current behaviour seems fine to me, although we could documented it better. 

I would recommend that as part of your deploy command, you copy your env file in your dist folder
ie, if you have something like this : 

```json
{
  "functions": { "source": ".output/server" },
  "hosting": [
    {
      "site": "<your_project_id>",
      "public": ".output/public",
      "cleanUrls": true,
      "rewrites": [{ "source": "**", "function": "server" }]
    }
  ]
}
```
Since you want your `.env` file to be in your `.output/server` : 

```json
  "scripts": {
    "build": "nuxi build",
	"prepare:env": "cp .env .output/server/",
    "deploy": "pnpm prepare:env && firebase deploy"
    }
 ```
 And then run your deploy command `pnpm deploy`. For windows or other package manager you will need to refactor this, but the approach will be the same. 

Given that Nitro doesn't handle the deploy command, this seems fair to me. I would also assume that there are situations where you do not want this to happen, or you want to copy `.env.production`, or you are using a SaaS service for secret like hashicopr vault ... So I'm not sure we should add this to Nitro.

**Comment by igorjacauna** [comment]
Nice @Hebilicious .

I had a similar solution. But I have used `postbuild` script to run `cp .env .output/server`. So, every time `build` finish, `yarn` automatically run the `postbuild` that will copy the file.

```json
"scripts": {
  "build": "nuxi build",
  "postbuild": "cp .env .output/server"
}
```

Every time I run `yarn build`, automatically after `build` finish, `yarn` will run `postbuild`.

I thought once there is use of `.env` files in deploy by Firebase Tools, maybe include this `.env` file handler in preset is a good idea.

But, again, just a idea.

**Comment by danielroe** [comment]
If you're still experiencing this, would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏

If it only recurs with Nuxt, let me know and I'll reopen it here.

**Comment by chrisspiegl** [comment]
Just adding this as one solution I am using for this use case when combined with GitHub Actions.

In that case, you can write the `.env` dynamically with a Shell Script and then the deploy will take this `.env` in the `.output/server` folder and provide it to the server function so that SSR work as expected.

https://github.com/unjs/nitro/issues/1098#issuecomment-2258100451
