### ISSUE TITLE
I want to filter some components and not add them all to the router

### ISSUE THREAD

**Issue by f754699** [nuxt/nuxt#19983]
### Describe the feature

我想过滤部分组件，让他们不添加到router里面,比如特定名称的组件，或者特定文件夹里面的组件

I want to filter some components so that they are not added to the router, such as components with specific names or components in specific folders

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
Components outside of `pages` should not represent pages.
If you store components *in* your `pages` folder, you can e.g. filter them in the `page:extends` hook. See [also docs](https://nuxt.com/docs/guide/going-further/custom-routing#using-the-pagesextend-hook).
