### ISSUE TITLE
State not persists in Pinia

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/nuxt#19980]
### Environment

RootDir: /home/projects/nuxt-starter-b3gnpr                                                                       14:23:07
Nuxt project info:                                                                                                14:23:07

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.3.2`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@pinia/nuxt@0.4.7`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                       14:23:07

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Reproduction

https://stackblitz.com/edit/nuxt-starter-b3gnpr

### Describe the bug

In the playback link, you can see that I am using the storage in two places (page and component), in theory, once the "application" json is loaded, it should not be loaded again, returning the Pinia status. However, the log is being painted twice "application empty we assign"

**Comment by manniL** [comment]
Use `useAsyncData` when fetching the data (`await appStore.load();`). See https://pinia.vuejs.org/ssr/nuxt.html#using-the-store-outside-of-setup

**Comment by agracia-foticos** [comment]
> Don't return `this` in your `load` function.

I change the code as you suggested, but not the desired behavior
https://github.com/nuxt/nuxt/issues/19980#issuecomment-1488783486

we want it to load only the object the first time and then return the loaded object to the store and not ask for it again.

Where we have the `const string = 'hello';` actually there is an axios request that we do not want it to perform every time the store is requested, only the first time

**Comment by agracia-foticos** [comment]
> This should still work as you described. Don't return the whole store but the state (easier with `setup`-style store)

Sorry, I don't understand, can you give me an example? Thanks in advance
