### ISSUE TITLE
Empty global components props typings

### ISSUE THREAD

**Issue by niklv** [nuxt/nuxt#20010]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.18.1`
- Nuxt Version:     `3.3.2`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/niklv/nuxt-component-props-def-bug

### Describe the bug

For my project config typing I need to refer to typing of component props.
I try extract props typing in this way. But looks like there are no props typing at all.
```vue
<script lang="ts" setup>
// ComponentA.vue
const {propA} = defineProps<{
    propA: string
}>()
</script>

<template>
    <div v-text="propA" />
</template>

```

```ts
// config.ts
import type {ComponentA} from "#components";
import {ComponentOptionsBase} from "@vue/runtime-core";


type ComponentProps<T> = T extends ComponentOptionsBase<infer P, // Props
    any, // RawBindings
    any, // D
    any, // C
    any, // M
    any, // Mixin
    any, // Extends
    any> ? unknown extends P ? {} : P : {};


type CompAProps = ComponentProps<typeof ComponentA>


const someConfig:CompAProps = {
    // @ts-expect-error
    notExistedProp: true // should be error
}
```

### Additional context

![изображение](https://user-images.githubusercontent.com/3831943/229060655-174418c6-b97e-46ca-8b82-49b33336dcf3.png)

There are must be some props typing in first generic argument of `DefineComponent`

**Comment by danielroe** [comment]
Would you raise this issue upstream with https://github.com/vuejs/language-tools? From what I can see the props are coming through, slightly modified by Volar:

![CleanShot 2023-04-05 at 13 48 55](https://user-images.githubusercontent.com/28706372/230085093-014a9b61-7ae6-4bc9-b1e8-39a338b0d11e.png)

**Comment by danielroe** [comment]
Yes, I'm using VSCode. If you're using Webstorm, then the types for the imported Vue files (in your editor) will be inferred by Webstorm. The types when using `nuxi typecheck` or `vue-tsc --noEmit` will be provided by Volar, however.

**Comment by everyx** [comment]
A temporary workaround is change `moduleResolution` to `nodenext`, upstream issue: https://github.com/vuejs/language-tools/issues/3390

```diff
{
  "extends": "./.nuxt/tsconfig.json",
+   "compilerOptions": {
+     "moduleResolution": "nodenext"
+  }
}
````

**Comment by danielroe** [comment]
Closing as this is not a Nuxt issue.
