### ISSUE TITLE
document `nuxt/image` features

### ISSUE THREAD

**Issue by danielroe** [nuxt/nuxt#20012]
[`@nuxt/image`](https://github.com/nuxt/image) is a core Nuxt ad-hoc module. Once we release v1 stable version with Nuxt 3, we should document `<NuxtImg>` and `<NuxtPicture>`. (We might add some stub documentation before that point.)

I also think we should consider adding it as a core `nuxt` dependency so it's available out-of-the-box, although it would be versioned separately. Timetable - we would aim for the next minor version after we release v1 of `nuxt/image`.

Thoughts very welcome.

**Comment by pi0** [comment]
Adding as direct dev-dependency is probably not best idea but we could create a placeholder component that asks to auto-install `nuxt-image` module on first usage (similar to how vitest-ui is integrated for example)

Also fully agree on docs. Both for introduction page in getting started and in the API/Components similar to `NuxtContent`.
