### ISSUE TITLE
bug(schema): cannot load module no "exports" main defined

### ISSUE THREAD

**Issue by Lexpeartha** [nuxt/nuxt#20026]
### Environment

Creating nuxt module with following info:

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.17.1`
- Nuxt Version:     `3.3.2`
- Nitro Version:    `2.3.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/Lexpeartha/nuxt-xstate/tree/inspector-support

### Describe the bug

Stubbing module with `npx nuxt-module-build --stub` always fails with:

```
 ERROR  No "exports" main defined in /home/aleksa/Desktop/Projects/nuxt-xstate/node_modules/@nuxt/schema/package.json

  at new NodeError (node:internal/errors:387:5)
  at throwExportsNotFound (node:internal/modules/esm/resolve:464:9)
  at packageExportsResolve (node:internal/modules/esm/resolve:688:7)
  at resolveExports (node:internal/modules/cjs/loader:493:36)
  at Function.Module._findPath (node:internal/modules/cjs/loader:533:31)
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:942:27)
  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
  at _resolve (node_modules/jiti/dist/jiti.js:1:241025)
  at jiti (node_modules/jiti/dist/jiti.js:1:243309)
  at node_modules/@nuxt/kit/dist/index.mjs:18:15


 ERROR  Cannot load module. Please check dist: /home/aleksa/Desktop/Projects/nuxt-xstate/dist/module.mjs
 ```
 
 Here's the content of the referenced `module.mjs`:
 ```
 import jiti from 'jiti';
export default jiti(null, { interopDefault: true })('/home/aleksa/Desktop/Projects/nuxt-xstate/src/module');
 ```

### Additional context

Because of this, I'm unable to use `dev:prepare` for testing module locally

This issue appeared when I bumped nuxt from 3.2 to 3.3.2 (I think?)

**Comment by danielroe** [comment]
Would you try refreshing your lockfile to bump your version of `jiti`?

**Comment by danielroe** [comment]
in any case, this should be resolved with https://github.com/nuxt/nuxt/commit/1fd491f1a5602e6f4cb05e2f27ba17179a095e0b.

**Comment by GithubMitch** [comment]
Changing to this solved it for me ...
    // import { defineNuxtConfig } from "nuxt"
    import { defineNuxtConfig } from "nuxt3/config"

Then i encountered the following error :
    "Cannot read properties of undefined (reading 'port')"

I solved this by running the 'npm run dev' command with a port like : "npm run dev 3000"
