### ISSUE TITLE
useCookies not working after npm run build && npm run preview

### ISSUE THREAD

**Issue by kurtobando** [nuxt/nuxt#20036]
### Environment

```
------------------------------
- Operating System: `Linux`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@8.5.5`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `modules`, `googleFonts`, `tailwindcss`, `imports`
- Runtime Modules:  `@nuxtjs/google-fonts@3.0.0`, `@nuxtjs/robots@3.0.0`, `@nuxtjs/tailwindcss@6.4.1`, `nuxt-simple-sitemap@1.0.7`, `@pinia/nuxt@0.4.7`, `@pinia-plugin-persistedstate/nuxt@1.1.1`
- Build Modules:    `-`
------------------------------

```

### Reproduction

Create a global middleware in middleware direcetory, e.g `myMiddleware.global.ts`
```
export default defineNuxtRouteMiddleware(async (to, from) => {
    const cookie = useCookie('slug');
    cookie.value = 'hello-world';
});

```

Create a server api in server/api directory, e.g `my-api.ts`
```
import { useCookie } from '#app/composables/cookie.mjs';

export default defineEventHandler( (event) => {
    const cookie = useCookie('slug');
    console.log('cookie', cookie.value);

    return {
        statusCode: 200,
    };
});

```

Create a simple page route, in pages directory e.g `hello-world.vue`
```
<template>
    <p>Hello World</div>
</template>

<script setup></script>

<style scoped></style>

```

### Describe the bug

This works perfectly when we are on npm run dev, however, after `npm run build` && `npm run preview`, console logs returns `undefined` here are some screenshots below:

In npm run dev, let us visit a page, let say `http://localhost:3000/hello-world/` just to trigger to the global middleware, it returns the created cookies as expected;
![image](https://user-images.githubusercontent.com/38178537/229359892-ac0eacb3-053a-4696-a366-641bdbbbc1bc.png)

then visit `http://localhost:3000/api/my-api`, and see the console log from the terminal
![image](https://user-images.githubusercontent.com/38178537/229359966-d63179aa-d103-4c50-9588-5dcbd9c690ad.png)

Now, let us `npm run build` && `npm run preview`, and then visit `http://localhost:3000/hello-world/`, it returns the created cookies as expected; but this time, console log returns `undefined`

![image](https://user-images.githubusercontent.com/38178537/229360372-13eb6c11-faf0-4aad-a0fe-28ab144e2e77.png)

Any suggestion on how to go about this?

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

You may need to confirm the behaviour locally as sometimes cookies don't work as expected in stackblitz.
