### ISSUE TITLE
Nitro hooks registered in "nitro:init" not being called

### ISSUE THREAD

**Issue by semiaddict** [nuxt/nuxt#20034]
### Environment

Nuxi 3.3.2                                                                                                                                                                            15:51:39
                                                                                                                                                                                      15:51:40
RootDir: ~/nuxt-nitro-hook-repro                                                                                                                              15:51:40
Nuxt project info:                                                                                                                                                                    15:51:40

------------------------------
- Operating System: `Linux` (WSL)
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.3.2`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@9.5.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Here is a minimal repro : https://stackblitz.com/edit/github-hbctsy?file=modules/my-module/index.ts

The important code is under "modules/my-module", which adds a server handler for `/my-module.json` and registers a listener on the custom nitro hook "my-module:myHook".
The hook is called from within the server handler to modify the response.

If the `/my-module.json` route is visited, the result should be:
```json
{ "called": true }
```

But the actual result is:
```json
{ "called": false }
```

### Describe the bug

From the [docs](https://nuxt.com/docs/api/advanced/hooks), the `nitro:init` hook is _called after Nitro is initialized, which allows registering Nitro hooks and interacting directly with Nitro_.
However, nitro hook listeners registered here don't seem to get called.

For example, the hook listener for `my-module:myHook` below is never called:
```js
nuxt.hook('nitro:init', (nitroApp) => {
  nitroApp.hooks.hook('my-module:myHook', (result) => {
    console.log('my-module:myHook called');
    result.called = true
  });
});
```

I have verified that the code in `nitro:init` is correctly being called. So the issue is not with that hook.

Note: I have also tested with existing hooks such as "content:file:afterParse" from the content module (see https://content.nuxtjs.org/api/advanced#contentfileafterparse), but the hook listener is also never called.

### Additional context

I ran into this issue while trying to find a way to alter the response of the server handler from within the module as I need access to module options.

**Comment by danielroe** [comment]
The issue is that there are two 'nitros' - there is the build time nitro, which we call 'nitro', and the runtime nitro, which is called either 'nitro app' or 'nitro runtime'. You are calling a hook on the runtime nitro (from your API) but you have registered the hook on the build-time nitro.

**Comment by semiaddict** [comment]
@danielroe, thank you for this information.
I don't know if it's me, but I don't think this is clear in the docs.

I am trying to build a pre-rendered search index (using [MiniSearch](https://lucaong.github.io/minisearch/)) for all content in SSG mode, and need to either (1) access module options from the route, or (2) alter route output from the module. How can I achieve one of those?

**Comment by danielroe** [comment]
You can inject what you need to pass to the runtime via `nuxt.options.appConfig` or  `nuxt.options.runtimeConfig`. There are other options too, including adding a virtual module.
