### ISSUE TITLE
expose `nuxi` for user to customize their command

### ISSUE THREAD

**Issue by gumingWu** [nuxt/nuxt#20041]
### Describe the feature

Maybe `nuxi` can expose some entry for user to customize themself command

For example, I want to use a command to create a template quickly, but don't like to create a new `bin`, so I want to add this new command into `nuxi`

More detail, user can add their command into a new floder, named `command`, the filename is the command name

| command
|----- theme.ts

so I can `nuxi theme`

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
This is planned - let's track in https://github.com/nuxt/nuxt/issues/13634.
