### ISSUE TITLE
`watch` api cannot auto unwatch when page is unmounted if there is `await` in `onMounted` before `composable API`

### ISSUE THREAD

**Issue by gyhyfj** [nuxt/nuxt#20043]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.3.3`
- Nitro Version:    `2.3.2`
- Package Manager:  `pnpm@8.1.0`
- Builder:          `vite`
- User Config:      `modules`, `vite`, `css`, `imports`, `eslint`, `stylelint`, `pinia`, `i18n`, `routeRules`, `appConfig`
- Runtime Modules:  `@nuxtjs/eslint-module@4.0.2`, `@nuxtjs/tailwindcss@6.6.0`, `@nuxtjs/stylelint-module@5.0.1`, `@nuxtjs/i18n@8.0.0-beta.10`, `@pinia/nuxt@0.4.7`, `@pinia-plugin-persistedstate/nuxt@1.1.1`, `nuxt-vitest@0.6.8`, `@nuxtjs/device@3.1.0`, `nuxt-icon@0.3.3`, `nuxt-gtag@0.2.2`, `@nuxt/devtools@0.3.1`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-gqjmkc?file=pages/index.vue

Such `watch` cannot auto unwatch when page is unMounted, if there is await before composable API like `useRouter` .
so I have to unwatch it manually.

### Describe the bug

`watch` api cannot auto unwatch when page is unmounted

**Comment by gyhyfj** [comment]
@manniL  Here is it sir :
https://stackblitz.com/edit/github-gqjmkc?file=pages/index.vue
Often I need to use `await import` to execute some client only code by putting these code in `onMounted` , and  use `useFetch` to send some request in `onMounted` also. Then I have to unwatch every `watch` API manually, and I don't know if there is any other memory leaking.

**Comment by danielroe** [comment]
`useFetch` should not be used in `onMounted`. Instead, you can use `$fetch` directly.

**Comment by gyhyfj** [comment]
You’re right, thank you very much

**Comment by danielroe** [comment]
The reason you are experiencing this is that you are calling `useRoute` within `onMounted`, after an await, which means it isn't bound to the instance. You should move `useRoute` and `useRouter` out of the `onMounted` callback.
