### ISSUE TITLE
`useSeoMeta` input type cannot support `keywords`

### ISSUE THREAD

**Issue by gyhyfj** [nuxt/nuxt#20045]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.3.2`
- Package Manager:  `pnpm@8.1.0`
- Builder:          `vite`
- User Config:      `modules`, `vite`, `css`, `imports`, `eslint`, `stylelint`, `pinia`, `i18n`, `routeRules`, `appConfig`
- Runtime Modules:  `@nuxtjs/eslint-module@4.0.2`, `@nuxtjs/tailwindcss@6.6.0`, `@nuxtjs/stylelint-module@5.0.1`, `@nuxtjs/i18n@8.0.0-beta.10`, `@pinia/nuxt@0.4.7`, `@pinia-plugin-persistedstate/nuxt@1.1.1`, `nuxt-vitest@0.6.8`, `@nuxtjs/device@3.1.0`, `nuxt-icon@0.3.3`, `nuxt-gtag@0.2.2`, `@nuxt/devtools@0.3.1`
- Build Modules:    `-`

### Reproduction

`useSeoMeta` input type cannot support `keywords`, but it works in actually.
```vue
useSeoMeta({
  title: 'xx',
  description: 'xx',
  keywords: 'xx',
})
```

### Describe the bug

Maybe type `UseSeoMetaInput` should includes `keywords` ?

**Comment by manniL** [comment]
Note: Not sure if necessary as `keywords` are obsolete for SEO nowadays

**Comment by Lehoczky** [comment]
What if we add `keywords` to the type, but mark it as deprecated? A link to some source could be added as well to the jsdoc, that is about the `keywords` being obsolete for SEO.

I know the deprecated tag is not necessarily for this purpose, but users would see it instantly crossed out in their IDE without an error being thrown.

**Comment by danielroe** [comment]
That's a nice idea. What do you think @harlan-zw?

**Comment by harlan-zw** [comment]
When using `useSeoMeta` the `keywords` key is now typed as deprecated (requires v1.1.28 of Unhead).
