### ISSUE TITLE
please upgrade nuxt2 to webpack5, and then finish!

### ISSUE THREAD

**Issue by lelouch-xue** [nuxt/nuxt#20055]
### Describe the feature

please upgrade nuxt2 to webpack5

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
We have already upgraded to webpack 5 in Nuxt 3.

We will not be upgrading the legacy branch (Nuxt 2) to webpack 5 as it is a significant breaking change for users on v2.

**Comment by lelouch-xue** [comment]
That's no choice, but I still hope to upgrade to webpack5. Thank you for your reply
