### ISSUE TITLE
Uncaught ReferenceError: Cannot access 'X' before initialization

### ISSUE THREAD

**Issue by nzuyanov** [nuxt/nuxt#20058]
### Environment

Nuxt Version: `3.3.3`
Nitro Version: `2.3.2`
Builder: `vite`

### Reproduction

nuxt.config.ts
```
export default defineNuxtConfig({
  ssr: false,
  vite: {
    build: {
      rollupOptions: {
        output: {
          manualChunks(id) {
            if (id.includes('vue')) {
              return 'vue';
            }
            if (id.includes('node_modules')) {
              return 'vendor';
            }
          },
        },
      },
    },
  },
});
```

### Describe the bug

I'm trying to split some dependencies (for example vue) into a separate chunk. After fix of this issue https://github.com/nuxt/nuxt/issues/19837 i see error like `Uncaught ReferenceError: Cannot access 'X' before initialization` in console and nothing works in production build.

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by danielroe** [comment]
I  can't reproduce this - https://stackblitz.com/edit/github-gmvrwz?file=package.json.

I'll happily reopen if you are able to provide a reproduction.

**Comment by linooohon** [comment]
Hi @nzuyanov , 
Did you already solve this problem?
I am also encountering this issue when I add `manualChunks` in Nuxt Config:
```
manualChunks(id) {
            if (id.includes('node_modules')) {
              return id.toString().split('node_modules/')[1].split('/')[0].toString();
            }
          }
```

**Comment by MosheL** [comment]
I  see the same problem with manualChunks.

**Comment by MosheL** [comment]
update: I can reproduct:

https://stackblitz.com/edit/github-gmvrwz-x9yx6b?file=nuxt.config.ts

build, start, and you can see the error and the blank screen:

![image](https://github.com/nuxt/nuxt/assets/2265043/e147061a-a699-4c5b-9259-fd7e6e82da25)


If i remove the `return 'site';` for some of the  chunks it will work.
