### ISSUE TITLE
Server Memory leaks, high CPU usage - appConfig

### ISSUE THREAD

**Issue by burda-osowiecki** [nuxt/nuxt#20056]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@9.6.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

I cannot reproduce it in small scale and ofc also cannot share our project code...
I hope someone other will have similar problem and be able to reproduce in from scratch.

### Describe the bug

![image](https://user-images.githubusercontent.com/118734217/229534317-182a8443-7a4a-49f8-8ea6-20ef2ff8373e.png)
![image](https://user-images.githubusercontent.com/118734217/229534514-e5e3ccda-4c9c-4ef5-8e83-70897beb0ab4.png)
![image](https://user-images.githubusercontent.com/118734217/229535443-09882080-5583-4ef7-8725-6caaf448c5fe.png)

### Additional context

We disabled all plugins and unnecessary third party libraries.
I was also trying the solution from this issue:
https://github.com/unjs/destr/issues/9
I passed a parseResponse option to useFetch but it didn't change anything.

_No response_

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

You don't need to share exactly your code, but sharing the _kind_ of code you are running is a helpful start.

**Comment by burda-osowiecki** [comment]
Looks like the problem causes appConfig.
I moved the appConfig (which is constant object in our case) to key in runtimeConfig, then created a composable to return this object from runtimeConfig and replaced all usage of `useAppConfig`.
Thats the results. It also effects the CPU usage.
**I'll try to create reproduction.**
![image](https://user-images.githubusercontent.com/118734217/231611160-0b70879e-0df1-434d-83dc-75b94f73bec2.png)
![image](https://user-images.githubusercontent.com/118734217/231611182-05b41413-7149-441c-a15d-883b3af399ac.png)

**Comment by burda-osowiecki** [comment]
@danielroe finally I prepared the reproduction.
https://github.com/burda-osowiecki/nuxt-memory-leak

`npm run build`
`npm run start:debug`
`gtimeout 10 siege -c 10 http://localhost:3000`

**Comment by burda-osowiecki** [comment]
@danielroe 
App with reproduction - It resolves the problem
Our production app - It still leaks, so there's something else :(

I'll try to create one more reproduction :/

**Comment by hoersamu** [comment]
We have the exact same issue. I'll try the useAppConfig workaround but it's causing a massive headache for us too.

**Comment by burda-osowiecki** [comment]
@danielroe I'm trying to update Nuxt to 3.4.2 to check the leaks on latest version but I encountered new bug.
Luckily I made a reproduction https://github.com/nuxt/nuxt/issues/20473

**Comment by burda-osowiecki** [comment]
@danielroe I've great news.
Looks like https://github.com/nuxt/nuxt/pull/20510 also resolves problem with memory leaks!
(Tested on Nuxt 3.4.2, updated others dependecies like pinia to the latest and applied fix with `callAsync`)

https://github.com/nuxt/nuxt/pull/20340 is not necessary.

Please keep the thread open until we test it on production after uprading to 3.4.3 :)
Release of 3.4.3 is planned for Friday 28.04 right?

**Comment by burda-osowiecki** [comment]
The problem is gone on 3.4.3!

Now the only one we have is: https://github.com/nuxt/nuxt/issues/20683
