### ISSUE TITLE
@nuxt/kit playground crashes my browser when I open my console - firefox

### ISSUE THREAD

**Issue by VividLemon** [nuxt/nuxt#20057]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v19.4.0`
- Nuxt Version:     `3.3.2`
- Nitro Version:    `2.3.2`
- Package Manager:  `pnpm@8.1.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Cannot -- make a @nuxt/kit module using the command

### Describe the bug

Build the module, and dev the module, open the playground, then open the console on firefox. It completely freezes the page. You are not able to close the console either.

### Additional context

I tested with and without extensions enabled. Both crash

### Logs

```shell-script
No logs, only crash
```

**Comment by danielroe** [comment]
I can't replicate this. Steps:

```
bunx nuxi init testm -t module
cd testm
pnpm i && pnpm dev:prepare
pnpm build
pnpm dev
// open localhost:3000 and open console
```

Maybe check your service workers? Or perhaps you could provide more information or a minimal reproduction? 🙏

**Comment by VividLemon** [comment]
I apologize. This hasn't been on my mind in awhile @danielroe . I struggled to get a good reproduction. However i do have the issue occurring on https://github.com/bootstrap-vue/bootstrap-vue-next . it happens in the nuxt module playground. And I think the newly made nuxt docs. I'm sorry, but I couldn't manage to replicate it in a new application. Perhaps it is an issue with nuxt+pnpm workspaces + turbo?

**Comment by danielroe** [comment]
I don't experience this. I cloned repo, ran:

```
cd bootstrap-vue-next
pnpm i
pnpm build
pnpm dev
# opened http://localhost:3000 in firefox
```

![CleanShot 2023-04-15 at 11 47 17](https://user-images.githubusercontent.com/28706372/232209385-cb8e0867-46cd-4d84-915e-7b9533b1ff4f.gif)

Would you check your service workers? It seems most likely, particularly given that you are having it on two unrelated sites. And I would also investigate the hydration issue, but don't think it would cause the issue you're encountering.

**Comment by VividLemon** [comment]
Given that you have no issue, it most likely is a service worker. I'll check soon

**Comment by VividLemon** [comment]
https://user-images.githubusercontent.com/31498096/232235327-2ce671f0-6b93-4825-ac0d-0c9e47177482.mp4

Doesn't seem that any service workers are registered. I'm getting much different results than you are

**Comment by VividLemon** [comment]
Strangest thing occurred today. I distro hopped, reinstalled everything, and then tried running this on a completely different operating system, and the issue persists. Very strange

**Comment by danielroe** [comment]
Would you try running in an incognito window, or in a fresh Firefox profile?

**Comment by VividLemon** [comment]
In the video, one of the splits are incognito with extensions off

**Comment by VividLemon** [comment]
@danielroe Thank you for your further look at this issue. 

Normally, I use my Linux machine to view the Nuxt stuff for BVN. However, today, I am using a Windows machine, with no extensions or anything. Simply a blank copy of Firefox, and the issue still exists. I'm surprised you weren't able to see the issue on your end. However, chromium works just fine with no issues. That's how I've been developing the docs in the meantime while we get to the bottom of this issue.

**Comment by prashantpalikhe** [comment]
@VividLemon Can you try opening the console already, undock it. And then go to your Nuxt url and see if you can see more on what is happening?

**Comment by VividLemon** [comment]
> @VividLemon Can you try opening the console already, undock it. And then go to your Nuxt url and see if you can see more on what is happening?

In this situation, the console works as expected, but the app starts freezing up.

**Comment by danielroe** [comment]
Is this still occurring for you? 🙏

**Comment by VividLemon** [comment]
> Is this still occurring for you? 🙏

I apologize for never responding to this. I get a lot of emails from github, so eventually one is bound to slip through. 

I recall testing this like a few weeks ago and it wasn't changed. However, I tried again today when I was testing a bug and it seems to be working correctly now.
