### ISSUE TITLE
`.client.vue` scoped styles are missing on ssr

### ISSUE THREAD

**Issue by warflash** [nuxt/nuxt#20061]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.3.3`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `experimental`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-a1d8zg?file=pages%2Findex.vue

### Describe the bug

Similar to what https://github.com/nuxt/framework/pull/8713 resolved a while back but it seems like the issue persists for `.client.vue` files?

Setting `experimental: {
    treeshakeClientOnly: false,
  },` which was the workaround for the mentioned pr does however not fix the issue

### Additional context

`.client` component on ssr:
![image](https://user-images.githubusercontent.com/22006082/229625912-0de313f2-6760-4424-9929-65baf3a36564.png)

`.client` component on client side navigation
![image](https://user-images.githubusercontent.com/22006082/229626042-cb014c1d-f567-4e9c-9f55-383bf2b2e25e.png)

The `<client-only>` wrapped component on the other hand works for both ssr and csr: 
![image](https://user-images.githubusercontent.com/22006082/229626216-dfd0351b-dfca-4aea-a406-c19f2cacf1fb.png)

**Comment by manniL** [comment]
Possibly Related (?): https://github.com/nuxt/nuxt/issues/18521, https://github.com/nuxt/nuxt/issues/15227

**Comment by huang-julien** [comment]
Indeed a bug, the root node of the `.client` component doesn't receive the scopeId. I'll take a look later. It's probably the same issue as https://github.com/nuxt/nuxt/issues/18521 but https://github.com/nuxt/nuxt/issues/15227 has been fixed with https://github.com/nuxt/framework/pull/8713
