### ISSUE TITLE
<NuxtPage> info message does not take custom pages dir into account

### ISSUE THREAD

**Issue by ItzExotical** [nuxt/nuxt#20064]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v19.8.1`
- Nuxt Version:     `3.3.3`
- Nitro Version:    `2.3.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`, `dir`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.6.5`, `nuxt-icon@0.3.3`
- Build Modules:    `-`

### Reproduction

Add something like this to `app.vue`.
```html
<template>
  <NuxtLayout>
    <NuxtPage/>
  </NuxtLayout>
</template>
```
Change the pages directory to something else in `nuxt.config.ts`.
```ts
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
    dir: {
        pages: "routes"
    }
});
```
Make sure to not have anything in the pages directory.

### Describe the bug

Nuxt throws info message `Create a Vue component in the pages/ directory to enable <NuxtPage>` instead of `Create a Vue component in the (pages dir)/ directory to enable <NuxtPage>`.

### Additional context

Literally no one cares, but I get annoyed by anything.

**Comment by postrenan** [comment]
this problem is happening to me

**Comment by TeodorDre** [comment]
same
