### ISSUE TITLE
Enable Content-Encoding:gzip for api request

### ISSUE THREAD

**Issue by SamWeichangyue** [nuxt/nuxt#20066]
### Environment

"nuxt": "3.2.0"

### Reproduction

import compression from 'compression';
export default defineNitroPlugin((nitroApp) => {
  console.log('Nitro plugin', nitroApp)
  const { h3App } = nitroApp;
  h3App.use(compression());
})
check the console:
[h3] Implicit event handler conversion is deprecated. Use eventHandler() or fromNodeMiddleware() to define event handlers.

### Describe the bug

i want to gzip the api request response, the backend api and nginx already support gzip,but i check the api requset in nuxt, it's  
Content-Encoding is disabled
<img width="1795" alt="image" src="https://user-images.githubusercontent.com/30724369/229702854-62f6cd9e-9062-425a-b035-7ba96f05b204.png">

**Comment by manniL** [comment]
This should be the job of your platform or reverse proxy.

An opt-in compression (which will be likely be worse than what your NGINX/Apache/... in front of your nuxt app can offer) is WIP here https://github.com/unjs/nitro/issues/1007#issuecomment-1453362030
