### ISSUE TITLE
`useRuntimeConfig()` is not defined when called from Nuxt module hook

### ISSUE THREAD

**Issue by DrJume** [nuxt/nuxt#20074]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.20.0`
- Nuxt Version:     `3.3.3`
- Nitro Version:    `2.3.2`
- Package Manager:  `pnpm@8.1.1`
- Builder:          `vite`
- User Config:      `extends`, `typescript`, `nitro`, `runtimeConfig`, `components`, `modules`, `vite`, `app`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.6.5`, `@vueuse/nuxt@9.13.0`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-orma7o?file=composables/useApi.ts

### Describe the bug

`useRuntimeConfig()` ist not defined in a composable when called from a Nuxt module hook, e.g. for adding `prerenderRoutes` from an API.

But `useNuxt().options.runtimeConfig` (from 'nuxt/kit') is available.

Would it be possible to allow usage of composables in a local Nuxt module and giving them access to useRuntimeConfig()?

**Comment by danielroe** [comment]
Nuxt modules run in a very different context from the Nuxt app runtime, and I think allowing composables to run there would be misleading to people. This is why we have a `runtime/` folder in the module template, for example - to separate runtime (composables, components, plugins, etc.) from module.

One significant difference in this case, for example, is that auto-imports also do not work within modules. They aren't processed with vite/webpack.

**Comment by DrJume** [comment]
Thank you for your fast response! 

What is the recommended way to use `addPrerenderRoutes()` with a runtime utility function (e.g access an API to get URLs) which is also used in the app?

**Comment by danielroe** [comment]
I would either write the utility twice, or write it in an agnostic way so it can be used in both places. For example, maybe you could use a factory pattern where you pass in the key options. So you can get them (in the module) from nuxt options and (in the runtime) from `useRuntimeConfig`.

**Comment by DrJume** [comment]
Would it be possible to create a special tsconfig.json project definition inside .nuxt/ for the environment of modules/ (where no autoImports are available)?

**Comment by DrJume** [comment]
When writing an agnostic API "composable" it is not possible to access useFetch from nuxt.
`import {} from '#app"` does not work inside a module, but accessing 'nuxt/dist/app' is also prevented (missing `exports` definition).

**Comment by danielroe** [comment]
No, it is not possible to use `#app` composables outside of a Nuxt runtime context.

**Comment by DrJume** [comment]
It would be great if it was possible to use `useFetch` in an agnostic way, inside of modules and in the app runtime.

**Comment by danielroe** [comment]
You can use `$fetch`, imported from `ofetch`. But the rest of what `useFetch` does is _vue_ specific and won't work in a module.
