### ISSUE TITLE
 ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'options')  

### ISSUE THREAD

**Issue by lillybhagya** [nuxt/nuxt#20072]
### Environment

vue js project

### Reproduction

npm run dev

### Describe the bug

While migrating nuxt 2 to nuxt 3 on a vue js project getting the below error

 ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'options')  
node js : 18.x
vue : 3
nuxt: 3
webpack: 5
bootstrap: 5
I updated all the dependencies to the latest version. Also nuxt.config.ts is with new configurations. 
Using '@nuxtjs/axios' -> Is this the problem ?

**Comment by danielroe** [comment]
Yes, `@nuxtjs/axios` is not compatible with Nuxt 3.

**Comment by lillybhagya** [comment]
Thank you. Let me try

**Comment by Foddie2** [comment]
This still throws the same error even after removing `@nuxtjs/axios`. Still does not work @danielroe

**Comment by danielroe** [comment]
@Foddie2 I am happy to take a look if you open an issue with a minimal reproduction.
