### ISSUE TITLE
How to Fix this problem when I run it after nuxt build

### ISSUE THREAD

**Issue by OnePsycho** [nuxt/nuxt#20071]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@8.2.0`
- Builder:          `vite`
- User Config:      `ssr`, `css`, `app`, `plugins`, `nitro`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                                                                                           16:12:51  

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Reproduction

![L328O}2DGU _ZLTR5M%69IN](https://user-images.githubusercontent.com/43296632/229730287-3779fd97-a4c7-4032-97c9-89bb4ef8efd0.jpg)

### Describe the bug

You can see the picture

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by xjccc** [comment]
@OnePsycho maybe you can try this in your nuxt.config
`
vite:{
  build: {
     target: 'es2015'
  }
}
`

**Comment by OnePsycho** [comment]
> @OnePsycho maybe some new syntax is not support in some browsers you can try this in your nuxt.config `vite:{ build: { target: 'es2015' } }`

非常感谢大佬！！！ 解决了！
