### ISSUE TITLE
HMR, CSS Module works not as expected after editing SCSS mixin in assets dir.

### ISSUE THREAD

**Issue by rvfakie** [nuxt/nuxt#20076]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.17.1`
- Nuxt Version:     `3.3.3`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `css`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

[Codesandbox](https://codesandbox.io/p/github/nuxt/starter/csb-wu8l7v/draft/snowy-wind?file=%2Fassets%2Fscss%2F_buttons.scss&selection=%5B%7B%22endColumn%22%3A2%2C%22endLineNumber%22%3A7%2C%22startColumn%22%3A2%2C%22startLineNumber%22%3A7%7D%5D)

### Describe the bug

Please see reproduction.
Seems like a bug with HMR. Nuxt CSS Modules and SCSS mixins imported with vite. 

After updating imported scss mixin in `_buttons.scss` styles for `<button>` just disappear.
Try to edit `_buttons.scss` style properties and you will see default button styles after HMR.

But if you modify `app.vue` after modifying `_buttons.scss` you will see HMR working correct.

### Additional context

After some research in my local project I've found that after editing scss mixin style HMR changes selector but CSS module doesn't.

Screenshots after editing mixin (you can see difference in selectors)

![style](https://gcdnb.pbrd.co/images/V9Ua7meknbQz.png)
![html](https://gcdnb.pbrd.co/images/pMgDaoyYIba2.png)

**Comment by danielroe** [comment]
Would you see if you can reproduce with https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter/tree/main ? 🙏

**Comment by rvfakie** [comment]
Sure, https://github.com/vitejs/vite/issues/12753

**Comment by danielroe** [comment]
thank you ❤️ 

closing here to track upstream 🙏
