### ISSUE TITLE
Script unnecessarily executed on redirect

### ISSUE THREAD

**Issue by igayamaguchi** [nuxt/nuxt#20080]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.3.3`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-7moc1e

```
$ npm i
$ npm run dev
```

### Describe the bug

I'm not sure if it's a bug or a specification, so I will report it as a bug for now.

Page script is executed twice when redirecting.
For example, let's say you have a simple page component like below.
A component that just outputs a console when created and onserver.

```vue
<script setup lang="ts">
console.log('created');

onServerPrefetch(() => {
  console.log('onServerPrefetch');
});
</script>

<template>
  <div>
    <h1>index</h1>
  </div>
</template>
```

Next, the middleware that redirects when there is a `redirect=1` in url query.

```ts
export default defineNuxtRouteMiddleware(async (to, from) => {
  if (to.query.redirect) {
    console.log('redirect');
    return navigateTo({ ...to, query: { ...to.query, redirect: undefined } });
  }
});
```

At this time, if I access `/?redirect=1`, Page script will be executed twice as below.

in console

```
redirect
created
onServerPrefetch
created
onServerPrefetch
```

I think it is desirable not to execute the script of the page that before being redirected when redirecting.
What do you think?

**Comment by pranjal6314** [comment]
hello, I tried to solve this issue could you please check this
// Middleware
export default function ({ route, redirect }) {
  // If the redirect query parameter is present
  if (route.query.redirect) {
    // Wait for the page to be created
    this.app.router.onReady(() => {
      // Call the onServerPrefetch hook
      this.$options.fetch.call(this, this.$options.context).then(() => {
        // Redirect to the new page
        redirect(route.path)
      })
    })
  }
}
we wait for the router.onReady event to fire, indicating that the page has been created. 
Then, we call the fetch method and also trigger the onServerPrefetch hook. Once the fetch method has been completed, we can safely redirect to the new page.

**Comment by igayamaguchi** [comment]
Is it Nuxt2?
Can Nuxt3 do the same?
