### ISSUE TITLE
Nuxt page error 404

### ISSUE THREAD

**Issue by nasirDoe** [nuxt/nuxt#20094]
### Environment

OSX - 13 Ventura
Node - 19.6.0
Nuxt - 3.3.3
Browser - Brave

### Reproduction

-

### Describe the bug

Yesterday i ran project is ok. but today i run dev this bugs is appear
![Screenshot 2023-04-05 at 10 54 48](https://user-images.githubusercontent.com/16643567/229977198-e691e529-b165-4ab2-926f-5996550a6699.png)
<img width="330" alt="Screenshot 2023-04-05 at 10 56 03" src="https://user-images.githubusercontent.com/16643567/229977316-7c16e717-6cf1-457d-96f5-baa819c396d2.png">

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by danielroe** [comment]
No, you do not need to set a name - it will be done automatically by Nuxt based on the file name. Of course, you are free to do so.

**Comment by danny007in** [comment]
> I had solved the issue, i set `name` value is duplicate with another page.
> 
> is it required when component is page ?:
> 
> `definePageMeta({ name: 'FeaturesPage', })`

@danielroe It would be very useful if its show actual error or warning rather than 404 page not found.
