### ISSUE TITLE
addComponent not working properly

### ISSUE THREAD

**Issue by rafifn** [nuxt/nuxt#20095]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.3.2`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `imports`, `modules`
- Runtime Modules:  `l-min@1.0.10`
- Build Modules:    `-`

### Reproduction

- [nuxt app](https://github.com/rafifn/nuxt-extends-parent)
- [repo module](https://github.com/rafifn/l-min)
- [stackblitz](https://stackblitz.com/edit/nuxt-starter-9tykra?file=app.vue)

### Describe the bug

I have a module and nuxt app
my module contains a component that uses the component library (element-plus).
when I use the module in the playground, the module runs fine and my component can be used. but when I use the module in another repo, my component can't be displayed.
is there something wrong with my implementation?

**Comment by danielroe** [comment]
In this case, `dayjs` is a problematic dependency of `element-plus`, which vite is having trouble with. You can manually add the deps to `vite.optimizeDeps.include` to handle it.

```js
// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  modules: ['l-min'],
  vite: {
    optimizeDeps: {
      include: ['element-plus', 'element-plus > dayjs', 'element-plus > dayjs/plugin/customParseFormat.js', 'element-plus > dayjs/plugin/localeData.js', 'dayjs/plugin/isSameOrAfter.js', 'dayjs/plugin/isSameOrBefore.js']
    }
  }
})
```

You can also do this in your module:

```ts
nuxt.options.vite.optimizeDeps.include.push(/* */)
```
