### ISSUE TITLE
Missing `<link>` tags in production build

### ISSUE THREAD

**Issue by WolfgangDrescher** [nuxt/nuxt#20091]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.3.3`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@9.5.1`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `app`, `ssr`, `srcDir`, `modules`, `vite`, `nitro`, `googleFonts`, `i18n`, `content`, `plausible`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.6.5`, `@pinia/nuxt@0.4.7`, `@nuxtjs/google-fonts@3.0.0`, `nuxt-icon@0.3.3`, `@nuxtjs/i18n-edge@8.0.0-beta.10-28003311.2c39470`, `@nuxt/content@2.5.2`, `@nuxtjs/plausible@0.2.0`
- Build Modules:    `-`

### Reproduction

I was not able to create a minimal reproduction for this issue as this bug does not seem to occur in a minimal example. So here is how you can reproduce it:

```sh
git clone --recurse-submodules https://github.com/WolfgangDrescher/lassus-tricinium-project.git demo
cd demo
git checkout bb55ac1
npm install
npx nuxi upgrade --force # currently it will upgrade to nuxt v3.3.3
npm run build
node .output/server/index.mjs
```

Compare this to the working example with nuxt v3.3.1:

```sh
git clone --recurse-submodules https://github.com/WolfgangDrescher/lassus-tricinium-project.git demo
cd demo
git checkout bb55ac1
npm install
npm run build
node .output/server/index.mjs
```

### Describe the bug

CSS and JS files are missing the the `<head>` when building my project with `npm run build`. In development mode everything works as expected. When I lock nuxt to `v3.3.1` it also works as expected but using `v3.3.2` or above the build will not have css styles for example (some global styles that are not `scoped` are displayed though). This is why I think it must be a bug related to nuxt but I'm unsure. Debugging this for quite a while it could also be related to Vite or `@nuxtjs/tailwindcss`.

First I thought that https://github.com/nuxt-modules/tailwindcss/issues/628 might be the problem but this does not seem to be the case.

Maybe `vite` was updated in nuxt `v3.3.2` so the production build is bundled different?

### Additional context

Nuxt v3.3.1:

<img width="1104" alt="Bildschirm­foto 2023-04-04 um 18 02 33" src="https://user-images.githubusercontent.com/865594/229855320-94c7abbf-179d-4344-8a50-148a099babec.png">

Nuxt v3.3.3:

<img width="1103" alt="Bildschirm­foto 2023-04-04 um 18 05 02" src="https://user-images.githubusercontent.com/865594/229855428-1ca85c5b-fc40-4662-84ca-f094a00dae31.png">

### Logs

The only error message I get is this `importScripts is not defined` related to a web worker. I don't think this can be the problem. Maybe if the Vite build somehow fails after this. But no errors in the console when while building. And still nuxt `v3.3.1` works just fine.

```shell-script
verovio-85527134.js:1 Uncaught ReferenceError: importScripts is not defined at verovio-85527134.js:1:1
```

**Comment by danielroe** [comment]
Would you try pinning to `vue-bundle-renderer@1.0.2` and let me know if this behaviour changes?

**Comment by WolfgangDrescher** [comment]
I switched to yarn and pinned `vue-bundle-renderer@1.0.2` with the `resolutions` property in `package.json` but still the same result as explained in my initial post.

```json
{
  "resolutions": {
    "vue-bundle-renderer": "1.0.2"
  }
}
```

**Comment by danielroe** [comment]
Thank you for testing; that rules out the recent changes to `vue-bundle-renderer`.

Would you be able to try to reduce a project with this issue down to the minimum required to reproduce it (realising that this might still be a large project)? That would be very much appreciated.

**Comment by WolfgangDrescher** [comment]
Yes. sorry that I had to post the link to my project directly. The setup is a bit complex with submodules, `nitro.publicAssets` and `@nuxt/content` and `srcDir`. But eliminating all of these things out one by one I was not able to reproduce it with a minimal example.

Don't forget to pin nuxt to v3.3.2 or above if you want to reproduce it in my project.

**Comment by danielroe** [comment]
I believe the issue here is an upstream one from vite related to web workers, maybe linked to https://github.com/vitejs/vite/issues/12611.

When I pin `vite` to `4.1.4` no issue occurs.

On the other hand, I believe the issue has be fixed in vite `4.3.0` as when I try with the current 4.3 beta version, all seems well.

**Comment by WolfgangDrescher** [comment]
Ah, makes sense as I did not include the complicated setup with the verovio web worker when I tried to create a minimal reproduction repo. So the error message with `importScripts` was not quite unimportant.

`vite` to `4.1.4` did not work for me, but I can confirm that `4.3.0-beta.2` does fix it for me.

For now I pinned vite. But to resolve this properly I have to wait for the next nuxt release that bumps vite to `4.3.0` in `@nuxt/vite-builder`, correct?

**Comment by WolfgangDrescher** [comment]
`vite@4.3.0` is released now: https://github.com/vitejs/vite/releases/tag/v4.3.0. I briefly checked the semver commit messages since `4.3.0-beta.0` and it doesn't look like there are breaking changes.

I would create a PR but I'm not aware of all the places where I need to bump the version number. I found `package.json` (`pnpm.overrides.vite`), `packages/vite/pacakage.json` (`dependencies.vite`) and the lock file. I'd be happy to contribute when someone can guide me how to handle the workspaces and lock file.
