### ISSUE TITLE
onResponseError({ request, options, response }) is not triggered even when the api calls returns error

### ISSUE THREAD

**Issue by gitamgadtaula** [nuxt/nuxt#20090]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.17.1`
- Nuxt Version:     `3.3.3`
- Nitro Version:    `2.3.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `app`, `imports`, `css`, `modules`, `pinia`, `vite`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.6.5`, `@formkit/nuxt@0.16.4`, `@pinia/nuxt@0.4.7`, `@vueuse/nuxt@9.13.0`
- Build Modules:    `-`

### Reproduction

```vue
<template>
  <div>
    <NuxtWelcome />
  </div>
</template>
<script setup>
onMounted(() => {
  await useFetch('https://beta.glrtec.com/api/v1/me', {
    onResponse({ request, response, options }) {
      console.log('im success but still i also error');
      // even the error response is triggered inside here
    },
    onResponseError({ request, response, options }) {
      console.log('im error');
      // error is not triggered
    },
  });
});

</script>
```

### Describe the bug

While using the nuxt useFetch composable, I can't seem to catch the error with onResponseError({ request, options, response }). Even the 400/401 status with status.ok is caught inside onResponse({request,options,response}).

**Comment by danielroe** [comment]
I can't reproduce this - it does correctly log `im error`. Note that you also should not use `useFetch` in a lifecycle hook like mounted, but instead can directly use `$fetch`.

Maybe try updating your lockfile to ensure you're using the latest version of `ofetch`?

If that doesn't work, please do update this with a new reproduction and I'll happily reopen.

**Comment by wjbarber3** [comment]
I'm experiencing this exact same scenario. Any error (404 in my case) is being handled in the `onResponse` interceptor rather than the `onResponseError` interceptor.

If I remove `onResponse` - the error gets handled properly in the `onResponseError` interceptor

**Comment by danielroe** [comment]
Would you see if you can reproduce this in ofetch directly, and if so, raise [there](https://github.com/unjs/ofetch/issues/new)? 🙏
