### ISSUE TITLE
When I load the plugin using addPlugin in @nuxt/kit, the load sort doesn't work

### ISSUE THREAD

**Issue by nfjBill** [nuxt/nuxt#20106]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `pnpm@7.29.1`
- Builder:          `vite`
- User Config:      `appConfig`, `runtimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

none

### Describe the bug

```
addPlugin(resolver.resolve('./runtime/0.plugin'))
addPlugin(resolver.resolve('./runtime/1.plugin'))
addPlugin(resolver.resolve('./runtime/2.plugin'))
addPlugin(resolver.resolve('./runtime/3.plugin'))
```

When I was developing the nuxt module, I found that plugin load sort did not work, the current order is 3,2,1,0

**Comment by danielroe** [comment]
Yes, sorting only applies to automatically scanned plugins from a user's plugin directory.

**Comment by nfjBill** [comment]
I see. Thank you very much
