### ISSUE TITLE
Inline styles not added for some pages

### ISSUE THREAD

**Issue by oleghalin** [nuxt/nuxt#20104]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.19.1`
- Nuxt Version:     `3.3.2`
- Nitro Version:    `2.3.2`
- Package Manager:  `pnpm@8.0.0`
- Builder:          `vite`
- User Config:      `components`, `extends`, `alias`, `modules`, `css`, `postcss`, `runtimeConfig`, `i18n`, `vite`
- Runtime Modules:  `@nuxt/devtools@0.3.1`, `@pinia/nuxt@^0.4.0`, `@nuxtjs/i18n@8.0.0-beta.10`, `@vueuse/nuxt@9.13.0`, `@vue-macros/nuxt@1.2.7`
- Build Modules:    `-`
------------------------------

### Reproduction

Cannot create correct repro, because i have 3 projects, 2 of them doesnt have inlined styles for any page. 

### Describe the bug

<style> tag wasnt added to SSR output. Maybe here is any conditions or?

**Comment by danielroe** [comment]
Nevertheless, we still need a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction) to investigate... 🙏

**Comment by danielroe** [comment]
Based on what you've said, it might possibly be a vite upgrade?

From the Nuxt end, `experimental.inlineSSRStyles` needs to be enabled - which is enabled by default in production, as long as `ssr` is not false, and `builder` is not webpack.

https://github.com/nuxt/nuxt/blob/f40b3e249294123a9954dad74d23a70a6b279497/packages/schema/src/config/experimental.ts#L102-L110

**Comment by oleghalin** [comment]
Found problem, it relates to vue-macros module. 

https://github.com/sxzz/unplugin-vue-macros/issues/337

**Comment by Laruxo** [comment]
I found that in my case the styles were not inlined for components not yet migrated to Vue 3 (we are in progress of migrating a big Nuxt 2 project that was using `vue-class-component` lib). After rewriting the component using `<script setup>` the styles appeared in the HTML.

However, I found an interesting case that confused me for a bit. Even if styles are inlined (visible in HTML head), the CSS file is still being requested. I can also see the CSS file in the client manifest, so it might be related to how the CSS is removed.
<img width="481" alt="image" src="https://user-images.githubusercontent.com/6096645/234693875-5db9794a-02c8-4901-b6a8-01ad1f5b6a49.png">
<img width="481" alt="image" src="https://user-images.githubusercontent.com/6096645/234709916-6bcaeda7-65f6-4921-99b4-02a02da12811.png">

Here is a minimal reproduction (please run `npm run build` and then `node .output/server/index.mjs`).
https://stackblitz.com/edit/nuxt-inline-styles-issue?file=my-button.vue
