### ISSUE TITLE
Error hooks don't catch html render error on SSR

### ISSUE THREAD

**Issue by MateiNenciu** [nuxt/nuxt#20113]
### Environment

```
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.3.3`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
```

### Reproduction

I noticed this issue only on ssr navigation, I didn't tested in depth on client navigation. Tried with both app:error and vue:error hooks.

Navigate to /script-error and check the console, app:error and vue:error hooks are firing.
Navigate to /html-error and see neither of the hooks firing.

Code: https://stackblitz.com/edit/github-wq5s8k

### Describe the bug

 While writing a custom error reporter I noticed that I could not catch when the SSR fails to render a route because of the template parsing (in my case a bad v-if). I expected at least app:error hook to fire in this situation.

**Comment by szwenni** [comment]
Hi
I encoutered the same. It seem like the error is only handled in the nitro environment.

I tried to find some way to implement sentry for nuxt 3 as the official plugin still not supports nuxt 3.

My way of doing it right now is to overwrite the `nitroApp.h3App.options.onError` handler in a nitro plugin with a function reporting the errors to sentry and then calling the original function. 
Secondly in a nuxt plugin I'm passing the currentRoute value into the h3 event (I wanted to have all the params in sentry)
I know this is not the cleanest approach but at least it works.

I also tried an approach like
- Pass an callback into the h3Event in a nuxt plugin. The callback basically is calling a nuxt hook called 'nitro:error' (non standard)
- somewhere else hook the 'nitro:error' event and use all the information availabe through current nuxt context
The outcome is the same but for me the nitro plugin made somehow more sense as Sentry for SSR only lives in nitro context then

I would love to have a way to catch all these errors already on the server side as if the error gets passed to the client side the stack is removed which is not really helpful for error tracing then.

**Comment by danielroe** [comment]
These two error hooks only run _within_ the Vue environment. If there is an error that crashes Vue entirely, these hooks won't run. I think your approach of using `onError` + a Nitro plugin to handle errors in this case is the right one.

Is there anything you're missing with this approach?

**Comment by pi0** [comment]
Upstream tracker discussion: https://github.com/unjs/nitro/issues/1152

**Comment by danielroe** [comment]
Let's track there ❤️

**Comment by MateiNenciu** [comment]
Ok I understand now but in my example the script crash shouldn't behave the same, crashing the Vue instance? Why it behaves differently?

**Comment by szwenni** [comment]
@danielroe I did not take a deep look till now how things are passed between nitro and nuxt but is there a more reasonable way to pass the current route into the error handler of nitro ? I have the feeling that my approach is not quite the best one by putting the route instance into the h3 event ? I saw that the error handler set in nitro is also not the default nitro error handler but some made by nuxt. Maybe there is a smarter way to have all the required information available in nitro context or even call some "default" hook in nuxt again.

**Comment by MateiNenciu** [comment]
Awesome!
