### ISSUE TITLE
How to read environment variables on the JS file?

### ISSUE THREAD

**Issue by zhizaiyunxiao** [nuxt/nuxt#20118]
### Environment

How to read environment variables on the JS file?

### Reproduction

How to read environment variables on the JS file?

### Describe the bug

There is no problem on the Vue page, but an error was reported on the JS file.How to read environment variables on the JS file?
![image](https://user-images.githubusercontent.com/22257246/230527682-2e793177-0834-4509-a321-e4840f07a406.png)

![image](https://user-images.githubusercontent.com/22257246/230527603-e7acc9ce-4473-4dcf-aad7-f56b16431058.png)

**Comment by danielroe** [comment]
You can read a bit more about this here: https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables
