### ISSUE TITLE
css background-image: url(/img/news_banner.png) ，  extractCSS not same

### ISSUE THREAD

**Issue by LanjianNUll** [nuxt/nuxt#20120]
### Environment

 app: {
    buildAssetsDir: './',
    baseURL: "/oort/oort-site/",
    cdnURL: '/oort/oort-site/'
}

this is config

### Reproduction

![image](https://user-images.githubusercontent.com/15379422/230565139-761a36b4-43c3-4929-8a73-a1948accc4e0.png)

### Describe the bug

 the extracted css styles are inconsistent

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by LanjianNUll** [comment]
> Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

yes 
https://stackblitz.com/edit/github-fjtufx?file=src/pages/index.vue

reproduction steps: 
1, yarn build
2, yan start 

and 
![image](https://user-images.githubusercontent.com/15379422/230582459-be9a44be-716f-45f9-aee6-508078ca7d26.png)

**Comment by danielroe** [comment]
This is no longer reproducible. 🙌  Let me know if you still experience it, with a reproduction, and I'll happily reopen.
