### ISSUE TITLE
Reactivity / hydratation issue on render with reactive object

### ISSUE THREAD

**Issue by benjaminrobinet** [nuxt/nuxt#20130]
### Environment

```
Nuxi 3.3.3

RootDir: /project/home/benjaminrobinet/workspace
Nuxt project info:

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.3.3`
- Nitro Version:    `2.3.2`
- Package Manager:  `pnpm@7.1.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

### Reproduction

https://codesandbox.io/p/sandbox/reactivity-issue-dlxt09

The page `index.vue` is mutating the reactive object, and the component `StateComponent.vue` is displaying the value and using it to apply a CSS class using a computed.

### Describe the bug

Here we have a useState method that is mutated to another value on the setup of a page. The template reacts well when using `{{ stateValue }}`, but not in computed, template binding, etc...

I added a button to mutate the state on a nextTick, and it works as expected. That's probably not a useState issue, as I have the same issue with Pinia.

EDIT: On HMR, it works fine.

The expected behavior is that everything should be correctly reactive to that reactive object.

**Comment by henriheymans** [comment]
Same here 👋

**Comment by danielroe** [comment]
The issue here is that on the server, order matters. Components are rendered from the top down, and there is no reactivity. In this case you are setting the data in your page, but by this point it's too late. The component above it has already rendered. So on the client side we have a mismatch, because the data is present _now_ for the header.

**Comment by benjaminrobinet** [comment]
@danielroe I see, any workaround for that ? In my specific case, I can just use `definePageMeta`, but no other way to have it reactive than duplicating it for client only ?

**Comment by danielroe** [comment]
It's definitely reactive on client-side - it's just that on the server you need to have it set to the correct value before the first component depending on it is rendered. So setting it in a plugin or middleware would likely be your best option.

**Comment by benjaminrobinet** [comment]
@danielroe oh yes make sense... sorry ! thanks for your time then!
