### ISSUE TITLE
If the parent project directory contains Chinese generate an error

### ISSUE THREAD

**Issue by wsm661** [nuxt/nuxt#20139]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.20.0`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `pnpm@8.1.1`
- Builder:          `vite`
- User Config:      `buildDir`, `modules`, `build`, `runtimeConfig`, `app`, `css`, `nitro`, `webpack`, `experimental`, `vite`, `hooks`
- Runtime Modules:  `@pinia/nuxt@0.4.7`, `@vueuse/nuxt@9.13.0`, `nuxt-windicss@2.6.0`, `@nuxt/content@2.5.2`, `@pinia-plugin-persistedstate/nuxt@1.1.1`, `nuxt-swiper@1.0.1`
- Build Modules:    `-`

### Reproduction

The project's parent directory contains Chinese

### Describe the bug

In actual testing, if the parent directory of the project contains Chinese, when generate is packaged, it will prompt that the vue file cannot be found, and the error message is shown in the screenshot
![3d68795313ab90e6b0f1c062d2f256d4](https://user-images.githubusercontent.com/20593648/230702646-2dedcaa7-0a16-46f3-a824-d2b97c7e4e34.JPG)

**Comment by manniL** [comment]
Can't repro this ☺️

[StackBlitz](https://stackblitz.com/edit/nuxt-issues-20139?file=some-chinese-%E5%90%B4%E6%80%9D%E6%A2%A6%2FREADME.md)

Feel free to provide a running reproduction showing the error and ping me if it still occurs in your case 👍🏻
