### ISSUE TITLE
`useFetch` API doesn't do anything in `onMounted`

### ISSUE THREAD

**Issue by gyhyfj** [nuxt/nuxt#20142]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.3.3`
- Nitro Version:    `2.3.2`
- Package Manager:  `pnpm@8.1.0`
- Builder:          `vite`
- User Config:      `modules`, `vite`, `css`, `imports`, `pinia`, `appConfig`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.6.5`, `@pinia/nuxt@0.4.7`, `@pinia-plugin-persistedstate/nuxt@1.1.1`, `@element-plus/nuxt@1.0.4`
- Build Modules:    `-`

### Reproduction

```
onMounted(()=>{
 const { data } = await useFetch('https://api.nuxtjs.dev/mountains')
})
```

### Describe the bug

`useFetch` API doesn't do anything in `onMounted` no matter if `server` is `true` or  `false`.
Is this a issue or not?  I don't find relative introduce about it in doc.

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

What do you mean it 'doesn't do anything'?

Note that you should use `$fetch` and not `useFetch` if you want to perform a fetch programmatically. `useFetch` is a Vue composable that is meant to be called in a setup function.

**Comment by gyhyfj** [comment]
Sorry , I cannot reproduct this problem again,  I'll give reproduct later if possible.
But I really found some issues which's so strange that I have to repuduct them through many experiment.
This one have already been reproducted:  https://github.com/nuxt/nuxt/issues/20043

**Comment by mrFANRA** [comment]
> Sorry , I cannot reproduct this problem again, I'll give reproduction later if possible. But I really found some issues which's so strange that I have to repuduct them through many experiments. This one have already been reproducted: #20043

Hi! Did you find solution? Some trouble =(

**Comment by hasnaindev** [comment]
> > Sorry , I cannot reproduct this problem again, I'll give reproduction later if possible. But I really found some issues which's so strange that I have to repuduct them through many experiments. This one have already been reproducted: #20043
> 
> Hi! Did you find solution? Some trouble =(

I don't think so, something about being bound to an instance. Use `$fetch` instead as stated in the reproduced issue. For me, the main headache is that when one `useFetch` relies on another `useFetch`. Both in `setup` with await. I created a singular API. `useFetch` is super nice when you have a simple call at the start but when things get a little "programatically", I've often found `$fetch` to be super reliable.
