### ISSUE TITLE
Modules in nuxt.config.ts... TS2589: Type instantiation is excessively deep and possibly infinite

### ISSUE THREAD

**Issue by devilmark84** [nuxt/nuxt#20159]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.14.2`
- Nuxt Version:     `3.3.3`
- Nitro Version:    `2.3.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `css`, `build`, `modules`, `vite`
- Runtime Modules:  `@nuxtjs/google-fonts@3.0.0`, `@sidebase/nuxt-auth@0.4.4`
- Build Modules:    `-`

### Reproduction

In my `nuxt.config.ts I'm using this:
```js
...
  modules: [
    [
      "@nuxtjs/google-fonts",
      {
        families: {
          Inter: [500, 700],
        },
        prefetch: true,
        preconnect: true,
        preload: true,
      },
    ],
    "@sidebase/nuxt-auth",
  ],
...
```

### Describe the bug

Until nuxt 3.2.2 no error was appearing in VS Code.
Starting from 3.2.3 and in the new 3.3.3, this warning appears. It appears even if I define empty `modules` entry, so I think this is not related any specific module I'm using.
Not appearing in the 3.3.2.

Thanks in advance

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by volk234** [comment]
Remove .nuxt, node_modules directories and npm lock file. It helped me today.

**Comment by devilmark84** [comment]
> Remove .nuxt, node_modules directories and npm lock file. After that, reinstall the dependencies. It helped me today.

It works, thanks!

**Comment by devilmark84** [comment]
> Remove .nuxt, node_modules directories and npm lock file. After that, reinstall the dependencies. It helped me today.

It works, thanks!

**Comment by plexus77** [comment]
Also needed to restart my jetbrains ide to get this to work.

**Comment by alexMugen** [comment]
npx nuxi cleanup and it works
