### ISSUE TITLE
extensions won't work

### ISSUE THREAD

**Issue by taoqf** [nuxt/nuxt#20156]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `pnpm@8.1.1`
- Builder:          `vite`
- User Config:      `srcDir`, `extensions`, `typescript`, `routeRules`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

```ts
export default defineNuxtConfig({
	srcDir: 'src/',
	extensions: [".api.ts",  ".page.vue"]
});
```

### Describe the bug

The configurations in `nuxt.config.ts` won't work, all vue files are treated as page files, I want ignore .vue as page file in pages.

### Additional context

I did the same thing in next.js,

**Comment by danielroe** [comment]
Check out https://nuxt.com/docs/guide/going-further/custom-routing#using-the-pagesextend-hook.

The `extensions` configuration option is not about the pages directory and configuring it adds extensions, doesn't remove ones that already exist
