### ISSUE TITLE
useFetch return type with POST method

### ISSUE THREAD

**Issue by Elliot67** [nuxt/nuxt#20150]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.19.0`
- Nuxt Version:     `3.3.3`
- Nitro Version:    `2.3.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `ssr`, `nitro`, `runtimeConfig`, `css`, `vite`, `modules`, `sitemap`, `components`, `devServer`, `typescript`
- Runtime Modules:  `nuxt-simple-sitemap@2.4.7`, `nuxt-icons@3.1.0`, `@vueuse/nuxt@9.13.0`
- Build Modules:    `-`

### Reproduction

[Reproduction on stackblitz](https://stackblitz.com/edit/github-qdnnos?file=test.ts,app.vue)

```ts
type MyReturnType = {
  data: string;
};

const { data } = useFetch<MyReturnType>('https://example.com', {
  method: 'POST',
});
```

> Type '"POST"' is not assignable to type '"get" | "GET" | Ref<"get" | "GET" | undefined> | undefined'.(2322)

### Describe the bug

Typescript error when trying to type the returned data of a POST request.
The typing for the same code with a GET request works fine.

Also found the same question/issue [on stackoverflow](https://stackoverflow.com/questions/75509552/provide-error-response-type-to-usefetch-in-nuxt-3-for-post-method).

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/19077.
