### ISSUE TITLE
scrollBehavior is not called on initial request on history mode

### ISSUE THREAD

**Issue by patrickteivas** [nuxt/nuxt#20178]
### Environment

  System:
    OS: Linux 5.4 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
    Memory: 2.36 GB / 3.84 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.19.0 - ~/nvm/current/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.3 - ~/nvm/current/bin/npm
  npmPackages:
    nuxt: ^2.16.3 => 2.16.3

### Reproduction

I created a PR on top of `v2-codesandbox` template.

https://github.com/patrickteivas/nuxt-minimal-repro/pull/1

### Describe the bug

The initial request is not calling out the `scrollBehavior` function. It stopped working after I upgraded the Nuxt to 2.15.8 (from 2.14.7). Reproduce is done on Nuxt version 2.16.3.

In reproduction, I created an `app/router.scrollBehavior.js` file that just console logs the `scrollBehavior` string when executed.

1. Clone the repository, checkout the `add-scroll-behavior` branch, install dependencies and start the development script (`yarn dev`)
2. Go to `http://localhost:3000/` - `scrollBehavior` function is NOT called

I found out that the `handleInitialScroll` function in `vue-router` on the client side is called with a `NavigationDuplicated` error instead of the actual route (as it was in 2.14.7 I upgraded from).

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
