### ISSUE TITLE
How to turn off [Vue Router warn] in a production environment

### ISSUE THREAD

**Issue by Baiyuetribe** [nuxt/nuxt#20175]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.14.0`
- Nuxt Version:     `3.3.3`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@9.3.1`
- Builder:          `vite`
- User Config:      `app`, `build`, `modules`, `vite`, `vue`, `runtimeConfig`
- Runtime Modules:  `@pinia/nuxt@0.4.8`
- Build Modules:    `-`
------------------------------

### Reproduction

In a production environment, a large number of unrelated Vue Router warn errors are generated.
```log
[Vue Router warn]: No match found for location with path "/css/album.css"
[Vue Router warn]: No match found for location with path "/css/album.css"
[Vue Router warn]: No match found for location with path "/css/album.css"
[Vue Router warn]: No match found for location with path "/css/album.css"
[Vue Router warn]: No match found for location with path "/css/album.css"
[Vue Router warn]: No match found for location with path "/data/admin/allowurl.txt"
[Vue Router warn]: No match found for location with path "/data/admin/allowurl.txt"
[Vue Router warn]: No match found for location with path "/data/admin/allowurl.txt"
[Vue Router warn]: No match found for location with path "/data/admin/allowurl.txt"
```

### Describe the bug

As described above

### Additional context

so, How to turn off [Vue Router warn] in a production environment

**Comment by NozomuIkuta** [comment]
Would you provide a minimal reproduction using either of the following templates?

- https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz
- https://codesandbox.io/p/github/nuxt/starter/v3-codesandbox

**Comment by danielroe** [comment]
If you're getting this server-side only, you can try adding `vue-router` to the `build.transpile` array.
