### ISSUE TITLE
ERROR  Cannot restart nuxt:  this.addPlugin is not a function 

### ISSUE THREAD

**Issue by lillybhagya** [nuxt/nuxt#20173]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.3.3`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@9.5.0`
- Builder:          `vite`
- User Config:      `target`, `mode`, `build`, `buildModules`, `types`, `fetch`, `head`, `loading`, `css`, `plugins`, `fontawesome`, `modules`, `generate`, `env`, `devServerHandlers`
- Build Modules:    `@nuxt/typescript-build@3.0.1`, `@nuxtjs/fontawesome`

### Reproduction

npm run dev

### Describe the bug

While migrating nuxt 2 to nuxt 3 on a vue js project getting the below error

 **ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'addPlugin')**                                                                                                        17:31:54

  at nuxtXXXXVue (node_modules/xxxxxx/dist/nuxt/index.js:5:8)
  
  **code for nuxtXXXXVue is:** (this code is coming from some other internal package)
  
  import path from 'path';

export default function nuxtXXXXVue(options) {
  this.addPlugin({
    src: path.resolve(__dirname, 'plugin.js'),
    options,
  });
}

export const meta = require('../../package.json');
  

this in this context is undefined when i debugged. This particular package is in nuxt 2 not updated to nuxt 3.

Is there any way i can fix the current project without modifying internal package ?
  **this.addPlugin is the function needs to be replaced with nuxt 3 ?**

**Comment by danielroe** [comment]
In Nuxt 3, modules do not have a `this` instance. Instead, you can import `addPlugin` from `@nuxt/kit` and directly call it.

You can read more in https://nuxt.com/docs/guide/going-further/modules.

**Comment by lillybhagya** [comment]
Thank you @danielroe , Like this right ?

import { defineNuxtModule } from '@nuxt/kit'

export default defineNuxtModule({
  setup(options) {
    this.nuxt.hook('builder:extendPlugins', (plugins) => {
      plugins.push({
        src: path.resolve(__dirname, 'plugin.js'),
        options,
      })
    })
  },
  meta: require('../../package.json')
})

**Comment by danielroe** [comment]
```ts
import { addPlugin, createResolver, defineNuxtModule } from '@nuxt/kit'

export default defineNuxtModule({
  setup (options) {
    const resolver = createResolver(import.meta.url)
    addPlugin({
      src: resolver.resolve('./plugin.js')
    })
  }
})
```

**Comment by jhasuev** [comment]
for me it does not work.
after doing above I got another error:

`Nuxt 3.5.3 with Nitro 2.4.1                                                                                                   12:11:30

 ERROR  Nuxt instance is unavailable!                                                                                         12:11:30

  at useNuxt (node_modules/@nuxt/kit/dist/index.mjs:31:11)
  at isNuxt2 (node_modules/@nuxt/kit/dist/index.mjs:81:25)
  at nuxt2Shims (node_modules/@nuxt/kit/dist/index.mjs:2160:8)
  at Object.normalizedModule [as config] (node_modules/@nuxt/kit/dist/index.mjs:2130:5)
  at resolveConfig (node_modules/c12/dist/index.mjs:281:28)                                                                   12:11:30
  at loadConfig (node_modules/c12/dist/index.mjs:116:40)
  at async loadNuxtConfig (node_modules/@nuxt/kit/dist/index.mjs:2447:18)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:124:20)
  at async _main (node_modules/nuxi/dist/cli.mjs:48:20)`
