### ISSUE TITLE
`useAsyncData` different behavior when has return value on SRR 

### ISSUE THREAD

**Issue by trandaison** [nuxt/nuxt#20171]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `pnpm@7.27.1`
- Builder:          `vite`
- User Config:      `typescript`, `app`, `plugins`, `css`, `build`, `modules`, `routeRules`, `runtimeConfig`, `i18n`, `lodash`
- Runtime Modules:  `@pinia/nuxt@0.4.6`, `@nuxtjs/i18n@8.0.0-beta.7`, `nuxt-lodash@2.4.1`, `@vueuse/nuxt@9.13.0`, `()`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-wkza2g?file=pages%2Findex.vue

### Describe the bug

The setup script as below

```ts
const counter = ref(0);

const { data } = useLazyAsyncData(() => {
  counter.value = 1;
  return {};
});
```

The problem on SSR, if I remove the return statement from `useLazyAsyncData`, the `counter` value will be `1`.
If add the return value, the value of `counter` will be `0`.

On CSR, `counter.value` is always `1`.

**Comment by danielroe** [comment]
This is intended behaviour. `useAsyncData` should return a value - it's not intended for side-effects.

**Comment by trandaison** [comment]
@danielroe Yeah, it should return a value.
but the behaviour on Server side is inconsistent with Client side, has a return statement is inconsistent with no return.

**Comment by danielroe** [comment]
What do you mean by saying it is inconsistent?
