### ISSUE TITLE
[v3.4.0] Runtime Config

### ISSUE THREAD

**Issue by vinayakkulkarni** [nuxt/nuxt#20212]
RootDir: /Users/vinayak/dev/geoql/expenses                                                                                                                                                  
Nuxt project info: (copied to clipboard)

------------------------------
- Operating System: Darwin
- Node Version:     v18.15.0
- Nuxt Version:     3.4.0
- Nitro Version:    2.3.3
- Package Manager:  npm@9.6.4
- Builder:          vite
- User Config:      app, css, ssr, modules, nitro, plugins, runtimeConfig, typescript
- Runtime Modules:  @pinia/nuxt@0.4.8, @vueuse/nuxt@9.13.0, @kevinmarrec/nuxt-pwa@0.17.0, @nuxtjs/plausible@0.2.0, nuxt-windicss@2.6.0
- Build Modules:    -
------------------------------

Getting error:

`value cannot be made reactive: undefined`

<img width="703" alt="Screenshot 2023-04-11 at 11 26 44 PM" src="https://user-images.githubusercontent.com/19776877/231248369-b20cde1c-4b7d-4856-b94e-10a46a286fce.png">

Seems the culprit commit is – [`76ac463` (#20082)](https://github.com/nuxt/nuxt/pull/20082/commits/76ac4634e59298a6158b8e293162433619652038)

Repro link – https://github.com/geoql/expenses/blob/dev/nuxt.config.ts#L19

**Comment by danielroe** [comment]
This should be resolved in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/) with https://github.com/nuxt/nuxt/pull/20216, or in the next release.

Let me know if not and I'll reopen.
