### ISSUE TITLE
useState broken in Nuxt 3.4.0

### ISSUE THREAD

**Issue by mcrapts** [nuxt/nuxt#20211]
### Environment

```
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.0
- Nitro Version:    2.3.3
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
```

### Reproduction

Minimal examples: 

Nuxt 3.3.3: https://stackblitz.com/edit/github-msmhxs-kcquo4
Nuxt 3.4.0: https://stackblitz.com/edit/github-msmhxs-i2vnvr

### Describe the bug

useState appears not to be reactive in Nuxt 3.4.0. Watchers do not get triggered and views are not updated when the useState ref changes.

Compare the minimal examples for Nuxt 3.3.3 and Nuxt 3.4.0. Nuxt 3.3.3 behaves as expected when the button is clicked, in the Nuxt 3.4.0 example nothing changes when the button is clicked.

**Comment by c-schwan** [comment]
same Problem

**Comment by danielroe** [comment]
You can try working around for the moment with `experimental.renderJsonPayloads`.

**Comment by sei-jdshimkoski** [comment]
The workaround does not work for us. Unfortunately, I am unable to share relevant code.

**Comment by Razi91** [comment]
Same with `useColorMode()`, the returned object is not reactive

**Comment by timb-103** [comment]
Setting render

**Comment by timb-103** [comment]
Setting experimental: { renderJsonPayloads: true } gives the following error:

 [nuxt] [request error] [unhandled] [500] Cannot stringify arbitrary non-POJOs

**Comment by danielroe** [comment]
@timb-103 I would welcome a new issue with a reproduction on that one as we work on JSON payload support 🙏

**Comment by hamonCordova** [comment]
same here

**Comment by Zebnastien** [comment]
Same here.
By the way, great work Nuxt Team ! I love this framework :)

**Comment by vasilistotskas** [comment]
Same here , after enabling the experimental flag renderJsonPayloads I'm getting the following error and I cannot find out why : [nuxt] [request error] [unhandled] [500] Cannot stringify arbitrary non-POJOs

**Comment by danielroe** [comment]
@vasilistotskas If you could open an issue with a minimal reproduction that would be very helpful.

**Comment by vasilistotskas** [comment]
> @vasilistotskas If you could open an issue with a minimal reproduction that would be very helpful.

not sure which part of my codebase is the problem as the app is big and the error showing me no information about which part of the code is the problem , the full error i get is :
```
[nuxt] [request error] [unhandled] [500] Cannot stringify arbitrary non-POJOs                                                                                                                                           7:03:13 PM
  at flatten (/C:/Dev/grooveShop/storefrontUINodeNuxt/src/node_modules/devalue/src/stringify.js:138:13)
  at flatten (/C:/Dev/grooveShop/storefrontUINodeNuxt/src/node_modules/devalue/src/stringify.js:166:43)
  at flatten (/C:/Dev/grooveShop/storefrontUINodeNuxt/src/node_modules/devalue/src/stringify.js:166:43)
  at flatten (/C:/Dev/grooveShop/storefrontUINodeNuxt/src/node_modules/devalue/src/stringify.js:166:43)
  at flatten (/C:/Dev/grooveShop/storefrontUINodeNuxt/src/node_modules/devalue/src/stringify.js:60:39)
  at stringify (/C:/Dev/grooveShop/storefrontUINodeNuxt/src/node_modules/devalue/src/stringify.js:178:16)
  at renderPayloadJsonScript (/C:/Dev/grooveShop/storefrontUINodeNuxt/src/.nuxt/dev/index.mjs:5448:32)
  at /C:/Dev/grooveShop/storefrontUINodeNuxt/src/.nuxt/dev/index.mjs:5340:29
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async /C:/Dev/grooveShop/storefrontUINodeNuxt/src/.nuxt/dev/index.mjs:491:22
```

**Comment by dargmuesli** [comment]
I'd guess that it's most likely required to know what data ("non-POJO") is tried to be stringified, so the stacktrace alone does not give enough telemetry to fix a potential bug.

**Comment by vasilistotskas** [comment]
any ideas how can i find out what data is the non-POJO as my project is big and the error giving me zero information to resolve it ?

**Comment by dargmuesli** [comment]
Hop into a debugger and set a breakpoint where the error occurs :bulb:

**Comment by ArthurSegato** [comment]
Looks like useState is not working in Nuxt 3.8.2 again

**Comment by danielroe** [comment]
@ArthurSegato Would you raise a new issue with a reproduction? 🙏

**Comment by ArthurSegato** [comment]
Yes, of course!
