### ISSUE TITLE
Nuxt 3.4.0 with pinia

### ISSUE THREAD

**Issue by maicWorkGithub** [nuxt/nuxt#20225]
### Environment

```
------------------------------
- Operating System: Windows_NT
- Node Version:     v16.20.0
- Nuxt Version:     3.4.0
- Nitro Version:    2.3.3
- Package Manager:  npm@8.19.4
- Builder:          vite
- User Config:      typescript, ssr, modules
- Runtime Modules:  @pinia/nuxt@0.4.8
- Build Modules:    -
------------------------------
```

### Reproduction

https://stackblitz.com/edit/nuxt-starter-mjjyny?file=app.vue

### Describe the bug

`npm run dev` gets error:
```
pinia was called with no active Pinia. Did you forget to install pinia?
	const pinia = createPinia()
	app.use(pinia)
This will fail in production.
 
```

**Comment by maicWorkGithub** [comment]
Just modify Nuxt version in package.json from 3.3.3 to 3.4.0. Should I open an issue in Pinia repo?

**Comment by danielroe** [comment]
If it's a change based on a Nuxt release, then I'd like to investigate.

But, looking at the sandbox, it shows the same error on 3.3.3: https://stackblitz.com/edit/nuxt-starter-av7vdl.

**Comment by maicWorkGithub** [comment]
OK, I'll open this issue in Pinia. Thanks.

**Comment by danielroe** [comment]
Let's track there. If this has been caused by a Nuxt update, let me know and I'll happily dive in further.
