### ISSUE TITLE
Error while mounting app after upgrade to Nuxt 3.4 and ssr = false

### ISSUE THREAD

**Issue by stenet** [nuxt/nuxt#20238]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.12.1
- Nuxt Version:     3.4.0
- Nitro Version:    2.3.3
- Package Manager:  npm@9.1.3
- Builder:          vite
- User Config:      ssr
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/github/stenet/nuxt-34-non-ssr

Start the server and look at the console:
![image](https://user-images.githubusercontent.com/1838511/231517508-8da1105b-b0c3-4f13-b0d7-660c6f38a527.png)

### Describe the bug

After updating to Nuxt 3.4, an error occurs at startup when ssr is set to false in nuxt.config.ts.

**Comment by danielroe** [comment]
This is resolved in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/) via #20218, and will be included in the next release.

**Comment by stenet** [comment]
😁 That was fast. I saw the PR but didn't know it was for the same reason.
Thanks Daniel!
