### ISSUE TITLE
useState not reactive since Nuxt 3.4.0

### ISSUE THREAD

**Issue by edupuySportiw** [nuxt/nuxt#20231]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.4.0`
- Nitro Version:    `2.3.3`
- Package Manager:  `pnpm@8.2.0`
- Builder:          `vite`
- User Config:      `sourcemap`, `srcDir`, `typescript`, `build`, `vite`, `modules`, `runtimeConfig`, `i18n`, `http`, `proxy`, `auth`, `unocss`, `googleFonts`, `lodash`
- Runtime Modules:  `@nuxt-alt/auth@2.3.11`, `@nuxt-alt/http@1.6.4`, `@nuxt-alt/proxy@2.2.3`, `@pinia/nuxt@0.4.8`, `@nuxtjs/google-fonts@3.0.0`, `@unocss/nuxt@0.51.4`, `@nuxtjs/i18n@8.0.0-beta.10`, `vite-plugin-vue-type-imports/nuxt`, `nuxt-lodash@2.4.1`, `nuxt-svgo@1.1.0`, `@nuxt/image-edge@1.0.0-28020728.5df24eb`, `@nuxtjs/device@3.1.0`
- Build Modules:    `-`

### Reproduction

The Stackblitz example on Nuxt useState documentation itself is not working : 
https://nuxt.com/docs/examples/composables/use-state#usestate

### Describe the bug

Since Nuxt 3.4.0, `useState` is not "reactive" anymore. If I update the value of the state, the rendered value won't be updated.
If I rollback to version 3.3.3, everything is working as it should.

**Comment by thijsw** [comment]
This was already reported in #20211 and solved in #20218
