### ISSUE TITLE
Add ability to append brackets to query array keys

### ISSUE THREAD

**Issue by RomanSkrypnik** [nuxt/nuxt#20234]
### Describe the feature

`useFetch` doesn't append brackets to query array keys and doesn't have an option to do this.
Previously, I used axios which had an ability to change query/params with **qs plugin**.

For example, I have an array of numbers: [1, 2, 3] which I want to pass to useFetch as query/params;
### What URL I expect to see:
`http://localhost:3000/test?num[]=1&num[]=2&num[]=3`
### What I'm getting:
`http://localhost:3000/test?num=1&num=2&num=3`

It quite important because of APIs which are used to process requests.
For example, Nest JS works fine if query array keys are without appended brackets.
However, Laravel takes the last key ignoring previous ones.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by thijsw** [comment]
You can get some info on this issue from this issue in unjs/ofetch: https://github.com/unjs/ofetch/issues/119

**Comment by RomanSkrypnik** [comment]
The solution which I have used to do this task is using qs package
Closing this topic

**Comment by noc2spam** [comment]
For future reference, I made it work using the following:

`await useFetch<ResponseType>(url, {
   query: {
     "param[]": [1,2,3]
   }
}`

So, essentially sending `param[]` instead of `param` does the trick. Backend receives the array as expected.
