### ISSUE TITLE
Nuxt Starter Project no longer works when SSR is false on 3.4.0

### ISSUE THREAD

**Issue by justinwride** [nuxt/nuxt#20240]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.18.1`
- Nuxt Version:     `3.4.0`
- Nitro Version:    `2.3.3`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `ssr`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

I created a new Nuxt application using `npx nuxi init project-ssr-false`

Then ran `npm install`

The only change I made was in **nuxt.config.ts**:
```ts
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
    ssr: false
})
```

Then `npm run dev` 

Here is a repo with the configuration specified above that reproduces the issue: https://github.com/justinwride/project-ssr-false

### Describe the bug

The bug is a blank white page when I expected to see my Nuxt application.

After navigating to http://localhost:3000 I get the following console errors:
<img width="512" alt="image" src="https://user-images.githubusercontent.com/32500970/231534495-112f4e80-3c0b-4e7a-8717-b7745b73249e.png">

### Additional context

This error *does not happen* on version `3.3.3`. It is a new error with version `3.4.0`.

The line that appears to be failing is this:
```js
const nuxt = createNuxtApp({ vueApp });
```

Which is failing because of this line:
```js
const runtimeConfig = process.server ? options.ssrContext.runtimeConfig : reactive(nuxtApp.payload.config);
```

It appears that `nuxtApp.payload.config` is `undefined` 

### Logs

```shell-script
entry.js:39 value cannot be made reactive: undefined
createReactiveObject @ vue.js?v=2e04f03c:1090
reactive @ vue.js?v=2e04f03c:1076
createNuxtApp @ nuxt.js?v=33afac7b:97
initApp @ entry.js:39
(anonymous) @ entry.js:57
Show 3 more frames
entry.js:58 Error while mounting app: TypeError: Cannot create proxy with a non-object as target or handler
    at createNuxtApp (nuxt.js?v=33afac7b:98:1)
    at initApp (entry.js:39:18)
    at entry.js:57:3
(anonymous) @ entry.js:58
Promise.catch (async)
(anonymous) @ entry.js:57
```

**Comment by danielroe** [comment]
Huge apologies for this. It's already resolved in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/) via https://github.com/nuxt/nuxt/pull/20216, and I'll be releasing a patch shortly.
