### ISSUE TITLE
useState not working in v. 3.4

### ISSUE THREAD

**Issue by procrates** [nuxt/nuxt#20243]
### Environment

Local:
------------------------------
- Operating System: Darwin
- Node Version:     v17.9.0
- Nuxt Version:     3.4.0
- Nitro Version:    2.3.3
- Package Manager:  pnpm@8.2.0
- Builder:          vite
- User Config:      runtimeConfig, modules, sanity, image, imports, typescript
- Runtime Modules:  @nuxtjs/sanity@1.6.0, @nuxtjs/tailwindcss@6.6.5, @nuxt/image-edge@1.0.0-28008586.381b906
- Build Modules:    -
------------------------------

Stackblitz:
------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.0
- Nitro Version:    2.3.3
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

[useState not working v. 3.4](https://stackblitz.com/edit/nuxt-starter-ars6vb?file=app.vue)

Clone to compare:
[useState working v. 3.3.3](https://stackblitz.com/edit/nuxt-starter-weney3?file=app.vue)

### Describe the bug

useState does not update the value on interaction.

### Logs

```shell-script
No errors or logs.
```

**Comment by danielroe** [comment]
This has been resolved in https://github.com/nuxt/nuxt/pull/20218 and there will be a patch release tomorrow:
