### ISSUE TITLE
Incompatibility when using `.md` pages through `vite-plugin-vue-markdown`

### ISSUE THREAD

**Issue by miosenpai** [nuxt/nuxt#20245]
### Environment

```
------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.0
- Nitro Version:    2.3.3
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      vite, extensions
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Reproduction

https://stackblitz.com/edit/github-o84u83

### Describe the bug

I have been looking to add a very small number (2-3) of pages to a Nuxt 3 project using Markdown. Since I'll only using Markdown for a few pages in the project and don't need additional features like querying, I thought I'd try using [vite-plugin-vue-markdown](https://github.com/mdit-vue/vite-plugin-vue-markdown) instead of the heavier Nuxt Content.

I changed the Vite settings in `nuxt.config.ts` according to `vite-plugin-vue-markdown`'s documentation and added `.md` to the `extensions` array. However, this does not seem to be sufficient to get `vite-plugin-vue-markdown` and the Nuxt page resolver to work together since when I visit a page written using a Markdown file, I run into the following errors (as if `vite-plugin-vue-markdown` hasn't ran at all):

Server
```
ERROR  At least one <template> or <script> is required in a single file component.
```
Browser
```
500
[vite-node] [plugin:vite:vue] [SyntaxError] /pages/about.md?macro=true

# About Page

at /pages/about.md?macro=true
at Object.parse$4 [as parse] (./node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:5269:21)
at createDescriptor (file://./node_modules/@vitejs/plugin-vue/dist/index.mjs:86:43)
at transformMain (file://./node_modules/@vitejs/plugin-vue/dist/index.mjs:2240:34)
at TransformContext.transform (file://./node_modules/@vitejs/plugin-vue/dist/index.mjs:2738:16)
at Object.transform (file://./node_modules/vite/dist/node/chunks/dep-79892de8.js:43436:44)
at async loadAndTransform (file://./node_modules/vite/dist/node/chunks/dep-79892de8.js:41154:29)
```

### Additional context

I have been able to partially get the Vite plugin working in Nuxt by manually importing the routes using `app/router.options.ts` (https://stackblitz.com/edit/github-dbvb63), although this workaround interferes with other Nuxt features like import aliases:
```
[nuxt] #imports should be transformed with real imports. There seems to be something wrong with the imports plugin.
```

Per the instructions for reporting bugs, I have also tried using the Vite plugin with the Vue 3 SSR template and it seems to work fine there (https://stackblitz.com/edit/github-uo229m).

**Comment by danielroe** [comment]
You can use this config for Nuxt.

```ts
import markdown from 'vite-plugin-vue-markdown'

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  vite: {
    vue: {
      include: [/\.vue$/, /\.md(\?.+)?$/],
    },
    plugins: [
      markdown({
        include: /\.md(\?.+)?$/
      })
    ],
  },
  extensions: ['.md'],
})
```
