### ISSUE TITLE
 An error occurred while parsing the WebWorker bundle. This is most likely due to improper transpilation by Babel

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/nuxt#20256]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.3.3`
- Nitro Version:    `2.3.3`
- Package Manager:  `npm@9.5.0`
- Builder:          `vite`
- User Config:      `srcDir`, `modules`, `vite`, `i18n`, `nitro`, `schemaOrg`, `telemetry`, `algolia`, `head`, `auth`, `viewport`, `css`, `build`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.6.5`, `genesis-design-system/nuxt`, `@nuxtjs/algolia@1.6.0`, `formidable@2.1.1`, `nuxt-viewport@2.0.4`, `@nuxtjs/partytown@1.3.0`, `@vueuse/nuxt@9.13.0`, `nuxt-schema-org@2.1.2`, `nuxt-icon@0.1.8`, `@pinia/nuxt@0.4.8`, `@nuxtjs/i18n@8.0.0-beta.10`, `@sidebase/nuxt-auth@0.4.4`
- Build Modules:    `-`

### Reproduction

![image](https://user-images.githubusercontent.com/77386602/231746477-ed0b2590-01cb-4306-b268-1d3ded7afa9d.png)

Since many days this mapbox component runs ok, now throws error

`An error occurred while parsing the WebWorker bundle. This is most likely due to improper transpilation by Babel; please see https://docs.mapbox.com/mapbox-gl-js/guides/install/#transpiling`

Im trying transpile with nuxt.config.ts buid : {transpile : []}
but also throws errors...

any idea?

### Describe the bug

![image](https://user-images.githubusercontent.com/77386602/231746477-ed0b2590-01cb-4306-b268-1d3ded7afa9d.png)

Since many days this mapbox component runs ok, now throws error

`An error occurred while parsing the WebWorker bundle. This is most likely due to improper transpilation by Babel; please see https://docs.mapbox.com/mapbox-gl-js/guides/install/#transpiling`

Im trying transpile with nuxt.config.ts buid : {transpile : []}
but also throws errors...

any idea?

**Comment by danielroe** [comment]
This is likely an upstream vite issue. You might try with vite 4.3 beta.

**Comment by agracia-foticos** [comment]
https://github.com/mapbox/mapbox-gl-js/issues/12656 issue with mapbox and vite ;)

**Comment by danielroe** [comment]
Okay, let's close it here.
