### ISSUE TITLE
Can not use `useRuntimeConfig` in `/composables` or `/server` 

### ISSUE THREAD

**Issue by gyhyfj** [nuxt/nuxt#20255]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.3.3`
- Nitro Version:    `2.3.2`
- Package Manager:  `pnpm@8.2.0`
- Builder:          `vite`
- User Config:      `modules`, `vite`, `css`, `imports`, `pinia`, `app`, `ignore`, `telemetry`, `appConfig`, `devServer`, `nitro`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.6.5`, `@pinia/nuxt@0.4.7`, `@pinia-plugin-persistedstate/nuxt@1.1.1`, `@element-plus/nuxt@1.0.4`
- Build Modules:    `-`

### Reproduction
https://stackblitz.com/edit/github-rrso2z?file=app.vue

I want to build in different mode by using env file, just like usual vue-vite project.
So I put `NUXT_PUBLIC_API_BASE=https://xxxxxx`,  set this varibale in `runtimeConfig.public.apiBase` of `nuxt.config.ts`, 
and then get this value by `useRuntimeConfig`.
But I cannot access it in `/composables` or`/server` ,  which could lead to `500 nuxt instance unavailable`.

And I found that if I use environment variables start with `VITE_`, these variables can still be accessed in `import.meta.env`, so that I can use them to define my special fetch method.

I don't think it should be used because it's vite's special feature. But, I really dont know how to deal with it now.

### Describe the bug

Can not use `useRuntimeConfig` in `/composables` or `/server` .

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by danielroe** [comment]
Thanks! Within a composable, you need to move `useRuntimeConfig` into the body of the function. As is explained in the docs I linked, it needs to be associated with a particular request and therefore has to be called (on the vue side of your app) within a setup function, plugin, middleware or nuxt hook.

**Comment by gyhyfj** [comment]
Thank you very much !

**Comment by NaMoCv** [comment]
> Thank you very much !非常感谢 ！

did you succeed ？
