### ISSUE TITLE
Multiple `useFetch` in plugin

### ISSUE THREAD

**Issue by ElYaiko** [nuxt/nuxt#20265]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.4.0`
- Nitro Version:    `2.3.3`
- Package Manager:  `npm@9.5.0`
- Builder:          `vite`
- User Config:      `alias`, `app`, `runtimeConfig`, `css`, `build`, `modules`, `vite`, `experimental`, `nitro`
- Runtime Modules:  `@pinia/nuxt@0.4.8`, `()`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-yn4nmm?file=plugins/test.ts

### Describe the bug

When using more than one `useFetch` inside a plugin it throws `Error: nuxt instance unavailable`, I tried to de-duplicate them with `key` but still throws error.

**Comment by danielroe** [comment]
See https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables.

**Comment by ElYaiko** [comment]
> See https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables.
> 
> The issue is that you have wrapped those `useFetch` calls within another intermediate function. They should be fine if used directly in the plugin.

@danielroe So there's not way to make an interceptor that re-executes like failed requests via foreach within a function...?

**Comment by danielroe** [comment]
There is indeed. `useFetch` supports interceptors directly in its config and you can use `$fetch` anywhere (in the interceptor, for example).

**Comment by ElYaiko** [comment]
> There is indeed. `useFetch` supports interceptors directly in its config and you can use `$fetch` anywhere (in the interceptor, for example).

Yes I've tried with an interceptor to call `useFetch` again but it doesn't work, and if a call with `$fetch` will duplicate the response in client/server and I'm trying to avoid that, that's why I was trying to catch the failed requests to retry in server-side and return the right value in client-side...

**Comment by danielroe** [comment]
you can do that by assigning the response to ctx within the interceptor. No need for an additional useFetch.

If you want to do it programmatically, use useState + $fetch.

**Comment by ElYaiko** [comment]
> you can do that by assigning the response to ctx within the interceptor. No need for an additional useFetch.
> 
> If you want to do it programmatically, use useState + $fetch, or wrap the whole thing in useAsyncData.

I'm trying to assign the ctx response but still doesn't work with `useFetch`:

https://stackblitz.com/edit/github-yn4nmm?file=plugins%2Ftest.ts,server%2Fapi%2Ftest.post.ts,server%2Fapi%2Ftest2.post.ts

But with $fetch.onResponse(ctx) works well.
