### ISSUE TITLE
[worker reload] [worker init] Cannot find package 'micromark'  | Nuxt 3.4.1

### ISSUE THREAD

**Issue by mrniamster** [nuxt/nuxt#20260]
Environment
----------------
Platfrom: Windows 10,
Package Manager: npm 9.4.0   

"@nuxt/content": "^2.5.2",
"@nuxt/devtools": "^0.4.0",
"@nuxtjs/tailwindcss": "^6.6.6",
"nuxt": "^3.4.1",

![image](https://user-images.githubusercontent.com/52563039/231811901-cb3a016b-8089-4052-a0d0-d287210fd4f5.png)

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by mrniamster** [comment]
Hello @danielroe ,
The issue got resolved by running:
`nuxi upgrade --force`

Reproduction steps:

I was previously in these version:
`{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/content": "^2.5.2",
    "@nuxt/devtools": "^0.2.5",
    "@nuxtjs/tailwindcss": "^6.6.4",
    "nuxt": "^3.3.2",
    "sass": "^1.60.0",
    "sass-loader": "13.2.1"
  },
  "dependencies": {
    "@picocss/pico": "^1.5.7",
    "@pinia/nuxt": "^0.4.7",
    "@shopid/vue3-swipe-box": "^0.1.5",
    "@tailwindcss/typography": "^0.5.9",
    "daisyui": "^2.51.5",
    "pinia": "^2.0.33",
    "vue-sidebar-menu": "^5.2.5"
  },
  "overrides": {
    "vue": "latest"
  }
}`

After that i did the following:
> npm check-npm-updates -u
> npm install 

and these issue arrived , 
`{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/content": "^2.5.2",
    "@nuxt/devtools": "^0.4.0",
    "@nuxtjs/tailwindcss": "^6.6.6",
    "nuxt": "^3.4.1",
    "sass": "^1.62.0",
    "sass-loader": "13.2.2"
  },
  "dependencies": {
    "@pinia/nuxt": "^0.4.8",
    "@shopid/vue3-swipe-box": "^0.1.5",
    "@tailwindcss/typography": "^0.5.9",
    "daisyui": "^2.51.5",
    "pinia": "^2.0.34",
    "vue-sidebar-menu": "^5.2.5"
  },
  "overrides": {
    "vue": "latest"
  }
}
`

**Comment by danielroe** [comment]
Great! I'm glad it was resolved.
