### ISSUE TITLE
nuxt warning: nuxt build finished but did not exit after 5s

### ISSUE THREAD

**Issue by buglavecz** [nuxt/nuxt#20271]
### Environment

```
 System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 2.77 GB / 15.87 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.18.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.39)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    nuxt: ^2 => 2.16.3
```

### Reproduction

I can't give reproduction link, because we runned in docker.

### Describe the bug

I got warning, when I crate a production build with `--standalone` option.

### Logs

![image](https://user-images.githubusercontent.com/43108336/232039522-b1513717-e67a-4261-8f15-8fce4f203759.png)

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

When you say you can't do it because of Docker, why is that? If that's required, feel free to share a repository with a Dockerfile.

**Comment by buglavecz** [comment]
hi @danielroe.
sorry, thats true. 

this is my dockerfile:
```
##
# BUILDER
##
FROM node:16 as builder

WORKDIR /app

ADD yarn.lock package.json ./
RUN yarn install \
  --prefer-offline \
  --frozen-lockfile \
  --non-interactive \
  --production=false
ADD . ./

ARG BUILD_VER
ARG COMMIT_HASH
ENV BUILD_VER=$BUILD_VER
ENV COMMIT_HASH=$COMMIT_HASH

RUN if [ "$BUILD_VER" = "prod-local.0123456" ]; \
        then cp .env.default .env;  \
    else cp .env.aws .env; \
	fi

RUN yarn build:prod-sa

##
# RUNNER
##
FROM node:16 as starter

WORKDIR /app

RUN yarn add \
    nuxt-start@2.16.3 \
    @nuxtjs/sentry@7.1.11 \
    @sentry/tracing@7.46.0 \
    node-fetch-native@1.0.2 \
    @artmizu/analytics-nuxt-2@1.0.1 \
    @remix-run/web-fetch@4.3.3 \
    basic-auth@2.0.1 \
    prom-client@14.2.0

COPY --from=builder /app/.env /app/.env
COPY --from=builder /app/.nuxt /app/.nuxt
COPY --from=builder /app/server-middleware /app/server-middleware
COPY --from=builder /app/nuxt.config.js /app/
COPY --from=builder /app/static /app/static

ARG BUILD_VER
ARG COMMIT_HASH
ENV BUILD_VER=$BUILD_VER
ENV COMMIT_HASH=$COMMIT_HASH

CMD ["npx", "nuxt-start"]
```

thanks.

**Comment by danielroe** [comment]
@buglavecz Would you provide more information? Ideally I want a reproduction that is self-sufficient so I can just run a few commands to reproduce the issue.

**Comment by buglavecz** [comment]
repository in private, so I can't give source code 😞 

this bug: 
![image](https://user-images.githubusercontent.com/43108336/232009194-fc6942e8-f42b-4c02-8ba6-ed261c7adcf5.png)

come with this lib: `@artmizu/analytics-nuxt-2` (https://github.com/artmizu/nuxt-2-prometheus)
this is use server middlewares. when i remove from nuxt.config under modules, the warn is not showing:
```
modules: [
        '@nuxtjs/sentry',
        /*['@artmizu/analytics-nuxt-2', {
            verbose: process.env.NODE_ENV === 'development'
        }],*/
    ],
```

but this bug isn't found, where come from:
![image](https://user-images.githubusercontent.com/43108336/232010705-1026bd77-c093-479a-b9be-9989ece8299b.png)

I found this issue, but not helped for me.
https://github.com/nuxt/nuxt/issues/5669

I don't have any idea.... 😞
