### ISSUE TITLE
dev server hangs on initial load when importing from `#components`

### ISSUE THREAD

**Issue by danielroe** [nuxt/nuxt#20272]
> My dev server hangs on specific routes on page reload when I import and use components imported from `#components`. It seems like a Vite issue, but if I import the same component from it's direct location the issue is gone. It also applies to built-in components like `NuxtLink`. 
>
> I was able to create a small reproduction of the issue, you can find it here: https://stackblitz.com/edit/nuxt-starter-azudzq?file=pages%2Findex.vue

_Originally posted by @zsilbi in https://github.com/nuxt/nuxt/issues/13413#issuecomment-1508212521_

**Comment by danielroe** [comment]
Looking into this, I think this is likely due to the circular dependency of importing _from_ `#components` _within_ a component which will be exposed through `#components`. It works in build, and within dev mode you can workaround with this config:

```ts
export default defineNuxtConfig({
  vite: {
    devBundler: 'legacy',
  }
})
```

I think it might be an issue from `vite-node` (cc: @antfu).

**Comment by antfu** [comment]
I can confirm it's a bug of vite-node, still investigating

**Comment by antfu** [comment]
This bug can count as my top 5 most challenging bugs to debug I have ever encountered 🤣 But I enjoyed the process :P

Helpfully https://github.com/vitest-dev/vitest/pull/3196 could solve it (it works now in repro).

It would be great if you could help test if the changes fix your issue in your real-world project.

You can build from the PR source, or I have pre-packed one for you to test:

https://temp.sh/BawXf/vite-node-0.30.1-3196a.tgz

Download it in your project root, and add

```ts
  "resolutions": {
    "vite-node": "./vite-node-0.30.1-3196a.tgz"
  }
```

To your package.json, run `pnpm install` or `yarn install` to apply it.

Thanks!

**Comment by zsilbi** [comment]
> This bug can count as my top 5 most challenging bugs to debug I have ever encountered 🤣 But I enjoyed the process 📦 

I wish I had known this sooner.. that way I might have enjoyed that few hours a bit more that I spent trying to reproduce this. 🤣 
But at least I am glad I could contribute to that list 😉 

> Helpfully [vitest-dev/vitest#3196](https://github.com/vitest-dev/vitest/pull/3196) could solve it (it works now in repro).
> 
> It would be great if you could help test if the changes fix your issue in your real-world project.

Great job!  Works like a charm. thank you guys!
