### ISSUE TITLE
`import.meta` is empty in server context 

### ISSUE THREAD

**Issue by enkot** [nuxt/nuxt#20283]
### Environment

- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.1
- Nitro Version:    2.3.3
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-c9hqoz?file=locales%2Fen-us%2Fproduct.json,locales%2Fen-ca%2Fproduct.json,server%2Fapi%2Fproduct.get.ts

### Describe the bug

The `import.meta.glob` throws an error when trying to import multiple json files in `/server/api/product.get.ts`:
```ts
const modules = import.meta.glob('../../locales/*/product.json');
console.log('modules', modules);

export default defineEventHandler(async (e) => {
  return { status: 'OK' };
});
```

**Comment by danielroe** [comment]
`import.meta.glob` is a vite utility and is not available in nitro, which is not bundled by vite.

**Comment by enkot** [comment]
@danielroe So, the only way to dynamically load json files is to use some glob lib (e.g. "globby") + fs, right?

**Comment by danielroe** [comment]
Nitro has a storage layer that can access files. As a plus, this will work even on deployment targets where you don't have FS access. You can move your json files into `~/server/assets` and access them via `useStorage` starting with the key `server`.

**Comment by enkot** [comment]
@danielroe Thank you for instant response, it works! 

P.S. Would be great to make it also work with layers, because currently `assets/server` only works for top-level `/server` folder. Currently I need to do something like this `root:my-layer:server:assets:locales:en-ca:product.json` for each layer.
