### ISSUE TITLE
Cannot read properties of undefined (reading'meta ')

### ISSUE THREAD

**Issue by zhaogongchengsi** [nuxt/nuxt#20295]
### Environment

- Operating System: Windows_NT
- Node Version:     v16.17.0
- Nuxt Version:     3.4.1
- Nitro Version:    2.3.3
- Package Manager:  pnpm@8.2.0
- Builder:          vite
- User Config:      modules, app, runtimeConfig
- Runtime Modules:  @nuxt/devtools@0.4.0
- Build Modules:    -

### Reproduction

https://github.com/zhaogongchengsi/blog-nuxt

### Describe the bug

After the project starts, there will be two errors ```"[Vue warning]: inject () can only be used inside setup () or functional components"``` and ```"Cannot read properties of undefined (reading'meta ')```, but I haven't started writing a page, so I think it's a bug in nuxt, and I haven't found a similar bug after looking for the issue, but I'm not sure.

**Comment by danielroe** [comment]
You have multiple copies of some core Vue packages in your lockfile. Run `pnpm dedupe` to clear them out, and you should be good.

**Comment by nexthis** [comment]
in nuxt 3.8.0 you need add

```
    "vue": "^3.3.7",
    "vue-router": "^4.2.5",
```
