### ISSUE TITLE
dynamic style space problem

### ISSUE THREAD

**Issue by productdevbook** [nuxt/nuxt#20292]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.3.3`
- Nitro Version:    `2.3.2`
- Package Manager:  `pnpm@8.1.0`
- Builder:          `vite`
- User Config:      `modules`, `extends`
- Runtime Modules:  `@unocss/nuxt`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-tgszn4?file=app.vue

### Describe the bug

div style space problem

```
style="position: fixed; z-index: 9999; inset: 16px; pointer-events: none;"
```

It should be like this, but it doesn't happen with the data entered with :style.

![image](https://user-images.githubusercontent.com/38668796/232195455-8c14ec3e-9cb8-4bbc-8085-b105ba9c4ed5.png)

**Comment by danielroe** [comment]
I'm not sure that spaces are required.

You can confirm at https://validator.w3.org/nu with the following code:

```ts
<!DOCTYPE html>
<html lang="en">

<head>
<title>Home</title>
</head>

<body>
<div style="position:fixed;z-index:9999">Hi</div>
</body>

</html>
```

I believe your issue is that you should use `inset: '16px'` and not `inset: 16`.
