### ISSUE TITLE
nuxt3.4.1 Object literal may only specify known properties, and 'srcDir' does not exist in type 'NuxtConfig'.

### ISSUE THREAD

**Issue by stephenjason89** [nuxt/nuxt#20302]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.13.0
- Nuxt Version:     3.4.1
- Nitro Version:    2.3.3
- Package Manager:  pnpm@8.2.0
- Builder:          vite
- User Config:      srcDir, build, imports, apollo, modules, hooks
- Runtime Modules:  nuxt-chatgpt@0.1.10, @nuxtjs/apollo@5.0.0-alpha.5, @pinia/nuxt@0.4.8
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/stephenjason89/nuxt-vuetify-graphql-pinia-starter
Clone the project then 
pnpm i
pnpm dev

open file nuxt.config.ts
no errors yet. on nuxt 3.3.2

nuxt upgrade --force
then pnpm dev

check nuxt.config.ts
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/3810177/232288394-58e57e8e-aad1-499c-85a5-f2b49abffd17.png">
error on nuxt 3.4.1

### Describe the bug

 Object literal may only specify known properties, and 'srcDir' does not exist in type 'NuxtConfig'.

**Comment by stephenjason89** [comment]
@danielroe Have you tried nuxt upgrade --force on the project that i linked?
The project is currently at nuxt 3.3.2 and no linting errors for me there as well.

I do have dist and .output gitignored
https://github.com/stephenjason89/nuxt-vuetify-graphql-pinia-starter/blob/main/.gitignore
But this doesn't cause the issue on 3.3.2

After commenting out dist and .output on my gitignore
<img width="272" alt="image" src="https://user-images.githubusercontent.com/3810177/232410667-112bda0d-c10d-4ca4-9755-f7a595d693f5.png">

<img width="207" alt="image" src="https://user-images.githubusercontent.com/3810177/232410609-db878a93-d975-425f-9916-6c9c7448ff29.png">

It still is present
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/3810177/232410529-ef710bbd-dc1f-43b6-b90e-d6b44ad292d6.png">

**Comment by danielroe** [comment]
Yes, I did indeed run that command and could not reproduce the issue.

Adding or removing paths to `.gitignore` won't make any difference. Would you try deleting them, and rerunning `nuxi prepare`, and then restart your IDE to see if it helps?

**Comment by krissss** [comment]
Perhaps it's a problem with webstorm. There's no problem with vscode.

**Comment by stephenjason89** [comment]
Thank you for the reply @danielroe 
i deleted dist and .output
did nuxi prepare and restarted my IDE
<img width="1581" alt="image" src="https://user-images.githubusercontent.com/3810177/232965608-f9de8d47-cbb9-446c-8901-acecdb054b0c.png">

@krissss I am getting the same error on my vscode
<img width="922" alt="image" src="https://user-images.githubusercontent.com/3810177/232966006-5349e24c-e7d5-4c70-bee6-7c9344dfd151.png">

Please let me know what other steps i can do to debug this.
Thank you so much

**Comment by noyalin** [comment]
I have encountered the same problem and I don't know what to do.

**Comment by danielroe** [comment]
The best thing is if you can provide a reproduction. Please check first that you can reproduce by following the exact steps in the reproduction (including cloning fresh).

**Comment by stephenjason89** [comment]
@danielroe will try it on a different computer. I have tried cloning fresh and can reproduce it in the same computer.
Might have something to do with my environment.

Will report back once I have tried reproducing it in a different computer.

**Comment by rcluis** [comment]
I had the same issue, I run again `nuxi upgrade` and the problem was solved.

Hope it helps.

**Comment by alimozdemir** [comment]
It is very hard to create a reproduction repository when you have a large repo. There are too many variables.

I have the same issue but what I found is actually is very interesting @danielroe 

![image](https://user-images.githubusercontent.com/4493134/233837738-8763b586-1e64-4a83-81bd-0582eaea53e3.png)

I just removed that extends configuration and the error moves to the 'nitro' configuration. Then If I remove the nitro configuration error will be present in "experimental". So it goes like that,


What I understand from this point NuxtConfig interface is generated automatically and when I see the definition there are no configuration def for those things.

![image](https://user-images.githubusercontent.com/4493134/233837849-c2e6c993-892c-4e48-bc21-640c9be18487.png)

I think it is misses some "extends BaseNuxtConfig" but idk.

I can share what packages I use.

```
"@nuxt/image-edge": "1.0.0-28020728.5df24eb",
"nuxt-simple-sitemap": "^2.4.11",
```

**Comment by TomasSestak** [comment]
same happening with `buildModules`

**Comment by jeebeys** [comment]
upgrading to TypeScript 5.0.4 resolved the problem for me :) #20221

**Comment by elizabthpazp** [comment]
> 

I have the same problem

**Comment by TheParad0X** [comment]
Same probleme here. Adding typescript and vue-tsc to the devDevependencies solves the problem:

`  "devDependencies": {
    "primeicons": "^6.0.1",
    "primevue": "^3.28.0",
  },`

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/20221.

**Comment by stephenjason89** [comment]
Hey @danielroe , 
I can confirm that this did the trick https://github.com/nuxt/nuxt/issues/20221#issuecomment-1505323984
However, it introduced another bug.
<img width="594" alt="image" src="https://user-images.githubusercontent.com/3810177/237003201-755aa3fb-a630-4131-a0b3-e320629b206a.png">
this is not present with the bundled typescript compiler 4.8.4
and present in 5.0.4
