### ISSUE TITLE
Unable to upload a file to nuxt server larger than 2Mo

### ISSUE THREAD

**Issue by k3z** [nuxt/nuxt#20319]
### Environment

- Operating System: Darwin
- Node Version:     v18.15.0
- Nuxt Version:     3.4.1
- Nitro Version:    2.3.3
- Package Manager:  pnpm@7.30.0
- Builder:          vite
- User Config:      app, runtimeConfig, modules, fontLoader, css, postcss, build
- Runtime Modules:  @pinia/nuxt@0.4.8, @element-plus/nuxt@1.0.4, nuxt-icon@0.2.11, @vueuse/motion/nuxt@2.0.0-beta.27, nuxt-font-loader@2.3.1
- Build Modules:    -

### Reproduction

This my server resource to use Nuxt3 server as a proxy to upload a file to a private API
Nginx accept big files `client_max_body_size 100m;` 

```
import { apiRequest } from '~~/server/utils/client'
import axios from 'axios'
const config = useRuntimeConfig()

export default defineEventHandler(async (event) => {
  const body = await readBody(event)
  const params = getRouterParams(event)
  try {
    const res = await fetch(body.file)
    const blob = await res.blob()

    const formData = new FormData()
    formData.append(body.key, blob, body.name)

    const url = `${config.apiPrivateURL}/${params._}`

    const result = await axios.post(url, formData, {
      headers: {
        'Content-Type': 'multipart/form-data',
        Authorization: `Bearer ${event.context.session.token}`,
      },
    })

    if (result.status === 200) {
      return result.data
    } else {
      return createError({
        statusCode: 500,
        message: 'NOT UPLOADED',
      })
    }
  } catch (error) {
    console.log(error.response._data)
    return createError({
      statusCode: 403,
      message: 'FORBIDDEN',
    })
  }
})

```

### Describe the bug

When I upload a file larger than ~2Mo I got an error response.
It's currently not documented

How can I pass this directive to nitro ?

```
url	"/api/upload/stories/8e7c874a-9e8f-4241-aebc-6447871480a8/upload-cover/"
statusCode	500
statusMessage	""
message	"Cannot read properties of undefined (reading '_data')"
stack	""
error FetchError:  (500 Internal Server Error (/api/upload/stories/[…]/upload-cover/))
    NuxtJS 39
entry.bf8ddc9e.js:9:91693
context 
Proxy { <target>: {…}, <handler>: {…} }
entry.bf8ddc9e.js:9:91716
```

Thank you and have a nice day :)

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
