### ISSUE TITLE
pageTransition breaks component rendering

### ISSUE THREAD

**Issue by darthf1** [nuxt/nuxt#20318]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.1
- Nitro Version:    2.3.3
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      app, imports, ssr, plugins
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-fxstfh?file=nuxt.config.ts

### Describe the bug

Having `pageTransition` enabled, the component does not render when navigating between pages. On initial render it works (after refresh) but when navigating to the other pages it stops rendering.

In the repro, removing the `pageTransition` option from `nuxt.config.ts`, it works again.

**Comment by danielroe** [comment]
The reason is that, with suspense, components are mounted before they are present in the DOM. This is upstream Vue behaviour and is tracked in an issue here, which includes a couple of workarounds:

https://github.com/nuxt/nuxt/issues/13471
