### ISSUE TITLE
Cannot create custom 404 error page

### ISSUE THREAD

**Issue by DavidAbou** [nuxt/nuxt#20316]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.15.0
- Nuxt Version:     3.4.1
- Nitro Version:    2.3.3
- Package Manager:  npm@9.5.0
- Builder:          vite
- User Config:      css, modules, postcss
- Runtime Modules:  nuxt-icon@0.3.3, nuxt-swiper@1.1.0
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-o64zed?file=pages/index.vue

### Describe the bug

Normally when create 404.vue under pages folder, 404.vue become custom 404 error page but here this is not the case.

**Comment by warflash** [comment]
The file should be called `error.vue` instead of `404.vue` (See https://nuxt.com/docs/getting-started/error-handling#rendering-an-error-page)

**Comment by DavidAbou** [comment]
I've foud the error. In the newest version of nuxt 3. All errors are handled in ~/error.vue at the root of the project. So if you want to handle custom 404 error page you have to create that error.vue file.
