### ISSUE TITLE
Nuxt 3.4.1 SSR & hydration bug

### ISSUE THREAD

**Issue by Bombastickj** [nuxt/nuxt#20312]
### Environment

Nuxt project info:

------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.1
- Nitro Version:    2.3.3
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-fsjbsx?file=app.vue

### Describe the bug

This project shows a render bug that appears on SSR & also after hydration. All you need is a component, which has a button as a root element & another one inside it. When this component is used in any way, on SSR the buttons turn to be split & outside of the parent button. On hydration, the wrongly placed buttons are not removed correctly.

**Comment by huang-julien** [comment]
Hi that's not a bug. This is a behavior from vue SSR which does not allow do render invalid HTML. In your case, you canno't put a `button` wthin a `button`

**Comment by Bombastickj** [comment]
Wow sometimes I'm really questioning my semantic skills. Thanks for the reply!
