### ISSUE TITLE
SSR Hydration Mismatch when rendering Property of Ref returned by Computed

### ISSUE THREAD

**Issue by floriankapaun** [nuxt/nuxt#20326]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.1
- Nitro Version:    2.3.3
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Stackblitz reproduction: [https://stackblitz.com/edit/nuxt-starter-68glvb](https://stackblitz.com/edit/nuxt-starter-68glvb?file=app.vue)

### Describe the bug

I have a Pinia Store holding an Array of all dog-datasets I fetched yet. When I render a specific dog-page (i.e. `/dogs/dog-id-123`) that pinia store gets instantiated, I check if the dog-dataset for `dog-id-123` was already fetched by using a getter that contains the finding logic. If the dog-dataset doesn't exist yet, I fetch it. Because I have to access the dog-dataset multiple times across the page template I use a computed instance (i.e. `const dogDataset = computed(() => dogStore.getDogBySlug(dogSlug))`) to recycle the logic and save me from typing a few characters.

That's all nice and working on first glance, but if you open the dev console you'd notice that you receive a `hydration mismatch` warning for the parts where the `dogDataset` is accessed in the template rendering if the page is loaded directly.

If I would always directly access the dataset trough its getter I wouldn't receive the warning. But I'd really like to save my users from computing the getter logic x times.

If I do a simple `console.log` of the computed value in the script setup that hydration mismatch will vanish.

You can see a very stripped down version of my example in the stackblitz reproduction repository. I'm not relying on pinia or something else in the reproduction to keep it focused on the core issue.

Is the fault on my side? Am I doing something that's not expected to be done? 😬

**Comment by danielroe** [comment]
The issue is that your store uses `useFetch` which should only be called in setup function, not within a template.

The reason it works with the console.log is that computed is lazy evaluated. So by logging it in setup you force `useFetch` to be _called_ in setup.

Instead, use `$fetch`.
