### ISSUE TITLE
Hydration mismatch when custom element contains child node

### ISSUE THREAD

**Issue by dritter** [nuxt/nuxt#20327]
### Environment

- Operating System: `Linux`
- Node Version:     `v19.8.1`
- Nuxt Version:     `3.4.1`
- Nitro Version:    `2.3.3`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `vue`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/dritter/nuxt-hydration-mismatch-reproducer

### Describe the bug

If I have a custom element that has a child node, I get an hydration mismatch.

![image](https://user-images.githubusercontent.com/1544760/232484949-df3582f1-76ec-45d1-a51c-dc9a86d87ade.png)

This reproducer configures a custom element [`my-component`](https://github.com/dritter/nuxt-hydration-mismatch-reproducer/blob/main/server/plugins/my-component.js) (using [a nitro hook](https://github.com/nuxt/nuxt/issues/14195#issuecomment-1397369535)) and [uses it](https://github.com/dritter/nuxt-hydration-mismatch-reproducer/blob/main/app.vue#L3).
The custom element renders a red block on the client side.

Interestingly this does not happen, if:
- the custom element has no child node
- I wrap the `connectedCallback()` code in a `setTimeout` with a large timeout (like 1000ms)

I would have guessed that by [marking it as custom element](https://github.com/dritter/nuxt-hydration-mismatch-reproducer/blob/main/nuxt.config.ts#L6) that this element gets completely ignored.

Not sure if this is a Bug in really in nuxt or in Vues SSR part (apologies if this is wrong).

### Logs

```shell-script
From the Browser console:

entry.js:49 [Vue warn]: Hydration children mismatch in <my-component>: server rendered element contains more child nodes than client vdom. 
  at <App key=3 > 
  at <NuxtRoot>
warn2 @ vue.js:1381
hydrateElement @ vue.js:5497
hydrateNode @ vue.js:5420
hydrateChildren @ vue.js:5524
hydrateElement @ vue.js:5492
hydrateNode @ vue.js:5420
hydrateSubTree @ vue.js:6101
componentUpdateFn @ vue.js:6115
run @ vue.js:405
instance.update @ vue.js:6220
setupRenderEffect @ vue.js:6228
mountComponent @ vue.js:6046
hydrateNode @ vue.js:5425
hydrateSuspense @ vue.js:2749
hydrateNode @ vue.js:5448
hydrateSubTree @ vue.js:6101
componentUpdateFn @ vue.js:6115
run @ vue.js:405
instance.update @ vue.js:6220
setupRenderEffect @ vue.js:6228
mountComponent @ vue.js:6046
hydrateNode @ vue.js:5425
hydrate2 @ vue.js:5342
mount @ vue.js:5209
app.mount @ vue.js:9291
initApp @ entry.js:49
await in initApp (async)
(anonymous) @ entry.js:57
Show 25 more frames
entry.js:49 Hydration completed but contains mismatches.
```

**Comment by danielroe** [comment]
This doesn't sound like a Nuxt issue to me. Would you see if you can reproduce with https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter and, if so, raise an issue to https://github.com/vuejs/core ? 🙏

**Comment by zabavnikov** [comment]
@dritter are you using nuxt-alt/auth?

**Comment by dritter** [comment]
> @dritter are you using nuxt-alt/auth?

@zabavnikov Nope.

@danielroe I was able to reproduce it upstream and created https://github.com/vuejs/core/issues/8110
Thanks for your help.

Closing this Issue here.

**Comment by cn1001wang** [comment]
I encountered the same error? How did you solve it

**Comment by dritter** [comment]
@cn1001wang This is not solved. I closed this issue because it is a bug within vue, not nuxt. See https://github.com/vuejs/core/issues/8110

**Comment by dritter** [comment]
Btw. I forgot to mention that we could work around it using a 3rd party lib to delay hydration: https://github.com/Baroshem/nuxt-lazy-hydrate
