### ISSUE TITLE
getSSRProps return value does not pass down innerHTML as dom props

### ISSUE THREAD

**Issue by henkvhest** [nuxt/nuxt#20331]
### Environment

- Operating System: Darwin
- Node Version:     v16.14.2
- Nuxt Version:     3.0.0
- Nitro Version:    1.0.0
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      nitro, css, components, vite
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-fvfobb?file=app.vue,plugins%2Finnerhtml.ts

### Describe the bug

I'm currently working rewriting some parts of our codebase from Nuxt 2 to Nuxt 3. Previously we made use of directives which had a specific part to allow for SSR rendering by passing our own bit of code to the Nuxt 2 config:
`
 bundleRenderer: {
      directives: {
        customDirective: (vnode, directiveMeta) => {
            vnode.data = {
                ...vnode.data,
                domProps: {
                // transforms value before putting it in innerHTML
                    innerHTML: transform(directiveMeta.value),
                },
             };
          },
      },
    },
`
This bit of config allowed us to render sanitized content in an SSR manner before. Now in Nuxt 3 this no longer works since we should pass our directives via a plugin. I tried in the stackblitz example to write some content to innerHTML via getSSRProps, but this doesn't provide the same value as domProps (nuxt 2) anymore. I'm not sure if this is a bug or intended behaviour, or perhaps there is a different way to modify innerHTML in getSSRProps?

**Comment by danielroe** [comment]
I believe this difference is attributable to the upgrade from Vue 2 to Vue 3.

Reproduction without Nuxt: https://stackblitz.com/edit/github-c1z4a8.

**Comment by henkvhest** [comment]
Ah I was under the impression that getSSRProps was a Nuxt specific thing, my bad
