### ISSUE TITLE
NuxtLink activeClass not applied on child routes

### ISSUE THREAD

**Issue by command-tab** [nuxt/nuxt#20338]
### Environment

nuxt 3.4.1

### Reproduction

https://stackblitz.com/edit/github-nugbe3?file=app.vue

### Describe the bug

When using NuxtLink's activeClass, it does not apply the [activeClass](https://nuxt.com/docs/api/components/nuxt-link#props) when visiting child routes of a parent. For example, if I have a persistently visible NuxtLink to `/items` with an `activeClass` specified like so:

```
<nav>
  <nuxt-link to="/items" activeClass="foo">Items</nuxt-link>
</nav>
```
When I visit the `/items` route, the link becomes active and the `foo` class is applied as expected. Great.

However, when I visit `/items/123`, the link becomes no longer active and the `foo` class is removed. I would expect that behavior if I had specified `exactActiveClass`, but I did not use `exactActiveClass` — I used regular old `activeClass`.

FWIW, NuxtLink under Nuxt 2 works as I expected.

I put together a minimal repro here: https://stackblitz.com/edit/github-nugbe3?file=app.vue

Thank you ❤️

**Comment by danielroe** [comment]
Your route `/things/:thing-id` is not a child/nested route of `/things`. They are parallel routes.

Note the caveat here: https://router.vuejs.org/guide/migration/#removal-of-the-exact-prop-in-router-link

**Comment by command-tab** [comment]
Thanks for looking! If I wanted navigation links to remain active even when visiting `/things/:thing-id`, is that achievable by rearranging the `pages/` directory structure, or would I need to do manual path comparisons and set the appearance myself (and not rely on `activeClass`)? Or something else entirely?

**Comment by danielroe** [comment]
Yes, you could indeed implement that by rearranging the structure so they are nested routes... Or maybe implement a custom link wrapper with different logic?

**Comment by command-tab** [comment]
Sorry for my ignorance — could you suggest how to rearrange the files in `pages/` such that `/things/:thing-id` becomes a nested route without changing the resulting route path? I understand that I can use `<NuxtPage>` to display a child, but I don't want child pages to appear _within_ their parent. I want them to appear to be standalone pages but still have `activeClass` apply when the parent or its children are being visited. It seems like I might need a custom link wrapper...

**Comment by command-tab** [comment]
Ah, nevermind! This StackOverflow question explained it:

https://stackoverflow.com/questions/74637529/router-link-active-nuxt-3-vuejs-on-nested-routes-not-applying-to-parent

I was missing was a top-level `things.vue` that contained only:

```
<template>
  <NuxtPage />
</template>
```

**Comment by slavanossar** [comment]
> Ah, nevermind! This StackOverflow question explained it:
> 
> [stackoverflow.com/questions/74637529/router-link-active-nuxt-3-vuejs-on-nested-routes-not-applying-to-parent](https://stackoverflow.com/questions/74637529/router-link-active-nuxt-3-vuejs-on-nested-routes-not-applying-to-parent)
> 
> I was missing was a top-level `things.vue` that contained only:
> 
> ```
> <template>
>   <NuxtPage />
> </template>
> ```

Just noting for anyone else that this solution results in another problem where `useFetch` in `<script setup>` runs twice, somehow linked to this issue https://github.com/vuejs/router/issues/626.

**Comment by belfortf** [comment]
I would be very interested in understanding what's the solution for this problem.

**Comment by milos018** [comment]
@belfortf The above solution as described in SO works perfectly. You will get the needed styling for all pages.

**Comment by FabianEllenberger** [comment]
I can't seem to get this working with a catch-all route. For instance when visiting `/test/132` it renders my `[...slug.vue]` catch-all route but the route `test` seems to be a parallel route instead of a child route.

My goal is that all routes and levels of child routes can have active classes when used in `NuxtLink` without having to have specific folders and instead make use of a global catch-all route.

Can this be achieved or do I have to specifically add child slug folders in my pages directory?

**Comment by InerkyJad** [comment]
i tried the solution that @command-tab referred to but it didn't work, (NOTE: my case is normal routes, nothing dynamic), i just opted to using `userRoute()`.
example `:class="{ active: route.path.includes('/app/interactions') }"`

**Comment by FullStackAlex** [comment]
> Ah, nevermind! This StackOverflow question explained it:
> 
> https://stackoverflow.com/questions/74637529/router-link-active-nuxt-3-vuejs-on-nested-routes-not-applying-to-parent
> 
> I was missing was a top-level `things.vue` that contained only:
> 
> ```
> <template>
>   <NuxtPage />
> </template>
> ```
Official Nuxt 3 docs:
https://nuxt.com/docs/guide/directory-structure/pages#nested-routes

**Comment by coltisor** [comment]
I think the solution from above no longer works. See: https://github.com/nuxt/nuxt/issues/26364

At least I wasn't able to make it work in my app.

**Comment by haexhub** [comment]
I came up with something like this:
This works even with localized routes.

```
<template>
  <NuxtLinkLocale
      :to
      :class="{ ['bg-base-300']: isChild }"
      ...
    >
    ...
  </NuxtLinkLocale>
</template>

<script>
const props = defineProps({
  to: {
    type: Object as PropType<RouteLocationRaw>,
    default: '',
  },
});

const isChild = computed(() => {
  const found = useRouter()
    .getRoutes()
    .find((route) => {
      if (typeof props.to === 'string') {
        return route.name === useLocaleRoute()(props.to)?.name;
      } else return route.name === useLocaleRoute()({ ...props.to })?.name;
    });
  return found?.children.some((child) => child.name === useRoute().name);
});
</script>
```

**Comment by kalnode** [comment]
The posted SO solution _does_ work; no frankenstein code needed.

Make sure your files are correct, ie:

```
/pages
  /posts
    [postId].vue
    index.vue
  posts.vue
```

Yes you will have a `posts.vue` living outside of the posts folder; that's the way it works. 

The file posts.vue acts as your "catch-all"; in it you simply have:

```
<template>
    <NuxtPage />
</template>
```

**Comment by danielroe** [comment]
@the94air This is an issue for vue-router - not a bug in Nuxt or something Nuxt could even implement. It was a decision vue-router took [for reasons](https://router.vuejs.org/guide/migration/#removal-of-the-exact-prop-in-router-link).

I'm not sure why you posted on this issue to tell us you'll never use vue-router or Nuxt again (unless you just wanted to make us feel bad?), but I wish you the very best 🙏 ❤

**Comment by the94air** [comment]
@danielroe Sorry, Daniel. There was a typo. I just wanted to express the frustrations I run into when using this feature in both nuxt/vue-router but it came out really wrong (due to the typo). Sorry again. You guys rocks.

**Comment by luksak** [comment]
I came up with this pretty generic approach, which also works for catch-all routes:

```vue
<script setup lang="ts">
interface MenuItem {
  path: string
  title: string
}

interface Props {
  items?: MenuItem[]
  modifier: string
}

defineProps<Props>()

const route = useRoute()
</script>

<template>
  <NuxtLink
    v-for="(item, i) in items"
    :key="i"
    :to="item.path"
    :class="{
      'router-link-active': route.path.startsWith(item.path),
    }"
  >
    {{ item.title }}
  </NuxtLink>
</template>
```
