### ISSUE TITLE
How do I add a script via defineNuxtConfig, but have this script only included in dev (localhost)?

### ISSUE THREAD

**Issue by VincEnterprise** [nuxt/nuxt#20332]
### Describe the feature

I'm trying to load the following script but I only want it to be added when I'm in dev mode, and not included in the final build:

```export default defineNuxtConfig({
    app: {
        head: {
            script: [
                { src: "https://kendo.cdn.telerik.com/2022.3.913/js/kendo.all.min.js" },
            ],
        },
    },
```
    
Is this achievable with Nuxt? I've tried adding the scripts with a custom nuxt plugin but unfortunately this doens't work for my use case as these scripts have to be loaded before everything else.

Thanks in advance

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by smilosevic** [comment]
This should help you

`{ src: process.env.NODE_ENV === 'development' ? 'https://kendo.cdn.telerik.com/2022.3.913/js/kendo.all.min.js' : undefined }`

**Comment by VincEnterprise** [comment]
Thanks, this works
