### ISSUE TITLE
Nuxt 3.4.1: nuxtApp.vueApp.config.errorHandler is undefined when use plugin

### ISSUE THREAD

**Issue by YIngChenIt** [nuxt/nuxt#20342]
### Environment

Nuxt 3.4.1

### Reproduction

https://stackblitz.com/edit/github-wfungx?file=plugins/my-plugin.ts

### Describe the bug

nuxtApp.vueApp.config.errorHandler is undefined when use plugin

**Comment by danielroe** [comment]
It is something you can set. Here's an example: https://nuxt.com/docs/getting-started/error-handling#errors-during-the-vue-rendering-lifecycle-ssr-spa
