### ISSUE TITLE
How to exit process without return?

### ISSUE THREAD

**Issue by tenfei4** [nuxt/nuxt#20357]
**example /api/test.ts**
import fun from '@/server/fun'
export default defineEventHandler(async e => {
    fun.result(e);
    console.log('i hope not execute this.')
    //return e.context.json;
});

**/server/fun.ts**
const result=(e){
        e.node.res.writeHead(200,{ 'Content-Type': 'application/json','Charset':'utf8'});
        e.node.res.end(JSON.stringify(e.context.json));
}
export default {result}

I hope to exit process not use return. However, after the content is output and the subfunction is called, the subsequent code will still be executed. How can I make the subsequent code not execute.

**Comment by danielroe** [comment]
Please do not open duplicate issues.

Let's track in https://github.com/nuxt/nuxt/discussions/20355
