### ISSUE TITLE
Having trouble upgrading to v3.4.1 from 3.0.0-rc8

### ISSUE THREAD

**Issue by preetmishra** [nuxt/nuxt#20359]
### Environment

- Operating System: `Darwin`
- Node Version:     `v19.4.0`
- Nuxt Version:     `3.4.1`
- Nitro Version:    `2.3.3`
- Package Manager:  `npm@9.2.0`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `modules`, `build`, `vite`, `nitro`, `typescript`, `buildModules`, `css`, `app`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.5`
- Build Modules:    `@pinia/nuxt@0.4.8`

### Describe the bug

I'm trying to upgrade Nuxt to 3.4.1. I'm getting the following error in the console while running the server.

```
ERROR  Cannot overwrite a zero-length range – use appendLeft or prependRight instead
```

I have tried looking online but couldn't find anything related at all. In addition, the error message doesn't have any context or additional debugging information.

I would greatly appreciate any pointers to debug my issue further. Please let me know if any other information is required.

### Additional context

Discussed in https://github.com/nuxt/nuxt/discussions/20334

**Comment by danielroe** [comment]
This is an upstream bug with rollup that's already fixed, and not related to Nuxt. Try refreshing your lockfile.

**Comment by preetmishra** [comment]
I tried refreshing the lockfile but it didn't work. I don't have `rollup` in my dependencies directly. I tried putting the latest rollup version in `resolutions` but that didn't work either. Any pointers on what should I look into?

**Comment by danielroe** [comment]
What package manager are you using? What does your package.json look like?

**Comment by preetmishra** [comment]
I'm using `npm`.

```json
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "generate": "nuxt generate",
    "preview": "nuxt build && nuxt preview"
  },
  "devDependencies": {
    "@cypress/code-coverage": "^3.10.0",
    "@nuxtjs/eslint-config-typescript": "^10.0.0",
    "@nuxtjs/tailwindcss": "^5.3.1",
    "cypress": "^12.7.0",
    "eslint": "^8.21.0",
    "nuxt": "3.4.1",
    "typescript": "^4.7.4",
    "vite-plugin-istanbul": "^4.0.0-rc.1",
    "vue-tsc": "^0.40.1"
  },
  "dependencies": {
    "@fullstory/browser": "^1.6.2",
    "@pinia/nuxt": "^0.4.0",
    "@sentry/tracing": "^7.15.0",
    "@sentry/vue": "^7.15.0",
    "@sindresorhus/slugify": "^2.2.0",
    "@tailwindcss/line-clamp": "^0.4.2",
    "@vee-validate/rules": "^4.6.6",
    "date-fns": "^2.29.2",
    "debounce": "^1.2.1",
    "html2pdf.js": "^0.10.1",
    "lodash.clonedeep": "^4.5.0",
    "lodash.isequal": "^4.5.0",
    "pinia": "^2.0.18",
    "vee-validate": "^4.6.6",
    "vue": "^3.2.37",
    "vue-tippy": "^6.0.0-alpha.63",
    "vue-toastification": "^2.0.0-rc.5",
    "vue3-click-away": "^1.2.4",
    "vue3-datepicker": "^0.3.4",
    "yup": "^0.32.11"
  },
  "resolutions": {
    "rollup": "3.20.1"
  }
}
```

**Comment by manniL** [comment]
@preetmishra You might want to use [`overrides`](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides) when using `npm`.

But as @danielroe said, removing package-lock.json and regenerate it should suffice.

**Comment by preetmishra** [comment]
@manniL Thanks! I tried regenerating the lock file but that didn't work. I replaced `resolutions` with `overrides` right now as well. No luck.

**Comment by danielroe** [comment]
You might try upgrading your version of node then. Overrides is a new feature of npm.

Otherwise, we'd really need a reproduction to help further

**Comment by preetmishra** [comment]
I tried upgrading `npm`. No luck still. I'll try to build a reproduction environment.

**Comment by preetmishra** [comment]
I removed everything from the project and only kept `index.vue` in `/pages` with a simple "Hello World" text, and it worked. I now know that there's something wrong in our code for sure. 

I'm getting `[vite-node] [plugin:nuxt:pages-macros-transform] [VITE_ERROR] /pages/admin/types.ts?macro=true` in the browser. I'm looking further.

**Comment by danielroe** [comment]
Is there a chance you have a file in your pages directory that's not a page?

**Comment by preetmishra** [comment]
Ah, got it! I have a file `types.ts`. Removed it. No more errors! 😅

**Comment by preetmishra** [comment]
This file got added two days ago and we didn't realize it was in the `/pages` directory (where it's not supposed to be).

**Comment by preetmishra** [comment]
We could probably have a check for this and throw a warning whenever somebody puts a file that's not a page in `/pages` directory. I don't know how complex it would be and but I am interested in contributing. Are you open to a pull request to address this?

**Comment by danielroe** [comment]
Absolutely ❤️

Feel free to DM me if that would be helpful.

**Comment by preetmishra** [comment]
Fantastic! I'll try looking into the codebase initially. Where do you prefer a DM? Is there a community for Nuxt? Or your personal Twitter?

**Comment by danielroe** [comment]
There's a Discord: https://discord.nuxtjs.org - and a channel, #contributing. Or a DM, or my Twitter is fine too!

**Comment by preetmishra** [comment]
Thanks, Daniel! I have created a pull request.
