### ISSUE TITLE
when upgrade nuxt from v3.2 to v3.4.1 found a debug.

### ISSUE THREAD

**Issue by tenfei4** [nuxt/nuxt#20368]
### Environment

Node.js v18.6.0
Nuxt v3.4.1

### Reproduction

file:///D:/node/nuxt_app/.output/server/chunks/node-server.mjs:7557
const parserCache$2 = new LRU({
                      ^
TypeError: LRU is not a constructor
    at file:///D:/node/nuxt_app/.output/server/chunks/node-server.mjs:7557:23
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:541:24)
    at async loadESM (node:internal/process/esm_loader:83:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)

Node.js v18.6.0

### Describe the bug

when upgrade nuxt from v3.2 to v3.4.1 white nuxt upgrade --force.
in dev mod.all ok.
when build,found this error.

**Comment by tenfei4** [comment]
when execute **node .output/server/index.mjs** found this error.

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by tenfei4** [comment]
> Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

sorry,that is in company local network.

**Comment by tenfei4** [comment]
in v3.2.x its all ok.just only upgrade to v3.4.1 with **nuxt upgrade --force** then build project and run **node .output/server/index.mjs** found error.

**Comment by danielroe** [comment]
I don't need exactly your company's code, but just a minimal sandbox that reproduces the error. Check the link for some advice on how to do this.

**Comment by tenfei4** [comment]
this,**[](https://stackblitz.com/edit/github-ukyx3h)**

**Comment by danielroe** [comment]
cc: @pi0 - might be an issue with hoisting in nitro

**Comment by danielroe** [comment]
If you're still experiencing this, would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏

If it only recurs with Nuxt, let me know and I'll reopen it here.
