### ISSUE TITLE
My project with nuxt 3 is not loading on the server side

### ISSUE THREAD

**Issue by dev02iggy** [nuxt/nuxt#20371]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `yarn@1.22.10`
- Builder:          `vite`
- User Config:      `ssr`, `app`, `css`, `windicss`, `build`, `buildModules`, `modules`, `experimental`, `components`, `vite`, `runtimeConfig`, `vueuse`
- Runtime Modules:  `@pinia/nuxt@0.4.7`, `@vueuse/nuxt@9.13.0`, `nuxt-windicss@2.6.0`, `nuxt-icon@0.3.3`, `@nuxt/image-edge@1.0.0-28002839.c6a7c9b`
- Build Modules:    `@nuxtjs/google-fonts@2.0.0`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-x6dths?file=layouts/default.vue

The reproduction is the same as the previous problem that opened here, because as I still use Nuxt 2, my project in Nuxt 3 doesn't change almost anything.

### Describe the bug

I believe that the project is not running on the server. Everything looked good, but now discover something. I still have projects in Nuxt 2 and that's why I'm working on 3 calmly. Today I went to do a test to get the headers and I ended up facing a code with nothing on the server side. I did the test in Postman. While in 2 the html comes, in 3 nothing comes as follows the images there.
Nuxt 2: 
<img width="1002" alt="Captura de Tela 2023-04-18 às 15 02 37" src="https://user-images.githubusercontent.com/83841469/232864923-4cfdeaf8-5e4d-4c11-a6aa-a53df7fb02ce.png">

Nuxt 3: 
<img width="1016" alt="Captura de Tela 2023-04-18 às 14 52 22" src="https://user-images.githubusercontent.com/83841469/232864997-9e773af7-f7a8-42ee-9198-c243a52216ac.png">

To be more sure, I did a basic test on this simulator https://www.ranktracker.com/pt-br/serp-simulator/ and got responses from Nuxt 2, but none from Nuxt 3.

### Additional context

No code works in process.server. I know this is horrible for the project, especially for Google. I would like you to help me.

**Comment by dev02iggy** [comment]
I created a new project and it runs normally on the server. I put the same nuxt.config.js in both. So I updated Nuxt to 3.4.1, but it still doesn't run on the server. The two projects do not have all the same packages, and the new one only has the most necessary packages. I'll try to see if there is any library that is causing this error

**Comment by danielroe** [comment]
Would you explain what you do not think is working in the reproduction? It seems to be server rendering all its HTML correctly.

**Comment by dev02iggy** [comment]
@danielroe I understood why. I usually use a variable to know when to render the page after the API data has arrived and I send it to each corresponding variable. In 2 it used fetch() to render the function it fetched with Axios. So still on the server, I already gave permission for the page to render. But in Nuxt 3, in my mind, it's not right to do this without being in a lifecycle, because when I do it openly in setup() sometimes the data doesn't come. It's just that lifecycles are only called on the client side which caused this problem.

Is there any way for me to work with the API data on the server and only allow the page to be rendered when all the data is managed. An example is I manage to Vuex or Pinia before the client side runs.

**Comment by danielroe** [comment]
Indeed it is possible. You can use `await` with Nuxt's data fetching composables to achieve this.

**Comment by dev02iggy** [comment]
@danielroe  thanks. When I started testing last year async was giving some errors with setup() and so I left it aside and tried to do it another way. I noticed that now it works better. I'm going to change all my code structure. Thank you again :)

**Comment by dev02iggy** [comment]
@danielroe You can tell me why useAsyncData() or useLazyAsyncData() on one page returns data, pending, error and refresh, but on another page the data comes straight through with nothing around it.
