### ISSUE TITLE
defineNuxtConfig is not defined  

### ISSUE THREAD

**Issue by moe-abbasi** [nuxt/nuxt#20377]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.18.1`
- Nuxt Version:     `2.15.0`
- Nitro Version:    `2.3.3`
- Package Manager:  `yarn@1.22.19`
- Builder:          `webpack`
- User Config:      `pages`, `build`, `css`, `plugins`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

 **don't have a minimal reproduction link but the issue is pretty self explanatory!
This is my package.json:**
`
{
  "name": "nuxt-app",
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@types/node": "^18",
    "nuxt": "^3.4.1"
  }
}
`
and you see my environment above which display different nuxt versions!

### Describe the bug

I create a nuxt app by running `npx nuxi init [project-name]`. When the project is created I see `"nuxt": "^3.4.1",` in my package.json. But as you can see in my environment when I run `npx nuxi info` it says my nuxt version is `Nuxt Version:     2.15.0` which makes me a lot of problems such as getting the error `defineNuxtConfig is not defined` is not defined in my `nuxt.config.ts`
What is wrong here?

### Additional context

My application is pretty empty since it was created brand new but just in case this is my tsconfig.json:
`{
  // https://nuxt.com/docs/guide/concepts/typescript
  "extends": "./.nuxt/tsconfig.json"
}
`

**Comment by aminimalanimal** [comment]
> Would you check to see if you have a `node_modules` folder in a parent directory. For example, you might have globally installed `nuxt@2`?

I had the same issue and deleting `node_modules` from a parent directory fixed the issue. Curious as to whether or not there's a solution to this—it seems like odd behavior to have a folder outside of my project that affects it.

**Comment by Jaystar-Bee** [comment]
I'm also having this issue. So i was working on this project that uses nuxt 3.2.0. I tried installing the the vuedatepicker and i got this defineNuxtConfig not found error. Have deleted the node_module folder, re-clone the app but I'm still having same issue

**Comment by jalamanderman** [comment]
I also have the same issue.

**Comment by so1ve** [comment]
Probably a jiti bug?

**Comment by Jaystar-Bee** [comment]
@jalamanderman You might this issue again when installing a new package, try Uninstalling nuxt 2 globally on your machine. That would fix the problem totally.

**Comment by Triloworld** [comment]
Issue is in global scope library what I can re-create
I was having: `typescript@4.8.4` that remove by command `npm -g remove typescript` resolve issue.

**Comment by 1714080902120** [comment]
I just install some dependences which has their own `nuxt.config.ts`，and they are using auto import. I guess the issue i met comes from here. Is there any solution?

**Comment by tdebooij** [comment]
FYI I had this issue with pnpm too, clearing the pnpm cache fixed it for me

```
# Clear global pnpm cache
pnpm store prune

# Remove global pnpm store completely
rm -rf "$(pnpm store path)"

# Clear local pnpm cache
rm -rf node_modules
```
