### ISSUE TITLE
`keepalive:true` in `definePageMeta` doesn't work in right way

### ISSUE THREAD

**Issue by gyhyfj** [nuxt/nuxt#20378]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.4.1
- Nitro Version:    2.3.3
- Package Manager:  pnpm@8.2.0
- Builder:          vite
- User Config:      modules, vite, css, imports, pinia, app, ignore, telemetry, appConfig, devServer, nitro
- Runtime Modules:  @nuxtjs/tailwindcss@6.6.6, @pinia/nuxt@0.4.8, @pinia-plugin-persistedstate/nuxt@1.1.1, @element-plus/nuxt@1.0.4
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-ugcjd1?file=pages/index.vue

### Describe the bug

`keepalive:true` in `definePageMeta`  cannot keep values in page and can always trigger `onMounted`
but can trigger `onDeactivated`

**Comment by DamianGlowala** [comment]
See why this doesn't work for you https://github.com/nuxt/nuxt/issues/15214#issuecomment-1397374389 and how you can make it work https://github.com/nuxt/nuxt/issues/15255#issuecomment-1397374998.

**Comment by gyhyfj** [comment]
Thank you, it's really confusing
