### ISSUE TITLE
Can I change the "exclude" setting in the "Keepalive" configuration to use route URLs instead of component names?

### ISSUE THREAD

**Issue by jskim82** [nuxt/nuxt#20386]
### Describe the feature

Is it possible to use URLs instead of component names in the "exclude" setting, as shown in the following source code?

```html
<script setup lang="ts">
const kk = {
  max: 10,
  exclude: ['/pageUrl']
}
</script>

<template>
  <div>
    <el-config-provider :locale="locale">
      <NuxtLayout>
        <NuxtPage :keepalive="kk" />
      </NuxtLayout>
      <modals-container />
    </el-config-provider>
  </div>
</template>
----------------

<template>
  <keep-alive exclude="['/home', '/about']">
    <router-view />
  </keep-alive>
</template>

**Comment by danielroe** [comment]
There's a bigger issue with KeepAlive and exclude/include that we can track in https://github.com/nuxt/nuxt/issues/15214.

Having said that, how keepalive works is not based on route but on component name. Check out the full docs at https://vuejs.org/guide/built-ins/keep-alive.html#keepalive
