### ISSUE TITLE
extractCSS option outputs stylesheets in both <style> tags and separate css files

### ISSUE THREAD

**Issue by juliendargelos** [nuxt/nuxt#20393]
### Environment

Nuxi 3.4.1
        
RootDir: /home/projects/github-wyh968/.output/public
Nuxt project info:

------------------------------
- Operating System: Linux
- Node Version: v16.14.2
- Nuxt Version: 3.4.1
- Nitro Version: 2.3.3
- Package Manager: npm@7.17.0
- Builder: vite
- User Config: -
- Runtime Modules: -
- Build Modules: -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-wyh968

### Describe the bug

When using the `extractCSS` option:

```typescript
export default defineNuxtConfig({
  webpack: {
    extractCSS: true
  }
})
```

Running `nuxt generate` outputs all component stylesheets both directly in the head tag of each html files, and as separate css files (see the reproduction above):

src/pages/index.vue
```vue
<template>
  <!-- ... -->
</template>

<style scoped lang="scss">
  .home {
    background: $turquoise;
  }
</style>
```

.output/public/index.html
```html
<!DOCTYPE html>
<html>
  <head>
    <!-- ... !-->
    <style>
      .home[data-v-a9afb481] {
        background: #40e0d0
      }
    </style>
  </head>
  <body>
    <!-- ... !-->
  </body>
</html>
```

.output/public/_nuxt/index.1ed677da.css
```css
.home[data-v-a9afb481]{background:#40e0d0}
```

Even if the stylesheets appear twice in the bundle, the generated css files are not linked anywhere and left unused.
Global stylesheets included using the nuxt `css` option don't have this problem and are only extracted once as a separate css file.

### Expected behavior

When setting the `extractCSS` option to `true`, all stylesheets should be extracted as separate css files, not be duplicated, and be linked in the corresponding html files.

**Comment by danielroe** [comment]
You must install `@nuxt/webpack-builder` and set `builder: 'webpack'` to use webpack.

**Comment by juliendargelos** [comment]
Do you mean css cannot be extracted using vite ?

**Comment by danielroe** [comment]
Vite extracts CSS by default here. You can disable inlining by setting `experimental.inlineSSRStyles` to false.
