### ISSUE TITLE
Module parse failed: Unexpected character '#' (1:0) – Please help understand this warning

### ISSUE THREAD

**Issue by katerlouis** [nuxt/nuxt#20407]
### Environment

  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 4.98 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 112.0.5615.49
    Firefox: 109.0.1
    Safari: 16.3
  npmPackages:
    nuxt: ^2.16.1 => 2.16.1

### Reproduction

All I can take from that warning message is that it has to do something with my `SvgRaw` component. But it works as expected without any issues. Here's the component:

```vue
<template>
  <div class="svg-raw" v-html="raw" />
</template>

<script>
export default {
  name: 'SvgRaw',

  props: {
    // path to svg relative to ~/assets/
    path: {
      type: String,
      required: true,
    },
  },

  computed: {
    raw() {
      return require(`~/assets/${this.path}?raw`);
    },
  },
};
</script>

<style lang="scss" scoped>
.svg-raw {
  ::v-deep svg {
    display: block;
  }
}
</style>
```

### Describe the bug

![image](https://user-images.githubusercontent.com/1983382/233302469-31bca975-d73d-450b-afcc-c552d4ce72be.png)

### Additional context

I have `@nuxtjs/composition-api` installed (nuxt-bridge is not an option for us, we've tried–)

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by katerlouis** [comment]
@danielroe Unfortunately I can't– this is happening in a rather big project and I have no idea what this warning means or where it comes from;
