### ISSUE TITLE
Test files causes errors in component directories with Tailwind module

### ISSUE THREAD

**Issue by pitcher-maarten** [nuxt/nuxt#20404]
### Environment

- Operating System: Darwin
- Node Version:     v16.14.0
- Nuxt Version:     3.4.1
- Nitro Version:    2.3.3
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      srcDir, buildDir, nitro, css, components, runtimeConfig, imports, modules, i18n, tailwindcss, pinia, build
- Runtime Modules:  nuxt-vitest@0.6.10, @nuxtjs/i18n@8.0.0-beta.11, @nuxtjs/tailwindcss@6.6.6, @pinia/nuxt@0.4.8, @vueuse/nuxt@10.0.2, @formkit/nuxt@1.0.0-beta.9-f64c966, nuxt-icon@0.3.3
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-huekcx?file=nuxt.config

### Describe the bug

We prefer to place our component .test files right into the components directory to have structure, overview and we can directly see which component does not have a test. However when enabling the **nuxt/tailwindcss** module it has some problems, probably because the module is scanning all of our files and also want to use the .test files.

The errors when enabling tailwind module.
```
node_modules/vitest-environment-nuxt/dist/utils.mjs:4:46: ERROR: Could not resolve "#imports"
node_modules/vitest-environment-nuxt/dist/utils.mjs:5:21: ERROR: Could not resolve "#build/root-component.mjs"
```

### Additional context
```
yarn dev
```
_No response_

**Comment by danielroe** [comment]
Probably you need to update the glob scanning patterns that Tailwind uses. If that doesn't resolve things for you, then would you raise an issue at https://github.com/nuxt-modules/tailwindcss instead?

**Comment by pitcher-maarten** [comment]
@danielroe you were right about the glob pattern. 
Should I make a PR to exclude test files (.spec,.test) within the [layerPaths configuration](https://github.com/nuxt-modules/tailwindcss/blob/main/src/module.ts#L29)? 

```
`${srcDir}/components/**/!(*.{test,spec}).{vue,js,ts}`,
```

**Comment by danielroe** [comment]
Makes sense to me!

**Comment by patriciakrupa** [comment]
> @danielroe you were right about the glob pattern. Should I make a PR to exclude test files (.spec,.test) within the [layerPaths configuration](https://github.com/nuxt-modules/tailwindcss/blob/main/src/module.ts#L29)?
> 
> For example:
> 
> ```
> `${srcDir}/components/**/!(*.{test,spec}).{vue,js,ts}`,
> ```

Greetings, 
i have the same "errors" with current versions of @nuxtjs/tailwindcss (6.10.1) and nuxt-vitest (0.11.5), how were you able to fix this manually ? 

BR
