### ISSUE TITLE
Nuxt dev server with https is broken on Node 18+

### ISSUE THREAD

**Issue by Atinux** [nuxt/nuxt#20435]
Reproduction:

```bash
npx nuxi init@latest my-app
cd my-app
pnpm i
npx nuxi dev --https
```

![CleanShot 2023-04-21 at 10.47.33@2x.png](https://volta.s3.fr-par.scw.cloud/Clean_Shot_2023_04_21_at_10_47_33_2x_83c54a9907.png)

I also notice that we don't support the `devServer.https: true` option, any reason for that?

**Comment by Atinux** [comment]
Actually the `devServer.https: true` option works but display a TS error:
![CleanShot 2023-04-21 at 10.54.39@2x.png](https://volta.s3.fr-par.scw.cloud/Clean_Shot_2023_04_21_at_10_54_39_2x_53b0a27386.png)

**Comment by sshwy** [comment]
facing the same bug

**Comment by danielroe** [comment]
This is now working for me.

**Comment by pi0** [comment]
Worth to mention, the final fix for this is that Nuxi CLI uses an internal `http` server + public `https` server which proxies to the internal one and vite dev server directly uses internal server.

In case of using `--https --no-fork`, we would need some Node.js flags to allow unauthorized keys (written in CLI output log)
