### ISSUE TITLE
Package import specifier "#internal/nitro" is not defined in package

### ISSUE THREAD

**Issue by anderslutzhoft** [nuxt/nuxt#20438]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.4.1`
- Nitro Version:    `2.3.3`
- Package Manager:  `npm@8.19.3`
- Builder:          `vite`
- User Config:      `modules`, `ionic`
- Runtime Modules:  `@formkit/nuxt@0.16.4`, `@nuxtjs/tailwindcss@6.6.6`, `@nuxtjs/supabase@0.3.5`, `nuxt-icon@0.3.3`, `@vueuse/nuxt@10.0.2`, `@nuxtjs/ionic@0.10.0`
- Build Modules:    `-`

### Reproduction

When running npm run generate using the Ionic VScode plugin to build and serving the files.

### Describe the bug

500
Package import specifier "#internal/nitro" is not defined in package **removed**/package.json imported from **removed**/.nuxt/dist/server/server.mjs

at new NodeError (node:internal/errors:400:5)
at importNotDefined (node:internal/modules/esm/resolve:350:10)
at packageImportsResolve (node:internal/modules/esm/resolve:777:9)
at moduleResolve (node:internal/modules/esm/resolve:932:16)
at defaultResolve (node:internal/modules/esm/resolve:1153:11)
at nextResolve (node:internal/modules/esm/loader:163:28)
at ESMLoader.resolve (node:internal/modules/esm/loader:842:30)
at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
at ModuleWrap. (node:internal/modules/esm/module_job:77:40)
at link (node:internal/modules/esm/module_job:76:36)

### Additional context

When I run npm run dev everything works fine, also if I use Ionic to run without building first.
As mentioned, Ionic uses npm run generate as specified in package.json: "ionic:build": "npm run generate".

### Logs

```shell-script
From Ionic Output
[npm] [nuxt] [request error] [unhandled] [500] Package import specifier "#internal/nitro" is not defined in package /Users/anderslutzhoft/Webapps/caloryai/package.json imported from /Users/anderslutzhoft/Webapps/caloryai/.nuxt/dist/server/server.mjs
[npm]   at new NodeError (node:internal/errors:400:5)  
[npm]   at importNotDefined (node:internal/modules/esm/resolve:350:10)  
[npm]   at packageImportsResolve (node:internal/modules/esm/resolve:777:9)  
[npm]   at moduleResolve (node:internal/modules/esm/resolve:932:16)  
[npm]   at defaultResolve (node:internal/modules/esm/resolve:1153:11)  
[npm]   at nextResolve (node:internal/modules/esm/loader:163:28)  
[npm]   at ESMLoader.resolve (node:internal/modules/esm/loader:842:30)  
[npm]   at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)  
[npm]   at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)  
[npm]   at link (node:internal/modules/esm/module_job:76:36)
```

**Comment by anderslutzhoft** [comment]
I'm very new to development and issue reporting, so I apologize if my report is lacking. Please let me know if any additional information is needed!

I've spent a few hours searching the internet for reports on this; I found only a few, but all of them should have been fixed with earlier updated. Thus I'm experiencing this now with the latest deps, I was hoping to get some help here.

**Comment by anderslutzhoft** [comment]
I've also made this repo to reproduce: https://github.com/anderslutzhoft/serverless-test

**Comment by danielroe** [comment]
Thank you! I can't reproduce with your repo when running `npm run generate` or `ionic build`: see https://stackblitz.com/edit/github-bj8gbc?file=package.json.

**Comment by martijnhartlief** [comment]
We have the same issue on MacArm **without** ionic.

When we locally build a project the dev runner crashes:

```
[nuxt] [request error] [unhandled] [500] Package import specifier "#internal/nitro" is not defined in package ***/package.json imported from ***/.nuxt/dist/server/server.mjs
  at new NodeError (node:internal/errors:399:5)  
  at importNotDefined (node:internal/modules/esm/resolve:350:10)  
  at packageImportsResolve (node:internal/modules/esm/resolve:777:9)  
```

We have this issue only on Mac (ARM?), 
Linux machines don't show this error for us.

Maybe not related, but isn't it weird that nuxt imports dist files? Or is the dist server shared for the dev and build?

**Comment by Lphal** [comment]
> Thank you! I can't reproduce with your repo when running `npm run generate` or `ionic build`: see https://stackblitz.com/edit/github-bj8gbc?file=package.json.

In this reprocuce, first I exec `npm run dev`, it works. Then I exec `npm run build`, I find the development process will be affected and the browser will show `500` Error.

<img width="1518" alt="image" src="https://github.com/nuxt/nuxt/assets/37396453/888a3a70-b74d-483d-be98-910497720e37">

**Comment by danielroe** [comment]
Yes, currently we do not support running a build _while_ running a dev server as they share the same output directory. We plan to allow this, however; let's track in https://github.com/nuxt/nuxt/issues/14607.
