### ISSUE TITLE
Fake [Vue warn]: Hydration text mismatch with nuxi dev

### ISSUE THREAD

**Issue by learntheropes** [nuxt/nuxt#20437]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.2
- Nitro Version:    2.3.3
- Package Manager:  npm@8.6.0
- Builder:          vite
- User Config:      meta, routeRules, runtimeConfig, pages, css, components, modules, content, i18n
- Runtime Modules:  @nuxt/content@2.6.0, @nuxtjs/i18n@8.0.0-beta.11
- Build Modules:    -
------------------------------

### Reproduction

A minimal reproduction is not possible because it requires to update the repo to reproduce.

### Describe the bug

When developing, every time I make a change, the preview reloads showing a fake `[Vue warn]: Hydration text mismatch`

If I stop `nuxi dev`, delete the `/.nuxt` folder and restart `nuxi dev`, the warning disappears. Delete `/.nuxt` is not always necessary, but it is necessary to restart `nuxi dev`.

What I'm actually doing is to ignore the warning and restart as described, before `git commit`, to make sure the warning is fake.

It seems to me that the Client is showing as rendering the previous version (before saving the change) and the Server the new one.

Is this the expected behavior? If so, it's really inconvenient. 

### Logs

```shell-script
[Vue warn]: Hydration text mismatch:
- Client: "<OMITTED>"
- Server: "blog" 
  at <NuxtLink to="<OMITTED>" > 
  at <MerchantProfile title="<OMITTED>" description="<OMITTED>" image="me.jpg"  ... > 
  at <Body> 
  at <Html lang="en-US" dir="ltr" > 
  at <Default > 
  at <LayoutLoader key="default" name="default" hasTransition=false > 
  at <FragmentWrapper > 
  at <NuxtLayout> 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouteProvider key="/" routeProps= {Component: {…}, route: {…}} pageKey="/"  ... > 
  at <FragmentWrapper > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <App key=3 > 
  at <NuxtRoot>
```
```

**Comment by learntheropes** [comment]
I investigated a bit farther, because I suspected the issue was showing only when updating the `/content` folder because I'm using `@nuxt/content`, but is not.

**Comment by manniL** [comment]
No, this is not intended. A reproduction + instructions how to trigger the problem would be appreciated though 😋

**Comment by tdekoning** [comment]
@manniL (cc @danielroe ) here you go https://stackblitz.com/edit/github-45sxb2-8etcop?file=app.vue,package.json,nuxt.config.ts .

To reproduce, follow these steps:
- run the example
- Open the console so you can see errors in the client
- Change the value that goes into the ref to a different string value.
- Refresh the frame of the client using the refresh button of stackblitz
- See that you now get a hydration mismatch error in the console (you can also see the content jump)

![image](https://github.com/nuxt/nuxt/assets/1109781/46a30630-668b-4f93-aad4-e8f6db1b42a6)

**Comment by tdekoning** [comment]
I must say that this bug is really hurting the developer experience. Every change you make requires a full Nuxt server reboot, because Nuxt keeps serving the old version

**Comment by manniL** [comment]
@tdekoning Apparently the route rules set cause the issue. As a workaround, you can remove them or set them only for production (via `routeRules: { $production: { '**' : /*...*/ {} } }`

**Comment by danielroe** [comment]
Yes, as Alex said - when you are setting caching route rules or other rules you don't want to apply in development, you can use the `$production` and `$development` keys in `nuxt.config` to set config conditionally.
