### ISSUE TITLE
Sharing global lazy components from #20259 blow ups `entry` file

### ISSUE THREAD

**Issue by logotip4ik** [nuxt/nuxt#20439]
### Environment

- Operating System: Linux
- Node Version:     v16.17.0
- Nuxt Version:     3.4.2
- Nitro Version:    2.3.3
- Package Manager:  pnpm@7.1.0
- Builder:          vite
- User Config:      sourcemap, modules
- Runtime Modules:  nuxt-icon@0.3.3
- Build Modules:    -

_note:_ same on my windows machine with yarn berry and 18.13.0 node

### Reproduction

https://codesandbox.io/p/sandbox/cocky-darwin-4sog1x

1. Try building with global components (`nuxt-icon` module for example). Despite using two lazy components, there is only one file emitted (`toasts`). Also notice `entry` file is `154kb`
2. Comment out `nuxt-icon` module and run build again. Two files for two separate lazy components emitted (`navbar` and `toasts`) and `entry` leaned from `154kb` to `132kb`

### Describe the bug

https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/components/templates.ts#L32

Everything is about this line. If you use in-file components definitions (as was on v3.4.1), all looks good and as it should be. But if you **only import** `lazyGlobalComponents` from `#componets`, `entry` file will grow up, but chunks for lazy components are still there. For example, on my local project i am using `tiptap` and as a result, `entry` file grew from `180kb` to `497kb`. Then, if you use `lazyGlobalComponents` in for loop, `entry` size remains the same `497kb`, but chunks for lazy components are gone. All lazy components ended up in one chunk -_-

**Comment by salomonsanz** [comment]
same here in 3.4.2, I had to rollback to 3.4.1, entry.js has grown x10

**Comment by agracia-foticos** [comment]
Same issue!!!!

**Comment by tenfei4** [comment]
Same issue too. entry.js has grown >x4.

**Comment by tenfei4** [comment]
> same here in 3.4.2, I had to rollback to 3.4.1, entry.js has grown x3
@salomonsanz  how to rollback from v3.4.2 to v3.2.2

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
