### ISSUE TITLE
experimental.renderJsonPayloads results in missing pinia state on the client

### ISSUE THREAD

**Issue by P4sca1** [nuxt/nuxt#20448]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.14.0`
- Nuxt Version:     `3.4.2`
- Nitro Version:    `2.3.3`
- Package Manager:  `pnpm@8.2.0`
- Builder:          `vite`
- User Config:      `ssr`, `dev`, `experimental`, `vite`, `typescript`, `css`, `sourcemap`, `runtimeConfig`, `modules`, `devtools`, `content`, `colorMode`, `robots`, `htmlValidator`, `routeRules`
- Runtime Modules:  `@nuxt/devtools@0.4.1`, `@nuxt/content@2.6.0`, `@nuxt/image-edge@1.0.0-28020728.5df24eb`, `@nuxtjs/tailwindcss@6.6.6`, `@nuxtjs/color-mode@3.2.0`, `@nuxtjs/robots@3.0.0`, `@nuxtjs/html-validator@1.2.5`, `@pinia/nuxt@0.4.9`, `@vueuse/nuxt@10.1.0`, `nuxt-headlessui@1.1.4`
- Build Modules:    `-`

### Reproduction

I did not manage to create a minimal reproduction yet. I still thought it is useful to open the issue in hope to find others with the same issue.

### Describe the bug

After enabling `experimental.renderJsonPayloads`, I have the problem that the pinia state is different on the client.

Inside a component:
```ts
const auth = useAuthStore() // A pinia store

// server { .... }
// client null
console.log(process.server ? 'server' : 'client', auth.user)
```

This is fixed after disabling `experimental.renderJsonPayloads` again.

### Additional context

`auth.user` is set inside an async store method, which makes a HTTP request.
This store method is called inside a global middleware on the server.

**Comment by manniL** [comment]
This should not happen anymore. Otherwise, please ping with a reproduction 🙏🏻
