### ISSUE TITLE
Manually refresh the page to reload the page

### ISSUE THREAD

**Issue by JanYork** [nuxt/nuxt#20451]
### Environment

nuxt3 、 node18、vue3

### Reproduction

Sorry, I can't reproduce the whole problem and the code is not public

### Describe the bug

There is no problem with the animation when I use nuxtlink for page jump, but when I receive refresh or use CTRL+F5, the page is loaded twice, and the animation is also executed twice, how to solve this problem. The strange thing is that I found that the nuxt official website is refreshed and there is no repeated loading phenomenon. I don't understand it and hope to get an answer.

### Additional context

In a completely new Nuxt3 project, I write a very simple page, but when I manually refresh the page or refresh the page with CTRL+f5, the page is loaded twice because my animation is executed twice

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
