### ISSUE TITLE
NuxtLink retrieves url param only first time

### ISSUE THREAD

**Issue by rubenRP** [nuxt/nuxt#20458]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`, `css`, `nitro`, `ssr`, `i18n`
- Runtime Modules:  `nuxt-vitest@0.6.8`, `@nuxtjs/i18n@8.0.0-beta.10`, `@pinia/nuxt@0.4.7`
- Build Modules:    `-`

### Reproduction

- Create a  list of NuxtLink with a dynamic param. For example: <NuxtLink :to="`/bottle/${item.id}`"> when the item.id (a number) is different in each NuxtLink Item.
- Create a Nuxt page: /pages/bottle/[id].vue and try to catch the id param

### Describe the bug

The id that uses when you click in each NuxtLink is the first you click. Only shows the right id if you reload the page.

### Logs

```shell-script
No errors in console or terminal
```

**Comment by peterroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by rubenRP** [comment]
Yes, this is the project: https://github.com/rubenRP/bodega/tree/nuxt
You can see the links in: https://github.com/rubenRP/bodega/blob/nuxt/components/cellar/TableItem.vue
The Page that doesn't load the id: https://github.com/rubenRP/bodega/blob/nuxt/pages/bottle/%5Bid%5D.vue

**Comment by NicholasDawson** [comment]
@rubenRP would you describe how you fixed this or what the issue ended up being? I'm running into the same issue...

**Comment by rubenRP** [comment]
@NicholasDawson It was a silly error. I was using router-link in that component instead NuxtLink.
