### ISSUE TITLE
useAppConfig() within setTimeout Error

### ISSUE THREAD

**Issue by zeezzh** [nuxt/nuxt#20452]
### Environment

Nuxi 3.4.1  

### Reproduction

any page
![image](https://user-images.githubusercontent.com/13638466/233833658-9e88fe68-7c49-47cc-a293-dea06e738281.png)

### Describe the bug

get error 'nuxt instance unavailable' on server side

**Comment by danielroe** [comment]
You must call it within the right context: see https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables
