### ISSUE TITLE
redirect cause page render twice

### ISSUE THREAD

**Issue by huihuilovekuikui** [nuxt/nuxt#20468]
### Environment

- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.2
- Nitro Version:    2.3.3
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-zefysc?file=pages%2Findex.vue,pages%2Fabc.vue,app.vue

### Describe the bug

when I use definePageMeta , use redirect in index.vue.
redirect to 'abc.vue'
but when I visit index page, which cause abc page render twice
![image](https://user-images.githubusercontent.com/66559869/233936353-c2b1ae56-1994-461a-8b77-83de8eb1ba3d.png)
![image](https://user-images.githubusercontent.com/66559869/233936354-5255aa86-14a8-4328-8e33-8b4db124305a.png)
that is a serious bug, which make my project render twice in all use redirect page.

**Comment by huihuilovekuikui** [comment]
just render twice in server

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/20294.
