### ISSUE TITLE
ERROR when trying to use @parcel/watcher

### ISSUE THREAD

**Issue by tobychidi** [nuxt/nuxt#20469]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.4.2
- Nitro Version:    2.3.3
- Package Manager:  pnpm@8.2.0
- Builder:          vite
- User Config:      experimental, modules
- Runtime Modules:  @unocss/nuxt@0.51.8, @vueuse/nuxt@10.1.0, nuxt-icon@0.3.3, nuxt-swiper@1.1.0, @nuxt/devtools@0.4.1, @nuxt/image-edge@1.0.0-28020728.5df24eb
- Build Modules:    -

### Reproduction

https://codesandbox.io/p/sandbox/reprodution-for-nuxt-3-and-parcel-watcher-06hsj3

### Describe the bug

The new Nuxt update came with performance improvements that included support for @parcel/watcher. I get this error when I use it. My code still runs even with the error.

```
 ERROR  (node:17028) Warning: No such label '[nuxt] builder:parcel:watch' for console.timeEnd() 
```

### Logs

```shell-script
ERROR  (node:17028) Warning: No such label '[nuxt] builder:parcel:watch' for console.timeEnd()
```

**Comment by danielroe** [comment]
This should be already resolved in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/) via https://github.com/nuxt/nuxt/pull/20424, or in the next release.
