### ISSUE TITLE
Error when passing data to options using useFetch + typescript Nuxt3

### ISSUE THREAD

**Issue by Roman-00** [nuxt/nuxt#20467]
### Discussed in https://github.com/nuxt/nuxt/discussions/20466

<div type='discussions-op-text'>

<sup>Originally posted by **Roman-00** April 24, 2023</sup>
I'm trying to pass options to useFetch, but I get an error

<img width="1068" alt="Снимок экрана 2023-04-24 в 13 53 08" src="https://user-images.githubusercontent.com/58338625/233934008-8f219bd4-1cf0-4e89-b090-44db7651fbb7.png">
</div>

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by Roman-00** [comment]
> Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

Repository for accurate investigation of the cause.

https://github.com/Roman-00/iteca.events/tree/testing

"useFetch" is executed on the path pages/index.vue

**Comment by danielroe** [comment]
`mode` should be `no-cors` and not `no-corse`. Apart from that, it seems to work fine.

<img width="986" alt="CleanShot 2023-04-25 at 22 03 44@2x" src="https://user-images.githubusercontent.com/28706372/234403688-562eb92a-3189-4b73-8cf5-b7e214ed418e.png">

**Comment by Roman-00** [comment]
> `mode` should be `no-cors` and not `no-corse`. Apart from that, it seems to work fine.
> 
> <img alt="CleanShot 2023-04-25 at 22 03 44@2x" width="986" src="https://user-images.githubusercontent.com/28706372/234403688-562eb92a-3189-4b73-8cf5-b7e214ed418e.png">
> 
> Note that body should be an object and you do not need to stringify it.

that's right, it should be no-corse.

Please tell me what version of typescript you have in the project?

Everything is absolutely highlighted in red for me :(

**Comment by Roman-00** [comment]
My editor is PhpShtorm

**Comment by Roman-00** [comment]
Yes indeed this is a typescript problem in phpstorm downgrading the version solved the problem :)

Thank you very much! I'm sorry for wasting your time, but I'll be more vigilant.
