### ISSUE TITLE
Using the project generated by nuxi generate to refresh the template structure error problem twice

### ISSUE THREAD

**Issue by xhc-code** [nuxt/nuxt#20462]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.19.0`
- Nuxt Version:     `3.3.3`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@8.19.3`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `imports`, `vite`, `postcss`, `modules`, `ssr`, `app`
- Runtime Modules:  `@pinia/nuxt@0.4.8`, `@element-plus/nuxt@1.0.4`
- Build Modules:    `-`

### Reproduction

can not provide

### Describe the bug

Nuxt configures ssr to true, and then uses the project generated by nuxi generate. After the first screen is loaded, it is normal to navigate to the second-level or third-level page through routing. If you refresh the browser page, this time will cause Vue in the single-file component. The template template structure is inconsistent (the top-level class of the template in the component is inexplicably gone, and then the css variables and styles defined by other pages appear.).
May I ask how this is caused? How to solve it effectively?
Currently, client-only is used for all pages in app.vue to display normally.

**Comment by danielroe** [comment]
Make sure each page has a single root node.

I'm happy to take a look further if you can provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction).
