### ISSUE TITLE
SSR: console.log not working in server api scripts on "pnpm run dev"

### ISSUE THREAD

**Issue by jirehnimes** [nuxt/nuxt#20464]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@8.3.1`
- Builder:          `vite`
- User Config:      `app`, `runtimeConfig`, `ssr`, `dev`, `modules`, `imports`, `vite`, `typescript`, `css`, `build`
- Runtime Modules:  `@pinia/nuxt@^0.4.6`, `nuxt-icon@^0.1.8`
- Build Modules:    `-`
------------------------------

### Reproduction

N/A

### Describe the bug

`console.log`s in `server/api` scripts are not working if ran using `pnpm run dev`. Logs will show if I ran it using `node .output/server/index.mjs` after `pnpm run build`. SSR is enabled.

Nuxt config:

```
export default defineNuxtConfig({
  app: {
    head: {
      title: 'App',
    },
    pageTransition: false,
    layoutTransition: false,
  },
  runtimeConfig: {
    app: {
      APP_ENV: process.env.VITE_APP_ENV,
    },
    APP_ENV: process.env.VITE_APP_ENV,
    APP_PORT: process.env.PORT,
    APP_CLIENT_ID: process.env.VITE_CLIENT_ID,
    APP_REDIRECT_URI: process.env.VITE_REDIRECT_URI,
    API: {
      URL: process.env.VITE_API_URL,
      GRAPHQL: process.env.VITE_API_GRAPH_URL,
    },
    PORT: process.env.PORT || 3002,
  },
  ssr: true,
  dev: true,
  modules: [
    '@pinia/nuxt',
    'nuxt-icon',
  ],
  imports: {
    dirs: ['stores'],
  },
  vite: {
    server: {
      fs: {
        strict: false,
      },
    },
  },
  typescript: {
    shim: false,
  },
});
```

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

I would recommend upgrading your Nuxt and nitro versions first.

**Comment by jirehnimes** [comment]
@danielroe Sure as requested. The specs listed above are from an internal app in my work. I'll create a test app instead for reproduction and will try the latest Nuxt and Nitro versions. Thanks for responding!

**Comment by jirehnimes** [comment]
@danielroe It seems `console.log` is now working on `server/api` scripts on the latest version of Nuxt and Nitro as shown in this sample app I created:

https://stackblitz.com/edit/github-fafu6r?file=app.vue

It logs the message "SERVER API LOG" when the button is clicked, executing a request to the `test` API endpoint.

I think I can close this issue. Thanks!
