### ISSUE TITLE
nuxt3 ssr mode in production, cannot visit the page

### ISSUE THREAD

**Issue by SamWeichangyue** [nuxt/nuxt#20479]
### Environment

Nuxi 3.2.0                                                                                                                                                                         10:05:56
                                                                                                                                                                                          10:05:57
RootDir: /usr/local/CarRentalH5                                                                                                                                                    
Nuxt project info:                                                                                                                                                             10:05:57

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.3`
- Package Manager:  `pnpm@8.3.1`
- Builder:          `vite`
- User Config:      `modules`, `app`, `srcDir`, `css`, `alias`, `routeRules`, `postcss`, `runtimeConfig`, `vite`
- Runtime Modules:  `@vant/nuxt@1.0.0`, `@pinia/nuxt@0.4.7`
- Build Modules:    `-`
------------------------------

### Reproduction

due to the company safety rule and  long time task running in docker, i cannot give a Reproduction link

### Describe the bug

use node .output/server/index.mjs  in docker(4Core4g)

A few hours later(usually in 24hours),i cannot visit the page, then i check the nodejs process status
In 24hours
- cpu used percent: 3.94%
- memery total used: 169MB

![1682390763074](https://user-images.githubusercontent.com/30724369/234162241-a45565a8-43e2-4361-8f5c-7820751742ce.jpg)

this phenomenon happend in last seven days, i am very confused now🤕

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏 It does not need to be your exact code (in fact, ideally it isn't!) but just code necessary to reproduce the issue.
