### ISSUE TITLE
Route params are undefined in layouts/components

### ISSUE THREAD

**Issue by holwech** [nuxt/nuxt#20471]
### Environment

- Operating System: Darwin
- Node Version:     v19.6.0
- Nuxt Version:     3.4.2
- Nitro Version:    2.3.3
- Package Manager:  npm@9.4.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://github.com/holwech/nuxt-3-bug-repro

### Describe the bug

When navigating on a page, for example clicking on a NuxtLink, to a route with a param, the param is undefined for the files located in the layout/component folders. Say we have the following folder structure:

```
pages/index.vue
pages/test-[id].vue
layouts/default.vue
layouts/test.vue
components/test.vue
```

```
// layouts/test.vue
<template>
    <div>
        <test></test>
        <slot></slot> // In the repro, this would be "test-[id].vue
    </div>
</template>
```

If we navigate from `/` to `/test-123` with a NuxtLink and print `route.params.id` in the layout, component and page, only the page is able to access the id inside the script tag. The layout and component will print `undefined`.

Running `console.log(route.params.id)` in `layouts/test.vue`, `components/test.vue` and `pages/test-[id].vue`, outputs the following:

```
layout undefined       [test.vue:4:8](http://localhost:3001/_nuxt/layouts/test.vue)
component undefined    [test.vue:4:8](http://localhost:3001/_nuxt/components/test.vue)
page 123               [test-[id].vue:6:8](http://localhost:3001/_nuxt/pages/test-[id].vue)
```

### Additional context

This issue seems to be similar/related but not certain #20458

**Comment by holwech** [comment]
Here is some [more context](https://stackoverflow.com/questions/76127659/route-params-are-undefined-in-layouts-components-in-nuxt-3) that might be relevant to this issue

**Comment by NILAXY** [comment]
Same here, does anyone know how to fix this?

**Comment by holwech** [comment]
Is there any plan to do something about this bug? To me this seems like a pretty critical bug that breaks core functionality in the Nuxt router and it seems like a lot of people are having problems with it. It's a little worrying that a bug like this can go unfixed for so long.

Sorry if I come off as entitled or harsh, but I don't want to downplay how problematic this bug is for the users having this issue.

**Comment by danielroe** [comment]
When navigating, the first time the component/layout runs _outside_ of `<NuxtPage>`, it will have the _current_ route data. Then, after the route navigation finishes, the route will update. If you add a watcher, you will see this behaviour:

```ts

console.log("id on first load", route.params.id);

watch(() => route.params.id, (id) => {
    console.log("id once route is updated", id);
});
```

This is not a bug; it is needed to make sure that the route is updated in sync with the visible content of the page.

In your case, we don't _display_ the component in the new layout, but because it's being loaded outside the new page, it's still in the 'old' route context.

**Comment by danielroe** [comment]
You're right, a `computed` is the right choice here. Presumably you would also want your component to update when the route changed subsequently. (ie. making the param unreactive in setup is probably not desirable)

**Comment by phunq-0851** [comment]
use `computed` is the best choice.

**Comment by p1xel007** [comment]
Still facing this issue

**Comment by ivan119** [comment]
> Still facing this issue

I lose much time until i found solution, please try 

const route = useRouter().currentRoute.value

const id = route.params.id


for some reason "useRoute().params.id" is cached

**Comment by ricksore** [comment]
Thanks @ivan119 worked the best for me.
