### ISSUE TITLE
useFetch triggers a request on the client side in nested components (using resolveComponent)

### ISSUE THREAD

**Issue by darioferderber** [nuxt/nuxt#20476]
### Environment

------------------------------
- Operating System: Linux
- Node Version:  v18.12.1
- Nuxt Version: 3.4.2
- Nitro Version: 2.3.3
- Package Manager:  npm@8.19.2
- Builder:  vite
- User Config:  components
- Runtime Modules:  -
- Build Modules: -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-6ejkfx?file=pages/variable.vue

### Describe the bug

This issue happens when you use nested ```<component :is="component" />```

If you resolve the parent component with the string - useFetch triggers a request only on the server side and the data is transferred to the client, which is fine.
```ts
const component = resolveComponent('Main');
```

If you resolve the parent component with the variable, everything renders well, but useFech triggers a request both on the server side and the client side
```ts
const name = 'Main';
const component = resolveComponent(name);
 ```
 
Components are registered as global components as it was mentioned [here](https://github.com/nuxt/nuxt/issues/14036#issuecomment-1397340507).

### Additional context

There is an **index.vue** page in the [stackblitz](https://stackblitz.com/edit/nuxt-starter-38tkoc) example where everything works fine, and **variable.vue** which is "broken".

**Comment by darioferderber** [comment]
As I understand, "behind the scenes" you use **defineAsyncComponent** to register the component as an async component and it gets separated into its own chunk ([here](https://stackblitz.com/edit/nuxt-starter-38tkoc?file=components/Main.vue) is an example replacing **resolveComponent** with **defineAsyncComponent** in the previous example).

When the chunk is loaded on the client, data from the useFetch somehow doesn't get transferred although it exists in the payload, and a new request is then triggered.

Here's a [workaround](https://stackblitz.com/edit/nuxt-starter-38tkoc?file=components/Inner.vue), which doesn't seem right 😄

Do you have any other ideas or workarounds on how to achieve this without triggering the request on the client?

**Comment by darioferderber** [comment]
With further "investigation", I concluded that the inner/nested component somehow doesn't hydrate.
I've changed the [asyncData.ts](https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/app/composables/asyncData.ts#L115) and removed ```nuxt.isHydrating``` just to return the payload and everything works as it should, but of course that's not a great idea to do.
```ts
const getCachedData = () => nuxt.payload.data[key] || nuxt.static.data[key]
```
Next, I've tried ```useHydration``` composable, and for some reason it's not auto-imported so you need to import it
```ts
import { useHydration } from '#app';
```
But ```useHydration``` doesn't work either because the [app:created](https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/app/composables/hydrate.ts#L20) hook from the [hydrate.ts](https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/app/composables/hydrate.ts#L20) never gets triggered, and that's the place where the set function is called on the client. I've tested it with ```app:mounted``` instead and it worked, strangely without hydration node mismatch.

Example for `useHydration`: https://stackblitz.com/edit/nuxt-starter-zqpoed?file=app.vue

Besides that, ```app:created``` (and many more hooks) doesn't work in any custom composable (just like in ```hydrate.ts```), but the [documentation](https://nuxt.com/docs/guide/going-further/hooks#app-hooks-runtime) says that the runtime hooks should work within the composables.

@danielroe can you please tell me if these are the Nuxt bugs so I can create a new issue or open a PR, or am I just doing something wrong?

Thanks!

**Comment by danielroe** [comment]
The root issue here is an upstream Vue bug with hydrating async components: https://github.com/vuejs/core/issues/6638.

We can track within the Nuxt repository via https://github.com/nuxt/nuxt/issues/18405.
