### ISSUE TITLE
Vuetify components errors

### ISSUE THREAD

**Issue by Lustach** [nuxt/nuxt#20484]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.14.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `css`, `build`, `hooks`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/CodyBontecou/nuxt3-and-vuetify

### Describe the bug

Vuetify components are working on, but i have errors in console.
![image](https://user-images.githubusercontent.com/46442175/234210019-ddd0c0c4-4782-49c4-ba73-b7e21a5d574e.png)

### Logs

```shell-script
localhost:3001/_nuxt/%EF%BF%BDplugin-vuetify:components/VCounter/VCounter.sass net::ERR_ABORTED 503 (Server Unavailable).
```

**Comment by Ap3rtur3** [comment]
The virtual URLs for SASS files contain `\0`, which leads to this behavior. 
Following workaround prevents those errors for now: https://github.com/vuetifyjs/vuetify-loader/issues/290#issuecomment-1435641075

**Comment by Lustach** [comment]
Thank you, it help

**Comment by AasmundN** [comment]
Does anyone here have any clue on how to fix this? Would be nice if the issue could be reopened as it is still a problem.

**Comment by shubov** [comment]
Still a problem!
When I just open my project in the browser and the router tries to load a page where some Vuetify components are used, this happens:

`GET http://localhost:8080/@id/__x00__plugin-vuetify:components/VChip/VChip.sass net::ERR_ABORTED 404 (Not Found)`

If I reload the page a couple of times, it goes away.
