### ISSUE TITLE
navigateTo 

### ISSUE THREAD

**Issue by luckilyhang** [nuxt/nuxt#20481]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.3`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `srcDir`, `modules`, `elementPlus`, `app`, `hooks`, `nitro`, `plugins`, `css`, `experimental`, `typescript`, `sourcemap`, `vue`, `modern`
- Runtime Modules:  `@pinia/nuxt@0.4.8`, `@element-plus/nuxt@1.0.4`
- Build Modules:    `-`

### Reproduction

In Composables, when processing the return value of useFetch, it was found that navigateTo cannot jump, and an error was reported indicating nuxt instance unavailable

### Describe the bug

 In Composables, when processing the return value of useFetch, it was found that navigateTo cannot jump, and an error was reported indicating nuxt instance unavailable
export async function useHttp<T>(
  url: string,
  options: any = {}
): Promise<HttpResponse<T>> {
  try {
    options = useGetFetchOptions(options);
    const $route = useRoute();
    const errorCode = ref<number>(200);
    const statusCode = ref<number>(200);
    const { data: result }: any = await useFetch<HttpResponse<T>>(url, {
      ...options,
      onResponse({ response }) {
        statusCode.value = response._data.Code;
      },
      onResponseError: async (ctx) => {
        errorCode.value = ctx.response.status;
      },
    });
    if (errorCode.value == 400) {
      throw createError({
        statusCode: 404,
      });
    }
    if (errorCode.value == 504) {
      throw createError({
        statusCode: 503,
      });
    }
    try {
      if (statusCode.value == 432) {
        const path = encodeURI(`//${userSite}/hhb${$route.path}`);
        await navigateTo(`${registerDomain}?url=${path}`, {
          external: true,
        });
      }
      if (statusCode.value == 404) {
        throw createError({
          statusCode: 404,
        });
      }
    } catch (error) {
      console.log(error, "error----");
      return Promise.reject(error);
    }
    return result._value ?? "";
  } catch (err) {
    return Promise.reject(err);
  }
}

NavigateTo cannot jump

**Comment by danielroe** [comment]
`navigateTo` needs to be called in a place where the nuxt instance is available. On the server, that means you may need to use `callWithNuxt` if you are using it in a composable and not in a setup function. See https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables
