### ISSUE TITLE
keepailve include is invalid when use <NuxtPage/> component in app.vue

### ISSUE THREAD

**Issue by huihuilovekuikui** [nuxt/nuxt#20480]
### Environment

- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.2
- Nitro Version:    2.3.3
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-nvbdfr?file=app.vue,pages%2Findex.vue,pages%2Fabc.vue

### Describe the bug

![image](https://user-images.githubusercontent.com/66559869/234163271-5f620f06-83c7-4d38-820a-3a5a1c1e6560.png)

click add button in index.vue, then click to abc
but when I back index page, the number is reset to zero, beacuse index.vue render again
![image](https://user-images.githubusercontent.com/66559869/234163076-cd08ddbe-3ffb-42a6-bf9e-e735c4c1aac6.png)
![image](https://user-images.githubusercontent.com/66559869/234163117-7868f0cc-4dca-436b-9912-fed812e4afda.png)
![image](https://user-images.githubusercontent.com/66559869/234163191-4f08ae46-ad34-44c2-b777-bb9b8657f687.png)

**Comment by huihuilovekuikui** [comment]
index page isn't add keepalive if use include
![image](https://user-images.githubusercontent.com/66559869/234163734-e4fbf60f-ec83-436c-aa95-35da3008d847.png)

but when i remove ’include’ property
![image](https://user-images.githubusercontent.com/66559869/234164202-752f1e51-db2d-4c29-b853-664d335bd9a2.png)

index page and abc page both keepalive
![image](https://user-images.githubusercontent.com/66559869/234164179-be050750-4cc5-425c-a862-5d5c9adba8cb.png)

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/15214.

**Comment by kongyijilafumi** [comment]
I create a example,what should i do  how to use keepalive  in  the `a` page. [example](https://stackblitz.com/edit/nuxt-starter-sxlfea?file=app.vue)
