### ISSUE TITLE
[DOC] IIS Support

### ISSUE THREAD

**Issue by derHodrig** [nuxt/nuxt#20499]
### Describe the feature

Please add 
https://github.com/nuxt/framework/commit/ede534847831f46c45089a122d19b083d2ae26c7

to your documentation. We had our app running with IIS10 + nuxt2 and had no problem at all. With Nuxt3 we struggled, but that documentation of the archived repo helped us alot!

Could you please add this to the Nuxt Docs in the deployment section?

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by derHodrig** [comment]
Linking to Nitro
https://github.com/unjs/nitro/issues/1187

**Comment by danielroe** [comment]
I think that upstream in Nitro is likely to be the correct place for this docs. cc: @pi0

**Comment by derHodrig** [comment]
Closed through [https://github.com/unjs/nitro/issues/1427](https://github.com/unjs/nitro/issues/1427)

Docs shown here [https://nitro.unjs.io/deploy/providers/iis](https://nitro.unjs.io/deploy/providers/iis)

Nice work!
