### ISSUE TITLE
DynamicRoute from router.beforeEach in plugin:  changed behaviour

### ISSUE THREAD

**Issue by henriksjodahl** [nuxt/nuxt#20491]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.4.1`
- Nitro Version:    `2.3.3`
- Package Manager:  `npm@9.5.1`
- Builder:          `vite`
- User Config:      `modules`, `runtimeConfig`, `sourcemap`, `devtools`
- Runtime Modules:  `@storyblok/nuxt@5.4.0`, `@nuxtjs/tailwindcss@6.6.6`, `@nuxtjs/robots@3.0.0`
- Build Modules:    `-`

### Reproduction

Working in v3.4.0
https://stackblitz.com/edit/github-1cetba-gmp4ez?file=plugins%2FdynamicRouting.ts

Not working in v3.4.2
https://stackblitz.com/edit/github-1cetba-sn9iac?file=plugins%2FdynamicRouting.ts

### Describe the bug

I have created a plugin that on router.beforeEach checks if the current path matches a path in en external API, and if so, creates a dynamicRoute for that path with a component matching the API item type, in the example, a Product.

This works in Nuxt 3.4.0 but have stopped working in Nuxt >= 3.4.1. In the newer version, the vue router seems to forget the route...

### Additional context

This is the idea behind the functionality
https://router.vuejs.org/guide/advanced/dynamic-routing.html#adding-routes-inside-navigation-guards

**Comment by CernyMatej** [comment]
Can confirm this used to work but now doesn't on newer versions.

**Comment by CernyMatej** [comment]
@henriksjodahl were you able to find a workaround?
This is still an issue in Nuxt 3.6.1 and I'd really like to use the new versions
