### ISSUE TITLE
The tsx in "< template setup lang='tsx' >" is compiled incorrectly.

### ISSUE THREAD

**Issue by TickHeart** [nuxt/nuxt#20513]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.3.3`
- Package Manager:  `pnpm@8.3.1`
- Builder:          `vite`
- User Config:      `app`, `ssr`, `alias`, `vite`, `imports`, `css`, `experimental`, `nitro`, `srcDir`, `hooks`, `modules`, `build`, `telemetry`
- Runtime Modules:  `@pinia/nuxt@0.4.6`, `@vueuse/nuxt@9.11.0`, `@vant/nuxt@1.0.0`
- Build Modules:    `-`
------------------------------

### Reproduction

Sorry, I don't have time to copy the mistakes. I try to be clear enough in the description of the mistakes.

### Describe the bug

The lock file was deleted due to an error in the project. I ran the project after reinstalling the project dependency, and there was an error about tsx.

At first, @nuxt/utils reported that the "consola" dependency could not be found.

I tried to fix the version number of "nuxt" in " package .json", and the first error disappeared , but there was still an error of "tsx".

### Logs

```shell-script
ERROR  Transform failed with 1 error:                                 09:46:26
/Users/tickHeart/qilin/projects/web-table-ssr/src/merge/pages/backstage/systemCenter/siteManage/messageSettings.vue:46:20: ERROR: Expected ">" but found "v"

```
```

**Comment by danielroe** [comment]
`@nuxt/utils` is a dependency of Nuxt 2 and shouldn't be installed alongside Nuxt 2. I suspect there are some dependencies that shouldn't be there.

Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
