### ISSUE TITLE
Nuxt2 to Nuxt3, not display component in a correct order 

### ISSUE THREAD

**Issue by TanguyC0** [nuxt/nuxt#20522]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.4.1`
- Nitro Version:    `2.3.3`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `app`, `css`, `components`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

page/[...id].vue

```
<template>
    <div>
            <component
                v-for="(item, key) in data"
                :key="key"
                :is="item.type" 
                
                v-bind="item"

                @lgc-action="$emit($event.handler, $event)"


                @update:payload="(value) => item.payload = value"
                @update:form="(value) => item.form = value"
                @update:restriction="(value) => item.restriction = value"/>
                
    </div>
</template>

<script setup>

    const route = useRoute()
    const runtimeConfig = useRuntimeConfig()
    const [path] = route.params.id.slice(-1)
    const  { data }  = reactive(await $fetch(`${runtimeConfig.public.BASE_URL}${runtimeConfig.public.SERVICE}/web/portal/${runtimeConfig.public.POI_NAME}/form/${path}`))
    
</script>
```

component/form.vue

```
<template>
  <div class="lgc-form-input-group">
    <p v-if="label" class="lgc-form-input-group__label">{{ label }}</p>
    <div class="lgc-form-input-group__form">
      <!-- v-bind="!item.type.toLowerCase().includes('form') ? { data: item } : item" -->
      <component :attr="index" v-for="(item, index) in data" :key="index" :is="item.type" v-bind="item" 
        @update:isValid="item.isValid = $event"
        @emit-value="constructPayload(item, $event)"
        @emit-input-and-value="constructPayload($event.input, $event.payload)"
        @add-error="errorManagement('add', $event)"
        @remove-error="errorManagement('remove', $event)"
        @lgc-action="$emit($event.handler, $event)"
      ></component>
    </div>
  </div>
</template>

<script setup>
import { v4 as uuidv4 } from 'uuid';

const emit = defineEmits(['emit-value','lgc-action'])

const props = defineProps({
    data: {
      type: Array,
      required: true
    },
    id: {
      type: String,
      required: false
    },
    label: {
      type: String,
      required: false
    },
    value: {
      type: Object,
      required: false,
      default() {
        return {}
      }
    },
    uuid: {
      type: String,
      required: false,
      default() {
        return uuidv4()
      }
    }
  })


  const inputValue= reactive(props.value ? props.value : {})

    function constructPayload(input, payload) {
      inputValue[input.id] = payload
    }

    function errorManagement(action, error) {
      let component = props.data.find(el => el.type === 'lgc-form-error');
      if (component) {
        let already = component.errors.find(el => el.key === error.key && el.byClient)
        let index = component.errors.indexOf(already)
        switch (action) {
          case 'add':
            if (component) {
              if (already) component.errors.splice(index, 1)
              if (error.value) component.errors.push(error)
            }
            break;
          case 'remove':
            if (component) {
              if (already) component.errors.splice(index, 1)
            }
            break;
          default:
            break;
        }
      } else {
        emit(`${action}-error`, error)
      }
    }

    async function submit() {
      emit('emit-value', inputValue)
    }

</script>

```

### Describe the bug

The problem occurred when switching from nuxt2 to nuxt3.
this is a problem with the display order of compose with the `<component :is="" v-for="" :key="">` tag, in all that I find as documentation, it tells me offers 2 solutions:
- make a sort function but even then, it doesn't work
- that it is an asynchronous problem and must be made synchronous. Off, nuxt3 with <script setup> makes compose directly asynchronous. It would then possibly be a "bug" linked to the frame work.

afterwards, I haven't seen any documentation on the problem caused here: depending on the index, the order changes.
In addition to the tests you had done, I tried to put a uuid in key, the whole display is reversed.
without key, it's good
the index, gives the current problem
a fixed key or just the item gives an even different display.
regarding the key, ideally, the uuid should be in the object since using the index seems to be a bad practice
 
 The problem occurs in the compose form
 
 result nuxt 2 & nuxt3 no :key
<img width="701" alt="Capture d’écran 2023-04-26 à 10 51 51" src="https://user-images.githubusercontent.com/98752049/234523209-431b7cfc-d0c0-4397-a82d-d6120635a12a.png">

result nuxt 3 whit :key="index"
<img width="675" alt="Capture d’écran 2023-04-26 à 10 55 16" src="https://user-images.githubusercontent.com/98752049/234524004-76a98dde-1312-4266-9455-d9f28c1c521d.png">

result nuxt3 whit :key="uuidv4()"
<img width="678" alt="Capture d’écran 2023-04-26 à 10 57 25" src="https://user-images.githubusercontent.com/98752049/234524648-d85ae34d-70b5-4f58-a23d-005e8afd829a.png">

**Comment by danielroe** [comment]
Instead of `reactive(await $fetch())` you should likely use `useAsyncData` or `useFetch`.

I suspect the issue you are facing is due to the fact that you are refetching the data before hydration on the client-side. Using `useFetch` will prevent refetching on the client. See https://nuxt.com/docs/getting-started/data-fetching for more information.
