### ISSUE TITLE
TS2589: Type instantiation is excessively deep and possibly infinite

### ISSUE THREAD

**Issue by SamHoque** [nuxt/nuxt#20524]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.19.1`
- Nuxt Version:     `0.0.0`
- Nitro Version:    `-`
- Package Manager:  `unknown`
- Builder:          `webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Copy paste the `modules` from the Nuxt Documentation.

```
import { defineNuxtConfig } from 'nuxt/config';

export default defineNuxtConfig({
  modules: [
    // Using package name
    '@nuxtjs/axios',
    // Relative to your project srcDir
    '~/modules/awesome.js',
    // Providing options
    ['@nuxtjs/google-analytics', { ua: 'X1234567' }],
    // Inline definition
    function () {},
  ],
});
```

### Describe the bug

This started to happen when I updated from nuxt 3.3.0 to 3.4.2.

![image](https://user-images.githubusercontent.com/30783651/234550134-efa778b5-491b-499a-a04a-ef83fe2ad2c0.png)

**Comment by danielroe** [comment]
First, several of those modules are not Nuxt 3 compatible.

Second, this looks like a WebStorm editor. Do you get any errors when running `vue-tsc --noEmit` (you will need to install `vue-tsc` and `typescript`)? If not, then it's a WebStorm bug, and you can check out using the workspace version of TypeScript as a workaround: https://volta.net/nuxt/nuxt/issues/20221#comment-2231202.
