### ISSUE TITLE
Cannot use absolute paths in imports inside nuxt.config

### ISSUE THREAD

**Issue by kehwar** [nuxt/nuxt#20539]
### Environment

- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.2
- Nitro Version:    2.3.3
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-anzwn3?file=nuxt.config.ts

### Describe the bug

Absolute paths and aliases cannot be used on imports inside nuxt.config.ts

Cannot be used in any locally imported modules either

Relative paths work fine

### Additional context

This is problematic if using the following eslint rule

https://github.com/MelvinVermeer/eslint-plugin-no-relative-import-paths

### Logs

```shell-script
ERROR  Cannot find module '~/config/api'
Require stack:
- /home/projects/github-anzwn3/nuxt.config.ts

  Require stack:
  - nuxt.config.ts
  at Module._resolveFilename (https://githubanzwn3-5rqk.w-credentialless.staticblitz.com/blitz.d830b1a2.js:35:242305)
  at Function.resolve (https://githubanzwn3-5rqk.w-credentialless.staticblitz.com/blitz.d830b1a2.js:35:480406)
  at _resolve (node_modules/jiti/dist/jiti.js:1:241100)
  at jiti (node_modules/jiti/dist/jiti.js:1:243384)
  at eval (nuxt.config.ts:2:12)
  at Object.jiti (node_modules/jiti/dist/jiti.js:1:245859)
  at resolveConfig (file://node_modules/c12/dist/index.mjs:300:24)
  at Module.loadConfig (file://node_modules/c12/dist/index.mjs:137:40)
  at async loadNuxtConfig (file://node_modules/@nuxt/kit/dist/index.mjs:561:18)
  at async Object.invoke (file://node_modules/nuxi/dist/chunks/dev.mjs:139:20)
```

**Comment by danielroe** [comment]
I think absolute paths would work fine (`/path/from/root`).

What aren't working in your example are aliases (which are defined _by_ your Nuxt config and don't currently work within it) and relative paths without a `./` in front.

We could enable some aliases (https://github.com/unjs/jiti/commit/cab50cc0ebba4934c010857241d7cc72e151fd86) but for example `~` refers to your source directory which is set within the config file. We could hard alias it to rootDir which would work for most users without custom srcDir but this would be misleading and inconsistent. Likewise supporting only rootDir aliases (`~~`) would be confusing.

**Comment by kehwar** [comment]
> I think absolute paths would work fine (`/path/from/root`).

This also doesn't work

I would prefer absolute paths everywhere (maybe enable the alias with an ENV variable?) but I understand this is a style preference

I'm using `"typescript.preferences.importModuleSpecifier": "non-relative"` on vscode to force absolute paths on my autoimports so I have gone ahead and added an override to my eslint config to prevent headaches later on

```
overrides: [
  {
    files: ["nuxt.config.ts", "**/module.ts", "**/module/**"],
    rules: {
      "no-relative-import-paths/no-relative-import-paths": "off",
      "no-restricted-syntax": [
        "error",
        {
          selector: "ImportDeclaration[source.value=/~+\\u002F/]",
          message: "Do not use absolute paths inside nuxt.config or local modules."
        }
      ]
    }
  }
]
```

**Comment by danielroe** [comment]
Indeed, you can enable the alias with an environment variable (`JITI_ALIAS`).

**Comment by kehwar** [comment]
I expected setting `JITI_ALIAS = {"~": "."}` to work

But it resolves `~/path/to/file` to `path/to/file`

Which throws `ERROR  Cannot find module 'path/to/file'`

Hardcoding my project root path in env variable works: `{"~": "full/path/to/project/root"}`

Is there a better way to do this? Besides using a script to set my env variable at runtime?
