### ISSUE TITLE
upgraged to 3.4.2 from 3.4.1 got an error about ' At least one <template> or <script> is required in a single file component.

### ISSUE THREAD

**Issue by chenyuncai** [nuxt/nuxt#20530]
### Environment

 npx nuxi info
Nuxi 3.4.2                                                              22:26:20
                                                                        22:26:22
RootDir: ***
Nuxt project info:                                                      22:26:22

------------------------------
- Operating System: Windows_NT                                          22:24:03
- Node Version:     v18.12.1
- Nuxt Version:     3.4.2
- Nitro Version:    2.3.3
- Package Manager:  npm@8.19.2
- Builder:          vite
- User Config:      nitro, runtimeConfig, extends, build, modules, colorMode, tailwindcss, auth, elementPlus
- Runtime Modules:  @nuxtjs/color-mode@3.2.0, unplugin-icons/nuxt, @sidebase/nuxt-auth@0.4.4, @element-plus/nuxt@1.0.4, @nuxtjs/tailwindcss@6.6.6
- Build Modules:    -
------------------------------

### Reproduction

Sorry i cannot give the link. It's my online project and it seems not a code problem.

### Describe the bug

got an error about ' At least one <template> or <script> is required in a single file component when upgraged to 3.4.2 from 3.4.1.

Everythinkg works fine in 3.4.1.

I checked all my vue component. There has no empty file.

so where the msg prompt from. 

### Additional context

![image](https://user-images.githubusercontent.com/8945203/234608507-9ca2bece-0d7d-4b2f-b95c-b73547c36363.png)

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by chenyuncai** [comment]
sorry. I found the cause. a empty component found. How can i delete this issue?
