### ISSUE TITLE
routerMiddleware.global.js call twice on server

### ISSUE THREAD

**Issue by ideafm** [nuxt/nuxt#20548]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.2
- Nitro Version:    2.3.3
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-ebbpgn?file=pages%2Findex.vue,pages%2Fforbidden.vue,app.vue,middleware%2FrouterMiddleware.global.js

open /forbidden link on client, and reload page. Result in terminal console.

### Describe the bug

router middleware calling twice, when using navigateTo.

**Comment by danielroe** [comment]
This is vue-router behaviour and is not caused by Nuxt: see https://stackblitz.com/edit/github-8dvck9?file=src/router.ts.
