### ISSUE TITLE
My plugin tests failed since the upgrade to 3.4.0: Failed to load url /.nuxt/nuxt.config.mjs

### ISSUE THREAD

**Issue by Kobee1203** [nuxt/nuxt#20550]
### Environment

Nuxi 3.4.0                                                                                                                         18:01:40
                                                                                                                                   18:01:42
RootDir: /home/projects/github-4o3qmw                                                                                              18:01:42
Nuxt project info:                                                                                                                 18:01:42

------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.0
- Nitro Version:    2.3.3
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      debug
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-4o3qmw?file=tests/my.test.ts

### Describe the bug

I have a problem that appeared when I upgraded from version 3.3.3 to 3.4.0.

When I run my tests on my plugins, I get the following error: 
`Error: Failed to load url /.nuxt/nuxt.config.mjs (resolved id: /.nuxt/nuxt.config.mjs) in /home/projects/github-4o3qmw/node_modules/nuxt/dist/app/composables/payload.js. Does the file exist?`

The error comes from the following change that was made in packages/nuxt/src/app/composables/payload.ts :
```
// @ts-expect-error virtual import
import { renderJsonPayloads } from '#build/nuxt.config.mjs'
```

See : https://github.com/nuxt/nuxt/pull/19205/files#diff-92e4a4d13b34c6fca4d7c5d84596f8e4d5440a7cb9e21de48573685cec194341R8

My tests use the same aliases as in the Nuxt `tsconfig.json`:
In particular, there are the following aliases:
```
      "#build": [
        ".nuxt"
      ],
      "#build/*": [
        ".nuxt/*"
      ]
```

In the plugin file, I import `defineNuxtPlugin` from '#app':

```
import { defineNuxtPlugin } from '#app';

export default defineNuxtPlugin((/*nuxtApp*/) => {
  console.log('Hello world!');
});
```

#app' points to `node_modules/nuxt/dist/app/index.d.ts`. that exports the composables:

`export * from "./composables/index.js";`

And especially `payload.js`:

`export { isPrerendered, loadPayload, preloadPayload } from './payload.js';`

And `payload.js` contains the import that causes problems:

`import { renderJsonPayloads } from '#build/nuxt.config.mjs`

It tries to find the file `nuxt.config.mjs` in `.nuxt/` but it does not exist.

**Comment by danielroe** [comment]
I think this is an issue with your testing setup, not Nuxt.

I would suggest trying https://github.com/danielroe/nuxt-vitest which should be able to handle these virtual imports for you.

**Comment by Kobee1203** [comment]
I have already tried nuxt-vitest but I get several errors.

I have already posted an issue: https://github.com/danielroe/nuxt-vitest/issues/88

plus other errors because it doesn't find the auto imported functions:

`ReferenceError: defineNitroPlugin is not defined`
`ReferenceError: defineEventHandler is not defined`

Anyway, I think for now I'll mock the import of the virtual file, even if I think it's not the best solution...

**Comment by silverbackdan** [comment]
Hi @Kobee1203 I've come across this issue in writing tests for a Nuxt module.

If I try to use `nuxt-vitest` it complains that I have not enabled it as a module. I do have a playground where I enable it but most of my tests are unit tests so I'm not quite sure what it's looking for me to enable.

I had been using `vite-plugin-nuxt-test` successfully which does as you did, and map all the imports.

What was your solution please?

**Comment by Kobee1203** [comment]
Hi @silverbackdan 

To solve my problems, I updated my vitest configuration.

**vitest.config.ts**

```
import { defineConfig } from 'vite'
import vitestNuxtPlugin from './vitest-nuxt-plugin'
import { configDefaults } from "vitest/config"

export default defineConfig({
    plugins: [vitestNuxtPlugin()],
    test: {
        dir: 'tests',
        environment: "happy-dom",
        restoreMocks: true
    }
})
```

I updated the vitest-nuxt-plugin to add the following alias: 
`"#build/nuxt.config.mjs": resolve(srcDir, "nuxt.config.ts")`

And I keep importing via an `auto-imports` directory the functions that are auto-imported and cannot be solved automatically.
![image](https://github.com/nuxt/nuxt/assets/1423193/7bf93c53-8f56-4b51-9a85-eaf12d43f34d)

Here is an example (nitro.ts) that import nitro functions and mock `useStorage()`
```
import { vi } from "vitest";
export { defineNitroPlugin } from 'nitropack/dist/runtime/plugin';

const mockedStorage = {
    getItem: vi.fn(),
    setItem: vi.fn()
}
export const useStorage = vi.fn(() => mockedStorage)
```

**vitest-nuxt-plugin.ts**

```
import { existsSync } from 'fs'
import { resolve } from 'path'
import AutoImport from 'unplugin-auto-import/vite'
import Vue from '@vitejs/plugin-vue'
import type { LoadNuxtOptions } from '@nuxt/kit'

/**
 * Turn tsconfig paths into aliases.
 */
function pathsToAlias(srcDir: string, paths: Record<string, string[]>) {
    return Object.fromEntries(
        Object.entries(paths).map(([key, value]) => [
            key,
            resolve(srcDir, value[0])
        ])
    )
}

/**
 * Get the tsconfig from Nuxt.
 */
async function getTsConfig(buildDir: string) {
    const {readTSConfig} = await import('pkg-types')
    return await readTSConfig(resolve(buildDir, 'tsconfig.json'))
}

/**
 * Get the paths from Nuxt's tsconfig.
 */
async function getTsConfigPaths(buildDir: string) {
    const {compilerOptions} = await getTsConfig(buildDir)
    return compilerOptions?.paths as Record<string, string[]>
}

/**
 * Other aliases not declared in Nuxt's tsconfig.
 */
function getOtherAliases(srcDir: string) {
    return {
        "#build/nuxt.config.mjs": resolve(srcDir, "nuxt.config.ts")
    }
}

/**
 * Get the list of aliases.
 */
async function getAlias(buildDir: string, srcDir: string) {
    const nuxtAliases = pathsToAlias(srcDir, await getTsConfigPaths(buildDir))
    const otherAliases = getOtherAliases(srcDir)
    return {...otherAliases, ...nuxtAliases}
}

/**
 * Nuxt Vitest Plugin
 */
export default async function (opts: LoadNuxtOptions = {}) {
    const {loadNuxt} = await import('nuxt')
    const nuxt = await loadNuxt(opts)
    const {buildDir, srcDir} = nuxt.options
    await nuxt.close()

    console.log('buildDir', buildDir)
    console.log('srcDir', srcDir)

    if (!existsSync(buildDir)) {
        const {runCommand} = await import('nuxi')
        await runCommand('prepare')
    }

    return [
        Vue(),
        AutoImport({
            dts: true,
            imports: [
                'vitest',
                'vue',
                {
                    '@unhead/vue': [
                        'useHead'
                    ]
                }
            ],
            dirs: [
                srcDir + '/tests/auto-import'
            ]
        }),
        {
            name: 'nuxt:vitest',
            async config() {
                return {
                    resolve: {
                        alias: await getAlias(buildDir, srcDir)
                    },
                    test: {
                        deps: {
                            inline: ['nuxt/dist']
                        }
                    }
                }
            }
        }
    ]
}
```

This way, the virtual import points to `nuxt.config.ts`. If I add `renderJsonPayloads` in the future, it will be taken into account correctly.
![image](https://github.com/nuxt/nuxt/assets/1423193/5ba1b7b6-d9f4-4e25-a199-71cc57987b3a)



**package.json**
```
{
  ...
  "scripts": {
    ...
  },
  "dependencies": {
    ...
    "@nuxtjs/i18n": "^8.0.0-beta.11"
  },
  "devDependencies": {
    ...
    "happy-dom": "^9.9.2",
    "nuxt": "^3.4.2",
    "unplugin-auto-import": "^0.15.3",
    "vitest": "^0.30.1",
    ...
  },
  "bundledDependencies": [
    "acorn"
  ],
  ...
}
```

**Extra info**

When I upgraded my dependencies, I encountered an error with the `@nuxtjs/i18n` module after upgrading it to `8.0.0-beta.11`.

I built my application.
When I ran it on Windows, I had no problems.
As soon as I ran it on Linux server (Red Hat), I had an error at startup.
![image](https://github.com/nuxt/nuxt/assets/1423193/7c18afd4-8547-449b-8b66-79336cac538d)

This is due to the use of the `acorn` dependency by `@intlify/bundle-utils` which is added as a symbolic link in the node_modules.
![image](https://github.com/nuxt/nuxt/assets/1423193/4945341f-fdb8-4f1f-92bc-0eecefa3575b)

Unfortunately, `npm pack` does not support symbolic links, so `acorn` is not added.

To make sure I added acorn to my package, I added `acorn` as bundledDependencies in the `package.json` file, and it worked.
```
"bundledDependencies": [
    "acorn"
],
```

Now you know everything 😃
