### ISSUE TITLE
NuxtLink affects the effect of anchor point positioning, which will cause the :target pseudo-element and scroll-padding-top to not work. How to solve it?

### ISSUE THREAD

**Issue by xhc-code** [nuxt/nuxt#20555]
### Environment

no

### Reproduction

example：https://codesandbox.io/p/sandbox/quiet-pine-pwftq4?file=%2Fapp.vue&selection=%5B%7B%22endColumn%22%3A28%2C%22endLineNumber%22%3A30%2C%22startColumn%22%3A28%2C%22startLineNumber%22%3A30%7D%5D

### Describe the bug

1. The anchor position cannot be performed normally
2. The anchor position cannot be triggered: the lock of the target pseudo-element
3. Invalid application of scroll-padding-top style
4. The anchor jump between pages cannot be effectively anchored to specify the position in the page

**Comment by xhc-code** [comment]
> ### Environment
> no
> 
> ### Reproduction
> example：https://codesandbox.io/p/sandbox/quiet-pine-pwftq4?file=%2Fapp.vue&selection=%5B%7B%22endColumn%22%3A28%2C%22endLineNumber%22%3A30%2C%22startColumn%22%3A28%2C%22startLineNumber%22%3A30%7D%5D
> 
> ### Describe the bug
> 1. The anchor position cannot be performed normally
> 2. The anchor position cannot be triggered: the lock of the target pseudo-element
> 3. Invalid application of scroll-padding-top style
> 4. The anchor jump between pages cannot be effectively anchored to specify the position in the page
> 
> ### Additional context
> _No response_
> 
> ### Logs
> _No response_

5. Adding external to true will reload the page for the same page jump anchor
6. Adding the no-prefetch attribute cannot turn off NuxtLink prefetching.

**Comment by awacode21** [comment]
i am experiencing the same problem. Anything new or known workaround ?

**Comment by xhc-code** [comment]
You can try to jump around manually using the vue-router or using the native a tag. You can try.

**Comment by manniL** [comment]
As a workaround you can use the `external` prop for this 👍🏻

**Comment by danielroe** [comment]
resolved in https://github.com/nuxt/nuxt/pull/28083
