### ISSUE TITLE
Session data not available on external redirect to nuxt

### ISSUE THREAD

**Issue by Ponkhy** [nuxt/nuxt#20552]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.12.1
- Nuxt Version:     3.4.2
- Nitro Version:    2.3.3
------------------------------

### Reproduction

Unfortunately I'm not able to provide a reproduction, since it relies on external oauth2 credentials.

### Describe the bug

Hello,

I'm currently trying to implement a OAuth2 authentication to my Nuxt project.
But everytime when I'm getting redirect back to the Nuxt project from the external provider like Discord (`https://discord.com/oauth2/authorize`), it seems like no session data at all is available when making a `useFetch()` request to a server api route, where I'm trying to get a cookie via `getCookie(event, 'cookie_name')`.
It is also not possible to access any cookie via `useCookie("cookie_name")`.

**Flow:** Nuxt Page 1 (`navigateTo(DISCORD_OAUTH_URL, { external: true })`) --> Authorize App for User --> Getting redirect back to Nuxt Page 2 where the cookie is needed, but not accessible anymore --> `useFetch()` to Nuxt Server API route --> No cookie on server side either

But when I'm manually reloading the Nuxt Page 2 after the redirect, everything is available, just not when it's redirected automatically from the external provider.

Any help is appreciated, many thanks!

**Comment by danielroe** [comment]
You need to set SameSite to Lax. See https://web.dev/samesite-cookies-explained/
