### ISSUE TITLE
Meta tags doesn't work when i build my app.

### ISSUE THREAD

**Issue by hakimov-dev** [nuxt/nuxt#20574]
### Environment

- Operating System: Windows 10

- Node Version: v16.18.0

- Nuxt Version: 2.16.3

- Package Manager: yarn@1.22.19

### Reproduction

  ```
head() {
      return {
        title: `My project / ${this.meta_data?.title}`,
        meta: [
          {
            name: 'Author',
            content: 'Project name'
          },
          {
            name: 'og:site_name',
            content: 'Project.com'
          },
          {
            name: 'og:title',
            content: this.meta_data?.title
          },
          {
            name: 'og:description',
            content: this.meta_data?.body
          },
          {
            name: 'og:type',
            content: 'article'
          },
          {
            name: 'og:url',
            content: `some link ${this.$route.params.id}`
          },
          {
            name: 'og:image',
            content: this.meta_data?.img ? this.meta_data?.img  : require('@/assets/images/404-image.jpg')
          },
        ]
      }
  }
```

### Describe the bug

I build my project to deploy then my meta tags doesn't work at deploy but it works when i run my project locally. I used this [docs](https://nuxtjs.org/docs/features/meta-tags-seo/) for adding meta tags and title.

**Comment by designchapnl** [comment]
I have the same issue.

1. Render static pages (target: static) 
2. Browsing sub page via internal links works as expected. 
3. Load sub page directly (or reload) gives the standard index meta.

I guess this is why Google is nagging about double canonicals.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
