### ISSUE TITLE
Showcase page awards category typo

### ISSUE THREAD

**Issue by GalacticHypernova** [nuxt/nuxt#20583]
### Environment

https://nuxt.com/showcase

### Reproduction

Going to the page.

### Describe the bug

The award category has a typo and says "Awwwards", and click on it will also change the URL to https://nuxt.com/showcase?category=Awwwards

### Additional context

If this is a planned word play I apologize in advance.

**Comment by warflash** [comment]
That is a pun yeah, probably based on https://www.awwwards.com/, not sure if that's the origin of the name or if there was something with the same name before them
