### ISSUE TITLE
ssr + useFetch not revalidating after upgrade from 3.3.3 to 3.4.3

### ISSUE THREAD

**Issue by lukascellar** [nuxt/nuxt#20589]
### Environment

- Operating System: Darwin
- Node Version:     v16.20.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.3.3
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      routeRules
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

1. nuxt.config.ts

```
    routeRules: {
        '/**': { swr: 5 }
    }
```

2. server route
```
export default defineEventHandler(async (event) => {
  return new Date().toISOString()
})
```

4. fetch data using useFetch

```
<template>
  <div>Date: {{ data }}</div>
</template>

<script setup>
const { data }  = await useFetch('/api/date')
</script>
```

https://stackblitz.com/edit/github-ugjk5d?file=nuxt.config.ts

### Describe the bug

rendered html is not changed after cache expiration and uses same __NUXT__ payload

### Additional context

3.3.3 this working corectly
3.4.0 - 3.4.3 not working

**Comment by agracia-foticos** [comment]
Same issue? https://github.com/nuxt/nuxt/issues/20630

**Comment by lukascellar** [comment]
tested latest nuxt 3.6.2 and it working correctly
