### ISSUE TITLE
Using `useCookie` in server plugin results in unhandledRejection on 404 pages

### ISSUE THREAD

**Issue by hecktarzuli** [nuxt/nuxt#20580]
### Environment

Node 18.15.0
Nuxt 3.4.3

### Reproduction

Create a page and use <NuxtPage> in app.vue
Create server plugin that uses `useCookie`
Go to an unknown page

**GOOD**
Nuxt 3.4.3 without using `useCookie` shows 404 fine
source: https://github.com/hecktarzuli/nuxt-bugs
url: https://nuxt-bugs.vercel.app/foo

**BAD**
Nuxt 3.4.3 using server plugin with `useCookie` shows 500 in vercel (crash) / 200 in dev (unhandled) for pages that should be 404.
source: https://github.com/hecktarzuli/nuxt-bugs/tree/usecookie-server-plugin-no-404
url: https://nuxt-bugs-ldou8053t-hecktarzuli.vercel.app/foo

![image](https://user-images.githubusercontent.com/2112282/235310014-26bb4d5a-d09f-4eae-b182-91152cc32fe8.png)

Vercel Crashes
![image](https://user-images.githubusercontent.com/2112282/235310120-ca780336-5cca-40e5-8845-8d57e4ab07c1.png)

Dev Exception
![image](https://user-images.githubusercontent.com/2112282/235309840-9801932f-eca6-4cf3-97fe-b82c50809d01.png)

### Describe the bug

When reading a cookie via `useCookie` in server plugin, if you hit a 404 page it throws an unhandled exception.  Plugins should be able to read and set cookies on 404 responses.

### Additional context
**This seems to work fine in 3.4.2**
### Logs

![image](https://user-images.githubusercontent.com/2112282/235310424-2281323e-e043-4e6e-9e53-6177d938b935.png)

**Comment by zhuoqi-chen** [comment]
In fact, your problem is essentially the same as the one I encountered (https://github.com/nuxt/nuxt/issues/20578)
Because `useCookie` is also add `app:error` hook.
https://github.com/nuxt/nuxt/blob/1464294d6abe13b54fdb8d204732345551c8e647/packages/nuxt/src/app/composables/cookie.ts#L55

**Comment by danielroe** [comment]
Let's track it there.

**Comment by peterkimzz** [comment]
same problem.

```
------------------------------
- Operating System: Darwin
- Node Version:     v20.13.1
- Nuxt Version:     3.11.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  yarn@1.22.22
- Builder:          -
- User Config:      devtools, modules, plugins, nitro, image, colorMode, tailwindcss, eslint, ui, typescript, supabase, runtimeConfig, routeRules, vite, security
- Runtime Modules:  nuxt-security@1.0.1, @nuxt/devtools@1.3.6, @nuxtjs/device@3.1.1, @nuxt/content@2.13.0, @nuxtjs/supabase@1.1.7, @nuxt/ui@2.16.0, @nuxt/eslint@0.4.0, @nuxt/image@1.7.0, @nuxtjs/i18n@8.3.1
- Build Modules:    -
------------------------------
```
