### ISSUE TITLE
upgrade from `3.4.2` to  `3.4.3` can only return `500` instead of `404` if page not found on `azure-swa`

### ISSUE THREAD

**Issue by gyhyfj** [nuxt/nuxt#20593]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.3.3
- Package Manager:  pnpm@8.3.1
- Builder:          vite
- User Config:      modules, vite, css, imports, pinia, sitemap, app, ignore, telemetry, appConfig, devServer, experimental, nitro
- Runtime Modules:  @nuxtjs/tailwindcss@6.6.6, @pinia/nuxt@0.4.8, @pinia-plugin-persistedstate/nuxt@1.1.1, @element-plus/nuxt@1.0.4, @nuxtjs/robots@3.0.0, nuxt-simple-sitemap@2.4.11
- Build Modules:    -

### Reproduction

3.4.3 with `preset:  azure`

### Describe the bug

If I visit pages not existing, it should return 404 and show the 404 page .
It's ok on `3.4.2`,
But once I upgrade nuxt to `3.4.3 `, that doesn't work on azure-swa. If visting pages not existing, I can't get 404 page, it return 500 and nothing else. So I'm back to `3.4.2` now.
It works well on node-server.

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/20578 - there's a PR pending to resolve
