### ISSUE TITLE
Issues with nuxt.config.ts when using Typescript in Webstorm

### ISSUE THREAD

**Issue by mcpanl** [nuxt/nuxt#20597]
### Environment

- Operating System: Windows_NT
- Node Version:     v16.20.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.3.3
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      routeRules
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

    Use Webstorm and Typescript 5.0.4.
    Create a nuxt.config.ts file and try to use the automatically imported method useHead.
    Try using the same nuxt.config.ts file with Typescript 4.3.5.

**4.3.5**
![图片](https://user-images.githubusercontent.com/59745518/235364413-24d0dc51-0071-4fbe-bbe7-6ee87de7a7a5.png)
![图片](https://user-images.githubusercontent.com/59745518/235364425-c3fc40c9-eea2-44ae-b3c1-f265403a2bf2.png)

**5.0.4**
![图片](https://user-images.githubusercontent.com/59745518/235364537-159e10fd-0bf2-4e16-b8fd-2421c06b533a.png)
![图片](https://user-images.githubusercontent.com/59745518/235364523-b442a876-4099-4def-b5e9-b3622fd51d85.png)

### Describe the bug

I am using Typescript 5.0.4 in Webstorm, and I can use nuxt.config.ts without any issues. However, the system does not recognize the automatically imported methods such as useHead, and it prompts the error "Unresolved function or method useHead()". On the other hand, when using Typescript 4.3.5 (Webstorm's default Bundled version), the system can recognize the automatically imported method useHead, but the nuxt.config.ts file is full of errors, and the error message "TS2345: Argument of type '{ routeRules: { '/api/**': { proxy: { to: string; }; }; }; }' is not assignable to parameter of type 'NuxtConfig'. Object literal may only specify known properties, and 'routeRules' does not exist in type 'NuxtConfig'." appears.

### Additional context

  "dependencies": {
    "@css-render/vue3-ssr": "^0.15.12",
    "@vicons/ionicons5": "^0.12.0",
    "http-proxy-middleware": "^2.0.6"
  },
  "devDependencies": {
    "@nuxt/test-utils": "3.3.3",
    "@types/node": "^16.18.20",
    "@types/prismjs": "^1.26.0",
    "@vitejs/plugin-vue": "^4.1.0",
    "@vitest/coverage-c8": "^0.29.8",
    "@vue/test-utils": "^2.3.2",
    "eslint-plugin-vitest": "^0.0.57",
    "jsdom": "^21.1.1",
    "naive-ui": "^2.34.3",
    "nuxt": "^3.4.3",
    "sass": "^1.60.0",
    "typescript": "^5.0.4",
    "vfonts": "^0.0.3",
    "vite-plugin-prismjs": "^0.0.8",
    "vitest": "^0.29.8",
    "vue-tsc": "latest"
  }

**Comment by warflash** [comment]
There has been a few reports in the Discord regarding ts is intellij products, from what I've gathered over time they are lagging behind in supporting certain ts features and slow to adapt. I think it could make sense also opening an issue with webstorm to make sure it's not something they're missing on their part

**Comment by memic84** [comment]
You should install the typescript package locally if you haven't already, and change the version from bundled to the one in node_modules (5.x version). This solved it for me.

**Comment by SugarF0x** [comment]
@memic84 that works for nuxt config types for me, but it breaks auto imported vue types resulting in all refs being of type any

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/20221.

**Comment by maximilianfixl** [comment]
I was able to solve the problem by enabling the `Vue Language Server (Volar)` option in `File | Settings | Languages & Frameworks | TypeScript | Vue` instead of `Automatically` in WebStorm 2023.2.2.
