### ISSUE TITLE
Server component will double styles if used in plugin

### ISSUE THREAD

**Issue by logotip4ik** [nuxt/nuxt#20602]
### Environment

- Operating System: Linux
- Node Version:     v16.17.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.3.3
- Package Manager:  pnpm@7.1.0
- Builder:          vite
- User Config:      experimental, sourcemap
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://codesandbox.io/p/sandbox/strange-head-g8ubxy

This works both in dev and prod builds

1. `npm run dev`. Notice, at the top of preview there are two `this will be inserted twice`. That is actually one style tag set in `plugins/test.ts`
2. Go to `pages/index.vue` and comment out `Test` component, now there is only one style tag

### Describe the bug

`useHead` composable in **plugin** context and a **server component** leads to doubling style tags

### Additional context

First noticed on my local project with `@nuxtjs/fontaine` module and server component. Style for fallback font was doubled. The only difference, one tag had `[data-h-...]` attribute. I guess, this is not a big deal, but still not nice.

**Comment by danielroe** [comment]
In general server components need to render styles because they don't know how they are being consumed or whether those styles have already been rendered or added to the page. I would like to see us deduplicate them, but you can already choose not to run a plugin when in an island context for now:

```ts
export default defineNuxtPlugin({
  env: {
    islands: false
  },
  setup () {
    useHead({
      style: [{
        innerHTML: 'this will be inserted twice'
      }]
    })
  }
})
```
