### ISSUE TITLE
`<template>` Element vanishes(?) from DOM, when NuxtLink-switching `pages/*`

### ISSUE THREAD

**Issue by BananaAcid** [nuxt/nuxt#20611]
### Environment

```
------------------------------
- Operating System: Linux
- Node Version:     v16.17.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.3.3
- Package Manager:  pnpm@7.1.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Reproduction

https://codesandbox.io/p/sandbox/nuxt-page-kills-template-content-zbiggk

### Describe the bug

`template`-content can not be read the second time anymore upon switching pages.

The element is still referenced by $ref but `.innerHTML` is nothing.

In another test project, the template element can not be found at all the second time.
Reproduced here.

### Additional context

Happens with VSCode locally on my machine too. 

The direct link to the test component: [/components/preContainer.vue](https://codesandbox.io/p/sandbox/nuxt-page-kills-template-content-zbiggk?file=%2Fcomponents%2FpreContainer.vue)

**Comment by manniL** [comment]
Can you try this in plain Vue SSR via https://github.com/nuxt-contrib/vue3-ssr-starter/ and see if issue is happening there too?

**Comment by BananaAcid** [comment]
I don't when i will have enough time to try this -

**Comment by manniL** [comment]
Seems to be a vue 3 ssr issue. [StackBlitz](https://stackblitz.com/edit/nuxt-issues-20611?file=src%2FApp.vue,src%2Fpages%2FB.vue,src%2Fcomponents%2FPreContainer.vue,src%2Fmain.ts,src%2Fpages%2FHome.vue,package.json&terminal=dev)
