### ISSUE TITLE
npx nuxi upgrade keeps geting nuxt 2

### ISSUE THREAD

**Issue by drigoalexander** [nuxt/nuxt#20616]
So i've got a project that got running on nuxt 3.2.3, and wanted to reinstall my node and package-lock by deleting them. when the instalation complete, it broking up says that 'defineNuxtConfig' is not defined. tried to check my nuxt version using ```npx nuxi info```, it tells that nuxt version that being used is **2.15.8**. try to use the ```npx nuxi upgrade -f``` it still says nuxt version of **2.15.8**. 

#### *nuxi version : 3.2.3
------------------------------
- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     2.15.8
- Nitro Version:    2.3.3
- Package Manager:  npm@9.5.1
- Builder:          webpack
- User Config:      modules, css, runtimeConfig
- Runtime Modules:  @nuxtjs/tailwindcss@6.6.7, @nuxtjs/fontaine@0.2.5, @pinia/nuxt@0.4.9, @pinia-plugin-persistedstate/nuxt@1.1.1, @nuxt/content@2.6.0, @vueuse/nuxt@10.1.2
- Build Modules:    -
------------------------------

#### Here's my package.json

```
{
  "overrides": {
    "vue": "latest"
  },
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/content": "^2.5.2",
    "@nuxtjs/fontaine": "^0.2.4",
    "@nuxtjs/tailwindcss": "^6.4.1",
    "@pinia-plugin-persistedstate/nuxt": "^1.1.1",
    "@sidebase/nuxt-auth": "^0.4.4",
    "@tailwindcss/typography": "^0.5.9",
    "@vueuse/nuxt": "^10.0.2",
    "nuxt": "^3.4.3",
    "tailwindcss": "^3.3.0"
  },
  "dependencies": {
    "@heroicons/vue": "^2.0.16",
    "@nuxt/test-utils-edge": "^3.5.0-28049707.16bf2284",
    "@nuxtjs/html-validator": "^1.2.4",
    "@nuxtjs/strapi": "^1.9.0",
    "@pinia/nuxt": "^0.4.7",
    "@popperjs/core": "^2.11.7",
    "@vueuse/core": "^10.0.2",
    "daisyui": "^2.51.3",
    "flowbite": "^1.6.4",
    "flowbite-datepicker": "^1.2.2",
    "hooper": "^0.3.4",
    "marked": "^4.3.0",
    "pinia": "^2.0.33",
    "v-calendar": "^3.0.3",
    "vue3-carousel": "^0.2.16"
  }
}

  ```

i tried to install a new project, and it still says 'defineNuxtConfig' is not defined, and got nuxt **2.15.8**.

**Comment by danielroe** [comment]
I would guess you have nuxt 2 installed globally or in a parent `node_modules` folder. Would you check?

**Comment by drigoalexander** [comment]
I see, it solved the problems. thankyou sir
