### ISSUE TITLE
Memory leak in Nuxt 2 website

### ISSUE THREAD

**Issue by thePercept** [nuxt/nuxt#20621]
### Environment

RootDir: /home/projects/github-rdczqk                                                                                                                                    3:04:22 PM
Nuxt project info:                                                                                                                                                       3:04:22 PM

------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     2.16.3
- Nitro Version:    -
- Package Manager:  yarn@1.22.19
- Builder:          webpack
- User Config:      server, ssr, optimization, modules, chakra, crawler, head, publicRuntimeConfig, privateRuntimeConfig, image, router, loading, css, plugins, components, buildModules, sitemap, build, i18n
- Runtime Modules:  @chakra-ui/nuxt@0.7.1, @nuxtjs/emotion@0.1.0, @nuxtjs/i18n@7.3.1, @nuxtjs/axios@5.13.6, @nuxt/image@0.6.2, @nuxtjs/sitemap@2.4.0
- Build Modules:    @nuxt/image@0.6.2
------------------------------

#### How to start the project

1. Start this nuxt project using yarn dev
2. Once the project is running then click on Open in New Tab button on stackblitz environment.
3. This will open the current running project on a new tab and also will give an error message :

RangeError
Maximum call stack size exceeded

4. Please ignore this message and head over to change the url on the same tab in the browser

### Opening the websites News & Events page as a starting point

1. Append the url as mentioned below :

/news-and-events/

2. Now you will be able to see the News & Events page
3. Click on the navigation menu to go to Home
4. While on homepage take a base heap snapshot
5. Go again to News & Events page
6. Come back to Homepage
7. Repeat this for few times
8. Again take a heap snapshot

### Describe the bug

**Finally you will notice how the sizes of the snapshots of heap keeps increasing and if you do compare the snapshots you'll see lots of detached strings, DOM elements and other Nodes retaining a lot of memory which can't be freed**

![image](https://user-images.githubusercontent.com/22754051/235634722-0cfeefd5-c013-44b4-b323-1c1ce31cf488.png)

**Comment by daniluk4000** [comment]
Hello there, memory leak expert there.

1. Change beforeCreate to created in default.vue, beforeCreate doesn't have access to this. I don't think that can cause memory leak, that's just an error
2. I can probably see memory leak in middleware, but I'm not sure. I would suggest moving this into **client-side** plugin, otherwise:
- You register hook every time when you go between pages
- You register hook you don't need on SSR
3. I can see possible memory leak in a way you register mixin in colorModeToggler. 
I have never seen someone add mixin like this to app, but one thing I know for sure: you can call Vue.mixin on SSR only once, otherwise in production mode it will cause memory leak.

Your code can look like this:
```typescript
import Vue from 'vue';

export default () => {
  //This two lines prevents memory leak
  if (Vue.prototype.customMixinsInitialized) return;
  Vue.prototype.customMixinsInitialized = true; 

  Vue.mixin({
    computed: {
      colorMode() {
        return this.$chakraColorMode();
      },
      mainStyles() {
        return {
          dark: {
            bg: 'gray.700',
            color: 'white',
            viewAllLinkColor: 'white',
            downloadLinkColor: 'white',
            smallTextColor: '#52FF94',
          },
          light: {
            bg: 'white',
            color: 'gray.900',
            viewAllLinkColor: '#C5283D',
            downloadLinkColor: '#100072',
            smallTextColor: '#C5283D',
          },
        };
      },
      mainStylesTwo() {
        return {
          dark: {
            bg: 'gray.600',
            color: 'white',
          },
          light: {
            bg: '#f4f4f4',
            color: 'gray.900',
          },
        };
      },
    },
    methods: {
      toggleColorMode() {
        this.$toggleColorMode();
      },
    },
  });
};
4. If suggestions above won't help, consider adding same Vue.prototype thing to other plugins, but I think that things above should be more than enough

**Comment by thePercept** [comment]
Hi daniluk,

Thanks for replying to me. I am happy that you took out your time and replied. 

What I did after understanding your points was to remove global mixin and removed that middleware. Now I have a mixin folder which is imported to the pages where the computed mixed color properties are made available for toggle.

Somehow the problem still persists. 

![2023-05-02 (10)](https://user-images.githubusercontent.com/22754051/235737337-157b6b64-4a46-4405-a60b-a89ede9423a6.png)

**Comment by thePercept** [comment]
I tested it again and I am not able to detect much changes in the memory increasing pattern 

![image](https://user-images.githubusercontent.com/22754051/235741274-d46a14e3-6ac8-49f0-b607-9f3c3958c1a1.png)

**Comment by daniluk4000** [comment]
@thePercept it grows until some time and then must stop. If it stops and not growing much, than you're good. I was using siege to test this and sent many requests, memory did grow, then I stopped and it went back to acceptable values.

**Comment by thePercept** [comment]
I agree with you, even I tried siege to send many request at some concurrency levels, in my case the node processes on the test servers would start growing in percentages and then It won't go back to its original (I am using a 2 core vCPU , 2GB ram, server ) And finally the server would stop responding and have to hard reset from the console. But I will try to implement these points for testing . 

But the numbers are not going down in this case while I am testing on my local machine

I made the changes mentioned by you in a different repo and here's the link if you want to see what I've changed :

[Here's the link](https://github.com/thePercept/new-test-nuxt-mem-leak-refactor.git)

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by thePercept** [comment]
Hi Dan 

This issue is not anything critical or related to security.  It can be ignored as it's not relevant for Nuxt 3. I have already switched to Nuxt 3 with some new projects. 

Thanks for your kind attention & addressing this issue  🙏.
