### ISSUE TITLE
The values ​​in the payload are lost in the VUE part

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/nuxt#20630]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.4.3`
- Nitro Version:    `2.3.3`
- Package Manager:  `npm@9.5.1`
- Builder:          `vite`
- User Config:      `srcDir`, `modules`, `robots`, `vite`, `i18n`, `nitro`, `telemetry`, `algolia`, `app`, `auth`, `viewport`, `css`, `build`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.6.7`, `genesis-design-system/nuxt`, `@nuxtjs/algolia@1.6.0`, `formidable@2.1.1`, `nuxt-viewport@2.0.4`, `@nuxtjs/partytown@1.3.0`, `@vueuse/nuxt@9.13.0`, `nuxt-schema-org@2.1.3`, `nuxt-icon@0.1.8`, `@pinia/nuxt@0.4.9`, `@nuxtjs/i18n@8.0.0-beta.11`, `@sidebase/nuxt-auth@0.4.4`, `@nuxtjs/robots@3.0.0`
- Build Modules:    `-`

### Reproduction

I have a newDesigns object that I have in the Node part, but lose in the VUE part.
It seems that the payload is not correctly collecting the information to the VUE part (client)

Debugger NODE Side
![image](https://user-images.githubusercontent.com/77386602/235686033-6a3ce161-4616-45a1-84cc-92625f604033.png)

Fail in VUE
![image](https://user-images.githubusercontent.com/77386602/235686402-f34e942d-24f1-4070-9e5e-5a1fd845d464.png)
![image](https://user-images.githubusercontent.com/77386602/235686488-3343f708-ebb0-4e82-aacb-de1cdfa1c5dc.png)

### Describe the bug

I have a newDesigns object that I have in the Node part, but lose in the VUE part.
It seems that the payload is not correctly collecting the information to the VUE part (client)

Debugger NODE Side
![image](https://user-images.githubusercontent.com/77386602/235686033-6a3ce161-4616-45a1-84cc-92625f604033.png)

Fail in VUE
![image](https://user-images.githubusercontent.com/77386602/235686402-f34e942d-24f1-4070-9e5e-5a1fd845d464.png)
![image](https://user-images.githubusercontent.com/77386602/235686488-3343f708-ebb0-4e82-aacb-de1cdfa1c5dc.png)

**Comment by danielroe** [comment]
Would you provide a [minimal reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
