### ISSUE TITLE
Terser and terserOptions seem to have no effect in Nuxt3

### ISSUE THREAD

**Issue by spreadpando** [nuxt/nuxt#20631]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.14.0
- Nuxt Version:     3.4.2
- Nitro Version:    2.3.3
- Package Manager:  npm@9.6.4
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

```
 return {
    typescript: {
      shim: false
    },
    ssr: useServer,
    builder: 'webpack',
    },
    useRuntimeConfig: true,
    devServer: {
      https: devHttps
    },
    rootDir: resolve('./src'),
    },
    hooks: {
      'webpack:config' (configs) {
        const clientConfig = configs.find(config => config.name === 'client')
        if (!clientConfig || !clientConfig.module || !clientConfig.module.rules) return
        ...
       }
    },
    webpack: {
      terser: { 
        terserOptions: {
          compress: {
            drop_console: true  // <-- This has no effect
          },
        }
      },
      css: {
        preprocessorOptions: {
          scss: {
            additionalData: '@use "@/assets/scss/_vars.scss" as *;'
          }
        }
      }
    }
  }
```

### Describe the bug

the terser field seems to have no impact when setting builder to 'webpack' and adding the terser and terserOptions properties to the the webpack field of nuxt.config.js as shown. It's also strange that when running `npx nuxi info` with the above config that the builder is reported as Vite.

**Comment by manniL** [comment]
Hey! Could you kindly provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by danielroe** [comment]
`@nuxt/webpack-builder` currently uses esbuild to minimise the output. We should allow this to be configurable (ie. configure the options passed to it) and either remove the `terser` section from the schema or enable terser instead if it is enabled.

**Comment by spreadpando** [comment]
@danielroe would changing the esbuild config in the vite field also work for webpack builds? Is there anyway to strip comments from a nuxt 3 webpack build at present?
