### ISSUE TITLE
Redirecting to external URL in middleware causes Page Not Found errors

### ISSUE THREAD

**Issue by Laruxo** [nuxt/nuxt#20646]
### Environment

- Operating System: Darwin
- Node Version:     v16.19.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.3.3
- Package Manager:  npm@8.19.3
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-3xhusn?file=middleware/my-middleware.global.ts

### Describe the bug

When middleware uses `navigateTo` redirecting to external URL, multiple `Page Not Found` errors are received in `app:error` hook. This happens because `navigateTo` returns false in [this part of the code](https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/app/plugins/router.ts#L241).

I am not sure if it is even possible to abort the navigation without throwing an error, so this might be a technical limitation of `vue-router`.

Related to https://github.com/nuxt/nuxt/issues/20294

**Comment by danielroe** [comment]
This is no longer reproducible.
