### ISSUE TITLE
Loading external javascript on hosted Nuxt app (AWS Amplify)

### ISSUE THREAD

**Issue by simoroma** [nuxt/nuxt#20645]
### Environment

- Operating System: Linux
- Node Version:     v16.19.1
- Nuxt Version:     3.4.3
- Nitro Version:    2.3.3
- Package Manager:  npm@8.19.3
- Builder:          vite
- User Config:      app
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

You can find the code here: https://github.com/simoroma/test_external_javascript

Also hosted on AWS Amplify here: https://main.d29qqvykn4nywd.amplifyapp.com/

### Describe the bug

This happens on built Nuxt code that is hosted on AWS Amplify. I honestly don't know if it is an AWS Amplify issue. Though, everything else works correctly.

I have an external javascript file added to `nuxt.config.ts`:

```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  app: {
    head: {
      script: [
        {
          hid: "my_external_javascript",
          src: "my_external_javascript.js",
        },
      ],
    },
  },
});
```

And two pages in the folder `pages`: `index.vue` and `page.vue`. 

If I load `/` (the root) the javascript is loaded correctly. If I load `/page` the javascript is not loaded.

**Comment by ucw** [comment]
Path to files in public folder should starts with / character like src: /my_external_javascript.js

**Comment by simoroma** [comment]
Thanks @ucw ! It was really matter of adding only `/`
