### ISSUE TITLE
Route Groups

### ISSUE THREAD

**Issue by Shyam-Chen** [nuxt/nuxt#20641]
### Describe the feature

> With file system routing, folders map directly to URL Paths. However, there might be times when you want to create folders for the sake of organization without affecting the URL structure.

```css
pages/
├── (home)
│   └── index.vue -> /
├── about
│   └── index.vue 
└── contact
    └── index.vue
```

```css
pages
├── (backstage)
│   └── dashboard.vue -> /dashboard
└── (portal)
    └── login.vue -> /login
```

```css
pages
├── (app)
│   └── ...
├── (marketing)
│   └── ...
└── admin
    └── ...
```

```css
pages
└── users
    ├── (home)
    │   └── index.vue -> /users
    ├── profile
    │   └── index.vue -> /users/profile
    └── posts
        └── index.vue -> /users/posts
```

Refs:

- [SvelteKit (`svelte`)](https://kit.svelte.dev/docs/advanced-routing#advanced-layouts-group)
- [Next.js (`react`)](https://nextjs.org/docs/app/building-your-application/routing/route-groups)
- [SolidStart (`solid-js`)](https://docs.solidjs.com/solid-start/building-your-application/routing#route-groups)
- [QwikCity (`@builder.io/qwik`)](https://qwik.builder.io/docs/advanced/routing/#grouped-layouts)
- [Analog (`@angular/core`)](https://analogjs.org/docs/features/routing/overview#route-groups)
- [Deno Fresh (`preact`)](https://fresh.deno.dev/docs/concepts/routing#route-groups)

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by pi0** [comment]
I would love to see this feature coming to Nuxt and Nitro 🔥

**Comment by ThimoDEV** [comment]
Is this something worth having besides all the new features coming in Nuxt 4 or maybe having it in a minor release after V4?

**Comment by gregmsanderson** [comment]
@ThimoDEV I think it is worth having. It makes the pages folder much neater.

**Comment by oumarbarry** [comment]
@danielroe 
worth to have this feature in the [unjs/unrouting](https://github.com/unjs/unrouting) library

**Comment by danielroe** [comment]
That's totally my plan!

**Comment by provok-me** [comment]
@danielroe @pi0 
It would be great to have an easy way to find out (in a middleware, for example) if the "to" page is part of a group.
This way, we could redirect every page of a specific group to a specific page.

Maybe a composable accepting the "to" page and the group name as an argument or something like that.

**Comment by manniL** [comment]
@provok-me could you raise a separate issue for it?

**Comment by Filip1139** [comment]
VS code autocoplite shows hint "(auth)/login" instead login

**Comment by provok-me** [comment]
> [@provok-me](https://github.com/provok-me) could you raise a separate issue for it?

No, sorry.
We switched all our projects from Vue + Nuxt to React + Next to work with more robust project foundations.

I wish you the very best @manniL.
