### ISSUE TITLE
Google WebCache issue

### ISSUE THREAD

**Issue by SamyBENYOUB** [nuxt/nuxt#20653]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `pnpm@7.32.2`
- Builder:          `vite`
- User Config:      `experimental`, `runtimeConfig`, `vite`, `hooks`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://webcache.googleusercontent.com/search?q=cache:y8j45sa4h-gJ:https://nuxt.com/&cd=15&hl=fr&ct=clnk&gl=fr

https://codesandbox.io/p/github/nuxt/starter/csb-8m6t9s/draft/silly-murdock?file=%2Fnuxt-app%2Fpages%2Findex.vue&selection=%5B%7B%22endColumn%22%3A32%2C%22endLineNumber%22%3A3%2C%22startColumn%22%3A32%2C%22startLineNumber%22%3A3%7D%5D

https://8m6t9s-3000.csb.app/ => 200
cache:https://8m6t9s-3000.csb.app => 404

### Describe the bug

Hi :) ,

We have recently found that we have an issue with google cache with our project.
Seems like the pages are correctly display server side, but when the client takes the hand, a 404 appear.

This is reproducible on nuxt.com page.

![image](https://user-images.githubusercontent.com/104013230/235933996-a77ccb93-5a17-48fd-aed0-0320bd432c6a.png)

This issue (https://github.com/vuejs/vue-router/issues/2042) was present on the previous version and solutions was find but doesn't seem to be Nuxt 3 compatible.

Any idea?

### Logs

```shell-script
[nuxt] error caught during app initialization Error: Page not found: /search?q
```

**Comment by danielroe** [comment]
Would you see if you can create a minimal [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

That will help us rule out whether this is an issue in nuxt/content, nuxt or vue-router.

**Comment by SamyBENYOUB** [comment]
It's done , I updated the description :)

**Comment by 21stc-09** [comment]
can i ask you a question ? @danielroe 
How Nuxt official website handles Google Cache issues ? i saw the https://nuxt.com can be loaded normally by https://webcache.googleusercontent.com. but after reload it becomes 404.
our site won't be 404 but meet the cors problem, but after deal the cors problem,we meet other problem.
