### ISSUE TITLE
@nuxt-vitest throws ERR_INVALID_URL when using setup() from @nuxt/test-utils in spec

### ISSUE THREAD

**Issue by lassediercks** [nuxt/nuxt#20651]
### Environment

- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.3
- Nitro Version:    2.3.3
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      modules
- Runtime Modules:  nuxt-vitest@0.6.12
- Build Modules:    -

### Reproduction

In https://stackblitz.com/edit/github-wtj3ft-nhb1dj?file=app.spec.js,nuxt.config.ts,app.vue,vitest.config.js,package.json

create a new terminal and run:

```shell
yarn run vitest
```

### Describe the bug

https://nuxt.com/docs/getting-started/testing#testing states to test context option one should use `await setup`

using that setup throws the error

```
Error while requiring module `nuxt-vitest`: TypeError [ERR_INVALID_URL]: Invalid URL
```

### Additional context

To migrate from nuxt2 to nuxt3 we replace fetch with `useAsyncData`. To minimise migration work we register an axios instance via a plugin to the nuxt context and return data inside `useAsyncData`

In order to mock the axios registered to `useNuxtApp()` we use the method described in https://nuxt.com/docs/getting-started/testing#testing

### Logs

```shell-script
yarn run v1.22.19
$ /home/projects/github-wtj3ft-nhb1dj/node_modules/.bin/vitest run

 RUN  v0.30.1 /home/projects/github-wtj3ft-nhb1dj

stdout | unknown test
<Suspense> is an experimental feature and its API will likely change.
setup

 ❯ app.spec.js  (1 test) 578ms
stdout | unknown test
<empty line>

 Test Files  1 failed (1)
      Tests   (1)
   Start at  15:26:17
   Duration  2.69s (transform 170ms, setup 0ms, collect 343ms, tests 578ms, environment 510ms, prepare 219ms)

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by danielroe** [comment]
You shouldn't use both nuxt-vitest + nuxt/test-utils in the same file. They are two different approaches - you can have them both in the same project but they need to run in different environments.

Here is your reproduction, updated to use both:

https://stackblitz.com/edit/github-wtj3ft-jqheul?file=app.unit.spec.ts,app.nuxt.spec.ts,package.json

A PR to improve the docs in this regard would be very much appreciated.
