### ISSUE TITLE
Changing useFetch baseURL results in hydration error

### ISSUE THREAD

**Issue by command-tab** [nuxt/nuxt#20664]
### Environment

```
- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.3.3
- Package Manager:  npm@9.5.1
- Builder:          vite
- User Config:      vite
- Runtime Modules:  -
- Build Modules:    -
```

### Reproduction

`app.vue`

```
<template>
  <h2>{{ device.name }}</h2>
</template>

<script setup>
const { data: device } = await useFetch('/api/devices/18', {
  baseURL: process.server ? 'http://127.0.0.1:5000' : 'https://myapp-local.example.com'
})
</script>
```

### Describe the bug

My app and API run behind an nginx reverse proxy in development to more closely mimic how it runs in production under Kubernetes. In development, I have nginx performing TLS termination for both, and it proxies `/` to Nuxt and `/api` to my API. I would like Nuxt to communicate directly with the API when performing `useFetch` calls during SSR to avoid going "out and back in" through the reverse proxy, as it's an unnecessary detour. Therefore, I set my `useFetch` options' `baseURL` to the direct address of the API when `process.server` is true under SSR, and to the address of the reverse proxy when `process.server` is false and the request is made by a remote browser.

When I visit the Nuxt app (at `https://myapp-local.example.com` which dutifully reverse proxies to Nuxt), SSR occurs, Nuxt successfully performs the `useFetch` GET to my API directly (at `http://127.0.0.1:5000/api/devices/18`), the page renders, and then the client errors:

```
[Vue warn]: Unhandled error during execution of render function 
  at <App key=3 > 
  at <NuxtRoot>
warn2 @ vue.js?v=b1d59ca7:1381
logError @ vue.js?v=b1d59ca7:1633
handleError @ vue.js?v=b1d59ca7:1625
renderComponentRoot @ vue.js?v=b1d59ca7:2195
hydrateSubTree @ vue.js?v=b1d59ca7:6094
componentUpdateFn @ vue.js?v=b1d59ca7:6115
run @ vue.js?v=b1d59ca7:405
instance.update @ vue.js?v=b1d59ca7:6220
setupRenderEffect @ vue.js?v=b1d59ca7:6228
(anonymous) @ vue.js?v=b1d59ca7:2696
Promise.then (async)
registerDep @ vue.js?v=b1d59ca7:2682
mountComponent @ vue.js?v=b1d59ca7:6039
hydrateNode @ vue.js?v=b1d59ca7:5425
hydrateSuspense @ vue.js?v=b1d59ca7:2749
hydrateNode @ vue.js?v=b1d59ca7:5448
hydrateSubTree @ vue.js?v=b1d59ca7:6101
componentUpdateFn @ vue.js?v=b1d59ca7:6115
run @ vue.js?v=b1d59ca7:405
instance.update @ vue.js?v=b1d59ca7:6220
setupRenderEffect @ vue.js?v=b1d59ca7:6228
mountComponent @ vue.js?v=b1d59ca7:6046
hydrateNode @ vue.js?v=b1d59ca7:5425
hydrate2 @ vue.js?v=b1d59ca7:5342
mount @ vue.js?v=b1d59ca7:5209
app.mount @ vue.js?v=b1d59ca7:9291
initApp @ entry.js:49
await in initApp (async)
(anonymous) @ entry.js:57
app.vue?t=1683177727330:29 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'name')
    at Proxy._sfc_render (app.vue?t=1683177727330:29:88)
    at renderComponentRoot (vue.js?v=b1d59ca7:2172:39)
    at hydrateSubTree (vue.js?v=b1d59ca7:6094:32)
    at ReactiveEffect.componentUpdateFn [as fn] (vue.js?v=b1d59ca7:6115:13)
    at ReactiveEffect.run (vue.js?v=b1d59ca7:405:19)
    at instance.update (vue.js?v=b1d59ca7:6220:52)
    at setupRenderEffect (vue.js?v=b1d59ca7:6228:5)
    at vue.js?v=b1d59ca7:2696:9
````

Here's what has me puzzled: If I adjust the `baseURL` to be the same static value between SSR and client (i.e. don't do a ternary on `process.server`), the error doesn't occur and the page renders fine and hydrates fine. It seems like the hydration process is erroring because the SSR request it made to a given URL is different than the one the browser client  _would have made_.

Am I wrong to be changing `useFetch` `baseURL` depending on the SSR vs. browser request context?

I've found that even if I omit `baseURL` and interpolate the base directly into the `useFetch` URL like this, I still get the same error.

```
<script setup>
const prefix = process.server ? 'http://127.0.0.1:5000' : 'https://myapp-local.example.com'
const { data: device } = await useFetch(`${prefix}/api/devices/18`)
</script>
```

Likewise, if I make the `baseURL` go through the very same reverse proxy (to rule out any potential misconfiguration there) but just with an alternate hostname, I get the same error.

```
<script setup>
const prefix = process.server ? 'https://myapp-local.example.com' : 'https://myapp-local-alternate.example.com'
const { data: device } = await useFetch(`${prefix}/api/devices/18`)
</script>
```

It sure seems like hydrating the result of a `useFetch` call when the resulting URL is different between SSR and client is not working, and I'm unclear on why, or what I can do to work around it.

Thanks for any insight you can provide!

**Comment by danielroe** [comment]
The issue is that the URL differs between client + server, which means the auto-generated key will differ. To resolve, you can manually set a key (for example, the URL).

**Comment by command-tab** [comment]
Ahh, that's the ticket! Thank you! I owe you a beverage of your choice 🥂 If you'd like a blurb about this for documentation, I'm happy to write something up in a PR.

**Comment by CheIIau** [comment]
https://github.com/nuxt/nuxt/issues/20664

> Ahh, that's the ticket! Thank you! I owe you a beverage of your choice 🥂 If you'd like a blurb about this for documentation, I'm happy to write something up in a PR.

Hi, I'm facing the same problem, can you please help me? This stuff is kinda new to me and i can't figure it out. What should I add to my code so that I don't have to go back and forth to load the data?

vue file 
`<script setup lang="ts">
import { useAsyncData } from '#imports'
const { data: users, pending } = await useAsyncData('test', () => $fetch('/api/testdata/'))
</script>`

Dockerfile in client folder
`FROM node:18-alpine as builder

WORKDIR /app

COPY package.json .
RUN npm install
COPY . .

ENV NODE_ENV production

RUN npm run build

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000

EXPOSE 3000 

ENTRYPOINT ["node", ".output/server/index.mjs"]
`
nginx config
`upstream client {
  server client:3000;
}

upstream api {
  server api:5000;
}

server {
  listen 80;

  location /api {
    proxy_http_version 1.1;
    rewrite /api/(.*) /$1 break;
    proxy_pass http://api;
  }

  location / {
    proxy_pass http://client;
  }

}`

**Comment by command-tab** [comment]
I had to set a useFetch `key` to avoid using the auto-generated key, as the auto-generated approach includes the base URL, and my API base URL is different depending on if the request is being made server side or client-side. (My Nuxt app can reach my Python API directly using a Kubernetes Service, but requests made from a browser must go through a Kubernetes Ingress/load balancer).

I also ran into an issue where subsequent requests to the same path would invalidate existing data, even if the HTTP method was different, so I had to include the HTTP method in my `key` as well as the path. Some discussion here: https://discord.com/channels/473401852243869706/1098270519075291237

**Comment by mmghv** [comment]
Creating a custom `$fetch` instance with a dynamic `baseURL` then using this instance with `useFetch` seems to solve the problem because that way no options are directly changed on `useFetch` itself.

https://nuxt.com/docs/guide/recipes/custom-usefetch#custom-usefetch
