### ISSUE TITLE
CSS Loading Order Inconsistent (SSR vs no SSR)

### ISSUE THREAD

**Issue by dzz007** [nuxt/nuxt#20662]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.3.3
- Package Manager:  npm@9.6.5
- Builder:          vite
- User Config:      srcDir, ssr, modules, dir
- Build Modules:    -
------------------------------

### Reproduction

Minimal repro: https://stackblitz.com/edit/nuxt-starter-ycw6ts

### Describe the bug

The output order between <link rel="stylesheet"> in template and <style> in component is different between SSR=true and SSR=false. 

For example the following App.vue: 
```
<template>
...
<Head>
<Link id="theme-link" rel="stylesheet" href="/public.css" />  NOTE: the reason I use Link here is that later in the code I can use id to dynamically change this public.css's location. 
...
</template>
<style src="@/assets/override.scss" />
```
My expectation would be override.scss content has to happen after public.css since override.scss could be overriding stuff from public.css. I have noticed that when SSR=true, the order is expected. But when I set SSR=false, the override.scss content actually is before public.css. 

Minimal Repro Link is here: https://stackblitz.com/edit/nuxt-starter-ycw6ts (button is blue when SSR=true, but is red when SSR=false)

**Comment by dzz007** [comment]
Bump on this

**Comment by danielroe** [comment]
Actually, looking at this this is because when `ssr: false`, the `public.css` file can't be rendered in the initial HTML as you are adding it within your Vue component (but the entry CSS file can be). And because it is loaded second it will be deprioritised by the browser.

I don't think this is a Nuxt issue.
