### ISSUE TITLE
asyncData not updated for child routes

### ISSUE THREAD

**Issue by IlyaSemenov** [nuxt/nuxt#20668]
### Environment

- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.3
- Nitro Version:    2.3.3
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-3zwbfd

Click the 4 links in the menu one by one and you will see:
- Path=/parent1/foo ID=foo
- Path=/parent1/bar ID=bar
- Path=/parent2/foo ID=foo
- Path=/parent2/bar ID=foo <------- here is the problem

### Describe the bug

`asyncData` doesn't update when navigating between sibling child routes (such as between two different `pages/some/[id].vue` where there is also `pages/some.vue` with `<router-view />`).

It however updates when navigating between prefixed but root level sibling routes (such as between `pages/some/[id].vue` where there is **no** `pages/some.vue`).

### Expected behavior

Clicking `/parent2/foo` then `/parent2/bar` calls `asyncData` automatically (or at least after adding adding `definePageMeta` with `key: route => route.params.id` to `parent2/[id].vue`).

### Additional context

1) Adding `definePageMeta` with `key: route => route.params.id` doesn't change anything.

2) I think this might be related to #12361 but this bug is more important and imminent in my thinking.

3) Of course, `<router-view :key="$route.params.id" />` (or even `$route.fullPath`) kind of fixes it. But this is hardly an acceptable solution:
- This is weirdly inconsistent with no-intermediate-router behaviour (parent1 vs. parent2 in the reproduction).
- There could be `pages/parent2/new.vue` and other non-parameter pages, which will break on `$route.params.id`.
- `[id].vue` could be nested much deeply and have no logical relation to the upper level router-view.

The current workaround I use is moving each `[id].vue` into `[id]/index.vue` and creating `[id].vue` like this:

```vue
<script lang="ts">
export default defineComponent({}) // Trigger typescript in template
</script>

<template>
  <router-view :key="$route.params.id as string" />
</template>
```

**Comment by danielroe** [comment]
You should use `<NuxtPage />` rather than `<RouterView />`.

```diff
  <template>
-    <router-view />
+   <nuxt-page />
  </template>
