### ISSUE TITLE
Nuxt 3 hooks 

### ISSUE THREAD

**Issue by glennovische** [nuxt/nuxt#20681]
### Environment

[npx nuxi info]

### Reproduction

https://stackblitz.com/edit/github-exuhyz?file=plugins%2Fspinner.ts

### Describe the bug

Simple nuxt 3 hook not working like written out in the documentation: https://nuxt.com/docs/guide/going-further/hooks
Would expect to get in page:start page:finish hooks but thats not the case

**Comment by danielroe** [comment]
The hook requires you have pages.

And it is worth noting it doesn't run on initial client side load but only on subsequent navigation.

**Comment by glennovische** [comment]
I implemented pages in my Reproduction
https://stackblitz.com/edit/github-exuhyz navigating from one to two I would expect my boolean to get triggered

**Comment by glennovische** [comment]
Ok updated my reproduction:
https://stackblitz.com/edit/github-exuhyz

Apparently the nuxt hook page.finish / page.start are not working if you are using layouts.

**Comment by VasanthThoraliKumaran** [comment]
> @danielroe Ok updated my reproduction: https://stackblitz.com/edit/github-exuhyz
> 
> Apparently the nuxt hook page.finish / page.start are not working if you are using layouts.

@glennovische Did you found any solution for this?

**Comment by glennovische** [comment]
@VasanthThoraliKumaran No, had to implement a work around in my app.vue 

with a ref - boolean 
`onEvent(EventSpinnerLoading, (loading: boolean) => {
  isLoading.value = loading;
});`

I still think it's weird that this does not work out of the box using layouts

**Comment by danielroe** [comment]
We do plan to have loading event support, but it's not yet implemented: https://github.com/nuxt/nuxt/issues/14221.
