### ISSUE TITLE
[Nuxt 2] Executes asyncData after page component navigated away from

### ISSUE THREAD

**Issue by rchl** [nuxt/nuxt#20691]
### Environment

```
  System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1
    Memory: 216.36 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Firefox: 112.0.2
    Safari: 16.4
    Safari Technology Preview: 16.4
```

### Reproduction

https://stackblitz.com/edit/github-6mgkvf?file=pages/index.vue

### Describe the bug

In case there is a global middleware (or a page has a middleware) that runs for a longer time, it's possible for the user to navigate to another page (either using browser back button or clicking another link) while the middleware is running. In that case the `asyncData` of the target page will still execute after the long-running middleware is finished but at that point the current route is no longer what that page expects so `context.route` will be unexpectedly pointing to another route.

That can lead to crashes due to unexpected input or if, for example, the page triggers and `error` function then it will actually apply to the page that is currently loaded rather than the one whose `asyncData` is running.

**Comment by rchl** [comment]
Note that I've identified a couple of cases where things could go wrong:
 - a long-running middleware, then asyncData that calls either `error(...)` or throws an exception
 - a long-running asyncData that calls either `error(...)` or throws an exception

If the user navigates away from the page after the long-running operation starts then things will go wrong (the error page will replace the current page).

It fairly easy to handle the first case with long-running middlewares since we can fairly easily interrupt page loading after middlewares have finished. The case with long running asyncData is more tricky since it's not possible to interrupt asyncData and if we'd want to suppress the effects of calling `error(...)` then it could also be tricky to do (the exception case should be easy to handle).

But of course those would be a bit of band-aids for a problem that probably is not fully fixable (at least with current architecture). There is no way to just interrupt execution of a middleware or asyncData at given moment and those handlers could do other things that would affect the state after navigating away.

That said, handling all or most of the cases that I've listed at the beginning of this comment would be beneficial in many if not most cases, so I could prepare some PR to that effect. Basically the change would be to explicitly interrupt `render` (in `client.js`) after certain async operations.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by rchl** [comment]
Two of the linked issues fixed it either partially or fully (I don't remember) but it's in a pretty good state now.
