### ISSUE TITLE
`devProxy` supports passing `listening-for-proxy-events` functionality

### ISSUE THREAD

**Issue by jiangmaniu** [nuxt/nuxt#20699]
### Describe the feature

The current `devProxy` can only set parameters of the [`ServerOptions`](https://github.com/http-party/node-http-proxy#options) type. I want to add some additional operations to the request header in [`Listening for proxy events`](https://github.com/http-party/node-http-proxy#listening-for-proxy-events). How can I achieve this? 

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
interesting idea - let's track upstream in nitro
