### ISSUE TITLE
Page setup and middleware running twice after SSR middleware redirect

### ISSUE THREAD

**Issue by brunohstein** [nuxt/nuxt#20696]
### Environment

- Node Version:     v16.14.0
- Nuxt Version:     3.4.2
- Nitro Version:    2.3.3
- Package Manager:  yarn@1.22.10
- Builder:          vite
- User Config:      target, ssr, app, css, build, components, nitro, routeRules, vite, runtimeConfig, plugins, serverHandlers, modules
- Runtime Modules:  @pinia/nuxt@^0.4.0
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-3enzca-hrq7dz?file=pages/index.vue

Click in "Click here to hard reload A". Check logs to check when middleware and page setup run.

### Describe the bug

With SSR enabled, a request to path `/a` is redirected with a global middleware to path `/b`.

Expected behavior: global middleware runs and performs the redirect. It runs again and does not perform another redirect. Page B setup runs once.

Actual behavior: global middleware runs and performs the redirect. It runs again and does not perform another redirect. Page B setup runs. Global middleware runs again. Page B setup runs again.

**Comment by brunohstein** [comment]
Thanks for your great work, @danielroe.

Running the reproduction against version 3.6.0, I'm intrigued by the second middleware log:

<img width="600" alt="Captura de Tela 2023-06-23 às 13 01 44" src="https://github.com/nuxt/nuxt/assets/1143565/357ce2c1-d3d6-4022-b5d5-2527ecbb7d57">

1. Hard reload link to /a
2. Middleware runs on server, logs /a to /a, and redirects to /b

As the redirect happens on the server and triggers another hard reload (302), I was expecting to see just one extra log: from /b to /b. But there's a /a to /b being logged as well. Is that expected?

**Comment by danielroe** [comment]
This is how vue-router processes middleware. It will call the middleware first for the move -> `/a`. Then it will call it again for the new route `/b`.

Example without Nuxt: https://stackblitz.com/edit/github-j5qfzp?file=src/router.ts

**Comment by ThinkingAbout** [comment]
Hi @danielroe, 
thanks for your answer, but it's still not so clear to me why "/a to /a" or "/b to /b" are invoked.

According to the documentation:

> Global route middleware, which are placed in the middleware/ directory (with a .global suffix) and will be automatically run on every route change.

So,  "/a to /a" or "/b to /b" there shouldn't be any route change.
I would expect that:

- from /some-route (or `undefined`, if first access) to /a;
- from /a to /b;

Am I misunderstanding some basic concept?
Thanks!

**Comment by danielroe** [comment]
Middleware also run on the initial page load.

**Comment by brunohstein** [comment]
@ThinkingAbout @danielroe I actually thought that the unexpected log was `/a to /b`.

As I understand, there's

- `a to a` as the initial navigation that requests the route `a` from the server
- `b to b` because the request to `a` is redirecting with a status 302, so it basically means another navigation similar to the initial request, but to `b`

What I don't understand is in which moment `/a to /b` is triggered. Certainly did not expect both `a to b` and `b to b` to exist.

**Comment by danielroe** [comment]
The middleware also needs to run for the navigation to `/b` on the first request. you could, for example, have another middleware guarding that route that wants to redirect again.

**Comment by vedmant** [comment]
Is there any way to avoid this behavior? It's creating havoc with my auth implementation and creates double redirects, inconsistent behavior with cookies.
