### ISSUE TITLE
Setup function of the destination page after redirect with navigateTo invoked twice

### ISSUE THREAD

**Issue by prashantpalikhe** [nuxt/nuxt#20703]
### Environment

 ------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.0
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-lvptgn

### Describe the bug

There are two pages.

1. i-get-redirected.vue
2. i-get-displayed.vue

`i-get-redirected` gets redirected to `i-get-displayed` via a global route middleware `redirect.global.ts`. `i-get-displayed`'s setup function logs `'I should be logged just once'` to the console. 

After the redirect happens, I expect the log to appear just once. But it appears twice.

<img width="385" alt="image" src="https://user-images.githubusercontent.com/2657709/236620500-fc5a6496-8954-40b8-8d7d-770e7b53fee3.png">

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/20696 as it was opened slightly earlier
