### ISSUE TITLE
Environment variables are undefined with vercel-edge preset

### ISSUE THREAD

**Issue by xanderbarkhatov** [nuxt/nuxt#20704]
### Environment

- Operating System: Linux
- Node Version:     v20.0.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.0
- Package Manager:  pnpm@8.3.1
- Builder:          vite
- User Config:      modules, runtimeConfig, typescript, colorMode, tailwindcss, build
- Runtime Modules:  nuxt-icon@0.3.3, @vueuse/nuxt@9.13.0, @nuxtjs/tailwindcss@6.6.7, nuxt-headlessui@1.1.4, nuxt-vercel-analytics@0.2.1, @vue-macros/nuxt@1.3.4, @nuxtjs/color-mode@3.2.0, @nuxt/image-edge@1.0.0-28004510.a0dc8e8
- Build Modules:    -

### Reproduction

-

### Describe the bug

Environment variables are undefined when using `NITRO_PRESET=vercel-edge`.
With regular Vercel deployment everything works fine.

**Comment by danielroe** [comment]
I believe @pi0 is already looking into this upstream.

**Comment by schmidfelix** [comment]
Sorry for the ping, but this is an important issue for me - are there any news or a workaround for that? Nevertheless, thanks for the awesome work on Nuxt3 :)

**Comment by xanderbarkhatov** [comment]
It seems to work fine now. We can close the issue.
