### ISSUE TITLE
No Output Directory named "dist" found after the Build completed Error when deploying the project to vercel?

### ISSUE THREAD

**Issue by terwer** [nuxt/nuxt#20717]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v16.20.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.0
- Package Manager:  pnpm@8.4.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

monorepo root

https://github.com/terwer/zhi-blog/tree/dist

nuxt project 

https://github.com/terwer/zhi-blog/tree/dist/apps/zhi-blog

### Describe the bug

I build a fresh nuxt project on vercel,dev is ok, bot on vercel it says 

Error: No Output Directory named "dist" found after the Build completed. You can configure the Output Directory in your Project Settings.

Build Command
```
pnpm vercelBuild -F zhi-blog
```

Output Directory
```
apps/zhi-blog/dist
```

Install Command

```
pnpm install
```

### Logs

```shell-script
11:30:12.263	zhi-blog:vercelBuild: [success] You can now deploy `.vercel/output/static` to any static hosting!
11:30:12.326	
11:30:12.326	  Tasks:    7 successful, 7 total
11:30:12.326	 Cached:    0 cached, 7 total
11:30:12.326	   Time:    1m8.276s 
11:30:12.326	Summary:    /vercel/path0/.turbo/runs/2PUfO10JoQGA5ierGXHlw9TFXix.json
11:30:12.326	
11:30:12.507	Error: No Output Directory named "dist" found after the Build completed. You can configure the Output Directory in your Project Settings.
11:30:12.507	Learn More: https://vercel.link/missing-public-directory
11:30:12.704	Deployment completed
11:30:12.656	STATIC_BUILD_NO_OUT_DIR: No Output Directory named "dist" found after the Build completed. You can configure the Output Directory in your Project Settings.
```

**Comment by terwer** [comment]
I give up using monirepo.As a single repo, it works now.

**Comment by tknickman** [comment]
Hey @terwer, Turborepo team here. I took a quick look at this, it looks like on Vercel, and when using:

```js
export default {
  nitro: {
    preset: 'vercel-edge',
  },
};
```

Outputs are written to `.vercel/output/static`. However, Nuxt is nice enough to alias this to `dist/`. So to enable caching with Turborepo on Vercel, your config should look like:

```json file=turbo.json 
{
  "pipeline": {
    "generate": {
      "outputs": ["dist/**"]
    }
  }
}
```

And ensure the output directory is set to `dist/` (the Nuxt default) on your Vercel project.

If you have more issues with Nuxt / Turbo feel free to open an issue over at [vercel/turbo](https://github.com/vercel/turbo/issues?q=is:issue+is:open+sort:updated-desc) and we'll happily take a look.

**Comment by gyhyfj** [comment]
> Hey @terwer, Turborepo team here. I took a quick look at this, it looks like on Vercel, and when using:
> 
> ```js
> export default {
>   nitro: {
>     preset: 'vercel-edge',
>   },
> };
> ```
> 
> Outputs are written to `.vercel/output/static`. However, Nuxt is nice enough to alias this to `dist/`. So to enable caching with Turborepo on Vercel, your config should look like:
> 
> ```json
> {
>   "pipeline": {
>     "generate": {
>       "outputs": ["dist/**"]
>     }
>   }
> }
> ```
> 
> This is assuming a `package.json` of:
> 
> ```
> {
>   "name": "nuxt-demo",
>   "private": true,
>   "scripts": {
>     "build": "nuxt build",
>     "dev": "nuxt dev",
>     "generate": "nuxt generate",
>     "preview": "nuxt preview",
>     "postinstall": "nuxt prepare"
>   },
>   "devDependencies": {
>     "nuxt": "^3.0.0"
>   }
> }
> ```
> 
> And ensure the output directory is set to `dist/` (the Nuxt default) on your Vercel project.
> 
> If you have more issues with Nuxt / Turbo feel free to open an issue over at [vercel/turbo](https://github.com/vercel/turbo/issues?q=is:issue+is:open+sort:updated-desc) and we'll happily take a look.

Hello, I encounter one trouble with ` preset: 'vercel-edge'`. 
In my project, I need to deploy my nuxt3 app to vercel-edge, and override build setting by `vercel.json` as this:
```json
{
  "installCommand": "pnpm install",
  "buildCommand": "pnpm build:enprod",
  "outputDirectory": "apps/dalle-nuxt3/.vercel/output/static",
  "framework": "nuxtjs"
}
```
I found that final outputs dir is `.vercel`, then I set `outputDirectory` to `path/to/.vercel` or `path/to/.vercel/output` or ` `path/to/.vercel`/output/static`  or `path/to/`, and then deploy it,
Every deployment is success, but after deploy, the result url is aloways `404`.
Is my config error?

**Comment by gyhyfj** [comment]
if set `outputDirectory` to `apps/dalle-nuxt3/.vercel/output/`, then deploy and then turn on `Directory Listing`
![image](https://github.com/nuxt/nuxt/assets/98264874/3c9ad61d-8fd6-4bb2-9820-f2d5e232d813)

**Comment by r3gisc** [comment]
Hi, i had the same type of issue with nx 18 monorepo

I managed to deploy using build-static command of NX

.vercel/project.json:
```
    "framework": "nuxtjs",
    "devCommand": null,
    "installCommand": "pnpm install",
    "buildCommand": "nx build-static NAME_OF_NX_APP",
    "outputDirectory": "apps/NAME_OF_NX_APP/.vercel/output/static",
```

**Comment by willwillems** [comment]
Experiencing this as well but somehow redeploying "fixes" the failed deployment. Tried everything from this issue.
