### ISSUE TITLE
fix: jose v4.14.2 leads to infinite type instantiation (TS2589)

### ISSUE THREAD

**Issue by dargmuesli** [nuxt/nuxt#20713]
### Environment

- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.0
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-ubqvmq?file=app.vue,package.json

### Describe the bug

Running `npm run lint` in the given reproduction yields
```
app.vue:10:13 - error TS2589: Type instantiation is excessively deep and possibly infinite.
10 console.log(x.value.username);
               ~~~~~~~~~~~~~~~~
Found 1 error in app.vue:10
```
but it shouldn't.

### Additional context

I've opened issue https://github.com/panva/jose/issues/534 with a real world use case and with a mention of the code snippet resulting in the error.

But [apparently](https://github.com/panva/jose/issues/534#issuecomment-1537292564) the problem lies in the project I'm using `jose` in, which would be Nuxt. To be fair, I'm not sure if it's a Nuxt problem. Happy about pointers into the right direction!

**Comment by danielroe** [comment]
Here's a reproduction without Nuxt: https://stackblitz.com/edit/stackblitz-starters-5bdptj.

When updating deps the error goes away: https://stackblitz.com/edit/stackblitz-starters-xlrpdj.
