### ISSUE TITLE
Nuxt Hook (page:start/ page:finish) not working with layouts

### ISSUE THREAD

**Issue by glennovische** [nuxt/nuxt#20737]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.14.2`
- Nuxt Version:     `3.4.3`
- Nitro Version:    `2.3.3`
- Package Manager:  `npm@9.5.0`
- Builder:          `vite`
- User Config:      `app`, `build`, `runtimeConfig`, `modules`, `css`, `plugins`, `postcss`, `vite`, `auth`
- Runtime Modules:  `@sidebase/nuxt-auth@0.5.0`, `nuxt-vitest@0.6.9`, `nuxt-lodash@2.4.1`, `@formkit/nuxt@1.0.0-beta.9-f64c966`, `@vueuse/nuxt@9.13.0`, `@pinia/nuxt@0.4.8`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-exuhyz

### Describe the bug

Apparently the nuxt hook page:finish / page:start are not working when using layouts in NUXT.

Everything is working like expected when you don't have a layouts folder. My console.logs are showing after adding a layouts folder its not working anymore.

**Comment by glennovische** [comment]
Anyone knows a solutions or workaround?

**Comment by TonhaoSantos** [comment]
Anyone knows a solutions or workaround?

**Comment by NozomuIkuta** [comment]
@glennovische 

You are using `RouterView` inside `layouts/default.vue`, which should be `<slot />` instead.
Check the docs: https://nuxt.com/docs/guide/directory-structure/layouts
