### ISSUE TITLE
Navigating to aliased pages doesn't work on client side

### ISSUE THREAD

**Issue by warflash** [nuxt/nuxt#20732]
### Environment

- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.0
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-jh62hm?file=pages%2Findex.vue,app.vue

### Describe the bug

Tried setting up a stackblitz for https://github.com/nuxt/nuxt/discussions/20731 showcasing the alias property of `definePageMeta` but noticed that NuxtLinks pointing to an aliased route don't seem to update the url. I recon this might be to avoid duplicate navigation since we're on the same component but vue router doesnt throw an error regarding that.

**Comment by danielroe** [comment]
I think the point here is that, from vue-router's perspective, these are the same route and so it's not a navigation at all - see https://router.vuejs.org/guide/essentials/redirect-and-alias.html#alias.

Here's a reproduction without Nuxt: https://stackblitz.com/edit/github-tnnwet.

**Comment by soylomass** [comment]
@warflash did you find any way to work around this? Have the same problem.
