### ISSUE TITLE
Static files fail to resolve resource paths

### ISSUE THREAD

**Issue by emdede** [nuxt/nuxt#20740]
### Environment

- Operating System: Linux (WSL)
- Node Version:     v18.16.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.0
- Package Manager:  npm@9.5.1
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

1. npx nuxi init my-app
2. cd my-app
3. npm i
4. npm run generate

### Describe the bug

When opening the `index.html` file of a static build, resource paths cannot be resolved. This might be a config issue or a system env issue but I think it's odd that with a fresh build this does not work. I couldn't find any direct mentions of how to avoid this in the docs.

This issue is present both when I open the file in WSL with a path like this: `file://wsl.localhost/Ubuntu/home/myHomeDir/test-app/.output/public/index.html` and also after I moved the directory to Windows filesystem with a path like this: `file:///C:/Users/MyUserName/Desktop/public/index.html`

I noticed that the generated tags all have absolute pathing instead of relative. I'm assuming it's for a reason, seeing that I couldn't find any directly related issues. But how would this even work?

![errors](https://github.com/nuxt/nuxt/assets/64293438/13cbea4b-ac4b-44da-ae50-c7005612946b)

### Additional context

I wanted to test SSG with the end goal of moving the generated files to some directory and serving them via Nginx. FWIW, I might be misunderstanding this situation but from where I am standing I would expect this to work.

**Comment by danielroe** [comment]
Unfortunately, you can't load a Nuxt/Vite site with a file URL directly - this is not a Nuxt issue.

You can try previewing the static files by running `npx serve .output/public` - this will launch a tiny web server for you.

**Comment by emdede** [comment]
Thank you @danielroe ❤️ for the quick handling. I was a bit flabbergasted to see it not working and not finding related issues. But now I do see that this does make a lot of sense. Any listening server would of course properly use the correct folder using static paths. I can move on to the next step now :)
