### ISSUE TITLE
Cross-site request pollution with useAsyncData

### ISSUE THREAD

**Issue by niklaswolf** [nuxt/nuxt#20741]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.4.3`
- Nitro Version:    `2.4.0`
- Package Manager:  `npm@9.5.0`
- Builder:          `vite`
- User Config:      `extends`, `shopware`, `runtimeConfig`, `modules`, `i18n`, `css`, `vite`, `router`, `nuxtShopwareCaching`, `prismic`, `app`
- Runtime Modules:  `modules/domainRuntimeInfo`, `@nuxtjs/prismic@3.0.0-rc.5`, `@mothership-gmbh/nuxt-shopware-caching@2.0.0`, `nuxt-schema-org@2.1.3`
- Build Modules:    `-`

### Reproduction

I'm working on a minimal reproduction.

### Describe the bug

When I request my app nearly at the same time with more than one request, there seems to be some cross-request pollution. See the screenshot. 
![Bildschirmfoto 2023-05-09 um 12 32 25](https://github.com/nuxt/nuxt/assets/16021919/11782901-ade5-4ca0-a6e4-7e046865e702)

The markup rendered on the server side is actually correct for each request and logging on the server side also shows that the values are present and correct for each request.
But if I inspect `window.__NUXT__` on the client side, the second request has the data of the other request in there, too, while the first request has it set to null.

I simplified the API-request that is normally done inside this useAsyncData.
```
const route = useRoute()

const returnValue = await useAsyncData('cmsResponse' + route.path, async () => {
  return {
    routeName: 'frontend.detail.page',
    foreignKey: '9855e4444b20459bbf9b94cc4f1c0c4c',
  }
})
```

Does anyone have an idea, why the second request can have the data of the first one?

**Comment by danielroe** [comment]
Is there a chance you could provide a [minimal reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by niklaswolf** [comment]
@danielroe I'm working on it :) 

But just to be sure: this is not expected behaviour isn't it? How can such a thing happen in general, maybe this helps me locating the essential parts faster. I unfortunately am not that familiar with how this works under the hood...

**Comment by niklaswolf** [comment]
Update: I can narrow this issue down to the nuxt-i18n module (https://v8.i18n.nuxtjs.org/).
So this is not directly an issue with nuxt itself it seems. Will keep this updated nevertheless if that's okay to have this documented somewhere.

**Comment by iijaachok** [comment]
Turns out it's not a nuxtjs/i18n issue, it's an async/await inside a nuxtRouteMiddleware, here's a reproduction of exactly the same issue without nuxtjs/i18n module enabled:
https://stackblitz.com/edit/github-i3vv2y-kyvq3p?file=middleware/asyncRouteMiddleware.global.ts

<img width="1632" alt="image" src="https://github.com/nuxt/nuxt/assets/8614062/2b9c0984-697f-4cb2-bf59-a031774a7b49">

**Comment by Atinux** [comment]
You you try by installing this version and confirm it solves your issues:

`package.json`
```json
"nuxt": "npm:nuxt3@pr-20910"
```

We locally tested with @danielroe and we could not reproduce anymore the cross-site request pollution with your repro @iijaachok

**Comment by iijaachok** [comment]
Had to rewrite the implementation of a test because of SSR payload structure changes, however after running a few tests I couldn't reproduce the issue anymore even with higher volume of requests - about 100 requests/sec.

Thanks for your help! 👍
