### ISSUE TITLE
Page does not load - blank screen

### ISSUE THREAD

**Issue by keuller** [nuxt/nuxt#20742]
### Environment

- Operating System: Darwin
- Node Version:     v16.15.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.0
- Package Manager:  pnpm@8.4.0
- Builder:          vite
- User Config:      css, app, runtimeConfig, modules, sitemap
- Runtime Modules:  @nuxt/image-edge@1.0.0-27919678.2f5b64b, nuxt-simple-sitemap@1.0.11, @nuxtjs/robots@3.0.0

### Reproduction

Just build the project

### Describe the bug

When we run in Dev mode nothing happens and our application works nice, but when we build the application and deploy it, the first page load doesn't work on Safari and Firefox. After reload the page, the application runs like a charm. We aren't able to simulate the behaviour on develop mode. The print screens below is the only way to see the issue.

![safari-logs-1](https://github.com/nuxt/nuxt/assets/2074316/dda032ea-1cac-4e4a-804b-184bee4555e4)

![safari-logs-2](https://github.com/nuxt/nuxt/assets/2074316/1165506b-ae6d-4872-bae1-bfad18ba568d)

![firefox-logs](https://github.com/nuxt/nuxt/assets/2074316/5ab3639a-2c6a-4456-ab2b-de430f5b878b)

### Additional context

What we figured out in our investigation is something related to vue-router processing during build phase.

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by keuller** [comment]
Hi @danielroe as I mentioned before it is hard to reproduce because it only happens after the build process (performing 'pnpm build`). Our client already asked us about when we will fix it and, which is pretty hard for us to debug.

**Comment by danielroe** [comment]
I'm happy to take a reproduction that only reproduces in certain situations (like after build) as long as there are steps I can follow to reproduce the problem.
