### ISSUE TITLE
Nux3, css problem when the browser will back and forth

### ISSUE THREAD

**Issue by zanxiaopeng** [nuxt/nuxt#20753]
My project is Nuxt3. I found that when the browser goes forward and back, the global style configured by nuxt.config will load slowly. If there is no slow loading problem in the vue page with many useHead references, how can this be solved?

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by danielroe** [comment]
Is this in dev mode or in production? And I am asking for a minimal project with instructions so I can see what you are experiencing.

**Comment by zanxiaopeng** [comment]
[dress_missacc_nuxt_shop.zip](https://github.com/nuxt/nuxt/files/11440509/dress_missacc_nuxt_shop.zip)

dev mode

You can run it, then you go to 404, and then return to the home page through the browser, you will see the problem

thank you

**Comment by zanxiaopeng** [comment]
You run it, and you type /404, and you hit the browser fallback button, you see
'element-plus/dist/index.css',
        'vant/lib/index.css',
        '~/assets/css/common.css',
        '~/assets/css/custom-theme.css'
These 4 styles are lazy loaded

**Comment by zanxiaopeng** [comment]
Hello, is there an answer to this question?

**Comment by serkon** [comment]
@zanxiaopeng, have you found any solution for this issue? 

I am facing the same problem and looking for a solution in Nuxt 3 (`"nuxt": "^3.12.4"`, `"@nuxtjs/tailwindcss": "^6.12.0"`). Initially, when the page loads, everything works as expected. However, when using the browser's forward and back buttons, Tailwind CSS temporarily disappears and reappears after about one second. I'm not sure if this issue only occurs in dev mode. I hope it doesn't happen in production.

**Comment by serkon** [comment]
check the link: https://github.com/nuxt/nuxt/issues/15723#issuecomment-1901783875
