### ISSUE TITLE
The vue sfc template is not checked properly when combining ts and eslint

### ISSUE THREAD

**Issue by yveeven** [nuxt/nuxt#20754]
### Environment

- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.0
- Package Manager:  pnpm@8.2.0
- Builder:          vite
- User Config:      modules, eslint
- Runtime Modules:  @nuxtjs/eslint-module@4.0.2
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-5ng4yv?file=package.json

### Describe the bug

I use the dependencies eslint,@nuxtjs/eslint-module,@typescript-eslint/eslint-plugin,@typescript-eslint/parser eslint-plugin-vue, but I can't check the template properly, I get the undefined variables in double brackets in the template, I run `npm run eslint` in the terminal and it doesn't report the error properly, I have added the correct script

**Comment by danielroe** [comment]
For Nuxt 3 projects, we recommend `@nuxt/eslint-config` which provides minimal but correct support with Nuxt 3 TypeScript features.
