### ISSUE TITLE
nuxt.config : app > head > titleTemplate doesn't work with a function.

### ISSUE THREAD

**Issue by korgan00** [nuxt/nuxt#20766]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.13.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.3.3
- Package Manager:  npm@8.19.3
- Builder:          vite
- User Config:      app, runtimeConfig, css, modules, components, vite, devtools
- Runtime Modules:  @nuxtjs/color-mode@3.2.0, @pinia/nuxt@0.4.9
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-mtzzdy?file=app.vue

### Describe the bug

The nuxt.config has a `titleTemplate` that can be set as a function. But the function doesn't work.

We are trying to have the `SiteName` when there is an empty title and the `Title | SiteName` when the title exists.

We are using the `<Title>` component.

```html
<Head>
  <Title> My title </Title>
</Head>
```

```typescript
export default defineNuxtConfig({
  app: {
    head: {
      titleTemplate: (titleChunk) => {
        return titleChunk ? `${titleChunk} | Site Name` : 'Site Name';
      },
    },
  },
});
```

It doesn't work. It just shows the title.

**Comment by danielroe** [comment]
You can instead use titleTemplate as a function within `app.vue` or set it as a string in nuxt.config. (You can't set it as a function in nuxt.config because this can't be serialised and passed into the build.)

We should update the types for this to disallow functional use, or warn if functions are passed within `app.head` - wdyt @harlan-zw?

**Comment by harlan-zw** [comment]
Agreed! 

Also, you can use templateParams to achieve the same result without needing a function. The %separator will be omitted when the page title is empty.

```ts
export default defineNuxtConfig({
  app: {
    head: {
      titleTemplate: `%s %separator %siteName`,
      templateParams: {
        siteName: 'Site Name',
        separator: '|',
      },
    },
  },
});
```

See https://stackblitz.com/edit/github-mtzzdy-vgkx5b?file=nuxt.config.ts

**Comment by korgan00** [comment]
Thank you both!
I didn't know about the `templateParams` property. I cannot find any documentation about it.
I tried and it works like a charm. 💯

**Comment by safejace** [comment]
when using 

``` 
 compatibilityDate: '2025-05-15',
  future: {
    compatibilityVersion: 4,
  },
```


this seems to break

```
      titleTemplate: `%s %separator %siteName`,
      templateParams: {
        separator: '|',
        siteName: 'My Site',
      },
```

see pic 

![Image](https://github.com/user-attachments/assets/54abe260-b8a8-42cd-8f49-ba933ca4a57d)

**Comment by harlan-zw** [comment]
See the migration steps https://nuxt.com/docs/getting-started/upgrade#migration-steps-4

We may make this easier
