### ISSUE TITLE
Coming from the error page fetch does not work

### ISSUE THREAD

**Issue by lipecss** [nuxt/nuxt#20767]
### Environment

- Operating System: Windows_NT
- Node Version:     v16.13.1
- Nuxt Version:     3.5.0-28059470.ddbb8479
- Nitro Version:    2.4.1-28058956.2ef9608
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      app, css, imports, plugins, modules, image, supabase,
 nitro, runtimeConfig
- Runtime Modules:  @nuxtjs/tailwindcss@6.6.7, @nuxt/image-edge@1.0.0-28059208.2abef1b, @nuxtjs/supabase@0.3.5, @pinia-plugin-persistedstate/nuxt@1.1.1, @pinia/nuxt@0.4.10

### Reproduction

I don have link

### Describe the bug

I have the index.vue page with the following code:

```
<script setup>
const { pending: pendingProject, data: projectData } = await useLazyFetch('/api/projects/latest')

console.log('projectData', projectData.value)

watch(() => pendingProject, (newVulue) => {
 
  if (!newVulue.value) {
    setTimeout(() => {

      if (process.client) projectScrollMagic()
    }, 800)
  }
}, { immediate: true })
</script>
```

 and this method is executed when I come from any page (except the one I need which is the error.page). If the user is on the page and I send him to the index, using router.push, router.replace, clearError, when accessing the index.vue the useLazyFetch is not executed and the projectData is null

**Comment by danielroe** [comment]
The 'error page' is not a route - it's not a page as such, so when you clear the page, it doesn't trigger any kind of update in the route or any refetch of `useLazyFetch`. Maybe instead you could watch `error.value` (if `const error = useError()`) or something similar?
