### ISSUE TITLE
Non-module Web Workers broken

### ISSUE THREAD

**Issue by DallasHoff** [nuxt/nuxt#20771]
### Environment

- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.0
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

Nuxt: https://stackblitz.com/edit/github-knhd4c?file=app.vue
Vanilla Vite (Working): https://stackblitz.com/edit/vitejs-vite-somqs4?file=main.js

### Describe the bug

In classic (not type: module) web workers, Vite adds `importScripts('/@vite/env')` to the top of the worker file. In Nuxt, this import returns a page, not the script that it is supposed to, and throws the error: "Refused to execute script from '/@vite/env' because its MIME type ('text/html') is not executable." This breaks the worker.

**Comment by danielroe** [comment]
This has been resolved upstream in Vite and should be included in the next Vite release, which will be available immediately in the Nuxt edge channel, or in the next Nuxt minor release (3.7).

**Comment by DallasHoff** [comment]
Awesome, thank you!
