### ISSUE TITLE
Modules missing from .output/server/node_modules after build

### ISSUE THREAD

**Issue by timb-103** [nuxt/nuxt#20773]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v16.19.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.0
- Package Manager:  npm@8.5.4
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/timb-103/nux3-ffprobe

### Describe the bug

When running in dev, ffprobe works fine however after running a npm run build, it gives the error "Could not find ffprobe executable".

Looking in .output/server/node_modules/@ffrobe-installer/win32-x64 there is no .exe file, where as in the parent node_modules it exists.

Seems like it's not being copied across during build for some reason.

**Comment by danielroe** [comment]
You can try setting `nitro.externals.traceInclude`:

```ts
export default defineNuxtConfig({
  nitro: {
    externals: {
      traceInclude: []
    }
  }
})
```

**Comment by timb-103** [comment]
> You can try setting `nitro.externals.traceInclude`:
> 
> ```ts
> export default defineNuxtConfig({
>   nitro: {
>     externals: {
>       // using the linux example because that's what's available in stackblitz
>       traceInclude: ['node_modules/@ffprobe-installer/linux-x64/ffprobe'],
>     }
>   }
> })
> ```
> 
> Example: https://stackblitz.com/edit/github-gdcj7v.
> 
> I'm closing this as this is an upstream issue with Nitro, and I am not sure this is something in general that Nitro can solve (tracing binaries). Maybe @pi0 has a different idea?
> 
> Certainly adding this to the Nitro docs would be a good idea.

Amazing, this does the trick. Thanks a ton Daniel, was trying to sort this out all day haha.
