### ISSUE TITLE
Hot reload only updates one component instance when rendered multiple times

### ISSUE THREAD

**Issue by lloydtao** [nuxt/nuxt#20788]
### Environment

```
Nuxi 3.4.3                                                                   14:11:35
                                                                             14:11:36
RootDir: /home/projects/github-echkk3                                        14:11:36
Nuxt project info:                                                           14:11:36

------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.0
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

The same occurs with `nuxt@3.4.3` and `nuxt@3.0.0`, on both Linux and Windows.

### Reproduction

https://stackblitz.com/edit/github-echkk3?file=pages/index.vue

![Recording 2023-05-11 at 14 07 42](https://github.com/nuxt/nuxt/assets/41923457/63007a59-52c8-4ff4-9507-0b9326f57e92)

### Describe the bug

When rendering a component multiple times (e.g. `<HelloWorld v-for="index in 10" :key="index" />`, or simply writing `<HelloWorld />` many times), hot reload appears to update only one instance of the component.

**Comment by danielroe** [comment]
This is an upstream issue: https://github.com/vitejs/vite-plugin-vue/issues/134. We can track in the Nuxt repo at https://github.com/nuxt/nuxt/issues/19856.

**Comment by lloydtao** [comment]
Thanks, @danielroe!

Any workaround for now? (e.g. different Vue version)

**Comment by danielroe** [comment]
I haven't confirmed it, but I reported this issue before (https://github.com/vitejs/vite/issues/9679) and it was confirmed working with Vue 3.2.40 so that might be worth investigating ...

**Comment by 0xmisu** [comment]
Same issue with nuxt@3.4.3 and nuxt@3.5.2, can't find the solution.

**Comment by danielroe** [comment]
This is an upstream issue: see https://github.com/nuxt/nuxt/issues/20788#issuecomment-1544024457.

**Comment by 0xmisu** [comment]
@danielroe Thanks, I got it.
I just initialized a project using vite.
```
yarn create vite my-vue-app --template vue-ts 
```
Indeed, the same issue exists.
