### ISSUE TITLE
Upgrade to new version goes back to 3.0.0

### ISSUE THREAD

**Issue by mateusavila** [nuxt/nuxt#20784]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.19.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@8.5.0`
- Builder:          `vite`
- User Config:      `app`, `modules`, `ssr`, `css`, `unocss`, `build`, `runtimeConfig`, `sourcemap`
- Runtime Modules:  `design@1.0.0`, `@pinia/nuxt@0.4.10`, `@unocss/nuxt@0.51.12`
- Build Modules:    `-`

### Reproduction

Just typing in the terminal

npx nuxi upgrade 

of

npx nuxi upgrade -f

### Describe the bug

I wanted to use vue 3.3 now, and I've tried to upgrade by using nuxi upgrade. Instead of upgrading the inner packages and vue to 3.3, still loading the older version of vue (3.2.47).

When I running the npx nuxi upgrade, this action returns my nuxt project to version 3.0.0.

To fix this, I just typing pnpm up --latest, to rollback the package.json.

**Comment by danielroe** [comment]
Under the hood `nuxi` runs `pnpm -D nuxt`. Do you mean that your package.json was updated to `3.0.0`, or that the version actually installed in node_modules was `3.0.0`?

**Comment by mateusavila** [comment]
Hello

My version is nuxt 3.4.3. I wanted to use vue 3.3, but only returns to old version. Here the prompt:

npx nuxi upgrade -f
npm WARN ignoring workspace config at /Users/mateus/Documents/projects/afiliapay/apps/apps/platform/.npmrc 
Nuxi 3.0.0                                                            14:00:47
                                                                      14:00:47
ℹ Package Manager: pnpm 8.5.0                                         14:00:47
ℹ Current nuxt version: 3.0.0                                         14:00:47
ℹ Removing lock-file and node_modules...                              14:00:47
ℹ Installing latest Nuxt 3 release...                                 14:00:47
../..                                    | Progress: resolved 0, reused 1, downl../..                                    | Progress: resolved 69, reused 69, dow../..                                    | Progress: resolved 71, reused 71, dow../..                                    | Progress: resolved 162, reused 162, d../..                                    | Progress: resolved 273, reused 272, d../..                                    | Progress: resolved 426, reused 425, d../..                                    | Progress: resolved 625, reused 624, d../..                                    | Progress: resolved 776, reused 776, d../members                               |  WARN  deprecated sourcemap-codec@1.4.8
../..                                    | Progress: resolved 776, reused 776, d../members                               |  WARN  deprecated rollup-plugin-terser@7.0.2
../..                                    | Progress: resolved 776, reused 776, d../..                                    | Progress: resolved 889, reused 889, d../..                                    | Progress: resolved 1024, reused 1002,../..                                    | Progress: resolved 1184, reused 1118,../..                                    | Progress: resolved 1377, reused 1314,../members                               |  WARN  deprecated stable@0.1.8
../..                                    | Progress: resolved 1377, reused 1314,../..                                    | Progress: resolved 1526, reused 1463,../..                                    | Progress: resolved 1526, reused 1464,../..                                    | Progress: resolved 1535, reused 1472,../..                                    | Progress: resolved 1537, reused 1474,../..                                    | Progress: resolved 1550, reused 1487,../..                                    | Progress: resolved 1562, reused 1499,../..                                    | Progress: resolved 1570, reused 1507,../..                                    | Progress: resolved 1573, reused 1510,../..                                    | Progress: resolved 1575, reused 1511,../..                                    | Progress: resolved 1575, reused 1512,../..                                    |  +12   -8 +-
../..                                    | Progress: resolved 1575, reused 1512,../..                                    | Progress: resolved 1575, reused 1512, downloaded 0, added 0, done
../members postinstall$ nuxt prepare
│ Nuxi 3.0.0
│ ✔ Types generated in .nuxt
└─ Done in 2s

dependencies:
+ @afiliapay/unocss-rules 1.0.0 <- ../../packages/unocss-rules
+ @afiliapay/use-afiliapay 1.0.0 <- ../../packages/use-afiliapay
+ @ckeditor/ckeditor5-build-classic 37.1.0
+ @ckeditor/ckeditor5-image 37.1.0
+ @ckeditor/ckeditor5-vue 5.1.0
+ @nuxt/cli 2.16.3
+ @pinia/nuxt 0.4.10
+ @vorms/core 1.1.0
+ @vorms/resolvers 1.1.0
+ @vuepic/vue-datepicker 5.0.1
+ @vueup/vue-quill 1.1.1
+ @vueuse/components 10.1.2
+ @vueuse/nuxt 10.1.2
+ add 2.0.6
+ c8 7.13.0
+ chart.js 4.3.0
+ date-fns 2.30.0
+ design 1.0.0 <- ../../packages/design
+ maska 2.1.9
+ normalize.css 8.0.1
+ quill-blot-formatter 1.0.5
+ vue-chartjs 5.2.0
+ zod 3.21.4

devDependencies:
+ @histoire/plugin-nuxt 0.16.1
+ @histoire/plugin-vue 0.16.1
+ @nuxt/test-utils 3.4.3
+ @types/pell 1.0.1
+ @unocss/nuxt 0.51.12
+ @unocss/preset-attributify 0.51.12
+ @vitest/coverage-c8 0.31.0
+ @vue/test-utils 2.3.2
- histoire
+ histoire 0.16.1
+ jsdom 22.0.0
- nuxt
+ nuxt 3.4.3
+ sass 1.62.1
+ vitest 0.31.0

 WARN  Issues with peer dependencies found
apps/platform
└─┬ @nuxt/test-utils 3.4.3
  └── ✕ unmet peer vitest@^0.30.1: found 0.31.0

Done in 9.7s
ℹ Cleaning up generated nuxt files and caches...                      14:00:57
ℹ Upgraded nuxt version: 3.0.0                                        14:00:57
✔ You're already using the latest version of nuxt.                    14:00:57
mateus@MacBook-Air-de-Mateus platform %

**Comment by danielroe** [comment]
It looks like the issue is that npm has cached an old version of `nuxi` - try running `npx nuxi@latest` instead.

**Comment by mateusavila** [comment]
Well, it's worked to upgrade to nuxt 3.4.3, but remains vue 3.2.47. I wanted to upgrade now to vue 3.3

**Comment by danielroe** [comment]
You can try `npx nuxi@latest upgrade --force`
