### ISSUE TITLE
Default error page does not work on Windows

### ISSUE THREAD

**Issue by ilyazolotarov** [nuxt/nuxt#20789]
### Environment

- Operating System: Windows_NT
- Node Version:     v16.14.2
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.0
- Package Manager:  npm@8.5.5
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

Initial project with "nuxi init". Cannot reproduce on stackblitz, it seems this is a Windows-related issue.

### Describe the bug

For some reason [this](https://github.com/nuxt/nuxt/blob/0258acdc8a6f02bd5de5e31611b4c821481bb519/packages/nuxt/src/app/components/nuxt-error-page.vue#L10)  template compiles incorrectly. The code after "defineProps" tries to access "error" from global scope instead of "props" object, which leads to the "ReferenceError: error is not defined".

![image](https://github.com/nuxt/nuxt/assets/10565780/095e7084-3a01-4783-8aa2-76ecec54e4db)

**Comment by danielroe** [comment]
Is this a fresh project? I wonder if this is a Vue 3.3 issue. 🤔

**Comment by Lehoczky** [comment]
Found a workaround by adding `"vue": "~3.2.47"` to the dependencies and doing a fresh install

**Comment by Lehoczky** [comment]
The upstream issue has also been fixed: https://github.com/vuejs/core/commit/f25bd37c6707fde19d164d90a38de41168941f4b and released as part of `Vue v3.3.2` https://github.com/vuejs/core/blob/main/CHANGELOG.md#332-2023-05-12
