### ISSUE TITLE
if leaving nested route, child page is unmounted before suspense resolves

### ISSUE THREAD

**Issue by danielroe** [nuxt/nuxt#20798]
[stackblitz.com/edit/github-f4gpfk-qhgrfy?file=pages/test.vue](https://stackblitz.com/edit/github-f4gpfk-qhgrfy?file=pages/test.vue)

> https://github.com/nuxt/nuxt/issues/13814#issuecomment-1544828371

**Comment by daehyun-thevc** [comment]
I am having a similar problem. Only the child, not parent, of the new nested page are being set up before page:start so child can't receive props properly from async parent

**Comment by danielroe** [comment]
@daehyun-thevc would you post a reproduction so when we resolve this we can verify your use case is also covered?

**Comment by daehyun-thevc** [comment]
https://stackblitz.com/edit/github-szoey5?file=pages/index.vue
when navigating from `/basecamp` to `/mountain` which is async nested route, mountain/index.vue implements setup function before mountain.vue implements setup function, so there is undefined prop `mountainTitle`

<img width="632" alt="image" src="https://github.com/nuxt/nuxt/assets/87633241/e18ba226-6748-40b4-9acb-427d04ed4fbf">

**Comment by daehyun-thevc** [comment]
https://stackblitz.com/edit/github-szoey5?file=pages/index.vue
when navigating from `/basecamp` to `/mountain` which is async nested route, mountain/index.vue implements setup function before mountain.vue implements setup function, so there is undefined prop `mountain`

<img width="605" alt="image" src="https://github.com/nuxt/nuxt/assets/87633241/409b675a-b156-457a-9cee-6b51cb96ecd6">

**Comment by Luffyyy** [comment]
I know this is being a bit pushy, but this issue is kinda related to the suspensible issue that Vue 3.3 fixed, but unfortunately hasn't fixed that specifically. I'd totally appreciate it (and I hope more that have this issue upvote it) if it got fixed already, I've been waiting months and this is the only major issue I have with Nuxt right now. 🚀

**Comment by emaung** [comment]
Heya yep. I agree that this needs a bit of priority. I am half way in my project and we keep building it hoping this will be fixed soon. Just that user experience is not very good with half of the page missing whenever change route.

Is there any workaround during the meantime?
