### ISSUE TITLE
Can the document indicate that vite: false has been deprecated

### ISSUE THREAD

**Issue by weilengdezaoshang** [nuxt/nuxt#20796]
### Describe the feature

When upgrading to a stable version, an error occurred due to the previous use of vite: false. But I did not see this configuration being deprecated in the document.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
@weilengdezaoshang Vite now only accepts a subset of `ViteConfig`. TypeScript should warn about `false` then.
<img width="823" alt="image" src="https://github.com/nuxt/nuxt/assets/640208/b6de1a1a-523f-4e9b-bed4-8c95c62bc9ec">
