### ISSUE TITLE
Support external library build output scanning for components

### ISSUE THREAD

**Issue by fabis94** [nuxt/nuxt#20799]
### Describe the feature

According to [this](https://nuxt.com/docs/guide/directory-structure/components#library-authors) you can specify folders from npm packages in the nuxt config (or its hooks) for component auto-scanning. What I dislike about how this works currently is that it seems to scan the source code of that package (.vue files) not the build output.

The .vue files of a third party NPM package might rely on custom bundler settings like custom path aliases or maybe custom loaders/plugins for handling imports to files that nuxt won't know how to handle. I also dislike the idea of importing another package's source code, not the build output, cause you can never know what kind of transformations the library author expects to happen during the build making the result actually different from what the source code says.

Additionally - this way of importing components is incompatible with non-nuxt applications. A standard Vue application will still need to rely on a standard ESM/CJS module to import the third party components, cause it doesn't have nuxt's vue file scanning mechanism. So you'd need to maintain 2 ways of consuming your package.

**The solution:** It would make a lot more sense to allow specifying build outputs - the resulting `./dist/library.mjs` file which will have all of the Vue components build into plain JavaScript. Then Nuxt could scan that module for all of the components that are exported and use them that way. Outputting components into an ESM/CJS file is how most component library packages are built, so this would also be more idiomatic in the ecosystem.

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by fabis94** [comment]
Ok turns out it's possible to do so with some extra steps:

```ts
import { createRequire } from 'node:module'
import { has, isObjectLike } from 'lodash-es'
import { defineNuxtModule, addComponent } from 'nuxt/kit'
import * as SpeckleUiComponents from '@speckle/ui-components'
import type { DefineComponent } from 'vue'

const req = createRequire(import.meta.url)

const isVueComponent = (val: unknown): val is DefineComponent => {
  if (!isObjectLike(val)) return false
  return has(val, '__name')
}

export default defineNuxtModule({
  meta: {
    name: 'speckle-ui-components'
  },
  setup() {
    // Add all @speckle/ui-components components
    for (const [key, val] of Object.entries(SpeckleUiComponents)) {
      if (!isVueComponent(val)) return
      addComponent({
        name: key,
        filePath: req.resolve('@speckle/ui-components'),
        export: key
      })
    }
  }
})
```

It would be nice if you wouldn't have to do this and you could just specify a library package name directly

**Comment by danielroe** [comment]
I use this method in [`@nuxtjs/ionic`](https://github.com/nuxt-modules/ionic/blob/main/src/module.ts#L142-L148).

Do you have any specific suggestions for improving this? Often libraries that expose components as named exports _also_ expose non-components, and I think it's probably safer to let module authors make the call rather than add _all_ exports as components, for example.

**Comment by fabis94** [comment]
@danielroe Well, originally I wasn't aware of the `addComponent()` method existing, I had to look at `nuxt` source code to find it when looking for workarounds. As long as something like this exists, it isn't that big of a deal, but it would be nice if this would be mentioned in the docs, cause currently they only mention `.vue` file scanning as the only method for library authors.

That said, it could be improved further by allowing this to be done through the `components` config key in the nuxt config so that you don't need to create a custom module.
To resolve the issue you brought up about mixed exports a predicate function could be provided that is invoked with each name of the export and that returns either true or false for whether it should be added as a component. I'd go even further and only invoke the predicate for exports that are actual Vue components using a filter method akin to the one I have in my workaround (isVueComponent).
Or alternatively you could also just provide an array of export names to add as components.

Something like this
```js
export default defineNuxtConfig({
  components: [
    { module: '@some/package', prefix: 'Special', include: (componentName) => componentName.startsWith('foo') },
    { module: '@other/package', prefix: 'Special', include: ['FormButton', 'TextInput'] },
  ]
})
```

**Comment by danielroe** [comment]
Having discussed it with the team, I think the current solution is pretty reasonable, and the additional effort doesn't seem too much for a module author.

You could also try mlly static import analysis, which we use within `unimport`, rather than directly importing the exports of the module.
