### ISSUE TITLE
The development environment is different from packaging, and yup is not packaged   。  .output\server\node_modules

### ISSUE THREAD

**Issue by 15844229646** [nuxt/nuxt#20803]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.12.1`
- Nuxt Version:     `0.0.0`
- Nitro Version:    `-`
- Package Manager:  `unknown`
- Builder:          `webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://gitee.com/WangJingXuan/new-team

### Describe the bug

[nuxt] [request error] [unhandled] [500] Cannot find package 'yup' imported from E:\blogtest\server\chunks\index.get.mjs
  at new NodeError (node:internal/errors:393:5)
  at packageResolve (node:internal/modules/esm/resolve:860:9)
  at moduleResolve (node:internal/modules/esm/resolve:909:20)
  at defaultResolve (node:internal/modules/esm/resolve:1124:11)
  at nextResolve (node:internal/modules/esm/loader:163:28)
  at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
  at link (node:internal/modules/esm/module_job:75:36)

我在开放环境运行正常，
当我打包后，运行，出现此错误

I am running fine in the development environment. However, when I package the application and run it, I encounter the following error:

  我的代码 
  ```

import {Schema, model} from 'mongoose';
import yup from 'yup'
import { getNextId } from '../tools/mongooseUtils';

const {modelName,fieldName} = {
    modelName:'Banner',
    fieldName:'bannerId'
} 

const bannerSchema = new Schema({
  [fieldName]: { type: Number, unique: true },
  title: { type: String },
  subtitle: { type: String, required: true },
  image: { type: String, required: true },
  enabled: { type: Number, required: true },
  sort: { type: Number },
}, { timestamps: true });

bannerSchema.pre('save', async function (next) {
  if (!this[fieldName]) {
    this[fieldName] = await getNextId(modelName, fieldName);
  }
  next();
});


export const Banner = model<any>(modelName, bannerSchema)

export const BannerYup = yup.object().shape({
    title: yup.string().required('Title is required'),
    subtitle: yup.string().required('Subtitle is required'),
    image: yup.string().required('Image is required'),
    enabled: yup.number().required('enabled is required'),
    sort: yup.number().required('sort is required'),
  });

```

接口的目录 <code>server/api/banner<code/>
引入文件的目录 <code>server/models/Banner<code/>

The endpoint directory is server/api/banner and the file is imported from server/models/Banner.

### 如需 复现

打包后 node .output/server/index.mjs 正常（正常的原因是，在项目的本地有node_modules/yup）
将打包的.output，放到其他文件夹，在 运行  node .output/server/index.mjs。则会出现此问题

To reproduce the issue:

After packaging, run node .output/server/index.mjs (The issue occurs because the node_modules/yup is present locally in the project)
Move the packaged .output folder to a different directory
Run node .output/server/index.mjs from the new location, which triggers the error.

### 疑问
为什么 我在文件中 使用
import yup from 'yup'

构建时 yup 并没有在 .output\server\node_modules 下;

Question:
Why is the yup module not included in the node_modules directory when building?

Please ensure that the translation accurately conveys the information provided.

-----------------------------------------------------------------------------------------------------

**Comment by 15844229646** [comment]
http://www.k2shi.com/admin/banner

**Comment by chenyuncai** [comment]
same problem to. it seems some packages were built into the .nitro dir.

**Comment by danielroe** [comment]
Workaround in https://github.com/nuxt/nuxt/issues/22325#issuecomment-1690421926. (Let's track in that issue.)
