### ISSUE TITLE
<NuxtPage> info message does not look up for module pages

### ISSUE THREAD

**Issue by edgarsn** [nuxt/nuxt#20801]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.0
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      modules
- Runtime Modules:  ./modules/test-module
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-hcx5za

### Describe the bug

If `pages/` directory is not created or is empty and all of the pages are defined using `extendPages` in module, it throws warning:

`Create a Vue component in the pages/ directory to enable <NuxtPage>`

and shows blank page.

If you create e.g. `pages/test.vue`, warning goes away and displays the intended page.

### Additional context

Also this warning goes away, if I create `app/router.options.ts` file.

**Comment by darioferderber** [comment]
@edgarsn you can add `pages: true` in the `nuxt.config`, or you can do the same inside your module:
```ts
setup(options, nuxt) {
  nuxt.options.pages = true;
  const { resolve } = createResolver(import.meta.url);

  extendPages((pages) => {
    pages.push({
      name: 'index',
      path: '/',
      file: resolve('./runtime/pages', 'index.vue'),
    });
  });
}
```

**Comment by edgarsn** [comment]
> 

Thank you for your reply. Yeah, this also works.

Could this issue be changed as enhancement so nuxt in core sets `nuxt.options.pages = true;` when `extendPages()` is called?
