### ISSUE TITLE
definePageMeta's Vue page declaration layout attribute in the pages directory is invalid

### ISSUE THREAD

**Issue by xhc-code** [nuxt/nuxt#20805]
### Environment

no

### Reproduction

https://codesandbox.io/p/sandbox/hopeful-stonebraker-6i12p9?file=%2Flayouts%2Flayout-custom.vue

### Describe the bug

The layout attribute of definePageMeta cannot override the value of the name attribute of the NuxtLayout component. Adding the following code to the vue page under specific pages/ is invalid
```
definePageMeta({
   layout: "layout-custom",
});
```

When the name attribute of the NuxtLayout component of app.vue is deleted, it will return to normal.
I should define the layout page used by definePageMeta to override the NuxtLayout component name property of the app.vue page.

**Comment by xhc-code** [comment]
![image](https://github.com/nuxt/nuxt/assets/28866025/d809ee87-e71d-41e6-a727-75070351cb52)
I checked the object information, but did not find the layout configuration item, which part belongs to the old version? How can I achieve the above way?

**Comment by danielroe** [comment]
This is by design. `<NuxtLayout>` will respect any layout set on the route metadata. But you can override this by passing an explicit name.

**Comment by xhc-code** [comment]
> This is by design. `<NuxtLayout>` will respect any layout set on the route metadata. But you can override this by passing an explicit name. (So if you want the route metadata to set the route, simply do not override it by passing a `name` prop.)

Ok, let me confirm that if you want to override the layout through the layout attribute of definePageMeta, you cannot set the name attribute of the NuxtLayout component, right?

**Comment by danielroe** [comment]
Exactly 👍  The `name` prop is the override; the page metadata value is the 'default'.

**Comment by xhc-code** [comment]
> Exactly 👍 The `name` prop is the override; the page metadata value is the 'default'.

OK, thanks
