### ISSUE TITLE
Does not redirect properly on the server in `useAsyncData`

### ISSUE THREAD

**Issue by nWacky** [nuxt/nuxt#20809]
### Environment

The issue occurs in `nuxt = 3.4.3`. 

Doesn't have an issue when using `nuxt = 3.4.0`

### Reproduction

[example on CodeSandbox](https://codesandbox.io/p/sandbox/silly-brattain-f93dme?file=%2Fpages%2Ftest%2F%5Bid%5D.vue%3A34%2C25)

### Describe the bug

A page has a url like `/test/[id]`

In `useAsyncData` when `id` is < 5 user should be redirected to the page with the next id (e.g `/test/1` thinks `/test/2` might have some data)

# Current behavior

uses `nuxt = 3.4.3`

client side everything works:

1. go to '[/](https://f93dme-3000.csb.app/)'
2. when clicking a `go to /test/1` link the app redirects client side to `/test/2`, `/test/3`, `/test/4` and `/test/5`

server side:

1. go to '[/test/1](https://f93dme-3000.csb.app/test/1)'
2. on the server `router.replace('/test/2')` is called (or `router.push` sometimes too)
3. server responds with status code 200 and content
   ```
   Page: test/1
     data: null,
     pending: false
   ```
4. page isn't redirected because data was fetched server side

# Expected behavior

works with `nuxt = 3.4.0`

1. go to '[/test/1](https://f93dme-3000.csb.app/test/1)'
2. server responds with `status = 302 Found` and header `location /test/2`
  - also for some reason with both production and debug builds sends data
   ```
   Page: test/1
     data: null,
     pending: false
   ```
2. browser goes to `/test/2`
3. ... redirects all the way to `/test/5`
4. `/test/5` status code = 200, response body
   ```
   Page: test/5
     data: data here!,
     pending: false
   ```

**Comment by logotip4ik** [comment]
You should probably use [navigateTo](https://nuxt.com/docs/api/utils/navigate-to#navigateto) instead of `router.push`

**Comment by nWacky** [comment]
> You should probably use [navigateTo](https://nuxt.com/docs/api/utils/navigate-to#navigateto) instead of router.push

Added a [/test2 page](https://codesandbox.io/p/sandbox/silly-brattain-f93dme?file=%2Fpages%2Ftest2%2F%5Bid%5D.vue%3A23%2C37). 

Tried using `return await navigateTo(newUrl); `*. Similar thing


\*  Probably it would be better to `await navigateTo`, then `return null` to avoid `data` of type `any`

**Comment by logotip4ik** [comment]
After awaiting promise - nuxt instance is lost, so that's why `navigateTo` doesn't work (wrap it in try catch and log error). As a work around you could store a `const nuxtApp = useNuxtApp()` before awaiting promise and then calling `navigateTo` with `nuxt` like this `callWithNuxt(nuxtApp, navigateTo, [newUrl])` (note: you need to import `import { callWithNuxt } from '#app'`)

working demo - https://codesandbox.io/p/sandbox/aged-pond-4304no

**Comment by logotip4ik** [comment]
More detailed answer - https://github.com/nuxt/nuxt/issues/12342#issuecomment-1400849134

**Comment by nWacky** [comment]
That worked, thank you. I think the issue can be closed then
