### ISSUE TITLE
`pending` of `<script>` in header can prevent page hydrate and navigate

### ISSUE THREAD

**Issue by gyhyfj** [nuxt/nuxt#20826]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.4.2
- Nitro Version:    2.4.0
- Package Manager:  pnpm@8.4.0
- Builder:          vite
- User Config:      modules, vite, css, imports, pinia, sitemap, app, ignore, telemetry, appConfig, devServer, nitro
- Runtime Modules:  @nuxtjs/tailwindcss@6.6.6, @pinia/nuxt@0.4.8, @pinia-plugin-persistedstate/nuxt@1.1.1, @element-plus/nuxt@1.0.4, @nuxtjs/robots@3.0.0, nuxt-simple-sitemap@2.4.11
- Build Modules:    -

### Reproduction

Add one extenal script:
```ts
/* [nuxt.config.ts] */
export default defineNuxtConfig({
  app: {
    header: {
      script: [
        {
            src: 'https://xxx.js',
            defer: true,
        },
       ],
    }
  }
})
```
Then load this page, if this js file's download is always pending because of net work problem, the page cannot finish hydrate or navigate until this request is timeout. Even if I set `defer: true` to this script

### Describe the bug

As above

**Comment by danielroe** [comment]
I don't think this is a Nuxt issue. If you want your script to be located lower-down in the DOM, you can instead set `tagPosition: 'bodyClose'`.
