### ISSUE TITLE
TS Error with auto-imports from composables and utils in Vue Template after 3.3

### ISSUE THREAD

**Issue by tobychidi** [nuxt/nuxt#20827]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.0
- Package Manager:  pnpm@8.5.0
- Builder:          vite
- User Config:      experimental, modules, colorMode
- Runtime Modules:  @unocss/nuxt@0.51.12, @vueuse/nuxt@10.1.2, nuxt-icon@0.4.0, nuxt-swiper@1.1.0, @nuxt/devtools@0.4.6, @nuxt/image-edge@1.0.0-28020728.5df24eb, @nuxtjs/color-mode@3.2.0
- Build Modules:    -

### Reproduction

![image](https://github.com/nuxt/nuxt/assets/111127651/51f17cc2-4624-4240-bcc3-d8d225045052)

This error doesn't seem to be reproducible on Stackblitz so I have included a [github repo](https://github.com/tobychidi/nuxt-utils-import-error)

### Describe the bug

When functions are auto-imported from utils/ composables and used in Vue SFC Template, VsCode throws and error. Yes, I use the latest volar. This error appeared after `pnpm up` That bumped my Vue version to 3.3.1.

I have not tried reverting Vue versions though. 

### Additional context

Example: 
```
Property 'useShowSnack' does not exist on type '{ $: ComponentInternalInstance; $data: {}; $props: { key?: string | number | symbol | undefined; ref?: VNodeRef | undefined; ref_for?: boolean | undefined; ... 8 more ...; style?: unknown; }; ... 10 more ...; $watch<T extends string | ((...args: any) => any)>(source: T, cb: T extends (...args: any) => infer R ? (arg...'.ts(2339)
```

_No response_

**Comment by danielroe** [comment]
This is unfortunately due to the Vue 3.3 upgrade. You can try pinning your vue version to Vue 3.2 for now until the next Nuxt release.

**Comment by tobychidi** [comment]
I see. Thank you

**Comment by AloisSeckar** [comment]
I am still experiencing this in 3.5.0. 

I tried to add into `package.json`
```
"overrides": {
  "vue": "3.2.47"
}
```
But it didn't seem to help either. 

Or is there different way how I should change its version?

**Comment by danielroe** [comment]
I believe this will need to be resolved upstream in Volar/vue-language-tools.

**Comment by dargmuesli** [comment]
See (and upvote) https://github.com/vuejs/language-tools/issues/3190

**Comment by xiaoxiangmoe** [comment]
Hi all, can you provide us a minimal reproduction to find some clue and then fix it?

**Comment by kleinpetr** [comment]
In my case when I just create a new one Nuxt project

`npx nuxi init my-project`

then install deps 
`pnpm i`

open `app.vue` and hover over `<NuxtWelcome>` I have no suggestion until I override vue version

**Comment by kleinpetr** [comment]
ok.. I am trying it again and it seems it works now. I am using Volar 1.7.6.

**Comment by tobychidi** [comment]
This issue has finally been resolved. With an update to unplugin-auto-imports. 👏🏽👏🏽

**Comment by yaroofie** [comment]
i still have this issue

**Comment by jonathanwilke** [comment]
This seems to be still an issue with the current versions of Nuxt and Vue. I think this issue should be reopened.

**Comment by Creatium** [comment]
I also get this error, but with very basic functions in utils folder. Functions that do basic string manipulation, so nothing directly related to third party libraries.

**Comment by danielroe** [comment]
third party libraries 'pollute' the namespace, which is why it causes the issue.

please open a new issue with a reproduction if you face something like this 🙏
