### ISSUE TITLE
Can't use paths with aliases inside nuxt.config.ts or modules/....

### ISSUE THREAD

**Issue by wanderer20** [nuxt/nuxt#20830]
When trying to importing files through aliases at the configuration (**nuxt.config.ts**), an error occurs: **Cannot find module '~/....**

There is an example: [codesnadbox.io](https://codesandbox.io/p/sandbox/tender-worker-l41rok?file=%2Fnuxt.config.ts%3A8%2C1)

## Short example

**nuxt.config.ts**
```
import { book } from "~/vars";

export default defineNuxtConfig({
  runtimeConfig: {
    bookApiEndpoint: book.apiEndpoint || "",
  },
});
```

## Full example

If use an absolute path, then file will be imported:

```
import { book } from "./vars";
```
But if there is another import through the alias inside the file, then there will be an error again (pic.1):

**./vars.ts**
```
export * from "~/entities";
```
**./entities/index.ts**

```
export * from "./book";
```

**./entities/book.ts**
```
export const book = {
    apiEndpoint: '/api/book'
}
````

![image](https://github.com/nuxt/nuxt/assets/8947500/fdb30d2b-eb5d-4290-a780-269f862f25c1)
Pic.1. Error: Cannot find module with alias

There is an example: [codesnadbox.io](https://codesandbox.io/p/sandbox/tender-worker-l41rok?file=%2Fnuxt.config.ts%3A8%2C1)

## Question
How can aliases be used inside a config file?

Thank you in advance!

**Comment by danielroe** [comment]
Check out https://github.com/nuxt/nuxt/issues/20539#issuecomment-1524953896. This is not currently supported.
