### ISSUE TITLE
page is blank when i enable browser add blocker 

### ISSUE THREAD

**Issue by git-e-001** [nuxt/nuxt#20837]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.18.1`
- Nuxt Version:     `3.1.0`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `app`, `runtimeConfig`, `css`, `modules`, `nitro`, `tailwindcss`, `googleFonts`, `i18n`, `lodash`, `build`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.6.4`, `@nuxtjs/google-fonts@3.0.0-1`, `@nuxtjs/i18n@8.0.0-beta.10`, `@vueuse/nuxt@9.13.0`, `@pinia/nuxt@0.4.7`, `nuxt-lodash@2.4.1`, `@nuxtjs/robots@3.0.0`, `@nuxtjs/device@3.1.0`
- Build Modules:    `-`

### Reproduction

![image](https://github.com/nuxt/nuxt/assets/78661753/f24fe18e-4057-42ed-bf99-e58f4b4b3e29)

### Describe the bug

When i use the add blocker in google or Firefox browser that can't show my index or other page. But when disable it's ok. 
How can i solve this issue

Add bloker link:
https://chrome.google.com/webstore/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg

Error Page:
![image](https://github.com/nuxt/nuxt/assets/78661753/f24fe18e-4057-42ed-bf99-e58f4b4b3e29)

**Comment by danielroe** [comment]
You need to disable that extension on localhost. You have components within an `/ads/` folder, and because of how vite works, that is in the URL, and clearly it's being blocked by the extension.
