### ISSUE TITLE
deploy preset

### ISSUE THREAD

**Issue by SATHISH099** [nuxt/nuxt#20849]
### Describe the feature

Preset guide line paga not found. getting 404 error 

https://nuxt.com/docs/guide/deploy/presets

![404](https://github.com/nuxt/nuxt/assets/109304430/764bedd8-bb6b-47a5-bd6d-ad04aa3d2e78)

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
That page is not present in the docs. See https://nuxt.com/docs/getting-started/deployment.
