### ISSUE TITLE
Components are rendered twice (<component :is> on [...slug].vue) 

### ISSUE THREAD

**Issue by mercs600** [nuxt/nuxt#20848]
### Environment

clean setup on stackblitz
------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.0
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-ketx95?file=app.vue

1. Please open devtools, 
2. Click any product on the list 
3. Notice there is two console.logs 'render' with two different instances of the same component. Described results on the video below: 

https://github.com/nuxt/nuxt/assets/7935392/1b308d97-255d-435d-9d5b-439a2d049c1a

## Context
We use:
+ dynamic page - `[...slug].vue`
+ dynamic components - `component :is`

Scenario
1. Fetch pageData on `[...slug].vue` by `useAsyncData`
2. Render dynamic components based on `pageData`

## A bug / a question? 
Please click on some links in the product list (under "Reproduction").
The question is, why are components being rendered twice? This is causing unexpected bugs.

https://github.com/nuxt/nuxt/assets/7935392/1b308d97-255d-435d-9d5b-439a2d049c1a

We could prevent the double rendering by adding a :key to NuxtPage, but this would cause the page components to rerender before asyncData is resolved, which could have some impact. In this example, when we add :key, the components are only rendered once, but the page component is empty and does not wait for asyncData to render.

https://github.com/nuxt/nuxt/assets/7935392/f546fea4-3d03-41bb-b083-cc068a85bd50

How to prevent the effect of double rendering?

**Comment by darioferderber** [comment]
@mercs600 I'm not 100% sure why, but if you do it like this, components won't get rendered twice.

```html
<Page :data="data" />

instead of:
<component
  :is="Array.isArray(data) ? 'ProductList' : 'ProductPage'"
  :data="data"
/>
```

```ts
const { data } = await useAsyncData('pageData', () =>
  $fetch(`https://fakestoreapi.com/products/${useRoute().params.slug}`)
);

const Page = Array.isArray(data.value)
  ? resolveComponent('ProductList')
  : resolveComponent('ProductPage');
```

**Comment by smg99** [comment]
+1
same issue

**Comment by mercs600** [comment]
## Reason 
Guys, this happens because we use shared state `(useState)`. 
So when you update your page state (which is responsible for components' data), the components are rendered once before the new page is shown, and then they are rendered again after the new page is shown. 

Please take a look at the example: 
https://stackblitz.com/edit/github-ketx95-n6id8p?file=components%2Fglobal%2FProductPage.vue

Scenario:
1. I receive the product list on [...slug].vue - page `/`:
```js
const { data } = await useAsyncData('pageData', () =>
  $fetch(`https://fakestoreapi.com/products/${useRoute().params.slug}`)
);
```
So this `pageData` is shared.
2. I navigate to the product page - page `/1`.
3. [...slug].vue fetches the data again and updates `pageData`.
4. The components are rendered again on page `/` and then on page `/1`.

The previous page is unmounted after the new one is mounted.
I think this is intended, but it might be confusing if you're used to Nuxt 2 and asyncData.

## Question
The question is what is the better way to use global share state and render components once. 
For instance you could create additional local scope state for current page.

**Comment by palaxius** [comment]
+1
same issue here

It works without component is as well. And if the user has time to scroll down, then during client rendering he will again be thrown to the very top of the page. And the flashing of all the cards on the page also occurs.

**Comment by smg99** [comment]
I think I have been using it wrong altogether. I found a different approach to use dynamic components for content coming from queryContent

here is how I iterate components now

`[...slug].vue` and `.md`

old
```
<component
  :is="'Product'"
  :data="data"
/>

```

```
### Product name
```

new

```
<ContentRenderer :value="data" />
```

```
::Product
### Product Name
::
```

**Comment by mercs600** [comment]
I'm closing this since this is intended behavior

**Comment by mimoo** [comment]
not sure where to post, but components rendering multiple times on my end as well when I deploy, but not when I run `npm run dev`, very confusing
