### ISSUE TITLE
page render fail when server api not ready.

### ISSUE THREAD

**Issue by transtone** [nuxt/nuxt#20844]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.15.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.3.3
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      modules, experimental, css, colorMode, nitro, app, build, pwa, devtools
- Runtime Modules:  @vueuse/nuxt@10.1.2, @unocss/nuxt@0.51.12, @pinia/nuxt@0.4.10, @nuxtjs/color-mode@3.2.0, @vite-pwa/nuxt@0.0.7
- Build Modules:    -

### Reproduction

https://github.com/transtone/vitesse-nuxt3

### Describe the bug

If use top lever await in server api. On waiting, it will get a 500 page with message: `Cannot access 'renderer$1' before initialization`

relation issue:
https://github.com/nuxt/nuxt/issues/20576

**Comment by danielroe** [comment]
Nitro does not support top-level await. (Instead, you can use `defineLazyEventHandler` in these situations.)

cc: @pi0

**Comment by transtone** [comment]
https://github.com/nuxt/nuxt/issues/14348#issuecomment-1411724974

**Comment by transtone** [comment]
the key is `Cannot access 'renderer$1' before initialization`, not only `top-level await`, but other nitro wait cause this.

why client hmr can't wait till nitro is ready?

**Comment by transtone** [comment]
the key problem is, when the error start, the whole client gos wrong forever! all page become the error page,  refresh and reopen has no effect.
![image](https://github.com/nuxt/nuxt/assets/46688/4a7bc0d8-38ca-4eeb-a8f4-577451044cc8)

it MUST kill the server and restart it.

**Comment by danielroe** [comment]
Would you provide a reproduction without using top-level await? 🙏

**Comment by transtone** [comment]
This problem appeared in an internal project with server/api, It hard to trace the real problem.
but when update to `nuxt-3.5.2` with https://github.com/nuxt/nuxt/pull/21008, it never appeared again.
