### ISSUE TITLE
Remove element plus typescript 2322 type check

### ISSUE THREAD

**Issue by wlinglinux** [nuxt/nuxt#20850]
### Describe the feature

![image](https://github.com/nuxt/nuxt/assets/286261/e1a640ab-9ef5-4806-8f48-964d5344c5d4)
How to remove element plus typescript 2322 type check through configuration files？

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by wlinglinux** [comment]
![image](https://github.com/nuxt/nuxt/assets/286261/e21898d5-f9d9-4ab1-b132-ead7c854be57)

**Comment by danielroe** [comment]
These inlays are produced by Volar - you can see more at https://github.com/vuejs/language-tools.
