### ISSUE TITLE
`throw createError` does not show error page on client-side (in production)

### ISSUE THREAD

**Issue by IonCodetec** [nuxt/nuxt#20855]
### Environment

- Operating System: Linux
- Node Version:     v18.16.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.0
- Package Manager:  npm@9.5.1
- Builder:          vite
- User Config:      ssr, app, modules, css, runtimeConfig, vite, devtools, pwa
- Runtime Modules:  @vueuse/nuxt@10.1.2, @nuxtjs/tailwindcss@6.6.8, nuxt-icon@0.4.0, @nuxt/devtools@0.4.6, @vite-pwa/nuxt@0.0.7
- Build Modules:    -

### Reproduction

To trigger the error, navigate to the test page.
There, an api call is made which returns a 404 status code.

In the plugins folder, there is a plugin called axiosPlugin, which has an interceptor that throws an error with the fatal property.

https://stackblitz.com/edit/github-qpzhgc

It is necessary to run the generate command and deploy the dist folder on a hosting.

### Describe the bug

We have a project (SPA) deployed in pre-production where we have an interceptor made with axios.

This interceptor controls several status codes (401, 403, 404, 419, 500) to throw the error, but it does not redirect to the error.vue page, instead, it goes into the catch section of the api call.  

I based this on the issue https://github.com/nuxt/nuxt/issues/15432.

### Additional context

The error is generated in the axios interceptor by: 
`throw createError({
          statusCode: error.response.status,
          statusMessage: 'Something bad happens',
          fatal: true
        });`

**Comment by anPalmer** [comment]
I'm surprised to see no one else struggling with this. It seems pretty clear in the docs that throwing createError server side should trigger the full error page, but I haven't been able to get it to work on various Nuxt versions. 
<img width="958" alt="image" src="https://github.com/nuxt/nuxt/assets/24212943/7e72dffe-a7a6-4e47-b0e8-1a31e9c8eedd">
I created a very simple reproduction just to make sure it wasn't something in my application: [https://stackblitz.com/edit/github-65veoe?file=server%2FthrowsError.ts](https://stackblitz.com/edit/github-65veoe?file=server%2FthrowsError.ts)

**Comment by danielroe** [comment]
This only shows the error page if it bubbles up to a Vue error handler.

If you need to show the error page and the error isn't going to bubble up to a Vue error handler, then you can use `showError`.

Improvement to the docs would be welcome here 🙏
