### ISSUE TITLE
 How to obtain headers in the client

### ISSUE THREAD

**Issue by luckilyhang** [nuxt/nuxt#20869]
### Environment

Nuxi 3.3.1  

### Reproduction

How to obtain headers in the client

### Describe the bug

How to obtain headers in the client?

const headers = useRequestHeaders() ;  server is  ok  ； client is not

**Comment by logotip4ik** [comment]
You can't really obtain request headers in client side, but you can pass them from server via `useState` ([more info about useState](https://nuxt.com/docs/getting-started/state-management))

Here is a small working reproduction - https://stackblitz.com/edit/nuxt-starter-w2w2dr?file=app.vue

**Comment by luckilyhang** [comment]
thanks
