### ISSUE TITLE
An error occurred during fast route jump

### ISSUE THREAD

**Issue by tenfei4** [nuxt/nuxt#20861]
### Environment

Nuxi 3.4.3
RootDir: D:/node/test
Nuxt project info: 
------------------------------
- Operating System: Windows_NT
- Node Version:     v18.6.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.3.3
- Package Manager:  npm@8.13.2
- Builder:          vite
- User Config:      modules, build, plugins, app
- Runtime Modules:  @nuxtjs/tailwindcss@6.6.7, nuxt-icons@3.2.1, nuxt-lazyimages@0.2.0
- Build Modules:    -

### Reproduction

**a example at stackblitz**
[](https://stackblitz.com/edit/github-nxpfus-6xtnkg?file=app.vue)

### Describe the bug

When the route jumps, if the incoming page needs to return to the previous page immediately due to conditional judgment or other reasons, an error occurs. This error only occurs when the network speed is particularly fast, and this problem does not occur when the network speed is slow.

 **Error describe:**
Uncaught DOMException: Node.insertBefore: Child to insert before is not a child of this node

### Additional context

Tests have found that the same problem occurs when clicking quickly between multiple pages.

**Comment by danielroe** [comment]
This is an upstream issue with transitions + suspense.

You can follow it here in Nuxt at https://github.com/nuxt/nuxt/issues/13350, and upstream at https://github.com/vuejs/core/issues/8105.
