### ISSUE TITLE
Cannot start nuxt when add postcss plugin

### ISSUE THREAD

**Issue by menghany** [nuxt/nuxt#20868]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.0
- Package Manager:  pnpm@8.5.1
- Builder:          vite
- User Config:      modules, postcss
- Runtime Modules:  @nuxtjs/eslint-module@4.0.2, @nuxtjs/tailwindcss@6.7.0
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-gkasfo?file=nuxt.config.ts

### Describe the bug

Add custom postcss plugin can not start nuxt

**Comment by danielroe** [comment]
`postcss.plugins` has an object syntax: see https://stackblitz.com/edit/github-gkasfo-keprew?file=nuxt.config.ts,postcss-inset.ts.
