### ISSUE TITLE
Nested Functional Component render only once 

### ISSUE THREAD

**Issue by Szymon-dziewonski** [nuxt/nuxt#20871]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.0
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-hsectr-l7wusd?file=btn.vue,app.vue

### Describe the bug

When using nested functional `h` components and showing conditionally lowest level component, nuxt renders only once this component and then just stops render it. 
In provided link please toggle click button `Show/hide functional component` at least 3 times to show -> hide -> show, to see issue.

**Comment by FRSgit** [comment]
I think this one might be connected to how VNodes are handled in Vue - they are meant to be created on every render (as you would use the `h` method within render function.
Example works if you change it like this: https://stackblitz.com/edit/github-hsectr-fhpcu4?file=app.vue

**Comment by danielroe** [comment]
Would you be able to check with https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter to see whether this is Nuxt-specific? I think this is likely Vue behaviour rather than Nuxt's.

**Comment by Szymon-dziewonski** [comment]
I guess you are both right, can be closed

**Comment by zernonia** [comment]
@FRSgit  You are a life saver!!! I spend countless hour trying to find the reason why the vnode wasn't mounted correctly, and your suggestion totally works! Really thank you!!!!
