### ISSUE TITLE
Error by using aws-jwt-verify in nuxt 2 project 

### ISSUE THREAD

**Issue by RaminderPaulSingh** [nuxt/nuxt#20874]
### Environment

  System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-1235U
    Memory: 6.00 GB / 15.68 GB
  Binaries:
    Node: 16.19.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\Documents\fare_nexus\nexus-sandbox\frontend\node_modules\.bin\yarn.CMD
    npm: 9.6.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1555.0), Chromium (113.0.1774.42)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    nuxt: ^2.15.8 => 2.16.3

### Reproduction

Description:
Error in nuxt project when aws-jwt-verify module is used.
Create a Nuxt project using the command npm init nuxt-app nuxt-sample.
Some times it is observed that the project creation process may hang at the step of extracting the rxjs package. However, waiting for approximately 5-7 minutes allows the project creation to proceed successfully.

Steps to Reproduce the issue:

Create a Nuxt project using the following command:
npm init nuxt-app nuxt-sample
During the project creation process, select the following options:
a) Programming language: JavaScript
b) Package manager: npm
c) UI framework: None
d) Template engine: HTML
e) Do not select any Nuxt.js modules.
f) Linting tools: None
g) Testing framework: Jest
h) Rendering mode: Universal (SSR / SSG)
i) Deployment target: Server (Node.js hosting)
j) Development tools: jsconfig.json (Recommended for VS Code if you're not using TypeScript)
k) Continuous integration: None
l) Version control system: Git

Once the project is created, navigate to the project folder by running the command:
cd nuxt-sample
Install the aws-jwt-verify package by executing the following command:
npm install aws-jwt-verify
Open the file pages/index.vue.
Insert the provided code snippet between the <script></script> tags.

<script> 
const { CognitoJwtVerifier } = require("aws-jwt-verify");
 const jwtVerifier = CognitoJwtVerifier.create({ userPoolId: "", tokenUse: "access", clientId: "", scope: "read", }); 
export default { name: 'IndexPage' }
 </script>

Build using npm run build

Following error occurs:_
ERROR in ./node_modules/aws-jwt-verify/dist/esm/jwt-rsa.js 316:63
Module parse failed: Unexpected token (316:63)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| // eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
| static create(verifyProperties, additionalProperties) {

    return new this(verifyProperties, additionalProperties?.jwksCache);
| }
| }
@ ./node_modules/aws-jwt-verify/dist/esm/index.js 3:0-46 3:0-46
@ ./node_modules/babel-loader/lib??ref--2-0!./node_modules/@nuxt/components/dist/loader.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./pages/index.vue?vue&type=script&lang=js&
@ ./pages/index.vue?vue&type=script&lang=js&
@ ./pages/index.vue
@ ./.nuxt/router.js
@ ./.nuxt/index.js
@ ./.nuxt/client.js
@ multi ./node_modules/@nuxt/components/lib/installComponents.js ./.nuxt/client.js

ERROR in ./node_modules/aws-jwt-verify/dist/esm/cognito-verifier.js 83:63
Module parse failed: Unexpected token (83:63)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| // eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
| static create(verifyProperties, additionalProperties) {

    return new this(verifyProperties, additionalProperties?.jwksCache);
| }
| /**
@ ./node_modules/aws-jwt-verify/dist/esm/index.js 4:0-59 4:0-59
@ ./node_modules/babel-loader/lib??ref--2-0!./node_modules/@nuxt/components/dist/loader.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./pages/index.vue?vue&type=script&lang=js&
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nuxt-sample@1.0.0 build: nuxt build
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nuxt-sample@1.0.0 build script.

### Describe the bug

Error on building nuxt project with  aws-jwt-verify module. The steps and errors are mentioned above.

**Comment by RaminderPaulSingh** [comment]
Hi Nuxt team,
Any update on this issue?
Thanks

**Comment by danielroe** [comment]
You can try adding the library to `build.transpile`.

**Comment by RaminderPaulSingh** [comment]
ERROR in ./node_modules/aws-jwt-verify/dist/esm/jwt-rsa.js
Module not found: Error: Can't resolve '#node-web-compat' in 'C:\Users\Lenovo\Documents\fare_nexus\nexus-sandbox\frontend\node_modules\aws-jwt-verify\dist\esm'
 @ ./node_modules/aws-jwt-verify/dist/esm/jwt-rsa.js 3:487-531 35:545-558 36:135-148 36:1204-1217 46:10-23 122:171-184 122:306-319
 @ ./node_modules/aws-jwt-verify/dist/esm/index.js
 @ ./middleware/auth.js
 @ ./.nuxt/middleware.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

ERROR in ./node_modules/aws-jwt-verify/dist/esm/jwt.js
Module not found: Error: Can't resolve '#node-web-compat' in 'C:\Users\Lenovo\Documents\fare_nexus\nexus-sandbox\frontend\node_modules\aws-jwt-verify\dist\esm'
 @ ./node_modules/aws-jwt-verify/dist/esm/jwt.js 3:308-352 30:36-49
 @ ./node_modules/aws-jwt-verify/dist/esm/jwt-rsa.js
 @ ./node_modules/aws-jwt-verify/dist/esm/index.js
 @ ./middleware/auth.js
 @ ./.nuxt/middleware.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

**Comment by danielroe** [comment]
I believe this is an issue with webpack 4 not supporting subpath imports. You may be able to work around this by using Nuxt Bridge which uses a different resolver (the resolver for webpack 5): https://github.com/nuxt/bridge. But this is likely not something we can resolve in Nuxt 2.
