### ISSUE TITLE
Empty proxy for template ref on component

### ISSUE THREAD

**Issue by Szymon-dziewonski** [nuxt/nuxt#20873]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.0
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Nuxtjs - https://stackblitz.com/edit/github-hsectr-yzmcmk?file=app.vue,btn.vue
Vue as reference - https://play.vuejs.org/#eNp9kctugzAQRX/lyhuChGCfAlLbP2ilrtgQMA2SX8JDskD+945DRFoqZeeRj4/nzizi1bn8MktxFKXvptERvKTZ1Y0ZtbMTYcEkhwzXlrozAobJaiT8InnZkLeZyJp3y5WRhu5MXpzIRHckG9NZ4wmnG/ohB1TRe0j5DmjMTX/YbjM8zl+tSlHVWJiMEqtkruz3IVm/BSNJ9hCnbAsZtz1qLfuxJXkETbNEiH+VxZqS83FBUjvFBFdAuY/B/VWN2MSNQMFgWfx61RiRiXvMOMK/wn681J9WSzCB60hnLAuUVQgBpVeWWFgWkfqnfbaM/RbWyUbvOtOkb33v22SXV4QfP22teA==

### Describe the bug

When using [template ref](https://vuejs.org/guide/essentials/template-refs.html) on component in next, I got object with `v_skip` instead of instance of component. Seems like getter proxy is modified in nuxt

![image](https://github.com/nuxt/nuxt/assets/2566152/e122407d-c107-4feb-bbc1-faea6a831b2e)

When I do the same in pure I got instance of component with all properties such as `$` , `$attrs` , `$data` etc which is expected result

![image](https://github.com/nuxt/nuxt/assets/2566152/9721633f-db67-4461-9eac-0d8fbd9869bf)

**Comment by danielroe** [comment]
This is replicable without Nuxt: https://stackblitz.com/edit/github-3i6doa?file=src/App.vue.

I suspect it's either caused by Suspense or by the fact that this is server rendered.

**Comment by I-NOZex** [comment]
is there any open issue in vue/core repo tracking this issue?

**Comment by Szymon-dziewonski** [comment]
@I-NOZex I haven't got time to open one, but once you mention it probably I will do it
