### ISSUE TITLE
Vue 3.3 components highlighting

### ISSUE THREAD

**Issue by localusercamp** [nuxt/nuxt#20875]
### Environment

Editor: VSCode
------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.0
- Package Manager:  npm@9.5.1
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

[Reproduction](https://stackblitz.com/edit/github-5sq5gd?file=app.vue)

### Describe the bug

After upgrading to Vue 3.3 IDE (VSCode) does not recognise (highlight) components in template and "go by reference" (`ctrl + click`) is unavailable now.
![image](https://github.com/nuxt/nuxt/assets/45385480/38a93ea4-3a06-466b-af80-02466b66a022)

This is a bit strange, because:
- `.nuxt/components.d.ts` generated perfectly.
  ```typescript
  declare module 'vue' {
  export interface GlobalComponents {
    'BaseComponent': typeof import("../components/Base/Component.vue")['default']
    'Test': typeof import("../components/Test.vue")['default']
    ...
  }
  ```
- [NuxtDevtools](https://github.com/nuxt/devtools) inspect Vue components works perfectly.
- IDE autocompletion for component `~/components/Test.vue` works perfectly.
  ![image](https://github.com/nuxt/nuxt/assets/45385480/a7959cbe-80a1-4096-86ec-1c8ef60d7b85)
- IDE autocompletion for component `~/components/Base/Component.vue` does not working. 
  ![image](https://github.com/nuxt/nuxt/assets/45385480/64cb6c57-5533-4bba-9152-cf04beec1db6)

**Comment by warflash** [comment]
#20586 will add support for vue 3.3, upgrading to 3.3 at the moment will yield some issues such as https://github.com/nuxt/nuxt/issues/20827 or what you're describing. You could perhaps check out whether the edge release fixes the issue for you in the meantime

**Comment by localusercamp** [comment]
Nice! Thanks for reply @warflash 👍

**Comment by danielroe** [comment]
This appears to still reproduce for me on the Edge Channel. But I don't _think_ the issue is within Nuxt itself, but rather related to the fact that we declare `GlobalComponents` on `vue` rather than `@vue/runtime-core`.

Related: https://github.com/vuejs/language-tools/issues/3107.

It's likely being fixed as we speak by @johnsoncodehk...

**Comment by localusercamp** [comment]
Came here to reopen this since problem does not fixed with nuxt 3.5 =D.
Thank you @danielroe for your attention to this problem.

**Comment by danielroe** [comment]
I believe this should now be resolved.

**Comment by localusercamp** [comment]
Yeah this is resolved now, great!
