### ISSUE TITLE
Support for Single Instance Server-Side Services in Clustered Environments with 'node-cluster' Preset

### ISSUE THREAD

**Issue by mrtoorich** [nuxt/nuxt#20882]
### Describe the feature

I'm using Nuxt 3 in a clustered environment using Node.js cluster mode with the 'node-cluster' preset configured in the `nuxt.config.ts` for improved performance and scalability. However, I've encountered an issue when trying to start a WebSocket server as part of my Nuxt application.

In a clustered environment, each worker process is a separate Node.js instance, and they don't share any memory or state. This is generally beneficial, but it creates a problem for services like a WebSocket server, which needs to maintain persistent connections. When I try to start the WebSocket server in a Nuxt server middleware or hook, it starts a separate WebSocket server in each worker process.

I understand that this is a result of how Nuxt and Node.js clusters work, but it would be very useful if there was a way to start a single instance of a service, like a WebSocket server, even when running Nuxt in a clustered environment with the 'node-cluster' preset.

One possible solution could be a new Nuxt hook or event that is guaranteed to run only once, regardless of the number of worker processes. This could be used to start services that should only have a single instance.

Alternatively, it could be helpful to have more control over the clustering behavior in Nuxt, such as being able to exclude certain middlewares or hooks from being run in every worker process when using the 'node-cluster' preset.

I hope this issue can be considered for future versions of Nuxt. It would greatly increase the flexibility of Nuxt in clustered environments and open up new possibilities for server-side services.

Thanks for your consideration.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by pi0** [comment]
Hi. For this, we need to check if the worker is the first one (nitro issue tracker: https://github.com/unjs/nitro/issues/1282)

```js
export default defineNitroPlugin(() => {
  if (!process.env.NITRO_CLUSTER_PIRMARY) {
    return;
  }
  console.log('Init code in nitro plugin');
});
```

(above code [not works](https://stackblitz.com/edit/nuxt-starter-gk2njl?file=server%2Fplugins%2Findex.ts) now)

**Comment by danielroe** [comment]
Let's track in upstream issue. 🙏
