### ISSUE TITLE
[3.5.0] Cannot stringify a function

### ISSUE THREAD

**Issue by ElYaiko** [nuxt/nuxt#20889]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.5.0`
- Nitro Version:    `2.4.0`
- Package Manager:  `npm@9.5.0`
- Builder:          `vite`
- User Config:      `alias`, `pwa`, `app`, `runtimeConfig`, `css`, `build`, `modules`, `vite`, `experimental`, `nitro`
- Runtime Modules:  `@pinia/nuxt@0.4.10`, `()`
- Build Modules:    `-`

### Reproduction

-

### Describe the bug

For some unknown reason I'm getting:

500
Cannot stringify a function

at flatten (./node_modules/devalue/src/stringify.js:166:43)
at flatten (./node_modules/devalue/src/stringify.js:60:39)
at flatten (./node_modules/devalue/src/stringify.js:102:15)
at flatten (./node_modules/devalue/src/stringify.js:166:43)
at flatten (./node_modules/devalue/src/stringify.js:60:39)
at flatten (./node_modules/devalue/src/stringify.js:60:39)
at flatten (./node_modules/devalue/src/stringify.js:166:43)
at flatten (./node_modules/devalue/src/stringify.js:166:43)
at flatten (./node_modules/devalue/src/stringify.js:166:43)

And it doesn't give more details, I am only passing a simple object with strings and arrays to the `nuxtApp.payload` ... What else could be?

**Comment by ElYaiko** [comment]
For some reason a component ref is being added into the payload?, I have a component that is like:

https://stackblitz.com/edit/github-w3ggbn?file=app.vue,components%2FTest.vue

In the repo works well, but in my project I get:
[https://i.imgur.com/d0cJ7RW.png](https://i.imgur.com/d0cJ7RW.png)

(I think is the pinia store using setup that is causing the problem...)

**Comment by baixiaoyu2997** [comment]
same issue

**Comment by danielroe** [comment]
Yes, that's very likely. The solution is probably pretty straightforward if you can provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)... 🙏

Until then you can workaround this way:

```ts
export default defineNuxtConfig({
  experimental: {
    renderJsonPayloads: false
  }
})
```

**Comment by ineshbose** [comment]
Seems to be coming from Pinia (as also noted by ElYaiko)

**Comment by ineshbose** [comment]
This could be a reproduction - https://stackblitz.com/edit/github-baazqd?file=app.vue (in my app, for eg, this ref is rather a Vue `inject`)

**Comment by danielroe** [comment]
We didn't support passing functions in the payload previously - so that would make this a feature request (though it's already possible with a custom 'function' type defined with `definePayloadReducer` and `definePayloadReviver`.

But I get the feeling from the original issue that the reporter felt this was a _regression_.

**Comment by ElYaiko** [comment]
> This could be a reproduction - https://stackblitz.com/edit/github-baazqd?file=app.vue (in my app, for eg, this ref is rather a Vue `inject` - this should be on client-side though so its assigned in `onMounted`)

Yes, using `renderJsonPayloads: false` or `onMounted` fixes the error so the pinia's function is defined only in client-side.
Thanks everybody for your help.

**Comment by DeVoresyah** [comment]
> I have the same issue. Working application then udpated to nuxt 3.5.2. We use pina everywhere export the actions and state in two objects. like:
> 
> ```
> const state = ref({
>     userAccount,
>     isUserAccountFormModalOpen,
>     isUserAccountUpdating,
>     userAccountLoadingError,
>     isLoadingUserAccount,
> 
>     actionTarget,
>     isLoading,
>   })
> 
>   const actions = reactive({
>     reloadUserAccount,
>     updateUserAccount,
>     openUserAccountModal,
>     closeUserAccountModal,
> 
>     sendChangePasswordNotification,
>     enableMfa,
>     disableMfa,
>   })
>   
> ```
> 
> When using `renderJsonPayloads: false` the error message is gone but i still see it on server side. Store actions are still not working on page. Get an error: `TypeError: $setup.actions.openUserAccountModal is not a function`
> 
> Do I need to setup `definePayloadReducer `? Don't understand that. Any other workaround we could do? Don't want to downgrade nuxt as new Vue features are awesome.

I still facing same issue today

**Comment by RomanSkrypnik** [comment]
Facing the same issue!

**Comment by danielroe** [comment]
@RomanSkrypnik See if you can reproduce the issue. You're probably passing a non JSON-ifiable object in `useAsyncData` or in a pinia store -> the browser.

**Comment by RomanSkrypnik** [comment]
@danielroe it doesn't matter pinia or something else
In my case, it happens when I try to assign new value to an object:
<img width="574" alt="image" src="https://github.com/nuxt/nuxt/assets/44501848/6651920a-d9a8-40bd-8ed9-b0555733fb84">
And then I face this:
<img width="1166" alt="image" src="https://github.com/nuxt/nuxt/assets/44501848/141d84d4-8216-44d7-95ee-383ac8970076">
**It works fine if it executes on client side**
Here is my repro: https://github.com/RomanSkrypnik/nuxt-devalue-issue

**Comment by danielroe** [comment]
@RomanSkrypnik It looks to me like you are assigning a _function_ into your state, which Nuxt is passing across to the client. But a function can't be converted to JSON and back again, which is why you are getting 'cannot stringify a function'.

**Comment by RomanSkrypnik** [comment]
@danielroe now I see
Thanks for your answer!

**Comment by ValeraKatruk** [comment]
Thank you! I learned about 2 ways to solve the problem.
1/ this is not preferable
export default defineNuxtConfig({   
 experimental: {
        renderJsonPayloads: false,
    },})
2/ this is right
I passed from useFetch refresh and tried to write it to actions in state
I removed the refresh and everything was fine
Thank you!

**Comment by spraddles** [comment]
So I've added @danielroe's suggestions to my Nuxt config.
...but now I'm getting this error:

<img width="853" alt="image" src="https://github.com/user-attachments/assets/d87e73f4-65ba-44a0-9cf7-15efc111d3e8">

Does anyone have any ideas about this issue please?

**Comment by ValeraKatruk** [comment]
perhaps you are using a plugin that is being processed on the server. he can't get the window
https://stackoverflow.com/questions/54979644/window-is-not-defined-in-nuxt-js

**Comment by JBustin** [comment]
Hello, is there a way to quickly identify what it is added to the shared state that's not supported ?
I mean, my app is huge, there are a lot of commits every day, and someone can easily add this kind of regression.
I need to log the part of the state that's invalid.

**Comment by danielroe** [comment]
That would be a nice improvement.
