### ISSUE TITLE
After upgrading to Nuxt 3.5 with esnext target dependencies cannot be resolved

### ISSUE THREAD

**Issue by peterbud** [nuxt/nuxt#20887]
### Environment

- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.5.0
- Nitro Version:    -
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      vite
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-zqfp5c

### Describe the bug

If you add this to `nuxt.config.ts`:
```
  vite: {
    build: {
      target: 'esnext',
    },
  },
```
then the following error occurs:
```
Failed to resolve dependency: @vue/runtime-core, present in 'optimizeDeps.include'          7:08:10 PM
WARN  Failed to resolve dependency: @vue/runtime-dom, present in 'optimizeDeps.include'           7:08:10 PM
WARN  Failed to resolve dependency: @vue/shared, present in 'optimizeDeps.include'                7:08:10 PM
ERROR  Error: The following dependencies are imported but could not be resolved:
```

I'm using `pnpm` _without_ `shamefully-hoist` (and it was working fine with nuxt 3.4.3
See repro above.

I have a hunch, maybe this is the origin of the issue:
https://github.com/nuxt/nuxt/pull/20829/files

**Comment by danielroe** [comment]
It doesn't work for me in 3.4.3 either. Let's track support without shamefully-hoist in https://github.com/nuxt/nuxt/issues/14146.

**Comment by peterbud** [comment]
Hi @danielroe many thanks for the quick reply. Hoever let me add, that nuxt 3.4.3 does work flawlessly with esnext target. See the same repo https://stackblitz.com/edit/github-zqfp5c . Once you revert back to 3.4.3, delete node_modules direcotry and do a fresh pnpm i, 3.4.3 does work without any issue.

**Comment by danielroe** [comment]
This seems now to be working fine in 3.7.1: https://stackblitz.com/edit/github-zqfp5c-ysbbml.
