### ISSUE TITLE
document enabling `defineModel` in 3.5 version

### ISSUE THREAD

**Issue by hiddenLadder** [nuxt/nuxt#20881]
### Environment

Nuxt project info:                                                                                                                   22:04:49

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.13.0
- Nuxt Version:     3.5.0
- Nitro Version:    2.4.0
- Package Manager:  npm@9.6.6
- Builder:          vite
- User Config:      srcDir, css, modules, app, experimental, runtimeConfig, postcss, typescript
- Runtime Modules:  nuxt-swiper@1.1.0, @vueuse/nuxt@9.13.0, nuxt-icon@0.4.0
- Build Modules:    -
------------------------------

### Reproduction

-

### Describe the bug

defineModel not working in 3.5 version and i dont see the way i could turn it on
There is also this warning in the console
![image](https://github.com/nuxt/nuxt/assets/89526742/624c43f2-cce9-42a5-865f-5f46e3879fab)

**Comment by sky-code** [comment]
Facing this issue after upgrade from 3.4.3 to 3.5.0
`
- Operating System: `Darwin`
- Node Version:     `v18.14.2`
- Nuxt Version:     `3.5.0`
- Nitro Version:    `2.4.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `ssr`, `router`, `components`, `modules`, `css`, `runtimeConfig`, `vite`, `imports`, `vue`, `app`
- Runtime Modules:  `@pinia/nuxt@0.4.10`, `@bootstrap-vue-next/nuxt@0.0.6`
- Build Modules:    `-`
`
Tried to delete .nuxt and node_modules, reinstall but it does not solve the issue.

**Comment by yassilah** [comment]
These features are experimental, you need to enable them in your vite config, as described [here](https://blog.vuejs.org/posts/vue-3-3#script-setup-typescript-dx-improvements) 🚀

```ts
// nuxt.config.ts

export default defineNuxtConfig({
  vite: {
        vue: {
            script: {
                defineModel: true,
                propsDestructure: true
            }
        }
    }
})

**Comment by cannap** [comment]
> These features are experimental and require explicit opt-in, you need to enable them in your vite config, as described [here](https://blog.vuejs.org/posts/vue-3-3#script-setup-typescript-dx-improvements) 🚀
> 
> ```ts
> // nuxt.config.ts
> 
> export default defineNuxtConfig({
>   vite: {
>         vue: {
>             script: {
>                 defineModel: true,
>                 propsDestructure: true
>             }
>         }
>     }
> })
> ```

does this work for you? for me its not working

**Comment by yassilah** [comment]
> > These features are experimental and require explicit opt-in, you need to enable them in your vite config, as described [here](https://blog.vuejs.org/posts/vue-3-3#script-setup-typescript-dx-improvements) 🚀
> > ```ts
> > // nuxt.config.ts
> > 
> > export default defineNuxtConfig({
> >   vite: {
> >         vue: {
> >             script: {
> >                 defineModel: true,
> >                 propsDestructure: true
> >             }
> >         }
> >     }
> > })
> > ```
> 
> does this work for you? for me its not working

Yup I can confirm it works for me, have you run `nuxi upgrade --force` as well?

**Comment by cannap** [comment]
@yassilah  it works i made a misstake i had <script type="setup"> xD

**Comment by danielroe** [comment]
I think it would be good to explicitly document how to set Vue options, particularly with regard to reactive props destructure, etc.

**Comment by hiddenLadder** [comment]
> I think it would be good to explicitly document how to set Vue options, particularly with regard to reactive props destructure, etc.

i agree, even in the blog there's nothing about it

**Comment by Haume0** [comment]
i have same problem and getting also same warning.

`[Vue warn]: defineModel() is a compiler-hint helper that is only usable inside <script setup> of a single file component. Its arguments should be compiled away and passing it at runtime has no effect.`

**Comment by RayJason** [comment]
> i have same problem and getting also same warning.
> 
> `[Vue warn]: defineModel() is a compiler-hint helper that is only usable inside <script setup> of a single file component. Its arguments should be compiled away and passing it at runtime has no effect.`

You can edit the config, then restart service.

**Comment by sky-code** [comment]
I upgraded to v3.5.2 and got this error again.

```[nuxt] error caught during app initialization ReferenceError: definePageMeta is not defined
    at index.vue:18:1
(```

Adding
```
vite: {
        vue: {
            script: {
                defineModel: true,
                propsDestructure: true
            }
        },
    }
}
```
to nuxt.config does not help.

**Comment by yassilah** [comment]
> @danielroe It would be great if we add these options to nuxt's `experimental` option

Personally, I feel it would be redundant and a bit confusing as it is not a Nuxt feature but really a Vue feature, so it makes sense to me that it is under `vite.vue.script` config. It is also how you would set it up outside a Nuxt project. However, it might indeed be good to add it to the Nuxt docs - not only for these specific options but more generally for all Vue features that require explicit opt-in
