### ISSUE TITLE
after update 3.4.3 to 3.5.0  set "type": "module" in the package.json

### ISSUE THREAD

**Issue by andysay** [nuxt/nuxt#20895]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v16.18.0
- Nuxt Version:     3.5.0
- Nitro Version:    2.4.0
- Package Manager:  npm@8.19.2
- Builder:          vite
- User Config:      app, modules, build, css, telemetry, runtimeConfig
- Runtime Modules:  ../modules/wsserver, @nuxtjs/tailwindcss@6.7.0, nuxt-headlessui@1.1.4, @pinia/nuxt@0.4.10, @pinia-plugin-persistedstate/nuxt@1.1.1, nuxt-swiper@1.1.0
- Build Modules:    -
------------------------------

### Reproduction

i'm have module 

```

import { defineNuxtModule } from '@nuxt/kit';
import { Server } from 'socket.io';

export default defineNuxtModule({
    setup(options, nuxt) {
        nuxt.hook('listen', (server) => {
            const io = new Server(server);

            nuxt.hook('close', () => io.close());

            io.on('connection', () => {
                console.log('CONNECTION');
            });
        });
    },
});

```

### Describe the bug

after update working stoped.

after dev 

Nuxi 3.5.0                                                                                                                                                   5:29:30 PM
Nuxt 3.5.0 with Nitro 2.4.0                                                                                                                                  5:29:30 PM
                                                                                                                                                             5:29:30 PM
  > Local:    http://localhost:8001/
  > Network:  http://10.0.0.221:8001/
  > Network:  http://10.211.55.2:8001/
  > Network:  http://10.37.129.2:8001/
  > Network:  http://[2001:1308:263c:6100:18f3:799:17a2:13cf]:8001/
  > Network:  http://[2001:1308:263c:6100:54bc:120b:c3cf:ccbe]:8001/
  > Network:  http://[2001:1308:263c:6100:a166:611c:74a3:7790]:8001/
  > Network:  http://[2001:1308:263c:6100:a5c7:ae0f:1a26:89ad]:8001/
  > Network:  http://[fdb2:2c26:f4e4:1::1]:8001/
  > Network:  http://[fdb2:2c26:f4e4::1]:8001/

 ERROR  (node:83454) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.                                      5:29:30 PM
(Use node --trace-warnings ... to show where the warning was created)

ℹ Using default Tailwind CSS file                                                                                                           nuxt:tailwindcss 5:29:30 PM
ℹ Tailwind Viewer: http://localhost:8001/_tailwind/                                                                                         nuxt:tailwindcss 5:29:31 PM
ℹ Vite client warmed up in 1573ms

**Comment by danielroe** [comment]
This seems likely to be a dependency of yours that was also upgraded in the process - rather than directly related to Nuxt.

Please do provide a reproduction and I will very happily reopen and look into it.

**Comment by andysay** [comment]
@danielroe only after npm install nuxt@3.5.0

How can I track which library started swearing after the update?

**Comment by danielroe** [comment]
It's difficult, but you can try using the node flag mentioned in the log... And try removing each module you have enabled, one by one.

**Comment by andysay** [comment]
@danielroe  this may be related to [6:03:20 PM] WARN "sendError" is imported from external module "/client/node_modules/h3/dist/index.mjs" but never used ?

**Comment by salomonsanz** [comment]
same here after upgrading to 3.5

**Comment by danielroe** [comment]
Would very much appreciate a reproduction. 🙏

**Comment by cexbrayat** [comment]
@danielroe I'm running into a similar error when bumping from v3.4.3 to v3.5.0, when using `@nuxtjs/i18n` v8.0.0-beta.12, with a config defined in a separate file (as I think we're supposed to do):
```ts
export default defineI18nConfig(() => ({
  legacy: false,
  fallbackLocale: 'en',
}));
```

See https://stackblitz.com/edit/nuxt-starter-qmmx7h?file=package.json for a small repro

Running `npm install && npm run build` throws:
```
[18:52:45]  ERROR  (node:73) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use node --trace-warnings ... to show where the warning was created)


 ERROR  [nuxt] [request error] [unhandled] [500] Unexpected token 'export'            18:52:45
  SyntaxError: export declarations may only appear at top level of a module  
  at compileFunction (https://nuxtstarterqmmx7h-v3h0.w-corp.staticblitz.com/blitz.9c8944bc.js:35:399059)  
```

**Comment by FatNerdPeng** [comment]
@danielroe Hello,I can provide a reproduction as I have also encountered this issue. I discovered this issue while using the @nuxtjs/i18n,

reproduction:
https://stackblitz.com/edit/nuxt-starter-xcpons

Let me briefly explain the problem,as shown in the figure, when I use nuxt@3.5.1, this error will occur:
![image](https://github.com/nuxt/nuxt/assets/33616855/df678dc7-89f5-4171-b3cc-f37157e4be39)
but when I use nuxt@3.4.3:
![image](https://github.com/nuxt/nuxt/assets/33616855/4ba8d45f-b4b1-43ab-a328-a88363ae9c4c)
you can see that this error has disappeared, so I can confirm this The error is caused by the nuxt@3.5.x.
This problem is not difficult to solve. I can use the 3.4.3. What I am more concerned about is why I can’t use @nuxtjs/i18n, it always reports the error shown in the picture "Cannot start nuxt:  Cannot read properties of undefined (reading 'options')"
Thanks!

**Comment by FatNerdPeng** [comment]
> @danielroe Hello,I can provide a reproduction as I have also encountered this issue. I discovered this issue while using the @nuxtjs/i18n,
> 
> reproduction: https://stackblitz.com/edit/nuxt-starter-xcpons
> 
> Let me briefly explain the problem,as shown in the figure, when I use nuxt@3.5.1, this error will occur: ![image](https://user-images.githubusercontent.com/33616855/241685920-df678dc7-89f5-4171-b3cc-f37157e4be39.png) but when I use nuxt@3.4.3: ![image](https://user-images.githubusercontent.com/33616855/241686715-4ba8d45f-b4b1-43ab-a328-a88363ae9c4c.png) you can see that this error has disappeared, so I can confirm this The error is caused by the [nuxt@3.5.x](mailto:nuxt@3.5.x). This problem is not difficult to solve. I can use the 3.4.3. What I am more concerned about is why I can’t use @nuxtjs/i18n, it always reports the error shown in the picture "Cannot start nuxt: Cannot read properties of undefined (reading 'options')" Thanks!

Oh, I know this is wrong, I used the wrong version, @nuxtjs/i18n 7.x only supports nuxt2, to adapt to nuxt3 I should use 8.x, right?

**Comment by FatNerdPeng** [comment]
@danielroe I know what's going on. The above problem should not be a nuxt version problem, but a collocation problem between nuxt and some modules.
If I use @nuxtjs/i18n@7.x in nuxt3, there will be no problem with nuxt@3.4.x, but an error "To load an ES module..." will occur with nuxt@3.5.x
If I use @nuxtjs/i18n@8.x in nuxt3, whether it is nuxt@3.4.x or nuxt@3.5.x, there will be no problem.

**Comment by danielroe** [comment]
I believe this is being tracked and resolved upstream in i18n

**Comment by LeonardoRick** [comment]
@danielroe I can't see i18n resolving this in any thread and it sounds kinda critical since it makes just impossible to startup a application with the newer versions of both packages (nuxt and @nuxtjs/i18n)

I have a really minimal reproducing project that shows that: https://github.com/LeonardoRick/temp-nuxti18n-bug

**Comment by Salotronic** [comment]
same here

**Comment by danielroe** [comment]
This is an upstream bug in i18n and isn't a Nuxt issue, but I will absolutely help resolve it upstream if needed. I am pretty sure that @kazupon is already fixing it, however.

**Comment by LeonardoRick** [comment]
Is there any opened there for me to track? I couldn't find it

**Comment by LeonardoRick** [comment]
@danielroe beta.13 pre-released and the issue persists. I don't think they have it tracked on their side since I can't find any open issue about this

**Comment by danielroe** [comment]
In that case would you raise an issue on the i18n repo?

**Comment by kazupon** [comment]
I've mentioned at [here](https://github.com/nuxt-modules/i18n/issues/2213#issuecomment-1627601744)
"type": "module" has already been resolved in v8 beta 13 and is no longer required.
