### ISSUE TITLE
[feature request]: `extendPagesDir` in `@nuxt/kit`

### ISSUE THREAD

**Issue by arashsheyda** [nuxt/nuxt#20899]
### Describe the feature

`@nuxt/kit` has extendPages and it is very good until the pages number that we want to extend is a lot, I though it's a good idea to have `extendPagesDir`

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/21371.
