### ISSUE TITLE
`lodash.template` is flagged up in snyk audit

### ISSUE THREAD

**Issue by wilsonpinto** [nuxt/nuxt#20891]
### Environment

any

### Reproduction

Run package scanner like snyk to detect vulnerabilities.

https://security.snyk.io/vuln/SNYK-JS-LODASHTEMPLATE-1088054

### Describe the bug

Details:
https://security.snyk.io/vuln/SNYK-JS-LODASHTEMPLATE-1088054

While Nuxt itself may not be directly affected, this can cause unnecessary issues with security package scanners, posing a challenge for internal dependency approvals.

**Comment by danielroe** [comment]
~> linking here: https://github.com/nuxt/nuxt/pull/20892#issuecomment-1550731095
