### ISSUE TITLE
Middleware on `/` are applied to server components

### ISSUE THREAD

**Issue by huang-julien** [nuxt/nuxt#20897]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.15.0
- Nuxt Version:     3.5.0
- Nitro Version:    2.4.0
- Package Manager:  pnpm@8.1.1
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

 https://stackblitz.com/edit/nuxt-starter-2qejrb?file=pages%2Ftest.vue,middleware%2Fbreak.global.ts,components%2FHello.server.vue,app.vue,nuxt.config.ts
### Describe the bug

when reviewing #20894 , I'm 100% sure that middlewares (at least global ones) are applied to server components. Middlewares shouldn't be applied to server components

**Comment by danielroe** [comment]
One thing to note is that it's possible to call a server component with a 'context' of a particular route, and if that route context is set, it may be important to allow router/route middleware to run.

I think if the `url` isn't set from the context we probably could skip middleware.

**Comment by huang-julien** [comment]
I see :+1:, do you think a check on `nuxtApp.ssrContext.url` should be enough ?

**Comment by danielroe** [comment]
I think maybe we can set it here:

https://github.com/nuxt/nuxt/blob/83cb5d6f5414378b2dbc43b2937cb4ca5edc843e/packages/nuxt/src/core/runtime/nitro/renderer.ts#L152-L159
