### ISSUE TITLE
Vite customlogger not working in v3.5.0

### ISSUE THREAD

**Issue by mikeschepers4** [nuxt/nuxt#20890]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.5.0
- Nitro Version:    2.4.0
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      vite, postcss
- Runtime Modules:  -
- Build Modules:    -
- Operating System: Linux
------------------------------

Although the same happens on my windows computer

### Reproduction

https://stackblitz.com/edit/nuxt-starter-3hephr?file=nuxt.config.ts 

The version in this project currently is v3.5.0. In my nuxt config i have a simple custom logger that i want to use to catch some warnings. As you can see it doesnt get triggered at all.

If you switch the nuxt version to 3.2.0 and reinstall the packages you will see that it now works again.

### Describe the bug

Using a custom logger in the nuxt configfile no longer seems to do anything. In previous versions it seems to work according to vites documentation but now it just gets ignored without any errors.

**Comment by danielroe** [comment]
Yes - this is the case. We now override with our own custom logger (https://github.com/nuxt/nuxt/pull/19523).

If you want to override this you can do so in the `vite:extendConfig` hook instead:

```ts
import { createLogger } from 'vite'

const logger = createLogger()

export default defineNuxtConfig({
  hooks: {
    'vite:extendConfig' (config) {
      config.customLogger = logger
    }
  }
})
```

See https://stackblitz.com/edit/nuxt-starter-dfd3rh.

**Comment by mikeschepers4** [comment]
Oh wow, missed this along all the other updates. This workaround is pretty neat. 

I was wandering around the docs for a while but couldnt really find this way of implementing it.

For my case consider it solved!
