### ISSUE TITLE
after update 3.3.2 to 3.5.0 run dev  Named export 'stringify' not found at ModuleJob._instantiate

### ISSUE THREAD

**Issue by mokurofuzo** [nuxt/nuxt#20906]
### Environment

Nuxi 3.5.0                                                                                                          15:06:23
                                                                                                                    15:06:24
RootDir: E:/workspace/GuYi_production/display-shop-new-version                                                      15:06:24  
Nuxt project info:                                                                                                  15:06:24

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.14.2
- Nuxt Version:     3.5.0
- Nitro Version:    2.4.1
- Package Manager:  npm@9.5.0
- Builder:          vite
- User Config:      imports, app, css, vite, typescript
- Runtime Modules:  -
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                         15:06:24  

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Reproduction

Local operation without connection

### Describe the bug

After upgrading from version 3.3 to version 3.5 npm install
run dev

![image](https://github.com/nuxt/nuxt/assets/44792146/9564b606-50c0-47c8-91b9-005610d10b9b)
I tried 3.4.3 again, everything is normal
I opened the configuration file again and found that all types reported errors, which did not appear in previous versions
![image](https://github.com/nuxt/nuxt/assets/44792146/8e63d2d2-20b8-4901-a4e2-2d784222e097)

### Logs

```shell-script
1、
(property) autoImport: boolean
Argument of type '{ imports: { autoImport: boolean; }; app: { head: { title: string; meta: ({ charset: string; } | { name: string; content: string; } | { hid: string; name: string; content: string; })[]; link: { rel: string; type: string; href: string; }[]; noscript: { ...; }[]; }; }; css: string[]; vite: { ...; }; typescript: { ...;...' is not assignable to parameter of type 'InputConfig<NuxtConfig, ConfigLayerMeta>'.
  Object literal may only specify known properties, and 'imports' does not exist in type 'InputConfig<NuxtConfig, ConfigLayerMeta>'.ts(2345)
2、
[worker reload] [worker init] Named export 'stringify' not found. The requested module 'file://E:/workspace/GuYi_production/display-shop-new-version/node_modules/devalue/dist/devalue.umd.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
                                                                                                                    14:59:38  
import pkg from 'file://E:/workspace/GuYi_production/display-shop-new-version/node_modules/devalue/dist/devalue.umd.js';      
const { stringify, uneval } = pkg;

  import { stringify, uneval } from 'E:/workspace/GuYi_production/display-shop-new-version/node_modules/devalue/dist/devalue.umd.js';
  ^^^^^^^^^
  SyntaxError: Named export 'stringify' not found. The requested module 'E:/workspace/GuYi_production/display-shop-new-version/node_modules/devalue/dist/devalue.umd.js' is a CommonJS module, which may not support all module.exports as named exports.   
  CommonJS modules can always be imported via the default export, for example using:

  import pkg from 'E:/workspace/GuYi_production/display-shop-new-version/node_modules/devalue/dist/devalue.umd.js';
  const { stringify, uneval } = pkg;

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)  at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
```

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by MrEraxd** [comment]
Hi @danielroe @mokurofuzo, it looks like there is problem with nuxt/i18n module, we can reproduce problem with those steps:

1. Init new app `npx nuxi@latest init my-app`
2. Before `npm i` add new package: `npm i -D @nuxtjs/i18n`
3. npm i
4. npm run dev
5. Error from images above displays

 installing [edge version](https://github.com/nuxt-modules/i18n#install-edge-version) of i18n seems to fix problem.

**Comment by mokurofuzo** [comment]
@MrEraxd thankyou，let me try right now

**Comment by mokurofuzo** [comment]
@danielroe @MrEraxd thankyou guys，i fixed it by @nuxt/i18n 8.0.0-beta12，there is also a bug usecookie  can not be used in i18nconfig

**Comment by evanlong0926** [comment]
I made the same mistake.

![image](https://github.com/nuxt/nuxt/assets/52912949/4946acd0-fdac-4bc1-a20a-a9f94c94528c)

**Comment by Suniron** [comment]
Remove node_modules folder and your dependencies lockfile and install your project again.

... Then restart volar/ts server.

🤞

**Comment by evanlong0926** [comment]
I also got the same error.
![image](https://github.com/nuxt/nuxt/assets/52912949/b2a5c6e1-194a-4bcc-b22d-fddef868148c)

In defineNuxtConfig, VSCode prompts me that I can only use these.
![image](https://github.com/nuxt/nuxt/assets/52912949/9ad27f41-2dbc-403a-bbab-f570a47ec4f9)

**Comment by mklueh** [comment]
Same here with `3.5.3`.

Only dropping this in helps

```
  experimental: {
    renderJsonPayloads: false
  },

```

**Comment by evanlong0926** [comment]
Thank you. I have fixed it. It was the inconsistency between TS and the dependent version in my workspace that caused this error. 😁

**Comment by caio-emidio** [comment]
@evanlong0926 could you provide a full example about what you did?

**Comment by evanlong0926** [comment]
> @evanlong0926 could you provide a full example about what you did?

The TS development dependency is installed in the dependency, and the TS global dependency is also installed locally. When you use `ts`, you'll see two version options:

![image](https://github.com/nuxt/nuxt/assets/52912949/90d2851a-436e-40b7-8184-8cd0334c357f)

If one of the `ts` files uses such a version:

![image](https://github.com/nuxt/nuxt/assets/52912949/5da051d9-9cf9-456c-b3eb-8eef20317417)

Another `ts` file uses this version again:

![image](https://github.com/nuxt/nuxt/assets/52912949/6f5788e4-df29-410e-8a69-0404f90f7a0c)

The type errors I mentioned before will occur, but I think this problem is very unscientific, maybe VSCode brought.

**Comment by tomardern** [comment]
I had the same error recently while starting to migrate from nuxt 2 to nuxt 3.

I can confirm that setting `renderJsonPayloads` (https://nuxt.com/docs/api/nuxt-config#renderjsonpayloads) to `false` fixed the issue for me.

```ts
export default defineNuxtConfig({
  // ...
  experimental: {
    renderJsonPayloads: false,
  },
  /// etc
 })
  ```
