### ISSUE TITLE
export default defineNuxtPlugin(nuxtApp => )  how to access the options   addPlugin(src:resolve(__dirname, 'plugins/apixxxader/apixxxxxoaderPlugin.js'),options)

### ISSUE THREAD

**Issue by mahanteshaCloudMPower** [nuxt/nuxt#20911]
### Environment

I'm using Nuxt3.4, but I'm having an issue. 
how to access the options  defineNuxtPlugin((options)=>) and addPlugin("options")

### Reproduction

this is my code  
   addPlugin({
        src: resolve(__dirname, 'plugins/apixxxader/apixxxxxxxaderPlugin.js'),
        fileName: 'apixxxx_loader.js',
        options: { apiConfigs: apiConfigs, apiUrlObj: apiUrlObj }
    })

this is my plugin code
     export default defineNuxtPlugin(nuxtApp => {
        const option = JSON.stringify(<%= options %>)
    })

### Describe the bug

How to get the options inside the defineNuxtPlugin({})

**Comment by danielroe** [comment]
You probably want `addPluginTemplate`, and try this for the contents of the plugin:

```ts
export default defineNuxtPlugin(nuxtApp => {
  const option = JSON.parse('<%= JSON.stringify(options) %>');
})
```

I would personally not recommend lodash templates but rather using virtual files (with `getContents()` method).

**Comment by mahanteshaCloudMPower** [comment]
thank you sir
