### ISSUE TITLE
[nuxt] [request error] [unhandled] [500] The requested moodule 'vue' does not provide an export named 'computed

### ISSUE THREAD

**Issue by wen403** [nuxt/nuxt#20919]
### Environment

- Operating System: Windows_NT
- Node Version:     v16.16.0
- Nuxt Version:     3.5.0
- Nitro Version:    2.4.1
- Package Manager:  pnpm@8.5.1
- Builder:          vite
- User Config:      runtimeConfig, build, vite, modules, experimental, plugins, css, colorMode, nitro, app, pwa
- Runtime Modules:  @vueuse/nuxt@9.13.0, @unocss/nuxt@0.51.12, @pinia/nuxt@0.4.8, @nuxtjs/color-mode@3.2.0, @vite-pwa/nuxt@0.0.7
- Build Modules:    -

### Reproduction

![img_v2_933ea207-5724-45c8-ba0e-1d934a8257eg](https://github.com/nuxt/nuxt/assets/67454874/c8933a05-0860-4b4e-98cc-15012022458a)

### Describe the bug

I have no issues with the development environment, but it appears after the build，I tried deleting the lock file and reinstalling the dependency, which is useless

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by wen403** [comment]
This is a problem with my PM2 program

**Comment by bitbytebit1** [comment]
I'm also running pm2 and seeing the error but with a different package (in my case is https://www.npmjs.com/package/@googlemaps/markerclusterer) could you explain what steps you took to resolve this @wen403

**Comment by zss1004504439** [comment]
I have the same problem with PM2

**Comment by polichan** [comment]
> This is a problem with my PM2 program

Could you please share your solution to this issue? I have the same issue. What did you do to your PM2? I build my nuxt app with Docker which uses keymetrics/pm2:16-alpine as the image.
