### ISSUE TITLE
When using composable function in the template area, a warning is displayed that there is no property.

### ISSUE THREAD

**Issue by yeonjulee1005** [nuxt/nuxt#20927]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.13.0
- Nuxt Version:     3.5.0
- Nitro Version:    2.4.1
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      ssr, target, devtools, app, vue, css, plugins, vite, build, modules, buildModules, experimental, stylelint, typescript, components, imports, i18n, vueuse, runtimeConfig
- Runtime Modules:  @vueuse/nuxt@10.1.2, @nuxtjs/stylelint-module@5.0.1, @nuxtjs/i18n@8.0.0-beta.11, @pinia/nuxt@0.4.10
- Build Modules:    unplugin-icons/nuxt
------------------------------

### Reproduction

https://stackblitz.com/edit/github-bhcu2c?file=composables%2Fui.ts,app.vue,pages%2Findex.vue

### Describe the bug

in stackblitz, It cannot be reproduced.
The error is shown as attached picture in vscode.

<img width="1040" alt="image" src="https://github.com/nuxt/nuxt/assets/57179957/feed0f23-3d60-45f9-a5e5-a634c7a1836d">

**Comment by warflash** [comment]
https://github.com/nuxt/nuxt/issues/20827
