### ISSUE TITLE
Layers - bug with resolving /public files during build

### ISSUE THREAD

**Issue by kleinpetr** [nuxt/nuxt#20929]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.5.0
- Nitro Version:    2.4.1
- Package Manager:  pnpm@8.4.0
- Builder:          vite
- User Config:      extends
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/github/kleinpetr/nuxt-layer-assets

1. `pnpm i`
2. `pnpm build`
3. see the error

### Describe the bug

When I use any relative path within my-layers such as `/public` assets it works for the dev, but it cannot be build.

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/18920.
