### ISSUE TITLE
Possible fix for Page Transition between [..uri].vue

### ISSUE THREAD

**Issue by TinyLightBold** [nuxt/nuxt#20920]
I had an issue with my query's on the [...uri].vue in Nuxt 3, where the pages between the uri already loaded and after that they transitioned.

Changing the query from `useFetch` to `useLazyFetch`
Think this would also work for `useAsyncData` to `useLazyAsyncData`

I think the thing about it is that Fetch immediately takes the query up to the next frame, and with Lazy you have a well lazy moment.

Hope this fixes for everyone who encounters it.

Don't think it really is a bug/issue, rather then just a query which is very quick ;)

_Originally posted by @TinyLightBold in https://github.com/nuxt/nuxt/issues/4132#issuecomment-1551655487_

**Comment by danielroe** [comment]
Thank you for the suggestion!

I'm going to close this as I think it's not something we can implement within Nuxt, either as a fix or an enhancement...

**Comment by TinyLightBold** [comment]
Unfortunately it gives an error on page change to [...uri].vue. When you refresh on that url after, then it loads in without issue and you can change pages as well with no problem.

title is in script setup
```
      useHead({
          title: data.value.title + ' - ProjectX'
      })
```

`  Uncaught (in promise) TypeError: Cannot read properties of null (reading 'title')
    at setup ([...uri].vue:338:29)
setup @ [...uri].vue:338
Promis`

**Comment by mrleblanc101** [comment]
Well, that's the point with LazyFetch, it render the page automatically.
It doesn't wait for the data. So you are trying to print to set a value which is still a pending promise there.
