### ISSUE TITLE
Question/ bug: How to provide functions from within Nuxt.config.ts or module.ts to runtime?

### ISSUE THREAD

**Issue by jvhellemondt** [nuxt/nuxt#20933]
Not sure if this belongs here. Feels like it doesn't belong in the Nuxt repo either, because it's module specific. Let me know if I need to move it.

So my situation is the following. I'm further improving my [Nuxt-vuetify module](https://github.com/invictus-codes/nuxt-vuetify). Users of the module, will provide a Vuetify config through the Nuxt.config.ts. Now Vuetify has the following feature when it comes to icons, [fa-svg](https://vuetifyjs.com/en/features/icon-fonts/#font-awesome-svg-icons). To use this feature, you need to provide a function as iconSet (component). This is how it works, I cannot change this. However, this is not the cause of my "issue".

What I can't seem to get working is the following, tested it on the nuxt-module-starter:

In my Nuxt.config.ts:
```typescript
export default defineNuxtConfig({
  modules: ["../src/module"],
  myModule: {
    testViaConfig() {
      console.log("test");
      return "test";
    },
  },
});
```

in my module.ts:
```typescript
import { defineNuxtModule, addPlugin, createResolver } from "@nuxt/kit";

// Module options TypeScript interface definition
export interface ModuleOptions {}

export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: "my-module",
    configKey: "myModule",
  },
  // Default configuration options of the Nuxt module
  defaults: {},
  setup(options, nuxt) {
    const resolver = createResolver(import.meta.url);

    nuxt.options.runtimeConfig.public.myModule = {
      ...options,
      test: "runtimeConfig, check",
      testViaModule: () => {
        console.log("test");
        return "test";
      },
    };
    // Do not add the extension since the `.ts` will be transpiled to `.mjs` after `npm run prepack`
    addPlugin(resolver.resolve("./runtime/plugin"));
  },
});
```

In my runtime/plugin.ts:
```typescript
import { defineNuxtPlugin, useRuntimeConfig } from "#app";

export default defineNuxtPlugin((nuxtApp) => {
  const config = useRuntimeConfig();
  const options = config.public.myModule;
  console.log({ options });
  console.log("Plugin injected by my-module!");
});
```

I would expect that in the browser both the `testViaConfig` and `testViaModule` functions would be logged. Except only the string (defined in module.ts, also passed via runtimeConfig), is logged in the browser.

I have made a codesandbox to reproduce. You can find it [here](https://codesandbox.io/p/github/jvhellemondt/nuxt-module-starter/draft/trusting-galileo?file=%2Fsrc%2Fmodule.ts&workspaceId=26bac05a-e35e-485b-bb0f-53f697bee73f).

Is it intended that I cannot pass functions to runtime like this? I have the feeling that it's not possible due to rollup, however I'm definitely not an expert on that. If so, is there another way around? It seems vital that users of the module can provide it via the Nuxt.config.ts from a user experience perspective.

Hope someone is able to help out. If I need to explain further, please let me know.

Thank you in advance.

Best regards,

J

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/18762.

**Comment by dreitzner** [comment]
> Let's track in #18762.
> 
> The way you can provide functions is through using `addTemplate` to add virtual files with code, or `addPlugin`, `addLayout`, etc.
> 
> There should be more information available at https://nuxt.com/docs/guide/going-further/modules.

@danielroe the link throws a 500 if opened directly 😉

For all others who want to open the link:
1. open https://nuxt.com/docs/guide/directory-structure/modules
2. scroll to `Read more in Docs > Guide > Going Further > Modules`
3. click
