### ISSUE TITLE
  ERROR  Failed to resolve import "fsevents" from "node_modules\.cache\vite\client\deps\chunk-MXLRMPOP.js?v=9e530d8b". Does the file exist? (x6)  

### ISSUE THREAD

**Issue by facexyy** [nuxt/nuxt#20945]
### Environment

    "@element-plus/nuxt": "^1.0.5",
    "@nuxtjs/tailwindcss": "^6.7.0",
    "@pinia/nuxt": "^0.4.11",
    "@types/node": "^18",
    "@vueuse/core": "^10.1.2",
    "@vueuse/nuxt": "^10.1.2",
    "element-plus": "^2.3.4",
    "nuxt": "^3.5.0",
    "nuxt-icon": "^0.4.0",
    "pinia": "^2.1.3",
    "prettier": "3.0.0-alpha.7-for-vscode",
    "prettier-plugin-tailwindcss": "^0.3.0",
    "sass": "^1.62.1"

### Reproduction

  // nuxt.config.ts
  modules: [
    "@element-plus/nuxt",
    "@nuxtjs/tailwindcss",
    "@vueuse/nuxt",
    "@pinia/nuxt",
    "nuxt-icon",
  ],
  
These modules need to be installed

### Describe the bug

![image](https://github.com/nuxt/nuxt/assets/125525983/4157f2f4-3f7e-4922-8e95-b7d6adcc8742)
 ERROR  Failed to resolve import "fsevents" from "node_modules\.cache\vite\client\deps\chunk-MXLRMPOP.js?v=9e530d8b". Does the file exist? (x6)

**Comment by danielroe** [comment]
It sounds like you are trying to import a node-only dependency into your Vue app.

Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by absolutetsonga** [comment]
Hi, I faced the same issue, and my problem was instead of importing the preview image I imported preview function from Vite, so check your imports again and maybe there hiding error

**Comment by simaotwx** [comment]
> Hi, I faced the same issue, and my problem was instead of importing the preview image I imported preview function from Vite, so check your imports again and maybe there hiding error

This can happen when the IDE imports it without you knowing. Solves the issue.

**Comment by gabrielcipriano** [comment]
> Hi, I faced the same issue, and my problem was instead of importing the preview image I imported preview function from Vite, so check your imports again and maybe there hiding error

@absolutetsonga what do you mean by "instead of importing the preview image I imported preview function"? 

I'm facing the same issue and I already searched my codebase from top to bottom looking for wrong imports

```
 ERROR  Failed to resolve import "fsevents" from "node_modules/.cache/vite/client/deps/chunk-UGOVS5OW.js?v=8b3721ca". Does the file exist?                         10:02:58 AM
 ERROR  Failed to resolve import "fsevents" from "node_modules/.cache/vite/client/deps/chunk-UGOVS5OW.js?v=8b3721ca". Does the file exist? (x2)
```

**Comment by AbelSanzDev** [comment]
it's because you have an import of another framework in my case im working in react and my issue was that i have an import from vite

**Comment by xiongpi** [comment]
it has something to do with defineConfig and process.env
