### ISSUE TITLE
bug to delete scss or note scss code

### ISSUE THREAD

**Issue by link-last** [nuxt/nuxt#20944]
### Environment

please see Reproduction

### Reproduction

1. https://stackblitz.com/edit/github-8pcgty?file=app.vue
2. https://stackblitz.com/edit/github-8pcgty?file=app.vue,pages%2Findex.vue

### Describe the bug

1. When you delete this block of code
`.aa {
}`
then refresh, you will see
![image](https://github.com/nuxt/nuxt/assets/82023850/5a3f686f-393e-4d0d-a672-dd22e007da3d)

2. When you comment css code
```
<!--<style lang="scss" scoped>-->
<!--.aa {-->
<!--}-->
<!--</style>-->
```
then refresh, you will see
![image](https://github.com/nuxt/nuxt/assets/82023850/1ca23811-9ff5-4ff2-a142-d70a309960e3)

**Comment by danielroe** [comment]
Let's track inhttps://github.com/nuxt/nuxt/issues/14976
