### ISSUE TITLE
Please upgrade to Vue 3.3.4 as the current version is causing some UI libraries to be incompatible

### ISSUE THREAD

**Issue by moyukingS** [nuxt/nuxt#20943]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.5.0
- Nitro Version:    2.4.1
- Package Manager:  pnpm@8.4.0
- Builder:          vite
- User Config:      app, routeRules, runtimeConfig, nitro, modules, pinia, imports, srcDir, image, i18n
- Runtime Modules:  nuxt-swiper@1.1.0, @vueuse/nuxt@10.1.2, @nuxtjs/i18n@8.0.0-beta.11, @nuxt/image-edge@1.0.0-28059208.2abef1b, nuxt-headlessui@1.1.4, @huntersofbook/naive-ui-nuxt@0.7.1, @nuxtjs/tailwindcss@6.7.0, nuxt-icons@3.2.1, @pinia/nuxt@0.4.10, @pinia-plugin-persistedstate/nuxt@1.1.1

### Reproduction

https://github.com/vuejs/core/issues/8353

### Describe the bug

missing semicolon in track function causing runtime error in production

https://github.com/vuejs/core/pull/8358

**Comment by danielroe** [comment]
I'll be releasing a patch this weekend but you can benefit now with `npx nuxi upgrade --force` which will regenerate the lockfile.

For Vue version differences, you may also need to use pnpm/npm overrides or yarn resolutions as sometimes package managers can install multiple versions if you have other packages that depend on it.
