### ISSUE TITLE
Get keys used by useFetch / useAsyncData || add option to exclude specific keys in refreshNuxtData()

### ISSUE THREAD

**Issue by mkierdev** [nuxt/nuxt#20949]
### Describe the feature

Currently there is no way to get a list of keys stored by useFetch / useAsyncData (at least documented).
Why would we need it? Generally to exclude them from refreshNuxtData().

Currently you have two options:
- refresh every data fetched from useFetch / useAsyncData
- refresh specific data by providing keys

Having access to all keys, we could have filter that array and pass it to refreshNuxtData().

Alternatively, it could be implemented as option for refreshNuxtData() to pass keys that we want to exlcude from refresh.

Simple use case:
Users signs out of page -> refreshNuxtData() -> every data is refreshed (you may want to refresh data only for page without knowing the key, but you don't want to refetch footer/header (you know the keys that should be excluded)

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
You should be able to see the keys by checking `useNuxtApp().payload.state` (for `useState` and `useNuxtApp().payload.data` (for `useAsyncData`).

**Comment by danielroe** [comment]
It is possible to pass a callback function to `refreshNuxtData` which would allow your use-case as-is, I think.
