### ISSUE TITLE
Component style in error.vue is missing on initial load

### ISSUE THREAD

**Issue by Siilwyn** [nuxt/nuxt#20958]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.4.3`
- Nitro Version:    `2.4.0`
- Package Manager:  `npm@9.5.1`
- Builder:          `vite`

### Reproduction

https://codesandbox.io/p/sandbox/nuxt-missing-styling-error-md91h6

View https://md91h6-3000.csb.app/nope with JS disabled to see the styling on the 'greetings' component missing. (Index page has the same component with the styling being properly shipped: https://md91h6-3000.csb.app/ )

### Describe the bug

A component with styling in `error.vue` does not ship with it's CSS on initial render, this only happens if the component is also used in another page.

**Comment by VladStepanov** [comment]
+1. Same with `nuxt.config.ts` -> `experimental.inlineSSRStyles = false`

**Comment by danielroe** [comment]
This is no longer reproducible, with or without `inlineSSRStyles`.

![CleanShot 2023-06-26 at 12 27 18](https://github.com/nuxt/nuxt/assets/28706372/b32068fb-8a5f-45e6-ad61-fb35ad89fcc5)

**Comment by Siilwyn** [comment]
Curious what caused it but happy it's fixed anyway! :)
