### ISSUE TITLE
Should skip unique keys generation for local functions having same names with keyed composables

### ISSUE THREAD

**Issue by ah-dc** [nuxt/nuxt#20954]
### Environment

Any

### Reproduction

https://stackblitz.com/edit/github-x5babp?file=app.vue

### Describe the bug

The composable-keys plugin only detects imports, we should detect local variables too. 
For example,
```js
function useState() {}
useState()
```

This may not that useful if the function is defined in user's code. But when some libraries has such functions and got bundled, there's chances those functions become local and break something. (e.g. `DatePicker` component of `@arco-design/web-vue`, )

### Additional context

I am willing to send a pr

**Comment by danielroe** [comment]
If you're happy to look at it, that would be great, thanks! ❤️

We could add an additional property here specifying where the composable needs to be imported from, for example:

https://github.com/nuxt/nuxt/blob/b3a09a62c96a0c10559c7790d08e351b14cae9cb/packages/schema/src/config/build.ts#L147-L155

**Comment by ah-dc** [comment]
> 

ok
