### ISSUE TITLE
I can't load enum in nuxt typescript :(

### ISSUE THREAD

**Issue by muzanella11** [nuxt/nuxt#20960]
### Environment

Local

### Reproduction

I'm using nuxt 3 and want to load my enum file in node module package. Nuxt always return error 500 like this one
<img width="1661" alt="Screen Shot 2023-05-19 at 21 50 31" src="https://github.com/nuxt/nuxt/assets/12839006/49a63a24-3124-4a56-86cd-a0d950f56b95">

This my code 
```
<script lang="ts" setup>
import { EventType } from '@mau-undang-backend/core/src/definitions/event-type.enum'

// I just want to using my enum :(
console.info('pleease help me to fix it :( ', EventType)
<script>
```

### Describe the bug

I cant load my enum file in nuxt :(

**Comment by NozomuIkuta** [comment]
@muzanella11 

Is it possible to provide a reproduction so that people could find the cause?

**Comment by ianjamieson** [comment]
I can reproduce it here:

https://stackblitz.com/github/ianjamieson/debug-nuxt-import-enums?file=playground%2Fapp.vue

Example is undefined in this instance. 

I tried also adding an import in the module definition, which results with my IDE finding the enum and adding auto complete options for it without needing to import it.

But then when accessing the page, it still shows as undefined.

**Comment by NozomuIkuta** [comment]
@ianjamieson 

Thank you for providing a reproduction.

It seems that you are making some mistakes in your code.

1. You "declare" `Example` enum without actually defining it

    If I'm correct, `declare` is used to tell TypeScript that "this is implemented somewhere else so it's safe to run. Here I just want to define its type for you to refer".

1. You import `Example` enum wrongly

    While you export `Example` as default export, you import it as named export `Example` in `app.vue`

In summary, if you remove `declare` and fix import name, your code works:

https://stackblitz.com/edit/github-qnieyk

---

Here are some more information for deep understanding.

Pushing a dir on `imports:dirs` hook means that files in the directory and their exports are listed up in `.nuxt/imports.d.ts`, which in turn means that you can import them from `#imports` alias.

Note that if you default-export something, the file name is used as named export. For example, if you push `path/to/your/module/runtime` dir, and `enums.ts` file exists there with default export, you can import the default export as named export `enum` from `#imports` alias.

```ts
// path/to/your/module/runtime/enums
const something = true

export default something
```

```ts
// .nuxt/imports.d.ts
export { default as enums } from `path/to/your/module/runtime/enums`
```

```ts
// your file
import { enums } from `#imports`
```

If you named-export something, the name is used to export from `#imports`:

```ts
// path/to/your/module/runtime/enums
export const something = true
```

```ts
// .nuxt/imports.d.ts
export { something } from `path/to/your/module/runtime/enums`
```

```ts
// your file
import { something } from `#imports`
```

That is, if you want use default export in your file while letting `#imports` export it as named export, you have to give the same name to the file and the export.

Here are sample code:

https://stackblitz.com/edit/github-zkqn92

---

@muzanella11

I'm not sure what happens in your case, but I guess you are making same kind of mistakes 🤔 
I could help if you provide a reproduction.

**Comment by ianjamieson** [comment]
Thanks @NozomuIkuta for the detailed response.
