### ISSUE TITLE
antdv [Vue warn]: Hydration node mismatch

### ISSUE THREAD

**Issue by daomiaru** [nuxt/nuxt#20966]
### Environment

- Operating System: Darwin
- Node Version:     v18.14.1
- Nuxt Version:     3.4.0
- Nitro Version:    2.3.3
- Package Manager:  npm@9.3.1
- Builder:          vite
- User Config:      modules, runtimeConfig, css, build, vite
- Runtime Modules:  @pinia/nuxt@0.4.9
- Build Modules:    -

### Reproduction

![image](https://github.com/nuxt/nuxt/assets/52020723/74591e29-b495-4fc4-9269-2f18d454ba6c)
<img width="1462" alt="image" src="https://github.com/nuxt/nuxt/assets/52020723/c84e8e29-3d44-424f-82ca-4cf71a1feef0">

### Describe the bug

It seems that the a-carousel component has not been properly parsed on the server. I attempted to configure nuxt.config 

build:{
transpile: [/ant-design/],
}

Still useless

**Comment by warflash** [comment]
Have you checked whether wrapping the `<a-carousel>` in `<client-only>` fixes the issue?

**Comment by huang-julien** [comment]
Hi can you provide a minimal reproduction please ? at first sight, it seems to be either an upstream issue from `antdv` either that a component from `antdv` does not support SSR.
As mentioned by @warflash it can be the `a-carousel`, `slider` (probably an internal component from `antdv`) or `a-image`

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by daomiaru** [comment]
Sorry, I tried using stackblitz to provide a demo on my end, but it seems to have no effect. The code is actually very simple, as I wrote in the screenshot

**Comment by daomiaru** [comment]
我这边尝试a-image不包裹在a-carousel里面，单独使用时是不会有告警的，我猜测可能carousel这个组件并不支持ssr,或者是其他的什么原因

**Comment by daomiaru** [comment]
I am trying to use a-image without wrapping it inside the a-carousel, so there will be no alarm when used alone. I suspect that the carousel component may not support SSR, or for some other reason

**Comment by daomiaru** [comment]
> Have you checked whether wrapping the `<a-carousel>` in `<client-only>` fixes the issue?
