### ISSUE TITLE
experimental.viewTransition + Anchor point link will cause temporary page downtime

### ISSUE THREAD

**Issue by libondev** [nuxt/nuxt#20977]
### Environment

- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.5.0
- Nitro Version:    2.4.1
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      modules, experimental
- Runtime Modules:  @nuxt/content@2.6.0, @nuxt/ui@0.4.1
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-36uxp6?file=pages%2Ftest.vue

steps:
1. View the `/` or `/test` page
2. Click the heading link text

If you directly access a with a anchor link, the same situation will occur after loading is complete.

### Describe the bug

This problem occurs when you click on the link on the page to change the url. I observed through the performance panel in the chrome devtools tool that a script command that takes 4 seconds will be executed after clicking.

<img width="1801" alt="image" src="https://github.com/nuxt/nuxt/assets/47918504/35420337-dbda-4e22-8394-af12312c7908">

In the meantime, the following is the performance profile file I recorded
[Profile-20230521T104434.txt](https://github.com/nuxt/nuxt/files/11523639/Profile-20230521T104434.txt)

### Additional context

If you use `transition.ready.then()` in the `view-transition.client.ts` file, you will get an update timeout error message on the console.

```js [view-transition.client.ts]
transition.ready.then((v) => {
      console.log('ready', v)
})
```

> Uncaught (in promise) DOMException: Transition was aborted because of timeout in DOM update

By the way, I know very little about startViewTransition API, but I think it's more like a chromium problem. I added the same interceptor code to the vue-router project and got the same results.

**Comment by vasilistotskas** [comment]
I also face the same problem but only when i click on pagination that changes the route like: 

```
<NuxtLink
  :to="{
    path: link,
    query: {
	    page,
	    ordering: route.query?.ordering
    }
  }"
/ >
```
in general the navigation is really smooth but when i add query string in current route the page freeze for 2-3 seconds.

**Comment by Jannchie** [comment]
It looks like this viewTransiton option is for different page jumps. If it is routed on the same page, a bug will occur.

A simple solution is to determine if the path is the same in `view-transitions.client.ts`.

I've tested this and it works fine.

``` ts
// view-transitions.client.ts
router.beforeResolve((to, from) => {
  if (to.path === from.path || to.meta.pageTransition === false) { return }
  ...
}
```

**Comment by Jannchie** [comment]
I just found that `pageTransition` API also using `to.path === from.path` determine. 
I will make a PR to solve this issue.

**Comment by juane1000** [comment]
This timeout issue also occurs when navigating to the same route that has a dynamic parameter

/parent/child/:id

where parent-route has:
`
<main>
  <header>
     <NuxtLink to="/parent/child/1">ID 1</NuxtLink>
     <NuxtLink to="/parent/child/2">ID 2</NuxtLink>  
  </header>
  <NuxtPage :page-key="route => route.name?.toString()" />
</main>
`
The component  instance is reused when navigating to a different id of the same route. Not sure how to proceed to get around this timeout problem. I removed the page-key to confirm that it works correctly but obviously lose the component instance re-use.
