### ISSUE TITLE
Not resolve module

### ISSUE THREAD

**Issue by xtoolkit** [nuxt/nuxt#20978]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.17.1
- Nuxt Version:     3.5.0
- Nitro Version:    2.4.1
- Package Manager:  pnpm@8.5.1
- Builder:          vite
------------------------------

### Reproduction

https://stackblitz.com/edit/github-swvjdy?file=app.vue

### Describe the bug

```vue
<template>
  <div>hello</div>
</template>

<script lang="ts" setup>
import * as components from '#components';

console.log(components);
</script>
```

When we import all exports as a variable, that variable not rendered in sfc.

### Additional context

This code okay in v3.4.0

### Logs

```shell-script
ReferenceError: components is not defined
```

**Comment by danielroe** [comment]
See https://github.com/nuxt/nuxt/issues/20733#issuecomment-1539151092.
