### ISSUE TITLE
upgrade to 3.5.1 ,get an error on Browser console TypeError: webCrypto.randomUUID is not a function

### ISSUE THREAD

**Issue by GITleonine1989** [nuxt/nuxt#20988]
### Environment

- Operating System: Windows_NT
- Node Version:     v16.16.0
- Nuxt Version:     3.5.1
- Nitro Version:    2.4.1
- Package Manager:  npm@8.11.0
- Builder:          vite
- User Config:      experimental
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-qleyyo 
here is this code ,but can`t  reproduce this issue.the same code on my local machine get this error
![image](https://github.com/nuxt/nuxt/assets/7582490/98185022-e6e7-475d-9ba0-4203df4f27e2)

### Describe the bug

when  i use a server component,  and set componentIslands true, the browser console will get a error: `TypeError: webCrypto.randomUUID is not a function`.

```
components/Header.server.vue
```
```
 experimental: {
    componentIslands: true,
  },
```
app.vue: 
```
<template>
  <div>
    <Header />
  </div>
</template>
```

But i cant reproduce  this issue on the stackblitz, and this issue occur when i upgrade  from v.3.4.3 to v.3.5

**Comment by maou-shonen** [comment]
WebCrypto is only enabled in HTTPS and localhost environments.
could this be the cause of your issue?

**Comment by GITleonine1989** [comment]
@maou-shonen i tried,you are right ,  this issue  occur  when i through the ip+port visit my site.
