### ISSUE TITLE
nuxtpage keepalive include can't work.

### ISSUE THREAD

**Issue by tenfei4** [nuxt/nuxt#20991]
### Describe the feature

I hope to improve the working principle of nuxtapp :keepalive, and I hope to work with a list that developers can control, such as directly using useState to control the include list of keepalive, instead of the current situation that can only be based on router, single max and one parameter can be controlled. I have already used nuxt3 on the project and hope to join the keepalive controllable list as soon as possible. Thank you very much.
```
<script setup>
const aliveList=computed(()=>useAliveList().value.join(','));
</script>
<template>
    <NuxtLayout>
        <NuxtLoadingIndicator :duration="6000"/>
        <NuxtPage :keepalive="{include:aliveList}"/>
    </NuxtLayout>
</template>
```

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/15214.

**Comment by freezyh** [comment]
> Let's track in #15214.

keepalive include/exclude props don't work with <NuxtPage>

**Comment by freezyh** [comment]
> Let's track in #15214.
 it is very big bug, can not control page keepalive, only all use, or all no
