### ISSUE TITLE
DEV SERVER ERROR - Afetr updating utils or composables

### ISSUE THREAD

**Issue by alessioraggioli** [nuxt/nuxt#20997]
### Environment

dev

### Reproduction

https://stackblitz.com/edit/nuxt-starter-hcptr4?file=utils%2Fhelper.js

### Describe the bug

The dev server throw an error after updating any function in utils or composable folders.
You can reproduce it here: https://stackblitz.com/edit/nuxt-starter-hcptr4?file=utils%2Fhelper.js

### Additional context

https://stackblitz.com/edit/nuxt-starter-hcptr4?file=utils%2Fhelper.js

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/18897
