### ISSUE TITLE
Force ErrorComponent not to be async?

### ISSUE THREAD

**Issue by edwh** [nuxt/nuxt#20996]
### Describe the feature

I'm seeing errors in a live system that suggest this scenario.  Suppose you're on mobile with an unreliable network connection.  You'll see problems that may result in you ending up on the error page.  

But Nuxt has this:

`const ErrorComponent = defineAsyncComponent(() => import('#build/error-component.mjs').then(r => r.default || r))`

Because `ErrorComponent` is async, the load of that may fail too.

Is there / could there be a way to force `ErrorComponent` to be included in the initial bundle so that it is always available?

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
In fact, I think this is a good idea to do by default. PR welcome. 👍

**Comment by danielroe** [comment]
resolved in https://github.com/nuxt/nuxt/pull/21406
