### ISSUE TITLE
Layout doesnt change when using navigateTo in Route Middleware

### ISSUE THREAD

**Issue by Serpentarius13** [nuxt/nuxt#21002]
### Environment

Nuxt 3.5.0

### Reproduction

I have a middleware than logs user in if he has a token and checks provided page meta to decide if to redirect him or not:
```ts

import { useUserStore } from "~/stores/useUser";

export default defineNuxtRouteMiddleware(async (request) => {
  if (process.server) return;

  const userStore = useUserStore();

  console.log(userStore.user);

  if (!userStore.user && userStore.isAuthPossible) {
    await userStore.loginWithToken();
  }

  console.log(userStore.user);
  if (request.meta.auth) {
    console.log("!");
    switch (request.meta.auth) {
      case "user":
        if (!userStore.user) {
          return navigateTo("/login");
        }
        break;
      case "guest":
        if (userStore.user) return navigateTo("/profile");
    }
  }
});

```

Store itself:

```ts
import { defineStore } from "pinia";

import { useCookies } from "vue3-cookies";

import { AUTH_COOKIE_KEY } from "~/features/constants/auth.constants";
import {
  IAccount,
  TLoginData,
  TRegisterData,
} from "~/features/types/auth.types";

interface IUserStoreState {
  user: IAccount | null;
}
const { cookies } = useCookies();
export const useUserStore = defineStore("user-store", {
  state: (): IUserStoreState => ({
    user: null,
  }),
  actions: {
    async login(data: TLoginData) {
      try {
 const { apiLogin } = useAuth();
        const user = await apiLogin(data);

        if (typeof user === "object") {
          cookies.set(AUTH_COOKIE_KEY, user.token);

          this.user = user.account;
        }
      } catch (error: any) {
        throw new Error(error);
      }
    },

    async loginWithToken() {
      try {
        const { apiLoginWithToken } = useAuth();

        const token = cookies.get(AUTH_COOKIE_KEY);

        if (!token) return;

        const user = await apiLoginWithToken(token);

        if (typeof user === "object") this.user = user;
        else throw new Error("Error getting user");
      } catch (error) {
        throw new Error(error);
      }
    },

    async register(data: TRegisterData) {
      try {
        const { apiRegister } = useAuth();

        const user = await apiRegister(data);

        if (typeof user === "object") {
          cookies.set(AUTH_COOKIE_KEY, user.token);

          this.user = user.account;
        }
      } catch (error) {
        throw new Error(error);
      }
    },
  },
  getters: {
    isAuthPossible() {
      return !!cookies.get(AUTH_COOKIE_KEY);
    },
  },
});

```

### Describe the bug

Everything works as expected, but with navigation layout doesnt change and remains the same. Probably a dupe of https://github.com/nuxt/nuxt/issues/389

https://www.veed.io/view/40d8ead8-e5de-4d19-885c-5fbd0c445ba0?sharingWidget=true&panel=

**Comment by Serpentarius13** [comment]
> Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

https://github.com/Serpentarius13/nuxt-example-bug here you go
As ive noticed when reproducing, it only happens with a) api call b) layout structure from my project which i included

**Comment by danielroe** [comment]
I think the issue here is that you are redirecting the route before the page has finished hydrating, which basically causes a hydration error because the rendered HTML on the server is _for a different page_.

There are some other strategies that can help you in the case. For example, can could early-return from the middleware when `useNuxtApp().isHydrating` is true and then use something like `onNuxtReady` in a plugin to perform an initial navigation on client side if needed.

**Comment by Serpentarius13** [comment]
@danielroe thanks for your work :) can you please elaborate on how to do that? im a newbie ._.

**Comment by rezelute** [comment]
Im not entirely sure I understand the suggestion mentioned here either ... ?

**Comment by ekrausso** [comment]
Having issues with this too... on prerendered routes

**Comment by artemklishch** [comment]
> 
@danielroe 
Hello!
I get the similar issue. In case of the redirection in the middleware - it outputs the two pages simultaneously with error message about 'hydration'.
In my case I can't resolve it with 'useNuxtApp().isHydrating' nor in plugin nor in the middleware - because it always equals to 'false'

I put the 'navigateTo(<route>)' expression inside the 'setTimeout' and it started to work as it is supposed.
But I don't consider that this is a good solution.

Is there any better way to resolve that?

Thank you!

**Comment by artemklishch** [comment]
> 

much better to use:

onBeforeMount(() => {
  if(!userGetter.value){
    navigateTo('/')
  }
})

in the protected component, but I would like to use Nuxt 3 itself special tool for that - 'midleware'

**Comment by danielroe** [comment]
Prerendered routes should also be hydrated and there is a moment before the app is mounted, when isHydrating is set to true.

I'm happy to provide some code if you can share what you are trying.

**Comment by zweeen** [comment]
I guys

I faced the same problem. I fixed it by calling vue3 composable `useRouter() `instead of Nuxt 3 helper fonction `NavigateTo` within my `middleware`:

### ❌ NavigateTo :

```
export default defineNuxtRouteMiddleware(async (to) => {
    const authStore = useAuthStore()

    if (!authStore.isUserConnected) {
        authStore.setRoute(to.fullPath)
        return navigateTo({
            path: '/customRoute',
        })
    }
})

```
### ✅ useRouter
```
export default defineNuxtRouteMiddleware(async (to) => {
    const authStore = useAuthStore()
    if (!authStore.isUserConnected) {
        const router = useRouter()
        authStore.setRoute(to.fullPath)
        return router.push({ path: '/customRoute' })
    }
})
```

**Comment by Stf-F** [comment]
Also fixed this by adding the `external:true` parameter to my `navigateTo`.
My global auth middleware:
```javascript
// middleware/auth.ts
export default defineNuxtRouteMiddleware(async (to, from) => {
  if (process.server) return;
  const user = await getCurrentUser();
  const publicPages = ["/login", "/register", "/thank-you", "/verify"];
  if (!user && !publicPages.includes(to.path)) {
    return navigateTo({
      path: "/login",
      query: {
        redirect: to.fullPath,
      },
    });
  }

  // If user is defined and they are on a public page, redirect to dashboard
  if (user && publicPages.includes(to.path)) {
    return navigateTo(
      {
        path: "/dashboard",
      },
      {
        external: true, // adding this fixes the issue of layouts not being updated 
      }
    );
  }
});

```
