### ISSUE TITLE
Support assetsInclude

### ISSUE THREAD

**Issue by dtrinh100** [nuxt/nuxt#21019]
### Describe the feature

I would like to see the `assetsInclude` config from Vite supported in the Nuxt configs. I have a few `.gltf` files that are a part of my assets directory, but currently can't get them to be included during the build. The workaround is to have them in the public directory.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Have you tried:

```ts
export default defineNuxtConfig({
  vite: {
    assetsInclude: [/\.gltf/]
  }
})
```

If that's not working, maybe a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction) could be a helpful first step?

**Comment by dtrinh100** [comment]
I tried using regular expression for that too and it doesn't seem to work.

I have reproduced the issue here:
https://stackblitz.com/edit/github-1mvead

When you run `npm run build`, the `.gltf` file doesn't get copied over.

**Comment by danielroe** [comment]
You don't seem to be using them during the build at all. Is there a reason you don't want them in the `public/` folder? (Normally this is where you would put assets that you don't want to be transformed as part of a build process. It allows Nuxt to set appropriate cache headers, for example...)

**Comment by dtrinh100** [comment]
In my real use case, I do need to import the file into my Vue component. From my understanding, I can't do that using the `public/` directory.

**Comment by danielroe** [comment]
Maybe you can update the repository to show how you are using it?

**Comment by dtrinh100** [comment]
I unfortunately could not upload a `.glb` file, which is just the binary version of the `.gltf` file probably due to the size, but I did update my code here to show how I usually import the model,

https://stackblitz.com/edit/github-1mvead?file=components%2Ftest.vue%3AL19

**Comment by danielroe** [comment]
The use case there really seems better suited to the `public/` directory. It's not included in the build other than being referenced via string. Vite doesn't process that at all other than to copy it across. Try including it in `~/public/assets` (or similar) and referencing via `assets/` rather than `_nuxt/assets/`...

**Comment by dtrinh100** [comment]
Ok, using the `public` folder does work. Though I may need to process the file in the future during the build step, but that is currently not yet required for me.
