### ISSUE TITLE
element-plus

### ISSUE THREAD

**Issue by hedengxing** [nuxt/nuxt#21018]
### Environment

- Operating System: Windows_NT
- Node Version:     v16.20.0
- Nuxt Version:     3.5.1
- Nitro Version:    2.4.1
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      publicRuntimeConfig, debug, crossOriginPrefetch, meta, css, typescript, modules, vueuse, elementPlus, localtunnel, devtools, runtimeConfig, postcss, vite
- Runtime Modules:  @pinia/nuxt@0.4.11, @vueuse/nuxt@10.1.2, nuxt-svgo@3.1.0, nuxt-swiper@1.1.0, nuxt-lodash@2.4.1, @nuxtus/nuxt-localtunnel@1.0.1, @element-plus/nuxt@1.0.5

### Reproduction

1

### Describe the bug

开启页面过渡时 来回切换路由 element-plus 的 v-infinite-scroll 
![1684812643084](https://github.com/nuxt/nuxt/assets/46393161/0507f72a-50cd-4d32-9585-35a10392a823)
![1684812580030](https://github.com/nuxt/nuxt/assets/46393161/a1aeb136-019a-4ff3-9746-1a78232e4f98)

**Comment by danielroe** [comment]
This doesn't seem like a Nuxt issue - that code is coming from a library you are using (element-plus?). I would suggest raising an issue there.
