### ISSUE TITLE
Production mode cannot fetch correct data when request is frequently

### ISSUE THREAD

**Issue by Donny2333** [nuxt/nuxt#21025]
### Environment

- Operating System: Windows_NT
- Node Version:     v16.20.0
- Nuxt Version:     3.5.1
- Nitro Version:    2.4.1
- Package Manager:  npm@8.19.4
- Builder:          vite
- User Config:      ssr, app, css, modules, nitro, mongoose
- Runtime Modules:  @pinia/nuxt@0.4.11, nuxt-mongoose@0.0.6
- Build Modules:    -

### Reproduction

should I provide?

### Describe the bug

`useFetch` to fetch 20+ request in one seconds only return the last request. Other's data is null.

dev mode works well. only appear in prod mode.

### Additional context

Run `nuxt dev` works well.

But run `nuxt build && npx nuxt start`, it appears.

Is because Product mode has some other configs?

![image](https://github.com/nuxt/nuxt/assets/12244311/2ee5d91a-10a0-483e-b1d6-a9e820481487)

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/15164
