### ISSUE TITLE
cndURL does not work for content rendered with v-for

### ISSUE THREAD

**Issue by RayJason** [nuxt/nuxt#21021]
### Environment

- Operating System: Darwin
- Node Version:     v18.15.0
- Nuxt Version:     3.5.1
- Nitro Version:    2.4.1
- Package Manager:  pnpm@8.1.1
- Builder:          vite
- User Config:      app, devServer, typescript, modules, extends, css, runtimeConfig, imports, pinia, linkChecker, vite
- Runtime Modules:  @pinia/nuxt@0.4.11, @element-plus/nuxt@1.0.5, @vueuse/nuxt@10.1.2, @nuxtjs/tailwindcss@6.7.0, @nuxtjs/eslint-module@4.1.0, @pinia-plugin-persistedstate/nuxt@1.1.1, nuxt-lodash@2.4.1, nuxt-icons@3.2.1
- Build Modules:    -

### Reproduction

[《minimal reproduction nuxt3-cdnurl-not-working》](https://1024code.com/codecubes/jaed0ty)
```html
<template>
  <div>
    <h1>inline src</h1>
    <div class="list">
      <div class="list-item">
        <img src="/img/a.webp" alt="img1" />
        <p>img1</p>
      </div>

      <div class="list-item">
        <img src="/img/b.webp" alt="img2" />
        <p>img2</p>
      </div>

      <div class="list-item">
        <img src="/img/c.webp" alt="img3" />
        <p>img3</p>
      </div>
    </div>
  </div>

  <!-- cndURL does not work for content rendered with v-for -->
  <div style="margin-top: 5rem">
    <h1>v-for render object src</h1>
    <div class="list">
      <div v-for="item in list" :key="item.id" class="list-item">
        <img :src="item.src" :alt="item.name" />
        <p>{{ item.name }}</p>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
const list = [
  {
    id: 1,
    name: 'img1',
    src: '/img/a.webp',
  },
  {
    id: 2,
    name: 'img2',
    src: '/img/b.webp',
  },
  {
    id: 3,
    name: 'img3',
    src: '/img/c.webp',
  },
]
</script>
```

### Describe the bug

cndURL does not work for content rendered with v-for. 
![](https://github.com/nuxt/nuxt/assets/15711610/b112d5c8-ffb5-48b3-acc3-4ae16dcff6f3)

### Additional context

It was working in 3.4.x.

**Comment by danielroe** [comment]
Would you see if you can reproduce in https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter - I don't believe this is a Nuxt issue.

**Comment by qiuqimin** [comment]
same problem

**Comment by danielroe** [comment]
The issue here is that Vue doesn't compile this into a dynamic property - it remains a string.

I think you're current workaround is best. We might expose a helper in future to make this easier. Let's track in https://github.com/nuxt/nuxt/issues/19818.
