### ISSUE TITLE
`experimental.typedPages`: Export types to make usable in application

### ISSUE THREAD

**Issue by madebyfabian** [nuxt/nuxt#21032]
### Describe the feature

Hey there! I'm really excited about the new `typedPages` feature. Great work on that one!

I would like to create composable, for example a `useGetAppLocation`, that essentially returns a resolved url while adding a param that every url in my app needs. Example:

```ts
// props must be any because we don't have a type for it :/
export const useGetAppLocation = (props: any) => {
	const router = useRouter()
	const currentSpaceStore = useCurrentSpaceStore()

	return router.resolve({
		...props,
		params: {
			...props.params,
			spaceKey: currentSpaceStore.currentSpaceKey
		}
	})
}
```

I would like to type this function, but as far as I can see nuxt doesn't export any types to do so. The `router.resolve()` uses `RouteNameMap`, `RouteLocationAsRelativeTyped`, `RouteLocationResolvedTyped ` and so on.

Ideally, these types could be used in an application.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
These types should be importable because we use them within Nuxt. Try:

```ts
import type { RouteLocation, RouteLocationRaw } from '#vue-router'
// ...
```
