### ISSUE TITLE
`nuxi dev` does not fully respect `--no-clear` option

### ISSUE THREAD

**Issue by Meadowsys** [nuxt/nuxt#21036]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.20.0`
- Nuxt Version:     `3.5.1`
- Nitro Version:    `2.4.1`
- Package Manager:  `pnpm@8.5.1`
- Builder:          `vite`
- User Config:      `telemetry`, `devServer`, `postcss`, `typescript`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Works with newly created project (ex. `pnpx nuxi init my-project`)

### Describe the bug

As before, the console wouldn't clear if the `--no-clear` option were passed to `nuxi dev`. This can be observed by running `nuxi dev` (or running the `dev` script with ex. `pnpm run dev`) and seeing that the terminal clears. Then, run `nuxi dev --no-clear` (or changing the `dev` script in `package.json` to be `nuxt dev --no-clear`), run it again, observe that the screen is not cleared but output is appended to it. This is as expected.

Then, open the project in an editor, and make a change. Observe that the screen is cleared anyway, regardless of `--no-clear` option.

### Additional context

Last version that I know of that doesn't do this is v3.2.3

**Comment by Meadowsys** [comment]
Thank you so much!

**Comment by danielroe** [comment]
You are very welcome 😊
