### ISSUE TITLE
[Bug] (another) Requested module does not provide export named 'default'

### ISSUE THREAD

**Issue by silverbackdan** [nuxt/nuxt#21034]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.5.1`
- Nitro Version:    `2.4.1`
- Package Manager:  `pnpm@8.5.1`
- Builder:          `vite`
- User Config:      `modules`, `cwa`, `extends`, `srcDir`, `typescript`
- Runtime Modules:  `nuxt-vitest@0.7.1`
- Build Modules:    `-`

### Reproduction

I am using `lodash` in my module https://github.com/components-web-app/cwa-nuxt-module/tree/nuxt3

### Describe the bug

When running the module it all works fine in the playground, but it is when the module is packaged up and distributed on NPM registry that I then use it in a Nuxt application and I get 
```
Uncaught (in promise) SyntaxError: The requested module '/_nuxt/@fs/[...]/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/isEqual.js?v=180b8f2b' does not provide an export named 'default' (at ComponentGroup.vue:22:8)
```

I can replicate this error in the module if in the playground nuxt config I add 
```
...
build: {
  transpile: ['lodash']
}
...
```

So I'm just wondering, when using a cjs package in a module, is there a best practice or some config / workaround I can use to help here. I'm not sure I understand the issue that I'm experiencing but it does seem related to the optimisations of the imports from the package using cjs. I had the same issue with the bluebird dependency but have since refactored so I do not need to use it.

### Additional context

I'm not sure how to best reproduce this as it's only a bug once the module is packaged to npm and then used in another application - I'm wondering if there's any helpful info that could be provided or material for me to look at? I've looked here https://nuxt.com/docs/guide/concepts/esm#default-exports but it doesn't seem to help. Perhaps I'm doing something wrong..

**Comment by silverbackdan** [comment]
To resolve this, in my application I need to add an alias:
```
  alias: {
    'lodash/isEqual': 'lodash/isEqual.js'
  }
```

Is there a bug to be fixed here to allow us to use lodash in this way - or is it completely unnecessary to import lodash using this syntax due to advanced tree-shaking. I noticed in some places it had been the recommended way to only import what we need.

**Comment by danielroe** [comment]
Yes, it is necessary to import with file extensions unless you add `/lodash/` to your `build.transpile` array, which is a consequence of how lodash is packaged + the way that native ESM imports work.

**Comment by danielroe** [comment]
Let me know if not and I'll happily reopen!

**Comment by silverbackdan** [comment]
Hi @danielroe 

When I changed the import in my module to `lodash/isEqual.js` I still need to add this in the nuxt application config using the module once it the module has been published:
```
alias: {
    'lodash/isEqual.js': 'lodash/isEqual.js'
  }
```

**Comment by avxkim** [comment]
@danielroe just tried to use extension `import debounce from 'lodash/debounce.js'` doesn't work either, maybe am i missing something?

**Comment by silverbackdan** [comment]
@avxkim is this when developing a module as well or just within your application?
@danielroe sorry for the news that this one seems to need reopening at least on some level. perhaps we can find some common ground on when this happens

**Comment by silverbackdan** [comment]
MUCH nicer workaround for now thank you - perhaps we open a new issue to get attention and reference this as the fix that works. It could give a much better insight to the maintainers as to what is going wrong.

**Comment by danielroe** [comment]
This is very probably an issue with lodash's packaging, and is unlikely to be fixed in the current lodash major release. `vite.optimizeDeps` exists to allow handling these kind of packages; it's not something Nuxt should fix.
