### ISSUE TITLE
public directory is not included in the build when using `vite.publicDir` and `srcDir` in nuxt config

### ISSUE THREAD

**Issue by marifcelik** [nuxt/nuxt#21030]
### Environment

- Operating System: Linux
- Node Version:     v20.1.0
- Nuxt Version:     3.5.0
- Nitro Version:    2.4.1
- Package Manager:  pnpm@8.5.1
- Builder:          vite
- User Config:      srcDir, devtools, app, css, router, runtimeConfig, vite
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-z5qg55

### Describe the bug

I'm using custom `srcDir` and custom `publicDir` in my project. i have this config in `nuxt.config.ts`

```ts
export default defineNuxtConfig({
  srcDir: 'src',
  vite: {
    publicDir: '../public'
  }
})
```

and this file structure
```
public/
src/
--pages/
package.json
... etc.
```

I can use the public folder while the dev server is running, but not after the build. The public folder is not included in the build process.

**Comment by marifcelik** [comment]
@danielroe thank you, but in DX, wouldn't it be enough to specify `vite.publicDir` ?

**Comment by danielroe** [comment]
It is enough just to specify `dir.public`, and this is required because there are other things (like configuring Nitro) that depend on knowing where public assets are located.
