### ISSUE TITLE
`useCookie`-Hook adds useless `Set-Cookie`-Header

### ISSUE THREAD

**Issue by LouisHaftmann** [nuxt/nuxt#21038]
The `useCookie` hook currently adds a `Set-Cookie` header even when the value of the cookie is `null` or `undefined` ([source](https://github.com/nuxt/nuxt/blob/a672cd7a4291eb812d76b9841ec516cd8609c680/packages/nuxt/src/app/composables/cookie.ts#LL68C1-L73C2)):

```js
function serializeCookie (name: string, value: any, opts: CookieSerializeOptions = {}) {
  if (value === null || value === undefined) {
    return serialize(name, value, { ...opts, maxAge: -1 })
  }
  return serialize(name, value, opts)
}
```

But the browser ignores it anyways since the `maxAge` is set to `-1`. I think it would be better to just don't add a cookie header if the value is `null` or `undefined`.

**Comment by thijsw** [comment]
I think this is needed to 'delete' a previously set cookie. By sending a Max-Age of -1 browsers decide to remove the cookie.

**Comment by pi0** [comment]
A reproduction would be nice. BTW here is the reference [`h3.setCookie`](https://github.com/unjs/h3/blob/3e5f42748ab73102c1b9c2059fe8fa110e734363/src/utils/cookie.ts#L54) dedup strategy. We probably have to use this utility or similar logic.

**Comment by LouisHaftmann** [comment]
Possible solution using H3's helper methods:

```ts
function writeServerCookie (event: H3Event, name: string, value: any, opts: CookieSerializeOptions = {}) {
  if (event) {
    // update if value is set
    if(value !== null && value !== undefined) 
      return setCookie(event, name, value, opts)

    // delete if cookie exists in browser and value is null/undefined
    const cookieAlreadySet = getCookie(event, name) !== undefined
    if(cookieAlreadySet)
      return deleteCookie(event, name, opts)

    // ignore if cookie doesn't exist in browser and value is null/undefined
  }
}
```

**Comment by agracia-foticos** [comment]
same issue
