### ISSUE TITLE
`devtools` type error in nuxt config file after run the server

### ISSUE THREAD

**Issue by marifcelik** [nuxt/nuxt#21035]
### Environment

- Operating System: Linux
- Node Version:     v20.1.0
- Nuxt Version:     3.5.1
- Nitro Version:    2.4.1
- Package Manager:  pnpm@8.5.1
- Builder:          vite
- User Config:      srcDir, dir, devtools, modules, ui
- Runtime Modules:  @nuxthq/ui@2.1.0
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-z5qg55

### Describe the bug

after run the server, the type of`devtools` option changes to string

![Screenshot from 2023-05-24 00-01-52](https://github.com/nuxt/nuxt/assets/46600975/a625e041-9778-43e7-8722-166c9aca669b)

**Comment by danielroe** [comment]
Reproduction: https://stackblitz.com/edit/github-z5qg55-xrhyv2.

**Comment by Lehoczky** [comment]
In order to this to work, [defineNuxtModule()](https://github.com/nuxt/nuxt/blob/357ad9bd31832803ed4a28f393b9e6457cfdc53f/packages/kit/src/module/define.ts#L16) must allow boolean as ModuleOptions but it [currently only accepts objects](https://github.com/nuxt/nuxt/blob/357ad9bd31832803ed4a28f393b9e6457cfdc53f/packages/schema/src/types/module.ts#L27)

This is what happens when trying to allow boolean as option type:
![image](https://github.com/nuxt/nuxt/assets/31937175/6c589338-00a0-4b65-96f2-50336cde1573)

I think it would be just easier to only allow to enable the devtools with `devtools: { enabled: true }` and not with `devtools: true`. It would even simplify the code [here](https://github.com/nuxt/nuxt/blob/357ad9bd31832803ed4a28f393b9e6457cfdc53f/packages/nuxt/src/core/nuxt.ts#L391) and [here](https://github.com/nuxt/devtools/blob/main/packages/devtools/src/module.ts#L15).

**Comment by danielroe** [comment]
We also have the same issue with `telemetry` which we have explicitly exempted in the types, IIRC.

**Comment by Lehoczky** [comment]
Yepp, it has [this `any` type casting](https://github.com/nuxt/telemetry/blob/main/src/module.ts#L30) to make the options comparable to `true` or `false` I think.

What do you guys think? Explicitly enable to use boolean for the `ModuleOptions` generic in `defineNuxtModule()` or change the `telemetry` and `devtools` plugin to only accept objects for options?

**Comment by danielroe** [comment]
I think I'd be happy to enable boolean for module options. Can you think of any downsides?

**Comment by marifcelik** [comment]
I think boolean is fine. If I just want to enable with default settings then I set to `true`.

**Comment by Lehoczky** [comment]
I see two potential issues:

#### Unintuitive option merging strategy

Right now we can have 3 objects and they are merged together with the following precedence: 
inline options -> keyed options -> defaults

This is pretty easy to remember and quite intuitive in my opinion. Just by looking at the following code I know what the options will be at the end:

```ts
export default defineNuxtModule({
  meta: { name: "test", configKey: "test" },
  defaults: { enabled: undefined },
})
```

```ts
export default defineNuxtConfig({
  modules: [
    ["./modules/test", { enabled: true }]
  ],
  test: { enabled: false },
})
```

However if we have a boolean in the mix, it gets trickier. What should the following resolve to?

```ts
export default defineNuxtConfig({
  modules: [
    ["./modules/test", true]
  ],
  test: { enabled: false },
})
```

To my surprise `defu` don't throw an error, but just ignores the boolean part. We can say, this is the way it will be resolved, or think about a more intuitive resolution strategy, but it will always be more complicated then knowing 3 objects can be merged together with a certain precedence. People will likely need to open the docs to know how the boolean part is being resolved.

#### API clarity

I try to always think about how people could misuse a certain API. Right now, it's easy to know what `telemetry: true` and `devtools: true` means, but what if a module author decides to use the boolean flag for something else then shortening `{ enabled: true}`?

For example, I could create a new eslint module, which has only one option: { showWarningsAsErrors: boolean }, then decide that the module can accept a simple boolean flag too to change this option. The users nuxt config would look like this:

```ts
export default defineNuxtConfig({
  modules: [...],
  eslint: true,
})
```

Which is now pretty misleading. By only accepting objects, it is clearer what the user configures for a module.

**Comment by danielroe** [comment]
I think can close this as devtools no longer accepts a boolean as an option.
