### ISSUE TITLE
[experimental.typedPages] Support i18n

### ISSUE THREAD

**Issue by szulcus** [nuxt/nuxt#21048]
### Describe the feature

`RouteNamedMap` from `#vue-router` have now all locale suffixes, and type checking not working in `localePath`. [Nuxt Typed Router](https://nuxt-typed-router.vercel.app/) already has i18n support.
![image](https://github.com/nuxt/nuxt/assets/48328739/f58702d9-6044-4ae5-9c2b-a38410797834)

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
If you are talking about type support for the `localePath` function, this will need to be implemented in `@nuxtjs/i18n` - it can be done by updating the type imports from `#vue-router`, as we've done here:

https://github.com/nuxt/nuxt/blob/4e6369cefa7c30dcff799a61738c8a04bc76799e/packages/nuxt/src/app/components/nuxt-link.ts#L3

**Comment by danielroe** [comment]
@szulcus You can use `pages:extend` I believe - we don't use the unplugin-vue-router to generate names, instead we tell it the names already generated by Nuxt (or modules), which you can modify in `pages:extend`. Be aware though, that changing the names may affect the behaviour of `@nuxtjs/i18n` and you could consider raising an issue there.
