### ISSUE TITLE
`script` and `style` tags in app.vue do not work if `srcdir` is specified

### ISSUE THREAD

**Issue by marifcelik** [nuxt/nuxt#21054]
### Environment

- Operating System: Linux
- Node Version:     v20.1.0
- Nuxt Version:     3.5.1
- Nitro Version:    2.4.1
- Package Manager:  pnpm@8.5.1
- Builder:          vite
- User Config:      srcDir, dir, devtools, modules, ui
- Runtime Modules:  @nuxthq/ui@2.1.0
- Build Modules:    -

### Reproduction

[View in StackBlitz](https://stackblitz.com/edit/github-d3w8pu?file=README.md)

### Describe the bug

`script` and `style` tags in app.vue do not work if `srcdir` is specified

The location of the app.vue file, in src or root dir, doesn't matter.

**Comment by baiwusanyu-c** [comment]
I think you should not set an empty or non-existent path as source directory of your Nuxt application

**Comment by manniL** [comment]
You should put all your source code in `src` then, including subfolders like `pages` and also the `app.vue`.

See https://stackblitz.com/edit/nuxt-21054?file=src%2Fpages%2Findex.vue
