### ISSUE TITLE
prerendering crashes with `@nuxtjs/i18n`

### ISSUE THREAD

**Issue by MosheL** [nuxt/nuxt#21051]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v19.4.0 // tried also 19.1, 19.9, 18.4
- Nuxt Version:     3.4.3 // tried also 3.5.1
- Nitro Version:    2.4.1 //tried also 2.3.3
- Package Manager:  yarn@2.4.3 //tried also NPM and yarn@1
- Builder:          vite
- User Config:      preset, server, loadingIndicator, css, app, modules, i18n, vite, nitro, experimental
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.12
- Build Modules:    -
------------------------------

### Reproduction

I an trying to create a repro but could not undestand what I  need to do for it.

I did

### Describe the bug

npx nuxt build

````
//log from linux machine
✔ Generated public .output/public                                                                            nitro 9:42:02 PM
ℹ Initializing prerenderer                                                                                   nitro 9:42:03 PM

 ERROR  Error: The service is no longer running: write EPIPE                                                 nitro 9:42:04 PM


// same code, build on Windows
why the proxy module need for prerender? how to remove it from this step ?


i Initializing prerenderer                                           nitro 21:43:01
[21:43:21] i [HPM] Proxy created: ... 
i Prerendering 1 routes                                              nitro 21:43:21

[21:43:21]  ERROR  (node:29456) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use node --trace-warnings ... to show where the warning was created)


[21:43:21]  ERROR  [nuxt] [request error] [unhandled] [500] Cannot use import statement outside a module
  at internalCompileFunction (node:internal/vm:73:18)
  at wrapSafe (node:internal/modules/cjs/loader:1195:20)
  at Module._compile (node:internal/modules/cjs/loader:1239:27)
  at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
  at Module.load (node:internal/modules/cjs/loader:1133:32)
  at Module._load (node:internal/modules/cjs/loader:972:12)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:165:29)
  at ModuleJob.run (node:internal/modules/esm/module_job:193:25)

  ├─ /__i18n__/prerender/365c1add.js (157ms) (Error: [500] )         nitro 21:43:21
i Building Nitro Server (preset: node-server)                        nitro 21:43:21

 ERROR  RangeError: Maximum call stack size exceeded                 nitro 21:45:01


undefined


 ERROR  Maximum call stack size exceeded                                   21:45:01

  at applyProductionCondition (/E:/inetpub/inn/nuxt3b/node_modules/nitropack/dist/shared/nitro.a3c42e5a.mjs:713:3)
  at applyProductionCondition (/E:/inetpub/inn/nuxt3b/node_modules/nitropack/dist/shared/nitro.a3c42e5a.mjs:724:5)
```



### Additional context

Exiting (working) install .
Tested on windows and on linux.

The old  logs from the working build did not  do the `prerender` step. the configuration  did not use the prerender as I am using SPA/SSR depending on the needs.


What  I was tried before opening the bug:
yarn, npm redownload  again and again
remove modules and build
tried to build with  nuxt/nuxi 3.4.1, 3.5.1, 3.4.2
tried diffrent node / OS versions.
tried to connect debugger to see where is the crash (code)
tried to add a logging code to  `applyProductionCondition`





### Logs

```shell-script
Thanks for all !!  we are using nuxt and happy with it.
```

**Comment by spiroszaf** [comment]
@MosheL Thanks for pointing me to the right direction. I had the same issue after I updated the `@nuxtjs/i18n@8.0.0-beta.9` to `@nuxtjs/i18n@8.0.0-beta.12` and moved the `vueI18n` property out of `nuxt.config.ts` into the `i18n.config.ts`, as requested by this [migration guide](https://v8.i18n.nuxtjs.org/guide/migrating#deprecated-vuei18n-option-to-not-accept-createi18n-options)

As a workaround I downgraded the package to `@nuxtjs/i18n@8.0.0-beta.10` and removed the config file.

**Comment by danielroe** [comment]
This is an downstream `@nuxtjs/i18n` issue.

**Comment by danielroe** [comment]
Nuxt _does_ prerender any routes you explicitly ask it to. And `@nuxtjs/i18n` is explicitly setting this config.

**Comment by MosheL** [comment]
You are right again.  I switched  to `@nuxtjs/i18n@8.0.0-beta.10` and the two problems disappeared.
`8.0.0-beta-12` is explicitly setting this config, as you wrote.  I do not set it (as I doesnt want to do it) and I could not know that they set this setting.

we still have the build errors with the last version, specific the  `ERROR  Maximum call stack size exceeded`, but I can build and work with the old version.


Thanks daniel.

**Comment by danielroe** [comment]
Let's track this upstream in i18n. A fix is in progress, I believe.

**Comment by FranciscoKloganB** [comment]
Sorry for posting on a closed issue. But I do not think the docs for `pre-rendering` are very clear, with or without, i18n. Not comparing apples to potatoes, when we use any of these "ssg", "ssr" on a particular page in Next, the build process, says which routes were pre-rendered and which ones weren't. I am not seeing a similar output on `nuxt build`, so I am not quite sure if my configuration was done correctly or not. :(

I also do not know, how to validate if the pre-render worked, or not, without going to production and actually changing content and redeploying. :thinking: Maybe some tips on these would be nice. :bow: 

```nuxt.config.ts
  nitro: {
    /**
     * @see https://nitro.unjs.io/config#routerules
     * @see https://github.com/unjs/radix3#route-matcher
     */
    routeRules: {
      '/': { static: true },
      '/about': { static: true },
      '/hire': { static: true },
      '/portfolio/**': { cache: { maxAge: minutes(15), swr: true } },
    },
  },
```

**Comment by danielroe** [comment]
Absolutely. Let's track in https://github.com/nuxt/nuxt/issues/21594

**Comment by FranciscoKloganB** [comment]
Thank you @danielroe. I will keep my eyes on that issue.
