### ISSUE TITLE
Nuxi 3.5.1 error on nuxt prepare Windows 10 

### ISSUE THREAD

**Issue by AntzyMo** [nuxt/nuxt#21055]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.5.1
- Nitro Version:    2.4.1
- Package Manager:  pnpm@8.5.1
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

![image](https://github.com/nuxt/nuxt/assets/45410431/e6752928-6938-4135-b0c0-e18eb2308209)
ok, so I'll just  `pnpm add @nuxt/devtools -D`, and the result is the same

### Describe the bug

I use this command `pnpm dlx nuxi init <project-name>`, then `pnpm i` the devtools error occurs

**Comment by danielroe** [comment]
cc: @antfu

**Comment by antfu** [comment]
@AntzyMo Can you try to remove the `.nuxtrc` file under your home directory and try again? Thanks.

**Comment by sasial-dev** [comment]
This also is the case on mac, with a different file.

**Comment by AntzyMo** [comment]
> @AntzyMo Can you try to remove the `.nuxtrc` file under your home directory and try again? Thanks.

Still the same

**Comment by hmuhdkamran** [comment]
I am facing the same issue,
.app prepare$ nuxi prepare
│ Nuxi 3.5.0
│  ERROR  Package subpath './utils' is not defined by "exports" in D:\Help\vue\tairo\node_modules\.pnpm\listhen@1.3.0\node_modules\consola\p…
│   at new NodeError (node:internal/errors:399:5)
│   at exportsNotFound (node:internal/modules/esm/resolve:266:10)
│   at packageExportsResolve (node:internal/modules/esm/resolve:602:9)
│   at packageResolve (node:internal/modules/esm/resolve:777:14)
│   at moduleResolve (node:internal/modules/esm/resolve:843:20)
│   at defaultResolve (node:internal/modules/esm/resolve:1058:11)
│   at nextResolve (node:internal/modules/esm/loader:164:28)
│   at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
│   at ESMLoader.getModuleJob (node:internal/modules/esm/loader:419:18)
│   at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)

**Comment by PMLS3** [comment]
> I am facing the same issue, .app prepare$ nuxi prepare │ Nuxi 3.5.0 │ ERROR Package subpath './utils' is not defined by "exports" in D:\Help\vue\tairo\node_modules.pnpm\listhen@1.3.0\node_modules\consola\p… │ at new NodeError (node:internal/errors:399:5) │ at exportsNotFound (node:internal/modules/esm/resolve:266:10) │ at packageExportsResolve (node:internal/modules/esm/resolve:602:9) │ at packageResolve (node:internal/modules/esm/resolve:777:14) │ at moduleResolve (node:internal/modules/esm/resolve:843:20) │ at defaultResolve (node:internal/modules/esm/resolve:1058:11) │ at nextResolve (node:internal/modules/esm/loader:164:28) │ at ESMLoader.resolve (node:internal/modules/esm/loader:838:30) │ at ESMLoader.getModuleJob (node:internal/modules/esm/loader:419:18) │ at ModuleWrap. (node:internal/modules/esm/module_job:77:40)

Did you manage to fix this?
