### ISSUE TITLE
Nuxt 2 debugging with VSCode or PHPStorm, breakpoints are not working even in basic setup

### ISSUE THREAD

**Issue by cfroe** [nuxt/nuxt#21059]
### Environment

Windows 11
NodeJS v18.16.0

New installation with npx create-nuxt-app selecting Typescript or Javascript as language

### Reproduction

New installation with npx create-nuxt-app selecting Typescript or Javascript as language

Add for example this code to then index.vue page

 ```
export default Vue.extend({
  name: 'IndexPage',

  mounted() {
    console.log("Breakpoint")
  },

})
</script>
```

And add this code to Tutorial.vue

```
    <div v-html="testData" />
  </div>
</template>

<script lang="ts">
export default {
  name: 'NuxtTutorial',

  mounted() {
    console.log("Breakpoint")
  },
  computed: {
    testData():string {
      for (let i = 0; i < 10; i++) {
        console.log(i);
      }
      return "Breakpoint";
    }
  }
}
</script>
```
![grafik](https://github.com/nuxt/nuxt/assets/12471024/0a5ce62d-0c14-487e-b6a0-bba0d6649db3)

![grafik](https://github.com/nuxt/nuxt/assets/12471024/14cd36e0-b91d-4eb9-99d7-3787834d6ed1)

### Describe the bug

When starting a JavaScript Debug Session in PHPStorm (same Problem in VSCode)

![grafik](https://github.com/nuxt/nuxt/assets/12471024/00b411f0-cbbb-4dcb-906b-ea1ee41af4f2)

The breakpoint in index.vue is not hit at all

In Tutorial.vue sometimes the mounted breakpoint is working but the testData breakpoint stopps in the wrong line and is not steppable.

I now also tested with Javascript instead of typescript and the result is that we have less problem but still problems. Both mounted breakpoints are working but the testData breakpoint not, it is stopping not in the breakpointline but in the next line and stepping through the loop is not possible

![grafik](https://github.com/nuxt/nuxt/assets/12471024/f417789a-f13f-4a7b-a1cc-72e62a9b3621)

 

### Additional context

In Nuxt 3 everything is working perfect. But we have a lot of customer projects in Nuxt 2 and cannot move them easily to Nuxt 3. There are also other people having the same problem: 
https://discordapp.com/channels/473401852243869706/1110959994758778950
https://stackoverflow.com/questions/75320195/how-can-i-configure-vscode-debugger-with-nuxt-2-typescript-and-eslint

In earlier versions of Nuxt it was working but I couldn't find out which the last working version it was.

**Comment by TheDutchCoder** [comment]
This is also the case in Nuxt 3.

In the v3 version it's because the sourcemap links to the _built_ version of the file, not the actual source file in the project.
E.g. `/src/index.vue` is actually located in `./_nuxt/index.vue`.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
