### ISSUE TITLE
Changing layout rerenders existing layout components

### ISSUE THREAD

**Issue by Jensxy** [nuxt/nuxt#21062]
### Environment

Nuxi 3.3.3                                                                                                                                                             16:40:34
                                                                                                                                                                       16:40:35
RootDir: C:/Users/d91589/Desktop/Projects/onlylaw/frontend-nuxt                                                                                                        16:40:35
Nuxt project info:                                                                                                                                                     16:40:35

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.3.3`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@9.6.2`
- Builder:          `vite`
- User Config:      `imports`, `typescript`, `modules`, `runtimeConfig`, `experimental`, `vite`, `css`, `i18n`, `pinia`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.10`, `@vueuse/nuxt@9.13.0`, `@pinia/nuxt@0.4.6`, `@nuxtjs/device@3.1.0`
- Build Modules:    `-`
------------------------------

### Reproduction

Problem is clear from description

### Describe the bug

I use 
```
definePageMeta({
  layout: "layoutname",
});
```
 to change the layout for different pages. 

First layout: 
```
<template>
  <div>
    <LayoutHeader></LayoutHeader>
        <slot></slot>
    <LayoutFooter></LayoutFooter>
  </div>
</template>
```

Second layout: 
```
<template>
  <div>
    <LayoutHeader></LayoutHeader>
     <slot></slot>
  </div>
</template>
```

When I change the layout, the header component rerenders. I think components that already exist in a layout should not be rerendered. Is that a bug or expected behavior?

**Comment by danielroe** [comment]
This is expected behaviour in Vue in general. Slots normally re-render when the component around them changes.

**Comment by Jensxy** [comment]
The slot should rerender, but not LayoutHeader, or?
