### ISSUE TITLE
Nested Child Pages - Child attempts to mount too soon

### ISSUE THREAD

**Issue by joel-wenzel** [nuxt/nuxt#21067]
### Environment

[4:28:30 PM] RootDir: C:/code/my-app
[4:28:30 PM] Nuxt project info: 

------------------------------
- Operating System: Windows_NT
- Node Version:     v16.19.1
- Nuxt Version:     3.5.1
- Nitro Version:    2.4.1
- Package Manager:  npm@8.19.3
- Builder:          vite
- User Config:      ssr
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/joel-wenzel/nuxt-sync-child-pages

Steps to reproduce:

- Upon running the app you should be on the `First` page
- Click on `Second` in the header
- Observe the console error saying injection is undefined
- If you refresh the page at this point everything works correctly.

### Describe the bug

When navigating between nested child pages it seems like the destination child tries to mount to the origin parent page during navigation. 

It seems related to #14860 but unfortunately this is still an issue after upgrading to 3.5.1

**Comment by danielroe** [comment]
I think we can track this together with https://github.com/nuxt/nuxt/issues/20798.
