### ISSUE TITLE
renderJsonPayloads causes Cannot stringify arbitrary non-POJOs error

### ISSUE THREAD

**Issue by kstraszewski** [nuxt/nuxt#21060]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v16.14.0
- Nuxt Version:     3.5.0
- Nitro Version:    2.4.0
- Package Manager:  npm@8.19.0
- Builder:          vite
- User Config:      typescript, app, ssr, experimental, routeRules, postcss, css, modules, sitemap, image, unocss, runtimeConfig, vite, build
- Runtime Modules:  nuxt-typed-router@3.2.2, @unocss/nuxt@0.51.13, @nuxt/image-edge@1.0.0-28059208.2abef1b, nuxt-jsonld@2.0.8, @funken-studio/sitemap-nuxt-3@4.0.4, @pinia/nuxt@0.4.11, @nuxt/devtools@0.4.6, @vueuse/nuxt@10.1.2, ()
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-3-h3gq8x?file=composables%2FuseFooStore.ts

### Describe the bug

Same as https://github.com/nuxt/nuxt/issues/20787. When `renderJsonPayloads` is set to `true`, this error occures:
`renderJsonPayloads causes Cannot stringify arbitrary non-POJOs`

**Comment by CernyMatej** [comment]
@danielroe sorry for the ping, but could you please consider expanding upon the documentation for the `definePayloadPlugin`? The current example, in my opinion, isn't very sufficient in explaining it.
I was able to get a class serialization working somehow - but have no idea how and I cannot reproduce it for a second one...

I have a ton of questions like:
- what is the `name` in `definePayloadReducer` and `definePayloadReviver` for? should it be the name of the class?
- will nuxt automatically determine which payload plugin to use?


Let's say I have a method which returns an array of the constructor parameters. Would this be the correct way of registering the payload plugin?
```ts
export default definePayloadPlugin(() => {
    definePayloadReducer('ApiResponse', data => data instanceof ApiResponse && data.getReducedData())
    // @ts-ignore   (bcs data is typed as string for some reason)
    definePayloadReviver('ApiResponse', data => new ApiResponse(...data))
})
```

I know that you showed this in one of your twitch streams, but I wasn't able to find it.
Thank you!

**Comment by danielroe** [comment]
@CernyMatej Let's do that here: https://github.com/nuxt/nuxt/issues/21832

**Comment by danielroe** [comment]
if you comment on the linked issue for adding better docs (https://github.com/nuxt/nuxt/issues/21832) with what you find confusing, I can make sure to address it when I write them.
