### ISSUE TITLE
Wrong Class in v-if

### ISSUE THREAD

**Issue by JulianMar** [nuxt/nuxt#21076]
### Environment

Stackblitz on Mac

### Reproduction

https://stackblitz.com/edit/nuxt-starter-fq9mdd?file=components%2Fcard.vue

### Describe the bug

The Class in v-if is not correctly applied. 
If you check out the reproduction. The Style during loading should be blue but it's red. After the timeout completes, the correct style is shown.  
It seems to take the class from the path evaluated on the server.

**Comment by danielroe** [comment]
`useAsyncData` should always return a value or it will rerun on client.

Here's how your component logic should probably work instead:

```vue
<template>
  <div>
    <div v-if="loaded">
      <div class="slide">
        {{ item }}
      </div>
    </div>
    <div v-else>
      <div class="no-slide">loading: {{ load }}</div>
    </div>
  </div>
</template>

<script setup>
defineProps(['item']);
const load = ref(true);

const loaded = computed(() => load.value);

useAsyncData(async () => {
  load.value = false
  console.log('trigger');
  await new Promise((r) => setTimeout(r, 100));
  load.value = true;
  console.log('trigger done');

  return true
});
</script>
```
