### ISSUE TITLE
`pageTransition` causes `querySelector` get null in `onMounted`

### ISSUE THREAD

**Issue by gyhyfj** [nuxt/nuxt#21117]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.4.2
- Nitro Version:    2.4.0
- Package Manager:  pnpm@8.5.1
- Builder:          vite
- User Config:      modules, vite, css, imports, pinia, sitemap, app, ignore, telemetry, appConfig, devServer, nitro
- Runtime Modules:  @nuxtjs/tailwindcss@6.6.6, @pinia/nuxt@0.4.8, @pinia-plugin-persistedstate/nuxt@1.1.1, @element-plus/nuxt@1.0.4, @nuxtjs/robots@3.0.0, nuxt-simple-sitemap@2.4.11
- Build Modules:    -

### Reproduction

If I set `pageTransition: { name: 'page', mode: 'out-in' },` in `nuxt.config.ts`,
Then toggle pages,  `document.querySelector` get `null` in `onMounted`.
If I put `querySelector` in `onMounted` or remove `pageTransition`, it's OK then

### Describe the bug

`pageTransition` causes `querySelector` get null in `onMounted` when anime is not end

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/13471 - it's an upstream issue
