### ISSUE TITLE
Nitro adapter error when deploying app using Netlify-edge preset

### ISSUE THREAD

**Issue by dosstx** [nuxt/nuxt#21223]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.5.1
- Nitro Version:    2.4.1
- Package Manager:  npm@9.5.1
- Builder:          vite
- User Config:      nitro, runtimeConfig
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-p7shqe

### Describe the bug

When I deploy to Netlify using the `netlify-edge` preset, I get a 404 error when calling the `server/api/chat.post.js` endpoint. It seems that although the endpoint is reachable, there was something wrong with the Nitro server (404 is very vague error it seems). 

**The app works locally with no problems**. It's just that when **deployed to Netlify, the Nitro server for the chat api fails**. 

Checking the Edge Function log on Netlify, I see the following message:

**`[nitro server handler] (e.adapter || ls.adapter) is not a function`**

Anyone know what that means?

Here's my code:

`server/api/chat.post.js`:

```js
import { getChatStream } from '../utils/ai'
export default defineEventHandler(async (event) => {
  try {
    const { messages } = await readBody(event)
    const stream = await getChatStream({ messages })
    return stream
  } catch (error) {
    console.error('error on server', error)
  }

})
```

`/utils/ai`:

```
import { Configuration, OpenAIApi } from 'openai'

const config = useRuntimeConfig()

const configuration = new Configuration({
    apiKey: process.env.OPENAI_API_KEY || config.OPENAI_API_KEY
})
const openai = new OpenAIApi(configuration)

const systemPrompts = [..removed..]


export const getChatStream = async ({ messages }) => {
    try {
        const response = await openai.createChatCompletion(
            {
                model: 'gpt-3.5-turbo',
                messages: [
                    ...systemPrompts, ...messages
                ],
                temperature: 0.5,
                stream: true // Not supported in OpenAI Node SDK yet
            },
            {
                timeout: 15000,
                responseType: "stream" // see above
            }
        );

        return response.data;
    } catch (error) {
        if (error.response) {
            console.log(error.response.status);
            console.log(error.response.data);
        } else {
            console.log(error.message);
        }
    }

};
```

### Additional context

App works when deployed using `Netlify` preset, but not `netlify-edge` preset.

### Logs

```shell-script
From Netlify Edge Function log:

[nitro server handler] (e.adapter || ls.adapter) is not a function
```

**Comment by dosstx** [comment]
Chance this has something to do with using axios in Nitro with edge functions? I think the OPEN AI Node sdk I am using has axios under the hood. Just a thought.

**Comment by Hebilicious** [comment]
Are you able to run you code without Nuxt on netlify-edge ? 
Netlify edge functions uses deno-deploy under the hood, so it might be the reason why openai isn't working there.

**Comment by dosstx** [comment]
> @dosstx Are you able to run you code without Nuxt on netlify-edge ? 
> 
> Netlify edge functions uses deno-deploy under the hood, so it might be the reason why openai isn't working there.

Yes, able to get it on plain Netlify. I was wanting to get the code on edge so I could get data streaming to work (like chatGPt).

**Comment by Hebilicious** [comment]
Just to be clear, I don't mean the netlify preset, I mean, can you run your code in a netlify *edge* function directly following their [docs](https://docs.netlify.com/edge-functions/get-started/), without nuxt or nitro ? Just your openAI logic.

**Comment by Hebilicious** [comment]
> I am having a similar issue with Vercel. I can deploy and get a non streaming response from a serverless function, but I've been unable to get streaming to work on the deploy.

Looks like openAI with the stream: true sends the data as [SSE](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#event_stream_format). You should be able to use h3 `sendStream` on node based runtime. For the edge though, this won't work. But [I'm working on it](https://github.com/unjs/h3/pull/395)

**Comment by Hebilicious** [comment]
@dosstx You can play around with the PR, but you might need to tweak Nitro a little too. The runtime/entries for your provider might not forward the stream properly, you will need to look at your provider specifically.
 https://github.com/unjs/h3/pull/395

**Comment by Hebilicious** [comment]
> I'm just not having any luck with streaming in Nuxt and Netlify. I appreciate your PR and I'll wait until it's officially merged. Thank you!

If I'm not mistaken, netlify edge uses the deno-deploy runtime, so this workaround *might* work for you :

```ts
export default async function (request: Request, _context) {
  const url = new URL(request.url);

  if (isPublicAssetURL(url.pathname)) {
    return;
  }

  if (!request.headers.has("x-forwarded-proto") && url.protocol === "https:") {
    request.headers.set("x-forwarded-proto", "https");
  }

  let body;
  if (request.body) {
    body = await request.arrayBuffer();
  }

  const r = await nitroApp.localCall({
    url: url.pathname + url.search,
    host: url.hostname,
    protocol: url.protocol,
    // @ts-ignore TODO
    headers: request.headers,
    method: request.method,
    redirect: request.redirect,
    body,
  });

  return new Response(r.body, {
    headers: r.headers as HeadersInit,
    status: r.status,
    statusText: r.statusText,
  });
}
```

If you look at the netlify-edge preset for Nitro, you'll see that you are able to return a Response object from your event handler. Now it might be possible for you to do something like this 

```ts
export async function respondWithResponse(event: H3Event, response: Response) {
  for (const [key, value] of response.headers) event.node.res.setHeader(key, value)
  if (response.body) {
    const contentType = response.headers.get("Content-Type") || ""
    if (contentType.includes("text") || contentType.includes("json")) {
      for await (const chunk of response.body as unknown as AsyncIterable<Uint8Array>) event.node.res.write(new TextDecoder().decode(chunk))
    }
    else for await (const chunk of response.body as unknown as AsyncIterable<Uint8Array>) event.node.res.write(chunk)
  }
  return event.node.res.end()
}


const response = await openai.createChatCompletion(
    {
		//...
    },
    {
        timeout: 15000,
        responseType: "stream" 
    }
);
        
return respondWithResponse(event, response)
```

This should work if `createChatCompletion` returns a Response with a body that handles streams.
Note that if your streaming something like this, it will time-out relatively quickly, which might not be ideal for all use cases. You might have more luck with a platform like cloudflare workers that have a hardware timeout, or good old node/deno on a container/vps etc

**Comment by danielroe** [comment]
If you're still experiencing this, would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏

If it only recurs with Nuxt, let me know and I'll reopen it here.

**Comment by s1mpLyy** [comment]
I'm facing this right now


AWS Lambda preset: “defineEventHandler is not defined” error

When deploying my NuxtJS project (with SSR enabled) using Nitro’s AWS Lambda preset, I get an “Internal server error” on the site. CloudWatch logs show:

`
"errorType": "ReferenceError",
"errorMessage": "defineEventHandler is not defined",
`

This issue does not occur when deploying on Cloudflare.

Any help would be appreciated!

**Comment by pi0** [comment]
@s1mpLyy please consider reporting in a new issue with minimal reproduction 🙏🏼
