### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by natl-set** [nuxt/nuxt#21244]
### Environment

nuxt 2.16

### Reproduction

Simply run nuxt app and run a load test on it. We observe increasing memory consumption

### Describe the bug

There seems to be large memory consumption here.

<img width="1158" alt="image" src="https://github.com/nuxt/nuxt/assets/133934820/b6708db2-799d-4e39-8e60-67a68937b3af">

<img width="1161" alt="image" src="https://github.com/nuxt/nuxt/assets/133934820/c8918af4-ccd6-4fef-9afe-3c49fc4b0d1a">

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/20621.

**Comment by natl-set** [comment]
@danielroe  Seems like it is a different problem. This one seems to be related to watchSyncEffect generated by vue-composition

**Comment by danielroe** [comment]
In that case, would you provide a reproduction? 🙏

**Comment by natl-set** [comment]
That's very difficult part. We are trying to find exactly what caused the memory to leak in the first place.

**Comment by danielroe** [comment]
I understand. I generally prefer avoiding creating an issue until that point because memory leaks can come from many places, including user code, and are difficult to debug even with a reproduction.

**Comment by thePercept** [comment]
> That's very difficult part. We are trying to find exactly what caused the memory to leak in the first place.

Even I tried to find what was causing it . But couldn't find.
