### ISSUE TITLE
static nitro builds when running `nuxi generate`

### ISSUE THREAD

**Issue by danielroe** [nuxt/nuxt#21254]
Now that we have support for nitro 'static' builds it would be nice to enable this behaviour automatically when running `nuxi generate`.

```[tasklist]
### Tasks
- [x] detect `netlify-static` and `vercel-static` environments automatically (upstream bug in nitro)
- [ ] normalise behaviour between `build` and `generate` when using a static preset (prerender configuration, crawler, etc.)
```

Linked issues:
* https://github.com/nuxt/image/issues/638
* https://github.com/nuxt/nuxt/issues/21232

**Comment by Hebilicious** [comment]
@danielroe I remember mentioning somewhere that we could get rid of the `nuxt generate` command (or make it strictly an alias of `nuxt build --generate`). It's confusing that these 2 behave differently. What do you think ? I can open an issue if that helps.

Also there's a CFP static preset, should this task apply for it too ?  https://github.com/unjs/nitro/pull/1310

**Comment by Lehoczky** [comment]
> @danielroe I remember mentioning somewhere that we could get rid of the `nuxt generate` command (or make it strictly an alias of `nuxt build --generate`). It's confusing that these 2 behave differently. What do you think ? I can open an issue if that helps.
> 
> Also there's a CFP static preset, should this task apply for it too ? [unjs/nitro#1310](https://github.com/unjs/nitro/pull/1310)

I would also support having only one build command

**Comment by Hebilicious** [comment]
> > @danielroe I remember mentioning somewhere that we could get rid of the `nuxt generate` command (or make it strictly an alias of `nuxt build --generate`). It's confusing that these 2 behave differently. What do you think ? I can open an issue if that helps.
> > Also there's a CFP static preset, should this task apply for it too ? [unjs/nitro#1310](https://github.com/unjs/nitro/pull/1310)
> 
> I would also support having only one build command

`generate` is now an alias of `build --prerender` https://github.com/nuxt/nuxt/pull/21860
This should be documented when https://github.com/nuxt/nuxt/issues/21594 is resolved

**Comment by Lehoczky** [comment]
Yeah I know, but it feels a bit confusing to have two different commands for building an app, and people will generally only use one of them in a project, right? If a team builds a static site, they will only use the `generate` command, if they build an SSR app, they will only use the `build` command.

Having only `build` would simplify things, especially if it automatically knows the rendering strategy based on the specified `nitro` config.

**Comment by danielroe** [comment]
This is now the case with the linked PR above. Setting `nitro.static` to true in your config should make `nuxi build` behave exactly like `nuxi generate`.

**Comment by Hebilicious** [comment]
> Yeah I know, but it feels a bit confusing to have two different commands for building an app, and people will generally only use one of them in a project, right? If a team builds a static site, they will only use the `generate` command, if they build an SSR app, they will only use the `build` command.
> 
> Having only `build` would simplify things, especially if it automatically knows the rendering strategy based on the specified `nitro` config.

I think you can open an issue if you want `nuxi generate` to be deprecated. But imo it's fine if there's an alias, as long as we document it and we consistently use `nuxi build --prererender` everywhere in the docs.
