### ISSUE TITLE
Nuxt forces inline application of styles, conflicts with CSP

### ISSUE THREAD

**Issue by GalacticHypernova** [nuxt/nuxt#21268]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.5.2
- Nitro Version:    2.4.1
- Package Manager:  npm@9.6.5
- Builder:          vite
- User Config:      modules, app, i18n
- Runtime Modules:  @nuxtjs/tailwindcss@6.7.0, @nuxtjs/i18n@8.0.0-beta.12
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-ogevja

You will see that the style breaks and the error is prompted, rendering the entire page broken.

### Describe the bug
This error revolves around vite's core functionality when dealing with styles, using __vite__updateStyle to force apply styles as inline styles (at least as it seems from the error logs), regardless of how it is handled in the actual application. This, combined with the lack of `unsafe-inline` in `style-src` (or `default-src`), causes the CSP to trigger and the style to not load, resulting in the entire application being broken, essentially getting rid of the CSP's functionality (due to the only option of it working being with `unsafe-inline`).

### Additional context

It would be nice if vite's behavior could be changed to at the very least respect and treat styles in files accordingly and not default to stringifying them, but a more appropriate solution to entirely mitigate this CSP conflict would be to just not apply it inline on vite's part. However, if none of these options are reasonable, style elements outside of the template should have a nuxt-internal nonce/hash to allow them through the CSP.

![image](https://github.com/nuxt/nuxt/assets/92037085/475dd48a-d253-431c-9cf5-7c002b384127)
When clicking on the problematic line it brings up the `__vite__updateStyle(__vite__id, __vite__css)` line (line 4)
### Logs

```shell-script
Too many to paste here, going to the reproduction will spam the console with logs
```

**Comment by dargmuesli** [comment]
@danielroe would you say that, given my comment above, this issue can be closed as there is a "workaround available" in favor of issue https://github.com/nuxt/nuxt/issues/11793?

**Comment by danielroe** [comment]
Yes, let's track it there 🙏
