### ISSUE TITLE
client-side plugin of qrcode-vue3 breaks HMR

### ISSUE THREAD

**Issue by acidjazz** [nuxt/nuxt#21273]
### Environment

RootDir: /Users/k/vc/qrcode-hmr                                                                         10:47:49 PM
Nuxt project info: (copied to clipboard)                                                                10:47:49 PM

------------------------------
- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.5.2
- Nitro Version:    2.4.1
- Package Manager:  pnpm@8.6.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                             10:47:49 PM

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Reproduction

https://github.com/acidjazz/qrcode-hmr

### Describe the bug

with the plugin running HMR breaks
turn the plugin off and HMR works fine

### Additional context

I'm not sure if this is a bug in nuxt3 or qrcode-vue3 but thought i'd start here!

### Logs

```shell-script
no issues, no errors, just broken HMR
```

**Comment by acidjazz** [comment]
@NozomuIkuta try this:

```bash
git clone git@github.com:acidjazz/qrcode-hmr.git
cd qrcode-hmr
pnpm i; pnpm run dev
```

visit http://localhost:3000

open up app.vue in your IDE of choice,
change "this is a test" to anything and save the file, you will not see it update in your browser

**Comment by bf** [comment]
@acidjazz maybe a workaround is to use a different SVG library. I tried many Vue QR components and most of them play badly with SSR.

Working example from my project:
```
<template>
            <img :src="toSvgDataURL(generate(TOTPSetupURL))" class="qr"/>
</template>

<script>
import { generate } from 'lean-qr'
import { toSvgDataURL} from 'lean-qr/extras/svg'
</script>
```

**Comment by manniL** [comment]
Same issue [with Vue and Vite](https://stackblitz.com/edit/nuxt-issues-21273?file=src%2FApp.vue&terminal=dev). So probably an issue of the lib itself 🤔

Better to report it there then 😋

Closing here 👍🏻

**Comment by acidjazz** [comment]
> Same issue [with Vue and Vite](https://stackblitz.com/edit/nuxt-issues-21273?file=src%2FApp.vue&terminal=dev). So probably an issue of the lib itself 🤔
> 
> Better to report it there then 😋
> 
> Closing here 👍🏻

Is there an issue open anywhere to follow instead?

**Comment by manniL** [comment]
@acidjazz I don't think so yet. Best would be to report it in https://github.com/scholtz/qrcode-vue3/ 👍🏻

**Comment by acidjazz** [comment]
> https://github.com/scholtz/qrcode-vue3/

thanks, someone beat me to it https://github.com/scholtz/qrcode-vue3/issues/42

**Comment by acidjazz** [comment]
duplicated:

### Environment

RootDir: /Users/k/vc/qrcode-hmr                                                                         10:47:49 PM
Nuxt project info: (copied to clipboard)                                                                10:47:49 PM

------------------------------
- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.5.2
- Nitro Version:    2.4.1
- Package Manager:  pnpm@8.6.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                             10:47:49 PM

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com


### Reproduction

https://github.com/acidjazz/qrcode-hmr

### Describe the bug

with the plugin running HMR breaks
turn the plugin off and HMR works fine

### Additional context

I'm not sure if this is a bug in nuxt3 or qrcode-vue3 but thought i'd start here!

### Logs

```shell-script
no issues, no errors, just broken HMR
```
