### ISSUE TITLE
An error occurs when while asynchronously using `useRuntimeConfig()` within `useAsyncData()`

### ISSUE THREAD

**Issue by Mini-ghost** [nuxt/nuxt#21270]
### Environment

Reproduction environment is:

------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.5.2
- Nitro Version:    2.4.1
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-rklf6m?file=app.vue

### Describe the bug

When we asynchronously use `useRuntimeConfig()` within `useAsyncData()`, it causes an error, but there is no error when it is used synchronously.

Here is a successful example:

```ts
const { data, error } = await useAsyncData('TEST', () => {
  useRuntimeConfig();
  useRuntimeConfig();

  return 'success';
});
```

And here is an example where an error occurs:

```ts
function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

const { data, error } = await useAsyncData('TEST', async () => {
  useRuntimeConfig();
  await sleep(100);
  useRuntimeConfig();

  return 'success';
});
```

### Logs

```shell-script
Error: [nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at `https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables`.
```

**Comment by danielroe** [comment]
See https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables.

You should call useRuntimeConfig outside of useAsyncData.

**Comment by Mini-ghost** [comment]
However, there is an issue here:

https://github.com/nuxt/content/blob/main/src/runtime/components/ContentQuery.vue#LL111C4-L111C4
https://github.com/nuxt/content/blob/586d6be80caec2e5739d7633e7d11e152b397d90/src/runtime/composables/query.ts#L60

According to the design of `<ContentQuery>` in Nuxt Content, `queryContent()` is used within `useAsyncData()`, and `queryContent()` itself uses `useRuntimeConfig()` internally.

Today, I have a requirement to customize the requests, where I need to use multiple `queryContent()` within `useAsyncData()` and the requests depend on each other, so the subsequent requests need to wait for the completion of the previous ones. In this case, it will result in an error similar to the reproduction mentioned above.

**Comment by danielroe** [comment]
In that case you can use nuxtApp.runWithContext within useAsyncData. We can also look at transforming useAsyncData as we do with other functions, now that https://github.com/unjs/unctx/pull/77 has been merged.

**Comment by Mini-ghost** [comment]
This works, will `nuxtApp.runWithContext` be written to the file later? It doesn't seem to be seen now.

**Comment by danielroe** [comment]
Yes, we need to update the docs for this.
