### ISSUE TITLE
no data collected

### ISSUE THREAD

**Issue by breizhwave** [nuxt/nuxt#21276]
### Environment

{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "nuxt": "^3.2.3",
    "primeflex": "3.2.1",
    "primeicons": "5.0.0",
    "primevue": "^3.25.0"
  },
  "dependencies": {
    "@pinia/nuxt": "^0.4.4",
    "bootstrap": "^5.2.3",
    "mixpanel-browser": "^2.47.0",
    "nuxt-gtag": "^0.5.7",
    "sass": "^1.56.1"
  }
}

### Reproduction

used pnpm and yarn do to add nuxt-gtag, front renders the gtag configuration, but does not add page view script 

window.__NUXT__={serverRendered:false,config:{public:{gtag:{id:"G-QxxxxxxxY",config:{},initialConsent:true,loadingStrategy:"defer"}}

### Describe the bug

not collecting data at all (similar to https://github.com/johannschopplich/nuxt-gtag/issues/11, except won't collect on other pages)

**Comment by danielroe** [comment]
This doesn't sound like an issue with Nuxt. Would you raise the issue on that module's repository instead? 🙏
