### ISSUE TITLE
useFetch/createError causing [Vue warn] on error in SSR/production

### ISSUE THREAD

**Issue by AndersNielsen85** [nuxt/nuxt#21274]
### Environment

- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.5.2
- Nitro Version:    2.4.1
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-7wxsag?file=pages%2F%5B...slug%5D.vue

### Describe the bug

When using "throw createError" on a failed useFetch an error it causes a Vue warn on the server.
It only happens after build/preview, _not_ in dev mode, and only on the initial SSR request.

To reproduce
- build
- preview
- goto/refresh https://nuxtstarter7wxsag-fxhj--3000--272d3407.local-credentialless.webcontainer.io/404notfound
- "[Vue warn]: Component <Anonymous> is missing template or render function." shows up in the output of the running server.

### Logs

```shell-script
node .output/server/index.mjs
Listening http://[::]:3000
[Vue warn]: Component <Anonymous> is missing template or render function.
```

**Comment by agracia-foticos** [comment]
Same issue!!!

**Comment by AndersNielsen85** [comment]
Seems the error can be muted by faking a template by adding this to the slug file
```
<script lang="ts">
  export default {
    name: 'Slug',
    template: '<div></div>'
  }
</script>

**Comment by JulienVanelian** [comment]
I'm experiencing the same warning on our project in production. I have the warning even without doing any fetch, **doing a createError in a script setup on server side, without an error.vue at the root, will still trigger the warning**.
I can confirm @AndersNielsen85's solution fixes the issue, but it feels unfortunately hacky.

**Comment by husayt** [comment]
@danielroe i had the similar issue where I couldn't get serversidecomponents working. Apparently, in contrast to client components serverside components have to be decalred exactly as they are named. 

With client component declared in "Stats.vue" i can use it vie `<stats>`.

**Comment by PdxLook** [comment]
I have the same problem. Have you solved it

**Comment by danielroe** [comment]
This should now be resolved with latest Vue version. (Previously we were bundling vue dev version in production.)
