### ISSUE TITLE
only null Type is allowed to useAsyncData's default Type

### ISSUE THREAD

**Issue by qoo1476** [nuxt/nuxt#21277]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v16.14.2
- Nuxt Version:     3.5.2
- Nitro Version:    2.4.1
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      telemetry, ssr, experimental, app, modules, css, imports, build, nitro
- Runtime Modules:  @vueuse/nuxt@10.1.2, @unocss/nuxt@0.52.5, @pinia/nuxt@0.4.11
- Build Modules:    -
------------------------------

### Reproduction

i tried to reproduction but it doesn't show typescript error

### Describe the bug

sorry my english is bad...

when i use useAsyncData with default data

```
type User = {
  name: string
  auth: string
}

const { data, pending, refresh } = useAsyncData<User>(
  () => $fetch('/users/1'),
  {
    default: () => ({
      name: '',
      auth: '',
    }),
  },
)
```

it shows typescript error 

so i checked useAsyncData's Type
```
export declare function useAsyncData<ResT, DataE = Error, DataT = ResT, PickKeys extends KeysOf<DataT> = KeysOf<DataT>, DefaultT = null>(handler: (ctx?: NuxtApp) => Promise<ResT>, options?: AsyncDataOptions<ResT, DataT, PickKeys, DefaultT>): AsyncData<PickFrom<DataT, PickKeys> | DefaultT, DataE | null>;
```

there are two ways i found
1. don't use default option or (awalys return null value [X]mean nothing)
```
const { data, pending, refresh } = useAsyncData<User>(
  () => $fetch('/users/1'),
  {
    default: () => null
  },
)
```
2.  generate default Type
```
const { data, pending, refresh } = useAsyncData<
  User,
  Error,
  User,
  KeysOf<User>,
  User <= [ here is default option's type ]
>(() => $fetch('/users/1'), {
  default: () => ({
    name: '',
    auth: '',
  }),
})
```

so i wonder it's any reason to default option's default type is null ?
i think it could be better with
```
DefaultT = null    =>   DefaultT = DataT [or] DefaultT = null|DataT
```
or i awalys have to generate default type when use useAsyncData

and i also checked nuxt.com api document and it looks like what i said

![image](https://github.com/nuxt/nuxt/assets/68536972/f2ecacda-e9dc-43a5-a073-344ca066ed0c)

sorry if i was wrong and thank you for the amazing job!

**Comment by danielroe** [comment]
I'm not 100% sure what you mean. Is the issue that when you provide a default value, the type of `data` is `Ref<Value>` rather than `Ref<Value | null>`?

**Comment by aaharu** [comment]
I think that you probably will avoid typescript errors in this way.
```ts
  const { data, pending, refresh } = useAsyncData(() => $fetch<User>('/users/1'), {
    default: (): User => ({
      name: '',
      auth: '',
    }),
  })
```

**Comment by qoo1476** [comment]
@danielroe sorry if my sentences confusing you. English is so hard to me😢
i mean Ref<Value> or Ref<Value | null> both is all ok. but when i checked useAsyncData type. it's not Ref<Value | null> but just null (for default)
![image](https://github.com/nuxt/nuxt/assets/68536972/a62b74e3-651a-4b87-ab0c-711c4da3337e)

@aaharu thank you for your answer but it still does not work

maybe something wrong in my develope environment?

i'm work with visual studio code with volar

**Comment by Applelo** [comment]
It seems like I have the same problem:

![image](https://github.com/nuxt/nuxt/assets/7613286/ca9cf9ee-f0b3-42f8-84a5-ab139e1368b5)
with 
```ts
await useAsyncData<Taxon[]>('brands', () =>
    $fetchApi('/api/v2/shop/taxons'), 
    {
       default: () => [],
    }
)
```

I have tried to pass `Taxon[]` (`Taxon` is an interface) like @aaharu mentionned but it didn't work :/ It appears when I have upgrade my version of Nuxt to 3.3 to 3.5 (maybe a typing change in useAsyncData).

**Comment by danielroe** [comment]
Would you provide a code reproduction? 🙏

**Comment by aaharu** [comment]
@Applelo 
The method I have shown is to specify no type argument for `useAsyncData`.
Would this still result in an error?
```ts
await useAsyncData('brands', () =>
    $fetchApi('/api/v2/shop/taxons') as Promise<Taxon[]>, 
    {
       default: (): Taxon[] => [],
    }
)
```

**Comment by Applelo** [comment]
@aaharu Ok so I have move the `<Taxon[]>` inside the useAsyncData to my $fetchApi (a ofetch object) and now it works fine with this code.

```ts
useAsyncData('brands', () =>
    $fetchApi<Taxon[]>('/api/v2/shop/taxons'), 
    {
    default: () => [],
  })
```

I don't know if it's relevant to do a reproduction ? Should my previous code work with typing pass in `useAsyncData` like this ?

```ts
useAsyncData<Taxon[]>()
```

If so, I can make a reproduction.

**Comment by qoo1476** [comment]
@aaharu 

it's still not solved to me.... so can i ask a one?

tell me if i was wrong.

this is from https://github.com/nuxt/nuxt/pull/20968

in asyncData type

https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/app/composables/asyncData.ts

```
export interface AsyncDataOptions<
  ResT,
  DataT = ResT,
  PickKeys extends KeysOf<DataT> = KeysOf<DataT>,
  DefaultT = null, // this Line, DefaultT's initial type is null
> {
  server?: boolean
  lazy?: boolean
  default?: () => DefaultT | Ref<DefaultT> // and default parameter return type is DefaultT(and it's null initially)
  transform?: _Transform<ResT, DataT>
  pick?: PickKeys
  watch?: MultiWatchSources
  immediate?: boolean
}
```
i see all DefaultT's initial type is null

and DefaultT is used default parameter's return type

so all these DefaultT's initial type sholdn't be follow Data's type?
like bottom code
```
export interface AsyncDataOptions<
  ResT,
  DataT = ResT,
  PickKeys extends KeysOf<DataT> = KeysOf<DataT>,
  // DefaultT = null,
  DefaultT = DataT (or ResT?)
> {
  server?: boolean
  lazy?: boolean
  default?: () => DefaultT | Ref<DefaultT>
  transform?: _Transform<ResT, DataT>
  pick?: PickKeys
  watch?: MultiWatchSources
  immediate?: boolean
}
```

please check this one if you have any times. thanks
