### ISSUE TITLE
getCookie return undefined only on ssr

### ISSUE THREAD

**Issue by mrc-bsllt** [nuxt/nuxt#21282]
### Environment

- Operating System: Darwin
- Node Version:     v16.18.1
- Nuxt Version:     3.5.1
- Nitro Version:    2.4.1
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      runtimeConfig, devServer, vite, typescript, css, modules, tailwindcss
- Runtime Modules:  @nuxtjs/tailwindcss@6.7.0, @pinia/nuxt@0.4.11, @nuxt/image-edge@1.0.0-28059208.2abef1b
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-ugzbfq

### Describe the bug

I premise that I don't know if it makes more sense to put this issue here, or on h3. I am trying to read a cookie in a nuxt server api. As written in the documentation, I am using the getCookie() fuction to which I pass event and the name of the cookie, but when I resfresh the page it always returns undefined. On the client side, everything works correctly.
This is the code of my server api:
```javascript
import validator from "validator"

export default defineEventHandler(event => {
  const authorization = getHeader(event, "Authorization")
  const token = authorization?.split(" ")[1] || ""
  const isValid = validator.isUUID(token)
  const validToken = getCookie(event, "validToken")
  const validTokenExistAndIsNotEqualToToken = validToken && validToken !== token

  console.log("validToken", validToken) // undefined on server side

  if (!token || !isValid || validTokenExistAndIsNotEqualToToken) {
    throw createError({
      statusCode: 401,
      statusMessage: "Unauthorized"
    })
  }

  if (!validToken) {
    throw createError({
      statusCode: 403,
      statusMessage: "Forbidden"
    })
  }

  return {
    stringMessage: "This is a secret message from the server"
  }
})
```

![Screenshot 2023-05-31 alle 11 52 37](https://github.com/nuxt/nuxt/assets/72490444/5bf5c384-69a0-4631-908c-d171a1b4731e)

**Comment by danielroe** [comment]
It works fine for me. Are you sure the cookie is being sent to the server? 

Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by mrc-bsllt** [comment]
> ### Environment
> * Operating System: Darwin
> * Node Version:     v16.18.1
> * Nuxt Version:     3.5.1
> * Nitro Version:    2.4.1
> * Package Manager:  yarn@1.22.19
> * Builder:          vite
> * User Config:      runtimeConfig, devServer, vite, typescript, css, modules, tailwindcss
> * Runtime Modules:  @nuxtjs/tailwindcss@6.7.0, @pinia/nuxt@0.4.11, @nuxt/[image-edge@1.0.0-28059208.2abef1b](mailto:image-edge@1.0.0-28059208.2abef1b)
> * Build Modules:    -
> 
> ### Reproduction
> ...
> 
> ### Describe the bug
> I am trying to read a cookie in a nuxt server api. As written in the documentation, I am using the getCookie() fuction to which I pass event and the name of the cookie, but when I resfresh the page it always returns undefined. On the client side, everything works correctly. This is the code of my server api:
> 
> ```js
> import validator from "validator"
> 
> export default defineEventHandler(event => {
>   const authorization = getHeader(event, "Authorization")
>   const token = authorization?.split(" ")[1] || ""
>   const isValid = validator.isUUID(token)
>   const validToken = getCookie(event, "validToken")
>   const validTokenExistAndIsNotEqualToToken = validToken && validToken !== token
> 
>   console.log("validToken", validToken) // undefined on server side
> 
>   if (!token || !isValid || validTokenExistAndIsNotEqualToToken) {
>     throw createError({
>       statusCode: 401,
>       statusMessage: "Unauthorized"
>     })
>   }
> 
>   if (!validToken) {
>     throw createError({
>       statusCode: 403,
>       statusMessage: "Forbidden"
>     })
>   }
> 
>   return {
>     stringMessage: "This is a secret message from the server"
>   }
> })
> ```
> 
> ![Screenshot 2023-05-31 alle 11 52 37](https://user-images.githubusercontent.com/72490444/242237260-5bf5c384-69a0-4631-908c-d171a1b4731e.png)
> 
> ### Additional context
> _No response_
> 
> ### Logs
> _No response_



> It works fine for me. Are you sure the cookie is being sent to the server?
> 
> Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

I've attached a reproduction on stackblitz! But I'm not sure it's faithful because I noticed that it doesn't save my cookies.

**Comment by danielroe** [comment]
Unfortunately stackblitz doesn't work with cookies correctly, but I can download and test locally - thanks!

**Comment by mrc-bsllt** [comment]
> Seems to be working fine for me.
> 
> ![CleanShot 2023-05-31 at 12.18.48.png](https://camo.githubusercontent.com/e43421ef3085a6b1830df12febdd3f3df4e02675fba3ae0e216c47ea9c4ac28f/68747470733a2f2f766f6c74612e73332e66722d7061722e7363772e636c6f75642f436c65616e5f53686f745f323032335f30355f33315f61745f31325f31385f34385f303636633134643330322e706e67)
> 
> Can you check the headers in your network panel?
> 
> ![CleanShot 2023-05-31 at 12.20.30.png](https://camo.githubusercontent.com/2b8398328ba0609140b9fb69dec938d922188a31c84dc3056640522d80594e26/68747470733a2f2f766f6c74612e73332e66722d7061722e7363772e636c6f75642f436c65616e5f53686f745f323032335f30355f33315f61745f31325f32305f33305f633730386637313134312e706e67)

How can i check a network request in chrome on server side?

**Comment by danielroe** [comment]
Check the request _to_ your server API from your browser. That's where the cookie is being passed.

**Comment by danielroe** [comment]
Ahh, I see. In that case, rather than using `$fetch`, you can use `useRequestFetch()` which will automatically proxy cookies to the endpoint. (Internally, that's what `useFetch` does.)

**Comment by mrc-bsllt** [comment]
I solved the problem by usingFetch instead of useAsyncData
