### ISSUE TITLE
Build errors hidden unless build.quiet enabled

### ISSUE THREAD

**Issue by rchl** [nuxt/nuxt#21284]
### Environment

```
  System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M1
    Memory: 228.05 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.90
    Firefox: 113.0.2
    Safari: 16.5
    Safari Technology Preview: 16.4
  npmPackages:
    @nuxt/types: ^2.16.3 => 2.16.3
    nuxt: ^2.16.3 => 2.16.3
```

### Reproduction

Don't have any public repro at the moment.

### Describe the bug

I have an error triggering during the build but Nuxt doesn't show the actual error and only shows not-very-englightning stack trace.

On setting `build.quiet = true` in nuxt config it shows the actual error.

With `build.quiet`:

```
FATAL  Nuxt build error

ERROR in Sentry CLI Plugin: Command failed: node_modules/@sentry/cli/sentry-cli releases new xxxx-xxx@1.14.12
error: project not found

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
```

Without `build.quiet`:

```
FATAL  Nuxt build error

at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack/dist/webpack.js:1861:21)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:1826:5)
at async Builder.build (node_modules/@nuxt/builder/dist/builder.js:249:5)
at async Object.run (node_modules/@nuxt/cli/dist/cli-build.js:99:7)
at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:356:7)
```

### Additional context

It seems like the relevant code is https://github.com/nuxt/nuxt/blob/5ab8ea9ded8e57d9e1becc2731053b245f7c645f/packages/webpack/src/builder.js#L151-L158 which indeed only exposes webpack error when `build.quiet` is set.

**Comment by rchl** [comment]
The quoted code comment says `non-quiet mode: errors will be printed by webpack itself` but it's not the case in this case at least.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️
