### ISSUE TITLE
Layout is getting "stuck" when switching between routes in middleware (with SSR on)

### ISSUE THREAD

**Issue by rezelute** [nuxt/nuxt#21294]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v16.19.0  
- Nuxt Version:     3.5.2     
- Nitro Version:    2.4.1     
- Package Manager:  npm@8.5.4 
- Builder:          vite
- User Config:      ssr
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/SilviaZeta/nuxt-app

### Describe the bug

There are a few questions for further understanding + one issue that we are trying to solve.
**The issue:**
We have a simple redirect in the `example.global.ts` middleware which goes from "/" to "/about".
The index page is using the 'default' layout (has a blue background) and the about page is using the 'about' layout (has a red background).

When the redirect happens, the blue background persists meaning that its applying the wrong layout to the redirected page. Why is this happening? When we switch SSR to false, the problem goes away.

**Questions:**
1. We only want to run the project by building it and hosting it on an S3 bucket, some routes will be pre-rendered and others will not but we only want to do the pre-rendering at build.  Does the below config look correct?
```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
   ssr: true,
   // Is this considered hybrid rendering? Are we allowed to do this if we only want to use SSG mode? 
   routeRules: {
      // Logged out pages pre-rendered at build time
      "/": { prerender: true },
       "/terms": { prerender: true },
      "/privacy": { prerender: true },
      "/account": { ssr: false },
      "/home": { ssr: false },
   },
...
```
2. If we do want to run in SSG mode only, should we always do this in the middleware?

```
if (process.server) {
     return;
} 
```
3. Why does a server run by default in Dev if we only want to build the project and deploy? We are getting confused about why we have to specify `SSR: true` when we will never have a server running in an S3 bucket.

**Comment by rezelute** [comment]
This was my first post, can no one help with this at all?

**Comment by Krutie** [comment]
@rezelute I have made slight changes to the `about.vue` page as below and it works as expected.

```html
<!-- // pages/about.vue -->

<template>
  <div>
    <!-- use `NuxtLayout` component with `name` props to tell Nuxt to use this new layout instead of the default one -->
    <NuxtLayout name="about"> 
      <h1>About page</h1>
    </NuxtLayout>
  </div>
</template>

<script setup>
definePageMeta({
  layout: false, // this is how we tell Nuxt to disable default layout - the one with blue background in this instance
});
</script>
```

Rest of the code is same as provided in your Github repo. 
Here's a working repro of this behaviour: https://stackblitz.com/edit/nuxt-starter-zebtpy?file=pages%2Fabout.vue

**Comment by danielroe** [comment]
The issue here is that you are redirecting on client-side _only_. So you have a rendered page for `/` and then on client-side you redirect before hydration and try to hydrate a page which is `/about` instead. This causes a hydration error.

I'm not really sure on the reason you're not redirecting on the server, but if you want to do this, you might consider not rendering the page on the server at all, or using an app shell pattern.
