### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'extend')

### ISSUE THREAD

**Issue by tejassyndell** [nuxt/nuxt#21300]
### Environment

.

### Reproduction

.

### Describe the bug

I'm upgrading my Vue version from 2 to 3, and I encountered an error during the upgrade process.https://prnt.sc/Unuv-eRIVc1T

**Comment by danielroe** [comment]
It sounds like you have a dependency that needs Vue 2. `Vue.extend` is no longer a function in Vue 3.
