### ISSUE TITLE
In CSR app, `navigateTo` (with `external:true`) redirection from route middleware triggers page script setup

### ISSUE THREAD

**Issue by nicolaspayot** [nuxt/nuxt#21314]
### Environment

Nuxi 3.5.2
------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.5.2
- Nitro Version:    2.4.1
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      ssr
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

From https://stackblitz.com/edit/nuxt-starter-77e2za?file=README.md, click on `Go to foo` link on home page.

You can see `Hello, foo!` blinking on the browser before it gets redirected. Also, you can see the log `onMounted: hello, foo!` from the console.

### Describe the bug

In a CSR application, when using a route middleware to redirect externally from a Nuxt page to another location (by using `navigateTo` with `external: true`), the setup script of the page where we apply the middleware is executed whereas it should not be (I believe?). As well as the lifecycle hooks such as `onMounted`. It's not the case when redirecting to an internal route.

**Comment by danielroe** [comment]
Wonderful!
