### ISSUE TITLE
Running Nuxt 3 development server with debugging mode not available?

### ISSUE THREAD

**Issue by cadenzah** [nuxt/nuxt#21312]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.5.0
- Nitro Version:    2.4.1
- Package Manager:  yarn@1.22.10
- Builder:          vite
- User Config:      srcDir, app, alias, css, modules, plugins, imports, logLevel, vite
- Runtime Modules:  ~/modules/eventHandler/index.js, ~/modules/eventBus/index.js, ~/modules/router/index.js, @pinia/nuxt@0.4.10
- Build Modules:    -
------------------------------

### Reproduction

Run below command:

```bash
node --inspect node_modules/.bin/nuxt dev
```

### Describe the bug

I want to start Nuxt development server while enabling the debug mode. For usual case if I run a node server with debug flag, I get a prompt message something like below:

```
Debugger listening on ws://127.0.0.1:9229/081fbb8d-b3e0-4ef5-92e6-54242327a280
```

And also by that point I can find the debugging tool for the server is activated by looking at the chrome inspector tool:

![debug](https://github.com/nuxt/nuxt/assets/18698124/7e294a65-481d-402a-bacb-f545bc8f1eb0)

But if I run that command with Nuxt 3 (3.5.0), it runs with same config as I run just `nuxt dev`. This did work with Nuxt 2 though, is there a change with how to run Nuxt server in debugging mode?

**Comment by cadenzah** [comment]
Probably it was a temporary issue, it doesn't reproduce. I'll close this issue, sorry about that.

**Comment by cadenzah** [comment]
It looks like the nuxt(node) server does run in debug mode, but whan I open the devtool it shows only blank browser screen, and it doesn't detect any debugger point on the code.

I ran the below script to run the nuxt server, is this wrong usage?

```bash
node --inspect node_modules/.bin/nuxt dev
```

Also, as soon as I run the node server with the script above, the console shows the message below:

```bash
Debugger listening on ws://127.0.0.1:9229/e32af443-7ba6-4179-b8b6-3ba4c1f70ab9
For help, see: https://nodejs.org/en/docs/inspector
Starting inspector on 127.0.0.1:9229 failed: address already in use
```

Is this saying that the inspector is not run properly? If so, what shall I check to make it run correctly?

**Comment by danielroe** [comment]
Would you provide a reproduction?

It's also worth checking you don't already have another project running with debugger? (Does this still reproduce after restarting your computer?)

**Comment by cadenzah** [comment]
@danielroe
Unfortunately it seems that is not the case. I also checked the ports occupied, but there wasn't 9229 port on the list. I restarted my machine and ran the script again, only finding out the same result.

**Comment by cadenzah** [comment]
@danielroe I provided reproduction, if you run the command you will see the above message and outcomes.

**Comment by cadenzah** [comment]
For those who need nuxt server log which you can find on Node devtools, you can get some infomation by putting `debug` props to `true` in `nuxt.config.js`:

```js
// nuxt.config.js
export default defineNuxtConfig({
    ...
    debug: true,
    ...
});
```

But even with this enabled, I can't get enough log message i.e. runtime error log at server-side.

**Comment by danielroe** [comment]
Have you tried this? https://nuxt.com/docs/guide/going-further/debugging#debugging-in-your-ide

This should definitely work.

**Comment by Clive-Ward-Cron** [comment]
I'm running into a similar issue with Nuxt v3.5.2 when trying to attach the debugger to the node process.

I was **previously** able to attach the vscode debugger to the Nuxt process directly using this launch configuration:

```js
{
      "type": "node",
      "request": "attach",
      "processId": "${command:PickProcess}",
      "name": "server: attach to nuxt"
}
```

I can see the debugger attaching in my terminal, but the break points will not bind in vscode.

Now I'm only able to get the debugger to work when using the `fullstack: nuxt` compound configuration provided by the link @danielroe provided that launches the Nuxt dev server in the vscode integrated terminal:

> Have you tried this? https://nuxt.com/docs/guide/going-further/debugging#debugging-in-your-ide
> 
> This should definitely work.

**Comment by zhuscat** [comment]
I have the same problem @danielroe

**Comment by danielroe** [comment]
Thanks for the deep dive! this should be straightforward to fix if someone wants to give it a try.
