### ISSUE TITLE
Access result of route handler on server side middleware

### ISSUE THREAD

**Issue by MSchutt** [nuxt/nuxt#21315]
### Describe the feature

From my stackoverflow question: https://stackoverflow.com/questions/76323883/nuxt-3-after-response-middleware

I have a use-case where I would like to call a middleware after the response went through the route handler. The docs describe that the standard server middleware only runs BEFORE the request is handled (https://nuxt.com/docs/guide/directory-structure/server).

What I'd like to accomplish is:

```
// file: server/api/test/index.ts
export default defineEventHandler(async (event) => {
    return { "test": true }
})
```
When I call the endpoint via GET /api/test I would like the response to be:

`{ "result": { "test": true } }`

So basically mapping all APIs response in a object with key "result". This is quite easy to do with express middleware and other frameworks as you can usually await the route handler's result and then just wrap the result in the object.

It seems that currently there is no way to access the route handler's response inside of a server side middleware. Within most frameworks (i.e. express) you can usually await the response within the middleware function.

Suggested syntax which would be desirable:
```
// file: server/middleware/test.ts
export default defineEventHandler(async (event) => {
  // Before
  console.log('New request: ' + getRequestURL(event))
  const result = await event.requestHandler // any function/property that can be await that contains the result
  // After (wrap in result object)
  return { result };
})
```

### Additional information

- [ ] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Would you raise this as a feature request on h3 instead?

https://github.com/unjs/h3
