### ISSUE TITLE
Layout error when using an Element ref on v-for

### ISSUE THREAD

**Issue by jbreuil** [nuxt/nuxt#21323]
### Environment

Nuxt project info:                                                                                                         15:46:56

------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.5.2
- Nitro Version:    2.4.1
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

[reproduction](https://stackblitz.com/github/jbreuil/layout-repro)

In this reproduction, the error is triggered when the layout is changed on routing. The error start appearing when adding a ref element in the component. The ref is on a v-for following the [documentation syntax](https://vuejs.org/guide/essentials/template-refs.html#refs-inside-v-for) and [typing](https://vuejs.org/guide/typescript/composition-api.html#typing-template-refs)

### Describe the bug

Related to #13309, where people have the same error when using Transition.

Here the error is the same and triggered at the same time (change of layout on routing  to another page). In this reproduction, the error is appearing once we add a ref in the v-for of the component.

Fixed if you downgrade to nuxt 3.3.3

**Comment by danielroe** [comment]
This very much sounds like a Vue error. Could you try to reproduce on https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter to see if it can be reproduced without Nuxt?

**Comment by jbreuil** [comment]
Fix on nuxt 3.6.1
