### ISSUE TITLE
Server sendRedirect not routing client

### ISSUE THREAD

**Issue by timmaier** [nuxt/nuxt#21334]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.5.2`
- Nitro Version:    `2.4.1`
- Package Manager:  `pnpm@8.6.0`
- Builder:          `vite`
- User Config:      `ssr`, `css`, `devServer`, `postcss`, `modules`, `veeValidate`, `robots`, `headlessui`, `components`, `pinia`, `devtools`, `vite`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.7.0`, `@nuxtjs/robots@3.0.0`, `@pinia/nuxt@0.4.11`, `@vee-validate/nuxt@4.9.6`, `@vueuse/nuxt@10.1.2`, `@nuxt/content@2.6.0`, `nuxt-headlessui@1.1.4`, `@unlazy/nuxt@0.8.9`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-rsjc9z?file=server%2Fapi%2Flogin.post.ts

### Describe the bug

Hey I have a nuxt 3 SSR project and have a server POST api route `/api/login` that I invoke via useFetch within a signIn method.

In my actual project, a bunch of network requests are run in the eventHandler (csrf, login, session) when useFetch('/api/login') is called from the client. Where my problem sits is with the last call in this file:

sendRedirect(event, '/listing/create')

I would expect my frontend to route to this page but it doesn't. Only after refreshing is my user in a "logged in state" I thought maybe my auth/session management had a bug so I recreated a minimal repo in Stackblitz and the problem persists there without the auth/session management. In the repo I would expect hitting the "Login and redirect" button routes to /listings/create.

https://stackblitz.com/edit/github-rsjc9z?file=server%2Fapi%2Flogin.post.ts

I'm new to SSR and nuxt so maybe there's something I've missed. Thanks for any help.

**Comment by warflash** [comment]
Quoting daniel [here](https://discord.com/channels/473401852243869706/1002541842409193563/1022558346798174340):
> You can't change the page the user is on from within the server route if it is just responding to an XHR request. You will need to call navigateTo on client side instead.

**Comment by timmaier** [comment]
Ahh okay, so the reason it works in this [todo](https://github.com/Atinux/nuxt-todos-edge) application [here]( https://nuxt-todos-edge.pages.dev/) then is because it's treated as a full page redirect via the anchor tag rather than an XHR.

Okay, I'll have to run a navigateTo on the client since it has to be an XHR so I can pass the username and password to the server.
