### ISSUE TITLE
comment tag in HTML source code

### ISSUE THREAD

**Issue by giticon** [nuxt/nuxt#21358]
### Environment

- Operating System: Windows_NT
- Node Version: v18.14.0
- Nuxt Version: 3.5.0
- Nitro Version: 2.4.0
- Package Manager:  yarn@1.22.10
- Builder:  vite
- User Config:  imports, app, modules, plugins, build, vue, vite, svgo, css, content, image, tailwindcss
- Runtime Modules:  @nuxtjs/tailwindcss@6.7.0, nuxt-svgo@3.1.0, @nuxt/content@2.6.0, @nuxt/image-edge@1.0.0-28094923.e859bba

### Reproduction

nuxt.com -> ctrl+u -> see the html source code

### Describe the bug

Going to see the page sergeant code appears this code at the beginning and end of certain tags. The error shown in the attachment is also present on nuxt.com . I have the same error
![capture_001_04062023_135644](https://github.com/nuxt/nuxt/assets/27739275/44fffa6f-4ad1-4666-a23c-d5063f2a0f8a)

**Comment by wilsonpinto** [comment]
This is related with this: https://github.com/nuxt/nuxt/issues/18754#issuecomment-1416683065

It's not an error and there is no significant impact on page speed.

**Comment by giticon** [comment]
I understand your point of view well, but from my point of view introducing unrequired, superfluous and redundant code may not generate significant effects in the front-end but remains technically and conceptually wrong. Just think of the case where you need to copy that HTML code for "n" reasons.

**Comment by wilsonpinto** [comment]
> I understand your point of view well, but from my point of view introducing unrequired, superfluous and redundant code may not generate significant effects in the front-end but remains technically and conceptually wrong. Just think of the case where you need to copy that HTML code for "n" reasons.

Hi @giticon, your concerns regarding the potential issues with introducing unneeded or redundant code are certainly valid. However, the extra HTML comments actually serves a role in Vue's reactivity system. It acts as a placeholder for Vue's reactive Shadow DOM, which in turn allows us to manipulate our components efficiently.

In the context of Vue, what might appear to be superfluous actually aids in improving the performance and reactivity of the application.
