### ISSUE TITLE
Could you upgrade nuxt2 to webpack5? The combination of webpack5 + vue2.7 will make nuxt2 more compatible with older browsers.

### ISSUE THREAD

**Issue by yisibell** [nuxt/nuxt#21367]
### Describe the feature

Although **nuxt3** already supports** webpack5**, **nuxt2** still has a large number of users. Can we consider upgrading **nuxt2** to **webpack5**? For example, **Vue cli** did this.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
I am very sympathetic to your point of view, but we do not plan to do this as Webpack 5 would be a breaking change for Nuxt 2 users and would additionally be a significant amount of time for the team to spend. Our focus this year is to help people transition to Nuxt 3 by the end of the year, when both Vue 2 and Nuxt 2 reach End of Life.

**Comment by yisibell** [comment]
Okk，i see! Thank you for your reply!
