### ISSUE TITLE
A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. 

### ISSUE THREAD

**Issue by yveeven** [nuxt/nuxt#21373]
### Environment

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  Languages:
    Bash: 1.0 - /bin/bash

### Reproduction

https://stackblitz.com/edit/nuxt-starter-ljsoxg?file=middleware%2Fauth.global.ts

### Describe the bug

I called the pinia action in the global middleware to send a request via axios and got an error

`A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. `

**Comment by yveeven** [comment]
But I found that wrapping the request file for axios without utils does not report errors and executes the asynchronous request normally

**Comment by danielroe** [comment]
The issue is that you are calling `useAppConfig()` at the top level of your JS code. See https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables.

**Comment by yveeven** [comment]
> 问题是你在JS代码的顶层调用`useAppConfig()`。参见[https：//nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables](https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables)。

Thank you for answering my big question, but I took the liberty of asking why, I didn't quite understand the documentation.

**Comment by danielroe** [comment]
Happy to expand further. Did you read the section and also the linked comment? What did you find unclear?

**Comment by yveeven** [comment]
> Happy to expand further. Did you read the section and also the linked comment? What did you find unclear?

After checking the documentation, I understand that it is because utils is imported automatically, before the nuxt instance is created, so it is not possible to use useAppConfig(), but I am not sure if this is the case

**Comment by yveeven** [comment]
> Happy to expand further. Did you read the section and also the linked comment? What did you find unclear?

I would like to add my understanding, is it because I put useAppConfig() at module level, in fact at this time nuxt must not be loaded
