### ISSUE TITLE
Component StyleTags in SSR incorrect with builder `vite` with `cssCodeSplit: false`

### ISSUE THREAD

**Issue by ThornWalli** [nuxt/nuxt#21381]
### Environment

- Operating System: Darwin
- Node Version:     v16.20.0
- Nuxt Version:     3.5.2
- Nitro Version:    2.4.1
- Package Manager:  npm@8.19.4
- Builder:          vite
- User Config:      vite, build
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

**Repo:** https://github.com/ThornWalli/nuxt-testing/tree/feature/missing-component-style-tag
```
npm i 
npm run generate
```

To compare, look in the file `.output/public/index.html`.

**Vite Config**
```
{
  vite: {
      build: {
          cssCodeSplit: false
      }
  },
}
```

There are two pages:

- Index `pages/index.vue`
- Page 1 `pages/page-1.vue`

There are two components:

- ComponentA `components/ComponentA.vue`
- ComponentB `components/ComponentB.vue`

On the index page ComponentA and ComponentB are implemented.

On the page "Page 1" ComponentB is implemented.

### Describe the bug

On the "Index" page, the style tag of ComponentB is missing if it is implemented on the "Page 1" page.

![image](https://github.com/nuxt/nuxt/assets/8287751/09ecd4a3-fc24-4695-adbf-737198bbf593)

If the page "Page 1" is ignored (`.nuxtignore`), both style tags are present in the page "Index".

![image](https://github.com/nuxt/nuxt/assets/8287751/23f87f89-345e-4e21-b03b-a6d4bcf540b8)

**Comment by danielroe** [comment]
This should be resolved in https://github.com/nuxt/nuxt/pull/23049
