### ISSUE TITLE
Commented CSS import in `<script>` is used.

### ISSUE THREAD

**Issue by ThornWalli** [nuxt/nuxt#21384]
### Environment

- Operating System: Darwin
- Node Version:     v16.20.0
- Nuxt Version:     3.5.2
- Nitro Version:    2.4.1
- Package Manager:  npm@8.19.4
- Builder:          vite
- User Config:      vite, build
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

**Repo:** https://github.com/ThornWalli/nuxt-testing/tree/feature/comment-css-import
```
npm i 
npm run generate
```

To compare, look in the file `.output/public/index.html`.

**Vite Config**
```
{
  vite: {
      build: {
          cssCodeSplit: false
      }
  },
}
```

### Describe the bug

Although the import is commented, it is still implemented as a style tag in the page.

https://github.com/ThornWalli/nuxt-testing/blob/29548464d6c4bf21dc15cd26323adccd4199d2d5/pages/index.vue#L7-L11

**Comment by danielroe** [comment]
This has been resolved upstream in `mlly`.
