### ISSUE TITLE
CSS import in plugin is missing in Generate as StyleTag with builder vite with cssCodeSplit: false

### ISSUE THREAD

**Issue by ThornWalli** [nuxt/nuxt#21383]
### Environment

- Operating System: Darwin
- Node Version:     v16.20.0
- Nuxt Version:     3.5.2
- Nitro Version:    2.4.1
- Package Manager:  npm@8.19.4
- Builder:          vite
- User Config:      vite, build
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

Repo: https://github.com/ThornWalli/nuxt-testing/tree/feature/plugin-css-import

```
npm i 
npm run generate
```

To compare, look in the file `.output/public/index.html`.

**Vite Config**
```
{
  vite: {
      build: {
          cssCodeSplit: false
      }
  },
}
```

### Describe the bug

A CSS file is imported in the plugin (client/server).

Specified CSS content is not included in the rendered HTML.

https://github.com/ThornWalli/nuxt-testing/blob/ce420bbdc3f6b1c57236dc69a33dc68a0061db5f/plugins/plugin.mjs#L2

**Comment by danielroe** [comment]
This should now be resolved in https://github.com/nuxt/nuxt/pull/23049.
