### ISSUE TITLE
fsevents EBADPLATFORM error

### ISSUE THREAD

**Issue by julian-printemps** [nuxt/nuxt#21393]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v16.20.0
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  npm@8.19.4
- Builder:          vite
- User Config:      typescript, ssr, nitro, runtimeConfig, modules, i18n, pinia, gtag, css, build, vite, hooks, app
- Runtime Modules:  @pinia/nuxt@0.4.11, @nuxtjs/i18n@8.0.0-beta.12, nuxt-gtag@0.5.7
- Build Modules:    -
------------------------------

### Reproduction

_No reproduction link_

### Describe the bug

I upgraded Nuxt to the latest version, and I get an error when deploying on Firebase.

### Logs

```shell-script
Build failed: npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  undefined
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64
```
```

**Comment by Chuiantw1212** [comment]
Workaround: Adding "linux" to "os".

![Screen Shot 2023-06-17 at 4 20 19 PM](https://github.com/nuxt/nuxt/assets/10844438/d0b769ba-4419-4189-82f4-f5faddc74775)

**Comment by Hebilicious** [comment]
@danielroe upstream issue tracked there https://github.com/unjs/nitro/issues/1367

**Comment by Chuiantw1212** [comment]
I guess its the same issue, I am unable to run the following command while deploying to firebase.
device OS: windows x64
![image](https://github.com/nuxt/nuxt/assets/10844438/a90455d3-9434-4ebf-b351-a963716f2235)

**Comment by Hebilicious** [comment]
> I guess its the same issue, I am unable to run the following command while deploying to firebase. device OS: windows x64 ![image](https://user-images.githubusercontent.com/10844438/251972642-a90455d3-9434-4ebf-b351-a963716f2235.png)

there's a fix available here https://github.com/unjs/nitro/pull/1381, you can workaround the issue by deleting fsevents from the package.json and node_modules of your bundled firebase directory

**Comment by Eckhardt-D** [comment]
Are there any new updates regarding this issue? I have just started encountering it, although I have not seen it once during multiple deploys. The only changes I made was I ran npx nuxi clean, adding nuxt-simple-sitemap and adding an 'isr' route rule.

**Comment by danielroe** [comment]
Let's track upstream in https://github.com/unjs/nitro/issues/1367
