### ISSUE TITLE
Installation failed with nuxi

### ISSUE THREAD

**Issue by liamwang** [nuxt/nuxt#21391]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     0.0.0
- Nitro Version:    -
- Package Manager:  unknown
- Builder:          webpack
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

```bash
 npx nuxi init nuxt-demo
```

or 

```bash
pnpm dlx nuxi init nuxt-demo
```

### Describe the bug

I always fail to initialize a Nuxtjs project.  I have tried switching the npm registry, using VPN proxy, and changing DNS settings but none of them worked.  Installing other NPN packages is normal, and I can also use `npx create-next-app@latest` to install Nextjs projects smoothly. 

Screenshots from one month ago(Nuxi 3.4.3):

![image](https://github.com/nuxt/nuxt/assets/5000396/132eb9f4-4c74-4668-9235-97261940654a)

![image](https://github.com/nuxt/nuxt/assets/5000396/bbf09f79-f222-46d8-bf3a-c026d3f4b8e0)

Today's screenshot(Nuxi 3.5.3):

![image](https://github.com/nuxt/nuxt/assets/5000396/94a672c2-54d6-4e55-a980-26aefcfcbdfb)

Screenshot of successful installation of Next.js:

![image](https://github.com/nuxt/nuxt/assets/5000396/e3775cdf-b000-43de-a989-1028dd53ec15)

**Comment by danielroe** [comment]
I can't reproduce this:

![CleanShot 2023-06-06 at 13.24.24.png](https://volta.s3.fr-par.scw.cloud/Clean_Shot_2023_06_06_at_13_24_24_3c8f66fe24.png)

cc: @pi0

**Comment by ah-dc** [comment]
nuxi fetches templates from raw.githubusercontent.com and your network is unable to access it, you can try adding a host entry or setup proxy on your router

**Comment by liamwang** [comment]
@ah-dc  Thank you. Adding a host entry solve the problem.
