### ISSUE TITLE
defineProps<Props> with external Props give a "Cannot read properties of undefined (reading 'sys')"

### ISSUE THREAD

**Issue by Aurion72** [nuxt/nuxt#21398]
### Environment

Ubuntu
Node 18
Nuxt 3.5.3 (same on 3.5.1 or 3.5.2)
Vue 3.3.4 (same on 3.3.3, 3.3.2, 3.3.1)
Nitro Version: 2.4.1

### Reproduction

https://stackblitz.com/edit/nuxt-props-ts-issue?file=tailwind.config.js,components%2FAHeader%2FAHeader.vue,components%2FALogoTest%2FALogoTest.vue

### Describe the bug

When I import types from an external file into a component and I want to use these types in defineProps, I get the following error on the reproduction link :

![image](https://github.com/nuxt/nuxt/assets/17456821/59233a50-4119-4820-8600-e00bc39cb604)

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/20936
