### ISSUE TITLE
`useCookie` non-persistent cookie seem to be not working

### ISSUE THREAD

**Issue by trandaison** [nuxt/nuxt#21411]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.5.1`
- Nitro Version:    `2.4.1`
- Package Manager:  `pnpm@8.6.0`
- Builder:          `vite`
- User Config:      `plugins`, `css`, `vite`, `build`, `devtools`, `modules`, `routeRules`, `runtimeConfig`, `elementPlus`, `i18n`, `auth`
- Runtime Modules:  `@vueuse/nuxt@10.1.2`, `@pinia/nuxt@0.4.11`, `./modules/auth`, `@nuxtjs/i18n@8.0.0-beta.12`, `@element-plus/nuxt@1.0.5`, `@unocss/nuxt@0.52.6`, `nuxt-lodash@2.4.1`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/github/nuxt/nuxt/tree/main/examples/composables/use-cookie?terminal=dev&file=app.vue

### Describe the bug

As the docs mention:

![Screen Shot 2023-06-06 at 22 26 12](https://github.com/nuxt/nuxt/assets/13447235/4844dbd8-d446-4519-9cad-06232135b9ef)

However, when not specifying an expiration date, the cookie automatically expires 1 year later.
So, I cannot set a cookie that expires when the browser closes. Is there a way to do this?

```ts
const persistent = useCookie('persistent');
// or
// const persistent = useCookie('persistent', { expires: undefined });

persistent.value = 'no';
```

![Screen Shot 2023-06-06 at 22 28 58](https://github.com/nuxt/nuxt/assets/13447235/83330d3e-aa1b-426a-9729-eb9c60aa753b)

**Comment by danielroe** [comment]
I suspect this is your browser's behaviour, rather than Nuxt's. Try running this code in your browser's devtools and seeing what happens:

```
document.cookie = 'persistent=no; Path=/'
```

When testing the repo, everything works as expected for me.
