### ISSUE TITLE
Caching is broken

### ISSUE THREAD

**Issue by SeanDylanGoff** [nuxt/nuxt#21414]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      routeRules
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-zfr2rj?file=nuxt.config.ts

Observe how the timestamp from app.vue never gets updated when reloading the page, even after 10 seconds.

### Describe the bug

With the following nuxt config:

```
{
  routeRules: {
    '**': {
      cache: {
        maxAge: 10,
      },
    },
  },
}
```

I would expect SSR rendered content to be cached for 10 seconds.
While the max-age header reflects that correctly, the same stale HTML gets served indefinitely.

**Comment by danielroe** [comment]
cc: @pi0

**Comment by pi0** [comment]
Thanks for reporting the issue and making a reproduction @SeanDylanGoff.

Trying with Nitro renderer only, it _seems_ not an upstream issue with Nitro but a regression somehow happened in nuxt renderer implementation.

[https://github7brgvq-ujei--3000--bf38680a.local-credentialless.webcontainer.io (cache invalida](https://stackblitz.com/edit/github-7brgvq?file=nitro.config.ts,renderer.ts) (cache invalidates properly)


Investigating your nuxt reproduction with some internal logs, the renderer result from cached function evaluate to this:


```
{ expired: true, ttl: 10000 }                                                                                                                     
resolving new value                                                                                                                              
Value {                                                                                                                                           
  code: 200,
  headers: {
    etag: 'W/"8C37fagqQL"',
    'last-modified': 'Wed, 07 Jun 2023 09:46:50 GMT',
    'cache-control': 'max-age=10'
  },
  body: undefined
}
```

Investigating more just shared current status
