### ISSUE TITLE
tailwindcss modules order problem

### ISSUE THREAD

**Issue by productdevbook** [nuxt/nuxt#21415]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.16.0
- Nuxt Version:     3.5.0
- Nitro Version:    2.4.1
- Package Manager:  pnpm@8.5.1
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/productdevbook/bug-tailwindcss

### Describe the bug

pnpm i
pnpm dev web

this color dont see .md files

```
  modules: [
    '@nuxtjs/tailwindcss',
    '@nuxt/content',
  ],
``` 
![image](https://github.com/nuxt/nuxt/assets/38668796/87e15f6c-71d4-446d-9d08-9f5c4b239a67)

if `layer` nuxt.config.ts in change array order, will working tailwindcss

```
  modules: [
    '@nuxt/content',
    '@nuxtjs/tailwindcss',
  ],
``` 
![image](https://github.com/nuxt/nuxt/assets/38668796/a0be660b-0c21-49a1-a947-84fd6f71541e)

**Comment by danielroe** [comment]
Would you open this instead in the https://github.com/nuxt-modules/tailwindcss/ repo?
