### ISSUE TITLE
Child page setup called without <nuxt-page> on parent page

### ISSUE THREAD

**Issue by IlyaSemenov** [nuxt/nuxt#21417]
### Environment

- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-9hmdww

### Describe the bug

During client-side navigation to `/page` when there are both `page.vue` and `page/index.vue`, the `setup()` function of `page/index.vue` is:
1) called when it shouldn't (if `page.vue` doesn't have `<nuxt-page>`);
2) called twice (if `page.vue` has `<nuxt-page>`).

* The problem does not repeat on hard refresh (SSR), it only happens during client-side navigation.
* To trigger the bug, the originating page must also be a nested page (`foo.vue` + `foo/whatever.vue`).
* To trigger the bug, `page.vue` should have `setup()` function, possibly doing nothing.

On the reproduction URL there are two simple demos:

- Demo 1 is the simplest minimal reproduction, but it needs you to open devtools console. You will see that `setup` of the child page (`1/index.vue`) is called when it should not.
- Demo 2 shows the bug even without devtools. It prints how many times the child `setup` was called, you can see that it is called twice.

### Additional context

This is a regression introduced in Nuxt 3.5. The same code works correctly in Nuxt 3.4.3.

_**UPDATE:** This is not entirely true. The reproduction above crashes in Nuxt 3.4, too. [See below](https://github.com/nuxt/nuxt/issues/21417#issuecomment-1580724743) for the actual regression reproduction._

**Comment by baiwusanyu-c** [comment]
Are you sure that the script will not be executed in 3.4.3? I checked all the submissions from 3.4.3 to 3.5.0 and tested it in the 3.4.3 version. The execution result is that the script will be called
https://stackblitz.com/edit/nuxt-starter-fijqtb?file=package.json

**Comment by IlyaSemenov** [comment]
I can see the problem in your reproduction with Nuxt 3.4.3 as a single dependency. I've extracted this from a real project with a locked set of dependencies including Nuxt 3.4.3 where I double checked that there weren't a problem with the exact same code. I'll see if I can trace this to a sub-dependency update.

**Comment by IlyaSemenov** [comment]
@baiwusanyu-c I came up with a minimum reproduction that works in Nuxt 3.4 but crashes in Nuxt 3.5:
- https://stackblitz.com/edit/nuxt-starter-mrri4n (Nuxt 3.4.3)
- https://stackblitz.com/edit/nuxt-starter-nscm2i (Nuxt 3.5.3)

This is the exact same set of files with the only difference in `package.json`.

Run the demo, click "This page will break". In Nuxt 3.4 it will call setup once and not crash, in Nuxt 3.5 it will call setup twice and crash.

**Comment by lorado** [comment]
this behaviour makes my old code not working anymore... I store some data in store between navigations, and on mount initialize the form with the given data, and clear the data, so that on next visit its not used again. and well... page gets mounted first time, it grabs the data, clears it out, then after `useAsyncData()` returns the data, it kills the page with all stored data, and creates new page with empty fields, bc they were cleared after first initialization... 
As workaround I currently added timeout before I clear the store, but this is really not idea solution at all....
Hope I can dig a little in the code this weekend and try to find the issue
