### ISSUE TITLE
ERROR  [worker reload] [worker init] Only URLs with a scheme in: file and data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'

### ISSUE THREAD

**Issue by djkloop** [nuxt/nuxt#21413]
### Environment

- Operating System: Windows11 22H2 22621.1702
- Node Version:     v18.16.0
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  pnpm@8.6.1
- Builder:          vite
- User Config:      modules, experimental, vite, devtools, unocss, typescript, imports, postcss, colorMode, robots, app
- Runtime Modules:  @unocss/nuxt@0.53.0, @vueuse/nuxt@10.1.2, @vue-macros/nuxt@1.3.11, @pinia/nuxt@0.4.11, nuxt-icon@0.4.1, @nuxt/image-edge@1.0.0-28101015.2a3c501, @nuxtjs/color-mode@3.2.0, @nuxtjs/critters@0.4.1, @nuxtjs/robots@3.0.0, @nuxt/devtools@0.5.5
- Build Modules:    -

### Reproduction

![image](https://github.com/nuxt/nuxt/assets/21050914/2aa98909-5b11-463e-91b6-8bd1ef33aaaa)

### Describe the bug

I used this open source template, and then upgraded to the latest version,I have changed many versions of node and it doesn’t work

https://github.com/mat2ja/nuxt-starter/tree/main

**Comment by prazdevs** [comment]
Hi, the issue is coming from `@nuxtjs/robots`, it's outdated and unmaintained. You should try using https://github.com/harlan-zw/nuxt-simple-robots as a replacement :)

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/21413.

**Comment by manniL** [comment]
As this one is self-referencing, linking https://github.com/unjs/nitro/issues/836 👍

**Comment by NaorTheEnlightened** [comment]
![image](https://github.com/user-attachments/assets/8f375958-1dd4-472f-b053-d445fe097e8b)

A similar issue happens to me as well, on Windows 11, Latest NodeJS version, and Nuxt Version.

It happened suddenly while I was developing with a dev server on my PC.

I have tried reverting recent changes but nothing has helped the issue to persist, I even tried removing the node modules.

I am not using robots.js module.

Here is my package.json:

{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "debug": "nuxi dev --inspect",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "prisma": {
    "seed": "node prisma/seed.js"
  },
  "dependencies": {
    "@nuxtjs/tailwindcss": "^6.12.1",
    "@pinia/nuxt": "^0.5.1",
    "@prisma/client": "^5.16.2",
    "bcrypt": "^5.1.1",
    "google-auth-library": "^9.11.0",
    "jsonwebtoken": "^9.0.2",
    "nuxt-vue3-google-signin": "^0.0.11",
    "pinia": "^2.1.7",
    "vue": "latest",
    "vue3-draggable-next": "^4.1.4",
    "zod": "^3.23.8"
  },
  "devDependencies": {
    "autoprefixer": "^10.4.19",
    "nuxt": "^3.12.3",
    "postcss": "^8.4.39",
    "prisma": "^5.16.2",
    "tailwindcss": "^3.4.5"
  },
  "overrides": {
    "vue": "latest"
  }
}


Here is my nuxt.config.ts:

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: '2024-04-03',
  devtools: { enabled: false },
  debug: true,
  // colorMode: {
  //   preference: 'light', // default value of $colorMode.preference
  // },
  plugins: ['~/plugins/prisma.js', '~/plugins/auth.js'],
  sourcemap: {
    server: true,
    client: true,
  },
  runtimeConfig: {
    // Keys within public are also exposed client-side
    public: {
      apiBase: '/api',
    },
    jwtSecret: process.env.JWT_SECRET,
    googleClientId: process.env.GOOGLE_CLIENT_ID,
  },
  modules: [
    '@nuxtjs/tailwindcss',
    '@pinia/nuxt',
    'nuxt-vue3-google-signin',
  ],
  css: ['~/assets/css/main.css'],
  postcss: {
    plugins: {
      tailwindcss: {},
      autoprefixer: {},
    },
  },
  googleSignIn: {
    clientId: process.env.GOOGLE_CLIENT_ID,
  },
});



Please help fix the issue promptly, as I am unable to continue an important project of mine built with Nuxt 3.

Thanks for all helpers.
