### ISSUE TITLE
Nuxt layer + veeValidate dont work in production

### ISSUE THREAD

**Issue by shba007** [nuxt/nuxt#21431]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  npm@9.6.7
- Builder:          vite
- User Config:      modules
- Runtime Modules:  @nuxt/devtools@0.5.5, @nuxtjs/tailwindcss@6.7.0, @vueuse/nuxt@10.1.2, nuxt-icons@3.2.1, nuxt-vitest@0.8.5  
- Build Modules:    

### Reproduction

Use a component from a nuxt layer poroject with vue validate

### Describe the bug

onSubmitting the form vueValidate does not gives any value on production while on development it works correctly

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
