### ISSUE TITLE
How do i use option vite.build.rollupOptions.output

### ISSUE THREAD

**Issue by fatcarter** [nuxt/nuxt#21453]
### Environment

- Operating System: Darwin
- Node Version:     v18.15.0
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      modules, vite
- Runtime Modules:  nuxt-icon@0.4.1
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-yubkie?file=app.vue

### Describe the bug

in production mode

a 404 error occurred in the js file of home page

**Comment by fatcarter** [comment]
My `nuxt.config.js` 
```javascript
// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  modules: ['nuxt-icon'],
  vite: {
    build: {
      rollupOptions:{
        output: {
          chunkFileNames: "chunk/[hash].js",
          entryFileNames: 'entry/[hash].js',
          assetFileNames: '[ext]/[hash].[ext]'
        }
      }
    }
  }
})
```

**Comment by danielroe** [comment]
you also need to set `app.buildAssetsDir` - and ensure all your build assets are in a common directory, or individually add each folder to `nitro.publicAssets`. For example:

```js
export default defineNuxtConfig({
  app: {
    buildAssetsDir: 'assets'
  },
  vite: {
    build: {
      rollupOptions: {
        output: {
          chunkFileNames: 'assets/chunk/[hash].js',
          entryFileNames: 'assets/entry/[hash].js',
          assetFileNames: 'assets/[ext]/[hash].[ext]'
        }
      }
    }
  }
})
```

**Comment by udit99** [comment]
So I tried both the things mentioned above and have started getting a 500 error in production: "error loading dynamically imported module: https://${{MY_APP}}/assets/chunk/${{RANDOM_HASH}}.js

If I remove the rollupOptions and deploy again, it fixes it.
The first deploy after I reintroduce the rollupOptions also works
The 2nd deploy after the rollupOptions are introduced throws the 500.

Is there some sort of cache that needs to be cleared between deploys to prevent this? Any ideas what could be happening?

cc: @danielroe @fatcarter

**Comment by danielroe** [comment]
Would you confirm you're on the latest Nitropack? There was a bug with ignore-options that meant that chunks starting with `-` would not be included in the build, but this is resolved.
