### ISSUE TITLE
SWR not working on Vercel when using @urql/vue

### ISSUE THREAD

**Issue by lewebsimple** [nuxt/nuxt#21469]
### Environment

- Operating System: Linux
- Node Version:     v16.17.1
- Nuxt Version:     3.5.2
- Nitro Version:    2.4.1
- Package Manager:  pnpm@8.6.0
- Builder:          vite
- User Config:      routeRules
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://github.com/lewebsimple/nuxt-vercel-swr-repro

Without SWR (works ok): https://nuxt-vercel-swr-repro-ompuy6o9u-ledevsimple.vercel.app/
With 60s SWR (never updates): https://nuxt-vercel-swr-repro-dx3cqusur-ledevsimple.vercel.app/

### Describe the bug

When setting `routeRules: { "/**": { swr: 60 } }` and deploying to Vercel the cached async data payload doesn't expire after the defined TTL.

### Additional context

The reproduction provided illustrates the problem with a timestamp returned from `useAsyncData`.

I would expect the timestamp to change after one minute but it's stuck at Jun 08 2023 16:00:30 GMT+0000 i.e. when it was first visited after deployment.

The other (working) deployment returns the current time on every request as caching is disabled.

**Comment by danielroe** [comment]
You now need to use `isr` to enable the Vercel integration after an upstream change in nitropack.

**Comment by lewebsimple** [comment]
Aaaah thanks so much @danielroe !
It was in the documentation I just didn't understand it right away.

**Comment by lewebsimple** [comment]
Hmmmm ... turns out it's still not working on my other project that's using @urql/vue so it looks like an issue with the way I use it.
Perhaps the cache layer in urql is being used server-side as well.

**Comment by lewebsimple** [comment]
Ok ... turns out it was prerendering that was causing the issue:
```
  nitro: {
    prerender: { crawlLinks: true, routes: ["/"] },
  },
```
