### ISSUE TITLE
Middleware executes twice

### ISSUE THREAD

**Issue by sumerokr** [nuxt/nuxt#21470]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

- go to https://stackblitz.com/edit/github-fwkt62?file=middleware%2Fpage.global.ts
- copy the preview URL from the top right side of the screen. It looks like `https://_randon_string_.local-credentialless.webcontainer.io`
- open a new browser tab, paste and navigate to it, ensure you see it running
- manually add `/another` path to the URL and hit enter
- go back to the sandbox browser tab and check the console

**Expected output**
```
! middleware !
navigating /another => /another
...redirecting...
! middleware !
navigating /another => /about
about.vue created
```

**Actual result**
```
! middleware !
navigating /another => /another
...redirecting...
! middleware !
navigating /another => /about
about.vue created
=== THE NEXT THREE LINES LOOK WRONG ===
! middleware !
navigating /about => /about
about.vue created
```

### Describe the bug

When navigating from page A to page B via middleware, instead of `A => B` redirect chain looks like `A => B => B` which doesn't feel right to me.
Page B being created and executed twice.

**Comment by danielroe** [comment]
This should be resolved in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/), or in the next release.

Let me know if not and I'll reopen.

**Comment by sumerokr** [comment]
Hey @danielroe , I did this
```
{
  "devDependencies": {
--  "nuxt": "^3.0.0"
++  "nuxt": "npm:nuxt3@latest"
  }
}
```
, then `rm package-lock.json` and `npm i`.
Has the same result. But I am not sure if it's worked out, since `npm list nuxt` shows the same output for both reproduction sandboxes.
```
❯ npm list nuxt
nuxt-app@ /home/projects/github-fwkt62-qdznec
+-- @nuxt/devtools@0.5.5
| +-- @nuxt/devtools-kit@0.5.5
| | `-- nuxt@3.5.3 deduped
| `-- nuxt@3.5.3 deduped
`-- nuxt@3.5.3
```

**Comment by Tristan971** [comment]
Why was this closed? We're observing the same behaviour on Nuxt 3.8.2

**Comment by danielroe** [comment]
@Tristan971 Please open a new issue with a reproduction. _This_ issue was resolved but you might be having a similar one.

**Comment by Tristan971** [comment]
Ok. That wasn’t very clear from the comment above.

**Comment by danielroe** [comment]
sorry, I hadn't seen the previous comment; thanks for following up. I'll close this issue again and track in the new one 🙏
