### ISSUE TITLE
Server tsconfig import aliases

### ISSUE THREAD

**Issue by mitjans** [nuxt/nuxt#21484]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.16.0
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  pnpm@8.6.1
- Builder:          vite
- User Config:      devtools, modules, css, eslint
- Runtime Modules:  @vueuse/nuxt@10.1.2, @nuxtjs/supabase@0.3.6, @nuxtjs/tailwindcss@6.7.0, @nuxtjs/eslint-module@4.1.0
- Build Modules:    -
------------------------------

### Reproduction

You can check a minimal reproduction in this repository: https://github.com/mitjans/nuxt-server-types

Typescript complains that it cannot find the module `"~/types/database"`.

![image](https://github.com/nuxt/nuxt/assets/7190600/7527e2f7-375c-49d3-9c83-d39a54ab7b48)

### Describe the bug

It seems that with the new tsconfig file introduced in version 3.5.2, global nuxt import aliases do not work inside the server folder. Autocompletion suggests importing relative paths.

Also, other Nuxt modules imports stopped working. See [@nuxtjs/supabase issue 191](https://github.com/nuxt-modules/supabase/issues/191).

**Comment by danielroe** [comment]
This depends on https://github.com/unjs/nitro/pull/1266.

**Comment by mitjans** [comment]
As I understand it, this is to allow other modules to customize path aliases, right?
What about nuxt path aliases (`"~"` and other)? Or will this also be solved?

**Comment by danielroe** [comment]
That PR will allow Nuxt to add necessary configuration, including aliases (via `paths`). (Though Nitro should also do that for any aliases it is aware of - feel free to open a PR if I don't get to it first.)

**Comment by JCtapuk** [comment]
I also observe this error before 3.5, I normally saw the import paths through @ ~ and others correctly, but now it stopped working, I had to manually set the includes path
![image](https://github.com/nuxt/nuxt/assets/61321608/bd5f2ed4-ded3-49c7-b846-09f05df6c2e9)
