### ISSUE TITLE
Vite `?raw` imports not working in server routes

### ISSUE THREAD

**Issue by mathix420** [nuxt/nuxt#21487]
I want to import markdown files as raw text, following [Vite's documentation](https://vitejs.dev/guide/assets.html#importing-asset-as-string).

```ts[transformers/schema/prompt.ts]
import prompt from '~/prompts/join.md?raw'
```

But I got the following issue: 
```
Error: Could not load [...]/join.md?raw (imported by transformers/schema/prompt.ts):
ENOENT: no such file or directory, open '[...]/join.md?raw'
```

Issue seems to appear only when imported in server routes.

Reproduction:
https://stackblitz.com/edit/github-tuan9y?file=server%2Fapi%2Freadme.get.ts

_Originally posted by @mathix420 in https://github.com/nuxt/nuxt/discussions/19694#discussioncomment-6131202_

**Comment by mathix420** [comment]
@danielroe just added reproduction link => https://stackblitz.com/edit/github-tuan9y?file=server%2Fapi%2Freadme.get.ts

**Comment by danielroe** [comment]
Server routes are not processed by Vite but directly by rollup (used by Nitro). Nitro does support a raw loader though. cc: @pi0

**Comment by mathix420** [comment]
Thanks, I should have noticed that nitro was compiled by rollup.

I ended up using [Nitro server assets](https://nitro.unjs.io/guide/assets#server-assets).

**Comment by fanckush** [comment]
@danielroe is there no way nuxt to universally import content of a txt file then?

for example: 

``` js
import strContent from '~/files/hello.txt'

**Comment by pi0** [comment]
@fanckush can you please make an issue in nitro? i think we can support `?raw`
