### ISSUE TITLE
[Documentation Request] Add a styling section to the docs

### ISSUE THREAD

**Issue by Hebilicious** [nuxt/nuxt#21491]
### Describe the feature

The Nuxt3 docs are very light when it comes to styling in general (I know that it has become trendy to use Tailwind and to stop writing stylesheets but still ...).
There is some information that is scattered around, and the docs could really use a dedicated section (similar to the excellent one in [astro](https://docs.astro.build/en/guides/styling/)) to explain everything about styling in Nuxt. 

I'm aware that some of this information could be considered redundant as it can be found respectively in Vite and VueJs docs.
That being said, it would be great, especially for newcomers, if we could have a comprehensive styling guide in the Nuxt docs. 

We could also recommend some best practice while we do this.

Here's what I have in mind 

- How to add an external stylesheet
- How to add a local stylesheet
- How to use useHead for dynamic stylesheet
- How to use preprocessors
- How to leverage layouts to have multiple styles in the same app
- Recap of all the nice SFC styling options (lang/import/scoped/modules/v-bind etc)
- How to configure postcss and use it (plugins etc)
- Font section (This is a really common thing)
- Advanced section (vite config, webpack config, optimizations, minification etc)
- Bonus section (maybe recommend some popular modules and tools such as tailwind or https://unocss.dev/)

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
This is a good idea - thank you!
