### ISSUE TITLE
navigateTo doesn't write query parameters with external URL

### ISSUE THREAD

**Issue by agenordebriat** [nuxt/nuxt#21499]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.5.3`
- Nitro Version:    `2.4.1`
- Package Manager:  `pnpm@8.6.1`
- Builder:          `vite`
- User Config:      `app`, `devtools`, `typescript`, `components`, `hooks`, `runtimeConfig`, `css`, `modules`, `dayjs`
- Runtime Modules:  `@formkit/nuxt@0.18.0-7d9b8a6`, `@unocss/nuxt@0.53.1`, `@vueuse/nuxt@10.1.2`, `dayjs-nuxt@1.1.2`
- Build Modules:    `-`

### Reproduction

Cannot provide a Stackblitz/CodeSandbox reproduction because they don't allow external links.

### Describe the bug

This doesn't seem to work :
```ts
navigateTo(
  { path: "https://www.google.com/search", query: { q: "Nuxt 3" } },
  { external: true },
);
```
I noticed `path` and `query` only work as long as `external` isn't set to `true`.

Workaround :
```ts
import { withQuery } from "ufo"

navigateTo(
  withQuery("https://www.google.com/search", { q: "Nuxt 3 }),
  { external: true },
);
```

Also, I tried to use the `open` option, as seen [here](https://nuxt.com/docs/api/utils/navigate-to#options-optional) and it doesn't even seem to exist.
Current `NavigateToOptions` interface looks like this:
```ts
export interface NavigateToOptions {
    replace?: boolean;
    redirectCode?: number;
    external?: boolean;
}
```

**Comment by danielroe** [comment]
The `open` option will be included in Nuxt 3.6 and is not yet released.
