### ISSUE TITLE
devtools break app running on localhost

### ISSUE THREAD

**Issue by miketests** [nuxt/nuxt#21506]
### Environment

I've created fresh new project with `npx nuxi init <project-name>` command but cannot run Nuxt app locally while devtools option is on.
Request to localhost is pending and the application will never be loaded.
With devtools turned off everything works fine.
Is there a reason to enable devtools by default that is in an experimental state?
So, it looks like the `nuxt.config.ts` is broken right out of the box.

### Reproduction

1) Create new project with `npx nuxi init new_app`
2) Go to the app folder and Install deps `npm i`
3) Run app locally `npm run dev`
4) Open browser and go to the localhost:3000
5) Waiting for the app forever

### Describe the bug

If devtools option is turned on it prevents the app from loading on localhost. 

### Additional context

Node: v16.14.2
NPM: 8.5.0
OS: MacOS

**Comment by danielroe** [comment]
cc: @antfu

**Comment by antfu** [comment]
I am not able to reproduce it with:

```ts
  System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.22 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.13.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
    Watchman: 2023.05.22.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 112.0.5615.137
    Edge: 111.0.1661.44
    Firefox: 92.0
    Safari: 16.4
  npmPackages:
    @nuxt/devtools: latest => 0.5.5 
    nuxt: ^3.5.2 => 3.5.2 
```

Can you share more info? Thanks

**Comment by miketests** [comment]
Thank you so much for taking the time to test on your side.
Indeed there was a problem with a hanging request to the localhost, but when I turned off the devtools option everything worked but after time, so it can be considered as ridiculous coincidence.
Sorry, I think this issue relates to Nitro.
