### ISSUE TITLE
docs: codesandbox demo throws `useNestedBar' is Undefined` error

### ISSUE THREAD

**Issue by kohasummons** [nuxt/nuxt#21515]
### Environment

Browser

### Reproduction

![Screengrab of the CodeSandbox error](https://i.imgur.com/qGM0xJH.png)

### Describe the bug

[The Codesandbox demo](https://nuxt.com/docs/examples/auto-imports/composables) under `auto-imports/composables` proclaims that `'useNestedBar' is not defined` making the sandbox unusable.

**Comment by danielroe** [comment]
There is no bug here with Nuxt but the issu is that Codesandbox is not installing a new enough version of Nuxt for the feature given the `^3.0.0` version constraint.

We need to finish our migration to https://github.com/nuxt/examples to ensure these examples stay up-to-date.

cc: @Atinux

**Comment by kohasummons** [comment]
Okay 🌟

Is there anything I can do to help?

**Comment by danielroe** [comment]
I think a good interim step would be to update the version in each example's package.jsonto 3.5.3.
