### ISSUE TITLE
How to have after middleware?

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt/nuxt#21522]
### Environment

/

### Reproduction

/

### Describe the bug

Hello,

Currently, having 'before' middleware for server-side (https://nuxt.com/docs/guide/directory-structure/server#server-middleware) is easy. But what about 'after' middleware which run after the handler has respond?

**Comment by danielroe** [comment]
Maybe you could open a feature request upstream on https://github.com/unjs/nitro?

**Comment by Barbapapazes** [comment]
Yes, I will do it very soon! I was investigating on the working of middleware in order to write (missing) documentation!
