### ISSUE TITLE
JS not running in DingTalk browser

### ISSUE THREAD

**Issue by zengRRR** [nuxt/nuxt#21528]
### Environment

UA: Mozilla/5.0 (Linux; U; Android 9; zh-CN; MHA-AL00 Build/HUAWEIMHA-AL00) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/69.0.3497.100 UWS/3.22.1.255 Mobile Safari/537.36 AliApp(DingTalk/7.0.30) com.alibaba.android.rimet/29879169 Channel/227200 language/zh-CN abi/64 Hmos/1 UT4Aplus/0.2.25 colorScheme/lig

### Reproduction

https://www.bangkebang.com/
https://openai.com/

### Describe the bug

Nuxt3 web, js cannot work. (Chrome/69.0.3497.100)

![image](https://github.com/nuxt/nuxt/assets/127286038/389f537d-314a-4404-b132-2ecd29216cf5) 
![image](https://github.com/nuxt/nuxt/assets/127286038/8b02d4db-be0b-43e3-a85d-c66308a6fc8f)
![安卓钉钉兼容问题](https://github.com/nuxt/nuxt/assets/127286038/a0acea8f-3dd2-412e-be38-edb98005be8e)

**Comment by danielroe** [comment]
What is the issue you are reporting? Feel free to use Chinese, but not in a screenshot as I cannot translate it.

**Comment by nxl3477** [comment]
Is there any follow-up? This problem is fatal to technology selection

**Comment by danielroe** [comment]
This is probably an upstream issue with DingTalk not supporting modules in the browser.
