### ISSUE TITLE
Router.replace in <setup> breaks when using <NuxtLayout> within pages

### ISSUE THREAD

**Issue by itm-ape** [nuxt/nuxt#21534]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://codesandbox.io/p/github/itm-ape/plugin-types/

### Describe the bug

TypeError when using router.replace inside `<script setup>` in a page-component while using `<NuxtLayout>`

In the sandbox i provided above I have 2 different pages. One using NuxtLayout that breaks and one without NuxtLayout that works. This used to work in Nuxt version 3.4.2. 

This error is preventing us from updating Nuxt.

**Comment by danielroe** [comment]
I can confirm this is fixed in https://github.com/nuxt/nuxt/pull/21450 but I would recommend directly calling `router.replace` within the _setup_ function of a page. Instead I would recommend calling navigation after the page has already mounted.

**Comment by itm-ape** [comment]
> I can confirm this is fixed in #21450 but I would recommend directly calling `router.replace` within the _setup_ function of a page. Instead I would recommend calling navigation after the page has already mounted.

So our use-case is we want to always have the URL align with some internal state in our store. So we have a watcher watching our state and whenever a user performs an action we update our query using router.replace(). Is there another smarter way to do this?

**Comment by danielroe** [comment]
I think middleware would be the natural place for this. (Or via a watcher, as you have.)
