### ISSUE TITLE
Unable to find a version of ajv that satisfies the peerDependencies

### ISSUE THREAD

**Issue by ikselll** [nuxt/nuxt#21543]
### Environment

System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M1 Pro
    Memory: 79.64 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
    Watchman: 2023.06.08.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 110.1.48.158
    Chrome: 114.0.5735.106
    Edge: 113.0.1774.57
    Safari: 16.5
  npmPackages:
    nuxt: ^2.17.0 => 2.17.0

### Reproduction

https://github.com/ikselll/nuxt-ajv + README.md

### Describe the bug

After upgrade from `2.15.8` to `2.16.x` or `2.17.x` some deps changed and there is version mismatch.

### Logs

```shell-script
nuxt-ajv git:(master) ✗ npm run show-issue

> nuxt-ajv@1.0.0 show-issue
> npx check-peer-dependencies

  ✅  ajv ^6.9.1 is required by ajv-keywords@3.5.2 (6.12.6 is installed)
  ✅  ajv >=5.0.0 is required by ajv-errors@1.0.1 (6.12.6 is installed)
  ❌  ajv ^8.8.2 is required by ajv-keywords@5.1.0) (6.12.6 is installed)

Search for solutions using this command:

npx check-peer-dependencies --findSolutions

Install peerDependencies using this command:

npx check-peer-dependencies --install

➜  nuxt-ajv git:(master) ✗ npx check-peer-dependencies --findSolutions
  ✅  ajv ^6.9.1 is required by ajv-keywords@3.5.2 (6.12.6 is installed)
  ✅  ajv >=5.0.0 is required by ajv-errors@1.0.1 (6.12.6 is installed)
  ❌  ajv ^8.8.2 is required by ajv-keywords@5.1.0) (6.12.6 is installed)

Searching for solutions for 1 missing dependencies...

  ❌  Unable to find a version of ajv that satisfies the following peerDependencies: ^6.9.1 and >=5.0.0 and ^8.0.0 and ^8.8.2
```

**Comment by danielroe** [comment]
Yes, this issue seems to be caused by webpack dev middleware having a newer dependency.

**Comment by ikselll** [comment]
@danielroe do U see any workaround for now? Maybe I can downgrade some deps installing previous version direct in project dev deps? I tried do it for avj directly but no luck.
