### ISSUE TITLE
v-for doesn't work on change layout

### ISSUE THREAD

**Issue by luca-smartpricing** [nuxt/nuxt#21544]
### Environment

- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/v-for-layout?file=layouts%2Fdefault.vue

### Describe the bug

When navigate to a route with a different layout, **and there's a `v-for` with a `ref()`** list inside the page, then return a vue warn and a error.

### Logs

```shell-script
[Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/core 
  at <NuxtLayout> 
  at <App key=3 > 
  at <NuxtRoot>


Uncaught (in promise) TypeError: Cannot read properties of null (reading 'parentNode')
    at parentNode (chunk-MNWBZQKJ.js:82:30)
    at ReactiveEffect.componentUpdateFn [as fn] (chunk-3Q27KRJ5.js:5823:11)
    at ReactiveEffect.run (chunk-BOVKDABU.js?v=1765f250:181:19)
    at instance.update (chunk-3Q27KRJ5.js:5860:52)
    at callWithErrorHandling (chunk-3Q27KRJ5.js:213:32)
    at flushJobs (chunk-3Q27KRJ5.js:411:9)
```

**Comment by Hossam01001000** [comment]
code in the setup script is set to run on the server so when you request the page URL everything works but when you navigate to the page using nuxt link the setup code doesn't work as expected 

you can move this line of code 'const test = ref([]);' to onMounted function to make sure it runs every time you navigate to the page
