### ISSUE TITLE
[nuxt] error caught during app initialization TypeError: Cannot destructure property 'store' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by tejassyndell** [nuxt/nuxt#21542]
### Environment

System:
    OS: macOS 13.4
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 761.65 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/node_modules/.bin/yarn
    npm: 9.6.6 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.106
    Firefox: 113.0.1
    Safari: 16.5
  npmPackages:
    @nuxt/content: ^2.6.0 => 2.6.0 
    @nuxt/types: ^2.16.3 => 2.16.3 
    nuxt: ^3.5.3 => 3.5.3

### Reproduction

.

### Describe the bug

I am encountering this error in my project when upgrading the Nuxt.js and Vue.js versions from 2 to 3.  https://prnt.sc/0I1lRudXj3Rg

**Comment by danielroe** [comment]
I would check to see what is destructuring `store` in your project. It could be a module; I would check to see whether all of them support Nuxt 3.
