### ISSUE TITLE
Classes not being merged from parent to child component (in client-only components) 

### ISSUE THREAD

**Issue by riderx** [nuxt/nuxt#21548]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction
![CleanShot 2023-06-13 at 15 15 51@2x](https://github.com/nuxt/nuxt/assets/4084527/dd84dfeb-ccd0-4cbc-8286-4fb7fcfc24e2)

https://stackblitz.com/edit/nuxt-starter-mavf4s?file=components%2FTest.vue

### Describe the bug

If we do client only in a child, neither the client only or the template got the class merged from parent.

Where in the component without client-only it got merged properly.

This have bit fixed for an other flavour of it already here: https://github.com/nuxt/nuxt/issues/15039

**Comment by Hossam01001000** [comment]
you need to have a single root component for it to automatically inherit its parent classes, 
try remove the other <template class="test-component2">

**Comment by riderx** [comment]
@Hossam01001000 I'm not sure to understand, there are only one div in the client-side, the template fallback is only for server side.

**Comment by Hossam01001000** [comment]
you can do it manually with v-bind="$attrs"

for more info
https://vuejs.org/guide/components/attrs.html#attribute-inheritance-on-multiple-root-nodes

**Comment by riderx** [comment]
I don't understand where do you see multiple root component, it's only one the other is a template present only in server side where the first one is not
