### ISSUE TITLE
Define environment variable after npm build and before npm start

### ISSUE THREAD

**Issue by devonik** [nuxt/nuxt#21559]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.14.0
- Nuxt Version:     3.5.1
- Nitro Version:    2.4.1
- Package Manager:  pnpm@8.6.0
- Builder:          vite
- User Config:      runtimeConfig, typescript, css, build, routeRules, vite, modules, gtm, devtools
- Runtime Modules:  @zadigetvoltaire/nuxt-gtm@0.0.13, nuxt-i18n-data@0.1.19, nuxt-vuetify-error-handler@1.1.0, nuxt-delay-hydration@1.2.0, (), @heiland/nuxt-hei-buttons@1.0.3, @pinia/nuxt@0.4.11, @nuxtjs/i18n@8.0.0-beta.12
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-p8jezy
run npm build and the npm start (see package.json start script)

### Describe the bug

The documentation https://nuxt.com/docs/guide/directory-structure/env says that we can define runtimeConfig env variables dynamically after build and before node start
> On a Linux server, you could pass the environment variables as arguments using the terminal DATABASE_HOST=mydatabaseconnectionstring node .output/server/index.mjs

But that does not work. See the stackblitz reproduction. The RUNTIME_VAR defined before node start (see package.json start script) is not defined

### Additional context

I want to define differently environment variables depending on the stage (staging and prod). I deploying on AWS Beanstalk and using Bitbucket for CI/CD. 
In Nuxt2 I can define env variables in AWS Beanstalk and the app will use this - but didnt work for nuxt3.
For nuxt3 I have to define the variables **before** npm run build is running. They seems to be static after that.

I think a similiar bug / missing feature is described here https://github.com/nuxt/nuxt/issues/15366

**Comment by danielroe** [comment]
You can override runtime config with specially-crafted variables. You can even see this when hovering over them in your nuxt.config:

![CleanShot 2023-06-14 at 09 10 01](https://github.com/nuxt/nuxt/assets/28706372/9437f9fb-96b0-4556-8788-95e5f7fc1307)

And in the docs: https://nuxt.com/docs/guide/going-further/runtime-config#environment-variables

**Comment by devonik** [comment]
Interesting. Indeed wIth command `NUXT_RUNTIME_VAR=test_var node .output/server/index.mjs` something seems to be happen. When I refresh the page I am getting `entry.e53f6bbf.js:1 Hydration completed but contains mismatches.` I added the runtimeConfig also in public config so then variable should be loaded on server side and client side but does not work

**Comment by danielroe** [comment]
You should access `$config.public.runtimeVar` in that case. `$config.runtimeVar` will only be defined on the server.

**Comment by danielroe** [comment]
Fantastic! If you can spot any opportunity to improve the DX or documentation here, a PR or idea would be very welcome.

**Comment by septatrix** [comment]
Am I correctly understanding that accessing `process.env` from a production build will not work? It seems to be implied in several places and also does not seem to work but stating it without any fuzz (and maybe even why it does not work) would be a good idea.
