### ISSUE TITLE
Route name generated for /catalog/[slug].vue is the same as /catalog/[...slug].vue

### ISSUE THREAD

**Issue by KOFI-GYIMAH** [nuxt/nuxt#21556]
Usinf [slug].vue and [...slug].vue in the same folder generates a warning:

Route name generated for /catalog/[slug].vue is the same as /catalog/[...slug].vue

How do I override some page component name?

**Comment by wilsonpinto** [comment]
@KOFI-GYIMAH the warnings makes sense since [...slug].vue will give you an array which already contains a patchMatch for the first [slug].vue 

You can use [...slug].vue and check the number of params to apply different logic in your page

**Comment by danielroe** [comment]
Alternatively, you can specify a different name in `definePageMeta`, or name the param differently (e.g. `~/catalog/[id].vue`).

**Comment by KOFI-GYIMAH** [comment]
> Alternatively, you can specify a different name in `definePageMeta`, or name the param differently (e.g. `~/catalog/[id].vue`).

Renaming one worked for me. Thanks
