### ISSUE TITLE
The Nuxt 3 build exports module "acorn" as a reference, symbolic link or how it's called in Win

### ISSUE THREAD

**Issue by sang1008** [nuxt/nuxt#21555]
### Environment

Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.5.2
- Nitro Version:    2.4.1
- Package Manager:  pnpm@8.6.0
- Builder:          vite
- User Config:      nitro, app, modules, css, i18n, swiper, vite
- Runtime Modules:  @nuxtjs/eslint-module@4.1.0, @nuxtjs/i18n@8.0.0-beta.12, nuxt-swiper@1.1.0
- Build Modules:    -

### Reproduction

Antfu's demo also has the same problem
https://github.com/antfu/nuxt-movies-demo.git

### Describe the bug

How do I tell Nuxt to export a module as a standard directory (if possible), or in the worse case, how do I copy a file in Windows droping references and making real files of them instead?

https://i.imgur.com/m6JlHNr.png

**Comment by danielroe** [comment]
What is the bug here? Can you explain more and give an example of what is not working for you?

**Comment by danielroe** [comment]
I see what you mean. Yes, on Windows we generate a different type of link as Windows lacks full link support.

I would recommend instead building your project in WSL and uploading from there if you are uploading to a Linux-based server. I think the `.tar` format would correctly package up the links.

**Comment by sang1008** [comment]
> 

It worked. Thank you！

**Comment by tojianghu** [comment]
@danielroe, I'm encountering the same issue. I'm developing on a Mac OS system, and when I run pnpm build, symbolic links are created in .output/server/node_modules, which work as expected. However, when I copy the .output folder to my debian server, these symbolic links are not recognized when I run index.mjs. I've seen your proposed solution, but I'm not entirely familiar with it. Could you please provide a more detailed explanation or perhaps suggest a more straightforward way to address this issue?
