### ISSUE TITLE
`parseQuery` and `stringifyQuery` option don't get applied using `nuxt.config.js`.

### ISSUE THREAD

**Issue by cadenzah** [nuxt/nuxt#21558]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.5.2
- Nitro Version:    2.4.1
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      router
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-lud3m5-kbud6a?file=nuxt.config.ts,app%2F__router.options.ts

### Describe the bug

Hi, I ran into this issue when I changed my repo's configuration structure. I previously put customized option settings for vue-router in `app/router.options.js`, and this worked okay. The option file was like below(simplified version for focusing on the issue):

```js
// app/router.options.js
import qs from 'qs';

export default {
    parseQuery: qs.parse,
    stringifyQuery: qs.stringify
};
```

And following [the official doc for nuxt](https://nuxt.com/docs/api/configuration/nuxt-config#router) says, I moved those options to `nuxt.config.js`like below:

```js
// nuxt.config.js
import qs from 'qs';

export default defineNuxtConfig({
    router: {
        options: {
            parseQuery: qs.parse,
            stringifyQuery: qs.stringify
        }
    }
});
...
```

But when I changed like this, the query parameters became a plain string, which was similar to [the issue I previously reported](https://github.com/nuxt/nuxt/issues/21305).

You can check this issue at reproduction repo above I linked. The repo doesn't work, but if you modify the source code into using `app/router.options.js` instead of `nuxt.config.js`'s `router.options`, you will find that the query parameter is passed properly.

### Additional context

I tested it on Nuxt `3.5.3`, and the same issue remains as well.

**Comment by danielroe** [comment]
The docs says:

> Note: Only JSON serializable options should be passed by nuxt config. For more control, you can use app/router.options.ts file.

Functions (like qs.parse) are not serializable to JSON. That is why it is not working. Instead you should set them in `app/router.options.ts` as the documentation recommends.

**Comment by enzonzee** [comment]
The solution with `app/router.options.ts` is not working on current nuxt version.
