### ISSUE TITLE
Caching or freezing component in layout when use routing

### ISSUE THREAD

**Issue by zeronerorgb** [nuxt/nuxt#21565]
### Describe the feature

For example we have file tree like this
components/
    - menu.vue
page/
    type/
         - [type].vue
layouts/
    - type.vue

we have a menu component that placed in layout and contain NuxtLink to page/type/[type] page with other parameter value. menu component has a onMounted hook and when we navigate through links evety time onMounted will fired. Page not change, layout not change. how can we freeze a menu component and layout when navigate like this?

minimal example here
https://stackblitz.com/edit/github-gypnfa?file=layouts%2Ftype.vue
    

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Your layout is created every time as it is _within_ your page, so it doesn't persist between page navigations.
