### ISSUE TITLE
`NuxtClientFallback` seems to have a memory issue!

### ISSUE THREAD

**Issue by RodrigoProjects** [nuxt/nuxt#21569]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.18.1`
- Nuxt Version:     `3.5.3`
- Nitro Version:    `2.4.1`
- Package Manager:  `pnpm@8.6.2`
- Builder:          `vite`
- User Config:      `ssr`, `app`, `hooks`, `css`, `devServer`, `modules`, `devtools`, `imports`, `inlineSSRStyles`, `vite`, `nitro`, `components`, `apollo`, `pinia`, `i18n`, `runtimeConfig`
- Runtime Modules:  `@company/module-proxy@1.0.0`, `@company/apollo@5.0.0-alpha.6`, `@company/module-tenant@1.0.0`, `@company/module-logger@1.0.0`, `@pinia/nuxt@0.4.8`, `@vueuse/nuxt@9.12.0`, `@pinia/nuxt@0.4.8`, `@nuxtjs/i18n@8.0.0-beta.12`, `@nuxt/devtools@0.6.0-28111142.42a69d2`
- Build Modules:    `-`

### Reproduction

This problem is very easily to mimic.

Adding this to the `nuxt.config.ts`:
```json
experimental: {
    clientFallback: true
  },
```

And using `NuxtClientFallback` with a big subtree inside it as the default slot! 

### Describe the bug

Memory ramps to extreme values: 

![image](https://github.com/nuxt/nuxt/assets/47485736/ab8270eb-dc2b-4edf-b422-4790ca4a593e)

Before and after of the removing `NuxtClientFallback` and the experimental flag in `nuxt.config.ts` (blue line).

### Additional context

This feature `NuxtClientFallback` is essential for my application because we can't serve a 500 page just because one of our 35 modules failed, we just discard that module and load the rest of the page (we use an headless CMS).

Happy to help on anything if you guide me on the right path!

**Comment by huang-julien** [comment]
strange i couldn't reproduce the issue even by running an K6 test on my own local build 🤔  , i'd be glad if you could provide a small reproduction.

**Comment by RodrigoProjects** [comment]
I forgot to mention I am using nitro cluster preset, could be relevant! 

Will do my best to reproduce but it could take a while to make the exact same logical flow

**Comment by agracia-foticos** [comment]
Same Issue!!!! we are implemented nuxtClientFallback and the memory rises until the server is goes down
