### ISSUE TITLE
wrong useFetch into error.vue crashes the app

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/nuxt#21562]
### Environment

https://stackblitz.com/edit/nuxt-starter-yk1sbd

### Reproduction

In error.vue there is an useFetch call with error.

If we push the button in each refresh page, in second round, the app crases.

![image](https://github.com/nuxt/nuxt/assets/77386602/533ddb8e-11b7-49f1-ab41-4115bc676a67)

### Describe the bug

In error.vue there is an useFetch call with error.

If we push the button in each refresh page, in second round, the app crases.

![image](https://github.com/nuxt/nuxt/assets/77386602/533ddb8e-11b7-49f1-ab41-4115bc676a67)

**Comment by danielroe** [comment]
Before accessing `error.statusMessage` you should first check whether `error` is set.

The issue is that you are overriding `props.error` with your new `error` object, which overrides the prop in the template.

```diff
  const props = defineProps({
    error: Object,
  });

- const { data: products, error } = await useFetch(`/api/test2`);
+ const { data: products, error2 } = await useFetch(`/api/test2`);
```
