### ISSUE TITLE
Config routeRules with runtimeConfig values

### ISSUE THREAD

**Issue by devonik** [nuxt/nuxt#21567]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.14.0
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  pnpm@8.6.0
- Builder:          vite
- User Config:      runtimeConfig, typescript, css, build, hooks, vite, modules, gtm, devtools
- Runtime Modules:  @zadigetvoltaire/nuxt-gtm@0.0.13, nuxt-i18n-data@0.1.19, nuxt-vuetify-error-handler@1.1.0, nuxt-delay-hydration@1.2.0, (), @heiland/nuxt-hei-buttons@1.0.3, @pinia/nuxt@0.4.11, @nuxtjs/i18n@8.0.0-beta.12
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-p8jezy?file=nuxt.config.ts,package.json

1. Run npm run build
2. Run `NUXT_REDIRECT_URL="test" node .output/server/index.mjs` to overwrite runtimeConfig
3. Go to page /register (redirection is set in routeRules)

### Describe the bug

When I add the routeRules in nuxt.config.ts like this it works 
```
routeRules: {
        // Homepage pre-rendered at build time
        '/agb': { prerender: true },
        '/datasecurity': { prerender: true },
        '/imprint': { prerender: true },
        '/cs/api/**': { proxy: `${process.env.REDIRECT_URL}/api/**` },
        // Redirect router until there migrated
        '/register': { redirect: `${process.env.REDIRECT_URL}/register` },
      },
```
But in my case I want to use runtimeConfig for the values (wich I can set via NUXT_REDIRECT_URL in production). 

To make this working I explored the hook nitro:config. The docu page https://nuxt.com/docs/api/advanced/hooks#nitro-app-hooks-runtime-server-side describe `Called before initializing Nitro, allowing customization of Nitro's configuration.` so I tried it and local it works fine. But in a production build when I start the app via `NUXT_REDIRECT_URL="test" node .output/server/index.mjs` the /route redirection seems to be endless and the browser says "Too many redirects"

**Comment by danielroe** [comment]
Your nuxt config is evaluated in dev and before building but it is not evaluated at runtime. So defining route rules there that are dependent on environment variables will not affect your runtime app.

**Comment by devonik** [comment]
Okey got it. Maybe i will handle the redirect pages i another way for my case like redirect definition after build time. But my biggest problem is the proxy setting. I really like that we can define a proxy rule as a one liner now 👍  but the value is changing in the environment. Process.env is ignored after the app is built :( Do you know any other smart solution?

**Comment by danielroe** [comment]
You could add your own proxy middleware within a nitro plugin, for example? You'd have access to runtimeconfig there.

**Comment by devonik** [comment]
Do you mean a nitro plugin with this https://nitro.unjs.io/guide/plugins or a nuxt server middleware described here https://nuxt.com/docs/guide/directory-structure/server#server-middleware ?

**Comment by danielroe** [comment]
I meant a nitro plugin. You could likely also do this within a nitro API route.

**Comment by devonik** [comment]
Can you explain me your idea ?

**Comment by or2e** [comment]
[devonik](https://github.com/devonik)

You can also use the built-in proxy helpers: https://github.com/unjs/h3#proxy
The implementation in nitro https://github.com/unjs/nitro/blob/main/src/runtime/route-rules.ts#L36

**Comment by devonik** [comment]
@or2e Thanks for the recommendation and the built in proxy in route rules is a awesome feature. I already used it (See first post) and it worked but the problem for this ticket was that I am using a runtime environment variable for the request url and any environment variable in route rules will be statically written while build time.
So I had the staging environment url used in prod environment as example

**Comment by or2e** [comment]
@devonik 

Yeah, I know what you mean.
You can create your own server plugin like you already did, use there `runtimeConfig` and `sendProxy/proxyRequest` instead of manually calling `ofetch`

**Comment by jcpascolo** [comment]
Same problem here! It would be awesome that routeRules "re-render" that values in runtime. In my case, we create a docker image with our nuxt-server and, depends on which environment we want to deploy, the proxy is different. What bother me a little bit is that it worked on "proxy" options of nuxt2. I hope we can use it that way. Meanwhile, I would try @devonik solution. Thanks a lot for share it!!

**Comment by or2e** [comment]
@jcpascolo 
On stage/prod env we use nginx to proxy the api

**Comment by devonik** [comment]
> that it worked on "proxy" options of nuxt2

I thought exactly the same. I used also the proxy setting in nuxt 2 nuxt.config

**Comment by barnabas-szekeres** [comment]
I need to address this issue. We build Docker images and want to set the proxy URL based on the environment. In Nuxt 2, we could set the proxy URL at runtime, but in Nuxt 3, there’s no elegant way to do this. I hope this issue won’t be closed with the aforementioned workaround. :(

**Comment by oemer-aran** [comment]
I think it would be really helpful, if there would be a copy-paste example for a proxy in nuxt 3 that requires runtimeConfig. Especially if it worked in Nuxt 2 with no issues. 
It's really not easy to know where to place the proxy:
*  `nuxt.config.ts`? 
* `server/middleware`?  
* `server/plugins`? 
* `server/api`? 


This is a common use case which deserves a bit more guidance.

**Comment by devonik** [comment]
Someone should make a new issue for that since this post is closed long time ago
> This is a common use case which deserves a bit more guidance.
I like that one and feel the same. Sometimes it's a bit of self exploration. But still awesome how much possibilities we just have

**Comment by devonik** [comment]
@oemer-aran had the same issue now on another project i migrated nuxt2 to nuxt3. I like your solution, thanks for sharing! Looks clean and works smooth. I needed to proxy cause 2 apis so i just added 2 server middlewares

**Comment by AbdallahAlhaddad** [comment]
There is a proxy utility function in `h3` that you can use. Here’s an example:

```ts
// file: /api/images/[...slug].ts

export default defineEventHandler(event => {
  const path = event.context.params.slug
  return proxyRequest(event, `${useRuntimeConfig().public.IMAGES_ENDPOINT}/${path}`)
})
```
Although I haven’t tested it for edge cases, you may need to tweak its options.

@pi0 
@danielroe 
Do you have any recommendations?
