### ISSUE TITLE
clearError only runs in vue part, not in node

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/nuxt#21560]
### Environment

https://stackblitz.com/edit/nuxt-starter-m7bh2f

### Reproduction

When i launch the app, it goes to '/' that produces an error.

In error page we return to /ok page, and the error disapears.

But if you push CTRL + F5 many times, raises 
![image](https://github.com/nuxt/nuxt/assets/77386602/7a8ec245-aa93-4920-b308-6e459d1692b0)

caught SyntaxError: Invalid or unexpected token

In our project (not in stackblitz),  when we clearError we can navigate correctly, but when we refresh the page with F5, the error is cached.

### Describe the bug

It seems that clearError only clear error in vue part, not in node part

**Comment by danielroe** [comment]
Yes, clicking `clearError` on the client is not going to affect the server. The error should not persist on the server beyond the request.

I can't reproduce the issue with pressing `Ctrl-F5` that you describe.

**Comment by agracia-foticos** [comment]
https://youtu.be/HRLZ0fs926M I can reproduce all times in stackblitz :(

**Comment by danielroe** [comment]
It seems like it might be a browser/Vue DevTools issue?

Can you try in an incognito tab or a fresh browser profile?

**Comment by danielroe** [comment]
It may be a stackblitz limitation. Instead, use a fresh profile. Or try to reproduce locally.

**Comment by agracia-foticos** [comment]
We can reproduce it, sorry... i close the issue
