### ISSUE TITLE
child component lifecycle does not work properly when using await syntax in parent (nested routes)

### ISSUE THREAD

**Issue by Alireza1996Sh** [nuxt/nuxt#21579]
### Environment

Nuxi 3.5.3

RootDir: /home/projects/life-cycle-problem-on-nested-route
Nuxt project info:

------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/life-cycle-problem-on-nested-route

### Describe the bug

this is the routing structure of my nuxt app:
- pages
  - post-[id].vue
  - post-[id]
    - index.vue
    - images.vue

the correct unmounting lifecycle of the pages when changing route from id 1 to id 2 is this:
parent onBeforeUnmount 1
child onBeforeUnmount 1
child onUnmounted 1
parent onUnmounted 1

but when we are using await expression in parent route, lifecycle will be so strange (from id 1 to id 2 again):
child onBeforeUnmount 1
parent onBeforeUnmount 1
child onBeforeUnmount 2
child onUnmounted 1
child onUnmounted 2
parent onUnmounted 1

what does child with id 2 doing here?!
this behavior is not acceptable. right?

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/20798.
