### ISSUE TITLE
[Bug] Edge builds requires manual aliasing of libraries

### ISSUE THREAD

**Issue by Hebilicious** [nuxt/nuxt#21571]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.2.0`
- Nuxt Version:     `3.5.3`
- Nitro Version:    `2.4.1`
- Package Manager:  `pnpm@8.6.2`
- Builder:          `vite`
- User Config:      `extends`, `alias`, `modules`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-j91xsv?file=app.vue
https://github.com/Hebilicious/docus-edge-issues

### Describe the bug

When building for non-node environment, some packages who have an export map with multiple files are not resolved to the correct target environment, which causes un-necessary polyfilling and errors if there's a missing polyfill from un-env.

I initially encountered this bug and thought it was due to docus, so I opened an issue there https://github.com/nuxt-themes/docus/issues/921

After investigating, I found out this is more of a nuxt/nitro issue.

A workaround that works is to manually alias dependencies with multiple export to their correct version according to your `NITRO_PRESET`, but I assume that users shouldn't have to do this. Nuxi/Nuxt/Nitro should know that for our target we need to resolve browser dependencies and not node, and only fallback to node/unenv if necessary.

This is the [nanoid](https://github.com/ai/nanoid/blob/main/package.json) export map :
```
  "exports": {
    ".": {
      "browser": "./index.browser.js",
      "default": "./index.js"
    },
    "./async": {
      "browser": "./async/index.browser.js",
      "default": "./async/index.js"
    },
    "./non-secure": "./non-secure/index.js",
    "./package.json": "./package.json"
  },
  "browser": {
    "./index.js": "./index.browser.js",
    "./async/index.js": "./async/index.browser.js"
  },
  "react-native": {
    "./async/index.js": "./async/index.native.js"
  },
  ```
If it's not possible to automatically resolve this, we should have something in the docs that explains that this is needed for a lot of dependencies when building for non-node platforms.

FWIW vercel edge runtime recommendations [recommend](https://vercel.com/guides/library-sdk-compatible-with-vercel-edge-runtime-and-functions) to use nanoid, so I assume they do something like this when building Next.

**Comment by danielroe** [comment]
You're right, we should pick the right export conditions. I believe that @pi0 is already working on this ...

**Comment by Hebilicious** [comment]
Upstream tracking issue : https://github.com/unjs/nitro/issues/1371
