### ISSUE TITLE
"ssr" type unknown in nuxt config. Rendering mode documentation up-to-date? 

### ISSUE THREAD

**Issue by mklueh** [nuxt/nuxt#21577]
### Environment

- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  yarn@3.5.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

![image](https://github.com/nuxt/nuxt/assets/1553757/702d9023-ef12-4432-971d-291f5bf90a97)

### Describe the bug

The type 'ssr' of this line seems to be unknown

```
"/my/**": { ssr: true },
```

I assume, ssr does not exist anymore, as it also is not present anymore in the Nitro config

![image](https://github.com/nuxt/nuxt/assets/1553757/8d1d7582-e2ae-46fd-b61d-8d644e4a50ac)

But is still mentioned in the documentation

![image](https://github.com/nuxt/nuxt/assets/1553757/0dd5a3b4-eed2-403b-840e-be0b8e05316b)

https://nuxt.com/docs/guide/concepts/rendering#hybrid-rendering

While swr / isr seems to replace ssr in some way or another, I see no config property for client side rendering. 

Is client side now the default, if no rendering mode is specified?

**Comment by danielroe** [comment]
I can't reproduce: https://stackblitz.com/edit/github-gmf8rl. Maybe an issue with WebStorm? (You might need to update your version or install a newer version of typescript.)
