### ISSUE TITLE
Arabic pages paths with ":" is not working

### ISSUE THREAD

**Issue by ahmadqwer** [nuxt/nuxt#21582]
### Environment

- Operating System: Linux
- Node Version:     v18.12.1
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  npm@8.19.2
- Builder:          vite
- User Config:      srcDir, head, plugins, render, loading, dev, hooks, serverMiddleware, css
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

Nuxt 3
https://stackblitz.com/edit/github-hg6cqb

Vue 3 
https://stackblitz.com/edit/github-awuqxh

### Describe the bug

I am trying to add the below page to my project
`/خاص:جديد`
but the issue is that any page with a colon ":" and with arabic is not working.
as you can see in the reproduction i created multiple pages
`/profile:new`
`/خاص:جديد`
`/جديد`
and if you try to go the English page with a colon it is working fine, but when you try to go to the Arabic one its not working while going to the page without a colon is working fine. 

Note that I am using the pages:extend hook to extend the pages but it is not working too.

### Additional context

Note that i am using `a` tag because in my project i remove all JS created on client side so no "SPA" just vanilla js

**Comment by Hebilicious** [comment]
Hello @ahmadqwer, are you able to reproduce this issue with vite without Nuxt ?
https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter/tree/main?terminal=dev

**Comment by ahmadqwer** [comment]
Hello @Hebilicious, I have tried to reproduce it now and it seems the issue is there too.
https://stackblitz.com/edit/github-awuqxh

**Comment by Hebilicious** [comment]
> Hello @Hebilicious, I have tried to reproduce it now and it seems the issue is there too. [stackblitz.com/edit/github-awuqxh](https://stackblitz.com/edit/github-awuqxh)

Interesting. It might be a vite issue or a vue router issue... I wonder if this is just with arabic characters of this happens with all types of non latin script

**Comment by ahmadqwer** [comment]
> Interesting. It might be a vite issue or a vue router issue... I wonder if this is just with arabic characters or if this happens with all types of non latin script

yeah, i am trying to migrate my project from Nuxt 2 to Nuxt 3 and it works fine with Nuxt 2 !

**Comment by danielroe** [comment]
I wonder if the issue is that `:` indicates the start of a parameter in vue router, and this appears to work with non-Arabic characters as `:new` is a valid param name but doesn't work with arabic characters, perhaps because they fail a regexp for param name, or maybe because they are URI-encoded.
