### ISSUE TITLE
useFetch pending true by default when immediate set to false

### ISSUE THREAD

**Issue by dextersiah** [nuxt/nuxt#21581]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.15.0
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  npm@9.5.0
- Builder:          vite
- User Config:      app, vite, modules, css, typescript, postcss, runtimeConfig, viewport, image
- Runtime Modules:  @pinia/nuxt@0.4.11, @vueuse/nuxt@9.13.0, @nuxt/image-edge@1.0.0-28099902.2b6ed1c, nuxt-viewport@2.0.4, nuxt-typed-router@3.2.2, @nuxtjs/google-fonts@3.0.1
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-sbu2zi?file=pages%2Ftest.vue

### Describe the bug

When the `immediate` option is set to false on the `useFetch` composable. The `pending` value return true on initial load till the function has been executed. 

The ideal behavior would be the `pending` value would be false by default when `immediate` option is set to false.

**Comment by danielroe** [comment]
See https://github.com/nuxt/nuxt/issues/15714#issuecomment-1418959804 - and you can access a new `status` property in the next Nuxt release via https://github.com/nuxt/nuxt/pull/21045.
