### ISSUE TITLE
routes with swr = true always call renderer but serve old content

### ISSUE THREAD

**Issue by MiniDigger** [nuxt/nuxt#21584]
### Environment

- Operating System: Linux
- Node Version:     v16.17.0
- Nuxt Version:     3.5.2
- Nitro Version:    2.4.1
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      devtools, routeRules
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://codesandbox.io/p/sandbox/damp-fire-5t4dw7

make sure to view the preview with JS disabled (or just with view-source:)

### Describe the bug

I want to cache certain pages and make use of the swr function to refresh the cache in the background.

It appears that this functionality is completely broken. Setting swr to true makes the page always revalidate and even worse, always serves the first rendered content, which can be outdated by days or more.

In the repro you can observe that. TTL is set to 10 seconds, so I would expect to see the time change on the frontend every 10 seconds and only see a console log on the backend every 10 seconds.

what I actually see is that the backend renders the page on every call and the time in the frontend is never changed.

I have tested this in nitro itself using a normal cached event handler route thingy and the result is as I would expect, so I raised this issue on here instead upstream on nitro, but its possible that its still caused by nitro, my debugging wasnt conclusive, but it could have something to do with the lazy event handler.

**Comment by MiniDigger** [comment]
for referenze, the event handler I used for comparison, which works as expected

```
  nitroApp.router.use(
    "/dum/dum",
    cachedEventHandler(
      defineEventHandler(async (event) => {
        const res = new Date().toISOString();
        console.log("update", res);
        return res;
      }),
      {
        swr: true,
        maxAge: 10,
      }
    )
  );
```

**Comment by danielroe** [comment]
cc: @pi0

**Comment by danielroe** [comment]
Would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏

**Comment by everyx** [comment]
I have the same problem, it occurs when swr is enabled for `/**`

```js
    routeRules: {
      '/api/**': { cache: false, swr: false, headers: { 'Cache-Control': 'no-cache' } },
      '/**': { swr: true },
    },
```

related issues:

* https://github.com/unjs/nitro/issues/887
* https://github.com/unjs/nitro/issues/1200

**Comment by danielroe** [comment]
I'm closing this here as it's likely a Nitro issue. But if it only recurs with Nuxt, let me know and I'll reopen it here.
