### ISSUE TITLE
[Documentation Request] Extending the HTML template

### ISSUE THREAD

**Issue by Hebilicious** [nuxt/nuxt#21593]
### Describe the feature

How to extend the HTML template should be explained clearly in the docs, with example for the most common things.

We should document how to use the following Nitro hooks at the same time.

```ts
export default defineNitroPlugin((nitroApp) => {
  nitroApp.hooks.hook('render:html', (html, { event }) => { console.log({ html }) })
  nitroApp.hooks.hook('render:response', (response, { event }) => { console.log(response) })
})
```

This would fix https://github.com/nuxt/nuxt/issues/14195

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
A PR would be very welcome ❤️  🙏

**Comment by huang-julien** [comment]
BTW is it me or don't we have any type for nitro hooks ?

**Comment by danielroe** [comment]
They exist in nitro. Worth checking the cause if the types aren't flowing through

**Comment by Lehoczky** [comment]
> They exist in nitro. Worth checking the cause if the types aren't flowing through

There is a `TODO` comment for this in nitro's source code:

```ts
export interface NitroApp {
  h3App: H3App;
  router: Router;
  // TODO: Type hooks and allow extending
  hooks: Hookable;
  localCall: ReturnType<typeof createCall>;
  localFetch: ReturnType<typeof createLocalFetch>;
}
```

https://github.com/unjs/nitro/blob/88b4e11854c6a84c764bf64329f8e50a946b03b8/src/runtime/app.ts#L29
