### ISSUE TITLE
nuxt3如何按需引入element-plus组件

### ISSUE THREAD

**Issue by xzfnn** [nuxt/nuxt#21606]

**Comment by xzfnn** [comment]
![image](https://github.com/nuxt/nuxt/assets/58756175/782d02b1-58cc-4402-abaa-8204c03201f3)
我安装了两个插件，dans但是不知道在nuxt中应该怎么使用

**Comment by danielroe** [comment]
Would you provide a reproduction, please?

**Comment by xzfnn** [comment]
> 请提供[复制品](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)好吗？🙏
This is my project address. Could you please help me solve the problem of importing component libraries on demand? Thankyou！！！

https://github.com/xzfnn/nuxt3.git

**Comment by baixiaoyu2997** [comment]
你可以参考element-plus-nuxt-starter这个模板
please reference :https://github.com/element-plus/element-plus-nuxt-starter 
and
https://github.com/element-plus/element-plus-nuxt
