### ISSUE TITLE
Nuxt 3.5.3 | The requested module 'vue-demi' does not provide an export named 'hasInjectionContext'

### ISSUE THREAD

**Issue by mrniamster** [nuxt/nuxt#21607]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.11.0
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  npm@9.6.5
- Builder:          vite
- User Config:      routeRules, nitro, css, vite, postcss, app, modules, content, googleSignIn, runtimeConfig   
- Runtime Modules:  nuxt-vue3-google-signin@0.0.8, @pinia/nuxt@0.4.11, @nuxt/devtools@0.6.1, @nuxt/content@2.7.0
- Build Modules:    -

### Reproduction

This happens on upgrading the below packages to latest version.
When my pinia was upgrade to    "pinia": "^2.0.36", from    "pinia": "^2.1.4",
On searching found the issues gets resolves to changing the version to 2.0.x version of pinia, the idea was to report it, for future  compatibility.
 https://stackoverflow.com/questions/76295214/getting-500-internal-server-error-for-nuxt-3-and-pinia

Run ncu -u to upgrade package.json
PS C:\Users\n30kumar\Desktop\projects\yts> ncu -u
Upgrading C:\Users\kum\Desktop\projects\ts\package.json
[====================] 15/15 100%

 @nuxt/content      ^2.5.2  →    ^2.7.0
 @nuxt/devtools     ^0.4.0  →    ^0.6.1
 @picocss/pico      ^1.5.9  →   ^1.5.10
 @pinia/nuxt        ^0.4.8  →   ^0.4.11
 bootstrap          ^5.2.3  →    ^5.3.0
 nuxt               ^3.4.1  →    ^3.5.3
 sass              ^1.62.0  →   ^1.63.4
 sass-loader        13.2.2  →    13.3.2
 sweetalert2       ^11.7.3  →  ^11.7.12
 vue-sidebar-menu   ^5.2.5  →    ^5.2.8

### Describe the bug

![image](https://github.com/nuxt/nuxt/assets/52563039/8767cb87-419c-4116-b220-ca6480c03951)

### Additional context

I thinks is it due to Pina version ?

```[tasklist]
### Tasks
```

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by mrniamster** [comment]
Added Reproduction @danielroe

**Comment by mrniamster** [comment]
@danielroe  Similar  issue: https://stackoverflow.com/questions/76295214/getting-500-internal-server-error-for-nuxt-3-and-pinia

**Comment by mrniamster** [comment]
Update the issue got resolved, 
rm -rf node_modules/ 
$ npm install
npx nuxi upgrade --force
