### ISSUE TITLE
shallowRef

### ISSUE THREAD

**Issue by ziaadini** [nuxt/nuxt#21610]
### Describe the feature

add a config to asyncData to use shallowRef for returing data, this is usefull for better performance when dealing with nested objects

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/12406.
