### ISSUE TITLE
[Nitro/Unenv] cloudflare build has issues with unenv

### ISSUE THREAD

**Issue by Hebilicious** [nuxt/nuxt#21619]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.2.0`
- Nuxt Version:     `3.5.3`
- Nitro Version:    `2.4.1`
- Package Manager:  `pnpm@8.6.2`
- Builder:          `vite`
- User Config:      `devtools`, `nitro`, `alias`, `modules`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.7.2`
- Build Modules:    `-`

### Reproduction

Encountered it by trying the cloudflare_pages preset with the nuxt-openai vercel-labs/ai example : 

https://github.com/vercel-labs/ai/tree/main/examples/nuxt-openai

Full Error :

```
ℹ Building Nitro Server (preset: cloudflare-pages)                                                                                     nitro 1:01:56 AM

[nitro 1:01:58 AM]  ERROR  RollupError: "types" is not exported by "../../node_modules/.pnpm/unenv@1.5.1/node_modules/unenv/runtime/node/util/index.mjs", imported by ".nuxt/dist/server/server.mjs".


24: import Stream, { pipeline as pipeline$1, PassThrough } from "node:stream";
25: import { Buffer as Buffer$1 } from "node:buffer";
26: import { promisify, deprecate, types } from "node:util";
                                   ^
27: import { format } from "node:url";
28: import { isIP } from "node:net";


[1:01:58 AM]  ERROR  "types" is not exported by "../../node_modules/.pnpm/unenv@1.5.1/node_modules/unenv/runtime/node/util/index.mjs", imported by ".nuxt/dist/server/server.mjs".
```

### Describe the bug

When building some projects with the cloudflare presets, there's some build errors that can be worked around by explicitly installing `unenv` and aliasing some node deps to the cjs version of unenv.

```ts
import path from 'node:path'

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  nitro: {
    preset: 'cloudflare-pages'
  },
  alias: {
    'node:util': path.resolve(
      __dirname,
      'node_modules/unenv/runtime/node/util/index.cjs'
    ),
    'node:net': path.resolve(
      __dirname,
      'node_modules/unenv/runtime/node/net/index.cjs'
    )
  },
  modules: ['@nuxtjs/tailwindcss'],
  runtimeConfig: {
    openaiApiKey: ''
  }
})
```

### Additional context

This might be a pnpm issue due to the fact that this setup doesn't use `shamefully-hoist`. In this case this should be fixed with full pnpm support.

**Comment by Hebilicious** [comment]
Linking https://github.com/nuxt/nuxt/issues/14146 for reference as this is very likely the same issue https://github.com/nuxt/nuxt/issues/14146

**Comment by danielroe** [comment]
I can't reproduce when enabling shamefully-hoist. Let's track in https://github.com/nuxt/nuxt/issues/14146 instead.

**Comment by pi0** [comment]
Relevant fix: https://github.com/unjs/unenv/commit/cf45410

You need to update lockfile and node_modules to receive the fix.

**Comment by danielroe** [comment]
(The reason shamefully-hoist worked to solve the issue was that it prevented the outdated version of the package from being loaded.)
