### ISSUE TITLE
[Documentation Request] Environment config override 

### ISSUE THREAD

**Issue by Hebilicious** [nuxt/nuxt#21616]
### Describe the feature

This was implemented here https://github.com/nuxt/nuxt/pull/20329 and added in the [blog](https://nuxt.com/blog/v3-5), but is currently not documented.

```ts
export default defineNuxtConfig({
  $production: {
    routeRules: {
      '/**': { isr: true }
    }
  },
  $development: {
    //
  }
})
```

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by adityarawat1223** [comment]
Hey, I am new to open source can I work on this? and if the answer is yes can someone tell me how can I do that , sorry for the trouble I hope you all are having a great day .

**Comment by Hebilicious** [comment]
> Hey, I am new to open source can I work on this? and if the answer is yes can someone tell me how can I do that , sorry for the trouble I hope you all are having a great day .

Fork the Nuxt repo and add the documentation locally, then open a PR. 

Look at other merged documentation PRs to have a better idea : 
 
https://github.com/nuxt/nuxt/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Amerged+label%3Adocumentation

**Comment by adityarawat1223** [comment]
thank you can you assign me the issue

**Comment by adityarawat1223** [comment]
i am sorry if i am asking for too much spoon feeding but this code should go in  configuration.md  located in getting started right ?

**Comment by Hebilicious** [comment]
> i am sorry if i am asking for too much spoon feeding but i should define this code in configuration.md located in getting started right ? i am also not sure how to define it Can you please Guide me , Sorry for the trouble

That would be a good place for it yes 👍🏽
