### ISSUE TITLE
pageRef is undefined

### ISSUE THREAD

**Issue by Ictuer** [nuxt/nuxt#21624]
### Environment

- Operating System: Darwin
- Node Version:     v16.20.0
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      app, runtimeConfig, css, build, ssr, imports, modules, postcss
- Runtime Modules:  @pinia/nuxt@0.4.11
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-5bqvk9?file=pages%2Findex.vue

### Describe the bug

I can not access pageRef in nuxt-page component

**Comment by huang-julien** [comment]
Hi :wave: this feature has been merged for the next 3.6 release (or on current edge release). The PR has been merged (see https://github.com/nuxt/nuxt/pull/19403).
You'll be able to access to it with `page-ref` prop

**Comment by danielroe** [comment]
For now, you can try it out in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/).

Let me know if you experience any issues with it.

**Comment by patrickdorival** [comment]
Also noticed an issue with `pageRef`, I've experienced that it ignores the `defineExpose` exposed objects when there are any calls to `async` functions in the `setup` script.

`pageRef` will then attach the whole Component/Page instead of the defined objects that are being exposed.

**Comment by manniL** [comment]
@patrickdorival Please raise a new issue with a reproduction ☺️

**Comment by pichot** [comment]
@patrickdorival I've found that `defineExpose` works as expected as long as it is defined before any `async` functions.
