### ISSUE TITLE
Uncaught (in promise) ReferenceError: definePageMeta is not defined

### ISSUE THREAD

**Issue by TechAkayy** [nuxt/nuxt#21634]
### Environment

Nuxi 3.5.2                                                                                                                                                                          6:59:34 PM
                                                                                                                                                                                    6:59:34 PM
RootDir: /Users/techakayy/Projects/nuxt/happy-paws-with-nuxt-tailwindcss                                                                                                            6:59:34 PM
Nuxt project info: (copied to clipboard)                                                                                                                                            6:59:34 PM

------------------------------
- Operating System: Darwin
- Node Version:     v18.12.1
- Nuxt Version:     3.5.2
- Nitro Version:    2.4.1
- Package Manager:  npm@8.19.2
- Builder:          vite
- User Config:      runtimeConfig, modules, pinegrow, css, postcss, content
- Runtime Modules:  @pinegrow/nuxt-module@3.0.0-beta.142, nuxt-icon@0.4.1, @nuxt/devtools@0.4.6, @nuxt/content@2.6.0, @vueuse/nuxt@10.1.2
- Build Modules:    -
------------------------------

### Reproduction

![image](https://github.com/nuxt/nuxt/assets/73772701/6bafd66a-7ccc-4e70-b5fb-80e966597858)

### Describe the bug

Below is my index.vue page. 

It is very hard to produce a reproduction, as this happen very randomly during HMR updates - definePageMeta is not defined.

I was wondering as a workaround, is it possible to do `import {definePageMeta} from 'nuxt' ` to avoid this issue? 

![image](https://github.com/nuxt/nuxt/assets/73772701/96ac2fc8-f58e-4cd8-8e87-27c041974309)

**Comment by like0413** [comment]
`<script setup lang=“ts”>`->`<script setup>`

**Comment by TechAkayy** [comment]
@like0413 Ohh really, is that how it has to be used, or this is a workaround?

**Comment by like0413** [comment]
I made a mistake，try reloading vscode

**Comment by danielroe** [comment]
Hm. No, this should be auto-imported in any case. You could import from `#imports`. Let's track in https://github.com/nuxt/nuxt/issues/18897
