### ISSUE TITLE
Vue can't resolve components from parent nuxt layer if nested directories used.

### ISSUE THREAD

**Issue by megFree** [nuxt/nuxt#21648]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.5.2
- Nitro Version:    2.4.1
- Package Manager:  pnpm@8.6.2
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-mh8tz7?file=layers%2Fextended%2Fnuxt.config.ts

Steps to reproduce
1. `cd layers/extended`
2. `npm i`
3. `npm run dev`

![image](https://github.com/nuxt/nuxt/assets/53655495/b3d93232-94ef-4021-96cf-276d96ef917a)
![image](https://github.com/nuxt/nuxt/assets/53655495/75535a82-afe8-4d80-b50c-e40186a28e16)

### Describe the bug

I'm trying to make components library for large project via layer and wish to organize my components in a some way using directory structure. But I've faced a problem:  when I try to put my components into nested directory, e.g. `/components/base`, Vue failes to resolve these components. If I put components into root components directory all works fine. But this not a way I wanted to do my task.
I've tried to use nuxt.config's `imports.dirs`, but it didn't help.

Thank you guys for your work and for any future feedback on this.

**Comment by nicolaspayot** [comment]
Hi! Actually it works. It's just that if you have a component in a nested directory (within `/components`) then its name will be based on its own path directory and filename, with duplicate segments being removed.

Here your component's name will be: `BaseComponentsBaseTitle`.

![image](https://github.com/nuxt/nuxt/assets/463319/23caef85-55d5-48e9-a2ef-3d267369d9ce)

You can change this behaviour if needed but it's the default one (I believe):

https://nuxt.com/docs/guide/directory-structure/components#component-names

**Comment by megFree** [comment]
@nicolaspayot thank you! Actually, this works!

**Comment by takakimiyajima** [comment]
can we import it as BaseTitle?
if possible, I'd like to do it due to my implementation
