### ISSUE TITLE
Disabling automatic route generation by specifying a pattern

### ISSUE THREAD

**Issue by yaquawa** [nuxt/nuxt#21649]
### Describe the feature

I'd like to organize components that are only used on a specific page. 
For example, the components `TestHeader` and `TestContent` will only be used in `pages/test/index.vue`. 
Therefore, I would like to place the component files near the `index.vue` file. 
In this case, I will create a directory called `pages/test/__partials__` and place the components inside it.

Here is the directory structure:

```
pages
└── test
    ├── index.vue
    └── __partials__
        ├── TestHeader.vue
        └── TestContent.vue
```

However, this approach causes Nuxt to generate unused routes for `/test/__partials__/TestHeader` and `/test/__partials__/TestContent`. To prevent Nuxt from generating these routes, I wish I could specify a pattern in the `nuxt.config.ts` file.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Here's an example hook that might be useful: https://nuxt.com/docs/guide/going-further/custom-routing#using-the-pagesextend-hook

**Comment by yaquawa** [comment]
Thanks, @danielroe that helps.
I just tried setting the `ignore` option in `nuxt.config.js` like below, and it seems to be working. 
Does this approach yield the same results as the method you mentioned?

```js
{
  ignore: ['**/__partials__/*']
}
```

**Comment by NozomuIkuta** [comment]
@yaquawa 

`pages:extend` hook is namely for you to extend (modify) pages/routes, besides Nuxt's filesystem-based routing.
For example, you can add a route that just redirects to another route, or remove auto-detected routes as you want.

---

`ignore` option is to exclude files from Nuxt build process by glob patterns.
For example, changes on ignored files don't trigger rebuild the app on development mode.
You can find how the option works in more detail by searching `isIgnored` function in the Nuxt codebase.

Or, you would find  by seeing [the default glob patterns](https://nuxt.com/docs/api/configuration/nuxt-config#ignore). 

Note that this options is complementary to [`.nuxtignore` file](https://nuxt.com/docs/guide/directory-structure/nuxtignore#nuxt-ignore-file).

---

If I'm correct, ignoring components in `__partials__` directory is not what you want in this time.

**Comment by yaquawa** [comment]
Hi @NozomuIkuta Thank you for your explanation!
