### ISSUE TITLE
error.vue useSeoMeta with i18n is missing reactivity

### ISSUE THREAD

**Issue by tomsdob** [nuxt/nuxt#21677]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.12
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-nmhzwq-lxngab?file=pages%2Findex.vue

### Describe the bug

Switching locale in `/error.vue` updates the text inside of `<template>`, but does not update the title with `useSeoMeta()` if `useFetch()`/`useAsyncData()` inside the `/pages/index.vue` page are used asynchronously.

### Additional context

Can see the title of the website not changing by clicking on "Open in New Tab" on StackBlitz and clicking on locale links while using `await useAsyncData` or `await useFetch` in `/pages/index.vue`.

**Comment by danielroe** [comment]
cc: @harlan-zw

**Comment by harlan-zw** [comment]
Can confirm there is a bug.

I spent some time playing with this, I tested the general reactivity of useSeoMeta within error.vue and it seemed to work correctly. 

I tested the general reactivity of the i18n locale and that seemed to work correctly.

Combining both of them seems to cause the issue so will need to investigate further. Good to leave with me.

**Comment by harlan-zw** [comment]
I think the reproduction is stale. Anyway this may be fixed with latest Nuxt and Unhead 1.4

**Comment by danielroe** [comment]
Yes, it doesn't look the the reproduction exists any more (for this issue). Let's close as I think this was solved; if you are still experiencing this, please provide a reproduction and we'll reopen. 🙏

**Comment by tomsdob** [comment]
Sorry, something had happened with the reproduction. I updated it to match the issue: https://stackblitz.com/edit/github-nmhzwq-lxngab?file=pages%2Findex.vue
