### ISSUE TITLE
Module @nuxtjs/tailwindcss is disabled due to incompatibility issues

### ISSUE THREAD

**Issue by vahid-bagh3ri** [nuxt/nuxt#21679]
### Environment

  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
    Memory: 4.30 GB / 15.78 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.23.0-20220130.1630 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.51)
    Internet Explorer: 11.0.19041.1566

### Reproduction

https://stackblitz.com/edit/github-veimfs

### Describe the bug

I deployed the same version of my packages two days ago, but today it gives me this err:

 WARN  Module @nuxtjs/tailwindcss is disabled due to incompatibility issues: - [bridge] Nuxt bridge is required

I will send some important packages that I use:
```js
"dependencies": {
    "@tailwindcss/line-clamp": "^0.4.0",
    "nuxt": "^2.16.1",
    "vue": "^2.7.0",
    "webpack": "^4.46.0"
},
"devDependencies": {
    "@nuxtjs/tailwindcss": "^6.4.0",
    "postcss": "^8.4.5",
    "@babel/eslint-parser": "^7.16.3",
},
"resolutions": {
    "@nuxt/kit": "3.0.0-rc.13"
}

```

### Additional context

At this moment I can't use nuxt-bridge is there any other solution for it?

**Comment by vahid-bagh3ri** [comment]
Here is the reproduction.
https://stackblitz.com/edit/github-veimfs

**Comment by danielroe** [comment]
It looks like you need to install Nuxt Bridge: https://github.com/nuxt/bridge
