### ISSUE TITLE
public files cannot be accessed after build

### ISSUE THREAD

**Issue by stj8888** [nuxt/nuxt#21689]
### Environment

nuxt 3.5.3

### Reproduction

When Nuxt3 is developing, the images stored under public can be accessed normally, but when the bulid package is built and deployed, the newly added pictures in the production environment cannot be found, but the image has been saved under public, and you can click to see it in VSCODE, but the webpage reports an error
![image](https://github.com/nuxt/nuxt/assets/106759204/b13c34b7-8254-483b-aa2b-5a8347df6a4f)
![image](https://github.com/nuxt/nuxt/assets/106759204/dc8f2c20-6ff6-46da-9028-27a19ce36d02)
![Uploading image.png…]()

### Describe the bug

When Nuxt3 is developing, the images stored under public can be accessed normally, but when the bulid package is built and deployed, the newly added pictures in the production environment cannot be found, but the image has been saved under public, and you can click to see it in VSCODE, but the webpage reports an error
![image](https://github.com/nuxt/nuxt/assets/106759204/b13c34b7-8254-483b-aa2b-5a8347df6a4f)
![image](https://github.com/nuxt/nuxt/assets/106759204/dc8f2c20-6ff6-46da-9028-27a19ce36d02)
![image](https://github.com/nuxt/nuxt/assets/106759204/7dd3a0e3-0a31-4f17-af9b-d30ced07531d)

### Logs

```shell-script
When Nuxt3 is developing, the images stored under public can be accessed normally, but when the bulid package is built and deployed, the newly added pictures in the production environment cannot be found, but the image has been saved under public, and you can click to see it in VSCODE, but the webpage reports an error
```

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by stj8888** [comment]
> Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

Thanks, it has been solved according to your suggestion

**Comment by jnsys** [comment]
> > Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
> 
> Thanks, it has been solved according to your suggestion

how you solved the issue? can you explain in details?

**Comment by stj8888** [comment]
> > > Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
> > 
> > 
> > Thanks, it has been solved according to your suggestion
> 
> how you solved the issue? can you explain in details?

https://github.com/nuxt/nuxt/issues/21692 please follow the link

**Comment by stj8888** [comment]
> > > Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
> > 
> > 
> > Thanks, it has been solved according to your suggestion
> 
> how you solved the issue? can you explain in details?

please follow the link https://github.com/nuxt/nuxt/issues/21689

**Comment by stj8888** [comment]
> > > Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
> > 
> > 
> > Thanks, it has been solved according to your suggestion
> 
> how you solved the issue? can you explain in details?

 please follow the #15779

**Comment by AlanRaza66** [comment]
Hi !
I had the same issue.
If the file is an image, we can use NuxtImg and it will work.

But how can i display an uploaded pdf? (it works on local but not in prod)
