### ISSUE TITLE
My useFetch to my server/api not executing

### ISSUE THREAD

**Issue by DavidAbou** [nuxt/nuxt#21687]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.16.0
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  npm@9.7.1
- Builder:          vite
- User Config:      app, css, modules, postcss, devtools
- Runtime Modules:  nuxt-icon@0.4.1
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-hbbnvs?file=server%2Finfo.ts

### Describe the bug

I have an error :
```
Uncaught (in promise) TypeError: data.value is null
    NuxtJS 11
[profile.vue:26:4](http://localhost:3000/_nuxt/pages/profile.vue)
    NuxtJS 10
    InterpretGeneratorResume self-hosted:1359
    AsyncFunctionNext self-hosted:756
    (Asynchrone : async)
    <anonyme> NuxtJS
```
Here is my line 24 to 28:
```
24 onMounted(async () => {
25     data.value = await getUserInfo()
26     notes.value = await getUserNotes(data.value.login)
27     picture.value = await getUserPicture(data.value.login)
28 })
```

I try to reproduce it in the provided stackblitz but it works in it and not in my project. But when I use useFetch("/api/info") in my getUserInfo function called in onMounted when click on reload page button, my useFetch not fetching my file at my server/api/info. I know that because i try a simple console.log in it and i see nothing. But when my code is updated by modification in it (hmr update), its work very well.

### Additional context

This error occurs only when reload page (click on reload button in browser)

**Comment by Nemure231** [comment]
Do not use axios, nuxt provide $fetch to allow you fetching data in server folder.

ref: https://nuxt.com/docs/getting-started/data-fetching#fetch

Also, you are using nuxt which is SSR framework, your fetch will auto excecute without wrap with onMounted, just write like this, and you will get the result.

![image](https://github.com/nuxt/nuxt/assets/49015080/74134d55-bbd2-4527-a84d-7977dc0f9622)

A i know, Onmounted can be works only in CSR (client-side rendering), if you want to use onMounted, you need to define route rules, SSR: false. in here: https://nuxt.com/docs/guide/concepts/rendering#hybrid-rendering

 But if you use CSR, its can remove the SSR benefits.

**Comment by danielroe** [comment]
You reproduction seems to be working fine: https://stackblitz.com/edit/github-hbbnvs?file=app.vue

Note that you should use `$fetch` and not `useFetch` in your `getInfo` and `getOtherInfo` handler functions. `useFetch` is a composable meant to be called in setup function, not used to programmatically fetch data.

**Comment by DavidAbou** [comment]
> Do not use axios, nuxt provide $fetch to allow you fetching data in server folder.
> 
> ref: https://nuxt.com/docs/getting-started/data-fetching#fetch
> 
> Also, you are using nuxt which is SSR framework, your fetch will auto excecute without onMounted, just write like this, and you will get the result.
> 
> ![image](https://user-images.githubusercontent.com/49015080/247806448-74134d55-bbd2-4527-a84d-7977dc0f9622.png)
> 
> As i know, Onmounted can be works only in CSR (client-side rendering), if you want to use onMounted, you need to define route rules, SSR: false. in here: https://nuxt.com/docs/guide/concepts/rendering#hybrid-rendering
> 
> But if you use CSR only, its can remove the SSR benefits.

My request is not jsonplaceholder (just for example) so my request is blocked by CORS when I do just one fetch or useFetch, I need to use axios in the server/api/info to get info without CORS restrictions.

**Comment by britzdylan** [comment]
> You reproduction seems to be working fine: https://stackblitz.com/edit/github-hbbnvs?file=app.vue
> 
> Note that you should use `$fetch` and not `useFetch` in your `getInfo` and `getOtherInfo` handler functions. `useFetch` is a composable meant to be called in setup function, not used to programmatically fetch data.

This is not very obvious in the docs unfortunately
