### ISSUE TITLE
Can't import types like `Ref` from `#imports`

### ISSUE THREAD

**Issue by yaquawa** [nuxt/nuxt#21684]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.5.3`
- Nitro Version:    `2.5.0`
- Package Manager:  `pnpm@8.6.2`
- Builder:          `vite`
- User Config:      `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

This will result in an error because the type `Ref` is not found in `#imports`.
```js
import { ref, type Ref } from '#imports'
```

or is this the correct approach..? (by the way I have set `autoImport: false` in `nuxt.config.ts`)
Actually, importing from 'vue' seems clearer to me than importing from '#imports'.
```js
import { ref, type Ref } from 'vue'
```

**Comment by Hebilicious** [comment]
In your case it doesn't matter, both the `Ref` and `ref` types are from vue.
You can look in your `.nuxt` directory to see the `#imports` in a `type/imports.d.ts` file.

You will see

```ts
declare global {
  // @ts-ignore
  export type { Component, ComponentPublicInstance, ComputedRef, InjectionKey, PropType, Ref, VNode } from 'vue'
}
```

and

```ts
  const ref: typeof import('vue')['ref']
```

**Comment by yaquawa** [comment]
@Hebilicious Thanks! Have you tried in your editor? Here is mine.

<img width="755" alt="image" src="https://github.com/nuxt/nuxt/assets/13927101/7c9dc758-2c5a-4122-ac18-6a572350991a">

**Comment by Hebilicious** [comment]
> @Hebilicious Thanks! Have you tried in your editor? Here is mine.
> 
> <img alt="image" width="755" src="https://user-images.githubusercontent.com/13927101/248138053-7c9dc758-2c5a-4122-ac18-6a572350991a.png">

I can reproduce it indeed.

**Comment by danielroe** [comment]
cc: @antfu
