### ISSUE TITLE
I'm using nuxt 3 to create a web app where users can upload files. Now I store them in a public folder, and I assume they will be available to users in that folder Other files like favicon get serviced but not uploaded files, I get a 404 error, during yarn dev it seems to work fine, but not after building with yarn build. This is a screenshot of the folder that can access the Favicon .ico, but not the newly uploaded screenshots. How can I mitigate this?

### ISSUE THREAD

**Issue by stj8888** [nuxt/nuxt#21692]
### Environment

nuxt 3.5.3

### Reproduction

I'm using nuxt 3 to create a web app where users can upload files. Now I store them in a public folder, and I assume they will be available to users in that folder
Other files like favicon get serviced but not uploaded files, I get a 404 error, during yarn dev it seems to work fine, but not after building with yarn build. This is a screenshot of the folder that can access the Favicon .ico, but not the newly uploaded screenshots. How can I mitigate this?

### Describe the bug

I'm using nuxt 3 to create a web app where users can upload files. Now I store them in a public folder, and I assume they will be available to users in that folder
Other files like favicon get serviced but not uploaded files, I get a 404 error, during yarn dev it seems to work fine, but not after building with yarn build. This is a screenshot of the folder that can access the Favicon .ico, but not the newly uploaded screenshots. How can I mitigate this?

**Comment by LarchLiu** [comment]
check on this
https://github.com/nuxt/nuxt/issues/15779#issuecomment-1397418353

btw: pls shorten the title, it's too long. 😱

**Comment by danielroe** [comment]
let's track in your other issue https://github.com/nuxt/nuxt/issues/21689.

**Comment by stj8888** [comment]
> 检查这个[#15779（评论）](https://github.com/nuxt/nuxt/issues/15779#issuecomment-1397418353)
> 
> 顺便说一句：请缩短标题，太长了。😱

Thanks, it has been solved according to your suggestion
