### ISSUE TITLE
emit HMR events when templates are updated

### ISSUE THREAD

**Issue by brendonmatos** [nuxt/nuxt#21690]
### Describe the feature

I am working on a Nuxt module that programmatically creates pages based on a specific configuration. Whenever I make changes to these configurations, I would like to receive instant feedback. I have managed to address this issue by implementing the following code:

```js
export default defineNuxtModule((options, nuxt) => {
  // define de "pages extender"
  extendPages(async (pages) => {
    const config = fs.read('...')
    await generatePagesBasedWithConfig(pages, config)
    await nuxt.callHook('admin:updated')
  })

  // watch for a config change
  nuxt.hook('builder:watch', async (event, path) => {
    if (isConfig(path)) {
      await updateTemplates({
        filter: (template) => template.filename === 'routes.mjs'
      })
    }
  })

  // plugin to reload when a page is updated
  addVitePlugin({
    name: 'config-hmr-plugin',
    configureServer(server) {
      server.ws.on('connection', () => {
        nuxt.hook('admin:updated', () => {
          setTimeout(() => {
            server.ws.send({
              type: 'full-reload'
            })
          }, 1000)
        })
      })
    }
  })
})
```

Although the current implementation works, I believe that it could be a more straightforward and efficient way to replace or modify a page. I would love to be working on this implementation if accepted this suggestion.

Please, let me know if I missed something.

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Great solution! Let's try to improve the `updateTemplates` utility to trigger HMR when it's called.

**Comment by brendonmatos** [comment]
Is the hook `builder:generateApp` the right one to use when we call to update just the templates? I'm understanding that this hook does more things than that. Please correct me if I'm wrong.

What do you think about receiving which templates have been changed on return of the hook and then "trigger" the HMR? 

```ts
export async function updateTemplates (options?: { filter?: (template: ResolvedNuxtTemplate<any>) => boolean }) {

  const updatedTemplates = await tryUseNuxt()?.hooks.callHook('builder:generateTemplates', options)

  await triggerHMR(updatedTemplates)

  return updatedTemplates
}
```

Would that be a nice approach, creating a hook just to generate templates? Do you see a better way of doing that?

**Comment by danielroe** [comment]
Does this work?

```ts
await updateTemplates({
  filter: template => template.filename === 'routes.mjs'
})
```

**Comment by brendonmatos** [comment]
@danielroe It works. Actually, I'm already calling from a watch of the config file:

```ts
nuxt.hook('builder:watch', async (event, path) => {
  if (isConfig(path)) {
    await updateTemplates({
      filter: (template) => template.filename === 'routes.mjs'
    })
  }
}) 
```

but calling `updateTemplates` from where I'm extending pages could lead to a loop. 

```ts
extendPages(async (pages) => {
  const config = fs.read('...')
  await generatePagesBasedWithConfig(pages, config)
  await nuxt.callHook('admin:updated')
  // await updateTemplates({ filter: ... 'routes.mjs' })
})
```

**Comment by brendonmatos** [comment]
No way that actually landed! 🚀 🚀  
You all are awesome

**Comment by sandros94** [comment]
I was trying to achieve something similar in Nuxt UI, so that during development of the module we could freely update the components themes (in [`src/theme`](https://github.com/nuxt/ui/tree/87a78289319520f8163495820081f61f6638df35/src/theme), which are then pulled from `#build/ui` within each component, eg: [UButton](https://github.com/nuxt/ui/blob/87a78289319520f8163495820081f61f6638df35/src/runtime/components/Button.vue#L3)).

I tried the following https://github.com/nuxt/ui/commit/46058f80046e867ef7ae9bb66cfd96d412607a8a, but it is not working. Although `builder:watch` is fired correctly and the filter is successful. It just reuses the old content to populate the template.

I'm still not sure if this is a bug/limitation or I'm just doing something wrong
