### ISSUE TITLE
`useCookie` value still remains after cookie expiration

### ISSUE THREAD

**Issue by trandaison** [nuxt/nuxt#21709]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.5.3`
- Nitro Version:    `2.4.1`
- Package Manager:  `pnpm@8.6.0`
- Builder:          `vite`
- User Config:      `ssr`, `plugins`, `css`, `vite`, `build`, `devtools`, `modules`, `routeRules`, `runtimeConfig`, `elementPlus`, `i18n`, `auth`, `pinia`, `veeValidate`
- Runtime Modules:  `@vueuse/nuxt@10.1.2`, `@pinia/nuxt@0.4.11`, `./modules/auth`, `@nuxtjs/i18n-edge@8.0.0-beta.12-28113576.7bc33c3`, `@element-plus/nuxt@1.0.5`, `@unocss/nuxt@0.52.7`, `nuxt-lodash@2.4.1`, `@vee-validate/nuxt@4.9.6`
- Build Modules:    `-`

### Reproduction

```ts
const testCookie = useCookie('test', { maxAge: 10 });
testCookie.value = 'some-value';

onMounted(() => {
  setTimeout(() => {
    console.log('testCookie', testCookie.value);
  }, 13000);
});
```

https://stackblitz.com/edit/github-mkuone?file=app.vue

### Describe the bug

* Actual result: `'some-value'` on console.
* Expected result: `undefined`.

Since the cookie has expired, accessing the cookie value should return `undefined` instead of the original value.

**Comment by MikeBellika** [comment]
Does anyone have an idea of how to implement this? Neither the client nor the server knows the expiration time of cookies. I guess it would be possible to store the expiration in a separate cookie, but that seems a bit overkill.

Might be possible to solve it in the specific case of short lived cookies that expire before a refresh. However this seems like quite a narrow use case and might introduce some inconsistency.

**Comment by c-schwan** [comment]
> Does anyone have an idea of how to implement this? Neither the client nor the server knows the expiration time of cookies. I guess it would be possible to store the expiration in a separate cookie, but that seems a bit overkill.
> 
> Might be possible to solve it in the specific case of short lived cookies that expire before a refresh. However this seems like quite a narrow use case and might introduce some inconsistency.

i solved my problem by adding a middleware

**Comment by trandaison** [comment]
@MikeBellika How about reading the cookie every time accessing the `cookie.value`? If the cookie has expired, it will return `undefined`.

**Comment by MikeBellika** [comment]
> @MikeBellika How about reading the cookie every time accessing the `cookie.value`? If the cookie has expired, it will return `undefined`.

Hmm yes that would work, but I'm not sure how to implement that. I have written some code that seems to work, but it's not that pretty and has some drawbacks:
```vue
<template>
  <div>
    {{ myCookie.value }}
  </div>
</template>
<script setup lang="ts">
function getCookie(name: string) {
  const value = process.server ? useRequestHeaders(['cookie']).cookie : `; ${document?.cookie}`;
  console.log(value)
  if (!value) return undefined
  const parts = value.split(`; ${name}=`);
  if (parts.length === 2) return parts.pop()?.split(';').shift();
}
class TestCookie {
  test = useCookie('test', { maxAge: 2 })
  set value(value: string | undefined | null) {
    this.test.value = value
  }
  get value() {
    return getCookie('test')
  }
}
const myCookie = new TestCookie()
myCookie.value = 'Super test'
onMounted(() => {
  setTimeout(() => {
    console.log('testCookie', myCookie.value);
  }, 3000);
});
</script>
```
However with this we need to also use `.value` in the template, which is not ideal. Maybe someone has a solution to this? Also I don't know what it does to reactivity.

Using computed doesn't seem to work either. The value is cached until the dependencies update, and it can't detect that `document.cookie` has updated.

**Comment by trandaison** [comment]
Perhaps `Ref` is not fit for this case 🤔

**Comment by trandaison** [comment]
@MikeBellika 
I have a workaround, it's working so far. I'm using a [`customRef` ](https://vuejs.org/api/reactivity-advanced.html#customref)

```ts
export function useSyncedCookie(name: string, options?: CookieOptions) {
  const cookie = useCookie(name, options);

  return customRef((track, trigger) => {
    return {
      get() {
        const value = getCookie(name);
        return value;
      },

      set(newValue) {
        cookie.value = newValue;
      },
    };
  });
}
```

By doing this, I think it is possible to update cookie flags (such as max-age, expires) when updating the cookie value, I also opened an issue here: https://github.com/nuxt/nuxt/issues/20652

**Comment by MikeBellika** [comment]
@trandaison Didn't know about customRef. That looks very promising!

**Comment by trandaison** [comment]
@MikeBellika Me either! 😂 I didn't known about it until today.

**Comment by jaegar-wolf** [comment]
Hi, I'm new to open source and I wanted to submit a PR for this issue but I don't really know how to do it properly, I've already fork the repo and make the solution I think that could resolve this issue, but I need some help for the submit.
Could someone help me ? Please

**Comment by gabrielmoris** [comment]
Did you try using `expires` instead of `maxage`?
```
 const expirationDate = new Date();
        expirationDate.setDate(expirationDate.getDate() + 1);
        const token = useCookie("token", { expires: expirationDate })
```

**Comment by vhovorun** [comment]
@MikeBellika Hey, have you managed some solution how to update cookie option?
