### ISSUE TITLE
Global Middleware isn't called after layout switching

### ISSUE THREAD

**Issue by c-schwan** [nuxt/nuxt#21701]
### Environment

Nuxt 3.6.0-28123897.e00bedda with Nitro 2.5.1-28123149.b926dd0                                                                                                                                                                    

### Reproduction

https://stackblitz.com/edit/middleware-nuxt

switching from Page index -> other (OK)
switching back form other -> index (Not called anymore)

### Describe the bug

Switching between pages with different layouts (client side) the middleware are not called anymore.

**Comment by Artem-Schander** [comment]
For me no middleware is getting called when navigating client side - after updating to nuxt 3.6
Maybe it's a different issue.. i thought I let this info here
