### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'html')

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/nuxt#21712]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.5.3`
- Nitro Version:    `2.5.1`
- Package Manager:  `npm@9.5.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

we have our app in production with nuxt 3.

we are reviewing the logs and we see some rare entry logs:

`TypeError: Cannot read properties of null (reading 'html')`

This error is throwed by app:error hook, but we dont know what is launching it :(

It's random error. The user agent that throw it are:

```
Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.133 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/103.0.5060.134 Safari/537.36
```

### Describe the bug

we have our app in production with nuxt 3.

we are reviewing the logs and we see some rare entry logs:

`TypeError: Cannot read properties of null (reading 'html')`

This error is throwed by app:error hook, but we dont know what is launching it :(

It's random error. The user agent that throw it are:

```
Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.133 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/103.0.5060.134 Safari/537.36
```

**Comment by danielroe** [comment]
Are you using server components?

**Comment by agracia-foticos** [comment]
> Are you using server components?

If you referer to "https://nuxt.com/docs/guide/directory-structure/components#server-components" we havent anyone
we havent any .client.vue file into /components folder

**Comment by danielroe** [comment]
In that case the error is not coming from anywhere in the _Nuxt_ codebase. Can you check your own code to see if you access a `.html` property on any object?

**Comment by agracia-foticos** [comment]
> In that case the error is not coming from anywhere in the _Nuxt_ codebase. Can you check your own code to see if you access a `.html` property on any object?

we have only one constructor.html in one page...  let's try to handle the object better to see if the error disappears
I keep you informed with news

**Comment by agracia-foticos** [comment]
the error of .html disapears handling better the object. i close the issue. thanks @danielroe
