### ISSUE TITLE
Nitro preset `netlify-edge` fails to build on Netlify

### ISSUE THREAD

**Issue by n-kort** [nuxt/nuxt#21719]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.16.1`
- Nuxt Version:     `3.6.0`
- Nitro Version:    `2.5.1`
- Package Manager:  `npm@9.5.1`
- Builder:          `vite`
- User Config:      `nitro`, `app`, `css`, `runtimeConfig`, `postcss`, `modules`, `i18n`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.12`, `@pinia/nuxt@0.4.11`
- Build Modules:    `-`

NPM modules
```json
{
  "devDependencies": {
    "@nuxt/postcss8": "^1.1.3",
    "@nuxtjs/i18n": "^8.0.0-beta.12",
    "@types/three": "^0.149.0",
    "autoprefixer": "^10.4.13",
    "nuxt": "^3.6.0",
    "postcss": "^8.4.21",
    "postcss-preset-env": "^8.0.1",
    "tailwindcss": "^3.3.1",
    "typescript": "^4.9.5",
    "vue-tsc": "^1.2.0"
  },
  "dependencies": {
    "@pinia/nuxt": "^0.4.11",
    "@types/masonry-layout": "^4.2.5",
    "@vueuse/core": "^9.13.0",
    "date-fns": "^2.29.3",
    "masonry-layout": "^4.2.2",
    "pinia": "^2.1.3",
    "swiper": "^9.1.1",
    "three": "^0.150.1"
  }
}
```

### Reproduction

Sadly difficult to reproduce. It happens with one particular project, but `npm run build` works fine locally. Just the deploy to Netlify that fails (default preset works fine in both cases).

Happy to share more configs, let me know what is relevant.

### Describe the bug

Trying to upgrade a project to `netlify-edge` server functions but the build step in Netlify always fails. Local build (and dev server) are fine, netlify says this:

```
4:26:56 PM: Edge Functions bundling                                       
4:26:56 PM: ────────────────────────────────────────────
4:26:56 PM: ​
4:26:56 PM: Packaging Edge Functions from .netlify/edge-functions directory:
4:26:56 PM:  - server
4:26:58 PM: TypeError: Cannot read properties of undefined (reading 'split')
4:26:58 PM:     at file:///opt/build/repo/.netlify/edge-functions/server/server.js:1:189193
4:26:58 PM: ​
4:26:58 PM: Bundling of edge function failed                              
4:26:58 PM: ────────────────────────────────────────────
```

### Additional context

Project was already up and running using Nuxt 3.4.x. When I tried 3.5.x almost nothing worked.. local dev server, local build, netlify build. The `dev` command just showed the nuxt loading page. 3.6.0 is solid, it's just the `netlify-edge` setting that seems to break stuff. Obviously there is some specific combination of factors at play in this project, any suggestions on where to look further would be appreciated!

**Comment by danielroe** [comment]
This is probably a Nitro issue - might be worth checking the code at that location in your `server.js`.

Could you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by n-kort** [comment]
Digging into that file, the error throws when trying `[oi, li] = h.versions.node.split(".").slice(0, 2).map((e) => Number.parseInt(e, 10))`, followed by `ui = "win32" === h.platform && (oi > 10 || (10 === oi && li >= 5))`. All minified... maybe `h` is `process`? 

Repro a little difficult... I have another project with almost the same setup that works fine 🤷‍♂️. I'll try removing packages here and there to try and narrow down.

**Comment by n-kort** [comment]
Update: downgrading from `@nuxtjs/i18n@8.0.0-beta.12` to `@nuxtjs/i18n@8.0.0-beta.10` fixed this.

Here's a [repro](https://github.com/n-kort/build-bugs) you can try to deploy to Netlify, the build will fail.

My fault for using a pre-release haha. I'll make an issue at [nuxt-modules](https://github.com/nuxt-modules/i18n).
