### ISSUE TITLE
Keep showing the spa-loading-template until page:finish

### ISSUE THREAD

**Issue by ploca14** [nuxt/nuxt#21721]
### Describe the feature

It would be nice to show the spa loading template until the 'page:finish' event. 

When using Nuxt with SSR turned off and using the spa-loading-template to show a loading screen, the loading screen disappears once the app mounts but the app isn't rendered yet. I believe because nuxt lazy loads the components that need to be rendered. This leads to a blank page once the app mounts and until the components are loaded. 

Other than that I love the new SPA loading template feature!

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by heartz66** [comment]
Additionally, setting `spaLoadingTemplate` to false does not disable the loading indiciator.

**Comment by timb-103** [comment]
This would be a good addition!

**Comment by danielroe** [comment]
Could you give me a sandbox example of the flash you're describing? 🙏

**Comment by ShantKevorkian** [comment]
@danielroe is the flashing issue fixed? I still encounter it in version 3.6.0 and 3.7.0 as @ucw provided the example

**Comment by umar13893** [comment]
Is this fixed? I am fetching data in components loading disappear and I see blank page for 2-4 seconds after animated Nuxt logo icon.

**Comment by Isa3v** [comment]
Hope to get a more permanent fix soon.

I've come up with a quick workaround where I create an HTML element using the content from `spaLoadingTemplate` before nuxtApp kicks in. It gets removed automatically with a slight delay after the `page:finish` hook fires.

https://github.com/Isa3v/nuxt-spa-loading-template

**Comment by kanhaic** [comment]
Any update on this? the workaround has issues with content loaded partially before spaloadingtemplate is removed.

**Comment by manniL** [comment]
@danielroe do you think this could be a 4.x change as it is "somewhat" breaking? 🤔

**Comment by danielroe** [comment]
I think it depends a bit on how we resolve it. I'd love to do so in a non-breaking way... if possible...

**Comment by sohaha** [comment]
You can either make a request, manually remove the spa-loading-template, or have a fade-out animation.

**Comment by nonehub** [comment]
Is the problem resolved?

**Comment by nonehub** [comment]
What do you think this way? 
https://stackoverflow.com/a/78472145/23524201

**Comment by Isa3v** [comment]
> What do you think this way? https://stackoverflow.com/a/78472145/23524201

I have already provided a link to a more better code
https://github.com/nuxt/nuxt/issues/21721#issuecomment-1780947313

_This workaround is still not the most elegant solution to this issue_

**Comment by kanhaic** [comment]
Is this planned to be fixed in v3 or v4?

**Comment by xjccc** [comment]
A simple way to show spa loading..

In `server/plugins/render-html.ts`

```
export default defineNitroPlugin((nitro) => {
  nitro.hooks.hook('render:html', async (html) => {
    const loadingHtml = `<div id="global_loading" class="wait-loading">
        <span class="loading-text">loading…</span>
    </div>`
    // add dom under body
    html.body.unshift(loadingHtml)
  })
})

```

In `plugins/loading.ts` control show/hide

```
export default defineNuxtPlugin({
  name: 'nuxt:page:loading',
  setup(nuxtApp) {},
  hooks: {
    'page:start': () => {
      const loading = document.getElementById('global_loading')
      if (loading) {
        loading.style.cssText = 'display:block;'
      }
    },
    'page:loading:end': () => {
      const loading = document.getElementById('global_loading')
      if (loading) {
        loading.style.cssText = 'display:none;'
      }
    }
  }
})

```

And you could add your global style in your app.vue

```
<style lang="less">
  @import '~/css/loading.less';
</style>
```

**Comment by mavyfaby** [comment]
any updates?

**Comment by globalkeyinfosolution** [comment]
any update please share with us

**Comment by SoCuul** [comment]
> I think it depends a bit on how we resolve it. I'd love to do so in a non-breaking way... if possible...

@danielroe this still seems to be an issue over a year later. i'm personally unable to even disable `spaLoadingTemplate` with the nuxt config option, as nothing changes.

**Comment by danielroe** [comment]
@SoCuul That sounds like a bug. Would you open a new issue with a reproduction.

**Comment by umar13893** [comment]
@danielroe in which version was this fixed?

**Comment by danielroe** [comment]
it is unreleased but it is scheduled for v3.15

**Comment by 29haspsfan** [comment]
Is this a resurfacing bug in 4.12?

**Comment by danielroe** [comment]
would you open a new issue with a reproduction?
