### ISSUE TITLE
Javascript Hooks Page Transition on Nuxt 3 does not work

### ISSUE THREAD

**Issue by Etidou** [nuxt/nuxt#21727]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v16.12.0
- Nuxt Version:     3.6.0
- Nitro Version:    2.5.1
- Package Manager:  npm@8.1.0
- Builder:          vite
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

[StackBlitz Link](https://stackblitz.com/edit/github-3c35yj?file=pages%2Findex.vue)
and
[Github Link](https://github.com/Etidou/Nuxt-Transition.git)

### Describe the bug

Hello, 

I got an error with the nuxt page transition and the javascript Hooks, I have the exact same code that in the doc here : https://nuxt.com/docs/getting-started/transitions#javascript-hooks

I don't really know what I'm doing wrong, if anyone does I'd love to know.

I've tried with console.log in every event and also without console.log but in neither case does it work.

The error seems to be related to Javascript Hooks because with :
```
export default defineNuxtConfig({
  app: {
    pageTransition: { name: 'page', mode: 'out-in' }
  },
})
```
it works perfectly but not with the javascript

### Additional context

![Error1](https://github.com/nuxt/nuxt/assets/45783736/259cebc3-0411-4d42-9218-ab419a0bddcf)
![error2](https://github.com/nuxt/nuxt/assets/45783736/ec7e10f7-6ce3-43ab-8a57-e969327a1213)

### Logs

```shell-script
[Vue warn]: Unhandled error during execution of transition hook 

Uncaught ReferenceError: oo_oo is not defined
    NuxtJS 50
```

**Comment by danielroe** [comment]
You need to add some CSS as well: see https://vuejs.org/guide/built-ins/transition.html#css-based-transitions.

**Comment by danielroe** [comment]
Reopened - it would be good to add this (or at least a link/notice) to the docs.

**Comment by Etidou** [comment]
I was silly I forgot about it.

But the error is still there, I can't see any console.log on the events

![Error3](https://github.com/nuxt/nuxt/assets/45783736/e75d3784-87cd-40ab-bc6c-7ad6d6078eed)

**Comment by Etidou** [comment]
So the docs example is still not working

**Comment by danielroe** [comment]
That error is not reproducible in the linked stackblitz.

**Comment by Etidou** [comment]
If you try with the Github Links I have provided ?

[Github Link](https://github.com/Etidou/Nuxt-Transition.git)

**Comment by danielroe** [comment]
It is also working fine once updated to 3.6.0: https://stackblitz.com/github/Etidou/Nuxt-Transition?file=package.json,nuxt.config.ts

**Comment by Etidou** [comment]
The error must therefore be linked to my local environment, as I always get the following error when I start the project on localhost

But yes it's working on the StackBlitz

**Comment by Etidou** [comment]
I got the exact same error on my Second Windows 10 Computer

```
- Operating System: Windows_NT
- Node Version:     v16.19.1
- Nuxt Version:     3.6.0
- Nitro Version:    2.5.1
- Package Manager:  npm@8.19.3
- Builder:          vite
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
```

**Comment by danielroe** [comment]
How are you getting the error? What steps?

**Comment by Etidou** [comment]
I get the error when I click the link

**Comment by Etidou** [comment]
https://github.com/nuxt/nuxt/assets/45783736/f269b1f0-a084-4b84-91e7-77d2bead2171

**Comment by Etidou** [comment]
The error is linked to my local dev env , because I have deployed with netlfify and the error disappeared.
So If you have some clue to avoid this on my dev env.

**Comment by danielroe** [comment]
Do you have Console Ninja installed, or something else that would intercept your logs? You could also try disabling Nuxt devtools, just in case?

**Comment by Etidou** [comment]
I don't know why, but the error was caused by the VScode Extension: Live Sass compiler, so it's been working perfectly ever since.

Thanks for your help!

**Comment by danielroe** [comment]
Great work debugging this! Glad to get to the bottom of it.
