### ISSUE TITLE
Allow scrollToTop page meta be dynamic with a function that receives the destination route

### ISSUE THREAD

**Issue by prashantpalikhe** [nuxt/nuxt#21738]
### Describe the feature

Currently, `scrollToTop` can only be a boolean. Making it a function allows users to turn the auto-scrolling on/off dynamically based on different route parameters.

For example, when you have a catch-all route and you need to handle scrolling yourself on a specific route subpath, this feature will allow us to do that. 

```TS
definePageMeta({
  scrollToTop: (route) => !route.path.startsWith('/handle-scroll-myself')
})
```

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
This sounds like a good idea to me 👍
