### ISSUE TITLE
CSS not included in dynamic pages (200.html) when statically generating/hosting. (3.6.0)

### ISSUE THREAD

**Issue by Parakoos** [nuxt/nuxt#21748]
### Environment

- Operating System: Windows_NT
- Node Version:     v16.15.0
- Nuxt Version:     3.6.0
- Nitro Version:    2.5.1
- Package Manager:  npm@8.5.5
- Builder:          vite
- User Config:      app, ssr, vite, nitro, css, plugins, components, dev, vue, modules, sourcemap, build, dir, typescript
- Runtime Modules:  @pinia/nuxt@^0.4.11, @vite-pwa/nuxt@^0.1.0, ()
- Build Modules:    -

### Reproduction

```
npx nuxi@latest init nuxt-repro-bad-200
cd nuxt-repro-bad-200
npm install
```

I also ran initalization of Firebase Static Hosting to be able to deploy to a server. It will redirect to the 200.html. The firebase.json file is as follows.

```json
{
  "hosting": {
    "public": ".output/public",
    "ignore": ["firebase.json", "**/.*", "**/node_modules/**"],
    "trailingSlash": false,
    "rewrites": [
      {
        "source": "**",
        "destination": "/200.html"
      }
    ]
  }
}
```

Next, make two pages, one that is statically generated and one that is skipped.

```html
<template>
  <!-- pages/pregen.vue -->
  <div class="big-red-box">
    I am statically generated at build time.
  </div>
</template>
```

```html
<template>
  <!-- pages/dynamic.vue -->
  <div class="big-red-box">
    I am dynamically generated by the client.
  </div>
</template>
```
```html
<template>
  <!-- app.vue -->
  <NuxtPage/>
</template>
```

Add a css file that defines the 'big-red-box' class.
```css
/* assets/styles/main.css */
.big-red-box {
  padding: 2rem;
  background: red;
  color: white;
}
```

Setup the config to 1) static generate 2) include the css 3) skip dynamic from generating
```js
// nuxt.config.ts
export default defineNuxtConfig({
  ssr: true, // Static generation
  css: ['~/assets/styles/main.css'], // Include the css file
  nitro: { prerender: { ignore: ['/dynamic'] } }, // Skip the dynamic page from generation
})
```

Include the workaround for the 200.html misdirection bug.
```js
// plugins/path.client.ts
export default defineNuxtPlugin({
  order: -25,
  setup(nuxtApp) {
    delete nuxtApp.payload.path
  },
})
```

Finally, build and deploy

```
npm run generate
firebase hosting:channgel:deploy bad-200
```

### Describe the bug

Going to the two pages show that the one that was dynamically generated does not have the required CSS while the statically generated page does.

![Capture](https://github.com/nuxt/nuxt/assets/3084827/1a0ce5a7-7506-4a06-8b07-850272331c1e)

### Additional context

This also affects included css from plugins such as Vuetify.

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by Parakoos** [comment]
I'm not really sure how to do that... I just uploaded all the code to [this repo](https://github.com/Parakoos/nuxt-3.6.0-bad-200-bug). Of course, you need to find somewhere to put the code once you deploy... If you want to see my deployed version (on Firebase Hosting) you can check out the two links:

* https://dev-phojo-app--bad-200-xqhmdfxp.web.app/pregen
* https://dev-phojo-app--bad-200-xqhmdfxp.web.app/dynamic/

**Comment by elishalon** [comment]
I'm having the same issue with 3.6. My SCSS file is not included in dynamic routes (ssr: false)

**Comment by ElYaiko** [comment]
Having same problem with `vuetify` on build, have to set `experimental.inlineSSRStyles: false` in nuxt.config

**Comment by stefanprobst** [comment]
there is also https://github.com/nuxt-modules/i18n/issues/2177 which may be related
