### ISSUE TITLE
Nuxt 3.6.0 Redirected to index.html and get 404 Page not found with ssr:false

### ISSUE THREAD

**Issue by kanhaic** [nuxt/nuxt#21743]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.6.0`
- Nitro Version:    `2.5.1`
- Package Manager:  `npm@9.6.6`
- Builder:          `vite`
- User Config:      `ssr`, `modules`, `app`, `i18n`, `alias`, `vite`, `css`, `postcss`, `build`
- Runtime Modules:  `@formkit/nuxt@1.0.0-beta.9-f64c966`, `@nuxtjs/i18n@8.0.0-beta.9`
- Build Modules:    `-`

### Reproduction

upgraded from nuxt 3.5.0 to nuxt 3.6.0  with ssr: false and tried to run it after `npm run generate` and run `npx servor .output/public`

tried the same by hosting on s3 bucket  and cloudfront - same issue

### Describe the bug

after running `nuxt generate` and runing `npx servor .output/public`. it gives an error index.html page not found.

### Additional context

![Screenshot 2023-06-24 at 4 01 27 PM](https://github.com/nuxt/nuxt/assets/1856476/23a39cf3-bd55-4a15-a93d-6476ccba0df2)

clicking on "Go Back Home" - shows the app.

nuxt.config.ts
```typescript
export default defineNuxtConfig({
  ...
  ssr: false,
  ...
});
```

package.json
```javascript
{
  ...
  "devDependencies": {
  ...
    "nuxt": "^3.6.0",
  ...
  }
  ...
}
```

### Logs

```
error caught during app initialization Error: Page not found: /index.html
    at xp (entry.74efe001.js:1:112405)
    at entry.74efe001.js:414:89339
    at r (entry.74efe001.js:1:92821)
    at Object.runWithContext (entry.74efe001.js:1:39687)
    at lU (entry.74efe001.js:1:92851)
    at Object.runWithContext (entry.74efe001.js:1:91498)
    at entry.74efe001.js:414:89317
    at entry.74efe001.js:5:20618
    at Object.runWithContext (entry.74efe001.js:1:39687)
    at $ (entry.74efe001.js:5:19663)
```
_No response_

**Comment by Yizack** [comment]
Same here, getting this issue too when hosting a static `ssr: false` app

**Comment by xh4528** [comment]
I also encountered the same problem

**Comment by danielroe** [comment]
This should be resolved with https://github.com/nuxt/nuxt/pull/21732

**Comment by XieHui1989** [comment]
> This should be resolved with #21732
> 
> In the mean time you can create the following plugin as `~/plugins/path.client.ts`:
> 
> ```ts
> export default defineNuxtPlugin({
>   order: -25,
>   setup (nuxtApp) {
>     delete nuxtApp.payload.path
>   }
> })
> ```

Thank you for repairing. Using this method is useful for me, and I look forward to future version updates

**Comment by trandaison** [comment]
@kanhaic How about setting Rewrites and redirects like this?

<img width="1342" alt="Screen Shot 2023-06-24 at 22 19 50" src="https://github.com/nuxt/nuxt/assets/13447235/49bf83fe-c461-439d-958a-3ce2f9662036">

I'm testing on aws amplify, Deploy without Git provider, I run the generate command on local, and upload the output folder. It's still working.

The same on S3.

<img width="807" alt="Screen Shot 2023-06-24 at 22 25 10" src="https://github.com/nuxt/nuxt/assets/13447235/6aa9dd7d-9e52-446d-8fe1-90bfcf06e051">

**Comment by kanhaic** [comment]
> This should be resolved with #21732
> 
> In the mean time you can create the following plugin as `~/plugins/path.client.ts`:
> 
> ```ts
> export default defineNuxtPlugin({
>   order: -25,
>   setup (nuxtApp) {
>     delete nuxtApp.payload.path
>   }
> })
> ```

This workaround worked well. Thank you.

**Comment by kanhaic** [comment]
> @kanhaic How about setting Rewrites and redirects like this?
> 
> <img alt="Screen Shot 2023-06-24 at 22 19 50" width="1342" src="https://user-images.githubusercontent.com/13447235/248491856-49bf83fe-c461-439d-958a-3ce2f9662036.png">
> I'm testing on aws amplify, Deploy without Git provider, I run the generate command on local, and upload the output folder. It's still working.
> 
> The same on S3.
> 
> <img alt="Screen Shot 2023-06-24 at 22 25 10" width="807" src="https://user-images.githubusercontent.com/13447235/248492235-6aa9dd7d-9e52-446d-8fe1-90bfcf06e051.png">

I will try it out and let you know. should this be done without the workaround?

**Comment by trandaison** [comment]
@kanhaic For me, the settings above works without any workaround.

**Comment by lfglopes** [comment]
I tried the workaround and the issue persists. Please note I'm using nuxt-i18n with the following config:

```
  i18n: {
    locales: [
      { code: 'pt-PT', iso: 'pt-PT', file: 'pt.js', name: 'Português' },
      { code: 'en-US', iso: 'en-US', file: 'en.js', name: 'English' }
    ],
    defaultLocale: 'pt-PT',
    strategy: 'prefix',
    lazy: true,
    langDir: 'lang/',
    detectBrowserLanguage: {
      useCookie: true,
      cookieKey: 'i18n_redirected'
    }
  },
```
