### ISSUE TITLE
Blank page when throwing an error from a `~/pages/[slug].vue` route parameter when hosting static generate

### ISSUE THREAD

**Issue by Yizack** [nuxt/nuxt#21749]
### Environment

- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.0
- Nitro Version:    2.5.1
- Package Manager:  pnpm@8.6.3
- Builder:          vite
- User Config:      nitro
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

Open https://stackblitz.com/edit/github-rdlsvu-s7ohlc, the `nuxt generate` command will run and for reproduction purposes, the static page will be served using `npx servor .output/public`, Write any invalid path or click on the error link and will see a blank page

![image](https://github.com/nuxt/nuxt/assets/16264115/ec1b4452-29ea-42da-9f3a-e7327c7b6304)

If I delete the `[slug].vue` file and run `nuxt generate` and  `npx servor .output/public` again, if any invalid path is entered, we see the normal error page of nuxt that should be shown instead of a blank page

![image](https://github.com/nuxt/nuxt/assets/16264115/3be82009-6f09-4d72-80f8-abbf2c163b05)

### Describe the bug

Let's say I want to use a page route parameter `slug` like this

```
pages/
--| [slug].vue
--| index.vue
--| ...
```

and inside the `[slug].vue` file I would like throw an error if the route parameter name doesn't exists within the properties of an object

```vue
<script setup>
const { params } = useRoute();

const obj = {
  foo: 'foo content',
  bar: 'bar content',
};

if (!obj[params.slug]) {
  throw createError({
    statusCode: 404,
    message: 'Page not found',
  });
}
</script>
```

The expected behavior would be to see the nuxt 404 error page when any invalid path is entered but I see a blank page instead.

### Additional context

The issue is only present when the app is generated statically, the routing works as expected except the error page. This doesn't happen in dev mode or when it's dynamically hosted

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by Yizack** [comment]
> Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

I did already 😄 but here's the stackblitz link again https://stackblitz.com/edit/github-rdlsvu-s7ohlc

**Comment by danielroe** [comment]
Ugh. Sorry, missed that!

**Comment by danielroe** [comment]
Two issues:

1. the nitro config in your nuxt.config should be wrapped in `prerender` (this is unrelated, but just an observation)
2. when you throw the error you must use `fatal: true` to force the error page

https://stackblitz.com/edit/github-rdlsvu-qymwyh?file=package.json,pages/%5Bslug%5D.vue,pnpm-lock.yaml

**Comment by Yizack** [comment]
Thank you so much for the help and for making nuxt the best framework ever! I'm kinda addicted to this framework
