### ISSUE TITLE
Error running nuxt locally when the builder webpack is enabled in config

### ISSUE THREAD

**Issue by jeanpierrecarvalho** [nuxt/nuxt#21746]
### Environment

- Operating System: Linux
- Node Version:     v16.19.1
- Nuxt Version:     3.6.0
- Nitro Version:    2.5.1
- Package Manager:  npm@8.19.3
- Builder:          webpack
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

To reproduce the error we need to add the following flag in nuxt.config:

`builder: "webpack"`

**StackBlitz:** [Click here](https://stackblitz.com/edit/github-ktzztp)

### Describe the bug

When the builder option it's changed in nuxt.config, the project is not running locally. 

`[1:55:07 PM]  ERROR  Cannot start nuxt:  Cannot destructure property 'bundle' of '(intermediate value)(intermediate value)(intermediate value)' as it is undefined.`

**Comment by jeanpierrecarvalho** [comment]
I think the message is not correct or is incomplete. I found that nuxt does not have the following package installed by default: [@nuxt/webpack-builder](https://www.npmjs.com/package/@nuxt/webpack-builder?activeTab=code)

![image](https://github.com/nuxt/nuxt/assets/90358872/a9c85e85-5b85-4efd-8ba0-bbba0f3d12ee)

**Comment by jeanpierrecarvalho** [comment]
After installed the [@nuxt/webpack-builder](https://www.npmjs.com/package/@nuxt/webpack-builder?activeTab=code) the problem was solved.

`npm i @nuxt/webpack-builder`

**Comment by danielroe** [comment]
Yes. You need to install this separately. But just as with `devtools`, we can offer to install it if the user enables the option.

**Comment by jeanpierrecarvalho** [comment]
@danielroe something like this?

`  if (options.devtools === true || (options.devtools && options.devtools.enabled !== false)) {
    if (await import('./features').then(r => r.ensurePackageInstalled(options.rootDir, '@nuxt/devtools', options.modulesDir))) {
      options._modules.push('@nuxt/devtools')
    } else {
      logger.warn('Failed to install `@nuxt/devtools`, please install it manually, or disable `devtools` in `nuxt.config`')
    }
  }`

**Comment by danielroe** [comment]
Exactly! Though it won't need to install the module.

**Comment by jeanpierrecarvalho** [comment]
@danielroe after adding the option to install the webpack-builder package to the core lib, I'm getting an error related to exports. 

![image](https://github.com/nuxt/nuxt/assets/90358872/ef12416a-4642-42ea-b2dc-f664f0a7122f)

I solved adding a ` "require": "./module.cjs"` in the webpack-builder package.json and the following snippet to the module.cjs

```
module.exports = function (...args) {
  return import('./dist/index.mjs').then(m => m.default.call(this, ...args))
}
```

the problem it's solved
