### ISSUE TITLE
Transforming JavaScript decorators to the configured target environment ("es2019") is not supported yet

### ISSUE THREAD

**Issue by brolnickij** [nuxt/nuxt#21756]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.20.0`
- Nuxt Version:     `3.6.0`
- Nitro Version:    `2.5.1`
- Package Manager:  `npm@9.4.2`
- Builder:          `vite`
- User Config:      `alias, nitro`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-jr6tha?file=server%2Fcontrollers%2Fdocument.controller.ts

### Describe the bug

Im experiencing an issue, where the TypeScript compiler fails to transform JavaScript decorators to the configured target environment ("es2019"). The exact error Im receiving is "Transforming JavaScript decorators to the configured target environment ("es2019") is not supported yet." This issue has only started recently, and previously the project was functioning correctly.

The project is configured to use TypeScript with experimental decorators enabled. Despite setting up the tsconfig.json correctly, Im encountering a transformation error when the TypeScript compiler tries to handle JavaScript decorators for the "es2019" environment.

### Additional context

The following configuration in `nuxt.config.ts` also doesnt work and begins to terminate the build with an error: `RollupError: Unexpected character '@' (Note that you need plugins to import files that are not JavaScript).`

```ts
export default defineNuxtConfig({
  nitro: {
    esbuild: {
      options: {
        target: 'esnext'
      }
    },
    typescript: {
      tsConfig: {
        compilerOptions: {
          experimentalDecorators: true
        }
      }
    }
  }
})
```

### Logs

```shell-script
ERROR  Error: Transform failed with 1 error: nitro 11:41:22 /home/projects/github-jr6tha/server/controllers/document.controller.ts:5:0: ERROR: Transforming JavaScript decorators to the configured target environment ("es2019") is not supported yet

Transforming JavaScript decorators to the configured target environment ("es2019") is not supported yet
```

**Comment by danielroe** [comment]
This is likely an upstream nitro issue (or configuration issue).

The correct way to set the nitro esbuild target here is:

```ts
export default defineNuxtConfig({
  nitro: {
    esbuild: {
      options: {
        target: 'esnext'
      }
    },
  },
})
```

You may also need to inject a rollup plugin in the nitro pipeline to transform the decorators, as there is another rollup plugin used by Nitro that clearly does not understand them. 

Maybe it might be worth adding a hook to allow manipulation of generated nitro rollup config upstream?

cc: @pi0

**Comment by NozomuIkuta** [comment]
The error message seems to come from esbuild ([ref](https://github.com/evanw/esbuild/blob/d17a12d417e29bcd235af854794f0f5bc0cffe4b/internal/js_parser/js_parser_lower.go#L144C1-L145)).

The phrase, `target: es2019`, seems to come from nitropack ([ref](https://github.com/unjs/nitro/commit/7d8505c59dde1a4a8dbea40bd3d8bdfedaa7de36)), whose commit has been released as nitropack v2.5.0, which in turn came to be used by Nuxt. I guess this is why @brolnickij says that

> This issue has only started recently, and previously the project was functioning correctly.

I checked the issue referred in the commit message (https://github.com/unjs/nitro/issues/189), but would be a wrong reference. @danielroe should know which issue was actual one.

---

The below is just for your information about recent esbuild situation.

esbuild author says [JavaScript (native) decorators came to be supposed as of esbuild v0.18.5](https://github.com/evanw/esbuild/issues/104#issuecomment-1597922979), but current stable Vite (v4.3.9) doesn't support the version.

Vite v4.4.0-beta supports the latest esbuild and your issue might be (partially) resolved once Nuxt bumps up Vite version to the next. Currently, Nuxt uses v4.3.9 ([ref](https://github.com/nuxt/nuxt/blob/5b7f52870c2b9c4fdb6e8f1449f33cd710e2ee6d/packages/vite/package.json#L59)).

I'm not sure about when inversify package will support JavaScript native decorators.

**Comment by evanw** [comment]
I saw this issue go by and figured I'd add a comment. The problem is likely that `experimentalDecorators: true` isn't making it to esbuild somehow, possibly because the `tsconfig.json` settings aren't being passed to esbuild. Transforming experimental decorators in TypeScript files has been supported by esbuild for quite a while now (since 2020). This transformation of experimental decorators is always done independent of the target, so setting a target of `es2019` shouldn't make a difference as long as experimental decorators are enabled. You can use the esbuild playground to compare what happens [when experimental decorators are disabled](https://esbuild.github.io/try/#dAAwLjE4LjgAewogIGxvYWRlcjogJ3RzJywKICB0YXJnZXQ6IFsnZXMyMDE5J10sCn0AQGluamVjdGFibGUoKQpleHBvcnQgY2xhc3MgRG9jdW1lbnRDb250cm9sbGVyIHsKfQ) to what happens [when experimental decorators are enabled](https://esbuild.github.io/try/#dAAwLjE4LjgAewogIGxvYWRlcjogJ3RzJywKICB0YXJnZXQ6IFsnZXMyMDE5J10sCiAgdHNjb25maWdSYXc6IHsKICAgIGNvbXBpbGVyT3B0aW9uczogewogICAgICBleHBlcmltZW50YWxEZWNvcmF0b3JzOiB0cnVlLAogICAgfSwKICB9LAp9AEBpbmplY3RhYmxlKCkKZXhwb3J0IGNsYXNzIERvY3VtZW50Q29udHJvbGxlciB7Cn0). Hope that helps.

**Comment by productdevbook** [comment]
> This is likely an upstream nitro issue (or configuration issue).
> 
> The correct way to set the nitro esbuild target here is:
> 
> ```ts
> export default defineNuxtConfig({
>   nitro: {
>     esbuild: {
>       options: {
>         target: 'esnext'
>       }
>     },
>   },
> })
> ```
> 
> You may also need to inject a rollup plugin in the nitro pipeline to transform the decorators, as there is another rollup plugin used by Nitro that clearly does not understand them.
> 
> Maybe it might be worth adding a hook to allow manipulation of generated nitro rollup config upstream?
> 
> cc: @pi0

`    "nitropack": "^2.5.2",` 

![image](https://github.com/nuxt/nuxt/assets/38668796/ef33638d-c2bc-408f-b794-53022db38cd2)

**Comment by brolnickij** [comment]
This was fixed in `nitropack@2.5.2`

For those who encounter the same issue:
- Run `npm list nitropack`. The version should be `2.5.2` or higher.
- Update your `nuxt.config.ts` with the following configuration:

```ts
export default defineNuxtConfig({
  nitro: {
    esbuild: {
      options: {
        tsconfigRaw: {
          compilerOptions: {
            experimentalDecorators: true
          }
        }
      }
    }
  }
})
```

---

@danielroe @NozomuIkuta @evanw Thank you so much for helping to solve this problem! <3

**Comment by gbyesiltas** [comment]
I have the issue with decorators causing `Unexpected character '@' (Note that you need plugins to import files that are not JavaScript).` on Nuxt 3.7.0 and the suggested solutions here don't help :/

**Comment by gbyesiltas** [comment]
> I have the issue with decorators causing `Unexpected character '@' (Note that you need plugins to import files that are not JavaScript).` on Nuxt 3.7.0 and the suggested solutions here don't help :/

Update here, adding
```
  esbuild: {
    tsconfigRaw: {},
  },
```
to the `vite` options solved the issue for me :D

**Comment by bbhxwl** [comment]
Transforming JavaScript decorators to the configured target environment ("es2019") is not supported yet

I use typeorm to prompt for this. How should I solve it?

**Comment by kaokei** [comment]
https://github.com/nuxt/nuxt/issues/21756#issuecomment-1727226259
@gbyesiltas Based on this answer, I will provide some additional information. There are two configuration options to choose from.
Option 1:
Configure in the tsconfig.json file:
```
"compilerOptions": {
    "experimentalDecorators": true,
  }
```
Additionally, configure in the nuxt.config.ts file:
```
vite: {
    esbuild: {
      tsconfigRaw: {},
    },
  },
```
Option 2:
Configure only in the nuxt.config.ts file:
```
  vite: {
    esbuild: {
      tsconfigRaw: {
        compilerOptions: {
          experimentalDecorators: true,
        },
      },
    },
  },
```
@danielroe @NozomuIkuta @productdevbook 

Why is it necessary to configure both tsconfig.json and nuxt.config.ts files in Option 1? Why doesn't esbuild automatically use the relevant configurations from the tsconfig.json file? After all, the configuration part in the nuxt.config.ts file, tsconfigRaw: {}, is empty, indicating that nothing is specified, and it seems that the final configurations are still read from the tsconfig.json file. I wonder if there is room for optimization in this aspect for Nuxt.
