### ISSUE TITLE
Prisma can't finding any environmental variables when Nuxt is in production

### ISSUE THREAD

**Issue by jeky1950** [nuxt/nuxt#21753]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v16.16.0
- Nuxt Version:     3.6.0
- Nitro Version:    2.5.1
- Package Manager:  npm@8.11.0
- Builder:          vite
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

I have created this repo [repo](https://github.com/jeky1950/nuxt-prisma) that recreates the issue. In summary if you load the DATABASE_URL from a .env, prisma wont find it when Nuxt is in production. 

### Describe the bug

When nuxt is in dev, prisma functions perfectly. However when I build the nuxt app, prisma can no longer find any of the environmental variables that were in the .env file and it fails.

### Logs

```shell-script
[nuxt] [request error] [unhandled] [500] 
Invalid `prisma.user.findMany()` invocation:


error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:10
   |
 9 |   provider = "sqlite"
10 |   url      = env("DATABASE_URL")
   |

Validation Error Count: 1
  at Rn.handleRequestError (C:\Users\petal\Desktop\Work\nuxt-prisma\.output\server\node_modules\@prisma\client\runtime\library.js:174:7601)
  at Rn.handleAndLogRequestError (C:\Users\petal\Desktop\Work\nuxt-prisma\.output\server\node_modules\@prisma\client\runtime\library.js:174:6754)
  at C:\Users\petal\Desktop\Work\nuxt-prisma\.output\server\node_modules\@prisma\client\runtime\library.js:177:3010
  at async C:\Users\petal\Desktop\Work\nuxt-prisma\.output\server\node_modules\@prisma\client\runtime\library.js:177:3225
  at async t._executeRequest (C:\Users\petal\Desktop\Work\nuxt-prisma\.output\server\node_modules\@prisma\client\runtime\library.js:177:11403)
  at async /C:/Users/petal/Desktop/Work/nuxt-prisma/.output/server/chunks/data.get.mjs:6:16
  at async Object.handler (/C:/Users/petal/Desktop/Work/nuxt-prisma/.output/server/node_modules/h3/dist/index.mjs:1285:19)
  at async toNodeHandle (/C:/Users/petal/Desktop/Work/nuxt-prisma/.output/server/node_modules/h3/dist/index.mjs:1360:7)
  at async ufetch (/C:/Users/petal/Desktop/Work/nuxt-prisma/.output/server/node_modules/unenv/runtime/fetch/index.mjs:9:17)
  at async $fetchRaw2 (/C:/Users/petal/Desktop/Work/nuxt-prisma/.output/server/node_modules/ofetch/dist/shared/ofetch.d438bb6f.mjs:206:26)
```

**Comment by danielroe** [comment]
You need to manually set those variables in production.

We are considering changing this within nitro.

**Comment by jeky1950** [comment]
Ok thank you.

Le dim. 25 juin 2023 à 15:10, Daniel Roe ***@***.***> a
écrit :

**Comment by luminous8** [comment]
How did you fixed it?
I don't understand the "You need to manually set those variables in production." and why the behaviour is different in dev/build mode

**Comment by jeky1950** [comment]
Hi, so I don't know what server you are deploying your Nuxt App but I
wanted to deploy on an Apache server on Ubuntu, for that you need to find
the /etc/environment file and there you paste in your environmental
variables from your .env file

**Comment by luminous8** [comment]
Thanks so much! I've deleted my comment because i learned how to fix it with pm2
Actually, reading this page helped https://nuxt.com/docs/guide/directory-structure/env (coming from nuxt 2 didn't make it easier)

**Comment by Zebnastien** [comment]
> Thanks so much! I've deleted my comment because i learned how to fix it with pm2 Actually, reading this page helped https://nuxt.com/docs/guide/directory-structure/env (coming from nuxt 2 didn't make it easier)

I am in the same trouble. Could you explain the origin of the problem? And you solution?

Thanks!

**Comment by jeky1950** [comment]
Hi Sébastien, so the assumption is that you will use nuxt in production
only in a server environment and on the server in is best practice to use
environment variables rather than to use a .env file like we do in
development.

Le mar. 19 sept. 2023 à 11:18, Sébastien MASSE ***@***.***> a
écrit :

**Comment by sigmaxf** [comment]
We're facing the exact same problem with AWS Amplify. Any ideas how to fix it?

**Comment by nagyszem22** [comment]
> We're facing the exact same problem with AWS Amplify. Any ideas how to fix it?

Hi there, did you manage to fix it by any chance? I'm facing the same issue

**Comment by mpratt** [comment]
> > We're facing the exact same problem with AWS Amplify. Any ideas how to fix it?
> 
> Hi there, did you manage to fix it by any chance? I'm facing the same issue

The way I managed to fix this in our case was to first define the url as a runtimeConfig in `nuxt.config.ts` something like this:
```js
runtimeConfig: {
    baseUrl: process.env.BASE_URL
  },
```
And then when initializing the prisma client we just pass the url

```js
const config = useRuntimeConfig();
const client = new PrismaClient({
    datasources: {
      db: {
        url: config.bdUrl
      }
    }
  });
```

This worked for us on amplify
