### ISSUE TITLE
manualChunks configuration does not take effect

### ISSUE THREAD

**Issue by wlinglinux** [nuxt/nuxt#21761]
### Environment

User Config:      srcDir, ssr, spaLoadingTemplate, app, runtimeConfig, css, modules, swiper, tailwindcss, vite, elementPlus, hooks, appDescription
- Runtime Modules:  @element-plus/nuxt@1.0.5, @nuxtjs/tailwindcss@6.8.0, nuxt-icons@3.2.1, nuxt-swiper@1.1.0, nuxt-lodash@2.5.0

### Reproduction

'vite:extendConfig'(config, { isClient }) {
      if (!isClient) return;
      config.build = defu(config.build, {
        chunkSizeWarningLimit: 500,
        rollupOptions: {
          output: {
            manualChunks: {
              'element-plus': ['element-plus'],
              'nuxt-lodash': ['nuxt-lodash'],
              'element-swiper': ['nuxt-swiper'],
              echarts: ['echarts'],
            },
          },
        },
      });
    },
manualChunks(id) {
            if (id.includes('node_modules')) {
              if (id.includes('element-plus')) {
                return 'element-plus'
              } else if (id.includes('echarts')) {
                return 'echarts'
              } else if (id.includes('nuxt-lodash')) {
                return 'lodash'
              } else if (id.includes('nuxt-swiper')) {
                return 'swiper'
              } else {
                return 'vendor'
              }
            }
          },

npx nuxi generate 

### Describe the bug

No split code
![image](https://github.com/nuxt/nuxt/assets/286261/0849e015-fcc7-43a3-bf0c-99cd3167d9bf)

**Comment by danielroe** [comment]
This seems to work fine:

```ts
import { defu } from 'defu'

export default defineNuxtConfig({
  hooks: {
    'vite:extendConfig' (config, { isClient }) {
      if (!isClient) { return }
      config.build = defu(config.build, {
        rollupOptions: {
          output: {
            manualChunks: {
              vue: ['vue']
            }
          }
        }
      })
    }
  }
})
```

![CleanShot 2023-06-25 at 16.57.43@2x.png](https://volta.s3.fr-par.scw.cloud/Clean_Shot_2023_06_25_at_16_57_43_2x_ac2843d38e.png)

If not, feel free to provide a reproduction and I will reopen.
