### ISSUE TITLE
Nuxt cloudflare-pages deployment fails

### ISSUE THREAD

**Issue by Aietes** [nuxt/nuxt#21768]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.16.1`
- Nuxt Version:     `3.6.0`
- Nitro Version:    `2.5.1`
- Package Manager:  `npm@9.5.1`
- Builder:          `vite`
- User Config:      `devtools`, `modules`, `apollo`
- Runtime Modules:  `@nuxtjs/apollo@5.0.0-alpha.6`
- Build Modules:    `-`

### Reproduction

https://github.com/floatingpixels/nuxt-apollo.git

### Describe the bug

I'm trying to deploy a Nuxt app to cloudflare pages. The app builds and runs fine locally, but the deployment to cloudflare pages fails. I'm using the Nuxt Apollo module, but I think the error might not be specific to the module, but has something to do with how Nuxt deploys on Cloudflare Pages. When deploying to Cloudflare pages I get the following error:

```
20:41:08.091 | [success] Server built in 1589ms
-- | --
20:41:08.108 | [success] [nitro] Generated public dist
20:41:08.168 | [info] [nitro] Building Nitro Server (preset: `cloudflare-pages`)
20:41:12.418 | (inject plugin) rollup-plugin-inject: failed to parse /opt/buildhome/repo/node_modules/graphql/jsutils/instanceOf.mjs. Consider restricting the plugin to particular files via options.include
20:41:12.421 | [error] [nitro] RollupError: Unexpected token (Note that you need plugins to import files that are not JavaScript)
20:41:12.422 |  
20:41:12.422 |  
20:41:12.422 | 10:   /* c8 ignore next 6 */
20:41:12.422 | 11:   // FIXME: https://github.com/graphql/graphql-js/issues/2317
20:41:12.423 | 12:   globalThis.process && globalThis.process.env.NODE_ENV === 'production'
20:41:12.423 | ^
20:41:12.423 | 13:     ? function instanceOf(value, constructor) {
20:41:12.423 | 14:         return value instanceof constructor;
20:41:12.424 | [error] Unexpected token (Note that you need plugins to import files that are not JavaScript)
20:41:12.425 | at error (node_modules/rollup/dist/es/shared/node-entry.js:2245:30)
20:41:12.425 | at Module.error (node_modules/rollup/dist/es/shared/node-entry.js:13572:16)
20:41:12.425 | at Module.tryParse (node_modules/rollup/dist/es/shared/node-entry.js:14298:25)
20:41:12.425 | at Module.setSource (node_modules/rollup/dist/es/shared/node-entry.js:13899:39)
20:41:12.425 | at ModuleLoader.addModuleSource (node_modules/rollup/dist/es/shared/node-entry.js:24422:20)
20:41:12.472 | Failed: Error while executing user command. Exited with error code: 1
20:41:12.482 | Failed: build command exited with code: 1
20:41:13.591 | Failed: error occurred while running build command
```

This implies the build works fine, but rollup-plugin-inject fails to parse the graphql module. I'm not sure how to solve this, I searched through issues here in nuxt, and also over at nuxt apollo, but I don't know how to go about fixing this. Any help would be appreciated!

**Comment by babyradJiri** [comment]
I have the exact same problem, only with vercel-edge preset.

**Comment by Hebilicious** [comment]
I'm not sure why, but it looks like globalThis is not supported with some nitro presets.
You can work around the issue  it by patching this line in `node_modules/graphql/jsutils/instanceOf.mjs`

`globalThis.process && globalThis.process.env.NODE_ENV === 'production'`

to this line : 

`process && process.env.NODE_ENV === 'production'`

It's easier if you use pnpm or yarn because of `patch` support. If you're using npm, use https://github.com/ds300/patch-package.

**Comment by Aietes** [comment]
Thank you for the hint! I tried your workaround, but somehow the patch is not being applied upstream. I'm still getting the same error on cloudflare pages, despite the patch.

**Comment by Hebilicious** [comment]
> Thank you for the hint! I tried your workaround, but the patch is not applied upstream. I'm using patch-package with npm. I'm still getting the same error on Cloudflare pages, despite the patch. The patch is applied in the local build, but when the nitro server is built on Cloudflare, it still uses the original library, and the same error message occurs.

Are you sure you have the postinstall script correctly setup ?  

If it's not working with npm, try using pnpm.

You could also fork the library or deploy manually with wrangler.

**Comment by babyradJiri** [comment]
Thank you @Hebilicious, I used yarn patch to replace the line and now it works!

**Comment by Aietes** [comment]
> Are you sure you have the postinstall script correctly setup ? Check the logs and make sure that the postinstall script is running. If it's not, try to manually run it as a part of the build command.
> 
> If it's not working with npm, try using pnpm.

@Hebilicious I switched to pnpm and created and committed a patch. Again, running the build locally applies the changes, the file in node_modules is changed. But running it on the server, the error continues to appear. I did not specifically configure a postinstall, is there something I should be doing manually? I see some postinstall in the logs, but I'm not sure if this is the right one: `nuxt-app@ postinstall /opt/buildhome/repo`

**Comment by Aietes** [comment]
It works using pnpm with its patch function. Thank you very much @Hebilicious !

**Comment by Hebilicious** [comment]
> The patch with the solution above lets the app compile, but when the app runs, it still has an issue to access `process` during run-time: `ReferenceError: Can't find variable: process`. We have now removed the check for the environment completely:
> 
> ```ts
> export const instanceOf = function instanceOf(value, constructor) {
>   return value instanceof constructor
> }
> ```
> 
> This workaround resolves the issue. For a real fix, maybe there is a way in nitro to ensure `globalThis` will work in node_modules. For a better workaround, is there a proper way to access `process` in nitro?

The issue is that you can't access process in cloudflare, as it's a node only api. Technically it should be poyfilled by unenv, but there's something weird going on. cc @pi0

**Comment by Aietes** [comment]
There are multiple issues in graphql/graphql-js that likely have the same root cause, but it seems there is a fix lined up in this PR graphql/graphql-js#3927. I guess the next release of graphql-js will fix this.

**Comment by Hebilicious** [comment]
> There are multiple issues in graphql/graphql-js that likely have the same root cause [graphql/graphql-js#3928](https://github.com/graphql/graphql-js/issues/3928), but it seems there is a fix lined up in this PR [graphql/graphql-js#3927](https://github.com/graphql/graphql-js/pull/3927). I guess the next release of graphql-js will fix this.

Great to hear there's an upstream PR already. 
I guess there's nothing to do on the Nuxt/Nitro side as they're using non standard syntax that vite doesn't like. 
Still I would expect unenv to catch that.

**Comment by phryneas** [comment]
@Hebilicious I believe this might actually be on the Nuxt side. 

The error message likely shows the unminified code - and the problem lies in the minified code. 
At least with vite, this transformation happens:
```diff
-globalThis.process.env.NODE_ENV
+globalThis."production"
```

Which would explain the error message of `"Unexpected token"`, which you would not get only because a variable name like `process` or `globalThis` would not exist.

**Comment by phryneas** [comment]
> You're saying that this error is caused by vite, and the fact that globalThis.process.env.NODE_ENV is not a syntax that vite supports by default ?
Yupp, I am saying that somewhere in your toolchain, you simply replace a string in your JavaScript without checking if it is a full expression - which is extremely dangerous, as the output of a simple string replacement on JavaScript code is not neccesarily JavaScript code.

I'm not a nuxt user myself, but if this only gets changed over at `graphql`, the next library is bound to ship code and break things again.

It seems that you are using the rollup replace plugin, which has a [`delimiters`](https://github.com/rollup/plugins/tree/master/packages/replace#delimiters) option that you can adjust to make sure this doesn't happen.  
Witout trying it, I believe changing the left delimiter from `\b` to `(?<!\.)\b` should help here, so you'd end up with
`delimiters: ['(?<!\\.)\\b', '\\b(?!\\.)']`

Maybe you could even bring that up with rollup? It seems like a sane default.

**Comment by Hebilicious** [comment]
> > You're saying that this error is caused by vite, and the fact that globalThis.process.env.NODE_ENV is not a syntax that vite supports by default ?
> 
> Yupp, I am saying that somewhere in your toolchain, you simply replace a string in your JavaScript without checking if it is a full expression - which is extremely dangerous, as the output of a simple string replacement on JavaScript code is not neccesarily JavaScript code.
> 
> I'm not a nuxt user myself, but if this only gets changed over at `graphql`, the next library is bound to ship code and break things again.
> 
> It seems that you are using the rollup replace plugin, which has a [`delimiters`](https://github.com/rollup/plugins/tree/master/packages/replace?rgh-link-date=2023-06-29T18%3A39%3A55Z#delimiters) option that you can adjust to make sure this doesn't happen. Witout trying it, I believe changing the left delimiter from `\b` to `(?<!\.)\b` should help here, so you'd end up with `delimiters: ['(?<!\\.)\\b', '\\b(?!\\.)']`
> 
> Maybe you could even bring that up with rollup? It seems like a sane default to see if there is not only a word-boundary, but also no dot preceeding that. 🙂

Thank you very much for the insight, I never digged into rollup plugins before so this is very helpful.

**Comment by ltroya-as** [comment]
@babyradJiri @Aietes Hi guys,

Can you please share what you did to bypass that error?

**Comment by Hebilicious** [comment]
> @babyradJiri @Aietes Hi guys,
> 
> Can you please share what you did to bypass that error?

You will have to fix this locally with a pnpm patch (or equivalent) until the next Nitro release is out (cc: @pi0)

**Comment by oritwoen** [comment]
You can also use `nitropack` update in `package.json` as in the example below.

Checked for operation and no problems for several weeks in production ;)

```json
    "pnpm": {
	"overrides": {
	    "nitropack": "npm:nitropack-edge@2.6.0-28142855.f0d0d91"
	}
    }
```

**Comment by alederzz** [comment]
> You can also use nitropack update in package.json as in the example below.

```
"pnpm": {
  "overrides": {
      "nitropack": "npm:nitropack-edge@2.6.0-28142855.f0d0d91"
   }
 }
```

Enviroment variables not work using this mehtod on Cloudflare Pages

```
export default defineNuxtConfig({
  runtimeConfig: {
    public: {
      apiUser: process.env.NUXT_PUBLIC_API_USER || '',
      apiPass: process.env.NUXT_PUBLIC_API_PASS || '',
    }
  },
...
```

**Comment by Hebilicious** [comment]
> > You can also use nitropack update in package.json as in the example below.
> 
> ```
> "pnpm": {
>   "overrides": {
>       "nitropack": "npm:nitropack-edge@2.6.0-28142855.f0d0d91"
>    }
>  }
> ```
> 
> Enviroment variables not work using this mehtod on Cloudflare Pages
> 
> ```
> export default defineNuxtConfig({
>   runtimeConfig: {
>     public: {
>       apiUser: process.env.NUXT_PUBLIC_API_USER || '',
>       apiPass: process.env.NUXT_PUBLIC_API_PASS || '',
>     }
>   },
> ...
> ```

We have a tracking issue https://github.com/unjs/nitro/issues/272 and an open PR https://github.com/unjs/nitro/pull/1318
