### ISSUE TITLE
ssr: false routes do not render with proper CSS

### ISSUE THREAD

**Issue by elishalon** [nuxt/nuxt#21760]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.6.0
- Nitro Version:    2.5.1
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Code is private

### Describe the bug

After upgrading from 3.53 to 3.6 all routes that are ssr: false (the default ssr is true) broke and looks like the CSS is not used. If changed to ssr: true, it works well but we need the specific routes to not render on the server.

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by elishalon** [comment]
It looks like the issue is with bootstrap 5 not being loaded.  using the following plugin code:

```
import bootstrap from 'bootstrap/dist/js/bootstrap.bundle'

export default defineNuxtPlugin(nuxtApp => {
    nuxtApp.provide('bootstrap', bootstrap)
})
```

will see if I can provide a reproduction

**Comment by elishalon** [comment]
OK, the issue is with the "css" prop in nuxt.config.ts - for some reason it is ignored when building the project. Here is the **nuxt.config.ts** from a demo project:

```
export default defineNuxtConfig({
  devtools: { enabled: true },
  routeRules: {    
    '/test/**': { ssr: false }
  },
  css: [
    '@/assets/css/main.scss'
  ],
  ssr: true
})

```

From what i'm seeing, the main.scss file is not compiled into the final dist

**Comment by danielroe** [comment]
@Achuttarsing That's a different issue. Do you have a reproduction?

**Comment by hichem-dahi** [comment]
I'm having the same issue.

**Environment:**
Operating System: Ubuntu 20.04.6 LTS
Node Version: v18.20.2
Nuxt Version: 3.11.2
Package Manager: npm@10.5.0
Builder: vite
User Config: -
Runtime Modules: -
Build Modules: -

**Reproduction**
https://stackblitz.com/~/github.com/hichem-dahi/trello-nuxt

Works fine for Firefox 126.0 (64-bit), doesn't work for Chrome 125.0.6422.60 (Official Build) (64-bit).
![Screenshot from 2024-05-28 12-14-45](https://github.com/nuxt/nuxt/assets/57720465/1e10e64f-bbc6-443c-960e-bbe268260b4f)
![Screenshot from 2024-05-28 12-15-21](https://github.com/nuxt/nuxt/assets/57720465/cfe37395-1c5c-4a60-aaae-3a37bc775d6d)

**Comment by danielroe** [comment]
Would you open a new issue with a minimal reproduction? 🙏

**Comment by hichem-dahi** [comment]
@danielroe Sure https://github.com/nuxt/nuxt/issues/27387
