### ISSUE TITLE
Disable nuxt 3 default preloader

### ISSUE THREAD

**Issue by davies-maina** [nuxt/nuxt#21769]
### Environment

- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.6.0
- Nitro Version:    2.5.1
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      typescript, ssr, modules, cookieControl, gtag, runtimeConfig, schemaOrg, vuefire, vite, css, app, build, nitro, extends, ogImage, sitemap, routeRules, security
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @pinia/nuxt@0.4.11, @dargmuesli/nuxt-cookie-control@5.10.2, nuxt-gtag@0.5.7, nuxt-vuefire@0.1.6, nuxt-security@0.13.1
- Build Modules:    -

### Reproduction

1. Deploy nuxt site to firebase hosting
2. Visit URL to see nuxt logo preloader briefly before seeing the website's content

### Describe the bug

I recently deployed my nuxt 3 site to firebase hosting. Visiting the URL, the nuxt logo is shown briefly before i actually see the contents of the website. Is there a way to disable the preloader? At least for production. I've searched far and wide in the docs to no avail.

**Comment by danielroe** [comment]
This should be resolved in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/), or in the next release.

Let me know if not and I'll reopen.

**Comment by rahulkumarsingh73690** [comment]
Not fixed #22028

**Comment by wirsindplural** [comment]
Could this be fixed by setting `spaLoadingTemplate: false` in nuxt.config?
https://v2.nuxt.com/releases/#img-srchttpsnuxtcomassetsdesign-kitlogoicon-greensvg-width16-height16-valigncenter--spa-loading-indicator
