### ISSUE TITLE
Styles aren't included on routes rendered client side

### ISSUE THREAD

**Issue by danielkellyio** [nuxt/nuxt#21773]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.6.0`
- Nitro Version:    `2.5.1`
- Package Manager:  `npm@9.5.1`
- Builder:          `vite`
- User Config:      `modules`, `routeRules`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.8.0`
- Build Modules:    `-`

### Reproduction

[Github Repo](https://github.com/danielkellyio/style-issue-reproduction)
[In Stackblitz](https://stackblitz.com/github/danielkellyio/style-issue-reproduction?file=nuxt.config.ts)

### Describe the bug

I'm using the @nuxtjs/tailwindcss module to style an app that has different rendering modes based on route.
Everything works great during development (`npm run dev`).

When I build the project with `npm run build` and serve it (both locally and on Netlify) the styles are broken on the client-side rendered pages when I visit them directly.

**Comment by danielroe** [comment]
This should be resolved in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/), or in the next release.

Let me know if not and I'll reopen.
