### ISSUE TITLE
"Page not found: /200.html" after upgrading from 3.5.3 to 3.6.0

### ISSUE THREAD

**Issue by some-user123** [nuxt/nuxt#21771]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.0
- Nitro Version:    2.5.1
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-s1sqyp?file=package.json,pages%2Findex.vue

### Describe the bug

I have a page that unconditionally forwards the user to another page.

I'm using `nuxt generate` and hosting the static output with a fallback to 200.html.

Calling that page that will forward, it shows the error "Page not found: /200.html". That doesn't make too much sense as the user did not use 200.html in the URL.

Same setup is working in Nuxt 3.5.3.

**Comment by danielroe** [comment]
This should be resolved in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/), or in the next release.

Let me know if not and I'll reopen.
