### ISSUE TITLE
Nested async-await composables break on the server when trying to do more than one

### ISSUE THREAD

**Issue by SebbeJohansson** [nuxt/nuxt#21772]
### Environment

Nuxi 3.6.0                                                                                                                                                   11:36:18 PM
                                                                                                                                                             11:36:20 PM
RootDir: /home/projects/nuxt-starter-qynmmz                                                                                                                  11:36:20 PM
Nuxt project info:                                                                                                                                           11:36:20 PM

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.0
- Nitro Version:    2.5.1
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                                                                  11:36:20 PM

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Reproduction

https://stackblitz.com/edit/nuxt-starter-qynmmz?file=composables%2FuseGameData.ts,composables%2FuseApi.ts,server%2Fapi%2F[slug].get.ts,pages%2Findex.vue,layouts%2Fdefault.vue,package-lock.json

### Describe the bug

This bug seems to happen when doing multiple nested async-awaited composable calls (doesn't seem to matter where they are run from). I am only 20% sure that this is an actual issue, and even less sure if its something that can be fixed. It might be that I am doing something wrong from a design point of view.

![image](https://github.com/nuxt/nuxt/assets/5083273/87419f59-1c70-49ff-8cc4-71d6cf01e7d4)

### Additional context

I have a bigger non stackblitz example with actual database connection that I can share, but its a bit harder to get that up and running.

### Logs

```shell-script
✔ Vite server hmr 47 files in 389.995ms                                                                                                                      11:35:19 PM
fetch from : /api/users                                                                                                                                      11:35:19 PM
guns response: { data: { value: [ 1234, 12345, 56456 ] } }                                                                                                   11:35:19 PM
[11:35:19 PM] Error: [nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables.
    at Module.useNuxtApp (file:///home/projects/nuxt-starter-qynmmz/node_modules/nuxt/dist/app/nuxt.js:174:13)
    at Module.useAsyncData (file:///home/projects/nuxt-starter-qynmmz/node_modules/nuxt/dist/app/composables/asyncData.js:26:38)
    at Module.useFetch (file:///home/projects/nuxt-starter-qynmmz/node_modules/nuxt/dist/app/composables/fetch.js:53:43)
    at Module.fetchFromApi (file:///home/projects/nuxt-starter-qynmmz/composables/useApi.ts:5:55)
    at createGameFromData (file:///home/projects/nuxt-starter-qynmmz/composables/useGameData.ts:8:56)
fetch from : /api/guns
```

**Comment by SebbeJohansson** [comment]
Related issues on github that i looked at before posting:
https://github.com/nuxt/nuxt/issues/12342
https://github.com/nuxt/nuxt/issues/18539
https://github.com/nuxt/nuxt/issues/14805
https://github.com/nuxt/nuxt/pull/20608

**Comment by danielroe** [comment]
This is documented behaviour: https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables.

You should in general either not create async composables (strongly recommended) or if you are using composables that rely on nuxt/vue instance being set, you must obtain the nuxtApp instance _before_ the first async operation, and then call them with `nuxtApp.runWithContext`.

**Comment by Noah-Ywh** [comment]
> You should in general either not create async composables (strongly recommended)

How should I understand this sentence? I often use `await useFetch` within async composables.

**Comment by danielroe** [comment]
@Noah-Ywh I would not advise it.
