### ISSUE TITLE
When ssr: false, baseURL is not set to _nuxt folder after build. Can not find /_nuxt/ files

### ISSUE THREAD

**Issue by trdln** [nuxt/nuxt#21780]
### Environment

```
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.0
- Nitro Version:    2.5.1
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      ssr, app
- Runtime Modules:  -
- Build Modules:    -
```
It repeats on 3.5.3 too.

### Reproduction

Project:
https://stackblitz.com/edit/github-llcwvz-tkssrz
Build with nuxt generate:
https://github-llcwvz-tkssrz.vercel.app/

### Describe the bug

When using `nuxt generate` with `ssr: false`, with different `baseURL`, entry files from` /_nuxt/` are lost. 
Modifying `app.buildAssetsDir` didn't help.

### Additional context

It may not depend on ssr

### Logs

```shell-script
Failed to load resource: the server responded with a status of 404 (Not Found)
entry.bbc96c86.css:1     
Failed to load resource: the server responded with a status of 404 (Not Found)
error-404.23f2309d.css:1     
Failed to load resource: the server responded with a status of 404 (Not Found)
error-404.10e2858c.js:1     
Failed to load resource: the server responded with a status of 404 (Not Found)
error-500.aa16ed4d.css:1     
Failed to load resource: the server responded with a status of 404 (Not Found)
error-500.55e9e483.js:1     
Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by danielroe** [comment]
This seems to be a provider-specific issue. (We likely need to respect `app.baseURL` in Vercel, and probably also in Netlify.)

**Comment by Nura-21** [comment]
> This seems to be a provider-specific issue. (We likely need to respect `app.baseURL` in Vercel, and probably also in Netlify.)
It appears in local network too. 
I have one folder with many nuxt projects. They are hosted under one host and port. There are IIS server routing to handle routing between projects, and such problem happened.

**Comment by Nura-21** [comment]
@danielroe Hi! Are there any ideas to solve somehow?

**Comment by jsunico** [comment]
I'm having similar problem with Cloudflare preset but mine's `SSR` is set to true. Happy to raise this as a new issue if this is a different scenario.

With nuxt config `baseURL` set to `/base/`, the static files are generated under `.output/public/_nuxt/`. This results to 404 when requesting files under `_nuxt` using wrangler dev. Setting the `buildAssetsDir` to `_nuxt` won't  generate files under `.output/public/base/_nuxt` instead it's still generated under `.output/public/nuxt`.

![image](https://github.com/nuxt/nuxt/assets/65151494/4dbc9280-02c5-44ad-84ff-c4ff757ab51c)

Changing `buildAssetsDir` to an absolute path (`/base/_nuxt/`) forces the generation of files under `.output/base/_nuxt`. However, when I launch the app, the `baseURL` is duplicated and becomes `/base/base/_nuxt/*.js`. This also results to 404.

![image](https://github.com/nuxt/nuxt/assets/65151494/e2057eca-b08b-4e0c-97c1-1e7ef73c1521)

Currently the workaround that worked for me is to override the `buildAssetsDir=_nuxt` runtime config of nitro. This avoids duplication of the `baseURL`.

```
  app: {
    baseURL: '/base/',
    buildAssetsDir: '/base/_nuxt/',
  },
  nitro: {
    runtimeConfig: {
      app: {
        buildAssetsDir: '_nuxt'
      }
    }
  }
```

Haven't tested in vercel but hopefully it works for you in the meantime @Nura-21 @danielroe.

**Comment by ayankcell** [comment]
Hi everyone, just wanna share a little bit in addition to @jsunico solution.  
In my case, it still gives 404 error when used along with [nuxt-swiper](https://nuxt.com/modules/swiper) and [@nuxtjs/google-fonts](https://nuxt.com/modules/google-fonts) modules.

In browser console:
![image](https://github.com/nuxt/nuxt/assets/13820957/668baab8-f659-4737-8aa4-74ed31e48828)

I just added another `baseURL` inside `nitro.runtimeConfig.app` like this.  Worked both in Vercel and Cloudflare Pages.
```
app:{
    baseURL:'/base',
    buildAssetsDir:'/base/_nuxt/'
  },
  nitro:{
    runtimeConfig:{
      app:{
        baseURL:'/base',
        buildAssetsDir: '_nuxt'
      }
    }
  },
```
Thank you
