### ISSUE TITLE
Failed to resolve import "fsevents" from "node_modules\.cache\vite\client\deps\chunk-S5GOWR7E.js?v=0348c6f3". Does the file exist?

### ISSUE THREAD

**Issue by facexyy** [nuxt/nuxt#21788]
### Environment

{
  "name": "nuxt-app",
  "private": true,
  "scripts": {
    "dev": "nuxt dev --open --mode dev",
    "build-test": "nuxt build --mode test",
    "build-production": "nuxt build --mode production",
    "start": "node .output/server/index.mjs"
  },
  "devDependencies": {
    "@element-plus/nuxt": "^1.0.5",
    "@nuxt/devtools": "latest",
    "@nuxtjs/tailwindcss": "^6.8.0",
    "@pinia/nuxt": "^0.4.11",
    "@types/node": "^18.16.18",
    "element-plus": "^2.3.7",
    "nuxt": "^3.6.0",
    "nuxt-icon": "^0.4.1",
    "pinia": "^2.1.4",
    "prettier": "2.8.8",
    "prettier-plugin-tailwindcss": "^0.3.0",
    "sass": "^1.63.6",
    "typescript": "latest"
  }
}

### Reproduction

import { loadEnv } from "vite";

interface VITE_ENV_CONFIG {
  VITE_API_HOST: string;
  VITE_PACK_ENV: string;
  VITE_PACK_URL: string;
}

const envScript = (process.env as any).npm_lifecycle_script.split(" ");
const envName = envScript[envScript.length - 1];
export const envData = loadEnv(envName, "env") as unknown as VITE_ENV_CONFIG;
console.log("当前环境：\n", envData.VITE_API_HOST);

### Describe the bug

When I use loadEnv, there will be an error ailed to resolve import "fsevents" from "node_modules\.cache\vite\client\deps\chunk-S5GOWR7E.js?v=0348c6f3". Does the file exist?, the error does not affect the operation, Please tell me how to modify it to get rid of this error, thank you very much!

**Comment by danielroe** [comment]
It feels like you are probably importing something that shouldn't be part of your Vue build (like a server dependency) into your app.

Would you provide a reproduction? 🙏

**Comment by facexyy** [comment]
@danielroe Happy for your reply, wait a minute, I create a repository, I just started to learn to use github, it can be slow.

**Comment by facexyy** [comment]
@danielroe I created a warehouse, thank you, this problem is not a fatal bug, but it has troubled me for a long time, if you have time to help me look, thank you again.

https://github.com/facexyy/opttask

**Comment by dammy001** [comment]
@facexyy i think you should externalize fsevents

**Comment by facexyy** [comment]
Thanks for the reply, I tried to add it, but the console still prints that error
![image](https://github.com/nuxt/nuxt/assets/125525983/05147418-f59c-4408-9e53-96d9b9a0578b)

**Comment by danielroe** [comment]
I would check to see where you are importing a dependency that relies on `fsevents`. It's probably a sign you are importing (for example) `@nuxt/kit` in your Vue app.
