### ISSUE TITLE
Fonts are not included in production build

### ISSUE THREAD

**Issue by thijsw** [nuxt/nuxt#21784]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.2.0
- Nuxt Version:     3.6.0
- Nitro Version:    2.5.1
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      $production, css, runtimeConfig, vue, typescript, modules, nitro, vite
- Runtime Modules:  @nuxtjs/google-fonts@3.0.1, nuxt-jsonld@2.0.8
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/custom-fonts?file=app.vue

Run

```
$ npm run build
$ node .output/server/index.mjs
```

### Describe the bug

When I reference a custom font in a CSS file, it works in the development environment. However, when I build the project for production, it appears that the font is not included in the production build.

Note this problem only occurs in the newest Nuxt release, version 3.6

**Comment by harlan-zw** [comment]
The import within the CSS is being transformed but the font file is not emitted within the .output.

![image](https://github.com/nuxt/nuxt/assets/5326365/51c96a13-2a4c-4892-b5a9-9966e9244e4c)

![image](https://github.com/nuxt/nuxt/assets/5326365/e267ff24-f7b2-4ab5-a792-936fee93a325)

This could point to a wider issue, possibly also images not being included in the build.

**Comment by danielroe** [comment]
This is an issue with the style inlining update which moves global css -> server only. For now you can work around it with the following configuration:

```ts
export default defineNuxtConfig({
  experimental: {
    inlineSSRStyles: id => !id?.includes('entry')
  }
})
```

**Comment by c-schwan** [comment]
hi @danielroe,

as i saw the css is adding twice (inline + entry.css).

also the inline style should be added before the entry.css or the components css file

**Comment by thijsw** [comment]
Thank you, @danielroe, for resolving this issue so quickly!

**Comment by danielroe** [comment]
Not at all! Aiming to get out a patch today.
