### ISSUE TITLE
useFetch called twice after layout switching

### ISSUE THREAD

**Issue by c-schwan** [nuxt/nuxt#21798]
### Environment

Nuxt Version: 3.6.1

### Reproduction

https://stackblitz.com/edit/nuxt-j8hefc

### Describe the bug

useFetch is called twice after the layout changed.

pages/index.vue (called useFetch) -> pages/other (different layout) -> pages/index.vue (called twice useFetch)

**Comment by danielroe** [comment]
For now, you can avoid passing a reactive route slug to useFetch. To resolve, we can look at ensuring the route is synced in layout suspense forks (though this will be tricky).

**Comment by c-schwan** [comment]
@danielroe can you please remove the workaround label, removing the reactivity from useFetch does not make any difference.

**Comment by prashantpalikhe** [comment]
@c-schwan 

Why not just use `definePageMeta({ layout: 'empty' })` in the `empty.vue` page instead of using `<NuxtLayout />` there too, which is already used in `app.vue`. 

I think that fixes the issue for you.

**Comment by c-schwan** [comment]
> @c-schwan
> 
> Why not just use `definePageMeta({ layout: 'empty' })` in the `empty.vue` page instead of using `<NuxtLayout />` there too, which is already used in `app.vue`.
> 
> I think that fixes the issue for you.

that's true in this cause, but i using different slots in layout so I have to use <NuxtLayout> or is there a way to pass content to a different slot in layout without using NuxtLayout

**Comment by prashantpalikhe** [comment]
You can define the `<NuxtLayout />` in the pages (passing different slots), and remove it from `app.vue`.

In your page, it would be something like

```HTML
<!-- /pages/empty.vue -->
<template>
  <NuxtLayout name="empty">
    <template #slot1>...</template>
    <template #slot2>...</template>
  </NuxtLayout>
</template>
```

**Comment by c-schwan** [comment]
@prashantpalikhe thx for help, but then i have to define on each page <NuxtLayout> (with default layout). this causes probleme that i loose the keepalive state navigating between default layout pages
