### ISSUE TITLE
Vue Nested SFC does not work

### ISSUE THREAD

**Issue by louiss0** [nuxt/nuxt#21800]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.0
- Nitro Version:    2.5.1
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      vite
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-zxp3zq?file=package.json,nuxt.config.ts,app.vue

### Describe the bug

Package `vite-plugin-vue-nested-sfc` is not working in Nuxt 3.6. The app gives me an error saying that a component is not registered Even though it will be rendered by this plugin. 

### Additional context

I had recently installed the `vite-plugin-vue-nested-sfc` it worked after I started the server but not before. I was surprised at this when I saw that the component was not rendered after restarting the server. I got a vite node error. 

### Logs

```shell-script
[Vue warn]: Failed to resolve component: NestedSfc 
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[3:28:58 PM] [Vue warn]: Component <Anonymous> is missing template or render function.
```

**Comment by danielroe** [comment]
Would you check if it works without Nuxt in a Vue SSR setup? https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter

**Comment by louiss0** [comment]
> Would you check if it works without Nuxt in a Vue SSR setup? https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter

It does not work at all. Sorry for the long wait 

This is the error that I get. 

```shell
 [vite] Error when evaluating SSR module /src/pages/Home.vue?vue&type=component&index=0&name=hello-world&lang.component: failed to import "/src/pages/Home.vue/HelloWorld.vue"
|- Error [ENOENT]: ENOENT: no such file or directory, open '/src/pages/Home.vue'
```

Here's my version I decided to fork it for this issue [My Version](https://stackblitz.com/edit/github-qkkygh-qqkvcd?file=src%2Fpages%2FHome.vue)

**Comment by danielroe** [comment]
Okay, that means it's a bug with vite-plugin-vue-nested-sfc - it does not work in Vite SSR, not only Nuxt.

I would suggest raising an issue in that library's repository.

**Comment by louiss0** [comment]
> Okay, that means it's a bug with vite-plugin-vue-nested-sfc - it does not work in Vite SSR, not only Nuxt.
> 
> I would suggest raising an issue in that library's repository.

I did there was no response I will go to him then.
