### ISSUE TITLE
window.__nuxt__ routePath does not match the current path

### ISSUE THREAD

**Issue by XzyZachary** [nuxt/nuxt#21808]
### Environment

Nuxt v2.15.8
Node v14.17.0

### Reproduction

Nuxt2 window.__nuxt__ routePath does not match the current path

### Describe the bug

I found a problem, I use nuxt generate project, but I want to use nginx for a layer of proxy. I used proxy_pass.

As a result, I found a.com/articles/xxx, and the proxy to the nuxt project is c.com/test/xx.

It is a static page, but the interface is called again. If I change it to a.com/test/xx, it will not be called.

I found out that it is caused by the inconsistency of the routePath of window.nuxt. How to solve this problem?

**Comment by danielroe** [comment]
I would recommend instead using the generated `200.html` as the file to point nginx to.

**Comment by XzyZachary** [comment]
> 

Sorry, can you please tell me why you want to point to 200.html? The dynamic routing I generated looks like this: _project/_id.html. I just tried to access 200 directly, but I didn’t get what I wanted.

**Comment by XzyZachary** [comment]
> I would recommend instead using the generated `200.html` as the file to point nginx to.

Sorry, can you please tell me why you want to point to 200.html? The dynamic routing I generated looks like this: _project/_id.html. I just tried to access 200 directly, but I didn’t get what I wanted.

**Comment by danielroe** [comment]
It might be clearer if you could provide a reproduction. 🙏

**Comment by XzyZachary** [comment]
> I may have misunderstood what you want to do. It might be clearer if you could provide a reproduction.
I'm very sorry, this is a bit difficult to reproduce, it needs a server, I will describe it roughly.
`
  window.__NUXT__ = function (r) { return { 
    layout: "default", 
    data: [{status: 1, createTime: r, updateTime: r, __v: 0 }], 
    fetch: {}, 
    error: null, 
    serverRendered: !0, 
    routePath: "/test/649a54a7181a8b84c31b50fc", 
    config: { _app: { basePath: "/", assetsPath: "/_nuxt/", cdnURL: null } } } 
    }
 `
The above is the window.__nuxt_ in my generate html.I pointed to this page with nginx, the domain name is b.com

The following is part of the nginx configuration of my other proxy domain name a.com:
`
location /article/ {
         proxy_set_header Host $proxy_host;
         proxy_pass https://b.com/test/;
 }
`

When I visit a.com/article/649a54a7181a8b84c31b50fc， 
I found that the current route should be inconsistent with the routePath, which led to re-rendering on the client side，triggered asyncData and adjusted the internal interface.


Forgive my poor description.

**Comment by XzyZachary** [comment]
> I may have misunderstood what you want to do. It might be clearer if you could provide a reproduction. 🙏

I may have misunderstood what you want to do. It might be clearer if you could provide a reproduction.
I'm very sorry, this is a bit difficult to reproduce, it needs a server, I will describe it roughly.
  






```
window.__NUXT__ = function (r) { return { 
    layout: "default", 
    data: [{status: 1, createTime: r, updateTime: r, __v: 0 }], 
    fetch: {}, 
    error: null, 
    serverRendered: !0, 
    routePath: "/test/649a54a7181a8b84c31b50fc", 
    config: { _app: { basePath: "/", assetsPath: "/_nuxt/", cdnURL: null } } } 
    }
```


The above is the window._nuxt in my generate html.I pointed to this page with nginx, the domain name is b.com

The following is part of the nginx configuration of my other proxy domain name a.com:
```
location  /article/ {
         proxy_set_header Host $proxy_host;
         proxy_pass https://b.com/test/;
}
```

When I visit a.com/article/649a54a7181a8b84c31b50fc，
I found that the current route should be inconsistent with the routePath, which led to re-rendering on the client side，triggered asyncData and adjusted the internal interface.

Forgive my poor description.

**Comment by danielroe** [comment]
Have you tried adding an alias in your route definition to allow vue-router to render the path on either route?
