### ISSUE TITLE
Analytic tools added through GTM accumulating on navigation

### ISSUE THREAD

**Issue by KaragiannidesAgapios** [nuxt/nuxt#21812]
### Environment

  System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M2
    Memory: 455.17 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.21.3 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 6.14.18 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Safari: 16.3
  npmPackages:
    nuxt: ^2.15.8 => 2.17.0

### Reproduction

https://stackblitz.com/edit/github-i8scez
 
1. Make sure you add a proper `GTM id` in `nuxt.config` file and that some other analytic tools are in included as well (`tiktok.analytics`, `criteo`, `marketing1by1`, `snap`, `adloop` etc ).
2. Run in terminal `npm run build && npm run start`
3. Navigate through the pages with the `NuxtLink` component.
4. Inspect `head` element and see it keep growing and duplicating scripts, iframes.

### Describe the bug

Every time that a user navigates to another page through `NuxtLink` a new script from the tools that intergraded through GTM is added. I can see scripts/iframes duplicating from the following list:

- Criteo
- Marketing1by1
- snap.licdn
- tiktok.analytics
- adloop
- etc

### Additional context

I already use https://github.com/nuxt-community/gtm-module and at the beginning i though this is the problem but i'm able to reproduce the exact same behaviour without the module.

Anyone seen this is before? I think this is quite important, because if you navigate in 20 different pages, you gonna end up with a bunch of duplicated scripts that might lead to a browser crash or slow performance etc.

**Comment by danielroe** [comment]
Are you sure you've configured GTM properly, and don't have a trigger that is re-adding the tags on navigation?

**Comment by KaragiannidesAgapios** [comment]
@danielroe Thanks a lot for your quick response. 
I'll try to see with my colleagues who are responsible for GTM and come back to update the ticket accordingly.

**Comment by KaragiannidesAgapios** [comment]
I will close this ticket as nuxt is not the problem here, but instead certain tools that don't handle this case correctly. Specifically `adloop`, `marketing1by1` are the ones that creating this problem.
