### ISSUE TITLE
Iframes on Self

### ISSUE THREAD

**Issue by snakysnake** [nuxt/nuxt#21818]
### Environment

Try and use an iframe on one of your pages, where you link to your own page, and see what happens.
I nearly got a panic attack from the amount of error messages that came my way. Not recommended, but there's defo something wrong here.

### Reproduction

      <iframe
        title="Demo"
        class="bg-white"
        style="
          border-top-right-radius: 0px;
          border-bottom-right-radius: 36px;
          border-bottom-left-radius: 36px;
          border-top-left-radius: 0px;
        "
        :src="iframeURL"
        width="100%"
        height="100%"
      />

### Describe the bug

Complete meltdown of nuxt, infinite loop

**Comment by arashsheyda** [comment]
@snakysnake is [this reproduction](https://stackblitz.com/edit/nuxt-starter-ainh13?file=pages%2Findex.vue) right?

**Comment by snakysnake** [comment]
I feel ashamed, it was again my mistake somehow.... Sorry guys.

**Comment by arashsheyda** [comment]
@snakysnake no worries 😄, it happens. have a good day
