### ISSUE TITLE
[nuxt-link] Invalid prop: type check failed for prop "to"

### ISSUE THREAD

**Issue by emaia** [nuxt/nuxt#21822]
### Environment

- Operating System: Linux
- Node Version:     v18.16.1
- Nuxt Version:     3.5.3
- Nitro Version:    2.5.1
- Package Manager:  npm@9.5.1
- Builder:          vite
- User Config:      devtools, modules, googleFonts
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @nuxtjs/google-fonts@3.0.1, @formkit/nuxt@0.17.3
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-uv3874?file=package.json

### Describe the bug

Passing an object to `nuxt-link` props `to` returns a Vue Warn and rendered link doesn't work.

```
<nuxt-link :to="{ hash: '#example' }">example</nuxt-link>


Invalid prop: type check failed for prop "to". Expected String with value "[object Object]", got Object
``` 

it render `<a>example</a>`

**Comment by dab-code** [comment]
I'm having the same issue in nuxt 3.6.1. I've tried passing an object with `name` and `href`. The results are the same as @emaia

**Comment by dab-code** [comment]
@emaia have you enabled routing? I hadn't at added a `index.vue` with `useRoute()` and now it works as inteded :+1:

**Comment by emaia** [comment]
> @emaia have you enabled routing? I hadn't at added a `index.vue` in the `pages` folder with `useRoute()` and now it works as inteded 👍

I also hadn't enable router... I understand now... Thanks!
