### ISSUE TITLE
Typescript dependency in subfolders

### ISSUE THREAD

**Issue by affinage-digital** [nuxt/nuxt#21826]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.12.1
- Nuxt Version:     3.6.0
- Nitro Version:    2.5.1
- Package Manager:  npm@8.19.2
- Builder:          vite
- User Config:      runtimeConfig, app, modules, css, vite, nitro, router
- Runtime Modules:  @pinia/nuxt@0.4.11, @nuxt/devtools@0.6.3
- Build Modules:    -

Typescript 5.1.3
C:/program files/microsoft vs code/resources/app/extansions/node_modules/typescript/tsserver.js

### Reproduction

The idea is to make a single IDE typescript support for two folders and use strapi types in nuxt.

This is my folder structure:

- backend-strapi (folder)
- - types (folder)
- - tsconfig.json
- frontend-nuxt3 (folder)
- - tsconfig.json
- .gitignore
- .prettierignore
- .prettierrc
- readme.md

Content of frontend/tsconfig.json
```json
{
    "extends": "./.nuxt/tsconfig.json",
    "include": [
        "../backend/types/**/*.ts" // i dont know if its right or wrong
    ]
}
```

Content of frontend/package.json
```json
{
    "dependencies": {
        "@nuxtjs/eslint-config-typescript": "^12.0.0",
        "@pinia/nuxt": "^0.4.11",
        "@types/node": "^20.3.0",
        "@typescript-eslint/parser": "^5.59.9",
        "eslint": "^8.42.0",
        "eslint-config-prettier": "^8.8.0",
        "eslint-plugin-prettier": "^4.2.1",
        "nuxt": "^3.5.3",
        "pinia": "^2.1.3",
        "prettier": "^2.8.8",
        "sass": "^1.63.3",
        "stylelint": "^15.7.0",
        "stylelint-config-recommended-scss": "^12.0.0",
        "stylelint-config-recommended-vue": "^1.4.0",
        "stylelint-config-standard": "^33.0.0",
        "stylelint-order": "^6.0.3",
        "typescript": "5.0.4",
        "vite-plugin-eslint": "^1.8.1",
        "vite-plugin-stylelint": "^4.3.0",
        "vue-eslint-parser": "^9.3.1"
    },
    "devDependencies": {
        "@nuxt/devtools": "^0.6.1"
    }
}

```

### Describe the bug

vscode dont see autoimport in nuxt3, but `npm run build` works in folder `frontend`.
Alias like `@` or `~` doesnt works too.

![img-2023-06-27-22-03-18](https://github.com/nuxt/nuxt/assets/207461/c9d9359a-157d-46f1-84df-cf4b8b620310)

![img-2023-06-27-21-55-43](https://github.com/nuxt/nuxt/assets/207461/cb865bde-9d85-4713-bdf6-0affde9cc00e)

![img-2023-06-27-22-12-02](https://github.com/nuxt/nuxt/assets/207461/42955b0a-ad3d-4c13-a849-b0a3b4a554c8)

### Additional context

Trying to add tsconfig.json to root **not working**:
```json
{
    "extends": "./frontend/tsconfig.json"
}
```

**Comment by danielroe** [comment]
Your `include` will override Nuxt's defined one. Instead, can you modify the `typescript.tsConfig.include` setting in your nuxt config?

**Comment by affinage-digital** [comment]
Thanks for fast response. Remove `include` from frontend/tsconfig.json works! All IDE problem is gone.
```json
{
    "extends": "./.nuxt/tsconfig.json"
}
```

I need time to check `typescript.tsConfig.include`

**Comment by affinage-digital** [comment]
@danielroe You advised right decision. Here it is important not to make mistakes in the paths.

1) ```ts
export default defineNuxtConfig({
    // ...
    typescript: {
        tsConfig: {
            include: ['../../backend/types/**/*.d.ts'],
        },
    },
    // ...
});
```

2) `npm run dev` or `npm run build` for generate `frontend/.nuxt/tsconfig.json`

3) Result of `frontend/.nuxt/tsconfig.json` like 
```json
{
   // ...
  "include": [
    "../../backend/types/**/*.d.ts",
    "./nuxt.d.ts",
    "../**/*"
  ],
   // ...
}
```

I will close issue
