### ISSUE TITLE
Static Site Preview Broken (MODULE_NOT_FOUND)

### ISSUE THREAD

**Issue by hecktarzuli** [nuxt/nuxt#21828]
### Environment

Nuxt 3.6.1
Node 18.15.0

### Reproduction

create a site using Nuxt 3.6.1 (could be earlier versions as well)
do a `yarn generate`
do a `yarn preview`

### Describe the bug

After generating a static site, Nuxt throws an error trying to start the preview server.

![image](https://github.com/nuxt/nuxt/assets/2112282/04134718-8493-4644-9f19-9964a85e8b04)

I noticed the nitro.json file doesn't show the `  "preset": "nitro-prerender",` it instead shows.
![image](https://github.com/nuxt/nuxt/assets/2112282/af7dddef-a9fd-45e3-a520-5c8c5eb0d630)

All of this worked in 3.5.3

### Additional context
If you delete your output file, you can see the nitro.json starts out using the pre-render preset, but then at the very end of the build it switches to node-server.

**Comment by danielroe** [comment]
This has been resolved upstream in https://github.com/unjs/nitro/pull/1342

This should be resolved in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/), or in the next release of nitropack.

Let me know if not and I'll reopen.
