### ISSUE TITLE
✨ Template syntax for url parameters (DX)

### ISSUE THREAD

**Issue by jd-solanki** [nuxt/nuxt#21830]
### Describe the feature

Hi 👋🏻 

I'm loving the nuxt as I'm learning more. Recently, I had a thought while making the API call on DX improvements.

## Problem

I'm so thankful that nuxt provides adding query params via `query` in `useFetch` however for URL params we still have to use computed property.

## Solution

We can allow setting params in url via object syntax just like we have in github api:
![image](https://github.com/unjs/ofetch/assets/47495003/22bfe1ee-1a83-406e-ba95-63cdde45732b)

example:
```ts
const postId = ref(1)
useFetch('https://jsonplaceholder.typicode.com/posts/{postId}/comments', {
  query: { q: 'ticket' },
  params: { postId },
})

postId.value = 2 // refetch triggers
```

Here's simple utility function that injects the params: https://github.com/antfu/utils/pull/34

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
This seems like a great candidate for a client-side wrapper composable. However, I think the template literal syntax is already configurable enough for this, as far as built-in support goes:

```ts
useFetch(() => `https://jsonplaceholder.typicode.com/posts/${postId}/comments`, {
  query: { q: 'ticket' },
})
```
