### ISSUE TITLE
Double Slashes not redirectable

### ISSUE THREAD

**Issue by alexan** [nuxt/nuxt#21838]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v16.17.1
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  yarn@3.5.1
- Builder:          vite
- User Config:      alias, devServer, experimental, typescript, vite, components, imports, runtimeConfig, css, modules, build, hooks, sourcemap, app, telemetry
- Runtime Modules:  @pinia/nuxt
- Build Modules:    -
------------------------------

### Reproduction

- open stackblitz https://stackblitz.com/edit/github-bhl812?file=server%2Fmiddleware%2Fdouble-slash-redirect.ts
- goto page in webbrowser `/folder//page`
- observe page is rendered and log output
```
url /folder/page
originalUrl /folder/page
path /folder/page   
```

### Describe the bug

we are normalizing all urls to have clean tracking. For this we had a server middleware deployed in nuxt2.
This server middleware detected if a route contained double `/` and redirected (301) to the route without double slashes.
While migrating we detected an odd behaviour in nuxt3. 
A route with double `/` is resolved by nuxt but without the ability for us to redirect the url. Because all values in the middleware containing the urls are already normalized to contain only one `/`
The same behaviour is observed when setting router.options.strict = true

This should be fixed by either:
- not resolving a route containing an invalid url containing double `/`
- allowing access to the url with double `/` inside

### Logs

```shell-script
url /folder/page
originalUrl /folder/page
path /folder/page
```

**Comment by danielroe** [comment]
cc: @pi0

**Comment by pi0** [comment]
Please note this only happens in development mode. When you build and run your application in production, `event.node.req.url` preserves double slashes. Upstream https://github.com/http-party/node-http-proxy/issues/1420

**Comment by danielroe** [comment]
Let's track upstream in that issue...
