### ISSUE TITLE
`useRoute` shows errors if not been used in pages/index.vue

### ISSUE THREAD

**Issue by ggalvez92** [nuxt/nuxt#21842]
### Environment

```
Operating System: Windows 11
Node Version: v16.15.0
Nuxt Version: 3.6.1
Package Manager: yarn@1.22.10
Builder: vite
User Config: devtools, experimental
IDE: Vscode
```

### Reproduction

Create other route file in pages or directory inside pages and try to `useRoute` in my example I created
`pages/testing.vue`

### Describe the bug

`useRoute` is not autocompleted and the IDE shows an error that `cannot find name`
[image](https://imgur.com/a/vjfXj9n)

### Additional context

No response

### Logs

```shell-script
No response
```

**Comment by manniL** [comment]
Hey! When opening an issue, please provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction) ☺️ 

In this case, ensure that the dev server is running (or ran before at least once) so the types for auto imports can be generated.

If that doesn't resolve the issue, please provide more info about how to reproduce the problem.

**Comment by ggalvez92** [comment]
sorry about this issue! It was related to some specific vs code extensions. After, I cleaned up some extensions it is working fine, thank you.
