### ISSUE TITLE
Pages route type issue

### ISSUE THREAD

**Issue by miketests** [nuxt/nuxt#21859]
### Environment

I've just created Nuxt 3 project but there are some type errors right out of the box.

![image](https://github.com/nuxt/nuxt/assets/131380665/93b6b3ae-5a53-4813-99b1-5b7529e79e88)

```
Property '$route' does not exist on type '{ $: ComponentInternalInstance; $data: {}; $props: { key?: string | number | symbol | undefined; ref?: VNodeRef | undefined; ref_for?: boolean | undefined; ... 8 more ...; style?: unknown; }; ... 10 more ...; $watch<T extends string | ((...args: any) => any)>(source: T, cb: T extends (...args: any) => infer R ? (arg...'.
```

```
Cannot find name 'useRoute'.
```

How to fix these errors?

### Reproduction

1) Create new Nuxt 3 project
2) Set `pages: true` option in `nuxt.config` file
3) Create `pages` folder
4) Add `<NuxtPage />` into `app.vue` file.
5) Add some page in `pages` folder
6) See type errors when using `$route` in the template or global `useRoute()` function in composition API.

### Describe the bug

There are type errors when just using Nuxt 3 pages router out of the box.

### Additional context

**package.json**

```
{
  "name": "my-new-nuxt-app",
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/devtools": "^0.5.5",
    "@types/node": "^18.16.18",
    "nuxt": "^3.6.1"
  },
  "overrides": {
    "vue": "latest"
  }
}
```

**app.vue**

```
<template>
  <div>
    <NuxtPage />
  </div>
</template>
```

**pages/[code].vue**

```
<template>
  <div>
    <p>{{ $route.params.code }}</p>
  </div>
</template>

<script setup lang="ts">
  const route = useRoute()
  console.log('code:', route.params.code)
</script>
```

**nuxt.config.ts**

```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  pages: true,
})
```

VS Code
Node v16.14.2
NPM 8.5.0

**Comment by danielroe** [comment]
Are you running the dev server?

**Comment by miketests** [comment]
Sure, I setup Nuxt 3 project at first to use pages and then use `npm run dev` to develop it locally.
So it's running despite type errors.

**Comment by danielroe** [comment]
I would imagine this might just be an IDE issue. You could try reloading it. Failing that, I would appreciate a reproduction as this issue does not occur for me.

**Comment by danielroe** [comment]
No problem!
