### ISSUE TITLE
Error: Failed to download template from registry: fetch failed

### ISSUE THREAD

**Issue by jeverduzco** [nuxt/nuxt#21853]
### Environment

------------------------------
- Operating System: Darwin - Mac M2
- Node Version: v18.16.1
- Nuxt Version: 3.6.1
- Nitro Version: 2.5.2
- Package Manager:  npm@9.7.2
- Builder: vite
- User Config: -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Init new project using Nuxi.

`npx nuxi init test`

![Screen Shot 2023-06-28 at 20 10 05 p m](https://github.com/nuxt/nuxt/assets/3856266/584a53e1-e728-48fa-9ecc-9d8d522f8852)

### Describe the bug

Impossibility to create a project, the bug is also present when using useFecth with SSR.

**Comment by danielroe** [comment]
This is probably due to your computer's networking or firewall settings. It is caused by the fact that node can't fetch anything from the network.

Perhaps you could investigate further

**Comment by jeverduzco** [comment]
Hey thanks @danielroe. I am trying and having problems even with `useFetch`, but you are right it must be something with my internet provider because with a VPN it has been solved.

**Comment by mrinalwahal** [comment]
I'm also having the same error.

And no, I'm neither using a proxy nor is internet access restricted for me to `raw.githubusercontent.com`.

I would like to know what is the potential solution for this on mac?

This looks like either a node or an npm issue.

**Comment by 171h** [comment]
+1

**Comment by meiqi1992** [comment]
+1

**Comment by abhaykumarvats** [comment]
To all the Indians facing this issue, it is a JioFiber issue. Somehow `raw.githubusercontent.com` is blocked (for the lack of better word) on JioFiber. I know, weird, but it is what it is. If you can get access to your router – I haven't been able to – change the DNS to Google's (i.e. 8.8.8.8) and it should work fine. If that's not doable, try using hotspot, will work absolutely fine.

**Comment by Dubemtopsite** [comment]
Best way to go about the issue is using VPN which worked for me

**Comment by riyal-xip** [comment]
Try after changing your network. Ex :- Mobile network to wifi OR JIO to GTPL  (Other Broadband connection).
In my case not working in JIO(Broadband) once we change with GTPL(Broadband) it will installing automatically.

**Comment by SheikhFaizan141** [comment]
easy fix for indians who are using Jio fiber or Jio 4/5g change your dns server either for router if possible or for your device and also mail jio fiber regarding this issue.

**Comment by chinesecooly** [comment]
How can I fix if from China that the computer system is win11.

**Comment by 19119294973** [comment]
我在Mac上面也遇到了这个问题，我没有开启防火墙，不管是打开还是关闭翻墙软件，都会报这个错误，即使我在hosts中添加了185.199.108.133 raw.githubusercontent.com依然没用

**Comment by 171h** [comment]
For those who have failed, you can manually download the templatefile from this link.
https://codeload.github.com/nuxt/starter/tar.gz/refs/heads/v3

**Comment by zc16607** [comment]
I have resolved the issue, as the domain name raw.githuusercontent.com cannot resolve the correct IP address. You can ping this domain name to see if you can get an IP address. If it is not possible, modify the host file of the system to any of these four IPs: 185.199.108.133, 185.199.109.133, 185.199.110.133, 185.199.111.133

**Comment by chinesecooly** [comment]
> For those who have failed, you can manually download the templatefile from this link. https://codeload.github.com/nuxt/starter/tar.gz/refs/heads/v3

Could you tell me the link where can I found because I want to find the lasted version in future.

**Comment by 171h** [comment]
https://github.com/nuxt/starter

**Comment by Justin3go** [comment]
Does anyone know what the problem is?

![image](https://github.com/nuxt/nuxt/assets/63507251/45f2c40e-bcc5-4514-9020-1178f064311e)

```sh
$ pnpm dlx nuxi@latest init xxx
Packages: +1
+
Progress: resolved 2, reused 1, downloaded 0, added 1, done

[上午10:13:52]  ERROR  Error: Failed to download template from registry: Failed to download https://raw.githubusercontent.com/nuxt/starter/templates/templates/v3.json: TypeError: fetch failed


xxx/repos
$ curl GET 'https://raw.githubusercontent.com/nuxt/starter/templates/templates/v3.json'
{
  "name": "v3",
  "defaultDir": "nuxt-app",
  "url": "https://nuxt.com",
  "tar": "https://codeload.github.com/nuxt/starter/tar.gz/refs/heads/v3"
}

xxx/repos
$ ping raw.githubusercontent.com

正在 Ping raw.githubusercontent.com [185.199.108.133] 具有 32 字节的数据:
来自 185.199.108.133 的回复: 字节=32 时间=128ms TTL=50
来自 185.199.108.133 的回复: 字节=32 时间=134ms TTL=50
来自 185.199.108.133 的回复: 字节=32 时间=183ms TTL=50
来自 185.199.108.133 的回复: 字节=32 时间=127ms TTL=50

185.199.108.133 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 127ms，最长 = 183ms，平均 = 143ms
```

**Comment by ljnMeow** [comment]
> 有谁知道问题是什么？
> 
> ![图像](https://private-user-images.githubusercontent.com/63507251/305770190-45f2c40e-bcc5-4514-9020-1178f064311e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MTkwNzIsIm5iZiI6MTcwODQxODc3MiwicGF0aCI6Ii82MzUwNzI1MS8zMDU3NzAxOTAtNDVmMmM0MGUtYmNjNS00NTE0LTkwMjAtMTE3OGYwNjQzMTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDA4NDYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2M2ZiMGM5MDJjOTcwMmJiYzM0NzFkYTBlMmEwMTFkZTY5YmQ2YjdjYjY2YzYzY2JmNzdkN2M5ZmQ4MWU4OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wW7mXYwGz309xSuRT5hBHqqTKkmDfRJWf68XYCIfKFA)
> 
> ```shell
> $ pnpm dlx nuxi@latest init xxx
> Packages: +1
> +
> Progress: resolved 2, reused 1, downloaded 0, added 1, done
> 
> [上午10:13:52]  ERROR  Error: Failed to download template from registry: Failed to download https://raw.githubusercontent.com/nuxt/starter/templates/templates/v3.json: TypeError: fetch failed
> 
> 
> xxx/repos
> $ curl GET 'https://raw.githubusercontent.com/nuxt/starter/templates/templates/v3.json'
> {
>   "name": "v3",
>   "defaultDir": "nuxt-app",
>   "url": "https://nuxt.com",
>   "tar": "https://codeload.github.com/nuxt/starter/tar.gz/refs/heads/v3"
> }
> 
> xxx/repos
> $ ping raw.githubusercontent.com
> 
> 正在 Ping raw.githubusercontent.com [185.199.108.133] 具有 32 字节的数据:
> 来自 185.199.108.133 的回复: 字节=32 时间=128ms TTL=50
> 来自 185.199.108.133 的回复: 字节=32 时间=134ms TTL=50
> 来自 185.199.108.133 的回复: 字节=32 时间=183ms TTL=50
> 来自 185.199.108.133 的回复: 字节=32 时间=127ms TTL=50
> 
> 185.199.108.133 的 Ping 统计信息:
>     数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
> 往返行程的估计时间(以毫秒为单位):
>     最短 = 127ms，最长 = 183ms，平均 = 143ms
> ```

请问解决了嘛

**Comment by Justin3go** [comment]
> > 有谁知道问题是什么？
> > ![图像](https://private-user-images.githubusercontent.com/63507251/305770190-45f2c40e-bcc5-4514-9020-1178f064311e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MTkwNzIsIm5iZiI6MTcwODQxODc3MiwicGF0aCI6Ii82MzUwNzI1MS8zMDU3NzAxOTAtNDVmMmM0MGUtYmNjNS00NTE0LTkwMjAtMTE3OGYwNjQzMTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDA4NDYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2M2ZiMGM5MDJjOTcwMmJiYzM0NzFkYTBlMmEwMTFkZTY5YmQ2YjdjYjY2YzYzY2JmNzdkN2M5ZmQ4MWU4OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wW7mXYwGz309xSuRT5hBHqqTKkmDfRJWf68XYCIfKFA)
> > ```shell
> > $ pnpm dlx nuxi@latest init xxx
> > Packages: +1
> > +
> > Progress: resolved 2, reused 1, downloaded 0, added 1, done
> > 
> > [上午10:13:52]  ERROR  Error: Failed to download template from registry: Failed to download https://raw.githubusercontent.com/nuxt/starter/templates/templates/v3.json: TypeError: fetch failed
> > 
> > 
> > xxx/repos
> > $ curl GET 'https://raw.githubusercontent.com/nuxt/starter/templates/templates/v3.json'
> > {
> >   "name": "v3",
> >   "defaultDir": "nuxt-app",
> >   "url": "https://nuxt.com",
> >   "tar": "https://codeload.github.com/nuxt/starter/tar.gz/refs/heads/v3"
> > }
> > 
> > xxx/repos
> > $ ping raw.githubusercontent.com
> > 
> > 正在 Ping raw.githubusercontent.com [185.199.108.133] 具有 32 字节的数据:
> > 来自 185.199.108.133 的回复: 字节=32 时间=128ms TTL=50
> > 来自 185.199.108.133 的回复: 字节=32 时间=134ms TTL=50
> > 来自 185.199.108.133 的回复: 字节=32 时间=183ms TTL=50
> > 来自 185.199.108.133 的回复: 字节=32 时间=127ms TTL=50
> > 
> > 185.199.108.133 的 Ping 统计信息:
> >     数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
> > 往返行程的估计时间(以毫秒为单位):
> >     最短 = 127ms，最长 = 183ms，平均 = 143ms
> > ```
> 
> 请问解决了嘛

没有，我在codespace里面初始化的项目

**Comment by chinesecooly** [comment]
Today I try again and I find it worked.
![image](https://github.com/nuxt/nuxt/assets/67155556/7ce7cc5e-1261-4900-860d-b02b4c4ca42d)

**Comment by idabaicai** [comment]
I'm also having the same error.

**Comment by 282159468** [comment]
I'm also having the same error.

**Comment by Amin199473** [comment]
Hello everyone , also I had this problem , I solved that via vscode , you should use the vscode terminal first create one root directory  , then install nuxt there please read here https://nuxt.com/docs/getting-started/installation

**Comment by Unequaled804** [comment]
> Here is the English translation of the provided content:
> 
> Solution:
> 
> First, ping raw.githubusercontent.com to check if it is accessible. If it is not accessible, visit https://ipaddress.com/website/raw.githubusercontent.com. ![image](https://private-user-images.githubusercontent.com/16145351/315051476-46e497e4-5cc4-4ab2-8aca-53feff1d065b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4NTU0NjAsIm5iZiI6MTcxOTg1NTE2MCwicGF0aCI6Ii8xNjE0NTM1MS8zMTUwNTE0NzYtNDZlNDk3ZTQtNWNjNC00YWIyLThhY2EtNTNmZWZmMWQwNjViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDE3MzI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxMGQ2ZDgxODlmNTM1MWRlZmE0YjEwYjM4NTk5ZTJlZWNiZDhiZmZmZGIxMGM2OTIyOWQyMTkzMjEyYjk4NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nhTrCYfoL5-nXZaW3eBjApsiTCKEuZjQY45_WSTT6A8)
> 
> Then, add the host entry. On macOS, the host configuration file path is: /etc/hosts Add a new line: 185.199.108.133 raw.githubusercontent.com After adding the host entry, ping raw.githubusercontent.com again to check if it is accessible. If the ping is successful, try running the command npx nuxi init nuxt-app again.

成功了 感谢！但我个人刚才试了一下得所有ip加上才好使
Add all these rules in your hosts file if it still not worked after adding only one rule.
```
185.199.108.133 raw.githubusercontent.com
185.199.109.133 raw.githubusercontent.com
185.199.110.133 raw.githubusercontent.com
185.199.111.133 raw.githubusercontent.com
```

**Comment by 254558** [comment]
When I use a Taiwan VPN, 
it doesn’t work, but when I switch to a Japan VPN, 
it works fine. 
For developers in China, 
it’s worth trying a different VPN node.

**Comment by danielroe** [comment]
nuxtathon closed @Norbiros
