### ISSUE TITLE
`useAsyncData` watcher will not be triggered on page reload

### ISSUE THREAD

**Issue by KillerJulian** [nuxt/nuxt#21857]
### Environment

- Operating System: Windows_NT
- Node Version:     `v16.17.1`
- Nuxt Version:     `3.6.1`
- Nitro Version:    `2.5.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `app, css, postcss`
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

Emaciated code example:

```vue
<template>
	<div class="m-auto h-[28rem] w-[42rem]">
		<Scatter v-if="chartData.data.value" :data="chartData.data.value" :options="chartOptions" />
	</div>

	<div class="m-auto mt-6 flex flex-col flex-wrap items-center justify-center gap-2">
		<span
			v-for="sensor of boxData.data.value?.sensors || []"
			class="cursor-pointer text-center text-neutral-300"
			@click="() => (selectedSensor = sensor._id)"
		>
			<p class="flex items-center justify-center gap-1 text-lg font-semibold underline underline-offset-2">
				<span>{{ sensor.title }}</span>
			</p>
		</span>
	</div>
</template>

<script lang="ts" setup>
import { ChartData, ChartOptions } from 'chart.js';
import 'chartjs-adapter-moment';
import { getBox, getData } from 'opensensemap-client';
import { Scatter } from 'vue-chartjs';

const osmBoxID = '591f578c51d34600116a8ea5';

const selectedSensor = ref<string | null>(null);

const boxData = useAsyncData(() => getBox(osmBoxID));
boxData.then((data) => (selectedSensor.value = data.data.value?.sensors[0]?._id || null));

const chartData = useAsyncData<ChartData<'scatter'>>(
	async () => {
		if (selectedSensor.value === null) {
			return { datasets: [] };
		}

		const fechedData = await getData(osmBoxID, selectedSensor.value);

		return {
			datasets: [
				{
					data: fechedData.flatMap((e) => ({ y: Number(e.value), x: new Date(e.createdAt).valueOf() })),
					backgroundColor: '#3b82f6'
				}
			]
		};
	},
	{
		watch: [selectedSensor]
	}
);

const chartOptions = computed<ChartOptions<'scatter'>>(() => {
	const primaryColor = '#d4d4d4';
	const secondaryColor = '#525252';

	const sensor = boxData.data.value?.sensors.find((e) => e._id === selectedSensor.value);

	return {
		responsive: true,
		maintainAspectRatio: false,
		plugins: {
			title: {
				text: sensor?.sensorType,
				display: true,
				font: {
					size: 16
				},
				color: primaryColor
			},
			legend: {
				display: false
			},
			tooltip: {
				mode: 'nearest',
				usePointStyle: true
			}
		},
		scales: {
			x: {
				type: 'time',
				time: {
					minUnit: 'hour',
					displayFormats: {
						hour: 'DD.MM. HH:mm',
						day: 'DD.MM.YYYY'
					},
					tooltipFormat: 'DD.MM.YYYY HH:mm [Uhr]'
				},
				grid: {
					drawOnChartArea: false,
					color: primaryColor
				},
				border: {
					color: primaryColor
				},
				ticks: {
					maxTicksLimit: 5,
					autoSkip: true,
					color: primaryColor
				}
			},
			y: {
				title: {
					text: `${sensor?.title} (${sensor?.unit})`,
					display: true,
					color: secondaryColor
				},
				grid: {
					drawOnChartArea: false,
					color: primaryColor
				},
				border: {
					color: primaryColor
				},
				ticks: {
					color: primaryColor
				}
			}
		}
	};
});
</script>
```

### Expected behaviour:
0. Page is entered
1. Fetch data of the weather station.
2. Set `selectedSensor` to the first sensor of the weather station
3. Fetch the history data for the `selectedSensor`
4. Adjust and display data

### Actual behaviour:
Works when switching between the routes.
Does not work if you reload the page itself.

-> `boxData` is present, `selectedSensor` is set correctly. `chartData` is triggered when it is initialised, but when the sensor is set during `boxData.then()`, `chartData` does not seem to be aware of this

**Comment by danielroe** [comment]
This is because the data starts off fully initialised when the page is hard reloaded.

In general you should not mutate state _outside_ the asyncdata fetcher function within it, because it is not guaranteed to be called. (The whole point of asyncData is to avoid re-calling the fetcher function on the client on a hard reload.)

Instead, you can use a computed value, e.g.:

```ts
const { data: boxData } = useAsyncData(() => getBox(osmBoxID))
const selectedSensor = computed(() => boxData.value?.sensors[0]?._id || null)
```

**Comment by KillerJulian** [comment]
Thank you for your quick reply.
I am very confused now.

The user has the possibility to select a sensor. I can include a setter in the `computed`, but this then refers to a `ref` again.

Also, `selectedSensor` has to be set to the first sensor in the array after each fetch.
_Use Case: The sensor selected by the user is no longer available._

**Comment by danielroe** [comment]
In that case, you had probably better do this:
```ts
const selectedSensor = ref<string | null>(null);
const { data: boxData } = useAsyncData(() => getBox(osmBoxID))
watch(boxData, (newData) => selectedSensor.value = newData.value?.sensors[0]?._id || null, { immediate: true })
```

**Comment by danielroe** [comment]
Perhaps you could provide a minimal stackblitz, and I'll take a look. Nonetheless, I don't think this is a Nuxt issue.

**Comment by KillerJulian** [comment]
https://stackblitz.com/edit/nuxt-starter-qfr3pa?file=components%2FWeather%2Findex.vue

**Comment by danielroe** [comment]
The key thing is that `data` is not what `useAsyncData` returns. Instead, it returns an object of reactive values:

```diff
- const data = useAsyncData(/* */)
+ const { data } = useAsyncData(/* * /)
```

I've updated your stackblitz: https://stackblitz.com/edit/nuxt-starter-1syqz6?file=components/Weather/index.vue,layouts/default.vue.

It seems to be working for me. What's the issue?

**Comment by KillerJulian** [comment]
Sorry I updatet my code on stackblitz. The problem should now be better presented. Take a look again

**Comment by danielroe** [comment]
Ah, I understand. The solution is to pass `server: false` to the second `useAsyncData` call as it's relying on data that isn't present the first time it runs (on the server). (Or to await the first asyncData call.)

I've updated my example.

**Comment by KillerJulian** [comment]
Thank you very much, that works as desired 👏

**Comment by shuvo-me** [comment]
> Ah, I understand. The solution is to pass `server: false` to the second `useAsyncData` call as it's relying on data that isn't present the first time it runs (on the server). (Or to await the first asyncData call.)
> 
> I've updated my example.

thanks @danielroe  this is correct ans.
