### ISSUE TITLE
watching asynchronous data can lead to inconsistent values in the store

### ISSUE THREAD

**Issue by baixiaoyu2997** [nuxt/nuxt#21858]
### Environment

- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.1
- Package Manager:  npm@9.4.0
- Builder:          vite
- User Config:      modules, imports
- Runtime Modules:  @pinia/nuxt@0.4.11
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-vibihh?file=pages%2Findex.vue,store%2Fwallet.ts

### Describe the bug

I want to modify the value of `isSetOption` to `true` in the `wallet store` by listening to the completion of asynchronous operations in the `chain store`. However, the final result is `false`, and there is no operation in my code to set `isSetOption.value` to `false`.

### Additional context

Although the maintainers of Pinia have provided me with a [solution](https://github.com/vuejs/pinia/issues/2285#issuecomment-1612535520) to this issue, I am not sure if it is a bug in Nuxt. So, if this is not a bug, feel free to close the issue.

**Comment by danielroe** [comment]
I think it was a good explanation in the upstream issue. On the server, if you do not somehow await a promise, the response may well return before the promise resolves.

In your case you may be able to use `onServerPrefetch` to await the promise - for example:

```ts
import { defineStore } from 'pinia';

export const useChainStore = defineStore('chain', () => {
  const isReady = ref(false);
  const promise = Promise.resolve().then(() => {
    isReady.value = true;
  });
  onServerPrefetch(() => promise)
  // alternatively, if onServerPrefetch isn't available because it's called outside nuxt lifecycle
  useNuxtApp().hook('app:created', () => promise)

  return {
    isReady,
  };
});
```

But this isn't a bug within Nuxt.
