### ISSUE TITLE
Cannot find module `pinia\dist\pinia.prod.cjs` when using npm package that exports pinia store only when deployed to vercel

### ISSUE THREAD

**Issue by kimbaudi** [nuxt/nuxt#21854]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.12.0
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      app, build, css, devtools, modules, runtimeConfig, typescript, vite
- Runtime Modules:  @pinia/nuxt@0.4.11
- Build Modules:    -
------------------------------

### Reproduction

public npm package: https://github.com/kimbaudi/vue3tslibtest

public github repo: https://github.com/kimbaudi/vue3-nuxt-demo

To reproduce the error, fork https://github.com/kimbaudi/vue3-nuxt-demo and deploy to vercel.
I already deployed vue3-nuxt-demo to vercel so you can see the error if you go to https://vue3-nuxt-demo.vercel.app/

![image](https://github.com/nuxt/nuxt/assets/1864092/26014ff5-7b7e-4c87-b81a-2a4aeb060114)

### Describe the bug

I created a vue3 component library that exports a pinia store and published it as a publicly scoped npm package (https://www.npmjs.com/package/@kimbaudi/vue3tslibtest).

I then created a nuxt3 project that uses the `@kimbaudi/vue3tslibtest` npm package (https://github.com/kimbaudi/vue3-nuxt-demo).

When I deploy `vue3-nuxt-demo` to vercel, I get a 500 error that module `pinia\dist\pinia.prod.cjs` cannot be found imiported from `@kimbaudi\vue3tslibtest\dist\my-lib.js`.

### Additional context

This issue is related to https://github.com/nuxt/nuxt/issues/19847.

Before I deployed `vue3-nuxt-demo` to vercel, I was able to reproduce the issue locally during build (`yarn build`), but not dev (`yarn dev`).  After a bit of searching, I discovered issue https://github.com/nuxt/nuxt/issues/19847, which suggested adding the following to `nuxt.config.ts` file in my `vue3-nuxt-demo` project:

```shell
  nitro: {
    alias: {
      pinia: "pinia",
    },
  },
```

After adding the above configuration, the issue was resolved locally during build so I then proceeded to deploy to vercel. Unfortunately, the 500 cannot find module error exists after deploying to vercel.  

Looking at https://github.com/nuxt/nuxt/issues/19847#issuecomment-1479848806, it seems that `pinia must be installed as a Vue plugin and so it will not work in your server routes, which are run/processed entirely outside of a Vue context`.

---

my npm package `@kimbaudi/vue3tslibtest` has 2 versions: v0.0.1 and v0.0.2.
- v0.0.1 exports pinia store.
- v0.0.2 doesn't export pinia store.

So when you fork https://github.com/kimbaudi/vue3-nuxt-demo, you can update @kimbaudi/vue3tslibtest to v0.0.2 in package.json and deploy to vercel and the 500 error will be resolved since I comment out the code that exports the pinia store.

If you fork https://github.com/kimbaudi/vue3-nuxt-demo and just keep @kimbaudi/vue3tslibtest at v0.0.1, then you will get the 500 error when deploying to vercel since the pinia store is being exported in that version.

I'll also open an issue at https://github.com/vuejs/pinia.

### Logs

```shell-script
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/node_modules/pinia/dist/pinia.prod.cjs' imported from /var/task/node_modules/@kimbaudi/vue3tslibtest/dist/my-lib.js
    at new NodeError (node:internal/errors:399:5)
    at finalizeResolution (node:internal/modules/esm/resolve:331:11)
    at moduleResolve (node:internal/modules/esm/resolve:994:10)
    at moduleResolveWithNodePath (node:internal/modules/esm/resolve:938:12)
    at defaultResolve (node:internal/modules/esm/resolve:1202:79)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/node_modules/pinia/dist/pinia.prod.cjs' imported from /var/task/node_modules/@kimbaudi/vue3tslibtest/dist/my-lib.js
    at new NodeError (node:internal/errors:399:5)
    at finalizeResolution (node:internal/modules/esm/resolve:331:11)
    at moduleResolve (node:internal/modules/esm/resolve:994:10)
    at moduleResolveWithNodePath (node:internal/modules/esm/resolve:938:12)
    at defaultResolve (node:internal/modules/esm/resolve:1202:79)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

**Comment by kimbaudi** [comment]
From https://github.com/nuxt/nuxt/issues/15058#issuecomment-1397371377:
> You can't use pinia outside your Vue app in a nitro API route. Pinia is written to be consumed in a Vue environment. It might be possible to add this functionality to @pinia/nuxt though. Feel free to open a feature request there.

**Comment by adrienZ** [comment]
In your package `vue3tslibtest`, you may need to set `pinia` as [peerDependencies](https://nodejs.org/en/blog/npm/peer-dependencies) instead of devDependencies.

example with [vue-demi](https://github.com/vueuse/vue-demi/blob/main/package.json).

Your issue is likely more related to nodejs behavior than Nuxt itself :)

**Comment by kimbaudi** [comment]
@adrienZ - I actually set pinia as both devDependency (https://github.com/kimbaudi/vue3tslibtest/blob/main/package.json#L38) & peerDependency (https://github.com/kimbaudi/vue3tslibtest/blob/main/package.json#L47).

When I remove pinia as devDependency and only add it as a peerDependency, I get the following error when I run `yarn install`:

> src/stores/counter.ts:2:29 - error TS2307: Cannot find module 'pinia' or its corresponding type declarations.
>
> import { defineStore } from "pinia";

I think its necessary to set pinia as devDependency in addition to setting it as a peerDependency. Otherwise, I get build error.

**Comment by kimbaudi** [comment]
related nuxt issue:
- https://github.com/nuxt/nuxt/issues/20128

links to discussions in pinia:
- https://github.com/vuejs/pinia/discussions/2216
- https://github.com/vuejs/pinia/discussions/2286

**Comment by kimbaudi** [comment]
It seems the main issue is that `.output/server/node_modules/@kimbaudi/vue3tslibtest/dist/my-lib.js` is importing pinia and expecting  it to be in `.output/server/node_modules/pinia/dist/pinia.prod.cjs`, but there only exists `.output/server/node_modules/pinia/dist/pinia.mjs`

**Comment by kimbaudi** [comment]
i was able to resolve this issue by adding the following to my `nuxt.config.ts` file in my `vue3-nuxt-demo` project:

```shell
export default defineNuxtConfig({
  build: {
    transpile: ["@kimbaudi/vue3tslibtest", "pinia"],
  },
});

```

**Comment by kimbaudi** [comment]
Since I was able to resolve this issue using a workaround, I will leave it open.
