### ISSUE TITLE
Introduce treeshakable`import.meta` build flags

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt#21862]
### Describe the feature

Nuxt provides `process.` flags such as `process.static` that allow writing tree-shakable conditional logic. Nitro recently introduced both that and identical flags for `import.meta.` which is more runtime agnostic namespace. (https://github.com/unjs/nitro/pull/1331).

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
I think this is great :+1:

**Comment by vargasmesh** [comment]
I can work on it.

**Comment by vargasmesh** [comment]
I have been looking at this the last few days, but I am having trouble getting a starting point. 
* I couldn't understand what are our build flags.
* What is the plugin responsible for tree-shaking. I have seen the `TreeShakeTemplatePlugin`, but I am not sure if we should use this or the `nuxt.options.optimization.treeShake.composables`.

Can I have some tips on it, please?

**Comment by vargasmesh** [comment]
@danielroe no problem! I will take a look at it as soon as possible. Thank you for the tips!
