### ISSUE TITLE
Update the documentation for "Get started with nuxt" now that volar takeover and the typescript plugin are no longer needed.

### ISSUE THREAD

**Issue by SebbeJohansson** [nuxt/nuxt#21869]
### Describe the feature

After helping a colleague to get started with nuxt3, we noticed that just using the base volar extension is the only thing needed.

I am only 90% sure that this is true, but im making the issue and a PR with the assumption that it is true.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
This is currently the Vue documentation.

https://vuejs.org/guide/typescript/overview.html#volar-takeover-mode

cc: @johnsoncodehk

**Comment by prashantpalikhe** [comment]
I updated Volar to `1.8.3` and I see this message if I don't enable the `takeover mode`.

![CleanShot 2023-07-01 at 18 33 56@2x](https://github.com/nuxt/nuxt/assets/2657709/40c01d8b-2331-40da-9943-6ff1ad9fd88e)

**Comment by SebbeJohansson** [comment]
Tested this again.

Running with node v18.12.1, Vue Language Features (Volar) 1.8.3, nuxt version 3.3.2. I have NOT disabled the builtin language features. I am not getting any issues at all. Given that this is working would point towards that atleast "TypeScript Vue Plugin" is no longer needed.

@prashantpalikhe Where did you see that issue?

@danielroe Maybe take over is still a good suggestion if it does indeed provide better performance (didnt see any signs of this either)?

**Comment by danielroe** [comment]
Will need to dive in to confirm. Maybe we can also remove the default shim in that case ...

**Comment by johnsoncodehk** [comment]
The situation has not changed, you still need one of takeover mode / ts plugin / shim, otherwise you will get an error when importing .vue in .ts.

**Comment by SebbeJohansson** [comment]
@johnsoncodehk not sure I trust that given that it is working fine in all my projects with the setup I specified before. Can you provide a project where it is not working for you with the setup I use?

**Comment by johnsoncodehk** [comment]
You can try https://github.com/johnsoncodehk/volar-starter

<img width="640" alt="image" src="https://github.com/nuxt/nuxt/assets/16279759/a6df3788-46cb-48fb-96fd-19ed19d96273">

**Comment by prashantpalikhe** [comment]
@SebbeJohansson 

> Where did you see that issue?

`cmd + shift + p` -> `Show running extensions` -> Volar

Without the takeover mode, I see the error I mentioned above.

**Comment by SebbeJohansson** [comment]
Okay i did some further testing! I think this was more a case of me not understanding the vue/volar documentation. I understood it as if Typescript wouldnt work within vue components, not the other way around. Specifically "To get Vue SFCs and TypeScript working together" confused me. The fact that I am able to do most things within vue SFCs without takeover mode confused me.

@johnsoncodehk, I can confirm that I see the same errors from the typescript language package:
![image](https://github.com/nuxt/nuxt/assets/5083273/3e895d30-ec3c-4dd7-9cd7-76dbf2d43530)
If I understand it correctly, I can still get most builtin nuxt stuff to work correctly, but typescript is still not working correctly in the background?
Example where i can use a "typescript feature":
![image](https://github.com/nuxt/nuxt/assets/5083273/3b40eceb-372f-4349-961c-dc9dbfe9c505)
As you can see all imports and functions i need to use, work without takeover mode.

@prashantpalikhe weird... I am not seeing that behaviour.

Given that apparently not everything works (but enough does for me) without takeover mode, it 100% makes sense to keep that instruction. I will close this issue.
