### ISSUE TITLE
Server middleware cookies on initial page serve in nuxt 3

### ISSUE THREAD

**Issue by githubnikola** [nuxt/nuxt#21875]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.12.0`
- Nuxt Version:     `3.6.1`
- Nitro Version:    `2.5.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Make a server/middleware where you set a cookie.
Request homepage.
In homepage script `setup` call useFetch to fetch some data from /server/api.

### Describe the bug

Both requests mentioned in reproduction section go through server/middleware but the later one does not have a cookie previously set.

I assume this is not a bug, but am running out of options on the internet on how to set a cookie on initial request that will persist throughout all requests.

### Additional context

I was told [here](https://github.com/unjs/h3/issues/406) to open an issue in the nuxt repo for better tracking.
@Hebilicious  I hope repo like this is ok. [Repo](https://github.com/githubnikola/nuxt3-server-middleware)

**Comment by Hebilicious** [comment]
Could you please try this : 

https://nuxt.com/docs/getting-started/data-fetching#pass-cookies-from-server-side-api-calls-on-ssr-response

**Comment by githubnikola** [comment]
@Hebilicious 
Tried it. Pushed it. Now there are to requests to API, first without cookie, second with cookie. Not sure whats going on.

**Comment by danielroe** [comment]
If you are trying to read a cookie on the same request where you set it, it will be present on the 'set-cookie' header in the response object, not the cookie header in the request object.

In your case, I would both set a cookie (for future requests) and a property in the `event.context` which you can use for the current request.
