### ISSUE TITLE
ERROR  Cannot start nuxt:  Cannot destructure property 'nuxt' of 'this' as it is undefined. 

### ISSUE THREAD

**Issue by Foddie2** [nuxt/nuxt#21882]
### Environment

 Nuxt project info:                                                                                                           

------------------------------
- Operating System: Linux
- Node Version:     v16.17.0
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      modules, buildModules, colorMode, ssr, pwa, tailwindcss, css, postcss
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @nuxt/postcss8@1.1.3, @vite-pwa/nuxt@0.0.7, @nuxtjs/google-fonts@3.0.1, @nuxt/image-edge@1.0.0-rc.1-28126030.07836ae, @nuxtjs/pwa@3.3.5
- Build Modules:    @nuxtjs/color-mode@3.3.0

### Reproduction

https://github.com/Foddie2/SweetsPot-Cakes

Please help fix issue. I am running on [Nuxt 3.6.1](https://nuxt.com/docs/getting-started/installation) 
and NODE [v16.17.0](https://nodejs.org/en)

### Describe the bug

ERROR  Cannot start nuxt:  Cannot destructure property 'nuxt' of 'this' as it is undefined.                                

  at postcss8Module (node_modules/@nuxt/postcss8/dist/index.js:15:10)
  at installModule (/home/foddie/node_modules/@nuxt/kit/dist/index.mjs:2407:101)
  at async initNuxt (/home/foddie/node_modules/nuxt/dist/index.mjs:2928:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:204:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:248:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:48:20)

### Additional context

Kindly help get the solution to this error am getting from my my Nuxt3 project

**Comment by prashantpalikhe** [comment]
You seem to be using `@nuxt/postcss8` module that is not required for `Nuxt >= 2.16`

**Comment by danielroe** [comment]
Also `@nuxt/postcss8` (not required for Nuxt 2.17+ either). And (most likely) `@nuxtjs/pwa` which is Nuxt 2 only.

**Comment by Foddie2** [comment]
Thanks @prashantpalikhe @danielroe this solved the error
