### ISSUE TITLE
Missing usefetch composable example in docs

### ISSUE THREAD

**Issue by erlestor** [nuxt/nuxt#21894]
### Describe the feature

The repo for the custom usefetch composable example is missing. 

See: https://nuxt.com/docs/examples/advanced/use-custom-fetch-composable

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by adrienZ** [comment]
Please move your issue to https://github.com/nuxt/examples/issues, I'm willing to fix it :)

**Comment by erlestor** [comment]
Moved!

Link to new issue: https://github.com/nuxt/examples/issues/34
