### ISSUE TITLE
 ERROR  [unhandledRejection] require() of ES Module 

### ISSUE THREAD

**Issue by Foddie2** [nuxt/nuxt#21897]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.17.0
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      modules, buildModules, colorMode, ssr, pwa, tailwindcss, css, postcss, devtools
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @vite-pwa/nuxt@0.0.7, @nuxtjs/google-fonts@3.0.1, @nuxt/image-edge@1.0.0-rc.1-28126030.07836ae
- Build Modules:    @nuxtjs/color-mode@3.3.0

### Reproduction

  at Object.<anonymous> (node_modules/ansi-align/index.js:3:21)
  at async Promise.all (index 0)
  at async normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:2140:17)
  at async installModule (/home/foddie/node_modules/@nuxt/kit/dist/index.mjs:2407:95)
  at async initNuxt (/home/foddie/node_modules/nuxt/dist/index.mjs:2928:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:204:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:248:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:48:20)

### Describe the bug

 ERROR  Cannot start nuxt:  require() of ES Module

**Comment by NozomuIkuta** [comment]
Unfortunately, it's not a reproduction by which people in community could help you.
Rather, it's a log.

Would you use the following templates as instructed in bug report template?

> Please use a template below to create a minimal reproduction
> 👉 https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz
> 👉 https://codesandbox.io/p/github/nuxt/starter/v3-codesandbox

Or, if the bug doesn't happen in these environments, you can share a link to GitHub repository.

**Comment by Foddie2** [comment]
> Unfortunately, it's not a reproduction by which people in community could help you. Rather, it's a log.
> 
> Would you use the following templates as instructed in bug report template?
> 
> > Please use a template below to create a minimal reproduction
> > 👉 https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz
> > 👉 https://codesandbox.io/p/github/nuxt/starter/v3-codesandbox
> 
> Or, if the bug doesn't happen in these environments, you can share a link to GitHub repository.

Hi @NozomuIkuta this is the github [repo](https://github.com/Foddie2/SweetsPot-Cakes.git)

**Comment by NozomuIkuta** [comment]
@Foddie2 

Thank you, but I got 404 error.
Is it a private repo, or is there a typo in URL?

**Comment by Foddie2** [comment]
> ### Environment
> * Operating System: Linux
> * Node Version:     v16.17.0
> * Nuxt Version:     3.5.3
> * Nitro Version:    2.4.1
> * Package Manager:  yarn@1.22.19
> * Builder:          vite
> * User Config:      modules, buildModules, colorMode, ssr, pwa, tailwindcss, css, postcss, devtools
> * Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @vite-pwa/nuxt@0.0.7, @nuxtjs/google-fonts@3.0.1, @nuxt/[image-edge@1.0.0-rc.1-28126030.07836ae](mailto:image-edge@1.0.0-rc.1-28126030.07836ae)
> * Build Modules:    @nuxtjs/color-mode@3.3.0
> 
> ### Reproduction
> at Object. (node_modules/ansi-align/index.js:3:21) at async Promise.all (index 0) at async normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:2140:17) at async installModule (/home/foddie/node_modules/@nuxt/kit/dist/index.mjs:2407:95) at async initNuxt (/home/foddie/node_modules/nuxt/dist/index.mjs:2928:7) at async load (node_modules/nuxi/dist/chunks/dev.mjs:204:9) at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:248:5) at async _main (node_modules/nuxi/dist/cli.mjs:48:20)
> 
> ### Describe the bug
> ERROR Cannot start nuxt: require() of ES Module
> 
> ### Additional context
> _No response_
> 
> ### Logs
> _No response_





> @Foddie2
> 
> Thank you, but I got 404 error. Is it a private repo, or is there a typo in URL?

It was private, I just made public.

**Comment by danielroe** [comment]
I would guess this is a package manager issue, as evidenced by the warnings when installing:

![CleanShot 2023-07-03 at 13 04 01](https://github.com/nuxt/nuxt/assets/28706372/6a8520ae-3d7e-426d-aeda-82afdff0a175)

See if you can identify what package/module is pulling in the dependency. You might try using yarn resolutions to force the right version of the package to install.

**Comment by Foddie2** [comment]
@danielroe thanks for support. I managed to fix the error in production by resolving my dependancies by adding this code to my package.json

  "resolutions": {
    "chalk": "^4.0.0",
    "nanoid": "3.3.6",
    "strip-ansi": "^6.0.0",
    "string-width": "^4.2.3",
    "wrap-ansi": "^8.1.0",
    "@nuxt/vite-builder": "3.6.1"
  },

Still I cannot load my project locally as it still gives me the same error.

ERROR  Cannot start nuxt:  require() of ES Module
