### ISSUE TITLE
[@nuxt/test-utils] nuxt shouldn't rebuild from scratch every time a test re-runs

### ISSUE THREAD

**Issue by fabis94** [nuxt/nuxt#21906]
### Describe the feature

It seems like irregardless of the parameters I pass into `setup` from `@nuxt/test-utils`, vitest always re-builds the entire app, even if nothing changed in it and the only change was in the test file.

I can pre-build the app and disable the test build step using `build: false`, but even that wasn't trivial to configure (because it always tries to use its own randomly generated build folder) and it would be better to be able to re-build during testing just when it's actually needed not on every test run.

For anyone interested, this is what I had to get done to get the tests to run from the standard `.output` directory:

```random.spec.ts
// Basic nuxt e2e test with vitest
import { createPage, setup } from '@nuxt/test-utils'
import { describe, it, expect } from 'vitest'
import path from 'path'

const mainOutputDir = path.resolve(__dirname, '../../.output')

describe('viewer', async () => {
  //
  await setup({
    buildDir: mainOutputDir,
    build: false,
    nuxtConfig: {
      buildDir: mainOutputDir,
      nitro: {
        output: {
          dir: mainOutputDir
        }
      }
    }
  })

  it('renders the viewer', async () => {
    const page = await createPage('/projects/9387e7e4c2/models/51c7c5b8eb')
    await page.waitForSelector('#speckle')
    const content = await page.content()
    expect(content).toMatch('helloworld')
  }, 100000)
})

```

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
completely agree. let's track in https://github.com/nuxt/nuxt/issues/15186
>
