### ISSUE TITLE
Compression brotli/gzip not work in file .html

### ISSUE THREAD

**Issue by ubay1** [nuxt/nuxt#21905]
### Describe the feature

in nuxt3 .html files do not compress files that have the .html extension

![image](https://github.com/nuxt/nuxt/assets/33889018/3fca262d-f161-4a1e-a02a-14a2a90cc46e)

how do you make .html files in nuxt 3 compressed as done in the project that uses sveltekit below?

![image](https://github.com/nuxt/nuxt/assets/33889018/d34ce11f-7303-4d00-9959-dd0371e797a9)

### Additional information

- [ ] Would you be willing to help implement this feature?
- [x] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Are those prerendered routes or are you running a server?

**Comment by ubay1** [comment]
@danielroe server.

**Comment by ubay1** [comment]
here is the sveltekit adapter node link using gzip/brotli.

maybe it can be used in nuxt 3.

 https://github.com/sveltejs/kit/pull/1693
