### ISSUE TITLE
WebSockets doesnt work correctly when using ngrok for https

### ISSUE THREAD

**Issue by SebbeJohansson** [nuxt/nuxt#21907]
### Environment

Nuxt project info:
------------------------------
- Operating System: Windows_NT
- Node Version:     v18.12.1
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      devtools, vite
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

1. Create a nuxt3 project using `npx nuxi@latest init {project_name}`
2. Start project.
3. Start node tunnel with ngrok.
4. Load page.
5. See that it is producing an error.
![image](https://github.com/nuxt/nuxt/assets/5083273/12395abb-2c66-47f1-b2ad-bfb20c6f07bc)

Example ngrok tunnel config:
```
tunnels:
  node:
    proto: http
    addr: 127.0.0.1:3000
    hostname: dragon.revolutionrace.se
```

### Describe the bug

Websockets work out of the box with ngrok so this should just work, but it doesn't seem to be possible right now.
* Using just the base setup described in the reproduction part just results in it failing because it is running in `ws`.
* Changing nuxt.config to use specifically `wss` results in a reload loop.
* Ive tried to start nuxt with `--https` but that didn't work either.

I have tried basically everything in the existing issues on github. For example: 
https://github.com/nuxt/nuxt/issues/12748#issuecomment-1397234718

**Comment by SebbeJohansson** [comment]
Looked a bit more into this, and it is working with vue3 and vite using the vue template `yarn create vite my-vue-app --template vue` and starting it with `yarn dev --port 3000 --host 127.0.0.1` so this seems to only be an issue with nuxt.

**Comment by SebbeJohansson** [comment]
@danielroe I would love it if you could check this one since this is completely blocking us from starting the migration from nuxt2 to nuxt3. Let me know if i have misunderstood something and if i can help debugging this.

**Comment by danielroe** [comment]
@pi0 and I were talking about this just the other day and IIRC is already working on this.

**Comment by SebbeJohansson** [comment]
@danielroe that sounds awesome. When you say "is already working on this" do you mean vite? Saw that you added "upstream".

**Comment by SebbeJohansson** [comment]
@pi0 and @danielroe any news on this?

**Comment by SebbeJohansson** [comment]
@pi0 hi! We are still hoping for a fix on this. Right now we are completely blocked from moving to nuxt3 because this is a dealbreaker.

**Comment by danielroe** [comment]
This is absolutely on the list, but let's track upstream in https://github.com/unjs/nitro/issues/678.

**Comment by SebbeJohansson** [comment]
Sounds great!
