### ISSUE TITLE
Missing a get started with server in documentation

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt/nuxt#21908]
### Describe the feature

Hello,

Currently, nav is looking like this

![image](https://github.com/nuxt/nuxt/assets/45267552/d698d4ae-d261-4d7b-b50d-d750fcd993f2)

But I think that we could add an item about the basic usage of API (a server get started). This could help new comer to have a better understanding of Nuxt.

_This message made me think of this: https://discord.com/channels/473401852243869706/473406506579263488/1125352768975155292_

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Good idea!

**Comment by doganalper** [comment]
I can start working on this on my free time if no one is willing to/started already. Is there way to open docs on local? @danielroe

**Comment by Barbapapazes** [comment]
> I can start working on this on my free time if no one is willing to/started already. Is there way to start docs on local? @danielroe 

Could help if needed

**Comment by doganalper** [comment]
@Barbapapazes Opened a PR for this, can you check and maybe tell me anything wrong or lacking?

**Comment by Barbapapazes** [comment]
> @Barbapapazes Opened a PR for this, can you check and maybe tell me anything wrong or lacking?

Absolutely, I can!
