### ISSUE TITLE
Hydration error for slot "inheritance" on dynamic components

### ISSUE THREAD

**Issue by FreekVR** [nuxt/nuxt#21915]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.15.0
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.6.0
- Builder:          vite
- User Config:      extends, telemetry, ssr, nitro, fontMetrics, routeRules, runtimeConfig, build, modules, components, bugsnag, devtools, i18n, app, dnGraphqlClient, vite, plugins
- Runtime Modules:  @nuxtjs/fontaine@0.4.0, @pinia/nuxt@0.4.11, @nuxt/devtools@0.6.6, nuxt-bugsnag@5.9.2, @digitalnatives/css-variables/nuxt@5.1.0, @digitalnatives/graphql-client@3.2.2, @nuxtjs/i18n@8.0.0-beta.12
- Build Modules:    -
------------------------------

### Reproduction

Setting up a component inheritance pattern:

- With ssr: true...
- Base component with a root-level `<component>` element and one or more slots
- An extending component which "inherits" the slots of the base component using `$slots` in the template;
- Use the extending component somewhere
- On the server, an error is thrown: `[1:54:29 PM] [Vue warn]: Property "name" was accessed during render but is not defined on instance.`
- On the client, a hydration error is thrown: SSR renders no content within the slots, client-side the component is rendered correctly however

See https://codesandbox.io/p/github/nuxt/starter/csb-rhhp8s/draft/determined-joliot?file=/app.vue:3,69

### Describe the bug

It seems server-side there is some problem with SSR trying to pass slots to a dynamic `<component>`

I would expect this pattern to work, but somehow the slot name is getting lost somewhere

```
<template>
    <component
        :is="element"
    >
        <slot />
    </component>
</template>

<script>
'use strict';

export default {
    props: {
        element: {
            type: String,
            required: false,
            default: 'button'
        }
    }
};
</script>
```

```vue
<template>
  <BaseComponent>
    <template v-for="(_, name) in $slots" v-slot:[name]="scope">
      <slot :name="name" v-bind="scope" />
    </template>
  </BaseComponent>
</template>

```

**Comment by danielroe** [comment]
This sounds like it's a Vue issue. Would you check with https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter to see if it can be reproduced without Nuxt?

**Comment by FreekVR** [comment]
Thanks @danielroe ,

I was able to confirm this issue is in Vue SSR as you suggested, I'll open an upstream issue there.
https://stackblitz.com/edit/github-u4xmkj?file=src%2Fcomponents%2FDynamic.vue,src%2FApp.vue,src%2Fcomponents%2FExtend.vue
