### ISSUE TITLE
Styles set in nuxt.config.ts css prop are not part of the build

### ISSUE THREAD

**Issue by LukasHirt** [nuxt/nuxt#21911]
### Environment

- Operating System: Darwin
- Node Version:     v16.18.1
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.2
- Package Manager:  npm@8.19.2
- Builder:          vite
- User Config:      build, routeRules, runtimeConfig, modules, i18n, css, plugins, devtools, eslint, vite, nitro, sourcemap, typescript
- Runtime Modules:  @nuxtjs/eslint-module@4.1.0, @nuxtjs/i18n@8.0.0-beta.12, @bootstrap-vue-next/nuxt@0.1.2, nuxt-jsonld@2.0.8
- Build Modules:    -

### Reproduction

I tried to make a reproduction in the stackblitz but somehow it seemed to work there. I am hoping then that maybe you can at least point me to the right direction and I can either find out the cause of this issue or at least find a way to reproduce it. Here are at least some tiny details:

CSS config in nuxt.config.ts:

`css: ['vue-final-modal/style.css', '~/assets/css/main.scss'],`

main.scss file includes import of bootstrap-vue-next and some separate files like e.g. variables.scss.

### Describe the bug

After updating Nuxt to version 3.6, the styles in our app are broken which forces us into staying at version 3.5. When opening the built output, the styles are not loaded. Styles from within pages and components are loaded fine but not those imported via css config prop in nuxt.config.ts.

There is also no error or warning when running the build or preview command. The strange thing also is that the styles are there when running the dev command.

**Comment by danielroe** [comment]
This has been resolved in https://github.com/nuxt/nuxt/pull/21864.
