### ISSUE TITLE
Cloudflare Workers Favicon Broken on Nuxt 

### ISSUE THREAD

**Issue by Geometrically** [nuxt/nuxt#21923]
### Environment

This is likely irrelevant to the issue at hand (tested with multiple OSes)

- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.6.1`
- Nitro Version:    `2.5.2`
- Package Manager:  `pnpm@8.6.0`
- Builder:          `vite`
- User Config:      `devtools`, `nitro`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

1. git clone https://github.com/Geometrically/repro-nuxt-favicon
2.`pnpm run build`
3.`npx wrangler dev`
4. Navigate to http://localhost:3000/favicon.ico
5. Notice that the favicon is errored

### Describe the bug

When building and running Nuxt on Cloudflare Workers, the favicon fails to be served properly. 

Instead of serving from static assets, it returns a garbage/placeholder GIF for the path `favicon.ico`. If it is not named `favicon.ico` but still ends in `.ico`, it attempts to server-render the path as a route.

### Additional context

Right now, the favicon path is returning the code shown here in nitro: https://github.com/unjs/nitro/blob/1950d1e24ea8463681a35fc48da8cbc09fe16774/src/runtime/renderer.ts#L18.

This seems to be related to this PR: https://github.com/unjs/nitro/pull/933.

Other assets in the public directory work fine, but not ones that end specifically in .ico.

### Logs

```shell-script
[mf:err] Error: ENOTDIR: not a directory, open '/Users/geometrically/Documents/Coding/modrinth/knossos/.output/public/favicon.ico/index.html'
```

**Comment by danielroe** [comment]
cc: @pi0

**Comment by Hebilicious** [comment]
@danielroe my apologies, I accidentally closed this issue https://github.com/unjs/nitro/issues/281

**Comment by danielroe** [comment]
closing to track in https://github.com/unjs/nitro/issues/281
