### ISSUE TITLE
Implement Shallow routing in nuxt 3

### ISSUE THREAD

**Issue by vietanhbui** [nuxt/nuxt#21925]
### Describe the feature

Implement Shallow routing in nuxt 3

### Additional information

- [x] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
What do you mean?

**Comment by vietanhbui** [comment]
@danielroe in next have shallow routing, nuxt 3 can be implement that feature?

**Comment by manniL** [comment]
Closing here for now. If someone has a similar request and *can provide more info*, **please open a new issue** and feel free to link this one here.
