### ISSUE TITLE
Component appears to be untyped in template block

### ISSUE THREAD

**Issue by niklas-may** [nuxt/nuxt#21933]
### Environment

- Operating System:        Darwin
- Node Version:                v18.14.0
- Nuxt Version:                 3.6.1
- Nitro Version:                2.5.2
- Package Manager:       yarn@1.22.19
- Builder:                          vite
- User Config:                 -
- Runtime Modules:        -
- Build Modules:             -

**VsCode 1.79.2**
- vscode.typescript-language-features:      disabled
- Vue.volar:                                                      1.8.3, enabled
- Vue.vscode-typescript-vue-plugin:           1.8.3, enabled

### Reproduction

https://github.com/niklas-may/nuxt-module-issue-reproduction

### Describe the bug

**Preface**
_Thank you for your amazing work on Nuxt!  I am not sure where this issue is best raised, Nuxt, VsCode or Vue. But due to the special typescript tooling with auto imports, I thought it's best to start here, and would be happy to hear if anybody observed a similar behaviour or has a solution._ 

**Description**
When I open `~/.nuxt/components.d.ts` in VsCode and hover over an imported component, VsCode IntelliSense popover displays the correct types for this component.
But when I use the component in any other components template block, for example `~/app.vue`, the typing is missing the prop types.

### Component and Type Definitions

`~/../src/runtime/MyButton.vue`

```vue
<template>
  <div style="border: 1px solid pink">
    <slot />
  </div>
</template>
<script setup lang="ts">
withDefaults(
  defineProps<{
    variant: "fill" | "ghost";
  }>(),
  { variant: "fill" }
);
</script>
```

`~/.nuxt/components.d.ts`

```TypeScript
declare module 'vue' {
  export interface GlobalComponents {
    //...
    'MyButton': typeof import("../../src/runtime/components/MyButton.vue")['default']
    //...
  }
}

export const MyButton: typeof import("../../src/runtime/components/MyButton.vue")['default']

export const componentNames: string[]
```

### Correct Intellisense

VsCode popopver hovering `'MyButton'` in `~/.nuxt/components.d.ts`

```TypeScript
(property) GlobalComponents['MyButton']: __VLS_WithTemplateSlots<DefineComponent<{
    variant: {
        type: PropType<"fill" | "ghost">;
        required: true;
        default: string;
    };
}, {}, unknown, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, ... 5 more ..., {}>, {
    ...;
}>
````

### Wrong Intellisense

VsCode popopver hovering `<MyButton />` in the template block of `~/app.vue` (or any other template)

```TypeScript
(property) 'MyButton': DefineComponent<{}, {}, any>
```

### Additional context

The above example is the current state of the reproduction repo. But a different, but similar behavior happened in other reports (for example a yarn workspace repo). Strange enough, sometimes, it works fine...

**Comment by robinscholz** [comment]
We are running into similiar problems with auto imported components, either from plugins, modules and even the `./components` directory. Also running vscode as our IDE.

However, hovering a component within `~/.nuxt/components.d.ts` often already shows something like:

```
(property) GlobalComponents['BaseAnimation']: DefineComponent<{}, {}, any>
```

Eventhough the component is written with `<script setup lang="ts">`

Any pointers/help would be much appreciated.

**Comment by danielroe** [comment]
I suspect this is an issue stemming from a volar update. If you can reproduce when running `vue-tsc`, then would you try installing an older version of `vue-tsc` and rerunning?

**Comment by b-jan** [comment]
Have you solved this issue @niklas-may ?

**Comment by niklas-may** [comment]
@b-jan unfortunately no. Restarting volar helps.

**Comment by danielroe** [comment]
If restarting volar helps, then this is likely a volar issue and should be raised there.

**Comment by danielroe** [comment]
Closing as it's not clear what we could do to resolve this issue, and I don't believe it's a Nuxt issue.

**Comment by jeandlv** [comment]
I had a similar issue on some components and not on on others and I couldn't find out why. I finally realize that **removing mixins** used in the component fix the issue. Although mixins are still supported with vue 3, they seem to cause type issues.
