### ISSUE TITLE
[Proposal] Move examples to bottom in docs search result

### ISSUE THREAD

**Issue by jd-solanki** [nuxt/nuxt#21932]
### Describe the feature

> _I created this issue to highlight my discord [message](https://discord.com/channels/473401852243869706/473407466630152201/1119174763374452746) after reading this issue (because I think both will improve the search): #21930_

Can we move example to bottom while searching because everytime I search & hit enter I realize I get navigated to sandbox example instead of actual docs.
![image](https://github.com/nuxt/nuxt/assets/47495003/01b2ef65-bbbe-4200-a26d-4f5f6dcfbf80)

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Totally agree. We should somehow deprioritise them. 👍 

cc: @Atinux
