### ISSUE TITLE
Cannot deploy to cloudflare

### ISSUE THREAD

**Issue by EmilyYond** [nuxt/nuxt#21938]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.16.1`
- Nuxt Version:     `3.6.0`
- Nitro Version:    `2.5.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `app`, `devtools`, `vite`, `build`, `vue`, `css`, `modules`, `postcss`, `components`, `strapi`, `image`
- Runtime Modules:  `@nuxtjs/strapi@1.9.3`, `@pinia/nuxt@0.4.11`, `@nuxt/image@1.0.0-rc.1`
- Build Modules:    `-`

### Reproduction

I'm trying to deploy my site in SSR mode, but whenever I try either on pages or as a worker it fails. I _think_ its because of google maps, whenever I add in @fawmi/vue-google-maps or vue3-google-map on a clean install the error happens, but this is my full package.json just in case its helpful.

Package.json:
```
"devDependencies": {
    "@nuxt/devtools": "latest",
    "@nuxt/image": "^1.0.0-rc.1",
    "@types/node": "^18",
    "autoprefixer": "^10.4.14",
    "nuxt": "^3.6.0",
    "postcss": "^8.4.24",
    "prisma": "^4.16.1",
    "sass": "^1.63.6",
    "sass-loader": "^13.3.2",
    "tailwindcss": "^3.3.2",
    "typescript": "latest",
  },
  "dependencies": {
    "@fawmi/vue-google-maps": "0.9.72",
    "@nuxtjs/strapi": "^1.9.3",
    "axios": "^1.4.0",
    "dayjs": "^1.11.8",
    "dotenv": "^16.3.1",
    "node-ical": "^0.16.1",
    "pinia": "^2.1.4",
    "postcode": "^5.1.0",
    "swiper": "^10.0.2",
    "v-calendar": "^2.4.1",
    "vite-svg-loader": "^4.0.0",
    "vue-imask": "^7.0.1",
    "vue-social-sharing": "^3.0.9",
    "vue3-tel-input": "^1.0.4"
  }
```

Wrangler.toml:
```
main = "./.output/server/index.mjs"
workers_dev = true
compatibility_date = "2022-09-01"
account_id = "***"
[site]
bucket = ".output/public"
```

### Describe the bug

Build fails with error defineComponent is not defined. It fails during the deploy/publish to cloudflare stage, as below:

![Screenshot 2023-07-04 at 10 15 25](https://github.com/unjs/nitro/assets/128067060/04044a92-f199-4bf4-b3ed-51f65d4b10a3)

### Additional context

I have followed https://nitro.unjs.io/deploy/providers/cloudflare but keep hitting this same error and I don't know where to even begin debugging this. Does anyone have any ideas?

**Comment by oritwoen** [comment]
Which version of wrangler are you using? I remember that a few weeks ago I was checking wrangler version 3.x and I couldn't come to an agreement with it in terms of building and with 2.20.0 everything worked beautifully.

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

My guess is that perhaps you need to add the google map library to `build.transpile`.

**Comment by EmilyYond** [comment]
@oritwoen I am using wrangler 3 but I have a basic test nuxt 3 app which can deploy using 3, so I'm not sure its that, but thank you for the suggestion!

@danielroe I just spent the morning ripping it apart more to determine where the issue lies, as today the google maps package seemed to work. I managed to route it down to the `vue-imask` package and its `Mask` component that I am using so I added that package to `build.transpile` and that seems to of worked! What does this actually do? How do I know when I need to add packages to this? Thank you so much for your help!

Another quick question about cloudflare if thats okay, is there a preference between using a worker or pages for a nuxt ssr site that utilises the server for apis too? I'm new to using cloudflare and don't understand the difference between the two for hosting nuxt. Thanks!

**Comment by danielroe** [comment]
Great work debugging.

Using `build.transpile` ensures we process the source code of the dependency with nuxt/vite plugins. (For example, I think this likely would ensure that it imports the 'same' vue dependency as the rest of the Nuxt app.) Normally you shouldn't need to add packages to this, but it is a useful escape-hatch when you encounter bugs.

For Cloudflare, I would recommend Pages. It is just as good for APIs and is the direction CF will be developing their platform.

**Comment by EmilyYond** [comment]
@danielroe ahh I see, thank you so much you've been really helpful!
