### ISSUE TITLE
hydration children mismatch when using placeholder on input

### ISSUE THREAD

**Issue by zecar** [nuxt/nuxt#21943]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.19.1`
- Nuxt Version:     `3.5.1`
- Nitro Version:    `2.4.1`
- Package Manager:  `npm@9.7.1`
- Builder:          `vite`
- User Config:      `app`, `modules`, `htmlValidator`, `css`, `components`, `postcss`, `i18n`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.12`, `@pinia/nuxt@0.4.11`, `@vueuse/nuxt@10.1.2`, `nuxt-jsonld@2.0.8`, `@nuxtjs/html-validator@1.2.5`
- Build Modules:    `-`

### Reproduction

get this BaseInput.vue
```
<template>
  <input
    :type="type"
    class="rounded-md bg-white text-sm text-gray-700 shadow-sm"
    :class="cssClasses"
    :value="modelValue"
    v-bind="$attrs"
    @input="$emit('update:modelValue', $event.target.value)"
  />
  <p v-if="error" class="text-red-500 m-1 text-xs">{{ error }}</p>
</template>
<script>
export default defineNuxtComponent({
  name: 'BaseInput',
  inheritAttrs: false,
  emits: ['update:modelValue'],
  props: {
    block: {
      type: Boolean,
      default: false,
    },
    type: {
      type: String,
      default: 'text',
    },
    modelValue: {
      type: String,
      default: '',
    },
    error: {
      type: String,
      default: '',
    },
  },
  computed: {
    cssClasses() {
      const classes = []
      if (this.block) {
        classes.push('w-full')
      }
      if (this.error) {
        classes.push('border-red-500')
      } else {
        classes.push('border-gray-200')
      }
      return classes
    },
  },
})
</script>

```

then use it like this
```
<BaseInput v-model="emailFilter" placeholder="Email..." />

// emailFillter is declared in data() as ''
```

### Describe the bug

i get hydration children mismatch when using placeholder on input

the REALLY strange part is that if I put "Email..." as placeholder, i get the error. If I put "Em ail..." the error goes away

### Additional context

this is happening on chrome
works ok in firefox

**Comment by zecar** [comment]
quick update:
```
<input
        type="text"
        placeholder="Email"
      />
```

If i put this anywhere in site I get the error

**Comment by zecar** [comment]
THIS WAS CAUSED BY LASTPASS CHROME EXTENSION

**Comment by MilenaPetkanova** [comment]
> THIS WAS CAUSED BY LASTPASS CHROME EXTENSION

Thankyou for solving the mystery, sir!
For me, it was another password management extension - Keeper.
