### ISSUE TITLE
router props function is ignored

### ISSUE THREAD

**Issue by zecar** [nuxt/nuxt#21953]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.19.1`
- Nuxt Version:     `3.5.1`
- Nitro Version:    `2.4.1`
- Package Manager:  `npm@9.7.1`
- Builder:          `vite`
- User Config:      `app`, `modules`, `htmlValidator`, `css`, `components`, `postcss`, `i18n`, `hooks`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.12`, `@pinia/nuxt@0.4.11`, `@vueuse/nuxt@10.1.2`, `nuxt-jsonld@2.0.8`, `@nuxtjs/html-validator@1.2.5`
- Build Modules:    `-`

### Reproduction

inside the pages:extend hook
```
pages.push({
	name: 'some-route',
	path: '/some-route',
	file: '~/some-pages/some-route.vue',
	props: () => ({ someProp: 'modified value' }),
})
```

page component
```
export default defineNuxtComponent({
  name: 'some-route',
  props: {
    someProp: {
      type: String,
      default: 'original value',
    },
  },
})
```

### Describe the bug

the props function is ignored. The page component will not receive someProp with a different value than the default one

if props is declared like this, it works
```
pages.push({
	name: 'some-route',
	path: '/some-route',
	file: '~/some-pages/some-route.vue',
	props: { someProp: 'modified value' },
})
```

### Additional context

this worked properly in nuxt v2

**Comment by danielroe** [comment]
You cannot pass non-serialisable values in `pages:extend` as they need to be included in the runtime build. For non-serialisable values, you can use `app/router.options`: https://nuxt.com/docs/guide/going-further/custom-routing#using-router-config.

**Comment by zecar** [comment]
but 
`Nuxt will not augment any new routes you return from the routes function with metadata defined in definePageMeta of the component you provide. If you want that to happen, you should use the pages:extend hook which is [called at build-time](https://nuxt.com/docs/api/advanced/hooks#nuxt-hooks-build-time).`

so this will mean that i will not take advantage of the page meta.. 

so I guess I will have to wait for this to be added in nuxt, right?

**Comment by danielroe** [comment]
You will receive the meta in the `routes()` function and can do what you want with it.

**Comment by kingxjs** [comment]
I found this issue when upgrading nuxt3 from nxut2, so the only way is to define it using useRoute()? Is using defineNuxtComponent({meta:{base:'/'}}) no longer effective?
