### ISSUE TITLE
Docs: The url to this repository is invalid.

### ISSUE THREAD

**Issue by ace9527x** [nuxt/nuxt#21950]
### Environment

文档错误

### Reproduction

https://nuxt.com.cn/docs/api/components/nuxt-page

### Describe the bug

![image](https://github.com/nuxt/nuxt/assets/49401748/33097bf8-178a-494f-b291-1e17956d6161)
示例在线预览无法访问

**Comment by danielroe** [comment]
That website is not actually created by us; it's a community site and they haven't yet updated the link.
