### ISSUE TITLE
Lighthouse test Avoid serving legacy JavaScript to modern browsers is failing

### ISSUE THREAD

**Issue by wokalek** [nuxt/nuxt#21969]
### Environment

<details>
  <summary>nuxi info</summary>
  
  ```
  Nuxi 3.6.2                                                                                                                                                   01:45:29
                                                                                                                                                               01:45:30
  RootDir: /home/wok/projects/wokalek/nuxt                                                                                                                     01:45:30
  Nuxt project info:                                                                                                                                           01:45:30
  
  ------------------------------
  - Operating System: Linux
  - Node Version:     v20.3.1
  - Nuxt Version:     3.6.2
  - Nitro Version:    2.5.2
  - Package Manager:  pnpm@8.6.5
  - Builder:          vite
  - User Config:      telemetry, srcDir, app, modules, runtimeConfig, vite, css, postcss, colorMode, device, image, content, pwa, robots, sitemap, schemaOrg
  - Runtime Modules:  @nuxtjs/robots@3.0.0, @nuxtjs/color-mode@3.3.0, @nuxtjs/fontaine@0.4.0, @nuxtjs/device@3.1.0, @nuxt/content@2.7.0, @nuxt/image@1.0.0-rc.1, @vueuse/nuxt@10.2.1, @vite-pwa/nuxt@0.1.0, nuxt-typed-router@3.2.3, nuxt-svgo@3.2.0, nuxt-simple-sitemap@2.7.0, nuxt-schema-org@2.2.0, nuxt-lodash@2.5.0
  - Build Modules:    -
  ------------------------------
  ```
</details>

### Reproduction

You can run lighthouse on [nuxt.com](https://nuxt.com), same error, but trying on my local project.

### Describe the bug

Lighthouse have error "Avoid serving legacy JavaScript to modern browsers"

![image](https://github.com/nuxt/nuxt/assets/23037847/96bfb7d0-78bd-484a-92f7-59ecc8cc5d2c)

### Additional context

Trying to set in config `vite.build.target = 'esnext'`, it's not helpful. Size of site resources not change.

**Comment by warflash** [comment]
> You can run lighthouse on [nuxt.com](https://nuxt.com/), same error

lighthouse on nuxt.com doesn't show that for me 🤔
![image](https://github.com/nuxt/nuxt/assets/22006082/23f852cb-e2fc-403b-8a4c-f63e05c46506)

**Comment by wokalek** [comment]
> > You can run lighthouse on [nuxt.com](https://nuxt.com/), same error
> 
> lighthouse on nuxt.com doesn't show that for me 🤔 ![image](https://user-images.githubusercontent.com/22006082/251313823-23f852cb-e2fc-403b-8a4c-f63e05c46506.png)

Yeah, I think those are chrome extensions. Thanks for the tip!
