### ISSUE TITLE
I can't disable app.vue

### ISSUE THREAD

**Issue by flvffywvffy** [nuxt/nuxt#21964]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.17.1`
- Nuxt Version:     `3.6.1`
- Nitro Version:    `2.5.2`
- Package Manager:  `npm@9.6.7`
- Builder:          `vite`
- User Config:      `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

[https://stackblitz.com/edit/github-e9mmcr](https://stackblitz.com/edit/github-e9mmcr)

### Describe the bug

I don't want to use app.vue, so I deleted it, and now I get this error:
```
Internal server error: Failed to resolve import "/Users/xxx/Desktop/xxx/app.vue" from "virtual:nuxt:/Users/xxx/Desktop/xxx/.nuxt/app-component.mjs". Does the file exist?
```
How do I fix this?

**Comment by ChillPapa** [comment]
you need an `app.vue`

just put this in it:
```vue
<template>
  <NuxtLayaout>
    <NuxtPage/>
  </NuxtLayout>
</template>
```
