### ISSUE TITLE
Expose URL (server/port) for "nuxi dev" as environment variable

### ISSUE THREAD

**Issue by imphil** [nuxt/nuxt#21970]
### Describe the feature

I'm creating an application where I need the absolute URL to the site within my code (to create a RSS feed actually). For Netlify builds (production and PR previews) I'm able to use the [Netlify-provided](https://docs.netlify.com/configure-builds/environment-variables/) environment variable `DEPLOY_PRIME_URL`, which will contain something like `https://main--yourproject.netlify.app`.

For development with `nuxi dev` I couldn't find equivalent information. The process environment contains `NUXT_VITE_NODE_OPTIONS` in the form of

```
  NUXT_VITE_NODE_OPTIONS: '{"baseURL":"http://localhost:3000/__nuxt_vite_node__","root":"/my/root","entryPath":"/my/root/node_modules/nuxt/dist/app/entry.js","base":"/_nuxt/"}',
  NODE_ENV: 'development',
```

which I could leverage, but that feels unstable/hacky.

Is there another way to get the current url (`http://localhost:3000` in this case, but it could be any port or host, depending on what is determined at startup) within a Nuxt application? 

If there is no existing way, maybe an environment variable in the form of `NUXT_URL=http://localhost:3000` could be added?

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by ChillPapa** [comment]
im working on an implementation

**Comment by danielroe** [comment]
You can access `nuxt.options.devServer.port` and `nuxt.options.devServer.host`, which are set here:

https://github.com/nuxt/nuxt/blob/b0daaa8cbbdc6e180163363a8d8de766f467d6f9/packages/nuxi/src/commands/dev.ts#L148-L153

**Comment by ChillPapa** [comment]
it just wont build for some reason if i revert my changes it still wont build

**Comment by danielroe** [comment]
@ChillPapa What do you mean?

**Comment by ChillPapa** [comment]
i run `pnpm build` but then it says something like:
```
nuxi failed in 39s `unbuild`
```

**Comment by danielroe** [comment]
Best to open a new issue with a reproduction; that doesn't _sound_ related to this one.

**Comment by ChillPapa** [comment]
ok

**Comment by imphil** [comment]
@danielroe Thanks, much appreciated!

`nuxt.options.devServer.url` should do the trick -- but I have one probably naive follow-up question: how do I access `nuxt.options.devServer.url` in a server route? (I got cdnURL from the runtimeConfig but, that isn't an option here.)

**Comment by danielroe** [comment]
I would create a module that injects it into the runtime via `nuxt.options.nitro.virtual`.
