### ISSUE TITLE
How to access Custom Props from child pages

### ISSUE THREAD

**Issue by devzakir** [nuxt/nuxt#21976]
### Nuxi 3.6.1  
------------------------------
- Operating System: Darwin
- Node Version:     v18.16.1
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      runtimeConfig, app, css, modules, plugins, content, googleFonts, devtools
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @nuxt/content@2.7.0, @nuxt/image@1.0.0-rc.1, @nuxtjs/google-fonts@3.0.1
- Build Modules:    -
------------------------------

### Reproduction

I have tried to access the categories and productName but couldn't. Here is the screenshot of my code. 

<img width="1629" alt="image" src="https://github.com/nuxt/nuxt/assets/33604077/726a9c2b-cf4b-478c-9b8e-ecc53b7a7614">

### Describe the bug

I have tried to access the categories and productName but couldn't. Here is the screenshot of my code.

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by devzakir** [comment]
Thanks @danielroe for checking out. I was able to solve it by calling `$attrs.categories`, I have updated the docs and created a PR, here is the link 

https://github.com/nuxt/nuxt/pull/21977
