### ISSUE TITLE
setCookie ignored when SSR (feat. useAsyncData)

### ISSUE THREAD

**Issue by devops3199** [nuxt/nuxt#21978]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v16.19.0
- Nuxt Version:     3.5.0
- Nitro Version:    2.4.1
- Package Manager:  yarn@3.5.0
- Builder:          vite
- User Config:      app, css, ssr, modules, htmlValidator, runtimeConfig, alias, build, vite
- Runtime Modules:  @vueuse/nuxt@10.1.2, @pinia/nuxt@^0.4.10, @nuxtjs/html-validator@^1.2.4, nuxt-swiper@^1.1.0
- Build Modules:    -
------------------------------

### Reproduction

I'm afraid that the repository cannot be shared due to the company policy. My apologies.

### Describe the bug

`setCookie` works on CSR, but it ignores when it comes to SSR.

```
// src/app.vue

<template>
  code...
</template>
<script setup>
const {data} = await useAsyncData('items', async () => {
   const res = $fetch('/api/items');
   ...
   return res;
})
</script>
```

```
// server/api/items.get.ts

export default defineEventHandler(async (event) => {
    setCookie(event, 'test', 'setCookieFromSSR');
    ...
    return {data: {...}};
});
</script>
```

Rendering HTML with data is fine, but a cookie named `test` can't be seen anywhere in browser. It seems like fetching api's event and rendering HTML event are not the same event.

**Comment by danielroe** [comment]
In order to proxy cookies/headers, etc., you can use `useRequestFetch()`

**Comment by devops3199** [comment]
Although your prompt response, `useRequestFetch()` often fails under the same condition. The most promising result is to use `setCookie` in server middleware instead of endpoint files.

I am just curious that why the events must be separated when SSR? (one for the rendering HTML and one for the APIs)

**Comment by danielroe** [comment]
The reason is:

- `$fetch` is not associated with a particular request (for good reasons, like flexibility and DX) and we don't want headers/cookies 'leaking' between requests
- sharing cookies/authorization headers by default could lead to security issues or unintentional sharing of keys - we want users _explicitly_ opting-in when they want a 'proxied' fetch

**Comment by wenmigwang** [comment]
is there any doc about useRequestFetch in https://nuxt.com/docs/api/composables/?

**Comment by vibonacci** [comment]
`useRequestFetch()` only includes the browser cookies on the (initial) SSR call. After hydration, the cookies are not included.
