### ISSUE TITLE
.output/server/index.mjs cannot run standalone

### ISSUE THREAD

**Issue by bf** [nuxt/nuxt#21981]
### Environment

- Operating System: Linux
- Node Version:     v18.12.0
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      mode, editor, runtimeConfig, head, loading, css, modules, devServer, build, devtools
- Runtime Modules:  @nuxt/devtools@0.6.6
- Build Modules:    -

### Reproduction

1) run `yarn build` on dev system
2) copy .output folder to server with same architecture & same node version
3) run `node .output/server/index.mjs`

Expected: nuxt3 app starts and listens for requests
Actual: Several errors during startup due to missing libraries

### Describe the bug

I assumed the .output blob from nuxt build is standalone and able to run on the deployment server. 
However it seems I need to run `yarn install && yarn build` also on the server.

From security perspective, I would like to fully build/bundle the production nuxt3 webapp on my dev system and just ship the trusted .output folder to the server. 

### Additional context

Building docker container is a solution for this problem of shipping a "known-good", running app to the server for deployment.
However, I feel it is overkill.

It'd be great if nuxt3 build result in .output folder could run on a machine with same operating system and architecture and nodejs version without a problem.

Is this kind of deployment a goal for nuxt3 or do you always recommend to yarn install && yarn build on the deployment server?

**Comment by danielroe** [comment]
It _is_ meant to be standalone. If it is not working then there's an upstream bug in nitro we need to investigate. 
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by bf** [comment]
Will create repro. The error messages were mentioning `node-fetch-native` and `pg-native`. I saw there are some issues open with regards to `node-fetch-native` and a bug that it sometimes multiple `node-fetch-native` versions are installed. I also have this case in my project: `node-fetch-native@^1.0.2, node-fetch-native@^1.1.1, node-fetch-native@^1.2.0:`

**Comment by danielroe** [comment]
Try refreshing your lockfile and see if that makes a difference. This is likely an issue with nitro's hoisting algorithm.
