### ISSUE TITLE
Layers - public folder different on build

### ISSUE THREAD

**Issue by JulianMar** [nuxt/nuxt#21988]
### Environment

Stackblitz

### Reproduction

https://stackblitz.com/edit/nuxt-examples-suakka?file=nuxt.config.ts

### Describe the bug

Go to the /foo page in the reprodution in dev mode and once in build mode.

The images from the public folder are different. in the production build it's the image in the base layer. In dev mode it's using the correct overwritten image.

I would be open to create a PR, if I get some starting help by being pointed in the right direction. :)
Thanks for this awesome feature!

**Comment by rizhenkov** [comment]
I have faced this bug too

**Comment by phi0411141** [comment]
I am having same issue, extending public folder works fine in development, but when building, rollup tells that assets are missing, please externalize it.

**Comment by Laruxo** [comment]
I have a similar issue - I am not trying to overwrite `public` folder, just use all the assets from the `core` layer. When building the app that extends this layer, I get this warning:
```
/fonts/regular.woff2 referenced in /Users/***/packages/core/assets/main.css didn't resolve at build time, it will remain unchanged to be resolved at runtime
```

**Comment by danielroe** [comment]
This was resolved in https://github.com/nuxt/nuxt/pull/26163 from v3.11+.
