### ISSUE TITLE
loading indicator shows/resolves too quickly when changing query

### ISSUE THREAD

**Issue by danielroe** [nuxt/nuxt#21991]
**Reproduction**: https://stackblitz.com/edit/nuxt-starter-3ab9sw?file=app.vue

Whithout `:throttle="0"`, navigate to "blog" and then to page 2. Loading indication works. But now if you navigate to page 1, 3 or 4 it not works. This pages are in the same component `[page].vue` but with different "page" param. Slugs `/blog/page/1`, `/blog/page/2`...

If you add `:throttle="0"` the indicator appears but with a weird speed... starting/stopping quickly.

I think it's necessary to do an extra check... maybe something like:

```js
if (to === from || to.matched.every((comp, index) => {
  return comp.components && comp.components?.default === from.matched[index]?.components?.default && 
Object.values(to.params) === Object.values(from.params)
})) {
  indicator.finish();
}
```

This works for my example.

_Originally posted by @emaia in https://github.com/nuxt/nuxt/issues/21656#issuecomment-1616829484_

**Comment by mrkody** [comment]
Invalid comparison for arrays, I think the more correct way to resolve this bug is below:

```js
router.beforeResolve((to, from) => {
    if (to === from || to.matched.every((comp, index) => {
        return comp.components && comp.components?.default === from.matched[index]?.components?.default &&
            Object.values(to.params).toString() === Object.values(from.params).toString()
    })) {
        indicator.finish()
    }
})
```
