### ISSUE TITLE
Dead link in documentation

### ISSUE THREAD

**Issue by itsthejoker** [nuxt/nuxt#21990]
### Environment

N/a

### Reproduction

https://nuxt.com/docs/getting-started/views#advanced-extending-the-html-template

### Describe the bug

Click on "SEO and meta section" -- you'll get directed to https://nuxt.com/docs/getting-started/docs/getting-started/seo-meta, which doesn't exist.

### Additional context

I think it's rendered from here? https://github.com/nuxt/nuxt/blob/main/docs/1.getting-started/3.views.md?plain=1#L139

**Comment by ChillPapa** [comment]
it works for me
