### ISSUE TITLE
Importing components with alias in monorepo causes VSCode/Volar to fail finding modules/type declarations

### ISSUE THREAD

**Issue by samydoesit** [nuxt/nuxt#21996]
### Environment

- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.6.6
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/github/samydoesit/nuxt-monorepo-import-reproduction
https://github.com/samydoesit/nuxt-monorepo-import-reproduction

### Describe the bug

Hi, i am experiencing issues while importing components in a monorepo using an alias.

The problem arises when using VSCode with the Volar extension. Since our ui directory is located outside of the Nuxt project directory, VSode (Volar) is unable to locate the module or type declaration.

However, if i manually add the path of the alias to the "includes" field in nuxt's tsconfig, the resolution in VSCode works.

### Logs

```shell-script
Cannot find module '@ui/components/button/Button.vue' or its corresponding type declarations.
```

**Comment by nxmad** [comment]
That's also problem with Docker.
After dependencies installation nuxt generates correct tsconfig with my local absolute path to nuxt directory, however path inside container usually differs from local one, so it breaks type resolution in VSCode as well.

**Comment by maxdzin** [comment]
@nxmad is it resolved for you? I still have a problem with Docker and Nuxt v3.6.5.
