### ISSUE TITLE
custom layout makes useAsyncData run on the client

### ISSUE THREAD

**Issue by tasiotas** [nuxt/nuxt#21999]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Source:
https://stackblitz.com/edit/nuxt-starter-ufrun1?file=pages%2Fadmin.vue

Preview:
https://nuxtstarterufrun1-yc3l--3000--e809191e.local-credentialless.webcontainer.io/admin

Repro:
1. Open dev tools network tab
2. Open preview link above
3. Note fetch call. It shouldnt be there
4. Click link to index, then link back to admin
5. Note double fetch calls

### Describe the bug

Since v3.6 I am getting client calls from useAsyncData when using custom layout.

Thank you

**Comment by danielroe** [comment]
This stems from an upstream bug (https://github.com/vuejs/core/issues/6638), but we can investigate to see if we can work around it.

**Comment by pgraug** [comment]
Looks like it's the `await useAsyncData` in your admin layout that's causing problems.
It's part of a more general bug with top-level await in layout in Nuxt 3.6 (I just made my first issue describing it #22091)

I think removing the `await useAsyncData` from your layout will fix this but there might not be a great other place to put it depending on your project

**Comment by mercs600** [comment]
> This stems from an upstream bug ([vuejs/core#6638](https://github.com/vuejs/core/issues/6638)), but we can investigate to see if we can work around it.

@danielroe it was working in Nuxt < 3.6

**Comment by JonathanDoelan** [comment]
Workaround: https://github.com/nuxt/nuxt/issues/22091#issuecomment-1635366666
