### ISSUE TITLE
Base option in nuxtconfig doesn't change scripts/styles to actually be based on that link

### ISSUE THREAD

**Issue by mybearworld** [nuxt/nuxt#21992]
This makes uploading to GitHub Pages basically impossible.

> I'd like to upload my Nuxt app to GitHub and use GitHub Pages with it. A search on how to do that gives these two options:
>
> - Just uploading the `dist` folder. This defeats the point of open source, as it makes reading the code and contributing to it pretty much impossible.
> - Using the GitHub action. This works in the sense that the page is public and the HTML actually gets used for that page, that actually has nothing in it (of course, as it's a static site). > The imported Javascript, however, doesn't load. This is because the code gets fetched from https://username.github.io/whatever.js, instead of https://username.github.io/page/whatever.js. Sometimes something is said about the `base` option, but that makes no difference.
>
> So none of these work - how _do_ you use Nuxt with GitHub Pages, if you even can?
>
> _Originally posted by @mybearworld in https://github.com/nuxt/nuxt/discussions/21550_

**Comment by danielroe** [comment]
Check out https://nitro.unjs.io/deploy/providers/github-pages.

Nuxt supports `app.baseURL` which you can set to `/page/` (in your example)
