### ISSUE TITLE
Can't import anything from 'vue'

### ISSUE THREAD

**Issue by yaquawa** [nuxt/nuxt#22007]
### Environment

- Operating System: Darwin
- Node Version:     v18.15.0
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.1
- Package Manager:  pnpm@8.6.2
- Builder:          vite
- User Config:      ssr, modules, app, css, imports, ignore, build, vite, devtools
- Runtime Modules:  ./modules/bootstrap, @nuxt/devtools@0.6.6, nuxt-jsonld@2.0.8
- Build Modules:    -

### Reproduction

just try to import anything from 'vue'.

### Describe the bug

I can import from `#imports`, but I can't import types such as `InjectionKey` from '#imports', so I'd like to import directly from 'vue', but that give me an error: `TS2305: Module '"vue"' has no exported member 'InjectionKey'.`

The error disappears if I delete the `.nuxt` directory.

<img width="595" alt="image" src="https://github.com/nuxt/nuxt/assets/13927101/4e148667-afdc-462f-aea0-5809c4fada81">

**Comment by ChillPapa** [comment]
you don't need to import them they are auto imported

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by yaquawa** [comment]
@danielroe 
I have set `autoImport` to `false`.
I just want to import them explicitly.
I'm sorry but I can't provide you a reproduction on the web, this type error will only shown on the vscode or webstorm.
So, to reproduce just create a new project with `npx nuxi@latest init my-app` and set `autoImport` to false.

```
// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  imports: {
    autoImport: false,
  },
});
```

**Comment by danielroe** [comment]
Seems to work fine for me.
![CleanShot 2023-07-07 at 10.10.34.png](https://volta.s3.fr-par.scw.cloud/Clean_Shot_2023_07_07_at_10_10_34_2ff693067c.png)

**Comment by yaquawa** [comment]
Hello @danielroe, I wanted to inform you that I have tested the most recent version and the reported issue seems to be resolved. Great job!
