### ISSUE TITLE
[Documentation Request] Document `app` Directory

### ISSUE THREAD

**Issue by Hebilicious** [nuxt/nuxt#22008]
### Describe the feature

In the directory structure, the app directory isn't mentioned or referenced.
https://nuxt.com/docs/guide/directory-structure/assets

This can be used for `app.router.options.ts` (documented here https://nuxt.com/docs/guide/going-further/custom-routing#router-options) 

There might be more options I'm not aware of.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by titan-65** [comment]
Good feature to add to the documentation aspects of the framework. What exactly are your thought processes on this directory?

**Comment by Hebilicious** [comment]
cc @Atinux

**Comment by Atinux** [comment]
There is also the [spaLoadingIndicator]( https://nuxt.com/docs/api/configuration/nuxt-config#spaloadingtemplate)

Also one note regarding Nuxt 4 is the new directory structure RFC: https://github.com/nuxt/nuxt/discussions/20251

**Comment by Hebilicious** [comment]
@Atinux Thanks !
Regarding this RFC I left some feedback in that discussion thread.

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/18966.
