### ISSUE TITLE
[Documentation Request] Prerender section

### ISSUE THREAD

**Issue by Hebilicious** [nuxt/nuxt#22011]
## Details

There's enough here that is unique about Nuxt that I think it makes sense to have in our docs, and we can link out to Nitro where it makes sense

_Originally posted by @danielroe in https://github.com/nuxt/nuxt/issues/21987#issuecomment-1624835848_

**Comment by RyanClementsHax** [comment]
I'd be happy to help out here (you can assign it to me).

What features specifically were you looking to call out in the prerendering documentation?

**Comment by danielroe** [comment]
I think it would be good to:
* explain how the crawler works (and how dynamic routes are generated)
* mention `static` builds and providers that support it with extra features (like vercel, netlify, amplify + cloudflare pages)
* give an example of how to add routes (both at runtime with `prerenderRoutes` and at build time in `prerender:routes` Nitro hook)
* mention 200.html + 404.html and the need to set these up as fallbacks (e.g. on S3)

**Comment by RyanClementsHax** [comment]
Sounds like this would warrant an additional page. What do you think?
