### ISSUE TITLE
Nuxt Build Error on VERCEL [error] [nuxt] [request error] [unhandled] [500] [nuxt] instance unavailable nuxt 

### ISSUE THREAD

**Issue by studentofcoding** [nuxt/nuxt#22029]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.6.1`
- Nitro Version:    `2.5.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`, `gtag`, `vite`, `linkChecker`, `experimental`, `nitro`, `robots`, `i18n`, `image`, `extends`, `runtimeConfig`, `css`, `build`, `app`
- Runtime Modules:  `@storyblok/nuxt@5.5.1`, `@nuxt/image-edge@1.0.0-rc.1-28139579.37395b7`, `@nuxtjs/i18n@8.0.0-beta.12`, `nuxt-schema-org@2.2.0`, `nuxt-simple-robots@1.0.9`, `nuxt-gtag@0.5.7`
- Build Modules:    `-`

### Reproduction

The error is on Vercel, after the recent version of 3.6.1

All build processes are broken now 
<img width="1440" alt="Screenshot 2023-07-08 at 00 37 47" src="https://github.com/nuxt/nuxt/assets/20473526/55095d1f-84ad-4f39-b4f4-738b3d2e2940">

But on 'yarn build' local, all things runs fine

### Describe the bug

The error is on Vercel, after the recent version of 3.6.1

All build processes are broken now 
<img width="1440" alt="Screenshot 2023-07-08 at 00 37 47" src="https://github.com/nuxt/nuxt/assets/20473526/55095d1f-84ad-4f39-b4f4-738b3d2e2940">

But on 'yarn build' local, all things runs fine

### Logs

```shell-script
[success] [nitro] Generated public .vercel/output/static
[info] [nitro] Initializing prerenderer
[info] [nitro] Prerendering 2 initial routes with crawler
[log] [nitro]   ├─ /robots.txt (59ms)
[error] [nuxt] [request error] [unhandled] [500] [nuxt] instance unavailable
```

**Comment by danielroe** [comment]
Seems like an i18n issue from the stacktrace. Are you sure the versions of the i18n module are the same?

In any case, would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by besfir** [comment]
In my case, I called useAsyncData() twice in the setup hook to handle paging and it threw an instance unavailable exception. This was fine in 3.5.3 and earlier, but in 3.6.x it's still happening. 

```
 ERROR  [nuxt] instance unavailable                                                           10:21:53 PM

  at useNuxtApp (.nuxt/prerender/chunks/app/server.mjs:212:13)
  at useAsyncData (.nuxt/prerender/chunks/app/_nuxt/query-82504ba2.mjs:26:16)
  at usePaginatedContent (.nuxt/prerender/chunks/app/_nuxt/usePaginatedContent-7ad2c523.mjs:310:54)     // my custom composable
  at runNextTicks (node:internal/process/task_queues:60:5)
  at process.processImmediate (node:internal/timers:442:9)
  at async setup (.nuxt/prerender/chunks/app/_nuxt/index-c4430770.mjs:83:146)
```
