### ISSUE TITLE
json file in /assets cannot be imported using useStorage().getItem() within server function

### ISSUE THREAD

**Issue by jetlej** [nuxt/nuxt#22025]
### Environment

- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.10
- Builder:          vite
- User Config:      app, runtimeConfig, components, css, plugins, buildModules, modules, colorMode, supabase, target, build
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @nuxtjs/color-mode@3.3.0, @vueuse/nuxt@10.2.1
- Build Modules:    -

### Reproduction

Not needed (hopefully!)

### Describe the bug

I'm trying to import a JSON file located at `/assets/test.json` within a serverless function located at `/server/test.js`

The function code is: 

```
export default defineEventHandler(async (event) => {
    const test = await useStorage().getItem(`assets/server/test.json`);
    
    return {
       statusCode: 200,
       body: JSON.stringify(test),
  };
}
```

However, it says that the file cannot be found and test returns null. 

Is it in the wrong directory?

**Comment by Krutie** [comment]
@jetlej  - Not sure how the `nitro:` section looks like in your project's `nuxt.config.ts` 🤔 

Make sure you have configured the storage `driver` with `base` path of your file, i.e. `/assets/server/` - or whatever it is in fact. 
Here's how the storage config should look like:

```ts
// nuxt.config.ts
export default defineNuxtConfig({
  nitro: {
    storage: {
      myFileSystem: { // pass this key - 'myFileSystem' - into useStorage while accessing the .json file
        driver: 'fs',
        base: 'assets/server/', // make sure your `test.json` exists at this location
      }
    }
  }
});
```

Next, we can create our eventHandler at `server/api/` directory:

```ts
// server/api/my-storage.ts

import { useStorage } from '#imports';

export default defineEventHandler(async (event) => {

  const jsonData = await useStorage('myFileSystem').getItem('test.json');
  const stringData = JSON.stringify(jsonData);

  return {
    jsonData, // json
    stringData, // string
  }

})
```

And finally, `npm run dev` and see you file data at `localhost:300/api/my-storage`.

**Comment by Krutie** [comment]
@jetlej  Here's a working repro - https://stackblitz.com/edit/nuxt-starter-3uwbhb?file=nuxt.config.ts

**Comment by jetlej** [comment]
@Krutie wow thank you so much for the detailed help! This fixed my issue! Thank you!!!
