### ISSUE TITLE
close tag for meta and link

### ISSUE THREAD

**Issue by astalegale** [nuxt/nuxt#22021]
### Environment

Nuxt project info:                                                                                                                 15:52:26

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.1
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  npm@9.5.1
- Builder:          vite
- User Config:      ssr, runtimeConfig, modules, app, css, typescript, alias, multiCache
- Runtime Modules:  nuxt-lodash@2.5.0, nuxt-multi-cache@3.0.1
- Build Modules:    -

### Reproduction

launch nuxt dev
open source page and look to meta and link tags

### Describe the bug

The generated html doesn't have the closing tag for meta and link and i need to use the html generated in xslt processor. Now it's fail.
Is there a way to generate xhtml in strict mode?

Here an example of what nuxt generate:
```
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" type="image/x-icon" href="/images/96x96_Favicon.png">

```

**Comment by danielroe** [comment]
It is more correct not to use `/>`. Adding an extra `/` is ignored by HTML specification in most cases but there are some accounts of where it interferes with parsing.

**Comment by astalegale** [comment]
Hi @danielroe  thanks for the response, in our case we need the self closing slash becaouse the html (xhtml in our case) must be parsed with a xslt processor and it fails without the closing or the self closing tag for each element.

Is there a way, for now, to disable this behaviour? 

We are converting our web site with nuxt an actually we have defined the html tag to be: 
`<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="it" lang="it">`

Thanks for the tip of using Nitro to intercept the tag but i didn't understoot how to manipulte the tags there. Please could be little more specific?
Won't customizing Nitro affect rendering performance?

Regards 
Alex

**Comment by manniL** [comment]
@astalegale One example how other people manipulated the HTML can be found here: https://github.com/nuxt/nuxt/issues/18376#issuecomment-1438303970

You'd have to create a nitro plugin, call the `render:html` hook and then do whatever you want 😋
