### ISSUE TITLE
useAsyncData has inconsistent behaviour (ssr:false) since v3.6.2

### ISSUE THREAD

**Issue by ChronicStone** [nuxt/nuxt#22027]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.5.1
- Builder:          vite
- User Config:      ssr, pages, srcDir, routeRules, experimental, devtools, alias, typescript, css, app, modules, unocss, imports, components, vite
- Runtime Modules:  @pinia/nuxt@0.4.11, @vueuse/nuxt@10.2.1, @unocss/nuxt@0.53.4, @vue-macros/nuxt@1.3.12, nuxt-vitest@0.8.7
- Build Modules:    -
------------------------------

### Reproduction

- Github repo : https://github.com/ChronicStone/repro-issue-nuxt-useAsyncData
- Live version : https://repro-issue-nuxt-use-async-data.vercel.app/

### Describe the bug

Since upgrating to v3.6.2, useAsyncData has inconsistent & strange behaviour.
I found two main strange behaviours  : 

### SCENARIO 1 :  

Here the data load once, but then the function that resolves it never runs again, no matter how the watch dependencies change.

Also, if I have the following route : `/users/profile/:userId()`
When first visiting the page, the data will be resolved correctly if it's not already populated. If I come back to the route with a different ID, it won't re-trigger the resolver at all. I need to do a full page reload to have it resolve the correct data.

### SCENARIO 2 : 

The data does not load at first, and stays empty. Then, if a dependency change, it will refresh correctly.

----

The reproduction provided includes the 2nd scenario, I couldn't reproduce the 1st case on a minimal setup yet. An other interesting is that on both case, devtools is completely bugged on these two cases, hitting refresh there won't do anything. You can also observe this in the provided minimal reproduction

### Additional context

First here's the context on which i'm using it
- `ssr: false` in config
- I'm not awaiting the useAsyncData on my component

Here's an example of how i'm using it in-app : 

```ts
const periodFilters = ref<{ month: number; year: number }>({ month: 1, year: 1 });

const { data, pending } = useAsyncData(
  "assessmentCountStats",
  () => StatisticsController.getAssessmentStatusCount(props.clientId, periodFilters.value),
  { watch: [() => props.clientId, () => periodFilters.value.year, () => periodFilters.value.month] }
);
```

Also worth mentionning that if I switch back to 3.6.1, everything works fine, data always update according to dependency & load correctly.

**Comment by danielroe** [comment]
Let's track in nuxt/nuxt#22022

**Comment by danielroe** [comment]
The issue in your case can be viewed in `error.value` - it is  `ReferenceError: Cannot access 'sleep' before initialization`.

**Comment by ChronicStone** [comment]
Hmmm @danielroe it is... Sleep is defined before my resolveData function on the repro...

I am missing something here ?

```ts
<script setup lang="ts"> 
  
 const value = ref<string>('') 
 const props = defineProps<{ id: number }>() 
 const { data, pending } = useAsyncData('data', () => resolveData(), { watch: [() => props.id, () => value.value] }); 
  
 const sleep = (ms: number) => new Promise(resolve => setTimeout(resolve, ms)) 
  
 async function resolveData() { 
     console.log('resolveData', props.id, value.value) 
     await sleep(1000) 
     return { 
         id: props.id, 
         value: value.value, 
         message: 'Hello World!', 
         timeStamp: new Date().toISOString() 
     } 
 } 
 </script>
```

**Comment by danielroe** [comment]
Try moving it earlier. Or checking error.value.

**Comment by omer-pon** [comment]
I am new to Nuxt, but why don't you await for `useAsyncData` @ChronicStone ? I am also having a similar issue, dependency changes, but the resolver does not get triggered.
