### ISSUE TITLE
Nuxt logo blinking on page load

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [nuxt/nuxt#22028]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.15.0
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  npm@9.5.0
- Builder:          vite
- User Config:      runtimeConfig, modules, image, sitemap, jsoneditor, colorMode, css
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @pinia/nuxt@0.4.11, @pinia-plugin-persistedstate/nuxt@1.1.1, @nuxtjs/color-mode@3.3.0, nuxt-jsoneditor@1.6.14, nuxt-simple-sitemap@0.5.10, @nuxt/image-edge@1.0.0-rc.1-28124054.2f62c05
- Build Modules:    -
------------------------------

### Reproduction

No

### Describe the bug

Cloudflare Pages Hosted Site Nuxt logo blinking on every page load. After updating from 3.4.3 to 3.6.2

**Comment by danielroe** [comment]
You can disable the logo by setting:

```ts
export default defineNuxtConfig({
  spaLoadingTemplate: false
})
```

**Comment by rahulkumarsingh73690** [comment]
This only remove logo but now page load blank for few seconds and then page load even title

**Comment by mustafadilmac** [comment]
you made my day sir. you are a great man @danielroe

**Comment by manniL** [comment]
@rahulkumarsingh73690 please provide a reproduction then ☺️

**Comment by rahulkumarsingh73690** [comment]
@manniL Noticed issue when nuxt/image is installed
