### ISSUE TITLE
Problem with typings for params object in useRoute composable

### ISSUE THREAD

**Issue by therealokoro** [nuxt/nuxt#22034]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v19.3.0
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.0.0
- Builder:          vite
- User Config:      srcDir, serverDir, alias, modules, css, app, runtimeConfig, build, vue, experimental, colorMode, unocss
- Runtime Modules:  @nuxtjs/color-mode@3.3.0, @nuxt/devtools@0.6.7, @nuxt/image-edge@1.0.0-rc.1-28139579.37395b7, nuxt-headlessui@1.1.4, nuxt-unhead@1.4.17, @unocss/nuxt@0.53.4, @vueuse/nuxt@10.2.1
- Build Modules:    -
------------------------------

### Reproduction

On request

### Describe the bug

The `useRoute` composable isn't working as expected. It's types are a bit messed up.

![image](https://github.com/nuxt/nuxt/assets/41494675/08a0d070-f501-4c69-a00d-e75c43c7db97)

**Comment by danielroe** [comment]
If you are using `experimental.typedRoutes` you need to pass the route path into `useRoute` for the types to work.

**Comment by therealokoro** [comment]
Yeah that worked, even though it's a little bit more code to writee

```ts
const _slug = useRoute('some-route-slug').params.slug
```

Thanks @danielroe
