### ISSUE TITLE
bad nitro publicDir when dir.public is modified

### ISSUE THREAD

**Issue by mathieunicolas** [nuxt/nuxt#22038]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v19.6.0
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  npm@9.4.0
- Builder:          vite
- User Config:      devtools, modules, ui, nitro, app
- Runtime Modules:  @nuxthq/ui@2.5.0, @vueuse/nuxt@10.2.1
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/mathieunicolas/nitropublic

### Describe the bug

I want to deploy with `nuxi generate` on gitlab and my instance needs to get the output in the `/public` dir.
So, I changed the config to ask nitro to output the public dir to `/public` :

```
  nitro: {
    output: {
        publicDir: 'public'
      }
  },
```

Everything is ok, I got my files in `/public`, but then I wanted to change the public dir in nuxt so I still can put files in it to be served at the root of the website : 
```
  dir: {
    public: 'static' // I tried other names
  },
```

And now, the static files are not in `/public` anymore, but in `/server/public`. I removed the config, and the generated files are back in `/public`.

### Logs

```shell-script
Same `npm run generate`. The first with the `dir.public: static`, the second without.


✔ You can preview this build using npx serve .output/public  nitro 5:31:36 AM
✔ You can now deploy server/public to any static hosting!          5:31:36 AM
```

```
✔ You can preview this build using npx serve .output/public  nitro 5:34:29 AM
✔ You can now deploy public to any static hosting!                 5:34:29 AM
```
```

**Comment by danielroe** [comment]
Nitro directories are resolved relative to the `~/server` directory, so you can get this result with the following config:

```ts
export default defineNuxtConfig({
  nitro: {
    output: {
      publicDir: '~/public'
    }
  },
  dir: {
    public: 'static'
  }
})
```

**Comment by mathieunicolas** [comment]
Perfect, it works with your workaround, thanks !
Any idea why the output dir is different with and without the `dir.public` option ?
