### ISSUE TITLE
Install upgraded nuxt version as main dependency

### ISSUE THREAD

**Issue by wokalek** [nuxt/nuxt#22036]
https://github.com/nuxt/nuxt/blob/2edd7a34419e042f6a694929d32178ecb379be51/packages/nuxi/src/commands/upgrade.ts#L54C29-L54C29

Why is its upgrade like devDependecy? It needs to be the main package if it's nuxt project, isn't it?

**Comment by wokalek** [comment]
> Most things in nuxt3 are dev dependencies. The only thing that need to be regular dependencies are things that vue needs.

Why vue? I working with nuxt, not specifically with vue.

**Comment by manniL** [comment]
Let's consolidate this in https://github.com/nuxt/nuxt/issues/22050
