### ISSUE TITLE
Cannot stringify arbitrary non-POJOs on SSR useFetch with transform to class

### ISSUE THREAD

**Issue by azamat7g** [nuxt/nuxt#22040]
### Environment

- Operating System: Linux
- Node Version:     v18.14.0
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  npm@9.3.1
- Builder:          vite
- User Config:      devtools, modules, css, app, i18n, colorMode, runtimeConfig, appConfig
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.12, @nuxtjs/color-mode@3.3.0, @pinia/nuxt@0.4.11, nuxt-icon@0.4.1, nuxt-svgo@3.1.0
- Build Modules:    -

### Reproduction

https://codesandbox.io/p/sandbox/heuristic-leftpad-srv8kp

### Describe the bug

When trying to fetch data on server and convert result with transform to custom class throws 500 server error. But when I try to add parameter server: false everything works fine. I try to add toJSON (https://www.npmjs.com/package/@nuxt/devalue) but still noting works. Example code provided 

### Logs

```shell-script
[nuxt] [request error] [unhandled] [500] Cannot stringify arbitrary non-POJOs                                                                                                                                          
  at flatten (./node_modules/devalue/src/stringify.js:138:13)  
  at flatten (./node_modules/devalue/src/stringify.js:166:43)  
  at flatten (./node_modules/devalue/src/stringify.js:166:43)  
  at flatten (./node_modules/devalue/src/stringify.js:166:43)  
  at flatten (./node_modules/devalue/src/stringify.js:60:39)  
  at stringify (./node_modules/devalue/src/stringify.js:178:16)  
  at renderPayloadJsonScript (./.nuxt/dev/index.mjs:1257:32)  
  at ./.nuxt/dev/index.mjs:1181:29  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async ./.nuxt/dev/index.mjs:578:22
```

**Comment by prashantpalikhe** [comment]
I think you need to add support for your [custom class serialization](https://nuxt.com/blog/v3-4#payload-enhancements)  yourself.

**Comment by danielroe** [comment]
Let's track improving the documentation (and the error message!) here: https://github.com/nuxt/nuxt/issues/21832.

You can also see a workaround for supporting `.toJSON` here: https://github.com/nuxt/nuxt/issues/21832#issuecomment-1610982355. However, note I would recommend adding a custom serialiser/revivifier to ensure there aren't differences between server (class) and client (object).

**Comment by azamat7g** [comment]
[#21832 (comment)](https://github.com/nuxt/nuxt/issues/21832#issuecomment-1610982355) i tried to add plugin with this code but now i have new error `Cannot use 'in' operator to search for 'toJSON' in true`

https://codesandbox.io/p/sandbox/kind-hopper-w9cn5g

Can you fix this example to make it work with custom class?
