### ISSUE TITLE
[Vue warn]: [@vue/server-renderer] Invalid VNode type: undefined (undefined)

### ISSUE THREAD

**Issue by sixdjango** [nuxt/nuxt#22041]
### Environment

nuxt@latest

### Reproduction

https://nuxt.com/docs/examples/advanced/jsx#jsx-tsx
official demo url ↑

### Describe the bug

<img width="953" alt="image" src="https://github.com/nuxt/nuxt/assets/100112640/58c83a7c-ed7b-4fe4-a3c6-019fe27e8f1d">
I added the Ref variable using the official demo and got an warning

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

I don't get this:

<img width="966" alt="CleanShot 2023-07-10 at 11 09 07@2x" src="https://github.com/nuxt/nuxt/assets/28706372/ca577cca-fd55-4bca-9e11-a257b53f1b43">
