### ISSUE TITLE
nuxt3 uses npm run build to package, sending pictures, word and other file types more than 10KB will report 500 errors

### ISSUE THREAD

**Issue by taishuai110** [nuxt/nuxt#22042]
### Environment

Operating System: Liunx
Nuxt: 3.2.2;
Nuxi: 3.2.2
Nitro: 2.2.3
Node: 18.16.0
npm:  9.5.1
Builder: vite

### Reproduction

(https://github.com/taishuai110/nuxt3-error/blob/main/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20230708191820.png)
(https://github.com/taishuai110/nuxt3-error/blob/main/3.png)
(https://github.com/taishuai110/nuxt3-error/blob/main/2.png)

### Describe the bug

After I package the project, I use useFetch to send FromData requests. Files smaller than 10kb can be sent to the server, but files larger than 10kb cannot be sent. This is not the case with the development environment and only happens after you have officially packaged it, whether you deploy it to the server or not.

### Logs

```shell-script
[nuxt] [request error] [unhandled] [500] fetch failed (API Url)
0|NuxtAppName  |   at sendProxy (./node_modules/h3/dist/index.mjs:468:20)  
0|NuxtAppName  |   at Object.handler (./node_modules/h3/dist/index.mjs:1196:19)  
0|NuxtAppName  |   at Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1271:7)
```

**Comment by taishuai110** [comment]
I found that degrading node to version 16.15.0 would solve the problem, although it would solve the problem, I still want to know why nuxt3 needs to downgrade node to version 16 to use some of the features, is nuxt3 not yet perfect or node18 is not stable enough?

**Comment by danielroe** [comment]
Would you see if you can reproduce this with pure Nitro and raise an issue at https://github.com/unjs/nitro ? 🙏

**Comment by taishuai110** [comment]
@danielroe 
     What do you mean, I tried to change my node18.16.0 to 16.18.0 so I could send large files with fromData, but when I did, the images I sent and the images I responded to were not rendered, as if they were corrupted.

**Comment by taishuai110** [comment]
@danielroe Give me a break. I looked at your warehouse, and I couldn't understand it. There's no entry app.vue. Can I provide my github repository to you, can you download it and help me have a look
