### ISSUE TITLE
 autoImport: false is not working

### ISSUE THREAD

**Issue by EduSantosBrito** [nuxt/nuxt#22056]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.1.0`
- Nuxt Version:     `3.6.2`
- Nitro Version:    `2.5.2`
- Package Manager:  `npm@9.6.4`
- Builder:          `vite`
- User Config:      `imports`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-jp4xw2?file=components%2FHelloWorld.vue

### Describe the bug

I tested disabling the auto import feature, but the component still being imported

**Comment by danielroe** [comment]
`imports.autoImport` is how to disable the importing of functions from your composables directory.

You can disable the components module by setting `components.dirs` to an empty array.

**Comment by EduSantosBrito** [comment]
Thanks @danielroe!

It was my first time using nuxt (as a 7 yo React developer) and I was struggling with disabling it. I've created a PR explaining this on the docs
