### ISSUE TITLE
move default nuxt package to dependency

### ISSUE THREAD

**Issue by danielroe** [nuxt/nuxt#22050]
Currently we [deliberately add `nuxt` as a devDependency](https://github.com/nuxt/starter/blob/v3/package.json#L11-L15). This is because nuxt is a build tool and was originally meant to add clarity that nuxt is not needed in the built site.

However, this is technically true of _all_ dependencies in a Nuxt project as Nitro fully generates a new `.output/server/node_modules` folder with every dependency needed to run the server.

As a result, I think this means we lose any differentiation between `dependencies`/`devDependencies` by default.

Accordingly, I'd propose we move `nuxt` to a `dependency`, enabling users to preserve differentiation between 'tooling' like linting, dev instructure, etc., and dependencies that become part of their runtime site (like nuxt, vue, etc.).

context: https://github.com/nuxt/nuxt/pull/22037

**Comment by wokalek** [comment]
When you work with nuxt in docker (optional), you install all dependencies on dev, and only production dependencies on prod.

When you update nuxt with the `nuxi upgrade --force` command, the package manager automatically moves nuxt back into a dependency for development, which in my opinion is a problem. We have to move it back to a dependency for production development.

If the nuxt will be the main dependency of the project, then it will be possible to update the nuxt via nuxi with confidence, and write in the dockerfile like this:

`nuxt.dev.dockerfile`
```dockerfile
COPY ./nuxt/package.json ./nuxt/pnpm-lock.yaml ./nuxt/.npmrc ./
RUN pnpm fetch
RUN pnpm install -r --offline
```

`nuxt.prod.dockerfile`
```dockerfile
COPY ./nuxt/package.json ./nuxt/pnpm-lock.yaml ./nuxt/.npmrc ./
RUN pnpm fetch --prod
RUN pnpm install -r --offline --prod
```

**Comment by danielroe** [comment]
To be clear, your production docker image should not include Nuxt as a dependency.

**Comment by wokalek** [comment]
> To be clear, your production docker image should not include Nuxt as a dependency.
> 
> It should only include the contents of `.output` and not the parent `node_modules` folder.

Can you give an example of what you mean, please?

Because in many examples and guides on the net that I have seen, the src folder is always copied, only prod dependencies are installed and a build is made, which is saved in the image.
Accordingly, it is quite logical to install only dependencies for production.

**Comment by danielroe** [comment]
Those and examples and guides are probably incorrect in that case.

No dependencies are required for a Nuxt project once it has been built.

**Comment by wokalek** [comment]
Yes, but before building, you need to fetch dependencies :)

How the build happens in the dockerfile is another question.

But the bottom line is that dependencies should still be installed before the build through the --prod flag.

**Comment by danielroe** [comment]
I'm not commenting on the process of building - it's your decision how to split production/dev dependencies and what to install before that point. Personally I would be happy to install all dependencies for the build, as long as **once built** you do not have nuxt installed in your final image.

**Comment by pi0** [comment]
It would be nice to keep dicussing before taking this decition. I like the idea of semantically declaring the bundled runtime dependencies vs development via depes/devDeps however it also makes it harder for some deployment flows when **by default** assumption is that dependencies has to be bundled finally and they don't only pick the `.output` folder.

**Comment by danielroe** [comment]
We plan to move forward on this once we have nitro presets to cover buildpack-based providers.

**Comment by pi0** [comment]
Talking with @danielroe i think we can do to do this change and push for the incompatible presets to be better as the main downside is only deployment bundle size.

**Comment by danielroe** [comment]
implemented in https://github.com/nuxt/starter/commit/ae15839727b873b546ac9ef36d5bb3964bac77e0 ✅
