### ISSUE TITLE
Memory Leak when integrating Vuetify

### ISSUE THREAD

**Issue by GaetanWi** [nuxt/nuxt#22064]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.16.1
- Nuxt Version:     3.5.1
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.17
- Builder:          vite
- User Config:      css, build, vite, hooks
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/smiura6/nuxt3-vuetify-memory-test

### Describe the bug

When accessed multiple times, the memory consumption is raising without ever being freed by the gc process. 

### Additional context

Running:

1. yarn build
2. node --inspect .output/server/index.mjs    
3. going to chrome://inspect (or pretty much any inspector) and monitoring the memory consumption
4. Siege your app with something like siege to see significant raise (or refresh the app multiple times)
5. Observe the memory consumption raising

(A PR is opened on vuetify's side as well with a bit more info : https://github.com/vuetifyjs/vuetify/issues/17473, but still opening one here as it may be related to Nuxt itself ?)

**Comment by danielroe** [comment]
I wonder if the issue is related to the fact that your vuetify instance is created outside the plugin. Is it possible it's preserving references within it?

**Comment by GaetanWi** [comment]
Defining the vuetify instance directly inside of the defineNuxtPlugin result in the same behavior if that was your concern. 

If not, not really sure that we have that much alternatives, at least to my knowledge, as Vuetify's documentation doesn't explain how to handle things.

**Comment by danielroe** [comment]
My guess would be it is a vuetify issue but it's difficult to say without investigating.

With node, it is normal for memory to grow until it reaches available space and then for node to garbage collect as needed.

**Comment by GaetanWi** [comment]
Closing the issue as it was related to Vuetify indeed. 

(Vuetify and I18n). 
If someone find this thread, here is the issue on Vuetify that got fix : https://github.com/vuetifyjs/vuetify/issues/17473
Bumping to Vuetify latest version disable reactivity on some theming part. 


If you're using vue-i18n : 
https://github.com/intlify/vue-i18n-next/issues/920

Good luck with other problems if there are some on your side !

**Comment by danielroe** [comment]
Great! 🥳
