### ISSUE TITLE
Error.vue page not working

### ISSUE THREAD

**Issue by niekbiesterbos** [nuxt/nuxt#22065]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.6.2`
- Nitro Version:    `2.5.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `css`, `plugins`, `components`, `app`, `srcDir`, `build`, `devServer`, `modules`, `i18n`, `runtimeConfig`, `devtools`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.13`, `nuxt-mapbox@1.3.9`, `@pinia/nuxt@0.4.11`, `@nuxt/content@2.7.0`, `@nuxtjs/robots@3.0.0`
- Build Modules:    `-`

### Reproduction

Create a new Nuxt project. Create a vue.error in the root folder. Try throwing errors or go to a non existing url

### Describe the bug

It seems that after the update that error.vue does not work anymore. I used this for an earlier project in the exact same way and that worked just fine. I did not use any specific setup but I just don't get the basic error page provided by the documentation to work. [](https://nuxt.com/docs/getting-started/error-handling#rendering-an-error-page)

**Comment by niekbiesterbos** [comment]
Hi Daniel, here is the reproduction: [](https://stackblitz.com/edit/github-e9od2a?file=src%2Ferror.vue)

Managed to fix it now tho! The problem is: when using a srcDir configuration, and having app.vue and error.vue in the root dir instead of the srcDir, app.vue does still load without an issue. When navigating to a page that does not exist, error.vue does not load but it just displays the default error page. 

I believe this error is on my side as I did not include app.vue and error.vue in the srcDir, but I did not find anything in the documentation which told me to do so, so I still report it to you so that you can decide if anymore action is necessary. 

Thanks for your response!

**Comment by esorribas** [comment]
@niekbiesterbos workaround (only for 404 pages, not for createError method): move the error.vue file inside srcDir folder.
@danielroe I have this issue too, when the srcDir is set, Nuxt doesn't load the file on errors.

Tested with 3.7

**Comment by esorribas** [comment]
> Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

https://stackblitz.com/edit/github-iwbx6s

**Comment by danielroe** [comment]
Both error.vue and app.vue are meant to be within your srcDir. That is not a bug.

**Comment by esorribas** [comment]
@danielroe I know... but please check the stackblitz link, if you click on the link the error.vue is not detected and shows the default Nuxt error page

![image](https://github.com/nuxt/nuxt/assets/2790282/016766bf-c7e1-4282-82e0-454b40452575)

**Comment by danielroe** [comment]
In your link neither `app.vue` nor `error.vue` are in your `srcDir`, where they will find their home and a small modicum of happiness. Try copying them inside.

**Comment by ryscript** [comment]
If this happens to anyone, just make sure to rebuild your application.

**Comment by javedTunio** [comment]
> If this happens to anyone, just make sure to rebuild your application.

yes, it got fixed by rebuilding. thanx
