### ISSUE TITLE
Deployment nuxt js on node server

### ISSUE THREAD

**Issue by saadallahdev** [nuxt/nuxt#22061]
### Environment

Nuxi 3.6.1                                                                                                                                                                                         
------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.2
- Package Manager:  npm@9.5.1
- Builder:          vite
- User Config:      devtools, modules, nitro, alias
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0
- Build Modules:    -
------------------------------

�👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                                                                                                        12:30:02 AM

�👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

�👉 Read documentation: https://nuxt.com

### Reproduction

Deployment nuxt js on node server

### Describe the bug

i have run npm run build and it create .output folder 
and uploed to the server and run 
node .output/server/index.mjs

everytime i go to the domine i get 503 code 

### Logs

```shell-script
node:internal/modules/cjs/loader:1115
    throw new ERR_REQUIRE_ESM(filename, true);
    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/manhal45/manhaly.com/.output/server/index.mjs not supported.
Instead change the require of /home/manhal45/manhaly.com/.output/server/index.mjs to a dynamic import() which is available in all CommonJS modules.
    at startApplication (/usr/local/lsws/fcgi-bin/lsnode.js:48:15)
    at Object.<anonymous> (/usr/local/lsws/fcgi-bin/lsnode.js:16:1) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.14.1
```

**Comment by danielroe** [comment]
This is an issue to do with how you are importing your Nuxt server.

It looks like your server is trying to import it from a cjs file.

I would suggest opening a discussion with more info or asking on the Nuxt Discord server.
