### ISSUE TITLE
expose is undefined in FComponent

### ISSUE THREAD

**Issue by sixdjango** [nuxt/nuxt#22063]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.15.0
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.6.0
- Builder:          vite
- User Config:      devServer, runtimeConfig, modules, i18n, build, vite, experimental, css, colorMode, nitro, app
- Runtime Modules:  modules/motion, @vueuse/nuxt@10.2.1, @unocss/nuxt@0.53.4, @pinia/nuxt@0.4.11, @nuxtjs/color-mode@3.2.0, @nuxt/devtools@0.2.5, @nuxtjs/i18n@8.0.0-beta.10
- Build Modules:    -
------------------------------

### Reproduction

import type { SetupContext, SlotsType } from 'vue'
import FooterVue from './Footer.vue'
import SecondChildVue from './SecondChild.vue'
interface FComponentProps {
  message?: string
}

interface Events {
  sendMessage(message: string): void
}

interface Slots extends SlotsType<Record<string, any>> {
  title: Function
}

export default function FComponent(
  props: FComponentProps,
  { slots, emit, expose }: SetupContext<Events, Slots>,
) {
  emit('sendMessage', 'good')

// expose is undefined
  consola.info('expose:', expose)
  const b = ref('dd')

  return (
    <div>
      <h1>{slots.title?.()}</h1>
      <SecondChildVue msg='sda' />
      <div>{b.value}</div>
      <FooterVue />
    </div>
  )
}

FComponent.props = {
  message: {
    type: String,
    required: true,
  },
}

FComponent.emits = {
  sendMessage: (value: unknown) => typeof value === 'string',
}

### Describe the bug

i can'd use expose and use fc component in nuxtjs

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

In particular, would you check if there's any difference without Nuxt by using this template? https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter
