### ISSUE TITLE
Re-throw exception when malformed URL is rejected by decodeURIComponent instead of letting the server run into a 500

### ISSUE THREAD

**Issue by nichtdiebohnehamburg** [nuxt/nuxt#22071]
### Describe the feature

When client tries to call a malformed url (f.e. http://localhost:3000/windows/win.ini%C0%80.jsp), the url is passed unvalidated into `decodeURIComponent`. decodeURIComponent fails and throws an exception which is triggering an 500 Server error. It is not possible to catch this exception beforehand, or to intercept the URL before it is passed through to decodeURIComponent.

It would be good to be able to catch this exception and to register a handler for this. Making possible to handle malformed URL, would enable for example to throw an error 400 (Bad Request) instead. It is not possible to fix this with a plugin or a navigation guard, since the decoding of the url happens way too early.

The example above is an actual URL called by a "security" scanner, triggering lots of errors on the server side by just calling malformed URLs.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Looking at this, we have a couple of places where this error will be triggered:
* vite, in dev mode
* nitro, in the static asset handler: https://github.com/unjs/nitro/blob/34d9d1dc074f2c13f6d5c83a50d500d501a725ac/src/runtime/static.ts#L18-L22

Neither of them are in Nuxt but we can push this issue upstream to Nitro, where I've raised https://github.com/unjs/nitro/pull/1459.
