### ISSUE TITLE
My path to nuxt.config.ts

### ISSUE THREAD

**Issue by Deemoguse** [nuxt/nuxt#22078]
### Discussed in https://github.com/nuxt/nuxt/discussions/22043

<div type='discussions-op-text'>

<sup>Originally posted by **Deemoguse** July  8, 2023</sup>
How can I specify the path to my configuration file? Now I'm organizing the directories and files of the project to bring everything to the form that suits me. I put all the project configuration files in the `configs` folder, but I still didn't figure out how to specify Nuxt the path to this file. I'm trying to use the flag `--config-file ./configs/nuxt.config.ts`, but it doesn't work for me.

```js
{
	"scripts": {
		"build": "nuxt build --config-file configs/nuxt.config.ts",
		"dev": "nuxt dev --config-file configs/nuxt.config.ts",
		"generate": "nuxt generate --config-file configs/nuxt.config.ts",
		"preview": "nuxt preview --config-file configs/nuxt.config.ts",
		"postinstall": "nuxt prepar --config-file configs/nuxt.config.ts"
	},
	"devDependencies": {
		...
	},
	"dependencies": {
		...
	}
}
```

**Here is my directory and file structure at the moment:**
![image](https://github.com/nuxt/nuxt/assets/68069851/a7c20a72-de66-4e11-9a74-d65b3d494943)
</div>

**Comment by NozomuIkuta** [comment]
I'm not so sure, but such feature is not yet supported as far as I checked.

One compromise is to pass `rootDir` to `nuxi` CLI and set `srcDir` in `nuxt.config.ts`.

```bash
nuxi dev path/to/directory/of/nuxt/config/file
```

```ts
export default defineNuxtConfig({
  srcDir: '../' // relative to `rootDir` (= the current directory)
})
```

A disadvantage of this approach is that `.env` has to be defined in the same directory as `rootDir`.
I'm also not sure whether other limitations will be brought in.

---

I guess this could be achieved by modifying nuxi package and its commands logic, as well as logic around `loadConfig` function. 🤔

**Comment by Deemoguse** [comment]
@NozomuIkuta, Thanks for the reply. Well, I'll try to expand the logic of the things you mentioned in my fork to offer it to merge. Although it is strange that such basic functionality was not implemented initially. I really like it when there is a single style and generally accepted rules regarding working with anything, but flexibility should remain available in any case
