### ISSUE TITLE
nuxt generate does not render pages since 3.6.0

### ISSUE THREAD

**Issue by mschoeffmann** [nuxt/nuxt#22072]
### Environment

LOCAL:
- Operating System: `Darwin`
- Node Version:     `v18.16.1`
- Nuxt Version:     `3.6.2`
- Nitro Version:    `2.5.2`
- Package Manager:  `pnpm@8.3.1`
- Builder:          `vite`
- User Config:      `build`, `css`, `devtools`, `modules`, `ssr`
- Runtime Modules:  `@nuxt/devtools@0.6.7`
- Build Modules:    `-`

STACKBLITZ:
- Operating System: `Linux`
- Node Version:     `v16.20.0`
- Nuxt Version:     `3.6.2`
- Nitro Version:    `2.5.2`
- Package Manager:  `npm@9.4.2`
- Builder:          `vite`
- User Config:      `ssr`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt3-generate-test?file=README.md

### Describe the bug

Since `3.6.0`, static pages are not rendered with `nuxt generate` any more.

### NOT WORKING IN 3.6.2

Output of `npm i nuxt@3.6.2 && nuxt generate`:

```
ℹ Prerendering 3 initial routes with crawler
  ├─ /200.html (456ms)
  ├─ /404.html (456ms)
  ├─ / (457ms)
```

### WAS WORKING IN 3.5.3

Output of `npm i nuxt@3.5.3 && nuxt generate`:

```
ℹ Prerendering 5 initial routes with crawler
  ├─ / (105ms)
  ├─ /test1 (5ms)
  ├─ /test2 (12ms)
  ├─ /200.html (8ms)
  ├─ /404.html (10ms)
  ├─ /_payload.json (2ms)
  ├─ /test1/_payload.json (8ms)
  ├─ /test2/_payload.json (9ms)
```

**Comment by Lexpeartha** [comment]
Can confirm that this is also happening with any build method (in my case at lexpeartha/portfolio#4 using vercel-edge) as long as there are some routes set in either `nitro.prerender.routes` or `generate.routes`

**Comment by danielroe** [comment]
Would you try explicitly setting `nitro.prerender.crawlLinks`?

**Comment by mrniamster** [comment]
Someone please upload a fix for this, in nuxt 2 this was quick and easy, 

Its not generating PAGES + CONTENT also 

Please update me if there is a workaround this..

**Comment by mrniamster** [comment]
Thanks @mschoeffmann , switch from nuxt 2 to nuxt 3.6 directly , i missed that :) 

But still one problem presits , the nuxt content pages are not generated, we have to do something for that  in nuxt.config.ts?
