### ISSUE TITLE
Bad path of assets after 3.6 upgrade

### ISSUE THREAD

**Issue by Sylvadoc** [nuxt/nuxt#22086]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.14.0
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.4.0
- Builder:          vite
- User Config:      nitro, typescript, runtimeConfig, devServerHandlers, modules, app, postcss, routeRules, i18n, schemaOrg, delayHydration, vite
- Runtime Modules:  nuxt-delay-hydration@1.2.1, nuxt-schema-org@2.2.0, @nuxtjs/i18n@8.0.0-beta.10
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-jaeoi1?file=components%2Ffoo.vue

### Describe the bug

Hi,

After upgrade to 3.6.2 : 

**After building** the application (no problem in dev) :

The icon's url in the inlined css is ok : 
```
[data-icon=foo] {
    --icon-custom: url(/_nuxt/ic-ecurie.dfbfbb0a.svg);
}
```

The icon's url in the **entry.css gives a 404**
```
[data-icon=foo] {
    --icon-custom: url(./ic-ecurie.dfbfbb0a.svg);
}
```

There's no `_nuxt` in the url because the asset is in the same directory as the css but the browser consider it not and resolve with his path.

Maybe i make something wrong but I see no problems in Nuxt 3.5.3 :thinking:

**Comment by danielroe** [comment]
This seems to be working fine for me in the reproduction. (I disabled inlining styles in order to see the effect.)

<img width="1435" alt="CleanShot 2023-07-11 at 15 54 50@2x" src="https://github.com/nuxt/nuxt/assets/28706372/77a819f5-c955-413a-af88-b38824375d7a">

**Comment by Sylvadoc** [comment]
Thanks @danielroe ! Indeed, when i disable inline styles, it works :sweat_smile: I don't understand at all :( i close the issue !
