### ISSUE TITLE
Can't order head tags after Nuxt head tags with `tagPriority`

### ISSUE THREAD

**Issue by ijkml** [nuxt/nuxt#22082]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.6.1`
- Nitro Version:    `2.5.2`
- Package Manager:  `pnpm@8.6.0`
- Builder:          `vite`
- User Config:      `devServer`, `app`, `routeRules`, `alias`, `modules`, `experimental`, `vite`, `css`, `typescript`, `devtools`
- Runtime Modules:  `@vueuse/nuxt@10.2.1`, `@unocss/nuxt@0.53.4`, `nuxt-beastcss@1.0.3`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-luygfj?file=nuxt.config.ts

(Inspect frame)

### Describe the bug

Hi :wave: 
I am trying to add this noscript tag to the bottom of `<head>`. By default, Nuxt adds it just below `<title>`. I tried using `tagPriority` and assumed the bigger the number, the later it would be registered.
```ts
export default defineNuxtConfig({
  app: {
    head: {
      noscript: [{ innerHTML: '...css link', tagPriority: 20 }],
    },
  }});
```

`tagPriority` has the following jsdoc
```
(property) tagPriority?: number | "critical" | "high" | "low" | `before:${string}` | `after:${string}` | undefined

The priority for rendering the tag, without this all tags are rendered as they are registered (besides some special tags).

The following special tags have default priorities:

-2 <meta charset ...>
-1
0 <meta http-equiv="content-security-policy" ...>
All other tags have a default priority of 10
```

Negative values seem to work, a `-10` put it first in head. I have tried 10 - 200, but can't make it lower than just below `<title>`. I would've tried to put it in body, but I'm putting a css link inside, and [that's not allowed](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/noscript).

### Additional context

Not exactly related... https://github.com/nuxt/nuxt/issues/21570

**Comment by danielroe** [comment]
cc: @harlan-zw

**Comment by harlan-zw** [comment]
Related to https://github.com/danielroe/nuxt-capo/issues/36#issuecomment-1629374648

Nuxt inserts <head> it's own head tags outside of Unhead so you can't insert anything after them without using nitro hooks. 

The solution is to have Nuxt SSR use Unhead for all tags.
