### ISSUE TITLE
nuxi generate suddenly failed, it was working before

### ISSUE THREAD

**Issue by saktya** [nuxt/nuxt#22083]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      ssr, app, modules, postcss, plugins, runtimeConfig, hooks
- Runtime Modules:  @pinia/nuxt@0.4.11, @pinia-plugin-persistedstate/nuxt@1.1.1, @vueuse/nuxt@10.2.1, @nuxt/image@1.0.0-rc.1, nuxt-gtag@0.5.7, 
@zadigetvoltaire/nuxt-gtm@0.0.13
- Build Modules:    -
------------------------------

### Reproduction

Run comment "yarn generate"

### Describe the bug

The static page generation failed with messages like this:
├─ /news/neuroplasticity-as-the-basis (500)                                                                                  nitro 08:45:51  
  ├─ /news/the-use-of-mirror-boxes-in-the-treatment-of-treatment-resistant-pain (500)                                          nitro 08:45:51  
  ├─ /news/pain-on-pain-off-controlling-persistent-pain (500)                                                                  nitro 08:45:51  
  ├─ /news/neuroplasticity-as-the-basis-for-a-new-understanding-of-human-functioning (500)                                     nitro 08:45:51  
  ├─ /news (500)                                                                                                               nitro 08:45:51  
                                                                                                                               nitro 08:45:51  

 ERROR  Exiting due to prerender errors.                                                                                             08:45:51  

  at prerender (/D:/Projects/Ntech/ntech-web/node_modules/nitropack/dist/shared/nitro.1db3349c.mjs:189:11)
  at async /D:/Projects/Ntech/ntech-web/node_modules/nuxt/dist/index.mjs:2634:7
  at async build (/D:/Projects/Ntech/ntech-web/node_modules/nuxt/dist/index.mjs:3785:5)
  at async Object.invoke (/D:/Projects/Ntech/ntech-web/node_modules/nuxi/dist/chunks/build.mjs:59:5)
  at async Object.invoke (/D:/Projects/Ntech/ntech-web/node_modules/nuxi/dist/chunks/generate.mjs:36:5)
  at async _main (/D:/Projects/Ntech/ntech-web/node_modules/nuxi/dist/cli.mjs:49:20)

error Command failed with exit code 1.

### Additional context

It happen suddenly the same code, same script already working with no problem but suddenly it throw this error without any detail information

**Comment by NozomuIkuta** [comment]
@saktya 

Would you provide a reproduction?

- https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz
- https://codesandbox.io/p/github/nuxt/starter/v3-codesandbox
- link to your repository

It is good to know what version of Nuxt you had used and with what version it broke.

**Comment by saktya** [comment]
I'm sorry I can't reproduce the error if I'm using the original starter pack, and because the problem suddenly happening (without we change any code) and not sure where to find more error information, I unable to reproduce the error in simple matter.

Do you have any idea where is the best place to find out more information about the error? because its just say 500 error, when I'm using SSR to the page its just working fine.

**Comment by NozomuIkuta** [comment]
Seeing the versions of packages, it might be worth checking #22072.

Or, you could try to downgrade Nuxt version to 3.5.x and forcefully reinstall `node_modules` and run `nuxi generate` again.
If it succeeds, it might be due to a bug in 3.6.x.

**Comment by Pedromdsn** [comment]
Try to delete the node_modules, after that, clean the yarn cache, and then reinstall the dependencies.

```
rm -rf node_modules/
yarn cache clean
yarn install
```

**Comment by genu** [comment]
can you share your `package.json`, or dependencies?
