### ISSUE TITLE
Nuxt 3.6 | 3.5.3  -  Content + Pages  not getting generated routes  | Static

### ISSUE THREAD

**Issue by mrniamster** [nuxt/nuxt#22084]
### Environment

Nuxi 3.5.3                                                                                             12:10:46 PM
                                                                                                       12:10:50 PM                                     12:10:50 PM
Nuxt project info:                                                                                     12:10:50 PM  

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.11.0
- Nuxt Version:     3.5.3
- Nitro Version:    2.5.2
- Package Manager:  npm@9.6.5
- Builder:          vite
- User Config:      ssr, hooks, vue, nitro, css, vite, postcss, app, modules, content, googleSignIn, runtimeConfig, 
devtools
- Runtime Modules:  nuxt-vue3-google-signin@0.0.8, @pinia/nuxt@0.4.11, @nuxt/content@2.7.0, @pinia/nuxt@0.4.11, @nuxtjs/color-mode@3.3.0
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt3-generate-test?file=README.md

### Describe the bug

Continuing the bug reported here , Nuxt generate not working with pages, in Nuxt 3.6, 
https://github.com/nuxt/nuxt/issues/22072

Content md files are not generated in nuxt 3.6

I switched to nuxt 3.5 the Pages are generating in  `npx nuxi generate` , **now the problem is the routes  are still  not generating for nuxt content,** 

Here is my nuxt.config.ts
```
  ssr: true,
  nitro: {
    preset: 'static',
    prerender: {
      crawlLinks: true,
      // routes:['/','/dashboard','/docs','/login','/register','/reset-password'] // this thing work , but needs to be automated ?
    }
```

### Additional context

I can see the logs it shows this :

![image](https://github.com/nuxt/nuxt/assets/52563039/c8f1c4b4-1ac0-4b25-b7e9-9f9bff33a20f)

But visiting the use the json shows empty 

![image](https://github.com/nuxt/nuxt/assets/52563039/10b99b72-748d-4db6-a0c2-517d050753a8)

Result : Nothing is getting fetched 

![image](https://github.com/nuxt/nuxt/assets/52563039/08839f56-90f5-4e2a-af12-758402d0570f)

### Logs

```shell-script
nitro 10:53:04 AM]   ├─ /api/_content/query/M5k2JI3fg2.1689052855198/eyJ3aGVyZSI6W3siX3BhcnRpYWwiOnsiJG5vdCI6dHJ1ZX0sIm5hdmlnYXRpb24iOnsiJG5vdCI6ZmFsc2V9fV0sIndpdGhvdXQi/OlsiYm9keSJdLCJzdXJyb3VuZCI6eyJxdWVyeSI6Ii9kYXNoYm9hcmQvczJ1L21hbmFnZSJ9LCJzb3J0IjpbeyJfZmlsZSI6MSwi/JG51bWVyaWMiOnRydWV9XX0.json (38ms)       
  ├─ /docs/_payload.json (2ms)                                                                                                            nitro 10:53:04 AM
[nitro 10:53:04 AM]   ├─ /api/_content/query/kF5Ak5ecZU.1689052855198/eyJ3aGVyZSI6W3siX3BhdGgiOiIvZG9jcyJ9XSwiZmlyc3QiOnRydWUsInNvcnQiOlt7Il9maWxlIjoxLCIkbnVtZXJpYyI6dHJ1/ZX1dfQ.json (3ms) (Error: [404] Document not found!)
```

**Comment by toniengelhardt** [comment]
Also having issues. The `generate` command completes and the page works, but  there seems to be an issue with prefetching.

<img width="782" alt="Screenshot 2023-07-15 at 16 24 06" src="https://github.com/nuxt/nuxt/assets/2703233/780b7bd2-9f9a-4e82-bd79-3b42f533da09">

The preview of the request gives me the Nuxt spa-loading indicator.

**Comment by toniengelhardt** [comment]
The solution here fixed it for me: https://github.com/nuxt/nuxt/issues/22068

**Comment by danielroe** [comment]
Would you try with the latest v3.6.3?

**Comment by danielroe** [comment]
I think this should be resolved in https://github.com/nuxt/nuxt/pull/22162. Let me know if not.

**Comment by mehotkhan** [comment]
on 3.6.2 fixed for me

**Comment by mrniamster** [comment]
@danielroe  Confirming its working on 3.6.5 , without any pre-render hook anymore, This is amazing! 
Nuxt team  never fail to disappoint! Thank you so much!
