### ISSUE TITLE
Top-level await in layout breaks hydration in Nuxt 3.6

### ISSUE THREAD

**Issue by pgraug** [nuxt/nuxt#22091]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.20.0`
- Nuxt Version:     `3.6.2`
- Nitro Version:    `2.5.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

[Here's a reproduction of the bug running on Nuxt 3.6.2](https://stackblitz.com/edit/nuxt-starter-4cbwhd?file=pages%2Findex.vue).
And for comparison [here's the same reproduction running on Nuxt 3.5.3](https://stackblitz.com/edit/nuxt-starter-l5ts6s?file=layouts%2Fdefault.vue) and the bug isn't there.

### Describe the bug

Starting in Nuxt 3.6, using top-level await in a layout causes the hydration to fail because `nuxt.isHydration` is set to `false` before the hydration has actually finished.

This leads to any `useAsyncData`s you have, checking for data in `nuxt.static.data[key]` where there is none, instead of `nuxt.payload.data[key]` where the data is ([see code](https://github.com/nuxt/nuxt/blob/08acfb749de2394e30e7c27d49f4226429743232/packages/nuxt/src/app/composables/asyncData.ts#L123)). This means all your `useAsyncData`s are suddenly set to `null` and the refetched, causing major hydration errors.

### Additional context

I suspect it's caused by PR #21450 reintroducing `defineAsyncComponent` that had previously been replaced by a work-around because of an upstream bug with `<Suspense>` in Vue (vuejs/core#6638)

It's been really difficult to debug this since all the hydration errors and problems happened after this bug silently caused `nuxt.isHydration` to be set to `false` too soon. Any tips on how to find what's causing bugs like this in a large codebase are very much appreciated.

This is blocking our upgrade to Nuxt 3.6 since we fetch some data to initialize a Pinia store in our layout. Don't know if that's bad practice though. Might move it to a plugin instead. At least until this is fixed.

**Comment by danielroe** [comment]
Nevertheless.

**Comment by JonathanDoelan** [comment]
I have found a workaround, by fetching the data in a composable like this:

```js
export const useMyData = async () => {
    const payloadKey = "my-data";

    // workaround
    if (process.client) {
        const { payload } = useNuxtApp();
        const payloadData = payload.data[payloadKey];
        if (payloadData) return ref(payloadData);
    }

    const { data } = await useAsyncData(
        payloadKey,
        async () => {
            // fetch data
        },
    );

    return data;
};
```
So, before we fetch data via useAsyncData, we manually search for the data in the existing payload.

In your page component:
```vue
<script setup>
    const myData = await useMyData();
</script>
```

An other solution could be to fetch the data you want to use in a layout (with useAsyncData) inside a plugin and then provide the data via the plugin.

**Comment by pgraug** [comment]
Thanks @JonathanDoelan!

Wouldn't using a custom composable like this mean having to replace all useAsyncData's in the project since there's still a top-level await in our layout? That might not be feasible for a project our size.

I think you might be right about fetching the layout's data in the plugin though, but haven't tested it yet since it would require some changes for us.

**Comment by JonathanDoelan** [comment]
True. As long as the bug is not fixed, we need to work around it.

**Comment by manniL** [comment]
* Related version: `npm:nuxt3@3.6.0-28125270.adb1c122`
* Related PR: https://github.com/nuxt/nuxt/pull/21450

**Comment by gerbenvandijk** [comment]
This issue still seems present when you are using a custom error layout (error.vue in the root of the application)
