### ISSUE TITLE
HMR problems

### ISSUE THREAD

**Issue by PLAKSHERiE** [nuxt/nuxt#22090]
### Environment

```
- Operating System: Windows_NT
- Node Version:     v18.12.1
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  pnpm@7.14.0
- Builder:          vite
- User Config:      devtools, css, postcss, pinia, modules, vite, nitro, runtimeConfig
- Runtime Modules:  @pinia/nuxt@0.4.11, nuxt-icon@0.4.2
- Build Modules:    -

```

### Reproduction

https://stackblitz.com/edit/nuxt-starter-wshrrb?file=stores%2Fauth.ts

### Describe the bug

There is an enabled auth.ts file with pinia. When changing this file, hmr is triggered, but the changes are cached(?). Cache in the browser is turned off. In the Network tab you can see that the script appears with changes(auth.ts?t=1689021567137), but they are not applied to the client. only rebooting page helps. I don't understand what causes this to happen, little experience, but since I'm doing it in nuxt I posted here.
This behavior in 4 different browsers, they have different engines too

https://github.com/nuxt/nuxt/assets/67220210/89716bec-eea0-4f23-a82b-d951be6a119c

**Comment by PLAKSHERiE** [comment]
> I'm not sure what you mean.

When changing a file - the changes are not displayed in the browser, only after reloading the page. This can be seen in the video and in the reproduction

**Comment by manniL** [comment]
This is indeed related to pinia and not a Nuxt issue.

See https://pinia.vuejs.org/cookbook/hot-module-replacement.html#hmr-hot-module-replacement
