### ISSUE TITLE
useFetch客户端渲染  data返回为null

### ISSUE THREAD

**Issue by NanYuJun** [nuxt/nuxt#22103]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      app, components, runtimeConfig, modules, pinia, vite, css, alias, experimental
- Runtime Modules:  @pinia/nuxt@0.4.11, nuxt-icon@0.4.2
- Build Modules:    -
------------------------------

### Reproduction

```
onMounted(async () => {
	if (process.client) {
		const { data } = await useFetch('http://192.168.0.134:9900/api/order/quotationbar/queryQuotationBarNumber', {
			method: 'post',
			headers: {
				Authorization: 'bearer b70d7091-aa41-4857-9eec-1b1ef336043f',
			},
			server: false,
			lazy: true,
		})
		console.log(data)
	}
})
```

data为null

### Describe the bug

客户端渲染获取到data为null

### Additional context

做了以下尝试

onMounted请求
判断process.client
修改useFetch配置为server为false
lazy为true

都获取不到数据

在浏览器的network是可以看到请求成功的～

**Comment by NanYuJun** [comment]
<img width="2560" alt="image" src="https://github.com/nuxt/nuxt/assets/34359307/3c592ede-0c87-4fb5-82f2-c0e3a66723dd">

**Comment by NanYuJun** [comment]
<img width="1440" alt="image" src="https://github.com/nuxt/nuxt/assets/34359307/1a267d6d-8991-4d4f-b22c-39de4bc58349">

**Comment by NanYuJun** [comment]
前边增加了个await nextTick() 解决了 但是不知道是否是正确的用法

**Comment by warflash** [comment]
Could you explain what you're trying to do? I find that a bit difficult to figure out based on the description. However data will be null when using `lazy: true`. You could set the default value to return an empty array for example or check whether the request is pending and show a loading spinner

**Comment by NanYuJun** [comment]
> 你能解释一下你想做什么吗？我发现根据描述有点难以弄清楚。但是使用时数据将为空`lazy: true`。例如，您可以设置默认值以返回空数组，或者检查请求是否处于待处理状态并显示加载微调器

我想实现进入页面购物车数量的加载，客户端发送请求，lazy:true 只是我的一个尝试

**Comment by warflash** [comment]
I'm still not sure I got that since translation is hard but:
```ts
const { data, pending } = await useFetch('http://192.168.0.134:9900/api/order/quotationbar/queryQuotationBarNumber', {
			method: 'post',
			headers: {
				Authorization: 'bearer b70d7091-aa41-4857-9eec-1b1ef336043f',
			},
			lazy: true,
		})
```
at the top level, not nested in onMounted etc. would be what I'd go for. Then in your template check v-if="pending" and render your loading state accordingly

**Comment by lz6060788** [comment]
![image](https://github.com/nuxt/nuxt/assets/98386138/f2c7506a-6552-4dc3-a091-ecc0ec9027f0)
https://www.nuxt.com.cn/docs/api/composables/use-fetch

**Comment by NanYuJun** [comment]
> ![image](https://user-images.githubusercontent.com/98386138/253146584-f2c7506a-6552-4dc3-a091-ecc0ec9027f0.png) https://www.nuxt.com.cn/docs/api/composables/use-fetch

那我应该如何正确的处理他，从客户端获取数据，目前我用await nextTick()解决了这个问题 但是我感觉这样式不科学的
<img width="700" alt="image" src="https://github.com/nuxt/nuxt/assets/34359307/e88e184f-4b2b-40db-97d9-280ab8f912cd">

**Comment by lz6060788** [comment]
> > ![image](https://user-images.githubusercontent.com/98386138/253146584-f2c7506a-6552-4dc3-a091-ecc0ec9027f0.png) https://www.nuxt.com.cn/docs/api/composables/use-fetch
> 
> 那我应该如何正确的处理他，从客户端获取数据，目前我用await nextTick()解决了这个问题 但是我感觉这样式不科学的 <img alt="image" width="700" src="https://user-images.githubusercontent.com/34359307/253148140-e88e184f-4b2b-40db-97d9-280ab8f912cd.png">

onMounted中会立即触发useFetch的then，其中的data就为null，因此直接在then内进行缓存操作应该是不行的，我也在头疼这个问题，或许应该抛弃useFetch，而我的方式是封装useFetch，传入回调函数，在onResponseCallback中进行操作，感觉也并不是很棒。

**Comment by YIngChenIt** [comment]
use $fetch

**Comment by fxzer** [comment]
我也遇到了这个问题，为什么第一次请求有，刷新浏览器就 Chrome网络面板就看不到发送的请求，useFetch返回的data为 null，网上说清缓存，useClearData试了没效果，

```js
const cards = ref([])

async function queryAccess() {
  const defaultQueryObj = {
    conditions: [],
    limit: 10,
    start: 0,
    count: false,
    replyWithCount: true,
    noError: false,
    sortBy: 'createDate',
    sortDirection: 'asc',
  }

  const { data } = await useFetch('/website/api', {
    // key: 'queryAccess',
    method: 'POST',
    body: {
      'com.syscxp.header.website.access.APIQueryQuickAccessMsg': defaultQueryObj,
    },
  })
  return data.value as any
}

const dv = await queryAccess()
// await clearNuxtData('queryAccess')
const result = dv ? Object.values(JSON.parse(dv.result))[0] as any : {}
cards.value = result.success ? result.inventories : []
console.log('[ cards.value  ]-114', cards.value)
```
## 使用$fetch项目直接报错
![image](https://github.com/nuxt/nuxt/assets/68853957/280c3d1c-8869-4d72-94dd-dfee3fa3ed0d)

**Comment by danielroe** [comment]
@fxzer Check out https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables.

**Comment by fxzer** [comment]
？？？看了一遍没发现解决方案啊
---- 回复的原邮件 ----
| 发件人 | Daniel ***@***.***> |
| 发送日期 | 2023年08月11日 18:16 |
| 收件人 | nuxt/nuxt ***@***.***> |
| 抄送人 | fxzer ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [nuxt/nuxt] useFetch客户端渲染 data返回为null (Issue #22103) |

@fxzer Check out https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables.

**Comment by Pancts** [comment]
set `useNuxtApp().payload.serverRendered = false`

**Comment by fxzer** [comment]
我直接用axios替代useFetch，之前不知道还可以这样
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年09月12日 14:18 |
| 收件人 | nuxt/nuxt ***@***.***> |
| 抄送人 | fxzer ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [nuxt/nuxt] useFetch客户端渲染 data返回为null (Issue #22103) |

set useNuxtApp().payload.serverRendered = false

**Comment by tanglongyan** [comment]
> set `useNuxtApp().payload.serverRendered = false`

这种方式就不走服务端渲染了，渲染页面能展示，但是检查网页源代码发现只渲染了空标签没实际的内容，这种方式还能做seo吗？

**Comment by liaow-ww** [comment]
> > set `useNuxtApp().payload.serverRendered = false`
> 
> 这种方式就不走服务端渲染了，渲染页面能展示，但是检查网页源代码发现只渲染了空标签没实际的内容，这种方式还能做seo吗？

解决了吗，我也遇到了这个问题

**Comment by sunriseLix** [comment]
试试加个key

**Comment by fanmucc** [comment]
我现在也遇到了这个问题，只有初始化时才会有，useFetch服务端数据正常获取，客户端则拿不到data中返回的数据，光打印data是能够看到数据的，但是数据取出来就为null。 同一个接口需要同时判断服务端和客户端
![客户端log，取不到data中返回的数据](https://github.com/nuxt/nuxt/assets/38582907/f135b3e4-e2c0-4797-8fff-5e3ba8d272b8)
![服务端正常log](https://github.com/nuxt/nuxt/assets/38582907/a500b7e7-54d0-43eb-909f-597465c1fb81)
![同一个方法需要分别判断](https://github.com/nuxt/nuxt/assets/38582907/1e822f18-83f9-4465-9557-81dcc9839867)
![useFetch调用](https://github.com/nuxt/nuxt/assets/38582907/61a76371-2ce6-4209-aecd-524f8937ac15)
有什么最终解决方案吗？这样每个接口做服务端处理的时候，太多相同代码需要处理了

**Comment by GArosy** [comment]
我使用`$fetch`解决了这个问题：
``` ts
export const useFetchData = (url: string, options?: any) => {
  const config = useRuntimeConfig()
  return $fetch(config.public.baseURL + url, options)
}
```
我的理解是useFetch专注于SSR，首次请求下它会默认读取服务器上一次的缓存，而在客户端下没有缓存这一概念，所以nuxt会认为命中了一个空缓存，反映出来就是首次加载的data为空。
遇到在客户端直接发起请求的场景，使用$fetch是官方推荐的做法：
<img width="598" alt="image" src="https://github.com/nuxt/nuxt/assets/96174912/5d4104b7-8d9b-4faa-a2e6-602f374d8c7d">
仅是个人猜测，请指正~

**Comment by winterZhao** [comment]
封装两个，一个用useFetch给服务端用，一个用$fetch给客户端用

**Comment by Hyebin98** [comment]
有什么最终解决方案吗？

**Comment by eYesInYours** [comment]
在其他地方看到的一个回答：不把接口请求写在onMounted这种生命钩子中就可以，我的问题是这样解决的

**Comment by HC-miss** [comment]
封装两个，一个用useFetch给服务端用，一个用$fetch给客户端用
在其他地方看到的一个回答：不把接口请求写在onMounted这种生命钩子中就可以

综上所述
