### ISSUE TITLE
Cannot use import.meta.glob in server/api

### ISSUE THREAD

**Issue by Rigo-m** [nuxt/nuxt#22106]
### Environment

https://stackblitz.com/edit/github-kaqv4b?file=server%2Fapi%2FtestApi.ts

### Reproduction

https://stackblitz.com/edit/github-kaqv4b?file=server%2Fapi%2FtestApi.ts

### Describe the bug

Cannot use import.meta.glob inside server apis, tried both inside the defineEventHandler and outside of it

Error given:
`[nuxt] [request error] [unhandled] [500] globalThis._importMeta_.glob is not a function `

**Comment by danielroe** [comment]
`import.meta.glob` is a Vite utility and not available within Nitro server endpoints.

Feel free to raise a feature request at https://github.com/unjs/nitro (or update docs if it's wrongly implying this is available). 🙏
