### ISSUE TITLE
error hook not catching errors?

### ISSUE THREAD

**Issue by minkoonim** [nuxt/nuxt#22109]
### Environment

- Operating System: Linux
- Node Version:     v18.15.0
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      typescript, app, modules, nitro, runtimeConfig, css, vue, build, imports, pinia, piniaPersistedstate, i18n, devtools
- Runtime Modules:  @pinia/nuxt@0.4.11, @pinia-plugin-persistedstate/nuxt@1.1.1, @nuxtjs/i18n@8.0.0-beta.13, @unocss/nuxt@0.53.5, @vueuse/nuxt@10.2.1, @nuxtjs/device@3.1.0, @nuxt/content@2.7.0
- Build Modules:    -

### Reproduction

```
// plugins/hook.ts
// code from doc's example
export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.hook('vue:error', (..._args) => {
    console.log('vue:error')
    // if (process.client) {
    //   console.log(..._args)
    // }
  })
  nuxtApp.hook('app:error', (..._args) => {
    console.log('app:error')
    // if (process.client) {
    //   console.log(..._args)
    // }
  })
  nuxtApp.vueApp.config.errorHandler = (..._args) => {
    console.log('global error handler')
    // if (process.client) {
    //   console.log(..._args)
    // }
  }
})
```

```
// server/api/someapi/index.get.ts
export default defineEventHandler(async (event) => {
  const data = getSomeData()
  if (!data)
    throw createError({statusCode: 404, statusMessage: 'errors.404_notfound'})
})
```

```
error message from console:
Uncaught (in promise) Error: errors.404_notfound
```

```
// layout/alert.vue
<template>
  <div>
    $t('some error messages')
  </div>
</template>
```

### Describe the bug

I want to popup error message when error occurs,
and was hoping nuxt hook would catch all the errors created by createError(),
so I can place popup alert function inside nuxt hook,
but it doesn't catch anything.

I have alert function ready for successful / failed api result,
just don't know how I can globally catch errors and handle them.

I don't want to render a full page of error and let user go back by using clearError,
I just want to simply catch it and show them what's wrong

**Comment by danielroe** [comment]
`useAsyncData` and `useFetch` errors are not caught by any hook but accessible in the `error` Ref returned from the composables.

And yes, you're right that not all errors will be caught in these hooks, only errors that are caught by Vue itself. A PR to improve the docs here would be very welcome 🙏

**Comment by laurensV** [comment]
> `useAsyncData` and `useFetch` errors are not caught by any hook

Would be great though if there would also be an error hook for useAsyncData.. Right now if I want to also console log the error, I have to either make watchers for every ref error object from useAsyncData, or add my own try/catch block in useAsyncData and then throw the error again after console logging..
