### ISSUE TITLE
ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'hook')

### ISSUE THREAD

**Issue by jcalfee** [nuxt/nuxt#22113]
### Environment

node v16.17.1
"nuxt": "^3.6.2"
yarn 1.22.19

What could possibly cause currentNuxt.hooks to be undefined? 
```
[web] currentNuxt.hooks undefined
[web] 
[web]  ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'hook')
[web] 
[web]   at load (node_modules/nuxi/dist/chunks/dev.mjs:211:41)
[web]   at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:250:5)
[web]   at async _main (node_modules/nuxi/dist/cli.mjs:49:20)
```
Right above it it is awaiting on Ready
```js
        await currentNuxt.ready();
        distWatcher = chokidar.watch(resolve(currentNuxt.options.buildDir, "dist"), { ignoreInitial: true, depth: 0 });
        distWatcher.on("unlinkDir", () => {
          dLoad(true, ".nuxt/dist directory has been removed");
        });
        const unsub = currentNuxt.hooks.hook("restart", async (options2) => {
          unsub();
          if (options2?.hard) {
            return hardRestart();
          }
          await load(true);
        });
```

I have commented out everything in nuxt.config.js 

### Reproduction

I can't reproduce it on the web, I have tried everything. 

### Describe the bug

I'm seeing different issues on the same code just by changing package managers or when trying to use the same code online v. local using the same package manager.  So many issues, rarely do I see the issue posted here.

### Additional context

Not sure I can proceed with Nuxt 3.  I'm quite burnt out trying to nail down the issues and trying to re-create them online.

**Comment by danielroe** [comment]
This sounds really frustrating.

Is there a chance you have a node_modules folder in a parent directory that might be getting loaded instead of the Nuxt version you have installed?

Failing that, could you upload your code to a repo that I can see, and provide more information about your system? Also, can you specify exactly the steps you take to create the issue, including what commands you run and what directory you are in? I appreciate that this is frustrating but I've not encountered this before and it sounds like it might be something unique to your setup.

**Comment by jcalfee** [comment]
Yes, I did but remove cleared that out as well.  This is in a new monorepo and I started with a pnpm-workspaces.yml at the root where each project like this one used relative links in the package.json for the other libraries ("mylib":  "link:../mylib").  To rule this out as an issue I deleted the pnpm-workspaces.yml file and cleaned up with `rm -fr node_modules */node_modules; rm -r */.nuxt` and still, after `pnpm i` in each by hand I had the error.

After fixing it with a rename as described above, I'm simply going to maintain each project and library with `pnpm i` by hand without the workspaces until I figure this out.

**Comment by jcalfee** [comment]
Also, I have another Nuxt 2 project in the same mono repo.  I'm using pnpm specifically do keep those two apart as separate everything (links and processes).  They would cross error though detecting both version Nuxt 2 and 3 and refusing to run.  So, something really went wrong outside of Nuxt prior to this.  Although I can't say it is the same issue, it likely is.  It is leading me to believe this is all something in pnpm...  I remove (rm -r) the pnpm store too just incase; that was not an immediate fix though.
