### ISSUE TITLE
Page transition not working with anchor tag

### ISSUE THREAD

**Issue by LucaArgentieri** [nuxt/nuxt#22112]
### Environment

- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      devtools, app
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-qjv6tr-vvemyr?file=app.vue

### Describe the bug

Hi! 💚
I'd tried to use page transition with a vue3 component library that has an anchor tag as a link but it seems not working.
Page transition works only with NuxtLink, the anchor tag does not trigger page transition.

**Comment by doganalper** [comment]
According to the docs, using `NuxtLink` component necessary for using page transitions since it uses `vue-router` under the hood and that prevents full page refresh. Anchor tag however fully refreshes page and that prevents page transition to work.

**Comment by LucaArgentieri** [comment]
I'm developing a component library in vue3 and I would like to use the nuxt3 page transition
How can I achieve that?
