### ISSUE TITLE
useRoute returning empty object

### ISSUE THREAD

**Issue by nurdism** [nuxt/nuxt#22110]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-dzjndw

### Describe the bug

useRoute() returning empty object not the current route

**Comment by danielroe** [comment]
It only seems to be empty when you are stringifying it because now `useRoute` uses getters as a performance improvement. (Also upstream in `vue-router`.)

Try checking the value of `route.fullPath` or `route.params` to see that it's not an empty object.
