### ISSUE TITLE
Prerender skip pages with navigateTo middlware 

### ISSUE THREAD

**Issue by MedBilelAbidi** [nuxt/nuxt#22123]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `alias`, `css`, `plugins`, `runtimeConfig`, `imports`, `build`, `modules`, `experimental`
- Runtime Modules:  `@pinia/nuxt@0.4.6`, `@vueuse/nuxt@9.11.1`
- Build Modules:    `-`

### Reproduction

no Reproduction 

### Describe the bug

nuxt generate skip any pages who have middleware with navigateTo() function when executing the pretender process
here's a code screenshot and logs:
<img width="466" alt="image" src="https://github.com/nuxt/nuxt/assets/102331552/aef62220-5187-415a-9f63-162c16a8d5b8">
<img width="507" alt="image" src="https://github.com/nuxt/nuxt/assets/102331552/cb5db5fe-816e-4772-aa94-fba2efa6961f">

here's a code screenshot and logs when navigateTo() is commented:
<img width="432" alt="image" src="https://github.com/nuxt/nuxt/assets/102331552/5de058f3-8a39-4b1e-9744-2774d8a3d789">
![image](https://github.com/nuxt/nuxt/assets/102331552/41aab4a8-529b-4699-83ba-4897ec43f9b6)
as u can see the marketplace pages and it children routes got prerendered

**Comment by MedBilelAbidi** [comment]
hi @danielroe  i hope this help https://stackblitz.com/edit/github-kbdmh7?file=middleware%2Fauth.ts

**Comment by danielroe** [comment]
A few comments:

1. pages should be in the `~/pages` directory, and you only have one `index.vue`, not the routes referenced in your middleware
2. middleware should always check that you are not redirecting to the current path or you will produce an infinite loop (e.g. the code `if (!cookies.value) return navigateTo('/authentication/sign-in');` will always redirect, even on the sign-in page).
