### ISSUE TITLE
Nuxt 3.6.2 breaks vite manualChunks

### ISSUE THREAD

**Issue by sei-jdshimkoski** [nuxt/nuxt#22127]
### Environment

Nuxi 3.6.2                                                          10:21:42 AM
                                                                    10:21:42 AM
RootDir: /home/projects/github-doxyzh                               10:21:42 AM
Nuxt project info:                                                  10:21:42 AM

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      vite
- Runtime Modules:  -
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new         10:21:42 AM

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Reproduction

https://stackblitz.com/edit/github-doxyzh?file=nuxt.config.ts

In the terminal, run `npm run build`.

### Describe the bug

With a vite manualChunks config, `npm run build` breaks:

```
// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  vite: {
    build: {
      rollupOptions: {
        output: {
          manualChunks(_id) {
            return 'index';
          },
        },
      },
    },
  },
});
```

Present errors like this:

```
[10:18:56 AM]  ERROR  "vue" cannot be included in manualChunks because it is resolved as an external module by the "external" option or plugins.

  at error (node_modules/rollup/dist/es/shared/node-entry.js:2270:30)
  at Bundle.assignManualChunks (node_modules/rollup/dist/es/shared/node-entry.js:17786:28)
  at Bundle.generateChunks (node_modules/rollup/dist/es/shared/node-entry.js:17818:20)
  at Bundle.generate (node_modules/rollup/dist/es/shared/node-entry.js:17732:39)
  at async eval (node_modules/rollup/dist/es/shared/node-entry.js:26590:27)
  at async catchUnfinishedHookActions (node_modules/rollup/dist/es/shared/node-entry.js:25723:16)
  at async Module.build (node_modules/vite/dist/node/chunks/dep-e8f070e8.js:46529:22)
  at async buildServer (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.ff002a15.mjs:773:5)
  at async bundle (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.ff002a15.mjs:1434:3)
  at async build (node_modules/nuxt/dist/index.mjs:3801:5)
```

**Comment by sei-jdshimkoski** [comment]
Please note: it is possible to manually ignore ids (but this doesn't actually create a single chunck):

```
vite: {
    build: {
      rollupOptions: {
        output: {
          manualChunks(id) {
            if (!id.includes('vue')) {
              return 'index'
            }
          }
        },
      },
    },
```

This incurs more issues:

1. It is unsustainable with large projects
2. This removes that ability to have a single chunk which is a blocker for us due to host configuration settings and performance issues with the stock chunk settings.

**Comment by bigshans** [comment]
`vue` is included in the `external`. It's rollup option, [docs here](https://rollupjs.org/configuration-options/#external).
You can try to fix it like this:

```javascript
export default defineNuxtConfig({
  vite: {
    build: {
      rollupOptions: {
        output: {
          manualChunks(_id) {
            if (!_id.includes('/home/projects')) {
              return;
            }
            return 'index';
          },
        },
      },
    },
  },
});
```

Hope this can help you.

**Comment by sei-jdshimkoski** [comment]
> 

Unfortunately, your solution does not fix the issue as it bloats the amount of requests that go across the wire.

For reference, using the original config as described in this initial ticket in Nuxt version 3.6.1, I was able to reduce 100+ requests down to 40... which drastically improves the performance of the application overall.

3.6.2 breaks the config all together and makes it impossible to have a single chunk.

**Comment by danielroe** [comment]
The issue is that your configuration is trying to configure the _server_ vite config as well as the client one (which is all you really care about).

Try this instead:

```ts
export default defineNuxtConfig({
  hooks: {
    "vite:extendConfig"(config, { isClient })  {
      if (isClient) {
        config.build.rollupOptions.output.manualChunks = function (_id) {
            return 'index';
          }
      }
    }
  }
});
```

**Comment by sei-jdshimkoski** [comment]
> The issue is that your configuration is trying to configure the _server_ vite config as well as the client one (which is all you really care about).
> 
> Try this instead:
> 
> ```ts
> export default defineNuxtConfig({
>   hooks: {
>     "vite:extendConfig"(config, { isClient })  {
>       if (isClient) {
>         config.build.rollupOptions.output.manualChunks = function (_id) {
>           return 'index';
>         }
>       }
>     }
>   }
> });
> ```

This works like a charm. Thank you @danielroe!

**Comment by rafaeelneto** [comment]
> The issue is that your configuration is trying to configure the _server_ vite config as well as the client one (which is all you really care about).
> 
> Try this instead:
> 
> export default defineNuxtConfig({
>   hooks: {
>     "vite:extendConfig"(config, { isClient })  {
>       if (isClient) {
>         config.build.rollupOptions.output.manualChunks = function (_id) {
>           return 'index';
>         }
>       }
>     }
>   }
> });

i would kiss you if i could. This solved my issue
