### ISSUE TITLE
All CSS inline with vite and nuxt 3 after 'nuxt generate'

### ISSUE THREAD

**Issue by lud-hu** [nuxt/nuxt#22139]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.16.1`
- Nuxt Version:     `3.6.2`
- Nitro Version:    `2.5.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `sanity`, `app`, `components`, `css`, `imports`, `modules`, `routeRules`, `hooks`, `runtimeConfig`, `schemaOrg`, `vite`
- Runtime Modules:  `@formkit/nuxt@0.17.4`, `@nuxtjs/sanity@1.7.3`, `@pinia/nuxt@0.4.11`, `@pinia-plugin-persistedstate/nuxt@1.1.1`, `@vueuse/nuxt@10.2.1`, `nuxt-icons@3.2.1`, `nuxt-schema-org@2.2.0`, `vite-plugin-vue-type-imports/nuxt`
- Build Modules:    `-`

### Reproduction

https://github.com/lud-hu/inline-css-nuxt-generate

```bash
yarn
yarn generate
```

### Describe the bug

When setting up a nuxt project, importing a css library like bootstrap with

```js

export default defineNuxtConfig({
  css: ["bootstrap/scss/bootstrap.scss"],
});
```
and running `nuxt generate` - then the generated HTML file will contain the 15k lines of the bootstrap css **inline** instead of linked as an external css for caching.

When executing `nuxt generate`with nuxt@3.0.0 it will properly put the css into a separate file and link it.

**Comment by danielroe** [comment]
You can disable this behaviour with 

```ts
export default defineNuxtConfig({
  experimental: {
    inlineSSRStyles: false,
  }
})
```

**Comment by lud-hu** [comment]
Ah wow, that was easy. Will hidden in the docs 😄 Thanks for the quick help!

**Comment by fabianwohlfart** [comment]
Is `inlineSSRStyles` removed in Nuxt 4?!

**Comment by danielroe** [comment]
no, but it's graduated out of experimental - you can access in `features`

**Comment by fabianwohlfart** [comment]
thanks for the quick reply, are you sure that the default is true? i had to explicitly switch it to true in order to inline my styles.

**Comment by danielroe** [comment]
it inlines styles in vue components but not other global css

check the upgrade guide for details

**Comment by fabianwohlfart** [comment]
fair, it's well explained there. yet the 'official' docs are different:

```
[inlineStyles](https://nuxt.com/docs/4.x/api/nuxt-config#inlinestyles)
Inline styles when rendering HTML (currently vite only).

You can also pass a function that receives the path of a Vue component and returns a boolean indicating whether to inline the styles for that component.

Type: boolean
Default: true
```
https://nuxt.com/docs/4.x/api/nuxt-config#inlinestyles
