### ISSUE TITLE
Composables autoimport doesn't works in my "nuxt": "^3.6.2",

### ISSUE THREAD

**Issue by DidoMarchet** [nuxt/nuxt#22136]
### Environment

"nuxt": "^3.6.2",

### Reproduction

Hi!
I try to add a composable under the composables folder and call it into a vue file.

### Describe the bug

It returns 500 Not Defined

<img width="1047" alt="Screenshot 2023-07-14 at 10 11 07" src="https://github.com/nuxt/nuxt/assets/38940340/b6569e6f-10b3-453d-8a7d-3f688656bfb7">

Thanks and kind regards,

Davide

**Comment by MuhammadM1998** [comment]
I think you need to put a reproduction for others to check it and help you. You can start by adding snippets of how you create the composable and your folder structure. Better yet start with a new project in stackblitz, reproduce the error there and then paste the link here
