### ISSUE TITLE
netlify-builder doesn't reutnr updated value if I change something in the CMS

### ISSUE THREAD

**Issue by DidoMarchet** [nuxt/nuxt#22144]
### Environment

```
"devDependencies": {
    "@nuxt/devtools": "latest",
    "@nuxtjs/apollo": "^5.0.0-alpha.6",
    "@nuxtjs/eslint-config-typescript": "^12.0.0",
    "@nuxtjs/i18n": "^8.0.0-beta.12",
    "@types/node": "^18",
    "@typescript-eslint/parser": "^5.59.11",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-prettier": "^4.2.1",
    "nuxt": "^3.6.2",
    "nuxt-simple-sitemap": "^2.7.0",
    "prettier": "^2.8.8",
    "sass": "^1.63.6",
    "stylelint": "^14.16.1",
    "stylelint-config-prettier": "^9.0.3",
    "stylelint-config-standard": "^26.0.0",
    "stylelint-config-standard-scss": "^6.1.0"
  },
  "dependencies": {
    "@pinia/nuxt": "^0.4.11",
    "pinia": "^2.1.4",
    "scss-react": "^1.0.2",
    "scss-slamp": "^1.3.4",
    "the-new-css-reset": "^1.8.6"
  },
  "overrides": {
    "vue": "latest"
  },
  "type": "module",
```

### Reproduction

Add a dynamic content and build with the `netlify-builder`:
Update the content and try to navigate the frontend.

### Describe the bug

Hi,
when I  build th app  with the `netlify-builder` preset and I update an entry in my CMS, the content are not updated in the frontend.
The `_payload.json` it's not updated.

How can I return the updated content? 

Thanks and kind regards,
Davide

**Comment by danielroe** [comment]
With the netlify builder preset, once first accessed, routes/payloads are not revalidated. I would advise using `netlify` preset and using route rules to configure the TTL/SWR appropriate.

**Comment by DidoMarchet** [comment]
Hi, thanks!
I see that in the configuration  there are routeRules under nitro (where I set the Netlify presets)
```
nitro: {
    routeRules: {
      '/**': { swr: 10 },
    },
```
and under the key routeRules:
```
routeRules: {
      '/**': { swr: 10 },
    }
```

Which of those it's useful form my goal?

Sorry for the dummy -last- question.

Thanks and kind regards,
Davide

**Comment by danielroe** [comment]
Either. Top level routeRules is an alias for convenience.

**Comment by DidoMarchet** [comment]
Thanks again!
Have a nice day,
Davide

**Comment by DidoMarchet** [comment]
Sorry. 
I tried both swr: 80 and isr: 80. 
After building, I looked at the HTML. 
Then, I updated the CMS. 80 seconds later, I checked the app. 
The Ajax navigation is updated, but the HTML still has the old stuff. I don't want to be annoying, but a working example would be nice.

Thansk again and kind regards,

Davide
