### ISSUE TITLE
publish nuxt 3 edge releases to `nuxt-nightly`

### ISSUE THREAD

**Issue by danielroe** [nuxt/nuxt#22143]
Currently we have a slightly inconsistent edge release strategy, whereby `nuxt` is the only package where its edge name doesn't just involve adding `-edge`.

<details>
<summary>Full breakdown</summary>

## Nuxt 3

| Package | Tag | Edge channel | 
| - | - | - |
`@nuxt/kit` | `latest` | `@nuxt/kit-edge`
`nuxi` | `latest` | `nuxi-edge`
`nuxt` | `latest` | `nuxt3`
`@nuxt/schema` | `latest` | `@nuxt/schema-edge`
`@nuxt/test-utils` | `latest` | `@nuxt/test-utils-edge`
`@nuxt/vite-builder` | `latest` | `@nuxt/vite-builder-edge`
`@nuxt/webpack-builder` | `latest` | `@nuxt/webpack-builder-edge`

## Nuxt 2

| Package | Tag | Edge channel |
| - | - | - |
`nuxt` | `2x` | `nuxt-edge`
`nuxt-start` | `latest` | `nuxt-start-edge`
`@nuxt/babel-preset-app` | `latest` | `@nuxt/babel-preset-app-edge`
`@nuxt/cli` | `latest` | `@nuxt/cli-edge`
`@nuxt/core` | `latest` | `@nuxt/core-edge`
`@nuxt/server` | `latest` | `@nuxt/server-edge`
`@nuxt/utils` | `latest` | `@nuxt/utils-edge`
`@nuxt/vue-renderer` | `latest` | `@nuxt/vue-renderer-edge`
`@nuxt/builder` | `latest` | `@nuxt/builder-edge`
`@nuxt/config` | `latest` | `@nuxt/config-edge`
`@nuxt/generator` | `latest` | `@nuxt/generator-edge`
`@nuxt/types` | `latest` | `@nuxt/types-edge`
`@nuxt/vue-app` | `latest` | `@nuxt/vue-app-edge`
`@nuxt/webpack` | `latest` | `@nuxt/webpack-edge`

</details>

I think it make sense to add a `2x` tag to the Nuxt 2 `nuxt-edge` channel, in line with how we're handling `nuxt`. It wouldn't be a breaking change as such as the edge channel is already opting in to breaking changes.

And it also will set us up for future versions of Nuxt, where `nuxt3` will no longer be an accurate package name.

**Comment by pi0** [comment]
On this topic, would be a nice chance to also rename edge channel to `canary` also avoiding to avoid confusing name with edge runtimes.

**Comment by Atinux** [comment]
canary makes sense, also nightly could be another name

**Comment by danielroe** [comment]
Let's see what people think. https://twitter.com/danielcroe/status/1681989670433878017
