### ISSUE TITLE
503 Server Unavailable while server iss running

### ISSUE THREAD

**Issue by mrniamster** [nuxt/nuxt#22150]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v19.9.0
- Nuxt Version:     3.6.3
- Nitro Version:    2.5.2
- Package Manager:  npm@9.6.3
- Builder:          vite
- User Config:      ssr, turnstile, build, hooks, vue, nitro, css, vite, postcss, app, modules, content, googleSignIn, runtimeConfig, devtools
- Runtime Modules:  nuxt-vue3-google-signin@0.0.8, @pinia/nuxt@0.4.11, @nuxt/content@2.7.0, @pinia/nuxt@0.4.11, @vuestic/nuxt@1.0.14, @nuxtjs/turnstile@0.5.0
- Build Modules:    -
------------------------------

### Reproduction

Usually while importing any file,still unable to find exactly when this happens

### Describe the bug

Whenever I'm importing a file ,the below message come in all suddent, after  reloading from browser still it doesn't go also after doing a npm run dev from same route ,

<img width="1240" alt="image" src="https://github.com/nuxt/nuxt/assets/52563039/3fe269ac-4a06-4df4-80d2-8c854b49b141">

**Comment by mrniamster** [comment]
@danielroe  @antfu  Unable to provide reproduction for it,The problem is :
It navigates to / but when you directly try to visit any other page '/dashboard/profile' in chrome and press enter, 

The Tab keeps loading.

**Comment by pi0** [comment]
Hi. Sorry, it took long for addressing this issue. You can track upstream investigation via https://github.com/unjs/nitro/issues/1454
