### ISSUE TITLE
Don't work HMR on custom folder

### ISSUE THREAD

**Issue by Gumper-x** [nuxt/nuxt#22155]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.6.2`
- Nitro Version:    `2.5.2`
- Package Manager:  `npm@9.5.0`
- Builder:          `vite`
- User Config:      `devtools`, `dir`, `alias`, `vite`, `hooks`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

I made a custom plugin for vite, but nuxt doesn't catch changes and I can't find a way to call nuxt HMR to restart the build

### Describe the bug

```ts
import fs from 'fs'
import { PluginOption, TransformResult } from 'vite'

export function templateResolver(
  defaultPath: string,
  templatePath: string
): PluginOption {
  const pathRegexp = new RegExp(`${defaultPath}(?!.*\?[^&]+=([^&]+))`)

  return {
    name: 'template-resolver',
    handleHotUpdate({ file, server, modules }) {
      console.log(file) // Log saved filed
    },
    load(src) {
      if (pathRegexp.test(src)) {
        const data = fs.readFileSync(
          src.replace(defaultPath, templatePath),
          'utf8'
        )
        return {
          code: data,
          map: null,
        }
      }
    },
  }
}

```

**Comment by danielroe** [comment]
This is really a vite/rollup question - there's documentation on the vite plugin API here: https://vitejs.dev/guide/api-plugin.html#authoring-a-plugin

You are probably wanting `this.addWatchFile`: https://rollupjs.org/plugin-development/#this-addwatchfile.
