### ISSUE TITLE
Router Transition Error when changing routes fast when mode is 'out-in', and with single div on root in the page.

### ISSUE THREAD

**Issue by ivan-angjelkoski** [nuxt/nuxt#22168]
### Environment

Nuxt 3

### Reproduction

apply a longer page transition and use 'out-in' mode, and an error occurs. i made sure every page has 1 div in the root and not multiple but still the error occures.

### Describe the bug

apply a longer page transition and use 'out-in' mode, and an error occurs. i made sure every page has 1 div in the root and not multiple but still the error occures.

**Comment by TutorFx** [comment]
Did you got this error migrating from 3.5.3 to 3.6.1? becouse i got the same error.

**Comment by Jannchie** [comment]
https://github.com/nuxt/nuxt/issues/22093 

Is that the same issue as yours?

**Comment by Jannchie** [comment]
If the problem is exactly the same, there is a work around. you need to add the following code to `/plugins`.

<details>
<summary> Here is the work around </summary>

``` ts
let running: boolean
let nextRoute: string | null

export default defineNuxtPlugin({
  name: 'fix-transiton',
  setup(app) {
    app.hook('page:start', () => {
      const nuxtApp = useNuxtApp()
      running = false
      nuxtApp.$router.beforeEach((to, _, next) => {
        if (running) {
          next(true)
        }
        else {
          nextRoute = to.fullPath
          next(false)
        }
      })
    })
    app.hook('page:transition:finish', () => {
      const nuxtApp = useNuxtApp()
      running = true
      if (nextRoute) {
        nuxtApp.$router.push(nextRoute)
        nextRoute = null
      }
    })
    return {
      provide: {
        hooks: {
          'page:transition:finish': function () {
            const nuxtApp = useNuxtApp()
            running = true
            if (nextRoute) {
              nuxtApp.$router.push(nextRoute)
              nextRoute = null
            }
          },
        },
      },
    }
  },
})

```

</details>

**Comment by danielroe** [comment]
I think the issue is being tracked in https://github.com/nuxt/nuxt/issues/13350. It's an upstream vue issue although it now occurs more frequently due to Nuxt using `<Suspense>` as the parent of layouts.
