### ISSUE TITLE
TypeScript type error in `useFetch` default option with `ResT` generic and `transform` returning `unknown` when making external server requests

### ISSUE THREAD

**Issue by Rock070** [nuxt/nuxt#22164]
### Environment

Node Version: v16.20.0
Nuxt Version: 3.6.2

### Reproduction

https://stackblitz.com/edit/nuxt-starter-xrqqhx?file=composables%2Ftest.ts

### Describe the bug

When using `useFetch` with the `ResT` generic, a TypeScript type error occurs with the `default` option. The error message is as follows:

```ts
useFetch<number[]>('/api/count', {
  default: () => [0]
}
```

```
Type '() => number[]' is not assignable to type '() => Ref<null> | null'.
```

However, the error can be resolved by using the following syntax:

```ts
useFetch<number[]>('/api/count', {
  default: (): number[] => [0]
}
```

But when making requests to an external server, using this syntax causes the `res` parameter in the `transform` function to be of type `unknown` instead of `number[]`. An example of this issue is shown below:

```ts
const { data: data2 } = useFetch('https://reqres.in/api/users?page=2', {
  default: (): number[] => [],
  transform(res){
    return res.map(i => i);
  }
});
```

```
'res' is of type 'unknown'.
```

**Comment by 94726** [comment]
> But when making requests to an external server, using this syntax causes the res parameter in the transform function to be of type unknown instead of number[]. An example of this issue is shown below:

For now, you would have to do something like this:
```ts
const { data: data2 } = useFetch('https://reqres.in/api/users?page=2', {
  default: (): number[] => [],
  transform(res: number[]){
    return res.map(i => i);
  }
});
```
`data2` will then have a correctly inferred type based on the ReturnTypes of default and transform which in this case is `never[] | number[]`. The `never[]` unfortunately comes from `[]`, for which you also have to explicitly set `number[]`.
