### ISSUE TITLE
Provide RouterLink-compatible `useLink` method

### ISSUE THREAD

**Issue by so1ve** [nuxt/nuxt#22169]
### Describe the feature

https://github.com/vuetifyjs/vuetify/issues/17490

vue-router has a method call `RouterLink.useLink`, but it doesn't exist in `NuxtLink`.

### Additional information

- [x] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by so1ve** [comment]
Hi @danielroe any progress on this?

If nuxt team doesn't have enough bandwidth on this, any thoughts on how to implement this feature? I tried, but with no luck.

**Comment by kingyue737** [comment]
Looking forward to this feature too
