### ISSUE TITLE
On initial load safari browser is giving errors

### ISSUE THREAD

**Issue by remcoz** [nuxt/nuxt#22172]
### Environment

 2.15.8

### Reproduction

2.15.8

### Describe the bug

In my Nuxt js app on production server i am getting issue with safari browser both on desktop and mobile view on initial load. i am using Nuxt version 2.15.8. On initial load safari browser is giving errors and not applying search on button click and returning these errors (see log) . When refresh the page it works fine, but not on the initial load. 

### Logs

```shell-script
SyntaxError: Unexpected identifier 'lValue'. Expected an opening '(' before a function's parameter list
SyntaxError: Unexpected identifier 'y'. Expected an opening '(' before a function's parameter list.
```

**Comment by danielroe** [comment]
Likely some library you are using needs to be transpiled because its code is too modern for Safari. You can do this by adding it to `build.transpile`.

**Comment by rajpootAbubakkar** [comment]
HI @danielroe i have added build.transpile in nuxt.config file. But it is still giving error on initial load. when i do hard refresh it worked.
```
build: {
    transpile: [
      'defu'
    ],
}
```

**Comment by abdullah-336** [comment]
I am also facing the same issue on node version of 16.20.0 and nuxt version 2.17.0. It is creating issue with my production website which is causing issue to the customers to login or apply search after initial load.
