### ISSUE TITLE
useFetch corrupting params containing "%"

### ISSUE THREAD

**Issue by blacksheep107** [nuxt/nuxt#22186]
### Environment

windows
Nodejs 18.14.0
Nuxt3.6.3

### Reproduction

```
const {data, error} = await useFetch("https://api.com/get", {
  params: {
    path: "path1%7Cpath2"
  }
});
console.log(data, error);
```

### Describe the bug

useFetch will auto encoded params's special characters, like % will be encoded to %25 :

which means server actually request url is: https://api.com/get?path=path1%257Cpath2

While the character "|" will not be encoded to "%7C", this is confusing.
Is this a bug or feature?

By the way, my workaround is concating params in url instead of using params option, like this: 
```
const {data, error} = await useFetch("https://api.com/get?path=path1%7Cpath2");
console.log(data, error);
```

```[tasklist]
### Tasks
```

**Comment by danielroe** [comment]
This is upstream behaviour from https://github.com/unjs/ufo (specifically in `withQuery`). Would you mind raising an issue there?
