### ISSUE TITLE
Generate command crawls to strange url

### ISSUE THREAD

**Issue by sherlockmac** [nuxt/nuxt#22180]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.16.1`
- Nuxt Version:     `3.6.3`
- Nitro Version:    `2.5.2`
- Package Manager:  `pnpm@8.6.8`
- Builder:          `vite`
- User Config:      `devtools`, `modules`, `site`, `css`, `robots`, `runtimeConfig`, `swiper`, `mapbox`, `gtag`, `routeRules`, `experimental`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.8.0`, `nuxt-swiper@1.1.1`, `nuxt-mapbox@1.3.9`, `@vueuse/nuxt@10.2.1`, `nuxt-gtag@0.5.7`, `nuxt-simple-sitemap@3.0.11`, `@nuxtjs/robots@3.0.0`
- Build Modules:    `-`

### Reproduction

The crawler starts with these two links during the `generate` phase:
```
├─ /%23a (19ms) (Error: [404] Page not found: /%2523a)                                       nitro 1:56:34 AM
├─ /%23b (18ms) (Error: [404] Page not found: /%2523b)                                       nitro 1:56:34 AM
```

adding the same `/#a` and  `/#b` to all the rest of the urls like so:
```
├─ /products/%23b (956ms)                                                                    nitro 1:56:36 AM
```
```
├─ /products/%23a (1058ms)                                                                   nitro 1:56:36 AM
```
it will end with:
```
Errors prerendering:
  ├─ /%23a (404)                                                                               nitro 1:56:40 AM
  ├─ /%23b (404)                                                                               nitro 1:56:40 AM
                                                                                               nitro 1:56:40 AM

 ERROR  Exiting due to prerender errors.                                                             1:56:40 AM

  at prerender (node_modules/.pnpm/nitropack@2.5.2/node_modules/nitropack/dist/shared/nitro.1db3349c.mjs:189:11)
  at async node_modules/.pnpm/nuxt@3.6.3_@types+node@18.0.0_sass@1.63.6/node_modules/nuxt/dist/index.mjs:2640:7
  at async build (node_modules/.pnpm/nuxt@3.6.3_@types+node@18.0.0_sass@1.63.6/node_modules/nuxt/dist/index.mjs:3791:5)
  at async Object.invoke (node_modules/.pnpm/nuxi@3.6.3/node_modules/nuxi/dist/chunks/build.mjs:59:5)
  at async Object.invoke (node_modules/.pnpm/nuxi@3.6.3/node_modules/nuxi/dist/chunks/generate.mjs:36:5)
  at async _main (node_modules/.pnpm/nuxi@3.6.3/node_modules/nuxi/dist/cli.mjs:49:20)

 ELIFECYCLE  Command failed with exit code 1.
```

### Describe the bug

As mentioned above the Nitro crawler seems to add `/#a` and `/#b` to every route until it exits due to prerender errors. I tried to exclude the aforementioned urls with no luck. The repo is private but I can give access to any team member who wants to invistigate.

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by sherlockmac** [comment]
@danielroe thanks for the reply; I just gave you access to the repo. 🙏🏼

**Comment by danielroe** [comment]
Your repo is using Nuxt 2 and Vue 2 🤔

**Comment by sherlockmac** [comment]
> Your repo is using Nuxt 2 and Vue 2 🤔

sorry wrong repo ... I added you to the correct one 😅

**Comment by sherlockmac** [comment]
@danielroe I appreciate your time; been seeing you a lot on YouTube ⭐

**Comment by iBobik** [comment]
Btw, I have the same issue in this public project:
https://github.com/iBobik/berubitcoin/tree/osm-nuxt3

```


:10:03.049 | [log] [nitro] prerender:route: 0.006ms
-- | --
17:10:03.049 | [log] [nitro]   ├─ /%23a (39ms) (Error: [404] Page not found: /%2523a)
17:10:03.050 | [log] [nitro] prerender:generate: 0.009ms
17:10:03.050 | [log] [nitro] prerender:route: 0.006ms
17:10:03.050 | [log] [nitro]   ├─ /%23b (35ms) (Error: [404] Page not found: /%2523b)


```

**Comment by iBobik** [comment]
Btw this would help with debugging: #8184

**Comment by iBobik** [comment]
Updated to Nuxt 3.6.5, not solved.

**Comment by iBobik** [comment]
Workaround:
```
  nitro: {
    prerender: {
      ignore: [
        '/%23',
      ],
    },
  },
```

**Comment by sherlockmac** [comment]
Setting ```failOnError``` to ```false``` bypasses the error, but it will generate the ``/%23`` links anyway.

```js
  nitro: {
    prerender: {
      failOnError: false,
    },
  },
```

I've checked my own code and believe that some of the fault is related to lack of error handling on my ```useFetch``` calls. I'm looking into the way Nitro handles the crawling so I might find the root of the issue.

**Comment by surgiie** [comment]
Ive started to get urls like this as well:

'/%60'
/example/%2560

Even though the url being passed to prerenderer doesnt contain any characters that would result in this encoding.

Did something change in a recent release? My builds were working fine a few days ago. 🤔

**Comment by surgiie** [comment]
> Workaround:
> 
> ```
>   nitro: {
>     prerender: {
>       ignore: [
>         '/%23',
>       ],
>     },
>   },
> ```

Does this feature work with dynamic urls/wildcards? I cant seem to get this to work with urls like `/*/*/example/%60`

**Comment by danielroe** [comment]
The issue in the originally reported issue is the same as https://github.com/unjs/nitro/issues/1527 and is coming from an `xlink:href` inside an encoded svg within the CSS.

**Comment by sherlockmac** [comment]
> The issue in the originally reported issue is the same as [unjs/nitro#1527](https://github.com/unjs/nitro/issues/1527) and is coming from an `xlink:href` inside an encoded svg within the CSS.

Thank you for the time. I was looking at the same line but didn't get to push it.
