### ISSUE TITLE
[nuxt] [request error] [unhandled] [500] The requested module '@intlify/core-base' does not provide an export named 'compile'

### ISSUE THREAD

**Issue by iksiecbi740** [nuxt/nuxt#22185]
### Describe the feature
Environment
Operating System: mac
Node Version: v16.3.1
Nuxt Version: 3.6.3
Nitro Version: 2.5.2
Package Manager: yarn@1.22.19
Builder: vite

[nuxt] [request error] [unhandled] [500] The requested module '@intlify/core-base' does not provide an export named 'compile'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)  
  at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)  
  at async Promise.all (index 0)  
  at async ESMLoader.import (node:internal/modules/esm/loader:530:24)  
  at async ./.output/server/chunks/handlers/renderer.mjs:73:24  
  at async ./.output/server/chunks/handlers/renderer.mjs:154:64  
  at async ./.output/server/chunks/handlers/renderer.mjs:19:22  
  at async Object.handler (./.output/server/node_modules/h3/dist/index.mjs:1284:19)  
  at async Server.toNodeHandle (./.output/server/node_modules/h3/dist/index.mjs:1359:7)

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by jrutila** [comment]
I started getting this error in `nuxt generate` after adding i18n into my project. @iksiecbi740 do you have `@nuxtjs/i18n` installed? And what version?
Mine is `8.0.0-beta.13`

**Comment by jrutila** [comment]
I found this document: https://vue-i18n.intlify.dev/guide/advanced/optimization.html

I followed it and installed `@intlify/unplugin-vue-i18n` and configured it like this to `nuxt.config.ts`
```
hooks: {
    "vite:extendConfig": (config, { isClient }) => {
      config.plugins.push(
        VueI18nPlugin({}),
      )
   })
```

After that, the missing compile errors vanished when I run `npm run dev`, and the translations are compiled on the server side. But still, running `npm run generate` gives me this error:

```
✔ Server built in 24010ms                                                                                                                                                                                                                                               9.01.33
✔ Generated public .output/public                                                                                                                                                                                                                                 nitro 9.01.34
ℹ Initializing prerenderer                                                                                                                                                                                                                                        nitro 9.01.34
ℹ Prerendering 5 initial routes with crawler                                                                                                                                                                                                                      nitro 9.01.43

 ERROR  [nuxt] [request error] [unhandled] [500] The requested module 'file://C:/project/node_modules/@intlify/core-base/index.mjs' does not provide an export named 'isMessageAST'                                         9.01.43  
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)


 ERROR  [nuxt] [request error] [unhandled] [500] The requested module 'file://C:/project/node_modules/@intlify/core-base/index.mjs' does not provide an export named 'isMessageAST'                                         9.01.43  
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)

  ├─ / (153ms) (Error: [500] )                               
```

**Comment by jrutila** [comment]
I have tried to reproduce this on StackBlitz but it works. I suspect my project has certain settings that will cause other problems, too. For example, #22046 is similar, in that it breaks `generate` on my project but not in StackBlitz.

Any hints on where should I look for this are appreciated.

**Comment by szulcus** [comment]
I also have this problem:
```
 ERROR  [nuxt] [request error] [unhandled] [500] Named export 'camelizeKeys' not found. The requested module 'file://C:/Users/.../node_modules/humps/humps.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'file://C:/Users/.../node_modules/humps/humps.js';
const { decamelizeKeys, camelizeKeys } = pkg;
```
I use `humps` in nuxt layer. Previously aliases fixed it, but now I can't generate my project :/.
In nuxt/config.ts I have:
```ts
export default defineNuxtConfig({
// ...
	alias: {
		axios: 'axios',
		humps: 'humps',
		qs: 'qs',
		dayjs: 'dayjs',
		'crypto-js': 'crypto-js',
	},
});
```

**Comment by sauravbv** [comment]
Have the same issue, runs fine in local dev server, but not from the build bundle..

**Comment by jrutila** [comment]
The problem in my project was, that the `@intlify/core-base` was resolved to version `9.2.2`.
I removed `node_modules` *and* `package-lock.json` and run `npm i`. It resolved to `9.3.0-beta.22` that _should_ work. But something is pushing it back to `9.2.2` in my project.

Check your `@intlify/core-base` from `head node_modules/\@intlify/core-base/package.json`.

**Comment by jrutila** [comment]
Got it to work. It was vuetify that was pushing the `vue-i18n` package back.
I added this to `package.json`:

```
  "overrides": {
    "vue-i18n": "^9.3.0-beta.22"
  }
```

And now the generate and dev run are working without warnings or errors.

**Comment by cesxhin** [comment]
Same problem with @nuxtjs/i18n@8.0.0-beta.13 and I solved this problem by rolling back with the version of @nuxtjs/i18n@8.0.0-beta.12

**Comment by jrutila** [comment]
I would suggest this is a duplicate with https://github.com/nuxt-modules/i18n/issues/2243 and that is the place to actually fix this. So this issue could be closed?

**Comment by sonsoixam** [comment]
Sep 5 06:06:32 PM  [nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 't')
Sep 5 06:06:32 PM    at formatParts (./.output/server/node_modules/@intlify/core-base/dist/core-base.mjs:823:15)
Sep 5 06:06:32 PM    at msg (./.output/server/node_modules/@intlify/core-base/dist/core-base.mjs:818:26)
Sep 5 06:06:32 PM    at evaluateMessage (./.output/server/node_modules/@intlify/core-base/dist/core-base.mjs:1265:22)
Sep 5 06:06:32 PM    at translate (./.output/server/node_modules/@intlify/core-base/dist/core-base.mjs:1087:22)
Sep 5 06:06:32 PM    at ./.output/server/chunks/app/server.mjs:1352:46
Sep 5 06:06:32 PM    at wrapWithDeps (./.output/server/chunks/app/server.mjs:1336:13)
Sep 5 06:06:32 PM    at Proxy.t (./.output/server/chunks/app/server.mjs:1352:12)
Sep 5 06:06:32 PM    at _sfc_ssrRender (./.output/server/chunks/app/_nuxt/index-6c95d79f.mjs:88:36)
Sep 5 06:06:32 PM    at renderComponentSubTree (./.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:423:9)
Sep 5 06:06:32 PM    at renderComponentVNode (./.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:371:12)

anyone can help me ? 
i deloy on render.com

**Comment by vallmar** [comment]
@sonsoixam try adding 
lazy: true
to your nuxt.config i18n section
and make sure you have a i18n.config.ts in your root.

Mine looks as:
//nuxt.config
i18n: {
    locales: [
      { code: 'en', iso: 'en-US' , file: 'en.js'},
      { code: 'sv', iso: 'sv-SE' , file: 'sv.js'},
      { code: 'no', iso: 'nn-NO', file: 'no.js' },
      // Add more locales as needed
    ],
    lazy: true,
    defaultLocale: 'sv',
    strategy: 'prefix_except_default',
    langDir: 'locales/'
  }

i18n.config.ts

export default defineI18nConfig(() => ({
    legacy: false,
  }))

**Comment by N-index** [comment]
> @sonsoixam try adding lazy: true to your nuxt.config i18n section and make sure you have a i18n.config.ts in your root.
> 
> Mine looks as: //nuxt.config i18n: { locales: [ { code: 'en', iso: 'en-US' , file: 'en.js'}, { code: 'sv', iso: 'sv-SE' , file: 'sv.js'}, { code: 'no', iso: 'nn-NO', file: 'no.js' }, // Add more locales as needed ], lazy: true, defaultLocale: 'sv', strategy: 'prefix_except_default', langDir: 'locales/' }
> 
> i18n.config.ts
> 
> export default defineI18nConfig(() => ({ legacy: false, }))

I solved the problem with this solution.

**Comment by sonsoixam** [comment]
thank everybody , i use this config and the problem is solved

i18n: {
        locales: [
            {
                code: 'vi',
                name: 'Tiếng Việt',
                file: 'vi-VN.json',
                src: 'vn.svg'
            },
            {
                code: 'en',
                name: 'English',
                file: 'en-US.json',
                src: 'us.svg'
            }
        ],
        lazy: false,
        langDir: 'locales',
        defaultLocale: 'vi'
    },
