### ISSUE TITLE
Provide option for trailing slash handling like in nuxt2, also to avoid double-redirects with nginx default settings

### ISSUE THREAD

**Issue by mschoeffmann** [nuxt/nuxt#22182]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.16.1`
- Nuxt Version:     `3.6.3`
- Nitro Version:    `2.5.2`
- Package Manager:  `pnpm@8.6.3`
- Builder:          `vite`
- User Config:      `devtools`, `ssr`
- Runtime Modules:  `-`
- Build Modules:    `-`

#### trailing-slash-redirect-test

https://stackblitz.com/edit/trailing-slash-redirect-test?file=README.md

- clone this repository to your local drive
- `pnpm install`
- `pnpm run generate`
- `docker run -v ./dist:/usr/share/nginx/html:ro -v ./nginx.conf:/etc/nginx/conf.d/default.conf:ro -p 3000:80 nginx:latest`
- navigate to `http:/localhost:3000/test` with chrome devtools > network tab open

### Describe the bug

In v2 it was possible, to always use a trailing slash for routes (https://v2.nuxt.com/docs/configuration-glossary/configuration-router#trailingslash).
In v3, it is only possible to tolerate (and redirect) or completely disallow a trailing slash (https://router.vuejs.org/api/interfaces/RouterOptions.html#Properties-strict).

The problem here is:
1. Opening `http://localhost:3000/test1`
2. Nginx redirects (HTTP 301) to `http://localhost:3000/test1/`
3. Nuxt loads the page, but replaces the history/location with `http://localhost:3000/test1` again
- If you refresh or open the link from a bookmark, the whole thing begins from top
- And some analytics tools count two page hits: `http://localhost:3000/test1/` and `http://localhost:3000/test1`

This can be fixed in nginx config - if you have access to it.
Otherwise every saved/bookmarked/refreshed HTTP request will result in a 2nd request after redirect and a nuxt/vue-internal redirect back to the URL without trailing slash.

In the screenshot you'll see:
1. Loads `http://localhost:3000/test1` 
2. URL field shows `http://localhost:3000/test1/` because of
3. redirect to `http://localhost:3000/test1/` 
4. URL field shows `http://localhost:3000/test1` because of internal nuxt redirect/replace

<img width="794" alt="Screenshot 2023-07-18 at 01 38 50" src="https://github.com/nuxt/nuxt/assets/9153512/35a76372-7187-4442-a791-5bcf03e5ed74">

**Comment by mrniamster** [comment]
Nuxt 2 was best <3

**Comment by danielroe** [comment]
The URL will only be without trailing slash if you have not created a link component with `defineNuxtLink` with the correct configuration: https://nuxt.com/docs/api/components/nuxt-link#definenuxtlink-signature (merged in https://github.com/nuxt/nuxt/pull/19458).

**Comment by rahulkumarsingh73690** [comment]
#22254 Same issue

**Comment by danielroe** [comment]
@mschoeffmann For that, you can use custom router.options to add configuration to vue router.

**Comment by GuillaumeDgr** [comment]
Hi, sorry to ask, but I'm facing the exact same issue and do not understand how to correct it with static website generation and using 'yarn generate', in loalhost all is ok but in prod, I have this 301 constant redirections from "/url" to "/url/" then "/url... Many thanks for your help or clarification !
