### ISSUE TITLE
Payload URLs are missing the configured `cdnURL` 

### ISSUE THREAD

**Issue by oliversalzburg** [nuxt/nuxt#22199]
### Environment

-

### Reproduction

-

### Describe the bug

You're not attaching the `cdnURL` to the paths you generate for "payloads": https://github.com/nuxt/nuxt/blob/4b6f3e1ba11ee247906a34ea76292bf3a171ed3b/packages/nuxt/src/core/runtime/nitro/renderer.ts#L243

### Additional context

Not sure why this setting should only apply to _some_ URLs and not others. If this is by design, feel free to close.

**Comment by oliversalzburg** [comment]
Just to give some context:

My task in this context was actually to deploy a Nuxt rendered output, as static pages, to S3-based simple website hosting. These pages were error pages, that should be presented at the requested URL if the request resulted in an error. When I served the pages at the given URL, they would always fall into a "404 state", because the current URL wasn't in the routing of the application.

The first I learned, was that another developer used a `ClientOnly` node in the pages, because they thought it would be the right solution for another problem they faced. It was not the right solution, as we were aiming for fully static pages.

Once I fixed that, I noticed that the entire JS usage dropped to pretty much zero, and that these payloads also didn't seem to contain any really meaningful data.

So I went with the following configuration bits:
```json
  experimental: {
    noScripts: true,
    payloadExtraction: false,
  },
```

The resulting pages were fully static HTML pages that I could serve from any origin or host. All other links in the document respected the `cdnURL` already through one mechanism or the other.

Sorry if any of the terminology is off. I'm in unknown territory here 😅

**Comment by danielroe** [comment]
Thoughts @pi0?

**Comment by danielroe** [comment]
I think we can implement once https://github.com/nuxt/nuxt/pull/21641 is merged.

**Comment by tresko** [comment]
@danielroe any news about implementation? I can help if you want :)
