### ISSUE TITLE
Rapidly Reloading Files Triggers HMR and Causes 500 Not Found Error

### ISSUE THREAD

**Issue by fp-sbn** [nuxt/nuxt#22195]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.10.0
- Nuxt Version:     3.6.3
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      devtools, ssr
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

1. Prepare files in directories such as `composables/` or `utils/` that are auto-imported, and create some variables in those files.
2. Call the variables from any screen (e.g., `app.vue`).
3. When quickly updating files, Hot Module Replacement (HMR) is triggered, and this may result in a 500 error.

#### Local Environment:

Save changes to the files without making any modifications, and sometimes, HMR runs twice, resulting in a 500 not defined error.

#### StackBlitz:

The issue is reproducible in the following StackBlitz example. However, it requires reloading the files 50 times at 50ms intervals (Note: the issue might occur at a lower frequency as well, but further testing is pending).
Please try `$ node update.js` at the following URL to reproduce the issue:
https://stackblitz.com/edit/github-whbp8g?file=composables%2FuseFoo.ts

<img width="849" alt="image" src="https://github.com/nuxt/nuxt/assets/82197450/f987e42e-9e3c-4d8f-a2aa-26313c52a993">

### Describe the bug

When files are quickly updated multiple times, it triggers Hot Module Replacement (HMR), leading to a 500 Not Found error.

In the provided simple project example, the bug seems to require multiple saves to reproduce. However, in moderately larger projects, the error can occur even with just two saves.

**Comment by danielroe** [comment]
cc: @antfu

**Comment by antfu** [comment]
Weirdly, I can't reproduce it in Stackblitz even I changed the update to 1000 times per 5ms
