### ISSUE TITLE
`dev` and `build` do not recognize declared types but `typecheck` does.

### ISSUE THREAD

**Issue by wvffle** [nuxt/nuxt#22209]
### Environment

```
------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.3
- Nitro Version:    2.5.2
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Reproduction

https://stackblitz.com/edit/github-fmsgrj?file=tsconfig.json,components%2FHello.vue,app.vue,package.json,types%2Ftest.d.ts

1. Run `npm run typecheck`
2. Run `npm run dev`

### Describe the bug

I've tried to create globally available types for my Nuxt app and I've failed after many attempts.

When you create a `types.d.ts` file with a type declaration it is available in the IDE and `nuxi typecheck` works like a charm not reporting any errors. However, when `nuxi dev` or `nuxi build` is run, it fails throwing `Unresolvable type reference or unsupported built-in utility type ` error.

```ts
// types.d.ts
declare interface MyProps {
  prop: string
}
```

### Logs

```shell-script
Nuxi 3.6.3                                                                                                                                                                                        12:58:56 AM
Nuxt 3.6.3 with Nitro 2.5.2                                                                                                                                                                       12:58:56 AM
                                                                                                                                                                                                  12:59:00 AM
  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.1.104:3000/


 ERROR  [@vue/compiler-sfc] Unresolvable type reference or unsupported built-in utility type                                                                                                      12:59:06 AM

/home/projects/github-fmsgrj/components/Hello.vue
1  |  <script setup lang="ts">
2  |  const props = defineProps<TestProps>();
   |                            ^^^^^^^^^
3  |  </script>
4  |  

ℹ Vite client warmed up in 1617ms                                                                                                                                                                 12:59:07 AM
✔ Nitro built in 867 ms  
```
```

**Comment by danielroe** [comment]
I believe the issue here is coming from Vue itself, which is looking to resolve these types in order to generate the props for them. This kind of usage may simply be unsupported.

Would you see if you can replicate/raise issue on https://github.com/vuejs/core ?

**Comment by wvffle** [comment]
@danielroe You're right, I could replicate the issue using Vue only. Thanks for the tip. 

I'm closing this issue as it is not related to Nuxt ;)
