### ISSUE TITLE
nuxt-link not working when is set dynamicly via Component element

### ISSUE THREAD

**Issue by dtoxvanilla1991** [nuxt/nuxt#22206]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.19.0`
- Nuxt Version:     `3.6.3`
- Nitro Version:    `2.5.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`, `i18n`, `devServer`, `formkit`, `tailwindcss`, `app`, `image`, `runtimeConfig`, `vite`, `devtools`, `experimental`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.8.0`, `@nuxtjs/i18n@8.0.0-beta.12`, `@formkit/nuxt@1.0.0-beta.9-f64c966`, `@nuxt/image-edge@1.0.0-28020728.5df24eb`, `nuxt-icon@0.4.2`
- Build Modules:    `-`

### Reproduction

Created baseButton dynamic component:
```
<template>
  <component
    class=""
    :class="{
      'flex gap-1.5 h-fit rounded px-3 py-2 justify-center items-center font-bebas text-slate-100 focus:outline-none':
        !to && !href,
      'opacity-50  pointer-events-none': disabled,
      'hover:opacity-90 cursor-pointer': !disabled,
      'bg-rb-dark-green': !to && !href && primary,
      'bg-amber-600': !to && !href && warning,
      'bg-red-600': !to && !href && error,
    }"
    :is="to ? 'nuxt-link' : href ? 'a' : 'button'"
    :to="to"
    :href="href"
    :disabled="disabled"
    :rel="href && 'noreferrer noopener'"
  >
    <slot name="prepend"></slot>
    <slot name="default"></slot>
    <slot name="append"></slot>
  </component>
</template>
<script setup lang="ts">
const props = defineProps({
  disabled: {
    type: Boolean,
    default: false,
  },
  to: {
    type: String,
    default: null,
  },
  href: {
    type: String,
    default: null,
  },
  variant: {
    validator(value: "primary" | "warning" | "error") {
      return ["primary", "warning", "error"].includes(value);
    },
    default: "primary",
  },
});

const primary = computed((): boolean => {
  return props.variant === "primary";
});
const warning = computed((): boolean => {
  return props.variant === "warning";
});
const error = computed((): boolean => {
  return props.variant === "error";
});
</script>
```

THEN tried to use it in on the page:
```
<div class="grid justify-center grid-cols-2 gap-10 mb-10">
      <ui-base-button
        style=""
        class="card flex items-center justify-center rounded-2xl backdrop-blur-2xl shadow-md h-32 md:h-60 border border-rb-dark-green/70 text-center font-bold text-3xl text-rb-dark-green"
        v-for="appeal in appeals"
        :to="`/campaign-admin/${appeal.slug}`"
      >
        <span class="!drop-shadow-glow" style="text-shadow: white 1px 0 10px">
          {{ appeal.title }}
        </span>
      </ui-base-button>
    </div>
```

### Describe the bug

I created a dynamic baseButton component using Component. Then tried using it on the page in the v-for loop with dynamic route and although in the DOM everything renders great, and it is indeed turning into nuxt-link, once clicked on any of the nuxt-links, they route nowhere. No url change, nothing.
If i simply change uiBaseButton directly to nuxt-link in the v-for loop, then everything works fine and routes.

### Additional context

![image](https://github.com/nuxt/nuxt/assets/73205087/b4b416f4-b021-4808-8c99-061705e9307a)

https://github.com/nuxt/nuxt/assets/73205087/61c49d59-e7f0-4978-bddf-c494d9b0200c

### Logs

```shell-script
No error logs in the console.
```

**Comment by huang-julien** [comment]
Hi you need to resolve it to use it with `Component`
-> `const NuxtLinkl = resolveComponent('NuxtLink')`
see: https://nuxt.com/docs/guide/directory-structure/components#dynamic-components
