### ISSUE TITLE
Strange behaviour with inline style

### ISSUE THREAD

**Issue by Julien-Martin** [nuxt/nuxt#22215]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.3
- Nitro Version:    2.5.2
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      experimental, components
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-ngduht?file=nuxt.config.ts

### Describe the bug

I have a strange behaviour on my project, I was able to reproduce it in a lighter environment.

Some components style are inline by the server, while others are not.

I can't figure out why :man_shrugging: 

When my component is not in lazy (TopBanner) i don't get style on the server 
![image](https://github.com/nuxt/nuxt/assets/23340944/f029830a-72f2-45de-b22c-d34cab5616b3)

When i add `Lazy` prefix, my component is rendered as expected, but on my larger project `Lazy` prefix doesn't change anything. And act like a css flickering...

How Vite/Nitro decide which style is inline ? :thinking:

**Comment by danielroe** [comment]
This is now resolved.
