### ISSUE TITLE
Limit max number of parallel requests for `useFetch`

### ISSUE THREAD

**Issue by ennioVisco** [nuxt/nuxt#22212]
### Describe the feature

There are cases where a server only accepts some amount of parallel requests, which can be problematic to handle when doing lazy fetching. 

I think it would be reasonable to provide a feature to programmatically limit the number of fetches for same baseURL, and just wait when that max has been reached.

Does this make any sense to others?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by Mini-ghost** [comment]
Hi!
I have tried creating a Nuxt module, nuxt-parallel-limit, to implement this feature. It's quite basic at the moment, but you can give it a try.

GitHub: https://github.com/Mini-ghost/nuxt-parallel-limit
Stackblitz: https://stackblitz.com/edit/nuxt-parallel-limit?file=app.vue

**Comment by ennioVisco** [comment]
I will close the issue since the module from @Mini-ghost works pretty well. In case anyone needs this feature, I strongly recommend it :)
