### ISSUE TITLE
navigateTo in middleware make refreshing asyncData do nothing 

### ISSUE THREAD

**Issue by wangbinyq** [nuxt/nuxt#22210]
### Environment

- Operating System: Darwin
- Node Version:     v20.4.0
- Nuxt Version:     3.6.3
- Nitro Version:    2.5.2
- Package Manager:  unknown
- Builder:          vite
- User Config:      ssr, devtools, modules, build, vite
- Runtime Modules:  @unocss/nuxt@0.53.5, @vueuse/nuxt@10.2.1
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-uxtv24?file=middleware%2Froute.global.ts

### Describe the bug

1. Load page with '/' route
2. middleware redirect to '/login'
3. login to '/' page
4. refresh asycData not working.
5. if first load page with '/ogin', everything works.

**Comment by danielroe** [comment]
This should be resolved in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/), or in the next release.

Let me know if not and I'll reopen.
