### ISSUE TITLE
DefinePageMeta is not accessible without autoimport.

### ISSUE THREAD

**Issue by mercs600** [nuxt/nuxt#22219]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.3
- Nitro Version:    2.5.2
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-gudkgu?file=.nuxtrc

### Describe the bug

There is no possibility of ussing `definePageMeta` without autoimport. 

Editor recommends using `import { definePageMeta } from 'nuxt/dist/pages/runtime` but then I got error: 

```bash
[plugin:vite:import-analysis] Missing "./dist/pages/runtime" specifier in "nuxt" package
/home/projects/github-gudkgu/pages/index.vue
```

It would be nice to also use it in modules, as that is my original issue

### Logs

```shell-script
[plugin:vite:import-analysis] Missing "./dist/pages/runtime" specifier in "nuxt" package
/home/projects/github-gudkgu/pages/index.vue
```

**Comment by warflash** [comment]
You should be able to import it from `#imports`
https://stackblitz.com/edit/github-gudkgu-sxnspa?file=app.vue,pages%2Findex.vue

**Comment by danielroe** [comment]
This is a compiler macro and doesn't work via auto-import. But without the auto import you aren't getting the _typings_ for it. You can likely get them by importing specifically from `#imports`.
