### ISSUE TITLE
Project building with page dirrectory routing(nuxt native) and building with nuxt/router(library)

### ISSUE THREAD

**Issue by vorobiov-novait** [nuxt/nuxt#22218]
### Environment

Environment
Nuxt v2.15.8
Node v18.16.0
ssr: false

### Reproduction

Founded a problem. During project development used a nuxt/router(library) for routing in app. Now get a need to moove routing to page dirrectory routing(nuxt native).

### Describe the bug

As a result, founded that in page dirrectory routing(nuxt native): 
- page loading and amount of loaded components(files) rised up; 
- the networking loading size rised twice;
- page navigation provides with reuploading components

Has anybody met such problems in transition from nuxt/router(library) -> page dirrectory routing(nuxt native)

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
