### ISSUE TITLE
nuxt generate the symlink dist is neccessary?

### ISSUE THREAD

**Issue by xjccc** [nuxt/nuxt#22235]
### Environment

- Operating System: Darwin
- Node Version:     v16.18.0
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.6.3
- Builder:          vite
- User Config:      typescript, app, nitro, experimental, sourcemap, build, runtimeConfig, css, vite, ignore, hooks, modules, errorCacheConfig
- Runtime Modules:  nuxt-error-and-cache@1.0.9, nuxt-custom-fetch@1.0.7, @vueuse/nuxt@10.2.1, @pinia/nuxt@0.4.11
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-pghlwa?file=nuxt.config.ts

### Describe the bug

in my nuxt.config 
`
nitro: {
  output: {
    dir: '~/node-server',
    publicDir: '~/node-server'
  }
}
`
after generate, there has two dirs, `node-server` and `dist`, the `dist` is not neccessary for me.
it has some reason to generate it or can generate one of these
![dist-dir](https://github.com/nuxt/nuxt/assets/16478776/0ff0911e-8712-4b97-bf4f-472b4df48bb5)
![node-server-dir](https://github.com/nuxt/nuxt/assets/16478776/d6782c11-0525-4b2e-9813-6bae73249b31)

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/14361
