### ISSUE TITLE
Cannot import file in .nuxt folder from nitro plugin in dev environment

### ISSUE THREAD

**Issue by kehwar** [nuxt/nuxt#22232]
### Environment

````
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
````

### Reproduction

https://stackblitz.com/edit/github-epxvsq?file=modules%2Fcustom.ts,server%2Fplugins%2Fcustom.ts

### Describe the bug

I'm generating some files on the .nuxt folder at build time

When trying to import the file from a server plugin it throws an error on the dev environment

`ERROR  [worker reload] [worker init] Cannot find module ...`

However, if I generate the file elsewhere, like a temp folder, it works fine

The error only happens on dev environment, the build runs

**Comment by danielroe** [comment]
I suspect this is because when your nitro server initialises and runs the plugin, the file in `.nuxt` is not yet present.

I don't think this is a bug, but rather a race condition/lifecycle issue between your nuxt + nitro builds - and would advise against writing files to disk in `.nuxt` if you need them within nitro plugins.

**Comment by kehwar** [comment]
> I suspect this is because when your nitro server initialises and runs the plugin, the file in `.nuxt` is not yet present.

The file is created before nitro initializes

> I don't think this is a bug, but rather a race condition/lifecycle issue between your nuxt + nitro builds

The file is already present when nitro initializes, also, the module/plugin works in production (build + preview), it only fails on dev

It also works if the file is created anywhere else on the project

> and would advise against writing files to disk in `.nuxt` if you need them within nitro plugins.

I tried following this: https://nuxt.com/docs/guide/going-further/modules#adding-templatesvirtual-files

But it throws `Vue app aliases are not allowed in server routes`

---

My use case is the following: 

I have several *.task.ts files, they all export a default TaskDefinition object which define an scheduled task to run

I can import each file manually inside a nitro plugin to start each task on my server

I thought I could write a module to auto-generate my TaskDefinition array an import it, but I ran into this issue

I have a similar approach for *.menu.ts files to build my Menus, it also writes a file to .nuxt and is imported by nuxt (clientside) without any problem

So far, I have only found this issue inside a nitro plugin

**Comment by danielroe** [comment]
For virtual files used within nitro, you can use `nitroConfig.virtual`.

**Comment by kehwar** [comment]
> For virtual files used within nitro, you can use `nitroConfig.virtual`.

This works!

The module author guide doesn't mention this, so I searched and followed this implementation: 
https://github.com/nuxt/content/blob/main/src/module.ts

I will try to make a PR to add this use case to the documentation
