### ISSUE TITLE
Discover that routeRules' proxy has a caching mechanism that prevents sending files larger than 10kb. Didn't you encounter this problem while developing?

### ISSUE THREAD

**Issue by taishuai110** [nuxt/nuxt#22238]
### Environment

nuxt 3.6.2
nitro 2.5.2
node 18.16.0

### Reproduction

https://github.com/taishuai110/nuxt3-error/tree/master

### Describe the bug

Do you analyze the proxy interface routeRules in nuxt3's nuxt.config.ts file? Discover that routeRules' proxy has a caching mechanism that prevents sending files larger than 10kb. Didn't you encounter this problem while developing?

**Comment by danielroe** [comment]
This is good debugging, but please do not open duplicate issues. Just add a comment in your original issue and/or update the title.

https://github.com/nuxt/nuxt/issues/21936
