### ISSUE TITLE
Nuxi generate crash using netlify preset

### ISSUE THREAD

**Issue by rcluis** [nuxt/nuxt#22236]
### Environment

- Operating System: Darwin
- Node Version:     v16.17.0
- Nuxt Version:     3.6.3
- Nitro Version:    2.5.2
- Package Manager:  npm@9.2.0
- Builder:          vite
- User Config:      app, nitro, css, build, vite, postcss, sitemap, modules, runtimeConfig, delayHydration, sourcemap
- Runtime Modules:  nuxt-delay-hydration@1.2.1, nuxt-simple-sitemap@1.0.11, (), @nuxt/content@2.7.0
- Build Modules:    -

### Reproduction

- Update to last version of nuxt > `3.6.0`
- Set the nitro preset to netlify
- run `nuxi generate`

### Describe the bug

I have my site deploy to Netlify. Until now I was using the command `nuxi generate` in order to build the site and deploy to Netlify using the automatic configuration of the nitro preset `netlify`. After updating to the last version of Nuxt `3.6.3` in that moment, I was getting the following error running the command `nuxi generate`:
 
`ENOENT: no such file or directory, open '/Users/.../Documents/Projects/.../.netlify/functions-internal/server/server.json' `

Before nuxt `3.6.0` was working perfectly

### Logs

```shell-script
> generate
> nuxi generate

Nuxi 3.6.3                                                                                                                                                          9:07:15 AM
Nuxt 3.6.3 with Nitro 2.5.2                                                                                                                                         9:07:15 AM

....

 ERROR  ENOENT: no such file or directory, open '/Users/.../Documents/Projects/.../.netlify/functions-internal/server/server.json'                  9:07:40 AM
```

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by rcluis** [comment]
hey @danielroe, creating the reproduction I saw that the preset `netlify-static` was available, and after changing `netlify` to `netlify-static` the `nuxi generate` is working properly. You may want to add this into the docs, as it is just specify to use the preset `netlify` there. Closing the issue though, thanks!

**Comment by danielroe** [comment]
Netlify static should be auto detected if you are running generate in a Netlify environment. Was that not working?

**Comment by rcluis** [comment]
Exactly @danielroe , with a clean installation of nuxt, and the preset `netlify`, the generate is not working

**Comment by danielroe** [comment]
You should not set `netlify` as the preset explicitly if you are running generate. Either do not set it, and it will be correctly detected, or you can set `netlify-static`.

**Comment by rcluis** [comment]
ok, got it! Could it be specified in the documentation, I did not see the generate part. Anyway, thank you so much!

**Comment by mklueh** [comment]
Ran into the same issue out of nowhere. 

I'm deploying via GitHub Actions and not via Netlify's CI, so auto-detecting the environment is out of the question.

This should really be part of the documentation.

**Comment by m-shum** [comment]
Running into this issue without a nitro preset set explicitly. `generate` runs fine locally but returns `no such file or directory, open '/opt/build/repo/.netlify/functions-internal/server/server.json'` when building in netlify.

**Comment by c4mbr0nn3** [comment]
> Running into this issue without a nitro preset set explicitly. `generate` runs fine locally but returns `no such file or directory, open '/opt/build/repo/.netlify/functions-internal/server/server.json'` when building in netlify.

Same error here starting from nuxt 3.14. 

You need to explicitly set the `netlify-static` in your `nuxt.config.ts` as written in the [documentation](https://nuxt.com/docs/getting-started/deployment#presets) 

```js
export default defineNuxtConfig({
  nitro: {
    preset: 'netlify-static'
  }
})
```
After doing this the build phase should complete.
