### ISSUE TITLE
H3error at Module.createError when fetching data using useAsyncData

### ISSUE THREAD

**Issue by lucasboh** [nuxt/nuxt#22249]
### Environment

-----------------------------
- Operating System: Linux
- Node Version:     v18.16.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      app, vite, runtimeConfig, css, modules, strapi, i18n, image
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.13, @nuxtjs/strapi@1.9.3, @nuxt/image-edge@1.0.0-rc.1-28164235.9cba5d4
- Build Modules:    -
------------------------------

### Reproduction

(---)

### Describe the bug

I have a Nuxt project which fetches data from a Strapi CMS also running locally. The following code is an example of how I am fetching data for a page:

```
const graphql = useStrapiGraphQL()
const { locale } = useI18n()
const pageData = ref<SecurityPage>()

const { data, error } = await useAsyncData<{data: {security: {data: {attributes: SecurityPage}}}}>(
            `security-content`,
            () => graphql(GET_SECURITY_PAGE(locale.value)),
)

if (data.value) {
  pageData.value = data.value.data.security.data.attributes

  console.log(pageData.value)
}

if (error.value) {
  console.log('error.value', error.value)
}
```

The problem is, that the first load does not work, and I get the following error logged in the console from the `console.log` inside the `if (error.value)`:

```
error.value Error
    at createError (index.mjs?v=e3328e0b:127:15)
    at createError (error.js?v=e3328e0b:31:16)
    at NuxtError (revive-payload.client.js?v=e3328e0b:8:24)
    at hydrate (parse.js?v=e3328e0b:60:32)
    at hydrate (parse.js?v=e3328e0b:125:19)
    at hydrate (parse.js?v=e3328e0b:125:19)
    at hydrate (parse.js?v=e3328e0b:60:40)
    at unflatten (parse.js?v=e3328e0b:132:9)
    at parse (parse.js?v=e3328e0b:16:9)
    at parsePayload (payload.js:86:10)
```

If I navigate to another page, and then come back to this page, then the data is fetched normally and everything works. But when I reload the page, it crashes again. Sadly, it is difficult to debug with this error information, which is actually an error in the error creation (?).

Thank you for your help!

### Additional context

---

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by lucasboh** [comment]
Hi @danielroe, 
I have created this reproduction (https://github.com/lucasboh/static-nuxt-test) of the project a while ago, because of other issue I had (see [https://github.com/nuxt/nuxt/issues/12377](https://github.com/nuxt/nuxt/issues/12377)), but the problem is not occurring in that case. The difference between the reproduction and the actual project is that in the actual project I am using docker to run Nuxt and the Strapi CMS, and in the reproduction I am fetching the data from the production CMS.

What I have just discovered is that using `try catch` instead of `useAsyncData()` solves the issue:

```
const pageData = ref<SecurityPage>()
const graphql = useStrapiGraphQL()
const { locale } = useI18n()

try {
  const data = await graphql(GET_SECURITY_PAGE(locale.value))

  if (data) {
    pageData.value = data.data.security.data.attributes
  }
}
catch (error) {
  console.log('catch', error)
}
```

But I need to use `useAsyncData()` in order for the static pages to be generated (see: [https://github.com/nuxt/nuxt/issues/12377](https://github.com/nuxt/nuxt/issues/12377)).

Furthermore, when I fetch the data from the production CMS in the actual project, instead of the local Strapi, the issue disappears as well. So it may have to do with using docker?

**Comment by danielroe** [comment]
Perhaps there is a network issue preventing the fetching of data from the server-side within your docker container? Maybe 'localhost' within the docker container doesn't point to your strapi server, for example?

**Comment by danielroe** [comment]
This probably does not happen on client side because the request goes from the browser to the strapi server and won't have the same network issue (if indeed that is the case).

**Comment by lucasboh** [comment]
The problem was indeed using localhost to reach strapi. When using the service name and port (`http://strapi:1337`) the problem was resolved.

Thank you very much for the help!

**Comment by patriciorivera** [comment]
I faced the exactly same problem in my local environment (no docker). What worked for me was overriding localhost by 127.0.0.1 in nuxtStrapi plugin options.

nuxt.config.js|ts

```
export default {
  modules: ['@nuxtjs/strapi'],
  strapi: {
    url: process.env.STRAPI_URL || 'http://localhost:1337',  <-----
    prefix: '/api',
    version: 'v4',
    cookie: {},
    cookieName: 'strapi_jwt'
  }
}
```
