### ISSUE TITLE
Nuxt Layer cannot build when using public folder

### ISSUE THREAD

**Issue by Julien-Martin** [nuxt/nuxt#22242]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      extends
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

`npm run build`

https://stackblitz.com/edit/github-xpbysw?file=nuxt.config.ts

### Describe the bug

Cannot build when using file from `public/` folder in component 

```
<img src="/Placeholder.png" />
```

![image](https://github.com/nuxt/nuxt/assets/23340944/745d88d2-c0fd-4329-9d46-db7befcbb49f)

Work well in dev mode, but not in build :(

**Comment by danielroe** [comment]
linked: https://github.com/nuxt/nuxt/issues/22107

**Comment by Julien-Martin** [comment]
linked: https://github.com/nuxt/nuxt/issues/18920

**Comment by danielroe** [comment]
This was resolved in https://github.com/nuxt/nuxt/pull/26163.
