### ISSUE TITLE
Support `async` function for the `prerender:routes` hook.

### ISSUE THREAD

**Issue by rudolfbyker** [nuxt/nuxt#22245]
### Describe the feature

When I define an asynchronous `prerender:routes` hook in `nuxt.config.ts`, it is not awaited. Depending on context, sometimes this is a problem, and sometimes not (i.e. a race condition). It would be nice to be able to perform asynchronous things e.g. querying a database to determine the appropriate routes for prerendering.

Reproduction:
- See https://stackblitz.com/edit/github-9ksyyc?file=pages%2Findex.vue
- Run `nuxt build`
- Observe the wrong order of operations:
```
✔ Server built in 1200ms                                                                                          14:12:47
✔ Generated public .output/public                                                                           nitro 14:12:47
Our prerender:routes hook has started                                                                             14:12:47
ℹ Building Nitro Server (preset: node-server)                                                               nitro 14:12:47
Our prerender:routes hook has finished
✔ Nitro server built                                                                                        nitro 14:12:53
```

The `prerender:routes` hook is called here:

https://github.com/unjs/nitro/blob/14670c94d8f11f24525295f55ed427ac616fc643/src/prerender.ts#L40

and it looks like it is being awaited, but we are missing the return or await keyword here:

https://github.com/nuxt/nuxt/blob/4b13dadaa2185cdf842c7718ffb4188fce798ef8/packages/nuxt/src/core/nitro.ts#L294

I will make a simple PR :)

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Nice find.

**Comment by rudolfbyker** [comment]
This feels like a new feature, or an enhancement of an existing feature, but seeing how simple the fix was, and that the docs have examples of asynchronous hooks without stating whether some or all hooks support async, I marked this as a bug fix.

**Comment by danielroe** [comment]
I would also consider it a bug fix 👍
