### ISSUE TITLE
Running logic post prerender

### ISSUE THREAD

**Issue by harlan-zw** [nuxt/nuxt#22255]
### Describe the feature

Context: https://github.com/nuxt/nuxt/pull/22251#issuecomment-1644173409

Currently, it's possible to emit assets after prerendering is finished. This is being used in a couple of my modules to emit files that are generated from data only discovered through the prerendering step.

For example, when using `nuxt generate`:
- [Nuxt Simple Sitemap](https://github.com/harlan-zw/nuxt-simple-sitemap/blob/main/src/prerender.ts) - Uses discovered crawled links as sitemap entries before emitting the `sitemap.xml`
- [Nuxt OG Image](https://github.com/harlan-zw/nuxt-og-image/blob/main/src/module.ts#L599) - All screenshots are generated in one batch post-prerender
- Nuxt Link Checker - Not currently implemented but adding a HTML report output would be useful.

This logic occurs within the build-time context, meaning code is being shared between the build-time and runtime. This has some issues:
- Inconsistent behavior and APIs
- Verbose APIs to pass in context-specific data

Not sure about an exact solution, but we do have some advantages in keeping it within the build-time:
- Full access to Node APIs and Nuxt
- Can easily avoid bundling deps into the runtime

Ideally, we'd have the ability to run it in an isolated Nitro context (dependencies within this code wouldn't be bundled).

> what about a utility that can run + require code 'within' a nuxt context? Or code registered in a nitro (runtime) plugin that runs after a build is complete. I think storage/bundled storage solves some of this but maybe worth brainstorming some ideas

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by pi0** [comment]
Thanks for opening up this discussion @harlan-zw ❤️ 

As a general design note, Nuxt 3 / Nitro is explicitly made to split runtime (dev, prerender, production) logic from build time context (modules). This can never change and this is actually why we could make Nuxt 3 builds efficient small and portable.

I fully agree btw. Also, from time to time felt the limitation of having a way to communicate from Module to the Dev|Prerender namespace. I think we could benefit from an API that gives function calling ability (with structured clone) between build-time (module context) and runtime (dev + prerender runtime context). Today, only `useStorage()` is available as a sharable context.

There are more internal reasons to even do this. Memory caching will be lost across dev reloads and storage watcher and db connections get restarted which is not best DX.

The reason for using a structured clone is that, right now dev server runs in thread workers but also prerender code actually is [running in the main Node.js context](https://github.com/unjs/nitro/blob/main/src/prerender.ts#L73C1-L73C1) but we might change it to leverage multi-threading and more isolation (https://github.com/unjs/nitro/issues/1447).

**Comment by Hebilicious** [comment]
Possibly related : https://github.com/nuxt/nuxt/issues/21855

**Comment by harlan-zw** [comment]
work around: https://github.com/nuxt/sitemap/blob/main/src/prerender.ts#L85

**Comment by pi0** [comment]
If the main requirement is to prerender more routes after, maybe we can pass `prerenderRoute` directly to the hook? I am up to also introduce a new hook like `prerender:extend` btw for more clearly purposed hook. Feel free to make issue or PR directly in upstream 👍🏼

**Comment by pi0** [comment]
Discussing with team and thanks for brainstorming with @danielroe we might introduce a new mount point to allow directly emit assets in runtime to address this issue. Let's track in upstream https://github.com/unjs/nitro/issues/2099
