### ISSUE TITLE
Deploys to netlify break after upgrading to 3.6.x

### ISSUE THREAD

**Issue by luis-agm** [nuxt/nuxt#22257]
### Environment

- Operating System: Linux
- Node Version:     v18.16.1
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@9.5.1
- Builder:          vite
- User Config:      components, modules, colorMode, googleFonts, build, typescript, vite
- Runtime Modules:  @nuxt/content@2.7.1, @nuxtjs/tailwindcss@6.8.0, @nuxtjs/google-fonts@3.0.1, @nuxt/image-edge@1.0.0-rc.1-28164352.ad7c010, @pinia/nuxt@0.4.11, @nuxtjs/color-mode@3.3.0
- Build Modules:    -

### Reproduction

[Repo with cleaned up branch](https://gitlab.com/luis-agm/nuxt-issue-reprod/-/tree/cleanup)

Branch `cleanup` is as far as I could make it while still reproducing the issue.

### Describe the bug

When upgrading from Nuxt 3.5.3 to Nuxt 3.6.5 (also tested with 3.6.3 before), netlify deploys break,showing an error message.

```
9:47:02 PM: Functions bundling                                            
9:47:02 PM: ────────────────────────────────────────────────────────────────
9:47:02 PM: ​
9:47:02 PM: Packaging Functions from .netlify/functions-internal directory:
9:47:02 PM:  - server/server.mjs
9:47:02 PM: ​
9:47:02 PM: Packaging Functions from functions/api directory:
9:47:02 PM:  - login.ts
9:47:02 PM:  - verifylogin.ts
9:47:02 PM: ​
9:47:21 PM: <--- Last few GCs --->
9:47:21 PM: [4031:0x6145730]    42000 ms: Scavenge 2025.0 (2059.0) -> 2025.0 (2064.2) MB, 4.3 / 0.0 ms  (average mu = 0.149, current mu = 0.144) allocation failure;
9:47:21 PM: [4031:0x6145730]    42006 ms: Scavenge 2027.8 (2064.2) -> 2028.0 (2065.5) MB, 4.3 / 0.0 ms  (average mu = 0.149, current mu = 0.144) allocation failure;
9:47:21 PM: [4031:0x6145730]    42012 ms: Scavenge 2028.8 (2065.5) -> 2028.5 (2076.5) MB, 5.1 / 0.0 ms  (average mu = 0.149, current mu = 0.144) allocation failure;
9:47:21 PM: <--- JS stacktrace --->
9:47:21 PM: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
9:47:21 PM:  1: 0xb83f50 node::Abort() [/opt/buildhome/node-deps/node]
9:47:21 PM:  2: 0xa94834  [/opt/buildhome/node-deps/node]
9:47:21 PM:  3: 0xd647c0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/opt/buildhome/node-deps/node]
9:47:21 PM:  4: 0xd64b67 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/opt/buildhome/node-deps/node]
9:47:21 PM:  5: 0xf42265  [/opt/buildhome/node-deps/node]
9:47:21 PM:  6: 0xf43168 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/opt/buildhome/node-deps/node]
9:47:21 PM:  7: 0xf53673  [/opt/buildhome/node-deps/node]
9:47:21 PM:  8: 0xf544e8 
...
```

**Comment by AnthonyRuelle** [comment]
Same problem here with 3.6.4 and 3.6.5 :(

**Comment by jackian30** [comment]
I'm not quite sure if this Nuxt's (3.6.5) issue or Netlify's but it's also happening to me

**Comment by Nemure231** [comment]
same here, in nuxt 3.6.5. Even downgrading nuxt not fixing it.

**Comment by luis-agm** [comment]
@Nemure231 I suggest you do a cleanup when downgrading, e.g remove node_modules and package-lock.json and then do `npm install`.

**Comment by Nemure231** [comment]
nevermind i solved this, removed unmaintained library that been sticking to my project, and its cleared the issue. Totally not nust issue.

**Comment by luis-agm** [comment]
@Nemure231  Would you mind sharing which library caused the issue for you? Might help others.

**Comment by Nemure231** [comment]
Actually its not really unmaintained... i just too upset because this issue keep show like 2 days, lol, i hope the author not in here 😂

Its a vite plugin. https://github.com/vite-plugin/vite-plugin-dynamic-import. Maybe that plugin doesnt updated with current vite version or something, so its cause issue on my side.

Anyway i still got that error, and realize i have it in client build, and also nitro build. Client problem is done, but still got in nitro build, still looking at what plugin/library cause this again. 🙁

**Comment by jackian30** [comment]
> I'm not quite sure if this Nuxt's (3.6.5) issue or Netlify's but it's also happening to me

Hi, just an update. After a lot of trial and error, I traced the issue on my repo and the culprit is the `@fortawesome/fontawesome-free/css/all.css` that I'm importing to css on my `nuxt.config.ts`.

**Comment by Ryan-santos** [comment]
Hi, I was having the same issue in my project. But after many tests, I discovered that the **google-fonts** module was causing the error. When I set `googleFonts { download: false }` in `nuxt.config`, it resolved the issue for me.

How I found the solution briefly: I accessed `.netlify\functions-internal\server\chunks\app_nuxt\entry-styles.mjs`, deleted the value of the variable **nuxtGoogleFonts**, tried to deploy again, and everything worked fine.

_Translated from Portuguese (Brazilian) by ChatGPT._

**Comment by DanielHefti** [comment]
I had a similar problem. I was able to trace the problem back to some kind of incompatibility between normalize.css and the experimental inlineSSRStyles feature. 

My solution is to either remove normalize.css or disable the inlineSSRStyles feature. 

`
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  css: ['normalize.css/normalize.css','@/assets/styles/app.scss'],
  devtools: { enabled: true },
  experimental: {
    inlineSSRStyles: false
  }
})
`

**Comment by zpzyyzp** [comment]
same problem and I had to deploy my app to vercel...

**Comment by bradsiefert** [comment]
I'm having this same issue, but I'm not using Google Fonts, just local @fontfaces. My site is extremely simple, literally no other devDependencies. The only thing that worked for me was downgrading to v3.5.3.

**Comment by luis-agm** [comment]
Still happening with 3.7.1

**Comment by luis-agm** [comment]
> I had a similar problem. I was able to trace the problem back to some kind of incompatibility between normalize.css and the experimental inlineSSRStyles feature.
> 
> My solution is to either remove normalize.css or disable the inlineSSRStyles feature.
> 
> `// https://nuxt.com/docs/api/configuration/nuxt-config export default defineNuxtConfig({ css: ['normalize.css/normalize.css','@/assets/styles/app.scss'], devtools: { enabled: true }, experimental: { inlineSSRStyles: false } })`

So far the `inlineSSRStyles` mentioned by @DanielHefti worked for me in one of my sites when upgrading from 3.5.3 to 3.7.1. This is unideal, but it seems to work. I'll be testing the other sites today.

**Comment by rafalves** [comment]
This seems to be Netlify problem, Vercel and my personal server works well.

**Comment by adydetra** [comment]
Use Vercel for a while

**Comment by danielroe** [comment]
This seems to be a Netlify bug that is being fixed. Here's a workaround: https://answers.netlify.com/t/javascript-heap-out-of-memory-when-trying-to-build-a-nuxt-app/93138/14
