### ISSUE TITLE
Separate the prerendering step from the build step

### ISSUE THREAD

**Issue by rudolfbyker** [nuxt/nuxt#22261]
### Describe the feature

Currently, the only place where prerendering is started is here:
https://github.com/nuxt/nuxt/blob/9742bffac24fbf9fa279d614ad6bf07b5d85672d/packages/nuxt/src/core/nitro.ts#L380C29-L380C29

It is therefore not possible to do prerendering from the CLI without also running the build. It would be a great help to my workflow if I could do the build on one server, copy the files, and do the prerendering on another server.

There are many use cases for this:
- Retrying the prerendering step without retrying the build step.
- App code did not change, but the routes returned by the `prerender:routes` have changed, and you only want to update the prerendered pages without updating the build and/or without updating previously prerendered routes.
- Splitting build and prerender steps into different CI steps (e.g. Bitbucket Pipelines, where each step is run sequentially in a separate docker container).
- Splitting up large prerender tasks with thousands of routes into independent steps (e.g. copy the build to separate physical machines, run pre-rendering with a different set of routes on each (the `prerender:routes` hook can figure this out based on environment variables) and merge the results afterwards for deployment).
- Workflows where one person is responsible for building, and another for prerendering.

What I would like to see:
- Clear API and CLI to run `build` and `prerender` separately or together.
- `prerender` will obviously fail if results of `build` is missing.
- `build` may throw away results of previous prerendering, but `prerender` should not touch results of previous build.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
This is indeed planned!

Let's track in https://github.com/nuxt/nuxt/issues/14918.

**Comment by rudolfbyker** [comment]
I'm not sure that I fully understand how these issues relate, but I will follow them to see what happens :) Thanks for the great work.
