### ISSUE TITLE
Missmatch nuxt version when package-lock is missing

### ISSUE THREAD

**Issue by WailanTirajoh** [nuxt/nuxt#22266]
### Environment

Nuxt project info:                  

Before package-lock removed:
------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.3.3`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@8.19.2`
- Builder:          vite
- User Config:      postcss, css
- Runtime Modules:  `-`    
- Build Modules:    `-`
------------------------------                                   

After package-lock removed:
------------------------------
- Operating System: Windows_NT
- Node Version:     v18.12.1
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@8.19.2
- Builder:          vite
- User Config:      postcss, css
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-1zpfce?file=package.json

Step to check:
1. delete package-lock
2. npm install
3. npx nuxi info
4. check the version on nuxi info with the defined nuxt version on package.json

### Describe the bug

Missmatch specified of nuxt on Package.json when package-lock is removed / missing.

Detail:
1. Project was built using nuxt 3.3.3, with nuxi 3.3.3 if we check using npx nuxi info. 
2. For some reason, the package-lock is removed / missing, and we try to run npm install 2 months latter and then installed nuxt & nuxi is the newer version.
3. when we run npx nuxi info, seems like it doesnt go with the defined nuxt version on package.json (devDependency).

**Comment by WailanTirajoh** [comment]
As a short-term solution, I located the package-lock in the commit history and selected it. However, for a more sustainable approach, it would be beneficial to adhere to the specifications defined in the package.json file.

**Comment by danielroe** [comment]
This is how your package manager works. With the `^` constraint and without a lockfile, it will select the most recent 3.x version. You can use `~` to pin to a minor, or just omit entirely to pin to a patch.
