### ISSUE TITLE
Allowing more than a single fetch in useAsyncData

### ISSUE THREAD

**Issue by devops3199** [nuxt/nuxt#22263]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v16.19.0
- Nuxt Version:     3.5.0
- Nitro Version:    2.4.1
- Package Manager:  yarn@3.5.0
- Builder:          vite
- User Config:      app, css, ssr, modules, htmlValidator, runtimeConfig, alias, build, vite
- Runtime Modules:  @vueuse/nuxt@10.2.1, @pinia/nuxt@^0.4.10, @nuxtjs/html-validator@^1.2.4, nuxt-swiper@^1.1.0
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/devops3199/nuxt3-issue-example

### Describe the bug

The issue occurs during SSR.

I'm trying to fetch second data based on a value from the first fetched data. From the below scenario, only the first fetch triggers then render html.

```
// src/app.vue

<template>
  code...
</template>
<script setup>
const {data} = await useAsyncData('items', async () => {
   let details;
   const {data} = await $fetch(...);
   
   if (data.isCondition) {
       // although isCondition value is true, does not trigger
      details = await $fetch(...);
   }
   
   return {data, details};
})
</script>
```

I can use `Promise.all` to solve this issue, but I am not sure whether this is the expected behaviour from `useAsyncData`.

**Comment by Julien-Martin** [comment]
@devops3199 The first second `$fetch` should be trigger if `data.isCondition` is `true`, in your test this value is equal to `true` ?

**Comment by danielroe** [comment]
This should work fine. Try checking the error value, and doing some logging within the function to reveal the issue

**Comment by devops3199** [comment]
Hi guys, I just reproduced the issue. Here is the link. https://github.com/devops3199/nuxt3-issue-example

```
/* ~/service/news.ts */
export const fetchNews = async () => {
  const cookie = useRequestHeaders(["cookie"]);
  return await $fetch<{ title: string }[]>(
    "https://api.hnpwa.com/v0/news/1.json",
    {
      headers: { ...cookie },
    }
  );
};

/* ~/service/jobs.ts */
export const fetchJobs = async () => {
  const cookie = useRequestHeaders(["cookie"]);
  return await $fetch<{ title: string }[]>(
    "https://api.hnpwa.com/v0/jobs/1.json",
    {
      headers: { ...cookie },
    }
  );
};

/* app.vue */
<script setup lang="ts">
import { fetchNews } from "~/service/news";
import { fetchJobs } from "~/service/jobs";

const { data, error } = await useAsyncData("init", async () => {
  let jobs: any = [];

  // Error ❌
  const news = await fetchNews();

  if (news.length > 0) {
    jobs = await fetchJobs();
  }

  /* Case 1 - Working 👍 */
  // const [news, jobs] = await Promise.all([fetchNews(), fetchJobs()]);
  
   /* Case 2 - Working 👍 but I need to pass cookies when ssr */
  // const news = await $fetch<any>("https://api.hnpwa.com/v0/news/1.json");

  // if (news.length > 0) {
  //   jobs = await $fetch<any>("https://api.hnpwa.com/v0/jobs/1.json");
  // }

  return { news, jobs };
});
</script>

```
The error said `Error: [nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables`.

I clearly understand the error, but I think this should be working under such circumstance.

**Comment by danielroe** [comment]
Check out the link which explains a bit more about why this is the case. You can use `nuxtApp.runWithContext` to preserve context when using methods that need access to the nuxt instance.

**Comment by devops3199** [comment]
Thanks. `nuxtApp.runWithContext` solved my issue.

But I still don't understand why those fetches are treated as different context.

**Comment by danielroe** [comment]
Because JavaScript does not (yet) have a way to preserve context across async/await boundaries. This is something coming soon with native async context, however: https://github.com/nuxt/nuxt/pull/20918.

**Comment by mubarak117136** [comment]
@devops3199 hi can you please provide the example how you solve that issue. I am facing similar issue. Or please update your this "https://github.com/devops3199/nuxt3-issue-example" repo.

**Comment by devops3199** [comment]
@mubarak117136 I updated the repo with solution. Please check `app.vue`.

**Comment by mubarak117136** [comment]
thank you
