### ISSUE TITLE
middleware works only with import and no strings in definePageMeta

### ISSUE THREAD

**Issue by DamnFilthy** [nuxt/nuxt#22274]
### Environment

 "nuxt": "^3.6.2"
 nuxt dev
 
Doesnot work: 
```
<script setup lang="ts">
definePageMeta({
  middleware: ["checkUserToken"]
})
</script>
```

this works:
 ```
 <script setup lang="ts">
import checkUserToken from "../middleware/checkUserToken";

definePageMeta({
  middleware: [checkUserToken]
})
</script>
 ```

### Reproduction

https://github.com/DamnFilthy/Code-Job/blob/master/services/nuxt3/pages/index.vue

### Describe the bug

doesn't work according to documentation, need import and no strings

### Logs

```shell-script
500
Unknown route middleware: 'checkUserToken'. Valid middleware: .

at http://localhost/_nuxt/node_modules/nuxt/dist/pages/runtime/plugins/router.js?t=1689963703977&v=880a1442:122:21
```

**Comment by danielroe** [comment]
Seems to work fine for me:

https://stackblitz.com/github/DamnFilthy/Code-Job/tree/master/services/nuxt3?file=pages/index.vue

**Comment by Krutie** [comment]
@DamnFilthy The route middleware names are normalised to kebab-case when written like this, `checkUserToken`. 
So `checkUserToken` in this case, will become `check-user-token`.

```js
definePageMeta({
    middleware: ["check-user-token"]
})
```

Ref: https://nuxt.com/docs/guide/directory-structure/middleware#middleware-directory > 2nd bullet point.
