### ISSUE TITLE
Nuxt fails to load urls on linked module

### ISSUE THREAD

**Issue by vis97c** [nuxt/nuxt#22278]
### Environment

- Operating System: Windows_NT
- Node Version:     v16.19.0
- Nuxt Version:     3.5.1
- Nitro Version:    2.4.1
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      app, runtimeConfig, vite, css, modules, vuefire
- Runtime Modules:  @open-xamu-co/vue-component-system/nuxt@0.0.1, nuxt-vuefire@0.1.6
- Build Modules:    -

### Reproduction

The monorepo for the packages I'm building depends as well on some other unpublished packages so to reproduce the issue you would have to run the locally.

To minimize the effort just clone https://github.com/xamu-co/components and create a npm link at the path "packages/vue"

Then create a brand new nuxt project and link the package 'npm link @open-xamu-co/vue-component-system'.

You could as well use https://gitpkg.vercel.app/ to have it installed.

```json
{
  "dependencies": {
    "@open-xamu-co/vue-component-system": "https://gitpkg.now.sh/xamu-co/components/packages/vue?dev"
  }
}
```

Copy the dist folder to the root of the linked package.
[dist.zip](https://github.com/nuxt/nuxt/files/12134996/dist.zip)

Now you can include the module in nuxt: @open-xamu-co/vue-component-system/nuxt

```typescript
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  modules: ["@open-xamu-co/vue-component-system/nuxt"],
})
```

If you start nuxt you would get the error.

In the other hand if you install the package without linking and copy the dist to "node_modules/@open-xamu-co/vue-component-system" and run nuxt you shoudn't have to see any issue.

### Describe the bug

I have a [monorepo ](https://github.com/xamu-co/components) to release some components and a nuxt module to inject them, I'm getting multiple errors when linking this module.

Here is a longer stack of the error, it repeats for every chunk import:

```bash
[5:04:22 p. m.]  ERROR  Failed to load url /@fs/C:/projects/xamu/components/packages/vue/dist/_virtual/chunk_modifier_simple.es.js (resolved id: C:/projects/xamu/components/packages/vue/dist/_virtual/chunk_modifier_simple.es.js) in C:/projects/xamu/components/packages/vue/dist/lib/icon/Fa.vue.mjs. Does the file exist?
```

Without "/@fs/" the showcased paths are correct within my system.

### Why I think this is a bug?

This is a unpublished package so to emulate the production behavior I had to compile the distributables tothen copy those files directly to the module location on node modules within the nuxt project (no link). After running nuxt it worked just fine. So the issue comes from linked packages path resolution.

[#20001](https://github.com/nuxt/nuxt/issues/20001) seems related

This issue could be related to the way viteFs package resolves urls. Thanks in advance.

### Additional context

Here is the full setup if you need it:

### Setup commons monorepo

```bash
# clone the commons monorepo
git clone https://github.com/xamu-co/common common
cd common
# run the build script
yarn && yarn build
# create links for the packages
yarn workspaces run link # @open-xamu-co/common-enums, @open-xamu-co/common-types, @open-xamu-co/common-helpers
```

### Setup component monorepo

the module comes from here

```bash
# clone the components monorepo
git clone https://github.com/xamu-co/components components
cd components
# install the dependencies
yarn
# link the previous packages
yarn link @open-xamu-co/common-enums
yarn link @open-xamu-co/common-types
yarn link @open-xamu-co/common-helpers
# run the build script
yarn build
# create a link for the vue package
yarn p:vue link # @open-xamu-co/vue-component-system
```

### Use the module on nuxt

on a nuxt3 project install and then link the package @open-xamu-co/vue-component-system

```bash
# setup a project
npx nuxi@latest init my-app
cd my-app
yarn
# install the module
yarn add https://gitpkg.now.sh/xamu-co/components/packages/vue?dev
# add @open-xamu-co/vue-component-system/nuxt to your nuxt modules and run nuxt
yarn dev
```
These are yarn monorepos so yarn classic is required

**Comment by Hebilicious** [comment]
Out of curiosity, would you be able to get rid of the issue by using pnpm insteaf of yarn ? I have been doing similar things locally and never had this issue.

**Comment by vis97c** [comment]
> 

Sadly it seems like the issue persist for me on pnpm.
![image](https://github.com/nuxt/nuxt/assets/45251845/9be4d713-d3a5-442d-94fe-152c1dc015ab)

Can you elaborate a bit further on your setup? I'm not following the module template given by the team so maybe I missed some configuration. I will make further test with an standalone module

**Comment by Rednas83** [comment]
I have the same error while it seems to have resolved the correct location. Not sure what `/@fs/` is though.
![image](https://github.com/nuxt/nuxt/assets/25219229/389feeea-715f-4db7-817c-95ddd177283e)

In vscode the location is also resolved correctly with no typecheck errors.
![image](https://github.com/nuxt/nuxt/assets/25219229/7d925b1c-fced-486d-8f71-7c9fecc8a731)

Tried:
* npm link
* yarn link
* coderunner but that tries to resolve from `node_modules` instead of the local registred package
![image](https://github.com/nuxt/nuxt/assets/25219229/e3ff14ab-ee8f-4cda-8f5a-199f4c437d18)

**Comment by Hebilicious** [comment]
I can see that you are both using windows and https://github.com/nuxt/nuxt/issues/20001 is windows only , so this might be a windows specific bug...
Just to make sure I'm not missing anything, you are trying to do something like this ? https://github.com/Hebilicious/form-actions-nuxt/blob/main/playgrounds/advanced/package.json (latest with pnpm resolves to the local version of the module)

**Comment by vis97c** [comment]
@Hebilicious Quite close.

Moving the components to the runtime folder and loading uncompiled *.vue files solves the main issue.

Aditionally I didn't want to use the "link:" syntax but yarn is unaware of the packages being part of a monorepo so {"package":"*"} would generate dependency errors. Now my dependencies on the monorepo look more or less like this: {"package": "file:../package"}

**Comment by Rednas83** [comment]
I think link is a nice way to test locally before publishing.

For me it is not resolved yet.

Tried adding `vite: { resolve: { preserveSymlinks: true } }` in **Nuxt.Config**. It resolved the error, but it returned some kind of promise instead of the actual module.
![image](https://github.com/nuxt/nuxt/assets/25219229/424475fb-1ad4-4727-bdc2-26150bb53b44)

@vis97c What do you mean with moving the components to the runtime folder?

**Comment by vis97c** [comment]
@Rednas83 previously I had this file structure:

```bash
#  src/
#    runtime/
#      plugin.ts
#    lib/
#      icon.vue
#    module.ts
```

Now I have this

```bash
#  src/
#    runtime/
#      components/
#        icon.vue
#      plugin.ts
#    module.ts
```

Also I think you should not be invoking methods outside of the plugin function

**Comment by Hebilicious** [comment]
> @Hebilicious Quite close. Thanks for the heads up.
> 
> Moving the components to the runtime folder and loading uncompiled *.vue files solves the main issue.
> 
> Aditionally I didn't want to use the "link:" syntax but yarn is unaware of the packages being part of a monorepo so {"package":"*"} would generate dependency errors. Now my dependencies on the monorepo look more or less like this: {"package": "file:../package"}
> 
> Seems also like pnpm is able to detect and replace that kind of mapping

Just a heads-up if your module *is* part of your monorepo, with pnpm you can use latest, and it will resolve your local version first, so you can avoid relative paths, and have a syntax that works everywhere.

**Comment by Rednas83** [comment]
Tried linking with pnpm but now I got 2 errors
![image](https://github.com/nuxt/nuxt/assets/25219229/b73a29f0-8e7e-4203-be2e-8e8c014a0528)

After adding the package to the vite allow list the errors are gone, but the module is still returned as promise instead of the actual module
**Nuxt config.js**
```
  vite: {
    // resolve: { preserveSymlinks: true }, // https://github.com/nuxt/nuxt/issues/20001
    server: { fs: { allow: ["D:/Onedrive/Projecten/CoinCodex-API-v2/"] } } // https://vitejs.dev/config/server-options.html#server-fs-allow
  },
```

**Plugin - importing an instance of a class - but actually returns a promise**
![image](https://github.com/nuxt/nuxt/assets/25219229/c0a3ffdd-1e9c-4b3a-9960-5918ec44520b)

**Comment by vis97c** [comment]
Did you define your plugin on [module.ts](https://github.com/xamu-co/ui/blob/c29996ed095d285691f6b441524aafccbecae974/components/vue/src/module.ts#L33)?

**Comment by Rednas83** [comment]
@vis97c I just linked it. What do you mean with defining the plugin? Can you perhaps provide an example?

Below a printscreen of the library enviroment containing an instance of a class which I am trying to link to a nuxt application which is not part of a monorepo
![image](https://github.com/nuxt/nuxt/assets/25219229/89a4a3f3-2e33-42ff-ae21-57be3be951c6)

**Comment by vis97c** [comment]
@Rednas83 I'm not sure but it seems to me like you are missing the basics.

I'm my previous comment I linked the exact line in my entrypoint where the plugin is injected into the module.

Also, where is your module.ts with "defineNuxtModule"? Pls do a reproduction because this feels more like a miss configuration

**Comment by Rednas83** [comment]
The module I am trying to import/link is a just a vanilla js module and not a nuxt plugin!  The module fully works in the local/lib environment after importing 'import CoinCodex from '../lib/CoinCodex' but doesn't works after linking with `pnpm link --global` and importing the link into a nuxt application with 'import CoinCodex from 'coincodex-api-v2'.

I did get a warning with 'pnpm link --global'
![image](https://github.com/nuxt/nuxt/assets/25219229/53b580c9-c237-4224-8cf4-00ac1f49ed94)
https://github.com/pnpm/pnpm/issues/4761

I am not sure if there is a fix for that. Can it be ignored?

I don't understand how the module works locally but not anymore after creating a link.
