### ISSUE TITLE
cdnURL from nuxt.config.ts doesnt show up in nuxt.options.app property in a module

### ISSUE THREAD

**Issue by leonardo-melhor-envio** [nuxt/nuxt#22275]
### Environment

- Operating System: Linux
- Node Version:     v16.17.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      devtools, ssr, app, modules, pwa
- Runtime Modules:  ~/modules/cdn-url-repro/index.js
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-ie2hzh?file=modules%2Fcdn-url-repro%2Findex.js

### Describe the bug

When accessing the cdnURL property, we notice that the value is empty.

**Comment by Krutie** [comment]
I came across the similar issue! 

Both `buildAssetsDir:` and `baseURL:` are available when accessed in custom Nuxt module using `nuxt.options.app` or `nuxt.options.runtimeConfig.app`, however the `cdnURL` comes up empty.

I tried adding `cdnURL` following two different ways:

 1. `nuxt.config`

```ts
export default defineNuxtConfig({
  modules: ['~/modules/cdn-url-repro/index.ts'],
  app: {
    baseURL: '/app/',
    cdnURL: 'https://mycdn.org/'
  },
})
```

2. `app.config`

```ts
export default defineAppConfig({
    cdnURL: 'https://mycdn.org/'
    foo: 'bar'
})

```

...but unable to access `cdnURL` in Nuxt module. Below is the output of `nuxt.options.runtimeConfig`.

```ts
// modules/cdn-url-repro/index.ts
export default defineNuxtModule({
  setup(moduleOptions, nuxt) {
    console.log('nuxt.options.runtimeConfig');
    // {
    //     public: {},
    //     app: {
    //         baseURL: '/app/',
    //         buildAssetsDir: '/_nuxt/',
    //         cdnURL: ''
    //     }
    // }
  }
});
```

**Comment by Krutie** [comment]
@leonardo-melhor-envio  I think the temporary work around would be to pass `cdnURL` as moduleOptions:

```ts
// nuxt.config.ts
export default defineNuxtConfig({

  modules: ['~/modules/cdn-url-repro/index.ts'],

  cdnUrlRepro: {
    cdnURL: process.env.NUXT_APP_CDN_URL,
  }

});
```
...and then access this value in your module like below:

```ts
// modules/cdn-url-repro/index.ts
export default defineNuxtModule({

  meta: {
    name: 'cdn-url-repro',
    configKey: 'cdnUrlRepro',
  },

  setup(moduleOptions, nuxt) {
    console.log('moduleOptions', moduleOptions);
    // moduleOptions { cdnURL: 'https://mycdn.org/' }
  }

})
```

**Comment by danielroe** [comment]
Looking into this, the reason is that `cdnURL` is empty in development mode (as we cannot serve your dev assets from a different location than the dev server):

https://github.com/nuxt/nuxt/blob/f5920ff2e76edfa89fb760fddea221e4a4c4d047/packages/schema/src/config/app.ts#L71-L73

However, it will be accessible when building your project.

Why do you want it to be accessible in development mode?

**Comment by leonardo-melhor-envio** [comment]
@danielroe I was looking at the [@vite-pwa/nuxt](https://github.com/vite-pwa/nuxt) library code. In the project I'm currently working on, I need to set a base url, but for some reason this library only uses baseUrl to include the service-worker. For example: /app/dev-sw.js.
So I've been looking for a solution to add service worker based on cdnurl - [issue-57](https://github.com/vite-pwa/nuxt/issues/57).
