### ISSUE TITLE
 The cache on the Cloudflare page does not expire

### ISSUE THREAD

**Issue by DanSnow** [nuxt/nuxt#22279]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.4.0`
- Nuxt Version:     `3.6.5`
- Nitro Version:    `2.5.2`
- Package Manager:  `yarn@3.6.1`
- Builder:          `vite`
- User Config:      `devtools`, `nitro`, `routeRules`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

source code: https://github.com/DanSnow/nuxt-cache-test
demo: https://nuxt-cache-test.pages.dev

### Cache Configuration
- API: Use defineCachedEventHandler with the settings `swr: true` and `maxAge: 1`. https://github.com/DanSnow/nuxt-cache-test/blob/main/server/api/time.ts
- Route Rule: All use the settings `swr: true`, `maxAge: 10`, and `staleMaxAge: 3`. https://github.com/DanSnow/nuxt-cache-test/blob/main/nuxt.config.ts#L12

### Expected Behavior
The time difference between the server and the client should be at most around 10 seconds.

### Actual Behavior
As shown in the video, the server's time remains unchanged.

https://github.com/nuxt/nuxt/assets/5575082/99c02dd2-287e-4d1a-8a25-51da24c60024

**Comment by danielroe** [comment]
If you're still experiencing this, would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏

If it only recurs with Nuxt, let me know and I'll reopen it here.
