### ISSUE TITLE
Why `cache` option in `useFetch` not mentioned in documentation ?

### ISSUE THREAD

**Issue by nasirDoe** [nuxt/nuxt#22287]
### Environment

- Nuxt 3
- Mac Os
- Chrome

### Reproduction

https://nuxt.com/docs/api/composables/use-fetch#usefetch

### Describe the bug

-

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/15445

**Comment by nasirDoe** [comment]
Sorry, how to disabled cache ? because when i updated data in CMS the data in FE still not updated ?

**Comment by danielroe** [comment]
@nasirDoe It sounds like you have questions about static builds. Would you open a discussion or join the Nuxt Discord? 🙏

**Comment by nasirDoe** [comment]
No, i build in ssr but API with laravel

**Comment by nasirDoe** [comment]
Finally i solved my problem with

```js
routeRules: {
    '/**': {
      prerender: false,
    },
  },
```

is this way good ?
