### ISSUE TITLE
Chart Error when navigating between pages that have animations

### ISSUE THREAD

**Issue by ivan-angjelkoski** [nuxt/nuxt#22285]
### Environment

Nuxt 3

### Reproduction

install apexcharts or any charting library and try to render a chart in a page different than index, when navigating to the page without animations, the chart renders fine, but when i add page transitions, especialy with the 'out-in' mode, the website crashes.

btw SSR is set to false.

### Describe the bug

install apexcharts or any charting library and try to render a chart in a page different than index, when navigating to the page without animations, the chart renders fine, but when i add page transitions, especialy with the 'out-in' mode, the website crashes.

### Additional context

<img width="1800" alt="image" src="https://github.com/nuxt/nuxt/assets/56976418/d51640ba-2e26-4049-aa8b-c9d2cfd122df">
<img width="1344" alt="image" src="https://github.com/nuxt/nuxt/assets/56976418/83704cf1-91c2-42a0-a301-544dc3667092">

**Comment by danielroe** [comment]
The core issue here is this one: https://github.com/vuejs/core/issues/5844, which is tracked in nuxt in https://github.com/nuxt/nuxt/issues/13471. It means that on client-side transition the mounted code runs before the dom is actually there. You can try some of the workarounds in that comment thread.
