### ISSUE TITLE
Retry import / chunk / CSS loads for transient network errors

### ISSUE THREAD

**Issue by edwh** [nuxt/nuxt#22283]
### Describe the feature

Two extremely common Sentry errors on my live site are `TypeError: Importing a module script failed` and `Unable to preload CSS`.  These are almost certainly caused by transient network errors on mobile devices.  

(The fact that I get the Sentry reports at all shows there are a lot of transient errors.  I also have sleep/retry function in my API-accessing code for this reason using [fetch-retry](https://www.npmjs.com/package/fetch-retry) and which I can tell succeeds after some retries.  So transient network errors are a common thing.)

I'd like to be able to add retrying for loading JS and CSS too - because these are common errors for mobile users.  Is this achievable in any way at present?

A couple of notes:
- I am aware of discussions about detecting chunk load errors in the case where a new version of the code has been deployed.  This is not that case, though it is related.
- I'm also aware of the preload function.  That reduces the chances of this happening, but a) doesn't cure it and b) costs more network data for mobile users and therefore may not be desirable.
- I'm interested in **everything** that gets loaded - whether it's an entry script, a chunk, a dynamic component, CSS, or anything else that I might not have thought of.

If this should be in Vue/vite/nitro/somewhere else, please let me know and I'll move it.  And if this is already covered clearly somewhere that I've failed to locate, then my apologies.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
This is managed by vite so it would probably be best to raise it there but please do tag me in it. If it's possible to take more ownership of this in Nuxt I'd be very happy to do that.

**Comment by edwh** [comment]
https://github.com/vitejs/vite/discussions/13925
