### ISSUE TITLE
Unable to use definePageMeta for error page

### ISSUE THREAD

**Issue by jd-solanki** [nuxt/nuxt#22300]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.6.5`
- Nitro Version:    `2.5.2`
- Package Manager:  `pnpm@8.5.1`
- Builder:          `vite`
- User Config:      `devtools`, `components`, `plugins`, `imports`, `hooks`, `experimental`, `typescript`, `sourcemap`, `vite`, `build`, `modules`
- Runtime Modules:  `@vueuse/nuxt@10.2.1`
- Build Modules:    `-`

### Reproduction

https://codesandbox.io/p/sandbox/hardcore-blackburn-68n32x?file=%2Ferror.vue%3A11%2C16

### Describe the bug

routes inside `pages` dir supports `definePageMeta` but error page is outside of the pages dir so how can I pass my custom route meta?

### Additional context

Nothing in docs regarding this 🤷🏻‍♂️

**Comment by danielroe** [comment]
The error page isn't a page/route and it is displayed no matter what page/route you are on. It does not support `definePageMeta`.

What are you trying to achieve?

**Comment by danielroe** [comment]
Yes, `error.vue` is used for displaying errors. Like `app.vue`, it's global and not specific to any page/route.

**Comment by pitambar-jha** [comment]
> 

You can trap the relevant route meta in a plugin and raise an error manually in case the route meta is ‘blank’, It will open the 404 page automatically.
