### ISSUE TITLE
return type inference does not work with uppercase 'GET' method

### ISSUE THREAD

**Issue by Gerbuuun** [nuxt/nuxt#22313]
### Environment

- Operating System: Darwin
- Node Version:     v20.2.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.6.10
- Builder:          vite
- User Config:      devtools, nitro, modules, components, css, runtimeConfig, auth
- Runtime Modules:  @nuxtjs/eslint-module@4.1.0, @nuxtjs/i18n@8.0.0-beta.12, nuxt-icon@0.4.2, @nuxtjs/device@3.1.0, @sidebase/nuxt-auth@0.6.0-beta.3, @nuxtjs/tailwindcss@6.8.0
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-9umhjm?file=app.vue
(idk how to show type errors on stackblitz but I tested the same code in VSCode and got the same behaviour)

### Describe the bug

When an endpoint has a `GET` and a `POST` file, `useFetch` has the union of both as the return type

**Comment by danielroe** [comment]
For now, you can work around by using a lowercase `'get'` method.
