### ISSUE TITLE
Auth middleware fetch data from api

### ISSUE THREAD

**Issue by Kalogeros95** [nuxt/nuxt#22314]
### Environment

```
import { authStore } from “~/store/auth”;
import { callWithNuxt } from “#app”;
export default defineNuxtRouteMiddleware(async () => {
  const auth = authStore();
  const nuxtApp = useNuxtApp();
  let user
  try {
    user = await $fetch(“http://localhost:3333/auth/validate”, {
      method: “POST”,
      headers: {
        Authorization: `Bearer ${auth.token}`,
      },
    });
    return await callWithNuxt(nuxtApp, navigateTo, [‘/’])
  } catch (e) {
    user = null
    console.log(e)
  }
  if (!user)
    return await callWithNuxt(nuxtApp, navigateTo, [‘/’])
});
```

### Reproduction

user null

### Describe the bug

I am trying to run this middleware but every time it returns null as if the user has never logged in. What is wrong?

**Comment by manniL** [comment]
In your example code, you never set the `user` variable to something 🤔

**Comment by Kalogeros95** [comment]
@manniL i updated the code, but still the user variable returns null.

**Comment by manniL** [comment]
@Kalogeros95 Could you kindly provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
