### ISSUE TITLE
Some files were not copied to .output/server/node_modules during build

### ISSUE THREAD

**Issue by dongnaebi** [nuxt/nuxt#22325]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.16.1
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.1
- Package Manager:  pnpm@7.13.6
- Builder:          vite
- User Config:      modules, colorMode
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, nuxt-icon@0.3.3, @nuxtjs/color-mode@3.3.0
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-amtrbm?file=server%2Fapi%2Ficons.ts

Steps:
```shell
npm run build
```
```shell
npm run preview
```
visit /api/icons

### Describe the bug

no such file or directory, open '/home/projects/nuxt-starter-amtrbm/.output/server/node_modules/@iconify/json/collections.json
![image](https://github.com/nuxt/nuxt/assets/6902417/a55211e6-9525-4ec5-a6b0-fa5f5c213b7e)

My api depends on iconify's api, but after build, the main files of the `@iconify/json` package were not copied to the `.output/server/node_modules/@iconify/json` directory

I saw a similar issue: https://github.com/nuxt/nuxt/issues/13131

### Additional context

It works in nuxt dev

correct directory structure：
![image](https://github.com/nuxt/nuxt/assets/6902417/90681967-4ef5-497b-8fed-89c6cd0c981a)

### Logs

```shell-script
{"url":"/api/icons","statusCode":500,"statusMessage":"","message":"ENOENT: no such file or directory, open '/home/projects/nuxt-starter-amtrbm/.output/server/node_modules/@iconify/json/collections.json'","stack":""}
```

**Comment by bitbytebit1** [comment]
In the past transpiling has worked for me. 
https://nuxt.com/docs/guide/concepts/esm#transpiling-libraries

**Comment by danielroe** [comment]
This is likely an upstream issue with nitro (or specifically vercel/nft which it uses to trace files used in the build).

You can manually add files via `nitro.externals.traceInclude`.

**Comment by davidnknight** [comment]
I'd like to add that I'm also experiencing the same issue with some files missing in the .output directory since upgrading Nuxt to 3.6.5. I have temporarily resolved this by uploading all files and folders, where as previously I would only upload the compiled .output directory, which is obviously preferred as we're now deploying source code until this issue is resolved.

For us, the issue has so far always been with destr package. Some deployments destr is present in the node_modules directory but missing the package.json, but in the deployment below the entire package is missing, so what's missing is different from one deployment to another.

```sh
node server/index.mjs
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'destr' imported from /home/[redacted]/[redacted]/releases/[redacted]/server/index.mjs
    at new NodeError (node:internal/errors:405:5)
    at packageResolve (node:internal/modules/esm/resolve:782:9)
    at moduleResolve (node:internal/modules/esm/resolve:831:20)
    at defaultResolve (node:internal/modules/esm/resolve:1036:11)
    at DefaultModuleLoader.resolve (node:internal/modules/esm/loader:251:12)
    at DefaultModuleLoader.getModuleJob (node:internal/modules/esm/loader:140:32)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:33)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v20.5.0
```

**Comment by danielroe** [comment]
This is almost certainly an issue with nitro's hoisting algorithm, which can occur when there are multiple versions of a dependency in your node_modules, which is why it has started occurring after a Nuxt upgrade

**Comment by davidnknight** [comment]
Thanks for the quick reply. I have rebuilt the lock file and no change. Any idea when the hoisting issue might be looked into further? Wondering if there's any rough timeline to this, be it days/weeks/months.

**Comment by bvqbao** [comment]
I have this problem when using knex. In the project root's ```./node_modules/knex``` there are two files: knex.js and knex.mjs:
<img width="149" alt="image" src="https://github.com/nuxt/nuxt/assets/4357219/81f1d70e-07e1-41cd-a203-f8c1fc229eea">

On the other hand, in the ```.output/server/node_modules/knex``` there is only one knex.mjs file:
<img width="115" alt="image" src="https://github.com/nuxt/nuxt/assets/4357219/2182d2bb-c166-45a9-982b-b65157341a7b">

When I copy the missing knex.js file to ```.output/server/node_modules/knex```, the production server works!

**Comment by MertcanYuzer** [comment]
> I have this problem when using knex. In the project root's `./node_modules/knex` there are two files: knex.js and knex.mjs: <img alt="image" width="149" src="https://user-images.githubusercontent.com/4357219/256860190-81f1d70e-07e1-41cd-a203-f8c1fc229eea.png">
> 
> On the other hand, in the `.output/server/node_modules/knex` there is only one knex.mjs file: <img alt="image" width="115" src="https://user-images.githubusercontent.com/4357219/256860623-2182d2bb-c166-45a9-982b-b65157341a7b.png">
> 
> When I copy the missing knex.js file to `.output/server/node_modules/knex`, the production server works!
> 
> So for some reason, the build process only copy *.mjs files when there are multiple versions of the same file.

I'm facing the same issue. Did you manage to solve it?

**Comment by bvqbao** [comment]
> I'm facing the same issue. Did you manage to solve it?
Nope. I just want to play with Nuxt server api a bit and I think the server api part is not ready (at least for me) yet.

**Comment by danielroe** [comment]
You also add the files to `nitro.externals.traceInclude`:

```ts
export default defineNuxtConfig({
  nitro: {
    externals: {
      traceInclude: []
    }
  }
})
```

**Comment by MertcanYuzer** [comment]
> You also add the files to `nitro.externals.traceInclude`:
> 
> ```ts
> export default defineNuxtConfig({
>   nitro: {
>     externals: {
>       traceInclude: []
>     }
>   }
> })
> ```

```js
externals: {
      traceInclude: ["node_modules/knex/knex.js"]
    }
```

This also solves the problem, thank you very much Daniel.
Actually, I saw your previous suggestion about using `nitro.externals.traceInclude`, but I couldn't grasp its purpose and how to try it out because I couldn't find any information. Is there any documentation available?

I'm curious if we can use it for other purposes, like for the knex migrations and seeds folders that we add directly to the project's directory.

**Comment by max06** [comment]
Sorry for being late to the party - same issue but with `@kubernetes/client-node`, or more precisely its dependency `ws`. And it happens only if I'm building it in the bun docker image (version 1.0.22).

**Comment by danielroe** [comment]
If you're still experiencing this, would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏

If it only recurs with Nuxt, let me know and I'll reopen it here.
