### ISSUE TITLE
Page:finish dont catch document.title correctly

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/nuxt#22334]
### Environment

Nuxi 3.6.5                                                                                                         8:53:45
                                                                                                                   8:53:46
RootDir: /home/projects/nuxt-starter-ae5bqu                                                                        8:53:46
Nuxt project info:                                                                                                 8:53:46

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                        8:53:46

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Reproduction

https://stackblitz.com/edit/nuxt-starter-ae5bqu

### Describe the bug

when we navigate in reproduction link, when page:finish hook is triggered, document.title its the previous page, not the actual page
![image](https://github.com/nuxt/nuxt/assets/77386602/cec60775-7b4e-47a2-83d6-e76661a35cc7)

See the console

**Comment by danielroe** [comment]
You will have to wait for the next tick for the document itself to be updated.

**Comment by danielroe** [comment]
well, it clearly does change, so it might be more than one tick.

what is the thing you are trying to do/what's the bug?

**Comment by agracia-foticos** [comment]
> well, it clearly does change, so it might be more than one tick.
> 
> what is the thing you are trying to do/what's the bug?

![image](https://github.com/nuxt/nuxt/assets/77386602/554b2f80-c07a-4d89-8073-c10289dcb8b8)

When you navigate, see the console of navigator.

The title its "Link 1" but in console, its printed "Home" (the previous title page)

**Comment by danielroe** [comment]
That's just because the code is running before the title is updated.

**Comment by agracia-foticos** [comment]
> That's just because the code is running before the title is updated. What makes you think it's a bug?

If the hook is "page:finish", I understand that it is when the page has been fully loaded in vue part, right? In this case, the title of the page still remains to be loaded :(

What hook can I use to make sure that the entire page is loaded?


The problem is that I am using segment (https://segment.com/docs/connections/spec/page/) which defaults to title as document.title. You are currently falsifying the data, because you are loading urls (paths) with wrong titles (the previous pages)

**Comment by agracia-foticos** [comment]
We are having problems with Google Analytics. The referrer is not loading correctly in the page:finish hook, which is giving "incorrect" values. Please reconsider the issue, we need a valid hook in which they are already loaded:
location.pathname
document.referrer
document.title

**Comment by danielroe** [comment]
cc: @harlan-zw Any thoughts on this?

**Comment by agracia-foticos** [comment]
Related https://github.com/nuxt/nuxt/issues/22560

**Comment by danielroe** [comment]
resolved in https://github.com/nuxt/nuxt/pull/22566
