### ISSUE TITLE
Cannot access environment variables in `useRuntimeConfig` using `source .env && node server.mjs`

### ISSUE THREAD

**Issue by xuzuodong** [nuxt/nuxt#22331]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.1.0`
- Nuxt Version:     `3.6.5`
- Nitro Version:    `2.5.2`
- Package Manager:  `pnpm@8.6.6`
- Builder:          `vite`
- User Config:      `devtools`, `runtimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

1. Clone https://github.com/xuzuodong/nuxt-source-test 
2. run `pnpm i`
3. run `pnpm dev`, open `localhost:3000`, and then console will print runtime config object, including environment variable `testEnv`, which is accessible:
```js
{
  app: { baseURL: '/', buildAssetsDir: '/_nuxt/', cdnURL: '' },
  nitro: { envPrefix: 'NUXT_', routeRules: { '/__nuxt_error': [Object] } },
  public: {},
  testEnv: '12345678asdf'
}
```
4. quit the dev process and run `pnpm build`, then `pnpm start`
5. open `localhost:3000`, and then console will print runtime config, and value of environment variable `testEnv` is missing:
```js
{
  app: { baseURL: '/', buildAssetsDir: '/_nuxt/', cdnURL: '' },
  nitro: {
    envPrefix: 'NUXT_',
    routeRules: { '/__nuxt_error': [Object], '/_nuxt/**': [Object] }
  },
  public: {},
  testEnv: ''
}
```

### Describe the bug

According to [the doc](https://nuxt.com/docs/guide/going-further/runtime-config#environment-variables), runtime config values are automatically replaced by matching environment variables at runtime. This works in development mode, but different behavior happens when I build and run the output with `.env` file sourced. 

According to [the env doc](https://nuxt.com/docs/guide/directory-structure/env), after server is built, environment variables should be set before server running, one recommended way is to source env file using `source .env && node .output/server/index.mjs`. 

However, such script cannot successfully inject environment variables declared in `.env`. 

Is there something I missed?

### Additional context

A temporary workaround I'm using now is manually assign environment variables to runtimeConfig in `nuxt.config.ts`: 

```
  runtimeConfig: {
    testEnv: process.env.NUXT_TEST_ENV
  }
```

**Comment by danielroe** [comment]
You're right, running `source .env` won't work, though this is not a Nuxt issue but a documentation point for how to load environment variables into a shell.

Here are two ways of loading in variables correctly:

```sh
NUXT_TEST_ENV=thing node .output/server/index.mjs
# or
export NUXT_TEST_ENV=thong
node .output/server/index.mjs
```

A PR to improve the docs here would be welcome, perhaps with details on Windows, Linux + MacOS 🙏 

And, as always, note that running `nuxi preview` will handle this automatically if you are wanting simply to preview your site locally.

**Comment by xuzuodong** [comment]
@danielroe Hi, thank you for prompt response to my issue. And I'm willing to help improving the docs! 

Though I still have a question: 

We still need a way to load all environment variables defined in `.env`. These two ways you mentioned is only suitable for a small number of environment variables in project, and users may have large numbers of environment variables defined in a `.env` file and it's certainly not elegant to explicitly define them all in `scripts` in `package.json`. 

So after doing some research, I found [a simple way to load all environment variables defined in `.env`](https://stackoverflow.com/a/65692087/12931490), and seems to work perfectly:

```bash
# instead of this
source .env && node server.js
# do this
export $(cat .env | egrep -v '#|^$' | xargs) && node server.js
```

Do you think this is a proper way and can go into docs?

**Comment by adrienZ** [comment]
what about ?

```typescript [nuxt.config.ts]
import 'dotenv/config'

export default defineNuxtConfig({
  ...your config
})
```
