### ISSUE TITLE
after installing new nuxt 3 project i recieve this error Named export 'consola' not found.

### ISSUE THREAD

**Issue by unknownman** [nuxt/nuxt#22346]
### Environment

Nuxi 3.6.5                                                                                                                                          5:53:02 PM
                                                                                                                                                    5:53:02 PM
RootDir: /Users/ainalavi/Desktop/Dashboard/Code/nuxtjs/youtube-channel                                                                              5:53:02 PM
Nuxt project info: (copied to clipboard)                                                                                                            5:53:02 PM

------------------------------
- Operating System: Darwin
- Node Version:     v16.15.1
- Nuxt Version:     3.4.3
- Nitro Version:    2.3.3
- Package Manager:  yarn@1.22.10
- Builder:          vite
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-9yreaw?file=package.json,app.vue

### Describe the bug

when i install new nuxt 3 i recieve this error 
```
[7:44:08 PM] [nuxt] [request error] [unhandled] [500] Named export 'consola' not found. The requested module 'consola' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'consola';
const { consola } = pkg;

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)  
  at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)  
  at async Promise.all (index 0)  
  at async ESMLoader.import (node:internal/modules/esm/loader:385:24)  
  at async ./.nuxt/dev/index.mjs:642:24  
  at async ./.nuxt/dev/index.mjs:724:64  
  at async ./.nuxt/dev/index.mjs:394:22  
  at async Object.handler (/Users/ainalavi/node_modules/h3/dist/index.mjs:1247:19)  
  at async Server.toNodeHandle (/Users/ainalavi/node_modules/h3/dist/index.mjs:1322:7)
  ```
  
  and this is output of yarn why consola
  ```
  => Found "consola@3.2.3"
info Reasons this module exists
   - "@nuxt#devtools" depends on it
   - Hoisted from "@nuxt#devtools#consola"
   - Hoisted from "nuxt#nitropack#consola"
   - Hoisted from "@nuxt#devtools#@nuxt#devtools-wizard#consola"
   - Hoisted from "nuxt#@nuxt#kit#consola"
   - Hoisted from "nuxt#@nuxt#telemetry#consola"
   - Hoisted from "nuxt#@nuxt#vite-builder#consola"
   - Hoisted from "nuxt#unenv#consola"
   - Hoisted from "nuxt#nitropack#citty#consola"
   - Hoisted from "nuxt#nitropack#listhen#consola"
info Disk size without dependencies: "308KB"
info Disk size with unique dependencies: "308KB"
info Disk size with transitive dependencies: "308KB"
info Number of shared dependencies: 0
  ```

### Logs

```shell-script
[7:44:08 PM] [nuxt] [request error] [unhandled] [500] Named export 'consola' not found. The requested module 'consola' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'consola';
const { consola } = pkg;

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)  
  at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)  
  at async Promise.all (index 0)  
  at async ESMLoader.import (node:internal/modules/esm/loader:385:24)  
  at async ./.nuxt/dev/index.mjs:642:24  
  at async ./.nuxt/dev/index.mjs:724:64  
  at async ./.nuxt/dev/index.mjs:394:22  
  at async Object.handler (/Users/ainalavi/node_modules/h3/dist/index.mjs:1247:19)  
  at async Server.toNodeHandle (/Users/ainalavi/node_modules/h3/dist/index.mjs:1322:7)
```

**Comment by command-tab** [comment]
Does this happen in the linked reproduction? I tried to reproduce this, but the linked reproduction appears to have installed and started up just fine.

**Comment by danielroe** [comment]
The latest Nuxt version is 3.6.5, not 3.4.3 - are you sure this is a new project?

**Comment by AmirJavaidSwe** [comment]
@danielroe 
I am getting this error on 3.6.5
my node version is 18
![image](https://github.com/nuxt/nuxt/assets/41790096/3c1e5548-f6c0-4c49-9b0f-4d44ab22726c)


can you help?

I also removed `package-lock.json` file and `node_modules` folder, and did `npm install`

**Comment by unknownman** [comment]
> * Nuxt Version:     3.4.3

Nuxt Version is 3.4.3 and 3.6.5 is the version of nuxi

**Comment by unknownman** [comment]
> Does this happen in the linked reproduction? I tried to reproduce this, but the linked reproduction appears to have installed and started up just fine.

i think its work in reproduction. but i catch this error in my local environment, as i mentioned before

**Comment by unknownman** [comment]
> @danielroe I am getting this error on 3.6.5 my `node version is 18` I am on `windows 11`
> 
> ![image](https://user-images.githubusercontent.com/41790096/256693100-3c1e5548-f6c0-4c49-9b0f-4d44ab22726c.png)
> 
> I am getting this error when I run
> 
> `npm run dev -- -o`
> 
> can you help?
> 
> I also removed `package-lock.json` file and `node_modules` folder, and did `npm install`

i check it with node16 and node 18. and in both of them i catch the same error
when i run ```yarn dev -o``` its ok as you see
<img width="487" alt="Screenshot 1402-05-06 at 12 24 53" src="https://github.com/nuxt/nuxt/assets/1284596/1d73d1a6-be06-4238-aebc-b7f6d08a786d">

but when i visit a page the error will be exist
<img width="1161" alt="Screenshot 1402-05-06 at 12 25 54" src="https://github.com/nuxt/nuxt/assets/1284596/cb405cef-25f3-4325-bb0c-c27366bb0e64">

**Comment by AmirJavaidSwe** [comment]
so, did you come up with any solution?

**Comment by unknownman** [comment]
Unfortunately no

**Comment by unknownman** [comment]
I checked with node 16 and 18
In both there are problem

**Comment by danielroe** [comment]
You have an outdated version of `consola`. Check your lockfile and maybe use npm overrides/yarn resolutions to force consola@3.

**Comment by unknownman** [comment]
my problem solved. it was Because of the existence of the node_modules in the home directory of the user.

**Comment by ra-dave** [comment]
Just started having this same problem out of the blue, have no idea what triggered it or how to resolve it.  I don't have a global node_modules folder.
