### ISSUE TITLE
Nuxt 3 + https devServer (https://localhost:3000/) throws 500 Error

### ISSUE THREAD

**Issue by rod2ik** [nuxt/nuxt#22347]
Hi,

Thanks for your fantastic work ! 

I am trying to set an `https` `devServer` with a fresh install of Nuxt 3, to work with `https://localhost:3000`.

After a fresh install (just Nuxt 3 + the two pem files), I am receiving the following error when everything is set, when I try to `yarn dev` the project.

I successfully created two pem files (with `mkcert`, and created/imported the CA certificate), and configured the `nuxt.config.ts` lines as stated in the official nuxt 3 site as described in [this page](https://nuxt.com/docs/api/configuration/nuxt-config#https)  :

``` ts
  devServer: {
    https: {
      key: './myserver+3-key.pem',
      cert: './myserver+3.pem',
    }
  }
```

## Environment

Nuxi 3.6.5                                                                                           17:00:45
                                                                                                     17:00:45
RootDir: /home/rod2ik/Documents/https-nuxt                                               17:00:45
Nuxt project info:                                                                                   17:00:45

------------------------------
- Operating System: Linux
- Node Version:     v20.3.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      devtools, devServer
- Runtime Modules:  -
- Build Modules:    -

## Reproduction

On project directory, type `yarn dev` and click on `> Local:    https://localhost:3000/ `

Here is a demo repo to play with : [rod2ik/https-nuxt](https://github.com/rod2ik/https-nuxt)

## Describe the bug

Both on the Terminal/IDE (I am using VSCode) and in my Browser (Firefox and Chrome)  I receive the following error when I launch the site via `yarn dev`

[nuxt] [request error] [unhandled] [500] fetch failed (https://localhost:3000/__nuxt_vite_node__/manifest)

![https-nuxt-500-error](https://github.com/nuxt/nuxt/assets/94541819/8144d249-f816-4b38-b735-cbd20777769e)

What is weird is that it works fine (the page `https://localhost:3000` is correctly rendered) if I add `ssr: false` in `nuxt.config.ts` configurations (uncomnent line 4 of `nuxt.config.ts` file to test it)

![https-nuxt-ssr-false](https://github.com/nuxt/nuxt/assets/94541819/f440c3e1-2732-4644-82f9-29434ed013e8)

## Browser/Terminal Logs

```shell-script
[17:09:26] [nuxt] [request error] [unhandled] [500] fetch failed (https://localhost:3000/__nuxt_vite_node__/manifest)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async $fetchRaw2 (./node_modules/ofetch/dist/shared/ofetch.d438bb6f.mjs:215:14)  
  at async $fetch2 (./node_modules/ofetch/dist/shared/ofetch.d438bb6f.mjs:239:15)  
  at async ./.nuxt/dev/index.mjs:810:20  
  at async ./.nuxt/dev/index.mjs:898:64  
  at async ./.nuxt/dev/index.mjs:537:22  
  at async Object.handler (./node_modules/h3/dist/index.mjs:1284:19)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1359:7)
[17:09:26] [nuxt] [request error] [unhandled] [500] fetch failed (https://localhost:3000/__nuxt_vite_node__/manifest)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async $fetchRaw2 (./node_modules/ofetch/dist/shared/ofetch.d438bb6f.mjs:215:14)  
  at async $fetch2 (./node_modules/ofetch/dist/shared/ofetch.d438bb6f.mjs:239:15)  
  at async ./.nuxt/dev/index.mjs:810:20                                                              17:09:21
  at async ./.nuxt/dev/index.mjs:898:64  
  at async ./.nuxt/dev/index.mjs:537:22  
  at async Object.handler (./node_modules/h3/dist/index.mjs:1284:19)  
  at async toNodeHandle (./node_modules/h3/dist/index.mjs:1359:7)  
  at async Object.ufetch [as localFetch] (./node_modules/unenv/runtime/fetch/index.mjs:9:17)  
  at async Object.errorhandler [as onError] (./.nuxt/dev/index.mjs:628:30)
```

## Additional context

Additional Context : in the async `toNodeHandle()`  function, on line 1359 of the `h3` module, the h3 event is  :

``` shell-script
H3Event {                                                                                            17:11:16
  __is_event__: true,
  _handled: false,
  context: {},
  node: {
    req: IncomingMessage {
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: undefined,
      readableEncoding: null,
      readableEnded: true,
      readableFlowing: false,
      readableHighWaterMark: 0,
      readableLength: 0,
      readableObjectMode: false,
      readableAborted: false,
      readableDidRead: false,
      closed: false,
      errored: null,
      readable: false,
      destroyed: false,
      aborted: false,
      httpVersion: '1.1',
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      complete: true,
      headers: [Object],
      trailers: {},
      method: 'GET',
      url: '/__nuxt_error?url=/&statusCode=500&statusMessage&message=fetch+failed+(https://localhost:3000/__nuxt_vite_node__/manifest)&stack=%3Cpre%3E%3Cspan+class=%22stack+internal%22%3Eat+process.processTicksAndRejections+(node:internal/process/task_queues:95:5)%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+async+$fetchRaw2+(./node_modules/ofetch/dist/shared/ofetch.d438bb6f.mjs:215:14)%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+async+$fetch2+(./node_modules/ofetch/dist/shared/ofetch.d438bb6f.mjs:239:15)%3C/span%3E%0A%3Cspan+class=%22stack%22%3Eat+async+./.nuxt/dev/index.mjs:810:20%3C/span%3E%0A%3Cspan+class=%22stack%22%3Eat+async+./.nuxt/dev/index.mjs:898:64%3C/span%3E%0A%3Cspan+class=%22stack%22%3Eat+async+./.nuxt/dev/index.mjs:537:22%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+async+Object.handler+(./node_modules/h3/dist/index.mjs:1284:19)%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+async+Server.toNodeHandle+(./node_modules/h3/dist/index.mjs:1360:7)%3C/span%3E%3C/pre%3E',
      statusCode: 200,
      statusMessage: '',
      connection: [Socket],
      socket: [Socket],
      body: null,
      __unenv__: undefined,
      [Symbol(kCapture)]: false
    },
    res: ServerResponse {
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: undefined,
      writable: true,
      writableEnded: false,
      writableFinished: false,
      writableHighWaterMark: 0,
      writableLength: 0,
      writableObjectMode: false,
      writableCorked: 0,
      closed: false,
      errored: null,
      writableNeedDrain: false,
      destroyed: false,
      _encoding: 'utf-8',
      statusCode: 200,
      statusMessage: '',
      upgrading: false,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      finished: false,
      headersSent: false,
      strictContentLength: false,
      connection: null,
      socket: null,
      _headers: {},
      req: [IncomingMessage],
      [Symbol(kCapture)]: false
    }
  }
}
```

**Comment by rod2ik** [comment]
This issue comes from [this](sidebase/nuxt-auth#484)

**Comment by danielroe** [comment]
If you are using a self-signed certificate in development, you will need to set `NODE_TLS_REJECT_UNAUTHORIZED=0` in your environment.

https://nuxt.com/docs/api/commands/dev#nuxi-dev

**Comment by steklopod** [comment]
> https://nuxt.com/docs/api/commands/dev#nuxi-dev

It's not actual anymore. Now it's easier. All that we need is:

```js
export default defineNuxtConfig({
  devServer: {
    https: {
      key: 'localhost-key.pem',
      cert: 'localhost.pem'
    }
  },
})
```
