### ISSUE TITLE
Add nuxt option to designate target version for `nuxt dev`

### ISSUE THREAD

**Issue by cadenzah** [nuxt/nuxt#22352]
### Describe the feature

As we all know we can set [`vite.build.target`](https://vitejs.dev/config/build-options.html) to a specific version, and this configuration will have effect when we do `nuxt build`.

But what about `nuxt dev`? For the environment's issue I have limited option for browser version; let's say I have to use Chrome with `73` version. When I put the config like below and build it using `nuxt build` command, I can view the built page on Chrome73 browser.

```js
// nuxt.config.js
...
build: {
    target: ['chrome76', 'node18'],
    ...
},
...
```

But when I run `nuxt dev` and view it on the Chrome73 browser, the browser console shows the error message like below:

```
Uncaught SyntaxError: Unexpected token '.'
```

Maybe the nuxt(or vite inside) compiles and generates JS bundle targeting the highest(latest) version of browser by default when `yarn dev`. This message means that the parsed JS script cannot be interpreted by the browser, because the build option is too high for the Chrome73 browser.

Can we configure target option for `nuxt dev`'s bundle as well as `nuxt build`? Or, is there any configuration option that I've missed?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
You can use the `$production` and `$development` environment prefixes in Nuxt config to set the target just for dev/prod build.

**Comment by cadenzah** [comment]
@danielroe Thank you for the guide, but would you share the page link for that configuration? I can't find it.

**Comment by danielroe** [comment]
https://nuxt.com/docs/getting-started/configuration#environment-overrides

**Comment by cadenzah** [comment]
@danielroe Thank you! 🙏
