### ISSUE TITLE
How to remove the CSS and data returned by the API in the nuxt3 source code?

### ISSUE THREAD

**Issue by MG-ROY** [nuxt/nuxt#22368]
### Discussed in https://github.com/nuxt/nuxt/discussions/22354

<div type='discussions-op-text'>

<sup>Originally posted by **MG-ROY** July 27, 2023</sup>
When opening the webpage source code, CSS and interface data are displayed on it, which is messy and affects SEO. How to remove it? Please help me. Thanks.

Just like this：
![image](https://github.com/nuxt/nuxt/assets/74823392/bc06b2f1-412d-4716-8bea-5098c837db11)

![image](https://github.com/nuxt/nuxt/assets/74823392/424af1cb-d77d-43e3-b482-faee185aec40)
</div>

**Comment by danielroe** [comment]
This is not a bug; it is how data is sent from server to client on initial load.
