### ISSUE TITLE
Cannot find package knex on production build of nuxt server (api routes)

### ISSUE THREAD

**Issue by bvqbao** [nuxt/nuxt#22373]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@9.5.1
- Builder:          vite
- User Config:      devtools, modules, content, experimental
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @nuxt/content@2.7.2, @nuxtjs/eslint-module@4.1.0
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/bvqbao/nuxt3-module-notfound

### Describe the bug

I have created some API in ~/server/api. The API use knex package to access to an SQLite DB. 
In dev mode (```npm run dev```), the API work as expected:
<img width="281" alt="image" src="https://github.com/nuxt/nuxt/assets/4357219/a719d0fb-1aae-4a22-98a2-23d96428d26f">

However, when I build the server for production (```npm run build```)  and run the server (```npm run preview```), the server returns an error about "Cannot find package ..." knex, altho it is present in ```./output/server/node_modules```:
<img width="687" alt="image" src="https://github.com/nuxt/nuxt/assets/4357219/29d0c008-63bd-48a7-b42b-9c0b517da55c">

I don't use TypeScript but JavaScript in ~/server.

**Comment by danielroe** [comment]
Let's track in Nuxt in https://github.com/nuxt/nuxt/issues/22325
