### ISSUE TITLE
missing port when refresh page of .output/public by nuxt generate

### ISSUE THREAD

**Issue by axolo** [nuxt/nuxt#22370]
### Environment

- nuxt: 3.4.1
- centos: 7.6
- nginx: 1.23

### Reproduction

- nuxt generate
- deploy .output/public by nginx
- refresh page (F5)
- missing port (cannot open page) 
- but exclude home page

### Describe the bug

missing port when page refresh (F5) but exclude home page

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
