### ISSUE TITLE
Two active nuxt apps on the same page cause conflict

### ISSUE THREAD

**Issue by MiniDigger** [nuxt/nuxt#22376]
### Environment

```
RootDir: /project/home/minidigger/workspace/firstapp                                                                                          12:53:14 PM
Nuxt project info:                                                                                                                            12:53:14 PM

------------------------------
- Operating System: Linux
- Node Version:     v16.17.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Reproduction

have two nuxt apps: one inner, that has ssr: false, so is a SPA. the outer app then loads the inner app by fetching the content of the index.html and injecting it.

example: https://codesandbox.io/p/sandbox/boring-grass-j6ygnz?file=%2Fsecondapp%2Fnuxt.config.ts%3A6%2C1
fix hostname in secondapp/nuxt.config.ts and firstapp/app.vue
start the inner app
```
cd secondapp
yarn
yarn run generate
npx serve -l 3001 -C .output/public/
```
start outer app
```
cd firstapp
yarn
yarn run dev
```
observe 

### Describe the bug

when you have two active nuxt apps (one embedding the other) on one page, you get a "context conflict" error message:
```
entry.80784344.js:1  [nuxt] error caught during app initialization Error: Context conflict
    at checkConflict (index.mjs?v=789c7ae0:6:13)
    at Object.set (index.mjs?v=789c7ae0:40:9)
    at Va (entry.80784344.js:1:74365)
    at Object.runWithContext (entry.80784344.js:1:73028)
    at Ja (entry.80784344.js:1:73921)
    at Qa (entry.80784344.js:1:74076)
    at $s (entry.80784344.js:3:1497)
    at entry.80784344.js:3:1825
```

I would expect that the two nuxt apps can run isolated from each other.

### Additional context

I noticed this because I am in the process of updating my "inner app" to nuxt 3. it never was an issue with nuxt 2.

**Comment by danielroe** [comment]
This is planned but not supported yet.

Let's track in https://github.com/nuxt/nuxt/issues/21635

**Comment by bagaskarala** [comment]
any solution for this @danielroe ?

@MiniDigger i also facing this isssue, my current workaround is set `appId` to different value in nuxt config

**Comment by MiniDigger** [comment]
I removed nuxt from the inner app for now and will revisit it once #21635 is implemented

**Comment by bagaskarala** [comment]
> I removed nuxt from the inner app for now and will revisit it once #21635 is implemented

Yap its already works for my current case which is embedding static page built by Nuxt, into Nuxt universal app.

using this config
```
  appId: 'widget-app',
  future: {
    multiApp: true,
  },
```
