### ISSUE TITLE
Long startup time Nuxt - Tailwind

### ISSUE THREAD

**Issue by dirkcremers** [nuxt/nuxt#22387]
### Environment

Nuxt project info:                                                                                                      

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.14.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@9.4.0
- Builder:          vite
- User Config:      runtimeConfig, app, build, css, modules, postcss, typescript
- Runtime Modules:  @pinia/nuxt@0.4.11
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/dirkcremers/Codebreakers-app

Just a starting project with some packages installed to showcase the problem.

### Describe the bug

The startup time of my Nuxt app is significantly long. To identify the cause, I created a fresh project and installed packages one by one. After adding Tailwind, the project's loading time increased to 5 minutes.

Here are the logs of starting the development app:
ℹ Vite client warmed up in 21919ms 11:07:05
✔ Nitro built in 768 ms

Even for a newly created Nuxt project, it takes after the above message nearly 1 or 2 minutes to see the landing page, which seems much slower than expected. Additionally, when I created a larger project, the build time was approximately 50 minutes, and it took about 10 minutes to load the project with npm run dev.

I believe that such long loading times are not normal, and I expect the app to start up much faster, ideally within a few seconds.

**Comment by kaikaibenkai** [comment]
Use `@nuxtjs/tailwindcss` instead.

**Comment by aa22dev** [comment]
I encountered the same issue with nuxt3. I am using the docus template and have installed the required dependencies.
Here are my logs:
ℹ Vite client warmed up in 63851ms
✔ Nitro built in 7441 ms

npm run dev takes too long to build and load the website

**Comment by manniL** [comment]
@aa22dev do you use the tailwind module? Which OS do you use?

**Comment by mhdalik** [comment]
I have same issue with nuxt3  `@nuxtjs/tailwindcss`. it takes around 12 seconds to restart development server, and not loading layouts without restarting development server. So totally its wasting more minutes.

**Comment by snowdream** [comment]
too slow for dev building.

```
Nuxi 3.6.5                                                                                                                         08:55:06
Nuxt 3.6.5 with Nitro 2.6.0                                                                                                        08:55:06
                                                                                                                                   08:55:11

                                                                                                                                   08:55:35

 WARN  warning:                                                                                                                    08:55:35
D:/workspace/go/src/snowdream.tech/vue-nuxt-element-template/components/Sidebar.vue
10 |  import { useAppStore } from "@/stores/app";
11 |  import { useSettingsStore } from "@/stores/settings";
12 |  import variables from "@/styles/variables.scss";
   |                         ^                                                                                                     08:55:35  
13 |  const _sfc_main = /* @__PURE__ */ _defineComponent({
14 |    __name: "Sidebar",
Default and named imports from CSS files are deprecated. Use the ?inline query instead. For example: import variables from "@/styles/variables.scss?inline"
  Plugin: vite:import-analysis
  File: D:/workspace/go/src/snowdream.tech/vue-nuxt-element-template/components/Sidebar.vue

✔ Nitro built in 51288 ms                                                                                                   nitro 08:56:35
ℹ ✨ new dependencies optimized: msw/node                                                                                         08:56:37
ℹ ✨ optimized dependencies changed. reloading                                                                                    08:56:37
ℹ Vite client warmed up in 71019ms                                                                                                08:56:38

```

**Comment by adiramardiani** [comment]
I don't know this issue is related to tailwind or not
But is *CRAZY* slooow now :(

![image](https://github.com/nuxt/nuxt/assets/8703419/e8709431-100e-4fbf-941c-adca63204327)

Just wait 3 minute for nitro built :(

**Comment by danielroe** [comment]
@adiramardiani I think it's an issue we're resolving in https://github.com/nuxt/cli rather than directly related to this issue. Check the issues in that repo and try the latest version of nuxt/nuxi to confirm. Any reproduction would also be very welcome.

**Comment by fabiovaz** [comment]
@adiramardiani try using 127.0.0.1:3000 insted localhost:3000

**Comment by aminshafieed** [comment]
I have same issue with nuxt3(3.12.4) @nuxtjs/tailwindcss. it takes around 20 seconds to restart development server, and also when i change even a text in my project, tailwind hot reloaded too and it causes HMR take more than 15 seconds.

![Screenshot from 2024-08-16 16-55-41](https://github.com/user-attachments/assets/046d31b5-2af3-477c-bbae-0bd7bed37d1b)
