### ISSUE TITLE
Error when upgrading to Nuxt 3.6.5: The argument 'path' must be a string or Uint8Array without null bytes. 

### ISSUE THREAD

**Issue by ivan-angjelkoski** [nuxt/nuxt#22380]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v16.20.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      vite, hooks, ssr, builder, debug, spaLoadingTemplate, app, imports, pinia, css, modules, bugsnag, plugins, typescript, sourcemap
- Runtime Modules:  @pinia/nuxt@0.4.11, @nuxtjs/i18n@8.0.0-beta.13, @vueuse/nuxt@10.2.1, @nuxt/devtools@0.7.1, @nuxtjs/tailwindcss@6.8.0, @injectivelabs/ui-shared@1.12.12
- Build Modules:    -
------------------------------

### Reproduction

happened after upgrading my project to nuxt 3.6.5

### Describe the bug

Started received the following error after upgrading nuxt.

<img width="1380" alt="image" src="https://github.com/nuxt/nuxt/assets/56976418/fa4cfe60-1dc2-47ab-b42d-e879efa6b705">

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
