### ISSUE TITLE
 Server API routes wrongfully respond 404 when they should respond 405

### ISSUE THREAD

**Issue by notKamui** [nuxt/nuxt#22382]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.14.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.6.9
- Builder:          vite
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://codesandbox.io/p/sandbox/snowy-feather-2khgvy

`server/api/test.get.ts` file with the following content:

```ts
export default defineEventHandler(() => {
    return { message: 'Hello World' }
})
```

### Describe the bug

> TLDR; `POST /api/test` responds 404 instead of 405

As per the documentation says in the "[Maching HTTP Method](https://nuxt.com/docs/guide/directory-structure/server#matching-http-method)" section of the `/server` directory, if a file `/server/api/test.get.ts` exists (and no other corresponding files for the other methods), then GETting to that enpoint should work fine, and requesting with any other method should respond 405 Method Not Allowed (this is the correct semantic behavior).

However, that is not the current behavior : POSTing to that endpoint always result in a `404 Not Found (Cannot find any path matching /api/test. (/api/test))`, which is wrong.

**Comment by Hebilicious** [comment]
@danielroe is there a problem with the upstream issue bot?

**Comment by pi0** [comment]
~> https://github.com/unjs/nitro/issues/1503 (@Hebilicious please use nitro minimal reproductions to report upstream issues 🙏🏼 )

**Comment by pi0** [comment]
~> https://github.com/unjs/nitro/issues/1503 (@Hebilicious please use nitro minimal reproductions to report upstream issues 🙏🏼 )

**Comment by danielroe** [comment]
Closing as this should be resolved in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/), and in the next release of Nitro.
