### ISSUE TITLE
Manually typing Runtime Config doesn't work as described in the docs

### ISSUE THREAD

**Issue by DawidKopys** [nuxt/nuxt#22392]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.6.5`
- Nitro Version:    `2.5.2`
- Package Manager:  `npm@9.5.1`
- Builder:          `vite`
- User Config:      `typescript`, `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

1. clone repo https://github.com/DawidKopys/nuxt-extending-runtime-config
2. run `npm i`
3. run type tests with `npm run typecheck`

The test will fail with error message:
```
 FAIL  tests/runtime-config.test-d.ts > runtime configuration can be extended
TypeCheckError: Argument of type 'unknown' is not assignable to parameter of type 'string'.
 ❯ tests/runtime-config.test-d.ts:9:22
      7|   assertType<string>(config.apiSecret)
      8|   assertType<string>(config.public.apiBaseButItWorks)
      9|   assertType<string>(config.public.apiBase)
       |                      ^
     10| })
     11|
```

### Describe the bug

According to [Nuxt 3 docs](https://nuxt.com/docs/guide/going-further/runtime-config#manually-typing-runtime-config), runtime config can be typed manually as below:

```
declare module 'nuxt/schema' {
  interface RuntimeConfig {
    apiSecret: string
    public: {
      apiBase: string
    }
  }
}

export {}
```
... but the "public" part doesn't work.

**Comment by arily** [comment]
Hi, I am wondering where should I put this index.d.ts? I tried place it in root folder as well as src/ (I have `srcDir: 'src/',`) in my Nuxt config.
