### ISSUE TITLE
Using @nuxt/devtools causes the page route: /pages/app/index.vue to return code

### ISSUE THREAD

**Issue by shanehoban** [nuxt/nuxt#22395]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.16.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@9.6.7
- Builder:          vite
- User Config:      modules, alias, typescript
- Runtime Modules:  @pinia/nuxt@0.4.11, @nuxtjs/tailwindcss@6.8.0, @nuxtjs/supabase@0.3.8
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-lzr81f?file=pages%2Fapp%2Findex.vue

### Describe the bug

Using @nuxt/devtools causes the page route: /pages/app/index.vue to return code. So by navigating to `/app` - interestingly, navigating to `/app/` has no issue.

Disabling the plugin resolves the issue (removing it from nuxt config).

**Comment by danielroe** [comment]
cc: @antfu

**Comment by antfu** [comment]
Fixed in DevTools v0.7.3
