### ISSUE TITLE
Scroll to top is not triggered on routes with the same component.

### ISSUE THREAD

**Issue by huang-julien** [nuxt/nuxt#22402]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.3.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.6.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-ajsbck?file=modules%2Frouting%2F[id].vue

### Describe the bug

- click on `to /hey`
- scroll down
- click alternatively on `to /toto` and `to /tata`
- you'll see that the page isn't scrolled to top

**Comment by danielroe** [comment]
Linked: https://github.com/nuxt/nuxt/issues/21991
