### ISSUE TITLE
ERROR bundle import should be a function when using { runInNewContext: false }.

### ISSUE THREAD

**Issue by shaobeichen** [nuxt/nuxt#22406]
### Environment

  System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 4.63 GB / 15.88 GB
  Binaries:
    Node: 16.13.1 - D:\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.7.1 - ~\AppData\Roaming\npm\npm.CMD
    pnpm: 7.9.5 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.1992.0), Chromium (115.0.1901.188)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    nuxt: 2.15.4 => 2.15.4

### Reproduction

I didn't reproduce the content because it appeared in the logs on the server, and I didn't find the same situation locally. I don't know where to start looking for the problem now, so I have no clue, or can you give me a general direction for solving it?

### Describe the bug

refresh the page for 2-3 times and check server logs:

ERROR  i is not a function
at node_modules/vue-server-renderer/build.prod.js:1:78890
at new Promise (<anonymous>)
at node_modules/vue-server-renderer/build.prod.js:1:78362
at Object.renderToString (node_modules/vue-server-renderer/build.prod.js:1:81897)
at SSRRenderer.render (node_modules/@nuxt/vue-renderer/dist/vue-renderer.js:353:38)

Now as long as the page is refreshed, the Server log will have an ERROR i is not a function. We find the earliest error before that is ERROR bundle export should be a function when using {runInNewContext: false}.

We have checked the previous issues and have not found any methods to try.

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
