### ISSUE TITLE
useFetch dosn't work on initial page load

### ISSUE THREAD

**Issue by baermathias** [nuxt/nuxt#22401]
### Environment

```bash
- Operating System: Linux
- Node Version:     v16.15.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@8.5.5
- Builder:          vite
- User Config:      app, typescript, ssr, css, build, vue, vite, modules, snipcart, plugins, components, runtimeConfig, sourcemap
- Runtime Modules:  @nuxtjs/snipcart@2.0.2
- Build Modules:    -

```

### Reproduction

I don't have a reproduction link, but below is a simple code snippet of what I do inside `pages/index.vue`. I also tried `cache: 'no-cache'` or setting a key `key: String(Math.random),`, none of this worked for me. But I remember, that this used to work in a previous version, where you had the option `initialCache: false`:
```ts
<script setup lang="ts">
const runtimeConfig = useRuntimeConfig()
const { data: restaurants, pending, refresh, error } = await useFetch<APIBody>(
  () => `api/restaurant-infos?populate=*`,
  { 
    key: String(Math.random),
    method: 'get',
    baseURL: runtimeConfig.public.API_BASE_URL,
    cache: 'no-cache',
    // initialCache: false <-- used to work with this option, which was available in a previous version
  }
)
</script>
```

### Describe the bug

I am loading some data on my home page vie `useFetch`, which does not work on initial page load. 
Only if you navigate from another page to the home page or if you set `ssr: false`.

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by baermathias** [comment]
I tried, but somehow the minimal reproduction templates don't work for me. 
`codesandbox` looks like this from the beginning (with Brave and Firefox):

![Screenshot from 2023-07-30 23-50-46](https://github.com/nuxt/nuxt/assets/45003352/f172b0dc-3e6e-4c80-93e8-91515c1c3688)

And on `stackblitz` I always get the warning `page-placeholder.js:7 Create a Vue component in the pages/ directory to enable <NuxtPage>`, even if I have created a pages folder with multiple components in it: https://stackblitz.com/edit/github-xcw7lm?file=components%2FTopNav.vue

**Comment by danielroe** [comment]
Apologies - Codesandbox seems not to be in sync with our `v3-codesandbox` branch. We've asked the team there to look into it.

For stackblitz, the link you shared seems to work for me ... maybe try reopening it?

**Comment by baermathias** [comment]
It seems to work again, I am closing this for now. Thank you.

**Comment by raftx24** [comment]
@danielroe 
```
- Operating System: Mac
- Node Version:     v20.6.1
- Nuxt Version:     3.7.1
- Nitro Version:    2.6.3
- Package Manager:  npm@9.8.1
```
I am encountering the exact same issue and it can be reproduced with ease.

```vue
<script setup lang="ts">
const route = useRoute()

onMounted(async () => {
  console.log(route.params.id)
  const {data, status, pending} = await useMyFetch(`/api/resume/${route.params.id}`, {
    method: 'GET',
  });

  console.log('response', data.value);
  console.log('status', status.value);
  console.log('pending', pending.value);
})
</script>

<template>
  <div>
  </div>
</template>
```

**Comment by danielroe** [comment]
You should not call useFetch in mounted. It should be called in the setup function

**Comment by undevweb** [comment]
I have the same issue at the first load of a page. What is the setup function in a composition api mode ? I thought it was just the fact to be in <script setup lang="ts">...</script>

**Comment by danielroe** [comment]
`<script setup>` or in `<script>export default defineComponent({ script () { /* here */ } })`

**Comment by undevweb** [comment]
Well, that's what I do but I got the problem

`
<template>
  <div v-if="userStore.user">
    <h1>OKAY USER IS HERE</h1>
    <PagesRoomsList />
  </div>
</template>
<script setup lang="ts">
import { useUserStore } from '~/stores/user.store';
const userStore = useUserStore();
onMounted(async () => {
  await userStore.fetchUser();
});
</script>
`

At the first load the ajax return null, if I navigate and back to this page inside the app that works but if I do f5 that doesn't work
I tried here with onMounted but it does the same

**Comment by antonreshetov** [comment]
Same issue. If set `server: false`, everything works, but not as desired. The desired result is to expect the request to be executed and only then the page is rendered on the first load.

**Comment by AK-digital** [comment]
Same issue here.

**Comment by axel-paillaud** [comment]
Same issue here: work with `server: false`, but seems to fetch asynchronously every time

**Comment by ChamkhiAnas** [comment]
any solution to this im facing the same problem 

useFetch works fine with internal navigation from app but the page crash when trying to access it from direct url or when i refresh the page

**Comment by danielroe** [comment]
If you are encountering this issue, please open a new issue with a reproduction 🙏

If the page crashes when accessing it from direct URL I would guess that you have a connectivity issue between your server-side and your API.
