### ISSUE TITLE
Can i simultaneous use ssr and ssg in nuxt3.我可以同时使用ssr和ssg吗

### ISSUE THREAD

**Issue by lz6060788** [nuxt/nuxt#22407]
### Describe the feature

I dont know how to simultaneous use ssr and ssg. In my project, some page need ssg, and some page need ssr. I overviewed docs, bug cant find some infomation useful. Then i try Configure `nitro.prerender` and excuted `npm run generate`, after that i excuted `npm run build` and start nuxt server. I found, after `npm run generate`, some static files like html、js and css were created in **/dist**, but after `npm run build`, them were overwrited. How can I resolve this problem.
我想要在项目中实现一部分页面使用ssr渲染，一部分页面做ssg静态化，我可以实现这样的配置吗（这里还有另一个问题，我发现我配置nitro.prerender没有生效，它会给我所有页面都执行静态化操作，了解的兄弟说下可能是啥原因），我发现我生成静态站点之后如果再npm run build再进行打包，会把原来静态化出来的静态文件给覆盖。

![IMG_20230731_140327](https://github.com/nuxt/nuxt/assets/98386138/2eb313e2-2f95-4089-8902-55d7b491a72a)
In my case, `/view/article`, `/view/community` and  `/view/dataplatform`, these pages or there subpages need ssr, and others need ssg. Does Nuxt3 support it? Or How I can configure it.
 `/view/article`, `/view/community` and  `/view/dataplatform`这些页面及其子页面我想实现ssr渲染，但是其他页面我希望实现ssg静态化，我应该如何配置...nuxt3支持这么干吗...，我这么配置`npm run generate`给我静态化了所有页面(`nitro.prerender`未生效)，然后出现了一堆接口访问错误，这个有老哥知道哪里配置错了吗

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
Pre-rendering should happen when building your application via `nuxt build`.

<img width="829" alt="image" src="https://github.com/nuxt/nuxt/assets/640208/40de06cb-8c66-4cdf-b4d4-96f563c6d287">

(Config:)

```ts
export default defineNuxtConfig({
  nitro: {
    prerender: {
      routes: ['/a', '/b']
    }
  }
})
```
