### ISSUE TITLE
How i can create loader page custom in nuxt3 ?

### ISSUE THREAD

**Issue by Ibrahimmousa1999** [nuxt/nuxt#22411]
### Environment

const nuxtApp = useNuxtApp();
const loading = ref(true);
nuxtApp.callHook("page:start").then(() => {
  console.log('page:start');
  loading.value = true;
});
nuxtApp.callHook("page:finish").then(() => {
  console.log('page:finish');
  loading.value = false;
});
<template>
    <Loader v-if="loading" />
</template>

### Reproduction

const nuxtApp = useNuxtApp();
const loading = ref(true);
nuxtApp.callHook("page:start").then(() => {
  console.log('page:start');
  loading.value = true;
});
nuxtApp.callHook("page:finish").then(() => {
  console.log('page:finish');
  loading.value = false;
});
<template>
    <Loader v-if="loading" />
</template>

### Describe the bug

const nuxtApp = useNuxtApp();
const loading = ref(true);
nuxtApp.callHook("page:start").then(() => {
  console.log('page:start');
  loading.value = true;
});
nuxtApp.callHook("page:finish").then(() => {
  console.log('page:finish');
  loading.value = false;
});
<template>
    <Loader v-if="loading" />
</template>

### Additional context

const nuxtApp = useNuxtApp();
const loading = ref(true);
nuxtApp.callHook("page:start").then(() => {
  console.log('page:start');
  loading.value = true;
});
nuxtApp.callHook("page:finish").then(() => {
  console.log('page:finish');
  loading.value = false;
});
<template>
    <Loader v-if="loading" />
</template>

### Logs

```shell-script
const nuxtApp = useNuxtApp();
const loading = ref(true);
nuxtApp.callHook("page:start").then(() => {
  console.log('page:start');
  loading.value = true;
});
nuxtApp.callHook("page:finish").then(() => {
  console.log('page:finish');
  loading.value = false;
});
<template>
    <Loader v-if="loading" />
</template>
```

**Comment by danielroe** [comment]
Check out https://nuxt.com/docs/api/components/nuxt-loading-indicator#nuxtloadingindicator
