### ISSUE TITLE
Plugin Registration Order with layers

### ISSUE THREAD

**Issue by derHodrig** [nuxt/nuxt#22414]
## The Environment
3 layers
1. @nuxt-themes/docus
2. @q-soft/qs-docu-tool (with i18n, vuetify, mermaid and stuff)
3. app layer > the app you are working on

![image](https://github.com/nuxt/nuxt/assets/53934248/714a2eba-eb31-4b7a-85b3-0273f31666d6)

Clarification about layers shown in the image
-  `@q-soft/qs-docu-tool` extends from `@nuxt-themes/docus`, 
- the app extends from `@q-soft/qs-docu-tool`

## the challenge
I want to access i18n in my plugin carousel of the app layer. I cant, since the plugins of @q-soft/qs-docu-tool are loaded afterward.

I tried both,
setup plugins just by name and with number prefix. The plugins of the base/extended layer got loaded AFTER the app layer.
(please help me with the naming convention of the layers)

## Expected

Load plugins of docus first, then @q-soft/qs-docu-tool and at last app layer plugins. In that case I could use i18n in my carousel plugin, since its loaded before.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by AndrewBogdanovTSS** [comment]
Hi @danielroe, any updates on this issue?

**Comment by userquin** [comment]
a simple workaround is to use object notation with `enforce: 'post'` in the carousel plugin: https://github.com/userquin/vuetify-nuxt-module/blob/main/src/runtime/plugins/vuetify.ts#L5-L11

**Comment by AndrewBogdanovTSS** [comment]
@danielroe why this was closed? What @userquin provided as a workaround might somehow work for his use case of 1 plugin but definitely not a solution (not even a workaround) for the problem in general. Layers have sequential order, why plugins which are arrays don't? If we need a more general issue to be opened for it let me know, otherwise let's reopen this one

**Comment by danielroe** [comment]
@AndrewBogdanovTSS This was closed because plugin ordering was resolved in https://github.com/nuxt/nuxt/pull/22889. If you still have an issue, then yes, please do open a new issue.

**Comment by AndrewBogdanovTSS** [comment]
@danielroe I just checked the issue on 3.7.1 and it still exists, here is a reproduction https://stackblitz.com/edit/nuxt-starter-g42wkd?file=nuxt.config.ts
Issue will be opened shortly
