### ISSUE TITLE
Treeshaking issue with conflicting enum value and type name

### ISSUE THREAD

**Issue by art-boer** [nuxt/nuxt#22416]
### Environment

Any environment with vite and latest nuxt version, see default sandbox repro

### Reproduction

https://codesandbox.io/p/sandbox/damp-cache-4fvnwg?file=%2Fapp.vue%3A4%2C1

### Describe the bug

Possible treeshaking issue?

If you are importing a type and use an enum value that has a conflicting name within a component, the export of the type seems to be broken.

```
<template>
  <div>
   {{TestEnum.**Test**}}
  </div>
</template>
import {**Test**, TestEnum} from 'test.ts';

defineProps<{
  test: Test[]
}>();
```
Given error:
```
The requested module '/_nuxt/test.ts' does not provide an export named 'Test'
```

**Comment by ah-dc** [comment]
this is a bug of vue, i will create a pr to fix it later
