### ISSUE TITLE
Nuxt 3.6.5: Build fails if any asset link is dynamically imported from a function in the `utils` folder when there's a CSS file that starts with "@"

### ISSUE THREAD

**Issue by alex-eliot** [nuxt/nuxt#22427]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.17.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://codesandbox.io/p/sandbox/festive-satoshi-qk263h?file=%2Fapp.vue%3A12%2C1

### Describe the bug

I'm using this handy function to dynamically get asset links:

```typescript
// utils/functions.ts
export function getAbsoluteAssetLink(path: string) {
  // https://stackoverflow.com/questions/69696677/vite-vue-3-require-is-not-defined-when-using-image-source-as-props
  return new URL(`../assets/${path}`, import.meta.url).href;
}
```

And getting asset links in a script setup:
```typescript
// app.vue
<script setup lang="ts">
import { getAbsoluteAssetLink } from "./utils/functions";

// If this function is called at least once, build fails
// comment it out and build succeeds!
getAbsoluteAssetLink("css/test.css");
</script>
```

The error thrown is:
```
[10:48:39 AM]  ERROR  Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)
file: /project/home/alex-eliot/workspace/assets/css/fonts/poppins.css?url?inline&used:1:0
1: @font-face {
   ^
2:   font-display: swap;
3:   font-family: "Poppins";


[10:48:39 AM]  ERROR  Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)

  at error (node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:2124:30)
  at Module.error (node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:13463:16)
  at Module.tryParse (node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:14184:25)
  at Module.setSource (node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:13786:39)
  at ModuleLoader.addModuleSource (node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:23782:20)

error Command failed with exit code 1.
```

This has worked well on Nuxt 3.5.3. On a chore routine to upgrade to Nuxt 3.6.5, this issue has prevented building the frontend. So I'm unsure which version exactly was where it started being an issue. Please note that this function **has** to exist in the `utils` folder. If we declare that function directly in the script setup, the build succeeds.

```typescript
// app.vue
<script setup lang="ts">
function getAbsoluteAssetLink(path: string) {
  return new URL(`./assets/${path}`, import.meta.url).href;
}

// Build succeeds
getAbsoluteAssetLink("css/test.css");
</script>
```

Using the URL directly works as well:
```typescript
// app.vue
<script setup lang="ts">
// Build succeeds
new URL(`./assets/test.css`, import.meta.url).href;
</script>
```

**Comment by alex-eliot** [comment]
Apparently this method is absolutely insecure though! In case of an SSR application, in the server the URL in the assets link is a relative filepath to the assets, which if passed to the rendered HTML can reveal folder structure of the server it's running on.

I don't know how bugs caused by bad practices are treated here so I'll leave this open and leave the decision to you. I learned the security issues with this the hard way so I recommend other people to avoid doing it.

**Comment by juancampuzano** [comment]
Hi guys! I am having the exact same issue. @alex-eliot  you tell us here that this way is insecure. Could you kindly tell us which is the right way to do the same in Nuxt then?

**Comment by alex-eliot** [comment]
@juancampuzano Sure. In my case I wanted to fetch some images from the assets directory. Since it was nothing really simple, and stuff in the assets/ directory is already available publicly under /_nuxt/*, so I just moved them to public/ directory and used that instead.

**Comment by juancampuzano** [comment]
@alex-eliot Thank you. I ended with the same conclusion after reading this [related issue](https://github.com/nuxt/nuxt/issues/14766#issuecomment-1757796772).

**Comment by danielroe** [comment]
This is a vite issue. Vite is trying to dynamically bundle those files, and it is assuming it's JS.

Change it to this and it should work:

```ts
export function getAbsoluteAssetLink(path: string) {
  return new URL(`../assets/${path}.css`, import.meta.url).href;
}
```
