### ISSUE TITLE
<NuxtPage /> with index.vue issue

### ISSUE THREAD

**Issue by Riadz** [nuxt/nuxt#22426]
### Describe the feature

Currently for nest routes if we have a page (`/parent/index.vue`) with `<NuxtPage />` and a child page (`/parent/child.vue`) on the same level as the parent,  `<NuxtPage />` doesn't render the child pages's content.
![2023-08-01 10_58_56-Window](https://github.com/nuxt/nuxt/assets/46753769/9e72b713-7549-4f91-8622-3a2e17abe199)

From the docs i have to make it `parent.vue` outside the `parent` folder.
![2023-08-01 10_33_46-Window](https://github.com/nuxt/nuxt/assets/46753769/44cde9c0-c032-4f6c-9e49-5b00d7017ef4)

In our project we have many pages and we have a folder structure where we separated the style from the template, example:
![2023-08-01 10_49_17-Window](https://github.com/nuxt/nuxt/assets/46753769/e0a25210-a858-4b6c-aebf-f36735b2c59a)

so jumping between the `parent.vue` file all the way to the child folder then the `child.vue` file is a bit of a bother 
it would be great if the above scenario with the `index.vue` as a parent would work 🙏

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
This is deliberate, because there are scenarios when you _don't_ want nested routes, and `parent/index.vue` is the way to make this happen.

Note that you can manipulate routes with the `pages:extend` hook if you want to customise things: https://nuxt.com/docs/guide/going-further/custom-routing#adding-custom-routes
