### ISSUE TITLE
Nuxt Transitions: Failed to execute 'insertBefore' on 'Node'

### ISSUE THREAD

**Issue by AT-Lorlando** [nuxt/nuxt#22438]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v16.16.0
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.1
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      app, srcDir, modules, css, build, content
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @nuxt/content@2.7.0, @pinia/nuxt@0.4.11
- Build Modules:    -
------------------------------

### Reproduction

Stackblitz reproduction: https://stackblitz.com/edit/nuxt-starter-muq6pj?file=pages%2Findex.vue

##### Header Component:
This provides links to navigate between the two pages, `hello` and `index`.

##### Default Layout:
It wraps around the page content and includes the `Header` component.

##### Pages:

`hello`: A simple component displaying "Hello world".
`index`: The main component displaying "index".

##### App Component:
This sets the page transition style using CSS classes like `.fade-enter-active` and `.fade-leave-active`.

##### Nuxt Configuration:
The  `nuxt.config` file has the transition configuration set to a fade effect with a mode of 'out-in'.

### Describe the bug

In this repository, we're encountering a specific error in a Nuxt application when rapidly switching between pages during a transition:

*Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.*

The error is attributed to the interaction between Nuxt's page transitions and the rapid toggling between components.

### Additional context

Vue.js, which is the foundation of Nuxt.js, updates the DOM in response to data changes. Transitions are a way to interpolate these DOM changes smoothly for better user experience.

The 'out-in' mode specified in our transitions means that the old page will finish its transition out before the new page starts transitioning in. This synchronous behavior becomes problematic when we rapidly switch between pages. Vue might still be in the process of removing the old page from the DOM when we attempt to insert the new page, leading to the observed DOMException.

### Logs

```shell-script
Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
at insert (...)
    at move (...)
    at move (...)
    at move (...)
    at activeBranch.transition.afterLeave (...)
    at performRemove (...)
    at el._leaveCb (...)
    at finishLeave (...)
    at resolve2 (...)
    at whenTransitionEnds (...)
```

**Comment by danielroe** [comment]
This is an upstream Vue bug which we're tracking in this repository in https://github.com/nuxt/nuxt/issues/13350.
