### ISSUE TITLE
useRoute watcher does not trigger on route change

### ISSUE THREAD

**Issue by chunglam2525** [nuxt/nuxt#22443]
### Environment

Operating System: MacOS
Node Version: v16.17.0
Nuxt Version: 3.6.5
Nitro Version: 2.5.2
Package Manager: -
Builder: vite
User Config: -
Runtime Modules: -
Build Modules: -

### Reproduction

https://stackblitz.com/edit/github-6hjnum-2idhxd?file=app.vue

### Describe the bug

```
const route = useRoute();
watch(route, (to, from) => {
    // do something when route changes
}, { immediate: true });
```

I used to able to watch for route changes with this watcher function. After upgrade to nuxt v3.6.5, it does not work anymore.
Not sure if it is intended or a bug cause I cant find anyone talking about this issue.

**Comment by danielroe** [comment]
This is a change in nuxt _and_ in vue router, for performance reasons. Now, instead of watching `route`, you can use a getter to watch a route property, like this:

```ts
watch(() => route.fullPath, path => {
  // ...
})
```

**Comment by marr** [comment]
Note that the above comment helped me address an issue I was seeing accessing route.params.  For some reason they were coming through as undefined. I had to convert:

```
const route = useRoute();
const { item } = route.params;
const menuItems = ref([
  {
    title: 'Settings',
    to: `/items/${item}/settings`,
  },
]);
```
to this:
```
const route = useRoute();
const menuItems = computed(() => [{
    title: 'Settings',
    to: `/items/${route.params.item}/settings`,
  },
]);
```
