### ISSUE TITLE
UseHead title is not updated when page is activated, title of page only get updated when page is mounted

### ISSUE THREAD

**Issue by devbinyameen** [nuxt/nuxt#22450]
### Environment

"nuxt": "^3.2.0"

### Reproduction

I've created a small application that is just a teaser of this error:

https://codesandbox.io/p/sandbox/nifty-http-tdnft3

### Describe the bug

I am using useHead for updating title in pages, titles are updating on mounting of pages  but when I revisit pages, title of page doesn't get updated.
In short useHead is updating title on mounted and is not updating on activated hook.

**Comment by alederzz** [comment]
Use 

```
useHead({
  title: () => 'My title'
})
```

[Unhead Watch](https://unhead.harlanzw.com/integrations/vue/reactivity#best-practices)

**Comment by devbinyameen** [comment]
> Use
> 
> ```
> useHead({
>   title: () => 'My title'
> })
> ```
> 
> [Unhead Watch](https://unhead.harlanzw.com/integrations/vue/reactivity#best-practices)

Still Its not working.

**Comment by manniL** [comment]
Can't reproduce.
[use-head-cant-repro.webm](https://github.com/nuxt/nuxt/assets/640208/a0899d3c-4835-4da1-9f96-f0b878771b9b)

**Comment by devbinyameen** [comment]
> Can't reproduce. [use-head-cant-repro.webm](https://github.com/nuxt/nuxt/assets/640208/a0899d3c-4835-4da1-9f96-f0b878771b9b)

I am using nuxt 3.0 version while the version on link in 3.2

**Comment by danielroe** [comment]
In that case, this is likely an old bug that has since been fixed.

**Comment by devbinyameen** [comment]
> In that case, this is likely an old bug that has since been fixed.

I have checked this and it's fixed in nuxt 3.2, thanks @danielroe
