### ISSUE TITLE
Reproduction templates don't work anymore

### ISSUE THREAD

**Issue by KamilBeda** [nuxt/nuxt#22451]
### Environment

N/A

### Reproduction

Stackblitz:
1. Use [reproduction link provided by issue template](https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz?file=README.md)
2. Template fails at executing `npm install` - `The requested module '@vue-macros/common' does not provide an export named 'getTransformResult' `

Codesandbox:
1. Use [reproduction link provided by issue template](https://codesandbox.io/s/github/nuxt/starter/v3-codesandbox)
2. Fork it
3. Nuxt won't start and website preview shows `504 Gateway Timeout`

### Describe the bug

Reproduction templates don't work anymore

**Comment by danielroe** [comment]
This is coming from a dependency of `unplugin-vue-router` (`@vue-macros/common`) which dropped that export. However, it has just released 1.6.2 to fix this bug: https://github.com/vue-macros/vue-macros/commit/0a1cbf796f00e774ba48ff019fec0e008e311faa.

It might take a moment for the stackblitz template to update the cache, or you can manually do it by running `npm up` in the stackblitz terminal.
