### ISSUE TITLE
Production build with parallel runner

### ISSUE THREAD

**Issue by arkhamvm** [nuxt/nuxt#22456]
### Describe the feature

Hello. IDK why, but production build works only in sequence runner:

```
const runner = options.dev ? utils.parallel : utils.sequence;
await runner(this.compilers, (compiler) => this.webpackCompile(compiler));
```

Only option that can change `runner` is `dev`.
So, why it works only in sequence mode? 
In my project it means that build time increase from 5 to 15 minutes (5 min. client + 5 min. modern + 5 min. server).

It would be nice to configure it somehow (e.g. `prodParallelBuild` option).

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
