### ISSUE TITLE
Dynamic Routes not working when deployed via npm run generate 

### ISSUE THREAD

**Issue by debayan-ghosh** [nuxt/nuxt#22453]
### Environment

Deployed to GCP

### Reproduction

Hi I have a pages/user.vue and a pages/user/[Id].Vue..when I try in local everything works fine and it is available and goes to /user/1 page. After I npm run generate and deploy it in server I open this page and it gives 404..how to solve this? I can't keep generating the file all time as an user gets created from backend. I am using nuxt3

### Describe the bug

Hi I have a pages/user.vue and a pages/user/[Id].Vue..when I try in local everything works fine and it is available and goes to /user/1 page. After I npm run generate and deploy it in server I open this page and it gives 404..how to solve this? I can't keep generating the file all time as an user gets created from backend. I am using nuxt3

**Comment by danielroe** [comment]
You need to point GCP to return `/200.html` or `/404.html` when someone requests a route that doesn't exist. Different providers have different ways of doing this.

**Comment by debayan-ghosh** [comment]
Can you please share me a example I really need help in this

**Comment by vietanhbui** [comment]
+1

**Comment by Iterator98** [comment]
> @debayan-ghosh This is to do with how static hosts work. If you get a request for a page that isn't rendered, you need to return a 'fallback' page that will render the page on the client instead (using dynamic routing).
> 
> The page might not be prerendered for a lot of reasons.

How do we do that?

**Comment by Iterator98** [comment]
Sorry, but this is still unclear. 

E.g. /page/[username]

When using pnpm dev on localhost, my dynamic page is rendered perfectly fine. 

When using pnpm build on a vps, I get 404. 

How can I achieve that it's shown after deployment.

**Comment by manniL** [comment]
@Iterator98  You can e.g. set the ErrorDocument or your NGINX/APACHE to the 404.html or 200.html of the generated output

**Comment by appscbelgirasol** [comment]
> Sorry, but this is still unclear.
> 
> E.g. /page/[username]
> 
> When using pnpm dev on localhost, my dynamic page is rendered perfectly fine.
> 
> When using pnpm build on a vps, I get 404.
> 
> How can I achieve that it's shown after deployment.

Any solution? Same problem here!
