### ISSUE TITLE
Nuxt 3 video.js support 

### ISSUE THREAD

**Issue by ks-neerajn** [nuxt/nuxt#22462]
### Environment

nuxt 3 fresh project where videos stored in assets/video/**.mp4

### Reproduction

install video.js and follow this setup https://stackoverflow.com/questions/73961731/import-video-js-into-nuxt-js-application-not-working

### Describe the bug

I'm not able to find how to use link in video src that comes from props and use like dynamically.

### Additional context

I want a way that I can use nuxt 3 assets folder file dynamically to play a video from video js.

I used some thins like this:

`const videosImport = import.meta.glob("@/assets/**/**.mp4");

--------------------

sources: [{
      src: videosImport["/assets/video/publish.mp4"],
      type: "video/mp4",

}]

`

After that also I'm getting the error like video file is not readable by the module

**Comment by danielroe** [comment]
See https://vitejs.dev/guide/features.html#glob-import.

We can track improving this in Nuxt in https://github.com/nuxt/nuxt/issues/14766.
