### ISSUE TITLE
Nuxt 3 nitro build fails with `Cannot read properties of undefined (reading 'pkgName') `

### ISSUE THREAD

**Issue by ChrisBellew** [nuxt/nuxt#22466]
### Environment

For some reason having `tsoa`, `node-ical` and `axios` in an api route causes a nuxt3 build to fail when building the nitro server. See minimal reproduction repo below.

### Reproduction

https://github.com/ChrisBellew/nuxt-bug-minimal-reproduction

### Describe the bug

When you run `npm run build` vite succeeds but nitro fails with

```
ERROR  TypeError: Cannot read properties of undefined (reading 'pkgName') 
```

See full error message on the README.md of the reproduction repo above.

**Comment by danielroe** [comment]
This is likely an upstream nitro issue, possibly from the tracing behaviour starting at these lines: https://github.com/unjs/nitro/blob/f12b38e8a50d83edc4ed1271f434c7289e635bb9/src/rollup/plugins/externals.ts#L258-L261.

**Comment by ChrisBellew** [comment]
> This is likely an upstream nitro issue, possibly from the tracing behaviour starting at these lines: https://github.com/unjs/nitro/blob/f12b38e8a50d83edc4ed1271f434c7289e635bb9/src/rollup/plugins/externals.ts#L258-L261.

Yes, those lines appeared to be culprit when I navigated into my `nitro.7a525996.mjs` at the reported location.

**Comment by danielroe** [comment]
cc: @pi0
