### ISSUE TITLE
Build Command does not create files in the .output.public._nuxt directory. ( with rollup options )

### ISSUE THREAD

**Issue by kyejune** [nuxt/nuxt#22464]
### Environment

- Operating System: Darwin
- Node Version:     v16.18.1
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      devtools, app, runtimeConfig, modules, dayjs, colorMode, css, components, vite, build
- Runtime Modules:  @nuxtjs/eslint-module@4.1.0, @pinia/nuxt@0.4.11, @vueuse/nuxt@10.2.1, nuxt-swiper@1.2.0, dayjs-nuxt@1.1.2, @nuxt/image@1.0.0-rc.1, @nuxtjs/i18n@8.0.0-beta.13, @nuxtjs/color-mode@3.3.0
- Build Modules:    -

### Reproduction

[rollup.zip](https://github.com/nuxt/nuxt/files/12249985/rollup.zip)

### Describe the bug

- set  (entryFileNames, chunkFileNames, assetFileNames) of vite.build.rollupOptions.output  in nuxt.config
- yarn build
- nothing  .output.public._nuxt

### Additional context

<img width="219" alt="image" src="https://github.com/nuxt/nuxt/assets/8554821/39133aa6-e696-43b5-a351-09633cefbadd">

**Comment by Nura-21** [comment]
@kyejune Can you share your `nuxt.config.ts`?

**Comment by kyejune** [comment]
> @kyejune Can you share your `nuxt.config.ts`?
here: 
<img width="419" alt="image" src="https://github.com/nuxt/nuxt/assets/8554821/aadb4bda-a8ab-4bb2-8b9b-f850987d6c92">

**Comment by kyejune** [comment]
Thanks to you, it was solved.
The cache is planned to create a specified value and put it in.

> You need to append `_nuxt/` to the start of those ids. So, for example: `_nuxt/[name].js`.
> 
> If you want to change the name of the directory you can do that with `app.buildAssetsDir`.
> 
> But we do need a directory name for setting appropriate cache headers for the build assets.

Thanks to you, it was solved.
The cache is planned to create a specified value and put it in.
