### ISSUE TITLE
Cannot find module `...\nuxt\node_modules\@nuxt\kit\dist\index.mjs`

### ISSUE THREAD

**Issue by Nura-21** [nuxt/nuxt#22460]
### Environment

npx nuxi info
Nuxi 3.6.5                                                                                                                     

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.1
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      app, ssr, spaLoadingTemplate, extends, watch, modules, imports, devServer, nitro, vite, router, components, hooks     
- Runtime Modules:  @pinia/nuxt@0.4.11, @nuxtjs/tailwindcss@6.8.0, @vueuse/nuxt@10.3.0
- Build Modules:    -
------------------------------

### Reproduction

I don't have any idea why this is happening. I have one root project and child projects with layering. And this happens when `nuxi generate` one of child projects. Does anyone have any ideas?

`nuxt.config.ts` below:
```
{
  ssr: false,
  spaLoadingTemplate: false,
  extends: ['../core'],
  watch: [process.env.NODE_ENV === 'development' ? '../core' : ''],

  modules: ['@pinia/nuxt', '@nuxtjs/tailwindcss', '@vueuse/nuxt'],

  imports: {
    dirs: ['store'],
  },

  devServer: {
    port: 8080,
  },

  nitro: {
    compressPublicAssets: true,
    output: {
      publicDir: import.meta.env.VITE_BUILD_DIR,
    },
  },

  vite: {
    build: {
      minify: false,
      rollupOptions: {
        output: {
          entryFileNames: `_nuxt/[name].js`,
          chunkFileNames: `_nuxt/[name].js`,
          assetFileNames: `_nuxt/[name].[ext]`,
        },
      },
    },
  },
  ```
  
  `package.json`:
  ```
  {
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev --dotenv .env.development",
    "test": "nuxt dev --dotenv .env.test",
    "prod": "nuxt dev --dotenv .env.production",
    "vercel": "nuxt dev --dotenv .env.vercel",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare",
    "typecheck": "nuxt typecheck"
  },
  "devDependencies": {
    "@nuxt/devtools": "^0.4.5",
    "@vueuse/nuxt": "^10.3.0",
    "nuxt": "^3.6.5",
    "prettier": "^2.8.8"
  },
  "dependencies": {
    "@nuxtjs/tailwindcss": "^6.8.0",
    "@pinia/nuxt": "^0.4.11",
    "pinia": "^2.1.6"
  }
}
```

### Describe the bug

I get such error
```
[4/4] Building fresh packages...
$ nuxt prepare
[log] Nuxi 3.6.5
[error] Cannot find module '...\efo\efo\node_modules\nuxt\node_modules\@nuxt\kit\dist\index.mjs' imported from '...\efo\efo\node_modules\nuxt\dist\index.mjs'
  at new NodeError (node:internal/errors:399:5)
  at finalizeResolution (node:internal/modules/esm/resolve:326:11)
  at moduleResolve (node:internal/modules/esm/resolve:945:10)
  at defaultResolve (node:internal/modules/esm/resolve:1153:11)
  at nextResolve (node:internal/modules/esm/loader:1[63](https://gitlab.halyklife.nb/dit/front-vue/efo/-/jobs/11694#L63):28)
  at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
  at link (node:internal/modules/esm/module_job:76:36)
error Command failed with exit code 1.
```

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by Nura-21** [comment]
I can not provide a reproduction, because it happens only when building using gitlab runner. When building local, everything works fine.

**Comment by dpmillerau** [comment]
I'm having something similar.  It will be using a buildpabck from heroku probably, @Nura-21  you should be able to install pack locally and build locally to recreate.  The same should happen during a "npm run build."

My current problem actually relates to relative paths and to layers, but I haven't got a reproduction yet. I wouldn't be surprised if it is related.

**Comment by krystofbruth** [comment]
For anybody stumbling upon this - had a similar issue, solved by deleting and re-installing `node_modules`.
