### ISSUE TITLE
Plugin: Cannot redefine property: $hello

### ISSUE THREAD

**Issue by tresko** [nuxt/nuxt#22479]
### Environment

Windows 10.
Node v18.15.0

### Reproduction

https://github.com/tresko/nuxt-plugin-error

### Describe the bug

I get following error when I add plugin.

````
[nuxt] error caught during app initialization TypeError: Cannot redefine property: $hello
    at Function.defineProperty (<anonymous>)
    at defineGetter (nuxt.js:175:10)
    at nuxtApp.provide (nuxt.js:67:5)
    at applyPlugin (nuxt.js:110:17)
    at async applyPlugins (nuxt.js:123:7)
    at async initApp (entry.js:47:7)
```

Plugin:
```
export default defineNuxtPlugin(() => {
  return {
    provide: {
      hello: (msg: string) => `Hello ${msg}!`,
    },
  }
})

```

### Additional context

_No response_

### Logs

_No response_

**Comment by husayt** [comment]
@tresko I have the similar issue. Can you provide more info on the cause? Thanks in advance

**Comment by tresko** [comment]
@husayt in https://github.com/tresko/nuxt-plugin-error/blob/main/nuxt.config.ts I changed `plugins` from

`
  plugins: [
    '/c:/Users/sedej/Documents/Projekti/vitest-test/plugins/02.piniaPlugin.ts',
    '/c:/Users/sedej/Documents/Projekti/vitest-test/plugins/01.helloPlugin.ts',
  ],
`

to 

`  plugins: [
    '~/plugins/02.piniaPlugin.ts',
    '~/01.helloPlugin.ts',
  ],`
  
But I don't know which code is auto-populating it.

**Comment by husayt** [comment]
yes, found that too. it's super annoying. i think it is nuxi trying to be
helpful.  this has caused me multiple headaches. this is not helpful at
all.

**Comment by tresko** [comment]
@husayt agree

**Comment by trandaison** [comment]
I have a same issue.
I create a module, it work perfectly on development mode (or even prepacked).
But when I build and release the module, it runs into this issue
<img width="720" alt="Screenshot 2023-12-20 at 08 12 49" src="https://github.com/nuxt/nuxt/assets/13447235/5de6d5da-4601-4df8-89a5-850866397f62">

Here is my module structure, I am not sure if Nuxt register this plugin automatically. 
<img width="315" alt="Screenshot 2023-12-20 at 08 13 17" src="https://github.com/nuxt/nuxt/assets/13447235/8756e99a-86ec-4451-aa4f-8811ca1f3d7f">
