### ISSUE TITLE
navigateTo to the same page with query change breaking the page on client side.

### ISSUE THREAD

**Issue by yuvalkarif** [nuxt/nuxt#22472]
### Environment

- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Stackblitz Repro: https://stackblitz.com/edit/github-mrmpjq

### Describe the bug

using `navigateTo` on client side setup breaks when navigating to the current page with query change.

Click on _goto foo-bar_ link, the page is now broken with errors and warnings in the window console: 
```
Vue Warn Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. 
```
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'parentNode')
```
 URL is correct `/foo/bar?p=1` but the actual page didn't change.

Entering from SSR to `/foo/bar` works fine. The only valid workaround I have found is to handle it with router.replace in client side. (which I left as a comment in the bar.vue file for testing).

**Comment by aviramaz** [comment]
+1

**Comment by l4dybird** [comment]
+1

**Comment by MGolob** [comment]
+1

**Comment by DenisLug** [comment]
The issue seems still to be there with nuxt 3.7.4. The only solution I discovered is to set the external option:
`await navigateTo({ path: '/myurl' }, { external: true })`

**Comment by danielroe** [comment]
possibly related: https://github.com/nuxt/nuxt/issues/22900.

**Comment by nosizejosh** [comment]
same issue on nuxt 3.11.2.

**Comment by manniL** [comment]
@nosizejosh Please raise a new issue then with a reproduction and link this one.
