### ISSUE TITLE
Upgrade from 3.2.2 to 3.5.6 issues with Uncaught SyntaxError: The requested module "vue.js?v=60daa4c8" does not provide an export named 'hasInjectionContext'

### ISSUE THREAD

**Issue by scottcarlton** [nuxt/nuxt#22477]
### Environment

- Operating System: Darwin
- Node Version:     v16.19.1
- Nuxt Version:     3.6.5 // previous 3.2.2
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.11
- Builder:          vite
- User Config:      ssr, modules, alias, security, apollo, css, vite, devServer
- Runtime Modules:  nuxt-security@^0.13.0, @nuxtjs/apollo@^5.0.0-alpha.6
- Build Modules:    -

### Reproduction

Using `npx nuxi upgrade --force`
`yarn dev`

### Describe the bug

See this error in the console. `Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.vite/deps/vue.js?v=60daa4c8' does not provide an export named 'hasInjectionContext' (at nuxt.js?v=861fd463:1:30)`

Looking that the module .vite/deps/vue.js there is no `hasInjectionContext` and looking at the nuxt.js file at the error `import { getCurrentInstance, hasInjectionContext, reactive } from "/_nuxt/node_modules/.vite/deps/vue.js?v=861fd463";
`

### Additional context

Looks like the issue is with the .vite/deps/vue.js not exporting `hasInjectionContext`

**Comment by danielroe** [comment]
The issue is likely that you still have an old version of vue hanging around. Try removing `node_modules/.vite` and/or checking `yarn why vue` and otherwise updating your lockfile. You might try explicitly installing a new version of vue.

**Comment by scottcarlton** [comment]
@danielroe - Thanks, for the reply. I had tried those. I remove `node_modules` using 'rm -rf node_modules ' and vue is currently version `vue@3.3.4`.  Seems sort of hacky to add vue to a nuxt app if explicityly installing a new version of vue is what you meant. Any other options?

**Comment by danielroe** [comment]
Could you check whether you have a node_modules folder in a parent directory? What is the output of `yarn why vue`?
