### ISSUE TITLE
generate project, svg inside image will appear error!

### ISSUE THREAD

**Issue by JoGlows** [nuxt/nuxt#22484]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      vite
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-t1mz7m?file=app.vue

### Describe the bug

`npm run generate`, it will show error that ELOOP: too many symbolic links encountered. The main reason the svg code inside image tag.

example:
```
<svg>
<path></path>
<image />
</svg>
```
How can avoid this error?

**Comment by danielroe** [comment]
Thanks! Let's track in https://github.com/unjs/nitro/issues/1527.
