### ISSUE TITLE
Scroll do weird jumping to the top of the web page on Nuxt3 page refresh

### ISSUE THREAD

**Issue by PolinaTcaciuc** [nuxt/nuxt#22487]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v16.15.0
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  npm@8.5.5
- Builder:          vite
- User Config:      app, components, devtools, modules, swiper, css, vite
- Runtime Modules:  @pinia/nuxt@0.4.11, nuxt-swiper@1.2.0
- Build Modules:    -
------------------------------

### Reproduction

You can check the effect here:
https://stackblitz.com/edit/nuxt-starter-cgquz4?file=pages%2Findex.vue

### Describe the bug

I have a problem with scroll behavior in Nuxt.js 3. When I refresh the page (when static content is served), the scroll jumps abruptly to the top of the page. However, after serving the static content, there is an automatic scroll to the previous position (the position from which the refresh was triggered), which creates an unpleasant "jumping" effect on the website.
If I use SSR = False, the scroll doesnt "jump" and stay on the same position when the page is refreshed.

I assume that Nuxt3 should prevent the scroll from returning to the top of the document when refreshing my page and keep the scroll at the same position.

When I try to do the same in Nuxt2, the scroll behaviour is normal.

**Comment by danielroe** [comment]
It's your browser that is jumping the scroll to the top of the page, and then Nuxt is scrolling back down to the bottom. It doesn't show up with `ssr: false` because Nuxt is already instantiated before the page renders. The options here - I think - are:

1. inject script to handle scroll position _before_ Nuxt hydrates (probably best option)
2. don't scroll at all on initial load
3. keep it as it is, with a potential jump

**Comment by Eclmist** [comment]
There is a similar issue I'm facing.

On first load, if the user scrolls down before Nuxt hydrates, once content is loaded Nuxt will scroll the page back up.
This is quite jarring especially if the network is slow, and you've already begun scrolling and reading static content.

@danielroe could you elaborate on 1 and 2?

**Comment by jooohyunpark** [comment]
+1 The scroll position has been retained on nuxt v2 static generation pages. Any rationale this has been changed in v3?

**Comment by danielroe** [comment]
That's why this is marked as a bug.

**Comment by or2e** [comment]
@PolinaTcaciuc 
A temporary hack is to set a custom scrollBehavior.
[Here app/router.options.ts](https://nuxt.com/docs/guide/going-further/custom-routing#router-options) you can copy the [default scrollBehavior](https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/pages/runtime/router.options.ts#L14) and at the top of it add `window.history.scrollRestoration = 'auto';` (default browser value).
It changes [here](https://github.com/vuejs/router/blob/main/packages/router/src/router.ts#L378) in the vue-router package.

I'll try to figure it out better over time, but at least the annoying upward jumps are gone.

**Comment by manuelodelain** [comment]
Thanks @or2e for the workaround.
Unfortunately the scrollRestoration `auto` breaks the scroll restoration during a page transition.
I have to restore the `manual` scrollRestoration.

```ts
// in the default layout, but I guess it should be somewhere else
onMounted(() => {
    // prevents window to scrollTop then returns to savedPosition
    window.history.scrollRestoration = 'auto'

    // but restore manual scrollRestoration at the first navigation
    const unwatch = useRouter().beforeEach(() => {
        window.history.scrollRestoration = 'manual'
        unwatch()
    })

    // and restore auto scrollRestoration when leaving the page
    window.addEventListener('unload', () => {
        window.history.scrollRestoration = 'auto'
    })
})

**Comment by robbiemie** [comment]
> @PolinaTcaciuc @danielroe 一个临时的技巧是设置自定义滚动行为。 [在 app/router.options.ts 中，](https://nuxt.com/docs/guide/going-further/custom-routing#router-options)您可以复制[默认的滚动行为](https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/pages/runtime/router.options.ts#L14)并在其顶部添加`window.history.scrollRestoration = 'auto';`（默认浏览器值）。 它[在](https://github.com/vuejs/router/blob/main/packages/router/src/router.ts#L378)vue-router 包中发生了变化。
> 
> 随着时间的推移，我会尝试更好地解决这个问题，但至少恼人的向上跳跃已经消失了。

Thanks @or2e , I have to resolve it.

```vue
onMounted(() => {
  window.history.scrollRestoration = 'manual'
})
```
