### ISSUE TITLE
Failing at generate

### ISSUE THREAD

**Issue by OlivierCoq** [nuxt/nuxt#22482]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.20.1`
- Nuxt Version:     `3.6.5`
- Nitro Version:    `2.5.2`
- Package Manager:  `npm@6.14.17`
- Builder:          `vite`
- User Config:      `devtools`, `ssr`, `typescript`, `css`, `plugins`, `modules`, `pinia`, `target`, `build`
- Runtime Modules:  `@pinia/nuxt@0.4.11`, `@pinia-plugin-persistedstate/nuxt@1.1.1`
- Build Modules:    `-`

### Reproduction

Basic. Project in Nuxt 3, with font awesome, Pinia, Sass, and Vuetify. Attempt to run `generate`

### Describe the bug

Repeatedly getting this error:
`[commonjs--resolver] Missing "./dist/pages/runtime" specifier in "nuxt" package`

I have cleared npm cache and installed node modules several times, and have the same result after switching from node versions 14, 16, and 18.

**Comment by manniL** [comment]
Could you kindly provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by OlivierCoq** [comment]
> Could you kindly provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

Yes. Here: https://stackblitz.com/edit/github-vbpafd?file=pages%2Findex.vue

**Comment by danielroe** [comment]
You have a module, Nuxt Axios, which depends on Nuxt 2.
