### ISSUE TITLE
Runtime Hook to perform setup scripts directly after server startup

### ISSUE THREAD

**Issue by dvelop-jkas** [nuxt/nuxt#22486]
### Describe the feature

We currently have the following scenario, we use the nitro server as a small backend in our application and need to dynamically load various environment variables when starting the server. 

In this process we have the problem that there is no hook available after the server start and before the first execution of the server middleware. Since our server middleware also accesses a database, we would need to run our setup script before running the middleware for the first time. 

For us also build time scripts do not solve our problems because we build docker images to deploy our application so some varaibles and files we need are not available in the build time.

My suggestion would be to provide a hook that covers exactly this scenario e.g. "nitro:ready" or "server:ready"

There some questions out there which are related to my topic like:
https://stackoverflow.com/questions/66931971/best-way-to-run-some-code-only-once-on-server-start-in-nuxt-js-and-not-during-b

https://github.com/nuxt/nuxt/discussions/15886

I hope the requirements are clear and understandable.

If there is another way, to perform this script to so,ve this issue please let me know :)

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by dvelop-jkas** [comment]
As a workaround we check if the environment is set is at the top of our server middleware, and when not we execute our setup function, but in my opinion there should be a better approach to handle this case

**Comment by danielroe** [comment]
You can create a nitro plugin to do this: https://nuxt.com/docs/guide/directory-structure/server#server-plugins.

If there's something you can't do there, feel free to open an issue directly in https://github.com/unjs/nitro.
