### ISSUE TITLE
Plugin: error absolute path in config

### ISSUE THREAD

**Issue by artnova-david** [nuxt/nuxt#22491]
### Environment

- Operating System: Windows_NT
- Node Version:     v16.15.1
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@8.12.0
- Builder:          vite
- User Config:      devtools, modules, css, alias, quasar
- Runtime Modules:  nuxt-quasar-ui@2.0.5, @vueuse/nuxt@10.3.0
- Build Modules:    -

### Reproduction

Start dev server and add a plugin to your project

### Describe the bug

Every time a plugin is added to the project and you run `npm run dev` the plugin is registered with an absolute path in the nuxt.config.ts file.
This results in the plugin not being found or errors like `error caught during app initialization TypeError: Cannot redefine property...`. To fix this the config file must be manually updated by removing the plugins property or changing the path. But every time you add a new plugin or remove one, all the paths are re-created to absolute paths. When having multiple plugins this can be a daunting task.
I don't know if this is a bug or me missing some configuration. I couldn't find anything about this in the docs except for this issue [https://github.com/nuxt/nuxt/issues/22479](url) but that's been closed without resolution.

Kind regards
David

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by artnova-david** [comment]
Well, I just created a new Nuxt project via `npx nuxi@latest init nuxt-base` ran `npm install` then ran `npm run dev` and added a plugin folder with this plugin.
 
```
export default defineNuxtPlugin((NuxtApp) => {
   return {
      provide: {
         $test: (msg: string) => 'Hello ${msg}!'
      }
   }
 })

```

and the plugin was added to the nuxt.config file automatically like this
`plugins: [ '/d:/apps/nuxt-apps/nuxt-base/plugins/myPlugin.ts`
Resulting in an error `error caught during app initialization TypeError: Cannot redefine property $test`
When I remove the plugin property from the config file all works fine and I can use the property `$test` without a problem in the app.vue file.

**Comment by danielroe** [comment]
That's not Nuxt doing it. Are you _sure_ you don't have an IDE extension that is doing this?

**Comment by artnova-david** [comment]
I'm using VsCode and these extensions: Nuxtr, Typescript Vue Plugin (Volar) and Vue Language Features (Volar)

**Comment by danielroe** [comment]
cc: @adhamfarrag could this be Nuxtr?

**Comment by adhamfarrag** [comment]
@danielroe Nuxtr adds plugins to Nuxt config file but we never add them with absolute path.

@artnova-david can you disable Nuxtr and try?

**Comment by artnova-david** [comment]
I think it is Nuxtr, when I change my config settings to an object like this

```
const config = {...}
export default defineNuxtConfig(config)
```
instead of directly using this

```
export default defineNuxtConfig({...})

```

Nuxtr throws an error:
![2023-08-04 133315](https://github.com/nuxt/nuxt/assets/21141231/94eae0b7-1140-40a0-a5c7-9222862d7081)

**Comment by adhamfarrag** [comment]
@artnova-david Thanks for bringing this to our attention but this doesn't justify the first error. Can you disable Nuxtr and try again?

**Comment by artnova-david** [comment]
I disabled Nuxtr and when adding a plugin the config file was **not** modified. When re-enabling Nuxtr and adding a plugin to the folder the config file **is** modified and the plugin is added as:
`plugins: [ '/d:/apps/nuxt-apps/nuxt-base/plugins/temp.ts']`

**Comment by danielroe** [comment]
It might be worth reconsidering whether to add plugins to the plugins array if they will be auto-scanned anyway. But I'll leave that to you.

I think we can close the issue here.

**Comment by artnova-david** [comment]
@adhamfarrag or maybe provide a an option in the settings?
