### ISSUE TITLE
smooth scroll not working when moving between pages using router

### ISSUE THREAD

**Issue by gileneusz** [nuxt/nuxt#22504]
### Environment

  System:
    OS: macOS 13.5
    CPU: (8) arm64 Apple M1
    Memory: 106.67 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.5.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.8.0 - /usr/local/bin/npm
    pnpm: 8.6.11 - /usr/local/bin/pnpm
  Browsers:
    Brave Browser: 114.1.52.122
    Chrome: 115.0.5790.170
    Edge: 110.0.1587.63
    Safari: 16.6
package.json:
```
     "dependencies": {
    "core-js": "^3.15.1",
    "nuxt": "^2.15.7",
    "vuetify": "^2.5.5"
  },
  "devDependencies": {
    "@nuxtjs/vuetify": "^1.12.1"
  }
```

### Reproduction

I want to set smooth scroll when I move between pages using router. 

For example I'm on "/" path and I want to move to "/test" path. 

I set the default behaviour on nuxt.config.js:
```
  router: {
    scrollBehavior(to, from, savedPosition) {
    return { x: 0, y: 0 }
    }
```
    and this works, however when I add smooth property:
    
```
  router: {
    scrollBehavior(to, from, savedPosition) {
    return { x: 0, y: 0, behavior: 'smooth' }
    }
```

scrolling on top of the page does not work anymore. Smooth property also does not work too.

### Describe the bug

<img width="500" alt="Screenshot 2023-08-06 at 10 18 28" src="https://github.com/nuxt/nuxt/assets/34601970/5a6127a3-82ba-4005-b833-02f7858b9528">

**Comment by ne0guille** [comment]
Hi @gileneusz , according to the docs [https://v2.nuxt.com/docs/configuration-glossary/configuration-router#scrollbehavior] you have to override the router in the following file ~/app/router.scrollBehavior.js
I've just tried it, and it works correctly
