### ISSUE TITLE
useSeoMeta or useHead with ssr:false

### ISSUE THREAD

**Issue by shidcordero** [nuxt/nuxt#22506]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      ssr, vite, app, css, modules, build, runtimeConfig
- Runtime Modules:  @pinia/nuxt@0.4.11, @vueuse/nuxt@10.2.1, @vee-validate/nuxt@4.10.8
- Build Modules:    -

### Reproduction

Hard to put a reproduction link as it requires to be deployed, but you can use my app link instead https://viewpointz.web.app/sign-up

### Describe the bug

On my app specific to this page https://viewpointz.web.app/sign-up

I added the code to add some meta tags

```
const config = useRuntimeConfig()
useSeoMeta({
  title: 'View Pointz',
  description:
    'View Pointz is your centralized ad service app where we showcase ads throughout the platform to enter a giveaway. Join Now! Win Now!',
  ogTitle: 'Sign up on View Pointz',
  ogDescription:
    'View Pointz is your centralized ad service app where we showcase ads throughout the platform to enter a giveaway. Join Now! Win Now!',
  ogImage: () => `${config.public.baseUrl}/images/preview-image.jpg`,
  ogUrl: () => `${config.public.baseUrl}sign-up`,
  ogType: 'website',
  twitterCard: 'summary_large_image',
  twitterTitle: 'View Pointz',
  twitterDescription:
    'View Pointz is your centralized ad service app where we showcase ads throughout the platform to enter a giveaway. Join Now! Win Now!',
  twitterImage: () => `${config.public.baseUrl}/images/preview-image.jpg`
})
```

or

```
const config = useRuntimeConfig()
useHead({
  meta: [
    // Open Graph
    { property: 'og:title', content: 'Sign up on View Pointz' },
    {
      property: 'og:description',
      content:
        'View Pointz is your centralized ad service app where we showcase ads throughout the platform to enter a giveaway. Join Now! Win Now!'
    },
    { property: 'og:image', content: () => `${config.public.baseUrl}/images/preview-image.jpg` },
    { property: 'og:url', content: () => `${config.public.baseUrl}sign-up` },
    { property: 'og:type', content: 'website' },
    // Twitter Card
    { name: 'twitter:card', content: 'summary_large_image' },
    { property: 'twitter:domain', content: 'viewpointz.web.app' },
    { property: 'twitter:url', content: () => `${config.public.baseUrl}sign-up` },
    { name: 'twitter:title', content: 'Sign up on View Pointz' },
    {
      name: 'twitter:description',
      content:
        'View Pointz is your centralized ad service app where we showcase ads throughout the platform to enter a giveaway. Join Now! Win Now!'
    },
    { name: 'twitter:image', content: () => `${config.public.baseUrl}/images/preview-image.jpg` }
  ]
})
```

Either of the two code works as I can see it was able to add meta tags but when I try to use the link to a verifier or even posted it on facebook, it won't contain the meta contents. 
https://www.opengraph.xyz/url/https%3A%2F%2Fviewpointz.web.app%2Fsign-up%2F ->verifier

I am thinking, is this because of I am not using ssr(`ssr: false`)?

Is there a work around on this without having to opt on ssr?

**Comment by danielroe** [comment]
Yes, it's because you are not using SSR. So there are no meta tags rendered.

You can set default meta tags for your app in `app.head` in your nuxt config, which will be respected even with `ssr: false`.

**Comment by shidcordero** [comment]
okay, so I am using ssr: true but I tried `useHead`, `useHeadSafe`, `useSeoMeta`, `useServerSeoMeta` but still meta tags are not generated when I run `yarn generate`

**Comment by danielroe** [comment]
You can open a new issue with a reproduction and I'll happily have a look

**Comment by shidcordero** [comment]
@danielroe my bad for this. I re-read the documentation and found out that I can only use useHead or useSeoMeta on the app.vue. Is there a way to use it on page level? like I have sign-up.vue and want to set meta tags on that page?

**Comment by danielroe** [comment]
You can use it in any component.

**Comment by vadimasadchi** [comment]
> You can use it in any component.

Original question was about prerending of static pages with `npm/yarn generate` which skips `useSeoMeta` so there is no option to have seo metatags set in static html file

**Comment by alSergey** [comment]
@danielroe Hi, sorry for tagging you. I have a similar issue where I need to use `useHead` with `ssr: false`, but I can't configure it in `nuxt.config.ts` because the data is generated dynamically. Are there any recommendations for this case? I’ve described everything in more detail [here](https://github.com/nuxt/nuxt/discussions/32458).
