### ISSUE TITLE
Bad rendering when a variable value changes from server side rendering to client side rendering

### ISSUE THREAD

**Issue by mykkode32** [nuxt/nuxt#22517]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v16.17.0
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      modules, colorMode, runtimeConfig
- Runtime Modules:  @tailwindcss/typography@0.5.9, @nuxtjs/tailwindcss@6.8.0, @pinia/nuxt@0.4.11, @nuxtjs/color-mode@3.3.0, nuxt-icon@0.4.2
- Build Modules:    -
------------------------------

### Reproduction

https://codesandbox.io/p/sandbox/keen-sea-66ccg7

### Describe the bug

We have a useDimensions composable which returns the dimension of the window.

We also have a simple vue file:

```
  <div>
    {{ dimensions.width }}
    <div v-if="dimensions.width > 1200" class="red">
      <span>Who let the dogs out</span>
    </div>
    <div v-else class="green">Wof Wof</div>
  </div>
```

which based on the useDimensions composable returns either DIV1 or DIV2.

1. The webpage renders on server side using a default preset value (`390x900`) which will render DIV2 (in production this should only happen the first time you access the website).
2. When the onmounted event happens we update the resolution using the actual resolution (let's say `1920x1080`).
3. The content of the two divs update accordingly, however the classes on the div remain the same: https://ibb.co/ZWFxyHk

The update happens in the onmounted event, at first the website should have been rendered using the initial resolution 390x900 and then it should have been updated to the 1920x1080 dimensions.

### Additional context

As a workaround we use CSS to render different elements on different dimensions, however sometimes it makes more sense to render some elements based on JS logic (like the number of elements of a carousel).

`v-show` should fix this issue as both divs are printed and the updated, however in some cases you might not want to use it (you don't want to print 1000 elements).

**Comment by danielroe** [comment]
This is called a hydration error. It's an additional constraint that exists when you are rendering an app on server + client - the initial state of both apps (namely, whatever renders the html) needs to match.
