### ISSUE TITLE
`app.rootId` set to an empty string isn't ignored

### ISSUE THREAD

**Issue by DamianGlowala** [nuxt/nuxt#22525]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.20.0`
- Nuxt Version:     `3.6.5`
- Nitro Version:    `2.5.2`
- Package Manager:  `pnpm@8.6.12`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

```
export default defineNuxtConfig({
  app: {
    rootId: ''
  }
})
```

### Describe the bug

![image](https://github.com/nuxt/nuxt/assets/48835293/e4ba3293-5c70-48e3-b8e1-72d27825dfa7)

**Comment by manniL** [comment]
As far as I can see, this is correct.

The `id` is needed for mounting as well as for removing the root node for server components.

**Comment by DamianGlowala** [comment]
I believe you misunderstood the intention behind this issue. Empty string is falsy, and therefore, I would argue whether *an empty string* should be taken into account (which clearly throws an error), or a default value (`__nuxt`) be taken instead.

**Comment by manniL** [comment]
Oops. Indeed, you are right.

**Comment by Lehoczky** [comment]
What do you think about validating the `rootId` with a regex to see if it would be a valid id, and ignoring it with a warning in case it fails this validation?

**Comment by DamianGlowala** [comment]
I had the exact same thought! Not only we can exclude an empty string, but go even further by validating if the passed string is a _valid ID_ (in this scenario I'd much rather throw an error than silently ignore the user-provided value).
