### ISSUE TITLE
router.push `async-page` Uncaught (in promise) TypeError: Cannot read properties of null (reading 'parentNode')

### ISSUE THREAD

**Issue by pdsuwwz** [nuxt/nuxt#22522]
version: `3.6.5`
Reproduce example:
https://stackblitz.com/edit/github-2vsgq3?file=src%2Fpages%2Findex.vue&file=src%2Fpages%2Fasync-page.vue

When you quickly double click the `To Async Page` button (i.e. quickly click), you can reproduce the error:

What I understand is that if you click multiple times, it will only respond to the last `router.push`, because I know that in a single-page application, this kind of operation is no problem, but there seems to be a problem in `SSR`

![Aug-08-2023 00-39-02](https://github.com/nuxt/nuxt/assets/19891724/81a40690-9ae2-44c0-8efa-1597fb1808c2)

_Originally posted by @pdsuwwz in https://github.com/nuxt/nuxt/issues/13309#issuecomment-1668241787_

**Comment by pdsuwwz** [comment]
If you switch to version `3.5.3`, it will not reproduce :(

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/13309.
