### ISSUE TITLE
Add link to the changelog on the community releases tab

### ISSUE THREAD

**Issue by bitbytebit1** [nuxt/nuxt#22533]
### Describe the feature

See title

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Would you explain a bit more about what you mean?

**Comment by danielroe** [comment]
Okay, that makes sense, but I think we instead need to redirect to the GitHub URL instead of adding a link within the page.

**Comment by danielroe** [comment]
See https://github.com/nuxt/nuxt/pull/22534#issuecomment-1674685681.
