### ISSUE TITLE
(Allow) ignoring 404 errors as failure on prerender

### ISSUE THREAD

**Issue by FreekVR** [nuxt/nuxt#22536]
### Describe the feature

Ever since https://github.com/nuxt/nuxt/pull/21817 our prerender will fail if any errors occur.

I believe this is correct behavior, however I would like to filter out 404 errors as non-blocking for the deploy as user-generated content is used and may hold up deployments unnecessarily now (though logging it as a warning would be nice). Currently I can only ignore all/no errors via `nitro.failOnError`?

I can't find any documentation for nuxt or nitro on how to (easily) achieve it. Any feature to configure this or a heads-up how I can do this myself would be appreciated :)

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
cc: @pi0

**Comment by yunyuyuan** [comment]
Currently you can use `failOnError`, which is not written in the document:
```ts
export default defineNuxtConfig({
  nitro: {
    prerender: {
      failOnError: false
...
```
![image](https://github.com/nuxt/nuxt/assets/45785585/163f4e83-6125-409c-b5fc-90bbf61ba731)

**Comment by FreekVR** [comment]
Thanks, that's a workaround though, as it ignores any error, not just 404
errors. I would still like it to fail if it fails to parse some pages for
some other reason.

**Comment by danielroe** [comment]
Let's track in https://github.com/unjs/nitro/issues/new.
