### ISSUE TITLE
UseFetch doesn't work if it's inside pinia store, despite its invocation from within the <script setup> section

### ISSUE THREAD

**Issue by KamilBeda** [nuxt/nuxt#22549]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.16.1
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.6.11
- Builder:          vite
- User Config:      ssr, devtools, imports, modules, css, svgo, i18n, headlessui, image, components, extends, runtimeConfig, linkChecker, googleFonts, build, vite, nitro
- Runtime Modules:  @nuxtjs/eslint-module@4.1.0, @pinia/nuxt@0.4.11, @nuxtjs/i18n@8.0.0-rc.2, nuxt-svgo@3.4.0, nuxt-headlessui@1.1.4, @nuxt/image@1.0.0-rc.1, nuxt-typed-router@3.2.5, @formkit/nuxt@0.17.5, @nuxtjs/tailwindcss@6.8.0, nuxt-icon@0.4.2, @nuxtjs/google-fonts@3.0.2, @vueuse/nuxt@10.3.0
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-ntrsan-qorvzj?file=app.vue

1. Make pinia store with function for example "fetchData" that returns `useFetch('some-endpoint')`
2. Use store inside `script setup` and call `store.fetchData`
3. Try to render data returned from `store.fetchData` in the template
4. Data remains undefined

### Describe the bug

UseFetch doesn't work if it's inside pinia store, despite its invocation from within the <script setup> section.

I like to keep my API calls in pinia modules. For example all API calls related to user would be in user.ts pinia module. Unfortunately I realized that it's not possible when using `useFetch` Nuxt composable. Could this be considered a bug, or is it an intentional behavior?

**Comment by yuvalkarif** [comment]
https://nuxt.com/docs/api/composables/use-fetch
> This composable provides a convenient wrapper around [useAsyncData](https://nuxt.com/docs/api/composables/use-async-data) and [$fetch](https://nuxt.com/docs/api/utils/dollarfetch).

To get you intentional behaviour, use `$fetch` inside your store action and wrap your page call inside `useAsyncData`.
This way you can use your API calls can be used in more ways, like on user triggered events... and having the benefits of caching in your page script.

```js
// store.ts
 async function fetchData() {
    return await $fetch(`https://dummyjson.com/products/1`);
  }
// app.vue
const { data } = await useAsyncData(()=>testStore.fetchData());
```

**Comment by KamilBeda** [comment]
Thank you for the info. That's what I was looking for 🥰
