### ISSUE TITLE
Unexpected substitutions in embedded scripts in useHead

### ISSUE THREAD

**Issue by dmytro-grablov** [nuxt/nuxt#22559]
### Environment

- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      -
- Runtime Modules:  -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-nk8qxi?file=app.vue

start the project and simply reload the page, the console error will appear.

To better see the results, you might want to directly open the app (probably with https://nuxtstarternk8qxi-antd--3000--d5d65229.local-credentialless.webcontainer.io/) and look at the source code

### Describe the bug

Nuxt 3 (Nuxt Bridge as well) performs unexpected substitutions inside the browser scripts, while page is being server-side rendered.
Consider the following example: 
```
useHead({
  script: [
    {
      innerHTML:
        'console.log("First very important part"); if ("function" === typeof window.performance.mark) { console.log("Second very important part"); }',
    },
  ],
});
```

While the page is being server-side rendered, the script string appears to be replaced with 
`console.log("First very important part"); if ("function" === "undefined".performance.mark) { console.log("Second very important part"); }`

So `typeof window` is being substituted with `"undefined"`

However when the page is hydrated on the client side, the faulty script string will be replaced with the original one, this leads to the following problems:

- script will not be fully executed at the point of time where it needed to be executed, read 'as soon as the document is there'. This is due to the substitution and "undefined" as a string does not contain `performance` property.
- After hydration script will be replaced with its original version. But in fact browser does not know about all that, for it it is one tag being removed and the other one being added, with different contents. So the script will be executed again, now as a complete. This leads to `Second very important part` being logged (executed) once, and `First very important part` twice, which can lead to very unexpected results in the business logic.

The code part causing problems seems to be https://github.com/nuxt/nuxt/blob/ce9aecca4a39e1d5e36e6b92c77e706f8f577445/packages/vite/src/server.ts#L46

however it is still not clear, why this substitution set and why apply this to script tags. Script tags are not meant to be executed server side anyway, but meant to be built server side. These do not have to change.

Even if the embedded scripts are rewritten to use optional chaining for the aforementioned places, it still won't solve the problem, that parts of scripts are going to be executed twice, and the full version of script is not going to be executed in time

**Comment by danielroe** [comment]
We are using vite's [`define` option](https://vitejs.dev/config/shared-options.html#define) to replace this. But because it's a straight text replacement, it's catching this text.

**Comment by danielroe** [comment]
This is now resolved as `define` now uses syntax aware replacement.
