### ISSUE TITLE
Unhandled error during execution of scheduler flush.  TypeError: Cannot set properties of null (setting 'nodeValue')

### ISSUE THREAD

**Issue by DiscreteTom** [nuxt/nuxt#22552]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.12.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      devtools, css, build
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

Repo: https://github.com/DiscreteTom/nuxt3-issue

### Describe the bug

I'm using Vuetify with Nuxt. Here is an example `pages/index.vue` to reproduce the bug (see the reproduction repo for the full project code):

```vue
<template>
  <div>
    <div class="d-flex flex-wrap">
      <v-card
        v-for="(value, name) in result"
        :key="name"
        class="mx-2 my-2 flex-grow-1"
      >
        <v-card-title class="d-flex align-center"> </v-card-title>
        <v-card-text>
          {{ value }}
        </v-card-text>
      </v-card>
    </div>
  </div>
</template>

<script setup lang="ts">
const result = reactive({
  key: "",
});

onMounted(() => {
  result.key = "value";
});
</script>
```

With `ssr: true`, when accessing this page, got the following error:

```
[Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/core 
  at <VCardText> 
  at <VCard key="key" class="mx-2 my-2 flex-grow-1" > 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) > > 
  at <RouteProvider key="/" vnode= Object route= Object  ... > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <VContainer fluid="" > 
  at <VMain> 
  at <VLayout> 
  at <Default ref=Ref< Proxy(Object) > > 
  at <LayoutLoader key="default" layoutProps= Object name="default" > 
  at <NuxtLayoutProvider layoutProps= Object key="default" name="default"  ... > 
  at <NuxtLayout> 
  at <App key=3 > 
  at <NuxtRoot>

Uncaught (in promise) TypeError: Cannot set properties of null (setting 'nodeValue')
    at setText (chunk-BVQHDTV7.js:9152:20)
    at processText (chunk-BVQHDTV7.js:6491:9)
    at patch (chunk-BVQHDTV7.js:6397:9)
    at patchKeyedChildren (chunk-BVQHDTV7.js:7363:9)
    at patchChildren (chunk-BVQHDTV7.js:7277:11)
    at patchElement (chunk-BVQHDTV7.js:6728:7)
    at processElement (chunk-BVQHDTV7.js:6563:7)
    at patch (chunk-BVQHDTV7.js:6424:11)
    at ReactiveEffect.componentUpdateFn [as fn] (chunk-BVQHDTV7.js:7171:9)
    at ReactiveEffect.run (chunk-BVQHDTV7.js:423:19)
```

Everytime you refresh the page you will get the error message.

### Additional context

This issue is similiar to https://github.com/nuxt/nuxt/issues/21901 , but seems like not the same.

This issue might be caused by universal rendering, which doesn't render the `v-card-text` properly.

Here are some workarounds I've found:

- Set `ssr: false`.
- Use `<client-only>` to wrap the `<v-card-text>`.
- Add a placeholder for the `<v-card-text>`: `{{ value || 'placeholder' }}`
- Change the `<v-card-text>` to `<div class="v-card-text">`.

**Comment by danielroe** [comment]
It seems like this might be a vuetify issue given that it only reproduces with it. Would you raise it there instead?

Here's an example with a different component which works fine: https://stackblitz.com/edit/github-pylpou.

**Comment by DiscreteTom** [comment]
Thanks for the response.

However this issue only occurs when the nuxt's ssr is enabled. If I disable the ssr options, vuetify works perfectly. So I think this might be a universal renderring issue.

**Comment by danielroe** [comment]
You can test in https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter to confirm.

**Comment by KaelWD** [comment]
https://play.vuejs.org/#__SSR__eNp9Ustu2zAQ/JUFL5IBWTrkZsgp2iCHFugDbdATL4JE20wokiBXqgtB/94lKStCUORka3d2OLOzE/tobTkOgh1YjaK3qkFxzzVA3ckx/AKM+5NxR87ysVGDKEA3vdiB1OCEHxRylmCHF/GXUKGbSpGGiMZ927huj+KKSwlgmiCywTwvqOotrK5IAf2rq40u+vStkxbBCxxsBMreGofw+4HGn2gaTs70kJXVWimffRZmV+wERn81g0bRFWSjaVGOpGWZpHUQHKA12uPiEo4rLp+SZPJ7gCwrwte8S/wrbZ7v4HgPCzRxlDRBPFl0Hl8IY3WVHJEXVjD09OpJnkmy0RRKJOCsNb2VSrjvFiWp4uxwo+asUcr8+RJr6CigW729iPblP/Vnfw01zn6QLOFGimvtYePOgiIN7cdf32h3m2ZvukER+p3mT+GNGoLGBPs06I5kb3BR7ecYg9TnJ/94RaH9zVQQGhcT8ZxRFA/vWH+Ve1fexTmuZ9riNnla4pp6J05SR0ajhcYCLrfQ41PhbrkW14gmbBOCfzOT0o/XB7l1xvqCiL0y6CnO18BxcBrSEVzyjE45C7hWNd7T1WyOPSOzab5cnvxQ5js6jORmx+Z/QyQyPw==

**Comment by danielroe** [comment]
Thanks for the reproduction @KaelWD.

@DiscreteTom, are you happy to look for/open an issue upstream in vuejs/core?

**Comment by KaelWD** [comment]
https://github.com/vuejs/core/issues/7285

**Comment by danielroe** [comment]
Closing to be tracked upstream.

**Comment by danielroe** [comment]
If you have a reproduction that seems to indicate there is a Nuxt issue, I'll happily take a look just to confirm.
