### ISSUE TITLE
Page finish: document.referrer is null

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/nuxt#22560]
### Environment

https://stackblitz.com/edit/nuxt-starter-kgkioa

### Reproduction

We use page:finish to catch de document.referrer to emit to Google Analytics.

This document.referrer is incorrect

### Describe the bug

We use page:finish to catch de document.referrer to emit to Google Analytics.

This document.referrer is incorrect

**Comment by danielroe** [comment]
I don't think this is a Nuxt issue.

**Comment by agracia-foticos** [comment]
but I think it is incorrect, if the hook is page:finish, then the page has loaded completely, but the referrer, title, etc... have not been loaded.

I think the hook should wait until these values are loaded, don't you think?

We need to know exactly when the document.referrer is loaded with the correct values, in order to issue an event to google analytics and right now it is impossible

**Comment by danielroe** [comment]
I would register a document onload listener or something similar. `page:finish` hook is about when suspense finishes, and makes no promises about the load state of the browser.

**Comment by agracia-foticos** [comment]
I will try what you tell me, I will inform you as soon as possible :). Thanks in advance

**Comment by Salotronic** [comment]
Same here, i think is a bug of the "page:finish" hook, maybe it should be called later. 
This hook seems to be the appropriate  hook to put the analytic plugins that reads "document.referrer, title, etc" but an the moment that is triggered, sometimes these properties are not set.

And is difficult to find an alternative out of nuxt, for example _window.addEventListener("load"_.... is not triggered with nuxtlinks

**Comment by danielroe** [comment]
This isn't a bug of the `page:finish` hook, and it is important that it is called when it is. If you would like a different hook with different properties, feel free to add a feature request with details.

Have you considered `onNuxtReady(() => {})`?

**Comment by agracia-foticos** [comment]
Indeed as @Salotronic  says, I have changed the mentioned code to
```
' window.addEventListener("load", (event) => {
        useAnalytics().page()
    });
})'
``` 
and if you navigate through NuxtLink this event is not fired

**Comment by danielroe** [comment]
Well, onload won't trigger on page navigation. (I was imagining you wanted to track referrer on _initial_ load.)

**Comment by Salotronic** [comment]
> This isn't a bug of the `page:finish` hook, and it is important that it is called when it is. If you would like a different hook with different properties, feel free to add a feature request with details.
> 
> Have you considered `onNuxtReady(() => {})`?

I will try, thanks!

**Comment by danielroe** [comment]
Note that `onNuxtReady` is also only used for deferring running a function until Nuxt is ready. Subsequent to that, it immediately runs the callback. It wouldn't be useful for running code _after_ a route changes.

**Comment by agracia-foticos** [comment]
onNuxtReady not working on NuxtLink links (SPA mode)
We also tried` "window.addEventListener('popstate', function (event) {" and the nuxtlink does not work.
We are quite blocked on this issue

**Comment by danielroe** [comment]
I'm sorry you are blocked. In this case it is because you are using the `page:finish` hook for something it's not designed for.

I would welcome a feature request for something that suits your needs, though I suspect it's also possible to implement already. (Mostly I would think `router.afterEach` would be what you want to track navigation. You get to/from routes. You probably only want to track referrer on initial load. Bear in mind it might not be set, but this is browser behaviour, not Nuxt's. I wouldn't try to track the actual rendered metadata, just the route that you are rendering. If necessary, you can use the route metadata, accessed from `to.meta`.)
