### ISSUE TITLE
add documentation for `@nuxt/test-utils`

### ISSUE THREAD

**Issue by homersimpsons** [nuxt/nuxt#22577]
### Environment

Not Applicable

### Reproduction

1. Go on https://nuxt.com/docs/community/roadmap
2. Check that there is no mention of `@nuxt/test-utils`

### Describe the bug

(Not really a bug, but not really a feature request)

The testing section is mentioning that `@nuxt/test-utils` is still in development (https://nuxt.com/docs/getting-started/testing) but I cannot seem to find any place where there are some ETA or rough estimation.

To me, the Roadmap page is the perfect place for such information https://nuxt.com/docs/community/roadmap.

**Comment by gibkigonzo** [comment]
Is there an update when `@nuxt/test-utils` will be production ready?

**Comment by akintoluvic** [comment]
I would like to help fix this, @danielroe is there additional information I should note

**Comment by danielroe** [comment]
We need to add documentation for Nuxt Test Utils and indicate that it is stable and suitable for use. Some documentation can be found at https://nuxt.com/docs/guide/going-further/modules/#testing.

**Comment by akintoluvic** [comment]
Thanks for the update, I'll get started on it @danielroe
