### ISSUE TITLE
Mismatch vnode.children & node.data when use tsx

### ISSUE THREAD

**Issue by Ives7** [nuxt/nuxt#22574]
### Environment

- Node Version:     v16.20.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-jztfdl?file=pages%2Findex.vue

### Describe the bug

We will get two warnings like the following logs

When we use jsx synax,even and we don't wirte any code that can effect server render:

```tsx
import { defineComponent } from 'vue';

export const testComponent = defineComponent(
  () => {
    const templateText = 'my text';
    return () => <div>hello wrold {templateText}</div>;
  },
  {
    name: 'test-component',
  }
);
```

but still mistach.

### Additional context

<img width="421" alt="image" src="https://github.com/nuxt/nuxt/assets/24537993/8cdefaac-6eba-4002-9cd9-b76a0bf4a4bc">

I don't know why they are different.

(vnode.children !== node.data).

Maybe it's a error of render.

### Logs

```shell-script
[Vue warn]: Hydration text mismatch:
- Client: "hello wrold my text"
- Server: "hello wrold " 
  at <TestComponent> 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouteProvider key="/" vnode= Object route= Object  ... > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <App key=3 > 
  at <NuxtRoot>





[Vue warn]: Hydration children mismatch in <div>: server rendered element contains fewer child nodes than client vdom. 
  at <TestComponent> 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouteProvider key="/" vnode= Object route= Object  ... > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <App key=3 > 
  at <NuxtRoot>
```

**Comment by Ives7** [comment]
<img width="642" alt="image" src="https://github.com/nuxt/nuxt/assets/24537993/30add6a3-a6cb-4866-85ab-de0b1bfbf52f">
I found the question when i debug.
The vnode children has two elements,but the vchildren only attach the first child:

**`(createTextVNode('你的名字是: '))`**

It will ignore the scecond child.

**Comment by danielroe** [comment]
This is not a Nuxt issue and is likely a core Vue SSR bug with TSX. Would you check to see if it already exists in https://github.com/vuejs/core and if not, raise an issue?

You can use https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter to create a reproduction. 🙏

**Comment by Ives7** [comment]
> This is not a Nuxt issue and is likely a core Vue SSR bug with TSX. Would you check to see if it already exists in https://github.com/vuejs/core and if not, raise an issue?
> 
> You can use https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter to create a reproduction. 🙏

Sure,let me try.

**Comment by Ives7** [comment]
> This is not a Nuxt issue and is likely a core Vue SSR bug with TSX. Would you check to see if it already exists in https://github.com/vuejs/core and if not, raise an issue?
> 
> You can use https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter to create a reproduction. 🙏

you're right,the problem is same when i don't use nuxt.
i will close this issue,thanks bro.

**Comment by danielroe** [comment]
No problem! Glad I could help 😊
