### ISSUE TITLE
async transform is not processing `setup()` in options api

### ISSUE THREAD

**Issue by dimakornev13** [nuxt/nuxt#22570]
### Environment

- Operating System: Linux
- Node Version:     v20.4.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@9.7.2
- Builder:          vite
- User Config:      target, experimental, vite, nitro, app, modules, imports, runtimeConfig, router, css, build
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, yandex-metrika-module-nuxt3@1.5.3, @pinia/nuxt@0.4.11
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-nhdvsy?file=pages%2Findex.vue

### Describe the bug

- set target to 'static' in 'nuxt.config.ts'
- make two pages at least
- run 'npm run generate'

I expect every single generated static file will be contain title tag, but just the last one contains it.

**Comment by manniL** [comment]
As you use `$fetch`, the data will not be serialized on the server. Can you try using `useFetch` instead.

PS: `target: 'static'` does not do anything anymore.

**Comment by dimakornev13** [comment]
I changed $fetch to useFetch, and now it give the 500 error during prefetching... 
command `npm run dev` gives the next error: "A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug..."

(changed) https://stackblitz.com/edit/github-nhdvsy?file=pages%2Findex.vue

**Comment by danielroe** [comment]
A workaround for now is to use `<script setup>` or you can do this:

```ts
const nuxtApp = useNuxtApp();
const { data: page } = await useFetch(
  'https://jsonplaceholder.typicode.com/posts/2'
);
const { data: list } = await useFetch(
  'https://jsonplaceholder.typicode.com/posts/2/comments'
);

nuxtApp.runWithContext(() =>
  useSeoMeta({
    title: page.value.title,
    description: page.value.body,
  })
);
```

https://stackblitz.com/edit/github-nhdvsy-gcugdp?file=pages/index.vue,nuxt.config.ts
