### ISSUE TITLE
Infinite redirect in navigation guard

### ISSUE THREAD

**Issue by 11003** [nuxt/nuxt#22578]
### Environment

{
  "name": "nuxt-app",
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/devtools": "latest",
    "@types/node": "^18.17.3",
    "nuxt": "^3.6.5"
  }
}

### Reproduction

-

### Describe the bug

Infinite redirect in navigation guard

### bug address

https://codesandbox.io/p/sandbox/recursing-davinci-f6p5pf?file=%2Fsrc%2Fmiddleware%2Fauth.global.js%3A2%2C1-7%2C4

**Comment by 11003** [comment]
https://codesandbox.io/p/sandbox/recursing-davinci-f6p5pf?file=%2Fsrc%2Fmiddleware%2Fauth.global.js%3A2%2C1-7%2C4

**Comment by manniL** [comment]
You should exclude `/login` from your auth middleware checks ☺️

**Comment by 11003** [comment]
Thank you!🥰
