### ISSUE TITLE
Layout artifacts after navigateTo in middleware

### ISSUE THREAD

**Issue by mike-kramer** [nuxt/nuxt#22582]
### Environment

- Operating System: Linux
- Node Version:     v18.16.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

and stackblitz

### Reproduction

https://stackblitz.com/edit/nuxt-starter-cpu4vf?file=app.vue

Go in browser to https://nuxtstartercpu4vf-yzbo--3000--d5d65229.local-credentialless.webcontainer.io/login?loggedIn=1

You will see two footers.

### Describe the bug

If two page have different layout, after navigateTo in client only middleware, there are artifacts of layout from the page redirected from.

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/22472.
