### ISSUE TITLE
middleware added from modules aren't typed properly in definePageMeta

### ISSUE THREAD

**Issue by Hebilicious** [nuxt/nuxt#22584]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.5.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@9.8.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Minimal reproduction : https://github.com/Hebilicious/nuxt-middleware-repro
(There is a Stackblitz but the TS error doesn't show-up there)

Initial reproduction by Shhu : https://github.com/Shhu/auth-nuxt-repro-signin-return

### Describe the bug

<img width="761" alt="image" src="https://github.com/nuxt/nuxt/assets/13395944/5370c267-e2d5-4ed0-bc0e-3cfc4964fb36">

Route middleware names that comes from modules should be merged with the local middleware types. They are not added.
This could be an issue with NuxtKit `addRouteMiddleware`, maybe the types need to be manually extended ?
In this case we could document this in nuxt kit docs.

**Comment by danielroe** [comment]
Calling `addRouteMiddleware` within a plugin isn't going to be able to tell Nuxt about types. Instead you use `addNuxtRouteMiddleware` from kit, which should work :+1: (Or you can manually augment the types.)
