### ISSUE TITLE
useHead cannot access nuxt context

### ISSUE THREAD

**Issue by yunyuyuan** [nuxt/nuxt#22590]
### Environment

```
------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Reproduction

https://stackblitz.com/edit/nuxt-starter-dfuuoo?file=app.vue

### Describe the bug

`computed()` inside `useHead()` cannot access nuxt context like `useState()`

here is error:
```
[nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at `https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables`.
```

**Comment by danielroe** [comment]
This is an expected limitation. Instead, access `useState` outside of `useHead` and reference that state within the computed property you pass to `useHead`.

**Comment by yunyuyuan** [comment]
@danielroe But why `useSeoMeta` work fine?It has similar functionality to `useHead`
