### ISSUE TITLE
nuxt.config.ts runtimeConfig is giving build time value

### ISSUE THREAD

**Issue by suningkooboo** [nuxt/nuxt#22594]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.16.1
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.4
- Builder:          vite
- User Config:      ssr, experimental, runtimeConfig, modules, ui, tailwindcss, i18n, viewport, proxy, imports, devServer, devtools, typescript
- Runtime Modules:  @nuxt-alt/proxy@2.2.3, @nuxtjs/google-fonts@3.0.1, @nuxt/image@1.0.0-rc.1, nuxt-icon@0.4.2, @nuxtjs/i18n@8.0.0-rc.2, nuxt-viewport@2.0.6, nuxt-swiper@1.1.1, @nuxthq/ui@2.7.0-28183458.9e5b8cc, @vueuse/nuxt@10.2.1, @kevinmarrec/nuxt-pwa@0.17.0

### Reproduction

We are using Nuxt Layers. In layer project, set .env key-value to nuxt.config.ts runtimeConfig
```
runtimeConfig: {
  key: process.env.key
}
```
set key value to "1" and yarn build
change key value to "2" and yarn preview

### Describe the bug

In Reproduction we found useRuntimeConfig().key is giving different value with process.env.key. useRuntimeConfig() is giving a build time value "1".

**Comment by danielroe** [comment]
Runtime config needs to be overridden with a particular environment variable name. So in your case it would need to be overridden with `NUXT_KEY`.

See https://nuxt.com/docs/guide/going-further/runtime-config#environment-variables.
