### ISSUE TITLE
Documentation - app.config.ts

### ISSUE THREAD

**Issue by abarke** [nuxt/nuxt#22595]
### Describe the feature

There is some documentation about how to define the config, however no example of how to use it.
https://nuxt.com/docs/guide/directory-structure/app-config

Could you please provide some examples and use cases?

I'm struggling how to use it. How does this differ from the `runtimeConfig.public` ? 
https://nuxt.com/docs/api/configuration/nuxt-config#runtimeconfig

I tried this with no success...

### app.config.ts
```ts
export default defineAppConfig({
  foo: "bar",
});
```

### app.vue
```ts
const nuxtApp = useNuxtApp();

console.log(nuxtApp.$config.foo); // undefined
```

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
You use it with `useAppConfig()`, which can be used in both the vue and nitro parts of your app.

I think there's an example here: https://nuxt.com/docs/guide/directory-structure/app-config#defining-app-config. But I'd be very open for any improvements/examples in the docs.
