### ISSUE TITLE
Provide convenient option to skip `useAsyncData`'s cache

### ISSUE THREAD

**Issue by hymair** [nuxt/nuxt#22608]
### Describe the feature

It's a pretty common case to have a dynamic page like `/invoice/<invoiceId>` and also `/invoice/<invoiceId>/edit` for editing this invoice. After editing, we want to redirect the user back to `/invoice/<invoiceId>`, where we are calling `useAsyncData`, of course. However, the result of that call is still returning the cached response from before the edit was done.

As I understand it, we can provide a unique key to achieve this:
```ts
const { data: invoice } = await useAsyncData(
    Date.now().toString(),
    () => $api.invoices.findOne(company.value.id, invoiceId)
)
```
But I think it would be convenient to be able to skip the cache entirely with just a simple option:
```ts
const { data: invoice } = await useAsyncData(
    () => $api.invoices.findOne(company.value.id, invoiceId),
    { force: true }
)
```

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by hichem-dahi** [comment]
Use `refreshNuxtData` to invalidate the cached response.

See example [here](https://nuxt.com/docs/api/utils/refresh-nuxt-data#refreshnuxtdata)

**Comment by danielroe** [comment]
This should now be possible in https://github.com/nuxt/nuxt/pull/20747.

**Comment by hymair** [comment]
@danielroe Great! Can you please provide an example how to use it? Should just return `null` from the `getCachedData` function?

**Comment by danielroe** [comment]
I added an example in the description of the linked pr.
