### ISSUE TITLE
Plugin created from a template doesn't get registered into `plugins.d.ts`

### ISSUE THREAD

**Issue by andriepu** [nuxt/nuxt#22617]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:    ` v16.20.0`
- Nuxt Version:    `3.6.5`
- Nitro Version:    `2.5.2`
- Package Manager:  `npm@9.4.2`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `./modules/hello.ts`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-avmg3e

Run: `nuxi prepare`

### Describe the bug

Starting from nuxt `3.5.0`, plugins created by template (`addPluginTemplate` / `addTemplate` -> `addPlugin`) don't get registered to `.nuxt/types/plugins.d.ts` when generated inside the `.nuxt` folder.

As we can see from the reproduction repo, the `InjectionType<typeof import("../plugins/hello").default>` is missing from the `plugins.d.ts`.

It causes the `useNuxtApp().$hello` type to be `unknown`.

### Additional context

If we generate the template outside the `.nuxt` folder, it requires running `nuxi prepare` **at least twice** to make it registered to `.nuxt/types/plugins.d.ts`.

Reproduction: https://stackblitz.com/edit/nuxt-starter-9mc6yi

**Comment by danielroe** [comment]
This is almost certainly because we do not include files that do not exist in the types:
https://github.com/nuxt/nuxt/blob/b5b2b47feb19b5c4b7c1fb4dcdbceadc89505f8f/packages/nuxt/src/core/templates.ts#L101

But on first running `nuxi prepare` command, the file does not yet exist.
