### ISSUE TITLE
Vite makes two requests on initial dev server start

### ISSUE THREAD

**Issue by jd-solanki** [nuxt/nuxt#22629]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.6.5`
- Nitro Version:    `2.5.2`
- Package Manager:  `pnpm@8.5.1`
- Builder:          `vite`
- User Config:      `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/jd-solanki/playgrounds/tree/nuxt-middleware-called-twice

<img width="698" alt="image" src="https://github.com/nuxt/nuxt/assets/47495003/18bc6e8d-900a-4f19-af34-6bb6f29fa3bd">

### Describe the bug

In my original application I have ACL setup which works weirdly. I inspected and found that initially when I visit the URL middleware is called twice.

### Additional context

I have real life ACL setup which redirects the user from login to home (if logged in) and index route decides where to redirect again based on user role. While performing this I'm facing some weird issue and drilled down to this.

Can above mentioned redirection leads to warnings like "[nuxt] Calling useRoute within middleware may lead to misleading results. Instead, use the (to, from) arguments passed to the middleware to access the new and old routes." 🤔

Daniel [response](https://discord.com/channels/473401852243869706/897487139888062506/1140565785933262879) on discord.

**Comment by danielroe** [comment]
Does this replicate in production?

Does this replicate on the second request to the dev server?

**Comment by jd-solanki** [comment]
For the first time, it works fine. However, when we restart the server, it gets called twice:

https://github.com/nuxt/nuxt/assets/47495003/dfc8cf66-76e9-4055-8c8f-d6477a0daccf

> Does this replicate in production?

In production, it gets called once


https://github.com/nuxt/nuxt/assets/47495003/cba9be43-d1e1-4dff-97ca-8a6cd074917a

> Does this replicate on the second request to the dev server?

Sorry I didn't get what you mean! Do you mean below?

https://github.com/nuxt/nuxt/assets/47495003/fae574e9-e641-42f4-8181-d8077117eaca

---

According to my debugging, it looks like when nuxt tries to auto reload the page middleware is called twice as you can seen in last video 🤔

**Comment by danielroe** [comment]
I can no longer reproduce this. If it's still occurring for you, please provide a reproduction and I'll look into it again 🙏
