### ISSUE TITLE
Middleware not working for prerendered routes in described in routeRules

### ISSUE THREAD

**Issue by RomanSkrypnik** [nuxt/nuxt#22630]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.5.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      devtools, routeRules
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

**Github link**: https://github.com/RomanSkrypnik/nuxt-prerenders-issue

Steps to reproduct:
1. `yarn install`;
2. `yarn build`;
3. `yarn start`;
4. Watch server console for `'test middleware'`;

### Describe the bug

Added `/` route page to `routeRules` for optimization purposes.
Noticed that middleware works fine with `yarn dev` but not working in build

### Additional context

![image](https://github.com/nuxt/nuxt/assets/44501848/a3a4b4e4-ce0f-4488-8f7a-7847fcd25126)

**Comment by danielroe** [comment]
What is the issue?

The middleware is not called when requesting the prerendered page, right? It's expected that when hitting a prerendered route the response should be directly returned without hitting the Vue rendering process or loading Nuxt plugins/middleware.

**Comment by RomanSkrypnik** [comment]
Understood
Thanks for answer, @danielroe!
