### ISSUE TITLE
`useSeoMeta` does not use `useHead` title template

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt/nuxt#22641]
### Environment

starter template from nuxt.new

### Reproduction

https://stackblitz.com/edit/github-vafbpu?file=app.vue

### Describe the bug

Hello,

When I set up a title template using `useHead`:

```ts
useHead({
  titleTemplate: '%s - site title',
});
```

I expected that `ogTitle` and `twitterTitle` get the template in the `useSeoMeta` composable.

```ts
useSeoMeta({
  ogTitle: 'og title',
  twitterTitle: 'twitter title',
});
```

At the end, I got: 

```html
<title>Welcome to Nuxt! - site title</title>
<meta property="og:title" content="og title"> <!-- No 'site title' -->
<meta name="twitter:title" content="twitter title"> <!-- No 'site title'-->
```

I don't know if it is a bug or something that is wanted but I think that having an option to automatically add the suffix can help.

**Comment by Barbapapazes** [comment]
@harlan-zw, I'm tagging know cause I know your the SEO guy and I don't know if this issue could be post somewhere else!

**Comment by harlan-zw** [comment]
Going to close this as I don't think there's anything actionable outside of these work arounds

**Comment by blowsie** [comment]
> Thanks for the issue, it's an interesting one.
> 
> I'm not really sure what is more intuitive from a user's point of view, but adding support for titleTemplate at this point will cause too many issues.
> 
> There are a few other workarounds that I'd say are more elegant anyway:
> 
> 1. Use template paarams
> 
> ```ts
> useHead({
>   templateParams: {
>     siteName: 'site title',
>   },
>   titleTemplate: '%s %separator %siteName',
> });
> 
> useSeoMeta({
>   ogTitle: '%s %separator %siteName',
>   twitterTitle: '%s %separator %siteName',
> });
> ```
> 
> See https://stackblitz.com/edit/github-vafbpu?file=app.vue
> 
> 2. Use https://github.com/harlan-zw/nuxt-seo-experiments
> 
> Adds a plugin which auto-sets these titles https://unhead.harlanzw.com/addons/plugins/infer-seo-meta-tags

Thanks for this.
Some observations:

1. Use template params
This title templating is not working for `ogTitle` and `twitterTitle`

2. Use https://github.com/harlan-zw/nuxt-seo-experiments
The [ infer seo meta ](https://unhead.unjs.io/plugins/plugins/infer-seo-meta-tags) only handles `ogTitle` and `ogDescription`, `twitterTitle` and `twitterDescrtiption`

**Comment by blowsie** [comment]
I think this could be a bug in the nuxt devtools the preview is not reflecting the config.

**Comment by n0099** [comment]
It seems unhead plugin `inferSeoMeta` won't [apply](https://github.com/unjs/unhead/blob/14853282c7c70399b1d3d4cd70ee884119e59e3f/packages/addons/src/plugins/inferSeoMetaPlugin.ts#L30-L43) any [`titleTemplate`](https://github.com/n0099/open-tbm/blob/1aaa2f1b8a6eef419598c1eb1d818c67a2fe472d/fe/src/app.vue#L21) configured by `useHead({...})`.
