### ISSUE TITLE
Detect if in CSR or SSR

### ISSUE THREAD

**Issue by yooneskh** [nuxt/nuxt#22643]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      extends, modules, gtag
- Runtime Modules:  nuxt-gtag@0.5.9
- Build Modules:    -
------------------------------

### Reproduction

None needed

### Describe the bug

How can i detect in what mode the currect code is being run? (Not in what side)

What i want to do is to have a composable for storing a persistent state, but this must correctly choose between Cookie and LocalStorage based on the rendering mode. I want something like this

```js
export function usePersistentState(key, factory) {

  if () {
    return useCookie ...... ;
  }
  
  if () {
    return useLocalStorage ..... ;
  }

  return ref .... ;

}
```

The reason i need this is because i use the same code and deploy it on a server for a SSR enabled website, and also deploy it as a mobile application using Capacitor. For SSR i use `yarn build` and for the mobile apps i use `yarn generate` so i will need the code to detect which one was used. I am fine if a special ENV is set on either of these modes. If there is none set i suppose i have to do it myself.

The second question is whether the unneeded imports (useCookie and useLocalStorage) be treeshaked in the irrelevant mode? So for example if i am doing `yarn build` and the code detects that and would never go into the `useLocalStorage` path, will that import be treeshaked?

Thank you very much for your amazing work!

### Additional context

Note that i need this to do the correct thing if the current path has been loaded in CSR mode because of a route rule.

**Comment by toto6038** [comment]
Though not documented, I am using `process.client && document` to test if the script is running on server-side or client-side. I am thinking the authors may not provide this composable intentionally, their recommended way is using `.client` on your component name or wrap it in `<ClientOnly>`

**Comment by yooneskh** [comment]
@toto6038 Doesn't this make the code run twice, once for when it is in the server side and once when it is in the client side? and each time a different if would run? (According to the snippet i provided)

**Comment by toto6038** [comment]
@yooneskh The snippet is used in a if statement, which only evaluates to true on client side

**Comment by yooneskh** [comment]
@toto6038 true, but i want to use it like this.

```js
export fundtion useMyState() {
  const isClient = Boolean(process.client && document);
  if (isClient) {
    return xxx ;
  }
  if (!isClient) {
   return yyy ;
  }
}
```

If i have it like this, then this function will run once in the server and return `yyy` and then while hydrating in the client, it will run `xxx`, unless hydration does something special.

I'm more thinking of something like this

```js
export fundtion useMyState() {
  if (import.meta.IS_SSR) {
    return xxx ;
  }
  else {
   return yyy ;
  }
}
```

**Comment by danielroe** [comment]
You can detect if a page is rendered on server with `process.server` and if the first page of a site _was_ rendered on server with `process.client && useNuxtApp().payload.serverRendered`.

So something like:

```ts
if (process.server || (process.client && useNuxtApp().payload.serverRendered)) {
  return 'xxx';
}
```

Because, as you pointed out, it's possible for routeRules to determine whether a page is server rendered, it's not possible to tree-shake this code out of the build if you are using `useNuxtApp().payload.serverRendered`. (But anything guarded by `process.client`/`process.server` will be tree-shaken as you expect.)
