### ISSUE TITLE
In dev, request header `x-forwarded-for` value is written as `::1` from only client side data fetching

### ISSUE THREAD

**Issue by jongmin4943** [nuxt/nuxt#22656]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v16.14.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.6.3
- Builder:          vite
- User Config:      runtimeConfig, app, modules, css, components, vite
- Runtime Modules:  @nuxt/devtools@0.4.6        
- Build Modules:    -
------------------------------

### Reproduction

It doesn't reproduced on StackBlitz.

```ts
// /server/middleware/log.ts
export default defineEventHandler((event) => {
    const cRemoteAddress = event.node.req.connection.remoteAddress;
    const sRemoteAddress = event.node.req.socket.remoteAddress;
    const xForwardedFor = event.node.req.headers['x-forwarded-for'];
    console.log('cRemoteAddress : ', cRemoteAddress);
    console.log('sRemoteAddress : ', sRemoteAddress);
    console.log('xForwardedFor : ', xForwardedFor);
    console.log("------------------------------------------")
});
```
```ts
// /server/api/test.ts
let count = 0;
export default defineEventHandler(() => {
    console.log('called!');
    return count++;
});
```
```vue
// app.vue
<template>
  <div>
    <button @click="() => refresh()">test</button>
    <span>{{ data }}</span>
  </div>
</template>

<script setup lang="ts">
const { data, refresh } = await useAsyncData<number>('useAsyncDataTest', () =>
    $fetch('/api/test')
);
console.log(data.value);
</script>
```

### Describe the bug

It is a similar issue with #18609.

1. Restart the `nuxt` -> open the page with `localhost:3000`
![image](https://github.com/nuxt/nuxt/assets/77711322/75af8cb9-79f1-4ff2-a113-aedd7e4bab63)

2. click the button to call 'refresh' method
![image](https://github.com/nuxt/nuxt/assets/77711322/cade26c0-7d0a-4eb0-8443-d2799da80f7b)

3. refresh the page
![image](https://github.com/nuxt/nuxt/assets/77711322/7f332636-1f06-4d83-a756-1d4af3f5f0fa)

I'm not sure it happens on prod mode but in dev mode, the request header `x-forwarded-for` value is written as `::1` which is IPv6 Loopback Address.
I guess it is from only client-side since it occurs when `refresh` method called, not refresh the page.
I'm not sure if it is intended behavior, but I think it should be consistent regardless of the rendering side.

**Comment by danielroe** [comment]
cc: @pi0

**Comment by manniL** [comment]
I can't repro this locally with `localhost:3000`, nor	`http://[::]:3000/` (all dev mode)

<img width="462" alt="image" src="https://github.com/nuxt/nuxt/assets/640208/109ce92e-7980-4e40-848e-b3d835886901">
