### ISSUE TITLE
建议为Nuxt.js开发文档添加中文版本（Suggestion to Add a Chinese Version for Nuxt.js Documentation）

### ISSUE THREAD

**Issue by okwinwin** [nuxt/nuxt#22655]
### Describe the feature

尊敬的Nuxt.js团队：

您好！我是一名来自中国的Nuxt.js开发者。首先，我想感谢您为开源社区所做的杰出贡献。Nuxt.js是一个非常强大和易用的框架，它极大地提高了我的开发效率。

然而，在使用Nuxt.js的过程中，我发现官方文档并没有中文版本。考虑到中文开发者社区的庞大规模和对Nuxt.js的广泛使用，我认为为开发文档提供中文版本将会对许多中文开发者带来极大的便利。

我理解翻译文档需要时间和资源，但我相信中文开发者社区会非常乐意参与这一过程，为Nuxt.js提供高质量的中文翻译。此外，中文文档将进一步推广Nuxt.js在中文开发者中的使用，为更多的开发者带来价值。

希望您能考虑这一建议，并期待Nuxt.js在未来能为更多的开发者提供更好的支持。

再次感谢您的辛勤工作和对开源社区的贡献！

祝好。

Dear Nuxt.js Team,

Greetings! I am a Nuxt.js developer from China. Firstly, I would like to express my gratitude for your outstanding contributions to the open-source community. Nuxt.js is an incredibly powerful and user-friendly framework that has significantly enhanced my development efficiency.

However, during my experience with Nuxt.js, I noticed that the official documentation does not have a Chinese version. Given the vast size of the Chinese developer community and the widespread use of Nuxt.js among them, I believe offering a Chinese version of the documentation would greatly benefit many Chinese-speaking developers.

I understand that translating documentation requires time and resources. However, I am confident that the Chinese developer community would be eager to participate in this process, providing high-quality Chinese translations for Nuxt.js. Moreover, a Chinese documentation would further promote the adoption of Nuxt.js among Chinese developers, bringing value to an even broader audience.

I kindly ask you to consider this suggestion, and I look forward to seeing Nuxt.js offer even better support for developers in the future.

Thank you once again for your hard work and dedication to the open-source community.

Best regards,

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by transtone** [comment]
https://ezdoc.cn/docs/nuxtjs

**Comment by baboon-king** [comment]
I've been using this "https://www.nuxt.com.cn"
But he seems to have a problem today.

**Comment by okwinwin** [comment]
> https://ezdoc.cn/docs/nuxtjs

哇，谢谢

**Comment by okwinwin** [comment]
> I've been using this ~"https://www.nuxt.com.cn"~ But he seems to have a problem today.
> 
> new link "https://nuxt.com.cn"

太好了，原来有这个。多谢多谢

**Comment by Hebilicious** [comment]
Related 
- https://github.com/nuxt/nuxt/issues/19926
- https://github.com/nuxt/nuxt/issues/21926

**Comment by 843905733** [comment]
> I've been using this ~"https://www.nuxt.com.cn"~ But he seems to have a problem today.
> 
> new link "https://nuxt.com.cn"

502 Bad Gateway

**Comment by ikxin** [comment]
也许你可以尝试一下 https://nuxt.zhcndoc.com
