### ISSUE TITLE
import.meta.server is undefined

### ISSUE THREAD

**Issue by a1mersnow** [nuxt/nuxt#22651]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.20.1`
- Nuxt Version:     `3.6.5`
- Nitro Version:    `2.5.2`
- Package Manager:  `pnpm@8.6.12`
- Builder:          `vite`
- User Config:      `app`, `ui`, `devtools`, `typescript`, `vue`, `modules`, `content`, `colorMode`, `vite`
- Runtime Modules:  `@nuxt/content@2.7.2`, `@nuxthq/ui@2.7.0-28200741.b8b7d74`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-2mnq8w?file=app.vue

### Describe the bug

Like the title said, `import.meta.server` is `undefined` in server console.
Inside the `import.meta`, there is only a `url` property

**Comment by danielroe** [comment]
Ah, unfortunately that's our mistake. The documentation is already updated, but `import.meta.{server|client}` are currently only available in edge and will be released in 3.7.

**Comment by a1mersnow** [comment]
@danielroe all right, thank you~

**Comment by danielroe** [comment]
resolved in https://github.com/nuxt/nuxt/commit/98c17e5d46b4096779b562ba28c68dfb3992d640.
