### ISSUE TITLE
app/router.options.ts 

### ISSUE THREAD

**Issue by gllinzbk1** [nuxt/nuxt#22659]
### Environment

nuxt3.5.3
nitro:2.5.2
vite v4.3.9

app/router.options.ts ：
```
import type { RouterConfig } from '@nuxt/schema'
import { createMemoryHistory,createWebHashHistory,createWebHistory } from 'vue-router'
// https://router.vuejs.org/api/interfaces/routeroptions.html
export default <RouterConfig> {
  history: base => import.meta.client ? createMemoryHistory(base) : null /* default */
}
```

### Reproduction

(https://github.com/gllinzbk1/nuxtgenerate)

### Describe the bug

after `npm run generate`,on apache,it can't remeber http://localhost/shop/carbon-mountain-bike/carbon-mountain-bike-rim/29er--

**Comment by manniL** [comment]
Could you provide more information?

**Comment by gllinzbk1** [comment]
> [http://localhost/shop/carbon-mountain-bike/carbon-mountain-bike-rim](http://localhost/shop/carbon-mountain-bike/carbon-mountain-bike-rim/29er--)


I need to remember the operation routes for static web pages that have been generated, 
such as http://localhost/shop/carbon-mountain-bike/carbon-mountain-bike-rim/index.html Generate a new route http://localhost/shop/carbon-mountain-bike/carbon-mountain-bike-rim/29er-- (There is no corresponding static webpage), refreshing or sending to others can access the new route normally.

**Comment by danielroe** [comment]
Apologies, `import.meta.client` will be supported in Nuxt 3.7 but isn't currently available. Right now you should use `process.client`.

**Comment by gllinzbk1** [comment]
> Apologies, `import.meta.client` will be supported in Nuxt 3.7 but isn't currently available. Right now you should use `process.client`.
> 
> Also, memory history is meant for server environments. On the client you should use `createWebHistory`.

In the new route, refreshing the page to retrieve data will retrieve the server and payload.json, which may not function properly

**Comment by danielroe** [comment]
`useFetch` automatically handles this behaviour. It will not refetch on client if it was fetched on the server. So you do not need to add custom logic to handle server/client behaviour.

**Comment by gllinzbk1** [comment]
reflesh:http://localhost/shop/carbon-mountain-bike/carbon-mountain-bike-rim/29er--
bug:
entry.bb23cab0.js:1 TypeError: Cannot read properties of null (reading 'data')

Data was originally a JSON, but after refreshing, it became HTML

**Comment by gllinzbk1** [comment]
Do I need to do this

 // let payload = {};
      // if(process.static && process.client && route.path !== '/')
      //   payload = await app.$axios.$get(document.location.origin + route.path + '/payload.json')
      // else
      //   payload.post = await app.$axios.$get(`/post.json`)
      //
      // return payload

**Comment by danielroe** [comment]
No. You can try adding `responseType: 'json'` to your `useFetch` options to force it to be read as a JSON.

**Comment by gllinzbk1** [comment]
![20230817-161724](https://github.com/nuxt/nuxt/assets/115514156/7035e287-f1eb-4455-a58f-b3643176d2cb)
![20230817-160836](https://github.com/nuxt/nuxt/assets/115514156/201491f0-8b3f-43ba-80f2-4f00bfcca055)

html data is homepage ,not data format

**Comment by danielroe** [comment]
Are you running a server or are you just deploying the prerendered pages?

**Comment by gllinzbk1** [comment]
> Are you running a server or are you just deploying the prerendered pages?

 just deploying the prerendered pages

**Comment by danielroe** [comment]
It seems that's the issue. The API request isn't going to work at runtime as there is no server to return the result.

**Comment by gllinzbk1** [comment]
I used the address of a third-party site for usefetch, and the content can be retrieved, but the retrieval method cannot obtain the result
like:
```
   const { data:data } = await useFetch('http://f.lgl.lb.in:8080/vueapi/list?url='+category+'&page=1')  
   //process.server
   // if (import.meta.env.SSR) {
    //    const { data:data } = await useFetch('/api/readjson',{      
    //   method: 'POST', // Post method works
    //   body: {
    //     category: category
    //   },
    //   responseType:'json'
    // })  
    const pdata = JSON.parse(data.value)
    console.log('apiDataLength',useSize(pdata),pdata,data)
```
and reflesh ,data.value get null
![image](https://github.com/nuxt/nuxt/assets/115514156/94d322cc-a57c-413b-8be5-9d685535b472)

**Comment by gllinzbk1** [comment]
I know where the problem lies. The rewrite rules for apache. htaccess cannot all go back to the homepage, it must go back to the current spa
