### ISSUE TITLE
scrollBehaviour plugin doesn't react on route changes anymore (after upgrading to Nuxt 6.5)

### ISSUE THREAD

**Issue by lazercaveman** [nuxt/nuxt#22663]
### Environment

- Operating System: Darwin
- Node Version:     v16.18.1
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  yarn@3.2.4
- Builder:          vite
- User Config:      app, routeRules, modules, vue, vite, nitro, css, postcss, runtimeConfig
- Runtime Modules:  @pinia/nuxt@0.4.11, @nuxt/devtools@0.7.1, @vueuse/nuxt@10.3.0, nuxt-jsonld@2.0.8
- Build Modules:    -

### Reproduction

When clicking a link the router plugin should get fired (and so for a  console log output should be visible within the console) - however it will only displayed when the app initially loads a document, not when clicking a link to trigger a route change. Also any other functionality defined within the plugin will only be fired when the first document is rendered...

### Describe the bug

Route plugin only gets executed when app starts, but doesn't get executed anymore when route changes. The route it self changes as is should, and the router itself seems to work as it should be...

### Additional context

Within my nuxt-3 project I am using a router plugin (plugins/router.scrollBehavior.js) which worked just fine - since the last update however it doesn't seems not to work anymore on route change. I reduced all the functionality to the minimum, so i can better test it: 

```js 
export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.$router.options.scrollBehavior = (to, from, savedPosition) => {
    console.log('test', to, from, savedPosition);
    return {
      x: 0,
      y: 0,
    };
  };
});
```

**Comment by danielroe** [comment]
We override and then restore scroll behaviour after the hydration. Instead, you should configure router scrollbehavior in here: https://nuxt.com/docs/guide/going-further/custom-routing#router-options

**Comment by lazercaveman** [comment]
@danielroe thnx for your answer, but in other threats it is recommended to define scroll behavior by defining a plugin: https://github.com/nuxt/nuxt/issues/12732#issuecomment-1397227098

Also the provided docs do not mention scroll behavior at all?? :D

**Comment by danielroe** [comment]
That was two years ago before we implemented `app/router.options`.

**Comment by lazercaveman** [comment]
alright, I think there are many threats mentioning that way for nuxt 3 as well, like this one https://github.com/nuxt/nuxt/issues/12732 (and a few more) ... anyways, the mentioned approach is working, so thnx @danielroe . : )

**Comment by danielroe** [comment]
If it's not mentioned in the docs, it might be nice to add it too.

**Comment by lazercaveman** [comment]
> If it's not mentioned in the docs, it might be nice to add it too.

I'll look if I can find some time to do it, and if so, I'll take it on... : )
