### ISSUE TITLE
Dynamic attributes are not rendered correctly on Firefox after page refresh

### ISSUE THREAD

**Issue by smastrom** [nuxt/nuxt#22666]
### Environment

```
------------------------------
- Operating System: Darwin
- Node Version:     v19.8.1
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.6.12
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Reproduction

[https://stackblitz.com/edit/nuxt-starter-g6fvbn?file=app.vue](https://stackblitz.com/edit/nuxt-starter-g6fvbn?file=app.vue)

### Describe the bug

If an attribute is toggled dynamically, on first-page load it is rendered correctly and works as expected.
After a full page refresh, the attribute is not rendered correctly anymore.

### Steps to reproduce

1. Open Firefox and visit the [reproduction](https://stackblitz.com/edit/nuxt-starter-g6fvbn?file=app.vue)
2. Click on `Toggle Button State`, this will enable the button as expected
3. Refresh the page (the StackBlitz one)
4. Notice that the button has no attribute `disabled`

### Additional context

The issue is not just on the dev server, It persists also in prod.

**Comment by smastrom** [comment]
Sorry if I haven't been clear enough, maybe a video is better. When I refresh the page, I expect the button to be disabled as the ref is initialized with `false`.

https://github.com/nuxt/nuxt/assets/60471784/38bfd77f-e637-495a-bdd8-5a5932d0f163

**Comment by smastrom** [comment]
Oki, thanks for clarifying.

**Comment by danielroe** [comment]
you're very welcome!

**Comment by danielroe** [comment]
Opened an issue here: https://bugzilla.mozilla.org/show_bug.cgi?id=1848982
