### ISSUE TITLE
Allow setting the layout dynamically without using NuxtLayout within pages

### ISSUE THREAD

**Issue by kilobyte2007** [nuxt/nuxt#22671]
### Describe the feature

For our website, we are loading pages from a Strapi backend. Those pages have a `layout` field which tells which layout should this page be rendered in. I made it work by using `<NuxtLayout :name="page.layout">` in our `[...slug].vue` page component.

The issue with this approach is that on each page change the whole layout and its components (i.e. the header, the footer) are re-rendered. Is there a way to either dynamically set the layout from within `useAsyncData` or make the layout be preserved between pages? If not - this would be a nice thing to have as full re-renders are not very optimal here.

Thanks a lot in advance!

Here's what it looks like now for reference:
```vue
<template>
  <NuxtLayout :name="page && page.layout ? page.layout : 'default'">
    <StrapiLandingPage v-if="page" :page="page" />
    <StrapiError v-else :code="404" :message="notFoundErrorMessage" />
  </NuxtLayout>
</template>

<script setup lang="ts">
import normalize from '~/utils/normalize'
const { params } = useRoute()
const { find } = useStrapi()

definePageMeta({
  layout: false
})

const notFoundErrorMessage = 'The page you are looking for was not found'

const slugs = [...params.slug].filter((s) => s)
const { data: page } = await useAsyncData(
  ['page', ...slugs].join('-'),
  async () => {
    let filters
    if (slugs.length === 0) {
      filters = {
        slug: {
          $null: true
        }
      }
    } else if (slugs.length === 1) {
      filters = {
        slug: {
          $eq: slugs[0]
        },
        category: {
          slug: { $null: true }
        }
      }
    } else if (slugs.length === 2) {
      filters = {
        slug: {
          $eq: slugs[1]
        },
        category: {
          slug: {
            $eq: params.slug[0]
          }
        }
      }
    } else {
      return null
    }

    const result = await find('landing-pages', {
      filters,
      populate: 'deep,6'
    })

    const pages = normalize(result)

    if (pages && pages.length > 0) {
      return pages[0]
    }
  }
)

if (!page.value && process.server) {
  throw createError({
    statusCode: 404,
    statusMessage: notFoundErrorMessage,
    fatal: true
  })
}
</script>
```

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
You can do something like:

```ts
const route = useRoute()
// get layout info
route.meta.layout = await $fetch('/api/my-layout') // or whatever
```

**Comment by kilobyte2007** [comment]
Sorry, but this still doesn't solve this issue, can I actually do this inside `useAsyncData`?

This doesn't work (simplified version):
```html
<template>
  <StrapiLandingPage v-if="page" :page="page" />
</template>

<script setup lang="ts">
import normalize from '~/utils/normalize'
const route = useRoute()
const { find } = useStrapi()

definePageMeta({
  layout: false
})

const { data: page } = await useAsyncData(route.params.slug, async () => {
  const page = await find('landing-pages', route.params.slug)

  route.meta.layout = page.layout
  return page
})
</script>
```

If I move `route.meta.layout = page.layout` out of the `useAsyncData` then it's working on the client side but still has a flash where it renders the page without a layout first, and it doesn't work at all on the server side (SRR). I've read the docs and I know that to make it work on the server side it has to either be done via a plugin or a middleware but I would still need to make a separate API call, which I don't want as the information about the layout is retrieved inside `useAsyncData`. Any other way to do this?

Thanks in advance!

**Comment by danielroe** [comment]
If you provide a reproduction I can tweak the code.

**Comment by kilobyte2007** [comment]
Will do, thanks!

**Comment by kilobyte2007** [comment]
Hi @danielroe,

I forgot to do this, but now I've met the same issue again.
Here's a reproduction - https://stackblitz.com/edit/nuxt-starter-z7rxtu?file=pages%2F%5B...slug%5D.vue

You can see that the Home and the Pricing pages are both using the default layout and I've included the `ComponentWithState` component to illustrate the idea that even if the page has the same layout - the layout component is re-rendered fully. I would like the layout to never re-render if it's the same layout across 2 pages.

Please let me know if there's a solution for this.

Thanks a lot in advance!

**Comment by danielroe** [comment]
For this, we have `setPageLayout` - if running on the server, this needs to be called before the layout starts rendering, so in a plugin or `app.vue`.

**Comment by kilobyte2007** [comment]
@danielroe  yes, but what if the layout is defined by the page which is retrieved from the API? It's a pretty common use case where we have the layout set up inside our headless cms. Is there a solution for this or am I missing something?
Thanks!

**Comment by danielroe** [comment]
I'm afraid that running it in the page setup function is too late, in the context of server rendering. The HTML for the layout has already been rendered at that point. 

You might be able to put it in an inline middleware defined in definePageMeta, as that will run before initialising the Nuxt app.

**Comment by kilobyte2007** [comment]
Thanks a lot! I made it work with an inline middleware, this is my code:

```vue
<template>
  <StrapiLandingPage v-if="$route.meta.page" :page="$route.meta.page" />
  <StrapiError v-else :code="404" :message="notFoundErrorMessage" />
</template>

<script setup lang="ts">
import normalize from '~/utils/normalize'
const { meta } = useRoute()

definePageMeta({
  middleware: [
    async function (to) {
      const { find } = useStrapi()
      const { params } = to

      const slugs = [...params.slug].filter((s) => s)
      let filters
      if (slugs.length === 0) {
        filters = {
          slug: {
            $null: true
          }
        }
      } else if (slugs.length === 1) {
        filters = {
          slug: {
            $eq: slugs[0]
          },
          category: {
            slug: { $null: true }
          }
        }
      } else if (slugs.length === 2) {
        filters = {
          slug: {
            $eq: slugs[1]
          },
          category: {
            slug: {
              $eq: params.slug[0]
            }
          }
        }
      } else {
        return
      }

      const result = await find('landing-pages', {
        filters,
        populate: 'deep,6'
      })

      const pages = normalize(result)

      if (pages && pages.length > 0) {
        const page = pages[0]
        to.meta.layout = page.layout || 'default'
        to.meta.page = page
      }
    }
  ]
})

const notFoundErrorMessage = 'The page you are looking for was not found'

if (!meta.page && process.server) {
  throw createError({
    statusCode: 404,
    statusMessage: notFoundErrorMessage,
    fatal: true
  })
}
</script>
```

Is it safe to pass the `page ` via the meta attribute or is there a different way?
