### ISSUE TITLE
Why is the version in. output/server/package.json inconsistent with the version in the unpackaged package.json

### ISSUE THREAD

**Issue by luckilyhang** [nuxt/nuxt#22678]
### Environment

 Operating System: `Windows_NT`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.5.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `srcDir`, `modules`, `elementPlus`, `imports`, `app`, `hooks`, `nitro`, `plugins`, `css`, `experimental`, `sourcemap`, `vue`
- Runtime Modules:  `@pinia/nuxt@0.4.11`, `@element-plus/nuxt@1.0.5`
- Build Modules:    `-`

### Reproduction

Why is the version in. output/server/package.json inconsistent with the version in the unpackaged package.json

Because the version number cannot be detected after packaging, the PM2 managed service cannot see the version number

### Describe the bug

Why is the version in. output/server/package.json inconsistent with the version in the unpackaged package.json

Because the version number cannot be detected after packaging, the PM2 managed service cannot see the version number

**Comment by luckilyhang** [comment]
项目根目录下的package.json 设置的版本号为1.0.1，但是打包后 生成的.output中package.json的version 是0.0.0

**Comment by luckilyhang** [comment]
The version number set for package.json in the project root directory is 1.0.1, but the version of package.json in the generated. output after packaging is

**Comment by danielroe** [comment]
cc: @pi0

Maybe we can respect this in the generated `package.json`?

**Comment by luckilyhang** [comment]
> cc: @pi0
> 
> Maybe we can respect this in the generated `package.json`?
what?How should this be resolved?

**Comment by pi0** [comment]
Seems good idea. Lets track in upstream: https://github.com/unjs/nitro/issues/new

**Comment by luckilyhang** [comment]
> Seems good idea. Lets track in upstream: [unjs/nitro#1598](https://github.com/unjs/nitro/issues/1598)

Do you want to manually change the version in. ouput/server/package.json?

**Comment by luckilyhang** [comment]
> 



> Seems good idea. Lets track in upstream: [unjs/nitro#1598](https://github.com/unjs/nitro/issues/1598)

Isn't this the version number automatically generated by reading the root directory?
