### ISSUE TITLE
reactive attribute not work in SSG

### ISSUE THREAD

**Issue by blacksheep107** [nuxt/nuxt#22674]
### Environment

windows
nuxt3.4.3

### Reproduction

```
// middleware/authority.global.ts

export default defineNuxtRouteMiddleware(async (to) => {
  if(!import.meta.env.SSR) {
    const { data } = await useFetch("/getUserAuthority");
    const store = useUserStore();  // pinia
    store.isAuth = data.value;
  }
})
```

```
// pages/index.vue

<script setup lang="ts">
const store = useUserStore();  // pinia
</script>

<template>
<div v-text="store.isAuth"></div>
123
{{ store.isAuth }}
</template>

```

Rendered page shows: 
**123 true**

The v-text tag is not reactive

### Describe the bug

Make xhr request only in client to get user auth, and set return data to pinia.
In page, use v-text="data" or attribute like :userRole="data", reactive not work, but use {{ data }} mastache, reactive work.

Is it bug or feature? If it's feature, why? Is there any recommend practice can I use to handle with scenarios that needs authentication?

### Additional context

My page have anony authority scene, and I want to make it a static site for seo and better performance.
For higher authority user, the page will show different data. My approach is to get auth info only in client, and set it in pinia, then the template watch pinia to update new data.

**Comment by danielroe** [comment]
This isn't a Nuxt issue, but to do with how pinia behaves or how Vue treats `v-text`. See if you can replicate without Nuxt: https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter. And

Also, your middleware should look like this instead:
```ts
    const data = await $fetch("/getUserAuthority");
```
