### ISSUE TITLE
The requested module '/_nuxt/node_modules/.pnpm/lodash.get@4.4.2/node_modules/lodash.get/index.js?v=facef416' does not provide an export named 'default'

### ISSUE THREAD

**Issue by hermesalvesbr** [nuxt/nuxt#22686]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.16.1
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2                                             18:17:33
- Package Manager:  pnpm@8.6.12
- Builder:          vite
- User Config:      extends, modules, vuetify, typescript, directus, devtools, imports
- Runtime Modules:  vuetify-nuxt-module@0.5.7, nuxt-directus@5.5.0
- Build Modules:    -
------------------------------

### Reproduction

` extends: ['@softagonsistemas/layer-button-download']`

I'm using layers, small pieces of my project I do in nuxt, like a button and call it in the main project which is also in nuxt.

My package is nuxt, my main project is nuxt, I just store it in packages and call it as extends.

In some cases it doesn't give any error, but in others the bug of looking for lodash.get@4.4.2 happens

I tried manually installing loadlash, however, the error persists.

### Describe the bug

When I use an layer extends, this error appears:
```
500
The requested module '/_nuxt/node_modules/.pnpm/lodash.get@4.4.2/node_modules/lodash.get/index.js?v=708021af' does not provide an export named 'default'
```

### Additional context

![Captura de tela de 2023-08-17 18-25-31](https://github.com/nuxt/nuxt/assets/379850/2ef27b58-6832-4a68-aab0-dc4d9a1b1224)

**Comment by danielroe** [comment]
Probably you need to add `lodash.get` to `vite.optimizeDeps`: see https://vitejs.dev/config/dep-optimization-options.html#optimizedeps-include.

**Comment by hermesalvesbr** [comment]
> Probably you need to add `lodash.get` to `vite.optimizeDeps`: see https://vitejs.dev/config/dep-optimization-options.html#optimizedeps-include.

```
"dependencies": {
    "@softagonsistemas/layer-button-download": "^0.0.5",
    "lodash.get": "^4.4.2",
    "lodash": "^4.17.21",
    "luxon": "^3.4.0"
  }
```
I'm not sure if I put it correctly, but the error persists. I agree with you that in the build the package is not going. I put this in nuxt.config.ts: 
```
 vite: {
        optimizeDeps: {
            include: [
                '@softagonsistemas/layer-button-download/components/**/*.vue',
                '@softagonsistemas/layer-button-download/pages/**/*.vue',
                '@softagonsistemas/layer-button-download/composables/**/*.vue',
                '@softagonsistemas/layer-button-download/',
            ],
        },
    },
```
The package that I want to call as a layer, it uses very old dependencies and related to files, I don't know if it's related, see the package of the external layer that I call in the project:
```
"dependencies": {
    "@json2csv/plainjs": "^7.0.2",
    "exceljs": "^4.3.0",
    "file-saver": "^2.0.5",
    "jspdf": "^2.5.1",
    "jspdf-autotable": "^3.5.31",
    "luxon": "^3.4.0"
  }
```
The **interesting** thing is that my project appears, only after ONE second that the 500 error message overlays my project.


https://github.com/nuxt/nuxt/assets/379850/211aa4d4-dd3f-4f5e-b75a-101a2f38a1d8

**Comment by hermesalvesbr** [comment]
I had misunderstood the use of vite.optimizeDeps, so I put it this way and it worked:
```
vite: {
        optimizeDeps: {
            include: [
                'lodash.get',
                'exceljs',
                'jspdf',
                'jspdf-autotable',
                'file-saver',
            ],
        },
    },
```

I tried not to put all the extension's packages, but it only worked when I put all the extension's dependencies.

Thanks @danielroe
