### ISSUE TITLE
`layout` property not working in `definePageMeta()`

### ISSUE THREAD

**Issue by szulcus** [nuxt/nuxt#22681]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v16.19.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      extends, app, imports, css, modules, vite, runtimeConfig, alias, build
- Runtime Modules:  nuxt-icon@0.2.11, nuxt-typed-router@3.2.5, nuxt-vitest@0.7.2, @nuxtjs/i18n@8.0.0-beta.10
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-jk2ltg?file=pages%2Ftest.vue

### Describe the bug

`<nuxt-layout>` component works fine, but `definePageMeta().layout` not working.

### Additional context

https://nuxt.com/docs/guide/directory-structure/layouts
https://nuxt.com/docs/guide/directory-structure/pages#page-metadata

**Comment by danielroe** [comment]
Your app.vue needs to contain `<NuxtLayout>`:

```vue
<template>
  <div>
    <nuxt-layout>
      <nuxt-page />
    </nuxt-layout>
  </div>
</template>
```

See https://nuxt.com/docs/guide/directory-structure/layouts#setting-another-layout.

**Comment by danielroe** [comment]
Your app.vue needs to contain `<NuxtLayout>`:

```vue
<template>
  <div>
    <nuxt-layout>
      <nuxt-page />
    </nuxt-layout>
  </div>
</template>
```

See https://nuxt.com/docs/guide/directory-structure/layouts#setting-another-layout.

**Comment by szulcus** [comment]
@danielroe Oh, you're right! I apologize for bothering you unnecessarily and thank you for the quick response ❤️

**Comment by danielroe** [comment]
No problem at all!
