### ISSUE TITLE
AbortController does not abort $fetch request when invoked server-side

### ISSUE THREAD

**Issue by arfedulov** [nuxt/nuxt#22684]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.16.0`
- Nuxt Version:     `^3.6.5`
- Nitro Version:    `-`
- Package Manager:  `npm@9.5.1`
- Builder:          `webpack`
- User Config:      `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/arfedulov/abort-controller-demo

Start dev server in the  demo project. Go to http://localhost:3000. 

See four links ( each one leads to the corresponding test case ). 

Open the first link. See that there are 10 Ok responses rendered on the page, even though the first successful response had to abort the rest 9 requests.

Go back to main page. Then go to the second link. See that there is only 1 Ok response and 9 null responses. This means 9 of the requests were abortet as expected.

### Describe the bug

When $fetch is called server-side AbortController's "abort" event is ignored.

There are four cases. The first one reproduces the bug, other three work as expected:

1) When calling `$fetch("/api/demo", { signal })` on server side, abort signal is ignored. Expected: the $fetch call is rejected with "AbortError".
2) When calling with full url `$fetch("http://localhost:3000/api/demo", { signal })` on server side, abort signal works as expected.
3) When calling native `fetch("http://localhost:3000/api/demo", { signal })` on server side, abort signal works as expected.
4) When calling `$fetch("/api/demo")` on server side with a wrapper that  emits "abort" event, abort signal works as expected.

**Comment by dulacp** [comment]
Have you looked into [this comment](https://github.com/unjs/ofetch/issues/23#issuecomment-1134481571)?

**Comment by danielroe** [comment]
The issue here is probably that `unenv` doesn't implement AbortController support within its fetch mocking, so 'direct' fetches (that bypass the network layer) are not cancellable.

I've opened https://github.com/unjs/unenv/issues/153 to track.
