### ISSUE TITLE
在 Nuxt 3.0 中，useFetch 的 onResponse 在 onMounted 中无法被执行

### ISSUE THREAD

**Issue by moqi-y** [nuxt/nuxt#22688]
### Environment

Nuxt project info:                                                                                                                                                         10:45:42

------------------------------
- Operating System: Windows_NT
- Node Version:     v16.15.1
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.2
- Package Manager:  npm@8.11.0
- Builder:          vite
- User Config:      pages
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

```javascript
<script setup>
/**
 * 请求api接口
 * @returns {Promise<any>}
 */
const getData = async () => {
    const { data, pending, error, refresh } = await useFetch('/api/test', {
        onResponse({ request, response, options }) {
            // 处理响应数据
            // localStorage.setItem('token', response._data.token)
            console.log("响应成功数据：", response);
        }
    })

    console.log("data:", data);
}

onMounted(() => {
    getData()
})
</script>

```

### 描述：

在我使用 Nuxt 3.0 的 useFetch 功能时，我发现了一个问题。如果我在 onMounted 的生命周期钩子中调用 useFetch，onResponse 似乎无法获取结果，或者说 onResponse 方法没有被执行。然而，如果我直接在 setup 中调用 useFetch，onResponse 就会被执行。这是我的代码：

```javascript
<script setup>
/**
 * 请求api接口
 * @returns {Promise<any>}
 */
const getData = async () => {
    const { data, pending, error, refresh } = await useFetch('/api/test', {
        onResponse({ request, response, options }) {
            // 处理响应数据
            // localStorage.setItem('token', response._data.token)
            console.log("响应成功数据：", response);
        }
    })

    console.log("data:", data);
}

onMounted(() => {
    getData()
})
</script>
```
### 重现步骤：

1. 创建一个新的 Nuxt 3.0 项目。
2. 在 onMounted 的生命周期钩子中调用 useFetch。
3. 观察控制台，无法看到 "响应成功数据" 的日志输出。

**期望的行为：**
onResponse 在 onMounted 中被正确执行，并在控制台输出 "响应成功数据"。

**实际的行为：**
onResponse 在 onMounted 中没有被执行。

**环境信息：**
Nuxt.js 版本：3.0
浏览器版本：Firefox 116.0.3 (64 位)
操作系统：Windows 11
Node.js 版本：16.15.1

**附加信息：**
我尝试在 setup 中直接调用 useFetch，这时 onResponse 可以被正确执行。

*****

### Description:

While using the useFetch feature in Nuxt 3.0, I encountered a problem. If I call useFetch in the onMounted lifecycle hook, onResponse seems unable to obtain a result, or in other words, the onResponse method is not executed. However, if I call useFetch directly in setup, onResponse is executed. Here is my code:

```javascript
<script setup>
/**
 * Request API interface
 * @returns {Promise<any>}
 */
const getData = async () => {
    const { data, pending, error, refresh } = await useFetch('/api/test', {
        onResponse({ request, response, options }) {
            // Processing response data
            // localStorage.setItem('token', response._data.token)
            console.log("Successful response data:", response);
        }
    })

    console.log("data:", data);
}

onMounted(() => {
    getData()
})
</script>
```
### Steps to reproduce:
Create a new Nuxt 3.0 project.
Call useFetch in the onMounted lifecycle hook.
Observe the console, the "Successful response data" log output is not visible.

### Expected behavior:
onResponse is correctly executed in onMounted, and "Successful response data" is output to the console.

### Actual behavior:
onResponse is not executed in onMounted.

### Environment Information:
Nuxt.js version: 3.0
Browser version: Firefox 116.0.3 (64-bit)
Operating System: Windows 11
Node.js version: 16.15.1

### Additional Information:
When I try to call useFetch directly in setup, onResponse is correctly executed.

### Additional context

完整代码如下（The complete code is as follows）：
``` vue
<!-- index.vue -->
<template>
    <div>
        <h1>欢迎来到我的首页</h1>
    </div>
</template>

<script setup>
/**
 * 请求api接口
 * @returns {Promise<any>}
 */
const getData = async () => {
    const { data, pending, error, refresh } = await useFetch('/api/test', {
        onResponse({ request, response, options }) {
            // 处理响应数据
            // localStorage.setItem('token', response._data.token)
            console.log("响应成功数据：", response);
        }
    })

    console.log("data:", data);
}

onMounted(() => {
    getData()
})


</script>

<style scoped></style>  
```

**Comment by vis97c** [comment]
Quick suggestion, let me know if it does helps.

```vue
<template>
    <div>
        <h1>{{data}}</h1>
    </div>
</template>

<script setup>
    const { data, pending, error, refresh } = useFetch('/api/test', {
        onResponse({ request, response, options }) {
            // 处理响应数据
            // localStorage.setItem('token', response._data.token)
            console.log("响应成功数据：", response);
        }
    })
</script>
```

**Comment by danielroe** [comment]
You should not call `useFetch` in mounted; it's a composable meant to be used in the setup function, not in the mounted hook. If you want to perform a fetch, you can call `$fetch`.

See also https://alex.party/posts/2023-09-17-usefetch-in-nuxt-3-the-proper-way

**Comment by moqi-y** [comment]
Thank you for your answers. Thank you very much
