### ISSUE TITLE
Argument of type '"schema-org:meta"' is not assignable to parameter of type 'HookKeys<RuntimeNuxtHooks>'.ts

### ISSUE THREAD

**Issue by avinean** [nuxt/nuxt#22692]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      modules
- Runtime Modules:  nuxt-schema-org@2.2.0
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-4upfvy?file=plugin%2FschemaOrg.ts

### Describe the bug
Run `npx vue-tsc`
```ts
  nuxtApp.hooks.hook('schema-org:meta', (meta) => {})
```
Argument of type '"schema-org:meta"' is not assignable to parameter of type 'HookKeys<RuntimeNuxtHooks>'.ts

**Comment by avinean** [comment]
@harlan-zw 
did I miss to configure something?

**Comment by harlan-zw** [comment]
Working on a fix for this, will be released soon. Thanks for flagging

**Comment by harlan-zw** [comment]
Going to track this in the upstream
