### ISSUE TITLE
Unable to fetch data on client side if useNuxtData used before useFetch

### ISSUE THREAD

**Issue by RomanSkrypnik** [nuxt/nuxt#22696]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.5.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

**Github**: https://github.com/RomanSkrypnik/nuxt-server-false-issue
**Videos**:
1. https://monosnap.com/direct/UYhZDjC21caXQAovqKsuAGyEMm4Pi0
2. https://monosnap.com/direct/lDKGf7wxSvv58r6TTCPuIk0ZNRk7KH

### Describe the bug

Using `useNuxtData` before `useFetch` on client side prevents request to API
If I try to comment/remove `useNuxtData` before `useFetch` - it will work just fine
Also, using `useNuxtData` with `useFetch` on server side works fine

**Comment by dimonixx** [comment]
I'm facing the same issue.  I've found following in the source code 

`useNuxtData`  initializes the `key ` in the nuxt app payload here: https://github.com/nuxt/nuxt/blob/a5cc858a4c390fc4d95a39d6c0851da60f381350/packages/nuxt/src/app/composables/asyncData.ts#L342 and `nuxt.payload.data[key] = null`

`useFetch` uses `useAsyncData` , which checks if `nuxt.payload.data[key]` ist not undefined - `hasCachedData` will be always true , after calling `useNuxtData`:
https://github.com/nuxt/nuxt/blob/a5cc858a4c390fc4d95a39d6c0851da60f381350/packages/nuxt/src/app/composables/asyncData.ts#L144

**Comment by darioferderber** [comment]
@RomanSkrypnik @dimonixx have you tried with the latest release (**3.8.1**)?
