### ISSUE TITLE
✨ Add `directoryAsNamespace` option like `unplugin-vue-components`

### ISSUE THREAD

**Issue by jd-solanki** [nuxt/nuxt#22690]
### Describe the feature

Hi 👋🏻 

I've been migrating my Vue app to Nuxt app and found that I have to rename all of my auto imported components because nuxt doesn't support `directoryAsNamespace` option to ommit prefixing the dir name to the components.

I already asked this in discord & checked the types of `components.dirs` option in `nuxt.config.ts` and it seems nuxt doesn't have this feature.

I've stopped migrating assuming nuxt will add support for those who will migrate to nuxt.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
You are looking for `pathPrefix` I think:

```ts
export default defineNuxtConfig({
  components: {
    dirs: [
      {
        path: '~/components',
        pathPrefix: false
      }
    ]
  }
})
```

You can also specify a custom prefix with `prefix` and customise options for specific folders.
