### ISSUE TITLE
The useFetch function sends 2 requests every time it is called

### ISSUE THREAD

**Issue by FatNerdPeng** [nuxt/nuxt#22700]
### Environment

nodejs: v18.17.3
nuxt: v3.6.5

### Reproduction

https://stackblitz.com/edit/nuxt-starter-kdgkx9

### Describe the bug

my code:
![image](https://github.com/nuxt/nuxt/assets/33616855/acfe4d2b-8387-443b-a98b-30e35c2be205)
When I click button “click me”, it will call function "submitForm" and the console will display:
![image](https://github.com/nuxt/nuxt/assets/33616855/d923abfe-5167-4bd0-bcd1-b13a01680879)
This only outputs once "111", indicating that this function was only called once, but the network request shows this:
![image](https://github.com/nuxt/nuxt/assets/33616855/082357a7-348f-4d5e-ba39-4fa5e78d6417)
This request will not respond correctly because it is just a request I casually wrote to demonstrate the problem, which does not hinder the problem I want to describe because the correct request I wrote in my work will also have the same problem,and it did send two requests to my server.
It is obvious that it has made two requests, and I suspect that this issue is related to the cache of nuxt. However, using the official combination function "clearNuxtData" is not helpful. So did I make a mistake somewhere?
Thanks!

**Comment by luc122c** [comment]
From looking at your code, I think this is the expected behaviour. [`useFetch`](https://nuxt.com/docs/api/composables/use-fetch) uses [oFetch](https://github.com/unjs/ofetch) under the hood. It has built in [auto-retry](https://github.com/unjs/ofetch#%EF%B8%8F-auto-retry) functionality. By default, it is `1` for `GET` requests.

If you changed the form submission to a `POST` request, it would not auto-retry.

**Comment by FatNerdPeng** [comment]
> From looking at your code, I think this is the expected behaviour. [`useFetch`](https://nuxt.com/docs/api/composables/use-fetch) uses [oFetch](https://github.com/unjs/ofetch) under the hood. It has built in [auto-retry](https://github.com/unjs/ofetch#%EF%B8%8F-auto-retry) functionality. By default, it is for requests.`1``GET`
> 
> If you changed the form submission to a request, it would not auto-retry.`POST`

It turns out that's the case, I don't understand why it's designed like this.Many times we use `GET` requests, and repeated requests on top of this can waste server resources. Does Nuxt have a design to avoid this situation?

**Comment by luc122c** [comment]
@FatNerdPeng Since `GET` requests shouldn't have a body, using a `POST` request to submit the form would be your best cource of action. Otherwise, you can disable the retries by setting it to 0.

**Comment by manniL** [comment]
What is written here is correct.

Also, when submitting a form, I'd usually resort to `$fetch`, because you don't want/need reactivity and want a "one-off" for the request instead.
