### ISSUE TITLE
`useSeoMeta` doesn't work properly in an async composable

### ISSUE THREAD

**Issue by andreww2012** [nuxt/nuxt#22712]
### Environment

```
- Operating System: Windows_NT
- Node Version:     v16.16.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.6.10
- Builder:          vite
- User Config:      devtools, imports
- Runtime Modules:  -
- Build Modules:    -
```

### Reproduction

https://github.com/andreww2012/nuxt3-useSeoMeta-doesnt-work-properly-in-async-composable

### Describe the bug

- Let's say the script section of pages `a` and `b` is async and contains `useSeoMeta` call after awaiting the same async operation.
- We want to avoid code duplication and move this code to a shared function (composable). Essentially, we replace this code with `await thisNewComposable()` expression.
- After that, if we perform parallel requests to those pages, meta tags defined in `useSeoMeta` start randomly missing from the rendered HTML. This doesn't happen if we don't move that code in the composable.

**Comment by danielroe** [comment]
You will need to do something like this:

```ts
export const useMeta = async (name: string) => {
  const nuxtApp = useNuxtApp();
  await new Promise((resolve) => setTimeout(resolve, 1000));

  nuxtApp.runWithContext(() => useSeoMeta(() => ({
    title: `${name} layout title`,
    description: `${name} layout description`,
  })));
};
```

See more here: https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables

**Comment by andreww2012** [comment]
Thank you for pointing that out! I did manage to work this around using a different approach in the end.

Several factors lead me to not reading this piece of documentation:
- No error messages. It worked absolutely fine, and I only started to suspect that something's not right when I started receiving emails from search engines complaining that meta tags are randomly disappearing on the production site. It took me around 6 hours in total to debug this :(
- I don't use auto imports. Consequently, I didn't even read the "Auto-imports" page in the docs.
- If even I did read that, it would probably take me a while to think of a solution that you proposed. `useNuxtApp` is not mentioned on that page, and `runWithContext` cannot be found in the whole documentation:

![2023-08-30](https://github.com/nuxt/nuxt/assets/6554045/de7bbfb2-4ff8-4fa3-9af1-9e680802214c)

I would like to propose:
- Documentation improvements in this regard (move this to a different section, more bad code examples + workarounds)?
- Maybe make `useSeoMeta` (and possibly other built-in composables) to print the error in this case (if that is even possible).

And thank you and the whole team for your hard work on Nuxt, keep it up!

**Comment by danielroe** [comment]
Those are excellent recommendations. Any PRs are welcome if you have specific suggestions.

 cc: @harlan-zw - do you think we could do this in unhead or maybe wrap the composable in Nuxt to provide a better error message?

**Comment by andreww2012** [comment]
@harlan-zw the issue still persists after upgrading to nuxt@3.7.0 by running `npx nuxi upgrade --force`.

> provide clearer reproduction details, like not sure how you're doing this exactly

The reproduction instructions are provided in [the README of the repository](https://github.com/andreww2012/nuxt3-useSeoMeta-doesnt-work-properly-in-async-composable?tab=readme-ov-file#steps-to-reproduce) that I've linked in the first message. I'm not sure how it can be further improved.

**Comment by harlan-zw** [comment]
> @harlan-zw the issue still persists after upgrading to nuxt@3.7.0 by running `npx nuxi upgrade --force`.
> 
> > provide clearer reproduction details, like not sure how you're doing this exactly
> 
> The reproduction instructions are provided in [the README of the repository](https://github.com/andreww2012/nuxt3-useSeoMeta-doesnt-work-properly-in-async-composable?tab=readme-ov-file#steps-to-reproduce) that I've linked in the first message. I'm not sure how it can be further improved.

Oh nice, sorry I missed te readme :facepalm:

**Comment by harlan-zw** [comment]
So the issue is that when you run anything that relies on the Vue app context after an async, the context is lost. Daniel's workaround is the correct solution to get around this for now.

An outstanding design issue with Unhead is that it tries to fallback to a shared head instance if the context is lost, which is resulting in the weird results you're seeing and it makes it a very difficult problem to diagnose.

There are already plans to change this logic but it may be a breaking change so was waiting for v2. There may be an alternative transitory solution that we can implement quicker though.

There is some work started on allowing context not to be lost after an async, but it doesn't apply to async composables. I think this would require some AST magic.

**Comment by andreww2012** [comment]
Thank you for the detailed explanation, it makes a lot of sense. I just wish it would fail with an error in this case or something similar. 😅

> Are you able to provide the work around you used out of curiosity?
It's having to do with changing the logic of the app to avoid using an async composable, so I believe it would be irrelevant to this issue.

**Comment by harlan-zw** [comment]
Agreed, thanks for the reproduction btw :)

**Comment by harlan-zw** [comment]
Using `useSeoMeta` after an await should _just work_ in Nuxt 3.7.1, let me know if you have any issues.

**Comment by andreww2012** [comment]
Well, it doesn't work, but now it throws an error when trying to navigate to the page with an async composable call - which is totally fine with me. Thank you a lot!

```
[nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at `https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables`.

at C:\Users\***\node_modules\.pnpm\nuxt@3.7.1_@types+node@18.17.14\node_modules\nuxt\dist\head\runtime\plugins\unhead.js:20:35
at injectHead (C:\Users\***\node_modules\.pnpm\@unhead+vue@1.5.2_vue@3.3.4\node_modules\@unhead\vue\dist\shared\vue.b1b42453.mjs:76:30)
at Module.useHead (C:\Users\***\node_modules\.pnpm\@unhead+vue@1.5.2_vue@3.3.4\node_modules\@unhead\vue\dist\shared\vue.b1b42453.mjs:85:32)
at Module.useSeoMeta (C:\Users\***\node_modules\.pnpm\@unhead+vue@1.5.2_vue@3.3.4\node_modules\@unhead\vue\dist\index.mjs:81:32)
at Module.useMeta (C:\Users\***\composables\useMeta.ts:5:25)
at async setup (C:\Users\***\pages\a-not-ok.js:17:110)
```

**Comment by harlan-zw** [comment]
> `useSeoMeta` still doesn't work after await, I'm on nuxt 3.10.0

You can try [asyncContext](https://nuxt.com/docs/guide/going-further/experimental-features#asynccontext). Please make a new issue with a reproduction if you're having issues beyond that.
