### ISSUE TITLE
Nuxt3 Module: Unable to dynamic import dependencies that contain alias imports

### ISSUE THREAD

**Issue by BKOHelix** [nuxt/nuxt#22713]
### Environment

Ubuntu 20.04.5 LTS
Node: 16.16.0
Nuxt: 3.6.1
Nitro: 2.5.2

### Reproduction

* Create a local module which uses (await import(file/path) to import a js module
* Start development server
* See terminal output.

### Describe the bug

Basically what I'm doing is I'm grabbing modules from my ~/server/discord/events folder within my custom module.

aliases inside of the import module don't work, and this issue bubbles up through each module that is imported into the imported module.

```
import myModule from "~/server/utils/myModule" <-- throws a module error cannot be found at runtime

```

if I use relative paths, any aliased import inside THAT module will throw an error:

```
import myModule from "../../../../utils/myModule"
```

```
myModule.ts
import anotherModule from "~/server/utils/anotherModule" <-- throws runtime error since it's in a module being imported into a nuxt module.
```

```
 ERROR  Cannot find module '~/server/utils/anotherModule'                                                                                                                                                                   nuxt3-discord-bot 11:02:55 a.m.
Require stack:
- /home/blackout/Projects/workplaces/nuxtApps/mywebapp/server/models/roster/myModule.ts

  Require stack:
  - server/models/roster/anotherModule.ts

```

**Comment by danielroe** [comment]
See https://github.com/nuxt/nuxt/issues/13728#issuecomment-1397313031.
