### ISSUE TITLE
Nuxt3 cannot hot reload after created component files

### ISSUE THREAD

**Issue by xiaochuan1719** [nuxt/nuxt#22711]
### Environment

------------------------------
- Operating System: Windows_NT                                                                                     
- Node Version:     v18.17.1
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@9.6.7
- Builder:          vite
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

```
step 1, init nuxt project  (npx or pnm )

step 2, add`<NuxtLayout>`  and `<NuxtPage>` component in app.vue

step 3, `npm run dev`  or `pnpm dev`

step 4, create some components  `pages/index.vue` and `pages/admin.vue`

step 4, open in browser
```
### Describe the bug

 **Each time a new component  is created, the service must be restarted**

![屏幕截图 2023-08-20 135226](https://github.com/nuxt/nuxt/assets/38381164/606ea85c-782f-47f1-81c6-eba15584a376)
![屏幕截图 2023-08-20 140948](https://github.com/nuxt/nuxt/assets/38381164/68d2f4e1-eecd-4338-9872-6ab7d4109448)
![屏幕截图 2023-08-20 135138](https://github.com/nuxt/nuxt/assets/38381164/dd90d1ff-33b7-459c-82a4-a13562da8a12)
![屏幕截图 2023-08-20 141309](https://github.com/nuxt/nuxt/assets/38381164/356fa180-c3fb-4b12-ad87-699e3ec17875)
![屏幕截图 2023-08-20 141436](https://github.com/nuxt/nuxt/assets/38381164/8c6ab179-3582-4411-af67-57ea75be372c)
![屏幕截图 2023-08-20 141243](https://github.com/nuxt/nuxt/assets/38381164/2149e51e-466e-4c36-994a-9b3e42ef2089)

**Comment by danielroe** [comment]
This should be resolved in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/), or in the next release.

Let me know if not and I'll reopen.
