### ISSUE TITLE
How do I add a timestamp to build.publicPath

### ISSUE THREAD

**Issue by ligouhai** [nuxt/nuxt#22716]
### Environment

> Operating System: Darwin
> Node Version: v16.17.0
> Nuxt Version: 2.15.8
> Package Manager: npm
> Bundler: Webpack

### Describe the bug

> The server rendering enabled by the project uses a CDN. When you want to reference resources, add a timestamp to distinguish the resources uploaded to the CDN each time. The validity is valid, but after the deployment to the production environment, if the project restarts automatically for some reason, the timestamp will be generated again, resulting in a mismatch with the uploaded static resource timestamp.

```

const dayjs = require('dayjs')
const time = dayjs().format('YYYYMMDDHHmmss')


module.exports = {
  build: {
    publicPath: `${env[process.env.MODE].PUBLIC_PATH}${time}/`
  }
}

```

**Comment by ligouhai** [comment]
> May I ask where it is better to load the prefix of this timestamp? Because I have modified config.output.publicPath in the extend() method and found that it does not take effect after deployment, possibly because ssr is enabled.

**Comment by ligouhai** [comment]
The reason for the difference through the time stamp is that each uploaded css and js resources are placed under the same folder, resulting in a lot of junk files in this folder, but do not know which can be deleted. You can manually delete the previously deployed files.

**Comment by danielroe** [comment]
If you want to do this, you could create a small Nuxt module that writes a file to disk with the current output path before each build. Then when you read your nuxt.config file to start the build server, this file could be read and would update your public path.
