### ISSUE TITLE
Page validation doesn't match route stack as expected

### ISSUE THREAD

**Issue by rijkvanzanten** [nuxt/nuxt#22729]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.6.12
- Builder:          vite
- User Config:      ssr, css, runtimeConfig, typescript, hooks, nitro, modules, vite
- Runtime Modules:  @vueuse/nuxt@10.2.1
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-ujdmhu

Try navigating to `/foo/bar`

### Describe the bug

When using a dynamic route matcher structure as follows:

```
pages/
  [type]/
    [id].vue
  [...fallback].vue
```

I expect the fallback to be used when the validation of `[type]/[id].vue` fails in it's `definePageMeta`. In reality, the fallback file is skipped completely and the 404 is rendered prematurely. If `[type]/[id].vue` doesn't exist, `[...fallback].vue` will correctly render nested pages as well, making me think the failing to resolve to fallback on failed validation is a bug.

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/19327.

You can see my comment in https://github.com/nuxt/nuxt/issues/19327#issuecomment-1695583844 with a workaround.
