### ISSUE TITLE
TypeScript errors when layer and app have different dependency versions

### ISSUE THREAD

**Issue by DawidKopys** [nuxt/nuxt#22726]
### Environment

app
```
- Operating System: `Darwin`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.6.5`
- Nitro Version:    `2.5.2`
- Package Manager:  `npm@9.5.1`
- Builder:          `vite`
- User Config:      `extends`, `typescript`, `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`
```

layer
```
- Operating System: `Darwin`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.6.5`
- Nitro Version:    `2.5.2`
- Package Manager:  `npm@9.5.1`
- Builder:          `vite`
- User Config:      `typescript`
- Runtime Modules:  `-`
- Build Modules:    `-`
```

### Reproduction

1. clone repo https://github.com/DawidKopys/nuxt-h3-event-ts-error-repro
2. run `npm i` in nuxt-layer directory
3. run `npm i` in app directory
4. run `npx nuxi typecheck` / `npm run dev` / `npx vue-tsc --noEmit` inside app directory. You should get below error:

```
Nuxi 3.6.5                                                                                       3:57:55 PM
../nuxt-layer/server/api/foo.ts:7:13 - error TS2345: Argument of type 'H3Event' is not assignable to parameter of type 'H3Event<EventHandlerRequest>'.

7   setCookie(event, 'someCookieName', 'someCookieValue')
              ~~~~~

../nuxt-layer/server/utils/someUtil.ts:6:13 - error TS2345: Argument of type 'H3Event' is not assignable to parameter of type 'H3Event<EventHandlerRequest>'.
  Type 'H3Event' is missing the following properties from type 'H3Event<EventHandlerRequest>': method, headers, toJSON, fetch, $fetch

6   setCookie(event, 'someCookieName', 'someCookieValue')
              ~~~~~


Found 2 errors in 2 files.

Errors  Files
     1  ../nuxt-layer/server/api/foo.ts:7
     1  ../nuxt-layer/server/utils/someUtil.ts:6
```

### Describe the bug

- `app` has dependency `h3` installed with version `1.8.0`
- `nuxt-layer` has dependency `h3` installed with version `1.7.1` (forced with `overrides` field in layer's `package.json` - for simplicity - the effect would be exactly the same if layer had `1.7.1` version locked with its `package-lock.json`)

As a result, I am getting typescript errors if **some** utils are imported manually from `h3` and others are auto-imported. Layer file `server/api/foo.ts` shows simple example of this scenario. In this file, `defineEventHandler` is imported manually, while function `setCookie` is auto imported - we get ts error because of that.

There is a simple solution for this exact situation - don't import `defineEventHandler` manually. If done so, there are no ts errors for this file.

However, sometimes we might need to import something manually from our dependency. File `server/utils/someUtil.ts` serves as an example of such case.
Here, we have some utility function, which accepts `event` as its argument. In order to type the parameter we need to import `H3Event` from `h3`. This function also uses `setCookie` function which is auto imported.
Again, we get ts error as a result.

**Workaround** 
Importing everything manually from our `h3` dependency fixes the problem - we no longer get ts errors.
We no longer get the benefit of auto imports though.

**Comment by danielroe** [comment]
Does it make a difference if you import from `#imports`?

**Comment by DawidKopys** [comment]
I can't make it work importing from `#imports`. My code with the changes is [here](https://github.com/DawidKopys/nuxt-h3-event-ts-error-repro/tree/import-from-imports):
- I have added `/nuxt-layer/server/tsconfig.json` file, similarily to how it was done in `app`
- in both `app` and `nuxt-layer` - I am getting ts errors:

layer:
```
server/api/foo.ts:5:10 - error TS2305: Module '"#imports"' has no exported member 'defineEventHandler'.

5 import { defineEventHandler } from '#imports'
           ~~~~~~~~~~~~~~~~~~

server/api/foo.ts:7:36 - error TS7006: Parameter 'event' implicitly has an 'any' type.

7 export default defineEventHandler((event) => {
                                     ~~~~~


Found 2 errors in the same file, starting at: server/api/foo.ts:5
```

the app (I have added file `/app/server/api/bar.ts` to verify if it works in the app:
```
server/api/bar.ts:1:10 - error TS2305: Module '"#imports"' has no exported member 'defineEventHandler'.

1 import { defineEventHandler } from '#imports'
           ~~~~~~~~~~~~~~~~~~

server/api/bar.ts:3:36 - error TS7006: Parameter 'event' implicitly has an 'any' type.

3 export default defineEventHandler((event) => {
                                     ~~~~~

../nuxt-layer/server/api/foo.ts:5:10 - error TS2305: Module '"#imports"' has no exported member 'defineEventHandler'.

5 import { defineEventHandler } from '#imports'
           ~~~~~~~~~~~~~~~~~~

../nuxt-layer/server/api/foo.ts:7:36 - error TS7006: Parameter 'event' implicitly has an 'any' type.

7 export default defineEventHandler((event) => {
                                     ~~~~~

../nuxt-layer/server/utils/someUtil.ts:4:10 - error TS2724: '"#imports"' has no exported member named 'setCookie'. Did you mean 'useCookie'?

4 import { setCookie } from '#imports'
           ~~~~~~~~~


Found 5 errors in 3 files.
```
- also, `H3Event` is not exported from `#imports` - I can only import it directly from `h3`

**Comment by dargmuesli** [comment]
might help:
- https://github.com/nuxt/cli/pull/264

at least I hope so :pray:

**Comment by danielroe** [comment]
This is no longer reproducible for me with latest package versions in that repo (though I kept the override)...
