### ISSUE TITLE
class / style attribute does not update on node mismatch

### ISSUE THREAD

**Issue by Julien-Martin** [nuxt/nuxt#22722]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  yarn@3.2.0
- Builder:          vite
- User Config:      alias, app, components, css, devtools, experimental, extends, i18n, modules, nitro, pinia, router, runtimeConfig, tailwindcss, telemetry, veeValidate, vite, vue
- Runtime Modules:  @pinia/nuxt@^0.4.11, @nuxtjs/stylelint-module@^5.1.0, @nuxtjs/i18n@8.0.0-beta.13, @vueuse/nuxt@10.2.1, @vee-validate/nuxt@^4.9.6, @nuxtjs/tailwindcss@^6.8.0
- Build Modules:    -
------------------------------

### Reproduction
I provide a minimal reproduction

https://stackblitz.com/edit/github-brcyvh?file=pages%2Findex.vue

### Describe the bug

I'm using a plugin `$bp` that use `useBreakpoints` from `vueuse` under the hood https://vueuse.org/core/useBreakpoints

My goal is to change the `size` of the component `NButton` based on a boolean : `$bp.isLapM`.

When we refresh the page, we see that the `btnSize` inside the button is updated but the class still `-sm`.
If I resize my window, both are updated

We are migrating our app to Nuxt 3, and on Nuxt 2 we didn't have this issue... :cry: 

I'm a doing something wrong about this ?

**Comment by Julien-Martin** [comment]
@danielroe Arf, indeed same behaviour without Nuxt :( 

https://stackblitz.com/edit/github-hzaudy?file=src%2Fpages%2FHome.vue

Do you have any workaroud how to fix this ? 🙏

**Comment by danielroe** [comment]
This is caused by a hydration mismatch. So the way to resolve and ensure the attributes remain reactive is to ensure you are not rendering a different value on the client _before_ the component is mounted. (So if you want to set something based on device size/localstorage you should do this in `onMounted`.)
