### ISSUE TITLE
VScode and PHPStorm cannot resolve alias paths when running Nuxt in Docker

### ISSUE THREAD

**Issue by martinszeltins** [nuxt/nuxt#22735]
### Environment

Docker

### Reproduction

Does not apply.

### Describe the bug

I have a dockerized app _(Symfony backend and Nuxt frontend)_ running in Docker. But Nuxt has generated a `.nuxt/tsconfig.json` file with aliases where the paths are the ones inside the docker container. This works fine, the project builds successfully and runs fine. But the problem is that the IDE (both VSCode and PHPStorm) cannot resolve these paths because they are not local but inside docker and I do not want to run my IDE inside of Docker 😅

Here is my `.nuxt/tsconfig.json` (notice the `/var/www`) paths:

````
// Generated by nuxi
{
  "compilerOptions": {
    "forceConsistentCasingInFileNames": true,
    "jsx": "preserve",
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "Node",
    "skipLibCheck": true,
    "strict": true,
    "allowJs": true,
    "baseUrl": "/var/www",
    "noEmit": true,
    "resolveJsonModule": true,
    "allowSyntheticDefaultImports": true,
    "types": [
      "node"
    ],
    "paths": {
      "~": [
        "/var/www"
      ],
      "~/*": [
        "/var/www/*"
      ],
      "@": [
        "/var/www"
      ],
      "@/*": [
        "/var/www/*"
      ],
      "~~": [
        "/var/www"
      ],
      "~~/*": [
        "/var/www/*"
      ],
      "@@": [
        "/var/www"
      ],
      "@@/*": [
        "/var/www/*"
      ],
      "assets": [
        "/var/www/assets"
      ],
      "./common/public": [
        "/var/www/common/public"
      ],
      "./common/public/*": [
        "/var/www/common/public/*"
      ],
      "img": [
        "/var/www/assets/img"
      ],
      "#app": [
        "/var/www/node_modules/nuxt/dist/app"
      ],
      "#app/*": [
        "/var/www/node_modules/nuxt/dist/app/*"
      ],
      "vue-demi": [
        "/var/www/node_modules/nuxt/dist/app/compat/vue-demi"
      ],
      "@typed-router": [
        "/var/www/.nuxt/typed-router"
      ],
      "@typed-router/*": [
        "/var/www/.nuxt/typed-router/*"
      ],
      "#apollo": [
        "/var/www/.nuxt/apollo"
      ],
      "#vue-router": [
        "/var/www/.nuxt/vue-router"
      ],
      "#imports": [
        "/var/www/.nuxt/imports"
      ],
      "#build": [
        "/var/www/.nuxt"
      ],
      "#build/*": [
        "/var/www/.nuxt/*"
      ],
      "#components": [
        "/var/www/.nuxt/components"
      ]
    }
  },
  "include": [
    "./typed-router/typed-router.d.ts",
    "./nuxt.d.ts",
    "../**/*",
    "../**/*",
    "/var/www",
    "/var/www/*",
    "/var/www",
    "/var/www/*",
    "/var/www",
    "/var/www/*",
    "/var/www",
    "/var/www/*"
  ],
  "exclude": [
    "../dist",
    "../.output"
  ],
  "vueCompilerOptions": {
    "jsxTemplates": true,
    "experimentalRfc436": true
  }
}
````

My actual project on my computer is located at `~/project` and not inside `/var/www` and that this the reason not my IDEs do not recognize these paths.

Is there some special configuration I need to do for Nuxt to configure it properly for Docker?

Screenshot 👇️
![image](https://github.com/nuxt/nuxt/assets/34019878/49889ae7-85f3-4ec4-92f0-f390ddf6373e)

**Comment by scottbedard** [comment]
I'm also having problems with this. I think a good solution would be allowing relative paths as an [`alias`](https://nuxt.com/docs/api/configuration/nuxt-config#alias), but they don't currently work

**Comment by martinszeltins** [comment]
I might have found a temporary solution. If you update your `tsconfig.json` file and override the `paths` then your IDE will recognize the aliases. This strangely works also for the Nuxt Nitro engine. I don't know why or how it works but it works. 🤷‍♂️

Here is my `tsconfig.json` file:
```json
{
    "extends": "./.nuxt/tsconfig.json",
    "compilerOptions": {
        "baseUrl": "./",
        "paths": {
            "@/*": [
                "./*"
            ],
            "@" : [
                "./*"
            ]
        }
    }
}
```

Now if I have this import, my IDE will recognize it:

```js
import User from '@/users/types/user'
```

**Comment by danielroe** [comment]
This should be resolved in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/), or in the next release.

Let me know if not and I'll reopen.
