### ISSUE TITLE
navigator.gpu is undefined in chrome 103

### ISSUE THREAD

**Issue by MusixNotMusic** [nuxt/nuxt#22734]
### Environment

node 16.13.2
windows10 64bit

### Reproduction

![image](https://github.com/nuxt/nuxt/assets/13427607/e27fd52d-23b5-4acc-8352-63cbb57606e4)
other page:
![image](https://github.com/nuxt/nuxt/assets/13427607/ecaed263-fe50-4b58-931d-a9aaf5ddc31c)

### Describe the bug

1. follow nuxt official website install nuxt
2. npm install
3. use webgpu feature, not craete webgpu adapter
error ---> const adapter = await navigator.gpu.requestAdapter();
undefined --> navigator.gpu

**Comment by huang-julien** [comment]
Hello do you have a minimal reproduction please ? 
Does this code run only client-side ?

**Comment by danielroe** [comment]
Yes, this isn't a Nuxt issue as far as I can tell as we do not use `navigator.gpu` in Nuxt.

Note that you will need to be careful to use `navigator` only in the client-side environment, but I suspect you're doing that as you've indicated the error is specific to chrome 103.

If you think this is a Nuxt issue, then please do feel free to provide a repro and we'll happily have a look.
