### ISSUE TITLE
getActivePinia()?._s.get(id);

### ISSUE THREAD

**Issue by gllinzbk1** [nuxt/nuxt#22732]
> Here you go: https://stackblitz.com/edit/github-fjfqqk?file=composables/useProduct.js,stores/sql.js,nuxt.config.ts. It finishes generation successfully now.
> 
There's a 500 error when rendering that page because you're trying to access .value of something that is null. 
```
export const getStoreById = (id: string) => {
    //@ts-expect-error _s is internal
    return getActivePinia()?._s.get(id);
};
```
Method to obtain data only once,in nuxt3.6.5
![image](https://github.com/nuxt/nuxt/assets/115514156/5816092f-8afd-4148-8c7c-805c75220085)

but in nuxt3.5.3 ,it's no problem.
Each address can be obtained once in dynamic routing

nuxt3.60,3.6.1 its ok
nuxt3.6.2-5 ,its not normally

**Comment by danielroe** [comment]
this doesn't sound like a nuxt issue, and that also looks like an internal pinia object rather than something intended to be public.

if you're sure this isn't a pinia issue would you create a minimal reproduction that I can test in nuxt 3.6.1 vs 3.6.5, with _only_ the code needed to reproduce the issue?

**Comment by gllinzbk1** [comment]
https://github.com/gllinzbk1/nuxtgenerate.git

**Comment by danielroe** [comment]
there seems to be a lot there that's not related to this issue

**Comment by gllinzbk1** [comment]
Just check if the result of 'npm run generate' is normal

**Comment by danielroe** [comment]
I don't know your project well enough to know what is normal.

**Comment by gllinzbk1** [comment]
![图片](https://github.com/nuxt/nuxt/assets/115514156/284a2f26-66ed-404c-9514-a4fa5c880561)

**Comment by gllinzbk1** [comment]
Today, I upgraded to 3.7 for nuxt, which is very cool. 'npm run generate' quickly, but I found a small problem with multiple pages in pagination, and the first page contains error500, which failed to generate
![image](https://github.com/nuxt/nuxt/assets/115514156/30fd3915-0154-45ef-9114-fc421d7f725d)
I am currently searching for the reason for my code

**Comment by gllinzbk1** [comment]
Random creation failure in pagination, not necessarily the homepage
