### ISSUE TITLE
nuxi build: Could not load raw:../../style/index.css (imported by

### ISSUE THREAD

**Issue by wiidede** [nuxt/nuxt#22730]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-e6xsap?file=app.vue

### Describe the bug

Catch a error while building. It seems normal while dev.
```bash
✔ Generated public .output/public                                   nitro 5:23:09 AM
ℹ Building Nitro Server (preset: node-server)                       nitro 5:23:09 AM

[nitro 5:23:10 AM]  ERROR  Error: Could not load raw:../../style/index.css (imported by node_modules/@arco-design/web-vue/es/tag/style/css.js): ENOENT: no such file or directory, open '../../style/index.css'
```

**Comment by danielroe** [comment]
In this case you need to transpile arco-design as it's importing CSS and this can't otherwise work in Node.

```ts
// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  build: {
    transpile: [/@arco-design/],
  },
});
```

**Comment by wiidede** [comment]
thank you very much😊. my bad.
