### ISSUE TITLE
Prisma sqlite provider doesn't work in the production environment

### ISSUE THREAD

**Issue by oski646** [nuxt/nuxt#22738]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.14.0`
- Nuxt Version:     `3.6.5`
- Nitro Version:    `2.5.2`
- Package Manager:  `npm@9.7.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Use Prisma with SQLite as a database provider and try to deploy an application

### Describe the bug

I am having trouble deploying an application with the SQLite provider because the server cannot locate the database file. It works perfectly during development using `npm run dev`. However, when I attempt to check the production version, I first run `npm run build`, then `npm run preview`, and unfortunately, it doesn't work in the preview.

I couldn't create a minimal reproduction on Stackblitz (an error occurred while installing Prisma), but I believe that my issue is straightforward.

I've tried to manually copy the database file, and everything works as expected. The file needs to be in the `.output/server/prisma` directory.

Here is what my project looks like (the directory manually copied by me is highlighted on the screenshot).
![CleanShot 2023-08-22 at 10 52 51](https://github.com/nuxt/nuxt/assets/28627427/1410f35d-eb25-4e02-9ce6-1fd4b1fb6c90)

**Comment by oski646** [comment]
As I said: "I couldn't create a minimal reproduction on Stackblitz (an error occurred while installing Prisma), but I believe that my issue is straightforward.", so please do not close automatically this issue.

**Comment by sunzehui** [comment]
same issue, which can be easily reproduced, occurs by building the official Nuxt.js template and then executing the "preview" command. 
The Nuxt template link is: https://github.com/prisma/prisma-examples/tree/latest/typescript/rest-nuxtjs.

**Comment by MachariaK** [comment]
Related: https://github.com/prisma/prisma/discussions/20103

**Comment by MachariaK** [comment]
@sunzehui Mind showing how?

**Comment by MachariaK** [comment]
I was experiencing this exact problem. 

The Prisma Rust Client creator pointed me to the documentation: [https://prisma.brendonovich.dev/extra/migrations](url). 

I enabled the `migrations` feature for `prisma-client-rust` and `prisma-client-rust-cli` then ran` cargo run --bin prisma migrate deploy --schema=./prisma/schema.prisma`. (This will depend on your setup). 

Then added the first five lines in the main function: 

```
#[tokio::main]
async fn main() {
    let client = prisma::new_client().await.unwrap();
    #[cfg(debug_assertions)]
    client._db_push().await;
    #[cfg(not(debug_assertions))]
    client._migrate_deploy().await;

    tauri::Builder::default()
        .invoke_handler(tauri::generate_handler![greet])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```
This resolved my problem and the app can now access the database in production.
