### ISSUE TITLE
[bug]Hydration children mismatch in <ul>: server rendered element contains more child nodes than client vdom. 

### ISSUE THREAD

**Issue by wintsa123** [nuxt/nuxt#22736]
### Environment

Nuxt project info:                                                                                                                                                                                                     16:07:28

------------------------------
- Operating System: Windows_NT
- Node Version:     v16.16.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      imports, image, runtimeConfig, app, css, typescript, modules, vueuse, colorMode, vite, elementPlus
- Runtime Modules:  @vueuse/nuxt@10.3.0, @pinia/nuxt@0.4.11, @element-plus/nuxt@1.0.5, @nuxtjs/color-mode@3.3.0, @nuxtjs/color-mode@3.3.0, @unocss/nuxt@0.55.1, @nuxt/image@1.0.0-rc.1
- Build Modules:    -

### Reproduction

not

### Describe the bug

我使用ul -li  标签，对li标签进行v-for循环渲染，渲染数据是来自lazy请求，刷新页面这时候浏览器提示
```js
Hydration children mismatch in <ul>: server rendered element contains more child nodes than client vdom. 
```
我查看服务端和客户端都成功拿到了数据。我认为问题的关键在于lazy请求没有拿到数据时，页面先在服务端渲染并返回客户端了。我尝试给ul的父元素添加v-if，如果数据没拿到,pending为true时不渲染，但很遗憾，并没有解决问题，仍然提示我。
我只能用client only /request api serve:false解决。我想知道更好的解决放阿飞

**Comment by huang-julien** [comment]
Hello can you provide a minimal reproduction please ? At first, it is probably some invalid html

**Comment by wintsa123** [comment]
> Hello can you provide a minimal reproduction please ? At first, it is probably some invalid html

i cant give provide a minimal reproduction,Because my server is not on the public IP address。
but i can give some code
```js
<temple>
<div v-if="!pending">
<ul :style="{
                        display: 'flex',
                        listStyle: 'none',
                        padding: 0,
                    }">
                        <li v-for="item in data" :key="item" class="mr-1"> <el-check-tag :checked="item.checked"
                                @change="(event: any) => tagChange(item, event)"
                                style="borderRadius:2.5rem;height: 1.5rem;lineHeight:1.5rem">{{ item.name
                                }}</el-check-tag>
                        </li>
                    </ul>
</div>
</temple>
<script lang='ts' setup>
const getFetch = <T>( url:NitroFetchRequest, params:Record<string, any>|undefined, options? : Options<unknown>) => {
  // 接口传参要求
  const config = useRuntimeConfig();
  const myObject = {
    ...(options?.method !== undefined ? { method: options.method } : {}),
    ...(options?.method !== undefined && options?.method !== 'get'  ? { body: params } : {query:params}),
    ...(options?.lazy !== undefined ? { lazy: options.lazy } : {}),
    ...(options?.immediate !== undefined ? { immediate: options.immediate } : {}),
    ...(options?.default !== undefined ? { default: options.default } : {}),
    ...(options?.transform !== undefined ? { transform: options.transform } : {}),
    ...(options?.server !== undefined ? { server: options.server } : {}),
  };
  return useFetch(url, {
    // method此处仅仅只处理了get与post请求
    // ofetch库会自动识别请求地址，对于url已包含域名的请求不会再拼接baseURL
    baseURL: config.public.apiBase,
    headers: { 'Accept': 'application/json, text/plain, */*' },
    // onRequest相当于请求拦截
   
    // onResponse相当于响应拦截
    ...myObject,})}
const getTagList = async (): Promise<AsyncData<ITag, null>> => {
    const result = await getFetch('/tag/list', undefined, {
        transform: (input: any) => {
            input.data.rows.unshift({ id: 0, name: '所有产品', checked: true });
            return input.data.rows.map((item: { id: number, checked: boolean }) => {
                if (item.id !== 0) {
                    item.checked = false;
                }
                return item;

            })
        }, lazy: true,server:false
    });
    return result as AsyncData<ITag, null>
}
const { data }: any = await getTagList()

</script>
```

**Comment by wintsa123** [comment]
if only lazy: true,it will show 'Hydration children mismatch in <ul>: server rendered element contains more child nodes than client vdom. ',if i set server :false,it normal work

**Comment by manniL** [comment]
@wintsa123 could you please use StackBlitz, CodeSandbox or a simple GitHub Repository to provide a *running* example?

**Comment by wintsa123** [comment]
> @wintsa123 could you please use StackBlitz, CodeSandbox or a simple GitHub Repository to provide a _runnable_ example?

https://github.com/wintsa123/huagong-Nuxt3/blob/master/components/content.vue

**Comment by Alex-Programmer-Bro** [comment]
@manniL Hi there, I got this problem too and I provide a minimal reproduction : https://stackblitz.com/~/github.com/Alex-Programmer-Bro/file-manager

## Install
```shell
npm install
```

## Run
```shell
npm run dev
```

<img width="961" alt="image" src="https://github.com/nuxt/nuxt/assets/115539090/cda25821-0637-4908-ba33-75b721ab332d">

**Comment by Alex-Programmer-Bro** [comment]
> @manniL Hi there, I got this problem too and I provide a minimal reproduction : https://stackblitz.com/~/github.com/Alex-Programmer-Bro/file-manager
> 
> ## Install
> ```shell
> npm install
> ```
> 
> ## Run
> ```shell
> npm run dev
> ```
> 
> <img alt="image" width="961" src="https://private-user-images.githubusercontent.com/115539090/288002135-cda25821-0637-4908-ba33-75b721ab332d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NzE0MjQsIm5iZiI6MTcwMTc3MTEyNCwicGF0aCI6Ii8xMTU1MzkwOTAvMjg4MDAyMTM1LWNkYTI1ODIxLTA2MzctNDkwOC1iYTMzLTc1YjcyMWFiMzMyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNVQxMDEyMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMGQ0NTljZDFhYzY3MTQzZjUxNjM5ZWUyY2Q4NWJjYjMyNjM0NTcxYTllNjdjZGFjMjA2N2UwZDQ1NzBmMWJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1WfmhBaSPRWB8ZYMqwzlLgi1TuMgj_cucBNopCblTIE">

@manniL By the way, I don't know why it crashes when installing dependencies with npm, I've been installing it myself manually inside the terminal with pnpm i since.
