### ISSUE TITLE
textContent of inline payload `<script>` tag is not properly escaped

### ISSUE THREAD

**Issue by danielroe** [nuxt/nuxt#22748]
**Reproduction**: https://stackblitz.com/edit/github-yg9nsm?file=app.vue

Regression from https://github.com/nuxt/nuxt/pull/22179, I suspect.

**Comment by harlan-zw** [comment]
Nice catch!

One feature of unhead is that if you pass a string to `innerHTML` when using either `application/json` or `application/ld+json` it will parse it as json and then jsonify it again, to ensure the data is properly json encoded.

This reparsing is stripping the encoding provided by [devalue](https://github.com/Rich-Harris/devalue/blob/master/src/utils.js).

I've decided to remove this logic as this should be on the user to encode the data correctly if they want to pass a string.

Release will go out soon, but let me know your thoughts
https://github.com/unjs/unhead/commit/464f98fa4ee6f852d4c20d85bee64c60c395f057

**Comment by harlan-zw** [comment]
I'll re-open until I do the release, likely tomorrow.

**Comment by harlan-zw** [comment]
Okay looks to be fixed https://stackblitz.com/edit/github-yg9nsm?file=app.vue
