### ISSUE TITLE
Routing system

### ISSUE THREAD

**Issue by ElvinKyungu** [nuxt/nuxt#22750]
### Describe the feature

Why is it that every time I create something I have to restart the server for the changes to take effect?
For example, when I create a pages folder and put an index.vue file inside, the routes are only taken into account when I restart.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
This should be resolved in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/), or in the next release.

Let me know if not and I'll reopen.
