### ISSUE TITLE
Automatic import of `useRoute` is not working properly on production build

### ISSUE THREAD

**Issue by trandaison** [nuxt/nuxt#22752]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.6.5`
- Nitro Version:    `2.5.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `telemetry`, `modules`, `pinia`
- Runtime Modules:  `@pinia/nuxt@0.4.11`
- Build Modules:    `-`

### Reproduction

https://codesandbox.io/p/sandbox/sad-lake-cjxzvt?file=/stores/test.ts:10,6

### Describe the bug

1. Visit the reproduction link
2. Click on any `/?id=1..n` button to change the id value on the route URL.
3. The value of `currentData` getter is updated correctly ✅
4. Click the `/home` link.
5. At the home page, click on any `/?id=1..n` button to navigate back to the index page.
6. Repeat step no. 2, but this time, the value of getter will not be updated ❌

![261888115-9201b18c-3654-4288-b614-9790d52000c3](https://github.com/nuxt/nuxt/assets/13447235/7b2500bc-06eb-4af9-a4aa-cd2424913997)

### Additional context

- In the sandbox above, this bug happen. In the localhost, you have to build production to reproduce the bug

```bash
npx nuxi generate
npx nuxi preview
```

- This happen when navigate to the page in client side. If you enter the page from URL, the getter still working.
- If I turn of the ssr from the nuxt config. And move the useRoute statement inside the computed/getter, it works.

```diff
- const route = useRoute();
  const currentData = computed(() => {
+   const route = useRoute();
    const index = Number(route.query.id || 1);
    return data.value[index];
  });
```
However this code never working on server side, cuz the `useRoute()` is call outside the setup context.

- I already open a issue on pinia repo (https://github.com/vuejs/pinia/issues/2361). However, adding a manual import from vue-router does fix it:

```ts
import { useRoute } from 'vue-router'
```

**Comment by Heunsig** [comment]
I have the same problem. I am working on nuxt@^3.7.0

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/28804 - see https://github.com/nuxt/nuxt/issues/28804#issuecomment-2327483434 for an explanation of what is happening and why.
