### ISSUE TITLE
Using middleware + redirect function results in failed rendering

### ISSUE THREAD

**Issue by jd-solanki** [nuxt/nuxt#22766]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.15.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.6.0
- Package Manager:  pnpm@8.6.12
- Builder:          vite
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/jd-solanki/playgrounds/tree/nuxt-middleware-redirect-issue

**Watch out for branch**

### Describe the bug

This is strange case I occured while developing my admin template. I already faced another [issue](https://github.com/nuxt/nuxt/issues/22629) which I thought is root for this current issue but after checking the build version I found that the original (this) issue still exist even in build.

### Steps

1. Run the server
2. Click on set auth cookies to login & set auth related cookie
3. hit `/login` by manually entering the URL
4. Error!!!! Check the console for more details.

![image](https://github.com/nuxt/nuxt/assets/47495003/ea6cc66c-1a24-49ea-aba2-dac42bfa6439)
![image](https://github.com/nuxt/nuxt/assets/47495003/1d0da86d-4f7c-4529-a2cb-42f47e7f7f19)

### Additional context

I'm building an admin panel with Auth & ACL. I already mentioned the related issue above.

**Comment by jd-solanki** [comment]
Just bumping this because it's still "pending triage". I hope you won't mind 😜

**Comment by danielroe** [comment]
You are using a Nuxt composable (`useCookie`) in a router `redirect` guard. `vue-router` will call this outside the Nuxt context. Instead of `redirect` you can set `meta.middleware` which will have the same effect but be called in a different context.

**Comment by jd-solanki** [comment]
Oh, that's the catch 👍🏻 

However, using path, name & meta only gives type error:

https://github.com/nuxt/nuxt/assets/47495003/63e549f5-5df1-44f5-94f9-5b73ca5983e9

Have to add `component: h('div')` as a workaround🤔
