### ISSUE TITLE
Nitro prerender does not crawl through all the links in vue files. 

### ISSUE THREAD

**Issue by ishaanparlikar** [nuxt/nuxt#22762]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.17.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@9.6.7
- Builder:          vite
- User Config:      app, devtools, ssr, nitro, pages, debug, gtm, runtimeConfig, build, logLevel, components, modules, swiper, css, eslint, googleFonts, tailwindcss, experimental, 
image, vite
- Runtime Modules:  @nuxtjs/eslint-module@4.1.0, @nuxtjs/tailwindcss@6.8.0, nuxt-swiper@1.1.1, @nuxt/image@1.0.0-rc.1, @nuxtjs/google-fonts@3.0.2, @zadigetvoltaire/nuxt-gtm@0.0.13, @nuxtjs/fontaine@0.4.1

### Reproduction

This is re-producible only when you build the app with nuxi generate command.

**I have output directory setup in different path so I am updating the base url paths accordingly which is working fine for other urls.**

1. Use a loop to display a set of images will not work if you have basePath configured in nuxt config. Pre-renderer will not crawl through and update the urls to set of images
2. Also it will not work in pre-render mode if you are passing image urls as props. and if you have "v-if" directive used it will also cause problems.

### Describe the bug

![image](https://github.com/unjs/nitro/assets/43013132/d0d545c8-d7be-4912-8034-0f6ea99596dc)

So I have this code. In normal circumstances it works when pre-rendering the application. 
But I have this in nuxt.config.js file. 

`app: {
    baseURL: ${process.env.NUXT_BUILD_ENV !== "local" ? "/vue/leah/" : "/"},
    buildAssetsDir: "/_nuxt/",
  }`
  
 So when crawling through the links when pre-rendering the site, It will not get replaced with the correct URL as configured.
  
![image](https://github.com/unjs/nitro/assets/43013132/5966692d-2861-4412-a523-73f1377f9b40)

if you use it without props or in loop it works fine.

**Comment by danielroe** [comment]
Yes, that would be perfectly fine. I can build/run within the REPL.

**Comment by ishaanparlikar** [comment]
Hi @danielroe 

Please have a look at this REPL. Images will not be shown, But have a look at generated output in "vue/leah/index.html" file. The image urls are not masked with the new path.

https://stackblitz.com/edit/github-9x9vtb

I have added a normal image tag with path, and as you can see in build it was masked properly with the baseURL path specified in nuxt.config.

Let me know if something else is needed. Would be happy to help :) 

Thanks,
Ishan

**Comment by danielroe** [comment]
The issue here is Vite in this case. It's not about the loop; it's about the fact that it's not a static string. So both the following can't be auto-prefixed with base URL:

```html
<img :src="`/test.png`" />
<img v-for="n in 10" :key="n" :src="`/${n}.jpg`" />
```

If this is an issue, feel free to raise an issue upstream at https://github.com/vitejs/vite, but Vite doesn't give us enough information here to prefix with the base URL when prerendering.

**Comment by ishaanparlikar** [comment]
Hi @danielroe 
Any workaround you recommend?
Problem is it is completely skipping the assets which are not in public directory. So images in assets folder which are under loop or passed by props are getting skipped completely.
