### ISSUE TITLE
[Feature request] Fix sourcemap bundling / DX

### ISSUE THREAD

**Issue by matthew-dean** [nuxt/nuxt#22773]
### Describe the feature

Right now, if a Nuxt configuration is opting to use sourcemaps / dev mode, then the resources sent to the browser / end user can be absolutely enormous. That's because there are only two values for the client `true` or `false` (or `undefined`, meaning false), and what `true` means is "inline sourcemaps only". This creates a problem when trying to evaluate initial bundle size in Chrome devtools, because, for example, importing `vue` will result in DevTools reporting a resource size of 2.6MB.

When I log the Vite config in the `vite:extendConfig` or try to explicitly set Vite to use the `true` option instead of `inline`, Nuxt still pushes the source map inline. However, if I look at the Vite cache, the sourcemap is separate, so it seems like somehow the sourcemap is getting injected into the sent resource?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/19253.

It should be possible to configure this by setting `vite.sourcemap` at the moment.

**Comment by danielroe** [comment]
In production or dev?
