### ISSUE TITLE
Allow to modify global useFetch

### ISSUE THREAD

**Issue by DarkGhostHunter** [nuxt/nuxt#22778]
## The problem

Uses that need to use interceptors or anything else on `useFetch()` require to:

a. Create a new composable `useCustomFetch()` with the new functionality.
b. Create a new compasable with `$fetch` and add the new functionality with the old.
c. Modify the `useFetch()` on each call in every part of the application.

All of these scenarios could be fixed by offering the user a way to modify the `useFetch()` function _before_ its given into userland. 

## Solution

This could be accomplished easily by allowing the user to _replace_ the `useFetch()` composable with it' own and receive the original object. Each callback registered would be executed without order guarantee.

```js
// /composables/useFetch.js

export default () => {
    return useFetch().global(fetch => {
        // ...
    })
}
```

This approach fixes four things:

- Doesn't replaces `useFetch()`, it extends it.
- Users that already use `useFetch.js` can still use it as always.
- Users that already use `useCustomFetch.js` can still use it as always.
- Remove the `WARN  Duplicated imports "useFetch", the one from "#app" has been ignored`

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by jd-solanki** [comment]
You can already do this: https://github.com/nuxt/nuxt/issues/14936#issuecomment-1397369123

Track here: https://github.com/nuxt/nuxt/issues/14736
