### ISSUE TITLE
v-html not getting hydrated/updated on prerendered site

### ISSUE THREAD

**Issue by codeflorist** [nuxt/nuxt#22784]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.6.0
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-ycgj3t?file=app.vue

### Describe the bug

Using `v-html` on a prerendered site will result in the html not getting updated after hydration.

Here is the example used in the stackblitz:

```js
<script setup>
const timestamp = ref();
timestamp.value = Date.now();
</script>
<template>
  <div>
    <div v-html="timestamp" />
    {{ timestamp }}
  </div>
</template>
```

After loading the prerendered site, the timestamp in the `v-html` ist not getting updated, but stays with the value it was prerendered with. I would expect that div to update to the current timestamp on every pageload.

**Comment by danielroe** [comment]
This is reproducible with Vue without Nuxt: https://stackblitz.com/edit/github-vxyebj?file=src/App.vue.

Check https://github.com/vuejs/core to see if there's already an issue tracking this, and feel free to raise one if not. (But it's not a Nuxt issue specifically, so I'll close it here.)

**Comment by codeflorist** [comment]
many thanks, daniel! 

upstream issue created: https://github.com/vuejs/core/issues/9033

**Comment by ColtHands** [comment]
If anyone has an issue with this - an easy fix is wrapping code with `<ClientOnly>` component.
Not ideal, but fixable.

**Comment by fairySusan** [comment]
@ColtHands  It's work in dev env, but not work in production env.

**Comment by vibonacci** [comment]
Does anybody know a workaround how to use v-html with data fetched in asyncData without using <ClientOnly>?

We really can't use ClientOnly and we need v-html.

**Comment by surgiie** [comment]
Did anyone find a fix for this?

**Comment by tulindulin** [comment]
> Did anyone find a fix for this?

Found workaround with helper component:

```
<template>
<span ref="refHtml" v-html="htmlContent"></span>
</template>

<script lang="ts" setup>
interface TranslatableHtmlProps {
  htmlContent: string,
}
const props = defineProps<TranslatableHtmlProps>();

const refHtml = ref<HTMLElement | null>(null);

function updateHtmlContent() {
  if (!refHtml.value) {
    return;
  }
  refHtml.value.innerHTML = props.htmlContent;
}
onMounted(updateHtmlContent);
watch(() => props.htmlContent, updateHtmlContent);
</script>
