### ISSUE TITLE
Can't get response headers when using $fetch.raw

### ISSUE THREAD

**Issue by martinsjek** [nuxt/nuxt#22791]
### Environment

- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.6.0
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-wc42d2?file=utils%2FfetchTest.ts,server%2Fapi%2Ftest-400.ts,app.vue

### Describe the bug

When having response status anything other than 2XX then i can't get response headers. Reproduction shows that i'm using NUXT server/api, but in my real project i'm using external API where that is critical.
When `console.log(response.headers);` then nothing shows up in Nuxt console other than error about 400 status.

### Logs

```shell-script
{ 'content-type': 'application/json' }   --- WHEN 200                                                                                            1:06:06 PM
[nuxt] [request error] [fatal] [400] Just error   --- WHEN 400                                                                      1:06:06 PM
  at new H3Error (./node_modules/h3/dist/index.mjs:150:5)  
  at Module.createError (./node_modules/h3/dist/index.mjs:180:15)  
  at eval (./.nuxt/dev/index.mjs:829:80)  
  at eval (./node_modules/h3/dist/index.mjs:1651:47)                                                                                 1:05:57 PM
  at async Object.eval (./node_modules/h3/dist/index.mjs:1802:19)  
  at async toNodeHandle (./node_modules/h3/dist/index.mjs:2012:7)  
  at async ufetch (./node_modules/unenv/runtime/fetch/index.mjs:28:17)  
  at async AsyncFunction.$fetchRaw2 (./node_modules/ofetch/dist/shared/ofetch.00501375.mjs:236:26)  
  at async Module.fetchTest (./utils/fetchTest.ts:2:20)  
  at async eval (./app.vue:21:19)
```

**Comment by martinsjek** [comment]
Any updates on this?

**Comment by danielroe** [comment]
The reason is that `$fetch` treats non 2xx responses as errors. Instead, you can run `const response = await $fetch.raw(url, { ignoreResponseError: true })` 

https://stackblitz.com/edit/nuxt-starter-wc42d2

**Comment by martinsjek** [comment]
@danielroe Thank you for response, but this does not fix my issue, and your provided stackBlitz example doesn't show any changes.
My goal is to see response headers when response status code is not 2xx.

**Comment by tomsdob** [comment]
@danielroe When using `ignoreResponseError: true`, the `useAsyncData` returned `error` value is null and the error seems to be applied to the returned `data` value, which, in my case, would mean that I would have to write additional logic to determine if the response had an error or not as `data` now contains the error response rather than `error`. Basically this makes the returned `error` value of `useAsyncData` useless...
Forked reproduction: https://stackblitz.com/edit/nuxt-starter-4vqmr9?file=utils%2FfetchTest.ts,app.vue

**Comment by danielroe** [comment]
By passing `ignoreResponseError`, you're opting out of built-in error handling. So (after reading the headers) you should then throw the error if you want asyncData to populate the `error.value` for you.
