### ISSUE TITLE
Nuxt dev server 300% CPU usage all the time

### ISSUE THREAD

**Issue by martinszeltins** [nuxt/nuxt#22795]
### Environment

Docker, Ubuntu 22.04

### Reproduction

https://github.com/martinszeltins/new-nuxt

### Describe the bug

The CPU usage of the Nuxt dev server is at 300% all the time and I have no idea why. Even the Nuxt devtools don't open (not sure if that is related though). The laptop fans are all spinning like crazy as soon as I start the dev server.

The process is `cli-run.mjs` that is running hot all the time.

It is easy to reproduce the issue in my repo. Simply run `docker-compose up -d`, wait for it to install deps and then run the dev server from inside the container using `pnpm run dev`

Here is a screenshot:
![image](https://github.com/nuxt/nuxt/assets/34019878/8ffe4df9-7730-4639-974d-77df9c0bd968)

**Comment by danielroe** [comment]
Would you be able to provide a more minimal reproduction?

For example, does this reproduce outside a docker environment?

You can also start by removing each of your modules in turn and disabling `typescript.typeCheck`.

**Comment by martinszeltins** [comment]
I have created a much better issue regarding this with minimal reproduction here - https://github.com/nuxt/nuxt/issues/22910

I will close this issue, please refer to the new issue.
