### ISSUE TITLE
Nuxt devtools do not open

### ISSUE THREAD

**Issue by martinszeltins** [nuxt/nuxt#22797]
### Environment

Docker, Ubuntu 22.04

### Reproduction

https://github.com/martinszeltins/new-nuxt

### Describe the bug

When I click on the Nuxt devtools it opens the loading screen and shows the loading forever but never opens up.

I should also mention that this begin to happen after I migrated from yarn to pnpm in my project.

It shows this loading screen forever 👇️
![image](https://github.com/nuxt/nuxt/assets/34019878/09f59e8a-622d-42a8-82e8-0ca088ea064f)

Error:
![image](https://github.com/nuxt/nuxt/assets/34019878/a6548a83-1e50-4ed8-93e2-869f71bf0f24)

**Comment by danielroe** [comment]
cc: @antfu

**Comment by antfu** [comment]
Continue with https://github.com/nuxt/nuxt/issues/22850#issuecomment-1694944111

I found that this is a user-land misconfig. If I print resolved `viteConfig.server.hmr` it says

```js
{ protocol: 'ws', port: 24679, clientPort: 35547 }
```

This means the server is listening to `24679` while the client is connected to the non-exist `35547`.

I'd again mention that [a **minimal** reproduction](https://antfu.me/posts/why-reproductions-are-required#reproducible-projects-or-playgrounds) is much more preferred to help maintainers identify the issue quickly. Thanks.
