### ISSUE TITLE
Getting wrong message - ⚠ 🚦 No routes defined. Check if your pages folder exists

### ISSUE THREAD

**Issue by martinszeltins** [nuxt/nuxt#22796]
### Environment

Docker, Ubuntu 22.04

### Reproduction

https://github.com/martinszeltins/new-nuxt

### Describe the bug

When I run the nuxt dev server, it says that I don't have any routes defined. But that is not true. I have routes and I also have pages directory. I have created both `index` and `about` routes and the pages open fine. Perhaps this is an issue with the way I have organized my app into modules and have custom config for pages? The error / warning message is wrong.

![image](https://github.com/nuxt/nuxt/assets/34019878/512707f7-1378-45f2-955e-8676d98b8162)

Here is my nuxt config:

````
export default defineNuxtConfig({

    serverDir: './common/server',

    dir: {
        assets: './common/assets',
        layouts: './common/layouts',
        middleware: './common/middleware',
        modules: './common/modules',
        pages: './common/pages',
        plugins: './common/plugins',
        public: './common/public',
        static: './common/static',
    },

})

````

**Comment by danielroe** [comment]
The `no routes defined` message is not coming from Nuxt but from `nuxt-typed-router`.

You might also consider enabling `experimental.typedPages` for a built-in solution.

**Comment by martinszeltins** [comment]
> typedPages

Thanks, I must have missed this experimental feature when I was reading the docs.
