### ISSUE TITLE
ECONNREFUSED on NodeJS 18

### ISSUE THREAD

**Issue by simonmaass** [nuxt/nuxt#22816]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.6.0
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      components, app, runtimeConfig, css, build, vuetify, googleSignIn, imports, modules, devtools, vite     
- Runtime Modules:  @nuxt-alt/vuetify@1.1.1, @nuxtjs/tailwindcss@6.8.0, nuxt-vue3-google-signin@0.0.9, @pinia/nuxt@0.4.11, nuxt-lodash@2.5.0, dayjs-nuxt@1.1.2, @vee-validate/nuxt@4.11.3
- Build Modules:    -
------------------------------

### Reproduction

Make a fetch request on server side

### Describe the bug

i get the following error:

{
  statusCode: 500,
  fatal: false,
  unhandled: false,
  __nuxt_error: true,
  [cause]: TypeError: fetch failed
      at Object.fetch (node:internal/deps/undici/undici:11457:11)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async $fetchRaw2 (node_modules/ofetch/dist/shared/ofetch.00501375.mjs:219:26)
      at async $fetchRaw2 (node_modules/ofetch/dist/shared/ofetch.00501375.mjs:228:14)
      at async $fetch2 (node_modules/ofetch/dist/shared/ofetch.00501375.mjs:261:15)
      at async Proxy.fetchUser (stores\useAuthStore.ts:18:29)
      at async F:\code\meevo\mac-frontend\plugins\loadUser.ts:11:85
      at async Object.callAsync (node_modules/unctx/dist/index.mjs:72:16)     
      at async applyPlugin (node_modules\nuxt\dist\app\nuxt.js:112:25)
      at async Module.applyPlugins (node_modules\nuxt\dist\app\nuxt.js:129:7) {       
    cause: Error: connect ECONNREFUSED ::1:8000
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
      errno: -4078,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '::1',
      port: 8000
    }
  }

### Additional context

maybe releated? https://github.com/node-fetch/node-fetch/issues/1624

**Comment by lukaszarpak** [comment]
I experience the same issue. To reproduce it try fetching data on SSR with a local URL from another app.

**Comment by lukaszarpak** [comment]
@pi0 it's `Nuxt Generation CLI Experience (nuxi v3.7.3)`

I resolved the issue by setting the `baseUrl` in ofetch options to `http://nginx:80/` which is a network URL of my API container. So the issue was on my side, not on Nuxt's or ofetch's. Thanks for a quick reply @pi0 !

**Comment by lisaschumann** [comment]
@lukaszarpak I am having the same issue when calling useFetch or $fetch from my pinia store. How did you set baseUrl exactly? I am not sure where to define ofetch options. Many thanks!

**Comment by lukaszarpak** [comment]
I created a composable function. which returns `$fetch(url, fetchOptions)` with `fetchOptions` being a configuration object for ofetch. You can set `baseUrl` there alongside other options. Then whenever I need to call API I use the composable function instead of `fetch` directly.

**Comment by lisaschumann** [comment]
Thanks for your help @lukaszarpak!

**Comment by nhh** [comment]
This is due to a node18 bug. 

Tried to fetch localhost:3000 with node 18, got ECONNREFUSED, switched to node22 it worked.

```
Welcome to Node.js v18.20.2. <--------------------------------------------------------

Type ".help" for more information.
> fetch("http://localhost:3000/api/settings.json").then(console.log)
Promise {
  <pending>,
  [Symbol(async_id_symbol)]: 68,
  [Symbol(trigger_async_id_symbol)]: 40
}
> Uncaught [TypeError: fetch failed] {
  cause: Error: connect ECONNREFUSED ::1:3000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:128:17) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 3000
  }
}
> .exit
❯ nvm use 22
N/A: version "v22" is not yet installed.

You need to run `nvm install 20` to install and use it.
❯ nvm install 22
Downloading and installing node v22.14.0...
Downloading https://nodejs.org/dist/v22.14.0/node-v22.14.0-darwin-x64.tar.xz...
############################################################################################################################################################################################ 100.0%
Computing checksum with sha256sum
Checksums matched!
tar: Failed to set default locale
Now using node v22.14.0 (npm v10.9.2)

❯ node
Welcome to Node.js v22.14.0. <--------------------------------------------------------
Type ".help" for more information.
> fetch("http://localhost:3000/api/settings.json").then(console.log)
Promise {
  <pending>,
  [Symbol(async_id_symbol)]: 52,
  [Symbol(trigger_async_id_symbol)]: 51
}
> Response {
  status: 200,
  statusText: 'OK', <------------------------------------------------------------------------------------
  headers: Headers {
    'x-request-id': '7f3d0d75-dbdf-42e0-a354-ff9abae14f2d',
    'x-runtime': '0.153448',
    'content-length': '56'
  },
  body: ReadableStream { locked: false, state: 'readable', supportsBYOB: true },
  bodyUsed: false,
  ok: true,
  redirected: false,
  type: 'basic',
  url: 'http://localhost:3000/api/settings.json'
}
```
