### ISSUE TITLE
fix: attribute "crossorigin" should omit value

### ISSUE THREAD

**Issue by dargmuesli** [nuxt/nuxt#22825]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.7.0
- CLI Version:      3.7.0
- Nitro Version:    2.6.1
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      app, devtools, modules
- Runtime Modules:  @nuxtjs/html-validator@1.5.2
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-b2yprs?file=package.json

### Describe the bug

Starting with Nuxt 3.7 the html validator plugin reports that `<link rel="modulepreload" as="script" crossorigin="" href="...">` `crossorigin` and two other similar occurences now have an empty value (`=""`) set when it should not have this value: https://html-validate.org/rules/attribute-empty-style.html
For Nuxt 3.6.5 the validator did not find this.

**Comment by danielroe** [comment]
cc: @harlan-zw

**Comment by harlan-zw** [comment]
This is valid HTML afaik? https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes

I think that validator is bugged possibly

**Comment by dargmuesli** [comment]
It's just a style preference (https://html-validate.org/rules/attribute-empty-style.html) which previously required no configuration to fulfill. I propose to follow that style preference again but that's only a cosmetic proposal.

**Comment by danielroe** [comment]
Thanks. Seems this is not a bug; we can close here. @dargmuesli, I think likely we can raise in https://gitlab.com/html-validate/html-validate, or perhaps you could raise in https://github.com/unjs/unhead but I suspect Harlan's point about there being a reason will still stand.

**Comment by harlan-zw** [comment]
This is completed as of Unhead 1.4
