### ISSUE TITLE
Uncaught "Unexpected token" on minimal install when using titleTemplate

### ISSUE THREAD

**Issue by dulnan** [nuxt/nuxt#22830]
### Environment

Can be reproduced on any environment.

### Reproduction

https://codesandbox.io/p/sandbox/interesting-sun-j9lq89

Bare setup with only Nuxt 3.7.0, using a custom titleTemplate configuration:

```typescript
export default defineNuxtConfig({
  app: {
    head: {
      titleTemplate: "%s - foobar",
    },
  },
});
```

### Describe the bug

With this configuration the following exception is visible in the browser console:

```
(index):37 Uncaught SyntaxError: Unexpected token ':' (at (index):37:45)
```

Because this <script> tag is placed in the head:

```html
<script id="unhead:payload">{"titleTemplate":"%s - foobar"}</script>
```

**Comment by danielroe** [comment]
cc: @harlan-zw

**Comment by harlan-zw** [comment]
Unhead 1.3.8 includes a fix for this. Thanks for the issue @dulnan
