### ISSUE TITLE
Error on image compression in public directory with AWS-Preset

### ISSUE THREAD

**Issue by NtchPlayer** [nuxt/nuxt#22832]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.17.1`
- Nuxt Version:     `3.7.0`
- CLI Version:      `3.7.0`
- Nitro Version:    `2.6.1`
- Package Manager:  `npm@9.8.1`
- Builder:          `-`
- User Config:      `nitro`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-ykr2t1

-> Open this stackblitz
-> Go to /icon.png

### Describe the bug

All .png or .jpg files in public directory are broken when you build your app with AWS-Preset.

### Additional context

This issue can be related to this pull request: https://github.com/unjs/nitro/pull/1274

**Comment by danielroe** [comment]
cc: @pi0

**Comment by danielroe** [comment]
Closing as this should be resolved in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/), and in the next release of Nitro.

**Comment by pi0** [comment]
(Fix already released, you can upgrade with npx nuxi upgrade —force)

**Comment by NtchPlayer** [comment]
Thx you ! It's work :)

**Comment by pi0** [comment]
Thanks for the tips @Azcray. Don't hesitate to open a PR to improve AWS deployment guides in nitro.
