### ISSUE TITLE
server -> api dir Generates the sawwger document

### ISSUE THREAD

**Issue by evanlong0926** [nuxt/nuxt#22836]
### Describe the feature

This is very useful when we have parts of the interface exposed to the outside

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Believe it or not, this is already done!

See https://github.com/unjs/nitro/pull/1162.

**Comment by evanlong0926** [comment]
> Believe it or not, this is already done!
> 
> See [unjs/nitro#1162](https://github.com/unjs/nitro/pull/1162).

Wow, that's cool!

**Comment by imcm7** [comment]
@danielroe  And how to add authentication and descripte params, query and headers, it not read @openapi comments?
