### ISSUE TITLE
Glob api route is not prerendered when used by a useFetch

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt/nuxt#22841]
### Environment

nuxt@3.7.0
nuxt/content

### Reproduction

https://stackblitz.com/edit/github-njygor?file=server%2Fapi%2Fpackages%2F%5Bname%5D.ts

### Describe the bug

_I could do something wrong And any resemblance with unjs/website is coincidental. :)_

Imagine you have 2 pages:
- `/packages.vue`, which list packages
- `/packages/[name].vue`

Imagine you have 1 API in the server folder:
- `api/[name].ts` which return a number

In your `[name].vue` page, you call the API using `await useFetch('/api/' + name)`.

To build the application, you use `npm run generate` in order to render it statically. 

Then, use `npx serve .output/public` and open the app.

Where is the bug?

Is you go on a package page, directly from the URL, everything is fine. If you go to a package page from the packages list page, fetch will return a 404.

The API is not prerendered even when adding a route rules to `/api/**` and since we are statically generated our site, there is no more API.

I think it works fine when coming directly on the package page because Nuxt replace the API call by a function. But because of that, Nitro never received the call and do not save the API call.

If, in the config, you replace the glob by a URL like `/api/hello`, everything works fine but I'm having more than 40 pages and I don't want to do it manually for every package.

**Comment by danielroe** [comment]
Would you try enabling `experimental.payloadExtraction` manually? If that doesn't work, then could you check whether all the package pages are prerendered?

Nuxt shouldn't fetch the api route at all if payload extraction is enabled because a payload should be created for that page for client-side navigation.

**Comment by Barbapapazes** [comment]
> Would you try enabling `experimental.payloadExtraction` manually? If that doesn't work, then could you check whether all the package pages are prerendered?
> 
> Nuxt shouldn't fetch the api route at all if payload extraction is enabled because a payload should be created for that page for client-side navigation.
> 
> If that doesn't work, can I reproduce this on [unjs/website](https://github.com/unjs/website)?

Here a reproduction, https://stackblitz.com/edit/github-4leygb?file=nuxt.config.ts but everything works fine. 😑 Will continue to investigate.

**Comment by Barbapapazes** [comment]
And I don't need to add the api route to prerender since I generate my project.

**Comment by Barbapapazes** [comment]
@danielroe I've got a reproduction. It happens with `nuxt/content` : https://stackblitz.com/edit/github-njygor?file=server%2Fapi%2Fpackages%2F%5Bname%5D.ts

**Comment by Barbapapazes** [comment]
But content is generated in `_payload` 
![image](https://github.com/nuxt/nuxt/assets/45267552/c1439aa0-52d8-4eb4-b49c-f26a75e3f69e)

**Comment by Barbapapazes** [comment]
`index.html` without `nuxt/content`

![image](https://github.com/nuxt/nuxt/assets/45267552/68794290-6ceb-401f-a181-56401464db8b)

`index.html` with `nuxt/content`

![image](https://github.com/nuxt/nuxt/assets/45267552/b26e9f09-175f-4f14-b427-c9cd57d11c7e)

In the second, there is no `_payload`.

**Comment by Barbapapazes** [comment]
@farnabaz I'm tagging you since it could be related to `@nuxt/content`!

**Comment by Barbapapazes** [comment]
The HTTP call is made even when application is generated.
