### ISSUE TITLE
nuxt3.7  nitro,devProxy not available

### ISSUE THREAD

**Issue by facexyy** [nuxt/nuxt#22848]
### Environment

nuxt3.7

### Reproduction

nuxt3.7

### Describe the bug

  nitro: {
    devProxy: {
      "/dev": {
        target: "https://xxxxx.com",
        changeOrigin: true,
        prependPath: true,
      },
    },
  },
  
  The proxy is unavailable, has the proxy method been updated?

**Comment by jonasolesen** [comment]
This was a [bug](https://github.com/unjs/httpxy/issues/5) with the underlying httpxy package used for proxying. It's been fixed in version 0.1.4, and updating to that version solved the issue for me 🙂

**Comment by facexyy** [comment]
> 这是用于代理的底层 httpxy [包的错误。](https://github.com/unjs/httpxy/issues/5)它已在 0.1.4 版中修复，更新到该版本为我🙂解决了问题



> This was a [bug](https://github.com/unjs/httpxy/issues/5) with the underlying httpxy package used for proxying. It's been fixed in version 0.1.4, and updating to that version solved the issue for me 🙂

Thank you very much, it can be used normally after the upgrade, I am very happy
