### ISSUE TITLE
nuxt3.7 [Vue Router warn]: No match found for location with path "/serviceWorker.js"

### ISSUE THREAD

**Issue by 7836246** [nuxt/nuxt#22849]
### Environment

[Vue Router warn]: No match found for location with path "/serviceWorker.js"

### Reproduction

[Vue Router warn]: No match found for location with path "/serviceWorker.js"

### Describe the bug

[Vue Router warn]: No match found for location with path "/serviceWorker.js"

**Comment by Umid-Berdiev** [comment]
@7836246 , Hi, did you find the solution, I've got the same issue and going to find solution couple of days

**Comment by xcy960815** [comment]
I also encountered the same problem

**Comment by 7836246** [comment]
Create an empty file serviceWorker.js under pubilc/

**Comment by xcy960815** [comment]
> Create an empty file serviceWorker.js under pubilc/

Problem solved. But why is this happening?

**Comment by 7836246** [comment]
> > Create an empty file serviceWorker.js under pubilc/
> 
> Problem solved. But why is this happening?

不知道

**Comment by xcy960815** [comment]
> > > Create an empty file serviceWorker.js under pubilc/
> > 
> > 
> > Problem solved. But why is this happening?
> 
> 不知道

好吧，谢谢啦，虽然没啥影响，就是看着不舒服

**Comment by Download** [comment]
I see this log warning as well, in a standard Nuxt 3 hello world project.

**Comment by Download** [comment]
Strangely, I don't see `Worker` being spelled with a capital `S`...

```console
[nitro] ✔ Nitro built in 1854 ms
[Vue Router warn]: No match found for location with path "/serviceworker.js"
[Vue Router warn]: No match found for location with path "/serviceworker.js"
[Vue Router warn]: No match found for location with path "/serviceworker.js"
```

**Comment by popdo** [comment]
I also suddenly appeared today. Can someone explain the reason? I want to know under what circumstances this would happen.

**Comment by johnhom1024** [comment]
![image](https://github.com/nuxt/nuxt/assets/20170882/68c39490-daaa-4654-a54b-4f85b1e2ac3e)

I reproducted the problem. First I will show how to fix it.
Just open Chrome DevTools, and go to the Application -> Service workers, then click the "Unregister" button to unregister it,
finally Refresh the page, done.

<img width="1219" alt="image" src="https://github.com/nuxt/nuxt/assets/20170882/136b15db-ba9a-4455-ab2d-bec75a80908b">

Why there is running a service workers? Not the Nuxt carry it, just besause I ran a other project which has registered the service worker in http://localhost:3000.

I can found it in Chrome at this path: chrome://serviceworker-internals/?devtools
![image](https://github.com/nuxt/nuxt/assets/20170882/35d3a5f5-ecc3-4805-9e9f-b4dc31522e56)

I unregistered it and finally vue-router warning never appear.
