### ISSUE TITLE
Issues with provide/inject in modules

### ISSUE THREAD

**Issue by Techassi** [nuxt/nuxt#22853]
### Environment

- Operating System: Linux
- Node Version:     v20.5.0
- Nuxt Version:     3.7.0
- CLI Version:      3.7.0
- Nitro Version:    2.6.1
- Package Manager:  pnpm@8.6.12
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-d9f4p7

### Describe the bug

It seems like there are a few issues:

1. The server displays `500 - useInject is not defined` in the reproduction. The auto imports file under `playground/.nuxt/imports.d.ts` includes the correct path to the composable: `export { useInject } from '../../src/runtime/composable';`.
2. Sometimes, the auto import magically starts working (no `500 - useInject is not defined`). Then, however, I'm still unable to use the inject. The server then reports `[Vue warn]: injection "my-key" not found.`.

I stumbled into this issue when writing a module for my Vue library. It is required to run on the client side only (that's why I added the `.client` suffix to the Nuxt plugin file). It additionally provides access to a central manager instance via the provide/inject mechanism, which does not work when using a Nuxt module.

### Additional context

https://github.com/vue-youtube/vue-youtube

**Comment by danielroe** [comment]
Modules need to import explicitly from `#imports` - this is because we disable full scanning for auto-imports within node_modules, for performance reasons.

In the module starter kit we add [this file](https://github.com/nuxt/starter/blob/module/.nuxtrc#L1) to disable auto-imports so you aren't misled in development into thinking they will be usable once your module is built.

**Comment by Techassi** [comment]
Using `#imports` solves the `500 - useInject is not defined` error. It does, however, not resolve the issues I'm having with the provide/inject API.

**Comment by danielroe** [comment]
What are the issues you are having with the provide/inject API?
