### ISSUE TITLE
Valid imports fail in one specific component

### ISSUE THREAD

**Issue by datsenkoboos** [nuxt/nuxt#22857]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.7.0
- CLI Version:      3.7.0
- Nitro Version:    2.6.1
- Package Manager:  pnpm@8.6.3
- Builder:          -
- User Config:      css, runtimeConfig, modules, components, API_URL
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @pinia/nuxt@0.4.11
- Build Modules:    -
------------------------------

### Reproduction

https://codesandbox.io/p/github/s1kebeats/s1kebeats_client/issue

### Describe the bug

[AppLogo](https://github.com/s1kebeats/s1kebeats_client/blob/dev/components/ui/AppLogo/AppLogo.vue) component  import works in [form.vue](https://github.com/s1kebeats/s1kebeats_client/blob/dev/layouts/form.vue), but doesn't work in [AppHeader](https://github.com/s1kebeats/s1kebeats_client/blob/dev/components/modules/AppHeader/AppHeader.vue). Imports are absolutely identical.

**Error:**
```
[Vue warn]: Failed to resolve component: AppLogo
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
```

[Search](https://github.com/s1kebeats/s1kebeats_client/blob/dev/components/modules/AppHeader/components/Search/Search.vue) component import in [AppHeader](https://github.com/s1kebeats/s1kebeats_client/blob/dev/components/modules/AppHeader/AppHeader.vue) doesn't work too.

**Error:**
```
[Vue warn]: Failed to resolve component: Search
[1] If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
```

You can visit `/register` route to see the import working in [form.vue](https://github.com/s1kebeats/s1kebeats_client/blob/dev/layouts/form.vue) and visit `/` route to see the import not working in [AppHeader](https://github.com/s1kebeats/s1kebeats_client/blob/dev/components/modules/AppHeader/AppHeader.vue).

### Additional context

I also have this in logs:

`[Vue Router warn]: No match found for location with path "/_nuxt/node_modules/.cache/vite/client/deps/"`

### Logs

```shell-script
[Vue Router warn]: No match found for location with path "/_nuxt/node_modules/.cache/vite/client/deps/"
[Vue warn]: Failed to resolve component: AppLogo
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Failed to resolve component: Search
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
```

**Comment by danielroe** [comment]
It needs to be `<script setup>` rather than `<script>`. Merely importing something into a `<script>` block doesn't make it available to your template - you would still need to have `export default defineComponent({ components: { AppLogo } })` or equivalent.

**Comment by datsenkoboos** [comment]
Thank you, didn't see that somehow. Sorry for taking your time

**Comment by danielroe** [comment]
No problem at all. Glad I was able to help.
