### ISSUE TITLE
Issues with Nuxi CLI 3.7?

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt#22867]
Hi everyone! 👋

With [Nuxt 3.7](https://nuxt.com/blog/v3-7), we have introduced a brand new CLI - [nuxt/cli](https://github.com/nuxt/cli). We are thrilled to share our exciting plans for it, along with numerous improvements. However, there might be unforeseen regressions associated with the new CLI.

In such cases, we apologize for any inconvenience caused. Please take a moment to review the [open issues](https://github.com/nuxt/cli/issues) as there might already be a known issue being tracked. If not, please don't hesitate to [open a new issue](https://github.com/nuxt/cli/issues/new).

Thank you!

**Comment by YumaInaura** [comment]
Thanks

Where gone `nuxi start`  ?
command not found in 3.7.0

```
 npm run start

> start
> nuxt start

Nuxt CLI (nuxi)                                                                                                                    8:16:21 PM

USAGE nuxi add|analyze|build-module|build|cleanup|_dev|dev|devtools|generate|info|init|module|prepare|preview|test|typecheck|upgrade
```

**Comment by mitch1009** [comment]
I'm encountering an issue with the command-line interface (CLI) while attempting to build the application in GitHub Actions. The problem arises when it attempts to install dependencies. My project follows a monorepo architecture, and within the workspace managed by pnpm, "nuxi" is one of the projects.

**Comment by pi0** [comment]
@YumaInaura We have added back the `start` command (alias to `preview`) in latest nuxi release please try to upgrade.


@mitch1009 Would you mind to open an issue in nuxi with ideally reproduction and some more CI logs?

**Comment by mitch1009** [comment]
> @YumaInaura We have added back the `start` command (alias to `preview`) in latest nuxi release please try to upgrade.
> 
> 
> @mitch1009 Would you mind to open an issue in nuxi with ideally reproduction and some more CI logs?

Definitely am on it. Thanks for the response

**Comment by YumaInaura** [comment]
@pi0 

>We have added back the start command (alias to preview) in latest nuxi release please try to upgrade.

i did not know start command is alias of preview command.
its good update thanks!

**Comment by manniL** [comment]
After two more minor versions, I think we can close this issue here ☺️
If there are CLI-related problems, suggestions or feedback, please use the https://github.com/nuxt/cli/ repo! 👏🏻
