### ISSUE TITLE
API Routes Break on when deploying to Vercel

### ISSUE THREAD

**Issue by khazixi** [nuxt/nuxt#22877]
------------------------------
- Operating System: Darwin
- Node Version:     v18.17.1
- Nuxt Version:     3.7.0
- CLI Version:      3.7.0
- Nitro Version:    2.6.2
- Package Manager:  pnpm@8.7.0
- Builder:          -
- User Config:      devtools, typescript, nitro, pinia, modules
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @pinia/nuxt@0.4.11
- Build Modules:    -
------------------------------

Config:
```ts
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  typescript: {
    strict: true,
  },
  nitro: {
    preset: 'node-server',
		moduleSideEffects: ["lucia/polyfill/node"],
  },
  pinia: {
    autoImports: ["defineStore", ["defineStore", "definePiniaStore"]],
  },
  modules: [
    "@nuxtjs/tailwindcss",
    // "@nuxtjs/eslint-module",
    "@pinia/nuxt"
  ],
});
```
The issue, when using the dev server all of my API Routes work correctly, however, when deploying to Vercel all API Routes return a 404 on fetch. 

If you need a reference to the code I have the GitHub URL Linked here: https://github.com/khazixi/Monopoly-datasite
```[tasklist]
### Tasks
```

**Comment by manniL** [comment]
Does it work without overriding the nitro preset (removing the `preset: 'node-server'` part)? 🤔

**Comment by danielroe** [comment]
Exactly. You should either remove it entirely and rely on Nuxt auto-detecting vercel environment (the best option), or set it conditionally like this:

```ts
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  $production: {
    nitro: {
      preset: 'vercel',
    },
  }
});
```
