### ISSUE TITLE
3.7: New project or existant: TS errors with auto-import (useFetch, useHeader etc...)

### ISSUE THREAD

**Issue by jervalles** [nuxt/nuxt#22874]
### Environment

- Operating System: Linux
- Node Version:     v20.5.1
- Nuxt Version:     3.7.0
- CLI Version:      3.7.2
- Nitro Version:    2.6.2
- Package Manager:  npm@9.8.1
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

this is a fresh project install with the nuxt latest version

### Describe the bug

On a fresh installed project

Each time I wanna use an auto-imported module, I got a TS error like this: 

Cannot find name 'useHeader'.ts(2304)
or
Cannot find name 'useAsyncData'.ts(2304)
(even useFetch etc...)

![image](https://github.com/nuxt/nuxt/assets/53664568/4995fa47-c2c4-4e21-8425-3cc5d88d3217)

the error desapear when I remove lang="ts"

here the tsconfig: 

```
{
  // https://nuxt.com/docs/guide/concepts/typescript
  "extends": "./.nuxt/tsconfig.json",
}
```

nuxt.config.ts: 
```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
})

```

Also have these kind of errors on Nitro part (on the non-fresh-app):

![image](https://github.com/nuxt/nuxt/assets/53664568/b0ad7e92-74e1-4f05-9d82-89820d9abbcd)

Tried to reinstall my VSCODE completely

### Additional context

package.json: (fresh installed app)
```
{
  "name": "nuxt-app",
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/devtools": "latest",
    "@types/node": "^20.5.7",
    "nuxt": "^3.7.0"
  }
}

```

_No response_

**Comment by manniL** [comment]
Did you run the dev server at least once (or `npx nuxi prepare`)?

**Comment by jervalles** [comment]
> px nuxi prepare

yes I starts the server with npm run dev (and tried npx nuxi dev)
When I do npx nuxi prepare it stays well "types generated in .nuxt" but nothing changes.

But on the main project (the one that I made couple days ago, it stays blocked on "types generated" (but actually I wanna fix the new fresh project before)

**Comment by jervalles** [comment]
> Did you run the dev server at least once (or `npx nuxi prepare`)?

yes I starts the server with npm run dev (and tried npx nuxi dev)
When I do npx nuxi prepare it stays well "types generated in .nuxt" but nothing changes.

But on the main project (the one that I made couple days ago, it stays blocked on "types generated" (but actually I wanna fix the new fresh project before)

**Comment by jervalles** [comment]
just saw that my VSCODE says "no tsconfig" 

![image](https://github.com/nuxt/nuxt/assets/53664568/d650db7f-030d-46b8-8592-29fd6727a1c6)

**Comment by jervalles** [comment]
Fixed, I just forgot to install the WSL package for VSCODE (I'm using WSL)
