### ISSUE TITLE
[feature request] add code documentation for all user facing exports

### ISSUE THREAD

**Issue by Hebilicious** [nuxt/nuxt#22884]
### Describe the feature

It would be great if we could provide code documentation for everything that ends up being auto-imported and available in userland (as well as a link towards the actual docs).
Some composables are already documented, such as https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/app/composables/state.ts

It would be great if we could go through all of them to add missing docs and a link to the official docs.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/13653 - feel free to update/edit that issue text directly 👍 (I worry it might be a bit outdated, but we do link to it in the docs as a source-of-truth.)

**Comment by Hebilicious** [comment]
@danielroe I can't edit the issue directly 🙈
