### ISSUE TITLE
Prerender OpenGraph tags

### ISSUE THREAD

**Issue by mzenz** [nuxt/nuxt#22886]
### Describe the feature

After asking around all over the place on Discord and looking through Nuxt v3 and Nitro docs I cannot find any mentions to an effective way to make `nuxi generate` prerender `<head>` tags to get a working OpenGraph configuration.

I'm highly surprised that no one is bringing this up, it feels like we're the only ones trying to deploy fully-static / jamstack style SPAs.

In Nuxt v2 there was at least an index.html template you could use to manually insert such tags but that's gone in v3.

Can you please either consider implementing such a basic and useful feature or at least document a solid workaround on how to handle this?

## Things I tried:

- Upgraded to Nuxt v3.7 and enabled `headNext`.
- Used `useHead()`, `useServerSeoMeta()` and `useSeoMeta()` all of them producing identical results (i.e. no prerendered meta tags).

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
This should work out of the box. Have you, perchance, disabled generation of your Vue site on the server with `ssr: false`?

**Comment by danielroe** [comment]
`ssr` should always be enabled, particularly if you care about SEO.

**Comment by mzenz** [comment]
@danielroe that clarifies a lot, I can confirm that works, thanks so much for the assistance, it's much appreciated.
