### ISSUE TITLE
The behavior of middleware is inconsistent with vue-router's `beforeEach`

### ISSUE THREAD

**Issue by Mini-ghost** [nuxt/nuxt#22898]
### Environment

**Stackblitz**
------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.7.0
- CLI Version:      3.7.2
- Nitro Version:    2.6.2
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-owjclb

### Describe the bug

When switching routes, both global middleware should be executed, but currently only one is being executed and then it stops.

I believe this might be happening because it immediately exits the middleware loop when a middleware returns `true`. It should continue executing the subsequent middleware. Can I create a pull request to address this issue?

**Comment by danielroe** [comment]
A PR would be very welcome ❤️
