### ISSUE TITLE
useFetch calling server API removes multiple pipe characters

### ISSUE THREAD

**Issue by georgesaliba** [nuxt/nuxt#22890]
### Environment

- Operating System: Darwin
- Node Version:     v19.1.0
- Nuxt Version:     3.7.0
- CLI Version:      3.7.2
- Nitro Version:    2.6.2
- Package Manager:  npm@9.1.2
- Builder:          -
- User Config:      experimental, routeRules, devtools, modules, app, i18n, nitro
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.3, @nuxtjs/tailwindcss@6.8.0, @pinia/nuxt@0.4.11, nuxt-headlessui@1.1.4, @vueuse/nuxt@10.4.1, nuxt-lazy-hydrate@1.0.0
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-vwnadd

### Describe the bug

I have an API endpoint that returns a pipe-delimited string. However, when there are multiple pipes next to each other "like||this||or||||this", something is replacing the multiple pipes, making the response look "like|this|or||this" - every two pipe characters become one pipe character - when using useFetch. Same thing happens when using $fetch.

I've added the minimal repro link, which is literally just an API endpoint that returns a string with multiple pipe delimiters, and displays the result. You can see the server-side rendered version looks right, but when the page is hydrated client-side the value changes and the pipes are removed.

### Additional context

The environment I shared is where I first noticed the issue; the minimal repro environment is StackBlitz.

**Comment by danielroe** [comment]
this is now resolved upstream in unhead
