### ISSUE TITLE
Build for production cause a prerenderer error nuxt 3.7.0 

### ISSUE THREAD

**Issue by yromeroImed** [nuxt/nuxt#22894]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.15.0
- Nuxt Version:     3.7.0
- CLI Version:      3.7.2
- Nitro Version:    2.6.2
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      nitro, build, modules, colorMode, css, postcss, components, runtimeConfig, app, vite
- Runtime Modules:  @pinia/nuxt@0.4.1, @nuxt/content@2.8.0, @nuxtjs/color-mode@3.3.0, @pinia-plugin-persistedstate/nuxt@1.1.1
- Build Modules:    -
------------------------------

### Reproduction

To reproduce the error, simply run the yarn build command, which ultimately triggers the nuxi build command.

### Describe the bug

When nuxi begins building the application, it encounters an issue during the creation of files for the server folder. Specifically, when it attempts to prerender using Nitro, the following error occurs:

ERROR  RollupError: Could not resolve "../isValid/index.js" from "../isValid/index.js?commonjs-external"                            nitro 18:25:43

undefined

 ERROR  Could not resolve "../isValid/index.js" from "../isValid/index.js?commonjs-external"                                               18:25:43

  at error (node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
  at ModuleLoader.handleInvalidResolvedId (node_modules/rollup/dist/es/shared/node-entry.js:24778:24)
  at node_modules/rollup/dist/es/shared/node-entry.js:24740:26 

### Logs

```shell-script
ℹ Initializing prerenderer                                                                                                          nitro 18:25:16

 ERROR  RollupError: Could not resolve "../isValid/index.js" from "../isValid/index.js?commonjs-external"                            nitro 18:25:43


undefined


 ERROR  Could not resolve "../isValid/index.js" from "../isValid/index.js?commonjs-external"                                               18:25:43

  at error (node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
  at ModuleLoader.handleInvalidResolvedId (node_modules/rollup/dist/es/shared/node-entry.js:24778:24)
  at node_modules/rollup/dist/es/shared/node-entry.js:24740:26 



 ERROR  Could not resolve "../isValid/index.js" from "../isValid/index.js?commonjs-external"                                               18:25:43

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by yromeroImed** [comment]
For reproduction:

# Nuxt 3 Minimal Starter

Dependencies

```bash
"devDependencies": {
    "@babel/eslint-parser": "7.18.9",
    "@intlify/unplugin-vue-i18n": "0.7.0",
    "@nuxt/content": "^2.4.0",
    "@nuxt/image": "^1.0.0-rc.1",
    "@nuxt/postcss8": "1.1.3",
    "@nuxt/test-utils": "^3.0.0",
    "@nuxt/test-utils-edge": "3.0.0-rc.10-27708028.1ca294e",
    "@nuxt/types": "2.15.8",
    "@nuxtjs/color-mode": "^3.2.0",
    "@nuxtjs/eslint-config": "11.0.0",
    "@nuxtjs/eslint-config-typescript": "11.0.0",
    "@types/platform": "1.3.4",
    "@types/vue-select": "^3.16.2",
    "@typescript-eslint/eslint-plugin": "5.36.1",
    "@typescript-eslint/parser": "5.36.1",
    "@vitejs/plugin-vue": "3.0.3",
    "@vitest/ui": "0.23.1",
    "@vue/test-utils": "2.0.2",
    "autoprefixer": "10.4.8",
    "date-fns": "2.29.3",
    "eslint": "8.23.1",
    "eslint-config-prettier": "8.5.0",
    "eslint-plugin-prettier": "4.2.1",
    "eslint-plugin-vue": "9.4.0",
    "jsdom": "20.0.0",
    "nuxt": "^3.7.0",
    "postcss": "8.4.14",
    "prettier": "2.7.1",
    "sass": "^1.56.2",
    "sitemap": "^7.1.1",
    "tailwindcss": "3.1.7",
    "typescript": "4.8.2",
    "vite-plugin-eslint": "1.8.1",
    "vitest": "^0.28.1",
    "vue-i18n": "9.2.2"
  },
  "dependencies": {
    "@chenfengyuan/vue-countdown": "2",
    "@fortawesome/fontawesome-free": "6.2.0",
    "@fortawesome/fontawesome-svg-core": "6.2.0",
    "@fortawesome/free-brands-svg-icons": "6.2.0",
    "@fortawesome/free-regular-svg-icons": "6.2.0",
    "@fortawesome/free-solid-svg-icons": "6.2.0",
    "@fortawesome/vue-fontawesome": "3.0.1",
    "@headlessui/vue": "1.7.0",
    "@pinia-plugin-persistedstate/nuxt": "^1.1.1",
    "@pinia/nuxt": "0.4.1",
    "@twilio/rtc-diagnostics": "^1.0.1",
    "@vee-validate/rules": "4.6.7",
    "@vueform/slider": "^2.1.6",
    "@vuelidate/core": "^2.0.0",
    "@vuelidate/validators": "^2.0.0",
    "@vuepic/vue-datepicker": "3.5.3",
    "cookie": "0.5.0",
    "date-fns": "2.29.3",
    "esbuild": "^0.15.15",
    "js-cookie": "3.0.1",
    "pinia": "2.0.21",
    "platform": "1.3.6",
    "rut.js": "2.1.0",
    "twilio-video": "^2.27.0",
    "uuid": "^9.0.0",
    "vee-validate": "4.6.7",
    "vue-final-modal": "3.4.4",
    "vue-recaptcha-v3": "^2.0.1",
    "vue-select": "^4.0.0-beta.6",
    "vue-slider-component": "^3.2.24"
  }
```

## Setup

Make sure to install the dependencies:

```bash
# yarn
yarn install

## Production

Build the application for production:

```bash
yarn build
```

Locally preview production build:

```bash
yarn preview
```

**Comment by dargmuesli** [comment]
Is that really minimal? If you could share a link to stackblitz or codesandbox that would be great!

**Comment by VicFleur** [comment]
I'm also having this problem but I don't think it's strictly tied to Nuxt 3.7.0 as I'm now getting the same error when building with 3.6.5. Can't say for sure where the problem lies or why it popped up today but I discovered I can get successful builds by removing all the instances of ```import format from 'date-fns/format/index.js'``` I had in the code.

**Comment by JefferySJones** [comment]
I started having this issue as well. I was able to get past it by removing the `/index.js` from `import format from 'date-fns/format/index.js'`

but then near the end it still fails on this error (which also appears to be related to date-fns.

```
 ERROR  Could not resolve "./_lib/Setter.js" from "./_lib/Setter.js?commonjs-external"                                                                                      

  at error (node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
  at ModuleLoader.handleInvalidResolvedId (node_modules/rollup/dist/es/shared/node-entry.js:24778:24)
  at node_modules/rollup/dist/es/shared/node-entry.js:24740:26
  ```
![image](https://github.com/nuxt/nuxt/assets/14797002/7085517f-4378-4665-a04b-3e5c88294b36)

 It seems as though rollup is not respecting the relative paths from within date-fns? This wasn't a problem in Nuxt 3.6.1 which I'm trying to update from

**Comment by JefferySJones** [comment]
### Minimal Starter to reproduce the error above:

package.json
```json
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview"
  },
  "devDependencies": {
    "nuxt": "3.7.0"
  },
  "dependencies": {
    "date-fns": "2.30.0"
  }
}

```

nuxt.config.ts
```
export default defineNuxtConfig({});
```

app.vue
```
<script lang="ts" setup>
import format from 'date-fns/format/index.js';

const today = format(new Date(), 'MM/yyyy');
</script>
<template>
  <div>Hello I'm working!</div>
</template>
```

**Comment by JefferySJones** [comment]
> I'm also having this problem but I don't think it's strictly tied to Nuxt 3.7.0 as I'm now getting the same error when building with 3.6.5. Can't say for sure where the problem lies or why it popped up today but I discovered I can get successful builds by removing all the instances of `import format from 'date-fns/format/index.js'` I had in the code.

I think you're right, when I do a stackblitz I get the same issue on 3.6.1 where I was not getting this error there before.

**Comment by JefferySJones** [comment]
I was able to solve this issue for myself by changing all of my imports for date-fns to this style:
`import { format } from 'date-fns';`

It looks like it is tree-shaken properly too despite not using the import of the module itself, which my worry using this style of import was that it wouldn't be tree-shaken, so that's nice.

https://stackblitz.com/edit/nuxt-broken-datefns?file=package.json,app.vue,nuxt.config.ts,package-lock.json

**Comment by danielroe** [comment]
Let's track in https://github.com/unjs/nitro/issues/1889.
