### ISSUE TITLE
useAsyncData break pages if multiple navigation during page change

### ISSUE THREAD

**Issue by huang-julien** [nuxt/nuxt#22900]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.17.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-suvj1g?file=pages%2Fasyncdata.vue,pages%2Findex.vue,app.vue

- click 10 time within a second on the link
- don't get navigated and the page breaks
- open your console
- see an error

### Describe the bug

when clicking a lot of time on a link with a navigation to a page which requires a long asyncData, nuxt breaks with an vue error when navigating and mounting the new page

### Additional context

I think this issue can happens a lot on slow pages with users double/triple clicking on a nav link but not on pages that has a fast useAsyncData. It can also depend on the user network speed

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/13309.

**Comment by bombasticseahorse** [comment]
@danielroe This bug was introduced in **v3.6.2**. **v3.6.1** with the same Vue version (**v3.3.4**) doesn't have this bug. It looks like it's related to Nuxt.

**Comment by danielroe** [comment]
Yes, it did start then, but that's likely because we fixed an upstream bug, and began awaiting suspense resolution properly.

The root cause is upstream.

**Comment by agracia-foticos** [comment]
> Yes, it did start then, but that's likely because we fixed an upstream bug, and began awaiting suspense resolution properly.
> 
> The root cause is upstream, as far as I can tell.
> 
> We're currently investigating a possible solution in Vue itself.

Perfect!!!

**Comment by MarioC3** [comment]
Has someone found a workaround for this issue?

**Comment by agracia-foticos** [comment]
Same issue

**Comment by Josepdal** [comment]
Same here

**Comment by firsttarhan** [comment]
Same issue

**Comment by hendrikheil** [comment]
Can you try disabling transitions?

You can see how to do that here:
https://nuxt.com/docs/getting-started/transitions#disable-transitions

This is possibly fixed by https://github.com/vuejs/core/pull/9309, but disabling the transitions should lead to the same result.

**Comment by Josepdal** [comment]
> Can you try disabling transitions?
> 
> You can see how to do that here: https://nuxt.com/docs/getting-started/transitions#disable-transitions
> 
> This is possibly fixed by [vuejs/core#9309](https://github.com/vuejs/core/pull/9309), but disabling the transitions should lead to the same result.

Hello, I have tried but got the same result.

In my case I am using <slot /> inside the layout to load pages.
https://nuxt.com/docs/migration/pages-and-layouts

Thanks!

**Comment by tolgahanbeyazoglu** [comment]
@Josepdal  It doesn't matter if usefetch or useasyncdata, the problem will be solved if the lazy feature is used. Do you know this?

**Comment by Josepdal** [comment]
> @Josepdal It doesn't matter if usefetch or useasyncdata, the problem will be solved if the lazy feature is used. Do you know this?

Yes thanks, but I don't want to handle a pending state. I prefer getting the data before hydration.

**Comment by tolgahanbeyazoglu** [comment]
> > @Josepdal It doesn't matter if usefetch or useasyncdata, the problem will be solved if the lazy feature is used. Do you know this?
> 
> Yes thanks, but I don't want to handle a pending state. I prefer getting the data before hydration.

I have the same problem and I couldn't find a solution.

**Comment by NtchPlayer** [comment]
Running into same error here o/ I could event reproduce it on https://nuxt.com if you navigate to fast on showcase or blog page from the navbar (-> be sure to don't have cachedData, you can downgrade you connexion with your browser to handle the error more simply).

**Comment by rylanharper** [comment]
This is still a major issue even with the latest release of Vue core `^3.3.10`. Is this on the pipeline to be addressed?

**Comment by tolgahanbeyazoglu** [comment]
@rylanharper The problem continues in vue 3.3.10, I did the tests.

**Comment by gogoend** [comment]
I'm trying to explore the commits between v2.6.1 and v2.6.2 and find that since [this commit](https://github.com/nuxt/nuxt/commit/d0dde6426fe6ae58ec1ea94e47c66f6e0e2a4d63), this bug started appearing.

**Comment by zzzhim** [comment]
I have the same problem, hope it can be fixed soon

**Comment by danielroe** [comment]
this is now resolved in vue v3.4. 🥳
