### ISSUE TITLE
onUnmounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.

### ISSUE THREAD

**Issue by nazar1ua** [nuxt/nuxt#22919]
I have this issue in the latest version of Nuxt

_Originally posted by @nazar1ua in https://github.com/nuxt/nuxt/issues/14489#issuecomment-1699639648_
            
@danielroe this is issue about what I told yesterday.
For reproduction you can clone [@greenrute/frontend](https://github.com/greenrute/frontend) and in .env GSI_KEY leave empty, and as API use https://api.greenrute.com/v1. Then register by email, complete all steps, and then open console at `/dashboard`.

As I can see, this issue is related to v-show, v-if, etc. Replace `v-show` with `v-if` in `pages/dashboard` on line 36, and see than is warnings there are no more <Button> trigger

**Comment by umairrafiq1133** [comment]
Its happening for us as well. Ever since we update to 3.7.0, Whenever some routing happens, It fill the console with warnings.

**Comment by danielroe** [comment]
It might be caused by multiple versions of vue in your project, but really it would be most helpful if we could look at a reproduction.

**Comment by nazar1ua** [comment]
@danielroe I'm not sure I will be able to provide more minimal reproduction, because I don't know exactly what causes this.

**Comment by nazar1ua** [comment]
Another interesting fact: I don't get these warnings in Safari

**Comment by umairrafiq1133** [comment]
@danielroe I am able to create a minimal reproduction of the issue.
Here's the link to repository.
https://github.com/umairrafiq1133/nuxt-issue

**Comment by umairrafiq1133** [comment]
Ok. I am able to reach to a conclusion, its happening because of useCookie.

```
const getLangCode = (): string => {
  const lang = useCookie<Language>("current_lang");
  return lang.value?.code ?? "sv";
};
```

Warnings are only there when I run this function while rendering the page.

**Comment by danielroe** [comment]
Good debugging. Yes, you should not call `useCookie` within that function. It's a composable, which means it's meant to be run in your setup function, and then used inside the function, like this:

```ts
const lang = useCookie<Language>("current_lang");
const getLangCode = (): string => {
  return lang.value?.code ?? "sv";
};
```

If you want to wrap it in a composable, do something like this:

```ts
export const useLangCode = () => {
  const lang = useCookie<Language>("current_lang");
  return {
    getLangCode: () => lang.value?.code ?? "sv"
  }
})
// in script setup somewhere
const { getLangCode } = useLangCode()
// then elsewhere, afterwards
const lang = getLangCode()
```
