### ISSUE TITLE
Use <NuxtLink> to jump errors

### ISSUE THREAD

**Issue by hixb** [nuxt/nuxt#22916]
### Environment

- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.7.0
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-uvphmq

### Describe the bug

Add a top-level asynchronous request to the home page. When jumping back to the home page from the **/about** page, I clicked the **go home** link twice. A white screen appeared on the page and the following error appeared on the console:

**Uncaught (in promise) TypeError: Cannot read properties of null (reading 'parentNode')**
and
**Uncaught (in promise) TypeError: Cannot read properties of null (reading 'subTree')**

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/13309.
