### ISSUE TITLE
useFetch: repeat request

### ISSUE THREAD

**Issue by XioDone** [nuxt/nuxt#22917]
### Environment

nuxt@3.7.0

### Reproduction

[playground](https://stackblitz.com/edit/nuxt-starter-cxgv9u?file=app.vue)

https://github.com/nuxt/nuxt/assets/82227884/360cf714-1d76-47b7-90d0-4432b62f7c51

### Describe the bug

Each call will accumulate the number of requests.

```vue

<script setup>
const data = reactive({
  foo: {},
});

const onSubmit = () => {
  data.foo = {};

  useFetch('https://api.test.com/test', {
    method: 'POST',
    body: { data },
  });
};
</script>

<template>
  <div>
    <button @click="onSubmit">Btn</button>
  </div>
</template>


```

**Comment by or2e** [comment]
Possibly related https://github.com/nuxt/nuxt/issues/22527

**Comment by manniL** [comment]
This is intended as `useFetch` will watch reactive parts automatically. Use `$fetch` instead. ☺️
