### ISSUE TITLE
moment-business-days npm does not support nuxt3. It shows below error

### ISSUE THREAD

**Issue by vinothkbest** [nuxt/nuxt#22926]
### Describe the feature

1. npm "moment-business-days" is the dependency of consumed dependency in my web app. 
2. Error:
nuxt.js?v=4d7b8031:96 [nuxt] error caught during app initialization TypeError: Cannot set properties of undefined (setting 'isHoliday')
    at node_modules/moment-business-days/index.js (index.js:7:11)
    at __require2 (chunk-6NOISVLF.js?v=4d7b8031:16:50)
    at index.js:248:1
3. When used below snippet at nuxt.config.ts; dev works fine but build output throws similar error.
optimizeDeps:{      
      exclude: ['moment-business-days'],
      esbuildOptions:{
        plugins:[
          esbuildCommonjs(['moment-business-days'])
        ]
      }
    },

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by vinothkbest** [comment]
usage code in plugins directory as client:

export default defineNuxtPlugin(async () => {
    await import('moment-business-days').then(response => console.log(response))
})

**Comment by danielroe** [comment]
Yes, I think configuring `vite.optimizeDeps` is likely the solution here. See more at https://vitejs.dev/config/dep-optimization-options.html#optimizedeps-include. You can use `$development.vite.optimizeDeps` options to configure just the dev server.

**Comment by vinothkbest** [comment]
Thanks for response. I used as below. It works in npm run dev. But npm run build not works
$development: {
    vite: {
      optimizeDeps:{      
        esbuildOptions:{
          plugins:[
            esbuildCommonjs(['moment-business-days'])
          ]
        }
      },
    }
  }

**Comment by vinothkbest** [comment]
![image](https://github.com/nuxt/nuxt/assets/56819946/66795e89-fffb-4e96-a503-c207eedf3478)
