### ISSUE TITLE
Unable to extend layers from private Bitbucket repository

### ISSUE THREAD

**Issue by Jactami** [nuxt/nuxt#22928]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.15.0
- Nuxt Version:     3.7.0
- CLI Version:      3.7.2
- Nitro Version:    2.6.2
- Package Manager:  npm@9.8.1
- Builder:          -
- User Config:      extends, devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

1. Setup a private Bitbucket repository
2. Initialize a new Nuxt project
3. Try to extend from the Bitbucket repository (see code below)
4. Nuxt is unable to fetch the remote repository

### Describe the bug

The concept of Nuxt Layers seems very promising. So I decided to establish Layers in my company as  way to share common components between various Nuxt projects. We generally store our code on Bitbucket. So I made a private Bitbucket repository for our shared code basis. However Nuxt is unable to fetch from this repository.

My setup:

- _.env_ file:
  `GIGET_AUTH=XXXXXXXXXXXXXXXXXXXXXXX`

- _nuxt.config.ts_:
 ```ts
export default defineNuxtConfig({
  extends: [
    'bitbucket:user_name/project_name#branch', 
  ],
  // ...
})
```

Internally `unjs/giget` converts this to `https://bitbucket.org/user_name/project_name/get/branch.tar.gz`. However in my opinion something like `https://api.bitbucket.org/2.0/repositories/user_name/project_name/src/branch/` would be more correct. I found a similar issue regarding [private github repositories](https://github.com/unjs/giget/pull/93#issue-1653853707) which is not released yet.

Is this  bug by Nuxt (/giget) or am I doing something wrong? Any help is much appreciated.

**Comment by danielroe** [comment]
It sounds like this would need to be fixed upstream in `giget`. Would you raise an issue there instead?
