### ISSUE TITLE
Confusing message about a Hydration text content mismatch

### ISSUE THREAD

**Issue by hidekatsu-izuno** [nuxt/nuxt#22931]
### Environment

- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.7.0
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-z1urrw?file=app.vue

### Describe the bug

If a hydoration text content mismatch occurs, a warning message is displayed on browser console.
However a client value and a server value are swapped.

For example:
```javascript
const x = ref(0);

if (process.client) {
  x.value = 1;
}
```

Displayed message:
```
vue.js:1449 [Vue warn]: Hydration text content mismatch in <div>:
- Client: 0
- Server: 1 
  at <App key=3 > 
  at <NuxtRoot>
```

**Comment by danielroe** [comment]
thanks! should be resolved when https://github.com/vuejs/core/pull/9089 merges.
