### ISSUE TITLE
Developing nux3 using @ nuxtjs/i18n is normal, but running i18n after packaging fails

### ISSUE THREAD

**Issue by S27149** [nuxt/nuxt#22938]
### Environment

- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.7.0
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  pnpm@8.6.5
- Builder:          -
- User Config:      i18n, robots, modules, app, css, devtools, devServer, nitro
- Runtime Modules:  nuxt-swiper@1.2.2, @nuxtjs/i18n@8.0.0-rc.3, @nuxtjs/tailwindcss@6.8.0, @element-plus/nuxt@1.0.5, @pinia/nuxt@0.4.11, nuxt-svgo@3.5.0, @nuxtjs/robots@3.0.0
- Build Modules:    -

### Reproduction

Download the latest version of nuxt and the latest version of @ nuxtjs/i18n, and then package them to encounter corresponding issues

### Describe the bug

I downloaded the latest version of Nuxt, and then downloaded the latest version of @ nuxtjs/i18n. Everything was normal during development, and then I packaged it and ran i18n again, but it failed again. Why do I suspect it's a problem with the new version of Nuxt? Because that project was previously packaged in 3.6.5 and everything was normal, including i18n, I updated the nuxt version to the latest version and it became invalid. Later, I rolled back the old version of nuxt and it was no longer useful.

**Comment by S27149** [comment]
This is my GittHub Project：https://github.com/S27149/nuxt3-app.git

**Comment by S27149** [comment]
Please clone and install the dependencies, run the development environment, and then build the project. If you use the preview command to preview, an error will occur

**Comment by gavin667** [comment]
Just commenting to say I'm also having the same problem. Dev fine, production build is missing translation key values after upgrading to 3.7.0 from 3.6.5. The build does succeed though, just without the keys.

Looking at the yarn.lock after upgrading via `nuxi upgrade` I can't see any specific @nuxt/i18n dependencies being upgraded either.

The only change I made between things working fully and not working fully was running `nuxi upgrade`. The deployment was made on Vercel.

**Comment by gavin667** [comment]
...and just to follow up bumping `@nuxt/i18n` to the latest RC (v8.0.0-rc.4) fixed my issue.

Lesson = directly check that you're up to date with dependencies before commenting.

See - https://nuxt.com/modules/i18n/changelog
