### ISSUE TITLE
Nuxt 3.7.0 - input text color is white

### ISSUE THREAD

**Issue by devonik** [nuxt/nuxt#22944]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.12.1
- Nuxt Version:     3.6.2
- Nitro Version:    2.6.2
- Package Manager:  pnpm@8.6.0
- Builder:          vite
- User Config:      sourcemap, runtimeConfig, typescript, css, build, vite, nitro, routeRules, modules, i18n, intercom, webVitals, gtm, devtools
- Runtime Modules:  @nuxt/image@1.0.0-rc.1, unplugin-icons/nuxt, nuxt-3-intercom@1.0.8, @nuxtjs/fontaine@0.4.1, @nuxtjs/web-vitals@0.2.6, @vueuse/nuxt@10.2.1, nuxt-vuetify-nested-containment@0.0.4, @zadigetvoltaire/nuxt-gtm@0.0.13, nuxt-vuetify-error-handler@1.1.0, (), @pinia/nuxt@0.4.11, nuxt-i18n-data@0.1.22, @nuxtjs/i18n@8.0.0-beta.12
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-wudebh?file=app.vue,plugins%2Fvuetify.ts,nuxt.config.ts,package.json

### Describe the bug

Since I updated to nuxt 3.7.0 the text color in every input is white. It's may a combination with vuetify but even when I rollback vuetify to 3.3.8 the input color is still white.

I rolled back nuxt to 3.6.2 and vuetify to 3.3.8 and the input color is black again

**Comment by devonik** [comment]
open reproduction as new tab works and direct click not ? weird behaviour

**Comment by danielroe** [comment]
Not 100% convinced this is a Nuxt bug. Initially I thought this was related to [this regression](https://github.com/unjs/website/pull/96#discussion_r1312789972).

However, when inspecting styles I see that vuetify is just setting `color: inherit` for these elements.

When I downgrade to Nuxt 3.6.2 this is still reproducible. So I do not believe it is a Nuxt issue.

**Comment by devonik** [comment]
Oh yes you're right it seems to be a change within vuetify 3.3.8 to 3.3.15. Thanks and sorry for the mislead
