### ISSUE TITLE
useFetch header case sensitivity results in duplicate 'accept' headers during SSR

### ISSUE THREAD

**Issue by tberk** [nuxt/nuxt#22949]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.17.1
- Nuxt Version:     3.6.5
- Nitro Version:    2.6.2
- Package Manager:  pnpm@8.5.0
- Builder:          vite
- User Config:      typescript, modules, imports, runtimeConfig, app, colorMode, eslint, auth
- Runtime Modules:  @sidebase/nuxt-auth@0.6.0-beta.5, @nuxtjs/tailwindcss@6.8.0, @nuxtjs/color-mode@3.3.0, @vueuse/nuxt@10.4.1, @pinia/nuxt@0.4.11, @pinia-plugin-persistedstate/nuxt@1.1.1, nuxt-swiper@1.2.2, @nuxtjs/eslint-module@4.1.0, nuxt-icon@0.5.0
- Build Modules:    -
------------------------------

### Reproduction

- Use the useFetch helper in a Nuxt component or page:

```javascript
useFetch('url', {
  Accept: 'application/json',
});
```

- Observe the request headers in SSR mode. You'll see:
```
accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
Accept: 'application/json'
```

- Now, modify the header name to lowercase:
```javascript
useFetch('url', {
  accept: 'application/json',
});
```

- Observe the request headers again in SSR mode. Now, it shows the intended behavior:
```
accept: 'application/json',
```

### Describe the bug

When using the useFetch helper with the Accept header set to 'application/json', I've noticed a discrepancy in behavior between SPA and SSR modes. Specifically, in SSR mode, if the header name is capitalized as Accept, it results in two separate 'accept' headers. However, using an all-lowercase accept generates the expected behavior.

### Additional context

Expected Behavior:
Regardless of the capitalization of the header name, the useFetch helper should use the provided header value consistently in both SPA and SSR modes.

Actual Behavior:
In SSR mode, capitalizing the header name results in duplicate headers, which can lead to unexpected behaviors.

**Comment by manniL** [comment]
I cannot reproduce this anymore ☺️

[Reproduction stackblitz](https://stackblitz.com/edit/nuxt-issues-22949).

**Comment by tberk** [comment]
Great to know, in case this issue arises again, I'll ensure to include the reproduction.
