### ISSUE TITLE
h3 setCookie method doesn't set cookies while published on microsoft azure static web app

### ISSUE THREAD

**Issue by Gaiozz** [nuxt/nuxt#22951]
### Environment

Microsoft azure static web app
Node Version:     v18.16.1
Nuxt Version:     3.7.0
CLI Version:      3.7.2
Nitro Version:    2.6.2
Package Manager:  npm@9.5.1

### Reproduction

https://stackblitz.com/edit/github-vbzu4s?file=server%2Ftsconfig.json

### Describe the bug

When deployed to azure static web app, h3 setCookie method won’t set cookies. It works fine on localhost. It was working with nuxt 3.2.0 version

**Comment by sig9** [comment]
Wonderful, I was coincidently trying to browse dev server on a tailscale IP and I noticed that my session cookie was not being set. I was fiddling with cookie options to set secure = false if in development.
Then noticed that the deployed site was also having issues setting cookies. Happy to have found the root cause here.

**Comment by sig9** [comment]
I returned event.node.res.getHeaders() value from a post to an api route which calls setCookie
Looks like the cookie is there in the outbound headers. However, in the browser, cookie is missing. 

    "sessionCookie": "snipped",
    "sessionCookieOptions": {
        "maxAge": 172800000,
        "httpOnly": true,
        "secure": false
    },
    "headers": {
        "cross-origin-resource-policy": "same-origin",
        "cross-origin-opener-policy": "same-origin",
        "cross-origin-embedder-policy": "require-corp",
        "content-security-policy": "base-uri 'self'; font-src 'self' https: data:; form-action 'self'; frame-ancestors 'self'; img-src 'self' data:; object-src 'none'; script-src-attr 'none'; style-src 'self' https: 'unsafe-inline'; upgrade-insecure-requests",
        "origin-agent-cluster": "?1",
        "referrer-policy": "no-referrer",
        "strict-transport-security": "max-age=15552000; includeSubDomains",
        "x-content-type-options": "nosniff",
        "x-dns-prefetch-control": "off",
        "x-download-options": "noopen",
        "x-frame-options": "SAMEORIGIN",
        "x-permitted-cross-domain-policies": "none",
        "x-xss-protection": "0",
        "permissions-policy": "camera=(), display-capture=(), fullscreen=(), geolocation=(), microphone=()",
        "access-control-allow-origin": "http://localhost:3000",
        "vary": "origin",
        "set-cookie": [
            "session=sniped; Max-Age=172800000; Path=/; HttpOnly"
        ]
        
Older Build return cookie to browser. 
session=snipped; max-age=432000000; domain=prsubdomain.azurestaticapps.net; path=/; secure; httponly        

note: tried also to drop the secure and httponly flags, neither changed the outcome. dropping set-cookie header somewhere.

**Comment by sig9** [comment]
yikes: https://github.com/Azure/static-web-apps/issues/760

**Comment by danielroe** [comment]
This is likely an upstream nitro issue rather than a Nuxt one. Would you raise an issue there with a minimal nitro reproduction? 🙏 

cc: @pi0

**Comment by pi0** [comment]
(i might forget this, please ping me once an issue created in Nitro with minimal reproduction 🙏🏼  -- if too hard, please feel free to open a discussion there)
