### ISSUE TITLE
nuxt3设置keepalive:true后路由跳转报错

### ISSUE THREAD

**Issue by incloudZhang** [nuxt/nuxt#22959]
### Environment

dev

### Reproduction

none

### Describe the bug

页面使用<NuxtLayout>后在设置 keepalive: true，路由从别处跳转过来报错,在layout中能够正常跳转，非layout组件跳转过来报错
TypeError: Cannot read properties of null (reading 'insertBefore')

### Additional context

<img width="575" alt="WeChat26d774ce2a549537517b76b333bc53de" src="https://github.com/nuxt/nuxt/assets/48787313/d51c4464-8d4d-4b47-b77c-2290ce2e5c26">

**Comment by lukangkang** [comment]
I have the same problem
