### ISSUE TITLE
Update unhead minimum version

### ISSUE THREAD

**Issue by korgan00** [nuxt/nuxt#22950]
### Environment

Nuxt project info:                                                                                                                                                                                      17:32:00

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.7.0
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      app, ssr
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-vbzu4s?file=nuxt.config.ts

### Describe the bug

If the project currently has an older version of unhead (like 1.3.9), the template heading doesn't work well with the separator.
In the reproduction environment, the title should be "My site name" and it is "| My site name".
With the latest version of unhead (1.4.1) it works well.

**Comment by danielroe** [comment]
this should be implemented
