### ISSUE TITLE
node-server.mjs breaks when using iisnode due to named pipe

### ISSUE THREAD

**Issue by tidan-16** [nuxt/nuxt#22961]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.17.1
- Nuxt Version:     3.6.5
- Nitro Version:    2.6.2
- Package Manager:  npm@9.6.7
- Builder:          vite
- User Config:      css, modules, imports, build, vite, pwa, pinia, i18n, gtag
- Runtime Modules:  nuxt-simple-robots@3.1.2, @vueuse/nuxt@10.4.1, @nuxtjs/i18n@8.0.0-beta.12, @vite-pwa/nuxt@0.1.0, @nuxtjs/device@3.1.0, @pinia/nuxt@0.4.11, @pinia-plugin-persistedstate/nuxt@1.1.1, nuxt-gtag@0.6.2, (), @nuxtjs/google-adsense@2.1.0
- Build Modules:    -
------------------------------

### Reproduction

Build the default nuxt 3, deploy it to any provider using iisnode.

### Describe the bug

When deploying the application to iisnode (windows), an error appends due to named Pipes:

![image](https://github.com/nuxt/nuxt/assets/83239949/8c80e69e-9a60-42cc-99fb-6e09388bc790)

I was able to change this line inside the ".output/server/chunks/nitro/node-server.mjs" from this (Please check line 7794) :

![image](https://github.com/nuxt/nuxt/assets/83239949/3fbc9dee-cd71-400b-93a2-a5a5104d0111)

To this (Please check line 7794):

![image](https://github.com/nuxt/nuxt/assets/83239949/5fb221b5-28fd-4d03-8de4-9fa941691690)

That simple fix seems to resolve all the issues for the IISNode named pipe errors.

Let me know where to change this line of code inside this repository for me being able to create the pull request.

### Additional context

I am using nuxt 3 in ssr mode.

I am using the default preset when deploying my application.

**Comment by danielroe** [comment]
cc: @pi0

**Comment by tidan-16** [comment]
I just have 2 questions:

1- Should I make an issue in the nitro github instead of in here?
2- Can I simply create a branch in the nitro repo then create a pull request or I need to fork the nitro repo in my account first? Sorry if its a noob question, im new to open source things

**Comment by pi0** [comment]
@tidan-16 Feel free to directly draft a PR in nitro and cross reference to this issue 👍🏼

**Comment by tidan-16** [comment]
Please review when you will have time :)

**Comment by danielroe** [comment]
Thank you ❤️

**Comment by tidan-16** [comment]
I might saying that too quick, but I think it is going to fix the issue when using the iis node preset too

**Comment by tidan-16** [comment]
Is there a problem with my pull request? maybe something I forgot to take into consideration that breaks up something else?

**Comment by tolgahanbeyazoglu** [comment]
The problem still persists on my IIS servers. need help @pi0 

Operating System: Windows
Node Version: v21.5.0
Nuxt Version: 3.8.1
Nitro Version: 2.8.1

**Comment by tidan-16** [comment]
My fix is working tho but did not get merged

**Comment by manniL** [comment]
@tidan-16 Can you confirm that [@pi0's fix](https://github.com/unjs/nitro/pull/1783) (similar) doesn't work for you?

**Comment by tidan-16** [comment]
Does not work with your fix, mine is still working in production

**Comment by tolgahanbeyazoglu** [comment]
3.8.1 and nitro 2.8.1 the following is not working


`export default defineNitroPlugin((nitroApp) => { process.env.NITRO_UNIX_SOCKET = process.env.PORT })

  nitro: { plugins: ["~/nitroPlugins/unixsocket.ts"], },`

**Comment by tidan-16** [comment]
Check my fix,

https://github.com/unjs/nitro/pull/1697/files

**Comment by tolgahanbeyazoglu** [comment]
what should I do?

**Comment by tidan-16** [comment]
Check the « describe bug » in the description of this issue, it is saying the fix

**Comment by manniL** [comment]
@tidan-16 I've proposed another PR with a solution close to yours but only applying to iis node 👍🏻

**Comment by tidan-16** [comment]
@manniL, thank you, im currently in vacation but ill let you know if it works properly around january 3rd. Meanwhile maybe someone could test before that time to see if it works properly under iis (I believe nuxt’s team does not have iis to test it)

**Comment by tolgahanbeyazoglu** [comment]
@tidan-16 The edit you specified does not work Should we run the file in index.js instead of here?
![555](https://github.com/nuxt/nuxt/assets/129540736/4f990e2e-00f9-4c85-a019-d70339e9ea79)

2-I created index.js on the server and put the codes there, it worked. Is this the correct method? if i guess node modules are not giving any output

![3333](https://github.com/nuxt/nuxt/assets/129540736/7cab5ae7-9ef6-4614-b21e-02a52f7c424d)

**Comment by manniL** [comment]
@tidan-16 No no, I know that Pooya has a test setup for it :) Issue was simply that the backslashes were not escaped. This was fixed via https://github.com/unjs/nitro/pull/2020 though.
