### ISSUE TITLE
docs: types in the Server Utilities example not working

### ISSUE THREAD

**Issue by OrlS15** [nuxt/nuxt#22967]
### Describe the feature

From docs (https://nuxt.com/docs/guide/directory-structure/server#server-utilities):
```ts
import type { EventHandler } from 'h3'

export const defineWrappedResponseHandler = (handler: EventHandler) =>
  defineEventHandler(async (event) => {
    try {
      // do something before the route handler
      const response = await handler(event)
      // do something after the route handler
      return { response }
    } catch (err) {
      // Error handling
      return { err }
    }
  })
```
Fetching an endpoint with $fetch or useFetch returns wrong type
```ts
let a = await $fetch("/api/wrappedEndpoint")
//  let a: Simplify<SerializeObject<{
//     response: any;
//     err?: undefined;
//} > | SerializeObject<{
//     err: unknown;
//     response?: undefined;
// }>>
```
So the editor doesn't give you suggestions when you write a.something

What about replacing it with something like this:
```ts
export const defineWrappedResponseHandler = <T extends EventHandlerRequest, D>(
  handler: EventHandler<T, D>
) =>
  defineEventHandler(async event => {
    try {
      // do something before the route handler
      const response = await handler(event)
      // do something after the route handler
      return { response }
    } catch (err) {
      // Error handling
      return { err }
    }
  })
```
Or at least add it below!

### Additional information

- [x] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by madebyfabian** [comment]
Also experienced this!  

Reprod: https://github.com/madebyfabian/nuxt-server-utils-types-reprod (Stackblitz doesn't work because of no Type Hints/Volar)

**Comment by danielroe** [comment]
That would be great change - thank you ❤️

**Comment by awdr74100** [comment]
@OrlS15 @danielroe Has this issue been resolved so far?

~/server/utils/handler.ts
```ts
import type { EventHandler, EventHandlerRequest } from 'h3';

export const defineWrappedResponseHandler = <T extends EventHandlerRequest, D>(
  handler: EventHandler<T, D>,
): EventHandler<T, D> =>
  defineEventHandler<T>(async (event) => {
    try {
      // do something before the route handler
      const response = await handler(event);
      // do something after the route handler
      return { response };
    } catch (err) {
      // Error handling
      return { err };
    }
  });
```

~/server/routes/api/auth/signup.post.ts
```ts
export default defineWrappedResponseHandler(async (event) => {
  return { message: 'awesome!' };
});
```

~/pages/index.vue
```vue
<script setup lang="ts">
const signup = async () => {
  const data = await $fetch('/api/auth/signup', { method: 'POST' }); //  type data = { message: string }
};
</script>
```

Shouldn't the type be `type data = { response: { message: string }}`? or am I understanding it wrong? 

Thank you all for your help!

**Comment by OrlS15** [comment]
> @OrlS15 @danielroe Has this issue been resolved so far?
> 
> ~/server/utils/handler.ts
> 
> ```ts
> import type { EventHandler, EventHandlerRequest } from 'h3';
> 
> export const defineWrappedResponseHandler = <T extends EventHandlerRequest, D>(
>   handler: EventHandler<T, D>,
> ): EventHandler<T, D> =>
>   defineEventHandler<T>(async (event) => {
>     try {
>       // do something before the route handler
>       const response = await handler(event);
>       // do something after the route handler
>       return { response };
>     } catch (err) {
>       // Error handling
>       return { err };
>     }
>   });
> ```
> 
> ~/server/routes/api/auth/signup.post.ts
> 
> ```ts
> export default defineWrappedResponseHandler(async (event) => {
>   return { message: 'awesome!' };
> });
> ```
> 
> ~/pages/index.vue
> 
> ```
> <script setup lang="ts">
> const signup = async () => {
>   const data = await $fetch('/api/auth/signup', { method: 'POST' }); //  type data = { message: string }
> };
> </script>
> ```
> 
> Shouldn't the type be `type data = { response: { message: string }}`? or am I understanding it wrong?
> 
> Thank you all for your help!

Try this:
```ts
import type { EventHandler, EventHandlerRequest } from 'h3';

export const defineWrappedResponseHandler = <T extends EventHandlerRequest, D>(
  handler: EventHandler<T, D>,
): EventHandler<T, D> =>
  defineEventHandler<T>(async (event) => {
    try {
      // do something before the route handler
      const response = await handler(event);
      // do something after the route handler
      return response;
    } catch (err) {
      // Error handling
      return { err };
    }
  });
  ```
