### ISSUE TITLE
Nuxt3.6.5 - Failed to resolve import ".nuxt/components" | Using a component in the template while also importing its type in the Composition API leads to an error.

### ISSUE THREAD

**Issue by sefacndmr01** [nuxt/nuxt#22979]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.17.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@9.6.7
- Builder:          vite
- User Config:      app, vite, build, modules, css, runtimeConfig, plugins, googleFonts, devtools
- Runtime Modules:  @pinia/nuxt@0.4.11, @pinia-plugin-persistedstate/nuxt@1.1.1, @nuxtjs/google-fonts@3.0.2, nuxt-icon@0.5.0
- Build Modules:    -
------------------------------

### Reproduction

[Reproduction](https://stackblitz.com/edit/github-egvwuo-q53rtw?file=README.md)

### Describe the bug

Using a component in the template while also importing its type in the Composition API leads to an error.

### Additional context

In reproduction you can delete comment tags in **bug.vue** page to see error. I don't encounter this error when i don't call the component within the template. You can see it on the **weird.vue** page or in the **bug.vue** page with a comment.

I don't encounter this issue in a project where I'm using version ^3.6.2.

### Logs

```shell-script
Internal server error: Failed to resolve import ".nuxt/components" from "pages\course\index.vue". Does the file exist?                                                       05:38:47  
  Plugin: vite:import-analysis
  File: *path*/pages/course/index.vue:8:32
  2  |  import { ref } from 'vue';
  3  |  import { defineComponent as _defineComponent } from "vue";
  4  |  import { ModalsClassroom } from ".nuxt/components";
     |                                   ^
  5  |  const _sfc_main = /* @__PURE__ */ _defineComponent({
  6  |    __name: "index",
```

**Comment by danielroe** [comment]
You should not import from `.nuxt/components`. (Or in fact, ever from `.nuxt`. This is an internal directory.) Instead you can import from `#components`.
