### ISSUE TITLE
Can't extend children routes

### ISSUE THREAD

**Issue by silencerspirit** [nuxt/nuxt#22984]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v16.20.0
- Nuxt Version:     3.7.0
- CLI Version:      3.7.2
- Nitro Version:    2.6.2
- Package Manager:  pnpm@8.6.5
- Builder:          -
- User Config:      components, typescript, runtimeConfig, modules, htmlValidator, vite, css, app, tailwindcss, nitro, hooks, experimental
- Runtime Modules:  @pinia/nuxt@0.4.11, @nuxtjs/tailwindcss@6.8.0, @nuxtjs/html-validator@1.5.2
- Build Modules:    -
------------------------------

### Reproduction

Reproduction with `pages:extend`
https://stackblitz.com/edit/nuxt-starter-zkywrm?file=nuxt.config.ts
Reproduction with `module`
https://stackblitz.com/edit/nuxt-starter-3bxtzr?file=modules%2Fpages.ts

### Describe the bug

I can't add additional routes inside the children option, the router takes the file that is specified in the top level.

Example: 
`nuxt.config.ts`
```Typescript
'pages:extend'(_pages) {
      _pages.push(
        ...[
          {
            name: 'main-page',
            path: '/',
            file: '@/additional/index.vue',
          },
          {
            name: 'contacts-page',
            path: '/contacts',
            file: '@/additional/contacts/index.vue',
            children: [
              {
                name: 'contacts-child-page',
                path: ':id',
                file: '@/additional/contacts/child.vue', // not-work :(
              },
            ],
          },
        ]
      );
    },
```

**Comment by danielroe** [comment]
You need to have `<NuxtPage />` within a nested page's parent, where you want to render the child page. With that change, your code works as you expect.

You can also do what you're trying without adding any custom hook by moving `~/pages/contacts/index.vue` to `~/pages/contacts.vue`. That way Nuxt knows it's meant to be a parent and not just render the `/contacts` route. (You will still need to add `<NuxtPage />` within the parent page.)

See more at https://nuxt.com/docs/guide/directory-structure/pages/#nested-routes.

**Comment by silencerspirit** [comment]
@danielroe much thx, half day wasted on it)

**Comment by danielroe** [comment]
you're very welcome 😊
