### ISSUE TITLE
Nuxt generates incorrect types when use `pick` with `transform`

### ISSUE THREAD

**Issue by enkot** [nuxt/nuxt#22981]
### Environment

- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.7.0
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-udceba?file=app.vue

### Describe the bug

If we change/add another field (`bar`) in the `transform` callback and then `pick` it - Nuxt will show us TS error (`nuxi typecheck`) but works correctly in runtime:
```sh
Type '"bar"' is not assignable to type '"id" | "foo"'.
``` 

Expected:
- correct types when use `pick` and `transform` together
- do not allow to use `pick` and `transform` together

**Comment by danielroe** [comment]
I would expect that only pick or transform are used - not both. Perhaps we could document this, or update types to disallow.

**Comment by noppytinto** [comment]
@danielroe I've opened a [PR](https://github.com/nuxt/nuxt/pull/26042) to improve documentation about `pick` and `transform`. Hope will be useful!

**Comment by noppytinto** [comment]
@danielroe opened another [PR](https://github.com/nuxt/nuxt/pull/26043) since I've messed up things in the previous PR 🙄
