### ISSUE TITLE
increased render blocking queue from nuxt 3.6.5 to 3.7

### ISSUE THREAD

**Issue by jpengelbrecht** [nuxt/nuxt#22995]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.10.0
- Nuxt Version:     3.7.0
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  npm@8.19.2
- Builder:          -
- User Config:      modules, site, sitemap, robots, ogImage, linkChecker, head, routeRules, extends, typescript, sourcemap, devServer, htmlValidator, image, runtimeConfig, schemaOrg, nitro, appConfig, ignore, hooks, css, vite
- Runtime Modules:  @pinia/nuxt@0.4.11, @nuxt/content@2.7.2, @nuxt/image-edge@1.0.0-rc.1-28164352.ad7c010, @vueuse/motion/nuxt@2.0.0, nuxt-calendly@0.1.14
- Build Modules:    -
------------------------------

### Reproduction

install nuxt 3.7 and compared render blocked resources to 3.6.5

### Describe the bug

So this is not technically a bug and sorry if this is the wrong place to report this.  

I noticed that TBT went up on the new nuxt version.   This seems to be the case because the new version is adding quite a lot of components as render blocking resources, where previously these same resources where non blocking resources
![image](https://github.com/nuxt/nuxt/assets/93583336/5b443001-0627-4e6e-bd52-4afc7e127f09)

**Comment by eitelkrauss** [comment]
I'm having the same issue after upgrading to nuxt 3.7.2

![image](https://github.com/nuxt/nuxt/assets/45218341/8f8d5208-4894-4fcc-bc37-b952054e0ea0)

**Comment by manniL** [comment]
@eitelkrauss can you provide a reproduction?

**Comment by eitelkrauss** [comment]
@manniL working on it

**Comment by eitelkrauss** [comment]
@manniL  best I can do right now is share my repo: https://github.com/eitelkrauss/nuxt-repro

Please note I have this in the 'build:manifest' hook:

```
'build:manifest': (manifest) => {
      for (const key in manifest) {
        manifest[key].dynamicImports = []
      }
    }
```
Too many preloaded resources was causing problems.. should I maybe remove it?

**Comment by manniL** [comment]
@eitelkrauss Unfortunately this is a huge repo and I can't go through every single file. Can you provide a more minimal reproduction?
