### ISSUE TITLE
Class based object dose not get stringified when used as body in $fetch

### ISSUE THREAD

**Issue by jongmin4943** [nuxt/nuxt#22996]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v16.14.0
- Nuxt Version:     3.7.0
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  pnpm@8.6.8
- Builder:          -
- User Config:      components
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/nuxt/nuxt/issues/new?assignees=&labels=pending+triage%2C3.x&projects=&template=bug-report.yml

### Describe the bug

When an `object` is passed as a body to `$fetch`, the `object` will be stringified automatically. However, if the `object` made from new operation of class is passed, it does not get stringified.

I found that in `ofetch`, there is a function `isJSONSerializable`, it dose not check the `value` is class based object or not.

**Comment by danielroe** [comment]
Have you tried providing a `toJSON` method on your class?

If that isn't working, would you raise an issue upstream in http://github.com/unjs/ofetch instead?
