### ISSUE TITLE
Cache: Can't use Unstorage custom driver with Nitro Cache in Nuxt 3

### ISSUE THREAD

**Issue by mkierdev** [nuxt/nuxt#22990]
### Environment

Nuxt 3.5
Node 18

### Reproduction

So we have Nitro Cache API documentation https://nitro.unjs.io/guide/cache
As well as an option to create custom driver for Unstorage: https://unstorage.unjs.io/custom-driver

```js
// Creating custom driver
import { createStorage, defineDriver } from "unstorage";

const myStorageDriver = defineDriver((options) => {
  return {
    name: "my-custom-driver",
    options,
    async hasItem(key, _opts) {},
    async getItem(key, _opts) {},
    async setItem(key, value, _opts) {},
    async removeItem(key, _opts) {},
    async getKeys(base, _opts) {},
    async clear(base, _opts) {},
    async dispose() {},
    async watch(callback) {},
  };
});

const storage = createStorage({
  driver: myStorageDriver(),
```

How to use that driver in Nuxt? Where to register it / import? I tried to put it in plugins, however did not succeed.
Below solution won't work, nuxt can't find it (unsuprisingly)
```js
// nuxt.config.ts
export default defineNuxtConfig({
  nitro: {
    storage: {
      cache: {
        driver: 'my-custom-driver'
      }
    }
  }
})
```

### Describe the bug

While in-memory production cache is nice for small-scale apps, in large-scale application we would like to connect to external key-value storage (which driver preset is not predefined in Unstorage, like Redis).

We would like to enable page-caching (enabling cache in route rules) in external storage and purge cache with our backend.

Assuming we successfully created custom cache driver, there is no documentation on how to connect it with Nuxt app (and how nuxt will use it to serve page from cache).

**Comment by danielroe** [comment]
You would do it like this:

```ts
export default defineNuxtConfig({
  nitro: {
    storage: {
      cache: {
        driver: '~/custom-driver' // path to file or npm package
      }
    },
  }
})
```

For example: https://stackblitz.com/edit/github-qmj8tb.

**Comment by mkierdev** [comment]
@danielroe adding devStorage breaks the project.

```
 ERROR  Cannot start nuxt:  Cannot find package '~' imported from ...
```

```js
export default defineNuxtConfig({
  nitro: {
    storage: {
      cache: {
        driver: '~/custom-driver',
      },
    },
    devStorage: {
      cache: {
        driver: '~/custom-driver',
      },
    },
    routeRules: {
      '/api/**': {
        cache: {
          maxAge: 60,
        },
      },
    },
  },
});
```js

**Comment by woldtwerk** [comment]
I got the same error. Cannot find package '~'

**Comment by danielroe** [comment]
Yes, it seems it's a bit inconsistent with devStorage vs storage. devStorage is actually executed at runtime so it needs to be something that can be dynamically imported.

Updated my stackblitz.

**Comment by woldtwerk** [comment]
I'm still a bit puzzled.
You changed the driver from ts  to mjs. That means the runtime driver needs to be plain js?

Also do you know how to apply this to nuxt/content sources? Afaik they don't allow devStorage.

**Comment by danielroe** [comment]
Sorry, that may have been confusing. I mean that the devStorage driver is not part of your app's build. It's imported and run directly within the dev server. So it needs to be runnable in Node - so yes, plain JS.

**Comment by pi0** [comment]
We might improve that for devStorage supprting ts and same aliases. Feel free to open a (short) upstream issue in nitro to not forget.

**Comment by woldtwerk** [comment]
got it to work with nuxt content and custom gitlab driver.
Thanks for support
