### ISSUE TITLE
Typed query and body for `$fetch` and `useFetch`

### ISSUE THREAD

**Issue by aspitrine** [nuxt/nuxt#23009]
### Describe the feature

Hi

In this [h3 issue closed ](https://github.com/unjs/h3/issues/129) we have now the generic type for the route definition but the type was not provided to the $fetch (for query / body).

It is possible to make it happening ? =)

thanks for all your hard work 🙏🏻🙏🏻🙏🏻

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
This first needs to be implemented in Nitro via https://github.com/unjs/nitro/pull/1532 (wip) and then implemented within Nuxt's `useFetch` composable.

**Comment by awdr74100** [comment]
A real killer feature! Finally no longer need to rely on trpc-nuxt and other things! Does that mean [server/functions](https://github.com/unjs/nitro/discussions/235) is no longer in the current development plan?

**Comment by minkoonim** [comment]
this will be so great!

**Comment by angelhdzmultimedia** [comment]
I'm working on a repository pattern, and was making a composable impl. useAsyncData + $fetch, 
and passed a type to `useAsyncData<AuthUser>`, and it complained in the body missing password (of course AuthUser doesn't have a password), so then I remembered that's the return type (for the data Ref), not the type for the body!!!

And all the roads brought me here.

Then after researching commits, I realized `defineEventHandler` already supports generics, `{body: T}` namespace for POST body and `{query: T}` namespace for GET query as the 1st generic parameter, and the 2nd generic parameter is the result type, and it works, but I get errors with the event handler and it's return type when I use `async`.

Can someone kindly please confirm this?

**Comment by jd-solanki** [comment]
I just switched from FastAPI + Nuxt to Fully Nuxt and realized I'm missing type safety for query & body params 😞 

Also, I guess implementing this feature will also help providing official support for OpenAPI docs like swagger & ReDoc.

**Comment by ElYaiko** [comment]
Bump
How does not Nuxt supports this yet?, this is a necessity for a even better DX

**Comment by angelhdzdev** [comment]
Hello 👀👋 any update on this?

I did some attempts to achieve this myself, but I realized the body type is static. The only workaround is augmenting $fetch or useFetch but any attempt at codegen the types conflicts with .nuxt/types/imports.d.ts declare global of useFetch.

We are so close to achieve type safety!!! 🥲🥵
