### ISSUE TITLE
env variable is messing when deploying to netlify edge 

### ISSUE THREAD

**Issue by sanba-anass** [nuxt/nuxt#23002]
### Environment

Operating System: Windows_NT
- Node Version:     v18.12.1
- Nuxt Version:     3.7.0
- CLI Version:      3.7.0
- Nitro Version:    2.6.1
- Package Manager:  npm@9.6.2
- Builder:          -
- User Config:      modules, nitro, supabase
- Runtime Modules:  @vue-macros/nuxt@1.7.12, @nuxtjs/supabase@1.0.2
- Build Modules:  -

### Reproduction

 i'm trying to deploy my [repo](https://github.com/sanba-anass/todo-app-nuxt) on netlify edge ,
 iwill expose my env variables so u can test :
SUPABASE_URL="https://byoguxigzppxdfezrqhv.supabase.co"

SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5b2d1eGlnenBweGRmZXpycWh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTMyMjc1ODUsImV4cCI6MjAwODgwMzU4NX0.TpUclehKVtW5Kdi1XLiHOTU3MqM1AWUbzn5k0IgFwmY"

### Describe the bug

![image](https://github.com/nuxt/nuxt/assets/83970851/7ed50489-d8bd-4d6c-9563-43325b53a1b9)
i'm getting this error when i open the deployed Link 
 

### Additional context

i'm using netlify-edge preset 
![code](https://github.com/nuxt/nuxt/assets/83970851/a43fa701-5aa0-44e7-b4f9-c6e42d956444)

### Logs

```shell-script
11:53:28 PM: build-image version: 8205490ca60064f5c9949f585e9e35b434be95b8 (focal)
11:53:28 PM: buildbot version: eb0b3c03ee1b40888f6883e255e3a141a5a683be
11:53:28 PM: Fetching cached dependencies
11:53:28 PM: Failed to fetch cache, continuing with build
11:53:28 PM: Starting to prepare the repo for build
11:53:29 PM: No cached dependencies found. Cloning fresh repo
11:53:29 PM: git clone --filter=blob:none https://github.com/sanba-anass/todo-app-nuxt
11:53:29 PM: Preparing Git Reference refs/heads/master
11:53:30 PM: Starting to install dependencies
11:53:30 PM: Python version set to 3.8
11:53:30 PM: Attempting Ruby version 2.7.2, read from environment
11:53:31 PM: Using Ruby version 2.7.2
11:53:32 PM: Started restoring cached go cache
11:53:32 PM: Finished restoring cached go cache
11:53:32 PM: go version go1.19.12 linux/amd64
11:53:32 PM: Using PHP version 8.0
11:53:33 PM: v18.17.1 is already installed.
11:53:34 PM: Now using node v18.17.1 (npm v9.6.7)
11:53:34 PM: Enabling Node.js Corepack
11:53:34 PM: Started restoring cached build plugins
11:53:34 PM: Finished restoring cached build plugins
11:53:34 PM: Started restoring cached corepack dependencies
11:53:34 PM: Finished restoring cached corepack dependencies
11:53:34 PM: No npm workspaces detected
11:53:34 PM: Started restoring cached node modules
11:53:34 PM: Finished restoring cached node modules
11:53:34 PM: Installing npm packages using npm version 9.6.7
11:53:42 PM: > postinstall
11:53:42 PM: > nuxt prepare
11:53:43 PM: [warn] Missing `SUPABASE_URL` in `.env`
11:53:43 PM: [warn] Missing `SUPABASE_KEY` in `.env`
11:53:44 PM: [success] Types generated in .nuxt
11:53:44 PM: added 991 packages, and audited 993 packages in 9s
11:53:44 PM: 151 packages are looking for funding
11:53:44 PM:   run `npm fund` for details
11:53:44 PM: 2 moderate severity vulnerabilities
11:53:44 PM: To address all issues (including breaking changes), run:
11:53:44 PM:   npm audit fix --force
11:53:44 PM: Run `npm audit` for details.
11:53:44 PM: npm packages installed
11:53:44 PM: Install dependencies script success
11:53:44 PM: Starting build script
11:53:45 PM: Detected 1 framework(s)
11:53:45 PM: nuxt at version 3.7.0
11:53:45 PM: Section completed: initializing
```

**Comment by danielroe** [comment]
Would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏
