### ISSUE TITLE
Perfect sitemap on local build, only defaultLocale on distant build (netlify)

### ISSUE THREAD

**Issue by Joaojack** [nuxt/nuxt#23018]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.4.0
- Nuxt Version:     3.7.1
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  npm@9.7.2
- Builder:          -
- User Config:      runtimeConfig, imports, app, devtools, modules, pinia, apollo, build, i18n, sitemap
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @vueuse/nuxt@10.4.1, @nuxtjs/apollo@5.0.0-alpha.6, @nuxtjs/i18n@8.0.0-rc.4, nuxt-schema-org@2.2.0, nuxt-simple-sitemap@2.7.0, @pinia/nuxt@0.4.11
- Build Modules:    -
------------------------------

### Reproduction

My config : 
  i18n: {
    baseUrl: 'https://www.foobat.com',
    stratedy: 'prefix_except_default',
    customRoutes: 'config', 
    locales: [
      {
        code: 'en',
        iso: 'en-US',
        name: 'English',
        file: 'en-US.json'
      },
      {
        code: 'fr',
        iso: 'fr-FR',
        name: 'Français',
        file: 'fr-FR.json'
      },
    ],
    defaultLocale: 'fr',
    langDir: 'lang',
    pages: {
      chambres: {
        en: '/rooms-suites-french-riviera', 
        fr: '/chambres-suites-cote-dazur',
      },
      journal: {
        fr : '/cote-d-azur-evenements-hebergement',
        en : '/french-riviera-events-accommodation'
      },
      cgv: {
        fr : '/conditions-generales-vente-hebergement-golfe-juan',
        en : '/general-terms-conditions-accommodation-golfe-juan'
      },
      confidentialite: {
        fr : '/declaration-confidentialite',
        en : '/privacy-policy'
      },
      legal: {
        fr : '/mentions-legales',
        en : '/legal-notice'
      },
      exterieurs: {
        fr : '/jardin-piscine-hebergement-golfe-juan',
        en : '/garden-pool-accommodation-golfe-juan'
      },
      services: {
        fr : '/services-luxe-cote-d-azur',
        en : '/services-luxury-french-riviera'
      },
      informations: {
        fr : '/informations-plage-hebergement-golfe-juan',
        en : '/information-beach-accommodation-golfe-juan'
      },
      professionnels: {
        fr : '/tournages-seminaires-cote-d-azur',
        en : '/shootings-seminars-french-riviera'
      },
  }
},
sitemap: {
  siteUrl: 'https://www.foobar.com'
}

### Describe the bug

Hi guys, my issue is with i18n, nuxt simple sitemap and deployment. When running build + Generate and launching the server locally, the sitemap is perfect with all the locale paths with custom route names.
But when deploying on netlify (which creates, i guess, a build), the sitemap.xml only displays the defaultLocale pages (with correct custom routes names)
How come my local build generates the correct xml, and the distant one doesn't ?

**Comment by danielroe** [comment]
This seems like an issue that should be raised with the sitemap module rather than in Nuxt itself.

**Comment by danielroe** [comment]
No problem at all! 😅
