### ISSUE TITLE
[nuxt generate] does not provide an export named 'isScriptProtocol'

### ISSUE THREAD

**Issue by lucassonsinlima** [nuxt/nuxt#23017]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.14.0`
- Nuxt Version:     `3.7.1`
- CLI Version:      `3.7.3`
- Nitro Version:    `2.6.2`
- Package Manager:  `npm@8.19.4`
- Builder:          `-`
- User Config:      `experimental`, `generate`, `router`, `hooks`, `modules`, `css`, `vite`, `intlify`, `runtimeConfig`, `nitro`, `app`
- Runtime Modules:  `@intlify/nuxt3@0.2.4`, `@pinia/nuxt@0.4.11`
- Build Modules:    `-`

### Reproduction

I tried to reproduce but seems that a raw `v3.7.1` app works fine even with same nuxt config as my error scenarios.

### Describe the bug

I've two apps using nuxt `v3.6.5` and `nuxt generate` works properly. After upgrading to `v3.7.1` I'm getting this error on both apps. I tried to create a raw app with same nuxt config but it works. Seems that it can be related to this line on [`router` composable](https://github.com/nuxt/nuxt/blob/88a6d0a499cc7696bff94c02548cd9cc60f7820b/packages/nuxt/src/app/composables/router.ts#L5). I checked out on `ufo`'s repository and [this function](https://github.com/search?q=repo%3Aunjs%2Fufo%20isScriptProtocol&type=code) still exists but I didn't find it on `dist`.

_error image after `nuxt generate`_
<img width="1506" alt="Screenshot 2023-09-05 at 17 13 57" src="https://github.com/nuxt/nuxt/assets/25435624/fad40c71-4dfe-45d1-98f0-fdf2cbb766a8">

**Comment by jessecogollo** [comment]
I guess. some dependency is using an old ufo version. I am getting the same error trying to deploy in vercel:

```
[error] [nitro] RollupError: "isScriptProtocol" is not exported by "node_modules/.pnpm/ufo@1.1.2/node_modules/ufo/dist/index.mjs", imported by ".nuxt/dist/server/server.mjs".
```

**Comment by danielroe** [comment]
Would you try refreshing your lockfile (which you can do with `npx nuxi upgrade --force`), and make sure it is included in your git repository?

**Comment by jessecogollo** [comment]
@danielroe it works. Just to let you  know that the error comes with an automatic PR using dependabot. Thank you so much.

**Comment by lucassonsinlima** [comment]
update: I found that both projects were using https://github.com/intlify/nuxt3 and it relies on `ufo@0.8.3`. I don't really got too deep on this and don't know why it's conflicting on nuxt router composable, nuxt uses the updated `ufo`'s version as dep. I ended up updating my i18n to `https://v8.i18n.nuxtjs.org/` since other package is on maintenance mode and it solved my issue but weird that nuxt was getting a plugin dep version and using it as it's own even after `npx nuxi upgrade --force`
