### ISSUE TITLE
Altering cdnURL through a module

### ISSUE THREAD

**Issue by ahmadqwer** [nuxt/nuxt#23010]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.12.1
- Nuxt Version:     3.7.0
- CLI Version:      3.7.0
- Nitro Version:    2.6.1
- Package Manager:  pnpm@8.6.1
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-akg9dw-ha2lwf

### Describe the bug

I am trying to altering `cdnUrl` in a custom module.

It did not work when when I try to altering it like this
`nuxt.options.app.cdnURL`

But when i add it to nuxt.config.ts it work just fine.

**Comment by danielroe** [comment]
By the time the module runs, cdnURL has already been passed to `runtimeConfig`. You should be able to set `nuxt.options.runtimeConfig.app.cdnURL` instead.
