### ISSUE TITLE
`nuxt build --spa` does not work in Nuxt3?

### ISSUE THREAD

**Issue by snowdream** [nuxt/nuxt#23019]
### Environment

$ npx nuxi info
Working directory: D:/workspace/go/src/snowdream.tech/vue-nuxt-element-template                                           07:10:09
Nuxt project info:                                                                                                        07:10:09

------------------------------
- Operating System: Windows_NT
- Node Version:     v19.8.1
- Nuxt Version:     3.7.0
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  pnpm@8.7.1
- Builder:          -
- User Config:      ssr, app, runtimeConfig, css, typescript, modules, i18n, vueuse, colorMode, unocss, vite, elementPlus
- Runtime Modules:  @vueuse/nuxt@10.4.1, @unocss/nuxt@0.55.4, @pinia/nuxt@0.4.11, @element-plus/nuxt@1.0.5, @nuxtjs/i18n@8.0.0-rc.4, @nuxtjs/color-mode@3.3.0, nuxt-icon@0.5.0
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                               07:10:09

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Reproduction

https://stackblitz.com/edit/github-qotxoc

### Describe the bug

nuxt build --spa does not work in Nuxt3

```
 pnpm build --help

> element-plus-nuxt-starter@0.1.0 build D:\workspace\go\src\snowdream.tech\vue-nuxt-element-template
> MODE=prod nuxi build "--help"

Build nuxt for production deployment (nuxi build v3.7.3)                                                                  07:11:36

USAGE nuxi build [OPTIONS] [ROOTDIR]

ARGUMENTS

  ROOTDIR    Root Directory

OPTIONS

        --cwd    Current working directory
   --logLevel    Log level
  --prerender    Build nuxt and prerender static routes
     --dotenv    Path to .env file

```

**Comment by danielroe** [comment]
See https://github.com/nuxt/nuxt/issues/13803#comment-1721476 and the workaround provided in the thread.

We don't plan to add this flag, for the reasons I mentioned there.

**Comment by snowdream** [comment]
Use Case: 
`nuxi build --spa` + `ssr: false` Support

Nuxt Build Mode SPA

Then I Embed the dist(.out/public) into golang binary, and served with gin.

My Solution:

1. edit nuxt.config
```
// https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
export default defineNuxtConfig({
  ssr: false,

  nitro: {
    prerender: {
      crawlLinks: false,
      ignore: [],
      routes: [],
    },
  },
```

2. execute
```
pnpm generate
```

**Comment by snowdream** [comment]
> PS: You can also add `ssr: !process.argv.includes('--spa')` in `nuxt.config` to replicate Nuxt 2 CLI behavior!

I see, Thank you.

in fact:

```
//https://github.com/nuxt/nuxt/issues/13803#issuecomment-1397316950
const spa = process.env.MODE === 'prod' || process.argv.includes("--spa");

// https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
export default defineNuxtConfig({
  ssr: !spa,

  nitro: {
    prerender: {
      crawlLinks: false,
      ignore: [],
      routes: [],
    },
  },
```

**Comment by alexcroox** [comment]
```
nitro: {
    prerender: {
      crawlLinks: false,
      ignore: [],
      routes: [],
    },
  },
```

This was the secret sauce required for `nuxt generate` to generate a real SPA with a single index.html input, instead of what looked like an SSG with hundreds of route based index.html files. 

Thanks!
