### ISSUE TITLE
[Bug] : Cannot read properties of undefined (reading 'toLowercase') ["@storefront-ui/vue": "^2.5.0", "nuxt": "2.15.8" , "vue": "2.6.14"]

### ISSUE THREAD

**Issue by bhagvanp** [nuxt/nuxt#23011]
### Environment

https://docs.storefrontui.io/v2/vue/getting-started.html

### Reproduction

https://github.com/bhagvanp/Vuestorefront-2/tree/vue-demo

### Describe the bug

I have shared  you my issue with screenshot screenshot :

We are  migrate Vue-Storefront 2  with Magento 2 then facing issue. 

![image](https://github.com/nuxt/nuxt/assets/143793264/fe3adf11-a2bc-4dc9-adce-c9c710ad385b)

![image](https://github.com/nuxt/nuxt/assets/143793264/feb27d10-807a-4685-8c63-67eb5b4a60df)

**Comment by danielroe** [comment]
Would you provide a more minimal reproduction, please? 🙏
