### ISSUE TITLE
Nuxt 3 - Referencing a store in a layout and a lazy loaded component stop layout component's styles being inlined on load 

### ISSUE THREAD

**Issue by gavin667** [nuxt/nuxt#23016]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.7.0`
- CLI Version:      `3.7.3`
- Nitro Version:    `2.6.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `-`
- User Config:      `devtools`, `modules`, `pinia`, `imports`, `postcss`, `experimental`, `css`
- Runtime Modules:  `@pinia/nuxt@0.4.11`
- Build Modules:    `-`

### Reproduction

View on https://nuxt-3-layout-css.vercel.app/

Reproduction repo available at - https://github.com/gavin667/nuxt-3-layout-css

#### Steps to reproduce
1. Load https://nuxt-3-layout-css.vercel.app/
2. You may need to throttle your network connection to notice the colour swap.
3. Notice the text for a component based in the layout flashes from black to blue?

#### Expected behaviour
The text for a component based in the layout should not flash black to blue on initial page load.

The styles for components referenced in a layout file should be inlined correctly like other page styles when a lazy loaded component that also references the same store in the layout is used.

#### Actual behavior

It seems to be that if I call a Pinia store in a layout file and reference a lazy loaded component that also references the same store it fails to inline the styles correctly on initial page load.

Commenting out either references to the store fixes the issue.

Check [the repo I made](https://github.com/gavin667/nuxt-3-layout-css) but as a simplified version:

```
// layouts/default.vue
<template>
  <div>
    <div>This is text directly on the layout.</div>

    <!-- CSS inside this is not inlined and leads to FOUC -->
    <AnotherComponent/>

    <!-- This component also references const exampleStore = useExampleStore() -->
    <LazyTestComponent v-if="showLazyComponent"/>

    <div>
        <slot />
    </div>
  </div>
</template>
<script setup>
  const exampleStore = useExampleStore()
</script>
```

```
// components/TestComponent.vue
<template>
  <div class="test-component">
    <h1>This should be red on load</h1>
  </div>
</template>

<script setup>
  const exampleStore = useExampleStore()
</script>

<style lang="postcss">
  .test-component {
    color: red;
    font-size: 1.2rem;
  }
</style>  
```

```
// components/AnotherComponent.vue
<template>
    <h1 class="another-component">
        This should be blue on load
    </h1>
</template>
<style lang="postcss">
  // these styles are missing onload
  .another-component {
    color: blue;
  }
</style>
```

### Additional context

I opened an issue on vuejs/pinia [here](https://github.com/vuejs/pinia/issues/2399) but that was close pretty promptly and I was recommended to open an issue here.

Happy to assist in any further debugging that might be needed.

I realise in the basic example I have linked it isn't much of an issue as it is just a simple colour swap. However when there are more or bigger components referenced within a layout and this happens it causes a more significant issue.

Appreciate any help (or fixes)!

**Comment by danielroe** [comment]
Thank you for the reproduction, that's helpful. Let's track in https://github.com/nuxt/nuxt/issues/22507.
