### ISSUE TITLE
Cannot build with CKEditor 5

### ISSUE THREAD

**Issue by duongxinh2003** [nuxt/nuxt#23029]
### Environment

- Operating System: Darwin
- Node Version:     v16.17.1
- Nuxt Version:     3.7.1
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  npm@9.6.7

### Reproduction

https://stackblitz.com/edit/github-xuxuvn

### Describe the bug

Hi,
I made an effort to set up CKEditor 5 based on Nuxt 3. I ran by command `npm run dev` with no problem. But, when I built my project by the command `npm run build`, an error occurred: `ENOENT: no such file or directory`. I tried many ways but the project cannot be built with the same error. The reproduction demo I added below.
Anyone can help me, thanks!

### Logs

```shell-script
ERROR  Could not load raw:../../theme/components/button/button.css (imported by node_modules/@ckeditor/ckeditor5-ui/src/button/buttonview.js): ENOENT: no such file or directory, open '../../theme/components/button/button.css'

ERROR  Could not load raw:../theme/code.css (imported by node_modules/@ckeditor/ckeditor5-basic-styles/src/code.js): ENOENT: no such file or directory, open '../theme/code.css'
```

**Comment by danielroe** [comment]
You will need to add ckeditor to your transpile array as it's shipping CSS/SVGs which can't be imported within a pure Node environment.

```diff
  // https://v3.nuxtjs.org/api/configuration/nuxt.config
  import ckeditor5 from '@ckeditor/vite-plugin-ckeditor5';
  import { createRequire } from 'node:module';
  
  const require = createRequire(import.meta.url);
  
  export default defineNuxtConfig({
+   build: {
+     transpile: [/ckeditor/]
+   },
    vite: {
      plugins: [
        ckeditor5({ theme: require.resolve('@ckeditor/ckeditor5-theme-lark') }),
      ],
    },
    routeRules: {
      '/**': { ssr: false },
    },
  });
```

**Comment by duongxinh2003** [comment]
Thank you so much!

**Comment by danielroe** [comment]
you're very welcome 😊
