### ISSUE TITLE
When using Nitro proxy, it's not possible to download files from the server's response.

### ISSUE THREAD

**Issue by ehaakdl** [nuxt/nuxt#23023]
### Environment

"node": "^16.20.0"
"nuxt": "^3.6.5"

### Reproduction

[web.zip](https://github.com/nuxt/nuxt/files/12530598/web.zip)

### Describe the bug

**nitro.config**
![image](https://github.com/nuxt/nuxt/assets/6407466/b75fc957-0115-46aa-9150-9ca86dbc21c8)

**backend code**
![image](https://github.com/nuxt/nuxt/assets/6407466/47721c60-5386-44b2-a593-3714ba176659)

I'm capturing the code for fetch when using Nitro and when not using Nitro.
When not in use, the size is measured as 2.
![image](https://github.com/nuxt/nuxt/assets/6407466/d689ec56-8499-40ae-8226-35f3a46b8550)

**Comment by danielroe** [comment]
Would it be possible for you to reproduce purely in Nitro and open in https://github.com/unjs/nitro instead? 🙏

**Comment by ehaakdl** [comment]
> 순전히 Nitro로 재현하고 대신 https://github.com/unjs/nitro 에서 열 수 있습니까 ? 🙏

sure

**Comment by ehaakdl** [comment]
[move](https://github.com/unjs/nitro/issues/1703)
