### ISSUE TITLE
Async context does not work on stackblitz

### ISSUE THREAD

**Issue by zipme** [nuxt/nuxt#23032]
### Environment

nuxt 3.7.0

### Reproduction

https://stackblitz.com/edit/nuxt-starter-jxxuvq?file=nuxt.config.ts,package.json,pages%2Findex.vue,layout%2Fdefault.vue

### Describe the bug

I am basically just copying from https://github.com/nuxt/nuxt/blob/main/test/fixtures/basic/pages/async-context.vue and https://github.com/nuxt/nuxt/blob/main/test/fixtures/basic/composables/async-context.ts

Then set
```ts
experimental: {
    asyncContext: true,
  },
```
But still got this error
> [nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at `https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables`.

**Comment by pi0** [comment]
Can you reproduce it locally on Node.js 18+ too?

**Comment by danielroe** [comment]
When cloning stackblitz and running locally it seems to work fine for me.

I think this is likely just a stackblitz limitation as Pooya suggested.

**Comment by pi0** [comment]
I can confirm with minimal reproduction as well: https://stackblitz.com/edit/stackblitz-starters-ip9tov?file=index.mjs&startScript=test

**Comment by zipme** [comment]
@pi0  @danielroe  Indeed it works locally with nodejs 18+

**Comment by danielroe** [comment]
I think we can close this here as it's not a Nuxt issue, but we might document this. We can track upstream in https://github.com/stackblitz/webcontainer-core/issues/1169#issuecomment-1698872854.

**Comment by zipme** [comment]
Hi @danielroe , do you know if it's also possible to restore vue's context? Currently if calling `getCurrentInstance()` we get `null` back, and doing things like `provide` `inject` doesn't seem to work unless we explicitly do:
```ts
const something = await getSomething()
cosnt nuxtApp = useNuxtApp()
const thing = nuxtApp.vueApp.inject(xxxx)
// inject(xxx) <- this would fail
```

**Comment by danielroe** [comment]
Vue doesn't yet have support for this, so `useNuxtApp()` works but Vue wouldn't yet be able to recover its context.
