### ISSUE TITLE
docs: router options not fully documented

### ISSUE THREAD

**Issue by riddla** [nuxt/nuxt#23039]
### Describe the feature

A colleague of mine stumbled upon the `scrollBehaviorType` router option introduced in v3.7.0 (which solved many problems for us 👍).

It seems that the [current router schema](https://github.com/nuxt/nuxt/blob/v3.7.1/packages/schema/src/config/router.ts) does not include the [additional options found in the routers type](https://github.com/nuxt/nuxt/blob/v3.7.1/packages/schema/src/types/router.ts#L3) and therefore the [according docs](https://nuxt.com/docs/api/configuration/nuxt-config#options) are incomplete.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Thanks for spotting this!

**Comment by madebyfabian** [comment]
Created a PR to improve the docs and examples on this, let me know if there is anything still missing/not documented!
