### ISSUE TITLE
Nuxt 3.7 - Properties of an reactive class object are set to undefined  

### ISSUE THREAD

**Issue by CodeDredd** [nuxt/nuxt#23038]
### Environment

- Operating System: Linux
- Node Version:     v18.16.0
- Nuxt Version:     3.7.1
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  pnpm@7.5.2
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  @pinia/nuxt@0.4.11, @pinia-plugin-persistedstate/nuxt@1.1.1, @pinia-orm/nuxt@1.6.7
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-qerved?file=app.vue

### Describe the bug

I already tried to debug on the pinia-orm package site.
I was able to pin it down that somehow the class object is set with the correct values but due to reactivity overwritten with undefined for all props. In the class object all functions are executed correctly. 
So my best guess is that it has to do with the serialization in nuxt.

### Additional context

With nuxt 3.6.5 everything works fine.

### Logs

```shell-script
vue.js:1449 [Vue warn]: Unhandled error during execution of native event handler 
  at <App key=3 > 
  at <NuxtRoot>
warn2 @ vue.js:1449
logError @ vue.js:1623
handleError @ vue.js:1615
callWithErrorHandling @ vue.js:1567
callWithAsyncErrorHandling @ vue.js:1573
invoker @ vue.js:9397

and

Uncaught Error: [Pinia ORM] The record is missing the primary key. If you want to persist record without the primary key, please define the primary key field with the `uid` attribute.
    at throwError (pinia-orm.1bd7d299.mjs:102:9)
    at assert (pinia-orm.1bd7d299.mjs:106:5)
    at Todo.$getIndexId (index.mjs?t=1693992789784:3226:5)
    at index.mjs?t=1693992789784:1461:21
    at Array.reduce (<anonymous>)
    at Query.compile (index.mjs?t=1693992789784:1460:23)
    at Query.insert (index.mjs?t=1693992789784:1314:32)
    at Repository.insert (index.mjs?t=1693992789784:1845:25)
    at addToDo (app.vue:16:8)
    at callWithErrorHandling (vue.js:1565:18)
```

**Comment by CodeDredd** [comment]
Update from my side:
The bug starts with commit: 1f1de38d0304ef8a00aaae1c02019fcf015f2f19
After a lot of hours of testing to get to this. I also found out that if you pin down `vite` to version 4.3.9 everything works.
https://stackblitz.com/edit/nuxt-starter-df6vdm?file=app.vue,package.json
````json
{
...
  "resolutions": {
    "vite": "4.3.9"
  },
  "devDependencies": {
    "nuxt": "^3.7.1"
  },
  "dependencies": {
    "@pinia-orm/nuxt": "^1.6.7",
    "@pinia-plugin-persistedstate/nuxt": "^1.1.1",
    "@pinia/nuxt": "^0.4.11",
    "@types/node": "^20.5.9",
    "pinia": "^2.1.6",
    "pinia-orm": "^1.6.7",
    "vite": "4.3.9",
    "vue": "^3.3.4"
  }
...
}
````

### **BUT** 
here comes now the headache. I started to create an example only with vite 4.4.9 and it also works:
https://stackblitz.com/edit/vitejs-vite-8usbda?file=package.json,src%2FApp.vue&terminal=dev

I need a bit more brainpower here 🙏 @danielroe @pi0 is this still a `nuxt` bug? i think not but it seems also not to be a `vite` bug.

**Comment by Sayanel34** [comment]
Hi ! Got any news on that by any chance ?

**Comment by Sayanel34** [comment]
Well it's a good thing to pin a workaround available, but it seems it does not work for everyone.

**Comment by mariusgnicula** [comment]
I can confirm it only works when using Vite 4.3.9. Thanks @CodeDredd! Spent quite a few hours scratching my head before I found your comment!

**Comment by mariusgnicula** [comment]
Hey fellas! Posting here as well as in https://github.com/CodeDredd/pinia-orm/issues/1610. So I got this working with Nuxt 3.8.1 and Vite 5.0.0. Apparently it wasn't enough to add experimental decorators to my TS config, but add it to Nuxt config as well, like so:

```
export default defineNuxtConfig({
  debug: true,
  devtools: { enabled: true },
  modules: ['@pinia/nuxt', '@pinia-orm/nuxt'],
  typescript: {
    typeCheck: true,
    strict: true,
  },
  vite: {
    esbuild: {
      tsconfigRaw: {
        compilerOptions: {
          experimentalDecorators: true,
        }
      }
    }
  }
})
Got this workaround from here: https://github.com/vitejs/vite/issues/13736

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/14126
