### ISSUE TITLE
NuxtLoadingIndicator does not working for dynamic pages

### ISSUE THREAD

**Issue by ghost** [nuxt/nuxt#23042]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.7.1`
- CLI Version:      `3.7.3`
- Nitro Version:    `2.6.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `-`
- User Config:      `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-cei3lp?file=app.vue

### Describe the bug

NuxtLoadingIndicator does not working for dynamic pages (loaded via `[...slugs].vue`). It works only for staticly added pages.  I suppose that the last working version of nuxt is `3.5.0`, I tried with versions:
- 3.6.0
- 3.6.5
- 3.7.0
- 3.7.1 (latest)

**Preview:**
https://github.com/nuxt/nuxt/assets/33403174/bc8cf61b-5923-4f77-a183-4c80138f1cef

**Comment by danielroe** [comment]
related: https://github.com/nuxt/nuxt/issues/22670 and https://github.com/nuxt/nuxt/issues/15271.

**Comment by agracia-foticos** [comment]
Any advance?

**Comment by agracia-foticos** [comment]
Any notice?

**Comment by danielroe** [comment]
This is resolved in v3.9.1.

See fixed reproduction: https://stackblitz.com/edit/github-cei3lp-p1aesy.
