### ISSUE TITLE
html is statically generated through the server api and redirected when accessed through a browser

### ISSUE THREAD

**Issue by mqyun** [nuxt/nuxt#23059]
### Environment

- Operating System: Darwin
- Node Version:     v16.20.1
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.17
- Builder:          vite
- User Config:      devtools, modules, vite, srcDir, app, router
- Runtime Modules:  @element-plus/nuxt@1.0.5
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-agc8n9?file=package.json

### Describe the bug

After the project is deployed and the interface /nuxt-demo/api/generate/detail is called, a static html file is generated and saved to disk. When I access this html in my browser, it gets redirected to the /detail/base route, which seems to be handled by the vue-router, is there any way not to redirect it?

**Comment by danielroe** [comment]
You can work around this by unsetting/deleting `nuxtApp.payload.path` in a server-only plugin.
