### ISSUE TITLE
Nuxt3 .server (island) components fail to render on soft navigation if they have different props on pages

### ISSUE THREAD

**Issue by arsengoian** [nuxt/nuxt#23051]
### Environment

Works in any environment, including StackBlitz:

```
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.7.1
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      experimental
- Runtime Modules:  -
- Build Modules:    -
```

### Reproduction

Please refer to:

https://stackblitz.com/edit/github-ydxe3t?file=pages%2Findex.vue

1. Do `nuxt generate` and `npx serve .output/public`.
2. CLick the link 'Go to page with scoped styles'
3. **Note the 404 in console on click to the link and absence of the component**
4. Reload the page
5. Note the component was loaded normally
6. Remove scoped attribute from style tag in pageWithScopedStyles.vue and repeat the excercise

### Describe the bug

Apparently because scoped styles in Vue are implemented using attributes and the server components are rendered based on attribute values, server components **in some instances** will break (the client will request a non-existing URL of `__nuxt_island/whatever_id`, leading to a 404. This will lead to the component not being displayed. 

The sufficient conditions for the reproduction are following: 
- There is a server component used on two separate pages
- It's not used directly, but through a third component (I used a wrapper) which uses this component as root
- It has a prop that is different on these pages (I injected the route, I suppose it's also possible that a state variable may be passed as a prop

This is not reproduced in dev, only if the site is statically generated using `nuxt generate` and the client navigates to the page which uses scoped styles using soft navigation, e.g. `<NuxtLink />`

I'm not certain what causes the bug.

### Additional context

I know this might sound like an edge case but I arrived to this bug in a real-world scenario and I imagine this could be an issue for example  for component library creators who want to use .server components (llike myself). An easy enough workaround is to avoid using it as a root in the wrapper but I'm sure there are also other unforeseen scenarios that might trigger this problem.

The fact is, it works OK in dev, but breaks during SSG.

**Comment by arsengoian** [comment]
Quick follow-up. The issue is not reproduced if using <NuxtIsland/> instead of a .server component, so that's one reasonable workaround for the time being

**Comment by danielroe** [comment]
Yes, this is an interesting one for sure. Any thoughts @huang-julien?

**Comment by huang-julien** [comment]
Quite strange, i'll take a look 👀 probably a bug at build time with the `loader`.

**Comment by danielroe** [comment]
I think the issue is that any attributes end up as props, and so data attribute added by vue becomes a prop. We might be able to explicitly ignore? Or you may have a better idea.

**Comment by huang-julien** [comment]
Yes, that's the issue. I'm looking at if we can ignore data attributes within `createServerComponent` without having to manually ignore `data-v-` attributes
