### ISSUE TITLE
Nuxt 3.7 - Hydration children mismatch in <div>: server rendered element contains more child nodes than client vdom.

### ISSUE THREAD

**Issue by martinszeltins** [nuxt/nuxt#23056]
### Environment

````
- Operating System: Linux
- Node Version:     v18.14.2
- Nuxt Version:     3.7.1
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  pnpm@8.6.12
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
````

### Reproduction

https://github.com/martinszeltins/nuxt-mismatch
or
https://stackblitz.com/edit/nuxt-starter-ehmtcj?file=app.vue

### Describe the bug

I started a new Nuxt project, added 1 simple component and I am getting a hydration mismatch in the console. The error does not always appear on the initial load. But if you refresh the page a few times the mismatch error shows up. Sometimes with multiple refreshes it disappears. It is really strange.

````
[Vue warn]: Hydration children mismatch in <div>: server rendered element contains more child nodes than client vdom. 
  at <FormField> 
  at <App key=3 > 
  at <NuxtRoot>
````

Here is my app.vue:

```js
<template>
  <div>
    <FormField>
        <input type="text" placeholder="Username">
    </FormField>
  </div>
</template>
```

And here is my FormField:
```js
<template>
    <div>
        <div>
            <slot></slot>
        </div>

        <div v-if="props?.errors?.length"></div>
    </div>
</template>

<script setup lang="ts">
    const props = defineProps<{
        errors?: any[]
    }>()
</script>

```

**Comment by martinszeltins** [comment]
I also added a StackBlitz reproduction if that is easier - https://stackblitz.com/edit/nuxt-starter-ehmtcj?file=app.vue

**Comment by danielroe** [comment]
Does this occur in an incognito window (that is, without any extensions)?

**Comment by martinszeltins** [comment]
> Does this occur in an incognito window (that is, without any extensions)?

@danielroe Oh, wow! You are right, the warnings are gone. It must have been my Chrome extensions. But this could be very confusing for new users when they see these warnings (think errors) and think that Nuxt has a bug. Is it possible to make Nuxt smarter and understand that it is not an actual mismatch between client and server but the extensions are causing it?

This could turn off some new users.

**Comment by renevall** [comment]
I can confirm I get this same behavior. In incognito or another browser account with less addons I don't get the warning. 

In my case, **Last Pass** was the source of the problem. No wonder it was form elements that were all funny.

**Comment by danielroe** [comment]
This error is being thrown by Vue.

Vue has no way of knowing _why_ the HTML is different, only that it is. The browser extension modifies it before Vue has a chance to hydrate it.

Any ideas are more than welcome though at https://github.com/vuejs/core.
