### ISSUE TITLE
Runtime Config Types misses Public Runtime Config

### ISSUE THREAD

**Issue by derHodrig** [nuxt/nuxt#23068]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v16.19.0
- Nuxt Version:     3.7.1
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  yarn@3.6.3
- Builder:          -
- User Config:      devtools, css, build, modules, googleFonts, hooks, imports, piniaPersistedstate, runtimeConfig, vite
- Runtime Modules:  @nuxtjs/google-fonts@3.0.2, @nuxtjs/i18n@8.0.0-rc.4, @pinia/nuxt@0.4.11, @pinia-plugin-persistedstate/nuxt@1.1.1
- Build Modules:    -
------------------------------

### Reproduction

1. Create a Nuxt App `nuxi@latest init my-app`
2. Create a .env with NUXT_PUBLIC_BACKEND_URL="https://localhost:44333"
3. In the nuxt.config add

```
runtimeConfig: {
    public: {
      BACKEND_URL: 'https://localhost:1337',
    },
  },
```

4. run `nuxt prepare`
5. create a component with that script section
```
<script setup lang="ts">
const runtimeConfig = useRuntimeConfig()
const baseUrl = runtimeConfig.public.BACKEND_URL
</script>
```

> The IDE should not recognize `runtimeConfig.public.BACKEND_URL`

### Describe the bug

After running `nuxt prepare` all types also the runtime config types should be generated in .nuxt 
> https://nuxt.com/docs/guide/going-further/runtime-config#manually-typing-runtime-config

In my case, this was true
(.nuxt/types/schema.d.ts)
1. Interface RuntimeConfig
```
interface RuntimeConfig {
   app: {
      baseURL: string,
      buildAssetsDir: string,
      cdnURL: string,
   },
   QSD_QSDID: string,
  }
```

2. Interface PublicRuntimeConfig
```
interface PublicRuntimeConfig {
   QSD_BACKEND_URL: string,
   QSD_FRONTEND_URL: string,
   QSD_UPDATE_UNSEEN_TICKETS_INTERVAL_IN_SECONDS: number,
   QSD_KUNDE_ICON_PATH: string,
   QSD_PRODUKT_ICON_PATH: string,
   i18n: {
      experimental: {
         jsTsFormatResource: boolean,
      },
      baseUrl: string,
   },
   persistedState: {
      storage: string,
      debug: boolean,
      cookieOptions: {
         sameSite: string,
         expires: any,
         maxAge: number,
         secure: boolean,
      },
   },
  }
```

The problem I see, is that the RuntimeConfig Interface does not have a property `public: PublicRuntimeConfig;`
which is given in `node_modules/@nuxt/schema/dist/index.d.ts`

As I add `public: PublicRuntimeConfig;`  to the (.nuxt/types/schema.d.ts ) RuntimeConfig interface 
```
interface RuntimeConfig {
   app: {
      baseURL: string,

      buildAssetsDir: string,

      cdnURL: string,
   },
   public: PublicRuntimeConfig; // <<<< this should solve the bug
   QSD_QSDID: string,
  }
  ```
  the IDE recognize all public ENV and shows their type and autocompletes

**Comment by manniL** [comment]
<img width="1699" alt="image" src="https://github.com/nuxt/nuxt/assets/640208/bc4f6f6f-245b-47a4-9b74-1e48c4eae32c">
<img width="760" alt="image" src="https://github.com/nuxt/nuxt/assets/640208/f85e3df1-f5d1-40e1-b2b3-c394a6605aa0">

Can't repro this anymore.

**Comment by Harm-Nullix** [comment]
I am still facing this exact issue in Jetbrains Webstorm.
`const useRuntimeConfig: typeof import('../../node_modules/nuxt/dist/app/nuxt')['useRuntimeConfig']` points to the nuxt.d.ts of the node_modules.
`export declare function useRuntimeConfig(_event?: H3Event<EventHandlerRequest>): RuntimeConfig;` 
And that points to `/node_modules/@nuxt/schema/dist/index.d.ts`

I will try to find out if I can identify why both files are targeted.. but I think it is not really a issue I am able to fix.

**Comment by jonasfroeller** [comment]
I have that issue in `typescript@5.7.3`. Is the version not supported?
