### ISSUE TITLE
Watch method is no longer working in the same way when watching route

### ISSUE THREAD

**Issue by jastaffen** [nuxt/nuxt#23075]
### Environment

"nuxt: 3.7.1"

### Reproduction

watch(route, async (newVal) => {
   // run code in here
}, { deep: true });

### Describe the bug

In earlier versions of nuxt3 and nuxt2, I used to be able to watch the route object for changes (i.e. query parameters) and adjust things in state or fetch more data, but I'm noticing in later versions of nuxt the watcher is not even running anymore. Any ideas?

**Comment by danielroe** [comment]
This is true, and is a behaviour change in both `vue-router` and in Nuxt, for performance reasons. Instead, you can try `watch(() => route.fullPath)`
