### ISSUE TITLE
Without `<script setup>` Nuxt App context is lost after async

### ISSUE THREAD

**Issue by Ni55aN** [nuxt/nuxt#23074]
### Environment

- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.7.1
- CLI Version:      3.8.0
- Nitro Version:    2.6.2
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      ssr
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-hyndhs-kkpbbx?file=app.vue

```js
export default {
  async setup() {
    // replacement for useAsyncData
    await new Promise((res) => setTimeout(res, 100));

    // awaited call before useHead produces an error on `npm run generate`
    useHead({
      title: 'issue',
    });
  },
};
```

### Describe the bug

After update to 3.7.1 it throws `500` error on `npm run generate` if there is `useSeoMeta` 

### Logs

```shell-script
ℹ ✓ built in 1.34s                                                                              20:45:56
✔ Server built in 1366ms                                                                        20:45:56
✔ Generated public .output/public                                                         nitro 20:45:56
ℹ Initializing prerenderer                                                                nitro 20:45:56
ℹ Prerendering 3 initial routes with crawler                                              nitro 20:45:58
  ├─ /200.html (117ms)                                                                     nitro 20:45:58
  ├─ /404.html (117ms)                                                                     nitro 20:45:58
  ├─ / (236ms)                                                                             nitro 20:45:58
  │ └── Error: [500] 
                                                                                           nitro 20:45:58
Errors prerendering:
  ├─ / (236ms)                                                                             nitro 20:45:58
  │ └── Error: [500] 
                                                                                           nitro 20:45:58

 ERROR  Exiting due to prerender errors.                                                         20:45:58
```
```

**Comment by harlan-zw** [comment]
So the issue is that the context is kept after async when using `<script setup>` but not with just `<script>` and setup.

This works (https://stackblitz.com/edit/github-hyndhs-upsuyv?file=app.vue)

```vue
<script setup>
await new Promise((res) => setTimeout(res, 100));
useHead({
  title: 'issue',
});
</script>
```

This doesn't work (https://stackblitz.com/edit/github-hyndhs-kkpbbx?file=app.vue)

```vue
<script>
export default {
  async setup() {
    await new Promise((res) => setTimeout(res, 100));
    useHead({
      title: 'issue',
    });
  },
};
</script>
```

Any ideas @danielroe? Is this a Vue limitation or are we handling these non-setup templates differently?

**Comment by manniL** [comment]
This is a "limitation" of async `setup` functions in vue. See e.g. https://antfu.me/posts/async-with-composition-api from @antfu for a more in-depth info.

**Comment by harlan-zw** [comment]
Nice, thanks for the link :+1: 

Seems like creating a compile-time solution could be feasible but a lot of effort. 

The current error is throwing an error which is good, but it's not exactly accurate. I think we can improve this error message and the linked documentation with examples like this.

> [nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at `https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables`.

**Comment by Ni55aN** [comment]
Okay, it looks like a valid workaround, but the thing is that on version 3.5.0 it works correctly.

Also, in version 3.7.0 `npm run generate` does not throw an error, but has another issue https://github.com/nuxt/nuxt/issues/22763#issuecomment-1702634066 (in fact, in 3.7.1 it isn't reproducible if I use `script setup`)

**Comment by danielroe** [comment]
This _should_ work as we have support in `unctx` for this kind of transform (https://github.com/unjs/unctx/pull/69). So if it has stopped working that is a regression.

**Comment by harlan-zw** [comment]
> This _should_ work as we have support in `unctx` for this kind of transform ([unjs/unctx#69](https://github.com/unjs/unctx/pull/69)). So if accessing _the nuxt instance_ has stopped working that is a regression.
> 
> In the case of `useHead` the issue might be because it's trying to access the vue app instance, which we can't preserve.

This would be a regression then as it's failing on `useNuxtApp()`. See https://stackblitz.com/edit/github-hyndhs-pumnes?file=app.vue

**Comment by peteromano** [comment]
Simpler repro:

```
<script setup lang="ts">    <---------- Works, as expected. Hooray!
const { myLayer } = useAppConfig()
</script>

<script lang="ts">             <---------- Composable context error. :'(
import { useAppConfig } from '#imports'
const { myLayer } = useAppConfig()
</script>

<template>
  <div>
    <h1>Hello World!</h1>
    <pre>asd</pre>
  </div>
</template>
```

I think this worked either way in previous versions, however, as mentioned in comments, it probably _shouldn't_ work without script setup.

This is a well known limitation in Urql as well. "Use functions" (composables, etc.) like useQuery in Urql yield the same type of error.

**Comment by manniL** [comment]
Related: https://github.com/nuxt/nuxt/pull/24784 (revert of https://github.com/nuxt/nuxt/pull/24515)

**Comment by danielroe** [comment]
This should be possible with `defineNuxtComponent`:

```vue
<template>
  <div>hi</div>
</template>

<script>
export default defineNuxtComponent({
  async setup() {
    await new Promise((res) => setTimeout(res, 100));
    useHead({
      title: 'issue',
    });
  },
});
</script>
```
