### ISSUE TITLE
Control hydration to refetch data on client side

### ISSUE THREAD

**Issue by gibkigonzo** [nuxt/nuxt#23072]
### Describe the feature

Is there API that can allow to control hydration state?

For example
```
<script lang="ts" setup>
// 1. SSR => fetch data with 300kb links
const { data } = await useAsyncData(() => fetch300kbData())

// 2. SSR => render page

// 3. SSR => remove data before html is sent to CSR
afterSSRRender(() => {
   data.value = []
})

// 4. CSR => client gets html and page is rendered by browser

// 5. CSR => keep page hydration in pending state
beforeCSRHydration(async () => {
   // 6. CSR => fetch same data that was fetched in SSR
   data.value = await fetch300kbData()
})

// 7. CSR => resolve hydration
</script>
```

It can give performance improvement (for example in CoreWebVitals). Lets say we have page with a lot of links, which needs to be interactive on client side. User will get html that is 300kb lighter and can see content before page is interactive. After data is refetch on client side user can interact with it.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by gibkigonzo** [comment]
It can be done, just need to fetch data with `$fetch` (not useAsyncData)

**Comment by sauravbv** [comment]
@gibkigonzo Can you share any example of how you achieved this? Also did it improve performance?
