### ISSUE TITLE
sharp  package __dirname error

### ISSUE THREAD

**Issue by icai** [nuxt/nuxt#23078]
### Environment

Nuxt project info:

------------------------------
- Operating System: Darwin
- Node Version:     v16.20.0
- Nuxt Version:     3.7.1
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  yarn@1.16.0
- Builder:          webpack
- User Config:      builder, dir, srcDir, env, alias, loading, router, app, css, extendPlugins, plugins, buildModules, modules, i18n, axios, auth, build, serverMiddleware
- Runtime Modules:  @pinia/nuxt@0.4.11, @nuxt-alt/http@1.6.8, @nuxt-alt/auth@2.6.1, client/modules/express.ts
- Build Modules:    @nuxt/typescript-build@3.0.1, ~modules/esbuild.ts
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                                                  11:38:04 AM

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Reproduction

[nitro] [uncaughtException] /Users/terry/xxx/node_modules/sharp/lib/libvips.js:23
const vendorPath = path.join(__dirname, '..', 'vendor', minimumLibvipsVersion, platform());
                             ^

ReferenceError: __dirname is not defined in ES module scope
    at <anonymous> (/Users/terry/xxx/node_modules/sharp/lib/libvips.js:23:30)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)

https://github.com/lovell/sharp/blob/main/lib/libvips.js#L26

### Describe the bug

ReferenceError: __dirname is not defined in ES module scope.

I try to  use
``` build: {
    transpile: ['defu', 'devalue', 'sharp'],
```
, but __dirname and __filename in npm package not  to work.
I found  a lot of these issues, may be provide some configure to handle this question should be better.

https://github.com/webpack/webpack/issues/14072

**Comment by alimozdemir** [comment]
I think this is the same issue [#22958](https://github.com/nuxt/nuxt/issues/22958)

**Comment by danielroe** [comment]
I think https://nuxt.com/docs/guide/concepts/esm#troubleshooting-esm-issues might be relevant here.

**Comment by alimozdemir** [comment]
@danielroe yes it seems like it is relevant, the page is not clear about how to troubleshoot this kind (__dirname) of error and fix it.

**Comment by alimozdemir** [comment]
Here is my reproduction with applicationinsight package.

https://stackblitz.com/edit/nuxt-starter-cdamuw?file=modules%2Fappinsight%2Fserver%2Fmiddleware%2Fappinsight.ts

even if transpile works with nuxt, it does not work with nitro server/middleware.

**Comment by alimozdemir** [comment]
Any news? If it is related to nitro, you can just tell us to open an issue on nitro. So, they can fix it. @danielroe @pi0

**Comment by danielroe** [comment]
Let's track in https://github.com/unjs/nitro/issues/1726.
