### ISSUE TITLE
how to extractCss from document

### ISSUE THREAD

**Issue by daomiaru** [nuxt/nuxt#23081]
### Environment

- Operating System: Darwin
- Node Version:     v18.14.1
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      modules, nitro, routeRules, app, css, build, vite, devtools
- Runtime Modules:  @pinia/nuxt@0.4.11, @nuxtjs/tailwindcss@6.8.0
- Build Modules:    -

### Reproduction

I used tailwind and some third-party tools in my project, and I used global. css to reference their styles. I found that every returned HTML page would load these styles in the form of style tags, which resulted in each HTML file being abnormally large. I hope to extract these css into external style sheets. How to handle this
![image](https://github.com/nuxt/nuxt/assets/52020723/6ba4f9e0-5a2f-4025-bc18-14ce2469ce32)
![image](https://github.com/nuxt/nuxt/assets/52020723/a933e4bc-f0cf-43aa-a80e-2280f11ec165)

### Describe the bug

I tried to use CSS code segmentation in vite, but it didn't work, and it seems that there are no official configuration instructions
![image](https://github.com/nuxt/nuxt/assets/52020723/84da1080-16a8-4488-b0e6-952527c56d9b)

**Comment by danielroe** [comment]
You can set `experimental.inlineSSRStyles` to false:

```ts
export default defineNuxtConfig({
  experimental: {
    inlineSSRStyles: false
  }
})
```
