### ISSUE TITLE
Strange behavior when vue file and directory with the same name exist

### ISSUE THREAD

**Issue by fabon-f** [nuxt/nuxt#23088]
### Environment

Working directory: /home/projects/github-wi7uj1
Nuxt project info:

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.7.1
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-wi7uj1?file=pages%2Findex.vue

### Describe the bug

For example, when both `foo.vue` and `foo/bar.vue` exist under `pages`, accessing `/foo/bar` returns the content of `foo.vue`.

This issue occurs in dev mode (with and without `NuxtLink`), SSR mode via `npm run build`, and SSG via `npm run generate`.

**Comment by learntheropes** [comment]
`foo/index.vue` should solve the issue

**Comment by danielroe** [comment]
This should explain what is going on: https://nuxt.com/docs/guide/directory-structure/pages/#nested-routes.

**Comment by fabon-f** [comment]
I overlooked that document. Thank you for replying.
