### ISSUE TITLE
require is not defined come from dependencies. How to optimise that package to run application.

### ISSUE THREAD

**Issue by vinothkbest** [nuxt/nuxt#23082]
### Environment

Build

### Reproduction

![image](https://github.com/nuxt/nuxt/assets/56819946/c7d8c568-29d7-41c5-807e-073420f6c3ca)

### Describe the bug

![image](https://github.com/nuxt/nuxt/assets/56819946/c02c1239-5beb-4290-88fc-10115be71e9a)

**Comment by danielroe** [comment]
See https://nuxt.com/docs/guide/concepts/esm#troubleshooting-esm-issues.
