### ISSUE TITLE
Dynamic routes on Azure Static Web Apps have stopped functioning since Nuxt 3.5.0 or later.

### ISSUE THREAD

**Issue by lt-tim** [nuxt/nuxt#23089]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.4.0
- Nitro Version:    2.6.3
- Package Manager:  npm@10.0.0
- Builder:          vite
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/lt-tim/nuxt-reproduction

This repository contains 2 nuxt projects, both are the same with the only difference being the nuxt version (labeled by their version)

### Describe the bug

Since Nuxt version 3.5.0 (we've pinpointed this version), dynamic routes have ceased to function correctly on Azure Static Web Apps. When attempting to access a dynamic route, users are being redirected back to its associated index page. For instance:

**/index/{id} → /index/**
And so on...
**Steps to Reproduce:**

Before attempting to reproduce this issue, please make sure to install the swa-cli first.

Clone the repository from https://github.com/lt-tim/nuxt-reproduction.

Navigate to the version you wish to test, either Nuxt 3.4.0 or the latest release (3.7.1).

Build the Nuxt app using the command: swa build.

Deploy the built Nuxt app using the following command, replacing **[ENV]** and **[DEPLOYMENT_TOKEN]** with your specific environment and deployment token, respectively:
4. Deploy the build nuxt app using `swa deploy --env **[ENV]** --deployment-token **[DEPLOYMENT_TOKEN]** --verbose silly`

**Reproduction Outcome:**

Upon testing the links on the site, you will notice that everything functions as expected in Nuxt version 3.4.0. However, dynamic links fail to work as intended in the latest version of Nuxt.

Your attention to this matter would be greatly appreciated in order to resolve this issue.

**Comment by danielroe** [comment]
Would you be able to open this upstream in https://github.com/unjs/nitro ?

**Comment by lt-tim** [comment]
> Would you be able to open this upstream in https://github.com/unjs/nitro ?

done https://github.com/unjs/nitro/issues/1716

**Comment by danielroe** [comment]
Thank you! We'll track this upstream as it's almost certainly an issue with the preset (or nitro configuration).
