### ISSUE TITLE
Nuxt doesn't minify html properly (does not remove line-breaks)

### ISSUE THREAD

**Issue by lazercaveman** [nuxt/nuxt#23085]
### Environment

- Operating System: Darwin
- Node Version:     v16.18.1
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  yarn@3.2.4
- Builder:          vite
- User Config:      app, routeRules, modules, vue, vite, nitro, css, postcss, runtimeConfig
- Runtime Modules:  @pinia/nuxt@0.4.11, @nuxt/devtools@0.8.2, @vueuse/nuxt@10.3.0, nuxt-jsonld@2.0.8
- Build Modules:    -

### Reproduction

`import { fileURLToPath, URL } from 'url';
import svgLoader from 'vite-svg-loader';

export default defineNuxtConfig({
  app: {
    baseURL: process.env.BASE_URL || '/',
    head: {
      htmlAttrs: {
        lang: 'de-DE',
      },
      meta: [
        {
          name: 'viewport',
          content: 'width=device-width, initial-scale=1, user-scalable=no',
        },
        {
          name: 'format-detection',
          content: 'telephone=no',
        },
      ],
      link: [
        {
          rel: 'icon',
          type: 'image/x-icon',
          href: '/favicon.ico',
        },
      ],
    },
  },
  routeRules: {
    '/': { prerender: true },
    '/**': { cors: true },
  },
  modules: [
    '@pinia/nuxt',
    '@nuxt/devtools',
    '@vueuse/nuxt',
    [
      'nuxt-jsonld',
      { disableOptionsAPI: true },
    ],
  ],
  vue: {
    compilerOptions: {
      isCustomElement: tag => tag.startsWith('cookie-banner-component'),
    },
  },
  vite: {
    resolve: {
      alias: {
        '~': fileURLToPath(new URL('./', import.meta.url)),
      },
    },
    plugins: [svgLoader()],
    assetsInclude: ['**/*.mdx'],
  },
  nitro: {
    compressPublicAssets: {
      brotli: false,
      gzip: true,
    },
    storage: {
      redis: {
        driver: 'redis',
        port: process.env.REDIS_CONFIG_PORT,
        host: process.env.REDIS_CONFIG_HOST,
        username: '',
        password: process.env.REDIS_CONFIG_PASSWORD,
        db: 0,
        tls: {},
      },
    },
  },
  css: [
    '~/assets/styles/css/tailwind.css',
    '~/assets/styles/scss/main.scss',
  ],
  postcss: {
    plugins: {
      tailwindcss: {},
      autoprefixer: {},
    },
  },
});
`

### Describe the bug

While using `nuxi build`, nuxt minifies the html as follows,

`<!doctype html>
<html data-n-head-ssr lang="en" data-n-head="%7B%22lang%22:%7B%22ssr%22:%22en%22%7D%7D">
  <head>
    <title>Website</title><meta data-n-head="ssr" charset="utf-8"><meta data-n-head="ssr" name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta data-n-head="ssr" name="description" content="Website"><meta data-n-head="ssr" name="format-detection" content="telephone=no"><link data-n-head="ssr" rel="icon" type="image/x-icon" href="/favicon.ico">`
    
As you can see the line breaks after <!doctype html>, <html>, <head> aren't removed. Why is that? And how do I remove the line breaks? Thanks.

This Problem was mentioned in Nuxt 2 back then as well.

**Comment by Mini-ghost** [comment]
@danielroe 

I have investigated this issue, and below is the HTML generated by executing `nuxi generate playground` with the current version:

```htm
<!DOCTYPE html>
<html >
<head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="preload" as="fetch" crossorigin="anonymous" href="/_payload.json">
<link rel="modulepreload" as="script" crossorigin href="/_nuxt/entry.lirqHv3X.js">
<link rel="prefetch" as="script" crossorigin href="/_nuxt/error-404.tbGoJl1q.js">
<link rel="prefetch" as="script" crossorigin href="/_nuxt/vue.f36acd1f.eXCIzdvm.js">
<link rel="prefetch" as="script" crossorigin href="/_nuxt/error-500.9n_HQChl.js">
<script type="module" src="/_nuxt/entry.lirqHv3X.js" crossorigin></script></head>
<body ><div id="__nuxt"><div> Nuxt 3 Playground </div></div><script type="application/json" id="__NUXT_DATA__" data-ssr="true" data-src="/_payload.json">[{"state":1,"once":3,"_errors":5,"serverRendered":7,"path":8,"prerenderedAt":9},["Reactive",2],{},["Reactive",4],["Set"],["Reactive",6],{},true,"/",1703474852002]</script>
<script>window.__NUXT__={};window.__NUXT__.config={public:{},app:{baseURL:"/",buildAssetsDir:"/_nuxt/",cdnURL:""}}</script></body>
</html>
```

In an attempt to refine the implementation, I adjusted the `renderHTMLDocument` and `joinAttrs` functions in `renderer.ts`. The results are as follows:

```htm
<!DOCTYPE html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="preload" as="fetch" crossorigin="anonymous" href="/_payload.json">
<link rel="modulepreload" as="script" crossorigin href="/_nuxt/entry.HCIDZTxN.js">
<link rel="prefetch" as="script" crossorigin href="/_nuxt/error-404.fb9U4sbQ.js">
<link rel="prefetch" as="script" crossorigin href="/_nuxt/vue.f36acd1f.O0-pTQn_.js">
<link rel="prefetch" as="script" crossorigin href="/_nuxt/error-500.6TmM4WXY.js">
<script type="module" src="/_nuxt/entry.HCIDZTxN.js" crossorigin></script></head><body><div id="__nuxt"><div> Nuxt 3 Playground </div></div><script type="application/json" id="__NUXT_DATA__" data-ssr="true" data-src="/_payload.json">[{"state":1,"once":3,"_errors":5,"serverRendered":7,"path":8,"prerenderedAt":9},["Reactive",2],{},["Reactive",4],["Set"],["Reactive",6],{},true,"/",1703474792485]</script>
<script>window.__NUXT__={};window.__NUXT__.config={public:{},app:{baseURL:"/",buildAssetsDir:"/_nuxt/",cdnURL:""}}</script></body></html>
```

The potential reduction in HTML size is minimal, primarily because the HTML in the `<head>` section is generated by `@unhead/ssr`. I believe this aspect may fall outside the scope of Nuxt's implementation. Beyond that, are there any specific aspects you would like to evaluate?

I plan to open a PR shortly. Please feel free to close it if you determine it may not be beneficial.
