### ISSUE TITLE
Nuxt app is not restarted after an imported file in nuxt.config changes

### ISSUE THREAD

**Issue by julesrx** [nuxt/nuxt#23108]
### Environment

- Operating System: Linux
- Node Version:     v20.6.1
- Nuxt Version:     3.7.1
- CLI Version:      3.8.1
- Nitro Version:    2.6.3
- Package Manager:  pnpm@8.6.12
- Builder:          -
- User Config:      app
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-vsfslu?file=nuxt.config.ts&view=editor

### Describe the bug

Create a `nuxt.config.ts` file that imports from another file.

```ts
import title from './title';

export default defineNuxtConfig({
  app: {
    head: {
      title
    }
  }
});
```

```ts
// title.ts
const title = 'Hello from title.ts';
export default title;
```

When the `title.ts` is updated, the app is not restarted.

### Additional context

I'm aware of [this](https://nuxt.com/docs/guide/directory-structure/nuxt.config#nuxt-config-file) :
> To ensure your configuration is up to date, Nuxt will make a full restart when detecting changes in the main configuration file, the .env, .nuxtignore and .nuxtrc dotfiles.

But should it not also include all the files that the nuxt config imports ?

Also, I couldn't use the [chokidar](https://nuxt.com/docs/api/configuration/nuxt-config#chokidar) to get it to work.

**Comment by julesrx** [comment]
Should probably move this to [nuxt/cli](https://github.com/nuxt/cli)...

**Comment by danielroe** [comment]
Could you try adding the file to `watch`?

```diff
  import title from './title';
  
  export default defineNuxtConfig({
    app: {
      head: {
        title,
      },
    },
+   watch: ['title.ts']
  });
```

**Comment by julesrx** [comment]
This workd thanks.
I though this was watched by a bundler, so that's why I was expecting it to automaticly update.

**Comment by danielroe** [comment]
No, the imports into `nuxt.config` are not watched.

**Comment by manniL** [comment]
@danielroe do you think it'd be possible adding imported files automatically to watch them or are there cases where this might not be desired? 🤔

**Comment by danielroe** [comment]
Tentatively, I think it could be good, although I'm not sure how much of a real need it solves.

For anyone else looking at this, we use https://github.com/unjs/jiti to load the config. We would also need (separately, I think?) to crawl the file + all imported dependencies (and their dependencies, etc.) to build a graph of files to watch, and then register these - and reupdate them on every reload.
