### ISSUE TITLE
Nuxt3.7.1 upgrade production build troubles

### ISSUE THREAD

**Issue by LorenzoRottigni** [nuxt/nuxt#23105]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.13.0
- Nuxt Version:     3.7.1
- CLI Version:      3.8.1
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

I tried to create a reproduction but it's crashing during build phase with different (awful) errors:

https://stackblitz.com/edit/github-djkpzr?file=app.vue,components%2FJupyterReader.vue,package.json

### Describe the bug

I am experiencing troubles with a nodejs module named "ipynb2html" during production build phase after upgrading to 3.7.1. It works in development mode (yarn dev) but it breaks the production build with reported errors.

I already contacted the ipynb2html package owner via mail to make him aware about this problem within the latest version of nuxt3 framework.

I think that the problem isn't directly related to nuxt3 update since is thrown by RollupJS, you updated its version within the latest update? :) 

I'm looking for some suggestion or workaround... Thanks for your help.

### Additional context

Since it correctly works inside dev environment I think that errors are due to some stricter checks of rollupjs introduced within the latest releases.

I also see that it's attempting to import files using query ?commonjs-external, maybe something changed about these kind of external declarations during build phase?

### Logs

```shell-script
`[nitro 11:58:21 AM]  ERROR  RollupError: Could not resolve "./markdownRenderer" from "./markdownRenderer?commonjs-external"
undefined
[nuxt] build:done: 4.775s                                                                       11:58:21 AM
 ERROR  Could not resolve "./markdownRenderer" from "./markdownRenderer?commonjs-external"      11:58:21 AM
  at error (node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
  at ModuleLoader.handleInvalidResolvedId (node_modules/rollup/dist/es/shared/node-entry.js:24855:24)
  at node_modules/rollup/dist/es/shared/node-entry.js:24817:26 
 ERROR  Could not resolve "./markdownRenderer" from "./markdownRenderer?commonjs-external"      11:58:21 AM
error Command failed with exit code 1.`
```

**Comment by jawngee** [comment]
Same issue.  Happens during nitro server build phase except it's for vue itself for me:

``Could not resolve "./dist/vue.cjs.prod.js" from "./dist/vue.cjs.prod.js?commonjs-external"``

**Comment by LorenzoRottigni** [comment]
Do you have any additional information to what I have listed?

**Comment by jawngee** [comment]
It was operator error on my part, hence I deleted my comment.  I had aliases setup in my `nuxt.config.ts`.

**Comment by jawngee** [comment]
I have gotten this before and my solution (which tripped me up this time) was:

```
export default defineNuxtConfig({
  alias:
    process.env.NODE_ENV === "production"
      ? {
          "@unhead/vue": require.resolve(join(currentDir, "./node_modules/@unhead/vue")),
        }
      : {},
});
```

**Comment by jawngee** [comment]
See: https://github.com/nuxt/nuxt/issues/20152

**Comment by LorenzoRottigni** [comment]
Unfortunately that's not my case, I am referring to Nuxt3 and ipynb2html documentation guidelines without any strange acrobatics...

**Comment by jawngee** [comment]
It's the exact same issue just a different module.  If you add an alias as above or as in the linked comment, but changed for your specific case, it might be the workaround you are looking for.

**Comment by LorenzoRottigni** [comment]
Oh, I understand what you mean sorry, I tough it was your implementation the problem. Let me try and I let you know, thanks 😄

**Comment by LorenzoRottigni** [comment]
I think my situation is quite different because module ipynb2html is attempting to import an internal module, not an external npm package.

**Comment by LorenzoRottigni** [comment]
You just had to grant correct imports from @unhead/vue

**Comment by LorenzoRottigni** [comment]
Also after updating to nuxt v3.7.3 the issue persists:

```
 ERROR  RollupError: Could not resolve "./markdownRenderer" from "./markdownRenderer?commonjs-external"              nitro 7:11:52 PM
undefined
[nuxt] build:done: 3.864s                                                                                                  7:11:52 PM
 ERROR  Could not resolve "./markdownRenderer" from "./markdownRenderer?commonjs-external"                                 7:11:52 PM
  at error (node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
  at ModuleLoader.handleInvalidResolvedId (node_modules/rollup/dist/es/shared/node-entry.js:24855:24)
  at node_modules/rollup/dist/es/shared/node-entry.js:24817:26 
 ERROR  Could not resolve "./markdownRenderer" from "./markdownRenderer?commonjs-external"  
```

**Comment by LorenzoRottigni** [comment]
I found a workaround for this issue by using dynamic imports (await import('ipynb2html')). I believe there is still a small bug in the Rollup build, but this issue is now resolved on my end.
