### ISSUE TITLE
Auto imports under server/ are not as expected when srcDir is changed

### ISSUE THREAD

**Issue by sdr0x07b6** [nuxt/nuxt#23101]
### Environment

```sh
% npx nuxt info

------------------------------
- Operating System: Darwin
- Node Version:     v18.14.2
- Nuxt Version:     3.7.1
- CLI Version:      3.8.1
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, srcDir
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Reproduction

Here is the minimum project to reproduce this.
https://github.com/sdr0x07b6/nuxt371_auto-imports

### Describe the bug

Set `{ srcDir: 'src/' }` in nuxt.config.ts.
```ts
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  srcDir: 'src/',
})
```

Other files like this one were created.

`src/@types/global.d.ts`
```ts
export {};

declare global {
  type MyString = string;
}
```

`src/utils/index.ts`
```ts
export const myFunction = (): string => {
  return 'myFunction';
};
```

`server/api/index.ts`
```ts
export default defineEventHandler(async (event) => {
  // const string: MyString = myFunction();

  return 'server/api/';
});
```

`src/server/api/index.ts`
```ts
export default defineEventHandler(async (event) => {
  // const string: MyString = myFunction();

  return 'src/server/api/';
});
```

`src/pages/index.vue`
```vue
<script lang="ts" setup>
const state: {
  string: MyString
} = reactive({
  string: myFunction(),
});
</script>

<template>
  <div>
    string: "{{ state.string }}"
  </div>
</template>
```

---

## Results

- `src/pages/index.vue`
  - No problem.
  - The `MyString` type is recognized.
  - `myFunction()` can be executed.

- `src/server/api/index.ts`
  - The built-in function `defineEventHandler()` cannot be auto imported.
  - The `MyString` type is not recognized.
  - Cannot execute `myFunction()`.
  - Commented out because it is inaccessible due to an error.

- `server/api/index.ts`
  - The `src/server/` is correct in the configuration, but because of the error as shown above, I created this route as a trial.
  - `defineEventHandler()` is auto imported.
  - The `MyString` type is recognized.
  - Cannot execute `myFunction()`.
  - Commented out because it is inaccessible due to an error.

![Screenshot - 2023-09-10 06 30 45](https://github.com/nuxt/nuxt/assets/1102138/8a2890bf-7bb0-492a-b8e2-dd7f7af305a7)

- Access http://localhost:3000/ and you will see "myFunction".
- Access http://localhost:3000/api and you will see "src/server/api/".

### Summary

- No problem in `pages/`, only under `server/`, which is not what I expected.
- Auto imports are not available in `src/server/`, which should be available, but are almost available in `server/`.
  - However, auto imports in `src/server/utils/` are also invalid for `server/`.
-  Except for the utils functions that cannot be auto imported, I am able to access `src/server/` at http://localhost:3000/api. The `defineEventHandler()` has an error with a red wavy line in the VSCode editor, but it seems to work.

## Expected results

Since `{ srcDir: 'src/' }` is set, we expect auto imports to be enabled under `src/server/`, including `utils/` and global type definitions.

## What we did to improve

- Delete Vite cache
- Restart VSCode
- System reboot

### Additional context

I have a v3.4.2 project in hand. It has the same `{ srcDir: 'src/' }`, contains many files, and is not a small project, but I have not seen any errors related to auto imports.

**Comment by DamianGlowala** [comment]
I can confirm this happens for me to. Anything auto-imported within the `server/` dir cannot be found by TS when I set up `srcDir: "src"`.

**Comment by sdr0x07b6** [comment]
Also, the `interface` in `*.d.ts` that is `declared global` also causes an error in the editor saying it cannot be found.
These are all working, just not recognized by the editor.

However, many things are displayed as errors, completion does not work, and the DX that Nuxt values so much is destroyed.

**Comment by danielroe** [comment]
You need to update your `~/src/server/tsconfig.json` (https://github.com/sdr0x07b6/nuxt371_auto-imports/blob/master/src/server/tsconfig.json) to reflect its new location:

```diff
  {
-   "extends": "../.nuxt/tsconfig.server.json"
+   "extends": "../../.nuxt/tsconfig.server.json"
  }
```

<img width="1010" alt="CleanShot 2023-10-23 at 20 50 56@2x" src="https://github.com/nuxt/nuxt/assets/28706372/77b91733-abe8-4d14-ad38-c336eccbc0ce">

**Comment by sdr0x07b6** [comment]
It worked! Thanks.

**Comment by katerlouis** [comment]
Just ran into the same issue; 
Is there really no way of extending with an absolute path or alias? Nuxt does so many things out of the box that its kind of frustrating to search for errors like this. 

I wanted to add a warning-box to the [api docs](https://nuxt.com/docs/api/nuxt-config#srcdir), but don't know how. Clicking "edit this page" reveals an md file with `<!-- GENERATED_CONFIG_DOCS -->` – @danielroe could you tell me how to edit the section? I'd like to contribute, even if its just enhancing the docs for noobs like me :D

(Maybe the [Get Started: Server](https://nuxt.com/docs/getting-started/server) section should also mention this?)

**Comment by danielroe** [comment]
Nuxt configuration file docs are edited directly in `@nuxt/schema`:

https://github.com/nuxt/nuxt/blob/37d24eed7dce72b3f7e4a983de1ab38ddaa72739/packages/schema/src/config/common.ts#L59-L92
