### ISSUE TITLE
use of string interpolation in vue component used by addLayout gives error 

### ISSUE THREAD

**Issue by shivanshtalwar** [nuxt/nuxt#23118]
### Environment

Nuxi 3.3.0-27973124.d4697401                                                                                                            13:37:58
                                                                                                                                        13:37:58
RootDir: /Users/utopia/Projects/education-sites/template-1                                                                              13:37:58
Nuxt project info: (copied to clipboard)                                                                                                13:37:58

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.3.0-27973124.d4697401`
- Nitro Version:    `2.6.3`
- Package Manager:  `npm@6.14.15`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                                             13:37:58

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Reproduction

```vue
<script setup lang="ts">
// myModule/src/runtime/layouts/default.vue

const languageId = useState<any>("languageId");
const { data: headerInfo } = await useAsyncData<any>(
  "headerInfo",
  async () => {
    const query = `+brandsHeader.name:"header" +languageId:"${languageId.value}"`; // removing ${languageId.value} fixes the problem
    const data: any = await $fetch("/api/cms/content", {
      method: "POST",
      body: {
        contentType: "brandsHeader",
        query,
      },
    });
    return data.data;
  },
  {
    watch: [languageId],
  }
);
</script>
```
```ts
//myModule/src/runtime/module.ts
async setup(options, nuxt) {
    addLayout(
      {
        filename: `default.vue`,
        write: true,
        src: resolver.resolve("./runtime/layouts/default.vue"),
      },
      `template-1-layout`
    );
}
```

### Describe the bug

use of string interpolation gives 
```
 ERROR  Error compiling template:  {                                                                                                    13:35:15
  filename: 'default.vue',
  write: true,
  src: '/Projects/education-sites/template-1/src/runtime/layouts/default.vue',
  dst: 'Projects/education-sites/template-1/playground/.nuxt/default.vue'
}


 ERROR  languageId is not defined                                                                                                       13:35:15
```
whereas when i remove string interpolation to string concatination it works without problem

**Comment by manniL** [comment]
Does the same happen when not using `useState` but a simple variable + string interpolation? 🤔

**Comment by shivanshtalwar** [comment]
yes it also happens with simple variable 
unfortunately i can't provide the whole code of module  as public since it is oraganization's code
but what i can say is you can reproduce by creating a nuxt module and using `addLayout` and try to have string interpolation in asyncData for instance and you can reproduce this issue

**Comment by manniL** [comment]
>  unfortunately i can't provide the whole code of module as public since it is oraganization's code

I'm more than sure that it is possible to provide a very simple example without involving org/company code, doing exactly what you've described later on ☺️ :

> but what i can say is you can reproduce by creating a nuxt module and using addLayout and try to have string interpolation in asyncData for instance and you can reproduce this issue
