### ISSUE TITLE
Nuxt 3 SSR doesn't work

### ISSUE THREAD

**Issue by razmatinyan** [nuxt/nuxt#23115]
### Discussed in https://github.com/nuxt/nuxt/discussions/23106

<div type='discussions-op-text'>

<sup>Originally posted by **razmatinyan** September 10, 2023</sup>

### Describe the bug

I have an issue with my Nuxt 3 App. It is not rendering is SSR mode. When I look at page in **`"View page source"`** mode, it is not rendered in SSR. In main `"__nuxt"` block I got empty `<div id="__nuxt"></div>` . Here is my `package.json` and `nuxt.config.ts` files. Does anyone know what is going on?

### Full repository
[https://github.com/razmatinyan/nuxt-link-shortener](https://github.com/razmatinyan/nuxt-link-shortener)

**nuxt.config.ts**

```javascript
export default defineNuxtConfig({
	ssr: true,
	devtools: { enabled: true },
	modules: ['@nuxt/ui', '@nuxtjs/supabase'],
	ui: {
		global: true,
		icons: ['heroicons'],
	},
	colorMode: {
		preference: 'dark',
	},
	css: ['~/assets/fonts.css'],
	alias: {
		assets: '/<rootDir>/assets',
	},
	supabase: {
		redirectOptions: {
			login: '/',
			callback: '/',
			exclude: [],
		},
	},
	runtimeConfig: {
		public: {
			DOMAIN: process.env.DOMAIN ?? 'http://127.0.0.1:3000/',
		},
	},
});

``` 

**package.json**
```javascript
{
  "name": "nuxt-app",
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/devtools": "latest",
    "@nuxtjs/supabase": "^1.1.0",
    "nuxt": "^3.7.1"
  },
  "dependencies": {
    "@iconify-json/heroicons": "^1.1.12",
    "@nuxt/ui": "^2.8.1",
    "crypto": "^1.0.1"
  }
}

``` 

</div>

**Comment by manniL** [comment]
Let's keep this [as a discussion](https://github.com/nuxt/nuxt/discussions/23106) as this is most likely not a nuxt bug.
