### ISSUE TITLE
Incorrect peer dependency "@csstools/css-tokenizer@^2.2.0"

### ISSUE THREAD

**Issue by ckhatton-transreport** [nuxt/nuxt#23117]
### Environment

```text
  System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
    Memory: 74.94 MB / 16.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 20.2.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.0 - /opt/homebrew/bin/npm
    pnpm: 7.29.1 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 116.0.5845.179
    Edge: 113.0.1774.57
    Safari: 16.5.1
  npmPackages:
    nuxt: ^2.17.1 => 2.17.1 
```

### Reproduction

`yarn install --check-files`

### Describe the bug

When `yarn` does an install or checks the files, it reports:

> "nuxt > @nuxt/webpack > postcss-preset-env > postcss-custom-media > @csstools/cascade-layer-name-parser@1.0.4" has incorrect peer dependency "@csstools/css-tokenizer@^2.2.0"

### Logs

```shell-script
❯ yarn install --check-files
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "aws-amplify > @aws-amplify/core > react-native-url-polyfill@1.3.0" has unmet peer dependency "react-native@*".
warning "aws-amplify > @aws-amplify/analytics > @aws-sdk/client-firehose > @aws-sdk/middleware-retry > react-native-get-random-values@1.9.0" has unmet peer dependency "react-native@>=0.56".
warning "nuxt > @nuxt/webpack > postcss-preset-env > postcss-custom-media > @csstools/cascade-layer-name-parser@1.0.4" has incorrect peer dependency "@csstools/css-tokenizer@^2.2.0".
warning Workspaces can only be enabled in private projects.
[4/4] 🔨  Building fresh packages...
✨  Done in 8.76s.
```

**Comment by danielroe** [comment]
This seems like an issue with the postcss preset and not with Nuxt.

**Comment by romainmenke** [comment]
Installing `postcss-preset-env` works just fine.

This is a yarn issue : https://github.com/yarnpkg/yarn/issues/4986

We already try to help users of yarn as much as possible by always bumping the version of each package after any dependency changes but given that `postcss-preset-env` is a collection of plugins that was historically created by multiple authors we don't have homogenous publishing access across the current maintainers. I can not release a new version of `postcss-custom-media` to keep `yarn` happy. I will ask other maintainers if they can release this.

But ultimately this is and will remain a `yarn` issue.

**Comment by romainmenke** [comment]
No blame was interpreted :)

**Comment by ckhatton-transreport** [comment]
Thank you for looking into this one guys, I appreciated your time 👍
