### ISSUE TITLE
Cannot add template inside `pages:extend` hook

### ISSUE THREAD

**Issue by HigherOrderLogic** [nuxt/nuxt#23128]
### Environment

Stackblitz

### Reproduction

https://stackblitz.com/edit/github-yuxp6m

### Describe the bug

Template added inside `extendPages` is not generated.
![image](https://github.com/nuxt/nuxt/assets/73709188/040b22cd-c475-467b-bd71-4877ebb330dd)
As you can see from the image, the templates have already been generated before the `pages:extend` hook is called.

**Comment by danielroe** [comment]
I don't consider this a bug, more that (as you have seen) it's too late in the lifecycle to add a template at this point.

You could consider implementing in a number of different ways, including hooking into `app:templates`.

**Comment by HigherOrderLogic** [comment]
> I don't consider this a bug, more that (as you have seen) it's too late in the lifecycle to add a template at this point.
> 
> You could consider implementing in a number of different ways, including hooking into `app:templates`.

I need to access the pages data inside the `pages:extend`hook so I don't think there's any other feasible place to do this.

**Comment by danielroe** [comment]
Maybe you could explain more about your use case then?

**Comment by HigherOrderLogic** [comment]
> Maybe you could explain more about your use case then?

I'm trying to generate middlewares for page, kinda similar to [SvelteKit's param matching](https://kit.svelte.dev/docs/advanced-routing#matching).

The code need the page's file name to decide which validator it should apply to a page inside the middleware, and then the module modify the page's URL to normal URL (eg: `[id=number].vue` will be /`idnumber` when generated by Nuxt, so I need to modify it to `/id`.)

**Comment by danielroe** [comment]
I think you probably want a shared context outside the pages, and then you can call the `updateTemplates` composable to refresh the generated file.

**Comment by HigherOrderLogic** [comment]
> I think you probably want a shared context outside the pages, and then you can call the `updateTemplates` composable to refresh the generated file.

Calling `await updateTemplates()` inside `extendPages` doesn't have any effect either.

**Comment by HigherOrderLogic** [comment]
So what can I do (maybe open a PR?) to resolve this issue?

**Comment by danielroe** [comment]
If you can identify the issue, then that would be great.

**Comment by B3nten** [comment]
I've managed to reproduce this, it's fairly simple. If the pages directory exists but is empty things work fine. Upon adding a route (`index.vue`), changes made to templates no longer appear in the final output. 

```typescript
import { addTemplate, defineNuxtModule, updateTemplates } from "nuxt/kit";

export default defineNuxtModule({
  meta: { name: "reproduction" },
  setup(_, nuxt) {
    const routes = { value: "Initial value." };
    addTemplate({
      filename: "reproduction.json",
      getContents: () => JSON.stringify(routes),
      dst: "#build/reproduction.json",
    });
    nuxt.hook("pages:extend", async () => {
      routes.value = "Modified value from pages:extend hook.";
			await updateTemplates();
    });
  },
});
```

With an empty pages directory the above module works as expected. As soon as I add `index.vue` (or any route) and render out a div, even without `NuxtPage` in `App.vue` it no longer works.

I'll try to find the underlying issue.

**Comment by B3nten** [comment]
So with an empty pages directory, the Pages module ends up calling `await nuxt.callHook('pages:extend', pages)` during its `setup()` phase. Thus why it worked without any files in `pages` dir.

With files present it doesn't call `pages:extend` until it compiles it's template. By then it's too late to modify an external context value because your template has already been written to the vfs.

```ts
    addTemplate({
      filename: 'routes.mjs',
      async getContents () {
        const pages = await resolvePagesRoutes()
        await nuxt.callHook('pages:extend', pages) // called after templates have been parsed.
        const { routes, imports } = normalizeRoutes(pages)
        return [...imports, `export default ${routes}`].join('\n')
      }
    })
```

You also cannot call `updateTemplates()` in `pages:extend` because it's a wrapper for calling `builder::generateApp`, which is only registered by the builder after `generateApp()` returns! Thus you have to call `updateTemplates()` in `build:before()` which generates the app a second time. I'm not sure the implications of doing this.

@danielroe I think this issue can probably be closed, and a new feature request opened to either move the `pages:extend` hook call out of the `addTemplate()` call, or to export `resolvePagesRoutes` for use in modules.

**Comment by HigherOrderLogic** [comment]
> ... Thus you have to call updateTemplates() in build:before() which generates the app a second time

Thanks for your solution, it works for me.

> ... or to export resolvePagesRoutes for use in modules

Imo this isn't feasible since this is meant to be called by the Nuxt app to generate pages, not by the users themselves.

**Comment by B3nten** [comment]
> The above solution seems to work only in dev for me, not in production build.

Right, during a build you can't trigger a rebuild by calling `builder:generateApp` (I assume).

> Imo this isn't feasible since this is meant to be called by the Nuxt app to generate pages, not by the users themselves.

I think this is potentially the only solution, as we need to execute our template building before the pages module executes. Exporting it from nuxt/kit makes sense (imo) as it's for module utilities.

**Comment by localusercamp** [comment]
I encountered the same issue.
I want to generate pages via module and add them via `extendPages()`.
I simply can not do that because all templates are resolved after `"pages:extend"` fired (as i can see).

**Comment by danielroe** [comment]
This seems to be working fine: https://stackblitz.com/edit/github-zcarjt?file=modules/test.ts.

To avoid these order issues, you should create a template outside of the hook, and you can trigger updating its contents later on.
