### ISSUE TITLE
[Bug] Plugin Registration Order is not deterministic when using layers

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [nuxt/nuxt#23123]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.7.1
- CLI Version:      3.8.1
- Nitro Version:    2.6.3
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      extends
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-g42wkd?file=nuxt.config.ts

### Describe the bug

The order of plugin execution is not correct when using layers. Plugins that are defined in lower layers execute after plugins defined in higher layers. This causes incorrect behavior when a plugin override is necessary. In the provided repo a use case of overriding the same entity from a higher level is not possible due to this issue.

**Comment by AndrewBogdanovTSS** [comment]
Yes, when using auto-imported plugins it seems to work as expected
https://stackblitz.com/edit/nuxt-starter-mofheb?file=nuxt.config.ts
isn't it ironic? :)

**Comment by AndrewBogdanovTSS** [comment]
But it feels counter-intuitive, I deliberately provided an example of a custom component auto import. That one is working correctly, isn't it? So then why plugins should behave differently when manually defined?
Btw, what is c12?

**Comment by userquin** [comment]
A workaround can be sorting the plugins using `app:resolve`  nuxt hook.
