### ISSUE TITLE
niro > routeRules > cache > getKey lost in the process of delivery

### ISSUE THREAD

**Issue by William-WFC** [nuxt/nuxt#23139]
### Environment

- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.7.0
- CLI Version:      3.7.2
- Nitro Version:    2.6.2
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      nitro
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-v6wnbq?file=nuxt.config.ts

### Describe the bug

I see getKey in nitro document, but in nuxt project the getKey is invalid
![image](https://github.com/nuxt/nuxt/assets/17450339/c04e55b0-2e5c-4fcd-8265-2852e27825e3)
![image](https://github.com/nuxt/nuxt/assets/17450339/3143644f-14a7-4eb7-92ec-d9f14bb495a7)

as in my reproduction, the cache file in .nuxt/cache/nitro/routes/my_test should be hhhiii.json, as configured in nuxt.config.ts.
but actually it's index.il7asoJjJE.json

I guess the getKey is important in nuxt project for cache control, so please fix this problem as soon as possible, thanks !!!

**Comment by danielroe** [comment]
Everything in your nuxt.config needs to be serialisable, so you can't pass functions there, which is why TS is disallowing it.

**Comment by William-WFC** [comment]
So how to contro route cache only by route pathname and not distinguishable by fragment

**Comment by danielroe** [comment]
You can use `defineCachedEventHandler` or use a Nitro plugin to set the route rules.

**Comment by William-WFC** [comment]
```
// Cache an API handler
export default cachedEventHandler((event) => {
  // My event handler
}, options);
```
how to use cachedEventHandler only set cache options on second parameter, and not fix default event handler

**Comment by artm4r** [comment]
> You can use `defineCachedEventHandler` or use a Nitro plugin to set the route rules.

I also can't find a way to set Route Rules inside of plugin. Maybe you can give an advice?

**Comment by Lewwiss** [comment]
> > You can use `defineCachedEventHandler` or use a Nitro plugin to set the route rules.
> 
> I also can't find a way to set Route Rules inside of plugin. Maybe you can give an advice?

Hey I had the same issue, this fix works https://github.com/nitrojs/nitro/issues/1048#issuecomment-2379420935
