### ISSUE TITLE
Rewrite query before SSR render

### ISSUE THREAD

**Issue by suningkooboo** [nuxt/nuxt#23136]
### Describe the feature

Want to remove tracking URL query like utm_source, utm_campaign before SSR render, especially before routeRules cache handling so the cache key not include these queries.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
I think you could probably do this in a Nitro middleware.
