### ISSUE TITLE
RouteRules about nuxt.config in nuxt3

### ISSUE THREAD

**Issue by Maxbsy** [nuxt/nuxt#23140]
### Describe the feature

In nuxt.config.js in nuxt2 I use this
Document address [https://www.nuxtjs.cn/faq/http-proxy](url)
`proxy: {
    "/*.txt": "https://example.com",
  },
`
But using this in nuxt3 does not take effect
` nitro: {
    routeRules: {
      '/**.txt': {
        proxy: 'https://example.com/**.txt'
      },
    }
  },`
Can this feature be made compatible in the future?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Let's track in unjs/nitro#1717. This is a nitro question.
