### ISSUE TITLE
nuxt3 ssg

### ISSUE THREAD

**Issue by zbk-it** [nuxt/nuxt#23144]
How to not write the data retrieved by the server to HTML (<script type="application/JSON" id="__NUXT-DATA__" data ssr="true">xxxx</script>) during SSG? This data can be removed?

**Comment by danielroe** [comment]
No, this is needed by Nuxt.

This is also not the best way to ask questions - try opening a GitHub Discussion or joining our Discord - https://discord.nuxtjs.org.

**Comment by zbk-it** [comment]
Is this data the entire website, the current page, or the current spa
