### ISSUE TITLE
Query parameters with ssr response

### ISSUE THREAD

**Issue by sauravbv** [nuxt/nuxt#23153]
### Environment

Operating System: Linux
Node Version: v16.20.0
Nuxt Version: 3.6.0
Nitro Version: 2.5.1
Package Manager: yarn@1.22.19
Builder: -
User Config: -
Runtime Modules: -
Build Modules: -

### Reproduction

[Stackblitz demo with query parameter](https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz?file=pages%2Findex.vue)
https://kkvixxbxpgithub-4igf--3000--7259293c.local-credentialless.webcontainer.io/?query1=hello

Notice the query parameters are part of the NUXT_DATA script
<img width="797" alt="image" src="https://github.com/nuxt/nuxt/assets/41701284/a77c3ed0-b7c2-4a45-a350-48dc2de0741c">

### Describe the bug

I am using a proxy cache server to add some query parameters before a request is sent to nuxt server. These query parameters are being returned in the NUXT DATA once I get SSR response from the nuxt server. 
These query parameters are then added to the initial URL request.

For example: 
`xyz/page-1` -> proxy cache server
proxy server adds some query parameters which is used for data fetching in `useAsyncData` in nuxt server. The request URL to the nuxt server will now be something like `nuxt-server-endpoint/?domain=xyz&path=page-1` 
When the request is forwarded back to the client from the proxy server, the URL is updated to `xyz/?domain=xyz&path=page-1`

This started happening after `nuxt 3.6.0` upgrade. 
Were there any changes related to query parameters handling in `v3.6.0` as this is not the case till `v3.5.3` as I tested

**Comment by sauravbv** [comment]
Reproduction
[Stackblitz demo with query parameter](https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz?file=pages%2Findex.vue)
https://kkvixxbxpgithub-4igf--3000--7259293c.local-credentialless.webcontainer.io/?query1=hello

Notice the query parameters are part of the NUXT_DATA script, this wasn't the case till `v3.5.4`
![image](https://github.com/nuxt/nuxt/assets/41701284/124ff0f5-634f-4746-96a2-ca57620aa2af)

**Comment by danielroe** [comment]
Yes, this is a feature, implemented in https://github.com/nuxt/nuxt/pull/21408. You can control this by setting `nuxtApp.payload.path` to a different value.

Closing as I don't think this is a bug, but feel free to let me know if you think it is.

**Comment by sauravbv** [comment]
This solved my issue.
Thanks @danielroe

**Comment by AndrewBogdanovTSS** [comment]
@sauravbv can you share how exactly you populated `nuxtApp.payload.path` ?

**Comment by AndrewBogdanovTSS** [comment]
But why not doing it globally in nuxt.config.ts or in the plugin?

**Comment by sauravbv** [comment]
Have different pages, in some need the query params. I have also noticed the response size has increased after upgrading to nuxt 3.7 by almost  30%. Anyone has an idea on why is this ?

**Comment by felipealpino** [comment]
I experienced a similar issue recently. It turns out that my CloudFront setup was filtering out my query parameters, which meant that when I attempted to access the route, any query parameters not explicitly listed in my CloudFront configuration were being dropped.
I managed to resolve this issue by integrating the following code snippet into all of my layouts:


```javascript
await useAsyncData('data', 
	async (nuxtApp) => {
		delete nuxtApp?.payload?.path;
	}
);
```

**Comment by AbelMakihara** [comment]
I got the same question,but nuxt.com's nuxt_data is as below.
![QQ_1724669749295](https://github.com/user-attachments/assets/6cb306ca-162c-4391-a32e-95d528e08682)
Anyone knows how to change the path?(manually delete param?) and how to set data-src?
What's the diffenence between data-src json and nuxt_data?

**Comment by namthanhtran** [comment]
i have a bug:
First enter: http://localhost:3000/page-1?abc=1
And i remove query, then url: "http://localhost:3000/page-1"
But when i enter, page mounted and url auto append query ?abc=1
Result: "http://localhost:3000/page-1?abc=1"

**Comment by badihi** [comment]
This feature will make caching pages with query string, that must be cached without respecting query strings impossible, as the url will always be changed to query strings that are stored in cache.
Honestly, I did not get the point of the feature at all (rendering without throwing 404?!)
I would be nice to add an option to prevent this behavior, or remove it all together if it does not make much value.
@danielroe
