### ISSUE TITLE
🐞 Type issues with custom fetch

### ISSUE THREAD

**Issue by jd-solanki** [nuxt/nuxt#23154]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.7.1`
- CLI Version:      `3.8.3`
- Nitro Version:    `2.6.3`
- Package Manager:  `pnpm@8.6.12`
- Builder:          `-`
- User Config:      `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/jd-solanki/playgrounds/tree/custom-fetch-nuxt-issues

> **NOTE**
> Watch out for branch

### Describe the bug

Hi 👋🏻 

Just like everyone I also want to define custom fetch and followed the codesandbox example. Later I discovered that I am facing two issues ATM that I wasn't facing when using `useFetch`.

1. With custom fetch (same code from example) We don't get auto completion for API endpoint with custom fetch
2. Type error when defining default value for data

**Comment by danielroe** [comment]
With custom fetch like you've provided, I don't think Nuxt _can_ reasonably provide auto-completion. You've provided a custom baseURL of `/api/`, for example, meaning that Nuxt would need to perform complicated string manipulation, so `/api/test` becomes auto-completed to `/test`.

If you just want to replicate existing types, you can do this:

```diff
- export function useCustomFetch<T> (url: 
+ export const useCustomFetch: typeof useFetch = function useCustomFetch<T> (url: 
```

The other issue with default is that you are not returning an object but _void_. This is TS rightly complaining:

```diff
  const { data } = await useCustomFetch<Record<string, any>>('/hello', {
-   default: () => {},
+   default: () => ({}),
  })
```

**Comment by BarishNamazov** [comment]
Hi @jd-solanki, sorry for bumping on a closed issue — I had the same problem so found this post. I got around it by doing a bit of type-gymnastics. It doesn't look beautiful, but you can put the type declarations on a different file and keep the custom wrapper on its file to focus on the implementation. Check out here: https://barish.me/blog/nuxt-usefetch/
