### ISSUE TITLE
[Nuxt 3.7] Nuxt's dev server is no longer compatible with visual studio code's remote SSH extension

### ISSUE THREAD

**Issue by jpleclerc** [nuxt/nuxt#23159]
### Environment

Local VSCode is on Windows 11
Remote VSCode is on Ubuntu

Nuxt version is 3.7

### Reproduction

- Connect a visual studio code instance to a remote Nuxt 3.7 project using VSCode's 'Remote - SSH' extension. In my case the local VSCode runs on windows and remote runs Ubuntu
- Start the dev server `nuxt dev`
- Ensure that the port is forwarded
![image](https://github.com/nuxt/nuxt/assets/1129404/c0ae26fa-7f3d-4c9a-a929-b096a8b1c830)
- Going to localhost:3000 hangs

### Describe the bug

It is no longer possible to test a Nuxt 3.7 application using VSCode's Remote SSH extension because the dev server (localhost:3000) hangs forever. Opening the app on the remote computer works fine.

**Comment by danielroe** [comment]
Is there any chance you are using VSCode Insiders?

**Comment by jpleclerc** [comment]
@danielroe Not using VSCode Insiders. Going back to Nuxt 3.6 works fine.

I kept looking around and found this issue: https://github.com/nuxt/cli/issues/118 and it seems related.

Using `nuxt dev --host 127.0.0.1` seems to be a workaround to the problem.

**Comment by danielroe** [comment]
Okay, if it's the same issue you're experiencing, let's close the issue here and track there.

**Comment by jpleclerc** [comment]
For future reference, I tried with VSCode insider, the request hits the server but is returning these errors:

![image](https://github.com/nuxt/nuxt/assets/1129404/3f75b87f-4a9a-4f2a-9667-d396212501eb)

Maybe that's also something worth looking into.
