### ISSUE TITLE
Layouts Auto Import

### ISSUE THREAD

**Issue by NelminDev** [nuxt/nuxt#23160]
### Describe the feature

Hello! I just found out that there is no Auto Import in the layouts folder so I thought I would create an Issue.

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

### Reproduction
1. Create a new Nuxt App.
2. Add a library like Nuxt UI.
3. Create the layouts folder
4. Add layout for example: test.vue
5. Add the template tag.
6. Try using a Nuxt UI Component or any other Component in the layout.

**Comment by danielroe** [comment]
What do you mean?

**Comment by NelminDev** [comment]
When I have a layout like layouts/custom.vue components from nuxt ui or other librarys/own components arent auto imported

**Comment by dargmuesli** [comment]
They should be. Could you provide a minimal reproduction?

**Comment by NelminDev** [comment]
Edited my original message

**Comment by dargmuesli** [comment]
Thank you

> Would you be able to provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

Using that link in the previous message by @github-actions would ensure that it's really a clean and reproducible state, but your instructions might just be enough

**Comment by danielroe** [comment]
Reproduction of auto-imports working fine: https://stackblitz.com/edit/github-yq3di6. Would you modify it until the error occurs? 🙏

**Comment by NelminDev** [comment]
Okay, modified it. [Stackblitz](https://stackblitz.com/edit/github-yq3di6-bvrj6o)

**Comment by danielroe** [comment]
You need to add `<NuxtLayout>` in your `app.vue` if you have a custom `app.vue`:

```vue
<template>
  <div>
    <NuxtLayout>
      <NuxtPage />
    </NuxtLayout>
  </div>
</template>
```
