### ISSUE TITLE
After upgrading to Nuxt 3.7.2, the application will not start

### ISSUE THREAD

**Issue by sdr0x07b6** [nuxt/nuxt#23163]
### Environment

```
------------------------------
- Operating System: Darwin
- Node Version:     v18.14.2
- Nuxt Version:     3.7.2
- CLI Version:      3.8.3
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, srcDir, modules, imports, app, vuetify
- Runtime Modules:  vuetify-nuxt-module@0.5.7, nuxt-icon@0.5.0, @pinia/nuxt@0.4.11, @pinia-plugin-persistedstate/nuxt@1.1.1
- Build Modules:    -
------------------------------
```

### Reproduction

I created a new project for Nuxt 3.7.2 and it was fine.
Also, just the other day I had created a minimal Nuxt 3.7.1 project to do a bug report on another matter, so I upgraded that and it was fine.
The Nuxt 3.7.1 project I was working on at work, the upgrade, gave me an error. It is not that big a project, but it contains a lot of information about my work and I can't submit it as is.

Present `package.json`.
```json
{
  "name": "nuxt-app",
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare",
    "lint": "eslint --ext .js,.vue,.ts .",
    "lint:fix": "eslint --fix --ext .js,.vue,.ts .",
    "format": "prettier --write ."
  },
  "devDependencies": {
    "@nuxt/devtools": "latest",
    "@pinia-plugin-persistedstate/nuxt": "^1.1.1",
    "@types/jsonwebtoken": "^9.0.2",
    "@typescript-eslint/eslint-plugin": "^6.7.0",
    "@typescript-eslint/parser": "^6.7.0",
    "@vue/eslint-config-typescript": "^11.0.3",
    "eslint": "^8.49.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-vue": "^9.17.0",
    "nuxt": "^3.7.2",
    "nuxt-icon": "^0.5.0",
    "prettier": "^3.0.3",
    "sass": "^1.66.1",
    "typescript": "^5.2.2",
    "vuetify-nuxt-module": "^0.5.7"
  },
  "dependencies": {
    "@pinia/nuxt": "^0.4.11",
    "@vee-validate/nuxt": "^4.11.6",
    "@vee-validate/yup": "^4.11.6",
    "autoprefixer": "^10.4.15",
    "jsonwebtoken": "^9.0.2",
    "pinia": "^2.1.6",
    "vue3-popper": "^1.5.0",
    "yup": "^1.2.0"
  }
}
```

### Describe the bug

After upgrading to Nuxt 3.7.2, the application will not start.

`% yarn dev`

```
500
Cannot read properties of undefined (reading 'use')

at ./virtual:nuxt:/Users/<Project in my home directory>/.nuxt/plugins/server.mjs:42:89
at Module.executeAsync (./node_modules/unctx/dist/index.mjs:111:19)
at setup (./virtual:nuxt:/Users/<Project in my home directory>/.nuxt/plugins/server.mjs:42:65)
at ./node_modules/nuxt/dist/app/nuxt.js:114:60
at fn (./node_modules/nuxt/dist/app/nuxt.js:162:44)
at Object.callAsync (./node_modules/unctx/dist/index.mjs:68:55)
at ./node_modules/nuxt/dist/app/nuxt.js:164:56
at Object.runWithContext (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3855:18)
at callWithNuxt (./node_modules/nuxt/dist/app/nuxt.js:164:24)
```

Before the update, it was Nuxt 3.7.1 and was bootable.
I ran `% yarn nuxi upgrade`.

```
❯ Would you like to recreate node_modules and yarn.lock to fix problems with hoisted dependency versions and ensure you have the most up-to-date
dependencies?
● Yes / ○ No
```

I selected Yes.
I then tried to boot with `% yarn dev` and got an error.

This time I was guided to `nuxi upgrade`, but usually `nuxi upgrade --force` is guided, so I tried that too. It did not resolve the problem.

**Comment by nasirDoe** [comment]
same problem

**Comment by sdr0x07b6** [comment]
After that,

- node_modules/
- yarn.lock

I deleted these two, fixed "nuxt" in package.json to "3.7.1", and did a yarn install.
It runs fine with 3.7.1.

**Comment by dargmuesli** [comment]
Potentially related: https://github.com/nuxt/nuxt/pull/23148

**Comment by pavloniym** [comment]
Same error, after upgrade to 3.7.2

**Comment by dargmuesli** [comment]
Are all of you experiencing this problem using layers? Or does this error pop up without layers? If someone feels like providing a minimal reproduction, that would be helpful!

**Comment by attentiondefficient** [comment]
I am not using layers and I get an error after upgrading to 3.7.2. I get this when running 

`nuxt prepare`

`[10:03:46 PM]  ERROR  Cannot find package '@vue/compiler-sfc' imported from /node_modules/unplugin-vue-router/dist/chunk-YCEF6K2A.mjs

  at new NodeError (node:internal/errors:405:5)
  at packageResolve (node:internal/modules/esm/resolve:782:9)
  at moduleResolve (node:internal/modules/esm/resolve:831:20)
  at defaultResolve (node:internal/modules/esm/resolve:1036:11)
  at DefaultModuleLoader.resolve (node:internal/modules/esm/loader:251:12)
  at DefaultModuleLoader.getModuleJob (node:internal/modules/esm/loader:140:32)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:33)
  at link (node:internal/modules/esm/module_job:75:36)`

**Comment by marcelloinfoweb** [comment]
Documention

> Upgrading
As usual, our recommendation for upgrading is to run:
**nuxi upgrade**

**Comment by attentiondefficient** [comment]
> Documention
> 
> > Upgrading
> > As usual, our recommendation for upgrading is to run:
> > **nuxi upgrade**

[https://nuxt.com/blog/v3-7](url) at the bottom indicates 

<img width="849" alt="Screen Shot 2023-09-12 at 10 26 35 PM" src="https://github.com/nuxt/nuxt/assets/122828582/01d03676-79fc-4ee1-8666-55a084741e66">

Should I use `--force` or not?

**Comment by attentiondefficient** [comment]
> I am not using layers and I get an error after upgrading to 3.7.2, using `nuxi upgrade --force`
> 
> I get this when running
> 
> `nuxt prepare` and `nuxt dev`
> 
> ```
> [10:03:46 PM]  ERROR  Cannot find package '@vue/compiler-sfc' imported from /node_modules/unplugin-vue-router/dist/chunk-YCEF6K2A.mjs
> 
>   at new NodeError (node:internal/errors:405:5)
>   at packageResolve (node:internal/modules/esm/resolve:782:9)
>   at moduleResolve (node:internal/modules/esm/resolve:831:20)
>   at defaultResolve (node:internal/modules/esm/resolve:1036:11)
>   at DefaultModuleLoader.resolve (node:internal/modules/esm/loader:251:12)
>   at DefaultModuleLoader.getModuleJob (node:internal/modules/esm/loader:140:32)
>   at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:33)
>   at link (node:internal/modules/esm/module_job:75:36)
> ```

I resolved this with `npm update`

Then devtools broke, I disabled that. 

Now I am getting the exact error mentioned above.

**Comment by attentiondefficient** [comment]
> Are all of you experiencing this problem using layers? Or does this error pop up without layers? If someone feels like providing a minimal reproduction, that would be helpful!

I am using `@pinia-plugin-persistedstate/nuxt` and I am not using layers and receiving this error.

**Comment by danielroe** [comment]
I plan to release a hotfix for this by the end of today; you can try with the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/) in the mean time.

**Comment by attentiondefficient** [comment]
> I plan to release a hotfix for this by the end of today; you can try with the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/) in the mean time.

Thank you!
