### ISSUE TITLE
Bun not working with windows

### ISSUE THREAD

**Issue by marcelloinfoweb** [nuxt/nuxt#23164]
### Describe the feature

It is compatible with Bun?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by warflash** [comment]
Probably better suited for a discussion, but yes, nuxt is. -> https://bun.sh/guides/ecosystem/nuxt

**Comment by huang-julien** [comment]
Yes it is 
https://nuxt.com/docs/getting-started/deployment#presets
https://nitro.unjs.io/deploy/providers/bun

**Comment by marcelloinfoweb** [comment]
But it doesn't work, it keeps crashing, whether in projects already under development or in a clean installation.



https://github.com/nuxt/nuxt/assets/2093128/430bce3b-cbef-4371-bad9-cde3f0f608bf

**Comment by pi0** [comment]
@marcelloinfoweb Please provide a reproduction environment (your operating system, Bun version and Nuxt/Nuxi version you can get via `nuxi info`).

Bun works with Windows on MacOS and Linux but it seems you are on windows which is currently an experimental target for Bun according to their docs.

**Comment by mario-neuhold** [comment]
(possible solution at the end?)

naked install via `bun x nuxi init nuxt-test` already throws an error:

![image](https://github.com/nuxt/nuxt/assets/29606929/b67029e9-82ee-4889-96a0-f8cab3149ed7)

but it still gets installed and can be started via `bun --bun run dev` yet it hangs, same behaviour as in @marcelloinfoweb's video. seems like it is only loading the `<head>`:

![image](https://github.com/nuxt/nuxt/assets/29606929/00589216-2368-43dd-ab0d-706d42170067)

network tab:
![image](https://github.com/nuxt/nuxt/assets/29606929/d2183533-5637-43ce-9567-806fb53f34a6)

browser console output is empty.

nuxi info:

```
Working directory: /home/user/nuxt-test
Nuxt project info:

------------------------------
- Operating System: Linux
- Node Version:     v18.15.0
- Nuxt Version:     3.7.2
- CLI Version:      3.8.3
- Nitro Version:    2.6.3
- Package Manager:  bun@1.0.0
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

windows info:

```
Edition	Windows 11 Pro
Version	22H2
Build	22621.2283
```

wsl info:
```
C:\Users\User>wsl -l -v
  NAME      STATE           VERSION
* Debian    Running         2
```

and after testing all this i just made a typo by typing `bun dev`... and it works :D seems like the "freeze" only happens with `bun --bun run dev`

**Comment by marcelloinfoweb** [comment]
Clean install as per Bun documentation


Working directory: /home/msc/projetos/my-nuxt-app                                                                           3:17:14 PM
Nuxt project info:                                                                                                                                     3:17:14 PM

------------------------------
- Operating System: Linux (WSL 2)
- Node Version:     v18.17.1
- Nuxt Version:     3.7.1
- CLI Version:      3.7.3
- Nitro Version:    2.6.3
- Package Manager:  bun@1.0.1
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

**Comment by mario-neuhold** [comment]
@marcelloinfoweb try `bun dev` instead of `bun --bun run dev`

**Comment by marcelloinfoweb** [comment]
> @marcelloinfoweb try `bun dev` instead of `bun --bun run dev`

Yes, but following the documentation, without --bun, it runs with node, which makes no sense using bun, and it is better to use pnpm, do you agree?

> The nuxt CLI uses Node.js by default; passing the --bun flag forces the dev server to use the Bun runtime instead.

**Comment by mario-neuhold** [comment]
ah.. i didn't see that, thanks for the info! at least my hard work providing all those details isn't wasted then, hope it helps finding a solution.
i'm still blown away buy the fast package installation with bun.

**Comment by pi0** [comment]
Please consider that `bun install` (package manager) is not (yet) supported on windows. You might need to choose another package manager (like `pnpm` or `npm`) and leverage `bun run` for runtime performances.

**Comment by marcelloinfoweb** [comment]
> Please consider that `bun install` (package manager) is not (yet) supported on windows. You might need to choose another package manager (like `pnpm` or `npm`) and leverage `bun dev` for runtime performances.

I understand, but I'm not running on Windows directly but on WSL (Ubuntu), which is a system that runs the native Linux kernel. It should work.

**Comment by mario-neuhold** [comment]
yep, we are talking WSL (windws subsystem linux), not native windows build:
![image](https://github.com/nuxt/nuxt/assets/29606929/f2477b19-4400-4a8f-b12f-92e6dd0d6bf5)

just for reference, there is a bun-ticket for this problem as well: https://github.com/oven-sh/bun/issues/4743

i tried some other related stuff with bun: vue3/vite and nitro apps are all working on bun with WSL

**Comment by pi0** [comment]
Thanks for confirmation! Let's track it via upstream then (i have also subscribed for updates)

**Comment by angelhdzmultimedia** [comment]
> yep, we are talking WSL (windws subsystem linux), not native windows build: ![image](https://user-images.githubusercontent.com/29606929/267765138-f2477b19-4400-4a8f-b12f-92e6dd0d6bf5.png)
> 
> just for reference, there is a bun-ticket for this problem as well: [oven-sh/bun#4743](https://github.com/oven-sh/bun/issues/4743)
> 
> i tried some other related stuff with bun: vue3/vite and nitro apps are all working on bun with WSL

I'm having the `error: script "dev" exited with code 11 (SIGSEGV)` in a Vite + Vue 3 project.
Apparently it's not only Nuxt. It's a problem with HMR in Vite. 
I make some changes in a .vue file, and bam, program crashes with error.

**Comment by pi0** [comment]
We would still be happy to track it if can find a workaround for Nuxt side. Only when an issue is closed, please consider making a fresh new issue mentioning exact nuxt and bun versions + platform (wsl, linux, macos, etc) and feel free to ping me to investigate 👍🏼

**Comment by angelhdzmultimedia** [comment]
Apparently latest version of bun fixed issues with Vite and Rollup and now Nuxt works, can someone confirm? https://github.com/oven-sh/bun/issues/4743#issuecomment-1817794912

**Comment by scottix** [comment]
Still getting error on WSL Ubuntu 22.04

It worked initially but then got into Tailwindcss and stopped working

`bunx nuxi info`
```
Nuxt project info:                                                                                                                                                                         1:57:17 PM

------------------------------
- Operating System: Linux
- Node Version:     v20.8.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  bun@1.0.13
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

`bun dev`

```
bun dev
$ nuxt dev
Nuxt 3.8.2 with Nitro 2.8.0                                                                                                                                                                1:59:56 PM
                                                                                                                                                                                           1:59:56 PM
  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

  ➜ DevTools: press Shift + Alt + D in the browser (v1.0.3)                                                                                                                                1:59:57 PM

ℹ Vite server warmed up in 1326ms                                                                                                                                                         1:59:59 PM
error: script "dev" exited with code 11 (SIGSEGV)
```

package.json
```json
{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/devtools": "latest",
    "autoprefixer": "^10.4.16",
    "nuxt": "^3.8.2",
    "postcss": "^8.4.31",
    "tailwindcss": "^3.3.5",
    "vue": "^3.3.8",
    "vue-router": "^4.2.5"
  }
}
```

**Comment by mario-neuhold** [comment]
yeah i just comfirmed it over there too - works for me on win11 with wsl in a fresh nuxt3 and even with the tailwindcss nuxt module:


```
bunx nuxi info
Working directory: /home/user/wsl-dev/nuxt3                                                                 8:58:57 AM
Nuxt project info:                                                                                          8:58:57 AM

------------------------------
- Operating System: Linux
- Node Version:     v18.17.1
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  bun@1.0.14
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  @nuxtjs/tailwindcss@6.10.1, @pinia/nuxt@0.5.1
- Build Modules:    -
------------------------------
```
