### ISSUE TITLE
How can I add a class to the root directory id="_ nuxt"?

### ISSUE THREAD

**Issue by 63490794** [nuxt/nuxt#23175]
### Describe the feature

`body` add `class`
```js
bodyAttrs: {
    class: 'page-content'
}
```

`_ nuxt` ???

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
You can either change the root id (not class!) from `_nuxt` to something else or apply classes to the `body` via `useHead`.
Alternatively, specify classes in your `App.vue` to specify them for your whole app. ☺️

**Comment by danielroe** [comment]
You can customise the root id + tag with `app.rootId` and `app.rootTag`: https://nuxt.com/docs/api/configuration/nuxt-config#rootid
