### ISSUE TITLE
when use isr mode on vercel, route.query lost,   such as a/b/1?d=2

### ISSUE THREAD

**Issue by TangsWang** [nuxt/nuxt#23171]
### Environment

nuxt3.7.0
vercel
ssr + isr mode on vercel

access   url "/a/b/1" is ok, but url "/a/b/1?d=2" error on vercel.

### Reproduction

nuxt3.7.0
vercel
ssr + isr mode on vercel

access   url "/a/b/1" is ok, but url "/a/b/1?d=2" error on vercel.

### Describe the bug

nuxt3.7.0
vercel
ssr + isr mode on vercel

access   url "/a/b/1" is ok, but url "/a/b/1?d=2" error on vercel.

**Comment by danielroe** [comment]
Query strings are not supported for ISR on Vercel at the moment. Feel free to raise an upstream issue in https://github.com/unjs/nitro if you want this feature, but it would require specifying valid queries on a per-route basis.
