### ISSUE TITLE
useLazyAsyncData does not fetch data from the network with nested routes

### ISSUE THREAD

**Issue by 5cube** [nuxt/nuxt#23187]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.7.2`
- CLI Version:      `3.8.3`
- Nitro Version:    `2.6.3`
- Package Manager:  `yarn@1.22.19`
- Builder:          `-`
- User Config:      `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://codesandbox.io/p/sandbox/sad-rhodes-26pnvm?file=/pages/index.vue:17,35

### Describe the bug

When using nested routes, useLazyAsyncData on the parent route component does not fetch data from the network on client side when ssr from parent route. When ssr from another route it’s ok. There was no such problem in version 3.6.0.

https://github.com/nuxt/nuxt/assets/16667756/f00d9143-1307-40c0-85ee-0463026b999d

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/22955
