### ISSUE TITLE
Nuxt does not register classes in `superjson` after building

### ISSUE THREAD

**Issue by Q16solver** [nuxt/nuxt#23183]
### Environment

- Operating System: Windows_NT  
- Node Version:     v20.5.1     
- Nuxt Version:     3.7.2       
- CLI Version:      3.8.3       
- Nitro Version:    -
- Package Manager:  npm@9.8.0   
- Builder:          -
- User Config:      alias, css, build, nitro, vite, typescript, imports, runtimeConfig, modules, authJs, googleFonts, pinia, unocss
- Runtime Modules:  @hebilicious/authjs-nuxt@0.3.0, @nuxtjs/google-fonts@3.0.2, @pinia/nuxt@0.4.11, @unocss/nuxt@0.55.7, @vueuse/nuxt@10.4.1
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-wn9aqn-sxviyo

1. Run `npm run build`
2. Run `npm run start` or `node .output/server/index.mjs`
3. Observe in Console tab that there is an error `TRPCClientError: Unable to transform response from server`.

### Describe the bug

I want to use trpc with superjson for transforming json data and classes, but it seems like the registered classes work in development but after build, it only runs on one-side (the api endpoint returns the right json + metadata in the network request) but trpc fails to transform it on the server, most likely somehow not registering the classes.

linked discussion in trpc: https://github.com/trpc/trpc/issues/4790

**Comment by kylegl** [comment]
Hey I am running into this as well. Any luck figuring it out?

**Comment by danielroe** [comment]
Would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏

**Comment by kylegl** [comment]
Im not quite sure how to do that but i'll see what i can do

**Comment by danielroe** [comment]
Closing as I'm pretty sure this is a Nitro-related issue and not a Nuxt one. If it only recurs with Nuxt, let me know and I'll reopen it here.

**Comment by Q16solver** [comment]
For @kylegl and anyone else who still cares about this issue, this is seemingly fixed as of nuxt v3.16.1 and trpc v11. For the "proper" way to do this in the cleanest way possible from my perspective for anyone/everyone's reference is to do the following:

1. Define an abstract **Serializable** base class with a **toJSON** method
https://github.com/Esposter/Esposter/blob/main/packages/app/shared/models/entity/Serializable.ts

2. Extend the **Serializable** class for the class you are implementing
https://github.com/Esposter/Esposter/blob/main/packages/app/shared/models/clicker/data/ClickerGame.ts

3. Add it to a **JSONClasses** list with the class and its name
https://github.com/Esposter/Esposter/blob/main/packages/app/shared/services/superjson/JSONClasses.ts

4. Define a nuxt plugin for the payload reducer and revivers for all the custom classes so you don't get into `Cannot stringify arbitrary non-POJOs` trouble on SSR for using it within vue components and composables

5. Register the superjson class in a **shared** folder along with the identifier so the superjson class name is not lost after nuxt builds your app
https://github.com/Esposter/Esposter/blob/main/packages/app/shared/services/trpc/transformer.ts

6. Now you are ready to use your superjson transformer in your trpc client and server!

Don't ask me why this doesn't work with decorators and that we need to manually define a list of json classes with its name (trust me, I've tried, **really hard** and it ends up being 100x simpler and easier to do it this way and ensure that both server and client side has the same list of json classes it registers)
