### ISSUE TITLE
Call useNuxtApp two times in pinia store inside useAsyncData - Nuxt context instance error

### ISSUE THREAD

**Issue by brunocamboim** [nuxt/nuxt#23192]
### Environment

- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.7.2
- CLI Version:      3.8.3
- Nitro Version:    2.6.3
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      modules, nitro, runtimeConfig
- Runtime Modules:  @pinia/nuxt@0.4.11
- Build Modules:   

### Reproduction

https://stackblitz.com/edit/github-bwuqrs

### Describe the bug

In my personal project, I have to do two requests on the server side. For this, I was using useAsyncData, making one request, and after it, doing another with the data of the previous request. 

it worked normally when I was using direct axios service. However, when I created a plugin for $api and injected it in the nuxt context, the second request started to throw an error: **A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function**.

I do these requests inside pinia store, calling useNuxtApp().$api inside of the store, for each request.

Example of **useAsyncData**:
```
await useAsyncData('initStore', async () => {
  if (process.server) {
    const settingsStore = useSettingsStore();
   // Change condition to works
    if (true) {
      await settingsStore.get();
      await settingsStore.get();
    } else {
      console.log('No error');
      await Promise.allSettled([settingsStore.get(), settingsStore.get()]);
    }
  }
});
```

**Pinia store:** 
```
export const useSettingsStore = defineStore('settingsStore', {
  state: () => ({}),
  actions: {
    async get() {
      try {
        const { $api } = useNuxtApp();
        console.log('$api passed');
      } catch (err) { 
        console.log('error inside catch', err);
      } 
    },
  },
});
```

Do I have to instantiate useNuxtApp inside useAsyncData and pass it to actions inside pinia? Why the second request is throwing this error? Is there a solution for that?

Ps.: If I do both requests at the same time, It works normally, the nuxt context inside pinia works.

### Logs

```shell-script
Error: [nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at `https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables`.
```

**Comment by danielroe** [comment]
Yes, this is an issue with the Nuxt pinia integration. You either need to use `nuxtApp.runWithContext`, or can raise a feature request to support transforming with async context within pinia.

You might also try enabling `experimental.asyncContext` to see if that makes a difference for you.
