### ISSUE TITLE
rollup resolve issue for commonJS packages

### ISSUE THREAD

**Issue by huang-julien** [nuxt/nuxt#23200]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v16.20.0
- Nuxt Version:     3.7.3
- CLI Version:      3.8.3
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-z1b17v?file=server%2Futils%2Fapplicationinsights.ts,server%2Fmiddleware%2Fapplicationinsights.ts

- try `npm run dev`
- ` RollupError: Could not resolve "./AutoCollection/CorrelationContextManager" from ./AutoCollection/CorrelationContextManager?commonjs-external"`

### Describe the bug

Hi :wave:

Since 3.7, importing `applicationinsights` breaks the whole app. This was working with 3.6.5.
I believe this is probably an issue with Nitro instead of Nuxt.  

Why didn't microsoft release ESM for this package ? 😱

**Comment by huang-julien** [comment]
Forcing the resolution to 2.5.2 for nitro seems to avoid the issue. I'm cloning this issue to nitro. 
Not sure if this should be kept open with a linking to the new issue so other people can see there's an issue with some commonJS packages

**Comment by danielroe** [comment]
Thank you for investigating. 🙏 

In general we're trying to avoid mirroring issues here as well as in nitro, so I'd be very happy just to track there.
