### ISSUE TITLE
Cannot properly declare module for docx files

### ISSUE THREAD

**Issue by KamilBeda** [nuxt/nuxt#23214]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.17.1
- Nuxt Version:     3.7.0
- CLI Version:      3.7.2
- Nitro Version:    2.6.2
- Package Manager:  npm@9.6.7
- Builder:          -
- User Config:      ssr, devtools, imports, modules, css, svgo, i18n, headlessui, components, extends, runtimeConfig, linkChecker, googleFonts, build, vite, nitro, app, auth
- Runtime Modules:  @nuxtjs/eslint-module@4.1.0, @pinia/nuxt@0.4.11, @nuxtjs/i18n@8.0.0-rc.2, @sidebase/nuxt-auth@0.6.0-beta.4, nuxt-svgo@3.4.1, nuxt-headlessui@1.1.4, nuxt-typed-router@3.3.1, @formkit/nuxt@1.0.0, @nuxtjs/tailwindcss@6.8.0, nuxt-icon@0.5.0, @nuxtjs/google-fonts@3.0.2, @vueuse/nuxt@10.4.1
- Build Modules:    -
------------------------------

### Reproduction

Reproduction link - [https://stackblitz.com/edit/github-7ztwvf?file=app.vue](https://stackblitz.com/edit/github-7ztwvf?file=app.vue)

### Describe the bug

Hello!
I'm having a hard time trying to declare module for docx imports.
I'm importing my file like this (in script setup)
```javascript
import PrivacyPolicyUrl from '~/assets/docs/polityka.docx'
```
The TypeScript error on that line is `Cannot find module '~/assets/docs/polityka.docx' or its corresponding type declarations.`
So I try to provide module declaration in index.d.ts in multiple ways:
1.
```javascript
declare module '*.docx' {
  const docxUrl: string
  export = docxUrl
}
```
2.
```javascript
declare module '*.docx' {
  const docxUrl: string
  export default docxUrl
}
```
3.
```javascript
declare module '~/assets/docs/polityka.docx' {
  const docxUrl: string
  export = docxUrl
}
```
4.
```javascript
declare module '~/assets/docs/polityka.docx' {
  const docxUrl: string
  export default docxUrl
}
```
Non of the above works, I still get the same typescript error.
I can't just put my docx in `public` folder because my assets are served by django and nuxt needs to copy all assets to `/static/_nuxt/` directory to make it happen. I'm using following nuxt.config entries for that:
```javascript
  vite: {
    assetsInclude: [/\.docx/],
  },
 app: {
    buildAssetsDir: '/static/_nuxt/',
  },
```

Any help is highly appreciated

**Comment by danielroe** [comment]
For a shim, you should not be operating in a TS context so you should just remove the `export {}`:

```diff
  declare module '*.docx' {
    const docxUrl: string;
    export default docxUrl;
  }
  
- export {};
```

**Comment by KamilBeda** [comment]
Thank you for your answer. I've realized that this issue was caused by other problems in my index.d.ts (I had top level imports and ts didn't like that at all). So I fixed it but I've stumbled on another issue.
The `export` in index.d.ts came from this documentation section [https://nuxt.com/docs/guide/going-further/runtime-config#manually-typing-runtime-config](https://nuxt.com/docs/guide/going-further/runtime-config#manually-typing-runtime-config). It says `It is always important to ensure you import/export something when augmenting a type` so is the documentation wrong?
Please run typecheck at updated reproduction link - [https://stackblitz.com/edit/github-7ztwvf?file=index.d.ts](https://stackblitz.com/edit/github-7ztwvf?file=index.d.ts) 
When there is no `export {}` typescript emits errors about nuxt.config and public runtime config. When I add it back, the issue with `docx` returns.

Thanks for help and very quick response :heart:

**Comment by danielroe** [comment]
There are two kinds of declaration files you can write. You can _augment_ which requires the `export {}`. Or you can totally overwrite (which is what you need with the `docx` declaration). They can't happen in the same file. So you may need to create a separate `shims.d.ts` file for the `docx` declaration.

**Comment by KamilBeda** [comment]
Thanks a lot. The d.ts files always were a little bit of mistery for me. Now it's all clear.
Sorry for wasting your time for such basic issues, I tried to reach out to community (discord) with this but couldn't get any anwser.
Have a great day!

**Comment by danielroe** [comment]
Glad to help 😊
