### ISSUE TITLE
Nuxt cannot build `import * as components from "vuetify/components"` when used in both client/server

### ISSUE THREAD

**Issue by Q16solver** [nuxt/nuxt#23210]
### Environment

- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.7.3
- CLI Version:      3.8.3
- Nitro Version:    2.6.3
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      build
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-wn9aqn

1. Run `npm run build`
2. Observe that you get `Could not load raw:./VCode.css (imported by node_modules/vuetify/lib/components/VCode/index.mjs): ENOENT: no such file or directory, open './VCode.css'`. It seems as if it gets the "./" (current directory part) wrong and tries to load it as if it's from project root instead of inside node_modules which is where it actually exists.

### Describe the bug

I wanted to add some types by doing `import * as components from "vuetify/components"` and generating some nice little types for that, but nuxt started crashing build for me when I used the types in a class, and `new`'d that class in the server api.

**Comment by danielroe** [comment]
I think this _might_ be linked to https://github.com/unjs/nitro/issues/1726.

**Comment by Q16solver** [comment]
Yes, that's most likely the case, nitro v2.9.6 seems to have resolved this issue, closing
