### ISSUE TITLE
Middleware confirm dialog not triggering on client-side navigation in Nuxt3

### ISSUE THREAD

**Issue by g1ronn1mo** [nuxt/nuxt#23217]
### Environment

Environment:

Nuxt Version: 3.3
Browser: Chrome
Operating System: Windows 11

### Reproduction

IN nuxt.config.ts set
  `ssr: false`
  
 create a folder with middleware described in https://nuxt.com/docs/guide/directory-structure/middleware and place a file with `preventBackToHome.ts` with:
 
```js
export default defineNuxtRouteMiddleware((to, from) => {
  console.log(from)
  // Check if user is navigating from /projects to /
  if (!process.server)
    console.log('middleware from client side')

  if (from.path === '/projects') {
    if (!window.confirm('You have unsaved changes. Are you sure you want to leave?')) {
      return abortNavigation() 
    }
  }
})
```
add it in `projects.vue` page:

```js
definePageMeta({
  middleware: ['prevent-back-to-home'],
})
```

Navigate to /projects route.
Use client-side navigation to move to another route (e.g., click on a <NuxtLink> pointing to another page).
Notice that the confirm dialog does not appear.
Reload the page while on /projects.
Now, try navigating away.
The confirm dialog appears as expected.

### Describe the bug

When navigating away from the /projects route using client-side navigation in Nuxt3, the window.confirm dialog in the checkBackNavigation middleware is not being displayed. However, the dialog is correctly shown during a full page reload.

Expected Behavior:
The window.confirm dialog should be displayed whenever navigating away from the /projects route, regardless of whether it's client-side navigation or a full page reload.

Actual Behavior:
The window.confirm dialog is only displayed during a full page reload and not during client-side navigation.

### Additional context

The middleware is correctly set up and applied to the /projects route.
Console logs within the middleware confirm that the middleware is being executed during client-side navigation.
Replacing window.confirm with alert or console.log indicates that the middleware is functioning, but the confirm dialog is not being shown.

**Comment by danielroe** [comment]
Named middleware should be run when navigating _to_ a page, not when navigating away from it.
