### ISSUE TITLE
Nuxt Link Multiple Click Then Error

### ISSUE THREAD

**Issue by xtrmus** [nuxt/nuxt#23228]
### Environment
NavBar : 
![image](https://github.com/nuxt/nuxt/assets/24972453/13860bf9-9983-413c-9c4f-c62a1decda02)
![image](https://github.com/nuxt/nuxt/assets/24972453/677bf314-f7e2-44f0-961a-d0291a90c7e9)

Leaderboard:
![image](https://github.com/nuxt/nuxt/assets/24972453/f02c4b7f-11fa-4f5e-a63c-e87db7676029)
![image](https://github.com/nuxt/nuxt/assets/24972453/7e8f28d4-5147-4544-b1c9-52250b769612)

### Reproduction

I shared the codes of the Navigation Bar and the relevant page above.

### Describe the bug

I do not have any problems when I click on the leaderboard once and wait for the page to open or when I refresh the leaderboard page.

However, when I press the leaderboard nuxt link button from the home page 3 or 4 times in a row without waiting for the page to open, I get an error. How can I solve this?

![image](https://github.com/nuxt/nuxt/assets/24972453/8005f8ec-3fad-442e-8463-9cd870ee1ce9)
![image](https://github.com/nuxt/nuxt/assets/24972453/dda76f0c-4d23-4311-ac72-2f8339e82f40)

**Comment by manniL** [comment]
Besides that the code needs some serious cleanup (no `var`, using a computed, etc. etc.):

Do you use transitions? If yes, this is likely from https://github.com/nuxt/nuxt/issues/13309

**Comment by danielroe** [comment]
I think this is being tracked in two places - one with transition that @manniL linked, and one more without based on pure async/suspense at https://github.com/nuxt/nuxt/issues/22900.
