### ISSUE TITLE
`useFetch` automatically handles this behaviour. It will not refetch on client if it was fetched on the server. So you do not need to add custom logic to handle server/client behaviour.

### ISSUE THREAD

**Issue by gllinzbk1** [nuxt/nuxt#23229]
`useFetch` automatically handles this behaviour. It will not refetch on client if it was fetched on the server. So you do not need to add custom logic to handle server/client behaviour.

_Originally posted by @danielroe in https://github.com/nuxt/nuxt/issues/22659#issuecomment-1681667974_

I found that on the static page of SSG, usefetch will request data again, which is not what I want. Is there any way to prevent regeneration

**Comment by gllinzbk1** [comment]
```
    const { data:data } = await useFetch('http://f.lgl.lb.in:8080/vueapi/list', {
  method: 'GET',
  params: {
    url: routeResult[0],
    page: 1
  },
  server: true,
  refetch:false,
  retry: 3,
  responseType:'json',
  key: `list-${routeResult[0]}`,
  watch:[routeResult[0]]
})
```

**Comment by gllinzbk1** [comment]
![image](https://github.com/nuxt/nuxt/assets/115514156/0720d299-9bc2-48ce-8410-c49bd75bba73)

**Comment by gllinzbk1** [comment]
https://github.com/gllinzbk1/gllin2
![image](https://github.com/nuxt/nuxt/assets/115514156/1986dc38-2f9b-4c9b-a72c-1addce46d1ba)

**Comment by danielroe** [comment]
@gllinzbk1 You have turned off the functionality on [this line](https://github.com/gllinzbk1/gllin2/blob/main/nuxt.config.ts#L7). Payload extraction is what enables what you want (not refetching on client-side navigation).

**Comment by gllinzbk1** [comment]
![image](https://github.com/nuxt/nuxt/assets/115514156/49747740-6f58-4066-8ddd-61ad1cf7b50f)
Is Payload.json and __nuxt_data__ duplicate? Is it enough to have just one
