### ISSUE TITLE
Nuxt 3.7 - Slow full first browser page (re)load in development mode in starter project

### ISSUE THREAD

**Issue by DavidDomkar** [nuxt/nuxt#23220]
### Environment

- Operating System: Windows_NT (also happens to the colleague on macos)
- Node Version:     v18.16.0
- Nuxt Version:     3.7.3
- CLI Version:      3.8.3
- Nitro Version:    2.6.3
- Package Manager:  yarn@3.5.1
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

`npx nuxi@latest init my-app` is enough to reproduce the issue. I have selected yarn as the package manager, other options are left as defaults. Then issuing `yarn dev`.

### Describe the bug

When reloading the browser in dev mode with Nuxt >=3.7, it takes really long time. This leaves our project stuck at version 3.6.5, which works really well and does not slow our development speed.

### Additional context

I am providing screenshots of the starter project 's browser dev tools network tab with Nuxt 3.6.5 (works as expected) and Nuxt 3.7.3 (painfully slow)

Nuxt 3.6.5:
![nuxt36](https://github.com/nuxt/nuxt/assets/7688351/d0f1b302-dfaf-49c3-bee6-a3365d32f528)

Nuxt 3.7.3:
![nuxt37](https://github.com/nuxt/nuxt/assets/7688351/d654ab76-9226-4e88-ad8f-8d08d7ca2aeb)

**Comment by warflash** [comment]
This is due to issues with the nuxt cli, e.g. -> https://github.com/nuxt/cli/issues/136 + https://github.com/nuxt/cli/issues, I'd recommend following that for updates

**Comment by DavidDomkar** [comment]
Thank you, I have been looking for similar issue but couldn't find. 👍

**Comment by liaow-ww** [comment]
omg, did you solve this problem? I also used 3.7.3, and then downgraded to 3.6.5. The speed of requesting resource files became much faster. The original local development speed was a nightmare.

**Comment by warflash** [comment]
@liaow-ww Upgrading nuxt to 3.8.1 should fix that issue, yes

**Comment by liaow-ww** [comment]
> @liaow-ww Upgrading nuxt to 3.8.1 should fix that issue, yes

emm, it doesn't work

**Comment by liaow-ww** [comment]
> @liaow-ww Upgrading nuxt to 3.8.1 should fix that issue, yes将 nuxt 升级到 3.8.1 应该可以解决这个问题，是的

nuxt 3.8.2, nitro 2.8.0

**Comment by denishm116** [comment]
> @liaow-ww Upgrading nuxt to 3.8.1 should fix that issue, yes

It doesn't work for me too, but downgrade version nuxt from 3.8.2 to 3.6.5 helps me! But i think it is not good.

**Comment by liaow-ww** [comment]
> > @liaow-ww Upgrading nuxt to 3.8.1 should fix that issue, yes
> 
> It doesn't work for me too, but downgrade version nuxt from 3.8.2 to 3.6.5 helps me! But i think it is not good.

okay.. I can only use this method at the moment. If there are other methods that work, please let me know.

**Comment by senher** [comment]
"nuxt": "^3.8.0",
"nuxt": "^3.10.0",
The problem still exists.
![image](https://github.com/nuxt/nuxt/assets/23719867/643402cf-a9ce-4e93-af10-9896cb0477aa)

**Comment by ha1uu** [comment]
downgrading to 3.6.5 helped me, thanks for solution
