### ISSUE TITLE
Hydration error with \r in text

### ISSUE THREAD

**Issue by gibkigonzo** [nuxt/nuxt#23234]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.17.0
- Nuxt Version:     3.7.3
- CLI Version:      3.8.3
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      telemetry
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Nuxt 2 (works) https://codesandbox.io/p/sandbox/black-http-w2ztvn?file=/components/Logo.vue:1,11-4,10
Nuxt 3 (doesn't work) https://codesandbox.io/p/sandbox/gifted-payne-y2lxwl?file=/app.vue:4,10

### Describe the bug

When I have in text `\r` then I get hydration error.

For example:
```
<template>
  <span>
    {{ "Some text \r" }}
  </span>
</template>
```

This results in:
![Screenshot from 2023-09-15 13-29-38](https://github.com/nuxt/nuxt/assets/42383376/61f5446f-4749-4dc1-9389-fcc6f876d279)

It works in Nuxt2 (there is no error), but doesn't work in Nuxt 3.

**Comment by danielroe** [comment]
This is almost certainly a Vue core SSR bug. See, for example, https://github.com/vuejs/core/issues/6410.

Would you open an issue upstream on https://github.com/vuejs/core? 🙏

**Comment by gibkigonzo** [comment]
@danielroe thanks for quick response. Yep, I've checked with latest vue and it also shows error in core. Here is issue https://github.com/vuejs/core/issues/9229
