### ISSUE TITLE
How to detect incompatible browsers to show a warning message?

### ISSUE THREAD

**Issue by preetmishra** [nuxt/nuxt#23233]
### Describe the feature

We have Vite as the bundler. [Vite](https://vitejs.dev/guide/build.html#browser-compatibility) targets following browsers:
* Chrome >=87
* Firefox >=78
* Safari >=14
* Edge >=88

What's the recommended to detect other browsers and show a warning message?

I gather a way would be to include a separate script tag in the `html` file (something that does not depend on Nuxt to be instantiated). However, in Nuxt 3, there's no way to work with the `html` file directly. Any pointers would be highly appreciated!

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
You can add scripts via `useHead({ script: [{ innerHTML: 'console.log("hi there")' }] })`

**Comment by preetmishra** [comment]
Thanks! Apologies for the trouble.

**Comment by danielroe** [comment]
No problem at all! Glad to help.
