### ISSUE TITLE
Is Payload.json and __nuxt_data__ duplicate? Is it enough to have just one

### ISSUE THREAD

**Issue by gllinzbk1** [nuxt/nuxt#23247]
![image](https://github.com/nuxt/nuxt/assets/115514156/082eea21-7687-4454-b662-3ab5e51508c9)
Is Payload.json and __nuxt_data__ duplicate? Is it enough to have just one

_Originally posted by @gllinzbk1 in https://github.com/nuxt/nuxt/issues/23229#issuecomment-1722080577_

**Comment by danielroe** [comment]
No, these are not duplicate. State is not stored in the extracted payload.
