### ISSUE TITLE
Nested dynamic pages not rendering

### ISSUE THREAD

**Issue by niekbiesterbos** [nuxt/nuxt#23244]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.7.3`
- CLI Version:      `3.8.4`
- Nitro Version:    `2.6.3`
- Package Manager:  `yarn@1.22.19`
- Builder:          `-`
- User Config:      `css`, `components`, `app`, `srcDir`, `build`, `devServer`, `modules`, `i18n`, `nitro`, `site`, `runtimeConfig`, `devtools`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-rc.4`, `nuxt-mapbox@1.4.4`, `@pinia/nuxt@0.4.11`, `@pinia-plugin-persistedstate/nuxt@1.1.1`, `@nuxt/content@2.8.2`, `@nuxtjs/robots@3.0.0`, `@nuxt/image@1.0.0-rc.2`, `nuxt-simple-robots@3.1.2`, `nuxt-simple-sitemap@3.3.3`
- Build Modules:    `-`

### Reproduction

Reproduction 1:
https://stackblitz.com/edit/github-5hgjm9?file=pages%2Findex.vue

Reproduction 2:
https://stackblitz.com/edit/github-mmggus?file=pages%2Findex.vue

### Describe the bug

I try to render a dynamic page which is nested inside the chats route. Chats is also a page, so I added NuxtPage to it so that it should render the child as well. But, rendering the child does not work, it does log the chatid (and changing meta data like the title etc. all works), but rendering the page does not. Using <a> instead of NuxtLink does get rid of the warning that the route does not exist, but it still does not render the page correctly. 

If there is anymore additional info needed, please let me now. 

### Additional context

Bug also appears when using in conjunction with the Nuxt Content module, the page does not render correctly all the time. Navigating to blog/the-content-file does not work when there is also a blog.vue file. 

### Logs

```shell-script
[Vue Router warn]: No match found for location with path "/_nuxt/pages/profile/chats/index.vue?t=6349809384571"
```

**Comment by danielroe** [comment]
You should use an absolute path:

```diff
- <NuxtLink to="chats/1234">
+ <NuxtLink to="/chats/1234">
```

Otherwise your first reproduction seems to work fine for me.

In your second reproduction the issue is this:

```diff
- const chatid = ref(route.value.chatid);
+ const chatid = ref(route.params.chatid);
```

It's throwing an error because `route.value` doesn't exist.

**Comment by niekbiesterbos** [comment]
Hi Daniel,

Sorry for the inconvenience, created the reproduction too fast. It does not work for me. It renders the [chat] page underneath it (as you can see it outputs the p element with the id) but it does not render it as a new page. 

I also use async route middleware on the route which may also influence the results, but that did not do the trick

**Comment by danielroe** [comment]
What do you mean by 'rendering it as a new page'?

**Comment by niekbiesterbos** [comment]
Updated this reproduction again:
https://stackblitz.com/edit/github-5hgjm9-wimelt?file=pages%2Findex.vue 

As you can see, the actual chat page (the [chatid].vue) does not render as a normal page on a route, but underneath the Chats Overview page. On my project, it does not render at all. 

I need to be able to;
- Render the chats page, which is nested in profile
- Navigate to a dynamic route on profile/chats/[chatid] 

Currently, it does navigate to the id, but it still renders the chats page. Also, I see that both the chats and chats/[chatid] page are active in the dev tools while I am on the chats/[chatid] route

**Comment by niekbiesterbos** [comment]
Logging route.params.chatid does correctly work, but it just does not display the content in [chatid].vue, also when there is only a template with a single p hello world in it.

**Comment by danielroe** [comment]
See https://nuxt.com/docs/guide/directory-structure/pages/#nested-routes.

You should likely have `chats/index.vue` and `chats/[chatid].vue` to achieve what you want.

**Comment by niekbiesterbos** [comment]
That did the trick, thank you very much! 

Keep up the good work :)
