### ISSUE TITLE
npx nuxi@latest (3.7.3) is broken -  ERROR  Cannot start nuxt:  Cannot redefine property: __internal__deprecationWarning

### ISSUE THREAD

**Issue by ilanbro** [nuxt/nuxt#23256]
### Environment

On my current project:
------------------------------
- Operating System: Darwin
- Node Version:     v20.6.0
- Nuxt Version:     3.7.3
- CLI Version:      3.8.4
- Nitro Version:    2.6.3
- Package Manager:  npm@9.8.1
- Builder:          -
- User Config:      pages, modules, supabase, devtools
- Runtime Modules:  @nuxtjs/supabase@1.1.0, @nuxtjs/tailwindcss@6.8.0
- Build Modules:    -

------------------

I've also tried to create a completely new project and see if it works, using:
npx nuxi@latest init <project name>

------------------------------
- Operating System: Darwin
- Node Version:     v20.6.0
- Nuxt Version:     -
- CLI Version:      3.8.4
- Nitro Version:    -
- Package Manager:  yarn@1.22.10
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Tried to upgrade from 3.7.1 to 3.7.3 an existing project but received:
 **ERROR  Cannot redefine property: __internal__deprecationWarning                                                                                                18:21:36**

  at Function.defineProperty (<anonymous>)
  at Object.<anonymous> (node_modules/@babel/types/lib/index.js:66:8)
  at Module._compile (node:internal/modules/cjs/loader:1241:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
  at Module.load (node:internal/modules/cjs/loader:1091:32)
  at Module._load (node:internal/modules/cjs/loader:938:12)
  at Module.require (node:internal/modules/cjs/loader:1115:19)
  at require (node:internal/modules/helpers:130:18)
  at Object.<anonymous> (node_modules/@babel/types/lib/builders/validateNode.js:8:14)
  at Module._compile (node:internal/modules/cjs/loader:1241:14) 

https://codesandbox.io/p/sandbox/nuxt-starter-z4660?file=/package.json:1,1-32,2

### Describe the bug

My upgrade from 3.7.1 to 3.7.3 received:
 ERROR  Cannot redefine property: __internal__deprecationWarning                                                                                                18:21:36

  at Function.defineProperty (<anonymous>)
  at Object.<anonymous> (node_modules/@babel/types/lib/index.js:66:8)
  at Module._compile (node:internal/modules/cjs/loader:1241:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
  at Module.load (node:internal/modules/cjs/loader:1091:32)
  at Module._load (node:internal/modules/cjs/loader:938:12)
  at Module.require (node:internal/modules/cjs/loader:1115:19)
  at require (node:internal/modules/helpers:130:18)
  at Object.<anonymous> (node_modules/@babel/types/lib/builders/validateNode.js:8:14)
  at Module._compile (node:internal/modules/cjs/loader:1241:14) 

My package.json is:
{
  "name": "nuxt-app",
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "prisma": {
    "seed": "node prisma/seed.js"
  },
  "devDependencies": {
    "@nuxt/devtools": "latest",
    "@nuxtjs/supabase": "^1.1.0",
    "nuxt": "^3.7.3"
  },
  "dependencies": {
    "@headlessui/vue": "^1.7.16",
    "@heroicons/vue": "^2.0.18",
    "@jridgewell/sourcemap-codec": "^1.4.15",
    "@nuxtjs/tailwindcss": "^6.8.0",
    "@pinia/nuxt": "^0.4.11",
    "@prisma/client": "^5.3.0",
    "@rollup/plugin-terser": "^0.4.3",
    "@vite-pwa/nuxt": "^0.1.1",
    "nuxt-icon": "^0.5.0",
    "prisma": "^5.3.0",
    "uuid": "^9.0.1"
  }
}

I've also tried to create a new project using npx nuxi@latest init <project name> and similarly it is broken.
package.json is:

{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/devtools": "latest",
    "nuxt": "^3.7.3"
  }
}

 ERROR  Cannot redefine property: __internal__deprecationWarning                                                                                                18:38:39

  at Function.defineProperty (<anonymous>)
  at Object.<anonymous> (node_modules/@babel/types/lib/index.js:66:8)
  at Module._compile (node:internal/modules/cjs/loader:1241:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
  at Module.load (node:internal/modules/cjs/loader:1091:32)
  at Module._load (node:internal/modules/cjs/loader:938:12)
  at Module.require (node:internal/modules/cjs/loader:1115:19)
  at require (node:internal/modules/helpers:130:18)
  at Object.<anonymous> (node_modules/@babel/types/lib/builders/validateNode.js:8:14)
  at Module._compile (node:internal/modules/cjs/loader:1241:14) 

Needless to say it was working before the upgrade.

### Logs

```shell-script
(base) XXXX ~/mydev/projects  $ tail -100 /Users/XXXX/.npm/_logs/2023-09-17T17_37_16_032Z-debug-0.log
4685 timing build:link:node_modules/@npmcli/run-script/node_modules/which Completed in 6ms
4686 timing build:link:node_modules/cacache/node_modules/glob Completed in 6ms
4687 timing build:link:node_modules/is-wsl/node_modules/is-docker Completed in 6ms
4688 timing build:link:node_modules/make-dir/node_modules/semver Completed in 6ms
4689 timing build:link:node_modules/make-fetch-happen/node_modules/glob Completed in 6ms
4690 timing build:link:node_modules/postcss-url/node_modules/mime Completed in 6ms
4691 timing build:link:node_modules/node-gyp/node_modules/nopt Completed in 6ms
4692 timing build:link:node_modules/postcss/node_modules/nanoid Completed in 6ms
4693 timing build:link:node_modules/@nuxt/devtools Completed in 8ms
4694 timing build:link:node_modules/open/node_modules/is-docker Completed in 6ms
4695 timing build:link:node_modules/@mapbox/node-pre-gyp Completed in 8ms
4696 timing build:link:node_modules/@nuxt/devtools-wizard Completed in 8ms
4697 timing build:link:node_modules/@nuxt/telemetry Completed in 8ms
4698 timing build:link:node_modules/@npmcli/installed-package-contents Completed in 8ms
4699 timing build:link:node_modules/autoprefixer Completed in 8ms
4700 timing build:link:node_modules/send/node_modules/mime Completed in 6ms
4701 timing build:link:node_modules/@vercel/nft Completed in 8ms
4702 timing build:link:node_modules/acorn Completed in 8ms
4703 timing build:link:node_modules/crc-32 Completed in 7ms
4704 timing build:link:node_modules/browserslist Completed in 7ms
4705 timing build:link:node_modules/read-package-json/node_modules/glob Completed in 6ms
4706 timing build:link:node_modules/vite/node_modules/esbuild Completed in 6ms
4707 timing build:link:node_modules/errno Completed in 7ms
4708 timing build:link:node_modules/esbuild Completed in 7ms
4709 timing build:link:node_modules/color-support Completed in 7ms
4710 timing build:link:node_modules/cssesc Completed in 7ms
4711 timing build:link:node_modules/esno Completed in 7ms
4712 timing build:link:node_modules/jiti Completed in 7ms
4713 timing build:link:node_modules/flat Completed in 7ms
4714 timing build:link:node_modules/is-docker Completed in 7ms
4715 timing build:link:node_modules/giget Completed in 7ms
4716 timing build:link:node_modules/is-inside-container Completed in 7ms
4717 timing build:link:node_modules/esprima Completed in 7ms
4718 timing build:link:node_modules/listhen Completed in 7ms
4719 timing build:link:node_modules/mime Completed in 7ms
4720 timing build:link:node_modules/json5 Completed in 7ms
4721 timing build:link:node_modules/nitropack Completed in 7ms
4722 timing build:link:node_modules/js-yaml Completed in 7ms
4723 timing build:link:node_modules/mkdirp Completed in 7ms
4724 timing build:link:node_modules/jsesc Completed in 7ms
4725 timing build:link:node_modules/node-gyp Completed in 7ms
4726 timing build:link:node_modules/node-gyp-build Completed in 7ms
4727 timing build:link:node_modules/nypm Completed in 7ms
4728 timing build:link:node_modules/nanoid Completed in 7ms
4729 timing build:link:node_modules/nuxi Completed in 7ms
4730 timing build:link:node_modules/nopt Completed in 7ms
4731 timing build:link:node_modules/resolve Completed in 7ms
4732 timing build:link:node_modules/openapi-typescript Completed in 7ms
4733 timing build:link:node_modules/pacote Completed in 7ms
4734 timing build:link:node_modules/rimraf Completed in 7ms
4735 timing build:link:node_modules/semver Completed in 7ms
4736 timing build:link:node_modules/rollup Completed in 7ms
4737 timing build:link:node_modules/svgo Completed in 7ms
4738 timing build:link:node_modules/terser Completed in 7ms
4739 timing build:link:node_modules/untun Completed in 7ms
4740 timing build:link:node_modules/rollup-plugin-visualizer Completed in 7ms
4741 timing build:link:node_modules/tsx Completed in 7ms
4742 timing build:link:node_modules/vite Completed in 7ms
4743 timing build:link:node_modules/vite-node Completed in 7ms
4744 timing build:link:node_modules/untyped Completed in 7ms
4745 timing build:link:node_modules/update-browserslist-db Completed in 7ms
4746 timing build:link:node_modules/wait-on Completed in 7ms
4747 timing build:link:node_modules/vscode-languageserver Completed in 7ms
4748 timing build:link:node_modules/which Completed in 7ms
4749 timing build:link:node_modules/node-gyp/node_modules/which Completed in 6ms
4750 timing build:link Completed in 8ms
4751 info run esbuild@0.19.3 postinstall node_modules/esbuild node install.js
4752 info run esbuild@0.18.20 postinstall node_modules/@esbuild-kit/core-utils/node_modules/esbuild node install.js
4753 info run esbuild@0.18.20 postinstall node_modules/vite/node_modules/esbuild node install.js
4754 info run esbuild@0.18.20 postinstall { code: 0, signal: null }
4755 timing build:run:postinstall:node_modules/vite/node_modules/esbuild Completed in 197ms
4756 info run esbuild@0.18.20 postinstall { code: 0, signal: null }
4757 timing build:run:postinstall:node_modules/@esbuild-kit/core-utils/node_modules/esbuild Completed in 283ms
4758 info run esbuild@0.19.3 postinstall { code: 0, signal: null }
4759 timing build:run:postinstall:node_modules/esbuild Completed in 421ms
4760 timing build:run:postinstall Completed in 422ms
4761 timing build:deps Completed in 438ms
4762 timing build Completed in 438ms
4763 timing reify:build Completed in 440ms
4764 timing reify:trash Completed in 3ms
4765 timing reify:save Completed in 91ms
4766 timing reify Completed in 82812ms
4767 timing command:install Completed in 83371ms
4768 verbose stack Error: command failed
4768 verbose stack     at ChildProcess.<anonymous> (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
4768 verbose stack     at ChildProcess.emit (node:events:514:28)
4768 verbose stack     at maybeClose (node:internal/child_process:1105:16)
4768 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
4769 verbose cwd /Users/xxxxx/mydev/projects/xxxxx
4770 verbose Darwin 22.6.0
4771 verbose node v20.6.0
4772 verbose npm  v9.8.1
4773 error code 1
4774 error path /Users/xxxxx/mydev/projects/xxxx
4775 error command failed
4776 error command sh -c nuxt prepare
4777 verbose exit 1
4778 timing npm Completed in 83462ms
4779 verbose code 1
4780 error A complete log of this run can be found in: /Users/XXXXXXX/.npm/_logs/2023-09-17T17_37_16_032Z-debug-0.log
```

**Comment by danielroe** [comment]
This was an upstream bug in Node 20.5 that is now resolved upstream: https://github.com/nuxt/nuxt/issues/23020

**Comment by ilanbro** [comment]
Oh, silly me, I should have tried rolling back to node TLS! 
Lots of thanks @danielroe, super appreciated !!

I didn't install beyond TLS consciously - I think brew upgrade did it.
For those who have mac, to downgrade back to TLS in brew:
brew install node@18
brew unlink node
brew link node@18
node -v

**Comment by aryankarim** [comment]
Dear fellow humans. 

Always be on the safe side and install node v.18.18.2 which is the LTS.
