### ISSUE TITLE
npx nuxi@latest init <my-project> Error reporting 

### ISSUE THREAD

**Issue by younglbj** [nuxt/nuxt#23262]
### Environment

npx nuxi@latest init <my-project> 

### Reproduction

No matching version found for nuxt@^3.7.3

### Describe the bug

The latest release of nuxt is "3.7.2".

Other releases are:
  * 1x: 1.4.5
  * rc: 3.0.0-rc.14
  * 2x: 2.17.1

If you need the full list of all 311 published versions run "$ pnpm view nuxt versions".

**Comment by danielroe** [comment]
I suspect this is an npm cache issue

![CleanShot 2023-09-18 at 09.17.28.png](https://volta.s3.fr-par.scw.cloud/Clean_Shot_2023_09_18_at_09_17_28_158bbe0db2.png)
