### ISSUE TITLE
Provide `addServerUtils` helper to `@nuxt/utils`

### ISSUE THREAD

**Issue by huang-julien** [nuxt/nuxt#23268]
### Describe the feature

Hi :wave:

We now have `addServerPlugin` and `addServerHandler` but not `addServerUtils` yet for `@nuxt/kit`

### Additional information

- [x] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by pi0** [comment]
I think we can introduce it as `addServerImports` / `addServerImportsDir` similar to currently `addImports`/ `addImportsDir` kit utils.

(utils/composables dirs are fs convention)

**Comment by huang-julien** [comment]
I'll try to do it when i'll have some time 🙂
