### ISSUE TITLE
Slow nuxt build of nitro on code changes when use DB

### ISSUE THREAD

**Issue by imcm7** [nuxt/nuxt#23271]
### Environment

- Operating System: Linux
- Node Version:     v18.17.1
- Nuxt Version:     3.7.1
- CLI Version:      3.8.1
- Nitro Version:    2.6.3
- Package Manager:  pnpm@8.7.1
- Builder:          -
- User Config:      alias, app, colorMode, css, dayjs, devtools, experimental, i18n, image, modules, nitro, pwa, runtimeConfig, security, spaLoadingTemplate, ssr, tailwindcss, viewport, vueEmail
- Runtime Modules:  @hebilicious/authjs-nuxt@0.3.0, @nuxt/image@1.0.0-rc.1, @nuxtjs/color-mode@3.3.0, @nuxtjs/i18n@8.0.0-rc.4, @nuxtjs/tailwindcss@6.8.0, @pinia/nuxt@0.4.11, @vee-validate/nuxt@4.11.6, @vueuse/nuxt@10.4.1, dayjs-nuxt@1.1.2, nuxt-security@0.14.4, nuxt-viewport@2.0.6, vue3-carousel-nuxt@1.1.0, vue-email/nuxt
- Build Modules:    -

### Reproduction

https://github.com/imcm7/nuxt-db/tree/main

### Describe the bug

When I use nitrojs only and make changes in server's code Nitrojs is build fast, but when I change server code in Nuxt nitro is build slow and eat all computers resource if I change a line of code in server dir.

**Comment by imcm7** [comment]
And if a error in code exists it not say what error and also not rebuild server and you get old error that no more exist and not get new error. And is need to re run it `pnmp run dev`

**Comment by imcm7** [comment]
And some thing with readBody occurs. Some time it work some time `TypeError: user.roles is not iterable
`

**Comment by danielroe** [comment]
Would you see if it's possible to make a nitro-only reproduction and open an issue on https://github.com/unjs/nitro? 🙏

**Comment by imcm7** [comment]
With nitro work well

**Comment by imcm7** [comment]
I have such code

```
export default eventHandler(async () => {
  const { em } = await useDatasource();

  return em.findOne(User, 1);

  // return { nitro: 'Is Awesome!' }
})

```

and server return 

```
{
  "nitro": "Is Awesome!"
}
```

**Comment by imcm7** [comment]
@danielroe https://github.com/unjs/nitro/issues/1734

**Comment by imcm7** [comment]
@danielroe with Bun I think it work well

**Comment by imcm7** [comment]
With bun server work well, but front not always rendered, white page in browser and it never stop load.

**Comment by imcm7** [comment]
After I make a change in nuxt.config file `error: script "dev" exited with code 11 (SIGSEGV)
`

**Comment by imcm7** [comment]
[Vue warn]: Component LayoutLoader is missing template or render function.

**Comment by danielroe** [comment]
cc: @pi0

**Comment by pi0** [comment]
Upstream ~> https://github.com/unjs/nitro/issues/1734

(also this is likely an implementation issue)
