### ISSUE TITLE
Nested NuxtLink/RouterLink components break SSR and throw a hydration mismatch

### ISSUE THREAD

**Issue by fabis94** [nuxt/nuxt#23274]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.16.0
- Nuxt Version:     3.7.3
- CLI Version:      3.8.4
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/fabis94/nested-nuxtlink-hydration-mismatch

### Describe the bug

The bug is that if you have nested NuxtLink instances, Nuxt (or Vue?) gets confused and breaks the HTML template in SSR. When the client-side app loads in it fixes the layout, but it's pretty ugly until it does and it also throws a hydration mismatch.

From my repro, this is what the Vue template looks like:
```
<template>
    <div class="index">
        <NuxtLink to="/other" class="card">
            <span>NuxtLink top text</span>
            <NuxtLink @click.stop.prevent="onNestedClick">Nested nuxt link</NuxtLink>
            <span>NuxtLink bottom text</span>
        </NuxtLink>
    </div>
</template>
```

But when SSR renders it, it completely breaks the resulting elements apart and comes up with something like this:
```
<div class="index" data-v-inspector="pages/index.vue:2:5">
    <a href="/other" class="card">
      <span data-v-inspector="pages/index.vue:4:7">NuxtLink top text</span>
    </a>
    <a>Nested nuxt link</a>
    <span data-v-inspector="pages/index.vue:6:7">NuxtLink bottom text</span>
</div>
```

The HTML is broken on multiple levels: The links are no longer nested and some of the content from the parent link is taken out and rendered outside of the component altogether.

### Additional context

This bug has been occurring for at least half a year at this point, so it's definitely not something new.

**Comment by danielroe** [comment]
It's not a bug; it's the HTML specification that (because `<a>` cannot be nested in another `<a>`) when the browser gets some HTML that has this, it will 'end' the previous `<a>` when it comes to the starting tag of the next a `<a>`.

This breaks SSR hydration. You can read more about this here: https://vuejs.org/guide/scaling-up/ssr.html#hydration-mismatch

**Comment by fabis94** [comment]
@danielroe Is there a way to force NuxtLink/RouterLink to mount as a different element instead? I do want all of the other logic that NuxtLink/RouterLink brings, just not the anchor element, and from NuxtLink's props it doesn't appear that it can do that

**Comment by fabis94** [comment]
Also - maybe this should be thrown as a warning or something? If you haven't memorized the HTML spec it's unlikely you're going to know of such an edge case and then trying to figure out why this happens is nearly impossible

**Comment by danielroe** [comment]
Yes, you can use `custom` prop to handle navigation/rendering manually.

And it would be a great idea to throw a warning. We could improve Vue's handling of these hydration errors (which I think would be a good idea). But I also have an idea to improve from Nuxt's end, as well
