### ISSUE TITLE
Server components reactivity not updating

### ISSUE THREAD

**Issue by bootsmann1995** [nuxt/nuxt#23277]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.7.3
- CLI Version:      3.8.4
- Nitro Version:    2.6.3
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      experimental
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-jkwmep?file=components%2Fislands%2FTropicalIsland.vue

### Describe the bug

I'm using @vueuse/nuxt & @vueuse/core to set isLargeScreen. When changing the screen with the isLargeScreen Proptery changes to true when going to a phone view. 

This property is not updated in the server component. 

I pass the property as a prop on the import.

<ServerComponent :count="secondCount" :is-large-screen="isLargeScreen" />

open the stackblitz and try minimizin the screen. As you can see the property is still false. even it the size of the screen is mobile.

It is only the mediaScreen property that doesn't update. As you can see there is a click function that increments a count, this works as intended.

**Comment by danielroe** [comment]
I might be misunderstanding, but I can't reproduce this.


https://github.com/nuxt/nuxt/assets/28706372/96027087-7023-42b9-89e3-4ec1e7308497

**Comment by bootsmann1995** [comment]
@danielroe  Works fine in edge/chrome. But when using firefox it doesnt work. I get this console error: 

![image](https://github.com/nuxt/nuxt/assets/65391517/ce783cb3-3b45-47df-84f6-9aae30123ac0)


the client side works fine, but the server component doesn't work properly on initial state. 

if I press "add +1 to count" on the servercomponent it works fine afterwards. So if the reactivity is triggered it works afterwards.

Not on initial component state.

**Comment by danielroe** [comment]
Oh, that's likely not an issue with server component reactivity but just about your default window size on firefox vs chrome.

I would guess it's probably a normal hydration error. You shouldn't use things like screen size in an initial render because the server can't know the screen size of the client, and this can cause a hydration error.
