### ISSUE TITLE
Can't register listeners inside onMounted (DOMContentLoaded / window.load events)

### ISSUE THREAD

**Issue by mkierdev** [nuxt/nuxt#23281]
### Environment

Nuxt 3.7.3 as well as 3.5 (other versions not tested)

### Reproduction

https://stackblitz.com/edit/github-aeewhc?file=pages%2Findex.vue

or paste this in your page.vue:
```js
<script setup>
onMounted(() => {
  window.addEventListener('load', (event) => {
    console.log('page is fully loaded');
  });
});
</script>
```

### Describe the bug

It appears that when we use pages catalog we don't have access to load event listeners inside onmounted, like DOMContentLoaded. Scroll event works fine.

When I remove pages folder and stick to app.vue only, event listener works as expected and fires when page is loaded.

**Comment by MrEraxd** [comment]
Hi @mkierdev I don't think it is nuxt issue as I can reproduce it with just Vue. I can assume that browsers fires load event before app is fully mounted. Check if using `beforeMount` method will fit your needs: https://vuejs.org/api/options-lifecycle.html#beforemount

Vue reproduction link: https://stackblitz.com/edit/vue-sds8s8?file=src%2FApp.vue

**Comment by mkierdev** [comment]
In my case, onNuxtReady() was enough to fit my needs.
https://nuxt.com/docs/api/utils/on-nuxt-ready#onnuxtready
