### ISSUE TITLE
`nuxt` generate starting 3.7.0

### ISSUE THREAD

**Issue by posva** [nuxt/nuxt#23283]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.3.1`
- Nuxt Version:     `3.7.3`
- CLI Version:      `3.8.4`
- Nitro Version:    `2.6.4-28243740.058bacf`
- Package Manager:  `pnpm@8.6.11`
- Builder:          `-`
- User Config:      `ssr`, `devtools`, `app`, `css`, `nitro`, `modules`, `vuefire`, `experimental`, `routeRules`
- Runtime Modules:  `nuxt-vuefire@0.3.0`, `@vueuse/nuxt@10.4.1`
- Build Modules:    `-`

### Reproduction

- https://github.com/posva/nuxt--vuefire-example-spark-plan

It's a bit big but I thought you might want to know about this either way.

### Describe the bug

In 3.6:

![Screenshot 2023-09-18 at 18 27 01](https://github.com/nuxt/nuxt/assets/664177/a7126831-6dba-4a9d-90ef-51ec3cdcdf23)

in 3.7.3:

![Screenshot 2023-09-18 at 18 29 56](https://github.com/nuxt/nuxt/assets/664177/1ee75359-ec45-4c5c-9bc2-3109afeec0da)

**Comment by danielroe** [comment]
thank you ❤️ 

let's track in https://github.com/nuxt/cli/issues/169. There are a couple of other issues there too with the same root cause.
