### ISSUE TITLE
3.7.3  The breakpoint is completely unusable and cannot be bound

### ISSUE THREAD

**Issue by hmuyin** [nuxt/nuxt#23282]
### Environment

3.7.3  The breakpoint is completely unusable and cannot be bound

### Reproduction

The breakpoint is completely unusable and cannot be bound

### Describe the bug

3.7.3  The breakpoint is completely unusable and cannot be bound

**Comment by hmuyin** [comment]
At startup, it works normally, and the code changes at any time, but gradually it doesn't work

launch.json
`  {
            "name": "Nuxt Server: Nuxt",
            "type": "node",
            "sourceMaps": true,
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "runtimeExecutable": "npm",
            "runtimeArgs": [
                "run",
                "dev"
            ],
            "console": "integratedTerminal"
        }`

or

`"configurations": [
        {
            "name": "nuxt3-server",
            "request": "launch",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "type": "node-terminal",
            "command": "npm run dev",
            "cwd": "${workspaceFolder}/",
        }
    ]`

or
`"scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },`

After this 3.7.3 update And I updated it
After updating to nuxt3.7.3 and vscode1.82.2 versions
And I completely initialized vscode, both of which encountered this issue

**Comment by bubu-bin** [comment]
I want to report also have this problem when trying to debug inside VSCode IDE
The `index.mjs` is correctly reproduced after save and it seems like `index.mjs.map` is also updating inside `.nuxt/dev/...` but the VSCode debugger is not able to follow up these changes and the breakpoint is either pointing at wrong place or is completely disabled
Also I checked that source maps are loaded correctly
To be able to debug I need to restart the nuxt dev each time which is time consuming

`launch.json` that is taken directly from [official documentation](https://nuxt.com/docs/guide/going-further/debugging) 
```
{
      "type": "node",
      "request": "launch",
      "name": "web:server",
      "outputCapture": "std",
      "program": "${workspaceFolder}/node_modules/nuxi/bin/nuxi.mjs",
      "console": "integratedTerminal"
}
```

**Comment by hmuyin** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
