### ISSUE TITLE
Build Fail - Cloudflare Pages

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [nuxt/nuxt#23299]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.15.0
- Nuxt Version:     3.7.3
- CLI Version:      3.8.3
- Nitro Version:    2.6.3
- Package Manager:  npm@9.5.0
- Builder:          -
- User Config:      runtimeConfig, modules, image, sitemap, jsoneditor, colorMode, css, routeRules, nitro
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @pinia/nuxt@0.4.11, @pinia-plugin-persistedstate/nuxt@1.1.1, @nuxtjs/color-mode@3.3.0, nuxt-jsoneditor@1.7.0, nuxt-simple-sitemap@0.5.10, @nuxt/image-edge@1.0.0-rc.2-28244125.e6e72be
- Build Modules:    -
------------------------------

### Reproduction

Tested on new small project working without issue

### Describe the bug

21:06:57.425 | [log] [nitro]   └─ /sitemap.xml (5ms)
-- | --
21:06:57.441 | [info] [nitro] Building Nitro Server (preset: `cloudflare-pages`)
21:08:09.285 | [error] [nitro] SyntaxError: 'with' in strict mode (10:4) in /opt/buildhome/repo/node_modules/domino/lib/sloppy.js
21:08:09.285 |  
21:08:09.285 |  
21:08:09.286 | 8:   Window_run: function _run(code, file) {
21:08:09.286 | 9:     if (file) code += '\n//@ sourceURL=' + file;
21:08:09.286 | 10:     with(this) eval(code);
21:08:09.286 | ^
21:08:09.286 | 11:   },
21:08:09.286 | 12:   EventHandlerBuilder_build: function build() {
21:08:09.288 | [error] 'with' in strict mode (10:4) in /opt/buildhome/repo/node_modules/domino/lib/sloppy.js
21:08:09.288 | at pp$4.raise (node_modules/rollup/dist/es/shared/node-entry.js:21616:13)
21:08:09.288 | at pp$8.parseWithStatement (node_modules/rollup/dist/es/shared/node-entry.js:19252:27)
21:08:09.289 | at pp$8.parseStatement (node_modules/rollup/dist/es/shared/node-entry.js:18981:35)
21:08:09.289 | at pp$8.parseBlock (node_modules/rollup/dist/es/shared/node-entry.js:19306:21)
21:08:09.289 | at pp$5.parseFunctionBody (node_modules/rollup/dist/es/shared/node-entry.js:21435:22)
21:08:09.289 | at pp$8.parseFunction (node_modules/rollup/dist/es/shared/node-entry.js:19428:8)
21:08:09.289 | at pp$5.parseExprAtom (node_modules/rollup/dist/es/shared/node-entry.js:20961:17)
21:08:09.289 | at pp$5.parseExprSubscripts (node_modules/rollup/dist/es/shared/node-entry.js:20764:19)
21:08:09.289 | at pp$5.parseMaybeUnary (node_modules/rollup/dist/es/shared/node-entry.js:20730:17)
21:08:09.289 | at pp$5.parseExprOps (node_modules/rollup/dist/es/shared/node-entry.js:20657:19)
21:08:09.290 | at pp$5.parseMaybeConditional (node_modules/rollup/dist/es/shared/node-entry.js:20640:19)
21:08:09.290 | at pp$5.parseMaybeAssign (node_modules/rollup/dist/es/shared/node-entry.js:20607:19)
21:08:09.290 | at pp$5.parsePropertyValue (node_modules/rollup/dist/es/shared/node-entry.js:21301:87)
21:08:09.290 | at pp$5.parseProperty (node_modules/rollup/dist/es/shared/node-entry.js:21275:8)
21:08:09.290 | at pp$5.parseObj (node_modules/rollup/dist/es/shared/node-entry.js:21230:21)
21:08:09.290 | at pp$5.parseExprAtom (node_modules/rollup/dist/es/shared/node-entry.js:20956:17)
21:08:09.290 | at pp$5.parseExprSubscripts (node_modules/rollup/dist/es/shared/node-entry.js:20764:19)
21:08:09.290 | at pp$5.parseMaybeUnary (node_modules/rollup/dist/es/shared/node-entry.js:20730:17)
21:08:09.290 | at pp$5.parseExprOps (node_modules/rollup/dist/es/shared/node-entry.js:20657:19)
21:08:09.291 | at pp$5.parseMaybeConditional (node_modules/rollup/dist/es/shared/node-entry.js:20640:19)
21:08:09.291 | at pp$5.parseMaybeAssign (node_modules/rollup/dist/es/shared/node-entry.js:20607:19)
21:08:09.291 | at pp$5.parseMaybeAssign (node_modules/rollup/dist/es/shared/node-entry.js:20625:23)
21:08:09.291 | at pp$5.parseExpression (node_modules/rollup/dist/es/shared/node-entry.js:20570:19)
21:08:09.291 | at pp$8.parseStatement (node_modules/rollup/dist/es/shared/node-entry.js:19014:45)
21:08:09.291 | at pp$8.parseTopLevel (node_modules/rollup/dist/es/shared/node-entry.js:18881:21)
21:08:09.291 | at Parser.parse (node_modules/rollup/dist/es/shared/node-entry.js:18653:15)
21:08:09.291 | at Function.parse (node_modules/rollup/dist/es/shared/node-entry.js:18703:35)
21:08:09.292 | at Graph.contextParse (node_modules/rollup/dist/es/shared/node-entry.js:25749:38)
21:08:09.292 | at tryParse (node_modules/@rollup/plugin-commonjs/dist/es/index.js:17:12)
21:08:09.292 | at analyzeTopLevelStatements (node_modules/@rollup/plugin-commonjs/dist/es/index.js:36:15)
21:08:09.292 | at Object.transformAndCheckExports (node_modules/@rollup/plugin-commonjs/dist/es/index.js:2066:68)
21:08:09.292 | at Object.transform (node_modules/@rollup/plugin-commonjs/dist/es/index.js:2257:41)
21:08:09.292 | at node_modules/rollup/dist/es/shared/node-entry.js:25539:40
21:08:09.292 |  
21:08:09.292 | [error] 'with' in strict mode (10:4) in /opt/buildhome/repo/node_modules/domino/lib/sloppy.js
21:08:09.483 | Failed: build command exited with code: 1
21:08:10.724 | Failed: error occurred while running build command

### Additional context

[Package.json](https://goonlinetools.com/snapshot/code/#8z3yu2l7eu5uj525ijo98)
[Nuxt.config.js](https://goonlinetools.com/snapshot/code/#gs4gfr7n1t6hwwttr8qcau)

**Comment by pi0** [comment]
Would you please provide a reproduction repository? 🙏🏼 

Quickly looking at logs, seems issue is related to `domino`.

**Comment by rahulkumarsingh73690** [comment]
What is domino @pi0

**Comment by rahulkumarsingh73690** [comment]
`Error: Failed to publish your Function. Got error: Uncaught TypeError: J10 is not a function   at functionsWorker-0.5227086407614521.js:52228:13   at functionsWorker-0.5227086407614521.js:52230:2`

**Comment by pi0** [comment]
Happy hearing the first one is now resolved. We still need a runnable reproduction in order to help. 

Hint: you can set `nitro: { minify: false }` in nuxt config to see a better trace of your errors.

**Comment by rahulkumarsingh73690** [comment]
`Error: Failed to publish your Function. Got error: Uncaught TypeError: _interopRequireDefault2 is not a function   at functionsWorker-0.1932807715472311.js:135557:18   at functionsWorker-0.1932807715472311.js:135575:3`

**Comment by pi0** [comment]
Seems like a rollup bundling issue. Are you able to share your repository @rahulkumarsingh73690 ?

**Comment by rahulkumarsingh73690** [comment]
No, it's too big and confidential. 

Can you please help with another issue? #22254

**Comment by pi0** [comment]
Unfortunately cannot help any further in this case without reproduction. Sorry.

Please let me know if you could to make a minimal reproduction to investigate more 

Tip: You can try to enable/disable each module/plugin one by one to find out about the problematic one and then make a reproduction that can be shared but only has that module enabled.
