### ISSUE TITLE
Fixed Bug: Nuxt3 some components load slowly

### ISSUE THREAD

**Issue by Tengxu666** [nuxt/nuxt#23305]
### Environment

 Operating System: Darwin
- Node Version:     v16.20.0
- Nuxt Version:     3.7.3
- CLI Version:      3.8.4
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.17
- Builder:          -
- User Config:      css, app, modules, plugins, piniaPersistedstate, tailwindcss, vite, nitro
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @pinia/nuxt@0.4.11, @pinia-plugin-persistedstate/nuxt@1.1.2, nuxt-icon@0.5.0, @element-plus/nuxt@1.0.6
- Build Modules:    -

### Reproduction

None

### Describe the bug

When I use Pina or Editor, the page loads more slowly than the other components
I found a way to fix it

app.vue
```
  <div id="app" class="hidden">
      <NuxtPage />
  </div>
```

hidden -> tailwindcss

~/plugins/loading.ts

```
export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.hook('page:finish', () => {
        const app = document.querySelector('#app')
        // @ts-ignore
        app.className = app.className.replace('hidden', '')
    })

})
```

remove hidden when the page has finished loading

**Comment by Aurion72** [comment]
Since 3.7.x, nuxtjs load very slowly yep.

I can't say why exactly, im using Ubuntu on WSL2 from windows 11

First starting and full page reload are extremly slows

**Comment by imcm7** [comment]
> Since 3.7.x, nuxtjs load very slowly yep.
> 
> I can't say why exactly, im using Ubuntu on WSL2 from windows 11
> 
> First starting and full page reload are extremly slows

`bun run dev`

**Comment by danielroe** [comment]
I think the issue here is with nuxt/cli. See https://github.com/nuxt/cli/issues/209 (including steps to upgrade `nuxi` and provide feedback if that doesn't solve the issue for you).
