### ISSUE TITLE
After setting the URL proxy_pass , js or css cannot be found

### ISSUE THREAD

**Issue by bme6** [nuxt/nuxt#23304]
### Environment

- Operating System: Windows_NT
- Node Version:     v16.13.2
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@9.8.1
- Builder:          vite
- User Config:      devtools, css, build, modules, nitro, elementPlus
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @pinia/nuxt@0.4.11, @element-plus/nuxt@1.0.5, @vueuse/nuxt@10.3.0
- Build Modules:    -

### Reproduction

run `npm run build`，

### Describe the bug

For example, using Nginx to configure `a.com/test` to be forwarded to` localhost:3000`, and the resources are using absolute paths. The automatically generated JS or CSS files will be using the address `a.com/_nuxt/***`, which leads to resource not found. Actually, it should be` a.com/test/_ Nuxt/**`

**Comment by MrEraxd** [comment]
Hi, it looks like it is implementation issue not nuxt issue. You should not have app visible under non root path this can cause errors like yours and lead to further linking errors after deployment. I would suggest you to use subdomains instead. Server below is working perfectly fine for me:

```
server {
        listen       80;
        server_name  local.example.com;

        location / {
            proxy_pass http://localhost:3000;
        }
    }
```

If you want to stick with your solution, you can try to redirect `a.com/_nuxt/**` to `a.com/test/_nuxt/**` also using nginx.
