### ISSUE TITLE
dev js loading is very slow

### ISSUE THREAD

**Issue by suningkooboo** [nuxt/nuxt#23309]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.17.1
- Nuxt Version:     3.7.3
- CLI Version:      3.8.4
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.4
- Builder:          -
- User Config:      ssr, experimental, runtimeConfig, modules, ui, tailwindcss, i18n, viewport, proxy, imports, devtools, typescript, $production
- Runtime Modules:  @nuxt-alt/proxy@2.3.2, @nuxtjs/google-fonts@3.0.2, @nuxt/image@1.0.0-rc.2, nuxt-icon@0.4.2, @nuxtjs/i18n@8.0.0-rc.4, nuxt-viewport@2.0.6, nuxt-swiper@1.2.2, @nuxt/ui@2.8.1, @vueuse/nuxt@10.4.1
- Build Modules:    -

### Reproduction

- upgrade nuxt from 3.6.2 to 3.7.3
- in Windows system run yarn dev

### Describe the bug

JS files including .vue files loading are quite slow. Need to wait 10 minutes (we are bigger project) to finish and onMounted start to run.

It do not happen in Mac system

**Comment by imcm7** [comment]
try bun

**Comment by imcm7** [comment]
https://github.com/nuxt/nuxt/issues/23271#issuecomment-1725393679

**Comment by darioferderber** [comment]
@suningkooboo have you tried `127.0.0.1:3000` instead of `localhost:3000`?

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/cli/issues/209.
