### ISSUE TITLE
error caught during app initialization Error: Page not found: /xxxx

### ISSUE THREAD

**Issue by xuzhihui123** [nuxt/nuxt#23317]
### Environment

"nuxt": "^3.7.3"

### Reproduction

https://stackblitz.com/edit/github-ottvmj?file=pages%2Findex.vue

### Describe the bug

I created an error.vue page, but when I input a non-existent route, such as/kkl, the browser's console outputs an error message: error caution during app initialization Error: Page not found:/kkl. The entire page is blank

**Comment by MrEraxd** [comment]
Hi @xuzhihui123 it looks like it is not a bug but intended bevaviour. You are opening an error page so we can asume that there is an error in your app which causes error to occur in console.

This is the code that is responsible for showing this exact error:

[Link to file](https://github.com/nuxt/nuxt/blob/eab27717b8364b4c71c1972ba3a550ccc2bbd29e/packages/nuxt/src/app/nuxt.ts#L307)

Regarding blank page, could you please check once again, reproduction link that you've provided is working for me (Text is visible)

![image](https://github.com/nuxt/nuxt/assets/34748386/177e5e36-a3d6-4c60-9fac-36908c200f0a)

**Comment by xuzhihui123** [comment]
If I print props in error. vue, they are not printed or redirected
![image](https://github.com/nuxt/nuxt/assets/42968962/00a5af7c-4ee0-4094-a8b8-ee44442f4f16)

**Comment by xuzhihui123** [comment]
Okay, I understand what to do now. Thank you
