### ISSUE TITLE
Using <component :is="'style'" type="text/css"> with slots produces hydration missmatch only in nuxt3 (vue+vite works fine)

### ISSUE THREAD

**Issue by SebbeJohansson** [nuxt/nuxt#23323]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.7.0
- Nuxt Version:     3.7.3
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Here is a reporduction version of this issue: https://stackblitz.com/edit/nuxt-starter-nufrzf?file=components%2FDynamicStyle.vue,app.vue
Please note that issues like this don't visually show in Stackblitz. You need to run it locally.

Here is an example from Vue with vite where it doesnt happen: https://stackblitz.com/edit/vitejs-vite-zcf5i1?file=src%2Fcomponents%2FDynamicStyle.vue,src%2FApp.vue&terminal=dev

### Describe the bug

When using `<component :is="'style'" type="text/css">` with named slots, a "Hydration text mismatch" happens. This seems to not happen when running vue with vite, but I am not 100% sure that this isn't something downstream.

### Additional context

I have a solution for my specific use-case: https://gist.github.com/SebbeJohansson/c76ecfcc019c11cda6e3abfa2e946efa
Kinda nasty, but it works.

### Logs

```shell-script
vue.js:1449 [Vue warn]: Hydration text mismatch:
- Client: " @media (max-width: 767px){ /* mobile */ <!--[--> .text-image-block__column { grid-column: span 1; } <!--]--> } @media (min-width: 768px) and (max-width: 1023px) { /* tablet */ <!--[--> .text-image-block__column { grid-column: span 2; } <!--]--> } @media (min-width: 1024px){ /* desktop */ <!--[--> .text-image-block__column { grid-column: span 2; } <!--]--> } "
- Server: " @media (max-width: 767px){ /* mobile */ " 
  at <DynamicStyle> 
  at <App key=3 > 
  at <NuxtRoot>
warn2 @ vue.js:1449
hydrateNode @ vue.js:5957
hydrateChildren @ vue.js:6180
hydrateElement @ vue.js:6136
hydrateNode @ vue.js:6014
hydrateChildren @ vue.js:6180
hydrateElement @ vue.js:6136
hydrateNode @ vue.js:6014
hydrateSubTree @ vue.js:7073
componentUpdateFn @ vue.js:7093
run @ vue.js:423
instance.update @ vue.js:7212
setupRenderEffect @ vue.js:7220
mountComponent @ vue.js:7010
hydrateNode @ vue.js:6026
hydrateChildren @ vue.js:6180
hydrateElement @ vue.js:6136
hydrateNode @ vue.js:6014
hydrateSubTree @ vue.js:7073
componentUpdateFn @ vue.js:7093
run @ vue.js:423
instance.update @ vue.js:7212
setupRenderEffect @ vue.js:7220
mountComponent @ vue.js:7010
hydrateNode @ vue.js:6026
hydrateSuspense @ vue.js:2953
hydrateNode @ vue.js:6066
hydrateSubTree @ vue.js:7073
componentUpdateFn @ vue.js:7093
run @ vue.js:423
instance.update @ vue.js:7212
setupRenderEffect @ vue.js:7220
mountComponent @ vue.js:7010
hydrateNode @ vue.js:6026
hydrate2 @ vue.js:5920
mount @ vue.js:5213
app.mount @ vue.js:10556
initApp @ null:55
await in initApp (async)
(anonymous) @ null:64
vue.js:1449 [Vue warn]: Hydration children mismatch in <style>: server rendered element contains fewer child nodes than client vdom. 
  at <DynamicStyle> 
  at <App key=3 > 
  at <NuxtRoot>
```

**Comment by SebbeJohansson** [comment]
Just to double check i tested with `<Style>` and that doesn't seem to work with slots at all. That might be a better solution than fixing what ever hydration issue is cause by this.
![image](https://github.com/nuxt/nuxt/assets/5083273/b0b3b64d-6df7-4a18-b7b3-78fb4398fd96)

**Comment by MrEraxd** [comment]
@SebbeJohansson you should not use <style> in your vue components at all. I don't know your use case but if you need some variable then I would sugest you to create Vue composable that will contain breakpoints and change class based on current breakpoint. I've created such example for you:

[Stack-blitz](https://stackblitz.com/edit/nuxt-starter-xamccr?file=components%2FDynamicStyledComponent.vue)

Of course the best solution would be to use style tag inside component. I understand that this will be harder to maintain if breakpoints will change later but it looks like the best option for now. 

If you are using SCSS you can also take a look at this article: [Article link](https://bholmes.dev/blog/alternative-to-css-variable-media-queries/)

**Comment by danielroe** [comment]
This is likely a Vue 3 SSR behaviour. Try with https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter to see.

**Comment by SebbeJohansson** [comment]
@MrEraxd maybe you are misunderstanding. The style tag I'm using in the last example isn't a normal style tag. It's one of the meta tags. Perfectly fine to use them in templates (since that's where they belong).
Your example isn't applicable for me since I need to add custom styling that are decided particular parts or fully coming from our cms. I understand that there are workarounds and such, but this issue is more to figure out if we can get something better that works. Mainly because a perfectly fine solution exists in nuxt2.

@danielroe I will check in vue-ssr when I have the chance. Sorry for not checking with that right away. It being in ssr is of course logical.

**Comment by danielroe** [comment]
For what it's worth, I would recommend using `useHead` instead of the Style component.

**Comment by SebbeJohansson** [comment]
> For what it's worth, I would recommend using `useHead` instead of the Style component.
> 
> But using `component :is="style"` will not resolve the `<Style>` component - it will resolve the normal `style` tag, IIRC.

@danielroe is there a reason to use `useHead` instead of the Style component or is it just a preference?

And yes, `<component :is="style">` does produce a normal style tag, which is what I would want.

**Comment by SebbeJohansson** [comment]
@danielroe is there a reason to use one over the other, other than preference?

And yes, it does produce a normal style tag, which is what I would want.

**Comment by SebbeJohansson** [comment]
Yes i can reproduce with vue + ssr.
https://stackblitz.com/edit/github-tzgxfc?file=src%2Fpages%2FHome.vue

I will make an issue there.
