### ISSUE TITLE
unable to remove `vue-shim.d.ts`

### ISSUE THREAD

**Issue by guy-confetti** [nuxt/nuxt#23320]
### Environment

- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.7.3
- CLI Version:      3.8.4
- Nitro Version:    2.6.3
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      typescript
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-hxa6oa?file=nuxt.config.ts

### Describe the bug

according to the [installation docs](https://nuxt.com/docs/getting-started/installation#prerequisites), it's recommended to disable the vue shim when using Volar:
```ts
export default defineNuxtConfig({
  typescript: {
    shim: false
  }
})
```
but it doesn't seem to work. see `.nuxt/types/vue-shim.d.ts` after running `nuxt prepare`.

### Additional context

https://github.com/nuxt/nuxt/blame/v3.7.3/packages/nuxt/src/core/nuxt.ts#L66

**Comment by danielroe** [comment]
Nuxt still generates the file but doesn't add a reference to it into your `nuxt.d.ts`. We could likely remove it entirely.
