### ISSUE TITLE
3.7.3 server devProxy not working

### ISSUE THREAD

**Issue by jaspergg** [nuxt/nuxt#23339]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v16.20.0
- Nuxt Version:     3.7.3
- CLI Version:      3.8.4
- Nitro Version:    2.6.3
- Package Manager:  pnpm@7.31.0
- Builder:          -
- User Config:      devtools, modules, css, runtimeConfig, pinia, nitro
- Runtime Modules:  @pinia/nuxt@0.4.11, @vueuse/nuxt@10.4.1, @unocss/nuxt@0.56.0
- Build Modules:    -
------------------------------

### Reproduction

server:

[Vue Router warn]: No match found for location with path "/api/user/userInfo"

### Describe the bug

<img width="810" alt="image" src="https://github.com/nuxt/nuxt/assets/93196496/0166dfe9-2960-4952-b198-c3bf64f17225">

<template>
  <div>测试：{{ data }}</div>
</template>

<script setup lang="ts">
const { data } = useFetch("/api/user/userinfo", {
  method: "POST",
});
</script>

<style scoped></style>

**Comment by danielroe** [comment]
Would you see if you can reproduce with just nitro, and (if so) create an upstream issue in https://github.com/unjs/nitro ?
