### ISSUE TITLE
Middleware AddRoute + Redirect Results in Infinite Redirect Loop

### ISSUE THREAD

**Issue by epasch** [nuxt/nuxt#23337]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.17.0
- Nuxt Version:     3.7.3
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      modules
- Runtime Modules:  @nuxt/devtools@0.8.4
- Build Modules:    -
------------------------------

### Reproduction

Here is a repo with my test set up: [Reproduction Repo](https://github.com/epasch/nuxt-dynamic-routes-test )

run "yarn && yarn dev" to kick it off
go to: [http://localhost:3000/columnists/test/link/](http://localhost:3000/columnists/test/link/) 
That link should trigger the middleware to add a route and replace it accordingly

If you change the Nuxt package version to 3.4.0 it works fine. Anything later than that and it will get stuck in an infinite redirect loop as routes added are forgotten after the redirect.

### Describe the bug

We use a CMS called Sitecore which allows a hierarchical URL structure where any given template could be anywhere in that content tree. Thus to use Nuxt, I need first do an API call to the CMS to pull back the data for that item (based on the Uri path), check what Template is required, add an appropriate route that ties that Path to  the correct Page Template.

I've added a global route middleware that does the following:

- Takes the path and generates a unique "name" for that path
- Verifies the route doesn't already exist and that this path is a valid Sitecore path
- Does an async data fetch to get a template name back (avoiding actual API calls for this test)
- Creates the route using router.addRoute()
- returns navigateTo() to force the system to pick up that route

This works fine against Nuxt 3.4.0. Any version later than that results in an infinite redirect loop. After the navigateTo triggers a redirect, the next time through, the router seems to have lost the new route that was added. Goes something like this:

- Route Doesn't exist
- Add Route
- Redirect
- Route Doesn't exist (it should exist at this point)
- Add Route
- Redirect
- etc

I'm guessing the issue is related to this PR that released with 3.4.1 [https://github.com/nuxt/nuxt/pull/20244](https://github.com/nuxt/nuxt/pull/20244)

Any added routes should carry over after navigateTo is called with an internal redirect.

**Comment by or2e** [comment]
@epasch 
Try replacing `navigatetTo` with `return to.fullPath`

By the way, I would define the functions of the components beforehand

**Comment by vhovorun** [comment]
@epasch Hey, have you fount some other way how to do that? Cause now stuck with the same problem

**Comment by TheDutchCoder** [comment]
This also happens in non-dynamically added middleware btw, I'm also getting infinite loops with something simple like this:

```ts
export default defineNuxtRouteMiddleware((to, from) => {
  if (true) { // go from :3000 to :3010
    return navigateTo(`https://localhost:3010`, { external: true })
  }
})
```

**Comment by Ed1ks** [comment]
Im trying to make an auth middleware. But if I run and Debug, it opens the webbrowser and constantly repeating to the navigateTo() Line, without changing the Url in Webbrowser (Stuck in redirect loop).
If I reload the Browser, it works and I will get redirected to the any.page.com.



# middleware/auth.global.ts:
```
export default defineNuxtRouteMiddleware(async (to, from) => {
    if (to.path !== "/api/auth/login") {
        // user.value is false
        user.value = await $fetch("/api/user");
        if (!user.value) return navigateTo("/api/auth/login", {external: true})
      }
});
```

# server/api/auth/login/index.get.ts
```
export default defineEventHandler(async (event) => {
    console.log("I got redirected")
    const url = "https://any.page.com"
    await sendRedirect(event, url, 302);
});
```

**Comment by danielroe** [comment]
The way a server redirect (or one marked with `external: true`) works is that it just sends the new location as a string to the browser. The browser then makes a new request. The new route that's been added doesn't persist on the server because it's a _new request_.

So any logic you have to handle these kind of requests needs to make sure it adds that new route consistently, or you can easily create redirect loops.

In the case of the original repro here, hitting the endpoint will send the following response:

```
http localhost:3000/columnists/test/link
HTTP/1.1 200 OK
access-control-allow-origin: *
connection: close
content-length: 107
content-type: text/html
date: Fri, 26 Jan 2024 09:32:42 GMT
location: /columnists/test/link

<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=/columnists/test/link"></head></html>
```

That is because in your middleware that is exactly what you are doing - sending a redirect every time that path is hit.

**Comment by Ed1ks** [comment]
> The way a server redirect (or one marked with `external: true`) works is that it just sends the new location as a string to the browser. The browser then makes a new request. The new route that's been added doesn't persist on the server because it's a _new request_.
> 
> So any logic you have to handle these kind of requests needs to make sure it adds that new route consistently, or you can easily create redirect loops.
> 
> In the case of the original repro here, hitting the endpoint will send the following response:
> 
> ```
> http localhost:3000/columnists/test/link
> HTTP/1.1 200 OK
> access-control-allow-origin: *
> connection: close
> content-length: 107
> content-type: text/html
> date: Fri, 26 Jan 2024 09:32:42 GMT
> location: /columnists/test/link
> 
> <!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=/columnists/test/link"></head></html>
> ```
> 
> That is because in your middleware that is exactly what you are doing - sending a redirect every time that path is hit.

Can you please show a working example?

**Comment by Ed1ks** [comment]
> The way a server redirect (or one marked with `external: true`) works is that it just sends the new location as a string to the browser. The browser then makes a new request. The new route that's been added doesn't persist on the server because it's a _new request_.
> 
> So any logic you have to handle these kind of requests needs to make sure it adds that new route consistently, or you can easily create redirect loops.
> 
> In the case of the original repro here, hitting the endpoint will send the following response:
> 
> ```
> http localhost:3000/columnists/test/link
> HTTP/1.1 200 OK
> access-control-allow-origin: *
> connection: close
> content-length: 107
> content-type: text/html
> date: Fri, 26 Jan 2024 09:32:42 GMT
> location: /columnists/test/link
> 
> <!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=/columnists/test/link"></head></html>
> ```
> 
> That is because in your middleware that is exactly what you are doing - sending a redirect every time that path is hit.

The cruel part is, that the url is not updated and stays the same. Could you please try my code and reopen this issue?

**Comment by danielroe** [comment]
The URL doesn't update because the way your code is written generates an infinite loop and the browser keeps making new requests.

**Comment by Ed1ks** [comment]
@danielroe 
> The URL doesn't update because the way your code is written generates an infinite loop and the browser keeps making new requests.

this is how the docs are showing it.
https://nuxt.com/docs/api/utils/navigate-to

**Comment by Ed1ks** [comment]
> @danielroe
> 
> > The URL doesn't update because the way your code is written generates an infinite loop and the browser keeps making new requests.
> 
> this is how the docs are showing it. https://nuxt.com/docs/api/utils/navigate-to

I know that it makes infinite requests and is in a loop. Thats why I am here, as I am trying to make an redirect with navigateTo() in middleware and am using it how the docs are explaining it. But the infinite loop is not the expected behavior.

**Comment by danielroe** [comment]
What the docs do, correctly, is check  that they are not redirecting to the same path they are already on, with this check `if (to.path !== '/search')`

**Comment by Ed1ks** [comment]
> if (to.path !== "/api/auth/login") {

This is exactly what I am doing:

if (to.path !== "/api/auth/login")

**Comment by danielroe** [comment]
Would you provide a reproduction then? I didn't realise you were not the original issue creator and that you were trying something else.

**Comment by Ed1ks** [comment]
> Im trying to make an auth middleware. But if I run and Debug, it opens the webbrowser and constantly repeating to the navigateTo() Line, without changing the Url in Webbrowser (Stuck in redirect loop). If I reload the Browser, it works and I will get redirected to the any.page.com.
> 
> # middleware/auth.global.ts:
> ```
> export default defineNuxtRouteMiddleware(async (to, from) => {
>     if (to.path !== "/api/auth/login") {
>         // user.value is false
>         user.value = await $fetch("/api/user");
>         if (!user.value) return navigateTo("/api/auth/login", {external: true})
>       }
> });
> ```
> 
> # server/api/auth/login/index.get.ts
> ```
> export default defineEventHandler(async (event) => {
>     console.log("I got redirected")
>     const url = "https://any.page.com"
>     await sendRedirect(event, url, 302);
> });
> ```

Sure. Thank you for checking it.
