### ISSUE TITLE
Bug: Layer not working with server api prerender method

### ISSUE THREAD

**Issue by Triloworld** [nuxt/nuxt#23336]
### Environment

https://stackblitz.com/edit/github-9qzebw-dofrfr

### Reproduction

https://stackblitz.com/edit/github-9qzebw-dofrfr?file=dist
Run: `npm install && npm run dev`
Workinf fine and can be generated. Env variable in place to force generating in stackblitz
Try: `npm install && npm run generate`
Check output for `/functions` catalog
No function on root, on `.output/public` or anywhere

### Describe the bug

- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.7.3
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools, extends
- Runtime Modules:  -
- Build Modules:    -

### Additional context

Forcing generate Cloudflare function from Layer. We like to extend and for now is only by copy to project or using hooks rather than layer structure. Similar what Atinux try there: https://nuxt.com/blog/nuxt-on-the-edge

**Comment by danielroe** [comment]
This seems to be working fine in your reproduction. Let me know if I'm missing anything.
