### ISSUE TITLE
Documentation - 404s for endpoint v3.nuxtjs.org/api/configuration/nuxt.config

### ISSUE THREAD

**Issue by Triloworld** [nuxt/nuxt#23335]
### Environment

Latest

### Reproduction

Go into: https://v3.nuxtjs.org/api/configuration/nuxt.config
Get redirect to: https://nuxt.com/docs/api/configuration/nuxt.config
See 404
Links in number 2,100 how much is impact in wild: https://github.com/search?q=api%2Fconfiguration%2Fnuxt.config&type=code

### Describe the bug

Open page and not 404
Only need to add redirection proper to new documentation page (decide and add)

### Additional context

Big impact for newcomer and from people who insert it to navigate. When you remember then you don't need it

**Comment by homersimpsons** [comment]
I do not know if this is linked but the page https://nuxt.com/modules also is broken:

It answers a 500 with the following message:
 > Error: EMFILE: too many open files, open '/var/task/chunks/error-500.mjs'

Interestingly, the favicon https://nuxt.com/favicon.ico answers with a 200 but the image looks invalid for Firefox:
> The image “https://nuxt.com/favicon.ico” cannot be displayed because it contains errors.

**Comment by NozomuIkuta** [comment]
@danielroe 

The URL should be fixed like below:

- Wrong: https://nuxt.com/docs/api/configuration/nuxt.config
- Correct: https://nuxt.com/docs/api/configuration/nuxt-config

- Wrong: https://nuxt.com/docs/modules
- Correct: https://nuxt.com/modules

I can and will fix comments in codebase, but I can't find configuration for redirection, so would you handle it?

The string `https://nuxt.com/docs/modules` doesn't seem to exist in the codebase.

---

I will check favicon case later.

**Comment by NozomuIkuta** [comment]
Ah, it seems to be have already fixed (at least) in [starter templates](https://github.com/nuxt/starter).

**Comment by danielroe** [comment]
I've added redirects on nuxt.com for those paths. Thank you for reporting.

Soon we will be open-sourcing the repo so it will be easier to fix these kinds of issues ❤️
