### ISSUE TITLE
x-forwarded-proto set to IPV4 in dev env

### ISSUE THREAD

**Issue by fanckush** [nuxt/nuxt#23348]
### Environment

- Operating System: Darwin
- Node Version:     v20.4.0
- Nuxt Version:     3.7.3
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  yarn@3.3.0
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

* https://stackblitz.com/edit/github-xatspk?file=app.vue,server%2Fapi%2Ftest.get.ts,nuxt.config.ts
* repo of above for cloning https://github.com/fanckush/nuxt-proto-bug

### Describe the bug

in a nuxt eventHandler (server endpoint or middleware) you can observe the following:
``` js
getRequestProtocol(event)                    // ------> http (as expected)
event.node.req.headers['x-forwarded-proto']  //------> ipv4 
```

Note that this bug only occurs in dev mode (so using `yarn dev`) but when you build the app it works fine
Also, in stackblitz the header isn't even present so you can't really test there

<img width="185" alt="image" src="https://github.com/nuxt/nuxt/assets/6278713/59ba52c9-ccd8-4db0-9292-5aeeb023ccb6">

**Comment by danielroe** [comment]
cc: @pi0

**Comment by zacwebb** [comment]
I believe this was fixed in https://github.com/unjs/nitro/commit/29ddd948407322c67aace0336fdc65eed12bad20?
