### ISSUE TITLE
sendRedirect() in /server/middleware causing error: [nuxt] [request error] [unhandled] [500] Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by leopoldkristjansson** [nuxt/nuxt#23340]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.7.3`
- CLI Version:      `3.8.4`
- Nitro Version:    `2.6.3`
- Package Manager:  `npm@8.5.0`
- Builder:          `-`
- User Config:      `modules`, `typescript`, `app`, `css`, `vite`, `prismic`, `i18n`, `image`, `devtools`, `experimental`
- Runtime Modules:  `@vueuse/nuxt@10.4.1`, `@nuxt/image@1.0.0-rc.2`, `@nuxtjs/i18n@8.0.0-rc.4`, `@nuxtjs/prismic@3.0.2`, `@pinia/nuxt@0.4.11`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-nduq6u?file=pages%2Findex.vue,pages%2F[[slug]]%2Findex.vue,server%2Fmiddleware%2Fredirects.ts

Using the reproduction link above:

- visit `/old-page`

You get an error in the console.

### Describe the bug

The console gives me an error when I go to `/old-page` (which redirects to `/new-page`).

The redirect seems to work, but I get the following error:

```
[nuxt] [request error] [unhandled] [500] Cannot set headers after they are sent to the client
  at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
  at new NodeError (node:internal/errors:371:5)
  at ServerResponse.setHeader (node:_http_outgoing:576:11)
  at setResponseHeaders (./node_modules/h3/dist/index.mjs:711:20)
  at null.<anonymous> (./node_modules/nitropack/dist/runtime/renderer.mjs:31:7)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Object.handler (./node_modules/h3/dist/index.mjs:1630:19)
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1840:7)
```

### Additional context

The file that is causing the error is `/server/middleware/redirects.ts` and the code looks like this:

```ts
export default defineEventHandler((event) => {
  const urlObj = getRequestURL(event)

  if (urlObj.pathname === '/old-page') {
    sendRedirect(event, '/new-page')
  }
})

```

**Comment by danielroe** [comment]
`sendRedirect` returns a promise and should be awaited

**Comment by leopoldkristjansson** [comment]
> `sendRedirect` returns a promise and should be awaited

To keep this issue as helpful as possible. I was coming from @hecktarzuli's blog about Nuxt redirects (thanks 👏).

https://deltener.com/blog/creating-redirects-with-nuxt/ 

By adding `async/await` everything starts working as expected:

```ts
export default defineEventHandler(async (event) => {
  const urlObj = getRequestURL(event)

  if (urlObj.pathname.includes('/__nuxt_error') || urlObj.pathname.includes('/__nuxt_island')) {
    return
  }

  if (urlObj.pathname === '/old-page') {
    await sendRedirect(event, '/new-page')
  }
})


```

**Comment by hecktarzuli** [comment]
Interesting, that's not what's in the doc examples.  And I tested this code myself.  I wonder if something changed.

![image](https://github.com/nuxt/nuxt/assets/2112282/0125e659-2bb2-4a13-a5c5-2df9419a70a1)

**Comment by hecktarzuli** [comment]
Weird, I know I tested this code as I wrote it.  Out of tens of thousands of people that have viewed that post, nobody has ever mentioned they had problems.  I'll update it thanks!

**Comment by leopoldkristjansson** [comment]
> Post: Updated! Also, I've submitted a pull to update the Nuxt example too. https://github.com/nuxt/nuxt/pull/23345/files

Perfect, good catch with the docs!

**Comment by 1714080902120** [comment]
I got the same problem, and i had tried await, but still no work

**Comment by leopoldkristjansson** [comment]
> I got the same problem, and i had tried await, but still no work

Did you add both keywords (`async` and `await`)?

**Comment by 1714080902120** [comment]
> > I got the same problem, and i had tried await, but still no work
> 
> Did you add both keywords (`async` and `await`)?
Certainly i did. The only difference is: i do this in `plugins`.
![image](https://github.com/nuxt/nuxt/assets/48143943/62076fa5-814d-483d-b684-2bb5a08365bb)
The code above only happen in server side.

**Comment by Esensats** [comment]
For future people ending up here with this problem, if you add async/await and the problem remains, make sure every function in between is also awaited, like here:

```typescript
export default defineEventHandler(async (event) => {
  const shouldAuth = !event.path.startsWith('/api/auth')
  if (shouldAuth) {
    const sessionCookie = $getCookie(event, consts.authSessionCookieName)
    await sessionCookie.match({ // If you forget to await functions in the body like this, it'll error
      some: (val) => {
        event.context.auth = {
          sessionToken: val,
        }
      },
      none: async () => { // async here
        await sendRedirect(event, '/auth/signin', 401) // awaiting only here is not enough
      },
    })
  }
})
```
