### ISSUE TITLE
`class and style merging` conflict with vue.template.compilerOptions.whitespace preserve

### ISSUE THREAD

**Issue by memsenpai** [nuxt/nuxt#23353]
### Environment

Node: 18.17.1
Vue 3.3.4
Nuxt 3.7.3
Vite 4.4.9

### Reproduction

https://stackblitz.com/edit/nuxt-starter-2xkzzs?file=nuxt.config.ts
![image](https://github.com/nuxt/nuxt/assets/10399540/ddcb1618-b4bd-46b2-89ac-6704c648eb3d)

### Describe the bug

if we leave a comment before the first element in the template
`style and class merging` do not work

### Additional context

my workaround now:
- move the comment into the div
- add `:class="$attrs.class"` to the element in the child component which I want to extend class from parent
- remove whitespace: 'preserve' (this way is very bad because nuxt 3/vite will render template without extra space as I write in this https://github.com/vitejs/vite/discussions/14378)

**Comment by danielroe** [comment]
I suspect this is a Vue issue rather than Nuxt. could you replicate on https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter ? 🙏

**Comment by memsenpai** [comment]
@danielroe  you are right, it still happens in vue 3 + vite without nuxt 
https://stackblitz.com/edit/github-gjgfy8

**Comment by danielroe** [comment]
Great - thank you.
