### ISSUE TITLE
when using manualChunks, get 'cannot access 'X' before initialization'

### ISSUE THREAD

**Issue by kingyang** [nuxt/nuxt#23354]
### Environment

Nuxt project info: 

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.10.0
- Nuxt Version:     3.7.3
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  pnpm@8.6.12
- Builder:          -
- User Config:      devtools, build, modules, css, sourcemap, app, vite, vue,
 elementPlus, experimental
- Runtime Modules:  @element-plus/nuxt@1.0.6, @nuxt/devtools@0.8.4, @unocss/nuxt@0.55.7, @vueuse/nuxt@10.4.1
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-gmvrwz-x9yx6b?file=nuxt.config.ts

### Describe the bug

I'm trying to split some dependencies (for example vue) into a separate chunk.  i see error like Uncaught ReferenceError: Cannot access 'X' before initialization in console and nothing works in production build.

#20058

**Comment by milos018** [comment]
I would think this is more of a Vite/Rollup issue than Nuxt.
In your nuxt.config.ts, you are declaring vite.build.rollupOptions.output.
Other than that, the whole application is the default generated Nuxt app, or am I missing something?

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/21354.
