### ISSUE TITLE
Nuxt generate no longer generating dynamic Nuxt/Content pages when deploying

### ISSUE THREAD

**Issue by StefanVDWeide** [nuxt/nuxt#23356]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.3.1`
- Nuxt Version:     `3.7.3`
- CLI Version:      `3.9.0`
- Nitro Version:    `2.6.3`
- Package Manager:  `npm@9.6.7`
- Builder:          `-`
- User Config:      `experimental`, `app`, `runtimeConfig`, `modules`, `content`, `site`, `i18n`
- Runtime Modules:  `@nuxt/content@2.8.2`, `@nuxtjs/i18n@8.0.0-rc.4-28252997.568c274`, `@nuxt/image@1.0.0-rc.2`, `@nuxtjs/tailwindcss@6.8.0`, `nuxt-simple-sitemap@3.3.4`
- Build Modules:    `-`

### Reproduction

N/A

### Describe the bug

When running `npm run generate` locally all the pages in my `/content` folder are being generated. However, when deploying to render.com and having it run the same command to generate the static content, all the dynamic pages are skipped over. This results in 404 errors when trying to navigate to those pages. 

The dynamic pages are all being linked to from a blog page overview `/blog` where each entry has a specific link e.g. `/blog/example`. The blog overview page is rendered correctly since this is not based on a markdown file but rather a `.vue` file. 

My content folder looks fairly standard:

- blog
   - NL
       - example
   -   EN
       - example 

This setup has always worked, only after upgrading to Nuxt/Content `2.8.2` from `2.6.0` and Nuxt itself from `3.4.3` to `3.7.3` it started failing on render.com. Reverting back does solve this issue but isn't ideal ofcourse.

I've attached the build logs from a local sucessful build and an incomplete build on render.com

Locally: https://pastebin.com/fs6kXcV2
render.com: https://pastebin.com/g5yvS0PS

Thanks!

**Comment by danielroe** [comment]
This sounds like a likely issue with nuxt/content. Can you try confirming which upgrade caused it? If it was nuxt/content, would you raise an issue there instead?

**Comment by StefanVDWeide** [comment]
@danielroe when trying to downgrade Nuxt/Content back to `2.6.0` and leaving Nuxt at `3.7.3` I'm having the same issue where locally everything is generated, but on my prod environment the dynamic pages are skipped. 

Some more context, these are the errors I'm seeing in the console. It seems the `JSON` payloads are missing and causing issues down the line.

```
GET https://studioterabyte.nl/blog/serverless-stack/_payload.json 404
```
```
entry.4513e066.js:1 [nuxt] Cannot load payload  /blog/serverless-stack/_payload.json SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
```

Interestingly, when downgrading Nuxt to `3.4.3` and leaving Nuxt/Content at `2.8.2` the pages are generated again as expected. So it seems an issue on the Nuxt side of things.

Looks like I'm not the only one with this issue too: https://stackoverflow.com/questions/77077036/nuxt-3-static-site-payload-json-not-found-404-due-to-wrong-route-on-request#comment136014809_77077036

**Comment by danielroe** [comment]
A reproduction would be very helpful then.
