### ISSUE TITLE
How can i control order of plugin execution between module and app 

### ISSUE THREAD

**Issue by shivanshtalwar0** [nuxt/nuxt#23369]
### Describe the feature

consider the use case where we have plugin from app and plugins from module how can we define the execution order or set priority of plugin execution, in my use case i want app plugin to be first and modules plugins to be evaluated last

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
You can use an object syntax plugin which can specify the order. Or you can use the second option to `addPlugin` to add it to the end of plugins array rather than beginning.
