### ISSUE TITLE
Routes rules should allow regex matchers

### ISSUE THREAD

**Issue by igbominadeveloper** [nuxt/nuxt#23361]
### Describe the feature

For example, I have two routes, `users/add` and `users/edit` and I want to set `ssr:false` for both, right now, I have to define them both separately like this:

```ts
'/users/add/**': {
    ssr: false,
  },
'/users/edit/**': {
    ssr: false,
  },
```

What would be nice is to be able to do this:
 ```ts
'/users/(add|edit)/**': {
    ssr: false,
  }
```

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
let's track in https://github.com/unjs/radix3/issues/51.
