### ISSUE TITLE
feat: add meta headAttrs #4536 stop/not working

### ISSUE THREAD

**Issue by beowoolf** [nuxt/nuxt#23379]
### Environment

 WARN  Current version of Node.js (16.20.0) is unsupported and might cause issues.                                                                                                                       17:12:28
       Please upgrade to a compatible version >= 18.0.0.

Working directory: /usr/home/wds/cloned/mojezapiski.pl/www-frontend                                                                                                                                      17:12:29
Nuxt project info:                                                                                                                                                                                       17:12:29

------------------------------
- Operating System: FreeBSD
- Node Version:     v16.20.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      css, ssr, devtools, modules, site, gtag, sitemap, pwa, googleFonts, app, runtimeConfig, nitro
- Runtime Modules:  @nuxt/content@2.7.2, @nuxtjs/color-mode@3.3.0, @nuxt/image@1.0.0-rc.1, @vite-pwa/nuxt@0.1.1, @nuxtjs/google-fonts@3.0.2, nuxt-jsonld@2.0.8, nuxt-gtag@1.1.1, nuxt-seo-experiments@3.0.7, nuxt-simple-robots@3.1.0, nuxt-simple-sitemap@3.3.5
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                                                                                                              17:12:29

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Reproduction

Not work in https://github.com/beowoolf/mojezapiski.pl in www-frontend

### Describe the bug

There is no attributes itemscope and itemtype for rendered head tag.

**Comment by beowoolf** [comment]
I added example project to bug reproduction.

**Comment by manniL** [comment]
@beowoolf Adding a whole project is no reproduction.
