### ISSUE TITLE
Reduce starter project size for better Edge/Microservice support

### ISSUE THREAD

**Issue by bitsnaps** [nuxt/nuxt#23380]
### Describe the feature

The Nuxt 3 starter project hits the size limit when running on platforms like Replit free tier. As suggested by @manniL, the starting project could benefit from being made more modular with a smaller footprint to enable running everywhere, including edge/serverless environments.

Currently on Replit, the starter project fails to run due to hitting the size limit, as you can seen below, in comparison, other framework starters (e.g. [Vitesse](https://github.com/antfu/vitesse) and VitePress are able to run without issues on the same conditions)

![image](https://github.com/nuxt/nuxt/assets/1217741/d808a238-75e7-472f-a4e3-556029bfbda6)

While Nuxt aims to provide a full-featured starting point "out of the box", the large bundled size may discourage some use cases where a smaller surface area is preferred.

It may help if optional features/dependencies could be separated out or lazy-loaded to create different starter "profiles" - a minimal profile optimized for edge scenarios in addition to the existing full-featured one. This would allow taking advantage of Nuxt's capabilities across more environments and project types, don't you think so @manniL ?

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Particularly would value your thoughts on this @antfu...

**Comment by bitsnaps** [comment]
Great news!  with the new v3.8 we're now able to build the minimal starting project on Replit using the free tier, I'm still not able to run/dev/preview for some config reason, but I believe this a replit's thing, so I think we can close this issue, so big thanks @danielroe , @antfu & @manniL !

![image](https://github.com/nuxt/nuxt/assets/1217741/de7fe0b7-12f1-4308-8d09-559e1d2a2421)
