### ISSUE TITLE
Type 'unknown' is not assignable

### ISSUE THREAD

**Issue by imcm7** [nuxt/nuxt#23383]
### Environment

- Operating System: Linux
- Node Version: v20.6.1
- Nuxt Version: 3.7.3
- CLI Version: 3.9.0
- Nitro Version: 2.6.3
- Package Manager: bun@1.0.2

### Reproduction

https://github.com/imcm7/nuxt-db

### Describe the bug

> Type 'unknown' is not assignable to type 'MaybeComputedRefOrPromise<MaybeArray<Stringable> | Promise<MaybeArray<Stringable> | null | undefined> | null | undefined>'.

> Argument of type '{}' is not assignable to parameter of type 'string | number'.

Pass the problem

```
declare module 'vue-router' {
    interface RouteMeta {
        title?: string | number;
    }
}
```

No effect 

```
declare module '#app' {
     interface PageMeta {
         title?: string | number;
     }

     interface RouteMeta {
         title?: string | number;
     }

}

export {};
``

**Comment by danielroe** [comment]
Seems to work fine when I remove `"baseUrl": ".",` from your tsconfig. In general you should not override nuxt defaults for things like this.

<img width="941" alt="CleanShot 2023-09-29 at 08 06 21@2x" src="https://github.com/nuxt/nuxt/assets/28706372/f7719627-d18d-4828-8919-9c9e639d1065">

**Comment by imcm7** [comment]
@daniel but I have `Argument of type '{}' is not assignable to parameter of type 'string | number'`
