### ISSUE TITLE
Type 'unknown' is not assignable to type 'MaybeComputedRefOrPromis

### ISSUE THREAD

**Issue by imcm7** [nuxt/nuxt#23382]
### Environment

- Operating System: Linux
- Node Version:     v20.6.1
- Nuxt Version:     3.7.3
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  bun@1.0.2

### Reproduction

Example not work https://nuxt.com/docs/getting-started/seo-meta#with-definepagemeta

```
const route = useRoute();


  useHead({
    meta: [{ property: 'og:title', content: route.meta.title }],
  })
```

### Describe the bug

> Type 'unknown' is not assignable to type 'MaybeComputedRefOrPromise<MaybeArray<Stringable> | Promise<MaybeArray<Stringable> | null | undefined> | null | undefined>'.ts(2322)

**Comment by manniL** [comment]
The actual examples works fine.

![grafik](https://github.com/nuxt/nuxt/assets/640208/2b278e5d-f01b-4058-b9e7-e2ed8e29d1aa)

If you only use `route.meta.title`, you *either* have to manually type it or do a type cast (e.g. `as`.

so either the "easy" but less safe way out

```ts
useHead({
  meta: [{ property: 'og:title', content: route.meta.title as string }]
})
```

or type it via [this guide](https://nuxt.com/docs/guide/directory-structure/pages/#typing-custom-metadata) in e.g. a `env.d.ts`

```
declare module '#app' {
  interface PageMeta {
    title?: string
  }
}

// It is always important to ensure you import/export something when augmenting a type
export {}
```

**Comment by imcm7** [comment]
@manniL not work, work

```
// declare module 'vue-router' {
//     interface RouteMeta {
//         title?: string | number;
//     }
// }
``

**Comment by manniL** [comment]
@imcm7 please check my example above. This is not the code I provided 😋

**Comment by imcm7** [comment]
It work for useHead. Sorry.
But I have the same with $route.meta.title

**Comment by imcm7** [comment]
Not understand, with that
```
declare module '#app' {
  interface PageMeta {
    title?: string
  }
}
```
I have errors

Only with that

```
declare module 'vue-router' {
    interface RouteMeta {
        title?: string | number;
    }
}
```

not

**Comment by imcm7** [comment]
@manniL https://i.ibb.co/tLGjb46/image.png

**Comment by imcm7** [comment]
@manniL its' not title, it's content field

**Comment by imcm7** [comment]
@manniL it's because I import not from #app 
`import { useRoute } from 'vue-router';`

**Comment by imcm7** [comment]
route.meta is of type RouteMeta not PageMeta. Why to alter PageMeta?

**Comment by imcm7** [comment]
@manniL https://github.com/nuxt/nuxt/issues/23383

**Comment by imcm7** [comment]
Modules also use `vue-router`  not `#app`

```
declare module 'vue-router' {
    interface RouteMeta {
        colorMode?: string;
    }
}
```
