### ISSUE TITLE
[Vue Router warn]: No match found for location with path "/"

### ISSUE THREAD

**Issue by TJ-strange** [nuxt/nuxt#23393]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.7.3
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@9.5.1
- Builder:          -
- User Config:      devtools, app, devServer, vite, postcss, css, runtimeConfig, modules, i18n, build
- Runtime Modules:  @element-plus/nuxt@1.0.6, @nuxtjs/i18n@8.0.0-rc.4-28257783.3664302, @vueuse/nuxt@10.4.1, @nuxtjs/tailwindcss@6.8.0, @pinia/nuxt@0.4.11
- Build Modules:    -
------------------------------

### Reproduction

@nuxtjs/i18n

### Describe the bug

When I used the detectBrowserLanguage of @nuxtjs/i18n and configured redirectOn to 'all', I got a console warning because I overwrote the nuxt3 default route "[Vue Router warn]: No match found for location with path. "/", How do I solve it

### Additional context

 i18n: {
    baseUrl: "https://my-nuxt-app.com",
    locales: [
      { code: "en", iso: "en-US", file: './locales/en.json' },
      { code: "cn", iso: "zh-CN", file: './locales/cn.json' },
    ],
    vueI18n: "./i18n.config.ts",
    detectBrowserLanguage: {
      useCookie: true,
      cookieKey: "i18n_redirected",
      redirectOn: "all",
    },
  },

### Logs

```shell-script
[Vue Router warn]: No match found for location with path "/"
```

**Comment by elizabthpazp** [comment]
I have the same problem

**Comment by manniL** [comment]
@elizabthpazp Feel free to open an issue in https://github.com/nuxt-community/i18n-module then 👍🏻

**Comment by frederikheld** [comment]
@elizabthpazp: I had the same error and it was related to `i18n.strategy: 'prefix'` in `nuxt.config.ts`. Changed it to `'prefix_and_default'` and the error was gone.

It's not really a solution, as I'd like to have prefixes for the default language as well, but the workaround works for now.

Did you open an issue in the nuxt-community/i18n-module repo as suggested by @manniL?

See: https://i18n.nuxtjs.org/guide/routing-strategies
