### ISSUE TITLE
useFetch does not preflight requests to /api/** and therefore cors does not work

### ISSUE THREAD

**Issue by videmann** [nuxt/nuxt#23396]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.7.3
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      nitro
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-j8fyzt

### Describe the bug

useFetch does not preflight requests to /api/** and therefore cors does not work.
Therefore, anyone from outside can make requests to the /api/ server

Nitro Settings have no effect...

export default defineNuxtConfig({
  nitro: {
    routeRules: {
      '/api/**': {
        cors: true,
        headers: {
          'access-control-allow-origin': '[any host]',
        },
      },
    },
  },
});

**Comment by videmann** [comment]
using middleware doesn't work either

src/middleware/cors.ts

export default defineEventHandler((event) => {
  setResponseHeaders(event, {
    "Access-Control-Allow-Origin": "[any host]",
  })
  if(getMethod(event) === 'OPTIONS'){
    event.res.statusCode = 204
    event.res.statusMessage = "No Content."
    return 'OK'
  }
})

**Comment by videmann** [comment]
> [<img alt="Fix this issue in StackBlitz Codeflow" width="117" height="20" src="https://camo.githubusercontent.com/78baa8e11fa39e8c93400da552607ff3a2ddb034a3d36fac19b771e6294c2d9f/68747470733a2f2f646576656c6f7065722e737461636b626c69747a2e636f6d2f696d672f6669785f746869735f69737375655f736d616c6c2e737667">](https://stackblitz.com/~/github.com/nuxt/nuxt/issues/23396?repros=nuxt-starter-j8fyzt) _Start a new pull request in [StackBlitz Codeflow](https://stackblitz.com/~/github.com/nuxt/nuxt/issues/23396?repros=nuxt-starter-j8fyzt)._
> 
>     * [**nuxt-starter-j8fyzt** (Open reproduction)](https://stackblitz.com/edit/nuxt-starter-j8fyzt?issueRepo=nuxt/nuxt&issueNumber=23396)

https://stackblitz.com/edit/nuxt-starter-znyjkd

**Comment by warflash** [comment]
Could you explain what exactly the issue is? In your provided reproduction the Access-Control-Allow-Origin header is added properly: 
![image](https://github.com/nuxt/nuxt/assets/22006082/a3feff80-6bea-4acf-afca-d5dbccafb967)

> useFetch does not preflight requests to /api/** and therefore cors does not work.

network requests on the same origin don't trigger a preflight request so that is expected, unless I misunderstood the concern

**Comment by danielroe** [comment]
Preflight requests are browser behaviour. @warflash is right here. I don't think this is an issue.
