### ISSUE TITLE
On 'nuxi cleanup', custom buildDir is ignored

### ISSUE THREAD

**Issue by Eternal-Grace** [nuxt/nuxt#23391]
Nuxt version: "^3.7.3"
___
### Environment

Hi, and thank you for clicking onto here.

Here is my issue:

When executing the commande `nuxi cleanup` (https://nuxt.com/docs/api/commands/cleanup), the default behavior deletes de following repositories: `.nuxt`, `.output`, `node_modules/.vite` and `node_modules/.cache`.

However, when defining a custom name via the file `nuxt.config.ts` 
```ts
export default defineNuxtConfig({
  // default: '.nuxt'
  buildDir: '.custom_dir'
})
```
The repository known as `.custom_dir` (see example above) is not removed.

I beleive the path to the repository known as `.nuxt` is hard-coded. Is it possible to REMOVE that.
And replace it with the actual configs inside the file `nuxt.cofig.ts` ?
> replace `'/.nuxt/'` with `config.options.buildDir` (if exists when `nuxi cleanup`)

### Reproduction

In a clean NuxtJS project: 
- execute either `npm i`, `npm run dev` or `npm run build`
- you will see the repository `.nuxt`
- execute `nuxt cleanup` - inside package.json (https://nuxt.com/docs/api/commands/cleanup)
- the repository `.nuxt` has been removed

Now, repleat with slight changes.

- execute either `npm i`, `npm run dev` or `npm run build`
- you will see the repository `.nuxt`
- replace `buildDir: '.nuxt'` with `buildDir: '.custom'` inside the file `nuxt.config.ts`
- execute either `npm i`, `npm run dev` or `npm run build`
- execute `nuxt cleanup` - inside package.json (https://nuxt.com/docs/api/commands/cleanup)
- ___the repository `.custom` will not be removed___

### Describe the bug

custom repository named after `buildDir` is not removed when executing `nuxi cleanup`. Unlike `.nuxt`

**Comment by danielroe** [comment]
closing to track there. ❤️
