### ISSUE TITLE
  NUXT ROLLUP BUILD ERROR: Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)            

### ISSUE THREAD

**Issue by gitamgadtaula** [nuxt/nuxt#23406]
### Environment

- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, css, serverHandlers, modules, cookieControl, gtag, i18n, postcss, vite
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @nuxt/image@1.0.0-rc.2, @nuxtjs/i18n@8.0.0-rc.4-28257783.3664302, @dargmuesli/nuxt-cookie-control@6.4.3, nuxt-gtag@1.1.1, @nuxtjs/robots@3.0.0
- Build Modules:    -

### Reproduction

This is a private project so I am hesitant to create a Reproduction. But I might as well do it later if need be. 

### Describe the bug

I am getting this issue on while I am trying to migrate my nuxt2 landing page into nuxt3. I already consider myself as a proficient nuxt 3 developer since I used it from its beta inception and making new nuxt app every week. But came across this issue just this time. It looks like it is coming from Rollup while trying to build the SSR Bundle; everything works fine if i disabled SSR. Looks like for some reason Rollup can't parse '@' inside the css file. I tried installing so many rollup plugins but with no luck. Can anyone point me in any directions? 

This is my Nuxt config 
`// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  css: ["~/assets/css/main.css"],

  modules: [
    "@nuxtjs/tailwindcss",
    "@nuxt/image",
    "@nuxtjs/i18n",
    "@dargmuesli/nuxt-cookie-control",
    "nuxt-gtag",
    "@nuxtjs/robots",
  ],

  postcss: {
    plugins: {
      tailwindcss: {},
      autoprefixer: {},
      // "postcss-apply": {},
      // "postcss-simple-vars": {},
      // "postcss-nested": {},
      // "postcss-custom-media": {},
    },
  },
  vite: {
    define: {
      "window.global": {},
    },
  },
});
`
And this is the Build error
<img width="874" alt="Screenshot 2023-09-26 at 08 39 35" src="https://github.com/nuxt/nuxt/assets/16968862/38291f40-0c06-40d6-a91d-cd1abd01e4b4">

`
 ERROR  Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)                                 8:08:37 AM
file: /Users/gitamgadtaula/Desktop/work/freelance/fiverr/nutriwebsite/assets/css/main.css?url?inline&used:1:0
1: @tailwind base;
   ^
2: @tailwind components;
3: @tailwind utilities;

 ERROR  Nuxt Build Error: Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)               8:08:37 AM

  at error (node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
  at Module.error (node_modules/rollup/dist/es/shared/node-entry.js:13740:16)
  at Module.tryParse (node_modules/rollup/dist/es/shared/node-entry.js:14471:25)
  at Module.setSource (node_modules/rollup/dist/es/shared/node-entry.js:14072:39)
  at ModuleLoader.addModuleSource (node_modules/rollup/dist/es/shared/node-entry.js:24644:20)
`

### Additional context
This is my main.css file
`
@tailwind base;
@tailwind components;
@tailwind utilities;

.transform-fade-down-enter-active,
.transform-fade-down-leave-active {
  @apply transition-all translate-y-0 duration-300;
}
.transform-fade-down-enter, .transform-fade-down-leave-to /* .fade-leave-active below version 2.1.8 */ {
  @apply opacity-0 transform -translate-y-2;
}

.paragraph {
  @apply text-gray-700 tracking-wide leading-relaxed;
}
`

_No response_

**Comment by danielroe** [comment]
Somehow that CSS file is not being transpiled. You can try adding a regexp that matches it manually to `build.transpile` or provide a reproduction.

**Comment by gitamgadtaula** [comment]
> Somehow that CSS file is not being transpiled. You can try adding a regexp that matches it manually to `build.transpile` or provide a reproduction.

Hi @danielroe, thank you for your much awaited response. My client is gonna cancel the project with me If I don't deliver him by tomorrow and this issue is the only thing thats holding me back. 

Could you please provide me with an example of what could i do with `build.transpile` ? I would love to provide a reproduction but its complicated.

**Comment by alex-eliot** [comment]
Could this be related to https://github.com/nuxt/nuxt/issues/22427 ?

**Comment by danielroe** [comment]
It could.

@gitamgadtaula Note you should not manually specify `@tailwind` directives, nor configure the `tailwindcss` postcss plugin; these are done for you by the `@nuxtjs/tailwindcss` module.
