### ISSUE TITLE
3.7.4 – Can't install @nuxt/kit-edge because @nuxt/schema-edge version does not exist

### ISSUE THREAD

**Issue by davbtmx** [nuxt/nuxt#23408]
### Environment

- Operating System: Darwin
- Node Version:     v18.17.1
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  pnpm@8.7.6
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

```shell
# create a fresh nuxt 3.7.4 project
$ pnpm dlx nuxi init nuxt-app

# install @nuxt/kit-edge
$ pnpm add @nuxt/kit-edge
```

### Describe the bug

Installing **@nuxt/kit-edge** in a Nuxt 3.7.4 project (fresh or not) fails.

```shell
$ pnpm add @nuxt/kit-edge

 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for
 @nuxt/schema@npm:@nuxt/schema-edge@3.7.5-28261484.5abd8a23

This error happened while installing the dependencies of
 @nuxt/kit-edge@3.7.5-28261484.5abd8a23

The latest release of @nuxt/schema-edge is "3.7.4-28261484.a6f845d1".
```

It is like **@nuxt/kit-edge** requires **@nuxt/schema-edge** with the exact same version, which does not exist.

When comparing **@nuxt/kit-edge** and **@nuxt/schema-edge** versions through time, they seem to always have a match in their versions, which is not the case with the latest versions.

Is it the reason why the installation fails?

**Comment by danielroe** [comment]
This happened due to an npm bug when publishing the edge version: https://github.com/nuxt/nuxt/actions/runs/6306354556/job/17121826191

You can pin the exact version to the previous one, or this will be fixed on the next commit.
