### ISSUE TITLE
Error on Vercel Edge function after upgrade to 3.7.4

### ISSUE THREAD

**Issue by silvio-e** [nuxt/nuxt#23418]
### Environment

- Operating System: Darwin
- Node Version:     v18.18.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  pnpm@8.7.4
- Builder:          -
- User Config:      nitro, devtools, experimental, modules, googleFonts, tailwindcss, vue
- Runtime Modules:  @nuxt/content@2.8.3, @nuxt/image@1.0.0-rc.1, @nuxtjs/google-fonts@3.0.2, @nuxtjs/tailwindcss@6.8.0
- Build Modules:    -

### Reproduction

https://github.com/silvio-e/nuxt-3-7-4

### Describe the bug

After upgrading Nuxt to version 3.7.4, the following error occurs when deploying to Vercel Edge:

`
Error: The Edge Function "__nitro" is referencing unsupported modules
index.mjs: fs, path`

**Comment by silvio-e** [comment]
I have updated the issue with a link to this repo: https://github.com/silvio-e/nuxt-3-7-4

It seems that the `nuxt-content` module creates this issue.

**Comment by silvio-e** [comment]
Sorry for the noise here. I just found that it should be the latest release of nuxt-content (2.8.3) that causes this error. I just rolled it back, and now the deployment works again. Should this be addressed in the nuxt or in the nuxt-content repo?

**Comment by danielroe** [comment]
This sounds like a content issue to me in that case.

**Comment by arunanshub** [comment]
@silvio-e Were you able to track down the source of the issue?

**Comment by silvio-e** [comment]
@arunanshub yes, it only needed a proper dependency upgrade with an updated lockfile.

**Comment by arunanshub** [comment]
@silvio-e Are you using `NITRO_PRESET=vercel-edge` in Vercel? Since only the deployments that are not deployed as vercel edge functions build successfully.
