### ISSUE TITLE
Layout shift when hydrating page

### ISSUE THREAD

**Issue by martinszeltins** [nuxt/nuxt#23416]
### Environment

````
------------------------------
- Operating System: Linux (Ubuntu 20.04 LTS)
- Node Version:     v18.14.2
- Nuxt Version:     3.7.3
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  pnpm@8.6.12
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------
````

### Reproduction

https://github.com/martinszeltins/nuxt-hydration-shift

### Describe the bug

The layout shifts do not happen with SSR disabled.

When the hydration kicks in, it causes very bad layout shifts. Some components and CSS disappears and then comes back. Even some text disappears for a while from the page. The initial render is perfect and the page looks how it should. But then a second later when hydration begins it messes everything up and then goes back to normal again.

I tried to keep the reproduction as minimal as possible, there is not much there, only a few components. It can be seen in my minimal reproduction if you run `pnpm dev`

Here is a screencast:
![Peek 2023-09-26 15-42](https://github.com/nuxt/nuxt/assets/34019878/5bef777d-4fb7-4375-9595-b03bdb325e6d)

![Peek 2023-09-26 15-57](https://github.com/nuxt/nuxt/assets/34019878/20400b7f-e387-48c3-a157-891b84549720)

**Comment by danielroe** [comment]
When you say that this is with 3.7.4, are you saying that this did not happen on a previous version of Nuxt?

**Comment by martinszeltins** [comment]
> When you say that this is with 3.7.4, are you saying that this did not happen on a previous version of Nuxt?

No, it also happens with 3.7.3. The title is a bit misleading.

**Comment by martinszeltins** [comment]
Now that I am taking a closer look at it, it does not actually seem to have it fully rendered on initial page load. But how could that be because I see that in the source code all the data is present.

**Comment by warflash** [comment]
This unfortunately is a problem with component libraries not properly considering SSR. This issue is just an example: https://github.com/primefaces/primevue/issues/4210.
