### ISSUE TITLE
Layout re-renders even if the layout contents are same

### ISSUE THREAD

**Issue by lubomirblazekcz** [nuxt/nuxt#23421]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.7.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@10.1.0
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/github/lubomirblazekcz/nuxt-layout-repro

### Describe the bug

As mentioned in https://github.com/nuxt/nuxt/issues/15158#issuecomment-1397373067, if NuxtLayout is used in page, the whole layout is re-rendered, even if the contents of the layout don't change.

This is clearly visible in repro, the animation occures on each page because of the layout re-render.

Here is a repro where animation occures only when the layout changes, which would be correct behaviour. This is because the layout is defined in `app.vue`, instead of page - but this is not ideal, because then slot & template doesn't work which is also mentioned in https://github.com/nuxt/nuxt/issues/15158

https://stackblitz.com/github.com/lubomirblazekcz/nuxt-layout-repro/tree/working

**Comment by danielroe** [comment]
This is inevitable based on how Vue works. To avoid this, move `NuxtLayout` outside of the page and into your `app.vue`.

**Comment by lubomirblazekcz** [comment]
I see, I must have misunderstood your previous comment https://github.com/nuxt/nuxt/issues/15158#issuecomment-1397373078

I would like to use slots in layout, but that can't be used in pages, and defining custom layouts on each page kind of defeats the purpose of layouts.

But I might create a component as a sublayout as a workaround, I saw this approach in Elk. Thanks for the help 👍
