### ISSUE TITLE
docs: add documentation for `useRequestFetch`

### ISSUE THREAD

**Issue by warflash** [nuxt/nuxt#23423]
### Describe the feature

Saw the `useRequestFetch` composable being used in the edge todo example https://github.com/Atinux/nuxt-todos-edge/blob/main/composables/session.ts#L16C39-L16C54 but couldn't find any documentation on it. 
I think it'd be nice to include what it does and what it's for.

### Additional information

- [x] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
It will use `event.$fetch` on the server and `$fetch` on client. AFAIK, the former ensure that the `fetch` of the platform is used (e.g. cloudflare worker's fetch).

**Comment by danielroe** [comment]
This would be great. Let's track in https://github.com/nuxt/nuxt/issues/19815.
