### ISSUE TITLE
Nitro `request` hook has incorrect types

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt#23437]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.14.2
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  pnpm@8.6.2
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

[Repo](https://github.com/manniL/nuxt3-23437)

Manual:

1. Create a file in `server/plugins/hooks.ts`
2. Add the following content

```ts
export default defineNitroPlugin((nitroApp) => {
  nitroApp.hooks.hook('request', (event) => {
    console.log('hey!')
  })
})
```

3. See a typescript error: `Argument of type '(event: any) => void' is not assignable to parameter of type 'never'.ts(2345)`

![grafik](https://github.com/nuxt/nuxt/assets/640208/c0f381f3-a9bc-4c8c-bcde-890d23f1adad)

This works fine in standalone Nitro though.

**Comment by manniL** [comment]
Oh, good point! Thanks. Then it is indeed upstream. Should we close here so we can track in unjs/nitro#1769?

**Comment by pi0** [comment]
Yes, feel free to open one in upstream 👍🏼

**Comment by rudolfbyker** [comment]
I can't find the upstream issue for this. Was it ever created?

**Comment by danielroe** [comment]
No, I directly fixed it.

**Comment by pi0** [comment]
It is fixed by https://github.com/unjs/nitro/pull/1769
