### ISSUE TITLE
Accessing Nuxt composables inside useAsyncData after awaiting some other promise throws error: "A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function."

### ISSUE THREAD

**Issue by alex-eliot** [nuxt/nuxt#23434]
### Environment

- Operating System: Linux
- Node Version:     v16.17.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      telemetry, ssr
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://codesandbox.io/p/sandbox/elated-orla-cd8gl2?file=%2Fapp.vue%3A8%2C18

### Describe the bug

```vue
<script lang="ts" setup>
// ~/app.vue
import { testUtilFunc } from "~/utils/someUtils";

const { error, data } = useAsyncData(
  "some-id",
  async () => {
    // It has to await an async function
    const message = await testUtilFunc(); /* returns Promise<"ok"> */

    // Using any nuxt composable hereafter shall throw the error
    useServerSeoMeta({
      title: message,
    });

    return message;
  },
  {
    // uncomment this to make it work again
    // server: false
  },
);
```

```typescript
// ~/utils/someUtils.ts
export async function testUtilFunc() {
  return "ok";
}

```

### Additional context

All Nuxt composables are inaccessible after awaiting a promise from a function in a util file (that doesn't have access to a Nuxt instance), including useServerSeoMeta, etc..

NOTE: This is ONLY occurring if the page is rendered on the server. If it renders on the client, it works ok.

**Comment by danielroe** [comment]
See https://nuxt.com/docs/api/composables/use-nuxt-app#runwithcontext. This will hopefully explain why you're getting the message and help you resolve it.

I would not call `useServerSeoMeta` within `useAsyncData` however. It's meant to be called in your setup function, and in general calling things with _side-effects_ inside `useAsyncData` will cause bugs in your app as the fetcher function is meant to be pure - just return a value.

**Comment by alex-eliot** [comment]
Thanks for the reply! runWithContext worked, but I'm a little confused as to how to do this properly now. What is the safe way of using data fetched asynchronously in meta tags in the served page?

**Comment by danielroe** [comment]
Something like this should work:

```ts
import { testUtilFunc } from "~/utils/someUtils";

const { error, data } = useAsyncData(
  "some-id",
  async () => {
    // It has to await an async function
    const message = await testUtilFunc(); /* returns Promise<"ok"> */

    return message;
  },
  {
    // uncomment this to make it work again
    // server: false
  },
);

// using a computed getter here but you can also await `useAsyncData` above
useServerSeoMeta({
  title: () => data.value,
});
```

**Comment by gee-whiz** [comment]
Hi @danielroe , I tired this but whenever I use useServerSeoMeat, the tags are empty when I use useSeoMeta, the tags in the head are populated but web crawlers do not find them. if I inspect the page, I can see the tags. ```
<template>
  <h1>{{ data?.title }}</h1>
</template>


<script setup lang="ts">
import { useStore } from "@/store";
import { useRoute } from 'vue-router';
import { ref, watch } from 'vue';

const store = useStore();
const route = useRoute();
const articleId = ref(route.params.id);


const { error, data } = useAsyncData(
  async () => {
    store.fetchArticleWithAssets(articleId.value as string);
    const article = store.getArticleById(articleId.value as string);
    return article;
  },
  { immediate: true
  },
);


useServerSeoMeta({
  description: () => `description: ${data.value?.title}`,
  ogDescription: () => `ogDescription: ${data.value?.title}`,
  ogImage: () => `ogImage: ${data.value?.imageURL}`,
})
</script>.
``` SSR:  I used this to inspect https://www.linkedin.com/post-inspector/inspect/

**Comment by danielroe** [comment]
@gee-whiz It seems this is an upstream bug with useSeoMeta that is being looked into.

**Comment by gee-whiz** [comment]
@danielroe Thanks, I guess I have to wait then

**Comment by Foddie2** [comment]
Thanks, @danielroe let's wait and see how it works. 

Also facing the same error 

`[Vue Router warn]: uncaught error during route navigation:
Error: [nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug.`

**Comment by Foddie2** [comment]
This is still an issue even after running `yarn upgrade `

**Comment by danielroe** [comment]
@Foddie2 Would you open a new issue with a reproduction? 🙏

**Comment by Foddie2** [comment]
@danielroe  FYI #24277

**Comment by icai** [comment]
@danielroe I try to use  `navigateTo` and `useCookie` in composables which using `useFetch` wrapped like axios library, but caught error `[nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug.`
