### ISSUE TITLE
onMounted invoked twice

### ISSUE THREAD

**Issue by alimozdemir** [nuxt/nuxt#23453]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-vqqsvj?file=pages%2Findex.vue

### Describe the bug

When we navigate with nuxt-link or router.push, onMounted on the page is invoked twice. You can see it in the console of reproduction. We just discovered this but it seems like it is also exist in 3.7.1 and 3.7.4

**Comment by danielroe** [comment]
This is because you have this code:

```vue
<template>
  <div>
    <NuxtPage :key="$route.path" />
  </div>
</template>
```

Instead, you should remove the key or explicitly specify it like this:

```vue
<template>
  <div>
    <NuxtPage :key="route => route.path" />
  </div>
</template>
```

**Comment by alimozdemir** [comment]
Ok, why? Is there any explanation for that, it was working in nuxt 3.6, I don't see any **BREAKING CHANGE** in the logs?

**Comment by danielroe** [comment]
It was a bug fix. And it's not a breaking change.
