### ISSUE TITLE
useCookie does not set cookie

### ISSUE THREAD

**Issue by hendrikheil** [nuxt/nuxt#23451]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      ssr
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

This reproduction requires an external navigation, at least as far as I can tell.

So the first environment is hosted here: https://stackblitz.com/edit/github-zyetwn?file=pages%2Findex.vue
The second is hosted here: https://stackblitz.com/edit/github-lqswyc?file=app.vue

### Describe the bug

Clicking the first link will cause nuxt to use `useCookie`, set a value to the cookie and then navigate away.
The other app will simply navigate back to a callback where the cookie value is displayed.

Interestingly, there is no cookie value stored in the browser. As far as I can tell, the external navigation is required, as it causes nuxt to stop.

I suspect Nuxt ends before the cookie had a chance to be persisted, but this suspicion has no real investigation proof.

**Comment by danielroe** [comment]
stackblitz does exhibit this behaviour, yes, but I can't reproduce locally with this code:

```vue
<script lang="ts" setup>
const cookie = useCookie<any | undefined>('example')

console.log('initial', cookie.value)

if (process.client) {
  if (useRoute().fullPath !== '/?test') {
    cookie.value = {
      state: 'abc',
      verifier: 'def'
    }
    await navigateTo('https://google.com', { external: true })
  }
}
</script>

<template>
  <pre>Check the devtools</pre>
  <ClientOnly>
    <pre>{{ cookie }}</pre>
  </ClientOnly>
  <button @click="cookie = null">
    clear
  </button>
</template>
```

**Comment by hendrikheil** [comment]
So I've spent some more time on this, and my reproduction is simply flawed, as it depends on a race condition, which does not occur locally for whatever reason.

Instead of relying on `navigateTo` to stop execution of Nuxt, replacing the navigation with `debugger;` produces the expected result. No cookie is actually persisted to the browser.

So a relatively simple workaround for this would be to actually just call `await nextTick()` after you update the cookie value.

Though, I'd say that maybe a watcher for the cookie isn't an ideal solution?
Would it make sense to replace the value with a computed property instead? That way persisting the cookie could be done synchronously instead of waiting for a watcher.

**Comment by danielroe** [comment]
I think maybe `await nextTick()` is the best approach so you ensure this occurs before navigating away from the page. This will be relevant for a lot more utilities and I'm not sure removing the reactivity (via watch) of `useCookie` is the right solution here.

What do you think?

**Comment by hendrikheil** [comment]
That's all good with me, but it definitely feels like unexpected behavior. Maybe not a lot of people will run into this. We noticed this when starting an OAuth2 flow and persisting the state in a ssr compatible way.

Maybe this is something we should add to the docs in the utilities affected by this?

**Comment by danielroe** [comment]
For sure we should add this to the docs, possibly both in `useCookie` and in a more general point in `navigateTo`.

I think `useCookie` might be the only core nuxt composable that uses `watch` apart from data fetching (which I don't think anyone would expect to resolve before navigating away from the page).

We might also consider waiting for `nextTick` when using `navigateTo` to an external URL 🤔

**Comment by Bhanuteja01** [comment]
hey @danielroe   can you explain me how to approach this problem

**Comment by hendrikheil** [comment]
I agree `navigateTo` should probably wait for `nextTick`, same with anything that could lead to stopping Nuxt' execution (though I can't think of anything else right now).
I think adding it to the `navigateTo` composable and mentioning it in `useCookie` would be a good idea. If we add it to `navigateTo`, I think we could safely omit mentioning it in its' docs.

On a different note, I've re-read your message:

> not sure removing the reactivity (via watch) of useCookie

Wouldn't my proposed solution still maintain the same reactivity as before, just removing the watcher?
I think if it's really only `useCookie` using the `watch` based reactivity, it would be well worth it to introduce a breaking change, we could maybe maintain the same options contract without actually using watch?

`watch == false` would return no ref at all;
`watch == true`, would return the computed prop (Proxy)
`watch == 'shallow'`, might be a bit more complex though

**Comment by hendrikheil** [comment]
> hey @danielroe can you explain me how to approach this problem

@Bhanuteja01 This composable would need to wait for `nextTick` https://github.com/nuxt/nuxt/blob/1e3d989ad90e672e5bcb1e9f944b27b13fc42f3d/packages/nuxt/src/app/composables/router.ts#L111

**Comment by Bhanuteja01** [comment]
@hendrikheil  ok 
is this beginner friendly or not

**Comment by hendrikheil** [comment]
I'd say yes, but I'd wait with the implementation until the final approach is decided to avoid potentially wasting your time :)

**Comment by danielroe** [comment]
@hendrikheil Thank you for your analysis on this, which I think is good.

I think we probably want to keep `watch` behaviour for now, as there is also the possibility of race conditions. By waiting for Vue's nextTick, we ensure the state is correct before we then trigger updates. (Although this is normally important to do before DOM updates, I think it's also important to do before - for example - posting a message to other tabs.)

So I suspect waiting on nextTick in `navigateTo` is right approach (possibly only in event of external navigation to reduce surface of change). The only issue we should check is what happens if using an external `navigateTo` to navigate away _before_ the DOM updates.

**Comment by danielroe** [comment]
I think with https://github.com/nuxt/nuxt/pull/23667 we can now set the cookie synchronously in `onScopeDispose` if it hasn't already been set - this should ensure it is set when navigating away, but not require a nextTick awaiting in navigateTo.
