### ISSUE TITLE
useFetch is fired twice if server returns with a 500 Error

### ISSUE THREAD

**Issue by jdnumm** [nuxt/nuxt#23457]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.18.0`
- Nuxt Version:     `3.7.4`
- CLI Version:      `3.9.0`
- Nitro Version:    `2.6.3`
- Package Manager:  `yarn@1.22.19`
- Builder:          `-`
- User Config:      `app`, `modules`, `components`, `nitro`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.8.0`, `@nuxtjs/plausible@0.2.3`
- Build Modules:    `-`

### Reproduction

```
<template>
  <div>
    <a @click="fetch('400')"> 400 </a>
    <a @click="fetch('404')"> 404 </a>
    <a @click="fetch('500')"> 500 </a>
  </div>
</template>

<script lang="ts" setup>
  const runtimeConfig = useRuntimeConfig()
  async function fetch(url) {
    await useFetch(`${runtimeConfig.public.apiURL}/${url}`, {
      onRequest({ request, options }) {
        console.log('Inside onRequest')
      },
      onResponse({ request, response, options }) {
        console.log('Inside onResponse')
      },
      onResponseError({ request, response, options }) {
        console.log('Inside onResponseError')
      }
    })
  }
</script>
```

### Describe the bug

On a server error, useFetch fired twice. In my code example, 400 and 404 work as expected, but on 500 the request is fired again. Here are the console.log messages from the code if you click on every anchor.

```
Inside onRequest test.vue:16:16
XHRGET
http://127.0.0.1:8000/400
[HTTP/1.1 400 Bad Request 13ms]
Inside onResponse test.vue:19:16
Inside onResponseError test.vue:22:16

Inside onRequest test.vue:16:16
XHRGET
http://127.0.0.1:8000/404
[HTTP/1.1 404 Not Found 12ms]
Inside onResponse test.vue:19:16
Inside onResponseError test.vue:22:16

Inside onRequest test.vue:16:16
XHRGET
http://127.0.0.1:8000/500
[HTTP/1.1 500 Internal Server Error 11ms]
Inside onResponse test.vue:19:16
Inside onResponseError test.vue:22:16

Inside onRequest test.vue:16:16
XHRGET
http://127.0.0.1:8000/500
[HTTP/1.1 500 Internal Server Error 10ms]
Inside onResponse test.vue:19:16
Inside onResponseError test.vue:22:16
```

**Comment by imcm7** [comment]
The ofetch library is built on top of [the fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) and adds handy features to it:
- Works the same way in browser, Node or worker environments
- Automatic response parsing
- Error handling
- **Auto-retry**
- Interceptors

**Comment by jdnumm** [comment]
Thanks for the tip. I thought something like that but somehow did not find the right option.
