### ISSUE TITLE
Consider headers in useFetch key

### ISSUE THREAD

**Issue by hendrikheil** [nuxt/nuxt#23455]
### Describe the feature

We are using Laravel Precognition feature to validate forms server-side before we actually submit them.

By default we use useFetch, and simply add the header required by this feature to perform the validation instead of the actual request.
Since useFetch deduplicates identical requests by default, our validation request is actually the request that gets cached. This means that when we actually want to make the request, we just get our cached response back instantly, which does not actually do anything.

We traced this down to this line https://github.com/nuxt/nuxt/blob/876fa7f3136129097ae3d04acff1dac87f2d2a90/packages/nuxt/src/app/composables/fetch.ts#L88

Since we don't actually change the body, url, or params, the cache is hit.

I think it would be sensible to also include the headers in the caching key.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
I think this is reasonable 👍

**Comment by c-schwan** [comment]
> I think this is reasonable 👍

I reported that issue a Long time ago with bearer Token in Header Hits the cache

**Comment by sisou** [comment]
Ha! This now triggers cache-misses when setting headers with `useRequestHeaders`, which only populates the headers on server-side, but not client-side: #23900

**Comment by ahoiroman** [comment]
Broke my little $larafetch util, as I now get multiple XSRF-cookies back as reported in https://github.com/nuxt/nuxt/issues/23900
