### ISSUE TITLE
<component is="NuxtLink" ...> doesn't render 

### ISSUE THREAD

**Issue by selimdoyranli** [nuxt/nuxt#23450]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.0.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.17
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-dvdiuv?file=app.vue

### Describe the bug

Hi,

I encountered a problem while creating a generic app button component in my project. I am using the dynamic component creation method in Vue and when I send a _NuxtLink_  value to the is attribute of the component tag, it does not render. I didn't encounter this problem on nuxt2. But it doesn't work on nuxt3. How can I solve it?

`<Component is="NuxtLink" to="/page">Link</Component>` doesn't render as a tag

### Additional context

My button component

```
<template lang="pug">
Component.app-button(
  :is="as"
  v-bind="$attrs"
  :class="[variantClass, textTypeClass, linkTypeClass, outlineClass, blockClass, iconPositionClass, loadingClass]"
  role="button"
)
  template(v-if="$slots.prepend")
    slot(name="prepend")

  template(v-if="iconPosition === 'left'")
    .app-button__icon
      slot(name="icon")

  slot

  template(v-if="iconPosition === 'right'")
    .app-button__icon
      slot(name="icon")

  template(v-if="$slots.append")
    slot(name="append")
</template>

<script setup lang="ts">
import type { ButtonPropTypes } from './AppButton.component.types'

const baseClassName = 'app-button'

const props = withDefaults(defineProps<ButtonPropTypes>(), {
  as: 'button',
  variant: 'default',
  text: false,
  link: false,
  outline: false,
  block: false,
  iconPosition: 'left'
})

const slots = useSlots()

const variantClass = computed(() => `${baseClassName}--${props.variant}`)

const textTypeClass = computed(() => props.text && `${baseClassName}--text`)
const linkTypeClass = computed(() => props.link && `${baseClassName}--link`)
const outlineClass = computed(() => props.outline && `${baseClassName}--outline`)
const blockClass = computed(() => props.block && `${baseClassName}--block`)

const iconPositionClass = computed(() => {
  if (slots.icon) {
    if (props.iconPosition === 'left') {
      return `${baseClassName}--iconLeft`
    } else if (props.iconPosition === 'right') {
      return `${baseClassName}--iconRight`
    } else {
      return null
    }
  } else {
    return null
  }
})

const loadingClass = computed(() => props.loading && `${baseClassName}--loading`)
</script>

<style lang="scss" src="./AppButton.component.scss"></style>
```

**Comment by warflash** [comment]
You need to explicitly resolve the component, see -> https://github.com/nuxt/nuxt/issues/13659#issuecomment-1397310923

**Comment by selimdoyranli** [comment]
> You need to explicitly resolve the component, see -> [#13659 (comment)](https://github.com/nuxt/nuxt/issues/13659#issuecomment-1397310923)

sorry for the duplicate. i couldn't find it in the issues. thanks a lot
