### ISSUE TITLE
TS Typing issue.

### ISSUE THREAD

**Issue by rkfiv** [nuxt/nuxt#23460]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.14.1
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  pnpm@8.7.0
- Builder:          -
- User Config:      devServer, sitemap, runtimeConfig, typescript, experimental, routeRules, modules, build, chatwoot, target, components, hooks, piniaPersistedstate, vuetify, vite, app, imports, colorMode, gtag, css, pinia, devtools
- Runtime Modules:  nuxt-lodash@2.5.0, @pinia/nuxt@0.4.11, @productdevbook/chatwoot@1.3.0, @nuxtjs/device@3.1.1, @nuxtjs/tailwindcss@6.8.0, nuxt-gtag@0.5.9, @nuxtjs/color-mode@3.3.0, nuxt-simple-sitemap@3.3.5, @nuxt/image@1.0.0-rc.2, @invictus.codes/nuxt-vuetify@0.3.0, @pinia-plugin-persistedstate/nuxt@1.1.2, @storyblok/nuxt@5.7.1
- Build Modules:    -

### Reproduction

Our application is private, I hope this is not too much of an issue. I will try to provide as much context as possible.

### Describe the bug

I have multiple Pinia stores in my application, most of them have are automatically typed and I get intellisense recommendations in vsCode for them. However, after some time, the type transforms from a pinia store to any. I then lose all type recommendations, I have tried for hours to fix it, I cant seem to figure it out. I can share a store for context.

`import { useVuelidate } from "@vuelidate/core";
import { cloneDeep, toNumber } from "lodash";
import { getNestedObjectValue, setNestedObjectValue } from "./helpers";
export const useApplicationStore = defineStore(
  "application",
  () => {
    // ? Questionnaire Definitions

    let questionnaires = reactive([
      {
        id: "petitionPartOne",
        label: "Petition Part One",
        progress: {
          completed: false,
          percentage: 0,
        },
        navigation: {
          history: [],
        },
        questionCategories: petitionPartOneCategories(),
      },
    ]);

    //#region Data Definitions

    function dynamicProperty(path) {
      return computed({
        get: () => getNestedObjectValue($customerData, path),
        set: (value) => setNestedObjectValue($customerData, path, value),
      });
    }
    let $settings = reactive({
      startingQuestionnaireId: "petitionPartOne",
    });

    let $data = reactive({
      activeQuestionnaireID: "",
      activeQuestionnaireCategoryID: "",
      activeQuestionID: "",
    });

    let $customerData = reactive({
      sponsor: {
        fullName: {
          first: "",
          middle: "",
          last: "",
        },
      },
      beneficiary: {
        fullName: {
          first: "",
          middle: "",
          last: "",
        },
      },
    });
    //#endregion Data Definitions

    //#region Computed Getters
    let questionCompletionStatusInjection = (questionId) => {
      return activeQuestionnaire.value!.questionCategories
    }

    let activeQuestionnaire = computed(() => {
      return questionnaires.find(
        (questionnaire) => questionnaire.id === $data.activeQuestionnaireID
      );
    });
    let activeQuestionnaireQuestionCategories = computed(() => {
      if (!activeQuestionnaire.value) {
        return "Active Questionnaire Is Unset";
      }
      return activeQuestionnaire.value.questionCategories;
    });
    let activeQuestionnaireProgress = computed(() => {
      if (!activeQuestionnaire.value) {
        return "Active Questionnaire Is Unset";
      }
      return activeQuestionnaire.value.progress;
    });
    let activeQuestionnaireCategory = computed(() => {
      if (!activeQuestionnaire.value) {
        return "Active Questionnaire Is Unset";
      } else if (activeQuestionnaire.value) {
        return activeQuestionnaire.value.questionCategories.find(
          (category) => category.id === $data.activeQuestionnaireCategoryID
        );
      }
    });
    let activeQuestionnaireCategoryIndex = computed(() => {
      if (!activeQuestionnaire.value) {
        return "Active Questionnaire Is Unset";
      } else if (activeQuestionnaire.value) {
        return activeQuestionnaire.value.questionCategories.findIndex(
          (category) => category.id === $data.activeQuestionnaireCategoryID
        );
      }
    });
    let onFinalQuestionnaireCategory = computed(() => {
      if (!activeQuestionnaire.value) {
        return "Active Questionnaire Is Unset";
      } else if (activeQuestionnaire.value) {
        return (
          activeQuestionnaireCategoryIndex.value ===
          activeQuestionnaire.value.questionCategories.length - 1
        );
      }
    });
    let activeQuestion = computed(() => {
      if (typeof activeQuestionnaireCategory.value !== "string") {
        return activeQuestionnaireCategory.value!.questions.find(
          (question) => question.id === $data.activeQuestionID
        );
      } else {
        return "Active Questionnaire Category Is Unset";
      }
    });
    let nextQuestion = computed(() => {
      if (typeof activeQuestionnaireCategory.value !== "string") {
        let nextQuestionIndex =
          activeQuestionnaireCategory.value!.questions.findIndex(
            (question) => question.id === $data.activeQuestionID
          );
        if (
          activeQuestionnaireCategory.value!.questions.length ===
          nextQuestionIndex + 1
        ) {
          return "End of Questionnaire";
        }
        return activeQuestionnaireCategory.value!.questions[
          nextQuestionIndex + 1
        ];
      } else {
        return "Active Questionnaire Category Is Unset";
      }
    });
    //#endregion Computed Getters

    //#region Actions

    let setActiveQuestionnaire = (questionnaireId) => {
      $data.activeQuestionnaireID = questionnaireId;
    };
    let setActiveQuestionnaireCategoryToFirstCategoryInQuestionnaire = () => {
      if (typeof activeQuestionnaireQuestionCategories.value[0] !== "string") {
        $data.activeQuestionnaireCategoryID =
          activeQuestionnaireQuestionCategories.value[0].id;
      }
    };
    let setActiveQuestionnaireCategoryToNextCategoryInQuestionnaire = () => {
      if (typeof activeQuestionnaireQuestionCategories.value[0] !== "string") {
        $data.activeQuestionnaireCategoryID =
          activeQuestionnaireQuestionCategories.value[
            toNumber(activeQuestionnaireCategoryIndex.value!) + 1
          ].id;
      }
    };
    let setActiveQuestionIDToFirstQuestionInActiveQuestionnaireCategory =
      () => {
        if (
          typeof activeQuestionnaireCategory.value !== "string" &&
          typeof activeQuestionnaireCategory.value !== "undefined"
        ) {
          $data.activeQuestionID =
            activeQuestionnaireCategory.value.questions[0].id;
        } else {
          console.error("Active Questionnaire Category is undefined");
        }
      };
    let setActiveQuestion = (questionId) => {
      $data.activeQuestionID = questionId;
    };

    let navigateToNextQuestion = () => {
      if (nextQuestion.value === "Active Questionnaire Category Is Unset") {
        console.error("Next Question is undefined");
        return;
      }
      // @ts-ignore
      if (nextQuestion.value == "End of Questionnaire") {
        // TODO - We need to check if there is other categories in the questionnaire
        // TODO - If there is, set the activeQuestionnaireCategory to the first one
        if (!onFinalQuestionnaireCategory.value) {
          setActiveQuestionnaireCategoryToNextCategoryInQuestionnaire();
          setActiveQuestionIDToFirstQuestionInActiveQuestionnaireCategory();
        }
      } else {
        setActiveQuestion(activeQuestion.value!.nextQuestion());
      }
    };

    let initialize = () => {
      // ! If none in memory, set active questionnaire to starting questionnaire
      // ! If there is one in memory, set active questionnaire to that one
      if (!$data.activeQuestionnaireID) {
        setActiveQuestionnaire($settings.startingQuestionnaireId);
        // TODO - Now we need to get the activeQuestionnaire so we can explore its questionCategories
        // ? You can get the active questionnaire by calling activeQuestionnaire.value
        // TODO - Of the categories lets get the first one then set that as the activeQuestionnaireCategory by its id
        setActiveQuestionnaireCategoryToFirstCategoryInQuestionnaire();
        // TODO - Now we need to set the activeQuestion to the first question in the activeQuestionnaireCategory
        setActiveQuestionIDToFirstQuestionInActiveQuestionnaireCategory();
      }
    };
    //#endregion Actions
    
    initialize();

    //#region Return Object
    return {
      $settings,
      $data,
      $customerData,
      activeQuestionnaireProgress,
      activeQuestionnaireQuestionCategories,
      activeQuestionnaire,
      activeQuestion,
      questionnaires,

      activeQuestionnaireCategory,
      nextQuestion,
      activeQuestionnaireCategoryIndex,
      onFinalQuestionnaireCategory,
      dynamicProperty,
      setActiveQuestionnaire,
      setActiveQuestionnaireCategoryToFirstCategoryInQuestionnaire,
      setActiveQuestionIDToFirstQuestionInActiveQuestionnaireCategory,
      // ? Questionnaire Navigation Actions
      navigateToNextQuestion,
      initialize,
    };
    //#endregion Return Object
  },
  {
    // persist: true,
  }
);
if (import.meta.hot) {
  import.meta.hot.accept(acceptHMRUpdate(useApplicationStore, import.meta.hot));
}
`
This is a store, I have it setup to auto import, other stores in the same folder work the way expected with the exception of one other one. It was working just yesterday. This happens on my macbook & my windows machine, so it is not the OS or anything like that. 

here is my tsconfig `{
  // https://nuxt.com/docs/guide/concepts/typescript
  "extends": "./.nuxt/tsconfig.json",
  "compilerOptions": {
    "strict": true,
    "allowJs": true,
    "jsx": "preserve",
    "noImplicitAny": false,
    "noImplicitThis": false,
  }

}
`

and my nuxt.config.ts 

`// https://nuxt.com/docs/api/configuration/nuxt-config
import { checker } from 'vite-plugin-checker'
export default defineNuxtConfig({
  devServer: {
    port: 1234,
  },
  sitemap: {
    runtimeCacheStorage: false,
  },
  runtimeConfig: {
    stripeSecret: process.env.STRIPE_SECRET_KEY,

    private: {},
    public: {},
  },
  typescript: {
    typeCheck: false,
    includeWorkspace: true,
    shim: false,
    strict: false,
  },
  
  experimental: {
    renderJsonPayloads: true,
  },
  routeRules: {
    // Homepage pre-rendered at build time
    "/": { ssr: false },
    // '/sitemap.xml': { prerender: true, ssr:false },
    "/immigration-resources": {},
    // "/immigration-resources/*": { sitemap: { changefreq: 'daily', priority: 0.3 }},
    "/path/*": { ssr: false },
    "/eligibility/**": { ssr: false },
    "/onboarding/**": { ssr: false },
    "/dashboard/**": { ssr: false },
    "/application/**": { ssr: false },
  },

  modules: [
    "nuxt-lodash",
    "@pinia/nuxt",
    "@productdevbook/chatwoot",
    "@nuxtjs/device",
    "@nuxtjs/tailwindcss",
    "nuxt-gtag",
    "@nuxtjs/color-mode",
    "nuxt-simple-sitemap",
    "@nuxt/image",
    "@invictus.codes/nuxt-vuetify",

    "@pinia-plugin-persistedstate/nuxt",
    [
      "@storyblok/nuxt",
      {
        accessToken: "aSFqeRkLQQPsTCOM3suWaQtt",
        bridge: true,
        devtools: true,
        apiOptions: {
          region: "us", // When creating your space in US region (EU default)c
        },
        cache: {
          type: "custom",
          custom: {
            flush() {
            },
          },
        },
      },
    ]
  ],
  build: {
    transpile: ["fsevents", "maz-ui"],
  },
  chatwoot: {
    init: {
      websiteToken: "isqLe6pfKaxEra1rkNYx6g7m",
    },
    settings: {
      locale: "en",
      position: "right",
      launcherTitle: "Hello Chat",
      // ... and more settings
    },
    // If this is loaded you can make it true, https://github.com/nuxt-modules/partytown
    partytown: false,
  },

  // ssr: true,
  target: "static",

  components: {
    global: true,
    dirs: ["~/components"],
  },
  hooks: {
    // "vite:extendConfig": (config, { isClient, isServer }) => {
    //   if (isClient) config!.resolve!.alias!.vue! = "vue/dist/vue.esm-bundler.js";
    // },
  },

  // buildModules: ["@nuxtjs/pwa",],
  // pwa: {
  //   meta: {
  //     mobileAppIOS: true,
  //   },
  // },
  piniaPersistedstate: {},
  vuetify: {
    /* vuetify options */
    vuetifyOptions: {
      // @TODO: list all vuetify options
      ssr: true,
    },
    theme: {
      defaultTheme: 'dark'
    },
    styles: { configFile: "@/assets/css/vuetifyConfig.scss" },
    moduleOptions: {
      /* nuxt-vuetify module options */
      treeshaking: true,
    },
  },
  //  plugins:['@/plugins/composition-api.js','@/plugins/rich-text-renderer.js'],
  
  vite: {
    plugins: [
      checker({
        vueTsc: true,
      }),
    ],
    optimizeDeps: { exclude: ["fsevents"] },
  },

  app: {
    pageTransition: { name: "page", mode: "out-in" },
  },
  imports: {

    dirs: [
      'composables/**', 'stores/**'
    ]
  },
  colorMode: {
    preference: "dark",
    fallback: "dark",
    hid: "nuxt-color-mode-script",
    globalName: "__NUXT_COLOR_MODE__",
    componentName: "ColorScheme",
    classPrefix: "",
    classSuffix: "",
    storageKey: "nuxt-color-mode",
  },

  gtag: {
    id: "G-LQ3CJ7EM1M",
  },

  css: [
    "~/assets/styles/main.scss",
    "~/assets/css/breakpoints.css",
    "@fortawesome/fontawesome-svg-core/styles.css",
    "maz-ui/css/main.css",
    "@/assets/css/tailwind.css",
    "@/assets/css/fa6/css/fontawesome.css",
    "@/assets/css/fa6/css/regular.css",
    "@/assets/css/fa6/css/solid.css",
  ],
  pinia: {
    autoImports: ["defineStore", "definePiniaStore", "acceptHMRUpdate"], // import { defineStore as definePiniaStore } from 'pinia'
    
  },
  devtools: {
    enabled: false,
  },
});
`

for example, when in a .vue component anywhere if i type useApplicationStore() the type is any, but if i call use<store-name>Store()  calling any of my other stores the typing is there and everything works as expected.

I will attach the nuxt generated types here:

[File too large] However the imports for the store look like any of the others that function properly.

### Additional context

I have tried deleting node-modules, performing nuxi cleanup, running typecheck, im not exactly sure what's going on.

**Comment by rkfiv** [comment]
![workingstore](https://github.com/nuxt/nuxt/assets/74265876/7d764952-8315-401c-a5ee-22e76c1a45e3)
![types](https://github.com/nuxt/nuxt/assets/74265876/c95656d7-6ec0-40d0-be72-26054af1a50d)
![nonworking](https://github.com/nuxt/nuxt/assets/74265876/0b0aab55-ae4c
![nonworking2](https://github.com/nuxt/nuxt/assets/74265876/972f8630-0246-4a10-9076-a168ab63f847)
-4908-90c5-203ac670c1c4)

**Comment by rkfiv** [comment]
I dont even know where to start with fixing this, im sorry if im not explaining what's happening the best way, im trying to with the best of my knowledge. Thank you anyone who may be able to help!

**Comment by danielroe** [comment]
It will be tricky to help only snippets of code pasted into an issue. Ideally a minimum runnable reproduction that can be cloned and opened in VSCode.

However, I would ask that you first check with running `vue-tsc --noEmit` to rule out editor issues.

**Comment by Rigo-m** [comment]
I have had TS typing issues as well after 3.7.3. 3.7.2 worked fine. I have a slimmer repo at this point, I might be able to provide a reproduction probably in the next days

**Comment by danielroe** [comment]
Please feel free to provide a reproduction and I'll happily reopen.
