### ISSUE TITLE
Something is bad with plugin types 

### ISSUE THREAD

**Issue by imcm7** [nuxt/nuxt#23478]
### Environment

upgraded today

### Reproduction

Here all is ok with hook

```
import { H3Event } from 'h3';
import { NitroApp } from 'nitropack';
import { useCompression } from 'h3-compression';

import { defineNitroPlugin } from 'nitropack/dist/runtime/plugin';

export default defineNitroPlugin((nitroApp: NitroApp) => {
  nitroApp.hooks.hook('render:response', async (response, { event  }: { event: H3Event }) => {}
}
```

After upgrade warnings `Argument of type '(event: H3Event) => void' is not assignable to parameter of type 'never'.`

```
import { H3Event } from 'h3';
import { NitroApp } from 'nitropack';

import { defineNitroPlugin } from 'nitropack/dist/runtime/plugin';

export default defineNitroPlugin((nitroApp: NitroApp) => {
    nitroApp.hooks.hook('request', (event: H3Event) => {} 
}
```

### Describe the bug

Argument of type '(event: H3Event) => Promise<void>' is not assignable to parameter of type 'never'

**Comment by imcm7** [comment]
All do some think https://github.com/search?q=defineNitroPlugin&type=code

```
// fix type stub - See https://github.com/nuxt/nuxt/issues/18556
7 | export type NitroAppPlugin = (nitro: NitroApp) => void
8 | function defineNitroPlugin(def: NitroAppPlugin): NitroAppPlugin {
9 | return def
10 | }
```

**Comment by imcm7** [comment]
or to do like here https://github.com/arashsheyda/nuxt-mongoose/pull/9/files

**Comment by imcm7** [comment]
Function implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.

**Comment by danielroe** [comment]
this has been resolved in https://github.com/unjs/nitro/pull/1769

**Comment by imcm7** [comment]
@danielroe now on edge I have

```
Argument of type '(response: Partial<RenderResponse>, { event }: { event: H3Event<EventHandlerRequest>; }) => Promise<void>' is not assignable to parameter of type '(response: Partial<RenderResponse>, context: { event: H3Event<EventHandlerRequest>; }) => void'.
  Types of parameters '__1' and 'context' are incompatible.
  ```
  
  for that `nitroApp.hooks.hook('render:response', async (response, { event  }: { event: H3Event }) => {}`

**Comment by imcm7** [comment]
Argument of type 'import("/home/node/nuxt/node_modules/.pnpm/h3-nightly@1.8.3-1695749697.86ad8e7/node_modules/h3-nightly/dist/index").H3Event<import("/home/node/nuxt/node_modules/.pnpm/h3-nightly@1.8.3-1695749697.86ad8e7/node_modules/h3-nightly/dist/index").EventHandlerRequest>' is not assignable to parameter of type 'import("/home/node/nuxt/node_modules/.pnpm/h3@1.8.2/node_modules/h3/dist/index").H3Event<import("/home/node/nuxt/node_modules/.pnpm/h3@1.8.2/node_modules/h3/dist/index").EventHandlerRequest>'.
  The types of 'context.matchedRoute' are incompatible between these types.
