### ISSUE TITLE
Could not resolve id ../jsx /project/sandbox/node_modules/.pnpm/vue@3.3.4/node_modules/vue/dist/vue.d.ts

### ISSUE THREAD

**Issue by jesephan** [nuxt/nuxt#23473]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.14.2
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  pnpm@8.8.0
- Builder:          -
- User Config:      ssr, pages, srcDir, devtools, modules
- Runtime Modules:  @vue-macros/nuxt@1.9.1, @vueuse/nuxt@10.4.1, @nuxt/devtools@0.8.5
- Build Modules:    -
------------------------------

### Reproduction

https://codesandbox.io/p/sandbox/zealous-neco-jhjpq2

### Describe the bug

Our objective is to clean up the console from any error or warning. This time we always see this kind of warning in the console when we run `pnpm run dev` saying Could not resolve id ** from ***/.pnpm/[package]/node_modules/**.d.ts. This only happened when we started upgrading to latest version of nuxt 3.7.4.

**Comment by danielroe** [comment]
This seems to be coming from `@vue-macros/nuxt`. Would you raise an issue there instead? 🙏

**Comment by ojvribeiro** [comment]
@jesephan

From https://github.com/vue-macros/vue-macros/issues/505:

> You can disable `betterDefine` feature if you don't need it.
