### ISSUE TITLE
When the parameters of a route are changed programmatically, the page will be rerendered.

### ISSUE THREAD

**Issue by alokVishu** [nuxt/nuxt#23474]
### Environment

Nuxt project info: (copied to clipboard)                                                                                                                                                     12:51:42 PM

------------------------------
- Operating System: Darwin
- Node Version:     v18.18.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, modules, vite, build
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://github.com/alokVishu/nuxt-route-params-change-issue

### Describe the bug

I am working on a Nuxt project with Vuetify, and I have noticed that when I programmatically change the parameters of the same route, the entire page gets re-rendered. This behavior is not observed in Vuetify with the Vue project.

I have also attached the Gif for your refresh.

https://github.com/nuxt/nuxt/assets/80033712/b6079cef-ee36-4f31-99aa-87e0dde59ff3

**Comment by danielroe** [comment]
By default, we rerender dynamic pages like `[slug].vue` but you can either use nested pages, or set a custom key like this:

```vue
<script setup>
definePageMeta({
  key: 'tabs'
})
// ... the rest of your component
</script>
```

**Comment by danielroe** [comment]
I would guess that is because it's not rerunning the setup function. (That's the point of the key.)

But you have this code:

```ts
const activeTab = ref(route.params.tab)
```

Again, I haven't checked, but you should probably not have a separate ref, but directly use the route param in your template.
