### ISSUE TITLE
`/server` files doesn't auto-import

### ISSUE THREAD

**Issue by DarkGhostHunter** [nuxt/nuxt#23471]
### Environment

Working directory: /users/italo/projects/finance/headless                                                                                                        12:55:01
Nuxt project info:                                                                                                                                           12:55:01

------------------------------
- Operating System: WSL2
- Node Version:     v20.5.1
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@9.8.0
- Builder:          -
- User Config:      watch, devtools, ssr, app, css, modules, colorMode, pwa, ui, runtimeConfig, googleFonts, tailwindcss
- Runtime Modules:  nuxt-lodash@2.5.0, nuxt-icon@0.5.0, @vite-pwa/nuxt@0.1.1, @nuxthq/ui@2.7.0, @nuxtjs/color-mode@3.3.0, @nuxtjs/google-fonts@3.0.2
- Build Modules:    -

### Reproduction

1. Create a new project
2. Create a file `~/composables/useTest.js` that export a function that returns an object.

```js
export default () => { name: 'test' }
```

3. Create a file `~/server/api/test.js` with the following contents:

```js
export default () => useTest()
```

4. Open `https://localhost:3000/api/test`

Response is:

```json
{
    "url": "/api/test",
    "statusCode": 500,
    "statusMessage": "",
    "message": "useTest is not defined",
}
```

### Describe the bug

No autoimports work. Trying to import manually a composable that uses autoimports return errors because the autoimports it uses are also not found.

**Comment by danielroe** [comment]
`~/composables` are only for use in the Vue part of your app. There is a folder `~/server/utils` you can use for auto-imports within the nitro part of your app.
