### ISSUE TITLE
[Vue Router warn]: No match found for location with path "/service-worker.js"

### ISSUE THREAD

**Issue by kouroshtajalliepour** [nuxt/nuxt#23475]
### Environment

- Operating System: Darwin
- Node Version:     v18.18.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  pnpm@8.8.0
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

bug happens after installing nuxt

### Describe the bug

in an empty project with 1 page that contains only a h3 element after running pnpm dev for every request that nuxt receives from a browser these warnings get printed to the console

`[Vue Router warn]: No match found for location with path "/service-worker.js?pusherBeamsWebSDKVersion=1.0.3"
[Vue Router warn]: No match found for location with path "/service-worker.js?pusherBeamsWebSDKVersion=1.0.3"
[Vue Router warn]: No match found for location with path "/service-worker.js?pusherBeamsWebSDKVersion=1.0.3"
[Vue Router warn]: No match found for location with path "/service-worker.js"
[Vue Router warn]: No match found for location with path "/service-worker.js?pusherBeamsWebSDKVersion=1.0.3"
[Vue Router warn]: No match found for location with path "/service-worker.js?pusherBeamsWebSDKVersion=1.0.3"
[Vue Router warn]: No match found for location with path "/service-worker.js?pusherBeamsWebSDKVersion=1.0.3"
[Vue Router warn]: No match found for location with path "/service-worker.js"`

```[tasklist]
### Tasks
```

**Comment by danielroe** [comment]
This isn't a Nuxt bug. Likely you have a service worker installed on localhost:3000 from a different project.
