### ISSUE TITLE
Using `useRoute` from auto-import makes the page component render twice.

### ISSUE THREAD

**Issue by nndnha** [nuxt/nuxt#23488]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-tmvnrq?file=layouts%2Fdefault.vue

### Describe the bug

Inconsistent behavior exists between two versions of `useRoute`. The one imported from `vue-router` functions as expected, while the other from Nuxt causes the component to render twice (mount -> unmount -> then mount again). This behavior leads to a performance penalty, particularly on pages with heavy computation.

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/21340.
