### ISSUE TITLE
make new project problem in v3.7

### ISSUE THREAD

**Issue by xfire5000** [nuxt/nuxt#23494]
### Environment

make new project problem in v3.7 with node 18.17 on windows platform

### Reproduction

nuxt 3.7

### Describe the bug

after run installation command in first page of nuxt.com nuxt project install unsuccessful with exit code 1
![Screenshot 2023-10-01 210557](https://github.com/nuxt/nuxt/assets/57075642/e3770dd9-324a-4a31-9d4b-f8d900155a30)

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/23489

**Comment by danielroe** [comment]
This has now been resolved in the latest version of `@nuxt/telemetry`, v2.5.2 - thanks @collins-lagat.

You should be able to manually add and remove the dependency or run `npm up @nuxt/telemetry` to resolve...
