### ISSUE TITLE
Nitro useStorage with FS driver is broken in Netlify functions

### ISSUE THREAD

**Issue by bytesbay** [nuxt/nuxt#23492]
### Environment

Netlify functions

Nuxt 3.7.4

### Reproduction

Add this to next.config.ts

```typescript
{
  // ...
  nitro: {
      
    storage: {
      precompiled: {
        driver: 'fs',
        base: 'public/precompiled/',
      }
    }
  },
  // ...
}
```
Add some .bin files to ~/public/precompiled/

And run `"build:prod": "NITRO_PRESET=netlify nuxt build"` in your netlify function

Now lest run this API endpoint

```typescript
const storage = useStorage("precompiled");
const vertices = await storage.getItemRaw("vertices.bin.gz");
console.log(vertices); // returns null
```

### Describe the bug

storage.getItemRaw("file.bin") returns null in netlify functions.

### Additional context

In local environment (npm run dev) works good, but in netlify production simply does not work.

**Comment by bytesbay** [comment]
I noticed that the storage in Netlify logs is mounted to a different path than it has to.
 
 Here is the mount object
 ```json
 {"name":"fs","options":{"driver":"fs","base":"/opt/build/repo/public/precompiled","ignore":["**/node_modules/**","**/.git/**"]}}
 ```
 
 So it is mounted to `/opt/build/repo/public/precompiled`
 
 But the `cwd()` in Netlify runtime shows this `/var/task`

**Comment by bytesbay** [comment]
Any ideas how fix this up? Maybe updating the nuxt config relying on env vars while building for netlify, as a quick fix.

**Comment by danielroe** [comment]
would you raise this in https://github.com/unjs/nitro ? 🙏

**Comment by bytesbay** [comment]
Raised it [here](https://github.com/unjs/nitro/issues/1775)

**Comment by danielroe** [comment]
Thank you. Let's track it there.
