### ISSUE TITLE
Cannot start nuxt:  The requested module 'vite-plugin-inspect' does not provide an export named 'default'

### ISSUE THREAD

**Issue by fathi91** [nuxt/nuxt#23493]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.1
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

fresh install

### Describe the bug

I started  a new project:
`npx nuxi@latest init my-project
`
then `cd my-project`

and `yarn dev`
the first thing i got is this error

### Logs

```shell-script
[7:10:59 PM]  ERROR  Cannot start nuxt:  The requested module 'vite-plugin-inspect' does not provide an export named 'default'

  import Inspect from 'vite-plugin-inspect';
  ^^^^^^^
  SyntaxError: The requested module 'vite-plugin-inspect' does not provide an export named 'default'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
```

**Comment by CharMinder** [comment]
I am experiencing this as well.

**Comment by RvtRebel** [comment]
Same with node 18.18.0 and yarn 3.6.3

**Comment by cwaring** [comment]
It looks like the exports were changed in [v0.7.39 release of `vite-plugin-inspect`](https://github.com/antfu/vite-plugin-inspect/compare/v0.7.38...v0.7.39), if you're using `pnpm` you can _temporarily_ override this with the following in your `package.json`:


```json
  "pnpm": {
    "overrides": {
      "vite-plugin-inspect": "0.7.38"
    }
  }
```

**Comment by agelinas** [comment]
I'm having the same problem today. Tried and retried and get the same result.

**Comment by alexd73** [comment]
This is worked with `yarn`
```
"resolutions": {
    "vite-plugin-inspect": "0.7.38"
  } 
```

**Comment by wheatjs** [comment]
Not an optimal solution, but as a workaround if you are using a package manager like bun which doesn't support overrides yet. You can disable nuxt devtools until this is fixed.

**Comment by ayalon** [comment]
If you are using npm, you may use:
```
  "overrides": {
    "vite-plugin-inspect": "0.7.38"
  }
```

**Comment by danielroe** [comment]
cc: @antfu

**Comment by nonInfelix** [comment]
As @wheatjs said, the only fix for me was to delete `  devtools: { enabled: true },` from nuxt.config.ts

**Comment by JokerMartini** [comment]
> As @wheatjs said, the only fix for me was to delete ` devtools: { enabled: true },` from nuxt.config.ts

Same here, by removing this line of code, the project then launched correctly.

**Comment by AMP3RAGE** [comment]
> > As @wheatjs said, the only fix for me was to delete ` devtools: { enabled: true },` from nuxt.config.ts
> 
> Same here, by removing this line of code, the project then launched correctly.

I just changed enabled to false and it worked.

**Comment by antfu** [comment]
It should be fixed in the latest version. Sorry for the trouble.
