### ISSUE TITLE
nuxt3 app Firebase Deploy Unexpected Error. how to ?[An unexpected error has occurred.] [TypeError: Cannot read properties of null (reading 'match')]

### ISSUE THREAD

**Issue by toriumi72** [nuxt/nuxt#23496]
### Environment

Working directory: /Users/User2/Desktop/Desktop/LINE-shift/LINE-shift-staff                        14:24:48
Nuxt project info: (copied to clipboard)                                                           14:24:48

------------------------------
- Operating System: Darwin
- Node Version:     v18.18.0
- Nuxt Version:     3.7.3
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@9.8.1
- Builder:          -
- User Config:      devtools, modules, runtimeConfig, nitro, ui
- Runtime Modules:  @nuxthq/ui@2.7.0
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/toriumi72/LINE_shift/tree/master

### Describe the bug

I have been encountering an unexpected error while trying to deploy my project using Firebase. The error occurred suddenly; everything was working fine until August 28th. Here is the background and the error message I received:

### Additional context

・package.json
{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "clean": "cd .output/server && rm -rf node_modules && npm i",
    "deploy": "npm npm run build && npm run clean && firebase deploy",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/devtools": "latest",
    "nuxt": "^3.7.4",
    "vue": "^3.3.4",
    "vue-router": "^4.2.5",
    "@nuxthq/ui": "^2.7.0",
    "cdate": "^0.0.6"
  },
  "overrides": {
    "vite-plugin-inspect": "0.7.38"
  },
  "dependencies": {
    "firebase": "^10.4.0",
    "firebase-admin": "^11.11.0",
    "firebase-functions": "^4.4.1",
    "firebase-functions-test": "^3.1.0"
  }
}

・firebase.json
{
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  },
  "functions": [
    {
      "source": ".output/server",
      "codebase": "default",
      "ignore": [
        "node_modules",
        ".git",
        "firebase-debug.log",
        "firebase-debug.*.log"
      ]
    }
  ],
  "hosting": {
    "public": ".output/public",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "cleanUrls": true,
    "rewrites": [
      {
        "source": "**",
        "function": "server"
      }
    ]
  },
  "storage": {
    "rules": "storage.rules"
  }
}

### Logs

```shell-script
=== Deploying to 'line-shift'...
i  deploying storage, firestore, functions, hosting
i  firebase.storage: checking storage.rules for compilation errors...
✔  firebase.storage: rules file storage.rules compiled successfully
i  firestore: reading indexes from firestore.indexes.json...
i  cloud.firestore: checking firestore.rules for compilation errors...
✔  cloud.firestore: rules file firestore.rules compiled successfully
i  functions: preparing codebase default for deployment
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled...
✔  functions: required API cloudbuild.googleapis.com is enabled
✔  functions: required API cloudfunctions.googleapis.com is enabled
✔  artifactregistry: required API artifactregistry.googleapis.com is enabled
i  functions: Loading and analyzing source code for codebase default to determine what to deploy
Serving at port 8875
shutdown requested via /__/quitquitquit
Error: An unexpected error has occurred.

---------------------------------------------------------------------------------------------

... 
[debug] [2023-09-19T01:45:05.303Z] Could not find functions.yaml. Must use http discovery 
[debug] [2023-09-19T01:45:05.307Z] Found firebase-functions binary at '/Users/User2/Desktop/Desktop/LINE-shift/node_modules/.bin/firebase-functions' 
[info] Serving at port 8149 
[debug] [2023-09-19T01:45:05.478Z] Got response from /__/functions.yaml {"endpoints":{"server":{"platform":"gcfv1","availableMemoryMb":null,"timeoutSeconds":null,"minInstances":null,"maxInstances":null,"ingressSettings":null,"serviceAccountEmail":null,"vpc":null,"region":[null],"httpsTrigger":{},"entryPoint":"server"}},"specVersion":"v1alpha1","requiredAPIs":[]} 
[info] shutdown requested via /__/quitquitquit 
[debug] [2023-09-19T01:45:10.643Z] TypeError: Cannot read properties of null (reading 'match') at resolveString (/opt/homebrew/lib/node_modules/firebase-tools/lib/deploy/functions/params.js:31:27) at /opt/homebrew/lib/node_modules/firebase-tools/lib/deploy/functions/params.js:47:36 at Array.map (<anonymous>) at Object.resolveList (/opt/homebrew/lib/node_modules/firebase-tools/lib/deploy/functions/params.js:47:21) at toBackend (/opt/homebrew/lib/node_modules/firebase-tools/lib/deploy/functions/build.js:180:30) at Object.resolveBackend (/opt/homebrew/lib/node_modules/firebase-tools/lib/deploy/functions/build.js:73:23) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async prepare (/opt/homebrew/lib/node_modules/firebase-tools/lib/deploy/functions/prepare.js:68:62) at async chain (/opt/homebrew/lib/node_modules/firebase-tools/lib/deploy/index.js:38:9) at async deploy (/opt/homebrew/lib/node_modules/firebase-tools/lib/deploy/index.js:95:5) 
[error] 
[error] Error: An unexpected error has occurred.
```

**Comment by danielroe** [comment]
Would you be able to open a nitro reproduction upstream at https://github.com/unjs/nitro ? 🙏

**Comment by ynechaev** [comment]
This issue makes it impossible to deploy a Nuxt 3 project to firebase. I am having the same issue with the following configuration:
```
- Operating System: `Darwin`
- Node Version:     `v20.5.1`
- Nuxt Version:     `3.7.4`
- CLI Version:      `3.9.0`
- Nitro Version:    `2.6.3`
- Package Manager:  `yarn@1.22.19`
- Builder:          `-`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
```

```
firebase -V
12.6.1
```

The following is a related piece of firebase-debug.log:
```
[debug] [2023-10-05T19:38:49.270Z] Building nodejs source
[info] i  functions: Loading and analyzing source code for codebase default to determine what to deploy 
[debug] [2023-10-05T19:38:49.271Z] Could not find functions.yaml. Must use http discovery
[debug] [2023-10-05T19:38:49.276Z] Found firebase-functions binary at '/Users/yuri/src/courses-landing/node_modules/.bin/firebase-functions'
[info] Serving at port 8881

[debug] [2023-10-05T19:38:49.453Z] Got response from /__/functions.yaml {"endpoints":{"server":{"platform":"gcfv1","availableMemoryMb":null,"timeoutSeconds":null,"minInstances":null,"maxInstances":null,"ingressSettings":null,"serviceAccountEmail":null,"vpc":null,"region":[null],"httpsTrigger":{},"entryPoint":"server"}},"specVersion":"v1alpha1","requiredAPIs":[]}
[info] shutdown requested via /__/quitquitquit

[debug] [2023-10-05T19:38:54.468Z] TypeError: Cannot read properties of null (reading 'match')
    at resolveString (/Users/yuri/.nvm/versions/node/v20.5.1/lib/node_modules/firebase-tools/lib/deploy/functions/params.js:31:27)
    at /Users/yuri/.nvm/versions/node/v20.5.1/lib/node_modules/firebase-tools/lib/deploy/functions/params.js:47:36
    at Array.map (<anonymous>)
    at Object.resolveList (/Users/yuri/.nvm/versions/node/v20.5.1/lib/node_modules/firebase-tools/lib/deploy/functions/params.js:47:21)
    at toBackend (/Users/yuri/.nvm/versions/node/v20.5.1/lib/node_modules/firebase-tools/lib/deploy/functions/build.js:180:30)
    at Object.resolveBackend (/Users/yuri/.nvm/versions/node/v20.5.1/lib/node_modules/firebase-tools/lib/deploy/functions/build.js:73:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async prepare (/Users/yuri/.nvm/versions/node/v20.5.1/lib/node_modules/firebase-tools/lib/deploy/functions/prepare.js:68:62)
    at async chain (/Users/yuri/.nvm/versions/node/v20.5.1/lib/node_modules/firebase-tools/lib/deploy/index.js:38:9)
    at async deploy (/Users/yuri/.nvm/versions/node/v20.5.1/lib/node_modules/firebase-tools/lib/deploy/index.js:95:5)
[error] 
[error] Error: An unexpected error has occurred.
```

**Comment by YusufTezel** [comment]
👋 Hello all,

I've come across this issue and haven't been able to find a solution yet. Has anyone managed to resolve this or found a workaround? @danielroe

**Comment by dmaloof** [comment]
had same issue, solved adding specific data to the nitro config

`nitro: {
        preset: 'firebase',
        firebase: {
            nodeVersion: "18",
            gen: 2,
            httpsOptions: {
                region: 'us-central1',
                maxInstances: 3,
            },
        },

    }`

**Comment by aipacommander** [comment]
Hi.

I was able to deploy to 2nd gen by using the configuration in the following URL.

https://github.com/nuxt/nuxt/issues/23496#issuecomment-1758748355

Since I am using 1st gen, the impact of the change in 2nd gen is significant, so I checked the source code to see if I could somehow deploy on 1st gen.

https://github.com/unjs/nitro/blob/ae253596a847f764e275f7e0450ffdfcdcd8957e/src/types/presets.ts#L76-L86

I modified the nitro setting in `nuxt.config.ts` as follows and was able to deploy.

```text
// ...
  nitro: {
    preset: 'firebase',
    firebase: {
      nodeVersion: '18',
      gen: 1,
      region: 'us-central1'
    }
  }
// ...
```

**Comment by julienreszka** [comment]
@aipacommander thank you very much this helped a lot

**Comment by danielroe** [comment]
This is an upstream issue in Nitro. Would you be able to open an issue there so we can track it in the right place? 🙏

**Comment by danieldanielecki** [comment]
`firebase: { nodeVersion: "18", gen: 2 }` is the essential missing part to fix the error. It starts working without the other options.

**Comment by danielroe** [comment]
Do we need to add anything to the docs here or in nitro?

**Comment by HoldenMalinchock** [comment]
@danielroe 
As someone who just spent 3 hours tracking down why my first firebase deployment didn't work yes.  Please add this to the nitro docs.

**Comment by pi0** [comment]
If it is a requirement for deployment i expect that was set by default. @HoldenMalinchock would you mind to open an issue in nitro repo to track in upstream. /cc @posva

**Comment by dosstx** [comment]
Hello everyone. Thank you for discussing this issue and thank you for providing a solution. This made it easy for me to get up and running with my first Firebase Hosting deployment.
