### ISSUE TITLE
Type 'unknown' is not assignable  if in dir pages exists files (index.vue)

### ISSUE THREAD

**Issue by imcm7** [nuxt/nuxt#23491]
### Environment

- Operating System: Linux
- Node Version: v20.6.1
- Nuxt Version: 3.7.3
- CLI Version: 3.9.0
- Nitro Version: 2.6.3
- Package Manager: bun@1.0.2

### Reproduction

https://github.com/imcm7/nuxt-db

### Describe the bug

In example, if no dir `pages` or in that dir no files like `index.vue` when `property) title?: string | number | undefined`.
If I put in that dir file `index.vue` I have `Argument of type '{}' is not assignable to parameter of type 'string | number'`.

> Type 'unknown' is not assignable to type 'MaybeComputedRefOrPromise<MaybeArray<Stringable> | Promise<MaybeArray<Stringable> | null | undefined> | null | undefined>'.

> Argument of type '{}' is not assignable to parameter of type 'string | number'.

Pass the problem

```
declare module 'vue-router' {
    interface RouteMeta {
        title?: string | number;
    }
}
```

No effect 

```
declare module '#app' {
     interface PageMeta {
         title?: string | number;
     }

     interface RouteMeta {
         title?: string | number;
     }

}

export {};
``

**Comment by imcm7** [comment]
https://github.com/nuxt/nuxt/issues/23383

**Comment by imcm7** [comment]
May be is related https://github.com/nuxt/nuxt/issues/23488 ?

**Comment by danielroe** [comment]
the reproduction is unchanged from the last time you opened this issue, and removing the baseUrl you added fixes it just as before: https://github.com/nuxt/nuxt/issues/23383#issuecomment-1740407448.

**Comment by imcm7** [comment]
> the reproduction is unchanged from the last time you opened this issue, and removing the baseUrl you added fixes it just as before: [#23383 (comment)](https://github.com/nuxt/nuxt/issues/23383#issuecomment-1740407448).

@danielroe I try locally and not fix if index,vue page is added, only if no pages if fixed. that is what I want to say.

**Comment by danielroe** [comment]
Maybe I'm misunderstanding you. Could you update the repository and tell me exactly the steps to run to reproduce? 🙏

**Comment by imcm7** [comment]
@danielroe it is updated but i get 

```
 ERROR(vue-tsc)  Argument of type '{}' is not assignable to parameter of type 'string | number'.
 FILE  /home/michael/Desktop/nuxt-db-main/layouts/default.vue:61:20

    59 |
    60 |   const title = computed(() => $i18n.t('hello', {
  > 61 |     title: $i18n.t($route.meta.title ?? 'test'),
       |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    62 |   }));
    63 | </script>
    64 |

```

If I remove pages dir (or may be only index.vue) I get
```
 ERROR                                                                                                                                                   
[vue-tsc] Found 0 errors. Watching for file changes.
```

**Comment by danielroe** [comment]
To augment vue-router's metadata (e.g. `$route.meta`) you need to do:

```ts
declare module 'vue-router' {
    interface RouteMeta {
        title?: string | number;
    }
}
```

which for some reason you have commented out. When it is uncommented, it works fine.

**Comment by imcm7** [comment]
> To augment vue-router's metadata (e.g. `$route.meta`) you need to do:
> 
> ```ts
> declare module 'vue-router' {
>     interface RouteMeta {
>         title?: string | number;
>     }
> }
> ```
> 
> which for some reason you have commented out. When it is uncommented, it works fine.

I know, but some one say that 'declare module '#auth' is needed. And it work without `declare module 'vue-router'` only no pages.

If I add `declare module 'vue-router'` then no need for declare module '#auth'.

**Comment by danielroe** [comment]
The reason is that vue-router is not used if you do not have a `~/pages` directory.

**Comment by imcm7** [comment]
I also think that. Ok, both are needed.
