### ISSUE TITLE
types(typedPages): export `RouteNamedMap` / `RouteName`

### ISSUE THREAD

**Issue by OrbisK** [nuxt/nuxt#23507]
### Describe the feature

It would be nice to be able to access `RouteNamedMap` or `RouteName` => `keyof RouteNamedMap`.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by pragyamishra56** [comment]
could you assign me plz?

**Comment by OrbisK** [comment]
> could you assign me plz?

I guess you can just open a PR and link it to this issue :)

**Comment by ThEditor** [comment]
I am not really sure where to look for `RouteNamedMap`/`RouteName`?
The only thing I could find was `getRouteName` function, could I get some guidance on where to look?

**Comment by doganalper** [comment]
I have come up with a possible solution but I belive it should be handled on [unplugin-vue-router](https://github.com/posva/unplugin-vue-router) since these types are being created there. I will open a PR in this repo soon.

**Comment by danielroe** [comment]
I think it should be as simple as this:

<img width="911" alt="CleanShot 2023-11-16 at 22 08 50@2x" src="https://github.com/nuxt/nuxt/assets/28706372/c6623f1a-b68b-4d56-af46-884a3f517359">
