### ISSUE TITLE
version Nuxt 3 ,I found out about the problem that the NuxtLink to jump page is blank

### ISSUE THREAD

**Issue by watler-peng** [nuxt/nuxt#23518]
### Environment

{
  "name": "nuxt-app",
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/postcss8": "^1.1.3",
    "nuxt": "^3.7.4",
    "sass": "^1.61.0",
    "sass-loader": "^13.3.2",
    "typescript": "^5.2.2"
  },
  "dependencies": {
    "@vueuse/core": "^9.13.0",
    "@vueuse/nuxt": "^9.13.0"
  }
}

### Reproduction

{
  "name": "nuxt-app",
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/postcss8": "^1.1.3",
    "nuxt": "^3.7.4",
    "sass": "^1.61.0",
    "sass-loader": "^13.3.2",
    "typescript": "^5.2.2"
  },
  "dependencies": {
    "@vueuse/core": "^9.13.0",
    "@vueuse/nuxt": "^9.13.0"
  }
}

### Describe the bug

![image](https://github.com/nuxt/nuxt/assets/3732856/49b324b5-32a9-4f06-a431-61ac1fac4866)

My link jump opens to a blank page, and it will be normal after refreshing.

**Comment by huang-julien** [comment]
hi :wave: Can you provide a reproduction please ?

**Comment by watler-peng** [comment]
> 您能提供一个[复制品](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)吗？🙏
> 
> 更多信息

https://stackblitz.com/edit/github-3gmvbv?file=app.vue

**Comment by watler-peng** [comment]
> 你好👋你能提供一份复制品吗？

https://stackblitz.com/edit/github-3gmvbv?file=package.json

**Comment by warflash** [comment]
https://stackblitz.com/edit/github-3gmvbv-vbcffu?file=src%2Fpages%2Findex.vue,app.vue,src%2Fpages%2Farticle.vue
Pages only ever should have one root element (comments also count as root elements). Also I'd recommend using auto-imports or importing from `#imports` if you want to keep manual imports
