### ISSUE TITLE
Nuxt - Global middleware override and sort issue with layer

### ISSUE THREAD

**Issue by slarrasoain** [nuxt/nuxt#23513]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      extends
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-4ryqhc?file=pages%2Findex.vue

### Describe the bug

Global middleware order and override seems to be not in the logic layer way.
base layer middleware shoud be overriden by project middleware and sorting should be alpha of all layers.

From the repro 
Console should show 
    00-middleware base 
    05-middleware project 
    10-middleware project 
    20-middleware base 

But show
    00-middleware base 
    10-middleware bas >
    20-middleware base
    05-middleware project 

For me 10-middleware base shoud be overriden by 10-middleware project
AND 05-middleware project should be just after 00-middleware base
  
I have made a module to correct the middleware sort (juste rename base\__modules foledr to base\module )
But can't find how to solve the not overriden middleware.

**Comment by danielroe** [comment]
The ordering of middleware is intentional - see https://github.com/nuxt/nuxt/pull/22889#discussion_r1311504048 and https://github.com/nuxt/nuxt/pull/22925. You can adjust the middleware ordering as you are doing in a module or hook.

But indeed the global middleware should be overrideable; this is a bug that should be fixed.
