### ISSUE TITLE
"No match found for location" is logged at least 8 times

### ISSUE THREAD

**Issue by mkarras** [nuxt/nuxt#23539]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.12.1
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@8.19.2
- Builder:          -
- User Config:      modules, devtools
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.1
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-lip1ot?file=pages%2Findex.vue,error.vue,app.vue 

### Describe the bug

When a not existing route/path is opened, the warning `[Vue Router warn]: No match found for location with path "/not-existing"` is logged 8 times. In our project (with translated paths via @nuxtjs/i18n and i18n pages) it logs even move times.

1. click the link "Link to not available page" in the preview of stackblitz to navigate to a not existing route
2. reload the page in preview window
3. see server log that logs 8 times `[Vue Router warn]: No match found for location with path "/not-existing"`

### Additional context

Im investigating a memory leak at server side. And this is potentially part of the issue. It seems like that multiple instances of the router are created.

When using a native Vue application with separat installed vue-router package the warning is only logged once.

### Logs

`[Vue Router warn]: No match found for location with path "/not-existing"` x 8

**Comment by hakan-akgul** [comment]
Hello @mkarras  

We have faced with same issue  
About 5 days, we try to find root cause of the memory leak
Are you sure that is it related with i18n, we also have `"@nuxtjs/i18n": "^8.0.0-rc.5"`

**Comment by isikhi** [comment]
Same as here. 7 to 14 times you can see no match found for location error occured.
here is my package json:
```
    "@nuxt/devtools": "^1.0.0",
    "@nuxtjs/stylelint-module": "^5.1.0",
    "@pinia-plugin-persistedstate/nuxt": "^1.1.2",
    "@pinia/nuxt": "^0.5.1",
    "@types/vue-tel-input": "^2.1.5",
    "@unocss/eslint-config": "^0.56.5",
    "@unocss/nuxt": "^0.56.5",
    "@vue/devtools": "^6.5.1",
    "@vueuse/nuxt": "^10.5.0",
    "eslint": "^8.51.0",
    "husky": "^8.0.3",
    "nuxt": "^3.7.4",
    "nuxt-schema-org": "^2.1.3",
    "nuxt-simple-sitemap": "^2.6.1",
    "nuxt-typed-router": "^3.3.1",
    "nuxt-unhead": "^1.4.20",
    "pino-pretty": "^10.2.3",
    "stylelint": "^15.11.0",
    "stylelint-config-recommended-vue": "^1.5.0",
    "stylelint-config-standard": "^34.0.0",
    "typescript": "^5.2.2",
    "vite-plugin-stylelint": "^5.1.1"
```

**Comment by hakan-akgul** [comment]
Hi

The memory leak problem solved after uninstall `@nuxtjs/i18n v8.0.0-rc.5`

Hope it helps

**Comment by designchapnl** [comment]
I've got this issue too. It's logging a router issue consisting of 2 urls from the app.config and this is chained (partly) 4-6 times. I really don't get it where this url chain is getting generated.
These 2 urls are inside a v-for with a NuxtLink.

Packages:
```javascript
"@fortawesome/fontawesome-svg-core": "^6.4.0",
"@fortawesome/free-brands-svg-icons": "^6.4.0",
"@fortawesome/pro-light-svg-icons": "^6.2.1",
"@fortawesome/pro-regular-svg-icons": "^6.4.0",
"@fortawesome/pro-solid-svg-icons": "^6.2.1",
"@fortawesome/vue-fontawesome": "^3.0.3",
"@nuxt/devtools": "^1.0.0",
"@nuxt/image": "^1.0.0",
"@nuxtjs/google-fonts": "^3.0.1",
"@nuxtjs/tailwindcss": "^6.6.5",
"@vite-pwa/nuxt": "^0.3.3",
"gsap": "^3.12.2",
"nuxt": "^3.3.3",
"nuxt-gtag": "^1.1.1",
"nuxt-og-image": "^2.1.3"
``` 
The urls are stored like this:
```javascript
[
      {
        name: 'LinkedIn',
        url: 'www.linkedin.com/in/butteruitvaartservice',
        icon: 'linkedin-in'
      },
      {
        name: 'Facebook',
        url: 'www.facebook.com/Butter-Uitvaartservice-Post-Mortem-Support-108482781491035',
        icon: 'facebook-f'
      }
]
``` 

The log message looks like this:
```
Dec 4, 10:54:34 AM: 6e9025da WARN   [Vue Router warn]: No match found for location with path "/www.facebook.com/www.facebook.com/www.facebook.com/www.facebook.com/www.facebook.com/www.linkedin.com/in/butteruitvaartservice/www.facebook.com/www.linkedin.com/in/butteruitvaartservice/www.facebook.com/www.linkedin.com/in/butteruitvaartservice/www.linkedin.com/in/butteruitvaartservice/www.facebook.com/www.facebook.com/www.linkedin.com/in/butteruitvaartservice/www.linkedin.com/in/butteruitvaartservice/www.facebook.com/www.linkedin.com/in/butteruitvaartservice/www.linkedin.com/in/butteruitvaartservice/www.facebook.com/Butter-Uitvaartservice-Post-Mortem-Support-108482781491035"
```

**Comment by manniL** [comment]
@designchapnl prefixing the URLs with a protocol (`https://` or even just `//`) should make it work. Otherwise, marking the link as `external` via the prop of `NuxtLink` is an option too.

**Comment by designchapnl** [comment]
I have it like so:
```javascript
:to="`https://${item.url}`"
``` 

I've also got another codeblock which loops through some other urls, that doesn't give this warning. So I don't get it what's going on here.

**Comment by sun-ergo-s** [comment]
Facing a similar problem. When accessing non-existing URL, it takes longer time to be redirected to 404 error page and also logs for the wrong URL is repeated 8 times. We're not using `@nuxtjs/i18n`.

**Comment by heng1025** [comment]
> Facing a similar problem. When accessing non-existing URL, it takes longer time to be redirected to 404 error page and also logs for the wrong URL is repeated 8 times. We're not using `@nuxtjs/i18n`.

same issue

**Comment by mkarras** [comment]
I still get multiple logs in latest Nuxt versions like 3.11.1 @danielroe

**Comment by mkarras** [comment]
@sun-ergo-s already did it @danielroe with https://github.com/nuxt/nuxt/issues/26425 🙂
