### ISSUE TITLE
Cannot start nuxt:  Cannot read properties of undefined (reading 'nuxt')

### ISSUE THREAD

**Issue by cdwmhcc** [nuxt/nuxt#23530]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.17.1
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  pnpm@8.7.6
- Builder:          -
- User Config:      app, runtimeConfig, imports, css, components, alias, modules, googleFonts, colorMode, buildDir, hooks
- Runtime Modules:  @nuxtjs/color-mode@3.3.0, @pinia/nuxt@0.4.11, nuxt-lodash@2.5.0, @/modules/google-fonts/module
- Build Modules:    -
------------------------------

### Reproduction

nuxt.config.ts

``` ts
import fs from 'node:fs'
import path from 'node:path'

export default defineNuxtConfig({
  app: {
    buildAssetsDir: `_test/`,
  },
  buildDir: `.test`,
  hooks: {
    build: {
      done(builder:any) {
        const extraFilePath = path.join( builder.nuxt.options.buildDir )
        console.log(extraFilePath)
      }
    }
  }
})

```

run `pnpm build` or `pnpm generate`

### Describe the bug

1. failed to resolve "extends":"./.nuxt/tsconfig.json"
2. ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'nuxt')

**Comment by huang-julien** [comment]
hi :wave:
Do you mean 
```ts

export default defineNuxtConfig({

  hooks: {
    "build:done": () => {
      // code here
    }
  }
})

``` 
? 
You can take a look at nuxt's lifecycle hooks [here](https://nuxt.com/docs/api/advanced/hooks) . We're using hookable so the `hooks` property in the config is a pair of key(hook name)/callback

**Comment by huang-julien** [comment]
By default the buildDir is `.nuxt` so if you change it to `.test`, the auto-generated config will be at `.test/tsconfig.json`. 
You have a `tsconfig.json` at the root of your project. Try to change it to 
```json
{
  "extends": "./.test/tsconfig.json"
}
```

**Comment by danielroe** [comment]
`build:done` does not receive any argument in Nuxt 3; that is why you are getting this error, because you are trying to access `builder.nuxt`.
