### ISSUE TITLE
NuxtData caching built into useAsyncData

### ISSUE THREAD

**Issue by willempie96** [nuxt/nuxt#23540]
### Describe the feature

I thought this was already the case in useAsyncData but after some issues in my project and finding this issue (https://github.com/nuxt/nuxt/issues/22622) it is clear this is not the case yet.

It would be great if we would have an option to integrate caching using useNuxtData in the useAsyncData itself. 
I have been able to implement this myself with a workaround like:

``
useAsyncData(`page-${id}`, async () => {
  const { data: cachedPage } = useNuxtData(`page-${id}`);
    return (
      cachedPage.value || (await getPage(id))
    );
})
``

Which works great, it's just a bit less clean.
The only issue is that if you would want to use the default refresh function provided by the useAsyncData composable this would not really refresh but just use the cache.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
This should now be possible in https://github.com/nuxt/nuxt/pull/20747.

**Comment by Hebilicious** [comment]
> This should now be possible in #20747.

Maybe we could add an example here ? https://nuxt.com/docs/api/composables/use-async-data

**Comment by danielroe** [comment]
Great idea! 🙏❤️

**Comment by mrc-bsllt** [comment]
Is there any news regarding this?
Why does getCachedData not appear among the available options?
I have already updated the latest version of Nuxt to 3.8.0, thanks!
<img width="881" alt="Screenshot 2023-10-27 alle 11 37 43" src="https://github.com/nuxt/nuxt/assets/72490444/639823de-53af-4a0f-8c51-a38a1566c364">

**Comment by mrc-bsllt** [comment]
Resolved. I had to update vue-tsc.
