### ISSUE TITLE
Node 18+ useFetch is not working in SSR

### ISSUE THREAD

**Issue by dany68** [nuxt/nuxt#23558]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.18.0
- Nuxt Version:     3.7.3
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@9.8.1
- Builder:          -
- User Config:      devtools, modules, css, postcss, build, googleFonts, phosphor, vue, runtimeConfig
- Runtime Modules:  @nuxtjs/google-fonts@3.0.2, nuxt-phosphor-icons@1.0.7, @pinia/nuxt@0.4.11, @pinia-plugin-persistedstate/nuxt@1.1.2, nuxt-og-image@2.0.28
- Build Modules:    -
------------------------------

### Reproduction

Fresh nuxt 3 application with SSR and node 18+.

### Describe the bug

Hi,
There are several posts online and I still didn't find a proper solution yet.
After upgrading from node 16 to 18 the useFetch function doesn't work on SSR and returns an error 500 on page load/refresh. This is apparently due to the way the ofetch library work with node 18+.

The only solution that works is to disable SSR which remove the main benefit of using nuxt as i need SEO.

Did anyone find a fix ? How can i fetch data and keep SSR while using node 18 ?

Thank you for your help,
Daniel

**Comment by Botz** [comment]
We have the same problem.

In our project the Problem occurs with nitro api routes and only if swr/cache is enabled.

I wasn't able to get a reproduction with a new nuxt3 project.

But i have found this issue here: https://github.com/node-fetch/node-fetch/issues/1624
And if i change `useFetch('/api/someRoute')` to `useFetch('http://127.0.0.1:8080/api/someRoute')` and now it works.

**Comment by danielroe** [comment]
I would very happily look into this in more detail with a reproduction, but for now I will need to close it. I'm not aware of any issue with `useFetch` or `$fetch`, though it sounds like possibly you should investigate node issues or changes in network requests with protocol/host.
