### ISSUE TITLE
Unable to properly monitor the close event of page request

### ISSUE THREAD

**Issue by amihhs** [nuxt/nuxt#23569]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.17.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://codesandbox.io/p/sandbox/stoic-sanderson-y6wjgg

### Describe the bug

When I want to request a page, when the page is not completed on the server side and the user stops the request for the page (such as closing the browser tab/clicking to stop loading), I want to do some additional processing.
Like a request to stop the api interface; but it seems that the close event cannot be correctly monitored.

It can only listen to the close event triggered after the normal end event.

**Comment by danielroe** [comment]
Would you raise a feature request in https://github.com/unjs/nitro, for discussion?

**Comment by amihhs** [comment]
yeah, let's discuss it here https://github.com/unjs/nitro/issues/1810
