### ISSUE TITLE
NuxtLoadingIndicator stopped working

### ISSUE THREAD

**Issue by acidjazz** [nuxt/nuxt#23568]
### Environment

multiple environments

### Reproduction

https://stackblitz.com/edit/github-ni6a1j?file=app.vue

### Describe the bug

Not sure if this was deprecated?

**Comment by acidjazz** [comment]
From more debugging it looks like the opacity stays 0 the whole time

**Comment by huang-julien** [comment]
Hello :wave:, NuxtLoadingIndicator doesn't use `page:start` hook to work, instead it uses a globalMiddleware to start

**Comment by acidjazz** [comment]
> Hello 👋, NuxtLoadingIndicator doesn't use `page:start` hook to work, instead it uses a globalMiddleware to start

Actually you can see it firing off when using `page:start` , you can see me use it here with an example: https://github.com/nuxt/nuxt/issues/15232

This worked fine w/ all of my projects and now suddenly stopped working

**Comment by huang-julien** [comment]
I see, this [PR ](https://github.com/nuxt/nuxt/pull/21003) (for 3.6) changed the behavior of `NuxtLoadingIndicator`. I will take a look at #15232 (currently busy but asap)

**Comment by acidjazz** [comment]
> I see, this [PR ](https://github.com/nuxt/nuxt/pull/21003) (for 3.6) changed the behavior of `NuxtLoadingIndicator`. I will take a look at #15232 (currently busy but asap)

Thank you, until then do you mind re-opening this?

**Comment by acidjazz** [comment]
Any progress on this? I would like to see the progress indicator back in action on all of my projects

**Comment by huang-julien** [comment]
yes, will be working on it
