### ISSUE TITLE
After some hours of development nuxt eat 1 Gb memory

### ISSUE THREAD

**Issue by imcm7** [nuxt/nuxt#23566]
### Environment

Nuxt 3
Linux

### Reproduction

https://ibb.co/bN1gWp7

### Describe the bug

After some hours of development nuxt eat 1 Gb memory and my computer freeze.
In product will be the same?

**Comment by danielroe** [comment]
No, development environment is always different. Any memory leaks in vite/nitro/nuxt dev servers will be happily investigated if you can provide a reproduction, but merely having a high memory usage doesn't indicate a leak.
