### ISSUE TITLE
Fix Global Style Imports documentation

### ISSUE THREAD

**Issue by jamesabell** [nuxt/nuxt#23567]
### Environment

N/A

**Please refer me to the proper place to report documentation issues if this isnt right**

### Reproduction

N/A

### Describe the bug

https://nuxt.com/docs/getting-started/assets#global-styles-imports

Example "In your nuxt.config"

```
export default defineNuxtConfig({
  vite: {
    css: {
      preprocessorOptions: {
        scss: {
          additionalData: '@use "@/assets/_colors.scss" as *;'
        }
      }
    }
  }
})
```

vite is not a valid option. The docs are either out of date, or the installed version linked me to the wrong documentation. Seems like the former.

**Comment by warflash** [comment]
The vite options and scss seem to work fine for me, drafted a quick example of here: https://stackblitz.com/edit/github-l6v7qt?file=nuxt.config.ts,assets%2F_colors.scss,app.vue
