### ISSUE TITLE
Hydration node mismatch

### ISSUE THREAD

**Issue by dextersiah** [nuxt/nuxt#23572]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.15.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  bun@1.0.4
- Builder:          -
- User Config:      colorMode, devtools, experimental, typescript, modules, css, ui, runtimeConfig
- Runtime Modules:  @pinia/nuxt@0.4.11, @nuxt/ui@2.9.0, nuxt-security@0.14.4
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-dgvnv6-s4j4zq?file=pages%2Findex.vue

### Describe the bug

A simple use of `useFetch` and `v-if` inside the template is returning a Hydration node mismatch. 

### Logs

```shell-script
[Vue warn]: Hydration node mismatch:
- Client vnode: Symbol("v-cmt") 
- Server rendered DOM: 
<div> <empty string> 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouteProvider key="/" vnode= 
Object { __v_isVNode: true, __v_skip: true, type: {…}, props: {…}, key: null, ref: {…}, scopeId: null, slotScopeIds: null, children: null, component: null, … }
 route= 
Object { fullPath: "/", hash: "", query: {}, name: "index", path: "/", params: {}, matched: (1) […], meta: Proxy, redirectedFrom: undefined, href: "/" }
  ... > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <App key=3 > 
  at <NuxtRoot>
```

**Comment by manniL** [comment]
If you wrap your page content in a div there shouldn't be a mismatch. Also you can omit `.value` in the template.

```vue
<template>
  <div>
    <div v-if="!fetchData.pending">content</div>
  </div>
</template>
```
