### ISSUE TITLE
[Server Components] `<template>` doesn't work

### ISSUE THREAD

**Issue by madebyfabian** [nuxt/nuxt#23575]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools, experimental
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-cykanv?file=app.vue,components%2FExample.server.vue

### Describe the bug

When creating components with `.server.vue`, currently, they cannot include any `<template>` tags. Because they are simply sent to the browser, which renders a real `<template>` in the DOM.
![Bildschirmfoto 2023-10-08 um 17 54 32](https://github.com/nuxt/nuxt/assets/32813692/e6179b89-c419-4c87-ab8d-83b784ebbdf0)

Not sure if this is intentional, or not solvable. I know that the component doesn't get hydrated on the client, but I thought the process of replacing `<template>` with html comments would already happen on the server.

**Comment by huang-julien** [comment]
Hey hey :wave:

I think using `<template>` within normal components without any directive will lead to hydration issues. 
Isn't this also the case with normal components ? I'm not sure in which case would we use `<template>` without any directive

**Comment by HigherOrderLogic** [comment]
https://github.com/vuejs/core/issues/7285 seems to be related.

**Comment by madebyfabian** [comment]
@huang-julien Hey there! You're right. I updated the reproduction, adding a `v-if="true"` and now it works. Using `template` without any directive also causes hydration issues for regular components.

So I guess this issue can be closed.
