### ISSUE TITLE
Nuxt 3 page cache - unable to manually control page key naming

### ISSUE THREAD

**Issue by mkierdev** [nuxt/nuxt#23587]
### Environment

Nuxt 3.7

### Reproduction

Use built-in Nitro cache and enable it for pages.

```js
export default defineNuxtConfig({
  routeRules: {
    '/': { swr: 3600 }, 
  }
})
```

### Describe the bug

Naming for cached page is not straightforward. It seems that is is using a hashing function. For example, here is the key for index.vue page: _nitro:routes:_:.il7asoJjJE.json_.

It should be possible to control this behavior / manually overwrite it.

Use-case: We would like to control whether or not we should store urlParams inside key.

**Comment by danielroe** [comment]
Would you raise this upstream in https://github.com/unjs/nitro instead? 🙏

**Comment by mkierdev** [comment]
Upstream: https://github.com/unjs/nitro/issues/1814
