### ISSUE TITLE
Nuxt 3 - Can't modify Route Rules dynamically (manually register middleware?) [cache]

### ISSUE THREAD

**Issue by mkierdev** [nuxt/nuxt#23585]
### Environment

Nuxt 3.7

### Reproduction

From docs:

Nuxt 3 includes route rules and hybrid rendering support. Using route rules you can define rules for a group of nuxt routes, change rendering mode or assign a cache strategy based on route!

**Nuxt server will automatically register corresponding middleware and wrap routes with cache handlers using [Nitro caching layer](https://nitro.unjs.io/guide/cache).**

```js
export default defineNuxtConfig({
  routeRules: {
    '/': { prerender: true },  // Homepage pre-rendered at build time
    '/products/**': { swr: 3600 }, // Product page generated on-demand, revalidates in background
  }
})
```

and implementation in nuxt with custom storage:
```js
 nitro: {
    storage: {
      cache: {
        driver: "~/storage-client",
      },
    },
    routeRules: {
      "/": { cache: { maxAge: 60 * 60 } },
    },
```

### Describe the bug

Use-case:
We are caching whole pages but we should have control whether or not we should serve cached page response to the end user. For example we want to serve cached pages by default, however if user is logged in into an app, pages should always bypass cache.

_This behavior is possible for cached requests with the use of shouldInvalidateCache / shouldBypassCache, but these options are exposed only for cachedEventHandler and cachedFunction._

However, if we define routeRules in nuxt.config.ts, we are unable to make any modifications for each user.

Nuxt docs are saying that _Nuxt server will automatically register corresponding middleware and wrap routes with cache handlers using [Nitro caching layer._. Maybe it's possible to create this kind of middleware by ourselves? Is there any template that we could use for this purpose?

### Additional context

We are using custom driver for cache (from unstorage template) where we connect to external cache DB. 
We use getItem() and setItem() functions.

getItem(key, _opts) has only key and _opts and we do not seem to find any way to bypass cache in here. If we could read cookies here it would probably be enough, but we can't reach them there. There is no option to capture user request headers here as well.

### References
https://nuxt.com/docs/guide/concepts/rendering#hybrid-rendering
https://nitro.unjs.io/guide/cache
https://unstorage.unjs.io/custom-driver

**Comment by danielroe** [comment]
Would you raise this upstream in https://github.com/unjs/nitro instead? 🙏

**Comment by mkierdev** [comment]
Upstream: https://github.com/unjs/nitro/issues/1815
