### ISSUE TITLE
vue router doesn't map /public routes during SSR

### ISSUE THREAD

**Issue by ilanc** [nuxt/nuxt#23589]
### Environment

Nuxt project info:                                                                                                                                                     15:27:50

------------------------------
- Operating System: Linux
- Node Version:     v18.12.1
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/github/ilanc/nuxt-bug-fetch-public-json

### Describe the bug

`/public` routes can be accessed client-side but not from server-side code

## Repro

In the above demo there are 2 pages: `/` and `/b`. The pages are identical: both use `$fetch` to retrieve `/temp.json`. However `/` only fetches client-side i.e.:

```ts
if (process.client) {
  data = await $fetch("/temp.json", { headers });
  console.log(JSON.stringify(data, null, 2));
}
```
whereas `/b` fetches on both client and server-side:

```ts
let data = await $fetch("/temp.json", { headers });
console.log(JSON.stringify(data, null, 2));
```

## Result

- `/b` loads when you navigate to the route from the clientside (e.g. click `b` in the top nav)
- `/b` returns a `404 /temp.json not found` when you reload (and hence server-side rendering code attempts to execute the fetch)

## Note
- `/` can render clientside or serverside - note however you get hydration mismatches (this is not the bug you are looking for) 

### Additional context

You can workaround this by adding `/server/routes` but I'm guessing that this is a bug not a feature

**Comment by ilanc** [comment]
@danielroe should I re-post this issue on nitro or another issue tracker?

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/13857
