### ISSUE TITLE
Nuxt 3 - Hydration mismatch error is not shown if the mismatch is caused by an Async Component

### ISSUE THREAD

**Issue by RodrigoProjects** [nuxt/nuxt#23590]
### Environment

Any

### Reproduction

https://stackblitz.com/edit/github-iuwbtr?file=package.json,components%2FHydrationMismatch.vue,app.vue

### Describe the bug

This may be an upstream issue with Vue (almost 100% certain) but I would like to know your opinion on a workaround or possible fix: 

 - The issue consists in not displaying "Hydration completed but contains mismatches" (in DEV and PRD envs) when we use an Async Component with a Mismatch. This is a severe issue for websites that serve milions of pages and have a mismatch but it is silent to our logs/obervability tooling.
 
 After some investigation it seems that when we use an Async Component the hydration is somewhat defered and at the moment of showing the `console.error("Hydration completed but contains mismatches")` the code that hydrates (or checks for possible mismatches) the mismatch component did not run yet.
 
 After some debugging: 
 
![image](https://github.com/nuxt/nuxt/assets/47485736/172d61ff-4b62-473c-b9d2-3a13a6fff909)

We see the hydrate function being called with the `nuxt-root` component in the first breakpoint. After that:

![image](https://github.com/nuxt/nuxt/assets/47485736/0b626a70-530a-4944-b8f8-de88ae1ab68c)

The `hasMismatch` flag continues to be `false`. I did put one more breakpoint at the `handleMismatch` function that is only called after already already running the `hydrate` function that has the `console.error()`:

![image](https://github.com/nuxt/nuxt/assets/47485736/00b0cf4f-b3d8-4fdc-bc49-8984ae53b474)

This function was called with the vnode where I have the mismatch but it's already to late for the `console.error()` because it already ran with the `hasMismatch` being false.

Any more information just ask, I will be happy to provide!

About the reproduction, you can comment and uncomment the import statements in `app.vue` and see the different behaviours :)

**Comment by huang-julien** [comment]
hi :wave: that's because you're using `ref(new Date().toISOString())`

It doesn't get the same value server-side and client side. Hydration is the process of instanciating an app over ssr rendered HTML. 
So your component is rendered twice. Once server side, once client-side.

You can use a `useState` instead.

**Comment by RodrigoProjects** [comment]
Hello @Julien Huang! The problem there is not the mismatch itself I know it has a mismatch and I want the mismatch to happen. The console.error("Hydration mismatch... ") does not happen when I use an asyncComponent vs using a normal import, please consider reopening :)

**Comment by huang-julien** [comment]
![image](https://github.com/nuxt/nuxt/assets/63512348/fa3ea808-ea90-4d2b-a2e1-280493d2662c)
![image](https://github.com/nuxt/nuxt/assets/63512348/a88705da-fa5e-4cf7-8c4d-6d6a51f1f6a5)

I see, this should be opened in `vue/core` then

**Comment by RodrigoProjects** [comment]
I thought so! Thank you very much for your time! And sorry if my explanation was not the best :P

**Comment by huang-julien** [comment]
Thank you for reporting it :) my bad i read the description too fast :joy:

**Comment by andufox** [comment]
ClientOnly surround the tag, solve my problem.

**Comment by mendmania** [comment]
> ClientOnly surround the tag, solve my problem.

this is not a solution

**Comment by RodrigoProjects** [comment]
This issue is fixed in the last Vue version!

**Comment by amandesai01** [comment]
> ClientOnly surround the tag, solve my problem.

This defeats entire purpose of SSR

**Comment by Easynone** [comment]
I need to use <a href> instead of NuxtLink because NuxtLink causes the page to remount, which makes my fetch requests visible in the browser's network tab. When I use the <a> tag, it becomes fully SSR-compatible and my fetch requests are hidden. However, using <a> gives a "Hydration completed but contains mismatches" error in Nuxt.js.
