### ISSUE TITLE
`nuxt dev` command does not use the base URL set in `nuxt.config.ts`

### ISSUE THREAD

**Issue by Lehoczky** [nuxt/nuxt#23598]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools, app
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-jnqsth

### Describe the bug

The CLI output no longer uses the `app.baseURL` from the config when running the dev command. Opening the URL which has been logged by the cli will result in a 404 page:

![image](https://github.com/nuxt/nuxt/assets/31937175/e0881b8f-a031-40b4-b638-7aad691e9361)

Same when using the `--open` flag.

Versions before 3.7 did not have this issue:

![image](https://github.com/nuxt/nuxt/assets/31937175/6063b905-5322-4ffb-a737-1b6824c7300d)

**Comment by warflash** [comment]
Thanks! This has been fixed in the CLI and should be available in the next release of the CLI -> https://github.com/nuxt/cli/issues/235
