### ISSUE TITLE
Path alias do not work with v-bind

### ISSUE THREAD

**Issue by mbledkowski** [nuxt/nuxt#23606]
### Environment

Nuxt CLI v3.0.0-rc.6
RootDir: /home/mble/Code/repos/mbledkowski/mble.dk
Nuxt project info: 

------------------------------
- Operating System: `Linux`
- Node Version:     `v20.5.1`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `css`, `build`, `app`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

```vue
<img src="~/assets/icons/x.webp" />
```
works fine.
```vue
<img :src="`~/assets/icons/${item}`" />
```
does not work at all.

### Describe the bug

I am trying to use path alias in v-bind-ed property, but I am not able to. I searched for a solution to this problem, but I cannot find one, although it seems that method with "require" in Nuxt2 was the solution. I am using Nuxt3, so this do not work for me.

### Logs
```console
[Vue Router warn]: No match found for location with path "/~/assets/icons/apps/affinity_designer.webp"
```

**Comment by warflash** [comment]
See -> https://github.com/nuxt/nuxt/issues/14766

**Comment by mbledkowski** [comment]
> See -> #14766 (Sidenode: I'd recommend upgrading your nuxt version if you're actually still on rc6)

I started that project when Nuxt was still in beta. Going to upgrade when I end it.
