### ISSUE TITLE
`typeCheck` reports errors from modules when using `tsconfig` rules

### ISSUE THREAD

**Issue by cmcnicholas** [nuxt/nuxt#23609]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools, modules, typescript
- Runtime Modules:  @nuxtseo/module@2.0.0-beta.15
- Build Modules:    -
------------------------------

### Reproduction

- minimal changes to nuxt config adding `typeCheck: true` and `compilerOptions.noUncheckedIndexedAccess: true`

https://stackblitz.com/edit/github-vdxk2t?file=nuxt.config.ts

### Describe the bug

This highlights an issue when trying to use tsconfig features e.g. `noUncheckedIndexedAccess` or `noUnusedLocals` etc. in a nuxt project to provide stricter code conformance. Any nuxt module you have installed will also be checked for these same rules.

This effectively means you cannot use any of the tsconfig rules for the risk of a module developer not adhering to those same standards.

Nuxt should not be type checking any installed modules as part of build with the same tsconfig rules defined at the project level. Providing access to all tsconfig properties is misleading as they effectively don't work with the nuxt ecosystem unless you have a raw project.

The repro and logs below show how this fails for the `@nuxtseo/module` module but this error is present in a number of modules I have tried to use e.g. `content`

### Logs

```shell-script
ERROR                                                                                                                                                                 21:54:09
 ERROR(vue-tsc)  Type '{ icon: string; label: false; ariaLabel: string | undefined; current?: boolean | undefined; disabled?: boolean | undefined; to?: string | undefined; separator?: string | undefined; hideSeparator?: boolean | undefined; ui?: { ...; } | undefined; }' is not assignable to type 'BreadcrumbItemProps'.
  Types of property 'to' are incompatible.
    Type 'string | undefined' is not assignable to type 'string'.
      Type 'undefined' is not assignable to type 'string'.
 FILE  /home/projects/github-vdxk2t/node_modules/nuxt-seo-ui/dist/runtime/components/Breadcrumb.vue:46:5

    44 |   }
    45 |   if (props.homeIcon) {
  > 46 |     items[0] = {
       |     ^^^^^^^^
    47 |       ...items[0],
    48 |       icon: 'material-symbols:home-outline-rounded',
    49 |       label: false,

[vue-tsc] Found 1 error. Watching for file changes. (x3)
```
```

**Comment by danielroe** [comment]
This is tricky. I _think_ we need to include runtime components here in our TS project in order to benefit from prop typing, for example, and we explicitly add them to the context here: https://github.com/nuxt/nuxt/pull/23240.

**Comment by danielroe** [comment]
Closing to track in #22421.

**Comment by LouisMazel** [comment]
I currently have this issue with a pnpm dependency

```bash
../../../node_modules/.pnpm/****@3.29.2_nuxt@3.8.2_typescript@5.3.2_vue@3.3.8/node_modules/maz-ui/tailwindcss/utils/colors.ts:11:7 - error TS7053: Element implicitly has an 'any' type because expression of type 'string | number' can't be used to index type '{}'.
  No index signature with a parameter of type 'string' was found on type '{}'.

11       colorVariations[variation] =
         ~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors in the same file, starting at: ../../../node_modules/.pnpm/****@3.29.2_nuxt@3.8.2_typescript@5.3.2_vue@3.3.8/node_modules/****/tailwindcss/utils/colors.ts:10
```

Is it not possible to add the possibility of adding `--skipLibCheck` of `vue-tsc`?

Thanks

**Comment by danielroe** [comment]
You can directly run `pnpm vue-tsc --noEmit --skipLibCheck` if needed.
