### ISSUE TITLE
Argument of type '{ devtools: { enabled: boolean; }; runtimeConfig: { abc: string; }; }' is not assignable to parameter of type 'InputConfig<NuxtConfig, ConfigLayerMeta>'

### ISSUE THREAD

**Issue by gustawdaniel** [nuxt/nuxt#23603]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.6.1
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  bun@1.0.0
- Builder:          -
- User Config:      devtools, runtimeConfig
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

add in the Nuxt config

```
export default defineNuxtConfig({
    devtools: {enabled: true},
    runtimeConfig: {
        abc: ''
    }
})
```

in pure vue project created by

```
npx nuxi init my-project
```

### Describe the bug

![Zrzut ekranu z 2023-10-10 19-41-31](https://github.com/nuxt/nuxt/assets/16663028/defe50d3-fd5d-458d-b2ca-9838f5a09a7f)

In Webstorm I see problems with a typescript like this:

> TS2345: Argument of type '{ devtools: { enabled: boolean; }; runtimeConfig: { twilioAccountSid: string; }; }' is not assignable to parameter of type 'InputConfig<NuxtConfig, ConfigLayerMeta>'.   Object literal may only specify known properties, and 'runtimeConfig' does not exist in type 'InputConfig<NuxtConfig, ConfigLayerMeta>'.Webstorm

### Additional context

this code works, but my issue is about typescript warnings in the IDE

docs with presented syntax https://nuxt.com/docs/guide/going-further/runtime-config

**Comment by danielroe** [comment]
Would you check you are using the most recent version of Webstorm?

**Comment by gustawdaniel** [comment]
I was using Nuxt Plugin 2.0.2, now updated to 2.0.6 - this does not help
Webstorm 2023.1, now updated to 2023.2.2 and this **helped**.

Now after updating to the latest webstorm, it works. Thanks.
