### ISSUE TITLE
handle chunk loading errors that are not triggered by navigation

### ISSUE THREAD

**Issue by nandi95** [nuxt/nuxt#23612]
### Describe the feature

When a chunk has been given a new name during build as it has changed, some clients will try to load the old chunk name. This results in errors like:
- `TypeError: error loading dynamically imported module:  ....`
- `Importing a module script failed.`
- `Failed to fetch dynamically imported module: ...`

With pages this issue gets detected, and the page reloaded which is necessary.
https://github.com/nuxt/nuxt/blob/24c5af328f94bb3cba26121530406ee5ac124dfe/packages/nuxt/src/app/plugins/chunk-reload.client.ts#L21
However, when I other lazy components that aren't pages, they might fail the same way, but there's have no strategy in place for them, nor can I safely tell the page and another lazy component error apart.

Solutions:

1. Don't emit app:chunkError for pages as this issue is handled and there's nothing further to be done (This counts as a breaking change, I take it). This would mean the user is free to implement their own error handling strategy.
2.  Perhaps force reload the manifest file and attempt to load the chunk again.
3. Weave in an argument to the app:chunkError hook that signifies that the chunk is a page or not.

I don't think it would be wise to refresh the page on any and all chunk errors (as a lazy component might not be too critical and it's more important to have a smooth ux).

If nuxt cannot resolve this issue universally, perhaps we could come up with a strategy and some documentation to include in the docs.

Original Issue for this feature: https://github.com/nuxt/nuxt/issues/14594#issuecomment-1757162054

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Currently you can set `experimental.emitRouteChunkError` to `manual` which will call the `app:chunkError` hook but not handle it at all, which means you can experiment with your own plugin to handle it.

**Comment by quroom** [comment]
I get the same error ``` TypeError: Failed to import a dynamically imported module: '``` but it is not a related app:chunkError. it catched app:error.
I don't know the reason.

It happens when I click the login button in sidebase/nuxt-auth and then press the back button in window browser, sometimes I get a normal page but sometimes I get the error.

I am using nuxt for product level service.
Is there only solution makding refresh button and clicking it by user manually?
And does it happen in product?

I didn't deploy yet but I would like to know and prevent it.

**Comment by quroom** [comment]
As you said, I set but chunk error not catched. So I made own my error catch plugin.

```
plugins/error-handler.ts

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.hook("app:error", (error, instance, info) => {
    const reoload_error_list = [
      "error loading dynamically imported module",
      "Importing a module script failed",
      "Failed to fetch dynamically imported module",
    ];
    for (const message of reoload_error_list) {
      if (error.message.indexOf(message) > -1) {
        console.log(message);
        window.location.reload();
      }
    }
  });
});
```
It's not real solution but temprory it could help page working  properly without  all the time manual refresh

**Comment by tomsdob** [comment]
@quroom, do you still use the workaround you provided here and did it solve your issue? I am facing the same issue and I am looking for a fix.

**Comment by quroom** [comment]
> @quroom, do you still use the workaround you provided here and did it solve your issue? I am facing the same issue and I am looking for a fix.

Yeah. I am using that code still. I haven't seen that chunk error until now after including code that I mentioned.

**Comment by AlejandroAkbal** [comment]
Having this issue too :(

**Comment by gregmsanderson** [comment]
I too found that a lazy-loaded component would not cause any error and would just silently fail without a retry.

I found that the "app:error" hook suggested by @quroom  would not fire.

_Instead_ the "app:chunkError" hook is needed. essentially replacing the name of the hook in the code above. That hook is not documented on https://nuxt.com/docs/api/advanced/hooks#app-hooks-runtime but (as that page suggests) it _is_ in the code: https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/app/nuxt.ts#L48 and so does work when combined with https://nuxt.com/docs/guide/going-further/experimental-features#emitroutechunkerror.

The app then _does_ reload.

However the code above could result in infinite reloads on a network issue (can simulate by simply deleting a chunk) and so I would guess  it needs an "attempts" counter in sessionStorage/localStorage and then give up. I assume (?) Nuxt's handler is smart enough to avoid infinite retries. We could look how it does that.

**Comment by maximatically** [comment]
By the way, are there any other/new fixes available because none oof the provided solutions helped me fix the error.

**Comment by maximatically** [comment]
> @maximatically I don't believe the issue itself is fixed, however building on the above example the infinite-reload could perhaps be solved by using Nuxt's own function `reloadNuxtApp()`.
> 
> From https://nuxt.com/docs/api/utils/reload-nuxt-app it looks like if/when that's called _again_ within its default time of 10s, that will be ignored.
> 
> Something like:
> 
> ```js
> export default defineNuxtPlugin((nuxtApp) => {
>   nuxtApp.hook("app:chunkError", (err) => {
>     const error_list = [
>       "error loading dynamically imported module",
>       "Importing a module script failed",
>       "Failed to fetch dynamically imported module",
>     ];
>     for (const message of error_list) {
>       if (message.indexOf(message) > -1) {
>         console.error("app:chunkError reloading ...");
> 
>         reloadNuxtApp();
>       }
>     }
>   });
> });
> ```

Sadly this doesn't seem to fix my problems. I think I will leave it for now and once I have time I'll write the nuxt/ui component I'm using from scratch.

**Comment by jonkuze** [comment]
I'm also facing this issue when deploying my new website built with Nuxt 3 + Nuxt UI Pro to Cloudflare. I can load the homepage just fine if I append a query param. I tried the above work-arounds, but no luck.

**Comment by BracketJohn** [comment]
@danielroe would you be open to receiving a small PR that adds a `emitRouteChunkError: 'automatic-navigation-and-lazy'` option which adds a plugin that (in essence):
```ts
export default defineNuxtPlugin({
  name: 'nuxt:chunk-reload-navigation-and-lazy',
  setup(nuxtApp) {
    nuxtApp.hook('app:chunkError', () => { reloadNuxtApp() })
  },
})
```

The PR would also extend docs on this to explain the different trade-offs (eg: `navigation-and-lazy` leading to more frequent reloads, potentially even without user-interaction).

One potential improvement to this proposal I already see is renaming the `automatic`-option to `automatic-navigation` and add the new option as `automatic` / `automatic-complete` / `automatic-total` (as it reloads for _all_ `chunkError`s). However, I'm concerned that this would be too breaking (as users already use the `automatic` strategy).

I think this would be useful as many users (see this issue & the many duplicates) seem to encounter the Lazy-chunk error, but don't seem to be comfortable with adding their own `manual` plugin / seem to be unsure whether this implementation would actually solve their problem (although it should, as you agreed [here](https://github.com/nuxt/nuxt/pull/19086#issuecomment-1553529591) given the same proposal by @edwh [right above that reply](https://github.com/nuxt/nuxt/pull/19086#issuecomment-1553385289)).

If you think this is useful, I'd be happy to open a PR & push it through. 

Thanks 💯

**Comment by danielroe** [comment]
I would! Thank you for the idea.

**Comment by maxibue** [comment]
> Great (: I've opened [#28160](https://github.com/nuxt/nuxt/pull/28160) to implement the proposal.

Excited to see this finally fixed! 👀
