### ISSUE TITLE
Code suggestions with typedPages enabled doesn't work on IntelliJ / VSCode

### ISSUE THREAD

**Issue by jdohuutin** [nuxt/nuxt#23618]
### Environment

- Node Version:     v19.4.0
- Nuxt Version:     3.7.4

### Reproduction

Reproduced with nuxt starter v3 codesandbox (with `experimental.typedPages` enabled)

https://github.com/nuxt/starter/tree/v3-codesandbox

### Describe the bug

With the `typedPages` feature enabled :

```js
experimental: {
    typedPages: true
},
```

On Intellij IDE (WebStorm/PHPStorm), code suggestions (autocompletion)(Ctrl+Space) doesn't work when using `NuxtLink` component, on the template block (same issue with VSCode)

It works fine with composable `useRouter` and `useRoute`, I can retrieve the correct type and visualize the routes of my application.

According to the README of the [unplugin-vue-router](https://github.com/posva/unplugin-vue-router), code suggestions on VSCode seems possible.

The `vue-tsc` tool work as intended on `NuxtLink` and can detect typescript errors. I guess the types of vue-router is correctly generated.

Am I missing something ?

**Comment by danielroe** [comment]
This sounds like an issue with Webstorm in that case, particularly if it is working with `vue-tsc`.
