### ISSUE TITLE
Headers object of `useFetch` should be reactive

### ISSUE THREAD

**Issue by ExEr7um** [nuxt/nuxt#23626]
### Describe the feature

Query options in `useFetch` are reactive, so it automatically watches for changes there. Headers should be also reactive and actually it is, I can pass `ref` to headers and it will watch for changes, but will give TypeScript errors.

It is because it only accepts `string` as value, but should accept `MaybeRef<string>`.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by c-schwan** [comment]
@ExEr7um 

I thought so too a while ago. But it was a Bad idea.

unref(opts.headers) are used for cached keys.
Refresh while watching the Headers will lead to cached result.

**Comment by ExEr7um** [comment]
> I was going to take a look at this but I'm not getting a TS error? I have the following code:
> 
> ```ts
> const query = ref({
>   latest: true
> })
> const headers = ref({
>   'x-test': 'true'
> })
> 
> const { data } = await useFetch('https://api.spacexdata.com/v3/launches', {
>   query,
>   headers
> })
> ```
> 
> And when I hover over `headers` in the `useFetch` I get the following hint which suggests it accpets a `Ref`:
> 
> ```
> (property) headers?: HeadersInit | globalThis.Ref<HeadersInit | undefined> | undefined
> A Headers object, an object literal, or an array of two-item arrays to set request's headers.
> ```
> 
> Also, as you say, it is reacitve and does re-fetch when the `headers` ref changes.

I use it to change localization, so what I do is:
```ts
const { data } = await useFetch('someApi', {
  headers: {
    "Accept-Language": useI18n().locale
  }
})
```
Here `useI18n().locale` is a `Ref`, and I get an error.

As a temporary fix I can wrap my headers into computed, but I don't need to do it when working with `query`, so I thinks it not consistent and should be changed.

**Comment by Mini-ghost** [comment]
@danielroe As a pure type fix, perhaps this be an acceptable approach?

```diff
type ComputedOptions<T extends Record<string, any>> = {
-   [K in keyof T]: T[K] extends Function ? T[K] : T[K] extends Record<string, any> ? ComputedOptions<T[K]> | Ref<T[K]> | T[K] : Ref<T[K]> | T[K]
+   [K in keyof T]: T[K] extends Function ? T[K] : ComputedOptions<T[K]> | Ref<T[K]> | T[K]
}
```

**Comment by danielroe** [comment]
That seems good to me. 🙏
