### ISSUE TITLE
Cannot find module '#internal/nitro/virtual/storage' 

### ISSUE THREAD

**Issue by simllll** [nuxt/nuxt#23622]
### Environment

Nuxt project info:                                                                                                                                                                                               19:50:41

------------------------------
- Operating System: Linux
- Node Version:     v18.16.1
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@9.5.1
- Builder:          -
- User Config:      srcDir, typescript, nitro, socket, app, runtimeConfig, tailwindcss, modules
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, nuxt3-socket.io@0.2.0
- Build Modules:    -
------------------------------

### Reproduction

just import `import { useStorage } from 'nitropack/runtime/storage'` anywhere during server startup, 

e.g. we use nuxt3-socket.io which runs in dev mode nuxt.hook('listen', (httpServer) => { ... }) where it executes via jiti some initailizations.

see e.g. here https://github.com/wobsoriano/nuxt3-socket.io/commit/69ea86b4a6c0438e0cd9c8600f531d7383e97360
or https://github.com/wobsoriano/nuxt3-socket.io/blob/main/src/module.ts

anywasy I figured that due to this circumstances no auto imports are working, and I need to import useStorage manually. I couldn't find any other way then importing it directly from nitropack/runtime/storage.. this was working some months ago, but doesn't work with latest nuxt anymore.

 Require stack:
  - node_modules/nitropack/dist/runtime/storage.mjs
  at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
  at Function.resolve (node:internal/modules/cjs/helpers:116:19)
  at _resolve (node_modules/jiti/dist/jiti.js:1:250334)
  at jiti (node_modules/jiti/dist/jiti.js:1:252917)
  at node_modules/nitropack/dist/runtime/storage.mjs:2:16
  at evalModule (node_modules/jiti/dist/jiti.js:1:255614)
  at jiti (node_modules/jiti/dist/jiti.js:1:253542)
  at src/dashboard/dashboard-state.ts:4:16
  at evalModule (node_modules/jiti/dist/jiti.js:1:255614)
  at jiti (node_modules/jiti/dist/jiti.js:1:253542)
  at src/server/socket/dashboardcore.ts:1:194
  at evalModule (node_modules/jiti/dist/jiti.js:1:255614)
  at jiti (node_modules/jiti/dist/jiti.js:1:253542)
  at .nuxt/io-dev-functions.mjs:5:29
  at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

### Describe the bug

importing useStorage manually fails due to the reason that it cannot resolve `#interal`

**Comment by simllll** [comment]
I actually went a different way, instead of using useStorage, I checked out unstorage directly.

```ts
import { createStorage, prefixStorage } from 'unstorage'
```

```ts
  const fs = fsDriver(configStorage)
  const storage = createStorage({})
  storage.mount('dashboardState', fs)

  const myStorage = prefixStorage(storage, 'myStorage')
```

**Comment by danielroe** [comment]
I think you should import like this:

```ts
import { useStorage } from '#imports'
```

**Comment by sebaguse** [comment]
sorry to re-opening this issue, but I'm getting same error but don't use useStorage in my application (at least not directly, perhaps pinia-plugin-persistedstate uses it?):
`"/node_modules/nuxt/dist/core/runtime/nitro/cache-driver.js" is imported by "virtual:#internal/nitro/virtual/storage", but could not be resolved – treating it as an external dependency.`
can't really see any problems with my app so difficult to track down the issue... I'll be grateful for any suggestions how to fix it :)

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.12.2
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.5.0
- Builder:          -
- User Config:      app, runtimeConfig, $development, css, modules, quasar, pinia, imports, vite, content, vue, nitro, devtools, devServer, ssr, build, alias
- Runtime Modules:  nuxt-quasar-ui@2.1.0, @pinia/nuxt@0.5.1, @vueuse/nuxt@10.9.0, @pinia-plugin-persistedstate/nuxt@1.2.0, @nuxt/content@2.12.1, @formkit/auto-animate/nuxt@0.8.2
- Build Modules:    -
------------------------------
