### ISSUE TITLE
I hope to support the function of publishing to cloudflare worker.

### ISSUE THREAD

**Issue by bbhxwl** [nuxt/nuxt#23630]
### Describe the feature

I hope to support the function of publishing to cloudflare worker.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
This is possible already, with NITRO_PRESET=cloudflare... You can read more at https://nitro.unjs.io/deploy/providers/cloudflare.

**Comment by bbhxwl** [comment]
> This is possible already, with NITRO_PRESET=cloudflare... You can read more at https://nitro.unjs.io/deploy/providers/cloudflare.

Why don't I have NITRO_ PRESET command?

**Comment by danielroe** [comment]
It's not a command; it's an environment variable you can set to force the environment. Or you can define it in the config:

```ts
export default defineNuxtConfig({
  nitro: {
    preset: 'cloudflare'
  }
})
```

**Comment by bbhxwl** [comment]
> Member

![image](https://github.com/nuxt/nuxt/assets/26525599/4ffb60db-3e33-4894-ad13-3b9ff81b30fe)
![image](https://github.com/nuxt/nuxt/assets/26525599/c45d7901-6dcd-42d6-a1bb-192bfa0d24aa)
![image](https://github.com/nuxt/nuxt/assets/26525599/d5690268-67be-46ed-981a-332a24ce6610)
