### ISSUE TITLE
failed to resolve "extends":"./.nuxt/tsconfig.json"

### ISSUE THREAD

**Issue by baixiaoyu2997** [nuxt/nuxt#23634]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  pnpm@8.6.12
- Builder:          -
- User Config:      extends
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

in https://stackblitz.com/edit/nuxt-starter-jrafrm?file=package.json
and run `pnpm run generate`

### Describe the bug

i can't build with layer, in `tsconfig.json`, i extend config from "./extends/deorderbook-base/tsconfig.base.json", but i have error: `failed to resolve "extends":"./.nuxt/tsconfig.json"`

this is really confusing because I'm not using extends/deorderbook-base/tsconfig.json

**Comment by AndreyYolkin** [comment]
<img width="1137" alt="image" src="https://github.com/nuxt/nuxt/assets/11289484/c40f4560-b276-446c-995b-fef6172fe2b0">

It can be solved by using the correct path

``` json
{
  "extends": ["../../.nuxt/tsconfig.json", "./tsconfig.base.json"]
}

```

**Comment by baixiaoyu2997** [comment]
> <img alt="image" width="1137" src="https://user-images.githubusercontent.com/11289484/274548357-c40f4560-b276-446c-995b-fef6172fe2b0.png">
> It can be solved by using the correct path
> 
> ```json
> {
>   "extends": ["../../.nuxt/tsconfig.json", "./tsconfig.base.json"]
> }
> ```

thanks, I configured it like this before，but i want layer can run standalone

**Comment by danielroe** [comment]
You probably need to prepare the layer then: `nuxi prepare extends/deorderbook-base`.

**Comment by baixiaoyu2997** [comment]
> You probably need to prepare the layer then: `nuxi prepare extends/deorderbook-base`.

big thanks daniel,  i add this command to my root project, this ensures that it can run properly on Vercel as well:
```
 "scripts": {
    "dev": "npm run prepare:base && cross-env MODE=locale nuxi dev --dotenv .env.development",
    "build": "npm run prepare:base && nuxi build",
    "prepare:base": "nuxt prepare extends/deorderbook-base",
    "generate:test": "npm run prepare:base && cross-env MODE=test nuxi generate --dotenv .env.production",
  },
```
a bit ugly, but it can run
