### ISSUE TITLE
nuxt.config.ts添加app:{baseURL:"v2"}在最新版本中启动项目后不会默认在端口号后边添加v2，只会显示http:localhost:3000

### ISSUE THREAD

**Issue by cqh-git** [nuxt/nuxt#23632]
### Environment

development

### Reproduction

![Uploading image.png…]()

### Describe the bug

nux3 的v3.7.4版本中，在nuxt.config.ts中添加配置app，然后在app中添加一个配置项baseURL:"v2"，然后启动命令后，ip和端口号后边不会默认添加v2，期望是http://localhost:3000/v2, 但是实际显示的是http://localhost:3000，而在nuxt3中的v3.5.2的版本中，在nuxt.config.ts,在app的配置中添加baseURL:"v2",启动项目后是会显示http://localhost:3000/v2，也就是最新版本不会在端口号后边添加自定义的baseURL

**Comment by cqh-git** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，你的邮件我已收到，看到后第一时间回复你

**Comment by Flysky12138** [comment]
me too

**Comment by warflash** [comment]
@Flysky12138 Do you happen to have a reproduction?

**Comment by Flysky12138** [comment]
@warflash There is a similar issue here https://github.com/nuxt/nuxt/issues/23598. I have downgraded Nuxt to 3.6.2, and it's working now.

**Comment by warflash** [comment]
Oh I see. The language made it a bit hard to understand. 
Same as with the issue you linked - this has been fixed in the cli repo and should be available in the next cli release, so keep an eye out for that. -> https://github.com/nuxt/cli/releases
Thanks!
