### ISSUE TITLE
Uncaught (in promise) DOMException: Failed to construct 'WebSocket': The URL 'ws://localhost:undefined/_nuxt/' is invalid.

### ISSUE THREAD

**Issue by yisibell** [nuxt/nuxt#23639]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.12.1
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  pnpm@8.3.1
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://github.com/yisibell/nuxt-svg-icons

### Describe the bug

Report an error when add vite plugin via `addVitePlugin`:

```html
client.ts:77 WebSocket connection to 'ws://localhost:3000/_nuxt/' failed: 
setupWebSocket @ client.ts:77
(anonymous) @ client.ts:67
Show 2 more frames
Show less
client.ts:77 Uncaught (in promise) DOMException: Failed to construct 'WebSocket': The URL 'ws://localhost:undefined/_nuxt/' is invalid.
    at setupWebSocket (http://localhost:3000/_nuxt/@vite/client:268:20)
    at fallback (http://localhost:3000/_nuxt/@vite/client:247:22)
    at WebSocket.<anonymous> (http://localhost:3000/_nuxt/@vite/client:283:13)
```

```bash
 ERROR  [unhandledRejection] read ECONNRESET                                                                                                                                                                      17:41:32  

  at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
```

**Comment by danielroe** [comment]
This is an upstream bug. Raised https://github.com/yisibell/vite-plugin-svg4vue/pull/3.

**Comment by yisibell** [comment]
> This is an upstream bug. Raised [yisibell/vite-plugin-svg4vue#3](https://github.com/yisibell/vite-plugin-svg4vue/pull/3).

Thank you for help! It works.
