### ISSUE TITLE
Unable to obtain response header using useFetch

### ISSUE THREAD

**Issue by 1877666** [nuxt/nuxt#23635]
### Environment

"nuxt": "^3.6.5"
Node.js v16.14.2.

### Reproduction

 .

### Describe the bug

In the nuxt3 project, the response. headers response header that encapsulates useFetch in the onResponse callback function is always an empty object, but it can be obtained using axios. The response header can be seen in the browser's network request, and the backend has already exposed it

**Comment by luc122c** [comment]
You probably want the [raw response from oFetch](https://github.com/unjs/ofetch?tab=readme-ov-file#-access-to-raw-response). `raw: true` doesn't seem to be a valid option for `useFetch` however.

**Comment by 1877666** [comment]
> github-actions

Thank you for your answer

const login = () =>{
    $fetch('http://localhost:3000/api/user/login',{
      raw:true,
      method:'post',
      body:{
    id:userInfo.id,
    password:userInfo.password
   },onResponse({response}){
    console.log('Headers', response.headers)
    //{}
   }
    })
}

I have tried both useFetch and $Fetch, and response.headers is still an empty object

**Comment by 1877666** [comment]
> You probably want the [raw response from oFetch](https://github.com/unjs/ofetch?tab=readme-ov-file#-access-to-raw-response). `raw: true` doesn't seem to be a valid option for `useFetch` however.
> 
> Example with `$fetch`:
> 
> ```ts
> const data = await $fetch('https://randomuser.me/api/', {
>   raw: true,
>   async onResponse({ response }) {
>     console.log('Headers', response.headers);
>   },
> });
> ```


Thank you for your answer

const login = () =>{
$fetch('[http://localhost:3000/api/user/login',{](http://localhost:3000/api/user/login',%7B)
raw:true,
method:'post',
body:{
id:userInfo.id,
password:userInfo.password
},onResponse({response}){
console.log('Headers', response.headers)
//{}
}
})
}

I have tried both useFetch and $Fetch, and response.headers is still an empty object

**Comment by christianholland** [comment]
@1877666 I have the same issue. The `response.headers` object is always empty. Did you find a solution?

**Comment by BenWaNH** [comment]
Same issue here!
In my response object i have only 4 keys: Cache-control, content-length, content-type and date. 
I need parse Link header from my server response (network show me all is good) but nothing in my response :'(

**Comment by FeatureSpitter** [comment]
```
    const { data, error } = await useFetch<User, FetchError<ApiErrorResponse>>(
      ApiPaths.USER_LOGIN(),
      {
        credentials: "include",
        method: "POST",
        body: loginPayload,
        onResponse({ request, response, options }) {
          console.log(response.headers)
        },
      },
    )
```

The headers are always empty... What the hell?

**Comment by BenWaNH** [comment]
Ok, for my case, it was a server issue with cors policy. I had to indicate that Link is an authorized header.

**Comment by psycongaroo** [comment]
same, is empty

**Comment by ycoya** [comment]
> Ok, for my case, it was a server issue with cors policy. I had to indicate that Link is an authorized header.

This works partially for me. After reading your comment, I looked into cors.php config file for laravel as backend, and i set the 

` 'exposed_headers' => ['*'],`
This expose all headers.
I had it in blank. The weird for me is that i could see these headers on browser response, but not with $fetch, that's why i didn't considered it was a cors issue.
Anyways, cookies are in blank even when i could check on browser that these cookies are sent. I have support to credentials set true in cors.

In my case i'm testing with $fetch.raw(url), not useFetch.
