### ISSUE TITLE
301 redirection on each page

### ISSUE THREAD

**Issue by GuillaumeDgr** [nuxt/nuxt#23647]
### Environment

- Operating System: Darwin
- Node Version:     v19.1.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      site, modules, runtimeConfig, plugins, build, googleFonts, strapi, i18n, colorMode, gtag, image, vite, sitemap, nitro
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @nuxtjs/google-fonts@3.0.2, @nuxtjs/strapi@1.9.3, @nuxtjs/i18n@8.0.0-rc.5, @nuxtjs/color-mode@3.3.0, @nuxt/image@1.0.0-rc.3, nuxt-icon@0.4.2, nuxt-gtag@0.5.9, nuxt-jsonld@2.0.8, nuxt-simple-robots@3.1.6, nuxt-simple-sitemap@3.4.0, vue-recaptcha/nuxt
- Build Modules:    -

### Reproduction

https://devloop.dev/any-url

### Describe the bug

Each time I visit any or my nuxt3 website url, a 301 redirection occurs and redirects to url/ with trailing slash at the end. This is really a problem for SEO matters...

I look for all topics about it but did not find any workable solution, pls help me! 

Many thanks!

![Screenshot 2023-10-12 at 17 39 12](https://github.com/nuxt/nuxt/assets/29545767/53770ca1-d4ee-4ae5-97d3-8ad060741a96)
![Screenshot 2023-10-12 at 17 42 01](https://github.com/nuxt/nuxt/assets/29545767/d507d684-4b8e-4651-b07c-81585dc24874)

**Comment by warflash** [comment]
This looks to be causes by the i18n module. Apart from appending the slash it seems to also redirect to the /fr/ locale so the redirect seems intentional

**Comment by danielroe** [comment]
I'd recommend raising an issue there. It doesn't seem like this is a Nuxt issue. 🙏

**Comment by GuillaumeDgr** [comment]
Done. Thanks a lot for your help and fast answers!
