### ISSUE TITLE
All components are loaded at once in development mode

### ISSUE THREAD

**Issue by cdwmhcc** [nuxt/nuxt#23649]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.18.1
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  pnpm@8.9.0
- Builder:          -
- User Config:      app, buildDir, runtimeConfig, imports, css, components, alias, modules, auth, image, googleFonts, colorMode
- Runtime Modules:  @nuxtjs/color-mode@3.3.0, @pinia/nuxt@0.4.11, nuxt-lodash@2.5.0, @/modules/google-fonts/module, @nuxt/image@1.0.0-rc.3, @sidebase/nuxt-auth@0.5.0
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-kpf6bg?file=plugins%2Fnxui.ts

### Describe the bug

1. Created some custom components in the `/packages/components` directory
2. Created `/plugins/nxui.ts` file to load the components.
3. When I run `pnpm run dev`, all components in the /packages/componets directory will be loaded.
4. When I refresh the page, all components in the /packages/componets directory are loaded.

This is a minimal example, I just created a card component under /packages/compoents, imported and exported the component in /packages/compoents/index.ts. The plugins are imported in /plugins/nxui.ts.

My page doesn't use the card component, but when the page loads it introduces it.

As you can imagine, when I have dozens of components, it takes dozens of seconds for the page to load.

I don't know from which version it became like this.

![image](https://github.com/nuxt/nuxt/assets/8030134/eed0f6bd-668f-45d9-b277-ef7c0203b7cf)

**Comment by danielroe** [comment]
They are all loaded because you are loading all of them in the plugin. I'm not sure I would consider this a Nuxt issue. What do you think should happen?

(Part of this is how Vite works in dev mode - vite has to load every component because you are initialising them.)

**Comment by cdwmhcc** [comment]
> They are all loaded because you are loading all of them in the plugin. I'm not sure I would consider this a Nuxt issue. What do you think should happen?
> 
> (Part of this is how Vite works in dev mode - vite has to load every component because you are initialising them.)

You may not understand what I mean.
Let's ignore components.
For example, let me create the folder `/packages/utils`
Create `is.ts`,`index.ts` in this folder

is.ts
``` ts
export const isUndefined = (val: any): val is undefined =>
  val === undefined
```
index.ts
``` ts
export * from './is'
```

Now, I don't import them in any of the components, but nuxt.js automatically loads them all after I execute `npm run dev`. What I understand is that it will only be loaded when I import `/packages/utils/is.ts` or `/packages/utils/index` in the component?

Now, I don't import them in any of the components, but when I execute npm run dev and access localhost:3000 through the browser, nuxt.js will automatically load them all. The problem caused by this is that no matter whether I actually import and use the module in the project, nuxt will load them. In the end, it will take dozens of seconds to load when I visit or refresh the page. This is very painful during the development process.

**Comment by danielroe** [comment]
Would you update your reproduction to show this?

**Comment by cdwmhcc** [comment]
> Would you update your reproduction to show this?

Ok, I have a rough idea of what's causing this problem, I need a moment to put together a minimal example

**Comment by vhovorun** [comment]
@cdwmhcc Hey, have u managed to do smth with this? Since I have same problem

**Comment by gavmck** [comment]
I think it's a Vite think rather than Nuxt https://github.com/vitejs/vite/issues/8237
