### ISSUE TITLE
create nuxt3 template fail

### ISSUE THREAD

**Issue by baba990aini** [nuxt/nuxt#23657]
### Environment

window10 64

### Reproduction

no have

### Describe the bug

 ERROR  Error: Failed to download template from registry: fetch failed                                         13:47:38

npm ERR! code 1
npm ERR! path C:\Users\Administrator\Desktop
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c create-vite

npm ERR! A complete log of this run can be found in: C:\Users\Administrator\AppData\Local\npm-cache\_logs\2023-10-13T05_47_18_390Z-debug-0.log
PS C:\Users\Administrator\Desktop>

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/cli/issues/159.

**Comment by baba990aini** [comment]
I have resolved it. Thank you
