### ISSUE TITLE
winston@3.9.0 cannot be imported correctly.

### ISSUE THREAD

**Issue by Sara2009** [nuxt/nuxt#23655]
### Environment

- Operating System: Darwin
- Node Version:     v18.1.0
- Nuxt Version:     3.6.3
- Nitro Version:    2.5.2
- Package Manager:  yarn@3.5.1
- Builder:          vite
- User Config:      modules
- Runtime Modules:  @nuxtjs/tailwindcss@6.7.0
- Build Modules:    -

### Reproduction

https://github.com/Sara2009/bug-report-nuxt3

run `yarn `

![image](https://github.com/nuxt/nuxt/assets/9332442/c4b0cb0f-83fc-440f-b165-290a512a4dfc)

### Describe the bug

nuxt dev use jiti to import module with `interopDefault: true`.
In winson:
```javascript
exports.transports = require('./winston/transports');

Object.defineProperty(exports, 'default', {
  get() {
    return {
      exceptionHandlers: defaultLogger.exceptionHandlers,
      rejectionHandlers: defaultLogger.rejectionHandlers,
      transports: defaultLogger.transports
    };
  }
});

```

```javascript
import winston from 'winston';
```

I want to use the `exports.transports`. But it is changed to `exports.default.transports`.

**Comment by danielroe** [comment]
This looks like an upstream issue with https://github.com/unjs/jiti.

cc: @pi0

**Comment by pi0** [comment]
Do you mind to open an issue in jiti as well with repro? 🙏🏼

**Comment by Sara2009** [comment]
> Do you mind to open an issue in jiti as well with repro? 🙏🏼

https://github.com/unjs/jiti/issues/177

**Comment by danielroe** [comment]
Thank you! ❤️ 

Let's track there.
