### ISSUE TITLE
Modify RuntimeConfig from Nitro Plugin

### ISSUE THREAD

**Issue by ccobham** [nuxt/nuxt#23653]
### Describe the feature

Hello,

We're looking to deploy a Nuxt 3 app that fetches credentials from AWS Secrets Manager at runtime on server startup and sets dynamic `RuntimeConfig` properties for later use in various server handlers/composables.

Although we can read the `RuntimeConfig` properties set pre-build time, we are unable to modify the `RuntimeConfig` object returned from `useRuntimeConfig()` within a Nitro Plugin.

Is there any existing mechanism to initialize `RuntimeConfig` values after Nitro starts up but before the first Vue app is created?

Thanks!

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/20561

**Comment by ccobham** [comment]
@manniL Thanks for the quick reply. I'll follow the linked issue for updates
