### ISSUE TITLE
Define components in /pages dir should not maps to a page

### ISSUE THREAD

**Issue by recallwei** [nuxt/nuxt#23658]
### Describe the feature

Is there some way to ignore the child components of a page located in /pages dir.
Here's a dir like below:
```
|- pages
     |- social
          |- _components
                  |- component1
                        |- index.vue
                  |- index.ts
          |- index.vue
     |- about
          |- index.vue
```
`/pages/social/_components/component1` should be ignored because it is just a child component of `/pages/social`
     

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by zhuchentong** [comment]
i have same question,if add `/pages/**/_components/**` in `.nuxtignore` ,hmr will not working

**Comment by HigherOrderLogic** [comment]
I believe that there isn't any convention such as `_components` folder exists in Nuxt.

**Comment by recallwei** [comment]
`_components` folder in pages helps us organize code better, we just split the huge page component into small chunks for maintainability and don't want them to be global components. Not only the components but also some other utils or constants.

**Comment by danielroe** [comment]
Nuxt supports a `.nuxtignore` file and an `ignore` property in Nuxt config.

You can also add custom code in the `pages:extend` hook to exclude any pages generated from a particular path.

**Comment by IlyaSemenov** [comment]
For anyone who lands here, put this to `modules/ignore-page-helpers.ts`:

```ts
import { defineNuxtModule } from "@nuxt/kit"
import type { NuxtPage } from "@nuxt/schema"

// Exclude page components gathered from files or folders starting with _ from the router.
export default defineNuxtModule({
  setup(_options, nuxt) {
    nuxt.hook("pages:extend", (pages) => {
      pages.splice(0, pages.length, ...filterIgnoredPages(pages))
    })
  },
})

function filterIgnoredPages(pages: NuxtPage[]) {
  return pages
    .filter((page) => !page.file?.includes("/_"))
    .map((page) =>
      page.children ? { ...page, children: filterIgnoredPages(page.children) } : page,
    )
}
```

That said, I am personally disappointed by the team's decision. This is a very reasonable approach to put e.g. "base" page components alongside the actual pages, for cases such as when the single slot in `<nuxt-page>` is not enough, which is quite often.

`ignore` property in Nuxt config is not a viable option because it excludes the respective files from HMR lifecycle.

There should be something like `pages: { ignore: "_" }` in Nuxt config in addition to root `ignore` option.
