### ISSUE TITLE
Nuxt config documentation is currently broken

### ISSUE THREAD

**Issue by matthew-dean** [nuxt/nuxt#23651]
### Environment

N/A

### Reproduction

[N/A](https://nuxt.com/docs/api/configuration/nuxt-config#nuxt-configuration-reference)

### Describe the bug

It says "This file is auto-generated from the [source code](https://github.com/nuxt/nuxt/tree/main/packages/schema/src/config)." but nothing is visible on the page.

**Comment by danielroe** [comment]
fixed - thanks for the report! ✅
