### ISSUE TITLE
ssr模式下，useFetch在页面刷新后获取的数据为null

### ISSUE THREAD

**Issue by tanglongyan** [nuxt/nuxt#23660]
### Environment

1. Operating System:window10
2. Node Version: v18.17.1
3. Nuxt Version: 3.6.5
5. Package Manager: yarn@1.22.19
6. Builder: vite
7. User Config: app, components, runtimeConfig, modules, pinia, vite, css, alias, experimental
8. Runtime Modules: @pinia/nuxt@0.4.11
9. Build Modules: -

### Reproduction

在setup中使用useFetch获取数据，项目刚启动完成后能正常拿到数据，但是在浏览器地址手动输入地址刷新页面后useFetch此时获取到的数据为null

### Describe the bug

在setup中使用useFetch获取数据，项目刚启动完成后能正常拿到数据，但是在浏览器地址手动输入地址刷新页面后useFetch此时获取到的数据为null

~~~vue

<template>
	<!-- 路由出口 -->
	<NuxtPage></NuxtPage>
</template>
<script setup lang="ts">
const { data } = await useFetch('/copywriter', {
	method: 'get',
	baseURL: 'https://*****/api',
	params: {
		uri: 'home',
	}
})

console.log('请求结果', data.value)
</script>

~~~

### Additional context

如果说这种写法本身有问题，为什么会在每次项目跑起来首次打开页面时可以正确的拿到数据，而在浏览器地址栏中手动输入刷新页面后，useFetch拿到的数据又变为null。

**Comment by TangsWang** [comment]
cors?

**Comment by tanglongyan** [comment]
> cors?

你是在说可能是跨域导致的数据为null吗？如果是跨域项目跑起来最开始打开页面的时候就改拿不到数据，现在就是有是后useFetch是拿得到值的

**Comment by TangsWang** [comment]
hybird, set it to server/api or use process.server.

**Comment by tanglongyan** [comment]
> hybird, set it to server/api or use process.server.
~~~vue
<template>
	<!-- 路由出口 -->
	<NuxtPage></NuxtPage>
</template>
<script setup lang="ts">
const h= ref()
if (process.server) {
	const { data } = await useFetch('/copywriter', {
		method: 'get',
		baseURL: 'https://api.astroai.com/api',
		params: {
			uri: 'home',
		}
	})
	h.value = data.value
	console.log('请求结果', data.value)
}
</script>
~~~

你的意思是在这儿加个判断？据我所知，官网建议如果走的ssr渲染就应该把useFetch在setup中运用

**Comment by bbhxwl** [comment]
nuxt3 挺好用的样子，可惜我nuxt2不容易升级

**Comment by Mobbbb** [comment]
朋友，你解决了吗，我遇到了同样的问题

**Comment by PdxLook** [comment]
@Mobbbb @tanglongyan  你好，你们解决此问题了吗？ 同样useFetch，第一次能获取数据，页面刷新就获取不了数据，页面还报错：This page is temporarily unavailable.

**Comment by Mobbbb** [comment]
> @Mobbbb @tanglongyan 你好，你们解决此问题了吗？ 同样useFetch，第一次能获取数据，页面刷新就获取不了数据，页面还报错：This page is temporarily unavailable.

我已经解决了，但是我的问题应该跟楼主的不太一样，我是把useFetch写在了store里导致获取结果为null，将他写在setup内就好了

**Comment by PdxLook** [comment]
@Mobbbb  感谢回答，我的写在setup内，在服务器上也会出现数据null的情况。加上key后，能获取数据。但是还是有问题

**Comment by Mobbbb** [comment]
> @Mobbbb 感谢回答，我的写在setup内，在服务器上也会出现数据null的情况。加上key后，能获取数据。但是还是有问题

你可以贴一下你的代码，而且你页面报错500，很可能是其他地方有问题

**Comment by PdxLook** [comment]
@Mobbbb  https://github.com/nuxt/nuxt/issues/25024 这边贴了代码，build上传到服务器，接口获取null，导致模板加载问题

**Comment by Mobbbb** [comment]
> @Mobbbb #25024 这边贴了代码，build上传到服务器，接口获取null，导致模板加载问题

感觉像是接口问题，你可以看看后端那边的接收、参数这些是不是都正常获取到了
