### ISSUE TITLE
Asynchronously adding routes at runtime doesn't work reliably

### ISSUE THREAD

**Issue by dulnan** [nuxt/nuxt#23678]
### Environment

Applies to any environment. Reproduction uses Nuxt 3.7.4.

### Reproduction

https://stackblitz.com/edit/github-wyjpmc?file=app.vue

## Setup
- Two pages exist: `pages/index.vue` with name `home` and `pages/foobar/index.vue` with name `foobar`.
- The plugin `plugins/alterRoutes.ts` adds an additional route using `router.addRoute()` with name `foobar-dynamic` and path `/foobar-dynamic`. The path is loaded async (e.g. from an API call)
- In `app.vue` a computed property returning the route name exists
- In `app.vue` a watcher on the computed route name logs the name to the console
- In `app.vue` the computed route name is logged to the console directly in setup()

## Reproduce bug
- Visit the front page `home`. Refresh. The name of the route is logged correctly to the console.
- Now click on `foobar-dynamic`. The name is logged correctly to the console.
- Now refresh the page.
- The name of the route logged to the console is `undefined`.

### Describe the bug

Only the initially available routes generated at build time are used for the inital router state. The reactive route from `useRoute()` does not contain the dynamically added route during setup.

The problem can be fixed with a workaround by calling router.replace() after adding the dynamic routes:

```typescript
router.addRoute({
  // ...
})
await router.replace({
  ...router.resolve(route.path),
  force: true
})
```

### Additional context

The closed issue #12823 seems related and also contains a few comments about adding/altering routes async. There is also #13467 which is open, but it doesn't specifically mention an async way of adding routes at runtime. There's also at least one open discussion about it.

Looking into it a bit this could be solved by allowing us to use an async method for the `routes` option in `app/router.options.ts`. That way the initial state of the router would already be correct and wouldn't require any additional plugins.

https://github.com/nuxt/nuxt/blob/5c7cca170a85b0584b4091e7e7e461b4800c0e36/packages/nuxt/src/pages/runtime/plugins/router.ts#L64C62-L64C62

This would be much more reliable, because it would also make sure that any other plugins (from third party modules or locally) won't have a stale/unmatched route. With the router.replace() workaround that has to be done in a custom plugin we additionally have to make sure that the order of the plugins is correct, which is another challenge in itself.

Alternatively a hook to alter the routes would also work.

A fix for this would really improve DX for a lot of us who build "headless CMS" sites where route paths can't possibly be known at build time and must be loaded at runtime, because they can be freely edited by content editors or are dynamically generated based on page titles (and therefore can change any time).

**Comment by or2e** [comment]
@dulnan 
https://github.com/nuxt/nuxt/issues/23337
