### ISSUE TITLE
Newly created page return 404 until manually reset HMR

### ISSUE THREAD

**Issue by anhhuy1605** [nuxt/nuxt#23682]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.8.1
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  pnpm@8.9.0
- Builder:          -
- User Config:      vue, devtools, telemetry, vite
- Runtime Modules:  -
- Build Modules:    -
------------------------------  

### Reproduction

1. Init new nuxt project
2. Remove `app.vue`
3. Add 2 pages: `index.vue` and `test.vue`
4. Delete `test.vue` page
5. Add `test2.vue` page
6. Visit `/test2`

### Describe the bug

It is similar to these reports:
https://github.com/nuxt/nuxt/issues/15651
https://github.com/nuxt/nuxt/issues/13725

This problem will not arise if we just create new pages. Only after we delete a page, then we see this issue appear.

**Comment by lafllamme** [comment]
Same here.

Very frustating for my dev experience, with a similar behaviour to /server

**Comment by danielroe** [comment]
Would you try on the latest version of Nuxt? I can't reproduce on v3.11.

**Comment by RSickenberg** [comment]
Any update? @anhhuy1605
