### ISSUE TITLE
Runtime config objects not replaced by env variables

### ISSUE THREAD

**Issue by becem-gharbi** [nuxt/nuxt#23695]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools, runtimeConfig
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-e6syfm-bu4rgq?file=nuxt.config.ts

### Describe the bug

As described in [docs](https://nuxt.com/docs/guide/going-further/runtime-config#environment-variables), matching env variables should replace runtime config properties.

However, a property with primitive and non-primitive type (e.g `boolean | object`) cannot be replaced. 

```ts
  runtimeConfig: {
    public: {
      feature: {   // Setting `NUXT_PUBLIC_FEATURE=false` has no effect
        option: true,
      },
    },
  },
```

### Additional context

This issue is related to this PR https://github.com/Baroshem/nuxt-security/pull/233#discussion_r1357841008

**Comment by danielroe** [comment]
This is because these values are merged using `defu` (in nitro).

If you think this is a bug, then would you open an issue in https://github.com/unjs/nitro? 🙏
