### ISSUE TITLE
When coming from Google, Nuxt module pages give 504: GATEWAY_TIMEOUT

### ISSUE THREAD

**Issue by AaronBeaudoin** [nuxt/nuxt#23702]
### Environment

N/A

### Reproduction

N/A

### Describe the bug

If I Google "nuxt icon" for example:

<img width="474" alt="image" src="https://github.com/nuxt/nuxt/assets/26592486/f683d580-75a0-4bbf-9d09-72d0e91a61bb">

If I click this link it spins for maybe 10 seconds or so and then I get this:

<img width="572" alt="image" src="https://github.com/nuxt/nuxt/assets/26592486/6ac2bdfc-be31-49b2-9f0f-4370b021adb1">

The issue isn't unique to that module. If I go to the Tailwind module from Google, I get the same thing. But in both cases, if I manually copy the URL that gave me the 504 and paste it back into the browser the page loads fine. After I do that, the link works from Google as well.

**Comment by huang-julien** [comment]
Not only from google, seems like to be an issue in SSR

cc @Atinux

**Comment by Atinux** [comment]
Should be fixed very soon, working on releasing the new website this week.
