### ISSUE TITLE
[Nuxt3] Unable to Override/Re-register a built-in Vue component 

### ISSUE THREAD

**Issue by mhdSid** [nuxt/nuxt#23712]
### Environment

Nuxt 3.6.5

### Reproduction

In Nuxt2, we could do something like this using a plugin:
```
Vue.component('transition', MockedTransitionComponent)
```

In Nuxt3, I expect to do something like this using a Nuxt3 plugin:
```
const nuxt3Plugin = defineNuxtPlugin(nuxtApp => {
    nuxtApp.vueApp.component('transition', MockedTransitionComponent)
})
```

### Describe the bug

Unable to override/de-register a built-in Vue component. It was possible with Nuxt2, but not with Nuxt3

**Comment by danielroe** [comment]
This is Vue behaviour, not Nuxt: see [reproduction without Nuxt](https://stackblitz.com/edit/github-rsmztn?file=src/main.ts,src/App.vue).

Feel free to raise an issue upstream at http://github.com/vuejs/core.
