### ISSUE TITLE
`ignore` option doesn't work with pages that include param like `[id]`

### ISSUE THREAD

**Issue by vedmant** [nuxt/nuxt#23713]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools, ignore
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-vfubx6?file=nuxt.config.ts

### Describe the bug

`ignore` property doesn't ignore paths that include params

**Comment by danielroe** [comment]
You need to escape the square brackets as they mean something in the context of a glob pattern:

https://stackblitz.com/edit/github-vfubx6-1fcvkh?file=nuxt.config.ts
