### ISSUE TITLE
Production server doesn't stop with preset node-cluster

### ISSUE THREAD

**Issue by Cheaterman** [nuxt/nuxt#23723]
### Environment

```
cheaterman@cmans-laptop ~/Dev/fluxt/frontend main @ npx nuxi info
Working directory: /home/cheaterman/Dev/fluxt/frontend                                                                                                                                                    16:13:48
Nuxt project info: (copied to clipboard)                                                                                                                                                                  16:13:48

------------------------------
- Operating System: Linux
- Node Version:     v20.6.1
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  pnpm@8.9.2
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                                                                                                               16:13:48

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

cheaterman@cmans-laptop ~/Dev/fluxt/frontend main @ docker compose run --rm frontend npx nuxi info
Working directory: /home/node                                                                                                                                                                           4:14:01 PM
Nuxt project info:                                                                                                                                                                                      4:14:01 PM

------------------------------
- Operating System: Linux
- Node Version:     v18.18.2
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  pnpm@8.9.2
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                                                                                                             4:14:01 PM

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

```

### Reproduction

- Create a new Nuxt3 app with the default NuxtWelcome in app.vue
- Build it making sure you're using `NITRO_PRESET=node-cluster` : `NITRO_PRESET=node-cluster pnpm build`
- Serve it: `node .output/server/index.mjs`
- Attempt to kill it non-interactively (ie, do _not_ use ^C in shell) : `pkill -f 'node .output' -TERM` (SIGINT works too)
- Notice that it takes two attempts (the way I originally noticed is because docker takes 10s to shut down, I suspect hitting the eventual SIGKILL timeout)

### Describe the bug

One would expect production server to stop instantly at the first SIGINT/SIGTERM, instead it either takes two or needs a SIGKILL.

### Additional context

- This only happens with node cluster preset.
- Using NITRO_SHUTDOWN does not help.
- This does not happen with dev server.

**Comment by danielroe** [comment]
Would you confirm i f this happens with nitro alone, and if so raise an issue there? 🙏

**Comment by pi0** [comment]
Consider nitro hase a graceful shutdown mechanism. If a request is pending for some reason or an active resource like DB connection hanging, this can happen regardless using nuxt or not.

Regardless i would be happy to help finding a solution also here if you can make a runnable reproduction. Nuxt is okay too 👍🏼

**Comment by Cheaterman** [comment]
> Consider nitro server hase a graceful shutdown mechanism. If a request is pending for some reason or an active resource like DB connection hanging, this can happen regardless using nuxt or not.
> 
> Regardless i would be happy to help finding a solution also here if you can make a runnable reproduction. Nuxt is okay too 👍🏼

Yes, I noticed the graceful shutdown mechanism, that's why I mentioned `Using NITRO_SHUTDOWN does not help.`. Other than that I'd be more than happy to make a pure-Nitro reproduction and raise the issue there, however I'm completely unsure how to use Nitro outside of Nuxt, sorry!

**Comment by Mateleo** [comment]
Yes I have exactly the same issue when deploying Nuxt
![image](https://github.com/nuxt/nuxt/assets/25607142/92cfdca3-0909-443b-9543-a615aa5eebce)

**Comment by pi0** [comment]
@Cheaterman If you can make a Nuxt reproduction, that would also work!

-----

@Mateleo Thanks for sharing. If your "build step" like the above fails, it is probably because of an unclosed handler made by a module or during the prerender process (from screenshot above I cannot tell). Here is the more relevant issue: https://github.com/nuxt/cli/issues/193

**Comment by Mateleo** [comment]
@pi0 You were right, it's the same issue : https://github.com/nuxt/cli/issues/193

Temporary workaround
```js
export default defineNuxtConfig({
  hooks: {
    close: (nuxt) => {
      if (!nuxt.options._prepare)
        process.exit()
    }
  }
})

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/cli/issues/193 in that case.
