### ISSUE TITLE
fix: alias `@unhead/vue` on enabled `experimental.headNext`

### ISSUE THREAD

**Issue by dargmuesli** [nuxt/nuxt#23738]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    -
- Package Manager:  pnpm@8.6.12
- Builder:          -
- User Config:      devtools, experimental
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-ta4wyu?file=nuxt.config.ts

### Describe the bug

When enabling `experimental.headNext` and using `pnpm` without `shamefully-hoist=true` there is the following error: `Failed to resolve import "@unhead/vue" from "virtual:nuxt:/home/projects/github-ta4wyu/.nuxt/unhead-plugins.mjs". Does the file exist?`

### Additional context

I proposed to solve this for `nuxt-seo-kit` in https://github.com/harlan-zw/nuxt-seo-kit/pull/124, but it should be solved for Nuxt instead really.

**Comment by dargmuesli** [comment]
This should be the place to add an alias: https://github.com/nuxt/nuxt/blob/5ee2f0aa8903dd71cf4d639dee1f00e85b798beb/packages/nuxt/src/head/module.ts#L63
Right?

**Comment by danielroe** [comment]
Exactly 👌

**Comment by dargmuesli** [comment]
You mean ```return `import { CapoPlugin } from '@unhead/vue';``` could be ```return `import { CapoPlugin } from '/.../.../@unhead/vue/.../....mjs';``` or so instead?

**Comment by danielroe** [comment]
yep

**Comment by niladrix719** [comment]
can i work on this?
