### ISSUE TITLE
Pass Server-Side API call response "set-cookie" to another Server-Side API call

### ISSUE THREAD

**Issue by martinsjek** [nuxt/nuxt#23779]
### Describe the feature

Hey.
So I would like the option to pass "set-cookie" header from one request to another as request cookies.

So I have 2 or more server side requests and the response cookie for that API domain is changing based on request (it works as a session or something). So from one request I get "set-cookie" headers and the next request requires those cookies as request headers. And currently I have 3 requests completing in Server-side before page loads with data.

These API endpoints are from Laravel not Nuxt itself.

The flow that currently happens:
Server side nuxt request -> Laravel API endpoint -> Laravel returns set-cookie -> another server side request ->  cookie not set

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/22631.
