### ISSUE TITLE
Nuxt anchor app router scrollBehavior doesn't work

### ISSUE THREAD

**Issue by DavidAbou** [nuxt/nuxt#23789]
### Environment

Nuxt project info:

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  npm@10.2.0
- Builder:          -
- User Config:      devtools, css, routeRules, modules, postcss, headlessui
- Runtime Modules:  nuxt-swiper@1.2.2, @nuxt/image@1.0.0, nuxt-icon@0.5.0, nuxt-headlessui@1.1.4
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-mtzuje

### Describe the bug

I have an error with the scrollBehavior in the reproduction provided, the scroll works fine, but in my code it doesn't works. When clicking on NuxtLink the hash changes but no scroll is done. But when I reload the page with the hash in it the page reloading at the right div#hash position.
Do you have some ideas why I have this issue ?

**Comment by warflash** [comment]
It'll be quite difficult to give advice on why it might not work for your local project. I'd recommend integrating the properly behaving reproduction into the project where it's failing. Or you might start with the project that has issues and strip things away until they start working as expected again.

**Comment by DavidAbou** [comment]
This function too isn't working :
```ts
const scrollToTop = () => {
  window.scrollTo(0, 0);
};
```

**Comment by Eternal-Grace** [comment]
In my case, the scrollBehavior inside `app/router.options.ts` doesn't work whenever I enable the css:
```css
scroll-snap-type: y mandatory;
overflow-y: scroll;
overflow-x: hidden;
```
I've figured that the problem is related to the scroll snap in css.
Whenever I enable the css scroll snap, the JavaScript stops functioning. And vise-versa.

Anyone wants to test that out for me, and help us resolve the issue?

**Comment by danielroe** [comment]
This doesn't sound like a Nuxt issue if even `window.scrollTo` doesn't work. I think likely you want to call `scrollTo` on the particular element that you want to scroll.

If you are still experiencing this, feel free to provide a reproduction and we can look into it.
