### ISSUE TITLE
Importing interface error The requested module '/_nuxt/stores/<example>.ts' does not provide an export named '<exported interface>'

### ISSUE THREAD

**Issue by samuelbelo** [nuxt/nuxt#23790]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.17.1
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      ssr, runtimeConfig, nitro, css, typescript, build, modules, components, imports, veeValidate, pinia, vite, app, vue, pwa
- Runtime Modules:  @nuxt/devtools@1.0.0, nuxt-icon@0.5.0, @pinia/nuxt@0.5.1, @pinia-plugin-persistedstate/nuxt@1.1.2, nuxt-time@0.1.1, @vueuse/nuxt@10.5.0, @kevinmarrec/nuxt-pwa@0.17.0, @vee-validate/nuxt@4.11.8, ()
- Build Modules:    -

### Reproduction

Stackblitz reproducible link: https://stackblitz.com/edit/nuxt-starter-wowrr5?file=package.json,app.vue,pages%2Findex.vue,nuxt.config.ts,stores%2FbackofficeStore.ts

### Describe the bug

Simply import an interface from a store file inside a SFC.

### Additional context

In a earlier version (3.7.4), import a interface or a type does not cause any issues. 

### Logs

```shell-script
500
The requested module '/_nuxt/stores/backofficeStore.ts' does not provide an export named 'NewsInterface'
```

**Comment by danielroe** [comment]
You should now use `import type`:

```ts
import type { NewsInterface } from '~/stores/backofficeStore';
import { useBackofficeStore } from '~/stores/backofficeStore';
```

See the bit in the release notes under `Type import changes`.

<img width="904" alt="CleanShot 2023-10-19 at 21 04 01@2x" src="https://github.com/nuxt/nuxt/assets/28706372/bcbe7af6-f791-426a-b910-7c7165efbba7">
