### ISSUE TITLE
fix: type error on `extends` in v3.8

### ISSUE THREAD

**Issue by dargmuesli** [nuxt/nuxt#23791]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      extends
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-bnn6ap?file=nuxt.config.ts

### Describe the bug

Upgrading to Nuxt 3.8 leads to a type issue for me: the `extends` key in `nuxt.config.ts` seems to not accept an array of strings anymore.

**Comment by danielroe** [comment]
For now you can use `// @ts-expect-error` to hide this warning.
