### ISSUE TITLE
npm run build regression

### ISSUE THREAD

**Issue by djixadin** [nuxt/nuxt#23798]
### Environment

- Operating System: Linux
- Node Version:     v18.18.1
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  npm@9.8.1
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

cant reproruce

### Describe the bug

in version 3.7.4. when building application on a server rollup used to have same hash with the same repo and same branch.. on 3.8 the hash is different even though files are the same.. tried npx nuxi cleanup but its not a cache thing. the hash is different and js scripts dont load on frontend. its a bunch of 404 errors

**Comment by djixadin** [comment]
reproduction? just run npm run build 2 times one after the onther and check .nuxt/dist/client/_nuxt hashes

**Comment by danielroe** [comment]
You say 'js scripts don't load on front-end'. I can't reproduce this. Would you provide a runnable reproduction?

**Comment by djixadin** [comment]
They don't load for me on multiple machines. the problem is that the rollup content hash is no longer content hash but appears to be a random generated string. It changes on every build even if the content of the components is the same. on 3.7.4 the hash in consistent

**Comment by danielroe** [comment]
The reason the hashes differ is that we now have a `buildId` that is different on each build, so the content is in fact different: https://github.com/nuxt/nuxt/pull/21641.

We can improve behaviour here when we implement https://github.com/nuxt/nuxt/issues/23392.
