### ISSUE TITLE
After upgrading Nuxt to version 3.8, modules are not functioning

### ISSUE THREAD

**Issue by selvinzr** [nuxt/nuxt#23805]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.18.2
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  npm@10.2.1
- Builder:          -
- User Config:      typescript, runtimeConfig, app, devtools, modules, strapi, tailwindcss
- Runtime Modules:  @bg-dev/nuxt-naiveui@1.5.1, @nuxtjs/tailwindcss@6.8.0, @nuxtjs/strapi@1.9.3, @pinia/nuxt@0.5.1
- Build Modules:    -
------------------------------

### Reproduction

npm install --save-dev @bg-dev/nuxt-naiveui
npm run dev

### Describe the bug

ERROR  Importing directly from module entry points is not allowed. [importing @bg-dev/nuxt-naiveui from app.vue]  

console：Uncaught SyntaxError: The requested module '/_nuxt/node_modules/unenv/runtime/mock/proxy.cjs?import' does not provide an export named 'ThemeConfig' (at app.vue:2:10)

**Comment by selvinzr** [comment]
> ### Environment
> * Operating System: Windows_NT
> * Node Version:     v18.18.2
> * Nuxt Version:     3.8.0
> * CLI Version:      3.9.1
> * Nitro Version:    2.7.0
> * Package Manager:  npm@10.2.1
> * Builder:          -
> * User Config:      typescript, runtimeConfig, app, devtools, modules, strapi, tailwindcss
> * Runtime Modules:  @bg-dev/nuxt-naiveui@1.5.1, @nuxtjs/tailwindcss@6.8.0, @nuxtjs/strapi@1.9.3, @pinia/nuxt@0.5.1
> * Build Modules:    -
> 
> ### Reproduction
> npm install --save-dev @bg-dev/nuxt-naiveui npm run dev
> 
> ### Describe the bug
> ERROR Importing directly from module entry points is not allowed. [importing @bg-dev/nuxt-naiveui from app.vue]
> 
> console：Uncaught SyntaxError: The requested module '/_nuxt/node_modules/unenv/runtime/mock/proxy.cjs?import' does not provide an export named 'ThemeConfig' (at app.vue:2:10)
> 
> ### Additional context
> _No response_
> 
> ### Logs
> _No response_

**Comment by klefix** [comment]
@selvinzr how did you resolve the issue? I am seeing this too, with `@vite-pwa/nuxt`
