### ISSUE TITLE
/pages/index.vue How to create a sub-route

### ISSUE THREAD

**Issue by facexyy** [nuxt/nuxt#23804]
### Describe the feature

Please tell me how should I create a sub-route for /pages/index.vue
/pages/index/index.vue
This may cause some conflicts

Example
/pages/home.vue
Create sub-route
/page/home/index.vue
/page/home/two.vue

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
You can do this:

```
pages/index.vue
pages/index/index.vue.
```

See more at https://nuxt.com/docs/guide/directory-structure/pages#nested-routes.
