### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by pkmco** [nuxt/nuxt#23803]
### Environment

![image](https://github.com/nuxt/nuxt/assets/142568325/07c6c243-50db-4de9-877b-38bd148afd88)
$ nuxt prepare

 ERROR                                                                                                                                                                                               9:25:51 AM

Vue packages version mismatch:

- vue@3.3.4
- vue-server-renderer@2.7.14

This may cause things to work incorrectly. Make sure to use the same version for both.

  Vue packages version mismatch:

  - vue@3.3.4
  - vue-server-renderer@2.7.14

  This may cause things to work incorrectly. Make sure to use the same version for both.

### Reproduction

When running **_yarn install_**

### Describe the bug

$ nuxt prepare

 ERROR                                                                                                                                                                                               9:25:51 AM

Vue packages version mismatch:

- vue@3.3.4
- vue-server-renderer@2.7.14

This may cause things to work incorrectly. Make sure to use the same version for both.

  Vue packages version mismatch:

  - vue@3.3.4
  - vue-server-renderer@2.7.14

  This may cause things to work incorrectly. Make sure to use the same version for both.

**Comment by pkmco** [comment]
I cant but here the error i get when i run yarn install yarn install
yarn install v1.22.19
warning ../../../package.json: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
warning vscode-languageclient@7.0.0: The engine "vscode" appears to be invalid.
[3/4] Linking dependencies...
warning "@nuxtjs/algolia > vue-instantsearch@4.8.8" has unmet peer dependency "vue@^2.6.0 || >=3.0.0-rc.0".
warning " > vee-validate@4.8.3" has unmet peer dependency "vue@^3.0.0".
warning "@vueuse/core > vue-demi@0.13.11" has unmet peer dependency "vue@^3.0.0-0 || ^2.6.0".
warning "@nuxtjs/tailwindcss > @nuxt/postcss8 > css-loader@5.2.7" has unmet peer dependency "webpack@^4.27.0 || ^5.0.0".
warning "@nuxtjs/tailwindcss > @nuxt/postcss8 > postcss-loader@4.3.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > sass-loader@13.2.1" has unmet peer dependency "webpack@^5.0.0".
[4/4] Building fresh packages...
$ nuxt prepare
Nuxi 3.3.1                                                                                                                                                                                             09:40:54

 ERROR                                                                                                                                                                                                 09:40:54

Vue packages version mismatch:

- vue@3.3.4
- vue-server-renderer@2.7.14

This may cause things to work incorrectly. Make sure to use the same version for both.



  Vue packages version mismatch:

  - vue@3.3.4
  - vue-server-renderer@2.7.14

  This may cause things to work incorrectly. Make sure to use the same version for both.

  at Object.<anonymous> (/home/pk/node_modules/vue-server-renderer/index.js:8:9)
  at Module._compile (node:internal/modules/cjs/loader:1254:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
  at Module.load (node:internal/modules/cjs/loader:1117:32)
  at Module._load (node:internal/modules/cjs/loader:958:12)
  at Module.require (node:internal/modules/cjs/loader:1141:19)
  at require (node:internal/modules/cjs/helpers:110:18)
  at Object.<anonymous> (/home/pk/node_modules/@nuxt/vue-renderer/dist/vue-renderer.js:17:27)
  at Module._compile (node:internal/modules/cjs/loader:1254:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command. this only noticed from yesterday.

**Comment by danielroe** [comment]
You probably have a package installed that depends on Vue 2 or Nuxt 2.
