### ISSUE TITLE
Cannot find module 'node:util'

### ISSUE THREAD

**Issue by adnanafzal565** [nuxt/nuxt#23806]
### Environment

Cannot find module 'node:util'

### Reproduction

Cannot find module 'node:util'

### Describe the bug

Cannot find module 'node:util'

### Additional context

Cannot find module 'node:util'

### Logs

```shell-script
Cannot find module 'node:util'
```

**Comment by luc122c** [comment]
Try importing from [unenv/node/util](https://github.com/unjs/unenv/blob/main/src/runtime/node/util) instead. unenv will likely already be in your `node_modules`

**Comment by DrewLosing** [comment]
got the same issue
![CleanShot 2023-12-21 at 09 40 36@2x](https://github.com/nuxt/nuxt/assets/121428202/e5c6d0ee-ac9e-46bb-965e-8f40ea616746)

**Comment by slaveofcode** [comment]
in my case, this is solved using newest node (14.21) when running nuxt 2
