### ISSUE TITLE
command error

### ISSUE THREAD

**Issue by lzb-libra** [nuxt/nuxt#23816]
### Environment

win 11

### Reproduction

not required

### Describe the bug

D:\workstation\practices>pnpm dlx nuxi@latest init nuxt-test
Packages: +1
+
Progress: resolved 2, reused 1, downloaded 0, added 1, done

 WARN  Current version of Node.js (16.17.0) is unsupported and might cause issues.                                                                                                                                                                                   17:45:32
       Please upgrade to a compatible version >= 18.0.0.

 ERROR  Error: Failed to download template from registry: request to https://raw.githubusercontent.com/nuxt/starter/templates/templates/v3.json failed, reason: getaddrinfo ENOENT raw.githubusercontent.com

### Additional context

I have tried multiple methods, including using a ladder

**Comment by danielroe** [comment]
You should use a newer version of Node, and it also looks like you might have an issue connecting to GitHub (where the template is stored). See https://github.com/nuxt/cli/issues/159 for some workarounds.
