### ISSUE TITLE
run dev error when using nuxt-electron mode Cannot read properties of undefined (reading 'entries')

### ISSUE THREAD

**Issue by Morii120** [nuxt/nuxt#23815]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.17.1
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  pnpm@8.6.12
- Builder:          -
- User Config:      devtools, modules, ssr, app, router, runtimeConfig, electron
- Runtime Modules:  nuxt-electron@0.6.0
- Build Modules:    -

### Reproduction

https://github.com/Morii120/nuxt_bug

### Describe the bug

That's the smallest copy you can download and run

There will be an error

Error message

Cannot read properties of undefined (reading 'entries')

![image](https://github.com/nuxt/nuxt/assets/13359932/ba3c7fe6-bec7-452e-90bb-55d2757c9e87)

**Comment by amplitudesxd** [comment]
I ran into the same, #23831 has a reproduction without the need for Electron. It's caused by the baseURL set by the nuxt-electron module.

**Comment by danielroe** [comment]
great; let's track it in that issue
