### ISSUE TITLE
Cannot find module ../middleware in ./.nuxt/nuxt-i18n/middleware.js

### ISSUE THREAD

**Issue by Andrej492** [nuxt/nuxt#23810]
### Environment

npx envinfo --system --npmPackages '{nuxt,@nuxt/*}' --binaries --browsers

### Reproduction

I am sorry but as this is a project for my company I cannot share whole code, though I will describe it.

### Describe the bug

So my package.json dependencies looks like this: 
```
  "dependencies": {
    "@nuxtjs/axios": "^5.13.6",
    "@nuxtjs/gtm": "^2.4.0",
    "@nuxtjs/i18n": "^7.3.1",
    "bootstrap": "^4.6.0",
    "core-js": "^3.8.3",
    "nuxt": "^2.16.2"
  },
``` 
So whenever I run npm run dev(build) there is added new folder to .nuxt folder which is nuxt-i18n. In that folder I have a file named middleware.js which looks like this: 
```
// @ts-ignore
import nuxtMiddleware from '../middleware'

/** @type {import('@nuxt/types').Middleware} */
const i18nMiddleware = async (context) => {
  const { app, isHMR } = context

  if (isHMR) {
    return
  }

  const [status, redirectPath, preserveQuery] = await app.i18n.__onNavigate(context.route)
  if (status && redirectPath) {
    const query = preserveQuery ? context.route.query : undefined
    context.redirect(status, redirectPath, query)
  }
}

nuxtMiddleware.nuxti18n = i18nMiddleware

``` 
. So and the error on build is: ❯ log friendly-errors › This relative module was not found:
❯ log friendly-errors › * ../middleware in ./.nuxt/nuxt-i18n/middleware.js . 
Therefore as there is realy not that module in .nuxt I am facing an error that unless I delete first and the last row of the code my app won't build at all. I tried with different versions of node ( 14.15, 10.21, 16.9, 18.1...) Any help would be appreciated :)

**Comment by danielroe** [comment]
This looks like an issue with `@nuxtjs/i18n` rather than Nuxt. Maybe you could raise an issue there instead?
