### ISSUE TITLE
when you click a nuxtlink more times, the page is white

### ISSUE THREAD

**Issue by 17biubiu** [nuxt/nuxt#23814]
### Environment

chrome

### Reproduction

1、when you set nuxtlink with no-prefetch
2、continue click it 

### Describe the bug

![image](https://github.com/nuxt/nuxt/assets/13295895/69fde553-076a-4968-bea7-278d9f83134c)

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/13309 and https://github.com/nuxt/nuxt/issues/22900.
