### ISSUE TITLE
`v-html` does not work in `<NuxtLink>`

### ISSUE THREAD

**Issue by stone-zeng** [nuxt/nuxt#23823]
### Environment

- Operating System: Darwin
- Node Version:     v20.8.1
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  pnpm@8.9.2
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-rojasq?file=app.vue

App.vue:

```vue
<script setup lang="ts">
const svg = `
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="100">
    <circle cx="50" cy="50" r="50" />
  </svg>
`;
</script>

<template>
  <ul>
    <li><NuxtLink v-html="'Text'"></NuxtLink></li>
    <li><NuxtLink v-html="svg"></NuxtLink></li>
    <li v-html="'Text'"></li>
    <li v-html="svg"></li>
  </ul>
</template>
```

### Describe the bug

When used together `<NuxtLink>`, the content in `v-html` does not show in the rendered link, only leaving an empty `<a>` element.

**Comment by warflash** [comment]
From the issue you linked https://github.com/vuejs/core/issues/6553#issuecomment-1232468857 that seems like it's not something that'll be changed anytime soon. As an alternative you could just put the v-text/v-html in a span in the component:
```html
<li>
      <NuxtLink to="/">
        <span v-html="'Text'"> </span>
      </NuxtLink>
    </li>
    <li>
      <NuxtLink to="/">
        <span v-html="svg"> </span>
      </NuxtLink>
    </li>
```

**Comment by Lehoczky** [comment]
I don't think this is an upstream bug, instead just how vue works. The example that @warflash gave is an easy solution, even though I would personally advise against using `v-html` if you can.

In your example, the svg can be part of the template, or even be extracted to a component:

```vue
<template>
  <NuxtLink to="/">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="100">
         <circle cx="50" cy="50" r="50" />
       </svg>
   </NuxtLint>
</template
```
