### ISSUE TITLE
onload callback from useHead doesn't get called when the page is refreshed or opened directly 

### ISSUE THREAD

**Issue by cosbgn** [nuxt/nuxt#23820]
### Environment

nuxt 3.8

### Reproduction

https://stackblitz.com/edit/github-dia771?file=pages%2Ftest.vue,pages%2Findex.vue

### Describe the bug

onload get's called only with nuxt-link not with href or opening the page directly. 

If you open `/test/` and refresh the page onload doesn't get called. Also if you open directly `/test` it doesn't. The only way it gets called is when navigating with `nuxt-link`

Expected behavior is that every time I open the page, like clicking on a link, onload gets called.

**Comment by danielroe** [comment]
I wouldn't consider this a bug; by the time unhead has hydrated the page the onload event has already fired.

Maybe @harlan-zw has another idea.

**Comment by harlan-zw** [comment]
This is fixed in the 1.8.0 version which is currently in a beta release. You can opt-in using `resolutions` otherwise will be available quite soon!

**Comment by cosbgn** [comment]
Thanks!
