### ISSUE TITLE
App Manifests break Histoire

### ISSUE THREAD

**Issue by happy-turtle** [nuxt/nuxt#23826]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-ypcyaj

### Describe the bug

An update to Nuxt 3.8.0 breaks story import in Histoire with a fetch error.
Disabling the app manifests fixes the errors.
```
  experimental: {
    appManifest: false
  },
```

### Logs

```shell-script
Error while collecting story /home/projects/jvmixpakw.github/stories/SampleStorie.story.vue:
FetchError: [GET] "/builds/meta/test.json": 404 Cannot find any path matching /builds/meta/test.json.
    at async $fetch2 (/home/projects/jvmixpakw.github/node_modules/ofetch/dist/shared/ofetch.00501375.mjs:278:15)
```

**Comment by happy-turtle** [comment]
Is this getting fixed in Histoire instead with https://github.com/histoire-dev/histoire/commit/05bcd28cd5d13012e2bdb9ae93f2a0f6d69e1ef5?

**Comment by danielroe** [comment]
yes, exactly.

**Comment by francisashley** [comment]
Hi, any news when this patch will be deployed?
