### ISSUE TITLE
useFetch calls repeat when sending and modifying reactive objects

### ISSUE THREAD

**Issue by command-tab** [nuxt/nuxt#23837]
### Environment

- Nuxt 3.7.4 and Nuxt 3.8.0
- Node 18.16.0
- macOS Sonoma 14.0 on Apple Silicon M2 Pro

### Reproduction

https://stackblitz.com/edit/nuxt-starter-skcrhm?file=app.vue

-or-

```vue
<template>
  <div>
    <input type="text" v-model="body.name" placeholder="Anything" />
    <button class="btn btn-primary" @click="sendIt">Send</button>
  </div>
</template>

<script setup>
const body = reactive({
  foo: 'bar',
  name: '',
});

const sendIt = async () => {
  const { data, error } = await useFetch('https://httpbin.org/anything', {
    method: 'POST',
    body,
  });
};
</script>
```

### Describe the bug

When POSTing a reactive Vue object using `useFetch`, I find that further modification of the object's properties causes the `useFetch` call to unexpectedly fire again for each modification.

In the above example, I have a reactive object named `body`, and I use `useFetch` to POST it somewhere. Afterward, if I modify the object using an `<input>` with `v-model` binding, that `useFetch` POST fires again for each keypress. If I click Send to trigger `useFetch` once more, then modify the object's properties yet again, the `useFetch` calls invoked by those modifications have doubled up, and they continue to double with each click of the Send button.

**Comment by danielroe** [comment]
This is intentional (that `useFetch` watches reactive objects passed in).

Your issue is caused by the fact that you are using `useFetch` within an event handler and therefore instantiating new copies of it every time that handler is called. You shouldn't do so as it is a composable meant to be called once only in `setup`; instead you can either use `$fetch` or something like this:

```ts
const body = reactive({
  foo: 'bar',
  name: '',
});


const { data, error, execute: sendIt } = await useFetch('https://httpbin.org/anything', {
  method: 'POST',
  immediate: false,
  body,
});
```

**Comment by command-tab** [comment]
Huh, interesting. I'll have to re-think how I've been using `useFetch`. I've been using it wrong the whole time.

Sorry, one more quick question along those lines: If I want to GET some data in `setup` and _also_ PUT it back later on, can I use `$fetch` for both the initial `setup` as well as future requests? i.e. Is SSR and hydration aware of `$fetch` calls in `setup`?

Thanks for your speedy help!

**Comment by danielroe** [comment]
No, `$fetch` won't handle passing data in the payload.
