### ISSUE TITLE
add type support for body and query to server api

### ISSUE THREAD

**Issue by minkoonim** [nuxt/nuxt#23833]
### Describe the feature

I've always appreciated the automatic type inference of the return type in server-side "get" APIs provided by Nuxt. 
However, I noticed that there doesn't seem to be support for request parameters. 
This feature could enhance developer experience by providing type safety and autocompletion for request parameters.

Consider the following example:

```
// api/auth/login.post.ts
export default defineEventHandler<{body: {username: string, password: string}}>(async (event) => {
  const { username, password } = await getBody(event) // typed!
  ...
});
```

also for client side:

```
<!-- page/login.vue -->
<script setup lang="ts">
const username = ref('');
const password = ref('');

async function login() {
  await $fetch('/api/auth/login', { 
    method: 'POST', 
    body: { username: username.value, someWrongKey: password.value }
  }); // typed!
}
</script>
```

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/23009.
