### ISSUE TITLE
使用Element plus - Menu 菜单 问题

### ISSUE THREAD

**Issue by lcyhyl** [nuxt/nuxt#23849]
### Environment

Working directory: D:/Vue3+Ts+Nuxt3打造SSR/duyun-index                                                                                                       19:56:57
Nuxt project info:                                                                                                                                           19:56:57

------------------------------
- Operating System: Windows_NT
- Node Version:     v16.20.1
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  pnpm@8.1.1
- Builder:          -
- User Config:      devtools, css, modules
- Runtime Modules:  @element-plus/nuxt@1.0.6
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-tdzdej?file=nuxt.config.ts,app.vue

### Describe the bug

当<el-sub-menu> 又嵌套sub-menu 时候，无法正常渲染

**Comment by warflash** [comment]
Like the element plus docs suggest you need to wrap the entire menu in `<client-only>` tags. -> https://element-plus.org/en-US/component/menu.html
![image](https://github.com/nuxt/nuxt/assets/22006082/f88c689f-1e9d-44a6-805b-42fd98260947)
