### ISSUE TITLE
Issue with typescript auto import from devDependencies

### ISSUE THREAD

**Issue by Bombastickj** [nuxt/nuxt#23842]
### Environment

Nuxt project info:                                                                                                                                            01:01:00

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools, typescript
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-mdasny?file=app.vue

### Describe the bug

It seems like nuxt v3.8.0 is not auto importing devDependencies correctly. I am using the google maps api and typescript throws an error that 'google' is not defined. Worked until v3.7.4

**Comment by warflash** [comment]
Thanks, that sounds similar to https://github.com/nuxt/nuxt/issues/23733 but not entirely sure so keeping open it for now.

**Comment by danielroe** [comment]
Nuxt automatically sets `compilerOptions.types` to an empty array for performance - so TypeScript won't scan your dependencies for types at all. If you have specific types you want included, just set this in your `nuxt.config`:

```ts
export default defineNuxtConfig({
  typescript: {
    tsConfig: {
      compilerOptions: {
        types: ['@types/google.maps']
      }
    },
  },
});
```
