### ISSUE TITLE
$fetch is not defined

### ISSUE THREAD

**Issue by citrusjunoss** [nuxt/nuxt#23848]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v16.20.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devServer, telemetry, imports, srcDir, app, runtimeConfig, css, vite, modules, vant, hooks, nitro, build
- Runtime Modules:  @qzd-h5-ui/nuxt@1.0.3, @vueuse/nuxt@10.5.0, @pinia/nuxt@0.4.11, @pinia-plugin-persistedstate/nuxt@1.1.2, nuxt-windicss@2.6.1
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-zr9tkf-upvvdt?file=utils%2Ffetch.ts

### Describe the bug

The browser throws an error "$fetch is not defined". 

I need to call an API when initializing on the client side. I wrapped $fetch and exported a fetch function, calling the API request method in plugins/1.init.client.ts.

### Additional context

<img width="1952" alt="image" src="https://github.com/nuxt/nuxt/assets/18432488/d746bf8f-a844-40a5-9706-94852349b194">

### Logs

```shell-script
fetch.ts:1 Uncaught ReferenceError: $fetch is not defined
    at fetch.ts:1:14
```

**Comment by danielroe** [comment]
cc: @antfu

**Comment by antfu** [comment]
`$fetch` is actually never auto-imported, but rather, it's a global assignment: https://github.com/nuxt/nuxt/blob/755cf2053489e7d324abd4d43a73497d874e7754/packages/nuxt/src/app/entry.ts#L21-L26

While the case here is that the module has been imported in `entry.ts` before the `globalThis.$fetch = ` assignment.

A few solutions:

- Register it in auto-import entry - we would need a virtual file hosting that instance as `import { $fetch } from 'ofetch'` is not an equalivent because the lack of baseUrl.

**Comment by citrusjunoss** [comment]
Interim solutions:
Manually import $fetch
<img width="823" alt="image" src="https://github.com/nuxt/nuxt/assets/18432488/a2ef6d86-5684-41fb-99ce-76363e27b6b6">

**Comment by pi0** [comment]
For clarification, I'm not against this (factory) pattern but belive the root cause could be fixed differently.

Also following https://github.com/nuxt/nuxt/issues/14736, we can start with creating a stable `defineFetch` utility that lazily calls `$fetch` to avoid this ordering issue.

**Comment by danielroe** [comment]
I think it's still worth it to avoid reliance on global variables, and to provide rollup with the right information about dependencies.

**Comment by pi0** [comment]
As explained before, `fetch` and `$fetch` are initialized by the nitro app entry which is expected to be executed first. They are not like any other utility.

Using the auto import feature which is essentially a rollup transform plugin itself only works around this issue for bundled code that passes through rollup and can create future limitations and regressions if we go this path.

Nevertheless, I really like to fix this issue and unblock the supporting fetch factory pattern for Nuxt. 

Currently looking for a minimal reproduction ([this](https://stackblitz.com/edit/unjs-nitro-epop52?file=utils%2Findex.ts,routes%2Findex.ts,routes%2Ftest.ts&title=Nitro%20Starter) with nitro alone works for example) before attempting to fix it upstream.

**Comment by danielroe** [comment]
> Create a virtual file and run it beforehand, similar to #build/paths.mjs

Yes, this is what I was suggesting, assuming this virtual file supplies the auto-import of `$fetch`. 👌

**Comment by antfu** [comment]
Sounds good. In the future, I think `createFetch` (which can be auto-imported) would be better than `$fetch.create` indeed.
