### ISSUE TITLE
[webpack-builder] Unable to use the out-of-the-box support for  jsx syntax 

### ISSUE THREAD

**Issue by mhdSid** [nuxt/nuxt#23844]
### Environment

Nuxt 3.8.0

### Reproduction

Just use nuxt 3.8.0 and try using jsx syntax through a layout or some component.
https://codesandbox.io/s/mystifying-haze-zyv2dh?file=/pages/index.vue

### Describe the bug

The jsx tags such as div and img are not being compiled into corresponding HTML elements.
I used jsx inside script with setup attribute and lang=“jsx”

### Additional context
message: 'React is not defined'

_No response_

**Comment by mhdSid** [comment]
## Reproduction link
https://codesandbox.io/s/mystifying-haze-zyv2dh?file=/pages/index.vue

**Comment by gjssss** [comment]
@mhdSid Hey! I don't find any error or message. I haven't changed any code. : >
![image](https://github.com/nuxt/nuxt/assets/74909529/e080717a-7c63-4885-81b0-37181686feba)
https://codesandbox.io/p/sandbox/serene-ioana-47zyhf?welcome=true
It work normally. May be?

**Comment by mhdSid** [comment]
Im currently using builder-webpack and it uses default tsx to transpile tsx/jsx code which injects React.createElement.
I solved it by removing Nuxt's default config for jsx/tsx for webpack (the code is not optimal but at least the JSX gets converted into code that uses "h" from vue instead of React.createElement):

```
import { defineNuxtModule, installModule, extendWebpackConfig } from '@nuxt/kit'

export default defineNuxtModule({
  async setup () {
    extendWebpackConfig(config => {
      console.log(config.module.rules)
      const ruleIndex = 4 // config.module.rules.findIndex(rule => String(rule.test) === String('/\.m?[jt]sx$/'))
      config.module.rules[ruleIndex] = {
        test: /\.m?[jt]sx$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: {
            plugins: ['@vue/babel-plugin-jsx'],
            presets: [
              [
                '@babel/preset-env',
                {
                  targets: process.server ? { node: 'current' } : { ie: 11 },
                  corejs: { version: 3 }
                }
              ]
            ]
          }
        }
      }
    })
  }
})

```

**Comment by mhdSid** [comment]
Let me find a time to create a PR for this..

**Comment by danielroe** [comment]
This will be resolved in the next Nuxt release, but for now you can resolve with:

```ts
export default defineNuxtConfig({
  builder: 'webpack',
  webpack: {
    loaders: {
      esbuild: {
        jsxFactory: 'h',
        jsxFragment: 'Fragment',
        tsconfigRaw: '{}',
      }
    }
  }
})
```
