### ISSUE TITLE
Error <no response> _fetch is not a function after setting NITRO_PRESET=node_cluster

### ISSUE THREAD

**Issue by 1129zaj** [nuxt/nuxt#23854]
### Environment

Error <no response> _fetch is not a function after setting NITRO_PRESET=node_cluster

### Reproduction

Error <no response> _fetch is not a function after setting NITRO_PRESET=node_cluster

### Describe the bug

Error <no response> _fetch is not a function after setting NITRO_PRESET=node_cluster

**Comment by danielroe** [comment]
Would you raise an issue with a reproduction at https://github.com/unjs/nitro ? 🙏
