### ISSUE TITLE
navigateTo doesn't work in useAsyncData server side

### ISSUE THREAD

**Issue by joffreyBerrier** [nuxt/nuxt#23867]
### Environment

- Operating System: `Darwin`
- Node Version:     `v19.9.0`
- Nuxt Version:     `3.8.0`
- CLI Version:      `3.9.1`
- Nitro Version:    `2.7.0`
- Package Manager:  `npm@9.8.0`
- Builder:          `-`
- User Config:      `experimental`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/joffreyBerrier/nuxt-redirect

### Describe the bug

I want to redirect the user when he arrives at a page (referenced only via server-side). This page must not be an error and the navigateTo should terminate the page execution.

### Additional context

On my house rental site, pages may no longer be available to the user but exist in Google. I need to redirect the user to the house destination search page.

**Comment by luc122c** [comment]
It should work if you `return` the `navgateTo`.

```ts
	return navigateTo('/', { redirectCode: 301 })
```

[See docs](https://nuxt.com/docs/guide/directory-structure/middleware#usage)

**Comment by joffreyBerrier** [comment]
Hi @luc122c I have try but it doesn't work with `return` or `await` or `return await`
https://github.com/joffreyBerrier/nuxt-redirect/commit/57470a3bc6e34ec4fc4dab6760c799c60c6ae524

**Comment by joffreyBerrier** [comment]
I'm also trying to redirect in server side using `sendRedirect` but it also doesn't work

**Comment by joffreyBerrier** [comment]
@luc122c sorry it works with middleware, but with a middleware I can't share data with the reste of the code ? The middleware will run every time, the trick is that when it works, I have to make another api call to get the information.
Do you have an idea

**Comment by manniL** [comment]
You'd want to check `error.value` as you've tried in one of your approaches. [Working example](https://stackblitz.com/edit/nuxt-23867)

**Comment by lukaszarpak** [comment]
@manniL it doesn't work with `external: true`. Example [here](https://stackblitz.com/edit/nuxt-23867-zrabpj?file=pages%2Findex.vue)

**Comment by manniL** [comment]
@lukaszarpak works fine locally, just stackblitz doesn't allow the redirect

**Comment by lukaszarpak** [comment]
@manniL you're right, I apologise for the confusion
