### ISSUE TITLE
Wrong `etag` and `last-modified` header when cache is enabled

### ISSUE THREAD

**Issue by everyx** [nuxt/nuxt#23877]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.2
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  pnpm@8.9.0
- Builder:          -
- User Config:      typescript, $development, runtimeConfig, build, nitro, modules, unocss, i18n, image, vue, routeRules
- Runtime Modules:  @unocss/nuxt@0.56.5, @nuxtjs/i18n@8.0.0-rc.3, @nuxt/image@1.0.0
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-fk7sob

### Describe the bug

I want to set up cache rules, but it is not working. I got `undefined` value for `etag` and `last-modified` header.

```ts
    routeRules: {
      '/**': { swr: 1 },
    },
```

**Comment by danielroe** [comment]
Would you open an issue in https://github.com/unjs/nitro instead? :pray:

**Comment by pi0** [comment]
Thanks for the issue report. It seems an upstream bug indeed. Moved to https://github.com/unjs/nitro/issues/1850
