### ISSUE TITLE
Cannot read properties of null (reading 'parentNode') with client Component and OnMounted

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/nuxt#23876]
### Environment

Working directory: /home/projects/nuxt-starter-3ukexv                                                             10:21:36
Nuxt project info:                                                                                                10:21:36

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                       10:21:36

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

### Reproduction

https://stackblitz.com/edit/nuxt-starter-3ukexv?file=pages%2Findex.vue

### Describe the bug

We are upgrading from 3.7.4 to 3.8.0 and we have a lot of errors "Cannot read properties of null (reading 'parentNode')"

This errors doesnt appears with 3.7.4

One of them you can see in the reproduction link.

The most of them, are related with .client components

**Comment by huang-julien** [comment]
hmmm... can your try by pinning the version to 3.7.4 ?
I'll take a look at this issue

**Comment by beniamin83** [comment]
I have the same error after upgrade to Nuxt 3.8.0
I have a component name `Xyz.client.vue` and it was causing the error.
I changed the component usage to
```
<ClientOnly>
    <Xyz />
</ClientOnly>
```
This solution works temporarily.

**Comment by agracia-foticos** [comment]
> I have the same error after upgrade to Nuxt 3.8.0 I have a component name `Xyz.client.vue` and it was causing the error. I changed the component usage to
> 
> ```
> <ClientOnly>
>     <Xyz />
> </ClientOnly>
> ```
> 
> This solution works temporarily.

This solution also works for me, but its redundant
