### ISSUE TITLE
Server middleware triggered even when not calling server endpoints

### ISSUE THREAD

**Issue by IvanBernatovic** [nuxt/nuxt#23883]
### Environment

Working directory: /home/projects/github-dlbtlr
Nuxt project info:

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      ssr, devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-dlbtlr

Try visiting pages on / or /foo. They will both crash because `server/middleware/test.ts` is executed even though app has `ssr: false` in Nuxt config and neither page is calling any server endpoint.

### Describe the bug

When visiting Nuxt page (either / or /foo) the server middleware is executed. I am not calling any server endpoint so I don't want server middleware to get executed. I expect server middleware to get executed only when I'm calling server endpoints (defined inside `server/api` or `server/middleware` directories). This is also stated [in docs](https://nuxt.com/docs/guide/directory-structure/server#server-middleware):

> Middleware handlers will run on every request before any other server route to add or check headers, log requests, or extend the event's request object.

### Additional context

I'm not sure if this is intended behaviour or not but docs suggest this shouldn't happen and I don't see any option to disable it.

**Comment by danielroe** [comment]
This is intended behaviour. Server middleware will be called on every request. The part of Nuxt that renders Vue into HTML is just another server handler. `ssr: false` only affects what kind of HTML is rendered by that handler, not whether there is a server handler or not.

**Comment by danielroe** [comment]
A request comes in.

- first it hits server middleware - they all run
- then it hits the router which tries to find a match.
- if it matches an api route, then we return the result of that route
- if it doesn't we fall through to Nuxt which renders everything else

So there's no way to know in advance (in the middleware) whether or not it will be rendered by Nuxt or not.

I'm not sure why you would have a server middleware at all if you want the client to render everything.

**Comment by IvanBernatovic** [comment]
@danielroe Thanks for the explanation.

> I'm not sure why you would have a server middleware at all if you want the client to render everything.

Because I'd like to have a client-side rendered Nuxt app that uses endpoints defined in `server/api`. I want to use server middleware only on those `server/api` endpoints because I'm doing some special authorization checks that I don't want to run when rendering client pages.

This is not a deal breaker to me as I can extract middleware logic to a function and use it inside every handler but it's definitely not expected if your perception is that `server/api` routes belong to an API server that's not coupled with page rendering.

**Comment by raf202** [comment]
@IvanBernatovic how did you solve this? I'm having the same issue

**Comment by IvanBernatovic** [comment]
> [@IvanBernatovic](https://github.com/IvanBernatovic) how did you solve this? I'm having the same issue

Didn't really solve it properly but for middleware that should only run for API roues I do this:
```ts
export default defineEventHandler(async (event) => {
  const { path } = event
  
  if (!path.startsWith('api')) {
    return
  }

  // middleware code from this line runs only in API routes
});
```

Not ideal but good enough for most situations.

**Comment by asadkhalid305** [comment]
I have a similar use case. I want the server middleware to execute for specific routes when they are called. 

I did find [this example in H3 docs](https://github.com/unjs/h3/blob/main/examples/handler-middleware.ts 
) which works very well. However, I am not sure if is this the ideal solution or recommended way of doing it. 

What do you guys think?
