### ISSUE TITLE
About the isLocalFetch variable of useFetch

### ISSUE THREAD

**Issue by KeJunMao** [nuxt/nuxt#23880]
### Describe the feature

https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/app/composables/fetch.ts#L143-L148C6

Currently, `isLocalFetch` is true when the request starts with `/`, and if I redefine `globalThis.$fetch` and set `baseURL`, then it's wrong.

When I tried to fix this I found that `ofetch` couldn't get the `options.baseURL` for the current instance, so I open https://github.com/unjs/ofetch/issues/303#issuecomment-1774885204

cc @pi0 

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
You should definitely not redefine `globalThis.$fetch`. But I do think we need to update this so we check for the baseURL.

**Comment by KeJunMao** [comment]
> You should definitely not redefine `globalThis.$fetch`. But I do think we need to update this so we check for the baseURL.

The root cause is that we lack a factory function for `useFetch`(#14736), and writing types for it is painful, but rewriting `globalThis.fetch` is relatively simple

**Comment by danielroe** [comment]
You can straightforwardly pass `$fetch` as an option to `useFetch`.

**Comment by KeJunMao** [comment]
Yes, I could, but that would never execute `useRequestFetch`, even if the baseURL of the fetch instance passed is '/'

**Comment by danielroe** [comment]
yes, because you're overriding the default behaviour. But you could pass your own `useRequestFetch()` in if on the server.
