### ISSUE TITLE
3.8.0 Tests Error - FetchError: [GET] "/_nuxt/builds/meta/test.json": 404 Cannot find any path matching /_nuxt/builds/meta/test.json.

### ISSUE THREAD

**Issue by silverbackdan** [nuxt/nuxt#23890]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.18.0`
- Nuxt Version:     `3.8.0`
- CLI Version:      `3.9.1`
- Nitro Version:    `2.7.0`
- Package Manager:  `pnpm@8.9.2`
- Builder:          `-`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/components-web-app/cwa-nuxt-module

run `pnpm test`

### Describe the bug

I'm getting errors originating from `nuxt/dist/app/composables/manifest.js::fetchManifest` after upgrading to 3.8.0 when running tests for my module using vitest.

I've also got `nuxt-vitest` installed. `vitest` is locked to 0.31.1 as any other versions cause errors currently. (Or still did a month or so ago when I tried to update).

Is there an update that I need to be doing to run tests in my module that runs 3.8.0?

**Comment by danielroe** [comment]
What version of `nuxt-vitest` are you on?

**Comment by silverbackdan** [comment]
For now, mitigation is to include
```
experimental: {
  appManifest: false
}
```
in the nuxt config. Looks like the buildId is set to `test` because of the `test` option being set by `nuxt-vitest` 

I'm sorry I didn't include the full path of the 404 error:
```
FetchError: [GET] "/_nuxt/builds/meta/test.json": 404 Cannot find any path matching /_nuxt/builds/meta/test.json.
```

**Comment by silverbackdan** [comment]
It appears this is an issue in any file sorry, it was not just 1 test file - but I can no longer mock the vue watch or onMounted implementation.

I'll go and check any updates that may have happened in nuxt-vitest.

Thanks Daniel
