### ISSUE TITLE
useNuxtApp can be accessed directly from the browser console

### ISSUE THREAD

**Issue by chendaozhun** [nuxt/nuxt#23907]
### Describe the feature

It can be displayed during debugging and try not to display internal APIs after packaging is completed

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
This is intended behaviour. What do you see as the downside of this?

**Comment by chendaozhun** [comment]
I can access all my routes through the useNuxtApp, and I don't want anyone to see all my routes information；
so I always feel like something terrible will happen..

**Comment by chendaozhun** [comment]
If I want to customize a plugin to remove nuxt related information from the browser console, what should I do? Thank you

**Comment by cuevana8** [comment]
+1 Like ..[.](https://github.com/flslib/fl-studio-cracked)[@@@](https://github.com/nuxt/nuxt/issues/23907#issue-1958583443)

**Comment by manniL** [comment]
Happily referencing my comment from the Nuxt 2 `$nuxt` feature [here](https://github.com/nuxt/nuxt/issues/4720#issuecomment-454411075), as well as the mention during my recent talk on [Slide 6 and 7](https://talk-nuxt-hidden-gems-nuxt-nation.vercel.app/6?clicks=3).

This is *not* a security risk. If someone downloads your JavaScript (which is publicly served), they can do *exactly the same thing* with a little more effort.

**Comment by chendaozhun** [comment]
Thank you, I've been thinking too much
