### ISSUE TITLE
Inconsistent Blank State and Mount Timing Issues When Using PageTransitions in Nuxt 3

### ISSUE THREAD

**Issue by citrusjunoss** [nuxt/nuxt#23915]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v16.20.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devServer, telemetry, imports, srcDir, app, router, runtimeConfig, css, vite, modules, nitro, routeRules, build
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/~/github.com/citrusjunoss/nuxt-demo

### Describe the bug

There is an inconsistent blank state between the two pages when pageTransitions is set to true in the official demo. Here is an issue - during the animation, the next page's mounted event has already been triggered but the DOM has not rendered yet. Operating on the DOM in the mounted event will lead to errors.
![changeCase](https://github.com/nuxt/nuxt/assets/18432488/8f502b81-5283-419a-bc94-f18a127a044c)

**Comment by danielroe** [comment]
Same issue as https://github.com/nuxt/nuxt/issues/13471 - but I'm sure you'll be delighted to hear that this should now be resolved in vue 3.3.7.

**Comment by citrusjunoss** [comment]
> Same issue as #13471 - but I'm sure you'll be delighted to hear that this should now be resolved in vue 3.3.7.

There is another possibility that this is caused by incorrect usage on my part rather than the component itself. In the official pageTransition demo, both pages clearly exist simultaneously, making the transition effect smoother. However, in my humble demo, the two pages cannot coexist, which results in an obvious blank screen during the animation rather than one page gradually disappearing as the other fades in.

I would be grateful if experts could advise if I may have used pageTransitions incorrectly rather than the component being flawed. The official demo transitions smoothly because both pages render simultaneously, but my ignorant attempt causes the pages to switch completely instead of having a blended transition. The blank state is likely from my inexperienced usage rather than issues with the excellent component itself.

![about](https://github.com/nuxt/nuxt/assets/18432488/51379f3d-9ebb-47cf-8e66-3517b6200c41)
