### ISSUE TITLE
Add Option to Disable Asset Validation*

### ISSUE THREAD

**Issue by rathahin** [nuxt/nuxt#23910]
### Describe the feature

**Description:**

Currently, Vite performs asset validation during the build process. While asset validation serves a useful purpose in many scenarios, it can be inconvenient for projects where dynamic loading and runtime asset management are essential. This feature request proposes the addition of an `assetsValidate` option to the Vite configuration, allowing users to choose whether or not asset validation should occur during the build process.

**Use Case:**

In certain projects, especially those where assets, such as images, can change dynamically on the production server, disabling asset validation is desirable. This option would enable users to handle asset loading entirely at runtime, without the build process imposing any checks on the assets.

**Benefits:**

- Improved flexibility for projects that require dynamic asset loading.
- Avoids unnecessary validation steps during the build process for assets that may change.
- Aligns Vite's behavior with specific use cases where asset validation is not required.

**Additional Context:**

Detailed discussions and requests from the community have highlighted scenarios where the ability to disable asset validation would be highly valuable. By implementing this feature, Vite can accommodate a broader range of project requirements while maintaining its performance advantages.

**Proposed Implementation:**

Introduce a new configuration option in `vite.config.js` called `assetsValidate` that can be set to `true` or `false`. When set to `true` (default behavior), asset validation occurs as usual during the build process. When set to `false`, Vite skips asset validation, allowing users to manage asset loading at runtime as needed.

**Example:**

```javascript
// In vite.config.js
export default {
  // ...other Vite configuration options

  build: {
    assetsValidate: false, // Disable asset validation
  },
};


### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
I think you might have meant to create this issue upstream in https://github.com/vitejs/vite.

This is already possible in Nuxt by placing your assets in the `/public` folder.
