### ISSUE TITLE
After nuxt3 is packaged and run after viewing the web source code, can the style be introduced through the connection?

### ISSUE THREAD

**Issue by 983796605** [nuxt/nuxt#23946]
### Describe the feature

After nuxt3 is packaged and run after viewing the web source code, can the style be introduced through the connection?
![image](https://github.com/nuxt/nuxt/assets/59547510/749b0f35-6eef-4a5f-84f1-96ffc1bca854)

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [ ] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [ ] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
I'm not sure what you're asking. Can you explain more?

**Comment by 983796605** [comment]
> I'm not sure what you're asking. Can you explain more?

After packaging, can css styles be packaged into files and imported using the link tag?

**Comment by 983796605** [comment]
> I'm not sure what you're asking. Can you explain more?

Can css styles be packaged into files and imported using the link tag? Instead of inserting it into the head with a style tag like the one I posted.

**Comment by madebyfabian** [comment]
I am currently archiving this by setting `inlineSSRStyles` to `false`. https://nuxt.com/docs/guide/going-further/experimental-features#inlinessrstyles. Be aware that this could have some side effects I am currently not aware of.

**Comment by danielroe** [comment]
Yes, that's exactly right. 👌  If you don't want the styles inlined it can be turned off as @madebyfabian says.

**Comment by 983796605** [comment]
> I am currently archiving this by setting `inlineSSRStyles` to `false`. https://nuxt.com/docs/guide/going-further/experimental-features#inlinessrstyles. Be aware that this could have some side effects I am currently not aware of.

Perfect solution. Thank you very much.

**Comment by 983796605** [comment]
> Yes, that's exactly right. 👌 If you don't want the styles inlined it can be turned off as @madebyfabian says.

Thank you very much.

**Comment by 983796605** [comment]
Another problem is that the.output file after build is super large. node_modules exists in the server folder, is this normal?

**Comment by 983796605** [comment]
It takes a long time to upload to the server.

**Comment by danielroe** [comment]
Yes, it is normal. And the size depends on your project and what you use at runtime.

**Comment by 983796605** [comment]
> Yes, it is normal. And the size depends on your project and what you use at runtime.

Ok, got it. Thank you
