### ISSUE TITLE
after package, upload images to "public" folder, but it can't visit the image url .just 404.

### ISSUE THREAD

**Issue by biliness** [nuxt/nuxt#23947]
### Describe the feature

before package folder tree:
public
--images
---a.jpg
---b.jpg

after package folder tree:
public
--images
---a.jpg
---b.jpg
I can visit image a.jpg, b.jpg.

via frontpage upload image c.jpg:
public
--images
---a.jpg
---b.jpg
---c.jpg
c.jpg can't be visit, just 404.
why?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Nuxt doesn't support updating the public folder after building it.

If you need this you could probably implement it yourself using `useStorage` and the `fs` storage driver.

**Comment by biliness** [comment]
> Nuxt doesn't support updating the public folder after building it.
> 
> If you need this you could probably implement it yourself using `useStorage` and the `fs` storage driver.

thank you for answer!
