### ISSUE TITLE
How nuxt3 declares types for plugin methods registered with provide

### ISSUE THREAD

**Issue by xxwangkaimin** [nuxt/nuxt#23953]
### Describe the feature

In the Nuxt3 project, WeChat shared JSSDK was used, so the following method was used to register a shared plugin:
```typescript
import wxJsSdk from 'weixin-js-sdk'

interface ShareOptions {
    title: string;
    desc: string;
    link: string;
    imgUrl: string
  }

export default defineNuxtPlugin(() => {
  return {
    provide: {
      wxShare(options: ShareOptions) {
        wxJsSdk.ready(function() {
          wxJsSdk.updateAppMessageShareData({
            title: options.title,
            desc: options.desc,
            link: options.link,
            imgUrl: options.imgUrl,
            success() {
            }
          })
          wxJsSdk.updateTimelineShareData({
            title: options.title,
            link: options.link,
            imgUrl: options.imgUrl,
            success() {
            }
          })
          wxJsSdk.onMenuShareWeibo({
            title: options.title,
            desc: options.desc,
            link: options.link,
            imgUrl: options.imgUrl,
            success() {
            },
            cancel() {
            }
          })
        })
      }
    }
  }
})
```
I declare the following in the global type file
```typescript
declare module 'nuxt' {
  interface NuxtApp {
    $wxShare(ShareOptions): void
  }
}
```
But when used, it will always report that this expression is not callable. Type '{}' does not have a call signature
![image](https://github.com/nuxt/nuxt/assets/33536543/a165a334-a3b8-4d78-86e9-1cc8ed96370e)
So how can I declare the type for this method

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
You should not need to manually declare this type. If you do, you do it like this:

```ts
declare module '#app' {
  interface NuxtApp {
    $wxShare(ShareOptions): void
  }
}
```

**Comment by xxwangkaimin** [comment]
> You should not need to manually declare this type. If you do, you do it like this:
> 
> ```ts
> declare module '#app' {
>   interface NuxtApp {
>     $wxShare(ShareOptions): void
>   }
> }
> ```
I have found a solution
```ts
declare module '#app' {
  interface NuxtApp {
    $wxShare(options: ShareOptions): void
  }
}

export {}

```
I have created a new type declaration file, but did not use export {}, which caused it to not take effect. It has now been resolved

**Comment by xxwangkaimin** [comment]
> You should not need to manually declare this type. If you do, you do it like this:
> 
> ```ts
> declare module '#app' {
>   interface NuxtApp {
>     $wxShare(ShareOptions): void
>   }
> }
> ```

Thank you very much. The problem has been resolved now

**Comment by bradley-varol** [comment]
I have this issue but don't know why. It looks like it started after updating deps.
