### ISSUE TITLE
class not change on watch 

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/nuxt#23954]
### Environment

Working directory: /home/projects/nuxt-starter-thxhbg                                                             10:28:32
Nuxt project info:                                                                                                10:28:32

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                       10:28:32

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Reproduction

https://stackblitz.com/edit/nuxt-starter-thxhbg

### Describe the bug

Open https://nuxtstarterthxhbg-qrf2--3000--f76cc998.local-credentialless.webcontainer.io/#description (with hash # description) 

variable isHash is true, but the class of 
`<a href="#description" :class="[isHash ? 'is-hash' : 'no-hash']"
      >Put #description hash</a
    >
`
appears 'no-hash'

![image](https://github.com/nuxt/nuxt/assets/77386602/f000dfa7-5601-4103-a198-ecdb27e545f3)

**Comment by danielroe** [comment]
This is a hydration error because hash is not defined on the server. If class/style attributes do not match between client and server, Vue does not then update them.
