### ISSUE TITLE
Error on keywords that shouldn't be unknown

### ISSUE THREAD

**Issue by CHIBX** [nuxt/nuxt#23957]
### Environment

- Operating System: Windows_NT
- Node Version:     v21.0.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.6.3
- Package Manager:  npm@10.2.0
- Builder:          -
- User Config:      devtools, router, alias, image, modules, imports, routeRules, nitro, experimental, app
- Runtime Modules:  @vueuse/nuxt@10.4.1, @nuxt/image-edge@1.0.0-rc.3-28271297.f1bc89f, @formkit/auto-animate/nuxt@0.8.0, @nuxtjs/robots@3.0.0
- Build Modules:    -

### Reproduction

![PostCSS Issue with Nuxt 3](https://github.com/nuxt/nuxt/assets/111882496/fa905385-9f6c-44e8-8fd7-2b80137bd5d4)

***Unfortunately, the error is not a constant one, as it happens to occur on some occassions***

### Describe the bug

![image](https://github.com/nuxt/nuxt/assets/111882496/fa905385-9f6c-44e8-8fd7-2b80137bd5d4)

# PostCSS mistakens script tag for style tag once in a while.
This error happens sometimes when I make little changes and this one happened when I added a new function to Vue script[setup] tag. I don't get any results after reloading my current page, or reverting my changes, but only until I restart my development server,  and most times by deleting the **.nuxt** folder. I initially thought that this error was due to my ***experimental*** option set with at least one key in ***nuxt.config.ts***, but it still occurred without any ***experimental*** set.

**Comment by agracia-foticos** [comment]
See the last "," of this line ... Could be?

**Comment by madebyfabian** [comment]
I can confirm that it occurs when you remove a `<style lang="postcss" scoped>` tag inside an SFC.

**Comment by CHIBX** [comment]
> I can confirm that it occurs when you remove a `<style lang="postcss" scoped>` tag inside an SFC.

I don't use postcss so i have no idea why it does like this

**Comment by CHIBX** [comment]
> See the last "," of this line ... Could be?

Isn't that the shorthand to define multiple variables together?

**Comment by agracia-foticos** [comment]
> > See the last "," of this line ... Could be?
> 
> Isn't that the shorthand to define multiple variables together?

That's true!!!

**Comment by CHIBX** [comment]
> > > See the last "," of this line ... Could be?
> > 
> > 
> > Isn't that the shorthand to define multiple variables together?
> 
> That's true!!!

However, I still don't understand how "const" would be termed unknown. Is there a way to disable postcss or is it needed by default

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/14976.

**Comment by CHIBX** [comment]
> Let's track in #14976.

Ok
