### ISSUE TITLE
Nuxt3 builder webpack uses "React.createElement" as default pragma to compile JSX element

### ISSUE THREAD

**Issue by mhdSid** [nuxt/nuxt#23950]
### Environment

Nuxt: 3.8.0 or 3.6.5

### Reproduction

https://nuxt.com/docs/examples/hello-world

Just try setting builder webpack and use JSX

### Describe the bug

After workarounds and surfing through the issues, the JSX element gets compiled into a React element which is not compatible with Vue.

```
import webpack from 'webpack'

export default defineNuxtConfig({
  srcDir: 'src/',
  builder: 'webpack',
  modulesDir: [
    `${process.cwd()}/node_modules`
  ],
  alias: {
    vue$: `${process.cwd()}/node_modules/vue/dist/vue.esm-browser.js`,
    react$: `${process.cwd()}/node_modules/react/index.js`
  },
  webpack: {
    extractCSS: true,
    optimization: {
      splitChunks: {
        cacheGroups: {
          styles: {
            name: 'styles',
            test: /\.(css|vue)$/,
            chunks: 'all',
            enforce: true
          }
        }
      }
    },
    plugins: [
      new webpack.ProvidePlugin({
        'React': 'react'
      })
    ]
  }
})
```

### Additional context
**Please any support would be grateful because Im migrating our product to Nuxt3!** :(

- Unable to use babel.config.js to setup proper plugin for vue3 jsx such as 
```['@vue/babel-plugin-jsx']```
- Babel config seems to be ignored by webpack builder.
- JSX element gets compiled into a React element: 
```() => /* @__PURE__ */ React.createElement("div", null, "hello")```

### Logs

```shell-script
- React is not defined
- vue.esm-browser.js:1513 [Vue warn]: Invalid VNode type: div (string)
```

**Comment by danielroe** [comment]
let's track in nuxt/nuxt#23844.
