### ISSUE TITLE
Vite dev middleware overrides cors headers

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt#23962]
### Environment

- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  pnpm@8.5.1
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://github.com/samydoesit/repro-nuxt-cors-options by @samydoesit (https://github.com/unjs/nitro/issues/1095#issuecomment-1779823612)

it has to run locally, for more readable reproduction, you can also change `test-handler.ts` to this:

```ts
export default defineEventHandler((event) => {
  setResponseHeader(event, 'x-custom', '123');
  setResponseHeader(event, 'access-control-allow-credentials', 'true');
  setResponseHeader(event, 'access-control-allow-origin', 'protocol://test');
  return '...';
});
```

`http OPTIONS :3000/test Origin:'protocol://test'` responds when using nuxt in development mode:

```
HTTP/1.1 204 No Content
access-control-allow-methods: GET,HEAD,PUT,PATCH,POST,DELETE
access-control-allow-origin: *
connection: close
content-length: 0
date: Thu, 26 Oct 2023 16:37:23 GMT
vary: Access-Control-Request-Headers
```

When running nuxt (nitro server alone) in production:

```
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 3
Date: Thu, 26 Oct 2023 16:38:21 GMT
Keep-Alive: timeout=5
access-control-allow-credentials: true
access-control-allow-origin: protocol://test
content-type: text/html
x-custom: 123
```

### Describe the bug

It seems the vite dev server overrides those headers (thanks for the investigation from @danschalow in https://github.com/unjs/nitro/issues/1095#issuecomment-1781075661)

----

As a workaround, one might use `nuxt.config` to customize `vite.server.cors`:

```ts
export default defineNuxtConfig({
  vite: {
    server: {
      cors: {
        origin: true,
        methods: ['GET', 'HEAD', 'PUT', 'PATCH', 'POST', 'DELETE'],
        preflightContinue: true,
        optionsSuccessStatus: 204,
      },
    }
  }
})
```

Response:

```
HTTP/1.1 200 OK
access-control-allow-credentials: true
access-control-allow-methods: GET,HEAD,PUT,PATCH,POST,DELETE
access-control-allow-origin: protocol://test
connection: close
content-length: 3
content-type: text/html
date: Thu, 26 Oct 2023 16:40:54 GMT
vary: Origin, Access-Control-Request-Headers
x-custom: 123
```

### Additional context

Using `routeRules` `cors` allows overriding `access-control-allow-origin` but not the rest as it early handles headers:

```ts
export default defineNuxtConfig({
  routeRules: {
    '/test': { cors: true }
  }
})
```

```
HTTP/1.1 204 No Content
access-control-allow-methods: GET,HEAD,PUT,PATCH,POST,DELETE
access-control-allow-origin: *
connection: close
content-length: 0
date: Thu, 26 Oct 2023 16:42:54 GMT
vary: Access-Control-Request-Headers
```

**Comment by danielroe** [comment]
thank you! ❤️

we can track in https://github.com/nuxt/nuxt/issues/22512.
