### ISSUE TITLE
Wrong type for server `getRouteRules`

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt#23964]
The `getRouteRules(path: string)` method exposed for nuxt app, is leaking to nitro server types, causing wrong typing as it accepts `getRouteRules(event`)

Reproduction: https://stackblitz.com/edit/nuxt-starter-m3nhq6?file=nuxt.config.ts,server%2Froutes%2Ftest.ts,app.vue

**Comment by danielroe** [comment]
Cloning locally I can't reproduce this.

![CleanShot 2023-11-07 at 12 37 00](https://github.com/nuxt/nuxt/assets/28706372/87de899b-1852-44ea-8a8e-63df64ba0dbf)

**Comment by pi0** [comment]
It is reproducible in stackblitz might it be a typescript support issue for them? 

<img width="724" alt="image" src="https://github.com/nuxt/nuxt/assets/5158436/6a3421c9-967b-4e1b-a6d5-5053a1923cf1">
