### ISSUE TITLE
$fetch has no result on some browsers

### ISSUE THREAD

**Issue by xjccc** [nuxt/nuxt#23972]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.15.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.1
- Package Manager:  pnpm@8.9.2
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/xjccc/useAsyncData-example

### Describe the bug

on QQ Browser and UC Browser has no result

on safari chrome quark firefox works fine

to add this QQ and UC works fine

`
"pnpm": {
  "overrides": {
    "ofetch": "1.2.1"
  }
}
`

### Additional context

https://github.com/unjs/ofetch/issues/294

i update my nuxt@3.8

it's not work fine too

**Comment by danielroe** [comment]
@pi0 What is your thinking on this? I would have thought it sounds like a browser support issue for something we're doing in `ofetch`, rather than an issue in Nuxt, but I guess you have another idea?

@xjccc Would you see if you can replicate with pure `ofetch` in those browsers, perhaps using https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter to get going? 🙏

**Comment by xjccc** [comment]
> @pi0 What is your thinking on this? I would have thought it sounds like a browser support issue for something we're doing in `ofetch`, rather than an issue in Nuxt, but I guess you have another idea?
> 
> @xjccc Would you see if you can replicate with pure `ofetch` in those browsers, perhaps using https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter to get going? 🙏

emm..

i download the project to dev in these browsers.

[project](https://github.com/xjccc/github-sxnytk)

`ofetch@1.2.1` is works fine.

`ofetch@1.3.3` at QQ\UC\SouGou Browsers works wrong

`its has no result`

**Comment by danielroe** [comment]
Okay, so that sounds like this isn't an issue in Nuxt but directly a matter of browser support.

**Comment by zss1004504439** [comment]
I have the same problem
`ofetch@1.2.1` is normal
`ofetch@1.3.3` no result in `useFetch`
