### ISSUE TITLE
Use custom $fetch client for useFetch

### ISSUE THREAD

**Issue by robin-dongbin** [nuxt/nuxt#24004]
### Describe the feature

Here is a reference:https://github.com/sot1986/nuxt-laravel-precognition

This package has a `useForm` function and it provide a way to custom the fetch client.
If the `useFetch` can provide something like this, that would be very nice.

I have read the docs and I know I can define my own `useCustomFetch`, but I think `useFetch` is shorter and more eleganter.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by warflash** [comment]
Do you intend to set defaults across the app for useFetch or supply actual different fetch implementations like using axios instead of ofetch under the hood?

**Comment by danielroe** [comment]
You can indeed do this by passing your custom `$fetch` as an option to `useFetch`.

https://github.com/nuxt/nuxt/blob/2dc078ea406638df19ed6036a873e89227e4db62/packages/nuxt/src/app/composables/fetch.ts#L143

**Comment by robin-dongbin** [comment]
> You can indeed(事实上) do this by passing your custom `$fetch` as an option to `useFetch`.
> 
> https://github.com/nuxt/nuxt/blob/2dc078ea406638df19ed6036a873e89227e4db62/packages/nuxt/src/app/composables/fetch.ts#L143

Then you must define `useCustomFetch`
