### ISSUE TITLE
useFetch cache Error response and never load it again

### ISSUE THREAD

**Issue by kon3ko** [nuxt/nuxt#24008]
### Environment

- Node Version: v18.18.0
- Nuxt 3.8.0
- Nitro 2.7.2

### Reproduction

https://stackblitz.com/edit/nuxt-starter-jgqfhc?file=pages%2Findex.vue

### Describe the bug

If use useFetch and receive a response of 404 500 ... After that, change the web page. and return to the original page.
useFetch will not resend the request and will continue to use the same one it received before. But if refresh the website, useFetch will work normally.

### Additional context

This is caching of useFecth? How do I handle it?

**Comment by danielroe** [comment]
This should be resolved in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/) via https://github.com/nuxt/nuxt/pull/23889, or in the next release.

Let me know if not and I'll reopen.
