### ISSUE TITLE
Watchers are not paused/destroyed when keepalive is set to true

### ISSUE THREAD

**Issue by toniengelhardt** [nuxt/nuxt#24011]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.8.0`
- CLI Version:      `3.9.1`
- Nitro Version:    `2.7.1`
- Package Manager:  `pnpm@8.10.0`
- Builder:          `-`
- User Config:      `ssr`, `runtimeConfig`, `site`, `modules`, `imports`, `experimental`, `sourcemap`, `devtools`, `app`, `vite`, `typescript`, `css`, `postcss`, `nitro`, `piniaPersistedstate`, `http`, `auth`, `colorMode`, `plausible`, `sitemap`
- Runtime Modules:  `@nuxt/devtools@1.0.0`, `@nuxt-alt/auth@2.7.0`, `@nuxt-alt/http@1.6.9`, `@nuxtjs/color-mode@3.3.0`, `@nuxtjs/plausible@0.2.3`, `@nuxtseo/module@2.0.0-beta.39`, `@pinia/nuxt@0.5.1`, `@pinia-plugin-persistedstate/nuxt@1.2.0`, `@unocss/nuxt@0.57.1`, `@vueuse/nuxt@10.5.0`, `nuxt-icon@0.6.1`, `nuxt-vitest@0.11.0`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-watch-teardown-bug

### Describe the bug

When keepalive is set to true in `nuxt.config.ts`, watchers are not properly destroyed. This means if you have dynamic pages with a watcher and navigate through a few pages and then an action or mutation triggers a watcher, it fires once for each page, see reproduction with magic keys.

**Comment by toniengelhardt** [comment]
Potentially related to https://github.com/nuxt/nuxt/issues/18871

**Comment by danielroe** [comment]
This is upstream behaviour. You can consider using `onActivated` and `onDeactivated` when using keepalive.

https://vuejs.org/guide/built-ins/keep-alive.html#lifecycle-of-cached-instance

Vue 3 only reproduction: https://stackblitz.com/edit/github-q7kqa2?file=src/App.vue,src/pages/About.vue,src/pages/Home.vue,src/pages/Another.vue.

**Comment by toniengelhardt** [comment]
Oh crazy! Gonna roll without `keepalive` then. Thanks for clarifying 🙏🏽
