### ISSUE TITLE
[nuxt] [request error] [unhandled] [500] Cannot find module '@resvg/resvg-js-linux-x64-gnu'

### ISSUE THREAD

**Issue by catsmeatman** [nuxt/nuxt#24017]
### Environment

MacOS Sonoma 14.0
NodeJS 21.1.0
Npm 10.2.0
Nuxt 3.8

### Reproduction

1. Create new Nuxt based app.

2. Add modules:
@nuxtseo/module
nuxt-site-config
nuxt-simple-sitemap

3. Add in Nuxt.config.ts `modules: ['@nuxtseo/module', 'nuxt-simple-sitemap']`

4. Run on local environment - all ok.

5. Deploy on production. Ubuntu 22, NodeJS 21.1.0, Npm 10.2.0, pm2 5.3.0

6. Execute run Nuxt app with pm2 `pm2 server/index.mjs`

### Describe the bug

Bug in used package @resvg/resvg-js. Package based on https://github.com/napi-rs/napi-rs and include many builds Rust app for different platforms.

When your building Nuxt app for production server in local environment (MacOS) used @resvg/resvg-js-darwin-x64 package.
When you deploy builded Nuxt app on production server and start app will be used @resvg/resvg-js-linux-x64-gnu (Ubuntu). 

Package @resvg/resvg-js-linux-x64-gnu not included in production build Nuxt app because local environment is differs from production.

### Logs

```shell-script
[nuxt] [request error] [unhandled] [500] Cannot find module '@resvg/resvg-js-linux-x64-gnu'
Require stack:
- /root/comisal.tech/server/node_modules/@resvg/resvg-js/js-binding.js
- /root/comisal.tech/server/node_modules/@resvg/resvg-js/index.js
  at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)  
  at Module._load (node:internal/modules/cjs/loader:901:27)  
  at Module.require (node:internal/modules/cjs/loader:1115:19)  
  at require (node:internal/modules/helpers:130:18)  
  at Object.<anonymous> (./comisal.tech/server/node_modules/@resvg/resvg-js/js-binding.js:1:3488)  
  at Module._compile (node:internal/modules/cjs/loader:1241:14)  
  at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)  
  at Module.load (node:internal/modules/cjs/loader:1091:32)  
  at Module._load (node:internal/modules/cjs/loader:938:12)  
  at Module.require (node:internal/modules/cjs/loader:1115:19)
```

**Comment by danielroe** [comment]
In this case you will probably need to manually include those files with this configuration: https://github.com/nuxt/nuxt/issues/22325#issuecomment-1690421926

**Comment by catsmeatman** [comment]
Thx!

**Comment by Turbotailz** [comment]
I'm also getting this error when deploying my project.

> In this case you will probably need to manually include those files with this configuration: https://github.com/nuxt/nuxt/issues/22325#issuecomment-1690421926

@danielroe Can you please elaborate on this? I don't understand what I need to do here.

@catsmeatman can you provide your solution if it's working again?

**Comment by catsmeatman** [comment]
@Turbotailz haven't solution. Deleted packaged used '@resvg/resvg-js-linux-x64-gnu

**Comment by Whbbit1999** [comment]
Removing the '@ nuxtseo/module' package will not result in this error. Could it be a bug in the '@ nuxtseo/module' package?

**Comment by danielroe** [comment]
@Whbbit1999 Interesting. It would be worth reporting there.

**Comment by cossssmin** [comment]
Just ran into this (see [logs](https://app.netlify.com/sites/maizzle-docs/deploys/65ccd286aad11a14f57fcdc1)), for me it was because of the `nuxt-og-image` module, which also has a dependency on `resvg`.

Fixed by updating `nuxt-og-image` to `3.x` (`3.0.0-rc.38` at the time of this writing).

**Comment by develth** [comment]
> Still running into this issue, all packages (Nuxt SEO / og-image) are on the latest versions:

i delted `node_modules`, `.output` and `.nuxt` - then it worked
