### ISSUE TITLE
Setting `shamefully-hoist=false` will make `$fetch` fail to get the types

### ISSUE THREAD

**Issue by awdr74100** [nuxt/nuxt#24016]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.9.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.1
- Package Manager:  pnpm@8.10.0
- Builder:          -
- User Config:      devtools, runtimeConfig
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

repo: https://github.com/awdr74100/nuxt-bug-reproduction

### Describe the bug

`~/.npmrc`
```env
shamefully-hoist=false
```

`~/server/api/user.get.ts`
```ts
export default defineEventHandler(async (event) => {
  return { user: { id: 1, name: "Eric" } };
});
```

`~/app.vue`
```vue
<script setup lang="ts">
const getUser = async () => {
  const data = await $fetch("/");
};
</script>
```
![螢幕擷取畫面 2023-10-29 215253](https://github.com/nuxt/nuxt/assets/47501692/75e32938-1d18-475e-8f53-f18705d61a36)

Same problem as #23984. Setting `shamefully-hoist=false` will cause nitro `$fetch` to fail to get the types.

Is this an expected error or is there something wrong with my configuration? If set `shamefully-hoist=true` everything will work fine

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/23984.
