### ISSUE TITLE
Updating spa-loading-template.html takes no effect

### ISSUE THREAD

**Issue by kingyue737** [nuxt/nuxt#24025]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools, ssr, spaLoadingTemplate
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-ishb9z

### Describe the bug

Make any changes to `app/spa-loading-template`.
Although the console printed `ℹ page reload app/spa-loading-template.html`, no changes take effect.
Users need to restart Nuxt server to view the updated spa loading template, which is not a good DX.

**Comment by danielroe** [comment]
This should be resolved in https://github.com/nuxt/nuxt/pull/24036.
