### ISSUE TITLE
custom transformAssetUrls removes the default? Intended behavior?

### ISSUE THREAD

**Issue by VividLemon** [nuxt/nuxt#24038]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.7.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  pnpm@8.6.5
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/packages/nuxt/src/module.ts#L28
& 
https://github.com/bootstrap-vue-next/bootstrap-vue-next/tree/main/packages/nuxt/playground

### Describe the bug

This could be intended behavior, but adding a custom transformAssetUrls option removes the defaults. 

For example if I do 
```ts
  vite: {
    vue: {
      template: {
        transformAssetUrls: {
          BImg: ['src'],
        },
      },
    },
  },
```
Suddenly `img: ['src']` resolution disappears. 

The simple solution is to just add it back in manually. But this is a bit strange. If transformAssetUrls ever has more defaults, then suddenly they would break too. 

This is a double edged sword, as the question is asked "What if you don't want to transform those urls?". If the default is merged, then you wouldn't be able to override that behavior. But in this context I don't know why you wouldn't want the defaults.

Maybe this is Vites fault, idk.

**Comment by danielroe** [comment]
This is likely due to `@vitejs/plugin-vue` but I think we can resolve this by setting the defaults so they can be merged.
