### ISSUE TITLE
Nuxt Layers + Npm Workspaces(Monorepo) Doesn't work only in Dev Mode

### ISSUE THREAD

**Issue by halilyuce** [nuxt/nuxt#24049]
### Environment

- Operating System: `Darwin`
- Node Version:     `v19.3.0`
- Nuxt Version:     `3.8.0`
- CLI Version:      `3.9.1`
- Nitro Version:    `2.7.2`
- Package Manager:  `npm@9.3.1`
- Builder:          `-`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/halilyuce/monorepo

### Describe the bug

Here is my monorepo structure:

<img width="297" alt="image" src="https://github.com/nuxt/nuxt/assets/29376592/7a1f6640-6b7b-4f63-aa0e-62adce755b01">

I created a monorepo with npm workspaces and extended apps in the portal(main app) thanks to nuxt layers. Everything works as expected in production mode but not in dev mode?

When I run the project in dev mode, I do not receive any errors. It stays on the nuxt loading screen and the computer starts to heat up seriously and the fans become loud, probably a memory problem. 

I have a decent laptop, according to my research, this problem occurs because the node_modules location changes when using monorepo. I applied dozens of solutions for this, but none of them worked.

<img width="454" alt="image" src="https://github.com/nuxt/nuxt/assets/29376592/cd338d5c-9071-43a9-9006-3e25e82f2169">

![image](https://github.com/nuxt/nuxt/assets/29376592/7c6cb370-5bf4-459e-ba03-02c46c552387)

**Comment by theguriev** [comment]
Most probably you have a cyclomatic dependency issue but it's hard to say without any reproduction.

**Comment by halilyuce** [comment]
> Most probably you have a cyclomatic dependency issue but it's hard to say without any reproduction.

Hmm, let me create a minimal repo with the same structure and provide then, thanks :)

**Comment by halilyuce** [comment]
@danielroe @theguriev I've added a reproduction and the result is the same unfortunately, thanks in advance.

**Comment by theguriev** [comment]
Well yes. Looks like there is an infinite loop when it's try to resolve aliases. #portal is trying to resolve #first-ui and #first-ui has some links to the #portal. It's a never-ending cycle. I'll prepare a minimal repro with fix in few minutes.

**Comment by halilyuce** [comment]
> Well yes. Looks like there is an infinite loop when it's try to resolve aliases. #portal is trying to resolve #first-ui and #first-ui has some links to the #portal. It's a never-ending cycle. I'll prepare a minimal repro with fix in few minutes.

I removed all the aliases from all apps but still the same mate, are you sure is it because of that?

**Comment by theguriev** [comment]
Here it is.
```bash
git clone git@github.com:theguriev/monorepo-explanation.git && cd monorepo-explanation && pnpm i && cd portal && pnpm run dev
```

Just run this in terminal and open http://localhost:3000/first-ui

<img width="1380" alt="image" src="https://github.com/nuxt/nuxt/assets/8502021/baedec4e-2b27-4465-8359-2551ca18a49d">

**Comment by halilyuce** [comment]
@theguriev  Thanks mate but the issue is they want me to only use npm workspaces, they don't want pnpm unfortunately. Judging by so far, the problem seems to be caused by npm workspaces?

**Comment by theguriev** [comment]
Yep. It's possible in `npm` as well. https://github.com/theguriev/monorepo-explanation/pull/1

Have fun :) 

So it's definitely no Nuxt issue. :)

**Comment by halilyuce** [comment]
> Yep. It's possible in `npm` as well. [theguriev/monorepo-explanation#1](https://github.com/theguriev/monorepo-explanation/pull/1)
> 
> Have fun :)
> 
> So it's definitely no Nuxt issue. :)

You are amazing mate, you put in a lot of effort! :) I installed pnpm while you were working on this and applied it to the current project, the problem is the same, I think we are looking in the wrong place. There are so many things missing in your example such as windiCSS. I'm starting to think maybe windiCSS is causing a problem?

**Comment by theguriev** [comment]
Oh, thank you! ❤️

> There are so many things missing in your example such as windiCSS. I'm starting to think maybe windiCSS is causing a problem?

True. I tried to isolate everything and make it as simple as possible. Let me check again your repro. I don't think it's windi

**Comment by halilyuce** [comment]
It may sound ridiculous, but the problem stems from this line;

`css: ["ant-design-vue/dist/antd.variable.less", "~/assets/scss/main.scss"],`

and it gets fixed when I remove the **"ant-design-vue/dist/antd.variable.less"** part from the CSS Array.

**Comment by theguriev** [comment]
I'm betting it can't resolve the paths and goes into an endless loop somewhere. btw in this case if you'll remove `nuxt-windicss` from every app + portal it will work as well. Something definitely wrong with deps

**Comment by theguriev** [comment]
Yep. It works in this case. At least it can render the 404 page :) 
<img width="1686" alt="image" src="https://github.com/nuxt/nuxt/assets/8502021/afd3d57c-a4ef-4928-a90d-2231a4bef7d0">
<img width="1045" alt="image" src="https://github.com/nuxt/nuxt/assets/8502021/d146d4ce-1af4-4032-8254-4e26146db318">

**Comment by theguriev** [comment]
So it requires deeper investigation but again it's not Nuxt issue :)

**Comment by halilyuce** [comment]
That's right mate, the problem seems to be caused by the ant design library, I will try to find another way to use the less file and solve the problem 😄  Thank you very much for your effort, I have been dealing with this for days and it turns out that I was looking for the problem in the wrong place 😅

**Comment by theguriev** [comment]
> That's right mate, the problem seems to be caused by the ant design library, I will try to find another way to use the less file and solve the problem 😄 Thank you very much for your effort, I have been dealing with this for days and it turns out that I was looking for the problem in the wrong place 😅

It happens :) Good luck with debugging :)
