### ISSUE TITLE
Hydration Mismatch when useAsyncData is not awaited

### ISSUE THREAD

**Issue by JavierEGonzalez** [nuxt/nuxt#24042]
### Environment

```
------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Reproduction

Go to:
https://stackblitz.com/edit/nuxt-starter-yamb8r?file=pages%2Findex.vue

and refresh the browser window.

### Describe the bug

Currently we are running to an issue for a production application where we are getting a 
```
chunk-JGO4W4UR.js:1708 [Vue warn]: Hydration text content mismatch in <div>:
- Client: value set
- Server: == to set == 
  at <HydrationError onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
 (...)
```
In the app in question, doing a top level await will remove the errors, but it becomes render blocking during client side navigation, making it unfeasible. I looked at a few other issues 
- https://github.com/nuxt/nuxt/issues/23590 
for example, but found the answer was not sufficiently addressing our issue (wrapping the content in a `<div>` had no effect). I am currently only getting this when I use `useAsyncData`, so I do believe it is a nuxt bug.

**Comment by danielroe** [comment]
`useAsyncData` should not have side effects; it should _return_ the value that you then go on to use.
