### ISSUE TITLE
useFetch transform diferent behaviour in npm run dev and building pro mode

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/nuxt#24046]
### Environment

Working directory: /home/projects/nuxt-starter-4edg7l                                                              9:30:34
Nuxt project info:                                                                                                 9:30:34

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                        9:30:34

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Reproduction

https://stackblitz.com/edit/nuxt-starter-4edg7l

### Describe the bug

we have this code https://stackblitz.com/edit/nuxt-starter-4edg7l in one of our pages.

we launch with dev mode, and the fetch into the transform function, only it trigers in SSR (Node) Mode, and returns the result in context to VUE (client).

But if i compile with production mode, and launch de server, we see in logs, that both request is launched in SSR Mode (Node) and VUE (client), not spread the result in context

**Comment by danielroe** [comment]
`useFetch` should only be used in setup. Moreover, the issue is that `transform` is a _sync_ hook and doesn't support async functions.

Here's how you could rewrite it: https://stackblitz.com/edit/nuxt-starter-efb1k7?file=pages/index.vue,nuxt.config.ts.

**Comment by agracia-foticos** [comment]
Thanks @danielroe !!!
