### ISSUE TITLE
Navigating to or from a page that uses a different layout will not scroll to the top automatically

### ISSUE THREAD

**Issue by hdwebpros** [nuxt/nuxt#24057]
### Environment

Nuxt 3.8

### Reproduction

https://stackblitz.com/edit/nuxt-starter-7kblg3

### Describe the bug

Navigating to or from a page that uses a different layout will not scroll to the top automatically.

If you take out `definePageMeta({ layout: 'home' });` on the index page in the example, navigating to and from the 2 pages works as expected. However, if you use that layout, navigating between pages doesn't do the automatic scroll to top on new page load anymore.

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/23593. There's an open PR to resolve as well.
