### ISSUE TITLE
Don't apply server middleware to all requests

### ISSUE THREAD

**Issue by jeannen** [nuxt/nuxt#24050]
### Describe the feature

Hi!

Right now it seems like all middleware created in `/server/middleware` are applied globally to every request

I was trying to make an auth system using JWT (where the user get redirected if they don't have valid token), but my middleware applies to every request, so it creates an infinite loop.
I searched the doc but haven't found anything about disabling them.

```

// middleware/authenticated.js
import { verifyToken } from '~/utils/auth'

export default defineEventHandler(async (event) => {
    // Get token from the request header
    const token = getCookie(event, 'session-token')

    if (!token) return sendRedirect(event, '/login')
   
    // // Verify the token
    const decoded = await verifyToken(token)
    if (!decoded) return navigateTo('/login')

})
```

It wouldn't work with client-side middleware since the auth has sensitive stuff.

Sorry if this is a dumb question or not the right place, I don't use Github that often maybe there is already a way of doing it 😅

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Yes, that's the concept of server middleware - you need to check to prevent loops of this kind if the middleware initiates its own request. you can set a property on the context and use `event.$fetch`...

**Comment by jeannen** [comment]
I see, would there be any better way of handling the middleware? 

Since the ones from the `/middleware` folder are exposed 

(ex: like the function above that checks if a token is valid from the cookies then redirect if it is not)

**Comment by jeannen** [comment]
Ended up doing this:

```JS
const protectedRoutes = [
    '/dashboard',
    '/api/auth/get-code'
]

export default defineEventHandler(async (event) => {
    if (!protectedRoutes.includes(event.node.req.url)) return
    /// rest of the middleware
})
```
