### ISSUE TITLE
Flag to control if generation runs build process or not

### ISSUE THREAD

**Issue by jeanpierrecarvalho** [nuxt/nuxt#24069]
`###` Describe the feature

Currently, when generating a Nuxt project using nuxt generate, the build process is automatically triggered before generation. This is helpful in most cases as it ensures that the project is up to date and the generated files are based on the latest code. However, there are situations where it would be beneficial to have more control over this behavior.

I propose the addition of a new flag or configuration option, for example, --skip-build or an entry in the nuxt.config.js file, that allows developers to specify whether the build process should be executed before generation.

This feature would be particularly useful in scenarios where we are confident that the project is already built and up to date, and we want to skip the build step to save time and resources during the generation process. It can also be helpful when integrating Nuxt with CI/CD pipelines where build and generation processes are managed separately.

`nuxt generate --skip-build`

Or

`build: {
    skip: true, // This is just an example; actual syntax and naming may vary
  }`

**Additional Context:**

I want to implement this functionality in **nuxt 2.x** and **nuxt 3.x**

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Let's track this in https://github.com/nuxt/nuxt/issues/23392 - though I'd like this to be done automatically rather than passing a flag. How does that sound?
