### ISSUE TITLE
Using `shallowRef` for `useState`

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt#24068]
### Describe the feature

After https://github.com/nuxt/nuxt/pull/23600 landed I wondered - couldn't we support the same for `useState`? 🤔

Which is: Give the users the option to use a `shallowRef` instead of a `ref` as underlying reactive structure

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
It is possible like this:

```ts
useState(shallowRef)
```

**Comment by manniL** [comment]
🤦‍♂️ 
Thanks!

**Comment by danielroe** [comment]
We only just documented it so totally understandable! 😆
