### ISSUE TITLE
Payload is not loaded when nuxt build is used

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt/nuxt#24067]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  pnpm@8.7.1
- Builder:          -
- User Config:      app, runtimeConfig, modules, experimental, css, nitro, content, unocss, site, sitemap, routeRules, devtools
- Runtime Modules:  @nuxt/content@2.9.0, @vueuse/nuxt@10.5.0, @unocss/nuxt@0.55.7, nuxt-simple-robots@3.1.9, nuxt-simple-sitemap@3.4.1, nuxt-schema-org@2.2.0, @nuxthq/studio@1.0.2, @nuxtjs/plausible@0.2.3
- Build Modules:    -
------------------------------

### Reproduction

https://unjs.io

If you take a look at the network tab, there is no `_payload.json` file loaded. But, there is a file at https://unjs.io/_payload.json with a correct prerenderedAt value.

### Describe the bug

I do not know what should be the correct behavior but when using nuxt build with the prerender object, `_payload.json` is not used.

Take a look at this https://github.com/unjs/website/pull/157 and this https://feat-package-readme.unjs.pages.dev/, you will this the same issue. 

This become a real issue if you navigate to a package like https://feat-package-readme.unjs.pages.dev/packages/bundle-runner. The payload file is not loaded, so not used, and a request to /api/github/unjs/bundle-runner/readme is fired but the page is prerendered so I expect that the payload is used instead when navigating from a page like /packages to /packages/bundle-runner. Otherwise, it took 300ms to navigate for something that I have prerendered.

Is this a normal behavior?

### Additional context

Maybe I should also prerender the /api/github/** (but this does not work). Adding every routes to the routes array seems a little tricky for something like this.

related https://github.com/unjs/nitro/issues/1875
related https://github.com/unjs/website/pull/157

**Comment by Barbapapazes** [comment]
This does not happens when using `nuxt generate`

**Comment by Barbapapazes** [comment]
Using the key static true withina routeRules seems to change this.

https://nitro.unjs.io/config#routerules

**Comment by Barbapapazes** [comment]
This solved my issue. do the documentation have a page about pre-render vs static or it this a way to improve documentation? (happy to write something about it if it's missing)
![image](https://github.com/nuxt/nuxt/assets/45267552/a7938ef7-f118-447b-8d09-e3c88c5ad369)

**Comment by Barbapapazes** [comment]
In the same time, the time, the command `nuxi generate` or `nuxi build --prerender` seems to do more than just prerendering pages. Maybe we could explain more?

**Comment by Barbapapazes** [comment]
Works with node but not with cloudflare

**Comment by danielroe** [comment]
This might be resolved in https://github.com/nuxt/nuxt/pull/24031 - would you check if things are working better with the nightly release? 🙏

**Comment by danielroe** [comment]
Checking, this does seem resolved with v3.8.1. 🥳

**Comment by Barbapapazes** [comment]
Yes, just checked on unjs.io (https://github.com/unjs/website/pull/182/files) and it works! thanks!
