### ISSUE TITLE
useFetch with watch ref not fetching new data 3.8 and persists when downgrading to 3.7.4

### ISSUE THREAD

**Issue by attentiondefficient** [nuxt/nuxt#24077]
Environment
Operating System: macOS and raspberrypiOS bullseye
Node Version: v20.9.0
Nuxt Version: 3.7.4 / 3.8.0
CLI Version: 3.9.1
Nitro Version: 2.7.0/2.7.2
Package Manager: npm@10.2.1

Describe the bug
Upgrading to 3.8.0 causes useFetch watch ref value change to no longer trigger refetching data

Additional context
I have tried removing node_modules, reinstalling everything, specifying nuxt@3.7.4 with no luck. I had no problem with nuxt3 3.7.4 and nitro 2.6.3. But any fresh install of nuxt installs a version of nitro 2.7.x.

**Comment by Nemure231** [comment]
i have same problem, its works with immediate option during first load, but when watching data after that, its doesn't works. Here i got an minimal reproduction. 

https://stackblitz.com/edit/nuxt-starter-vxdkv1?file=pages%2Findex.vue

**Comment by Nemure231** [comment]
@attentiondefficient  please add labels in this issue, add bug label or something, just to get attention from the maintainer.

**Comment by manniL** [comment]
@Nemure231 Your example is "misusing" `useFetch` quite a bit 🙈

I've updated your example in two ways: Either to [react on data change](https://stackblitz.com/edit/nuxt-issues-24077-data?file=pages%2Findex.vue) (click change the id which trigger `useFetch` again) or to [refresh on click](https://stackblitz.com/edit/nuxt-issues-24077-click?file=pages%2Findex.vue) as kind of "side effect"

**Comment by Nemure231** [comment]
Wow, really?

How about i have use case to watch a tab data, the tab will change, and fetching the different data accoourding to the tabs. Its not about refreshing data.

**Comment by manniL** [comment]
> How about i have use case to watch a 'tabs' data like ['tab1', 'tab2'] , the tab will change and fetching the different data according to the current tab. Its not about refreshing data.


You can use the `watch` property, but commonly the data should be part of your params or url. If they are reactive, changes will happen automatically.

Example:

```ts
const activeTab = ref('tab1')
const { data, pending } = await useFetch(
  () => `https://dummyjson.com/products/${tab.value}`
);
```


Also, how about i want to reuse it, using a composable, pinia anyway? I must use function, your example is not relevant, open this issue again please.

**Comment by attentiondefficient** [comment]
I will elaborate and clarify in greater detail when I am home, and I apologize for my hastily written post. 

I am using a rest API to put a zwave controller into inclusion mode and pair devices. I am trying to refresh the discovered device/inbox data every 3 seconds for 60 seconds or until a device is paired. I could not get the refresh function to work for the life of me, so ended up using the watch parameter. 

Any advice/guidance in the proper way I should be doing this would be greatly appreciated. Thank you!

**Comment by manniL** [comment]
>  I am trying to refresh the discovered device/inbox data every 3 seconds for 60 seconds or until a device is paired. I could not get the refresh function to work for the life of me, so ended up using the watch parameter.

Refresh *should* work fine as shown in the example linked above ☺️

Happy to look over existing code if you can provide the reproduction when you are home 👍🏻
