### ISSUE TITLE
Target app doesn't install dependencies from layer

### ISSUE THREAD

**Issue by bureaubox** [nuxt/nuxt#24071]
### Environment

- Operating System: Darwin
- Node Version:     v18.18.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  npm@9.8.1
- Builder:          -
- User Config:      extends, build, telemetry, alias, ssr, nitro, ui, routeRules, runtimeConfig, hooks
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

if needed, I can provide access to repo's where this issue occurs

### Describe the bug

any (dev)dependencies that are installed in the layer, are not automatically installed in the target app. Result is that you need to manually copy dependencies from the layer's package.json and paste to target app's package.json

if dependencies are not copied, an error is thrown upon running ```npm i```

### Additional context

I'm consuming the layer as a npm package from the target app (so not referencing the github repo)

There are some other issues concerning layer dependencies, but I don't think they refer to exactly the same bug:

https://github.com/nuxt/nuxt/issues/23445
https://github.com/nuxt/nuxt/issues/19426

### Logs

```shell-script
remihuigen@Remis-MBP voorbereiden % npm i

> voorbereiden-nuxt@0.0.1 postinstall
> nuxt prepare


 ERROR  Cannot find any nuxt version from /Users/remihuigen/local-projects/clients-onderwijsloket/voorbereiden                                                                                        4:46:28 PM

  at loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:2577:11)
  at async Object.run (/Users/remihuigen/.nvm/versions/node/v18.18.0/lib/node_modules/nuxi/dist/chunks/prepare.mjs:58:18)
  at async runCommand$1 (/Users/remihuigen/.nvm/versions/node/v18.18.0/lib/node_modules/nuxi/dist/shared/nuxi.c6444792.mjs:1647:7)
  at async runCommand$1 (/Users/remihuigen/.nvm/versions/node/v18.18.0/lib/node_modules/nuxi/dist/shared/nuxi.c6444792.mjs:1638:11)
  at async runMain$1 (/Users/remihuigen/.nvm/versions/node/v18.18.0/lib/node_modules/nuxi/dist/shared/nuxi.c6444792.mjs:1770:7) 



 ERROR  Cannot find any nuxt version from /Users/remihuigen/local-projects/clients-onderwijsloket/voorbereiden                                                                                        4:46:28 PM

npm ERR! code 1
npm ERR! path /Users/remihuigen/local-projects/clients-onderwijsloket/voorbereiden
npm ERR! command failed
npm ERR! command sh -c nuxt prepare

npm ERR! A complete log of this run can be found in: /Users/remihuigen/.npm/_logs/2023-11-01T15_46_23_190Z-debug-0.log
```

**Comment by danielroe** [comment]
Any dependencies you need to be installed should be in the `dependencies` of the layer rather than `devDependencies`.

**Comment by owl1n** [comment]
Im using yarn@berry and published my layer to some npm registry. After installing fired postinstall script which throw error:

```
➤ YN0009: │ @some-package-layer::__archiveUrl=* couldn't be built successfully (exit code 127, logs can be found here: /private/var/folders/y_/zvctb7j10s15_grywfghjttr0000gn/T/xfs-7844c117/build.log)
```

log file contain:

```
# Script name: postinstall

command not found: nuxt
```

package.json of layer has nuxt in `dependecies`. Whats wrong?
