### ISSUE TITLE
Provide a way to scroll to top when route query changed

### ISSUE THREAD

**Issue by hareku** [nuxt/nuxt#24070]
### Describe the feature

On nuxt v3.8.0, vue-router doesn't scroll to top when route query changed even `scrollToTop` is set true.

e.g. navigated `/users?page=2` to `/users?page=3`

```ts
definePageMeta({
  key: (r) => r.fullPath,
  scrollToTop: true,
})
```

This is because `_isDifferentRoute` does not consider route query.
https://github.com/nuxt/nuxt/blob/d7b11164434e5ae318cd8cf85417362fddb99d71/packages/nuxt/src/pages/runtime/router.options.ts#L66

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by or2e** [comment]
Usually `scrollBehavior` is not affected by changing query parameters
I suggest you do it manually

```ts
const route = useRoute();
const scrollToTop = useScrollToTop(); // window.scrollTo(0, 0)
watch(
    () => route.query,
    scrollToTop,
);
```

Though maybe either set up your own `scrollBehavior` or create a PR + unit-test

**Comment by danielroe** [comment]
You can also provide your own within the page in question:

```ts
definePageMeta({
  scrollToTop(to, from) {
  }
})
```

Or create your own scrollBehavior: https://nuxt.com/docs/guide/going-further/custom-routing#using-approuteroptions.

Often query changes are used for things like filter selections and shouldn't result in a page scrolling to the top, so I wouldn't like to change the default behaviour on this one.
