### ISSUE TITLE
Using the fetch API causes the function type value of the data attribute to be modified during server rendering

### ISSUE THREAD

**Issue by kiss-keray** [nuxt/nuxt#24098]
### Environment

-----------------------------
- Operating System: macos
- Node Version:     v16.19.0
- Nuxt Version:     2.15.8, 2.17.2
------------------------------

### Reproduction

https://stackblitz.com/edit/github-qva7df?file=pages%2Findex.vue

### Describe the bug

When rendering on the server side, the type attribute is incorrect. It was supposed to have a value of function, but an object was returned

**Comment by danielroe** [comment]
Yes, this is because `fetch` stringifies the entire state of the component and passes it to the client within the HTML. Functions can't be stringified like this. It's a limitation of the `fetch()` hook, unfortunately.
