### ISSUE TITLE
API endpoints useRuntimeConfig(event) throws type errors with nuxt typecheck

### ISSUE THREAD

**Issue by mdarrik** [nuxt/nuxt#24095]
### Environment

Stackblitz + WSL

WSL Info: 

------------------------------
- Operating System: Linux
- Node Version:     v18.17.1
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@9.8.1
- Builder:          vite
- User Config:      devtools, typescript, modules, components, graphqlMiddleware, css, postcss, runtimeConfig, app, routeRules
- Runtime Modules:  @nuxt/image@1.0.0-rc.1, nuxt-graphql-middleware@4.0.0-beta.3
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-gscpb2?file=server%2Fapi%2Fhello.ts

### Describe the bug

Passing the event to useRuntimeConfig in server API routes causes typechecking to fail, despite being [encouraged in the docs](https://nuxt.com/docs/guide/going-further/runtime-config#server-routes)

1. Create an API route that uses `useRuntimeConfig(event)`
2. Run `npx nuxi typecheck` (or similar) 
3. Will fail with `Expected 0 arguments, but got 1.`

Note that stackblitz flags this as an error right in the editor too. 
![screenshot of the stackblitz error tooltip with the message "expected 0 arguments but got 1"](https://github.com/nuxt/nuxt/assets/30670444/59ec393d-ab2a-4243-8edc-3573e29ca19f)

### Additional context

1. ESLint + VS Code's internal typescript seem to be able to narrow the right type. (Clicking "Jump to Type Definition" navigates to the right type which accepts events).  I'm not sure why typechecking is failing there. 

### Logs

```shell-script
error TS2554: Expected 0 arguments, but got 1.

const { apiUrl } = useRuntimeConfig(event);
                                        
```
```

**Comment by productdevbook** [comment]
Yes, same problem

**Comment by youkei-zzz** [comment]
Yes, same problem

**Comment by danielroe** [comment]
resolved in https://github.com/nuxt/nuxt/pull/25440
