### ISSUE TITLE
Custom Elements defined in isCustomElement configuration, but warning issued when used in h()"

### ISSUE THREAD

**Issue by maximepvrt** [nuxt/nuxt#24104]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.8.0`
- CLI Version:      `3.9.1`
- Nitro Version:    `2.7.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `-`
- User Config:      `modules`, `experimental`, `ssr`, `vue`, `runtimeConfig`
- Runtime Modules:  `@nuxt/content@2.9.0`, `@nuxt/ui@2.10.0`, `@nuxthq/studio@0.14.1`, `nuxt-headlessui@1.1.4`, `@nuxt/devtools@1.0.0`, `nuxt-monaco-editor@1.2.3`
- Build Modules:    `-`

### Reproduction

- Define a custom element in the nuxt.config.ts file using the isCustomElement configuration.
```
Vue: {
        compilerOptions: {
            isCustomElement: (tag) => {
                return tag === 'mjml' || /^(Mj[A-Z]|mj-)/.test(tag);
            }
        }
    },
```
- Create a component in Nuxt.js, particularly an island component and use the h() function to create elements within the component with custom element tag.
```
<script lang="ts">
import { h } from 'vue'
import { ContentRendererMarkdown } from '#components'

export default defineComponent({
  props: {
    path: String,
  },
  async setup(props) {
    if (process.dev) {
      const { data } = await useAsyncData(() =>
          queryContent(props.path!).findOne()
    )
      return () => h(ContentRendererMarkdown, { value: data.value!, tag: 'mj-column' })
    }
    const value = await queryContent(props.path!).findOne()
    return () => h(ContentRendererMarkdown, { value, tag: 'mj-column' })
  },
})
</script>
```
(thanks @danielroe for this code https://roe.dev/blog/nuxt-server-components#case-study-nuxt-content)

Expected Behavior:
The custom element should be recognized and rendered without any error.

Actual Behavior:
The error Failed to resolve component: MjColumn occurs, indicating that the isCustomElement configuration is not being utilized in this context.

### Describe the bug

When creating elements using Vue's h() function within a Nuxt.js component, specifically in an island component, the isCustomElement configuration in the nuxt.config.js file doesn't seem to be recognized. As a result, the following error is encountered:

```
[Vue warn]: Failed to resolve component: MjColumn
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
```

**Comment by maximepvrt** [comment]
@danielroe https://codesandbox.io/p/sandbox/dazzling-rgb-qmzpm9 ;-)

**Comment by danielroe** [comment]
You also need to set this at runtime in a Nuxt plugin.

**Comment by maximepvrt** [comment]
I'm not sure I understand @danielroe

**Comment by huang-julien** [comment]
@maximepvrt that's because the config from the build config is only passed to the vue compiler at build time for performance reasons. 
As @danielroe said, you need to configure this in a plugin since it is ran before mounting the app. You can access to the vue app instance through `nuxtApp.vueApp.config`

**Comment by maximepvrt** [comment]
Thanks @huang-julien !
I'm updated my example with a plugin, but vue compilerOptions are not used https://codesandbox.io/p/sandbox/practical-colden-trz6sd, an idea why ?

**Comment by danielroe** [comment]
Checking, this is coming from `@nuxtjs/mdc`: https://github.com/nuxt-modules/mdc/blob/main/src/runtime/components/MDCRenderer.vue#L304-L317. Directly calling `resolveComponent` (as that code does) will not respect any custom element configuration.

Also note that `vue.compilerOptions.isCustomTag` in your `nuxt.config` is only used for compiling `<template>` -> render functions. However note that this kind of thing works fine without any configuration:

```ts
defineComponent({
  render() {
    return h('mjml')
  }
})
```
