### ISSUE TITLE
Internal server error: URI malformed

### ISSUE THREAD

**Issue by nhatimme** [nuxt/nuxt#24105]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v16.16.0
- Nuxt Version:     3.7.1
- CLI Version:      3.8.1
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.10
- Builder:          -
- User Config:      ssr, build, routeRules, postcss, modules, i18n, app, runtimeConfig, css
- Runtime Modules:  @pinia/nuxt@0.4.11, @nuxtjs/i18n@8.0.0-rc.4
- Build Modules:    -
------------------------------

### Reproduction
https://stackblitz.com/edit/github-9ukebr-wqhcss?file=pages%2Findex.vue,pages%2F[...slug].vue

Using: ip:3000/test?test=100% (Goes correct, no crashes)
Using: ip:3000/test/?test=100% (Nuxt/Node crashes)

In our opinion it should not crash.

### Describe the bug

It crashes the complete NUXT/NODE. We have to restart the hole application to make sure it works again.

### Logs

```shell-script
ERROR  Internal server error: URI malformed                                        14:40:57  
      at decodeURI (<anonymous>)
      at viteTransformMiddleware (file:///C:/Users/Nick/Desktop/ES%20Webshop%20NUXT/webshop/node_modules/vite/dist/node/chunks/dep-df561101.js:64233:19)
      at call (file:///C:/Users/Nick/Desktop/ES%20Webshop%20NUXT/webshop/node_modules/vite/dist/node/chunks/dep-df561101.js:50613:7)
      at next (file:///C:/Users/Nick/Desktop/ES%20Webshop%20NUXT/webshop/node_modules/vite/dist/node/chunks/dep-df561101.js:50557:5)
      at handle (file:///C:/Users/Nick/Desktop/ES%20Webshop%20NUXT/webshop/node_modules/@nuxt/vite-builder/dist/shared/vite-builder.9e5595a0.mjs:589:9)
      at call (file:///C:/Users/Nick/Desktop/ES%20Webshop%20NUXT/webshop/node_modules/vite/dist/node/chunks/dep-df561101.js:50613:7)
      at next (file:///C:/Users/Nick/Desktop/ES%20Webshop%20NUXT/webshop/node_modules/vite/dist/node/chunks/dep-df561101.js:50557:5)
      at file:///C:/Users/Nick/Desktop/ES%20Webshop%20NUXT/webshop/node_modules/vite/dist/node/chunks/dep-df561101.js:47453:28
      at viteServePublicMiddleware (file:///C:/Users/Nick/Desktop/ES%20Webshop%20NUXT/webshop/node_modules/vite/dist/node/chunks/dep-df561101.js:47583:9)
      at call (file:///C:/Users/Nick/Desktop/ES%20Webshop%20NUXT/webshop/node_modules/vite/dist/node/chunks/dep-df561101.js:50613:7) (x3)

[Vue Router warn]: Error decoding "100%". Using original value
```

**Comment by danielroe** [comment]
are you aware you're using a pre release version of nuxt? we've had the official release of nuxt 3 and 8 more minor releases since then 

when updated, your repro works fine: https://stackblitz.com/edit/github-9ukebr-3rupby?file=assets/main.css,package.json

**Comment by nhatimme** [comment]
I just updated to 3.8.0. Still same issue:

IP:3000/test?test=100% throws an modal (vite) with the error. Then It redirects to error.vue. 
When using ip:3000/test/?test=100% it crashes the hole application.

When you press F5 (when it's freezed) you see the NUXT introduction page.
We need to restart the hole application to make sure it works again.

In build version same issue.

**Comment by danielroe** [comment]
Would you provide a reproduction so I can see the issue?

https://stackblitz.com/github/nuxt/starter/tree/v3/

**Comment by danielroe** [comment]
The issue in _dev_ mode is not Nuxt related.

**Comment by nhatimme** [comment]
Done: https://stackblitz.com/edit/github-x3bbih?file=pages%2F%5B...slug%5D.vue. Steps:
- pages/[...slug].vue
- pages/index.vue

IP:3000/test?test=100% throws an modal (vite) with the error. Then It redirects to error.vue.
When using ip:3000/test/?test=100% it crashes the hole application.

Its freezing, to make sure the application runs again, we stop it and start it again. (Production/Build mode)

**Comment by danielroe** [comment]
Run `pnpm build && pnpm preview`. It does not show this behaviour.

**Comment by nhatimme** [comment]
Thanks. I also tried and Im not getting the same problem as we have. I just upgraded it to 3.8.0 and have the sort of same setup in basic.

When I navigate to: `3000/test/?test=100%` - my middleware console.logs this: (And it is an infitine loop!!!!!!). How is that possible?
```

middleware init global
undefined
FROM
{
  fullPath: '/test/?test=100%',
  path: '/test/',
  query: { test: '100%' },
  hash: '',
  name: 'slug',
  params: { slug: [ 'test', '' ] },
  matched: [
    {
      path: '/:slug(.*)*',
      redirect: undefined,
      name: 'slug',
      meta: [Object],
      aliasOf: undefined,
      beforeEnter: undefined,
      props: [Object],
      children: [],
      instances: {},
      leaveGuards: Set(0) {},
      updateGuards: Set(0) {},
      enterCallbacks: {},
      components: [Object]
    }
  ],
  meta: { layout: 'page' },
  redirectedFrom: undefined,
  href: '/test/?test=100%'
}
TO
{
  fullPath: '/test/?test=100%25',
  hash: '',
  query: { test: '100%' },
  name: 'slug',
  path: '/test/',
  params: { slug: [ 'test', '' ] },
  matched: [
    {
      path: '/:slug(.*)*',
      redirect: undefined,
      name: 'slug',
      meta: [Object],
      aliasOf: undefined,
      beforeEnter: undefined,
      props: [Object],
      children: [],
      instances: {},
      leaveGuards: Set(0) {},
      updateGuards: Set(0) {},
      enterCallbacks: {},
      components: [Object]
    }
  ],
  meta: { layout: 'page' },
  redirectedFrom: {
    fullPath: '/test/?test=100%25',
    hash: '',
    query: { test: '100%' },
    name: 'slug',
    path: '/test/',
    params: { slug: [Array] },
    matched: [ [Object] ],
    meta: { layout: 'page' },
    redirectedFrom: undefined,
    href: '/test/?test=100%25'
  },
  href: '/test/?test=100%25'
}
middleware init global
```

**Comment by danielroe** [comment]
can you reproduce it?

**Comment by nhatimme** [comment]
Well, I tried to reproduce it at a minimal, sort of same as you already checked. But can't reproduce it. I would love to share my screen so you can see it.

**Comment by danielroe** [comment]
I'm afraid I don't have time right now to screen share but I would investigate your middleware and make sure you're not redirecting the page yourself. Or feel free to share a screen recording with me directly if you think that will help. (But normally it's not as useful as it might seem.)
