### ISSUE TITLE
Vue Router "no match found" warning when using path from routeRules in NuxtLink

### ISSUE THREAD

**Issue by lwpinion** [nuxt/nuxt#24112]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@9.6.1
- Builder:          -
- User Config:      app, build, components, css, devtools, devServer, experimental, hooks, imports, modules, pinia, plugins, routeRules, runtimeConfig, telemetry, vite
- Runtime Modules:  @pinia/nuxt@0.4.11, @nuxt/devtools@0.5.5
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-vppyrh-tbnswt?file=app.vue

### Describe the bug

We have started using routeRules consistently for our redirects. Personally, I really like the concise format of the feature.

However, it seems that the routes are generated in a way that Vue Router still deems it necessary to create warnings in the console when using linking to any given path using `NuxtLink`. We have these rules in place to create simple URLs that redirect to complex search queries on our products page. Likewise, we link to the "simplified" routes in our footer for SEO purposes.

For example, we might have a routeRule like the following:
`'/media/backgrounds': { redirect: { to: '/media/filters/category/Backgrounds', statusCode: 301 } },`

We use `<NuxtLink to="/media/backgrounds">Backgrounds</NuxtLink>` in our footer, but receive an error saying:
`[Vue Router warn]: No match found for location with path "/media/backgrounds"`

I have provided a minimal reproduction that clearly shows what is happening, but please let me know if anymore information is needed.

Thanks!

**Comment by naveeng2402** [comment]
Hi @danielroe I'm really interested in fixing the bug, can you guide me in the right direction
