### ISSUE TITLE
shortcuts link problem in Deployment

### ISSUE THREAD

**Issue by ys928** [nuxt/nuxt#24124]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.9.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  npm@10.1.0
- Builder:          -
- User Config:      modules, devtools, nitro, vite
- Runtime Modules:  @element-plus/nuxt@1.0.6
- Build Modules:    -

### Reproduction

This may seem like a simple question

### Describe the bug

after I use [archiver](https://www.npmjs.com/package/archiver) compress the .output directory and upload it to my server,I use `unzip -od tmp/ output.zip` to uncompress it。

it will mention：
```
.....
finishing deferred symbolic links:
  tmp/server/node_modules/lru-cache -> .nitro\lru-cache@8.0.5
  tmp/server/node_modules/named-placeholders/node_modules/lru-cache -> ..\..\.nitro\lru-cache@7.18.3
```
when I run `node tmp/server/index.mjs` and visit the website,I get a lot of errors.

I guess the reason is that the shortcuts link between the systems are different.

![image](https://github.com/nuxt/nuxt/assets/80371119/ad78b60f-efed-4eb1-8330-691322b96854)

Using [freefilessysn](https://freefilesync.org/)  direct synchronization directory  can also lead to the same problems.

So can you package without using shortcut links?

**Comment by danielroe** [comment]
tracking upstream.

**Comment by acidleaf** [comment]
I'm also facing the same problem. @ys928 did you manage to find a workaround for this?

**Comment by ys928** [comment]
> I'm also facing the same problem. @ys928 did you manage to find a workaround for this?

Yes, later I used WSL and used zip to compress files locally, unzip to extract files on the cloud server, and scp to transfer files between the local WSL and the server. @acidleaf

**Comment by acidleaf** [comment]
> > I'm also facing the same problem. @ys928 did you manage to find a workaround for this?
> 
> Yes, later I used WSL and used zip to compress files locally, unzip to extract files on the cloud server, and scp to transfer files between the local WSL and the server. @acidleaf

I see, I shall try that approach, though I would need to build my files into a Docker container. Thanks!
