### ISSUE TITLE
Unable to fetch records in SSR mode from server side on Page reload or refresh return data as null

### ISSUE THREAD

**Issue by select-good-way** [nuxt/nuxt#24120]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.18.2
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      ssr, devtools, build, runtimeConfig, components, css, modules, nuxtSvgIcons, swiper, quasar
- Runtime Modules:  @nuxtjs/tailwindcss@6.9.3, nuxt-quasar-ui@2.0.6, @nuxtjs/fontaine@0.4.1, @nuxtjs/i18n@8.0.0-rc.5, @nuxtjs/google-fonts@3.0.2, @pinia/nuxt@0.4.11, nuxt-swiper@1.2.2, @nuxt/image@1.0.0, nuxt-svg-icons@1.23.1
- Build Modules:    -
------------------------------

### Reproduction

-----------

### Describe the bug

const {pending,data:productListData, error, refresh } = await useFetch(
  '/api/product/fetch-products',
  {
    onRequest({ request, options }) {
      options.baseURL = config.public.apiBase
      options.method = 'GET'
      options.cache = 'no-cache'
      options.initialCache = false
      options.params = { page: page.value, itemsPerPage: itemsPerPage.value }

      options.key = hash(['fetch-properties',getKeyForFetch.value]) // getKeyForFetch.value is computed property which return timestamp
  
    },
    onRequestError({ request, options, error }) {
      // Handle the request errors
    },
    async onResponse({ request, response, options }) {
    
    

        productList. product = []
        productList.product = [...response._data.data]
     
    },
    onResponseError({ request, response, options }) {
     
    },
  }
)

**Comment by select-good-way** [comment]
<template>
{{  productList.product }}
</template>
<script setup async>

let productList =ref( {
product : [] 
})
const {pending,data:productListData, error, refresh } = await useFetch(
'/api/product/fetch-products',
{
onRequest({ request, options }) {
options.baseURL = config.public.apiBase
options.method = 'GET'
options.cache = 'no-cache'
options.initialCache = false
options.params = { page: page.value, itemsPerPage: itemsPerPage.value }

  options.key = hash(['fetch-properties',getKeyForFetch.value]) // getKeyForFetch.value is computed property which return timestamp

},
onRequestError({ request, options, error }) {
  // Handle the request errors
},
async onResponse({ request, response, options }) {



    productList.product = []
    productList.product = [...response._data.data]
 
},
onResponseError({ request, response, options }) {
 
},
}
)
</script>

my node version is v18.16.0

only this much is the code it's working proper on local after build not fetching data on page refresh/reload I am using pm2

please assist the solution

**Comment by dargmuesli** [comment]
Hey, please provide a full reproduction using stackblitz or codesandbox. Without that we're unable to help as e.g. we cannot imagine the api route's code. We can reopen this issue once a full minimal reproduction is provided :)

**Comment by Jogiter** [comment]
it seems the async onResponse inteceptor do not return anything, so when nothing will return when useFetch is done
