### ISSUE TITLE
cannot get route params when navigate to new page

### ISSUE THREAD

**Issue by docodocool** [nuxt/nuxt#24129]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.8.1
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  pnpm@8.9.0
- Builder:          -
- User Config:      devtools, modules, components, content
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @nuxt/content@2.9.0
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-zotksb-koaelc?file=app.vue

### Describe the bug

click link on index page and navigate to "/practice/1", and target page cannot get route.params.id

**Comment by manniL** [comment]
Your app.vue should be using `NuxtPage` like [the default one](https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/pages/runtime/app.vue)
