### ISSUE TITLE
devProxy does not Proxy Websockets

### ISSUE THREAD

**Issue by evans23** [nuxt/nuxt#24134]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  npm@9.8.1
- Builder:          -
- User Config:      routeRules, runtimeConfig, components, dir, imports, css, build, modules, nitro, devtools
- Runtime Modules:  @pinia/nuxt@0.4.11, nuxt-gtag@1.1.1
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-xwvyvm?file=app.vue

Websockets appear blocked in online setup. If run locally, note that proxy is not attempted to fake http address (error expected).

### Describe the bug

Websocket connections are not listened for when configured into Nitro devProxy.

### Logs

```shell-script
Each WebSocket connection fails without reaching intended target.
```

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/cli/issues/107.
