### ISSUE TITLE
nuxt3 useHead title String Escape

### ISSUE THREAD

**Issue by slow-sheep** [nuxt/nuxt#24138]
### Environment

nuxt : 3.6.5

### Reproduction

[https://www.igv.com/items/276662411227344 view](view-source:https://www.igv.com/items/276662411227344)
![image](https://github.com/nuxt/nuxt/assets/117260282/e6367868-376b-4561-99c7-713aa6fe9f6a)

### Describe the bug

I used useHead to add webpage SEO tags, but as long as the symbol of the title tag is escaped. You can view the title and meta tags in the link to reproduce bugs

**Comment by danielroe** [comment]
cc: @harlan-zw

**Comment by harlan-zw** [comment]
The page you linked looks like it's displaying correctly.

Tokens need to be encoded within the HTML <title>, they will be decoded within the title bar. 

Going to close but please let me know if I missed something.

**Comment by slow-sheep** [comment]
> 您链接的页面看起来显示正确。
> 
> 令牌需要在 HTML <title> 中进行编码，它们将在标题栏中进行解码。
> 
> 即将关闭，但如果我错过了什么，请告诉我。

我不需要转义，只要展示原本的符号就好了。

**Comment by slow-sheep** [comment]
> 您链接的页面看起来显示正确。
> 
> 令牌需要在 HTML <title> 中进行编码，它们将在标题栏中进行解码。
> 
> 即将关闭，但如果我错过了什么，请告诉我。

你应当在链接的源代码中查看这个title标签，我现在依然是转义的情况，我不需要转义，这导致了seo方面有巨大的缺陷

**Comment by harlan-zw** [comment]
This will not lead to any flaws in SEO, the title should be encoded to avoid XSS

```html
<title><img title="</title><img src onerror=alert(1)>"></title>
```

**Comment by slow-sheep** [comment]
<title>【Season 1】[PC&#x2F;PS5&#x2F;XBOX]-Help Find Tempest Roar -[100% Makes You Get him]-[Druid Unique Item] - iGV</title> 你是不是看错了？？？ 链接中网页源代码的title是这个，[PC&#x2F;PS5&#x2F;XBOX]这一段文本里面的/被转义了，我不想转义。

> 这不会导致任何 SEO 缺陷，标题应该进行编码以避免 XSS
> 
> ```
> <title><img title="</title><img src onerror=alert(1)>"></title>
> ```
