### ISSUE TITLE
The latest version of nuxt3 deployment server ran an error: This page is temporarily unavailable

### ISSUE THREAD

**Issue by xxwangkaimin** [nuxt/nuxt#24133]
### Environment

Nodejs：v18.1.0
```json
{
"devDependencies": {
    "@nuxt/devtools": "latest",
    "@types/node": "^20.8.9",
    "nuxt": "^3.8.0",
    "typescript": "^5.2.2",
    "vue": "^3.3.7",
    "vue-router": "^4.2.5"
  },
  "dependencies": {
    "@nuxt/ui": "^2.9.0",
    "ohash": "^1.1.3",
    "sass": "^1.69.4"
  }
}
```

### Reproduction

https://stackblitz.com/edit/github-nf5wwj?file=nuxt.config.ts

### Describe the bug

Can display data normally in the development environment.Prompt that this page is temporarily unavailable after deploying the server

**Comment by danielroe** [comment]
Checking the reproduction locally, it seems to work fine.

**Comment by xxwangkaimin** [comment]
> Checking the reproduction locally, it seems to work fine.

Local development runs normally, but packaging and deploying it to the server does not work.

**Comment by xxwangkaimin** [comment]
> Would you be able to provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
> 
> More info

https://stackblitz.com/edit/github-nf5wwj?file=nuxt.config.ts

**Comment by dl-ias** [comment]
Same issue with Nuxt 3.8.1

**Comment by danielroe** [comment]
@xxwangkaimin I checked and ran that reproduction locally (`nuxi build && nuxi preview`) and everything seemed to work fine.

@dl-ias Your issue seems to be different - maybe you also have vue 2 installed in your project - or possibly multiple versions of vue 3?

**Comment by dl-ias** [comment]
> @dl-ias Your issue seems to be different - maybe you also have vue 2 installed in your project - or possibly multiple versions of vue 3?

No. Any vue2 in project. And actually my problem was solved by reupgrade nuxt with `pnpx nuxi upgrade --force`

**Comment by maartentibau** [comment]
Having the same issue, with upgrading from `3.7.5` to `3.8.1` ... error are not really explaining what is going wrong, pretty frustrating.

```bash
{"url":"/api/server","statusCode":500,"statusMessage":"","message":"Cannot find module '/Users/maarten/my-app/desktop-app/packages/app.nuxt/.output/server/functions/node_modules/vue/server-renderer/index.mjs' imported from /Users/maarten/my-app/desktop-app/packages/app.nuxt/.output/server/functions/chunks/handlers/renderer.mjs","stack":""}
```

**Comment by danielroe** [comment]
This sounds like maybe the issue is multiple versions of Vue (because there was a vue version upgrade at the same time). That would explain why `npx nuxi@latest upgrade --force` resolves it.

**Comment by maartentibau** [comment]
Thanks for your quick response @danielroe but I have tried that one already. But how can one have `multiple` vue versions?
Do you mean it in the sense like other dependencies that also use vue as a dependency? For example `primevue` or `vue-i18n` ?

Should I scan my `lock` file to verify?

**Comment by danielroe** [comment]
yes, exactly! Or even because your package manager keeps a second version around. you can try `pnpm why vue` or `npm why vue`.

**Comment by xxwangkaimin** [comment]
> yes, exactly! Or even because your package manager keeps a second version around. you can try `pnpm why vue` or `npm why vue`.
I executed the command pnpm why Vue and found that the versions of Vue are consistent, all versions are 3.3.7.

**Comment by xxwangkaimin** [comment]
@danielroe I executed the command pnpm why Vue and found that the versions of Vue are consistent, all versions are 3.3.7.

**Comment by fmoessle** [comment]
Same here

**Comment by chenyuncai** [comment]
has same error in nuxt@3.8.1, checked pnpm-lock.yaml and no vue2 found.

```

nuxt-template-nuxt-template-1  | [nuxt] [request error] [unhandled] [500] Cannot find module '/app/.output/server/node_modules/vue/server-renderer/index.mjs' imported from /app/.output/server/chunks/handlers/renderer.mj
```

```
$ pnpm list | grep vue
@vueuse/core 10.6.1
vue 3.3.8
vue-router 4.2.5
```

**Comment by xxwangkaimin** [comment]
@chenyuncai If the server is using PM2, check if it is the latest version. If not, upgrade it. Upgrading my PM2 to the latest version no longer has this issue.
```bash
# Install latest PM2 version
$ npm install pm2@latest -g
# Save process list, exit old PM2 & restore all processes
$ pm2 update
```

**Comment by chenyuncai** [comment]
this works for me too. @xxwangkaimin 
```
pnpx nuxi upgrade --force
```

**Comment by xxwangkaimin** [comment]
@chenyuncai I'm not sure if this operation will affect server deployment.

**Comment by whcxxb** [comment]
Why are there so many transition bugs

**Comment by xxwangkaimin** [comment]
@whcxxb I don't know why either. But upgrading PM2 to the latest version did solve this problem.

**Comment by PdxLook** [comment]
This problem is also encountered, but upgrading PM2, the error still exists

**Comment by develth** [comment]
also happens locally, when doing `yarn build` and then  `node .output/server/index.mjs` or `yarn node .output/server/index.mjs`.
Node version is `v20.5.1`
