### ISSUE TITLE
Nuxt 3 Migration Docs: Add error handling

### ISSUE THREAD

**Issue by bmulholland** [nuxt/nuxt#24140]
Nuxt 3 has new error handling that isn't included in the migration docs.

Easy one: context.error({ statusCode, message }) which (I assume) -> showError

Stretch goal: what else is there?

**Comment by pravintargaryen** [comment]
Hi @bmulholland. Please assign this to me

**Comment by OctopussyO** [comment]
Hi! Will there be any updates?

**Comment by bobrov-site** [comment]
@bmulholland are we talking about this feature https://nuxt.com/docs/getting-started/error-handling ?

**Comment by bmulholland** [comment]
I don't recall, and I switched off of Nuxt so I don't want to spend more time on it. Sorry! Will let someone else open a new Issue if they can add the detail.
