### ISSUE TITLE
404 error on dynamic page

### ISSUE THREAD

**Issue by echocage123** [nuxt/nuxt#24152]
### Environment

- Operating System: Windows_NT
- Node Version:     v16.19.1
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  npm@8.19.3
- Builder:          -
- User Config:      render, vuetify, head, env, components, devtools, build, devServer, nitro, buildModules, modules, sitemap, optimization, runtimeConfig
- Runtime Modules:  nuxt-simple-sitemap@3.4.1
- Build Modules:    @averjs/nuxt-compression@1.2.2

### Reproduction

https://github.com/echocage123/productmanagementautomator-frontend

### Describe the bug

The problem is that on all dynamic routes I am seeing a 404 error return when the page is rendered normally - that is, the page is rendered correctly, but the page itself returns a 404 error. 

It is worth saying that this happens exclusively on dynamic routes. Regardless of the content of the page. Moreover, 404 error is returned exactly in production mode - there is no problem in dev mode.

And it is this problem that makes it impossible to send my dynamic pages to google sitemap analysis.

I also tried changing some configuration settings - enable and disable ssr, disable all site modules and plugins, and so on - but nothing helped

_By the way the same problem occurs on a full server (ubuntu), which right now is running on a domain and is available on the internet_

![image](https://github.com/nuxt/nuxt/assets/67440446/6017dfeb-403e-4183-94b3-92fd17a21fec)
![image](https://github.com/nuxt/nuxt/assets/67440446/f0de8f92-5f04-421e-ba5a-2a221b121ad0)
![image](https://github.com/nuxt/nuxt/assets/67440446/ffbec170-b3a6-45f5-90cd-fc0a4c610400)

### Additional context

For production builds, I use:
npx nuxi build
npx nuxi generate

**Comment by danielroe** [comment]
Where are you deploying your site? The 404 response is coming from the provider, not from Nuxt, as there is no Nuxt server to send the response. The reason is that no file that matches the request directly. Some providers allow you to configure the response, so I would investigate your provider documentation or raise an issue with them.

**Comment by echocage123** [comment]
I'm not sure what you mean by "provider". If it is a web server, I use nginx, with standard settings from the documentation (https://v2.nuxt.com/deployments/nginx/).

Maybe you mean assets/ or providers/ - I don't have either of them

Also here is a link to a page where you can see this error yourself: https://element-of-beautiful.ru/product/kniga-plakat-v-politprosvetrabote-gercenberg

**Comment by danielroe** [comment]
Yes, I think it is an issue with your `nginx` settings. You can perhaps configure nginx to return a 200 response when serving a `404.html`.

**Comment by echocage123** [comment]
This is the problem, I also run the build in production mode locally - that is, without a web server, and still get 404. But I will still try to find some patch options via nginx
