### ISSUE TITLE
Weird behavior when loading runtime values inside a plugin 

### ISSUE THREAD

**Issue by kasvith** [nuxt/nuxt#24155]
### Environment

Nuxt project info: (copied to clipboard)                                                                      12:17:03 AM

------------------------------
- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.8.1
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  npm@9.5.1
- Builder:          -
- User Config:      devtools, modules, googleSignIn
- Runtime Modules:  nuxt-vue3-google-signin@0.0.10
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                   12:17:03 AM

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://n

### Reproduction

SB: https://stackblitz.com/edit/github-7tvhqt-cjjnim?file=app.vue

Repo: https://github.com/kasvith/nuxt-vue3-google-signin-reproduce-bug

**Note**: Use the repo as it provides some information on this behavior

### Describe the bug

As users reported recently we got an issue with our plugin while loading runtime config in dev mode of nuxt.
Most users were facing this issue randomly(sometimes it works, sometimes it doesn't) and it was very hard for us to even find whats wrong with our plugin.

https://github.com/wavezync/nuxt-vue3-google-signin/blob/89e5ffcb5aa6761331c6775a4199caf3b76fed02/src/runtime/plugin.ts#L3-7

In our plugin we simply inject a value from runtime config to our standalone plugin.

```js
import { defineNuxtPlugin, useRuntimeConfig } from '#app'

export default defineNuxtPlugin(async (nuxtApp) => {
  const { googleSignIn } = useRuntimeConfig().public
  if (googleSignIn) {
    const plugin = await import('vue3-google-signin')
    nuxtApp.vueApp.use(plugin.default, { clientId: googleSignIn.clientId })
  }
})
```

and as user reports, the injected value randomly disappears and it make plugin unusable in dev mode.

**Weird behavior**

By adding a simple `console.log` in the `node_modules/nuxt-vue3-google-signin/dist/runtime/plugin.mjs` it makes the plugin work normally

```js
import { defineNuxtPlugin, useRuntimeConfig } from '#app'

export default defineNuxtPlugin(async (nuxtApp) => {
  console.log('here is a log') // this line fixed the issue
  const { googleSignIn } = useRuntimeConfig().public
  if (googleSignIn) {
    const plugin = await import('vue3-google-signin')
    nuxtApp.vueApp.use(plugin.default, { clientId: googleSignIn.clientId })
  }
})
```

I was discussing this with @danielroe in discord before posting this issue here.

**Related Issues**:
https://github.com/wavezync/nuxt-vue3-google-signin/issues/14
https://github.com/wavezync/nuxt-vue3-google-signin/issues/11

**Comment by zola33dsf** [comment]
Hi,
After upgrading from Nuxt v3.8.2 to the latest release of Nuxt v3.9.0 the issue came back..

**Comment by kasvith** [comment]
Hi @danielroe is this a problem with the dev server module loading?

**Comment by frasza** [comment]
@kasvith @danielroe Any ideas around the issue here? We recently had issue even on production environment.

**Comment by danielroe** [comment]
I cannot reproduce this with the link above.
