### ISSUE TITLE
Use class mode. Don't support anonymous class

### ISSUE THREAD

**Issue by ValueLan** [nuxt/nuxt#24159]
### Environment

https://stackblitz.com/edit/github-hifsq1-kbgrdz?file=app.vue

### Reproduction

https://stackblitz.com/edit/github-hifsq1-kbgrdz?file=app.vue

### Describe the bug

Use class mode. Don't support anonymous class

### Logs

```shell-script
/home/projects/github-hifsq1/app.vue:27:7: ERROR: Multiple exports with the same name "default"
```

**Comment by danielroe** [comment]
This isn't a Nuxt issue; it's reproducible with Vue 3 + `vue-facing-decorator`: https://stackblitz.com/edit/github-ktwbgn?file=src/App.vue.

I would suggest raising an issue upstream, either in http://github.com/vuejs/core/ or https://github.com/vitejs/vite-plugin-vue.
