### ISSUE TITLE
`setup` being executed again after useAsyncData triggered by watch data source

### ISSUE THREAD

**Issue by bchen1029** [nuxt/nuxt#24179]
### Environment

```
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.1
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
```

### Reproduction

online link: https://stackblitz.com/edit/github-rgp9a2-8enc26?file=pages%2Fproduct%2F%5Bpid%5D.vue

step: 
1. click `product 1` link
2. open devtools and in `Console` tab, it should logged `[fire]`
3. click `next product` link
4. in `Console` tab, `[fire]` logged again means `setup` script is being executed again

In this case,
`computedDataBaseOnApi` should be the correct one
and `simpleDataBaseOnApi` should be the incorrect data for losing the `connection` with `res` without being wrapped by `computed`.

### Describe the bug

After `useAsyncData` refetched data when watch data changed, the whole `setup` script is being executed again.
According to my understanding `setup` should only be executed once.

Not sure if this is a bug need to fixed cause this is little confused.
If so, happy and willing to open a PR and try to fix it. 
Thank you guys.

**Comment by huang-julien** [comment]
Hello ! the page is reinstantiated on page change so it is normal for the setup function to be rerun.

**Comment by bchen1029** [comment]
@huang-julien 
Sorry, I got confused here.
When page Paramus changed.
Shouldn’t vue reuse the page component and only called useAsyncData agained?
Could not understand that why page component is reinstantiated, is there any reference in doc?

**Comment by huang-julien** [comment]
@bchen1029 Vue should indeed not reload the page component since it is the same. However, changing params is still technically a page change so we do force refresh it. 
If you really need it to not change, you can set a `page-key` on `NuxtPage` : `<NuxtPage :page-key="some-key" />`

**Comment by bchen1029** [comment]
@huang-julien Oops...my bad! just founded that in [nuxt2 doc](https://v2.nuxt.com/docs/directory-structure/pages#key), and [nuxt3 doc](https://nuxt.com/docs/api/components/nuxt-page#example). 

btw, I think the default `page-key` value might be an important info to everyone.
It is clear in [nuxt2 doc](https://v2.nuxt.com/docs/directory-structure/pages#key), hope we could also have this info in nuxt3!

really appreciate for your help! Thank you.

**Comment by huang-julien** [comment]
:+1: yes, actually it is on the NuxtPage component's documentation
