### ISSUE TITLE
Localhost not displaying nuxt app and showing 503 error (Service Unavailable)

### ISSUE THREAD

**Issue by Ranecodes** [nuxt/nuxt#24170]
### Environment

**Operating System:** Windows 11
**Node Version:** v20.9.0
**Nuxt Version:** 3.6.1

### Reproduction

I'm not sure I can reproduce a 503 (Service Unavailable) error because it seems to be a server-side issue.

### Describe the bug

After running `npm run dev` command in my vs code terminal, it displays the local host link: `http://localhost:3000/ ` and network link.
When I click on the local host link, the Nuxt app does not display. Instead, it is stuck on the Nuxt screen forever. 
![Screenshot 2023-11-07 155459](https://github.com/nuxt/nuxt/assets/74962989/1ecc63db-a9cf-40df-9ea7-69ae53e3af3e)

In the console, this error is displayed: `Failed to load resource: the server responded with a status of 503 (Service Unavailable)` `GET http://localhost:3001/ 503 (Service Unavailable)`

### Additional context

Sometimes it displays, a lot of times it does not. It worked last week(the nuxt app displayed), but now it is now working and I have not made any changes to the code.

### Logs

```shell-script
Failed to load resource: the server responded with a status of 503 (Service Unavailable)
(index):88 
        
        
GET http://localhost:3000/ 503 (Service Unavailable)
```

**Comment by MkLHX** [comment]
Hi there same thing here on fresh install on macos sonoma

**Comment by manniL** [comment]
That's normal during start. Check your terminal for errors / info though.

**Comment by MkLHX** [comment]
@manniL please Check example repo there is nothing in terminal when start fresh project

**Comment by manniL** [comment]
@MkLHX Can't reproduce with your test repo.
<img width="1696" alt="image" src="https://github.com/nuxt/nuxt/assets/640208/918d4b61-547e-4a5d-9d05-f1f972792314">
<img width="1163" alt="image" src="https://github.com/nuxt/nuxt/assets/640208/e536963e-d3c4-4d37-938a-aedefe88032f">
<img width="266" alt="image" src="https://github.com/nuxt/nuxt/assets/640208/667f925a-5e2e-4003-8e03-9686ae6c83eb">

**Comment by Curs3W4ll** [comment]
I have the exact same problem here

**Comment by Curs3W4ll** [comment]
Okay, I resolved my issue,

You just need to restart your Mac, this fixed this permission issue for me

**Comment by SauceDoctR914** [comment]
I restarted my mac and it did nothing for me, i'll have to keep digging. 

Failed to load resource: the server responded with a status of 503 (Service Unavailable)Understand this error
localhost/:1

**Comment by SauceDoctR914** [comment]
for me using pnpm was the issue, switched back to npm and its fine.

**Comment by jonas-lomholdt** [comment]
I'm also suddenly getting this error. I have tried all of the above but can't make it respond. Sometimes it works for a few seconds before it stops. I'm using `bun` though, on a M1 Mac.

**Comment by davidboom95** [comment]
Tried `npm` & `yarn`, no luck

If it helps, for me is happening after upgrading Mac OS to Sequoia 15.1

**Comment by nedosekinstanislav** [comment]
I encountered the same problem, has anyone solved it yet? OC Windows 10

**Comment by beierzhijin** [comment]
same problem, and suddenly it became like this.

**Comment by beierzhijin** [comment]
Sometimes normal, sometimes error

**Comment by kalnode** [comment]
Happening to me as well, suddenly.

Everything was working fine all morning, now I'm troubleshooting this Nuxt 503 and spinning my wheels.

**Notes:**
All of my other services are running.

A few days ago I updated all of my Nuxt project packages to their latest versions. Everything has been working fine for days.

I've tried:

- Rebooting
- Deleting `node_modules` and re-installed (`npm install`)
- Deleting `.nuxt` and re-run
- Private browser window
- Reverting to previous commit

503 remains.

**Possibly unrelated:**

The last thing I remember doing before this commotion was running `build` to troubleshoot something (a 404 error from my `server/api/` folder). Build failed with the below error, but the error could have been long-standing (days, weeks, etc); I don't know:

`ERROR  RollupError: [plugin impound] Vue app aliases are not allowed in server runtime. [importing #build/app.config.mjs from node_modules/nuxt/dist/app/config.js]`

I now notice the error appear during run dev as well; again may have been long-standing and unrelated.

**Comment by kalnode** [comment]
**UPDATE:**

Nuxt works again after reverting to an old commit just before I updated package versions earlier this week. When running this old commit, the "RollupError" error message does not occur but that could be unrelated. Build is clean.

When I switch back to current commit (with updated package versions and a few commits ahead) Nuxt still runs fine, even though I'm seeing the "RollupError" error message (again, possibly unrelated).

When I run build, everything breaks again (503 error).

**Comment by Xnasav** [comment]
I use yarn on a Mac with Intel chip and had this issue in two different projects now. I tried the steps mentioned above as well (reinstalling everything). However in the end I executed `yarn generate` (nuxt generate) once and afterwards started the dev server. This  seems to have somehow fixed the issue (at least for now).

**Comment by idorenyinudoh** [comment]
hey — if you're still experiencing this problem, it's most likely because you're making use of a composable outside the nuxt context.
look [here](https://github.com/nuxt/nuxt/issues/15188#issuecomment-1434628265).

**Comment by lixiaofa** [comment]
> 启动时这很正常。不过请检查终端是否有错误/信息。

Can you tell me the reason? 503 has been running for a long time. How can we solve it
