### ISSUE TITLE
Usage of `import.meta` in nuxt modules easily breaks

### ISSUE THREAD

**Issue by passionate-bram** [nuxt/nuxt#24185]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.6.5`
- CLI Version:      `3.9.0`
- Nitro Version:    `2.6.3`
- Package Manager:  `yarn@1.22.19`
- Builder:          `-`
- User Config:      `srcDir`, `authoringTools`, `typescript`, `app`, `runtimeConfig`, `graphql-client`, `modules`, `image`, `sentry`, `tailwindcss`, `vite`, `build`, `experimental`
- Runtime Modules:  `nuxt-lodash@^2.5.0`, `@nuxtjs/tailwindcss@^6.8.0`, `@vueuse/nuxt@10.5.0`, `nuxt-graphql-client@^0.2.29`, `nuxt-icon@^0.4.2`, `@nuxt/image-edge@1.0.0-rc.3-28294248.a578636`
- Build Modules:    `-`

### Reproduction

```js
// my-nuxt-app/modules/my-module/index.ts

console.log({
  url: import.meta.url,
  nitro: import.meta.nitro,
  build: import.meta.build,
  client: import.meta.client,
  server: import.meta.server,
});
```

All accesses of `import.meta` except for `url` cause execution failures when running/building the project.

### Describe the bug

When `import.meta.url` is available, then `import.meta` should be safe to access with arbitrary (but compile-time known) keys. For example `import.meta.server`.

This will make code that is nuxt-aware (e.g. using the `client` and `server` properties to determine where code is being ran) safe to use within a nuxt module setup function.

### Additional context

Since `import.meta.url` works, I suspect there is some sort of define-replace step before the module code is being executed. I first was going to open this issue on nitro, but I quickly found that using this kind of code in a nitro route works fine.

Looking at the stack trace it points to a `@nuxt/kit` function `loadNuxtModuleInstance` which uses `requireModule` (also from kit) to load the nuxt module.

### Logs

```shell-script
<pre>
ERROR  Cannot start nuxt:  Cannot use 'import.meta' outside a module                                                                 10:49:45 AM
10:49:44 AM
client: import.meta.client
^^^^

SyntaxError: Cannot use 'import.meta' outside a module
    at new Script (node:vm:100:7)
    at createScript (node:vm:259:10)
    at Object.runInThisContext (node:vm:307:10)
    at evalModule (.../node_modules/jiti/dist/jiti.js:1:255425)
    at jiti (.../node_modules/jiti/dist/jiti.js:1:253542)
    at requireModule (.../node_modules/nuxt/node_modules/@nuxt/kit/dist/index.mjs:2244:26)
    at loadNuxtModuleInstance (.../node_modules/nuxt/node_modules/@nuxt/kit/dist/index.mjs:2435:90)
    at async installModule (.../node_modules/nuxt/node_modules/@nuxt/kit/dist/index.mjs:2408:47)
    at async initNuxt (.../node_modules/nuxt/dist/index.mjs:3238:7)
    at async load (.../node_modules/nuxi/dist/chunks/dev.mjs:205:9)
    at async Object.invoke (.../node_modules/nuxi/dist/chunks/dev.mjs:249:5)
    at async _main (.../node_modules/nuxi/dist/cli.mjs:49:20)

</pre>
```

**Comment by passionate-bram** [comment]
Assuming this bug is considdered valid, I'm willing to help out resolve this but I may need some direction on what kind of solution would be accepted (expanding replacements, or if nuxt modules need to become full es modules that natively support import.meta).

**Comment by danielroe** [comment]
`import.meta.server` and so on are accessible only in runtime code and not in Nuxt modules. That is, they can be present in plugins or middleware, etc. that Nuxt modules _add_ to the runtime code of the module. But the code of the module itself always runs at build time in a Node or Bun process and does not have access to these flags.

**Comment by passionate-bram** [comment]
It was odd to me that the flags instead of being false cause such failures instead

**Comment by daniluk4000** [comment]
I also have trouble when I don't even use those import.meta, and it still causes failure with no way for me to disable this behavior. I can't also import nuxt/app anywhere because of this.

**Comment by danielroe** [comment]
@daniluk4000 The `nuxt/app` subpath relies on a Nuxt runtime context and is not usable in a module.

**Comment by daniluk4000** [comment]
> @daniluk4000 The `nuxt/app` subpath relies on a Nuxt runtime context and is not usable in a module.

We're not using them, it's only the import. We have a file with like 50 helpers, and use 2 of them in module (without import.meta etc). Because of behaviour when if file or import contains import.meta, we'll have to make a separate file for those 2-3 functions.

**Comment by danielroe** [comment]
@daniluk4000 I'm sorry for the inconvenience, but that's something we actually want to enforce - a clear boundary between code that is 'runtime' and relies on a bundler environment - and code which can be run directly in `nuxt.config` or a module. There are a lot of differences between these environments.

**Comment by daniluk4000** [comment]
@danielroe gotcha! I think this issue can be closed then.

My mistake actually happened during our in-progress migration to Nuxt 3: that was unexpected (for me) behavior change from Nuxt 2, which didn't really care (and even if did, I always could add, like, webpack ignore or smth like that). 

We'll support different environments for config/module then, if this is intended, and will stick to that in new projects. No worries, I just haven't expected that coming =)

Would be great if this was listed in documentation. Maybe it does, but I didn't find anything.

**Comment by shayandrg** [comment]
same issue

#24507
