### ISSUE TITLE
nuxt 3 case sensitive url

### ISSUE THREAD

**Issue by hooman-mirghasemi** [nuxt/nuxt#24183]
### Describe the feature

I found out in default nuxt 3 is case insensitive for URLs
as you know duplicate contents are not ok for SEO, please change this default to case sensitive mode 

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
You can do this with an `app/router.options.ts` file:

```ts
import type { RouterOptions } from 'nuxt/schema'

export default <RouterOptions> {
  sensitive: true
}
```

See https://nuxt.com/docs/guide/going-further/custom-routing#using-approuteroptions

**Comment by hooman-mirghasemi** [comment]
Yes, you are right
but I say the default value with out customizing.
Why the default value is false? why all projects build with nuxt should have case insensitive URLs in default!
we know whats the bad thing duplicate content in SEO. and if we have case insensitive URLs we have multi URLs show same content!

So I mean that its better to have case sensitive URL in default. if some one is special case need case insensitive URL he/she will change it!

**Comment by danielroe** [comment]
This is a vue-router default: https://router.vuejs.org/guide/essentials/route-matching-syntax.html#Sensitive-and-strict-route-options.

**Comment by manniL** [comment]
As a site note: In most cases (there are exceptions!), uppercase URLs can be confusing for the user and I'd suggest to keep them all lowercase. You would add a middleware or redirects then to ensure /AbC will be transformed to /abc.
