### ISSUE TITLE
Component template wrapped in <ClientOnly> doesn't inherit attributes on first element

### ISSUE THREAD

**Issue by maestroosram** [nuxt/nuxt#24194]
### Describe the feature

When you have a component whose <template> is globally wrapped by a <ClientOnly> you don't get it's first child element to inherit attributes (i.e. classes) from the parent template.

Parent component:
`<template>
    <SubComponent class="nice-class" />
</template>`

Child component with <ClientOnly>
`<template>
    <ClientOnly>
        <div id="sub-component">
            ...
        </div>
    </ClientOnly>
</template>`

What I expect from my rendered SubComponent is:
`< div id="sub-component" class="nice-class">
    ...
< /div>`
Instead the "nice-class" is lost.
If I remove the `<ClientOnly>` it works.

The quick solution would be to put the <ClientOnly> in the parent component wrapping the sub component inclusion, but sometimes is useful to have the client-only logic built-in in the components but with the possibility to quickly personalize them (i.e. classes) without having to use custom props.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by MuhammadM1998** [comment]
Have you tried to use `v-bind="$attrs"` on your sub component?

**Comment by maestroosram** [comment]
Yes, it works
