### ISSUE TITLE
wrong Nuxt hooks module name

### ISSUE THREAD

**Issue by userquin** [nuxt/nuxt#24193]
### Environment

NA

### Reproduction

https://nuxt.com/docs/guide/going-further/hooks#app-hooks-runtime

### Describe the bug

should be `#app/nuxt`

### Additional context

Thx @danielroe

> probably also need to update the module builder too: https://github.com/nuxt/module-builder/blob/main/src/commands/build.ts#L160

**Comment by danielroe** [comment]
Would you be able to provide a reproduction?

**Comment by userquin** [comment]
> Would you be able to provide a reproduction?

Sure, I'll provide an small repro after publishing vuetify nuxt module, I'm fixing a few issues...

**Comment by userquin** [comment]
@danielroe https://github.com/userquin/nuxt-module-build-issue-187

On main branch open plugin and module in playground, you will see an error, then checkout fix-hooks branch (run `pnpm dev:prepare` after installing dependencies (`pnpm`))

**Comment by userquin** [comment]
There is some inconsistent behavior when running `pnpm nuxt prepare playground` in module playground and `nuxt-module-build prepare && nuxt-module-build` with latest Nuxt and module builder (3.8.1 and 0.5.4 respectivelly), check the exports:

<details>
<summary><strong>pnpm nuxt prepare playground</strong></summary>

```ts

import type { ModuleOptions, ModuleHooks, RuntimeModuleHooks, ModuleRuntimeConfig, ModulePublicRuntimeConfig } from './module'

declare module '#app' {
  interface RuntimeNuxtHooks extends RuntimeModuleHooks {}
}

declare module '@nuxt/schema' {
  interface NuxtConfig { ['vuetify']?: Partial<ModuleOptions> }
  interface NuxtOptions { ['vuetify']?: ModuleOptions }
  interface NuxtHooks extends ModuleHooks {}
  interface RuntimeConfig extends ModuleRuntimeConfig {}
  interface PublicRuntimeConfig extends ModulePublicRuntimeConfig {}
}

declare module 'nuxt/schema' {
  interface NuxtConfig { ['vuetify']?: Partial<ModuleOptions> }
  interface NuxtOptions { ['vuetify']?: ModuleOptions }
  interface NuxtHooks extends ModuleHooks {}
  interface RuntimeConfig extends ModuleRuntimeConfig {}
  interface PublicRuntimeConfig extends ModulePublicRuntimeConfig {}
}


export type { default } from './module'
```
</details>

<details>
<summary><strong>nuxt-module-build prepare && nuxt-module-build</strong></summary>

```ts
// types.d.ts/types.d.mts
import type { ModuleOptions, ModuleHooks, RuntimeModuleHooks } from './module'

declare module '#app' {
  interface RuntimeNuxtHooks extends RuntimeModuleHooks {}
}

declare module '@nuxt/schema' {
  interface NuxtConfig { ['vuetify']?: Partial<ModuleOptions> }
  interface NuxtOptions { ['vuetify']?: ModuleOptions }
  interface NuxtHooks extends ModuleHooks {}
}

declare module 'nuxt/schema' {
  interface NuxtConfig { ['vuetify']?: Partial<ModuleOptions> }
  interface NuxtOptions { ['vuetify']?: ModuleOptions }
  interface NuxtHooks extends ModuleHooks {}
}


export type { ComponentName, Components, DateAdapter, DateOptions, DirectiveName, Directives, ExternalVuetifyOptions, FontAwesomeSvgIconSet, FontIconSet, IconFontName, IconSetName, IconsOptions, InlineModuleOptions, JSSVGIconSet, LabComponentName, LabComponents, MOptions, ModuleHooks, ModuleOptions, RuntimeModuleHooks, SSRClientHints, SSRClientHintsConfiguration, UnoCCSMdiIconSet, VOptions, VuetifyLocale, default } from './module'
```

![imagen](https://github.com/nuxt/nuxt/assets/6311119/e1c0f9a2-1468-4bb0-a147-351f0e0b07c9)

</details>

**Comment by BobbieGoede** [comment]
It seems like, as long as there are modules installed mixing `#app` and `#app/nuxt` for `declare module` the type inference will break.

I made a minimal reproduction to demonstrate [here](https://stackblitz.com/edit/nuxt-starter-i48ykr?file=plugins%2Fi18n.ts,nuxt.config.ts,plugins%2Fhead.ts,package.json). This reproduction has both `@nuxtjs/i18n` (uses `#app`) and `@nuxtseo/module` (uses `#app/nuxt`) installed, which both provide runtime hooks and I have added plugins that use these hooks.

The reproduction has some npm scripts to demonstrate the issue by running `nuxt typecheck` to show which hook types get type errors. You can run `pnpm check:all` to run all of the checks listed below for convenience.

* `pnpm check` (unexpected behavior)
  * both modules enabled
  * i18n hooks type error 
* `pnpm check:i18n-only` (proof i18n hooks work)
  * disables seo module
  * only seo hooks have type errors 
* `pnpm check:seo-only` (proof seo hooks work)
  * disables i18n module
  * only i18n hooks have type errors

**Comment by danielroe** [comment]
Thank you for the deep dive 🙏 

I think it's safer to keep as `#app`. Was there a reason for using `#app/nuxt` at some point?

cc: @harlan-zw

**Comment by harlan-zw** [comment]
Hm interesting, I can't remember at this point. I either based it off another module or this is where my IDE pointed me to. I feel like I switched to using `@nuxt/scema` in other modules.

Thanks for the investigation @BobbieGoede & @userquin. Will keep an eye out for it elsehwere
