### ISSUE TITLE
Possibility to disable direct API calls

### ISSUE THREAD

**Issue by SzymonLisowiec** [nuxt/nuxt#24202]
### Describe the feature

Hello,
In case you aren't using nitro server API, but a external backend e.g. NestJS, it would be very useful to be able to disable direct API calls ( https://nuxt.com/docs/guide/concepts/server-engine#direct-api-calls ). Lack of this feature gave me very hard time.

My current, workaround solution is plugin `fetch.ts`:
```javascript
import { ofetch } from 'ofetch';

export default defineNuxtPlugin(() => {
  globalThis.$fetch = ofetch.create({
    baseURL: process.client ? 'http://127.0.0.1:3001' : 'http://127.0.0.1:8080',
  });
  
  if (process.server) {
    useRequestEvent().$fetch = globalThis.$fetch; // it's disables direct API calls
  }
});
```

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
@SzymonLisowiec Could you elaborate why that feature caused troubles for you? 🤔

**Comment by danielroe** [comment]
Overriding `$fetch` will potentially break modules and other code that relies on direct fetch calls. For example, it may break Nuxt's error handling or component island rendering.

Instead, you should create a custom api client for your backend rather than overriding `$fetch`.
