### ISSUE TITLE
Is ClientOnly needed for Teleports in routes marked with `ssr: false`?

### ISSUE THREAD

**Issue by brc-dd** [nuxt/nuxt#24203]
### Environment

Working directory: /home/projects/github-qaz8gk
Nuxt project info:

------------------------------
- Operating System: Linux
- Node Version: v18.18.0
- Nuxt Version: 3.8.1
- CLI Version: 3.9.1
- Nitro Version: 2.7.2
- Package Manager: npm@9.4.2
- Builder: -
- User Config: routeRules
- Runtime Modules: -
- Build Modules: -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-qaz8gk?file=pages%2Ffoo%2Fbar.vue,app.vue,nuxt.config.ts

* Go to /foo/bar and see errors in console.

### Describe the bug

`<Teleport to="#some-selector">` doesn't work in pages where `routeRules.ssr` is `false`. One currently needs to wrap it with `ClientOnly` to make it work. Not sure if this is bug, or just how things related to teleports are supposed to work 😅

**Comment by huang-julien** [comment]
Hello! 
You should'nt use `Teleport` to teleport thing within your vue application. By setting ssr to false, you disable pre-rendering / server side rendering so when you instantiate the application client-side, `#some-selector` does not exist yet on first render
