### ISSUE TITLE
This page is temporarily unavailable

### ISSUE THREAD

**Issue by xxwangkaimin** [nuxt/nuxt#24206]
### Environment

node version: 18.15.0

package.json:
```json
{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/devtools": "latest",
    "@types/node": "^20.9.0",
    "nuxt": "^3.8.1",
    "vue": "^3.3.8",
    "vue-router": "^4.2.5"
  }
}
```

### Reproduction

https://stackblitz.com/edit/nuxt-starter-l1ytpj?file=app.vue
https://codesandbox.io/p/sandbox/modest-meitner-gd43nq

### Describe the bug

The useAsyncData method was used in the app.vue page, and there were no issues with the development environment. After running the packaging command npm run build, this page is temporarily unavailable when deployed to the server.
app.vue
```vue
<template>
  <div>
    <div v-for="(item, index) in articleList" :key="index">{{ item.title }}</div>
  </div>
</template>
<script lang="ts" setup>
const url = getBaseUrl() + 'article/front/list';
const { data } = await useAsyncData('articles', () =>
  $fetch(url, {
    params: {
      index: 1,
      size: 9,
    },
  })
);
const articleList = (data.value as ResponseData<PageResult<ArticleVo>>).data.list
</script>
```
utils/baseUrl.ts
```ts
export function getBaseUrl() {
  if (process.server) {
    return "https://api-manage-dev.wkmblog.com/api/";
  }
  return "/api/";
}
```
types/global.d.ts
```ts
declare global {

  /**
   * 分页响应数据类型
   */
  interface PageResult<T> {
    /**
     * 数据列表
     */
    list: T[],
    /**
     * 总页数
     */
    pages: number;
    /**
     * 总条数
     */
    total: number
  }

  /**
   * 网络请求响应数据类型
   */
  interface ResponseData<T> {
    data: T;
    code: number;
    message: string
  }

  // 文章数据类型
  interface ArticleVo {
    articleColumn: {
      id: string;
      name: string
    };
    createTime: string;
    id: string;
    pic: string;
    publishTime: string;
    status: string
    title: string
  }
}

export {}
```
nuxt.congif.ts
```ts
export default defineNuxtConfig({
  devtools: { enabled: true },
  nitro: {
    devProxy: {
      '/api/': {
        target: 'https://api-manage-dev.wkmblog.com/api/',
        changeOrigin: true
      }
    }
  }
})
```
Development environment display effect:
![image](https://github.com/nuxt/nuxt/assets/33536543/a7044f2f-4735-4aaf-9199-8b1bf845213c)
There was a problem deploying the server:
![image](https://github.com/nuxt/nuxt/assets/33536543/3c0c81fe-ab2c-4e7e-9153-bd80fa7fe963)
When I remove network requests and only display static data, there is no problem:
```vue
<template>
  <div>
    <!--<div v-for="(item, index) in articleList" :key="index">{{ item.title }}</div>-->
    <div>nuxt3</div>
  </div>
</template>
<script lang="ts" setup>
// const url = getBaseUrl() + 'article/front/list'
// const page = ref(1)
// const {data} = await useAsyncData('articles', () => $fetch(url, {
//   params: {
//     index: page.value,
//     size: 9
//   }
// }), {
//   watch: [page]
// })
// const articleList = (data.value as ResponseData<PageResult<ArticleVo>>).data.list
</script>
```
Development environment display effect:
![image](https://github.com/nuxt/nuxt/assets/33536543/67bf738b-274f-4c80-a189-6fe9af75c706)
There was a problem deploying the server:
![image](https://github.com/nuxt/nuxt/assets/33536543/df4f7920-14a1-41e2-8234-b3f324646006)
So I only know it's a network request issue, but I don't know how to solve it!

**Comment by Sebarkar** [comment]
Got this error on pm2 server:
pm2 update
Solved my problem.

**Comment by xxwangkaimin** [comment]
@Sebarkar Thank you very much. According to your method, my project can now run normally on the server.

**Comment by PdxLook** [comment]
请问你是通过升级pm2 解决的这个问题吗？ 我这边同样第一次打开页面正常，刷新页面就 This page is temporarily unavailable.

<script setup>

const useFetchData = async () => {
  try {
    const response = await fetch('http://api.xxx.com/site', {
      method: 'POST'
    });
    
    const data = await response.json();
    console.log(data)
    return data;
  } catch (error) {
    console.error('Error fetching data:', error);
    throw error;
  }
};

const { data: count } = await useFetchData();
console.log(count.value)
</script>

<template>
  <div class="text-white">
    <p class="p-5">Page visits: {{ count }}</p>

  </div>
</template>

**Comment by xxwangkaimin** [comment]
@PdxLook 我确实是在服务器端升级pm2到最新版本后这个问题就不存在了

**Comment by xxwangkaimin** [comment]
@PdxLook 至于是什么原因，我确实没有找到

**Comment by PdxLook** [comment]
我线上部署服务器是宝塔，通过宝塔配置的PM2,升级到最新同样存在此问题。请问你是怎么配置的PM2? 我来试着部署一下
