### ISSUE TITLE
Teleport behaves differently for SSR and client-side

### ISSUE THREAD

**Issue by TO-koswald** [nuxt/nuxt#24207]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.1
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-mdx82e?file=app.vue

### Describe the bug

When using `Teleport` during SSR, the content is teleported **above** the main nuxt application. When using `Teleport` on the client-side, the content is teleported below. This causes issues with teleported modals / dropdowns etc.

```html
<Teleport to="body">
  <div>SSR teleport</div>
</Teleport>
<ClientOnly>
  <Teleport to="body">
    <div>Client teleport</div>
  </Teleport>
</ClientOnly>
```

The resulting HTML will look like this:
```html
<body>
  <div>SSR teleport</div>
  <div id="__nuxt">...</div>
  <div>Client teleport</div>
</body>
```

I would have expected this result:
```html
<body>
  <div id="__nuxt">...</div>
  <div>SSR teleport</div>
  <div>Client teleport</div>
</body>
```

**Comment by manniL** [comment]
This is not a limitation of Nuxt but related to plain Vue SSR.

Evan [mentioned in an issue](https://github.com/vuejs/core/issues/5242#issuecomment-1129829701) that targeting `body` via Teleport when using SSR can cause issues. Instead, using a dedicated element helps.

**Comment by xvaara** [comment]
@manniL so nuxt docs say: `Nuxt currently has SSR support for teleports to body only`, so dedicated element is not an option? Or is the docs wrong?

The way I'm seeing is that nuxt is rendering the teleport in the wrong place (or different from normal vue). Should it not just render it in the same place as vue?

**Comment by manniL** [comment]
You are right. I'll dive into it.

**Comment by danielroe** [comment]
This might be a behaviour change in Vue, or possibly I encountered a hydration error when appending to the body. 🤔 I'd be very happy to append these teleports to body, as long as it doesn't cause any issues.

**Comment by manniL** [comment]
@danielroe Just tested, it will cause hydration errors 🙈 (probably as explained in https://github.com/vuejs/core/issues/5242#issuecomment-1129829701).

**Comment by danielroe** [comment]
That works 👌

**Comment by manniL** [comment]
On it 👍🏻

**Comment by manniL** [comment]
I'll track that in a new issue though (linking here in a second).  

Closing this issue here again because sadly appending is not possible due to hydration errors as linked.
