### ISSUE TITLE
Opening Nuxt in a tab while dev server initialization breaks the build with cryptic error until server restarted

### ISSUE THREAD

**Issue by bmulholland** [nuxt/nuxt#24216]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.8.1
- Nuxt Version:     3.8.1
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  yarn@4.0.1
- Builder:          -
- User Config:      ssr, runtimeConfig, app, build, css, imports, modules, postcss, vite, sourcemap, dayjs, googleFonts, loading, loadingIndicator, hooks
- Runtime Modules:  @nuxtjs/google-fonts@3.0.2, dayjs-nuxt@2.1.9, @nuxtjs/svg-sprite@1.0.2, nuxt3-vuex-module@1.0.13, @nuxtjs/storybook@7.0.0
- Build Modules:    -
------------------------------

### Reproduction

Honestly I couldn't entirely say. Maybe it's caused by switching back and forth between branches with Nuxt 2 and 3 enabled, and perhaps doing so while the server is still running?

### Describe the bug

Whatever the reason, sometimes my Nuxt 3 server gets stuck in this state. It won't load anything, just throws the generic error "ambiguous indirect export: PropType"

I spent hours hunting through usage of PropType in my app to try to fix it, because the error has no associated stack trace. That didn't help. Incredibly frustrating.

It's hard to say even what fixes it. Most recently I fixed it by deleting the following directories: .nuxt, .output, storybook-static, node_modules. Then yarn install and restarting the server.

**Comment by bmulholland** [comment]
Now I'm getting a new one: `ambiguous indirect export: StateChanger`

I haven't changed branches, so it's not that.

**Comment by bmulholland** [comment]
I tried removing the Storybook module, suspecting that was the problem, but now I seem to get the PropType error on EVERY load, even if I don't have a tab open?

**Comment by danielroe** [comment]
This sounds like an issue related to the migration. I would suggest using git worktrees to avoid duplicating things like the Vite cache folder. It might be that Vite has cached the wrong version of `vue`, for example.

I'll happily look into this if you have a reproduction (or even a half-migrated project).

**Comment by bmulholland** [comment]
Thanks Daniel. Given all the blockers I faced — storybook not working, reloading code not working, this broken build oddity — I realized it would be easier to migrate off Nuxt and use raw Vue/Vite 3. That’s mostly done now. Thanks for all your help.

**Comment by danielroe** [comment]
All the best to you @bmulholland ❤️
