### ISSUE TITLE
Issue with runtimeConfig + layers in production when certain conditions are met

### ISSUE THREAD

**Issue by Maiquu** [nuxt/nuxt#24215]
### Environment

- Operating System: `Linux`
- Node Version:     `v20.9.0`
- Nuxt Version:     `3.8.1`
- CLI Version:      `3.9.1`
- Nitro Version:    `2.7.2`
- Package Manager:  `pnpm@8.9.2`
- Builder:          `-`
- User Config:      `devtools`, `extends`, `runtimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Reproduction repository: https://github.com/Maiquu/nuxt-bug-reproduction

Since this is a build-only issue, I haven't included a StackBlitz link. I included notes in `README` about the issue.

### Describe the bug

If all of the following conditions are met, the build output will not read environment variable equivalents of runtime configuration keys that were `undefined` at build time.

- Main app should extend a layer which is defined as a node module.
- Extended layer should have `runtimeConfig` defined with any number of values.

Build output will not be flawed if extended layer is defined as a relative path. (**EDIT**: This is incorrect, layer type does not matter)

Can be worked around by giving a default value for any runtimeConfig expression that can be undefined during build.

**Comment by v-moravec** [comment]
Why was this closed? I don't see any PR which would fix the issue. It seems I'm getting the same bug.

**Comment by Maiquu** [comment]
I'm not really sure why I closed it back then. Maybe I thought it was a very rare and minor issue with a simple workaround, making it not worth the time. But yes, after checking again, there is still inconsistent behavior in how `undefined` initial values are handled for `runtimeConfig`. I can re-open the issue with the reproduction repo if you think its necessary.

**Comment by v-moravec** [comment]
I already created my own minimal reproduction, might dig into it later.
