### ISSUE TITLE
Runtime config is not replaced by env variables in the module

### ISSUE THREAD

**Issue by enkot** [nuxt/nuxt#24224]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.1
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools, runtimeConfig
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-anbt7g?file=modules%2Ftest.ts

### Describe the bug

Expected: `feature` should be equal to `bar`
Actual: `feature` is equal to `foo`

**Comment by pi0** [comment]
Hi. Runtime config is overriden in runtime (vue componens, pages, composables, server API, plugin, etc) and not the nuxt.config and modules.

However i think it might be a good idea to handle it also for build namespace for more consistent behavior. /cc @danielroe wdyt?

**Comment by enkot** [comment]
I think this is a good idea because otherwise module authors would have to manually do the same work to get the required env and conform to the `NUXT_` convention.

**Comment by danielroe** [comment]
@pi0 I think it sounds like a good idea to me 👌

**Comment by enkot** [comment]
@danielroe This is probably the fourth "good first issue" label in my issues 😄 But thanks!
