### ISSUE TITLE
Error when opening nuxt3 web link in China's QQ application

### ISSUE THREAD

**Issue by leggod** [nuxt/nuxt#24229]
### Environment

- Operating System: Darwin
- Node Version:     v20.9.0
- Nuxt Version:     3.8.1
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  pnpm@8.10.0
- Builder:          -
- User Config:      alias, app, spaLoadingTemplate, runtimeConfig, plugins, modules, vant, css, postcss, nitro, vite, vue, telemetry, sourcemap
- Runtime Modules:  @vant/nuxt@1.0.3, @pinia-plugin-persistedstate/nuxt@1.2.0, @pinia/nuxt@0.5.1
- Build Modules:    -

### Reproduction

The link I used is https://m.xchuxing.com

### Describe the bug

At present, it is only found that an error will be reported when nuxt3 is opened in QQ's webview. The error message is as shown in the figure.The link I used is https://m.xchuxing.com
![IMG_0277](https://github.com/nuxt/nuxt/assets/20152324/61025977-9008-4468-9e47-bab576abffea)
Then I located ju.matchAll by controlling the search and found the source code in the map file.
![image](https://github.com/nuxt/nuxt/assets/20152324/e2e702d4-545f-4808-b536-33d3bccdacf4)
I didn't use pages. I deleted it, created a view, and customized the route through app-router.options.ts. I wonder if it has something to do with this operation, but it works in other browsers, only QQ. The webview will report an error, how to solve it?

**Comment by leggod** [comment]
https:stackblitz.com/edit/github-wmfvbw  I simplified the code a bit and opened it in QQ on iOS, but still got an error.
![976EC54D-2413-4F7C-93E6-52F85F8E7F8F](https://github.com/nuxt/nuxt/assets/20152324/ff2c590a-e789-4010-b851-0b59c8414921)

**Comment by leggod** [comment]
Just drop it to 3.7.4, I'm fine with it.  
![image](https://github.com/nuxt/nuxt/assets/20152324/4b7a58dd-5fff-4cb1-bf10-f78b20dc0426)

**Comment by leggod** [comment]
If you can download QQ Browser from iOS app store and visit nuxt.com, you will be surprised
![DEDF81C3-1711-4223-9A6B-7494825D2A86](https://github.com/nuxt/nuxt/assets/20152324/e339773c-4f3b-49c2-8793-c13403f480ee)

**Comment by Okamidev** [comment]
I also get this error since Nuxt 3.8.1. I figured out it happens when I include some company component library in nuxt config with:
```
script: [
    { src: 'path/to-js-lib.js', type: 'module' },
],
``` 

I had to go back to version 3.7.4 :disappointed:

**Comment by Jame6292** [comment]
I also got this error in QQ context browser( open url in qq,  Alipay context(scan url qrcode)

package.json
```
"devDependencies": {
    "@nuxt/devtools": "latest",
    "nuxt": "^3.8.2",
    "sass": "^1.69.5"
}
```

**Comment by OrangeOran** [comment]
same error in QQ and QQ browser with ios

**Comment by Binaryify** [comment]
https://github.com/nuxt/nuxt/issues/24625
use v3.7.* can fix this

**Comment by lixiao258** [comment]
> e

After configuring in this way, clicking on the jump button will result in a blank page that must be refreshed to display data. Is there a similar feature?

**Comment by lixiao258** [comment]
> Turning off experimental.appManifest solved the issue. nuxt.config.ts

After configuring in this way, clicking on the jump button will result in a blank page that must be refreshed to display data. Is there a similar feature?

**Comment by chenhan19** [comment]
3.7.4 QQ browser routing failure in mobile iOS system

**Comment by fenyuluoshang** [comment]
I have same bug in QQ browser with iOS system

And I found it may a bug form https://github.com/unjs/radix3

**Comment by 1477696126** [comment]
自从3.8版本以来 ，IOS系统的 QQ UC 搜狗浏览器都有这个问题

**Comment by 594900298** [comment]
The DingTalk mini program webview also encountered issues

**Comment by 594900298** [comment]
ios DingTalk mini program webview also encountered issues

**Comment by zhangjunjie6b** [comment]
So has this problem been resolved? I've been waiting for the new version

**Comment by zhanyuzhang** [comment]
> Turning off experimental.appManifest solved the issue. nuxt.config.ts

Thanks. It works for me.

**Comment by zhanyuzhang** [comment]
Maybe it's a bug of ofetch. It works for me adding following code in pakcage.json.(I use pnpm)
```js
"pnpm": {
  "overrides": {
    "ofetch": "1.2.1"
  }
}
```

**Comment by markthree** [comment]
If someone doesn't have high stability requirements, they can use this module → [markthree/nuxt-fix-ofetch](https://github.com/markthree/nuxt-fix-ofetch)

**Comment by 594900298** [comment]
> So has this problem been resolved? I've been waiting for the new version

There's no way, using the version above can solve it

**Comment by lizy0329-biubiubiu** [comment]
[nuxt-fix-ofetch](https://github.com/markthree/nuxt-fix-ofetch): 0.0.14
 500 error
 null is not an object (evaluating 'instance.__vrv_devtools=info')

**Comment by lizy0329-biubiubiu** [comment]
```
export default defineNuxtConfig({
    devtools: {enabled: false},
    experimental: {
        appManifest: false
    },
}
```

is work for me

**Comment by BluesYoung-web** [comment]
same error in Alipay with 3.11.2

**Comment by markthree** [comment]
> [nuxt-fix-ofetch](https://github.com/markthree/nuxt-fix-ofetch): 0.0.14 500 error null is not an object (evaluating 'instance.__vrv_devtools=info')

Hi, if [nuxt-fix-ofetch](https://github.com/markthree/nuxt-fix-ofetch) has any bugs, please go to [nuxt-fix-ofetch/issues](https://github.com/markthree/nuxt-fix-ofetch/issues) and raise issues and bring a minimal replica repository, I'll be happy to take a look!

**Comment by zhangjunjie6b** [comment]
> > So has this problem been resolved? I've been waiting for the new version
> 
> There's no way, using the version above can solve it @zhangjunjie6b

```
 "resolutions": {
    "ofetch": "npm:ofetch@1.2.1"
  },
  "overrides": {
    "ofetch": "npm:ofetch@1.2.1"
  }
```
Yes, this is how I temporarily resolved it

**Comment by cazs-lyh** [comment]
![c069dd20-19cd-4f7a-b2cb-2deabf485239](https://github.com/nuxt/nuxt/assets/153475206/1e07e5ed-e908-44a0-9fa0-e35629a4a142)
i had  same error with QQ&Alipay, 
thought maybe this error because of router
who can solve it ,someone save me pls, thankGod

**Comment by cazs-lyh** [comment]
> ![c069dd20-19cd-4f7a-b2cb-2deabf485239](https://private-user-images.githubusercontent.com/153475206/325631396-1e07e5ed-e908-44a0-9fa0-e35629a4a142.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTI4NzUsIm5iZiI6MTcxNDA1MjU3NSwicGF0aCI6Ii8xNTM0NzUyMDYvMzI1NjMxMzk2LTFlMDdlNWVkLWU5MDgtNDRhMC05ZmEwLWUzNTYyOWE0YTE0Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQxMzQyNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2UyYzIyYmYzN2U1NWQ0NWU1ZDNkZGM3N2RjOTc4NjU3NDRjZTIzMTI5ZDVlNWM4MTZiODkzMTIwNzhkYzhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.88nE7dGdwq6hhUK-XEccsZuzzxIhd2OTq9OyEmch3n0) i had same error with QQ&Alipay, thought maybe this error because of router who can solve it ,someone save me pls, thankGod

i try to drop it to 3.7.4,it didnt work

**Comment by lizy0329-biubiubiu** [comment]
> 自从3.8版本以来 ，IOS系统的 QQ UC 搜狗 浏览器都有这个问题

都是 X5 内核
