### ISSUE TITLE
`useCookie` with `maxAge` or `expires` gets removed when updated

### ISSUE THREAD

**Issue by ChrisGV04** [nuxt/nuxt#24227]
### Environment

- Operating System: Darwin
- Node Version:     v18.17.1
- Nuxt Version:     3.8.1
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  pnpm@8.10.2
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

I used the starter project from `pnpx nuxi@latest init` and just replaced the `app.vue` with the following code:

```vue
<script setup lang="ts">
const hasConsent = useCookie('dialog', {
  sameSite: 'strict',
  default: () => 'no',
  maxAge: 2592000, // 30 days in seconds
});
const showConsentAlert = ref(false);

onMounted(() => {
  if (process.server) return;
  if (hasConsent.value === 'yes') return;

  showConsentAlert.value = true;
});

function acceptConsent() {
  hasConsent.value = 'yes';
  showConsentAlert.value = false;
}
</script>

<template>
  <Teleport to="body">
    <div v-if="showConsentAlert">
      <span>We use cookies</span>
      <button type="button" @click="acceptConsent">Accept</button>
    </div>
  </Teleport>
</template>
```

### Describe the bug

When I click the `acceptConsent` button, I set the cookie value from `no` to `yes`. However, instead of saving the `yes` value inside the cookie, it gets removed completely. I tried on Firefox v119.0.1 and Chrome v119.0.6. Both browsers have the exact same behavior.

The strange part is that if I remove the `maxAge` option from `useCookie`, everything works fine. But I would like that the consent cookie expires after 30 days. I also tried with `expires` and the same issue happened.

I'm not sure if I'm doing something wrong or if it really is a bug, but I would expect that if I change the value of the cookie, it must be persisted, but it is getting deleted...

### Additional context

I'm trying to create a cookie consent dialog that shows once and if it gets accepted, it doesn't show again for 30 days. My reproduction code is just a bare-bones demo with the minimal code I could reproduce it with. In the real website this functionality is inside a `CookieConsent.vue` component and it is a Modal.

https://github.com/nuxt/nuxt/assets/47041342/f6146867-31a0-468e-98c7-cb3536c797ba

**Comment by RomanSkrypnik** [comment]
@ChrisGV04 I'm facing the same issue
@danielroe says that's an expected behaviour for now
Here I created this issue but it was closed : https://github.com/nuxt/nuxt/issues/24041#issuecomment-1802069216

**Comment by ChrisGV04** [comment]
Hi @RomanSkrypnik! I see you had a similar issue, however in my case I'm not even using `useCookie` with different options. I just created it once and if I change the value it gets deleted completely...

If that's the expected behavior, I don't understand how should cookies be updated. I did as the docs show but with options it doesn't work.

And yeah, that's a breaking change! I didn't notice until a customer told me that every time they enter or refresh my website they keep getting the cookie consent even after accepting...

**Comment by ZEA-repository** [comment]
Hi everyone! Pr #23697 seems to be related to this issue.

**Comment by positiveprogrammer** [comment]
Hi, We had a similar issue. The code is trying to convert maxAge to milliseconds to use setTimeout. But it looks like the value is too big. Our workaround would be to decrease maxAge to less than 20 days, but waiting for a more robust solution.

[Maximum delay value](https://developer.mozilla.org/en-US/docs/Web/API/setTimeout#maximum_delay_value)
Browsers store the delay as a 32-bit signed integer internally. This causes an integer overflow when using delays larger than 2,147,483,647 ms (about 24.8 days), resulting in the timeout being executed immediately.

**Comment by affinage-digital** [comment]
Is there a solution to the problem?

**Comment by ChrisGV04** [comment]
Hi @positiveprogrammer!
You are right. I reduced the `maxAge` to 1,296,000 (15 days in seconds) and it worked... Even if it's not ideal to reduce the time.

I went through [the code for the `useCookie` composable](https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/app/composables/cookie.ts) and it seems that PR #23549 created a `customRef` that is only used client-side to make expired cookies `undefined` on the browser. It uses `setTimeout` for that, which is why setting a long expiration time client-side doesn't work...

The `default` value doesn't have that issue because it runs server-side. Server-side cookies don't use that same functionality. They use a normal `ref`.

I think I have an idea on how to solve it or at least to work around it since it's a browser limitation. I will work on a PR for it

**Comment by fransyrcc** [comment]
Hello, I'm also facing the same issue. 1 to 24 days work but 25 days do not. However, if I set it to 1 year it works
```
 maxAge: 365 * 24 * 60 * 60,
```

Nuxt Version: 3.8.1

**Comment by ChrisGV04** [comment]
Hi @junkiet! 
`useCookie` uses seconds for the `maxAge` option. Internally it converts it to milliseconds

**Comment by junkiet** [comment]
What I test just now, maxAge: -1 at setCookie() at server side

at client side, need to set also but using useCookie():
let token = useCookie('token');
token.value = res.value.token;

I have no idea, why need to set both server and client side, is it something depreciated at 3.8.1  or a bug?

**Comment by ChrisGV04** [comment]
Hi @junkiet 

I wrote about this issue and why it's happening in detail at my currently open PR [#24253](https://github.com/nuxt/nuxt/pull/24253).

The issue only exists on the client side, that's why if you set the cookie on the server, it always works. In the client it uses `useTimeout` which has a maximum wait time of 24.8 days, so adding any value above that on the client makes the cookie expire immediately

**Comment by junkiet** [comment]
> Hi @junkiet
> 
> I wrote about this issue and why it's happening in detail at my currently open PR [#24253](https://github.com/nuxt/nuxt/pull/24253).
> 
> The issue only exists on the client side, that's why if you set the cookie on the server, it always works. In the client it uses `setTimeout` which has a maximum wait time of 24.8 days, so adding any value above that on the client makes the cookie expire immediately

ii see, I will try it

**Comment by junkiet** [comment]
I found the problem, once execute deleteCookie, whever you set in setcookie, it will be automatically set to expiry immediately, and use normal auth.value = null to delete it, then work as normal., before 3.7 nuxt, it is working fine

**Comment by CaptainFalcon92** [comment]
I can also join and confirm this exact behavior. Cookie of about more than 20 days of TTL will get deleted immediately upon updating.

```js
  const aboutCookies = useCookie('aboutCookies', {
    sameSite: true,
    maxAge: 2592000, // 30 days   (1728000 works tho')
    default: () => false
  })
  ```
  
The overflow theory seems to match - however, please notice it worked flawless prior to updating nuxt to 3.8.
