### ISSUE TITLE
Lack of documentation around packages not auto-installing when using local Nuxt layers

### ISSUE THREAD

**Issue by rstainsby** [nuxt/nuxt#24225]
### Environment

N/A

### Reproduction

N/A

### Describe the bug

The current Nuxt documentation doesn't explicitly mention that npm packages won't automatically install when a local Nuxt layer is extended (e.g., extends: ['../base']). This appears to be an oversight, as the only related information is somewhat hidden within the "Git Repository" section of the layer authoring guide. This can be misleading, especially for those who aren't planning to use a git repository for their layer, as they may skip over that section entirely (like I did) or not realise it also applies to local projects.

A dedicated section, perhaps titled "Local Layers," could help clarify this point. If this documentation already exists and I've overlooked it, I'd appreciate a pointer. Otherwise, I'm happy to contribute to the documentation to address this gap.

### Additional context

When extending Nuxt 3 layers locally, NPM packages installed in the layer are not auto-installed by the consuming project. This was mentioned as a know limitation of Nuxt layers by @danielroe in issue #19124.

**Comment by CernyMatej** [comment]
Hi, so what is the solution when using local layers? Is it possible to auto install the packages?
What you mentioned is exactly my case... I thought it wasn't implemented yet.

**Comment by MuhammadM1998** [comment]
@CernyMatej you're actually right. Auto installing deps from remote (GitHub, GitLab, etc..) is not implemented yet (didn't try local layers but according to this issue the same applies). You need to define & install them again in your main app. But it seems it will be implemented soon according to these https://github.com/unjs/c12/issues/51#issuecomment-1770797712, https://github.com/unjs/giget/issues/6.

**Comment by bernhardberger** [comment]
should dependencies auto-install when using a layer hosted on a local npm registry? Because that also doesn't seem to work for me..

**Comment by danielroe** [comment]
This is now documented.
