### ISSUE TITLE
Loading new changes doesn't work

### ISSUE THREAD

**Issue by bmulholland** [nuxt/nuxt#24223]
### Environment

    Operating System: Darwin
    Node Version: v20.8.1
    Nuxt Version: 3.8.1
    CLI Version: 3.9.1
    Nitro Version: 2.7.2
    Package Manager: yarn@4.0.1
    Builder: -
    User Config: ssr, runtimeConfig, app, build, css, imports, modules, postcss, vite, sourcemap, dayjs, googleFonts, loading, loadingIndicator, hooks
    Runtime Modules: @nuxtjs/google-fonts@3.0.2, dayjs-nuxt@2.1.9, @nuxtjs/svg-sprite@1.0.2, nuxt3-vuex-module@1.0.13, @nuxtjs/storybook@7.0.0
    Build Modules: -

### Reproduction

I have too many issues to post a minimal repro for everything.

### Describe the bug

I can't get reloading to work. Not even HMR, but anything. I make a change to the component, and I get a message in the console that "page reload <file name>". Great.

But the code doesn't take effect. The only way to get the new code running is to manually restart the entire Nuxt server. Hot reloading doesn't work, refreshing the page doesn't work. Also, per https://github.com/nuxt/nuxt/issues/24216, I also have to make sure to kill the tab while the server loads. Then, when the server is done loading, I can open the tab, maybe do a hard refresh (inconsistent), and then I can see my changes.

**Comment by bmulholland** [comment]
I'd asked in https://github.com/nuxt/nuxt/discussions/23533#discussioncomment-7503363 about ways to diagnose/debug issues but didn't hear anything.

**Comment by Wharley01** [comment]
I am havinng same issue

**Comment by danielroe** [comment]
> I have too many issues to post a minimal repro for everything.

I understand this must be frustrating but it's not possible to investigate an issue like this without a reproduction.

**Comment by R0N1n-dev** [comment]
Always thought  some scenarios are almost impossible to create a minimal reproduction.
Stackblitz and Codesandbox are perfect dev environments coz they nulllify local dev environment variables but are not really good for issues such as those that come up from those differences such as OS.

So need for an alternative to minimal repros in some cases such as this

**Comment by manniL** [comment]
> So need for an alternative to minimal repros in some cases such as this

You are more than welcome to provide a public GitHub repo with instructions too ☺️
