### ISSUE TITLE
Support @vitejs/plugin-legacy

### ISSUE THREAD

**Issue by bgrand-ch** [nuxt/nuxt#24232]
### Describe the feature

Thank you for Nuxt.

Nuxt and Vue 3 build the application with the latest ECMAScript standards, which is great.

However, some applications still need to work with old web browsers and in my case SmartTVs.

The Vite plugin `@vitejs/plugin-legacy` seems ideal, but unfortunately not supported on Nuxt (despite the ability to add Vite plugins). More infos: https://github.com/nuxt/nuxt/issues/15464

I did try to use an alternative from the Nuxt community `nuxt-vite-legacy`, but unfortunately it is not functional or not documented enough to use it easily.

Could you make the `@vitejs/plugin-legacy` plugin compatible with Nuxt or add a section in the documentation explaining in detail how to use Babel with Nuxt or other similar services please?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by bgrand-ch** [comment]
🤔

**Comment by danielroe** [comment]
~> https://github.com/nuxt/nuxt/issues/15464#issuecomment-1596895289

**Comment by bgrand-ch** [comment]
@danielroe https://github.com/nuxt/nuxt/issues/15464#issuecomment-1596958686 🤔

**Comment by danielroe** [comment]
I'm happy to have an issue to track configuring the load order of bundles if you think that would help you. 🙏
