### ISSUE TITLE
Error server when using browser utilities in middleware

### ISSUE THREAD

**Issue by castrogarciajs** [nuxt/nuxt#24240]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.9.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  pnpm@8.10.2
- Builder:          -
- User Config:      app, devtools, modules, pinia, css, ui, colorMode, postcss, runtimeConfig
- Runtime Modules:  @nuxt/ui@2.9.0, @nuxt/image@1.0.0, @pinia/nuxt@0.5.1, @vueuse/nuxt@10.5.0
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-as6bmv-csyfz1?file=app.vue

### Describe the bug

Hello nuxt team,

I have both a doubt and this strange interaction, when using any property of the browser, nuxt apparently doesn't like it, but I still read what I write, the development server does not go down, it is still active and nuxt returns an error 500 server, is there a way to use something from nevagdor in the middleware or what you recommend, thank you!

### Additional context

The error is 500, the server is supposed to crash but it doesn't, it's confusing

![Captura de pantalla 2023-11-10 093652](https://github.com/nuxt/nuxt/assets/116913262/52934eb1-ea3c-4b38-9b00-3792640d91da)

I still get the console.log() I requested

![2023-11-10](https://github.com/nuxt/nuxt/assets/116913262/6552e9d1-6523-4f9b-8a77-bea5affd6158)

code

![2023-11-10 (1)](https://github.com/nuxt/nuxt/assets/116913262/1cc1663d-e946-47ea-9a25-048f358c721f)

**Comment by huang-julien** [comment]
Hello !

Middlewares are run server side and client side. You need to wrap the client code within `if (import.meta.client)`.

see https://nuxt.com/docs/guide/directory-structure/middleware#when-middleware-runs
