### ISSUE TITLE
Nuxt instance in window object as in v2

### ISSUE THREAD

**Issue by makaraman** [nuxt/nuxt#24259]
### Describe the feature

We are using Nuxt v2 in most of our projects. Now we started working with v3, and we have a system that tracks the nuxt instance out of the box in v2. For example, we use `window.$nuxt` `window.$nuxt.$watch` `window.$nuxt.$store.state` `window.$nuxt.$pinia.state` from another JS (clean webpack) project, which is actually under a folder in the nuxt project.

I also tried to use `window.__NUXT__`, but for example, it's not possible to use getters from the store.

I saw that it is possible to use `useNuxtApp` from the window object, but it doesn't include the instance as in v2. If there is a way to use `$nuxt.$watch`, can you please enlighten me as it's not described in the documents?

If the feature mentioned above is already usable, please leave an instruction.

Thanks

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
Hey 👋 
Yes, you can access e.g. provided values from plugins, as well as `$router`, via `window.useNuxtApp` (also [showcased here](https://www.youtube.com/watch?v=gMoipv_NkWE)). There might be less APIs exposed when using the composition api (e.g. now `$watch` by default) but you could expose helpers if necessary.
