### ISSUE TITLE
Server Components are not working

### ISSUE THREAD

**Issue by joni1802** [nuxt/nuxt#24267]
### Environment

OS: Windows 11
Node Version: v20.9.0
NPM Version: 10.2.3
Nuxt Version: 3.8.1

### Reproduction

1. Create a new Nuxt project ``npx nuxi@latest init xxx``.
2. Go to the project folder and run ``npm install``.
3. Create a Server Component:
```
// components/TestServerComponent.server.vue
<script setup>
const dir = __dirname;
</script>

<template>
  <p>This runs on the server in the following directory: {{ dir }}</p>
</template>
```
4. Edit the app.vue filte:
```
// app.vue
<template>
  <TestServerComponent />
</template>
```

### Describe the bug

1. When I run ``npm run dev`` the pages renders correctly. But doing changes in the server component are not updated on the page. I always have to stop the script and run ``npm run dev`` again to see the changes.
2. Running ``npm run build`` and start the server with ``node .output/server/index.mjs`` renders a blank page and the following error is logged in the console:
```
[Vue warn]: Component <Anonymous> is missing template or render function.
```

**Comment by huang-julien** [comment]
I don't think we have access to `__dirname`, and you should rely on it since you won't have the same result in build.

However we should improve the error message.

**Comment by joni1802** [comment]
Thank you for the fast response. 
I have used ``__dirname`` just for testing because I know this is only available on the server side. Why this should not work? As of my understandig the code runs always on the server side and I should be able to use ``__dirname`` or ``fs.read()`` in scripts.
Also the HMR problem still persists even if I remove the ``__dirname`` thing.
