### ISSUE TITLE
middleware does not work as expected

### ISSUE THREAD

**Issue by qoo1476** [nuxt/nuxt#24263]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.17.1
- Nuxt Version:     3.8.1
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      ssr, app, telemetry, spaLoadingTemplate, experimental, css, devtools, nitro, modules, components, build, imports, vite
- Runtime Modules:  @vueuse/nuxt@10.6.0, @unocss/nuxt@0.57.3, @pinia/nuxt@0.5.1
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-sbzjzu-ymnnnu

### Describe the bug

see reproduction. there are simple layout and page components and middleware.

1. i used page-key with custom state ( for rerendering page component with same path )
2. click 'Move To INDEX' button several times to rerendering index page it always trigger onMounted function and initial number ref as i expected.
3. see console to hit middleware log. if i move to diffrent path page then hit middleware log. but not on the same path (even i use custom page key and it rerendering everything on page)

i don't know it because 'from' and 'to' path has physically same path
then is there any way to just trigger middleware again?
because i don't want to reload whole page again with location.href (original my app's layout has many components, api request, so it's slow to refresh page, not good for ux)

**Comment by danielroe** [comment]
You should use a function in this case if you are keying the page based on the route:

```vue
<script setup lang="ts">
const pageKey = useState<number>('pageKey', () => 0);
</script>

<template>
  <div>
    <NuxtLayout>
      <NuxtPage :page-key="route => `${route.fullPath}_${pageKey}`" />
    </NuxtLayout>
  </div>
</template>
```

See https://nuxt.com/docs/api/components/nuxt-page#example.

**Comment by qoo1476** [comment]
thank you for the replying!
i know it's closed but maybe my explain is bad. sorry for that

```
<NuxtPage :page-key="route => `${route.fullPath}_${pageKey}`" />
```
this is not helpful my case.

the point is even my custom pagekey is make refresh page but it diddn't come in my middleware.

if this is not bothering you please check my reproduction link and middleware's console log message when route same page

**Comment by danielroe** [comment]
The increase in page key reloads the page component but it doesn't change the route. Middleware is keyed on _route_ change and not on the loading of the page component.

Instead you can do something like this to _force_ a navigation to the same route.

```ts
const router = useRouter()
const movePage = (path) => router.push({ path, force: true });
```
