### ISSUE TITLE
A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. 

### ISSUE THREAD

**Issue by Foddie2** [nuxt/nuxt#24277]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.7.0
- CLI Version:      3.9.1
- Nitro Version:    2.6.2
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      ssr, devtools, css, plugins, postcss, modules, content, runtimeConfig
- Runtime Modules:  @nuxt/content@2.9.0, nuxt-purgecss@2.0.0, nuxt-mailer@0.11.0
- Build Modules:    -
------------------------------

### Reproduction

Clone this repo `https://github.com/Foddie2/TechBytes-Today.git`

### Describe the bug

Getting this error when I run in dev mode 

`[nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at `https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables`.`

**Comment by danielroe** [comment]
You need to call them in a setup function or other location where the Nuxt context is available.

This limitation is to avoid sharing state between requests.
