### ISSUE TITLE
The _nuxt folder could not be found in .output/public when building the application

### ISSUE THREAD

**Issue by NguyenDuyHieu987** [nuxt/nuxt#24272]
### Environment

OS: Windows 11
Node Version: v19.9.0
NPM Version: 9.6.3
Nuxt Version: 3.8.1

### Some of my configs in nuxt.config.ts:
```
app: {
    rootId: '__nuxt',
    // buildAssetsDir: '/home/',
    pageTransition: { name: 'page', mode: 'out-in', appear: true },
},
vite: {
    ssr: {
      external: ['compute-scroll-into-view', 'ant-design-vue', 'moment'],
      noExternal: [],
    },
    optimizeDeps: {
      include: ['./components/**/*.vue'],
    },
    css: {
      preprocessorOptions: {
        less: {
          math: 'always',
          relativeUrls: true,
          javascriptEnabled: true,
        },
      },
    },
    build: {
      sourcemap: 'hidden',
      minify: 'terser',
      ssrManifest: true,
      // assetsDir: 'home/',
      cssMinify: true,
      reportCompressedSize: false,
      terserOptions: {
        ecma: 2016,
        sourceMap: true,
        parse: {
          html5_comments: false,
        },
        compress: false,
        mangle: {},
        format: {
          ecma: 2016,
          comments: false,
        },
      },
    },
    vue: {
      script: {
        defineModel: true,
        propsDestructure: true,
      },
    },
    server: {
      hmr: {
        overlay: true,
      },
    },
  },
  vue: { defineModel: true, propsDestructure: true },
  nitro: {
    preset: 'static',
    prerender: {
      routes: [],
      crawlLinks: true,
    },
    storage: {},
    output: {
      // dir:'.output',
      // serverDir: '.output/server',
      // publicDir: '.output/public',
    },
  },
```

### Describe the bug

When I run `npm run build` with nuxt version 3.8.1 there is no `_nuxt` folder in the `.ouput/public` directory but when I change to version 3.8.0 it is fine.

**Comment by NguyenDuyHieu987** [comment]
> Can't reproduce with the given info.
> 
> <img alt="image" width="245" src="https://user-images.githubusercontent.com/640208/282521670-dac65a37-14ae-4c61-8e98-e0fd5354f41f.png">
> If you add `buildAssetsDir` and `build.assetsDir` (which are commented out right now), the `_nuxt` folder will be ranmed to the value set (in your case: `home`).

I did that but the result is still the same. Can you check for me to see where I went wrong?
[My reproduction](https://stackblitz.com/~/github.com/NguyenDuyHieu987/The-Movie-Nuxt-Antdv)

**Comment by manniL** [comment]
@NguyenDuyHieu987 I'm afraid I can't go through a full-blown project. Instead, you can try removing content / components / modules until you find out what is causing it and provide a [minimal reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction) 🙏🏻

Also, feel free to share how your .output folder content looks like.

**Comment by NguyenDuyHieu987** [comment]
I found the error! When building the project, there are a few routes with prerender errors, so it leads to not being able to create the `_nuxt` folder in the `public` directory.
