### ISSUE TITLE
Add an option to configure anchors Y position when scrolling to a hashLink

### ISSUE THREAD

**Issue by crunchwrap89** [nuxt/nuxt#24280]
### Describe the feature

When navigating to hash links, its not unusual that you actually want to add an additional couple of pixels to the scroll Y position.

It would be great if this could be controlled via an option in the nuxt.config, similar to the "scrollBehaviourType".

Proposed solution:
Add new option called "scrollY" that will take a positive or negative number of pixels for where the anchor will be.

```
export default defineNuxtConfig({
  router: {
    options: {
      scrollBehaviorType: 'smooth',
      scrollY: '50px'
    }
  }
})

```

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
Any reason you'd prefer this over [`scroll-padding-top`](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-padding-top)?

**Comment by crunchwrap89** [comment]
I did not know about that
It works just fine for me ^^. Sorry
