### ISSUE TITLE
Auto import from custom directory errors at runtime

### ISSUE THREAD

**Issue by chisomgbata** [nuxt/nuxt#24297]
------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.1
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools, imports
- Runtime Modules:  -
- Build Modules:    -
------------------------------

I don't get any errors from typescript when i setup custom dir to auto-import from, when i hover over the auto imported variable, I see the definition to indicate that it works, and even in nuxt dev tools, it is visible in the imports section, but when i want to use the variable it errors out as undefined at runtime

Reproduction Link: https://stackblitz.com/edit/github-ablgyz?file=nuxt.config.ts,custom%2Fcustom.ts,app.vue

**Comment by danielroe** [comment]
`imports.dirs` registers auto-imports for the entirety of your app except the server directory. For that directory, you need to set `nitro.imports.dirs` instead.
