### ISSUE TITLE
Experimental Payload Extraction breaks `@nuxtjs/ionic`

### ISSUE THREAD

**Issue by markglattback** [nuxt/nuxt#24291]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.7.0
- Nuxt Version:     3.8.1
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  pnpm@8.10.2
- Builder:          -
- User Config:      devtools, extends, ionic, modules, ssr
- Runtime Modules:  @nuxtjs/ionic@0.12.1
- Build Modules:    -
------------------------------

### Reproduction

See https://github.com/nuxt-modules/ionic/issues/484

### Describe the bug

When using the `@nuxtjs/ionic` module, serving the output of `nuxi generate` gives the following error:

`[nuxt] error caught during app initialization TypeError: Cannot read properties of undefined (reading 'beforeResolve')`

This is due to the `useRouter()` returning `undefined` when called inside the `nuxt:payload` hook.

### Additional context

Setting `experimental.payloadExtraction` to `false` solves the issue.

**Comment by ennioVisco** [comment]
> ### Environment
> * Operating System: Windows_NT
> * Node Version:     v20.7.0
> * Nuxt Version:     3.8.1
> * CLI Version:      3.9.1
> * Nitro Version:    2.7.2
> * Package Manager:  pnpm@8.10.2
> * Builder:          -
> * User Config:      devtools, extends, ionic, modules, ssr
> * Runtime Modules:  @nuxtjs/ionic@0.12.1
> * Build Modules:    -
> 
> ### Reproduction
> See [nuxt-modules/ionic#484](https://github.com/nuxt-modules/ionic/issues/484)
> 
> ### Describe the bug
> When using the `@nuxtjs/ionic` module, serving the output of `nuxi generate` gives the following error:
> 
> `[nuxt] error caught during app initialization TypeError: Cannot read properties of undefined (reading 'beforeResolve')`
> 
> This is due to the `useRouter()` returning `undefined` when called inside the `nuxt:payload` hook.
> 
> ### Additional context
> Setting `experimental.payloadExtraction` to `false` solves the issue.
> 
> ### Logs
> _No response_

Oh thanks, I was trying to get which was the issue, but I completely missed it!

**Comment by eshanit** [comment]
Any progress? This is also happening in vue3

**Comment by manniL** [comment]
@eshanit you should be able to turn off payload extraction via `experimental.payloadExtraction: false`

**Comment by danielroe** [comment]
Would you open an issue in https://github.com/nuxt-modules/ionic instead? 🙏

**Comment by markglattback** [comment]
https://github.com/nuxt-modules/ionic/issues/484
