### ISSUE TITLE
Nuxt Build Failure: Unhandled 'undefined' in Plugins Configuration (TypeError: Cannot read property 'src' of undefined )

### ISSUE THREAD

**Issue by amjad1233** [nuxt/nuxt#24301]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@nuxt/builder@2.15.8` for the project I'm working on.

## Description
I've encountered a persistent issue during the build process of a Nuxt.js application, which seems to be related to the handling of `undefined` values in the plugins array. The problem arises when custom configurations, particularly for authentication headers, are added to the Druxt module. This modification seems to inadvertently introduce `undefined` entries into the plugins array, leading to build failures.

The specific error occurs during the 'Generating nuxt files' stage and manifests as a failure to correctly process plugins, leading to a fatal error: `TypeError: Cannot read property 'src' of undefined`. This indicates that somewhere in the process, an `undefined` entry is being encountered in the plugins array.

A closer examination of the code in `node_modules/@nuxt/builder/dist/builder.js` suggests that the `normalizePlugins` method does not account for `undefined` or `null` values within the plugins array. This oversight becomes problematic when additional configurations are introduced that inadvertently push `undefined` values into this array.

I've applied a temporary fix by modifying the method to filter out `undefined` or `null` values. This workaround involves adding a check at the start of the `.map()` function within `normalizePlugins` to return `undefined` for any such values, followed by a `.filter(p => p !== undefined)` operation to remove these from the final array.

While this approach resolves the immediate build issue, a more robust solution within Nuxt.js to handle such cases gracefully would be beneficial. This fix would prevent similar issues for other users who might encounter `undefined` values in their plugins array due to various custom configurations or modifications.

## Steps to Reproduce
1. Modify the Nuxt.js configuration to include custom authentication headers using the Druxt module.
2. Run the build command (`nuxt build`).
3. Observe the build process failure during the 'Generating nuxt files' stage.

## Expected Result
The build process should handle `undefined` or `null` values in the plugins array gracefully without causing a build failure.

## Actual Result
The build process fails with a `TypeError: Cannot read property 'src' of undefined`, indicating an unhandled `undefined` entry in the plugins array.

I believe this issue warrants further investigation and possibly an enhancement to the Nuxt.js core to better handle such scenarios.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@nuxt/builder/dist/builder.js b/node_modules/@nuxt/builder/dist/builder.js
index fc6cb88..f2ed878 100644
--- a/node_modules/@nuxt/builder/dist/builder.js
+++ b/node_modules/@nuxt/builder/dist/builder.js
@@ -407,9 +407,15 @@ class Builder {
     const modePattern = new RegExp(`\\.(${modes.join('|')})(\\.\\w+)*$`);
     return lodash.uniqBy(
       this.options.plugins.map((p) => {
+        // If p is undefined or null, skip processing it
+        if (p == null) {
+          return undefined;
+        }
+
         if (typeof p === 'string') {
           p = { src: p };
         }
+
         const pluginBaseName = path__default['default'].basename(p.src, path__default['default'].extname(p.src)).replace(
           /[^a-zA-Z?\d\s:]/g,
           ''
@@ -434,9 +440,10 @@ class Builder {
           mode: p.mode,
           name: 'nuxt_plugin_' + pluginBaseName + '_' + hash__default['default'](p.src)
         }
-      }),
+      }).filter(p => p !== undefined), // Filter out undefined or null values
       p => p.name
-    )
+    );
+
   }
 
   addOptionalTemplates (templateContext) {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️
