### ISSUE TITLE
Netlify edge and isr return 500 and build fail with a certain number of pre-rendered pages

### ISSUE THREAD

**Issue by DidoMarchet** [nuxt/nuxt#24317]
Hi,
I saw if there a number of prerender pages (around 300) with netlify-edge, netlify returns a lot of 500. If I reduce the pages (for example removing a locale) it works as expected.
So I'm wonder if there's some tips deploying nuxt 3 with netlify edge and routeRules { '/**': {isr:true}.

Any idea would be appreciate!

Really thanks and kind regards,
Davide

**Comment by danielroe** [comment]
This seems like it might be a platform limitation that we should document, but using ISR seems like a good solution.

cc: @pi0

**Comment by DidoMarchet** [comment]
Hi @danielroe and thanks. So I will try to ask to netlify team😞 do
Can I ask if you  have experience or do
You know large website that use this configuration?

Really thanks again and kind regards, Davide
