### ISSUE TITLE
After using swr to render the page in nitro, some variable values ​​failed to update.

### ISSUE THREAD

**Issue by lxccc812** [nuxt/nuxt#24326]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v16.19.1
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.1
- Package Manager:  pnpm@8.9.2
- Builder:          -
- User Config:      modules, ssr, runtimeConfig, devServer, experimental, css, routeRules, nitro, app, pwa, devtools, site, sitemap, gtm, device
- Runtime Modules:  nuxt-swiper@1.2.2, @unocss/nuxt@0.57.1, @vueuse/nuxt@10.5.0, @nuxtjs/device@3.1.1, @vite-pwa/nuxt@0.1.1, nuxt-simple-sitemap@3.4.1, @zadigetvoltaire/nuxt-gtm@0.0.13
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-j4gwru?file=nuxt.config.ts

### Describe the bug

After I use swr rendering rules for some routes, some variables in the routes cannot follow the changes of the device even if they are modified. I use `@nuxtjs/device@3.1.1` to determine the current device.

### Additional context

How to test:
  With `swr` open, change the device type through chrome's device toobar and observe the variable values ​​printed on the homepage. You can observe that: on the mobile phone, 'Desktop' will be displayed for the first time, and then immediately changed to 'Mobile'

### Logs

```shell-script
None
```

**Comment by danielroe** [comment]
Anything that should be specific to the individual request (like a device size) should not have `swr` enabled, as this is a form of caching that shares responses between requests.

**Comment by lxccc812** [comment]
But caching is necessary for me, and there are also requirements for different devices to display different layouts (styles). How should I implement it reasonably?

**Comment by danielroe** [comment]
Instead, you should make sure to load consistent HTML no matter the user's device. And use CSS to control what is shown on different devices (or update the layout after the app is mounted).
