### ISSUE TITLE
NuxtErrorBoundary dont effects in v-html

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/nuxt#24327]
### Environment

https://stackblitz.com/edit/nuxt-starter-zcpije

### Reproduction

He have an string with wrong html that its called in a v-html

We try to catch de error, envolved it in a NuxtErrorBoundary but the error persists.

![image](https://github.com/nuxt/nuxt/assets/77386602/e3afa122-3e30-47ed-858c-5cfd7ad3a611)

### Describe the bug

He have an string with wrong html that its called in a v-html

We try to catch de error, envolved it in a NuxtErrorBoundary but the error persists.

![image](https://github.com/nuxt/nuxt/assets/77386602/e3afa122-3e30-47ed-858c-5cfd7ad3a611)

**Comment by agracia-foticos** [comment]
@danielroe sorry, i fixed the stackblitz environment
https://stackblitz.com/edit/nuxt-starter-zcpije

In the end it all boils down to: How can I handle the error when the string that I include within the v-html has an incorrect format?

**Comment by danielroe** [comment]
The tricky thing is that Vue doesn't throw an error; it just prints a warning, so we can't catch it and handle it.

**Comment by agracia-foticos** [comment]
> The tricky thing is that Vue doesn't throw an error; it just prints a warning, so we can't catch it and handle it.

In our case, throws distinct error
![image](https://github.com/nuxt/nuxt/assets/77386602/6797c4fe-e90d-450f-8820-e648758402b1)

Similar that a parent node error :(
