### ISSUE TITLE
When using the nitro preset as 'node', the example in the documentation does not execute correctly.

### ISSUE THREAD

**Issue by trylovetom** [nuxt/nuxt#24324]
### Environment

```sh
Nuxt project info:

------------------------------
- Operating System: Linux
- Node Version:     v16.17.0
- Nuxt Version:     3.8.1
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, nitro
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Reproduction

1. Configuring `nuxt.config`
```ts
export default defineNuxtConfig({
  nitro: { preset: 'node' }
})
```

2. Creating an `index.mjs` server
```ts
import { createServer } from 'node:http'
import { handler } from './.output/server/index.mjs'

const server = createServer(handler)
server.listen(3000)
```

3. Compiling and starting the server
```sh
yarn build && node index.mjs
```

[Reproduction Here](https://codesandbox.io/p/sandbox/practical-bird-2v7hy5?file=%2F.codesandbox%2Ftasks.json%3A34%2C35&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clp0o4t0z000c3b6k6r236dt0%2522%252C%2522sizes%2522%253A%255B57.90419162%252C42.09580838%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clp0o4t0z00033b6km9ezvzz5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clp0o4t0z00093b6kb1i58g4f%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clp0o4t0z000b3b6k6oc6syxf%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clp0o4t0z00033b6km9ezvzz5%2522%253A%257B%2522id%2522%253A%2522clp0o4t0z00033b6km9ezvzz5%2522%252C%2522activeTabId%2522%253A%2522clp0or5y101cr3b6jv5plb4f8%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clp0or5y101cr3b6jv5plb4f8%2522%252C%2522mode%2522%253A%2522temporary%2522%257D%255D%257D%252C%2522clp0o4t0z000b3b6k6oc6syxf%2522%253A%257B%2522id%2522%253A%2522clp0o4t0z000b3b6k6oc6syxf%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522yarn%2520build%2520%2526%2526%2520node%2520index.mjs%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clp0oo9fo00vr3b6j2s9a6of3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clp0oo9fo00vr3b6j2s9a6of3%2522%257D%252C%2522clp0o4t0z00093b6kb1i58g4f%2522%253A%257B%2522id%2522%253A%2522clp0o4t0z00093b6kb1i58g4f%2522%252C%2522activeTabId%2522%253A%2522clp0onuml00q53b6jmd5jytwd%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522yarn%2520build%2520%2526%2526%2520node%2520index.mjs%2522%252C%2522id%2522%253A%2522clp0onuml00q53b6jmd5jytwd%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Describe the bug

Expected Result:
The server should start normally and execute the Vue program in the client side without issues.
![Kapture 2023-11-16 at 12 32 58](https://github.com/nuxt/nuxt/assets/13268073/919c3160-467a-4291-9d37-bb409c294be3)

Actual Result:
The server starts up correctly, but the Vue program in the client side fails to execute.
![Kapture 2023-11-16 at 12 34 34](https://github.com/nuxt/nuxt/assets/13268073/bd9d00ff-e592-4007-8dbd-53cb3d951cb4)

### Additional context

Nuxt and Nitro are fantastic, and I really appreciate this community and the team's effort. However, I expected that following the Nuxt and Nitro documentation for setup would result in a successful execution. I would appreciate some assistance in troubleshooting this issue. Thank you.

https://nitro.unjs.io/deploy/runtimes/node#handler-advanced

### Logs

```shell-script
[Vue Router warn]: No match found for location with path "/_nuxt/entry.97d8de00.js"
[Vue Router warn]: No match found for location with path "/_nuxt/entry.97d8de00.js"
[Vue Router warn]: No match found for location with path "/_nuxt/entry.97d8de00.js"
[Vue Router warn]: No match found for location with path "/_nuxt/entry.97d8de00.js"
[Vue Router warn]: No match found for location with path "/_nuxt/index.ae8c31f5.js"
[Vue Router warn]: No match found for location with path "/_nuxt/index.ae8c31f5.js"
[Vue Router warn]: No match found for location with path "/_nuxt/index.ae8c31f5.js"
[Vue Router warn]: No match found for location with path "/_nuxt/index.ae8c31f5.js"
[Vue Router warn]: No match found for location with path "/_nuxt/error-500.4b457395.js"
[Vue Router warn]: No match found for location with path "/_nuxt/error-500.4b457395.js"
[Vue Router warn]: No match found for location with path "/_nuxt/error-500.4b457395.js"
[Vue Router warn]: No match found for location with path "/_nuxt/error-500.4b457395.js"
[Vue Router warn]: No match found for location with path "/_nuxt/vue.f36acd1f.5681e6db.js"
[Vue Router warn]: No match found for location with path "/_nuxt/vue.f36acd1f.5681e6db.js"
[Vue Router warn]: No match found for location with path "/_nuxt/vue.f36acd1f.5681e6db.js"
[Vue Router warn]: No match found for location with path "/_nuxt/vue.f36acd1f.5681e6db.js"
[Vue Router warn]: No match found for location with path "/_nuxt/error-404.4a434e74.js"
[Vue Router warn]: No match found for location with path "/_nuxt/error-404.4a434e74.js"
[Vue Router warn]: No match found for location with path "/_nuxt/error-404.4a434e74.js"
[Vue Router warn]: No match found for location with path "/_nuxt/error-404.4a434e74.js"
[Vue Router warn]: No match found for location with path "/_nuxt/index.ae8c31f5.js"
[Vue Router warn]: No match found for location with path "/_nuxt/index.ae8c31f5.js"
[Vue Router warn]: No match found for location with path "/_nuxt/index.ae8c31f5.js"
[Vue Router warn]: No match found for location with path "/_nuxt/index.ae8c31f5.js"
[Vue Router warn]: No match found for location with path "/_nuxt/entry.97d8de00.js"
[Vue Router warn]: No match found for location with path "/_nuxt/entry.97d8de00.js"
[Vue Router warn]: No match found for location with path "/_nuxt/entry.97d8de00.js"
[Vue Router warn]: No match found for location with path "/_nuxt/entry.97d8de00.js"
[Vue Router warn]: No match found for location with path "/_nuxt/error-404.4a434e74.js"
[Vue Router warn]: No match found for location with path "/_nuxt/error-404.4a434e74.js"
[Vue Router warn]: No match found for location with path "/_nuxt/error-404.4a434e74.js"
[Vue Router warn]: No match found for location with path "/_nuxt/error-404.4a434e74.js"
[Vue Router warn]: No match found for location with path "/_nuxt/error-500.4b457395.js"
[Vue Router warn]: No match found for location with path "/_nuxt/error-500.4b457395.js"
[Vue Router warn]: No match found for location with path "/_nuxt/error-500.4b457395.js"
[Vue Router warn]: No match found for location with path "/_nuxt/error-500.4b457395.js"
[Vue Router warn]: No match found for location with path "/_nuxt/vue.f36acd1f.5681e6db.js"
[Vue Router warn]: No match found for location with path "/_nuxt/vue.f36acd1f.5681e6db.js"
[Vue Router warn]: No match found for location with path "/_nuxt/vue.f36acd1f.5681e6db.js"
[Vue Router warn]: No match found for location with path "/_nuxt/vue.f36acd1f.5681e6db.js"
```

**Comment by danielroe** [comment]
`node-server` is probably what you want.

`node` is, to quote from the docs:

> ... a more low-level preset that directly exports a function with (req, res) => {} signature usable for middleware and custom servers.

**Comment by trylovetom** [comment]
@danielroe thanks, enable `serveStatic` is suitcase for me. Maybe this related options should be notice on doc.
