### ISSUE TITLE
`useAsyncData` ReturnType error

### ISSUE THREAD

**Issue by hminghe** [nuxt/nuxt#24353]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.1
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-ahyg3i?file=test.test.ts

### Describe the bug

The return type of `useAsyncData` is not as expected.
see `test.test.ts`

**Comment by arashsheyda** [comment]
I think having a type like `number[] | null` for useAsyncData is normal. It accounts for the initial state (null) before the data is fetched and helps handle potential errors.

**Comment by manniL** [comment]
As explained by @arashsheyda 👍 

So the data is `null` if:

* there is an error
* initially if you use `lazy: true` or `useLazyAsyncData` ☺️

**Comment by DamianGlowala** [comment]
Shall we keep it open unless the other case included in the reproduction is justified (`number[] | never[]`)?

**Comment by manniL** [comment]
> Shall we keep it open until the other case included in the reproduction is justified (number[] | never[])?

I think this is fine.

`never[]` will be `[]` if data would be null (default) or `number[]` if data exists.
