### ISSUE TITLE
Detect if navigation page is served from server or client

### ISSUE THREAD

**Issue by mkierdev** [nuxt/nuxt#24352]
### Environment

Nuxt 3.5

### Reproduction

```js
// app.vue
watch(
  () => route.path,
  () => {
    console.log(process.client && useNuxtApp().payload.serverRendered);
  }
);
```

### Describe the bug

If you navigate through pages in your application, above code will always return true. It should return true only on first page, according to this comment: https://github.com/nuxt/nuxt/issues/22643#issuecomment-1678896048.

Why do we need it?
We are fetching every page data with useFetch(). We want to use it only on the first load, and each request on client-side should be handled by $fetch instead. Even if we navigate between pages on client, each request is added to useNuxtApp().payload which is dangerous for large-scale app and memory management.

**Comment by danielroe** [comment]
The comment linked is allowing you to detect if the _first_ page of a site was server rendered.

To detect while running its setup function if the _current_ page is rendered on the server you can use `nuxtApp.isHydrating && nuxtApp.payload.serverRendered`.

**Comment by mkierdev** [comment]
@danielroe it may serve some use-cases, but if we want to launch code inside onNuxtReady() nuxtApp.isHydrating will always be false. I assume there is no in-built solution for this case?
