### ISSUE TITLE
 ERROR  [unhandledRejection] read ECONNRESET    

### ISSUE THREAD

**Issue by Foddie2** [nuxt/nuxt#24355]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.7.0
- CLI Version:      3.9.1
- Nitro Version:    2.6.2
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      ssr, devtools, css, plugins, postcss, modules, content, runtimeConfig
- Runtime Modules:  @nuxt/content@2.9.0, nuxt-purgecss@2.0.0, nuxt-mailer@0.11.0
- Build Modules:    -
------------------------------

### Reproduction

You can see it in this [repo](https://github.com/Foddie2/TechBytes.git)

### Describe the bug

Facing the following error when I run my code 

` ERROR  [unhandledRejection] read ECONNRESET                                                                                  

  at TCP.onStreamRead (node:internal/stream_base_commons:217:20)`

**Comment by warflash** [comment]
The error itself seems similar to https://github.com/nuxt/nuxt/issues/23832#issuecomment-1782885973. Loading up your project I can't seem to reproduce it locally so I can't verify whether that fixes is unfortunately

**Comment by Foddie2** [comment]
Thanks, it works
