### ISSUE TITLE
no prerenderedAt value when static page generated using ISR

### ISSUE THREAD

**Issue by silverbackdan** [nuxt/nuxt#24362]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.18.0`
- Nuxt Version:     `3.8.1`
- CLI Version:      `3.9.1`
- Nitro Version:    `2.7.2`
- Package Manager:  `pnpm@8.10.5`
- Builder:          `-`
- User Config:      `devtools`, `routeRules`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/silverbackdan/nuxt-isr-reproduction

On Vercel
https://nuxt-isr-reproduction.vercel.app/

Refresh pages to see content served from the server.

### Describe the bug

The prerenderedAt value should be set I think when the static version has been generated on the vercel side too? I think it'd give us a definitive value to check to see when the version being served was generated. Is this possible?

**Comment by silverbackdan** [comment]
Hi, I've pushed some updates - I've also noticed that the `prerenderedAt` value is only set and then retained depending on the very first load. When the page then changes, would it be reasonable to expect this value to then update as on the client-side the next page will always then be client-rendered, or do you think this should be the responsibility of the developer?

**Comment by silverbackdan** [comment]
P.s. mind if I sneak a quick question in as well? On an ISR load, do I need to do something specific with a `fetch` to an API to still be carried out even on a static/isr page load?

**Comment by danielroe** [comment]
With ISR, there is no prerendering as such. (Prerendering is a stage in the build process after the Vue app is built with vite, and before the nitro server is built.)

`prerenderedAt` is also only with respect to the first page.

Implementing a `renderedAt` option for all pages should be very possible in your project, but I'm not sure we'd want that in Nuxt in case it leaks too much information for users.

**Comment by silverbackdan** [comment]
Ah ok, I see - I thought perhaps under the hood it was calling the same rendering process.

No problem if it isn't something that would be useful within the Nuxt core I'm happy to close and figure out my method for a `renderedAt` variable in context of my appllication

Thanks for your time.
