### ISSUE TITLE
useQuery and useParams composables

### ISSUE THREAD

**Issue by 1nusah** [nuxt/nuxt#24365]
### Describe the feature

useQuery should return all route queries.
useParams should all return all route params.

Currently we have to first call the useRoute composable before getting the route queries and or route params.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by DamianGlowala** [comment]
I believe a reproduction isn't needed here, as it is a feature request.

To summarise, the author proposes the following shortand methods for accessing:
- route's query: `useRoute().query` -> `useQuery()`;
- route's params: `useRoute().params` -> `useParams()`.

If we decided to go ahead with the implementation, I would vote for more precise naming: `useRouteQuery` and `useRouteParams`.

**Comment by 1nusah** [comment]
@manniL @DamianGlowala  useRouteQuery and useRouteParams sounds better. Also this is a feature request. I've worked on this locally and will push if given the go ahead

**Comment by manniL** [comment]
> I believe a reproduction isn't needed here, as it is a feature request.

My bad, misunderstood that!

I personally don't mind adding the helper composables, though the same *could* be implemented in the user land already today.

**Comment by 1nusah** [comment]
> > I believe a reproduction isn't needed here, as it is a feature request.
> 
> My bad, misunderstood that!
> 
> I personally don't mind adding the helper composables, though the same _could_ be implemented in the user land already today.

hi, what's the user land?

**Comment by manniL** [comment]
> hi, what's the user land?

As in "your own project". You could add these composables in the `composables` folder already to avoid writing `useRoute().query` etc. all the time ☺️

**Comment by 1nusah** [comment]
I'm very interested in contributing to nuxt.  I'll be going through the issues and try fixing some. I'd appreciate any guidance too.

**Comment by danielroe** [comment]
~> https://github.com/nuxt/nuxt/pull/24369#issuecomment-1820677093
