### ISSUE TITLE
`useFetch` triggers before route params have been loaded when navigating to route

### ISSUE THREAD

**Issue by zusorio** [nuxt/nuxt#24363]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.8.1
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  npm@9.5.1
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  @nuxtjs/supabase@1.1.4, @nuxt/ui@2.10.0, nuxt-icon@0.6.6, @vueuse/nuxt@10.6.1
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-eq2suc?file=pages%2Findex.vue

### Describe the bug

If you `useFetch` with a route parameter as part of the query, that parameter will not load before the data is fetched.

However, if you go to the page directly or if you refresh it then the parameter is used and everything is fine.

**Comment by danielroe** [comment]
You need to use `<NuxtPage>` and not `<RouterView>`. We handle all kinds of edge cases for you that `<RouterView>` does not.
