### ISSUE TITLE
production server not not hosted on NITRO_PORT from .env

### ISSUE THREAD

**Issue by sebaguse** [nuxt/nuxt#24373]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.8.1
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  npm@9.5.1
- Builder:          -
- User Config:      app, runtimeConfig, css, modules, quasar, pinia, imports, vite, content, vue, nitro, devtools, devServer
- Runtime Modules:  nuxt-quasar-ui@2.0.6, @pinia/nuxt@0.5.1, @vueuse/nuxt@10.6.1, @pinia-plugin-persistedstate/nuxt@1.2.0, @nuxt/content@2.9.0, @formkit/auto-animate/nuxt@0.8.1
- Build Modules:    -

### Reproduction

* define Nitro port in .env:
NITRO_PORT=3003
* run dev server with `npx nuxi dev`
* application hosted on correct port: http://localhost:3003
* build the app with 'npx nuxi build` and host using `node .output/server/index.mjs`, the app is hosted on port 3000.

### Describe the bug

Production app not properly hosted on port defined in .env, not sure if this is Nuxt or Nitro bug, apology if raised in wrong repository.

**Comment by danielroe** [comment]
The production server does not read `.env` in - try setting the port value explicitly when running your production server:

```sh
NITRO_PORT=3003 node playground/.output/server/index.mjs
```

You can track support for reading `.env` at runtime via https://github.com/unjs/nitro/issues/1079 or use Node 20.6+ with `--env-file`: https://nodejs.org/docs/latest-v20.x/api/cli.html#--env-fileconfig.
