### ISSUE TITLE
3.8.2 An error occurred in the console after upgrading

### ISSUE THREAD

**Issue by facexyy** [nuxt/nuxt#24383]
### Environment

nuxt 3.8.2

### Reproduction

![image](https://github.com/nuxt/nuxt/assets/148040903/af619d5b-a6b0-4f36-b96d-9cd9740e92c3)

### Describe the bug

3.8.1 Error after upgrading to 3.8.2

**Comment by PatrikBird** [comment]
did you use 
```
npx nuxi upgrade --force
```
to upgrade?

**Comment by facexyy** [comment]
![image](https://github.com/nuxt/nuxt/assets/148040903/0c8212c4-77ae-47d4-afb7-5f37783a2816)
![image](https://github.com/nuxt/nuxt/assets/148040903/4f0d17de-69a7-47b1-a519-cbd6500917b8)
Yes, I used it again

**Comment by facexyy** [comment]
![Uploading image.png…]()
Is it because of this?
I don't know how to modify this

**Comment by facexyy** [comment]
Wait, I just used npx nuxi upgrade --force
Reopen VScode and restart the project. The error seems to have disappeared.

**Comment by facexyy** [comment]
I will close issues first and continue to observe
