### ISSUE TITLE
Prerendering via `nuxt generate` broken when using relative baseURL

### ISSUE THREAD

**Issue by jwahdatehagh** [nuxt/nuxt#24390]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools, app
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-vkjeze?file=nuxt.config.ts

### Describe the bug

Running the `generate` command fails when using a relative baseURI.

![Screenshot 2023-11-21 at 16 07 43](https://github.com/nuxt/nuxt/assets/2725836/c72c32b1-2b0b-4442-a25b-cf7e36d9d151)

**Comment by danielroe** [comment]
let's track this in https://github.com/nuxt/nuxt/issues/28474.
