### ISSUE TITLE
Template Refs are undefined in onMounted hook in *.client.vue components

### ISSUE THREAD

**Issue by OrlS15** [nuxt/nuxt#24398]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.6.1
- Nuxt Version:     -
- CLI Version:      3.10.0
- Nitro Version:    -
- Package Manager:  npm@10.1.0
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-f3bfuh?file=app.vue

1. Open the reproduction in a new window
2. Open the console
3. TestComp.vue prints the div element, TestComp.client.vue prints undefined.

### Describe the bug

Template Refs are undefined in onMounted hook in client components.

```vue
// TestComp.client.vue
<script setup lang="ts">
const divRef = ref();
onMounted(() => {
  console.log('onMounted');
  console.log(divRef.value); // undefined
});
</script>

<template>
  <div ref="divRef" />
</template>
```

This components prints undefined in the console if its clientonly (it works if wrapped in ClientOnly but not if the file is .client.vue)

**Comment by warflash** [comment]
This behaviour is by design as noted in the docs: https://nuxt.com/docs/guide/directory-structure/components#client-components. To get access to template refs you want to add `await nextTick()` in the mounted hook
