### ISSUE TITLE
Nuxt>3.7.0 Client with deactivated "renderJsonPayloads" fails with "TypeError: Cannot read properties of undefined (reading 'baseURL')"

### ISSUE THREAD

**Issue by johannes-wtfoxtrot** [nuxt/nuxt#24391]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.7.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      experimental
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-1ck4gv-jlars8?file=nuxt.config.ts

Or:

(1) Install a new project with nuxt@3.7.0 (or 3.8.2)

(2) Edit nuxt.config.ts
```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  experimental: {
    renderJsonPayloads: false,
  },
});
```

(3) Generate and serve
`nuxt generate && nuxt start`

(4) Open in browser

### Describe the bug

In Chrome, the application crashes immediately and does not become interactive.

```
Uncaught TypeError: Cannot read properties of undefined (reading 'baseURL')
    at Lo (entry.6ea0d6d1.js:1:64338)
    at entry.6ea0d6d1.js:1:70997
```

### Additional context

It seems, that the entry-file (`entry.6ea0d6d1.js`) is executed before `window.__NUXT__` is defined.

```
const useRuntimeConfig$1 = () => {
  var _a2;
  return ((_a2 = window == null ? void 0 : window.__NUXT__) == null ? void 0 : _a2.config) || {};
};
const appConfig = useRuntimeConfig$1().app;
const baseURL = () => appConfig.baseURL;
```

`appConfig` is then undefined, leading to the observed error.

I would guess that this is caused by the changes in https://github.com/nuxt/nuxt/pull/22179/files#diff-db3a4ecfe5a4e5a379ed2f515a315f812ddc26b48ce80dd3f2cada3b75c06c12.

In 3.6.5 the script defining `window.__NUXT__` was loaded right before the entry-file at the bottom of the `<body>`. In >3.7.0 the entry-file became part of the `<head>`. This seems to be incompatible with deactivating `renderJsonPayloads`.

**Comment by hardik1410** [comment]
@johannes-wtfoxtrot Did you find any workaround for this?

I am currently seeing a similar issue after adding `renderJsonPayloads: false` in nuxt config.

**Comment by uke5tar** [comment]
+1 on this issue. Is there are a timeline for fixing it?

**Comment by danielroe** [comment]
We test in nuxt/nuxt against `renderJsonPayloads: false` and haven't encountered the issue there, suggesting this is a race condition.

**Comment by uke5tar** [comment]
@danielroe  There is a reproduction link from the author: https://stackblitz.com/edit/github-1ck4gv-jlars8?file=README.md&issueNumber=24391&issueRepo=nuxt/nuxt

I can see the error there too. Can you confirm?

**Comment by uke5tar** [comment]
Is there any recommendation on how to deal with this? I think the reason we are having this in our code is because of this: https://github.com/nuxt/nuxt/issues/20889

So I assume we can't just use `renderJsonPayloads: false` at the moment with SSG?

**Comment by danielroe** [comment]
Yes. Or you can wait until v3.12.

**Comment by uke5tar** [comment]
Awesome. Last question from my side: Do you know when you will release v.3.12? This would help me in my planning. Thank you very much for all your work by the way 👍 I am a big fan of nuxt.

**Comment by danielroe** [comment]
should be quite soon: https://github.com/nuxt/nuxt/pull/26703
