### ISSUE TITLE
Infinite loop when plugin/middleware throw error

### ISSUE THREAD

**Issue by Atinux** [nuxt/nuxt#24393]
### Environment

Nitro 2.8.0

### Reproduction

https://stackblitz.com/edit/github-syrpot?file=server%2Fapi%2Ftest.ts,plugins%2Ftest.server.ts

### Describe the bug

If we create a plugin using `useRequestFetch()`, the http headers from the browser are forwarded (`accept: 'text/html'`), and since [this commit](https://github.com/unjs/nitro/commit/0a5911e342a24d5099b6045605913d5d52d30d46) in Nitro, it won't look at it as JSON request.

What is weird is that when calling the API route and rendering the error page, it calls again the Nuxt plugin with the API route as path (I suspected to never do this).

### Additional context

Workaround is to explicit set the text/json header.

```ts
await useRequestFetch()('/api/test', {
  headers: {
    Accept: 'text/json',
  },
}).catch(() => {});
```

**Comment by pi0** [comment]
Todo:

- [ ] Avoid proxy `accept` header by default
- [ ] Decouple error tests to avoid depending Nuxt on nitro internal utils
- [ ] (to discuss) disable user plugins and middleware for the **default error handler***
