### ISSUE TITLE
Prerender.Routes problem dealing with trailing slashes

### ISSUE THREAD

**Issue by lassediercks** [nuxt/nuxt#24392]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.1
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      nitro
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-rqmpdd?file=pages%2F[..._].vue,layouts%2Fdefault.vue,nuxt.config.ts

1. Open the reproduction in a new window
2. Click on any of the links
3. `Content has been fetched, even when it should be pregenerated` should appear in console even though all routes should've been prerendered

### Describe the bug

When adding routes with a trailing slash to nitro.prerender.routes the prerendered content is not used and the page is refetched instead.

### Additional context

The behaviour does not seem to appear with nuxt version `3.6.5`

https://stackblitz.com/edit/github-rqmpdd-ih3byq?file=pages%2F[..._].vue,nuxt.config.ts,layouts%2Fdefault.vue,pages%2Findex.vue

**Comment by danielroe** [comment]
If you log the `cacheKey` you have created you will see that when prerendering it is `/evan/` but in production without the trailing slash, the cache key is `/evan`. This is because your key _depends_ on the trailing slash. Instead, you should ensure you do not depend on the trailing slash for your key. You can use `withoutTrailingSlash` from ufo as a helpful utility to strip it if you really need to use the path.

**Comment by lassediercks** [comment]
Hey @danielroe ,

the `cacheKey` variable indeed had the trailing slash included.
That variable was not used as the cache key though. 

Instead the route param is used as the cache key.  Only including single string `anthony,daniel,evan` 

Sorry for the confusion, I've updated the reproduction

**Comment by alihardan** [comment]
Same problem. It happen after upgrading to `Nuxt  3.8.1`. I'm temporarily reverting to `3.8.0`.
