### ISSUE TITLE
Netlify preset doesn't build when running "nuxt generate"

### ISSUE THREAD

**Issue by DreaMinder** [nuxt/nuxt#24394]
### Environment

Local env with node 18 and 20 on OS X;
Netlify env with node 18 on Ubuntu 20;
Nuxt version since 3.6.0 (can't reproduce this bug on 3.5.*, but server routes don't work there anyway when deployed to netlify).

### Reproduction

https://stackblitz.com/edit/github-grmvj5?file=nuxt.config.ts - run `npm run generate` in terminal

### Describe the bug

Terminal throws error `ENOENT: no such file or directory, open '[project dir]/.netlify/functions-internal/server/server.json'` when trying to build a project with `netlify` preset.

### Additional context

No issues in dev mode though, it builds and lets me make browser-request to server routes.
<sub>Also, Nuxt doesn't set preset automatically when building with Netlify. Also, server routes with `netlify-edge` preset don't work and return a default 404 page (netlify says no edge functions deployed).</sup>

**Comment by danielroe** [comment]
This is likely an upstream Nitro issue. Could you check whether this is reproducible on https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world ?

**Comment by DreaMinder** [comment]
@danielroe yeah, might be, but I couldn't reproduce it with nitro-only setup: it finished building without issues and pointed out in logs that it used "netlify" preset.

**Comment by DreaMinder** [comment]
...actually `npm run build` works. But I need it to pregenerate some pages while also having server routes.

**Comment by DreaMinder** [comment]
I found a workaround:
```"generate": "NITRO_PRESET=netlify nuxi build && NITRO_PRESET=netlify-static nuxi generate" ```

Please let me know if it might have pitfalls.

I took a look at Nitro sources, looks like it's not a bug, but rather an unhandled use case. But to make it work, a lot of code needs to be rewritten. Closing for now, feel free to reopen 🙌

**Comment by DreaMinder** [comment]
UPD: server routes are still returning 404 page though... 😞

**Comment by DreaMinder** [comment]
My current solution to this problem is to:
1. add proper redirects and headers files manually to the codebase (for example caching headers and /api/* path proxy to netlify cloud function) 
```
/api/*    /.netlify/functions/server/api    200!
```
2. use this build command that prerenders first and then builds cloud functions on top of previous build  -
```
"generate:prod": "nuxi generate && nuxi build"
```
3. Set the following presets for each of the two builds in nuxt config:
``` 
const isPrerender = process.argv.includes('generate')
...
nitro: {
    preset: isPrerender ? 'static' : 'netlify'
},
```
4. disable public dir on build stage
``` 
nitro: {
    noPublicDir: !isPrerender,
    preset: isPrerender ? 'static' : 'netlify'
},
```


But, of course, it would be nice to have such a use case in Nuxt/Nitro core someday.
