### ISSUE TITLE
ERROR  Cannot start nuxt:  The requested module 'node:module' does not provide an export named 'isBuiltin'

### ISSUE THREAD

**Issue by littlegreay** [nuxt/nuxt#24402]
### Environment

ERROR  Cannot start nuxt:  The requested module 'node:module' does not provide an export named 'isBuiltin'

### Reproduction

ERROR  Cannot start nuxt:  The requested module 'node:module' does not provide an export named 'isBuiltin'

### Describe the bug

ERROR  Cannot start nuxt:  The requested module 'node:module' does not provide an export named 'isBuiltin'

### Additional context

ERROR  Cannot start nuxt:  The requested module 'node:module' does not provide an export named 'isBuiltin'

### Logs

```shell-script
ERROR  Cannot start nuxt:  The requested module 'node:module' does not provide an export named 'isBuiltin'
```

**Comment by hui00** [comment]
try to use the latest node version

**Comment by pi0** [comment]
~> https://github.com/unjs/unenv/issues/147 (still a reproduction would be nice as the used library that requires `isBuiltin` might require an actual impl to solve)

**Comment by emad313** [comment]
Try to use node v18.18.0 or latest one.

**Comment by JMKelley** [comment]
> Try to use node v18.18.0 or latest one.

This happened to me today, using @emad313 answer worked.

**Comment by valeri** [comment]
I think this is nuxt latest version problem try nuxt@3.7.4 version and this vue "^3.3.4" version 

I`m solve this problem on this way

**Comment by clopezpro** [comment]
I got this error after updating @nuxt/ui

I have the node version
v18.5.0

**Comment by clopezpro** [comment]
> Try to use node v18.18.0 or latest one.

Thank you, I no longer have problems using the node version 18.18.0
