### ISSUE TITLE
Rendering incorrect content when client plugin modifies state variables

### ISSUE THREAD

**Issue by Nomango** [nuxt/nuxt#24409]
### Environment

- Operating System: Linux
- Node Version:     v18.18.2
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      telemetry
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://codesandbox.io/p/devbox/unruffled-jang-8f7ywm

`yes` should be black, not red.

![image](https://github.com/nuxt/nuxt/assets/22350366/746d66be-2a9a-4cca-bf9a-b0245bca7ea1)

### Describe the bug

A client side plugin which modifies `state` variables will cause a rendering mistake.

**Comment by danielroe** [comment]
This is called a hydration error. You should ensure that you do not change the state of your app before it mounts, or there will be a mismatch between client + server.

**Comment by Nomango** [comment]
@danielroe Thanks for your reply. Is there a easy way to do something such as fetching user info before all components are mounted on client side?

**Comment by Nomango** [comment]
For example, I need to determine whether the user is logged-in in `onMounted` to decide whether to open Google One Tap Sign-in. So it is necessary to have a unified processing before mounting all components.

**Comment by danielroe** [comment]
Yes, you can use Nuxt plugins to run tasks before the app is mounted.
