### ISSUE TITLE
Explain returns for composables in data fetching guide

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt#24407]
The [data fetching guide](https://nuxt.com/docs/getting-started/data-fetching) in the docs explains lots of good background but lacks information about what exactly is exposed via `useFetch` and `useAsyncData` return. It is mentioned [on the respective pages of the composables](https://nuxt.com/docs/api/composables/use-fetch#return-values), but also here, it would be good to point out that `data`, `error` and `pending` are Vue `ref`s.

This was originally mentioned in https://github.com/nuxt/website-v2/issues/2024.

**Comment by akintoluvic** [comment]
Just for confirmation and clarity, the return values from `useFetch` and `useAsyncData` are of two types;

1. `data`, `pending`, `status` and `error` are refs
2. `refresh` and `execute` are composables

Also, it would be nice if the [data fetching guide](https://nuxt.com/docs/getting-started/data-fetching) simply links to the respective return values of `useFetch` and `useAsyncData` on their pages. This will prevent duplication of information and having to update in several places if need be.
@manniL @danielroe

**Comment by manniL** [comment]
Almost!

`refresh` and `execute` (actually being the same) are plain functions ☺️
