### ISSUE TITLE
NuxtLink internal hash behavior

### ISSUE THREAD

**Issue by damienroche** [nuxt/nuxt#24415]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.9.0`
- Nuxt Version:     `3.8.0`
- CLI Version:      `3.9.1`
- Nitro Version:    `2.7.2`
- Package Manager:  `pnpm@8.10.5`
- Builder:          `-`
- User Config:      `css`, `vite`, `devtools`, `modules`, `runtimeConfig`, `algolia`, `stripe`, `experimental`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-rc.5`, `@nuxtjs/tailwindcss@6.8.1`, `@vueuse/nuxt@10.5.0`, `@unlok-co/nuxt-stripe@2.0.0`, `@pinia/nuxt@0.5.1`, `@nuxt/content@2.9.0`, `@nuxt/image@1.0.0`, `nuxt-vitest@0.11.3`, `@nuxtjs/algolia@1.10.1`, `@vee-validate/nuxt@4.11.8`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-3-g8ospn?file=pages%2Findex.vue

### Describe the bug

I'm trying to use the power of target selector in css to show/hide a cart component.
For this I need to send the user to an url with a hash of the component id. 
When I use the `NuxtLink` component with the value `to="#cart"` the url is updated but the component is not displayed. If I then use the external property, the component is displayed.
Vice versa, to hide the component I have to use the same property which results in reloading the page.

**Comment by manniL** [comment]
This seems to be an issue when using plain Vue + Vue-Router already. Raised it there via https://github.com/vuejs/router/issues/2076
