### ISSUE TITLE
nuxt2: update `hable` to `hookable`

### ISSUE THREAD

**Issue by AndreyYolkin** [nuxt/nuxt#24419]
### Describe the feature

This issue covers 3 packages: nuxt, [nuxi](https://github.com/nuxt/cli/blob/f113a083f000d19c9ae7f35ae2534ac5c0dba77b/src/utils/dev.ts#L233) and @nuxt/bridge

While digging inside outdated internals I've found out, that Nuxt Bridge relies on `hookable` package for types, but Nuxt 2 uses `hable`, which is the same package, but with old name and outdated versions. `hable` package doesn't even support removing hooks, which breaks hooks system in bridge with nitro.

For example, I write this code in a module:

```ts
nuxt.callHook('restart')
```

then I get
![image](https://github.com/nuxt/nuxt/assets/11289484/aa5428ef-8937-4906-895e-1c0998e2b02d)

nuxi expects from hookable to return self-removing function, which only exists from v4 (hable is v3). @nuxt/bridge uses v5 as types reference, which is not entirely true.

With updating hookable in nuxt 2 to v4 (not 5, because it will break the usage with ie11, see https://github.com/unjs/hookable#migration) and also downgrading types in @nuxt/bridge to the same version we can solve this issue/proposal

### Additional information

- [x] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by pi0** [comment]
Can you please try `pnpm why hable` or `yarn why hable` and show output which packages depend on it?

**Comment by AndreyYolkin** [comment]
https://github.com/nuxt/nuxt/blob/2.x/packages/cli/package.json
https://github.com/nuxt/nuxt/blob/2.x/packages/core/package.json

<img width="1243" alt="image" src="https://github.com/nuxt/nuxt/assets/11289484/1071befd-0481-4f5b-a7ae-d6db74285122">

**Comment by pi0** [comment]
Feel free to make a PR to 2.x branch to try for migration 👍🏼
