### ISSUE TITLE
v0.6.6 is problems with uppercase alias names

### ISSUE THREAD

**Issue by toniengelhardt** [nuxt/nuxt#24420]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.8.2`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.0`
- Package Manager:  `pnpm@8.10.5`
- Builder:          `-`
- User Config:      `runtimeConfig`, `site`, `modules`, `experimental`, `sourcemap`, `devtools`, `app`, `typescript`, `vite`, `nitro`, `css`, `postcss`, `image`, `content`, `colorMode`, `plausible`, `sitemap`, `ogImage`
- Runtime Modules:  `@nuxt/content@2.9.0`, `@nuxt/image@1.1.0`, `@nuxtjs/color-mode@3.3.2`, `@nuxtjs/plausible@0.2.3`, `@nuxtseo/module@2.0.0-beta.45`, `@unocss/nuxt@0.57.7`, `@vueuse/nuxt@10.6.1`, `nuxt-icon@0.6.6`, `nuxt-vitest@0.11.5`
- Build Modules:    `-`

### Reproduction

See description.

### Describe the bug

In `v0.6.5` this works:

```ts
nuxtIcon: {
  aliases: {
    'aws': 'IconAWS',
    // ...
  }
}
```

if there is a component in global named `IconAWS.vue`, but in `v0.6.6` it breaks. The reason is the uppercase naming, if I rename the component and the alias to `IconAws.vue` it works.

**Comment by manniL** [comment]
I suppose you want to raise that straight away in https://github.com/nuxt-modules/icon 😋

**Comment by toniengelhardt** [comment]
@manniL 🙈 sorry, it's been a long day lol. Thought I was in the `nuxt-icon` repo, will move.
