### ISSUE TITLE
Docs: Add new H3 body/query validation

### ISSUE THREAD

**Issue by MickL** [nuxt/nuxt#24429]
### Describe the feature

H3 now provides integrated functions to validate query and body of a server handler function. It would be great if this would be added to the Nuxt docs. For example I only found out about this randomly by googling "Nuxt Zod".

Blog entry H3: https://unjs.io/blog/2023-08-15-h3-towards-the-edge-of-the-web#runtime-type-safe-request-utils

The following example could possibly be added to the docs:
- `readValidatedBody()` with a `Zod` schema using `.safeParse()` and throwing an error with Nuxt  `createError()` when `result.success` is `false`
- `getValidatedQuery()` with a `Zod` schema that uses `.coerce` to automatically cast a string to number
- `readValidatedBody()` with a custom validate function

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by DamianGlowala** [comment]
I'd also add a recently added [getValidatedRouterParams](https://github.com/unjs/h3/pull/573) util to the above list :)

**Comment by ceodevforce** [comment]
Have you already started to write this in the doc @MickL?

**Comment by MickL** [comment]
I didnt have the time

**Comment by MickL** [comment]
Also there should be added documentation (also to Nuxt docs) how to get multiform files. Because I trief around with Multer and Formidable for a long time until I randomly realized I can do it with H3 already in just a few seconds and there is no need for Multer or Formidable :)
