### ISSUE TITLE
can i define util name start with $ in /utils ？

### ISSUE THREAD

**Issue by zjf710** [nuxt/nuxt#24422]
### Environment

- Operating System: Darwin
- Node Version:     v18.15.0
- Nuxt Version:     -
- CLI Version:      3.10.0
- Nitro Version:    -
- Package Manager:  unknown
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

<img width="272" alt="image" src="https://github.com/nuxt/nuxt/assets/18107501/ae7f5a62-3863-4467-9558-e305710fa429">

<img width="253" alt="image" src="https://github.com/nuxt/nuxt/assets/18107501/84b1f158-9d67-422d-9cff-7b83811c7d6d">

<img width="699" alt="image" src="https://github.com/nuxt/nuxt/assets/18107501/2ac17739-4f4b-468c-abb0-6ed0af355deb">

### Describe the bug

util name start with $，when use in template can not find the util

**Comment by manniL** [comment]
Added a reproduction myself this time ☺️ https://stackblitz.com/edit/nuxt-issues-24422?file=utils%2Fcode.ts,app.vue

Please provide a runnable one next time 🙏

**Comment by manniL** [comment]
Resolved in unimport (see linked issue)
