### ISSUE TITLE
ISR Image hydration bug(?)

### ISSUE THREAD

**Issue by sptBlack** [nuxt/nuxt#24428]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.18.2
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  npm@9.8.1
- Builder:          -
- User Config:      devtools, ssr, alias, build, ui, imports, tailwindcss, modules, viewport, routeRules
- Runtime Modules:  @nuxt/ui@2.10.0, @nuxt/image@1.0.0, nuxt-viewport@2.0.6, nuxt-rating@0.0.15
- Build Modules:    -

### Reproduction

Using "ISR" build the website with nuxt build and deploy it, change any image tag's src on like an admin page or inside DB manually (as an example from image1.png -> image2.png). Refresh the page and should be no hydration occuring.

### Describe the bug

Unsure if it's intended or bug but worth the mention. Basically I deploy a site with products that are got images they are fetched from server. If I change product's name hydration occurs and 1-2 seconds later it will change so it works as intended however with image whenever I try to change the hydration only occurs if I rebuild the site or ISR recaching itself.

### Additional context

Im using Meteor.js for backend with MongoDB.
EDIT: I've tried both with NuxtImg and without NuxtImg using "img"

**Comment by sptBlack** [comment]
I did more research in my problem even tried to made a sandbox reproduction to give you but with using "fetch" it worked perfectly but using Meteor's websocket calls doesnt work even for a simple string return. I'm trying to make a reproduction for Meteor.js specifically in sandbox and see what happens

**Comment by madebyfabian** [comment]
@sptBlack Do you still experience this issue?

**Comment by sptBlack** [comment]
@madebyfabian Ill check once home (most likely tomorrow)
