### ISSUE TITLE
Nuxt doesn't allow auto import types from modules

### ISSUE THREAD

**Issue by userquin** [nuxt/nuxt#24439]
### Environment

```shell
------------------------------                                                                                                                                 
- Operating System: Windows_NT
- Node Version:     v20.9.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  pnpm@8.10.5
- Builder:          -
- User Config:      devtools, modules, vuetify, experimental
- Runtime Modules:  @unocss/nuxt@0.57.7, ~/layer-modules/another-vuetify, vuetify-nuxt-module@0.6.7
- Build Modules:    -
------------------------------
```

### Reproduction

https://github.com/userquin/vuetify-nuxt-module-types-check

### Describe the bug

Cannot use module hooks if we don't register the module in modules manually.

To reproduce the error, remove `~/modules/vuetify.ts`, run `pnpm nuxt prepare` and restart the window in VSCode or the Vue Language Server in JetBrains IDE and go to the module.

Running `vue-tsc --noEmit` works, why? :thinking: . Thx @BobbieGoede , `vue-tsc`  using `tsconfig.json` not `tsconfig.server.json`

### Additional context

When auto importing modules, the folder is excluded in the `tsconfig.json` file, and so using any module hook will not resolve the hook.

On left, registering the module in the modules, on right no:
![imagen](https://github.com/nuxt/nuxt/assets/6311119/fd1613a1-d931-44fa-b35a-929cc7be7591)

Check the following video (also in linked reproduction):
https://streamable.com/5qdx8g

### Logs

NA: check screenshot and the video

**Comment by BobbieGoede** [comment]
It seems like the root directories of auto registered modules are being added to the exclude/include arrays in `tsconfig.json`. 

So adding modules in the `modules` directory will add `../modules` in the exclude array, and adding `my-module/index.ts` would add `../modules/my-module` to the exclude array. (as well as those same entries but ending with `/runtime` or `/runtime/server`)

When modules are registered via the `modules` array in the nuxt config only entries ending with `/runtime` or `/runtime/server` will be added to `tsconfig.json`/`tsconfig.server.json` include/exclude arrays. 

I found a hacky workaround which probably breaks things, but seems to resolve the type issues, and may point to the source of the issue. Workaround is adding the following as the last module in the `modules` array:
```ts
(options, nuxt) => {
 nuxt.options.modulesDir = nuxt.options.modulesDir.filter(x => !x.startsWith(nuxt.options.srcDir + '/modules'))
}
```

Will look into it further tomorrow

**Comment by BobbieGoede** [comment]
I believe this issue was introduced by these changes https://github.com/nuxt/nuxt/commit/b5c9a81d68f0511239dd26f040c6b2926441adce#diff-84e752bfeb5965269318fc84ddc24d24fa76cdca52fcc7d4e61f9ea5e7efae21R28-R31
