### ISSUE TITLE
Auto-imports in  webworker bundle not work

### ISSUE THREAD

**Issue by kingyang** [nuxt/nuxt#24443]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.9.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  pnpm@8.3.1
- Builder:          -
- User Config:      alias, app, components, devtools, experimental, modules, nitro, runtimeConfig, session, sourcemap, typescript, vite, vue
- Runtime Modules:  @unocss/nuxt@0.57.7, @vueuse/nuxt@10.6.1
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-6zhzee?file=services%2Fdemo%2Fworker.ts,pages%2Findex.vue

### Describe the bug

In the webworker file, the referenced Auto-imports function will not be packaged, and will appear "Uncaught (in promise) ReferenceError: log is not defined
    at globalThis.onmessage (worker-6dbb1795.js:1:255)
"

### Additional context

step:
1. pnpm build
2. node .output/...
3. see browser devtools console

**Comment by manniL** [comment]
Missed that issue. We can consolidate in #24590
