### ISSUE TITLE
Wrong type import when using addServerImportsDir in module

### ISSUE THREAD

**Issue by kiki-kanri** [nuxt/nuxt#24445]
### Environment

- Operating System: Linux
- Node Version:     v20.9.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  pnpm@8.10.5
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-k32tbj-5xnldv

### Describe the bug

I use the tool `addServerImportsDir` to export my custom utils in a module I made myself, but when I install and use it, the type of the exported functions is any.

Referring to the example above, the `clearH3EventContextSession` method in the `server/api/index.ts` file is of type any.

Looking at `.nuxt/types/nitro-imports.d.ts`, I see that the path file for the method has .mjs after it.

![image](https://github.com/nuxt/nuxt/assets/83924639/94fb03f8-4492-4ce7-9c0e-9d91f66ef2b9)

However, all other auto-importing does not have an extension, and this problem does not occur if you use `addImportsDir` or `addServerImports`.

**Comment by productdevbook** [comment]
@danielroe https://github.com/unjs/unimport/pull/303 i send unimport pr.
