### ISSUE TITLE
Can we add a rootClass

### ISSUE THREAD

**Issue by 63490794** [nuxt/nuxt#24448]
### Describe the feature

Can we add a rootClass

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by huang-julien** [comment]
Hello you can change the rootId within the nuxt config https://nuxt.com/docs/api/nuxt-config#rootid

**Comment by 63490794** [comment]
https://github.com/nuxt/nuxt/discussions/24447
