### ISSUE TITLE
getQuery is not defined in the middleware

### ISSUE THREAD

**Issue by chenx130** [nuxt/nuxt#24458]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.9.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  npm@10.1.0
- Builder:          -
- User Config:      devtools, modules, nitro, unocss, runtimeConfig, elementPlus, experimental
- Runtime Modules:  @unocss/nuxt@0.57.7, @element-plus/nuxt@1.0.7
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-d2ffav?file=pages%2Findex.vue

### Describe the bug

getQuery is not defined in the middleware, but if there is a statement that imports getQuery, even if it has been commented, like: 
`// import { getQuery } from 'h3'; `
it will work.

![截屏2023-11-25 18 40 41](https://github.com/nuxt/nuxt/assets/107945468/4f9f9820-6bac-451f-a7ac-a2c495d51aa8)
![截屏2023-11-25 18 40 58](https://github.com/nuxt/nuxt/assets/107945468/0f5cad3b-5e83-45b3-a188-c10961bf26f4)

**Comment by manniL** [comment]
It is intended that the Nitro/H3 utilities are *not* auto-imported in the "Nuxt-part" of your application.

In a middleware, I'd rather use the `from` attribute and check the query like this:

```vue
<template>
  <div></div>
</template>

<script setup>
definePageMeta({
  middleware: [
    function (from, to) {
      console.log(from.query);
    },
  ],
});
</script>
```
