### ISSUE TITLE
Nuxt Kit import causing `crypto.getHashes is not implemented yet` on nodeless environments

### ISSUE THREAD

**Issue by brendonmatos** [nuxt/nuxt#24466]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.9.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  pnpm@8.10.2
- Builder:          -
- User Config:      extends, app, devtools, modules, quasar, telemetry, nitro, security, vue, build, runtimeConfig
- Runtime Modules:  nuxt-quasar-ui@2.0.6, nuxt-auth-utils@0.0.8
- Build Modules:    -
------------------------------

### Reproduction

1. Create a base project 

2. start using `useLogger` from `nuxt/kit`. In my case I was importing on a `/server/api/hello.ts`:

```ts
const ctx = { 
  logger: useLogger('nuxt-trpc/server')
}
```

The bug was evident when I where deploying to cloudflare-pages (unenv/nodeless env)

2. `NITRO_PRESET=cloudflare-pages nuxi build`

3. `npx wrangler pages dev dist/`

### Describe the bug

At first hand, I thought this was related to nuxt-security (https://github.com/Hebilicious/authjs-nuxt/issues/132#issue-1981095433) but the error persisted even removed entirely from the project. 

Building without minifying, I noticed that the unjs/jiti was being initialized inside my server chunk, like this: 

```js
jiti(process$2.cwd(), { interopDefault: true, esmResolve: true });
```

Later I would find out that is related to this line on nuxt/kit:
https://github.com/nuxt/nuxt/blob/e3f349f61274d85889c2292d425ec0a68bb8e5ab/packages/kit/src/internal/cjs.ts#L7

But this jiti initialization ends up being the error because at some point calls the object-hash lib and then calls crypto.getHash.

### Additional context

I managed to work by patching my local nuxt/kit module with

```diff
-const _require = jiti(process.cwd(), { interopDefault: true, esmResolve: true });
+const _require = new Proxy(function () { }, {
+  get(target, key) {
+    this.jiti = this.jiti || jiti(process.cwd(), { interopDefault: true, esmResolve: true });
+    return this.jiti[key]
+  },
+  apply(target, thisArg, argumentsList) {
+    this.jiti = this.jiti || jiti(process.cwd(), { interopDefault: true, esmResolve: true });
+    return this.jiti(...argumentsList)
+  }
+})
```

### Logs

```shell-script
(file:.//Users/brendonferreira/Projects/todo/.wrangler/tmp/dev-GwQzSi/70eaj8rffan.js:37395:5)
  [nuxt] [request error] [unhandled] [500] [unenv] crypto.getHashes is not implemented yet!
    at createNotImplementedError2
  (file:.//Users/brendonferreira/Projects/todo/.wrangler/tmp/dev-GwQzSi/70eaj8rffan.js:1141:11)
    at Object.fn3 [as getHashes]
  (file:.//Users/brendonferreira/Projects/todo/.wrangler/tmp/dev-GwQzSi/70eaj8rffan.js:1145:13)
    at ./node_modules/.pnpm/object-hash@3.0.0/node_modules/object-hash/index.js
  (file:.//Users/brendonferreira/Projects/todo/.wrangler/tmp/dev-GwQzSi/70eaj8rffan.js:3214:50)
    at __webpack_require__
  (file:.//Users/brendonferreira/Projects/todo/.wrangler/tmp/dev-GwQzSi/70eaj8rffan.js:4303:45)
    at
  file:.//Users/brendonferreira/Projects/todo/.wrangler/tmp/dev-GwQzSi/70eaj8rffan.js:4447:127
    at
  file:.//Users/brendonferreira/Projects/todo/.wrangler/tmp/dev-GwQzSi/70eaj8rffan.js:7352:9
    at
  file:.//Users/brendonferreira/Projects/todo/.wrangler/tmp/dev-GwQzSi/70eaj8rffan.js:7353:7
    at requireJiti
  (file:.//Users/brendonferreira/Projects/todo/.wrangler/tmp/dev-GwQzSi/70eaj8rffan.js:7354:5)
    at lib
  (file:.//Users/brendonferreira/Projects/todo/.wrangler/tmp/dev-GwQzSi/70eaj8rffan.js:37228:21)
    at .wrangler/tmp/pages-8pyQy0/chunks/_trpc_.mjs
  (file:.//Users/brendonferreira/Projects/todo/.wrangler/tmp/dev-GwQzSi/70eaj8rffan.js:37395:5)
```

**Comment by brendonmatos** [comment]
unjs/jiti was supposed to work in the edge?

**Comment by danielroe** [comment]
`useLogger` (and indeed `@nuxt/kit`) is not meant to be used in non-Node environments - and definitely not in your built application. Instead, you should import from `consola` directly.
