### ISSUE TITLE
definePageMeta does not set layout If app/router.options.ts is used

### ISSUE THREAD

**Issue by cbrgpl** [nuxt/nuxt#24472]
### Environment

- Operating System: Linux
- Node Version:     v21.2.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, typescript, css, build, imports, runtimeConfig, vite, alias, modules
- Runtime Modules:  (), @pinia/nuxt@0.4.11
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-l2ydly?file=modules%2Fauth%2Fviews%2FMainAuth.vue

### Describe the bug

When I use **router.options.ts** Instead of **pages/**, definePageMeta does not change the layout. It always loads default layouts.

### Additional context

In my local project I tried to use pages instead of router.options.ts and then definePageMeta started work.

**Comment by danielroe** [comment]
Yes, you are overriding the default metadata with `app/router.options.ts`. However, you can _respect_ it if you want; the `routes()` function receives as its first argument the routes that Nuxt has received (including metadata) and you can do with this what you wish.

**Comment by 4designing** [comment]
in your routes in the file **router.options.ts** you gonna add layout inside meta like following:
`import type { RouterConfig } from '@nuxt/schema'
export default <RouterConfig>{
  // https://router.vuejs.org/api/interfaces/routeroptions.html#routes
  routes: (_routes) => [
  {
      path: '/myPath',
      component: () => import('@/pages/MyPage.vue'),
      meta: {
        layout: 'customLayoutName'
      },
    },
   ],
}
`

**Comment by 4designing** [comment]
**This works for me **
in your routes in the file **router.options.ts** you gonna add layout inside meta like following:
```
import type { RouterConfig } from '@nuxt/schema'
export default <RouterConfig>{
  // https://router.vuejs.org/api/interfaces/routeroptions.html#routes
  routes: (_routes) => [
  {
      path: '/myPath',
      component: () => import('@/pages/MyPage.vue'),
      meta: {
        layout: 'customLayoutName'
      },
    },
   ],
}
```
