### ISSUE TITLE
node_modules component in nuxt modules : I still get SSR related errors despite `mode:client`

### ISSUE THREAD

**Issue by Tumulte** [nuxt/nuxt#24478]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-4byrfr?file=modules%2Fcode-block.ts,app.vue

### Describe the bug

I have installed a vue component from NPM and created a nuxt module for it:

```javascript
import { defineNuxtModule, addComponent } from '@nuxt/kit'

export default defineNuxtModule({
    setup() {
        addComponent({
            name: 'VCodeBlock',
            export: 'VCodeBlock',
            filePath: '@wdns/vue-code-block',
            mode: "client",
        })
    },
})
```

However, despite `mode: "client"` whenever I put it in a nuxt page, layout or component I still get an ssr related issue

```
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Component <Anonymous> is missing template or render function.
```
I also have the same error if I just import the component without using nuxt modules 
If I completely disable SSR, it works fine. 

If I remove mode client, it's worse : it says window is undefined

I would assume the problem is that the module is client side... but the component  use it in isn't, therefore it's rendered before it should. 

It does feel like a bug however because you'd assume mode client would work. What does `mode:client` do exactly ? 

### Logs

```shell-script
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Component <Anonymous> is missing template or render function.
```

**Comment by danielroe** [comment]
Try updating it like this:

```diff
  import { defineNuxtModule, addComponent } from '@nuxt/kit';
  
  export default defineNuxtModule({
    setup() {
      addComponent({
        name: 'VCodeBlock',
-       export: 'VCodeBlock',
        filePath: '@wdns/vue-code-block',
        mode: 'client',
      });
    },
  });
```

It seems like the issue is to do with importing that named export from your component (likely because it's 'fake' ESM and has both a default and a named export).
