### ISSUE TITLE
Hydration children mismatch in <div>: server rendered element contains more child nodes than client vdom.

### ISSUE THREAD

**Issue by Ice-Hazymoon** [nuxt/nuxt#24479]
### Environment

fatal: not a git repository (or any of the parent directories): .git
Working directory: E:/Project/                                                                                21:13:28
Nuxt project info:                                                                                                               21:13:28

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.14.1
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  pnpm@8.9.2
- Builder:          -
- User Config:      devtools, postcss, vite, ssr, experimental, sourcemap, typescript, devServer, css, modules, runtimeConfig, imports, app, hooks, googleFonts
- Runtime Modules:  @pinia/nuxt@0.5.1, @pinia-plugin-persistedstate/nuxt@1.2.0, @nuxtjs/google-fonts@3.1.0
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-bydy2i

### Describe the bug

```
<template>
  <input type="email" placeholder="Please enter your email" />
</template>
```
![image](https://github.com/nuxt/nuxt/assets/25239977/1990fbe3-c5b5-49e7-b55f-ffaf4da9150e)

```
<template>
  <input type="email" placeholder="Please enter your emmmail" />
</template>
```
![image](https://github.com/nuxt/nuxt/assets/25239977/ea05d26b-4c04-4be5-97ea-d717893723e5)

WTF???

**Comment by warflash** [comment]
Looks like the reproduction you provided does work fine, not getting a hydration error 🤔

**Comment by Ice-Hazymoon** [comment]
> Looks like the reproduction you provided does work fine, not getting a hydration error 🤔

Well, the problem was caused by [LastPass](https://www.lastpass.com/), and after I disabled it the warning no longer appeared.
