### ISSUE TITLE
`:class` reactive binding is not updated on the client side

### ISSUE THREAD

**Issue by imrim12** [nuxt/nuxt#24474]
### Environment

Nuxt project info: 

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Stackblitz: https://stackblitz.com/edit/nuxt-starter-b2yda2?file=app.vue

### Describe the bug

The template is updated as `Mobile` but not the `:class` is not updated to `flex-col`
![image](https://github.com/nuxt/nuxt/assets/46400321/8da7563e-7c81-47ba-ac88-bca269d4c95d)
![image](https://github.com/nuxt/nuxt/assets/46400321/ee6f8eff-2e5c-4081-9afb-7aeec5c9d026)

### Additional context

This happens when we update the reactive value from the client side (simply check for `window`)
This will work
![image](https://github.com/nuxt/nuxt/assets/46400321/707af968-10a2-4669-afc3-61e7fe24cab4)

This won't work
![image](https://github.com/nuxt/nuxt/assets/46400321/72782cf6-6b9a-4b4e-ad46-e33c488c31fa)

### Logs

```shell-script
No logs
```

**Comment by lxccc812** [comment]
Refer to the answer here #24326

**Comment by warflash** [comment]
Make sure to always check you dev console for errors and warnings. In your case you're getting a hydration mismatch since the isClient flag differs between client and server.
Here's an updated version: https://stackblitz.com/edit/nuxt-starter-qcxtwc?file=app.vue

**Comment by EricLeaoF** [comment]
I had this same problem and that solved! Thanks

> I had to do this to update it lol The thing is the html template is updated properly, but the `:class` binding does not change
> 
> ```
> :key="forceRerenderFlag"
> ////
> const forceRerenderFlag = ref(1)
> onMounted(() => {
>   forceRerenderFlag.value++
> })
> ```
