### ISSUE TITLE
islands: nested components styles are not send with the server component

### ISSUE THREAD

**Issue by huang-julien** [nuxt/nuxt#24480]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.17.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/huang-julien/julien-huang.dev/blob/main/components/ProjectCard.vue
https://github.com/huang-julien/julien-huang.dev/blob/main/components/ProjectsList.server.vue

`ProjectsList.server.vue` has a workaround which is to copy the styles of `ProjectCard`. Remove all styles from ProjectsList to reproduce the issue

### Describe the bug

It seems that components called within a server component does not get their styles send with the island response.

**Comment by danielroe** [comment]
resolved in https://github.com/nuxt/nuxt/pull/25455
