### ISSUE TITLE
`manifest.json` becomes a folder with `index.html` instead of a JSON file

### ISSUE THREAD

**Issue by nickdnk** [nuxt/nuxt#24487]
### Environment

- Operating System: Darwin
- Node Version:     v18.18.2
- Nuxt Version:     3.8.1
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      app, sourcemap, spaLoadingTemplate, ssr, devtools, devServer, nitro, modules, plugins, build, vite, pinia, runtimeConfig
- Runtime Modules:  <redacted>
- Build Modules:    -

### Reproduction

Put `manifest.json` in your `public` folder, run `nuxt generate` on version 3.8.1 or 3.8.2. Instead of `.output/public/manifest.json` you'll have `.output/public/manifest.json/index.html`.

Downgrading to 3.8.0 and changing nothing else in the project fixes the problem.

### Describe the bug

`manifest.json` inside `public` becomes a folder in `.output/public` with an `index.html` file in it instead of the expected JSON file.

### Logs
```
ℹ ✓ built in 12.07s
✔ Client built in 12086ms
ℹ Building server...
ℹ vite v4.5.0 building SSR bundle for production...
ℹ ✓ 1 modules transformed.
Inspect report generated at <redacted>
ℹ .nuxt/dist/server/styles.mjs  0.07 kB
ℹ .nuxt/dist/server/server.mjs  0.10 kB │ map: 0.22 kB
ℹ ✓ built in 346ms
✔ Server built in 352ms
ℹ Initializing prerenderer
ℹ Prerendering 4 initial routes with crawler
  ├─ /200.html (15ms)
  ├─ / (15ms)
  ├─ /index.html (14ms)
  ├─ /404.html (15ms)
  ├─ /manifest.json (1ms)  // I'm guessing this is the issue. Edit: No, this still prints on 3.8.0, but it works then.
✔ Generated public .output/public
✔ You can preview this build using npx serve .output/public
```

**Comment by pi0** [comment]
Are you using any custom config by any chance? Tried on a minimal nuxt app (Nuxt 3.8.2 with Nitro 2.8.0) and `.output/public` is as expected:

<img width="321" alt="image" src="https://github.com/nuxt/nuxt/assets/5158436/fa7a2638-f403-4ead-b593-bf32bb1f5924">

https://stackblitz.com/edit/nuxt-starter-p8dqvx?file=public%2Fmanifest.json,package.json

**Comment by nickdnk** [comment]
Tried with `nuxt upgrade --force` to 3.8.2. It does the same thing.

I wouldn't know what custom config you refer to. I'm assuming there's *something*, or you would be able to reproduce it, but the fact that I can change nothing at all except to downgrade to 3.8.0 to fix it indicates that it's not just my project misbehaving.

The string `manifest.json` appears nowhere in my project except where you'd expect it to; in compiled `index.html` and as `{ rel: 'manifest', href: '/manifest.json' }` in the `link`section of `nuxt.config.ts`.

<img width="407" alt="Screenshot 2023-11-28 at 03 59 40" src="https://github.com/nuxt/nuxt/assets/8411314/6d381ef8-cdd5-4e6c-857f-326b6cecce4b">

<img width="868" alt="Screenshot 2023-11-28 at 03 57 02" src="https://github.com/nuxt/nuxt/assets/8411314/d4044d40-eeaf-4fbd-86c7-901a3369e1da">

<img width="172" alt="Screenshot 2023-11-28 at 03 58 05" src="https://github.com/nuxt/nuxt/assets/8411314/73e6b9a7-78ee-486f-aad6-eb6ce5cd69c8">

**Comment by pi0** [comment]
It shouldn't happen but in order to fix the root cause, i need to reproduce same problematic output as you have. Do you after upgrading when trying `npx nuxi info` (or in CLI header) see Nitro `2.8` now? Also, what is under `nitro` config you have in `nuxt.config`?
