### ISSUE TITLE
getSSRProps vnode is null

### ISSUE THREAD

**Issue by 17630966776** [nuxt/nuxt#24492]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.18.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  npm@9.8.1
- Builder:          -
- User Config:      devtools, app, vite, css, modules, build, i18n, nitro
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.5, tdesign-vue-next/es/nuxt, @nuxtjs/device@3.1.1, ./modules/module
- Build Modules:    -
------------------------------

### Reproduction

expect vnode but got null

### Describe the bug

`export default defineNuxtPlugin(nuxtApp => {
	nuxtApp.vueApp.directive("aos", {
		getSSRProps(binding, vnode) {
			// 你可以在这里提供SSR特定的props
			console.log({ binding, vnode });
		},
	});
`});``

**Comment by danielroe** [comment]
This is Vue 3 SSR behaviour: https://stackblitz.com/edit/github-iswjxq?file=src/main.ts,src/App.vue.

Feel free to raise an issue in https://github.com/vuejs/core/issues/new. 🙏
