### ISSUE TITLE
Reactivity trigger useFetch in page, but not in component.

### ISSUE THREAD

**Issue by DavidDeSloovere** [nuxt/nuxt#24509]
### Environment

Working directory: /home/DavidDeSloovere/github-g5ho8q                                                                                    Nuxt project info:                                                                                                                        
------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools, modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.5
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/~/github.com/DavidDeSloovere/github-g5ho8q
I have added information in the code.

### Describe the bug

When changing language/locale:
Reactivity reruns useFetch for the index.vue page, 
but not for the same code in the child component.

### Additional context

Same issue with and without layout file.
I don't get why it works in one place, but not in the other.

**Comment by danielroe** [comment]
It's because your index page is being rerun (it's a navigation) but your component setup isn't.

That's because you are removing reactivity when you access `.value` in your setup function. Instead:

```diff
  const { data: dataWithQuery } = await useFetch('/api/hello?source=component', {
-   query: { locale: locale.value },
+   query: { locale: locale },
  });
```

**Comment by DavidDeSloovere** [comment]
Thanks Daniel. Spent hours on this.
As I understand, it has nothing to do with useFetch in itself, but pure reactivity and navigation.

I wasn't sure about this being a bug. But I couldn't understand it.
Reactivity in useFetch is documented, must have missed it, my bad.

Not sure if the notion about page navigation vs component is documented. 
_Should I add some documentation about this to this section? https://nuxt.com/docs/guide/directory-structure/pages#navigation_
