### ISSUE TITLE
CookieRef from useCookie inside a v-if prevents conditionally rendered component from updating the cookie it depends on

### ISSUE THREAD

**Issue by BrankoKrstic** [nuxt/nuxt#24501]
### Environment

- Operating System: Darwin
- Node Version:     v20.10.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

[Reproduction](https://stackblitz.com/edit/github-urvkyv?file=README.md)

### Describe the bug

When value from useCookie is used to conditionally render multiple components with v-if, only the last rendered component can update the cookie. Otherwise, the value gets updated, but is immediately reset.

**Comment by danielroe** [comment]
This should be resolved in the [nightly release](https://nuxt.com/docs/guide/going-further/nightly-release-channel#nightly-release-channel) via https://github.com/nuxt/nuxt/pull/24503, or in the next release.

Let me know if not and I'll reopen.
