### ISSUE TITLE
`setup` in `defineComponent` is not transformed to preserve context

### ISSUE THREAD

**Issue by RyanCasas** [nuxt/nuxt#24505]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.10.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  pnpm@8.10.5
- Builder:          -
- User Config:      devtools, ssr
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

GitHub repo: https://github.com/RyanCasas/nuxt-3-8-2-useRoute-issue
StackBlitz: https://stackblitz.com/~/github.com/RyanCasas/nuxt-3-8-2-useRoute-issue

To reproduce the issue, read the bug description, boot up the project, input any value on the text box and use either the form button or the `<NuxtLink />` component.

### Describe the bug

When trying to navigate to a route with parameters, if we try to `await` for anything in `setup()` before using the `useRoute()` composable, then the `route.params` are not properly set.

If you then try to read the route params within `mounted()` for instance, then the values are there as expected.

This only happens when trying to either programatically navigate to the route with `navigateTo` or using a `NuxtLink` component. Accessing directly to the URL, or refreshing once navigated makes everything work as expected.

### Additional context

It can be fixed by using the `useRoute()` composable before any `await`.

**Comment by danielroe** [comment]
The issue is that Vue manually sets/restores context when using `<script setup>` (as a compiler optimisation) but it doesn't do so for an object syntax export (https://github.com/RyanCasas/nuxt-3-8-2-useRoute-issue/pull/1):

```vue
<script setup lang="ts">
// This is just to test and it can be anything else really
await useFetch(`https://api.publicapis.org/entries`);

const route = useRoute();

const setupValue = route.params.dynamic

const mountedValue = ref(null)

const documentLocation = computed(() => document.location)

onMounted(() => {
  mountedValue.value = route.params.dynamic;
})
</script>
```

Previously we implemented a feature using `unctx` to do that for any `setup()` function wrapped in `defineComponent` but it looks like that isn't working right now even when added to `build.optimization.asyncTransforms.objectDefinitions`. That needs to be fixed. (But you would still need to wrap the export default object in `defineComponent`.)

**Comment by RyanCasas** [comment]
Hey @danielroe,

Thanks for taking the time to look into this issue, I appreciate it. As I mentioned on the original post, this can also be fixed by using the `useRoute()` composable before the `await`, no need to change from the Options API to Composition API.
But it seemed like a weird behaviour, so it might be worth looking into (maybe it affects something else that isn't as trivial to solve).
