### ISSUE TITLE
$fetch for self DNS

### ISSUE THREAD

**Issue by borodadada** [nuxt/nuxt#24500]
### Environment

  "devDependencies": {
    "nuxt": "3.8.2"
  },

### Reproduction

My server Ubuntu use DNS name, to create a request i use this name
Example: site.com
SSR request $fetch('https://site.com/api') <- stopped working
On ubuntu i try CURL - all work fine!

### Describe the bug

Now i replace $fetch on axios and all work fine!
I think it's your bug. Thx!

**Comment by borodadada** [comment]
ohh man.... i try

index page
```
<script setup>
//pre-load
const { data } = await useAsyncData('pre-data', () => Promise.all([
    teamspeak.getFullUserList(),
    teamspeak.getInfoForWeb()
]))
</script>
```

composables
```
    url(){
        const config = useRuntimeConfig()
        return config.public.server.url + '/teamspeak'
    },
    async getFullUserList(){
        const url = this.url() + '?target=api&action=getFullUserList'
        const res = await axios.get(url, { cache: false })
        if( res && res.data && res.data.status ){
            return res.data.data
        }else 
            return false
    },
    async getInfoForWeb(){
        const url = this.url() + '?target=api&action=getInfoForWeb'
        const res = await axios.get(url, { cache: false })
        if( res && res.data && res.data.status ){
            return res.data.data
        }else 
            return false
    },
```

this is work, if replace axios on $fetch = not working

```
    async getFullUserList(){
        const url = this.url() + '?target=api&action=getFullUserList'
        const res = await $fetch(url)
        if( res && res.status ){
            return res.data
        }else 
            return false
    },
```

**Comment by danielroe** [comment]
This is likely an issue with Node's native fetch implementation, which `$fetch` uses if you are on the latest Node version. Without a running reproduction it's difficult to say. Please feel free to provide one and I'll happily reopen 🙏
