### ISSUE TITLE
`useAsyncData` is not blocking the client navigation

### ISSUE THREAD

**Issue by pguilbert** [nuxt/nuxt#24542]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.18.2
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  npm@8.19.4
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/~/github.com/pguilbert/nuxt-await-tests

Navigation from "Home" to "noawait-default" should be identical to the one from "Home" to "await-default" (but twice faster because of the parallelization). Without `{lazy: true}` "Loading..." should not be shown to the user.

### Describe the bug

The documentation states the following:
> By default, data fetching composables will wait for the resolution of their asynchronous function before navigating to a new page by using Vue’s Suspense. This feature can be ignored on client-side navigation with the lazy option. In that case, you will have to manually handle loading state using the pending value. (https://nuxt.com/docs/getting-started/data-fetching#useasyncdata ) 

It appears that this is not the case when `useAsyncData` is not awaited.  Currently, my understanding is that: 
```ts
const asyncData = useAsyncData(
  () => ...
);
```

is equivalent to 
```ts
const asyncData = useAsyncData(
  () => ...,
  { lazy: true}
);
```

Thank you for your help 🙏

**Comment by manniL** [comment]
You could use `await` + `Promise.all`:

```ts
const asyncDataPromise = useAsyncData(
  () =>
    new Promise((resolve) => {
      setTimeout(() => resolve("data"), 4000);
    })
);

const asyncData1Promise = useAsyncData(
  () =>
    new Promise((resolve) => {
      setTimeout(() => resolve("data"), 4000);
    })
);

const [asyncData, asyncData1] = await Promise.all([asyncDataPromise, asyncData1Promise])
```

**Comment by pguilbert** [comment]
Hello @manniL thank you for taking the time! 

Sorry for insisting, but could you clarify the purpose of `useLazyAsyncData` or the `lazy` option if this isn't a bug?

I thought Nuxt was performing the same actions on the client as it does on the server. Meaning that asyncData promises were awaited by the framework.
