### ISSUE TITLE
Nuxt/Storyblok - When clicking quickly on NuxtLink multiple times, i get error Cannot read properties of null (reading 'parentNode')

### ISSUE THREAD

**Issue by webmaster-dexontechnology** [nuxt/nuxt#24549]
### Environment

Node: v18.18.2
OS: Windows 10
Nuxt: 3.0.0, 3.6.3, 3.7.1, 3.8.0, 3.8.2
@storyblok/nuxt: 5.0.2,  5.7.4, 5.7.7, 5.7.9
Browser: Google Chrome

### Reproduction

https://github.com/webmaster-dexontechnology/my-problem/tree/master
https://stackblitz.com/edit/nuxt-3-sdk-demo-fgf4wa?file=app.vue

### Describe the bug

When clicking quickly on NuxtLink multiple times, I receive the following error (this error occurs only on pages with Storyblok).
I have tried to downgrade the version of Nuxt and Storyblok and fix other issues, but my problem has not been resolved.

TypeError: Cannot read properties of null (reading 'parentNode')
TypeError: Cannot read properties of null (reading 'subTree')

![bugubgubugbg](https://github.com/nuxt/nuxt/assets/134662978/732a8477-8e9b-4d24-918f-9063881bdcdc)

https://github.com/nuxt/nuxt/assets/134662978/0263cbd2-0518-4d24-b547-c0ced29536c1

**Comment by huang-julien** [comment]
Hi :wave: this is an upstream issue. Let's track it in #22900
