### ISSUE TITLE
issues output pathname in `~/error.vue`

### ISSUE THREAD

**Issue by WickyNilliams** [nuxt/nuxt#24543]
### Environment

```
Working directory: /home/projects/nuxt-starter-y5gman
Nuxt project info:

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Reproduction

https://stackblitz.com/edit/nuxt-pathname-error-page?file=pages%2Findex.vue

### Describe the bug

I'd like to output the pathname in the case of a 404 being handled by `error.vue`. For example a message like:

```vue
Could not find the page {{ location.pathname }}
```

However, it seems that the pathname is always behind, since the error page begins rendering before the browser's url is updated. There's a similar, but different issue with `$route.fullPath`.

In cases where the route simply does not exist, `location.pathname` gives the correct value, but `$route.fullPath` gives the url for the previous page.

In cases where the navigation fails due to route validation, neither are correct - they both show the previous url.

**Comment by KellsWorks** [comment]
You can try to explore useError composable: (property) error: Error | {
    url: string;
    statusCode: number;
    statusMessage: string;
    message: string;
    description: string;
    data?: any;
} | null | undefined

**Comment by WickyNilliams** [comment]
That does not help unfortunately. `~/error.vue` receives an `error` prop. And that object is the same as returned from `useError`:

```vue
// ~/error.vue
<script>
defineProps<{ error: any }>()
const e = useError()
</script>
<template>
  {{ error === e }}
</template>
```

In all cases the type is an `Error` and not the object with a `url` property

**Comment by manniL** [comment]
> In cases where the route simply does not exist, location.pathname gives the correct value, but $route.fullPath gives the url for the previous page.

I assume because the error happened before the router could resolve the URL but after site navigation. Thus the mismatch

> In cases where the navigation fails due to route validation, neither are correct - they both show the previous url.

Here, the error happens even before navigation kicks in. The user "technically" doesn't leave the current page.

**Comment by WickyNilliams** [comment]
thanks! appreciate the quick fix. look forward to it landing :)

**Comment by manniL** [comment]
You are welcome @WickyNilliams! Feel free to try it out on the [nightly channel](https://nuxt.com/docs/guide/going-further/nightly-release-channel) already 😋
