### ISSUE TITLE
[Feature Request] File-based routing support for vue-router named views

### ISSUE THREAD

**Issue by JMaylor** [nuxt/nuxt#24541]
### Describe the feature

In [`vue-router`](https://router.vuejs.org) there is a concept of [Named Views](https://router.vuejs.org/guide/essentials/named-views.html#Named-Views). To copy part of the docs as it explains it best:

> Sometimes you need to display multiple views at the same time instead of nesting them, e.g. creating a layout with a sidebar view and a main view. This is where named views come in handy. Instead of having one single outlet in your view, you can have multiple and give each of them a name. A router-view without a name will be given default as its name.
> ```vue
> <router-view class="view left-sidebar" name="LeftSidebar"></router-view>
> <router-view class="view main-content"></router-view>
> <router-view class="view right-sidebar" name="RightSidebar"></router-view>
> ```
> A view is rendered by using a component, therefore multiple views require multiple components for the same route. Make sure to use the components (with an s) option:
> ```ts
> const router = createRouter({
>  history: createWebHashHistory(),
>  routes: [
>    {
>      path: '/',
>      components: {
>        default: Home,
>        // short for LeftSidebar: LeftSidebar
>        LeftSidebar,
>        // they match the `name` attribute on `<router-view>`
>        RightSidebar,
>      },
>    },
>  ],
> })
> ```

In [`unplugin-vue-router`](https://github.com/posva/unplugin-vue-router?tab=readme-ov-file#named-views) this is implemented by appending `@<name>.vue` at the end of the file to render as the named view. e.g. in the above example, we would have `pages/index.vue`, `pages/index@LeftSidebar.vue` and `pages/index@RightSidebar.vue`.

I created [a discussion](https://github.com/nuxt/nuxt/discussions/20981) a while ago which did not gain much traction, where I showed an example of how to implement this by extending the router in `app/router.options.ts` (see https://nuxt.com/docs/guide/going-further/custom-routing). Note in this discussion I was using `__` as the filename separator rather than `@` as I had not seen the `unplugin-vue-router` implementation before that.

Firstly, is there already an easier way to implement this in Nuxt 3 than I proposed in [the discussion](https://github.com/nuxt/nuxt/discussions/20981#discussioncomment-5960870))? 

Is this something that could/should be implemented in Nuxt as a core feature?

I could only find v2.x issues on this topic:
* https://github.com/nuxt/nuxt/issues/968
* https://github.com/nuxt/nuxt/issues/4100

### Additional information

- [X] Would you be willing to help implement this feature? Yep
- [ ] Could this feature be implemented as a module? I don't think so. The only way I have been able to do this is in `app/router.options.ts`. I was unable to do anything in the `pages:extend` hook since the only param in the callback for this hook has type `NuxtPage[]`.

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
I think in general we'd want to align with first-party file-based routing conventions (cc @posva).

My question is primarily around how to 'escape' this if you do want to use `@` within a pattern in your route, e.g. `~/pages/[user]@[host].vue`.

**Comment by posva** [comment]
I wonder if from Nuxt's perspective it makes sense to allow named views 👀 I thought it was never added because of layouts.

Currently you cannot escape `@`, so you would have to use `defineRoute()` to set the actual path. I wonder what would be a good strategy to escape characters in filenames given the existing restrictions in windows

**Comment by danielroe** [comment]
You can set a name for a route in `definePageMeta`, and I think that's a reasonable solution for now.

I would welcome a PR to add `name` support within `pages:extend` to enable building this as a userland module. But we wouldn't want to add it to core as it would be a breaking change for existing users - see [this search for example](https://github.com/search?q=path:/pages%5C/@.*vue/&type=code&p=3).
