### ISSUE TITLE
[Feature Request] Implement a backing off strategy for <NuxtLoadingIndicator>

### ISSUE THREAD

**Issue by martinszeltins** [nuxt/nuxt#24552]
### Describe the feature

Currently, the NuxtLoadingIndicator component is not very smart about the way it shows page loading. For example if you set the `duration` prop to 2000 ms it will simply go to the end in 2 seconds and that's all. But if the page takes 5 seconds to load then the loading bar will be at the end stuck for 3 seconds. Not a very good UX.

I have seen loading indicators where it slowly backs off from reaching the end if the page is not loaded yet. For example if it gets  to about 50% and the page is still not loaded it starts moving more slowly and gets slower with time so it does not reach the end. It's an incremental back-off strategy.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by Ivankalachikov** [comment]
@danielroe I'd like to contribute on this, could I be assigned on the issue?

I consider adding `adaptive` property to the component, to switch between current and proposed behaviors.
This `adaptive` property is `false` by default. When it is `true` - use arctangent function to decrease step after reaching 50% of progress.

**Comment by Lehoczky** [comment]
> @danielroe I'd like to contribute on this, could I be assigned on the issue?
> 
> I consider adding `adaptive` property to the component, to switch between current and proposed behaviors. This `adaptive` property is `false` by default. When it is `true` - use arctangent function to decrease step after reaching 50% of progress.

I think this should be the default, and only behaviour. As the OP mentioned, the current implementation is not very user-friendly

**Comment by Ivankalachikov** [comment]
> > @danielroe I'd like to contribute on this, could I be assigned on the issue?
> > I consider adding `adaptive` property to the component, to switch between current and proposed behaviors. This `adaptive` property is `false` by default. When it is `true` - use arctangent function to decrease step after reaching 50% of progress.
> 
> I think this should be the default, and only behaviour. As the OP mentioned, the current implementation is not very user-friendly

Sounds pretty much reasonable, I'll stick this approach. Thank you!

**Comment by martinszeltins** [comment]
> I consider adding adaptive property to the component, to switch between current and proposed behaviors.
This adaptive property is false by default. When it is true - use arctangent function to decrease step after reaching 50% of progress.

I also think it would be nice to make it configurable when it starts to decrease step. At 50% or 20% or 30% and how large the decrease step is. But also with sane defaults that would work for most people.
