### ISSUE TITLE
`prerenderRoutes()` is not called on dynamic routes

### ISSUE THREAD

**Issue by cewald** [nuxt/nuxt#24579]
### Environment

- Operating System: Linux
- Node Version:     v16.17.0
- Nuxt Version:     3.8.1
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      telemetry
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://codesandbox.io/p/sandbox/lively-leaf-p4j22m

### Describe the bug

If I use `prerenderRoutes()` on a dynamic route to define a list of URLs to be crawled by the Nitro crawler, they won't be crawled. But if I put the same call into a static- or index-route it works fine. It also works if I put an empty `prerenderRoutes()` into the index route but not if I call `prerenderRoutes([])` in the static file to prevent the creation of an `undefined` route.

You can replicate it by running `npm run generate` and look at the generated HTML files in the `/.output` folder of my sample.

**Comment by b0ul17** [comment]
@danielroe This issue has been resolved. Would you close it to avoid any confusion?
