### ISSUE TITLE
Middleware executes twice when using navigateTo

### ISSUE THREAD

**Issue by Tristan971** [nuxt/nuxt#24576]
### Environment

Working directory: /redacted
Nuxt project info: (copied to clipboard)

------------------------------
- Operating System: Linux
- Node Version:     v20.8.1
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-3djymt?file=middleware%2Fbug.global.ts

Just open it, then navigate to /. For local testing:
- clone locally
- `npm install && npm run dev`
- in another window: `curl -IL -XGET localhost:3000`

### Describe the bug

When using a middleware which returns a `navigateTo`-based redirect, we see one more execution than expected.

On the reproduction linked, here are the middleware executions:
1. Execution for /, which the middleware returns a 302 to /redirected/
2. Execution for /redirected/ (as expected)
3. Execution for /redirected/ again (not expected)

### Additional context

In our project, we see a slightly different behaviour, where the original request is what gets handled twice (while in the repro it's the redirected request that gets handled twice).

I'm not entirely sure of what causes this difference, but I expect they are the same bug so it doesn't matter too much.

Either way, seems similar to https://github.com/nuxt/nuxt/issues/21470 and @danielroe suggested opening a separate issue instead, so here it is

### Logs

client-side:

```plain
$ curl -IL -XGET localhost:3000
HTTP/1.1 302 Found
location: /redirected/
content-type: text/html
date: Sun, 03 Dec 2023 10:03:07 GMT
connection: close
content-length: 98

HTTP/1.1 200 OK
content-type: text/html;charset=utf-8
x-powered-by: Nuxt
date: Sun, 03 Dec 2023 10:03:07 GMT
connection: close
content-length: 102729
```

server-side:
```
Running middleware for path: /
Redirecting to /redirected
Running middleware for path: /redirected/
Running middleware for path: /redirected/
```

**Comment by danielroe** [comment]
There is a known issue in _development_ mode where the very first request to the Vite dev server results in two hits. I don't think that's what you're reporting. Instead, this is happening:

* First server request, browser requests `/` and middleware executes, printing:
   > Running middleware for path: `/`
   > Redirecting to `/redirected`
* Still first server request, server now runs middleware for new path that we've been redirected to:
   > Middleware existRunning middleware for path: `/redirected/`
* Server sends `Location: /redirected` to browser
* Browser makes second request to server for `/redirected` and middleware executes on server, printing:
   > Running middleware for path: `/redirected/`

This is expected, and correct behaviour.

**Comment by danielroe** [comment]
I think it is correct. It's a new 'navigation' and needs to have all middleware run on it again. You can always store info on nuxtApp, for example.
