### ISSUE TITLE
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'data')

### ISSUE THREAD

**Issue by besscroft** [nuxt/nuxt#24587]
### Environment

Nuxt project info:                                                                                                                                                                             21:03:51  

------------------------------
- Node Version:     v18.18.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  pnpm@8.7.6
- Builder:          -
- User Config:      modules, experimental, pinia, piniaPersistedstate, css, colorMode, nitro, app, pwa, devtools
- Runtime Modules:  @vueuse/nuxt@10.6.1, @pinia/nuxt@0.5.1, @nuxtjs/color-mode@3.3.2, @vite-pwa/nuxt@0.3.2, @unocss/nuxt@0.57.7, @nuxtjs/device@3.1.1, @formkit/auto-animate/nuxt@0.8.1, @pinia-plugin-persistedstate/nuxt@1.2.0, @element-plus/nuxt@1.0.7, @nuxt/ui@2.11.0, @nuxt/image@1.1.0
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/besscroft/kamera/blob/dev/server/api/uploadFile.post.ts

### Describe the bug

When I requested this interface, an error message appeared. I'm running fine on Windows 11 and Vercel, but I'm getting errors with Netlify.

```ts
export default defineEventHandler(async (event) => {
    const body = await readMultipartFormData(event)
    console.log('body', body)
})
```
On Windows 11 and Vercel, body gets the correct content, but on Netlify, body is []. I tried a few things but couldn't solve the problem.

Finally, thank you for taking the time to read my question, thank you!

### Logs

```shell-script
Dec 4, 08:54:54 PM: 8eadd6b2 INFO   body []
Dec 4, 08:54:54 PM: 8eadd6b2 ERROR  [nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'data')
Dec 4, 08:54:54 PM: 8eadd6b2 ERROR    at ./chunks/uploadFile.post.mjs:24:24
Dec 4, 08:54:54 PM: 8eadd6b2 ERROR    at async Object.handler (./chunks/nitro/netlify.mjs:2444:19)
Dec 4, 08:54:54 PM: 8eadd6b2 ERROR    at async toNodeHandle (./chunks/nitro/netlify.mjs:2633:7)
Dec 4, 08:54:54 PM: 8eadd6b2 ERROR    at async lambda (./chunks/nitro/netlify.mjs:5604:13)
```

**Comment by danielroe** [comment]
This seems like a Nitro issue. Would you see if you can reproduce with pure Nitro, and raise an issue in https://github.com/unjs/nitro? 🙏

**Comment by besscroft** [comment]
> This seems like a Nitro issue. Would you see if you can reproduce with pure Nitro, and raise an issue in https://github.com/unjs/nitro? 🙏

Thanks for your suggestion, I tried to find the approximate location of the problem and submitted an issue to [h3](https://github.com/unjs/h3).

**Comment by danielroe** [comment]
Thank you ❤️ Let's track there.
