### ISSUE TITLE
Typescript error: useState have the wrong type in <template /> block in VsCode.

### ISSUE THREAD

**Issue by LouisMazel** [nuxt/nuxt#24591]
### Environment

- Operating System: Darwin
- Node Version:     v21.2.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.11.0
- Builder:          -
- User Config:      devtools, srcDir, app, appConfig, devServer, css, components, routeRules, modules, i18n, robots, sitemap, gtag, mazUi, vite, tailwindcss, postcss
- Runtime Modules:  maz-ui/nuxt, @nuxtjs/i18n@8.0.0-rc.4, @nuxtjs/tailwindcss@6.10.1, @nuxt/devtools@1.0.4, nuxt-schema-org@3.2.1, nuxt-gtag@1.1.1, nuxt-simple-sitemap@4.1.7, @nuxtjs/robots@3.0.0
- Build Modules:    -

--- 

VScode extensions: 
- Nuxtr
- TypeScript Vue Plugin (Volar)

## Example:

`pages/conversations.vue`

```vue
<template>
  <div>
    {{ conversations.length }}
    
    <ChatRoomItem v-for="conversation in conversations" :key="conversation.id" :conversation="conversation" />
  </div>
</template>

<script lang="ts" setup>
  type Conversation = {
    id: string
    roomId: string
    state: 'read' | 'unread'
    user?: User | null
    message?: string
    messages?: Message[]
    role: 'client' | 'admin'
    createdAt: string
    updatedAt?: string
  }

  const conversations = useState<Conversation[]>('conversations', () => [])
</script>
```

`tsconfig.json`

```json
{
  "extends": "./.nuxt/tsconfig.json"
}
```

### Describe the bug

The type of this `useState` is not good interpreted in the template block: 

![image](https://github.com/nuxt/nuxt/assets/12446546/58b42dd9-7c3d-45cf-a6b1-e96231081b02)

![image](https://github.com/nuxt/nuxt/assets/12446546/bde143db-4813-4346-b2db-985e3748764d)

The bug is not present if I use a `ref` instead of `useState`.

**Comment by derodz** [comment]
I am seeing this problem as well. It seems that the Ref returned by useState is no longer compatible with the expected Ref used in vue components. I believe I found a workaround by simply casting as a Ref but I haven't fully tested my application.
```typescript
const object = useState<ObjectType>('obj') as unknown as Ref<ObjectType>;
```

**Comment by danielroe** [comment]
This seems to be working fine to me in a new project.

<img width="1234" alt="CleanShot 2023-12-09 at 20 27 38@2x" src="https://github.com/nuxt/nuxt/assets/28706372/be10dc6b-73c4-431c-ba47-f3a80b2f59ea">

Check you don't have multiple versions of Vue in your project.

**Comment by derodz** [comment]
> This seems to be working fine to me in a new project.
> 
> <img alt="CleanShot 2023-12-09 at 20 27 38@2x" width="1234" src="https://private-user-images.githubusercontent.com/28706372/289311061-be10dc6b-73c4-431c-ba47-f3a80b2f59ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1ODQzNDYsIm5iZiI6MTcwMjU4NDA0NiwicGF0aCI6Ii8yODcwNjM3Mi8yODkzMTEwNjEtYmUxMGRjNmItNzNjNC00MzFjLWJhNDctZjNhODBiMmY1OWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDIwMDA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1N2UxNGM3YTZlZWI4YWMzYzVmZGZhMmFjYTQ2MmJlMDRmMzRkOTE5NzQ0Nzc5YjBhODc5MWRjZWU4ZmVjODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m-fzuy6Dj3J3MU3RB5GmoiJKJIUbAyzKuiNsqSFU2-0">
> Check you don't have multiple versions of Vue in your project.

This worked. Package.json in my nuxt folder had a different version of vue than package.json in my root folder.
