### ISSUE TITLE
How to make a static site generation website using nuxt 3 ? can u show me step by step like where to fetch the data is it from the nuxt config or fetch in the pages 

### ISSUE THREAD

**Issue by gervasiuswisely** [nuxt/nuxt#24598]
### Discussed in https://github.com/nuxt/nuxt/discussions/22006

<div type='discussions-op-text'>

<sup>Originally posted by **surgiie** July  7, 2023</sup>
In nuxt 2, you were able to specify `payload` in a route object during a `nuxt generate` to provide the data for the static html file:

https://v2.nuxt.com/docs/configuration-glossary/configuration-generate/#speeding-up-dynamic-route-generation-with-payload

I dont see any docs on how to accomplish this in nuxt 3, passing this payload during a generate is not rendering this data as it was before.

Am i missing something?</div>

**Comment by danielroe** [comment]
I'm not sure what issue this is here, but a discussion or Discord is a better place to ask it.
