### ISSUE TITLE
Customize middleware in server folder for custom api paths

### ISSUE THREAD

**Issue by Ahmadheysami** [nuxt/nuxt#24596]
### Describe the feature

I want to create an authentication firm in the server folder and in the firm folder and want to support any route / API / user path that is inside the user, how can I do this? In fact, what is the best way that Nuxt offers?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by Amar-Gill** [comment]
From what I can infer, you want to make a directory under `/server/api/` that corresponds to a firm (or business) name. And you want to run middleware only for that firm. Is this correct?

You can achieve this by adding a server middleware and using either `getRequestURL(event)` or `getRequestPath(event)` h3 utilities to filter for requests only on that path, and run logic conditionally.

https://github.com/unjs/h3#utilities

**Comment by Ahmadheysami** [comment]
Using Regex to filter paths is the best method I can use, and for example, a path /api/user as a fixed path and any path that is placed after user will be correct. Is this a good method?

**Comment by Amar-Gill** [comment]
Regex can work but also look into `String.includes()`. It looks for the first instance of a given substring. Could be simpler because each directory you got under /api should be unique.

There is also `String.split("/")`. Between these methods I think you can develop a system that works best for you.

**Comment by Ahmadheysami** [comment]
If I use String.includes(/) I have to check the array row by row. Or, for example, I want to use this middleware only for the path /api/dashboard/user, but a request is made from api/user, then user is included in includes, and the condition becomes true, and the middleware is also executed for this path.

**Comment by Amar-Gill** [comment]
I'm confused when you say "path /api/dashboard/user" ~ sounds like a client side page. Nitro middleware will only run on requests to  the nitro server: https://nuxt.com/docs/guide/directory-structure/server#server-middleware

Regardless, I think the discussion here demonstrates how to selectively run Nitro middleware for a subset of api routes (default is all routes) which was the original question. I believe we can close this issue if there is no further questions?

**Comment by Ahmadheysami** [comment]
Thank you very much.. The issue was fixed from the beginning, but it was always the best way. Thank you again.
