### ISSUE TITLE
navigateTo between dynamic routes cannot stop running setup function

### ISSUE THREAD

**Issue by daehyun-thevc** [nuxt/nuxt#24600]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools, experimental
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-luv6hh?file=pages%2Fblog%2F%5Bid%5D.vue

### Describe the bug

I expected that calling await navigateTo to another path with the same dynamic path but different params stop immediately setup function  running, resolve navigation and again run setup function. However, when I called navigateTo, the set function did not stop. 

https://github.com/nuxt/nuxt/assets/87633241/640f8f0a-84dd-4a2b-a3df-141feb06f75d

**Comment by daehyun-thevc** [comment]
That's not point. Thanks but the problem is console.log is exectued after navigateTo is called

**Comment by manniL** [comment]
Related issue (and the solution would be the same I'd say): https://github.com/nuxt/nuxt/issues/23698
