### ISSUE TITLE
Auto import doesn't work when exported variable and type share the same name.

### ISSUE THREAD

**Issue by DawidKopys** [nuxt/nuxt#24606]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.17.1`
- Nuxt Version:     `3.8.2`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `npm@9.6.7`
- Builder:          `-`
- User Config:      `devtools`, `typescript`, `imports`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

1. clone repo https://github.com/DawidKopys/nuxt-auto-imports-issue
2. run `npm i` -> `npx nuxt typecheck`

Expected Result: no TS errors

Actual Result: there is 1 TS error
```
components/WithTSError.vue:8:10 - error TS2749: 'TestEnum' refers to a value, but is being used as a type here. Did you mean 'typeof TestEnum'?

8 const a: TestEnum = TestEnum.foo
           ~~~~~~~~


Found 1 error in components/WithTSError.vue:8
```

### Describe the bug

It appears that - when variable and type are exported with the same name, only the variable is automatically imported.
The type is not added to `.nuxt/types/imports.d.ts`'s type re-export section at all.
As a result, there is TypeScript error in the `WithTSError.vue`.

I believe the type should be auto imported as well. TypeScript is "smart enough" to deal with variables and types sharing the same name as it understands what is being referred to (value or type) depending on the context. Some sources: https://notes.dt.in.th/TypeScriptValuesAndTypesWithSameName, https://stackoverflow.com/a/49798480/13329671.

Component `WithoutTSError.vue` proves that - it imports the `TestEnum` type from `#imports`. We don't have TypeScript error here. In fact, importing what we want from `#imports` seems to be a workaround for this issue.

Also, I have confirmed that the TS error goes away after adding below code in appropriate place inside `.nuxt/types/imports.d.ts`:
```typescript
// for type re-export
declare global {
  // ...
  // @ts-ignore
  export type { TestEnum } from '../../poorMansEnums/testEnum'
  import('../../poorMansEnums/testEnum')
}
```

### Additional context

You might be wondering why `TestEnum` is both constant object and a type. Let me explain - we have a large codebase in which we are migrating away from enums and we are replacing them with such const objects (see https://dev.to/egorovsa/how-to-extend-enum-in-typescript-cj4).
We want to keep the same names for both the value (const object) and the type in order to avoid doing changes in the files using our enum.

**Comment by manniL** [comment]
This might be an [unimport](https://github.com/unjs/unimport/) issue. Can you check and open one there in this case? 🤔

**Comment by manniL** [comment]
Are types auto-import as expected when using different names for the type + variable? 
If so, this might be an [unimport](https://github.com/unjs/unimport/) issue. Can you check and open one there in this case? 🤔

**Comment by danielroe** [comment]
cc: @antfu

**Comment by antfu** [comment]
This feels like a TypeScript limitation to me, and I am not sure if there is a workaround for it. Enums and Class are special type objects that can be referenced in both runtime space and type space. Our way of registering the global imports might not be able to have TypeScript understand it. I guess the workaround is either:

- Explictly import that enum to bail out the auto-import
- Export a type alias like `type TestEnumType = typeof TestEnum` and use `const a: TestEnumType = TestEnum.foo` to separate the runtime and type.

**Comment by DawidKopys** [comment]
I feel that I need to clarify this issue. I am sorry for making it more confusing by mentioning enums at all - my bad.

This issue isn't about enums. I have just mentioned enums to provide additional context here.
The point is:
- it is perfectly viable TypeScript code to have variable and type share the same name
- TypeScript will try to infer whether we are referencing value or type based on the context
- [it works](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYg9nKBeKBvKAzBAuKBnYAJwEsA7AcygF8AoGgYzlINhylIFcBbAIwkORQALHQD0oqACJ4cSVGJ4ohCI3KliALwgATKAENFeqADc9AGw7QeIKABVwEAMr0SYYFAAW-CAyZ44ZhAAdGZw5AAUMgCUYhLSCHIKSiph6lq6BvpQoJBQ1nYOzq7uXsq+zO48eoS4MoLoWHC4AOT+XNCmFhDN1EA)
- nuxt's autoimports (or, to be more precise, most likely `unimport`) only import the "value" and ignores the "type" if both exported variable and a type share the same name **- that's the issue I was trying to report here**

Hope this helps. Thanks everyone for looking into this topic.

**Comment by urbgimtam** [comment]
👀 Just stumbled on this today.

**Comment by dargfox** [comment]
Just happend to my project. Autoimports for enums just do not work correctly. It exports enums as "typeof FooEnum" that causes the potential problem.
I have separated composable constants.ts, where I have ModuleType enum. When I try to use it as a type, I see the same typescript check error.
Code example:
```
//@/composables/constants.ts

export enum ModuleType{
    TIMER,
    CUSTOM,
}
```

```
//@/components/Module.vue

interface IProps {
    name: string,
    type: ModuleType, // <- check error
    sizeY?: 1 | 2,
    sizeX?: 1 | 2,
}

const props = withDefaults(defineProps<IProps>(), {
    name: 'Module',
    type: ModuleType.CUSTOM,
    sizeY: 1,
    sizeX: 1,
})
```

The only ways to work around it that I found is to import in .vue file my Enum:
```
import { ModuleType } from '@/composables/constants.ts';
```
OR very ugly solution, but still works fine, is to create ValueOf type and use it as type in interface:
```
//@/components/Module.vue
type ValueOf<T> = T[keyof T];

interface IProps {
    name: string,
    type: ValueOf<typeof ModuleType>,
    sizeY?: 1 | 2,
    sizeX?: 1 | 2,
}

const props = withDefaults(defineProps<IProps>(), {
    name: 'Module',
    type: ModuleType.CUSTOM, // <- OK
    //type: 'test', <- check error
    //type: 3,       <- check error
    //type: 0,       <- OK
    sizeY: 1,
    sizeX: 1,
})
```

To extend last approach, to make it more usable, I moved ValueOf type to separate composable/(module declaration), and additionally created type Enum<T> that I will be use all over the project:
```
//@/types/index.d.ts
export {}

declare global {
    export type ValueOf<T> = T[keyof T]

    export type Enum<E> = ValueOf<E>
}



//@/components/Module.vue

interface IProps {
    name: string,
    type: Enum<typeof ModuleType>,
    sizeY?: 1 | 2,
    sizeX?: 1 | 2,
}

const props = withDefaults(defineProps<IProps>(), {
    name: 'Module',
    type: ModuleType.CUSTOM,
    sizeY: 1,
    sizeX: 1,
})
```

If I will find any type of other workaround - I'll leave comment here.

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/25311. Looks like it might have a PR to resolve it.
