### ISSUE TITLE
API error data gets rendered as HTML during SSR 

### ISSUE THREAD

**Issue by remonke** [nuxt/nuxt#24609]
### Environment

- Operating System: Linux
- Node Version:     v21.2.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  bun@1.0.13

### Reproduction

https://stackblitz.com/edit/nuxt-starter-typhrm

### Describe the bug

When I throw an error with `createError` in an API handler, and then want to retrieve its data in an app, instead of JSON response I receive an HTML page. This makes it impossible to retrieve any additional data I passed in with the error, and also bloats the `__NUXT_DATA__` object.  

Happens only during SSR, client side requests do not have this problem. Also works when the error is actually thrown, as simply responding with an error response status works fine.

Renders HTML ❌
![Screenshot_20231205_155553](https://github.com/nuxt/nuxt/assets/102010617/4647fee1-d2d5-44c0-ab55-8ad61c2212f4)

Renders JSON ✅
![Screenshot_20231205_155614](https://github.com/nuxt/nuxt/assets/102010617/8b123ed6-267c-4427-8fcc-0d2d84ce2f46)

**Comment by remonke** [comment]
Okay I have figured out this is because `useFetch` passes headers from the request event, which contains `accept` header with `text/html`. Hence I get an HTML page instead of a JSON response.

https://github.com/nuxt/nuxt/blob/6a1c054012ca81c73911bdd62c262e9d34b5c611/packages/nuxt/src/core/runtime/nitro/error.ts#L9

Passing explicitly `{ accept: '*/*' }` does not cause this to happen. However, why does Nuxt pass the browser `accept` header to server API requests?

**Comment by danielroe** [comment]
I think we probably should _not_ pass the browser `accept` header through via `useRequestEvent`.

cc: @pi0

**Comment by yapengsoft** [comment]
sendError(event, createError({
    statusCode: 400,
    statusMessage: 'Bad Request',
}), false);
