### ISSUE TITLE
Nuxt project creation failed.

### ISSUE THREAD

**Issue by lzb-libra** [nuxt/nuxt#24618]
### Environment

win11

### Reproduction

In the local environment, whether I use the 'npx' or 'pnpm' command, creating a Nuxt project fails with the error message: 'Error: Failed to download template from registry: fetch failed'.

### Describe the bug

`pnpm dlx nuxi@latest init nuxt-test ` or `pnpm dlx nuxi@latest init nuxt-test`

**Comment by hug-love** [comment]
https://github.com/nuxt/cli/issues/159

**Comment by hug-love** [comment]
https://github.com/nuxt/cli/issues/159。maybe project should support http proxy when using nuxi init，not #21853。

**Comment by chow5566** [comment]
> [nuxt/cli#159](https://github.com/nuxt/cli/issues/159) maybe project should support http proxy when using nuxi init，not [#21853](https://github.com/nuxt/nuxt/issues/21853)。

yes,when i close the vpn(steam++),it works
