### ISSUE TITLE
High Traffic Website Chunk Breaks/Not Found on Redeployment

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [nuxt/nuxt#24613]
After deploying my high-traffic website on DigitalOcean App, I’ve noticed a recurring issue where a chunk of the website breaks / not found for a few seconds during redeployment. Upon careful log analysis, it appears that approximately 2 - 5% of users are consistently affected each time we redeploy.

Every time chunk file url changes that's why this happens. It's automatically fix when user refresh page

Is there any way to prevent this issue?
```[tasklist]
### Tasks
```

**Comment by manniL** [comment]
See https://github.com/nuxt/nuxt/issues/14594 and https://github.com/nuxt/nuxt/pull/19038

Try out `experimental.emitRouteChunkError` (e.g. `reload`)

**Comment by rahulkumarsingh73690** [comment]
Thanks @manniL 

In [docs ](https://nuxt.com/docs/guide/going-further/experimental-features#emitroutechunkerror) only automatic, manual or false 

No reload

**Comment by manniL** [comment]
@rahulkumarsingh73690 Ah sorry, yes. Old situation. It *should* reload automatically by now 🤔 
If that doesn't happen, you can still hook in manually and give it a try

**Comment by rahulkumarsingh73690** [comment]
@manniL 

The CDN part is a bit complicated. 

Is there any to make the chunk file name the same?

So even if a new build is deployed previous users still use our app

**Comment by manniL** [comment]
ere any to make the chunk file name the same?
> 
> So even if a new build is deployed previous users still use our app

Yes but I'd not advice that. Then you can't cache them properly and people will receive old files, leading to a broken app.
