### ISSUE TITLE
getBoundingClientRect is not a function

### ISSUE THREAD

**Issue by cybercoder-naj** [nuxt/nuxt#24615]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v21.2.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  pnpm@8.11.0
- Builder:          -
- User Config:      devtools, css, postcss, app
- Runtime Modules:  -
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                                                                             21:51:20

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Reproduction

```
<script setup lang="ts">
const aboutSection = ref<HTMLDivElement | null>(null);
const top = ref<number>(0);

onMounted(() => {
  top.value = aboutSection.value?.getBoundingClientRect().top
});
</script>

<template>
  <AboutSection ref="aboutSection" :style="`height: calc(100vh - ${top}px)`" />
    <!-- AboutSection is a component inside components/ directory -->
  </AboutSection>
</template>
```

### Describe the bug

`aboutSection.value?.getBoundingClientRect is not a function`

**Comment by huang-julien** [comment]
Hi, `aboutSection` will not be an HTMLDivElement but a vue component public instance 
see https://vuejs.org/guide/essentials/template-refs#ref-on-component
