### ISSUE TITLE
How can I cancel useLazyFetch payload cache?

### ISSUE THREAD

**Issue by fairySusan** [nuxt/nuxt#24622]
### Environment

 "nuxt": "^3.7.3"

### Reproduction

https://stackblitz.com/edit/github-ww98ek?file=pages%2Fabout.vue,pages%2Findex.vue,server%2Fapi%2Flist.ts

### Describe the bug

in the `index` page, I request two pages of data, then navigate to the `about` page, and then back to the `index` page, the `index` page will have a cache of page2 data, and I don't want this cache.This is actually a scroll loading more list.
I am a brand-new about nuxt, I am very appreciate for giving me advice.

### Additional context
I've tried `initialCache: false`  but it didn't work
_No response_

**Comment by fairySusan** [comment]
@manniL Thank you very much!

**Comment by Shmi1y** [comment]
Hello, after upgrading to the latest version recently, the project runs smoothly locally and uses cached data when refreshing the page. However, when deployed online, there is no data echo when refreshing the page. My previous project used version 3.4, and I remember using cached data when refreshing the page. The line is also normal, but the new version does not have cached data. What's the problem
