### ISSUE TITLE
504 (Outdated Optimize Dep) (vue.js, line 0) on Safari

### ISSUE THREAD

**Issue by baldurfb** [nuxt/nuxt#24631]
### Environment

npx nuxi info
- Operating System: `Darwin`
- Node Version:     `v20.10.0`
- Nuxt Version:     `3.8.2`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `yarn@1.22.21`
- Builder:          `-`
- User Config:      `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

```
 "devDependencies": {
    "@nuxt/devtools": "latest",
    "nuxt": "^3.8.2",
    "vue": "^3.3.10",
    "vue-router": "^4.2.5"
  }
```

The browser is Safari 17.1.2

### Reproduction

The issue is present with only the default scaffolding.
The following are exhaustive steps to reproduce the issue.
Note that this is most likely highly dependent on the environment.

- ```npx nuxi@latest init <project-name>```
- ```cd <project-name>```
- ```yarn install```
- ```yarn dev```
- Visit the page and keep it open
- control + c to shut down the server
- ```yarn dev```
- Before the server has booted up, bring focus back to the website

### Describe the bug

Expected behaviour:
There is a short wait while the server finishes booting up. Then everything works normally

Actual behaviour:
http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/vue.js?v=b5b0d026 fails to load with the following error message in the console: "Failed to load resource: the server responded with a status of 504 (Outdated Optimize Dep)". As a result no client-side scripts work.

### Additional context

I did not manage to reproduce the problem using the [Vue SSR starter](https://github.com/nuxt-contrib/vue3-ssr-starter).

Tested solutions:
- Disabling the browser cache & refreshing the page has no effect.
- Deleting node_modules and doing a full reinstall has no effect.
- Yarn complained that some packages were missing vite as a peer dependency, installing that does not resolve this issue.
- Googling yielded few results
	- Some mention the solutions above
	- Running vite with --force, not applicable?
	- Adding the dependency ("vue") to vite.optimizeDeps.exclude does not solve this issue.
- Disabling anti-tracking/ad-block plugins had no effect.

Two methods to temporarily clear the issue:
- Method 1
	- Shut down the server
	- Refresh the page to bring up the Safari's "Safari cannot connect ..." page
	- Start the server
	- Refresh the page
- Method 2
	- "Empty Buffers" in the Safari developer menu. and refresh the page

### Logs

```shell-script
[Error] Failed to load resource: the server responded with a status of 504 (Outdated Optimize Dep) (vue.js, line 0)
[Debug] [vite] connecting... (client, line 229)
[Debug] [vite] connected. (client, line 324)
```

**Comment by ExEr7um** [comment]
I have this error every time I restart the server.

For me it fixes when I reload page using `Option`+`Command`+`R`.

**Comment by danielroe** [comment]
This is a Vite issue. It may be resolved in Vite 5 - would you try manually adding `npm i vite@5` and seeing if that makes a difference? 🙏

**Comment by jason-Impress** [comment]
> This is a Vite issue. It may be resolved in Vite 5 - would you try manually adding `npm i vite@5` and seeing if that makes a difference? 🙏

That fixed it for me!

**Comment by educbraga** [comment]
> This is a Vite issue. It may be resolved in Vite 5 - would you try manually adding `npm i vite@5` and seeing if that makes a difference? 🙏

Unfortunately, no difference.

**Comment by P4sca1** [comment]
After updating to Nuxt 2.9 / Vite 5, I still had to perform a full reload once using `Option` + `Command` + `R` to resolve the issue.
On subsequent server restarts the issue no longer occured with the latest nuxt version.

**Comment by whcxxb** [comment]
nuxt3.9.0 problem still exists

**Comment by manniL** [comment]
@whcxxb Provide a reproduction then please ☺️

**Comment by chasebank** [comment]
> @whcxxb Provide a reproduction then please ☺️

Getting this in a completely fresh install, just as OP describes, using `npx nuxi@latest init <project-name>`, following exact steps explained to reproduce.

Error isn't present after running `yarn dev` for first time. But after restarting server and returning to page, error is perpetual.

Error only present in Safari (v 17.2.1). Chrome has no issue.

Tried reproducing in StackBlitz but there's currently a different issue with webcontainers and Safari compatibility, that's completely breaking Nuxt installs on their platform.

**Comment by danielroe** [comment]
I still can't reproduce following those exact steps.

However, it seems likely that this is a vite issue. You could try removing `node_modules/.cache` to remove the vite cache.

**Comment by chasebank** [comment]
> I still can't reproduce following those exact steps.
> 
> However, it seems likely that this is a vite issue. You could try removing `node_modules/.cache` to remove the vite cache.

Try `yarn dev --host`. Still getting with a fresh install after updating Safari, but not with `--host` omitted. Also tried forcing Vite to v5

**Comment by sondh0127** [comment]
Hope we have tracking issue in Vite

**Comment by SheikhElMoctarG** [comment]
> I still can't reproduce following those exact steps.
> 
> However, it seems likely that this is a vite issue. You could try removing `node_modules/.cache` to remove the vite cache.

I still same problem, Is there not another option?

**Comment by matthew-dean** [comment]
Also seeing this issue in latest Nuxt. In my case I have a custom `devServer` host / port, which may be related

**Comment by Suniron** [comment]
Same error on wsl2 / Windows 11

**Comment by Gonzalo-Bruna** [comment]
I got this issue, fixed it by making a full-reload using option + cmd + R. Only happens on Safari.
