### ISSUE TITLE
When I switch layout , keepAlive doesn't work.

### ISSUE THREAD

**Issue by 2536629322** [nuxt/nuxt#24646]
### Environment

Operating System: Windows
Node Version: v18.16.1
Nuxt Version: 3.8.2
Nitro Version: 2.8.1

### Reproduction

[https://stackblitz.com/edit/nuxt-starter-xf3axm?file=pages%2Findex.vue](https://stackblitz.com/edit/nuxt-starter-xf3axm?file=pages%2Findex.vue)
There are two layouts. index.vue and test2.vue  use default layout , and test1.vue uses test layout. When i switch route between index.vue and test2.vue , keep alive is working. But when i switch route to test1, keepAlive isn't working.

### Describe the bug

`<template>
    <div>
        <NuxtLayout>
            <NuxtPage :keepalive="{}" />
        </NuxtLayout>
    </div>
</template>
  `
I have add keepalive on app.vue, and I have three layouts.  When I switch layout , keepAlive doesn't work. Under same layout, keepAlive works.

**Comment by danielroe** [comment]
`KeepAlive` won't be able to retain the component instance if `<NuxtPage>` itself is recreated (by a new/different layout being rendered).

This is a Vue limitation.
