### ISSUE TITLE
Symlink dependency resolve.modules logic mistake which created by package.json workspace

### ISSUE THREAD

**Issue by samuel-pp** [nuxt/nuxt#24643]
### Environment

- system: ubuntu 18.04.6 TLS
- node version: v16.14.2
- npm version: 8.5.0
- nuxt version: ^2.17.0
- nuxt bridge: npm:@nuxt/bridge-edge@^3.0.0-rc.1-28283885.3bdcd6b

### Reproduction

..

### Describe the bug

my project folder tree:
```
|-- root
|   |-- a
|       |-- node_modules
|           |-- b (symlink to ../packages/b)
|-- packages
    |-- b
|-- node_modules
```
*no node_modules folder in the root/packages and its sub folder.*

**I want the components in the b folder use dependencies in the root/a/node_modules, instead of root/node_modules.**

After trying various methods such as `webpackConfig.resolve.symlinks` or `nuxtConfig.followSymlinks`, I discovered that the `webpackConfig.resolve.modules` appears as follows: `['node_modules', '/root/a/node_modules/@nuxt/bridge/node_modues', ...(normal recursion to /root)]`. When attempting to remove the first relative-path item ('node_modules'), the dependencies are resolved as intended. However, this approach affects packages that have their own `node_modules`, disrupting their normal dependency logic.

How can I address this issue?

**Comment by hahaland** [comment]
Same problem, help!!

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
