### ISSUE TITLE
On-demand Incremental Static Site Regeneration

### ISSUE THREAD

**Issue by kangelopoulos** [nuxt/nuxt#24654]
### Describe the feature

Right now, nuxt is capable of both ISR and SWR based on TTL from the routes option in the nuxt.config.ts. However, I'm curious if there is a plan to allow for on-demand incremental static regeneration where a change to a CMS or database can rebuild one or a few pages of many statically generated pages. 

It would look something like this: a content manager updates a CMS like Sanity. A webhook with a secret token of some sort calls the nuxt server and initiates a rebuild of a page (accessing that page through a unique ID or hash value). Users are served a stale page while the site is rebuilding the page in the background. The rebuilt page is then served once it's ready. 

This would be a game changer for dynamic e-commerce sites that have data change often, especially where products become unavailable suddenly as supply chains are disrupted or change in some way. Next has this feature (see https://nextjs.org/docs/pages/building-your-application/data-fetching/incremental-static-regeneration section 2), and it would be a huge plus to nuxt e-commerce sites in particular. 

I've tried to look this up several times and see if it's a possibility in nuxt at all and have come up blank on whether I can rebuild a single page based on some kind of endpoint created in the nuxt server. Does anyone know if there is a way to accomplish this currently? If not, could it be considered for a feature request?

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Let's track in https://github.com/unjs/nitro/issues/889. This is absolutely on the roadmap.
