### ISSUE TITLE
v-show breaks when used in a Vue component that is a direct slot of NuxtClientFallback

### ISSUE THREAD

**Issue by prashantpalikhe** [nuxt/nuxt#24650]
### Environment

Nuxt project info:                                                                                                                       12:11:19

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools, experimental
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-ouse6d?file=app.vue

### Describe the bug

The page should not show any content at all. But it does when the SSR rendered HTML is shown. And then turns black after hydration completes.

### Additional context

This only happens when v-show is used on a Vue component that is a direct child of NuxtClientFallback.

**Comment by danielroe** [comment]
Let's track in that issue then 🙏 

If for whatever reason that's not fixed upstream we can reopen here and look to resolve in Nuxt.
