### ISSUE TITLE
Cannot start nuxt:  Cannot use 'import.meta' outside a module

### ISSUE THREAD

**Issue by shayandrg** [nuxt/nuxt#24664]
### Discussed in https://github.com/nuxt/nuxt/discussions/24507

<div type='discussions-op-text'>

<sup>Originally posted by **shayandrg** November 28, 2023</sup>
**Environment**
Operating System: Ubuntu 22.04.3 LTS
Node Version: v20.8.1
Nuxt Version: 3.8.2
CLI Version: 3.10.0
Nitro Version: 2.8.0
Package Manager: npm@10.1.0
jiti: 1.21.0
telemetry: 2.5.3

**Describe the bug**
i tried to create nuxt module with default template as (nuxt.new) says and i done everything like nuxt module author document said but i got this error when starting nuxt with npm run dev:

![image](https://github.com/nuxt/nuxt/assets/45017318/5278ccdb-1b46-4114-bca2-2d3932b5e430)

i tried to clear npm local and global cache and remove parent folders node_modules and clear and re-installing more than 3 times everything and changing nuxt/kit version to previous but nothing happend.

im not new to nuxt module and i developed some modules for nuxt 2 in the past but I never had such an experience

what should i do?

</div>

**Comment by shayandrg** [comment]
reproduction: https://stackblitz.com/edit/nuxt-starter-hnmoca

note: it runs fine on stackblitz. also I tested this on 3 computers and it had an error on 2, but it was ok on another computer!
so we can't say it's like this only for me because it happened on other computers as well.

**Comment by madebyfabian** [comment]
@shayandrg Do you still experience this? I unfortunately cannot reproduce it when opening the Stackblitz project.

**Comment by shayandrg** [comment]
Can confirm this is a Nuxt bug. It's a proper `.mjs` file being imported into `nuxt.config.ts` but the `import.meta` call within the `.mjs` file is not correctly interpreted and throws this error.

_Originally posted by @matthew-dean in https://github.com/nuxt/nuxt/discussions/24507#discussioncomment-10318456_

**Comment by danielroe** [comment]
Would you be able to provide a minimal reproduction in that case? 🙏
