### ISSUE TITLE
Nuxt3 nuxt.config.ts

### ISSUE THREAD

**Issue by xunzhaotech** [nuxt/nuxt#24666]
### Environment

plugins parameters cannot be assigned to parameters of type "InputConfig<NuxtConfig, ConfigLayerMeta>". Object text can only specify known properties, and "plugins" are not in the type "InputConfiguration<NuxtConfiguration, ConfigLayerMeta>". Ts (2345)

### Reproduction

plugins parameters cannot be assigned to parameters of type "InputConfig<NuxtConfig, ConfigLayerMeta>". Object text can only specify known properties, and "plugins" are not in the type "InputConfiguration<NuxtConfiguration, ConfigLayerMeta>". Ts (2345)

### Describe the bug

plugins parameters cannot be assigned to parameters of type "InputConfig<NuxtConfig, ConfigLayerMeta>". Object text can only specify known properties, and "plugins" are not in the type "InputConfiguration<NuxtConfiguration, ConfigLayerMeta>". Ts (2345)

### Additional context

plugins parameters cannot be assigned to parameters of type "InputConfig<NuxtConfig, ConfigLayerMeta>". Object text can only specify known properties, and "plugins" are not in the type "InputConfiguration<NuxtConfiguration, ConfigLayerMeta>". Ts (2345)

### Logs

```shell-script
plugins parameters cannot be assigned to parameters of type "InputConfig<NuxtConfig, ConfigLayerMeta>". Object text can only specify known properties, and "plugins" are not in the type "InputConfiguration<NuxtConfiguration, ConfigLayerMeta>". Ts (2345)
```

**Comment by manniL** [comment]
@xunzhaotech Please provide information on how to reproduce that error.

**Comment by xunzhaotech** [comment]
> Not exactly same as @xunzhaotech but similar problem exists even on minimal reproduction [link](https://codesandbox.io/s/github/nuxt/starter/v3-codesandbox) <img alt="image" width="623" src="https://private-user-images.githubusercontent.com/48688801/290557941-065fd52c-5ae7-4112-b7bb-3ec5712f4abe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NjcxNjgsIm5iZiI6MTcwMjU2Njg2OCwicGF0aCI6Ii80ODY4ODgwMS8yOTA1NTc5NDEtMDY1ZmQ1MmMtNWFlNy00MTEyLWI3YmItM2VjNTcxMmY0YWJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDE1MTQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyMTJiYjczMjEwNDE0YTdmODFlN2Y2MWI0ZmUzMmJkODhiOGNmODZlOGVkMjY0YjAxNGZmZjhlMTVkOWU0OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CWfg-XsK8_a3uJedxCJOu5SvEuhNmVF0aaAZmQbKAj4">

**Comment by xunzhaotech** [comment]
How to deal this bug?

**Comment by madebyfabian** [comment]
Can be closed. Original poster never provided a reproduction. The reproduction from @doganalper does not have an issue anymore:
![Bildschirmfoto 2024-03-29 um 19 29 28](https://github.com/nuxt/nuxt/assets/32813692/cbaf7bb7-7bb4-4bc8-ac9f-d31cd43855a9)
