### ISSUE TITLE
【usage】cannot read preperties of null (reading ‘$nuxt‘)

### ISSUE THREAD

**Issue by robbiemie** [nuxt/nuxt#24663]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.17.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  pnpm@8.10.0
- Builder:          -
- User Config:      ssr, build, sourcemap, debug, devServer, alias, modules, app, typescript, components, imports, vite
- Runtime Modules:  @pinia/nuxt@0.4.11
- Build Modules:    -
------------------------------

### Reproduction

```ts
// parent component
function renderComponent(container:HTMLElement, configs) {
  const { vueComponent, app } = configs
  const el = container || createElement()
  if(!el) {
    throw new Error('[error render]: container is empty');
  }
  const vNode = createVNode(vueComponent)
  render(vNode, container);
  const vm = <ComponentInternalInstance>vNode.component
  return {
    instance: vm,
    reference: vm.exposed?.reference
  }
}
```

```ts
// subcomponent
<script lang="ts" setup>
onMounted(() => {
  const nuxtApp = useNuxtApp() // error: cannot read preperties of null (reading ‘$nuxt‘)
  // or
  const route = useRoute() // error: cannot read preperties of null (reading ‘$nuxt‘)
})
</script>
```

### Describe the bug

> When I created a component through the createVNode method, Its appContext attribute is null in subComponent.

### Additional context

![企业微信截图_30d918ff-f439-4064-9e40-889668b6638c](https://github.com/nuxt/nuxt/assets/20657678/d19720a1-a470-4d77-b5c0-814a74bed634)
![企业微信截图_f5b9d9d3-a4e8-4814-83c3-114b060ff806](https://github.com/nuxt/nuxt/assets/20657678/414f680d-877a-4e55-adbe-3c9c3efaca31)

**Comment by danielroe** [comment]
I think this is a usage issue; you're not passing through the `vueApp` injections. In Vue 3 these are not global.

**Comment by robbiemie** [comment]
> I think this is a usage issue; you're not passing through the `vueApp` injections. In Vue 3 these are not global.

Hi, This is a test code link.pls~

https://stackblitz.com/edit/github-zqj5r6?file=public%2Fcomponents%2FsubComponent.vue

**Comment by robbiemie** [comment]
I might have solved it.


```ts

  if(app?.vueApp?._context) {
    // inject appContext props
    vNode.appContext = app.vueApp._context
  }
```

> Complete code

follows:

```ts
function renderComponent(container:HTMLElement, configs: any) {
  const { vueComponent, app, props } = configs
  const el = container || createElement()
  if(!el) {
    throw new Error('[error render]: container is empty');
  }
  const defaultProps = {}
  const mergeProps = merge(defaultProps, props)
  const vNode = createVNode(vueComponent, mergeProps)
  if(app?.vueApp?._context) {
    vNode.appContext = app.vueApp._context
  }
  const dom = render(vNode, container);
  const vm = <ComponentInternalInstance>vNode.component
  return {
    instance: vm,
    reference: vm.exposed?.reference,
    dom
  }
}
```

**Comment by danielroe** [comment]
I guess that's a question for Vue itself.
