### ISSUE TITLE
useFetch in route middleware will called twice.

### ISSUE THREAD

**Issue by robin-dongbin** [nuxt/nuxt#24677]
### Environment

- Operating System: Darwin
- Node Version:     v18.19.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.11.0
- Builder:          -
- User Config:      ssr, devtools, build, css, modules, components, runtimeConfig
- Runtime Modules:  @nuxt/image@1.1.0, @nuxtjs/i18n@8.0.0-rc.5, @nuxtjs/color-mode@3.3.2, @pinia/nuxt@0.5.1, @vueuse/nuxt@10.7.0, @unocss/nuxt@0.56.5, @pinia-plugin-persistedstate/nuxt@1.2.0, nuxt-laravel-precognition@0.0.7, tdesign-vue-next/es/nuxt
- Build Modules:    -

### Reproduction

middleware:
```
export default defineNuxtRouteMiddleware(() => {
  const { data } = useFetch('/api/profile')
})

```
server
```
export default defineEventHandler(
  async (event) => {
    console.log(event.path)
  },
)

```

### Describe the bug

useFetch in middleware will called twice, once in server, once in clicent.
you can see 2 event.path log.
and in the browser devtools will see a request.

**Comment by danielroe** [comment]
Just to confirm, `/api/profile` should return a value; if a value is not returned from `useFetch`/`useAsyncData`, it will be recalled on the client.

**Comment by robin-dongbin** [comment]
The server throw an error
Thanks.
