### ISSUE TITLE
Disabling `experimental.appManifest` in a module breaks the app

### ISSUE THREAD

**Issue by IonianPlayboy** [nuxt/nuxt#24672]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      myModule, devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

I also had the issue on my local env. (OS `Darwin`, Package Manager `pnpm@8.12.0`)

### Reproduction

[Link to StackBlitz reproduction](https://stackblitz.com/edit/nuxt-bug-app-manifest-in-module?file=modules%2Fmy-module.ts)

### Describe the bug

To make the bug appear, your Nuxt project needs to satisfy both of these criterias :

- Enable routing in the project (i.e have at least one route in the `pages` folder)
- Add to the project a module that changes `nuxt.options.experimental.appManifest` to false

When all these conditions are met, the `manifest-route-rule` middleware will still be included in the app, but since `experimental.appManifest` is set to `false` by the module it will throw and thus break the app. (A 500 error appears when trying to access the app)

I would be interested in opening a PR to fix this if that's okay, but I would rather wait to have an answer on the best way to solve the issue before starting. (see below)

### Additional context

The bug is a result of the order in which Nuxt add the `manifest-route-rule` and read the user added modules inside [packages/nuxt/src/core/nuxt.ts](https://github.com/nuxt/nuxt/blob/7a32eaf873c16980d304ce8ace0a125dce8567c0/packages/nuxt/src/core/nuxt.ts).

The user plugins initialisation starts here :
https://github.com/nuxt/nuxt/blob/7a32eaf873c16980d304ce8ace0a125dce8567c0/packages/nuxt/src/core/nuxt.ts#L196-L198

Whereas the `manifest-route-rule` middleware is added here : 
https://github.com/nuxt/nuxt/blob/7a32eaf873c16980d304ce8ace0a125dce8567c0/packages/nuxt/src/core/nuxt.ts#L97-L102

The Nuxt config was not updated by user modules at this point, so the middleware is added before it can be overrided by the user plugin, which causes the bug.

I did not test it, but I would think that changing the config inside a Layer would not have the same issue, since its configuration alterations are handled before the middleware : 

https://github.com/nuxt/nuxt/blob/7a32eaf873c16980d304ce8ace0a125dce8567c0/packages/nuxt/src/core/nuxt.ts#L53-L58

I also have not checked further, but I guess that it's not the only option that might break currently if changed by a user plugin, since a lot of initialisation happens in `initNuxt` before the user plugins had a chance to update the config.

There are a few ways to solve the issue :

- Move the middleware addition after the user plugin are initialised (simple, would fix this bug but there might be more to fix)
- Change the way user plugins are initialised, either by doing it earlier in the process or by splitting the initialisation between config alteration (which should happen as early as possible) and the rest of the plugin's logic (which can stay in the same place the plugins were). This is more work, but it would be a better solution long term in my opinion.
- If this is intended behavior and there are no plans to change this, I think the documentation should be updated at least to warn/inform users about this caveat. This is definitely not the behavior I would expect when reading the docs about [altering the nuxt config inside a module](https://nuxt.com/docs/guide/going-further/modules#altering-nuxt-configuration).

### Logs

```shell-script
500

[nuxt] app manifest should be enabled with `experimental.appManifest`

getRouteRules@https://githubrnqxck-hrac--3000--d3416dfd.local-corp.webcontainer.io/_nuxt/node_modules/nuxt/dist/app/composables/manifest.js?v=0a3effb9:26:9
@https://githubrnqxck-hrac--3000--d3416dfd.local-corp.webcontainer.io/_nuxt/node_modules/nuxt/dist/app/middleware/manifest-route-rule.js?v=0a3effb9:8:70
executeAsync@https://githubrnqxck-hrac--3000--d3416dfd.local-corp.webcontainer.io/_nuxt/node_modules/unctx/dist/index.mjs?v=0a3effb9:111:19
@https://githubrnqxck-hrac--3000--d3416dfd.local-corp.webcontainer.io/_nuxt/node_modules/nuxt/dist/app/middleware/manifest-route-rule.js?v=0a3effb9:8:38
setup/
fn@https://githubrnqxck-hrac--3000--d3416dfd.local-corp.webcontainer.io/_nuxt/node_modules/nuxt/dist/app/nuxt.js?v=0a3effb9:153:44
runWithContext@https://githubrnqxck-hrac--3000--d3416dfd.local-corp.webcontainer.io/_nuxt/node_modules/.cache/vite/client/deps/chunk-YBSB36RH.js?v=0a3effb9:5284:18
callWithNuxt@https://githubrnqxck-hrac--3000--d3416dfd.local-corp.webcontainer.io/_nuxt/node_modules/nuxt/dist/app/nuxt.js?v=0a3effb9:158:24
createNuxtApp/runWithContext/<@https://githubrnqxck-hrac--3000--d3416dfd.local-corp.webcontainer.io/_nuxt/node_modules/nuxt/dist/app/nuxt.js?v=0a3effb9:31:66
run@https://githubrnqxck-hrac--3000--d3416dfd.local-corp.webcontainer.io/_nuxt/node_modules/.cache/vite/client/deps/chunk-YBSB36RH.js?v=0a3effb9:293:16
runWithContext@https://githubrnqxck-hrac--3000--d3416dfd.local-corp.webcontainer.io/_nuxt/node_modules/nuxt/dist/app/nuxt.js?v=0a3effb9:31:44
setup/<@https://githubrnqxck-hrac--3000--d3416dfd.local-corp.webcontainer.io/_nuxt/node_modules/nuxt/dist/pages/runtime/plugins/router.js?v=0a3effb9:126:40
async*guardToPromiseFn/
guardToPromiseFn/<@https://githubrnqxck-hrac--3000--d3416dfd.local-corp.webcontainer.io/_nuxt/node_modules/.cache/vite/client/deps/vue-router.js?v=0a3effb9:1468:16
runWithContext@https://githubrnqxck-hrac--3000--d3416dfd.local-corp.webcontainer.io/_nuxt/node_modules/.cache/vite/client/deps/chunk-YBSB36RH.js?v=0a3effb9:5284:18
runWithContext@https://githubrnqxck-hrac--3000--d3416dfd.local-corp.webcontainer.io/_nuxt/node_modules/.cache/vite/client/deps/vue-router.js?v=0a3effb9:2485:66
createRouter/runGuardQueue/
promise callback*createRouter/runGuardQueue/<@https://githubrnqxck-hrac--3000--d3416dfd.local-corp.webcontainer.io/_nuxt/node_modules/.cache/vite/client/deps/vue-router.js?v=0a3effb9:2754:54
runGuardQueue@https://githubrnqxck-hrac--3000--d3416dfd.local-corp.webcontainer.io/_nuxt/node_modules/.cache/vite/client/deps/vue-router.js?v=0a3effb9:2754:19
createRouter/navigate/<@https://githubrnqxck-hrac--3000--d3416dfd.local-corp.webcontainer.io/_nuxt/node_modules/.cache/vite/client/deps/vue-router.js?v=0a3effb9:2504:14
promise callback*navigate@https://githubrnqxck-hrac--3000--d3416dfd.local-corp.webcontainer.io/_nuxt/node_modules/.cache/vite/client/deps/vue-router.js?v=0a3effb9:2498:34
pushWithRedirect@https://githubrnqxck-hrac--3000--d3416dfd.local-corp.webcontainer.io/_nuxt/node_modules/.cache/vite/client/deps/vue-router.js?v=0a3effb9:2431:50
push@https://githubrnqxck-hrac--3000--d3416dfd.local-corp.webcontainer.io/_nuxt/node_modules/.cache/vite/client/deps/vue-router.js?v=0a3effb9:2367:12
replace@https://githubrnqxck-hrac--3000--d3416dfd.local-corp.webcontainer.io/_nuxt/node_modules/.cache/vite/client/deps/vue-router.js?v=0a3effb9:2370:12
setup/<@https://githubrnqxck-hrac--3000--d3416dfd.local-corp.webcontainer.io/_nuxt/node_modules/nuxt/dist/pages/runtime/plugins/router.js?v=0a3effb9:169:22
_function@https://githubrnqxck-hrac--3000--d3416dfd.local-corp.webcontainer.io/_nuxt/node_modules/hookable/dist/index.mjs?v=0a3effb9:133:14
serialTaskCaller/
run@https://githubrnqxck-hrac--3000--d3416dfd.local-corp.webcontainer.io/_nuxt/node_modules/hookable/dist/index.mjs?v=0a3effb9:41:43
serialTaskCaller/
promise callback*serialTaskCaller/<@https://githubrnqxck-hrac--3000--d3416dfd.local-corp.webcontainer.io/_nuxt/node_modules/hookable/dist/index.mjs?v=0a3effb9:48:40
serialTaskCaller@https://githubrnqxck-hrac--3000--d3416dfd.local-corp.webcontainer.io/_nuxt/node_modules/hookable/dist/index.mjs?v=0a3effb9:47:16
callHookWith@https://githubrnqxck-hrac--3000--d3416dfd.local-corp.webcontainer.io/_nuxt/node_modules/hookable/dist/index.mjs?v=0a3effb9:198:26
callHook@https://githubrnqxck-hrac--3000--d3416dfd.local-corp.webcontainer.io/_nuxt/node_modules/hookable/dist/index.mjs?v=0a3effb9:187:17
initApp@https://githubrnqxck-hrac--3000--d3416dfd.local-corp.webcontainer.io/_nuxt/home/projects/github-rnqxck/node_modules/nuxt/dist/app/entry.js:52:24
async*@https://githubrnqxck-hrac--3000--d3416dfd.local-corp.webcontainer.io/_nuxt/home/projects/github-rnqxck/node_modules/nuxt/dist/app/entry.js:64:19
```

**Comment by danielroe** [comment]
I'd be very happy for a PR to fix this. Moving the code that depends on it to after all modules are initialised would be the best fix. Layers won't reproduce the issue as they are evaluated before Nuxt is loaded.
