### ISSUE TITLE
allow passing props directly to page via `<NuxtPage>`

### ISSUE THREAD

**Issue by mebest100** [nuxt/nuxt#24670]
### Describe the feature

I'm trying migrate my vue3 project to nuxt3, but find many problems.
Just as below codes, nuxtPage cannot get its rendering component, but the router-view has such api to achieve it. 

```
    <router-view :style="viewStyle" v-slot="{ Component }">
      <component :is="Component" />
    </router-view>
    <router-view :style="viewStyle" name="user" v-slot="{ Component }">
      <transition appear name="slide">
        <component :is="Component" />
      </transition>
    </router-view> 
```
In nuxt3 I cannot use nuxtPage to achieve the same effect of above codes.
Seems NuxtPage neither  get its rendering component  nor add addtional style to its rendering component .
Hence need NuxtPage to get its rendering component to achieve the dynamic component feature in vue3. Thx!

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
What would you need the `Component` for? 
You could wrap the transition component around the `NuxtPage` component *or* use page/layout transitions straight away. ☺️

**Comment by mebest100** [comment]
But  as below codes I eactly need to get its rendering component from nextPage to bind props data to the endering component.

```
  <router-view v-slot="{Component}">
      <transition appear name="slide">
        <component :is="Component" :data="selectedAlbum"/>
      </transition>
    </router-view>
```
If nuxtPage have no such api for getting its rendering component , how can achieve the purpose of binding data to the rendering component which as child component and accept the binding data passed by its parent component

**Comment by idorenyinudoh** [comment]
with the `NuxtPage` component, you can pass custom data via custom props. hence, you wouldn't need the `Transition` component if you don't specifically want to apply transitions to the rendered pages.

from your vue3 example, this is how the implementation will look like in nuxt:

```vue
<NuxtPage :data="actualData" />
```

hence, to use the data in a specific page, you can use `$attrs.data` in the page's template or `useAttrs().data` in `<script setup>`.

[reference](https://nuxt.com/docs/api/components/nuxt-page#custom-props)
