### ISSUE TITLE
Improve callWithNuxt DX

### ISSUE THREAD

**Issue by daniluk4000** [nuxt/nuxt#24681]
### Describe the feature

Despine asyncContext feature it is still required sometimes to use callWithNuxt. 

I would like those composables to be present for better DX:
- callWithNuxtSync. Current callWithNuxt uses callAsync on SSR, but sometimes we don't need such stuff here
- tryUseNuxtApp. Not all our SSR composables require nuxt app to be present, so we don't need it's call to crash everything

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by daniluk4000** [comment]
@danielroe & Nuxt Team, if you like this idea I would love to make a PR with new methods, documentation & tests (if needed) update.

**Comment by danielroe** [comment]
We think `tryUseNuxtApp` is a good idea (as an alias for `tryUse` access via unctx) but for `callWithNuxtSync`, our desired future direction is via async context which _requires_ being in a Promise situation.

**Comment by daniluk4000** [comment]
We actually had to implement `callWithNuxtSync` on our side for `useHead`. Currently it is the only case I have found for this composable.

useHead does not accept promise, and we need to use Nuxt's composables in some of the pages here. Loss of reactivity cannot be a solution here, so we needed sync context.

**Comment by daniluk4000** [comment]
Finally got time to implement this.

@danielroe I'm not implementing sync function, yet the case I described above is still there. But I can agree it's very rare.

@harlan-zw what do you think about that? Basically we have veery rare case, when we make our initial setup of useMeta via Nuxt Plugin where we pass function for use meta and use `useRoute` inside of it, therefore require Nuxt Context. We also can't use async for meta value. 

If someone will need sync function I have a workaround:

```typescript
import type { NuxtApp } from 'nuxt/app';
import { getContext } from 'unctx';

export const nuxtAppContext = getContext<NuxtApp>('nuxt-app', {
    asyncContext: !!process.env.NUXT_ASYNC_CONTEXT && process.server,
});

export function callWithNuxtSync<T extends (...args: any[]) => any>(nuxt: NuxtApp, setup: T, args?: Parameters<T>): ReturnType<T> {
    return nuxtAppContext.call(nuxt, args ? () => setup(args) : setup);
}

```
