### ISSUE TITLE
IFrame style and script leak to parent page

### ISSUE THREAD

**Issue by CMTV** [nuxt/nuxt#24689]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools, pages
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt3-iframe-leak

### Describe the bug

In my `index.vue` page I create an `iframe` element, which is rendering my `iframe.vue` page:

```vue
// index.vue

<template>
  <div>This is index page content!</div>
  <iframe src="/iframe"></iframe>
</template>
```

```vue
// iframe.vue

<script setup>
  console.log('Hello World inside iframe!');
</script>

<template>This is iframe content.</template>

<style>
* {
  color: red;
}
</style>
```

The problem is that both style and script leak from iframe to parent page (`index.vue`).
All elements are red and I also see message in console log.

How to prevent iframe from applying styles and script to parent page?

Here is a working [example][1] on Stackblitz.

[![enter image description here][2]][2]

  [1]: https://stackblitz.com/edit/nuxt3-iframe-leak
  [2]: https://i.stack.imgur.com/CNH39.gif

### Additional context

I am trying to create an editor. Heavy work is done in worker and the rendered result I want to send to iframe and set content.

**Comment by manniL** [comment]
This is how normal CSS styles work. See more in https://github.com/nuxt/nuxt/issues/22817#issuecomment-1849081202

**Comment by CMTV** [comment]
@woldtwerk I fully agree that it is indeed a bug. Nothing from iframe must not leak to parent page. So the only solution I found is to create a separate Nuxt app just for my iframe preview.

**Comment by woldtwerk** [comment]
that's a bummer. Was building a little Website builder in an iframe.
That behavior must have been explicitly implemented to behave like this.
Would like to know why this would be desireable.

**Comment by woldtwerk** [comment]
> that's a bummer. Was building a little Website builder in an iframe. That behavior must have been explicitly implemented to behave like this. Would like to know why this would be desireable.

I'm confused.  Suddenly it's working

**Comment by woldtwerk** [comment]
@danielroe @manniL
as promised a new reproduction: https://stackblitz.com/edit/github-buv7dk?file=pages%2Fchild.vue,pages%2Findex.vue,components%2FFoo.vue

I think it's a dev only issue

**Comment by woldtwerk** [comment]
> I think it's a dev only issue

on the other hand I'm pretty sure I tried production build also last time around 🤷

**Comment by danielroe** [comment]
Thanks for prepping. This is pure Vite behaviour, not Nuxt; if you then remove the iframe from the home page you'll _still_ see the CSS included. In general you shouldn't rely on CSS _not_ to be bundled; Vite might well include it your main entry css file for many possible reasons. For this purpose, there's scoped CSS in Vue, or you can also use CSS modules.

**Comment by woldtwerk** [comment]
thanks for clarification
