### ISSUE TITLE
CSS asset files of other pages get loaded / merged together

### ISSUE THREAD

**Issue by MichaelRoosz** [nuxt/nuxt#24688]
### Environment

- Operating System: `Darwin`
- Node Version:     `v21.4.0`
- Nuxt Version:     `3.8.2`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `npm@10.2.4`
- Builder:          `-`
- User Config:      `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/MichaelRoosz/nuxt-example/

Changes made after "npx nuxi@latest init nuxt": https://github.com/MichaelRoosz/nuxt-example/commit/b822ab9a6582bef37817e7cdcc233d62e173a123

### Describe the bug

Given two Pages "/PageOne" (using component "TestOne") and "/PageTwo" (using component "TestTwo") the SSR code will merge all css files added to the html between different requests. For example:

After starting the server:

- load http://localhost:3000/PageOne the first time - the css asset file http://localhost:3000/_nuxt/components/TestOne.vue?vue&type=style&index=0&lang.css gets loaded

- load http://localhost:3000/PageTwo - now the css asset files http://localhost:3000/_nuxt/components/TestOne.vue?vue&type=style&index=0&lang.css and http://localhost:3000/_nuxt/components/TestTwo.vue?vue&type=style&index=0&lang.css get loaded

- load http://localhost:3000/PageOne a second time - now the css asset files http://localhost:3000/_nuxt/components/TestOne.vue?vue&type=style&index=0&lang.css and http://localhost:3000/_nuxt/components/TestTwo.vue?vue&type=style&index=0&lang.css get loaded

After some requests this will result in all the css assets files of all components getting loaded for any page - even if none of the components are used.

**Comment by manniL** [comment]
This is because of smart prefetching the links + how CSS styles that are *not scoped* work. See https://github.com/nuxt/nuxt/issues/22817#issuecomment-1849081202 for more.

**Comment by MichaelRoosz** [comment]
@manniL Are you sure about this? scoped styles would make sense to me if we were talking about single page apps and the styles merge on browser-side. However, I am talking about server-side. I can re-test with "style=scoped", but I assume it would not change anything.

**Comment by manniL** [comment]
@MichaelRoosz My bad, I've mistaken your repro to something similar to #22817 (which also targets issues with multiple styles and might be a side effect of what you described too).

The behavior described in this issue should only happen when running the dev server, right? Not in prod
