### ISSUE TITLE
Why nuxt is not same with package.json

### ISSUE THREAD

**Issue by SuleymanQ** [nuxt/nuxt#24687]
### Discussed in https://github.com/nuxt/nuxt/discussions/24686

<div type='discussions-op-text'>

<sup>Originally posted by **SuleymanQ** December 11, 2023</sup>
> ## How to downgrade nuxt in project or node_modules?

### When nuxt running shows `3.8.2`
<img width="558" alt="Screenshot 2023-12-11 at 16 49 25" src="https://github.com/nuxt/nuxt/assets/104755033/036c2a56-fa5b-4639-93e0-70ff4d2d9375">

### But my package.json is `3.2.3`
<img width="316" alt="Screenshot 2023-12-11 at 16 50 01" src="https://github.com/nuxt/nuxt/assets/104755033/8145c1e3-6b52-41f2-b6ea-a7f3cd135ac8">

</div>
```[tasklist]
### Tasks
```

**Comment by warflash** [comment]
This sounds like a package manager issue. Make sure the lockfile you're using is up to date and potentially regenerate that + reinstall your dependencies. If you want to lock nuxt to 3.2.3 you need to remove the `^` as that allows your package manager to use the latest minor release.
