### ISSUE TITLE
useFetch `error.statusMessage` doesn't work when using `server:false`

### ISSUE THREAD

**Issue by cosbgn** [nuxt/nuxt#24693]
### Environment

nuxt3 latest 

### Reproduction

https://edgenu.vercel.app
https://github.com/cosbgn/edgenu/blob/main/pages/index.vue

### Describe the bug

In development `error.statusMessage` (from useFetch) works perfectly. However when I deploy nothing shows up. This happens only when I use `server:false`. With `server:true` It works as expected.

**Comment by manniL** [comment]
When using `server: false`, the message is under `error.data.statusMessage`

**Comment by cosbgn** [comment]
Shouldn't it be the same on localhost and production?

**Comment by manniL** [comment]
Ideally yes, but I suppose depending on the platform, error handling might be different. `error.data` should be consistent though.

**Comment by cosbgn** [comment]
Ok I'll stick to error.data then. Thanks for the clarification.
