### ISSUE TITLE
Nuxt inversify - breaking changes between nuxt 3.6.5 and 3.7.0 (ERROR  Unexpected character '@' (8:0) ERROR: Parameter decorators only work when experimental decorators are enabled)

### ISSUE THREAD

**Issue by WojciechxFalkowski** [nuxt/nuxt#24691]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.14.2
- Nuxt Version:     3.7.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.5.0
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Here I created simple reproduction of my issue.
https://stackblitz.com/edit/nuxt-starter-inversify

### Describe the bug

Hi,
I am not able to upgrade to the newest version of nuxt (3.8.2). I found that the breaking changes were made in nuxt 3.7.0 (in 3.6.5 still working). There is a issues using inversify decorators with nuxt. I tried it with newest vite + vue + inversify project and everything worked fine - maybe I created inversify container in a bad place but ealier it was working. I created enviroment on stackblitz which you can check - https://stackblitz.com/edit/nuxt-starter-inversify?file=README.md. There is simple inversify container in plugin directory and the error message looks like this: 
![image](https://github.com/nuxt/nuxt/assets/49166265/3fa60691-1ebd-4b10-995e-68273ad626fc)
I have only created plugin directory with file inside of it, added 2 depenencies: "inversify": "^6.0.2", "reflect-metadata": "^0.1.14" and in tsconfig.ts I added property   "compilerOptions": {"target": "ES2020", "experimentalDecorators": true, "moduleResolution": "bundler"},

As far as I remember I created container in plugins because I wanted to use injections in SSR so if you have other solution for that please let me know. About myy main project - it is written in nuxt 3.2.3 and I could only upgrade nuxt to version 3.6.5.

### Additional context
It looks like that other people have / had similiar issues:
 https://github.com/nuxt/nuxt/issues/21756#issuecomment-1704892777
 https://github.com/nuxt/test-utils/issues/540#issue-2021760322 - in my case it is not working
 https://github.com/nuxt/nuxt/issues/21756#issuecomment-1846568373 - for me only worked option number 2 but I am not sure if it is a good way - please let me know if the ticket should be closed.
_No response_

### Logs

```shell-script
ERROR  Unexpected character '@' (8:0)
ERROR: Parameter decorators only work when experimental decorators are enabled
```

**Comment by danielroe** [comment]
My guess is that the issue here was triggered by a vite upgrade between those versions rather than a Nuxt change.

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/14126
