### ISSUE TITLE
Add `getCachedData` to `useFetch` and `useAsyncData` docs

### ISSUE THREAD

**Issue by luc122c** [nuxt/nuxt#24694]
### Describe the feature

The docs pages for [useFetch](https://nuxt.com/docs/api/composables/use-fetch#params) and [useAsyncData](https://nuxt.com/docs/api/composables/use-async-data#params) are missing the `getCachedData` parameter. 

I'll open a PR to add it to the docs. I would also like to add a link to the [Client-side Caching with getCachedData](https://youtu.be/aQPR0xn-MMk) example by @manniL if that's OK?

Related: https://github.com/nuxt/nuxt/issues/24271

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
That would be great! 🙏
