### ISSUE TITLE
ssr typecheck error

### ISSUE THREAD

**Issue by PhE** [nuxt/nuxt#24698]
### Environment

- Operating System: Linux
- Node Version:     v18.13.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  bun@1.0.6
- Builder:          -
- User Config:      components, devtools, extends, modules, ui, fontMetrics, googleFonts, routeRules, runtimeConfig, supabase, telemetry, typescript, vite
- Runtime Modules:  @nuxt/content@2.9.0, @nuxt/ui@2.11.0, @nuxtjs/fontaine@0.4.1, @nuxtjs/google-fonts@3.1.1, @vueuse/motion/nuxt@2.0.0, @nuxtjs/supabase@1.1.4, nuxt-og-image@2.2.4
- Build Modules:    -

### Reproduction

Define a route rule with the `ssr` prop:

```javascript
export default defineNuxtConfig({
  routeRules: {
    '/profile': { ssr: false },
    '/api/search.json': { prerender: true },
  },
  // ...
}
```

Then run `nuxt typecheck` to get the error:

```
error TS2353: Object literal may only specify known properties, and 'ssr' does not exist
```

### Describe the bug

The `ssr` option in route rule raises a type error in `nuxt typecheck`.

### Additional context

Got a similar error in nuxt/content: https://github.com/nuxt/content/issues/2459

### Logs

```shell-script
Here is the output part of `nuxt typecheck` showing the error :


nuxt.config.ts:63:19 - error TS2353: Object literal may only specify known properties, and 'ssr' does not exist in type '{ cache?: false | { base?: string; integrity?: any; name?: string; group?: string; swr?: boolean; maxAge?: number; staleMaxAge?: number; headersOnly?: boolean; varies?: string[]; }; headers?: { [x: string]: string; }; ... 8 more ...; ogImage?: false | { ...; }; }'.

63     '/profile': { ssr: false },
                     ~~~

  node_modules/@nuxt/schema/dist/index.d.ts:1220:80
    1220 type DeepPartial<T> = T extends Function ? T : T extends Record<string, any> ? {
                                                                                        ~
    1221     [P in keyof T]?: DeepPartial<T[P]>;
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1222 } : T;
         ~
    The expected type comes from property '/profile' which is declared here on type '{ [x: string]: { cache?: false | { base?: string; integrity?: any; name?: string; group?: string; swr?: boolean; maxAge?: number; staleMaxAge?: number; headersOnly?: boolean; varies?: string[]; }; headers?: { [x: string]: string; }; ... 8 more ...; ogImage?: false | { ...; }; }; }'
```
```

**Comment by danielroe** [comment]
Seems to be working fine for me: https://stackblitz.com/edit/github-5lnamp?file=nuxt.config.ts,package.json.

I would guess you have maybe duplicate installs of some Nuxt/Nitro dependencies that are fooling TypeScript.

**Comment by PhE** [comment]
Fixed.
@danielroe thanks for the hint !

We use bun, something went wrong with `bun.lockb` :
```shell
rm -Rf node_modules bun.lockb .nuxt
npx nuxt typecheck
```
