### ISSUE TITLE
building with prisma causes this error on preview: Uncaught TypeError: The specifier “.prisma/client/index-browser” was a bare specifier, but was not remapped to anything. Relative module specifiers must start with “./”, “../” or “/”.

### ISSUE THREAD

**Issue by BlackoutGG** [nuxt/nuxt#24690]
### Environment

Operating System: Linux
- Node Version:     v20.9.0
- Nuxt Version:     3.8.1
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      imports, modules, snackbar, css, build, io, discord, auth, vite
- Runtime Modules:  (), nuxt-snackbar@1.0.4, nuxt-icon@0.4.2, @sidebase/nuxt-auth@0.5.0, nuxt-lodash@2.5.3, @pinia/nuxt@0.4.11
- Build Modules:    -

### Reproduction

integrate prisma into your app like the following:
```
/service/prisma
import { PrismaClient } from "@prisma/client";

const prismaClientSingleton = () => {
  return new PrismaClient();
};

type PrismaClientSingleton = ReturnType<typeof prismaClientSingleton>;

const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClientSingleton | undefined;
};

export const prisma = globalForPrisma.prisma ?? prismaClientSingleton();

if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;

```

Now import into an module you plan on using it in like so:

```
import { prisma } from "~/services/prisma

//do stuff with prisma
```

### Describe the bug

After build and the during preview, the client doesn't seem to hydrate properly because it's interrupted by the following error:

```
Uncaught TypeError: The specifier “.prisma/client/index-browser” was a bare specifier, but was not remapped to anything. Relative module specifiers must start with “./”, “../” or “/”.
```
I'm using enums from prisma so could this be the problem?

**Comment by BlackoutGG** [comment]
> Would you be able to provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
> More info

It's kinda hard to provide a reproduction due to the size and scope of the project. I will add that during npx nuxi build I also get this:

```
.prisma/client/index-browser" is imported by ".prisma/client/index-browser?commonjs-external", but could not be resolved – treating it as an external dependency.
```

**Comment by 3201623169** [comment]
It is a vite build issue, add vite config to your defineNuxtConfig will fix it, like this:
defineNuxtConfig({
  vite: {
    ssr: {
      external: ["@prisma/client"]
    },
    resolve: {
      alias: {
        ".prisma/client/index-browser": "./node_modules/.prisma/client/index-browser.js"
      }
    }
  }
})

**Comment by wjdp** [comment]
Is the above solution still current @mateow1192 ?

I'm attempting to use it but running into issues where the object containing my client is undefined on prod builds. See https://github.com/prisma/nuxt-prisma/issues/86
