### ISSUE TITLE
Using http-proxy-middleware with asyncContext causes memory leak

### ISSUE THREAD

**Issue by daniluk4000** [nuxt/nuxt#24699]
### Environment

- Operating System: Linux
- Node Version:     v20.10.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, experimental
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://github.com/daniluk4000/nuxt3-proxy-leak

1. Install deps with `yarn` command
2. Execute `yarn build && yarn start`
3. Open inspector, proceed to memory page
4. Take a snapshot
5. Make tons of request to proxy /api/ok, for example, `siege -c 10 http://localhost:3000/api/ok`
6. Take another snapshot
7. Disable asyncContext: true and repeat steps 2-6

With asyncContext (30k req):
![image](https://github.com/nuxt/nuxt/assets/10450717/c2f93150-c3a2-433b-94bd-5f7bea44fec4)

Without asyncContext GC works **much** better, it's not even comparable:
![image](https://github.com/nuxt/nuxt/assets/10450717/c7e80247-274f-41ea-9632-fa5f22c0ecfb)

### Describe the bug

When you try to use both http-proxy-middleware (in Nitro handler) and asyncContext you get a memory leak. 

You can find many `__unctx_async_handlers__` inside memory profiler

![image](https://github.com/nuxt/nuxt/assets/10450717/1b27ce71-7a10-4d24-8039-8e20c79e70fc)

### Additional context

1. I was only able to reproduce memory leak with http-proxy-middleware
2. I have no idea what inside of http-proxy-middleware causes the leak
3. Leak is only there when using asyncContext
4. I'm not sure this issue belongs to Nuxt, unctx or Nitro so I brought it there
5. We will **try** to switch to Nitro's routeRules, those doesn't cause the leak

Yet I still think that http-proxy-middleware is more powerful than Nitro's routeRules since it has much more options. Also I think solving this can prevent some other possible memory leaks.

**Comment by GalacticHypernova** [comment]
For starters, you're using a couple of questionable practices. 
In stead of checking if !proxyServer you can set it just before the defined event handler. 
You can also alternatively set it as a middleware either in the middleware folder or in the request middleware in object syntax event handler.
While it may not fix the issue, it will at least make it easier to determine the root cause, because considering this module isn't specifically crafted for nuxt and the last publish was 2 years ago, it may just be a faulty package.

**Comment by daniluk4000** [comment]
@GalacticHypernova 

> In stead of checking if !proxyServer you can set it just before the defined event handler.

Sorry, this got from other code when we have more than one of that, defined by config. We've created our simple equivalent of Nuxt 2 module and that check got from there haha, since we had to call useRuntimeConfig and only then define middleware.

> You can also alternatively set it as a middleware either in the middleware folder or in the request middleware in object syntax event handler.

Nah, we use those for proxying request to some backend services, those has to be nitro modules (catch-all route), or server middlewares as they were called in Nuxt 2.

> it may just be a faulty package

Agreed, but it has 13-14 million weekly downloads. We choose this for Nuxt 3 because in Nuxt 2 we used [Proxy Module](https://github.com/nuxt-community/proxy-module). Also interesting point for me is to find out WHAT exactly causes the leak, because it's was never there in Nuxt 2 and I can't reproduce it without asyncContext. I believe this issue can potentially discover some other possible leak not directly related to this package but the one that can be reproduced even without using it.

**Comment by GalacticHypernova** [comment]
I'll see if I can find out what causes it

**Comment by GalacticHypernova** [comment]
> We chose this for Nuxt 3 because in Nuxt 2 we used [Proxy Module](https://github.com/nuxt-community/proxy-module)

Why not just use routeRules? It's also whay they officially recommend.

**Comment by daniluk4000** [comment]
> > We chose this for Nuxt 3 because in Nuxt 2 we used [Proxy Module](https://github.com/nuxt-community/proxy-module)
> 
> Why not just use routeRules? It's also whay they officially recommend.

I've described in orig post that we will try to switch, but http-proxy-middleware is still much more powerful (in meaning of features & settings). 

But since we can't use it (asyncContext is preferred) we'll try to switch to routeRules, and stay if they will satisfy our requirements, or either write our own implementation of proxy from scratch or find another lib (more modern I guess).

**Comment by GalacticHypernova** [comment]
> still much more powerful (in meaning of features & settings).

Well, let's try. We need to check both things of course, if we want to be thorough about it. I am not saying I won't try to solve this issue, just saying you should also consider using builtin features whenever possible because they're best integrated (I.e. nitro for backend)

**Comment by GalacticHypernova** [comment]
At least with the no async and yes async routeRules we could see if the issue is truly the package, which would be a step in the right direction

**Comment by daniluk4000** [comment]
> At least with the no async and yes async routeRules tests we could see if the issue is truly the package, which would be a step in the right direction

routeRules from Nitro doesn't cause the leak, Ive tested them with asyncContext as well. So it IS something inside this package for sure, that works bad with asyncContext.

**Comment by GalacticHypernova** [comment]
Alright, so at least we localized the issue to the proxy in response to async context. Allow me to read through the package really quickly.

**Comment by daniluk4000** [comment]
> By the way, have you tried opening an issue there as well?

In a lib? Nope since it works fine in pure Node, Nuxt 2 & Nuxt 3 without asyncContext. They will like say that it is Nuxt's issue.

**Comment by daniluk4000** [comment]
Nitro's proxy is not enough for me, I can't even debug it properly to be honest.

I found out Nitro uses httpxy under-the-hood, will take a look on this one. 

![image](https://github.com/nuxt/nuxt/assets/10450717/629a7c38-5fad-4234-8e2f-9bf55565e487)

**Comment by manniL** [comment]
@daniluk4000 Easiest would be a nitro middleware (or endpoint) + using `sendProxy` there. That also won't leak 😋

**Comment by daniluk4000** [comment]
For anyone who will be looking there with same problem in future.

I rewrite reproduction example to use `httpxy` from unjs and memory leak is not there anymore. httpxy is not exactly same solution though, and has less config features, but I managed to achieve what we need with it. 

Unjs saves the day once again :D
