### ISSUE TITLE
useSeoMeta 使用后meta标签的位置

### ISSUE THREAD

**Issue by xuyifeiOnly** [nuxt/nuxt#24703]
### Describe the feature

我使用了useSeoMeta来动态生成TDK，但是我发现每次meta标签都会生成在body标签下面，而不是header标签下面，这个和大部分网站的seo是不一样的，请问这个可以改善吗？
<img width="760" alt="lank retereodalesretoosr asaseript Bnsorigin hreter auctsersxax fesacunentsstudytnvtatosuapvarot" src="https://github.com/nuxt/nuxt/assets/49358706/decf31c5-1cd2-49c2-a7cd-5f7b358b411e">
![WX20231212-174626@2x](https://github.com/nuxt/nuxt/assets/49358706/64b94268-289d-40b7-a62d-8066f96251ce)

### Additional information

- [x] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by freezyh** [comment]
本地出现这种情况还是说发布到生产环境也出现这情况？如果仅仅是本地出现这行情可以忽略

**Comment by danielroe** [comment]
You can specify the position/order - see https://unhead.unjs.io/usage/guides/sorting.

I'd also suggest you try enabling `experimental.headNext` which uses the capo.js order to optimise your head order for SEO.

**Comment by xuyifeiOnly** [comment]
Thank you very much. I tried the first way to set tagPriority, but it only works when the value is set to critical. I think high has a higher priority, but it doesn't work. I don't know why

**Comment by xuyifeiOnly** [comment]
> 本地出现这种情况还是说发布到生产环境也出现这情况？如果仅仅是本地出现这行情可以忽略

发布到线上也是会出现的
