### ISSUE TITLE
> I think this is a usage issue; you're not passing through the `vueApp` injections. In Vue 3 these are not global.

### ISSUE THREAD

**Issue by robbiemie** [nuxt/nuxt#24700]
> I think this is a usage issue; you're not passing through the `vueApp` injections. In Vue 3 these are not global.
@danielroe 
Hi, This is a test code link.pls~

https://stackblitz.com/edit/github-zqj5r6?file=public%2Fcomponents%2FsubComponent.vue

_Originally posted by @robbiemie in https://github.com/nuxt/nuxt/issues/24663#issuecomment-1848891014_

**Comment by manniL** [comment]
Let's keep it in https://github.com/nuxt/nuxt/issues/24663#issuecomment-1848891014 ☺️
