### ISSUE TITLE
Issue when a prop and  a component have the same name

### ISSUE THREAD

**Issue by ThinkingAbout** [nuxt/nuxt#24712]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.10.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      modules, build, tailwindcss
- Runtime Modules:  @nuxtjs/tailwindcss@6.10.1
- Build Modules:    -
------------------------------

### Reproduction

[stackblitz](https://stackblitz.com/edit/nuxt-starter-ndjt4o?file=components%2Fcard%2Fvariant%2Findex.vue)

### Describe the bug

At a certain point I was no longer able to run one of my projects (presumably after an npm install).

I have no errors but only the following warning:
```
[Vue warn]: Vue received a Component that was made a reactive object. This can lead to unnecessary performance overhead and should be avoided by marking the component with `markRaw` or using `shallowRef` instead of `ref`.
Component that was made reactive: { title: 'Product 1', to: '/product/product-01' }
```

I noticed that by modifying the name of the prop in `components/card/variats/index.vue ` from `btn` to something else everything seems to work fine again, for example, 
from:

```
<btn :title="btn.title" :to="btn.to">
  <div>
    <p>TITLE: {{ btn.title }}</p>
    <p>LINK: {{ btn.to }}</p>
  </div>
</btn>
``` 

to:
```
<btn :title="btnData.title" :to="btnData.to">
  <div>
    <p>TITLE: {{ btnData.title }}</p>
    <p>LINK: {{ btnData.to }}</p>
  </div>
</btn>
``` 

As you can see, both the prop and the component have the same "btn" name, but this never created errors and worked until a few days ago.

Can anyone help me?
Thanks,
Matteo

**Comment by manniL** [comment]
This is normal when using `script setup` as variables can be used as components (think of render functions like `() => h('div')`). You rather want to use the `PascalCase` name of your component (`Btn`) and **also rename it** to a two-word name like `AppButton` ☺️

**Comment by ThinkingAbout** [comment]
Hi @manniL, thanks for the reply 🫶 I'll refactor things around. Just out of curiosity, the [project](https://www.mirage.it) has been online for months and has been implemented like this since day 1. Has anything changed during the last days? Thanks again!

**Comment by manniL** [comment]
@ThinkingAbout No problem! Hmm, hard to tell. you could pinpoint it by pinning the version to an older one and check (same for Vue) but I have no obvious guess in mind.
