### ISSUE TITLE
Nuxt can't start the app in production on windows

### ISSUE THREAD

**Issue by GalacticHypernova** [nuxt/nuxt#24716]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.8.0
- CLI Version:      3.10.0
- Nitro Version:    2.7.2
- Package Manager:  npm@9.6.5
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

1. Create a new project using `npx nuxi@latest init NuxtTest` (doesn't matter which package manager)
2. Build the app
3. Run the app
4. Go to localhost:3000
5. Receive error

For reference:
https://github.com/GalacticHypernova/NuxtFailTest

### Describe the bug

There appears to be an issue with the `server-renderer` module not being found which causes any project (even just the starter template with no change whatsoever) to instantly break on production.

### Additional context

The template in https://nuxt.new works fine, so I'm guessing it's a Windows only issue.

### Logs

```shell-script
[nuxt] [request error] [unhandled] [500] Cannot find module 'NuxtFailTest\.output\server\node_modules\vue\server-renderer\index.mjs' imported from \NuxtFailTest\.output\server\chunks\handlers\renderer.mjs
  at new NodeError (node:internal/errors:399:5)
  at finalizeResolution (node:internal/modules/esm/resolve:326:11)
  at moduleResolve (node:internal/modules/esm/resolve:945:10)
  at defaultResolve (node:internal/modules/esm/resolve:1153:11)
  at nextResolve (node:internal/modules/esm/loader:163:28)
  at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
  at link (node:internal/modules/esm/module_job:76:36)
```

**Comment by manniL** [comment]
Can't reproduce on my Windows machine
![image](https://github.com/nuxt/nuxt/assets/640208/c31ecb1d-4042-41d5-beef-2a7e01511603)
![image](https://github.com/nuxt/nuxt/assets/640208/fba690d5-d7d8-400a-a174-a57e13aea3e3)

Maybe https://github.com/nuxt/nuxt/issues/19129 is a related issue?

**Comment by GalacticHypernova** [comment]
> Maybe #19129 is a related issue?

Doesn't seem like it, I have vue 3.
I can screen record this occuring if needed. From what I saw you're running this on either macos or linux, based on the terminal style (unless it's a custom theme for windows command prompt). If you try to run the server from windows and check any browser it errors (tested both chrome and edge).

**Comment by manniL** [comment]
>  From what I saw you're running this on either macos or linux, based on the terminal style

No no, this is the windows git bash 😋

**Comment by GalacticHypernova** [comment]
What if you do it from cmd? I probably forgot to specify, I haven't tested on PS.

**Comment by manniL** [comment]
> What if you do it from cmd? I probably forgot to specify, I haven't tested on PS.

Same working result.

**Comment by aaharu** [comment]
I think that you probably did not run `node .output/server/index.mjs`, but ran `nuxt dev`.
listhen v1.5.5's dev server has a problem that does not work properly on Windows.
https://github.com/unjs/listhen/pull/142

**Comment by GalacticHypernova** [comment]
@aaharu No, in dev it actually works. Only production isn't as I said.

**Comment by aaharu** [comment]
@GalacticHypernova Sorry, I missed the "on production".
But I have tested [GalacticHypernova/NuxtFailTest](https://github.com/GalacticHypernova/NuxtFailTest) and it seems to work fine on Windows, whether cmd or ps.

**Comment by GalacticHypernova** [comment]
> But I have tested [GalacticHypernova/NuxtFailTest](https://github.com/GalacticHypernova/NuxtFailTest) and it seems to work fine on Windows, whether cmd or ps.

So am I actually the only one with this issue? It doesn't seem extremely likely, I started a brand new project from the nuxi starter so it's not even a code issue. What could it be?

**Comment by GalacticHypernova** [comment]
@manniL how come yours is building correctly with my project but mine doesn't? It doesn't make any sense

**Comment by manniL** [comment]
> @manniL how come yours is building correctly with my project but mine doesn't? It doesn't make any sense

Yeah, now the fun debugging begins 🙈 
Clear global caches (e.g. from npm)
Ensure you have the last version of all (e.g. update nitro)

**Comment by GalacticHypernova** [comment]
> What is in `.output/server/node_modules/vue/server-renderer`? 🤔

Those're the contents of the vue folder in the server node_modules:
![image](https://github.com/nuxt/nuxt/assets/92037085/6c7b07b8-9fcd-4606-b98e-14a6a326a8ca)

**Comment by jimhucksly** [comment]
i have same error.    
folder node_modules/vue/server-renderer don't generated with node v18.

**Comment by jimhucksly** [comment]
need import from '@vue/server-renderer'

**Comment by GalacticHypernova** [comment]
To anyone who may receive this error in the future:
Sometimes this happens due to misconfigured global packages (usually inside the %USERPROFILE% path). Removing everything related to node modules and your package manager would fix it. (Did for me).
A good way to know if you're affected is by seeing a .nuxtrc file inside that path if you haven't initiated a project there.

**Comment by Nytveit** [comment]
@jimhucksly Did you fix this? Where did you import from  '@vue/server-renderer'?
