### ISSUE TITLE
Cannot use v8 or istanbul for coverage with @nuxt/test-utils

### ISSUE THREAD

**Issue by nethriis** [nuxt/nuxt#24710]
### Environment

Nuxt project info:                                                                                                 15:05:56

------------------------------
- Operating System: Windows_NT
- Node Version:     v21.3.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      devtools, css, modules, postcss, pinia
- Runtime Modules:  nuxt-icon@0.6.7, @pinia/nuxt@0.5.1, @vueuse/nuxt@10.7.0
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-hutksq?file=package.json

### Describe the bug

When I run:
```bash
npx vitest run --coverage
```

I have the message that ask me if I want to install v8 (✔ Do you want to install @vitest/coverage-v8?)
And after that I receive the error :
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: vitest@0.33.0
npm ERR! node_modules/vitest
npm ERR!   dev vitest@"^0.33.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vitest@"^1.0.0" from @vitest/coverage-v8@1.0.4
npm ERR! node_modules/@vitest/coverage-v8
npm ERR!   dev @vitest/coverage-v8@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /home/.npm/_logs/2023-12-12T14_11_48_769Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2023-12-12T14_11_48_769Z-debug-0.log

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: Command failed with exit code 1: npm install -D @vitest/coverage-v8
    at makeError$1 (/home/projects/nuxt-starter-hutksq/node_modules/vitest/dist/chunk-install-pkg.23da664c.js:993:11)
    at handlePromise (/home/projects/nuxt-starter-hutksq/node_modules/vitest/dist/chunk-install-pkg.23da664c.js:1529:35) {
  shortMessage: 'Command failed with exit code 1: npm install -D @vitest/coverage-v8',
  command: 'npm install -D @vitest/coverage-v8',
  escapedCommand: 'npm install -D "@vitest/coverage-v8"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

Why nuxt test utils do not use vitest >= 1.0.0

**Comment by danielroe** [comment]
I believe this is already fixed in the latest main branch - would you check https://github.com/nuxt/test-utils/issues/644 and report an issue in https://github.com/nuxt/test-utils if you encounter any issues? 🙏

**Comment by nethriis** [comment]
This is not fixed in the latest main branch

**Comment by danielroe** [comment]
Are you sure?

https://stackblitz.com/edit/nuxt-starter-azmgaz?file=package.json,some-file.test.ts

**Comment by nethriis** [comment]
Oh with nightly version ok

**Comment by danielroe** [comment]
Yes, that's what reflects the main branch. It should also be fine with the alpha release I linked to 👌
