### ISSUE TITLE
If there are properties in a combination function that are functions, then when using it, you may encounter this problem:Cannot stringify a function

### ISSUE THREAD

**Issue by FatNerdPeng** [nuxt/nuxt#24727]
### Environment

nuxt: v3.8.2

### Reproduction

https://stackblitz.com/edit/nuxt-starter-nhel2m

### Describe the bug

Hello team.
I wrote a combinatorial function, which is roughly like this:
![FWNG}2 FVII65T` NT_6QPK](https://github.com/nuxt/nuxt/assets/33616855/c391a82c-b38f-41bc-874d-a477b23a0ed7)

When I call my custom combination function on 'pages/index.vue', it will report the following error:
![JNO@213~K6}JAWCYR~6YL(E](https://github.com/nuxt/nuxt/assets/33616855/1a7b208d-0d19-4f65-b70b-27a8096e0023)
![$0AU$GD{(73IJ1L78 VL{CS](https://github.com/nuxt/nuxt/assets/33616855/69de0484-e43e-4423-886f-b6ebd9667209)

As long as I don't use it on this page, or rather, I use it under the component, there won't be this problem:
![89`P}BKRXGR }GD(K7CMMEC](https://github.com/nuxt/nuxt/assets/33616855/0c98a158-0c74-443a-a02c-a70f36964c0e)
![G6U1M)3IPJ5)1{_Z90XU4B9](https://github.com/nuxt/nuxt/assets/33616855/420222f8-e6f9-4514-84f0-7ead1ffeb295)

which makes me very confused. I don't know why this is happening.Perhaps you may wonder why I didn't write 'menus' and 'content' separately in two different 'useState()' functions to solve this problem. Please note that this is just a very simple example. In fact, my business requirements do not allow me to do so, or in other words, I did not know that this problem would occur at the beginning, so I have written a lot of code. I hope to understand the principle of this problem and let me solve it without changing too much code.
Thanks!

**Comment by manniL** [comment]
Content of `useState` must be serializable because it is saved as JSON and transferred when doing SSR.
Hence, saving functions will be pretty tricky I'm afraid.

You might want to check custom revivers (https://github.com/nuxt/nuxt/pull/19205) or refrain from saving non-serializable state ☺️
