### ISSUE TITLE
v-bind:class isn't reactive on page load

### ISSUE THREAD

**Issue by gezzasa** [nuxt/nuxt#24723]
### Environment

- Operating System: Darwin
- Node Version:     v18.18.2
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  npm@9.8.1
- Builder:          -
- User Config:      devtools, modules, srcDir, css, vite, app, eslint, stylelint, gtag, image
- Runtime Modules:  @nuxtjs/eslint-module@4.1.0, @nuxtjs/stylelint-module@5.1.0, @nuxt/image@1.1.0, nuxt-icon@0.6.6, nuxt-gtag@1.1.1
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-hqpmmt?file=app.vue

### Describe the bug

To reproduce, click on one of the two links. This should turn the link colour to pink. Then refresh the playground browser (not the whole browser)

Expected: The link should have a class of `active` and be pink

Actual: The link doesn't have the class of `active` but the value is true. Also causes the link to no receive the `active` class when clicked again after reload

**Comment by manniL** [comment]
The fragment part, also known as hash, is never transferred to the server by the browser. Hence, you can't use it to achieve what you want.

This is not a Nuxt issue but intended by the spec.

**Comment by gezzasa** [comment]
I feel this was closed prematurely. The computed value resolves during the hydration phase.

1. Click a link, this makes it active
2. Reload the play area, not the whole browser
3. Check the value printed in the play area, the boolean is true but the active class isn't added to the anchor

This value is reactive and should work. The value is true after the hydration phase so SSR doesn't have anything to do with it.

This causes another bug when clicking the link that should be active doesn't give it the active class since the value is already true after hydration. Please have another look.

**Comment by manniL** [comment]
> The computed value resolves during the hydration phase.

Sadly not. If you check the condition on the server and client-side, you will receive a hydration error because server and client state are not matching, breaking parts or the rest of the application. From that point on, you can't do much.

![image](https://github.com/nuxt/nuxt/assets/640208/34bc7b7b-57ff-4cba-9449-20811d49569a)


> This value is reactive and should work.

Yes, if you check it only on the client side it does (and will)

**Comment by gezzasa** [comment]
Ah okay thank you for the explanation. I will find a different way to render this link as active.
