### ISSUE TITLE
More support for nested route

### ISSUE THREAD

**Issue by gyhyfj** [nuxt/nuxt#24720]
### Describe the feature

In `nuxt 3.8.2`, if I want to create two nested route like `/parent/a` and `/parent/b`, I need to organize these three `.vue` file like this:
```
\pages
    \parent
        a.vue
        b.vue
    parent.vue
```
then add `<NuxtPage />` into `parent.vue` as `<RouterView>`, and add redirect rule in `parent.vue`:
```ts
definePageMeta({
  redirect: '/parent/a',
})
```
It work well.

---

But if I place these three files as the following structure:
```
\pages
    \parent
        index.vue
        a.vue
        b.vue
```
this `index.vue` couldn't be execute or render.
But I think it's a better way to origainze nasted file, especially when the neste rule is complex. 

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
This is by design. It's how we've chosen to arrange nested routes, because it's also possible to have _parallel_ routes, as in the second example - and that's what we prefer to make the default.
