### ISSUE TITLE
life cycle hook of onMounted does not work on nuxt3

### ISSUE THREAD

**Issue by mebest100** [nuxt/nuxt#24729]
### Environment

------------------------------
- Operating System: Windows 7 x64
- Node Version:     v18.19.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.21
- Builder:          -
- User Config:      devtools, css, vite, build, modules, proxy, devServer
- Runtime Modules:  nuxt-proxy-request@1.7.0
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/~/github.com/mebest100/nuxt-Vue3Music

### Describe the bug

I'm migrating vue3 to nuxt3  but find  the life cycle hook of onMounted does not work on nuxt3.
You can find Reproduction link to check it.

For the root route(app.vue, path: / ), I place a console.log state in onMounted, but no any ouput in cmd console and chrome console.
```
onMounted(() => {
      console.log("app mounted。。。");
    });
```
also with another route: (parent.vue, path: /parent),  still no any output for it.

Seems onMounted does not work on nuxt3 at all. 
Pls help check it. Thx!

**Comment by manniL** [comment]
Hey! I can't reproduce this in a [plain nuxt app](https://stackblitz.com/edit/nuxt-issues-24729?file=app.vue) ☺️

Could you kindly provide a [minimal reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by mebest100** [comment]
But could you pls take a try for my reproduce-below:
https://stackblitz.com/~/github.com/mebest100/nuxt-Vue3Music

because the issue will take place in specfic env but not for minimal env.
And onMounted as a basic api shall not be affected by different env.

**Comment by manniL** [comment]
@mebest100 I'm afraid providing a full project is no reproduction. The issue could be easily in the userland.

Feel free to boil it down to isolate the error with as little code (no unrelated logic, no additional configuration etc. etc.) as possible.

**Comment by madebyfabian** [comment]
Can be closed due to no reproduction provided
