### ISSUE TITLE
Nuxt fails to load runtimeConfig in static Storybook build

### ISSUE THREAD

**Issue by filiphazardous** [nuxt/nuxt#24724]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.2
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.10.5
- Builder:          -
- User Config:      devtools, components, modules, runtimeConfig, app
- Runtime Modules:  @nuxtjs/storybook@7.0.0
- Build Modules:    -
------------------------------

### Reproduction

Branch named `storybook-static` on https://github.com/filiphazardous/nuxt-storybook-module-demo
Run `pnpm i` followed by `pnpm build-storybook && pnpm static-storybook` - open http://localhost:6007 and check the console.

### Describe the bug

The bug happens in the lines https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/core/templates.ts#L317-L323 (as generated by the Storybook build). `useRuntimeConfig()` on line 321 returns an empty object, which sets `appConfig` on the same line to `undefined`. When `baseURL()` on line 323 is called, the web browser throws an error.

### Additional context

Initially, I reported the bug at https://github.com/nuxt-modules/storybook/issues/458  

I'm not sure if the bug is that Nuxt by default provides an empty object as runtime config, or if the storybook addon erroneously managed to set it to an empty object.  

The problem could be avoided by adding `?.` in a couple of places to the `publicPathTemplate` - or just changing line 321 to `: 'const appConfig = useRuntimeConfig().app || {}',`

**Comment by danielroe** [comment]
This is a storybook bug: let's track in https://github.com/nuxt-modules/storybook/issues/458.
