### ISSUE TITLE
Uncaught (in promise) non-precached-url: non-precached-url :: [{"url":"/"}]

### ISSUE THREAD

**Issue by wokalek** [nuxt/nuxt#24748]
### Environment

------------------------------
- Node Version:     v21.4.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.12.1
- Builder:          -
- User Config:      telemetry, srcDir, app, extends, modules, appConfig, runtimeConfig, vite, css, postcss, colorMode, device, image, content, pwa, robots, sitemap, site
- Runtime Modules:  @nuxtjs/robots@3.0.0, @nuxtjs/color-mode@3.3.2, @nuxtjs/fontaine@0.4.1, @nuxtjs/device@3.1.1, @nuxt/content@2.8.2, @nuxt/image@1.1.0, @vueuse/nuxt@10.7.0, @vite-pwa/nuxt@0.3.5, nuxt-typed-router@3.5.0, nuxt-svgo@3.7.0, nuxt-simple-sitemap@4.1.17, nuxt-schema-org@3.2.3, nuxt-lodash@2.5.3
- Build Modules:    -

### Reproduction

Just see in console. There may be an error in the workbox.

### Describe the bug

Inside console have error:

```
workbox-cd63daf5.js:1 Uncaught (in promise) non-precached-url: non-precached-url :: [{"url":"/"}]
    at O.createHandlerBoundToURL (https://wokalek.ru/workbox-cd63daf5.js:1:13245)
    at Object.createHandlerBoundToURL (https://wokalek.ru/workbox-cd63daf5.js:1:14828)
    at https://wokalek.ru/sw.js:1:1025
    at https://wokalek.ru/sw.js:1:565
```

Appears once and does not occur a second time after the page is reloaded. But even a single appearance affects SEO.

**Comment by desaisoftwaree** [comment]
Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"https://apnabijjnes.com/200","status":404}]

**Comment by maxflex** [comment]
Had the same issue. This helped:
https://github.com/vite-pwa/nuxt/issues/53#issuecomment-1615266204

**Comment by meliceanu** [comment]
https://github.com/vite-pwa/vite-plugin-pwa/issues/731
