### ISSUE TITLE
Unable to dynamically add components via string

### ISSUE THREAD

**Issue by jcollazosmarino** [nuxt/nuxt#24758]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools, vue
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

You can change the v-if from true to false to see the actual rendering failing:

https://stackblitz.com/edit/nuxt-starter-gd1iaq?file=components%2FRichTextRenderer.vue

### Describe the bug

I am trying to render custom elements loaded from a CMS, example, I am trying to render responses like this:

```
<div>
  <component :is="custom-element"></component>
  <component :is="custom-accordion"></component>
</div>
```

I was expecting to be able to do this by configuring the vue runtimeCompiler to true and using something like:

```h({template: receivedHtml})```

### Additional context

On the provided example, the three first options work, the fourth one fails:

```<script setup lang="ts">
const CoolComponent = resolveComponent('CoolComponent')

const render1 = h({ template: '<span>Hellow render 1</span>' })
const render2 = h({ template:`<component :is="${CoolComponent}"></component>` })
</script>
<template>
  <div>
    <div><b>Basic test:</b> <CoolComponent></CoolComponent></div>

    <div><b>Test without components:</b> <render1></render1></div>

    <div><b>Test with component:</b> <component :is="CoolComponent"></component></div>

    <div v-if="true"><b>Broken test:</b> <render2></render2></div>
  </div>
</template>
```

### Logs

```shell-script
missing ] after element list

on esm-bundler.js
```

**Comment by danielroe** [comment]
This is not working because `const CoolComponent = resolveComponent('CoolComponent')` actually returns the component - an object.

Then, you pass that object into a string in `const render2 = h({ template: `<component :is="${CoolComponent}"></component>` })`. It renders into `<component :is="[object Object]">` which isn't valid Vue syntax.

**Comment by jcollazosmarino** [comment]
Thanks for the quick response @danielroe, if tried all the combinations I can think of, the most obvious, if I change it to `<component :is="CoolComponent">` it does not work either, it is just left empty.

**Comment by jcollazosmarino** [comment]
More context:

I've also tried vue3-runtime-template, with the same error `missing ] after element list`

Checked the api for vue component, it looks like I can pass a Component object via its "is" prop:
https://vuejs.org/api/built-in-special-elements

**Comment by jcollazosmarino** [comment]
Found correct syntax:

```
const render3 = h({ template: `<CoolComponent></CoolComponent>`, components: {CoolComponent}})
```
I was missing the "(components: {CoolComponent})" part.
