### ISSUE TITLE
`<Transition appear>` breaks click event listener

### ISSUE THREAD

**Issue by CernyMatej** [nuxt/nuxt#24754]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools, vite
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-s3ebia?file=app.vue,components%2FFullscreenBackground.vue

### Describe the bug

I was making a background for a modal component when I noticed a strange behaviour with the `<Transition />` component, specifically when the `appear` prop is set.

It seems that the click event listener on an element inside `<Transition appear>` isn't being properly handled.
Steps to reproduce:
1. open the reproduction
2. click on the semi-transparent fullscreen div
3. *nothing happens* even though it should have set its visibility to `false`

1. remove `appear` from the `<Transition>` component in `FullscreenBackground.vue`
2. repeat the same steps & now the click is properly handled

### Additional context

I've tried and I couldn't reproduce the same issue in Vue, so I assume it could be a bug in Nuxt.

_No response_

**Comment by danielroe** [comment]
Would you see if you can reproduce on https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter ? Sometimes these issues only reproduce on Vue SSR.

**Comment by CernyMatej** [comment]
Yeah, I can reproduce it there. Didn't think of trying Vue SSR. Sorry 🙈 Will report to Vue then.

**Comment by danielroe** [comment]
Linking https://github.com/nuxt/nuxt/issues/14715.
