### ISSUE TITLE
Typescript error when using the useError composable.

### ISSUE THREAD

**Issue by sangbk208** [nuxt/nuxt#24767]
### Environment

- Operating System: Darwin
- Node Version:     v18.16.1
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.21

### Describe the bug

When I use 'useError' and access the 'statusCode' property, TypeScript shows an error: 'Property 'statusCode' does not exist on type 'Error | { url: string; statusCode: number; statusMessage: string; message: string; description: string; data?: any; }'.
Property 'statusCode' does not exist on type 'Error'.

<img width="709" alt="image" src="https://github.com/nuxt/nuxt/assets/50744056/edd2e33d-3c32-4580-89ec-cce83e2368b0">

**Comment by manniL** [comment]
This is not a nuxt issue but simply how TS works.
You have to narrow down the type as it can be "any generic Error" *or* an object with values like `statusCode`.

[Example](https://www.typescriptlang.org/play?#code/C4TwDgpgBAglC8UCiAnFB7FUA+UDeAsAFBSlQCuKANgFxQDOwKAlgHYDmxZDwAhsOXoBhdABMIdVuQC2AIwgouZRv0EBZCPXq92Eniw5LS0zdt11GBziTLj6AYxZhgzdKwtM217qP68A-HS8rCBKAL7ExOL2VLwo0PZujFC8dDAA3JFEvAB0KgLCYhBZzABmABQA5PmCIuKVUGwpAJT4RlCJrPToVBA5VOjs5bk1heLNxGFAA)

[Link to the Type definition in Nuxt](https://github.com/nuxt/nuxt/blob/fe2f0e01f27845b9157ba18b2a6da12dacdc1ed6/packages/nuxt/src/app/nuxt.ts#L78-L84)
