### ISSUE TITLE
expose some route metadata at build-time

### ISSUE THREAD

**Issue by danielroe** [nuxt/nuxt#24770]
### Describe the feature

Currently `definePageMeta` is a purely runtime macro and can't be consumed by modules. But _some_ of that metadata, particularly the route metadata (`alias`, `name`, `path`), would be very useful for modules to have access to and modify at build time. For example, see https://github.com/nuxt-modules/i18n/pull/2603.

The downside here would be performance cost, and of course it would only work with static strings/arrays rather than variables or conditional assignment.

Might be worth exposing option for metadata extraction (e.g. useful for extracting component metadata), and investigate caching or sharing parsing between utilities/plugins?

It would resolve https://github.com/nuxt/nuxt/issues/24359.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by Atinux** [comment]
How do you think those metadata could be exposed to the module authors? Though hooks?

**Comment by danielroe** [comment]
It would be made available in `pages:extend`. At the moment users can _set_ some of these values there but not read them.
