### ISSUE TITLE
UseFetch with Pinia actions return null

### ISSUE THREAD

**Issue by Efcolipt** [nuxt/nuxt#24780]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.9.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.2
- Builder:          -
- User Config:      modules, $production, $development, site, routeRules, srcDir, devServer, devtools, app, nitro, vite
- Runtime Modules:  @vueuse/nuxt@10.7.0, nuxt-icons@^3.2.1, @nuxtjs/robots@^3.0.0, nuxt-simple-sitemap@^4.1.17, @pinia/nuxt@^0.5.1 
- Build Modules:    -
------------------------------

### Reproduction

App.vue

```
<script setup lang="ts">
  const { init } = useAuth();
  
  await init();
</script>
```

store Pinia actions
console.log inside actions "null null true 'idle'"

```
  async init() {
    await this.getMe();
  },

 async getMe() {
      const tokens = useTokens()


      if (tokens.value) {
        const { data, error, pending, status } = await useApi<IResponse<IUser | null>>("auth/me", {
          method: 'GET',
          cache: 'no-cache',
          key: 'get-me',
        });

        console.log(error.value, data.value, pending.value, status.value);


        if (data.value?.data) {
          this.user = data.value.data;
          this.isAuth = true;
        } else {
          // tokens.value = null;
          this.user = null;
          this.isAuth = false;
        }
      }
    },
```

useApi function

config.public.API_BASE_URL - http://localhost:3000

```
  import type { UseFetchOptions } from "nuxt/app";
  import type { IAuthTokens } from "~/types";
  import { defu } from "defu";
  
  export async function useApi<T>(
    url: string | (() => string),
    _options: UseFetchOptions<T> = {}
  ) {
    const { $reset } = useAuth();
    const tokens = useTokens();
    const config = useRuntimeConfig();
    const refreshUrl = "/auth/refresh";
  
    const defaults: UseFetchOptions<T> = {
      baseURL: config.public.API_BASE_URL,
      retryStatusCodes: [401],
      retry: 1,
  
      onRequest({ options }) {
        if (tokens.value?.accessToken) {
          options.headers = {
            ...options.headers,
            Authorization: `Bearer ${tokens.value.accessToken}`,
          };
        }
      },
  
      async onResponseError({ response }) {
        if (
          response.status === 401 &&
          ![refreshUrl].includes(response.url) &&
          tokens.value?.refreshToken
        ) {
          try {
            const data = await $fetch<IAuthTokens>(refreshUrl, {
              baseURL: config.public.API_BASE_URL,
              method: "GET",
              headers: {
                "Token-ID": String(tokens.value.tokenId),
                Authorization: `Bearer ${tokens.value.refreshToken}`,
              },
            });
  
            tokens.value = data;
          } catch (exc) {
            tokens.value = null;
            $reset();
            console.error(exc);
          }
        }
      },
    };

  const params = defu(_options, defaults);

  return await useFetch(url, params);
}
```

### Describe the bug

When I use fn getMe I got null from useFetch
Use after each reloading page
After a few seconds i'll get answere

### Additional context
  "@pinia/nuxt": "^0.5.1",
  "pinia": "^2.1.7",

_No response_

**Comment by manniL** [comment]
The issue here starts with using `useFetch` or `useAsyncData` in the pinia store IMO. You should use `$fetch`.

**Comment by Atinux** [comment]
I also think that #24787 would help, you should use `$fetch` in your pinia store like @manniL said.

Then update your `app.vue` to:

```html
<script setup lang="ts">
const { init } = useAuth();
  
await once(init)
</script>
```

In the meantime you can do:

```html
<script setup lang="ts">
const { init } = useAuth();
  
await useAsyncData(async () => {
  await init()
  return {}
})
</script>
```

**Comment by Efcolipt** [comment]
@manniL if i will use $fetch, data will fetch on server and also on client, but i need once
So if i use function once i think its will work, but if i want to have one instance for fetching data from server ?
How to create one instance for fetching data from server, useFetch or useAsyncData fetch on the server and transfer it to client

**Comment by Efcolipt** [comment]
At the moment, i just use $fetch inside pinia actions, then i wrap it in useAsyncData, i dont know it correct or not
