### ISSUE TITLE
Error: import @nuxt/bridge-edge or @nuxt/bridge bring error: Cannot read properties of undefined (reading '_version')

### ISSUE THREAD

**Issue by liyoung1874** [nuxt/nuxt#24808]
### Environment

dev

### Reproduction

https://github.com/nuxt/nuxt

### Describe the bug

![image](https://github.com/nuxt/nuxt/assets/77315337/6473a017-b139-4c42-975f-75f03485710c)
![image](https://github.com/nuxt/nuxt/assets/77315337/40317380-9fd8-448f-8d5b-f9cbe6d3e148)

### Additional context

and other 
windows11
node 18.18.2
npm 9.8.1

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
