### ISSUE TITLE
fetch data api in nuxt 3 using server 

### ISSUE THREAD

**Issue by gervasiuswisely** [nuxt/nuxt#24807]
hi guys, my name is wisely i have an issue when im using useFetch in nuxt 3 for static my usefetch is accessed  public runtime config in nuxt config so the env files are exposed in client is there a way to access private runtime config in client nuxt or is there a way to use the useFetch to fetch it on the server and then on the client i just show the data i got from the generate this is my code can u see where im wrong 

my idea is i split the useFetch in the server using private variable in nuxt config so it will fetch all data and fill the payload in dist after i npm run generate and i fill the payload with the data from usefetch server and if in the client i fill the artikelData  with the payload data 

if (process.server) {
  const { data: article } = await useFetch(endpoint, {
    headers: {
      Id: runTimeConfig.public.APP_ID,
      Secret: runTimeConfig.public.APP_SECRET,
      partner: runTimeConfig.public.PARTNER,
    },
  });
  nuxtApp.payload.data = article.value;
  artikelData = ref(nuxtApp.payload.data);
} else {
  artikelData = nuxtApp.payload.data;
}
can u help me pleaseee?? tyyy

**Comment by Efcolipt** [comment]
@gervasiuswisely in nuxt config https://nuxt.com/docs/api/composables/use-runtime-config#define-runtime-config you can set secret env

**Comment by manniL** [comment]
@gervasiuswisely You don't, hence "secret". I've [explained that a bit more in detail in my video](https://www.youtube.com/watch?v=2tKOZc3Z1dk)
