### ISSUE TITLE
 points to missing source files    

### ISSUE THREAD

**Issue by horizon188** [nuxt/nuxt#24803]
### Environment

"nuxt": "3.5.0",
node v16.17.0
### Reproduction

 WARN  Sourcemap for "D:/project/congra-online-school-student/pages/course/live/liveRoomServer.ts" points to missing source files    

### Describe the bug

 WARN  Sourcemap for "D:/project/congra-online-school-student/pages/course/live/liveRoomServer.ts" points to missing source files    

### Logs

```shell-script
WARN  Sourcemap for "D:/project/congra-online-school-student/pages/course/live/liveRoomServer.ts" points to missing source files
```

**Comment by horizon188** [comment]
> Would you be able to provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏你能提供复制品吗？🙏
> 
> More info 更多信息

Sorry, it involves trade secrets and cannot be provided

**Comment by horizon188** [comment]
Perhaps it's because the TS file cannot be placed under the pages directory

> Would you be able to provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏你能提供复制品吗？🙏
> 
> More info 更多信息

Perhaps it's because the TS file cannot be placed under the pages directory

**Comment by madebyfabian** [comment]
@horizon188 Yes the `pages` directory is for `.vue` route files only. Or `.jsx/.tsx`. But `.ts` files are not allowed. Correct me if I'm wrong @danielroe.
