### ISSUE TITLE
Nuxt Server Side Rendering (SSR) not render data to html when view source browser

### ISSUE THREAD

**Issue by hoangnx1986** [nuxt/nuxt#24804]
### Environment

Nuxt 3

### Reproduction

<script setup>
const config = useRuntimeConfig();
const url = "https://oneone/api/get-country-buy-group";

const { data, pending, error } = await useFetch(url, {
  query: { groupName: "ban_chay", getTop: 8 },
  key: "keyData",
  server: true,  
});
</script>

### Describe the bug

In NUXT 3 I use useFetch to get data from the API and display it on the Index page. The data is fully displayed to the user. But the data is not rendered on view source in the browser. So is my website an SSR server site (I have set " ssr: true" in nuxt.config.ts)

Looking forward to everyone's help

**Comment by manniL** [comment]
[Can't reproduce](https://stackblitz.com/edit/nuxt-issues-24804?file=app.vue) with a simple setup. Please provide a reproduction.

**Comment by hoangnx1986** [comment]
i found my problem. When using useFetch to call a localhost api url, the data will not be rendered in the view source. In case the localhost api is not called, the data is rendered normally. Thanks for answering :)

**Comment by manniL** [comment]
Sounds like a proxy issue ☺️ 
Happy that it works though 👍
