### ISSUE TITLE
Netlify Forms with Nuxt3

### ISSUE THREAD

**Issue by dbzx10299** [nuxt/nuxt#24816]
### Describe the feature

There is a problem using forms with netlify because it only works if the netlify build command is `npm run generate`. The problem is when `npm run generate` is used, then the regular serverless functions stop working. For the serverless functions to work `npm run build` has to be used as the netlify build command.

I tried using a route rule and setting the netlify build command to `npm run build`, but this does not work. This piece of code prerenders the contact page as expected, and the netlify functions work, but netlify is not able to pick up on the form.

```js
defineNuxtConfig({
  routeRules: {
    '/contact': { prerender: true }
  }
})
```

This is creating a problem because getting access to forms causes the serverless functions to no longer work due to the build command having to be `npm run generate` and using `npm run build` in order to use serverless functions causes the form not to work. The edge functions work either way with `npm run build` or `npm run generate`. 

We might need to leverage serverless functions though since they use a node js runtime whereas edge functions use a deno runtime.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
We likely need to add support for this in the Nitro netlify provider. Would you open an issue in https://github.com/unjs/nitro/ instead so we can track it there? 🙏

**Comment by dbzx10299** [comment]
Will do
