### ISSUE TITLE
Nuxt 3 works fine locally but goes into an infinite loop on the server

### ISSUE THREAD

**Issue by makaraman** [nuxt/nuxt#24818]
### Environment

- Operating System: Docker & Kubernetes
- Node Version:     v18.18.2
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  npm@9.8.1
- Builder:          -
- User Config:      devtools, modules, css, components, plugins, fontLoader, app, runtimeConfig, build, delayHydration
- Runtime Modules:  @nuxtjs/tailwindcss@6.10.1, @pinia/nuxt@0.5.1, nuxt-font-loader@2.3.5, nuxt-delay-hydration@1.3.3, @nuxtjs/device@3.1.1
- Build Modules:    -

### Reproduction

Here is the exact structure of the project: https://stackblitz.com/edit/github-wqqyll

### Describe the bug

![image](https://github.com/nuxt/nuxt/assets/42525116/7950f630-8d75-413e-b0ed-d293f04ebfa8)
When I launch the project on our server which is handled by Docker & K8 & Nginx then it returns incredible amount of request logs as you can see in the screenshot.

I was unable to replicate this problem using either stackblitz or locally. However, if you look closely at the stackblitz project, you can see how we utilize the Nuxt 3.

### Additional context

`package.json` file

````{
  "type": "module",
  "engines": {
    "node": "18.18.2"
  },
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare",
    "start": "node .output/server/index.mjs",
    "test": "vitest run",
    "test:watch": "vitest"
  },
  "dependencies": {
    "@nuxtjs/device": "^3.1.1",
    "@nuxtjs/tailwindcss": "^6.8.0",
    "@pinia/nuxt": "^0.5.1",
    "body-scroll-lock": "^4.0.0-beta.0",
    "click-outside-vue3": "^4.0.1",
    "consola": "^3.2.3",
    "dayjs": "^1.11.10",
    "nuxt": "^3.7.4",
    "nuxt-font-loader": "^2.3.4",
    "pinia": "^2.1.7",
    "tailwindcss": "^3.3.5",
    "vue": "^3.3.4",
    "vue-router": "^4.2.5",
    "vue-screen": "^2.3.2",
    "vue-screen-utils": "^1.0.0-beta.13"
  },
  "devDependencies": {
    "@babel/eslint-parser": "^7.22.15",
    "@nuxt/devtools": "latest",
    "eslint": "^8.54.0",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-plugin-jest": "^27.6.0",
    "eslint-plugin-nuxt": "^4.0.0",
    "eslint-plugin-vuejs-accessibility": "^2.2.0",
    "nuxt-delay-hydration": "^1.3.3",
    "prettier": "^3.1.0",
    "sass": "^1.69.4",
    "vitest": "^0.33.0"
  }
}


### Logs

_No response_

**Comment by danielroe** [comment]
I suspect this is due to your deployment layer. Possibly due to redirects or how requests are being proxied. But it is difficult to investigate without a reproduction.

**Comment by makaraman** [comment]
> I suspect this is due to your deployment layer. Possibly due to redirects or how requests are being proxied. But it is difficult to investigate without a reproduction.

Thank you for the feedback. Unfortunately, this is the most possible way to show what's happening. I'll try to deploy stackblitz example, if it works then I'll know that I need to focus on the code.

**Comment by danielroe** [comment]
If you can reproduce in a docker container, that might be a possible way to show the deployment setup in a reproducible way...

**Comment by makaraman** [comment]
`Update` It happens when we use global middleware. I applied the change on stackblitz. Now, the project operates on our server as intended when I remove the middleware. But since plugins also utilize a lot of data, we still need to load the pinia store before the project begins. Is there another way to do that ?

**Comment by makaraman** [comment]
@danielroe Finally I found the issue and reproduced on stackblitz: https://stackblitz.com/edit/github-wqqyll
When we use runtimeConfig that contains .env variable on a composable, it stucks in a loop. You can see the logs from the link. Also I tried using the runtimeConfig on a page and it returns empty variable on the server which should not be the case.

Hope the link above helps to figure out what is happening.

**Comment by makaraman** [comment]
@danielroe I found the solution.
Here is an explanation for those who get the same issue (infinite request loop or `no location found with ...`)
These are all about defining environment variables. If you send `baseUrl` empty string or `/` to `useFetch` it makes so many request for nothing which also cause no location found issue :)

So beware that you filled your baseUrl as expected. Also pay attention using `NUXT_` `NUXT_PUBLIC_` depends on the type within the .env and do not forget to fill them in the nuxt.config.js file. You can check the stackblitz project the way I've done this.
