### ISSUE TITLE
any api call works fine in dev mode but in production build returns 404

### ISSUE THREAD

**Issue by JoachimR** [nuxt/nuxt#24815]
### Environment

- Operating System: Darwin
- Node Version:     v18.12.1
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.12.1
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

1. `pnpm dlx nuxi@latest init myapp`

2. add `server/api/hello.ts` with
```typescript
export default defineEventHandler((event) => {
  return {
    hello: 'world'
  }
})
```

3. set app.vue to
```vue
<script setup lang="ts">
onMounted(async() => {
  const res = await $fetch('/api/hello')
  console.log(JSON.stringify(res, null, 4))
})
</script>

<template>
  <p>start</p>
</template>
```

4. `pnpm i && pnpm generate && pnpx serve .output/public`

5. open `localhost:3000` and check network if api call to `/api/hello` was successful

==> It is only successful on dev mode, but not in production mode

### Describe the bug

Hi, I am not sure I miss something but it seems that having a simple api on the nuxt server works in dev mode but not on a production build. I searched for anything around this but didn't find any good lead so that's why I am opening this bug. Sorry if I miss something obvious?

### Additional context

node -v
v18.12.1

**Comment by danielroe** [comment]
As you are generating the site, there is no server to return the API call.

Try running `pnpm build` instead, and launching the server with `node .output/server/index.mjs`.
