### ISSUE TITLE
Background color flashes between light and dark mode using @vueuse/nuxt

### ISSUE THREAD

**Issue by polarove** [nuxt/nuxt#24819]
### Environment

- Operating System: Windows 10
- Node Version:     v20.9.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.21
- Builder:          -
- User Config:      routeRules, devtools, css, runtimeConfig, nitro, modules, alias, vite, components
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.5, nuxt-icons@3.2.1, @unocss/nuxt@0.57.7, @element-plus/nuxt@1.0.7, @vueuse/nuxt@10.7.0, @vueuse/motion/nuxt@2.0.0, @pinia/nuxt@0.5.1, @pinia-plugin-persistedstate/nuxt@1.2.0, @nuxtjs/device@3.1.1
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-rr4shs?file=app.vue

### Describe the bug

In the dark mode && toggleDark from @vueuse/core, refresh the page, we would see the background color of the page flashes from white to black.

**Comment by polarove** [comment]
I've tried to push a htmlAttr on nitro's render:html hook
```
export default defineNitroPlugin((nitroApp) => {
	nitroApp.hooks.hook('render:html', (html, { event }) => {
		html.t
	})
})
```

**Comment by polarove** [comment]
Can someone tell me how does nuxt official site implement dark mode without flashing on refreshing?

**Comment by manniL** [comment]
Best would be to use https://github.com/nuxt-modules/color-mode for that, which also covers detection before rendering 👍

**Comment by polarove** [comment]
> Best would be to use https://github.com/nuxt-modules/color-mode for that, which also covers detection before rendering 👍

I undertood, thanks!
