### ISSUE TITLE
Custom Error Page not rendering

### ISSUE THREAD

**Issue by carbdias** [nuxt/nuxt#24810]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.18.2
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.8.1
- Builder:          -
- User Config:      srcDir, devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-qnjwye?file=src%2Fpages%2Findex.vue

### Describe the bug

Hello, this reproduction is with Nuxt 3.8.2.

The issue I've found is the following :
- When trying rendering a non existent page with a **custom Error Page** (built in the root of the project as error.vue as the documentation teaches), if I have pages folder in the root of the project too, it works fine,
However, if I put the pages folder inside a src folder and I change the nuxt.config.ts configuration to have the **srcDir: 'src'** option, the default and expected behavior of the custom Error page disappears and it gets **impossible to access it** (I've tried using composables as showError and createError directly from the homepage, creating a plugin to handle errors as the documentation shows, etc), but the only Error Page I get is the **Default Error Page** from Nuxt, which is not the one I'm looking for.

Thank you in advance,

Maybe this is a minor issue, but I believe many developers can encounter it.

Thank you,

**Comment by manniL** [comment]
The `src` directory should contain all your components, also `app.vue` and `error.vue`. Then, the error page will be rendered as usual

**Comment by carbdias** [comment]
Thank you very much !!

**Comment by carbdias** [comment]
Hello, I still have a problem here, despite rendering, it seems that variables made available in the setup are not available in the template, is like a vue page built outside of pages does not have the same possibilities than a normal page would. 
I mean I do have variables to true that in template react as they are undefined or not exist.

**Comment by cryptic-dev** [comment]
> Hello, I still have a problem here, despite rendering, it seems that variables made available in the setup are not available in the template, is like a vue page built outside of pages does not have the same possibilities than a normal page would. I mean I do have variables to true that in template react as they are undefined or not exist.

Its mentioned in the documentation that its not a page in the general sense
