### ISSUE TITLE
Issue with Placing Files in the /public Path After Production in Nuxt3

### ISSUE THREAD

**Issue by listensay** [nuxt/nuxt#24820]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.19.0
- Nuxt Version:     3.7.4
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.21
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

When I need to place files in the public directory after packaging with Nuxt, I find that they become inaccessible. I noticed that the packaged files have a mapping object that maps the file directory. How can I make the files accessible without having them mapped?

<img width="1710" alt="image" src="https://github.com/nuxt/nuxt/assets/36002169/2d140589-8214-4532-96d5-9fa534aaa9f1">

### Describe the bug

This might not be a bug. I believe it should be controllable, so how can I solve my problem?

**Comment by danielroe** [comment]
This is not supported, by design. It allows for a much faster, more optimised server.

If you need to support uploading files you can use [the Nitro storage layer](https://nitro.unjs.io/guide/storage) to access the file system after build, and implement your own handler for this.
