### ISSUE TITLE
prepopulate cache during prerendering

### ISSUE THREAD

**Issue by kangelopoulos** [nuxt/nuxt#24828]
### Describe the feature

This may already be a feature but it is not described in the documentation anywhere that I can find. I'm looking for a way to prerender pages but then still utilize SWR. I'm working in a complex site where the initial hit on SWR routes would take way too long to put it on the server - it needs to be pre-generated even if it increases build times. Is that already available in nuxt? 

-------

To elaborate on this, earlier this year there was a mistake in the docs suggesting that swr renders all pages statically at build time and then would revalidate the pages in the back round every TTL seconds. A bunch of Nuxt users wrote articles on this feature and took the docs at face value. So there is a lot of information out there suggesting that this is possible in Nuxt 3.

It turns out swr actually caches the page response the first time a page is visited (e.g. server side rendering on the first hit to any endpoint, then cached response thereafter with background revalidation). 

Is there a way to get the behavior of static rendering at build time but with the typical swr/isr behavior at runtime? 

In addition - just to comment on this as well - the docs are still unclear. It says under the isr/swr route rules that it caches the server response and implies this is the response of the page itself. What it is actually doing is caching all of the responses on the server that are used to build the page so the client is pinging the server repeatedly if it takes more than one call to gather the content to render a page. 

### Additional information

- [X] Would you be willing to help implement this feature?
- [x] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by pi0** [comment]
Thanks for the suggestion. This seems a nice usecase, however we might need to make add new feature to nitro to allow "pre-populating the SWR cache" and bundling it via the deployment as pre-rendered pages will always override and skip hitting the renderer at all.

**Comment by pi0** [comment]
I have escalated your issue to Nitro for discussion 👍🏼  https://github.com/unjs/nitro/issues/2016
