### ISSUE TITLE
spa loading template is removed before the page is completely loaded

### ISSUE THREAD

**Issue by jd1378** [nuxt/nuxt#24838]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.9.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      ssr, telemetry
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://codesandbox.io/p/devbox/nuxt3-spa-loading-bug-s4pg67

### Describe the bug

When the spa loading template is removed, depending on the page content and network speed (I am not sure), it takes some time till the page is actually rendered

in my case (not locally), it takes like 3-5 seconds after the template is removed to show the content, which is not expected. I tried to make a reproduction of the bug, which should demonstrate what I mean, even though it take less than a second to render, but still you can see the completely empty screen

it should be only removed once the page is completely ready to be shown, it should not show a blank screen at all

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/21721.
