### ISSUE TITLE
Throw showError breaks interactivity of asyncData on page 

### ISSUE THREAD

**Issue by VladimirCores** [nuxt/nuxt#24844]
### Environment

- Operating System: `Linux`
- Node Version:     `v20.10.0`
- Nuxt Version:     `3.8.2`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `-`
- User Config:      `anime`, `app`, `colorMode`, `devtools`, `eslint`, `fontMetrics`, `googleFonts`, `imports`, `modules`, `nitro`, `runtimeConfig`, `spaLoadingTemplate`, `ssr`, `tailwindcss`, `telemetry`, `ui`, `vite`
- Runtime Modules:  `@hypernym/nuxt-anime@2.1.1`, `@nuxtjs/fontaine@0.4.1`, `@nuxtjs/google-fonts@3.1.0`, `@nuxtjs/eslint-module@4.1.0`, `@nuxt/ui@2.11.1`
- Build Modules:    `-`

### Reproduction

Please take a look here: https://stackblitz.com/edit/github-1bxyzu?file=pages%2Findex.vue

### Describe the bug

useLazyAsyncData just stop working when return to the same page after showError and then clearError

**Comment by VladimirCores** [comment]
Now it can't be reproduced. I will try to update my example to match conditions I have on local run.

**Comment by VladimirCores** [comment]
Here is what I experience it almost the same scenario as in the reproducible link above:

[Screencast from 2023-12-20 18-30-44.webm](https://github.com/nuxt/nuxt/assets/442111/f2ca4ec6-c973-4d94-8e17-33b90bea8cd3)

"Refetch data" from dev tool not working as well.
Complete do not understand why reactivity breaks : |
However `reloadNuxtApp({ path })` instead of `clearError({ redirect: path })` solve the problem.

**Comment by manniL** [comment]
Because `selectedTodoId.value` will be `undefined`, thus `immediate` will be false. by default. Using the buttons triggers useAsyncData fine though.

Feel free to ping if you have another running reproduction though ☺️
