### ISSUE TITLE
useCookie doesn't update when maxAge or expires option is set

### ISSUE THREAD

**Issue by Kyowdem** [nuxt/nuxt#24856]
### Environment

It's a new nuxt project.

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.18.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.0
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

In the following below, the cookie updates. However, if you uncomment the maxAge, it will no longer be updated.

```vue
<template>
  <div>
    {{ bgChart }}
    <input type="color" v-model="bgChart.v" name="" id="">
  </div>
</template>

<script setup lang="ts">
const bgChart = useCookie("bgChart", {
  default: () => ({ v: "#fcfcfc" }),
  // maxAge: Number.MAX_SAFE_INTEGER,
});
</script>
```

### Describe the bug

If you set the option maxAge or expires in useCookie function, the variable will not be updated.

**Comment by ambroisemaupate** [comment]
Same issue here.

Easy to reproduce on Nuxt Hello World : https://nuxt.com/docs/examples/hello-world

```
<script setup lang="ts">
const version = 2 + 1;

const user = useCookie('userInfo', {
  default: () => ({ score: -1 }),
  watch: true,
  // maxAge breaks cookie reactivity
  maxAge: 60 * 60,
});

const increment = () => {
  user.value.score++;
};
</script>

<template>
  <div class="hello">Hello Nuxt {{ version }}!</div>

  <p>User score: {{ user.score }}</p>

  <button @click="increment">Increment score (cookie)</button>
</template>

<style scoped>
.hello {
  font-family: Arial, Helvetica, sans-serif;
  font-size: 3rem;
}
</style>
```
