### ISSUE TITLE
WebSocket connection to 'wss://dev.*******.in/_nuxt/hmr/' failed: 

### ISSUE THREAD

**Issue by mahanteshaCloudMPower** [nuxt/nuxt#24855]
### Environment

Node 20.10.0
npm 3.8.2

### Reproduction

https://stackblitz.com/edit/github-jfxmyq?file=app.vue,nuxt.config.js

client.ts:77 WebSocket connection to 'wss://dev.***.in/_nuxt/hmr/' failed: 
[vite] server connection lost. polling for restart...

### Describe the bug

client.ts:77 WebSocket connection to 'wss://dev.***.in/_nuxt/hmr/' failed: 
setupWebSocket @ client.ts:77
(anonymous) @ client.ts:67
client.ts:105 [vite] server connection lost. polling for restart...
client.ts:339

**Comment by manniL** [comment]
Works fine locally. More information + explanation is needed here ☺️

**Comment by hutchic** [comment]
possibly the same as https://github.com/nuxt/nuxt/issues/25335 (?)

**Comment by manniL** [comment]
Indeed. Let's consolidate in https://github.com/nuxt/nuxt/issues/25335
