### ISSUE TITLE
useRuntimeConfig not defined in composable when called from server middleware

### ISSUE THREAD

**Issue by tibineagu** [nuxt/nuxt#24867]
### Environment

```
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      runtimeConfig, devtools
- Runtime Modules:  -
- Build Modules:    -
```

### Reproduction

https://stackblitz.com/edit/github-vvktbn?file=server%2Fmiddleware%2Fmy-middleware.js

### Describe the bug

When using a [composable that calls `useRuntimeConfig`](https://stackblitz.com/edit/github-vvktbn?file=composables%2FuseMyComposable.js) in a [server middleware](https://stackblitz.com/edit/github-vvktbn?file=server%2Fmiddleware%2Fmy-middleware.js), a request error is thrown regarding "useRuntimeConfig is not defined"

### Additional context

The same composable works as expected when [called from a plugin](https://stackblitz.com/edit/github-vvktbn?file=plugins%2Fmy-plugin.server.js).

### Logs

```shell-script
[nuxt] [request error] [unhandled] [500] useRuntimeConfig is not defined
  at Module.useMyComposable (./composables/useMyComposable.js:15:25)  
  at Object.eval [as handler] (./.nuxt/dev/index.mjs:686:82)  
  at Object.eval [as handler] (./node_modules/h3/dist/index.mjs:1796:31)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:2006:7)
```

**Comment by manniL** [comment]
Funnily this was discussed a few days ago in https://github.com/nuxt/nuxt/issues/24841 ☺️

**Comment by tibineagu** [comment]
@manniL a colleague who was helping me out with this forwarded me that link a few moments after I opened my issue 🤦‍♂️ 

Thanks for replying so quickly, i can't tell you how much we appreciate the help!

**Comment by tibineagu** [comment]
@manniL what would you recommend as the best course of action if we need the same functionality in both the server middleware and in the app at runtime?

**Comment by manniL** [comment]
@tibineagu no worries 😋 Solutions are also in the linked issue 👍🏻
