### ISSUE TITLE
Client-only page

### ISSUE THREAD

**Issue by kingyue737** [nuxt/nuxt#24866]
### Describe the feature

Importing a library that is not compatible with SSR in a page may result in an error like `window is undefined`.

```vue
<!-- /pages/page1.vue -->
<script setup>
import L from 'L' // L is a library that does not support SSR
</script>

<template>
<div id='L'>
  <!-- ... -->
</div> 
</template>
```

We need to manually extract it to a separate component to the `components` folder and import it in the page, even though this component may only be used once.

```vue
<!-- /components/PageComponent.vue -->
<script setup>
import L from 'L' // L is a library that does not support SSR
</script>

<template>
<div id='L'>
  <!-- ... -->
</div> 
</template>
```
```vue
<!-- /pages/page1.vue -->
<script setup>
</script>

<template>
<ClientOnly>
  <PageComponent />
</ClientOnly> 
</template>
```

Maybe we can add a `clientOnly: boolean` field to `definePageMeta` macro to improve DX. Wrapping this page to `ClientOnly` for end users.

I know we already have `routeRules`. However, I still want to server render the layout when navigating to this page.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by ExEr7um** [comment]
You can use `routeRules` to achieve that: https://nuxt.com/docs/guide/concepts/rendering#route-rules.

**Comment by kingyue737** [comment]
> You can use `routeRules` to achieve that: https://nuxt.com/docs/guide/concepts/rendering#route-rules.

Please read my last sentence. 

> I know we already have routeRules. However, I still want to server render the layout when navigating to this page.

`routeRules` will render all the things on client side when navigating to that page via address bar. But I want to render the layout on server side like other pages to keep it consistent but only leave the page content to client side.

**Comment by mukhriddin-dev** [comment]
Good @danielroe

**Comment by zyp971018** [comment]
I had the same problem

**Comment by SemionChi** [comment]
is someone on it?
would love to make my first contribution.

**Comment by mukhriddin-dev** [comment]
@danielroe fire
