### ISSUE TITLE
server plugins loading twice in dev

### ISSUE THREAD

**Issue by jinusean** [nuxt/nuxt#24871]
### Environment

- Node Version:     v18.17.1
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  pnpm@8.9.2
- Builder:          -
- User Config:      alias, ssr, devtools, plugins, sourcemap, primevue, build, modules, runtimeConfig, routeRules, pinia, nitro, css, vite, tailwindcss
- Runtime Modules:  @formkit/nuxt@1.2.1, @nuxt/devtools@1.0.0-beta.0, @pinia/nuxt@0.4.11, @nuxtjs/tailwindcss@6.8.0
- Build Modules:    -

### Reproduction

```javascript
export default definNitroPlugin(() => {
     console.log('plugin')
})
```

### Describe the bug

Plugins are being called twice when running in `dev` mode.

Steps to reproduce
0. Delete `.nuxt` directory
1. `pnpm run dev` to generate `.nuxt` directory.
2. Notice single log statement `"plugin"`
3. Stop process. 
4. Run `pnpm run dev` again and notice two log statements.

**Comment by manniL** [comment]
Hey 👋🏻
Please include a running repository! I can't reproduce this [with this StackBlitz](https://stackblitz.com/edit/nuxt-issues-24871).

**Comment by danielroe** [comment]
I think this might be linked to https://github.com/nuxt/nuxt/issues/22629. (Though it might not be reproducible since vite 5.) Let's track there
