### ISSUE TITLE
In useAsyncData, error.value loses its class instance

### ISSUE THREAD

**Issue by alex-eliot** [nuxt/nuxt#24870]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.9.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      telemetry
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://codesandbox.io/p/devbox/distracted-cloud-4zvpy9?file=%2Fapp.vue%3A1%2C1

### Describe the bug

The error ref which is populated with the thrown error by the async callback in useAsyncData loses its class instance, making checks like `error.value instanceof AxiosError` no longer feasible.

**Comment by manniL** [comment]
Classes are (by default) not serializable, hence "transmitting" them from server to client is not straightforward. You either use an own check (e.g. for a custom attribute like [Nuxt is doing it for it's errors](https://github.com/nuxt/nuxt/blob/4dcc48f4e60f42f3207a5e72833c6cccb9e1ffe0/packages/nuxt/src/app/composables/error.ts#L7-L8)) or use a [custom reviver](https://nuxt.com/docs/getting-started/data-fetching#custom-serializer-function) to restore the class (which could be more effort)
