### ISSUE TITLE
Chunk ordering in Nuxt 3 (When generating)

### ISSUE THREAD

**Issue by Gumper-x** [nuxt/nuxt#24878]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.9.0
- Nuxt Version:     -
- CLI Version:      3.10.0
- Nitro Version:    -
- Package Manager:  pnpm@8.12.1
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### On the first screen as it was before:

<img width="944" alt="image" src="https://github.com/nuxt/nuxt/assets/52721424/ce1c5086-3e76-4216-b12f-11c28688ddf8">

## It can be seen that default.[hash].css is at the beginning of the list and has a rel="stylesheet" parameter
```
<link rel="stylesheet" href="/_nuxt/default.414593af.css">
```

### But at some point the generation gave me this:
<img width="943" alt="image" src="https://github.com/nuxt/nuxt/assets/52721424/bc7311ce-7caa-40c5-982b-a303b1ca5bd3">

## Our link with default.[hash].css flew down somewhere and changed the rel to prefetch and added a attr as="style"
```
<link rel="prefetch" as="style" href="/_nuxt/default.414593af.css">
```

**Comment by danielroe** [comment]
The package responsible is https://github.com/nuxt-contrib/vue-bundle-renderer. It renders the links. But they are then finally rendered/ordered by https://github.com/unjs/unhead. (You can even enable `experimental.headNext` to optimise their order automatically.)

Feel free to open an issue in either package (or here) with a reproduction 🙏
