### ISSUE TITLE
Lazy Fetch 100% CPU

### ISSUE THREAD

**Issue by BlackYuzia** [nuxt/nuxt#24879]
### Environment

```js
- Operating System: Windows_NT
- Node Version:     v18.18.2
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  npm@9.8.1
- Builder:          -
- User Config:      ssr, modules, vite, runtimeConfig, app
- Runtime Modules:  ()
- Build Modules:    -
```

### Reproduction

https://gitlab.com/BlackYuzia/nuxt-3-useasyncdata-bug-reproduce

### Describe the bug

When you use `useLazyAsyncData` or `useLazyFetch` for fetch a lot of items (5-10K+)  you will get 100% CPU and a lot of RAM using on "first render".

### Additional context

I use **nuxt3** with **vuetify3**. 
In my case I use [**VVirtualScroll**](https://vuetifyjs.com/en/components/virtual-scroller/#usage) component

**Comment by danielroe** [comment]
What if you set the `deep: false` option?

**Comment by BlackYuzia** [comment]
@danielroe already try it, don't help.

**Comment by manniL** [comment]
Can't repro without extra components or using the virtual scroll component. [See StackBlitz](https://stackblitz.com/edit/nuxt-issues-24879?file=app.vue)

**Comment by danielroe** [comment]
Thanks for investigating @manniL.

Yes, in that case this seems like an upstream issue and we should probably close here for now.

@BlackYuzia if you can reproduce with just Nuxt, let me know and we can reopen here 🙏
