### ISSUE TITLE
Nuxt3 props and refs weird behaviour

### ISSUE THREAD

**Issue by Ischafak** [nuxt/nuxt#24872]
### Environment

- Operating System: Darwin
- Node Version:     v18.17.0
- Nuxt Version:     3.7.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.17
- Builder:          -
- User Config:      runtimeConfig, purgeCSS, modules, pinia, imports, i18n, dayjs, dayjsI18n, turnstile, app, meta, build, css
- Runtime Modules:  nuxt-icons@3.2.1, @nuxtjs/turnstile@0.6.3, @gabortorma/nuxt-dayjs-i18n@2.0.2, @nuxtjs/i18n@8.0.0-beta.13, dayjs-nuxt@2.1.9, @nuxtjs/tailwindcss@6.10.1, @pinia/nuxt@0.4.11, @pinia-plugin-persistedstate/nuxt@1.2.0
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                     

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Reproduction

https://codesandbox.io/p/devbox/dazzling-lake-wsdcds?file=%2Fpages%2Findex.vue%3A3%2C8

### Describe the bug

i dont know am i thinking wrong but this is the case.

i am changing data which i am also using as a prop and after i change i am calling the function inside of component but prop data is not changing directly.

---------

There is a main page file and inside of it i have 
data object

data: {
  id:0
}

when i click the button i am changing this data objects id to 2 and i am calling the method inside component

but if you check the console you can see the data is still 0. 

it should be 2 because i did this

this.data.id = 2;
this.$refs["testref"].conslog();

if i use nexttick it is working btw

**Comment by manniL** [comment]
This is also a behavior in [plain Vue.js](https://play.vuejs.org/#eNqFU81OGzEQfhXLqgRIaLeC23aJ+iMO7YFWLbeaw7I7SQxee7HHISjKuzO2EzsSKOzBnv9vZvzthn+bpmrlgTe8RRgn1SHMhGasvQWHF8zC/EpwJJkkwVkjB9KHDrtKDqTXKfjeIxrNvvZK9o+7hBFwaShmlpxtnW5KaOsDKFJdb+WEJMtxMhZZgp5bM7KTqo5a6PHki9CwjhEDzDuvkG0Cem8oTYNG1yQDSxXOg7yNZ2j49GzvtYDe6r2WvDk1fHJo2OeYGL5Ugm7C32tpuAJYBi4wZF1KV+2Wxa7YRSyQHZ9ope7/wXbvqt5op8zi9GwXmcDCGcDbOm+Kn3N0FD2Xi+rBGU3vF1EFD9uQCuzvCSVVEzz3KHinlHn+FW1oPezmopwl9I/v2B/cOtgE/2PBgV2B4NmHnV0AJvf1vxtYk5ydoxm8ougjzr/gjPKhxxT23euB2j6Ii93+jJSQenHrrtcI2u2HCo2W9xCcCPLjyOil3cvqMubRTmmLmV1v/4BBrmabDZGBbbdtHbQj1H2PmJM1U6FIIFVhxssEDbvx4z3YTDQLT15aoLiDVygUeMu6TJdSOJiMgiqYI8vk8DGZtq8YWkz7)

I also think this is related to the data update not being propagated when calling the exposed function of the template ref component, as `nextTick` works.

Nevertheless, this is not a Nuxt issue.
