### ISSUE TITLE
Nuxt link does not expose slot api on component like Router Link

### ISSUE THREAD

**Issue by inthegreenwild** [nuxt/nuxt#24874]
### Environment

- Operating System: Darwin
- Node Version:     v16.19.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.9.2
- Builder:          -
- User Config:      devtools, vite
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-yfh8fb?file=app.vue

### Describe the bug

Vue Router's link component exposes its api via v-slot api as noted here https://router.vuejs.org/guide/advanced/composition-api.html#useLink which I have used in a vue 2 component. But after migrating to Vue 3 and attempting to use the same component in a Nuxt 3 application, it does not work because nuxt does not offer the v-slot api, resulting in a destructuring error. 

The component I have is meant to support both vue router and nuxt router, which means it must work for both router-link and nuxt-link. This is now an issue because nuxt 3 does not provide the v-slot api. 

### Logs

```shell-script
Cannot destructure property 'href' of 'undefined' as it is undefined.

at Proxy.renderFnWithContext (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:770:13)
at Proxy.eval (./node_modules/nuxt/dist/app/components/nuxt-link.js:260:92)
at renderComponentRoot (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:830:16)
at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:702:28)
at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:631:12)
at Module.ssrRenderComponent (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:86:10)
at _sfc_ssrRender (./app.js:28:31)
at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:685:9)
at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:631:12)
```

**Comment by manniL** [comment]
You need to set the `custom` prop. Then you can also use the slot api ☺️

https://stackblitz.com/edit/nuxt-issues-24874?file=app.vue

**Comment by inthegreenwild** [comment]
@manniL  Adding custom did resolve the issue in stackblitz but it turns out this doesn't work if using dynamic components which is what I'm running into in my application. I've updated the reproduction like to use `comonent :is` to better show the exact issue I'm experiencing.

**Comment by manniL** [comment]
@inthegreenwild Use [`resolveComponent`](https://nuxt.com/docs/guide/directory-structure/components#dynamic-components) then 😋

**Comment by inthegreenwild** [comment]
> @inthegreenwild Use [`resolveComponent`](https://nuxt.com/docs/guide/directory-structure/components#dynamic-components) then 😋
> 
> Updated my StackBlitz for it 👍🏻

Hi @manniL , that stackblitz link doesn't appear to be updated for me but I did try this and the issue persists: https://stackblitz.com/edit/github-yfh8fb?file=app.vue

**Comment by manniL** [comment]
@inthegreenwild `to` prop was missing ;)

**Comment by inthegreenwild** [comment]
that fixed it thanks!
