### ISSUE TITLE
useNuxtApp provides are of type unknown when typescript is installed as dependency

### ISSUE THREAD

**Issue by jakubkoje** [nuxt/nuxt#24885]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.10.0`
- Nuxt Version:     `3.8.2`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `bun@1.0.0`
- Builder:          `-`
- User Config:      `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/jakubkoje/nuxt-reproduction

### Describe the bug

In the reproduction I created a plugin that adds a method $hello to the useNuxtApp. The issue is, If I have typescript with vue-tsc installed (as shown here https://nuxt.com/docs/guide/concepts/typescript), I do not see the $hello in useNuxtApp. If I uninstall the typescript and vue-tsc everything works normally.

### Additional context

I encountered this first on production project, after realizing what the issue is inside the reproduction, I was able to temporarily fix it both in reproduction and production projects by uninstalling typescript and vue-tsc. This is not a ideal solution.

I have tried to downgrade the installed typescript version down to what the nuxt comes with, no luck - had to remove typescript from my dependencies entirely.

**Comment by root5427** [comment]
I'm encountering the same problem. I've initialized multiple starter projects and created plugins following the documentation, but the `useNuxtApp` provides plugins of an unknown type.

**Comment by danielroe** [comment]
This works fine for me when cloning and installing deps (and of course, running `nuxi prepare`):

<img width="651" alt="CleanShot 2023-12-25 at 13 17 24@2x" src="https://github.com/nuxt/nuxt/assets/28706372/95bc8365-1e76-4b48-a48a-93b466977ef3">

**Comment by jakubkoje** [comment]
Unfortunately, I can not provide any more detailed reprotuction. I tried to reistall it once again using bun, ran ’bun prepare’ again and it sudenly started working.

**Comment by danielroe** [comment]
It worked fine for me with pnpm. Maybe the issue is mixing the package managers?

**Comment by jakubkoje** [comment]
Well, I always removed the node_modules and all lockfiles. So I am not sure - I might try installing latest pnpm and trying it out again just to be sure.

**Comment by root5427** [comment]
> I wonder what the TypeScript version installed by your IDE is

Tried using VSCode's TypeScript version 5.3.2 and the project's bundled TypeScript version 5.3.3. The result is the same. I suppose a temporary solution might be manually typing the plugins as described [here](https://nuxt.com/docs/guide/directory-structure/plugins#typing-plugins).

**Comment by danielroe** [comment]
Would you try running `vue-tsc` and seeing if there is an error reported? That's probably more reproducible than using your IDE, which might have other issues.

**Comment by jakubkoje** [comment]
It shows just that the type is unknown in my production project. I really cannot reproduce it now, even with pnpm in the reproduction repo I provided. I guess we can close this for now, if I encounter this again, I will create a new issue. Sorry for bothering you, I got no idea why it started working today :)

**Comment by jakubkoje** [comment]
I may have found the issue. It seems like it is caused by installling `@vueuse/motion` inside the modules. I will update the reproduction.

**Comment by Dananz** [comment]
Happens here too, all the the plugins returns as `unknown`
![image](https://github.com/nuxt/nuxt/assets/40542472/8f9c66c9-dfb8-4ca6-b889-2b060df67e02)

**Comment by manniL** [comment]
One way to repro it is the linked reproduction + uncommenting `@vueuse/motion`. This should be an issue of the module then though.
Would be interesting to see if there are more modules where that happens.

**Comment by jakubkoje** [comment]
I have found a similiar bug which may be related, nuxt-modules/ionic#597. The generated types are empty and it is causing the same issue, that all other plugins in useNuxtApp are unknown.
