### ISSUE TITLE
vue development build is included in nitro output

### ISSUE THREAD

**Issue by gyxoBka** [nuxt/nuxt#24882]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Here's [Stackblitz](https://stackblitz.com/edit/nuxt-examples-tnmdbb?file=package.json)
npm run build
npm run start
go to /user/dsdsd

### Describe the bug

When start production server with node .output/server/index.js  and in error page is throwed i get [Vue warn]: Component <Anonymous> is missing template or render function.

What is going on? How to remove this warn?

**Comment by huang-julien** [comment]
Did you mean to have your `user.vue` file named `index.vue` ?

**Comment by gyxoBka** [comment]
> Did you mean to have your `user.vue` file named `index.vue` ?

hi, no.  user.vue - parent route. user folder - children. I improved the example for clarity on StackBlitz

**Comment by danielroe** [comment]
For now, you can run `NODE_ENV=production node .output/server/index.mjs` instead.

cc: @pi0 It seems we have a regression with [tracing export conditions](https://github.com/unjs/nitro/issues/844) as the Vue dev build is also getting picked.

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/23402.

**Comment by danielroe** [comment]
This is now resolved (for vue) in the latest release of `@vue/runtime-core`! 🎉 

See bundle size diff in https://github.com/nuxt/nuxt/pull/25036/files#diff-04a7585c5d6ddd5cf80321c69bc6e07cd85e9e86ae35fa5f9c036651f137c312.
