### ISSUE TITLE
useFetch returns null in very strange and complex case

### ISSUE THREAD

**Issue by Rusinas** [nuxt/nuxt#24895]
### Environment

- Operating System: Windows_NT
- Node Version:     v21.2.0
- Nuxt Version:     -
- CLI Version:      3.10.0
- Nitro Version:    -
- Package Manager:  unknown
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

Well, guys, this was a hell to find out the reason. Here is a link:
https://github.com/Rusinas/use-fetch-bug

So, what you need to do is to just run `npm run build` and `npm start`, because the bug occurs only in the build.  Open `localhost:3000` and see that useFetch returned `null`

To see that it works fine without the bug I found, go to `WithGlobalState2.vue` and comment out line number 13 `const { global } = useGlobal()`, rebuild and rerun. Now it works fine. 

### Describe the bug

The sequence of the bug to occur is just crazy. It is very specific case, where I have a composable, that uses some kind of global state (I really need it, don't suggest Pinia please, this is for a good reason), and it is inside both regular and async component, where async component is inside regular. If it is a case - `useFetch` will break in production. Please help, I spent days to figure this out.

**Comment by manniL** [comment]
Did you consider using `useState` instead? A `ref` (especially outside of a composable as global state) is not ssr-safe

**Comment by Rusinas** [comment]
@manniL thank you for the response, I really thought it was some kind of a bug, but I totally get why it is not ssr safe.
What is the useState exactly? Is it in nuxt or in vue?
The problem is that all the logic I showed is inside of a package that is used across multiple applications, vue mostly, and it is pretty complex and I have no idea how to fix it just for nuxt if there are some nuxt's tools required for this :(

I probably need to rethink that composable logic all over, but it is quite painful that I can't use that syntax

**Comment by manniL** [comment]
> What is the useState exactly? Is it in nuxt or in vue?

It is [a Nuxt composable](https://nuxt.com/docs/api/composables/use-state)

> is pretty complex and I have no idea how to fix it just for nuxt if there are some nuxt's tools required for this :(

I guess one way would be to have an initialize method for the globals that allows to pass the refs to them. In Nuxt, you'd just pass the `useState` (which also returns a ref eventually).

**Comment by Rusinas** [comment]
> an initialize method for the globals that allows to pass the refs to them
@manniL kindly asking for a little code snippet on how to achieve this, can't figure it our now :(

**Comment by Rusinas** [comment]
@manniL whooops, it turned out that the problem is not with the global refs, but with the sharing composable between regular and async component in general. 

With the same use case, as I described previously, but with the updated composable (I've updated the repo):
![image](https://github.com/nuxt/nuxt/assets/42975143/c6f6af5f-2f29-4eb9-bd03-bd9e7be661ab)
(well, it is not global anymore, but don't mind the name)

The bug is the same. `useFetch` will return `null`. So, I guess that your solution might help, but I have no idea how to implement it right now. 

And all this raises a question - is using composables and async components simultaneously THAT dangerous in nuxt? That's a bummer, because I have so many libraries already and I've never took this into account during development.

**Comment by manniL** [comment]
I don't see `useFetch` returning null 
<img width="1391" alt="image" src="https://github.com/nuxt/nuxt/assets/640208/e2ae868e-5dca-4be6-8175-83438a7058c7">

**Comment by Rusinas** [comment]
@manniL is this `npm run build && npm start`?

**Comment by Rusinas** [comment]
@manniL can you reproduce it? It is blocking me and I need to know if the problem is on my side :(

**Comment by manniL** [comment]
@Rusinas I can indeed with `npm run build && npm start` with your app. But the issue is rather how you use useFetch I'd say.

I've updated your repo a little so reactivity is kept and results are fine. If `useFetch` returns null initially (which can happen, e.g. when used lazily or not awaited properly), the result will be updated as useFetch **is a composable** and `data` is a ref.

[Example](https://stackblitz.com/edit/nuxt-issues-24895-2?file=composables%2FuseApi.ts,pages%2Findex.vue,components%2FWithGlobalState2.vue)

**Comment by Rusinas** [comment]
Oh, damn. Thank you. I think this will work perfectly fine now, thank you x1000, didn't think that could be the reason

**Comment by Rusinas** [comment]
@manniL I am so sorry for bothering you once again, but... It didn't work out. You can check my repo, I updated the useApi composable as you described and no, this is still not working. Maybe I did something wrong?
