### ISSUE TITLE
useLoadingIndicator doesn't work correctly

### ISSUE THREAD

**Issue by divine** [nuxt/nuxt#24900]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      extends
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-examples-4fafzz?file=pages%2Findex.vue

Step to reproduce:

1. Click on Demo Link (doesnt work)
2. Check console logs (`useLoadingIndicator().start();`is called but not working)
3. Click on Start/Stop and see it's working fine from page.

### Describe the bug

I've tried implementing `useLoadingIndicator().start()`but failed because it doesn't work from plugin hooks/pinia store for unknown reason.

I've provided reproduction which should work, check DevTools logs and click on ?

**Comment by manniL** [comment]
This works correctly!
Your reproduction doesn't because `stopLoading` is automatically called on `'page:loading:end'`, so right away after you started the loading manually 🙈 

Calling it with an await works better to showcase! 

```ts
export default defineNuxtPlugin({
  // eslint-disable-next-line unused-imports/no-unused-vars
  async setup(nuxtApp) {},
  hooks: {
    // You can directly register Nuxt app runtime hooks here
    'page:loading:end': async function () {
      console.log('Calling startLoading function from a plugin!');
      await new Promise(r => setTimeout(r, 1000))
      startLoading();
    },
  },
});
```

**Comment by divine** [comment]
Hello @manniL,

Your example works but honestly I didn't expect that.

My idea was that loading indicator should start as it was "restarted" in my case because it's a minimal reproduction.

Basically I'm trying to fetch data from API inside store and show loading indicator while data is fetched... but it's not working well and it's only reproduction that I was able to create which is solved by your given example.

Also an option like force start it from scratch should fix it  I think.

What do you think?

Thanks!

**Comment by divine** [comment]
This is the reason of my problem:

https://github.com/nuxt/nuxt/blob/f5676fba5668c3dbff8c1c40e988d469740ee82e/packages/nuxt/src/app/composables/loading-indicator.ts#L16-L23

After page load for 900 milliseconds loading indicator can't be started. There should be a function to reset that instantly imo.

**Comment by manniL** [comment]
@divine I agree with regards to fully resetting it! Would you mind creating a new feature request for that?
