### ISSUE TITLE
Error deploying NUXT 3 application on IIS server

### ISSUE THREAD

**Issue by hoangnx1986** [nuxt/nuxt#24904]
### Environment

IIS server v10
node js v20.10
iisnode core v0.2.26-x64
url rewrite

### Reproduction

http://t.com.vn/

### Describe the bug

I have a NUXT 3 SSR application that was running fine under localhost. But when deploying to the iis server, I receive the following error message: "Application has thrown an uncaught exception and is terminated:
RangeError [ERR_SOCKET_BAD_PORT]: options.port should be >= 0 and < 65536. Received type string ('\\.\pipe\9de302c8-f71e-42...')."

I followed the instructions here:
https://github.com/nuxt/framework/commit/ede534847831f46c45089a122d19b083d2ae26c7

Does anyone know how to fix this error? Please help me,

```[tasklist]
### Tasks
```

**Comment by hoangnx1986** [comment]
And here is the log in iisnode folder:

Application has thrown an uncaught exception and is terminated:
RangeError [ERR_SOCKET_BAD_PORT]: options.port should be >= 0 and < 65536. Received type string ('\\.\pipe\fd654833-c89f-46...').
    at validatePort (node:internal/validators:424:11)
    at Server.listen (node:net:2000:5)
    at file:///C:/inetpub/wwwroot/esim_du_lich/demo/server/chunks/nitro/node-server.mjs:5563:25
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:431:15)

**Comment by manniL** [comment]
Should be resolved since https://github.com/unjs/nitro/pull/2020 (pending for release, can be used on the nightly nitro channel)

**Comment by hoangnx1986** [comment]
You are wonderful! My problem has been resolved. Thank you very much.

**Comment by mnce92** [comment]
I also encounter similiar issue , i got this error -->  "The iisnode module is unable to start the node.exe process. Make sure the node.exe executable is available at the location specified in the [system.webServer/iisnode/@nodeProcessCommandLine](https://github.com/tjanczuk/iisnode/blob/master/src/samples/configuration/web.config) element of web.config. By default node.exe is expected in one of the directories listed in the PATH environment variable."  how do i fix this?

**Comment by TARGINO0110** [comment]
Intructions deploy into iis -----> https://nuxt.com/deploy/iis
