### ISSUE TITLE
useFetch and useLazyFetch bugs

### ISSUE THREAD

**Issue by RifatMahmudno-1** [nuxt/nuxt#24903]
### Environment

Nuxt project info:                                                         1:12:27 PM

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.18.2
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.5
- Builder:          -
- User Config:      devtools, app
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Check this Stackblitz [https://stackblitz.com/edit/nuxt-starter-9yhhsu](https://stackblitz.com/edit/nuxt-starter-9yhhsu)

### Describe the bug

1. Doesn't run `getCachedData()` when refreshed or when watching variables changes. It's important because otherwise the client will request the same old data.
2. `getCachedData()` runs 3 times in both server and client.
3. Reactive `key` not supported. It's important because `?page=1`, `?page=2` `...` they all have different data. So, they need to be stored under different keys.

**Comment by manniL** [comment]
Let's track in the following issues:

* `refresh` +  `getCachedData` - https://github.com/nuxt/nuxt/issues/24332#issuecomment-1827581590
* Reactive key - https://github.com/nuxt/nuxt/issues/21532
