### ISSUE TITLE
wrong jsdocs in `experimental.features`

### ISSUE THREAD

**Issue by userquin** [nuxt/nuxt#24910]
### Environment

NA

### Reproduction

https://github.com/nuxt/nuxt/blob/8ba118facb78b77cc3a9cf50e4f1f991bfff7d8b/packages/schema/src/config/experimental.ts#L26-L30

### Describe the bug

`experimental.features` jsdocs with `futures` jsdocs

**Comment by danielroe** [comment]
resolved in https://github.com/nuxt/nuxt/commit/f5676fba5668c3dbff8c1c40e988d469740ee82e ❤️ .

**Comment by userquin** [comment]
@manniL good issue first :sweat_smile: ?
