### ISSUE TITLE
Warning from NuxtLayout: Your project has layouts but the `<NuxtLayout />` component has not been used.

### ISSUE THREAD

**Issue by doantu05150** [nuxt/nuxt#24912]
### Environment
package.json

`{
 "nuxt": "^3.9.0",
"typescript": "^5.2.2",
"vue": "3.4.0-rc.3",
"vue-router": "latest"
}`

### Reproduction

I upgraded Nuxt from `3.8.2` to `3.9.0`

### Describe the bug

I upgraded to the latest Nuxt version (3.9.0), Vue (3.4.0-rc.3), and the latest vue-router, but I'm getting a warning.

![image](https://github.com/nuxt/nuxt/assets/29808554/d996f7e2-2cec-4ee5-9025-8d2de349d115)

There's no error, but rather annoying.

### Additional context

Only my `app.vue` file contains `<NuxtLayout>` component. Here is my `app.vue` file:

![image](https://github.com/nuxt/nuxt/assets/29808554/4bcc08a9-7111-4d0b-a254-8f479ff65e2a)

### Logs

```shell-script
[Vue warn]: Component LayoutLoader is missing template or render function.
[Vue warn]: Component LayoutLoader is missing template or render function.
[nuxt] Your project has layouts but the `<NuxtLayout />` component has not been used.
[nuxt] Your project has layouts but the `<NuxtLayout />` component has not been used.
[Vue warn]: Component LayoutLoader is missing template or render function.
[nuxt] Your project has layouts but the `<NuxtLayout />` component has not been used.
[Vue warn]: Component LayoutLoader is missing template or render function.
[nuxt] Your project has layouts but the `<NuxtLayout />` component has not been used.
```

**Comment by doantu05150** [comment]
I tried reproducing [a demo](https://codesandbox.io/p/devbox/cocky-lumiere-sjzq66) using the latest version, but I couldn't replicate the bug. The problem might be related to the upgrading process rather than the current version.

**Comment by daver987** [comment]
I have got the same issued when I updated one of my projects as well, I'm still trying to track down what the guilty culprit is, I will let you know if I get it figured out.

**Comment by chris-visser** [comment]
Same here. Removing my .nuxt folder fixes it for me. (did'nt even need restart the app). Looks to me like it somehow loses track of  app.vue

**Comment by daver987** [comment]
Looks like they jumped the gun on closing the issue.



On Dec 27, 2023, at 12:23, Chris Visser ***@***.***> wrote:

﻿

Same here. Removing my .nuxt folder fixes it for me. (did'nt even need restart the app). Looks to me like it somehow loses track of app.vue

**Comment by waleedtariq109** [comment]
I'm also facing the same issue as well i don't know why this issue is closed even though it's a nuxt 3 bug.

```
[Vue warn]: Component LayoutLoader is missing template or render function.
[Vue warn]: Component LayoutLoader is missing template or render function.
[nuxt] Your project has layouts but the `<NuxtLayout />` component has not been used.
[nuxt] Your project has layouts but the `<NuxtLayout />` component has not been used.
[Vue warn]: Component LayoutLoader is missing template or render function.
[nuxt] Your project has layouts but the `<NuxtLayout />` component has not been used.
[Vue warn]: Component LayoutLoader is missing template or render function.
[nuxt] Your project has layouts but the `<NuxtLayout />` component has not been used.
```

**Comment by agracia-foticos** [comment]
Same issue!!!

**Comment by manniL** [comment]
@waleedtariq109 Please provide a reproduction then - happy to reopen the issue if you can provide one 👍🏻

**Comment by manniL** [comment]
@armenr Without a reproduction we can't do much here. Also, no full-blown project is needed (and actually discouraged as the reproduction should be minimal) 😋

**Comment by chris-visser** [comment]
Lol I found a consistent reproduction!  Here's the link https://github.com/chris-visser/layout-not-used

**Reproduction NuxtLayout component not used**

1. Install dependencies. (I've used pnpm)
2. Start the app using `pnpm dev`
3. Restart laptop (I'm using Windows)
4. When reinstalling or removing the nuxt folder, the warning disappears

It looks like it looses references / symlinks on laptop restart?

**One other note. Not sure if related**

When adding a new component my PyCharm IDE doesn't recognize that new component's auto import 
When using in another place after that it does somehow recognize it. This behavior is consistent 
everywhere in the app (layouts, pages and other components)

![Screenshot 2023-12-28 131947](https://github.com/nuxt/nuxt/assets/2496739/afb47880-0dad-40c8-ab75-d861b259b1bc)

**Comment by Smart-Ace-Designs** [comment]
If it helps, this only happens for me if I use Vuetify with a project and more specifically the "vuetify-nuxt-module".  I cannot get it to happen with a generic out-of-the-box Nuxt project or one with, for example, Nuxt UI added to it.

**Comment by L422Y** [comment]
I am using a single layout (`default`)

<img width="264" alt="image" src="https://github.com/nuxt/nuxt/assets/156414/492103d6-e0cb-4b80-a330-839a0f5796f6">

<img width="646" alt="image" src="https://github.com/nuxt/nuxt/assets/156414/2d588dcb-55b0-4b5f-819b-c2cab272d437">

It seems like in some cases an error in the application will prevent `_isNuxtLayoutUsed` from being set at all

<img width="482" alt="image" src="https://github.com/nuxt/nuxt/assets/156414/93525c30-824e-4e8e-adb6-57e791c6b8bf">

Not sure if this helps but I thought it couldn't hurt.

**Comment by cropr** [comment]
After some testing.  It is an issue of Nuxt 3.9, it is not present Nuxt 3.8

Steps to reproduce:
 - install nuxt 
 - add vuetify as in https://vuetifyjs.com/en/getting-started/installation/#using-nuxt-3
 - edit app.vue to 
 
```
<template>
  <NuxtLayout>
    <NuxtPage />
  </NuxtLayout>
</template>
```

**Comment by productdevbook** [comment]
It's interesting, but I suddenly got this too. I've been fine for 2 days. It just broke all of a sudden.

**Comment by Aareksio** [comment]
Not sure if reproduction is still needed, but here is one without 3rd party libs:
https://stackblitz.com/edit/github-pbst5v?file=app.vue

When running dev server, make HTML invalid, eg. delete opening `<span>` tag.
Observe error in console:
```
[nuxt] Your project has layouts but the `<NuxtLayout />` component has not been used.
```

**Comment by CharlesBT** [comment]
+1 same issue after upgrading to 3.9

**Comment by purpxd** [comment]
just getting started with nuxt version 3.9 and ran into this issue. 

[nuxt] Your project has layouts but the `<NuxtLayout />` component has not been used.

downgrading the version to 3.8 resolved it.

**Comment by nosizejosh** [comment]
Same issue. I haven't updated nuxt in the project yet project ( still on "nuxt": "^3.8.2") but running yarn dev shows
```
 $ nuxt dev
Nuxt 3.9.0 with Nitro 2.8.1      
```
and I have these warnings in the console

**Comment by manniL** [comment]
Please stop posting "+1" or "me too". Instead, simply 👍🏻 the issue!

**Comment by sharpprahs** [comment]
worked for me: 1) delete .nuxt 2) add   <NuxtLayout> <NuxtPage/> </NuxtLayout>

**Comment by devtrex007** [comment]
Make `NuxtLayout` top tag in your `app.vue ` it will fix that issue.

![image](https://github.com/nuxt/nuxt/assets/83870773/4667ca44-4a90-4e4f-92bf-dd8616b0dd34)

**Comment by swlittles** [comment]
I downloaded your new sass template, and everything worked fine for 1 day. Today I'm encountering the issue without any code changes from last night. I tried some of the solutions in this thread but nothing worked.

**Comment by mabutalid-kroma** [comment]
This issue seems to happen when you use navigateTo() in the global middleware

**Comment by ndro** [comment]
@mabutalid-kroma me too

I didn't get any warning until adding middleware with `navigateTo('/)`

`app.vue`
```vue
<template>
  <NuxtLayout>
    <NuxtPage />
  </NuxtLayout>
</template>

```
`layouts` / `default.vue`
```vue
<template>
  <div>
    <slot />
  </div>
</template>
```

Trying middleware from [Docs](https://nuxt.com/docs/guide/directory-structure/middleware#usage)
`middleware` / `test.ts`
```typescript
export default defineNuxtRouteMiddleware((to, from) => {
  if (to.params.id === '1') {
    return abortNavigation()
  }
  // In a real app you would probably not redirect every route to `/`
  // however it is important to check `to.path` before redirecting or you
  // might get an infinite redirect loop
  if (to.path !== '/') {
    return navigateTo('/')
  }
})
```

then some pages
```vue
<template>
  <div>
    <h1>Tes Page</h1>
  </div>
</template>

<script setup lang="ts">
definePageMeta({
  middleware: ["test"]
})
</script>
```

My environment
```json
"nuxt": "^3.9.3",
```
with
```text
node v20.11.0
```

**Comment by mrnasil** [comment]
Any update?

[nuxt] Your project has layouts but the `<NuxtLayout />` component has not been used.

**Comment by danielroe** [comment]
Your issue may be resolved in 3.10.1. If not, please open a new issue with reproduction.

**Comment by evgeny-myasishchev** [comment]
Upgraded to 3.10.1, same issue.

**Comment by Oscar2av** [comment]
Same issue here, I am using 3.10.0. The problem only appears while using navigateTo inside a middleware.

**Comment by fmichenaud** [comment]
No longer having the issue on 3.10.2

**Comment by Patrity** [comment]
Still encountering this issue as of 3.10.2

```json
  "dependencies": {
    "@heroicons/vue": "^2.1.1",
    "@nuxtjs/supabase": "^1.1.6",
    "@nuxtjs/tailwindcss": "^6.11.4",
    "@nuxtjs/turnstile": "^0.6.3",
    "@pinia-plugin-persistedstate/nuxt": "^1.2.0",
    "@pinia/nuxt": "^0.5.1",
    "@tailwindcss/forms": "^0.5.7",
    "@vueuse/nuxt": "^10.7.2",
    "nuxt": "^3.10.2",
    "nuxt-headlessui": "^1.1.5",
    "vue": "^3.4.19",
    "vue-router": "^4.2.5"
  },
  ```

**Comment by pavloskafritsas** [comment]
I'm also having the same issue (using the latest nuxt version: 3.10.2.

here is my App's structure:

![image](https://github.com/nuxt/nuxt/assets/30981857/df7e2650-5a3d-4560-90b8-61b1a1b6295f)

here is my browser's console output:

![image](https://github.com/nuxt/nuxt/assets/30981857/517ff11a-ceaf-431e-b30f-eca82cf0fae2)

**Comment by Dino-Kupinic** [comment]
For me the problem was that i forgot `<slot />` in my default layout.

**Comment by pavloskafritsas** [comment]
IMO, this check should run when the page has finished loading, so that v-if conditions can be evaluated first, before this check applies.

**Comment by FelixBecquart1990** [comment]
Create at the same level that app.vue an error.vue.
`<script setup lang="ts">
import type { NuxtError } from '#app'

const props = defineProps({
  error: Object as () => NuxtError
})

const handleError = () => clearError({ redirect: '/' })
</script>

<template>
  <div>

    <div>{{ error.statusCode }}</div>

    <div>{{ error.message }}</div>

    <div v-html="error.stack"></div>

  </div>
</template>`

The error was more explained from **error.stack**. I found my error and was able corrected it.

**Comment by abarke** [comment]
I'm also getting this error in a Nuxt Ionic App. In this case I am not using `NuxtPage`, because I'm using `ion-router` which I assume uses `NuxtPage`. Any way to disable this false positive warning?

![image](https://github.com/nuxt/nuxt/assets/34715541/b2936fa3-80b8-404b-a362-a2af8a96a572)

```
------------------------------
- Operating System: Windows_NT
- Node Version:     v22.1.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.15.5
- Builder:          -
- User Config:      devServer, ssr, css, modules, electron, ionic, vite, nitro
- Runtime Modules:  @nuxtjs/ionic@0.13.1, nuxt-electron@0.7.0
- Build Modules:    -
------------------------------
```

**Comment by danielroe** [comment]
IonRouter does not use NuxtPage. This should be worked around in https://github.com/nuxt-modules/ionic.

**Comment by nideajun** [comment]
我在nuxt ^3.11.2同样有这个问题，用的是node 21.7.3。 换成node 22.1.0后就没有这个问题，但是我用"exif-js": "^2.3.0",报错 ERROR  (node:23780) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.                                                                                                    09:04:30  
(Use node --trace-deprecation ... to show where the warning was created).

**Comment by adampatterson** [comment]
I know this is old, but I ran into the same issue.

Deleting my `node_modules` folder fixed the issue for me.
