### ISSUE TITLE
Multiple javascript files are loading on static build in Nuxtjs 3

### ISSUE THREAD

**Issue by anuj9196** [nuxt/nuxt#24919]
### Environment

production 

### Reproduction

- Setup new nuxtjs 3 project 
- Create an index.vue page
- Add static content (only HTML and CSS)
- run `npm run generate`

### Describe the bug

I want to generate a static site which has 0 dependency on javascript. The project is only built using HTML and SCSS.

However, after opening the static generated file, it loads various javascript files in the browser’s network tab.

How do you get rid of javascript files after the build?
```html
<link rel="modulepreload" as="script" crossorigin href="/_nuxt/entry.uEwHeBjl.js">
<link rel="modulepreload" as="script" crossorigin href="/_nuxt/default.D3HJ612v.js">
<link rel="modulepreload" as="script" crossorigin href="/_nuxt/fetch.X0yPUN-o.js">
<link rel="modulepreload" as="script" crossorigin href="/_nuxt/index.m3rl-4ZK.js">
<link rel="modulepreload" as="script" crossorigin href="/_nuxt/vue.f36acd1f.fZrwODD9.js">
<link rel="prefetch" as="script" crossorigin href="/_nuxt/error-404.3IAJHKGW.js">
<link rel="prefetch" as="script" crossorigin href="/_nuxt/error-500.M14LAvY2.js">
<script type="module" src="/_nuxt/entry.uEwHeBjl.js" crossorigin></script>
```

**Comment by manniL** [comment]
JavaScript is necessary if you want interactivity and an SPA-like behavior after the page was loaded.
If you don't need it, you can disable it via [`noScripts`](https://nuxt.com/docs/guide/going-further/features#noscripts) (can also be done per route.

You might also want to look into [Server Components](https://roe.dev/blog/nuxt-server-components) for a more granular approach to that.
