### ISSUE TITLE
[feat] useLoadingIndicator force reset function

### ISSUE THREAD

**Issue by divine** [nuxt/nuxt#24938]
### Describe the feature

Hello,

As discussed in #24900.

There should be an option for `useLoadingIndicator.start({ force: true })` so when it's called the Loading indicator should start from scratch.

Currently, after the page load it's not possible to manually start `useLoadingIndicator` because there is `setTimeout` which is basically preventing the start:

https://github.com/nuxt/nuxt/blob/f5676fba5668c3dbff8c1c40e988d469740ee82e/packages/nuxt/src/app/composables/loading-indicator.ts#L16-L23

As suggested by @manniL I could use a workaround and wait 1 second

```javascript
export default defineNuxtPlugin({
  // eslint-disable-next-line unused-imports/no-unused-vars
  async setup(nuxtApp) {},
  hooks: {
    // You can directly register Nuxt app runtime hooks here
    'page:loading:end': async function () {
      console.log('Calling startLoading function from a plugin!');
      await new Promise(r => setTimeout(r, 1000))
      startLoading();
    },
  },
});
```

Honestly, this makes loading indicator as lagging which is weird.

Thanks!

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
One could even consider making that the default behavior 🤔 (cc @huang-julien)

**Comment by huang-julien** [comment]
@divine @manniL makes sense to me :+1: . Let's see if we can make it default, maybe by having a user method and an internal one...
