### ISSUE TITLE
runtimeConfig is throwing ts errors

### ISSUE THREAD

**Issue by ahoiroman** [nuxt/nuxt#24933]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.8.0`
- Nuxt Version:     `3.9.0`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `bun@1.0.20`
- Builder:          `-`
- User Config:      `extends`, `modules`, `sanctum`, `runtimeConfig`, `i18n`, `ui`, `fontMetrics`, `googleFonts`, `devtools`, `typescript`
- Runtime Modules:  `@nuxt/content@2.10.0`, `@nuxt/ui@2.11.1`, `@nuxtjs/fontaine@0.4.1`, `@nuxtjs/google-fonts@3.1.3`, `nuxt-og-image@2.2.4`, `@nuxtjs/i18n@8.0.0`, `@nuxt/image@1.1.0`, `nuxt-auth-sanctum@0.0.14`
- Build Modules:    `-`

### Reproduction

Add 

```
    runtimeConfig: {
        apiSecret: '123'
    },
```

to `nuxt.config.ts`

### Describe the bug

If I add runtimeConfig declaration to my app, I am getting a bunch of ts errors:

> Argument type {googleFonts: {download: boolean, display: string, families: {"DM+Sans": number[]}}, extends: [string], ui: {icons: string[]}, sanctum: {baseUrl: string, origin: string}, runtimeConfig: {apiSecret: string}, devtools: {enabled: boolean}, typescript: {strict: boolean}, fontMetrics: {fonts: string[]}, modules: ("@nuxt/content" | "@nuxt/ui" | "@nuxtjs/fontaine" | "@nuxtjs/google-fonts" | "nuxt-og-image" | "@nuxtjs/i18n" | "@nuxt/image" | "nuxt-auth-sanctum")[], i18n: {defaultLocale: string, locales: ({code: string, file: string, iso: string, name: string} | {code: string, file: string, iso: string, name: string})[], lazy: boolean, detectBrowserLanguage: {cookieKey: string, useCookie: boolean, redirectOn: string}, experimental: {jsTsFormatResource: boolean}, langDir: string, strategy: string}} is not assignable to parameter type InputConfig<NuxtConfig, ConfigLayerMeta> 

![Bildschirmfoto 28 12 2023 - 00h 18min 24s@2x](https://github.com/nuxt/nuxt/assets/23051150/2228606f-7ed9-4b84-a65c-60e4bd532368)

### Additional context

This does also happen if I strip out everything and rebuild types using `bunx nuxi prepare``

![Bildschirmfoto 28 12 2023 - 00h 21min 39s@2x](https://github.com/nuxt/nuxt/assets/23051150/388d6c44-e5e6-4e80-ba6a-eecf1bed7164)

**Comment by manniL** [comment]
Can't reproduce that in a new project.

<img width="504" alt="image" src="https://github.com/nuxt/nuxt/assets/640208/58c65867-a600-4049-937c-2644648e3115">

<img width="935" alt="image" src="https://github.com/nuxt/nuxt/assets/640208/7435a64b-0f34-46f5-a9f6-0e9caa990f82">

---

Just for the sake of it - can you try a different package manager?
