### ISSUE TITLE
All 3rd party hooks dont working

### ISSUE THREAD

**Issue by productdevbook** [nuxt/nuxt#24943]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  @nuxtjs/tailwindcss@6.10.3, ()
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                              8:26:37 PM

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Reproduction

https://stackblitz.com/edit/github-zedr6v-s2bzm9

### Describe the bug

```
  nuxt.hook('tailwindcss:config', (tailwindConfig) => {
        console.log('test');
      });
```

dont see logs.

**Comment by danielroe** [comment]
The issue is simply one of ordering. Move tailwind after your module and the hook is called.

You can see the module calls the hook when it is run. Probably they should instead do it in `modules:done` after every module has a chance to register a hook.

**Comment by productdevbook** [comment]
If so, it seems like everyone in the ecosystem is unaware of it.

**Comment by danielroe** [comment]
There was no change to this behaviour in v3.9.0.

**Comment by productdevbook** [comment]
Even if I put it in, it won't work, if it is something that will be done by the module authors, is it possible that the ecosystem has been going wrong until today?  We thought he was working. :/

```ts
   nuxt.hook('modules:done', () => {
        nuxt.hook('i18n:registerModule', (register) => {
          console.log('BUG:I18N')
          register({
            // langDir path needs to be resolved
            langDir: resolver.resolve(join('brands', options.brand, 'lang')),
            locales: [
              {
                code: 'en',
                file: 'en.json',
                name: 'English',
              },
              {
                code: 'tr',
                file: 'tr.json',
                name: 'Türkçe',
              },
            ],
          })
        })
      })
```

**Comment by productdevbook** [comment]
[fixed](https://github.com/nuxt-modules/tailwindcss/issues/785#issuecomment-1872254214)
