### ISSUE TITLE
[3.9.0] Client rendering and page transitions broke after updating to the newest Nuxt version

### ISSUE THREAD

**Issue by igortrinidad** [nuxt/nuxt#24944]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.16.1
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.5.1
- Builder:          -
- User Config:      devtools, app, routeRules, experimental, runtimeConfig, modules, build, alias, dir, piniaPersistedstate, gtag, vite
- Runtime Modules:  @nuxtjs/tailwindcss@6.10.3, nuxt-icon@0.4.2, @pinia/nuxt@0.5.1, @pinia-plugin-persistedstate/nuxt@1.2.0, nuxt-gtag@1.1.2
- Build Modules:    -
------------------------------

### Reproduction

Run the app using Nuxt version 3.9.0 and navigate to any route

Check it out the live version using 3.9.0
[https://capacithor-git-nuxt-390-igortrinidad.vercel.app/](https://capacithor-git-nuxt-390-igortrinidad.vercel.app/)

### Describe the bug

The page transitions and layout rendering broken after the update, for some reason the  component SiteFooter appears above the layout <slot /> on any route client route change, but it renders properly on server side rendering (hard refresh)....

### Additional context

layouts/default.vue
```
<template>
  <div class="w-screen h-full min-h-[100vh]">
    <SiteHeader />
    <slot />
    <SiteFooter />
  </div>
</template>

<script setup>
  import SiteHeader from './site-components/SiteHeader.vue'
  import SiteFooter from './site-components/SiteFooter.vue'
</script>
```

**Comment by bounoable** [comment]
Had the same issue, fixed it by wrapping the slot with a div:
```
<template>
  <div class="w-screen h-full min-h-[100vh]">
    <SiteHeader />
    <div><slot /></div>
    <SiteFooter />
  </div>
</template>
```

**Comment by igortrinidad** [comment]
@bounoable that worked perfectly, Thanks a lot! I'll close the issue...

**Comment by DreaMinder** [comment]
It's nice to see that there's a workaround, but the bug is still there. It happens with `<nuxt-page />` component as well. I'd keep it open so that it would be visible to maintainers...

**Comment by manniL** [comment]
Follow https://github.com/nuxt/nuxt/issues/24632 then
