### ISSUE TITLE
appManifest causing non-deterministic build

### ISSUE THREAD

**Issue by jgupta** [nuxt/nuxt#24940]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.17.1
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.5
- Builder:          -
- User Config:      telemetry, nitro, extends, image, modules, pwa, vite, postcss, build, sourcemap, runtimeConfig, typescript, app, tailwindcss, experimental, features, delayHydration
- Runtime Modules:  @pinia/nuxt@0.5.1, @nuxtjs/tailwindcss@6.10.1, @nuxt/image@1.1.0, nuxt-delay-hydration@1.3.3, @vite-pwa/nuxt@0.4.0
- Build Modules:    -
------------------------------

### Reproduction

Keep appManifest: true (by default)

### Describe the bug

appManifest functionality creates a new hash in file names for every build even if source has not changed.

### Additional context

We deploy to several load balanced nodes/servers and having non-deterministic build causes 404 errors as file names are not same on all servers because of difference hash in build file names.

**Comment by SebastianBoergers** [comment]
Can confirm & reproduce.

**Comment by danielroe** [comment]
What do you suggest in your case? The ability to set the build timestamp to a value of your choosing?

I have plans when we implement https://github.com/nuxt/nuxt/issues/23392 - we can use a hash of all inputs to the build. But until then ... ideas welcome. 🙏

**Comment by Meleemaru2k** [comment]
I'd assume just setting the appManifest to false by default would help for now, with a warning in the docs that it, as of now, causes each build to hash files differently if it's enabled.

Otherwise the manual timestamp set would also work.

**Comment by alecStewart1** [comment]
Can also confirm and reproduce.

**Comment by hecktarzuli** [comment]
setting `appManifest: false` does make builds have the same filename if they don't change.  However, in testing it would appear most/all of the filenames change even if 1 file has a minor change which is just as bad.  What I'd like is similar to what we had in Webpack where filenames are based on their contents and they only change if their contents change.

**Comment by danielroe** [comment]
This should be resolved in the [nightly release](https://nuxt.com/docs/guide/going-further/nightly-release-channel#nightly-release-channel) via https://github.com/nuxt/nuxt/pull/27258, or in the next release.

Let me know if not and I'll reopen.
