### ISSUE TITLE
installation failed in cli of this command => npx nuxi@latest init 

### ISSUE THREAD

**Issue by mrayushmehrotra** [nuxt/nuxt#24956]
❯ neofetch
            .-/++/-.               as@as-Acer-One-14-Z8-415 
        `:++:`           ------------------------ 
      -++-         OS: Ubuntu 22.04.3 LTS x86_64 
    ..       Host: Acer One 14 Z8-415 
   //      Kernel: 6.5.0-1004-oem 
  ++     Uptime: 1 hour, 56 mins 
 //    Packages: 2650 (dpkg), 1 (guix-user), 8 ( 
..   Shell: fish 3.3.1 
++   Resolution: 1920x1080 
   DE: GNOME 42.9    WM: Mutter 
+s   WM Theme: Adwaita 
..   Theme: WhiteSur-Dark [GTK2/3] 
   Icons: Cupertino-Ventura [GTK2/3] 

       Terminal: gnome-terminal 
   //      CPU: 11th Gen Intel i3-1115G4 (4) @ 3.000 
    ..       GPU: Intel Device 9a78 
      -++-         Memory: 2715MiB / 7676MiB 
        `:++:`
            .-/++/-.        
![Screenshot from 2023-12-29 17-49-03](https://github.com/nuxt/nuxt/assets/110099419/33b20b63-486e-4738-8f6f-4e91b475ed10)

**Comment by manniL** [comment]
Please provide more info. What is failing? What doesn't work?

**Comment by mrayushmehrotra** [comment]
npx nuxi init newproject

[8:34:12 pm]  ERROR  Error: Failed to download template from registry: fetch failed

**Comment by manniL** [comment]
This was [asked multiple times](https://github.com/nuxt/nuxt/issues?q=failed+to+download+template+from+registry%3A+fetch+failed+) already ☺️

See e.g. https://github.com/nuxt/nuxt/issues/21853
