### ISSUE TITLE
useCookie doesn't change value of an object stored in cookie

### ISSUE THREAD

**Issue by GhostvOne** [nuxt/nuxt#24969]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-4fsr9x?file=app.vue

### Describe the bug

Same as https://github.com/nuxt/nuxt/issues/22001 
When I store an object in a cookie using useCookie composable and then want to change the value of a key of that object it doesn't effect the cookie in the web browser. The value in the ref is good but value registered in the cookie browser it not updated.

**Comment by Ganthology** [comment]
Hi, I tested the repro locally on my mac machine and it seems to be working fine. 

Not sure if it's stackblitz behaviour that did not update the cookies correctly in browser, here's a [stackblitz repro](https://stackblitz.com/edit/nuxt-starter-rhcsmb?file=app.vue) from another [issue](https://github.com/nuxt/nuxt/issues/24148#issuecomment-1802582230) related to cookie that I tested.

Attached is a demo of me running the repro locally, can notice that the cookie did update when I click refresh after hitting the button. 
Hope it helps!

https://github.com/nuxt/nuxt/assets/18641991/df40d72c-5117-4506-aaa7-120ad8340fa6
