### ISSUE TITLE
Mixins + Options Api with setup() and ordering hooks work incorrect

### ISSUE THREAD

**Issue by chz** [nuxt/nuxt#24964]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.16.1
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.13.1
- Builder:          -
- User Config:      devtools, telemetry, sourcemap, modules, css, i18n, nitro, app, vite, runtimeConfig, postcss, routeRules, typescript, features, experimental, imports
- Runtime Modules:  @pinia/nuxt@0.5.1, @nuxtjs/i18n@8.0.0, @nuxtjs/device@3.1.1, @nuxt/image@1.1.0
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-mknqgt?file=mixins%2Fseo.js,pages%2Findex.vue

### Describe the bug

Hi. I have strange problem, as i know mixins must be worked at nuxt 3 + options api. In Reproduction link i set setup with useHead in mixin and on page. from mixin not working. also ordering hook, functions is incorrect. Mounted and etc. must be called after component mounted hook.

**Comment by chz** [comment]
Or it there any idea how i can solve this ? because i used more mixins for set page title canonical alternate href

**Comment by chz** [comment]
BTW i know composables is best version. But i think this behaviour must be worked.

**Comment by manniL** [comment]
No, using `setup` in a mixin is [not supported](https://github.com/vuejs/core/issues/1866#issuecomment-674881439) in Vue.
