### ISSUE TITLE
redirect  trailing slash problem on SSG

### ISSUE THREAD

**Issue by ziaadini** [nuxt/nuxt#24974]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.9
- CLI Version:      3.10.0

### Reproduction

here is my nitro config: 
```
  nitro: {
        compressPublicAssets: true,
        prerender: {
            crawlLinks: true,
            failOnError:true,
            routes: ['/sitemap.xml'],
            ignore:['pages/dev/*'],
            autoSubfolderIndex:true,
        }
    

```

### Describe the bug

am using `SSG` , the problem is after refresh the page, user will redirect to the route with  trailing slash and after that in the client side  trailing slash is gone, google can not crawl routes because of this.

![aa](https://github.com/nuxt/nuxt/assets/15521662/ace2ac57-c38a-43f1-acfb-afec91ce26c2)

my old version of web site also was in this host and it did work okay with `vite-ssg` with this config:
```
  server: {
    fs: {
      strict: true,
    },
  },
  
   ssgOptions: {
    script: 'async',
    formatting: 'minify',
    dirStyle: 'nested',
    includedRoutes //this is my function to provide extra routes
  }

```
so i pretty sure this problem is with nitro, not my hosting provider

**Comment by manniL** [comment]
Very unlikely that this is a nuxt-related issue as Nuxt can't redirect when requesting a document when using SSG. It is not under control of your server because it only generates static files. 

Most commonly it *is* an option/feature/... of your hosting provider. E.g. netlify does that by default when using "pretty URLs".

If you provide a reproduction with regards to *how* to see the same issue when e.g. running it locally, let me know and I am happy to reopen!

**Comment by leosin** [comment]
@ziaadini Did you solve your problem? I have the same problem now.

**Comment by umar13893** [comment]
I am having the same problem. Any fix for this?

**Comment by NathanDubord** [comment]
I am also having the same problem. I tested by deploying a Nuxt 2 app and a Nuxt 3 app with the same GCS bucket/Cloudflare config and the Nuxt 2 pages do not have this problem, but the Nuxt 3 pages do. Has anyone found a solution/work-around?

**Comment by xiaoniuhululu** [comment]
I am having the same problem! Any fix for this?

**Comment by xiaoniuhululu** [comment]
> I am having the same problem! Any fix for this?

Solved, it's actually due to nginx

**Comment by Sarim-Rao** [comment]
I am having same problem in Nuxt 3 pages are not indexing in google search console giving redirect issue any suggestion

<img width="725" alt="Image" src="https://github.com/user-attachments/assets/6cd6fbef-41a2-4f89-9997-c263d7d4ad18" />

**Comment by greetfish** [comment]
My final solution is really simple, it just needs one line of configuration.

Call your files about.html instead of about/index.html in ./.output/

`  
nitro: {
    prerender: {
      autoSubfolderIndex: false,
    },
  },
`

![Image](https://github.com/user-attachments/assets/249ce4bf-3121-4243-a1c6-5489028b7394)

**Comment by ghost** [comment]
> 我的最终解决方案非常简单，只需要一行配置。
> 
> 在 ./.output/ 中将文件命名为 about.html 而不是 about/index.html
> 
> ` nitro: { prerender: { autoSubfolderIndex: false, }, },`
> 
> ![Image](https://github.com/user-attachments/assets/249ce4bf-3121-4243-a1c6-5489028b7394)



> 我的最终解决方案非常简单，只需要一行配置。
> 
> 在 ./.output/ 中将文件命名为 about.html 而不是 about/index.html
> 
> ` nitro: { prerender: { autoSubfolderIndex: false, }, },`
> 
> ![Image](https://github.com/user-attachments/assets/249ce4bf-3121-4243-a1c6-5489028b7394)

还有个配置需要调整，关于nginx中try_files $uri $uri/配置，需要调整下兜底策略，try_files $uri $uri.html

**Comment by greetfish** [comment]
你好，你的来信我已收到
