### ISSUE TITLE
我想知道loadingTemplate这个函数返回什么东西

### ISSUE THREAD

**Issue by f754699** [nuxt/nuxt#24977]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.12.1
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@7.16.1
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

无

### Describe the bug

loadingTemplate文档上说是一个函数，没说这个函数返回什么东西

“loadingTemplate” ： The document says it's a function, but it doesn't say what it returns

**Comment by owljackob** [comment]
Well, you can find out what it returns.

**Comment by danielroe** [comment]
`spaLoadingTemplate` should be a string or boolean. We currently have an issue where documentation isn't properly appearing on the website, which we can track in https://github.com/nuxt/nuxt.com/issues/1415.
