### ISSUE TITLE
(client-side) nuxt-loading-indicator stuck when in url fragment identifier or query params change.

### ISSUE THREAD

**Issue by BilalShah3** [nuxt/nuxt#24973]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.16.1
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.5.1
- Builder:          -
- User Config:      devtools, ssr, modules, runtimeConfig
- Runtime Modules:  @unocss/nuxt@0.57.7, @vueuse/nuxt@10.7.0, @formkit/nuxt@1.4.0, maz-ui/nuxt, @nuxt/image@1.1.0

### Reproduction

go to this page and 
and click on table of contents
![Screenshot 2023-12-31 020150](https://github.com/nuxt/nuxt/assets/110353066/aec18811-c47e-4e70-ba68-359e4134a0d9)

https://nuxt.com/docs/api/components/nuxt-loading-indicator#usage

### Describe the bug

nuxt-loading-indicator stuck it is not hiding when in the url fragment identifier or query params change. Even in your official docs its stuck.
you can verify there.
https://nuxt.com/docs/api/components/nuxt-loading-indicator#usage

**Comment by ridge-kimani** [comment]
Related to this [issue](https://github.com/nuxt/nuxt/issues/24928)

**Comment by manniL** [comment]
Let's track that in https://github.com/nuxt/nuxt/issues/24928 as @ridge-kimani mentioned 👍🏻
