### ISSUE TITLE
Being able to set request headers in Nuxt config routeRules

### ISSUE THREAD

**Issue by Tarabass** [nuxt/nuxt#24971]
### Describe the feature

If it's possible I want to be able to set request headers through the routeRules config section. Something like:

```js
import type { NuxtConfig } from '@nuxt/types'

const config: NuxtConfig = {
    ...
    routeRules: {
        '/api/**': {
            responseHeaders: {
                ...
            },
            requestHeaders: {
                ...
            }
        },
    },
    ...
}

export default config
```

This doesn't work:

```js
import type { NuxtConfig } from '@nuxt/types'

const config: NuxtConfig = {
    ...
    routeRules: {
        '/api/**': {
            // We only can set response headers here
            headers: {
                authorization: 'Basic ***', <-- impossible
            },
        },
    },
    ...
}

export default config
```

The problem I ran into as well was that h3 also doesn't support request headers in a server middleware, like this:

```js
/**
 * TODO: We want to set headers in this middleware before each request but it's not working
 * because this are response headers
 */
setHeader(event, 'Authorization', `Basic ${config.base24}`)
```

My workaround for now is to set headers on the event context in a middleware and pass them through to the api event handler.

auth.ts server middleware:
```js
import { RequestHeaders } from 'h3'

export default defineEventHandler((event) => {
    const config = useRuntimeConfig()

    event.context.headers = {
        Authorization: `Basic ${config.base24}`,
    } as RequestHeaders
})
```

index.get.ts:
```js
export default defineEventHandler(async (event) => {
    const config = useRuntimeConfig()
    const endPoint = config.apiEndpoint

    const response = await fetch(`${endPoint}/someEndpoint`, {
        headers: event.context.headers,
    })

    if (!response.ok) {
        throw new Error('Network response was not OK')
    }

    return await response.json()
})
```

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by Tarabass** [comment]
I just found this thread, maybe it helps for the discussion:

https://github.com/unjs/h3/issues/565

**Comment by manniL** [comment]
As a team we decided to not implement this feature. Commonly, you want to add request headers (e.g. auth tokens) because you check them somewhere in your code. The way to go would be *altering* the logic that checks it. 👍 

Feel free to provide more info on your specific use case if that general idea doesn't help ☺️
