### ISSUE TITLE
TypeScript see template refs as never

### ISSUE THREAD

**Issue by rrd108** [nuxt/nuxt#24972]
### Environment

- Operating System: Linux
- Node Version:     v18.12.1
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.21
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://codesandbox.io/p/devbox/twilight-cookies-64h529?file=%2Fapp.vue

### Describe the bug

app.vue line 3 drops a ts error: Property 'focus' does not exist on type 'never'.ts(2339)

**Comment by warflash** [comment]
You can pass the type of the ref in like this: `const input = ref<HTMLInputElement | null>(null)`
