### ISSUE TITLE
nuxt3 的tsx组件中beforeRouteEnter感觉有怪异的情况

### ISSUE THREAD

**Issue by Wlisfes** [nuxt/nuxt#24989]
### Environment

- Operating System: windows10
- Node Version: v20.10.0
- Nuxt Version: 3.8.2
- vue: 3.3.10
- vue-router: 4.2.5
- Package Manager: npm@10.2.3

### Reproduction

复现地址：https://stackblitz.com/edit/github-hi9xzq?file=app.vue,pages%2Findex.vue,pages%2Ftest.vue

### 这个Index组件beforeRouteEnter钩子函数在浏览器刷新页面的时候未执行nuxt传入的回调函数，正常的nuxt-link组件跳转就会正常执行。
```

<script lang="tsx">
export default defineComponent({
    name: 'Index',
    beforeRouteEnter(to, form, next) {
        console.log({ to, form, next })
        return next(vm => {
            console.log({ vm })
        })
    },
    setup() {
        return () => (
          <div>
            <div>Index</div>
            <nuxt-link to="/test">Text</nuxt-link>
        </div>
        )
    }
})
</script>

```

```[tasklist]
### Tasks
```

**Comment by ridge-kimani** [comment]
@Wlisfes I believe the navigation guards, e.g. `beforeRouteEnter` are designed to be used in the context of a page component. The `app.vue`  is the root component so it might not follow the same life cycles.

**Comment by mcpanl** [comment]
你咋这么装呢？不会先翻译成英文再提issues吗

**Comment by Wlisfes** [comment]
> 你咋装呢？不会先翻译成英文这么提问题吗？

噢！好的下次不提了
