### ISSUE TITLE
Nuxt 3.9.0 update gives hydration errors on NuxtUI

### ISSUE THREAD

**Issue by pixelpaulaus** [nuxt/nuxt#24994]
### Environment

N/A

### Reproduction

N/A

### Describe the bug

The update to 3.9.0 seems to be causing hydration errors with NuxtUI:

` - rendered on server: id="headlessui-popover-button-85"
  - expected on client: id="headlessui-popover-button-13"`

People are also reporting this in the NuxtUI git issues.
https://github.com/nuxt/ui/issues/1171

**Comment by manniL** [comment]
Repro via https://github.com/nuxt/ui/issues/1171 - https://stackblitz.com/edit/nuxt-starter-5tmfpt?file=components%2FUserForm.vue

Seems to be more like a Nuxt UI issue though. Let's track there.
