### ISSUE TITLE
When I use the element-plus framework, the script information returned by the request is displayed on the page

### ISSUE THREAD

**Issue by YTaoger** [nuxt/nuxt#24999]
### Environment

Working directory: ~/project/SASS                                                                
Nuxt project info: (copied to clipboard)                                                                                        

------------------------------
- Operating System: Darwin
- Node Version:     v18.18.2
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, devServer, ssr, vite
- Runtime Modules:  -
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                                     

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Reproduction

I didn't have this problem previewing in stackblitz!
So I want to know exactly where the problem is?

### Describe the bug

When I use the element-plus framework, the script information returned by the request is displayed on the page.
I am using Google Browser, which uses the fehelper browser plugin, when the page is opened, it will display the contents of the script on the page, I would like to confirm whether the problem is fehelper or nuxt? Or is it the element-plus problem?
In nuxt.config.ts, I set the ssr to false, but I had to.
<img width="788" alt="image" src="https://github.com/nuxt/nuxt/assets/35984856/e2304545-0039-473a-a065-0edc85d1fce3">
<img width="1338" alt="image" src="https://github.com/nuxt/nuxt/assets/35984856/cec93db2-bdb2-41a3-a524-1395e85648ac">

**Comment by manniL** [comment]
Does that also happen when not using element-plus?

**Comment by YTaoger** [comment]
> Does that also happen when not using element-plus?
> 
> If StackBlitz doesn't show that problem, please provide a minimal GitHub repo ☺️

Yes, this happens when I use element-plus
This is a minimal GitHub repo:
https://github.com/YTaoger/nuxt-repo.git
Here's how I ran it

https://github.com/nuxt/nuxt/assets/35984856/3c34deee-af25-42ab-b246-172a8114d5e4

**Comment by manniL** [comment]
I see that also ssr is disabled via `ssr: false`. Then it'd be the best to raise it in element-plus 👍🏻

**Comment by YTaoger** [comment]
> I see that also ssr is disabled via `ssr: false`. Then it'd be the best to raise it in `element-plus` or `fehelper` 👍🏻
> 
> Weirldy the `__NUXT_DATA__` json is rendered which should be part of the nuxt page in all cases.

Oh, what I understand is that I'm supposed to optimize in `element-plus` or `fehelper`, right?
What should I do about the fact that the contents of `__NUXT_DATA__ `will be treated as parsing?

**Comment by manniL** [comment]
> Oh, what I understand is that I'm supposed to optimize in element-plus or fehelper, right?

Yes, correct. Not sure why fehelper is triggered by the element-plus button but it should be between these two. It most likely is the same when using "plain vue" and having some JSON in the HTML 🤔

> What should I do about the fact that the contents of __NUXT_DATA__ will be treated as parsing?

Just as extra info, not sure if it'll be useful for debugging.

**Comment by YTaoger** [comment]
> > Oh, what I understand is that I'm supposed to optimize in element-plus or fehelper, right?
> 
> Yes, correct. Not sure why fehelper is triggered by the element-plus button but it should be between these two. It most likely is the same when using "plain vue" and having some JSON in the HTML 🤔
> 
> > What should I do about the fact that the contents of **NUXT_DATA** will be treated as parsing?
> 
> Just as extra info, not sure if it'll be useful for debugging.

Ok, I see. Thank you!
This doesn't happen again when I disable fehelper, I can only disable fehelper for now.

**Comment by YTaoger** [comment]
> Just as extra info, not sure if it'll be useful for debugging.

@manniL  Sorry, but I still want to know, why is this json information in a script tag with the `type = "application/json"` attribute, I still don't understand here, can optimize it in which version?
Because I think that even if the developer disables the json parsing tool, there is no guarantee that the customer is not using the json tool in the browser.I have used the `build` command to package and see that this code is still in the code.
I would say that's always a concern!
``` js
<script type="application/json" id="__NUXT_DATA__" data-ssr="false">[{"_errors":1,"serverRendered":2,"data":3,"state":4,"once":5},{},false,{},{},["Set"]]</script>
```

**Comment by manniL** [comment]
> Because I think that even if the developer disables the json parsing tool, there is no guarantee that the customer is not using the json tool in the browser.

Then they would have problems with half of the web I'd say 🙈
Most sites nowadays have some part of JSON, be it for serialization (as in Nuxt's case), for plain config or similar.

<img width="796" alt="image" src="https://github.com/nuxt/nuxt/assets/640208/7b657d2d-cb04-4840-8605-8d56a473e0a4">


> I have used the build command to package and see that this code is still in the code.
> I would say that's always a concern!

No, that is intended and needed. This is the way how nuxt initializes some global data (e.g. if the size is server-rendered or not)

**Comment by bbhxwl** [comment]
我也碰到了同样的问题，没有更好的解决办法了么？

**Comment by YTaoger** [comment]
> 我也碰到了同样的问题，没有更好的解决办法了么？

我目前是没有想到更好的解决办法，只能禁用了插件

**Comment by bbhxwl** [comment]
> > 我也碰到了同样的问题，没有更好的解决办法了么？
> 
> 我目前是没有想到更好的解决办法，只能禁用了插件

是只有这1个插件会这样吧？

**Comment by YTaoger** [comment]
> 是只有这1个插件会这样吧？

是的，我目前遇到的就是这样的，应该是只要json解析的插件，都会这样吧，是那段script脚本，触发了json解析的动作

**Comment by Ackerman-Levi** [comment]
在**nuxt.config.js** 中的 **plugins** 配置项中配置插件的路径，并将 **ssr** 属性值设置为 **false** 
`plugins: [
  {
    src: '~/plugins/element-ui', 
    ssr: false
  }
]`
**ssr: false** 插件只会在客户端运行

**Comment by YTaoger** [comment]
> 在**nuxt.config.js** 中的 **plugins** 配置项中配置插件的路径，并将 **ssr** 属性值设置为 **false** `plugins: [ { src: '~/plugins/element-ui', ssr: false } ]` **ssr: false** 插件只会在客户端运行

我在`nuxt.config.ts` 中使用的是`modules` 形式的`@element-plus/nuxt` ，不是`plugins` 的方式，并且`ssr: false` 是正确设置了的，本来做的就是客户端渲染
