### ISSUE TITLE
Href use svg symbol

### ISSUE THREAD

**Issue by gyxoBka** [nuxt/nuxt#25005]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

[StackBlitz](https://stackblitz.com/edit/nuxt-examples-7qpsts?file=pages%2Findex.vue) reproduction

### Describe the bug

[Vue Router warn]: No match found for location with path "/assets/sprite/gen/svg-symbols.svg/" in console

UISvgIcon component that draw icon as svg sprite but after update version of nuxt it's broken. it looks like nuxt doesn't recognize this as a link because other files in the root are opening correctly.

this worked until the nuxt version 3.8.2

### Additional context

I'm sorry, I have one more question. After update appeared warn: 
`[nuxt] Your project has layouts but the `<NuxtLayout />` component has not been used.`

this is also in the same stackblitz.  Layout works fine.
Explain me please is this way to do layouts is worng and i have to use App.vue ?

**Comment by manniL** [comment]
Re layout: You can ignore that. See https://github.com/nuxt/nuxt/issues/24912
