### ISSUE TITLE
Latest sass 1.69.6 doesnt work - Cannot read properties of undefined

### ISSUE THREAD

**Issue by MickL** [nuxt/nuxt#25012]
### Environment

- Operating System: Darwin
- Node Version:     v21.0.0
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, css
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

It does NOT happen on Stackblitz for some reason:
https://stackblitz.com/edit/github-qarseh

But I confirmed by creating a new project on my machine:

- `nuxi init sass-test`
- `cd sass-test`
- `yarn add sass`
- Put this in nuxt.config.ts: `css: ['~/assets/styles/main.scss']`
- Create file: `assets/styles/main.scss`
- `yarn dev`

### Describe the bug

Using the latest version `1.69.6` of `sass` which has been released 5 days ago throws an error when starting with `nuxt dev`:

> [5:54:18 PM]  ERROR  Pre-transform error: Preprocessor dependency "sass" failed to load:
> Cannot read properties of undefined (reading 'indexOf')

And then when visiting localhost:

> 500
> [vite-node] [plugin:vite:css] [VITE_ERROR] /assets/styles/main.scss

Downgrading to `1.69.5` works

**Comment by danielroe** [comment]
This is likely a sass or vite issue rather than a Nuxt one. Would you see if you can reproduce without Nuxt? 

https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter
