### ISSUE TITLE
Adding node polyfills to nuxt

### ISSUE THREAD

**Issue by paro-paro** [nuxt/nuxt#25016]
### Environment

- Operating System: Darwin
- Node Version:     v20.10.0
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.12.1
- Builder:          -
- User Config:      ssr, devtools, vite
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

Repro:

1. [vite-vue](https://stackblitz.com/edit/vitejs-vite-frjpo1)
2. [vite-nuxt](https://stackblitz.com/edit/github-y9hcb5) (SPA)

Both cases use vite 5.x (nuxt 3.9.0)

### Describe the bug

Hi!

I am trying to integrate the following authentication library [@web3auth/modal](https://www.npmjs.com/package/@web3auth/modal) into my nuxt app.

Despite being distributed as a "browser" library... it requires adding a few [polyfills](https://web3auth.io/docs/troubleshooting/vite-issues) in order to work, so I am using the [vite-plugin-node-polyfills](https://github.com/davidmyersdev/vite-plugin-node-polyfills) to handle them.

Unfortunately, I can only seem to make it work in a simple vite+vue application but not in nuxt (SPA mode).

Both cases share the same simple `App.vue` / `app.vue` file (see below) and in both cases the vite/nuxt dev server is run successfully.

The problem seems to be related with the build stage. Running `vite build` in the first case (vite+vue) will successfully build the application and `vite preview` will serve a fully functional production app. 

But in nuxt, despite setting `ssr` option to `false` and running `nuxt generate` (which successfully builds the app in SPA mode) (.output/public chunks are almost identical to the first case, as expected) serving the static app will throw an error when clicking in the sign in button =>  `exports are not defined`

I do understand that polyfills are messy, that browser-library authors should avoid them ([not this time, unfortunately](https://github.com/Web3Auth/web3auth-web/issues/1430#issuecomment-1489805525)) and that the vite plugin that I am using is not an official one (I have tried many other polyfills plugins/libraries and custom configurations with no luck so far...) but I was kind of hoping that maybe this "simple" use case might have a quick solution if I find the right nuxt configuration option or something like that.

Any help or guidance will be really appreciated. 

Thanks in advanced and happy new year!

### Additional context

`App.vue`- `app.vue` (same in both cases)

```vue
<script setup lang="ts">
const onSignIn = async () => {
  try {
    const pkg = await import('@web3auth/modal')
    const auth = new pkg.Web3Auth({
      clientId: 'random',
      chainConfig: {
        chainNamespace: 'eip155',
      },
    })

    await auth.initModal()
    await auth.connect()
  } catch (error) {
    console.log((error as Error).message)
  }
}
</script>

<template>
  <div>
    <div>Polyfilling: web3auth/modal</div>
    <button @click="onSignIn">Sign In</button>
  </div>
</template>
```

`vite.config.ts`

```ts
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import { nodePolyfills } from 'vite-plugin-node-polyfills'

export default defineConfig({
  plugins: [vue(), nodePolyfills()],
})

```

`nuxt.config.ts`

```ts
import { nodePolyfills } from 'vite-plugin-node-polyfills';

export default defineNuxtConfig({
  ssr: false,
  devtools: { enabled: false },
  hooks: {
    'vite:extendConfig': (config) => {
      config.plugins!.push(nodePolyfills()); // unshift ?
    },
  },
  // not completely sure what's the recommended way to extend vite's plugins in nuxt!
  // vite: {
  //   plugins: [nodePolyfills()],
  // },
});
```

**Comment by manniL** [comment]
This works fine for me in the provided Nuxt reproduction. It just takes ages to load - might be a StackBlitz thing.

<img width="1721" alt="image" src="https://github.com/nuxt/nuxt/assets/640208/6d62bed3-4ae6-4a98-bd6b-4e14c17e4a64">

Locally that works fast and fine 👍🏻

PS: I'd use the 2nd approach to update the vite config (via `vite.plugins`).

**Comment by paro-paro** [comment]
Hi @manniL 

No, it does not work. You have checked the dev server, which works fine.

But if you `nuxt generate` the app and then serve the static application you will get an error in the console (the modal wont be shown never).

1) npm run generate
2) npx serve .output/public

<img width="364" alt="Screenshot 2024-01-03 at 10 43 24" src="https://github.com/nuxt/nuxt/assets/43136874/fa215284-02f5-444f-86ff-74f4e59f7271">

<img width="1505" alt="Screenshot 2024-01-03 at 10 44 50" src="https://github.com/nuxt/nuxt/assets/43136874/8f3a3ad2-868a-4246-b3e9-77d9be464177">

PS: Thanks for the recommendation!

**Comment by manniL** [comment]
My bad 🙈
I'll have another look 👍🏻

**Comment by paro-paro** [comment]
No problem!! Thanks! 🙏

**Comment by pi0** [comment]
Related: #12830

We made and use [unjs/unenv](https://github.com/unjs/unenv) polyfill for server bundle node polyfills. It is a much better maintained framework for node polyfills.

**Comment by manniL** [comment]
I think that issue might be best fixed in https://github.com/davidmyersdev/vite-plugin-node-polyfills. I've tried to use `unenv` for the resolves which also works, but I also needed to spare `buffer`. This works fine.

**Comment by manniL** [comment]
Closing here as a workaround is now available and the main "issue" to track unenv polyfilling for client/vite is #12786

**Comment by paro-paro** [comment]
Thanks a lot for the workaround. You guys are great!

**Comment by paro-paro** [comment]
Guys, sorry to bother again with what might be a simple or stupid question...

My issue is completely solved... but may I ask why the use of the [unjs/unenv](https://github.com/unjs/unenv) library will work but aliasing to a different one, such as [node-stdlib-browser](https://github.com/niksy/node-stdlib-browser) (the one that the [vite-plugin-node-polyfills](https://github.com/davidmyersdev/vite-plugin-node-polyfills) uses under the hood), fails in a nuxt app but works on a vite+vue app?

Is it related to the fact that when dealing with SSR (universal code) production bundles have to be carefully crafted/synced for both client and server? Is is just the quality of the targeted library? Maybe something else? 

Again, thanks a lot for your help and a big shout out to the amazing work that you guys do within the frontend/javascript ecosystem. The [unjs](https://unjs.io/) project is just incredible ❤️

**Comment by pi0** [comment]
I haven't tested `node-stdlib-browser` but at least [their buffer is unimplemented](https://github.com/niksy/node-stdlib-browser/blob/master/mock/buffer.js) and they have [dozens of browserify dependencies](https://github.com/niksy/node-stdlib-browser/blob/e4d4583067d24f1ab32c49cee19990ea12ce029d/package.json#L51) (in unenv they are reimplemented or ported some of browserify stuff is literally from a decade ago!) and it covers less node APIs... Otherwise, there is no reason it doesn't work in Nuxt if you use an alias.

**Comment by transtone** [comment]
https://nuxt.com/blog/v3-10#client-side-nodejs-support
