### ISSUE TITLE
@PdxLook 我确实是在服务器端升级pm2到最新版本后这个问题就不存在了

### ISSUE THREAD

**Issue by PdxLook** [nuxt/nuxt#25023]
@PdxLook 我确实是在服务器端升级pm2到最新版本后这个问题就不存在了

_Originally posted by @xxwangkaimin in https://github.com/nuxt/nuxt/issues/24206#issuecomment-1874967344_
我线上部署服务器是宝塔，通过宝塔配置的PM2,升级到最新同样存在此问题。请问你是怎么配置的PM2? 我来试着部署一下
```[tasklist]
### Tasks
```

**Comment by xxwangkaimin** [comment]
@PdxLook 我没有用宝塔这个软件，我是直接在服务器上安装了nvm来控制nodejs版本、pm2、Nginx等这些依赖。
![image](https://github.com/nuxt/nuxt/assets/33536543/c7140108-61c6-4368-a0ce-c3c50cdff2fd)
pm2运行配置：
![image](https://github.com/nuxt/nuxt/assets/33536543/ebbcecd3-78e9-4964-8d0d-46a5115964be)

**Comment by PdxLook** [comment]
@xxwangkaimin  感谢，这边来操作一下

**Comment by PdxLook** [comment]
[project-name.zip](https://github.com/nuxt/nuxt/files/13816855/project-name.zip)
This is the project code, please understand the big God take a look at what is the situation
![image](https://github.com/nuxt/nuxt/assets/117615674/3a1fcbaf-8805-4145-9b3d-e09113653111)

**Comment by manniL** [comment]
Let's track in #25024.
