### ISSUE TITLE
Incremental call of watch if Page use defineNuxtComponent Setup - Maybe a Memory Leak?

### ISSUE THREAD

**Issue by LuXDAmore** [nuxt/nuxt#25029]
### Environment

Nuxt project info:
------------------------------
- Operating System: Windows_NT
- Node Version:     v18.18.2
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

[Basic Live view](https://77fmvd-3000.csb.app/subfolder)
[Code](https://codesandbox.io/p/devbox/nuxt-v3-bug-watch-called-multiple-times-77fmvd)

### Describe the bug

I've created an example with 4 different types of routes:
- 2 routes created with the setup component;
    - _One route with `definePageMeta({ key: (route) => route.fullPath });` e one without_
- 2 routes created with the defineNuxtComponent-setup;
    - _One route with `definePageMeta({ key: (route) => route.fullPath });` e one without_

Every route have the same code (one inside <script setup> and one inside defineNuxtComponent-setup):
```js

    const { pending, data: todo } = await useLazyAsyncData(
      `define-component-key-todos-${ idSubfolderDefineComponentKey }`,
      () => $fetch( `https://jsonplaceholder.typicode.com/todos/${ idSubfolderDefineComponentKey || "" }` ),
    );
    const single = computed(() => todo.value ?? {});
    const singleChangedTimes = ref(0);

    console.info("todo", todo.value);

    watch(single, (newSingle, oldSingle) => {
      console.info("newAndOldSingle", newSingle, oldSingle);
      singleChangedTimes.value++;
    });

```

From this code you can see I'm using the `useLazyAsyncData` that is returning a **Ref** named **todo**.

Now, if you navigate the browser and look at the console you can see some different behaviours.

### Step to reproduce

- Click on '_Go to idSubfolder - No PageKey - Setup 1_' **for the first time** you can see in the console that there are 2 console log, one empty e one when the watch is called: ![First click on Setup no PageKey](https://github.com/nuxt/nuxt/assets/3841171/986c416b-10d4-47c7-9a9a-a06a9bcadded)
- Click on '_<-- Go back_';
- Click again on '_Go to idSubfolder - No PageKey - Setup 1_' (so, for the **second time**) you can see in the console that there are 2 console log, one with the old value (from the previous one) and another one when the watch is called: ![Second click on Setup no PageKey](https://github.com/nuxt/nuxt/assets/3841171/599b3b4d-3409-41e7-8081-2c61d06c9d04)
- Now you can repeat the same steps for every route type;
- '_Go to idSubfolder - With PageKey - Setup 1_', two info are logged in the console, one on the first click and one on the second: ![First click on Setup with PageKey](https://github.com/nuxt/nuxt/assets/3841171/262b11e2-34bd-404f-9ffd-0a50c7a2e75c)
![image](https://github.com/nuxt/nuxt/assets/3841171/65bb0f9b-ca38-4560-a171-3e950af36bdf)

- 🔴 Now, the issue seems to appear if you are trying to follow the same steps on **a page declared with defineNuxtComponent**.
- Click on '_Go to idSubfolder - With PageKey - With Define component 1_' then '_<-- Go back_' and then again on '_Go to idSubfolder - With PageKey - With Define component 1_', you will immediately see that in the console the watch is called multiple times, and it's incremental based on how many times you've entered the same page (here after 4 click on the same page): ![Fourth click on defineNuxtComponent-Setup no PageKey](https://github.com/nuxt/nuxt/assets/3841171/6a8bd8c0-8c20-452d-818f-685fbee43f93)

### Additional context

I'm not sure, but this could be a **Memory Leak**.
And maybe the problem is related to the **Ref** given by the _useLazyAsyncData_,
because the GC is not able to release the memory and the **watch** still have a reference to the previous given value.
This is why in every page the previous _watch_ is called and a new one is also instantiated.

> Using `definePageMeta({ key: (route) => route.fullPath });` does not fix the problem.

I've also added a variable (`singleChangedTimes`) to check how many times the actual **watch** is called, and its value is **always 1**.

```js

   const { pending, data: todo } = await useLazyAsyncData(
      `define-component-key-todos-${ idSubfolderDefineComponentKey }`,
      () => $fetch( `https://jsonplaceholder.typicode.com/todos/${ idSubfolderDefineComponentKey || "" }` ),
    );
    const single = computed(() => todo.value ?? {});
    const singleChangedTimes = ref(0);

    console.info("todo", todo.value);

    watch(single, (newSingle, oldSingle) => {
      console.info("newAndOldSingle", newSingle, oldSingle);
      singleChangedTimes.value++;
    });

```

Note: if you add a `useFetch/$fetch` inside the watch callback, you can see in the _Newtwork Tab_ that you have the same problem and that the _Network Fetch number is incrementing on every page view_.

Btw, I'm not a Node memory expert 😄 , so I'm sorry if i said something wrong..

**Comment by manniL** [comment]
@LuXDAmore does that also happen in prod and not only in the dev build? ☺️

**Comment by LuXDAmore** [comment]
@manniL Yes, it happen also in the Prod build

**Comment by manniL** [comment]
It might be related to how async is handled when not using `<script setup>`. See [Anthony's blogpost](https://antfu.me/posts/async-with-composition-api) for detailed info.

**Comment by LuXDAmore** [comment]
@manniL It's mandatory to use the **useLazyAsyncData** with the `async/await`? I mean.. It's lazy 🤔  ...

I've added a route with a **useLazyAsyncData** without the `async/await` and I can see that everything is still working as expected.. Mmm, but the problem of the `watch callback` is persisting also in this route.
