### ISSUE TITLE
Vitest can't resolve import '#imports'(Nuxt3, vitest)

### ISSUE THREAD

**Issue by gyofeel** [nuxt/nuxt#25021]
### Environment

ENV
os: Darwin
nodejs: 20.9.0
nuxt: 3.8.1
@nuxt/test-utils: 3.8.1
vitest: 1.1.1
yarn: 1.15.2

### Reproduction

https://stackblitz.com/edit/nuxt-starter-rx4vx2?file=package.json,testUtils.js,testUtils.test.js

you can run test command below.
```
npm test
``` 

### Describe the bug

Hello, I am using Vitest for testing on Nuxt3, vite env.
Due to our team's convention, the configuration uses 'autoImport: false'.(For an explicit declaration) So when importing Nuxt's built-in items (useRoute, nextTick, computed, etc.) we use import '#imports'.

When I run Vitest, the following error occurs:

Error: Failed to resolve import "#imports" from "[file path]". Does the file exist?
How do I solve this? help.
Is this something that needs to be fixed in vitest?
(I registered an issue on vitest. https://github.com/vitest-dev/vitest/issues/4853)
(https://github.com/nuxt/nuxt/discussions/24719)

Below is my vitest.config.js
```javascript
import path from 'path';
import vue from '@vitejs/plugin-vue';

export default {
    plugins: [vue()],
    test: {
        globals: true,
        environment: 'jsdom'
    },
    resolve: {
        alias: {
            '@': path.resolve(__dirname, './src')
        }
    }
};
``` 

Thanks.

**Comment by manniL** [comment]
Have a look into the [nuxt test utils](https://github.com/nuxt/test-utils/) which allow you to test components in a nuxt environment. There, aliases should work easily too 👍🏻

**Comment by gyofeel** [comment]
@manniL 
Thank you for replying.
But #imports is not my alias but nuxt's implicit object you know.
And I'm using test-utils already.
Can you share some hints on how to resolve #imports using vitest and @nuxt/test-utils (if there is a way to do so without causing an error)?

**Comment by Vittorio-QA** [comment]
> @manniL Thank you for replying. But #imports is not my alias but nuxt's implicit object you know. And I'm using test-utils already. Can you share some hints on how to resolve #imports using vitest and @nuxt/test-utils (if there is a way to do so without causing an error)?

I ve been struggling with the same issue. Been looking github tickets about this and it seems it is still unresolved. Please let me know if you found a solution.

**Comment by gyofeel** [comment]
@manniL 
I resolved this issue as below.
https://github.com/nuxt/test-utils/issues/700

Thank you for your replying.
