### ISSUE TITLE
useAsyncData with $fetch  layout typescript problem

### ISSUE THREAD

**Issue by htchtc052** [nuxt/nuxt#25034]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.5.1`
- Nuxt Version:     `3.9.0`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `npm@10.2.5`
- Builder:          `-`
- User Config:      `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

1)Create new project 
2) Add page with async data and $fetch request and output results in template
3) Can see error in code editor

### Describe the bug

```
<script setup lang="ts">

interface Post {
  id: number;
  userId: number;
  title: string;
}

const { data: posts, pending } = await useAsyncData<Post[]>(
"posts",
() => $fetch("https://jsonplaceholder.typicode.com/posts"),
{
default: (): Post[] => [],
}
);

console.debug(posts.value);
</script>
<template>
  <div v-if="pending">Loading...</div>
  <div v-else>
    <ul>
      <li v-for="post of posts" :key="post.id">{{ post.title }}</li>
    </ul>

  </div>
</template>
```

In ul > li section view typescript error Unresolved variable title  and wrong type of post variable post: any | any

Repository with problem https://github.com/htchtc052/nuxt3_fetch_typescript_problem

**Comment by manniL** [comment]
<img width="1642" alt="image" src="https://github.com/nuxt/nuxt/assets/640208/18999df2-6e47-4365-83b3-f9caed012c32">

Can't repro. Make sure that:
* your IDE has Volar installed and uses takeover mode
* Your dev server ran
* You've tried restarting the IDE at least once

If that didn't help, what does `npx nuxi typecheck` return?

**Comment by htchtc052** [comment]
alekslog@MacBook-Pro-Aleks test-fetch % npx nuxi typecheck

Don't return anything 

Used webstorm ide. Restart and re-open project many time.

**Comment by htchtc052** [comment]
<img width="1502" alt="image" src="https://github.com/nuxt/nuxt/assets/17771913/c03394e6-e04a-43b4-a1ad-439c3bf28b32">

**Comment by manniL** [comment]
I'm afraid I don't use JetBrains/WebStorm (anymore). If `typecheck` doesn't throw any errors, it must be based on the configuration of the IDE.
Maybe it is the best to raise an issue in JetBrain's issue tracker then 👍🏻
[Might be related](https://youtrack.jetbrains.com/issue/WEB-62037/Nuxt-correctly-infer-type-of-data-retrieved-via-useFetch)

**Comment by htchtc052** [comment]
> I'm afraid I don't use JetBrains/WebStorm (anymore). If `typecheck` doesn't throw any errors, it must be based on the configuration of the IDE. Maybe it is the best to raise an issue in JetBrain's issue tracker then 👍🏻 [Might be related](https://youtrack.jetbrains.com/issue/WEB-62037/Nuxt-correctly-infer-type-of-data-retrieved-via-useFetch)

I see discusion from JetBrains issue. But there's no solution. 

Please recommend a compromise solution for this problem. I need develop in webstorm because autoimport. May be with computed?

**Comment by manniL** [comment]
> Please recommend a compromise solution for this problem. I need develop in webstorm because autoimports. May be with computed?

But Nuxt provides auto imports? :D

Unfortunately I can't tell you. I only can tell you that this isn't a nuxt problems and types are working as expected. It is an IDE or config issue.
