### ISSUE TITLE
Fast Navigation on SSG Initial Page Load Causes Nuxt to Rerun Asyncdata and Not Load payload.json

### ISSUE THREAD

**Issue by kangelopoulos** [nuxt/nuxt#25049]
### Environment

- Operating System: Windows_NT but has happened on multiple systems
- Node Version:     v18.19.0
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      build, nitro, runtimeConfig, modules, plugins, gtm, lazyLoad, $meta, dayjs, css, vite
- Runtime Modules:  @nuxtjs/google-fonts@3.1.0, @nuxt/image@1.1.0, nuxt-lazy-load@3.0.4, @zadigetvoltaire/nuxt-gtm@0.0.13, dayjs-nuxt@2.1.9, @samk-dev/nuxt-vcalendar@1.0.2, @pinia/nuxt@0.5.1
- Build Modules:    -

### Reproduction

Will provide asap - I'm wrapping up a big project and will need to jury rig a solution around this first. Expect it by 1/6/2024.

### Describe the bug

This is occurring on statically rendered sites in Nuxt 3. The site is prerendering using Nitro. Some routes are SSR, more are prerendered, a few are CSR. What's happening is, on first page load, if someone attempts to quickly (in less than a second) hit one of navigation links, then the payload.json that should be returned is not returned and instead Nuxt attempts to rerun asyncdata, but fails to do that as well. 

Below is an extremely simplified version of the asyncData on the statically rendered page. What's interesting is the console log will log when this bug occurs, but will not log on normal navigation. It seems as though asyncData is rerunning when it shouldn't be for these static pages if the navigation link is clicked too quickly on the first page load. After that, I'm not having issues with further navigation. 

```javascript
async asyncData() {
   try {
      console.log('i am here')
      const route = useRoute()
      const { category } = await $fetch(`/category/${route.params.category}`)
      return { category, error: null }
    } catch (e) {
      return {
        error: e
    }
 }
``` 

I do wonder if it relates to this closed issue: #13350. When I upgraded some of the random, unclear error messages disappeared. However, with this new asyncData bug, what seems to happen is it attempts to rerun asyncData but does not wait to try to render the page and considers the "category" 'undefined.' As a string, which is making it difficult for me to even keep the user out of a complete error state. How it got to 'undefined' I have no idea. Feel free to tell me if any of this sounds like an operator error.

### Additional context

The navigation links I'm referring to are all prefetched nuxt links.

**Comment by manniL** [comment]
Still tagging it with "needs reproduction" - looking forward to it 👍🏻

**Comment by kangelopoulos** [comment]
So I just tried to create a reproduction - even calling for large amounts of data to try to mimic how large the repo I'm working on is. It doesn't work. But I did find this ticket #9448 - I know it was in Nuxt v2 but it is exactly the issue I'm experiencing. It seems to have something to do with a file nuxt is loading onto the browser on the first page hit since sometimes it happens, sometimes it doesn't, and it happens more often for our team members (like me) who are furthest away from the server. It's only a fast navigation on the first page hit. 

I don't know if you can help me since I can't reproduce it...

**Comment by bernhardberger** [comment]
I can see similar behavior even in SSR/ISR and dev server where I can force suspend to break when navigating before the page is fully hydrated. I think it can be made more evident when using a page transition.

**Comment by kangelopoulos** [comment]
Yeah, it still seems to have something to do with the Suspense component and I don't think these minimal reproduction links are going to cut it. It may still be upstream with Vue.

**Comment by kangelopoulos** [comment]
I diagnosed the issue - it's in our code, not Nuxt!

**Comment by pixelpaulaus** [comment]
> I diagnosed the issue - it's in our code, not Nuxt!

i am having similar issues, and gone through all my code and cant find anything.
Do you mind sharing what your issue was so I can see if it would be similar in my code?
