### ISSUE TITLE
Page transition should support navigation backward.

### ISSUE THREAD

**Issue by kaokei** [nuxt/nuxt#25042]
### Describe the feature

I hope the page transition could support backward navigation.

The page transition animations triggered by navigating forward and backward should be different. 

For instance, if there are three pages labeled A, B, and C, when transitioning from A to B and then to C, the expected animation effect is `the current page fades out, and the new page slides in from the right.`

If navigating back from C to B and then to A, the expected animation effect is `the current page slides out from the right, and the new page fades in.`

However, the current implementation results in the same effect for both scenarios: `the current page fades out, and the new page slides in from the right.`

I'm not sure if there's a mature solution available to achieve this. Any suggestions?

---------

一句话解释需求：页面前进和页面会退触发的页面过度动画应该可以是不一样的。
假设我又3个页面：A B C
当我一次从A页面进入B页面，然后再进入C页面时，我期望的动画效果是`当前页面淡出，新页面从右侧滑入`。
如果我从C页面返回B页面，再返回A页面，我期望的动画效果是`当前页面从右侧滑出，新页面淡入`。

但是实际上的效果都是`当前页面淡出，新页面从右侧滑入`。

我不知道当前是否有成熟的方案可以做到这一点呢？

### Additional information

- [x] Could this feature be implemented as a module?
- [x] Would you be willing to help implement this feature?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by bernhardberger** [comment]
This is something that imho needs to be handled on the implementation side of the custom transition effect one creates and not in the framework itself?

**Comment by manniL** [comment]
Indeed! This should work fine with CSS already and is shown in the docs too https://nuxt.com/docs/getting-started/transitions#page-transitions.
