### ISSUE TITLE
Cloudflare Pages Environment Variables not working

### ISSUE THREAD

**Issue by nicogenz** [nuxt/nuxt#25047]
### Environment

Cloudflare Pages

### Reproduction

https://github.com/nicogenz/cf-pages-env-test

### Describe the bug

When deploying a Nuxt3 project to Cloudflare Pages with default configuration, the environment variables are not working. They are always empty, even when set in Cloudflare. To reproduce the issue you can clone the repo above, deploy it to cloudflare pages, set the `NUXT_SECRET_KEY` environment to anything you want and once deployed visit `/api/test`. There you will see that an empty string is returned instead of the value you entered in your cloudflare dashboard.

**Comment by nicogenz** [comment]
@manniL `useRuntimeConfig(event)` fixed it. Thank you

**Comment by manniL** [comment]
(According to @pi0 it should *not* be necessary to pass the event though 🙈)

**Comment by nicogenz** [comment]
For me it only worked when i passed the event. I was using the latest Nuxt version, 3.9.0, at the moment

**Comment by pi0** [comment]
Reproduction link gives 404. You don’t necessarily need to pass event but then have to make sure useRuntimeConfig is being called within the request context not ambient top level. This is a requirement/limitation of cf.

If also within the context you call it and it won’t access variables, it might be a bug in which case a runnable reproduction would be welcome.

**Comment by nicogenz** [comment]
@pi0 I deleted the repo earlier. Just recreated it. You should now be able to see it under https://github.com/nicogenz/cf-pages-env-test

**Comment by pi0** [comment]
Thanks for confirming 👍🏼 You are correct. My early answer to Alex was based on assumption for when default `event` to `useEvent()` but it is going to take a while.

I have made upstream tracker issue https://github.com/unjs/nitro/issues/2054 and have some ideas to mitigate this limitation for us.

**Comment by DavidDeSloovere** [comment]
I think I understand the Nitro issues and the need to pass `event` into `useRuntimeConfig`. 
But what about SSR? 

`__NUXT__config.public` is empty (unless prerendered)

i.e. A Google Maps api key that is stored in public runtime config, and you want to access it in `<script setup>` in `.vue` file?

Is it the same reason?

**Comment by Amar-Gill** [comment]
@DavidDeSloovere for public run time config, I had to update my `nuxt.config.ts` to reference `process.env`, and I got it working.

Example:
```ts
public: {
  myEnvVar: process.env.NUXT_PUBLIC_MY_ENV_VAR
}
```

**Comment by manniL** [comment]
@Amar-Gill This is not specific to the cloudflare pages env but is generally recommended.

> Setting the default of runtimeConfig values to differently named environment variables (for example setting myVar to process.env.OTHER_VARIABLE) will only work during build-time and will break on runtime. It is advised to use environment variables that match the structure of your runtimeConfig object.

+ https://www.youtube.com/watch?v=_FYV5WfiWvs

**Comment by DavidDeSloovere** [comment]
The docs mention the addition of Alex about variable with other names and using `process.env`, but don't really mention that as best practice. Code samples don't even include that.
 
I thought having `NUXT_PUBLIC_MY_ENV_VAR` defined was enough, but indeed, for CF you **need** to explicitly use `process.env.NUXT_PUBLIC_MY_ENV_VAR` in `nuxt.config.ts`. Thanks @Amar-Gill

**Comment by DavidDeSloovere** [comment]
I'd love to. (And docs are 90% of my open source contributions)
However I don't know enough of how this actually works vs what I have observed. That said, I think I can open up an issue to have the docs improved.
