### ISSUE TITLE
Failed to resolve web component warning

### ISSUE THREAD

**Issue by dzbo** [nuxt/nuxt#25040]
### Environment

- Operating System: Darwin
- Node Version:     v18.17.0
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@4.0.1
- Builder:          -
- User Config:      devtools, app, modules, plausible, device, tailwindcss, vite, vue, imports, ssr, spaLoadingTemplate, piniaPersistedstate, runtimeConfig
- Runtime Modules:  @nuxtjs/tailwindcss@6.10.3, @pinia/nuxt@0.5.1, @pinia-plugin-persistedstate/nuxt@1.2.0, @nuxtjs/device@3.1.1, @nuxtjs/plausible@0.2.4, @nuxtjs/algolia@1.10.1, @pinia-orm/nuxt@1.7.0
- Build Modules:    -

### Reproduction

https://github.com/lukso-network/wallet.universalprofile.cloud

### Describe the bug

After upgrading from `nuxt@^3.6.5` to `nuxt@^3.9.0` I've started to see a lot of warnings regarding component resolving:

```
Failed to resolve component: lukso-sanitize
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
```

App uses web components that's why in my `nuxt.config.ts` I have this entry which worked before upgrade:

```
vue: {
    compilerOptions: {
      isCustomElement: (tag: string) => {
        return tag.startsWith('lukso-')
      },
    },
  },
```

**Comment by pgraug** [comment]
Does moving the extra vue config inside the 'vite' key fix it? That's what I'm using.

Like this:
```ts
export default defineNuxtConfig({
  vite: {
    vue: {
      template: {
        compilerOptions: {
          isCustomElement: (tag) => tag.startsWith('lukso-'),
        },
      },
    },
  },
})
```

**Comment by dzbo** [comment]
> Does moving the extra vue config inside the 'vite' key fix it? That's what I'm using.

Yeah I've tried that already, it still give warnings.
