### ISSUE TITLE
[Nuxt 3.9] - Hydration STYLE mismatch

### ISSUE THREAD

**Issue by mkierdev** [nuxt/nuxt#25045]
### Environment

Nuxt 3.9

### Reproduction

I tried to upgrade from 3.8.2 to 3.9 using ```nuxi upgrade```

### Describe the bug

I've run into issue that was not present in 3.8.2:

 Hydration **style** mismatch on < div class...>​…​</div>​ // etc, replaced upon pasting
  - rendered on server: style="font-size:16px;--spacing:12px;"
  - expected on client: style="font-size: 16px; --spacing: 12px"

What's even more weird is that these properties actually comes from simple props with default values:
(Component simplified for showcase)
```js
withDefaults(defineProps<Props>(), {
  width: 16,
  spacing: 12,
});
```
```html
<div :style="`font-size: ${width}px; --spacing: ${spacing}px`" />
```

In another component, if style is generated by computed(), it also returns hydration style mismatch.

**Comment by manniL** [comment]
Be aware that Vue 3.9 added more fine-grained hydration info. That issue could've been there for long but was simply undetected. For more insights you have to provide a reproduction ;)

**Comment by josuelrocha** [comment]
It really seems to be a bug in Nuxt 3.9, in the example below, when you have `:style` and also `v-show` to modify the **style**, the Hydration warning is displayed.

### Example to reproduce
Anywhere in a Nuxt 3.9 project, place this code
``` vue
<div v-show="false" :style="{ width: 'auto' }">test</div>
```

### Console warn
```
[Vue warn]: Hydration style mismatch on 
<div style="width:auto;display:none;"> 
  - rendered on server: style="width:auto;display:none;"
  - expected on client: style="width:auto;"
```

**Comment by mkierdev** [comment]
Moreover, if you are returning default 'server' styles and modify it on the client during first load (ex. When accessing client window and calculating some stuff based on it) you also have this warning. Does not seems good.

**Comment by josuelrocha** [comment]
Really, the problem seems to be coming from Vue and not Nuxt.

https://stackblitz.com/edit/github-dyqiua?file=src%2Fpages%2FHome.vue

![vue-warn](https://github.com/nuxt/nuxt/assets/43762190/4d327826-23b1-4d5e-97bd-63f7fb870de7)

**Comment by manniL** [comment]
Let's track in https://github.com/vuejs/core/issues/10000, https://github.com/vuejs/core/pull/10004 should fix this I think
