### ISSUE TITLE
[nuxt 3.9] build failed when importing components from npm package

### ISSUE THREAD

**Issue by karen1au** [nuxt/nuxt#25055]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v21.2.0
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.21
- Builder:          -
- User Config:      devtools, components
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

import an external component library on app.vue in the nuxt scaffold app and get error:
`[vite-node] [ERR_LOAD_URL] @someOrg/someLib/index.js` 

### Describe the bug

When using an external organization scoped package it fails to resolve the path at build time with error:
```
ERROR  Pre-transform error: Failed to resolve import "@someOrg/someLib/index.js" from "app.vue". Does the file exist?
```
I've tried removing the scope locally and the import works after, i.e. `import { AppButton } from "someOrg/someLib/index.js"";`

This happens after upgrading to version 3.9.0, and was not happening with version 3.8.2

**Comment by karen1au** [comment]
I'm using the import for @coreui/vue as an example, getting the same error on log 
```
 ERROR  Pre-transform error: Failed to resolve import "@coreui/coreui/dist/css/coreui.min.css" from "app.vue". Does the file exist?
```
https://stackblitz.com/edit/github-8rdrdj?file=app.vue

**Comment by manniL** [comment]
@karen1au Your repro works after `yarn add @coreui/coreui` (`@coreui/coreui` is not present before, only `@coreui/vue`)

**Comment by karen1au** [comment]
Sorry I figured this is a local yarn link issue. Closing this, thanks!
