### ISSUE TITLE
Properties of provided values in a plugin lose template reactivity

### ISSUE THREAD

**Issue by TheDutchCoder** [nuxt/nuxt#25050]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.7.0
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.1.0
- Builder:          -
- User Config:      devServer, app, components, css, devtools, modules, auth, nitro, runtimeConfig, srcDir, vite
- Runtime Modules:  @nuxtjs/partytown@1.4.0, @nuxtjs/i18n@8.0.0, nuxt-jsonld@2.0.8, @nuxtjs/device@3.1.1, @nuxtjs/robots@3.0.0, nuxt-lazy-hydrate@1.0.0, @vueuse/nuxt@10.7.1, @sidebase/nuxt-auth@0.6.3
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-d8kxbk?file=app.vue,plugins%2Ftest.js

### Describe the bug

When providing objects through a plugin with reactive properties, the properties lose their reactivity when used in template directives.

For example:
```html
<pre>{{ $foo.bar }}</pre> <!-- this is reactive -->
<pre v-if="$foo.bar">I should disappear</pre> <!-- this is NOT reactive -->
```

**Comment by warflash** [comment]
This seems to be expected vue behaviour to me: https://vuejs.org/guide/essentials/reactivity-fundamentals.html#caveat-when-unwrapping-in-templates

**Comment by TheDutchCoder** [comment]
Indeed, although "expected" is a bit of a stretch here because it's not obvious that the injected object isn't reactive (even when wrapped in a ref).

Could we add this to the docs in case people hit this wall coming from Nuxt 2 and trying to shim plugins/modules?

**Comment by GalacticHypernova** [comment]
> Could we add this to the docs in case people hit this wall coming from Nuxt 2 and trying to shim plugins/modules?

I think we could 😉

**Comment by danielroe** [comment]
Note that wrapping this in `reactive` will make it work:

```diff
  export default defineNuxtPlugin(() => {
    const foo = ref(true);
    const bar = computed(() => foo.value === true);
  
    setTimeout(() => {
      foo.value = false;
    }, 2500);
  
    return {
      provide: {
-       test: {
+       test: reactive({
          foo,
          bar,
-       },
+       }),
      },
    };
  });
```

```diff
  <template>
    <div>
-     <button v-if="$test.foo.value">Show on foo true</button>
+     <button v-if="$test.foo">Show on foo true</button>
-     <button v-if="!$test.foo.value">Show on foo false</button>
+     <button v-if="!$test.foo">Show on foo false</button>
      <pre>{{ $test }}</pre>
    </div>
  </template>
```

**Comment by TheDutchCoder** [comment]
@danielroe It doesn't though, that's the issue.

Could it be that during injection time the injected object is unwrapped?
That was my alternative approach as well but neither `reactive` nor `ref` wrapping works on the plugin level.

**Comment by danielroe** [comment]
I was sure it worked when I made that change in your reproduction. Are you sure?

**Comment by TheDutchCoder** [comment]
@danielroe my apologies, it actually does (forgot to remove `.value`). Now I'm intrigued why it doesn't work locally 🤔 
The part that doesn't work is exposing destructured props from another composable and injecting them.

I think it's clear this is not a Nuxt issue anyway, so apologies for opening it on thsis repo, it's just the Vue caveat with plain objects (which isn't clear in this context).
