### ISSUE TITLE
Typesafety for NuxtLink

### ISSUE THREAD

**Issue by Ayax0** [nuxt/nuxt#25062]
### Describe the feature

It would be great if we had typesafe routes for the NuxtLink component similar to useFetch with suggestions for available routes. The Tanstack router could serve as an example: https://tanstack.com/router/v1

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
This is indeed possible. Enable `experimental.typedPages` and you should be good to go!
