### ISSUE TITLE
NuxtLoadingIndicator still not working properly in nuxt 3.9.1 when using navigateTo()

### ISSUE THREAD

**Issue by jony1993** [nuxt/nuxt#25081]
### Environment

- Operating System: Darwin
- Node Version:     v20.10.0
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@4.0.2
- Builder:          -
- User Config:      ssr, runtimeConfig, app, modules, apiParty, devtools, eslint, storyblok, image, i18n, router, routeRules, components, vue, typescript
- Runtime Modules:  @nuxt/devtools@1.0.6, @nuxtjs/device@3.1.1, @nuxt/image@1.1.0, @nuxtjs/i18n@8.0.0, @nuxtjs/eslint-module@4.1.0, nuxt-api-party@0.22.3, nuxt-clarity-analytics@0.0.6, nuxt-jsonld@2.0.8, nuxt-swiper@2.0.0-0, @voctag/ui@1.0.50, @vueuse/nuxt@10.7.1, @pinia/nuxt@0.5.1, @storyblok/nuxt@6.0.0
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-wlowtc?file=app.vue

### Describe the bug

NuxtLoadingIndicator stuck/freeze

Happens for example when you navigate from one page with layout A to another page with layout B via `navigateTo()`

**Comment by jony1993** [comment]
Ah my bad.
Seems to be working when moving <NuxtLoadingIndicator /> out of <NuxtLayout /> in app.vue

**Comment by bsiguret** [comment]
@jony1993 Hello, I have the same problem, what's your solution? Moving it to each layout you got?

Thank you 😄

**Comment by jony1993** [comment]
@bsiguret 
I moved it out of the NuxtLayout

```
    <NuxtLoadingIndicator />

    <NuxtLayout class="layouts">
      <NuxtPage />
    </NuxtLayout>
    
    ```

**Comment by haula-dv** [comment]
<template>
	<NuxtLayout>
		<NuxtLoadingIndicator color="#5d87ff" :height="5" :throttle="0" />

		<NuxtPage />
	</NuxtLayout>
</template> 

It work for me now.
