### ISSUE TITLE
Nuxt3 global middleware called twice for 404 page

### ISSUE THREAD

**Issue by alex-zabyshny** [nuxt/nuxt#25084]
### Environment

- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.7.5
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://github.com/alex-zabyshny/nuxt3-404-page-issue

### Describe the bug

Clone project and perform the following steps:

1. `pnpm install`
2. `pnpm build`
3. `pnpm preview`

Then open the project in a browser and go to any non-existent page. For example: `http://localhost:3000/noexistingpage`
In the server console, you will see that the middleware is called twice for **the same** route:
<img width="447" alt="Screenshot 2024-01-06 at 18 16 12" src="https://github.com/nuxt/nuxt/assets/93944018/32cd9135-c0ec-4222-9830-c5f5264d4778">
If you try to follow the "/" route, everything will be fine, and the middleware only calls ones.

**Expeted result:**
Middleware is called only once if the page is not found.

**Comment by toto6038** [comment]
I would like to supplement for @alex-zabyshny that the situation can be observed on dev server as well.

<img width="607" alt="image" src="https://github.com/nuxt/nuxt/assets/50100922/32cc325e-a7eb-44a0-869d-2966242c8b68">

**Comment by saifobeidat** [comment]
we're facing this, and its a bit important as we're receiving many visits (fake) on 404 routes, which causes the plugins/middleware run twice if you visit a 404 route, this lead to have many duplicate API calls and makes the CPU consumption very high

**Comment by danielroe** [comment]
When an error page is rendered, it is done so as an entirely separate 'page load'. So you can check in your middleware if `import.meta.server && useError().value` is true, and avoid additional API calls if that is the case.
