### ISSUE TITLE
Calling `useFetch` two times in a composable requires access to the nuxt instance

### ISSUE THREAD

**Issue by PoloLacoste** [nuxt/nuxt#25099]
### Environment

- Operating System: Windows_NT
- Node Version:     v21.0.0
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.14.0
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-zkclkd?file=utils%2Ftest.ts

### Describe the bug

When creating a `composable` to fetch some data, I found that I couldn't call `useFetch` twice in the same function and then using `useStore` inside my component setup script.

```js
export const useStore = async () => {
  await useFetch('/api/a')
  await useFetch('/api/b')
}
```

```js
<script setup lang="ts">
await useStore()
</script>
```

I don't really know if this is a bug or if this is intended based on this [comment](https://github.com/nuxt/nuxt/issues/23434#issuecomment-1737484680).

### Logs

```shell-script
[nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at `https://nuxt.com/docs/guide/concepts/auto-imports#vue-and-nuxt-composables`.

at Module.useAsyncData (C:\Projects\bug-usefetch\node_modules\.pnpm\nuxt@3.9.1_vite@5.0.11\node_modules\nuxt\dist\app\composables\asyncData.js:26:38)
at Module.useFetch (C:\Projects\bug-usefetch\node_modules\.pnpm\nuxt@3.9.1_vite@5.0.11\node_modules\nuxt\dist\app\composables\fetch.js:60:43)
at Module.useStore (C:\Projects\bug-usefetch\utils\test.ts:5:31)
at async setup (C:\Projects\bug-usefetch\app.js:16:107)
```

When previewing the application:

```shell-script
[nitro] [unhandledRejection] Error: [nuxt] instance unavailable
    at useNuxtApp (file:///C:/Projects/bug-usefetch/.output/server/chunks/app/server.mjs:296:13)
    at useAsyncData (file:///C:/Projects/bug-usefetch/.output/server/chunks/app/server.mjs:913:32)
    at useFetch (file:///C:/Projects/bug-usefetch/.output/server/chunks/app/server.mjs:1059:21)
    at useStore (file:///C:/Projects/bug-usefetch/.output/server/chunks/app/server.mjs:1098:9)
    at Timeout._onTimeout (file:///C:/Projects/bug-usefetch/.output/server/chunks/app/server.mjs:1106:13)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
```

**Comment by danielroe** [comment]
This is a known (and, I think, documented) limitation of the composition API.

You can use `runWithContext` to handle this (see [docs](https://nuxt.com/docs/api/composables/use-nuxt-app#runwithcontext)):

```ts
export const useStore = async () => {
  const nuxtApp = useNuxtApp()
  await nuxtApp.runWithContext(() => useFetch('/api/a'))
  await nuxtApp.runWithContext(() => useFetch('/api/b'))
}
```

**Comment by zifnab87** [comment]
@danielroe Thanks for the workaround

I have something similar but I am writing my components in a non-composable way
https://stackoverflow.com/questions/78101911/multiple-uses-of-usefetch-is-causing-nuxt-a-composable-that-requires-access-to

I tried to use your approach and I don't get the OP's error but now the second request appears in the client which negates the use of useFetch in the first place..

**Comment by zifnab87** [comment]
@danielroe I was able to replicate some weird (for me at least) behavior:


1.  in the current form it just does the meat request in the client and it doesn't load cheese at all
2. if (either async is removed from serverPrefetch, or await is added in front of its `this.fetchData();`) it works as expected, all requests in the server and both meet and cheese are loaded

I am thinking that async over serverPrefetch shouldn't change the behavior... also not sure why await is fixing the issue.. 

Hope my observations help a bit. Thanks in advance


```
<template>
  <div>
    meat: {{ meat }}
  </div>
  <div>----</div>
  <div>
    cheese: {{ cheese }}
  </div>
</template>

<script>
export default {
  data() {
    return {
      meat: [],
      cheese: []
    }
  },
  mounted() {
    this.fetchData();
  },
  async serverPrefetch() {
    this.fetchData();
  },
  methods: {
    async fetchData() {
      const nuxtApp = useNuxtApp()
      const res = await nuxtApp.runWithContext(() => useFetch('https://baconipsum.com/api/?type=cheese'))
      const res2 = await nuxtApp.runWithContext(() => useFetch('https://baconipsum.com/api/?type=meat'))
      this.cheese = res.data.value
      this.meat = res2.data.value
    },
  },
};
</script>
```


https://codesandbox.io/p/devbox/nuxt-fetch-hook-and-asyncdata-demo-forked-6zstxk?workspaceId=6b5cff00-ab9a-4c21-b219-049bf39984fa

**Comment by zifnab87** [comment]
@danielroe so is the above behavior to be expected? thanks!

**Comment by danielroe** [comment]
You definitely need to wait the promise in serverPrefetch.
