### ISSUE TITLE
Running development with https flag returns http urls from helper methods

### ISSUE THREAD

**Issue by zacwebb** [nuxt/nuxt#25108]
### Environment

- Operating System: Darwin
- Node Version:     v20.10.0
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.21
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

Can't use stackblitz/sandbox as these handle https automatically, instead...

- Pull and start with `yarn dev` (or `nuxt dev --https`): https://github.com/zacwebb/nuxt-https-repro
- Hit the endpoint https://localhost:3000/api/https-test
- Observe that `helper: "http"`, whereas it should be `https`
- vs when building for production it's correctly `https`: https://nuxt-https-repro.onrender.com/api/https-test

### Describe the bug

When starting nuxt with the `--https` flag in development, the h3 `getRequestProtocol` method should return `https` rather than `http`.

This can lead to some issues for packages that use `getRequestURL` (which calls `getRequestProtocol`) returning http urls when they should be returning https (see my original issue for context: https://github.com/Hebilicious/authjs-nuxt/issues/151)

Couldn't quite track down whether this was an issue with h3, nitro, or nuxt specifically but since `getRequestProtocol` simply checks the value of `(event.node.req.connection as any).encrypted`, I'm assuming it's an issue with Nuxt's implementation of https with nitro when in dev mode.

This isn't an issue in the production build (even locally)

**Comment by pi0** [comment]
Can you please verify with `nuxt dev --no-fork`? If it works, it is probably same issue as https://github.com/nuxt/cli/issues/324

**Comment by zacwebb** [comment]
> Can you please verify with `nuxt dev --no-fork`? If it works, it is probably same issue as [nuxt/cli#324](https://github.com/nuxt/cli/issues/324)

No luck unfortunately, `nuxt dev --no-fork --https` results in `http` from `getRequestProtocol` still

**Comment by pi0** [comment]
Have you switched to nuxt nightly channel as well?

**Comment by pi0** [comment]
Awesome thanks for confirming. Let's track it from https://github.com/nuxt/cli/issues/324 then!
