### ISSUE TITLE
When accessing the route object within a layout, it provides the previous route instead of the current route.

### ISSUE THREAD

**Issue by jonathan-rvezy** [nuxt/nuxt#25107]
### Environment

- Operating System: Linux
- Node Version:     v20.6.1
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.8.1
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

See this repo for the reproduction: https://github.com/jonathan-rvezy/nuxt-route-bug

### Describe the bug

When accessing the route within a layout it will return the previous page route rather than the current page route.

**Comment by divagueame** [comment]
I could reproduce this issue on my machine as well. It seems to be related to definePageMeta macro. When having a page setup  like this:

```
<script setup lang="ts">
definePageMeta({
  layout: 'b'
})
...
```

The route returned on the layout is, unexpectedly, the previous page.
This issue disappears, by instead of using definePageMeta,  just declaring the layout on <NuxtLayout> like this:

`  <NuxtLayout name="b">`

**Comment by manniL** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/25069

**Comment by jonathan-rvezy** [comment]
> I could reproduce this issue on my machine as well. It seems to be related to definePageMeta macro. When having a page setup like this:
> 
> ```
> <script setup lang="ts">
> definePageMeta({
>   layout: 'b'
> })
> ...
> ```
> 
> The route returned on the layout is, unexpectedly, the previous page. This issue disappears, by instead of using definePageMeta, just declaring the layout on like this:
> 
> ` <NuxtLayout name="b">`

This changes the behaviour of the page. If you do definePageMeta, then anything you did in the layout like an injection will be available to provide... however if you switch to <NuxtLayout>, those injections will not be available and provide will return null.
