### ISSUE TITLE
Devtools dosnt work even on clean Nuxt install

### ISSUE THREAD

**Issue by angh0r** [nuxt/nuxt#25104]
### Environment

[17:46:36] Working directory: D:/Web/nuxt3-clean
[17:46:36] Nuxt project info: 

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.8.0
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

just clean nuxi instalation.

### Describe the bug

Devtools have problems with Nuxt 3.9/3.9.1. They never work in my dev env.
![image](https://github.com/nuxt/nuxt/assets/17060750/71f5b9e3-8122-40ba-8f39-44bf5392d770)

I got this issue on every project that is using Nuxt 3.9. Even a fresh clean install ends with the same issue.
After a few minutes I got websocket error in devtools and console.

**Comment by angh0r** [comment]
I've tried my son's laptop and everything there is OK, so it's an internal issue of my Windows. Closing.

**Comment by arashsheyda** [comment]
@angh0r this is most probably because you are using an old cached version of DevTools, please check https://github.com/nuxt/devtools/issues/517 to resolve it, have a good day
