### ISSUE TITLE
nuxt3.9.1在ios的qq浏览器上报错，其他浏览器正常

### ISSUE THREAD

**Issue by chenhan19** [nuxt/nuxt#25110]
### Environment

![image](https://github.com/nuxt/nuxt/assets/57612000/e4f2df60-776d-4a1c-b36b-0ab0efce7c98)

### Reproduction

https://servicehall.chaoxing.com/home

### Describe the bug

nuxt3.9.1在ios的qq浏览器上报错，其他浏览器正常

**Comment by chenhan19** [comment]
![Uploading IMG_0153.PNG…]()

**Comment by miosenpai** [comment]
Possibly a duplicate of https://github.com/nuxt/nuxt/issues/24229, you might want to try some of the workarounds in that issue.

**Comment by manniL** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/24229

**Comment by xiaoruo-lin** [comment]
I also hope the author can solve this problem of QQ browser
