### ISSUE TITLE
Seeing old route information when using useRoute() with async components

### ISSUE THREAD

**Issue by martinszeltins** [nuxt/nuxt#25114]
### Environment

Stackblitz

### Reproduction

https://stackblitz.com/edit/github-xfixy7?file=pages%2Fabout%2F%5Bid%5D.vue

### Describe the bug

I have observed a very strange behavior regarding Suspense and async components. If I have an async call before I access the route using `useRoute()` composable then I will get old route (the route info of previous page). But if I move the `const route = useRoute()` before the async call then I will get the info about the current route correctly. I'll put the two code examples below.

This is very strange, I can't understand what is going on here. If this is expected behavior then please explain how it works because I could not find anything on the documentation about this.

Please check the reproduction link on Stackblitz - https://stackblitz.com/edit/github-xfixy7?file=pages%2Fabout%2F%5Bid%5D.vue

So for example, if I do this then I will not get the current route info (instead I am getting old route info): 😲

```vue
<template>
  <div>About</div>

  <NuxtLink to="/">Index</NuxtLink>

  {{ route.params }}
</template>

<script setup>
  const sleep = (ms) => {
    return new Promise(resolve => setTimeout(resolve, ms))
  }

  const myFunc = async () => {
    await sleep(100)

    const route = useRoute()

    // Old route info !!! 👇️ 😟
    // Path: /
    // Params: {}
    console.log(route)
  }

  await myFunc()
</script>
```

But if I move the `useRoute()` call two lines up then it will work as expected and I will get the info about the new route: 👍🏻 

```vue
<template>
  <div>About</div>

  <NuxtLink to="/">Index</NuxtLink>

  {{ route.params }}
</template>

<script setup>
  const sleep = (ms) => {
    return new Promise(resolve => setTimeout(resolve, ms))
  }

  const myFunc = async () => {
    const route = useRoute()

    await sleep(100)

    // Now it works as expected 👍️
    // Path: /about/1
    // Params: { id: 1 }
    console.log(route)
  }

  await myFunc()
</script>

```

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/24942.
