### ISSUE TITLE
allow `useLoadingIndicator` to not start when path does not change

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt/nuxt#25117]
### Describe the feature

Hello,

Actually, when using `navigateTo` to update the query from the current path (useful for a search for example), the loading indicator will load every time the `navigateTo` run.

Maybe I'm doing something wrong.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by Barbapapazes** [comment]
this generate a strange behavior because the hook `page:loading:end` is never call. (the nuxt loading indicator never end)

**Comment by huang-julien** [comment]
What version of nuxt are you using ? 3.9.1 fixed this by stopping the loading indicator if the setup of the page isn't run -> anchor and query change

**Comment by Barbapapazes** [comment]
Hooo, I was thinking it was in 3.9.0. Will update dans try.

https://github.com/unjs/website/pull/209

**Comment by Barbapapazes** [comment]
Nice, it works fine with 3.9.1! thanks
