### ISSUE TITLE
errorHandler description is not available in production

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [nuxt/nuxt#25118]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.18.0
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.8.1
- Builder:          -
- User Config:      runtimeConfig, modules, image, sitemap, site, colorMode, css, routeRules
- Runtime Modules:  @nuxtjs/tailwindcss@6.10.1, @pinia/nuxt@0.5.1, @pinia-plugin-persistedstate/nuxt@1.2.0, @nuxtjs/color-mode@3.3.2, nuxt-simple-sitemap@3.4.1, @nuxt/image@1.1.0
- Build Modules:    -
------------------------------

### Reproduction

// 

### Describe the bug

When my app is in development, all details are used to create a GitHub issue automatically. However, I am trying to achieve the same thing in production. In the production environment, the URL and error code are displayed, but the error message is not.

In dev:
![image](https://github.com/nuxt/nuxt/assets/37482171/c3f40b43-7581-4b24-bc63-261bc749f48c)

In production (digitalocean)

![image](https://github.com/nuxt/nuxt/assets/37482171/f5792125-6a59-4cfc-9c41-dda50371d029)

### Additional context

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.config.errorHandler = (error, instance, info) => {
    // handle error, e.g. report to a service

    const response = $fetch(`/api/createIssue`, {
      method: "POST",
      body: JSON.stringify({
        url: instance.error.url,
        error: instance.error.stack,
        errorCode: instance.error.statusCode,
      }),
    });
  };
});

**Comment by danielroe** [comment]
The stack is deliberately not present in production to avoid leaking information.

https://github.com/nuxt/nuxt/blob/dc02809ec0dee5385c62580d63d2e4e7a6966981/packages/nuxt/src/core/runtime/nitro/error.ts#L19-L21

**Comment by rahulkumarsingh73690** [comment]
Thanks @danielroe for answer.

Is there any alternative way to achieve this feature?

**Comment by rahulkumarsingh73690** [comment]
@manniL I am running a huge project with many pages and components. Sometimes, after updating Nuxt, some packages break. To monitor which package is breaking, I am trying to create a GitHub issue automatically. This makes it easy to track and fix without checking all pages one by one after every single deployment.

**Comment by manniL** [comment]
@rahulkumarsingh73690 [Example of it](https://www.lichter.io/articles/nuxt3-sentry-recipe/#capturing-errors-with-sentry-in-nitro)

**Comment by rahulkumarsingh73690** [comment]
Thanks 😍

Solved 90% problem but now the issue is H3Error doesn't return URL

import { H3Error } from "h3";

export default defineNitroPlugin((nitroApp) => {
  nitroApp.hooks.hook("error", (error) => {
    // Do not handle 404s and 422s
    if (error instanceof H3Error) {
      if (error.statusCode === 404 || error.statusCode === 422) {
        return;
      }
    }

   ```
 if (error instanceof H3Error) {
      console.log("toy" + error);
      const response = $fetch(`/api/createIssue`, {
        method: "POST",
        body: JSON.stringify({
          url: `${error.url}`,
         // error.url not available
          error: `${error.cause.message}`,
          errorCode: `${error.statusCode}`,
        }),
      });
    }
  });
});

```

**Comment by manniL** [comment]
The 2nd arg should give the context, thus also the event
`.hook("error", async (error, { event }) => {`
