### ISSUE TITLE
When useFetch requests an API under server/API, there is no type annotation

### ISSUE THREAD

**Issue by GaoNeng-wWw** [nuxt/nuxt#25112]
### Environment

```
Working directory: /workspace                                                   7:45:07 AM
Nuxt project info:                                                              7:45:07 AM

------------------------------
- Operating System: Linux
- Node Version:     v20.9.0
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      telemetry
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Reproduction

https://codesandbox.io/p/devbox/peaceful-wind-cgtm75?file=%2Fnode_modules%2Fnitropack%2Fdist%2Fshared%2Fnitro.da3b833a.d.ts%3A57%2C6

### Describe the bug

When using the `useFetch` function, even if there is an interface under "server/api", `useFetch ` does not have type annotations.

**Comment by danielroe** [comment]
Seems to be working fine for me in your reproduction.

![CleanShot 2024-01-09 at 09 49 16@2x](https://github.com/nuxt/nuxt/assets/28706372/73e5d19f-b414-40bf-aa15-17538f11cb2b)

**Comment by GaoNeng-wWw** [comment]
> Seems to be working fine for me in your reproduction.
> 
> ![CleanShot 2024-01-09 at 09 49 16@2x](https://private-user-images.githubusercontent.com/28706372/295166326-73e5d19f-b414-40bf-aa15-17538f11cb2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MDA3MTQsIm5iZiI6MTcwNDgwMDQxNCwicGF0aCI6Ii8yODcwNjM3Mi8yOTUxNjYzMjYtNzNlNWQxOWYtYjQxNC00MGJmLWFhMTUtMTc1MzhmMTFjYjJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDExNDAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1MzUwODBiYzJmYjgyODcxN2JhZGM5ZTcyYjI4ZWE3YThiMzQ5MDZiOWY4Mzc4YTA4YWVjMzI5NmVmMzlkZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UxWwuJUuW3HEy103JjpG-PbZV3VgSKSB_x9Fz5l_m7c)

![image](https://github.com/nuxt/nuxt/assets/31283122/fd1267b0-09f9-4ee4-ade1-c24093fa8e7e)

In theory, there should be a prompt for`/app/hello` after entering `/`, but it's not in the screenshot. Is it my problem?

**Comment by sduduzog** [comment]
This is usually caused by either an error in your nuxt.config.ts file (Which is unlikely from this reproduction) or dependencies. 

The most dreadful way of debugging this is deleting everything (even node_modules, package-lock.json, .nuxt folder) and all dependencies in my package.json file... then from here, I'd bring back files one by one after installing nuxt as the only dependency. It's tedious but it usually fixes my issue.

**Comment by wJoenn** [comment]
I'm having the same problem
```
|-- server
|   |-- api
|   |   |-- test.ts
```
```ts
// test.ts
export default defineEventHandler(() => "Hello there")
```
```ts
// app.vue
const { data } = useFetch("/api/test")
```
![image](https://github.com/nuxt/nuxt/assets/75388869/2968adfb-093c-4743-ae38-37a7b6bf6df7)
![image](https://github.com/nuxt/nuxt/assets/75388869/20b1efb1-dfcd-4c0a-81c7-550c4c470950)

I couldn't create a reproduction with a code sandbox (neither template would work) so I made a very small repo instead (litterally 3 lines of code) https://github.com/wJoenn/nuxt-reproduction

**Comment by manniL** [comment]
Probably related to https://github.com/nuxt/nuxt/issues/23984

**Comment by wJoenn** [comment]
Any news on this ?
I just discovered that, on a project that does not have the issue and using `bun` as the package manager, if I  `rm -rf bun.lockb` file and `rm -rf node_modules` and install the dependencies with `pnpm i` this time then the issue appears. Then if I `rm -rf pnpm.lock` and `rm -rf node_modules` and reinstall the dependencies with `bun i` then the issue is fixed.

Not sure why the behavior would be different from one package manager to another, I could share a copy of each lock file if that can help

**Comment by manniL** [comment]
@wJoenn did you check the linked issue? Your issue fits in there while the author of this issue does not use pnpm or yarn 3 but yarn one.

**Comment by wJoenn** [comment]
I did but there isn't much in there.
I haven't tried the workaround but it doesn't really explain what the issue is not why it would work with bun and not with pnpm 🤔

**Comment by manniL** [comment]
@wJoenn Because PNPM saves dependencies differently (but "more space-efficient") than yarn or NPM (and I assume also differently than bun).

**Comment by woldtwerk** [comment]
I can confirm that the types are missing with pnpm and no .npmrc file. Bun works fine.

It **works** fine when I add a .npmrc file with:
```
public-hoist-pattern[]=*nitropack*
```

**Comment by manniL** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/23984 then 👍
