### ISSUE TITLE
Add `refreshCookie` util

### ISSUE THREAD

**Issue by enkot** [nuxt/nuxt#25125]
### Describe the feature

There are scenarios where a cookie is added/updated on the client, but since we can't observe the changes, we need to manually update the ref returned by `useCookie` to keep it reactive.

F.e. we have `/token` request that sets new cookie value in the browser and we should somehow react to cookie change.
1st solution:
```ts
const tokenCookie = useCookie('token')

const login = async (username: string, password: string) => {
  // Sets `token` cookie on response
  const token = await $fetch('/api/token', {
    method: 'post',
    body: {
      authorizationCode
    }
  })

  // Refresh the ref
  tokenCookie.value = useCookie('token').value
})

// Cookie dependent computeds
const loggedIn = computed(() => !!tokenCookie.value)
const consumerId = computed(() => tokenCookie.value || xUsidCookie.value)
```
2nd solution:
```ts
const tokenCookie = useCookie('token')
const loggedIn = ref(!!tokenCookie.value)

const login = async (username: string, password: string) => {
  // Sets `token` cookie on response
  const token = await $fetch('/api/token', { ... })

  loggedIn.value = true
})

// Cookie dependent computeds
const consumerId = computed(() => loggedIn.value ? useCookie('token').value : xUsidCookie.value)
```
Using composable inside the computed doesn't look good 👀 

Since `useCookie` already uses [BroadcastChannel](https://developer.mozilla.org/ru/docs/Web/API/BroadcastChannel) under the hood, I suggest adding another `refreshCookie` utility. We can call it to update the cookie's ref value when we know the new cookie value has been set:
```ts
const tokenCookie = useCookie('token')

const login = async (username: string, password: string) => {
  // Sets `token` cookie on response
  const token = await $fetch('/api/token', { ... })

  // Refresh all cookie refs
  refreshCookie('token')
})

// Cookie dependent computeds
const loggedIn = computed(() => !!tokenCookie.value)
const consumerId = computed(() => tokenCookie.value || xUsidCookie.value)
```

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
That seems reasonable to me. We could also add an experimental option to add a plugin to use `CookieChangeEvent` to listen for updates (if supported by the browser) and then call `refreshCookie` if so.

https://developer.mozilla.org/en-US/docs/Web/API/CookieChangeEvent
