### ISSUE TITLE
500 This page is temporarily unavailable.

### ISSUE THREAD

**Issue by moshetanzer** [nuxt/nuxt#25123]
### Environment

Production

### Reproduction

Not sure how to reproduce this, since have no way to debug it seemingly. Could be wrong though.

### Describe the bug

Hi,

I have come across an issue that i didnt come across before nuxt v3.9 and vue 3.4.

I am getting a screen that states "500. This page is temporarily unavailable" only a specfic page in my production site.

On dev i dont get any issue at all - and there seems no way to debug this issue since nothing is logged. 

Surely there should be a way to debug fatal errors in production?

**Comment by moshetanzer** [comment]
@danielroe how would i reproduce this?

**Comment by danielroe** [comment]
Try to reproduce locally using `nuxt build` and then `nuxt preview `. If that doesn't reproduce it might be something like a missing environment variable in your production setup, for example.

**Comment by moshetanzer** [comment]
Ok thanks so much. Busy building - should there be a way to debug it? Also, why would that be if you can navigate to the page and all works, but when accesing it directly not?

**Comment by danielroe** [comment]
Now try `node .output/server/index.mjs`. This won't load env variables.

The difference between the two situations is that one is rendering the page on the server. The other is doing it on the client.

**Comment by moshetanzer** [comment]
thanks. tested that, works also there.
Am happy to DM you website link - not sure if there is much to see besides that when accessing the page directly getting this 500 error, and when accessing though a NuxtLink it working.

**Comment by moshetanzer** [comment]
Would love to solve my problem - i am sure it is my error (definilty would appreciate help with that) however these are my main points;

My two questions are;

1. Shouldn't there be a way of showing advance debugging in production?
2. Whatever this issue is (am sure it is human mistake - just no way to debug easily beside rewriting page) surely it should occur both on accessing it directly and navigating to it within nuxt.

Thanks Daniel for your help ❤️

**Comment by moshetanzer** [comment]
@danielroe here is a bit more information

Might be a vite error?

[10:34:32 PM]  ERROR  Internal server error: Internal server error: Soft-invalidated module "/node_modules/nuxt/dist/app/entry.js" should not have existing transform result
      at handleModuleSoftInvalidation (file:///C:/Users/tanze/Desktop/raise-match-project/frontend/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:49828:15)
      at doTransform (file:///C:/Users/tanze/Desktop/raise-match-project/frontend/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:49635:16)     
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async viteTransformMiddleware (file:///C:/Users/tanze/Desktop/raise-match-project/frontend/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:59342:32)

**Comment by warflash** [comment]
@moshetanzer 
Perhaps this discussion helps with ideas: https://github.com/nuxt/nuxt/issues/24133, there's a few of them if you google for e.g. "nuxt This page is temporarily unavailable"
Regarding 1., your deployed app should print some sort of error log by default to the console of the process and there is plenty of hooks and error boundries to hook into and do custom logging/error handling -> https://nuxt.com/docs/getting-started/error-handling
Regarding 2., like Daniel mentioned, navigating to a page on client renders the page on the client, not the server. If you refresh the page or navigate to the erroring page directly using the url then the server will try to render the initial HTML. It's two distinct environments so it makes sense one might throw an error if configured or used in a wrong way

**Comment by moshetanzer** [comment]
@warflash 

Thanks for your answer, why then on nuxt build and preview locally do i not get this error?

**Comment by warflash** [comment]
Well your local environment I image is different to the server? You might have different node versions, the build step might differ, different environment variables etc. etc.

**Comment by moshetanzer** [comment]
@warflash 

Thanks for your help but:

have got node engine defined in packae.json 

ran it using node as @danielroe suggested shouldnt include any env var...

Do you have a suggestion how to debug, not understanding your suggestion.

Other issue quoted doesn't seem to have any solution either - what are you suggesting from there?

What i am suggesting is that this is not "Temporarily unavailable" it is an acutal issue that wont get resolved and therefore either should be a clear and dx freindly way to debug, else should display some less generic message. Additionaly, for dx there should be some way to match the navigating and accesign directly...

This is also a new issue, not sure why anything should have changed in latest vue and nuxt, but it wasnt present before

Thanks for your help 🙏 !

**Comment by warflash** [comment]
> Other issue quoted doesn't seem to have any solution either - what are you suggesting from there?

There is different people reporting different approaches that solved the problem for them, hence I linked it mentioning it might contain ideas.

> Additionaly, for dx there should be some way to match the navigating and accesign directly...

You can set the page that's throwing the error for you to `ssr: false`, then there won't be any server rendered html allowing you to access the page through the url.

> This is also a new issue, not sure why anything should have changed in latest vue and nuxt, but it wasnt present before

Vite 5 was introduced and with the error log you linked a few minutes ago (thanks for that 👍) it does look like it's vite related, this distinction also explaining why only one env of server/client is throwing the error https://github.com/vitejs/vite/blob/2836276dc0e132c4d64dc4c08fc730058406f2c0/packages/vite/src/node/server/transformRequest.ts#L398 

There is also a working reproduction over on the unocss repo https://github.com/unocss/unocss/issues/3472

**Comment by moshetanzer** [comment]
@warflash 

Thanks again for your time.

Yeah, aware of setting to ssr:false, only thing is seo quite important specifically on this page, but definilty is a temporary solution.

What steps do you think need to be taken for a permanant solution? Is this something Nuxt should correct or Vite?

Thanks again

**Comment by moshetanzer** [comment]
@warflash do you understand what the actual error is, have quite understood...

Thanks so much

**Comment by moshetanzer** [comment]
@danielroe what do you suggest? Do you think this a bug or incompetency?

**Comment by moshetanzer** [comment]
Seems to be a reproduction now. Any update on this?

**Comment by manniL** [comment]
@moshetanzer do you also use unocss?

**Comment by moshetanzer** [comment]
Nope. Just nuxt 3. Work perfectly when on dev and on production with ssr false... really been a pain.

**Comment by manniL** [comment]
@moshetanzer Then we need a reproduction from that 👍

**Comment by moshetanzer** [comment]
@manniL Sorry, dont know anyway to debug - so cant reproduce. If you have any suggestion would be keen to try.

**Comment by manniL** [comment]
@moshetanzer You don't need to debug. Simply provide a reproduction that shows that issue [as described here](https://github.com/nuxt/nuxt/issues/25123#issuecomment-1883614736)

**Comment by moshetanzer** [comment]
> @moshetanzer You don't need to debug. Simply provide a reproduction that shows that issue [as described here](https://github.com/nuxt/nuxt/issues/25123#issuecomment-1883614736). Without knowing how to "make that error show", how should we fix it? 😋

I have absoloutly no idea how to reproduce since i cant put my finger on what the issue is. Just get the generic 500 with page is temporarily unaviable. But do not get it when using csr or ssr on local with build. 

Do you have any suggestion of how to catch the error, it is only on one page of site..

Would be happy to dm you live links to see...

Thanks!

**Comment by zgurea1** [comment]
I have the same issue, after updating to last update, when trying to acces the build app its showing 500 This page is temporarily unavailable. If i downgrade to 3.8 works fine.

package.json :
"nuxt": "^3.9.1",
 "vue": "3.4.0-rc.1",
 "vue-router": "latest"


Error:
[nuxt] [request error] [unhandled] [500] Cannot find module 'D:\Desktop\cods\unificat\.output\server\node_modules\vue\server-renderer\index.mjs' imported from D:\Desktop\cods\unificat\.output\server\chunks\handlers\renderer.mjs
  at new NodeError (node:internal/errors:406:5)
  at finalizeResolution (node:internal/modules/esm/resolve:233:11)
  at moduleResolve (node:internal/modules/esm/resolve:845:10)
  at defaultResolve (node:internal/modules/esm/resolve:1043:11)
  at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12)
  at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25)
  at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:228:38)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
  at link (node:internal/modules/esm/module_job:84:36)


![image](https://github.com/nuxt/nuxt/assets/60965273/48dc2760-3b42-4b4d-8768-384c24cafbdc)

**Comment by danielroe** [comment]
@zgurea1 Almost certainly you have multiple versions of Vue installed. Check and dedupe your lock file and you should be good...

**Comment by zgurea1** [comment]
@danielroe I deleted the lock, node_modules and .nuxt, did a fresh install build, and i have the same error

**Comment by danielroe** [comment]
And in your lockfile?

**Comment by zgurea1** [comment]
@danielroe I deleted yarn.lock. I need to do something else inside it?

**Comment by danielroe** [comment]
Look inside it to see whether you have more than one Vue version.

**Comment by zgurea1** [comment]
hmm, i see, i have version 3.4.0-rc.1 and 3.4.11.
I will check home. Thx!


![image](https://github.com/nuxt/nuxt/assets/60965273/5a7255da-a1de-4edc-8f10-11b6d5e48cfe)

**Comment by ZackPlauche** [comment]
Just received this issue adding @nuxtjs/tailwindcss 🤔

**Comment by ZackPlauche** [comment]
Also gone after a few refreshes 🤔

**Comment by https-eduardo** [comment]
> Hi, @moshetanzer, I have the same issue, after updating to last update, when trying to acces the build app its showing 500 This page is temporarily unavailable. If i downgrade to 3.8 works fine.
> 
> package.json : "nuxt": "^3.9.1", "vue": "3.4.0-rc.1", "vue-router": "latest"
> 
> Error: [nuxt] [request error] [unhandled] [500] Cannot find module 'D:\Desktop\cods\unificat.output\server\node_modules\vue\server-renderer\index.mjs' imported from D:\Desktop\cods\unificat.output\server\chunks\handlers\renderer.mjs at new NodeError (node:internal/errors:406:5) at finalizeResolution (node:internal/modules/esm/resolve:233:11) at moduleResolve (node:internal/modules/esm/resolve:845:10) at defaultResolve (node:internal/modules/esm/resolve:1043:11) at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12) at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25) at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:228:38) at ModuleWrap. (node:internal/modules/esm/module_job:85:39) at link (node:internal/modules/esm/module_job:84:36)
> 
> ![image](https://private-user-images.githubusercontent.com/60965273/296304833-48dc2760-3b42-4b4d-8768-384c24cafbdc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxMDA1MzQsIm5iZiI6MTcwNTEwMDIzNCwicGF0aCI6Ii82MDk2NTI3My8yOTYzMDQ4MzMtNDhkYzI3NjAtM2I0Mi00YjRkLTg3NjgtMzg0YzI0Y2FmYmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDIyNTcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3MDgzMWQ2MjI1N2NjODgwZDZmYWNkNWY4MDA0YjRkZWIyZDRkMDUwNWQxZDRiNjU5YTRiNTJiMmIzY2E4OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FRt4MHAVcKy26pzByvyenb2JiaVSCZuqnZg3sJ6GTck)

I was facing the same issue, but downgrading didn't work. My solution was changing the package manager (from yarn to npm). After re-installing the dependencies and rebuild it started working.  🙏🤝

**Comment by MiniDigger** [comment]
maybe this helps somebody. I ran into this error too and daniels comment made me realize that I still have a preview version of vue 3.4, updated that and my problem went away (https://github.com/HangarMC/Hangar/commit/efe3e0bf79ecd2bc384c24e9f02d0c8643d375b0)

**Comment by moshetanzer** [comment]
Hi all,

Seem to be that when I did an upgrade oferch caused the issue. It is resolved. This isn't a bug in nuxt latest version. 
Though I think better error login would be in place. 

Also error message is inaccurate since it was not a temporary issue. 

Additionally, to have better DX would suggest that there would be a way to test on build for 500 errors. Or some way clone the refresh on hmr since I was only getting this error on production and on full page reload or direct access. 

Just my thoughts. 

Thanks to @danielroe and all maintainers for this powerful framework. 

Think this issue can be closed unless suggestions want to be added as nice to have...

**Comment by Pamavoc** [comment]
Hello everyone, 

What solved it for me was switching back to npm. Yarn was installing two vue versions (since 3.4.15, the one bundled with nuxt is messing up Transition between pages, I decided to install vue 3.4.8, which is more stable for now). It messed up with vue/server-renderer package. Npm is taking in consideration only the 3.4.8, not both.

**Comment by RezaErfani67** [comment]
![image](https://github.com/nuxt/nuxt/assets/24381986/ba51a613-d94a-42d1-8770-333e93990642)

not resolve for me...
check this link: https://doctorjs.ir/course/mongo_installation
if i click on <NuxtLink> every thing is ok but if i press f5 show me error.
this is not occure in dev mode but in producttion...
```
  "devDependencies": {
    "@nuxt/devtools": "latest",
    "@types/node": "^18.17.3",
    "nuxt": "^3.10.1"
  },
  "dependencies": {
    "@bosquig/vue3-treeselect": "^0.1.5",
    "@mayasabha/ckeditor4-vue3": "^1.0.5",
    "@nuxtjs/tailwindcss": "^6.8.0",
    "@videojs-player/vue": "^1.0.0",
    "array-to-tree": "^3.3.2",
    "comma-number": "^2.1.0",
    "highlight.js": "^11.8.0",
    "mitt": "^3.0.1",
    "ohash": "^1.1.3",
    "sass": "^1.66.1",
    "video.js": "^7.20.3",
    "vue-toastification": "2.0.0-rc.5",
    "vue3-editor": "^0.1.1",
    "vue3-persian-datetime-picker": "^1.2.2",
    "vuejs-paginate-next": "^1.0.2"
  }
}
```

**Comment by pathnirvana** [comment]
updating prod node version from 16 to 18 to match the development machine fixed the issue for me

**Comment by TARGINO0110** [comment]
Versions above 3.0.0 of Nuxt 3 require variable environment, issue 500 occurs due to not finding an environment variable on the production server. Below is the document explaining:
https://nuxt.com/docs/guide/recipes/sessions-and-authentication#cookie-encryption-key

![Image](https://github.com/user-attachments/assets/70b1cef4-cc0a-4e58-b6f6-574a822d1cac)
