### ISSUE TITLE
[DOCS] StackBlitz examples not loading

### ISSUE THREAD

**Issue by busybox11** [nuxt/nuxt#25137]
### Environment

N/A

### Reproduction

Go to any docs page with a StackBlitz code example in an iFrame.
I am using https://nuxt.com/docs/examples/advanced/config-extends as an example here.
Reproductible in every major browser on my Mac and Linux machine.

### Describe the bug

The code example iframes are not loading. Looks like a CORS error?
The iframe page works when accessed directly using the same browsers.

<img width="2560" alt="image" src="https://github.com/nuxt/nuxt/assets/29630035/fcd78af7-4b21-4260-afb3-a26c967caa31">

(When hovered the iframe shows "Refused to connect", there isn't any relevant logs in the console nor network tab)

### Additional context

MacOS Sonoma w/ Arc v1.21.3 on Chromium 120 on the screenshot, Firefox Developer Edition 122.0b7

ArchLinux w/ Chrome Dev 122, Chrome Canary 122

**Comment by manniL** [comment]
https://stackblitz.com/github/nuxt/examples/tree/main/examples/advanced/config-extends?embed=1&file=nuxt.config.ts&theme=dark is accessible directly though

**Comment by busybox11** [comment]
It looks like it comes from both StackBlitz and this website.

This is the iframe inspected request on their own popup, is is blocked.
<img width="493" alt="image" src="https://github.com/nuxt/nuxt/assets/29630035/268057d9-abe3-4e84-aaad-e528642de256">

Though as Sébastien pointed out, the new COEP config would have theoretically blocked the iframe anyway.
https://github.com/nuxt/nuxt.com/issues/1475#issuecomment-1885139036

**Comment by manniL** [comment]
Also resolved again. See https://github.com/nuxt/nuxt.com/issues/1475#issuecomment-1885139036
