### ISSUE TITLE
Generated tsconfig.json for modules is messing with VS Code's TypeScript support

### ISSUE THREAD

**Issue by antony-k1208** [nuxt/nuxt#25134]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v16.18.1
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.7.6
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-6h2ghs?file=.nuxt%2Ftsconfig.json

### Describe the bug

When using modules in your nuxt project the generated `tsconfig.json` in `.nuxt` seems to be conflicting with VS Code's TypeScript server.

In the `include` section everything in the module's `runtime` folder is allowed but then in the `exclude` section the whole module gets removed again.

```
"include": [
    "../modules/1.first/runtime",
    ".."
  ],
  "exclude": [
    "../modules/1.first",
    "../modules/1.first/runtime/server",
  ]
```

As you can see when opening a file from within the `runtime` folder, VS Code shows on the bottom right that no tsconfig file is associated with that file and the auto imports are not working as intended:

<img width="1289" alt="image" src="https://github.com/nuxt/nuxt/assets/4183726/cb6ef2ad-dd68-476c-93cc-196d8a245b22">

**Comment by manniL** [comment]
Can you try only add `runtime/composables` via `addImportsDir`?
