### ISSUE TITLE
$ref with Nuxt 3

### ISSUE THREAD

**Issue by carbdias** [nuxt/nuxt#25138]
### Describe the feature

Hello, is $ref supported by Nuxt 3 ?
I'm trying to use it but I have a vite message saying it is not recognized, 

[plugin:vite:import-analysis] Internal server error: _Failed to resolve import "vue/macros"_

even if I write the import explicitly : 

**import { $ref } from 'vue/macros'**

This is a feature I've found here : https://www.thisdot.co/blog/omit-dot-value-in-refs-vue-3

that avoids having to use .value with the ref variables.

Thank you very much,

Carlota

my vue and nuxt versions are :

"vue": "^3.3.8",
"vue-router": "^4.2.5"
"nuxt": "^3.8.2"

Thank you

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by warflash** [comment]
Did you install the vue macros package? See https://vue-macros.dev/guide/nuxt-integration.html and https://vue-macros.dev/features/reactivity-transform.html

**Comment by manniL** [comment]
Works fine, see [this StackBlitz](https://stackblitz.com/edit/nuxt-issues-25138). Be aware that reactivity transform is deprecated, hence I'd suggest not to rely on it or use it.
`.value` is also a nice indicator for reactivity.

**Comment by carbdias** [comment]
Thank you, message received.
