### ISSUE TITLE
[vite-node] [ERR_LOAD_URL] while using nuxt module

### ISSUE THREAD

**Issue by RomanSkrypnik** [nuxt/nuxt#25132]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.5.0
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  ./modules/test-module/dist/module
- Build Modules:    -
------------------------------

### Reproduction

**Github**: https://github.com/RomanSkrypnik/nuxt-module-issue

### Describe the bug

I'm developing custom nuxt module for my project and using **lodash-es** dependency in it
Initially, I used `nuxt 3.6.5` - it worked fine
Then I decided to upgrade nuxt version to the latest version - `3.9.0` and started to face this problem:

![image](https://github.com/nuxt/nuxt/assets/44501848/1a24b182-6faa-41c5-835a-c560984396c0)

As I have understood, this problem relates to `vite-node`: https://github.com/nuxt/nuxt/issues/24850#issuecomment-1865945495 - if I write `ssr: false` in `nuxt.config.ts` - everything works fine

@danielroe , could you please give me a hint, if it relates to `vite-node` also?

**Comment by manniL** [comment]
You have to add `lodash-es` to `build.transpile`

```ts
  build: {
    transpile: ['lodash-es']
  }
```

**Comment by donejeh** [comment]
The issue is that __dirname isn't available in Nuxt 3's ESM context. Fixing the path resolution:

IN YOUR:  app\nuxt.config.ts

The fix changes:
from: path.resolve(__dirname, "./presets/[YOUR PROJECT FOLDER NAME]/"),

To:
from: path.resolve(process.cwd(), "presets/[YOUR PROJECT FOLDER NAME").replace(/\\/g, "/"),


  primevue: {
    options: { unstyled: true },
    importPT: {
      as: "omeife",
      // Cross-platform path: normalize to forward slashes for Vite compatibility
      // Works on Windows, Mac, and Linux
      from: path.resolve(process.cwd(), "presets/[YOUR PROJECT FOLDER NAME]").replace(/\\/g, "/"),
    },
  },
