### ISSUE TITLE
The href attribute of a tag and the to attribute of Nuxtlink do not use client data but server data on the client side.

### ISSUE THREAD

**Issue by wkif** [nuxt/nuxt#25149]
### Environment

- Operating System: Linux
- Node Version:     v20.9.0
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

[codesandbox Demo](https://codesandbox.io/p/devbox/zealous-silence-ypx7yt?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr7o2vri0007356iq97ey39z%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr7o2vri0002356i1jwhuzgt%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr7o2vri0004356ih8uhvaa6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr7o2vri0006356irafyjwyz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr7o2vri0002356i1jwhuzgt%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr7o2vri0001356i90u5fh)

### Describe the bug

The link array is randomly generated by the generateRandomLinks method, and the execution result of the server is successfully applied to the dom, but the data executed again by the client is not applied, resulting in a link error.

**Comment by wkif** [comment]
![微信图片_20240111085715](https://github.com/nuxt/nuxt/assets/62132584/b065eb56-5341-4139-aef2-17c9ee43ca12)

**Comment by manniL** [comment]
Because `createData` is executed on client and on server side, the data is different.
Either only use it on the server side and save it in a `useState`, or only generate it on the client-side ☺️

**Comment by wkif** [comment]
> Because `createData` is executed on client and on server side, the data is different. Either only use it on the server side and save it in a `useState`, or only generate it on the client-side ☺️

The problem is that there is no problem using {{}} data, while the href property will not

**Comment by manniL** [comment]
@wkif in all cases, you should see a hydration warning in the console 🤔

**Comment by wkif** [comment]
> @wkif in all cases, you should see a hydration warning in the console 🤔
> 
> ![image](https://private-user-images.githubusercontent.com/640208/295846176-c74b65aa-6121-465b-91cc-74225e2da160.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NjI2OTgsIm5iZiI6MTcwNDk2MjM5OCwicGF0aCI6Ii82NDAyMDgvMjk1ODQ2MTc2LWM3NGI2NWFhLTYxMjEtNDY1Yi05MWNjLTc0MjI1ZTJkYTE2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQwODM5NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOGQ0NWU2YTg3NzFhNjc3YmQ3ZTVkNGY5ZjhlMWZiNDkxMTI0NDdmMGJhNTg3NGQ0NzE0YThhYzlhNDFhZjA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7oF6UrGjJ6FLsAe0f-9BngZa3HFwUNv0QnHBnJd0-VM)
> 
> ## Example of how it can work
> https://stackblitz.com/edit/nuxt-issues-25149?file=app.vue

well,i see.Thank you very much.
