### ISSUE TITLE
Anchor in navigateTo composable in setup script (Composition API, Nuxt 3)

### ISSUE THREAD

**Issue by carbdias** [nuxt/nuxt#25146]
### Describe the feature

Hello, is there any way to define an anchor in the navigateTo composable of Nuxt 3 ?
For example, the case where we need query parameters and an anchor in the end of the url and navigate programmatically to it, through the Composition API.
Thank you very much,

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by DamianGlowala** [comment]
Is this what you're looking for?
```
navigateTo({
    path: '...',
    query: {
        foo: '...'
    },
    hash: '...'
})
```

**Comment by carbdias** [comment]
Thank, it seems, but I've seen the documentation and in the possible options, I've seen no hash as being possible to add.
But if it is already implemented, great, I'll test it.
Thank you,

**Comment by DamianGlowala** [comment]
The [`to` parameter](https://nuxt.com/docs/api/utils/navigate-to#to) in the documentation has clickable [`RouteLocationRaw`](https://router.vuejs.org/api/interfaces/RouteLocation.html), which takes you to the relevant section of Vue Router documentation:
![image](https://github.com/nuxt/nuxt/assets/48835293/5a72eff1-d110-4cc1-b89a-94f0b379aa64)

**Comment by carbdias** [comment]
I understand, but if I put the hash inside the to parameter (where the url is), won't the hash appear before the query parameters?
I'm not sure if the url will get the right format.

**Comment by DamianGlowala** [comment]
If you are unsure, the quickest way is to find it out by trying. I first recommend you give it a go and see if `navigateTo` behaves the way you would expect. If not, please attach the snippet which doesn't work for you and the intended behavior.

**Comment by carbdias** [comment]
Thank you, it seems to work this syntaxis.
So it is just this intel is lacking in the documentation.

navigateTo({
    path: '...',
    query: {
        foo: '...'
    },
    hash: '...'
})

**Comment by DamianGlowala** [comment]
There is an example already with this syntax: https://nuxt.com/docs/api/utils/navigate-to#within-a-vue-component. For checking all available fields (including `hash`), please check the Vue Router docs accordingly, as stated in my previous comment. We cannot afford showing every possible combination in the examples, as we would flood the docs with tens of them and decrease readability. As developers, we sometimes need to dig a bit further/check/experiment to find out what we're looking for and that's fine! :)

**Comment by carbdias** [comment]
Ok, thank you
