### ISSUE TITLE
allow `dependsOn` plugin definition to be a callback

### ISSUE THREAD

**Issue by userquin** [nuxt/nuxt#25141]
### Describe the feature

There are modules that can register multiple runtime plugins based on configuration options or even on installed dependencies and/or Nuxt modules.

Right now, there is no way to configure `dependsOn`, it must be an static array.

An example can be found here: https://github.com/userquin/vuetify-nuxt-module. This module has a few runtime plugins that can be enabled via configuration: 
- `vuetify-date` when enabled and the corresponding `@date-io/*` dependency installed
- `vuetify-i18n` when `@nuxtjs/i18n` module configured

I want to use this new feature to allow main Vuetify Nuxt runtime plugins to be parallel, registering secondary plugins or external plugin via custom virtual module using `dependsOn` callback:
- https://github.com/userquin/vuetify-nuxt-module/blob/main/src/runtime/plugins/vuetify.ts
- https://github.com/userquin/vuetify-nuxt-module/blob/main/src/runtime/plugins/vuetify-sync.ts

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
I think we'd prefer for the moment to leave open the option for `dependsOn` to be fully statically analysable at build-time to reduce runtime cost even further ...

For the feature you'd like to implement, you can do this without a callback, by generating a different plugin template and (within `getContents`) generate a different `dependsOn` array depending on what modules are installed, etc. You can do this with `addPluginTemplate` (or `addTemplate`) which allows you to generate a virtual plugin file.

**Example:** https://github.com/nuxt/nuxt/blob/642d4dc9de091009a18074bb9d6b162d35565532/packages/nuxt/src/components/templates.ts#L36-L71

**Comment by userquin** [comment]
Refactored all my plugins and also added both main plugins using `addPluginTemplate`, it is working, feel free to close this issue and the linked PR: https://github.com/userquin/vuetify-nuxt-module/pull/185

**Comment by danielroe** [comment]
Having discussed it with the team, we think we'd prefer not to add this potential complexity, particularly in view of the possibility of static analysis of `dependsOn`.
