### ISSUE TITLE
Nuxt Layers not handling gitlab subgroups correctly

### ISSUE THREAD

**Issue by sl0wik** [nuxt/nuxt#25145]
### Environment

Docker image node:18

- Operating System: `Linux`
- Node Version:     `v18.19.0`
- Nuxt Version:     `^3.1.0`
- CLI Version:      `3.10.0`
- Nitro Version:    `-`
- Package Manager:  `yarn@1.22.19`
- Builder:          `-`

### Reproduction

Add any Gitlab repository based in subgroup to `extends` configuration, for example:
```
    extends: [
        'gitlab:group-name/foo/bar'
    ],
```
Running `yarn install` will result in `[error] Failed to download https://gitlab.com/group-name/foo/-/archive/main.tar.gz: 403 Forbidden`.  It seems to take only the first parameter and ignore `bar`.

### Describe the bug

Gitlab uses a different structure than Github, so this example https://nuxt.com/docs/guide/going-further/layers#git-repository seems to be incorrect.

Instead of `username/repoName` Gitlab uses `{groupName}/{repoName|subgroupName}/...` and it would cause 403 error on `https://gitlab.com/{groupName}/{subgroupName}/-/archive/main.tar.gz`.

I can't figure right way to extend GitLab repository.

**Comment by pi0** [comment]
Upstream tracker: https://github.com/unjs/giget/issues/107 

I didn't have chance to investigate it yet but PR is more than welcome to fix 🙏🏼

**Comment by danielroe** [comment]
Let's track in linked upstream issue. 🙏
