### ISSUE TITLE
Method not allowed

### ISSUE THREAD

**Issue by fearart** [nuxt/nuxt#25153]
### Environment

Working directory: C:/dev/hotel-viewer                                                                                                                                                                08:16:49
Nuxt project info:                                                                                                                                                                                    08:16:49

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.10.0
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.21
- Builder:          -
- User Config:      devtools, modules, runtimeConfig, colorMode, ssr, app, googleFonts, ui
- Runtime Modules:  @nuxt/ui@2.11.1, @pinia/nuxt@0.5.1, @nuxtjs/google-fonts@3.1.3
- Build Modules:    -
------------------------------

### Reproduction

i've created a folder in `/server/api` directory, with name `/logs`. Added `index.get.ts` file. 

### Describe the bug

When trying to fetch endpoint `/server/api/logs/index.get.ts` (( '/api/logs' in axios )) with axios/devtools/insomnia. I'm getting error which says method not allowed.

### Additional context

index.get.ts
```js
import mongoose from "mongoose";
import jwt from 'jsonwebtoken';
const config = useRuntimeConfig();

export default defineEventHandler(async (event) => {
    let token = getCookie(event,'token')
    if (!token) {
        unauthorizedReturn(event)
        return
    }
    try {
        jwt.verify(token,config.jwt_secret)
    }
    catch {
        unauthorizedReturn(event)
        return
    }
    const body = await readBody(event)
    if (body.login === undefined || body.auth === undefined) {
        setResponseStatus(event,400,"Bad Request")
    }
    const user = await mongoose.connection.db.collection('hotel-users').findOne({token: body.auth})
    if (user === null) {
        unauthorizedReturn(event)
        return
    }
    if (user.permissions.root === false) {
        unauthorizedReturn(event)
        return
    }
    return mongoose.connection.db.collection('hotel-logs').find({}).toArray()
})

const unauthorizedReturn = (event: any) => {
    setResponseStatus(event,401,"Unauthorized")
}
```
vue request
```js
axios.post('/api/users/modify',{"token": openedUser.value.token, "login": openedUser.value.login,"password": openedUser.value.password,
            "permissions": openedUser.value.permissions,"name":openedUser.value.name,"surname":openedUser.value.surname,"group":openedUser.value.group}).then((res) => {
        getUsers()
    })
```
Folder sctructure
![image](https://github.com/nuxt/nuxt/assets/68917859/00627fcd-848b-4c6b-a176-460d53056a60)

### Logs
```
{
    "url": "/api/logs",
    "statusCode": 405,
    "statusMessage": "HTTP method is not allowed.",
    "message": "HTTP method is not allowed.",
    "stack": "<pre><span class=\"stack internal\">at createError (/C:/dev/hotel-viewer/node_modules/h3/dist/index.mjs:78:15)</span>\n<span class=\"stack internal\">at assertMethod (/C:/dev/hotel-viewer/node_modules/h3/dist/index.mjs:294:11)</span>\n<span class=\"stack internal\">at readRawBody (/C:/dev/hotel-viewer/node_modules/h3/dist/index.mjs:372:3)</span>\n<span class=\"stack internal\">at readBody (/C:/dev/hotel-viewer/node_modules/h3/dist/index.mjs:437:22)</span>\n<span class=\"stack\">at <anonymous> (C:\\dev\\hotel-viewer\\server\\api\\logs\\index.get.ts:19:1)</span>\n<span class=\"stack internal\">at /C:/dev/hotel-viewer/node_modules/h3/dist/index.mjs:1608:14</span>\n<span class=\"stack internal\">at Object.handler (/C:/dev/hotel-viewer/node_modules/h3/dist/index.mjs:1851:28)</span>\n<span class=\"stack internal\">at Object.handler (/C:/dev/hotel-viewer/node_modules/h3/dist/index.mjs:1675:31)</span>\n<span class=\"stack internal\">at process.processTicksAndRejections (node:internal/process/task_queues:95:5)</span>\n<span class=\"stack internal\">at async Server.toNodeHandle (/C:/dev/hotel-viewer/node_modules/h3/dist/index.mjs:1885:7)</span></pre>"
}
```

**Comment by fearart** [comment]
Fixed it rewriting code to `POST` method

**Comment by manniL** [comment]
`.post.ts` suffix is the solution here 😋

**Comment by Max-Kucher** [comment]
Guys, this is definitely a bug

**Comment by Webdesignwill** [comment]
Yeah i'm getting the same.

Vue JS File
`const { data } = await $fetch("/api/folders/stories", {
  folder: "payloads",
  method: "GET",
});`

/server/api/folders/stories.get.ts

NOT ALLOWED

In my server file, it hits readBody and then returns NOT ALLOWED but if I comment this out and return a 200, it's fine.

const { folder } = await readBody(event);

**Comment by fearart** [comment]
well you can't pass body in get requests, use post

**Comment by Webdesignwill** [comment]
Yeah your right, that's a terrible idea. I cut and pasted the code from my get/all request and didn't use my brain after that haha Thanks!

**Comment by NicolasPL64** [comment]
Still, it should work in my case but it didn't. I had to change it to POST and move the query params to a JSON body, not a solution but rather a workaround.
