### ISSUE TITLE
[Feature Request] Allow to configure multiple custom directory paths for "pages" directory

### ISSUE THREAD

**Issue by martinszeltins** [nuxt/nuxt#25152]
### Describe the feature

At our company we are creating a large-scale Nuxt app by splitting it into modules. Thanks to Nuxt configuration, we were able to reconfigure custom paths for everything except for the `pages` directory, which allowed us to create a directory structure where everything is placed in its own module. This allows one team to work on one module and another team to work on another module easily. But currently with Nuxt it is not possible to define MULTIPLE custom directory paths for the `pages` directory. Which forces us to put the pages of each module in `/common/pages/users.vue` instead of in `/users/pages/users.vue`, `/auth/pages/login.vue`. It would be very useful to be able to also customize the `pages` directories to allow for multiple paths. Currently you can only specify a single custom directory for pages which does not allow us to split it into multiple modules.

This is our current directory structure:
````
frontend/
- common     (/assets, /config, /layouts, /pages, /plugins, /public, /server)
- shipments  (/components, /composables, /utils, /api)
- invoices   (/components, /composables, /utils, /api)
- auth       (/components, /composables, /utils, /api)
- users      (/components, /composables, /utils, /api)
- settings   (/components, /composables, /utils, /api)
- app.vue
- package.json
````

And here is our `nuxt.config.ts`:
```js
export default defineNuxtConfig({
    serverDir: './common/server',

    dir: {
        assets: './common/assets',
        layouts: './common/layouts',
        middleware: './common/middleware',
        modules: './common/modules',
        pages: './common/pages',
        plugins: './common/plugins',
        public: './common/public',
        static: './common/static',
    },

    components: [
        {
            path: '~/shipments/components',
        },

        {
            path: '~/invoices/components',
        },

        {
            path: '~/auth/components',
        },

        {
            path: '~/users/components',
        },

        {
            path: '~/settings/components',
        },
    ],

    imports: {
        dirs: [
            'shipments/**/*.ts',
            'invoices/**/*.ts',
            'auth/**/*.ts',
            'users/**/*.ts',
            'settings/**/*.ts',
        ],
    }
})
```

Solution:
Instead of being able to specify only one custom directory for `pages` as it is currently, allow to specify multiple directories for pages, just like it is possible to do so for `components`. This will allow to create truly modular apps using Nuxt.

```js
nuxt.config.ts

export default defineNuxtConfig({
  pages: [
      {
          path: '~/auth/pages',
      },

      {
          path: '~/users/pages',
      },
  ]
}
```

Additionaly it would require that each page could define it's own root path like:

```vue
<script setup lang="ts">
    // if this page is inside /auth/pages/login.vue then the resulting path would be /auth/login.vue
    definePageMeta({ rootPath: '/auth' })
</script>
```

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
You can split up your nuxt app "like this" already by using nuxt layers/`extends` ☺️

**Comment by martinszeltins** [comment]
> You can split up your nuxt app "like this" already by using nuxt layers/`extends` ☺️

Thanks, that was exactly what I needed. Using Layers I was able to create the exact directory structure that I was looking for.

````
users
  └─ components
  └─ composables
  └─ nuxt.config.ts
settings
  └─ components
  └─ composables
  └─ nuxt.config.ts
sales
  └─ components
  └─ composables
  └─ nuxt.config.ts
app.vue
package.json
nuxt.config.ts
````
