### ISSUE TITLE
Lazy loading component error: TypeError: can't access property "classList", data.root.value is undefined 

### ISSUE THREAD

**Issue by paro-paro** [nuxt/nuxt#25164]
### Environment

stackblitz / latest versions

### Reproduction

Below

### Describe the bug

Hi, I am trying to lazy load a dialog component (v-dialog from vuetify) and I am getting the following error in the console, which prevents my application from running properly (even thou the component is actually lazy-loaded).

`Error: TypeError: can't access property "classList", data.root.value is undefined`
`Vue Warning: Unhandled error during execution of watcher callback`

I have tried both the Lazy prefix syntax and defineAsyncComponent function from vue.

[Reproduction](https://stackblitz.com/edit/nuxt-starter-rhhaqn?file=app.vue)

In vite-vue-vuetify [works](https://stackblitz.com/edit/vue-vuetify-xktfby?file=src%2FApp.vue) without any error/warning so I thought that might not be vuetify related.

Any help will be appreciated. Thanks!

**Comment by paro-paro** [comment]
Seems like the error was specific to the v-dialog (v-overlay) component (maybe because is teleported?)

In any case, setting `suspensible: false` option in the defineAsyncComponent does fix it.

**Comment by alihardan** [comment]
For anyone coming here in the future:

Wrapping your component (`v-overlay` in my case) by `<ClientOnly>` fixes the issue.
