### ISSUE TITLE
Camel Cased Content Components Do Not Render in Nuxt 3.9.1

### ISSUE THREAD

**Issue by dbzx10299** [nuxt/nuxt#25166]
### Environment

```
------------------------------
- Operating System: Darwin
- Node Version:     v20.4.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.7.2
- Builder:          -
- User Config:      devtools, css, modules, site, components, app
- Runtime Modules:  @nuxt/content@2.9.0, @vueuse/nuxt@10.7.0, nuxt-simple-sitemap@4.1.17, nuxt-jsonld@2.0.8
- Build Modules:    -
------------------------------
```

### Reproduction

https://stackblitz.com/edit/nuxt-starter-snapag?file=content%2Fblog%2Ftest.md

### Describe the bug

I am on nuxt `3.8.2` with no issues, since I ran `npx nuxi upgrade` my blog articles broke. I did some experimenting and I noticed that the content components are not working.

For example, this now breaks in `3.9.1` but works in the version I am running `3.8.2`.

NOTE: this only happens if there is camel casing in the components content name, e.g. `FooBar.vue` breaks, `Foobar.vue` works.

<pre>

::FooBar
some p text
::
</pre>
This will output in the html
```html
<foobar>
  <p>some p text</p>
</foobar>
```

In the `FooBar.vue` component
```html
<template>
  <div class="foobar">
    <slot />
  </div>
</template>
```

So the expected result is 
```html
<div class="foobar">
  <p>some p text</p>
</div>
```

But we get 
```html
<foobar>
  <p>some p text</p>
</foobar>
```

**Comment by manniL** [comment]
![image](https://github.com/nuxt/nuxt/assets/640208/b6e5605a-4442-4446-b2ef-aec7d613b313)
Works as expected, no?

**Comment by danielroe** [comment]
I believe this is an issue with `@nuxt/content` - let's track in https://github.com/nuxt/content/issues/2497.
