### ISSUE TITLE
useFetch dosn't work on initial page load in proxy mode

### ISSUE THREAD

**Issue by antonreshetov** [nuxt/nuxt#25170]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.9.0`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `pnpm@8.6.2`
- Builder:          `-`
- User Config:      `devtools`, `nitro`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

1. Clone repo - https://github.com/antonreshetov/nuxt3-proxy-reproduction
2. Install deps
3. Run `pnpm dev`
4. Open `http://localhost:3000`
5. In the terminal, you will see an warning - `[Vue Router warn]: No match found for location with path "/api/posts"`

### Describe the bug

When proxying a request, `useFetch` does not receive data on the initial page load. This can be seen by opening `http://localhost:3000`. If you go to the `/about` page and then back to `/`, `useFetch` works correctly and the data is received in the request.

If you remove the [proxy](https://github.com/antonreshetov/nuxt3-proxy-reproduction/blob/3199a2343ad441e848a9253d446117901472e702/composables/custom-fetch.ts#L9), the data is successfully received on the initial page load.

**Comment by manniL** [comment]
`devProxy` does not work for SSR calls. Use `runtimeConfig` for proxy instead. More info [in my video](https://www.youtube.com/watch?v=J4E5uYz5AY8)

**Comment by antonreshetov** [comment]
@manniL 

1. Why should I watch your video, thereby increasing your views? This seems like advertising. If there is a link to documentation, I would prefer that. According to this [section](https://nuxt.com/docs/api/composables/use-fetch), it specifically states that `useFetch` is SSR friendly.
2. `runtimeConfig` is not the same as proxying, as proxying is used to bypass CORS.
4. If you set `server: false` for `useFetch`, then proxying works, and if you put this request in middleware, then you can get what you want - data before entering the page.

I think this is more of a bug than a feature or architectural design.

**Comment by antonreshetov** [comment]
@Atinux think it's rude to close an issue like that.

**Comment by manniL** [comment]
> 1. Why should I watch your video, thereby increasing your views? This seems like advertising. 

Nobody forces you to 🤷 I linked that video because it helped people before and I am certain that it would help you understand the background. This is more than just two sentences of docs would cover ☺️ 

> If there is a link to documentation, I would prefer that. 

Sure! The [Nitro docs](https://nitro.unjs.io/config#routerules) explain how you can use the proxy route rule. Docs in Nuxt don't cover that yet.


> According to this [section](https://nuxt.com/docs/api/composables/use-fetch), it specifically states that `useFetch` is SSR friendly.

I said nowhere that `useFetch` is not SSR friendly. In fact, I stated that *devProxy* is not!

>     2. `runtimeConfig` is not the same as proxying, as proxying is used to bypass CORS.

My bad, I meant `routeRules` 👍 Edited the comment above 👍 
I also am aware what a proxy does (as shown in the video you decided not to watch) 


>     3. If you set `server: false` for `useFetch`, then proxying works, and if you put this request in middleware, then you can get what you want - data before entering the page.

But then you lose SSR benefits. Also this is, once again, explained in the linked video 🙈

**Comment by adamdehaven** [comment]
@manniL I think the issue here is that oftentimes you only need proxying when in local development (but including SSR).

I don't need the proxy once I'm in production 🤔

**Comment by manniL** [comment]
> I don't need the proxy once I'm in production 🤔

If your API runs on the same domain (or has CORS set up for your prod domain) then you don't need it indeed 👍🏻

**Comment by adamdehaven** [comment]
Right, but if you define in `routeRules` (assuming it's not in the `$development` block) wouldn't the proxy also exist in Production when deployed?

**Comment by manniL** [comment]
> Right, but if you define in `routeRules` (assuming it's not in the `$development` block) wouldn't the proxy also exist in Production when deployed?

When not using `$development` then yes, indeed!
