### ISSUE TITLE
[deps update]: Please update @vitejs/plugin-vue to 5.0.3 at package @nuxt/vite-builder@3.9.1 to fix HMR Maximum call stack size exceeded

### ISSUE THREAD

**Issue by WygorFonseca** [nuxt/nuxt#25178]
### Environment

Nuxt project info:                                                                                             9:28:21

------------------------------
- Operating System: Windows_NT
- Node Version:     v21.5.0
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.21
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

No reproduction required, taking into account that the error below is the same as the one mentioned here:
https://github.com/vitejs/vite-plugin-vue/issues/325

<img width="999" alt="image" src="https://github.com/nuxt/nuxt/assets/43591893/20bacaa6-90c7-4485-9ef7-b04706793003">

### Describe the bug

HMR throw Maximum call stack size exceeded
Plugin: vite:vue at deepEqual
Ref.: https://github.com/vitejs/vite-plugin-vue/issues/325

The fix from vite community was merged and released at (version 5.0.3)
https://github.com/vitejs/vite-plugin-vue/pull/334

So, please update "@vitejs/plugin-vue" "^5.0.2" depency from @nuxt/vite-builder@3.9.1 to 5.0.3

If you need more information please let me know. Thanks!

**Comment by volk234** [comment]
+1 
tired of restarting the server in nuxt 3.9

**Comment by manniL** [comment]
@volk234 Please refrain from posting comments that don't add additional context like "+1", "me too" or "bump". Instead, just upvote the issue through reactions *or* provide additional context like a reproduction, a new scenario where it happens or anything else that helps resolving the issue.

**Comment by manniL** [comment]
@WygorFonseca just update your deps (remove node_modules + lockfile) and then run `npm i` (or your package managers equivalent). We don't pin the versions so it should be updated automatically when doing this 👍
