### ISSUE TITLE
Issues using Alias NUXT 3 application on IIS server

### ISSUE THREAD

**Issue by hoangnx1986** [nuxt/nuxt#25187]
### Environment

IIS server v10
node js v20.10
iisnode core v0.2.26-x64
url rewrite

### Reproduction

t.com.vn
t.com.vn/app

### Describe the bug

I have deployed a nuxt 3 application on IIS server with domain name t.com.vn.
When I add an application using Alias "app", I receive the error "Access to t.com.vn was denied". 
Can someone help me configure web.config to be able to use Alias?
Thank you!

```[tasklist]
### Tasks
```

**Comment by hoangnx1986** [comment]
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <webSocket enabled="false" />
    <handlers>
      <add name="iisnode" path="index.js" verb="*" modules="iisnode"/>
    </handlers>
    <rewrite>
      <rules>
        <rule name="NodeInspector" patternSyntax="ECMAScript" stopProcessing="true">
          <match url="^server\/debug[\/]?" />
        </rule>

        <rule name="StaticContent">
          <action type="Rewrite" url="public{REQUEST_URI}"/>
        </rule>

        <rule name="DynamicContent">
          <conditions>
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="True"/>
          </conditions>
          <action type="Rewrite" url="index.js"/>
        </rule>	
      </rules>
    </rewrite>

    <security>
      <requestFiltering>
        <hiddenSegments>
          <remove segment="bin"/>
		  <add segment="node_modules" />
           <add segment="iisnode" />
        </hiddenSegments>
      </requestFiltering>
    </security>

    <httpErrors existingResponse="PassThrough" />
    <iisnode watchedFiles="web.config;*.js" node_env="production" debuggingEnabled="true" nodeProcessCommandLine="C:\Program Files\nodejs\node.exe" devErrorsEnabled="true"/>
		<staticContent> 
            <mimeMap fileExtension=".webp" mimeType="image/webp" /> 
        </staticContent> 
	
  </system.webServer>
</configuration>

**Comment by gcom-ryan** [comment]
I don't think we can provide a reproduction for this case. You will need your own IIS web server to look at, and debug this problem.

Our team has also tried to follow the official docs to deploy to IIS, and we get a similar error, the site will not display.

The best way to test this, is to get an IIS web server and try to deploy a simple Nuxt 3 app following these official docs...

https://nuxt.com/deploy/iis

**Comment by KidSysco** [comment]
I think I know what may be going on here, ran into the same issue, got it resolved...

Most of the time, generally speaking, IIS is configured to use URLReWrite at the top level of a website, not a virtual directory, not an alias.

This is super common, and the web.config that is generated with ```npx nuxi build --preset=iis_node``` would need to be modified in order to work correctly with an IIS Virtual Directory or Alias.

If you want that web.config to work un-modified, you need to give the app it's own top level website in IIS.
