### ISSUE TITLE
When a prop has two possible values and the server sets one, and the client sets the other it loses initial reactivity to other props

### ISSUE THREAD

**Issue by jonathan-rvezy** [nuxt/nuxt#25183]
### Environment

- Operating System: Linux
- Node Version:     v20.6.1
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.8.1
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

Add this to an existing project or create a new project...

```
<template>
  <div>
    <a href="https://nuxt.com/" :target="linkTarget" ref="link"> nuxt.com </a>
    <dl>
      <dt>expected</dt>
      <dd>{{ linkTarget }}</dd>
      <dt>actual</dt>
      <dd>{{ $refs.link?.target }}</dd>
    </dl>
  </div>
</template>

<script lang="ts" setup>
const linkTarget = computed(() => (process.server ? "server" : "client"));
</script>
```

### Describe the bug

When the server generates a value, in this case "server" ... and when the client hydrates and changes the value, in this case to "client", the hydration doesn't update the value passed to component props. However if the value is changed to anything other than the two values then it picks up the change immediately.

### Additional context

In my actual case I was using the [@vueuse/useMediaQuery](https://vueuse.org/core/useMediaQuery/) composable to set a prop based on screensize. On server it would always default to "mobile" because it doesn't have access to the screen size, however if you loaded it on a larger screen (like a desktop or laptop) it would get a different value. Resizing the screen would have no effect until it went into the "mobile" threshold, and then back out of it.

**Comment by manniL** [comment]
You are technically forcing a hydration error here, breaking (parts of) your app, because the client expects a different value than the server delivers.

![image](https://github.com/nuxt/nuxt/assets/640208/c347a8be-f783-4fa4-9941-7d792419d9d6)

Instead, consider changing the value via `onMounted(() => {})`
