### ISSUE TITLE
Vite Server Headers not Available in Production.

### ISSUE THREAD

**Issue by LordEwans** [nuxt/nuxt#25184]
### Environment

- Operating System: Linux
- Node Version:     v20.8.1
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  bun@1.0.21
- Builder:          -
- User Config:      devtools, security, modules, css, app, runtimeConfig, routeRules, vite
- Runtime Modules:  @nuxtjs/tailwindcss@6.10.1, @nuxt/devtools@1.0.4, nuxt-security@1.0.0
- Build Modules:    -

### Reproduction

Setup a Nuxt project and add the following to your nuxt.config.ts:

`vite: {
   server: {
        headers: {
          "Access-Control-Allow-Origin": "*",
          "Cross-Origin-Embedder-Policy": "require-corp",
          "Cross-Origin-Opener-Policy": "same-origin"
        },
      },
  },`

Setup some html files in your public folder that may requires SharedArrayBuffer (it doesn't matter though). As long as you can check their response headers.

### Describe the bug

While developing my local resources contained in the public folder provides `"Cross-Origin-Embedder-Policy": "require-corp",  "Cross-Origin-Opener-Policy": "same-origin"` header responses, but in production the vite config doesn't seem to be applicable as the headers are no longer present.

### Additional context

Thanks and if it's a mistake on my part let me know.

**Comment by manniL** [comment]
Because there is no vite server running in production ☺️ 
You can use route rules instead!

```ts
export default defineNuxtConfig({
  routeRules: {
    '/**': {
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Cross-Origin-Embedder-Policy': 'require-corp',
        'Cross-Origin-Opener-Policy': 'same-origin',
      },
    },
  },
});
```

**Comment by LordEwans** [comment]
Thanks, I tried running it on my local machine earlier it didn't work, I never considered it being a production feature. For now I'll use both the vite.option as well as the routerules for both local and production. Once again thank you.

**Comment by manniL** [comment]
routeRules should also work locally! 👌🏻
