### ISSUE TITLE
Nuxt3: nitro.publicAssets does not copy custom dirs to .output/public

### ISSUE THREAD

**Issue by pstatham-exp** [nuxt/nuxt#25185]
### Environment

Nuxt project info:                                                                                                                                                         11:47:55 PM

------------------------------
- Operating System: Linux
- Node Version:     v21.5.0
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      app, alias, css, devtools, nitro, modules, quasar, postcss, ssr
- Runtime Modules:  nuxt-quasar-ui@2.0.7
- Build Modules:    -
------------------------------

### Reproduction

The StackBlitz and CodeSandbox do not allow `.output/` directories, so cannot reproduce there

### Describe the bug

Following the description of #18918 I am unable to add additional directories to the `.output/public` folder:

```
nitro: {
    publicAssets: [
      {
        baseURL: 'samples',
        dir: './samples',
        maxAge: 60 * 60 * 24 * 7
      }
    ]
  },
```
This assumes I have a directory called `samples` at the same level of the `nuxt.config.ts`. 

When running `npm run build`, the `.output/public` does not contain this directory.

**Comment by danielroe** [comment]
Stackblitz does produce a `.output/` folder, it's just hidden. So you are welcome to provide a Stackblitz reproduction.

**Comment by marekbuxobucek** [comment]
@pstatham-exp As you can see it is semi-working.

It gives public access to serve content under dir path ignoring baseURL in nitro.publicAssets

reproduction 
https://stackblitz.com/edit/github-9ukebr-ui1ppg?file=pages%2Findex.vue&file=nuxt.config.ts

steps to reproduce:
- yarn build
- node .output/server/index.mjs

it works until I change the img src in index.vue to use publicAssets.baseURL instead of publicAssets.dir name

**Comment by danielroe** [comment]
We need to provide a resolver to let Vite know that the custom baseURL you provide matches that directory on disk. (We already do something very similar for layer public dirs.)
