### ISSUE TITLE
`<NuxtLayout /> component has not been used.` Warning when using `<ClientOnly>` in `app.vue`

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt#25196]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-issues-25196

```vue
<template>
  <ClientOnly>
    <NuxtLayout>
      <NuxtPage />
    </NuxtLayout>
  </ClientOnly>
</template>
```

### Describe the bug

When using a `<ClientOnly>` component around the `App.vue` (only SSR the app shell), the NuxtLayout warning will appear even though the component is used.

### Additional context

Related: https://github.com/nuxt/nuxt/issues/24912

**Comment by danielroe** [comment]
Yes, this is a limitation in how we are checking whether the layout is used.

**Comment by zeezzh** [comment]
I get the warning when using middleware call navigateTo().

**Comment by danielroe** [comment]
@zeezzh Would you provide a reproduction? 🙏

**Comment by zeezzh** [comment]
@danielroe See [https://stackblitz.com/edit/github-bnh9zl](url).It happens when navigateTo called on server side.

**Comment by danielroe** [comment]
We could bail on checking entirely if `<ClientOnly>` is used somewhere?
