### ISSUE TITLE
[Vue warn]: injection 'key' not found when developing a module

### ISSUE THREAD

**Issue by samk-dev** [nuxt/nuxt#25194]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.10.0`
- Nuxt Version:     `3.9.1`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `npm@10.2.3`
- Builder:          `-`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-yqhwiw?file=src%2Fruntime%2Fcomposables%2FuseSomeComposable.ts,src%2Fruntime%2Fcomponents%2FSomeComponent.vue,src%2Fmodule.ts,playground%2Fapp.vue

### Describe the bug

I am trying to use provide/inject inside a Module it returns `undefined` and in the console it logs `[Vue warn]: injection  'key' not found`.

runtime/components/SomeComponent.vue
```vue
<script lang="ts" setup>
import { provide } from 'vue';

provide('message', 'hello nuxt');
</script>

<template>
  <div>XSome Component</div>
</template>
```

runtime/composables/useSomeComposable.ts
```ts
import { inject } from 'vue';

const useSomeComposable = () => {
  const message = inject('message');

  function run() {
    console.log('inect message', message);

    return message;
  }

  // ....rest of composables

  return { run };
};

export default useSomeComposable;

```

playground/app.vue
```vue
<script lang="ts" setup>
import { XSomeComponent } from '#components';
import { useSomeComposable } from '#imports';

const { run } = useSomeComposable();

const message = run();
</script>

<template>
  <div>
    <XSomeComponent />
    <pre>
      {{ message }}
    </pre>
  </div>
</template>

```

### Logs

```shell-script
✔ Vite server hmr 6 files in 61.55ms
[Vue warn]: injection "message" not found.
inect message undefined
```

**Comment by manniL** [comment]
If you provide the message in a subcomponent, how should it be available in `app.vue` then? 🤔 

[Vue Playground with the same issue](https://play.vuejs.org/#eNqNU01vnDAQ/SsjX9hIKzjklrKR2iqH9tBWTQ89+EJhlrA1tuWPLRLiv3dsA9nNbpsggex5z+M3w5uRvdc6P3pkd6y0tem0A1HJdseZs5yBRef1PZddr5Vx8PNR9fhR0UaidLA3qocsL86iIVv2bj3iLa6wrX4JXE/Zs3DubDjFZa2kdTCC8RIm2F0m2Nyc8Hq0tmqReMSPSFmkOkg1bRz2WlQOaQdQNt0xLmj5opRiiWuTuOEZxzX/NM14sRDKImUri5M72Jb6Rsr2XZsfrJLU1jGQOavpqk6g+apdR8o5u4OIBKwSQv35HGPOeNwu8foJ699X4gc7hBhn3wxaNEfkbMVcZVp0CX54/IIDrVewV40XxP4P+B2tEj5oTLQPXjYk+4QX1X6Kf7eT7Q/7MDiUdikqCA3MKfI5IzeELv+r9Ge5t/ltPMflRF28MAd1cnbUCJ08YO3IHclKyXCG/je9yRaXrtvB5gZ293QzkQBeuiel3GRzJCMnzQkB9l7WQXmy2JIh5VAkTqh2k82alvPbZXWaCMDQPBm5YBEKJa+MGZ/dH/H0DS8Osf4G95UXV2qMROrdxTi+bbhH0EYdu4bMftZYGqMZeG7PFrInJB+A9IMLzXp17OK8wSrryvSw6S+RP5CZ)

Instead, I'd suggest using `useState` for easier state sharing (or e.g. a pinia store)

**Comment by samk-dev** [comment]
Thank you for quick response 🙏

That's a little bit odd. I checked Nuxt UI code and found similar use case where it's being used provide/inject in [components/forms/Form.vue](https://github.com/nuxt/ui/blob/dev/src/runtime/components/forms/Form.vue) and [/composables/useFormGroup.ts](https://github.com/nuxt/ui/blob/dev/src/runtime/composables/useFormGroup.ts). 

I have tried injecting what I want from a plugin with global app provide either Nuxt or Vue and it's working nice.

What I am trying to avoid here is prop drilling like in the screenshot from vue docs. I'll keep digging and see what I am doing wrong here
<img width="722" alt="Screenshot 2024-01-14 at 09 42 44" src="https://github.com/nuxt/nuxt/assets/33263129/8d97374c-1c2e-413b-aaa9-cfb69da1744b">

**Comment by samk-dev** [comment]
I think I just saw my mistake 😅 From the screenshot the data flow is cascading, that top level component is the one to provide the data and any child/grand child can consume it and not the other way around.

**Comment by adntin** [comment]
You can add inject default value. Other provide value preferable a ref value.
const message = inject('message', 'xxx');
