### ISSUE TITLE
Remove `params` alias for the `query` option in data fetching composables

### ISSUE THREAD

**Issue by DamianGlowala** [nuxt/nuxt#25208]
### Describe the feature

Currently, data fetching composables accept search params via two properties: `query` and `params`, where `params` is an alias for `query`. It would be great to settle on one of them for consistency. As this would be a breaking change, it's probably best to address it in the next version of Nuxt.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by Lehoczky** [comment]
I would go with `params`, because that's [how it's called in axios](https://axios-http.com/docs/req_config), and it is still a popular data fetching library. Also, query has a different meaning if someone is used to [VueQuery](https://tanstack.com/query/latest/docs/vue/guides/queries) or [GraphQL](https://graphql.org/learn/queries/#operation-name).

**Comment by manniL** [comment]
This would be needed in ofetch on the first place https://github.com/unjs/ofetch/blob/244fb6a720478a8e834f4e2715f8cef866802440/src/fetch.ts#L110-L115

**Comment by danielroe** [comment]
Personally, I think 'query parameters' is the full accurate version here, but there are other kinds of parameters, such as route parameters (as in Nitro). So 'query' would be most specific. But this is an upstream `ofetch` decision to make; we just inherit the types from `ofetch`.

Thoughts @pi0?

**Comment by pi0** [comment]
Let's run a poll https://twitter.com/_pi0_/status/1748316340627067181

**Comment by danielroe** [comment]
Closing to track upstream in `ofetch` 🙏
