### ISSUE TITLE
Css `:deep()` selector not working correctly with SSR

### ISSUE THREAD

**Issue by CernyMatej** [nuxt/nuxt#25229]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.9.0`
- Nuxt Version:     `3.9.1`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `pnpm@8.10.4`
- Builder:          `-`
- User Config:      `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Not working (Nuxt): https://stackblitz.com/edit/github-a6umaw?file=app.vue,components%2FFlashingSquare.vue
Working (Vue SSR): https://stackblitz.com/edit/github-hhybci?file=src%2Fpages%2FHome.vue,src%2Fcomponents%2FFlashingSquare.vue

### Describe the bug

When using the `:deep` CSS selector, the styles are not applied in the correct order during loading, causing them to be overwritten after the page loads. When I tried reproducing this issue in Vue SSR, it worked correctly.

### Additional context

Works fine with `ssr: false`

**Comment by CernyMatej** [comment]
@manniL I already did, as stated in the description. The reproduction for plain vue + ssr is under the link to the nuxt reproduction. 😊

**Comment by manniL** [comment]
@CernyMatej Thanks 👍

**Comment by danielroe** [comment]
Linked to https://github.com/nuxt/nuxt/issues/23785.

Basically the two selectors have equal specificity and the the order of CSS inlined differs from the order in the CSS file. You can work around by increasing the specificity of your CSS selector.

![CleanShot 2024-02-09 at 12 31 38@2x](https://github.com/nuxt/nuxt/assets/28706372/d7d008bb-a4c1-4838-a29d-bfb676cc4616)

**Comment by CernyMatej** [comment]
@danielroe I don't think this was fixed in https://github.com/nuxt/nuxt/pull/25749. Or am I overlooking something?
Btw. this reproduction doesn't have inlining of ssr styles enabled. However, it doesn't seem to be fixed even with it enabled either.

Updated reproduction with Nuxt 3.10.2:
https://stackblitz.com/edit/github-a6umaw?file=components%2FFlashingSquare.vue,package.json

**Comment by danielroe** [comment]
The issue we fixed was in production.

Vite still does have an issue in development, but that is not Nuxt - Nuxt renders `app.vue` styles first, and then `FlashingSquare`'s styles. But when Vite hydrates, it swaps out the stylesheets and seems to do it in the wrong order. We could open a new issue to track - but would be worth seeing if we could reproduce for vite with SSR.

We could start with https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter but it will need modifying to add rendering CSS links.

**Comment by CernyMatej** [comment]
Ah, I see. Well, I initially tried to reproduce it in Vue SSR as well, but I wasn't able to. https://stackblitz.com/edit/github-hhybci?file=src%2Fpages%2FHome.vue,src%2Fcomponents%2FFlashingSquare.vue

I'm not sure which changes you're suggesting we make.
