### ISSUE TITLE
Navigating between layouts with transition breaks page flow when page has async setup declared.

### ISSUE THREAD

**Issue by Jannick94** [nuxt/nuxt#25227]
### Environment

Info from the StackBlitz reproduction:

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, app
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-tj5ohy?file=pages%2Findex.vue

### Describe the bug

In the reproduction when you navigate to 'About' using the menu and then navigate back to 'Home', you will see the `<footer>` element switches place from where it originally was and not corresponding with the layout.vue file.

When the `async` keyword gets removed from the `setup` method in `index.vue`, everything works fine.

### Additional context

I noticed this in my project when I was trying to upgrade from nuxt 3.7.4 to 3.9.1. I also tried upgrading to 3.8.x, and the same issue occured. So it might be something that changed between 3.7.4 and 3.8.x.

Update: It only seems to happen when transitions are enabled within the config.

**Comment by danielroe** [comment]
It seems that `<NuxtLayout>` may need a root node which is not `<NuxtPage>` in this case.

Try this as a workaround for now:

```diff
  <template>
    <div>
      <nuxt-layout>
+       <div>
          <nuxt-page></nuxt-page>
+       </div>
      </nuxt-layout>
    </div>
  </template>
```

**Comment by danielroe** [comment]
let's track in
