### ISSUE TITLE
Event listeners are removed during bootstrap?

### ISSUE THREAD

**Issue by signor-pedro** [nuxt/nuxt#25223]
### Environment

Nuxt 3.8

### Reproduction

(any Nuxt3 app with GTM)

### Describe the bug

Hi. In our company, we rely on Google Analytics to **automatically attach an event listener** that listens to changes in History API.

The listener is 100% working when I trigger Google Analytics after the **whole page loaded** (every css/image/... is loaded and the DOM fully mounted).

However, this is not recommended - GA should be triggered right after the HTML arrived and the DOM starts to mount (the so-called "Page Loaded" trigger). It makes sense - why should I wait for an image to download in order to fire an XHR request to Google.

But when set to Page Loded, the listener works only 50% of the time, and it seems there is a race condition and a random chance that the listener mounts after hard refresh.

It kinda looks like if 3rd party sets up the listener too early, it is discarded when Nuxt mounts?

Anyone who is better acquainted with the code of Nuxt than I am - could it be that somehow, as part of the bootstrapping process, some cleanup script removes all attached event listeners when Nuxt fires up?

I am not even sure if that would constitute as a bug, but I guess many people rely on Google Analytics and we should have a way for 3rd party to safely mount event listeners.

Thank you for any advice.

**Comment by signor-pedro** [comment]
Yes, well if you had the lifecycle of the 3rd party script under control, you would :) 

I ended up implementing PageView tracking manually, just as you suggest.

However, the point of the new version of Google Analytics is that when you set up Enhanced Measurement, it tracks the changes to `history` automatically. When the 3rd party script loads, it mounts its own listener, see Google code for reference.

<img width="917" alt="Snímka obrazovky 2024-01-17 o 9 17 27" src="https://github.com/nuxt/nuxt/assets/53906348/30fc3764-4819-4ab2-9f04-1b2702533a2f">

After much experimenting, I found out I would need to delay the execution of the script by ~100ms in order for this listener to be mounted properly.

I just don't get it why. I get that `vue-router` might set up its own listenrs for pushstate/popstate, but that should not clash with other listeners? You can have multiple listeners attached to the same event after all, so...

That's why I was interested in what might be causing this.

**Comment by danielroe** [comment]
Ah, I was recommending not loading the third party script until after nuxt had loaded...

Tricky to debug this issue (in a third party script) without a reproduction.

Hopefully we'll soon release `nuxt/scripts` which will make this a lot easier.

**Comment by signor-pedro** [comment]
thanks!
