### ISSUE TITLE
Nuxt 3.9.2: Unstyled pages rendered briefly with Unocss

### ISSUE THREAD

**Issue by rylanharper** [nuxt/nuxt#25240]
### Environment

- Operating System: Darwin
- Node Version:     v18.18.2
- Nuxt Version:     3.9.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.12.0
- User Config:      devtools, modules, css, sanity, image, components
- Runtime Modules:  @vueuse/nuxt@10.7.2, @vueuse/motion/nuxt@2.0.0, @nuxtjs/sanity@1.8.3, @unocss/nuxt@0.58.3, @pinia/nuxt@0.5.1, @nuxt/image@1.2.0

### Reproduction

https://stackblitz.com/edit/github-mz42kv

Go to the follow reproduction, and manually refresh the web container. The page should briefly be unstyled. 

### Describe the bug

After upgrading to Nuxt `3.9.2` this morning, I notice that all my pages and components become briefly unstyled when my local environment is initially loaded or a page manually refreshed. This happens with Unocss, the styling library I am using, but it may also be happening with other styling libraries. 

### Additional context

I checked the Unocss issues, and no issues have been reported. This is likely not a Unocss bug (was working fine yesterday with Nuxt `3.9.1`)

**Comment by marcinkozaczyk** [comment]
I am using vuetify and started expiriencing this same issue since `3.9.2`. In `3.9.1` it was fine.

**Comment by huang-julien** [comment]
Also reproductible with tailwind

**Comment by danielroe** [comment]
**Note**: this only affects the first load in development, not in production.

**Comment by rylanharper** [comment]
> **Note**: this only affects the first load in development, not in production.

Correct! However, it is a somewhat annoying bug in development that wasn't there before. 

Manually refreshing the page, while not a core part of development, is a pretty standard part of my workflow to see different cached changes used when working with APIs (say from Sanity or Shopify).. Seeing everything unstyled each time is not ideal 😭

**Comment by danielroe** [comment]
Oh, it's definitely an unpleasant bug. Don't worry, we'll fix it.

**Comment by danielroe** [comment]
We'll be releasing a patch today 👍
