### ISSUE TITLE
Why does Nuxt3 use the <NuxtLoadingIndicator /> progress bar component not work?

### ISSUE THREAD

**Issue by LiuYuYang01** [nuxt/nuxt#25246]
### Environment

  "devDependencies": {
    "@nuxt/devtools": "latest",
    "nuxt": "^3.8.2",
    "vue": "^3.3.10",
    "vue-router": "^4.2.5"
  },

### Describe the bug

Why does Nuxt3 use the <NuxtLoadingIndicator /> progress bar component not work?

![image](https://github.com/nuxt/nuxt/assets/103110550/243d4bf7-007e-4a3f-bcfd-886c60a3fae1)

This progress bar has not been shown, I follow the official writing

**Comment by manniL** [comment]
Be aware that if your site loads "too fast" it will not be shown. This is to avoid a flickering or janky loading bar for sub-200ms calls.

**Comment by LiuYuYang01** [comment]
Hello, I set the network speed to slow, still can't see the progress bar


![PixPin_2024-01-18_09-12-07](https://github.com/nuxt/nuxt/assets/103110550/6ae5e888-eb55-41bf-b913-6600ab71df53)

**Comment by LiuYuYang01** [comment]
Hello, how can I solve this problem

**Comment by manniL** [comment]
@LiuYuYang01 Can you provide a [reproduction](https://github.com/nuxt/nuxt/issues/25246#issuecomment-1895296857) please?

**Comment by guofeifei123** [comment]
NuxtLoadingIndicator     opacity=0;    It has never changed



<NuxtLoadingIndicator  style="opacity: 1;" />


@LiuYuYang01  @manniL

**Comment by viniciuspinatti** [comment]
> NuxtLoadingIndicator opacity=0; It has never changed <---> `<NuxtLoadingIndicator` style="opacity: 1;" />`
> 
> @LiuYuYang01 @manniL

@guofeifei123 is right. If you go to Nuxt docs https://nuxt.com/docs/examples/routing/pages there is an example using the loading indicator to routes, but it doesn't show any loading. Just adding a `style="opacity: 1;"` in the app.vue file in the editor and saving and refreshing the editor it started to work.

**Comment by madebyfabian** [comment]
Can be closed due to no reproduction provided. 

@LiuYuYang01 Note that the loading indicator will only show if there is a top level await in your script setup, for example a `useFetch` or `useAsyncData`. It will not appear if the route finishes loading and some component inside the route is fetching data (that's what your case looks like from the video).

**Comment by dosstx** [comment]
Same problem. I had to add the `tyle="opacity: 1;" to NuxtLoadingIndicator` to get it to show.
