### ISSUE TITLE
DX: warn or throw error when using `setInterval` during SSR

### ISSUE THREAD

**Issue by Atinux** [nuxt/nuxt#25256]
### Describe the feature

It is easy to make a mistake and use `setInterval` in a Vue component without wrapping it into `onMounted()`.

This will let of memory leaks and `nuxt generate` being stuck.

I suggest to mock `setInterval` for the application part to throw an error and suggest using it inside `onBeforeMount` or `onMounted` Vue hooks.

Example of reproduction:

```vue
<script setup>
const index = ref(1);

setInterval(() => {
  if (index.value === 8) index.value = 1
  else index.value = index.value + 1;
}, 1000)
</script>
```

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by pi0** [comment]
I think previously we were thinking to include it as a rule also in eslint plugin to warn or disallow /cc @antfu

The tricky part is we need to make sure make this warning only when code is used in a server path. 

One idea to try btw: We might provide an auto import for `setInterval` in server bundle only.

**Comment by Atinux** [comment]
> One idea to try btw: We might provide an auto import for setInterval in server bundle only.

I like this idea if it can work out of the box!

Otherwise I was thinking of a server plugin for the app that overwrite the global `setInterval`

**Comment by pi0** [comment]
> server plugin for the app that overwrite the global setInterval

Since server global context is shared with Nitro, it can potentially break code like a Nitro plugin that does background cronjobs or even in a websocket or database connection checker. `setInterval` is dangerous only in a SSR rendering lifecycle.

**Comment by Kasopej** [comment]
> > server plugin for the app that overwrite the global setInterval
> 
> Since server global context is shared with Nitro, it can potentially break code like a Nitro plugin that does background cronjobs or even in a websocket or database connection checker. `setInterval` is dangerous only in a SSR rendering lifecycle.

was thinking along similar lines.. why wasn't this considered? I get trying to put guardrails but guardrails actually make the framework more rigid imo.. it should throw a warning not break the server (as there are valid reasons to use interval on server side)
