### ISSUE TITLE
icon and iconfy build modüle error

### ISSUE THREAD

**Issue by tolgahanbeyazoglu** [nuxt/nuxt#25283]
### Environment

    "nuxt": "^3.9.3",
    "nuxt-icon": "^0.6.8",
    "vue": "^3.4.14",
    "vue-router": "^4.2.5"

### Reproduction
[[](url)](https://stackblitz.com/edit/github-xafzmu?file=package.json)

github 
https://github.com/tolgahanbeyazoglu/nuxt-iconfy-example.git

### Describe the bug

I updated to version 3.9.3 and when I load nuxt-icon or iconfy in the build process I get a node module error, this does not prevent exporting the files but I don't understand.I think it is a bug with the new update

![111](https://github.com/nuxt/nuxt/assets/129540736/887cdbca-3118-4dde-aebb-387ceb3271ca)

**Comment by tolgahanbeyazoglu** [comment]
@manniL

**Comment by manniL** [comment]
@tolgahanbeyazoglu A reproduction is necessary as written in https://github.com/nuxt/nuxt/issues/25283#issuecomment-1898160979

**Comment by tolgahanbeyazoglu** [comment]
@manniL I am doing the build process in the replication environment, I do not get an error, but in the local environment I get the error I specified, nuxt-ui, iconfy, in short, iconfy is having problems with the modules it is connected to.

**Comment by manniL** [comment]
@tolgahanbeyazoglu it is fine to provide a GitHub repository then with a lock-file 👍

**Comment by tolgahanbeyazoglu** [comment]
@manniL okey I shared it with you, sorry it's late  https://github.com/tolgahanbeyazoglu/nuxt-iconfy-example.git

**Comment by manniL** [comment]
@tolgahanbeyazoglu can you also add your system info (`npx nuxi info`)?

**Comment by tolgahanbeyazoglu** [comment]
@manniL 
![12](https://github.com/nuxt/nuxt/assets/129540736/6d59ce43-8479-40f2-905e-2a68dff7736c)

**Comment by madebyfabian** [comment]
Hi there @tolgahanbeyazoglu, can you confirm that this issue still exists with the newest versions of all packages? (nuxt, nuxt-icon, etc...)?

**Comment by danielroe** [comment]
this does not seem to be a Nuxt issue in any case, nor can I reproduce on the latest Nuxt version.
