### ISSUE TITLE
[GET] "/_nuxt/builds/latest.json": 404 Cannot find static asset /_nuxt/builds/latest.json

### ISSUE THREAD

**Issue by waleedtariq109** [nuxt/nuxt#25280]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.19.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@10.2.3
- Builder:          vite
- User Config:      app, devServer, modules, alias, runtimeConfig, piniaPersistedstate, veeValidate, css, vite, imports, gtag, i18n
- Runtime Modules:  @pinia/nuxt@0.4.11, @pinia-plugin-persistedstate/nuxt@1.1.1, @nuxtjs/i18n@8.0.0-rc.3, nuxt-gtag@0.3.0, @vee-validate/nuxt@4.11.2, floating-vue/nuxt
- Build Modules:    -
------------------------------

### Reproduction

[Stackblitz](https://stackblitz.com/edit/github-wgwmfc)

### Describe the bug

This issue occurred in production. When the user logs in, we redirect them to another project for more context. Both projects (auth and investor) are built in Nuxt3. From there, it automatically logs the user out. I am not sure why this issue is occurring, but I have integrated Rollbar into the project, and Rollbar gives this error:

`[GET] "/_nuxt/builds/latest.json": 404 Cannot find the static asset /_nuxt/builds/latest.json`

**Comment by danielroe** [comment]
This is not a reproduction.

![CleanShot 2024-01-18 at 09 29 23@2x](https://github.com/nuxt/nuxt/assets/28706372/4567337e-5a7c-4470-a711-62eea601e046)

**Comment by vaidd4** [comment]
Having the same problem, I found this is a new behaviour of Nuxt 3.8: https://nuxt.com/blog/v3-8#app-manifest

as stated in the blog post, it can be disable with:
```
// nuxt.config.ts
export default defineNuxtConfig({
  experimental: {
    appManifest: false
  }
})
```

**Comment by vaheqelyan** [comment]
Same issue
