### ISSUE TITLE
Everything breaks down when you change the layout

### ISSUE THREAD

**Issue by Gonerman** [nuxt/nuxt#25307]
### Environment

- Operating System: Darwin
- Node Version:     v18.15.0
- Nuxt Version:     3.9.3
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-stprju

### Describe the bug

When changing layout my links break at least, on nuxt 3.8.2 everything worked fine

**Comment by manniL** [comment]
Wrapping the `<slot>` in an element (e.g. a `div`) will resolve that. Related to sth. like https://github.com/nuxt/nuxt/issues/25214

**Comment by ferferga** [comment]
@manniL While I agree with you that the slot should be wrapped in a div to avoid forgetting it, if you take a look at the given reproduction, both pages have divs as top level elements, so this issue should not happen (as OP pointed out, it worked fine in previous nuxt versions).

This is related to the upstream bug of Suspense I linked to the same issue you posted (so you're indeed right as well that this is a duplicate of that issue, but for completely unrelated reasons!)
