### ISSUE TITLE
 How can ‘addServerHandler ’ match dynamatic routes？

### ISSUE THREAD

**Issue by fairySusan** [nuxt/nuxt#25304]
### Describe the feature

like this:
```
 addServerHandler({
      route: `/[sitemapName]-sitemap.xml`,
      handler: resolve('./runtime/api-route')
})
```
I want to match `/genres-sitemap.xml` or  `/popular-sitemap.xml`  or `/any-sitemap.xml`

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
It's not currently possible - but you can track upstream in https://github.com/unjs/radix3/issues/68. (That's where the feature would need to be implemented.)

**Comment by manniL** [comment]
Also linking https://github.com/unjs/nitro/issues/1849 here 😋

**Comment by fairySusan** [comment]
I got a solution plan. 
` ``
addServerHandler({
      middleware:true,
      handler: resolve('./runtime/api-route')
})
```
// ./runtime/api-route.ts

```
import { parseURL } from 'ufo'
export default defineEventHandler(async (event) => {
   const path = parseURL(event.path).pathname
   if (!path.endsWith('-sitemap.xml')) return
   // next what do you want to do when route match '-sitemap.xml'
}
```
