### ISSUE TITLE
`defineModel` shoule enable by default

### ISSUE THREAD

**Issue by baixiaoyu2997** [nuxt/nuxt#25302]
### Environment

no need

### Reproduction

no need

### Describe the bug

defineModel stable since `vue v3.4`

**Comment by manniL** [comment]
It is!

https://stackblitz.com/edit/nuxt-issues-25302

If you are on an earlier nuxt version, make sure you update your Vue version / regenerate the lockfile ;)

**Comment by baixiaoyu2997** [comment]
thanks for reply,  I actually mean the documentation, and the type hints for the configuration file.
<img width="1234" alt="image" src="https://github.com/nuxt/nuxt/assets/9149999/7fac1461-4f69-4c3c-8ec9-3515c6403ca2">
![image](https://github.com/nuxt/nuxt/assets/9149999/89839446-dbe8-4508-9acd-4070a2c33c7c)
<img width="802" alt="image" src="https://github.com/nuxt/nuxt/assets/9149999/058dc200-c1a7-4069-924b-035e2f4193fd">

**Comment by manniL** [comment]
Good point 👍

**Comment by manniL** [comment]
Resolved via #25306
