### ISSUE TITLE
Bug: error TS2749: 'User' refers to a value, but is being used as a type here. Did you mean 'typeof User'?

### ISSUE THREAD

**Issue by martinszeltins** [nuxt/nuxt#25311]
### Environment

Environment: `Stackblitz` 👈️

```
Working directory: /home/projects/github-68jxaq                                                                12:13:23 PM
Nuxt project info:                                                                                             12:13:23 PM

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.9.3
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, imports
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Reproduction

https://stackblitz.com/edit/github-68jxaq?file=package.json,app.vue

### Describe the bug

I have a TypeScript enum in `common/types/user.ts` and I want to use this enum in my app. _(see Stackblitz reproduction)_. And it gets auto-imported by Nuxt but it seems to do it wrongly. Because if I manually import it myself it works _(typechecker does not complain)_. But if I let Nuxt auto-import do it then then typechecker is throwing this error:

```
$ npm run typecheck
> vue-tsc --noEmit

app.vue:9:23 - error TS2749: 'User' refers to a value, but is being used as a type here. Did you mean 'typeof User'?

9 const myFunc = (user: User) => {
                        ~~~~

Found 1 error in app.vue:9
```

**nuxt.config.ts:**
```js
export default defineNuxtConfig({
  devtools: { enabled: true },
  imports: {
    dirs: [
        'common/**/*.ts',
    ]
  }
})
```

**user.ts:**
```js
export enum User {
  ADMIN = 'admin',
  USER = 'user',
}
```

**app.vue**
```vue
<template>
  <div>My app</div>
  <button @click="myFunc(User.ADMIN)">My button</button>
</template>

<script setup lang="ts">
// import { User } from './common/types/user';

const myFunc = (user: User) => {
  if (user === User.ADMIN) {
    console.log('admin');
  } else {
    console.log('user');
  }

  console.log(user);
};
</script>
```

If I add the import _manually_ then typechecker does not complain 🤷🏻‍♂️ 

```js
import { User } from './common/types/user';
```

**Comment by manniL** [comment]
Might be an [unimport](https://github.com/unjs/unimport/) issue 👀

**Comment by martinszeltins** [comment]
> Might be an [unimport](https://github.com/unjs/unimport/) issue 👀 If you have time, could you try to repro it with autoimport only and open an issue there?

I'm not familiar with `unimport` or how it works. Not sure how to do that. 😞

**Comment by manniL** [comment]
@martinszeltins Take a look at https://stackblitz.com/github/unjs/unimport/tree/main/playground/ and see if this happens there too when using an enum in the Vue app. ☺️

**Comment by ericyyds** [comment]
Terrible code... but it works.

```ts
export enum UserEnum {
  Student = 1,
  Teacher = 2,
}

export type UserEnumType = UserEnum

function getUserPermsByUserType(userType: UserEnumType) {
  // ...
}

getUserPermsByUserType(UserEnum.Student)
```
