### ISSUE TITLE
Remove `templateUtils` 

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt#25338]
### Describe the feature

`templateUtils` for compiling templates is deprecated and can be removed in v4

https://github.com/nuxt/nuxt/blob/648ef069931336b8ee0c0e48fef3ee700ebc3dbe/packages/nuxt/src/core/app.ts#L37-L38

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
👉 Recommend `knitwork` for manually creating templates.

**Comment by danielroe** [comment]
implemented in https://github.com/nuxt/nuxt/pull/26925 under a flag (to be removed when v4 lands)
