### ISSUE TITLE
Remove `compileTemplate` for kit v4

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt#25332]
### Describe the feature

We can remove `compileTemplate` for Nuxt 4

https://github.com/nuxt/nuxt/blob/648ef069931336b8ee0c0e48fef3ee700ebc3dbe/packages/kit/src/internal/template.ts#L10-L27

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
implemented in https://github.com/nuxt/nuxt/pull/26925 under a flag (to be removed when v4 lands)
