### ISSUE TITLE
Scan `<subdir>/index` files for composables, plugins, middleware, etc.

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt#25331]
### Describe the feature

This PR will align scanning behavior for `plugins` with existing behavior for e.g. composables or middleware by only scanning top-level folders by default.

https://github.com/nuxt/nuxt/blob/648ef069931336b8ee0c0e48fef3ee700ebc3dbe/packages/kit/src/plugin.ts#L23-L27

Related: https://github.com/nuxt/nuxt/pull/18418/files

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by enkot** [comment]
@manniL What is the problem of scanning index files within subdirectories?
This is very convenient when you can logically divide the functionality of the plugin between files and keep in this directory.

**Comment by atorscho** [comment]
I agree with @enkot. I have multiple composable files prefixed with "account-" and it would be extremely useful to be able to separate them into different subdirectories.

Is there a functional/performance reason for this decision?
