### ISSUE TITLE
Emit absolute paths in `builder:watch` hook

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt#25339]
### Describe the feature

Related PR with discussion: https://github.com/nuxt/nuxt/pull/22333

Nuxt v4 would be the time to update that. Might need discussion before though.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
implemented in https://github.com/nuxt/nuxt/pull/26925 under a flag (to be removed when v4 lands)
