### ISSUE TITLE
Remove `window.__NUXT__` once app initialises

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt#25336]
### Describe the feature

Apparently it only exists for backwards-compat according to code comments:

https://github.com/nuxt/nuxt/blob/648ef069931336b8ee0c0e48fef3ee700ebc3dbe/packages/nuxt/src/app/plugins/revive-payload.client.ts#L52-L53

Nuxt v4 might be a good point to remove it if that's the case.

PR: #19205

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by martinszeltins** [comment]
I'm not familiar with internal Nuxt codebase but as a user of Nuxt, I kind of enjoy using `window.__NUXT__` to access data when Vue devtools are not available. I often look at pinia store through `window.__NUXT__.pinia`. And even cooler is that it is also available on prod which makes debugging really pleasant.

**Comment by manniL** [comment]
@martinszeltins you can use `window.useNuxtApp` in Nuxt 3 for that 😋
Here is a link to [the PR introducing it](https://github.com/nuxt/nuxt/pull/21636) and to [a video about it I made](https://www.youtube.com/watch?v=gMoipv_NkWE)

**Comment by martinszeltins** [comment]
> @martinszeltins you can use `window.useNuxtApp` in Nuxt 3 for that 😋 Here is a link to [the PR introducing it](https://github.com/nuxt/nuxt/pull/21636) and to [a video about it I made](https://www.youtube.com/watch?v=gMoipv_NkWE)

Ah, I wasn't aware of `window.useNuxtApp`, I guess in that case `window.__NUXT__` is indeed not needed anymore.

**Comment by sohaha** [comment]
In the case of closed SSR, currently window. Write too much unnecessary code, SPA application is not very friendly, there is no way to remove

**Comment by bbhxwl** [comment]
Is there a way to use a micro front-end?
