### ISSUE TITLE
`useAsyncData`: `getCachedData` + `immediate: false` don`t work

### ISSUE THREAD

**Issue by or2e** [nuxt/nuxt#25341]
### Reproduction

https://stackblitz.com/edit/nuxt-starter-g5apvu?file=pages%2Findex.vue

### Describe the bug

Composable `useAsyncData`.
`getCachedData` in combination with `immediate: false` don't behave as expected. 
In reproduction, when returning to the `/` page, the API request is still executed.

**Comment by manniL** [comment]
Duplicate of https://github.com/nuxt/nuxt/issues/24332
