### ISSUE TITLE
Upgrade ESLint config to v9 config system

### ISSUE THREAD

**Issue by luc122c** [nuxt/nuxt#25351]
### Describe the feature

From the ESLint docs:
> We are transitioning to a new config system in ESLint v9.0.0. The config system shared on this page is currently the default but will be deprecated in v9.0.0.

There is no timetable for v9 release ([see this blog post](https://eslint.org/blog/2023/11/whats-coming-in-eslint-9.0.0/#when-to-expect-eslint-v9.0.0)), however the new config system is "feature complete but not enabled by default" therefore, it seems desireable to think about switching to the new config system. 

See: 
- https://eslint.org/docs/latest/use/configure/configuration-files
- https://eslint.org/docs/latest/use/configure/configuration-files-new
- https://eslint.org/blog/2023/11/whats-coming-in-eslint-9.0.0
- https://github.com/eslint/eslint/discussions/17468

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
This issue is used to track changes for the the ESLint config used for the nuxt framework itself, not https://github.com/nuxt/eslint-config

**Comment by luc122c** [comment]
There is a tracker for plugin compatibility available: https://github.com/eslint/eslint/issues/18093
