### ISSUE TITLE
`useRoute()` returns old path

### ISSUE THREAD

**Issue by Yaxnice301** [nuxt/nuxt#25352]
### Environment

"nuxt": "^3.9.3",
"vue": "^3.4.14",
"vue-router": "^4.2.5"

### Reproduction

github repo https://github.com/Yaxnice301/bugreport.git

https://github.com/nuxt/nuxt/assets/141637740/8a9df018-4c05-4e7e-b706-5a1b76386902

### Describe the bug

The path displayed in my Route is different from the address in the web address.
And when refreshed, it will also jump to other pages

**Comment by manniL** [comment]
Possibly related: #24942 #25069 

Can you try using `useRouter().currentRoute` to check if that contains the correct value?

Also please reduce your reproduction *to a minimum*.

**Comment by Yaxnice301** [comment]
useRouter().currentRoute is correct

but useRoute() isn't

**Comment by Yaxnice301** [comment]
## Let me elaborate (Later I upload a brief code using `codesandbox`)

Route from `/login` `[no layout]` to `/user/info` `[default layout]`,

```typescript
  //    false
  useRouter().currentRoute.value.path === useRoute().path
```

```typescript
// layouts/default.vue

onMounted(() => {
  //  -->  /user/info
  console.log(useRouter().currentRoute.value.path)
  //  -->  /login
  console.log(useRoute().path)
})
```

After manually refreshing the page
```typescript
  //   true
  useRouter().currentRoute.value.path === useRoute().path
```

But if I have a middleware to verify that the user is logged in

```typescript
// stores/user.ts

import { defineStore } from 'pinia'

type User = {
  id: string
  name: string
  role: string[]
}

const useUserStore = defineStore({
  id: 'user',
  state: (): {isLoggedIn: boolean,user: User} => ({
    isLoggedIn: false,
    user: {
      id: '',
      name: '',
      role: []
    }
  }),
  actions: {
    login(user: User){
      this.isLoggedIn = true
      this.user = user
    },
    logout(){
      this.isLoggedIn = false
    }
  }
})

export default useUserStore
```

```typescript
// middleware/01.auth.global.ts

import useUserStore from "~/stores/user";

export default defineNuxtRouteMiddleware((to, from) => {

  const userStore = useUserStore()

  if(!to.meta.noAuth && !userStore.$state.isLoggedIn){
    console.log(!userStore.$state.isLoggedIn)
    useRouter().push('/login')
  }
});
```

After the page is refreshed, the route is redirected to `/login` even if the user is logged in
I think this is due to a problem with `useRoute()`

I'm not sure if this is a `vue-router` problem or a `nuxt` problem

**Comment by Yaxnice301** [comment]
### That's the first question. I'll show you the second one later
I have tried very hard to use codesandbox, but the effect is not satisfactory, I will upload the code to github, please check:
> https://github.com/Yaxnice301/bug_one.git

This code is about the inconsistency between `useRouter().currentRoute.value.path` and `useRoute().path`
Here's the weird thing:
The output in the console is inconsistent, but the data presented in the page components is consistent

**Comment by Yaxnice301** [comment]
## `useState([key]).value ` lose status after refresh
## I tried `localStorage` , but it didn't work.

Any suggestions?

**Comment by daniluk4000** [comment]
@Yaxnice301 [my workaround that rely on middleware](https://github.com/nuxt/nuxt/issues/24942#issuecomment-1895586730) should work fine for you.

The issue is really weird tho. Maybe layouts are related somehow.

Can you also check route within useNuxtApp()._route?

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/21340.
