### ISSUE TITLE
Uncaught ReferenceError: globalThis is not defined in old browsers (Chrome 65)

### ISSUE THREAD

**Issue by radislaw** [nuxt/nuxt#25368]
### Environment

- Operating System: Linux
- Node Version:     v18.19.0
- Nuxt Version:     3.9.3
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

The Nuxt starter template is enough to reproduce the issue. You just need to open it in Chrome 65

### Describe the bug

I'm using the Nuxt starter template. When I run yarn build and then preview in Chrome 65 browser. I get an error in the browser console:
`entry.J2zEOy1-.js:13 Uncaught SyntaxError: Unexpected token ?`

In order to solve this problem, I use the Vite settings in nuxt.config
```
 vite: {
        build: {
            target: ['chrome65'],
        },
    }

```

After restarting yarn build, I get the following error
```
Uncaught ReferenceError: globalThis is not defined
    at entry.IRimNRDK.js:17
```

I tried using the plugin `@vitejs/plugin-legacy` and even `nuxt-vite-legacy` and separately connect the polyfile for globalThis, but it does not bring any effect, despite the fact that the final Html contains scripts with polyfile and legacy code
![image](https://github.com/nuxt/nuxt/assets/11686471/614eaf61-9790-4724-b03e-85c2323f50da)

and there is an error in the console

![image](https://github.com/nuxt/nuxt/assets/11686471/0aa05b81-cced-4d09-b40b-272b3598b408)

### Logs

```shell-script
entry-legacy.rwZSLLd-.js:1 Uncaught ReferenceError: System is not defined
    at entry-legacy.rwZSLLd-.js:1
(anonymous) @ entry-legacy.rwZSLLd-.js:1
entry.VwnH7qei.js:17 Uncaught ReferenceError: globalThis is not defined
    at entry.VwnH7qei.js:17
(anonymous) @ entry.VwnH7qei.js:17

The error refers to this code
globalThis.__buildAssetsURL=Gt,globalThis.__publicAssetsURL=m1;
```

**Comment by manniL** [comment]
Hey! Please have a look at https://github.com/nuxt/nuxt/issues/14893 and all the linked issues in there (such as https://github.com/nuxt/nuxt/issues/19328).

We [decided last year](https://github.com/nuxt/nuxt/issues/15464#issuecomment-1596895289) that we don't support legacy support as part of the core but would be happy to see a module implementation
