### ISSUE TITLE
Nuxt does not recognize globally registered components (type: unknown)

### ISSUE THREAD

**Issue by martinszeltins** [nuxt/nuxt#25371]
### Environment

Stackblitz

```
Working directory: /home/projects/github-vom1ml                                                                10:32:25 AM
Nuxt project info:                                                                                             10:32:25 AM

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.9.3
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Reproduction

https://stackblitz.com/edit/github-vom1ml?file=plugins%2Ffontawesome.ts,app.vue

### Describe the bug

I was following the installation guide of FontAwesome for Nuxt 3 at https://fontawesome.com/docs/web/use-with/vue/use-with#nuxt

Basically, it says that to add a global `<FontAwesomeIcon>` component, you need to register it using:

```js
export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component('font-awesome-icon', FontAwesomeIcon)
})
```

And yes, the component is working and the icon does show up. But VSCode does not recognize this component, it shows `unknown`. Which means it does not have autocomplete for props, type checking etc.

Screenshot:
![image](https://github.com/nuxt/nuxt/assets/34019878/15eeac06-32a3-4aa3-8158-316a2b0f5c36)

This happens with any 3rd party component that I want to register globally using `vueApp.component(...)`. I have Volar installed and my local auto-imported components are indeed recognized. Also I see that all Nuxt components are also recognized like `<NuxtLayout>` and `NuxtLoadingIndicator` etc.

So why aren't my own custom-registered 3rd party components recognized? Is it the wrong approach to use `nuxtApp.vueApp.component()`?

**Comment by danielroe** [comment]
This isn't a Nuxt issue. The third party library needs to provide type definitions or you need to augment the global context.

Alternatively, you can use `addComponent` from `@nuxt/kit` and Nuxt will augment the global context for you (and only import the component if it is used).

**Comment by martinszeltins** [comment]
@danielroe how do I augment the global context? is there some example that I can look at?

**Comment by danielroe** [comment]
You can add this to your plugin:

```ts
declare module 'vue' {
  interface GlobalComponents {
    FontAwesomeIcon: typeof FontAwesomeIcon
  }
}
```

**Comment by martinszeltins** [comment]
> You can add this to your plugin:
> 
> ```ts
> declare module 'vue' {
>   interface GlobalComponents {
>     FontAwesomeIcon: typeof FontAwesomeIcon
>   }
> }
> ```

Thanks, that's exactly what I was looking for! Works like a charm! 👍🏻
