### ISSUE TITLE
ref<VNodeRef>() recursive call when the name of the variable corresponds to the component name

### ISSUE THREAD

**Issue by RomainMazB** [nuxt/nuxt#25373]
### Environment

- Operating System: Linux
- Node Version:     v18.15.0
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.6.1
- Builder:          -
- User Config:      dev, runtimeConfig, devServer, routeRules, modules, i18n, css, vite
- Runtime Modules:  @pinia/nuxt@0.5.1, @pinia-plugin-persistedstate/nuxt@1.2.0, @nuxtjs/i18n@8.0.0-rc.11, @nuxtjs/tailwindcss@6.10.1, @nuxt/content@2.9.0
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-tfw8ur?file=app.vue

### Describe the bug

As you can see in the reproduction link, when we use a variable `myComponent` to store a `ref` of a component named `my-component`, the component is not rendered as this falls into a recursive call.
```html
<template>
  <my-component ref="myComponent" />
</template>

<script setup>
const myComponent = ref(null);
</script>
```
Renaming the ref variable to something that to not correspond to the component name like `somethingElse` makes it work.

### Logs
On stackblitz:
```shell-script
[Vue warn]: Component is missing template or render function. 
  at <Anonymous ref="myComponent" > 
  at <App key=3 > 
  at <NuxtRoot>
```
On local machine:
```shell-script
[Vue warn]: Maximum recursive updates exceeded in component <PieceOfPaper>. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function. 
```

**Comment by danielroe** [comment]
This is Vue behaviour. 

https://play.vuejs.org/#eNp9kL1Ow0AQhF/ltE1ACk6RLjiRAKWAAhBQXmM5a3Ph/nQ/wZHld2fvIgcXkM6e+XZudnu4s7Y4RIQVlAGVlVXADdeMlep4UxtljUYdmMNmzUEdH0aFA1sQVy4mQ/TraydsYB5DtKQIol1gfZpnA2ucUWxGr824ro32gU0S2TpRVzpKeX2bkk9ZG5hD8EQ3oi323mhq2qeCHFI9IdG92CAojcOKZSd5lZTm+ylrwUWcj3r9ifXXH/red0nj8OrQozsgh7MXKtcibZzs7fszdvR9NpXZRUn0BfMNvZExdTxh91HvqPaEy20f87GEbj/8tguo/bhUKprIIfMc6IDpav+t/lt3WSzzHNcDDD/PZ6QY
