### ISSUE TITLE
[Nuxt 2.17.0]Can optional chaining be used with v-model?

### ISSUE THREAD

**Issue by Kazu0929** [nuxt/nuxt#25388]
### Environment

@nuxt/types: 2.17.3 
@nuxt/typescript-build:  2.1.0 
nuxt: 2.17.0 

### Reproduction

..

### Describe the bug

I am using optional chaining and nullish coalescing within the template and script.

There is nothing wrong with using them in mustash syntax or as function arguments.

However, using these in v-model results in a build error.

Is using these in v-model supported in 2.17.0 of Nuxt.js?

### Logs

```shell-script
Module build failed (from ./node_modules/vue-loader/lib/loaders/templateLoader.js):
SyntaxError: Unexpected token (33:241)
```

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
