### ISSUE TITLE
Automatic add of `@` for twitter site on `useSeoMeta`

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt/nuxt#25382]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.11.0
- Nuxt Version:     3.9.3
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.6.12
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

/

### Describe the bug

Hello,

Could be a great addition to automatically add `@` to the beginning of the twitter site. Otherwise, a type could alert dev that he should add one.

For reference: https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started

**Comment by manniL** [comment]
Might be a better request for https://github.com/unjs/unhead/

cc @harlan-zw

**Comment by danielroe** [comment]
Closing here but do open in `unhead` 🙏
