### ISSUE TITLE
clearError throws TypeError: node is null

### ISSUE THREAD

**Issue by miteyema** [nuxt/nuxt#25384]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.11.0`
- Nuxt Version:     `3.9.3`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `npm@10.2.4`
- Builder:          `-`
- User Config:      `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Sandbox: https://codesandbox.io/p/sandbox/clear-error-typeerror-node-is-null-yp248m

Steps to reproduce:

- Go to any slug URL, e.g. https://yp248m-3000.csb.app/test
- Page correctly shows 404 error
- Click the "Handle error" button

### Describe the bug

After clicking the "Handle error" button, there is
- no redirection at all
- the browser console shows `Uncaught (in promise) TypeError: node is null NuxtJS runtime-dom.esm-bundler.js:39:24`

### Logs

```shell-script
Uncaught (in promise) TypeError: node is null
    NuxtJS 4
        parentNode
        resolve
        resolve
        registerDep
```

**Comment by markthree** [comment]
To add to the description, according to my tests, the issue is triggered whenever `NuxtLayout` is used in `error.vue`

For example, I don't have this problem now when I use div wrapping 👇
```vue
<!-- error.vue -->
<template>
  <div>
    <h1>Error {{ error?.statusCode }}</h1>
    <button class="btn btn-primary" @click="handleError">Handle error</button>
  </div>
</template>

<!-- ignore some code -->
```

The codesandbox I forked → [codesandbox](https://codesandbox.io/p/devbox/clear-error-typeerror-node-is-null-forked-x8ff35?file=%2Ferror.vue%3A1%2C1-6%2C12&workspaceId=34ff5319-a739-46ac-8b8f-87a7a8350204)

**Comment by danielroe** [comment]
In this case the issue is that NuxtLayout can't be the root component. But you can work around by adding another root element.

```diff
  <template>
+   <div>
      <NuxtLayout>
        <h1>Error {{ error?.statusCode }}</h1>
        <button class="btn btn-primary" @click="handleError">Handle error</button>
      </NuxtLayout>
+   </div>
  </template>
```

Let's track in https://github.com/nuxt/nuxt/issues/25214.
