### ISSUE TITLE
Add a way to use our own custom routes without folder structure

### ISSUE THREAD

**Issue by GhostvOne** [nuxt/nuxt#25386]
### Describe the feature

Nuxt routing using folders is a nightmare for complex routes.
Can I suggest a way to generate our custom router file without using the pages:extend hook?

The option to define a custom route in router.options.ts is also not good because Nuxt will not extend any new routes you return from the routes function with metadata defined in definePageMeta.

We should be able to choose to use a pre-generated routes with page directories or use our own custom rules routing file. With your own custom routing files we could be able to use everything from vue router like regex for matching route.

Thank you.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
You can use `pages:extend` hook. Or you can use `app/router.options` and get the metadata at runtime when you augment the routes. (What isn't working, specifically?)

Finally, this PR will allow the `pages:extend` hook to receive route metadata: https://github.com/nuxt/nuxt/pull/25210.
