### ISSUE TITLE
nuxt3  input button

### ISSUE THREAD

**Issue by WalkAlone0325** [nuxt/nuxt#25385]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.10.0
- Nuxt Version:     3.9.3
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.13.1
- Builder:          -
- User Config:      ssr, devtools, app, runtimeConfig, css, vite, elementPlus, modules
- Runtime Modules:  @pinia/nuxt@0.4.11, @element-plus/nuxt@1.0.6, @vueuse/nuxt@10.4.1
- Build Modules:    -
------------------------------

### Reproduction

```html
<input v-model="personalForm.userName" placeholder="请输入用户账号" />
  <input v-model="personalForm.password" placeholder="请输入密码" type="password" />
   <button type="primary" size="large" @click="handleLogin">登录</button>
```

```js
const personalForm = reactive({
  userName: '',
  password: '',
})

const handleLogin = async () => {
      try {
        const res = await loginApi(personalForm)
        console.log(res)
      } catch (e) {
      }
}
```

### Describe the bug

填写 input 后，点击登录按钮调用接口，然后修改输入框，会一直调用接口

```[tasklist]
### Tasks
```

**Comment by markthree** [comment]
@WalkAlone0325 I assume you're using useFetch, which turns on watch mode by default, but I can't see an implementation of loginApi.

Based on the use case you gave me, I think a direct re-decomposition of the data would solve your problem。

for example 👇

```ts
const personalForm = reactive({
  userName: '',
  password: '',
})

const handleLogin = async () => {
      try {
        const res = await loginApi({ ...personalForm })
        console.log(res)
      } catch (e) {
      }
}
```

**Comment by WalkAlone0325** [comment]
@markthree That's right.I need to learn more about `useFetch`...thanks.
