### ISSUE TITLE
Value dissapeared 

### ISSUE THREAD

**Issue by fearart** [nuxt/nuxt#25405]
### Environment

Working directory: C:/dev/hotel-viewer                                                                                                                                                   21:00:40
Nuxt project info:                                                                                                                                                                       21:00:40

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.10.0
- Nuxt Version:     3.9.3
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.21
- Builder:          -
- User Config:      devtools, modules, runtimeConfig, colorMode, ssr, app, googleFonts, ui, nitro
- Runtime Modules:  @nuxt/ui@2.12.3, @pinia/nuxt@0.5.1, @nuxtjs/google-fonts@3.1.3
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                                                                                              21:00:40

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Reproduction

↓

### Describe the bug

Created an endpoint which return an object. Fetched it in `getFloorInfo()` method and set value of kitchen Object to var `kitchens`. Then check logic of `openKitchenModal` method. The value just dissapears / don't get passed / or event worse when trying to do like this 
```js
kitchens.value.forEach((k) => {
        if (k.name === kitchen_name) {
            kitchen = k
            return
        }
    })
    console.log(kitchen)
    openedKitchen.value = kitchen
```
it CLEARS OBJECT in the `kitchens`. So that name and other params are "" but somehow `id` is keeped
    

### Additional context

 Images : 
 
![image](https://github.com/nuxt/nuxt/assets/68917859/53597810-8fd4-47af-8d75-46cc5f692395)
![image](https://github.com/nuxt/nuxt/assets/68917859/ca17d829-a25f-412c-a071-adcceb4fd594)
![image](https://github.com/nuxt/nuxt/assets/68917859/39bd992c-1fbc-4b3d-b4bb-bb88056dbeab)
![image](https://github.com/nuxt/nuxt/assets/68917859/0c7e0d17-df6a-4779-a7cb-a6ba44207be0)

**Comment by fearart** [comment]
codebase: https://github.com/fearart/hotel-viewer/tree/bugs

**Comment by fearart** [comment]
UPD it was due to maska, but i have no clue why original value was impacted so i'll keep the issue

**Comment by fearart** [comment]
https://stackblitz.com/edit/nuxt-starter-xvisqv?file=package.json

**Comment by madebyfabian** [comment]
@fearart Do you still experience this in the latest Nuxt version?

**Comment by fearart** [comment]
welp i forgot to add UPD. That was caused by v-maska directive. So if anyone have similar issues, check your input's mask firstly
