### ISSUE TITLE
`callOnce` run multiple times in client-only components

### ISSUE THREAD

**Issue by becem-gharbi** [nuxt/nuxt#25419]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.9.3
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-6wtgz2?file=app.vue

### Describe the bug

The reproduction contains a client-only component. This component calls `callOnce` on setup.
The problem is when multiple instances are rendered the callbacks of `callOnce` are all executed. 
I'm not sure if this is intentional or an issue with reactivity.

**Comment by becem-gharbi** [comment]
> What would be the expected behavior? That the callOnce just run once (in the first component) because the key is the same for all instances?

Yes I think that.

**Comment by manniL** [comment]
If you return a non-nullish value that should work. e.g.

```ts
await callOnce('key-1', () => {
  called.value = true;
  return 1
});
```

**Comment by becem-gharbi** [comment]
> If you return a non-nullish value that should work. e.g.

Unfortunately this didn't solve the issue. After debgging this seems to be related to the await executed before registering the callOnce's key.

https://github.com/nuxt/nuxt/blob/44fcacba846a6cdf33e1475fc8413f6ae49d1fe4/packages/nuxt/src/app/composables/once.ts#L29

**Comment by becem-gharbi** [comment]
I faced this issue in a project I'm working on. The return value didn't solve the issue in contrast to the await fix. Maybe I should make another reproduction. This issue is simple, I will create a PR for this with test.

**Comment by becem-gharbi** [comment]
I misplaced `return 1` previously, I'm sorry for that. Your solution works perfectly!
