### ISSUE TITLE
Nuxt 3 caching with ISR/SWR does not work as expected on Netlify

### ISSUE THREAD

**Issue by TroyanOlga** [nuxt/nuxt#25418]
### Environment

- Operating System: Linux
- Node Version:     v18.16.0
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.14.1
- Builder:          -
- User Config:      ssr, routeRules
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

The issues described can be viewed on this deployment: https://extraordinary-zuccutto-58a082.netlify.app. Currently it is deployed without Nitro preset.

### Describe the bug

I have a minimal Nuxt 3 app with different pages set up to use different rendering modes:
https://github.com/RisingStack/nuxt3-cashing-with-auth-clone

nuxt.config is as following:
```javascript
export default defineNuxtConfig({

ssr: true,

routeRules: {

"/isr_ttl": { isr: 60 },

"/isr_no_ttl": { isr: true },

"/swr_ttl": { swr: 60 },

"/swr_no_ttl": { swr: true },

},

});
```
I use 2 timestamps to check whether caching works as expected: one comes from API response, another one is rendered in browser.

I tried deploying this app to Netlify with different nitro presets or without a preset at all and all of the deploys produce unexpected behaviour with at least some rendering modes. Please see the summary below:

NITRO_PRESET = netlify_builder

SSR: cached for at least 2 mins

SWR without TTL: cached permanently

SWR with TTL of 60 seconds: cached permanently

ISR without TTL: cached permanently

ISR with TTL of 60 seconds: cached permanently

Unexpected behaviour:

SSR (expected no caching),

SWR without TTL (expected to be cached until response changes),

SWR with TTL of 60 seconds (expected to be cached for 60 seconds),

ISR with TTL of 60 seconds (expected to be cached for 60 seconds),

NITRO_PRESET = netlify_edge

SSR: no caching

SWR without TTL: cached until response changes

SWR with TTL of 60 seconds: cached for 60 seconds

ISR without TTL: no caching

ISR with TTL of 60 seconds: no caching

Unexpected behaviour:

ISR without TTL (expected to be cached permanently),

ISR with TTL of 60 seconds (expected to be cached for 60 seconds),

NITRO_PRESET = netlify

SSR: no caching

SWR without TTL: cached permanently

SWR with TTL of 60 seconds: cached permanently

ISR without TTL: cached permanently

ISR with TTL of 60 seconds: cached permanently

Unexpected behaviour:

SWR without TTL (expected to be cached until response changes),

SWR with TTL of 60 seconds (expected to be cached for 60 seconds),

ISR with TTL of 60 seconds (expected to be cached for 60 seconds),

no NITRO_PRESET

SSR: no caching

SWR without TTL: cached permanently

SWR with TTL of 60 seconds: cached permanently

ISR without TTL: cached permanently

ISR with TTL of 60 seconds: cached for at least 2 mins

Unexpected behaviour:

SWR without TTL (expected to be cached until response changes),

SWR with TTL of 60 seconds (expected to be cached for 60 seconds),

ISR with TTL of 60 seconds (expected to be cached for 60 seconds),

I opened a topic in the Netlify forum: [topic](https://answers.netlify.com/t/nuxt-3-caching-with-isr-swr-does-not-work-as-expected/110715) and they answered that this is a Nuxt issue, specifically "Nuxt would have to make sure that its presets are now following the Netlify’s cache control headers (which should work if they’re following the standard)". 
Looking for clarification if there is any nitro preset which is expected to work with all rendering modes on Netlify or some clarification regarding to which preset supports which rendering mode.

**Comment by jbool24** [comment]
Bumping this as it's still an open issue and Netlify claims this is a Nuxt config issue.

Clarifications Team?

**Comment by cfab** [comment]
same here !

**Comment by timbkr** [comment]
same here..

**Comment by manniL** [comment]
This is most likely something which has to be resolved in https://github.com/unjs/nitro

**Comment by Hoan-Duong** [comment]
same here !

**Comment by danielroe** [comment]
If you're still experiencing this, would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏

If it only recurs with Nuxt, let me know and I'll reopen it here.

**Comment by plexus77** [comment]
I am using the latest version of nuxt with the netlify_builder preset and isr is caching permanently, I have trigger a deployment to clear it...

**Comment by manniL** [comment]
@plexus77 see the comment above yours!

**Comment by francisneedham** [comment]
Hi ! any updates on this - we are experiencing this problem with all of our Sanity + Netlify  projects and it's terrible as right now we are using ISR and run a deploy task everytime we change content to regenerate the cache.
it's very easy to replicate the issue - just deploy on netlify a nuxt 3 application and the settings are not working.

**Comment by danielroe** [comment]
See my comment above - can you try to reproduce with nitro alone and raise an issue there? 🙏

**Comment by danielroe** [comment]
The sandbox has a minimal amount of code. You can clone it and use it to deploy to netlify yourself. Then add it to a GitHub repository and use that as the repro.

**Comment by francisneedham** [comment]
Not working on netlify ( https://nitrocachetest.netlify.app/test_swr_time ) => should refresh every 10 seconds but is not.

opened an issue on nitro github
https://github.com/unjs/nitro/issues/2617

**Comment by danielroe** [comment]
Thank you! 🙏
