### ISSUE TITLE
[Bug] When using auto-import - library loses all TypeScript types

### ISSUE THREAD

**Issue by martinszeltins** [nuxt/nuxt#25412]
### Environment

Stackblitz

```
Working directory: /home/projects/nuxt-starter-t11enq
Nuxt project info:
------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.9.3
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, imports
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Reproduction

https://stackblitz.com/edit/nuxt-starter-t11enq?file=app.vue

### Describe the bug

I wanted to use the [fuzzysort](https://www.npmjs.com/package/fuzzysort) npm package in my Nuxt project. When I use a manual import then VSCode shows all the TypeScript types correctly:

```vue
<template>
    <div>
        {{ result }}
    </div>
</template>

<script lang="ts" setup>
    import fuzzysort from 'fuzzysort'

    const result = fuzzysort.single('query', 'some string that contains my query.');
</script>
```

Screenshot:
![image](https://github.com/nuxt/nuxt/assets/34019878/2cc3767a-ba02-4be5-8517-604fdc196ab7)

The library itself does come with TS types as can be seen in `node_modules/fuzzysort/index.d.ts` - that's why the manual import approach works.

But when I remove the manual import and add auto-import for `fuzzysort` in my `nuxt.config.ts` then the types are no longer working and shows `any`

**nuxt.config.ts**

```js
export default defineNuxtConfig({
    devtools: { enabled: false },
  
    imports: {
      presets: [
        {
          from: 'fuzzysort',
          imports: [
            {
              name: 'default',
              as: 'fuzzysort',
            },
          ],
        },
      ],
    },
  });
```

And now the result looks like this:

Screenshot:
![image](https://github.com/nuxt/nuxt/assets/34019878/547b8dad-2c69-44d3-81e0-bb9849a0058f)

The thing is that in both (manual import and auto-import) the library works as expected in runtime. The only issue is that in my IDE I no longer get TS types if I use Nuxt auto-import instead of manual import.

I tried adding a type declaration file `types/fuzzysort.d.ts` but no matter what I tried it didn't work, it still showed `any` for types.

I tried adding this to `tsconfig.json`

```json
{
  "extends": "./.nuxt/tsconfig.json",
  "files": [
    "types/fuzzysort.d.ts"
  ],
}
```

And I tried with this approach which did not work:

```js
declare module 'fuzzysort' {
    const fuzzysort: fuzzysort.Fuzzysort
    export = fuzzysort
}
```

I also tried this which also did not work:

```js
declare module 'fuzzysort' {
    export default {
        single: (search: string, target: string) => string,
    }
}
```

I'm out of options. I have no clue why using the auto-import loses types and what I need to do to get them back. It looks like a Nuxt bug. I can always use the manual import approach but I would rather take advantage of Nuxt's auto-imports.

**Comment by manniL** [comment]
Can you also check here if this is a thing with [plain unimport](https://github.com/unjs/unimport) ☺️ ?

**Comment by markthree** [comment]
@martinszeltins I tested it and the package can't resolve the specific type from the relative paths

for example 

![image](https://github.com/nuxt/nuxt/assets/36569518/6294170a-67ed-4958-97bf-2f3b93a72579)

tip → This is because nuxt's internal unimport uses relative paths to resolve specific packages when generating types

I'm not sure if this is a typescript problem or a unimport problem.

But I think one of the simplest solutions is to create `utils/fuzzysort.ts` 🤣

```ts
// utils/fuzzysort.ts
import fuzzysort from "fuzzysort";

export default fuzzysort;
```

Without any configuration, you can get the best type of `fuzzysort`

![image](https://github.com/nuxt/nuxt/assets/36569518/d8364296-2644-46db-83e7-0ecab1ed71be)

**Comment by n0099** [comment]
Did you ran `npm nuxt prepare`? Does `.nuxt/imports.d.ts` has any line exporting from `fuzzysort`?

**Comment by danielroe** [comment]
There are two issues here:

1. we do not need to use relative path imports for explicit project dependencies - we can resolve this
2. `fuzzysort`'s types use `export = ` syntax which causes issues here for the `typeof import('fuzzysort')['default']` syntax - which is unfortunately something that needs to be resolved in `fuzzysort`: https://github.com/farzher/fuzzysort/issues/94
