### ISSUE TITLE
missing important inline styles from components used across multiple pages

### ISSUE THREAD

**Issue by gibkigonzo** [nuxt/nuxt#25420]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.9.0
- Nuxt Version:     3.9.3
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction
**!!! It only appears in production mode. Run** `yarn build && yarn preview`

https://codesandbox.io/p/devbox/affectionate-lederberg-vz2xsy

### Describe the bug
When a component is used across multiple pages, the styles associated with that component do not appear as inline styles. This issue arises because these components are likely candidates for quick loading. For instance, I have an icon component that appears on every page. From a performance perspective, it's crucial to load the styles from this component as soon as possible, similar to critical CSS. In a real application, there may be components responsible for establishing the page layout, and they should ideally be loaded as soon as possible.

In reproduction, you'll notice that the "IconComponent" turns red once the styles from the file are applied. This delay increases the First Contentful Paint (FCP). Those styles should be loaded as critical css (which worked that way in nuxt 2).

![Screenshot from 2024-01-24 16-12-44](https://github.com/nuxt/nuxt/assets/42383376/f42ea46b-f876-4979-9d0d-01e564d3cd54)

However, if you delete the `test.vue` page, the styles from the "IconComponent" are added as inline CSS.

![Screenshot from 2024-01-24 16-24-12](https://github.com/nuxt/nuxt/assets/42383376/90d77cd6-fbae-482d-9aaf-c5c2517447b4)

Is this behavior expected? Is there a method to enforce inline styles for certain components?

Could this issue be related to https://github.com/nuxt/nuxt/issues/22507 ?

### Additional context

Even when I add this component as suggested here https://github.com/nuxt/nuxt/issues/22507#issuecomment-1757833275
Those styles are still not included as inline.
https://codesandbox.io/p/devbox/gifted-noyce-j3rncx

![Screenshot from 2024-01-24 16-42-50](https://github.com/nuxt/nuxt/assets/42383376/d963b661-9d14-42f0-9162-c1498b206042)

**Comment by danielroe** [comment]
resolved in https://github.com/nuxt/nuxt/pull/25455
