### ISSUE TITLE
Parentheses in path name

### ISSUE THREAD

**Issue by piotr-f6s** [nuxt/nuxt#25421]
### Environment

- Operating System: Linux
- Node Version:     v20.9.0
- Nuxt Version:     3.9.3
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  ./modules/export-routes.js
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-sg7brw?file=modules%2Fexport-routes.js

### Describe the bug

If you go to reproduction repo, you will see log `[ '/', '/posts/:id()' ]` in terminal during installation. Note that posts path has parentheses.
[Nuxt docs](https://nuxt.com/docs/getting-started/routing) say that generated route is without any`()`:
```
    {
      "path": "/posts/:id",
      "component": "pages/posts/[id].vue"
    }
```

Is it a bug? Where do these parentheses come from? It's hard to find anything on Google about this. I need 'clean' paths like in Nuxt 2 to export paths to a file using `path-to-regexp`.

**Comment by danielroe** [comment]
The parentheses are important to terminate the slug. You can just remove them if you are exporting paths to a file.
