### ISSUE TITLE
When using useFetch form is submitted for each key press

### ISSUE THREAD

**Issue by getshcc** [nuxt/nuxt#25426]
### Environment

- Operating System: Windows_NT
- Node Version:     v21.6.0
- Nuxt Version:     ^3.2.3
- Nitro Version:    ^2.2.3
- Package Manager:  unknown
- Builder:          webpack
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://github.com/getshcc/nuxt-auth

### Describe the bug

when using `useFetch` in `*.vue` file after submit form for first time. The form is submitted for each key press.

Mongodb:
![useFetch-2024-25-1](https://github.com/nuxt/nuxt/assets/92691902/dd33e33c-80d3-4cca-ac32-0d0637f14d0a)

### Additional context

when i changed `useFetch` to `$fetch` problem fixed.

**Comment by warflash** [comment]
You shouldn't register useFetch inside a function, it should almost always be on the top level scope.
Here's a video explaining why and how to properly use it: https://www.youtube.com/watch?v=njsGVmcWviY, alternatively note the info box in the docs: https://nuxt.com/docs/api/composables/use-fetch
