### ISSUE TITLE
Server-side rendering with Nitro preset cloudflare_module and router.addRoute() not working

### ISSUE THREAD

**Issue by nicgene** [nuxt/nuxt#25428]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.9.3
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, pages
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://github.com/nicgene/nuxt-add-route/

### Describe the bug

Hello, I'm deploying Nuxt 3 on Cloudflare Workers using the Nitro preset cloudflare_module. When adding routes from a plugin, the component isn't server-side rendered. I've attempted to reproduce this issue using the regular cloudflare preset, but I couldn't. Additionally, I've tried deploying to Netlify and Vercel without encountering the same problem. Therefore, I believe this issue is specific to the cloudflare_module preset.

```
// plugins/addRoute.ts
export default defineNuxtPlugin(async (nuxtApp) => {
  const router = useRouter();
  router.addRoute({
    name: "test",
    path: "/test",
    component: () => import("~/components/test.vue"),
  });
});

```

### Additional context

- Example deployed to Cloudflare Workers using the cloudflare_module preset - https://nuxt-add-route.dupkey.workers.dev/test
- Netlify - https://nuxt-add-route.netlify.app/test
- Vercel - https://nuxt-add-route.vercel.app/test

**Comment by danielroe** [comment]
I think you likely need to do: `component: () => import("~/components/test.vue").then(r => r.default || r)`

**Comment by nicgene** [comment]
That worked. Thank you very much!
