### ISSUE TITLE
@click event handle doesn't work in IE 11

### ISSUE THREAD

**Issue by e7868a** [nuxt/nuxt#25430]
### Environment

  System:
    OS: Linux 5.15 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (6) x64 Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz
    Memory: 4.40 GB / 7.76 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
  Browsers:
    Chrome: 119.0.6045.105
  npmPackages:
    @nuxt/http: ^0.6.4 => 0.6.4
    @nuxt/types: ^2.15.8 => 2.17.3
    @nuxt/typescript-build: ^2.1.0 => 2.1.0
    nuxt: ^2.15.8 => 2.17.3

### Reproduction

create a nuxt2 application following [https://v2.nuxt.com/examples/data-fetching/async-data](https://v2.nuxt.com/examples/data-fetching/async-data) . 

copy souces from  [https://github.com/nuxtlabs/examples/blob/master/data-fetching/async-data-hook/pages/mountains/_slug.vue](https://github.com/nuxtlabs/examples/blob/master/data-fetching/async-data-hook/pages/mountains/_slug.vue)

This page uses a Back button to return to the previous page, and specifies the `goBack` function using `@click`. when the user clicks the button, it should return to the previous page.

### Describe the bug

the example work fine in Chome.

But in IE 11, clicking on the "Back" button doesn't work, and no errors are reported in the Console.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
