### ISSUE TITLE
`useRequestEvent` return type should be `H3Event | undefined`

### ISSUE THREAD

**Issue by antoinerey** [nuxt/nuxt#25442]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.10.0`
- Nuxt Version:     `3.8.0`
- CLI Version:      `3.9.1`
- Nitro Version:    `2.7.0`
- Package Manager:  `npm@8.19.4`
- Builder:          `-`
- User Config:      `app`, `extends`, `runtimeConfig`, `modules`, `vue`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Execute the following client-side. It will throw a type error even though TypeScript is perfectly fine with such code.

```ts
const event = useRequestEvent()
console.log(event.property)      // Type error. Reading property of undefined.
```

### Describe the bug

The helper function `useRequestEvent` may be executed seamlessly on both client and server sides. However, they do not return the same thing.

- On the server, it returns a proper `H3Event` instance.
- On the client, it returns `undefined`.

However, its return type does not reflect that. [It's manually cast into `H3Event`](https://github.com/nuxt/nuxt/blob/44fcacba846a6cdf33e1475fc8413f6ae49d1fe4/packages/nuxt/src/app/composables/ssr.ts#L8-L10). 

This forces the consumers to add a defensive layer if they want to be type-safe. Below is an example of such a layer.

```ts
const event = useRequestEvent() as H3Event | undefined

if (event) {
  // ...
}
```

Such boilerplate clutters the consumer code, and requires the `H3Event` type to be imported. Needless to say that it's also extremely easy to forget about such a defensive layer, and introduce type errors at runtime.

### Additional context

/

### Logs

```shell-script
/
```

**Comment by SilentSobs** [comment]
Hello! I'm eager to contribute to this issue, and I believe I've identified a potential fix. However, I need to validate it. As a newcomer to GitHub's contribution platform, I've encountered some challenges.

So, here's what's happening: when we create a new project, it fetches packages from GitHub, right? Now, let's say I have npm rights. In the npm local directory, those packages are available, and it forms the basis for the new project.

Here's where things get interesting. I forked your repository and made some changes in my forked repository. Now, when I try to create a project, I want it to use the base packages from my forked repository instead of the original one. I've been attempting this quite a bit, but it's not working as expected.

So I think this code work But I am not able to test this 

here's the code :- 
```
export function useRequestEvent (nuxtApp: NuxtApp = useNuxtApp()): H3Event | undefined {
  return nuxtApp.ssrContext?.event as H3Event | undefined;
}
```
This change helps TypeScript understand that, on the client side, the function might not always have a valid H3Event, and it could be undefined.

**Comment by pi0** [comment]
I agree that types could be more clear about this behavior 💯 

In the meantime, do you mind to explain some of your usecases that involves accessing `useRequestEvent()` in universal codes? (mainly to see how we can reduce dependency of it)

**Comment by SilentSobs** [comment]
used for accessing server-side events on the client side.

```
const randomNumber = Math.floor(Math.random() * 100);
context.ssrContext.nuxt = {
  event: {
    type: 'randomNumberEvent',
    data: { randomNumber }
  }
};
```
client side 
```
const event = useRequestEvent();

if (event?.type === 'randomNumberEvent') {
  randomServerNumber.value = event.data.randomNumber;
}

```

With the modified function (useRequestEvent(): H3Event | undefined), TypeScript allows you to handle the possibility of undefined directly without the need for explicit if-else checks.

```
export function useRequestEvent(nuxtApp: NuxtApp = useNuxtApp()): H3Event | undefined {
  return nuxtApp.ssrContext?.event as H3Event | undefined;
}
```

useRequestEvent is explicitly stated as H3Event | undefined, that the function may return undefined

**Comment by antoinerey** [comment]
In our case, we use it inside a composable that may be executed on both server and client sides. The composable is responsible for tracing a callback via the `dd-trace` library. The code roughly looks like this:

```ts
function useTrace(name: string, callback: Function) {
  const event = useRequestEvent() as H3Event | undefined

  if (event) {
    return event.tracer.trace(name, callback)
  }

  return callback()
}
```

If we're not defensive enough, TypeScript thinks that `event` is always defined, and thus does not prevent us from calling `event.tracer` client-side.

**Comment by SilentSobs** [comment]
changes i made aims to explicitly declare the return type as H3Event | undefined,


```
export function useRequestEvent(nuxtApp: NuxtApp = useNuxtApp()): H3Event | undefined {
  return nuxtApp.ssrContext?.event as H3Event | undefined;
}
```

 which addresses concerns related to handling undefined on the client side. Could you please confirm if this modification is considered sufficient for a pull request?

**Comment by pi0** [comment]
Thanks for sharing your insights. Issue of type inconsistency is resolved with https://github.com/nuxt/nuxt/pull/25480 at least.

Regarding your cases @SilentSobs, I would say, we could potentially expose a `useNuxtSSRContext()` utility to avoid depending on low-level event context. wdyt @danielroe ?

@antoinerey I would highly recommend that you use `event.context`. Top level properties of event object should not be set.

**Comment by antoinerey** [comment]
Yes, sorry. It's already the case but I wrongly reported the code here. 😅
