### ISSUE TITLE
Plugins are triggered and previous context is lost on error shown

### ISSUE THREAD

**Issue by daniluk4000** [nuxt/nuxt#25447]
### Environment

- Operating System: Linux
- Node Version:     v20.10.0
- Nuxt Version:     3.9.3
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  @pinia/nuxt@0.5.1
- Build Modules:    -

### Reproduction

https://github.com/daniluk4000/nuxt-error-reset-context

### Describe the bug

After showError is used, it almost feels like whole page is reloaded:
- All previous pinia data is lost
- All plugins are executed once again

### Additional context

God please tell me this is not intended. This leads to duplicate requests and logs lose on our side.

### Logs

```shell-script
Inside console

Triggered //Initial plugin trigger
bar //Initial pinia data has been set
Triggered //Second plugin trigger after showError. Pinia data will be lost then
```

**Comment by daniluk4000** [comment]
Basically, any thrown error inside `defineRenderHandler` leads to this.

**Comment by daniluk4000** [comment]
As I've trugged deep into the code, the problem is probably that we can't rerender our app if any error happenened. 

The only thing that could delay some component from rendering is `onServerPrefetch`, but we can't wait inside of it forever since we can't know if remaining app has been rendered or not.

Solution could be is to listen for "@resolve" hook for that, but this is currently impossible due to https://github.com/vuejs/core/pull/8555 not merged. 

Also solution could be to render app twice (don't use Nitro's error handler) and on second render pass all the payload and state to this second render, and that will also skip mounting any plugins twice there.

**Comment by danielroe** [comment]
Yes, that is the case (and intentional). To render an error page, we render the app a second time, but just the error page and not `app.vue`.

Plugins might do more things than set payload/state, such as inject helper functions. So we _do_ need to rerun them. You can add your own logic to avoid rerunning logic. You can check in your plugins if `useError().value` is set.

**Comment by daniluk4000** [comment]
> Yes, that is the case (and intentional). To render an error page, we render the app a second time, but just the error page and not `app.vue`.
> 
> Plugins might do more things than set payload/state, such as inject helper functions. So we _do_ need to rerun them. You can add your own logic to avoid rerunning logic. You can check in your plugins if `useError().value` is set.

Yes I could, but sadly pinia context is lost as well :(

**Comment by daniluk4000** [comment]
@danielroe do you think this worth trying to solve when `@resolve` will be supported on SSR? Basically, that's how it worked in Nuxt 2 (I know that there was totally different logic).

If at least state (including useState & pinia) would be passed to this reloaded context, it wouldn't be such a problem.
