### ISSUE TITLE
On production build, CSS does not get inlined in SSR response in some cases when using `defineAsyncComponent`

### ISSUE THREAD

**Issue by tibineagu** [nuxt/nuxt#25451]
### Environment

```
Working directory: /home/projects/nuxt-starter-ta6mqt
Nuxt project info:

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.9.3
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Reproduction

[Reproduction repository](https://stackblitz.com/edit/nuxt-starter-ta6mqt)

- run `npm run build && npm run preview`
- access the page and look at the HTML response
- notice that the styles for both `layout.vue` and `AsyncCompParent.vue` are NOT inlined in the response

### Describe the bug

There seems to be an issue when using a common mapping object to create associations to various components that need to be loaded dynamically.

This is a rather complex system so please follow along carefully.
- we have an enum in `@/utils/name-map.js`
- this enum is used in a parent component (`AsyncCompParent`) that will decide which other component to render based on an association map
    - these child components (`ChildComponentA`) are declared using `defineAsyncComponent` in order to achieve code splitting
- The async component (`ChildComponentA`) uses a composable (`useSayMyName.js`) that, in turn, ALSO imports the enum

The setup above will cause the following:
- no styles declared in `AsyncCompParent` are inlined in the SSR HTML response
- no styles in `layout.vue` (which is the _parent_ of `AsyncCompParent`) are inlined in the SSR HTML response

#### Expected behaviour
The styles for `layout.vue` and `AsyncCompParent.vue` should be inlined in the SSR HTML response, since these components are always present on the page and rendered at load time.

### Additional context

The repo above is an extremely simplified version of code we ported from a Nuxt 2 app, where it functions as expected.

More background / things we discovered:
- if, in any of the two files that import from `@/utils/name-map`, we instead redeclare a local copy of that constant, the build goes ahead as expected and the CSS is inlined (see comment in the code)
- if we don't use `defineAsycnComponent`, and just use plain a `import` statement for `ChildComponentA`, the build goes ahead as expected
- if we don't import `useSayMyName` in `ChildComponentA`, and instead import the enum directly there, the build goes ahead as expected

None of the options presented above are valid alternatives for us given the complexity of our code and, to be fair, I don't think we are doing any illegal coding patterns - this feels like a very common use-case for example when you want to trigger various flows from the same component and don't want the flow code to be included in the bundle since they might never be triggered.

**Comment by danielroe** [comment]
resolved in https://github.com/nuxt/nuxt/pull/25455
