### ISSUE TITLE
NPM Audit: Prototype Pollution in lodash

### ISSUE THREAD

**Issue by tsega** [nuxt/nuxt#25457]
### Environment

- Operating System: Darwin
- Node Version:     v20.10.0
- Nuxt Version:     3.9.3
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      ssr, devtools, modules, googleFonts
- Runtime Modules:  @nuxtjs/tailwindcss@6.11.1, @nuxtjs/google-fonts@3.1.3, nuxt-lucide-icons@1.0.3, nuxt3-leaflet@1.0.12, @vee-validate/nuxt@4.12.4, nuxt-primevue@0.2.2
- Build Modules:    -

### Reproduction

npm audit report

### Describe the bug

Nuxt v3.9.3 has a dependency on lodash.pick >= 4.0.0 that has a high severity Prototype Pollution vulnerability.

```
# npm audit report

lodash.pick  >=4.0.0
Severity: high
Prototype Pollution in lodash - https://github.com/advisories/GHSA-p6mc-m468-83gw
fix available via `npm audit fix --force`
Will install nuxt@3.8.2, which is a breaking change
node_modules/lodash.pick
  vite-plugin-checker  >=0.2.0-beta.0
  Depends on vulnerable versions of lodash.pick
  node_modules/vite-plugin-checker
    @nuxt/vite-builder  >=3.0.0-rc.0
    Depends on vulnerable versions of vite
    Depends on vulnerable versions of vite-plugin-checker
    node_modules/@nuxt/vite-builder
      nuxt  >=3.9.0
      Depends on vulnerable versions of @nuxt/devtools
      Depends on vulnerable versions of @nuxt/vite-builder
      node_modules/nuxt
        @nuxt/devtools  >=1.0.7
        Depends on vulnerable versions of @nuxt/devtools-kit
        Depends on vulnerable versions of nuxt
        node_modules/@nuxt/devtools
        @nuxt/devtools-kit  >=1.0.7
        Depends on vulnerable versions of nuxt
        node_modules/@nuxt/devtools-kit
```

**Comment by rolandtannous** [comment]
I am also having the same problem and haven't been able to figure it out yet.

**Comment by danielroe** [comment]
This doesn't seem to be an issue. User input is not exposed to `lodash.pick` as it is only run in development mode by `vite-plugin-checker`.

**Comment by Peggy535** [comment]
Same here as well - linked comment/log: https://github.com/nuxt/nuxt/issues/25458#issuecomment-1914107710

-```
 lodash.pick  >=4.0.0
- Severity: high
- Prototype Pollution in lodash - https://github.com/advisories/GHSA-p6mc-m468-83gw
- fix available via npm audit fix --force
- Will install nuxt@3.8.2, which is a breaking change
- node_modules/lodash.pick
-     vite-plugin-checker  >=0.2.0-beta.0
-     Depends on vulnerable versions of lodash.pick
-     node_modules/vite-plugin-checker
-         @nuxt/vite-builder  >=3.0.0-rc.0
-         Depends on vulnerable versions of vite
-         Depends on vulnerable versions of vite-plugin-checker
-         node_modules/@nuxt/vite-builder
-             nuxt  >=3.9.0
-             Depends on vulnerable versions of @nuxt/devtools
-             Depends on vulnerable versions of @nuxt/vite-builder
-             node_modules/nuxt
-                 @nuxt/devtools  >=1.0.7
-                 Depends on vulnerable versions of @nuxt/devtools-kit
-                 Depends on vulnerable versions of nuxt
-                 node_modules/@nuxt/devtools
-                     @nuxt/devtools-kit  >=1.0.7
-                     Depends on vulnerable versions of nuxt
-                     node_modules/@nuxt/devtools-kit
- 
- vite  5.0.0 - 5.0.11
- Severity: high
- Vite dev server option server.fs.deny can be bypassed when hosted on case-insensitive filesystem - https://github.com/advisories/GHSA-c24v-8rfc-w8vw
- fix available via "npm audit fix --force"
- Will install nuxt@3.8.2, which is a breaking change
- node_modules/@nuxt/vite-builder/node_modules/vite
```

**Comment by manniL** [comment]
@rolandtannous correct.

**Comment by JakiChen** [comment]
if you use `npm create vue@latest` create a vue project, You will get a vue project powered by vite, but without any of the vite-related security vulnerabilities. All reason to suspect that the nuxt team is just lazy or unwilling to make changes.
