### ISSUE TITLE
Nuxt's module "defineNuxtConfig" type error

### ISSUE THREAD

**Issue by TutorFx** [nuxt/nuxt#25456]
### Environment

- Operating System: Windows_NT
- Node Version:     v21.6.1
- Nuxt Version:     3.9.3
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://github.com/TutorFx/nuxt-zod/tree/type-bug-reproduction

### Describe the bug

After creating the module using npx nuxi init -t module _project name_, I noticed that some typings were missing.

```ts
import MyModule from '../../../src/module'

export default defineNuxtConfig({
//              ^^^^^^^^^^^^^^^
// Cannot find name 'defineNuxtConfig'. Did you mean 'defineNitroConfig'?ts(2552)
// nitro.da3b833a.d.ts(867, 11): 'defineNitroConfig' is declared here.
  modules: [
    MyModule
  ]
})

```
```ts
import { defineNuxtModule, addPlugin, createResolver } from '@nuxt/kit'

// Module options TypeScript interface definition
export interface ModuleOptions {}

export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: 'my-module',
    configKey: 'myModule'
  },
  // Default configuration options of the Nuxt module
  defaults: {},
  setup (options, nuxt) {
    const resolver = createResolver(import.meta.url)
//                                 ^^^^^^^^^^
//       The 'import.meta' meta-property is only allowed when the '--module'
//       option is 'es2020', 'es2022', 'esnext', 'system', 'node16', 
//       or 'nodenext'.ts(1343)

    // Do not add the extension since the `.ts` will be transpiled to `.mjs` after `npm run prepack`
    addPlugin(resolver.resolve('./runtime/plugin'))
  }
})
```

### Additional context

Some things I tried to work around the problem:

- npm ci
- enable the "Takeover" mode
- delete the node_modules
- update the node to v21.6.1

**Comment by markthree** [comment]
@TutorFx 
A temporary solution is to add the following script to your `package.json`

```json
{
  "scripts": {
      "prepare": "nuxt prepare",
  }
}
```

Then remove your `yarn.lock` and re-execute `yarn`, and finally restart your editor to get the type hints

**Comment by danielroe** [comment]
You need to run the `dev:prepare` script.

https://github.com/nuxt/starter/blob/module/README.md#development
