### ISSUE TITLE
Throwing error on server route triggers vue router warning and error

### ISSUE THREAD

**Issue by Aietes** [nuxt/nuxt#25492]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.9.3
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, vue
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-em1yu6?file=README.md

Open in new tab and call `/api/test`

### Describe the bug

When an error is thrown in an api route, vue router tries to resolve the api path and throws an exception.

<img width="813" alt="Screenshot 2024-01-29 at 17 01 47" src="https://github.com/nuxt/nuxt/assets/5823770/eacf5803-3ed3-406f-8ce3-eefb55b4ccdf">

The 500 error from the api handler is expected, as it has been thrown. The additional warning from vue router and the error from vue router should not occur, as this is a server route and handler.

**Comment by danielroe** [comment]
This should be resolved when `h3` is next released via https://github.com/unjs/h3/pull/646.

**Comment by manniL** [comment]
As note for a workaround, until the release lands: You can set your headers manually to accept json:

```ts
useFetch(`/api/...`, {
  headers: {
    accept: 'application/json'
  }
});
```
