### ISSUE TITLE
Parent page rendered before asyncData finished in child route

### ISSUE THREAD

**Issue by tibineagu** [nuxt/nuxt#25491]
### Environment

```
Working directory: /home/projects/nuxt-starter-bb8vfa
Nuxt project info: 

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.9.3
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  @pinia/nuxt@0.5.1
- Build Modules:    -
------------------------------
```

### Reproduction

[Nuxt 3 minimal reproduction](https://stackblitz.com/edit/nuxt-starter-bb8vfa)

To reproduce
- navigate to `/any-parent/any-child` using hard navigation
- notice that the value for "URL in parent" only appears after page load, whereas the "URL in child" is correctly populated from server rendering
- there is also a Hydration Mismatch warning about the text being different

For comparison, please see basically the same folder structure [running on Nuxt 2](https://stackblitz.com/edit/github-nszxhn)
- with Nuxt 2, both "URL in parent" and "URL in child" are correctly populated from SSR

### Describe the bug

It appears that in Nuxt 3, parent components are server-rendered without waiting for the async data on child routes to complete.

The easiest way to reproduce this is in cases where the parent and the child share a store, but the child is the one triggering the action that retrieves data in the store. The child's rendering will wait until the action has finalized (because it's got the `useAsyncData` logic), but the parent goes ahead and tries to render with the "undefined" data from the store.

This didn't happen in Nuxt 2, as you can see from the example repo, where it looks like both the parent and the child get rendered only after the `asyncData` in child has completed.

### Additional context

While this isn't necessarily implemented according to "best practices", we found that on our Nuxt 2 codebase this saves us having to perform additional API requests, therefore reducing load on the API servers and also creating a single point of failure for the data hydration of both the child page and parent page.

Furthermore, if both the parent page and the child page need to use the same data set, as it currently stands with Nuxt 3, it's not safe to only dispatch the data action on the parent, because that would expose the child to the same "missing data" effect.

Right now this is an issue we are facing when migrating our codebase to Nuxt 3, and I'd be happy to provide more context if needed.

**Comment by danielroe** [comment]
This is an issue with rendering logic. Here's how it works.

1. server renders `[parent]` - no image URL is present
2. server renders `[child]`
3. child calls `getImage` and now the image URL is present
4. page gets sent to client
5. client renders `[parent]` - image URL is present as child added it in step 3
6. hydration mismatch and flicker as the URL appears

There is no reactivity on the server and it's too 'late' to rerender the parent after step 3. You should update your logic so you're not reliant on what children of a component do in order to render the parent.

**Comment by manniL** [comment]
Linking https://github.com/nuxt/nuxt/issues/19258 as being the same issue

**Comment by manniL** [comment]
> If the async request for the parent takes, say, 50ms, and the one for the child route takes 60ms, the total time waiting for data is 110ms, whereas with parallelization it would only be 60ms.

For now! That's until https://github.com/nuxt/nuxt/pull/22301 is resolved 👍
