### ISSUE TITLE
useState composables return default value, instead of actual value in plugins

### ISSUE THREAD

**Issue by TheDutchCoder** [nuxt/nuxt#25519]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.10.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-1dmzwk?file=plugins%2FmyPlugin.ts

### Describe the bug

When using the [Shared State](https://nuxt.com/docs/getting-started/state-management#shared-state) strategy, the composables defined always return the default value in plugins, instead of the actual value.

When setting the value in middleware, the plugin keeps referring to the default value instead of the current value.

Maybe this isn't a bug and works as "intended", but the docs suggest that `useState` is the way to share data between server and client.

it's important to note that _other_ things (like pages) use the current value correctly, it's only plugins that don't.

### Additional context

I'm trying to store a cookie value as `useState`, so that I can reference that instead of having to use `useCookie`, but setting the value from middleware doesn't change the value the plugin uses.

**Comment by danielroe** [comment]
I'll check this when I'm back at my computer but the first key thing is that plugins all run before middleware. Then middleware run.

So I would expect that in the ssr logs we'd get the initial value from the plugin, but in the browser the plugin would show the set value. If this isn't the behaviour, it's a bug.

**Comment by TheDutchCoder** [comment]
Hmmm okay, that's problematic in the sense that we handle session/cookie stuff in middleware (where it belongs in my opinion) and want to access the values set there in plugins that are used in the app.

Maybe one strategy would be to move the session stuff to a plugin? That just feels odd...

**Comment by danielroe** [comment]
The plugins run first in case they need to add middleware.

**Comment by TheDutchCoder** [comment]
Ok in that case I might need to move the session logic to a plugin. Thanks!
