### ISSUE TITLE
Pre-transform error: Failed to parse source for import analysis because the content contains invalid JS syntax

### ISSUE THREAD

**Issue by daniluk4000** [nuxt/nuxt#25513]
### Environment

- Operating System: Linux
- Node Version:     v20.10.0
- Nuxt Version:     3.10.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://github.com/daniluk4000/nuxt-dynamic-routes-bug

### Describe the bug

Basically, manual meta when initializing route via hook doesn't work anymore and leads to fatal error

### Additional context

![image](https://github.com/nuxt/nuxt/assets/10450717/d5045438-dde0-4f06-8607-c6bfa25c5df4)

### Logs

```shell-script
ERROR  Pre-transform error: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.

[vite-node] [plugin:vite:import-analysis] [VITE_ERROR] virtual:nuxt:./.nuxt/routes.mjs:43:3
```

**Comment by BobbieGoede** [comment]
Sorry for introducing this bug! #25515 should resolve this, hopefully we can add some regression tests for this as well.

As a workaround you can try out enabling [`experimental.scanPageMeta`](https://nuxt.com/blog/v3-10#%EF%B8%8F-build-time-route-metadata) as it serializes route meta in a different way which bypasses the bug.

**Comment by daniluk4000** [comment]
> Sorry for introducing this bug! #25515 should resolve this, hopefully we can add some regression tests for this as well.
> 
> As a workaround you can try out enabling [`experimental.scanPageMeta`](https://nuxt.com/blog/v3-10#%EF%B8%8F-build-time-route-metadata) as it serializes route meta in a different way which bypasses the bug.

No worries! I should have tried that before I rewrote everything to definePageMeta 😂
