### ISSUE TITLE
[ 6 high severity vulnerabilities ] 

### ISSUE THREAD

**Issue by JakiChen** [nuxt/nuxt#25526]
### Environment

1. **macOS**: 11.7.10
2. **npm**: 10.2.3
3. **node**: v20.10.0
4. **nuxt**: 3.9.3 ~ 3.10.0

### Reproduction

When you install any development dependency package through npm.

### Describe the bug

6 **high** severity vulnerabilities. fix available via `npm audit fix --force` will install nuxt@2.17.3 ~

### Additional context

<img width="829" alt="截屏2024-01-31 18 55 42" src="https://github.com/nuxt/nuxt/assets/3423524/544f93f9-70cd-4cdf-ac19-3db26e4a4bab">

**Comment by JakiChen** [comment]
https://github.com/nuxt/nuxt/issues/25526 —— I would like to ask if there are any plans to fix these vulnerabilities. We have been waiting for several versions.

**Comment by danielroe** [comment]
This is not a vulnerability in Nuxt.

See https://github.com/nuxt/nuxt/issues/25457#issuecomment-1913337934.
