### ISSUE TITLE
Log the whole file when a transformation issue happens

### ISSUE THREAD

**Issue by huang-julien** [nuxt/nuxt#25525]
### Describe the feature

related to https://github.com/nuxt/nuxt/issues/25513

When a transform issue happens within a virtual file, it's almost impossible to get the cause of the issue. We should fidn a way to provide a log of the whole content of the file or allow the user to acces to the virtual file

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by amandesai01** [comment]
Let me take this up.

**Comment by amandesai01** [comment]
I tried to analyse code but wasn't able to find a proper fix / entrypoint. Can I get some pointers?

**Comment by huang-julien** [comment]
Hey :wave: I haven't looked at how to do it. But you should try to look at how to catch pre-transform errors and how to send it to the dev error page; It should be  `packages/nuxt/src/core/runtime/nitro/error-dev.ts`

**Comment by zen0dev** [comment]
This is much needed. Can't figure out shit. How are devs devving?
