### ISSUE TITLE
module resolution

### ISSUE THREAD

**Issue by saeedkgr** [nuxt/nuxt#25529]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.11.0
- Nuxt Version:     3.10.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      ssr, imports, generate, nitro, css, extends, app, runtimeConfig, vite, devtools, typescript, experimental 
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

clone the repository and run Yarn

### Describe the bug

@danielcroe
after running npx nuxi upgrade --force (or --no-force) every thing works ok.
but after commit changes to yarn.lock and package.json when any other developer pull (or clone the repository) and run Yarn the following error appears:

yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
warning Pattern ["strip-ansi@^6.0.1"] is trying to unpack in the same destination "C:\\Users\\saeed\\AppData\\Local\\Yarn\\Cache\\v6\\npm-strip-ansi-cjs-6.0.1-9e26c63d30f53443e9489495b2105d37b67a85d9-integrity\\node_modules\\strip-ansi-cjs" as pattern ["strip-ansi-cjs@npm:strip-ansi@^6.0.1"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["string-width@^4.1.0"] is trying to unpack in the same destination "C:\\Users\\saeed\\AppData\\Local\\Yarn\\Cache\\v6\\npm-string-width-cjs-4.2.3-269c7117d27b05ad2e536830a8ec895ef9c6d010-integrity\\node_modules\\string-width-cjs" as pattern ["string-width-cjs@npm:string-width@^4.2.0"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["strip-ansi@^6.0.0"] is trying to unpack in the same destination "C:\\Users\\saeed\\AppData\\Local\\Yarn\\Cache\\v6\\npm-strip-ansi-cjs-6.0.1-9e26c63d30f53443e9489495b2105d37b67a85d9-integrity\\node_modules\\strip-ansi-cjs" as pattern ["strip-ansi-cjs@npm:strip-ansi@^6.0.1"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["string-width@^4.2.3"] is trying to unpack in the same destination "C:\\Users\\saeed\\AppData\\Local\\Yarn\\Cache\\v6\\npm-string-width-cjs-4.2.3-269c7117d27b05ad2e536830a8ec895ef9c6d010-integrity\\node_modules\\string-width-cjs" as pattern ["string-width-cjs@npm:string-width@^4.2.0"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["string-width@^4.2.0"] is trying to unpack in the same destination "C:\\Users\\saeed\\AppData\\Local\\Yarn\\Cache\\v6\\npm-string-width-cjs-4.2.3-269c7117d27b05ad2e536830a8ec895ef9c6d010-integrity\\node_modules\\string-width-cjs" as pattern ["string-width-cjs@npm:string-width@^4.2.0"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["wrap-ansi@^7.0.0"] is trying to unpack in the same destination "C:\\Users\\saeed\\AppData\\Local\\Yarn\\Cache\\v6\\npm-wrap-ansi-cjs-7.0.0-67e145cff510a6a6984bdf1152911d69d2eb9e43-integrity\\node_modules\\wrap-ansi-cjs" as pattern ["wrap-ansi-cjs@npm:wrap-ansi@^7.0.0"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["string-width@^1.0.2 || 2 || 3 || 4"] is trying to unpack in the same destination "C:\\Users\\saeed\\AppData\\Local\\Yarn\\Cache\\v6\\npm-string-width-cjs-4.2.3-269c7117d27b05ad2e536830a8ec895ef9c6d010-integrity\\node_modules\\string-width-cjs" as pattern ["string-width-cjs@npm:string-width@^4.2.0"]. This could result in non-deterministic behavior, skipping.
warning vscode-languageclient@7.0.0: The engine "vscode" appears to be invalid.
[3/4] Linking dependencies...
warning " > @nuxt/devtools@1.0.8" has unmet peer dependency "vite@*".
warning "@nuxt/devtools > @nuxt/devtools-kit@1.0.8" has unmet peer dependency "vite@*".
warning "@nuxt/devtools > vite-plugin-inspect@0.8.3" has unmet peer dependency "vite@^3.1.0 || ^4.0.0 || ^5.0.0-0".
warning "@nuxt/devtools > vite-plugin-vue-inspector@4.0.2" has unmet peer dependency "vite@^3.0.0-0 || ^4.0.0-0 || ^5.0.0-0".
warning " > postcss-custom-properties@13.3.4" has unmet peer dependency "postcss@^8.4".
[4/4] Building fresh packages...
$ nuxt prepare

[3:38:56 PM]  ERROR  require() of ES Module P:\source\test\app\node_modules\string-width\index.js from P:\source\test\app\node_modules\wide-align\align.js not supported.
Instead change the require of index.js in P:\source\test\app\node_modules\wide-align\align.js to a dynamic import() which is available in all CommonJS modules.

  Instead change the require of index.js in node_modules\wide-align\align.js to a dynamic import() which is available in all CommonJS modules.
  at Object.<anonymous> (node_modules\wide-align\align.js:2:19)

[3:38:56 PM]  ERROR  require() of ES Module P:\source\test\app\node_modules\string-width\index.js from P:\source\test\app\node_modules\wide-align\align.js not supported.
Instead change the require of index.js in P:\source\test\app\node_modules\wide-align\align.js to a dynamic import() which is available in all CommonJS modules.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

### Additional context

also we tried npm and pnpm , nothing changed.
if each system runs "npx nuxi upgrade --force" it works (and nothing changes in newly created yarn.lock)
but we can't deploy it to cloud (for example cloudflare)

**Comment by saeedkgr** [comment]
@danielroe

**Comment by danielroe** [comment]
Please do not ping maintainers when you create an issue.

This is a bug in yarn, not Nuxt. See https://github.com/search?q=strip-ansi+string-width&type=issues.

[This comment](https://github.com/storybookjs/storybook/issues/22431#issuecomment-1630086092) explains the issue and provides a workaround.

**Comment by saeedkgr** [comment]
thank you, it solved
sorry to bother you. the reason I mentioned was this link (https://nuxt.com/blog/v3-10#bundler-module-resolution) that I thought this problem was a module resolution problem.
