### ISSUE TITLE
Fetch.mjs not automatically generating by Nuxt 3 when running npm run dev

### ISSUE THREAD

**Issue by bennyrubanov** [nuxt/nuxt#25521]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.7.0`
- Nuxt Version:     `3.10.0`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `npm@10.4.0`
- Builder:          `-`
- User Config:      `devtools`, `css`, `build`, `modules`, `primevue`, `googleFonts`, `runtimeConfig`, `tailwindcss`, `ssr`, `app`, `vue`, `postcss`, `alias`
- Runtime Modules:  `@nuxtjs/google-fonts@3.1.3`, `@nuxt/ui@2.13.0`, `nuxt-primevue@0.2.2`
- Build Modules:    `-`

### Reproduction

I believe minimal reproduction not necessary (let me know if not!)

### Describe the bug

Receiving the following error despite updating to Nuxt 3 and checking package and nuxt.config.ts files. Have attempted deleting node_modules and .nuxt directories

 Failed to load url /.nuxt/fetch.mjs (resolved id: /Users/bennyrubanov/pinit_frontend/.nuxt/fetch.mjs) in /Users/bennyrubanov/pinit_frontend/node_modules/nuxt/dist/app/entry.js. Does the file exist?

**Comment by tobychidi** [comment]
Could it be why this is happening?

```
[9:21:41 AM]  ERROR  [worker reload] [worker init] Cannot find module 'C:\Users\tobychidi\Documents\GitHub\kaycee\Rotabliss\node_modules\.pnpm\@auth+core@0.24.0_nodemailer@6.9.8\node_modules\@auth\core\providers\email' imported from C:\Users\tobychidi\Documents\GitHub\kaycee\Rotabliss\node_modules\.pnpm\@auth+core@0.24.0_nodemailer@6.9.8\node_modules\@auth\core\providers\nodemailer.js

  at finalizeResolution (node:internal/modules/esm/resolve:264:11)
  at moduleResolve (node:internal/modules/esm/resolve:917:10)
  at defaultResolve (node:internal/modules/esm/resolve:1130:11)
  at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
  at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
  at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
  at link (node:internal/modules/esm/module_job:84:36)
```

**Comment by bennyrubanov** [comment]
see reproduction here: https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz?file=.nuxt%2Ftsconfig.server.json

@manniL

**Comment by manniL** [comment]
@bennyrubanov 

This seems to work fine in the sandbox? 🤔 
![image](https://github.com/nuxt/nuxt/assets/640208/f01db798-597e-41a6-ab8e-f06248ad5b0c)

**Comment by bennyrubanov** [comment]
I'm a bit confused - I tried opening my own link and it took me back to the starting version of the sandbox. I must have shared the wrong link??

What's the best way to import my .nuxt directory into the sandbox? I was able to recreate the issue in the sandbox this morning just by copying my .nuxt directory and some other files to match what I had in my repo.

**Comment by manniL** [comment]
@bennyrubanov providing a GitHub repo and link it here is fine too ☺️

**Comment by bennyrubanov** [comment]
Can't, private 😭 any other suggestions 😅

**Comment by manniL** [comment]
I mean, you can just add your .nuxt folder (+ use a basic app) there :)

Any kind of reproduction is needed to investigate

**Comment by bennyrubanov** [comment]
Issue has been resolved (with help from a mentor)! I was using the deprecated nuxt3 package. Oops!!

Thanks regardless for the help @manniL . Will work on my reproduction skills for the next one ;)

**Comment by manniL** [comment]
Glad to here it was resolved 👏

**Comment by m2sahin** [comment]
@bennyrubanov I have the same problem and I haven't been able to solve it for three days. How did you overcome this?

**Comment by bennyrubanov** [comment]
I had added "nuxt3" as a dependency in the package.json, which caused the issue because the nuxt3 package is deprecated:
https://www.npmjs.com/package/nuxt3

I removed the package, cleared the node modules again, and reloaded - that fixed it!

**Comment by mklueh** [comment]
Facing the same problem now with Nuxt 3.11.2. Not sure what package is causing it

**Comment by phenomenal-hardy** [comment]
having exact same error on Nuxt 3.11.2

Pre-transform error: Missing "#internal/nuxt/paths" specifier in "nuxt" package

**Comment by manniL** [comment]
@JhumanJ feel free to create a new issue then with a reproduction 👍

**Comment by mklueh** [comment]
Running into this issue again and I wish the logs could give more hints about the package that might cause it, as it is a huge time waste to find out what is going on

**Comment by PatrickSchutte** [comment]
I had the exact same problem, I was working on my dev machine, all fine, and when I pulled it into the test server, I ran into this problem, deleting the node_modules, deduping did not help.
The solution for me was to run the proper **npx nuxi upgrade** on the test server, and all worked fine.
