### ISSUE TITLE
app.viewTransition does not use the value from experimental.viewTransition

### ISSUE THREAD

**Issue by troyciesco** [nuxt/nuxt#25547]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.10.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, experimental
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-xbgnk8-nxglfy?file=nuxt.config.ts

### Describe the bug

If I'm reading the [release notes](https://nuxt.com/blog/v3-10#granular-view-transitions-support) and PR https://github.com/nuxt/nuxt/pull/25264 correctly, the value for `app.viewTransition` should automatically use the value set on `experimental.viewTransition`. 

That doesn't seem to be the case - to get viewTransitions to work now, I have to manually set `app.viewTransition` to true.

In `packages/schema/src/config/app.ts` on [L159](https://github.com/nuxt/nuxt/blob/main/packages/schema/src/config/app.ts#L159), changing this:
```
    viewTransition: {
      $resolve: async (val, get) => val ?? await get('experimental.viewTransition') ?? false
    },
```

To this seems to work:
```
viewTransition: {
  $resolve: async (val, get) => val ?? await (get('experimental') as Promise<Record<string, any>>).then(
    (e) => e?.viewTransition
  ) ?? false
},
```

Which I mimicked from the `experiemental.ts` file [here](https://github.com/nuxt/nuxt/blob/main/packages/schema/src/config/experimental.ts#L22).

However, I see `// TODO: remove in v3.10` above every implementation of that pattern, so idk if there's a better way to solve it (I'm not too familiar with untyped and defineUntypedSchema).

I'm happy to work on it regardless - I can have a PR ready shortly if the pattern I listed above makes sense.

**Comment by danielroe** [comment]
Yes, I think your solution is right 👍
