### ISSUE TITLE
window.onload not running

### ISSUE THREAD

**Issue by WooHoo-Wu** [nuxt/nuxt#25554]
### Environment

3.x

### Reproduction

pro

### Describe the bug

![image](https://github.com/nuxt/nuxt/assets/52190592/6146221b-d71c-431f-aa67-f9853fc29e28)

**Comment by mkierdev** [comment]
Issue lacks any details, however this may resolve your problem:
https://nuxt.com/docs/api/utils/on-nuxt-ready

I stumbled accross similar problem when I had to update something after page was fully loaded and onNuxtReady fulfilled my use-case

**Comment by Barbapapazes** [comment]
Why do you need onload in a mounted? When mounted is executed, the page is already loaded.

**Comment by WooHoo-Wu** [comment]
When I inserted code into the script, I used onload. Through debugging, I found that onload was not executed. The picture above is just an example I made simply.

**Comment by Barbapapazes** [comment]
> When I inserted code into the script, I used onload. Through debugging, I found that onload was not executed. The picture above is just an example I made simply.

I think that it's also normal since the hydration is after the page has loaded. What is your use case?

**Comment by danielroe** [comment]
onNuxtReady is the solution here. This is not a bug; the code that registers the event listener is running after that event in the browser.
