### ISSUE TITLE
middleware not execute

### ISSUE THREAD

**Issue by nicdnepr** [nuxt/nuxt#25565]
I have site with vue+nuxt+pm2
I'm new on vue+nuxt
I want such condition-if logged user open page `/login` then redirect to cabinet
I put to folder `middleware` file `login.js` with such content
```
export default function ({ route, store, redirect }) {
	console.log('login')
  if (/login/.test(route.path) && store.getters['auth/isAuthorized']) {
    redirect('/cabinet')
  }
}
```
then I put such code to file `nuxt.config.js`
```
module.exports = {  
router: {
    middleware: ['login']
  },
  mode: 'universal',
  head,
  css,
  modules,
  env,
  router,
  plugins,
  generate,
  build,
  render,
  serverMiddleware,
  ...options
}
```
then run command pm2 restart id
but the code not execute, even log
what I do wrong?

**Comment by nicdnepr** [comment]
I'm new with vue and nuxt, so its hard for me to Create a Minimal Reproduction
I have working site and I moved it to new server
The main  problem why I created the topic- on new server, when user go to page `/login` after success login, then for some reasons site crush
It's hard for me to debug and find a reason so I desiced to add condition-if user is logged and open page  `/login` then redirect him
i asked chatGPT and it suggest a solution with `middleware` but it's not worked
by the way the version nuxt is `@nuxt/cli v2.9.0`

**Comment by hamedniroumand** [comment]
@nicdnepr Your log may be executed on the server side. see the pm2 logs.
