### ISSUE TITLE
Add import meta for static rendering

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt/nuxt#25566]
### Describe the feature

Hello,

Actually, there is different import meta. One of them is for prerendering. But there is nothing about static when nuxt is generating the website. Pre-render key is not enough specific when site is static since there is a payload generated. 

See https://github.com/nuxt/content/issues/2533

https://nuxt.com/docs/api/advanced/import-meta#runtime-app-properties

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by pi0** [comment]
Modules can use `nuxt.options.static` flag to change their behavior for full-static builds.

**Comment by danielroe** [comment]
The nuxt options are only usable in nuxt/module context but modules can expose whatever they need at runtime.

**Comment by danielroe** [comment]
What would your use case be for this?

**Comment by danielroe** [comment]
Closing as I think this is already implemented. Feel free to add more info later and we can reopen 🙏
