### ISSUE TITLE
My babel.config.js setting will only transpile but not polyfill my nuxt v2 app

### ISSUE THREAD

**Issue by qiulang** [nuxt/nuxt#25561]
### Environment

```
  System:
    OS: macOS 14.1.2
    CPU: (8) arm64 Apple M2
    Memory: 52.88 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.4 - /usr/local/bin/npm
    pnpm: 8.14.0 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 121.0.6167.85
    Safari: 17.1.2
  npmPackages:
    nuxt: ^2.15.8 => 2.17.2
```

### Reproduction

1. yarn create nuxt-app test
2. add my babel.config.js
3. use a package or write some codes that uses es2016+ new api

### Describe the bug

My babel.conig.js setting will only **transpile** but not **polyfill** my nuxt v2 app (using create-nuxt-app to create). I don't now what I miss here because using the same babel.conig.js for my other webpack projects all work well.

```
presets: [
    [
        // '@babel/preset-env',
        '@nuxt/babel-preset-app',
        {
            debug: true,
            targets: {
                chrome: '100',
                ie: '10',
                firefox: '100'
            },
            useBuiltIns: 'usage',
            shippedProposals: true,
            modules: "commonjs",
            corejs: '3.25'
        }
    ]
]
```

For my other webpack project, the only different is I use '@babel/preset-env' instead of '@nuxt/babel-preset-app'.  From the webpack output I can see it will transpile and polyfill my app,

```
// The transpile part

Using targets:
{
  "chrome": "100",
  "firefox": "100",
  "ie": "10",
}

Using modules transform: commonjs

Using plugins:
  proposal-numeric-separator { ie }
  proposal-logical-assignment-operators { ie }
  ...

// The polyfill part

The corejs3 polyfill added the following polyfills:
  es.array.concat { "ie":"10" }
  es.object.to-string { "ie":"10" }
  es.regexp.to-string { "ie":"10" }
  ...

```

But for my nuxt app, I only see the transpile part but no polyfill part and IE 11 can't open the page (I add array.concat code to double confirm this.)

```
@babel/preset-env: DEBUG option                                         
                                                                        
Using targets:
{                                                                       
  "chrome": "100",
  "firefox": "100",
  "ie": "10"
}
                                                                        
Using modules transform: commonjs
                                                                        
Using plugins:
  transform-unicode-sets-regex { chrome < 112, firefox < 116, ie }      
  bugfix/transform-v8-static-class-fields-redefine-readonly { ie }      
  proposal-class-static-block { ie }                                    
  syntax-private-property-in-object                                     
  syntax-class-properties                                               
  proposal-numeric-separator { ie }
  ...
  corejs3: DEBUG option                            
                                                   
Using targets: {
  "chrome": "100",
  "firefox": "100",
  "ie": "10"
}
                                                   
Using polyfills with usage-global method:
regenerator: DEBUG option                          
                                                   
Using targets: {}
```

So is it a bug or what I miss here ?

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
