### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '<' at main.js

### ISSUE THREAD

**Issue by topdevhere623** [nuxt/nuxt#25574]
### Environment

nuxt3 project with unocss

### Reproduction

I don't know how to reproduce this error.

### Describe the bug

Hello!

I'm facing this kind error in Console Dev Tool panel.
My project is Nuxt3. I can not fix this issue.
Please help me out.

![image](https://github.com/nuxt/nuxt/assets/93789798/eaf3edaf-aec4-4c02-96bb-6b84cca25cd4)

![image](https://github.com/nuxt/nuxt/assets/93789798/706707ed-66bf-466b-b3c6-886895b6e6da)

Hope you will not ignore my problem.

Thank you in advance.

**Comment by danielroe** [comment]
I doubt this is coming from Nuxt. Probably something is adding a Js script tag with main.js, but because this doesn't exist in your project it's just getting an HTML page as a response.
