### ISSUE TITLE
navigateTo redirects to external url, without setting external to true

### ISSUE THREAD

**Issue by ahoek** [nuxt/nuxt#25570]
### Environment

- Operating System: Darwin
- Node Version:     v20.10.0
- Nuxt Version:     3.9.3
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.15.0
- Builder:          -
- User Config:      srcDir, app, plugins, components, vite, css, modules, i18n, router, hooks, site, sitemap, build, webpack, gtm, runtimeConfig, nitro, loading, robots, strapi
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.5, vue-recaptcha/nuxt, nuxt-simple-sitemap@4.4.1, @nuxtjs/robots@3.0.0, @nuxtjs/strapi@1.11.0, @vueuse/nuxt@10.7.2, @zadigetvoltaire/nuxt-gtm@0.0.13, nuxt3-vuex-module@1.0.14, nuxt-jsonld@2.0.8
- Build Modules:    -

### Reproduction

Call the following line in middleware
```
navigateTo('//example.com', { redirectCode: 301 });
```

### Describe the bug

When using navigateTo with a url that starts with `//`, I'll get the following warning in the console:

```
[Vue Router warn]: Location "//example.com" resolved to "//example.com". A resolved location cannot start with multiple slashes.
```

But Nuxt will redirect the example.com, which is a security risk.

### Additional context

The code was based given on the solution is this stackoverflow question: https://stackoverflow.com/questions/74261193/nuxt-3-how-to-remove-trailing-slash?newreg=5c6117aa6a6a4d16889cfb39aff372dd

### Logs

```shell-script
[Vue Router warn]: Location "//example.com" resolved to "//example.com". A resolved location cannot start with multiple slashes.
```

**Comment by danielroe** [comment]
A double slash is a protocol relative URL and is an external link, just as if it started with https://.

**Comment by danielroe** [comment]
This seems to be working fine. See https://stackblitz.com/~/edit/github-e7zrnz.

If this isn't working for you, would you provide a reproduction? 🙏

**Comment by ahoek** [comment]
I'm able to reproduce the problem when I'm using an object instead of a string url: 
```
export default defineNuxtRouteMiddleware((to) => {
  if (to.path === '//example.com') {
    // Prevent eternal redirect loop
    return undefined;
  }
  return navigateTo({ path: '//example.com' }, { redirectCode: 301 });
});
```

https://stackblitz.com/c/edit/github-e7zrnz-cuxkrd

When I run via `npm run build && node .output/server/index.mjs`, I'm getting redirected.
