### ISSUE TITLE
Types for `#imports` in server routes are not correct

### ISSUE THREAD

**Issue by paro-paro** [nuxt/nuxt#25571]
### Environment

* stackblitz with nuxt 3.10.0
* same issue is present in 3.9.x

### Reproduction

https://stackblitz.com/edit/github-cebp1w?file=server%2Froutes%2Fhello.ts

### Describe the bug

Hey there!

I have [disabled](https://nuxt.com/docs/guide/concepts/auto-imports#disabling-auto-imports) the auto-import feature from nuxt due to its (in my opinion) excessive implicitness and I have found out that I cannot explicitly import nitro's functions/composables using the `#imports` syntax. 

[Explicit imports](https://nuxt.com/docs/guide/concepts/auto-imports#explicit-imports) work perfectly fine for composables, utils, vue/nuxt API's but not for nitro.

 From the reproduction, It seems that is only importing the value but not the type:
 
 ` [vue-tsc] Module '"#imports"' has no exported member 'defineEventHandler'. `

I have tried `#build/types/nitro-imports` as well with no success: 

`Vue app aliases are not allowed in server runtime. [importing #build/types/nitro-imports from server/routes/test.ts]`

Is this expected behaviour? Any workaround available so I can leverage the `#imports` syntax for nitro as well? Do I have to import them directly from `h3` or `nitropack`?

Any help will be appreciated.

Thanks in advanced

**Comment by danielroe** [comment]
Importing from `#imports` is definitely the correct option. This is a type issue; the Nuxt `#imports` alias is shadowing the Nitro equivalent.

**Comment by paro-paro** [comment]
Thanks a lot for the clarification @danielroe 

Importing from 'h3' until further fix.

**Comment by paro-paro** [comment]
Hi @danielroe 

Sorry to bother... Are there any plans on addressing this issue?

Updated [repro](https://stackblitz.com/edit/github-pccv4h)

**Comment by yxw007** [comment]
> Hi @danielroe
>
> Sorry to bother... Are there any plans on addressing this issue? Sorry to bother... Are there any plans on addressing this issue?
>
> Updated [repro](https://stackblitz.com/edit/github-pccv4h) Updated [repro](https://stackblitz.com/edit/github-pccv4h)

I just used the reproduct you provided. Just upgrade nuxt to 3.12.4. The issue can be closed.
