### ISSUE TITLE
How to mount nuxt app to the body tag without use the "__nuxt" id?

### ISSUE THREAD

**Issue by XiaohCeale** [nuxt/nuxt#25573]
### Describe the feature

I need mount nuxt app to body tag.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by DamianGlowala** [comment]
Here you are:
```
export default defineNuxtConfig({
  app: {
    rootId: false
  }
})
```

**Comment by XiaohCeale** [comment]
This doesn't work.
app shoud mount to "body" tag rather than "body>div"
```
<html>
<head></head>
<body>
    app shoud be in here
    <div>shoutn`t be in here</div>
</body>
<html>
```
---
这不符合预期。
app应该直接在html标签下，而不是html>div里
```
<html>
<head></head>
<body>
    app应该挂载在这
    <div>而不是在这</div>
</body>
<html>
```
