### ISSUE TITLE
Hydration style mismatch: v-bind and style attribute on component root

### ISSUE THREAD

**Issue by Foresteam** [nuxt/nuxt#25588]
### Environment

- Operating System: Linux
- Node Version:     v20.11.0
- Nuxt Version:     3.10.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.15.1
- Builder:          -
- User Config:      modules, devtools, app, vite, vue, css, postcss, nitro, build, typescript, runtimeConfig
- Runtime Modules:  @nuxtjs/tailwindcss@6.11.2, @pinia/nuxt@0.5.1, @formkit/auto-animate/nuxt@0.8.1, nuxt-headlessui@1.1.5, nuxt-icon@0.6.8
- Build Modules:    -
- latest firefox & chromium

### Reproduction

https://stackblitz.com/edit/nuxt-starter-pgrig4?file=app.vue

### Describe the bug

Using v-bind together with style attribute on component root gives ```Hydration style mismatch``` warning:
```
- rendered on server: style="padding:100px;--938b83b0-test:100;--938b83b0-test2:red;"
- expected on client: style="padding:100px;"
```

**Comment by manniL** [comment]
Let's track in https://github.com/vuejs/core/issues/10259
