### ISSUE TITLE
Server Component Fallback not showing when lazy=true (On refresh)

### ISSUE THREAD

**Issue by dihmeetree** [nuxt/nuxt#25583]
### Environment

```
- Operating System: Darwin
- Node Version:     v20.3.1
- Nuxt Version:     3.10.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.21
- Builder:          -
- User Config:      build, devtools, experimental, modules, security, srcDir
- Runtime Modules:  @nuxtjs/tailwindcss@6.11.0, @pinia/nuxt@0.5.1, nuxt-security@1.1.0
- Build Modules:    -
```

### Reproduction

Add a server component to `components` directory (Mine looks like this, you can just use a useFetch or something):
```vue
<script setup lang="ts">
const { $client } = useNuxtApp()
const { data: todos } = $client.getTodos.useQuery()
</script>

<template>
  <div>
    <li v-for="todo in todos" :key="todo.id">
      {{ todo.name }}
    </li>
  </div>
</template>
```

Add a page in Nuxt (`pages/index.vue`) like this:
```vue
<template>
  <section>
    <div>
      <TodoList :lazy="true">
        <template #fallback>Loading...</template>
      </TodoList>
    </div>
    <NuxtLink to="/about">
      <button>
        Go to About
      </button>
    </NuxtLink>
  </section>
</template>
```

### Describe the bug

You'll notice that when you refresh... the fallback is not shown (even though it is a Lazy server component). The page just hangs until the data in the server component is fetched.

**HOWEVER!** If you're on another page, and you redirect to the index page for example (Using a `<NuxtLink>`), the fallback will be shown.

I would expect the page to render whatever is outside the Server Component instantly (showing the fallback loader), and then render it's contents once the data in the server component has been fetched.

Here's a video to what i'm describing: https://www.loom.com/share/0e5144d6e3074b03a0a632954142261f (Note: I have a 2 second delay added to my tRPC endpoint.. so you can see the delay more clearly)

**Comment by BoBo-Git** [comment]
I got same problem with latest version 3.10.0.

**Comment by manniL** [comment]
AFAIK there is no "streaming and replacing" supported at the time of writing, meaning all data (including the data from server components) need to be present to finish the initial request and to return the HTML.

cc @huang-julien

**Comment by huang-julien** [comment]
Hi :wave:

@manniL is right. the `lazy` prop act like `useLazyAsyncData` and `useLazyFetch` so it only works client side. However if you really want to not block the ssr, you can wrap the server component with a `<ClientOnly>`

**Comment by huang-julien** [comment]
hmmm can you provide a minimal reproduction so i can check what's going on ?

**Comment by manniL** [comment]
> However if you really want to not block the ssr, you can wrap the server component with a `<ClientOnly>`

Important to note: Then the content is also not in the initial HTML ☺️

**Comment by manniL** [comment]
> I would need to wait until streaming support is available for Server Components? 

I think so, yes.

**Comment by huang-julien** [comment]
there's indeed a bug in your reproduction, `NuxtIsland` isn't able to mount properly with a `<CLientOnly>` and a `#fallback`
