### ISSUE TITLE
Custom useCookie composable is not reactive between components

### ISSUE THREAD

**Issue by Jungzl** [nuxt/nuxt#25587]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.19.0
- Nuxt Version:     3.10.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.15.1
- Builder:          -
- User Config:      app, nitro, build, modules, css, vueuse, typescript, devServer, runtimeConfig, vite, elementPlus, headlessui, swiper, experimental
- Runtime Modules:  @vueuse/nuxt@10.7.2, @unocss/nuxt@0.58.4, @pinia/nuxt@0.5.1, @element-plus/nuxt@1.0.7, nuxt-headlessui@1.1.5, nuxt-swiper@1.2.2
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-mbsb9n?file=composables%2Fuse-a.ts,components%2FcompA.vue,components%2FcompB.vue,app.vue

1. click button in CompA
2. CompB text disappears

### Describe the bug

It used to work in v3.9.3, two components should have same value.
Now, after clicking the button in CompA, value in CompB becomes undefined.
If you call `refreshCookie('a')` in click event and click button frequently, you'll notice that text flashes in CompB then disappears.

**Comment by danielroe** [comment]
resolved in https://github.com/nuxt/nuxt/pull/25598
