### ISSUE TITLE
Prerendering fails if file-based routing is disabled, but there are .vue files in pages directory

### ISSUE THREAD

**Issue by andreww2012** [nuxt/nuxt#25594]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.10.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-sgbtc2

```shell
npm run generate
```

### Describe the bug

During prerendering, it tries to pre-render pages corresponding to `.vue` files in `/pages` directory, but since the server is responding with 404 status code, the whole process fails.

This can be cured by adding all the pseudo-routes to `nitro.prerender.ignore` array of nuxt config file.

**Comment by RyanClementsHax** [comment]
I'd be happy to take a look at this

**Comment by RyanClementsHax** [comment]
It seems nitro is being handed the wrong route options when prerendering here https://github.com/nuxt/nuxt/blob/ec5d254f417d04e92acd0a716c662637e178f6a6/packages/nuxt/src/core/nitro.ts#L501

I'm debugging further

**Comment by RyanClementsHax** [comment]
The prerender config is set by [this line](https://github.com/nuxt/nuxt/blob/fa79b86d4ab286c3c43735b5d589006e95d9182f/packages/nuxt/src/pages/module.ts#L281) which sets it to a set of pages from [created only from pages within the `/pages` directory](https://github.com/nuxt/nuxt/blob/fa79b86d4ab286c3c43735b5d589006e95d9182f/packages/nuxt/src/pages/module.ts#L258).

The custom `router.options.ts` seems only imported by the runtime code generated by [this template](https://github.com/nuxt/nuxt/blob/fa79b86d4ab286c3c43735b5d589006e95d9182f/packages/nuxt/src/pages/module.ts#L442).

I see now that the pages module doesn't have the final routing config in memory when creating the prerendering config.

I see a few ways to tackle this. Let me know if there are others.
1. Import the `router.options.ts` file (and any other files) in the pages module to discover what the final routing config resolves to.
    - Is there precedent for something similar elsewhere in nuxt? I haven't found anything yet, but I'll keep looking.
2. Change the way prerendering works to introspect the running site to discover what routes exist.
    - Based on what I know about nitro and nuxt thus far, this seems like it would require a change to nitro and the generated app for prerendering. I could be wrong though.

@danielroe any thoughts?

**Comment by danielroe** [comment]
I think we should use a Nuxt plugin that is guarded by `import.meta.prerender` so it does not add anything to the final build, and which only executes once, passing all paths to the `prerenderRoutes` composable.

**Comment by RyanClementsHax** [comment]
Just to make sure we are talking about the same piece of code, you're referring to [this composable](https://github.com/nuxt/nuxt/blob/27f9c55fc2f5c7d6a21920e6bd902a7ebc728efc/packages/nuxt/src/app/composables/ssr.ts#L62) correct?

Also, I'll be happy to take this on if you want to assign it to me.

**Comment by RyanClementsHax** [comment]
@danielroe Thanks for your patience. I've been helping my wife with morning sickness (we're having another kid!!!).

Anyway, regarding the `prerenderRoutes` function, I played around with it to learn how prerendering works and see that it is only additive to what the prerenderer generates. Given [nitro is preconfigured to generate all of the routes in the `pages` directory](https://github.com/nuxt/nuxt/blob/fa79b86d4ab286c3c43735b5d589006e95d9182f/packages/nuxt/src/pages/module.ts#L254), are you suggesting that we remove this logic from the module and expose the routes to crawl using the plugin?

**Comment by andreww2012** [comment]
Hey, thank you for taking your time into resolving this issue, but unfortunately it is still not fixed in the latest Nuxt version (3.12.4). You can use the same reproduction to confirm that (since nuxt has a ^ before the version, it will install the newer version and then run `npm run generate`): https://stackblitz.com/edit/nuxt-starter-sgbtc2).
