### ISSUE TITLE
useNuxtApp provide type

### ISSUE THREAD

**Issue by arashsheyda** [nuxt/nuxt#25595]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.10.0`
- Nuxt Version:     `3.9.3`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `npm@10.2.3`
- Builder:          `-`
- User Config:      `modules`, `css`, `runtimeConfig`, `sanity`, `lodash`, `devServer`, `server`, `ssr`, `app`, `vue`, `sitemap`, `robots`, `routeRules`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.8.0`, `@nuxtjs/sanity@1.8.1`, `nuxt-lodash@2.5.0`, `@pinia/nuxt@0.4.11`, `nuxt-simple-robots@2.3.0`
- Build Modules:    `-`

### Reproduction

create any `plugin` and provide something, for example `dayjs.ts`:

```
import dayjs from 'dayjs'

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.provide('dayjs', dayjs)
})

```

### Describe the bug

when we want to use it in our `.vue`, there is no autocomplete for it. to have the types we have to add this into our plugin:

```
declare module '#app' {
  interface NuxtApp {
    $dayjs: typeof dayjs
 }
}
```

in the documentation there is no reference of declaring [`NuxtApp interface`](https://nuxt.com/docs/api/composables/use-nuxt-app)

should we add that to documentation?

**Comment by warflash** [comment]
The plugin docs actually do include a section covering typing plugins: https://nuxt.com/docs/guide/directory-structure/plugins#typing-plugins

**Comment by arashsheyda** [comment]
@warflash didn't know that, thanks
