### ISSUE TITLE
Nuxt prepare error after installing sass, pinia and vitest with yarn in Nuxt 3.10.0

### ISSUE THREAD

**Issue by alanbosco** [nuxt/nuxt#25597]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.10.0
- Nuxt Version:     3.10.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.21
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Links: [https://stackblitz.com/~/edit/github-mqk1g4]( https://stackblitz.com/~/edit/github-mqk1g4)

### Describe the bug

While installing sass, vitest, and pinia in nuxt 3.10.0 using yarn. I am getting an error on Nuxt prepare. 

#### Error

```
$ nuxt prepare

[3:48:40 AM]  ERROR  require() of ES Module [path]/nuxt-pica-boilerplate/node_modules/string-width/index.js from [path]/nuxt-pica-boilerplate/node_modules/wide-align/align.js not supported.
Instead change the require of index.js in [path]/nuxt-pica-boilerplate/node_modules/wide-align/align.js to a dynamic import() which is available in all CommonJS modules.

  Instead change the require of index.js in node_modules/wide-align/align.js to a dynamic import() which is available in all CommonJS modules.
  at Object.<anonymous> (node_modules/wide-align/align.js:2:19)



[3:48:40 AM]  ERROR  require() of ES Module [path]/nuxt-pica-boilerplate/node_modules/string-width/index.js from [path]/nuxt-pica-boilerplate/node_modules/wide-align/align.js not supported.
Instead change the require of index.js in [path]/nuxt-pica-boilerplate/node_modules/wide-align/align.js to a dynamic import() which is available in all CommonJS modules.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Do you have any possible fixes?

**Comment by warflash** [comment]
Thanks for reporting! Unfortunately this is an issue with yarn itself, please see https://github.com/nuxt/nuxt/issues/21231#issuecomment-1921051936 for more  discussion on the topic
