### ISSUE TITLE
nuxt.js3 How to use qrcodejs2-fix; keeps reporting errors document is not defined

### ISSUE THREAD

**Issue by wangrunze2023** [nuxt/nuxt#25608]
### Environment

nuxt.js3 How to use qrcodejs2-fix; keeps reporting errors document is not defined

### Reproduction

nuxt.js3 How to use qrcodejs2-fix; keeps reporting errors document is not defined

### Describe the bug

nuxt.js3 How to use qrcodejs2-fix; keeps reporting errors document is not defined

### Additional context

nuxt.js3 How to use qrcodejs2-fix; keeps reporting errors document is not defined

### Logs

```shell-script
nuxt.js3 How to use qrcodejs2-fix; keeps reporting errors document is not defined
```

**Comment by moshetanzer** [comment]
Welcome to Nuxt.

Problem is that this is running on Server side.

See this for starters:
https://stackoverflow.com/questions/46058544/document-is-not-defined-in-nuxt-js

This should probably be asked in discussions or stackoverflow.

This is not a bug.

**Comment by manniL** [comment]
@moshetanzer is correct 👍 While the linked answer is a bit outdated, you can try:

* dynamically importing it in `onMounted`
* or (better) use a `.client.vue` component and encapsulate it in there
