### ISSUE TITLE
Problem with `useRuntimeConfig` and `useCookie` in `useCustomFetch`

### ISSUE THREAD

**Issue by joffreyBerrier** [nuxt/nuxt#25604]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.10.0
- Nuxt Version:     3.10.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.8.0
- Builder:          -
- User Config:      devtools, modules, runtimeConfig
- Runtime Modules:  @pinia/nuxt@0.5.1
- Build Modules:    -
------------------------------

### Reproduction

Reproduction link: https://github.com/joffreyBerrier/nuxt-issue-use-custom-fetch/tree/main

## Nuxt Debugging Steps

1. Run `npm install` & `npm run dev`.
2. Check your terminal to see this error:
```
ERROR AUTH STORE Error: [nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Learn more at `https://nuxt.com/docs/guide/concepts/auto-imports#vue-and-nuxt-composables`.
```

## Encountered Issue

* Encountered a problem with the useCustomFetch function, created based on this example: https://nuxt.com/docs/examples/advanced/use-custom-fetch-composable, but it fails to work.
* Removing `useCookie` and `useRuntimeConfig` resolves the issue, however, **I need `useCookie` or an alternative, or `useRuntimeConfig` to set the baseURL.**

### Describe the bug

I have create a `useCustomFetch` like this example : 
https://nuxt.com/docs/examples/advanced/use-custom-fetch-composable

But when I'm using `useCookie` or `useRuntimeConfig` I can't use `useCustomFetch` after asynchronous api call

### Additional context

I understand why the bug is occurring; it's related to calling a composable after an asynchronous call. However, I don't understand how I can solve this problem. Since this example is on your website, I would like a working solution.

### Logs

```shell-script
Nuxt 3.10.0 with Nitro 2.8.1                                                                                         13:07:42
                                                                                                                     13:07:42
  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

  ➜ DevTools: press Shift + Option + D in the browser (v1.0.8)                                                       13:07:43

ℹ Vite client warmed up in 455ms                                                                                    13:07:44
ℹ Vite server warmed up in 711ms                                                                                    13:07:44
✔ Nitro built in 458 ms                                                                                       nitro 13:07:44
resUser { userId: 1, id: 1, title: 'delectus aut autem', completed: false }
ERROR AUTH STORE Error: [nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at `https://nuxt.com/docs/guide/concepts/auto-imports#vue-and-nuxt-composables`.
    at useNuxtApp (/**/node_modules/nuxt/dist/app/nuxt.js:216:13)
    at Module.useRuntimeConfig (/**/node_modules/nuxt/dist/app/nuxt.js:226:27)
    at Module.useCustomFetch (/**/composables/useCustomFetch.ts:11:40)
    at Proxy.callApi (/**/stores/auth.ts:20:54)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /**/middleware/auth.global.ts:19:11
    at async Object.callAsync (**/node_modules/unctx/dist/index.mjs:72:16)
    at async /**/node_modules/nuxt/dist/pages/runtime/plugins/router.js:144:26
```

```[tasklist]
### Tasks
- [ ] Review the documentation with the new example so that it works
```

**Comment by danielroe** [comment]
useFetch or useCustomFetch are composables and should be called in setup, not in a callApi method in a store.

If you do need to pass the Nuxt instance, you can run useNuxtApp at the top of your store method and then nuxtApp.runWithContext to call your custom composable.
