### ISSUE TITLE
Warning for `NuxtPage` absence is always shown if `setPageLayout` is called in middleware

### ISSUE THREAD

**Issue by NozomuIkuta** [nuxt/nuxt#25617]
### Environment

- Operating System: `Darwin`
- Node Version:     `v21.5.0`
- Nuxt Version:     `3.10.0`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `npm@10.2.4`
- Builder:          `-`
- User Config:      `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

But I believe this bug happens in all environments.

### Reproduction

Original reproduction by @robert-gruner
https://stackblitz.com/~/edit/github-wgg4gm-sdfzwd

Minimal reproduction by me
https://stackblitz.com/edit/github-wgg4gm-8hhehw

### Describe the bug

This issue is an edge case which was not tested in #25490.

With the `content.global.ts`, which dynamically changes layout, the warning message is always shown.
Without the middleware (i.e. without calling `setPageLayout`), the warning message is shown expectedly.

### Additional context

This issue and the reproduction were originally reported by @robert-gruner as https://github.com/nuxt/nuxt/pull/25490#issuecomment-1925902990.

**Comment by NozomuIkuta** [comment]
>Neither of those layouts has a <slot />, and <NuxtPage /> is not being rendered in either case.

Ah, I overlooked that point!

Here is the fixed version of the reproduction, and yes the warning is not shown with `<slot />`.
And now calling `setPageLayout()` doesn't affect this behavior.

https://stackblitz.com/edit/github-wgg4gm-qyvjee

I believe this issue can be closed for now 👍 

@robert-gruner

You might want to add `<slot />` to the layout components in which `<NuxtPage />` is rendered.

**Comment by robert-gruner** [comment]
Thanks for the clarification. I can confirm that the warning disappears if we have proper Slots inside the layouts. Sorry for missing that. 🙈

**Comment by NozomuIkuta** [comment]
@danielroe 

For the repository governance, I will leave the closing operation to you 🙋‍♂️

**Comment by danielroe** [comment]
Thank you all for the investigation and faithful reproductions ❤️
