### ISSUE TITLE
Feature: support style config on addComponent & addComponentsDir

### ISSUE THREAD

**Issue by zhangmo8** [nuxt/nuxt#25611]
### Describe the feature

In the component library module. 
We should automatically import components in Nuxt3 for users. We always import some style files for this component (<var-button> import '../xxx/style'). 

 at this link https://github.com/nuxt/module-builder/issues/106. I want to use `addComponentsDir` to replace `addComponent`. Then now I can use `extendComponent` to resolve the Component's alias. 

I want to add an optional prototype to the Component's style file. if anyone needs.

Maybe It's like 

```javascript
const dirPath = `${moduleName}/es`;
const filePath = `${moduleName}/es/${kebabCase(name)}/index`;
const stylePath = `${moduleName}/es/${kebabCase(name)}/style/index`;

addComponent({
   name: `XXX${name}`,
   filePath,
   stylePath,
   export: `_${name}Component`
})

addComponentsDir({
  path: join(CMD, `node_modules/${dirPath}`),
  .......
  extendComponent (component) {
    const componentName = component.pascalName.replace('Var', '')
    return {
      ...component,
      stylePath: `${component.filePath}/style`
        export: `_${componentName}Component`,
      }
    }
  ......
})
```

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
We think this is probably too specific of a use case to support in Nuxt core. But it would be possible to implement this using a build plugin created with `unplugin` that you ship with your module, which automatically adds the correct CSS import when using the component.

**Comment by zhangmo8** [comment]
> We think this is probably too specific of a use case to support in Nuxt core. But it would be possible to implement this using a build plugin created with `unplugin` that you ship with your module, which automatically adds the correct CSS import when using the component.

OK.
