### ISSUE TITLE
Compilation often leads to errors.

### ISSUE THREAD

**Issue by bbhxwl** [nuxt/nuxt#25629]
### Environment

```
{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/devtools": "latest",
    "@nuxtjs/color-mode": "^3.3.2",
    "@nuxtjs/device": "^3.1.1",
    "@nuxtjs/tailwindcss": "^6.11.2",
    "@pinia-plugin-persistedstate/nuxt": "^1.2.0",
    "@pinia/nuxt": "^0.5.1",
    "@vant/nuxt": "^1.0.4",
    "dayjs-nuxt": "^2.1.9",
    "vant": "^4.8.4",
    "nuxt": "^3.10.0",
    "vue": "^3.4.15",
    "vue-router": "^4.2.5",
    "jwt-decode": "^4.0.0"
  },
  "dependencies": {

  }
}

```

### Reproduction

![image](https://github.com/nuxt/nuxt/assets/26525599/5e7df6db-6478-4925-a7b3-69680eb10589)

### Describe the bug

![image](https://github.com/nuxt/nuxt/assets/26525599/f4e114a6-7984-49c8-8048-779c046b41e2)

**Comment by danielroe** [comment]
This is a bug in yarn, not Nuxt. See https://github.com/search?q=strip-ansi+string-width&type=issues.

[This comment](https://github.com/storybookjs/storybook/issues/22431#issuecomment-1630086092) explains the issue and provides a workaround.
