### ISSUE TITLE
useHead not works with routeRoules ssr false

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/nuxt#25621]
### Environment

- Operating System: `Linux`
- Node Version:     `v20.5.1`
- Nuxt Version:     `3.10.0`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `npm@9.8.0`
- Builder:          `-`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-zx9ywx

### Describe the bug

If we use useHead with a client page, dont writes the title, the descripton and meta robots information

**Comment by manniL** [comment]
Works as expected on the client-side only.

![image](https://github.com/nuxt/nuxt/assets/640208/c7574935-48e9-4aa4-add9-9f07c78a76a6)

Without using SSR, no meta information are rendered in the HTML received "from the server".

**Comment by agracia-foticos** [comment]
@manniL  How do I indicate metadata to a page of type "client"?
