### ISSUE TITLE
updateTemplates internal server error: Failed to resolve import

### ISSUE THREAD

**Issue by productdevbook** [nuxt/nuxt#25637]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.10.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  normalizedModule()
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-cvjq9i?file=nuxt.config.ts

### Describe the bug

![CleanShot 2024-02-05 at 20 49 51](https://github.com/nuxt/nuxt/assets/38668796/86340735-d8f9-405d-af06-6e4dd3e867db)

Even if the algorithm is renewed, .vue does not see that algorithm in it.

1. graphql/a.ts add new function.
2. app.vue `Test.test33333();` change function. and refresh page.

### Video
https://github.com/nuxt/nuxt/assets/38668796/695c61f2-9190-4424-873c-2b46c612ac04

**Comment by danielroe** [comment]
You should not use `.nuxt` as the source for scanning any imports you generate. It is explicitly not watched to avoid infinite loops.
