### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by DTesch-Reem** [nuxt/nuxt#25643]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.19.0
- Nuxt Version:     3.10.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      extends, modules, css, app, devtools, multiCache, experimental, colorMode, runtimeConfig, graphql-client, ui, $development, nitro
- Runtime Modules:  nuxt-graphql-client@0.2.33, nuxt-multi-cache@3.1.1, @nuxt/ui@2.13.0
- Build Modules:    -
------------------------------

### Reproduction

I am using ddev with nginx to get ssl on local environment. (ddev npm run dev)
After 10-15 saves, when using the  HMR with the Dev-Server I get this error:

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb7f974 node::Abort() [/usr/bin/node]
 2: 0xa97f08  [/usr/bin/node]
 3: 0xd40e78 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
 4: 0xd41048 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
 5: 0xf1f5fc  [/usr/bin/node]
 6: 0xf20264 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/usr/bin/node]
 7: 0xf307ac  [/usr/bin/node]
 8: 0xf31370 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/bin/node]
 9: 0xf0d718 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]
10: 0xf0e6f0 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]
11: 0xef1380 v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/bin/node]
12: 0x1297a34 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/bin/node]
13: 0x167c4ec  [/usr/bin/node]

### Describe the bug

Running the dev-Server behind a reverse proxy (nginx) and using HMR crashes the development server after some saves (10-15).
Only fix is to restart the server.

**Comment by boboldehampsink** [comment]
Seeing this too with 3.10+

**Comment by alexrodriguezjob** [comment]
We are having the same issue, couln't replicate in dev/staging and in production we have an absurd increase of memory 

![image](https://github.com/nuxt/nuxt/assets/89662700/1e5e45d9-28ae-45de-872b-e3f4a7917ba5)

**Comment by daniluk4000** [comment]
> We are having the same issue, couln't replicate in dev/staging and in production we have an absurd increase of memory
> 
> ![image](https://private-user-images.githubusercontent.com/89662700/307134256-1e5e45d9-28ae-45de-872b-e3f4a7917ba5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MzUzNzgsIm5iZiI6MTcwODYzNTA3OCwicGF0aCI6Ii84OTY2MjcwMC8zMDcxMzQyNTYtMWU1ZTQ1ZDktMjhhZS00NWRlLTg3MmItZTNmNGE3OTE3YmE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDIwNTExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyNWM0NWFlN2E5MDg1MjA4MTU5NGZlNzlhMjMxZjQwZjUyZTE1MmVjMDFhZmU5MDVlNDkzZDhlN2QwYTg3MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._YSxBheXIGjawY81I2sYcff5HVXggX1OOs_vpFY11pQ)

Jesus christ. 

I'll share our stats then. We have semi-highload website with several replicas of Nuxt. All of them go to ~500-600MB of memory, which is even higher we were on Nuxt 2. On Staging we have no higher than 300MB, with medium at ~200-250MB. Nuxt 2 were more stable for me on memory. Sadly we went straight to Nuxt 3.10 (were upgrading) so I can't say if it was better.

**Comment by daniluk4000** [comment]
Our heavy spike was caused by asyncContext + timeout in useFetch/ofetch (https://github.com/unjs/ofetch/pull/369)

**Comment by andrevferreiraa** [comment]
Got the same issue but when generating the pages

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/26798.
