### ISSUE TITLE
UseState work after middleware during SSR

### ISSUE THREAD

**Issue by Efcolipt** [nuxt/nuxt#25645]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.9.0
- Nuxt Version:     3.10.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.2
- Builder:          -
- User Config:      modules, site, sitemap, $production, $development, runtimeConfig, srcDir, devServer, devtools, app, experimental, nitro, vite
- Runtime Modules:  @vueuse/nuxt@10.7.2, @nuxtjs/robots@^3.0.0, nuxt-icons@^3.2.1, @nuxtjs/device@^3.1.1, @nuxtjs/sitemap@^5.0.4, @nuxtjs/google-fonts@^3.1.3, nuxt-gtag@^1.1.2
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-zabnym?file=app.vue

### Describe the bug

So useState don't set when we on page where we have a middleware which check useState have or not
Middleware work first instead set useState during ssr
So We catch error when hydration html

**Comment by danielroe** [comment]
I think this is just a misunderstanding of the order in which these things run.

1. plugins
2. middleware
3. page starts being rendered

So if you set the user when the page is rendered, it's too late. Middleware won't rerun. There is no reactivity when rendering on the server.
