### ISSUE TITLE
The page is rendered first with middleware when using Pinia

### ISSUE THREAD

**Issue by ThisAccountHasBeenSuspended** [nuxt/nuxt#25652]
### Environment

- Operating System: Windows_NT
- Node Version:     v21.6.1
- Nuxt Version:     3.10.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      srcDir, devtools, css, postcss, modules, imports, routeRules, runtimeConfig
- Runtime Modules:  @pinia/nuxt@0.5.1
- Build Modules:    -

### Reproduction

The website may appear for 1 second before the middleware is invoked:
```js
export default defineNuxtRouteMiddleware((to, from) => {
  // Website already rendered ...
  const authStore = useAuthStore();
  if (authStore.loggedIn === true) {
    return navigateTo('/');
  }
});
```

Without problems:
```js
export default defineNuxtRouteMiddleware((to, from) => {
  // Route e.g. `/login` doesn't render ...
  if (1 === 1) {
    return navigateTo('/');
  }
});
```
```js
export default defineNuxtRouteMiddleware((to, from) => {
  // Route e.g. `/login` doesn't render ...
  const loggedIn = useCookie('loggedIn');
  if (typeof loggedIn !== 'undefined') {
    return navigateTo('/');
  }
});
```

### Describe the bug

Using `Pinia`, for example, causes the page I don't want to be displayed to still appear for a second.

**Important:** Here the complete route `http://localhost:3000/login` must be used instead of a link like `<NuxtLink :to="/login">`

**Comment by danielroe** [comment]
This is likely a logic issue in the app/your code rather than in Nuxt. So probably `loggedIn` is not yet set on the server, so the server renders the page. Then on the client `loggedIn` is set, but the browser will obviously still show whatever the server rendered, for a brief moment. (This will also cause a hydration error.)

**Comment by ThisAccountHasBeenSuspended** [comment]
> This is likely a logic issue in the app/your code rather than in Nuxt. So probably `loggedIn` is not yet set on the server, so the server renders the page. Then on the client `loggedIn` is set, but the browser will obviously still show whatever the server rendered, for a brief moment. (This will also cause a hydration error.)

This "bug" with Pinia is just what I found out about my actual problem. The real problem is when I use the first code everything works fine but when I use Pinia I get these messages in the browser in the console when I use `navigateTo()` without `external: true`:

![image](https://github.com/nuxt/nuxt/assets/154023155/568cd95a-32a2-4bfa-b766-5f5135df5631)

__Without any warnings/errors:__
```js
export default defineNuxtRouteMiddleware((to, from) => {
  if (1 == 1) {
    return navigateTo('/');
  }
});
```

__With warnings and errors:__
```js
export default defineNuxtRouteMiddleware((to, from) => {  
  const auth = useAuthStore();

  if (auth.loggedIn === true) {
    return navigateTo('/');
  }
});
```

**Comment by madebyfabian** [comment]
@ThisAccountHasBeenSuspended Can you confirm that you still experience this issue?
