### ISSUE TITLE
Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. Received protocol 'https:'

### ISSUE THREAD

**Issue by Foddie2** [nuxt/nuxt#25656]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.15.0
- Nuxt Version:     3.10.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.21
- Builder:          -
- User Config:      ssr, devtools, css, plugins, devServerHandlers, postcss, modules, content, runtimeConfig
- Runtime Modules:  @nuxt/content@2.11.0, nuxt-purgecss@2.0.0, nuxt-mailer@0.11.0, @nuxtjs/tailwindcss@6.11.2
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/Foddie2/TechBytes

### Describe the bug

Getting this error when in production

**Comment by danielroe** [comment]
Would you see if you can provide a more minimal reproduction? 🙏
