### ISSUE TITLE
Add short "pcss" extension of postcss

### ISSUE THREAD

**Issue by usmanov-uktam** [nuxt/nuxt#25653]
https://github.com/nuxt/nuxt/blob/c5d5932f57cdaabd39c611b91e021381a44a5afa/packages/vite/src/utils/index.ts#L10

**Comment by manniL** [comment]
Seems like a good candidate for a PR to me. Also should be updated in https://github.com/nuxt-contrib/vue-bundle-renderer/blob/main/src/utils.ts#L5

**Comment by amandesai01** [comment]
Let me know if anything else needed
