### ISSUE TITLE
Unable to Start a Project in Windows

### ISSUE THREAD

**Issue by znonthedev** [nuxt/nuxt#25664]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.19.0
- Nuxt Version:     3.10.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.15.1
- Builder:          -
- User Config:      devtools, app, modules, shadcn, veeValidate, runtimeConfig
- Runtime Modules:  @nuxtjs/tailwindcss@6.11.3, shadcn-nuxt@0.8.7, @nuxtjs/supabase@1.1.6, @vee-validate/nuxt@4.12.5
- Build Modules:    -

### Reproduction

Use Windows and install node using NVM (v18). 
pnpm dlx nuxi@latest init winodows-issue

### Describe the bug

Unable to start working on a project, I tried this in WSL and it is working fine

### Logs

```shell-script
![image](https://github.com/nuxt/nuxt/assets/22857223/bbbf4913-6c36-4a46-ab65-383b527c4496)



 ERROR  Pre-transform error: path should be a path.relative()d string, but got "C:/Users/***********/AppData/Roaming/nvm/v18.19.0/node_modules/@nuxt/devtools/node_modules/vite-plugin-vue-inspector/src/load.js"                                                       7:03:59 PM  


 ERROR  Pre-transform error: path should be a path.relative()d string, but got "C:/Users/***********/AppData/Roaming/nvm/v18.19.0/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.mjs?v=3738113a"                                                      7:03:59 PM
```

**Comment by znonthedev** [comment]
![image](https://github.com/nuxt/nuxt/assets/22857223/c90026ca-34a5-45b5-9ff8-3361b7ff694a)

**Comment by daniser** [comment]
@znonthedev Check this out #25261.

**Comment by znonthedev** [comment]
Thanks, @daniser for sharing, I will close this as a duplicate of https://github.com/nuxt/nuxt/issues/25261
