### ISSUE TITLE
Types Error for types exported from external libraries.

### ISSUE THREAD

**Issue by mrc-bsllt** [nuxt/nuxt#25674]
### Environment

- Operating System: Darwin
- Node Version:     v20.9.0
- Nuxt Version:     3.10.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, experimental, runtimeConfig, app, modules, fontLoader, css, vite, typescript, i18n, nuxt-jsonld, primevue, image
- Runtime Modules:  @nuxt/image@1.3.0, @nuxtjs/eslint-module@4.1.0, @nuxtjs/i18n@8.0.2, @nuxtjs/robots@3.0.0, @nuxtjs/strapi@1.11.0, @nuxtjs/tailwindcss@6.11.3, @pinia/nuxt@0.5.1, @vueuse/nuxt@10.7.2, nuxt-icons@3.2.1, nuxt-jsonld@2.0.8, nuxt-primevue@0.2.2, @vee-validate/nuxt@4.12.5, nuxt-font-loader@2.3.5
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-1psnfn?file=types%2Ftest.types.ts

### Describe the bug

After updating Nuxt to the latest version (3.10.1), it no longer recognises types imported from external libraries (in my case, strapi and i18n).

**Comment by mrc-bsllt** [comment]
For the moment, I solved the problem by setting sharedPrerenderData to false.

```javascript
export default defineNuxtConfig({
  experimental: {
    sharedPrerenderData: true,
  },

 // ...
});
```

**Comment by cn-2k** [comment]
> ```js
> future: {
>     typescriptBundlerResolution: false,
>   },
> ```

I had the same problem, this solved it for me, thanks!

**Comment by manniL** [comment]
@cn-2k @mrc-bsllt can you please let us know *which* libraries have issues with it? Ideally also raise an issue there if you have the time for it ☺️

**Comment by cn-2k** [comment]
> @cn-2k @mrc-bsllt can you please let us know _which_ libraries have issues with it (so far I read the strapi module and nuxt i18n module)? Ideally also raise an issue there if you have the time for it ☺️

Until now my problem  was with `@nuxtjs/eslint-module` when using top level options (not recognises types).
It only happen on `3.10` nuxt release.

**Comment by danielroe** [comment]
Yes, this isn't a Nuxt issue; any libraries that have this problem probably don't have valid Node16 style types. Feel free to tag me/@manniL in issues you raise there - I'm more than happy to help resolve.
