### ISSUE TITLE
304 Response contains content-type header field but should not

### ISSUE THREAD

**Issue by ma-koch** [nuxt/nuxt#25678]
### Environment

Nuxt project info:                                                                                                                                              3:19:22 PM

------------------------------
- Operating System: Linux
- Node Version:     v18.16.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      nitro, devtools, runtimeConfig, css, vite, modules, security, build, app, apollo, routeRules
- Runtime Modules:  @nuxtjs/apollo@5.0.0-alpha.6, nuxt-security@1.0.0-rc.3, nuxt-lazy-hydrate@1.0.0, nuxt-beastcss@1.0.3
- Build Modules:    -
------------------------------

### Reproduction

Build app in production mode, and request css or js asset with the header field `if-modified-since` set to a date > file modified. 
e.g.

curl 'http://localhost:5000/_some-path/test.1234.css' -Ik \
  -H 'sec-ch-ua: "Chromium";v="121", "Not A(Brand";v="99"' \
  -H 'Referer: http://localhost:5000/' \
  -H 'dpr: 1' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36' \
  -H 'viewport-width: 1920' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'if-modified-since: "Wen, 7 Feb 2024 14:22:00 GMT"' \
  --compressed
 
 The  -Ik Flag is to display just the header information.

### Describe the bug

Expectation:
304 Response,  without the content-type field.
https://www.rfc-editor.org/rfc/rfc7232#section-4.1

Actual Answer:
304 Response but with a content-field  (default value text/html)

### Additional context

When you create a nitro plugin within your `server/plugin` folder, you can see that between the  `beforeResponse` and  `afterResponse` hook the header field is added.

see:

```
export default defineNitroPlugin((nitroApp) => {
  nitroApp.hooks.hook('beforeResponse', (event) => {
    if (event.node.res.statusCode === 304) {
     // header field does not contain content-type
      console.log(event.node.res.getHeaders())
    }
  })
  nitroApp.hooks.hook('afterResponse', (event) => {
    if (event.node.res.statusCode === 304) {
      // header field does contain a content-type field
      console.log(event.node.res.getHeaders())
    }
  })
})
```

Nitro config:
```
nitro: {
    compressPublicAssets: {
      brotli: true,
    },
 },
```

**Comment by danielroe** [comment]
Would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏

**Comment by ma-koch** [comment]
Hey,

thank you for the fast answer. 

i cant get the server to respond with an 304 request.
Also tried to clone the [Starter Template](https://nitro.unjs.io/guide/getting-started#starter-template) to my laptop with the same result.

So i guess its just inside Nuxt?

**Comment by danielroe** [comment]
Could you provide a Nuxt reproduction then? 🙏

**Comment by grob** [comment]
Not applying the default content type `text/html` to 304 responses has already been fixed in [h3](https://github.com/unjs/h3/issues/603) ([nitro issue](https://github.com/unjs/nitro/issues/1700)), so maybe it's just a matter of dependency bump in nuxt?

**Comment by danielroe** [comment]
Nuxt already will accept any patch/minor of h3 so you may just need to update your lock file.

**Comment by ma-koch** [comment]
ah yes this worked. Thank you
