### ISSUE TITLE
Please make child components to be able to redeclare parent's component layout defined in NuxtLayout

### ISSUE THREAD

**Issue by kerim1505k** [nuxt/nuxt#25689]
### Describe the feature

I saw a lot of similar issues about that (for example - https://github.com/nuxt/nuxt/issues/19762) but there is still a problem with redeclaring nuxt layouts in child components.

I created a reproduction for example - https://stackblitz.com/edit/github-bzckfe-r7uiho?file=layouts%2Fparentlayout.vue,pages%2Fparent%2Fchild2.vue,layouts%2Fcustom.vue,pages%2Findex.vue

As you can see in my reproduction build, component named "child2" has it's own NuxtLayout defined and it's rendering inside parent's layout. 

And it's the same problem if I use condition check in parent component

```<NuxtLayout name="$route.meta.layout || 'parentLayout'"></NuxtLayout>```

and in child component by using ```definePageMeta({ layout: 'custom' });```
it still rendering inside parent's layout. 

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
I'm not sure I understand the issue.

**Comment by manniL** [comment]
@danielroe I think the idea is that the child component should be able to change the layout of the page (which I don't think is possible with SSR being rendered top to bottom).

**Comment by danielroe** [comment]
You can use `setPageLayout` in a plugin or middleware to set the layout before the parent starts to render. Or you can use `definePageMeta` to override the layout from the child.

If you explicitly set `<NuxtLayout name="parentlayout">` then this is not overrideable. (Passing an explicit layout name _is_ the override in this case.)
