### ISSUE TITLE
setPageLayout is invalid when NuxtLayout name is set

### ISSUE THREAD

**Issue by Beiluola** [nuxt/nuxt#25687]
### Environment

Nuxt project info: (copied to clipboard)                                                                                                                                                     10:49:26

------------------------------
- Operating System: Darwin
- Node Version:     v18.18.0
- Nuxt Version:     3.10.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.15.1
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/Beiluola/nuxt3.10.1-setpagelayout-is-invalid-when-nuxtlayoutname-is-set

1. `pnpm i`
2. `pnpm dev`
3. open `/test` page, the `default layout` text is displayed
4. open `app.vue`, delete `name` attribute
5. open `/test` page, the `empty layout` text is displayed

this is document content about `NuxtLayout name`:

> name: Specify a layout name to be rendered, can be a string, reactive reference or a computed property. It must match the name of the corresponding layout file in the layouts/ directory.

this is document content about `setPageLayout`:

> setPageLayout allows you to dynamically change the layout of a page.

I'm not sure if this is a feature or a bug.

### Describe the bug

setPageLayout is invalid when NuxtLayout name is set

**Comment by danielroe** [comment]
`setPageLayout` doesn't override any _explicit_ layout name provided. You can consider providing the layout name provided in the `name` as the final override.
