### ISSUE TITLE
Add `exclude` for `routeRules`

### ISSUE THREAD

**Issue by ThisAccountHasBeenSuspended** [nuxt/nuxt#25693]
### Describe the feature

It would be a nice feature if it was possible to exclude underlying routes.

How I imagine it:
```
routeRules: {
  '/api/**': {
    exclude: [
      '/api/example'
    ]
  }
}
```
something like `http://localhost:3000/api/example/test` will then be ignored

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by pi0** [comment]
You can also try this btw:

```js
routeRules: {
  '/api/**': { cache: true },
  '/api/example': { cache: false } 
}
```

**Comment by ThisAccountHasBeenSuspended** [comment]
> You can also try this btw:
> 
> ```js
> routeRules: {
>   '/api/**': { cache: true },
>   '/api/example': { cache: false } 
> }
> ```

I'll try it. Thank you

**Comment by danielroe** [comment]
Feel free to raise this in https://github.com/unjs/nitro/ as a proposal directly. 🙏
