### ISSUE TITLE
Style sheets are not included on the server side during production builds

### ISSUE THREAD

**Issue by kominov** [nuxt/nuxt#25690]
### Environment

- Operating System: Linux
- Node Version:     v20.8.0
- Nuxt Version:     3.10.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.1.0
- Builder:          -
- User Config:      app, debug, sourcemap, router, runtimeConfig, build, experimental, vite, typescript, css, modules, devtools, plugins, image, viewport, BASE_API_URL
- Runtime Modules:  @nuxt/image@1.3.0, @nuxtjs/partytown@1.4.0, @vueuse/nuxt@10.7.2, nuxt-jsonld@2.0.8, nuxt-viewport@2.1.4, sitis-nuxt-3/dist
- Build Modules:    -

### Reproduction

-

### Describe the bug

Stylesheets are not included on the backend during production builds if the project uses layouts. If the contents of layouts are transferred to app.vue everything works as expected. The problem appeared since version 3.10
This is the content of app.vue

![image](https://github.com/nuxt/nuxt/assets/76279904/2e605f44-b761-433a-94ad-0390841e4b58)

This is the content of layouts

![image](https://github.com/nuxt/nuxt/assets/76279904/1f8726e7-1d80-4f88-8b07-b587a617fe59)

**Comment by kominov** [comment]
Unfortunately, I can’t reproduce this error on a new project, but I noticed this oddity. If I remove all the scss code from the style tag in layout, then everything starts working correctly, but if I add at least one class there, then default.css stops being generated in the production build.
it's with scss in layout
![image](https://github.com/nuxt/nuxt/assets/76279904/b1b852a3-978e-4274-903e-ff057341e778)
![image](https://github.com/nuxt/nuxt/assets/76279904/5432ad4f-e611-4b0f-9e5d-790bdc90de36)
it's without scss
![image](https://github.com/nuxt/nuxt/assets/76279904/8de87245-6f04-45fe-b3ee-9981db6995dc)

**Comment by MickL** [comment]
Possibly because of this: https://github.com/nuxt/nuxt/issues/25724

**Comment by danielroe** [comment]
resolved in https://github.com/nuxt/nuxt/pull/25764
