### ISSUE TITLE
Page renders before layout change is done

### ISSUE THREAD

**Issue by fanckush** [nuxt/nuxt#25695]
### Environment
```
- Operating System: Darwin
- Node Version:     v20.11.0
- Nuxt Version:     3.10.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  bun@1.0.22
- Builder:          -
- User Config:      devtools, typescript, modules, ssr, app, build, postcss, vite, nitro, supabase, primevue, headlessui, piniaPersistedstate, security, routeRules, runtimeConfig
- Runtime Modules:  @nuxtjs/supabase@1.1.6, @nuxtjs/tailwindcss@6.11.3, nuxt-icon@0.6.8, nuxt-typed-router@3.5.1, nuxt-security@1.1.0, @vueuse/nuxt@10.7.2, @pinia/nuxt@0.5.1, @pinia-plugin-persistedstate/nuxt@1.2.0
- Build Modules:    -
```

### Reproduction

https://stackblitz.com/edit/github-41grgd?file=nuxt.config.ts,app.vue,layouts%2Fdefault.vue

### Describe the bug

1. go to the second page (works fine)
2. go to the 1st page again 
3. notice how the page content loads before the layout has loaded

I added a transition and you can see how the transition runs **after** the other page loaded. Even thought, that other page should never appear together at the same time with other Layout

in the repro I added an `await timeout` to introduce the bug. In my actual case, there is no timeout and i'm not 100% sure why it's happening yet. But clearly, I expect Nuxt to load the layout first and then its slot content (the page)

**Comment by danielroe** [comment]
This is because you are specifying the layout in your `app.vue`, but not using the routing implementation to specify the layout. That means we can't _start_ rendering the layout at the same time as we start rendering the page.

This is an implication of how Suspense + routing works within Nuxt.

Instead, you can use `definePageMeta` layout to ensure that layouts load synchronously with the pages they correspond to.

**Comment by fanckush** [comment]
Ahh I see, interesting! Maybe it's worth adding the bit about synchronous loading in the Nuxt docs. Currently the docs don't show any difference between the 2 approaches

**Comment by danielroe** [comment]
Yes, that would be great 🙏

**Comment by fanckush** [comment]
@danielroe hello again!

nuxt `3.11` just added a very cool way to define middleware like so:

``` ts
routeRules: {
  '/admin/**': {
    appMiddleware: 'admin',
  },
},
```

This is really cool because up until now, i've been manually setting the middleware for all the admin routes manually which can error prone.

In reality I set 2 things in each nuxt page these days, the layout and the middleware. E.g. 
``` ts
definePageMeta({ middleware: 'admin', layout: 'admin' })
```

do you adding a `layout` as a route rule is a feasible feature suggestion? 
currently the only 2 ways I know of to set a layout have their downsides, one is not synchronous and other is verbose and requires the dev to remember that a new page always needs the layout to be set.

This feature would resolve both problems, it will be synchronous and ensure consistency
