### ISSUE TITLE
Warn when server routes overwrite vue pages

### ISSUE THREAD

**Issue by harlan-zw** [nuxt/nuxt#25707]
### Environment

n/a

### Reproduction

n/a

### Describe the bug

Related https://github.com/nuxt-modules/sitemap/issues/232

While there are workarounds for the above issue (checking `accept` header, check files exist, etc), it might be a good idea to change the convention for the default API paths.

I think changing the default path to `/_api` would be consistent with internal routes `/_nuxt`, and would save a lot of effort on module authors and end users when they have `/api` vue pages.

It's not a breaking change as it's tied to the user's local files, but maybe v4 is the best time to update the starters and documentation to use this.

Module authors' supporting is a bit annoying though, not sure how to solve this so added discussion tag.

**Comment by manniL** [comment]
Not sure how many users actually have that issue (I'd assume a rather small amount). Instead, allowing to rename the `api` folder + documenting it might be better than changing the default.

**Comment by pi0** [comment]
For modules, i think we can have strong recommendations to not use `/api` and instead `/_{name}` (I have mentioned this multiple times before)

For end-users I think it is still a good balance and convention to use standard/wellknown `/api` prefix. And we can document (or better as @manniL suggested to warn if pages paths are overlapping) to use `server/routes`.

**Comment by manniL** [comment]
> For modules, i think we can have strong recommendations to not use /api and instead /_{name} (I have mentioned this multiple times before)

We definitely should document that 👍

**Comment by pi0** [comment]
Indeed. Clear namespacing means for everything that modules register. But probably worth to have dedicate section for server best practices.

**Comment by danielroe** [comment]
~> https://github.com/nuxt/nuxt/issues/25709
