### ISSUE TITLE
all defineComponent are ignored.

### ISSUE THREAD

**Issue by ChurikiTenna** [nuxt/nuxt#25706]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.0.0
- Nuxt Version:     3.10.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@3.2.3
- Builder:          -
- User Config:      devtools, plugins, app
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

$ yarn create nuxt-app your-app-name

add this to index.vue

```
<template>
    <div>
        Text
    </div>
</template>

<script lang="ts">
console.log("Start!!");
export default defineComponent({
  mounted() {
    console.log("Mounted!!");
  },
})
</script>
```

$ yarn dev

### Describe the bug

I was testing my 1 year old project, and noticed the inside of `defineComponent` are not triggered at all.

I created a new blank page as shown above.
There is "Start!!" on console, but no "Mounted!!".

Same for the new project I created.

Console shows this error:
`Failed to load resource: the server responded with a status of 504 (Outdated Optimize Dep)`

### Additional context

I tried:

rm -r node_modules
rm -r yarn.lock
yarn install

**Comment by manniL** [comment]
![image](https://github.com/nuxt/nuxt/assets/640208/4f96515e-22c4-4a12-8ba9-41e6ac686a57)
Works fine for me. Be aware that `mounted` runs only on the client-side, so you will see the logs in browser only.
