### ISSUE TITLE
Circular dependency when using Nitro plugins and `useNitroApp`

### ISSUE THREAD

**Issue by noook** [nuxt/nuxt#25710]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.9.0
- Nuxt Version:     3.10.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://codesandbox.io/p/sandbox/quirky-lovelace-pd9l7w

### Describe the bug

When building the app linked above in the reproduction, the following message is displayed:

```
Export "useNitroApp" of module "node_modules/nitropack/dist/runtime/app.mjs" was reexported through module "node_modules/nitropack/dist/runtime/index.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "server/api/index.ts" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
```

### Additional context

This seems to happen when we use `useNitroApp()` in any route. Each call will result in one additional log.

Similar issue in #18789 

### Logs

```shell-script
Export "useNitroApp" of module "node_modules/nitropack/dist/runtime/app.mjs" was reexported through module "node_modules/nitropack/dist/runtime/index.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "server/api/index.ts" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
```
```

**Comment by pi0** [comment]
Thanks. It is probably something we need to fix upstream in Nitro (if you had time to move it forward there would be nice too)

General note: Please do not attach things to `nitroApp` instance. It is not supposed to be used this way. Instead use `nitroApp.hooks.hook('request, event => {}` and attach things to `event.context` which you can later retrieve from it in other places.

**Comment by noook** [comment]
Noted. I noticed the issue when I had to attach pre-initialized Google Node API's client instances (init takes a lot of time for some of them).

Would a `server/utils` file with a reference to the initialized client outside the `getClient` function work, or is the plugin a better method ? Also, what is the correct way to type a new property attached to `event.context` ?

I'll transfer the issue.

**Comment by pi0** [comment]
You can import them from #imports for plain nitro if for some reason auto import is not working (really wired btw will check later)
