### ISSUE TITLE
Calling `useId()` in template throws an error

### ISSUE THREAD

**Issue by antoinerey** [nuxt/nuxt#25717]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.10.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-sauxej?file=app.vue

```vue
<template>
  <div>
    {{ useId() }}
  </div>
</template>
```

### Describe the bug

When calling `useId()` directly inside a template, Nuxt throws an error when rendering the page: `[nuxt] [useId] key must be a string`.

**Comment by danielroe** [comment]
`useId` should not be called in template but in the `setup()` function.

**Comment by antoinerey** [comment]
Oh sh*t, that's embarrassing. Indeed, my bad. 😅

That said, the fact that `useId` is so small and pretty much what we could expect from a regular `getRandomId` method makes me think that this situation will happen again in the future.

So, may I still suggest improving the error message? As of today, the error message makes it look like a bug in the function itself rather than a misuse from the consumer. What if we had something along those lines instead?

```
[nuxt] [useId] must be used in setup functions
```

That said, thanks for the prompt answer, and sorry for the noise. 🙇

**Comment by danielroe** [comment]
Excellent point.
