### ISSUE TITLE
Add a `<script>` to the head without appending an additional hash to the `type` attribute.

### ISSUE THREAD

**Issue by Jannchie** [nuxt/nuxt#25716]
### Describe the feature

My requirement is to add a "synchronized blocking" script to the page, to set the data-scheme.

I used the nitro hook to add this script.

``` ts
export default defineNitroPlugin((nitroApp) => {
  nitroApp.hooks.hook('render:html', (html, { event: _ }) => {
    html.head.push(`<script>!(function () {
      const e = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches
      const t = localStorage.getItem('scheme') || 'auto'; (t === 'dark' || e && t !== 'light')
        ? document.documentElement.dataset.scheme = 'dark'
        : document.documentElement.dataset.scheme = 'light'
    }())
    </script>`)
  })
})
```

I want the server html to contain content like this:

``` html
<script type="text/javascript">
!(function () {
      const e = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches
      const t = localStorage.getItem('scheme') || 'auto'; (t === 'dark' || e && t !== 'light')
        ? document.documentElement.dataset.scheme = 'dark'
        : document.documentElement.dataset.scheme = 'light'
    }())
</script>
```

However, for whatever reason, the server will render the script with the hash in its own way.

``` html
<script type="a5a7080a6034cd8d6c36dc4b-text/javascript">
!(function () {
      const e = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches
      const t = localStorage.getItem('scheme') || 'auto'; (t === 'dark' || e && t !== 'light')
        ? document.documentElement.dataset.scheme = 'dark'
        : document.documentElement.dataset.scheme = 'light'
    }())
</script>
```

Notice that the type attribute contains a hash, which prevents this code from being executed when the html is initially loaded.
Then, nuxt removes this hash to make the code work.

However it doesn't fit my needs. I want to include the script without the hash exactly in the returned html so that it can be executed blockingly, otherwise I'll have problems with the screen flickering (My website, https://codetime.dev, The screen flickers when loading because the data-theme is not set in a blocking way, causing the colors to be invalidated.).

I want to add a script to the html template without appending an extra hash to the type attribute.
What can I do?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by ucw** [comment]
You can write a plugin that will add a script via useHead or use the [nuxt-color-mode](https://color-mode.nuxtjs.org/) module

**Comment by Jannchie** [comment]
I found this to be the behavior of Cloudflare's Rocket Loader™, not nuxt.
