### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'parentNode')

### ISSUE THREAD

**Issue by nazariisliusarenko** [nuxt/nuxt#25722]
### Environment

"vue": "3.4.8"
"nuxt": "3.9.1"

### Reproduction

i am getting error when reload the page on ssr mode. When i go back to this page in SPA mode i dont see this error

### Additional context

After upgrade from nuxt 3.0.0 to 3.8.0, 3.9.0,3.10.0 i am getting this error. Triied to chaged version of vue from 3.3.8 to 3.4.8, 3.4.13 and still get an error. Tried to wrap NuxtLayout and NuxtPage into div , didnt help.Tried to remove NuxtPageIndicator also didnt help.

### Logs

```shell-script
TypeError: Cannot read properties of null (reading 'parentNode')     at parentNode (entry.dOCZ9qXz.js:28:687)     at ReactiveEffect.he [as fn] (entry.dOCZ9qXz.js:20:54324)     at ReactiveEffect.run (entry.dOCZ9qXz.js:9:1851)     at L.$.update (entry.dOCZ9qXz.js:20:55334)     at callWithErrorHandling (entry.dOCZ9qXz.js:20:2166)     at flushJobs (entry.dOCZ9qXz.js:20:4841)     at flushJobs (entry.dOCZ9qXz.js:20:5014) logError @ entry.dOCZ9qXz.js:20
```

**Comment by danielroe** [comment]
There are a number of issues raised which have the same issue.

It is a bug in Vue and will probably be addressed there.

Let's track in one of them: https://github.com/search?q=repo:nuxt/nuxt+parentnode&type=issues

**Comment by nazariisliusarenko** [comment]
what is the latest vesrion vue and nuxt that works correct without this issue ?

**Comment by danielroe** [comment]
In that case could you open a new issue with a reproduction? 🙏

**Comment by nazariisliusarenko** [comment]
yes, sure
