### ISSUE TITLE
Failed to fetch dynamically imported module

### ISSUE THREAD

**Issue by mirikqq** [nuxt/nuxt#25729]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.17.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      builder, ssr, css, runtimeConfig, devtools, modules, yandexMaps, device, vite
- Runtime Modules:  @element-plus/nuxt@1.0.7, @vueuse/nuxt@10.7.0, nuxt-icons@3.2.1, vue-yandex-maps/nuxt, @nuxtjs/device@3.1.1
- Build Modules:    -
------------------------------

### Reproduction
https://stackblitz.com/edit/github-cdznxw?file=pages%2Ftest1.vue
### Describe the bug

![Снимок экрана 2024-02-10 в 16 25 16](https://github.com/nuxt/nuxt/assets/148229590/44f5e213-f513-49ac-9d6b-ec537b6d4434)

trying to go back from page, but getting error: Failed to fetch dynamically imported module

router.back() && router.go(-1) do the same

Unfortunately reproduction fails to show the error in full, but here's what I realized from the errors -

```
<template> 
  <div class="articles__main__container"> 
    <UIArticle v-if="articles" v-for="article in articles.data" :article="article"> </UIArticle> 
  </div>
</template>

<style scoped lang="scss"> @import url("~/assets/main/pages/index/index.scss"); </style>
```

By removing `@import url("~/assets/main/pages/index/index.scss");` the `Failed to fetch dynamically imported module` error disappears

### Additional context

Browser backward button call the same error, tried on different browsers - same

I use the <a> tag rather than the nuxt-link tag

**Comment by mirikqq** [comment]
And so here is the reproduction - https://stackblitz.com/edit/github-cdznxw?file=pages%2Ftest1.vue As I understand the problem is that after <a> does not save the state of window.history and therefore no access to useRouter, but the problem is that I do not need NuxtLink, I can only use <a>, what to do in this case?

**Comment by mirikqq** [comment]
Unfortunately reproduction fails to show the error in full, but here's what I realized from the errors -

`<template> <div class="articles__main__container"> <UIArticle v-if="articles" v-for="article in articles.data" :article="article"> </UIArticle> </div> </div> </template>

<style scoped lang="scss"> @import url("~/assets/main/pages/index/index.scss"); </style>`

By removing `@import url("~/assets/main/pages/index/index.scss");` the `Failed to fetch dynamically imported module` error disappears

**Comment by mirikqq** [comment]
config: 
```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
	builder: "vite",
	ssr: true,
	css: ["~/assets/scss/index.scss"],
	runtimeConfig: {
		public: {
			apiUrl: process.env.NUXT_PUBLIC_API_URL,
		},
	},
	devtools: {
		enabled: true,

		timeline: {
			enabled: true,
		},
	},
	modules: [
		"@element-plus/nuxt",
		"@vueuse/nuxt",
		"nuxt-icons",
		"vue-yandex-maps/nuxt",
		"@nuxtjs/device",
	],
	device: {
		refreshOnResize: true,
	},
	vite: {
		css: {
			preprocessorOptions: {
				scss: {
					additionalData: `
						@import "~/assets/scss/_vars.scss";\n
						@import "~/assets/scss/_mixins.scss";\n
					`,
				},
			},
		},
	},
})

```

**Comment by khalidhardiansyah** [comment]
How did you resolve this problem?

**Comment by yeasin2002** [comment]
same issues, how did you fixed that ?

**Comment by matthew-dean** [comment]
I've been seeing this problem periodically ("Failed to fetch dynamically imported module"), and a reload usually resolves it, but it didn't use to happen. I think it might be related to another problem, which is that my production builds stopped working, but only in a particular dev environment. I tracked it down to `useRouter()` returning undefined even if called within a component. I think Nuxt has a really hard-to-track-down race condition related to vue-router.

**Comment by OrbisK** [comment]
@matthew-dean can you reproduce this with a minimal reproduction? I think you should open this as separate issue 😄
