### ISSUE TITLE
3.10.x: `nuxt build` creates vue files in `.nuxt/dist/server/_nuxt` folder

### ISSUE THREAD

**Issue by MickL** [nuxt/nuxt#25724]
### Environment

```
- Operating System: Darwin
- Node Version:     v21.2.0
- Nuxt Version:     3.10.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  bun@1.0.25
- Builder:          -
- User Config:      devtools, css, modules, runtimeConfig, image, build, i18n, ignore, nitro, routeRules, security, vite
- Runtime Modules:  @nuxtjs/i18n@8.1.0, @nuxt/image@1.3.0, nuxt-icon@0.6.8, nuxt-security@1.1.1
- Build Modules:    -
```

### Reproduction

-

### Describe the bug

With `3.10.0` and `3.10.1` I get an error at the end of `nuxt build`: `ERROR  RollupError: At least one <template> or <script> is required in a single file component`, with `3.9.3` everything is fine.

Unfortunately I cant reproduce this in the sandbox but I already tried to debug this for hours. I nailed it down to one of my ~10 components: If it contains a `<style>` tag with ANY content (even just a comment). Weirdly when I delete the content of the `<script>` tag I can have styles:

Throws the error:

```vue
<script setup lang="ts">
// hello
</script>

<template>
  hello
</template>

<style lang="scss">
// hello
</style>
```

Doesnt throw an error:

```vue
<script setup lang="ts">
// hello
</script>

<template>
  hello
</template>

<style lang="scss"></style>
```

Doesnt throw an error:

```vue
<script setup lang="ts"></script>

<template>
  hello
</template>

<style lang="scss">
// hello
</style>
```

It also only happens with this one component named `overlay.vue`. I feel like I am getting crazy or something but this seems to make absolutely no sense.

Full error:

```
 ERROR  RollupError: At least one <template> or <script> is required in a single file component.         nitro 9:00:59 PM


undefined


 ERROR  At least one <template> or <script> is required in a single file component.                            9:00:59 PM

  at error (node_modules/rollup/dist/es/shared/parseAst.js:337:30)
  at Object.error (node_modules/rollup/dist/es/shared/node-entry.js:18507:20)
  at Object.error (node_modules/rollup/dist/es/shared/node-entry.js:17616:42)
  at node_modules/rollup-plugin-vue/dist/sfc.js:22:49
  at Array.forEach (<anonymous>)
  at Object.transformSFCEntry (node_modules/rollup-plugin-vue/dist/sfc.js:22:16)
  at Object.transform (node_modules/rollup-plugin-vue/dist/index.js:99:38)
  at node_modules/rollup/dist/es/shared/node-entry.js:18692:40 



 ERROR  At least one <template> or <script> is required in a single file component.                            9:00:59 PM

error Command failed with exit code 1.
```

**Comment by danielroe** [comment]
This is unlikely to be an issue with Nuxt - `rollup-plugin-vue` is not used by Nuxt or Nitro and is what is throwing your error.

**Comment by MickL** [comment]
I am not 100% sure about that. Yes this plugin throws the error BUT I disabled the plugin and realized there is exactly one .vue file in the folder `.nuxt/dist/server/_nuxt` which is exactly the file I debugged to be the one creates the error. I guess there shouldnt be any vue file in this folder which one mean that there actually is a bug within Nuxt.

**Comment by danielroe** [comment]
Interesting. Have you customised `assetFileNames` by any chance?

**Comment by MickL** [comment]
I did not

**Comment by danielroe** [comment]
I probably can't look into this without a reproduction or more info.

**Comment by MickL** [comment]
I can try to dig more into this and make this reproducable.

**Comment by MickL** [comment]
@danielroe So it took me a few hours of removing more and more stuff from my app until I ended in an empty app and I realized:

This happens on a blank empty app created with `nuxi init` and just a single index page and a single component in it! If the component has a script with `lang=ts` and a style tag (both with ANY content) a vue file is in the `.nuxt/dist/server` folder!

Since StackBlitz doesnt seem to work, here is the repo: https://github.com/MickL/nuxt-bug

**Comment by danielroe** [comment]
When you say that StackBlitz doesn't work, what do you mean?

**Comment by danielroe** [comment]
I can't reproduce with that repo.

Here's a StackBlitz created from it - seemingly working fine: https://stackblitz.com/edit/github-iqamf7.

Could you share any more info about your setup?

**Comment by MickL** [comment]
I used bun install if that changed anything. My specs are at the very top. I think #25690 could be the same issue

**Comment by MickL** [comment]
> When you say that StackBlitz doesn't work, what do you mean?

I meant that the links on the Nuxt website (the two I posted above) both dont start and produce errors.

So I double checked on another machine. I downloaded my repo, run npm install and then npm run buld. If I check the folder `` I see (as I described) there is a vue file which is probably supposed to be a js file:

<img width="612" alt="Bildschirmfoto 2024-02-12 um 23 31 32" src="https://github.com/nuxt/nuxt/assets/5103210/abed89e6-66f5-430c-a19d-e8233d2042cd">

**Comment by danielroe** [comment]
You're quite right; it is reproducible there - I was checking `.output`, not `.nuxt`.

**Comment by KresimirCosic** [comment]
I am not sure if this is causing me problems now - I updated my packages to latest (all of them), and somehow I get an error:

`cannot find module './stringify'` (module in question is `qs`, which is only used by Strapi module as far as I can tell)

This only happens in dev mode, build is running fine. When I don't include it in the configuration everything works.

If I keep use the Nuxt `^3.10.1` version I have no problems. Does any of this ring a bell?
