### ISSUE TITLE
Vue plugin in Nuxt Module not being called on client

### ISSUE THREAD

**Issue by VividLemon** [nuxt/nuxt#25735]
### Environment

Nuxt project info:                                                                                                                                                           12:06:29 PM

------------------------------
- Operating System: Linux
- Node Version:     v20.7.0
- Nuxt Version:     3.10.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.1.0
- Builder:          -
- User Config:      modules, css
- Runtime Modules:  @bootstrap-vue-next/nuxt@0.16.1
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/bcorey85/bootstrap-vue-next-modal-debug

### Describe the bug

Originally posted here https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/1758

There is an issue I am having with this nuxt plugin. 
The flow goes
https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/packages/nuxt/src/module.ts#L22 -> https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/packages/nuxt/src/runtime/plugins/createBootstrap.ts -> https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/packages/bootstrap-vue-next/src/BootstrapVue.ts#L122 -> https://github.com/bootstrap-vue-next/bootstrap-vue-next/tree/main/packages/bootstrap-vue-next/src/plugins

Using the following resources
https://nuxt.com/docs/guide/going-further/modules#injecting-plugins-with-addplugin
& https://nuxt.com/docs/guide/directory-structure/plugins#vue-plugins

Something to note, on server, the plugin is registered and used. If you add `{{ modal }}` to the template in the reproduction, you can see that on initial page load, it will send over the correct data.

To add a little bit of complexity, the issue seems intermittent. Sometimes it will appear, and sometimes it wont. In order to get it to not appear, I delete .nuxt & node_modules, then redownload and run server. 

I suspect I'm having an issue with creating the nuxt module. Certainly it would be more ideal to do `defineNuxtPlugin(() => { return {provide: {}}})`, but I want to reuse as much code as possible. The "plugins" simply provide some data, that is captured by composables such as `const modalManagerPlugin = inject(modalManagerPluginKey)`. So, the return {provide} isn't quite ideal, since we want to reuse the composables from the main package.

Although, I wonder if these plugins should be client only, regardless, the client is the source of the issue (as in addition to the composable not working, doing {{modal}} causes a hydration mismatch)

### Logs

```shell-script
[Vue warn]: injection "Symbol(modalManagerPlugin)" not found. 
[Vue warn]: injection "Symbol(modalManagerPlugin)" not found.
```

**Comment by danielroe** [comment]
~> https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1761

**Comment by VividLemon** [comment]
> ~> [bootstrap-vue-next/bootstrap-vue-next#1761](https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1761)

Thank you very much for this addition
