### ISSUE TITLE
Will accessing the homepage load CSS and JavaScript files from other sub pages?

### ISSUE THREAD

**Issue by bbhxwl** [nuxt/nuxt#25733]
### Environment

  "devDependencies": {
    "@ant-design-vue/nuxt": "^1.4.1",
    "@element-plus/nuxt": "^1.0.7",
    "@formkit/auto-animate": "^0.8.1",
    "@nuxt/ui-pro": "^0.7.5",
    "@nuxtjs/color-mode": "^3.3.2",
    "@nuxtjs/device": "^3.1.1",
    "@nuxtjs/tailwindcss": "^6.11.2",
    "@pinia-plugin-persistedstate/nuxt": "^1.2.0",
    "@pinia/nuxt": "^0.5.1",
    "@tweenjs/tween.js": "^23.1.1",
    "@types/three": "^0.161.2",
    "ant-design-vue": "^4.1.2",
    "dayjs-nuxt": "^2.1.9",
    "element-plus": "^2.5.3",
    "jwt-decode": "^4.0.0",
    "mqtt": "^5.3.5",
    "nuxt": "^3.10.1",
    "pinia": "^2.1.7",
    "three": "^0.161.0",
    "vue": "^3.4.14",
    "vue-router": "^4.2.5"
  },

### Reproduction

I will enter the homepage, index. vue, and the page resources will load the data of my sub page 3DBuilding. vue? Why?

index.vue 
```
<script setup lang="ts">

</script>

<template>

  <div  class="text-center">
    <el-button >add</el-button>
    <UDivider></UDivider>
    <UAlert icon="i-heroicons-command-line" title="111"></UAlert>
  </div>

</template>

<style scoped>

</style>
```

### Describe the bug

![38NMG3YQJ@ $M1J{$(E8A{9](https://github.com/nuxt/nuxt/assets/26525599/e3f81e9a-58ce-464a-94c4-ec84625d7f24)

**Comment by manniL** [comment]
If you use prefetching (which NuxtLink does by default) then yes, but only after the resources for the current pages.

**Comment by bbhxwl** [comment]
> If you use prefetching (which NuxtLink does by default) then yes, but only after the resources for the current pages.

How can I optimize accessing resources on a page to minimize loading?

**Comment by bbhxwl** [comment]
> If you use prefetching (which NuxtLink does by default) then yes, but only after the resources for the current pages.

From my homepage, no redirection was used

**Comment by bbhxwl** [comment]
> If you use prefetching (which NuxtLink does by default) then yes, but only after the resources for the current pages.

It's strange that none of the code in my project uses NuxtLink. Is it the latest version bug?

**Comment by bbhxwl** [comment]
Please check my demo. It needs to be built and run to view. If you visit the homepage, it will load 3DBuilding.*****.js and 3DBuilding.*****.css


[ADLDataDisplay.zip](https://github.com/nuxt/nuxt/files/14231163/ADLDataDisplay.zip)

**Comment by bbhxwl** [comment]
![image](https://github.com/nuxt/nuxt/assets/26525599/e0ccd5df-8017-4908-80e3-c7414084d414)

**Comment by manniL** [comment]
First, providing your whole project is not a reproduction.

As mentioned before, this is the `prefetch` feature of the `<NuxtLink>` component:

> When a [`<NuxtLink>`](https://nuxt.com/docs/api/components/nuxt-link) enters the viewport on the client side, Nuxt will automatically `prefetch` components and payload (generated pages) of the linked pages ahead of time, resulting in faster navigation.

If you don't want that, you can e.g. add the `no-prefetch` attribute to the links

More [in the docs](https://nuxt.com/docs/getting-started/routing#navigation)

**Comment by bbhxwl** [comment]
> First, providing your whole project is not a reproduction.
> 
> As mentioned before, this is the `prefetch` feature of the `<NuxtLink>` component:
> 
> > When a [`<NuxtLink>`](https://nuxt.com/docs/api/components/nuxt-link) enters the viewport on the client side, Nuxt will automatically `prefetch` components and payload (generated pages) of the linked pages ahead of time, resulting in faster navigation.
> 
> If you don't want that, you can e.g. add the `no-prefetch` attribute to the links
> 
> More in the [routing docs](https://nuxt.com/docs/getting-started/routing#navigation) and the [NuxtLink docs](https://nuxt.com/docs/api/components/nuxt-link#nuxtlink)

<NuxtLink>
I haven't used this component before.

**Comment by bbhxwl** [comment]
> First, providing your whole project is not a reproduction.
> 
> As mentioned before, this is the `prefetch` feature of the `<NuxtLink>` component:
> 
> > When a [`<NuxtLink>`](https://nuxt.com/docs/api/components/nuxt-link) enters the viewport on the client side, Nuxt will automatically `prefetch` components and payload (generated pages) of the linked pages ahead of time, resulting in faster navigation.
> 
> If you don't want that, you can e.g. add the `no-prefetch` attribute to the links
> 
> More in the [routing docs](https://nuxt.com/docs/getting-started/routing#navigation) and the [NuxtLink docs](https://nuxt.com/docs/api/components/nuxt-link#nuxtlink)

I haven't used this component in all of my code, but after compilation, it does exist. Why? I only have 2 pages, neither of which has a jump.


![image](https://github.com/nuxt/nuxt/assets/26525599/a228d56c-1e4d-4647-82ae-1885822ca7c7)

**Comment by manniL** [comment]
Because your UI library uses it under the hood. In this case, the `Button` component (7th result in search)

**Comment by bbhxwl** [comment]
> Because your UI library uses it under the hood. In this case, the `Button` component (7th result in search)

Will the button load even if it does not specify a jump route? This principle is so complex.
