### ISSUE TITLE
Is there a way for nuxt3 to develop websites with higher efficiency? CSS and JavaScript are both uncompressed and will load them all.

### ISSUE THREAD

**Issue by bbhxwl** [nuxt/nuxt#25738]
Is there a way for nuxt3 to develop websites with higher efficiency? CSS and JavaScript are both uncompressed and will load them all.
I have found that both the pages I created myself and those developed by Nuxt have the same issue. Can this be considered poor performance? CSS and JavaScript are both uncompressed maximum scripts, and they load unused web page resources in advance, even if nuxtlink is not used

https://github.com/nuxt/nuxt/issues/25733

![image](https://github.com/nuxt/nuxt/assets/26525599/51861f5f-66fe-45e0-8940-b93c4d6291b3)

**Comment by manniL** [comment]
You have pretty-print enabled in the devtools (see the blue { } at the bottom). ☺️ 
Minification is applied by default
