### ISSUE TITLE
Image error bug

### ISSUE THREAD

**Issue by wangrunze2023** [nuxt/nuxt#25730]
### Environment
`<img src="~/assets/image/searchBg.jpg" alt=""/>`

chunk-SOI3BFCQ.js?v=091eb3ff:1759 [Vue warn]: Hydration attribute mismatch on <img src=​"/​_nuxt/​assets/​image/​searchBg.jpg?t=1707570632814" alt>​ 
  - rendered on server: src="/_nuxt/assets/image/searchBg.jpg?t=1707570632814"
  - expected on client: src="/_nuxt/assets/image/searchBg.jpg?t=1707570632813"
  Note: this mismatch is check-only. The DOM will not be rectified in production due to performance overhead.
  You should fix the source of the mismatch. 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <Anonymous key="/search" vnode= {__v_isVNode: true, __v_skip: true, type: {…}, props: {…}, key: null, …} route= {fullPath: '/search?title=dd', hash: '', query: {…}, name: 'search', path: '/search', …}  ... > 
  at <BaseTransition onAfterLeave= [ƒ] mode="out-in" appear=false  ... > 
  at <Transition onAfterLeave= [ƒ] name="page" mode="out-in" > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <Default ref=Ref< undefined > > 
  at <LayoutLoader key="default" layoutProps= {ref: RefImpl} name="default" > 
  at <NuxtLayoutProvider layoutProps= {ref: RefImpl} key="default" name="default"  ... > 
  at <NuxtLayout> 
  at <App key=3 > 
  at <NuxtRoot>

### Reproduction

chunk-SOI3BFCQ.js?v=091eb3ff:1759 [Vue warn]: Hydration attribute mismatch on <img src=​"/​_nuxt/​assets/​image/​searchBg.jpg?t=1707570632814" alt>​ 
  - rendered on server: src="/_nuxt/assets/image/searchBg.jpg?t=1707570632814"
  - expected on client: src="/_nuxt/assets/image/searchBg.jpg?t=1707570632813"
  Note: this mismatch is check-only. The DOM will not be rectified in production due to performance overhead.
  You should fix the source of the mismatch. 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <Anonymous key="/search" vnode= {__v_isVNode: true, __v_skip: true, type: {…}, props: {…}, key: null, …} route= {fullPath: '/search?title=dd', hash: '', query: {…}, name: 'search', path: '/search', …}  ... > 
  at <BaseTransition onAfterLeave= [ƒ] mode="out-in" appear=false  ... > 
  at <Transition onAfterLeave= [ƒ] name="page" mode="out-in" > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <Default ref=Ref< undefined > > 
  at <LayoutLoader key="default" layoutProps= {ref: RefImpl} name="default" > 
  at <NuxtLayoutProvider layoutProps= {ref: RefImpl} key="default" name="default"  ... > 
  at <NuxtLayout> 
  at <App key=3 > 
  at <NuxtRoot>

### Describe the bug

chunk-SOI3BFCQ.js?v=091eb3ff:1759 [Vue warn]: Hydration attribute mismatch on <img src=​"/​_nuxt/​assets/​image/​searchBg.jpg?t=1707570632814" alt>​ 
  - rendered on server: src="/_nuxt/assets/image/searchBg.jpg?t=1707570632814"
  - expected on client: src="/_nuxt/assets/image/searchBg.jpg?t=1707570632813"
  Note: this mismatch is check-only. The DOM will not be rectified in production due to performance overhead.
  You should fix the source of the mismatch. 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <Anonymous key="/search" vnode= {__v_isVNode: true, __v_skip: true, type: {…}, props: {…}, key: null, …} route= {fullPath: '/search?title=dd', hash: '', query: {…}, name: 'search', path: '/search', …}  ... > 
  at <BaseTransition onAfterLeave= [ƒ] mode="out-in" appear=false  ... > 
  at <Transition onAfterLeave= [ƒ] name="page" mode="out-in" > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <Default ref=Ref< undefined > > 
  at <LayoutLoader key="default" layoutProps= {ref: RefImpl} name="default" > 
  at <NuxtLayoutProvider layoutProps= {ref: RefImpl} key="default" name="default"  ... > 
  at <NuxtLayout> 
  at <App key=3 > 
  at <NuxtRoot>

### Additional context

chunk-SOI3BFCQ.js?v=091eb3ff:1759 [Vue warn]: Hydration attribute mismatch on <img src=​"/​_nuxt/​assets/​image/​searchBg.jpg?t=1707570632814" alt>​ 
  - rendered on server: src="/_nuxt/assets/image/searchBg.jpg?t=1707570632814"
  - expected on client: src="/_nuxt/assets/image/searchBg.jpg?t=1707570632813"
  Note: this mismatch is check-only. The DOM will not be rectified in production due to performance overhead.
  You should fix the source of the mismatch. 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <Anonymous key="/search" vnode= {__v_isVNode: true, __v_skip: true, type: {…}, props: {…}, key: null, …} route= {fullPath: '/search?title=dd', hash: '', query: {…}, name: 'search', path: '/search', …}  ... > 
  at <BaseTransition onAfterLeave= [ƒ] mode="out-in" appear=false  ... > 
  at <Transition onAfterLeave= [ƒ] name="page" mode="out-in" > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <Default ref=Ref< undefined > > 
  at <LayoutLoader key="default" layoutProps= {ref: RefImpl} name="default" > 
  at <NuxtLayoutProvider layoutProps= {ref: RefImpl} key="default" name="default"  ... > 
  at <NuxtLayout> 
  at <App key=3 > 
  at <NuxtRoot>

**Comment by wangrunze2023** [comment]
<img src="~/assets/image/searchBg.jpg" alt=""/>

**Comment by madebyfabian** [comment]
Can be closed due to no response & no reproduction.

@wangrunze2023 In the future, could you please try to create more helpful issues and actually answer the issue template's questions + provide a working reproduction? That would be awesome 😊
