### ISSUE TITLE
Opening redirected URL (through routeRules) does not redirect and breaks page

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt#25743]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.10.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, routeRules
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-issues-25743

1. Click the link on the index page
2. See error in the console and no content nor the redirect happening

`[Vue warn]: Component is missing template or render function.`

### Describe the bug

When adding a redirect in the routeRules, e.g. `routeRules: { '/support-me/': { redirect: { to: '/sponsors/', statusCode: 301 } } }` and then trying to directly access the page through the browser, the redirect does not happen and the page breaks instead.

### Additional context

Related PR: https://github.com/nuxt/nuxt/pull/25391

**Comment by danielroe** [comment]
Weirdly, this works just fine when I download and run locally.

**Comment by danielroe** [comment]
nitro reproduction: https://stackblitz.com/edit/github-yjju3h?file=nitro.config.ts,routes/index.ts,routes/sponsors.ts

**Comment by danielroe** [comment]
Let's track in https://github.com/unjs/nitro/issues/2146.

**Comment by danielroe** [comment]
Ah - nice find. But it also seems to be reproducible in nitro on its own.

**Comment by danielroe** [comment]
Also note https://github.com/nuxt/nuxt/issues/23813, which might be related (haven't investigated).
