### ISSUE TITLE
Unable to get the full error message when using useFetch() or $fetch

### ISSUE THREAD

**Issue by martinszeltins** [nuxt/nuxt#25745]
### Environment

Stackblitz

```
Working directory: /home/projects/nuxt-starter-t11enq
Nuxt project info:
------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.10.1
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, imports
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Reproduction

https://stackblitz.com/edit/nuxt-starter-5g2kqi?file=app.vue

### Describe the bug

I have a server api route that throws an error if something goes wrong. The error includes custom fields like `validation`, `code` etc. that the 3rd party backend actually sends back in the HTTP response. My Nuxt server api route contacts that 3rd party backend API and receives the HTTP response. But when I try to use `useFetch()` or `$fetch` from my Vue components then I am unable to access all these error fields.

In the real world this would be an Apollo GraphQL request that would throw the error in the server api route that I then need to be able to access in the Vue component but the FetchError simply does not seem to include all that information from the original error / http response.

My server api throws this error:

```ts
export default defineEventHandler(() => {
    const isRequestValid = false

    if (isRequestValid) {
        return {
            users: [{ id: 1, username: 'John Doe' }]
        }
    } else {
        throw {
            name: 'Users',
            cause: 'Could not load users',
            code: 'USERS_LOAD_ERROR',
            guiltyDeveloper: 'John Doe',
            validation: {
                username: 'Username is required',
            }
        }
    }
})
```

And then in my Vue component I try to access this error but I do not see the full error object:

```vue
<template>
  <div>
    data: <pre>{{ data }}</pre>
    error: <pre>{{ error }}</pre>
  </div>
</template>

<script setup lang="ts">
    const { data, error, refresh } = await useFetch('/api/users', { method: 'POST', lazy: true })

    console.log(data.value)
    console.log(error.value)

    onMounted(async () => {
        setTimeout(async () => {
            await refresh()
    
            console.log(data.value)
            console.log(error.value)
        }, 5000)

        try {
            await $fetch('/api/users', { method: 'POST' })
        } catch (exception) {
            console.log(exception)
            console.log(exception.data)
            console.log(exception.response)
        }
    })
</script>
```

The most that I see is this:

```ts
{
    "_data": {
        "url": "/api/users",
        "statusCode": 500,
        "statusMessage": "",
        "message": "Error",
        "stack": "<pre><span class=\"stack internal\">at createError (./node_modules/.pnpm/h3@1.10.1/node_modules/h3/dist/index.mjs:79:15)</span>\n<span class=\"stack internal\">at Server.toNodeHandle (./node_modules/.pnpm/h3@1.10.1/node_modules/h3/dist/index.mjs:1909:21)</span>\n<span class=\"stack internal\">at process.processTicksAndRejections (node:internal/process/task_queues:95:5)</span></pre>"
    }
}
```

No matter what I do, I am unable to access the full raw HTTP response. Where is my `validation` field? Or where is the `guiltyDeveloper` field and `code` and `cause`?

**Comment by manniL** [comment]
You ideally should use `createError` when throwing in event handlers.

```ts
 throw createError({
      statusCode: 422,
      data: {
        name: 'Users',
        cause: 'Could not load users',
        code: 'USERS_LOAD_ERROR',
        guiltyDeveloper: 'John Doe',
        validation: {
          username: 'Username is required',
        },
      },
    });
```

**Comment by martinszeltins** [comment]
> You ideally should use `createError` when throwing in event handlers.
> 
> ```ts
>  throw createError({
>       statusCode: 422,
>       data: {
>         name: 'Users',
>         cause: 'Could not load users',
>         code: 'USERS_LOAD_ERROR',
>         guiltyDeveloper: 'John Doe',
>         validation: {
>           username: 'Username is required',
>         },
>       },
>     });
> ```

Thank you @manniL that worked! I don't recall this being mentioned in the docs anywhere. So the trick is to add a `data` property in createError().

**Comment by manniL** [comment]
This is [covered here](https://nuxt.com/docs/getting-started/error-handling#createerror) ☺️
