### ISSUE TITLE
"Secret" `runtimeConfig` shown during window reload

### ISSUE THREAD

**Issue by agreedSkiing** [nuxt/nuxt#25740]
### Environment

> npx nuxi info
Working directory: /home/eriase/Repositories/nuxt-app
Nuxt project info:

------------------------------
- Operating System: Linux
- Node Version:     v20.10.0
- Nuxt Version:     3.10.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, runtimeConfig
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Don't have a repo for this so just providing a tar.gz file instead
[nuxt-app.tar.gz](https://github.com/nuxt/nuxt/files/14231829/nuxt-app.tar.gz)

### Describe the bug

After building the application and running `npm run preview` and then refreshing the page I can see the config.hello value flashing before being de-loaded from the homepage.

**Comment by manniL** [comment]
That's correct as the "private" runtimeConfig is available on the server side. Rendering it in a template will leak it when doing the initial request.
