### ISSUE TITLE
Nuxt3 strips body in POST request with transfer-encoding: chunked (http 1.1 request).

### ISSUE THREAD

**Issue by benlavalley** [nuxt/nuxt#25746]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.19.0
- Nuxt Version:     3.10.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Reproduced here:
https://github.com/benlavalley/nuxttransferencoding/commit/64633ee29d5aee4ded87ca488a65815f6f0b1de7

Notes are in the commit -- it is just the latest nuxt init app, with a single additional file /server/api/chunkedtest.ts that simply logs the inbound body, headers, and http version.

### Describe the bug

HTTP requests sent to Nuxt3 are having their body of inbound POST requests if they are received with transfer-encoding: chunked headers. 

The same requests can be processed just fine by barebones Connect / Express. 

This request does NOT work:
```
curl --location 'http://localhost:3000/api/chunkedtest' \
--header 'Content-Type: application/json; charset=utf-8' \
--header 'transfer-encoding: chunked' \
--data '{"testkey":"testvalue","testkey2":"testvalue2"}'
```

This request DOES:
```
curl --location 'http://localhost:3000/api/chunkedtest' \
--header 'Content-Type: application/json; charset=utf-8' \
--header 'Content-Length: 47' \
--data '{"testkey":"testvalue","testkey2":"testvalue2"}'
```
I've also sent the requests with Postman and seen no difference in behavior.

Content of /server/api/chunkedtest.ts which is the only addition to the initialized Nuxt3 app:
```
export default defineEventHandler(async (event) => {
	try {
	  const body = await readBody(event);
	  console.log('NUXT received request with headers: ', event.headers)
	  console.log('NUXT received request httpVersion: ', event.node.req.httpVersion)
	  console.log('NUXT received request with  BODY: ', body)
	  return true;
	} catch (error: any) {
		console.log('Error in /api/test: ', error.message)
	  throw new Error('Error in /api/test: ')
	}
  });
```

I have no control over the request Nuxt receives unfortunately - I am using Netlify's Edge Functions so I can begin supporting Server-Side events in my app, and it forces this header with no way to send with usual content-length header.

**I dug a little deeper (I have probably put 10 hours into this one already) and was actually able to narrow the issue down to H3 - standing up a basic H3 server sees it strip the body with transfer-encoding:chunked.** I dug a little deeper and the issue may even be another package used further upstream than H3.

I am going to write up an issue for H3 and will relay their response here - a lot of CDNs force this transfer-encoding:chunked and I'd imagine other folks using Nuxt might be running into this issue.

### Logs

```shell-script
Success processing http 1.1 request with a JSON body and standard "content-length" header:

NUXT received request httpVersion:  1.1
NUXT received request with  BODY:  { testkey: 'testvalue', testkey2: 'testvalue2' }
NUXT received request with headers:  HeadersList {
  cookies: null,
  [Symbol(headers map)]: Map(10) {
    'content-type' => { name: 'content-type', value: 'application/json; charset=utf-8' },
    'content-length' => { name: 'content-length', value: '47' },
    'user-agent' => { name: 'user-agent', value: 'PostmanRuntime/7.36.1' },
    'accept' => { name: 'accept', value: '*/*' },
    'host' => { name: 'host', value: 'localhost:3000' },
    'accept-encoding' => { name: 'accept-encoding', value: 'gzip, deflate, br' },
    'connection' => { name: 'connection', value: 'close' },
    'x-forwarded-for' => { name: 'x-forwarded-for', value: '127.0.0.1' },
    'x-forwarded-port' => { name: 'x-forwarded-port', value: '53957' },
    'x-forwarded-proto' => { name: 'x-forwarded-proto', value: 'IPv4' }
  },
  [Symbol(headers map sorted)]: null
}

No body to process received with "transfer-encoding:chunked" header:

NUXT received request httpVersion:  1.1
NUXT received request with  BODY:  undefined
NUXT received request with headers:  HeadersList {
  cookies: null,
  [Symbol(headers map)]: Map(10) {
    'content-type' => { name: 'content-type', value: 'application/json; charset=utf-8' },
    'user-agent' => { name: 'user-agent', value: 'PostmanRuntime/7.36.1' },
    'accept' => { name: 'accept', value: '*/*' },
    'host' => { name: 'host', value: 'localhost:3000' },
    'accept-encoding' => { name: 'accept-encoding', value: 'gzip, deflate, br' },
    'connection' => { name: 'connection', value: 'close' },
    'content-length' => { name: 'content-length', value: '47' },
    'x-forwarded-for' => { name: 'x-forwarded-for', value: '127.0.0.1' },
    'x-forwarded-port' => { name: 'x-forwarded-port', value: '53850' },
    'x-forwarded-proto' => { name: 'x-forwarded-proto', value: 'IPv4' }
  },
  [Symbol(headers map sorted)]: null
}
```

**Comment by danielroe** [comment]
Thank you for the triage. Please do let me know when you have upstream issues created so we can link them 🙏

**Comment by benlavalley** [comment]
> Thank you for the triage. Please do let me know when you have upstream issues created so we can link them 🙏

boom! https://github.com/unjs/h3/issues/651

**Comment by danielroe** [comment]
Thank you! ❤️ 

Let's close this issue to track there. Nice debugging.
