### ISSUE TITLE
The requested module 'node:stream' does not provide an export named 'getDefaultHighWaterMark'

### ISSUE THREAD

**Issue by ironytr** [nuxt/nuxt#25757]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v19.4.0
- Nuxt Version:     -
- CLI Version:      3.9.1
- Nitro Version:    -
- Package Manager:  npm@9.2.0
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

npx nuxi init new-project

### Describe the bug

```
 ERROR  The requested module 'node:stream' does not provide an export named 'getDefaultHighWaterMark'      10:14:12 PM

  import {PassThrough as PassThroughStream, getDefaultHighWaterMark} from 'node:stream';
  ^^^^^^^^^^^^^^^^^^^^^^^
  SyntaxError: The requested module 'node:stream' does not provide an export named 'getDefaultHighWaterMark'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
```

### Additional context

 pn why @sindresorhus/merge-streams
checkout out @sindresorhus/merge-streams 2.2.0 20minutes before updated.
`dependencies:
nuxt 3.10.1
├─┬ @nuxt/devtools 1.0.8
│ ├─┬ @nuxt/devtools-kit 1.0.8
│ │ └─┬ @nuxt/kit 3.10.1
│ │   └─┬ globby 14.0.1
│ │     └── @sindresorhus/merge-streams 2.2.0
│ ├─┬ @nuxt/kit 3.10.1
│ │ └─┬ globby 14.0.1
│ │   └── @sindresorhus/merge-streams 2.2.0
│ └─┬ vite-plugin-inspect 0.8.3
│   └─┬ @nuxt/kit 3.10.1 peer
│     └─┬ globby 14.0.1
│       └── @sindresorhus/merge-streams 2.2.0
├─┬ @nuxt/kit 3.10.1
│ └─┬ globby 14.0.1
│   └── @sindresorhus/merge-streams 2.2.0
├─┬ @nuxt/telemetry 2.5.3
│ └─┬ @nuxt/kit 3.10.1
│   └─┬ globby 14.0.1
│     └── @sindresorhus/merge-streams 2.2.0
├─┬ @nuxt/vite-builder 3.10.1
│ └─┬ @nuxt/kit 3.10.1
│   └─┬ globby 14.0.1
│     └── @sindresorhus/merge-streams 2.2.0
├─┬ globby 14.0.1
│ └── @sindresorhus/merge-streams 2.2.0
└─┬ nitropack 2.8.1
  └─┬ globby 14.0.1
    └── @sindresorhus/merge-streams 2.2.0`

**Comment by danielroe** [comment]
That export was added in Node 19.9.0. I would recommend using Node 20 in any case.

But I can't reproduce this with Node 18.

**Comment by ironytr** [comment]
upgrading node to v20 solved.

**Comment by flaviooria** [comment]
Thank you for my it's work 👌🏽
