### ISSUE TITLE
ModuleOptions are not inferred correctly

### ISSUE THREAD

**Issue by rinux55** [nuxt/nuxt#25767]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.8.1
- Nuxt Version:     3.10.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.1.0
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/~/github.com/rinux55/nuxt-module-types 

You can see that `nuxt.options.publicRuntimeConfig` does not contain the `myModule` with `myComplexType: false | {a : string}`, in `module.ts:23`

### Describe the bug

When creating a Nuxt Module, according to the docs (https://nuxt.com/docs/guide/going-further/runtime-config#typing-runtime-config) the module options are generated with untyped. It seems to generate the types from the `defaults` object. 

If you have more complex types, which cannot be inferred from the `defaults` object, it should be possible to declare an `index.d.ts`, according to the docs.

I am not able to get this to work. I've created a minimal reproduction. In the reproduction, I've added the `index.ts` to `/src`, but I've also tried adding it to `/playground` or `/`.

**Comment by danielroe** [comment]
Just creating an `index.d.ts` isn't enough.

I've updated your reproduction to show how to make it work:

- https://github.com/rinux55/nuxt-module-types/pull/1

**Comment by rinux55** [comment]
Thanks for your suggestion Daniel, this seems to work!
