### ISSUE TITLE
Ant Design Vue - Dropdown menu item group not rendered

### ISSUE THREAD

**Issue by anhthang** [nuxt/nuxt#25776]
### Environment

- Operating System: `Darwin`
- Node Version:     `v21.6.1`
- Nuxt Version:     `3.10.1`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `yarn@1.22.21`
- Builder:          `-`
- User Config:      `build`, `modules`
- Runtime Modules:  `@ant-design-vue/nuxt@1.4.1`
- Build Modules:    `-`

### Reproduction

https://codesandbox.io/p/devbox/nuxt-minimal-cvvr79?file=%2Fapp.vue

### Describe the bug

Hi, I'm using Nuxt with Ant Design Vue for my project, but the menu item group is not rendered

### Additional context

I also tested without Nuxt, only `ant-design-vue` and it works. Here is codesandbox for that: https://codesandbox.io/p/sandbox/antd-vue-minimal-jyvy6h?file=%2Fsrc%2FApp.vue%3A14%2C12

**Comment by danielroe** [comment]
Would you check with Vue SSR (without Nuxt)?

https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter

**Comment by anhthang** [comment]
Hi @danielroe 

I have tested and it's not rendered

<img width="1732" alt="Screenshot 2024-02-14 at 12 56 46 PM" src="https://github.com/nuxt/nuxt/assets/10458061/f96d4bfa-7137-4ed2-8f7c-bf7924c76f7a">

So, is it Vue SSR issue?

**Comment by danielroe** [comment]
Thank you for checking. I would guess it's probably an issue with Ant Design Vue. I would suggest raising an issue there first, and if they think it's a Vue SSR issue then you can take things to vuejs/core.

**Comment by anhthang** [comment]
Thanks for helping me to address it
