### ISSUE TITLE
[Bug] Nuxt link does not navigate after using pushState

### ISSUE THREAD

**Issue by martinszeltins** [nuxt/nuxt#25772]
### Environment

Stackblitz

````
Working directory: /home/projects/nuxt-starter-wkm6a7
Nuxt project info:

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.10.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------
````

### Reproduction

https://stackblitz.com/edit/nuxt-starter-wkm6a7?file=pages%2F%5B%5Buuid%5D%5D%2Findex.vue

### Describe the bug

I am creating an app where I have an `upload page (/import/upload/:uuid?)` which can have an optional `uuid` parameter. So the route is `/import/upload/[[uuid]]/index.vue`. At first, the user goes to `/import/upload` and when the user clicks on the `Upload` button, the backend server sends back an upload uuid. I wanted to silently add this uuid to my URL without triggering a navigation because a navigation re-mounts the components, runs lifecycle, shows loading bar hooks etc. which I don't want. I only want to update the `uuid` route param silently so that if the user refreshes the page he will land on the page with uuid in the URL.

I tried using `router.push` and `router.replace` but they always performed a navigation which is not what I wanted. So I found a solution that I can use the browser History API's `pushState` and `replaceState` method to do what I wanted. And it worked - the URL was updated without triggering navigation.

But a new problem appeared. I have a `<NuxtLink to="/import/upload">Upload</NuxtLink` which does not do anything when clicked when I am on route `/import/upload/1234-5678-9012` which is very strange. I expected it to navigate to `/import/upload` but nothing happens.

I tried both with state object and without but the result was the same:

```js
history.pushState({}, '', newPath)

// same result with this....
history.pushState({
    back: currentPath,
    current: newPath,
    forward: null,
    position: window.history.state.position + 1,
    replaced: false,
    scroll: null,
}, '', newPath)
```

_Please see the reproduction for a working demo._

**Comment by danielroe** [comment]
This also seems to occur without Nuxt: https://stackblitz.com/edit/github-ma3ruz?file=src/pages/Home.vue,src/App.vue.

I suspect this is just how `vue-router` behaves. My guess is that it's not a navigation, as from the router's perspective the route hasn't changed and you're just clicking on a link to the current route.
