### ISSUE TITLE
Add `noUncheckedIndexedAccess` to `tsconfig.server.json` and `tsconfig.json`

### ISSUE THREAD

**Issue by DamianGlowala** [nuxt/nuxt#25789]
### Describe the feature

We might consider adding `noUncheckedIndexedAccess` to `tsconfig.server.json` by default in Nuxt 4 for improved type safety.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by sharifzadesina** [comment]
This should also be added to client-side code.

**Comment by Mateleo** [comment]
I just spent 2 hours trying to figure out why my array was filled with null values, even though my backend is definitely sending non-null values. This configuration change should be clearly documented in the migration steps.

Here is what I ended up doing (client-side tsconfig)
```ts
{
  // https://nuxt.com/docs/guide/concepts/typescript
  "extends": "./.nuxt/tsconfig.json",
  "compilerOptions": {
    "noUncheckedIndexedAccess": false
  }
}
````

**Comment by danielroe** [comment]
while it doesn't make a difference in this case, I would recommend  configure this instead in `typescript.tsConfig`
