### ISSUE TITLE
Element-Ui The text in the el-table is crossed in the middle

### ISSUE THREAD

**Issue by shilo123** [nuxt/nuxt#25782]
### Environment

npm

### Reproduction

Vue.js

### Describe the bug

When I use el-table then inside el-table-column there is text and the text is crossed in the middle of the word it drops a line even before the space what to do?!!?!

**Comment by danielroe** [comment]
This is likely not a Nuxt issue. Let me suggest you ask for help on the [Nuxt Discord](https://discord.nuxtjs.org). You'll probably want to create a minimal reproduction so people can see what you are trying and better help you.
