### ISSUE TITLE
environment configuration alias docs (`$production`, `$development` and `$test`)

### ISSUE THREAD

**Issue by lassediercks** [nuxt/nuxt#25812]
In [Getting Started with Unit Tests](https://nuxt.com/docs/getting-started/testing#registerendpoint)  using `$test` is the suggested way of handling api requests. 

@danielroe provided an [example in a PR discussion](https://github.com/nuxt/nuxt/pull/25805#discussion_r1490992101) but besides that there is no documentation about that feature

```ts
export default defineNuxtConfig({
  $test: {
    runtimeConfig: {
      apiBase: ''
    }
  }
})
```

![image](https://github.com/nuxt/nuxt/assets/1765584/85e8eb2b-704b-4249-8d30-78e0530868ae)

**Comment by riddla** [comment]
There is some documentation over at https://github.com/unjs/c12#environment-specific-configuration. At least I think that this is the underlying feature used in the `nuxt.config`.

**Comment by manniL** [comment]
It is also documented in https://nuxt.com/docs/getting-started/configuration#environment-overrides, which should suffice. Feel free to point out what is missing if you disagree ☺️

**Comment by maartenvanhunsel** [comment]
@manniL is it possible to change the envname withing Nuxt? https://github.com/unjs/c12?tab=readme-ov-file#envname
For example I would like to use the `NUXT_SITE_ENV` variable to determine the environment.

**Comment by manniL** [comment]
@maartenvanhunsel follow along https://github.com/nuxt/cli/issues/357 ☺️

**Comment by lassediercks** [comment]
I do agree that the environment overrides section does greatly document the feature. 

Following my personal scenario: from a perspective of someone that explores the nuxt docs for the first time there is still not clear indication what `$test` is refering to 
<img width="770" alt="image" src="https://github.com/nuxt/nuxt/assets/1765584/3b06d77b-2612-4c0e-bc11-0e2d77d884e3">


Here is my idea how to battle that: https://github.com/nuxt/nuxt/pull/27315
