### ISSUE TITLE
reported `ip` vulnerability

### ISSUE THREAD

**Issue by Zae** [nuxt/nuxt#25810]
### Describe the feature

Hello,

It seems that a dependency that nuxt uses has a security vulnerability, but a fix does not seem likely, so someone else forked the package and fixed the vuln.

See: https://github.com/indutny/node-ip/issues/136#issuecomment-1945750119

Is it possible for nuxt to switch to this alternative package as well?

Security advisory: https://github.com/advisories/GHSA-78xj-cgh5-2h22

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Nuxt 3 has no production dependency using `ip` so is not vulnerable.

Nuxt 2 still depends on it but usage is not vulnerable as we do not use `ip.isPublic()` but merely `ip.address()`.

https://github.com/nuxt/nuxt/blob/e6878425367c5c1e3362ee5e9cd147e485fe70f4/packages/server/src/listener.js#L49
