### ISSUE TITLE
Nuxt router doesn't know how to resolve internal URL's between SSG and SPA routes

### ISSUE THREAD

**Issue by wanxe** [nuxt/nuxt#25818]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.9.0
- Nuxt Version:     3.10.2
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      css, ssr, app, nitro, devtools, components, postcss
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

CODESANDBOX:
https://codesandbox.io/p/devbox/nuxt3-routing-ssg-issue-psg437

### Describe the bug

When navigate between URLs generated by a CMS everything goes fine. (Any route resolved by [slug]). But if I navigate to any "internal page" like `Login` and then hit any of the other routes of the navbar (generated from the API call). Vue router doesn't know how to resolve the "/" of the project.

Same happened when I run `npm run generate`.

From now i'm using different layouts to handle this situation. I'm not 100% sure if it is a bug, but it is certainly something that should be considered as a use case. And it is not easy to find the problem.

### Additional context

I'm using a CMS to generate certain pages and nav links, but also want to preserve some "fixed" routes to handle some other logic from Nuxt.

**Comment by PabloIsidro** [comment]
I'm having the same issue

**Comment by ayozemr** [comment]
+1

**Comment by wanxe** [comment]
It was converted to a relative route; now, with a named route, it appears to manage the routes perfectly. My apologies!"

```:to="{ name: 'slug', params: { slug: String(item?.id) } }"```
