### ISSUE TITLE
Nuxt 3.10.2: Page takes too long to hydrate

### ISSUE THREAD

**Issue by Xenossolitarius** [nuxt/nuxt#25824]
### Environment

  ------------------------------
- Operating System: Linux
- Node Version:     v20.9.0
- Nuxt Version:     3.10.2
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.15.3
- Builder:          -
- User Config:      imports, components, alias, modules, colorMode, headlessui, sourcemap, runtimeConfig, $development, i18n, googleFonts, devtools, tailwindcss, experimental, nitro
- Runtime Modules:  @nuxtjs/color-mode@3.3.2, @nuxtjs/tailwindcss@6.11.4, @pinia/nuxt@0.5.1, @nuxtjs/google-fonts@3.1.3, @vueuse/nuxt@10.7.2, @nuxt/devtools@1.0.8, nuxt-headlessui@1.1.5, floating-vue/nuxt, nuxt-swiper@1.2.2, @nuxtjs/i18n@8.1.0, base/modules/preview
- Build Modules:    -
------------------------------

### Reproduction

use npm:nuxt-nightly@3.10.2-28463651.3ac8b18c 

### Describe the bug

Rendered page takes too long to hydrate which causes a long flash of unstyled HTML. Can confirm the route (index) chunk/module is delayed a lot.
I was able to pin it down with nightly releases when it stopped working: npm:nuxt-nightly@3.10.2-28463651.3ac8b18c

I managed to discard this change as a cause of issue by manually changing back the code, not 100% sure:
https://github.com/nuxt/nuxt/commit/3ac8b18cb6145e49c30d42a5f327c0ed33862f3f

Some of these deps updates caused I guess wrong ordering:

https://github.com/nuxt/nuxt/commit/eb1593ceba69986edcc30fdbd8b6a73168056f81
https://github.com/nuxt/nuxt/commit/18063b251ce3ed6b334b2b8951c328005841c299

**Comment by tberk** [comment]
I am having this flash issue with my projects too. 3.10.1 is fine, 3.10.2 breaks it.

Video from 3.10.2

https://github.com/nuxt/nuxt/assets/11773408/b5a54f10-cfea-441d-9db6-c9c52674b51b

Video from 3.10.1

https://github.com/nuxt/nuxt/assets/11773408/9553aa74-7794-471c-90ab-5665491606fd

**Comment by hmuyin** [comment]
Yes, I also encountered this issue. Without making any changes to the code, upgrading to 3.10.2 only resulted in CSS appearing as if it had not been loaded when the page was opened, followed by styles that caused serious visual flicker, which was very bad

**Comment by hmuyin** [comment]
"nuxt": "^3.10.2",
 "sass": "^1.71.0",
"vue": "^3.4.19",
"vue-router": "^4.2.5"

**Comment by markthree** [comment]
> Yes, I also encountered this issue. Without making any changes to the code, upgrading to 3.10.2 only resulted in CSS appearing as if it had not been loaded when the page was opened, followed by styles that caused serious visual flicker, which was very bad

Yes, I have also encountered this issue. I will try to reproduce it later

**Comment by markthree** [comment]
This is my reproduction, it only has the problem in 3.10.2, and can only be reproduced locally in node, not in stackblitz, so if anyone wants it, please download it locally → [stackblitz.com/github-yfdmxa](https://stackblitz.com/edit/github-yfdmxa?file=README.md)

**Comment by markthree** [comment]
I found out this is a problem with vite 🤣

Please add the following configuration to your package.json ↓

```json
{
  "overrides": {
    "vite": "npm:vite@latest"
  },
  "resolutions": {
    "vite": "npm:vite@latest"
  }
}
```

Then reinstall，Everything works perfectly 🥰

Related issue → #25806

**Comment by hmuyin** [comment]
> 我发现这是 vite 🤣 的问题
> 
> 请将以下配置添加到您的package.json ↓
> 
> ```json
> {
>   "overrides": {
>     "vite": "npm:vite@latest"
>   },
>   "resolutions": {
>     "vite": "npm:vite@latest"
>   }
> }
> ```
> 
> 然后重新安装，一切正常 🥰
> 
> 相关问题 [→ #25806](https://github.com/nuxt/nuxt/issues/25806)
> 
> 由于这是底层 vite 依赖版本的问题，请等待下一个 nuxt 版本，该问题将自动修复（因为 renovate bot）
> 
> 如果您等不及了，请使用我上面🥰描述的方法

Thank you

**Comment by hmuyin** [comment]
> 我发现这是 vite 🤣 的问题
> 
> 请将以下配置添加到您的package.json ↓
> 
> ```json
> {
>   "overrides": {
>     "vite": "npm:vite@latest"
>   },
>   "resolutions": {
>     "vite": "npm:vite@latest"
>   }
> }
> ```
> 
> 然后重新安装，一切正常 🥰
> 
> 相关问题 [→ #25806](https://github.com/nuxt/nuxt/issues/25806)
> 
> 由于这是底层 vite 依赖版本的问题，请等待下一个 nuxt 版本，该问题将自动修复（因为 renovate bot）
> 
> 如果您等不及了，请使用我上面🥰描述的方法

Thank you

**Comment by danielroe** [comment]
Ah, yes, if this is in development mode then it has already been fixed in vite. You should be able to regenerate your lockfile to pull in the latest vite version, as Nuxt does not pin to a specific Vite version.

**Comment by Xenossolitarius** [comment]
> Ah, yes, if this is in development mode then it has already been fixed in vite. You should be able to regenerate your lockfile to pull in the latest vite version, as Nuxt does not pin to a specific Vite version.

nuxt 3.10.2
├─┬ @nuxt/devtools 1.0.8
│ ├─┬ @nuxt/devtools-kit 1.0.8
│ │ └── vite 5.1.3 peer
│ ├── vite 5.1.3 peer
│ ├─┬ vite-plugin-inspect 0.8.3
│ │ └── vite 5.1.3 peer
│ └─┬ vite-plugin-vue-inspector 4.0.2
│   └── vite 5.1.3 peer
└─┬ @nuxt/vite-builder 3.10.2
  ├─┬ @vitejs/plugin-vue 5.0.4
  │ └── vite 5.1.1 peer
  ├─┬ @vitejs/plugin-vue-jsx 3.1.0
  │ └── vite 5.1.1 peer
  ├── vite 5.1.1
  ├─┬ vite-node 1.3.0
  │ └── vite 5.1.3
  └─┬ vite-plugin-checker 0.6.4
    └── vite 5.1.1 peer

Oh well override it is

**Comment by kindlychung** [comment]
For me overriding vite didn't work, but replacing "localhost" with "127.0.0.1" worked like magic. Why is it?

**Comment by miosenpai** [comment]
> For me overriding vite didn't work, but replacing "localhost" with "127.0.0.1" worked like magic. Why is it?

You are likely running into https://github.com/nuxt/cli/issues/209.

**Comment by darren-trottier** [comment]
Neither overriding or replacing "localhost" with "127.0.0.1" worked our my side. 

We are running "nuxt": "3.6.5" without issue, but I've try with 3.9.x 3.10.x without any success 

![image](https://github.com/nuxt/nuxt/assets/57952871/dc207e79-1607-4c9b-86e3-ca4f20b6e942)
