### ISSUE TITLE
Missing `routeNameSplitter` router param in config

### ISSUE THREAD

**Issue by bargel** [nuxt/nuxt#25823]
### Describe the feature

I had a trouble migrating large nuxt 2 project to the nuxt 3 version, because of the missing `router.routeNameSplitter` config parameter, so I was going to submit a PR, but in the last moment I found [this discussion](https://github.com/nuxt/nuxt/issues/18457), and the suggested fix worked for me.

I still want to help other devs in the migration process, if anyone face similar issue. It took time to found the solution, so should I still suggest a PR with this parameter added for backwards compatibility, [commit for the reference](https://github.com/bargel/nuxt/commit/1d55a28faeafb335e7d5030b0fe3352755428508)? or if those points from the discussion still relevant, maybe just add this solution somewhere to the migration guides?

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
As discussed in https://github.com/nuxt/nuxt/issues/18457, the maintenance effort outweighs the benefits.

Maybe this could be something that could be either documented somewhere (e.g. the migration guide)? 🤔
