### ISSUE TITLE
Objects diferentes in composable

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/nuxt#25828]
### Environment

❯ npx nuxi info
Working directory: /home/projects/nuxt-starter-juxjq4                                                             13:23:19
Nuxt project info:                                                                                                13:23:19

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.10.2
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                       13:23:19

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Reproduction

https://stackblitz.com/edit/nuxt-starter-juxjq4

### Describe the bug

The object into composable and in usage are diferents!!

When i return the variable into composable, the object is 
`AnalyticsBrowser2`
but when i use this composable, the object is an array!!

![image](https://github.com/nuxt/nuxt/assets/77386602/ec9b0aae-e3ae-4b41-bc8b-cc0ddad4687f)

Must be the same object!

**Comment by manniL** [comment]
Seems to be related to the `await` call and the way of returning 🤔.

As a workaround, `return { segment }` instead of `return segment`. See [StackBlitz](https://stackblitz.com/edit/nuxt-issues-25828)

**Comment by manniL** [comment]
Ah, no. This is the result when `await`ing the created `segment` variable. ☺️ 

You can verify by using `console.log('segment', await segment);`
