### ISSUE TITLE
📄 Docs on CORS is missing

### ISSUE THREAD

**Issue by jd-solanki** [nuxt/nuxt#25827]
### Describe the feature

Hi 👋🏻 

Recently, I was deploying the nuxt app and encountered the CORS error. I tried to find CORS docs on nuxt but couldn't find. I checked nitro as well but there's not dedicated section for CORS as well.

Adding this straight in nuxt docs (or even reference link) will be great.

---

Regardless of this, Team was going to do some magic where you can list other site's search data in nuxt's docs so people can cross search at single place, I guess that can resolve this kind of issue.

---

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
I don't think this is really Nuxt-related, but adding a few lines to the documentation would be welcome.
