### ISSUE TITLE
ESLint: The template root requires exactly one element.(vue/no-multiple-template-root)

### ISSUE THREAD

**Issue by stephenjason89** [nuxt/nuxt#25820]
### Environment

- Operating System: `Darwin`
- Node Version:     `v21.5.0`
- Nuxt Version:     `3.10.2`
- CLI Version:      `3.10.1`
- Nitro Version:    `2.8.1`
- Package Manager:  `pnpm@8.14.1`
- Builder:          `-`
- User Config:      `future`, `app`, `srcDir`, `vite`, `ssr`, `build`, `experimental`, `typescript`, `imports`, `modules`, `shadcn`, `tailwindcss`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.11.4`, `@nuxt/test-utils/module@3.11.0`, `@vueuse/nuxt@10.7.2`, `@nuxtjs/device@3.1.1`, `shadcn-nuxt@0.9.0`, `nuxt-icon@0.6.8`, `@pinia/nuxt@0.5.1`
- Build Modules:    `-`

### Reproduction

Enable global transition
Create a new page
turn off transition with definePageMeta on that page

Add multiple root nodes on the template

### Describe the bug

https://github.com/nuxt/eslint-config/blob/main/packages/eslint-config/index.js#L77

This rule does not take into account when you have global transition enabled but you disabled it on certain pages with
```
definePageMeta({
	pageTransition: false,
})
```

I still get The template root requires exactly one element.(vue/no-multiple-template-root) error.
The error should not be present because transition for that page is false. Thus, we should be allowed to use multiple root nodes.

**Comment by manniL** [comment]
The rules are *not* config-based and always apply. Feel free to disable or override the rule in your own eslint config ☺️
