### ISSUE TITLE
defineModel doesnt know set option

### ISSUE THREAD

**Issue by sphex813** [nuxt/nuxt#25844]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.1.0
- Nuxt Version:     3.10.2
- CLI Version:      3.10.1
- Nitro Version:    2.7.0-28295243.3e9302a
- Package Manager:  npm@9.6.4
- Builder:          -
- User Config:      devtools, build, plugins, imports, nitro, modules, eslint, css, pinia, alias, colorMode, vite
- Runtime Modules:  @nuxtjs/tailwindcss@6.11.4, @pinia/nuxt@0.5.1, @nuxtjs/eslint-module@4.1.0, @nuxt/image@1.3.0, @nuxtjs/i18n@8.1.1, nuxt-icon@0.6.8, @vueuse/nuxt@10.7.2, @nuxtjs/color-mode@3.3.2, @nuxtjs/supabase@1.1.6
- Build Modules:    -

### Reproduction

create component with 
`const modelValue = defineModel<string | null | undefined>({
  set(value: string) {
    if (value) {
      return value.trim();
    }
    return value;
  },
});`

following declaration of defineModel gives `No overload matches this call.
  The last overload gave the following error.ts(2769)
 ` error

also 
`const modelValue = defineModel<string, "trim">();
` is not working, it is throwing `Expected 1 type arguments, but got 2.`

### Describe the bug

following declaration of defineModel gives `No overload matches this call.
  The last overload gave the following error.ts(2769)
 ` error

### Additional context

those are functionalities from official Vue 3.4 documentation https://vuejs.org/api/sfc-script-setup.html#modifiers-and-transformers

**Comment by danielroe** [comment]
This is not a Nuxt issue. Here's the behaviour in the Vue SFC playground:

https://play.vuejs.org/#eNqNUk1v2zAM/SuELk2AxsaQXZalRbehhw3YB7ZhJ108m0nVSZQg0WkAz/+9tJ2kTvqBnhLxPZrvPbJRH0LINjWqhVqmMprAkJDrALag9YVWnLS61GRc8JGhgQpXhvCrr9BCC6voHZxJ+5kmTaWnxOA67E9ha4SLMX2ZOBpaw3+g2lr5qWlAq8tJowm6uZNN17eAgTqFvg5gVjAgU4giLhL0r0xYbjIdOGOgq7Tnmtrpe03LfPAlLuTB6IItGOUF0DRjtW3bkUcEda4G3zNXhOw2eZKUekl6B0g4i71IrSSH7q3VDXNIizwvK5I2GWA2MSPknILLr4SWx5rYOJxV3l3Ns7fZm3d5ZRKP6xkmN/sb/V3CKF/RSgwd5uRS3GCcRZQQI8bXzj1pO5p9gj2a36cqoUosnGTXK7M+CaX0LhiL8XtgI7dwFE5hrb/70tc41ngwU95g+e+J+m3aDqZ+ROyVjQLgIq6RB/j61zfcyv8DKBut7W4Rz4A/MXlbdxoH2kc5RZE94vVqP/c7lkP8na63jJT2po6Edrda9mK68v70dnv69EIiDy7m2fwQbnsPX/U2hw==

You can raise at https://github.com/vuejs/core but perhaps this is a misuse of the generic?
