### ISSUE TITLE
can't deploy SPA mode, vite.base isn't recognized by nuxt

### ISSUE THREAD

**Issue by omar-labana** [nuxt/nuxt#25849]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.11.0
- Nuxt Version:     3.10.2
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  bun@1.0.26
- Builder:          -
- User Config:      devtools, ssr, css, modules, veeValidate, vite
- Runtime Modules:  @vee-validate/nuxt@4.12.5
- Build Modules:    -
------------------------------

### Reproduction

try out any value in vite.base
```ts
export default defineNuxtConfig({
  devtools: { enabled: true },
  ssr: false,
  css: ["~/assets/scss/style.scss"],
  modules: ["@vee-validate/nuxt"],
  veeValidate: {
    autoImports: true,
  },
  vite: {
    base: "/fluxo/",
  },
});
```

### Describe the bug

when serving the static build or deploying to gh-pages the index.html can't find the js files
please check this out https://omar-labana.github.io/fluxo/
repo: https://github.com/omar-labana/fluxo

**Comment by manniL** [comment]
Instead of `vite.base` use `app.baseURL` 👍
