### ISSUE TITLE
readBody(event) won't work on Cloudflare Pages.

### ISSUE THREAD

**Issue by marcbejar** [nuxt/nuxt#25845]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.10.2
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.2
- Builder:          -
- User Config:      devtools, modules, app, runtimeConfig, supabase, ui, colorMode, swiper, pwa
- Runtime Modules:  @nuxtjs/supabase@1.1.6, @nuxt/ui@2.13.0, nuxt-icon@0.6.8, nuxt-swiper@1.2.2, @vite-pwa/nuxt@0.3.6, @pinia/nuxt@0.5.1, @pinia-plugin-persistedstate/nuxt@1.2.0
- Build Modules:    -
------------------------------

### Reproduction

1. Create a Nuxt App with `npx nuxi@latest init <project-name>`
2. Create a delete API route (/api/link.delete.ts):
`
export default defineEventHandler(async (event) => {
  const body = await readBody(event)
  console.log('HELLO WORLD')
})
`
4. Call tthe API with $fetch:
`
  try{
    await $fetch('/api/link', {
      method: 'DELETE',
      body: { account:account_id, link:link_id }
    })
  } catch(e) {  }
`
5. Create Pages project on cloudflare and push changes to GitHub.
6. Try to perform the DELETE action.

### Describe the bug

After calling the function that contains the try/catch with the DELETE api call, the brower shows an 500 (Internal Server Error) error in the console:

`DELETE https://domain.app/api/link 500 (Internal Server Error)`

Then  if you activate the cloudflare deployed function Log Stream, you will see the complete exception error saying:

`{
  "outcome": "exception",
  "scriptName": "pages-worker--1779133-production",
  "diagnosticsChannelEvents": [],
  "exceptions": [
    {
      "name": "Error",
      "message": "The script will never generate a response.",
      "timestamp": 1708203292109
    }
  ],
...`

Summarizing, the await readBody(event) causes an Error in Cloudflare workers resulting in "The script will never generate a response".

### Additional context

This reproduction works fine in Local development.

To confirm it was the readBody(event) I have already commented the line in the code and without it, the DELETE api call performs well on Cloudflare.

I have researched the error and there are multiple related to the error itself but no one related to the error with Nuxt.

**Comment by danielroe** [comment]
This should be fixed upstream - see https://github.com/unjs/nitro/issues/912#issuecomment-1486816149.

If not, please do raise an issue [upstream](https://github.com/unjs/nitro/issues/new/choose) with a reproduction in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)) 🙏
