### ISSUE TITLE
路由优先级问题

### ISSUE THREAD

**Issue by f754699** [nuxt/nuxt#25858]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.12.1
- Nuxt Version:     3.9.3
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.6.1
- Builder:          -
- User Config:      devtools, hooks, build, vite, runtimeConfig, modules, pinia, css, devServer, nitro
- Runtime Modules:  @vueuse/nuxt@10.5.0, nuxt-icon@0.6.8, @nuxt/devtools@1.0.8, @nuxtjs/device@3.1.0, nuxt-windicss@2.6.1, @pinia/nuxt@0.5.1, @pinia-plugin-persistedstate/nuxt@1.1.2, @formkit/auto-animate/nuxt@0.8.0
- Build Modules:    -

### Reproduction

无

### Describe the bug

我的路由：
/wiki/viewku/zhishiku?           一个路径参数
/wiki/viewku/zhishiku?/airtle?      两个路径参数

访问的地址：
/wiki/viewku/1/Folder_1

我应该访问：/wiki/viewku/zhishiku?/airtle?  
我实际访问的：/wiki/viewku/zhishiku? 

### Additional context

无

### Logs

```shell-script
无
```

**Comment by f754699** [comment]
我定义的文件：
pages/wiki/viewku/[zhishiku].tsx
pages/wiki/viewku/[zhishiku]/[airtle].tsx

**Comment by f754699** [comment]
我解决了

pages/wiki/viewku/[zhishiku]/index.tsx
pages/wiki/viewku/[zhishiku]/[airtle].tsx

但是，这样会报一个解析url的错误
Failed to parse URL from

**************************************************************************
I solved it
now,The file path configuration is

pages/wiki/viewku/[zhishiku]/index.tsx
pages/wiki/viewku/[zhishiku]/[airtle].tsx

However, this will result in an error parsing the URL
"Failed to parse URL from"

**Comment by madebyfabian** [comment]
@f754699 Do you still experience an issue? Or can this be closed?
