### ISSUE TITLE
 nuxt.js3 How to get the js files in local assets

### ISSUE THREAD

**Issue by wangrunze2023** [nuxt/nuxt#25856]
### Describe the feature

nuxt.js3 How to get the js files in local assets, but the introduction fails.

`useHead({
    script: [
        {
            src:'@/assets/js/qrcode.min.js'
        }
    ]
})`

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
asset paths will not be resolved this way. Best would be putting it into public ☺️

**Comment by wangrunze2023** [comment]
> asset paths will not be resolved this way. Best would be putting it into public ☺️资产路径不会以这种方式解决。最好将其公开 ☺️

Thanks ！😄
