### ISSUE TITLE
UseFetch / UseAsyncData Dedupe not Working

### ISSUE THREAD

**Issue by metkm** [nuxt/nuxt#25853]
### Environment

- Operating System: Windows_NT
- Node Version:     v21.1.0
- Nuxt Version:     3.10.2
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.5
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-yjwcwx

### Describe the bug

When
`useAsyncData` `key` is set to `defer`

Having the request on `App.vue` and the children causes it to make the request twice. I would expect this to be make the request once when the page is reloaded. I guess currently It doesn't dedupe the request correctly when it's on different levels even though the key is the same. Also the `refreshNuxtData` runs once as it should. But this behavior is different than what happens when you refresh the page.

When
`useAsyncData` `key` is set to `cancel`

This is the worst case scenario. Makes request for every `useAsyncData`. The same goes for `refreshNuxtData`. No dedupe at all.

**Comment by Floppy012** [comment]
Same issue with latest nuxt update
- Operating System: Linux
- Node Version:     v20.11.1
- Nuxt Version:     3.11.1
- CLI Version:      3.11.0
- Nitro Version:    2.9.4
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      modules, devtools, ssr, css, runtimeConfig
- Runtime Modules:  @nuxtjs/tailwindcss@6.11.4, @nuxt/fonts@0.3.0, dayjs-nuxt@2.1.9
- Build Modules:    -

**Comment by 18anandn** [comment]
@metkm @Floppy012 
I have not dwelled deeply into nuxt yet but I may have found the source of the problem.
In the [docs](https://nuxt.com/docs/api/composables/use-async-data#params) it says the following for getCachedData:
#getCachedData: Provide a function which returns cached data. A null or undefined return value will trigger a fetch. By default, this is: key => nuxt.isHydrating ? nuxt.payload.data[key] : nuxt.static.data[key], which only caches data when payloadExtraction is enabled.

So if we change the useHello composable to the following:
```
export const useHello = async () => {
  const nuxt = useNuxtApp()
  return useAsyncData('hello', () => $fetch('/api/hello'), {
    server: true,
    getCachedData(key) {
      return nuxt.payload.data[key] || nuxt.static.data[key]
      // return nuxt.isHydrating ? nuxt.payload.data[key] : nuxt.static.data[key]
    },
    dedupe: 'defer',
  });
};
```
We get the desired behaviour with this. So I think it will be great if we can know when the hydration starts exactly and which components are actually completerly server rendered

**Comment by vhovorun** [comment]
+1

**Comment by SunXinGuo** [comment]
As I tried under nuxt `3.15.2`,  `dedupe: 'cancel'` does **NOT** cancel existing request, `dedupe: 'defer'` works as expected.

The document is NOT clear enough about the cache behavior of `useFetch` and `useAsyncData` , for anyone who was also confused by it:

> There is `NO cache` by default, `dedupe` is `only useful` when make a request multiple times `at the same time`, subsequent request at later time still send to server，but the result will affect everywhere that use the same request.

 

Quite  confusing design.
