### ISSUE TITLE
[Nuxt 3.10.2] .css file imported by .css is not loaded in the first rendering

### ISSUE THREAD

**Issue by kingyue737** [nuxt/nuxt#25860]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.11.1
- Nuxt Version:     3.10.2
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.15.3
- Builder:          -
- User Config:      devtools, css
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-mz42kv-xsjtzy

### Describe the bug

Run dev server on Windows and refresh the page. The title on the page should always be red but it was actually originally blue:

![bug](https://github.com/nuxt/nuxt/assets/40021217/d8f47588-053c-4b73-97c7-9ab9c0e85cd2)

It seems that style in `~/assets/style.css`, which is imported by `~/assets/index.css`, is loaded after the initial rendering.

This bug totally messed up the layout when my project use a UI library like Vuetify.
Very similar to #25240

### Additional context

Can only be reproduced on Windows + Nuxt 3.10.2
No such issue on Linux
No such issue on Windows + 3.10.1

**Comment by danielroe** [comment]
This is a Vite upstream bug that was fixed in v5.1.3. For now, you can add a resolution/override, or it will be fixed in the next Nuxt patch release.
