### ISSUE TITLE
"The stylesheet was not loaded because its MIME type" error in Firefox

### ISSUE THREAD

**Issue by matt-clegg** [nuxt/nuxt#25879]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.11.1
- Nuxt Version:     3.10.2
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.15.2
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

1. Create a new Nuxt project with the `pnpm dlx nuxi@latest init <project-name>` command.
2. Start the dev server with `pnpm run dev`.
3. Open the Nuxt site in Firefox, my version is: 122.0.1 (64-bit).

### Describe the bug

When you open the Nuxt site in Firefox for the first time, the console looks like this:
![image](https://github.com/nuxt/nuxt/assets/34515355/08f9c16a-1dac-47b1-a03c-d3d454d7ecbc)

But when you hit F5 to refresh the page, the following errors appear in the console:
![image](https://github.com/nuxt/nuxt/assets/34515355/58ebef0e-36a4-44b9-bf22-1f41f6e42739)

`The stylesheet http://localhost:3000/_nuxt/node_modules/.pnpm/@nuxt+ui-templates@1.3.1/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue?vue&type=style&index=0&scoped=5186e9ca&lang.css was not loaded because its MIME type, "text/javascript", is not "text/css".`

`The stylesheet http://localhost:3000/_nuxt/node_modules/.pnpm/vite-plugin-vue-inspector@4.0.2_vite@5.1.3/node_modules/vite-plugin-vue-inspector/src/Overlay.vue?vue&type=style&index=0&scoped=75011137&lang.css was not loaded because its MIME type, "text/javascript", is not "text/css".`

I don't think it breaks the dev site, but I have noticed when I hit refresh the page loads without any styling, then the styling pops in after a moment.

These errors don't appear when using other browsers like Chrome.

**Comment by manniL** [comment]
I use Firefox daily and have no issues with Nuxt sites in dev nor in production. It might be your AV scanner or extension. Can you try a new FF profile?

**Comment by matt-clegg** [comment]
I tried disabling all extensions and running in an incognito window and I got the same behaviour. Unfortunately I don't have access to disable my AV as this is on a work machine.

I also asked a colleague to try and recreate this on their personal mac and they were able to recreate the console errors. This is their result from running `npx nuxi info`:

- Operating System: Darwin
- Node Version:     v20.11.1
- Nuxt Version:     3.10.2
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.15.3
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

They are running Firefox 122.0.1.

**Comment by cosbgn** [comment]
I can confirm that I have the same issue on firefox devevoper edition also on incognito without any extension (I use the tailwind module):

```js

The stylesheet http://localhost:3000/_nuxt/assets/tailwind.css was not loaded because its MIME type, “text/javascript”, is not “text/css”.

```

I noticed that via nuxt-link it doesn't happen but it happens when refreshing the page via the browser

**Comment by manniL** [comment]
Just upgraded to the latest FF version and see it too. 🙈

**Comment by danielroe** [comment]
Can you check whether it's reproducible when pinning Vite to 5.1.3?

**Comment by matt-clegg** [comment]
I tried pinning Vite to 5.1.3 and I can still reproduce the issue.
![image](https://github.com/nuxt/nuxt/assets/34515355/4091a4d5-61b4-4aec-b918-bf31835fe7ac)

**Comment by nsina** [comment]
Getting this error on Firefox 123.0 (running Nuxt Version: 3.10.2). Was happening on Nuxt 3.10.1 as well.

**Comment by amirrezajef** [comment]
Same here, also I'm geting "Uncaught (in promise) TypeError: error loading dynamically imported module:" error that also I think relevant to this

![image](https://github.com/nuxt/nuxt/assets/37063716/c8750e5e-838c-4f5c-b6db-defccf7131d0)

- Operating System: Windows_NT
- Node Version: v20.10.0
- Nuxt Version: 3.10.2
- Package Manager: yarn@1.22.19

**Comment by matt-clegg** [comment]
Upgrading to Nuxt v3.10.3 seems to have fixed the issue!

**Comment by awacode21** [comment]
hi! i have the same issue with nuxt 3.12.2 and google chrome Version 128.0.6613.86 (Offizieller Build) (arm64)

**Comment by danielroe** [comment]
Would you provide a reproduction?

**Comment by NullVoxPopuli** [comment]
I just ran in to this with a pnpm + vite project and _not_ nuxt. so I don't think it's nuxt related, specifically.
