### ISSUE TITLE
Replace files on build / dev

### ISSUE THREAD

**Issue by MickL** [nuxt/nuxt#25876]
### Describe the feature

I would love to have the possibility to replace a file on dev or build. 

For example Angular has such an option:

```
"configurations": {
  "development": {
    "fileReplacements": [
        {
          "replace": "src/environments/environment.ts",
          "with": "src/environments/environment.development.ts"
        }
      ],
      …
```

_Motivation:_
I am using a specific database driver for deployment (`@vercel/pg`) while on local dev I use `postgres.js`. If I deploy to Vercel the build fails because the serverless edge functions dont work with the former driver but my file `use-db.ts` imports it. 

Instead of a file that imports both and uses an `if ()` (which results in the failed deployment) I would like to swap out the file, e.g. replace `use-db.ts` with `use-db.dev.ts` on local dev. 

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
As a workaround, you could do something like this:

```ts
import { addTemplate } from 'nuxt/kit'

export default defineNuxtConfig({
  modules: [
    function () {
      addTemplate({
        filename: 'use-db.mjs',
        write: true,
        getContents: ({ nuxt }) => nuxt.options.dev ? `export * from '~/use-db.dev` : `export * from '~/use-db.prod`
      })
    }
  ],
})
```

... and then import from `#build/use-db`.

**Comment by danielroe** [comment]
We've discussed and think the additional complexity wouldn't warrant adding this to Nuxt core, particularly given there is a workaround available.

**Comment by MickL** [comment]
Thats unfortunate! It is a default feature in Angular since its release but thanks.
