### ISSUE TITLE
reactive() of a class improperly inherits the class's type with private properties included

### ISSUE THREAD

**Issue by alex-eliot** [nuxt/nuxt#25884]
### Environment

- Operating System: Darwin
- Node Version:     v20.11.0
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.21
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

```ts
class Service {
  value: number
  private initialValue: number

  constructor(initialValue: number) {
    this.initialValue = initialValue
    this.value = initialValue
  }
}

// Correct, no type errors
const instance: Service = new Service(1)

// Error: Property 'initialValue' is missing in type '{ value: number; }' but required in type 'Service'
const instance2: Service = reactive(new Service(1))
```

### Describe the bug

When using reactive() with a class instantiation as an input, the type test against the class fails, making it difficult to use that value on functions with input type the class.

### Additional context

The following still doesn't work:
```ts
const instance: Service = reactive<Service>(new Service(5))
```

The following will (of course) work:
```ts
const instance: Service = reactive(new Service(5)) as Service
```

**Comment by manniL** [comment]
This is [a Vue behavior](https://play.vuejs.org/#eNp9kk1v2zAMhv8KoYtTIEiwj1OWDNiKHLbDVqzDTrq4CpuqkyWNotwUhv/7aLtubCAo4INFviIf6mWjvsS4qjOqjdomQzYyJOQcwZX+uNOKk1aftbdVDMTQEJaGbY0t3FOooJCbhfbGlSnBLVJtDUKjPUBduowb8Lm6Q+oCkWxdMoL1lm3p/szzncIEn5iy4UCLS6qroTIAP9i0mipgNys7UfUYF9Kt9vJpv17DdSBCw0vwAfg5IiBRoCRTdTxyM3HpjVCM8+3A49N4Wry7eqmz765t4IZCROJnKKY9C7AJKpuS9UcpOTQqmvkzfYK2gLvMQPgvW8LDWfnSrXvrGdX7KdZozmLOJ4Db9eCtOCkHxio68UJOAE1zLgatPMp2PcmrpWyAtLy3x9VjCl7WpDdBKxOqaB3Sz8hWkLTajPZoVToXnr73MTEUl2PcPKD5eyH+mE5dTKsbwiTcqNVrjks6Ig/p/e0PPMn/a7IKh+xE/UbyF6bgcsc4yL5mfxDsia6n/dYvuLjzO+1PjD6NQ3Wg/cb0eq1k46/fGP2M+2H1cdw01f4HSDAsow==) and no Nuxt issue. Feel free to raise upstream.

https://github.com/vuejs/core/issues/5920 might be related?
