### ISSUE TITLE
path did not match /api/boards

### ISSUE THREAD

**Issue by safi-okz** [nuxt/nuxt#25883]
### Environment

I have an issue to fetch an API and the API did not fetch and show me the error "[Vue Router warn]: No match found for location with path "/api/boards/"

### Reproduction

I have an issue to fetch an API and the API did not fetch and show me the error "[Vue Router warn]: No match found for location with path "/api/boards/"

### Describe the bug

I have an issue to fetch an API and the API did not fetch and show me the error "[Vue Router warn]: No match found for location with path "/api/boards/"

### Additional context

I have an issue to fetch an API and the API did not fetch and show me the error "[Vue Router warn]: No match found for location with path "/api/boards/"

### Logs

```shell-script
I have an issue to fetch an API and the API did not fetch and show me the error "[Vue Router warn]: No match found for location with path "/api/boards/"
```

**Comment by danielroe** [comment]
Try updating `h3`. I think this was likely resolved in https://github.com/unjs/h3/pull/646.

**Comment by madebyfabian** [comment]
@safi-okz Can you confirm that this is still happening?
