### ISSUE TITLE
Nuxt Layer - Multi App - Disable Server Routes and Middleware for App

### ISSUE THREAD

**Issue by samydoesit** [nuxt/nuxt#25885]
### Describe the feature

Hello, I'm currently encountering an issue where I need to disable server routes and middleware for a specific package within our monorepo, but I'm unsure how to proceed.

We are developing two Nuxt applications: one is a server-side rendered (SSR) app that includes some server routes, and the other is a small hybrid app built with CapacitorJS and Nuxt. Both applications utilize a shared Nuxt layer to reuse some components and logic.

The SSR Nuxt app employs a proxy and server routes. I've noticed that when I start a development server for the Capacitor Nuxt app, the server routes defined in our Nuxt layer begin to respond to events and navigations in the Capacitor Nuxt app (which is not SSR). This behavior is unintended at this stage.

Is there a method to disable server routes and middleware for a project within a multi-app environment using a Nuxt layer?

For reproduction, please see: https://stackblitz.com/edit/github-t2tsxy?file=.playground%2Fpages%2Flogout.vue,.playground%2Fpages%2Findex.vue

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
One way could be solving this in userland with e.g. a `runtimeConfig` value to check before executing the middleware/routes this in a layer 👍

**Comment by manniL** [comment]
Probably easier to build a wrapper for `defineEventHandler` and similar that covers that ☺️ @Mokkapps

**Comment by samydoesit** [comment]
Thank you for your prompt response. I have tested the solution you proposed, but unfortunately, it did not achieve the expected outcome.

I was anticipating that by implementing an early return in the logout event handler, the Nuxt logout page would be displayed. However, instead of navigating to the logout page, it returns 'false' if the navigation occurs through a manual URL entry or a standard anchor (`<a>`) tag. A normal `GET` Request will still be answered by the event handler even if early returned. 

When navigating using a NuxtLink, the logout page renders as expected.

You can test this in the [Updated StackBlitz](https://stackblitz.com/edit/nuxt-issues-25885) environment.

**Comment by pi0** [comment]
Allowing to disable certain features from Nuxt/Nitro layers (server routes, pages, components) is something we might think about to support in Nuxt 👍🏼 (we might introduce a new `$layer` configuration API to allow disabling certain routes)

---

Generally, I would highly advice to prefer the composable/util methods over global patterns such as plugins and middleware (also not wrappers You might want to use [object syntax](https://h3.unjs.io/guide/event-handler#object-syntax) for fine control instead). **especially** for Nuxt layers when a layer can have undesired global side effects.

---

@samydoesit I got your immediate question but I think we might think of some faster solutions. Do you mind to update your sandbox/repro with the current multi-app of your project?

**Comment by samydoesit** [comment]
Hi, thank you for the support.
I've tried my best to replicate our app structure in StackBlitz. 
[Multi-App Monorepo Stackblitz](https://stackblitz.com/edit/github-om7hsq-1d7k9t?file=apps%2Fapp%2Fapp.vue)

**Comment by mlbonniec** [comment]
Hi :\) I'm currently facing the same issue.

We're building about 10 websites, depending on the same OAuth provider. To simplify those websites, we've created a utils library, containing a notification helper, global styles etc. and a server API middleware, to exchange authentication tokens safely.

However, one of our website (*the authentication website*) doesn't need this middleware, as it's automatically redirecting users to other websites.

As a workaround, I'm not using layer, but module, to allow configuring styles, authentication etc.

**Comment by danielroe** [comment]
You can disable server routes and middleware with a Nuxt hook:

```ts
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: [
    function (_, nuxt) {
      nuxt.hook('nitro:init', nitro => {
        nitro.options.scanDirs = []
      })
    }
  ]
})
```

You could add this tiny module or hook into your capacitor app.

**Comment by samydoesit** [comment]
Thank you for your feedback. I encountered an issue when setting`scanDirs` to an empty array, as it also removes our Nitro route types, which our application's code relies on. Is there a way to selectively enable or disable a specific layer route or middleware?
