### ISSUE TITLE
Issue with baseURL on Cloudflare Pages

### ISSUE THREAD

**Issue by mrbubbaz** [nuxt/nuxt#25892]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.11.0`
- Nuxt Version:     `3.10.2`
- CLI Version:      `3.10.1`
- Nitro Version:    `2.8.1`
- Package Manager:  `npm@10.2.4`
- Builder:          `-`
- User Config:      `devtools`, `app`, `nitro`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Check this [Nuxt project](https://github.com/mrbubbaz/nuxt-baseURL-cf)

to Reproduce:

1. Clone the repository.
2. Install dependencies and run the project.
3. type: `npm run cf-preview` to build project locally and preview it with Cloudflare Wrangler
4. open generated link from wrangler console

### Describe the bug

I am currently working with Nuxt 3.10.2 (the latest version) and have a perfectly functioning project in the development environment. My project utilizes the baseURL functionality because it runs in a subdirectory of my main domain. Typically, this isn't an issue, as it works smoothly on various providers where I've deployed it. However, I'm encountering several bugs on Cloudflare Pages.

### Additional context

You got this 404 errors with wrangler runtime console while you visiting homepage:

```console
⎔ Starting local server...
[wrangler:inf] Ready on http://localhost:8788
[wrangler:inf] GET / 404 Cannot find any path matching /. (80ms)
[wrangler:inf] GET /dir/subdir/_nuxt/entry.BSINYclE.js 404 Page not found: /_nuxt/entry.BSINYclE.js (3ms)
[wrangler:inf] GET /dir/subdir/_nuxt/vue.f36acd1f.CLfYOuw6.js 404 Page not found: /_nuxt/vue.f36acd1f.CLfYOuw6.js (6ms)
[wrangler:inf] GET /dir/subdir/_nuxt/error-404.CIPWpD7_.js 404 Page not found: /_nuxt/error-404.CIPWpD7_.js (6ms)
[wrangler:inf] GET /dir/subdir/_nuxt/error-500.DB7gr8pt.js 404 Page not found: /_nuxt/error-500.DB7gr8pt.js (3ms)
[wrangler:inf] GET /favicon.ico 200 OK (10ms)
[wrangler:inf] GET /dir/subdir/ 200 OK (6ms)
[wrangler:inf] GET /dir/subdir/_nuxt/entry.BSINYclE.js 404 Page not found: /_nuxt/entry.BSINYclE.js (2ms)
[wrangler:inf] GET /dir/subdir/_nuxt/index.D2go8O3-.js 404 Page not found: /_nuxt/index.D2go8O3-.js (7ms)
[wrangler:inf] GET /dir/subdir/images/sample.jpg 404 Page not found: /images/sample.jpg (7ms)
[wrangler:inf] GET /dir/subdir/_nuxt/vue.f36acd1f.CLfYOuw6.js 404 Page not found: /_nuxt/vue.f36acd1f.CLfYOuw6.js (6ms)
[wrangler:inf] GET /favicon.ico 200 OK (9ms)
[wrangler:inf] GET /dir/subdir/_nuxt/error-404.CIPWpD7_.js 404 Page not found: /_nuxt/error-404.CIPWpD7_.js (5ms)
[wrangler:inf] GET /dir/subdir/_nuxt/error-500.DB7gr8pt.js 404 Page not found: /_nuxt/error-500.DB7gr8pt.js (11ms)
```

**Comment by EugenPulup** [comment]
Hi, you can try configure CF Pages environment, and in build settings set `Root directory` your path(_/dir/subdir/_). 

But i think it will be much easier to separate main and sub projects and pair them using CloudFlare DSN->CNAME for sub-domain

**Comment by mrbubbaz** [comment]
Hi EugenPulup,

Thank you for your suggestion. I tried configuring the root directory as you suggested in the Cloudflare Pages environment, but unfortunately, it didn't resolve the issue. The deployment still fails with the error message:

```console
13:33:50.212 | Error: Cannot find cwd: /opt/buildhome/repo/dir/subdir
-- | --
13:33:50.213 | at we (/snapshot/dist/run-build.js)
13:33:50.213 | at Hn (/snapshot/dist/run-build.js)
13:33:50.213 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
13:33:50.221 | Failed: build command exited with code: 1
13:33:51.469 | Failed: error occurred while running build command
```

It seems that this error is not related to DNS settings or the use of a CNAME. It appears to be more closely tied to the configuration of the basePath in Nuxt, which may have an incompatibility with the "cloudflare-pages" template in Nitro.

Do you have any further insights or suggestions on how to address this compatibility issue?

Thank you for your help.

**Comment by danielroe** [comment]
Would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏
