### ISSUE TITLE
nuxt doesn't respect vite.server.hmr config

### ISSUE THREAD

**Issue by flapili** [nuxt/nuxt#25909]
### Environment

- Operating System: Darwin
- Node Version:     v20.11.1
- Nuxt Version:     3.10.2
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.15.3
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

```ts
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },

  devServer: {
    port: 3002,
  },
  vite: {
    server: {
      hmr: {
        host: '192.168.50.44',
        port: 3001,
      }
    },
  },
})
```

the vite.server.hmr config is just ignored (nuxt keep doing hmr via port 3002 on localhost)

### Describe the bug

on proxied environment like in tauri android it fail to hmr, this config worked in mid-2023 (doing more investigation currently),

### Logs

```shell-script
client.ts:77 WebSocket connection to 'ws://tauri.localhost/_nuxt/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
setupWebSocket @ client.ts:77
Show 1 more frame
Show less
client.ts:77 Uncaught (in promise) DOMException: Failed to construct 'WebSocket': The URL 'ws://localhost:undefined/_nuxt/' is invalid.
    at setupWebSocket (http://tauri.localhost/_nuxt/@vite/client:505:20)
    at fallback (http://tauri.localhost/_nuxt/@vite/client:484:22)
    at WebSocket.<anonymous> (http://tauri.localhost/_nuxt/@vite/client:520:13)
```

**Comment by flapili** [comment]
this config worked in 3.6.5 (which is pretty old) but not in 3.7

**Comment by manniL** [comment]
Related: https://github.com/nuxt/cli/pull/189

**Comment by flapili** [comment]
should I make another issue for nitro endpoints too ?

**Comment by pi0** [comment]
Nuxi/Nitro soon will recieve an update for unified websocket support. I think it should give less reasons to depend on vite WS API.

**Comment by flapili** [comment]
I mean, http for nitro is affected too (i'm doing a repo at the moment)
