### ISSUE TITLE
`deep: false` on `useAsyncData` doesn't provide native shallowRef behaviour

### ISSUE THREAD

**Issue by warflash** [nuxt/nuxt#25901]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.10.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  @pinia/nuxt@0.5.1
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-6ss7qv?file=store%2FtrueShallow.ts,store%2FasyncDataShallow.ts,pages%2FasyncDataShallow.vue,pages%2FtrueShallow.vue,app.vue,pages%2Findex.vue

### Describe the bug

Setting `deep: false` in `useAsyncData` options doesn't seem to provide the same performance or behaviour as native `shallowRef` does.
As a "workaround" `transform: (d) => markRaw(d)` or `transform: (d) => Object.freeze(d)` seem to to the trick.

On a sidenote, [useAsyncState from vueuse](https://vueuse.org/core/useAsyncState/) does not seem to have the same issue.

### Additional context

Performance Profile of native `shallowRef` clicking the button
![image](https://github.com/nuxt/nuxt/assets/22006082/6244e804-53f3-4b9f-a7dd-a1f34b9f5351)

Profile of `deep: false` `useAsyncData`
![image](https://github.com/nuxt/nuxt/assets/22006082/6bb799c2-a1a0-4b1c-a089-2926633e5e7e)

**Comment by manniL** [comment]
After checking further, the issue seems to appear when using Pinia together with `useAsyncData`.

**Comment by warflash** [comment]
Indeed. I wasn't able to reproduce in plain setup without pinia either, though my attempts have been fairly limited. 
With `markRaw` and `freeze` fixing this though I'm fairly certain this is not strictly related to pinia but rather pinia allows the issue to surface.

**Comment by Mini-ghost** [comment]
I have tried researching this problem in every possible way, and I've discovered that this question actually pertains to Nuxt DevTools.

When I disabled Nuxt DevTools, the performance panel results showed no noticeable difference between `useAsyncData` and plain `shallowRef`.

Profile of native `shallowRef`
![Profile of native shallowRef](https://github.com/nuxt/nuxt/assets/39984251/63979d19-59d1-4d70-b5a8-3bf2555d2600)

Profile of `deep: false` `useAsyncData`
![Profile of deep: false useAsyncData](https://github.com/nuxt/nuxt/assets/39984251/17d3d983-6abc-48e7-b75a-0563fbf267b7)


I believe Nuxt DevTools may inevitably sacrifice some performance during the development period for a better development experience. However, this should not at all affect the use of the production version.

**Comment by warflash** [comment]
I appreciate the investigation @Mini-ghost 🎉 Raised an issue upstream
