### ISSUE TITLE
 Nuxt build error with undici

### ISSUE THREAD

**Issue by emiltsang-flow** [nuxt/nuxt#25907]
### Environment

  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.1 - ~/.nvm/versions/node/v18.17.1/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
  npmPackages:
    @nuxt/core: ^2.12.2 => 2.17.1 
    @nuxt/image: ^0.7.1 => 0.7.1 
    nuxt: 2.17.0 => 2.17.0 

### Reproduction

see logs

### Describe the bug

[fatal] Nuxt build error
  ERROR in ./node_modules/undici/lib/cache/cachestorage.js 13:2
  Module parse failed: Unexpected character '#' (13:2)
  You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
  |    * @type {Map<string, import('./cache').requestResponseList}
  |    */
  >   #caches = new Map()
  |
  |   constructor () {
  @ ./node_modules/undici/index.js 128:27-62
  @ ./node_modules/@firebase/auth/dist/node/index.js
  @ ./node_modules/firebase/auth/dist/index.cjs.js
  @ ./plugins/firebase.js
  @ ./.nuxt/index.js
  @ ./.nuxt/server.js
  @ multi ./.nuxt/server.js

### Logs

```shell-script
[fatal] Nuxt build error
  ERROR in ./node_modules/undici/lib/cache/cachestorage.js 13:2
  Module parse failed: Unexpected character '#' (13:2)
  You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
  |    * @type {Map<string, import('./cache').requestResponseList}
  |    */
  >   #caches = new Map()
  |
  |   constructor () {
  @ ./node_modules/undici/index.js 128:27-62
  @ ./node_modules/@firebase/auth/dist/node/index.js
  @ ./node_modules/firebase/auth/dist/index.cjs.js
  @ ./plugins/firebase.js
  @ ./.nuxt/index.js
  @ ./.nuxt/server.js
  @ multi ./.nuxt/server.js
```

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
