### ISSUE TITLE
useAsyncData types are inferred from getCachedData and not from the handler

### ISSUE THREAD

**Issue by OrlS15** [nuxt/nuxt#25903]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v21.5.0
- Nuxt Version:     3.10.2
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.15.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-ptesuy?file=app.vue

### Describe the bug

```ts
const { data: thisTypeIsCorrect } = await useAsyncData("test", async () => ({ hello: "world!" }));

const { data: thisTypeIsAny } = await useAsyncData("test2", async () => ({ hello: "world!" }), {
  getCachedData: (key) => useNuxtApp().payload.data[key],
});
```

useAsyncData types are inferred from getCachedData and not from the handler.
Is this the behavior it should have?

**Comment by edomod** [comment]
I have the same problem
