### ISSUE TITLE
The nuxt3 public directory cannot access new resources in the production environment.

### ISSUE THREAD

**Issue by wangrunze2023** [nuxt/nuxt#25926]
### Describe the feature

After nuxt3 has npm run build to generate the .output file and successfully deployed it on the server, now I want to add a logo1.png image to the public directory. Why does the browser return 404 through the domain name xxx.com/logo1.png. Does the documentation say that the public folder will not be compiled? Why do I add images to the public file after deployment but cannot access them afterwards?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by markthree** [comment]
@wangrunze2023 you can try [nitro-public-module](https://github.com/markthree/nitro-public-module)，Related issue discussions → [nitro/issues/1918](https://github.com/unjs/nitro/issues/1918)

**Comment by wangrunze2023** [comment]
> [nitro-public-module](https://github.com/markthree/nitro-public-module)，

thank you for your help!
But after installing this nitro-public-module, some errors were reported. It may be that the operation was not correct.


D:\>node .output/server/index.mjs
Listening on http://[::]:3000
[nuxt] [request error] [unhandled] [500] Invalid value "undefined" for header "Content-Type"
  at ServerResponse.setHeader (node:_http_outgoing:648:3)
  at setResponseHeader (/D:/.output/server/chunks/nitro/node-server.mjs:1707:18)
  at /D:/.output/server/chunks/nitro/node-server.mjs:5554:7
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async _callHandler (/D:/.output/server/chunks/nitro/node-server.mjs:2085:7)
  at async Object.handler (/D:/.output/server/chunks/nitro/node-server.mjs:2197:19)
  at async Server.toNodeHandle (/D:/.output/server/chunks/nitro/node-server.mjs:2386:7)
```

```

**Comment by markthree** [comment]
@wangrunze2023 
By default, the nitro-public-module will automatically infer the Content-Type from the file extname, so please make sure all your files have extname.

for example 

- foo ❌
- foo.txt ✔

**Comment by wangrunze2023** [comment]
> @wangrunze2023 By default, the nitro-public-module will automatically infer the Content-Type from the file extname, so please make sure all your files have extname.
> 
> for example
> 
> * foo ❌
> * foo.txt ✔

Thank you for your reply!
After adding this module, this error was reported at startup. I looked at the files in the pbulic directory and found that the suffixes were all complete.

![Uploading 企业微信截图_17089150767638.png…]()

**Comment by markthree** [comment]
@wangrunze2023 I’m sorry, I can’t reproduce it. Can you provide a reproduction repository?

**Comment by wangrunze2023** [comment]
> @wangrunze2023 I’m sorry, I can’t reproduce it. Can you provide a reproduction repository?

I have now regenerated a nuxt3 project, which is brand new and only uses your module, and the same error was reported. If you use it directly locally and open it in the editor, no error will be reported. However, you can use this command locally as long as you run npm run build and package it to generate an .output file.
node .output/server/index.mjs is used for deployment. Finally visit http://localhost:3000/. The same error will be reported. You can copy it. “The key is you need access to the project after it’s deployed.”


**My node version v18.6.1**
New nuxt3 project download address：[https://codeload.github.com/nuxt/starter/tar.gz/refs/heads/v3](https://codeload.github.com/nuxt/starter/tar.gz/refs/heads/v3)

**Comment by markthree** [comment]
@wangrunze2023 Thank you, I have reproduced the issue, and I will fix it today.

**Comment by wangrunze2023** [comment]
I hope you can repair it successfully. This module is quite meaningful. 😄👍

**Comment by wangrunze2023** [comment]
> @wangrunze2023 Thank you, I have reproduced the issue, and I will fix it today.

I hope you can repair it successfully. This module is quite meaningful. 😄👍

**Comment by markthree** [comment]
> I hope you can repair it successfully. This module is quite meaningful. 

@wangrunze2023 Fixed, please update to version 0.0.9

**Comment by wangrunze2023** [comment]
> > I hope you can repair it successfully. This module is quite meaningful.
> 
> @wangrunze2023 Fixed, please update to version 0.0.9


Okay, I'll try it right away

**Comment by wangrunze2023** [comment]
> > I hope you can repair it successfully. This module is quite meaningful.
> 
> @wangrunze2023 Fixed, please update to version 0.0.9

it`s ready. nice! 👍

**Comment by markthree** [comment]
> it`s ready. nice! 👍

nice

**Comment by wangrunze2023** [comment]
> > it`s ready. nice! 👍
> 
> nice

There is a new problem. It is true that no error is reported, but the pictures added to the public directory cannot be accessed 404

**Comment by wangrunze2023** [comment]
> > it`s ready. nice! 👍
> 
> nice

I found that the 404 was because the picture name was in Chinese, so I could access it after changing it to English.

**Comment by markthree** [comment]
> I found that the 404 was because the picture name was in Chinese, so I could access it after changing it to English.

done，please use `v0.0.10`

We should avoid discussing this in the current issue; if you are interested in this package, please submit an issue at [nitro-public-module/issues](https://github.com/markthree/nitro-public-module/issues).

**Comment by vanminhquangtri** [comment]
hello @markthree ,
I also have an app with Nuxt3, my static file video mp4 is larger than 2GB so I can't build these file. I want to copy these file to folder .output/public instead. Is this library can do this? can you please give me example code for this? Thanks
https://github.com/markthree/nitro-public-module

**Comment by markthree** [comment]
@vanminhquangtri Yes, build, then copy, then access.
