### ISSUE TITLE
Reload pages when switch layout.

### ISSUE THREAD

**Issue by HuanVo** [nuxt/nuxt#25921]
### Environment

Development

### Reproduction

No

### Describe the bug

when I am on Page A (belonging to layout 1). I have moved to page B (belonging to layout 2). I realize that. page B has been initialized and run twice. I checked by tracing the console in onMounted. and it came out to the console twice.

**Comment by HuanVo** [comment]
> Would you be able to provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
> 
> More info

https://codesandbox.io/p/devbox/boring-grass-26qjzp?file=%2Fpages%2Fsettings.vue%3A14%2C11&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsxzmx600005356j2fadly0q%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsxzmx600002356jk89l58if%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsxzmx600003356jmqvh0xk4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsxzmx600004356jwazu1qxp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B43.991991876927806%252C56.008008123072194%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsxzmx600002356jk89l58if%2522%253A%257B%2522id%2522%253A%2522clsxzmx600002356jk89l58if%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsy12njs0002356k3r389ut5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A8%252C%2522startColumn%2522%253A21%252C%2522endLineNumber%2522%253A8%252C%2522endColumn%2522%253A21%257D%255D%252C%2522filepath%2522%253A%2522%252Fpages%252Findex.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clsy1lrna0002356kj0y6dyyg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A14%252C%2522startColumn%2522%253A11%252C%2522endLineNumber%2522%253A14%252C%2522endColumn%2522%253A11%257D%255D%252C%2522filepath%2522%253A%2522%252Fpages%252Fsettings.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsy1lrna0002356kj0y6dyyg%2522%257D%252C%2522clsxzmx600004356jwazu1qxp%2522%253A%257B%2522id%2522%253A%2522clsxzmx600004356jwazu1qxp%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clsy0iqez02wz356j8g01teb0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsy0iqez02wz356j8g01teb0%2522%257D%252C%2522clsxzmx600003356jmqvh0xk4%2522%253A%257B%2522id%2522%253A%2522clsxzmx600003356jmqvh0xk4%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clsxznixe005f356jsedpprid%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522clsy0ioch02sp356j4o5cm0uv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clsy0ipec000vdhab2zr90v0d%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsxznixe005f356jsedpprid%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by HuanVo** [comment]
I router from home to setting page. The text 'Setting page onMounted' is write one more.
[Uploading screen-capture (3).webm…]()

**Comment by warflash** [comment]
@HuanVo I can't seem to reproduce the issue with the repro you linked. There's only one "Setting page onMounted" being logged
![image](https://github.com/nuxt/nuxt/assets/22006082/1ff9ef66-db5d-4fd2-8c84-319f0cd8805b)

**Comment by madebyfabian** [comment]
@HuanVo I also cannot reproduce this in the CodeSandbox. It logs only once. Do you still experience this issue?
