### ISSUE TITLE
Runtime config environment variables do not override default values with cloudflare-pages preset

### ISSUE THREAD

**Issue by niklaswolf** [nuxt/nuxt#25925]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.10.0`
- Nuxt Version:     `3.10.3`
- CLI Version:      `3.10.1`
- Nitro Version:    `2.8.1`
- Package Manager:  `pnpm@8.14.1`
- Builder:          `-`
- User Config:      `devtools`, `runtimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-6r61tu

- in normal dev-mode everything works fine, the value from the .env file is printed
- if you build the app with `cloudflare-pages` preset and then run it via `npx wrangler pages dev dist/ --port=3000`, you'll see that the cli says that the variables from `.dev.vars` are picked up, but they aren't used as the app prints the default value from runtime config

### Describe the bug

When building the app with `cloudflare-pages` preset, the env-variables for runtime config are not used in the app correctly.

### Logs

```shell-script
✨ Compiled Worker successfully
 ⛅️ wrangler 3.29.0
-------------------
Using vars defined in .dev.vars
Your worker has access to the following bindings:
- Vars:
  - NUXT_PUBLIC_TEST_VALUE: "(hidden)"
```
```

**Comment by niklaswolf** [comment]
tagging @Atinux because I saw the announcement of nuxt-hub and he might know further details about using the ENV-Variables for `useRuntimeConfig` during runtime in cloudflare-pages preset :)

**Comment by Atinux** [comment]
Might be related to the fact that we don't use `useRuntimeConfig(event)` here: https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/core/runtime/nitro/renderer.ts#L291 but not 100% sure.

What do you think @danielroe ?

**Comment by danielroe** [comment]
Nice catch!

**Comment by pi0** [comment]
Pasasing `event` explicitly when possible is best option.

Also related: https://github.com/unjs/nitro/issues/2054

(in general, I'm afraid only safe point we can say cloudflare pages supports env universally, is when we can opt into Async Context)
