### ISSUE TITLE
Tabs throw warning: Computed is still dirty after getter evaluation

### ISSUE THREAD

**Issue by MickL** [nuxt/nuxt#25943]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v21.6.1
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  bun@1.0.26
- Builder:          -
- User Config:      extends, modules, runtimeConfig, pinia, image, routeRules, app, i18n, security
- Runtime Modules:  @nuxt/ui@^2.14.1
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-4rnoff-spccez?file=app.vue

### Describe the bug

Using tabs as shown in the docs throws multiple warnings:

> [Vue warn] Computed is still dirty after getter evaluation, likely because a computed is mutating its own dependency in its getter. State mutations in computed getters should be avoided.  Check the docs for more details: https://vuejs.org/guide/essentials/computed.html#getters-should-be-side-effect-free

**Comment by manniL** [comment]
Please raise in https://github.com/nuxt/ui

**Comment by DamianGlowala** [comment]
Already raised in Nuxt UI (https://github.com/nuxt/ui/issues/1392) and at source in Headless UI (https://github.com/tailwindlabs/headlessui/issues/2985).

**Comment by MickL** [comment]
Damn I was looking in the wrong repo, thats why I didnt find it
