### ISSUE TITLE
Hydratation issue

### ISSUE THREAD

**Issue by DraftProducts** [nuxt/nuxt#25940]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  nuxt-icon@0.6.8
- Build Modules:    -

### Reproduction

Reproduction : https://stackblitz.com/edit/draftman-nuxt-reproduction-1?file=app.vue

### Describe the bug

Since migrating from nuxt2 to nuxt3, I've noticed a number of hydration problems, particularly with nuxt/content rendering, but as I haven't managed to make a minimal reproduction, here's an example based on the teleport example of the doc.
It happen when we target a dedicted div (from a ID selection).

### Additional context

Code preview :
![image](https://github.com/nuxt/nuxt/assets/29425008/4f6c771d-7e17-4dc3-ae9a-249af4a46476)

Console :
![image](https://github.com/nuxt/nuxt/assets/29425008/559e3e26-9740-40e7-a414-f2285aa07396)

### Logs

```shell-script
[Vue warn]: Hydration children mismatch on <div id=​"teleport">​…​</div>​ 
Server rendered element contains fewer child nodes than client vdom. 
  at <App key=3 > 
  at <NuxtRoot>
```

**Comment by DamianGlowala** [comment]
The following note from the [docs](https://nuxt.com/docs/api/components/teleports) might help you resolve the issue. Either teleport to the `body` or wrap your `<Teleport>` in a `<ClientOnly>` component.
![image](https://github.com/nuxt/nuxt/assets/48835293/835256de-1328-44b9-9ff1-039c5ded049b)

**Comment by manniL** [comment]
Also linking #24840 here for the future 👍
