### ISSUE TITLE
When opening a page of nuxt3 in a qq app window on an apple phone, it reports 500 error code

### ISSUE THREAD

**Issue by mumuchongya** [nuxt/nuxt#25956]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.18.0
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.8.1
- Builder:          -
- User Config:      devtools, app, sourcemap, typescript, modules, site, css, imports, legacy, vite, nitro, runtimeConfig, image
- Runtime Modules:  nuxt-vite-legacy@1.2.0, @nuxt/image@1.1.0, @nuxt/ui@2.11.1, @pinia/nuxt@0.5.1, @pinia-plugin-persistedstate/nuxt@1.2.0, nuxt-swiper@1.2.2, @element-plus/nuxt@1.0.7, @nuxtjs/sitemap@5.1.0
- Build Modules:    -

### Reproduction

uconf.com

### Describe the bug

![500](https://github.com/nuxt/nuxt/assets/151698067/1d0ee828-01a3-499e-895b-590a6d709c53)
When opening a page of nuxt3 in a qq app window on an apple phone, it reports 500 error code

**Comment by mumuchongya** [comment]
> @mumuchongya Although this is not a recommended practice, you can set up in `package.json` ↓
> 
> ```json
> "resolutions": {
>   "ofetch": "npm:ofetch@1.2.1"
> },
> "overrides": {
>   "ofetch": "npm:ofetch@1.2.1"
> }
> ```
> 
> After that, re-run `npm install` and package it again. This should temporarily solve your problem.

Thank you! This is the best solution I've used so far!

**Comment by markthree** [comment]
If someone doesn't have high stability requirements, they can use this module → [markthree/nuxt-fix-ofetch](https://github.com/markthree/nuxt-fix-ofetch)

**Comment by YunYouJun** [comment]
https://github.com/unjs/ofetch/pull/366

**Comment by xiaoruo-lin** [comment]
I also hope the author can solve this problem of QQ browser

**Comment by danielroe** [comment]
This should be resolved in the latest v3.12.1. Would you check?

**Comment by xiaoruo-lin** [comment]
> 此问题应在最新的 v3.12.1 中通过#27441得到解决。如果没有解决，请告诉我，我会很乐意重新打开。🙏

Wow, I'm so surprised, thanks for your reply, I'm even more happy that you are going to deal with this issue, thank you
