### ISSUE TITLE
dynamic components (lazy-xyz) cause hydration error, if the component contains await in setup

### ISSUE THREAD

**Issue by TheTimewaster** [nuxt/nuxt#25958]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.10.2
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-kqbstc

### Describe the bug

When using dynamic components (e.g. `lazy-my-component`) 
```html
<!-- app.vue -->
<template>
  <lazy-hello />
</template>
```

and it contains a async/await in the top level (e.g. `useAsyncData`)

```html
<!-- components/Hello.vue -->
<template>
  <div>
    {{ data }}
  </div>
</template>

<script lang="ts" setup>

// can be a fetch from an API
const getHello = async () => {
  return new Promise((resolve) => {
    setTimeout(() => {
      if (process.server) {
        resolve('Hello from server');
        return;
      }

      resolve('Hello from client');
      return;
    }, 1000);
  });
};
const { data, refresh } = await useAsyncData<string>(
  async () => {
    return getHello();
  }
);
</script>
```
the component is rendered on the server side with the server side content, but the fetch is triggered on the client side again.

This causes a hydration error on client side.

If the component is used without `lazy-` prefix, there are no issues.

### Additional context
I also added the key for `useAsyncData` but it does not help. 

If this is a intended design decision, please update the documentation with a corresponding warning.

**Comment by danielroe** [comment]
This is caused by https://github.com/vuejs/core/issues/6638. Let's track within https://github.com/nuxt/nuxt/issues/18405.
