### ISSUE TITLE
Hydration issue

### ISSUE THREAD

**Issue by DraftProducts** [nuxt/nuxt#25963]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      extends, modules, hooks
- Runtime Modules:  @nuxt/content@2.12.0, @nuxt/ui@2.14.1
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/draftman-nuxt-reproduction-2

### Describe the bug

Since migrating from nuxt2 to nuxt3, I've noticed multiple hydration problems, particularly with nuxt/content rendering.
In this case, it happen when a wrapper is added around ProseImg component.

### Additional context

SSR :
![image](https://github.com/nuxt/nuxt/assets/29425008/2cad03a2-a5c6-44a5-9b3f-65d9ef26abef)

After hydration :
![image](https://github.com/nuxt/nuxt/assets/29425008/60442947-033c-4c61-9320-7fc524b888c1)

### Logs

```shell-script
[Vue warn]: Hydration node mismatch:
- rendered on server: <img src=​"https:​/​/​i.imgur.com/​xyywXJ1.png" alt=​"Test" data-v-inspector=​"components/​content/​ProseImg.vue:​3:​5">​
- expected on client: Symbol(v-cmt) 
  at <Callout icon="i-heroicons-light-bulb" > 
  at <AsyncComponentWrapper icon="i-heroicons-light-bulb" > 
  at <MDCRenderer body= Object data= Object tag="div"  ... > 
  at <ContentRendererMarkdown value= Object excerpt=false tag="div" > 
  at <ContentRenderer value= Object excerpt=false tag="div" > 
  at <ContentQuery path="/" find="one" > 
  at <ContentDoc> 
  at <[...slug] onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <Anonymous key="/" vnode= Object route= Object  ... > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <NuxtLayoutProvider layoutProps= Object key="default" name="default"  ... > 
  at <NuxtLayout> 
  at <App key=3 > 
  at <NuxtRoot>
```

**Comment by danielroe** [comment]
This is because your custom component is rendering a `<div>` which is not valid HTML within `<p>`, which is where Nuxt Content is rendering your prose component.

You can use https://html-validator.nuxtjs.org/ to detect these kind of issues.
