### ISSUE TITLE
"Catch-all Route" catch .js file

### ISSUE THREAD

**Issue by gibkigonzo** [nuxt/nuxt#25962]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Nuxt 3 https://stackblitz.com/edit/github-ddpyg6-tnnjef
Nuxt 2 https://stackblitz.com/edit/github-qzm4pm-1rxdu9

### Describe the bug

In Nuxt2 when I want to use `_.vue` and try to reach some empty file then I get 404 with `cache-control: no-cache,no-store,must-revalidate` and empty result.
For example `/test.js`

In Nuxt3, in the same situation, I use `[...slug]` and when I try to get `/test.js` then it is catched by `[...slug]` and returns 200.

Is this a normal behavior? Is there a config to have same result as is in Nuxt2?

### Additional context
Nuxt2
![Screenshot from 2024-02-26 17-17-20](https://github.com/nuxt/nuxt/assets/42383376/0c257402-744c-4d60-a336-35c9977c111a)

Nuxt3
![Screenshot from 2024-02-26 17-17-02](https://github.com/nuxt/nuxt/assets/42383376/32638a4e-3763-4cb0-bb00-b00df1605ff9)

**Comment by danielroe** [comment]
You can create an `error.vue` and handle the 404. Or use `setResponseStatus(useRequestEvent(), 404)`?

A catchall is technically saying that any route is _found_ unless you choose to throw a 404 error.

**Comment by gibkigonzo** [comment]
@danielroe I can handle this in `error.vue`, but it also work in the same way for files from `_nuxt/` dir. Shouldn't `serve-placeholder` handle those missing files?
