### ISSUE TITLE
`i18n ally` dose not find 'i18n-ally-key-missing' in `Nuxt 3.10.x`

### ISSUE THREAD

**Issue by yeonjulee1005** [nuxt/nuxt#25970]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.0.0
- Nuxt Version:     3.9.3
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  bun@1.0.7
- Builder:          -
- User Config:      devtools, app, css, modules, build, colorMode, ui, components, imports, pinia, dayjs, i18n, stylelint, supabase, vueuse, runtimeConfig
- Runtime Modules:  @nuxt/devtools@1.0.8, @nuxt/image@1.3.0, @nuxt/ui@2.14.1, @nuxtjs/color-mode@3.3.2, @nuxtjs/i18n@8.1.1, @nuxtjs/supabase@1.1.6, @nuxtjs/stylelint-module@5.2.0, nuxt-icon@0.6.8, @pinia/nuxt@0.5.1, @pinia-plugin-persistedstate/nuxt@1.2.0, @vueuse/nuxt@10.8.0, dayjs-nuxt@2.1.9
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-nvni9s?file=locales%2Fen.ts,locales%2Fko.ts,app.vue,components%2FLanguageChange.vue

### Describe the bug

when using Nuxt 3.10.x version, 
it dosen't find `locale file` like below,

<img width="1746" alt="스크린샷 2024-02-27 오전 11 22 15" src="https://github.com/nuxt/nuxt/assets/57179957/d7161537-8192-4d07-8ff6-e24e8f352d30">

---

but, when using Nuxt 3.9.3 version,
it work normally like this,
<img width="932" alt="스크린샷 2024-02-27 오전 11 19 54" src="https://github.com/nuxt/nuxt/assets/57179957/f348352d-59e6-437f-9d36-fecc3859bacb">

---

I'm not sure why this happens starting from version 3.10.0.
I created a reproduction URL, but since there is no i18n-ally extension in stackblitz, I would appreciate it if you could run it in vs code.

### Logs

```shell-script
// error message in vs code
No locale files loaded. Probably there is something wrong with your project config.

// in .vue error
ko: i18n key "placeholder.password" does not exist(i18n-ally-key-missing)
```

**Comment by danielroe** [comment]
I suspect this is not a Nuxt issue. Would you raise this upstream at [`i18n-ally`](https://github.com/lokalise/i18n-ally) instead? 🙏
