### ISSUE TITLE
this error [GET] "/_nuxt/builds/meta/test.json": 404

### ISSUE THREAD

**Issue by MohitNN** [nuxt/nuxt#25977]
### Environment

![Screenshot (22)](https://github.com/nuxt/nuxt/assets/83907255/614bb5d8-3fce-43a2-baf4-4d92cc535ccc)

**video**
https://www.loom.com/share/35a5eed434294ef48bbcdc7e3c100e6d?sid=ec32d91c-e3d3-48bc-a7b2-e7afc02cd507

I am getting this error after doing live my code

### Reproduction

![Screenshot (22)](https://github.com/nuxt/nuxt/assets/83907255/614bb5d8-3fce-43a2-baf4-4d92cc535ccc)
**video**
https://www.loom.com/share/35a5eed434294ef48bbcdc7e3c100e6d?sid=ec32d91c-e3d3-48bc-a7b2-e7afc02cd507

I am getting this error after doing live my code

### Describe the bug

![Screenshot (22)](https://github.com/nuxt/nuxt/assets/83907255/614bb5d8-3fce-43a2-baf4-4d92cc535ccc)
I am getting this error after doing live my code

### Additional context

![Screenshot (22)](https://github.com/nuxt/nuxt/assets/83907255/614bb5d8-3fce-43a2-baf4-4d92cc535ccc)
I am getting this error after doing live my code

**Comment by ex-wangyanbo001** [comment]
hello,这个问题最后是怎么解决的啊，我这边也遇到了这个问题  偶尔会遇到/_nuxt/builds/meta/xxx.json 404的问题
