### ISSUE TITLE
Add partitioned option to useCookie

### ISSUE THREAD

**Issue by achenieux-eyein** [nuxt/nuxt#25984]
### Describe the feature

Hello, currently Nuxt 3 useCookie composable does not have the option for a cookie to be partitioned.

Google Chrome is phasing out third-party cookies and it should be the case by the end of 2024. 

I have a use case of a website that must work inside an iframe, so I have to set SameSite to "None" but it's then considered as a 3rd party cookie. So the new CHIPS partitioned option is the solution as presented here: [https://developers.google.com/privacy-sandbox/3pcd/chips?hl=en](https://developers.google.com/privacy-sandbox/3pcd/chips?hl=en)

I want to be able to do something like this:
`const cookie = useCookie('mycookie', {secure: true, sameSite: 'none', httpOnly: false, partitioned: true})`

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by DamianGlowala** [comment]
There's a pending PR for adding `Partitioned` attribute:
https://github.com/unjs/cookie-es/pull/21

**Comment by achenieux-eyein** [comment]
Any news on this? I see the unjs/cookie-es PR you sent is now merged.

**Comment by DamianGlowala** [comment]
You can already do this in Nuxt:
```
useCookie('foo', {
  partitioned: true
})
```

**Comment by achenieux-eyein** [comment]
Oh thank you, I just tested it and it seems to work. I just checked the documentation and it's not here yet: [https://nuxt.com/docs/api/composables/use-cookie](https://nuxt.com/docs/api/composables/use-cookie)
