### ISSUE TITLE
EBUSY: resource busy or locked, access '\\\\.\\pipe\\nitro\\worker-11280-1.sock'

### ISSUE THREAD

**Issue by marcoborsoi** [nuxt/nuxt#25981]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.11.1
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.15.3
- Builder:          -
- User Config:      app, build, css, experimental, imports, modules, routeRules, runtimeConfig, typescript, apollo, i18n, dev, devtools, debug, nitro, vite
- Runtime Modules:  @nuxtjs/apollo, @nuxtjs/device, @nuxtjs/i18n@8.1.1, @pinia/nuxt@0.5.1
- Build Modules:    -

### Reproduction

Unfortunately I cannot provide an reproduction. Please let me know if the information provided in the description is enough to understand the problem.

### Describe the bug

I am getting this error on Windows when reaching certain routes of my Nuxt application.
 
`Error: EBUSY: resource busy or locked, access '\\\\.\\pipe\\nitro\\worker-11280-1.sock'`

The error is the same described in https://github.com/nuxt/nuxt/issues/22759

Regarding the logs, initially I see an Apollo Error:

```
at C:\Users\marco.borsoi\Workspace\lq-web-apps\node_modules\.pnpm\@apollo+client@3.8.8_graphql-ws@5.14.2_graphql@16.8.1_react-dom@18.2.0_react@18.2.0\node_modules\@apollo\client\core\QueryManager.js:714:88at both (C:\Users\marco.borsoi\Workspace\lq-web-apps\node_modules\.pnpm\@apollo+client@3.8.8_graphql-ws@5.14.2_graphql@16.8.1_react-dom@18.2.0_react@18.2.0\node_modules\@apollo\client\utilities\observables\asyncMap.js:23:31)at C:\Users\marco.borsoi\Workspace\lq-web-apps\node_modules\.pnpm\@apollo+client@3.8.8_graphql-ws@5.14.2_graphql@16.8.1_react-dom@18.2.0_react@18.2.0\node_modules\@apollo\client\utilities\observables\asyncMap.js:12:72at new Promise ()at Object.then (C:\Users\marco.borsoi\Workspace\lq-web-apps\node_modules\.pnpm\@apollo+client@3.8.8_graphql-ws@5.14.2_graphql@16.8.1_react-dom@18.2.0_react@18.2.0\node_modules\@apollo\client\utilities\observables\asyncMap.js:12:24)at Object.error (C:\Users\marco.borsoi\Workspace\lq-web-apps\node_modules\.pnpm\@apollo+client@3.8.8_graphql-ws@5.14.2_graphql@16.8.1_react-dom@18.2.0_react@18.2.0\node_modules\@apollo\client\utilities\observables\asyncMap.js:25:49)at notifySubscription (C:\Users\marco.borsoi\Workspace\lq-web-apps\node_modules\.pnpm\zen-observable@0.8.15\node_modules\zen-observable\lib\Observable.js:140:18)at onNotify (C:\Users\marco.borsoi\Workspace\lq-web-apps\node_modules\.pnpm\zen-observable@0.8.15\node_modules\zen-observable\lib\Observable.js:179:3)at SubscriptionObserver.error (C:\Users\marco.borsoi\Workspace\lq-web-apps\node_modules\.pnpm\zen-observable@0.8.15\node_modules\zen-observable\lib\Observable.js:240:7)
```

But when adding a console.log at the `apollo:error` hook, I can see the `EBUSY: resource busy or locked` inside the error object:

```js
{
  operation: {
    variables: {
      limit: 10,
      locale: 'fr',
      device: 'desktop',
      url: '/commun/tag/test-ced'
    },
    extensions: {},
    operationName: 'GetGamesByLabel',
    query: { kind: 'Document', definitions: [Array], loc: [Location] }
  },
  networkError: Error [ServerError]: Response not successful: Received status code 503
      at Module.throwServerError (C:\Users\marco.borsoi\Workspace\lq-web-apps\node_modules\.pnpm\@apollo+client@3.8.8_graphql-ws@5.14.2_graphql@16.8.1_react-dom@18.2.0_react@18.2.0\node_modules\@apollo\client\link\utils\throwServerError.js:2:17)
      at parseJsonBody (C:\Users\marco.borsoi\Workspace\lq-web-apps\node_modules\.pnpm\@apollo+client@3.8.8_graphql-ws@5.14.2_graphql@16.8.1_react-dom@18.2.0_react@18.2.0\node_modules\@apollo\client\link\http\parseAndCheckHttpResponse.js:124:31)
      at C:\Users\marco.borsoi\Workspace\lq-web-apps\node_modules\.pnpm\@apollo+client@3.8.8_graphql-ws@5.14.2_graphql@16.8.1_react-dom@18.2.0_react@18.2.0\node_modules\@apollo\client\link\http\parseAndCheckHttpResponse.js:182:48
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    response: Response {
      [Symbol(realm)]: null,
      [Symbol(state)]: [Object],
      [Symbol(headers)]: [HeadersList]
    },
    statusCode: 503,
    result: `<!DOCTYPE html><html><head><title>Error: EBUSY: resource busy or locked, access '\\\\.\\pipe\\nitro\\worker-11280-1.sock' | Nuxt</title>...`,
  graphQLErrors: undefined,
  forward: [Function (anonymous)]
}
```

### Additional context

For context, the main difference between this specific route to others is that this one makes use of several carousel components where each one fetches data from a GraphQL API through `@nuxtjs/apollo`. The composition of the page is controlled by a headless CMS (Contentstack) and, during my tests, this error started to happen once we have 6 carousels.

BTW, the whole application runs just fine on Mac.

I tested the same application in WSL2 and this route works, but the whole application is extremely slow and I am likely running into https://github.com/nuxt/cli/issues/209
 
Any help or idea is appreciated! Thank you! 🙏

**Comment by danielroe** [comment]
Would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏

**Comment by marcoborsoi** [comment]
@danielroe Sure, I'm on it. Thank you!

**Comment by maitlandmarshall** [comment]
I'm also getting this, basically a transient issue when the dev server is spammed with too many requests (these are performing MSSQL queries, maybe this is impacting it)
![image](https://github.com/nuxt/nuxt/assets/38200645/30018f60-69c5-424e-b361-9f3436123ee0)

**Comment by marcoborsoi** [comment]
@danielroe @pi0 I was able to make a simplified Nuxt app to reproduce the issue on Windows: https://stackblitz.com/edit/nuxt-apollo-demo-cd35uc?file=nuxt.config.ts

Please let me know if you prefer to continue the discussion here or if we should move it to Nitro.

I don't why, but it my case, an `EBUSY` is only thrown by the Nodejs Event Loop when there are too many requests to the API and they are passing by a proxy. By disabling the proxy, the operation don't get locked.

I found this in [node/deps/uv/docs/src/loop.rst](https://github.com/nodejs/node/blob/40565e90b4fc72649cd4801b01d6e0e00f21b06c/deps/uv/docs/src/loop.rst#L82) that might bring some light:

> Releases all internal loop resources. Call this function only when the loop
    has finished executing and all open handles and requests have been closed,
    or it will return UV_EBUSY. After this function returns, the user can free
    the memory allocated for the loop.

**Comment by danielroe** [comment]
It would be fantastic if you could reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏

If it only recurs with Nuxt, let me know and I'll reopen it here.

**Comment by TimGuendel** [comment]
I am facing this as well. I cannot really reproduce it, but so far this is the context:
- Nuxt 3.12.4 with Nitro 2.9.7
- Yarn 4.3.0, Node v20.14.0
- Dev Mode only
- Many requests with useAsyncData with transform and getCachedData
- Catch all route with proxyRequest()

Eventually a 503 would happen and an error page would return:

`<title>Error: EBUSY: resource busy or locked, access '\\.\pipe\nitro\worker-34972-1.sock' | Nuxt</title>`

I am afraid that's all I have 👀

**Comment by Hunsfer** [comment]
@TimGuendel 

I just came across this. Have you done something about this yourself?

**Comment by TimGuendel** [comment]
> [@TimGuendel](https://github.com/TimGuendel)
> 
> I just came across this. Have you done something about this yourself?

I have not 😐

**Comment by pawelgur** [comment]
Started bumping into similar issue after updating some of the packages - randomly getting 503 resource locked errors for subrequests done by Nuxt on server. Seems to be caused by some new dependency version, though not sure which.
```
└─┬ nuxt@3.11.2
  └── nitropack@2.9.6 (tried with 2.9.7
```
node@v18.20.4 (seems slightly better after updating from 18.17.0, [ref](https://github.com/nuxt/nuxt/issues/22759)) ,
npm@10.7.0

Using custom js proxy based on `http-proxy-middleware` module for proxying to local dev calls to staging env.

**Comment by avinmaster** [comment]
+1

**Comment by TimGuendel** [comment]
> [@TimGuendel](https://github.com/TimGuendel)
> 
> I just came across this. Have you done something about this yourself?

So this started happening again. Not sure if it's related or if it helps, but I changed code from this

```
const [{ data: data1 }, { data: data2 } ]await Promise.all([
    useAsyncData([...]),
    useAsyncData([...]),
 ]);
```

to

```
const { data: data1 } = awaituseAsyncData([...]),
const { data: data2 } = awaituseAsyncData([...]),
```

After doing this, the EBUSY errors did not happen anymore.
Note that the error only occured when running in DEV mode with `pnpm run dev`
