### ISSUE TITLE
Layout issues (error page, slot/NuxtPage props)

### ISSUE THREAD

**Issue by kamran-12** [nuxt/nuxt#25982]
Initially I declared my default layout using `<slot>` for router-views because that's what was [recommended in the documentation](https://nuxt.com/docs/guide/directory-structure/layouts#default-layout). This worked but I noticed that the error page does not get the layout. Even [this](https://nuxt.com/docs/guide/directory-structure/layouts#overriding-a-layout-on-a-per-page-basis) and this:
```
<script setup lang="ts">
// You might choose this based on an API call or logged-in status
const layout = "default";
</script>

<template>
  <NuxtLayout :name="layout">
    <NuxtPage />
  </NuxtLayout>
</template>
```
did not change the problem that the error page didn't get the layout. This is the first bug in my opinion. So I did a workaround:
```
<script setup lang="ts">
import type { NuxtError } from '#app'
import DefaultLayout from "/layouts/default.vue"
const props = defineProps({
    error: Object as () => NuxtError
})
</script>
<template>
    <DefaultLayout>
    <div>
        <h1>{{ "Error " + error?.statusCode }}</h1>
        <pre>{{ JSON.stringify(error, null, 4) }}</pre>
        <NuxtLink to="/">Go back home</NuxtLink>
    </div>
    </DefaultLayout>
</template>
```
This was ugly but worked however eventually I noticed another problem. I tried passing props from layout to page components and that wasn't working (second bug). So I fixed (?) the problem by replacing `<slot>` on the layout with `<NuxtPage />`. This again worked but I faced another problem: Now the error page content (other than layout) isn't visible. So now the "best" choice I know I have is to have an error page without a layout, but that's not what I want. Do you confirm my bug reports? What should I do? Thanks.

**Comment by coltisor** [comment]
I guess the solution is to have both <slot/> and <NuxtPage/>? 

I am facing the same issue with Nuxt3.

Here's reproduction: https://stackblitz.com/edit/nuxt-starter-418a3t?file=error.vue

If you try to access an unexisting page, you get the error page, but you only see the Layout, as the <NuxtPage> does not return the error page content.

**Comment by Qonflux** [comment]
Using both <slot /> and <NuxtPage /> causes issues as well, fixed it by using this in /layouts/default.vue:

```
<script setup>
const error = useError()
</script>

<template>
  <AppHeader />
  <NuxtPage v-if="!error" />
  <slot v-else />
  <AppFooter />
</template>
```

A fix for this problem would be to allow content of error.vue to show when using <NuxtPage />. This just feels like a hacky workaround...
