### ISSUE TITLE
generate bug

### ISSUE THREAD

**Issue by mark980828** [nuxt/nuxt#25989]
### Environment

 System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i3-10100F CPU @ 3.60GHz   
    Memory: 8.10 GB / 15.93 GB
  Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - F:\Other\nodejs\global\yarn.CMD
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.0 - F:\Other\nodejs\global\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (117.0.2045.36)
    Internet Explorer: 11.0.19041.1566

### Reproduction

https://stackblitz.com/edit/github-7jsgdv?file=nuxt.config.js

### Describe the bug
my test site:http://nuxt2.cqyx.vip
When I use the npm run generate,cdn prefix of //, the example.
{.
build: {.
publicPath: "//static.cqyx.vip/nuxt2/"
}.
}.
Static resources will report an error and there will be two manifest.js references
![1709078320640](https://github.com/nuxt/nuxt/assets/36203842/74354798-fd66-4957-aa59-19e23c583e73)

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by mark980828** [comment]
> If it's a critical or security issue,

it's a critical issue.

**Comment by danielroe** [comment]
Does this reproduce if you do not use `//` but use a protocol?

**Comment by mark980828** [comment]
> Does this reproduce if you do not use `//` but use a protocol?

If not used, this problem will not occur.

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
