### ISSUE TITLE
The Baidu search engine has stopped including sites written by Nuxt3 in recent months

### ISSUE THREAD

**Issue by Macrohoo** [nuxt/nuxt#25992]
### Environment

"nuxt": "3.0.0"

### Reproduction

Not a code debugging issue

### Describe the bug

Our site has been no longer included in Baidu Search for the past two months, and at first I thought it was caused by the quality of the articles on our website. So I looked for websites of larger companies in China that use the NuxT3 framework, and found that ByteDance's rare earth nuggets also use the Nuxt3 technology stack. Their website has not been indexed by Baidu in the past month. I don't know if it's because of the details at the framework level that Baidu has blocked some problems with the nuxt3 framework.

As infrastructure construction technicians, you may be able to contact the rule-making technicians of Baidu's crawler and find the problem, and I don't know if this kind of problem feedback is appropriate here.

 ByteDance's site: https://juejin.cn

thanks！

![1708396327588](https://github.com/nuxt/nuxt/assets/15125523/6372ee4a-1aef-4680-88b0-b2c2eb6464ac)

**Comment by danielroe** [comment]
I wonder if this is an issue of a syntax being used in Nuxt code that isn't understood by the Baidu engine. Do you have any information you could point me to to start investigation, or any contacts at Baidu?

**Comment by Macrohoo** [comment]
Sorry, I can't provide anything about nuxt due to possible syntax errors.
Because it can be indexed by Bing and Google normally
We tried to describe the problem to Baidu agents, but the agents who handled such simple problems did not understand the root cause of the problem.
This type of agent handles the problem in a way that is based on simple prevarication reasons.

**Comment by geminigeek** [comment]
> I wonder if this is an issue of a syntax being used in Nuxt code that isn't understood by the Baidu engine. Do you have any information you could point me to to start investigation, or any contacts at Baidu?

this is a serious issue if at all , the telemetry data if it includes domain names , should be used to cross verify the scale of this

**Comment by breathshoria** [comment]
We experiencing the same issue, Baidu can't crawl anything unless main page, it's ignoring all sitemap links
It's hard to understand what's the cause, Baiduspider requests are getting 200 code

**Comment by manniL** [comment]
Might [this issue](https://github.com/nuxt/nuxt/issues/24229) be related in some way and Baidu could stop crawling because of console errors (which would be strange but might happen)?

**Comment by breathshoria** [comment]
> Might [this issue](https://github.com/nuxt/nuxt/issues/24229) be related in some way and Baidu could stop crawling because of console errors (which would be strange but might happen)?

Thanks for pointing to this bug!
I guess, that's not directly related, because it seems Baiduspider using engine compatible with Mozilla/5.0

We have behaviour that bot opens mainpage, downloading all the scripts (for some reason with HTTP1, instead of H2) and never go further, I don't see any errors that can stop bot from crawling
Also we can succsefully open any of our pages in Baidu console, them can be verified, parsed and rendered

This is such a global, broad and unclear issue, that's currently hard to identify its causes, that's also may not be related to Nuxt itself but Vue3 core

**Comment by Macrohoo** [comment]
Recently, this problem has been solved and has begun to be included. It should have been dealt with by Baidu. Anyway, I haven't changed our site. ❤️ thanks
