### ISSUE TITLE
`useNuxtData` cannot get the latest data

### ISSUE THREAD

**Issue by Dylan0916** [nuxt/nuxt#25990]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

Here is a minimal reproduction:
[stackblitz](https://stackblitz.com/edit/github-dgrw8m?file=pages%2F[id]%2Findex.vue)

### Describe the bug

Please access the page directly: `/1`

I use `useAsyncData` in `layout`, and use `useNuxtData` in the component (`/[id]/index.vue`) in `page` to read data, but when I switch route, `useNuxtData` returns `null`, why is this?

**Comment by adrienZ** [comment]
your layout component script setup function "only executes once when the component is first imported"
> https://vuejs.org/api/sfc-script-setup.html#basic-syntax

so `useAsyncData` will only run once with  the first route param id it finds (1, 2 or undefined).

![image](https://github.com/nuxt/nuxt/assets/10186993/dba3af96-cf1b-445d-ad17-6360d65ca0e8)

you might want to to move your fetching logic in the page as it will re-render on navigation, see [fork](https://stackblitz.com/edit/github-dgrw8m-ke6byx?file=pages%2F%5Bid%5D.vue)

the caching implementation may need to change depending on what you to do but `useAsyncData` provides a [few ways](https://nuxt.com/docs/api/composables/use-async-data#params)

**Comment by Dylan0916** [comment]
> your layout component script setup function "only executes once when the component is first imported"

thank you so much~ I understand why 😆
