### ISSUE TITLE
Don't compile/obfuscate certain part of code

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/nuxt#25996]
### Environment

Working directory: /home/projects/nuxt-starter-xccgew                                                              9:31:53
Nuxt project info:                                                                                                 9:31:53

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                        9:31:53

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Reproduction

https://stackblitz.com/edit/nuxt-starter-xccgew

### Describe the bug

We have integration with this provider and we need this code snippet not to be obfuscated, since the variable name should not change.
Is there a way/tag to tell the compiler to leave the code snippet as is?

https://wiki.awin.com/index.php/Advertiser_Tracking_Guide/Standard_Implementation#Conversion_Tag

**Comment by gianLuigiL** [comment]
If you need it asap you could declare it like window.AWIN = {}. Provided you need to have it run on the client or it'll crash.

**Comment by danielroe** [comment]
I think this is probably correct:

```ts
if (import.meta.client) {
	window.AWIN = {};
	window.AWIN.Tracking = {};
	window.AWIN.Tracking.Sale = {
	  amount: 10,
	  currency: 'EUR',
	  orderRef: 'WWGDGSDG',
	  parts: `SALE:50`,
	  voucher: '',
	  custom: ['CREDIT'],
	  channel: 'aw',
	  test: 1,
	};
}
```
