### ISSUE TITLE
CSS @import with Layer not supported

### ISSUE THREAD

**Issue by darylteo** [nuxt/nuxt#25995]
### Describe the feature

Hi I've been trying out PrimeVue, and part of PrimeVue's system recommends that any reset styles should be partitioned into a layer. 

Thus meaning that I would be required to use this syntax.

```
<style>
@import url layer(layer-name);
</style>
```

This, unfortunately, does not work with Nuxt as nuxt rewrites the import into a `link` for HMR

```
import { createHotContext as __vite__createHotContext } from "/_nuxt/@vite/client";import.meta.hot = __vite__createHotContext("/node_modules/@unocss/reset/tailwind-compat.css");import { updateStyle as __vite__updateStyle, removeStyle as __vite__removeStyle } from "/_nuxt/@vite/client"
...
document.querySelectorAll(`link[href="/_nuxt/node_modules/@unocss/reset/tailwind-compat.css"]`).forEach(i=>i.remove())
```

And unfortunately, at this point, there is no support for this draft proposal 

https://github.com/w3c/csswg-drafts/issues/5853

```
<link rel="stylesheet" href="remedy.css" layer="reset">
```
So it's impossible for Nuxt to write it in that way.

---

The only workarounds I can think of is

Option A:  pull a reset from a third party CDN jsdelivr/unpkg etc. so that it does not attempt to inject it.

```
<style>
@import 'https://cdn.jsdelivr.net/npm/@unocss/reset/tailwind.min.css' layer(reset);
</style>
```

Option B: add a way to inline the styles into the html instead of an import and update it for HMR so we can add the `@layer` directive.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by Tanvir-rahman** [comment]
Would it be possible for a beginner to address this issue? Could you kindly provide a pointer or reference to help get started on resolving it?

**Comment by danielroe** [comment]
Start by looking in https://github.com/nuxt/nuxt/blob/c045c4b1546cdbc4a31eabfbed95d78392c45f1d/packages/vite/src/plugins/dev-ssr-css.ts#L10-L30.

This logic likely needs to be updated.

**Comment by Tanvir-rahman** [comment]
Can you please give hints about what to do in the file? Totally beginner in the context. 
Otherwise i would prefer to watch existing issues and their pr to learn more about the codebase. Thanks

**Comment by danielroe** [comment]
Just checking this - it seems to work fine 🤔 

![CleanShot 2024-07-01 at 22 52 35@2x](https://github.com/nuxt/nuxt/assets/28706372/78b475f8-7dd5-4666-a2f7-56322ab72b48)

Would you provide an example of what isn't working?

**Comment by darylteo** [comment]
This is a pretty old issue 😅 as is tradition, even after checking out my old commits, this issue no longer seems to affect my codebase.

I have no idea what happened there. Happy to close as it works in my current codebase as is after removing my workarounds. 🙏
