### ISSUE TITLE
Component placed in nuxt component cannot inject inline styles

### ISSUE THREAD

**Issue by Nisekoi5** [nuxt/nuxt#25991]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.19.0
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.15.1
- Builder:          -
- User Config:      devtools, ssr, features, build, modules, vite
- Runtime Modules:  ()
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-11vucf-dwcpwg?file=app.vue

### Describe the bug

Happens in production build , The text does not turn red
![image](https://github.com/nuxt/nuxt/assets/49276902/2ff459c3-63a9-4cc8-8b42-37d373527d5b)
If the component is removed from pages/index.vue and placed outside the `NuxtLayout` component in `app.vue` and rebuilt, the inline style can be injected normally.
text turns red
![image](https://github.com/nuxt/nuxt/assets/49276902/5e14f5b0-a5ca-4704-8df6-e8347508dea8)

### Additional context

No styles are injected in the development environment (is this planned?)

**Comment by danielroe** [comment]
this is no longer reproducible
