### ISSUE TITLE
Support runtimeConfig as a function to load remote configs

### ISSUE THREAD

**Issue by enkot** [nuxt/nuxt#26001]
### Describe the feature

There are cases when we need to load config asynchronously during build (f.e. from LauchDarkly). Currently it is possible by creating a Nuxt module, fetching data and writing it to the `runtimeConfig` object. And this is absolutely valid solution 👍 
But it would be nice to allow users to use async functions as values ​​inside runtimeConfig that will be run and resolved at build time, for example:
```ts
export default defineNuxtConfig({
  runtimeConfig: {
    public: {
      phoneCodes: async () => {
        return $fetch('/remote-server/phoneCodes')
      }
    }
  }
})
```
The only problem it that function should explicitly specify return type, so Untyped can properly generate schema type.

Or `runtimeConfig` as a function:
```ts
export default defineNuxtConfig({
  runtimeConfig: async () => {
    const phoneCodes = await $fetch('/remote-server/phoneCodes')

    return {
      public: {
        phoneCodes
      }
    }
  }
})
```

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by MuhammadM1998** [comment]
As a workaround `nuxt-prepare` module can achieve this [(ref)](https://github.com/johannschopplich/nuxt-prepare/issues/6). a plugin also should work.
```ts
// `server.prepare.ts`
import { defineNuxtPrepareHandler } from 'nuxt-prepare/config'

export default defineNuxtPrepareHandler(async () => {
  // Do some async magic here, e.g. fetch data from an API

  return {
    // If not set, defaults to `true`
    ok: true,

    // Overwrite the runtime config variable `foo`
    runtimeConfig: {
      public: {
        foo: 'Overwritten by "server.prepare" script'
      }
    }
  }
})
```
