### ISSUE TITLE
typescript error on Ref  type

### ISSUE THREAD

**Issue by minkoonim** [nuxt/nuxt#26009]
### Environment

```
- Operating System: Linux
- Node Version:     v20.11.0
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.9.0
- Package Manager:  bun@1.0.29
- Builder:          -
- User Config:      app, devtools, modules, build, sourcemap, runtimeConfig, css, imports
- Runtime Modules:  @pinia/nuxt@0.5.1, @pinia-plugin-persistedstate/nuxt@1.2.0, @unocss/nuxt@0.58.5, @vueuse/nuxt@10.9.0
- Build Modules:    -
```

### Reproduction

```
const { data: testData } = useAsyncData<{ id: 1, name: string }[] | null>('some', () => $fetch('/api/some'))
type TestDataType = MaybeRef<any[] | null>
type TestGeneric<T extends TestDataType> = T extends MaybeRef<infer U> ? U : T
type Test = TestGeneric<typeof testData>
```

![image](https://github.com/nuxt/nuxt/assets/38183949/18fa6dc0-e4a0-41f7-a626-4a0dd113d868)

### Describe the bug

It was all fine till yesterday I think,
I ran package updates, then this happenes.
It also happens on vueuse's some functions.

Any ref types that goes into generic or function arg throws this error about [RefSymbol]

```
Type 'Ref<{ id: 1; name: string; }[] | null>' does not satisfy the constraint 'TestDataType'.
  Property '[RefSymbol]' is missing in type 'Ref<{ id: 1; name: string; }[] | null>' but required in type 'Ref<any[] | null>'.ts(2344)
reactivity.d.ts(420, 5): '[RefSymbol]' is declared here.
```

### Additional context

I see vue's last update is from 20 hours ago,
so I did 
nuxi cleanup
removed all the caches and lockfile of package manager
removed node_modules
and re installed with vue 3.4.20,
but it wasn't fixed.

**Comment by minkoonim** [comment]
> > It also happens on vueuse's some functions.
> 
> Can you reproduce this with plain vue too?

uh.. not on plain vue, but on same project I just go:
```
<script>
const el = ref<HTMLElement | null>(null)
const test = useElementBounding(el)
</script>

<template>
  <div ref="el" />
</template>
```
![image](https://github.com/nuxt/nuxt/assets/38183949/f98dccc5-e179-4cf7-bbd2-9228075b1a9a)

**Comment by Nicolas-Yazzoom** [comment]
The same error occurs when using the `storeToRefs` function from pinia. It worked correctly in nuxt 3.10.1 but it broke in 3.10.2.
Instead of typing refs as `Ref<T>` it types them as

```TypeScript
 Ref<{
    value: T;
    [RefSymbol]: true;
}
```

You can pin your nuxt version (remove `^`) to 3.10.1 and run `npx nuxi upgrade --force` as a temp solution for now. I checked the release notes but couldn't link it to changes there.

**Comment by manniL** [comment]
@Nicolas-Yazzoom could you check if it works with nuxt 3.10.1 and the latest Vue version?

**Comment by danielroe** [comment]
As @manniL says, this is unlikely to be an issue in Nuxt but more likely an issue with Volar + Vue. (Volar sometimes has type issues when multiple Vue versions are installed, and likely when you upgraded to v3.10.2 your Vue version was updated too.)

**Comment by minkoonim** [comment]
> As @manniL says, this is unlikely to be an issue in Nuxt but more likely an issue with Volar + Vue. (Volar sometimes has type issues when multiple Vue versions are installed, and likely when you upgraded to v3.10.2 your Vue version was updated too.)
> 
> I don't get this issue:
> 
> ![CleanShot 2024-03-03 at 21 11 43@2x](https://private-user-images.githubusercontent.com/28706372/309581798-a0d9332c-1bb1-4604-8d47-541b080d652a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MTE2NjQsIm5iZiI6MTcwOTUxMTM2NCwicGF0aCI6Ii8yODcwNjM3Mi8zMDk1ODE3OTgtYTBkOTMzMmMtMWJiMS00NjA0LThkNDctNTQxYjA4MGQ2NTJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDAwMTYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlNWJmMGEzOThmZTMzN2M1YTI0ZmQzOGMyZDE3YjVhODUxZTExOTU5MGNhZTEyOGY2ZTgzZjQ4NGVjOWIyZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cECdUUv-Cta5exa8rOMubCnBFTTUx6-Ao_tFWLXEW2Q)

Thanks man, I will try re installing volar
By the way, your font and theme looks so fine,
please tell me what they are?

**Comment by manniL** [comment]
@minkoonim Daniel uses Dank Mono (see his [/uses](https://roe.dev/uses) page)

**Comment by Nicolas-Yazzoom** [comment]
> @Nicolas-Yazzoom could you check if it works with nuxt 3.10.1 and the latest Vue version?

My original post used `nuxt 3.10.2` and `Vue 3.4.15`. This gave the weird type issue.
I just tested with `nuxt 3.10.1` and current latest vue version `3.4.21`. This worked as expected (`nuxt 3.10.1` always worked for me).
I also tested with `nuxt 3.10.3` and `Vue 3.4.21`. The issue doesn't occur here as well so it appears to be fixed somehow.
