### ISSUE TITLE
How to delete the crossorigin attribute of the link element?

### ISSUE THREAD

**Issue by unicape** [nuxt/nuxt#26000]
### Describe the feature

How to delete the crossorigin attribute of the link element?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
What do you mean? Could you provide a reproduction to make the question clearer? 🙏
