### ISSUE TITLE
@ant-design-vue/nuxt deps error

### ISSUE THREAD

**Issue by bobby169** [nuxt/nuxt#26007]
### Environment

<img width="587" alt="image" src="https://github.com/nuxt/nuxt/assets/4695440/bc827ed3-623d-44f0-ba59-3901602754e5">

### Reproduction

https://github.com/bobby169/nuxt-app-bug

### Describe the bug

<img width="899" alt="image" src="https://github.com/nuxt/nuxt/assets/4695440/b150b362-4578-4511-b973-ebafe2b9d90d">
<img width="1107" alt="image" src="https://github.com/nuxt/nuxt/assets/4695440/d4a52e25-0e82-4906-9e99-4b51b23c28b6">

**Comment by markthree** [comment]
@bobby169 
I see that you are using pnpm without including a `.npmrc` file.
You should add a `.npmrc` file to the root directory with the following content ↓

```env
shamefully-hoist=true
auto-install-peers=true
```

Finally, run `pnpm install` again.

**Comment by bobby169** [comment]
> @bobby169 I see that you are using pnpm without including a `.npmrc` file. You should add a `.npmrc` file to the root directory with the following content ↓
> 
> ```dotenv
> shamefully-hoist=true
> auto-install-peers=true
> ```
> 
> Finally, run `pnpm install` again.

Thank you very much, solved my problem

**Comment by avxkim** [comment]
@markthree i've added this to my `.npmrc` and re-run `pnpm install`, still getting this error related to a dayjs, what else it might be?

**Comment by markthree** [comment]
@avxkim Please provide the reproducible repository, I'm more than willing to help you take a look.

**Comment by avxkim** [comment]
[ui-kit.zip](https://github.com/nuxt/nuxt/files/14519574/ui-kit.zip)
uploaded my app without node_modules

**Comment by markthree** [comment]
@avxkim 

I found that ant-design-vue-nuxt would get stuck in the case of layer, so I eliminated the layer

[demo.zip](https://github.com/nuxt/nuxt/files/14520023/demo.zip)

**Comment by avxkim** [comment]
@markthree i've started from scratch on a clean nuxt installtiong (without layers) and found out that we also need:

```
  "devDependencies": {
    "@ant-design-vue/nuxt": "^1.4.1",
    "ant-design-vue": "^4.1.2"
  }
  ```
  
  in nuxt.config.ts
  
  ```
  // https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: ["@ant-design-vue/nuxt"],
  antd: {
    extractStyle: true,
  },
  css: ["ant-design-vue/dist/reset.css"],
  vite: {
    resolve: {
      alias: {
        "ant-design-vue/dist": "ant-design-vue/dist",
        "ant-design-vue/es": "ant-design-vue/es",
        "ant-design-vue/lib": "ant-design-vue/es",
        "ant-design-vue": "ant-design-vue/es",
      },
    },
  },
});
  ```

**Comment by markthree** [comment]
@avxkim 

Yes, I think it's a problem with [ant-design-vue-nuxt/issues](https://github.com/vueComponent/ant-design-vue-nuxt/issues)
