### ISSUE TITLE
`navigateTo` in script setup causes plugins two run again on server-side

### ISSUE THREAD

**Issue by fabkho** [nuxt/nuxt#26015]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.11.0
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.9.0
- Package Manager:  yarn@1.22.21
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-qr6d3x-kta8tn?file=README.md

### Describe the bug

I have a plugin with just a log:

```ts
export default defineNuxtPlugin((nuxtApp) => {
  console.log('test plugin')
})
```

And two pages. The first one is `index.vue`:
```ts
<script setup lang="ts">
console.log('Index page', 'server?', process.server)
await navigateTo('/welcome')
</script>

<template>test</template>
```

And the second one is `welcome.vue`:
```ts
<script setup lang="ts">
console.log('Welcome page', 'server?', process.server)
</script>

<template>welcome</template>
```

**Expected behaviour:**
The plugin is executed once on the server and once on the client.

**Actual behaviour:**
The plugin gets executed twice on the server. Initially and after the redirect from `/index` to `/welcome. And then only once on the client. 

### Additional context

If you start the dev server of my reproduction, you can see the logs below.

So, it is clear that after every server-side navigation the plugin is executed again.

### Logs
```
test plugin
Index page server? true
test plugin
Welcome page server? true
test plugin
Index page server? true
test plugin
Welcome page server? true
```

**Comment by danielroe** [comment]
The plugin should be executed twice.

* First server request, browser requests `/` and plugin executes, printing:
   > 'test plugin'
* Server sends `Location: /welcome` to browser and a 302 response.
* Browser makes second request to server for `/welcome` and plugin executes on server, printing:
   > 'test plugin'
* Now server responds to the second request with HTML and a 200 response.

This is expected, and correct behaviour.

You are also encountering a known issue in _development_ mode where the very first request to the Vite dev server results in two hits. A fix would be appreciated but it's quite a small issue.

**Comment by fabkho** [comment]
@danielroe thanks for this great explanation!
