### ISSUE TITLE
Image src fails in production build

### ISSUE THREAD

**Issue by nosizejosh** [nuxt/nuxt#26037]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.11.1
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.9.1
- Package Manager:  npm@10.4.0
- Builder:          -
- User Config:      debug, runtimeConfig, devtools, modules, ui, css, app, supabase
- Runtime Modules:  @nuxtjs/supabase@1.1.6, @vueuse/nuxt@10.9.0, @pinia/nuxt@0.5.1, @nuxt/ui@2.14.1, @pinia-plugin-persistedstate/nuxt@1.2.0, nuxt-icon@0.6.8
- Build Modules:    -
------------------------------

### Reproduction

Image src with images in public folder fails in production build (Digital Ocean). 

`<img  src="/img/bee.png" alt="" />`
even though this works in local and builds in local envn, it fails when i deploy to production using Digital Ocean. 
I'm I missing something?

I am not using nuxtImage because there was too many issues with it even on local.

### Describe the bug

Image src with images in public folder fails in production build (Digital Ocean). 

`<img  src="/img/bee.png" alt="" />`
even though this works in local and builds in local envn, it fails when i deploy to production using Digital Ocean. 
I'm I missing something?

I am not using nuxtImage because there was too many issues with it even on local.

**Comment by charlie-s** [comment]
Can you reproduce this or provide links? For someone to help identify, more context would be needed. This is working for me in production builds FWIW.

**Comment by nosizejosh** [comment]
Thank for responding. Other images work so it must be related to the image, windows and renaming. Closing this for now. Thanks

**Comment by nosizejosh** [comment]
confirmed, this was a windows renaming issue.
