### ISSUE TITLE
Nuxt Generate does not generate everything in 'content' folder

### ISSUE THREAD

**Issue by pnxl** [nuxt/nuxt#26033]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.11.1
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.9.0
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      devtools, ssr, css, modules, tailwindcss, app, content, generate
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @nuxt/content@2.12.0
- Build Modules:    -

### Reproduction

Reproduction repo available here: https://github.com/pnxl/notes-repro

Clone, install packages, and deploy on a static host (Vercel, CloudFlare, Netlify, etc.)
You will see that you can visit /digital-gardening (because there's a link to it in /index), but not /test (presumably because there are no router-links pointing to that page)

### Describe the bug

Doing `nuxt generate` only generates items in the `content` folder that has a link to it - without a link, the pages do not get generated. Notice how /digital-gardening is generated, but not /test. There's a link to /digital-gardening on index, but not to test.

Previously on Content v1 and Nuxt 2, I would use this to generate all routes:
```js
generate: {
    async routes() {
      const { $content } = require("@nuxt/content");
      const files = await $content({ deep: true }).only(["path"]).fetch();

      return files.map((file: { path: string }) =>
        file.path === "/index" ? "/" : file.path,
      );
    },
  },
```

But how could I do this with Nuxt 3 + Content v2? Help is appreciated.

**Comment by charlie-s** [comment]
When I attempt to `npm run generate` your repo, I do get the same output as you, but I see errors stemming from your nuxt config:

```
✔ Server built in 1313ms                                                                                                                     3:12:19 PM
ℹ Initializing prerenderer                                                                                                             nitro 3:12:19 PM
ℹ Prerendering 5 initial routes with crawler                                                                                           nitro 3:12:21 PM

[3:12:21 PM]  ERROR  Failed to parse URL from async%20routes()...
```

`generate.routes` is to be of type `string || string[]`, but you've passed an async function. The [docs](https://nuxt.com/docs/api/nuxt-config#generate) suggest using `nitro.prerender.routes` for dynamic routes.

I don't use @nuxt/content (yet) but a little digging suggests it doesn't generate a full static site. If you rip out your `generate` directive in `nuxt.config.ts` and add this:

```  
nitro: {
  prerender: {
    crawlLinks: true,
    routes: ['/']
  }
}
```

and then run generate, you'll see that your site is built and the `test.md` data actually exists inside `./output/public/api/_content/cache[hash].json`. When you visit that page, Vue will load it. Without a link, it doesn't appear to crawl it. [Here's a comment and thread](https://github.com/nuxt/nuxt/discussions/16153#discussioncomment-3904542) on the topic, but it's old and may be outdated. You could look into [Document Driven](https://content.nuxt.com/document-driven/introduction/) mode and see if it's what you need. 

I think your issue is really a support request for @nuxt/content (https://github.com/search?q=repo%3Anuxt%2Fcontent+ssg&type=issues). Or maybe try Discord.

**Comment by pnxl** [comment]
> but I see errors stemming from your nuxt config:

```✔ Server built in 1313ms                                                                                                                     3:12:19 PM
ℹ Initializing prerenderer                                                                                                             nitro 3:12:19 PM
ℹ Prerendering 5 initial routes with crawler                                                                                           nitro 3:12:21 PM

[3:12:21 PM]  ERROR  Failed to parse URL from async%20routes()...
```
> `generate.routes` is to be of type `string || string[]`, but you've passed an async function. The [docs](https://nuxt.com/docs/api/nuxt-config#generate) suggest using `nitro.prerender.routes` for dynamic routes.

Hi! Thanks for your response - yeah I added that out of despair because I didn't know what else to do lol - i forgot to remove that.

For the solution you've provided: I appreciate your help but deploying it on Cloudflare Pages doesn't seem to help and still shows a 404 page - even though it has already crawled it.

I'll look into creating a support ticket on content's repo and I'll take a look at documentDriven aswell. Thanks!

**Comment by danielroe** [comment]
You can use almost exactly the same code you used in `generate.routes` in `nitro.hooks['prerender:routes']`. It accepts an async function. But you won't have access to `$content` there.

However, in your app you can do something like this - just make sure you don't do it on every page:

```ts
if (import.meta.prerender) {
  // this will be tree-shaken out in production
  const routes = await getTheContentRoutes()
  prerenderRoutes(routes)
}
```

**Comment by pnxl** [comment]
> You can use almost exactly the same code you used in `generate.routes` in `nitro.hooks['prerender:routes']`. It accepts an async function. But you won't have access to `$content` there.
> 
> However, in your app you can do something like this - just make sure you don't do it on every page:
> 
> ```ts
> if (import.meta.prerender) {
>   // this will be tree-shaken out in production
>   const routes = await getTheContentRoutes() // you can use content composables within your app
>   prerenderRoutes(routes)
> }
> ```

Hi, thank you for your comment! I'm confused on how I could incorporate this onto my app - could you please elaborate? Thanks!

**Comment by riddla** [comment]
You could use the following in your layout (`app.vue` or `layouts/default.vue`):

```typescript
if (import.meta.prerender && useRoute().path === '/') {
  // this will be tree-shaken out in production
  const routes = await getTheContentRoutes() // you can use content composables within your app
  prerenderRoutes(routes)
}
```

This way the code should only be invoked once and only during SSR/prerender.
