### ISSUE TITLE
When createError is thrown in server middleware, custom error.vue is not used

### ISSUE THREAD

**Issue by charlie-s** [nuxt/nuxt#26035]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.9.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-q4aqpy-zxpnvh?file=server%2Fmiddleware%2Fauth.ts,server%2Fapi%2FcurrentUser.ts,app.vue,error.vue

See `server/middleware/auth.ts` and `server/api/currentUser.ts`. Toggle which of these throws an error to see this behavior.

### Describe the bug

When I `throw createError(...)` in a server or client route, my `./error.vue` renders as expected. When I throw the same error in a server middleware, `@nuxt/ui-templates/templates/error-dev.mjs` (or `error-500.mjs` in production) is rendered.

### Additional context

I would expect my `error.vue` to be used in all of these instances. Is this the expected behavior? For what it's worth, adding `fatal: true` to the error object, or using `showError`, does not impact this.

**Comment by danielroe** [comment]
The reason this is true _in your reproduction_ is that Nuxt makes a fresh (internal) request to render the error page, and your middleware is throwing the error there as well, so we fall back to a 'safe' error.

Make sure you check whether Nuxt is rendering an error before throwing _another_ error.

**Comment by charlie-s** [comment]
Interesting! Thanks for checking out the repro and providing insight. 

I'm trying to find the corresponding code in Nuxt to follow this flow. Specifically, I did not expect server middleware to run to display the error since there are no server-side fetch's etc happening in my error.vue. I _would_ expect client middleware to run. Can you point me in the direction to look at this flow more closely? Is it nuxt/packages/nuxt/src/app/plugins/router.ts?
