### ISSUE TITLE
useAsyncData is running twice refetching data (server and client)

### ISSUE THREAD

**Issue by jeffreytung7** [nuxt/nuxt#26049]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.10.3`
- CLI Version:      `3.10.1`
- Nitro Version:    `-`
- Package Manager:  `pnpm@8.3.1`
- Builder:          `-`
- User Config:      `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Reproduction: https://github.com/jeffreytung7/test-1

### Describe the bug

useAsyncData is refetching data on the client side even after it ran on SSR.

Steps to reproduce:

1. `pnpm dlx nuxi@latest init <project-name>`
2. in app.vue replace `<NuxtWelcome />` with `<NuxtPage />`
3. create a file `pages/index.vue`
4. create a useAsyncData call:

```
const { data, error } = await useAsyncData('test', async () => {
    if (process.server) {
        console.log('Server: hi');
    } else if (process.client) {
        console.log('Client: hi');
    }
    const response = await $fetch('/api/test')
});
```

5. create a file `server/api/test.get.ts` with this code:

```
export default defineEventHandler(async event => {
    console.log('test.get.ts hit')
});
```

6. `npm run dev` and each time you refresh the page, the console log in terminal will show 

```
Server: hi
test.get.ts hit
test.get.ts hit
```

I've tested this on my main project with a api endpoint that adds a row to the database, and it is adding two rows every refresh. 

I think the problem is that useAsyncData is running the full function both on server and client. It should not be re-fetching the data on client.

**Comment by manniL** [comment]
Every nullish value returned from useAsyncData will be treated as "no response", leading to another fetch on the client-side.
