### ISSUE TITLE
validate method doesn't allow customising status code

### ISSUE THREAD

**Issue by Mingcomity** [nuxt/nuxt#26046]
### Environment

PS E:\develop\Vue\Nuxt\07-middleware-nuxt> pnpm i nuxt@latest
Packages: +263 -134
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-------------------------------------------------
Progress: resolved 767, reused 678, downloaded 0, added 5, done
node_modules/.pnpm/esbuild@0.20.1/node_modules/esbuild: Running postinstall script, done in 698ms
node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild: Running postinstall script, done in 940ms

dependencies:
- nuxt 3.0.0
+ nuxt 3.10.3

Done in 16.6s
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                                              23:26:38  

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

PS E:\develop\Vue\Nuxt\07-middleware-nuxt>

### Reproduction

[github-dxzyyv.zip](https://github.com/nuxt/nuxt/files/14469895/github-dxzyyv.zip)

### Describe the bug

![image](https://github.com/nuxt/nuxt/assets/107565965/caff9d6e-60cc-45ec-b3ae-827de8a71bd8)
按照文档描述，如果我按照以下代码编写：
```
definePageMeta({
    validate:(route) =>{
    return {
        statusCode: 401, 
        statusMessage:'route validate false' 
    }
    }
})
```
则应该是跳转到为401的error页面，但是实际跳转到404的error页面，同时在此基础上刷新，则放回500的error页面
同时我在Nuxt3.0.0版本中测试没有这样的错误

**Comment by Mingcomity** [comment]
**Environment**

PS E:\develop\Vue\Nuxt\07-middleware-nuxt> npx nuxi info
Working directory: E:/develop/Vue/Nuxt/07-middleware-nuxt                                                                                23:43:57
Nuxt project info:                                                                                                                       23:43:57

------------------------------
- Operating System: Windows_NT
- Node Version:     v21.6.2
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.9.1
- Package Manager:  pnpm@8.9.2
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                                              23:43:57  

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

**Comment by harveyLXH** [comment]
I have the same problem

**Comment by danielroe** [comment]
Would you be able to provide a runnable reproduction on StackBlitz or GitHub rather than a zip file? 🙏

**Comment by harveyLXH** [comment]
> Would you be able to provide a runnable reproduction on StackBlitz or GitHub rather than a zip file? 🙏



> Would you be able to provide a runnable reproduction on StackBlitz or GitHub rather than a zip file? 🙏

https://stackblitz.com/edit/nuxt-starter-zh4seg?file=pages%2Fprofile.vue

**Comment by Mingcomity** [comment]
> 您能否在 StackBlitz 或 GitHub 上提供可运行的复制品而不是 zip 文件？🙏

https://stackblitz.com/edit/github-f8uzqk?file=pages%2Fprofle%2F%5Bid%5D.vue
