### ISSUE TITLE
Dependencies in Nuxt Layer

### ISSUE THREAD

**Issue by v0id-4lpz** [nuxt/nuxt#26054]
Hi guys,

My Nuxt layer can't use it's internal node modules and i can't find why.

Ex:
```
/projects
|-- /my-layer    <= nuxt layer
|-- /my-project  <= nuxt project
```

In my layer i have dependencies `npm install @sidebse/nuxt-auth` and NOT in `my-project`.

```ts
# /my-layer/nuxt.config.ts

modules: [
  '@sidebase/nuxt-auth',
],
```

```ts
# /my-project/nuxt.config.ts

extends: [
  '../my-layer',
],
```

When i `npm run dev`

```
[11:07:32]  ERROR  Error while requiring module @sidebase/nuxt-auth: Error: Cannot find module 'D:/Projects/my-project/@sidebase/nuxt-auth'
Require stack:
- D:\Projects\my-project\index.js
```

It looks for the dep in `my-project` instead of `my-layer`...

When i install the dep in `my-project`, it works fine...
But I want my dep only in my layer.

I can't find why or any workaround about that.
Maybe someone can help ?

Thanks!

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/23445.
