### ISSUE TITLE
CSS is inlined and added as a blocking resource after production build

### ISSUE THREAD

**Issue by mikeCrafted** [nuxt/nuxt#26056]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v21.6.1`
- Nuxt Version:     `0.0.0`
- Nitro Version:    `-`
- Package Manager:  `npm@9.6.4`
- Builder:          `webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-9d4aie?file=pages%2Findex.vue

### Describe the bug

When building for production and inspecting page source, I get most of the CSS inlined with <style> tags properly, but not all of it.

I always end up having some components producing a <link> CSS like this one: `<link rel="stylesheet" href="[/_nuxt/homepage.vy-tb-hO.css](http://localhost:3000/_nuxt/homepage.vy-tb-hO.css)">` which is a blocking resource and lighthouse complains about it. 

You can run a lighthouse report and see "Avoid render-blocking resources" - this is a huge pain in my main production app costing us almost 2.5 seconds.

Why is this happening? I saw the docs stating that all CSS is automatically inlined :)
Thank you so much for any help!

### Additional context

You can see the issue here very clearly: view-source:https://www.locaverse.at/essen-bestellen
All component's CSS is style="scoped"

**Comment by htmlfactorycz** [comment]
same issue here. Looks like <link rel="stylesheet" /> created on components wich are reused multiple ones. But if you look closed you will see, that the component css is inlined + stylesheet created, so its duplicated..

In Nuxt2 there was a configuration to have all styles inlined or all styles extracted. There should be same config in nuxt 3..

**Comment by mikeCrafted** [comment]
Another idea / observation: we started seeing errors in our sentry tracking that go like `Error createError(nuxt/dist/app/composables/error) Unable to preload CSS for https://www.locaverse.at/_nuxt/index.CgwrX-82.css`
This also causes the app to crash in production (not in development!)
Could this be a Vite issue, @danielroe?
I tried to switch to webpack, but after installing `@nuxt/webpack-builder` and setting `builder: 'webpack'` in my config, I got the error `[unhandledRejection] Identifier '__executeAsync' has already been declared (4:25)` which is caused by `node_modules\acorn\dist\acorn.js:651:37 `

**Comment by danielroe** [comment]
The reason this is happening in the original reproduction is that layouts _can_ be used anywhere, so we still need to emit a separate CSS file for them (ie. we can't just inline it on the server).

When this is the case, we can't omit any CSS from the file. (On the other hand, we do 'prune' CSS that is _definitely_ inlined in the entrypoint.)

We also do need to add it as a dependency of the initial request as there are situations where there is client-side CSS we don't know about, such as if your layout imported a client-only component.

I'm not ruling out improvements here - I would love that! - but let's track in https://github.com/nuxt/nuxt/issues/21821.

**Comment by mikeCrafted** [comment]
@danielroe thank you very much for the answer! So, if I understand correctly, the I am doing everything right by using scoped CSS in layouts and components and the issue is not in the code but in Vite/internal implementation of CSS styles inlining?
Is there anything I can do to prevent that as a workaround until this is fixed (it seems to be a major change/improvement as I saw in the mentioned issue #21821
