### ISSUE TITLE
Add ability to disable the `NuxtLoadingIndicator` on some API calls

### ISSUE THREAD

**Issue by genu** [nuxt/nuxt#26050]
### Describe the feature

I'd like to be able to disable the global loading indicator for some API calls in cases where I build components that have their own loading indicator. Having a global one is redundant in such a case.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by huang-julien** [comment]
You can disable the loading indicator by "hiding" it, using `finish` from the loading indicator composable or using `loading:...` hooks.

Do you have a more precise use case so we can see what API could be implemented ?

**Comment by genu** [comment]
I haven't tried it my self yet, but I would imagine that if I do something like this, it wouldn't actually work because it would technically cause the indicator to finish, but it would just startup again during the await?

```ts
const indicator = useLoadingIndicator();

const doSomething = async () => {
   indicator.finish()
   const data =  await $fetch(`...`);
}
...
```

Unless you had something else in mind?

**Comment by adrienZ** [comment]
This may work you: 

Include the [NuxtLoadingIndicator](https://nuxt.com/docs/api/components/nuxt-loading-indicator#usage) in your layout and/or your app.vue file. 

create a global state to store whether or not showing the indicator with [useState](https://nuxt.com/docs/api/composables/use-state)

```ts
const showIndicator = useState('nuxtIndicator', () => true)
```

in your layout 
```vue
<template>
  <main>
    <NuxtLoadingIndicator v-if="showIndicator" />
    <slot />
  </main>
</template>
```

and then

```ts
const doSomething = async () => {
   showIndicator.value = false;
}
```

**Comment by CernyMatej** [comment]
Agreed, I don't think there needs to be another way to do this. It's already possible.

**Comment by genu** [comment]
I'm fine with the workaround. I'll close this.
