### ISSUE TITLE
Error sharing a pnpm workspace package using nuxt layer

### ISSUE THREAD

**Issue by yugal-compro** [nuxt/nuxt#26065]
### Discussed in https://github.com/nuxt/nuxt/discussions/26008

<div type='discussions-op-text'>

<sup>Originally posted by **yugal-compro** February 29, 2024</sup>
I have a pnpm monorepo in which I have
- a base layer
- an app app1 extending base
- base layer using 2 packages - 
    - supervillains 
    - good(local pnpm workspace package)

**Issue:** I am able to use supervillains in app1 but not local package (pnpm workspace)

Able to see my package - good in node modules of base
![image](https://github.com/nuxt/nuxt/assets/107843548/0e3c9db7-147a-4cdf-ac60-4906d43b4220)

In app1-
![image](https://github.com/nuxt/nuxt/assets/107843548/b28a878f-5971-4fb2-88e5-53f98801cc62)

Github repo link - https://github.com/yugal-compro/nuxt-monorepo

  </div>

**Comment by markthree** [comment]
@yugal-compro 

I don’t think this is a bug; you should explicitly list the use of "good" in `apps/app1/package.json`, like this ↓

```json
{
  "dependencies": {
    "base": "workspace:*",
    "good": "workspace:*"
  }
}
```
Because `good` is a dependency of `base`, not of `apps/app1`, this is not allowed in a pnpm workspace.

**Comment by yugal-compro** [comment]
@markthree 

Layers provide this feature, That's why I am able to use `supervillains` - dependency of `base` inside `apps/app1`

**Comment by adamdehaven** [comment]
When you import the local package via the package name, you have to build the local package before you can utilize it in the parent app.

**Comment by yugal-compro** [comment]
@adamdehaven there is no problem when I install and use package in `app1` , problem arise when I install local package in `base` but use it in `app1`
