### ISSUE TITLE
Transform function in data fetching can't use a filter declared in "global" scope

### ISSUE THREAD

**Issue by TheDutchCoder** [nuxt/nuxt#26070]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.9.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-5sktf3?file=app.vue,server%2Fapi%2Ftags.ts

### Describe the bug

When using a filter to transform the data in a useFetch call, you can only apply inline logic, not a filter function. Is this some kind of scope issue?

**Comment by TheDutchCoder** [comment]
To clarify, it only works if you move the filter function declaration into the transform scope:

```js
transform: (data) => {
  const filterTags = (tag) => tag.slug === 'en'
  return data.tags.filter(filterTagss)
}
```

**Comment by warflash** [comment]
To me this looks like regular js hoisting, unrelated to nuxt.
You either need to define the `filterTags` variable before you call the useFetch function or if you want to place it anywhere in the scope then use regular functions. -> https://stackblitz.com/edit/github-5sktf3-zyrz9j?file=app.vue

**Comment by TheDutchCoder** [comment]
Hmm, this is a fair point 😓
