### ISSUE TITLE
Error on default installation template

### ISSUE THREAD

**Issue by Vicnovais** [nuxt/nuxt#26074]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.14.2
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.9.1
- Package Manager:  npm@8.1.4
- Builder:          -
- User Config:      devtools, typescript
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Just start a new project as the installation guide says:
`npx nuxi@latest init <project-name>`

### Describe the bug

After creating a fresh project, VSCode shows many errors on app.vue file, as follows
![image](https://github.com/nuxt/nuxt/assets/7889190/1a829eeb-343e-4541-af37-45e5e25c59dc)

### Additional context

I have installed the [Vue - Official extension](https://marketplace.visualstudio.com/items?itemName=Vue.volar)
- Typescript version: 5.3.2
- VSCode version: 1.86.0

**Comment by Vicnovais** [comment]
Just found out the problem: apparently there is some conflict when using the [vscode-styled-components](https://marketplace.visualstudio.com/items?itemName=styled-components.vscode-styled-components) extension. Disabling it worked for me.

**Comment by danielroe** [comment]
This might possibly be caused by the latest version of https://marketplace.visualstudio.com/items?itemName=Vue.volar.
