### ISSUE TITLE
Incorrect types in `getCachedData` when passing a `Data` type to `useFetch`

### ISSUE THREAD

**Issue by MuhammadM1998** [nuxt/nuxt#26093]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.9.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-gfzzpe?file=pages%2Findex.vue

### Describe the bug

1. Open the reproduction link
2. Run `npm run typecheck`. 
3. It will complete successfully and caching works (navigate between index & about to see it)
4. In **index.vue**, add the type `TestDataT` to useFetch and repeat step 3, everything work as expected
5. Comment the first line inside `getCachedData` function and uncomment the `return undefined` and repeat step 3, gives a type error.

### Additional context

`getCachedData` accepts `undefined` or a function that returns a data if found or `undefined` or `null` to trigger a refetch [as stated in the docs](https://nuxt.com/docs/api/composables/use-fetch#params).

> getCachedData: Provide a function which returns cached data. A null or undefined return value will trigger a fetch

When not passing a response type to `useFetch`, things work correctly and `getCachedData` gets typed as `(key: string) => unknown | undefined`
```vue
<script setup lang="ts">
  const { data } = await useFetch('/todos/1', {
    getCachedData: (key) => {
      // ^ (key: string) => unknown | undefined

      // Both works without type errors 
      return nuxtApp.payload.data[key] || nuxtApp.static.data[key] 
      return undefined 
    },
 })
</script>

<template>
  <div> {{ data }} </div>
</template>
```

When passing aresponse type to `useFetch`. `getCachedData` gets typed as (key: string) => DataT and gives a type error if I attempt to return undefined

```vue
<script setup lang="ts">
  type TestDataT = { foo: 'bar' }

  const { data } = await useFetch<TestDataT>('/todos/1', {
    getCachedData: (key) => {
      // ^ (key: string) => TestDataT

      // This works 
      return nuxtApp.payload.data[key] || nuxtApp.static.data[key] 

      // This gives type error
      return undefined 
    },
 })
</script>

<template>
  <div> {{ data }} </div>
</template>
```

**Comment by danielroe** [comment]
I think we can track in https://github.com/nuxt/nuxt/issues/25903.
