### ISSUE TITLE
Route object created with useRoute and accessed via $route in template has no reactivity.

### ISSUE THREAD

**Issue by fedikan** [nuxt/nuxt#26092]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.17.0
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.9.1
- Package Manager:  npm@9.6.7
- Builder:          -
- User Config:      devtools, plugins, css, components, modules, nitro, colorMode, vite, runtimeConfig, app
- Runtime Modules:  @element-plus/nuxt@1.0.7, @nuxtjs/color-mode@3.3.2, @nuxt/image@1.4.0
- Build Modules:    -
------------------------------

### Reproduction

package.json: 
{
  "dependencies": {
    "@ant-design/icons-vue": "^6.1.0",
    "@element-plus/icons-vue": "^2.1.0",
    "@floating-ui/dom": "^1.4.5",
    "@phosphor-icons/vue": "^2.0.1",
    "@types/js-cookie": "^3.0.3",
    "axios": "^1.5.1",
    "dompurify": "^3.0.5",
    "highlight.js": "^11.7.0",
    "jwt-decode": "^3.1.2",
    "marked": "^5.1.2",
    "marked-mangle": "^1.1.4",
    "mitt": "^3.0.1",
    "mixpanel-browser": "^2.47.0",
    "nuxt-gtag": "^1.1.1",
    "sass": "^1.58.0",
    "socket.io-client": "4.6.2",
    "three": "^0.161.0",
    "tslib": "^2.5.0",
    "vue": "^3.4.19",
    "vue-router": "^4.1.6",
    "vue-virtual-scroller": "^2.0.0-beta.8",
    "vue3-lottie": "^2.7.0",
    "vue3-toastify": "^0.1.5",
    "vuex": "^4.1.0",
    "wavesurfer.js": "^7.4.5",
    "yup": "^1.3.2"
  },
  "devDependencies": {
    "@element-plus/nuxt": "^1.0.5",
    "@nuxt/devtools": "latest",
    "@nuxt/image": "^1.1.0",
    "@nuxtjs/color-mode": "^3.3.0",
    "@rushstack/eslint-patch": "^1.1.4",
    "@types/cookie": "^0.5.1",
    "@types/mixpanel-browser": "^2.47.4",
    "@types/node": "^20.2.5",
    "@typescript-eslint/eslint-plugin": "^5.56.0",
    "@typescript-eslint/parser": "^5.56.0",
    "@vitejs/plugin-vue": "^4.0.0",
    "@vue/eslint-config-prettier": "^7.0.0",
    "@vue/eslint-config-typescript": "^11.0.2",
    "autoprefixer": "^10.4.13",
    "element-plus": "^2.3.8",
    "eslint": "^8.36.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-config-standard-with-typescript": "^34.0.1",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-n": "^15.6.1",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-promise": "^6.1.1",
    "eslint-plugin-vue": "^9.10.0",
    "nuxt": "^3.10.3",
    "prettier": "^2.7.1",
    "typescript": "^5.0.2",
    "unplugin-auto-import": "^0.15.2",
    "unplugin-vue-components": "^0.24.1",
    "vite": "^4.3.9",
    "vite-svg-loader": "^4.0.0",
    "vue-eslint-parser": "^9.1.0"
  }
}

### Describe the bug

Route object created with useRoute and accessed via $route in template has no reactivity.
I have updated from 3.6.5 to 3.10.3 and now huge part of a project which is based on route object is totally not working.
 I can access route object only by using
 `
 const router = useRouter();
 const route = computed(()=> router.currentRoute.value);
 `
 Also sometimes i face an error saying: ERROR  [unhandledRejection] write EPIPE, not sure if these problems are related, but anyways. 
 Will appreciate any help.

 

### Logs

```shell-script
ERROR  [unhandledRejection] write EPIPE                                                                                                                                                                  23:04:48

  at afterWriteDispatched (node:internal/stream_base_commons:160:15)
  at writeGeneric (node:internal/stream_base_commons:151:3)
  at Socket._writeGeneric (node:net:931:11)
  at Socket._write (node:net:943:8)
  at writeOrBuffer (node:internal/streams/writable:392:12)
  at _write (node:internal/streams/writable:333:10)
  at Writable.write (node:internal/streams/writable:337:10)
  at Socket.ondata (node:internal/streams/readable:766:22)
  at Socket.emit (node:events:514:28)
  at addChunk (node:internal/streams/readable:324:12)
```

**Comment by fedikan** [comment]
I have a conditional header, so it renders different header for different page, and it's component is mounting inside layout. But when i go to the page that should show SharedHeader, and then go to the page that should show MainHeader, i still see SharedHeader, as route object is not being changed. 

```
<template>
  <div
    id="header"
    :class="{
      default: isDefaultHeader,
      empty: !isDefaultHeader,
    }"
  >
    <SharedHeader v-if="isSharedHeader" />

    <MainHeader v-else-if="activeGroupId || activeChatId" />
    <FeedHeader v-else-if="isFeedHeader" />
    <EmptyHeader v-else />
  </div>
</template>

<script setup lang="ts">
import { useStore } from 'vuex';
const store = useStore();
const route = useRoute();
const isFeedHeader = computed(
  () => store.getters['display/isFeedHeaderVisible'] && route.name === 'index'
);
const isDefaultHeader = computed(
  () =>
    isFeedHeader.value ||
    activeGroupId.value ||
    activeChatId.value ||
    route.fullPath.match('context-block')
);
const activeGroupId = computed(() => store.getters['group/activeGroup']?._id);
const activeChatId = computed(() => store.getters['chat/chat']?._id);
const isSharedHeader = computed(() => route.fullPath.match('context-block'));
</script>
```

**Comment by fedikan** [comment]
Any chance to get help?

**Comment by madebyfabian** [comment]
@fedikan Could you please provide an actual minimal reproduction so this can be debugged? Thanks! 👍
