### ISSUE TITLE
`useRequestURL()` doesn't provide the correct hostname in when `swr` is enabled (route rules)

### ISSUE THREAD

**Issue by bpolaszek** [nuxt/nuxt#26102]
### Environment

- Operating System: `Darwin`
- Node Version:     `v21.6.2`
- Nuxt Version:     `3.10.3`
- CLI Version:      `3.10.1`
- Nitro Version:    `2.9.1`
- Package Manager:  `yarn@1.22.21`
- Builder:          `-`
- User Config:      `ssr`, `pages`, `devtools`, `runtimeConfig`, `routeRules`, `sourcemap`, `modules`, `vite`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.11.4`, `nuxt-icon@0.6.8`, `nuxt-schema-org@3.3.4`, `@pinia/nuxt@0.5.1`
- Build Modules:    `-`

### Reproduction

```
# /etc/hosts
127.0.0.1    example.local
```

```vue
// app.vue
<template>
  {{ hostname }}
</template>

<script setup>
const {hostname} = useRequestURL()
</script>
```

```console
yarn dev --host 127.0.0.1
```

If you visit `http://example.local:3000`, `example.local` will be displayed (from SSR).

### Describe the bug

Now, add an [`swr` directive](https://nuxt.com/docs/guide/concepts/rendering#hybrid-rendering) to add cache headers: 
```ts
// nuxt.config.ts
export default defineNuxtConfig({
  // ...
  routeRules: {
    '/**': {
      swr: 3600,
    },
  },
})
```

Then do it again:
```console
yarn dev --host 127.0.0.1
```

If you visit `http://example.local:3000`, `localhost` will be displayed instead of `example.local` (from SSR).

**Comment by danielroe** [comment]
Would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏

**Comment by pi0** [comment]
Hi, dear @bpolaszek. Yes, and it is an expected limitation you are facing.

When you opt-in to a caching mechanism, we have to make sure the "same" cache response is served to every request hitting this URL. And therefore it should not "vary" based on incoming headers.

By default Nitro removes all incoming headers as a safety measure to avoid cache leaks. 

You can add varies support for `header` host (but consider `useRequestURL` depends on **more headers** including `x-forwarded-*` ones for full support)

```js
export default defineNuxtConfig({
  routeRules: {
    "/**": {
      cache: { swr: true, varies: ["host"] },
    },
  },
});
```

---

We also plan to support new `useCanonicalURL()` utility + explicit configuration to set canonical URL. You can followup on it from https://github.com/unjs/nitro/issues/2052

**Comment by bpolaszek** [comment]
Hi @pi0, thank you for your quick and efficient answer !

Your solution works, thanks a lot ! 😃
