### ISSUE TITLE
Double fetching when using dynamic components with resolveComponent and Suspense

### ISSUE THREAD

**Issue by dakt** [nuxt/nuxt#26101]
### Environment

- Operating System: Darwin
- Node Version:     v19.9.0
- Nuxt Version:     3.9.3
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.12.0
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-veyfpd?file=pages%2Findex.vue

### Describe the bug

Not sure if this is a bug or expected behaviour.

If we wrap dynamic component with `Suspense` and that dynamic component is global and resolved using `resolveComponent` and a variable as parameter, for example:
```javascript
const foo = 'foo';
const component = resolveComponent(foo);
```

```html
<Suspense>
  <component :is="component" />
</Suspense>
```
then data fetching within that component gets repeated on the client after page load even though component is already server rendered.

If we remove `Suspense` or use string literal in `resolveComponent` everything works fine.

**Comment by danielroe** [comment]
This is caused by https://github.com/vuejs/core/issues/6638. Let's track within https://github.com/nuxt/nuxt/issues/18405.
