### ISSUE TITLE
[nuxt] error caught during app initialization TypeError: document$1.getElementsByTagName is not a function

### ISSUE THREAD

**Issue by rmeira** [nuxt/nuxt#26110]
### Environment

Guys, how are you?

I just updated NUXT with some new dependencies and now it is no longer running STATIC.

Can anyone help me?

my `package.json`

```
{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "version": "1.0.0",
  "scripts": {
    "build": "nuxt build",
    "dev": "cp .env.dev .env && nuxt dev",
    "generate": "nuxt generate",
    "build-qa": "cp .env.qa .env && nuxt generate",
    "build-prod": "cp .env.prod .env && nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare",
    "test": "vitest --run",
    "test:watch": "vitest",
    "test:ui": "vitest --ui --coverage.enabled=true",
    "test:cov": "vitest run --coverage",
    "lint": "prettier . --check",
    "lint:fix": "prettier . --write",
    "prepare": "husky"
  },
  "dependencies": {
    "@mdi/font": "^7.4.47",
    "codemirror": ">=5.64.0 <6",
    "codemirror-editor-vue3": "^2.4.1",
    "keycloak-js": "^24.0.1",
    "nuxt": "^3.10.3",
    "vue": "^3.4.19",
    "vue-router": "^4.3.0",
    "vue3-lottie": "^3.2.0",
    "vue3-toastify": "^0.2.1"
  },
  "devDependencies": {
    "@nuxt/test-utils": "^3.11.0",
    "@pinia/nuxt": "^0.5.1",
    "@vitest/coverage-v8": "^1.3.1",
    "@vitest/ui": "^1.3.1",
    "@vue/test-utils": "^2.4.4",
    "husky": "^9.0.11",
    "jsdom": "^24.0.0",
    "playwright-core": "^1.42.1",
    "prettier": "^3.2.5",
    "vite-plugin-vuetify": "^2.0.2",
    "vitest": "^1.3.1",
    "vuetify": "^3.5.7"
  }
}
```

after i run `yarn generate` and run `npx serve .output/public` the error below started to appear in the browser:
```[nuxt] error caught during app initialization TypeError: document$1.getElementsByTagName is not a function```
<img width="542" alt="image" src="https://github.com/nuxt/nuxt/assets/8323576/3840bfcf-c9f6-40ba-9a20-3b8ecee03bf3">

### Reproduction

@manniL, see reproduction -> [vueify+nuxt](https://codesandbox.io/p/devbox/nuxt-vuetify-spa-mlkjgh?embed=1&showConsole=true&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clth3l8g800083b6hdsrzx37h%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clth3l8g800023b6h6yc2ykf8%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clth3l8g800053b6ha0tgp9x4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clth3l8g800073b6hb7qfff8y%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clth3l8g800023b6h6yc2ykf8%2522%253A%257B%2522id%2522%253A%2522clth3l8g800023b6h6yc2ykf8%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clth3l8g800073b6hb7qfff8y%2522%253A%257B%2522id%2522%253A%2522clth3l8g800073b6hb7qfff8y%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clth3n0zt00393b6h9luyd1hf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clth3n0zt00393b6h9luyd1hf%2522%257D%252C%2522clth3l8g800053b6ha0tgp9x4%2522%253A%257B%2522id%2522%253A%2522clth3l8g800053b6ha0tgp9x4%2522%252C%2522activeTabId%2522%253A%2522clth41zv400kf3b6hd0hld0j5%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clth41zv400kf3b6hd0hld0j5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clth421qc001odhei0n6re9jt%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

![image](https://github.com/nuxt/nuxt/assets/8323576/adec2d2d-d28b-47f6-a432-3f8cd19e51aa)

### Describe the bug

```[nuxt] error caught during app initialization TypeError: document$1.getElementsByTagName is not a function```

**Comment by rmeira** [comment]
I found a way to solve it by going back to version: 3.8.2.

Has anyone had this problem in the current version and resolve it?

**Comment by manniL** [comment]
@rmeira Your whole project does **not** qualify as a reproduction. Please make sure the repro is as minimal as possible.

**Comment by rmeira** [comment]
Hi guys, morning!

I found the issue! The problem was in the following function located in the `utils/formatters.ts` file of my application. For some reason, the `$` symbols were breaking when compiling the code to JavaScript.

```
export const document = (document: string): string => {
  if (document.length < 14) {
    return document.replace(/(\d{3})(\d{3})(\d{3})(\d{2})/, `$1.$2.$3-$4`) || '';
  }
  return document.replace(/^(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})/, '$1.$2.$3/$4-$5') || '';
};
```
