### ISSUE TITLE
interface AppConfig does not take types when using `extends`

### ISSUE THREAD

**Issue by olivervorasai** [nuxt/nuxt#26116]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.10.0
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.9.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-zges3w?file=types%2Fapp.config.d.ts,app.vue,types%2Fvariables.d.ts

### Describe the bug

When referencing `theme` from `useAppConfig`, typescript should **always** allow both the `primary` and `secondary` type as possible values.

This should be possible by overriding the App Config Output as described here: https://nuxt.com/docs/guide/directory-structure/app-config#app-config-output.

However, that does not work when using `extends` and only works when the `AppConfig` interface has the overriding types explicitly written out.

Stackblitz doesn't visibly show the error, but VS Code with the volar extensions does:
![image](https://github.com/nuxt/nuxt/assets/6283219/7a5ce57b-cae7-4b4b-b2f0-075dc3f04feb)

### Additional context

I use this pattern in a monorepo where there is a `base` layer with components that take in the config set by child sites.

This **does** work if `export {};` is **not** declared after `declare module '@nuxt/schema'`. However this will break types in `nuxt.config.ts`

**Comment by mrleblanc101** [comment]
Thanks, changing `nuxt/schema` to `@nuxt/schema` solve the issue on my end.

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/23207.
