### ISSUE TITLE
Docs For Chinese: there is no response when clicking search on any page

### ISSUE THREAD

**Issue by Hub-yang** [nuxt/nuxt#26123]
### Environment

- OS: macOS Somoma 14.4
- Chrome: 122.0.6261.111 (arm64)
- Safari: 17.4 (19618.1.13.11.5)

### Reproduction

https://github.com/nuxt/nuxt/assets/78254474/8ab103af-c188-45b4-82ed-cc280f465b1a

### Describe the bug

- For Chrome, there is no response when clicking search on any page, causing the page to crash after a period of time.
- For Safari, the browser freezes immediately after clicking.

**Comment by danielroe** [comment]
Thank you for reporting. However, this  is not a site that we created or have control over.
