### ISSUE TITLE
首屏渲染报错（刷新浏览器首屏渲染报错） First screen rendering error (refresh browser first screen rendering error)

### ISSUE THREAD

**Issue by 1877666** [nuxt/nuxt#26129]
### Environment

nuxt 3.10.3

### Reproduction

 .

### Describe the bug

当浏览器首次进入页面或者在当前页面刷新浏览器时，报错了无法渲染导致项目出现致命，无法继续操作，如果是从别的页面跳转过来的却不会报错或者使用 '<ClientOnly />' 也能解决问题，但是是因为什么原因导致首屏或者是刷新浏览器的时候报错呢，如果使用ClientOnly  服务端渲染就会失效，或者说从别的页面跳转过来也不会报错是因为，首屏渲染才是使用服务端渲染，后续都是客户端渲染

When the browser enters the page for the first time or refreshes the browser on the current page, an error is reported and rendering is not possible, causing the project to become fatal and unable to continue operation. If it is redirected from another page without an error or using '<ClientOnly/>' can also solve the problem. However, what causes the error to appear on the first screen or when refreshing the browser? If using the ClientOnly server for rendering, it will fail, Or to put it another way, jumping over from another page won't cause an error because the first screen rendering is done using server-side rendering, and subsequent rendering is done using client-side rendering

![image](https://github.com/nuxt/nuxt/assets/76433247/ce79199d-6606-4b39-aa4d-a4b09546c6e5)

**Comment by xjccc** [comment]
If you delete the `split` where you use, the error also occur?

**Comment by tanglongyan** [comment]
你的最后一句话其实是说对了的，刷新浏览器或者首次进入页面如果你只是用的$fetch会是在服务器端跟浏览器端发送请求的，大概率你这错是服务器端没拿到数据导致的，请求发送姿势问题

**Comment by madebyfabian** [comment]
@1877666 Can you please provide a minimal reproduction? Otherwise, you could also try to seek help on discord (https://discord.com/invite/nuxt) as this does not look like an error with Nuxt, and more an error with data not being loaded.
