### ISSUE TITLE
Make `transform` in `AsyncDataOptions ` and `UseFetchOptions` less restrictive

### ISSUE THREAD

**Issue by ennioVisco** [nuxt/nuxt#26138]
### Describe the feature

The request is pretty simple; the current type is:

```ts
type AsyncDataOptions<DataT> = {
  server?: boolean
  lazy?: boolean
  immediate?: boolean
  deep?: boolean
  dedupe?: 'cancel' | 'defer'
  default?: () => DataT | Ref<DataT> | null
  transform?: (input: DataT) => DataT
  pick?: string[]
  watch?: WatchSource[]
  getCachedData?: (key: string) => DataT
}
```
I think it makes sense to change it to:
```ts
type AsyncDataOptions<DataT, TransformT=DataT> = {
  // ... 
  transform?: (input: TransformT) => DataT | Promise<DataT>
  // ...
}
```
The use cases I have in mind for that are multiple:
1. It could be the transformation requires some async operation (e.g., determine the response based on some DB type)
2. It could be the transformation changes the type of the response (e.g., I receive a Blob, but I want to return a string)
3. Both of the above

### Further Notes
- Since the `data` field of the response is asynchronous anyway, I don't see why the current restriction to synchronous transformations is needed/helpful
- Similarly, the request to provide the same type for the transformation's return type appears nonsensical and unneeded.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by ennioVisco** [comment]
@danielroe sweet ❤️

**Comment by ennioVisco** [comment]
@danielroe but what about the different data type?

**Comment by danielroe** [comment]
It should work.

**Comment by ennioVisco** [comment]
> It should work.

OK, perhaps I was doing something wrong! I'll test it when it's out and in case I have issues, report! Thanks a lot ❤️

**Comment by ennioVisco** [comment]
> It should work.

Ok, I found what the problem is and it's just a documentation error. In fact, on the docs it says (`ResT` is not appearing at all):
<img width="684" alt="image" src="https://github.com/nuxt/nuxt/assets/740025/d4fb3636-eae5-49e9-8d86-fc685439e81c">
But the actual code is a bit different:
<img width="566" alt="image" src="https://github.com/nuxt/nuxt/assets/740025/f350cc5a-b67a-48e1-b519-baa2ec14ff81">

**Comment by danielroe** [comment]
It's really difficult to know how to describe this complex type best in the docs. PR welcome to improve this 🙏 

Maybe when we have twoslash enabled for this bit we can just display the source types.

**Comment by ennioVisco** [comment]
> It's really difficult to know how to describe this complex type best in the docs. PR welcome to improve this 🙏 
> 
> Maybe when we have twoslash enabled for this bit we can just display the source types.

You're right, it took me a while to appropriately type my custom useFetch. I still don't have a complete idea of all the connections between `ResT` and `DataT`.

I think your suggestion is the best, then if I feel I have a decent understanding I'll try to open a PR to help :)
