### ISSUE TITLE
Clientside buffer polyfill incomplete

### ISSUE THREAD

**Issue by mullet627** [nuxt/nuxt#26141]
### Environment

See reproduction

### Reproduction

https://stackblitz.com/edit/github-wutxc5?file=app.vue

### Describe the bug

Trying to use new 3.10.3 node polyfill seems to be recognized but incomplete.  Can someone let me know if I am using this incorrectly or understanding the feature incorrectly?

```
Uncaught Error: Module "node:buffer" has been externalized for browser compatibility. Cannot access "node:buffer.Buffer" in client code.  See https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
    at Object.get (__vite-browser-external:node:buffer:3:11)
    at app.vue:8:37
```

**Comment by danielroe** [comment]
You need to enable it:

```ts
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  experimental: {
    clientNodeCompat: true
  }
})
```

Updated sandbox: https://stackblitz.com/edit/github-wutxc5-zq71hz?file=nuxt.config.ts,app.vue

**Comment by mullet627** [comment]
I still get the same error if I try doing the import in utils/* ; is that supposed to be supported?
