### ISSUE TITLE
Implement Fade-Out/In Transition Effect for UCarousel

### ISSUE THREAD

**Issue by mullet627** [nuxt/nuxt#26143]
### Describe the feature

The current iteration of UCarousel primarily supports a slide transition effect for navigating through images in an autoplay mode. While this functionality serves its purpose for linear transitions, the introduction of a fade-out/in effect could significantly enhance the visual appeal and user experience. This feature request proposes the addition of an option within UCarousel to enable images to smoothly fade out and then fade in when transitioning, instead of the default slide mechanism.

The fade transition effect should be customizable, allowing developers to adjust the duration of both the fade-out and fade-in phases according to their specific needs. This feature would be optional and can be toggled based on the developer's preference, ensuring that UCarousel remains versatile for various use cases. Implementing this feature would provide a more dynamic and visually appealing way to showcase images, making UCarousel a more attractive option for developers looking to incorporate carousels in their web applications.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
Please open this in the Nuxt UI repo - https://github.com/nuxt/ui ☺️
