### ISSUE TITLE
Deployment guide for Azure App Service on Windows

### ISSUE THREAD

**Issue by DamianGlowala** [nuxt/nuxt#26140]
### Describe the feature

For Nuxt 2, there's an example `web.config` file which we can use to deploy an app on Azure App Service running on Windows:

https://v2.nuxt.com/deployments/azure-portal/#running-the-webserver

It would be great to have one in the docs which works with Nuxt 3 (SSR) (... or, ideally, a Nitro preset which will generate a Nuxt config-aware `web.config` file for us).

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
It would be nice to raise an issue in https://github.com/unjs/nitro to track the creation of this provider 🙏
