### ISSUE TITLE
fix: server handlers with `.json` suffix do not work anymore with nitro 2.9.2

### ISSUE THREAD

**Issue by dargmuesli** [nuxt/nuxt#26168]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.9.2
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  ()
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-eocpga?file=nuxt.config.ts,package.json

### Describe the bug

Nitro PR https://github.com/unjs/nitro/issues/2217 seems to have introduced a breaking change for server handlers with `.json.ts` suffix.

### Additional context

Nuxt OG image uses those routes for example: https://github.com/nuxt-modules/og-image/issues/172
Which makes automatic dependency updates like this go nana: https://github.com/dargmuesli/creal/pull/442

### Logs

The error states
 
> Error: Could not load raw:/home/projects/github-eocpga/bug/routes/index.json (imported by virtual:#internal/nitro/virtual/server-handlers): ENOENT: no such file or directory, open '/home/projects/github-eocpga/bug/routes/index.json

**Comment by pi0** [comment]
Should be fixed in latest nitro release (https://github.com/unjs/nitro/pull/2239)
