### ISSUE TITLE
Docs: Add @vue/test-utils example in Getting started with Unit testing

### ISSUE THREAD

**Issue by Alexandros23Kazantzidis** [nuxt/nuxt#26178]
### Describe the feature

After reading [Testing-Get started docs](https://nuxt.com/docs/getting-started/testing#unit-testing) I had confusion on whether I could use the already existing `@vue/test-utils`. I was able to do it after following a guide I found online and it worked just fine.

I wanted to raise this topic and ask if you think it would be useful to also add a section on how to set this in a new Nuxt 3 project? Was thinking just a basic step-by-step process on how to add `@vue/test-utils`, `vitest` and `happy-dom` and spin up a simple Unit test.

I know we already have `@nuxt/test-utils` but in some old projects it might be useful to also have a short guide on `@vue/test-utils`. What do you think?

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
I think it would be a great idea!

**Comment by Alexandros23Kazantzidis** [comment]
Openned PR here https://github.com/nuxt/nuxt/pull/26205 @danielroe
