### ISSUE TITLE
Warn if an httpOnly cookie is used client side (useCookie)

### ISSUE THREAD

**Issue by Ayax0** [nuxt/nuxt#26177]
### Describe the feature

At the moment, if I define an httpOnly cookie which is only to be read by the server, the content of this cookie is still sent to the client in the __NUXT_DATA__ area. If the client then hydrates, the content is removed, but it is still present in the __NUXT_DATA__ area.

```vue
<script lang="ts" setup>
const refresh_token = useCookie("refresh_token", { httpOnly: true });
</script>

<template>
  <div>{{ refresh_token }}</div>
</template>
```

It would be nice if either this data is not sent to the client at all, or at least a warning appears in the console that "protected" data is being used incorrectly.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by huang-julien** [comment]
Hey :wave: what do you mean by `the content of this cookie is still sent to the client in the NUXT_DATA area` ? This shouldn't be serialized in the SSR HTML. Also we don't have any `NUXT_DATA` object, did you meant `__NUXT__` ?

do you have a reproduction please ?

**Comment by Ayax0** [comment]
Hey, yes I meant the `__NUXT_DATA__` script element that is sent with the ssr response. I have been trying to reproduce this problem for 2 days now only to realize that the token that was sent was my access_token and not my refresh_token stored in the cookie. The two tokens look very similar. The access_token is stored normally with useState and so everything works as it should. sorry for taking up your time.
