### ISSUE TITLE
Add a way to properly infer types from dynamic routes

### ISSUE THREAD

**Issue by genu** [nuxt/nuxt#26171]
### Describe the feature

This has been an issue for some time, so I'll do my best to explain the issue and see if we can move a fix along or consider the recommended solution below.

Other relevant conversations that I was able to dig up:

#15280 
#22488 

## Current Behavior
Given these API routes:

```
── api
   └── group
       ├── .get.ts
       ├── .post.ts
       └── [groupId]
           ├── .delete.ts
           ├── .get.ts
           └── .put.ts
```

The following routes are generated in `nitro-routes.d.ts`:

```ts
'/api/group/': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/group/.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/group/.post').default>>>>
    }
    '/api/group/:groupId/': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/group/[groupId]/.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/group/[groupId]/.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/group/[groupId]/.put').default>>>>
    }
```

## The issue

There isn't a propper way to infer the type from the `api/group/:groupId`

**Option 1: [Doesn't work]** This matches the types from `/api/group/get`
```ts
const groupId = 42
const data = useFetch(`/api/group/${groupId}`)
```

**Option 2: [Doesn't work]**:  This infers the correct types from  from `/api/group/[groupId]/.get`, but the actual api call fails because we have not way to pass the _**groupID**_ value,
```ts
const groupId = 42
const data = useFetch(`/api/group/:groupId/`)
```

There isn't a way currently to deal with this,

## Proposal
There are two way to really solve this.
1. Fix the underlying type inference issue. I'm not sure if this feature is complete
2. I like option 2 above because it looks pretty clean. Can we add the ability to pass parameters to the `useFetch` function that allows setting those url parameters?

Something like this:

```ts
const data = useFetch('/api/group/:groupId/', {
   routerParams: {
       groupId: 42
   }
})
```

This would make the type inference work as expected, and make the API calls correctly.  We already use `RouterParams` on the backend, so naming would be consistent.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
Can't reproduce in this [StackBlitz](https://stackblitz.com/edit/nuxt-issues-26171?file=app.vue,server%2Fapi%2Ftest%2Findex.post.ts,server%2Fapi%2Ftest%2Findex.get.ts).

**Comment by genu** [comment]
@manniL Thanks for the insight.

> Be aware that your routes missing an index (.get.ts -> index.get.ts)

Its odd, I was on the impression that `.get.ts` worked as an alias to `index.get.ts`. We had assumed that behavior throughout our codebase and it had been working. That shouldn't be working, you're saying? 🤔 

Using `index.get.ts` as you mention does seem to make the issue go away. So, I'll close this for now.

I'll keep a look out for the other issue that remains open.

**Comment by ipanamski** [comment]
I have the same issue with useFetch. It has a return type of `globalThis.Ref<unknown, unknown>`:
```
const { params } = useRoute()
const { data } = await useFetch(`/api/things/${params.seoName}`)
```
I was able to work around doing this:
```
const { params } = useRoute()
const { data } = await useFetch(`/api/things/${<' '>params.seoName}`)
```

**Comment by BYohann** [comment]
i have the same issues, type inference is lost when :id is replaced with ${someValue}, there should be an option in parameters to replace it and keep :id in the string
