### ISSUE TITLE
app.config.ts typing fails

### ISSUE THREAD

**Issue by DavidDeSloovere** [nuxt/nuxt#26201]
### Environment

Working directory: /home/projects/github-xfi7iq                                                                                     5:27:10 PM
Nuxt project info:                                                                                                                  5:27:10 PM

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.9.3
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, runtimeConfig
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-xfi7iq?file=utils%2Fconfig.ts

`app.config.ts`
```javascript
export default defineAppConfig({
  foo: 'bar',
});

```

`utils/config.ts`
```javascript
const appConfig = useAppConfig();
appConfig.foo // 👈 no typing
```

### Describe the bug

A typed app config is expected from `useAppConfig()`, but unfortunately it does not work.

From the docs
"Nuxt tries to automatically generate a TypeScript interface from provided app config so you won't have to type it yourself."

### Additional context

Tooltip for app config variable does not show type string:
![image](https://github.com/nuxt/nuxt/assets/352626/80b7e840-97d8-4ab7-8ee6-8ab41f725ccc)

To prove typing works, tooltip for runtime config does show correct typing:
![image](https://github.com/nuxt/nuxt/assets/352626/617c3c1a-1e40-4ad1-af25-11d16ec41c82)

**Comment by danielroe** [comment]
This is a StackBlitz issue, I believe.

Running the type check command manually shows that the types are correctly inferred: https://stackblitz.com/edit/github-xfi7iq-tuss4e?file=utils/config.ts,package.json

**Comment by DavidDeSloovere** [comment]
Thanks Daniel 🙏. 
You have tought me to use also use `vue-tsc --noEmit && tsc --noEmit` for checking this.

The reason I chased this bug was because I didn't have typings in my project.
But the cause was not a Nuxt bug, but had something to do with using pnpm workspaces.

_After adding `shamefully-hoist=true` in `.npmrc` I not only got rid of errors in import statements of indirectly installed packages (ie. H3), but also fixed typing on appconfig!_

I didn't include `shamefully-hoist` at first because I know Nuxt does not require it since a few releases ago.

**Comment by danielroe** [comment]
In fact I also have fixed that bug. In v3.11 you can remove hoisting again
