### ISSUE TITLE
Env variables not working on Cloudflare Pages

### ISSUE THREAD

**Issue by matt-clegg** [nuxt/nuxt#26215]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.11.1
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    -
- Package Manager:  pnpm@8.15.4
- Builder:          -
- User Config:      devtools, runtimeConfig, nitro
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

The reproduction is increadibly simple. Create a new Nuxt app with `pnpm dlx nuxi@latest init <project-name>`.

`nuxt.config.ts`
```ts
export default defineNuxtConfig({
    devtools: {enabled: true},

    runtimeConfig: {
        public: {
            exampleValue: "unknown"
        }
    },
    
    nitro: {
        preset: "cloudflare-pages"
    }
})
```

`app.vue`
```vue
<template>
  <div>
    <strong>Config:</strong>
    <pre>{{ config}}</pre>
  </div>
</template>

<script setup lang="ts">
const config = useRuntimeConfig();
</script>
```

Build the Nuxt app with `nuxt build` then deploy it to Cloudflare using `pnpm dlx wrangler pages deploy dist/`.

### Describe the bug

When the Nuxt app is deployed to Cloudflare Pages using the `cloudflare-pages` nitro preset, environment variables aren't passed down into Nuxt. Unless I've missed a step in configuring the Nuxt app or something else in Cloudflare, I would expect the `public.exampleValue` to be overridden with my environment value.

The hosted Nuxt app can be found here: https://pages-env-demo-55q.pages.dev/
![image](https://github.com/nuxt/nuxt/assets/34515355/d2364ed7-d722-4a35-81f9-45a1f99719b9)

My environment variable in Cloudflare Pages are configured like so:
![image](https://github.com/nuxt/nuxt/assets/34515355/f0cd56f2-d5fa-467c-a7f7-7446ae0302fd)

**Comment by Amar-Gill** [comment]
Same issue as https://github.com/nuxt/nuxt/issues/25047#issuecomment-1975064474

^ let me know if this works for you.

**Comment by matt-clegg** [comment]
@Amar-Gill I tried changing my `nuxt.config.ts` to inclue the `process.env`, but it's still not passing the value down.

```ts
runtimeConfig: {
    public: {
        exampleValue: process.env.NUXT_PUBLIC_EXAMPLE_VALUE || "unknown"
    }
},
```

**Comment by Amar-Gill** [comment]
@matt-clegg can you try with just
```ts
runtimeConfig: {
    public: {
        exampleValue: process.env.NUXT_PUBLIC_EXAMPLE_VALUE
    }
},
```

**Comment by matt-clegg** [comment]
@Amar-Gill I forgot about that! I spotted [this video](https://www.youtube.com/watch?v=_FYV5WfiWvs) on runtime config. I fixed the nuxt.config.ts file moved the default value into the app.vue file and it's still not being picked up.

```ts
runtimeConfig: {
    public: {
        exampleValue: process.env.NUXT_PUBLIC_EXAMPLE_VALUE
    }
},
```

```vue
<template>
  <div>
    <strong>Config:</strong>
    <pre>{{ config.public.exampleValue || "No value" }}</pre>
  </div>
</template>

<script setup lang="ts">
const config = useRuntimeConfig();
</script>
```

https://pages-env-demo-55q.pages.dev/
![image](https://github.com/nuxt/nuxt/assets/34515355/2a2c1efe-51ed-4ed4-8bf3-feb6be433ea0)

**Comment by danielroe** [comment]
This was already resolved in  https://github.com/nuxt/nuxt/pull/26058 and should be present in the next release.
