### ISSUE TITLE
500 Cannot read properties of null (reading 'data')

### ISSUE THREAD

**Issue by RezaErfani67** [nuxt/nuxt#26213]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.11.1
- Nuxt Version:     3.10.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      devtools, app, nitro, experimental, srcDir, components, modules, css, vite, build, runtimeConfig
- Runtime Modules:  @nuxtjs/tailwindcss@6.11.3
- Build Modules:    -
------------------------------

### Reproduction

https://doctorjs.ir/article/fastApi-websocket-send-recieve-file

### Describe the bug

in development mode everything work correctly but in production i have this error

### Additional context

![image](https://github.com/nuxt/nuxt/assets/24381986/1dd76ed2-4df6-4e0c-bc13-2d15e7cf9576)

**Comment by RezaErfani67** [comment]
this state occures on production...
i insert link that you can see waht happen.

**Comment by madebyfabian** [comment]
@RezaErfani67 This looks like some data is not being loaded and thefore `data` is not available. Though this is likely not a Nuxt issue but something with your data loading. Can you create a minimal reproduction?

**Comment by RezaErfani67** [comment]
the problem related to ssl certificate... 

i changed my certificate and it produce this error because self sign ...
it should run with this command:
NODE_TLS_REJECT_UNAUTHORIZED='0' node index.mjs
