### ISSUE TITLE
useFetch does not update request parameter on reactive variable change

### ISSUE THREAD

**Issue by lammerfalcon** [nuxt/nuxt#26228]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.9.3
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-gewmnl?file=app.vue

### Describe the bug

I am using **useFetch** in a Vue.js component to fetch data based on a **reactive variable page**. However, I've encountered a bug where **useFetch** executes the request with the **old value of page** even after it changes, leading to incorrect data being fetched. This issue **does not occur** with **useAsyncData**, which **correctly** updates the request based on the page variable's new value.

**Comment by markthree** [comment]
Here, it will actually re-request, but `page.value` is only read once (non-reactive). You should pass the `page` ref directly, for example ⬇️

```diff
const { data: useFetchResponse } = useFetch('/api/test', {
  query: {
--  page: page.value,
++  page: page
  },
  watch: [page],
});
```

**Comment by WangShuan** [comment]
Hi, Could you please take a look at this video? It very helpful. [link](https://www.youtube.com/watch?v=0X-aOpSGabA). Thank you!

**Comment by enkot** [comment]
@lammerfalcon Just pass the reactive value to useFetch. It will watch for `page` changes under the hood and automatically rerun the request :)
```ts
const page = ref(0)

const { data } = useFetch('/api/test', {
  query: {
    page
  }
})
```
https://stackblitz.com/edit/github-gewmnl-z1zfu7?file=app.vue
