### ISSUE TITLE
useLazyFetch works in Development but not Production

### ISSUE THREAD

**Issue by RezaErfani67** [nuxt/nuxt#26222]
### Environment

Production:
------------------------------
- Operating System: Windows_NT
- Node Version:     v20.11.1
- Nuxt Version:     -
- CLI Version:      3.10.1
- Nitro Version:    -
- Package Manager:  unknown
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

Develoment:
------------------------------
- Operating System: Windows_NT
- Node Version:     v20.11.1
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.9.3
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      devtools, app, nitro, experimental, srcDir, components, modules, css, vite, build,
 runtimeConfig
- Runtime Modules:  @nuxtjs/tailwindcss@6.11.4     
- Build Modules:    -
------------------------------

### Reproduction

https://doctorjs.ir/article/fastApi-websocket-send-recieve-file

### Describe the bug

i dont know why after some years, yet there are problems on fetch data on nuxt...
why working on development is different with production...

**Comment by danielroe** [comment]
Based on your description, it is almost certainly an issue with your production API endpoint differing in some way from your development API endpoint.

**Comment by RezaErfani67** [comment]
in nuxt config define something like this:
```
   runtimeConfig: {
        SOME_SECRET_KEY: process.env.SOME_SECRET_KEY,
        public: {
          API_URL: process.env.NODE_ENV === 'development' ? 'http://127.0.0.1:9300/api' : 'https://doctorjs.ir/api',  
        },
      }, 

```

**Comment by manniL** [comment]
@RezaErfani67 This will not work as your runtimeConfig is not set up correctly. See https://www.youtube.com/watch?v=_FYV5WfiWvs

**Comment by RezaErfani67** [comment]
i compeltely removed runtimeConfig and use fetch...
here is resullt...
![image](https://github.com/nuxt/nuxt/assets/24381986/3adcc505-8335-42cd-959d-bf96a762a604)

```javascript

<script setup>

async function myfetch1(url, options, emits) {
  const { data, pending, error, refresh } = await useFetch(url, {
    key: hash(["api-fetch", url, options]),
    baseURL: "https://doctorjs.ir/api",
    initialCache: false,
    headers: new Headers({
      authorization: process.client ? localStorage.getItem("token") : "",
    }),
    ...options,
    onResponse({ response }) {
      return response._data;
    },
    onResponseError({ response }) {
      return response._data;
    },
  });
  const resData = data.value;
  const resPending = pending.value;
  const resError = error.value;
  return resData;
}

let response = await myfetch1("/article/artPost/view/" + props.enTitle, {
  method: "GET",
});
form.title = response.data.title;
form.enTitle = response.data.enTitle;
form.abstract = response.data.abstract;
form.description = response.data.description;
form.createdAt = response.data.createdAt;
form.cover = response.data.cover;
useHead({
  title: (title) => `${form.title}`,
  link: [
    {
      rel: "canonical",
      href: "/article/" + props.enTitle,
    },
  ],

  meta: [
    { name: "description", content: form.abstract },
    { name: "article:published_time", content: form.createdAt },
    { name: "twitter:card", content: form.abstract },
    { hid: "og:type", property: "og:type", content: "article" },
    { hid: "og:url", property: "og:url", content: "/article/" + props.enTitle },
    { hid: "og:brand", property: "og:brand", content: uuu().public.BRAND },
    {
      hid: "og:site_name",
      property: "og:site_name",
      content: uuu().public.SITE_NAME,
    },
    { hid: "og:locale", property: "og:locale", content: "fa" },
    {
      hid: "twitter-url",
      name: "twitter:url",
      content: "/article/" + props.enTitle,
    },

    { hid: "og:title", property: "og:title", content: form.title },
    { hid: "twitter:title", name: "twitter:title", content: form.title },

    {
      hid: "og:description",
      property: "og:description",
      content: form.abstract,
    },
    {
      hid: "twitter:description",
      name: "twitter:description",
      content: form.abstract,
    },

    {
      hid: "og:image",
      property: "og:image",
      content: "/api" + form.cover?.replace(/\\/g, "/"),
    },
    {
      hid: "twitter:image",
      property: "twitter:image",
      content: "/api" + form.cover?.replace(/\\/g, "/"),
    },

    { property: "og:site_name", content: uuu().public.TITLE },
    { name: "twitter:site", content: uuu().public.TITLE },
  ],
});


</script>

```

**Comment by manniL** [comment]
@RezaErfani67 can you provide a standalone reproduction? Most likely a userland problem

Also, why setting `resData` etc. manually and not just returning `useFetch` as is, then destructure from there?

**Comment by RezaErfani67** [comment]
aha...
i added console.log() to above code and see this error:
unable to verfy the first certificate...
![image](https://github.com/nuxt/nuxt/assets/24381986/05cf5f35-6e47-4ae7-a34c-89849a2cfc55)

**Comment by RezaErfani67** [comment]
after about one week , solved problem...
i changed  my certificate  and it produce this error because self sign ...
it should run with this command:
NODE_TLS_REJECT_UNAUTHORIZED='0' node index.mjs

**Comment by svenvreenen** [comment]
Isn't the issue above that you are using useFetch within a function and therefore the best practice should be to use $fetch instead as you are creating a js function?

**Comment by RezaErfani67** [comment]
@svenvreenen 
base on this [stack ](https://stackoverflow.com/questions/76839341/which-to-use-fetch-useasyncdata-or-usefetch-for-get-and-post-requests-in-nuxt#:~:text=useFetch%20is%20the%20most%20straightforward,right%20handler%20to%20go%20for.) i'm using $fetch when i want **post** data to server

**Comment by svenvreenen** [comment]
@RezaErfani67  In Nuxt 3, the useFetch function is typically used directly inside the setup function or in a composable function. so from the docs we can see this: https://nuxt.com/docs/api/composables/use-fetch.

if you try something like this, does it solve your issue?

`````
const props = defineProps({
  enTitle: {
    type: String,
    required: true,
  },
});

const { data: response, pending, error, refresh } = await useFetch(`/article/artPost/view/${props.enTitle}`, {
  method: "GET",
  baseURL: "https://doctorjs.ir/api",
  initialCache: false,
  headers: new Headers({
    authorization: process.client ? localStorage.getItem("token") : "",
  }),
  onResponse({ response }) {
    return response._data;
  },
  onResponseError({ response }) {
    return response._data;
  },
});`````
