### ISSUE TITLE
nuxt 3.10.3 使用 useFetch 获取数据正式环境会报错

### ISSUE THREAD

**Issue by csnan** [nuxt/nuxt#26236]
### Environment

- Operating System: Darwin
- Node Version:     v18.13.0
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.9.3
- Package Manager:  npm@8.1.2
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction
```
<template>
  <div>
    {{ aaa }}
  </div>
</template>

<script setup lang="ts"> 
const aaa = await useFetch('https://xxx/api/xxx', { method:'post', body: { lang: 'en', routerUrl: 'home' }})
</script>

<style scoped>
</style>
```

### Describe the bug

本地开发能正常获取数据，但是线上环境页面则会出现以下错误：
{ "data": null, "pending": false, "error": "Error: Headers is not a constructor", "status": "error" }

**Comment by GordonZH** [comment]
I got the same problem,  the request works fine in develop environment, but when build it and put to a docker environment , the request in the server-side will show the "Headers is not a constructor"

**Comment by csnan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by NikitaPoplavskiy** [comment]
> I got the same problem, the request works fine in develop environment, but when build it and put to a docker environment , the request in the server-side will show the "Headers is not a constructor"

Have you fixed that? I have exactly the same issue and i have no idea why it's actually going like that.

**Comment by csnan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
