### ISSUE TITLE
Huge Collection of Vue Router Errors for paths that arent in any source files

### ISSUE THREAD

**Issue by SomethingNew71** [nuxt/nuxt#26248]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.19.0
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.9.3
- Package Manager:  npm@10.5.0
- Builder:          -
- User Config:      ssr, app, css, modules, robots, plugins, runtimeConfig, build, vite, pwa
- Runtime Modules:  @nuxtjs/fontaine@0.4.1, nuxt-disqus@1.0.1, @vite-pwa/nuxt@0.6.0, @nuxtjs/sitemap@5.1.2, @nuxtjs/robots@3.0.0, @nuxt/image@1.4.0, nuxt-gtag@2.0.5, ()
- Build Modules:    -
------------------------------

### Reproduction

Delete .nuxt/ folder contents and then run `npm run dev`. App spins up and renders all these errors.

### Describe the bug

None of these sw files exist nor are they called by my source code. "/_nuxt/node_modules/@oruga-ui/oruga-next/dist/oruga.css" used to be part of the app but all references have been removed from app and package removed. Is there some sort of global cache somewhere that needs to be cleared? I cant find anywhere on my machine that caches this info. I also see a flash of a version of my app months old before hard refreshing to reload the page. 

### Additional context

N/a

### Logs

```shell-script
[Vue Router warn]: No match found for location with path "/_nuxt/node_modules/@oruga-ui/oruga-next/dist/oruga.css"
[Vue Router warn]: No match found for location with path "/_nuxt/node_modules/@oruga-ui/oruga-next/dist/oruga.css"
[Vue Router warn]: No match found for location with path "/dev-sw.js?dev-sw"
[Vue Router warn]: No match found for location with path "/dev-sw.js?dev-sw"
[Vue Router warn]: No match found for location with path "/workbox-5357ef54.js"
[Vue Router warn]: No match found for location with path "/workbox-5357ef54.js"
[Vue Router warn]: No match found for location with path "/_nuxt/node_modules/@oruga-ui/oruga-next/dist/oruga.css"
[Vue Router warn]: No match found for location with path "/_nuxt/node_modules/@oruga-ui/oruga-next/dist/oruga.css"
[Vue Router warn]: No match found for location with path "/dev-sw.js?dev-sw"
[Vue Router warn]: No match found for location with path "/dev-sw.js"
[Vue Router warn]: No match found for location with path "/workbox-5357ef54.js"
[Vue Router warn]: No match found for location with path "/workbox-5357ef54.js"
[Vue Router warn]: No match found for location with path "/dev-sw.js?dev-sw"
[Vue Router warn]: No match found for location with path "/dev-sw.js?dev-sw"
[Vue Router warn]: No match found for location with path "/dev-sw.js?dev-sw"
[Vue Router warn]: No match found for location with path "/dev-sw.js"
[Vue Router warn]: No match found for location with path "/dev-sw.js?dev-sw"
[Vue Router warn]: No match found for location with path "/dev-sw.js?dev-sw"
[Vue Router warn]: No match found for location with path "/dev-sw.js?dev-sw"
[Vue Router warn]: No match found for location with path "/dev-sw.js"
[Vue Router warn]: No match found for location with path "/workbox-5357ef54.js"
[Vue Router warn]: No match found for location with path "/workbox-5357ef54.js"
[Vue Router warn]: No match found for location with path "/workbox-5357ef54.js"
[Vue Router warn]: No match found for location with path "/workbox-5357ef54.js"
[Vue Router warn]: No match found for location with path "/dev-sw.js?dev-sw"
[Vue Router warn]: No match found for location with path "/dev-sw.js?dev-sw"
[Vue Router warn]: No match found for location with path "/dev-sw.js?dev-sw"
[Vue Router warn]: No match found for location with path "/dev-sw.js"
```
```

**Comment by manniL** [comment]
Seems like you still have a service worker running in dev mode which requests these files (probably from a previous PWA plugin or similar). Try to unregister it through the devtools.
