### ISSUE TITLE
Inconsistent Meta Information Retrieval in `﻿router.afterEach`: Previous Page's Data Returned for Current Page

### ISSUE THREAD

**Issue by asokawotulo** [nuxt/nuxt#26244]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.9.3
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-ec9bjb-tcq5dd

### Describe the bug

When using ﻿router.afterEach to access the document's meta information, the retrieved information reflects that of the previous route instead of the current one.

Despite trying ﻿await nextTick(), the issue persists with the previous page's meta information being retrieved.

**Comment by harlan-zw** [comment]
I think we can expose a way to easily hook into the route change + head updated event with Nuxt Scripts, maybe just with the `useTrackingScript` composable.

**Comment by asokawotulo** [comment]
Hi @harlan-zw, is the `useTrackingScript` similar to the `useScript` composable described in #22016 ?

**Comment by harlan-zw** [comment]
Current implementation is `useAnalyticsPageEvent`, here is the code if it helps:

```ts
export function useAnalyticsPageEvent(onChange?: (payload: TrackedPage) => void) {
  const nuxt = useNuxtApp()
  const route = useRoute()
  const head = injectHead()
  const payload = ref<TrackedPage>({
    path: route.fullPath,
    title: import.meta.client ? document.title : '',
  })
  // no know to know the title on the server until the page is rendered
  if (import.meta.server)
    return payload

  let lastPayload: TrackedPage = { path: '', title: '' }
  let stopDomWatcher: () => void
  nuxt.hooks.hook('page:finish', () => {
    Promise.race([
      // possibly no head update is needed
      new Promise(resolve => setTimeout(resolve, 100)),
      new Promise((resolve) => {
        stopDomWatcher = head.hooks.hook('dom:rendered', () => resolve())
      }),
    ]).finally(() => {
      stopDomWatcher && stopDomWatcher()
    }).then(() => {
      payload.value = {
        path: route.fullPath,
        title: document.title,
      }
      if (lastPayload.path !== payload.value.path || lastPayload.title !== payload.value.title) {
        onChange && onChange(payload.value)
        lastPayload = payload.value
      }
    })
  })
  return payload
}
```

Usage:

```ts
useAnalyticsPageEvent(({ title, path }) => {
  // triggered on route change
  gtag('event', 'page_view', {
    page_title: title,
    page_location: 'https://example.com/',
    page_path: path
  })
})
```
