### ISSUE TITLE
Page is being rendered twice when using nested routes with async components.

### ISSUE THREAD

**Issue by MrEraxd** [nuxt/nuxt#26258]
### Environment

Bug is happening since nuxt 3.6.2, especially this commit: https://github.com/nuxt/nuxt/commit/d0dde6426fe6ae58ec1ea94e47c66f6e0e2a4d63

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.10.0
- Nuxt Version:     -
- CLI Version:      3.10.1
- Nitro Version:    -
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-debhpn?file=app.vue

### Describe the bug

_Because I didn't want to create components that are big, please use performance tab in devtools and slow down CPU as much as possible so you can see the effect. Bug is happening in dev and after generating. But in real project this can be visible even without cpu slowdown._

When using lazy components with nested routes, nuxt does not wait for page to generate/load all components before removing old node. This causes page to blink. When keeping same route but different url this problem does not happen (See video, name of the route is on top).

3.6.2+ (On video 10.3.1 [Stackblitz](https://stackblitz.com/edit/github-debhpn?file=app.vue))

https://github.com/nuxt/nuxt/assets/34748386/172f4f8f-0f0b-4092-b36a-5a0b9093a971

3.6.1 ([Stackblitz](https://stackblitz.com/edit/github-debhpn-vunj6r?file=package.json))

https://github.com/nuxt/nuxt/assets/34748386/3d29d506-33c1-44c7-b808-0a6246e1da1e

### Additional context

I'm working with CMS and I want to get list of components used in page and generate static page based on that. I've also noticed that [this function](https://github.com/nuxt/nuxt/blob/5dc96de8a928d10e90f47d9941ed7402328b1e3f/packages/nuxt/src/pages/runtime/page.ts#L71) is called twice when changing routes

Workarounds:

- Register component globally
- Use catch all route and handle everything there thus not changing route do not cause this issue.
- Add page transition to hide this blink (even 0.3s works for me)

**Comment by MrEraxd** [comment]
Update on findings:

I've found out that calling `page:finish` here: https://github.com/nuxt/nuxt/blob/5dc96de8a928d10e90f47d9941ed7402328b1e3f/packages/nuxt/src/pages/runtime/page.ts#L118

Causes page to rerender and blink. Curently I'm searching what exactly is causing issue.

**Comment by MrEraxd** [comment]
It looks like calling syncCurrentRoute in:

https://github.com/nuxt/nuxt/blob/5dc96de8a928d10e90f47d9941ed7402328b1e3f/packages/nuxt/src/pages/runtime/plugins/router.ts#L114

is causing this issue.

**Comment by MrEraxd** [comment]
Because of this statement: https://github.com/nuxt/nuxt/blob/977377777afcc38186c7a309a86e9e5613470652/packages/nuxt/src/pages/runtime/plugins/router.ts#L118 from commit https://github.com/nuxt/nuxt/commit/7a706445f8e3837731e3842c9a24d6995a1e2232 when changing route to different instance of NuxtPage page is prune to rerenender NuxtPage when changing files responsible for such route ex. `/[page].vue -> /[type]/[slug].vue`. Changing this if statement to be `!==` causes moving from same file route ex. `[page] -> [page]` blink and render twice instead.

Removing this if statement and just calling `syncCurrentRoute` after each route removes an issue and casues correct order of sync and render:

- (Sync route -> Render NuxtPage -> Sync route) 
- instead of 
- (Render NuxtPage-> Sync -> Render NuxtPage)

for both redirections `/[page].vue -> /[type]/[slug].vue` and `/[page].vue -> /[page].vue`. I would like to make PR but want to discuss my solution first. I don't know why was this if statement added as issue linked to this commit is for nuxt2.

**Comment by tkjaergaard** [comment]
Experiencing the same issue with nested routes.

**Comment by danielroe** [comment]
The issue is likely that `page:finish` should not be called until the child page resolves.

**Comment by DarkLite1** [comment]
Same issue: old content is not always removed from the page in dev mode.

**Comment by danielroe** [comment]
The issue here seems to be the use of `defineAsyncComponent` within the template. It should not be used there as every time it's called, it creates a fresh component with a fresh loading state.

Instead, try something like this:

```ts
const { data } = await useAsyncData(route.fullPath, () =>
  $fetch(`/api/cms-response?${route.fullPath}`)
);


const blocks = computed(() => data.value?.blocks.map(block => ({
  ...block,
  component: defineAsyncComponent({
    loader: () => import(`../components/${block.componentName}.vue`),
  })
})) || [])
```

(This resolves your issue for me.)
