### ISSUE TITLE
Problem with useFetch after refresh in production

### ISSUE THREAD

**Issue by milanblasko28** [nuxt/nuxt#26264]
### Environment

- node-20.5:latest
- nuxt: 3.10.3,

### Reproduction

https://stackblitz.com/~/github.com/minoo221/slovbohemia
```
<script setup lang="ts">



const {
  data: walls,
  pending,
  error,
  refresh,
} = await useFetch(url + "/sliding-wall", {
  immediate: true,
});

const banner: Ref<any> = ref({
  title: walls.value?.data.attributes.title,
  desc: walls.value?.data.attributes.desc,
  btns: [{ title: "Kontaktovať", link: localePath("/"), color: "primary" }],
  slides: [{ img: "/images/offer-3.jpg" }],
  maxWidth: "790px",
});


onMounted(() => {
  console.log("walls", walls?.value);
});
</script>
```

### Describe the bug

Hi, I have problem with fetch data in production mode. 

In development mode everything is okay. If I go to the view through the route everything fine, but If I refresh page console.log from onMounted method return null.

Here is Dockerfile
```
FROM node:18-alpine

WORKDIR /opt/

RUN apk update && apk upgrade && apk add git
COPY . /opt/

#RUN npm install --global yarn
RUN yarn && yarn build

EXPOSE 3000

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000

CMD [ "yarn", "start" ]`

### Additional context

_No response_

### Logs

_No response_
```

I notice one thing. If I log 
` console.log("walls", walls);` I get some data in _value object
![image](https://github.com/nuxt/nuxt/assets/152985226/c6b1c304-253f-4177-af90-4a5d7a7c2c5c)
but if I logs
` console.log("walls", walls.value);`
I get 
![image](https://github.com/nuxt/nuxt/assets/152985226/15579322-0939-4955-aee3-7cdec9f1f650)
I dont kwon If I use this wrong but it work properly in development mode

URL: http://194.163.176.146:3050/posuvne-steny

**Comment by milanblasko28** [comment]
I'm update issue.

**Comment by milanblasko28** [comment]
> Would you be able to provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
> 
> More info

I'm updated issue

**Comment by luc122c** [comment]
Your reproduction is not accessible.

At first glace, it may simply be the case that the data has not been fetched yet when `onMounted` runs. Instead of running code when the page is ready, you could use a watcher to wait for the data to be ready.

```ts
watch(walls, (data) => {
	if (data) {
		console.log("walls", data);
	}
}, {
	immediate: true
]);
```

It may also help to use a utility such as [whenever](https://vueuse.org/shared/whenever/) or [watchOnce](https://vueuse.org/shared/watchOnce/) from VueUse

**Comment by danielroe** [comment]
@luc122c is likely correct. It's possible the data can't be fetched on the server side, for whatever reason. Check to see if that might be the issue.

I'm closing as there's no reproduction I can access...
