### ISSUE TITLE
Add module aliases so that running nuxi module add tailwind would actually install @nuxtjs/tailwindcss

### ISSUE THREAD

**Issue by martinszeltins** [nuxt/nuxt#26277]
### Describe the feature

I wanted to add tailwind module so I ran `nuxi module add tailwind` and it added tailwind package instead of @nuxtjs/tailwindcss but we all know that I actually wanted to add the Tailwind Nuxt module. It would be very convenient if Nuxt was a bit smarter about this and understand what I actually meant.

As you can see what Nuxt actually added is completely wrong. Perhaps we could add some aliases to modules so nuxi could install the correct one? That would be very convenient. I have seen other projects do this and it is amazing DX.

For example, Symfony projects does this: https://github.com/symfony/recipes#aliases-option

It added `tailwind` instead of `@nuxtjs/tailwindcss`

```diff
  "devDependencies": {
    "@vueuse/nuxt": "^10.9.0",
+    "tailwind": "^4.0.0"
  }
```

and

```diff
export default defineNuxtConfig({
+  modules: ["tailwind"]
})
```

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
There are indeed module aliases. In this case, however, the alias is `tailwindcss` rather than `tailwind`.

**Comment by Atinux** [comment]
Feature is on its way 🚀 

https://github.com/nuxt/cli/pull/362
