### ISSUE TITLE
Settle on either `undefined` or `null` for async data's data and error

### ISSUE THREAD

**Issue by DamianGlowala** [nuxt/nuxt#26295]
### Describe the feature

Currently, there is a discrepancy in default values of async data's data and error:
- data is assigned an `undefined` value (unless a different default value is specified)
- error is assigned a `null` value

It would be good to consider settling on one of them for consistency, unless there's a justifiable reason for why they have to differ.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
We will settle on `undefined` 🚀 🔥

**Comment by manniL** [comment]
To not forget: This might mean additional behavior changes for `getCachedData()` too, or an additional check for compat.
