### ISSUE TITLE
Consola: Context is not available

### ISSUE THREAD

**Issue by Ayax0** [nuxt/nuxt#26308]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v21.5.0
- Nuxt Version:     3.11.0
- CLI Version:      3.10.1
- Nitro Version:    2.9.4
- Package Manager:  npm@10.2.5
- Builder:          -
- User Config:      devtools, nitro
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

[Reproduction](https://codesandbox.io/p/devbox/elegant-cannon-zkt5yk?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltvjtzqu00073j6hjdljlaln%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltvjtzqu00023j6hf7jaaofa%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltvjtzqu00043j6hgcyg8cwu%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltvjtzqu00063j6h6ljbmpky%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltvjtzqu00023j6hf7jaaofa%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltvjtzqu00013j6hwjwgoqp7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cltvjtzqu00023j6hf7jaaofa%2522%252C%2522activeTabId%2522%253A%2522cltvjtzqu00013j6hwjwgoqp7%2522%257D%252C%2522cltvjtzqu00063j6h6ljbmpky%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltvjtzqu00053j6h33ueauum%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cltvjtzqu00063j6h6ljbmpky%2522%252C%2522activeTabId%2522%253A%2522cltvjtzqu00053j6h33ueauum%2522%257D%252C%2522cltvjtzqu00043j6hgcyg8cwu%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltvjtzqu00033j6h7he13is7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522cltvjtzqu00043j6hgcyg8cwu%2522%252C%2522activeTabId%2522%253A%2522cltvjtzqu00033j6h7he13is7%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Describe the bug

Since the latest 3.11 update I get a "Context is not available" error when I try to use console.log in a NitroPlugin in the server Folder `/server/plugins/testPlugin.ts`

### Additional context

I think it has to do with the latest "Better logging" update

### Logs

```shell-script
ERROR  [worker reload] [worker init] Context is not available                                                                                              2:22:38 PM

  at Object.use (node_modules/unctx/dist/index.mjs:31:15)
  at <anonymous> (node_modules/nuxt/dist/core/runtime/nitro/dev-server-logs.js:14:30)
  at Object.log (node_modules/nuxt/dist/core/runtime/nitro/dev-server-logs.js:53:7)
  at Consola._log (node_modules/consola/dist/core.mjs:381:16)
  at resolveLog (node_modules/consola/dist/core.mjs:349:14)
  at Consola._logFn (node_modules/consola/dist/core.mjs:377:5)
  at console.log (node_modules/consola/dist/core.mjs:306:19)
  at <anonymous> (server/plugins/pluginTest.ts:2:1)
  at createNitroApp (node_modules/nitropack/dist/runtime/app.mjs:143:7)
  at <anonymous> (node_modules/nitropack/dist/runtime/app.mjs:151:25)
```

**Comment by Ayax0** [comment]
As mentioned in the release note [v3.11.0](https://github.com/nuxt/nuxt/releases/tag/v3.11.0) they have revised the logging so that serverside logs are also displayed clientside. My guess is that something went wrong here.

The example with the NitroPlugin literally looks like this:
```ts
// plugins/test.ts
export default defineNitroPlugin((nitroApp) => {
  console.log('Nitro plugin', nitroApp)
})
```
Accordingly, I do not think that this is intentional.

**Comment by mwohlan** [comment]
I noticed this as well when playing with Nitro Websockets last night. Whenever I used console.log within the hooks, I got the same error.
