### ISSUE TITLE
[SSG] Nuxt v3.11.0 generates lookbehind regex that old Safari does not support

### ISSUE THREAD

**Issue by hellososhi** [nuxt/nuxt#26309]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.17.0`
- Nuxt Version:     `3.11.0`
- CLI Version:      `3.10.1`
- Nitro Version:    `2.9.4`
- Package Manager:  `yarn@1.22.22`
- Builder:          `-`
- User Config:      `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

You can reproduce using this minimal starter.
https://stackblitz.com/github/nuxt/starter/tree/v3?file=README.md
1. install modules using the package manager
2. generate static files with `nuxt generate` command
3. deploy files with `npx serve .output/public` command
4. access `localhost:3000` with Safari (<=16.3)
5. syntax error occurs

### Describe the bug

When static files are generated with the `nuxt generate` command, lookbehind regex (`?<!`), which is not supported by older Safari, is output to the JS file.
To find the JS file, look at the first script tag in the head tag of `.output/public/index.html`.

**Comment by danielroe** [comment]
This is upstream from `ufo` from https://github.com/unjs/ufo/pull/222. We likely need to update here:

https://github.com/nuxt-contrib/ufo/blob/3910926c2666c8dafd193d6dd485cc7527d8ecbf/src/utils.ts#L359-L374

cc: @pi0.

**Comment by rylanharper** [comment]
Going off this, this is a major bug preventing all my Nuxt SSG sites from deploying on Netlify:
```
[error] Nuxt Build Error: "joinRelativeURL" is not exported by "../node_modules/.pnpm/ufo@1.4.0/node_modules/ufo/dist/index.mjs", imported by "virtual:nuxt:/opt/build/repo/web/.nuxt/paths.mjs".
```

The solution is to downgrade back to `v3.10.3`

**Comment by pi0** [comment]
Browser compatibility issue with ufo is **hotfixed** via https://github.com/unjs/ufo/pull/226 with [ufo@1.5.2](https://github.com/unjs/ufo/releases/tag/v1.5.2). 

Please make sure to update lockfile manually (or using `npx nuxi upgrade --force`), remove `node_modules` if the issue presists and check `pnpm why ufo` or `npm why ufo` to see why an older version of ufo might have been stalled.

---

@danielroe What is Nuxt browser support policy? ([caniuse](https://caniuse.com/js-regexp-lookbehind) shows safari >= 16.4 as minimum and 92% global coverage)
