### ISSUE TITLE
[3.11.0] useLoadingIndicator finish type error

### ISSUE THREAD

**Issue by dethdkn** [nuxt/nuxt#26317]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v21.5.0
- Nuxt Version:     3.11.0
- CLI Version:      3.10.1
- Nitro Version:    -
- Package Manager:  pnpm@8.15.4
- Builder:          -
- User Config:      modules, app, css, site, i18n, colorMode, ui, robots, sitemap, linkChecker, runtimeConfig, devServer, devtools
- Runtime Modules:  @nuxt/image@1.4.0, @nuxt/ui@2.14.2, @nuxtjs/i18n@8.2.0, @nuxtjs/seo@2.0.0-rc.9, @vueuse/nuxt@10.9.0, @pinia/nuxt@0.5.1, @pinia-plugin-persistedstate/nuxt@1.2.0
- Build Modules:    -
------------------------------

### Reproduction

I tried but I guess nuxt is broken on stackblitz? 

https://stackblitz.com/edit/nuxt-starter-uq849c?file=README.md

### Describe the bug

Before nuxt 3.11.0 I was able to use the loading indicator like this

```ts
const { start, isLoading, finish } = useLoadingIndicator()
start()
...
finish()
```

Now it gives me a type error if a don't add {} inside the finish func
```ts
const { start, isLoading, finish } = useLoadingIndicator()
start()
...
finish({})
```

### Additional context

![1](https://github.com/nuxt/nuxt/assets/106754824/69a6574c-bd2a-47c2-8b8b-3b34bcedaea8)

Since force is the only entry inside opts and it's optional, I guess opts should be
```ts
opts?: {
	force?: boolean | undefined
}
```

Sorry in advance if I'm saying anything wrong here!

**Comment by danielroe** [comment]
Thanks also for note about Stackblitz. Fixed in https://github.com/nuxt/nuxt/commit/523db1a1972d13dee05bfcf6c14523cb55b6e5b7.
