### ISSUE TITLE
Nuxt v3.11.0 proxyRequest in server api routes makes nitro crash if proxy server is down

### ISSUE THREAD

**Issue by geminigeek** [nuxt/nuxt#26318]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.11.1
- Nuxt Version:     3.11.0
- CLI Version:      3.10.1
- Nitro Version:    2.9.4
- Package Manager:  bun@1.0.29
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/geminigeek/proxy-request-nitro-error

clone repo
bun install
bun run dev

visit http://localhost:3000/api/hello

then try reloading http://localhost:3000, app home page , nothing happens , it seems nitro crashed

### Describe the bug

after a failed proxy request to a dead proxy server, the error is unhandled it crashes nitro/h3.
error in  console is below

```

 ERROR  [nuxt] [request error] [unhandled] [500] fetch failed
  at node:internal/deps/undici/undici:12345:11
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async sendProxy (./node_modules/h3/dist/index.mjs:1157:20)
  at async ./node_modules/h3/dist/index.mjs:1962:19
  at async Object.callAsync (./node_modules/unctx/dist/index.mjs:72:16)
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:2249:7)
```

### Additional context

same was working as expected in 3.10.3

**Comment by danielroe** [comment]
Would you check if this is reproducible with earlier nuxt but updated nitro/ofetch? This doesn't _sound_ like a Nuxt issue.

**Comment by geminigeek** [comment]
> Would you check if this is reproducible with earlier nuxt but updated nitro/ofetch? This doesn't _sound_ like a Nuxt issue.

working fine with  3.10.3 , i checked before posting

**Comment by danielroe** [comment]
I mean, did you manually upgrade nitro/ofetch with your v3.10.3?

**Comment by geminigeek** [comment]
no , this test repo i installed v3.11.0 fresh install 
error came, 
i downgraded nuxt, deleting node_modules and choosing 
```
 "nuxt": "3.10.3",
```
error was not present 

i again deleted node_modules , added 
```
 "nuxt": "^3.11.0",
```
same error

nuxt 3.10.3 throws this error in console but its a handled, error passed to client 
```
[nuxt] [request error] [unhandled] [500] fetch failed
  at node:internal/deps/undici/undici:12345:11
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async sendProxy (./node_modules/h3/dist/index.mjs:1157:20)
  at async Object.handler (./node_modules/h3/dist/index.mjs:1962:19)
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:2249:7)
```

**Comment by danielroe** [comment]
Okay, great. Thank you!

**Comment by danielroe** [comment]
cc: @pi0

**Comment by pi0** [comment]
Any chance you can reproduce with nitro alone and Node.js? (Bun might be unstable)

**Comment by geminigeek** [comment]
hi,

same issue,  nitro crashed, i ran the production repo on windows with node , i will try and send a reproduction with stand alone nitro, but the issue is somewhere else as this test repo works fine with  Nuxt 3.10.3

```

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.11.1
- Nuxt Version:     3.11.0
- CLI Version:      3.11.0
- Nitro Version:    2.9.4
- Package Manager:  pnpm@8.15.4
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

```

here the error with node in windows 11

```
F:\node-local\git-issues\proxy-request-nitro-error>pnpm run dev

> nuxt-app@ dev F:\node-local\git-issues\proxy-request-nitro-error
> nuxt dev

Nuxt 3.11.0 with Nitro 2.9.4                                                                                                           10:42:25 pm
                                                                                                                                       10:42:25 pm
  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

  ➜ DevTools: press Shift + Alt + D in the browser (v1.0.8)                                                                            10:42:27 pm

i Vite server warmed up in 623ms                                                                                                       10:42:29 pm
i Vite client warmed up in 1264ms                                                                                                      10:42:29 pm
√ Nuxt Nitro server built in 666 ms                                                                                              nitro 10:42:30 pm

 ERROR  [nuxt] [request error] [unhandled] [500] fetch failed
  at node:internal/deps/undici/undici:12345:11
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async sendProxy (/F:/node-local/git-issues/proxy-request-nitro-error/node_modules/.pnpm/h3@1.11.1/node_modules/h3/dist/index.mjs:1157:20)
  at async /F:/node-local/git-issues/proxy-request-nitro-error/node_modules/.pnpm/h3@1.11.1/node_modules/h3/dist/index.mjs:1962:19
  at async Object.callAsync (/F:/node-local/git-issues/proxy-request-nitro-error/node_modules/.pnpm/unctx@2.3.1/node_modules/unctx/dist/index.mjs:72:16)
  at async Server.toNodeHandle (/F:/node-local/git-issues/proxy-request-nitro-error/node_modules/.pnpm/h3@1.11.1/node_modules/h3/dist/index.mjs:2249:7)
```

**Comment by geminigeek** [comment]
i did a little digging sendproxy need a try catch in h3 , this seems to be the cause of this error , may be some thing changed in undici.

here is what i a patched in  h3/index.mjs to get around this ,

```
async function sendProxy(event, target, opts = {}) {
  try {
    const response = await _getFetch(opts.fetch)(target, {
      headers: opts.headers,
      ignoreResponseError: true,
      // make $ofetch.raw transparent
      ...opts.fetchOptions
    });
    
  } catch (error) {
    console.log('error :>> ', error);
    return event.node.res.end();
  }
....
```

**Comment by ghartemann** [comment]
We have the exact same issue with our project when updating to 3.11.0.

This error pops up and then build fails.

>  ERROR  [nuxt] [request error] [unhandled] [500] fetch failed
  at Object.fetch (node:internal/deps/undici/undici:11730:11)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async sendProxy (/C:/wamp64/www/maslow/source-web/node_modules/h3/dist/index.mjs:1157:20)
  at async /C:/wamp64/www/maslow/source-web/node_modules/h3/dist/index.mjs:1962:19
  at async Object.callAsync (/C:/wamp64/www/maslow/source-web/node_modules/unctx/dist/index.mjs:72:16)
  at async Server.toNodeHandle (/C:/wamp64/www/maslow/source-web/node_modules/h3/dist/index.mjs:2249:7)

We're using yarn, not bun. Here's the project info:

- Operating System: Windows_NT
- Node Version:     v20.10.0
- Nuxt Version:     3.11.0
- CLI Version:      3.10.1
- Nitro Version:    2.9.4
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, app, css, ssr, plugins, components, buildModules, fontMetrics, image, modules, gtm, axios, server, devServer, postcss, build, vue, runtimeConfig, sourcemap, vite, alias, debug, nitro, hooks
- Runtime Modules:  @nuxtjs/tailwindcss@6.11.4, @zadigetvoltaire/nuxt-gtm@0.0.13, @nuxt/image@1.2.0, @pinia/nuxt@0.5.1, @vueuse/nuxt@10.9.0
- Build Modules:    @nuxtjs/dotenv, nuxt-webpack-optimisations, @nuxt/postcss8, @pinia/nuxt@0.5.1, @nuxtjs/fontaine@0.4.1

**Comment by lacoste-sochi** [comment]
The same error (The proxy fell off. As I understand it, even the headers are not thrown using usefetch(

`

{"url":"/api/excursion/partner/excursion","statusCode":500,"statusMessage":"","message":"fetch failed","stack":"
at Object.fetch (node:internal/deps/undici/undici:11576:11)\nat async sendProxy (/PATCH/node_modules/h3/dist/index.mjs:1157:20)\nat async
/PATCH/node_modules/h3/dist/index.mjs:1962:19\nat async Object.callAsync (PATCH/node_modules/unctx/dist/index.mjs:72:16)\nat async Server.toNodeHandle (PATCH/node_modules/h3/dist/index.mjs:2249:7)
"}

`

Everything worked before the update(((

**Comment by manniL** [comment]
Why not try/catching the code? 🤔

```
 defineEventHandler(async (event) => {
    let url = "http://some-non-existent.url.domain"
    try {
      const req = await proxyRequest(event, url)
      return req
    } catch {
      throw createError({
        status: 519, // TODO
        statusMessage: 'TODO'
      })
    }
  }),
```

**Comment by geminigeek** [comment]
> Why not try/catching the code? 🤔
> 
> ```
>  defineEventHandler(async (event) => {
>     let url = "http://some-non-existent.url.domain"
>     try {
>       const req = await proxyRequest(event, url)
>       return req
>     } catch {
>       throw createError({
>         status: 519, // TODO
>         statusMessage: 'TODO'
>       })
>     }
>   }),
> ```
> 
> Linking [unjs/h3#722](https://github.com/unjs/h3/issues/722) anyway

if i go this way , i have to do it in too many places, i am using proxy to hide my real api endpoints, i expect proxy to work as expected as in the last version 3.10.3

**Comment by lacoste-sochi** [comment]
I've solved the problem easier so far.

`
yarn add h3@1.9.0
`
https://github.com/unjs/h3/issues/722

I realized this when I sent a postman request to the proxy

![image](https://github.com/nuxt/nuxt/assets/42961050/8b13e21f-963b-49c8-b61c-890dd9a44f4f)

**Comment by manniL** [comment]
Closing here as we can track in https://github.com/unjs/h3/issues/722 and a workaround exists 👍🏻
