### ISSUE TITLE
Can't reach nuxt server from host.docker.internal

### ISSUE THREAD

**Issue by pmnzt** [nuxt/nuxt#26324]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.17.1
- Nuxt Version:     3.11.0
- CLI Version:      3.10.1
- Nitro Version:    -
- Package Manager:  pnpm@8.15.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/pmnzt/nuxt-host-docker-internal

### Describe the bug

In docker to reach localhost i use ``host.docker.internal``,
eg. ``http://host.docker.internal:3000/api/team/admin``, works if this api was listening on port 3000 and was not a nuxt app.
if a nuxt app then i am able to call it using ``http://localhost:3000/api/team/admin`` outside docker, but inside docker wouldn't work ofc.

### Additional context

My docker app that needs to call the nuxt endpoint is a supabase app.
I am able to send requests from it into any other server i have locally using just `host.docker.internal`.
But if i make the api in nuxt. it won't work.

**Comment by igorjacauna** [comment]
Does it works if you run Nuxt with `--public`  options like `pnpm dev --public`?

Or with `--host=0.0.0.0`?

**Comment by pmnzt** [comment]
> Does it works if you run Nuxt with `--public` options like `pnpm dev --public`?
> 
> Or with `--host=0.0.0.0`?

yes :) works now. using --public and --host=0.0.0.0

Thank you

**Comment by igorjacauna** [comment]
> > Does it works if you run Nuxt with `--public` options like `pnpm dev --public`?
> > 
> > Or with `--host=0.0.0.0`?
> 
> yes :) works now. using --public and or --host=0.0.0.0
> 
> Thank you

Nice!

I believe that only the `--public` option would resolve! 😉
