### ISSUE TITLE
Inconsistent version between package.json and runtime

### ISSUE THREAD

**Issue by nazmirket** [nuxt/nuxt#26325]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.11.1`
- Nuxt Version:     `3.11.0`
- CLI Version:      `3.10.1`
- Nitro Version:    `2.9.4`
- Package Manager:  `pnpm@8.15.3`
- Builder:          `-`
- User Config:      `app`, `build`, `modules`, `i18n`, `components`, `ssr`, `runtimeConfig`, `devServer`, `typescript`, `vite`, `tailwindcss`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.11.4`, `@pinia/nuxt@0.5.1`, `@pinia-plugin-persistedstate/nuxt@1.2.0`, `@nuxtjs/i18n@8.2.0`
- Build Modules:    `-`

### Reproduction

.

### Describe the bug

When I removed pnpm-lock.yaml and node_modules without changing package.json this strange bug occurred. In my package.json the nuxt version is ```3.9.1``` but when I run the app it displays ```3.11.0``` it is also same in the ```nuxi info``` command output. There are lots of things broken since this bug. My tailwind config not working properly, primevue acting strange etc. 

### Additional context

Below is my ```package.json``` file

```JSON
{
	"name": "auth",
	"private": true,
	"scripts": {
		"build": "nuxt build",
		"dev": "nuxt dev",
		"generate": "nuxt generate",
		"preview": "nuxt preview",
		"postinstall": "nuxt prepare"
	},
	"devDependencies": {
		"@nuxtjs/tailwindcss": "^6.10.3",
		"@pinia-plugin-persistedstate/nuxt": "^1.2.0",
		"@types/lodash": "^4.14.202",
		"@types/node": "^20.10.7",
		"@typescript-eslint/eslint-plugin": "^6.16.0",
		"@typescript-eslint/parser": "^6.16.0",
		"eslint": "^8.56.0",
		"eslint-config-prettier": "^9.1.0",
		"eslint-plugin-nuxt": "^4.0.0",
		"eslint-plugin-prettier": "^5.1.2",
		"eslint-plugin-vue": "^9.19.2",
		"nuxt": "^3.9.1",
		"prettier": "^3.1.1",
		"tailwindcss": "^3.4.0",
		"vite-plugin-eslint": "^1.8.1"
	},
	"dependencies": {
		"@nuxtjs/i18n": "^8.2.0",
		"@pinia/nuxt": "^0.5.1",
		"date-fns": "^3.3.1",
		"lodash": "^4.17.21",
		"lucide-vue-next": "^0.303.0",
		"pinia": "^2.1.7",
		"primevue": "^3.45.0"
	}
}
```

This is also my ```nuxt.config.ts``` file

```TypeScript
import eslint from 'vite-plugin-eslint'

export default defineNuxtConfig({
	app: {
		head: {
			title: 'auth',
			meta: [
				{ charset: 'utf-8' },
				{
					name: 'viewport',
					content: 'width=device-width, initial-scale=1',
				},
				{
					hid: 'description',
					name: 'description',
					content: 'Novaya UMS',
				},
			],
			link: [
				{
					rel: 'icon',
					type: 'image/x-icon',
					href: 'http://localhost:3030/api/v1/public/brand/min.webp',
				},
			],
		},
	},

	build: {
		transpile: ['primevue'],
	},

	modules: [
		'@nuxtjs/tailwindcss',
		'@pinia/nuxt',
		'@pinia-plugin-persistedstate/nuxt',
		'@nuxtjs/i18n',
	],

	i18n: {
		defaultLocale: 'prm',
		locales: [
			{ code: 'prm', file: 'locales/prm.json' },
			{ code: 'scn', file: 'locales/scn.json' },
		],
		detectBrowserLanguage: false,
		strategy: 'no_prefix',
	},

	// Component auto import
	components: [
		{
			path: '~/components',
			pathPrefix: false,
			extensions: ['.vue'],
			global: true,
		},
	],

	ssr: false,

	runtimeConfig: {
		public: {
			API: 'http://localhost:3030/api/v1',
		},
	},

	devServer: {
		port: 7010,
	},

	typescript: {
		tsConfig: {
			compilerOptions: {
				declaration: true,
				declarationDir: 'types',
			},
			include: ['~/types'],
		},
	},

	vite: {
		plugins: [eslint()],
	},

	tailwindcss: {
		cssPath: '~/assets/css/style.css',
		configPath: 'tailwind.config.js',
		injectPosition: 'first',
	},
})

```

**Comment by mukundshah** [comment]
removing lockfile will cause installation of latest packages which satisfies the constraint set in `package.json`. Since in your `package.json`, nuxt is set to `^3.9.1`,  and `3.11.0` satisfies the constraint, it's a norrmal thing to occur. You can pin your nuxt version to `3.9.1` . That should solve your issue.

References:
1. https://docs.npmjs.com/about-semantic-versioning
