### ISSUE TITLE
JavaScript heap out of memory when using `ts.createSourceFile` in server api

### ISSUE THREAD

**Issue by gjfLeo** [nuxt/nuxt#26327]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.11.1
- Nuxt Version:     3.11.0
- CLI Version:      3.10.1
- Nitro Version:    2.9.4
- Package Manager:  pnpm@8.15.4
- Builder:          -
- User Config:      modules, experimental, css, colorMode, nitro, app, pwa, devtools, features, eslintConfig
- Runtime Modules:  @vueuse/nuxt@10.9.0, @unocss/nuxt@0.58.6, @pinia/nuxt@0.5.1, @nuxtjs/color-mode@3.3.2, @vite-pwa/nuxt@0.4.0, nuxt-module-eslint-config@0.0.2
- Build Modules:    -
------------------------------

### Reproduction

1. Create a Nuxt app.
2. Add `server/api/test.ts`:
```ts
import { createSourceFile, ScriptTarget } from "typescript";
export default defineEventHandler(() => {
  const code = "const hello = 'world';";
  const sourcefile = createSourceFile("test.ts", code, ScriptTarget.Latest);
  return code;
});
```
3. `npm i` and `npm run dev`

### Describe the bug

When starting dev server, got `JavaScript heap out of memory`.

### Logs

```shell-script
<--- Last few GCs --->

[18952:00000229CC0A1270]    46880 ms: Mark-Compact (reduce) 2037.8 (2082.8) -> 2037.5 (2083.6) MB, 742.95 / 0.00 ms  (average mu = 0.327, current mu = 0.299) allocation failure; GC in old space requested


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 00007FF6251A71AB node::SetCppgcReference+16075
 2: 00007FF62511DCC6 v8::base::CPU::num_virtual_address_bits+79190
 3: 00007FF62511FED5 v8::base::CPU::num_virtual_address_bits+87909
 4: 00007FF625B8F061 v8::Isolate::ReportExternalAllocationLimitReached+65
 5: 00007FF625B787F8 v8::Function::Experimental_IsNopFunction+1336
 6: 00007FF6259DA120 v8::Platform::SystemClockTimeMillis+659328
 7: 00007FF6259D71A8 v8::Platform::SystemClockTimeMillis+647176
 8: 00007FF6259EC4BA v8::Platform::SystemClockTimeMillis+733978
 9: 00007FF6259ECD37 v8::Platform::SystemClockTimeMillis+736151
10: 00007FF6259FB62F v8::Platform::SystemClockTimeMillis+795791
11: 00007FF6256BBACF v8::CodeEvent::GetFunctionName+116495
12: 00000229ED95AAFA
 ELIFECYCLE  Command failed with exit code 134.
```

**Comment by danielroe** [comment]
Would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏

(Having said that, I'm not convinced this is a Nitro _bug_ either.)
