### ISSUE TITLE
SEO Metadata not updated in source code with nuxt 3

### ISSUE THREAD

**Issue by aquerol2** [nuxt/nuxt#26335]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.19.0
- Nuxt Version:     3.11.0
- CLI Version:      3.10.1
- Nitro Version:    2.9.4
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      ssr, devtools, app, vite, css, modules, hooks, build, runtimeConfig
- Runtime Modules:  @pinia/nuxt@0.4.11, nuxt-icons@3.2.1, ()
- Build Modules:    -
------------------------------

### Reproduction

N/A

### Describe the bug

Hi,

I want to have some SEO metadata on my nuxt 3 project. I have the following nuxt.config.ts :

```
export default defineNuxtConfig({
  ssr: false,
  devtools: { enabled: true },
  app: {
    head: {
      title: 'Connexion...',
      meta: [
        { charset: 'utf-8' },
        { name: 'viewport', content: 'width=device-width, initial-scale=1' },
        { hid: 'description', name: 'description', content: 'mywebsite' },
        { hid: 'og:title', name: 'og:title', content: 'test title' },
        { hid: 'og:description', name: 'og:description', content: 'my website' },
        { hid: 'og:type', name: 'og:type', content: 'website' },
        { hid: 'og:url', name: 'og:url', content: '/' },
        { hid: 'og:image', name: 'og:image', content: '/' },
        { hid: 'og:site_name', name: 'og:site_name', content: 'test title' },
        { hid: 'twitter:card', name: 'twitter:card', content: 'summary_large_image' },
        { hid: 'twitter:site', name: 'twitter:site', content: '@test' },
        { hid: 'twitter:title', name: 'twitter:title', content: 'test title' },
        { hid: 'twitter:description', name: 'twitter:description', content: 'my website' },
        { hid: 'twitter:creator', name: 'twitter:creator', content: '@test' },
        { hid: 'og:image', name: 'og:image', content: '/' },

      ],
      link: [
        { rel: 'icon', type: 'image/png', href: '/favicon.png' }
      ],
      script: [
        ...
      ]
    },
  },
```

So I have some metadata in my source code (on all pages) that are fixed. I can see them when I select "view source code" on chrome. What I want is for each page to have their own metadata, and I want the source code to change accordingly.

For example, in Home.vue
```
<template>
 <div>
   Hello world
 </div>
</template>

<script> 
export default defineNuxtComponent({
 setup() {
  useSeoMeta({
    title: 'My Amazing Site',
    ogTitle: 'My Amazing Site',
    description: 'This is my amazing site, let me tell you all about it.',
    ogDescription: 'This is my amazing site, let me tell you all about it.',
    ogImage: 'https://example.com/image.png',
    twitterCard: 'summary_large_image',
 })
}

})
</script>
```

I would expect the title, description, and so on... to change, and it does but not in the source code of the page. On the source code it's still the default metadata that i definied in nuxt.config.ts I have tried to use useHead but it's the same result.

**Comment by manniL** [comment]
When not using SSR (`ssr: false`), the values won't change in the HTML as your code only runs on the client side.

**Comment by aquerol2** [comment]
It was working fine in nuxt 2, it's just not the case anymore in nuxt 3 ?

**Comment by manniL** [comment]
The behavior should be similar in Nuxt 2.
While the data *will* be updated in the client (in Nuxt 2 and Nuxt 3), crawlers won't be able to get the data from the initial HTML, so for example og tags won't be taken into account.

**Comment by withgogo** [comment]
> The behavior should be similar in Nuxt 2. While the data _will_ be updated in the client (in Nuxt 2 and Nuxt 3), crawlers won't be able to get the data from the initial HTML, so for example og tags won't be taken into account.

I have exactly the same problem as yours. I got data from requests and assigned by useSeoMeta. the FB or LINE can not get the og:image & og:title. It seems dynamic seo meta is not working, or crawlers can only get the static data.

**Comment by manniL** [comment]
> > The behavior should be similar in Nuxt 2. While the data _will_ be updated in the client (in Nuxt 2 and Nuxt 3), crawlers won't be able to get the data from the initial HTML, so for example og tags won't be taken into account.
> 
> I have exactly the same problem as yours. I got data from requests and assigned by useSeoMeta. the FB or LINE can not get the og:image & og:title. It seems dynamic seo meta is not working, or crawlers can only get the static data.

Nothing is broken here. This is a downside of not using SSR.
