### ISSUE TITLE
Inconsistency in Nuxt's behavior with and without server: useRoute

### ISSUE THREAD

**Issue by gitFoxCode** [nuxt/nuxt#26331]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.11.0
- Nuxt Version:     3.11.0
- CLI Version:      3.10.1
- Nitro Version:    2.9.4
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-xwmppm?file=pages%2Findex.vue

### Describe the bug

`<button :class="{ 'active': activeTab === 0 }">Button 0</button>` - class active is working as expected with `npm run dev`, but `npm run generate` and `npm run preview` with `localhost:3000?active=0` its not working  

### Additional context

Code like this:
```
const route = useRoute()
activeTab.value = route.query?.active
```
Class change its not working with prerender static website

**Comment by danielroe** [comment]
The issue here is that when prerendered, there was no query string. But there is in production, which means there is a hydration error (what was rendered doesn't match what you expect the client to render).

Instead, you should update activeTab in onMounted.
