### ISSUE TITLE
[WARN] Sourcemap ... pointing to missing source files

### ISSUE THREAD

**Issue by fcristaldi** [nuxt/nuxt#26332]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.9.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, extends, modules, unocss
- Runtime Modules:  @unocss/nuxt@0.58.6
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-mxdo6f?file=nuxt.config.ts

### Describe the bug

I've noticed that when using Unocss on global components, a WARNING message appears upon running the application.
<img width="785" alt="Screenshot 2024-03-18 at 11 13 19" src="https://github.com/nuxt/nuxt/assets/161730840/e169783f-623c-4e93-ae48-a4fd65ba3292">

If we disable unocss transformers or remove the group class within the external component, the warning disappears.

cc: @danielroe

**Comment by danielroe** [comment]
From the description, this sounds like it might be an issue with unocss not emitting sourcemaps? (cc: @antfu)

**Comment by danielroe** [comment]
Let's track there. Of course, if it ends up being a Nuxt issue, we can reopen.
