### ISSUE TITLE
Console log in nitro plugin breaks the server

### ISSUE THREAD

**Issue by Xenossolitarius** [nuxt/nuxt#26330]
### Environment

Latest Nuxt 3.11.0

### Reproduction

![image](https://github.com/nuxt/nuxt/assets/26404060/fbdcfcd1-8a01-4482-a08c-52734bc3d962)

### Describe the bug

Using console log of any type breaks server in server plugins

**Comment by fabianwohlfart** [comment]
Should be the same as mine https://github.com/nuxt/nuxt/issues/26329

**Comment by danielroe** [comment]
Yes, this is already resolved and should be released in a patch later today.
