### ISSUE TITLE
3.11.0 throws error about missing joinRelativeURL

### ISSUE THREAD

**Issue by MickL** [nuxt/nuxt#26345]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v21.6.1
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  bun@1.0.29
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Sorry for not providing a production repo. I already spend SO much time in the last 4-6 weeks debugging and providing reproduction repos for bugs in latest Nuxt and Nuxt UI versions. [This one](https://github.com/nuxt/nuxt/issues/25724) took me forever.

### Describe the bug

After updating to 3.11.0 I get the following error in the console on all pages:

```
Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.cache/vite/client/deps/ufo.js?v=f3153824' does not provide an export named 'joinRelativeURL' (at paths.mjs:1:10)
```

### Additional context

<img width="630" alt="313720052-26481557-8286-45de-897c-81ce6d218867" src="https://github.com/nuxt/nuxt/assets/5103210/2300fe6f-5205-4337-b258-c8e068264bb6">

**Comment by pi0** [comment]
Hi. Can you please try removing `node_modules`, lockfile and then `npx nuxi upgrade --force`?

If the issue persists, please share the output of `pnpm why ufo` / `npm why ufo` (i see you are using `bun`, then try other package manager or `node_modules/ufo/package.json` for installed version)

**Comment by danielroe** [comment]
As @pi0 comments, this will occur if you have multiple versions of `ufo`, and a version of `ufo` that is not the one required by Nuxt is the one hoisted in your project.

Deduping or manually specifying the latest version of `ufo` should resolve it.

**Comment by MickL** [comment]
I removed node_modules and lock file multiple times before I opened this issue. Now it works, I dont know, very frustrating.

**Comment by pi0** [comment]
Good to hear it is working now.

Just some guesses why you kept having issues:

- If you kept `node_modules`, vite caches results into `node_modules/.cache`
- Bun package manager might have been using a cached/older version of `ufo`.

**Comment by MickL** [comment]
Maybe the latter. In any case thanks for the quick responses!
