### ISSUE TITLE
useFetch do not respect timeout when proxied by a routeRule

### ISSUE THREAD

**Issue by marcelobotega** [nuxt/nuxt#26346]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.11.1`
- Nuxt Version:     `3.11.0`
- CLI Version:      `3.10.1`
- Nitro Version:    `2.9.4`
- Package Manager:  `pnpm@8.15.1`
- Builder:          `-`
- User Config:      `devtools`, `routeRules`, `experimental`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/marcelobotega/route-rules-no-timeout

### Describe the bug

When using `routeRules` as a proxy the composable `useFetch` do not respect the timeout. 

I created the following `routeRule`: 
```
  routeRules: {
    '/delayed-response': {proxy: 'http://localhost:3001/delayed-response'},
  },
```
And when I call it with `useFetch`: 
```
 await useFetch('/delayed-response', {
  timeout: 1000,
});
```

The 1 second timeout do not work.

### Additional context

I also tried using the experimental defaults on `nuxt.config.ts` but that do not work either.
```
  experimental: {
    defaults: {
      useFetch: {
        timeout: 500,
      }
    }
  }
```

**Comment by danielroe** [comment]
This is likely because on the server we are using a 'local call' which does not have a way to cancel requests.

We can track upstream in https://github.com/unjs/unenv/issues/153.

**Comment by marcelobotega** [comment]
Hi @danielroe, I was checking the issue and looking at the implementations and I noticed something. 
The [nitro implementation](https://github.com/unjs/nitro/blob/d2881a8a5079a9f3e22224eba5ea5dda5fcc9b7c/src/runtime/app.ts#L111) is using the localFetch on the `createRouteRulesHandler` if `$fetch` (or `$fetch.raw`) were utilized instead, the [proxyRequest](https://github.com/unjs/nitro/blob/d2881a8a5079a9f3e22224eba5ea5dda5fcc9b7c/src/runtime/route-rules.ts#L59C14-L59C26) might benefit from the abortSignal from `ofetch`.
If I'm looking on the right place, maybe this change would fix the issue ? Assuming that Nuxt is not doing a local call.

**Comment by danielroe** [comment]
I think the signal wouldn't travel all the way through right now. But that might be the kind of change to make.
