### ISSUE TITLE
v3.11.0 useFetch getCachedData triggers unexpected refetch on client and breaks site

### ISSUE THREAD

**Issue by katerlouis** [nuxt/nuxt#26349]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.19.1`
- Nuxt Version:     `3.11.0`
- CLI Version:      `3.10.1`
- Nitro Version:    `2.9.4`
- Package Manager:  `npm@10.2.4`
- Builder:          `-`
- User Config:      `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/katerlouis/nuxt311-get-cached-data-bug

### Describe the bug

When using `getCachedData()` like [explained here](https://youtu.be/aQPR0xn-MMk?t=252) by @manniL , the client does unexpectedly fetch data again AND breaks the site for me on refresh.

Apparently for a brief second `data` is `null`?

![image](https://github.com/nuxt/nuxt/assets/1983382/101d875a-ca2d-4f92-9179-b8aa63092cba)

### Additional context

The same happens when I do 

```js
getCachedData() {
  return null;
}
```

in that case I also would expect the client to NOT REFETCH, since the server already fetched something. Why fetch again then?

**Comment by manniL** [comment]
When returning `null` or `undefined`, `getCachedData` handles it as "no cache hit" and it will refetch the data.
