### ISSUE TITLE
Nuxt v3.11.0 CSS background images try to load from _nuxt causing 404 

### ISSUE THREAD

**Issue by ejg** [nuxt/nuxt#26352]
### Environment

"nuxt": "^3.11.0" 

### Reproduction

https://github.com/ejg/nuxt311CSSbackground

### Describe the bug

`npm run dev`
File in the pages folder has a CSS background images that is in the `public/images` folder  
Nuxt tries to load  the image from `/_nuxt/images` resulting in a 404 Not Found.  
The image eventually is loaded correctly from `/images`.

<img width="988" alt="Screenshot 2024-03-18 at 1 48 49 PM" src="https://github.com/nuxt/nuxt/assets/213104/23f04b9b-9a55-4b83-a6d3-4bf2cb22d0b4">

This is only in the Dev environment. The problem does not occur in the static site after build.

**Comment by danielroe** [comment]
To access an image in `~/public` you should use an absolute path (= `/images/fl.png`) and not a relative one.
