### ISSUE TITLE
Nested routes is not highlighting in Nuxt-Link

### ISSUE THREAD

**Issue by Venegrad** [nuxt/nuxt#26364]
### Environment

Operating System: Darwin
Node Version: v18.16.0
Nuxt Version: 3.10.3
CLI Version: 3.10.1
Nitro Version: 2.9.1
Package Manager: yarn@1.22.19
Builder: -
User Config: alias, runtimeConfig, modules, i18n, app, css, vite
Runtime Modules: @nuxtjs/i18n@8.1.1
Build Modules: -

### Reproduction

https://stackblitz.com/edit/github-9jte8n?file=layouts%2Fdefault.vue

### Describe the bug

In previous versions, Nuxtjs highlighted nested routes. Now it doesn't do it, I think it's a bug.

I created a gameshop folder, and inside it is a subfolder route.
It turns out that when I go to `/gameshop/userid`, the nuxt-link that has the `/gameshop` link doesn't get the highlighting class. Nuxt2 previously highlighted nested routers.

**Comment by danielroe** [comment]
This is a change in the latest vue-router: https://router.vuejs.org/guide/migration/#removal-of-the-exact-prop-in-router-link
