### ISSUE TITLE
Browser Console Warning: definePageMeta() is a compiler-hint helper that is only usable inside the script block of a single file component which is also a page.

### ISSUE THREAD

**Issue by XioDone** [nuxt/nuxt#26377]
### Environment

Nuxt Version: 3.11.1

### Reproduction

https://stackblitz.com/edit/nuxt-starter-yd5hhb?file=pages%2Findex.client.vue

### Describe the bug

When defining Client-Only Pages, Received this warning.
`definePageMeta() is a compiler-hint helper that is only usable inside the script block of a single file component which is also a page. Its arguments should be compiled away and passing it at runtime has no effect.`

**Comment by moshetanzer** [comment]
@danielroe seem to be getting this again on v4
