### ISSUE TITLE
`navigateTo` `open` disables server side redirect

### ISSUE THREAD

**Issue by warflash** [nuxt/nuxt#26390]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.11.1
- CLI Version:      3.11.0
- Nitro Version:    2.9.4
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-f7dgow?file=app.vue,pages%2Findex.vue,pages%2Fredirect.vue,middleware%2Ftest.ts

### Describe the bug

Setting open
```ts
export default defineNuxtRouteMiddleware((to) => {
  return navigateTo('/redirect', {
    open: {
      target: '_self',
    },
    redirectCode: 302,
  });
});
 ```

as options in `navigateTo` forces client side execution of the navigate to, even if the middleware also runs on server.
[The docs mention the field is being ignored](https://nuxt.com/docs/api/utils/navigate-to#options-optional) which does not seem to be the case.

![image](https://github.com/nuxt/nuxt/assets/22006082/397a6be0-713e-415f-aa7c-21b7c234b7e7)
No 302 redirect is returned here

**Comment by manniL** [comment]
Created a PR for it. I wonder if it makes more sense to "ignore the field" and perform the request server-side *or* to "ignore the request" if the field is set on the server side and run it on the client-side as is.

WDYT @warflash?

**Comment by warflash** [comment]
Awesome!
To me the current actual behaviour felt highly unintuitive so I'd be leaning towards performing the request server side and ignoring the field there.
