### ISSUE TITLE
type of `default` option in `useFetch` is not correct

### ISSUE THREAD

**Issue by kingyue737** [nuxt/nuxt#26395]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.11.1
- CLI Version:      3.11.0
- Nitro Version:    2.9.4
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-fy9tv9

### Describe the bug

The following code has type error. The type of `default` option always requires `() => Ref<null> | null`, I can only assign the default value asserted as `any`.

```ts
const { data } = useFetch<{ bug: string }[]>('/', {
  default: [],
});
```

Secondly, the `data` returned by `useFetch` is always nullable even if I've set a non-null default value.
The following code raises type error because the type of data is `Ref<{ bug: string }[] | null>` instead of `Ref<{ bug: string }[]>`

```ts
data.value.push({ bug: 'bug' });
```

### Logs

```shell-script
> typecheck
> nuxt typecheck

ℹ Compiled plugins/client.mjs in 504.86ms                                            11:56:46 AM
ℹ Compiled types/plugins.d.ts in 511.66ms                                            11:56:46 AM
app.vue:3:3 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(request: NitroFetchRequest | Ref<NitroFetchRequest> | (() => NitroFetchRequest), opts?: UseFetchOptions<{ bug: string; }[], { bug: string; }[], KeysOf<...>, null, NitroFetchRequest, AvailableRouterMethod<...>> | undefined): AsyncData<...>', gave the following error.
    Type '{ bug: string; }[]' is not assignable to type '() => Ref<null> | null'.
      Type '{ bug: string; }[]' provides no match for the signature '(): Ref<null> | null'.
  Overload 2 of 2, '(request: NitroFetchRequest | Ref<NitroFetchRequest> | (() => NitroFetchRequest), opts?: UseFetchOptions<{ bug: string; }[], { bug: string; }[], KeysOf<...>, { ...; }[], NitroFetchRequest, AvailableRouterMethod<...>> | undefined): AsyncData<...>', gave the following error.
    Type '{ bug: string; }[]' is not assignable to type '() => { bug: string; }[] | Ref<{ bug: string; }[]>'.
      Type '{ bug: string; }[]' provides no match for the signature '(): { bug: string; }[] | Ref<{ bug: string; }[]>'.

3 
  


app.vue:5:1 - error TS18047: 'data.value' is possibly 'null'.

5 
  

app.vue:5:12 - error TS2339: Property 'push' does not exist on type 'NonNullable<PickFrom<_ResT, KeysOf<DataT>>>'.

5 
  


Found 3 errors in the same file, starting at: app.vue:3


[11:56:50 AM]  ERROR  Command failed with exit code 2: /home/projects/nuxt-starter-fy9tv9/node_modules/vue-tsc/bin/vue-tsc.js --noEmit

  at makeError (node_modules/nuxi/dist/chunks/index3.mjs:1292:11)
  at handlePromise (node_modules/nuxi/dist/chunks/index3.mjs:2530:26)
  at async Object.run (node_modules/nuxi/dist/chunks/typecheck.mjs:91:7)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.892d3e71.mjs:1678:16)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.892d3e71.mjs:1669:11)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.892d3e71.mjs:1807:7) 



[11:56:50 AM]  ERROR  Command failed with exit code 2: /home/projects/nuxt-starter-fy9tv9/node_modules/vue-tsc/bin/vue-tsc.js --noEmit

```
```

**Comment by aaharu** [comment]
I made `default` to function and it worked!

```ts
const { data } = useFetch<{ bug: string }[]>('/', {
  default: () => [],
});
data.value.push({ bug: 'bug' });
```

**Comment by kingyue737** [comment]
@aaharu good workaround!

**Comment by kingyue737** [comment]
@aaharu not work. Still error: https://stackblitz.com/edit/nuxt-starter-jpexsn

**Comment by kingyue737** [comment]
Thanks for the workaround! But I found this does not work for custom useFetch in the official example:
https://nuxt.com/docs/examples/advanced/use-custom-fetch-composable

**Comment by aaharu** [comment]
I think that this is not a bug. Although the error output of `typecheck` is not always easy to understand.

The documentation also states that it's a function.
https://nuxt.com/docs/api/composables/use-fetch
> default: a factory function to set the default value of the data

For the following implementation, `default` is expected to be a function.
https://github.com/nuxt/nuxt/blob/v3.11.1/packages/nuxt/src/app/composables/asyncData.ts#L313

**Comment by kingyue737** [comment]
I think you are right. Then I will track the issue of the example in https://github.com/Atinux/atinotes/issues/6
Closing
