### ISSUE TITLE
srcDir in extends config on dev causes cannot be imported directly error in console

### ISSUE THREAD

**Issue by daniluk4000** [nuxt/nuxt#26401]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.11.1
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.4
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, extends
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/daniluk4000/nuxt-src-dir-bug

### Describe the bug

We are using shared config for our dozens of projects. On every single one weird error occures when running dev:

`nuxt, nuxt3 or nuxt-nightly cannot be imported directly. Instead, import runtime Nuxt composables from #app or #imports. [importing nuxt from src/index.html]`

Turned out it happens because of srcDir in that shared config. When you move it from extendable config to main errors disappears.

I don't know if it affects anything, also I don't see this error when running build. It's just I noticed that on nearly empty project and got interested to find out why it occurs.

**Comment by daniluk4000** [comment]
Maybe it's a conflict between this:
- https://github.com/nuxt/nuxt/blob/6f2e7a8b2327695048a9c8cf0090b4e6ecee629c/packages/nuxt/src/core/nuxt.ts#L134
- https://github.com/nuxt/nuxt/blob/6f2e7a8b2327695048a9c8cf0090b4e6ecee629c/packages/vite/src/vite.ts#L162

Also since second code runs on dev only it can explain that

**Comment by danielroe** [comment]
Nice debugging.
