### ISSUE TITLE
Strange behavior when using NuxtLink

### ISSUE THREAD

**Issue by AndreiMaelstrom** [nuxt/nuxt#26409]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.18.2`
- Nuxt Version:     `3.11.1`
- CLI Version:      `3.11.0`
- Nitro Version:    `2.9.4`
- Package Manager:  `yarn@1.22.19`
- Builder:          `-`
- User Config:      `ssr`, `pages`, `debug`, `typescript`, `modules`, `devtools`, `runtimeConfig`, `colorMode`, `tailwindcss`, `purgecss`, `eslint`, `i18n`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.11.4`, `nuxt-purgecss@2.0.0`, `nuxt-headlessui@1.1.5`, `@nuxtjs/i18n@8.2.0`, `@nuxtjs/color-mode@3.3.3`, `nuxt-icon@0.6.9`, `@nuxt/image@1.4.0`, `@nuxt/content@2.12.1`, `vue3-carousel-nuxt@1.1.0`, `@nuxtjs/device@3.1.1`
- Build Modules:    `-`

### Reproduction

- Start nuxt app using yarn dev (SSR mode)
- Manually/directly browse to a page (using url) **(1)**
- Navigating to another page through a NuxtLink element **(2)**
- Navigating back to the initial page through a NuxtLink element **(3)**

### Describe the bug

When the page at **(1)** is opened, everything is rendered correctly. After browsing to another page **(2)** and then back to the initial page **(3)** the initial page no longer has any content (like the previous state disappeared). The content/state is visible in the nuxt devtool widget, yet it is not rendered, and the client reports that the data object in the initial page **(1)** is undefined.  No errors / warning / debugging messages are shown anywhere (neither in the client or the server).

### Additional context

The data object in the page described at **(1)** looks like this:
```
let categories = await findAll<ICategory>('categories', {
  locale: languageToLocale(locale.value),
  populate: '*',
  requestKey: 'static-content-categories',
});
```

The object is then used in the `<template>` block to display some fields, using plain elements.

The findAll() function simply calls function queryApi() that internally uses useAsyncData(). The findAll/queryApi functions are part of a custom composable (added under composables/ directory).

```
async function queryApi (entity: string, requestParams: IApiRequestParams) {
    const {
      data,
      pending
    } = await useAsyncData<IApiResponse>(
      requestParams.requestKey,
      async () => $fetch(makeApiEndpointQueryUrl(entity, requestParams), {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/json',
        },
      })
    );

    return {
      data: data.value?.data ?? undefined,
      meta: data.value?.meta ?? undefined,
    };
  }
```

Additional methods used in queryApi (part of the same composable):

 ```
function makeApiEndpointUrl (entity: string): string {
    return useRuntimeConfig().api.url + '/api/' + entity;
  }

  function makeApiEndpointQueryUrl (entity: string, requestParams: IApiRequestParams): string {
    let query = qs.stringify(requestParams, { encodeValuesOnly: true });
    return makeApiEndpointUrl(entity) + '?' + query;
  }
```

The interfaces presented in the example are exported from types/index.d.ts.

All in all it seems that things are starting to break after the first render (coming from the server), when the app goes in SPA mode. If I use `<a>` tags instead of `<NuxtLink>` everything works correctly, the only downside being that the app no longer offers the SPA feeling (as pages get refreshed).

**Comment by mitarkrivokapic** [comment]
I think the problem is in your runtime config, on the client side you can only access public env variables from your runtimeConfig object, it should look something like this:

```
function makeApiEndpointUrl (entity: string): string {
   return useRuntimeConfig().public.api.url + '/api/' + entity;
 }
```
Or if you don't want to expose your API address you should migrate all your API calls into /server folder and you will have access to this secret env.

PS.
I am giving you this info just on top of my head.
If you make some reproduction somewhere I would try it. 😃

**Comment by AndreiMaelstrom** [comment]
That's exactly what went wrong - thanks for helping me figure it out. The strange thing is that this is silently failing and there's nothing shouting at you when you go down this route. Not sure if something could be done for this (i.e. at least a undefined error when trying to use a non-public config element in the client context), so that at least people can spot it without having it crack silently.
