### ISSUE TITLE
Potential memory leak on fresh nuxt 3 install

### ISSUE THREAD

**Issue by Bcavez** [nuxt/nuxt#26405]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.11.1
- Nuxt Version:     3.11.1
- CLI Version:      3.11.0
- Nitro Version:    2.9.4
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

1) Do a fresh install of nuxt.
2) Add this file to the plugins folder

```
process.lastRequestMemoryUsed = -1;
process.requestsServed = 0;

export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.hook('app:rendered', (renderContext) => {
        // Force Garbage Collection for consistency, more about that later
        global.gc();

        process.requestsServed++;

        // Get currently used memory in MB
        const currentMemory = process.memoryUsage().heapUsed / 1024 / 1024;

        let memoryUsed;
        if (process.lastRequestMemoryUsed > 0) {
            memoryUsed = currentMemory - process.lastRequestMemoryUsed;
        } else {
            memoryUsed = currentMemory;
        }
        process.lastRequestMemoryUsed = currentMemory;

        console.log(`===== REQUEST COMPLETED (${process.requestsServed}) =====`);
        console.log('Unreleased memory used in last request: ', memoryUsed);
        console.log('Total: ', currentMemory);
    })
})
```

3) npm run build
4) node --expose-gc .output/server/index.mjs
5) observe the heapused go up slowly but surely.

### Describe the bug

I'm getting some apparent memory leak in my application. The heap use goes up consistently for every new request until it reaches the maximum and crashes.
I've tried to do some debugging using this article https://medium.com/@oliverolmaru/memory-leak-in-ssr-nuxt-js-if-everything-else-fails-1a28e6c2e360
While doing this, no matter how many parts of my application I removed, the leak was still present.

So I tried going the other way and started with the basic installation of nuxt. That's where I noticed that heap usage was also going up consistently per request and never going down.
I have tried with node 18.18.0 and node 20.11.1

Here is a excerpt of the logs generated showing that after 1000 request to localhost:3000 the heap usage went up by 700kb.

===== REQUEST COMPLETED (20) =====
Unreleased memory used in last request:  0.0090484619140625
Total:  10.3126220703125
===== REQUEST COMPLETED (1000) =====
Unreleased memory used in last request:  0.00049591064453125
Total:  11.064949035644531

I am wondering also if maybe I am doing something wrong when testing this ?

**Comment by geminigeek** [comment]
possibly, oftech need to be fixed opened an issue last month https://github.com/unjs/ofetch/issues/361  , i was using ofetch on a large scale crawling , ended up using got because of memory issue

**Comment by Bcavez** [comment]
> Have been having same issue since Nuxt 3.11, did you test in earlier versions? Seemed like it was only in dev though.. and editing a backend fetch api while dev server running would reach heap and crash instantly.. hmm

But on the fresh nuxt install, the app doesn't fetch anything right ? It just displays the static <NuxtWelcome> component.

Also occurs on 3.9

**Comment by Bcavez** [comment]
I think this can be closed then. It is probably incorrect setup of the test on my part.
In the meantime we have found the cause of our issues (With urql, leak happens in the exchanges, cacheexchange and mapexchange, when there are graphql errors)

**Comment by Bcavez** [comment]
I think this can be closed then. It is probably incorrect setup of the test on my part.
In the meantime we have found the cause of our issues (With urql, leak happens in the exchanges, cacheexchange and mapexchange, when there are graphql errors)

**Comment by Max199909** [comment]
I encountered the same problem. How can I monitor memory leaks in the dev and test environments in a timely manner?

**Comment by Max199909** [comment]
> I think this can be closed then. It is probably incorrect setup of the test on my part.我认为这可以关闭。我的测试设置可能不正确。 In the meantime we have found the cause of our issues (With urql, leak happens in the exchanges, cacheexchange and mapexchange, when there are graphql errors) 与此同时，我们已经找到了问题的原因（使用 urql，当存在 graphql 错误时，泄漏发生在交换、cacheexchange 和 mapexchange 中）

I encountered the same problem. How can I monitor memory leaks in the dev and test environments in a timely manner?
