### ISSUE TITLE
HMR failure in tsx in setup

### ISSUE THREAD

**Issue by mark980828** [nuxt/nuxt#26417]
### Environment

Operating System: Windows_NT
- Node Version:     v20.11.0
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.4
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      ssr, extends, modules
- Runtime Modules:  @nuxt/ui@2.14.2
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-rft5cs?file=pages%2Findex.vue

### Describe the bug

When I modified the content of tsx in the setup, vite was not updated.

**Comment by mark980828** [comment]
There's no problem with vite building, but there's a problem with nuxt building

**Comment by danielroe** [comment]
This is likely caused by this plugin which we use to transform page metadata:

https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/pages/plugins/page-meta.ts

**Comment by danekslama** [comment]
I discovered the line causing the issue. I've recently decided to start contributing, but to be honest, I still feel pretty overwhelmed by everything and I'm unsure how to fix this specific issue. Do you have any tips on how to better navigate and understand the code?

   ```
   const scriptImport = imports.find(i => parseMacroQuery(i.specifier).type === 'script')
      if (scriptImport) {
        const reorderedQuery = rewriteQuery(scriptImport.specifier)
        // Avoid using JSON.stringify which can add extra escapes to paths with non-ASCII characters
        const quotedSpecifier = getQuotedSpecifier(scriptImport.code)?.replace(scriptImport.specifier, reorderedQuery) ?? JSON.stringify(reorderedQuery)
        s.overwrite(0, code.length, `export { default } from ${quotedSpecifier}`) // When you comment this line, it starts working
        return result()
      }
```
