### ISSUE TITLE
`undefined` returned from a server route isn't included in the resolved type when calling it using `$fetch`

### ISSUE THREAD

**Issue by DamianGlowala** [nuxt/nuxt#26411]
### Environment

n/a

### Reproduction

https://stackblitz.com/edit/github-2rvskw?file=server%2Fapi%2Ftest.ts

### Describe the bug

Having `undefined` returned from the server route and calling this route using `$fetch`, the return type does not include it. Hover over the `fn` in `middleware/test.ts` to see that `Promise<"test">` gets resolved instead of `Promise<"test" | undefined>`.

**Comment by danielroe** [comment]
This is likely an upstream issue with nitropack's `Simplify<Serialize<>>` type helpers; it's reproducible simply by referencing the nitro type.

![CleanShot 2024-03-21 at 12 52 58@2x](https://github.com/nuxt/nuxt/assets/28706372/ca762851-24b1-4748-a52c-3f77ad03177a)

```ts
import type { InternalApi } from 'nitropack'

export default defineNuxtRouteMiddleware(() => {
  const fn = $fetch("/api/test")
  type B = InternalApi['/api/test']['default']
})
```

Would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏

**Comment by DamianGlowala** [comment]
Upstream PR: https://github.com/unjs/nitro/pull/2286

**Comment by danielroe** [comment]
Thank you! ❤️ 

as there's a nitro issue you've linked, I think we can close this one in favour of it.
