### ISSUE TITLE
Using webpack-builder in Nuxt3, running nuxt dev The styles in the <style> tag are lost

### ISSUE THREAD

**Issue by li-jingxuan** [nuxt/nuxt#26423]
### Environment

development

### Reproduction

The warehouse address is temporarily unavailable.

### Describe the bug

Steps
  step 1:
  `npx nuxi@latest init test-project`
  step 2:
  Configure in nuxt.config.ts: builder: 'webpack'
  step 3:
  Modify the file App.vue: <div><NuxtPage /><div>
  step 4:
  Create directory: pages
  step 5:
  Add the file in the pages directory: index.vue
  ![image](https://github.com/nuxt/nuxt/assets/48175155/797cd85e-a587-4d9a-98bc-c75648231d01)

Results：
The style in the <style> tag of the index.vue file is invalid.
JS Error: Uncaught SyntaxError: Invalid or unexpected token.

### Additional context

Node: v18.17.0
Nuxt: v3.11.1
vue: v3.4.21

Tips: The problem only occurs in the development environment (cmd: nuxt dev)

**Comment by li-jingxuan** [comment]
@danielroe https://github.com/li-jingxuan/nuxt3-testing   It's reproduction

Thanks

**Comment by danielroe** [comment]
It seems to be working fine when your lockfile is refreshed: https://stackblitz.com/github/li-jingxuan/nuxt3-testing?file=package-lock.json.

**Comment by li-jingxuan** [comment]
> It seems to be working fine when your lockfile is refreshed: https://stackblitz.com/github/li-jingxuan/nuxt3-testing?file=package-lock.json.当您的锁定文件刷新时，它似乎工作正常：https://stackblitz.com/github/li-jingxuan/nuxt3-testing?file=package-lock.json。

But the CSS style is not taking effect. This is what I'm confused about. [https://stackblitz.com/github/li-jingxuan/nuxt3-testing?file=pages%2Findex.vue](url)

Please see the picture below:
![image](https://github.com/nuxt/nuxt/assets/48175155/bc3f19c0-9a00-4a4b-b19a-f562286dc4c8)

**Comment by danielroe** [comment]
This seems to be working fine with latest versions of everything - namely the styles: https://stackblitz.com/edit/github-rs6ccf?file=package.json,nuxt.config.ts,pages/index.vue

(There's another issue that's meant I've had to set `ssr: false` but this seems to be unrelated and we can track separately.)
