### ISSUE TITLE
Nuxt > 3.8.1 <client-only> showing blank with "builder: webpack"

### ISSUE THREAD

**Issue by guska8** [nuxt/nuxt#26437]
### Environment

```
------------------------------
- Operating System: Linux
- Node Version:     v18.19.1
- Nuxt Version:     3.8.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.4
- Package Manager:  npm@10.2.4
- Builder:          webpack
- User Config:      app, pages, modules, sourcemap, builder
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Reproduction

https://stackblitz.com/edit/github-mjshxb?file=nuxt.config.ts

![image](https://github.com/nuxt/nuxt/assets/25177050/d032256b-8641-4490-9948-a992a636acb3)

### Describe the bug

While trying to upgrade from nuxt 3.8.1 to 3.11.1 i discovered that `<client-only>` tag and  builder 'webpack' on nuxt.config.js it not working

If i comment builder line it works like before

### Logs

```shell-script
Uncaught SyntaxError: Invalid or unexpected token (at vendors-node_modules_webpack-hot-middleware_client_js_reload_true_timeout_30000_path_2F__webp-648d94.js:73:6)
```
```

**Comment by guska8** [comment]
I works correctly with 

```
  "nuxt": "3.8.1",
  "@nuxt/webpack-builder": "3.8.1"
```

and `builder: 'webpack'`

**Comment by huang-julien** [comment]
I can't reproduce the issue locally, can you try to refresh your lock and node module ?

**Comment by guska8** [comment]
> I can't reproduce the issue locally, can you try to refresh your lock and node module ?

Tried that many times, even on brand new projects the error occurs either locally or like stackblitz

**Comment by danielroe** [comment]
let's track in https://github.com/unjs/nitro/issues/2541.
