### ISSUE TITLE
context.outputFileSystem.lstat is not a function

### ISSUE THREAD

**Issue by mark980828** [nuxt/nuxt#26435]
### Environment

System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.3 - /usr/local/bin/pnpm
  npmPackages:
    nuxt: ^2.17.3 => 2.17.3

### Reproduction

https://stackblitz.com/edit/nuxt-starter-vi9px5?file=pages%2Findex.vue

### Describe the bug

This issue is like a version issue with "webpack-dev-middleware".

### Logs

```shell-script
ERROR  context.outputFileSystem.lstat is not a function

  at size (node_modules/webpack-dev-middleware/dist/middleware.js:157:36)
  at new Promise (<anonymous>)
  at processRequest (node_modules/webpack-dev-middleware/dist/middleware.js:155:28)
  at ready (node_modules/webpack-dev-middleware/dist/utils/ready.js:17:5)
  at Object.middleware (node_modules/webpack-dev-middleware/dist/middleware.js:69:5)
  at eval (node_modules/pify/index.js:33:11)
  at new Promise (<anonymous>)
  at Object.eval (node_modules/pify/index.js:6:9)
  at Object.apply (node_modules/pify/index.js:80:20)
  at WebpackBundler.middleware (node_modules/@nuxt/webpack/dist/webpack.js:1917:37)
```

**Comment by danielroe** [comment]
Likely latest patch in webpack-dev-middleware causes this - you can try pinning previous version.

https://github.com/nuxt/nuxt/pull/26427 does highlight some type changes with our implementation of mfs and we likely need to update.

**Comment by mark980828** [comment]
> Likely latest patch in webpack-dev-middleware causes this - you can try pinning previous version.

Yes, it can run now.
"resolutions": {
    "webpack-dev-middleware": "5.0.0"
  }

**Comment by bhrutledge** [comment]
Duplicate of https://github.com/nuxt/nuxt/issues/20564?

**Comment by mark980828** [comment]
> Duplicate of #20564?

yeah

**Comment by manniL** [comment]
Closing in favor of https://github.com/nuxt/nuxt/issues/20564

**Comment by mark980828** [comment]
> ~Closing in favor of #20564~ Ah well, that was closed already 🙈

But this issue reappeared in nuxt@2.17.3.

**Comment by manniL** [comment]
Yeah, as Daniel mentioned, it is because of the subdependency and pinning should be sufficient. we can consider pinning the package to a patch version too if the bug won't be fixed soon

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by mark980828** [comment]
> If it's a critical or security issue

it's a critical issue.
