### ISSUE TITLE
  3.11.1 Pinia not working

### ISSUE THREAD

**Issue by gllinzbk1** [nuxt/nuxt#26456]
### Environment

  "dependencies": {
    "@pinia/nuxt": "^0.5.1",
    "axios": "^1.6.8",
    "lodash": "^4.17.21",
    "nuxt": "^3.11.1",
    "nuxt-lodash": "^2.5.3",
    "pinia": "^2.1.7",
    "vue": "^3.4.21",
    "vue-router": "^4.3.0"
  }

export default defineNuxtConfig({
  devtools: { enabled: true },
  
  modules: [
   
   '@pinia/nuxt'
  ],

  pinia: {
    autoImports: ['defineStore', 'acceptHMRUpdate', 'storeToRefs', 'mapStores', 'getActivePinia','usePinia'],
   // storesDirs: ['./stores/**'],
  },
})

Pinia auto imports invalid

### Reproduction

https://github.com/gllinzbk1/nuxt3.111.git

### Describe the bug

![图片](https://github.com/nuxt/nuxt/assets/115514156/843ffbd7-ae07-4ad6-baaf-b5c6e4af22ac)

**Comment by MustafaM257** [comment]
To begin, it's important to note that `autoImports` are not supported by Pinia in `nuxt.config.ts`. Therefore, it's recommended to remove it from your configuration.
You can check : `imports: {
    dirs: ['...']
  }`

Next, I restructured your code to align with a format similar to `script setup`. Pinia offers another syntax to define stores, akin to the Vue Composition API's `setup` function. You can achieve this by passing in a function that defines reactive properties and methods, returning an object containing the properties and methods you wish to expose.
```
import { defineStore } from "pinia";
export const useNewsLetterStore = defineStore("news-letter", () => {
  const products = ref([]);
  const init = (pdata) => {
    console.log("storeInitDataLength", pdata, pdata?.productList);
    products.value = pdata?.productList ?? [];

    return products;
  };

  return {
    products,
    init,
  };
});

```
But surely, you can stick to your syntax too, but I find this to be more   clear as I push for simplicity in my code

For detailed implementation guidance, refer to the official Pinia documentation for Nuxt [here](https://pinia.vuejs.org/ssr/nuxt.html).

Moving forward, it's essential to update the way you import your store in `App.vue`, leveraging auto import functionality. This ensures that your methods are properly called within the context of your application.
If you want to read the store, you should get your states directly, as you correctly do with the second console log, that will work now `console.log(storeCounter.validProperty)`;
```
<script setup>
const productStore = useNewsLetterStore();
console.log("1111111", productStore.products);
if (productStore.products === undefined || productStore.products.length === 0) {
  const data = { productList: "123" };
  console.log("222222222222222", data);
  productStore.init(data);
  console.log("News", productStore.products);
}
</script>
```

And after that it works! 



### NOTE : I saw you importing axios, just wanted to let you know:
### Axios module supports Nuxt 2. Nuxt 3 users can use the new isomorphic `fetch API`

I hope this guidance proves helpful in resolving your issue.

**Comment by selemondev** [comment]
Hey @gllinzbk1, just an addition to what @MustafaM257 has said.

1. You don't need to import  `defineStore()`, `usePinia()`, `storeToRefs()` and `acceptHMRUpdate()`. The `@pinia/nuxt` module automatically imports them for you.

**Comment by gllinzbk1** [comment]
Another issue is that there is a problem when refreshing the page
![图片](https://github.com/nuxt/nuxt/assets/115514156/b38a3234-8161-4743-8161-f14a2540de97)

**Comment by gllinzbk1** [comment]
console.log('News',NewsListtore)  500 err

console.log('News',NewsListtore.value)  normal
but nuxt3.7.4.
console.log('News',NewsListtore)  normal
