### ISSUE TITLE
Add ability to prerender pages without including them in routes

### ISSUE THREAD

**Issue by RomanSkrypnik** [nuxt/nuxt#26450]
### Describe the feature

It could be useful to have an ability to prerender pages without including them in routes ( just storing their prerenders in public folder )

For example, I working on seo-optimization (e.g. Google-Lighthouse) of a project and I need to return prerendered html from Nitro Server **without changing URL** of entered page

Currently, it's possible to return html from Nitro server but you will get redirected to prerendered route page with changing URL

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by RyanClementsHax** [comment]
Is your feature request that you want the prerenderer to implicitly crawl a directory without having to specify config like this?

```ts
export default defineNuxtConfig({
  devtools: { enabled: true },
  nitro: {
    prerender: {
      routes: [
        /**
          You don't want to add anything here,
          but you want it to crawl something like 'public/prerendered'
        */
      ],
    },
  },
});
```

> Currently, it's possible to return html from Nitro server but you will get redirected to prerendered route page with changing URL

What do you mean by this?

**Comment by danielroe** [comment]
Closing as it's not clear what the feature request is here.
