### ISSUE TITLE
Template installation error

### ISSUE THREAD

**Issue by jw-star** [nuxt/nuxt#26457]
### Environment

mac book

### Reproduction

dev

### Describe the bug

 % npx nuxi@latest init  xxx

[13:33:00]  ERROR  Error: Failed to download template from registry: Failed to download https://raw.githubusercontent.com/nuxt/starter/templates/templates/v3.json: TypeError: fetch failed

**Comment by MustafaM257** [comment]
Hello there,

I noticed the issue you're experiencing and I believe it might be related to your location.
To potentially resolve this issue, I suggest checking out this link: [Link to Potential Fixes](https://github.com/nuxt/cli/issues/198). It contains several solutions that have worked for others facing similar issues.

Please try these solutions, and if none of them work for you, feel free to reach out for further assistance. and let me know if it works for you

Good luck!

**Comment by warflash** [comment]
Also see: https://stackoverflow.com/questions/74283819/error-while-creating-nuxt3-project-failed-to-download-template-from-registry for further reference.

**Comment by sundayha** [comment]
I change the DNS to Google's (i.e. 8.8.8.8), then it worked
