### ISSUE TITLE
Browser console warning when debugging

### ISSUE THREAD

**Issue by indam1** [nuxt/nuxt#26453]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.11.1
- Nuxt Version:     3.11.1
- CLI Version:      3.11.0
- Nitro Version:    2.9.4
- Package Manager:  yarn@1.22.21
- Builder:          -
- User Config:      sourcemap, debug
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-tnjhkj

### Describe the bug

`Timer '[nuxt-app] page:loading:start' already exists` and similar warnings appears probably due to `console.time()` being called two times in the `hookable` debugger. You can see this warning in the browser console with `debug: true` if you follow any link

**Comment by remihuigen** [comment]
Been seeing this one (and others). Using Nuxt 3.12.3

```
Warning: Label '[nuxt-app] app:created' already exists for console.time()
Warning: Label '[nuxt-app] page:loading:start' already exists for console.time()
No such label '[nuxt-app] page:loading:start' for console.timeEnd()
No such label '[nuxt-app] app:created' for console.timeEnd()
```

**Comment by danielroe** [comment]
I think we can track this in https://github.com/nuxt/nuxt/issues/26535.
