### ISSUE TITLE
onMounted fires before the properties have time to accept the ref in the client.

### ISSUE THREAD

**Issue by JCtapuk** [nuxt/nuxt#26469]
### Environment

Use https://codesandbox.io/
------------------------------
- Operating System: Linux
- Node Version:     v20.9.0
- Nuxt Version:     3.11.1
- CLI Version:      3.11.0
- Nitro Version:    2.9.4
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://codesandbox.io/p/devbox/vigorous-darkness-pdmxxm?file=%2Fcomponents%2FExample.client.vue%3A7%2C1

### Describe the bug

If the component has a file name of .client.vue, then when onMounted is triggered it will turn out that the ref is not registered.
If you remove the extension name *.client.vue. That works fine. But since I want to have the file name *.client.vue, I have to implement watch on the element reference

**Comment by huang-julien** [comment]
Hi :wave: https://nuxt.com/docs/guide/directory-structure/components#client-components

You need to await a tick in your onMounted hook
