### ISSUE TITLE
useError not returning documented interface

### ISSUE THREAD

**Issue by plexus77** [nuxt/nuxt#26470]
### Environment

- Operating System: `Darwin`
- Node Version:     `v21.5.0`
- Nuxt Version:     `3.11.1`
- CLI Version:      `3.11.1`
- Nitro Version:    `2.9.4`
- Package Manager:  `npm@10.2.4`
- Builder:          `-`
- User Config:      `ssr`, `nitro`, `vite`, `typescript`, `experimental`, `runtimeConfig`, `modules`, `gtm`, `routeRules`, `site`, `sitemap`, `algolia`, `proxy`, `alias`, `app`, `tailwindcss`, `googleFonts`
- Runtime Modules:  `nuxt-jsonld@2.0.8`, `@nuxtjs/google-fonts@3.2.0`, `@nuxtjs/tailwindcss@6.11.4`, `@nuxt-alt/proxy@2.5.8`, `@pinia/nuxt@0.5.1`, `@nuxtjs/algolia@1.10.1`, `@davestewart/nuxt-scrollbar@1.0.0`, `@zadigetvoltaire/nuxt-gtm@0.0.13`, `nuxt-simple-sitemap@4.4.1`
- Build Modules:    `-`

### Reproduction

When I use showError or throwError and then in another area useError I can see that there is an object set but it is different to the documented type.

### Describe the bug

`const error = useError()` returns the following object

```
ObjectRefImpl {
  _object:
   { data: {},
     state: { '$s__nuxt_devtools__': [Object] },
     once: Set(0) {},
     _errors: {},
     serverRendered: true,
     path: '/essentialssdfsdfdsf',
     error:
      { url: '/essentialssdfsdfdsf',
        statusCode: 404,
        statusMessage: 'Page Not Found',
        message: 'Page Not Found',
        stack: '' },
     pinia: {} },
  _key: 'error',
  _defaultValue: undefined,
  __v_isRef: true }
```

To access the status code and message I am doing the following `error._object.error.statusCode + ' ' + error._object.error.statusMessage`

### Additional context

I have global seo middleware that is either loading seo content from the cms or trying to set the head title and description from useError.

**Comment by warflash** [comment]
`error` is a ref so you need to access its value through `.value`

**Comment by plexus77** [comment]
Yes I realise that but there is no object in there let alone what is documented on the website ie statusCode, statusMessage & message https://nuxt.com/docs/api/composables/use-error

**Comment by danielroe** [comment]
@plexus77 Would you raise a new issue with a reproduction? 🙏

**Comment by plexus77** [comment]
Ok will do when I get some free time
