### ISSUE TITLE
@nuxt/kit.addComponent fails when using external npm package + global = true

### ISSUE THREAD

**Issue by cioraneanu** [nuxt/nuxt#26471]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.4
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-jldudq?file=modules%2Fregister-component.js

### Describe the bug

I'm importing the "@tabler/icons-vue" library and I want to globally register some of the icons so I can show them using as dynamic components via `<component :is="a" />`

If global is set to false everything works as expected and i can render the component using it's name.
Setting global to true throws this error:

`Uncaught SyntaxError: The requested module '/_nuxt/node_modules/@tabler/icons-vue/dist/esm/tabler-icons-vue.mjs?nuxt_component=async&nuxt_component_name=IconAnalyze' does not provide an export named 'IconAnalyze' (at components.plugin.mjs:1:10)`

**Comment by huang-julien** [comment]
Hi :wave: you have to resolve your component first:

```html
<template>
  <div>
    <p>Test</p>

    <div>1.(Registered) <IconAnalyze :size="22" /></div>
    <div>2.(Global) <component :is="analyze" /></div>
    <div>3. <IconAngle /></div>
  </div>
</template>

<script setup>
const analyze = resolveComponent('IconAnalyze')
</script>
```
