### ISSUE TITLE
 I would like to know whether it is possible to dynamically modify the environment variable values ​​defined in the project through pm2 after nuxt3 is packaged through build?

### ISSUE THREAD

**Issue by tanglongyan** [nuxt/nuxt#26484]
### Environment

node: v18.17.1
pm2: 5.3.1
nuxt: 3.6.5

### Reproduction

I would like to know whether it is possible to dynamically modify the environment variable values ​​defined in the project through pm2 after nuxt3 is packaged through build?

### Describe the bug

I would like to know whether it is possible to dynamically modify the environment variable values ​​defined in the project through pm2 after nuxt3 is packaged through build?

### Additional context

![image](https://github.com/nuxt/nuxt/assets/44485600/65085395-bba3-4696-bd4c-79b7d8954bc9)
![image](https://github.com/nuxt/nuxt/assets/44485600/b73d925c-4576-4487-a442-74f3ff9c3ed3)

**Comment by tanglongyan** [comment]
> You can modify runtimeConfig variables with `NUXT_*` environmenet. See [the runtime config documentation](https://nuxt.com/docs/guide/going-further/runtime-config#environment-variables)

I want to dynamically set environment variables through pm2 after nuxt is packaged through the build command. Is there any way to do this with nuxt?

**Comment by huang-julien** [comment]
you have to set it up in your startup command in pm2

**Comment by tanglongyan** [comment]
> you have to set it up in your startup command in pm2
Thank you! The problem has been solved
