### ISSUE TITLE
Hydration error using asynchronous global state (Pinia, useState) between adjacent component

### ISSUE THREAD

**Issue by leofredy** [nuxt/nuxt#26508]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.0.0
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.5
- Package Manager:  npm@9.6.4
- Builder:          -
- User Config:      app, runtimeConfig, css, googleFonts, modules, devtools, srcDir, dir, alias, pinia
- Runtime Modules:  nuxt-swiper@1.2.2, @nuxtjs/google-fonts@3.2.0, @pinia/nuxt@0.5.1, @nuxtjs/eslint-module@4.1.0
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-u2kiq1?file=app.vue

### Describe the bug

My application needs to share asynchronous information between two adjacent component, but hydration errors are returned to me and this is very frustrating.

look example below, simple application using useState, but we have a same error using Pinia

https://stackblitz.com/edit/nuxt-starter-u2kiq1?file=app.vue

Where am I going wrong?

### Logs

```shell-script
[Vue warn]: Hydration node mismatch:
- rendered on server: <!---->  
- expected on client: div
```

**Comment by manniL** [comment]
On the road right now but could be similar to https://github.com/nuxt/nuxt/issues/19258

**Comment by leofredy** [comment]
@manniL 

Yeah, is similar, but to Global State it shouldn't be error, right? For cascade flow we can use a prop...

**Comment by danielroe** [comment]
I think this is the same issue as https://www.youtube.com/watch?v=dZSNW07sO-A.

Global state can't update HTML that has already been rendered.

**Comment by leofredy** [comment]
@danielroe Wow, I was surprised to learn that this operation is as expected from nuxt 3, a big change that didn't exist in nuxt 2, we were able to render there, as the flow was something more global.

It was clear that in nuxt 3 we will have to work on a flow of props and emitters so that the application recognizes the changes and re-renders it correctly.

"Global status will just be a shortcut to not go from prop to prop"
