### ISSUE TITLE
Recurring consola Named Export Error in Nuxt 3

### ISSUE THREAD

**Issue by nicokempe** [nuxt/nuxt#26505]
### Original in https://github.com/nuxt/nuxt/discussions/26477

<div type='discussions-op-text'>

<sup>Originally posted by **nicokempe** March 25, 2024</sup>
Hey everyone! 👋🏽 

I'm running into a recurring issue with consola in a Nuxt 3 project and am wondering if this is a known issue. After reinstalling or recreating pnpm-lock.yaml and node_modules, I keep getting an error related to a missing Named Export from consola. Here are some details about my environment:

- Operating System: Windows_NT
- Node Version: v20.8.1
- Nuxt Version: 3.11.1
- Package Manager: pnpm@8.14.1
- Additional Info: Using @nuxtjs/tailwindcss and nuxt-headlessui

I've tried running nuxi upgrade --force and switching to Node.js 18, but the issue persists. How consola is currently being inherited in my project is visible in my [pnpm why consola](https://github.com/nuxt/nuxt/files/14746376/pnpm-why-consola.txt) file. I have seen an old issue (https://github.com/nuxt/nuxt/issues/20209) with a similar problem but my current enviroment should have fixed that a long time ago...

And this is the exact error message I'm encountering:

```bash
ERROR [worker reload] [worker init] The requested module 'file://C:/Users/accou/node_modules/consola/dist/consola.js' does not provide an export named 'consola'
import { consola } from 'C:/Users/accou/node_modules/consola/dist/consola.js';
^^^^^^^
SyntaxError: The requested module 'C:/Users/accou/node_modules/consola/dist/consola.js' does not provide an export named 'consola'
```

Are there any known issues or conflicts with consola in this environment, or any suggestions on what else I might try? Any insight would be much appreciated! Not sure if this is actually an issue so I have opened an discussion first. :)

Thanks in advance! 🙏🏽 </div>

**Comment by danielroe** [comment]
There are no known issues with this, but note that there is a global `C:/Users/accou/node_modules` on your computer. Delete that folder to avoid the old `consola` instance from there from being used in your nuxt project.

**Comment by nicokempe** [comment]
Thank you very much! Wasn't sure, that's why I have created it as a discussion at first but makes sense.. 😅

**Comment by p0358** [comment]
In my case, also using pnpm, I had no global "consola", had to nuke node_modules and lockfile completely and make a fresh install for the error to go away. It's as if something depended on newer "consola" without explicitly bumping the required version and then pnpm didn't bother to update it in such case?

**Comment by danielroe** [comment]
@p0358 Nuxt has an explicit dependency but maybe you had another package that didn't.

regardless, I'm glad it's resolved
