### ISSUE TITLE
Static Asset does not work in the production version when changing public folders

### ISSUE THREAD

**Issue by PicassoHouessou** [nuxt/nuxt#26509]
### Environment

- Operating System: `Darwin`
- Node Version:     `v21.6.2`
- Nuxt Version:     `3.10.2`
- CLI Version:      `3.10.1`
- Nitro Version:    `2.8.1`
- Package Manager:  `yarn@1.22.21`
- Builder:          `-`
- User Config:      `devtools`, `typescript`, `srcDir`, `modules`, `i18n`, `app`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/i18n@8.1.1`, `@pinia/nuxt@0.5.1`, `@vee-validate/nuxt@4.12.5`, `@nuxtjs/color-mode@3.3.2`, `@nuxt/image@1.4.0`
- Build Modules:    `-`

### Reproduction

```ts
// https://nuxt.com/docs/api/configuration/nuxt-config
const path = require('path');
export default defineNuxtConfig({
  devtools: { enabled: true },
  srcDir: 'src/',
  dir:{public: path.join(__dirname, 'public')  }
  })

```

### Describe the bug

I change the source directory to **src**, then place the public directory in a folder outside the src directory. Static assets work in dev (**yarn dev**) but in production (**yarn build**) they don't. I notice that static files are not copied when compiling in production.

When I put the public folder in the src folder and don't change the **public** option, everything works fine.

**Comment by danielroe** [comment]
This was resolved in https://github.com/nuxt/nuxt/pull/26163.
