### ISSUE TITLE
Cannot run dev from network location/drive 

### ISSUE THREAD

**Issue by OxyzOne** [nuxt/nuxt#26507]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.9.0
- Nuxt Version:     -
- CLI Version:      3.11.1
- Nitro Version:    -
- Package Manager:  unknown
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

Just follow Nuxt Get Started Installation: https://nuxt.com/docs/getting-started/installation

```
npx nuxi@latest init <project-name>
yarn install
yarn dev --open
```

### Describe the bug

**On Terminal**
X:\CODESPACE\src>yarn dev --open
yarn run v1.22.19
$ nuxt dev --open
[error] Pre-transform error: path should be a `path.relative()`d string, but got "/172.18.3.14/.....CODESPACE/src/node_modules/nuxt/dist/app/composables/error.js?v=1aa07e21"
[error] Pre-transform error: path should be a `path.relative()`d string, but got "/172.18.3.14/.....CODESPACE/src/node_modules/nuxt/dist/app/nuxt.js?v=1aa07e21"
[error] Pre-transform error: path should be a `path.relative()`d string, but got "/172.18.3.14/.....CODESPACE/src/node_modules/nuxt/dist/app/nuxt.js?v=1aa07e21" (x2)
[error] Pre-transform error: path should be a `path.relative()`d string, but got "/172.18.3.14/.....CODESPACE/src/node_modules/nuxt/dist/app/plugins/revive-payload.client.js?v=1aa07e21"
[error] Pre-transform error: path should be a `path.relative()`d string, but got "/172.18.3.14/.....CODESPACE/src/node_modules/nuxt/dist/head/runtime/plugins/unhead.js?v=1aa07e21"
[error] Pre-transform error: path should be a `path.relative()`d string, but got "/172.18.3.14/.....CODESPACE/src/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js?v=1aa07e21"
[error] Pre-transform error: path should be a `path.relative()`d string, but got "/172.18.3.14/.....CODESPACE/src/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js?v=1aa07e21"
[error] Pre-transform error: path should be a `path.relative()`d string, but got "/172.18.3.14/.....CODESPACE/src/node_modules/nuxt/dist/app/plugins/router.js?v=1aa07e21"
[error] Pre-transform error: path should be a `path.relative()`d string, but got "/172.18.3.14/.....CODESPACE/src/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js?v=1aa07e21"
[error] Pre-transform error: path should be a `path.relative()`d string, but got "/172.18.3.14/.....CODESPACE/src/node_modules/nuxt/dist/app/components/nuxt-root.vue"

**On Browser**
![image](https://github.com/nuxt/nuxt/assets/6562487/8194071c-b459-41f2-938c-2c74f6b640b5)

X: is a mapped drive of network location //172.18.3.14/...
This only happened when I run it from network location. As we can see in log above the error show that it use the network path instead of mapped drive where I start the command.

When I copy the exact directory to C: drive and run it from there, the issue disappear. Nuxt started successfully.

### Additional context

In my office environment, Developers logged in to Remote Desktop Terminal, so each dev assigned with a network location for storage while C: is limited for Remote Desktop server storage. Thus, we must mapped our network storage as a drive.

With this bug I cannot work with Nuxt 3. This has not happen with Nuxt 2. I can run Nuxt 2 project from my network drive.

**Comment by danielroe** [comment]
This seems like it might be an upstream issue with vite/vite-node.

cc: @antfu

**Comment by OxyzOne** [comment]
@danielroe , thanks for pointing out the source of the issue. I finally found out the solution.

For those who might have same issue:

in nuxt.config.ts
```
export default defineNuxtConfig({
  ....
  vite: {
    resolve: {
      preserveSymlinks: true
    }
  }
})

```
