### ISSUE TITLE
Augmenting RuntimeNuxtHooks not working correctly

### ISSUE THREAD

**Issue by Tarabass** [nuxt/nuxt#26510]
### Environment

- Operating System: Windows_NT
- Node Version:     v21.5.0
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.4
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      devtools, extends, app, buildModules, modules, image, pinia, piniaPersistedstate, imports, i18n, primevue, css, runtimeConfig, routeRules
- Runtime Modules:  @nuxtjs/i18n@8.2.0, @nuxt/image@1.4.0, @nuxtjs/tailwindcss@6.11.4, @pinia/nuxt@0.5.1, @pinia-plugin-persistedstate/nuxt@1.2.0, nuxt-primevue@0.3.1, @vueuse/nuxt@10.9.0     
- Build Modules:    @nuxt/typescript-build@3.0.2

### Reproduction

[Stackblitz](https://stackblitz.com/edit/github-owmsrs?embed=1&file=app.vue) (typescript not working, I'm sorry)

or

[Github](https://github.com/Tarabass/stackblitz_nuxt_custom_hooks_not_typed)

### Describe the bug

As I want to add a custom hook to the `RuntimeNuxtHooks` hooks I added this hook to my `vue-shim.d.ts` file. Everything is working correctly, except that `TypeScript` is not picking up the custom hook. 

vue-shim.d.ts
```js
import { HookResult } from "@nuxt/schema";

declare module '#app' {
  interface RuntimeNuxtHooks {
    'form:submit': () => HookResult
  }
}
```

![317195876-c52d884a-3347-4ac6-8354-d844d72acef8](https://github.com/nuxt/nuxt/assets/462513/0123cfa4-8c22-4554-b1c8-a7183ba78ca0)

### Additional context

I don't know if it has something to do with the bug, but in the `.nuxt` folder `vue-shim-d.ts` is empty

**Comment by Tarabass** [comment]
Discussion: https://github.com/nuxt/nuxt/discussions/16873

**Comment by manniL** [comment]
Did you export something at the end to ensure the file is considered a module? Try e.g. `export {}`

**Comment by danielroe** [comment]
`@nuxt/types` and `@nuxt/typescript-build` are not Nuxt 3 packages. Also your `vue-shim.d.ts` is incorrect; it's a format for a Vue 2 shim, not a Vue 3 shim.

Finally, you are overwriting the Nuxt types in your `tsconfig.json` by modifying it (and importing Nuxt 2 types there). Please see note in https://nuxt.com/docs/guide/concepts/typescript#nuxttsconfigjson.

Here's an updated and working reproduction on Stackblitz: https://stackblitz.com/edit/github-owmsrs?embed=1&file=app.vue

**Comment by Tarabass** [comment]
Thx for the explanation! Do you know a tutorial or walk-through to set this up properly. It has to be cross IDE, 'cause my colleague's are IntelliJ users. I saluted Webstorm long time ago in return for VSCode..

Coming from a Vue 2 environment in TypeScript, now working with Nuxt 2 without TypeScript and migrating to Nuxt 3 with TypeScript makes me sometimes "door de bomen het bos niet meer zien" 🌳

**Comment by danielroe** [comment]
Updated: https://stackblitz.com/edit/github-owmsrs?embed=1&file=app.vue...

**Comment by danielroe** [comment]
Updated (sorry - it wasn't forking properly before): https://stackblitz.com/edit/github-owmsrs-bv3kyu?file=plugins/test.ts,nuxt.config.ts,package.json,tsconfig.json

**Comment by Tarabass** [comment]
Thank you for your time and effort, Daniël! So much appreciated :)

**Comment by danielroe** [comment]
Not at all!
