### ISSUE TITLE
NuxtWelcome instructs to alter app.vue, when app.vue is absent

### ISSUE THREAD

**Issue by maritaria** [nuxt/nuxt#26513]
### Environment

- Operating System: Linux
- Node Version:     v16.15.0
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.5
- Package Manager:  pnpm@8.15.4
- Builder:          -
- User Config:      modules, devtools
- Runtime Modules:  @nuxtjs/tailwindcss@6.11.4, @nuxt/fonts@0.5.1
- Build Modules:    -

### Reproduction

1. pnpm dlx nuxi create my-app
2. cd my-app
3. pnpm i
4. rm app.vue
5. pnpm dev
6. Open http://localhost:3000/

### Describe the bug

The introduction of `<NuxtWelcome />` explains that the developer should edit `app.vue` and replace `<NuxtWelcome />` with some content. There is a case when the developer removes app.vue, as noted in [Docs > Views#Pages](https://nuxt.com/docs/getting-started/views#pages). Then the routing, I presume, is based solely of the `pages/` directory and the index has as fallback  the `NuxtWelcome` component.

### Additional context

- I removed `/app.vue`
- In the project `/pages` exists as a directory, but has no single file in it.
- Creating the file `/pages/index.vue` removes the welcome as per usual.

**Comment by maritaria** [comment]
Since there is a fallback to the absence of app.vue, perhaps that check can point to an alternative `NuxtWelcome`; for example a NuxtWelcomeWithoutApp which just renders `<NuxtWelcome without-app-file>` and then instructions alter in `NuxtWelcome` based on that flag.

I'd say that extending the intro message with two approaches increases complexity for beginners, which is the intended audience of the text.

Also, I'm willing to contribute the changes but I'd rather the project maintainers/leadership would decide on the direction.

**Comment by manniL** [comment]
@maritaria Seems more than reasonable 👍🏻
You should find the NuxtWelcome template in https://github.com/nuxt/assets/blob/main/packages/templates/templates/welcome/index.html

**Comment by danielroe** [comment]
So sorry, I just saw you had assigned it! I raised a PR, but would welcome your thoughts + feedback on it.
