### ISSUE TITLE
Removal of baseUrl from .nuxt/tsconfig.json in nuxt v3.7.0 breaks Cypress tsconfig.json path aliasing

### ISSUE THREAD

**Issue by JasonLandbridge** [nuxt/nuxt#26512]
### Environment

Working directory: /mnt/PROJECTS/ProjectA                                     12:37:32 PM
Nuxt project info:                                                                                   12:37:32 PM

------------------------------
- Operating System: Linux
- Node Version:     v18.19.1
- Nuxt Version:     3.7.4
- CLI Version:      3.11.1
- Nitro Version:    2.9.5
- Package Manager:  npm@9.8.0
- Builder:          -
- User Config:      ssr, srcDir, devServer, runtimeConfig, app, modules, quasar, typescript, macros, lodash, i18n, css, imports, alias, components, vite, nitro, build, hooks, telemetry
- Runtime Modules:  nuxt-quasar-ui@2.0.4, @vueuse/nuxt@10.2.1, @nuxtjs/i18n@8.0.0-beta.13, @vue-macros/nuxt@1.3.18, nuxt-lodash@2.5.0, @nuxt/test-utils/module@3.12.0, @pinia/nuxt@0.4.11
- Build Modules:    -
------------------------------

### Reproduction

Reproduction link: https://github.com/JasonLandbridge/Cypress-Path-Alias-Reproduction

### Describe the bug

When using Nuxt in combination with [Cypress](https://docs.cypress.io/guides/overview/why-cypress) and [Cypress-Vite](https://github.com/mammadataei/cypress-vite) it is recommended to have the following tsconfig layout:
[Cypress Typescript support](https://docs.cypress.io/guides/tooling/typescript-support): 
```
<Project folder>
├── .nuxt
│   └── tsconfig.json
├── cypress
│   └── tsconfig.json
├── src
└── tsconfig.json
```

Where each `tsconfig.json` extends from the other to allow Typescript path aliasing to work correctly in Cypress E2E tests.

This worked great until Nuxt [v3.7.0](https://github.com/nuxt/nuxt/releases/tag/v3.7.0) where in PR https://github.com/nuxt/nuxt/pull/22410 the `baseUrl` was removed from the `.nuxt/tsconfig.json`

However, this `baseUrl` is crucial for Cypress to correctly translate path aliasing to the real path. 

Consider the following `tsconfig.json` files:

```json5
// .nuxt/tsconfig.json
{
  "compilerOptions": {
    "paths": {
      "@mock": [
        "../src/mock-data"
      ],
      "@mock/*": [
        "../src/mock-data/*"
      ],
  },
}
```

```json5
// [ROOT]/tsconfig.json
{
  "extends": "./.nuxt/tsconfig.json",
  "compilerOptions": {
    "noImplicitAny": false,
    "types": [
      "unplugin-vue-define-options/macros-global",
      "@nuxtjs/i18n",
      "@pinia/nuxt",
      "vitest/importMeta",
      "vitest/globals",
      "@testing-library/cypress",
      "cypress"
    ]
  }
}

```

```json5
// cypress/tsconfig.json
{
  "extends": "../tsconfig.json", // Needed for the path aliases
  "compilerOptions": {
    "types": ["cypress", "cypress-signalr-mock", "@testing-library/cypress", "node"],
    "baseUrl": "./",
    "sourceMap": false,
    "target": "ES2019"
  },
  "include": ["**/*.ts", "../node_modules/cypress/types", "../node_modules/@types/mocha"],
}
```

The project path in this case is 
`/mnt/PROJECTS/ProjectA/`

Before v3.7.0

```bash
vite:resolve-details [fs] /mnt/PROJECTS/ProjectA/src/mock-data/mock-base 
-> /mnt/PROJECTS/ProjectA/src/mock-data/mock-base.ts +0ms
```

After v3.7.0

```bash
  vite:resolve-details [fallthrough] @mock +0ms
 # The Project folder is now missing from the path
  vite:resolve-details [fallthrough] /mnt/PROJECTS/src/mock-data +0ms
```

But, when I manually add `"baseUrl": "./",` to `.nuxt/tsconfig.json`, when on `v3.7.0`, then everything works again as it should and the paths get resolved correctly.

It seems as if there is a `../` to many when resolving the paths in the newer Nuxt versions.

Would it be possible to have a `nuxt.config.ts` option that will add back `"baseUrl": "./",` to `.nuxt/tsconfig.json` or is there some other workaround possible?

Thanks!

**Comment by danielroe** [comment]
It feels like this is an upstream issue in `cypress/vite-tsconfig-paths` - they need to support resolving relative `paths` within a file that is extended.

Here's an example of how to do that:

https://github.com/nuxt/module-builder/blob/main/src/commands/build.ts#L279-L295

**Comment by JasonLandbridge** [comment]
Workaround: https://github.com/aleclarson/vite-tsconfig-paths/issues/123#issuecomment-2029702341

In the root `tsconfig.json`
```json
{
  "extends": "./.nuxt/tsconfig.json",
  "compilerOptions": {
    "baseUrl": "./.nuxt/",  //<-- Add this
  }
```

then inherrit from this `tsconfig.json` in `/cypress/tsconfig.json`

```json
{
  "extends": "../tsconfig.json", // Needed for the path aliases
}
```
