### ISSUE TITLE
NUXT_PUBLIC_XXX environment variables not overriding public runtimeConfig in production

### ISSUE THREAD

**Issue by 4dr1en** [nuxt/nuxt#26520]
### Environment

Working directory: /home/andrey/Documents/nuxt-env-test                                                                                                      4:42:45 PM
Nuxt project info:                                                                                                                                           4:42:45 PM

------------------------------
- Operating System: Linux
- Node Version:     v20.11.0
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.5
- Package Manager:  pnpm@8.15.5
- Builder:          -
- User Config:      devtools, runtimeConfig
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/4dr1en/repro-nuxt-dynamic-env

The .env is included in the repo.
> pnpm run dev

and

> pnpm preview

work

> source .env && node .output/server/index.mjs

do not

### Describe the bug

When I follow the official documentation:
https://nuxt.com/docs/guide/going-further/runtime-config#example

The public runtimeConfig is being replaced by the environements variables in developpement and when doing `pnpm preview`.
But when the nuxt application is started doing `source .env && node .output/server/index.mjs`, the public runtime configuration is left empty.

### Additional context

I need to update the runtimeConfiguration using the env variables without rebuilding the app, I tried to follow th official [documentation](https://nuxt.com/docs/guide/going-further/runtime-config#example) but it doesn't work in production.

.env content
```env
NUXT_PUBLIC_MSG="Hello world!"
```

nuxt.config.ts
```typescript
export default defineNuxtConfig({
  devtools: { enabled: true },
  runtimeConfig: {
    public: {
      msg: ''
    }
  }
})
```

app.vue
```typescript
<script lang="ts">
  export default defineNuxtComponent({
    mounted() {
      console.log(this.$config.public.msg)
    }
  })
</script>

<template>
  <div>
    {{ $config.public.msg }}
  </div>
</template>
```

### Logs
cli
```shell-script
❯ source .env && echo $NUXT_PUBLIC_MSG
Hello world!
❯ source .env && node .output/server/index.mjs
Listening on http://[::]:3000
```

browser console
```javascript
<empty string> Mc_nPuuN.js:23:55632
```

This is working with `pnpm preview` :

cli
```shell-script
❯ pnpm preview

> nuxt-app@ preview /home/andrey/Documents/nuxt-env-test
> nuxt preview

                                                                                                                                                             5:06:53 PM
 ╭────────────────────────────────────────Preview Mode──────────────────────────────────────────╮
 │                                                                                              │
 │  You are running Nuxt production build in preview mode.                                      │
 │  For production deployments, please directly use node ./server/index.mjs command.            │
 │                                                                                              │
 │  Node.js:           v20.11.0                                                                 │
 │  Nitro Preset:      node-server                                                              │
 │  Working directory: .output                                                                  │
 │                                                                                              │
 ╰──────────────────────────────────────────────────────────────────────────────────────────────╯

ℹ Loading .env. This will not be loaded when running the server in production.                                                                              5:06:53 PM
ℹ Starting preview command: node ./server/index.mjs                                                                                                         5:06:53 PM
                                                                                                                                                             5:06:53 PM
Listening on http://[::]:3000
```

browser console
```javascript
Hello world! [Mc_nPuuN.js:23:55632](http://[::]:3000/_nuxt/Mc_nPuuN.js)
```

**Comment by manniL** [comment]
`NUXT_PUBLIC_MSG=Hello  node .output/server/index.mjs` runs fine in the reproduction, so the problem is not in nuxt but on the system settings.

`export $(grep -v '^#' .env | xargs) && node .output/server/index.mjs` works too ☺️

More info e.g. on [StackOverflow](https://stackoverflow.com/a/20909045/3975480)

**Comment by 4dr1en** [comment]
> `NUXT_PUBLIC_MSG=Hello node .output/server/index.mjs` runs fine in the reproduction, so the problem is not in nuxt but on the system settings.
> 
> `export $(grep -v '^#' .env | xargs) && node .output/server/index.mjs` works too, same goes for `set -a; source .env; set +a` ☺️
> 
> More info e.g. on [StackOverflow](https://stackoverflow.com/a/20909045/3975480)

Thank you very much
