### ISSUE TITLE
When usefetch makes network requests, the parameters of the second request depend on the response result of the first interface. If usefetch is nested, an error will be returned, indicating that usefetch can only be used by setup. If $fetch is used, both client and server will be triggered once. What's the solution

### ISSUE THREAD

**Issue by yyt-do** [nuxt/nuxt#26529]
### Describe the feature

When usefetch makes network requests, the parameters of the second request depend on the response result of the first interface. If usefetch is nested, an error will be returned, indicating that usefetch can only be used by setup. If $fetch is used, both client and server will be triggered once. What's the solution
![code](https://github.com/nuxt/nuxt/assets/56466963/9e0719d2-9839-4e46-8ec5-5adf8acadbfd)

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
See https://nuxt.com/docs/guide/going-further/nuxt-app#the-nuxt-context for why this happens. You can use `runWithContext` to resolve this: https://nuxt.com/docs/api/composables/use-nuxt-app#runwithcontext.

**Comment by yyt-do** [comment]
When I use nuxtApp.runWithContext(() =&gt; navigateTo('/login')) to perform route jump in the fetch response intercept according to your method, the page will always be stuck and cannot jump, because my request is a request from the server side. When the request of the server side is expired, I want the application to jump to the login page. At this time, because the server side cannot carry out route redirection, the page will always load. How to deal with this situation? At present, I make judgment in the middleware for processing




As before, nuxt2 can be directly redirected using redirect
------------------ 原始邮件 ------------------
发件人:                                                                                                                        "nuxt/nuxt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月29日(星期五) 凌晨2:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nuxt/nuxt] When usefetch makes network requests, the parameters of the second request depend on the response result of the first interface. If usefetch is nested, an error will be returned, indicating that usefetch can only be used by setup. If $fetch is used, both client and server will be triggered once. What's the solution (Issue #26529)





 
Closed #26529 as not planned.
