### ISSUE TITLE
nest NuxtImg inside NuxtLink

### ISSUE THREAD

**Issue by vvatlin** [nuxt/nuxt#26528]
### Environment

- Operating System: `Darwin`
- Node Version:     `v21.7.1`
- Nuxt Version:     `3.10.3`
- CLI Version:      `3.11.0`
- Nitro Version:    `2.9.3`
- Package Manager:  `npm@10.5.0`
- Builder:          `-`
- User Config:      `devtools`, `modules`, `colorMode`, `runtimeConfig`
- Runtime Modules:  `@nuxt/ui@2.14.2`, `@nuxt/image@1.4.0`, `@pinia/nuxt@0.5.1`
- Build Modules:    `-`

### Reproduction

```
<NuxtLink :to="`/post/${id}`"> 
    <NuxtImg width="230" sizes="100vw" class="rounded-xl" :src="image" alt="Error load image" />
</NuxtLink>
```

### Describe the bug

Sorry I'm not very familiar with CSS but such combination break NuxtImage responsive size and I get absolutely different sizes for different images although without NextLink everything is perfect

**Comment by MustafaM257** [comment]
Hello, Could you upload a github repository for further debugging ?
