### ISSUE TITLE
getCookie return always undefined

### ISSUE THREAD

**Issue by joffreyBerrier** [nuxt/nuxt#26534]
### Environment

- Operating System: Darwin
- Node Version:     v20.10.0
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.5
- Package Manager:  pnpm@8.15.5
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://github.com/joffreyBerrier/get-cookie-nuxt
https://stackblitz.com/~/github.com/joffreyBerrier/get-cookie-nuxt

### Describe the bug

I'm using this example https://nuxt.com/docs/api/composables/use-cookie#cookies-in-api-routes
* `getCookie` send always undefined, it doesn't work properly

If I replace useAsyncData by useFetch it doesn't change anything I saw [this issue](https://github.com/nuxt/nuxt/issues/24180) but I don't understand how I can fix my issue

**Comment by danielroe** [comment]
`getCookie` returns the cookie on the incoming request headers. `setCookie` sets a cookie on the outgoing response headers. So setting a cookie will not affect the value when you get a cookie.

Let's track in https://github.com/nuxt/nuxt/issues/22631.
