### ISSUE TITLE
Are GitHub Discussions actually being used for non-feature/bug issues?

### ISSUE THREAD

**Issue by dword-design** [nuxt/nuxt#26538]
### Describe the feature

Wanted to basically ask if GitHub Discussions are actually the right place to ask questions not directly related to features and bugs? Since I have the feeling that they aren't read, most issues are unanswered. Not wanting to push anything, just interested :).

I opened [this thread about whether to support Nuxt 2 in Nuxt modules](https://github.com/nuxt/nuxt/discussions/24685).

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
It's indeed a great place to go for help/support, alongside Discord.
