### ISSUE TITLE
Add Vite's preprocessorMaxWorkers config

### ISSUE THREAD

**Issue by daniluk4000** [nuxt/nuxt#26539]
### Describe the feature

Hello there. I've been digging around and found this new `preprocessorMaxWorkers` setting from Vite, which is considered experimental. I have tried to enable it for our project and build time reduced by almost 30 seconds. 

I've come with idea to enable this for all Nuxt users and allow to easy configure it from `experimental`:

- Name in config: `experimental.preprocessorMaxWorkers`
- Default: `true` (or maybe `false` until next minor?)
- Possible values: `boolean | number`
- Basically enables `vite.css.preprocessorMaxWorkers`

I can see that as potential performance improvement with option for easy disable.

I would happily implement that if Nuxt team is OK with described above.

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Let's let Vite manage moving this feature out of experimental, and for now, document this in the preprocessor documentation for Nuxt 🙏
