### ISSUE TITLE
nuxt3 builderio tree shaking

### ISSUE THREAD

**Issue by Ischafak** [nuxt/nuxt#26555]
### Describe the feature

Hi, i am using builder io with nuxt 3. 
there is one component that i dont use anywhere else in my project. When i try to call that component in builder io i get nothing on my screen.

is it possible for me to disable tree shaking for that component?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Yes, you can register that component as a global component.
