### ISSUE TITLE
routeRules are undefined in production

### ISSUE THREAD

**Issue by mikeCrafted** [nuxt/nuxt#26567]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v21.6.1
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.5
- Package Manager:  npm@9.6.4
- Builder:          -
- User Config:      runtimeConfig, sourcemap, vite, app, css, modules, i18n, alias, auth, build, site, schemaOrg, ogImage, sitemap, devtools
- Runtime Modules:  @sidebase/nuxt-auth@0.6.7, @nuxtjs/i18n@8.2.0, @pinia/nuxt@0.5.1, nuxt3-leaflet@1.0.12, @nuxtjs/seo@2.0.0-rc.10
- Build Modules:    -
------------------------------

### Reproduction

Indeterministic behavior only in production build on Azure app service :(
following routeRules are in nuxt.config:
`routeRules: {
        '/jobs': { redirect: '/karriere' }
    }`

### Describe the bug

App crashes on load with this error:
![image](https://github.com/nuxt/nuxt/assets/63555352/6084d0cb-2a69-481f-a093-8c539179b26a)
Never had this in dev or local build, error occurs only for some users - not on any of my machines, which makes it difficult to track down for the cause.

**Comment by tobiasdiez** [comment]
I experience a similar but slightly different issue. Upon upgrading from nuxt 3.10.3 all routes defined in `nuxt.config` as well as all pages except for the index are resulting in 404 errors when deployed to azure functions. Strangely, also the server routes are working correctly (in my case `/api`). I cannot reproduce it locally with the azure cli, and running the dev server locally also works. No errors are logged in the azure portal. Hence, I have no idea how to investigate this issue further. @mikeCrafted did you found a temporary workaround?

Not sure if I its worth opening another issue for the problem I'm seeing.

**Comment by mikeCrafted** [comment]
@tobiasdiez no, nothing so far. Keep getting this error every now and then, probably once per day. Still can't reproduce it though.

**Comment by tobiasdiez** [comment]
Thanks. For me downgrading nitro to 2.8.1 worked. Not sure if you see exactly the same error, so not sure if this is a solution for you as well. I've opened https://github.com/unjs/nitro/issues/2342 to track this at the source.

**Comment by markthree** [comment]
@tobiasdiez @mikeCrafted I think it's a problem with ofetch, try this module to fix it for now you [markthree/nuxt-fix-ofetch](https://github.com/markthree/nuxt-fix-ofetch)

**Comment by danielroe** [comment]
let's track upstream in https://github.com/unjs/nitro/issues/2342 - this is unlikely to be a nuxt issue and is more likely to be a nitro one... a minimal reproduction would be helpful there though, if possible
