### ISSUE TITLE
Remove or fix `state` from islands components

### ISSUE THREAD

**Issue by huang-julien** [nuxt/nuxt#26579]
### Describe the feature

Currently, we send back all states (`useState`) from island within the island response.

It currently doesn't have any impact on the app calling the island.

There's 2 solutions:
- we keep it and fix the bug where the state isn't applied to the current App
  - ⚠️What would happen if we have 2 island located in the same component ? Both are making a promise so the user cannot know what will happen (in which order useState will be set)
- we completly remove it and reduce the json payload for island responses.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Let's remove state for now. We can always add as a future enhancement if needed 🙏
