### ISSUE TITLE
Body style background image does not update when theme changes

### ISSUE THREAD

**Issue by PicassoHouessou** [nuxt/nuxt#26586]
### Environment

- Operating System: `Darwin`
- Node Version:     `v21.6.2`
- Nuxt Version:     `3.11.1`
- CLI Version:      `3.11.1`
- Nitro Version:    `2.9.5`
- Package Manager:  `yarn@1.22.21`
- Builder:          `-`
- User Config:      `devtools`, `typescript`, `srcDir`, `modules`, `i18n`, `app`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/i18n@8.2.0`, `@pinia/nuxt@0.5.1`, `@vee-validate/nuxt@4.12.6`, `@nuxtjs/color-mode@3.3.3`, `@nuxt/image@1.4.0`
- Build Modules:    `-`

### Reproduction

```ts
const colorMode = useColorMode();
useHead({
  bodyAttrs: {
    class: computed(() => {
      if(colorMode.value=== 'light'){
        return "bg-fixed"
      }else if(colorMode.value==="dark"){
        return "bg-fixed dark-layout"
      }
      return ""
    }),
    style: computed(() => {
      if(colorMode.value=== 'light'){
        return "background-image: url(/assets/img/shape/banner-1.jpg)"
      }else if(colorMode.value==="dark"){
        return "background-image: url(/assets/img/shape/banner-2.jpg)"
      }
      return ""
    })

  },
}) ;
```

### Describe the bug

After updating to nuxt 3.11.1, the background image does not change when the theme changes.

### Additional context

I use **@nuxtjs/color-mode**

**Comment by manniL** [comment]
Could you provide a running reproduction please?

**Comment by harlan-zw** [comment]
Reproduction would be useful. I'd suggest using the object API as a workaround as well.

```ts
useHead({
  bodyAttrs: {
    class: {
      'bg-fixed': true,
      'dark-layout': () => colorMode.value === 'dark',
    },
    style: {
      'background-image': () => {
        if (colorMode.value === 'light')
          return 'url(/assets/img/shape/banner-1.jpg)'
        else if (colorMode.value === 'dark')
          return 'url(/assets/img/shape/banner-2.jpg)'

        return ''
      },
    },
  },
})
```

**Comment by manniL** [comment]
@PicassoHouessou A full project is no *minimal* reproduction. Please reduce the code to a minimum necessary to showcase the error.

**Comment by PicassoHouessou** [comment]
@manniL I reduced the code to the minimal https://github.com/PicassoHouessou/nuxt-bug/blob/main/src/pages/index.vue

**Comment by manniL** [comment]
@PicassoHouessou are the used nuxt modules also necessary to reproduce it?
Ideally, I'd suggest to start with a [new nuxt project](https://nuxt.new/s/v3) and try to repro it there

**Comment by PicassoHouessou** [comment]
I also have a problem with the languague switcher.
When I run 
`yarn generate`
The page crashes completely when I change the language in the select. In **dev**, it works.

![image](https://github.com/nuxt/nuxt/assets/56270479/659d0942-c6e8-402f-baea-a3c94940ae0a)

**Comment by PicassoHouessou** [comment]
@manniL the reproduction https://stackblitz.com/edit/github-iupks8?file=app.vue

**Comment by PicassoHouessou** [comment]
[screen-recorder-tue-apr-02-2024-10-52-07.webm](https://github.com/nuxt/nuxt/assets/56270479/322e8a2a-0285-4bc1-9981-3815211691c9)

**Comment by manniL** [comment]
This is indeed a bug it seems, but unrelated to the color mode. Next time, please make sure to make the reproduction minimal, e.g.:

```vue
<template>
  <div>
    <button @click="toggle = !toggle">Toggle</button> Value: {{ toggle.toString() }}
  </div>
</template>

<script setup>
const toggle = ref(false)

const style = computed(() => {
  if (toggle.value) {
    return 'background-color: red;';
  } else if (!toggle.value) {
    return 'background-color: green;';
  }
  return '';
})

useHead({
  bodyAttrs: {
    style
  },
});
</script>
```

**Comment by manniL** [comment]
Updating this issue - [Plain Vue + Unhead works fine](https://stackblitz.com/edit/nuxt-issues-26586-plain-vue?file=src%2FApp.vue,src%2Fmain.js) apparently.

**Comment by harlan-zw** [comment]
This should be fixed with https://github.com/unjs/unhead/releases/tag/v1.9.14
