### ISSUE TITLE
I can't use useRuntimeConfig in async setup function (Options API)

### ISSUE THREAD

**Issue by Mounir-Bouaiche** [nuxt/nuxt#26596]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.11.1`
- Nuxt Version:     `3.11.1`
- CLI Version:      `3.11.1`
- Nitro Version:    `2.9.5`
- Package Manager:  `pnpm@8.10.5`
- Builder:          `-`
- User Config:      `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction
Stackblitz: [https://stackblitz.com/edit/github-qcvhqc?file=app.vue](https://stackblitz.com/edit/github-qcvhqc?file=app.vue)
Fresh project init.

in `app.vue` file:
```vue
<template>
  <div>RuntimeConfig</div>
</template>

<script>
export default {
  name: 'HomePage',
  async setup () {
    await new Promise(res => setTimeout(res, 1000))
    return { runtimeConfig: useRuntimeConfig() }
  },
}
</script>
```

### Describe the bug

I can't use useRuntimeConfig in async setup function (Options API)
This error show up:
```
[nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at `https://nuxt.com/docs/guide/concepts/auto-imports#vue-and-nuxt-composables`.
```

**Comment by Mini-ghost** [comment]
You can try using `nuxtApp.runWithContext()` like this:

```ts
export default {
  name: 'HomePage',
  async setup() {
    const nuxtApp = useNuxtApp();
    await new Promise((res) => setTimeout(res, 1000));
    return { runtimeConfig: nuxtApp.runWithContext(() => useRuntimeConfig()) };
  },
};
```
