### ISSUE TITLE
 WARN  Cannot stringify arbitrary non-POJOs Error

### ISSUE THREAD

**Issue by Foddie2** [nuxt/nuxt#26597]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.15.0
- Nuxt Version:     3.11.0
- CLI Version:      3.10.1
- Nitro Version:    2.9.4
- Package Manager:  yarn@1.22.22
- Builder:          -
- User Config:      ssr, devtools, typescript, css, plugins, devServerHandlers, postcss, modules, content, runtimeConfig, experimental
- Runtime Modules:  @nuxt/content@2.12.1, nuxt-purgecss@2.0.0, @nuxt/image@1.4.0, @vite-pwa/nuxt@0.5.0, nuxt-mailer@0.11.0, @nuxtjs/tailwindcss@6.11.4

### Reproduction

https://stackblitz.com/edit/https-github-comfoddie2techbytes

### Describe the bug

Getting this error

**Comment by manniL** [comment]
Your StackBlitz does not contain code that can reproduce the error. But as this is a "common problem", take a look at [this video](https://www.youtube.com/watch?v=8w6ffRBs8a4&t=1s)

**Comment by dilverdev** [comment]
> Your StackBlitz does not contain code that can reproduce the error. But as this is a "common problem", take a look at [this video](https://www.youtube.com/watch?v=8w6ffRBs8a4&t=1s)

It works, I don't understand why next doesn't do it by default u.u

**Comment by manniL** [comment]
@dilverdev Nuxt can't magically assume *how* to serialize your classes, that's why 😋
