### ISSUE TITLE
Allow dedicated error pages for child routes

### ISSUE THREAD

**Issue by mklueh** [nuxt/nuxt#26608]
### Describe the feature

When having multiple routes with nested routes, I'd like to have **specific 404 pages for each.** 

However, it seems you can't place `error.vue` pages elsewhere **but in the root**.

In my opinion, it would be great if you could just drop in multiple `error.vue` pages into the directories of your routes and quickly style them according to your needs.

![image](https://github.com/nuxt/nuxt/assets/1553757/2f97c965-5b5e-41b2-aca4-6a7c9df6b14a)

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
The `error.vue` acts as a "fatal error page". You can always handle errors in your page itself by making them non-fatal and render a different component then, either via `NuxtErrorBoundary` or a `v-if`

**Comment by mklueh** [comment]
@manniL okay, so where would I need to put that `NuxtErrorBoundary` to catch a non-existent child route call without falling back to the "fatal error page"?

For example, there is a `store` package containing some entries, and a `store.vue` next to the package containing

```
<template>
  <NuxtErrorBoundary @error="someErrorLogger">
    <!-- You use the default slot to render your content -->
    <template #error="{ error, clearError }">
      You can display the error locally here: {{ error }}
      <button @click="clearError">
        This will clear the error.
      </button>
    </template>

    <NuxtPage />
    
  </NuxtErrorBoundary>
</template>
```


calling `/store/non-existent-route` will now fallback to the `error.vue` page instead of showing the custom error of the boundary.

Not sure where else I should place it otherwise
