### ISSUE TITLE
Invalid Assignment Target Error when running npm run generate

### ISSUE THREAD

**Issue by Vijayabhaskar96** [nuxt/nuxt#26649]
### Environment

Working directory: F:/Projects/beautifier
Nuxt project info:

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.11.1
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.5
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      devtools, css, vue, modules, app
- Runtime Modules:  @nuxtjs/tailwindcss@6.11.4
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

### Reproduction

I believe the issue is obvious enough to understand without reproduction.

### Describe the bug

The following piece of code runs fine with `npm run dev`
```
                                                <input
                                                    type="text"
                                                    v-model.number="
                                                        canvasHeight
                                                    "
                                                    class="text-sm font-semibold w-10 text-center" />
```
Notice the newline character introduced by Prettier before and after `canvasHeight`.

But fails with 
```
Nuxt Build Error: [vite:define] Transform failed with 1 error:                                      3:37:13 pm
F:/Projects/project/pages/index.vue?macro=true:780:56: ERROR: Invalid assignment target
```

Disabling prettier autoformating for the line and removing new line fixes it.
```
<!-- prettier-ignore -->
                                                <input
                                                    type="text"
                                                    v-model.number="canvasHeight" 
                                                    class="text-sm font-semibold w-10 text-center" />
```
This works.

**Comment by DamianGlowala** [comment]
Let's track in https://github.com/vuejs/core/issues/8306.
