### ISSUE TITLE
Configurable baseURL for `$fetch`, `useFetch` & `useLazyFetch`

### ISSUE THREAD

**Issue by MickL** [nuxt/nuxt#26651]
### Describe the feature

Currently it doesnt seem possible to define the base url for `$fetch()`, `useFetch()` and `useLazyFetch()`.  When using an external API, the url always needs to be retrieved from the config, which is kinda cumbersome:

```ts
const config = useRuntimeConfig();
const { data, error } = await useFetch('/products', {
  baseURL: config.public.apiUrl,
});
```

There is a [Stackoverflow question](https://stackoverflow.com/questions/72041740/how-to-set-global-api-baseurl-used-in-usefetch-in-nuxt-3/73636631) regarding to it with the only solution of defining wrappers around the Nuxt fetch functions, which would require to create three wrappers.

**Possible solution**
Configure the api url within `nuxt.config.ts`. If set any call to `/` goes to this API instead:

```ts
const { data, error } = await useFetch('/products'); // -> https://localhost:3333/api/products
```

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by MickL** [comment]
What do you mean by userland?

Yes I wrote above that it requires 3 wrappers which is very cumber some and the reason of this feature request. Can we leave it open please?

**Comment by manniL** [comment]
> What do you mean by userland?

Userland = "what developers using nuxt can implement"

> Yes I wrote above that it requires 3 wrappers which is very cumber some and the reason of this feature request. Can we leave it open please?

As I mentioned above, just providing defaults for all data fetching instances is not feasible. But with https://github.com/nuxt/nuxt/issues/14736 this should be easier (should cover your case too) ☺️

**Comment by MickL** [comment]
Personally I "just" want to set the baseUrl for $fetch, useFetch and useLazyFetch. Something I guess a lot of devs want to do. @manniL  You close this issue in favor of #14736 but #14736 is open for 2 years now.

As a workaround you said we can use a wrapper. This might work for useFetch and useLazyFetch but for $fetch we need to create a new instance. If doing so other problems occur, for example cookies are not passed anymore, e.g. #27996

@manniL @danielroe Can we please reopen this issue? Setting the baseUrl is something very simple and common, but it is very very cumberstone in Nuxt, especially for $fetch it seems impossible for any normal dev because of #27996

**Comment by danielroe** [comment]
Setting a default baseURL for `$fetch` isn't hard - but it would break every module or nuxt core composable that uses `$fetch`.

That's why we allow you to create your own fetch instances as Alex exemplified above.

**Comment by MickL** [comment]
baseUrl could be only applied if a configurable prefix matches, problem solved.

For example I may want everything that goes to '/api' to go to 'https://myapi.com/' instead. Same idea as the proxy, but just prefix the url string. 

Or the other way around: If the fetch url doesnt start with `_` it goes to the defined baseUrl, otherwise Nuxt Nitro server. (I think most/all modules that communicate with Nitro server, e.g nuxt icon, start their routes with '_' or even '__')
