### ISSUE TITLE
postinstall nuxt prepare error

### ISSUE THREAD

**Issue by preshitd** [nuxt/nuxt#26654]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.12.1`
- Nuxt Version:     `3.11.2`
- CLI Version:      `3.11.1`
- Nitro Version:    `2.5.0-28072065.c1cf5ce`
- Package Manager:  `npm@10.5.0`
- Builder:          `-`
- User Config:      `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

> npx nuxi@latest init test2
✔ Which package manager would you like to use?
npm
◐ Installing dependencies...                                                                                                                                                                    

### Describe the bug

Following the getting started documentation throws the error. Happens with my existing nuxt3 project as well.
https://nuxt.com/docs/getting-started/installation

5:39:26 PM

> postinstall
> nuxt prepare

 ERROR  Cannot read properties of undefined (reading 'some')                                                                                                                                    5:39:46 PM

  at node_modules/nuxt/dist/index.mjs:2733:21
  at node_modules/hookable/dist/index.mjs:48:66
  at node_modules/hookable/dist/index.mjs:48:56
  at async generateApp (/Users/star_coder/node_modules/nuxt3/dist/index.mjs:3311:3)
  at async _applyPromised (/Users/star_coder/node_modules/perfect-debounce/dist/index.mjs:54:10) 

 ERROR  Cannot read properties of undefined (reading 'some')                                                                                                                                    5:39:46 PM

npm ERR! code 1
npm ERR! path /Users/star_coder/test2
npm ERR! command failed
npm ERR! command sh -c nuxt prepare

npm ERR! A complete log of this run can be found in: /Users/star_coder/.npm/_logs/2024-04-05T12_09_27_221Z-debug-0.log

 ERROR  Error: Command failed with exit code 1: npm install 

### Logs

```shell-script
Below is the npm log:
/Users/star_coder/.npm/_logs/2024-04-05T12_09_27_221Z-debug-0.log
4626 info run fsevents@2.3.3 install node_modules/fsevents node-gyp rebuild
4627 info run fsevents@2.3.3 install { code: 1, signal: null }
4628 verbose reify failed optional dependency /Users/star_coder/test2/node_modules/fsevents
4629 silly reify mark deleted [ '/Users/star_coder/test2/node_modules/fsevents' ]
4630 timing build:run:install:node_modules/fsevents Completed in 1364ms
4631 timing build:run:install Completed in 1364ms
4632 info run esbuild@0.20.2 postinstall node_modules/esbuild node install.js
4633 info run vue-demi@0.14.7 postinstall node_modules/@vueuse/components/node_modules/vue-demi node -e "try{require('./scripts/postinstall.js')}catch(e){}"
4634 info run vue-demi@0.14.7 postinstall node_modules/@vueuse/core/node_modules/vue-demi node -e "try{require('./scripts/postinstall.js')}catch(e){}"
4635 info run vue-demi@0.14.7 postinstall node_modules/@vueuse/integrations/node_modules/vue-demi node -e "try{require('./scripts/postinstall.js')}catch(e){}"
4636 info run vue-demi@0.14.7 postinstall node_modules/@vueuse/shared/node_modules/vue-demi node -e "try{require('./scripts/postinstall.js')}catch(e){}"
4637 info run vue-demi@0.14.7 postinstall { code: 0, signal: null }
4638 timing build:run:postinstall:node_modules/@vueuse/shared/node_modules/vue-demi Completed in 137ms
4639 info run vue-demi@0.14.7 postinstall { code: 0, signal: null }
4640 timing build:run:postinstall:node_modules/@vueuse/core/node_modules/vue-demi Completed in 141ms
4641 info run vue-demi@0.14.7 postinstall { code: 0, signal: null }
4642 timing build:run:postinstall:node_modules/@vueuse/components/node_modules/vue-demi Completed in 169ms
4643 info run vue-demi@0.14.7 postinstall { code: 0, signal: null }
4644 timing build:run:postinstall:node_modules/@vueuse/integrations/node_modules/vue-demi Completed in 174ms
4645 info run esbuild@0.20.2 postinstall { code: 0, signal: null }
4646 timing build:run:postinstall:node_modules/esbuild Completed in 764ms
4647 timing build:run:postinstall Completed in 764ms
4648 timing build:deps Completed in 2166ms
4649 timing build Completed in 2166ms
4650 timing reify:build Completed in 2167ms
4651 timing reify:trash Completed in 6ms
4652 timing reify:save Completed in 242ms
4653 timing reify Completed in 15146ms
4654 timing command:install Completed in 19170ms
4655 verbose stack Error: command failed
4655 verbose stack     at ChildProcess.<anonymous> (/Users/star_coder/.nvm/versions/node/v20.12.1/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
4655 verbose stack     at ChildProcess.emit (node:events:518:28)
4655 verbose stack     at maybeClose (node:internal/child_process:1105:16)
4655 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
4656 verbose cwd /Users/star_coder/test2
4657 verbose Darwin 21.6.0
4658 verbose node v20.12.1
4659 verbose npm  v10.5.0
4660 error code 1
4661 error path /Users/star_coder/test2
4662 error command failed
4663 error command sh -c nuxt prepare
4664 verbose exit 1
4665 timing npm Completed in 19412ms
4666 verbose code 1
4667 error A complete log of this run can be found in: /Users/star_coder/.npm/_logs/2024-04-05T12_09_27_221Z-debug-0.log
```

**Comment by manniL** [comment]
Removing the `/Users/star_coder/node_modules/` should resolve the problem.
