### ISSUE TITLE
Empty runtimeConfig.nitro.envPrefix breaks public runtime config

### ISSUE THREAD

**Issue by volk234** [nuxt/nuxt#26664]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.17.1
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  pnpm@8.6.12
- Builder:          -
- User Config:      runtimeConfig
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

Define nuxt.config.ts like this:
```ts
export default defineNuxtConfig({
    runtimeConfig: {
        public: {
            apiUrl: process.env.API_URL || 'http://localhost:8000',
            frontendUrl: process.env.FRONTEND_URL || 'http://localhost:3000',
            vapidPublicKey: process.env.VAPID_PUBLIC_KEY,
        },
        nitro: { envPrefix: '' },
    },
});
```

Log public runtime config:
```ts
console.log(useRuntimeConfig().public);
```

It becomes `"C:\\Users\\Public"`

### Describe the bug

Empty runtimeConfig.nitro.envPrefix breaks public runtime config

**Comment by danielroe** [comment]
This is the reason we added an `envPrefix` in the first place. Windows has a `PUBLIC` environment variable that would otherwise overwrite the entire public runtimeConfig.
