### ISSUE TITLE
[uncaughtException] proxyReq.appendHeader is not a function

### ISSUE THREAD

**Issue by ash-p-uk** [nuxt/nuxt#26662]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.2.0`
- Nuxt Version:     `3.11.2`
- CLI Version:      `3.11.1`
- Nitro Version:    `2.9.6`
- Package Manager:  `npm@8.9.0`
- Builder:          `-`
- User Config:      `alias`, `css`, `devtools`, `modules`, `ssr`, `ui`
- Runtime Modules:  `@nuxt/ui@2.15.1`, `@pinia/nuxt@0.5.1`, `@nuxtjs/google-fonts@3.2.0`
- Build Modules:    `-`

### Reproduction

I noticed this error on a project that I have begun working on, however I also tried a fresh install and get the same error. Another colleague also getting same error on their local machine.. Both using macOS 14.4.1

### Describe the bug

When running dev server, I get an error `[uncaughtException] proxyReq.appendHeader is not a function` on every page load

**Comment by yanhe0317** [comment]
Maybe you need to upgrade Node.js version.

**Comment by ash-p-uk** [comment]
Hi, thanks for the response. I had tried with Node v20 too before posting, however I just updated to v21 and it has resolved the issue, thanks

**Comment by yywangyu** [comment]
I also encountered the same problem but I updated the pnpm version to solve it
