### ISSUE TITLE
Deployment problems with Nuxt 3 - Tailwind - Netlify or vercel

### ISSUE THREAD

**Issue by Aklowa** [nuxt/nuxt#26673]
I used nuxt 3 for a project, and then during the deployment, when I run the `npx nuxi generate`, none of the images in the asset folder would display as well as the script codes, though they worked fine locally. I tried the `npm run build` and this was quite better. Just that swiper runs the first slide and then that is it. the rest of the images wouldn't show. Fontawesome never works when I run the two commands. When I tried deploying to Netlify, I get the first results. When i switched to vercel, when it runs the `npm run build` command, I get the first result; as in no images in the assets show, the codes in the script tags doesn't work. I tried to change the command to `npx nuxi generate`and i get the same results. In the browser, `Loading module from “https://aklowadrumz-ilx4-jm01tvghs-aklowa-drumzs-projects.vercel.app/aklowadrumz/assets/CAUEt-de.js” was blocked because of a disallowed MIME type (“text/html”)`.

Here is the configuration that I did in the nuxt.config.ts

`import { Static } from "vue";

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: process.env.NODE_ENV !== 'production' },
  ssr: true,
  target: Static,
  nitro: {
    preset: 'vercel',
    prerender: {
      routes: ['/', '/blog/history', '/blog/history', '/blog/dance', '/blog/acrobatics']
    }
  },
  app: {
    baseURL: '/aklowadrumz/', // baseURL: '/<repository>/'
    buildAssetsDir: 'assets',
    head: {
      title: 'Aklowa Drum Band',
      meta: [
            { name: 'viewport', content: 'width=device-width, initial-scale=1' }
        ],
        script: [{ src: 'https://identity.netlify.com/v1/netlify-identity-widget.js', defer: true }],
    }
},
build: {
  assetsDir: 'assets',
transpile: ['@fortawesome/vue-fontawesome'],
chunkSizeWarningLimit: 100000,
cssMinify: {
  preset: 'default',
},
},
postcss: {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
},
publicRuntimeConfig: {
  static: {
    publicPath: "/" // or a path relative to your domain (e.g., "/my-app/")
  }
},
// publicPath: process.env.npm_lifecycle_event === 'generate' ? '/pwa/' : '/_nuxt/',

optimization: {
  splitChunks: {
    name: true,
  },
  runtimeChunk: true,
},

splitChunks: {
  layouts: true,
  pages: true,
  commons: true,
},

    modules: [
      '@hypernym/nuxt-gsap',
      '@nuxtjs/tailwindcss',
      'nuxt-purgecss',
      '@nuxtjs/eslint-module',
      'nuxt-swiper',
      "@nuxt/image"
    ],
  tailwindcss: {
    cssPath: ['~/assets/css/tailwind.css', { injectPosition: "first" }],
    configPath: 'tailwind.config',
    exposeConfig: {
      level: 2
    },
    config: {},
    viewer: true,
  },
  css: [
    '@fortawesome/fontawesome-svg-core/styles.css',
    '~/assets/css/tailwind.css'
    ],
})`

and here is the package.json
`{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^6.5.2",
    "@fortawesome/free-brands-svg-icons": "^6.5.2",
    "@fortawesome/free-solid-svg-icons": "^6.5.2",
    "@fortawesome/vue-fontawesome": "^3.0.6",
    "@hypernym/nuxt-gsap": "^2.4.2",
    "@nuxt/image": "^1.5.0",
    "@nuxtjs/pwa": "^3.3.5",
    "@tailwindcss/typography": "^0.5.12",
    "gh-pages": "^6.1.1",
    "gsap": "^3.12.5",
    "nuxt": "^3.11.1",
    "nuxt-swiper": "^1.2.2",
    "swiper": "^11.1.0",
    "vue": "^3.4.21",
    "vue-router": "^4.3.0"
  },
  "devDependencies": {
    "@nuxtjs/eslint-module": "^4.1.0",
    "@nuxtjs/tailwindcss": "^6.11.4",
    "autoprefixer": "^10.4.19",
    "eslint": "^8.57.0",
    "eslint-plugin-vue": "^9.24.0",
    "nuxt-purgecss": "^2.0.0",
    "postcss": "^8.4.38",
    "sass": "^1.72.0",
    "tailwindcss": "^3.4.3"
  }
}
`

**Comment by RyanClementsHax** [comment]
Could you provide a complete reproduction repo? It will be hard reproducing with just this information.

I've already started creating one for you here https://codesandbox.io/p/devbox/nuxt-26673-prerendering-deployment-snjp23

I unfortunately wasn't able to reproduce any of the issues you've mentioned and won't be able to reproduce any of the issues below as I couldn't create a reproduction from the information given alone.

> none of the images in the asset folder would display as well as the script codes, though they worked fine locally

> Just that swiper runs the first slide and then that is it. the rest of the images wouldn't show

> Fontawesome never works when I run the two commands.

> Loading module from “https://aklowadrumz-ilx4-jm01tvghs-aklowa-drumzs-projects.vercel.app/aklowadrumz/assets/CAUEt-de.js” was blocked because of a disallowed MIME type (“text/html”)
