### ISSUE TITLE
v-if does not work with useAsyncData

### ISSUE THREAD

**Issue by ValentinFunk** [nuxt/nuxt#26683]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-zdl7ze?file=pages%2Findex.vue

### Describe the bug

I'm new to Vue/Nuxt and maybe this is something really obvious but I'm seeing something that makes no sense to me:

<img width="515" alt="image" src="https://github.com/nuxt/nuxt/assets/337968/159bebd0-27df-4670-87c9-82e60236db83">

The red container has an `v-if="data.pending"` on it. My understanding is that this should mean the element is hidden when the value is false. That does not happen, I can see the `false` value rendered **inside** the element. 

The code is very small:

```ts
<script setup lang="ts">
const data = useAsyncData('test', async () => {
  return 'test';
});
</script>

<template>
  <div style="background: red" v-if="data.pending">
    Pending is: {{ data.pending }}, Data is: {{ data.data }}
  </div>
  <div style="background: red" v-if="false">This is false</div>
  <div style="background: green" v-if="true">This is true</div>
</template>
```

### Additional context

This happens locally (MacOS) and in stackblitz

**Comment by DamianGlowala** [comment]
Could you please check the reproduction link? It currently shows '404: Not Found'.

**Comment by ValentinFunk** [comment]
Hey sorry, it was set to private should work now @DamianGlowala

**Comment by DamianGlowala** [comment]
`data.pending` is a ref. You need to check for `data.pending.value`.

FYI, `pending` is going to be removed in favor of `status` (https://github.com/nuxt/nuxt/issues/25225). I would advice checking for `data.status.value === 'pending'` instead.

**Comment by ValentinFunk** [comment]
Thank you!
