### ISSUE TITLE
`loadNuxtConfig` does not populate `runtimeConfig` from `process.env`

### ISSUE THREAD

**Issue by rijenkii** [nuxt/nuxt#26684]
### Environment

```
------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, runtimeConfig
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Reproduction

https://stackblitz.com/edit/nuxt-starter-zru9z3?file=bin%2FcustomCmd.js&view=editor

### Describe the bug

I am trying to create a custom command that uses Nuxts `runtimeConfig` for configuration values. I am trying to use `loadNuxtConfig` for this purpose. It seems to correctly read `nuxt.config.ts`, however it does not read the environment nor the dotenv file.

### Additional context

```javascript
// bin/customCmd.js
import { loadNuxtConfig } from "@nuxt/kit";

console.log("process.env =", process.env);
console.log("runtimeConfig =", (await loadNuxtConfig({})).runtimeConfig);
```

### Logs

```shell-script
process.env = {
  COLORTERM: 'truecolor',
  TERM: 'xterm-256color',
  LSCOLORS: 'ExGxBxDxCxEgEdxbxgExEx',
  PATH: '/bin:/usr/bin:/usr/local/bin',
  HOME: '/home',
  SHELL: '/bin/jsh',
  HISTFILE: '/home/.jsh_history',
  TMPDIR: '/tmp',
  CHROME_BIN: '/usr/local/bin/google-chrome',
  PWD: '/home/projects/nuxt-starter-zru9z3',
  NEXT_TELEMETRY_DISABLED: '1',
  ASTRO_TELEMETRY_DISABLED: '1',
  __NEXT_DISABLE_MEMORY_WATCHER: '1',
  NG_CLI_ANALYTICS: 'false',
  EDITOR: 'code',
  NUXT_TEST: 'hello'
}
runtimeConfig = {
  public: {},
  app: { baseURL: '/', buildAssetsDir: '/_nuxt/', cdnURL: '' },
  test: ''
}
```

**Comment by Buzut** [comment]
Same issue with Node 20.17.0 and Nuxt 3.13.2.

**Comment by danielroe** [comment]
We now have a new utility `useRuntimeConfig` (from nuxt/kit) that can access the resolved runtime config - and you can update it with the complementary `updateRuntimeConfig` util.

**Comment by Buzut** [comment]
@danielroe from what version is this available? Also the big benefit of `loadNuxtConfig` is that it can get the config outside of a Nuxt scope (and that's great for all sorts of things (db creation/migration is a good exemple).

From what I'm reading in the docs, `useNuxtapp` requires the complete Nuxt context.
> Since [useNuxtApp](https://nuxt.com/docs/api/composables/use-nuxt-app) throws an exception if context is currently unavailable, if your composable does not always require nuxtApp, you can use [tryUseNuxtApp](https://nuxt.com/docs/api/composables/use-nuxt-app#tryusenuxtapp) instead, which will return null instead of throwing an exception.

**Comment by danielroe** [comment]
from 3.14+

**Comment by Buzut** [comment]
Thanks! I'll take a look. For those that need a quick access to the settings outside of a nuxt env, quick solution:

```js
global.defineNuxtConfig = (config) => config;

async function parseNuxtConfig() {
  const module = await import(path.resolve(configFile));
  return module.default;
}

const config = await parseNuxtConfig();
```

Note that this config object is as is, not augmented by the .env like the "real" object returned by `useRuntimeConfig()`. Although you can get these easily in a node script.
