### ISSUE TITLE
Request to Update @nuxt/test-utils-edge for Latest vitest Version Support

### ISSUE THREAD

**Issue by kumimaru2002** [nuxt/nuxt#26698]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.11.1
- CLI Version:      3.11.0
- Nitro Version:    2.9.4
- Package Manager:  npm@9.5.1
- Builder:          -
- User Config:      ssr, srcDir, app, imports, modules, components, dev, typescript, css, vite, runtimeConfig
- Runtime Modules:  nuxt-svgo@4.0.0, nuxt-typed-router@3.6.2
- Build Modules:    -
------------------------------

### Reproduction

Currently, @nuxt/test-utils-edge supports only older versions of vitest (^0.30.0, ^0.31.0, ^0.32.0, or ^0.33.0). However, vitest has been updated to version 1.4.0, leading to dependency conflicts when attempting to install or update packages in projects that use the latest version of vitest.

### Describe the bug

@nuxt/test-utils-edge should support the latest versions of vitest, allowing developers to use both packages together without encountering dependency conflicts.

I kindly request the developers of @nuxt/test-utils-edge to update the package to support the latest versions of vitest. This update would resolve the current dependency conflicts and facilitate a smoother development experience for projects utilizing both @nuxt/test-utils-edge and the latest vitest.

**Comment by danielroe** [comment]
The nightly release is now named `@nuxt/test-utils-nightly`.
