### ISSUE TITLE
The window._NUXT_ property initialization is happening too late, leading to the error "Cannot read properties of undefined(reading 'baseURL')" 

### ISSUE THREAD

**Issue by yunchuan123** [nuxt/nuxt#26690]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v16.20.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  pnpm@8.11.0
- Builder:          -
- User Config:      target, nitro, app, experimental, devtools, css, postcss, modules, vite, plugins, build
- Runtime Modules:  @element-plus/nuxt@1.0.8, @pinia/nuxt@0.5.1, @nuxtjs/tailwindcss@6.11.4
- Build Modules:    -
------------------------------

### Reproduction

**git repository**: https://github.com/yunchuan123/nuxt-issue

Pull this project to replicate the issue.
After generating, accessing the path "/abou-us" will result in an error being logged in the console.

### Describe the bug

![image](https://github.com/nuxt/nuxt/assets/76022317/3af17730-5c9b-4361-9f0d-e1cd5ea63f46)
The module imported in the first red box is attempting to read properties from 'window._NUXT_',but at this point _NUXT_ has not been initialized yet.

window._NUXT_ has initialized in the second box.

**Comment by yunchuan123** [comment]
<img width="937" alt="image" src="https://github.com/nuxt/nuxt/assets/76022317/c4766e60-6e07-4976-a451-348dd3fd6dd2">

**Comment by yunchuan123** [comment]
The module in the first red box is related to Vue, and the part accessing the "window._NUXT_" property is in the Vue runtime-dom.
However, this is not a Vue issue, but rather caused by _NUXT_ initializing too late. I'm just not sure why _NUXT_ is initialized later in this example?

**Comment by danielroe** [comment]
this was resolved in https://github.com/nuxt/nuxt/pull/27506
