### ISSUE TITLE
Routing to Nuxt page with multiple top-level divs on built project results in duplicate pages being rendered on one route/page

### ISSUE THREAD

**Issue by fisher60** [nuxt/nuxt#26706]
### Environment

Nuxt project info:                                                                          10:47:31 AM

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.10.0
- Nuxt Version:     3.10.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.5
- Builder:          -
- User Config:      devtools, css, modules, tailwindcss, app
- Runtime Modules:  @nuxtjs/tailwindcss@6.11.3, @nuxtjs/color-mode@3.3.2
- Build Modules:    -

### Reproduction

To reproduce the issue: 
1. run `nuxt build` on [this project](https://github.com/AbandonTech/abandontechsite/tree/demo/broken-about-page) (ensure you are on the dedicated branch that has this issue). 
2. Navigate to the `About` page
3. Navigate to any other page,
4. Navigate back to the `About` page, duplicate pages will be rendered on the app and will continue infinitely as long as you keep navigating.

(Currently the hosted version at https://demo.abandontech.cloud/ has this bug and I will refrain from updating it temporarily incase anyone would like to demo it live)
(working on creating a minimal reproduction)

This is reproducible on linux and windows, in docker, and after building from a github action.

### Describe the bug

I am unable to find the specific cause of this issue, but when navigating between a specific, problem `page` (the about page), then navigating away from this page, then navigating back to the problem page, other pages will be duplicated/embedded on the application. The application enters a broken state where navigating to other pages (using NuxtLink) results in each new page being rendered on the existing screen/application and infinitely expanding

To fix the issue, the contents of the about.vue page can be wrapped in a single `div`, making the component ClientOnly, or using a NuxtIsland.

### Additional context

The issue is only reproducible on the built version of the app. The issue is not observable when using `yarn dev` to run the project.

The hosted demo site complains about a hydration issue, but I have fixed the hydration issue and have confirmed the page duplication bug still exists.

Attached is an image of the expected result of navigating to the `About` page as well as the result of navigating away and back to the `About` page many times 

![image](https://github.com/nuxt/nuxt/assets/39353605/0048907c-b2bf-4964-b6ad-d9243dde6344)

![image](https://github.com/nuxt/nuxt/assets/39353605/1d5a639b-2f33-4039-816b-db6dca17ea1b)

### Logs

```shell-script
No logs or error output generated
```

**Comment by warflash** [comment]
Nuxt pages are required to only have a single top level element. See -> https://nuxt.com/docs/guide/directory-structure/pages#usage

**Comment by fisher60** [comment]
Thank you, I missed that in the pages documentation, but suspected as much due to my `React trauma`.

I would expect my console to be berated with warnings or for the application to outright error to prevent this issue. Or, as a last-resort for the output of `nuxt build` to scream warnings at me.
Especially since it is only observable on a built/deployed version of the app and not in dev.

**Comment by fisher60** [comment]
Also, out of my own curiosity, it seems that this error is only reproducible on some pages and if a page has a certain number of elements or a specific amount of content. Would anyone happen to know why this is the case?

**Comment by danielroe** [comment]
As pointed out by @warflash, this is a documented limitation of Nuxt pages.

**Comment by aku12138** [comment]
> Also, out of my own curiosity, it seems that this error is only reproducible on some pages and if a page has a certain number of elements or a specific amount of content. Would anyone happen to know why this is the case?

I'm also experiencing this issue, where the top is SSR-rendered and the bottom is CSR-rendered. It doesn't happen on subdomains, only on the main domain,  For now, I've temporarily solved it by using:
<ClientOnly>
    <NuxtLayout>
      <NuxtPage />
    </NuxtLayout>
  </ClientOnly>
This forces everything to be CSR-rendered.

Have you resolved this issue?

**Comment by aku12138** [comment]
> Also, out of my own curiosity, it seems that this error is only reproducible on some pages and if a page has a certain number of elements or a specific amount of content. Would anyone happen to know why this is the case?

I'm also experiencing this issue, where the top is SSR-rendered and the bottom is CSR-rendered. It doesn't happen on subdomains, only on the main domain, For now, I've temporarily solved it by using:
<ClientOnly>
  <NuxtLayout>
    <NuxtPage />
  </NuxtLayout>
</ClientOnly>

This forces everything to be CSR-rendered.

Have you resolved this issue?
