### ISSUE TITLE
As long as you write nuxtPage, there will be a warning.

### ISSUE THREAD

**Issue by bbhxwl** [nuxt/nuxt#26715]
### Environment

{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@ant-design-vue/nuxt": "^1.4.1",
    "@element-plus/nuxt": "^1.0.7",
    "@nuxt/devtools": "latest",
    "@nuxtjs/device": "^3.1.1",
    "@pinia-plugin-persistedstate/nuxt": "^1.2.0",
    "@pinia/nuxt": "^0.5.1",
    "@types/three": "^0.163.0",
    "@vant/nuxt": "^1.0.4",
    "dayjs-nuxt": "^2.1.9",
    "nuxt": "^3.11.2",
    "vue": "^3.4.21",
    "vue-router": "^4.3.0"
  },
  "dependencies": {
    "@nuxt/ui-pro": "^1.1.0",
    "@vueuse/nuxt": "^10.9.0",
    "ant-design-vue": "^4.1.2",
    "element-plus": "^2.6.3",
    "jwt-decode": "^4.0.0",
    "mqtt": "^5.5.0",
    "pinia": "^2.1.7"
  }
}

### Reproduction

![image](https://github.com/nuxt/nuxt/assets/26525599/7257d413-1f56-4a9b-9a1c-5921c0ea1419)
![image](https://github.com/nuxt/nuxt/assets/26525599/37adb396-f461-493c-ab85-ee9c4a45d7da)

### Describe the bug

·As long as you write nuxtPage, there will be a warning.

**Comment by huang-julien** [comment]
Hi you have a hydration in your module/manage.vue component.

**Comment by bbhxwl** [comment]
> Hi you have a hydration in your module/manage.vue component.

I have 2 nested routes and only wrote one nuxtPage. I have resolved it. Thank you.
