### ISSUE TITLE
location header is not encoded

### ISSUE THREAD

**Issue by huang-julien** [nuxt/nuxt#26711]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.12.1
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  pnpm@8.14.1
- Builder:          -
- User Config:      typescript, pages, modules
- Runtime Modules:  ()
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-cbb3dz?file=pages%2Fredirection.vue,pages%2F[...slug].vue,pages%2Findex.vue

### Describe the bug

When redirecting to url with some special char (like `/cœur`), the location header is not encoded resulting into an ssr error

**Comment by deleteme** [comment]
Would calling `encodeURI` around the url that is _known_ to be containing special characters be enough?

```
await navigateTo(encodeURI('/cœur'));
```

Instead of assuming that every location isn't already correctly encoded.
