### ISSUE TITLE
resolveComponent does not work directly in templates: <o-button :tag="resolveComponent('NuxtLink')">

### ISSUE THREAD

**Issue by iamlaristo** [nuxt/nuxt#26729]
### Environment

- Operating System: Windows_NT
- Node Version:     v21.7.2
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  bun@1.1.3
- Builder:          -
- User Config:      devtools, plugins, css
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

I have a fresh Nuxt install with Oruga as component framework: https://github.com/oruga-ui/oruga
I used `<o-button tag="...">` component to add a link, it's basically just a dynamic component.

### Describe the bug

`<o-button tag="NuxtLink">` doesn't work because NuxtLink doesn't exist globally.
So I tried `<o-button :tag="resolveComponent('NuxtLink')">` which also doesn't seem to work because it's used directly in the template.

The following works:

```vue
<script setup>
const mylink = resolveComponent('NuxtLink');
</script>

<o-button :tag="mylink" to="/" variant="white">
  Dashboard
</o-button>
```

But this doesn't:
```vue
<o-button :tag="resolveComponent('NuxtLink')" to="/" variant="white">
  Dashboard
</o-button>
```

I don't understand why resolveComponent doesn't work in templates as it's written statically in the code.

**Comment by manniL** [comment]
Because it needs the component context. See the [Vue docs](https://vuejs.org/api/render-function)

> `resolveComponent()` must be called inside either setup() or the render function in order to resolve from the correct component context.
