### ISSUE TITLE
navigateTo makes a full-page refresh and causes an infinite redirect loop

### ISSUE THREAD

**Issue by GalacticHypernova** [nuxt/nuxt#26722]
### Environment

Default stackblitz environment

### Reproduction

https://stackblitz.com/edit/github-dkuqbf?file=app.vue,pages%2Findex.vue,pages%2Ftest.vue

### Describe the bug

Upon launching the reproduction, the callOnce block executes a single navigation to the /test page. From there it repeatedly redirects, until the browser short circuits the page, stating it has redirected too many times.

### Additional context

This does not happen when used with a regular useRouter().push

### Logs

```shell-script
No logs
```

**Comment by danielroe** [comment]
What is happening is:
1. on server, you are performing a redirect in `app.vue`. so this returns a `Location` header that asks browser to make a fresh request
1. this hits `app.vue` - repeat infinitely

This isn't a Nuxt issue.
