### ISSUE TITLE
Responses from two components using useAsyncData with different Props values are identical

### ISSUE THREAD

**Issue by MingDaJhong** [nuxt/nuxt#26727]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.12.1
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@8.19.2
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

You can check the link below:<br>
https://stackblitz.com/edit/github-57k4ba?file=components%2FFetchDataByProps.vue

### Describe the bug

When I pass different values into two separate components and use `useAsyncData` to call an API within each component, with the props' values passed into the useAsyncData key, I expect the responses in the two components to be different. However, the responses in both components end up being the same.

### Additional context

Using the useFetch method with `post` will also encounter the same issue, but there won't be this problem if the method is `get`.

**Comment by manniL** [comment]
Because you don't stringify the object, leading to `key_[Object Object]` being the key.

![image](https://github.com/nuxt/nuxt/assets/640208/bee86e23-2a28-4973-83ea-098b31ccbcd6)

**Comment by MingDaJhong** [comment]
I want to ask that initially, the values of props are all empty strings, and when useAsyncData uses the values in props as keys, it causes the response data of both components to be linked. I have thought of a solution to pass in a constant to differentiate or if there is a better way to solve this.

You can check the link below:
https://stackblitz.com/edit/github-57k4ba?file=components%2FFetchDataByProps.vue
