### ISSUE TITLE
firebase deployment failed: @css-inline/css-inline-darwin-arm64 EBADPLATFORM error

### ISSUE THREAD

**Issue by devcat-net** [nuxt/nuxt#26735]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v21.6.2
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      devtools, ssr, modules, site, i18n, nitro, plugins
- Runtime Modules:  @nuxtjs/tailwindcss@6.11.4, @nuxtjs/i18n@8.3.0, @nuxtjs/seo@2.0.0-rc.10
- Build Modules:    -
------------------------------

### Reproduction
_No reproduction link_

### Describe the bug

I want to deploy my Nuxt 3 application to firebase hosting. When I run `firebase deploy` I get following error:
```bash
Build failed with status: FAILURE and message: npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for @css-inline/css-inline-darwin-arm64@0.14.0: wanted {"os":"darwin","cpu":"arm64"} (current: {"os":"linux","cpu":"x64"})
npm ERR! notsup Valid os:   darwin
npm ERR! notsup Actual os:  linux
npm ERR! notsup Valid cpu:  arm64
npm ERR! notsup Actual cpu: x64
```
For setting everything up I used this tutorial from the nitro website: [Nitro Firebase](https://nitro.unjs.io/deploy/providers/firebase)

### Additional context

My package.json looks like this:
```js
{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare",
    "clean": "cd .output/server && rm -rf node_modules && npm i",
    "deploy": "NITRO_PRESET=firebase npm run build && npm run clean && firebase deploy"
  },
  "dependencies": {
    "vue": "^3.4.19",
    "vue-router": "^4.3.0"
  },
  "devDependencies": {
    "@nuxtjs/i18n": "^8.3.0",
    "@nuxtjs/seo": "^2.0.0-rc.9",
    "@nuxtjs/tailwindcss": "^6.11.4",
    "eslint": "^8.57.0",
    "firebase": "^10.10.0",
    "firebase-admin": "^12.0.0",
    "firebase-functions": "^4.9.0",
    "firebase-tools": "^13.7.1",
    "nuxt": "^3.11.2"
  }
}
```

### Logs
```bash
Build failed with status: FAILURE and message: npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for @css-inline/css-inline-darwin-arm64@0.14.0: wanted {"os":"darwin","cpu":"arm64"} (current: {"os":"linux","cpu":"x64"})
npm ERR! notsup Valid os:   darwin
npm ERR! notsup Actual os:  linux
npm ERR! notsup Valid cpu:  arm64
npm ERR! notsup Actual cpu: x64
```

**Comment by Chuiantw1212** [comment]
Work around available, painful though.
Delete the following code from .output/server/package.lock works for me.
<img width="519" alt="Screenshot 2024-05-15 at 8 10 32 AM" src="https://github.com/nuxt/nuxt/assets/10844438/5e603b4e-37d1-4f4d-aed6-61e27ec31753">

**Comment by danielroe** [comment]
Would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏

**Comment by davemg3** [comment]
Having similar issue with 2 packages attached to Nuxt-seo package https://nuxtseo.com/nuxt-seo/getting-started/what-is-nuxt-seo

                "@css-inline/css-inline": "0.14.1",
                "@resvg/resvg-js": "2.6.2",

When using Nitro server preset: firebase, it adds in .output/server 4 packages :

  "@css-inline/css-inline":"0.14.1",
@css-inline/css-inline-win32-x64-msvc":"0.14.1",
"@resvg/resvg-js":"2.6.2"
"@resvg/resvg-js-win32-x64-msvc"

with following error message :

i  functions: updating Node.js 20 (2nd Gen) function server(europe-west1)...
Build failed with status: FAILURE and message: npm error code EBADPLATFORM
npm error notsup Unsupported platform for @css-inline/css-inline-win32-x64-msvc@0.14.1: wanted {"os":"win32","cpu":"x64"} (current: {"os":"linux","cpu":"x64"})
npm error notsup Valid os:   win32
npm error notsup Actual os:  linux
npm error notsup Valid cpu:  x64
npm error notsup Actual cpu: x64

Theses errors stop the deployment. Do i need to open another issue?
Also similar to https://github.com/nuxt/nuxt/issues/21393 and https://github.com/nuxt/nuxt/issues/26735

**Comment by alexpilugin** [comment]
I have the same issue.
ChatGPT gave me an advice to add the optionalDependencies in package.json but it has not helped me.
  "optionalDependencies": {
    "@css-inline/css-inline-darwin-arm64": "0.14.1",
    "@css-inline/css-inline-darwin-x64": "0.14.1",
    "@resvg/resvg-js-darwin-arm64": "2.6.2",
    "@resvg/resvg-js-darwin-x64": "2.6.2"
  },

**Comment by davemg3** [comment]
@danielroe , is it better to open another issue or can this one be open again?

**Comment by danielroe** [comment]
Please open a new issue. Ideally, would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏

**Comment by davemg3** [comment]
@danielroe , ok it did... but i dont see how to reproduce the bug in stackblitz as the issue appear when deploying from a local host (win 32 ) to linux server. Otherwise it works locally...https://github.com/unjs/nitro/issues/2604

**Comment by danielroe** [comment]
@davemg3 Fantastic - thank you.

**Comment by marcosgomesneto** [comment]
I use the version "@nuxtjs/seo": "^2.0.0-rc.23".

I had the same problem, and in my case I needed to disable the nuxt seo ogImage in nuxt.config.ts:

```typescript
export default defineNuxtConfig({
...
ogImage: {
enabled: false,
},
```

I haven't researched deeply to find out the reason for the problem, but for now since I don't use ogImage, this works for now.
