### ISSUE TITLE
`routeRules` do not work in DEV mode for static files

### ISSUE THREAD

**Issue by xak2000** [nuxt/nuxt#26740]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      ssr, routeRules
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

In [this example](https://stackblitz.com/edit/nuxt-route-rules-dev?file=nuxt.config.ts) `/hello.txt` route should return `Content-type: application/json` header, and it does work in the PROD mode, but doesn't work in the DEV mode, where `Content-type: text/plain; charset=UTF-8` is returned.

#### public/hello.txt

```
World
```

#### nuxt.config.ts

```ts
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  ssr: false,
  routeRules: {
    '/hello.txt': {
      headers: {
        'Content-Type': 'application/json',
      },
    },
  },
});
```

#### app.vue

```vue
<script setup>
const contentType = ref();
const { data } = useFetch('/hello.txt', {
  onResponse({ response }) {
    contentType.value = response.headers.get('Content-Type');
  },
});
</script>

<template>
  <div>Data: {{ data }}</div>
  <div>Content-Type: {{ contentType }}</div>
</template>
```

### Describe the bug

When `nuxt.config.ts` contains a `routeRules` section that sets headers for a static file (from `public` dir), then these headers are not set when server is running in DEV mode (`npm run dev`). The headers are set, though, when server is running in PROD mode (`npm run build && node .output/server/index.mjs`).

### Additional context

The discussion was started in #22141 and this behavior was [marked as `bug`](https://github.com/nuxt/nuxt/issues/22141#issuecomment-2048388551) by @danielroe.

**Comment by gustavonikov** [comment]
yo, any update on this issue? I understand that is not a priority, since, the problem is in dev mode and does not affect our apps in production, but would be nice to be able to test any change on our headers in a development environment :)

**Comment by danielroe** [comment]
Would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏

**Comment by xak2000** [comment]
Thanks, Daniel.
It does reproduce in pure Nitro. Raised it as unjs/nitro#2749.
This issue could be closed now, or maybe keep it open to re-check if/when Nitro behavior is fixed.

**Comment by danielroe** [comment]
let's track there - thank you for investigating! ❤️
