### ISSUE TITLE
[Nuxt 3 SSR] Deliver only necessary styles

### ISSUE THREAD

**Issue by kasadawa** [nuxt/nuxt#26749]
### Discussed in https://github.com/nuxt/nuxt/discussions/26732

<div type='discussions-op-text'>

<sup>Originally posted by **kasadawa** April 11, 2024</sup>
I have a Nuxt 3  SSR with Vite, Less, which has 2 layouts and dynamic routes (using app/routes.options.ts). 

Currently when I load a page, all of the styles are being delivered, no matter that the component is being rendered or not.

Example: 

mainPage.vue
```
<template>
  <div>
     <p>Main Page</p>
     <sub-navigation v-if="false" />
     <left-navigation v-if="false" />
 </div>
</template>
<script setup>
...
</script>
<style lang="less">
... 
</style>
```
 contains subNavigation.vue, leftSideNavigation.vue, et. 
None of them are being rendered, due to conditioning, but their styles are being delivered in a separate files. (`npm run build`)
mainPage.[hash].css
subNavigation.[hash].css 
leftSideNavigation.[hash].css

Here is most of nuxt.config: 

```
export default defineNuxtConfig({
  devtools: { enabled: true },
  telemetry: false,
  ssr: true,
  features: {
    noScripts: true,
  },
  builder: 'vite',
  vite: {
    build: {
      // cssCodeSplit: false, // I was thinking of combining the styles to single file
    },
    css: {
      preprocessorOptions: {
        less: {
          additionalData: `
          @import "~/assets/less/variables.less";
        `,
          math: 'always',
        },
      },
    },
  }
  }); 
```
 
 Is there a way to deliver only the needed styles rather all of the styles from the nested child components ? 
 Before, in nuxt 2 it was possible, only the styles were inlined, not in a separeted files.
 
 </div>

**Comment by dsvgl** [comment]
You need to import them dynamically -> prepend your component names wit `Lazy`, eg.:
```
<LazySubNavigation v-if="false" />
<LazyLeftNavigation v-if="false" />
```

With Lazy, Nuxt uses vues `defineAsyncComponent`. It still creates these css chunks but won't include them in `mainPage.vue`.

**Comment by kasadawa** [comment]
Thanks, actually when I started reading about `Lazy` in the docs, I found out that there are server components and pages. When pages are made with `.server.vue` prefix, then only the used styles were delivered, without the child-component ones, which are not even called.
