### ISSUE TITLE
On route update, page component is unmounted instead of being updated

### ISSUE THREAD

**Issue by kuhma** [nuxt/nuxt#26753]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-4fzezm-lvwg5k

### Describe the bug

On route param update (e.g. /route/1 to /route/2), the target component is unmounted and mounted again instead of just being updated.

This used to work with Nuxt 2.

**Comment by CernyMatej** [comment]
I would say this is intended behaviour.

**Comment by kuhma** [comment]
Vue router seems to work the way I expect, as Nuxt 2 do:
https://stackblitz.com/edit/vue-ssr-mfm3n2

**Comment by danielroe** [comment]
This is intended behaviour, but you can customise it by passing a custom key (or key function) to `<NuxtPage>`: https://nuxt.com/docs/api/components/nuxt-page#props.

**Comment by kuhma** [comment]
I already tried setting a custom key long before filing this issue and it does not change anything.

I do not understand how a regression having a performance impact can be an intended behaviour.

**Comment by danielroe** [comment]
@kuhma Different people have different needs, in terms of whether a change of slug should result in reloading the page component. If it isn't working, it's a bug though. Would you provide a reproduction using the page key to show me what you're trying? 🙏
