### ISSUE TITLE
useCookie Cannot be set again after expiration

### ISSUE THREAD

**Issue by NaMoCv** [nuxt/nuxt#26765]
### Environment

- Operating System: Darwin
- Node Version:     v18.18.2
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  bun@1.1.3
- Builder:          -
- User Config:      devtools, ssr
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://github.com/NaMoCv/my-app

### Describe the bug

Cannot be set again after expiration.
console.log(identity.value)   ok
but document.cookie not found anything

**Comment by NaMoCv** [comment]
> https://github.com/NaMoCv/my-app
Sry, forgot to set it as a public project.

**Comment by awdr74100** [comment]
Are there any updates to this question?

#27389 
```vue
<template>
  <button
    type="button"
    class="px-3 py-2 border border-primary text-xl text-primary"
    @click="setCookie"
  >
    SET Cookie
  </button>
  <span>{{ locked }}</span>
</template>

<script setup lang="ts">
const locked = useCookie<boolean>('locked', {
  maxAge: 20,
  default: () => false
});

const setCookie = () => {
  locked.value = true;
};
</script>
```

After clicking the button to create a cookie, the cookie will expire after 20 seconds, after the expiration, clicking the button again will make the cookie expire immediately, the status of the cookie on the screen will flash, is this expected?

**Comment by leoosa** [comment]
Made PR #27632
