### ISSUE TITLE
URL will back to home when use Dynamic Routes and SSG and deploy with nginx

### ISSUE THREAD

**Issue by aimer-fan** [nuxt/nuxt#26764]
### Environment

- Operating System: Darwin
- Node Version:     v20.10.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  pnpm@8.15.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

1. use `pnpm dlx nuxi@latest init <project-name>` create a project
2. add `pages/[..slugs].vue`
``` vue
<template><div>Nuxt App</div></template>
```
3. run `pnpm run generate` command and move to dist folder to nginx root folder
4. set nginx.conf
```nginx
location / {
  try_files $uri $uri/ @router;
  index  index.html index.htm;
}

location @router {
  rewrite ^.*$ /index.html last;
}
```
5. visit `/foo`, browser will back to `/` path when nuxt app is ready

### Describe the bug

when you visit `/foo`, nginx will return the index.html, but the url will back to the `/` after nuxt app ready.

I found that `initialURL` will be override by `nuxtApp.payload.path`.

https://github.com/nuxt/nuxt/blob/fa79b86d4ab286c3c43735b5d589006e95d9182f/packages/nuxt/src/pages/runtime/plugins/router.ts#L72

so i add `useNuxtApp().payload.path = ''` to `app.vue`, it works.

Is there any other better way to solve this problem?

**Comment by NamesMT** [comment]
Bump, encountering this as an major issue in our upcoming internal app, there are dynamic routes that are sent by email and could not be accessed.

**Comment by danielroe** [comment]
The best solution here is to have nginx serve up `200.html` for unknown routes that have not been prerendered. (It's intended for that purpose.)
