### ISSUE TITLE
definePageMeta().path not compatible with static generation

### ISSUE THREAD

**Issue by jeannen** [nuxt/nuxt#26786]
### Environment

- Operating System: `Darwin`
- Node Version:     `v21.1.0`
- Nuxt Version:     `3.11.2`
- CLI Version:      `3.11.1`
- Nitro Version:    `2.9.6`
- Package Manager:  `npm@10.2.0`
- Builder:          `-`
- User Config:      `devtools`, `components`, `modules`, `site`, `runtimeConfig`, `app`, `image`, `css`, `content`, `metaTracking`, `sitemap`, `build`, `nitro`, `routeRules`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.11.4`, `@pinia/nuxt@0.5.1`, `@nuxt/content@2.12.1`, `@nuxt/image@1.5.0`, `nuxt-icon@0.6.10`, `nuxt-schema-org@3.3.6`, `@nuxtjs/sitemap@5.1.4`, `nuxt-og-image@3.0.0-rc.52`, `@nuxtjs/plausible@0.2.4`, `@nuxt/eslint@0.3.6`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-k6cb5d?file=pages%2Fapp%2Fnote-list.vue

### Describe the bug

Hey!

I first opened the issue [here](https://github.com/nuxt-modules/sitemap/issues/255) but I got told that I should open it here instead because it's a Nuxt issue

It seems like there is an issue when using the sitemap in combination with the `path` property of definePageMeta.

Instead of using the proper path, the sitemap is generated using the `/pages` files, even if they have a custom path.

For example, if I have `/app/note-list.vue` with a custom path to use it as the index of a folder (better for organization purposes):

```JS
    definePageMeta({
        path: '/app/',
    });
```

I will get the following error when generating the website while doing `npm run generate`. I think it might be because the generation switch to using the sitemap instead?

```
  ├─ /app/note-list (886ms)                                                                                                                                                             nitro 9:11:44 AM
  │ └── Error: [404] Page not found: /app/note-list
```

The issue seems to persists even when I exclude every page in `nuxt.config.ts`

```
 sitemap: {
        exclude: ['**'],
    },
```

I use NuxtSEO directly, so it might be another module maybe? As soon as I remove NuxtSEO it the issue is gone

**Comment by danielroe** [comment]
This sounds like it's a NuxtSEO issue. Would you be able to open it there? 🙏
