### ISSUE TITLE
It is expected that during the server-side rendering process, some way can be provided to modify the content of html

### ISSUE THREAD

**Issue by rainydayDY** [nuxt/nuxt#26790]
### Describe the feature

I am using nuxt2. I hope to provide some way to modify the content of html during the server-side rendering process. I hope to modify the insertion method of Script scripts and wrap all defer-form scripts with setTimeout(()=>{}, 0)

Reason: On low-end devices, the defer script will block the rendering of the first frame. It is guessed that the main thread is blocked. If you use setTimeout, you can split the synchronization task of the script into an asynchronous task, so as not to block the rendering of the first frame

### Additional information

- [ ] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by huang-julien** [comment]
Hi :wave: Maybe are you lookign for the `render:html` hook ?
https://nuxt.com/docs/api/advanced/hooks#nitro-app-hooks-runtime-server-side
