### ISSUE TITLE
Support Tailwind SSR Styling

### ISSUE THREAD

**Issue by sobbey99** [nuxt/nuxt#26794]
### Describe the feature

![Screenshot from 2024-04-15 22-07-06](https://github.com/nuxt/nuxt/assets/72673043/f0f150ac-3e27-4088-9f84-aff66a6b907d)
![image](https://github.com/nuxt/nuxt/assets/72673043/0c67aaa0-0599-426e-8b3a-c49df5ec0661)

Screenshots are from Next configuration and it supports prestyling on server side 

const nextConfig = {

  //...

  experimental: {

    optimizeCss: true, // enabling this will enable SSR for Tailwind

  },

};

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by sobbey99** [comment]
> Would you be able to provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
> More info


[Reproduction repository here](https://github.com/sobbey99/nuxt3-ssr-styling-reproduction)

**Comment by manniL** [comment]
@sobbey99 please provide a *minimal* reproduction without additional plugins or modules (except the tailwind module)

**Comment by sobbey99** [comment]
Just commited, actually only additional module is tailwind

> @sobbey99 please provide a _minimal_ reproduction without additional plugins or modules (except the tailwind module)

**Comment by Lehoczky** [comment]
@sobbey99 you need to add your server's source file paths to your tailwind config's content array, or use the `safelist` property.

See more at the official tailwind documentation: https://tailwindcss.com/docs/content-configuration
