### ISSUE TITLE
Nitro plugin `while loop` stucks server 

### ISSUE THREAD

**Issue by ElYaiko** [nuxt/nuxt#26809]
### Environment

- Operating System: Darwin
- Node Version:     v18.15.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  bun@1.1.3
- Builder:          -
- User Config:      devtools, app, runtimeConfig
- Runtime Modules: ()
- Build Modules:    -

### Reproduction

-

### Describe the bug

I have a simple plugin that reads a file and runs some code periodically.

````
const task = () => {
  while (1){
    // Reads file and runs code if data on it
  }
}

export default defineNitroPlugin(() => {
  task();
});
````

The `while` makes the server go stuck, is there an alternative to run a code like that in the server background without breaking the rest of the server?
Thanks.

**Comment by markthree** [comment]
@ElYaiko  you can use → [scheduled-tasks](https://nitro.unjs.io/guide/tasks#scheduled-tasks)

**Comment by huang-julien** [comment]
Hi :wave: nitro plugins are synchronous so making an infinite loop will stuck your server. As @markthree pointed out, there's a Nitro task API

**Comment by ElYaiko** [comment]
> Hi 👋 nitro plugins are synchronous so making an infinite loop will stuck your server. As @markthree pointed out, there's a Nitro task API

Crons doesn't work for me since this code runs async, so sometimes can take more time.
Any suggestion to running this kind of background task without interfering the server runtime?
