### ISSUE TITLE
Dynamic component loader not showing up

### ISSUE THREAD

**Issue by zaalbarxx** [nuxt/nuxt#26824]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

but also Windows

### Reproduction

https://stackblitz.com/edit/nuxt-starter-uvnsdy?file=app.vue,components%2FLazy.vue,layouts%2Fdefault.vue,pages%2Findex.vue,components%2FLoader.vue

### Describe the bug

In the reproduction repo there are two buttons which trigger dynamic (lazy) load of components. I would assume that both of the solutions would correctly trigger one of loading states (either `fallback` slot in `Suspense` component or `loadingComponent` when using `defineAsyncComponent`). Meanwhile it does not trigger any of it and only ocasionally shows them up during hot reload. I am not sure if this is a bug or correct behavior.

The thing is I would like some kind of global overlay with loading status to show up during waiting for some modal or side panel gets loaded (quite standard thing, I think). So the issue is that when I simulate slow network or just use this timeouts to simulate long load of component I cannot get this to work correctly. For reference this is example Vue project which properly loads the component with loader status:
https://stackblitz.com/edit/vue3-vite-typescript-starter-hn8dyy?file=src%2Fcomponents%2FHelloWorld.vue,src%2FApp.vue

### Additional context
I found this issue https://github.com/nuxt/nuxt/issues/15648, but I don't quite understand why the provided repo does not work correctly anyway. I get it that `NuxtPage` component wraps all the content inside `<Suspense>` tag, but there is also an "outer" suspense in `app.vue` which should work. Also I'd assume that since the `<Suspense>` wraps `<NuxtPage>` content I could just do something like

```
<template>
<NuxtPage>
<NuxtLoadingIndicator />

<LazySomeComponent v-if="displayComponent" />
</NuxtPage>
```
and then `NuxtLoadingIndicator` would "catch" load of async component (since it is in Suspense context) and display this indicator on the page (which also does not happen).

**Comment by huang-julien** [comment]
Hello you have to move the `v-if` to the `Suspense` component
