### ISSUE TITLE
extendPages is called twice in module (Nuxt > 3.8)

### ISSUE THREAD

**Issue by ilyamsts** [nuxt/nuxt#26822]
### Environment

Operating System: Ubuntu
Node Version: v20.9.0
Nuxt Version: 3.11.2
Nitro Version: 2.9.6

### Reproduction

https://stackblitz.com/edit/github-jhhj19?file=modules%2Fmodule.js

### Describe the bug

**extendPages** is called twice when to use it in modules in Nuxt > 3.8. But in 3.8 and lower version called only once.

**Comment by huang-julien** [comment]
Hey :wave: 

So build time hooks must be free of any side effect, consider each time it is called that you have a fresh array of pages. 
Some features needs hooks to be called multiple time to work.
When it is possible, we tries to call build-time hooks only once but sometimes we don't really havea choice. We can probably document that.

**Comment by ilyamsts** [comment]
closed

**Comment by BatthewZ** [comment]
I think I'm also having this issue, but I could be mistaken. I noticed it when setting up custom routing rules either in nuxt.config.ts as `hooks: {"pages:extend"}` or in a separate custom module calling the extendPages function.

More specifically, though, it seems to happen when I include a custom catchall page with the path "/:pathMatch([^/]*)", which inadvertently tries to catch "/_nuxt/"
