### ISSUE TITLE
vant declare is incorrect (>= 3.7.0)

### ISSUE THREAD

**Issue by decba78b** [nuxt/nuxt#26830]
### Environment

- Operating System: Windows_NT
- Node Version:     v16.14.2  
- Nuxt Version:     3.7.0     
- CLI Version:      3.11.1    
- Nitro Version:    2.9.6     
- Package Manager:  pnpm@8.10.3
- Builder:          -
- User Config:      modules
- Runtime Modules:  @vant/nuxt@1.0.4
- Build Modules:    -

### Describe the bug

using nuxt@3.7.0, `showToast` will be imported by `vant.cjs`, like this
`const showToast: typeof import('../../node_modules/.pnpm/vant@4.8.11_vue@3.4.23/node_modules/vant/lib/vant.cjs')['showToast']`
I try nuxt@3.6.5, `showToast` will be imported by `vant`
`const showToast: typeof import('vant')['showToast']`
nuxt@3.6.5 is the correct one, how can I make it correct?

**Comment by decba78b** [comment]
this one is the correct one
https://stackblitz.com/edit/wknrpzx0iu
this one is incorrect
https://stackblitz.com/edit/mbteiq

**Comment by decba78b** [comment]
@warflash please check this

**Comment by warflash** [comment]
Bumping nuxt/deps does the trick https://stackblitz.com/edit/mbteiq-tbkqox?file=app.vue,package.json,nuxt.config.ts,package-lock.json
