### ISSUE TITLE
String interpolation in dynamically added layout prevents app starting

### ISSUE THREAD

**Issue by russellbrown** [nuxt/nuxt#26838]
### Environment

- Operating System: Linux
- Node Version:     v20.9.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  ~/modules/interpolation/index
- Build Modules:    -

### Reproduction

https://codesandbox.io/p/devbox/crazy-almeida-5j8nyd

### Describe the bug

String interpolation (`${}`) within a dynamically added layout (i.e. via `addLayout`) seems to prevent the application from starting, even if commented out.  Appears to be identical to #23118 which was closed without a reproduction.

For clarity I'll just recap all the steps I took to demonstrated this in the reproduction:

We create a custom module which dynamically adds a page and a layout:

```ts
// /modules/interpolation/index.ts
import {
  defineNuxtModule,
  extendPages,
  addTemplate,
  addLayout,
} from "@nuxt/kit";
import { resolve } from "pathe";

export default defineNuxtModule({
  setup() {
    extendPages((pages) => {
      pages.push({
        name: "index",
        path: "/",
        file: resolve(__dirname, "./pages/index.vue"),
      });
    });

    const defaultTemplate = addTemplate({
      src: resolve(__dirname, "./layouts/default.vue"),
      write: true,
    });
    addLayout(defaultTemplate, "default");
  },
});

```

And of course add it to our Nuxt config:

```ts
// nuxt.config.ts
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: ["~/modules/interpolation/index"],
});
```

The layout contains string interpolation which causes the app not to start, with console error `Error compiling template.... Could not compile template... [VARIABLE] is not defined`, although string concatenation is fine.  It doesn't make any difference whether the interpolation is at the top level of the setup function or inside another function, async or otherwise or even whether such a function runs - the error happens even if the line is commented out:

```vue
// /modules/interpolation/layouts/default.vue
<template>
  <slot />
</template>

<script setup>
const does = "does";
console.log(`Interpolation ${does} not work in a dynamically added layout`); // remove this line for the app to run
console.log("Concatenation " + does + " work in a dynamically added layout");
</script>
```

Interpolation seems to work fine in a page though:

```vue
// /modules/interpolation/pages/index.vue
<template>
  <div>
    <p>See README.md</p>
  </div>
</template>

<script setup>
definePageMeta({
  layout: "default",
});
const does = "does";
console.log(`Interpolation ${does} work in a dynamically added page.`);
</script>
```

### Additional context

I'm not sure if it is related but hot module replacement (HMR) doesn't seem to work with dynamically added layouts either, although it works with with dynamically added pages.

**Comment by adrianpdm** [comment]
I also encountered this issue on `addPluginTemplate`. Looking at the code, anything that involves `@nuxt/kit` `compileTemplate`, e.g. `addPluginTemplate, addLayout, addTemplate, addTypeTemplate, ...` may break once it has `${}`.
That is due to the underlying `lodash-es/template` used in compiling the template. 

https://github.com/nuxt/nuxt/blob/3a1137e2b8fdf0e0138e7ce891f6fc5655e943e0/packages/kit/src/internal/template.ts#L3-L17

Unfortunately, `lodash.template` doesnt support escaping ES template literal either. There's solution to that lodash issue as suggested [here](https://github.com/lodash/lodash/issues/399), but nuxt seems to not expose a way to change its interpolation delimiter

I guess we're left with traditional string concat for now.
