### ISSUE TITLE
Transition of page change poisition of components

### ISSUE THREAD

**Issue by suchorski** [nuxt/nuxt#26836]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.12.1
- Nuxt Version:     ^3.11.2
- CLI Version:      3.11.1
- Nitro Version:    -
- Package Manager:  pnpm@8.15.6
- Builder:          -
- User Config:      devtools, ssr, app
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Online version: https://nuxtbug.netlify.app
Project: https://github.com/suchorski/nuxt-bug

### Describe the bug

When changing page with transition changes the <slot /> position when have a component on bottom of <slot />

**Comment by huang-julien** [comment]
I'm pretty sure that an issue has already been opened but i can't find it.

I think this has something to do with Suspense ?
cc @danielroe
