### ISSUE TITLE
Compatibility issues between @nuxt/kit and Node.20

### ISSUE THREAD

**Issue by RosarioAleCali** [nuxt/nuxt#26841]
### Environment

- Operating System: Darwin
- Node Version:     v20.12.2
- Nuxt Version:     ^3.11.2
- CLI Version:      3.11.1
- Nitro Version:    -
- Package Manager:  yarn@1.22.22
- Builder:          -
- User Config:      app, css, postcss, sourcemap, modules, proxy, pages, ssr, telemetry, runtimeConfig, nitro, typescript
- Runtime Modules:  @pinia/nuxt@^0.5.1, nuxt-proxy@^0.4.1
- Build Modules:    -

### Reproduction

- Install node.js 20
- Run `yarn`

### Describe the bug

Whenever I try to install my node modules using yarn, I get the following error message:
```
yarn install v1.22.22
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error @nuxt/kit@3.1.1: The engine "node" is incompatible with this module. Expected version "^14.16.0 || ^16.10.0 || ^17.0.0 || ^18.0.0 || ^19.0.0". Got "20.12.2"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I could get around it by running `yarn install --ignore-engines`, however that feels a bit hacky.

Somebody made an [https://github.com/nuxt/nuxt/issues/20445](issue) a while ago, perhaps we can extend that fix to cover this?

**Comment by manniL** [comment]
This should be fixed in a newer kit version - https://github.com/nuxt/nuxt/blob/7adb7d82daf4765557438ff13d6266f54f8f8cf9/packages/kit/package.json#L60

**Comment by RosarioAleCali** [comment]
@manniL How do I use a newer one? My installation fails the same way even if I run `npx nuxi upgrade --force`.

I've also tried cleaning my `node_modules` and `yarn.lock`.
