### ISSUE TITLE
$fetch error on Response.blob()

### ISSUE THREAD

**Issue by Dominic-Marcelino** [nuxt/nuxt#26843]
### Environment

- Operating System: Darwin
- Node Version:     v18.19.1
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  pnpm@8.15.4

### Reproduction

https://stackblitz.com/edit/github-xzcnqt?file=app.vue,nuxt.config.ts

### Describe the bug

When using $fetch instead of the native fetch `Response.blob()` creates an error:
`TypeError: r2.blob is not a function`

### Additional context

For reference the function of the directus sdk which is used in the demo:
https://github.com/directus/directus/blob/d37a16a31ebd201ef884bf30994366b95b156458/sdk/src/rest/commands/read/assets.ts#L33-L44

**NOTE:** The function `readAssetArrayBuffer` (directy below) which does the same for arrayBuffers works as expected. Therewith I assume it's something about blobs.

**Comment by danielroe** [comment]
Would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose) or in https://github.com/unjs/ofetch ? 🙏

**Comment by Dominic-Marcelino** [comment]
Thanks for getting back!

> Would you see if you can reproduce this in pure Nitro
As this example is with CSR I assume this is independent of nitro or am I wrong?

Should I open an issue in ofetch in that case?

**Comment by danielroe** [comment]
Yes, that would make sense ❤️

**Comment by danielroe** [comment]
Great - thank you for doing that. Let's track there. 🙏
