### ISSUE TITLE
Calling onBeforeRouterLeave inside components triggers a vue-router error

### ISSUE THREAD

**Issue by m-shum** [nuxt/nuxt#26861]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.9.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.1.0
- Builder:          -
- User Config:      css, image, modules, devtools, sanity, vite
- Runtime Modules:  @pinia/nuxt@0.5.1, @nuxtjs/sanity@1.11.0, @nuxt/image@1.5.0, nuxt-lenis@1.1.0
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-mrizpf-sp9jw2?file=app.vue,layouts%2Fdefault.vue,pages%2Findex.vue,pages%2Ftest.vue,components%2FNav.vue

### Describe the bug

Calling onBeforeRouterLeave() inside a component generates the following error:

```

[Vue Router warn]: No active route record was found when calling `onBeforeRouteLeave()`. Make sure you call this function inside a component child of <router-view>. Maybe you called it inside of App.vue?

```

**Comment by m-shum** [comment]
Just realised you're supposed to import in-component navigation guards from 'vue-router'.

This would be a useful addition to the docs.

**Comment by danielroe** [comment]
The issue here is not where it's imported from but the fact that it needs to be within a page.
