### ISSUE TITLE
`<NuxtLink>` should scroll up when on same page as clicked page

### ISSUE THREAD

**Issue by MickL** [nuxt/nuxt#26879]
### Describe the feature

Right now when clicking on a link that is the same route as the current route nothing happens.

This is very confusing to the user, e.g. he clicks on "Contact" in the footer while already being on the contact page but nothing happens.

Instead it should at least scroll up the page to make the impression of a navigation.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
This is probably upstream vue-router behaviour rather than explicitly something Nuxt is doing. Would you see if you can reproduce on https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter, and if so raise in https://github.com/vuejs/router ? 🙏
