### ISSUE TITLE
Official API to consume SSE on client side

### ISSUE THREAD

**Issue by jd-solanki** [nuxt/nuxt#26877]
### Describe the feature

Hi 👋🏻 

I'm consuming Server-Sent Events in Nuxt from my FastAPI server. To handle SSE I've to write manual logic that parses the SSE data and prepares the whole string/json.

It'll be great if Nuxt can provide an official way to handle SSE.

I found [this](https://github.com/nuxt/rfcs/issues/36) but I guess its for Nuxt 2.

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by miosenpai** [comment]
[useEventSource](https://vueuse.org/core/useEventSource/) from VueUse may be helpful for your use case here.

**Comment by jd-solanki** [comment]
In my case, I'm consuming SSE via POST request.

There can be cases where we've to make a POST req that responds with SSE and it might include JSON and not just plain string.

Above is the same case with me. Hence, I'm raising this feq request.

---

Using AI solution in web are increasing so this will be great benefit 🤖

**Comment by danielroe** [comment]
I'm not sure we really need this built into Nuxt - it's pretty straightforward:

```ts
  const source = new EventSource('/your-endpoint')
  source.onmessage = (event) => {
    // access event.data
  }
```

This was how I initially implemented the dev logs plugin with SSE: [`96b8d40` (#25936)](https://github.com/nuxt/nuxt/pull/25936/commits/96b8d40f34ee1dd5f2d6accc2c00ed9534b2b967#diff-940d8d26749e7dc3985656618ad0bd0b1e069cf7595a754b5ecfa61493d51960R56-R62).

What kind of API would you be suggesting instead?

**Comment by jd-solanki** [comment]
EventSource is simple and we can use `useEventSource` from VueUse but things gets tricky when we have below:

> **There can be cases where we've to make a POST req that responds with SSE and it might include JSON and not just plain string.**

**Comment by danielroe** [comment]
I think it's probably outside the scope of what we should provide (e.g. POST req that receives SSE JSON back is very specific and sounds like a good opportunity for a user-land/module solution). But we can keep it open for a bit to see if there's demand.

**Comment by danielroe** [comment]
We discussed and think having an example in the Nuxt docs/examples/recipes would be really helpful. 👍

**Comment by kalil0321** [comment]
Hi @danielroe, I would like to contribute.

**Comment by danielroe** [comment]
@kalil0321 Wonderful! Feel free to open a PR to the docs 🙏

**Comment by sukbearai** [comment]
> useEventSource

Have you finished?

**Comment by kalil0321** [comment]
> Have you finished? 

Sorry i wasn’t able to work on this. If you would like to do it, you can.

**Comment by jd-solanki** [comment]
I'll submit PR by tomorrow

**Comment by jd-solanki** [comment]
#27422 is merged so we can close this

**Comment by TimGuendel** [comment]
Just wanted to say thank you - I had the exact same problem and the recipe in the docs works like a charm ✅
