### ISSUE TITLE
definePageMeta not working while extendPages from *.js files

### ISSUE THREAD

**Issue by ilyamsts** [nuxt/nuxt#26887]
### Environment

- Operating System: Ubuntu 20
- Node Version:     v20.10.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-vscyr6

### Describe the bug

While in "extendPages" to make a push a new object into "pages" array and pass in "file" option a path which refers to ***.js** file (which exports vue component):

```
extendPages(pages=>{
   pages.unshift({name:'AboutPage', path:'/about', file:'path_to_file/AboutPage/index.js'})
})
```
then not working any defenitions of layouts, middleware at definePageMeta() on this page. But the page itself working fine

**Comment by danielroe** [comment]
`definePageMeta` needs to be located in the file that is registered; it's not an _export_ that is re-exported by this:

```ts
import AboutPage from './components/AboutPage.vue';

export default AboutPage;
```
