### ISSUE TITLE
Can't serve app under subfolder

### ISSUE THREAD

**Issue by ryanweston** [nuxt/nuxt#26886]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.3.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  pnpm@8.6.2
- Builder:          -
- User Config:      routeRules, app, nitro, modules, css, content, mdc, fonts, colorMode, typescript
- Runtime Modules:  @nuxt/content@2.12.1, @nuxtjs/color-mode@3.4.0, @nuxt/fonts@0.6.1, @vueuse/nuxt@10.9.0
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-w6rohg?file=nuxt.config.ts

Builds work locally, deployment to Vercel does not.

### Describe the bug

URL's are correctly generated using the baseURL: `/docs/logo.svg`, however they are still served from the root directory as opposed to the base URL, resulting in a 404. The same applies to `/docs/_nuxt/` assets. 

Works fine with a local build, but not when deployed on Vercel.

### Additional context

Potentially related: https://github.com/unjs/nitro/issues/1348

_No response_

**Comment by danielroe** [comment]
Would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏

**Comment by JohannesPichlerSTRABAG** [comment]
any news here? facing the same problem serving over docker container on a docker-swarm network domain and app in a sub-path like:

my-domain.com/my-nuxt-app-1
my-domain.com/my-nuxt-app-2
my-domain.com/my-nuxt-app-3

**Comment by JohannesPichlerSTRABAG** [comment]
We found the solution in our case. May be related to that.
The nitro server itself expects to run and serves the app on a sub path, works fine.
If the kubernetes ingress is not set to have its base rewrite also on the sub-path, the two configurations do not match.
For us, setting the rewrite-target to the subfolder of the running app did the trick to serve correct.
![image](https://github.com/nuxt/nuxt/assets/142501518/dd8ac8a0-9569-40d7-acf8-d19aa9e548fb)

would be grate to add an additional option to the nuxt config to handle situations, where we can not access configurations, so set the deployments to root and then do not redirect the frontend to root, but stay on the sub-path
