### ISSUE TITLE
Netlify infinite 302 loop with query params & trailing slashes

### ISSUE THREAD

**Issue by abovedave** [nuxt/nuxt#26888]
### Environment

- Operating System: Netlify
- Node Version:      v18.20.2
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.5.0
- Builder:          -
- User Config:      nitro, devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

Repo: https://github.com/hrishikesh-k/zd-246130-2

**Test links:**

Works: https://zd-246130-2.netlify.app/post/1?foo=bar
Redirect loop triggered: https://zd-246130-2.netlify.app/post/1?foo=bar/

### Describe the bug

Dynamic routes which have trailing slashes & query params present trigger a redirect loop.

### Additional context

Occurs with `nitro.preset` = `netlify` and `netlify-edge` but **not** `netlify-builder`.

I tried to create a minimal reproduction with Nitro, but it seemed fine, so I suspect this is on the Nuxt side.

### Netlify support

Netlify support was kind enough to dig on this. Reply below:

> This is indeed a very strange issue.
> 
> I spent more than an hour debugging this and checking everything I could from our end, but the conclusion might not seem very satisfying. The TL;DR is that, this looks like a bug with Nuxt or its server engine Nitro (at least a bug specific to Netlify).
 > 
> Here's my minimal reproduction: hrishikesh-k/zd-246130-2 (github.com), which has been deployed here: https://zd-246130-2.netlify.app/. You can try going to the link: https://zd-246130-2.netlify.app/post/1 and experiment with query parameters like for your site. You'd see the same behaviour.
 > 
> Here's how everything is currently working on Netlify:
 > 
> * Request hits our servers
> * We match the request to the redirect rules generated by Nuxt (rewrite to the server function)
> * The function (generated by Nuxt) invokes Nuxt/Nitro server and tries to render the required content
> * If you add any log statements in the above SSR-page, you would see those logs appear in the function console when the page renders fine. However, in case of a redirect loop, it doesn't log anything (except the function duration and memory usage which indicates the successful invocation of a function). This means that, the function is getting invoked (I also confirmed that from our logs), but something is happening in Nuxt side of things which returns a 302.
> 
> Strangely, the issue exists with any query param that contains a trailing slash. So if you send a request to: https://zd-246130-2.netlify.app/post/1/?foo=2/&bar=1, it gets redirected to: https://zd-246130-2.netlify.app/post/1/?bar=1&foo=2/.
> 
> Unfortunately this investigation doesn't find any root cause or probably help you much, but this does look like an error with Nuxt side of things than Netlify.

**Comment by huang-julien** [comment]
let's track this in #26882
