### ISSUE TITLE
Remove timestamp from `_payload.json`

### ISSUE THREAD

**Issue by septatrix** [nuxt/nuxt#26881]
### Describe the feature

While investigating #26873 i noticed that many of the `_payload.json` files differed only in the last field which contains an integer. Based on the magnitude and value I immediate suspected it might be a valid unix-time and converting it revealed that it seems to be the time when the page was generated.

I do not know of any reason why these timestamps should exist. Removing them would somewhat automatic file deduplication (though it would still be better if #26873 could be resolved differently - I really like Nuxt but it does not seem feasible to use it for the planned project).
Furthermore the inclusion of the timestamps makes the builds non-reproducible which is another issue that should be resolved.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Added a comment on that discussion.

The field in question is `prerenderedAt` which tells you how recently the data was generated. If you want to remove this you can add a Nuxt plugin (`~/plugins/date.server.ts` or similar):

```ts
export default defineNuxtPlugin(nuxtApp => {
  delete nuxtApp.payload.prerenderedAt
})
```

**Comment by septatrix** [comment]
Thank you, is that field documented somewhere? I was unable to find any info about it or way to access it so I wonder why it is present

**Comment by danielroe** [comment]
We should probably add docs on the format of the Nuxt payload 👍
