### ISSUE TITLE
The document occurs error

### ISSUE THREAD

**Issue by coderew** [nuxt/nuxt#26896]
### Environment

https://nuxt.com/docs/getting-started/installation

### Reproduction

<img width="1305" alt="Xnip2024-04-23_10-18-12" src="https://github.com/nuxt/nuxt/assets/20498067/d6a8a7d3-dc94-4592-a26e-b78ed06ecf4b">

### Describe the bug

![Uploading Xnip2024-04-23_10-18-12.png…]()

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/23612.
