### ISSUE TITLE
auto custom mode for ssr or csr

### ISSUE THREAD

**Issue by sajadhzj** [nuxt/nuxt#26919]
### Describe the feature

hi guys , ssr project It takes a lot of resources from the servers so for seo should run project ssr now It must be functional when robots in site , render ssr and else render csr

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
This can be done in userland already. You can use [a custom nitro middleware](https://www.lichter.io/articles/nuxt3-dynamic-ssr-spa/#solution-3-a-custom-nitro-middleware) to set SSR to true or to false depending on your needs.
