### ISSUE TITLE
Response status code is returned as 200 on a 404 page

### ISSUE THREAD

**Issue by jay8t6** [nuxt/nuxt#26915]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.11.1
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://nuxtjs-boilerplate-ten-mauve.vercel.app/

### Describe the bug

Try to go to a sub page that doesnt exist, like /blah. The error page show up with 404 message, but you get a 200 on the network request.

### Additional context

Here's the repository that contains the boilerplate code:
https://github.com/jay8t6/nuxtjs-boilerplate

**Comment by jay8t6** [comment]
@danielroe sorry about that, it’s public now.

**Comment by manniL** [comment]
When using `ssr: false`, you cannot get "accurate" HTTP error codes because the serving platform is not aware if a site exists or not. So you either get *always* 404s or *always* 200s for all "non-prerendered" files.

**Comment by liaow-ww** [comment]
you can setResponseStatus, like this. 
![image](https://github.com/nuxt/nuxt/assets/115768717/ac2ec1d8-baf2-4797-b1e8-f21c09f708e4)

**Comment by manniL** [comment]
@liaow-ww But not if you don't have SSR - then you can't use `setResponseStatus` because there is no server which is setting a response 😋

**Comment by liaow-ww** [comment]
> @liaow-ww But not if you don't have SSR - then you can't use `setResponseStatus` because there is no server which is setting a response 😋

emm.. yes, i'm not noticed it sets `ssr:false`.

**Comment by jay8t6** [comment]
> When using `ssr: false`, you cannot get "accurate" HTTP error codes because the serving platform is not aware if a site exists or not. So you either get _always_ 404s or _always_ 200s for all "non-prerendered" files. Only Nuxt knows if a site "exists" or not but as Nuxt has no control of the server sending the results, it change the status code or headers.

yep, I realized after I opened this issue. Thanks for looking into this.
