### ISSUE TITLE
Typescript not picking up extended NuxtConfig interface when installing with pnpm

### ISSUE THREAD

**Issue by arnestaphorsius** [nuxt/nuxt#26921]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    -
- Package Manager:  pnpm@8.15.3
- Builder:          -
- User Config:      devtools, modules, ui, colorMode
- Runtime Modules:  @nuxt/ui@2.15.2
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-yurofm?file=package.json,nuxt.config.ts

### Describe the bug

When using a module, for example `@nuxt/ui`, and installing dependencies with `pnpm`, the extended type for NuxtConfig is not being picked up by Typescript (both `tsc` and `vue-tsc`). This leads to a type error in `nuxt.config.ts`: 
```
nuxt.config.ts:5:3 - error TS2353: Object literal may only specify known properties, and 'ui' does not exist in type 'InputConfig<NuxtConfig, ConfigLayerMeta>'.

5   ui: {
    ~~

Found 1 error in nuxt.config.ts:5
```

Additionally, I found that:
- the extended interface is present in `.nuxt/schema.d.ts`
- removing `node_modules` and reinstalling with `npm` will fix the error
- type casting the input parameter of `defineNuxtConfig` as `InputConfig<NuxtConfig>` will circumvent the issue, but requires me to add `c12` as a dependency

### Additional context

This is my first project using `pnpm`, but I decided to give it a go after I saw `nuxt` itself uses it. Because of that I was also surprised I did not find any other issues mentioning this. So perhaps this is a misconfiguration on my end, and people here know the answer straight away. But I decided to open a bug since I could easily reproduce the issue with Stackblitz.

**Comment by huang-julien** [comment]
hi :wave: can you try with a `--shamefully-hoist` install ?

**Comment by arnestaphorsius** [comment]
Hi @huang-julien! When I install with `--shamefully-hoist` it types correctly, so I reckon the error is in the `node_modules` struture of `pnpm`.

Any clue on why this happens? If I have to use that flag I probably just switch back to `npm`. Not really a problem, but I wonder if there's something to be fixed here.

**Comment by danielroe** [comment]
This is resolved in the latest version of Nuxt.

![CleanShot 2024-09-04 at 15 51 59@2x](https://github.com/user-attachments/assets/750d42da-9276-4c31-9356-0c4def011fca)

https://stackblitz.com/edit/github-yurofm-5kpdoa?file=nuxt.config.ts
