### ISSUE TITLE
Router params 'undefined' in server middleware

### ISSUE THREAD

**Issue by krisflajs** [nuxt/nuxt#26924]
### Environment

- Operating System: Darwin
- Node Version:     v20.12.1
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  pnpm@8.15.6
- Builder:          -
- User Config:      devtools, ssr, app, alias, css, modules, components, vite, runtimeConfig, supabase, i18n, tailwindcss, colorMode, formkit, imports
- Runtime Modules:  @vueuse/nuxt@10.9.0, @nuxtjs/eslint-module@4.1.0, @nuxtjs/supabase@1.2.0, @nuxtjs/i18n@8.3.0, @nuxt/ui@2.15.1, @pinia/nuxt@0.5.1, @formkit/nuxt@1.6.2
- Build Modules:    -

### Reproduction

[https://stackblitz.com/edit/github-nyobao-hs48va?file=server%2Fmiddleware%2Fconsole.ts](https://stackblitz.com/edit/github-nyobao-hs48va?file=server%2Fmiddleware%2Fconsole.ts)

### Describe the bug

When trying to access a route param in the API part (e.g. the `id` from `server/api/[id]/test.get.ts`) in the server middleware (e.g. `server/middleware/console.ts`), the params are always undefined, although they are then present in the actual event handler of the route.

**Comment by manniL** [comment]
The nitro middleware has now knowledge about "how the route resolves" and possible params.

**Comment by shide1989** [comment]
having the same issue. Having to create a utility handler to read the params in a simple middleware is a shame for Nuxt.

**Comment by shide1989** [comment]
took me 5min to get a standard API behaviour like, with zod validation through pattern matching with this method 
```typescript
// Workaround to capture path params from the event, because Nuxt/H3 doesn't pass them to the middleware.
const capturePathParams = (
  event: H3Event,
  pattern: string,
): Record<string, string> => {
  const pathParams: Record<string, string> = {};
  const path: string = event.path;
  const pathname = path.split('?')[0];
  const pathParts = pathname.split('/');
  const patternParts = pattern.split('/');
  pathParts.forEach((part: string, index: number): void => {
    if (patternParts[index].startsWith(':')) {
      pathParams[patternParts[index].slice(1)] = part;
    }
  });
  return pathParams;
};
```
