### ISSUE TITLE
Firefox no longer load Nuxt3 websit

### ISSUE THREAD

**Issue by msgpix** [nuxt/nuxt#26933]
### Environment

Any Nuxt3 project I could try really, but using Firefox. Other browsers seems unaffected though.

On my side I reproduced it with Firefox developer edition, 125.0b9, but colleagues reported to me that it also happen with a up-to-date standard Firefox — all tested under Mac OS X.

### Reproduction

Open a recent Firefox browser and go to https://nuxt.com/docs/getting-started/introduction (which uses Nuxt 3.11 at the time this report is provided)

### Describe the bug

This generate a 500 error with the following message:
```
error loading dynamically imported module: https://nuxt.com/_nuxt/e5HDipEK.js
```

![image](https://github.com/nuxt/nuxt/assets/109071162/a39a87e5-5c36-48de-a1dd-4b7eb03f4453)

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt.com/issues/1569.
