### ISSUE TITLE
NuxtLayout breaks v-model behaviour when used after any async statement

### ISSUE THREAD

**Issue by sharifzadesina** [nuxt/nuxt#26934]
### Environment

- Operating System: Linux
- Node Version:  v18.18.0
- Nuxt Version: 3.11.2
- CLI Version: 3.11.1
- Nitro Version: 2.9.6
- Package Manager: npm@10.2.3
- Builder: -
- User Config: devtools, modules
- Runtime Modules: @nuxt/content@2.12.1
- Build Modules: -

### Reproduction

Checkout the project on Stackblitz:
[https://stackblitz.com/edit/nuxt-starter-cjpm2f?file=app.vue](https://stackblitz.com/edit/nuxt-starter-cjpm2f?file=app.vue)
The input value should be 2, but it remains 1 if you remove the async statement or NuxtLayout, everything will be fixed.

### Describe the bug

It seems something happens in NuxtLayout that breaks v-model behavior *before mount* and prevent it from updating the value of input. if you don't use any async statement or NuxtLayout, everything works fine.

### Additional context

If you don't use v-model and use `:value` and `@input` instead or just print the variable value, everything works file, only v-model is broken.

**Comment by manniL** [comment]
FYI: This does not happen when awaiting a `setTimeout` Promise like this:

```vue
<template>
  <input v-model="a" />
  <p>{{ a }}</p>
</template>

<script setup lang="ts">
const a = ref(1);

const myFunc = async () => {
  await new Promise(r => setTimeout(r, 1000));
  a.value = 2;
};

onBeforeMount(() => {
  myFunc();
});
</script>
```

**Comment by sharifzadesina** [comment]
@manniL I don't know about timeouts, but when I have real AJAX calls in my application it happens.
I just tried to make example simple as possible so I used `nextTick()`

**Comment by huang-julien** [comment]
hey :wave:

`onBeforeMount` is treeshaken in ssr so `myFunc` won't be  called. You're probably looking for the `useAsyncData()` composable ?

Here Alex's video about it
https://www.youtube.com/watch?v=0X-aOpSGabA

I can't reproduce the v-model issue

**Comment by sharifzadesina** [comment]
@huang-julien Bro this bug has nothing to do with SSR, `onBeforeMount` should be called on client side and it should update the input value. As you can see on the provided project, only the input value is not changed and the variable itself is changed and printed value is valid.

**Comment by manniL** [comment]
@sharifzadesina can you repro it with something else than nextTick?

**Comment by sharifzadesina** [comment]
@manniL No, but in my own app, fetch calls also cause problems.

**Comment by manniL** [comment]
Then please provide a reproduction without `nextTick` ☺️
