### ISSUE TITLE
Nuxt 3 - Convert `404.html` file to `404.shtml` on `Cpanel` hosting

### ISSUE THREAD

**Issue by Noorani-MM** [nuxt/nuxt#26940]
### Describe the feature

Hi there,

I've recently encountered an issue where we create a file named `[404].vue` in the pages directory to create a custom page for **page not found**. The output is satisfactory as long as the `npm run dev` command is executed.

However, for developers like me who use the `npm run generate` command to generate the project output and place the contents of the _dist folder_ in the _public_html_ directory in cpanel, these settings **do not take effect** and display the general template set for cpanel.

After some investigation, I found that if the file name is changed from `404.html` to `404.shtml`, it **overrides** the default cpanel page and displays the desired output.

Therefore, I thought it would be great if in **_generate_** mode, error pages would be created in `*.shtml` format by default or there would be a **flag** (such as `npm run generate --cpanel` or `npm run generate --custom-errors=shtml`) when generating to make these settings.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
Besides an own script running after generate, You could use an own custom preset ([example of a simple preset here](https://github.com/unjs/nitro/blob/main/src/presets/github-pages.ts)) and create it via [`compiled`](https://github.com/unjs/nitro/blob/45ff175ec9ce962ddc8cbe67925bb2136279c80b/src/presets/service-worker.ts#L62-L100)
