### ISSUE TITLE
Uncaught SyntaxError when building Nuxt.js 3.11.2 with Webpack

### ISSUE THREAD

**Issue by konkarin** [nuxt/nuxt#26951]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.3
- Builder:          webpack
- User Config:      devtools, builder
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-x4yvog

### Describe the bug

I encountered this issue when upgrading from nuxt `3.10.3` to `3.11.2` on my local environment. This error did not occur with `3.10.3`.
As shown in the attached reproduction repository, the issue persists even when downgrading `nuxt` and `@nuxt/webpack-builder` to `3.10.3`, so the problem may not be limited to just those packages.

I would really appreciate any help or insights you could provide on resolving this.

### Logs

```shell-script
Uncaught SyntaxError: Invalid or unexpected token (at vendors-node_modules_webpack-hot-middleware_client_js_reload_true_timeout_30000_path_2F__webp-b4bdca.js:29:6)
```

**Comment by wattanx** [comment]
I found that setting `webpack-dev-middleware` to `7.0.0` or lower is a workaround.

https://stackblitz.com/edit/github-x4yvog-bvn5jq

**Comment by konkarin** [comment]
@wattanx
Thank you for providing the workaround. I really appreciate you taking the time.🥳

**Comment by danielroe** [comment]
This is highly likely to be an upstream issue in webpack-dev-middleware. Would you be able to open an issue with reproduction in https://github.com/webpack/webpack-dev-middleware ? 🙏

**Comment by wattanx** [comment]
I'm trying if I can reproduce this without nuxt.
Maybe it reproduces only when nitro is used.

nitro & webpack-dev-middleware
https://stackblitz.com/edit/github-yqcgdy

express & webpack-dev-middleware (not reproduced)
https://stackblitz.com/edit/github-mawhuh

Strangely, with nitro, the requested bundle is broken.

**Comment by konkarin** [comment]
Since `3.12.1`, the workaround using `webpack-dev-middleware` `7.0.0` no longer works 😭

https://stackblitz.com/edit/github-7zdkqz

**Comment by martinszeltins** [comment]
Just curious - is there any possible way for you to move away from webpack to vite?

**Comment by konkarin** [comment]
@martinszeltins 
I'm considering migrating to Vite, but at this moment, it is difficult for me to make the switch immediately. In the short term, I would like to continue using Webpack.

**Comment by danielroe** [comment]
Let's track in https://github.com/unjs/nitro/issues/2541. This seems to be a nitro bug. Thank you @wattanx for an excellent reproduction.
