### ISSUE TITLE
Cannot find module from node_modules

### ISSUE THREAD

**Issue by ps-20x** [nuxt/nuxt#26955]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.20.2`
- Nuxt Version:     `3.11.2`
- CLI Version:      `3.11.1`
- Nitro Version:    `2.9.6`
- Package Manager:  `npm@10.5.0`
- Builder:          `-`
- User Config:      `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

1. Checkout https://github.com/ps-20x/phpstorm-issues
2. Run `npm ci`
3. Open utils/createSitemapItem.ts
4. Import type shows an error

### Describe the bug

The following error is showing up:

>`Vue: Cannot find module @nuxtjs/sitemap/dist/runtime/types or its corresponding type declarations.`

### Additional context

Tried it in PHPStorm as well as in VSCode. The project is an almost plain project.

PHPStorm
![image](https://github.com/nuxt/nuxt/assets/126659880/2042b114-9e37-445e-80e9-8b5f30cf8a4e)

VSCode
![image](https://github.com/nuxt/nuxt/assets/126659880/bf931bb4-5718-4930-a833-ea9da85d8b38)

**Comment by danielroe** [comment]
This is an issue with the types in `@nuxtjs/sitemap`, not with Nuxt. Would you raise an issue there instead?

https://arethetypeswrong.github.io/?p=@nuxtjs/sitemap@5.1.4

**Comment by ps-20x** [comment]
> This is an issue with the types in `@nuxtjs/sitemap`, not with Nuxt. Would you raise an issue there instead?
> 
> https://arethetypeswrong.github.io/?p=@nuxtjs/sitemap@5.1.4

Thank you very much for getting back to me. I raised an issue in `@nuxtjs/sitemap` and linked it for reference.

**Comment by harlan-zw** [comment]
> This is an issue with the types in `@nuxtjs/sitemap`, not with Nuxt. Would you raise an issue there instead?
> 
> [arethetypeswrong.github.io/?p=@nuxtjs/sitemap@5.1.4](https://arethetypeswrong.github.io/?p=@nuxtjs/sitemap@5.1.4)

FYI these type issues are within all Nuxt modules so this is not relevant, see https://arethetypeswrong.github.io/?p=%40nuxt%2Ffonts%400.6.1

**Comment by danielroe** [comment]
It's a question for module authors, as to how they want to expose their types. Your answer is correct - if you want users to be able to import from `./dist` subpath this needs to be added to `exports` as a subpath export pattern.
