### ISSUE TITLE
Error with `dist` symlink with SST Ion

### ISSUE THREAD

**Issue by NamesMT** [nuxt/nuxt#26968]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.12.2
- Nuxt Version:     -
- CLI Version:      3.11.1
- Nitro Version:    -
- Package Manager:  pnpm@9.0.6
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

TBA

### Describe the bug

The `dist` symlink seems to have an additional `.` entry, that causes [SST Ion](https://github.com/sst/ion)'s `StaticSite` hashing step to errors out with an `EISDIR` error.

### Additional context

The error doesn't happen when using `.output/public`
This could be fixed on SST's side, just wanna bring attention to a weird inconsistent behavior between `dist` and `.output/public`, also would be amazing if we could disable `dist` symlinking altogether for a cleaner directory structure.

**Comment by danielroe** [comment]
Would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏

**Comment by NamesMT** [comment]
Hi Daniel, sorry for the missing of informations, I have forgot that I created this issue.

This cannot be reproduced in pure Nitro, as it is a `dist` symlink usage issue, detail below:

---
I have pin-point this error later that it is because of symlink usage.
I have created a `test` symlink that points to `.output/public` and it have the same issue.
Seems like symlink for some reason creates an extra `.` entry when using `glob` to scan all files in the directory,
This will later throw an error in `SST` because it calls `readFile` on `dist/.`, which resolves to the directory and not a file.

I think I will close this issue as it's a general issue of symlink/glob and not Nuxt specific.

**Comment by danielroe** [comment]
Would it help if we had an option to disable the creation of this symlink?

**Comment by NamesMT** [comment]
As written in `Additional context` , the error could be avoided simply by pointing to `.output/public` instead of `dist` (which Nuxt's CLI already recommends),
And the error is because of a weird interaction of `glob` and symlink, so it's not mandatory for Nuxt to implement a fix.

But as another issue/feat request, the ability to disable the creation of the symlink is definitely great to have and would reduce an unnecessary entry in the file directory.

Thanks a lot!
