### ISSUE TITLE
页面刷新 页面抖动

### ISSUE THREAD

**Issue by chuntaoXu** [nuxt/nuxt#26974]
### Environment

nuxt2

### Reproduction

https://xywl.itubang.com/ 地址请看

### Describe the bug

刚进入首页的时候以及首页刷新的时候 ，css部分样式 先出来了 css样式错乱 
<img width="1107" alt="image" src="https://github.com/nuxt/nuxt/assets/100253090/cfbc76db-61e8-4846-8ea6-931f0e06bbe8">
过了2秒后 数据请求回来正常显示了 
<img width="1083" alt="image" src="https://github.com/nuxt/nuxt/assets/100253090/4500a77c-65ce-4972-945e-f3f07258da3f">
请问是我需要css 占位吗？

**Comment by Dmytro-Tihunov** [comment]
Hey ! I would be good if you will use translator
