### ISSUE TITLE
static generating is removing invalid html, but not reporting when linting

### ISSUE THREAD

**Issue by pixelpaulaus** [nuxt/nuxt#26978]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.2
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.5.0
- Builder:          -
- User Config:      vite, css, modules, routeRules, nitro, delayHydration, colorMode, image, components, devtools
- Runtime Modules:  @nuxt/ui@2.15.2, @nuxt/image@1.6.0, @pinia/nuxt@0.5.1, nuxt-delay-hydration@1.3.3
- Build Modules:    -
------------------------------

### Reproduction

N/A

### Describe the bug

If i have any invalid HTML such as this....

```
<p>
text here
<ul>
<li>list item here</li>
<li>list item here</li>
</ul>
</p>
```

or this...

```
<p>
text here
<pre class="m-2 bg-gray-200 p-2">text here</pre>
</p>
```

the pre and ul/li tags within the p tag are invalid. And Nuxt Generate will just remove them. But it does report it at any stage to let me know. When running the Lint tool, it is not reported.

**Comment by danielroe** [comment]
To investigate the issue you reported, I would need a reproduction. Are you sure it's _Nuxt_ that is removing the invalid HTML, and not your browser?

But as for ensuring you produce valid HTML, I would recommend using https://github.com/nuxt-modules/html-validator.

**Comment by pixelpaulaus** [comment]
it actually removes the elements from the static HTML files generated ( so accessing directly the page URL ) , but not the JS files for Nuxt when you navigate to the page from another.

**Comment by danielroe** [comment]
I'll wait to see your reproduction 🙏

**Comment by danielroe** [comment]
closing for now - please feel free to provide a reproduction and I'll happily investigate 🙏
