### ISSUE TITLE
nuxt aos set options { once: true },  only show the animation on the first visit but not work when navigating to a page

### ISSUE THREAD

**Issue by yanggengzhen123** [nuxt/nuxt#26977]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.8.0
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.4
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      modules, aos, devtools, css, vite, app, imports, runtimeConfig, hooks, nitro, build
- Runtime Modules:  nuxt-aos@1.2.4
- Build Modules:    -

### Reproduction

https://wwwtest.uqiantech.com/

### Describe the bug

it will only show the animation on the first visit on every page (or again after a refresh), but when navigating to a page more than once it seems to remember that it already did the animation and is not doing the animation again. Probably something todo with how nuxt/vue is rendering the DOM.. Not sure if there is a fix for that problem

**Comment by Gruce** [comment]
Hello,

Seems working fine to me? How do you deal with the animation exactly? can you share your minimal reproduction code?
