### ISSUE TITLE
When opened in some browsers, it displays: undefined is not an object (evaluating'uc.matchAll'

### ISSUE THREAD

**Issue by zzy-life** [nuxt/nuxt#26982]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.12.2
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.5.0
- Builder:          -
- User Config:      app, site, robots, sitemap, devtools, ogImage, css, postcss, modules, build, vite
- Runtime Modules:  nuxt-icon@0.6.10, @nuxt/image@1.5.0, @nuxtjs/seo@2.0.0-rc.10
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/nuxt/nuxt/assets/68179477/c0ff6166-bd48-4c99-b868-f0a98de82672

### Describe the bug

undefined is not an object (evaluating'uc.matchAll'

**Comment by zzy-life** [comment]
#24229 类似问题

**Comment by markthree** [comment]
@zzy-life 可以临时使用 [nuxt-fix-ofetch](https://github.com/markthree/nuxt-fix-ofetch)
