### ISSUE TITLE
nuxt3 开发环境实现分片上传会 [unhandledRejection] write ECONNABORTED    

### ISSUE THREAD

**Issue by WZY1999428** [nuxt/nuxt#26996]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.20.2
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -

### Reproduction

import path from 'path'
import fs from "fs";
import formidable from 'formidable';
import { IncomingMessage } from 'node:http';
const STATIC_PATH = path.join(process.cwd(), "/public/files")
export default defineEventHandler(async e => {
    const info = await parseFile(e.node.req, "videos") as FileInfo;
    return info
})

type FileInfo = {
    file?: any,
    hash?: string,
    filename?: string,
    chunkHash?: string
}

function parseFile(req: IncomingMessage, uploadDir: string): Promise<{ [key: string]: any }> {
    return new Promise((resolve, reject) => {
        const form = formidable({
            uploadDir: path.join(STATIC_PATH, uploadDir)
        });
        form.once("error", (err) => {
            console.log(err);
        })
        form.parse(req, (err, fields, files) => {
            if (err) {
                reject(err);
                return;
            }
            const keys = Object.keys(fields) as string[];
            const info: { [key: string]: any } = {};
            if (keys.length > 0) {
                const len = fields[keys[0]] as [];
                for (let i = 0; i < len.length; i++) {
                    for (let k = 0; k < keys.length; k++) {
                        const d = fields[keys[k]];
                        info[keys[k]] = d ? d[0] : "";
                    }
                    const file = files.file;
                    if (file) {
                        const f = file[i];
                        const d = path.parse(file[i].filepath);
                        fs.renameSync(f.filepath, path.join(d.dir, info.chunkHash));
                        info.file = {
                            filepath: f.filepath,
                            size: file[i].size,
                        }
                    };

                }
            }
            resolve(info);
        });
    })
}

这是server代码 

<template>
    <div>
        <input type="file" id="file" @change="uploadFile">
    </div>
</template>
<script setup lang="ts">
async function uploadFile() {
    const file = document.querySelector("#file") as HTMLInputElement | null;
    if (file) {
        const flist = file.files || [];
        if (flist.length > 0) {
            const file = flist[0];
            createChunks(file).then(async chunks => {
                const str = chunks.map(item => item.hash).join("");
                const hash = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(str));
                const hasharr = Array.from(new Uint8Array(hash));
                const hex = hasharr.map(byte => byte.toString(16).padStart(2, '0')).join('');
                await upload(chunks.slice(0, 5), hex, file.name)
            })

        }
        file.value = "";
    }

}

function upload(chunks: Chunk[], hash: string, filename: string): Promise<Boolean> {
    function start(chunk: Chunk): Promise<Boolean> {
        return new Promise(async (r, j) => {
            const formd = new FormData();
            formd.append("file", chunk.file);
            formd.append("chunkHash", chunk.hash);
            formd.append("name", chunk.name as string);
            formd.append("hash", hash);
            formd.append("filename", filename);
            const { data, pending, error } = await useFetch("/api/files/upload", {
                method: "POST",
                body: formd
            });
        })
    }

    return new Promise((r, j) => {
        let count = 0;
        for (let i = 0; i < chunks.length; i++) {
            start(chunks[i]);
        }
    })
}

type Chunk = {
    file: Blob,
    hash: string,
    name: String,
    size: number
}
const chunkSize = 1024 * 1024 * 5;
async function createChunks(file: File): Promise<Chunk[]> {
    const len = Math.ceil(file.size / chunkSize);
    const chunks: Chunk[] = [];
    let start = 0;
    let end = chunkSize;
    for (let i = 0; i < len; i++) {
        const chunk = file.slice(start, end, file.type);
        const hash = await createHash(chunk);
        chunks.push({
            file: chunk,
            hash: `${i}-${hash}`,
            name: i.toString(),
            size: chunk.size
        });
        start += chunkSize;
        end += chunkSize
    }
    return chunks;
}
function createHash(file: Blob): Promise<string> {
    return new Promise((r: Function, j: Function) => {
        if (crypto.subtle.digest) {
            const reader = new FileReader();
            reader.onload = async (event) => {
                try {
                    if (event.target) {
                        const hash = await crypto.subtle.digest("SHA-256", event.target.result as BufferSource);
                        const hasharr = Array.from(new Uint8Array(hash));
                        const hex = hasharr.map(byte => byte.toString(16).padStart(2, '0')).join('');
                        r(hex);
                    }
                } catch (error) {
                    j(error)
                }
            }
            reader.readAsArrayBuffer(file)
        } else {
            j("浏览器不支持crypto.subtle.digest")
        }

    })
}

</script>
<style></style>
这是前端代码

### Describe the bug

你好我使用nuxt3 在开发环境 实现分片上传过程中上传多个分片文件时会出现 ERROR  [unhandledRejection] write ECONNABORTED                                                                                                                                     10:35:47  

  at afterWriteDispatched (node:internal/stream_base_commons:160:15)
  at writeGeneric (node:internal/stream_base_commons:151:3)
  at Socket._writeGeneric (node:net:962:11)
  at Socket._write (node:net:974:8)
  at doWrite (node:internal/streams/writable:411:12)
  at clearBuffer (node:internal/streams/writable:572:7)
  at Writable.uncork (node:internal/streams/writable:351:7)
  at connectionCorkNT (node:_http_outgoing:951:8)
  at process.processTicksAndRejections (node:internal/process/task_queues:81:21)  出现的频率很高，生产环境就不会出现这个问题

**Comment by cossssmin** [comment]
This is still an issue in `3.12.2`:

```
> nuxt dev --host

Nuxt 3.12.2 with Nitro 2.9.6                                          2:50:32 PM
                                                                      2:50:32 PM

              █▀▀▀▀▀▀▀██▀▀▀█▀██▀█▀▀▀▀▀▀▀█
              █ █▀▀▀█ ██▀▀ ▄█▀█▀█ █▀▀▀█ █
              █ █   █ █ █ ▄▀  ▄▄█ █   █ █
              █ ▀▀▀▀▀ █▀▄ █▀▄▀█▀█ ▀▀▀▀▀ █
              █▀▀███▀▀▀█ ▀█ ▀██▀███▀▀████
              ██▄▀▄▀▄▀█▀▀▄▀▀▀█ ▄▄▀▀  ▄ ▀█
              ██▄█▄▄█▀ ▄▀ ▄██ ▀▄▀▀▄█▄██ █
              █ █ ▄▄█▀▄▄▀ █▄█▄ █▀█▀█▀█ ▀█
              █ █  ▄ ▀▀▄▀ █ ▀▄▄▀▀▀▀ █ █▄█
              █▀▀▀▀▀▀▀█ ▄ █▀▀ █ █▀█ ▀▄█▀█
              █ █▀▀▀█ █▄   ▀▀█▀ ▀▀▀ ▀▀█▄█
              █ █   █ ██ ▀█▄██▀ ▀▄▄█▄▀▄ █
              █ ▀▀▀▀▀ █ ▄▄▄▀█▀  ▀▄▄▄▀██ █
              ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀

  ➜ Local:    http://localhost:3000/
  ➜ Network:  http://172.28.48.1:3000/ [QR code]
  ➜ Network:  http://192.168.1.190:3000/

  ➜ DevTools: press Shift + Alt + D in the browser (v1.3.3)           2:50:37 PM

ℹ Vite server warmed up in 4105ms                                    2:50:44 PM
ℹ Vite client warmed up in 5338ms                                    2:50:44 PM
✔ Nuxt Nitro server built in 3116 ms                           nitro 2:50:46 PM

 ERROR  [unhandledRejection] write ECONNABORTED                       2:50:50 PM  

  at afterWriteDispatched (node:internal/stream_base_commons:160:15)
  at writeGeneric (node:internal/stream_base_commons:151:3)
  at Socket._writeGeneric (node:net:952:11)
  at Socket._write (node:net:964:8)
  at writeOrBuffer (node:internal/streams/writable:556:12)
  at _write (node:internal/streams/writable:490:10)
  at Writable.write (node:internal/streams/writable:494:10)
  at IncomingMessage.ondata (node:internal/streams/readable:985:22)
  at IncomingMessage.emit (node:events:514:28)
  at addChunk (node:internal/streams/readable:545:12)
```
