### ISSUE TITLE
RouterView slot

### ISSUE THREAD

**Issue by frasza** [nuxt/nuxt#26998]
### Describe the feature

hey 👋

recently I came across a special case where I had to pass a component to child NuxtPage and figured out that NuxtPage does not seem to support passing vslot.

Here is the documentation from Vue Router about that:
https://router.vuejs.org/guide/advanced/router-view-slot

Seems very useful functionality. Do you think it would be possible to support it with NuxtPage?

Cheers!

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by Mini-ghost** [comment]
I've attempted to enable the default slot support in `<NuxtPage>`, and it appears to be functioning well so far. If the core team is open to adopting this feature, may I submit a PR to implement it?

**Comment by manniL** [comment]
We as a team think it is a great idea!

A PR is more than welcome 👍🏻

The only thing to ensure is that it doesn't "break" Suspense and works with it 😋
