### ISSUE TITLE
Remove inline scripts from the build

### ISSUE THREAD

**Issue by CodeCube0** [nuxt/nuxt#27004]
### Describe the feature

Hi Development Team,

I hope everything is going well. I would like to propose a new feature for Nuxt.js that could be very useful for many developers: the ability to remove inline scripts from the build.

Currently, when building a Nuxt.js project, JavaScript scripts can be embedded directly into the HTML pages. However, this practice can increase the page size and negatively impact performance, especially on devices with slow or limited internet connections.

My proposal is to implement an option in the Nuxt.js configuration that allows developers to specify whether they want to include inline scripts or prefer to exclude them from the final build. This would allow developers to optimize their applications for performance by reducing the overall page size and improving the user experience.

This feature could be implemented through a setting in the Nuxt.js configuration file, for example:

```
// nuxt.config.js

export default {
  // Other configurations...
  build: {
    inlineScripts: false // Default setting to true to maintain current behavior
  }
}
```
With this setting, developers could easily control whether they want to include inline scripts in the build or not.

I understand that this change may require some significant adjustments within the core of Nuxt.js, but I believe the performance and page load optimization benefits would definitely make it worthwhile.

Would it be possible to consider including this feature in future versions of Nuxt.js? It would be great to have this option available to further enhance web development with Nuxt.js.

Thank you for your attention and for all the work you do to continually improve Nuxt.js.

Best regards.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Do you mean disabling JS entirely, or just `<script>` tags with content?

**Comment by CodeCube0** [comment]
I would like to move the inline scripts to external files because if used in some environments (Browser Extensions) it causes security problems

**Comment by CodeCube0** [comment]
@danielroe you have some ideas in mind?

**Comment by CodeCube0** [comment]
but how should I do it?

**Comment by BlackHunfer** [comment]
@danielroe I encountered the same problem, I want to use Nuxt applications to output to smart TV Samsung via webview and due to the security policy I cannot use inline scripts with content. And Nuxt generates configuration scripts inside the body. 

How do I move these scripts content into separate files?
```html
<script type="application/json" id="__NUXT_DATA__" data-ssr="false">[{"_errors":1,"serverRendered":2,"data":3,"state":4,"once":5},{},false,{},{},["Set"]]</script>
<script>window.__NUXT__={};window.__NUXT__.config={public:{...},app:{baseURL:"/",buildAssetsDir:"/_nuxt/",cdnURL:""}}</script>
```

**Comment by CodeCube0** [comment]
Could you give me some examples on how to solve it? @danielroe

**Comment by Ibochkarev** [comment]
@danielroe Hello


Could you give me some examples on how to solve it?

**Comment by surgiie** [comment]
I am also looking for this feature, is there anyway we can get this script removed as an inline script? It prevents me from being able to effectively create a good CSP policy and im forced to use `unsafe-inline` which is discouraged.

**Comment by snoweuph** [comment]
So, how can we remove that?

**Comment by BlackHunfer** [comment]
@CodeCube0 will you share?)

**Comment by snoweuph** [comment]
> I wrote a powershell script that removes the tags and moves them to an external file and then adds the generated file to the generated HTML files. @snoweuph

powershell would need mean we would need to get some way to get a dos system in our jenkins for deployment (and we devs also dont have a dos system)

**Comment by CodeCube0** [comment]
For Windows with powershell:
```
$files = @(
    "build\index.html",
    "build\200.html",
    "build\404.html"
)

$extractedCreated = $false
$outputFilePath = Join-Path -Path (Split-Path -Parent $files[0]) -ChildPath "extracted.js"

foreach ($file in $files) {
    $htmlContent = Get-Content -Path $file -Raw

    if (-not $extractedCreated) {
        $bodyScriptRegex = '(?s)(<body.*?>.*?<script>)(.*?)(<\/script>.*?<\/body>)'

        $scriptMatch = [regex]::Match($htmlContent, $bodyScriptRegex)

        if ($scriptMatch.Success) {
            $scriptContent = $scriptMatch.Groups[2].Value.Trim()

            Set-Content -Path $outputFilePath -Value $scriptContent
            
            $extractedCreated = $true
        } else {
            Write-Host "Nessun tag <script> trovato nel file $file."
        }
    }

 
    if ($extractedCreated) {
        $htmlContent = $htmlContent -replace $bodyScriptRegex, '$1$3'
        $htmlContent = $htmlContent -replace '<script></script>', ''
    }

    $newScriptTag = '<script src="extracted.js"></script>'

    $modifiedHtmlContent = [regex]::Replace($htmlContent, '(<script type="module".*?>)', "$newScriptTag`n`$1")

    Set-Content -Path $file -Value $modifiedHtmlContent

    Write-Host "File $file modified successfully!"
}
```

For MacOS or Linux with bash: 

```
#!/bin/bash

files=(
    "build/index.html"
    "build/200.html"
    "build/404.html"
)

extractedCreated=false
outputFilePath="build/extracted.js"

for file in "${files[@]}"; do
    htmlContent=$(<"$file")

    if [ "$extractedCreated" = false ]; then
        # Usa grep e sed per estrarre il contenuto dello script
        scriptContent=$(echo "$htmlContent" | grep -oP '(?s)(<body.*?>.*?<script>)(.*?)(<\/script>.*?<\/body>)' | sed -n 's/.*<script>\(.*\)<\/script>.*/\1/p' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')

        if [ -n "$scriptContent" ]; then
            echo "$scriptContent" > "$outputFilePath"
            extractedCreated=true
        else
            echo "Nessun tag <script> trovato nel file $file."
        fi
    fi

    if [ "$extractedCreated" = true ]; then
        # Rimuove il contenuto dello script dal body
        htmlContent=$(echo "$htmlContent" | sed -e 's/<body.*?>.*<script>.*<\/script>.*<\/body>/<body>.*<\/body>/')
        htmlContent=$(echo "$htmlContent" | sed 's/<script><\/script>//g')
    fi

    newScriptTag='<script src="extracted.js"></script>'
    # Aggiunge il nuovo tag dello script
    modifiedHtmlContent=$(echo "$htmlContent" | sed "s/<script type=\"module\".*>/$newScriptTag\n&/")

    echo "$modifiedHtmlContent" > "$file"

    echo "File $file modified successfully!"
done
```

@BlackHunfer @snoweuph

**Comment by angrymusic** [comment]
> For Windows with powershell:
> 
> ```
> $files = @(
>     "build\index.html",
>     "build\200.html",
>     "build\404.html"
> )
> 
> $extractedCreated = $false
> $outputFilePath = Join-Path -Path (Split-Path -Parent $files[0]) -ChildPath "extracted.js"
> 
> foreach ($file in $files) {
>     $htmlContent = Get-Content -Path $file -Raw
> 
>     if (-not $extractedCreated) {
>         $bodyScriptRegex = '(?s)(<body.*?>.*?<script>)(.*?)(<\/script>.*?<\/body>)'
> 
>         $scriptMatch = [regex]::Match($htmlContent, $bodyScriptRegex)
> 
>         if ($scriptMatch.Success) {
>             $scriptContent = $scriptMatch.Groups[2].Value.Trim()
> 
>             Set-Content -Path $outputFilePath -Value $scriptContent
>             
>             $extractedCreated = $true
>         } else {
>             Write-Host "Nessun tag <script> trovato nel file $file."
>         }
>     }
> 
>  
>     if ($extractedCreated) {
>         $htmlContent = $htmlContent -replace $bodyScriptRegex, '$1$3'
>         $htmlContent = $htmlContent -replace '<script></script>', ''
>     }
> 
>     $newScriptTag = '<script src="extracted.js"></script>'
> 
>     $modifiedHtmlContent = [regex]::Replace($htmlContent, '(<script type="module".*?>)', "$newScriptTag`n`$1")
> 
>     Set-Content -Path $file -Value $modifiedHtmlContent
> 
>     Write-Host "File $file modified successfully!"
> }
> ```
> 
> For MacOS or Linux with bash:
> 
> ```
> #!/bin/bash
> 
> files=(
>     "build/index.html"
>     "build/200.html"
>     "build/404.html"
> )
> 
> extractedCreated=false
> outputFilePath="build/extracted.js"
> 
> for file in "${files[@]}"; do
>     htmlContent=$(<"$file")
> 
>     if [ "$extractedCreated" = false ]; then
>         # Usa grep e sed per estrarre il contenuto dello script
>         scriptContent=$(echo "$htmlContent" | grep -oP '(?s)(<body.*?>.*?<script>)(.*?)(<\/script>.*?<\/body>)' | sed -n 's/.*<script>\(.*\)<\/script>.*/\1/p' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
> 
>         if [ -n "$scriptContent" ]; then
>             echo "$scriptContent" > "$outputFilePath"
>             extractedCreated=true
>         else
>             echo "Nessun tag <script> trovato nel file $file."
>         fi
>     fi
> 
>     if [ "$extractedCreated" = true ]; then
>         # Rimuove il contenuto dello script dal body
>         htmlContent=$(echo "$htmlContent" | sed -e 's/<body.*?>.*<script>.*<\/script>.*<\/body>/<body>.*<\/body>/')
>         htmlContent=$(echo "$htmlContent" | sed 's/<script><\/script>//g')
>     fi
> 
>     newScriptTag='<script src="extracted.js"></script>'
>     # Aggiunge il nuovo tag dello script
>     modifiedHtmlContent=$(echo "$htmlContent" | sed "s/<script type=\"module\".*>/$newScriptTag\n&/")
> 
>     echo "$modifiedHtmlContent" > "$file"
> 
>     echo "File $file modified successfully!"
> done
> ```
> 
> @BlackHunfer @snoweuph

hello, I too have the same problem. How can I apply this to my nuxt3 build? (i'm using ubuntu)

**Comment by angrymusic** [comment]
@CodeCube0 hello, I too have the same problem. How can I apply this to my nuxt3 build? (i'm using ubuntu) How can I apply it in the .ouput folder?

**Comment by Neruell** [comment]
Would also like to have this as a standard feature.

**Comment by Dante-dan** [comment]
This could be more complex than you think. `__NUXT__` contains data from the server-side runtime. If we want to remove it from `inlineScrpts`, it implies that we need to generate a `js` file during the server-side runtime. This may cause more complicated problems. 

If we are willing to accept using this feature only in the scenario where `ssr: false`, I might be able to try it.

**Comment by CodeCube0** [comment]
> This could be more complex than we think. `__NUXT__` contains data from the server-side runtime. If we want to remove it from `inlineScrpts`, it implies that we need to generate a `js` file during the server-side runtime. This may cause more complicated problems. 
> 
> 
> 
> If we are willing to accept using this feature only in the scenario where `ssr: false`, I might be able to try it.

yes, in fact I use the script above with ssr set to false

**Comment by Dante-dan** [comment]
https://www.npmjs.com/package/nuxt-inline-scripts 

maybe you can use this package

**Comment by CodeCube0** [comment]
Can I close this conversation?

**Comment by shroomlife** [comment]
Hey, I tried https://github.com/Dante-dan/nuxt-inlineScripts and the problem is that on SSG the inline-scripts will be placed in /server folder and that is not what you expect for a client only build. Currently not possible to create a Twitch extension with Nuxt3... 😔

**Comment by fk-aconso** [comment]
> Hey, I tried https://github.com/Dante-dan/nuxt-inlineScripts and the problem is that on SSG the inline-scripts will be placed in /server folder and that is not what you expect for a client only build. Currently not possible to create a Twitch extension with Nuxt3... 😔

You can adjust the path (see: https://github.com/Dante-dan/nuxt-inline-scripts/issues/15), but the plugin will not handle inline json correctly, so its not a working solution at the moment.
