### ISSUE TITLE
Vue draggable lib not working inside module during dev mode while it works on production build

### ISSUE THREAD

**Issue by shivanshtalwar** [nuxt/nuxt#27000]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.11.2`
- CLI Version:      `3.11.1`
- Nitro Version:    `2.9.6`
- Package Manager:  `npm@6.14.15`
- Builder:          `-`
- User Config:      `css`, `modules`, `components`, `vite`, `runtimeConfig`, `hooks`, `nitro`
- Runtime Modules:  `@UtopiaTechCorp/utt-block-editor@1.0.0`
- Build Modules:    `-`

### Reproduction

create a simple nuxt module and installed the package 
```
"@marshallswain/vuedraggable": "^4.2.0",
```
or 
https://github.com/marshallswain/vue.draggable  

According to documentation of this package you can use it either by 
```ts
import draggable from '@marshallswain/vuedraggable'
  ...
  export default {
        components: {
            draggable,
        },
 ```
 or
 you can install it as a global component in a plugin, I did with this approach
 
 ```ts
 import draggable from "@marshallswain/vuedraggable";
 export default defineNuxtPlugin((app) => {
    app.vueApp.component('draggable', draggable)
})
``` 
Now on running it in dev mode it throws error in browser
```
Uncaught SyntaxError: The requested module '/_nuxt/node_modules/@marshallswain/vuedraggable/dist/vuedraggable.umd.js?v=11114f9e' does not provide an export named 'default' (at vuetify.mjs?v=11114f9e:2:8)
```
now on googling i tried by importing like
```ts
import * as draggable from '@marshallswain/vuedraggable'
```
the previous error will go away however it will give another error
that `defineComponent` is undefined in package's umd file
but if you run the code with
```
npm run build
npm run start
```
everything will work as expected.
      

### Describe the bug

apparently nuxt is not able to run this component in dev mode

**Comment by danielroe** [comment]
This is likely an issue upstream with `@marshallswain/vuedraggable` and you can probably resolve with `vite.optimizeDeps` - see https://vitejs.dev/config/dep-optimization-options.html.

**Comment by shivanshtalwar** [comment]
@danielroe  Thank you very much for your quick reply
after adding dependency to  module.ts of my nuxt module it works like a charm in dev mode
```ts
 nuxt.options.vite.optimizeDeps = defu(nuxt.options.vite.optimizeDeps, {
            needsInterop: ['@marshallswain/vuedraggable'],
            include: ['@marshallswain/vuedraggable']
        })
```
