### ISSUE TITLE
HMR doesn't work on pages that are added to .nuxtignore file

### ISSUE THREAD

**Issue by Sakamitsu** [nuxt/nuxt#27030]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.13.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@8.19.3
- Builder:          -
- User Config:      devtools, hooks
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

1. Open https://stackblitz.com/edit/github-zvug7j
2. Try change child page

### Describe the bug

If you add a page to `.nuxtignore` and then include it via a hook (pages:extend) in `nuxt.config.ts`, HMR will not work on that page.

### Additional context

I'm not sure if this is a bug or expected behavior, but it seems quite confusing to me.
Possible solutions:
- HMR will work in the scenario described above.
- Nuxt config will completely disregard all pages specified in `.nuxtignore`, and the hook will simply not work in the specified case.
- If this behavior is intentional and not a bug, consider adding information about it to the documentation, for example, here: https://nuxt.com/docs/guide/directory-structure/nuxtignore

**Comment by danielroe** [comment]
This is very much expected.

**Comment by Sakamitsu** [comment]
That's demonstrated in the reproduction. Change the routing of some pages while keeping the original file names. Aliases don't solve this problem. Nuxt also has `app/router.options.ts`, which perfectly solves this problem. However, I think the behavior of hooks in nuxt.config.ts is not entirely clear from the documentation.

If I can add them manually, why doesn't HMR work? 
Why am I able to add these pages in `nuxt.config.ts` if I have them in `.nuxtignore`? It seems that the expected behavior would be that Nuxt shouldn't acknowledge their existence at all.

**Comment by danielroe** [comment]
Have you tried setting the path in definePageMeta?

**Comment by Sakamitsu** [comment]
I use typed-router module and it doesn't support definePageMeta, see this issue https://github.com/victorgarciaesgi/nuxt-typed-router/issues/81
However, even when I use definePageMeta, it still doesn't resolve the ambiguities mentioned above.

**Comment by danielroe** [comment]
Are you sure? You should be able to provide a fully custom route with it:

```vue
<script setup lang="ts">
definePageMeta({
  path: '/some/:custom'
})
</script>

<template>
  <div>
    Nuxt 3 Playground
  </div>
</template>

<style scoped>

</style>
```

As far as `.nuxtignore` is concerned, it's not meant for the purpose you're using it for.

Instead, don't add the pages to `.nuxtignore` and manually remove them in the `pages:extend` hook (or modify the page route _there_).

We might be willing to support custom globs for scanning pages later on.
