### ISSUE TITLE
updating of experimental options

### ISSUE THREAD

**Issue by danielroe** [nuxt/nuxt#27031]
With the v4 release, we have an opportunity to simplify our current list of 'experimental' features:

- [ ] remove `treeshakeClientOnly` experimental option (enabled by default since v3.0.0)
- [ ] remove `configSchema` option (enabled by default since v3.3.0)
- [ ] remove `polyfillVueUseHead` (disabled since v3.4.0) - implementable in user-land with [plugin](https://github.com/nuxt/nuxt/blob/f209158352b09d1986aa320e29ff36353b91c358/packages/nuxt/src/head/runtime/plugins/vueuse-head-polyfill.ts#L10-L11)
- [ ] remove `respectNoSSRHeader` (disabled since v3.4.0) - implementable in user-land with [server middleware](https://github.com/nuxt/nuxt/blob/c660b39447f0d5b8790c0826092638d321cd6821/packages/nuxt/src/core/runtime/nitro/no-ssr.ts#L8-L9)

I would also like to remove `renderJsonPayloads` option (enabled by default since v3.5.0) but there seem to be [a number of repositories using it](https://github.com/search?q=%22renderJsonPayloads:+false%22&type=code) and I think we need to investigate _why_ and help them migrate to JSON payloads first.

In addition, I think we can consider enabling the following options by default sooner than 4.x:

- [x] `headNext` (cc: @harlan-zw - what do you think?)
- [ ] `scanPageMeta`
- [ ] `sharedPrerenderData`

Thoughts welcome 🙏

**Comment by harlan-zw** [comment]
`polyfillVueUseHead` can definitely be removed, `@vueuse/head` has been sunset for almost a year

`headNext` may also be worth removing if we're considering moving things under the module key `meta`, the Capo implementation can be enabled by default in the next Unhead release

**Comment by manniL** [comment]
Happy with all the considerations 👍🏻

For each removed feature/flag which could be a user-land implementation it'd be great to give an example in the release notes / migration guide / blog post, so people can easily "migrate" if they need said behavior.

**Comment by Dmytro-Tihunov** [comment]
Thanks, looking forward to
