### ISSUE TITLE
Infinite redirection when using qs after nuxt 3.11

### ISSUE THREAD

**Issue by Rigo-m** [nuxt/nuxt#27059]
### Environment

Netlify, various nuxt versions, check repo

### Reproduction

https://github.com/Rigo-m/test-query-netlify

### Describe the bug

Up until nuxt 3.10, integration with qs (which is needed for deep objects handling in query, e.g.: handling instantsearch filters state) works flawlessly in netlify.
From 3.11 onwards, there is an infinite redirection happening when the query values contains spaces.
I think this is happening because %20 gets transformed to + which gets re-transformed to %20 by qs, but I'm not sure.
I'm also not sure if this is an upstream issue with nitro (paging @pi0 )

Here relevant netlify links:

Nuxt 3.11.2 with qs in router-options
https://test-nuxt-query-netlify.netlify.app/?test=erba%20vita

Nuxt 3.10.2 with qs in router-options

https://nuxt-310--test-nuxt-query-netlify.netlify.app/?test=erba%20vita

Nuxt 3.11.2 without qs in router-options

https://noqs--test-nuxt-query-netlify.netlify.app/?test=erba%20vita

**Comment by danielroe** [comment]
This has been resolved on the nightly branch and the fix is incoming in v3.12

**Comment by Rigo-m** [comment]
Thanks Daniel! Can you point me to the PR fixing this? Curious what was happening under the hood

**Comment by manniL** [comment]
For all ppl interested, it is https://github.com/nuxt/nuxt/pull/27016
