### ISSUE TITLE
How to automatically reference enum types?Why can't implicit references be used?

### ISSUE THREAD

**Issue by bbhxwl** [nuxt/nuxt#27052]
Why can't implicit references be used?

<img width="913" alt="image" src="https://github.com/nuxt/nuxt/assets/26525599/00b3a1aa-67c8-4edc-96cf-524698dcdb95">

<img width="993" alt="image" src="https://github.com/nuxt/nuxt/assets/26525599/553b024a-ab25-4d69-8c4e-bcb2b4b0d2f6">

<img width="990" alt="image" src="https://github.com/nuxt/nuxt/assets/26525599/e99683ff-2291-4e9e-a3a0-57fcf8219374">

**Comment by dsvgl** [comment]
enums are both, runtime and types. Never put them in a d.ts file. These are only for declaring types.

**Comment by bbhxwl** [comment]
> enums are both, runtime and types. Never put them in a d.ts file. These are only for declaring types.

Do you need any special code? Or does it prompt that it does not exist and needs to be imported?


<img width="1079" alt="image" src="https://github.com/nuxt/nuxt/assets/26525599/2b69e167-5d3c-4fdf-884a-fe59ccaf5513">

**Comment by dsvgl** [comment]
Not sure if it is possible to make it auto-import. sorry.
