### ISSUE TITLE
Improve ignorePrefix JSDoc

### ISSUE THREAD

**Issue by volk234** [nuxt/nuxt#27064]
### Environment

https://stackblitz.com/edit/github-4pefag?file=package.json&view=editor

### Reproduction

https://stackblitz.com/edit/github-4pefag?file=package.json&view=editor

### Describe the bug

1. Create file "-test.txt" in public directory
2. Build project
3. The public directory does not contain a file "-test.txt"

**Comment by manniL** [comment]
I'd say this is intended because `-` is the `ignorePrefix`. The [JSDOC for it](https://github.com/nuxt/nuxt/blob/b330a296b8c91d1dd6dbc3dc74a84819120830a8/packages/schema/src/config/common.ts#L399-L405) should be updated though.
