### ISSUE TITLE
No export named 'consola' after upgrading to `v3.11.2`

### ISSUE THREAD

**Issue by beselig** [nuxt/nuxt#27070]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.12.2`
- Nuxt Version:     `3.11.2`
- CLI Version:      `3.11.1`
- Nitro Version:    `-`
- Package Manager:  `npm@10.7.0`
- Builder:          `-`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

I cannot link to a repository right now. The problem appears to be within nuxt `v3.11.2`. I didn't test prior patch versions, but `v3.10.3` works just fine.

### Describe the bug

I upgraded an existing project to nuxt `v3.11.2`, causing an error, seemingly related to the `consola` dependency, when running `nuxt dev`.

### Logs

```shell-script
ERROR  [worker reload] [worker init] The requested module 'file:///Users/xyz/projects/foo/node_modules/consola/dist/consola.js' does not provide an export named 'consola'                                    12:02:43 PM

  import { consola } from '/Users/xyz/projects/foo/node_modules/consola/dist/consola.js';
  ^^^^^^^
  SyntaxError: The requested module '/Users/xyz/projects/foo/node_modules/consola/dist/consola.js' does not provide an export named 'consola'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:217:5)
  at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
  at async loadESM (node:internal/process/esm_loader:28:7)
  at async handleMainPromise (node:internal/modules/run_main:113:12)
```

**Comment by g1ronn1mo** [comment]
For everyone, wondering how to downgrade Nuxt. 

use    `"nuxt": "3.10.3" ` insted of   ` "nuxt": "^3.10.3"`

The `^` cast a new version.

**Comment by danielroe** [comment]
Likely you have another dependency with an outdated consola dependency which is causing an old one to be installed.

Try ensuring you update `consola` - either by explicitly installing it, by refreshing your lockfile, or by identifying the package that has an old version and updating it.

**Comment by ecoms-ye** [comment]
same problem when creating a new project using `pnpm dlx nuxi@latest init`

```bash
$ pnpm why consola

dependencies:
nuxt 3.11.2
└─┬ @nuxt/devtools 1.3.3
  ├─┬ @nuxt/devtools-kit 1.3.3
  │ ├─┬ @nuxt/kit 3.11.2
  │ │ ├─┬ @nuxt/schema 3.11.2
  │ │ │ └── consola 3.2.3
  │ │ ├─┬ c12 1.10.0
  │ │ │ └─┬ giget 1.2.3
  │ │ │   ├─┬ citty 0.1.6
  │ │ │   │ └── consola 3.2.3
  │ │ │   ├── consola 3.2.3
  │ │ │   └─┬ nypm 0.3.8
  │ │ │     ├─┬ citty 0.1.6
  │ │ │     │ └── consola 3.2.3
  │ │ │     └── consola 3.2.3
  │ │ └── consola 3.2.3
  │ └─┬ @nuxt/schema 3.11.2
  │   └── consola 3.2.3
  ├─┬ @nuxt/devtools-wizard 1.3.3
  │ └── consola 3.2.3
  └─┬ @nuxt/kit 3.11.2
    ├─┬ @nuxt/schema 3.11.2
    │ └── consola 3.2.3
    └─┬ c12 1.10.0
      └─┬ giget 1.2.3
        └─┬ citty 0.1.6
          └── consola 3.2.3
```

**Comment by ra-dave** [comment]
Just started having this same problem out of the blue, have no idea what triggered it or how to resolve it.  I don't have a global node_modules folder.
