### ISSUE TITLE
Suggestion for new composables: `useResponseHeader(s)` similar to existing `useRequestHeader` composable

### ISSUE THREAD

**Issue by jelmerdemaat** [nuxt/nuxt#27075]
### Describe the feature

My feature suggestion is to add 1 or 2 new composables:

- `useResponseHeader`
- `useResponseHeaders`

Which would both be very similar to their existing equals:
- [useRequestHeader](https://nuxt.com/docs/api/composables/use-request-header)
- [useRequestHeaders](https://nuxt.com/docs/api/composables/use-request-headers)

Without having looked extensively at these existing composables, I think you might even be able to reuse a lot of the same scaffolding for creating `useResponseHeader(s)`.

Although I have not contributed before, I am experienced in building with Nuxt and would be willing (glad!) to implement this feature myself.

Motivation for this feature comes from my own desire to have a simple way to set response headers. For what it's worth, I did a quick search for issues and more people are asking about this:
- https://github.com/nuxt/nuxt/discussions/25091
- https://github.com/nuxt/nuxt/discussions/25425 
- https://github.com/nuxt/nuxt/discussions/21920

(It's not impossible right now of course, but having a dedicated composable for this in the docs could increase discoverability/usability.)

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Would love to see it! Let me know if you need any help. 🙏
