### ISSUE TITLE
onUploadProgress on $fetch

### ISSUE THREAD

**Issue by a7med-hussien** [nuxt/nuxt#27079]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.12.2
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.1.0
- Builder:          -
- User Config:      app, routeRules, runtimeConfig, css, colorMode, googleFonts, ssr, devtools, ignore, modules, build, dayjs, auth
- Runtime Modules:  @nuxt/ui@2.15.2, @vueuse/nuxt@10.9.0, @nuxt/image@1.6.0, @pinia/nuxt@0.5.1, @sidebase/nuxt-auth@0.6.7, @pinia-plugin-persistedstate/nuxt@1.2.0, @nuxtjs/device@3.1.1, @nuxtjs/google-fonts@3.2.0, dayjs-nuxt@2.1.9, @nuxtjs/fontaine@0.4.1, @formkit/auto-animate/nuxt@0.8.2, @nuxt/test-utils/module@3.12.1, floating-vue/nuxt, @samk-dev/nuxt-vcalendar@1.0.3
- Build Modules:    -
------------------------------

### Reproduction

```
upload(files) {
  const config = {
    onUploadProgress: function(progressEvent) {
      const percentCompleted = Math.round((progressEvent.loaded * 100) / progressEvent.total)
      console.log(percentCompleted)
    }
  }

  let data = new FormData()
  data.append('file', files[0])

  $fetch(url, {
    method: 'POST',
    body: data,
    config
  }).then(res => console.log({ res })).catch(err => console.log({ err }))}
```

### Describe the bug

i can't find `onUploadProgress` in `$fetch` module
we used to use it in `axios` to enable us making a progress bar while uploading images

**Comment by xjccc** [comment]
https://github.com/unjs/ofetch/issues/45

It's not support now...

**Comment by manniL** [comment]
Closing in favor of https://github.com/unjs/ofetch/issues/45

**Comment by bbhxwl** [comment]
> Closing in favor of [unjs/ofetch#45](https://github.com/unjs/ofetch/issues/45). Should work in chrome only at the moment with a bit of hand work.

Is it not supported yet?

**Comment by Alireza1996Sh** [comment]
please use something better than ofetch for xml http requests. @danielroe 
ofetch doesn't support interceptors too! [nuxt/nuxt#24157](https://github.com/nuxt/nuxt/issues/24157)

**Comment by manniL** [comment]
@Alireza1996Sh you can use anything you want. `ofetch` will be a central part of Nuxt though and *does* support interceptors!

**Comment by Alireza1996Sh** [comment]
> @Alireza1996Sh you can use anything you want. `ofetch` will be a central part of Nuxt though and _does_ support interceptors!

@manniL no it doesn't support global interceptors as you can see in these open issues:
[nuxt/nuxt#24157](https://github.com/nuxt/nuxt/issues/24157)
[unjs/ofetch#319](https://github.com/unjs/ofetch/issues/319)

**Comment by manniL** [comment]
> @manniL no it doesn't support global interceptors as you can see in these open issues: [nuxt/nuxt#24157](https://github.com/nuxt/nuxt/issues/24157) [unjs/ofetch#319](https://github.com/unjs/ofetch/issues/319)

It has interceptor support, you have to define a new instance an can't simply use `$fetch` but that's it. They will then also work "globally" when using the instance. See e.g. [this video](https://www.youtube.com/watch?v=jXH8Tr-exhI).

> anyway the problem here is with `onProgress`, not interceptors. so unfortunately the ofetch does not fully support xhr features and this is the problem

Like `fetch` 🤷🏻‍♂️ It is not an ofetch problem here. ☺️

**Comment by Alireza1996Sh** [comment]
@manniL So there are two solutions I can see:

1. We use some han written composable like what I wrote [useUploader](https://github.com/nuxt/nuxt/issues/27079#issuecomment-2378181628) until `fetch` supports `onProgress`
2. Nuxt uses old-fashioned libraries like `Axios` as _a central part of `Nuxt`_

**Comment by manniL** [comment]
@Alireza1996Sh 

Almost

1. You use your own solution (as you mentioned) or another one in userland
2. You use a different fetching library.

No reason to change something in Nuxt :)

**Comment by jeky1950** [comment]
@manniL is right, fetch does have global interceptors. I am using them in my app as part of my session management system. And @Alireza1996Sh I like your composable, let me give it a try.
