### ISSUE TITLE
Suggestion for useFetch Documentation: Add cache Option

### ISSUE THREAD

**Issue by nd2024** [nuxt/nuxt#27080]
I recently encountered an issue while using useFetch where I needed to prevent caching in a request. Unfortunately, it took me several hours of research to discover that a cache option exists for useFetch since it wasn't explicitly mentioned in the documentation. As a beginner, this was quite challenging and led to some frustration.

I believe adding a cache option to the documentation would greatly benefit users like myself. Clear documentation plays a crucial role in making tools accessible, especially for those who are just starting. By explicitly mentioning the cache option and providing usage examples, beginners would be able to leverage this functionality more efficiently, saving time and effort.

Example:

```
const { data, error} = await useFetch<GeneralResponse>('/bookmark/add', {
        method: 'post',
        cache: false,
        headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${token.value}`
        },
        body: {
           id: id
        },
    });
```

**Comment by manniL** [comment]
Related lines of code so documentation is easier: https://github.com/nuxt/nuxt/blob/f415e9cd0ace4ac1234463dd23483c4028014b29/packages/nuxt/src/app/composables/fetch.ts#L130
