### ISSUE TITLE
Need to fetch Request header's in Nuxt

### ISSUE THREAD

**Issue by krishfredrick** [nuxt/nuxt#27100]
### Describe the feature

I'm looking for to access the request headers in the Server api side it was not working 
 I used useRequestHeaders and useRequestHeader both composable in  `filepath: server/api/index.ts`
 it was throwing the function  is not define

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
```ts
export default defineEventHandler(async (event) => {
  console.log(getRequestHeaders(event))
})
```
