### ISSUE TITLE
The CJS build of Vite's Node API is deprecated.

### ISSUE THREAD

**Issue by 332lfgb6** [nuxt/nuxt#27110]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.10.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  pnpm@8.12.0
- Builder:          -
- User Config:      devtools, css, devServer, modules, postcss, vite
- Runtime Modules:  @vant/nuxt@1.0.4
- Build Modules:    -

### Reproduction

No repo needed

### Describe the bug

When I use the official legacy plugin, I get this warning
![image](https://github.com/nuxt/nuxt/assets/51245335/f1937fef-9c82-4176-9db7-15a9de6a2998)
```typescript
import legacy from "@vitejs/plugin-legacy";

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  vite: {
    plugins: [
      legacy({
         targets: ["Chrome 63", "ios 9"],
         modernPolyfills: true,
      }),
    ],
  },
});
```
```json
{
"dependencies": {
    "nuxt": "^3.11.2",
  },
  "devDependencies": {
    "@vitejs/plugin-legacy": "^5.4.0",
  }
}
```

**Comment by danielroe** [comment]
This is because `jiti` (which we use to transpile the `nuxt.config` in `c12` is loading the file in a CJS context.

@pi0 might have an idea about how to force ESM resolution of Vite, or a workaround here.

**Comment by pi0** [comment]
You can use `VITE_CJS_IGNORE_WARNING=1` environment variable to hide this warning. Once vite completely drops CJS entrypoint OR when [jiti v2](https://github.com/unjs/jiti/issues/174) is landed and c12 (and nuxt) adopts it, it will be resolved.
