### ISSUE TITLE
Infinite warn and memory crash when updating nuxt from 3.10 to 3.11

### ISSUE THREAD

**Issue by gsabater** [nuxt/nuxt#27130]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.17.1
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@9.6.7
- Builder:          -
- User Config:      experimental, typescript, components, modules, imports, css, build, content, app,
 site, sitemap, schemaOrg, webpack, vite, sourcemap, devtools
- Runtime Modules:  @nuxt/content@2.12.1, @nuxt/devtools@1.2.0, @nuxtjs/seo@2.0.0-rc.10, @vueuse/nuxt@10.9.0, @pinia/nuxt@0.5.1
- Build Modules:    -
------------------------------

### Reproduction

- Git clone https://github.com/gsabater/backlog.rip
- Checkout to dev
- npm install
- npm update nuxt
- Then add an error to the code either by modifying the code or deleting some plugins
- Access http://localhost:1337 preferably with the console already open 

### Describe the bug

The console shows the following warning more than 100.000 times until it crashes and the tab must be closed.
This happens on either Edge or Chrome

``
Avoid app logic that relies on enumerating keys on a component instance. The keys will be empty in production mode to avoid performance overhead. 
``

![image](https://github.com/nuxt/nuxt/assets/4948172/4e1e9fbb-e8aa-449f-998d-8d0e08a541a2)

### Additional context

As stated, this does not happen in nuxt 3.10 and starts happening on nuxt 3.11
Also, this does not happen if the code contains no errors. But once the console should show an error for an undefined method or undefined var, it starts crashing

### Tests made without success
- Disabling vue devtools and other chrome extensions
- Reducing the default layout and pages/index.vue to the bare minimum 
- Removing all plugins, stores and utils
- Removing .nuxt cache folder
- Returning to default port and remove `--host`

**Comment by danielroe** [comment]
Thanks for the report!

For now, you can work around by setting `features.devLogs` to `false`.

**Comment by gsabater** [comment]
It's amazing; I wasn't aware that I could disable this feature since I hadn't read the blog post. Thank you for your time, and I apologize for any inconvenience.
