### ISSUE TITLE
showError doesn't trigger `app:error` (anymore?)

### ISSUE THREAD

**Issue by TheDutchCoder** [nuxt/nuxt#27152]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-khtc7d?file=plugins%2Ferror-handler.js,app.vue

### Describe the bug

showError is supposed to trigger the `app:error` hook.
However this doesn't seem to work (anymore). I'm sure it used to work in the past.
You can see the hook registering properly in the plugin, but the actual log message on error never shows up.

I also tried throwing `createError`, but that also yields no results.

### Additional context

I noticed the docs now discourage using `showError`, which is new to me, but that has the same result.
<img width="439" alt="image" src="https://github.com/nuxt/nuxt/assets/1668207/bca55332-9e90-4498-9847-b9a16446d0f8">

**Comment by danielroe** [comment]
This seems to be working for me.

![CleanShot 2024-05-24 at 17 36 00@2x](https://github.com/nuxt/nuxt/assets/28706372/7deeffdf-635b-40cb-9a7f-29d6c3abb85f)

You can see the implementation here, which does call the hook:

https://github.com/nuxt/nuxt/blob/8a759bc6fe402bb6fc8dc0ae25401992a16d5880/packages/nuxt/src/app/composables/error.ts#L18-L40

**Comment by danielroe** [comment]
Hm. I don't know what might have been causing this to fail, but it _should_ be purely a Nuxt behaviour, and one that hasn't changed since you opened the repro...
