### ISSUE TITLE
ReportingObserver [deprecation]: Unload event listeners are deprecated and will be removed

### ISSUE THREAD

**Issue by sts-ryan-holton** [nuxt/nuxt#27154]
### Environment

Production

### Reproduction

I'm getting deprecation warnings about the `unload` event listeners. Upon further investigation it seems that there's an unload event listener triggered on each page when looking at the inspecter in Chrome

### Describe the bug

Nuxt JS is throwing core code deprecation warnings:

> ReportingObserver [deprecation]: Unload event listeners are deprecated and will be removed

I think this might be something related to core code that may need to be addressed as this is going to be fully deprecated at Q4 2024,.

### Additional context

![Screenshot 2024-05-10 at 16 58 47](https://github.com/nuxt/nuxt/assets/25177538/abbd8bd7-38fe-4695-bfad-9117780c989f)
![Screenshot 2024-05-10 at 16 58 39](https://github.com/nuxt/nuxt/assets/25177538/b7b8649d-9faa-4918-b8cb-7dbf096c68f4)

**Comment by JoshuaRobertson** [comment]
I'm also interested to know if this is something that will affect my Nuxt JS 2 projects. How important is the `unload` event in this context?

I haven't found a discussion about this but open to starting one if there are others looking for guidance and reassurance.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by sts-ryan-holton** [comment]
@danielroe Will there not be any chance to review the above given it was made earlier in May?

**Comment by danielroe** [comment]
The warning is being shown because of this code:

https://github.com/nuxt/nuxt/blob/00aeff62e700cabf65d5c67828bd419c015558e6/packages/vue-app/template/router.scrollBehavior.js#L11-L16

I think this is harmless and should not cause any issues in your project - you will simply lose the benefit of this feature, which applies when clicking an external link and then clicking the back button.

**Comment by sts-ryan-holton** [comment]
Thanks! This will be a good resource for other users approaching Q4 too.

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
