### ISSUE TITLE
Nuxt Docs seem broken

### ISSUE THREAD

**Issue by leoboyerbx** [nuxt/nuxt#27153]
### Environment

Public nuxt website

### Reproduction

Go to [https://nuxt.com/docs/getting-started/installation](https://nuxt.com/docs/getting-started/installation) or any other page of the docs

### Describe the bug

The public docs seem to be broken currently, I get a 500 on any page:

<img width="1282" alt="image" src="https://github.com/nuxt/nuxt/assets/38182814/0e92bf62-bc34-4ff6-89e1-56abff69aa86">

**Comment by silicoflare** [comment]
Facing the same issue here. On one browser I get the 500 error, and on another I get the base paragraph about the topic, but the subtopics flash in for a brief second before disappearing.

![image](https://github.com/nuxt/nuxt/assets/100959814/e63fe57f-8322-4e96-bbad-96045eb21cdc)

No adblockers or such scripts are up, so there's no external interference.

**Comment by Houssam-OUATMANI** [comment]
Same issue  :
Chrome:
<img width="1260" alt="Capture d’écran 2024-05-10 à 19 41 57" src="https://github.com/nuxt/nuxt/assets/60886381/a8a83cf3-a9d2-43d5-9a1d-6c26348661f4">
Firefox:
<img width="1260" alt="Capture d’écran 2024-05-10 à 19 45 08" src="https://github.com/nuxt/nuxt/assets/60886381/c3d4e9b1-6532-430c-baeb-27c6f6a91b52">

**Comment by olesiakissa** [comment]
> I was having this issue earlier today but it seems to be working now. I was getting a 500 error on the Firefox for iOS.

I confirm that it is working now, but only partially (personally I can access it  in Edge / Firefox)

![image](https://github.com/nuxt/nuxt/assets/15348166/70ff6ca9-1598-436e-a754-e24584e6e4f3)

However, the problem still persists in Chrome

![image](https://github.com/nuxt/nuxt/assets/15348166/b9f70f12-591d-43bf-b045-3c015e4d0a9c)

**Comment by leoboyerbx** [comment]
It seems to have been fixed, I thunk we can close this issue.
