### ISSUE TITLE
Cannot read documentation 

### ISSUE THREAD

**Issue by 756D61** [nuxt/nuxt#27151]
### Environment

Browser

### Reproduction

Visit https://nuxt.com/docs/getting-started/introduction

### Describe the bug

Cannot read any documentation page in Firefox, Chrome and Chrome Android.

![image](https://github.com/nuxt/nuxt/assets/129543910/7547b36f-4602-4d5e-a45e-a5d6a2397af0)

**Comment by manniL** [comment]
https://github.com/nuxt/nuxt.com/issues/1569#issuecomment-2104412793
