### ISSUE TITLE
Suggest supporting React component import to compensate for the current deficiencies in the Vue ecosystem.

### ISSUE THREAD

**Issue by 1057105012** [nuxt/nuxt#27156]
**Summary (generated)**:

Feature description is empty.

Would you be willing to help implement this feature?: [ ] 

Could this feature be implemented as a module?: [ ] 

Final checks:

- [X] Read the contribution guide.
- [X] Check existing discussions and issues.

<hr>

### Describe the feature

nothing

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
I don't think that the Nuxt repo is the right place for this suggestion ☺️
