### ISSUE TITLE
nuxt provides a simplified version of the documentation

### ISSUE THREAD

**Issue by 1057105012** [nuxt/nuxt#27162]
### Describe the feature

I think nuxt's documentation is too complicated, I think there are a lot of experimental, various ingenious ideas in it, but this also brings a problem, which is the increase in cognitive cost. I hope nuxt will propose a basic template of best practices as a common development scaffold, and split the documentation into advanced and basic versions. For example, what are the core components of nuxt, routing, server-side rendering, API writing methods, these are actually all beginners care about, as for how to make images faster, fonts more elegant, these are rarely relevant in the initial stage, what beginners do not care about, I think the nuxt official can provide their own best-looking and optimal settings, not exposed to developers, just as the default values of the basic template. If the documentation is simplified, the cognitive cost is reduced, for beginners, nuxt is also easier to accept, this is a good thing. Because many times, we do not prioritize "performance" and "clever design."

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
IMO that's more or less the sidebar when using "Get started"

<img width="269" alt="image" src="https://github.com/nuxt/nuxt/assets/640208/d2fb600e-4b8d-47d8-9280-23f123b218b2">

What do you think would be too complicated in these sections?

**Comment by danielroe** [comment]
We would definitely value improvement to the docs, and if you have any specific actionable suggestions that would be wonderful. 

I'm going to close this as it's difficult to mark it as 'done' at any point. But I think we already agree it would be great to make things simpler and clearer.
