### ISSUE TITLE
[feat] useLoadingIndicator error

### ISSUE THREAD

**Issue by dethdkn** [nuxt/nuxt#27175]
### Describe the feature

When calling finish() from useLoadingIndicator, it would be nice to have a error param to show a red (or any other color) loading bar

example:
![loading](https://github.com/nuxt/nuxt/assets/106754824/78d92732-f82f-4f53-8939-f8a75f64c606)

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by H0onnn** [comment]
@huang-julien Hello ! Can I solve this problem ?

**Comment by dethdkn** [comment]
Hello @H0onnn I've actually already submitted a pull request to address it. I would really appreciate it if you could take a look at my code and provide any feedback or improvements you might have in mind.

#27176

**Comment by H0onnn** [comment]
@dethdkn good ! Thank you for the great job you've done :)
