### ISSUE TITLE
TS error `...will overwrite file` when certain files exist

### ISSUE THREAD

**Issue by then3rdman** [nuxt/nuxt#27172]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.11.1
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  pnpm@9.1.0
- Builder:          -
- User Config:      eslint, fonts, pinia, ui, vueuse, modules, typescript, devtools
- Runtime Modules:  @nuxt/eslint@0.3.12, @nuxt/fonts@0.7.0, @nuxt/test-utils/module@3.12.1, @pinia/nuxt@0.5.1, @nuxt/ui@2.16.0, @vueuse/nuxt@10.9.0
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/then3rdman/nuxt-starter/tree/ts-error

### Describe the bug

TS has a warning about overwriting the `eslint.config.mjs` file only when there is a TS file inside the `server` directory. 

### Additional context

Manually setting `noEmit: true` in `tsconfig.server.json` fixes the warning.

**Comment by danielroe** [comment]
This is resolved in https://github.com/unjs/nitro/pull/2402

**Comment by then3rdman** [comment]
I thought that would be the case but has this not made it downstream into Nuxt yet?
