### ISSUE TITLE
useRoute didnt update

### ISSUE THREAD

**Issue by gyxoBka** [nuxt/nuxt#27199]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, modules, pinia
- Runtime Modules:  @pinia/nuxt@0.5.1
- Build Modules:    -
------------------------------

### Reproduction

[Stackblitz](https://stackblitz.com/edit/nuxt-starter-h3pnwf?file=stores%2Flocation.ts)

### Describe the bug

1. Go to Other page id 1
You'll see that all id's are 1

2. Then go to Main Page

3.Then go to Other page id 2
You'll see that all id's are 2 except first. Location Outside wiill be still 1

it is updated only when declaring a variable inside the method during auto-import or when importing from vue-router

**Comment by jakubednar** [comment]
Hello 👋, 
you can use `const route = useRouter().currentRoute.value;` to get reactive route object.

**Comment by gyxoBka** [comment]
> Hello 👋, you can use `const route = useRouter().currentRoute.value;` to get reactive route object.

Hello! Thank you a lot! It actually works. However, I don't think this is the solution to the useRoute problem

**Comment by xavier-ottolini** [comment]
> Hello 👋, you can use `const route = useRouter().currentRoute.value;` to get reactive route object.

This is not the usual way to get the current route in Vue. `useRoute` to get the current route should be more userFriendly. 
However it it can not be done easily, it should be at least documented.

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/28804 - see https://github.com/nuxt/nuxt/issues/28804#issuecomment-2327483434 for an explanation of what is happening and why.
