### ISSUE TITLE
Nuxt 4 testing

### ISSUE THREAD

**Issue by R0N1n-dev** [nuxt/nuxt#27203]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.16.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@9.6.7
- Builder:          -
- User Config:      devtools, future
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Used 'nuxi init' to start a new nuxt 3 project.
Followed Nuxt 4 migration guide from https://nuxt.com/docs/getting-started/upgrade#testing-nuxt-4

### Describe the bug

Instead of being taken to home page, am taken to nuxt welcome page.
![Screenshot from 2024-05-14 10-10-04](https://github.com/nuxt/nuxt/assets/83344872/e388015a-f92f-43ad-86b6-8b03b8b4b6d5)
code structure as follows
![Screenshot from 2024-05-14 10-10-34](https://github.com/nuxt/nuxt/assets/83344872/05de9554-7e3d-49d4-95f9-a00dc85d51dd)

App.vue
![Screenshot from 2024-05-14 10-15-50](https://github.com/nuxt/nuxt/assets/83344872/70094514-7348-488f-9e87-7617c81b7449)

**Comment by rtrap-rsi** [comment]
This could happen if the nuxt version (and dependency) are not correctly installed. Have you delete the package-lock.json before running `npm install`? The `nuxt.config.ts` show some type issue (on compatibilityVersion for example)?
Here you could find a working version (I just followed the same steps):
https://stackblitz.com/~/github.com/rtrap-rsi/nuxt-starter-lrhmf1?file=nuxt.config.ts

**Comment by R0N1n-dev** [comment]
> This could happen if the nuxt version (and dependency) are not correctly installed. Have you delete the package-lock.json before running `npm install`? The `nuxt.config.ts` show some type issue (on compatibilityVersion for example)? Here you could find a working version (I just followed the same steps): https://stackblitz.com/~/github.com/rtrap-rsi/nuxt-starter-lrhmf1?file=nuxt.config.ts

Yes. Did that and same thing. Nothing.

**Comment by rtrap-rsi** [comment]
I see that in the issue description you wrote
> Nuxt Version: 3.11.2

It is exactly what you have? It should be `npm:nuxt-nightly@latest` (that now resolve at something like 3.12.0-hash...)

**Comment by danielroe** [comment]
You need to use the nightly release channel to test it. Or wait for the release of v3.12.

**Comment by R0N1n-dev** [comment]
Yeah still not working.
![Screenshot from 2024-05-21 06-32-40](https://github.com/nuxt/nuxt/assets/83344872/aae5c27f-dcaa-4b17-9774-c581d74ac8a7)
![Screenshot from 2024-05-21 06-32-55](https://github.com/nuxt/nuxt/assets/83344872/e780b270-fa6f-4b25-a85f-7aa8452ecec2)


Will just wait.

**Comment by rtrap-rsi** [comment]
Removed node modules and package lock and reinstalled after the change?

**Comment by R0N1n-dev** [comment]
> Removed node modules and package lock and reinstalled after the change?

Yes, I did. TWICE.

**Comment by danielroe** [comment]
If you're encountering an issue with the nightly version, please provide a reproduction and I'll happily take a look 🙏

**Comment by R0N1n-dev** [comment]
> If you're encountering an issue with the nightly version, please provide a reproduction and I'll happily take a look 🙏

https://stackblitz.com/github/R0N1n-dev/nuxt-4-issue

**Comment by rtrap-rsi** [comment]
If I remove 
    "@nuxt/devtools": "^1.3.1",
everything work as expected. It is included in nuxt, why the need to install it manually? Which command did you use it to create the project ? (I used npx nuxi@latest init)

**Comment by R0N1n-dev** [comment]
> If I remove "@nuxt/devtools": "^1.3.1", everything work as expected. It is included in nuxt, why the need to install it manually? Which command did you use it to create the project ? (I used npx nuxi@latest init)

![Screenshot from 2024-05-22 09-33-25](https://github.com/nuxt/nuxt/assets/83344872/23a30417-bea5-4a39-8a20-ab311898ac6c)
![Screenshot from 2024-05-22 09-35-47](https://github.com/nuxt/nuxt/assets/83344872/d0f1a025-e4ac-4e8c-83a8-70c3e86f87a6)

Nothing
![Screenshot from 2024-05-22 09-33-32](https://github.com/nuxt/nuxt/assets/83344872/74631ea2-f010-4660-9b38-3bacc714d3fd)

**Comment by danielroe** [comment]
@R0N1n-dev The reproduction you linked seems fine.

![CleanShot 2024-05-22 at 13.16.32@2x.png](https://volta.s3.fr-par.scw.cloud/Clean_Shot_2024_05_22_at_13_16_32_2x_fa9ad80aaf.png)

My guess is that you are not in fact on the latest version. Try explicitly installing `npm:nuxt-nightly@3.12.0-28605073.2e25afdf`
