### ISSUE TITLE
Type issue with the value ref of useAsyncData

### ISSUE THREAD

**Issue by paranoidPhantom** [nuxt/nuxt#27220]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.13.1
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.4
- Package Manager:  bun@1.1.8
- Builder:          -
- User Config:      devtools, modules, primevue, supabase, ssr
- Runtime Modules:  nuxt-primevue@0.3.1, @nuxtjs/supabase@1.2.2
- Build Modules:    -
------------------------------

### Reproduction

[Link](https://codesandbox.io/p/devbox/useasyncdata-bug-5fkm42?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clw6nbs3200063j6mh5c72rti%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clw6nbs3200023j6mzqg3gd13%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clw6nbs3200043j6m2c2ped22%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clw6nbs3200053j6m7rvpw2wc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clw6nbs3200023j6mzqg3gd13%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw6nbs3200013j6mpdoi8uhk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clw6nbs3200023j6mzqg3gd13%2522%252C%2522activeTabId%2522%253A%2522clw6nbs3200013j6mpdoi8uhk%2522%257D%252C%2522clw6nbs3200053j6m7rvpw2wc%2522%253A%257B%2522id%2522%253A%2522clw6nbs3200053j6m7rvpw2wc%2522%252C%2522activeTabId%2522%253A%2522clw6ne2jx004x3j6m83iepzbi%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clw6ne2jx004x3j6m83iepzbi%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clw6nbs3200043j6m2c2ped22%2522%253A%257B%2522id%2522%253A%2522clw6nbs3200043j6m2c2ped22%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw6nbs3200033j6m5xhx96dc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clw6nbt38000kd0ebbd06bh0a%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clw6ne2c0003l3j6ms20d4kvk%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clw6ne2c0003l3j6ms20d4kvk%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Describe the bug

When destructuring { data } from useAsyncData and using it in v-for, typescript suggests using data.value instead of just data.
It happens in my editor but not the reproduction and I don't know why.
![image](https://github.com/nuxt/nuxt/assets/46633092/4a007ad2-2eaf-4299-ad01-25f33abf57bb)
![image](https://github.com/nuxt/nuxt/assets/46633092/a52c0078-e0db-45ad-8807-fee14be7ba12)

**Comment by DamianGlowala** [comment]
Which version of the `Vue - Official` extension are you using?

**Comment by paranoidPhantom** [comment]
> Which version of the `Vue - Official` extension are you using (if you do)?

How would I check this?

**Comment by xMorthi** [comment]
@paranoidPhantom Simply go to extensions tab -> find `Vue - Official` and on the top, next to the name you should have version which is currently in use

<img width="745" alt="Screenshot 2024-05-23 at 10 53 37" src="https://github.com/nuxt/nuxt/assets/13519194/87d4fa51-eab1-4a25-a150-ae5025200bd9">

**Comment by danielroe** [comment]
Yes, this will be an issue with the Vue IDE plugin rather than Nuxt's types. (Sometimes this happens when you have multiple Vue versions installed, which you can debug with `pnpm why vue`.)
