### ISSUE TITLE
[nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at `https://nuxt.com/docs/guide/concepts/auto-imports#vue-and-nuxt-composables`.

### ISSUE THREAD

**Issue by xuzhihui123** [nuxt/nuxt#27235]
### Environment

"nuxt": "3.11.2"

### Reproduction

https://stackblitz.com/edit/github-469cia-fcqpq7?file=plugins%2Ftest.ts

### Describe the bug

I introduced a composables method in plugins, which simulates asynchronous requests, but after an asynchronous request, an error will be reported.
<img width="1099" alt="Snipaste_2024-05-16_01-03-30" src="https://github.com/nuxt/nuxt/assets/42968962/574546b5-732e-4e5e-9dcf-f6df8735fd73">

**Comment by arashsheyda** [comment]
@xuzhihui123 composables are runtime only, if you want to use a composable in plugin you have to make sure it's running on client side only. you can achive that by adding `.client` to your plugin name (`test.client.ts`) or adding an if to your code:

```ts
if (process.client) {
    await a();
}
  ```

**Comment by xuzhihui123** [comment]
thanks, Is there any other way to run it on the server side?

**Comment by xuzhihui123** [comment]
Because I want to set some values after requesting some data from the server, which happens in server-side rendering, not just client-side rendering

**Comment by huang-julien** [comment]
Hello, you need to set the nuxt context with `nuxtApp.runWithContext`. `useState` is a composable that requires the nuxt context to be accessible

see https://nuxt.com/docs/guide/going-further/nuxt-app#the-nuxt-context

**Comment by xuzhihui123** [comment]
ok, solved it，thanks
