### ISSUE TITLE
useCookie not updating value in browser

### ISSUE THREAD

**Issue by martinszeltins** [nuxt/nuxt#27231]
### Environment

Stackblitz

````
------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------
````

### Reproduction

https://stackblitz.com/edit/nuxt-starter-kkckgc?file=app.vue

### Describe the bug

When using `useCookie` it updates the cookie ref itself but the change is not reflected in browser devtools as can be seen in the screenshot below.

And when calling `refreshCookie()` it takes the value that is in the browser (old value) even when the ref value is newer.

Screenshot:
![image](https://github.com/nuxt/nuxt/assets/34019878/78122a12-ed34-4060-bbcb-903fa3b897e2)

**Comment by vhovorun** [comment]
@martinszeltins Try to click refresh button inside devtools in will show you updated value
![image](https://github.com/nuxt/nuxt/assets/129970958/083c057b-2419-4ae8-87c4-181dabcb3992)

**Comment by martinszeltins** [comment]
> @martinszeltins Try to click refresh button inside devtools after changing cookie value and it will show you updated value !

Nope, the value is not updating even when I refresh cookies.

**Comment by hcz** [comment]
@martinszeltins For me works on my laptop and Stackblitz too

I can assume that you confused urls in dev tools
<img width="1127" alt="Screenshot 2024-06-18 at 00 42 46" src="https://github.com/nuxt/nuxt/assets/21956722/880f85b1-d5b7-415b-a242-baefee81180f">

**Comment by martinszeltins** [comment]
@hcz What is going on here? I tried it again, and the value is not updating. I am also looking at the `.webcontainer.io` url and it is not updating.

![image](https://github.com/nuxt/nuxt/assets/34019878/9a44b19f-f690-4546-a2f3-18744755b21f)

**Comment by danielroe** [comment]
@martinszeltins can you reproduce outside of Stackblitz?

**Comment by danielroe** [comment]
Thank you so much for your work on this.

Any chance you could raise an issue with Chrome in that case, and maybe investigate a bit further? 🙏

**Comment by martinszeltins** [comment]
I have reported this issue to the Google Chrome team - https://issues.chromium.org/issues/348683488

**Comment by artur1214** [comment]
I Faced the same issue. Looks like it can be fixed by manually changing sameSite parameter from None to Lax (None is default)

`sameSite: "lax"` Parameter. e.g.:

```TS

 const preferredCurrency = useCookie('preferred-currency', {
        default: () => defaultCurrencyId.value.toString()
    });
//Value is not being updated, but no errors are presented. 
prefferedCurrency.value = 'es';
```
```TS

 const preferredCurrency = useCookie('preferred-currency', {
        default: () => defaultCurrencyId.value.toString(),
        sameSite: "lax"
    });
// This works ok.
prefferedCurrency.value = 'es';
```
