### ISSUE TITLE
Problem with route rules in nuxt.config

### ISSUE THREAD

**Issue by BogdanPirozhok** [nuxt/nuxt#27243]
Good afternoon. Thanks for your attention, any help would be appreciated.

I have these rules in nuxt.config:

```
routeRules: {
    '/feed': { ssr: true, swr: false },
    '/feed/**': { swr: true }
},
```

So what I'm trying to accomplish is:
- **_/feed_** - this page is rendered dynamically using SSR.
- **_/feed/[slug]_** - dynamic pages with this pathname will be rendered statically with SWR

Unfortunately, in my case, it doesn't work, both routers generate static. This happens both in production environment and in development mode

**Comment by Jesse1989pp** [comment]
Shouldn't you opt-out of ssr over opting in as per https://nuxt.com/docs/guide/concepts/rendering#route-rules? Did you try removing `ssr:true` and add `ssr:false` to the slug rule?

**Comment by danielroe** [comment]
Does it work if you try:

```ts
routeRules: {
    '/feed': { swr: false, cache: false },
    '/feed/**': { swr: true }
},
```

**Comment by BogdanPirozhok** [comment]
> ```ts
> '/feed': { swr: false, cache: false },
>     '/feed/**': { swr: true }
> ```

It works amazingly. Thank you very much. I think this example should be covered in the documentation

**Comment by danielroe** [comment]
A PR would be very welcome! Also I think we likely need to make this behaviour more intuitive - see https://github.com/unjs/nitro/issues/887.
