### ISSUE TITLE
[useFetch] Component is already mounted, please use $fetch instead. See https://nuxt.com/docs/getting-started/data-fetching

### ISSUE THREAD

**Issue by bbhxwl** [nuxt/nuxt#27242]
Although it can be used, there are warnings. Why? Can't I keep using useFetch?

```
import type {UseFetchOptions} from "#app";
import type {Ref} from "vue";
import type {SearchParameters} from "ofetch";

const request = async <T = any>(url: any, options: any) => {
    const config = useRuntimeConfig();
    //设置url
    options.baseURL=config.public.apiBase
    let token = useCookie("manageToken")
    let customHeaders: { "Content-Type": string, Authorization?: string } = {"Content-Type": "application/json"}
    const res=await useFetch<T>(url, {headers: customHeaders,...options})
    if(process.client){
        if(res.error&&res.error.value){
            ElNotification({
                title: '系统错误提示',
                message: res.error.value.message,
                type: 'error',
                appendTo: document.body,
                zIndex: 9999
            })
        }
        else if (res.data.value&&(res.data.value as any).Msg) {
            if((res.data.value as any).Code===0){
                ElNotification({
                    title: '系统提示',
                    message: (res.data.value as any).Msg,
                    type: 'success',
                    appendTo: document.body,
                    zIndex: 9999
                })
            }
            else{
                ElNotification({
                    title: '错误提示',
                    message: (res.data.value as any).Msg,
                    type: 'error',
                    appendTo: document.body,
                    zIndex: 9999
                })
            }
        }
    }

    return res
};
type ResponseType<T = any> = T extends undefined ? CommonResponse<any> : CommonResponse<T>;

export const http = {
    get: <T = any>(url: Ref<string>|string, query?: SearchParameters, opts?: UseFetchOptions<T>) => {
        return request<T>(url, {...opts,...{method: 'GET', query}});
    },
    post: <T = undefined>(url: Ref<string>|string, body?: RequestInit["body"] | Record<string, any>, opts?: UseFetchOptions<ResponseType<T>>) => {
        return request<ResponseType<T>>(url, {...opts,...{method: 'POST', body}});
    },
    put: <T = undefined>(url: Ref<string>|string, body?: RequestInit["body"] | Record<string, any>, opts?: UseFetchOptions<ResponseType<T>>) => {
        return request<ResponseType<T>>(url, {...opts,...{method: 'PUT', body}});
    },
    postGetList: (url: Ref<string>|string, body?: RequestInit["body"] | Record<string, any>, opts?: UseFetchOptions<ResponseType<CommonResponseGetList>>) => {
        return request<CommonResponseGetList>(url, {...opts,...{method: 'POST', body}});
    },
}

```

**Comment by huang-julien** [comment]
Hello, that's because you're probably calling it outside a nuxt setup or component setup hook. see https://www.youtube.com/watch?v=njsGVmcWviY

**Comment by bbhxwl** [comment]
> Hello, that's because you're probably calling it outside a nuxt setup or component setup hook. see https://www.youtube.com/watch?v=njsGVmcWviY

Can't I call it with a method? My English is not good and I can't understand the video. Can you describe it in text? Can't I call useFetch as a method?

**Comment by huang-julien** [comment]
useFetch is a composable, it means that it is meant to be called in a setup function (nuxt or vue).
If you need to do any calls outside/after a component's setup function being called, you can use $fetch or the native fetch.

**Comment by bbhxwl** [comment]
> useFetch is a composable, it means that it is meant to be called in a setup function (nuxt or vue). If you need to do any calls outside/after a component's setup function being called, you can use $fetch or the native fetch.

I did this, and a warning will appear in the btnClick method.


![image](https://github.com/nuxt/nuxt/assets/26525599/c673870a-c540-4869-b7f3-09112456823f)

**Comment by bbhxwl** [comment]
Isn't there a universal method?

**Comment by Nisekoi5** [comment]
Requests initiated only on the client side should use $fetch
https://www.youtube.com/watch?v=njsGVmcWviY

**Comment by bbhxwl** [comment]
> Requests initiated only on the client side should use $fetch https://www.youtube.com/watch?v=njsGVmcWviY
> 
> You can continue to use it, it will only display warnings, but problems may occur in some scenarios. It is recommended to use $fetch instead. For details, you can check the youtube video link I sent.

Do I need to use two different methods for the server and client?

**Comment by bbhxwl** [comment]
> Requests initiated only on the client side should use $fetch https://www.youtube.com/watch?v=njsGVmcWviY
> 
> You can continue to use it, it will only display warnings, but problems may occur in some scenarios. It is recommended to use $fetch instead. For details, you can check the youtube video link I sent.

I am not good at English and cannot translate videos.

**Comment by Nisekoi5** [comment]
> > Requests initiated only on the client side should use $fetch https://www.youtube.com/watch?v=njsGVmcWviY
> > You can continue to use it, it will only display warnings, but problems may occur in some scenarios. It is recommended to use $fetch instead. For details, you can check the youtube video link I sent.
> 
> Do I need to use two different methods for the server and client?

Yes, use `$fetch` if this call is only for client requests
  If you need to initiate a request on both the server and client. You can use the `execute/refresh` method returned by `useFetch` to re-initiate the request. Instead of calling a new `useFetch`

----


是的，如果这个调用只在客户端请求就使用 `$fetch`
 如果在服务端和客户端都需要发起请求。则可以使用 `useFetch` 返回的  `execute/refresh` 方法来重新发起请求。而不是重新调用一次新的 `useFetch`

此外youtube有翻译字幕功能

**Comment by bbhxwl** [comment]
> `useFetch`



> > > 仅在客户端发起的请求应该使用 $fetch https://www.youtube.com/watch?v=njsGVmcWviY
> > > 可以继续使用它，它只会显示警告，但在某些场景下可能会出现问题。建议使用 $fetch 代替。详情可以查看我发的youtube视频链接。
> > 
> > 
> > 我需要为服务器和客户端使用两种不同的方法吗？
> 
> `$fetch`是的，如果此调用仅针对客户端请求，则使用 如果您需要在服务器和客户端上都发起请求。您可以使用`execute/refresh`返回的方法`useFetch`重新发起请求。而不是调用一个新的`useFetch`
> 
> 是的，如果这个调用只在客户端请求就使用，`$fetch` 如果在服务端并且客户端都需要发起请求。则可以使用`useFetch`返回的 `execute/refresh`方法来重新发起请求。而不是重新调用一次新的`useFetch`
> 
> 另外youtube有翻译字幕功能

I am currently only using useFetch, not refresh, and there are no errors. Will there be any unexpected issues?

**Comment by Nisekoi5** [comment]
> I am currently only using useFetch, not refresh, and there are no errors. Will there be any unexpected issues?

Not sure, it depends on the usage scenario

**Comment by KyleXie** [comment]
> > useFetch is a composable, it means that it is meant to be called in a setup function (nuxt or vue). If you need to do any calls outside/after a component's setup function being called, you can use $fetch or the native fetch.
> 
> I did this, and a warning will appear in the btnClick method.
> 
> ![image](https://private-user-images.githubusercontent.com/26525599/331424085-c673870a-c540-4869-b7f3-09112456823f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzOTU1ODEsIm5iZiI6MTcxNjM5NTI4MSwicGF0aCI6Ii8yNjUyNTU5OS8zMzE0MjQwODUtYzY3Mzg3MGEtYzU0MC00ODY5LWI3ZjMtMDkxMTI0NTY4MjNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDE2MjgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyNzc2NzNlODEzYWZmMmVkYmM2ZWY3OGJjMTNkYmU3NWVjNDUyNjRmNjAwZTAxYmI1NjMzM2UwZmY2ZjBhZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VMjc-9_wFTT9858t7-eZXGBlHvLmRAfhBCmuLElDgX4)

你还可以这样：

```
<script setup lang="ts">
const { refresh } = useFetch('test');

function btnClick() {
    refresh();
}
</script>
```

**Comment by Ken-Sinn** [comment]
这个情况我有解决办法，但是不确定这么做会不会有未知问题，暂时没发现问题

`const isServer = typeof window === 'undefined'

    //是否纯前端请求
    const isAjax = !isServer&&!app.isHydrating`

**Comment by Ken-Sinn** [comment]
这个情况我有解决办法，但是不确定这么做会不会有未知问题，暂时没发现问题

`
const isServer = typeof window === 'undefined'
//是否纯前端请求
const isAjax = !isServer&&!app.isHydrating
`

**Comment by Ken-Sinn** [comment]
这个情况我有解决办法，但是不确定这么做会不会有未知问题，暂时没发现问题

const app = useNuxtApp()
const isServer = typeof window === 'undefined' 
//是否纯前端请求
const isAjax = !isServer&&!app.isHydrating
