### ISSUE TITLE
<script setup> does not run on Pages which where navigated to by <NuxtLink>

### ISSUE THREAD

**Issue by FantixX** [nuxt/nuxt#27267]
### Environment

```
------------------------------
- Operating System: Windows_NT
- Node Version:     v20.11.1
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      devtools, modules, vuefire
- Runtime Modules:  @nuxtjs/tailwindcss@6.12.0, vue3-carousel-nuxt@1.1.1, nuxt-vuefire@1.0.2, @nuxt/image@1.7.0
- Build Modules:    -
------------------------------
```

### Reproduction

https://github.com/FantixX/nuxt-bug-report

### Describe the bug

After the dev server is started, the `<script setup>`  of a given page does not seem to run on first navigation to said page when it was navigated to by a `<NuxtLink>`
It runs as expected when when accessing the page via URL in the browser. It also behaves correctly on each subsequent Navigation via `<NuxtLink>` after the first one.

**Comment by b-mounir-dev** [comment]
@FantixX It's working for sure, but on client side only. SSR or any other rendering mode will only work when navigating via URL

**Comment by danielroe** [comment]
This seems to be working fine in your reproduction:

https://github.com/nuxt/nuxt/assets/28706372/228b81e9-782c-4c6f-94f1-2e7839a687fb
