### ISSUE TITLE
PostCSS breaking on adding tailwind plugin for nuxt-tour specifically, unable to start nuxt dev server

### ISSUE THREAD

**Issue by bippan1407** [nuxt/nuxt#27277]
### Environment

Build breaks with postcss for this specific package. Error screenshot below:
![Screenshot 2024-05-20 at 12 22 55 PM](https://github.com/nuxt/nuxt/assets/45727492/a6c20c1a-d1f6-4783-97e6-d509522c695a)

### Reproduction

I am sharing stackblitz for reproduction:

https://stackblitz.com/edit/nuxt-starter-sv2vxi?file=nuxt.config.ts,tailwind.config.js

### Describe the bug

Unable to start dev server

**Comment by bippan1407** [comment]
fix - https://github.com/BayBreezy/nuxt-tour/issues/19

**Comment by danielroe** [comment]
The reproduction works - dev server starts.

This also seems unlikely to be a Nuxt issue.
