### ISSUE TITLE
_How to run "useLazyAsyncData" on client-side only?_

Use the "clientSide" option. For example:

Nuxt.useLazyAsyncData(objects, { clientSide: true });

### ISSUE THREAD

**Issue by toknT** [nuxt/nuxt#27278]
**Summary (generated)**:

A user needs to log in with a token stored in local storage before accessing certain data, but when using the `useLazyAsyncData` function, it results in an unauthorized error on the server-side. The user is willing to help implement this feature and suggests it could be implemented as a module. Prior to implementation, the user has reviewed the contribution guide and checked existing discussions and issues.

<hr>

### Describe the feature

There are some data need user login with the token I store in localstorage. But if I run `useLazyAsyncData` it will get unauthoried error on server side.

So current I create component use `useLazyAsyncData`  in it and put it in `<client-only></client-only>`

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by warflash** [comment]
You can add `server: false` to the fetch options

**Comment by yxw007** [comment]
I've also encountered this problem, is it possible that the interface that requires a token can only be called on the client side?
