### ISSUE TITLE
routeRules /** swr crashed ipx provider

### ISSUE THREAD

**Issue by ovchinnikov-lxs** [nuxt/nuxt#27307]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.10.0`
- Nuxt Version:     `3.11.2`
- CLI Version:      `3.11.1`
- Nitro Version:    `2.9.6`
- Package Manager:  `pnpm@8.10.5`
- Builder:          `-`
- User Config:      `extends`, `modules`, `css`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/i18n@8.2.0`
- Build Modules:    `-`

### Reproduction

-

### Describe the bug

1. Add module [nuxt/image](https://github.com/nuxt/nuxt) 
2. add to nuxt.config this code
```
 routeRules: {
            '/**': {
                swr: 300,
            },
            '/_ipx/**': {
                swr: false,
            },
        },
```
3. /_ipx/** images paths will crash in next page reload

**Comment by b-mounir-dev** [comment]
@manniL @danielroe '/_ipx/**' config should override '/**' config, don't you think ? I noticed that when using '/**' routeRules, all other routeRules will be ignored.

**Comment by danielroe** [comment]
Does it work if you also set `cache: false`?

**Comment by ovchinnikov-lxs** [comment]
@danielroe Thank you very much it's work!❤️ So, can we use all fields from routeRules in Nitro? Because in the [documentation](https://nuxt.com/docs/guide/concepts/rendering#route-rules), cache field is not listed (although I now realize swr is a shortcut). If so, perhaps we should supplement the documentation with a link to [Nitro](https://nitro.unjs.io/config#routerules)?

**Comment by ItsRyanWu** [comment]
Hey guys, you should check this solution
https://github.com/nuxt/image/issues/1400#issuecomment-2522750442
