### ISSUE TITLE
Warning will appear when passing an external link to `<NuxtLink>`

### ISSUE THREAD

**Issue by Mini-ghost** [nuxt/nuxt#27312]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.0-28606556.69430aa2
- CLI Version:      3.11.2-1716385490.bfaf128
- Nitro Version:    2.9.6
- Package Manager:  pnpm@8.15.6
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-jphpju?file=app.vue

### Describe the bug

1. Start [Reproduction](https://stackblitz.com/edit/nuxt-starter-jphpju?file=app.vue). It includes the following code:
   ```html
   <NuxtLink to="https://nuxt.com/">Nuxt</NuxtLink>
   ```
2. Open the Console panel in DevTools.
3. A warning appears: `[Vue Router warn]: No match found for location with path "https://nuxt.com/"`.

<img width="689" alt="截圖 2024-05-23 凌晨1 29 32" src="https://github.com/nuxt/nuxt/assets/39984251/c817d310-dbfc-493b-89c3-fc97496c26f6">

### Additional context

This might be related to this PR: #26522.

### Logs

N/A

**Comment by Mini-ghost** [comment]
I've tested various scenarios regarding this PR #26522 and noticed that the `useLink` from this PR behaves slightly differently from Vue Router's `useLink`. For example:

```vue
<script setup lang="ts">
import { useLink } from 'vue-router'

const props = shallowReactive({
  to: 'https://mini-ghost.dev',
})

const { isActive } = useLink(props)
const { isActive: isNuxtLinkActive } = resolveComponent('NuxtLink').useLink(props)

const onClick = () => {
  if (props.to === '/') {
    props.to = '/about'
  } else {
    props.to = '/'
  }
}
</script>

<template>
  <div>
    <button @click="onClick">
      Click
    </button>

    isActive {{ isActive }} <br>
    isNuxtLinkActive: {{ isNuxtLinkActive }}
  </div>
</template>
```

When we switch routes by clicking the `<button>`, Vue Router's `isActive` reacts to the changes, but `<NuxtLink>`'s `isNuxtLinkActive` does not respond to changes in data. This issue might be caused by the following code segment:

https://github.com/userquin/nuxt/blob/1c5338dd43edb5b78c8776c33a5dcdca0768b9f0/packages/nuxt/src/app/components/nuxt-link.ts#L148-L151

Here, we are destructuring the passed `props`, which if `reactive` or `shallowReactive`, would lose their reactivity.

Should we align `<NuxtLink>`'s `useLink` behavior with Vue Router's `useLink`?

**Comment by danielroe** [comment]
Nice find! Yes, we should ensure this remains reactive.
