### ISSUE TITLE
In original code is using "renderToString", I want to use "renderToNodeSteam", what should I do?

### ISSUE THREAD

**Issue by wangzhe13555313322** [nuxt/nuxt#27317]
**Summary (generated)**:

Nuxt3 Environment 

Reproduction None

Describe the bug None

Additional context No response

Logs No response

<hr>

### Environment

Nuxt3

### Reproduction

none

### Describe the bug

none

**Comment by danielroe** [comment]
We do plan to support this in future but it's not yet configurable.
