### ISSUE TITLE
routeRules doesn't work

### ISSUE THREAD

**Issue by phpmac** [nuxt/nuxt#27323]
### Environment

routeRules doesn't work

### Reproduction

    nitro: {
        devProxy: {
            '/sapi': {
                target: 'https://xx',
                // target: 'http://localhost',
                changeOrigin: true,
                prependPath: true,
            },
            '/bit/gooes': {
                target: 'https://www.bitgoose.top/',
                changeOrigin: true,
                prependPath: true,
            },
        },
        routeRules: {
            '/sapi/**': { proxy: 'https://xx/**' },
            '/bit/gooes/**': { proxy: 'https://www.bitgoose.top/**' },
        },
    },

### Describe the bug

Doesn’t work after online build

**Comment by danielroe** [comment]
Would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏

**Comment by phpmac** [comment]
waiting

**Comment by phpmac** [comment]
Already updated, never encountered the error, I was using nuxt2 before and it worked fine,

**Comment by phpmac** [comment]
So proud of your team's enthusiasm to help!

**Comment by danielroe** [comment]
Okay, so it's not reproducible any more?

**Comment by phpmac** [comment]
Why do I get errors when initializing a new project?


[link](https://codesandbox.io/p/devbox/github/nuxt/starter/tree/v3-codesandbox/?file=%2Fapp.vue%3A3%2C20&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwkkyjom00073b6p76ckid01%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwkkyjom00023b6pejaui6tx%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwkkyjom00043b6pby83x46u%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwkkyjom00063b6pgbauempx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwkkyjom00023b6pejaui6tx%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwkkyjom00013b6pdbtmgt0b%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clwknk8ru003q3b6sdcvo9arg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A3%252C%2522startColumn%2522%253A20%252C%2522endLineNumber%2522%253A3%252C%2522endColumn%2522%253A20%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clwkkyjom00023b6pejaui6tx%2522%252C%2522activeTabId%2522%253A%2522clwknk8ru003q3b6sdcvo9arg%2522%257D%252C%2522clwkkyjom00063b6pgbauempx%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwkkyjom00053b6pkg3xh0os%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clwkkyjom00063b6pgbauempx%2522%252C%2522activeTabId%2522%253A%2522clwkkyjom00053b6pkg3xh0os%2522%257D%252C%2522clwkkyjom00043b6pby83x46u%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwkkyjom00033b6pw06tep9c%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clwkkyjom00043b6pby83x46u%2522%252C%2522activeTabId%2522%253A%2522clwkkyjom00033b6pw06tep9c%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by danielroe** [comment]
`npx serve .output/public` will just serve the static files.

To run a server, run `node .output/server/index.mjs`.

**Comment by phpmac** [comment]
Same, so can you try it? It's still a project engineering problem. I've invited you. The switching method is still the same, so I don't know if it's a bug in nuxt3.

**Comment by danielroe** [comment]
I'm closing as there's no reproduction - but that may just be a mistake as it seems like you might have tried to create one. Let me know if you have a reproduction and I'll happily reopen 🙏
