### ISSUE TITLE
navigateTo not working inside defineNuxtPlugin on initial render

### ISSUE THREAD

**Issue by theathleticnerd** [nuxt/nuxt#27335]
### Discussed in https://github.com/nuxt/nuxt/discussions/27301

<div type='discussions-op-text'>

<sup>Originally posted by **theathleticnerd** May 22, 2024</sup>
I'm trying to navigate the app to a path in my $fetch wrapper plugin. The url to be redirected to is being sent by the API.
If response._data.redirect is true, then it should redirect to response._data.redirect_url_path. 
The code below doesn't work on the initial render (while directly going to the particular url), but it does work after the app loads and the user navigates through the app to the particular url.

This is payload in case of a page that should be redirected:
```javascript
{
    "redirect":true,
    "redirect_url_path":"/xyz/def",
}
``` 

This is the code of the $fetch wrapper.
```typescript
// plugins/customFetch.ts
export default defineNuxtPlugin((nuxtApp) => {
  const config = useRuntimeConfig();
  const $customFetch = $fetch.create({
    baseURL: config.public.baseURL,
    async onRequest({ request, options, error }) {
      options.headers = {
        "X-PUBLIC-URL": `https://www.abcd.com${request}`,
      };
    },
    async onResponse({ response }) {
      if (response._data.redirect) {
        await navigateTo(response._data.redirect_url_path);
      }
    },
  });
  // Expose to useNuxtApp().$customFetch
  return {
    provide: {
      customFetch: $customFetch,
    },
  };
});
``` 
This is the code of the the useFetch wrapper composable
```typescript
// composables/serverFetch.ts
import type { UseFetchOptions } from "nuxt/app";
export function $serverFetch<T>(
  url: string | (() => string),
  options: UseFetchOptions<T> = {},
) {
  return useFetch(url, {
    ...options,
    $fetch: useNuxtApp().$customFetch,
  });
}
``` 
I have tried using nuxtApp.runWithContext and callWithNuxt but it is still not working.
I would greatly appreciate your help.
Thank you.</div>

**Comment by theathleticnerd** [comment]
I have attached a link to the code below:
https://stackblitz.com/edit/github-m9sk89?file=plugins%2FcustomFetch.ts

While this works after the app is loaded, it doesn't work during SSR.

navigateTo is being used inside the defineNuxtPlugin(), but still i'm getting the error: 
`A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function.`

**Comment by danielroe** [comment]
See the link in the error message. You will probably need to do nuxtApp.runWithContext. You're not calling it in the plugin, you're registering a hook that runs sometime later after an async operation.
