### ISSUE TITLE
Page navigation shows warning - Component is already mounted, please use $fetch instead

### ISSUE THREAD

**Issue by martinszeltins** [nuxt/nuxt#27336]
### Environment

````
------------------------------
- Operating System: Linux
- Node Version:     v20.11.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    -
- Package Manager:  pnpm@8.1.0
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------
````

### Reproduction

https://stackblitz.com/github/martinszeltins/nuxt-fetch-warning-middleware?file=middleware%2Fsettings.ts

### Describe the bug

I have 2 pages in my app - index and settings. When I navigate from the index page to the settings page it throws this warning in the console:

> [nuxt] [useFetch] Component is already mounted, please use $fetch instead. See https://nuxt.com/docs/getting-started/data-fetching

The settings page has a middleware that loads the settings from the API using `useFetch`.

I understand that I should use `$fetch` upon user interaction and `useFetch` on initial page load. In this case, I think I am using `useFetch` for the initial page load from inside the middleware. I need to use `useFetch` for SSR.

But I don't think this warning should be showing, something seems wrong.

**pages/settings.vue:**

```vue
<template>
    <div>
        <h1>About</h1>

        <div>
            <NuxtLink to="/settings">Settings</NuxtLink> | 
            <NuxtLink to="/">Home</NuxtLink>
        </div>
    </div>
</template>


<script setup lang="ts">
    definePageMeta({ middleware: ['settings'] })
</script>
```

**middleware/settings.ts:**

```ts
export default defineNuxtRouteMiddleware(async () => {
    // Load settings
    const { data: settings } = await useFetch('/api/settings')

    console.log(settings.value)
})
```

**Comment by afflexux** [comment]
[#27242](https://github.com/nuxt/nuxt/issues/27242)

**Comment by joerosenthal** [comment]
I get the same warning, and my site works fine in production, and I currently don't have a real work around without using useAsyncData once mounted. I assume in my case it's calling useNuxtData once things are mounted, but I'm not entirely sure. I'm happy with whatever behavior is occurring from a performance perspective, but I wish there were a kosher way of doing it.

**Comment by lc-btaylor** [comment]
Just throwing in my two cents here. The [documentation](https://nuxt.com/docs/api/composables/use-fetch) supports that _useFetch_ is designed for route middleware:
> useFetch is a composable meant to be called directly in a setup function, plugin, or route middleware.

It isn't a _huge_ issue since it isn't functionally impacting, but it is cosmetically annoying and spams my console logs during tests.
