### ISSUE TITLE
"How to Set Server Cookie in Nuxt 2, Multiple Users Requesting at the Same Time is a Confusion Problem"

### ISSUE THREAD

**Issue by huangguofei** [nuxt/nuxt#27344]
**Summary (generated)**:

Here is a brief summary of the text in English:

Environment: Node v16.20.2, Nuxt 2.15.8

Reproduction: The bug occurs when using cookie-universal-nuxt to set token in server's cookie and obtain token in nuxtServerInit in production environment.

Describe the bug: Occasional refreshing of non-logged-in page returns a token belonging to another user due to consistent headers returned by server when multiple users request at the same time.

Additional context: A screenshot is provided showing the inconsistent server-side DOM structure.

Logs: No response.

<hr>

### Environment

node: v16.20.2
nuxt: 2.15.8

### Reproduction

links: [www.seaart.ai](url)

### Describe the bug

In nuxt2, cookie-universal-nuxt is used to set the token and save it in the server's cookie, and obtain the token in nuxtServerInit and inject it into the state. In the production environment, occasionally refreshing the page without logging in will obtain the token returned by the server. The reason seems to be that when different users request at the same time, the headers returned by the server are consistent. The tokens obtained each time belong to other users. This problem has troubled me for a long time. Please help me find a solution. Thank you.
----------------------
I need to ensure that the user's login status can be obtained during server-side rendering and ensure that the page rendering is consistent. Otherwise, another bug will occur: the server-side DOM structure is inconsistent with the client's. Therefore, it is necessary to ensure that the server saves the user token synchronously to avoid the problem of consistent request headers when making simultaneous requests, resulting in a bug where the page is not logged in but has the token.

### Additional context

<img width="498" alt="image" src="https://github.com/nuxt/nuxt/assets/28044333/f5c28a1d-4197-4679-bcb4-91653134fa6e">

**Comment by huangguofei** [comment]
Thank you everyone, please help

**Comment by huangguofei** [comment]
It is impossible to provide relevant reproduction because this occurs in the production environment where multiple users request simultaneously. I suspect it is caused by server-side header confusion.

**Comment by huangguofei** [comment]
help me，please

**Comment by SultanMashukov** [comment]
Hello! Please share the solution to this problem. I have exactly the same problem, and it occurs under heavy load.
