### ISSUE TITLE
Can't define Expose be used after the request?

### ISSUE THREAD

**Issue by bbhxwl** [nuxt/nuxt#27367]
### Environment

{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "dependencies": {
    "@ant-design-vue/nuxt": "^1.4.1",
    "@nuxt/ui-pro": "^1.2.0",
    "@pinia-plugin-persistedstate/nuxt": "^1.2.0",
    "@element-plus/nuxt": "^1.0.9",
    "element-plus": "^2.7.3",
    "@pinia/nuxt": "^0.5.1",
    "ant-design-vue": "^4.2.1",
    "nuxt": "^3.11.2",
    "vue": "^3.4.27",
    "vue-router": "^4.3.2",
    "dayjs-nuxt": "^2.1.9",
    "@nuxtjs/device": "^3.1.1",
    "@vueuse/nuxt": "^10.9.0",
    "jwt-decode": "^4.0.0"
  }
}

### Reproduction
https://stackblitz.com/edit/github-hn5jfw?file=components%2Ftest.vue
If defineExpose is before useFetch, there will be no error, but it cannot expose refresh?

![image](https://github.com/nuxt/nuxt/assets/26525599/36cdb3cf-e191-459b-8152-99296ca448d7)
![image](https://github.com/nuxt/nuxt/assets/26525599/844c156c-2144-45c9-a878-f644dec017b9)
![image](https://github.com/nuxt/nuxt/assets/26525599/930114d1-1e1c-4cab-b937-2a3db2b894e4)

### Describe the bug
https://stackblitz.com/edit/github-hn5jfw?file=components%2Ftest.vue
If defineExpose is before useFetch, there will be no error, but it cannot expose refresh?

**Comment by manniL** [comment]
Not a nuxt issue but related to the `async` operation before. Remove `await` + check https://github.com/vuejs/core/issues/4930 for more details.
