### ISSUE TITLE
[nightly] generate/prerender doesn't work anymore

### ISSUE THREAD

**Issue by NamesMT** [nuxt/nuxt#27360]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v22.1.0
- Nuxt Version:     3.12.0-28612267.2f932698
- CLI Version:      3.11.1
- Nitro Version:    -
- Package Manager:  pnpm@9.1.2
- Builder:          -
- User Config:      devtools, future
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/NamesMT/nuxt-ssg-repro
https://stackblitz.com/github/namesmt/nuxt-ssg-repro

run `nuxt generate` then `nuxt preview` (and navigate to 200.html)

Example working example using stable version:
https://github.com/NamesMT/nuxt-ssg-repro/tree/stable-eg-2
https://stackblitz.com/github/namesmt/nuxt-ssg-repro/tree/stable-eg-2

### Describe the bug

SSG / generate / prerender is broken right now for `nuxt-nightly`, reproducible for both v4 schema and v3 schema.

The reproduction contains a simple `useAsyncData` that, if working normally should be statically generated once and no longer changes for later visit/refreshes.

`index.html` is also not generated.

**Comment by danielroe** [comment]
This is likely an upstream change in `nitropack` behaviour which we haven't yet updated Nuxt for.

With this in your `package.json` it works fine:

```json
  "resolutions": {
    "nitropack": "latest"
  },
```

cc: @pi0 in case it's an unexpected bug.
