### ISSUE TITLE
I don't think this is a bug. no-cors only supports content-types of application/x-www-form-urlencoded, multipart/form-data or text/plain.

### ISSUE THREAD

**Issue by clasterA** [nuxt/nuxt#27371]
**Summary (generated)**:

This is a bug. Because you can change content-types to any of "application/x-www-form-urlencoded", "multipart/form-data" or "text/plain" but with 'no-cors' your headers is fully removed.

<hr>

This is a bug. Because you can change content-types to any of this:
`application/x-www-form-urlencoded`,`multipart/form-data` or `text/plain`
but with ''no-cors' your headers is fully removed.

  useFetch(`/api/v1/abc`, {
    method: "GET",
    baseURL: "http://localhost:8081",
    mode: "no-cors",
    headers: {
      "Content-Type": "text/plain",
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET,POST,OPTIONS",
      "Access-Control-Allow-Credentials": "*",
      Authorization: `Bearer ${accessToken.value}`,
    },
  }).then((result) => {
    console.log("data ", result);
  })

and you can't ignore cors error

**Comment by danielroe** [comment]
Try this in your browser console:

```ts
fetch('https://jsonplaceholder.typicode.com/todos/1', {
  method: "GET",
  mode: "no-cors",
  headers: {
    "Content-Type": "text/plain",
    "Access-Control-Allow-Origin": "",
    "Access-Control-Allow-Methods": "GET,POST,OPTIONS",
    "Access-Control-Allow-Credentials": "",
    Authorization: `Bearer Bob`,
  }
}).then((result) => {
  console.log("data ", result);
})
```

Then inspect the request.

![CleanShot 2024-05-27 at 12 03 20@2x](https://github.com/nuxt/nuxt/assets/28706372/1d013e4d-ae70-45b6-99b2-7a6302fbf105)

You can see that only a subset of headers is allowed/passed on. This is the Fetch specification, which is a browser API.

If `useFetch` differs from this, please provide a reproduction and I'll happily reopen.

**Comment by clasterA** [comment]
The problem with mode: "no-cors", is that it completely removes user-set header settings.
And it has nothing to do with the selected content type as you write in your comment in the previous ticket.

[danielroe](https://github.com/danielroe) commented [on Jan 30, 2023](https://github.com/nuxt/nuxt/issues/15466#issuecomment-1407808466)
I don't think this is a bug. no-cors only supports content-types of application/x-www-form-urlencoded,multipart/form-data or text/plain.

**Comment by danielroe** [comment]
Are you talking about the behaviour of the Fetch API or `useFetch`? Would you provide a reproduction that shows a bug here?

**Comment by danielroe** [comment]
See https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#supplying_request_options.

![CleanShot 2024-05-28 at 09 14 00@2x](https://github.com/nuxt/nuxt/assets/28706372/ab2712b4-f8d8-492a-8f3a-383118f081a7)
