### ISSUE TITLE
No control over <head> in server components

### ISSUE THREAD

**Issue by MatthiasRossbach** [nuxt/nuxt#27381]
### Environment

- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, experimental
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-zsncjd?file=pages%2Findex.server.vue

### Describe the bug

Usually, you can change Head subproperties either with template, useHead, useSeoMeta or useServerSeoMeta. This works fine - unless it is a .server. component. Neither of the described functions work there. If you rename the server component back to a normal one, it works as expected. 

### Additional context

This is required for SEO optimization.

### Logs

```shell-script
There are no error logs
```

**Comment by huang-julien** [comment]
Hi :wave: thanks for the issue.

This is intended in the first implementation of islands. But having this for pages makes sense :+1:
