### ISSUE TITLE
Tailwindcss added at last is not applied

### ISSUE THREAD

**Issue by bippan1407** [nuxt/nuxt#27385]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.11.1`
- Nuxt Version:     `3.11.2`
- CLI Version:      `3.11.1`
- Nitro Version:    `2.9.6`
- Package Manager:  `yarn@4.2.2`
- Builder:          `-`
- User Config:      `devtools`, `debug`, `hooks`, `modules`, `plugins`, `nitro`, `runtimeConfig`, `dayjs`, `postcss`, `app`, `css`, `apollo`, `carousel`, `tour`, `vue`, `routeRules`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.12.0`, `@nuxtjs/device@3.1.1`, `@nuxt/image@1.4.0`, `@pinia/nuxt@0.5.1`, `@pinia-plugin-persistedstate/nuxt@1.2.0`, `dayjs-nuxt@2.1.9`, `vue3-carousel-nuxt@1.1.1`, `@nuxtjs/apollo@5.0.0-alpha.14`, `nuxt-tour@0.0.9`, `@nuxtjs/i18n@8.3.1`
- Build Modules:    `-`

### Reproduction

Cannot reproduce the issue either on new repo or stackblitz

Using 

 "nuxt": "^3.11.2",
 "@nuxtjs/tailwindcss": "^6.12.0",

### Describe the bug

In the below image in nuxt 3 bg-transparent is added at last but it is overridden by bg-yocket-neutral-100

<img width="647" alt="Screenshot 2024-05-28 at 5 46 06 PM" src="https://github.com/nuxt/nuxt/assets/45727492/081685a9-7c97-4f4e-8449-e3f0bfbc0719">

In nuxt 2 the behaviour was opposite
<img width="1115" alt="Screenshot 2024-05-28 at 5 52 22 PM" src="https://github.com/nuxt/nuxt/assets/45727492/f4d6d5f5-d323-4312-bb37-46a4fb52f776">

This same thing is happening throughout the project

**Comment by manniL** [comment]
> Cannot reproduce the issue either on new repo or stackblitz

Then it is most likely not a Nuxt issue ☺️

**Comment by bippan1407** [comment]
Parent Component
 <Child class="border border-blue-800 border-yellow-500 bg-transparent" />

Child Component
<template>
  <div
    class="bg-slate-700 w-20 h-20 border-8 border border-red-800"
  >
    TEST
  </div>
</template>


Parent component CSS added should override already defined CSS
@manniL

**Comment by bippan1407** [comment]
There is another tailwind css issue similar to current issue related to CSS specificity, css does not remain consistent when dev server is restarted.

I have recorded the issue.

https://drive.google.com/file/d/1HJ7y2opGSoUkSgCzK8qnnvyvtcPbE2ig/view?usp=drive_link

Github link for code - https://github.com/bippan1407/nuxt-explore/tree/tailwind-issue

CSS specificity while working on dev and after restarting the dev should remain same @manniL
