### ISSUE TITLE
Disabling SSR prevents remaining CSS from loading

### ISSUE THREAD

**Issue by hichem-dahi** [nuxt/nuxt#27387]
### Environment

- Operating System: Linux
- Node Version:     v18.20.2
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.5.0
- Builder:          -
- User Config:      ssr, css, devtools, modules, colorMode
- Runtime Modules:  @nuxt/ui@2.16.0, @pinia/nuxt@0.5.1, @vueuse/nuxt@10.9.0
- Build Modules:    -

### Reproduction

https://stackblitz.com/~/github.com/hichem-dahi/trello-nuxt

### Describe the bug

Setting `ssr: false` in nuxt config prevents remaining CSS from loading.

### Additional context

Works fine for Firefox 126.0 (64-bit), doesn't work for Chrome 125.0.6422.60 (Official Build) (64-bit).
![Screenshot from 2024-05-28 12-14-45](https://github.com/nuxt/nuxt/assets/57720465/3bae0a03-f9e4-4bc8-ad1c-e192101374ba)
![Screenshot from 2024-05-28 12-15-21](https://github.com/nuxt/nuxt/assets/57720465/ede88b47-6fc5-4824-839b-31c6a1fdec74)

**Comment by manniL** [comment]
Can you double-check if that also happens on [nightly](https://nuxt.com/docs/guide/going-further/nightly-release-channel)?

**Comment by hichem-dahi** [comment]
@manniL same issue.
- Nuxt Version:     3.12.0-28613622.d1ac12c9

**Comment by hichem-dahi** [comment]
I cleared the cache and now it's working fine!

**Comment by Ragura** [comment]
I can confirm this is indeed a cache invalidation problem. Once solved by clearing/disabling cache, it remains solved, but it's kind of weird that it occurs in the first place. In my case I had it happen when importing css from font-awesome while `srr: true`, then changing it to `ssr: false` which caused the cache problem. Not a big deal in this case, but it might be an indicator of other caching issues that could be hard to debug.

**Comment by danielroe** [comment]
Ahh, this is likely due to a Vite issue - IIRC, in some situations css is imported as JavaScript (which is executed and injects the CSS) vs a CSS file. There have been issues with setting the appropriate cache headers.
