### ISSUE TITLE
Error: Cannot find module punycode/

### ISSUE THREAD

**Issue by github19938** [nuxt/nuxt#27388]
### Environment

"nuxt": "^3.11.2"

### Reproduction

![screenshot-20240529-002240](https://github.com/nuxt/nuxt/assets/23568108/cb3a288c-68f3-4bf7-9d90-64b6358026cd)

### Describe the bug

when: yarn build

![screenshot-20240529-002240](https://github.com/nuxt/nuxt/assets/23568108/4449a042-295b-4afc-8c35-b22505017517)

**Comment by Tuscan-blue** [comment]
Try to downgrade the nodejs version.
https://nodejs.org/api/punycode.html#punycode
https://github.com/yarnpkg/yarn/issues/9005

**Comment by github19938** [comment]
I tried：node v20.13.1， v22.2.0 ，v18.20.2  and yarn  v1.22.19 ,v1.22.20,v1.22.21

However, it is still the same mistake

Can you tell me a specific and correct version

thank you!

**Comment by Tuscan-blue** [comment]
I can't reproduce it, so I can't provide a specific version. I have previously encountered this issue.
Maybe you colud try `npm install punycode`, `yarn install punycode`? 
@github19938 

If the error persists, you may also consider the following steps:
1. delete the `node_modules` directory and `package-lock.json` and `yarn.lock` file
- [optional: `npm cache clean --force`, `yarn cache clean`]
2. close the project and reopen it in the IDE
3. run `npm install` or `yarn install`
4. run `npm install punycode` or `yarn install punycode`
I hope these could help you.

**Comment by github19938** [comment]
I tried your method, but it didn't work.
this is my code ，Hope you can help me find the problem，
when run：yarn build，It will report this error
yarn version：1.22.22
node version：21.7.1
![screenshot-20240529-002240](https://github.com/nuxt/nuxt/assets/23568108/aa844b60-7081-484f-9342-aef958ea5c87)

I really hope to get your help, I am a beginner
thank you
@Tuscan-blue

**Comment by Tuscan-blue** [comment]
![image](https://github.com/nuxt/nuxt/assets/141131070/929220f0-3151-4e50-9345-08edd7ea0bca)
nodejs v18.1.0
Success with 'npm run build'
@github19938

**Comment by github19938** [comment]
Thank you very much. It has been resolved

**Comment by github19938** [comment]
hi friend，Do you know the cause of this problem?
#27402 
Looking forward to your answer
@Tuscan-blue

**Comment by Tuscan-blue** [comment]
> hi friend，Do you know the cause of this problem? #27402 Looking forward to your answer @Tuscan-blue
I cannot reproduce this error.
