### ISSUE TITLE
keepalive not work

### ISSUE THREAD

**Issue by weiquanju** [nuxt/nuxt#27394]
### Environment

```log
Nuxt project info:                                                                                                                                           21:02:54

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.10.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  pnpm@9.1.3
- Builder:          -
- User Config:      devtools, app, ssr
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Reproduction

The feature keepalive is not work.
#### Minimal reproduction
The [Github Repository](https://github.com/weiquanju/nuxt-keepalive-failed) has 2 branch, `main` and `spa-mode`.
Both branch dosn't work.
If it is a usage error, is it convenient to provide a demo.

### Describe the bug

Enter each page, when there is a button on the page, click the button once to return to the homepage, and then browse each page in sequence. 
The page with the button is expected to be the last clicked value. But in fact, it is the initial value.

**Comment by danielroe** [comment]
You are using `<RouterView>` and not `<NuxtPage>`. Once you change that, everything works fine 👌 

https://stackblitz.com/edit/github-3yhqux?file=pages/user.vue,pages/dashboard.vue,app.vue
