### ISSUE TITLE
"Error: Unable to find component 'path to the component' in the directory 'path to the directory'. The error message 'Cannot read property 'length' of undefined' indicates that there is a bug with nested folder of components.

### ISSUE THREAD

**Issue by jackieveev** [nuxt/nuxt#27425]
**Summary (generated)**:

Here is a brief summary in English of the issue:

The issue is about a Nuxt.js project where components are not being detected when there is a subfolder (e.g. "foo") in the "components" directory. When this subfolder exists, the component "Bar" under the "components" folder cannot be used even though it's correctly imported in the code. The error is triggered when the "components" configuration is disabled in the "nuxt.config.ts" file, specifically when "pathPrefix: false" is set.

<hr>

### Environment

- Operating System: Windows_NT
- Node Version:     v18.20.2
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  pnpm@9.1.4
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-z9zdey?file=app.vue,nuxt.config.ts,components%2Fbar.vue

### Describe the bug

When there is a sub folder(eg: foo and component test.vue inside) in components, <code>\<FooTest \/\></code> would be working well, but if I disable the auto prefix in nuxt.config.ts
```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  components: [
    {
      path: '~/components/foo',
      pathPrefix: false,
    },
  ],
})
```

I will get this error
<img width="595" alt="image" src="https://github.com/nuxt/nuxt/assets/32574201/7da86886-5834-41aa-8e33-70c364736a1f">

The component Bar under components folder can not be detected and used.

**Comment by danielroe** [comment]
The issue is that you are not registering `~/components`. Add it to the end of your component dirs and you should be good.

https://stackblitz.com/edit/github-z9zdey-kfcld3?file=app.vue,nuxt.config.ts,components/bar.vue
https://nuxt.com/docs/guide/directory-structure/components#custom-directories
