### ISSUE TITLE
Transitions with comments in pages creates warning + failed to render next route

### ISSUE THREAD

**Issue by zguig52** [nuxt/nuxt#27436]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.14.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  yarn@1.22.22
- Builder:          -
- User Config:      app, devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-edfk45?file=pages%2Fabout.vue

I just used the example documentation from Nuxt and added some comments in the page.

### Describe the bug

When using comments in the template section of a page, combined with page transition activated (similar behavior is found also with layout transition), following bug is created:
- on page load, in browser dev console, this FALSE POSITIVE warning appears: [nuxt] `/home/projects/paripjqkq.github/pages/index.vue` does not have a single root node and will cause errors when navigating between routes.
- when trying to navigate to other pages, the rendering fails

**Comment by danielroe** [comment]
Unfortunately comments are nodes as well and this is a limitation of Vue Transitions - they must have a single root node/element.

See https://nuxt.com/docs/guide/directory-structure/pages#usage.

![CleanShot 2024-06-05 at 22 05 18@2x](https://github.com/nuxt/nuxt/assets/28706372/29724894-4c8f-4938-8580-d109f8952c23)
