### ISSUE TITLE
Passing date from frontend to server

### ISSUE THREAD

**Issue by imzoloft** [nuxt/nuxt#27448]
### Environment

- Operating System: Darwin
- Node Version:     v22.0.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.5.1
- Builder:          -
- User Config:      devtools, runtimeConfig, modules
- Runtime Modules:  @samk-dev/nuxt-vcalendar@1.0.3
- Build Modules:    -

### Reproduction

Not required IMO.

### Describe the bug

When I pass a date to my backend, the date that I received is now a string, which means I have to set the string to a date and after can call getDay, etc.

const response = await $fetch('/api/checkout', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        startDate: new Date(range.value.start),
        endDate: new Date(range.value.end),
      }),
    });
    
   const { startDate, endDate }: CheckoutBody =
    await readBody(event);
  console.log(startDate.getDay());

### Logs

```shell-script
[request error] [unhandled] [500] startDate.getDay is not a function
```

**Comment by manniL** [comment]
because `startDate` will be the stringified date. Bodies will be converted into JSON before being sent (if you sent a JS object) - in this case, you already to it on your own (but wouldn't have to)
