### ISSUE TITLE
Normal plugin depending on a server-only one causes an error

### ISSUE THREAD

**Issue by CernyMatej** [nuxt/nuxt#27457]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.9.0`
- Nuxt Version:     `3.11.2`
- CLI Version:      `3.11.1`
- Nitro Version:    `2.9.6`
- Package Manager:  `pnpm@9.0.6`
- Builder:          `-`
- User Config:      `extends`, `plugins`, `googleFonts`, `css`, `vite`, `i18n`, `runtimeConfig`, `alias`, `features`, `experimental`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-q8ahjp?file=plugins%2Fb.ts,plugins%2Fa.server.ts

### Describe the bug

When a normal nuxt plugin specifies a server-only plugin in its dependencies, an error message is shown in the console:
```
 ERROR  Plugin b depends on a but they are not registered. 
 ```
 
I'm not sure whether it actually affects anything, but even the error message should probably not show up.

**Comment by danielroe** [comment]
I think this makes sense, as the dependency is unavailable on the client...

Why do you think:
> I'm not sure whether it actually affects anything, but even the error message should probably not show up.

**Comment by CernyMatej** [comment]
It's a tricky situation. On one hand, it makes complete sense to show an error message when a dependency is not available on the client. However, in use cases like mine — where I want it to be a dependency on the server but not on the client — it might be misleading.

Maybe I'm thinking about it wrong…

I'm using the plugin to fetch some initial configuration on the server and store it in shared state using `useState`.

I removed the `.server` suffix from the dependency and added an early return when executed on the client to make the error message go away.

**Comment by danielroe** [comment]
The error is to flag up to users who may be unaware. I think in your case handling it manually is right.

It's common, for example, to have a server plugin injecting something, e.g. `$someVar`, which is not accessible on the client, and for users to think this is a Nuxt bug.

I think specifying a hard dependency on another plugin means it's _needed_, and we can't just assume that the user has accounted for it not being available on the client side.

So I think we'll leave this as is, but please do feel free to circle back if you think there's a better solution (or better log message)! 🙏
