### ISSUE TITLE
if computed returns a object {} and await in setup, triggering the watch callback and causing an infinite loop.

### ISSUE THREAD

**Issue by green-mike** [nuxt/nuxt#27454]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.9.0`
- Nuxt Version:     `3.11.2`
- CLI Version:      `3.11.1`
- Nitro Version:    `2.9.6`
- Package Manager:  `pnpm@9.1.2`
- Builder:          `-`
- User Config:      `telemetry`, `modules`, `features`, `experimental`, `imports`, `vite`, `content`, `runtimeConfig`, `app`, `css`, `elementPlus`, `routeRules`, `devtools`, `vueuse`, `unocss`, `gtm`
- Runtime Modules:  `@vueuse/nuxt@10.9.0`, `@pinia/nuxt@0.5.1`, `@nuxt/content@2.12.1`, `@element-plus/nuxt@1.0.9`, `@unocss/nuxt@0.60.3`, `@zadigetvoltaire/nuxt-gtm@0.0.13`, `@nuxt/eslint@0.3.13`, `@nuxt/test-utils/module@3.13.1`
- Build Modules:    `-`

### Reproduction

[trigger in setup](https://stackblitz.com/edit/github-gfd69j?file=app.vue)
[trigger in watch immediate](https://stackblitz.com/edit/github-gfd69j-wdfrel?file=app.vue)
[Vue SFC Playground not trigger recursive](https://play.vuejs.org/#eNqdVE2P2jAQ/SujXMhKUVDVnrYs0rbaQyu1Rbuol80eXGcgBseO/BFAKP+9YydkoSpVtRyQPfPmzZsP55jcN03eekxuk5nlRjQOLDrfzAsl6kYbB5913cDK6Bom+TRcAnzysVCzaR9AULo4rBvJHNINYFaKNh7o+ORtg8r2jmgJJPNZ5DqBpheo2bSPn03PWJMscZZrtRLrfGO1IsXHAC4STkRCovnROKGVLZJbiJ7gY1Lq3ddoc8ZjdrLzCvn2L/aN3QdbkSwMWjQtFsnoc8ys0fXuh6fvuKfz6Kx16SWh/+F8RKulDxp72CevSpJ9hotqv8S+C7Ve2oe9o6acigpCA7KL+CKhOYQeXiv9Ve77/EOMK1RHXTzN8PrIjxBa6h2WGeyY4xV0wwYMo6cxWAdGE+QnM4L9kmjhboxK0xu4m/dKDFEbBceOwrob+isU2zHhoNZ8e28Piqe9NSZKLzkzOGMKSbXEXOp1OrnETbI/xOQtkx4D8ZDzbcGkNSiElVc8NPhc9EV5CnewoA4Ji2lKm6Nli6/KITR4KWqkNOe9Cb8BnE4C9SQkDdYug3f9Oeqnyf3fa3tWwhn9As9eVSxsV/mIG4zaX+Ab24va15SSe2NFi+Cbkkgs4J4jlljmsKyEhRoZ7VIkPGgPFSMoozBGRHTE1YoowVXMQUB7x8K6gnAW9E5BifSUS1RcEDWpIKQf6MbU8kDrLNZrNEMkylUOC22toBGA1d5wihaKS19i3CytUFHWofLhzZiQyYwDyoaSSqi03oI2/f4Somccgfn170z3G9pBvs4=)

### Describe the bug

This code causes recursive updates because the computed property routeVariables returns a new object {} each time it is accessed. When mockAsync is awaited, the watch callback is triggered, leading to an infinite loop.
Reporting this bug because the documentation does not indicate that computed values cannot be used in the setup or watch immediate contexts. Moreover, no error messages appear in the Vue SFC Playground. I suspect Nitro might be causing this issue. My actual use case is more complex, requiring URL parsing, then calling an API, and setting the return value as the initial value. Therefore, it took considerable time to narrow down and reproduce the issue. During this period, I found that using the oldValue of a computed property to avoid object updates or using newValue in watch can mitigate the problem. However, since there are no errors in the Vue SFC Playground and no hints in the documentation, this is still a valuable case to report.

**Comment by manniL** [comment]
This is a actually a Vue issue! Here is a [Vue-SSR only reproduction](https://stackblitz.com/edit/github-jxndex?file=src%2FApp.vue&terminal=dev). Could you raise it in https://github.com/vuejs/core?

**Comment by green-mike** [comment]
Thank you for identifying this issue with Vue! We'll raise it on the Vue.js GitHub repository. Your feedback is appreciated.

**Comment by manniL** [comment]
Tracking in https://github.com/vuejs/core/issues/11078 then 👍
