### ISSUE TITLE
[3.12.1] prerender broke when using `nuxt-seo`'s `robots`

### ISSUE THREAD

**Issue by NamesMT** [nuxt/nuxt#27490]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v22.2.0
- Nuxt Version:     3.12.0-28630014.af65d596
- CLI Version:      3.11.2-1717084152.03d4a54
- Nitro Version:    2.10.0-28629495.e316df32
- Package Manager:  pnpm@9.2.0
- Builder:          -
- User Config:      devtools, modules, site
- Runtime Modules:  @nuxtjs/seo@2.0.0-rc.10
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/github/NamesMT/repro-ssg-seo
https://github.com/NamesMT/repro-ssg-seo

### Describe the bug

*I have overrides `nitropack` to `latest` and confirm prerender work in other cases.*

When Nuxt SEO is installed, `nuxt-nightly` SSG prerender broke regardless of schema version (compatibilityVersion).
It does not throw an error but continues normally without generating `index.html` and `payload` files.

By bisecting the enabled module, I have scoped it down to the `robots` module, by disabling just the `robots` module prerender would work again.

### Additional context

Does not happens with stable nuxt `3.11`.

**Comment by danielroe** [comment]
cc: @harlan-zw

**Comment by NamesMT** [comment]
Tested for `3.12.1` and is breaking, changed issue title.

**Comment by danielroe** [comment]
This is not a bug in robots. For now you can work around with this config:

```ts
export default defineNuxtConfig({
  nitro: {
    prerender: {
      routes: ['/']
    }
  },
})
```

**Comment by harlan-zw** [comment]
Thank you Daniel :medal_sports:
