### ISSUE TITLE
Ref variable shared from page to two components has different value in <template> and in <script>

### ISSUE THREAD

**Issue by lmc3s3f0r** [nuxt/nuxt#27528]
### Environment

- Operating System: Linux
- Node Version:     v20.10.0
- Nuxt Version:     3.12.0
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  @nuxtjs/tailwindcss@6.12.0
- Build Modules:    -

### Reproduction

https://github.com/lmc3s3f0r/bug_vue_ref_through_components

1 - Launch the app and keep the browser console open.

2 - Every 3 seconds, a console.log will be fired from app.vue, comp1.vue and comp2.vue, showing the content of a variable shared from app.vue to comp2.vue through comp1.vue. The first time, you'll see the content of the three logs is the same.

3 - Now try either deleting one of the names in the page or all of them with the "Delete all" button.

4 - Wait 3 seconds and check the content of the three logs. "DATA IN APP" will display the updated list with whatever you removed, but "DATA IN COMP1" and "DATA IN COMP2" will still show the previous content. However, in the page, the content is updated in app and the two components (the lines "(debug) Data in App/component 1/component 2" show the same data).

5 - No need to use the "add" button. Adding new items works perfectly. It's there in case you want to add more entries for testing.

### Describe the bug

A ref variable shared from a page to a second-level component through another component is not properly updated through emits from the second component back to the page. The content shown in the <template> section in the components differ from the content displayed in <script> with a console.log.

### Additional context

This comes from a big web app I'm working on. The reproduction repo might make no sense but it does in the app context XD

The issue is that, having a ref variable sent as a prop from a page to a couple of components (parent and child), firing a "delete" operation from the child component back to the page (or app.vue) doesn't update the content in the <script> section of the two components (it does in the template, weirdly enough).

**Comment by Eckhardt-D** [comment]
Hi @lmc3s3f0r are you sure this is a bug or is it not perhaps related to this line: https://github.com/lmc3s3f0r/bug_vue_ref_through_components/blob/ef4ae516637406d4bc2efe30fb6392c3d6541b7f/components/comp2.vue#L30 ?

As far as I know, destructuring props like this causes a loss in reactivity. [see here](https://vuejs.org/guide/extras/reactivity-transform.html#reactive-props-destructure) (point 1.)

**Comment by lmc3s3f0r** [comment]
Oh, didn't know that. 

In that case, why does it work when adding new items but not when deleting, when it's (supposedly) the same (modifying the original array from an emit in a child component)?

**Comment by lmc3s3f0r** [comment]
Ok, so whatever the reason it works for adding but not for removing items, I found that to make it work, instead of this props destructure:

const { carriers } = defineProps<comp1Props>();

I should use:

const props = defineProps<comp1Props>()
const { carriers } = toRefs(props)
