### ISSUE TITLE
using regular `form` with post method throws 404 `Error: Page not found: /api/v1/oauth on Cloudflare pags/workers bug`

### ISSUE THREAD

**Issue by samk-dev** [nuxt/nuxt#27545]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.14.0`
- Nuxt Version:     `3.11.2`
- CLI Version:      `3.11.1`
- Nitro Version:    `2.9.6`
- Package Manager:  `pnpm@8.15.6`
- Builder:          `-`
- User Config:      `devtools`, `modules`, `app`, `runtimeConfig`, `build`, `nitro`
- Runtime Modules:  `@nuxt/ui@2.16.0`, `@nuxt/eslint@0.3.13`
- Build Modules:    `-`

### Reproduction

https://github.com/samk-dev/nuxt-appwrite-node

### Describe the bug

I am working on a starter that uses `Appwrite` as backend and `Nuxt/Nitro`

I have a form in `pages/login.vue` that has a normal form that uses oauth. When submitting the form only in Cloudflare pages/workers throws `404 Error: Page not found: /api/v1/oauth on Cloudflare pags/workers bug`. Everything works fine locally and in a `docker` deploy on my home server and also works great.

_I have tried with the domain and just /api/v1/oauth_
```vue
<form :action="`${config.public.appDomain}/api/v1/oauth`" method="post">
   <input type="hidden" name="provider" value="spotify" />
  <UButton type="submit" variant="soft">Sign up with Spotify</UButton>
</form>
```

### Additional context

Cloudflare logs doesn't show any error. All requests has 200 status

**Comment by danielroe** [comment]
Would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏

**Comment by samk-dev** [comment]
Hey Daniel, sure. I'll make a reproduction with pure nitro and see what happens. Thanks 🙏

**Comment by samk-dev** [comment]
Hey @danielroe, the problem disappeared after updating to `3.12.2` can I close the issue?

**Comment by danielroe** [comment]
Great!! 🙌
