### ISSUE TITLE
Nuxt 3.12.1 Error: does not provide an export named 'setupDevtoolsPlugin'

### ISSUE THREAD

**Issue by mrchoke** [nuxt/nuxt#27544]
### Environment

Nuxt project info:                                                                                                        1:06:56 AM (+7)

------------------------------
- Operating System: Linux
- Node Version:     v20.12.0
- Nuxt Version:     3.12.1
- CLI Version:      3.12.0
- Nitro Version:    -
- Package Manager:  pnpm@9.3.0
- Builder:          -
- User Config:      devtools, future, modules, css, i18n, quasar, experimental, plugins, imports, proxy, routeRules, app
- Runtime Modules:  @nuxt/eslint@0.3.13, @pinia/nuxt@0.5.1, nuxt-zod-i18n@1.8.0, @nuxtjs/i18n@8.3.1, @vueuse/nuxt@10.10.1, @vee-validate/nuxt@4.13.1, nuxt-quasar-ui@2.1.2, @pinia-plugin-persistedstate/nuxt@1.2.0, @nuxt-alt/proxy@2.5.8
- Build Modules:    -
------------------------------

### Reproduction

Error: upgrade from Nuxt 3.11.2 to 3.12.1
Work: downgrade to Nuxt 3.11.2

### Describe the bug

it show message
```
The requested module '/_nuxt/node_modules/.pnpm/@vue+devtools-api@6.6.3/node_modules/@vue/devtools-api/lib/cjs/index.js' does not provide an export named 'setupDevtoolsPlugin'

```
![Screenshot 2024-06-12 at 01 12 14](https://github.com/nuxt/nuxt/assets/3403645/c7e1ba16-65c4-454d-98d5-0298f6ad358b)

### Logs

```shell-script
nuxt.js?v=130e9795:122 [nuxt] error caught during app initialization SyntaxError: The requested module '/_nuxt/node_modules/.pnpm/@vue+devtools-api@6.6.3/node_modules/@vue/devtools-api/lib/cjs/index.js' does not provide an export named 'setupDevtoolsPlugin' (at index.mjs?v=130e9795:79:15)Caused by: SyntaxError: The requested module '/_nuxt/node_modules/.pnpm/@vue+devtools-api@6.6.3/node_modules/@vue/devtools-api/lib/cjs/index.js' does not provide an export named 'setupDevtoolsPlugin' (at chunk-IYZISRBI.js?v=130e9795:3:10)
```

**Comment by ZTL-UwU** [comment]
I'm able to reproduce this with the vee-velidate zod integration.
https://stackblitz.com/~/github.com/ZTL-UwU/nuxt-3.12.1-setupDevtoolsPlugin-repro

**Comment by vasilistotskas** [comment]
Im facing same error after updating nuxt to 3.12.1 and using :
```
  future: {
    compatibilityVersion: 4,
  },
```
The error is:

`Uncaught SyntaxError: The requested module '/_nuxt/@fs/C:/Dev/grooveshop-dev/grooveshop-storefront-ui-node-nuxt/node_modules/.pnpm/@vue+devtools-api@6.6.3/node_modules/@vue/devtools-api/lib/cjs/index.js' does not provide an export named 'setupDevtoolsPlugin' (at vee-validate.esm.js:7:10)`

Im running pnpm version 9.3.0

**Comment by vasilistotskas** [comment]
After adding `"@vue/devtools-api": "6.6.3",` as a dev dependency the error gone

**Comment by danielroe** [comment]
I wonder if we need to add `@vue/devtools-api` to `vite.optimizeDeps.include`. cc: @antfu

**Comment by shaunnbarron** [comment]
> After adding `"@vue/devtools-api": "6.6.3",` as a dev dependency the error gone

This works for me in dev, but building is a no-go.

**Comment by danielroe** [comment]
This seems to be an upstream issue. I think the following should resolve it for you:

```ts
export default defineNuxtConfig({
  vite: {
    optimizeDeps: {
      exclude: ['vee-validate']
    }
  },
  modules: ['@vee-validate/nuxt'],
})
```

This may be worth adding to the `@vee-validate/nuxt` module, but I'm a little unsure as `vee-validate` does not expose a valid ESM build - and does not have export conditions either.

cc: @antfu

**Comment by ibqn** [comment]
I have added ` <VueQueryDevtools />` component as suggested here in the documentation https://tanstack.com/query/latest/docs/framework/vue/devtools and ended up with the same error, unless I install a suggested workaround i.e.`@vue/devtools-api` package explicitly.

**Comment by yunyuyuan** [comment]
If you're using pnpm and the method provided by @danielroe doesn't work, you can create a `.npmrc` file in the root directory with the content `shamefully-hoist=true`, which should resolve the issue.

**Comment by abh1nash** [comment]
Nothing mentioned here worked for me. Instead, I disabled auto imports for vee-validate and manually imported the components wherever needed.

**Comment by c0nd3v** [comment]
@danielroe This is still a problem

**Comment by cybertino** [comment]
+1

**Comment by logaretm** [comment]
I published vee-validate `v4.14.0` that defines the `exports` fields in the `package.json` files to fix other issues. It looks like it fixed this as well as I have tested it against the linked [demo here](https://stackblitz.com/~/github.com/ZTL-UwU/nuxt-3.12.1-setupDevtoolsPlugin-repro).

**Comment by logaretm** [comment]
I checked again. v4.14.0 solves the auto import and resolution issues with `vee-validate` itself but It doesn't solve the `@vue/devtools-api` issue. I think this will happen with any lib that uses the devtool as a dependency.

One work around is to manually install it:

```sh
pnpm add @vue/devtools-api
```

**Comment by murshex** [comment]
It doesn’t happen with every lib because I have other libs that depend on it and don’t cause this issue @logaretm

**Comment by mrchoke** [comment]
@logaretm  

Thank you very much for addressing and fixing this issue. After testing without adding `exclude: ['vee-validate']` in the vite optimizeDeps option, I found that everything now works correctly without throwing any errors. 

I tested this with Nuxt 3.13.2. 

Thanks again for your hard work!

**Comment by avinmaster** [comment]
The same error with nuxt-aos, pnpm installation is broking it.

**Comment by behruzchick** [comment]
You should install another version of cookie and @supabase/ssr

npm install @supabase/ssr@0.1.4

npm install cookie@0.5.0
