### ISSUE TITLE
`definePageMeta` overwrites meta defined during `pages:extend` hook.

### ISSUE THREAD

**Issue by killjoy1221** [nuxt/nuxt#27547]
### Environment

❯ npx nuxi info
Working directory: /home/projects/github-bxdlen-q4by65
Nuxt project info: 

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.1
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, experimental, hooks
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-bxdlen-q4by65?file=pages%2Findex.vue

### Describe the bug

I'm using the hook `pages:extend` to generate built-time metadata for each page.

```ts
// nuxt.config.ts
export default defineNuxtConfig({
  hooks: {
    "pages:extend": (pages) => {
      for (const page of pages) {
        page.meta ??= {}
        page.meta.buildconfig = "something"
      }
    }
  }
})
```

Starting with Nuxt 3.12.0 and with `experimental: { scanPageMeta: true }` (the default), the meta assigned by the hook is ignored if the page defines its own meta via `definePageMeta({something: "..."})`

In the linked stackblitz, index.vue and index2.vue both have the correct meta created by the hook. However index3.vue defines a meta `foo: "Bar"`, and is the only meta defined.

**Comment by danielroe** [comment]
For now you can work around with:

```ts
export default defineNuxtConfig({
  experimental: {
    scanPageMeta: false
  }
})
```

**Comment by killjoy1221** [comment]
I think a possible fix would be to use defu for this line instead of `Object.assign`.

https://github.com/nuxt/nuxt/blob/d202669611d3d1e8f8078e6d7f2e1f7552bae9ba/packages/nuxt/src/pages/utils.ts#L146

**Comment by lhlyu** [comment]
Note: In `nuxt@3.15.1`, with `experimental.scanPageMeta = false`, use the `pages:resolved` hook to ensure meta properties are properly overridden.
