### ISSUE TITLE
Debugging Stops Working with TypeScript

### ISSUE THREAD

**Issue by aetherealtech** [nuxt/nuxt#27543]
### Environment

- Operating System: Darwin
- Node Version:     v21.7.3
- Nuxt Version:     2.17.3
- CLI Version:      3.12.0
- Nitro Version:    -
- Package Manager:  npm@10.5.0
- Builder:          webpack
- User Config:      head, css, plugins, components, buildModules, modules, build
- Runtime Modules:  primevue/nuxt
- Build Modules:    @nuxt/typescript-build@2.1.0

### Reproduction

Create a new Nuxt 3 app, and replace the `Tutorial` component with this:

```
<script setup>
import { ref } from "vue";

const counter = ref(0)

function increment() {
  counter.value++
}
</script>

<template>
  <button @click="increment">Count is: {{ counter }}</button>
</template>
```

Run the app in dev mode with `npm/yarn run dev`. Debug the app in WebStorm (2024.1.4) using a JavaScript Debug configuration.  Add a breakpoint inside the `increment` function, click the button and confirm the breakpoint is hit.

Add `lang=ts` to the opening `script setup` tag.  Reload the page, click the button.  The breakpoint is no longer hit.  Remove `lang=ts` and reload again, confirm the breakpoint is hit again.

### Describe the bug

Turning on TypeScript by adding `lang=ts` to the `script setup` in a `vue` source file causes breakpoints to stop working.

### Additional context

Possibly related report here: https://stackoverflow.com/questions/58014876/sourcemap-missing-for-typescript-based-vue-file-due-to-lang-ts-attribute

I tried several devtools like `eval-source-map`, `cheap-module-eval-source-map`, `inline-source-map`, etc..  Some of these caused the debugger to successfully break but inside compiled `.js` files rather than the source `.vue` file.

**Comment by danielroe** [comment]
Are you sure you're using Nuxt 3? Would you provide a reproduction?

**Comment by aetherealtech** [comment]
@danielroe I must have followed an out of date setup guide that was for Nuxt 2.  I created a new Nuxt 3 project and debugging is working correctly with TypeScript.  Thank you!
