### ISSUE TITLE
State defined in a composable is not reactive when `ssr: false`

### ISSUE THREAD

**Issue by yooneskh** [nuxt/nuxt#27559]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.1
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, routeRules
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-caxd3f?file=app.vue

### Describe the bug

When in normal SSR mode, you can share a state using a composable like this
```ts
// composables/use-value.ts
export const useValue = () => useState('the-value', () => 0)
```
Then you can use it everywhere and it will be reactive. But if you change the SSR mode to false in nuxt.config, this shared state will not be reactive anymore. Please see the repro. When you click on the button, it will not rerender. But if you go to the nuxt.config.ts and comment the routeRules, the page will rerender after you click on the button.

This problem did not exist before 3.12.0

Thank you very much for this fantastic framework!

**Comment by danielroe** [comment]
This should be resolved in the [nightly release](https://nuxt.com/docs/guide/going-further/nightly-release-channel#nightly-release-channel), or in the next release.

Let me know if not and I'll reopen.
