### ISSUE TITLE
Progressive Web App.

### ISSUE THREAD

**Issue by ekomlenovic** [nuxt/nuxt#27557]
### Describe the feature

Hello,  
I saw on the nuxt roadmap that pwa is being integrated into the framework. Is this planned for early 2024 or late 2024?  
Is there an alternative while waiting for the implementation in the framework?  
It seems to me that https://pwa.nuxtjs.org/ is deprecated, is that a problem?
![image](https://github.com/nuxt/nuxt/assets/14351506/4cf1ba75-20b7-40c1-9746-1bc1a7388b18)

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by DamianGlowala** [comment]
See https://github.com/vite-pwa/nuxt

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/14148.
