### ISSUE TITLE
Type "image/x-icon" for favicon missing from link types

### ISSUE THREAD

**Issue by toniengelhardt** [nuxt/nuxt#27553]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.10.0
- Nuxt Version:     3.12.1
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  pnpm@9.1.3
- Builder:          -
- User Config:      ssr, runtimeConfig, site, modules, imports, experimental, sourcemap, devtools, app, vite, typescript, eslint, css, postcss, piniaPersistedstate, http, auth, colorMode, plausible, sitemap
- Runtime Modules:  @nuxt/devtools@1.3.3, @nuxt/eslint@0.3.13, @nuxt-alt/auth@3.1.7-beta.1, @nuxt-alt/http@1.7.10, @nuxtjs/color-mode@3.4.1, @nuxtjs/plausible@1.0.0, @nuxtjs/sitemap@5.2.0, @pinia/nuxt@0.5.1, @pinia-plugin-persistedstate/nuxt@1.2.0, @unocss/nuxt@0.61.0, @vueuse/nuxt@10.10.1, nuxt-icon@0.6.10
- Build Modules:    -
------------------------------

### Reproduction

Add this to `nuxt.config.ts`

```ts
app: {
    head: {
      link: [
        { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' },
      ],
    },
  }
```

### Describe the bug

The typically recommended type `image/x-icon` for favicons is missing from the available link types. 

This appeared in `v3.12`.

**Comment by nicholas5538** [comment]
I have the same issue as well, they have removed `rel: 'mask-icon` and `sizez:192x192` as well, it was previously working on `v3.11.x` before I updated to the latest `v3.12.1`.

**Comment by danielroe** [comment]
Apologies.

This should be resolved in the [nightly release](https://nuxt.com/docs/guide/going-further/nightly-release-channel#nightly-release-channel), or in the next release.

You can temporarily mask with `@ts-expect-error`

Let me know if not and I'll reopen.
