### ISSUE TITLE
Runtime config warning (typo error link)

### ISSUE THREAD

**Issue by LucaArgentieri** [nuxt/nuxt#27555]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.18.0
- Nuxt Version:     3.12.1
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  bun@1.0.30
- Builder:          -
- User Config:      devtools, runtimeConfig, modules, image, sanity, site, seo, build
- Runtime Modules:  @nuxt/eslint@0.3.13, @nuxtjs/tailwindcss@6.12.0, @nuxt/image@1.7.0, @nuxtjs/sanity@1.11.3, @nuxtjs/seo@2.0.0-rc.10
- Build Modules:    -
------------------------------

### Reproduction

I'm not providing a reproduction because there is only a small typo error:

```
[nuxt] Could not access `nuxt-schema-org`. The only available runtime config keys on the client side are `public` and `app`. See `https://nuxt.com/docs/guide/going-further/runtime-config` for more information.
```

I noticed that the link redirects to this:
https://nuxt.com/docs/guide/going-further/runtime-config%60

### Describe the bug

I noticed that the link redirects to this:
https://nuxt.com/docs/guide/going-further/runtime-config%60

**Comment by v-romanyuk** [comment]
The warning is probably caused because of this line
`const runtimeConfig = useRuntimeConfig()["nuxt-schema-org"] || useRuntimeConfig().public["nuxt-schema-org"];`

it is in the .nuxt/dev/index.mjs file

**Comment by manniL** [comment]
Somehow your terminal considers the last "`" as part of the website.

Maybe we can just add a redirect on nuxt.com to avoid that?
