### ISSUE TITLE
NuxtLink with an external url gives vue router waring

### ISSUE THREAD

**Issue by v-romanyuk** [nuxt/nuxt#27556]
### Environment

- Operating System: Darwin
- Node Version:     v20.14.0
- Nuxt Version:     3.12.1
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  yarn@1.22.22
- Builder:          -
- User Config:      devServer, runtimeConfig, app, css, experimental, modules, devtools
- Runtime Modules:  @nuxtjs/tailwindcss@6.12.0, @element-plus/nuxt@1.0.9, @nuxtjs/supabase@1.2.2, @nuxtjs/device@3.1.1, @vueuse/nuxt@10.10.1, @nuxtjs/seo@2.0.0-rc.10, unplugin-icons/nuxt
- Build Modules:    -

### Reproduction

<img width="581" alt="image" src="https://github.com/nuxt/nuxt/assets/46523281/5c50de35-bbec-42a0-9bee-946610762cd3">
<img width="413" alt="image" src="https://github.com/nuxt/nuxt/assets/46523281/39083721-d223-49b4-8102-6d5c27bce597">

### Describe the bug

[Vue Router warn]: No match found for location with path"

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/27312.
