### ISSUE TITLE
Nuxt 3 - Nitro vercel-edge - Redirection problem on page load - URL parameter appended to URL

### ISSUE THREAD

**Issue by CedsTrash** [nuxt/nuxt#27550]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.11.1
- Nuxt Version:     3.12.1
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      basicAuth, head, build, components, css, devtools, nitro, i18n, modules, runtimeConfig, routeRules
- Runtime Modules:  @nuxtjs/tailwindcss@6.12.0, @kgierke/nuxt-basic-auth@1.6.0, @nuxtjs/i18n@8.3.1
- Build Modules:    -
------------------------------

### Reproduction

I can't give you a minimal reproduction because it runs on Vercel Edge. I can just give you the link to the website:
https://staging.nxstar.ca/

You will need to access this shared link first in order to be able to see the site:
https://staging.nxstar.ca?_vercel_share=FQNHJcaSSRuyURCd3NA6AlMbNNIBHeqQ

### Describe the bug

Everything works fine locally and when I deploy to vercel with the "vercel" nitro preset.

But when I do the same with the "vercel-edge" preset the problems start:
You must use thie preview link from Vercel in order to be able to see the preview site:
https://staging.nxstar.ca?_vercel_share=FQNHJcaSSRuyURCd3NA6AlMbNNIBHeqQ

After this you'll be able to access the site directly here:
https://staging.nxstar.ca
* https://staging.nxstar.ca is redirected to https://staging.nxstar.ca/?url=/
* https://staging.nxstar.ca/first-page is redirected to https://staging.nxstar.ca/first-page?url=/first-page
* And so on

If I reach any of the pages directly, I can see the content and then open my navigation menu and navigate to an other page. It works fine and the URL is now correct (without the appended URL parameter). But the problem appears again as soon as I refresh the page.

All my routes are in ISR mode and I use @nuxtjs/i18n with this config:
```
export default defineNuxtConfig({
    i18n: {
        defaultLocale: 'en',
        detectBrowserLanguage: false,
        langDir: 'lang',
        lazy: true,
        locales: [
          {
            code: 'fr',
            iso: 'fr-CA',
            file: 'fr.ts'
          },
          {
            code: 'en',
            iso: 'en-CA',
            file: 'en.ts'
          }
        ],
        customRoutes: 'config',
        pages: {
            '[url]': {
                en: '/[url]',
                fr: '/[url]'
            },
            'post/[url]': {
                en: '/post/[url]',
                fr: '/article/[url]'
            }
        },
        strategy: 'prefix_except_default',
        vueI18n: "./i18n.config.ts"
    },
    routeRules: {
        '/**': { isr: 3600 },
    }
})
```

And finally, page content is fetched from a headless CMS like this:
pages/[url].vue
```
<script setup>
const config = useRuntimeConfig()
const route = useRoute()
const { locale } = useI18n()
const requestUrl = useRequestURL()

const url = ref({en: '/' + route.params.url, fr: '/fr/' + route.params.url})
const { data : page } = await useAsyncData(
    'page-${route.params.url}',
    () => $fetch(config.public.BASE_API_URL + '/collections/pages/entries?token=' + route.query.token + '&filter[site]=' + locale.value + '&filter[url]=' + url.value[locale.value])
)
</script>
```

I'm giving you all this context because I wonder if this "url" URL param is not coming from somewhere in this code...

Anyway, again, it all works perfectly until I activate the vercel-edge preset.

Thanks for your help.

### Additional context
I want to use Vercel Edge in conjunction with ISR because I need the On-Demand ISR feature.

_No response_

**Comment by danielroe** [comment]
Would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏

**Comment by CedsTrash** [comment]
Hi @danielroe I would love to but I’m not sure if I have the knowledge to do this to be honest.

**Comment by CedsTrash** [comment]
I found 2 other people with the same problem on the Nuxt Discord server.
* One 6 months ago with somebody pointing to an eventful problem with the vercel-edge nitro preset.
* Another one 2 months ago who just replied to me this:
`Bug on their side, I just removed preset: "vercel-edge"`

I guess I’ll raise an issue with Nitro then.

**Comment by danielroe** [comment]
let's track in https://github.com/unjs/nitro/issues/2515.
