### ISSUE TITLE
The way dynamic route path is generated breaks usage with path-to-regexp 

### ISSUE THREAD

**Issue by thomaspaillot** [nuxt/nuxt#27566]
### Describe the bug

https://github.com/nuxt/nuxt/blob/9e56b60c6b948596d29f153a0ef002ee04d5c067/packages/nuxt/src/pages/utils.ts#L268-L281

Nuxt is adding parenthesis at the end of a dynamic param of a route path like this `/:projects()/all` and when you use path-to-regexp to match a potential url the regex generated by path-to-regexp doesn't work because of the empty parenthesis.

```
import pathToRegexp from 'path-to-regexp';

'/my-project-name/all'.match(pathToRegexp('/:projects()/all')) // return false
'/my-project-name/all'.match(pathToRegexp('/:projects(\\S+)/all')) // return true
'/my-project-name/all'.match(pathToRegexp('/:projects/all')) // return true
```
### Reproduction

[Reproduction on Codesandbox](https://codesandbox.io/p/sandbox/lucid-lalande-vanilla?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxbytbre00063b6i06kzsxv1%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxbytbre00023b6iyiqri9u6%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxbytbre00033b6iqviiliyv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxbytbre00053b6inl3uwhpt%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxbytbre00023b6iyiqri9u6%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxbytbre00013b6i77rxgkpn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.html%2522%257D%255D%252C%2522id%2522%253A%2522clxbytbre00023b6iyiqri9u6%2522%252C%2522activeTabId%2522%253A%2522clxbytbre00013b6i77rxgkpn%2522%257D%252C%2522clxbytbre00053b6inl3uwhpt%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxbytbre00043b6ixp26ca5f%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxbytbre00053b6inl3uwhpt%2522%252C%2522activeTabId%2522%253A%2522clxbytbre00043b6ixp26ca5f%2522%257D%252C%2522clxbytbre00033b6iqviiliyv%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxbytbre00033b6iqviiliyv%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by danielroe** [comment]
Would you explain a bit more about why you are using `path-to-regexp` and why this is a problem for you? We use the parentheses to force close the token so you can have an expression like `[param]thing`.

This works fine with `vue-router`, so I imagine this something custom you're doing?

**Comment by thomaspaillot** [comment]
I'm using Bugsnag to monitor the performance of my website and they have a [library that integrate with vue-router](https://github.com/bugsnag/bugsnag-js-performance/blob/next/packages/vue-router/lib/vue-router-routing-provider.ts) to report performance for each route: this is where I found the usage of route path with path-to-regexp to match a url.

Maybe I should raise the issue there but I wasn't sure the parenthesis was needed or not, apparently it serves a purpose so I think I will open an issue on the bugsnag lib.

**Comment by thomaspaillot** [comment]
After some further investigation I think Bugsnag lib shouldn't use path-to-regexp to match the url as it is not used by vue-router internally. Vue Router expose a `createRouterMatcher` function that seems to do the same thing so they should probably use that instead. I'll close the issue, thanks for your quick answer.

**Comment by danielroe** [comment]
Not at all - and best of luck!
