### ISSUE TITLE
Massive amount of warnings with PrimeVue

### ISSUE THREAD

**Issue by DarkVen0m** [nuxt/nuxt#27560]
### Environment

- Nuxt Version:     3.12.1
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Builder:          -
- User Config:      devtools, pages, css, modules, runtimeConfig, eslint, primevue, i18n, pinia, tailwindcss
- Runtime Modules:  @nuxt/eslint@0.3.13, nuxt-primevue@4.0.0-beta.4, @nuxtjs/i18n@8.3.1, @pinia/nuxt@0.5.1, @nuxtjs/tailwindcss@6.12.0, nuxt-icon@0.6.10, @vueuse/nuxt@10.10.1, nuxt-zod-i18n@1.8.0, @nuxt/image@1.7.0

### Reproduction

Use any nuxt-primevue component in Nuxt 3.12+

### Describe the bug

After update to 3.12 nuxt creates massive amount of warnings when used with PrimeVue, as it's BaseComponent reads "pt" key from config.
![image](https://github.com/nuxt/nuxt/assets/16627883/99ac50c4-91f8-4101-b81b-1166553fd51a)
![image](https://github.com/nuxt/nuxt/assets/16627883/0e12dbae-acbf-4c52-9cdf-d3c8dc2ebcad)
https://github.com/primefaces/primevue/blob/master/components/lib/basecomponent/BaseComponent.vue

### Additional context

Although optional chaining is used in PrimeVue it still uses "get" method of proxy object, so I am kinda unsure if it should be fixed on your side with some kind of config for list of keys to ignore or on PrimeVue side with some other way, e. g. with "key in object" check.

**Comment by DarkVen0m** [comment]
https://stackblitz.com/edit/github-tyjczq?file=app.vue

**Comment by danielroe** [comment]
PrimeVue should probably do something like this:

```ts
const config = useRuntimeConfig()
const primveVueConfig = import.meta.client ? config.public.primevue : config.primevue
```

We can ensure we only log once, however: https://github.com/nuxt/nuxt/commit/9e56b60c6b948596d29f153a0ef002ee04d5c067.
