### ISSUE TITLE
nuxt 3.12 useState change detection fails when ssr is false

### ISSUE THREAD

**Issue by jonasem** [nuxt/nuxt#27561]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.12.1`
- Nuxt Version:     `3.12.1`
- CLI Version:      `3.12.0`
- Nitro Version:    `2.9.6`
- Package Manager:  `npm@10.5.0`
- Builder:          `-`
- User Config:      `runtimeConfig`, `devtools`, `$development`, `css`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

set `ssr: false` in nuxt.config

https://stackblitz.com/edit/github-mgtj4t-rnyqmk?file=app.vue

### Describe the bug

Only initial state is rendered

### Additional context

State changes fine when downgrading to nuxt 3.11

**Comment by danielroe** [comment]
This should be resolved in the [nightly release](https://nuxt.com/docs/guide/going-further/nightly-release-channel#nightly-release-channel) by https://github.com/nuxt/nuxt/pull/27542, or in the next release.

Until the next patch, you can work around by creating `~/plugins/payload-reactivity.client.ts` with the following content:`

```ts
export default defineNuxtPlugin(nuxtApp => {
  const payload = nuxtApp.payload

  for (const key in ['_errors', 'data']) {
    if (!isReactive(payload[key])) {
      payload[key] = shallowReactive(payload[key])
    }
  }

  if (!isReactive(payload.state)) {
    payload.state = reactive(payload.state)
  }
})
```
