### ISSUE TITLE
The route I customized in pages:extend cannot load the custom layout.

### ISSUE THREAD

**Issue by mc471066223** [nuxt/nuxt#27577]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.10.0
- Nuxt Version:     3.12.1
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  pnpm@8.12.1
- Builder:          -
- User Config:      devtools, hooks
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-bxdlen-fwzkjx?file=pages%2Findex.vue

### Describe the bug

I replaced the routing with pages:extend, and before version 3.12, the page could be displayed normally. But after I upgraded to version 3.12, the customized layout no longer displays on any of my pages.
``` 
// nuxt.config.ts
export default defineNuxtConfig({
  hooks: {
    "pages:extend": (pages) => {
        pages.splice(0, pages.length);
        pages.push(...routers);
    }
  }
})

### Additional context

_No response_

### Logs

_No response_

**Comment by tresko** [comment]
I have the same issue.

**Comment by danielroe** [comment]
For now you can work around with:

```ts
export default defineNuxtConfig({
  experimental: {
    scanPageMeta: false
  }
})
```

@tresko your issue is the same as https://github.com/nuxt/nuxt/issues/27490.

**Comment by mc471066223** [comment]
This solved my problem, thank you

**Comment by huaiguoguo** [comment]
> This solved my problem, thank you

how to solved?
