### ISSUE TITLE
useState lost reactivity on `ssr: false` 

### ISSUE THREAD

**Issue by kazudeath1** [nuxt/nuxt#27580]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.11.1
- Nuxt Version:     3.12.1
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      devtools, ssr
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-1nmobk

### Describe the bug

When `ssr: false` is specified in nuxt.config.ts, useState loses its reactivity, causing the display not to update and the watch not to respond.

In the example shown in reproduction, when there is no SSR specification, the display updates and the watch is triggered each time the respective update button is pressed. However, when `ssr: false` is specified, there is no update, and the update occurs only when update `reactive` value.

**Comment by manniL** [comment]
Resolved on nightly via https://github.com/nuxt/nuxt/issues/27536
