### ISSUE TITLE
Middleware ( in definePageMeta ) isn't called in Option API components in Nuxt v3.12.1

### ISSUE THREAD

**Issue by k-karen** [nuxt/nuxt#27585]
### Environment

Nuxt project info:                                                                                                                                                        22:36:28

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.1
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

v3.12.1 ( this bug version )
https://stackblitz.com/edit/github-vtuvrv?file=pages%2Fcomposition.vue

v3.11.2 ( middleware will work )
https://stackblitz.com/edit/github-vtuvrv-5by1ox?file=pages%2Foptions.vue

### Describe the bug

The middleware is not called in the Page component defined as follows.

```vue
<template>
  <h1>This is a test page(options)</h1>
</template>

<script>
export default {
  setup() {
    definePageMeta({
      // it won't work
      middleware: (from, to) => console.warn('middleware'),
    });
  },
};
</script>
```

On the other hand, the middleware is invoked when defined as follows

```vue
<template>
  <h1>
    This is a test page(composition)
  </h1>
</template>

<script setup>
// It will work
definePageMeta({
  middleware: (from, to) => console.warn('middleware')
})
</script>
```

**Comment by danielroe** [comment]
For now, just move `definePageMeta` out of that function call:

```ts
<template>
  <h1>This is a test page(options)</h1>
</template>

<script>
definePageMeta({
  // it won't work
  middleware: (from, to) => console.warn('middleware'),
})

export default {
  setup() {
  },
};
</script>
```
