### ISSUE TITLE
Type error in nuxt.config.ts for valid app.head.link[].type

### ISSUE THREAD

**Issue by markbrouch** [nuxt/nuxt#27598]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.16.1`
- Nuxt Version:     `3.12.1`
- CLI Version:      `3.12.0`
- Nitro Version:    `2.9.6`
- Package Manager:  `yarn@3.6.1`
- Builder:          `-`
- User Config:      `rootDir`, `devtools`, `typescript`, `sourcemap`, `alias`, `imports`, `runtimeConfig`, `modules`, `app`, `vite`, `css`, `doxErrors`, `i18n`, `image`, `build`, `server`, `analyze`, `loading`, `telemetry`, `vuex4`
- Runtime Modules:  `@nuxt/test-utils/module@3.13.1`,  `@nuxtjs/i18n@8.3.1`, `@vueuse/nuxt@10.11.0`, `@nuxt/eslint@0.3.13`, `@nuxt/image@1.7.0`, `@pinia/nuxt@0.5.1`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-dgpntw?file=nuxt.config.ts

### Describe the bug

`Type "image/x-icon" is not assignable to type...` type error exists in `nuxt.config.ts` in `app.head.link[].type`, despite this being a valid link type attribute.

### Additional context

The `zhead` package strictly constrains valid type attributes for links in an exhaustive list as described in this issue: https://github.com/harlan-zw/zhead/issues/23.

However, this list of types is not valid according to whatwg specifications:

> Official specs state that the type attribute must be a valid MIME type string: https://html.spec.whatwg.org/multipage/semantics.html#attr-link-type
> 
> A valid MIME type string is then defined as: "a string that matches the media-type token production." https://mimesniff.spec.whatwg.org/#valid-mime-type
> 
> The media-type token production is simply a case-insensitive pair of strings separated by a / with an optional semicolon delimited parameters as key/value pairs separated by =. For example: text/html;charset=utf-8. https://www.rfc-editor.org/rfc/rfc9110#name-media-type
> 
> Therefore, I think think the appropriate type should be simply string until such time as a regex type is supported in TypeScript.

`image/x-icon` and other valid type attributes are missing from the `zhead` type definition, causing an incorrect type error here.

**Comment by danielroe** [comment]
This should be resolved in the [nightly release](https://nuxt.com/docs/guide/going-further/nightly-release-channel#nightly-release-channel) by https://github.com/nuxt/nuxt/pull/27540, or in the next release (aiming for this weekend).

Until the next patch, you can work around by using `// @ts-expect-error`.

**Comment by markbrouch** [comment]
nice, thanks for the quick fix!
