### ISSUE TITLE
Nuxt 4 - defineNuxtModule using nuxt.dir.public resolve to absolute path

### ISSUE THREAD

**Issue by FlorianWerndl** [nuxt/nuxt#27591]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.11.0`
- Nuxt Version:     `3.12.1`
- CLI Version:      `3.12.0`
- Nitro Version:    `2.9.6`
- Package Manager:  `npm@10.2.4`
- Builder:          `-`
- User Config:      `srcDir`, `future`, `experimental`, `runtimeConfig`, `app`, `components`, `imports`, `devtools`, `typescript`, `modules`, `eslint`, `fontMetrics`, `i18n`, `tailwindcss`, `postcss`, `css`, `alias`, `vite`, `build`, `sourcemap`, `hooks`
- Runtime Modules:  `@nuxtjs/critters@0.7.1`, `@nuxtjs/fontaine@0.4.2`, `@nuxtjs/i18n@8.3.1`, `@nuxtjs/tailwindcss@6.12.0`, `@pinia/nuxt@0.5.1`, `@vueuse/nuxt@10.11.0`, `nuxt-lazy-hydrate@1.0.0`, `nuxt-viewport@2.1.5`, `@nuxt/eslint@0.3.13`, `@nuxtjs/html-validator@1.8.2`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-yaoajr

```
  future: {
    compatibilityVersion: 4,
  },
```  

### Describe the bug

According to the migration guide https://nuxt.com/docs/getting-started/upgrade#migrating-to-nuxt-4 

> modules and public are resolved relative to <rootDir> by default

Using `nuxt.options.dir.public` within `defineNuxtModule` resolves to an absolute path instead of a relative to the rootDir.

**Comment by danielroe** [comment]
This is probably a bug in the fontaine module. Modules should handle this being an absolute path.

We deliberately resolve the public directory absolutely in compatibility mode.

**Comment by FlorianWerndl** [comment]
But removing `compatibilityVersion: 4` will make `nuxt.options.dir.public` resolve to just `public`

**Comment by danielroe** [comment]
I mean that modules should handle either case.

Using `resolve(nuxt.options.srcDir, nuxt.options.dir.public)` will always give the correct directory.

**Comment by FlorianWerndl** [comment]
I see. I will create an issue or raise an PR. Thanks for having a look.

**Comment by danielroe** [comment]
~> https://github.com/nuxt-modules/fontaine/compare/fix/resolve-public-dir?expand=1
