### ISSUE TITLE
Cannot deploy to cloudflare pages

### ISSUE THREAD

**Issue by carlosvaldesweb** [nuxt/nuxt#27605]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.14.0
- Nuxt Version:     3.12.1
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  npm@10.7.0
- Builder:          -
- User Config:      css, extends, modules, site, sitemap, ogImage, linkChecker, seoExperiments, seo, cookieControl, sanctum, bugsnag, eslint, image, runtimeConfig, imports, ui, devtools, experimental, colorMode, tailwindcss
- Runtime Modules:  @nuxt/ui@2.17.0, @nuxt/image@1.7.0, @nuxtjs/eslint-module@4.1.0, @vueuse/motion/nuxt@2.2.3, nuxt-clarity-analytics@0.0.6, dayjs-nuxt@2.1.9, nuxt-bugsnag@7.3.0, @dargmuesli/nuxt-cookie-control@8.4.2, nuxt-zod-i18n@1.8.0, @nuxtjs/i18n@8.3.1, nuxt-auth-sanctum@0.3.14, @nuxtjs/seo@2.0.0-rc.10, nuxt-delay-hydration@1.3.3
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-yebevt?file=nuxt.config.ts

### Describe the bug

Hello, I am deploying an application to Cloudflare Pages, but I am receiving this message. I am using Nuxt Hub, by the way, congratulations on that! Also i've tried directly on cloudflare pages and is the same.

Iv'e noticed this message at end. 
```
18:22:58.106 | ✨ Success! Uploaded 3 files (472 already uploaded) (1.42 sec)
-- | --
18:22:58.106 |  
18:22:58.597 | ✨ Upload complete!
18:23:01.311 | Success: Assets published!
18:23:02.431 | Error: Failed to publish your Function. Got error: Uncaught TypeError: Cannot read properties of undefined (reading 'toString')   at chunks/runtime.mjs:1:193088   at chunks/runtime.mjs:1:216534

```
I've uploaded logs, because are bigs to paste here
[cloudflare_pages.log](https://github.com/user-attachments/files/15830203/cloudflare_pages.log)

**Comment by danielroe** [comment]
Would you be able to make your reproduction more minimal, please? 🙏

There are a lot of modules in that `nuxt.config` file.

**Comment by MickL** [comment]
I am deploying latest Nuxt and Nitro successful to Cloudflare Pages. Just for some reason Nitro doesnt automatically select preset cloudflare_pages anymore.

**Comment by carlosvaldesweb** [comment]
@danielroe For sure, i was testing modules one by one and is a problem with nuxt-bugsnag module. I've opened an issue in bugsnag repository.

**Comment by tuannguyenminh2086** [comment]
> [@danielroe](https://github.com/danielroe) For sure, i was testing modules one by one and is a problem with nuxt-bugsnag module. I've opened an issue in bugsnag repository.

any update? I've a issue with bugsnag also.

**Comment by MickL** [comment]
You guys need to provide reproduction repos. Probably your problem is an individual problem. Possibly also check if you are using libraries that only work in Node and not in a serverless edge function.

Nuxt deploys fine on Cloudflare Pages, I have multiple complex apps there with tons of modules in production.
