### ISSUE TITLE
`typedPages` does not work without `shamefully-hoist` unless `unplugin-vue-router` is installed

### ISSUE THREAD

**Issue by martinszeltins** [nuxt/nuxt#27616]
### Environment

````
------------------------------
- Operating System: Linux
- Node Version:     v18.14.2
- Nuxt Version:     -
- CLI Version:      3.10.1
- Nitro Version:    -
- Package Manager:  unknown
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------
````

### Reproduction

https://stackblitz.com/edit/github-wulwg4?file=pages%2Findex.vue

### Describe the bug

Nuxt 3.12 has broken typings for routes when typedPages is enabled.

1. In templates `$route` has the type `any` now
2. `<NuxtLink>` does not show autocomplete anymore for `to` prop.
3. `useRoute()` also does not show autocomplete anymore.

All these things were working before but now are broken. Please see the reproduction.

```vue
<template>
  <div>Index Page</div>

  <!-- $route is of type "any" -->
  <div>{{ $route.params }}</div>

  <!-- "to" autocomplete broken here -->
  <NuxtLink to="/user-1">User Page</NuxtLink>
</template>

<script setup lang="ts">
definePageMeta({ name: 'index' });

const route = useRoute(); // Autocomplete broken here
</script>
```

**Comment by toniengelhardt** [comment]
Nuxt 3.12 also breaks my build with these errors:

![Screenshot 2024-06-14 at 15 25 13](https://github.com/nuxt/nuxt/assets/2703233/303c3efa-ae77-4de6-9b78-182ce353c3c5)

If I disable `ogImage` in `nuxt.config.ts` it works.

**Comment by danielroe** [comment]
@toniengelhardt I think our issue is unrelated and possibly resolved with https://github.com/nuxt/nuxt/pull/27596. You might check the nightly release to confirm.

**Comment by toniengelhardt** [comment]
Thanks @danielroe, I think you're right 🙏🏽

**Comment by danielroe** [comment]
This seems to be an issue with hoisting. Adding `unplugin-vue-router@0.7.0` should resolve the issue.

**Comment by danielroe** [comment]
Note that typedPages are currently being reworked to merge the types into vue-router, which will resolve this issue.

**Comment by networdai** [comment]
> @toniengelhardt I think your issue is unrelated and possibly resolved with #27596. You might check the nightly release to confirm.

I have problem with router after upgrading nuxt@3.12.1 , vue@3.4.28 , vue-router@4.3.3. I have [Vue Router warn]: No match found for location with path ; For an external URL on NuxtLink, even when I enforce it by external tag.
`<NuxtLink :to="`https://etherscan.io/address/${pageData.collector}`" target="_blank" external>`
---
How can I install nightly version to check it solved or not?

**Comment by danielroe** [comment]
@networdai See https://nuxt.com/docs/guide/going-further/nightly-release-channel,.

**Comment by martinszeltins** [comment]
> This seems to be an issue with hoisting. Adding `unplugin-vue-router@0.7.0` as a project dependency should resolve the issue (or enabling `shamefully-hoist`).

@danielroe Thank you! Everything started to work when I added `shamefully-hoist=true` to my `.npmrc` file. I will have to read up on what exactly shamefully hoist does, I am not familiar with it.
