### ISSUE TITLE
`usdId` on component that root is Fragment will cause server-side warning: Extraneous non-props attributes

### ISSUE THREAD

**Issue by enpitsuLin** [nuxt/nuxt#27636]
### Environment

- Operating System: Darwin
- Node Version:     v20.10.0
- Nuxt Version:     3.12.1
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  pnpm@9.3.0
- Builder:          -
- User Config:      devtools, modules, experimental, future, css, colorMode, content, image
- Runtime Modules:  @nuxt/content@2.12.1, @vueuse/nuxt@10.11.0, @unocss/nuxt@0.61.0, @pinia/nuxt@0.5.1, @nuxtjs/color-mode@3.4.1, @nuxt/eslint@0.3.13, @nuxt/image@1.7.0
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-sq4pag?file=fragment-root.tsx

but dont know why SFC won't get this warning, it should be same 

### Describe the bug

https://github.com/nuxt/nuxt/blob/a3d8f005a648d5081ed8dcb052fdf2c4bcbbed10/packages/nuxt/src/app/composables/id.ts#L36

here we will set current instance attrs on the server, if the component that uses `useId()` renders Fragment or text as root, then I get a warning on the server side log, if I disable inheritAttrs option and get a new warning on the browser

> [nuxt] `useId` might not work correctly with components that have `inheritAttrs: false`.

I don't know if I should ignore these warning in my case

**Comment by danielroe** [comment]
This is a documented limitation of `useId`: https://nuxt.com/docs/api/composables/use-id

> useId must be used in a component with a single root element, as it uses this root element's attributes to pass the id from server to client.
