### ISSUE TITLE
Assigning a value on the `onServerPrefetch` hook will result in a hydration error

### ISSUE THREAD

**Issue by awdr74100** [nuxt/nuxt#27649]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.12.2
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  pnpm@9.1.0
- Builder:          -
- User Config:      vue, devtools, experimental, modules
- Runtime Modules:  @nuxtjs/tailwindcss@6.12.0  
- Build Modules:    -

### Reproduction

Consider the following:

server/api/numbers/index.get.ts
```ts
export default defineEventHandler(async event => {
  await new Promise((resolve) => setTimeout(resolve, 2000))

  return [2, 4]
})
```

pages/numbers.vue
```vue
<template>
  <pre>
    {{ localNumbers }}
  </pre>
</template>

<script setup lang="ts">
import { useQuery } from '@tanstack/vue-query';

const localNumbers = ref<number[]>([]);

const {
  data: numbers,
  suspense: suspenseGetNumbers,
  isPending: isPendingGetNumbers,
} = useQuery({
  queryKey: ['USE_QUERY_GET_NUMBERS'],
  queryFn: () => $fetch('/api/numbers'),
  refetchOnWindowFocus: false,
});

onServerPrefetch(async () => {
  await suspenseGetNumbers();

 if (numbers.value) localNumbers.value = numbers.value;
})
</script>
```
![螢幕擷取畫面 2024-06-16 155722](https://github.com/nuxt/nuxt/assets/47501692/d82c05e0-513b-4c0c-9f52-88abcc7a2f68)

I'm not sure if I'm misunderstanding something, why is the client side an empty array, and isn't the server side already assigned the default value?

### Describe the bug

rendered on server: [2, 4]

expected on client: [2, 4]

**Comment by danielroe** [comment]
The reason is that the value you assign isn't passed to the client - so it initialises as an empty array.

For this purpose, Nuxt provides `useState`: https://nuxt.com/docs/api/composables/use-state.

Try this:

```diff
- const localNumbers = ref<number[]>([]);
+ const localNumbers = useState<number[]>(() => []);

  // ...
  onServerPrefetch(async () => {
    await suspenseGetNumbers();
  
   if (numbers.value) localNumbers.value = numbers.value;
  })
```

**Comment by awdr74100** [comment]
@danielroe Thank you very much for your quick and effective response every time! It worked!

**Comment by danielroe** [comment]
Fantastic! 😊
