### ISSUE TITLE
Use useCookie to modify the value in one component, but the value in other components is not modified

### ISSUE THREAD

**Issue by thhary** [nuxt/nuxt#27660]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.9.0
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  npm@10.1.0
- Builder:          -

### Reproduction

When running on my device, the value of useCookie can be modified correctly when I run 'npm run dev', only when I run 'npm run generate', the value of useCookie will not be updated.
But in this website, even if I just run 'npm run dev', the value of useCookie will not be updated
https://stackblitz.com/edit/github-jaqn2d?file=components%2FChild.vue&file=app.vue

### Describe the bug

![image](https://github.com/nuxt/nuxt/assets/74284785/f0c277b6-7f31-4cf7-9eb6-9b3ee2d7dfe9)

**Comment by estige** [comment]
I also have this problem after updating to 3.12

**Comment by vptill** [comment]
Same issue for me after updating to 3.12

**Comment by yesworld** [comment]
Same issue for me after updating from 3.10 to 3.12.2. Have to downgrade to 3.10.. :(

**Comment by rolfkoizumi** [comment]
Having the same issue on MacOS with nuxt@3.12.2. Last working version seems to be 3.11.2 for me.
`useCookie()` is not reactive anymore and won't update its value if the cookie is changed. I encounter this even with `npm run dev`.

Reproductions on Stackblitz where I use `useCookie()` in a component and add this component twice. Editing the cookie value in one component should update the value in the other component. With nuxt@3.11.2 it is working, with nuxt@3.12.2 not anymore:
- [useCookie with nuxt@3.11.2](https://stackblitz.com/edit/nuxt-starter-wmwvx2?file=package.json,components%2FEditCookie.vue,pages%2Findex.vue)
- [useCookie with nuxt@3.12.2](https://stackblitz.com/edit/nuxt-starter-hhkqfe?file=package.json,components%2FEditCookie.vue,pages%2Findex.vue)

**Comment by manniL** [comment]
This is related to the now switched-on `cookieStore` feature. As a workaround, disabling it for now (`experimental.cookieStore` to `false`) should resolve the issue.

https://github.com/nuxt/nuxt/commit/f597ca59a

**Comment by TheDutchCoder** [comment]
I think this is a much deeper issue.

When I use `useCookie` in a composable it doesn't even remain reactive within the composable itself, unless I hoist the `useCookie` outside of the composable:

This doesn't work
```ts
export default function () {
  const bannerCookie = useCookie('banner')

  const showAppBanner = computed(() => {
    console.log(bannerCookie.value) // Never re-triggers
    return bannerCookie.value
  })

  function dismissAppBanner() {
    bannerCookie.value = false // This should re-trigger the computed value
  }

  return {
    showAppBanner,
    dismissAppBanner,
  }
}
```

But this does:
```ts
const bannerCookie = useCookie('banner')

export default function () {
  const showAppBanner = computed(() => {
    console.log(bannerCookie.value) // Never re-triggers
    return bannerCookie.value
  })

  function dismissAppBanner() {
    bannerCookie.value = false // This should re-trigger the computed value
  }

  return {
    showAppBanner,
    dismissAppBanner,
  }
}
```

**Comment by danielroe** [comment]
@TheDutchCoder Where are you calling that function?

**Comment by yesworld** [comment]
> But this does:
> 
> ```ts
> const bannerCookie = useCookie('banner')
> 
> export default function () {
>   const showAppBanner = computed(() => {
>     console.log(bannerCookie.value) // Never re-triggers
>     return bannerCookie.value
>   })
> 
>   function dismissAppBanner() {
>     bannerCookie.value = false // This should re-trigger the computed value
>   }
> 
>   return {
>     showAppBanner,
>     dismissAppBanner,
>   }
> }
> ```

@TheDutchCoder hmmm...  if i repeat your code. I'll get an error:

_[nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at `https://nuxt.com/docs/guide/concepts/auto-imports#vue-and-nuxt-composables`._

<img width="1661" alt="image" src="https://github.com/nuxt/nuxt/assets/6162264/42f7a09e-0eb8-40b6-b88d-b1424dacccd9">

**Comment by TheDutchCoder** [comment]
> This is related to the now switched-on `cookieStore` feature. As a workaround, disabling it for now (`experimental.cookieStore` to `false`) should resolve the issue.
> 
> Linking [f597ca59a](https://github.com/nuxt/nuxt/commit/f597ca59a) and #25198 - cc @enkot

Just to bring attention to this: for us this still doesn't work.
We can watch the cookie value and the watcher triggers, but the exported value (when consumed in another place) never updates:

```ts
export default function useCurrency() {
  const preferredCurrencyCookie = useCookie(COOKIES.currency, {
    domain: runtimeConfig.public.cookieDomain,
  })

  watch(preferredCurrencyCookie, (newVal) => {
    console.log('trigger') // this works fine
  })

  return {
    preferredCurrencyCookie,
  }
}

// In app.vue
<template>
  <div>{{ preferredCurrencyCookie }}</div> <!-- This never updates -->
</template>

<script setup lang="ts>
const { preferredCurrencyCookie }  = useCurrency()
</script>
```

**Comment by TheDutchCoder** [comment]
@danielroe @manniL Here's a simple reproduction, useCookie is completely broken at the moment: https://stackblitz.com/edit/github-ojwre2?file=app.vue

**Comment by danielroe** [comment]
@TheDutchCoder One issue with your SSR:

* you are using cookie without a default value in `app.vue`. This renders an empty string
* then you use it with a default value in a component - this renders `test` _and_ sets the value of the cookie
* on hydration, there's now a mismatch because `app.vue` now expects the empty string it renders to be `test` instead

Having said that, the reproduction seems to work fine to me locally, both in dev mode and when built:

https://github.com/user-attachments/assets/737a087e-c69b-401d-8586-b09a85634c1c

That indicates it might be the Chrome bug referenced in https://github.com/nuxt/nuxt/issues/28178.

**Comment by danielroe** [comment]
@TheDutchCoder I would recommend exactly that.

As for this feature, it started out experimental and was moved out of experimental status when we set the default to true. We typically leave the option name under experimental to allow people to disable it if regressions appear.

**Comment by yesworld** [comment]
@TheDutchCoder, If you add another function to activate a banner, will it work for you?

example: https://stackblitz.com/edit/github-1mayxm-rnjiki?file=composables%2FuseBanner.ts,app.vue

```js

export default function useBanner() {
  const bannerCookie = useCookie('banner', {
    path: '/',
    expires: new Date('2060-01-01'),
    default: () => 'show',
  });

  const showBanner = computed(() => bannerCookie.value === 'show');

  function dismissBanner() {
    bannerCookie.value = 'hide';
  }

  const activeBanner = () => {
    bannerCookie.value = 'show'
  }

  return {
    showBanner,
    dismissBanner,
    activeBanner,
  };
}
```

app.vue
```js
<template>
  <div>
    <CompA />
    <CompB />

    Show Banner: {{ showBanner }} <br />
    <button @click="avtiveBanner">Active</button>
  </div>
</template>

<script setup>
const { showBanner, avtiveBanner } = useBanner();
</script>

```

**Comment by yesworld** [comment]
@danielroe please, look at this example.
https://stackblitz.com/edit/github-1mayxm-rnjiki?file=composables%2FuseBanner.ts,app.vue

Why do cookies not change after clicking on the Active button?
```js
<button @click="avtiveBanner">Active</button>
```

**Comment by danielroe** [comment]
@yesworld Try updating to v3.12.4 which is the version with the fix.

**Comment by davidbayra** [comment]
@danielroe I upgraded to 3.12.4 and I also have cookie update not working when I click on ActiveButton:(
https://stackblitz.com/edit/github-1mayxm-jyhhra?file=composables%2FuseBanner.ts,package.json

**Comment by yesworld** [comment]
@danielroe Thanks for the answer!

My example was't good, but I tried updating to version **v3.12.4**. Both in my example and in my local project changing cookies does not work.

**Comment by danielroe** [comment]
Try locally (not in Stackblitz). And do open a new issue with a reproduction if you can reproduce 🙏

**Comment by yesworld** [comment]
Sorry, I made a mistake in the local version. Everything works well!

**Comment by danielroe** [comment]
Great! 🙌
