### ISSUE TITLE
Directive Custom | Hydration error when adding a class

### ISSUE THREAD

**Issue by SimonGSpin** [nuxt/nuxt#27664]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      buildModules, plugins
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Nuxt : https://stackblitz.com/edit/github-9ukebr-n5eon6?file=package.json

Vue : https://stackblitz.com/edit/github-iswjxq-hto8un?file=src%2Fmain.ts,src%2FApp.vue

### Describe the bug

Hi,

I tried to create a directive who add a class to an element but I have this warning : 
```
Hydration class mismatch on <div class=​"test b-red" data-v-inspector=​"pages/​index.vue:​2:​3">​Hello World!​</div>​ 
  - rendered on server: class="test b-red"
  - expected on client: class="test"
  Note: this mismatch is check-only. The DOM will not be rectified in production due to performance overhead.
```

I have done the reproduction on Vue and Nuxt, because I do not have this error on Vue (only in Nuxt).

To see this error, you need to open the console, do not only look on StackBlitz terminal.

### Logs

```shell-script
[Vue warn]: Hydration class mismatch on 
 <div class="test b-red" data-v-inspector="pages/index.vue:2:3">Hello World!</div>
  - rendered on server: class="test b-red"
  - expected on client: class="test"
  Note: this mismatch is check-only. The DOM will not be rectified in production due to performance overhead.
  You should fix the source of the mismatch. 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <Anonymous key="/" vnode= 
{__v_isVNode: true, __v_skip: true, type: {…}, props: {…}, key: null, …}
 route= 
{fullPath: '/', hash: '', query: {…}, name: 'index', path: '/', …}
  ... > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <ElMain> 
  at <ElContainer> 
  at <ElContainer> 
  at <Default ref=Ref< undefined > > 
  at <LayoutLoader key="default" layoutProps= 
{ref: RefImpl}
 name="default" > 
  at <NuxtLayoutProvider layoutProps= 
{ref: RefImpl}
 key="default" name="default"  ... > 
  at <NuxtLayout> 
  at <App key=4 > 
  at <NuxtRoot>
```

**Comment by danielroe** [comment]
You would have the same error in Vue SSR: see https://stackblitz.com/edit/github-npi9cl?file=src/main.ts,src/App.vue.

This is because you are not adding the class on the client side until _mounted_ - but hydration (and hydration errors) happen before that point.

![CleanShot 2024-06-17 at 15 15 35@2x](https://github.com/nuxt/nuxt/assets/28706372/b46dda59-7fb1-4358-930e-5aa3db45e614)

**Comment by SimonGSpin** [comment]
Even when I use `created hook` or any other directive hook the error is still here.

I can't find any documentation on it so I guess we can't add className in directive ?
