### ISSUE TITLE
Having issues accessing the images stored under src/public directory

### ISSUE THREAD

**Issue by nicholas5538** [nuxt/nuxt#27661]
**Summary (generated)**:

An issue report is being submitted about a problem with accessing assets in the public folder after updating the Nuxt version from 3.11.x to 3.12.x. The issue occurs when trying to access assets in the public folder located under the src folder. Despite reconfiguring the nuxt-config.ts file, the problem persists. The issue has not been tested in production mode, but the user can no longer see images in the assets tab of the Nuxt devtools.

<hr>

### Environment

Development

### Reproduction

https://github.com/nicholas5538/portfolio-vue/pull/51

### Describe the bug

I can no longer access my assets in the public folder when I updated the nuxt version from `3.11.x` to `3.12.x`. My public folder is under the src folder, I have tried to reconfigure `nuxt-config.ts` but to no avail.

I have not tested this in production mode, but I can no longer see my images under the assets tab on the nuxt devtools.

### Logs

![image](https://github.com/nuxt/nuxt/assets/99808500/39388c52-2906-42cc-8398-3a90442d9c63)

**Comment by danielroe** [comment]
One of the steps when migrating to `compatibilityVersion: 4` is to move your `public/` and `server/` folders out of the `src/` directory and into the root. This is a little different from the normal migration steps as you already have a `srcDir` which is not set to `app/`.
