### ISSUE TITLE
Unable to update cookie with `useCookie` with `maxAge`/`expires` after cookies expired

### ISSUE THREAD

**Issue by trandaison** [nuxt/nuxt#27666]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.11.2`
- CLI Version:      `3.9.1`
- Nitro Version:    `2.9.6`
- Package Manager:  `pnpm@8.15.5`
- Builder:          `-`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-nvdbhq?file=app.vue

### Describe the bug

When using `useCookie` with `maxAge`/`expires` and trying to set a new cookie with the same name after the cookie has expired, the new cookie is not set.

Either calling a new `useCookie()` statement or assigning the `cookieRef.value` directly does not work.

![useCookie](https://github.com/nuxt/nuxt/assets/13447235/04ad3555-f500-4e8e-ae3b-6e1b38343112)

**Comment by danielroe** [comment]
This should be resolved in v3.12.2 with https://github.com/nuxt/nuxt/pull/27632.
