### ISSUE TITLE
Not found provide composable on hot reload

### ISSUE THREAD

**Issue by leofredy** [nuxt/nuxt#27668]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.0.0
- Nuxt Version:     3.12.1
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  npm@9.6.4
- Builder:          -
- User Config:      app, runtimeConfig, css, googleFonts, plugins, modules, devtools, imports, srcDir, dir, alias, pinia
- Runtime Modules:  nuxt-swiper@1.2.2, @nuxtjs/google-fonts@3.2.0, @pinia/nuxt@0.5.1, @nuxtjs/eslint-module@4.1.0
- Build Modules:    -

### Reproduction

**minimal reproduction:** https://stackblitz.com/edit/github-y3jkd3?file=composables%2FuseProvideContext.ts,pages%2Findex.vue,components%2FComponentA.vue

**video:** https://www.loom.com/share/99e29467a2204d0e8e74de1805351cbd

### Describe the bug

Not found provide context when hot reload, why?

**Comment by danielroe** [comment]
This isn't a Nuxt-specific issue. But the problem is that your `Symbol` is unique, which means on hot reload (because only one component is reloaded) the symbol differs from parent + child. Instead you can use a global registry:

```diff
  import { provide, inject, type InjectionKey } from 'vue';
  
  export function useProvideContext<ContextValue>(contextName: string) {
-   const injectionKey: InjectionKey<ContextValue | null> = Symbol(contextName);
+   const injectionKey: InjectionKey<ContextValue | null> = Symbol.for(contextName);
    // ...
  }
```
