### ISSUE TITLE
Running `generate` crashes dev server

### ISSUE THREAD

**Issue by ralacerda** [nuxt/nuxt#27674]
### Environment

From StackBlitz reproduction:
------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-53r4wj?file=package.json

Start a new project and run `npm install && npm run dev`. Start a new terminal and run `npm run generate`, reload the browser.

### Describe the bug

I get an 500 error:

`Package import specifier "#internal/nuxt/paths" is not defined in package /home/projects/nuxt-starter-53r4wj/package.json imported from /home/projects/nuxt-starter-53r4wj/.nuxt/dist/server/server.mjs
`

![image](https://github.com/nuxt/nuxt/assets/19380403/d40415be-acd8-4511-9bec-56b68b6eb999)

### Additional context

You can see output on the dev server while the generate is running.

On my system, I get `[500] Package import specifier "#internal/nitro" is not defined`

Since the behaviour is totally unexpected and the error message might change based on the project, I believe this can be the root cause of other unsolved issues like https://github.com/nuxt/nuxt/issues/26731

**Comment by lustremedia** [comment]
Tried to reproduce on StackBlitz however I do not get any error ...

**Comment by manniL** [comment]
Yes, that's the current behavior (you can't run dev & build at the same time). This is meant to be changed in the future though

Let's track in https://github.com/nuxt/nuxt/issues/14607
