### ISSUE TITLE
Change in Script Order between Nuxt 3.11.2 and Nuxt 3.12.2

### ISSUE THREAD

**Issue by CodeCube0** [nuxt/nuxt#27686]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.14.0
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  npm@10.8.1
- Builder:          -
- User Config:      runtimeConfig, typescript, ssr, devtools, app, modules, primevue, css, validations, devServer, routeRules
- Runtime Modules:  nuxt-primevue@3.0.0, @nuxt/eslint@0.3.13, @nuxt/test-utils/module@3.13.1
- Build Modules:    -
------------------------------

### Reproduction

To reproduce this problem, you can place the elements in the nuxt.config.ts file as shown in the image below:

```
app: {
  head: {
    link: [
      {
        id: 'theme-css',
        rel: 'stylesheet',
        type: 'text/css',
        href: '/themes/mdc-light-indigo/theme.css',
      },
      {
        id: 'theme-css-override',
        rel: 'stylesheet',
        type: 'text/css',
        href: '/themes/mdc-light-indigo/override.css',
      },
    ],
    script: [
      {
        innerHTML: `
          window._historyCache = {
            replaceState: window.history.replaceState,
            pushState: window.history.pushState
          };`,
      },
      {
        src: 'https://appsforoffice.microsoft.com/lib/1/hosted/office.js',
        defer: false,
        type: 'text/javascript',
      },
      {
        innerHTML: `
          window.history.replaceState = window._historyCache.replaceState;
          window.history.pushState = window._historyCache.pushState;`,
      },
    ],
  },
},
```

![image](https://github.com/nuxt/nuxt/assets/59050532/d5ec09bb-9c8b-4493-8264-707b9ac88ec4)

### Describe the bug

In Nuxt 3.11.2, the order of scripts is preserved as expected (innerHTML - src - innerHTML), ensuring that the inline script content executes in the correct sequence.

However, in Nuxt 3.12.2, there has been a change in the script execution order: scripts with the "src" attribute are moved to the top (src - innerHTML - innerHTML). This can affect the behavior of applications that rely on a specific script execution order, potentially causing compatibility and functionality issues.

Nuxt 3.11.2
![image](https://github.com/nuxt/nuxt/assets/59050532/9f0d722d-70b7-435b-843d-f39467d2bc33)

Nuxt 3.12.2
![image](https://github.com/nuxt/nuxt/assets/59050532/6cf20703-9bd8-4fc7-bafb-25434eb04189)

Is there a way to restore the original script order?

**Comment by danielroe** [comment]
Have you configured ssr or renderJsonPayloads?

**Comment by CodeCube0** [comment]
> Have you configured ssr or renderJsonPayloads?

I set "ssr" false and "renderJsonPayloads" I didn't use

**Comment by danielroe** [comment]
We needed to change the script order because with `ssr` false, the payload is otherwise injected too late. See https://github.com/nuxt/nuxt/pull/27506.

This should, however, only apply if you are using the legacy option `renderJsonPayloads: false`.

**Comment by CodeCube0** [comment]
> We needed to change the script order because with `ssr` false, the payload is otherwise injected too late. See #27506.
> 
> This should, however, only apply if you are using the legacy option `renderJsonPayloads: false`.

I tried now to set it to both "true" and "false" but nothing changed

**Comment by danielroe** [comment]
would you provide a reproduction? 🙏

**Comment by CodeCube0** [comment]
> would you provide a reproduction? 🙏

https://github.com/CodeCube0/reproduction-bug-nuxt.git

You can reproduce the problem by changing the Nuxt version number from "3.12.2" to "3.11.2"

**Comment by CodeCube0** [comment]
have you checked the problem? @danielroe

**Comment by danielroe** [comment]
Ahh, this is not attributable to the PR I linked above. It's instead because we now enable a set of performance optimisations based on https://github.com/rviscomi/capo.js.

You can disable it like this:

```ts
export default defineNuxtConfig({
  experimental: {
    headNext: false
  },
})
```

However, I would suggest instead using `tagPriority` in your `app.head` to specify the order you want to apply. (With 1, 2, 3 it works exactly as before for you.)
