### ISSUE TITLE
The CJS build of Vite's Node API is deprecated.

### ISSUE THREAD

**Issue by bbhxwl** [nuxt/nuxt#27680]
**Summary (generated)**:

The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.

<hr>

I know this is a warning and it doesn't affect usage, but is there a way to resolve this warning?

 
WARN  The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
![image](https://github.com/nuxt/nuxt/assets/26525599/e2d62a89-f589-4aa1-83d2-c8846a8ddaac)

**Comment by GalacticHypernova** [comment]
Considering this is cjs, did you make sure to use esm?
There's a section on it in the docs:
https://nuxt.com/docs/guide/concepts/esm

**Comment by manniL** [comment]
Duplicate of https://github.com/nuxt/nuxt/issues/27110
