### ISSUE TITLE
"Failed to resolve import source - TypeScript modules"

### ISSUE THREAD

**Issue by mkalinski93** [nuxt/nuxt#27703]
**Summary (generated)**:

Here is a brief summary in English:

Operating system: Darwin. Node version: 21.7.1. Nuxt version: 3.11.2. 

A TypeScript file is created in the "types" folder, declaring a module "components/logo" and an interface "LogoProps". 

Trying to import this type into a component results in the bug that only exported interfaces work, not declared modules. 

There is no additional context or logs provided.

<hr>

### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v21.7.1
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.5.0
- Builder:          -
- User Config:      modules, css, tailwindcss, primevue
- Runtime Modules:  @primevue/nuxt-module@4.0.0-rc.2, @nuxtjs/tailwindcss@6.12.0, @vueuse/nuxt@10.11.0
- Build Modules:    -
------------------------------

### Reproduction

Create a typescript file in the "types" folder

"components.ts"
```ts
declare module "components/logo" {
    export interface LogoProps {
        width?:string;
    }
}
```

try to import the type into a component
"component.vue"
```vue
<script setup lang="ts">
import type {LogoProps} from 'components/logo'

withDefaults(defineProps<LogoProps>(), {
  width: '32px'
});
</script>
```

### Describe the bug

It doesn´t seem to be possible, to add declared modules in a component. Only exported interfaces seems to be working fine.

**Comment by danielroe** [comment]
you just do `export type`, no need for the `declare module` bit.

Here's an example. Bear in mind you need to install `typescript` and `vue-tsc` as dependencies:

https://stackblitz.com/edit/github-ewqayl?file=app.vue,types/components.ts
