### ISSUE TITLE
Types auto-import

### ISSUE THREAD

**Issue by Ragura** [nuxt/nuxt#27719]
### Describe the feature

I've been enjoying the DX of auto-imported components and composables ever since the release of those packages for Vue and I'm happy it's auto-configured for Nuxt.

As for the next step, would it be possible to **selectively** auto-import types? There's no point in auto-importing everything because large apps would just have too many types clogging the IDE and there would be naming collisions all over the place. But perhaps by adding a `.global` or `.auto` to a type file's name, exported types in those files could be safely auto-imported. It would certainly be a handy tool for those ubiquitous types that tend to sneak into many of your components.

I'm sure there's pros and cons to this, so let's discuss 💬

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by maxdzin** [comment]
Maybe it would be good to just auto import all the types, rather than selectively (not sure if there are could be some cases when it would be really handful). But optionally.

Having all the TS things to be imported on demand is actually a good practice (maybe to prevent some collisions). But, yes, it is also interesting how it will look like with auto-imports.

When I think about this feature, it reminds me of the previous versions of Nuxt 3 where composables, utils, etc. weren't automatically imported, but now they are, and so it made using Nuxt much easier.

Maybe we will have the same effect with the types to be auto imported? I assume that it wasn't done yet because of some pitfalls or something, probably. @danielroe can you share your thoughts about it?

**Comment by Ragura** [comment]
I think it hasn't been done because there is no existing unplugin package that does this, unlike for auto-imports of composables and components?

I agree you could make an argument for having to explicitly import types as a best practice, but that argument would then be the same for any imports.

The reason I suggested not importing all types is that there will be many more types than there are functions/components in a project. Imagine the IDE experience with 3000 types being loaded for autocomplete...
But the biggest issue with importing all types indiscriminately is naming collisions. Let's say you have an exported interface `FormBody` in every form component/composable/api route. How would the auto-import even know which one you're referring to?

I think the greatest strength of this feature would be to take away the workload of importing regularly used common types and improve readability of the top of a file as a result (not having your first actual line of code further down the file).

**Comment by maxdzin** [comment]
> I think it hasn't been done because there is no existing unplugin package that does this

Ah, indeed

> But the biggest issue with importing all types indiscriminately is naming collisions. Let's say you have an exported interface FormBody in every form component/composable/api route. How would the auto-import even know which one you're referring to?

In that case, it will surely require maintaining naming conventions effectively, like ensuring you have unique names, etc.

It seems I need to express more about what I imagined about auto-importing: it is to import everything automatically from the `types` directory and its subdirectories only.
As for the other types exports, like from components or other places, those things will require to be imported manually.
But I just thinking about how it could be.

**Comment by Ragura** [comment]
Oh yeah, absolutely should only look at types inside the types folder. But in my project for example, I have differently named files in that folder that still have similarly named types. They would cause collision problems if they were all auto-imported. You're right that full auto-import could come with restraints put on developers to make sure they have unique names, though I'm not sure how practical that would be for existing codebases.

**Comment by danielroe** [comment]
This appears to be working by default in a Nuxt project.
