### ISSUE TITLE
useHead body style attributes cleared when changing pages 

### ISSUE THREAD

**Issue by DevChanQ** [nuxt/nuxt#27712]
### Environment

```
"@unhead/vue": "^1.9.13",
"nuxt": "^3.12.1"
```

### Reproduction

[Stackblitz](https://stackblitz.com/edit/nuxt-starter-lkygzg?file=pages%2Findex.vue)

### Describe the bug

Created an issue in the unhead repo https://github.com/unjs/unhead/issues/357 but not getting any response there. Felt it's appropriate to mention it here since it affects nuxt users quite a bit.

I am currently using `useHead` to update body style attributes for different pages. It was not working for some reason, the style would be cleared no matter what.

After some investigation, I found that the styles are cleared because the tracked scope includes the value of the attribute, making the previous pending side effect unable to be removed.
https://github.com/unjs/unhead/blob/c0ca0c1cc196928b40952d525f7f5e0d9edd54ce/packages/dom/src/renderDOMHead.ts#L111-L120

**Comment by manniL** [comment]
I think tracking it in unhead seems to be the best way (cc @harlan-zw)

**Comment by harlan-zw** [comment]
@DevChanQ Please be mindful that I like most open-source maintainers have limited bandwidth in responding to issues. Creating another issue won't expedite the process.

Closing as the existing issue is tracking.

**Comment by DevChanQ** [comment]
My apologies 🤝
