### ISSUE TITLE
undefined title in google SERP?

### ISSUE THREAD

**Issue by carlosvaldesweb** [nuxt/nuxt#27725]
### Environment

Production in Hosted in Vercel

- Operating System: Darwin
- Node Version:     v20.14.0
- Nuxt Version:     3.12.1
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  npm@10.7.0
- Builder:          -
- User Config:      css, extends, modules, site, sitemap, ogImage, linkChecker, seoExperiments, seo, cookieControl, sanctum, bugsnag, eslint, image, runtimeConfig, imports, ui, devtools, experimental, colorMode, tailwindcss, routeRules
- Runtime Modules:  @nuxt/ui@2.17.0, @nuxt/image@1.7.0, @nuxtjs/eslint-module@4.1.0, @vueuse/motion/nuxt@2.2.3, nuxt-clarity-analytics@0.0.6, dayjs-nuxt@2.1.9, nuxt-bugsnag@7.3.0, @dargmuesli/nuxt-cookie-control@8.4.2, nuxt-zod-i18n@1.8.0, @nuxtjs/i18n@8.3.1, nuxt-auth-sanctum@0.4.0, @nuxtjs/seo@2.0.0-rc.10, nuxt-delay-hydration@1.3.3
- Build Modules:    -

### Reproduction
You can check app.vue and index.vue to check how to set titles.
https://stackblitz.com/edit/nuxt-starter-n1zpvy?file=app.vue

### Describe the bug

Hello, I am having some SEO issues with my website. Previously, we used Laravel to develop the front end of our site, but we decided to migrate to Nuxt. The problem is that sometimes our website appears with the title "undefined" in Google's SERP. I haven't noticed which specific pages it happens with, but it has already happened with several search terms.

For example, if I search for the term "resumir textos", the page appears as "undefined", but it can stay like that for a few hours or days and then return to normal.

<img width="1440" alt="Captura de pantalla 2024-06-19 a la(s) 8 04 17 p m" src="https://github.com/nuxt/nuxt/assets/32969705/a83d7b75-95ce-45ae-bd94-c35c33eb53ca">

I have noticed that other people have this specific problem with Nuxt because if I search on Google "undefined in google serp" without adding any programming language or any reference, another Nuxt topic appears.

https://www.reddit.com/r/Nuxt/comments/14cjpq6/undefined_in_title_on_google_serp/

<img width="1440" alt="Captura de pantalla 2024-06-19 a la(s) 8 28 03 p m" src="https://github.com/nuxt/nuxt/assets/32969705/287c6b8b-cb24-4c96-b963-eb97ad243b28">

This is concerning because it is negatively affecting the SEO of our website.

P.S. It would be great if you could add our website to the Nuxt showcase: https://parafrasist.com/

**Comment by danielroe** [comment]
Can you update the reproduction to reproduce this without `@nuxtjs/i18n`?

If not, would you open an issue in https://github.com/nuxt-modules/i18n instead? 🙏

**Comment by carlosvaldesweb** [comment]
For sure, here is reproduction without i18n 
https://stackblitz.com/edit/nuxt-starter-pfk6oh?file=app.vue

**Comment by danielroe** [comment]
Sorry, but I've checked your reproduction and it seems to have a defined title. What do I need to do to reproduce?

**Comment by carlosvaldesweb** [comment]
@danielroe Yes, i't have a title, but i don't know why in google SERP title is undefined.

**Comment by danielroe** [comment]
ccing @harlan-zw in case he's encountered this before, but it's very difficult to investigate in this situation

**Comment by carlosvaldesweb** [comment]
@danielroe I'm thinking that the issue is related that this line
```ts
const title = computed(() =>
  route.meta.title
    ? route.meta.title
    : ''
);
```

When i set empty title, the tag is empty
```html
<title></title>
```
According to Mozilla, this tag must always have text.

I've changed my code to the following:
```ts
const title = computed(() =>
  route.meta.title
    ? route.meta.title
    : undefined
);
```

Those pages always have a title, but I don't know why Google does that. I'm not sure if there might be an issue with the delay hydration module or if sometimes nuxt sends the empty tag during SSR. What do you think? I've changed my code and push to production, i'll be monitoring these days and updating in this issue.

**Comment by harlan-zw** [comment]
The issue was probably related to the hydration of the title, given that you have the nuxt-delay-hydration module.

Either hydrating to undefined before flashing back "my title" -> undefined -> "my title" or undefined -> "my title".

The current site looks correct so this will sort itself out once google re-indexes it.

Will close for now but feel free to ping me if it doesn't sort itself out.
