### ISSUE TITLE
The QueryString is double URL encoded when running `navigateTo` on the server side.

### ISSUE THREAD

**Issue by konti-kun** [nuxt/nuxt#27728]
### Environment

- Operating System: Darwin
- Node Version:     v20.10.0
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  yarn@1.22.21
- Builder:          -
- User Config:      devtools, css, modules, runtimeConfig, colorMode, ui, googleFonts, gtm, bugsnag, vite, nitro, hooks
- Runtime Modules:  @vueuse/nuxt@10.11.0, @nuxtjs/color-mode@3.4.1, @nuxt/ui@2.17.0, @nuxtjs/tailwindcss@6.12.0, @nuxtjs/google-fonts@3.2.0, @nuxtjs/device@3.1.1, @zadigetvoltaire/nuxt-gtm@0.0.13, nuxt-bugsnag@7.3.0

### Reproduction

The code below can be reproduced by running it on the server side.

```
<script setup lang="ts">
const params = {
  client_id: 'client_id',
  response_type: "code",
  redirect_uri: "http://localhost:3000/sso/callback",
  scope: "openid",
  nonce: "12345",
  state: "12345",
}
navigateTo({ path: 'https://example.com/oauth/authorize', query: params }, { external: true })
</script>
```

When urlencoded, "/" should be "%2F", but it becomes "%2f25".

### Describe the bug

https://github.com/nuxt/nuxt/blob/77685e43e4b4602151f0d2e7fbfa8bc372308907/packages/nuxt/src/app/composables/router.ts#L123

https://github.com/nuxt/nuxt/blob/77685e43e4b4602151f0d2e7fbfa8bc372308907/packages/nuxt/src/app/composables/router.ts#L172

It seems that this issue is occurring because two parts of the code are being executed separately.

**Comment by danielroe** [comment]
Great investigation - thank you.

I'm closing to track in https://github.com/nuxt/nuxt/issues/27554.
