### ISSUE TITLE
When I build project, packed folder will loss some file in server/node_modules

### ISSUE THREAD

**Issue by HaishengLiang** [nuxt/nuxt#27726]
### Environment

Operating System: Darwin
Node Version: v20.14.0
Nuxt Version: 3.11.2
CLI Version: 3.11.1
Nitro Version: 2.9.6
Package Manager: pnpm 8.6.7
Builder: -
User Config: devtools, vite, $production, $development
Runtime Modules: -
Build Modules: -

### Reproduction

when I run the project which I builded . It call me loss some file 
![20240620111239](https://github.com/nuxt/nuxt/assets/1995687/a1c26104-655a-4832-a8c4-afcb9997dd7b)

### Describe the bug

I have check the packed files in .output/server/node_modules. I find the file has no copy to target folder
like this:

![20240620110953](https://github.com/nuxt/nuxt/assets/1995687/1bc92767-0b5f-4cef-9c3b-fc84890b8040)
![20240620111021](https://github.com/nuxt/nuxt/assets/1995687/b95e41d3-e23d-48ac-83b7-23f9f0591db4)

**Comment by danielroe** [comment]
This is a Nitro issue - would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏

You can also manually add the files you need with `nitro.externals.traceInclude`.
