### ISSUE TITLE
Hydration mismatch for nested server component

### ISSUE THREAD

**Issue by kingyue737** [nuxt/nuxt#27731]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-qjtrhd-mtyvxv

### Describe the bug

When placing a server component in another server component, vue throw the following warning:

```
runtime-core.esm-bundler.js:48  [Vue warn]: Hydration node mismatch:
- rendered on server: <!--]-->  
- expected on client: Symbol(v-fgt) 
  at <NuxtIsland name="MyWrapper" lazy=false props= Proxy(Object) {}  ... > 
  at <MyWrapper> 
  at <App key=4 > 
  at <NuxtRoot>
```

**Comment by danielroe** [comment]
Server components (and islands) must have a single root element. (HTML comments are considered elements as well.)

See https://nuxt.com/docs/guide/directory-structure/components#standalone-server-components

![CleanShot 2024-06-20 at 11 48 04@2x](https://github.com/nuxt/nuxt/assets/28706372/d084bf66-18ec-4574-aaeb-be76df570159)

**Comment by kingyue737** [comment]
(Sorry I accidentally add an extra root element in the reproduction. I've now removed it)

Ah I see. That means the following is not allowed @danielroe ?
```vue
<!-- MyWrapper.server.vue -->
<template>
  <AnotherServerComponent />
</template>
```

An extra wrapper is required?
```vue
<!-- MyWrapper.server.vue -->
<template>
  <div>
    <AnotherServerComponent />
  </div>
</template>
```

> Server components (and islands) must have a single root element. (HTML comments are considered elements as well.)

I think it makes sense to add it in `@nuxt/eslint`
