### ISSUE TITLE
Instance type of Server component does not contain `refresh` 

### ISSUE THREAD

**Issue by kingyue737** [nuxt/nuxt#27730]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-qjtrhd

### Describe the bug

IslandComponent does have method [`refresh`](https://stackblitz.com/edit/github-qjtrhd) but it does not exist in its type.

Enter the reproduction and you will see `vue-tsc` throwing error

**Comment by danielroe** [comment]
(For now you can use `// @ts-expect-error`.)
