### ISSUE TITLE
Route middleware causing duplicate runs on error

### ISSUE THREAD

**Issue by jopandey** [nuxt/nuxt#27738]
### Environment

- Operating System: Darwin
- Node Version:     v18.16.1
- Nuxt Version:     3.11.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  yarn@1.22.18
- Builder:          -
- User Config:      ssr, app, runtimeConfig, telemetry, devServer, typescript, devtools, postcss, tailwindcss, experimental, features, vite, nitro, routeRules, hooks, swiper, image, i18n, modules
- Runtime Modules:  nuxt-swiper, @nuxtjs/tailwindcss@^6.11.4, @nuxt/image@1.7.0, @nuxtjs/i18n@8.3.1, @storyblok/nuxt
- Build Modules:    -

### Reproduction

[Stackblitz](https://stackblitz.com/edit/nuxt-starter-qbz8xk?file=middleware%2Fredirect.global.ts)

### Describe the bug

I am using route middleware in my project to handle invalid requests. The middleware matches the requested path against valid URLs in the project. If the path doesn't match a valid URLs, it throws an error and results in a 404/error page. When the path is valid, the route middleware runs only once. However, in the case of an error, it runs twice. I am not using any navigation for the error page; it simply throws an error inside the route middleware.

Let me know if you need more info.

**Comment by danielroe** [comment]
This is expected. When an error page is rendered, it is done so as an entirely separate 'page load'. So you can check in your middleware if `import.meta.server && useError().value` is true, and avoid additional API calls if that is the case.

We should likely better document this in related places in the docs:
- error page rendering
- middleware
- plugins

We added a note to the docs about this in https://github.com/nuxt/nuxt/pull/27481.
