### ISSUE TITLE
 ERROR  [nuxt] [request error] [unhandled] [500] [GET] "api/xx/yy": <no response> fetch failed. About using $fetch in server

### ISSUE THREAD

**Issue by BocaiheDabaicai** [nuxt/nuxt#27754]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.20.3
- Nuxt Version:     3.12.1
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  pnpm@9.4.0
- Builder:          -
- User Config:      devtools, css, postcss, app, runtimeConfig
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

```
// server/api/a/test.js
export default defineEventHandler(async event => {
    const nowPlayingMovies = await $fetch('https://jsonplaceholder.typicode.com/todos/1', {
        method: 'GET',
        headers: {
            accept: 'application/json',
        },
    })
    return {nowPlayingMovies}
})

// pages/index.vue
const {data} = await useFetch('/api/a/test',{
  transform:data => {
    console.log(data)
  }
})
```
console will report：
 ERROR  [nuxt] [request error] [unhandled] [500] [GET] "https://jsonplaceholder.typicode.com/todos/1": <no response> fetch failed

### Describe the bug

In the server, using $fetch requests data gets 500 errors, but using useFetch in client requests data can successfully get data.
Here is the situation:
```
// server
export default defineEventHandler(async event => {
    const nowPlayingMovies = await $fetch('https://jsonplaceholder.typicode.com/todos/1', {
        method: 'GET',
        headers: {
            accept: 'application/json',
        },
    })
    return {nowPlayingMovies}
})

// client
const {data} = await useFetch('/api/movies/nowplaying',{
  transform:data => {
    console.log(data)
  }
})
```
![image](https://github.com/nuxt/nuxt/assets/108516200/645f6679-20a5-44e5-a1bd-43bbc6588aa7)
ERROR  [nuxt] [request error] [unhandled] [500] [GET] "api/xx/yy": <no response> fetch failed

---

```
// client
const {data, error} = await useFetch('https://jsonplaceholder.typicode.com/todos/1');

```
![image](https://github.com/nuxt/nuxt/assets/108516200/2816fe03-5d1c-4eae-a564-eee323457e0c)
Success get data

### Additional context

I hope to get a proper solution method. Thank you !!

**Comment by manniL** [comment]
https://stackblitz.com/edit/nuxt-issues-27754 can't reproduce.

**Comment by BocaiheDabaicai** [comment]
> https://stackblitz.com/edit/nuxt-issues-27754 can't reproduce.

Sorry, this may be my local environment question, and I need to know what situations can report 500 error about $fetch.

I found that using $fetch in server can get different response results, url: `https://jsonplaceholder.typicode.com/posts` reports 500 error (fetch no response), but url: `https://api.api-ninjas.com/v1/celebrity` reports 200 (success).

Could you provide me with some advice for helping me inspect server errors?

**Comment by manniL** [comment]
check your `error.value` and debug what it is in there (error message, cause, etc. etc.)

**Comment by Benbende41** [comment]
i got the same bug! when i use $fetch  in the server , the terminal will give 500 errors code ,but when i use useFetch in client it will work and give me the right response,it makes me very confused. ![Image](https://github.com/user-attachments/assets/148023a2-4a2b-41e4-9546-28da11afb050)
![Image](https://github.com/user-attachments/assets/b46ba29f-0173-4fbf-bab3-fdd4e82f3733)

which i use api is https://api.themoviedb.org/3/discover/movie?include_adult=false&include_video=false&language=en-US&page=1&sort_by=popularity.desc

![Image](https://github.com/user-attachments/assets/8eb61b57-d3e4-48f5-869a-49c668d129e9)

![Image](https://github.com/user-attachments/assets/34e89e03-1b59-41ad-98e7-bfb4005a3dfd)
