### ISSUE TITLE
Slot "default" invoked outside of the render function when using a composable (contains useLazyAsyncData) inside ClientOnly component

### ISSUE THREAD

**Issue by sharifzadesina** [nuxt/nuxt#27752]
### Environment

- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  @nuxt/content@2.13.0
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-mzb2e5

Open the console and click on the "Link".

### Describe the bug

If you create a composable with `useLazyAsyncData` and then call it inside `ClientOnly` component it will log the below warning when you want to navigate between pages:

```
chunk-2XHGWBZJ.js?v=008d553a:1512 [Vue warn]: Slot "default" invoked outside of the render function: this will not track dependencies used in the slot. Invoke the slot function inside the render function instead. 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <Default ref=Ref< Proxy(Object) {…} > > 
  at <LayoutLoader key="default" layoutProps= {ref: RefImpl} name="default" > 
  at <NuxtLayoutProvider layoutProps= {ref: RefImpl} key="default" name="default"  ... > 
  at <NuxtLayout> 
  at <App key=3 > 
  at <NuxtRoot>
```

### Additional context

Using `useLazyAsyncData` directly inside the component is Okay and works without problem.

**Comment by GalacticHypernova** [comment]
Can't reproduce with the same reproduction link

![image](https://github.com/nuxt/nuxt/assets/92037085/40443919-a966-4866-9c79-0a35f07b8e95)

**Comment by GalacticHypernova** [comment]
This works when removing the `await` inside the `useExampleData` function (and keeping the await in the component).
Even in the nuxt documentation, the recipe to creating a custom `useFetch` (which is a wrapper for useAsyncData with $fetch, exactly like in your example) does not await it inside the wrapper, because the await still needs to happen in the sfc.

https://stackblitz.com/edit/nuxt-starter-ushcbj?file=composables%2FuseExampleData.ts

https://nuxt.com/docs/guide/recipes/custom-usefetch

**Comment by sharifzadesina** [comment]
@GalacticHypernova It would be better to add this to docs.

**Comment by GalacticHypernova** [comment]
It's already present in the recipe 🙂

**Comment by sharifzadesina** [comment]
@GalacticHypernova Yeah, but no where is docs says you can't "await" `useAsyncData`.

**Comment by GalacticHypernova** [comment]
You can, but it has to be inside the script setup block (as opposed to $fetch which can also be awaited outside)

**Comment by sharifzadesina** [comment]
@GalacticHypernova Ok, Ifix my comment.
 no where in the docs says you can't "await" useAsyncData in a composable.

**Comment by GalacticHypernova** [comment]
Opened a PR for it 👍

**Comment by sharifzadesina** [comment]
@GalacticHypernova Thanks.
