### ISSUE TITLE
how to set boost to false in nuxt.config.js

### ISSUE THREAD

**Issue by robertyclin** [nuxt/nuxt#27756]
### Describe the feature

I can't find any description about Boost.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
What is boost? 🤔

**Comment by DamianGlowala** [comment]
@manniL I think we can close this, it refers to (misleading) Nuxt bot's suggestion here: https://github.com/nuxt/nuxt/issues/27751
