### ISSUE TITLE
Unable to import useRuntimeConfig from a layer's server middleware

### ISSUE THREAD

**Issue by cmgdragon** [nuxt/nuxt#27761]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.11.0
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    -
- Package Manager:  pnpm@9.0.6
- Builder:          -
- User Config:      extends, runtimeConfig, i18n
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-6sjdoj?file=base%2Fserver%2Fserver%2Fmiddleware%2Fsecurity.js

pnpm dev  -> useRuntimeConfig is not defined
pnpm build && pnpm preview -> working as expected

### Describe the bug

I'm using layers for providing security to my server endpoints (in this case, validating a jwt token) and I need to access an environment variable defined in the **runtimeConfig** for such validation

however when starting the dev server, it cannot resolve the `useRuntimeConfig` auto-import. Same happens with `defineEventHandler` or `getRequestHeaders`, it won't find those if not explicity imported from 'h3'

### Additional context

It only happens during dev mode and if you're using a different package manager than npm  (tested with pnpm and bun)

**Comment by danielroe** [comment]
Does it work if you rename to `*.ts` rather than `*.js`?

**Comment by cmgdragon** [comment]
> Does it work if you rename to `*.ts` rather than `*.js`?

okay, that did the trick. I just had to switch the extension to `.ts`. I didn't even think about it because with npm was working just fine with `.js`

thanks!
