### ISSUE TITLE
Nuxt doesn't update when making CSS changes

### ISSUE THREAD

**Issue by sugoidesune** [nuxt/nuxt#27769]
### Environment

- Operating System: Windows_NT
- Node Version:     v22.1.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.7.0
- Builder:          -
- User Config:      devtools, ssr, modules, alias, colorMode, vuefire
- Runtime Modules:  @nuxtjs/tailwindcss@6.12.0, shadcn-nuxt@0.10.4, nuxt-vuefire@1.0.2, @vueuse/nuxt@10.9.0, @pinia/nuxt@0.5.1, @nuxtjs/color-mode@3.4.1
- Build Modules:    -

### Reproduction

Any project

### Describe the bug

When saving changes in HTML/template the website updates.
When saving changes in Javascript/script the website updates.
When saving changes in CSS the website **does not** updates.
A manual refresh is necessary, or adding a space in the script part.

**Comment by martinszeltins** [comment]
Seems to be working fine for me. Could you please share a minimal reproduction?

**Comment by sugoidesune** [comment]
Of course it fixed itself after 30min and after posting this... 😅✌️
