### ISSUE TITLE
You must define the vuex store in the server side and use VuexPersistencePlugin in the plugin list.

### ISSUE THREAD

**Issue by bbhxwl** [nuxt/nuxt#27765]
**Summary (generated)**:

I used cookie persistence, but how can I use it with the server?

<hr>

Pinia, I used cookie persistence, but how can I use it with the server?

<img width="1159" alt="image" src="https://github.com/nuxt/nuxt/assets/26525599/36ef4664-d9b9-4d33-8a90-25c3399c01d1">

**Comment by GalacticHypernova** [comment]
How about using h3's [`getCookie`](https://h3.unjs.io/utils/advanced#getcookieevent-name)?

**Comment by bbhxwl** [comment]
> In order to access the cookie on the server, you can use the server side utilities like h3's [`getCookie`](https://h3.unjs.io/utils/advanced#getcookieevent-name)

So, do we need two different types of code to handle it?

**Comment by GalacticHypernova** [comment]
Yes, because the server portion of the app is different from the client. Vuex only works on the client as it's part of vue.
