### ISSUE TITLE
Utils Dir in compatibility Mode not auto-imported

### ISSUE THREAD

**Issue by pisandelli** [nuxt/nuxt#27763]
### Environment

Nuxt project info:                                                 10:36:49 AM

------------------------------
- Operating System: Linux
- Node Version:     v20.14.0
- Nuxt Version:     3.12.3-28642550.8578e2bd
- CLI Version:      3.11.2-1718100309.03d4a54
- Nitro Version:    2.9.6
- Package Manager:  bun@1.1.13
- Builder:          -
- User Config:      app, typescript, imports, modules, runtimeConfig, devtools, future, compatibilityDate
- Runtime Modules:  @nuxt/fonts@0.7.0, @nuxt/image@1.7.0, @nuxt/test-utils@3.13.1, @nuxtjs/html-validator@1.8.2, @vueuse/nuxt@10.11.0, dayjs-nuxt@2.1.9, nuxt-aos@1.2.4, @pinia/nuxt@0.5.1, vuetify-nuxt-module@0.14.1
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-jwxut5?file=app%2Fapp.vue

### Describe the bug

Trying to use `~/utils/rootTest.ts` or `~/utils/services/test.ts` is not working in script tag, only in template.

```html
<script setup lang="ts">

//These will throw a 500 Error.
//can't access lexical declaration [CONST_NAME] before initialization
const test = test();
const rootTest = rootTest();

</script>

<template>
  <div>
    <!--This works!-->
    <p>{{ test() }}</p>

    <!--This works!-->
    <p>{{ rootTest() }}</p>
  </div>
</template>
```

### Additional context

Using Nuxt in compatibilityMode 4

### Logs

```shell-script
ERROR  [nitro] [unhandledRejection] $setup.test is not a function

  renderComponentSubTree@node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:693:18
  renderComponentVNode@node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:637:12
  ssrRenderComponent@node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:84:10
  default@node_modules/nuxt/dist/app/components/nuxt-root.vue:102:38
  ssrRenderSuspense@node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:466:5
  _sfc_ssrRender@node_modules/nuxt/dist/app/components/nuxt-root.vue:91:26
  renderComponentSubTree@node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:693:18
  renderComponentVNode@node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:637:12
  renderToString@node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:911:24
  renderToString$1@.nuxt/dev/index.mjs:1134:101
  renderToString@node_modules/vue-bundle-renderer/dist/runtime.mjs:200:40
```
```

**Comment by mehaac** [comment]
You can try renaming your constants to const testZ = test() and const rootTestZ = rootTest(). This should help.

**Comment by pisandelli** [comment]
It works. Thanks for the tip @mehaac, but I'm wondering this is just a workaround, right?

**Comment by GalacticHypernova** [comment]
Not really, this is just how JS (and TS, Vue, etc) behave. Since you named your components the same name as the functions, it takes the closest declaration by scope (auto imports have a further scope compared to the sfc's own setup function).

**Comment by pisandelli** [comment]
Thanks @GalacticHypernova and @mehaac
