### ISSUE TITLE
Middleware issue when redirecting with encodeURIComponent

### ISSUE THREAD

**Issue by Lucas-Gruber** [nuxt/nuxt#27776]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.12.0
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  yarn@1.22.22
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/Lucas-Gruber/nuxt-reproduction-middleware

### Describe the bug

I aim to generate an encoded URI string as a query parameter for redirection when the user is not authenticated with a middleware. However, the current implementation results in double encoding of the URL path. 

For example, instead of obtaining a redirect URL like:
`http://localhost:3000/?redirect=%2Fprotected%2Fprofile`, the application produces:
`http://localhost:3000/?redirect=%252Fprotected%252Fprofile`. 

This indicates that the URL path is being encoded twice, leading to unintended behavior in redirection.

### Logs

```shell-script
Nuxt 3.12.2 with Nitro 2.9.6                                                                                         1:20:14 AM
                                                                                                                     1:20:14 AM
  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

  ➜ DevTools: press Shift + Option + D in the browser (v1.3.6)                                                       1:20:16 AM

✔ Nuxt Nitro server built in 2947 ms                                                                          nitro 1:20:22 AM
ℹ Vite client warmed up in 5874ms                                                                                   1:20:23 AM
ℹ Vite server warmed up in 5534ms                                                                                   1:20:23 AM

called auth.ts
Redirect-URI: %2Fprotected%2Fprofile
```

**Comment by GalacticHypernova** [comment]
You don't need to generate a URI encoded version of it, as that is already handled by the router. You can see that even when placing the regular string it handles the navigation correctly internally, because `ufo` (the underlying dependency used in Nuxt) encodes it when using `withQuery` in the `navigateTo` source code.

**Comment by Lucas-Gruber** [comment]
But when I don't encode the url, it's decided in the query string. Isn't this a problem?

**Comment by GalacticHypernova** [comment]
What kind of problem are you experiencing with it?

**Comment by Lucas-Gruber** [comment]
Then i get this:
![CleanShot 2024-06-22 at 16 48 57@2x](https://github.com/nuxt/nuxt/assets/72545889/527510fe-fc73-4447-9d43-55b1a92f1b7a)

I think Nuxt decodes it automatically or something doesn't work when i do this.

**Comment by GalacticHypernova** [comment]
Works fine for me:
![image](https://github.com/nuxt/nuxt/assets/92037085/5c749703-17fe-4223-a38c-a21a712f784b)

I also still don't quite understand what issues you ran into?

**Comment by Lucas-Gruber** [comment]
Okay, i tested some stuff and it looks like Nuxt auto replaces "%2F" with "/" in the URL.

I tested now also in an completely new Project in Stackblitz and a fresh Browser, typing manually "%2Fprotected%2Fprofile" in the URL-Bar and it replaces the query with: "/protected/profile".

So i think it is intentionally from nuxt.

I wanted to encode it, because i had in other projects issues with plain, decoded urls. Maybe isn't this a problem anymore.
