### ISSUE TITLE
Wrapping useFetch in a function causes hydration mismatch

### ISSUE THREAD

**Issue by IcyFoxe** [nuxt/nuxt#27775]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.11.1
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.1
- Builder:          -
- User Config:      components, css, devtools, vite
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

-

### Describe the bug

Since recent update, wrapping `useFetch` in a custom function causes hydration mismatch.
This doesn't happen if useFetch is in the root of the setup script.

I didn't receive this error before upgrading Nuxt today. Previous version I had was `3.11.2`. However I cannot replicate NOT having this mismatch error even after downgrading the packages again. Did something change recently?

Benefit of wrapping useFetch in a custom function was that in isolates the logic, and allows using destructured variables without renaming them.

**Comment by GalacticHypernova** [comment]
`useFetch` is generally used for for async data pre-mounting. Depending on what kind of function you wrapped it in, there is no point in using it if it's after user interaction, as that's already on the client and will have no benefit over the regular `$fetch` (which is used under the hood)

**Comment by IcyFoxe** [comment]
Something like this was an intention, when you need to use `useFetch` multiple times in a single file, it makes its usage easier, when the logic is separated in a function..

```js
const state = reactive({
  data1: [],
  data2: [],
});

(() => {
  const { data } = await useFetch("/api/route-1");
  state.data1 = data.value || [];
})()

(() => {
  const { data } = await useFetch("/api/route-2");
  state.data2 = data.value || [];
})()

```

**Comment by IcyFoxe** [comment]
Anyway, regarding my issue, is there any reason why `useFetch` cannot be used elsewhere other than top level of the sfc setup? Why is this throwing hydration mismatch warning?

**Comment by agracia-foticos** [comment]
I think i have the same issue with https://github.com/johannschopplich/nuxt-api-party
