### ISSUE TITLE
Nuxt 4 - allow flat layers directory structure without needing `layers` directory, allow each layer to have its own server routes

### ISSUE THREAD

**Issue by martinszeltins** [nuxt/nuxt#27770]
### Describe the feature

In Nuxt 3, I loved how I could have a flat layers structure. It meant that as soon as someone opened my app directory, they could immediately see what this app was about. It looks like this:

````
users
  └─ components
  └─ composables
  └─ server
  └─ nuxt.config.ts
settings
  └─ components
  └─ composables
  └─ server
  └─ nuxt.config.ts
sales
  └─ components
  └─ composables
  └─ server
  └─ nuxt.config.ts
app.vue
package.json
nuxt.config.ts
````

Now with Nuxt 4 we have an `app/` directory which is fine but in order to use layers you need to also nest them inside `app/layers` which is just unnecessary noise. It would be nice to be able to have a nice, clean and flat structure like this:

Nuxt 4

````
app
  └─ users
      └─ components
      └─ composables
      └─ server
      └─ nuxt.config.ts
  └─ settings
      └─ components
      └─ composables
      └─ server
      └─ nuxt.config.ts
package.json
nuxt.config.ts
````

Instead now I am forced to have `my-fancy-app/app/layers/users` - the `layers` is totally unnecessary in this case.

Also, each of my layers (which is a mini Nuxt app) had its own `server` with api routes. It seems this is not possible anymore? I don't want to put all my `server` api routes in one place. I would rather group my user api routes with my user layer and my settings api routes in my settings layer which makes more sense.

**UPDATE:**
It looks like this is already possible with Nuxt 4, I got both flat layers and `server/` inside each layer working. But that makes me wonder and confused me - why do we still have the `layers` directory? It seems not needed. Or is layers/ directory a special one that auto-registers layers without having to write `extends`? This is confusing, hopefully we can get this explained in the docs. Here is my demo project - https://stackblitz.com/~/github.com/martinszeltins/nuxt-4-test-app

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Yes, `layers/` is a special directory for auto-registration, and it is not within `app/`. You can completely ignore it if you don't want to use the auto-registration feature.

**Comment by martinszeltins** [comment]
@danielroe Thanks for the answer! I just wanted to clarify one thing. When reading about Nuxt 4, it says that the "Vue" part of the app will go into the new `app` directory. But is that truly accurate? Because like you said, I can just ignore the `layers/` directory and do this in Nuxt 4 where I have `server` inside `app/`, right? Will would give me that clean, flat directory structure just like in Nuxt 3.

Juts wanted to clarify that this is ok and that it is not entirely true that `app/` is only for "Vue" in every case.

````
app
  └─ users
      └─ components
      └─ composables
      └─ server
      └─ nuxt.config.ts
  └─ settings
      └─ components
      └─ composables
      └─ server
      └─ nuxt.config.ts
package.json
nuxt.config.ts
````

**Comment by danielroe** [comment]
No, it would work like this:

```
layers/
  └─ users/
      └─ app/
            └─ components
            └─ composables
      └─ server/
      └─ nuxt.config.ts
  └─ settings/
      └─ app/
            └─ components
            └─ composables
      └─ server/
      └─ nuxt.config.ts
package.json
nuxt.config.ts
```

**Comment by martinszeltins** [comment]
> Yes, layers/ is a special directory for auto-registration, and it is not within app/. You can completely ignore it if you don't want to use the auto-registration feature.

I thought I could ignore the `layers/` directory if I didn't want to use auto-registration. Still a bit confused about this.

**Comment by martinszeltins** [comment]
> Oh, yes you can manually specify layers in your nuxt config. I thought you were asking about auto-registration.

ok, awesome! In that case, I could have this structure, right? And I shouldn't be concerned in this case that "server" is under "app"?

````
app
  └─ users
      └─ components
      └─ composables
      └─ server
      └─ nuxt.config.ts
  └─ settings
      └─ components
      └─ composables
      └─ server
      └─ nuxt.config.ts
package.json
nuxt.config.ts
````

**Comment by danielroe** [comment]
I would advise against it as `app/` will be confusing as it will have a totally different meaning in the nuxt docs as in your custom setup. additionally by not adopting the `app/` + `server/` pair within each layer, you will experience slower speeds when loading your project as we can't optimise the watcher as well.
