### ISSUE TITLE
Build issue: Lexical.node.mjs not found, only Lexical.prod.mjs present

### ISSUE THREAD

**Issue by Rusinas** [nuxt/nuxt#27784]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.15.0
- Nuxt Version:     -
- CLI Version:      3.12.0
- Nitro Version:    -
- Package Manager:  unknown
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

I'm using Nuxt and Lexical.js and I'm trying to build the project with the nuxt build command. After this, my dependencies are placed in the .output/server/node_modules folder in a compiled form. However, when running the built project, Nuxt requests the Lexical.node.mjs file, while only Lexical.prod.mjs is present in the folder. The package.json inside .output/node_module/Lexical looks like this:
```
  "name": "lexical",
  "description": "Lexical is an extensible text editor framework that provides excellent reliability, accessible and performance.",
  "keywords": [
    "react",
    "lexical",
    "editor",
    "contenteditable",
    "rich-text"
  ],
  "license": "MIT",
  "version": "0.16.0",
  "main": "Lexical.js",
  "types": "index.d.ts",
  "repository": {
    "type": "git",
    "url": "https://github.com/facebook/lexical",
    "directory": "packages/lexical"
  },
  "module": "Lexical.mjs",
  "sideEffects": false,
  "exports": {
    ".": {
      "import": {
        "types": "./index.d.ts",
        "development": "./Lexical.dev.mjs",
        "production": "./Lexical.prod.mjs",
        "node": "./Lexical.node.mjs",
        "default": "./Lexical.prod.mjs"
      },
      "require": {
        "types": "./index.d.ts",
        "development": "./Lexical.dev.js",
        "production": "./Lexical.prod.js",
        "default": "./Lexical.prod.js"
      }
    }
  }
}
```
Here we can see that there's an export for Lexical.node.mjs, however, it's not created during the build process. What's happening here and how can I fix this?

### Describe the bug

```500
Cannot find module '/app/.output/server/node_modules/lexical/Lexical.node.mjs' imported from /app/.output/server/chunks/build/Post-RhhK4vZX.mjs 
```

When open a page that uses Lexical.

**Comment by GalacticHypernova** [comment]
Could you please provide a minimal project that encounters this?

**Comment by Rusinas** [comment]
@GalacticHypernova sure. https://github.com/Rusinas/nuxt-build-bug

Just build it and run `npm preview`, open it and check the server console, there will be this error: 
```
[nuxt] [request error] [unhandled] [500] Cannot find module 'C:\Users\andre\Desktop\Code\Stuff\build-bug\.output\server\node_modules\lexical\Lexical.node.mjs' imported from C:\Users\andre\Desktop\Code\Stuff\build-bug\.output\server\chunks\build\server.mjs
```

Then you can check the `.output/node_modules/lexical`, there is a Lexical.prod.mjs, but no Lexical.node.mjs for some reason. If I change the `prod` to 'node` manually, everything will work just fine, but I don't really want to do this in my apps, because there are another `@lexical/***` packages that fail like this and I think it would be better to find the reason.

**Comment by GalacticHypernova** [comment]
https://stackblitz.com/edit/github-nmwrag?file=app.vue,package.json

Used this one, can't reproduce, I guess you can take a look at what could be different between implementations
![image](https://github.com/nuxt/nuxt/assets/92037085/cd967b26-d5c6-44e9-8875-eb63cf8f7874)

**Comment by Rusinas** [comment]
@GalacticHypernova thanks for checking. Yes, the problem is only in production (I described how to reproduce it locally above), I guess I should've mentioned that. 

Speaking of nuxt being a dev dependency - probably I installed it like that by mistake, I will change that, but I'm pretty sure this is not the reason.

**Comment by manniL** [comment]
It also is reproducible on stackblitz with build an run, yes. Most likely a dep issue though.
![image](https://github.com/nuxt/nuxt/assets/640208/8c2eaaa6-8d88-4b01-952f-891ed878e328)

**Comment by danielroe** [comment]
This is likely an issue with nitro's tracing of the dependencies. You can likely work around by adding the file you need to `nitro.externals.traceInclude`.

Would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏

**Comment by Rusinas** [comment]
@manniL you mean this could be a problem with the `Lexical` itself?

@danielroe could you please provide an example of using `traceInclude`? I couldn't find any docs on this, tried to add there `Lexical.node.js` but it didn't help

**Comment by manniL** [comment]
Simple workaround @Rusinas :

```ts
export default defineNuxtConfig({
  devtools: { enabled: true },
  nitro: {
    externals: {
      traceInclude: ['node_modules/lexical/Lexical.node.mjs']
    }
  }
})
```

**Comment by manniL** [comment]
Let's track in https://github.com/unjs/nitro/issues/2562
