### ISSUE TITLE
Improve Nuxt auto-imports to ignore undefined name properties

### ISSUE THREAD

**Issue by jinyongp** [nuxt/nuxt#27795]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.12.0
- Nuxt Version:     3.10.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.5.0
- Builder:          -
- User Config:      devtools, imports
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

[Reproduction](https://codesandbox.io/p/devbox/damp-thunder-yqgwd6?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxssug5h00073b6jo0s0xriu%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxssug5h00023b6j2czgep2u%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxssug5h00043b6j7nmrl0k3%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxssug5h00063b6jpf02n1hz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxssug5h00023b6j2czgep2u%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxssug5h00013b6j942bd6z4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clxssug5h00023b6j2czgep2u%2522%252C%2522activeTabId%2522%253A%2522clxssug5h00013b6j942bd6z4%2522%257D%252C%2522clxssug5h00063b6jpf02n1hz%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxssug5h00053b6jyx42qqf2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxssug5h00063b6jpf02n1hz%2522%252C%2522activeTabId%2522%253A%2522clxssug5h00053b6jyx42qqf2%2522%257D%252C%2522clxssug5h00043b6j7nmrl0k3%2522%253A%257B%2522id%2522%253A%2522clxssug5h00043b6j7nmrl0k3%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxssug5h00033b6j2q0wqij8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clxssug5h00033b6j2q0wqij8%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Describe the bug

When configuring imports in nuxt.config.ts, if the name property is not specified, it should be ignored instead of being set to undefined.

configuration:

```ts
imports: {
  imports: [
    { as: '_', from: 'remeda' },
  ],
},
```

Current behavior:

```ts
const _: (typeof import('../../node_modules/remeda'))['undefined'];
```

Expected behavior:

```ts
const _: (typeof import('../../node_modules/remeda'));
```

By implementing this change, it will be possible to import all exports from modules that do not have a default export.

**Comment by manniL** [comment]
This sounds more like an issue of https://github.com/unjs/unimport itself. Could you check it with only unimport and raise it there if it occurs with just the lib?

**Comment by jinyongp** [comment]
I found that setting the name property to '*' resolves this issue:

```ts
imports: {
  imports: [
    { as: '_', from: 'remeda', name: '*' },
  ],
},
```

result:

```ts
const _: typeof import('../../node_modules/remeda');
```

This solution was not documented in unimport's README, but it effectively addresses the issue.

Thank you for your help.

**Comment by manniL** [comment]
@jinyongp please feel free to send a PR to the README to add the case 👍🏻
