### ISSUE TITLE
Unable to send options via `addServerHandler`

### ISSUE THREAD

**Issue by cybercoder-naj** [nuxt/nuxt#27802]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v22.2.0
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  bun@1.1.13
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

This is a [repo](https://github.com/cybercoder-naj/nuxt-subdomains) with a proposed module. 

### Describe the bug

I am not sure how to send options to the server middleware here. I have a `TODO` in the above repo [here](https://github.com/cybercoder-naj/nuxt-subdomains/blob/main/src/module.ts#L32) and [here](https://github.com/cybercoder-naj/nuxt-subdomains/blob/main/src/runtime/server/subdomain-handler.ts#L8). 

### Additional context

Pass options to the server middleware via nuxt-kit when authoring a nuxt module.

**Comment by manniL** [comment]
Suggestion: Use runtime config + copy the settings, then use useRuntimeConfig to retireve them.
