### ISSUE TITLE
`layout: false` does not remove the layout when multiple routes use the same page component

### ISSUE THREAD

**Issue by ianjamieson** [nuxt/nuxt#27814]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v22.1.0
- Nuxt Version:     3.12.0
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  npm@10.7.0
- Builder:          -
- User Config:      devtools, runtimeConfig, vite, alias, modules, image, hooks, nitro, serverMiddleware, build, css
- Runtime Modules:  @pinia/nuxt@0.5.1, @tixel/ui-nuxt@0.0.7, @tixel/component-library@0.4.0, nuxt-jsonld@2.0.8, @pinia-plugin-persistedstate/nuxt@1.2.0, @nuxt/devtools@1.3.6, @nuxt/image@1.0.0-rc.3, @vueuse/nuxt@10.11.0, @nuxtjs/device@3.1.1, @nuxt/content@2.12.1
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-m1cmbw?file=pages%2Fexample-page.vue

### Describe the bug

On the reproduction URL

Go to `/example-page`

You will see that there is no default layout set, because the page component has:

```
definePageMeta({
  layout: false,
});
```

However, now go to `/example-page-2` and you will see that this page still includes the layout, despite using the same component as the other route.

Both pages should not render the layout.

See the routes are rendered in `routes.ts`

### Additional context

This only occurs in `v3.12.x`, rolling back to `v3.11.x` fixes the issue.

**Comment by manniL** [comment]
`example-page-2` is missing from the repo 🤔

**Comment by manniL** [comment]
Probably because the extraction of the meta happens *before* extending the routes 🤔

**Comment by manniL** [comment]
As a workaround, you can set `experimental.scanPageMeta` to false!
