### ISSUE TITLE
Server component cannot be the root element of another server component

### ISSUE THREAD

**Issue by kingyue737** [nuxt/nuxt#27810]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-qjtrhd-mtyvxv

### Describe the bug

```vue
<!-- MyWrapper.server.vue -->
<template>
  <AnotherServerComponent />
</template>
```

Directly using a server component as another server component's root will cause a hydration warning:
```
runtime-core.esm-bundler.js:48  [Vue warn]: Hydration node mismatch:
- rendered on server: <!--]-->  
- expected on client: Symbol(v-fgt) 
  at <NuxtIsland name="MyWrapper" lazy=false props= Proxy(Object) {}  ... > 
  at <MyWrapper> 
  at <App key=4 > 
  at <NuxtRoot>
```

```
[Vue warn]: Hydration children mismatch on <div data-v-inspector=​"app.vue:​4:​3">​…​</div>​ 
Server rendered element contains fewer child nodes than client vdom. 
  at <NuxtIsland name="MyWrapper" lazy=false props= Proxy(Object) {}  ... > 
  at <MyWrapper> 
  at <App key=4 > 
  at <NuxtRoot>
```

I think it is at least an undocumented behavior.

### Additional context

The previous post in https://github.com/nuxt/nuxt/issues/27731#issuecomment-2180766312 was ignored so I reopened a new issue.

**Comment by danielroe** [comment]
Yes, this should be documented.

**Comment by huang-julien** [comment]
it's not really a good practice as we have 2 waterfall for server comps. Let's find a place to add this

**Comment by Rigo-m** [comment]
It's not good practice to have a server component inside a server component?

**Comment by huang-julien** [comment]
It's not as you'll have a waterfall of internal fetch. 

main app -- fetch ---> island -- fetch --> island
