### ISSUE TITLE
app.baseURL is no longer applied to url(...) in <style> since v3.11.0

### ISSUE THREAD

**Issue by atoka-tech** [nuxt/nuxt#27818]
### Environment

```
------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.11.1
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, app
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Reproduction

3.10.3 (works as expected): https://stackblitz.com/edit/github-e5yfeu-ko5zsj?file=app.vue
3.11.1 or later (broken): https://stackblitz.com/edit/github-e5yfeu?file=app.vue

(Using 3.11.1 because 3.11.0 does not work on StackBlitz: https://github.com/nuxt/nuxt/issues/26347)

### Describe the bug

In v3.11.0 and later, `app.baseURL` is no longer automatically added even if the path to a asset in the `public` directory is specified in the `url()` in `<style>`.

**Comment by danielroe** [comment]
This was resolved in v3.12 via https://github.com/nuxt/nuxt/pull/27327.

**Comment by atoka-tech** [comment]
@danielroe Thank you! But this doesn't seem to have been fixed yet.

Reproduction in v3.12.3 (The `favicon.ico` should be displayed, but it is not.)
https://stackblitz.com/edit/github-dpiewu?file=app.vue

Is this by any chance a specification from v3.11?

**Comment by Jak-Ch-ll** [comment]
This issue is not limited to `<style>` tags, but also happens with `url(..)` in .css files.

As a workaround we have set the baseURL manually for our assets, but this creates annoying build warning, because https://github.com/nuxt/nuxt/pull/27328 does not recognize the paths with baseURL
