### ISSUE TITLE
Improve "setup is not a function" error when misusing `runWithContext`

### ISSUE THREAD

**Issue by saturn4er** [nuxt/nuxt#27827]
### Environment

any

### Reproduction

https://stackblitz.com/edit/github-e5yfeu-vqz5gn
There's "setup is not a function in console".

### Describe the bug

nuxt throw an error "setup is not a function". It started to appear once I wrapped useFetch with runWithContext

**Comment by saturn4er** [comment]
I discovered why the error occurs. I needed to wrap useFetch within a function. However, the error message was quite unclear.

**Comment by huang-julien** [comment]
closing as #28926 should make you aware that you can only pass a function
