### ISSUE TITLE
`import.meta` warning after updating to 3.12.2

### ISSUE THREAD

**Issue by CernyMatej** [nuxt/nuxt#27826]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  pnpm@8.15.6
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-9dddhv?file=my-module%2Fsrc%2Fmodule.ts

Open `nuxt.config.ts` and you should see `import.meta` with a red underline and the warning.

### Describe the bug

After updating to Nuxt 3.12.2, I started getting the following warnings in some of my projects:
```
The 'import.meta' meta-property is only allowed when the '--module' option
is 'es2020', 'es2022', 'esnext', 'system', 'node16', or 'nodenext'.
```

What's strange is that it appears in 2 out of 3 of my Nuxt layers and I haven't been able to find a difference between the one, where it doesn't.
However, I was able to reproduce the issue by creating a brand new nuxt module on Stackblitz. Since the error message is the same, I suppose that the cause is the same as in my projects as well.

**Comment by CernyMatej** [comment]
I think this might have been fixed somehow. I can't see it in my projects any more.

**Comment by Serpentarius13** [comment]
Still seeing this with 3.12.4

**Comment by danielroe** [comment]
@Serpentarius13 In that case would you open a new issue with a reproduction, please? 🙏

**Comment by Serpentarius13** [comment]
> @Serpentarius13 In that case would you open a new issue with a reproduction, please? 🙏

Guess it doesnt happen on a clean project..

**Comment by Serpentarius13** [comment]
I guess something is broken with my tsconfig, although I hadnt touched it. Await with useFetch throws an error saying top-level awaits are not okay, although generated and extended config is using ESNext. @danielroe Can you please look into it? https://github.com/Serpentarius13/broken-ts-nuxt

**Comment by Serpentarius13** [comment]
Figured it out.

**Comment by Serpentarius13** [comment]
> what was the problem?

I think some stupid stuff with permissions somehow messed up. I used docker, maybe volume binding did the thing and I couldn't use generated types
