### ISSUE TITLE
Static routes are no longer rendered in v3.11.0

### ISSUE THREAD

**Issue by jdbdnz** [nuxt/nuxt#27828]
### Environment

- Operating System: Darwin
- Node Version:     v18.19.0
- Nuxt Version:     3.11.0
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      ssr
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

I can reproduce on a fresh install using SSR from v3.11.0. 

## Reproduce on v3.12.2

```
npx nuxi@latest init reproduce-prerender-routes-error --gitInit=false --packageManager=npm
cd reproduce-prerender-routes-error

mkdir pages
echo "<template>Testing</template>" > pages/testing.vue
echo "export default defineNuxtConfig({
  ssr: false
})" > nuxt.config.ts

npm install
npm run generate
cat .output/public/testing/index.html
```

> cat .output/public/testing/index.html: No such file or directory

## Downgrade to v3.10.3 to resolve

```
npm install nuxt@3.10.3 --save-exact
npm run generate
cat .output/public/testing/index.html
```

> ...(html)...

## Upgrade to next version, v.3.11.0 to reproduce

```
npm install nuxt@3.11.0 --save-exact
npm run generate
cat .output/public/testing/index.html
```
> cat .output/public/testing/index.html: No such file or directory

### Describe the bug

I expect static route generation to create a file for every route. 

I observe that only default routes are being created.

**Comment by jdbdnz** [comment]
Looks like this PR is the culprit:

https://github.com/nuxt/nuxt/pull/26694

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/27694.

**Comment by jdbdnz** [comment]
> Let's track in https://github.com/nuxt/nuxt/issues/27694.

Thanks @danielroe, can you help me understand why you see this as a duplicate of https://github.com/nuxt/nuxt/issues/27694

- It describes a regression introduced between 3.12.1 and 3.12.2, whereas this issue describes a regression introduced between 3.10.3 and 3.11.0.
- I do not observe `pages/index.vue` affecting whether pages are created for routes during static generation in 3.11.0 (nor in 3.12.2, but I'm also not setting `config.generate` which is a reproduction step of that issue)

**Comment by jdbdnz** [comment]
I've closed https://github.com/nuxt/nuxt/pull/27851 on the advice that a fix will be coming after a near term Nitro release, see comment https://github.com/nuxt/nuxt/pull/27851#issuecomment-2195092353

**Comment by danielroe** [comment]
The fix should resolve both issues but more than happy to keep this open.

**Comment by danielroe** [comment]
With `ssr: false`, there is no difference between every generated page and `200.html`. Instead we recommend configuring your web server to serve every route with `200.html`. Is there a reason you or @fcieminski want to have your web server have these files present?

**Comment by jdbdnz** [comment]
>  Instead we recommend configuring your web server to serve every route with `200.html`.

Alas, not every environment is so generous as to configure this.

> Is there a reason you or @fcieminski want to have your web server have these files present?

Yeah, my CI E2E tests have been failing since https://github.com/nuxt/nuxt/pull/26694 because Cypress is gets 404s when trying to navigate my app.

**Comment by jdbdnz** [comment]
I've just bumped to 3.12.4 and I've confirmed my CI suite is happy again 😌 thank you!

**Comment by nandi95** [comment]
My issue was the node version. LTS works, latest doesn't.
