### ISSUE TITLE
Dynamic component SSR rendering problem

### ISSUE THREAD

**Issue by bastienrossi** [nuxt/nuxt#27836]
### Environment

- Operating System: Linux
- Node Version:     v20.9.0
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, components
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://codesandbox.io/p/devbox/nuxt-3-bug-vl98j5

### Describe the bug

The problem only occurs with the production build.
If a component is imported dynamically and uses components common to its sub-components (e.g. a composable) and this sub-component is used elsewhere in the code, then SSR rendering of the component no longer occurs.
In my example in dev mode, the final rendering of the page is :
```
Hello
Test : foo
Test Child : foo
Test Child 2
Test Child 2 Child : foo
Test Child 2
Test Child 2 Child : foo
```
Unfortunately, in prod mode, the ssr rendering is as follows : 
```
Hello
Test : foo
Test Child : foo
Test Child 2
Test Child 2 Child : foo
```
As the client-side setup also executes for hydration, the rendering updates correctly and everything is displayed, but there is a problem with the SSR rendering.
There are no errors during the nuxt build or when generating the page on the SSR side.
I think the problem must come from rollup because if you look in the file `.output/server/chunks/BaseTestChild2-WlFZNhyr.mjs` there is an export of several elements.
```
const BaseTestChild2 = /* @__PURE__ */ Object.freeze({
  __proto__: null,
  default: _sfc_main
});

export { BaseTestChild2 as B, _sfc_main as _, useFoo as u };
```
If we compare it to a normal component (`.output/server/chunks/BaseTest-DrvCz1q7.mjs`), the export is different.
```
export { _sfc_main as default };
```
For me, the problem comes from the fact that it creates an object with `default: _sfc_main` before exporting it.
When we look at the use of these files in `.output/server/server.mjs` there is a difference.
```
setup(__props) {
    const BaseTest = defineAsyncComponent(
      () => import('./BaseTest-DrvCz1q7.mjs')
    );
    const BaseTestChild2 = defineAsyncComponent(
      () => import('./BaseTestChild2-WlFZNhyr.mjs').then(function(n) {
        return n.B;
      })
    );
}
```
For my part, when I remove the creation of this object to export in the same way as `.output/server/chunks/BaseTest-DrvCz1q7.mjs`, it works.
Or if I add `n.B.default` to the `import('./BaseTestChild2-WlFZNhyr.mjs').then(function(n) {`, that works too.

### Additional context

To reproduce, simply `yarn build` then `yarn preview` in my codesandbox example.
You can look directly at the existing `.output` that contains the problem.
I don't know if this is the right place for this ticket or if I should make a ticket on the rollup side.

**Comment by bastienrossi** [comment]
Hi, the problem doesn't seem to come entirely from rollup, in fact rollup does an object.freeze which returns an object instead of a module (n.B), so the defineAsyncComponent code doesn't work and doesn't call the .default 
```
if (comp && (comp.__esModule || comp[Symbol.toStringTag] === 'Module')) {
  comp = comp.default
}
```
https://github.com/vuejs/core/blob/e0428884b57ac834274045bd33841263aeae259e/packages/runtime-core/src/apiAsyncComponent.ts#L100.

**Comment by danielroe** [comment]
For a workaround, you can add an interop default line:

```ts
const BaseTestChild2 = defineAsyncComponent(
  () => import("@/components/BaseTestChild2.vue").then(r => r.default || r)
);
```

I don't think this is a Nuxt issue but rather a Vue one - `defineAsyncComponent` probably needs to update its condition. Would you raise an issue on https://github.com/vuejs/core/issues/6638 ? 🙏

**Comment by bastienrossi** [comment]
There already seems to be a way out on view concerning the behaviour of "defineAsyncComponent".
https://github.com/vuejs/core/issues/8351
It says that there is also another, cleaner alternative to converting everything to es2015 in rollup to fix the problem temporarily.
```
defineNuxtConfig({
  vite: {
    $server: {
      build: {
        rollupOptions: {
          output: {
            generatedCode: {
              symbols: true // temporary fix for https://github.com/nuxt/nuxt/issues/27836
            }
          }
        }
      }
    }
  }
}
```

**Comment by danielroe** [comment]
I would be willing to investigate adding that configuration in Nuxt by default.

**Comment by SergkeiM** [comment]
@danielroe The issue still exists, at least when I'm deploying to Cloudflare Workers, using `cloudflare_module` nitro preset, SSR is broken, if I replace `defineAsyncComponent` with normal import everything works fine.

**Comment by danielroe** [comment]
@SergkeiM could you create a new issue with a reproduction? 🙏
