### ISSUE TITLE
Nuxt migration 

### ISSUE THREAD

**Issue by Deepakra07** [nuxt/nuxt#27833]
### Environment

getting this error after upgrading nuxt 2 to nuxt 3 

500
[vite-node] [plugin:vite:vue] [SyntaxError] C:/kcweb new/KidsChaupalWeb/pages/assessment/_id.vue:16:29

15 |                :currenttQuestionData="currenttQuestionData"
16 |                @getQuestion="
17 |               query.current_question_id = ''
   |  ^
18 |                 query.question_id = $event
19 |                getAssessQuestionmentDeatils()

at C:/kcweb new/KidsChaupalWeb/pages/assessment/_id.vue:16:29
at createCompilerError (C:\kcweb new\KidsChaupalWeb\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:1328:17)
at emitError (C:\kcweb new\KidsChaupalWeb\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2812:5)
at createExp (C:\kcweb new\KidsChaupalWeb\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2805:7)
at Object.onattribend (C:\kcweb new\KidsChaupalWeb\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2329:29)
at Tokenizer.handleInAttrValue (C:\kcweb new\KidsChaupalWeb\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:909:16)
at Tokenizer.stateInAttrValueDoubleQuotes (C:\kcweb new\KidsChaupalWeb\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:919:10)
at Tokenizer.parse (C:\kcweb new\KidsChaupalWeb\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:1063:16)
at Object.baseParse (C:\kcweb new\KidsChaupalWeb\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2851:13)

![image](https://github.com/nuxt/nuxt/assets/92357726/b5204dc9-d2b0-4b73-9d56-a09e7ecaf5ad)

### Reproduction

After upgrading nuxt 2 to nuxt 3 

### Describe the bug

I upgaded nuxt 2.12.1 to "Nuxt": "^3.12.2" 
  getting this issue  compile time  after running  project

**Comment by manniL** [comment]
if you'd write a handler for `getQuestion` instead of inlining the code, that should work!

**Comment by Deepakra07** [comment]
> if you'd write a handler for `getQuestion` instead of inlining the code, that should work!
is this only nuxt 3 issue because it is using vite under the hood and it is perfectly working in nuxt2 


is there any option to disable the vite js 


this is my package.josn file

{
  "name": "kidschaupalweb",
  "version": "1.0.0",
  "description": "KidsChaupal",
  "author": "Ashish Srivastava",
  "private": true,
  "type": "module",

  "scripts": {
    "dev": "nuxt dev",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "precommit": "npm run lint"
  },
  "dependencies": {
    "@bachdgvn/vue-otp-input": "^1.0.7",
    "@nuxtjs/auth": "^4.9.1",
    "@nuxtjs/axios": "^5.10.3",
    "@nuxtjs/dotenv": "^1.4.1",
    "@nuxtjs/google-analytics": "^2.2.3",
    "@nuxtjs/google-gtag": "^1.0.4",
    "@nuxtjs/sitemap": "^2.2.1",
    "aws-sdk": "^2.672.0",
    "axios": "^1.7.2",
    "body-parser": "^1.19.0",
    "bootstrap": "^4.1.3",
    "bootstrap-vue": "^2.13.1",
    "consola": "^3.2.3",
    "core-js": "3.37.1",
    "cross-env": "^5.2.1",
    "dotenv": "^16.4.5",
    "express": "^4.17.1",
    "express-session": "^1.17.1",
    "firebase": "^7.17.1",
    "firebase-admin": "^12.1.1",
    "js-cookie": "^2.2.1",
    "lodash": "^4.17.15",
    "mobile-device-detect": "^0.3.3",
    "moment": "^2.29.1",
    "nuxt": "^3.12.2",
    "nuxt-facebook-pixel-module": "^1.3.0",
    "sitemap": "^8.0.0",
    "skeleton-loader-vue": "^1.0.10",
    "tb-skeleton": "^0.3.6",
    "timeago.js": "^4.0.2",
    "uuid": "^8.0.0",
    "vee-validate": "^2.2.6",
    "vue-carousel": "^0.18.0",
    "vue-clipboard2": "^0.3.1",
    "vue-content-loader": "^0.2.3",
    "vue-google-autocomplete": "^1.1.0",
    "vue-infinite-scroll": "^2.0.2",
    "vue-loader": "^15.9.3",
    "vue-loading-overlay": "^3.3.2",
    "vue-multiselect": "^2.1.6",
    "vue-pdf": "^4.2.0",
    "vue-star-rating": "^1.7.0",
    "vue-stepper-component": "^1.0.0",
    "@vue/compiler-core": "^3.4.24",
    "vue-sweetalert2": "^1.6.4",
    "vue-toastification": "^1.7.11",
    "vue2-datepicker": "^3.11.0",
    "vuejs-datepicker": "^1.6.2",
    "vue": "^3.4.29"
  },
  "devDependencies": {
    "@nuxt/image": "^1.6.0",
    "eslint": "^9.4.0",
    "sass":"1.77.4",
    "sass-loader": "14.2.0"
  }
}
