### ISSUE TITLE
`definePageMeta` is ignored when used alongside normal <script> since 3.12.x

### ISSUE THREAD

**Issue by patzick** [nuxt/nuxt#27845]
### Environment

Nuxt 3.12.x

### Reproduction

https://stackblitz.com/edit/github-1zinkb?file=pages%2Findex.vue

### Describe the bug

The last update is causing breaking change when someone is using `script` alongside `script setup` to name components for devtools: https://vuejs.org/api/sfc-script-setup.html#usage-alongside-normal-script

This affects `definePageMeta` as it is ignored and Layouts are not working properly

### Additional context

Since Vue 3.3+, there is already a macro `defineOptions` https://vuejs.org/api/sfc-script-setup#defineoptions, and this is respected. 

I'm filling this bug just to let you know about that for educational purposes :) also maybe someone will search for issues and find this helpful 🙌

**Comment by tberk** [comment]
Yeah I am having this issue after 3.12 too. My route names are defined in pages but they are read as `undefined`.

```
definePageMeta({
  name: 'wallet-items',
})
```

**Comment by xjccc** [comment]
@tberk I think your problem like this. https://github.com/nuxt/nuxt/issues/28436
