### ISSUE TITLE
"Docs: Nuxt config responsiveness is broken."

### ISSUE THREAD

**Issue by moshetanzer** [nuxt/nuxt#27844]
**Summary (generated)**:

This is a bug report about a line of code in the Nuxt documentation that breaks the reactivity of the Nuxt config page in the API section. The issue is related to the "unhead" module and its installation options. A screenshot is provided to illustrate the problem.

<hr>

### Environment

nuxt.com

### Reproduction

https://nuxt.com/docs/api/nuxt-config#unhead

### Describe the bug

Hi,

This line seems to break reactivity of the nuxt config page in api section in docs:
See: https://unhead.unjs.io/setup/ssr/installation#optionsExample:

here is pic 

<img width="425" alt="Screenshot 2024-06-26 at 15 48 09" src="https://github.com/nuxt/nuxt/assets/82201261/fefb486f-9355-4110-acfc-b620f90ffdc6">

**Comment by manniL** [comment]
@moshetanzer seems like a straightforward fix! PR welcome
