### ISSUE TITLE
nuxtlink or navigateto forces client side request instead of SSR

### ISSUE THREAD

**Issue by settery** [nuxt/nuxt#27840]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.12.2
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  yarn@1.22.21
- Builder:          -
- User Config:      devtools, css, postcss, modules, runtimeConfig
- Runtime Modules:  @pinia/nuxt@0.5.1, @pinia-plugin-persistedstate/nuxt@1.2.0, @nuxt/image@1.7.0
- Build Modules:    -
------------------------------

### Reproduction

// profile/index.vue

```vue
const { $api } = useNuxtApp();
const authStore = useAuthStore();

const { data, error, status } = await useAsyncData(() =>
	$api
		.get<{ status: string; user: User }>('/user/me', {
			headers: {
				Authorization: `Bearer ${authStore.token}`,
			},
		})
		.then(res => res.data)
);
```

// components/navbar.vue

```vue
<script lang="ts" setup>
import { useAuthStore } from '~/store/auth.store';
import type { User } from '~/types/user';

const { $api } = useNuxtApp();
const authStore = useAuthStore();

const { data, error, status } = await useAsyncData(() =>
	$api.get<{ status: string; user: User }>('/user/me').then(res => res.data)
);
</script>
<template>
	<nav
		class="fixed top-0 left-0 flex justify-end items-center w-screen px-5 py-3"
	>
		<div
			v-if="authStore.isAuth && data?.user"
			class="text-sm border px-2 py-1 rounded-full bg-zinc-50 hover:bg-zinc-200"
		>
			<NuxtLink to="/profile">{{ data.user.id }}</NuxtLink>
		</div>
	</nav>
</template>
```

### Describe the bug

Using `<NuxtLink to="/profile">` forces requests on the passed page to be client-side. I understand why this happens, NuxtLink prefetching pages and moves user to the page without reloading html. But how to prevent this? With navigateTo method I fixed this with using router.replace and window.location.reload(), but it seems to be not the right way.

**Comment by danielroe** [comment]
You can pass the `external` prop to force a hard reload, though note this will probably lead to a worse UX.

**Comment by settery** [comment]
> You can pass the `external` prop to force a hard reload, though note this will probably lead to a worse UX.

then there's no correct way to prevent page do client requests when they should be server side?

**Comment by settery** [comment]
i think it sounds insecure. like, what if i pass secret api key which only server should use? creating nuxt api layer to proxy sounds not that good if not every route requires this type of key.

**Comment by settery** [comment]
> You can pass the `external` prop to force a hard reload, though note this will probably lead to a worse UX.

and it doesn't work !) 

```ts
const handlePayment = async () => {
	// TODO: handle payment
	return navigateTo('/delivery/' + offerId, {
		external: true,
	});
};
```

still client requests on the navigated page, and even when i move in history like clicking back and forward buttons in browser i see client requests. would be cool to see some info on nuxt docs about this type of simple tasks, how to make it correct way how nuxt devs would do it.

**Comment by danielroe** [comment]
Please provide a reproduction if it doesn't work.

I would recommend you consider server components or create a BFF using Nitro server routes.

**Comment by AdrianFahrbach** [comment]
So the only ways to solve this are:
1. External links everywhere (basically not using `NuxtLink`)
2. Wrapping server side api requests into a server component
3. BFF Nitro server routes

@danielroe Do you have improvements for this planned in the future? I would definitely prefer an option to force `useAsyncData` to only run on the server.

Could you also elaborate on the BFF Nitro server route approach a bit? My guess is that the solution there would be to create an internal API route that caches the data fetched from external sources, but still gets called on the client.

**Comment by danielroe** [comment]
@AdrianFahrbach You can also set `payloadExtraction` to true to ensure `useAsyncData` only runs on the server for all routes.

**Comment by AdrianFahrbach** [comment]
> @AdrianFahrbach You can also set `experimental.payloadExtraction` to true to ensure `useAsyncData` only runs on the server for all routes.

@danielroe Unfortunately this doesn't work with ISR or SWR, since I can't pre-generate the  pages there, right?

As far as I know I therefore can't fetch data server side only when using ISR or SWR unless I am using server components with `experimental.componentIslands.selectiveClient`. So in turn I have to do all my server-side API requests in separate server components which I wrap around my actual components?

Are there any plans on changing this? The current solution feels a bit complex to me. I would prefer to just pass a prop to `useAsyncData` to make it run on the server only.

**Comment by sudomuli** [comment]
Let me be clear, so i can not force only ssr when navigating via `<NuxtLink>`...?
What is the solution when using `server/api/**` routes to avoid exposing for example `/api/article/[slug].ts` to the whole internet?
And even though you can do CORS, i want no plain JSON objects in the network tab...
