### ISSUE TITLE
Nuxt Image Auto-install with Nuxt Content forces installation even when module is not used

### ISSUE THREAD

**Issue by sebaguse** [nuxt/nuxt#27854]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.15.0
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  npm@10.7.0
- Builder:          -
- User Config:      app, runtimeConfig, $development, css, modules, quasar, pinia, imports, vite, content, vue, nitro, devtools, devServer, ssr, build, alias, piniaPersistedstate
- Runtime Modules:  nuxt-quasar-ui@2.1.3, @pinia/nuxt@0.5.1, @vueuse/nuxt@10.11.0, @pinia-plugin-persistedstate/nuxt@1.2.1, @nuxt/content@2.13.0, @formkit/auto-animate/nuxt@0.8.2
- Build Modules:    -

### Reproduction

* create new project
* add @nuxt/content module
* add in `nuxt.config.ts`: 
```  runtimeConfig: {
    public: {
      mdc: {
        useNuxtImage: false,
      },
    },
  }
```
* create a content page with image i.e. `![My Image](/img/my-image.jpg)`
* due to the logic in ProseImg.vue (`const imgComponent = useRuntimeConfig().public.mdc.useNuxtImage ? resolveComponent('NuxtImg') : 'img'`), Nuxt MDC would use standard `img` tag for images, not NuxtImg
* press Ctrl+C to stop dev server
* NuxtImage will be auto-installed

### Describe the bug

NuxtImage is auto-installed despite MDC being forced to use standard `img` tag via flag in nuxt.config, so technically I'm not using `@nuxt/image` but I get this installed which makes build much bigger than without `@nuxt/image`

### Additional context

NuxtImg is optionally used by ProseImg.vue in Nuxt MDC, if I change this line:
```
const imgComponent = useRuntimeConfig().public.mdc.useNuxtImage ? resolveComponent('NuxtImg') : 'img'
```

to 
```
const imgComponent = 'img'
```
@nuxt/image wouldn't be auto-installed

### Logs

```shell-script
i Vite client warmed up in 7416ms                                                                             09:04:18
√ Nuxt Nitro server built in 8346 ms                                                                    nitro 09:04:21
i Package @nuxt/image is missing                                                                              09:05:02

x Do you want to install @nuxt/image package?
Yes

i Installing @nuxt/image...                                                                                   09:05:25
i Installing @nuxt/image@latest development dependency                                                        09:05:26

added 46 packages, and audited 1031 packages in 12s

246 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
i Updating nuxt.config.ts                                                                                     09:05:39
i Adding @nuxt/image to the modules                                                                           09:05:39
√ nuxt.config.ts updated                                                                                      09:05:39
√ Installed @nuxt/image                                                                                       09:05:39
i nuxt.config.ts updated. Restarting Nuxt...
```

**Comment by danielroe** [comment]
Would you open an issue on nuxt-modules/mdc? 🙏

**Comment by brettsprads** [comment]
Can we re-open this please? 
This is still an issue - and in my Nuxt add I don't have a need for the Nuxt Image package, but it insists...
I also don't think this has anything to do with "nuxt-modules/mdc" as I'm not using that package either.

<img width="735" alt="image" src="https://github.com/nuxt/nuxt/assets/157126564/a5be97d1-1e62-4671-9955-7f0d53558e64">

**Comment by sebaguse** [comment]
Two weeks ago I created an issue for MDC as suggested by @danielroe but nobody replied yet, perhaps you're using another module that has similar issue to MDC? My solution so far is just let `nuxt/image` get installed and then comment it out in `nuxt.config`.
