### ISSUE TITLE
`error.value` is undefined in composable when using `useAsyncData` on client

### ISSUE THREAD

**Issue by MikeBellika** [nuxt/nuxt#27855]
### Environment

- Operating System: `Darwin`
- Node Version:     `v22.1.0`
- Nuxt Version:     `3.12.2`
- CLI Version:      `3.12.0`
- Nitro Version:    `2.9.6`
- Package Manager:  `pnpm@9.1.1`
- Builder:          `-`
- User Config:      `devtools`, `modules`
- Runtime Modules:  `@nuxt/eslint@0.3.13`
- Build Modules:    `-`

### Reproduction

Github: https://github.com/MikeBellika/Async-data-error-reproduction
Stackblitz: https://stackblitz.com/~/github.com/MikeBellika/Async-data-error-reproduction

After running the project, head to `/client` and `/server`. On `/client`, the error is blank, while it is `This is a human readable error` on `/server`.

### Describe the bug

We wrap `useAsyncData` in another function, to provide error handling. The function looks something like this:
```typescript
  async function myAsyncData<T>(...args: AsyncArgs<T>) {
    const { error, ...rest } = await useAsyncData<T>(...args);
    return { error: humanReadableError(error.value), ...rest };
  }
```
However when we run this on the client, for example with `{server: false}`, `error.value` is null. If we just do `return {error, ...rest }`, we can get the error from the template.

**Comment by manniL** [comment]
You [lose reactivity](https://www.youtube.com/watch?v=sccsXulqMX8) when using `humanReadableError(error.value)`

**Comment by MikeBellika** [comment]
> You [lose reactivity](https://www.youtube.com/watch?v=sccsXulqMX8) when using `humanReadableError(error.value)`

@manniL Thank you for the quick reply and great video!

Are you sure that it's the loss of reactivity that causes this issue? I don't need error to be reactive.
Also is it expected that this behaves differently on server and client side?

**Comment by manniL** [comment]
> @manniL Thank you for the quick reply and great video!

Glad you liked it 🙏🏻

> Are you sure that it's the loss of reactivity that causes this issue? I don't need error to be reactive. Also is it expected that this behaves differently on server and client side?

Yes, it should be. Because the request is executed on the client when `server: false`, the data and error values are `null` first and will be populated when the request was processed.

**Comment by MikeBellika** [comment]
> > @manniL Thank you for the quick reply and great video!
> 
> Glad you liked it 🙏🏻
> 
> > Are you sure that it's the loss of reactivity that causes this issue? I don't need error to be reactive. Also is it expected that this behaves differently on server and client side?
> 
> Yes, it should be. Because the request is executed on the client when `server: false`, the data and error values are `null` first and will be populated when the request was processed.

I see. So the right thing to do is to wrap it in `computed`?

**Comment by manniL** [comment]
Exactly 👍🏻 (then your function can work with the "value only" and the computed can return the human readable error
