### ISSUE TITLE
I'm here to help.

### ISSUE THREAD

**Issue by saturn4er** [nuxt/nuxt#27850]
**Summary (generated)**:

Here is a brief summary in English:

The bug occurs when using NuxtLink with setup provided, causing the page to fully reload on navigation between different pages.

<hr>

### Environment

Any

### Reproduction

https://stackblitz.com/edit/github-e5yfeu-vqz5gn?file=app.vue

### Describe the bug

For some reason in setup I provided page fully reloads on navigation between different pages using NuxtLink.

**Comment by huang-julien** [comment]
Hello something seems to be wrong within your store's methods. It calls composables within async functions and `initDataRefreshesPage` is blocking the setup of the component client side
