### ISSUE TITLE
Auto-imported `ref`s are unwrapped to a left-hand side expression in `<template>`

### ISSUE THREAD

**Issue by typed-sigterm** [nuxt/nuxt#27868]
### Environment

```
- Operating System: Windows_NT
- Node Version:     v20.10.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  pnpm@9.1.0
- Builder:          -
- User Config:      ssr, modules, app, imports, runtimeConfig, vite, spaLoadingTemplate, devServer
- Runtime Modules:  @bg-dev/nuxt-naiveui@1.13.0, @pinia/nuxt@0.5.1, @unocss/nuxt@0.59.4, @vueuse/nuxt@10.9.0, unplugin-icons/nuxt
- Build Modules:    -
```

(seems not related)

### Reproduction

https://stackblitz.com/edit/nuxt-demo-789b7ff?file=app.vue

### Describe the bug

Auto-imported `ref`s are unwrapped to a **left-hand side expression** in `<template>`.

### Logs

```shell-script
Uncaught SyntaxError: Invalid left-hand side expression in prefix operation
```

**Comment by danielroe** [comment]
I would not expect this would work. Only things defined in script setup are unwrapped in template.

Can you explain a bit more about your use case?

**Comment by typed-sigterm** [comment]
> Can you explain a bit more about your use case?

Sharing state across components - just a `boolean` to show/hide a modal, it seems unnecessary to create a Pinia store for this.

(I know this is not a good practice, but the conditions for not unwrapping `ref`s seem not to be mentioned anywhere (if this point is documented somewhere, please remind me))

**Comment by danielroe** [comment]
We mention this in the context of plugins but could add a note in the auto imports docs as well.

https://github.com/nuxt/nuxt/blob/356173134280b66c5902e5129d2f5ee73b799352/docs/2.guide/2.directory-structure/1.plugins.md?plain=1#L209
