### ISSUE TITLE
Server page is nested in an extra div compared to client page

### ISSUE THREAD

**Issue by RebeccaStevens** [nuxt/nuxt#27877]
### Environment

- Operating System: Linux
- Node Version:     v20.14.0
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  pnpm@9.4.0
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://codesandbox.io/p/devbox/falling-https-pw2gmk?file=%2Flayouts%2Fdefault.vue%3A6%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxy585qz00052v6hjyg8tt5k%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxy585qz00022v6h3batydsk%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxy585qz00032v6h0krexa9s%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxy585qz00042v6hfwaov04n%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxy585qz00022v6h3batydsk%2522%253A%257B%2522id%2522%253A%2522clxy585qz00022v6h3batydsk%2522%252C%2522activeTabId%2522%253A%2522clxy5nfse00022v6iyfdihnmk%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxy585qz00012v6he4fma5f8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clxy5f40a00gs2v6h4ujpclfe%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxy5nfse00022v6iyfdihnmk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A6%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A6%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Flayouts%252Fdefault.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clxy585qz00042v6hfwaov04n%2522%253A%257B%2522id%2522%253A%2522clxy585qz00042v6hfwaov04n%2522%252C%2522activeTabId%2522%253A%2522clxy5bq4300f32v6h3o1l3cf8%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A3000%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clxy5bq4300f32v6h3o1l3cf8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clxy585qz00032v6h0krexa9s%2522%253A%257B%2522id%2522%253A%2522clxy585qz00032v6h0krexa9s%2522%252C%2522activeTabId%2522%253A%2522clxy5mfgh00u12v6hgwztb14u%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clxy5mfgh00u12v6hgwztb14u%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Describe the bug

With the following page template:

```vue
<template>
  <main>...</main>
</template>
```

It will be rendered as this when using the `.vue` extension:

```html
<main>...</main>
```

But will be rendered like this when using `.server.vue`:

```html
<div>
  <main>...</main>
</div>
```

This change breaks my page styles. Is there anyway to remove that outer div? or at least be able to add a class to it?

**Comment by huang-julien** [comment]
Hello :wave: this is intended as NuxtPage needs a root element (islands renders a fragment). The div is only to make transition to working properly

**Comment by siaikin** [comment]
@huang-julien I'm having a similar problem, the only difference with this issue is that I'm using `*.client.vue` as the filename.Again rendering in the browser is wrapped in redundant ` <div>`.

I don't think this is normal, even though as you say "The div is only to make transition to working properly", the redundant ` <div>` should be removed when the transition is complete.However it is not.

Can you please explain why it is closed?Or am I misunderstanding?

**Comment by huang-julien** [comment]
The issue with adding then removing the redundant div is that you'll have a flash of broken css if you targeting the root dir of the island component. Also, re-rendering the whole tree can be costly performance wise
