### ISSUE TITLE
Nuxt `builder:prepared` hook

### ISSUE THREAD

**Issue by tmg0** [nuxt/nuxt#27875]
### Describe the feature

Recently, There is a new bundler based on rust called [Farm](https://www.farmfe.org/), and I wanna try to create a module for using it in Nuxt to replace Vite.

I referred to the `nuxt-vite` repository for nuxt2, which seems to use the `builder:prepared` hook to replace the `bundleBuilder`. But this hook is not yet implemented in Nuxt 3 and is marked as TODO in the source code.

I noticed that `nuxt.options.builder` supports a  param that implement the `NuxtBuilder` interface, but I couldn’t find a suitable hook to replace it in the [Lifecycle Hooks](https://github.com/nuxt/nuxt/blob/main/packages/schema/src/types/hooks.ts#L53). Are there any other ways to replace Vite as the bundler? 

An answer would be greatly appreciated.

### Additional information

- [x] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
We support pluggable bundles in Nuxt. That is how webpack and vite builders are currently implemented. To the Nuxt `builder` option you can can provide any file or npm library that exposes a bundle function. (Or directly inline it.)

Here's how the vite bundler does it: https://github.com/nuxt/nuxt/blob/main/packages/vite/src/vite.ts#L31

**Comment by tmg0** [comment]
Thank you very much for your answer, It solved my question perfectly

Hope the `Nuxt` community all the best!

**Comment by danielroe** [comment]
Wonderful! And i look forward to seeing your work, if you open source it 🙏
