### ISSUE TITLE
in Nuxt3.11.2,How to solve the issue where data fetched using useFetch isn’t requested again after refreshing the page?

### ISSUE THREAD

**Issue by zsk-coder** [nuxt/nuxt#27886]
### Environment

- Operating System: Windows10
- Node Version: v18.16.1
- Nuxt Version: 3.11.2
- Package Manager: npm@9.5.1

### Reproduction

https://stackblitz.com/edit/github-xsxgjf?file=app.vue

### Describe the bug

After entering the page and completing the request, refreshing the page will not re-issue the request. My demand is to obtain the server data in real time, so I do not want to go to the cache. I have tried to add a time stamp as the key in the request, but my demand is still not met, please help me solve it, thank you very much

### Additional context

*No response*

### Logs

*No response*

**Comment by metkm** [comment]
- useFetch shouldn't be used inside functions. Put it in top level.
- It makes a request but because It's server-side rendered. It's normal that you don't see the request in the devtools if that's where you got confused.

https://nuxt.com/docs/getting-started/data-fetching

**Comment by danielroe** [comment]
Just to add, if you are using static generation with `nuxi generate` then requests will be made and inlined at generate time - to avoid this behaviour you can set `server: false` in your useAsyncData or useFetch options to force data to be fetched on client side.
