### ISSUE TITLE
useRoute() inside $fetch interseptors

### ISSUE THREAD

**Issue by localusercamp** [nuxt/nuxt#27887]
### Environment

- Operating System: Linux
- Node Version:     v20.10.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

There is no need in reproduction

### Describe the bug

Currently `useRoute()` called inside `$fetch` interseptors return empty object in server context.
Because of this there is no way to know on which page user was when he got error from response and limits interseptors a lot.
For example with i18n nuxt module i want interseptor `onRequest` to set request header `'Accept-Language'` accordingly to prefix in my route, but i can not do that because interseptors knows nothing about the route.

```ts
// Works fine in both SSR and Client
useAsyncData('foo', async () => {
    const route = useRoute();
    return $fetch('http://api.site.com/some/route', {
        onRequest({ options }) {
            const locale = getLocaleFromRoute(route);
            options.headers['Accept-Language'] = locale;
        }
    });
});
```

```ts
// Does not work in SSR
useFetch('http://api.site.com/some/route', {
    onRequest({ options }) {
        const route = useRoute();
        const locale = getLocaleFromRoute(route);
        options.headers['Accept-Language'] = locale;
    }
});
```

Any plans to support route object in interseptors?
Is there any woraround for this?

**Comment by danielroe** [comment]
Composables that rely on the Nuxt instance should not be called in interceptors. Ideally they should be called outside at the top level of a component or plugin. If they are called in the interceptor they should be called with nuxtApp.runWithContext.
