### ISSUE TITLE
WARN  [nuxt] Expected @nuxt/schema to be at least 3.12.2 but got 3.11.2

### ISSUE THREAD

**Issue by Ibochkarev** [nuxt/nuxt#27881]
### Environment

```
Nuxt project info: (copied to clipboard)                                                                                                                                         12:34:33 PM

------------------------------
- Operating System: Darwin
- Node Version:     v20.14.0
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  pnpm@9.4.0
- Builder:          -
- User Config:      ssr, app, telemetry, experimental, build, modules, dir, components, vueuse, runtimeConfig, css, vite, nitro, routeRules, typescript, hooks, devtools, testUtils, imports
- Runtime Modules:  @nuxt/test-utils/module@3.13.1, @vueuse/nuxt@10.11.0, @pinia/nuxt@0.5.1, @pinia-plugin-persistedstate/nuxt@1.2.1, @nuxt/devtools@1.3.6, @/modules/iconica, @/modules/fontagon, nuxt-typed-router@3.6.4, nuxt-viewport@2.1.5
- Build Modules:    -
------------------------------
```

### Reproduction

NA

### Describe the bug

After updating to 3.12.2 `npx nuxi@latest upgrade --force` i get

`WARN [nuxt] Expected @nuxt/schema to be at least 3.12.2 but got 3.11.2. This might lead to unexpected behavior. Check your package.json or refresh your lockfile.              12:31:14 PM`

**Comment by Ibochkarev** [comment]
@ronenteva we are not using the specified file

**Comment by ronenteva** [comment]
Try adding it and reinstall dependencies, see if it solves the issue

**Comment by popadicbranislav** [comment]
I am getting the same error message, and I am using `.npmrc` with `shamefully-hoist=true`. The warn message suggests to remove the lock file. I did that, but it didn't help.

**Comment by MuhammadM1998** [comment]
Deduping your lockfile might solve the issue. Run `pnpm dedupe`

**Comment by junogueira** [comment]
I'm having the same issue, here's a minimal version of my project: [https://codesandbox.io/p/devbox/blue-violet-gkyh7w](https://codesandbox.io/p/devbox/blue-violet-gkyh7w).

```
------------------------------
- Operating System: Darwin
- Node Version:     v20.12.2
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  pnpm@9.1.1
- Builder:          -
- User Config:      colorMode, devtools, modules, runtimeConfig, ssr, ui
- Runtime Modules:  @nuxt/eslint@0.3.13, @nuxt/fonts@0.6.1, @nuxt/image@1.7.0, @nuxt/ui@2.17.0, @vueuse/nuxt@10.11.0, nuxt-typed-router@3.6.5
- Build Modules:    -
------------------------------
```

**Comment by popadicbranislav** [comment]
> Deduping your lockfile might solve the issue. Run `pnpm dedupe`

Running `pnpm dedupe` worked for me. Thanks for the tip.

**Comment by danielroe** [comment]
This sounds like the warning is working as expected. We might add a CLI tool to automatically resolve things like this in future: https://github.com/nuxt/cli/issues/330.

**Comment by junogueira** [comment]
`pnpm dedupe` didn't change anything for me.

**Comment by dargmuesli** [comment]
@Ibochkarev **your** project's version isn't `3.11.2` by any chance? Because @junogueira's reproduction shows the user project's version to be mentioned in the error, which very much looks like a bug. I also see this happening in some of my projects, e.g. `Expected @nuxt/schema to be at least 3.12.2 but got 1.21.15.` when my project's version is `1.21.15`. @danielroe should this issue be reopened to track this or should a new one be created? The reproduction by @junogueira works.

**Comment by Ibochkarev** [comment]
> @Ibochkarev **your** project's version isn't `3.11.2` by any chance? Because @junogueira's reproduction shows the user project's version to be mentioned in the error, which very much looks like a bug. I also see this happening in some of my projects, e.g. `Expected @nuxt/schema to be at least 3.12.2 but got 1.21.15.` when my project's version is `1.21.15`. @danielroe should this issue be reopened to track this or should a new one be created? The reproduction by @junogueira works.

![image](https://github.com/nuxt/nuxt/assets/2138260/f09f9ddb-c26a-49bb-8b52-c9dab33174af)

**Comment by danielroe** [comment]
You can also explicitly add a dependency of the correct version.

**Comment by HELWATANY** [comment]
Using `.npmrc` with `shamefully-hoist=true` then running `pnpm dedupe` solved the issue for me

**Comment by jumptrnr** [comment]
> You can also explicitly add a dependency of the correct version.

WARN  [nuxt] Expected @nuxt/kit to be at least 3.12.4 but got 3.8.2. This might lead to unexpected behavior. Check your package.json or refresh your lockfile.

Using yarn 4.3.1 - added both to dependencies ^3.12.4 and still get this warning. Nothing in my lockfile says 3.8.2

**Comment by katerlouis** [comment]
I've removed my package_lock.json and node_modules folder; a clean install still posts these warnings. 

`$ npm run generate` runs into problems and this is cryptic to me that I have no other way to start than getting rid of those errors. I'm not using nuxt-kit, nor nuxt-schema, so I'd rather not install them explicitly with the "correct version"

![image](https://github.com/user-attachments/assets/60ad166d-cc58-4f70-9107-7abda0e3bcee)

**Comment by kurt-grung** [comment]
I have the same issue: 

`.npmrc` & ` shamefully-hoist=true` + `  pnpm dedupe`   doesn’t solve the warnings.

**Comment by Besufikad17** [comment]
> I have the same issue:
> 
> `.npmrc` & ` shamefully-hoist=true` + `  pnpm dedupe`   doesn’t solve the warnings.

running `npx nuxi upgrade` worked for me

**Comment by kurt-grung** [comment]
Tried running `px nuxi upgrade` but still says the same issue - 

```
ℹ Package manager: npm 10.9.0                                                                                                                                            
ℹ Current Nuxt version: 3.13.2                                                                                                                                           

✔ Would you like to recreate node_modules and package-lock.json to fix problems with hoisted dependency versions and ensure you have the most up-to-date dependencies?
Yes
ℹ Recreating node_modules and package-lock.json. If you encounter any issues, revert the changes and try with --no-force        
ℹ Installing latest stable Nuxt 3 release...                                                                                                                             
npm warn idealTree Removing dependencies.@nuxt/kit in favor of devDependencies.@nuxt/kit
npm warn idealTree Removing dependencies.@nuxt/schema in favor of devDependencies.@nuxt/schema
.....
added packages, and audited packages in 54s

found 0 vulnerabilities
ℹ Cleaning up generated Nuxt files and caches...                                                                                                                         
ℹ Upgraded Nuxt version: 3.14.159                                                                                                                                        
✔ Successfully upgraded Nuxt from 3.13.2 to 3.14.159                                                                                                                     
ℹ Changelog: https://github.com/nuxt/nuxt/compare/v3.13.2...v3.14.159 
```

`nuxi dev`

```
 WARN  [nuxt] Expected @nuxt/kit to be at least 3.14.159 but got 3.12.2. This might lead to unexpected behavior. Check your package.json or refresh your lockfile. 

 WARN  [nuxt] Expected @nuxt/schema to be at least 3.14.159 but got 3.12.2. This might lead to unexpected behavior. Check your package.json or refresh your lockfile.     

```

**Comment by Maakdev** [comment]
Never has that and voila

> Expected @nuxt/kit to be at least 3.15.4 but got 3.15.3.
