### ISSUE TITLE
useCookie navigateTo new page hydration

### ISSUE THREAD

**Issue by marekbuxobucek** [nuxt/nuxt#27908]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-9ukebr-8dmsnx?file=pages%2Findex.vue,pages%2Fnext.vue,composables%2FuseFetchApi.ts

### Describe the bug

On the new page hydration I'm not able to read the cookies value in custom fetchapi composable function.
Simulation context provided below.

### Additional context

On index.vue page I setup cookies. When I navigate to another page by clicking button "Navigate to next page". 
My custom useFetchApi composable is not able to read the cookies when fetching data in setup function.
It is not included in request header. It works on F5 full-page refresh only.

**Comment by fairySusan** [comment]
I meet the same problem. I fixed it like this:
```
const { data, refresh} = await useLazyFetchWrap('/h5/comic/chapter', initData, {
  onRequest({ options }) {
    options.headers['Authorization'] = `Bearer ${tokenCookie.value}`
  }
})
refresh()
```

**Comment by marekbuxobucek** [comment]
> I meet the same problem. I fixed it like this:
> 
> ```
> const { data, refresh} = await useLazyFetchWrap('/h5/comic/chapter', initData, {
>   onRequest({ options }) {
>     options.headers['Authorization'] = `Bearer ${tokenCookie.value}`
>   }
> })
> refresh()
> ```

This is not what i was talking about. I'm missing tokenCookie.value as undefined even i have it defined.

**Comment by s-en-o** [comment]
@marekbuxobucek When navigating to other page can you try using [NuxtLink](https://nuxt.com/docs/api/components/nuxt-link)?

Index page button
```
<NuxtLink :to="'/next'">Navigate to next page</NuxtLink>
```

Next page button
```
<NuxtLink :to="'/'">Navigate to index page</NuxtLink>
```

**Comment by marekbuxobucek** [comment]
> @marekbuxobucek When navigating to another page can you try using [NuxtLink](https://nuxt.com/docs/api/components/nuxt-link)?
> 
> Index page button
> 
> ```
> <NuxtLink :to="'/next'">Navigate to next page</NuxtLink>
> ```
> 
> Next page button
> 
> ```
> <NuxtLink :to="'/'">Navigate to index page</NuxtLink>
> ```

Yes. I have to admit that this approach is working. Thanks for hint.
 But, 
 When I want to do some actions/api calls/operations @click event  before navigation I would like to have possibility to navigate from script because this approach is not suitable in that moment.

**Comment by danielroe** [comment]
I don't think this is a Nuxt issue.

1. Your next page isn't loading because it doesn't have a single root node.
2. When it does, it fails to load because you are accessing `routemw` in your template, but this is not defined on the component.
3. When this is fixed, it can't fetch data from that API due to CORS issues, which is likely why it works fine on hard reload (because CORS rules don't apply on a server).

Updated reproduction: https://stackblitz.com/edit/github-9ukebr-xjyznv

Let me know if you still think there's a bug here.

**Comment by marekbuxobucek** [comment]
@danielroe 
This problem is not presented in stackblitz at all. I don't know why. It appears in local dev build.

I created a [https://www.loom.com/share/e6969e892da54d4f9f1ac5a42a510663?t=21&sid=7980599f-60b3-43d1-ad61-1c784546f357](video) where I start on /sign-in page and  index page is not downloaded to browser yet. I click on submit sign-in what after 2 seconds navigateTo('/') and my index page component is rendered on server with cookie undefined.

Same project what I was using in video is. Where you can see server console log of undefined cookie in local dev build.
 https://stackblitz.com/edit/nuxt-starter-jokjay?file=pages%2Fsign-in.vue,pages%2Findex.vue,server%2Fapi%2Fauth%2Fgx%2Flogin.post.ts
 
 I would like also update project info to my local instead of stackblitz env:
 ------------------------------
- Operating System: Windows_NT
- Node Version:     v20.11.0
- Nuxt Version:     3.12.3
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  yarn@1.22.22
- Builder:          -
- User Config:      compatibilityDate
- Runtime Modules:  -
- Build Modules:    -
------------------------------

**Comment by marekbuxobucek** [comment]
> I don't think this is a Nuxt issue.
> 
> 1. Your next page isn't loading because it doesn't have a single root node.
> 2. When it does, it fails to load because you are accessing `routemw` in your template, but this is not defined on the component.
> 3. When this is fixed, it can't fetch data from that API due to CORS issues, which is likely why it works fine on hard reload (because CORS rules don't apply on a server).
> 
> Updated reproduction: https://stackblitz.com/edit/github-9ukebr-xjyznv
> 
> Let me know if you still think there's a bug here.

https://github.com/nuxt/nuxt/issues/27908#issuecomment-2208593587

**Comment by danielroe** [comment]
Would you check with the latest v3.12.4? 🙏

**Comment by marekbuxobucek** [comment]
> /sign-in page



> Would you check with the latest v3.12.4? 🙏

I appreciate your time.

In the described scenario of [https://github.com/nuxt/nuxt/issues/27908#issuecomment-2208593587](url)

The problem "cookie undefined" on the server persists :-(

- Operating System: Windows_NT
- Node Version:     v20.15.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  yarn@1.22.22
