### ISSUE TITLE
SSR Context Lost

### ISSUE THREAD

**Issue by felixSchl** [nuxt/nuxt#27909]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v21.6.2
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@8.8.0
- Builder:          -
- User Config:      ssr, devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

I created a repo that reproduces the problem here: https://github.com/felixSchl/nuxt-ssr-context-bug. Uncomment this line to see it caching the SSR context as expected: https://github.com/felixSchl/nuxt-ssr-context-bug/blob/3addb782689582efa3155a0f410a837e108658dd/app.vue#L5-L7. Also see the middleware file in the repro https://github.com/felixSchl/nuxt-ssr-context-bug/blob/3addb782689582efa3155a0f410a837e108658dd/server/middleware/setup-context.ts#L1. In a real app I should be able to check if `event.context.message` is already set and then exit early since the work to establish this context has already been done in the initial "real" request.

### Describe the bug

When handling SSR requests it appears that event.context is getting lost when making the call directly on the server. This causes problems because now the middleware in every server-side SSR call needs to re-establish that context which could involve DB calls when validating user sessions, for example.

**Comment by danielroe** [comment]
Would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏

**Comment by felixSchl** [comment]
I'm afraid I won't be able to allocate more time to this because it is not
blocking me and I am tight on time. I found an acceptable workaround after
I understood why this was happening.

**Comment by danielroe** [comment]
Ah, just checked your reproduction more fully. Yes, `useRequestEvent` is the correct solution here.

**Comment by felixSchl** [comment]
Hm, I think there is something off here. Why wouldn't `$fetch` just magically work in pages as it does in middleware? In middleware I do not have to call `useRequestFetch` and `$fetch` just does the right thing automatically. Is this not a fair expectation it should be consistent behaviour if called from pages? Also the documentation makes zero mention of this behaviour and I had to dig deep to find the root cause. I wonder how many pages out there are falling into this. I was using trpc-nuxt which also tripped over this and all trpc requests ran without the initial SSR context, so all users of that library are affected as well. I think this issue has not been resolved.

**Comment by danielroe** [comment]
I think this explains a bit: https://nuxt.com/docs/getting-started/data-fetching#passing-headers-and-cookies

Basically, for security reasons, we require explicit opt in before proxying headers and other details from the initial request via an internal $fetch. In addition, having different behaviour based on where $fetch was called would probably be confusing.
