### ISSUE TITLE
404 error when using navigateTo in a middleware

### ISSUE THREAD

**Issue by ThibaultVlacich** [nuxt/nuxt#27903]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v21.6.2
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  bun@1.1.15
- Builder:          -
- User Config:      telemetry, devtools, typescript, modules, ssr, i18n, app, image, security, pwa, googleFonts, ui, colorMode, vcalendar, css, vite, nitro, runtimeConfig, eslint, tailwindcss      
- Runtime Modules:  nuxt-security@1.4.3, @vite-pwa/nuxt@0.8.1, @nuxtjs/i18n@8.3.1, @nuxt/ui@2.17.0, @nuxtjs/google-fonts@3.2.0, @pinia/nuxt@0.5.1, @nuxt/image@1.7.0, @samk-dev/nuxt-vcalendar@1.0.3,
 @vueuse/nuxt@10.11.0, nuxt-applicationinsights@0.3.4, @nuxt/eslint@0.3.13
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-mz7brn?file=package.json

Run the app, navigate to `/auth/login`, you're automatically redirected to `/fr/auth/login`
Now change the version in package.json to Nuxt 3.12+ (3.12.2 for example), do the same thing and you get a 404 error.

### Describe the bug

After upgrading to Nuxt 3.12, Nuxt throws a 404 error when trying to redirect from a page that doesn't exist in the router using a middleware.
SSR is disabled on some specific routes, through Nitro config, which seems to be the source of the issue.
```
  nitro: {
    routeRules: {
      '/': {
        ssr: false,
      },
      '/**': {
        ssr: false,
      },
    },
  },
```

EDIT: this can even be simplified. Just having `ssr: false` in the Nuxt config causes the issue.

### Logs

> [nuxt] error caught during app initialization Error: Page not found: /auth/login

**Comment by GalacticHypernova** [comment]
Can't seem to reproduce it with 3.12.2
![image](https://github.com/nuxt/nuxt/assets/92037085/013968f5-4704-4ab2-a22a-1601526c2ebb)

![image](https://github.com/nuxt/nuxt/assets/92037085/906c67dc-61d4-4cc0-acb9-786610cd0f7c)

**Comment by ThibaultVlacich** [comment]
> Can't seem to reproduce it with 3.12.2:
> 
> ![image](https://private-user-images.githubusercontent.com/92037085/344431220-013968f5-4704-4ab2-a22a-1601526c2ebb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MDIzNTMsIm5iZiI6MTcxOTcwMjA1MywicGF0aCI6Ii85MjAzNzA4NS8zNDQ0MzEyMjAtMDEzOTY4ZjUtNDcwNC00YWIyLWEyMmEtMTYwMTUyNmMyZWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDIzMDA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NzgxNTI0ZjVhYmUzZjYyZTMwNGM1NWNhYTgxMzE2MGQzYzA0MGJiZTAzOWJmODFiNTg0YmYzZTdhNDY4YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UjIfdJ9YRcA86_i_alHcmMUVgK6aJzT8Uw9MzL4SUrQ)
> 
> ![image](https://private-user-images.githubusercontent.com/92037085/344431235-906c67dc-61d4-4cc0-acb9-786610cd0f7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MDIzNTMsIm5iZiI6MTcxOTcwMjA1MywicGF0aCI6Ii85MjAzNzA4NS8zNDQ0MzEyMzUtOTA2YzY3ZGMtNjFkNC00Y2MwLWFjYjktNzg2NjEwY2QwZjdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDIzMDA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwYTY4NTZlYTE5ZjNlYzI3OTA2NGUyMTA4OWU0OTE1YTVhYjg1ZDE2OGU2OWI0MmUxNjZkZjFiZTQ2YmZhZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F8oaz6k1igHksPauyiXbVsMlMEUctf4KR2SwYblkMTA)
> 
> [stackblitz.com/edit/github-mz7brn-gkhhkt?file=pages%2Findex.vue,middleware%2Fdefault.global.ts](https://stackblitz.com/edit/github-mz7brn-gkhhkt?file=pages%2Findex.vue,middleware%2Fdefault.global.ts)

I see that you've added a link on the home page to reach `/auth/login`
This is indeed working. To reproduce the bug, you need to go directly on `/auth/login` by typing it in the address bar.

![image](https://github.com/nuxt/nuxt/assets/334940/0ba14f92-dff3-442d-9d72-14fde6eb0191)

**Comment by danielroe** [comment]
This is somewhat expected - you only have `~/pages/[lang]/auth/login.vue` and so `/auth/login` is not a valid page.

As a workaround, you can update it to `~/pages/[[lang]]/auth/login.vue` - the `[[` indicates an optional parameter.

This was caused by https://github.com/nuxt/nuxt/pull/27016, which runs middleware _earlier_ in the lifecycle.
