### ISSUE TITLE
When running npm run generate, the script path is incorrect.

### ISSUE THREAD

**Issue by k3341095** [nuxt/nuxt#27918]
### Environment

nuxt3 latest version 
node 20

### Reproduction

none

### Describe the bug

"I have the following configuration in nuxt.config.ts:

app: {
  head: {
    script: ["/neutralino.js"],
  },
}
However, when I build the static site using npm run generate, it generates:

<script>
  /neutralino.js
</script>
Shouldn't it generate the following instead?

<script src="/neutralino.js"></script>

Is there something I'm missing?"

### Logs

```shell-script
<script>
      /neutralino.js
    </script>
```

**Comment by danielroe** [comment]
It should take an object with a src property.
