### ISSUE TITLE
Fail to alter the nuxt config via module

### ISSUE THREAD

**Issue by kingyue737** [nuxt/nuxt#27924]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, ssr
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-drjvtt

### Describe the bug

I'm trying to alter config following https://nuxt.com/docs/guide/going-further/modules#altering-nuxt-configuration

```ts
// app/modules/hello/index.ts
import { defineNuxtModule } from '@nuxt/kit';

export default defineNuxtModule({
  setup(options, nuxt) {
    nuxt.options.experimental.componentIslands = true;
  },
});
```

But the following warning still appears and the server component fails to mount:
```
WARN  Using server components with ssr: false is not supported with auto-detected component islands. If you need to use server component MyComponent, set experimental.componentIslands to true.
```

**Comment by s-en-o** [comment]
@kingyue737 You [also need to set](https://nuxt.com/docs/guide/directory-structure/components#server-components) `experimental.componentIslands` to `true` in `nuxt.config.ts`

```
export default defineNuxtConfig({
 // ... 
 experimental: {
    componentIslands: true
  }
 // ... 
})
```

![image](https://github.com/nuxt/nuxt/assets/4535187/dc4623f7-3ea7-4dfe-84ea-b4d7ba3fae90)

**Comment by kingyue737** [comment]
@s-en-o please read my issue carefully, I want to alter config via Nuxt module, not via `nuxt.config.ts`

**Comment by s-en-o** [comment]
@kingyue737 I see. Is there any specific reason why the `ssr` was set to `false` in your case?

**Comment by kingyue737** [comment]
@s-en-o Im working on a module. I want to guarantee that users can still use the module out of box even if they set `ssr:false` on their side.
