### ISSUE TITLE
Nuxt 3.12 - ssr: false, nuxt generate - 404 on routes after page refresh

### ISSUE THREAD

**Issue by fcieminski** [nuxt/nuxt#27925]
### Environment

Operating System: Windows_NT
- Node Version:     v20.11.1
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  unknown
- Builder:          -
- User Config:      devtools, ssr
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://github.com/fcieminski/nuxt-bug  - here's minimal repo, just run nuxt generate and serve generated output.

### Describe the bug

After visiting any page in the page directory – if you are using my repo, for example after visiting 'test-second', and then hard refreshing the page, you can see in the network tab that there's a 404 error for that page, which causes a lot of Google SEO errors. It's also happening on Netlify and any other static hosting.

![obraz](https://github.com/nuxt/nuxt/assets/45480039/088217f0-5e2a-4385-839f-048e9cc15495)

**Comment by danielroe** [comment]
What is your Netlify deploy/build configuration?
Have you specified a nitro preset?

**Comment by fcieminski** [comment]
> What is your Netlify deploy/build configuration? Have you specified a nitro preset?

I'm not using any specific nitro preset, should I? That issue was not valid in Nuxt 3.8, and as you can see, issue is not netlify related, same thing is happening when serving by node from local machine.

**Comment by danielroe** [comment]
You should use `netlify-static` (but it should be auto-detected) which is why I'm asking.

That configures Netlify to serve 'missing' requests from your `200.html`, which addresses this issue for pages that aren't generated in static sites... The reason the pages aren't generated is tracked in https://github.com/nuxt/nuxt/issues/27828.
