### ISSUE TITLE
feat(kit): add `prepend` option to `addRouteMiddleware`

### ISSUE THREAD

**Issue by trandaison** [nuxt/nuxt#27932]
### Describe the feature

By default, global middleware is executed alphabetically based on the filename. However, not all global middlewares are sorted at the sametime, instead, Nuxt run global middlewares from the `middleware` folder first, then run middleware from moduels. Middlewares from modules have lower order then the ones from `middleware` folder. This is a problem when we want to run a middleware from a module before a global middleware.

For example, we want to run a middleware from a module to check if the user is authenticated before running a global middleware to check if the user has the right permissions.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
We think it would be a good idea to allow passing an option to `addRouteMiddleware` (as [with `addPlugin`](https://github.com/nuxt/nuxt/blob/83f8617e3f506125c2a9882afef4074ee0f1ded9/packages/kit/src/pages.ts#L40-L59)) to allow adding middleware to the beginning of the middleware array rather than the end.

In general I'd advise against strict middleware ordering dependencies.

**Comment by Atinux** [comment]
Code is here: https://github.com/nuxt/nuxt/blob/83f8617e3f506125c2a9882afef4074ee0f1ded9/packages/kit/src/pages.ts#L40-L59

If we want to have the same behavior as `addPlugin`, we need to `unshift()` by default and add the `append` option to `push()`

Suggestion:
```ts
// push() the middleware instead of unshift()
addRouteMiddleware({
      name: 'auth',
      path: resolver.resolve('runtime/auth.ts'),
      global: true
}, { append: true })
```

It makes sense to update the default as module middleware (like plugin) should run before user land middleware.

PR welcome ❤️

**Comment by trandaison** [comment]
thanks! @atinux, @danielroe 

I create an PR for this, please take a look https://github.com/nuxt/nuxt/pull/28496/files
