### ISSUE TITLE
Bug Report: SyntaxError in @vue/devtools-core Module

### ISSUE THREAD

**Issue by frederic117** [nuxt/nuxt#27935]
### Environment

-----------------------------
- Operating System: Windows_NT
- Node Version:     v20.12.0
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  yarn@1.22.22
- Builder:          -
- User Config:      devtools, app, components, modules, booster, image, snackbar, gtag, pwa, ui, runtimeConfig, colorMode, cookieControl, postcss, nitro, vite       
- Runtime Modules:  @nuxt/devtools@1.3.7, @nuxt/ui@2.17.0, @vueuse/nuxt@10.11.0, @vueuse/motion/nuxt@2.2.3, @dargmuesli/nuxt-cookie-control@8.4.2, @nuxtjs/device@3.1.1, @nuxt/image@1.7.0, @pinia/nuxt@0.5.1, @pinia-plugin-persistedstate/nuxt@1.2.1, @vite-pwa/nuxt@0.8.1, nuxt-particles@0.3.0, vue3-carousel-nuxt@1.1.2, nuxt-snackbar@1.0.4, nuxt-gtag@2.0.6, nuxt-booster@3.0.16
- Build Modules:    -

### Reproduction

Set up a new Nuxt3 project.
Add the @vue/devtools module to the project.
Start the development server using npm run dev or yarn dev.
Observe the console for the above error message.

### Describe the bug

  Description
I encountered a SyntaxError when trying to run my Nuxt3 application. The error message indicates that the requested module does not provide an export named isUrlString.

Error Details
SyntaxError: The requested module '/_nuxt/node_modules/@vue/devtools-core/node_modules/@vue/devtools-shared/dist/index.js?v=18ebdbc5' does not provide an export named 'isUrlString' (at index.js?v=18ebdbc5:2172:28)

Expected Behavior
The development server should start without any syntax errors, and the devtools should be functional.

Nuxt3 version:  "3.12.2"

**Comment by danielroe** [comment]
I don't see any issues when I follow the reproduction steps, using pnpm.

**Comment by frederic117** [comment]
sorry for that, i remove all nodes module an make a clean install and i don't see it anymore
