### ISSUE TITLE
definePageMeta doesn't work/ gets ignored

### ISSUE THREAD

**Issue by cxo-jutz** [nuxt/nuxt#27943]
### Environment

```
"nuxt": "^3.10.1",
"vue": "^3.4.21",
```

### Reproduction

Minimal example - here it seems to work as intended tho: https://codesandbox.io/p/sandbox/stoic-star-y6tk4z

In app.vue is simply
```
<template>
    <NuxtLayout>
        <NuxtPage />
    </NuxtLayout>
</template>
```
defined. And in pages is the layout (which is in /layouts (default.vue, test.vue) with definePageMeta
```
<script setup lang="ts">
definePageMeta({
    layout: 'test',
});
</script>
```

### Describe the bug

Only since a few days without any recall of change regarding these files, we noticed that on the checkout and account pages it will always load the default layout now. If we add a console.log right underneath the definePageMeta it shows up, so the file itself etc is the correct, just the right layout isn't applied anymore.We tried updating the packages but even that didn't change the behavior, same with cache and a fresh dev start.
I've also read through https://github.com/nuxt/nuxt/issues/13354 which seemed to be the same bug, but we have the NuxtPage wrapping the NuxtLayout in the app.vue.

Any clues/ ideas on which direction we could debug would be highly appreciated!
![local_nuxt_behavior](https://github.com/nuxt/nuxt/assets/40888663/3630b6bb-a842-4002-93dd-3a77ddcf3978)

**Comment by cxo-jutz** [comment]
I am unsure about the _why_  but at our project it seemed to be fixed by removing the second script tags with
```
<script lang="ts">
export default {
  name: "TestPage",
};
</script>
```

**Comment by cxo-jutz** [comment]
I am unsure about the _why_  but at our project it seemed to be fixed by removing the second script tags with
```
<script lang="ts">
export default {
  name: "TestPage",
};
</script>
```

**Comment by fletcherhaz** [comment]
We have some files which export GraphQL Fragments in the non-setup script tag, so removing it wasn't an option. Thankfully, simply moving `definePageMeta` to the `<script>` tag without `setup` fixed the issue. Might be worth adding a note about that to the documentation, but leaving this here for anyone who finds the issue.

**Comment by fenn1ks** [comment]
i updated nuxt to 3.13.0
Have same problem with definePageMeta

**Comment by danielroe** [comment]
Please open a new issue with a reproduction if you are facing this. Several similar issues have been resolved, which is why this is closed.

**Comment by fletcherhaz** [comment]
#27845 is the duplicate issue being referred to that has the pull request attached. Version 3.13.0 should have the fix in it, I think.
