### ISSUE TITLE
navigateTo in middleware will double encode url on SSR

### ISSUE THREAD

**Issue by rettrich** [nuxt/nuxt#27941]
### Environment

❯ npx nuxi info
Working directory: /home/projects/nuxt-starter-nnndb3
Nuxt project info: 

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-nnndb3?file=package.json

- Go to `/page1` by typing it in the browser or refreshing on `/page1`
- A middleware will trigger a redirect to `/page%20with%20space`
- URL will be double encoded, error page will be shown because `/page%2520with%2520space` was not found

On 3.11.2 this was working without an error, URL was not double encoded

### Describe the bug

On SSR (e.g. after a hard refresh), using `navigateTo` in middleware will encode already encoded URLs, e.g. a redirect to `/page%20with%20space` will result in a redirect to `/page%2520with%2520space`. This is a regression, as in 3.11.2 this behaviour was not present, and `navigateTo("/page%20with%20space")` is working without error

**Comment by danielroe** [comment]
This should be resolved in the [nightly release](https://nuxt.com/docs/guide/going-further/nightly-release-channel#nightly-release-channel), or in the next release.

Let me know if not and I'll reopen.

**Comment by rettrich** [comment]
You're right, the issue is not present in the current nightly

**Comment by jschroeter** [comment]
@danielroe, do you have a rough estimate when the next release including this fix will be published? Thanks!

**Comment by danielroe** [comment]
I’m aiming for today.
