### ISSUE TITLE
When loading the real machine on the mobile terminal in the production environment for the first time, _nuxt/builds/meta/xx.json failed to detch appears. After refreshing the browser, it is normal. Why

### ISSUE THREAD

**Issue by fhqiypmb** [nuxt/nuxt#27942]
### Environment

![image](https://github.com/nuxt/nuxt/assets/130637387/625a9250-b12b-4a7f-82f6-e28c42ae804e)

### Reproduction

When loading the real machine on the mobile terminal in the production environment for the first time, _nuxt/builds/meta/xx.json failed to detch appears. After refreshing the browser, it is normal. Why

### Describe the bug

When loading the real machine on the mobile terminal in the production environment for the first time, _nuxt/builds/meta/xx.json failed to detch appears. After refreshing the browser, it is normal. Why

**Comment by danielroe** [comment]
What version of Nuxt are you on?

**Comment by fhqiypmb** [comment]
> What version of Nuxt are you on?

3.11.2

**Comment by danielroe** [comment]
Should be resolved in v3.12+ via https://github.com/nuxt/nuxt/pull/27441.
