### ISSUE TITLE
Component fails on initial page load, but works after HMR

### ISSUE THREAD

**Issue by frenicohansen** [nuxt/nuxt#27952]
### Environment

- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    -
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  @nuxt/icon@1.0.0, @nuxtjs/tailwindcss@6.12.0
- Build Modules:    -

### Reproduction

https://stackblitz.com/github/frenicohansen/pnd-nuxt

### Describe the bug

I got the following error only on the first page load. 

If I delete the component `<PndList />` from the page and add the component back after the page loaded, then the component will be shown after HMR without any errors.

### Logs

```
 WARN  [Vue Router warn]: uncaught error during route navigation:


 ERROR  Cannot find module './arrayWithHoles.js'
Require stack:
- /home/projects/aonirlxyyr.github/@babel/runtime/helpers/slicedToArray

  Require stack:
  - @babel/runtime/helpers/slicedToArray
  at Module._resolveFilename (https://aonirlxyyrgithub-vypu.w-corp-staticblitz.com/builtins.5bf3667c.js:144:12334)
  at Module._load (https://aonirlxyyrgithub-vypu.w-corp-staticblitz.com/builtins.5bf3667c.js:144:9839)
  at Module.require (https://aonirlxyyrgithub-vypu.w-corp-staticblitz.com/builtins.5bf3667c.js:144:13097)
  at require3 (https://aonirlxyyrgithub-vypu.w-corp-staticblitz.com/builtins.5bf3667c.js:163:2815)
  at eval (@babel/runtime/helpers/slicedToArray:1:207)
  at ViteNodeRunner.runModule (node_modules/.pnpm/vite-node@1.6.0/node_modules/vite-node/dist/client.mjs:379:11)
  at ViteNodeRunner.directRequest (node_modules/.pnpm/vite-node@1.6.0/node_modules/vite-node/dist/client.mjs:363:16)
  at async ViteNodeRunner.cachedRequest (node_modules/.pnpm/vite-node@1.6.0/node_modules/vite-node/dist/client.mjs:206:14)
  at async ViteNodeRunner.dependencyRequest (node_modules/.pnpm/vite-node@1.6.0/node_modules/vite-node/dist/client.mjs:250:12)
  at async eval (node_modules/.pnpm/@atlaskit+pragmatic-drag-and-drop@1.1.12/node_modules/@atlaskit/pragmatic-drag-and-drop/dist/esm/adapter/element-adapter.js:1:216)


 WARN  [nuxt] Failed to stringify dev server logs. Received DevalueError: Cannot stringify arbitrary non-POJOs. You can define your own reducer/reviver for rich types following the instructions in https://nuxt.com/docs/api/composables/use-nuxt-app#payload.
```

**Comment by frenicohansen** [comment]
Working examples using Vue https://github.com/frenicohansen/pdnd-vue

**Comment by frenicohansen** [comment]
Solved by wrapping the component with `<ClientOnly> </ClientOnly>`

I think, this is because pragmatic drag and drop doesn't support SSR.

**Comment by imding** [comment]
So @frenicohansen, what was the thing you did that fixed the issue?

**Comment by frenicohansen** [comment]
> So [@frenicohansen](https://github.com/frenicohansen), what was the thing you did that fixed the issue?

When using Nuxt with SSR (Server-Side Rendering), libraries that rely on browser-specific APIs (like `window` or `document`) can cause errors if they are imported on the server. This happens because Nuxt tries to run the code on the server where no `window` object exists.

Even if you “just import” certain functions without calling them, those libraries may have top-level code that executes immediately upon import — leading to SSR errors.

Some solutions you can try:

1. **Dynamic Import in [`onMounted`](https://vuejs.org/api/composition-api-lifecycle#onmounted)** 
   ```js
   <script setup>
   import { onMounted } from 'vue'

   onMounted(async () => {
     const { testFunction } = await import('test-library')
     // Now use `testFunction` in the browser environment
   })
   </script>
   ```

2. **Client-Only Component**  
   - Convert the component that depends on the library into a [client-only component](https://nuxt.com/docs/guide/directory-structure/components#client-components) by using `.client.vue` suffix in the file's name.
   - Alternatively, wrap the usage in the [`<ClientOnly>`](https://nuxt.com/docs/api/components/client-only) component:
     ```html
     <template>
       <ClientOnly>
         <!-- Your component -->
       </ClientOnly>
     </template>
     ```

3. **Client-Only Plugin**  
   - Create a Nuxt plugin (e.g. `plugins/test-plugin.client.ts`) to import and provide the functions from the library. The `.client.ts` suffix tells Nuxt that it should only be executed on the client.
   - `plugins/test-plugin.client.ts`:
     ```js
     import { testFunction } from 'test-library'

     export default defineNuxtPlugin(() => {
       return {
         provide: {
           testFunction
         }
       }
     })
     ```
   - You can now access `testFunction` in your components via `useNuxtApp().$testFunction`.
