### ISSUE TITLE
How to Assign Specific IDs to JavaScript Files Generated by Nuxt.js Build Process

### ISSUE THREAD

**Issue by CodeCube0** [nuxt/nuxt#27973]
### Describe the feature

Hi everyone,

I need help configuring my Nuxt.js project so that the JavaScript files generated by the build process have specific IDs that I want to set. What configuration should I add to the nuxt.config.ts file to achieve this?

Thank you in advance for your help!

This is an example link that is generated by the build process
`<link rel="prefetch" as="script" crossorigin href="/test/web-addin/nuxt/RA488SzE.js">`

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
You can use a custom `vite.build.rollupOptions.output.chunkFileNames` function.

See https://rollupjs.org/configuration-options/#output-chunkfilenames.

**Comment by CodeCube0** [comment]
> You can use a custom `vite.build.rollupOptions.output.chunkFileNames` function.
> 
> See https://rollupjs.org/configuration-options/#output-chunkfilenames.

Could you tell me where I should insert this function? Should I create a file with that name or should I put it in nuxt.config.ts? Or should I do it another way? @danielroe

**Comment by danielroe** [comment]
You do it like this:

```ts
export default defineNuxtConfig({
  vite: {
    build: {
      rollupOptions: {
        output: {
          chunkFileNames(chunk) {
            // use the chunk details to come up with an id
            return 'someid'
          }
        }
      }
    }
  }
})
```

**Comment by CodeCube0** [comment]
> You do it like this:
> 
> 
> 
> ```ts
> 
> export default defineNuxtConfig({
> 
>   vite: {
> 
>     build: {
> 
>       rollupOptions: {
> 
>         output: {
> 
>           chunkFileNames(chunk) {
> 
>             // use the chunk details to come up with an id
> 
>             return 'someid'
> 
>           }
> 
>         }
> 
>       }
> 
>     }
> 
>   }
> 
> })
> 
> ```

Thank you.
