### ISSUE TITLE
nuxt 3.12.3 stops working registering `.mjs` plugin (Nuxt 3.12.2 works)

### ISSUE THREAD

**Issue by userquin** [nuxt/nuxt#28007]
### Environment

```shell
npx nuxi info
Working directory: C:/temp-working/pwa/vite-pwa-nuxt-issue-146                                                                                         17:55:51
Nuxt project info:                                                                                                                                     17:55:51

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.10.0
- Nuxt Version:     3.12.3
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.4.0
- Builder:          -
- User Config:      compatibilityDate, devtools, typescript, modules
- Runtime Modules:  @vite-pwa/nuxt@0.8.1
- Build Modules:    -
------------------------------
```

### Reproduction

https://stackblitz.com/edit/github-j6cwz8-ft4vdx

Same reproduction can be found in [vite-pwa-nuxt-issue-146](https://github.com/userquin/vite-pwa-nuxt-issue-146) repo and the variant using the new pwa-icon plugin template in the [fix](https://github.com/userquin/vite-pwa-nuxt-issue-146/tree/fix) branch.

### Describe the bug

When Nuxt registers the `pwa-icons.mjs` plugin it breaks any other plugin failing in dev with typecheck enabled or during build (the editor fails to resolve the plugin, it has no types). The same reproduction using previous Nuxt 3.12.2 version works.

If we just add the `.mjs`  extension in `.nuxt/types/plugins.d.ts` it works.

I'm moving the `pwa-icon.mjs`  to plugin template generating the ts file, I have the pwa icon types also generated in `#build/pwa-icons/pwa-icons`:

### Additional context

https://github.com/vite-pwa/nuxt/issues/146

_Error running dev with typecheck enabled_
![imagen](https://github.com/nuxt/nuxt/assets/6311119/7c7a5a8a-cec4-4061-b933-8d8fec0c5ef5)

_Error in build_
![imagen](https://github.com/nuxt/nuxt/assets/6311119/6fef5ca9-a8ad-4f02-8bf4-8cd8a786a841)

**Comment by userquin** [comment]
here SB reproduction for Nuxt 3.12.2 (vue-tsc 1.8.27): https://stackblitz.com/edit/github-1nrcnd?file=nuxt.config.ts

**Comment by userquin** [comment]
Here the same SB reproduction with the plugin template `@vite-pwa/nuxt v0.9.0`: https://stackblitz.com/edit/github-1nrcnd-xmwk42?file=.nuxt%2Fpwa-icons-plugin.ts

**Comment by danielroe** [comment]
The issue here is that this is the contents of your `dist/runtime/plugins/` directory:

```bash
pwa-icons.d.mts
pwa-icons.mjs
pwa.client.d.ts
pwa.client.mjs
types.d.ts
```

TypeScript requires the declaration file to match the file name of the code. So a `.mjs` file requires a `.d.mts` declaration - it should be `pwa.client.d.mts`.

It's not clear to me why this worked previously.
