### ISSUE TITLE
Placing the custom scss file in the 'css' option of 'nuxt.config.ts' will result in an error message: 'Internal server error: [sass] Undefined variable'

### ISSUE THREAD

**Issue by FatNerdPeng** [nuxt/nuxt#28015]
### Environment

node: 20.11.1
nuxt:  3.12.3

### Reproduction

https://stackblitz.com/edit/nuxt-starter-anwoe5

### Describe the bug

Hello team! I have found that there are two places where custom scss files can be configured, namely the `css` option(I named it `Situation 1` here) and `vite [css] [preprocessorOptions] [scss] [additionalData]`(I named it `Situation 2` here) of `nuxt.config.ts` . Now I have discovered an issue with these two places like this:

my code:

`~/assets/css/base.scss`:

```
$linear-color-blue: #03e9f4;
$linear-color-green: #03f40f;
$linear-color-purple: #ab65cc;
$linear-color-red: #e74a4a;
$linear-color-yellow: #eeff00;

body {
  margin: 0;
  padding: 0;
  background-color: black;
  font-size: 20px;
}
```
`~/components/User.vue`:
```
<template>
  <div class="total">hello nuxt</div>
</template>

<style scoped lang="scss">
.total {
  border: 1px solid $linear-color-red;
}
</style>\
```
`~/pages/index.vue`:
```
<template>
  <div>hello world</div>
  <User />
</template>
```
`Situation 2`(use `base.scss` in  `vite [css] [preprocessorOptions] [scss] [additionalData]`):
```
export default defineNuxtConfig({
  app: {
    layoutTransition: { name: 'layout', mode: 'out-in' },
    pageTransition: { name: 'page', mode: 'out-in' },
  },

  // css: ['~/assets/css/base.scss'],

  devtools: { enabled: true },

  vite: {
    css: {
      preprocessorOptions: {
        scss: {
          additionalData: '@use "@/assets/css/base.scss" as *;',
        },
      },
    },
  }
});
```
result:
![image](https://github.com/nuxt/nuxt/assets/33616855/bdad5a50-9003-4053-86a3-526f7f4210ce)
so,why is the `scss variable` effective, but the setting of the `body` is invalid?

Okay, I thought `base.scss` should be placed in `css` option, so:
`Situation 1`(css option):
```
export default defineNuxtConfig({
  app: {
    layoutTransition: { name: 'layout', mode: 'out-in' },
    pageTransition: { name: 'page', mode: 'out-in' },
  },

  css: ['~/assets/css/base.scss'],

  devtools: { enabled: true },
  compatibilityDate: '2024-07-04',
});
```
result:
![image](https://github.com/nuxt/nuxt/assets/33616855/0ef80a0f-a878-4772-afba-ff9367bba747)
terminal:
```
ERROR  Internal server error: [sass] Undefined variable.                                                                                                    11:55:53
  ╷
4 │   border: 1px solid $linear-color-red;
  │                     ^^^^^^^^^^^^^^^^^
  ╵
  components/User.vue 4:21  root stylesheet
  Plugin: vite:css
  File: /home/projects/nuxt-starter-anwoe5/components/User.vue:10:21
  Error: Undefined variable.
    ╷
  4 │   border: 1px solid $linear-color-red;
    │                     ^^^^^^^^^^^^^^^^^
    ╵
    components/User.vue 4:21  root stylesheet
      at Object.wrapException (/home/projects/nuxt-starter-anwoe5/node_modules/.pnpm/sass@1.77.6/node_modules/sass/sass.dart.js:2161:43)
      at eval (/home/projects/nuxt-starter-anwoe5/node_modules/.pnpm/sass@1.77.6/node_modules/sass/sass.dart.js:83775:23)
      at _wrapJsFunctionForAsync_closure.eval (/home/projects/nuxt-starter-anwoe5/node_modules/.pnpm/sass@1.77.6/node_modules/sass/sass.dart.js:4900:15)
      at _wrapJsFunctionForAsync_closure.call$2 (/home/projects/nuxt-starter-anwoe5/node_modules/.pnpm/sass@1.77.6/node_modules/sass/sass.dart.js:35592:12)
      at Object._asyncStartSync (/home/projects/nuxt-starter-anwoe5/node_modules/.pnpm/sass@1.77.6/node_modules/sass/sass.dart.js:4864:20)
      at _EvaluateVisitor2.visitVariableExpression$body$_EvaluateVisitor0 (/home/projects/nuxt-starter-anwoe5/node_modules/.pnpm/sass@1.77.6/node_modules/sass/sass.dart.js:83781:16)
      at _EvaluateVisitor2.visitVariableExpression$1 (/home/projects/nuxt-starter-anwoe5/node_modules/.pnpm/sass@1.77.6/node_modules/sass/sass.dart.js:83755:19)
      at VariableExpression0.accept$1$1 (/home/projects/nuxt-starter-anwoe5/node_modules/.pnpm/sass@1.77.6/node_modules/sass/sass.dart.js:115765:22)
      at VariableExpression0.accept$1 (/home/projects/nuxt-starter-anwoe5/node_modules/.pnpm/sass@1.77.6/node_modules/sass/sass.dart.js:115768:19)
      at _EvaluateVisitor_visitListExpression_closure2.call$1 (/home/projects/nuxt-starter-anwoe5/node_modules/.pnpm/sass@1.77.6/node_modules/sass/sass.dart.js:88981:25) (x2)
```
Okay, so I can't use the scss variable in `scenario 1`? So I changed it this way:
`~/components/User.vue`:
```
<template>
  <div class="total">hello nuxt</div>
</template>

<style scoped lang="scss">
.total {
  border: 1px solid white;
}
</style>
```
result:
![image](https://github.com/nuxt/nuxt/assets/33616855/663d733b-8b6f-4cde-9736-481536abe02c)
It's not reporting an error anymore, but that way I won't be able to use the scss variable.

I don't know if this is a bug, or is the mechanism of `nuxt` designed like this? That means I have to write 2 CSS files, one for writing `styles` and one for defining `scss` variables, and then I have to put these two files separately in the `css` option and `vite [css] [preprocessorOptions] [scss] [additionalData]` options? If it's designed like this, I feel very unfriendly, do you think?
Thanks!

**Comment by danielroe** [comment]
This isn't a bug but I understand it's a pain.

It's documented [here](https://vitejs.dev/config/shared-options.html#css-preprocessoroptions-extension-additionaldata) and it's tricky for us to do automatically as:

> Note that if you include actual styles and not just variables, those styles will be duplicated in the final bundle.

@manniL does maintain this module to make the DX better: https://github.com/nuxt-modules/style-resources.

**Comment by shroomlife** [comment]
I upgraded SASS and got deprecation warnings for @import statements. Now I tried to use @use instead but get full error page.
![Image](https://github.com/user-attachments/assets/4e4c1f33-7a0c-4ed9-9684-60c8281061bc)
