### ISSUE TITLE
run `npx nuxi module add @vueuse/nuxt` and reinstall all node_modules, imports.d.ts  in .nuxt not import @vueuse/core 

### ISSUE THREAD

**Issue by flonny** [nuxt/nuxt#28032]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.11.1
- Nuxt Version:     3.12.3
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.4.0
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  @vueuse/nuxt@10.11.0
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/flonny/nuxt-app

### Describe the bug

```
npx nuxi@latest init nuxt-app
npx nuxi module add @vueuse/nuxt
rm -rf .nuxt
rm -rf node_modules
pnpm i
```

imports.d.ts  in .nuxt not import @vueuse/core

**Comment by danielroe** [comment]
This is just how the module is written it wants you to add `@vueuse/core` as a dependency in your project.

However, it would be worth a PR adding `@vueuse/core` as a `peerDependency` to the module. Then the upcoming version of `nuxi` will auto-install it: see https://github.com/nuxt/cli/pull/442.
