### ISSUE TITLE
[3.12.3] SSG/prerender broke

### ISSUE THREAD

**Issue by NamesMT** [nuxt/nuxt#28037]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.15.0
- Nuxt Version:     3.12.3
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.4.0
- Builder:          -
- User Config:      future, devtools, experimental, devServer, runtimeConfig, ignore, app, components, imports, vue, modules, site, i18n, shadcn, css, primevue, svgo, features, colorMode, eslint, telemetry
- Runtime Modules:  @nuxt/eslint@0.3.13, @unocss/nuxt@0.61.0, @nuxtjs/color-mode@3.4.2, @vueuse/nuxt@10.11.0, nuxt-primevue@3.0.0, shadcn-nuxt@0.10.4, @namesmt/vue-query-nuxt@0.3.3, @nuxtjs/i18n@8.3.1, @nuxtjs/seo@2.0.0-rc.10, nuxt-svgo@4.0.1
- Build Modules:    -
------------------------------

### Reproduction

See https://github.com/nuxt/nuxt/issues/28037#issuecomment-2224553461

### Describe the bug

After upgrading from v3.12.2 to v3.12.3, SSG broke.

### Logs

```shell-script
This is on v3.12.2, SSG still working:

frontend:build: [info] [nitro] Initializing prerenderer
frontend:build: [info] [nitro] Prerendering 5 initial routes with crawler
frontend:build: [log] [nitro]   ├─ /__sitemap__/style.xsl (27ms)
frontend:build: [log] [nitro]   ├─ /robots.txt (35ms)
frontend:build: [log] [nitro]   ├─ /200.html (81ms)
frontend:build: [log] [nitro]   ├─ /404.html (73ms)
frontend:build: [log] [nitro]   ├─ / (3338ms)
frontend:build: [log] [nitro]   ├─ /_payload.json?fe0c5c74-fd78-46a4-b0b9-b52b30f3e1a4 (14ms) (skipped)
frontend:build: [log] [nitro]   ├─ /__nuxt_island/IsSST_heipOnaRLn.json (6ms)
frontend:build: [log] [nitro]   ├─ /_payload.json (3ms)
frontend:build: [log] [nitro]   ├─ /seat (257ms)
frontend:build: [log] [nitro]   ├─ /seat/_payload.json?fe0c5c74-fd78-46a4-b0b9-b52b30f3e1a4 (7ms) (skipped)
frontend:build: [log] [nitro]   ├─ /seat/_payload.json (3ms)
frontend:build: [log] [nitro]   ├─ /favorite (405ms)
frontend:build: [log] [nitro]   ├─ /favorite/_payload.json?fe0c5c74-fd78-46a4-b0b9-b52b30f3e1a4 (5ms) (skipped)
frontend:build: [log] [nitro]   ├─ /favorite/_payload.json (3ms)
frontend:build: [log] [nitro]   ├─ /schedule ([591](https://git.gameloft.org/csd/workspace/-/jobs/7709018#L591)ms)
frontend:build: [log] [nitro]   ├─ /schedule/_payload.json?fe0c5c74-fd78-46a4-b0b9-b52b30f3e1a4 (4ms) (skipped)
frontend:build: [log] [nitro]   ├─ /schedule/_payload.json (3ms)
frontend:build: [log] [nitro]   ├─ /__og-image__/image/og.png (1214ms)
frontend:build: [log] [nitro]   ├─ /sitemap.xml (9ms)
frontend:build: [info] [nitro] Running link inspections...
frontend:build: [log] [nitro]   ├─ / [1 warning]
frontend:build: [log] [nitro]      /
frontend:build: [log] [nitro]         ⚠ Should have descriptive text. (link-text)
frontend:build: [log] [nitro]   ├─ /seat [1 warning]
frontend:build: [log] [nitro]      /
frontend:build: [log] [nitro]         ⚠ Should have descriptive text. (link-text)
frontend:build: [log] [nitro]   └─ /favorite [1 warning]
frontend:build: [log] [nitro]      /
frontend:build: [log] [nitro]         ⚠ Should have descriptive text. (link-text)
frontend:build: [log] [nitro]   ├─ /schedule [1 warning]
frontend:build: [log] [nitro]      /
frontend:build: [log] [nitro]         ⚠ Should have descriptive text. (link-text)
frontend:build: [info] [nitro] Prerendered 15 routes in 32.199 seconds
frontend:build: [success] [nitro] Generated public .output/public
```

This is on v3.12.3, SSG is broken:
```
frontend:build: [info] [nitro] Initializing prerenderer
frontend:build: [info] [nitro] Prerendering 4 initial routes with crawler
frontend:build: [log] [nitro]   ├─ /__sitemap__/style.xsl (17ms)
frontend:build: [log] [nitro]   ├─ /robots.txt (22ms)
frontend:build: [log] [nitro]   ├─ /200.html (48ms)
frontend:build: [log] [nitro]   ├─ /404.html (45ms)
frontend:build: [log] [nitro]   ├─ /sitemap.xml (14ms)
frontend:build: [info] [nitro] Prerendered 5 routes in 35.268 seconds
frontend:build: [success] [nitro] Generated public .output/public
```
```

**Comment by NamesMT** [comment]
Currently using this as workaround:

```ts
export default defineNuxtConfig({
  nitro: {
    prerender: {
      routes: ['/']
    }
  },
})
```

_Originally posted by @danielroe in https://github.com/nuxt/nuxt/issues/27490#issuecomment-2162890462_

**Comment by manniL** [comment]
> * Since 3.12.3, it **works** if you create `pages/index.vue`.
> * However, the default case (`app.vue` alone) still does not work.

> Shortest bug description I can give you is that right now, with 3.12.3, this workflow is broken:

```bash
nuxi create tmp
cd tmp && yarn && yarn generate
```

> It will say "You can now deploy .output/public to any static hosting" but you cannot. I guess that the simplest layout (just `app.vue`, no `pages/` folder) is not supported by the static site generator.

_Originally posted by @teajaymars in https://github.com/nuxt/nuxt/issues/28042#issuecomment-2210635263_

**Comment by NamesMT** [comment]
Hi @manniL, my case seems to be different as I do have `pages/index.vue`,
I'll try to create a reproduction tomorrow, caught in a fever currently.

**Comment by gxres042** [comment]
Here is a case that upgrade from 3.11.x to 3.12.3 will cause this problem.

**Comment by timbenniks** [comment]
I have this one as well. There are no pages rendered in SSG mode. I'm at 3.12.3

**Comment by jason-Impress** [comment]
I'm also experiencing this since updating to 3.12.3
For me the workaround from NamesMT doesn't work. 
The only thing that gives me a working homepage now is disabling SSG by renaming index.vue file to index.client.vue. 
[slug].vue works just fine on the other hand.
Also, reverting to an earlier version of Nuxt doesn't resolve the issue, so assuming the bug might be in a dependency.
Unfortunately there is no helpful error thrown to debug with

**Comment by NamesMT** [comment]
Hi @manniL, @danielroe, hope the tagging doesn't bother you,
Just got out of my flu and did more testing, seems like it could be reproduced with the same procedure in #27490, that is, install `nuxt-seo` with `robots` module turned on.

I have update the repro for this issue (with Nuxt 3.12.3) here: https://github.com/NamesMT/repro-ssg-seo

I could confirm that the SSG generates normally when turning off robots (of course a `pages/index.vue` [also required](https://github.com/nuxt/nuxt/issues/28037#issuecomment-2210754383))
