### ISSUE TITLE
Nonsensical formatting for nuxt.config.ts when accepting suggested compatibilityDate

### ISSUE THREAD

**Issue by minimusubi** [nuxt/nuxt#28038]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.15.0
- Nuxt Version:     3.12.3
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.7.0
- Builder:          -
- User Config:      future, devtools, components
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

1. Run `npx nuxi@latest init --package-manager npm nuxt-config-formatting-repro`.
2. Modify `nuxt.config.ts` to give it more "depth"
3. Run `npm run dev`
4. Accept the suggested compatibilityDate
5. View the newly modified `nuxt.config.ts`

Example repo here: https://github.com/minimusubi/nuxt-config-formatting-repro
A diff of nuxt.config.ts before and after nuxt modifies it: https://github.com/minimusubi/nuxt-config-formatting-repro/compare/e1d42f089e44d42d30a1a0b27ef5c160f69deba2...fb1ae3af952a35e7a4fddac3a5aedaacc8ad2bb0

### Expected outcome
After nuxt modifies `nuxt.config.ts`,

- The file should be formatted similarly to how it was before
- OR, at the very minimum
- The file should be formatted consistently, even if it differs from previous formatting
  - Meaning,
    - If it's going to use spaces, use them. Always. 2 spaces? 4 spaces? It doesn't really matter, as long as it sticks to it.
    - If it's going to use tabs, use them. Don't use both.
    - Indentation should make sense.

Alternatively,

- Don't attempt to format the file

### Actual outcome
Nuxt applies very odd indentation to `nuxt.config.ts`. Note that some lines use a wild number of tabs, and some lines use just a single (!) space.

Example of a nuxt-modified config:
```js
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
 future: {
					compatibilityVersion: 4,
	},

 devtools: { enabled: false },

 // https://nuxt.com/docs/api/nuxt-config#components
	components: [
					{
									path: '~/components/global',
									global: true,
					},
					'~/components',
					// This line is custom
					// https://github.com/nuxt/nuxt/discussions/17167#discussioncomment-3288741
					{ path: '~/components/common', pathPrefix: false },
	],

 compatibilityDate: '2024-07-04',
});
```

### Additional context

With further inspection, it seems that

- Whenever nuxt indents a line using tabs, it seems to (correctly) use a single tab for the first indent level, but then uses 4 tabs per indent level for each level after.
- Whenever it used spaces, it only used one space.

Maybe, it used spaces where it should have used tabs, and tabs where it should have used spaces?
This analysis was only conducted with the example config given. I didn't explore adding more config options.

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/28021.

These are upstream issues in `magicast` or its dependencies (which are also relevant for installing modules) but we might decide not to prompt to update your config by default.
