### ISSUE TITLE
[useNuxtApp] Non-reactive code is reactive

### ISSUE THREAD

**Issue by szulcus** [nuxt/nuxt#28041]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.20.2
- Nuxt Version:     3.6.5
- Nitro Version:    2.9.7
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      extends, app, imports, css, experimental, ssr, modules, vite, runtimeConfig, alias, build, nitro
- Runtime Modules:  @f24/nuxt-module-icons@1.0.2, nuxt-icon@0.2.11, nuxt-typed-router@3.6.5, @pinia/nuxt@0.5.1, @nuxtjs/i18n@8.0.0-beta.10, @nuxt/eslint@0.3.13
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-cjmbdn?file=composables%2FuseDayjs.ts

(can't start this project, but it should work)

### Describe the bug

This code (without watch):
```ts
const { $i18n } = useNuxtApp();
const { localeProperties } = $i18n;
locale(localeProperties.value.dayjsCode);
```

works like this code (with watch):
```ts
const { localeProperties } = useI18n();
watch(localeProperties, (newLocaleProperties) => {
	locale(newLocaleProperties.dayjsCode);
}, { immediate: true });
```

but this code doesn't work (in my opinion correctly):
```ts
const { localeProperties } = useI18n();
locale(localeProperties.value.dayjsCode);
```

**Comment by danielroe** [comment]
I'm not entirely sure of the issue, but this sounds like an upstream issue for https://github.com/nuxt-modules/i18n.

Would you raise an issue there? 🙏
