### ISSUE TITLE
bun cannot initialize a nuxt3 project

### ISSUE THREAD

**Issue by aiyay** [nuxt/nuxt#28061]
### Environment

![image](https://github.com/nuxt/nuxt/assets/27837058/2fa8bfd2-23e4-44c5-a561-a84c4b5e63a1)

### Reproduction

![image](https://github.com/nuxt/nuxt/assets/27837058/06e2f9e5-1555-4896-be52-fa76f8810820)

### Describe the bug

The documentation says to use:
 ``` bunx nuxi@latest init <project-name>```
But there is an error.
Why can I use this to pass
 ``` bun x nuxi@latest init <project-name>```

**Comment by itshizhan** [comment]
This seems to be a problem with Bun.
You can set an alias for `bunx` to be `bun x`.

**Comment by aiyay** [comment]
ok , thanks
