### ISSUE TITLE
Too many requests during development

### ISSUE THREAD

**Issue by wokalek** [nuxt/nuxt#28066]
### Environment

- Operating System: Linux
- Node Version:     v20.15.0
- Nuxt Version:     3.12.3
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.4.0
- Builder:          -
- User Config:      telemetry, devtools, srcDir, app, extends, modules, vite, appConfig, runtimeConfig, css, apollo, tailwindcss, postcss, colorMode, device, mdc, image, pwa, robots, sitemap, site
- Runtime Modules:  @nuxt/eslint@0.3.13, @nuxtjs/apollo@5.0.0-alpha.14, @nuxtjs/tailwindcss@6.12.0, @nuxtjs/robots@3.0.0, @nuxtjs/sitemap@5.3.2, @nuxtjs/color-mode@3.4.2, @nuxtjs/fontaine@0.4.3, @nuxtjs/device@3.1.1, @nuxtjs/mdc@0.8.3, @nuxt/image@1.7.0, @pinia/nuxt@0.5.1, @vueuse/nuxt@10.11.0, @vite-pwa/nuxt@0.9.1, nuxt-typed-router@3.6.5, nuxt-svgo@4.0.1, nuxt-schema-org@3.3.8, nuxt-lodash@2.5.3
- Build Modules:    -

### Reproduction

I checked that with an absolutely clean project, loading the start page takes 8+ seconds (second page reload after start with `pnpm dev`), with 164 requests on the page.

Therefore, my case can be reproduced on any existing project that implements some of its own logic.

![image](https://github.com/nuxt/nuxt/assets/23037847/62df1fa9-0b79-45b5-81b4-8ee65e2fc0c6)

### Describe the bug

During the development of a real project where multiple modules need to be used, when using a dev server, the number of requests can reach an enormous amount due to dependencies.

I know that this can be partially addressed through the config: `vite.optimizeDeps.include`, but honestly, it still doesn't solve the problem, or sometimes it's impossible due to errors.

Because of this problem, page loading in development mode can take a minute or two. With **every** load! This significantly complicates the development and maintenance of Nuxt sites.

My number of requests reaches 500 (in some projects I have even seen 1200), and the waterfall loading of dependencies always makes a limited number of asynchronous requests.

What can be done about this? How is this specifically resolved?

![image](https://github.com/nuxt/nuxt/assets/23037847/7743cdac-290c-4841-a75a-5788ddbf3626)

### Additional context

I think it's worth clarifying. I am developing on a remote machine, which is an Ubuntu server that is connected to my computer via a router. And I connect to it using vscode remote development.
But to be honest, this doesn’t reduce the problem much if I deploy the project locally on the host, it just loads 600 page requests 20-30% faster. But this still remains a problem.

**Comment by danielroe** [comment]
This is how Vite works. Make sure you gave not turned off network caching.

**Comment by wokalek** [comment]
> This is how Vite works. Make sure you gave not turned off network caching.

Yes, that's what I said. I also found this package [antfu/nuxt-better-optimize-deps](https://github.com/antfu/nuxt-better-optimize-deps), which helps a little with the problem.

**Comment by danielroe** [comment]
The defaults set by that module should now be already part of the latest Nuxt release.

**Comment by Barbapapazes** [comment]
This is clearly related to "on a remote machine".

I faced this issue while trying to use Codespace to develop Nuxt app (to many network request and limited to 6 concurrents requests because it's http1.1) but it's clearly more related to Vite, as Daniel said. Other than waiting for a rolldown, I don't think there are any solutions here.
