### ISSUE TITLE
[3.12.3]: router hook onBeforeRouteLeave is stuck

### ISSUE THREAD

**Issue by jenjen75** [nuxt/nuxt#28067]
### Environment

any environment, just enable : 
```
  future: {
    compatibilityVersion: 4,
  }
```

and apply v4 directory structure.

### Reproduction

https://stackblitz.com/edit/github-hjeabw?file=app%2Fpages%2Findex.vue

### Describe the bug

Navigation is stuck in onBeforeRouteLeave.
When calling 3rd argument function `next` it works but it should be optionnal.
Regression from nuxt v3

**Comment by danielroe** [comment]
Is this reproducible without the new folder structure?

**Comment by jenjen75** [comment]
@danielroe thank you for your reply
sadly yes  : https://stackblitz.com/edit/nuxt-starter-sovmp3?file=pages%2Findex.vue

**Comment by hankdetank** [comment]
I would like to add, that it also happens when future is empty. Therefore this is not an future/v4 bug. But also a v3 bug.

This issue came in with v3.12.3 . The issue didnt occur with 3.12.2.

Issue (3.12.3): https://stackblitz.com/edit/github-819pq2-gvrrtm?file=package.json,nuxt.config.ts,pages%2Findex2.vue
no issue (3.12.2): https://stackblitz.com/edit/github-819pq2-pwydxw?file=package.json,nuxt.config.ts,pages%2Findex.vue

**Comment by jenjen75** [comment]
> I would like to add, that it also happens when future is empty. Therefore this is not an future/v4 bug. But also a v3 bug.
> 
> This issue came in with v3.12.3 . The issue didnt occur with 3.12.2.
> 
> Issue (3.12.3): https://stackblitz.com/edit/github-819pq2-gvrrtm?file=package.json,nuxt.config.ts,pages%2Findex2.vue no issue (3.12.2): https://stackblitz.com/edit/github-819pq2-pwydxw?file=package.json,nuxt.config.ts,pages%2Findex.vue
> 
> @jenjen75 Maybe change the title. So its clear this is not only an v4 issue.

**Comment by jenjen75** [comment]
@hankdetank exact, thanks for your details :)

**Comment by hankdetank** [comment]
I just had some time so i was wondering if i could figure out were it goes wrong. 
https://github.com/nuxt/nuxt/commit/77d32cdcec9febb906b80b6dc7b35588421fd3df

`
    // Add vue-router route guard imports
    nuxt.hook('imports:sources', (sources) => {
      const routerImports = sources.find(s => s.from === '#app/composables/router' && s.imports.includes('onBeforeRouteLeave'))
      if (routerImports) {
        routerImports.from = '#vue-router'
      }`

In this commit this part of the code is removed. And logically i would suggest the problem lies here.

**Comment by 20x-dz** [comment]
Can confirm, removing the one instance of `onBeforeRouteLeave` fixes our non-working navigation under 3.12.3.

Importing it manually via `import { onBeforeRouteLeave } from 'vue-router';` fixes the issue as well. I guess the docs need to be updated accordingly?
