### ISSUE TITLE
navigateTo() Server Side

### ISSUE THREAD

**Issue by moshetanzer** [nuxt/nuxt#28076]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v22.2.0
- Nuxt Version:     3.12.3
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.1.2
- Builder:          -
- User Config:      ssr, future, devtools, modules, eslint
- Runtime Modules:  @nuxt/eslint@0.3.13
- Build Modules:    -
------------------------------

### Reproduction

```return navigateTo('/)```

### Describe the bug

Hi,

When i try return navigateTo('/') from within an api - TS shouts "Cannot find name 'navigateTo'. Did you mean 'navigator'?ts(2552)
lib.dom.d.ts(27611, 13): 'navigator' is declared here." and it doesnt work. From docs it seems like it should work out of the box in server and client navigation?

Have i missed something?

**Comment by Barbapapazes** [comment]
I think you should use [`sendRedirect`](https://h3.unjs.io/utils/response#sendredirectevent-location-code).

`navigateTo` is meant to be used within Vue code.

**Comment by moshetanzer** [comment]
@Barbapapazes that was exactly my question! It is answered. @danielroe do you think this should be updated for clarity?

**Comment by danielroe** [comment]
@Barbapapazes is exactly right. Yes, I would welcome a PR improving anything that might be confusing about this 🙏

**Comment by Barbapapazes** [comment]
> From docs it seems like it should work out of the box in server and client navigation?

@moshetanzer could you tell me where in the docs? (with a link?) I will take a look to see how it could be improved.

**Comment by moshetanzer** [comment]
https://nuxt.com/docs/api/utils/navigate-to#:~:text=programmatically%20navigates%20users.-,navigateTo,is%20available%20on%20both%20server%20side%20and%20client%20side.,-Usage

Happy to submit PR just want to know if this is just a misunderstanding on my part - or could do with some added clarification.

**Comment by danielroe** [comment]
It's available on the server part of your Vue app, yes. But not outside the Vue app, in the nitro part of your app.

**Comment by Barbapapazes** [comment]
Indeed, it could be improved by mentioning that 'server side and client side' referred to the Vue application and by adding that on the server, Nitro, `sendRedirect` should be used.
