### ISSUE TITLE
webpack watchRun hooks

### ISSUE THREAD

**Issue by Zackin-He** [nuxt/nuxt#28099]
### Environment

nuxt2

### Reproduction

https://v2.nuxt.com/

### Describe the bug

For the same plugin, watchRun hook has mtimes property in normal webpack projects, but mtimes is undefined in nuxt2. Does nuxt intercept the watcher object?

**My requirements are as follows:** 
When the content of the vue file is updated, it is rebuilt directly, and when the content of other files is updated, it is rebuilt after a delay of 3s
````javascript {
      apply(compiler) {
        compiler.hooks.watchRun.tapAsync('watchRun', (watching, callback) => {
          console.log(watching.watchFileSystem.watcher.mtimes);
          callback();
        });
      }
    }


### Additional context

_No response_

### Logs

_No response_

**Comment by danielroe** [comment]
Nuxt 2 is EOL: https://nuxt.com/blog/nuxt2-eol.
