### ISSUE TITLE
DefinePageMeta overwrites meta properties on NuxtPage objects.

### ISSUE THREAD

**Issue by sykes10** [nuxt/nuxt#28106]
### Environment

Nuxt project info:                                                                                            18:24:11

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.3
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      compatibilityDate, devtools, hooks
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-znsjbh?file=pages%2Ftest.vue

### Describe the bug

Context: The router is being generated by hooks:pages:extends, routes will have the meta property, and those pages will have the definePageMeta methods in them.
Issue: If definePageMeta is present on a vue page the meta property declared in the pages:extend hook will be overwritten instead of merged.
I can see this issue happening since 3.12.0

**Comment by huang-julien** [comment]
Hello :wave: a workaround is to disable `experimental.scanPageMeta` in your config

**Comment by sykes10** [comment]
Thanks for the the quick reply! I can confirm that solves the issue for me.
