### ISSUE TITLE
`useId` hydration mismatch with dynamic and non-dynamic components nested in dynamic component

### ISSUE THREAD

**Issue by codeflorist** [nuxt/nuxt#28105]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.3
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      compatibilityDate, devtools, components
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-ijvmk1?file=app.vue

### Describe the bug

Consider this setup:

- `app.vue` containing:
  - dynamic global component containing:
    - dynamic global component containing:
      - component with `useId`
    - non-dynamic component containing:
      - component with `useId`

This results in hydration mismatches due to different order of appended numeric ids:
```
  - rendered on server: for="n7UMpQwNU5n-1"
  - expected on client: for="n7UMpQwNU5n-0"
```

**Comment by codeflorist** [comment]
Actually, i just realised, that in my project the second form is not a child of any dynamic component, but in a separate non-dynamic component. Nonetheless i still have the same issue. But i was not able to create a reproduction using this structure. This might be yet another bug, or related to the one above.

So, imho there are definitely some fishy things going on with `useId` in more complex projects using dynamic and variously nested components.

**Comment by danielroe** [comment]
Unfortunately this is a consequence of this upstream bug: https://github.com/vuejs/core/issues/6638. In general hydration within _any_ async component, including layouts, can cause issues until this is resolved. 

Let's track in https://github.com/nuxt/nuxt/issues/27378.
