### ISSUE TITLE
[ERR_MODULE_NOT_FOUND]: Cannot find module after running production app

### ISSUE THREAD

**Issue by BayBreezy** [nuxt/nuxt#28127]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.20.2`
- Nuxt Version:     `3.12.3`
- CLI Version:      `3.12.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `npm@10.5.0`
- Builder:          `-`
- User Config:      `devtools`, `css`, `vite`, `modules`, `build`, `typescript`, `vcalendar`, `tailwindcss`, `imports`, `app`, `content`, `routeRules`, `colorMode`, `pwa`, `site`, `sitemap`, `ogImage`, `compatibilityDate`
- Runtime Modules:  `@vueuse/nuxt@10.11.0`, `@nuxtjs/tailwindcss@6.12.1`, `radix-vue/nuxt`, `nuxt-icon@0.6.10`, `@samk-dev/nuxt-vcalendar@1.0.3`, `@vee-validate/nuxt@4.13.2`, `@nuxt/content@2.13.1`, `@nuxtjs/color-mode@3.4.2`, `@morev/vue-transitions/nuxt@3.0.2`, `@kevinmarrec/nuxt-pwa@0.17.0`, `@nuxtjs/seo@2.0.0-rc.12`, `@nuxt/eslint@0.3.13`, `nuxt-swiper@1.2.2`, `v-wave/nuxt`, `@nuxt/image@1.7.0`
- Build Modules:    `-`

### Reproduction

https://ui-thing.behonbaker.com/getting-started/introduction

### Describe the bug

After installing the dependencies and running the build command. I ran the command to preview the app: `node .output/server/index.mjs`. But the I get this error

```bash
❯ node .output/server/index.mjs

node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/baker/Desktop/ui-thing/.output/server/node_modules/shiki/dist/core.mjs' imported from /Users/baker/Desktop/ui-thing/.output/server/index.mjs
    at new NodeError (node:internal/errors:405:5)
    at finalizeResolution (node:internal/modules/esm/resolve:327:11)
    at moduleResolve (node:internal/modules/esm/resolve:980:10)
    at defaultResolve (node:internal/modules/esm/resolve:1193:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:404:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:373:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:250:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:39)
    at link (node:internal/modules/esm/module_job:75:36) {
  url: 'file:///Users/baker/Desktop/ui-thing/.output/server/node_modules/shiki/dist/core.mjs',
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v18.20.2
```

### Additional context

The repo can be found here: https://github.com/BayBreezy/ui-thing

**Comment by BayBreezy** [comment]
The reproduction is the live link here: https://ui-thing.behonbaker.com/getting-started/introduction
and the repo for it is here: https://github.com/BayBreezy/ui-thing

**Comment by manniL** [comment]
@BayBreezy please read the comment from above.

> Please ensure that the reproduction is as minimal as possible. See more details [in our guide](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction).

**Comment by BayBreezy** [comment]
@manniL Sadly I cannot reproduce the error in a fresh nuxt project.
I know what the problem is. When I run the build command, vite (or nuxt) is not including the file called `core.mjs` inside the `.output/server/node_modules/shiki/dist` folder. 

In a fresh nuxt project with the `content` module added, I see that this file is included after running the build command.
Is there a way to force the build command to include this file in the `shiki` package that is installed in the `.output/server/node_modules`?

**Comment by BayBreezy** [comment]
So I got the build to work by adding `shiki` to the list of dependencies that should be transpiled.

```ts
build: { transpile: ["vue-sonner", "shiki"] },
```

I doubt this is the correct way to get this to work. It was never an issue in the past but maybe something changed in the shiki repo that i am not aware of. 

If there is a better solution, I would love to hear it. If this is as good as it gets, then feel free to close this issue.

**Comment by henryclw** [comment]
> @BayBreezy please read the comment from above.
> 
> > Please ensure that the reproduction is as minimal as possible. See more details [in our guide](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction).

I could reproduce this error with freshly cloned https://github.com/nuxt-ui-pro/saas/
Refer to: https://github.com/nuxt-ui-pro/saas/issues/42

**Comment by henryclw** [comment]
> So I got the build to work by adding `shiki` to the list of dependencies that should be transpiled.
> 
> ```ts
> build: { transpile: ["vue-sonner", "shiki"] },
> ```
> 
> I doubt this is the correct way to get this to work. It was never an issue in the past but maybe something changed in the shiki repo that i am not aware of.
> 
> If there is a better solution, I would love to hear it. If this is as good as it gets, then feel free to close this issue.

Thank you for this temp fix using [transpile](https://nuxt.com/docs/api/nuxt-config#transpile), it works for me

**Comment by AnthonyFromTheVault** [comment]
I can also reproduce this error with a freshly cloned copy of https://github.com/nuxt-ui-pro/saas/ — in my case I'm running into issues when trying to deploy it to Netlify.

Any serverless functions that are generated during the build, crash when you try to access them/use them in the browser:
```
This function has crashed

An unhandled error in the function code triggered the following message:

Error - Cannot find module '/var/task/node_modules/shiki/dist/core.mjs' imported from /var/task/server.mjs 
```
---

**I am able to get it working with the transpile fix [mentioned above](https://github.com/nuxt/nuxt/issues/28127#issuecomment-2226765229)** — thanks all who have pointed that out and posted it here so that I could stumble across this after a long day of hunting down this bug!

**Comment by Solynhoo** [comment]
> So I got the build to work by adding `shiki` to the list of dependencies that should be transpiled.
> 
> ```ts
> build: { transpile: ["vue-sonner", "shiki"] },
> ```
> 
> I doubt this is the correct way to get this to work. It was never an issue in the past but maybe something changed in the shiki repo that i am not aware of.
> 
> If there is a better solution, I would love to hear it. If this is as good as it gets, then feel free to close this issue.

I was having the same issue with my **Nuxt Image and Nuxt SEO** and this solution worked, thank you! 😁

**Comment by outlabsio** [comment]
same issue here, on netlify when using the nuxt pro saas template. local builds work fine. seems to be a serverless issue?

**Comment by acidjazz** [comment]
ran into this as well

**Comment by danielroe** [comment]
This seems to be an issue with shiki + nitro's wasm implementation. 

Would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏

Alternatively, I think when shiki finally uses JS rather than wasm, this issue will be resolved.

**Comment by acidjazz** [comment]
the change recommended in `nuxt.config.ts` fixed it for me
 
```ts
  build: {
    transpile: ['shiki'],
  },
```
