### ISSUE TITLE
I'm using the caching system of nitro, which use the redis driver. If my redis connection fails, is there a way to make defineCachedEventHandler not report an error and not use the cache?

### ISSUE THREAD

**Issue by robertyclin** [nuxt/nuxt#28129]
### Describe the feature

defineCachedEventHandler run normally

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
Please kindly ask this question in the [nitro repository](https://github.com/unjs/nitro) ☺️
