### ISSUE TITLE
Nuxt 3.12.0 no longer calls route key functions in definePageMeta for routes created by the pages:extend hook

### ISSUE THREAD

**Issue by hecktarzuli** [nuxt/nuxt#28122]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.12.1`
- Nuxt Version:     `3.12.3`
- CLI Version:      `3.12.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `npm@10.5.0`
- Builder:          `-`
- User Config:      `app`, `appConfig`, `vite`, `css`, `components`, `modules`, `formkit`, `experimental`, `nitro`, `sourcemap`, `runtimeConfig`, `postcss`, `devtools`, `typescript`
- Runtime Modules:  `nuxt-vitest@0.10.5`, `@vueuse/nuxt@10.11.0`, `@pinia/nuxt@0.5.1`, `@formkit/nuxt@1.6.5`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-c2dzdp

Instructions are on the site.

### Describe the bug

Starting with Nuxt 3.12.0, Nuxt is no longer calling key functions defined in `definePageMeta` for pages added via `pages:extend` hook.  This results in pages re-mounting unexpectedly.  In our case, we have a couple of routes all going to the same page component.  We use `definePageMeta/key` to make sure the app re-mounts when specific url data changes.

It seems to be related to this change, https://github.com/nuxt/nuxt/pull/27134/files.
If I set `scanPageMeta: false`, it works as expected.

### Additional context
Possibly related to https://github.com/nuxt/nuxt/issues/28086

Pages added via /pages folder seem fine.

**Comment by danielroe** [comment]
Have you tested this is still reproducible with v3.12.4?

**Comment by hecktarzuli** [comment]
Yeah, this still looks to be a problem in v3.12.4.

**Comment by hecktarzuli** [comment]
This is still an issue in 3.15.1

https://stackblitz.com/edit/nuxt-starter-c2dzdp

**Comment by danielroe** [comment]
@hecktarzuli  you're meant to use the new hook. is it an issue if you do?

**Comment by hecktarzuli** [comment]
@danielroe i'm not sure what you mean.  We're just trying to upgrade from 3.11.   Setting `experimental.scanPageMeta:false` seems to fix the issue since this seems to be defaulted to `true` in 3.12, but I'm not sure if this issue is expected with it set to `true` or not.

**Comment by danielroe** [comment]
set `experimental.dcsnPageMeta` to `after-resolve`. or set compat version and you should be good.

**Comment by danielroe** [comment]
@hecktarzuli  perhaps you could provide a reproduction?
