### ISSUE TITLE
HMR is broken for a simple skeleton app

### ISSUE THREAD

**Issue by x-tropy** [nuxt/nuxt#28135]
### Environment

- Operating System: `Darwin`
- Node Version:     `v22.0.0`
- Nuxt Version:     `3.12.3`
- CLI Version:      `3.12.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `pnpm@9.4.0`
- Builder:          `-`
- User Config:      `devtools`, `modules`, `compatibilityDate`
- Runtime Modules:  `@nuxt/ui@2.17.0`
- Build Modules:    `-`

### Reproduction

the app is generated with this command:
`npx nuxi init -t ui <app>`

I added an `about` page
![image](https://github.com/user-attachments/assets/0c5f6b8b-fae6-4058-a836-b483d1ea3226)

Then added a `<NuxtLink>` to `about` page in `app.vue`
![image](https://github.com/user-attachments/assets/8ee8ea5e-1860-4dcf-809c-6c66adb6642f)

### Describe the bug

first of all, hmr is not working, I see nothing in the `/about` route.

secondly, i see this warning in the command line:
```

 ERROR  [unhandledRejection] write EPIPE                                                                                            4:54:41 PM

  at afterWriteDispatched (node:internal/stream_base_commons:161:15)
  at writeGeneric (node:internal/stream_base_commons:152:3)
  at Socket._writeGeneric (node:net:953:11)
  at Socket._write (node:net:965:8)
  at writeOrBuffer (node:internal/streams/writable:564:12)
  at _write (node:internal/streams/writable:493:10)
  at Writable.write (node:internal/streams/writable:502:10)
  at Socket.ondata (node:internal/streams/readable:1007:22)
  at Socket.emit (node:events:520:28)
  at addChunk (node:internal/streams/readable:559:12)
```

### Additional context

![image](https://github.com/user-attachments/assets/02116a39-e1eb-4699-a4ef-2dd275a6ff96)
![image](https://github.com/user-attachments/assets/3515f559-a31c-472e-b709-1c9d89f4faec)

**Comment by x-tropy** [comment]
Also the [Vue Router warn], this might relate to HMR failure:
![image](https://github.com/user-attachments/assets/43e0731e-9d04-4596-a132-889b2b240c96)

**Comment by HigherOrderLogic** [comment]
Seems like an upstream issue from Vite for me.

**Comment by x-tropy** [comment]
any idea how could this be solved？I think this might be caused by my local
environment but i have no way to figure out which part is wrong.

**Comment by danielroe** [comment]
You need to add `<NuxtPage />` to your `app.vue` to enable showing the page content.

**Comment by x-tropy** [comment]
thanks daniel for replying. 
I get your point about add `<NuxtPage />` to `app.vue`, but this won't solve the issue here. Even the most basic project setup won't work and the socket warning persits.
This shouldn't be prevelant issues, maybe just me, but I really can't figure out why...

**Comment by x-tropy** [comment]
To illustrate further, here are some more screenshots:
![image](https://github.com/user-attachments/assets/46b8e447-ad4c-48f8-aed7-99464f6c5a9b)
![image](https://github.com/user-attachments/assets/26a6ea79-acef-4af7-97c5-895c5cfe65fa)

**Comment by danielroe** [comment]
Sure - would you provide a reproduction?

**Comment by x-tropy** [comment]
Thanks @danielroe ! Here is a minimal project setup as public Github repo: [https://github.com/x-tropy/reproduce-hmr-issue](https://github.com/x-tropy/reproduce-hmr-issue)

After adding `/pages/hello.vue`, the dev server starts yelling at me about the socket error:
![image](https://github.com/user-attachments/assets/780ead6f-62b7-42bc-85ad-f2bb41b39513)

Additional environment info:
```
pnpm -v
9.5.0

node -v
v22.0.0
```

**Comment by x-tropy** [comment]
the initial project boilerplace is created by `Nuxtr: Create new Nuxt Project` vscode extension command.

**Comment by x-tropy** [comment]
I've trie running the provided repo in stackblitz, HMR does work...
But in my local computer, adding new route does nothing, until I restart the dev server.

**Comment by danielroe** [comment]
Your directory name might be the issue. (I believe there are upstream issues here.) Try renaming `[1] Frontend` to `frontend` and see if that works.

**Comment by x-tropy** [comment]
Yes, it's the folder name's fault. Thank you! I'm closing this issue.
