### ISSUE TITLE
Add a way to distinguish between server error/nonerror responses for client types

### ISSUE THREAD

**Issue by asasinmode** [nuxt/nuxt#28136]
### Describe the feature

Given a server route with handler

```ts
// routes/example.ts
export default defineEventHandler((event) => {
  if(Math.random() > 0.5){
    setResponseStatus(event, 500);
    return 'random error occurred'
  }
  return 'nonerror response'
})
```

when you fetch it on client using a nuxt composable like `$fetch`, for example in a `getExample` function that could be called on a button click

```ts
async function getExample() {
  try {
    // in reality can only be "nonerror response"
    const response = await $fetch('/example')  // `Simplify<"random error occurred" | "nonerror response">`
  } catch(error) {
    if (error instanceof FetchError) {
      // in reality can only be "random error occurred"
      error.data  // `any`
    }
  }
}
```

or when using `useFetch` in component `setup`

```ts
const fetchResult = useFetch('/example')
fetchResult.data   // `globalThis.Ref<Simplify<"random error occurred" | "nonerror response"> | null>`
fetchResult.error  // `globalThis.Ref<FetchError<any> | null>`
``` 

an issue with types arises. While successful responses are technically typed correctly, in reality they can only be `nonerror response` (and error responses are just `any`). I'd like to propose a way for developers to specify on server which responses are error responses that could then augment types on client. Here's more or less what I imagine it to look like

```ts
// routes/example.ts
export default defineEventHandler((event) => {
  if(Math.random() > 0.5){
    setResponseStatus(event, 500);
    return useExplicitErrorResponse('random error occurred')  // HERE
  }
  return 'nonerror response'
})
```

Only one line changes from the original example, an opt in way for users to specify this return path is an error response by wrapping the normal response in `useExplicitErrorResponse`. It could then be used to type the `useFetch().error` that would become `FetchError<'random error occurred'>` or something similar.

Additionally, it would be nice to have this functionality in the `try catch` flow, which could look something like this

```ts
try {
  const response = await $fetch('/example')
} catch(error) {
  if (error instanceof FetchError) {
    // data would now be `'random error occurred' | undefined`
    const { data } = error as FetchErrorFromRoute<'/example'>
  }
}
```

In the `try catch` variant I made up `FetchErrorFromRoute` that would type itself in the similar fashion the fetch composables do from passed url and return the error response types or fallback to `any` if the route didn't return anything wrapped in `useExplicitErrorResponse`.

I'd be willing to help with the implementation but I'm not familiar with the codebase and I would most likely need guidance

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [x] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by asasinmode** [comment]
I made a [playground](https://www.typescriptlang.org/play/?#code/C4TwDgpgBAogHmANgSwMbODATlg9lgJQgGcxcA7YiAHgBUoBeKAV3IGtzcB3cgPkagBvKADcAhomYQAXFHoBfANwAoUJCgBlYFjFh4SNBgDqOsJCx1+TehDjAI5ACbFYCFOkw58RUhSrVkcgAzCCwoAn4AfnCoWVoVZSDWVGBkCihULAgxe313DGw8QhIyShpUP2A5XgAKcUkZOQBKWTzDTyKfUv9afkFlKCgs4GYsclEJKSgxFzaPQu8SvxpelXllROTU9Mzs3JEHYAAJMSdEUJqmoQGoZCCagFkcgAsAOh0nXABbS6hqKAADK8AKxNfqDQbDUbjXY5CBzApeYq+Mo1ADkoSKQyWZSgAEY0U0bvIoBBEFRbvcnsA3h9HN9fv8gaDwRCoWMMlk4QiOosUVR0Zj8Nj+dAAEyE4k3dnjam0070n5XJkgqDRNGcchCsJZUX4tGxKAa9LakXdcVo5TrVTgaAAcQgwAAqlQAGKO1DPIgjMYANUmNBuNjsDmcUF+DH4rA43HGTAjUfYnB4ABobk6BN7obRbZY04MACICeCoSSOGhOlOuAzzJFdZbUU4gXi8fOwARaUw8ky6czUEtlitVgst5RWa6DRw5MSyAsqQba1prDZqaC0EhVJgO51uj1ex3Q-0Nair3BBTl7eEHcjHBXnLC8G3qAvTgTr4jAADaaKnwDEaIAXQhKAAHoQKgYhnlwZhEEcKAACNoAAAwAIk1U1dXNfEUKgAAfKA0JNJEzWWKAxRQpCn2gABJBYwmsDdv21QDQPAyDoNghDkJQjCcQpPEcPwnjiMw0jyKQoA) that more or less shows what I think the implementation would have to do

```ts
type ExplicitErrorResponse<T = unknown> = { value: T };
type StrapExplicitWrapper<T> = T extends ExplicitErrorResponse<infer R> ? R : T;

function createExplicitErrorResponse<const T>(value: T): ExplicitErrorResponse<T> {
  return value as ExplicitErrorResponse<T>;
}

function createEventHandler() {
  if(Math.random() < 0.5){
    return createExplicitErrorResponse('error response 1')
  } else if(Math.random() < 0.5){
    return createExplicitErrorResponse('error response 2')
  }
  return Math.random() < 0.5 ? 'nonerror response 1' : 'non error response 2'
}

type GetUseFetchReturnValue<
  T extends () => unknown = () => unknown,
  U = ReturnType<T>,
  D = Exclude<U, ExplicitErrorResponse<any>>,
  E = StrapExplicitWrapper<Exclude<U, D>>
> = {
  data: D;
  error: E;
}

type Test = GetUseFetchReturnValue<typeof createEventHandler>
type Data = Test['data']    // should be `"nonerror response 1" | "non error response 2"`
type IError = Test['error'] // should be `"error response 1" | "error response 2"`
```

**Comment by danielroe** [comment]
I love this idea!

It would need to be implemented in nitro + h3 however. Would you be happy to open an issue there instead?

**Comment by asasinmode** [comment]
Sure, by nitro + h3 do you mean the [nitro repository](https://github.com/unjs/nitro)?

**Comment by danielroe** [comment]
Yes, that's probably where we need to track this.

**Comment by asasinmode** [comment]
Done, feel free to close this if it being open there is enough
