### ISSUE TITLE
Production Build Fails: "default" is not exported by "node_modules/unenv/runtime/polyfill/process.mjs"

### ISSUE THREAD

**Issue by they-cloned-me** [nuxt/nuxt#28149]
### Environment

- Operating System: `Darwin`
- Node Version:     `v21.5.0`
- Nuxt Version:     `3.12.3`
- CLI Version:      `3.12.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `bun@1.1.20`
- Builder:          `-`
- User Config:      `app`, `css`, `fonts`, `devtools`, `future`, `modules`, `nitro`, `vue`, `runtimeConfig`, `compatibilityDate`
- Runtime Modules:  `@nuxt/fonts@0.7.1`, `nitro-cloudflare-dev@0.1.5`, `nuxt-workers@0.0.2`
- Build Modules:    `-`

### Reproduction

Not sure how I’ll reproduce here as everything works fine locally (in dev), and only breaks when you run the `build` command.

### Describe the bug

I'm encountering an issue when running the build command for production (`bun run build`).
The development build works perfectly, but during production build, I get the following error (see logs)

The app is currently hosted on `Cloudflare`

 Here is my complete `package.json`
```json
 "dependencies": {
    "nuxt": "^3.12.3",
    "nuxt-workers": "^0.0.2",
    "vue": "^3.4.31",
    "vue-router": "^4.4.0"
  },
  "devDependencies": {
    "@biomejs/biome": "^1.8.3",
    "@nuxt/fonts": "^0.7.1",
    "nitro-cloudflare-dev": "^0.1.5",
    "sass": "^1.77.8",
    "typescript": "^5.5.3",
    "wrangler": "^3.64.0"
  }
```

### Additional context

I’m using the `cloudflare` preset for deployment

### Logs

```shell-script
node_modules/std-env/dist/index.mjs (1:9): Error when using sourcemap for reporting an error: Can't resolve original location of error.
Error:  [nitro] RollupError: node_modules/std-env/dist/index.mjs (1:9): "default" is not exported by "node_modules/unenv/runtime/polyfill/process.mjs", imported by "node_modules/std-env/dist/index.mjs".
1: import { default as process } from 'unenv/runtime/polyfill/process';
            ^
2: 
3: const r=Object.create(null),E=e=>globalThis.process?.env||globalThis._importMeta_.env||globalThis.Deno?.env.toObject(...
Error:  node_modules/std-env/dist/index.mjs (1:9): "default" is not exported by "node_modules/unenv/runtime/polyfill/process.mjs", imported by "node_modules/std-env/dist/index.mjs".
  at getRollupError (node_modules/rollup/dist/es/shared/parseAst.js:396:41)
  at error (node_modules/rollup/dist/es/shared/parseAst.js:392:42)
  at Module.error (node_modules/rollup/dist/es/shared/node-entry.js:13858:16)
  at Module.traceVariable (node_modules/rollup/dist/es/shared/node-entry.js:14306:29)
  at ModuleScope.findVariable (node_modules/rollup/dist/es/shared/node-entry.js:11984:39)
  at Identifier.bind (node_modules/rollup/dist/es/shared/node-entry.js:[69](https://github.com/unserious-dev/aiisgoinggreat/actions/runs/9932982835/job/27435098067#step:5:70)08:40)
  at UnaryExpression.bind (node_modules/rollup/dist/es/shared/node-entry.js:4775:23)
  at BinaryExpression.bind (node_modules/rollup/dist/es/shared/node-entry.js:4775:23)
  at LogicalExpression.bind (node_modules/rollup/dist/es/shared/node-entry.js:4775:23)
  at LogicalExpression.bind (node_modules/rollup/dist/es/shared/node-entry.js:4775:23) 
Error:  node_modules/std-env/dist/index.mjs (1:9): "default" is not exported by "node_modules/unenv/runtime/polyfill/process.mjs", imported by "node_modules/std-env/dist/index.mjs".
error: script "build" exited with code 1
Error: Process completed with exit code 1.
```

**Comment by danielroe** [comment]
As a first step, would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏

Note: it's not a problem if you need to build or deploy a reproduction to confirm it. But without _any_ code there's often little we can do.

**Comment by they-cloned-me** [comment]
Hey Daniel, 
Sorry for not producing a repro... closing this as I think it’s a Nitro issue. 
Will investigate more, and provide a repro with extra details on the Nitro project

**Comment by they-cloned-me** [comment]
I found the root of the issue [here](https://github.com/unjs/unenv/issues/260) (unenv repo)
As a temporal fix, install `unenv` as a devDependency.

Also, this comment by @IgorMinar 
<img width="917" alt="Screenshot 2024-07-17 at 04 21 13" src="https://github.com/user-attachments/assets/5e4d478e-8e1b-4f9a-bc1b-b6e3d691177d">

cc @pi0 @danielroe

**Comment by they-cloned-me** [comment]
> once wrangler updated their pinned dependency of `unenv-nightly` this issue will be solved (it is already fixed in unenv by https://github.com/unjs/unenv/pull/261)

Thank you
