### ISSUE TITLE
Navigation guards like onBeforeRouteLeave might prevent all navigation after upgrade to 3.12.3

### ISSUE THREAD

**Issue by xollaborator** [nuxt/nuxt#28141]
### Environment

```
- Operating System: Linux
- Node Version:     v18.19.1
- Nuxt Version:     3.12.3
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  bun@1.1.20
- Builder:          -
- User Config:      alias, app, components, css, devtools, hooks, i18n, imports, modules, pwa, runtimeConfig, shadcn, srcDir, ssr, supabase, tailwindcss, typescript, vite, vue, compatibilityDate
- Runtime Modules:  @pinia/nuxt@0.5.1, @vite-pwa/nuxt@0.9.1, @nuxtjs/i18n@8.3.1, @nuxtjs/supabase@1.2.2, @nuxtjs/tailwindcss@6.12.0, shadcn-nuxt@0.10.4
- Build Modules:    -
```

### Reproduction

https://stackblitz.com/edit/github-pnptkr?file=app.vue

### Describe the bug

After upgrade to 3.12.3 navigation stops to work on pages that use navigation guards from Nuxt.

By default no return in `onBeforeRouteLeave` should work but after adding explicit `return true` below message is printed in the console. 
![image](https://github.com/user-attachments/assets/cbf5b067-e82a-4a00-82e0-d67db7f178dd)

So this makes it clear that as a workaround I need to add all parameters and call `next()` explicitly.

I see in tsconfig that latest version has changed how `#vue-router` is imported:
![image](https://github.com/user-attachments/assets/61462891-bbf3-4f9d-a8ab-b4736a871267)

It does not seem to be related from the issue perspective but maybe above finding might also help with solving other router issues, since warnings might not be shown in default usage:
https://github.com/nuxt/nuxt/issues/28086
https://github.com/nuxt/nuxt/issues/28122

**Comment by danielroe** [comment]
This has been resolved and will be included in the next patch.

**Comment by xollaborator** [comment]
@danielroe I found the original issue for the fix. Does it make sense to change the docs so it will mention searching also in (recently) closed bugs? https://nuxt.com/docs/community/reporting-bugs#search-the-issues

**Comment by danielroe** [comment]
Good idea! Maybe we could also link to a search that will show PRs merged since last release.
