### ISSUE TITLE
Nuxt page not loading

### ISSUE THREAD

**Issue by Aroshold** [nuxt/nuxt#28146]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.14.0
- Nuxt Version:     3.12.3
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.8.1
- Builder:          -
- User Config:      compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

1. Create a new npm nuxt project with git repository
2. Change app.vue to 
```vue
<template>
  <div>
    <NuxtLayout>
      <NuxtPage />
    </NuxtLayout>
  </div>
</template>
```
3. Create any layout and index page
4. `npm run dev`

### Describe the bug

app.vue has both NuxtPage and NuxtLayout inside, but either only layout is loaded, or only page

**Comment by Logannford** [comment]
hey @Aroshold ! In regards to the second point here, what are you changing `app.vue` to?

**Comment by Aroshold** [comment]
`app.vue` consists only of the following:
`
<template>
    <NuxtLayout>
        <NuxtPage/>
    </NuxtLayout>
</template>
`

**Comment by deepak-shah-np** [comment]
Hi I also have the same issue with nuxt `3.12.4` version.
I cannot load the `<NuxtPage />` . I have vue file inside `src/pages`


* Operating System: Ubuntu
* Node Version: v22.5.1
* Nuxt Version: 3.12.4
* Nitro Version: 2.9.7
* NPM: 10.8.2

app.vue

```
<template>
  <NuxtLayout>
     <NuxtPage />
  </NuxtLayout>
</template>
```

nuxt.config.ts

```
export default defineNuxtConfig({
  compatibilityDate: '2024-04-03',
  srcDir:'src/',
  ssr:false,
  devtools: { enabled: false },
  modules: []
})
```
