### ISSUE TITLE
"404 Not Found" API Calls to the Server Directory

### ISSUE THREAD

**Issue by abdulrahmanhenedy** [nuxt/nuxt#28145]
### Environment

- Operating System: Darwin
- Node Version:     v20.12.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.9.7
- Package Manager:  yarn@1.22.22
- Builder:          vite
- User Config:      devtools, ssr, modules, build, analyze, experimental, nitro, vuefire, runtimeConfig, buildModules, vuetify, css, postcss
- Runtime Modules:  nuxt-icon@0.4.2, @nuxt/content@2.12.0, @pinia/nuxt@0.5.1, nuxt-security@2.0.0-rc.9, @nuxt/image@1.7.0, nuxt-vuefire@1.0.2
- Build Modules:    @nuxtjs/vuetify, @nuxt/typescript-build@3.0.1

### Reproduction

https://github.com/abdulrahmanhenedy/nuxt-reproduction

### Describe the bug

i have a nuxt app that uses the nuxt server folder for backend besides using django as well and Django also used for a small portion of the app. now i have a serious problem with API requests to the nuxt server folder for some reason.

I'm getting a " [POST] (server/api file> 404 not found" everytime i try to interact (POST) with the Nuxt /server/API directory, even if i turned django off it doesn't change.

I'm using Coolify (open-source Vercel alternative) for deployment on a DigitalOcean droplet. The problem appears in prod while the dev environment works pretty well.

### Additional context

![Screen Shot 2024-07-14 at 12 34 30 AM](https://github.com/user-attachments/assets/deb60ca5-28f2-4c70-9191-bbdc136e4a21)

**Comment by abdulrahmanhenedy** [comment]
so after some debugging i found out it only happens when it's async function or a POST request. Interesting since It works pretty well with normal non-async GET requests.

**Comment by itsrishabh** [comment]
Having the same issue here within an async function using a post request

```
async function someCall() {
  const body: any = {
    key: value,
  }

  console.info({ body });

  const { data, status, error }: any = await useFetch('/api/whatever', {
    method: 'POST',
    body: body,
    server: false,
    dedupe: 'defer',
  });

  console.info({ status: status.value })

  if (error.value) {
    console.error({ error: error.value });
    return;
  }

  console.info({ data: data.value })
};
```

What was your resolution @abdulrahmanhenedy ?
