### ISSUE TITLE
module disabled due to incompatibilty issues nuxt 4

### ISSUE THREAD

**Issue by data-diego** [nuxt/nuxt#28140]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.15.0
- Nuxt Version:     4.0.0-28679856.48a8b180
- CLI Version:      3.13.0-1719571044.bca75ab
- Nitro Version:    -
- Package Manager:  pnpm@9.4.0
- Builder:          -
- User Config:      modules, future, shadcn, extends, appConfig, ssr, experimental, imports, googleFonts, app, compatibilityDate
- Runtime Modules:  @nuxtjs/tailwindcss@6.12.1, @pinia/nuxt@0.5.1, @vueuse/nuxt@10.11.0, nuxt-icon@1.0.0-beta.7, @nuxtjs/google-fonts@3.2.0, shadcn-nuxt@0.10.4
- Build Modules:    -
------------------------------

### Reproduction

Fresh nuxt 4 instance with the modules listed using pnpm

### Describe the bug

Hi,

I upgraded to nuxt 4 but some modules say that are incompatible and got disabled, is there a workaround for this?

### Additional context

Specifically I got @nuxtjs/tailwindcss, pinia and nuxt-icon with that issue

### Logs

[1:39:30 AM]  WARN  Module @nuxtjs/tailwindcss is disabled due to incompatibility issues:
 - [nuxt] Nuxt version ^2.9.0 || ^3.0.0-rc.1 is required but currently using 4.0.0-28679856.48a8b180

[1:39:30 AM]  WARN  Module pinia is disabled due to incompatibility issues:
 - [nuxt] Nuxt version ^2.0.0 || ^3.0.0-rc.5 is required but currently using 4.0.0-28679856.48a8b180

[1:39:30 AM]  WARN  Module nuxt-icon is disabled due to incompatibility issues:
 - [nuxt] Nuxt version ^3.0.0 is required but currently using 4.0.0-28679856.48a8b180

**Comment by HigherOrderLogic** [comment]
This is the expected behaviour. If you really want to bypass those warnings and you are sure those modules would work fine with Nuxt 4, you can patch those using your package manager.

**Comment by danielroe** [comment]
This should be raised downstream.

- Pinia should be resolved when https://github.com/vuejs/pinia/pull/2694 is released.
- https://github.com/nuxt-modules/tailwindcss/pull/876
- https://github.com/nuxt/icon/pull/202
