### ISSUE TITLE
nuxt3最新版本安装依赖的时候提示好几个”no longer supported“

### ISSUE THREAD

**Issue by freezyh** [nuxt/nuxt#28155]
### Describe the feature

node版本22，当创建完项目，安装依赖包提示：
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated npmlog@5.0.1: This package is no longer supported.
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated are-we-there-yet@2.0.0: This package is no longer supported.
npm WARN deprecated gauge@3.0.2: This package is no longer supported.
这依赖包不在提供长期支持，后面会不会影响项目？官方能处理下么

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by freezyh** [comment]
@danielroe

**Comment by danielroe** [comment]
@freezyh Thank you for commenting. These are dependencies of our dependencies and in most cases are already being tracked. You can use the `npm why` or `pnpm why` commands to find out why they are in the dependency tree, and please do raise them in the repositories which have a direct dependency on them 🙏

**Comment by AlphaFoxz** [comment]
@freezyh 
![Image](https://github.com/user-attachments/assets/98510405-c571-4c73-9394-b38f54beed9d)

https://github.com/unjs/nitro/issues/2522
