### ISSUE TITLE
`nuxt.options.nitro.publicAssets.push` leads to 404 errors

### ISSUE THREAD

**Issue by Skyost** [nuxt/nuxt#28163]
### Environment

```
Nuxt project info:                                                                                                                                                          22:50:35

------------------------------
- Operating System: Windows_NT
- Node Version:     v22.4.1
- Nuxt Version:     3.12.3
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.8.1
- Builder:          -
- User Config:      ssr, compatibilityDate, app, css, vite, modules, nitro, eslint, runtimeConfig, content, googleFonts, site, sitemap, linkChecker, commitShaFileGenerator, cname, experimental
- Runtime Modules:  @nuxt/eslint@0.3.13, nuxt-cname-generator@1.0.1, ~/modules/commit-sha-file-generator, ~/modules/content-downloader, ~/modules/latex-pdf-generator, ~/modules/nuxt-content-latex, @bootstrap-vue-next/nuxt@0.23.5, @nuxt/content@2.13.1, @nuxtjs/google-fonts@3.2.0, nuxt-link-checker@3.0.0-rc.12, @nuxtjs/sitemap@5.3.4, @nuxtjs/robots@4.0.0, @nuxt/icon@1.1.1
- Build Modules:    -
------------------------------
```

### Reproduction

https://github.com/Skyost/MesCoursDeMaths/blob/master/modules/nuxt-content-latex/index.ts#L62

### Describe the bug

I'm trying to push dynamically generated resources to Nitro.

```
nuxt.options.nitro.publicAssets = nuxt.options.nitro.publicAssets || []
nuxt.options.nitro.publicAssets.push({
  baseURL: '/images/',
  dir: dynamicImagesDir
})
````

The problem is that, as my `/images/` directory already exists in my _public_ folder, all my "static" images that are in _public/images_ lead to 404 errors.

### Additional context

It wasn't happening with the previous version of Nuxt (3.11.2).

**Comment by danielroe** [comment]
Would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏

**Comment by Skyost** [comment]
Just tried to reproduce the error without Nuxt : https://stackblitz.com/edit/github-kmwgkj?file=nitro.config.ts. Is it good @danielroe ?

**Comment by danielroe** [comment]
Ah. That's helpful. I don't think it's a bug though. You just enable `fallthrough` if you want to opt out of early returning if a given public asset dir doesn't have a file. (It's a performance feature.)

**Comment by Skyost** [comment]
Oh okay, I wasn't aware of this. How can I enable it to see if it works ?

**Comment by danielroe** [comment]
It's possible it's an issue in Nuxt if it was introduced in an update to Nuxt itself.

Sorry to trouble you again, but could you create a minimal Nuxt reproduction? 🙏

**Comment by Skyost** [comment]
@danielroe Sure, here is it : https://stackblitz.com/edit/github-a9mcsr?file=modules%2FdownloadImage.ts,pages%2Findex.vue.

**Comment by danielroe** [comment]
Checking, this seems fine:

```diff
  nuxt.options.nitro.publicAssets.push({
    baseURL: '/images/',
    dir: destinationDirectory,
+   fallthrough: true,
  });
```

That is what I would expect. I'm not sure why this might have been a change in behaviour here but it might have been in a nitropack update.

**Comment by Skyost** [comment]
Thanks a lot !
