### ISSUE TITLE
Vite import types are not included with nuxt

### ISSUE THREAD

**Issue by markbrockhoff** [nuxt/nuxt#28197]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.11.0`
- Nuxt Version:     `3.12.3`
- CLI Version:      `3.12.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `pnpm@9.4.0`
- Builder:          `-`
- User Config:      `compatibilityDate`, `devtools`, `typescript`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/markbrockhoff/nuxt-vite-types-bug-repro

### Describe the bug

Right now typescript will complain when trying to use raw or url imports ([Docs](https://vitejs.dev/guide/assets#explicit-url-imports)):

<img width="1070" alt="image" src="https://github.com/user-attachments/assets/10b80947-ce66-44ca-8171-3aaa46f3c6e2">

For projects using vite as a bundler I'd expect that vites' types are included within the types generated by nuxt so that these kinds of imports work out of the box.

### Additional context

If I understood it correctly, this should have been added by #19338 already. That's why I'm opening this as a bug and not a feature request. Please correct me if I'm mistaken.
It also seems like there is an ongoing discussion regarding this, which didn't get that much attention so far: #19694

**Comment by cwaring** [comment]
It looks like the nuxt cli bundler can't access `vite/client` ([ref](https://github.com/nuxt/nuxt/blob/c8cff9be540922182e9af92aa33bba9c91138b06/packages/nuxt/src/core/nuxt.ts#L512)) during [nuxt prepare:types ](https://github.com/nuxt/nuxt/blob/c8cff9be540922182e9af92aa33bba9c91138b06/packages/nuxt/src/core/nuxt.ts#L518C14-L518C27), if you are using pnpm without hoisting or installing `vite` as a project dependency first.

A temporary workaround is to add the follow hoisting pattern to `/.npmrc`

```ini
public-hoist-pattern[]=vite
```

Then run the following to reinstall the project deps and rebuild the types:
```sh
pnpm i
```

**Comment by cwaring** [comment]
It looks like the nuxt cli bundler can't resolve the required `vite/client` ([ref](https://github.com/nuxt/nuxt/blob/c8cff9be540922182e9af92aa33bba9c91138b06/packages/nuxt/src/core/nuxt.ts#L512)) dependency during `nuxt prepare:types` – if you are using pnpm without hoisting or installing `vite` as a project dep first.

A temporary workaround is to add the follow hoisting pattern to `/.npmrc`

```ini
public-hoist-pattern[]=vite
```

Then reinstall the project deps and rebuild the types:
```sh
pnpm i
```
