### ISSUE TITLE
The regex caused the auto-imports to fail.

### ISSUE THREAD

**Issue by Ice-Hazymoon** [nuxt/nuxt#28190]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.13.1
- Nuxt Version:     3.12.3
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@8.9.2
- Builder:          -
- User Config:      devtools, app, runtimeConfig, ssr, experimental, pwa, sourcemap, typescript, modules, vite, primevue, unocss, imports, googleFonts, turnstile, supabase, css, postcss
- Runtime Modules:  @nuxtjs/turnstile@0.9.3, @unocss/nuxt@0.61.5, nuxt-primevue@3.0.0, @nuxtjs/google-fonts@3.2.0, @nuxtjs/supabase@1.3.5, @pinia/nuxt@0.5.1, @pinia-plugin-persistedstate/nuxt@1.2.1, @vueuse/nuxt@10.11.0, @vite-pwa/nuxt@0.9.1     
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-c1luxa?file=app.vue

### Describe the bug

```js
const regex =
  /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/; //
```

Once I use this regex anywhere in the script tag, all subsequent auto-imports stop working.

Seriously, I often encounter this issue, especially when I write some content or comments within the template tags. Even though it fully complies with Vue's syntax, it causes compilation to fail until I either delete the content, change some words, or rewrite it differently. I don't understand the internal parsing logic of Nuxt or Vue3. This issue doesn't always happen, but it's quite common.

**Comment by danielroe** [comment]
let's track in https://github.com/unjs/unimport/issues/346.
