### ISSUE TITLE
Catch or ignore import errors on modules/plugins

### ISSUE THREAD

**Issue by DaniGTA** [nuxt/nuxt#28198]
### Describe the feature

I have several plugins and modules essential for functionality, but some, like analytics, are not strictly necessary. If these non-essential plugins fail due to a connection error or are blocked by a browser plugin, Nuxt should still operate correctly.

I would like a feature that allows me to mark certain plugins so they can be ignored if they fail to load.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
I think it makes sense for you to wrap your code in `try/catch` so you can handle or ignore the error as you wish. If Nuxt implements this it would add unnecessary overhead.

Note that https://github.com/nuxt/scripts provides some helpers here.
