### ISSUE TITLE
`onBeforeRouteLeave` triggered by `router.replace({ query: {...} })` since `v3.12.3`

### ISSUE THREAD

**Issue by Nicolas-Yazzoom** [nuxt/nuxt#28194]
### Environment

```
------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Reproduction

https://stackblitz.com/edit/github-piu9n3?file=pages%2Findex.vue

- This example uses `3.12.2`.
- Click the buttons and observe console. There is no "onBeforeRouteLeave called" in the console.
- Stop dev server and run `npx nuxi upgrade --force` to set the project to `3.12.3` and run `npm run dev` to restart.
- Click the buttons and observe console again. Now "onBeforeRouteLeave called" can be seen in the console.

### Describe the bug

In `3.12.2`, `onBeforeRouteLeave` did not get triggered by `router.replace({ query: { test: 'A' } });`. In `3.12.3` it does. Note that I'm using the pages directory in the repro.

### Additional context

I saw some other tickets related to `onBeforeRouteLeave` and this version, but since this specific thing wasn't mentioned, I created a new one.

**Comment by huang-julien** [comment]
Hello :wave: this is probably fixed in the nightly channel. can you try adding this piece of code in a module ? 

```ts
    nuxt.hook('imports:sources', (sources) => {
      const routerImports = sources.find(s => s.from === '#app/composables/router' && s.imports.includes('onBeforeRouteLeave'))
      if (routerImports) {
        routerImports.from = 'vue-router'
      }
    })
```

or try with nuxt-nightly

**Comment by Nicolas-Yazzoom** [comment]
> Hello 👋 this is probably fixed in the nightly channel. can you try adding this piece of code in a module ?
> 
> ```ts
>     nuxt.hook('imports:sources', (sources) => {
>       const routerImports = sources.find(s => s.from === '#app/composables/router' && s.imports.includes('onBeforeRouteLeave'))
>       if (routerImports) {
>         routerImports.from = 'vue-router'
>       }
>     })
> ```
> 
> or try with nuxt-nightly

Tried both suggestions and both seem to work.

**Comment by huang-julien** [comment]
Closing as fixed in nightly
