### ISSUE TITLE
Uncaught (in promise) non-precached-url: non-precached-url :: [{"url":"/"}]

### ISSUE THREAD

**Issue by meliceanu** [nuxt/nuxt#28200]
### Environment

- Operating System: Darwin
- Node Version:     v22.1.0
- Nuxt Version:     3.12.3
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.5.0
- Builder:          -
- User Config:      apollo, app, build, css, devtools, experimental, formkit, gtm, i18n, modules, nitro, pwa, runtimeConfig, site, sitemap, sourcemap, ssr, vite, compatibilityDate
- Runtime Modules:  @nuxtjs/i18n@8.3.1, @nuxtjs/sitemap@5.3.5, @nuxtjs/apollo@5.0.0-alpha.8, @pinia/nuxt@0.5.1, @vite-pwa/nuxt@0.9.1, @formkit/nuxt@1.6.5, @zadigetvoltaire/nuxt-gtm@0.0.13
- Build Modules:    -

### Reproduction

<img width="1296" alt="screenshot" src="https://github.com/user-attachments/assets/46463494-a8b8-4f77-ad49-d4e9acd81bb5">

### Describe the bug

There is no way to remove this error, i don't know what to do. I don't even know where it's from.

**Comment by meliceanu** [comment]
i found out that i have to prerender the / page and i used nitro 


<img width="406" alt="Screenshot 2024-07-18 at 14 18 05" src="https://github.com/user-attachments/assets/e29b6e93-2cd0-4e63-b0ef-b98015aa4233">

**Comment by danielroe** [comment]
Ahh, in that case this will be resolved with the next 3.x release.
