### ISSUE TITLE
Wrong auto import types of `vue-router` API

### ISSUE THREAD

**Issue by serkodev** [nuxt/nuxt#28218]
### Environment

- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

```ts
// auto import wrong type of onBeforeRouteUpdate
onBeforeRouteUpdate((to) => {
  console.log(to);
});
```

https://stackblitz.com/edit/github-bjyhxs?file=app.vue,pages/index.vue,package.json,tsconfig.json

```sh
npm run typecheck
```

### Describe the bug

```
pages/index.vue:2:22 - error TS7006: Parameter 'to' implicitly has an 'any' type.
2 onBeforeRouteUpdate((to) => {
```

The reason is the below `vue-router` API inside `.nuxt/types/imports.d.ts` imported from `../../node_modules/vue-router/auto-routes` which does not exports the `useLink`, `onBeforeRouteLeave`, `onBeforeRouteUpdate`

```ts
readonly useLink: UnwrapRef<typeof import('../../node_modules/vue-router/auto-routes')['useLink']>
readonly onBeforeRouteLeave: UnwrapRef<typeof import('../../node_modules/vue-router/auto-routes')['onBeforeRouteLeave']>
readonly onBeforeRouteUpdate: UnwrapRef<typeof import('../../node_modules/vue-router/auto-routes')['onBeforeRouteUpdate']>
```

### Additional context

in Nuxt v3.12.2 has no issue and the below is the `imports.d.ts` of it.
```ts
const onBeforeRouteLeave: typeof import('../vue-router-stub')['onBeforeRouteLeave']
const onBeforeRouteUpdate: typeof import('../vue-router-stub')['onBeforeRouteUpdate']
const useLink: typeof import('../vue-router-stub')['useLink']
```

#### Temporary fix

Add `vue-router` imports manually
```diff
+ import { onBeforeRouteUpdate } from 'vue-router'
onBeforeRouteUpdate((to) => {
  console.log(to);
});
```

**Comment by zzpmaster** [comment]
the same issue is occurring with me.

**Comment by serkodev** [comment]
@danielroe `vue-router` accepted the solution PR (https://github.com/vuejs/router/pull/2323) I submitted.
This issue should be resolved in the next `vue-router` release. Thanks for following up.
