### ISSUE TITLE
Wrong module resolution in tsconfig.json file

### ISSUE THREAD

**Issue by guibulator** [nuxt/nuxt#28224]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.13.1`
- Nuxt Version:     `3.12.4`
- CLI Version:      `3.12.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `yarn@1.22.22`
- Builder:          `-`
- User Config:      `compatibilityDate`, `devtools`, `modules`
- Runtime Modules:  `@sidebase/nuxt-auth@0.8.1`
- Build Modules:    `-`

### Reproduction

You have the issue with your default repro as well.
https://codesandbox.io/p/devbox/gifted-boyd-vmf834?file=%2F.nuxt%2Ftsconfig.json%3A145%2C5

### Describe the bug

@danielroe 
I opened an issue on `@sidebase/nuxt-auth` because PageMeta was not properly augmented from `#app` https://github.com/sidebase/nuxt-auth/issues/807. I tested with a local module augmenting `#app` and it works as expected.

Turns out that the issue is that files under `include` section in the `tsconfig.json` are not resolved properly. You can check with even your own `devtools` module. Check the path in `.nuxt/tsconfig.json` for devtools: `../node_modules/@nuxt/devtools/runtime`

But it should be `../node_modules/@nuxt/devtools/dist/runtime`

**Comment by guibulator** [comment]
Issue is here: https://github.com/nuxt/nuxt/blob/228b9f6820ee63a13e95c8c7d3c1a66d2408de7f/packages/kit/src/template.ts#L159

**Comment by HigherOrderLogic** [comment]
I want to work on this issue.

One question @danielroe, is it the convention (or required) for modules to place runtime inside `dist` like the starter template? Some like the [UnoCss](https://github.com/unocss/unocss/tree/main/packages/nuxt) module has its `runtime` dir placed outside.

**Comment by danielroe** [comment]
We can support both. Local modules won't have a dist, for example.

**Comment by guibulator** [comment]
Hi @danielroe , I'm sorry to reopen this conversation but after re-testing the fix, there are still some issues with discoverability. Maybe my understanding is wrong and you can guide me a bit with this.

In the `include` section of the `tsconfig.json` file, we now have this, which is good
<img width="1415" alt="image" src="https://github.com/user-attachments/assets/ce99bcd6-9ee4-49c6-a92d-114d59a52db9">
But we also have the node_modules excluded which causes the type augmentation to not be found.
<img width="300" alt="image" src="https://github.com/user-attachments/assets/79c46cd4-a11a-4a49-a075-d41fe34136f6">

If I remove the `node_modules` from the `exlude`, it works but I guess that's not the solution. Should the reference to the typings be explicitly added to `.nuxt/types` or should it work with the `node_modules` excluded as well?

I updated my repro with the fix: https://github.com/guibulator/nuxt-pagemeta-repro

**Comment by danielroe** [comment]
@guibulator Checking, `@sidebase/nuxt-auth` should likely add that file to `references` in the `prepare:types` hook. It's right that we exclude `node_modules` by default (it's the [default ts setting](https://www.typescriptlang.org/tsconfig/#exclude)) and it would be very non-performant to ask TS to scan all files in that folder.
