### ISSUE TITLE
Error 500 when building Nuxt 3.12.4 after upgrading from 2.17.3

### ISSUE THREAD

**Issue by ltroya-as** [nuxt/nuxt#28228]
### Environment

Previous version:
- Operating System: Darwin
- Node Version:     v21.7.1
- Nuxt Version:     2.17.3
- CLI Version:      3.12.0
- Nitro Version:    -
- Package Manager:  yarn@1.22.22
- Builder:          webpack
- User Config:      target, ssr, generate, head, css, plugins, components, buildModules, modules, sitemap, robots, sentry, axios, build, router, publicRuntimeConfig, graphql, hooks, storybook, ignore
- Runtime Modules:  @nuxtjs/axios@5.13.6, nuxt-graphql-request@6.0.3, cookie-universal-nuxt@2.2.2, @nuxtjs/sentry@5.1.7, @nuxtjs/sitemap@2.4.0, @nuxtjs/robots@2.5.0, nuxt-clipboard@0.0.7
- Build Modules:    @nuxtjs/eslint-module@3.1.0, @nuxtjs/stylelint-module@5.2.0, @nuxt/postcss8@1.1.3, @nuxtjs/svg@0.1.12, @/modules/generator

Current version:
- Operating System: `Darwin`
- Node Version:     `v20.11.1`
- Nuxt Version:     `3.12.4`
- CLI Version:      `3.12.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `yarn@1.22.22`
- Builder:          `-`
- User Config:      `compatibilityDate`, `nitro`, `app`, `typescript`, `devServerHandlers`, `vite`, `runtimeConfig`, `sourcemap`, `modules`, `build`, `css`, `tailwindcss`, `ignore`, `graphql`, `experimental`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.12.1`, `nuxt-graphql-request@8.1.0`, `@nuxtjs/sitemap@5.3.5`, `@nuxtjs/robots@4.0.1`, `@nuxt/test-utils/module@3.13.1`
- Build Modules:    `-`

### Reproduction

N/A

### Describe the bug

Hi guys,

# Error using `externalVue: false`
After upgrading from Nuxt 2.17.3 to Nuxt 3.12.3 I am getting an 500 error "This page is temporarily unavailable." after running `nuxi build && nuxi preview` with the flag of `externalVue: false` on my `nuxt.config.js`.

The error I am getting in the console is: 

```
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'exports')
  at ./server/chunks/routes/renderer.mjs:839:24  
  at ModuleJob.run (node:internal/modules/esm/module_job:218:25)  
  at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)  
  at async Object.handler (./server/chunks/runtime.mjs:2878:19)  
  at async Server.toNodeHandle (./server/chunks/runtime.mjs:3148:7)
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'exports')
  at ./server/chunks/routes/renderer.mjs:839:24  
  at ModuleJob.run (node:internal/modules/esm/module_job:218:25)  
  at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)  
  at async Object.handler (./server/chunks/runtime.mjs:2878:19)  
  at async Server.toNodeHandle (./server/chunks/runtime.mjs:3148:7)
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'exports')
  at ./server/chunks/routes/renderer.mjs:839:24  
  at ModuleJob.run (node:internal/modules/esm/module_job:218:25)  
  at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)  
  at async Object.handler (./server/chunks/runtime.mjs:2878:19)  
  at async Server.toNodeHandle (./server/chunks/runtime.mjs:3148:7)
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'exports')
  at ./server/chunks/routes/renderer.mjs:839:24  
  at ModuleJob.run (node:internal/modules/esm/module_job:218:25)  
  at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)  
  at async Object.handler (./server/chunks/runtime.mjs:2878:19)  
  at async Server.toNodeHandle (./server/chunks/runtime.mjs:3148:7)
  ```
  
If I take a look at `renderer.mjs:839:24` I can see this line of code:
 ```var vueExports$1 = vue.exports;```

However, I see that `vue` is declared in line `1692` using this code:
```var vue = {exports: {}};```

Can you give me a hint on how can I fix it?

# Error using `externalVue: true`

After enabling that flag, I get a total different error: 

```
[nuxt] [request error] [unhandled] [500] Cannot find module '.output/server/node_modules/vue/server-renderer/index.mjs' imported from .output/server/chunks/routes/renderer.mjs
  at finalizeResolution (node:internal/modules/esm/resolve:264:11)  
  at moduleResolve (node:internal/modules/esm/resolve:917:10)  
  at defaultResolve (node:internal/modules/esm/resolve:1130:11)  
  at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)  
  at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)  
  at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)  
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)  
  at link (node:internal/modules/esm/module_job:84:36)
[nuxt] [request error] [unhandled] [500] Cannot find module '.output/server/node_modules/vue/server-renderer/index.mjs' imported from .output/server/chunks/routes/renderer.mjs
  at finalizeResolution (node:internal/modules/esm/resolve:264:11)  
  at moduleResolve (node:internal/modules/esm/resolve:917:10)  
  at defaultResolve (node:internal/modules/esm/resolve:1130:11)  
  at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)  
  at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)  
  at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)  
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)  
  at link (node:internal/modules/esm/module_job:84:36)
```

For this error, I tried everything on this [thread](https://github.com/nuxt/nuxt/issues/14820) without any luck. Is there anything I am missing?

I'm using `Vue 3.4.27`

**Note:** Everything is working as expected on `dev` mode. The platform I am using to deploy my project is Cloudflare, in which I am getting a different error but I hope that's fixed once the `nuxi build && nuxi preview` works 🙏 

I would appreciate any hint on this 🙏 

### Additional context

I'm using Vue 3.4.27

Nuxt config:

```
interface CustomNuxtConfig extends NuxtConfig {
  eslint?: any
}

const config: CustomNuxtConfig = {
  compatibilityDate: '2024-04-03',
  nitro: {
    prerender: {
      autoSubfolderIndex: false,
    },
  },
  typescript: {
    strict: false,
  },
  devServerHandlers: [],
  vite: {
    plugins: [svgLoader({ svgo: false })],
    define: {
      __DEV__: !IS_PRODUCTION,
      global: 'window',
    },
  },
  runtimeConfig: {
    public: {},
  },
  sourcemap: {
    server: process.env.CONTEXT === 'production',
    client: process.env.CONTEXT === 'production',
  },
  modules: [
    '@nuxtjs/tailwindcss',
    // '@nuxtjs/eslint-module',
    // '@nuxtjs/stylelint-module',
    'nuxt-graphql-request',
    '@nuxtjs/sitemap',
    '@nuxtjs/robots',
    '@nuxt/test-utils/module',
  ],
  build: {
    transpile: [
      'nuxt-graphql-request',
      'chartjs-adapter-date-fns',
      'modern-screenshot',
    ],
  },
  css: ['~/assets/main.scss'],
  tailwindcss: {
    exposeConfig: true,
    viewer: false,
    configPath: './tailwind.config.ts',
  },
  ignore: ['playwright/**/*.spec.*', 'playwright-report/*', '.idea/*'],
  graphql: {
    clients: {
      default: {
        endpoint: PUBLIC_GRAPHQL_ENDPOINT,
        options: {
          requireCredentials: false,
        } as any,
      },
      authenticatedClient: {
        endpoint: GRAPHQL_ENDPOINT,
        options: {
          requireCredentials: true,
        } as any,
      },
    },
  },
  experimental: {
    defaults: {
      nuxtLink: {
        trailingSlash: 'append',
        activeClass: 'nuxt-link-active',
        exactActiveClass: 'nuxt-link-exact-active',
      },
    },
  },
}

export default defineNuxtConfig(config)
```

**Comment by harlan-zw** [comment]
I've also run into this error on the [@nuxtjs/robots](https://github.com/nuxt-modules/robots) repo for version v3.12.4 when running my tests. It seems random in which tests it's failing for, config does not seem to matter.

>[nuxt] [request error] [unhandled] [500] Cannot find module '/home/harlan/packages/robots/test/fixtures/basic/.nuxt/test/6o8k0p/output/server/node_modules/vue/server-renderer/index.mjs' imported from /home/harlan/packages/robots/test/fixtures/basic/.nuxt/test/6o8k0p/output/server/chunks/routes/renderer.mjs

I've [pinned to 3.12.3](https://github.com/nuxt-modules/robots/commit/03cce09bbd2d7678d01066c42234bd923fbea8e7) to unblock myself (ignore the vue / vue-router deps, was trying to see if it was a hoisting bug). If you unpin the version and try run the test suite it will fail.

**Comment by ltroya-as** [comment]
@harlan-zw good point. I will disable all of those plugins to see if it changes something

**Comment by ltroya-as** [comment]
@harlan-zw I got the same error even after removing those modules. Updated `nuxt.config.ts`

```
import svgLoader from 'vite-svg-loader'
import { defineNuxtConfig, type NuxtConfig } from 'nuxt/config'
import ConfigManager from './utils/config-manager'
import { BASE_URL, PUBLIC_GRAPHQL_ENDPOINT } from './utils/constants'
import { HOTJAR_SCRIPT, HUBSPOT_SCRIPT } from './constants/third-party-scripts'

const IS_PRODUCTION = process.env.CF_PAGES_BRANCH === 'production'
const baseUrl = ConfigManager.get('BASE_URL', BASE_URL)
const scripts = []

const GRAPHQL_ENDPOINT = `${baseUrl}/wp/graphql`

if (IS_PRODUCTION) {
  scripts.push(HOTJAR_SCRIPT)
  scripts.push(HUBSPOT_SCRIPT)
}

interface CustomNuxtConfig extends NuxtConfig {
  eslint?: any
}

const config: CustomNuxtConfig = {
  compatibilityDate: '2024-04-03',
  typescript: {
    strict: false,
  },
  devServerHandlers: [],
  vite: {
    plugins: [svgLoader({ svgo: false })],
    define: {
      __DEV__: !IS_PRODUCTION,
      global: 'window',
    },
  },
  runtimeConfig: {
    public: {},
  },
  sourcemap: {
    server: process.env.CONTEXT === 'production',
    client: process.env.CONTEXT === 'production',
  },
  modules: ['@nuxtjs/tailwindcss', 'nuxt-graphql-request'],
  build: {
    transpile: [
      'nuxt-graphql-request',
      'chartjs-adapter-date-fns',
      'modern-screenshot',
    ],
  },
  css: ['~/assets/main.scss'],
  tailwindcss: {
    exposeConfig: true,
    viewer: false,
    configPath: './tailwind.config.ts',
  },
  ignore: ['playwright/**/*.spec.*', 'playwright-report/*', '.idea/*'],
  graphql: {
    clients: {
      default: {
        endpoint: PUBLIC_GRAPHQL_ENDPOINT,
        options: {
          requireCredentials: false,
        } as any,
      },
      authenticatedClient: {
        endpoint: GRAPHQL_ENDPOINT,
        options: {
          requireCredentials: true,
        } as any,
      },
    },
  },
  experimental: {
    defaults: {
      nuxtLink: {
        trailingSlash: 'append',
        activeClass: 'nuxt-link-active',
        exactActiveClass: 'nuxt-link-exact-active',
      },
    },
  },
}

export default defineNuxtConfig(config)
```

**Comment by ltroya-as** [comment]
@harlan-zw I found the issue on my project. It was the `vue` dependency on my `package.json`, after removing that dependency the project started working again.

**Comment by mctweb** [comment]
This was an error for me upgrading from Nuxt 3.12.3 to 3.12.4. The suggestion of removing vue from the package.json worked. Thank you @ltroya-as!

**Comment by danielroe** [comment]
@harlan-zw The issue you are experiencing is caused by multiple versions of vue being present in your project. It's an upstream vue/package manager issue and is not linked to any particular version of Nuxt. You should also be able to resolve by setting a resolution on a particular version of vue.

**Note**: using `@latest` can cause issues with package managers as it is not guaranteed to resolve the _actual_ latest version of the package 🤦  I would guess the original issue here was caused by a package manager smuggling in vue@2 into a Nuxt 3 project.

**Comment by harlan-zw** [comment]
@danielroe it's worth noting that this _only_ broke due to upgrading to 3.12.4 from 3.12.3 and was fixed by pinning the version back. I'll try and make a minimal reproduction when I'm back on it.

**Comment by danielroe** [comment]
That is probably happening because the Vue version depended on by a new version of Nuxt is newer than the version you already have installed.

**Comment by amandesai01** [comment]
I am facing same issue with Nuxt 3.12.3 and Vue 3.4.33

**Comment by avxkim** [comment]
i was on 3.12.3 and everything was fine, until i've upgraded to 3.12.4 `pnpm build` started to produce broken builds. Removed `vue` from package.json dependencies and it works now!

**Comment by felixgabler** [comment]
It also started happening to us recently (using bun, Vue 3.5.3, Nuxt 3.15.1) and can confirm that removing vue from the `devDependencies` helps. Interestingly it also seems to solve https://github.com/nuxt/nuxt/issues/28869

**Comment by danielroe** [comment]
This is caused by having more than one version of Vue in your dependencies, which is probably why that resolved it. Also, refreshing your lockable should resolve.
