### ISSUE TITLE
since Nuxt >= 3.12.0 definePageMeta({ layout: 'custom' }) invalid

### ISSUE THREAD

**Issue by Ttou** [nuxt/nuxt#28245]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      srcDir, app, components, devtools, vite, nitro, compatibilityDate
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/~/github.com/Ttou/nuxt-layout-issue

### Describe the bug

`definePageMeta({ layout: 'custom' })` invalid

**Comment by Yizack** [comment]
### Note for maintainers:

It seems that the `definePageMeta` macro stopped working on files with a `.tsx` extension. I tried changing the `index.tsx` implementation to `index.vue` and it seems to still work fine on `.vue` extension files

**Comment by huang-julien** [comment]
Hello :wave: can you try by disabling `experimental.scanPageMeta` in your config ? It should be fixed in nuxt-nightly

**Comment by Ttou** [comment]
@huang-julien it works 👍

**Comment by MichalPB1** [comment]
I am using [vue-facing-decorator](https://facing-dev.github.io/vue-facing-decorator/) and if in the component I use eg `definePageMeta({ layout: false })` then  I get an error as below:
```
 ERROR  [unhandledRejection] Unexpected character '@' (6:0)

  at pp$4.raise (node_modules/acorn/dist/acorn.mjs:3580:13)
  at pp.getTokenFromCode (node_modules/acorn/dist/acorn.mjs:5561:8)
  at pp.readToken (node_modules/acorn/dist/acorn.mjs:5248:15)
  at pp.nextToken (node_modules/acorn/dist/acorn.mjs:5239:15)
  at pp.next (node_modules/acorn/dist/acorn.mjs:5200:8)
  at pp$9.eat (node_modules/acorn/dist/acorn.mjs:696:10)
  at pp$9.semicolon (node_modules/acorn/dist/acorn.mjs:743:13)
  at pp$8.parseExpressionStatement (node_modules/acorn/dist/acorn.mjs:1238:8)
  at pp$8.parseStatement (node_modules/acorn/dist/acorn.mjs:959:24)
  at pp$8.parseTopLevel (node_modules/acorn/dist/acorn.mjs:823:21)
```

but when I disable `experimental.scanPageMeta` then error does not occur

**Comment by d-balaskas** [comment]
I have the same problem. The workaround worked for me:
`./nuxt.config.ts`
```
export default defineNuxtConfig({
  experimental: {
    scanPageMeta: false
  }
});
```

I have two projects A and B. Project B extends Project A. Both projects works fine but when I run Project B and try to access a page of Project A then nuxt fails to recognize the layout. Layout is defined in Project A.

on Project A's page I have just defined:
```
definePageMeta({
  layout: 'a-layout'
});
```
And created projectA/layouts/ALayout.vue

**Comment by AloneRUS** [comment]
Hello. I have only one question, why experimental function scanPageMeta turned on by default?

**Comment by lbm210** [comment]
![1723709381165](https://github.com/user-attachments/assets/2babdd6f-abdf-46b4-b5db-7bbd833aa187)
![1723709414976](https://github.com/user-attachments/assets/1034fd11-72c8-4694-bd91-b7e4db2475dc)
![1723709486506](https://github.com/user-attachments/assets/465f1572-a5ff-43fd-9103-bb39e687805e)
I modified it as above, but it still prompts me: WARN Invalid layout custom selected.

**Comment by c0nd3v** [comment]
@danielroe https://github.com/nuxt/nuxt/issues/29522 I can confirm scanPageMeta: true is causing a problem for me.
