### ISSUE TITLE
add Infinite fetch support

### ISSUE THREAD

**Issue by anton-liam** [nuxt/nuxt#28244]
### Describe the feature

like [TanStack Infinite Query](https://tanstack.com/query/latest/docs/framework/vue/guides/infinite-queries)

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
You can already use tanstack query with Nuxt for this (for example)!

Closing here as not related to the Nuxt core
