### ISSUE TITLE
when deploying to cloudflare pages using latest nuxt version, showing `This page is temporarily unavailable.`

### ISSUE THREAD

**Issue by Giancarlo-Ma** [nuxt/nuxt#28248]
### Environment

- Operating System: Linux
- Node Version:     v20.3.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    -
- Package Manager:  pnpm@9.5.0
- Builder:          -
- User Config:      compatibilityDate, devtools, nitro, modules
- Runtime Modules:  nitro-cloudflare-dev@0.1.6
- Build Modules:    -

### Reproduction

https://github.com/Giancarlo-Ma/nuxt-cf-bug

### Describe the bug

run

```
pnpm i
pnpm preview
```

and visit the / route, it will show `This page is temporarily unavailable.`

### Additional context

only add one page file in pages folder then you can reproduce
### Logs

```shell-script
✘ [ERROR] [node-fetch-native] Node.js compatible build of `node-fetch-native` is being used in a non-Node.js environment. Please make sure you are using proper export conditions or report this issue to https://github.com/unjs/node-fetch-native. You can set `process.env.DISABLE_NODE_FETCH_NATIVE_WARN` to disable this warning.


✘ [ERROR] [nuxt] [request error] [unhandled] [500] global is not defined
```

**Comment by danielroe** [comment]
Is this resolved if you add `vue-router` as a dependency?

**Comment by Yizack** [comment]
@Giancarlo-Ma 

Your project root is missing the `.npmrc` file with the following contents

```
shamefully-hoist=true
strict-peer-dependencies=false
```

cc @danielroe

**Comment by Giancarlo-Ma** [comment]
@Yizack Thank you, it works. Can you explain why making that change fixed it?

**Comment by Yizack** [comment]
Hello! @Giancarlo-Ma While 

I just noticed adding `vue-router` as dependency without the `.npmrc` file as mentioned before works

While crawling in nuxt history, I just learned that efforts are being made to support nuxt without `--shamefully-hoist`, what it does when enabled is make installed dependencies by other packages be in the root/top-level of the `node_modules` folder so have it accessible for your project and other module dependencies, nowadays nuxt works without enabling `--shamefully-hoist` but it means that you may need to install more dependencies explicitly your projects and more when installing modules or other packages.

You can read about it here

https://github.com/nuxt/nuxt/issues/14146#issuecomment-1767243568

#14146

**Comment by xh4528** [comment]
> Is this resolved if you add `vue-router` as a dependency?如果添加`vue-router`作为依赖项，这个问题是否可以解决？

Thanks, it solved my problem
