### ISSUE TITLE
Nuxt ui datepicker component freezing issue

### ISSUE THREAD

**Issue by Ahmed-Assaf** [nuxt/nuxt#28243]
### Environment

npm nuxi info

### Reproduction

[link to issue](https://stackblitz.com/edit/github-jeyslg?file=app.vue,package.json,pages%2Findex.vue)

### Describe the bug

the datepicker component freezes when i try to use it in the site

**Comment by danielroe** [comment]
Would you raise this on https://github.com/nuxt/ui instead? 🙏
