### ISSUE TITLE
defineModel behavior for `ref` arrays differs from plain Vue

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt#28240]
### Environment

Stackblitz

### Reproduction

1. Open [Vue Playground Link](https://play.vuejs.org/#eNp9U1tP2zAU/itHfmk6lRQoT12pxrY+MImLBtsLRlOanBSDY2eOXYqq/PcdO2nacakURcc+1+87n9fsrCzjpUM2ZpMqNaK0UKF15ZQrUZTaWFiDwXwAz4lNH2Z5jqmFGnKjC+hRXq+Lu3j5pslSqGzrjoc7d74JBXOValVZsFjZM2Pg1FeP7tYgsjEcQT2gft483pqjrXkC9X2fq51ZoqgPp1PwRbXEWOpF1JaOl4l0OIDe1a/bm/Pvs16fMifDBiTBo4PFopSJRToBTHYBLA8KnaEc+1oHiTGnnLVlOYMhxU+GXTIbsFc4X5MJMlELX6LibJfYjzj9zJV9KRFuqeXV/JFIauArV8zRQP2WxAxzofDCzzxps+7up1Gvjeh5Ag3+dcIg1bHGIdREB1e5U6kVWoErMwJDscnLTGJBSCKhMlxtug5AqFyP4ToxViRdl2kf1p69/0i/C5n3fm7vA4jj+L2AQef1tcOJsNG3AZjh3C1++wyq1Wz6nTmPN/K4SOxDnEutTRRMk6hMF5T36ejwsN8ifiueMOQ+BZ1fNgKivdT+t09FmVgGg8y5s5aY/ZJKkT7R+rdoggx8DMANktrCXZM0bLJa/3rdLbkmXry/abCjP65IgbYiALlYxI+VVqS/gImzlGQpJJqr0i+Z5DferISzREr9/CPceUG0y6CcB0yf3rl/rFb+jrNrgxWaJaHofDYxC7SNe3ZziSuyOyc9JScpeo/zJxL5zs/YhH11KqOxd+LCtOfh5Qi1uK1mK4uq2oDygwb5hHjO6BX5F/kR9O24o3i0kR2x+GeJxtckAkfxSTwasfof0HG4/Q==)
2. Click on "Set value"
3. Check the console and see that watchEffect was triggered ("outside" and "inside")

Now with Nuxt 🙈 

1. Open the [Stackblitz](https://stackblitz.com/edit/nuxt-issues-28240)
2. Click on "Set Value"
3. Check the console -> watchEffect **was not triggered**, neither "outside" nor "inside"

### Describe the bug

I am not sure why the behavior is different than in plain Vue but somehow, even with `ssr: false`, the update event of `defineModel` is never fired when using an array ref as value and modifying an element of the array.

### Additional context

using `watch` + `deep` (in either inside or outside) will trigger properly.

**Comment by huang-julien** [comment]
Do you think this could be an issue with Vue ssr ?

**Comment by manniL** [comment]
@huang-julien SSR is disabled in the example, so I would think no.

**Comment by danielroe** [comment]
Would you see if you can reproduce this in pure Vue SSR without Nuxt ([reproduction sandbox](https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter)), and if so, raise [there](https://github.com/vuejs/core/issues/new/choose)? 🙏

**Comment by manniL** [comment]
So weird. It is not related to vue ssr but plain vue. the vue playground is working though 🙈 

Tracking in https://github.com/vuejs/core/issues/11420
