### ISSUE TITLE
TAR_BAD_ARCHIVE giget

### ISSUE THREAD

**Issue by fouss** [nuxt/nuxt#28258]
### Environment

- Operating System: Darwin
- Node Version:     v20.9.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.5.0
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

run `pnpm build/dev` command with an extented layer (at least from gitlab)

### Describe the bug

the command fail after ~3sec with this error TAR_BAD_ARCHIVE: Unrecognized archive format.
Everything was working well on friday, nothing change on any project this weekend but we cannot run the project anymore.
It's ok when i remove the layer (but it's my UI lib so the project is broken)

### Logs

```shell-script
ERROR  TAR_BAD_ARCHIVE: Unrecognized archive format

at Unpack.warn (node_modules/.pnpm/tar@6.2.1/node_modules/tar/lib/warn-mixin.js:21:40)
at Unpack.warn (node_modules/.pnpm/tar@6.2.1/node_modules/tar/lib/unpack.js:236:18)
at Unpack.<anonymous> (node_modules/.pnpm/tar@6.2.1/node_modules/tar/lib/parse.js:83:14)
at Unpack.emit (node:events:526:35)
at [emit] (node_modules/.pnpm/tar@6.2.1/node_modules/tar/lib/parse.js:313:12)
at [maybeEnd] (node_modules/.pnpm/tar@6.2.1/node_modules/tar/lib/parse.js:468:17)
at [consumeChunk] (node_modules/.pnpm/tar@6.2.1/node_modules/tar/lib/parse.js:500:21)
at Unpack.write (node_modules/.pnpm/tar@6.2.1/node_modules/tar/lib/parse.js:427:25)
at Unpack.end (node_modules/.pnpm/tar@6.2.1/node_modules/tar/lib/parse.js:548:14)
at Pipe.end (node_modules/.pnpm/minipass@3.3.6/node_modules/minipass/index.js:75:17) 

 ERROR  TAR_BAD_ARCHIVE: Unrecognized archive format 

 ELIFECYCLE  Command failed with exit code 1.

 Tasks:    0 successful, 1 total
Cached:    0 cached, 1 total
  Time:    2.828s 
Failed:    @website/www#build
```

**Comment by simon-kramer** [comment]
I got the exact same issue whilst trying to extend a layer from a private gitlab instance (added giget & the corresponding .env to resolve the domain) but it runs into the same error.


I do use `// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: '2024-04-03',
  devtools: { enabled: true },
      extends: ['gitlab:project/layer/ui', { auth: process.env.GITHUB_TOKEN, install: true }],
})`


.env:
`GITLAB_TOKEN=my_token
GIGET_GITLAB_URL=git@my.project.domain`

**Comment by danielroe** [comment]
Would you see if you can raise upstream at https://github.com/unjs/giget? 🙏

**Comment by simon-kramer** [comment]
Is there an update on this one?

**Comment by moleCuleFFF** [comment]
+1 This is an issue for us, using group/subgroup

**Comment by simon-kramer** [comment]
Is ther an update on this issue?

**Comment by moleCuleFFF** [comment]
@simon-kramer I fixed this issue by passing the ref on the end of the URL after the hash.
` extends: [['gitlab:publishing/nuxt3-skeleton-app/app/webapp#master', { auth: process.env.GIGET_AUTH, install: true }]],`

**Comment by danielroe** [comment]
Closing - this should be tracked in https://github.com/unjs/giget if you're still experiencing it, with a reproduction 🙏
