### ISSUE TITLE
Incrementing/Repeated Routes (?)

### ISSUE THREAD

**Issue by phuze** [nuxt/nuxt#28267]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.11.1
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      compatibilityDate, devtools, devServer, app, build, css, sourcemap, cssSourceMap, alias, modules, routeRules, hooks, auth, i18n, googleFonts, primevue, runtimeConfig

### Reproduction

https://stackblitz.com/edit/github-ym6g3r?file=pages%2Fapple.vue

Open the console.

As you continue to click the Forward and Back button in the app, notice that the `window.confirm` dialog will incrementally fire multiple times, requiring multiple clicks.

### Describe the bug

I'm not entirely sure how to properly describe this, other than to suggest its best that you just look at the example.

I am attempting to implement a route guard, with the idea of prompting a user whether they want to save their work, before leaving a page.

Every subsequent action taken, increasingly triggers additional dialogs. Logging the route param `from`, reflects the increasing number of clicks required before a route change occurs.

The more the user navigates throughout the app, the more dialogs they are presented with.

This was occurring in Nuxt 3.12.3 and continued in 3.12.4 after I updated.

![image](https://github.com/user-attachments/assets/bcb6f254-c6d8-4f1c-918a-98e424acc19c)

**Comment by phuze** [comment]
While I still feel like the above example is a bug, I was able to successfully implement a route guard by relying on onBeforeRouteLeave and a promise.

```js
const saveBeforeExit = () => {
  return new Promise((resolve, reject) => {
    const answer = window.confirm('Do you really want to leave?');
    if (!answer) {
      resolve(false)
    }
    resolve(true)
  })
}

onBeforeRouteLeave(async (to, from) => {
  if(from.path === '/apple') {
    const userConfirmed = await saveBeforeExit()
    if (userConfirmed) {
      return true
    } else {
      return false
    }
  } else {
    return true
  }
})
```

**Comment by danielroe** [comment]
It's not a bug. By adding `router.beforeEach` you are registering an additional guard on every page that's loaded so this is expected behaviour.

Instead, you can use `onBeforeRouteLeave` or clean up your guard with `onBeforeUnmount` (I believe `router.beforeEach` returns an 'unsubscribe' function you can call to do so).
