### ISSUE TITLE
Can't call the same composable that using a composable that require nuxt instance in same function

### ISSUE THREAD

**Issue by Necrometal** [nuxt/nuxt#28272]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.14.0
- Nuxt Version:     3.12.3
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.5.0
- Builder:          -
- User Config:      compatibilityDate, app, pages, devtools, modules, pinia, eslint, primevue, css, runtimeConfig, colorMode
- Runtime Modules:  @nuxtjs/tailwindcss@6.12.1, @pinia/nuxt@0.5.1, @nuxt/eslint@0.3.13, @primevue/nuxt-module@4.0.0, @vueuse/nuxt@10.11.0, @vee-validate/nuxt@4.13.2, @nuxtjs/color-mode@3.4.2, @hebilicious/vue-query-nuxt@0.3.0
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-zkcgqh?file=nuxt.config.ts,composables%2FuseApi.ts,middleware%2Fauth.ts,utils%2FcheckAuth.ts

### Describe the bug

I created a custom fetch as composables `useApi` , this composable use `useRuntimeConfig` to get the public build runtime config.
i have a function utils that need to use this composable, when calling the composable once i have no error but when calling second time i got error 
<span style="color:red">[nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at `https://nuxt.com/docs/guide/concepts/auto-imports#vue-and-nuxt-composables`.</span>
when i try to remove the second call, there is no error.

### Additional context

The context is i want to create a middleware that check the session of user using token, if the token is invalid i got response authenticated : false then i check if refresh token exist to make refresh token api call; so the 2 api call is in the same logic so the check session work but on the refresh token i got the error above

**Comment by danielroe** [comment]
You can use `nuxtApp.runWithContext` for this purpose: https://nuxt.com/docs/api/composables/use-nuxt-app#runwithcontext.

**Comment by Necrometal** [comment]
It work when using `nuxtApp.runWithContext` on each asynchronous call after the first but it spend much effort to set the `nuxtApp.runWithContext` on each call, is there a way to wrap the whole logic inside one `nuxtApp.runWithContext`? Like i have function that make a multiple api call inside then using the runWithContext on the function. I tried to set it on my main function but it not work.
