### ISSUE TITLE
Cannot read properties of null (reading 'parentNode') when navigate from page

### ISSUE THREAD

**Issue by zzpmaster** [nuxt/nuxt#28274]
### Environment

- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-ax2aaa

### Describe the bug

When using NuxtLink to navigate from the root component to another page, a TypeError: Cannot read properties of null (reading 'parentNode') error occurs. This bug appeared after Vue version 3.4.32.

#### Conditions Triggering the Bug:

The error occurs when a Teleport component does not have a v-if condition for mounting. During page navigation, if Teleport is used without a v-if condition, the error is triggered.

#### Conditions Not Triggering the Bug:

The error does not occur if a v-if condition is added to the Teleport component.

The issue seems to be caused by a change introduced in Vue version 3.4.32, where hostRemove(targetStart!) was added. This can be referenced in the following commit: [Commit 8655ced](https://github.com/vuejs/core/commit/8655ced480ea0fe453ff5fe445cecf97b91ec260#diff-030bd876734dc84e37752a562874250fd76eb083242b96a7774adb7a44f77872R275).

**Comment by signor-pedro** [comment]
Same issue here, but in different setup.

In our case, navigation is broken when:
- page uses explicit `<NuxtLayout>` with `definePageMeta({ layout: false })`
- layout uses [Nuxt UI's Notification](https://ui.nuxt.com/components/notification)

When the `<UNotifications>` component is commented out, everything works again.

**Comment by signor-pedro** [comment]
Reproducer: https://stackblitz.com/edit/github-nshmnk?file=layouts%2Fdefault.vue

**Comment by huang-julien** [comment]
Hello :wave: thanks for reporting this issue. I think 3.4.31 also has this issue. Can you try to set the version of vue to 3.4.30 with the `resolutions` (or `overrides` with npm) field in your package.json ?

Do you think you'll be able to reproduce it with pure vue or vue ssr ? I think mixing it with Suspense should be enough to reproduce it.

**Comment by urbgimtam** [comment]
Was suffering the exact same thing on various updated projects. Vue 3.4.31 does not trigger the issue for me, only 3.4.32 and 3.4.33. Adding a condition to <Teleport> component fixed the issue.

**Comment by MarioC3** [comment]
@huang-julien In our case, adding resolutions for vue 3.4.29 fixed the issue.

**Comment by danielroe** [comment]
This seems almost certainly to be a Vue issue therefore.

Would you see if you can reproduce this in pure Vue SSR without Nuxt ([reproduction sandbox](https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter)), and if so, raise [there](https://github.com/vuejs/core/issues/new/choose)? 🙏

**Comment by zzpmaster** [comment]
@huang-julien @urbgimtam Yes, this issue only occurs in versions 3.4.32 and 3.4.33.

**Comment by zzpmaster** [comment]
@MarioC3 This method works for me only under `nuxi dev`. Although it compiles successfully with `nuxi build`, a 500 error occurs when accessing it.

**Comment by sumomo015** [comment]
This might be the same issue.
https://github.com/vuejs/core/issues/11400

**Comment by danielroe** [comment]
Let's track there 🙏
