### ISSUE TITLE
module get `modulepreload` despite dynamic import

### ISSUE THREAD

**Issue by andrewspy** [nuxt/nuxt#28283]
### Environment

Stackblitz
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.3
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      compatibilityDate, devtools, vite
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-preloaded-dynamic-import?file=pages%2Findex.vue

### Describe the bug

I'm trying to conditionally dynamic import `firebase-auth` module in Nuxt 3, however the build always `modulepreload` `firebase-auth` despite dynamic import, sample code below:

```js
onMounted(async () => {
  if (Math.random() > 100) {
    // never reach here
    const { getAuth } = await import('firebase/auth')

    console.log('getAuth() imported')
  }
})
```

I don't expect the `firebase-auth` to `modulepreload` as the `if` statement will never be reached.

I have also split the firebase chunks accordingly into:

- `vendor_firebase_app`
- `vendor_firebase_auth`
- `vendor_firebase_firestore`

Which are `modulepreload` on SSR despite dynamic import without reaching the called function.

### Additional context

It may be related to #18376 which I have posted there, but I am unsure if `modulepreload` and `prefetch` is the same issue, and hope to clear up the confusion with a clean reproduction.

### Logs

```shell-script
SSR page with `modulepreload` for firebase auth/firestore module

<link rel="modulepreload" as="script" crossorigin href="/_nuxt/entry.CAE70tCN.js">
<link rel="modulepreload" as="script" crossorigin href="/_nuxt/vendor_firebase_auth.BfwJ_nJi.js">
<link rel="modulepreload" as="script" crossorigin href="/_nuxt/vendor_firebase_app.DLRcA3jR.js">
<link rel="modulepreload" as="script" crossorigin href="/_nuxt/vendor_firebase_firestore.OkGLP7SR.js">
<link rel="modulepreload" as="script" crossorigin href="/_nuxt/index.EmvhLKRK.js">
<link rel="prefetch" as="script" crossorigin href="/_nuxt/error-404.CmQPSeHd.js">
<link rel="prefetch" as="script" crossorigin href="/_nuxt/vue.f36acd1f.B0hSbiN_.js">
<link rel="prefetch" as="script" crossorigin href="/_nuxt/error-500.D8pDP7U-.js">
```

**Comment by andrewspy** [comment]
After trying with some older versions of Nuxt, the problem started to appear with Nuxt v3.9.x when it used Vite 5 and Rollup 4 under the hood.

Does anyone know what has changed under the hood that causes the different build behavior?

**Comment by mseeley** [comment]
@andrewspy do you see this when running on the dev server and when running a dist build?

**Comment by andrewspy** [comment]
@mseeley I see this after the `npm run build`  and `npm run preview`. It has nothing to do with dev server.

**Comment by andrewspy** [comment]
Resolved in https://github.com/vitejs/vite/issues/17936.
