### ISSUE TITLE
On redirection with NuxtLink pageLayout is not set that is defined in definePageMeta

### ISSUE THREAD

**Issue by bippan1407** [nuxt/nuxt#28282]
### Environment

- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.10.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  @pinia/nuxt@0.5.1, @nuxtjs/tailwindcss@6.11.3
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-wgg4gm-my7nhi?file=pages%2Fproduct.vue

1. Go to index page reload the page
2. Click on Go To Product page
3. Layout that should be used on Product page is product-layout but used is initial-layout
4. Reload the page Product layout is now used on product page.

By default product-layout should be used on product page.

### Describe the bug

Layout set on definePageLayout is not set by default

**Comment by Krutie** [comment]
`setPageLayout` is a Nuxt util and it relies on Nuxt context to work properly. So, `onMounted` is not the right place for it to work as expected. 

Recommended places for `setPageLayout` are either Nuxt plugins or Nuxt Route Middleware. 
 

```js
<script setup>
onMounted(() => {
  // Remove setPageLayout from here
  // setPageLayout('initial');
});

definePageMeta({
  middleware: [
    function (to, from) {
      // Use Nuxt route middleware instead
      setPageLayout('initial');
    },
  ],
});
</script>
```

Here's your forked Stackblitz in action: https://stackblitz.com/edit/github-wgg4gm-jq9qss?file=pages%2Findex.vue 

Reference: https://nuxt.com/docs/api/utils/set-page-layout

**Comment by bippan1407** [comment]
@Krutie Thanks for the answer, I have read the documentation 

Based on my requirements will go with

```
useNuxtApp().runWithContext(() => {
    setPageLayout('initial');
  });
```

**Comment by bippan1407** [comment]
I have one doubt since nuxt context is not available after onMounted, so if I change setPageLayout on  onClick Action without using runWithContext is it possible that nuxt context is still not available?

I have changed the code to understand how does setPageLayout works and in some cases it does not work as expected

When clicked on 'Change layout to product layout' layout does not change to product-layout

https://stackblitz.com/edit/github-wgg4gm-ihphsl?file=middleware%2Fauth.ts,pages%2Findex.vue%3AL18,pages%2Fproduct.vue

docs -> [Change layout to product layout](https://nuxt.com/docs/guide/directory-structure/layouts#changing-the-layout-dynamically)

@Krutie
