### ISSUE TITLE
"Unexpected token ';'" error when running the build.

### ISSUE THREAD

**Issue by vinoddotcom** [nuxt/nuxt#28293]
### Environment

Operating System: ubuntu 22.04 
Node Version: v20.12.2
Nuxt Version: 3.12.4
CLI Version: 3.12.0
Nitro Version: 2.9.7
Package Manager: npm@10.5.0

### Reproduction

Minimal Reproduction: https://stackblitz.com/edit/github-tmvhj9?file=package.json
1. `npm run clear-cache`
2. `npm run build`
3. `npm run preview`

![Screenshot from 2024-07-24 13-41-42](https://github.com/user-attachments/assets/232a25cf-d781-4cf0-838e-928c5f30542e)
![Screenshot from 2024-07-24 13-42-28](https://github.com/user-attachments/assets/1def3160-2344-42b9-ab64-b4d57ffb6078)

### Describe the bug

While using Pinia with Nuxt, the production build throws an error: 'nuxt] [request error] [unhandled] [500] Unexpected token ';''. 

Upon investigation, I found the error in .output/server/chunks/build/server.mjs.

However, I tried to fix the problem by downgrading packages using vite@5.31, nuxt/vite-builder@3.12.2, nuxt@3.12.2 and nuxt/kit@3.12.0. Unfortunately, I was unable to resolve the issue.

### Logs

```shell-script
[nuxt] [request error] [unhandled] [500] Unexpected token ';'
  at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:168:18)  
  at callTranslator (node:internal/modules/esm/loader:279:14)  
  at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:285:30)  
  at async link (node:internal/modules/esm/module_job:78:21)
[nuxt] [request error] [unhandled] [500] Unexpected token ';'
  at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:168:18)  
  at callTranslator (node:internal/modules/esm/loader:279:14)  
  at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:285:30)  
  at async link (node:internal/modules/esm/module_job:78:21)
```

**Comment by vinoddotcom** [comment]
The issue was resolved by updating pinia @2.1.7 to @2.1.8-beta.0.

**Comment by danielroe** [comment]
Given that this seems tied to a pinia version, would you raise an issue and reproduction in  that repo? 🙏

**Comment by atomiomi** [comment]
Getting the same error after upgrading from nuxt@3.12.3 to nuxt@3.12.4
Don't have pinia connected though

**Comment by gsperk** [comment]
I added rollup 4.18.1 to my resolutions after upgrade to nuxt 3.12.4 to work around this build error
Unexpected token punc «;», expected punc «,»

**Comment by LorenzoRottigni** [comment]
Hello guys! I have the same problem :( any suggestion?

**Comment by LorenzoRottigni** [comment]
I actually only have "@pinia/nuxt": "^0.5.1",

**Comment by LorenzoRottigni** [comment]
Would you please provide a package.json with the issue fixed / worked around?

**Comment by LorenzoRottigni** [comment]
Adding pinia@2.1.8-beta.0 works... It's already a good point that you found this solution! Do you think it's going to be marked as stable that pinia version?

**Comment by wattanx** [comment]
The latest version of pinia seems to have solved this problem.
https://stackblitz.com/edit/github-tmvhj9-cmdfks
