### ISSUE TITLE
How client component use data from server component?

### ISSUE THREAD

**Issue by linpengteng** [nuxt/nuxt#28290]
### Describe the feature

When I use the following components, I find that the client component cannot use the data rendered by the server component

```vue
// Comp.server.vue
<template>
  <div>
    Render from Server: {{ date }}
  </div>
</template>

<script setup lang="ts">
const date = ref(Date.now())
</script>
```

```vue
// Comp.client.vue
<template>
  <div>
    Render from Client: {{ date }}
  </div>
</template>

<script setup lang="ts">
const date = ref(Date.now())
</script>
```

When I try to use the useState or useAsyncData APIs, they seem to work as expected:

```vue
// Comp.server.vue
<template>
  <div>
    Render from Server: {{ date }}
  </div>
</template>

<script setup lang="ts">
const date = useState('date', Date.now())
</script>
```

```vue
// Comp.client.vue
<template>
  <div>
    Render from Client: {{ date }}
  </div>
</template>

<script setup lang="ts">
const date = useState('date', Date.now())
</script>
```

But there is a serious problem. When I reuse the same Comp component in a page, the `date` data is shared, while the key defined in useState is global. This is not what I want. How can I ensure that when the Comp component is initialized, only the client component in this instance obtains and uses the server component data in this instance?

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by huang-julien** [comment]
Hello :wave: client components and server components are completly isolated from each other. You can't share data between them due to the hydration process as the client component can't retrieve the server side data. 

Using `useState` IS the solution.
