### ISSUE TITLE
propsDestructure no longer working 

### ISSUE THREAD

**Issue by yassilah** [nuxt/nuxt#28295]
### Environment

- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      compatibilityDate, devtools, vue
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-g3udp4?file=nuxt.config.ts

### Describe the bug

Since [@vitejs/plugin-vue](https://github.com/vitejs/vite-plugin-vue/blob/main/packages/plugin-vue)@5.1.0 the `propsDestructure` option should be set inside a `features` flag (see [changelog](https://github.com/vitejs/vite-plugin-vue/blob/plugin-vue@5.1.0/packages/plugin-vue/CHANGELOG.md#510-2024-07-23)) and therefore doesn't work anymore in Nuxt by setting `vue.propsDestructure: true`. I'll make a PR.

**Comment by danielroe** [comment]
Thank you! 🙏

**Comment by danielroe** [comment]
Note: this seems like a breaking change and should probably be raised in the vite-plugin-Vue repo too 🙏

**Comment by ivomarsan** [comment]
> Note: this seems like a breaking change and should probably be raised in the vite-plugin-Vue repo too 🙏

I'm using 3.12.0 to avoid this problem for now

**Comment by danielroe** [comment]
Instead, just pin your version of vite-plugin-vue.

**Comment by ivomarsan** [comment]
> Instead, just pin your version of vite-plugin-vue, or configure vite.vue in line with the new options.

Could you help me with this? I've just using 
```
  vite: {
    vue: {
      script: {
        defineModel: true,
        propsDestructure: true,
      },
    },
  }
```

**Comment by RyoOhno** [comment]
This is a machine translation of deepl's translation.
Sorry if it's hard to understand.

The contents of the propsDestructure setting in nuxt.config.ts when using @vitejs/plugin-vue@5.1.0.
script
Change “script” to “features” and it will work.


  vite: {
    vue: {
      features: {
        propsDestructure: true,
      }
    }    
  },
