### ISSUE TITLE
When running pnpm dev, Unable to automatically get environment variables from `.env.local` and `.env.development`

### ISSUE THREAD

**Issue by linpengteng** [nuxt/nuxt#28309]
### Environment

- Operating System: Darwin
- Node Version:     v22.0.0
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.6.0
- Builder:          -
- User Config:      future, modules, hub, ui, eslint, devtools
- Runtime Modules:  nuxt-auth-utils@0.1.0, @nuxthub/core@0.7.0, @nuxt/eslint@0.3.13, @nuxt/ui@2.17.0
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-fhawmu?file=.env.development

<img width="1910" alt="image" src="https://github.com/user-attachments/assets/b8348784-34cb-4104-9d32-c4d29c1381e4">

### Describe the bug

When running pnpm dev , I found that useRuntimeConfig() can get environment variables from `.env` environment configuration, but cannot get environment variables from `.env.local` and `.env.development`.. 
I need help, Thanks!

**Comment by gokhantaskan** [comment]
Have you tried `pnpm dev --dotenv development`? You can also apply it to the build and preview commands for local testing.

**Comment by linpengteng** [comment]
I tried running pnpm dev --dotenv .env.development, and was able to get variables from the .env.development environment configuration file. However, since it needs to be specified manually, it cannot be automatically obtained from the following environment configuration file (high -> low), which is a bit troublesome. Will it be supported in the future?

eg. pnpm dev

.env.development.local
.env.development
.env.local
.env
