### ISSUE TITLE
Allow `baseURL` with relative path in `nuxt.config.ts`

### ISSUE THREAD

**Issue by HuakunShen** [nuxt/nuxt#28310]
### Describe the feature

vite config supports `base: "./"`

The resulting html is like this. 

```html
<script type="module" crossorigin src="./assets/index-CgobQE0i.js"></script>
<link rel="stylesheet" crossorigin href="./assets/index-yVtaL3pq.css">
```

In nuxt config, using a relative path doesn't work. 
In some circumstances I don't know the url prefix, a relative path is helpful.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by xjccc** [comment]
Something Like this? https://github.com/nuxt/nuxt/issues/28474
