### ISSUE TITLE
Hydration error if <ul> or <ol> is within a <p> block 

### ISSUE THREAD

**Issue by joerosenthal** [nuxt/nuxt#28325]
### Environment

- Operating System: Darwin
- Node Version:     v20.11.1
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.8.2
- Builder:          -
- User Config:      compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

I was able to reproduce this issue with a clean nuxt install, and I've put it in a public repository. You can find the hydration error in app.vue: https://github.com/joerosenthal/ul-ol-p-bug

### Describe the bug

If I have a `<p>` with a `<ul>` or `<ol>` inside it, I get hydration errors. The hydration errors end if I move the list outside of the paragraph block. 

### Additional context

I've reproduced this bug with a clean nuxt install, but I was unable to reproduce this with just a clean vue install on its own. As far as I understand it, `<ul>` and `<ol>` are able to be inside `<p>` as per HTML5, and I don't remember this being an issue with my production site in the past. This was also occurring on my production site, so I've just removed the surrounding `<p>`—easy enough fix once I had an idea of what the problem was, but that was a bear to track down on a relatively large codebase. Something like this wouldn't be my first guess as the source of a hydration issue.

Also, it's worth noting, this issue persisted in production after a nuxt generate on my website, so this isn't just an issue with nuxi dev.

**Comment by huang-julien** [comment]
Hello :wave: this is not a bug. You can reproduce it with Vue SSR. 
When rendering HTML, browsers strips or tries to fix invalid HTML, resulting in the hydration issue you encountered

**Comment by Matthi0uw** [comment]
I have same issue since I update my project to Nuxt3.

Why in Nuxt2 there is no problem ?

**Comment by huang-julien** [comment]
There was probably some changes in your project during your nuxt 3 upgrade. This is also a normal behavior in nuxt 2
