### ISSUE TITLE
The props of `PublicRuntimeConfig` are inferred as `unknown`

### ISSUE THREAD

**Issue by KazariEX** [nuxt/nuxt#28332]
### Environment

- Operating System: Windows_NT
- Node Version:     v22.0.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.6.0
- Builder:          -
- User Config:      runtimeConfig
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://github.com/KazariEX/nuxt-minimal

### Describe the bug

When I write the following code somewhere in the application:

```ts
declare module "@nuxt/schema" {
    interface PublicRuntimeConfig {}
}
```

all properties under `runtimeConfig` will be overridden by this interface instead of being extended.

### Additional context

I understand that doing this in isolation doesn't make sense, but when I import the `ModuleOptions` type from `@nuxtjs/robots`, the `dist/types.d.ts` file from that package will be included, which contains the aforementioned code, causing all my `runtimeConfig.public` types to be lost.

I'm not sure what the issue is, but I hope to learn how to prevent type loss.

**Comment by ThibaultVlacich** [comment]
I have this issue also. I noticed that changing `declare module 'nuxt/schema' {` by `declare module '@nuxt/schema' {` in `.nuxt/types/schema.d.ts` fixes the issue (but obviously it gets overridden every time there's a change)

I'll be honest, I'm highly confused as why there's `nuxt/schema` and `@nuxt/schema` in the same file, and I think TypeScript is also very confused.

**Comment by danielroe** [comment]
With the latest module builder, we now no longer emit those types with both `nuxt/schema` and `@nuxt/schema`. Modules should only ever touch/author `@nuxt/schema`. Users can use `nuxt/schema` as a shorthand.

Some actions (if not specified, we need to update `@nuxt/module-builder` and release):

- [x] `@nuxt/telemetry`
- [ ] `nuxt-csurf`
- [ ] `nuxt-security`
- [ ] `@nuxtjs/i18n`

**Comment by BobbieGoede** [comment]
>@nuxtjs/i18n: https://github.com/nuxt-modules/i18n/pull/3071 but may need to be backported to v8 (cc: @BobbieGoede)

This was backported in `v8.5.1` so if anyone is experiencing issues, make sure to check if you have updated `@nuxtjs/i18n` to `v8.5.1` or higher!

**Comment by danielroe** [comment]
The reproduction is no longer reachable, and I think this has now been resolved in upstream modules.

If this is is still reproducible for you, let me know and I'll happily reopen.
