### ISSUE TITLE
Deleting cookies `useCookie` does not work in components if you pass `null`

### ISSUE THREAD

**Issue by yesworld** [nuxt/nuxt#28343]
### Environment

- Operating System: Darwin
- Node Version:     v20.11.1
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@8.19.2
- Builder:          -
- User Config:      compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://github.com/yesworld/reproduce-issue-cookie-test

uncomment and comment out these lines..
- https://github.com/yesworld/reproduce-issue-cookie-test/blob/main/composables/useBanner.ts#L7
- https://github.com/yesworld/reproduce-issue-cookie-test/blob/main/composables/useBanner.ts#L16

### Describe the bug

If you delete cookies using `null`, nothing changes in the components `<CompA />` and `<CompB />`.
https://github.com/yesworld/reproduce-issue-cookie-test/blob/main/composables/useBanner.ts#L7
```js
    token.value = null // doesn't work
```

If you delete using an empty string `''`, everything works fine.
https://github.com/yesworld/reproduce-issue-cookie-test/blob/main/composables/useBanner.ts#L8
```js
    token.value = '' // it works!
```

**Comment by TimGuendel** [comment]
+1, thanks. This is a regression, it used to work before.
