### ISSUE TITLE
NuxtClientFallback renders fallback for all components if one failed, after hydration

### ISSUE THREAD

**Issue by timhn-bm** [nuxt/nuxt#28344]
### Environment

- Operating System: Linux
- Node Version:     v20.11.1
- Nuxt Version:     3.10.3
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  yarn@4.2.1
- Builder:          -
- User Config:      devtools, experimental
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://github.com/timhn-bm/nuxt-client-fallback-errors

I've added 2 pages
- `/works` - not using the `ErrorBoundary` wrapper: it behaves correctly :heavy_check_mark: 
- `/bugs` - using the `ErrorBoundary` wrapper: it reproduces the bug :red_circle: 

### Describe the bug

When building a wrapper around `NuxtClientFallback` and using it is used in multiple places on one page, given that one wrapped component throws an error, then all instances of `NuxtClientFallback` will display the `fallback` slot **only after hydration**

### Additional context

I want to build a wrapper component around `NuxtClientFallback`.

The wrapper - let's call it `ErrorBoundary` - can look like this in its simplest form

```
<template>
  <NuxtClientFallback :keep-fallback="true">
    <slot> </slot>

    <template #fallback>
      <div style="background: red; color: white; padding: 10px">
        <slot name="error"> </slot>
      </div>
    </template>
  </NuxtClientFallback>
</template>
```

If I create a page with the following template: `A` `B` and `C` are wrapped by my custom `ErrorBoundary`.

If `A` throws an error -> after hydration, then the error slot will also by displayed for `B` and `C`

```
<template>
  <div >
    <ErrorBoundary>
      <A /> --> only A will throw an error 
      <template #error> an error occurred in A </template>
    </ErrorBoundary>

    <ErrorBoundary>
      <B />
      <template #error> an error occurred in B </template>
    </ErrorBoundary>

    <ErrorBoundary>
      <C />
      <template #error>
        <div>an error occurred in C</div>
      </template>
    </ErrorBoundary>
  </div>
</template>
```

The very weird this, is that if I use directly `NuxtClientFallback` instead of my wrapper `ErrorBoundary`, then everything behaves as expected.

Thanks for your help in advance !

**Comment by huang-julien** [comment]
Hey :wave: thanks for opening the issue !

You repo seems to be private, you can also use stackblitz to avoid having to create a repo in your gh

**Comment by timhn-bm** [comment]
Sorry, I had missed your message! 

I just changed it to public. Weirdly, I had issues creating a reproducible stackblitz :/ Let me know if you prefer me to create a StackBlitz instead of a git repo before looking into this, thanks :)

**Comment by linpengteng** [comment]
I also encountered the same problem

**Comment by timhn-bm** [comment]
Hey @huang-julien , my bad this issue completely went over my head.

I've been able to have a reproducible Stackblitz. I believe the issue only arises when using `NuxtClientFallback` inside a component that's inside a `v-for`

See the Stackblitz: https://stackblitz.com/edit/github-tdwwxv-i95loe

**Comment by huang-julien** [comment]
We inject the uid at build time; It's probably worth migrating this old code to runtime useId

**Comment by timhn-bm** [comment]
Got it, thanks for the answer👍
