### ISSUE TITLE
Option to Build Backend Only

### ISSUE THREAD

**Issue by dahjson** [nuxt/nuxt#28345]
### Describe the feature

Include an option to build only the backend part of the application. Currently, the `nuxt generate` command generates a static site, which does not include the backend server. However, in many scenarios, developers might want to build and deploy just the backend part of the application if using `nuxt generate` for the frontend. Adding an option to build only the backend part of the application will greatly enhance the flexibility and efficiency of using Nuxt in various development and deployment scenarios. Could be a command like `nuxt build:backend` or something similar.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by huang-julien** [comment]
Hey :wave: 

Do you mean build the nitro server ? Or a server to serve the generated SPA ?

**Comment by dahjson** [comment]
I'm thinking it would just be anything dependent on the Nitro server. When I use `nuxt generate` the only thing that seems to be missing is what I have in my `server` folder. I'm not totally sure if that's the case though.

**Comment by dahjson** [comment]
It would also be nice if I could just combine what you get from `nuxt generate` (doesn't currently include the backend Nitro server) with only the server part of what you get from `nuxt build` into a single command.

**Comment by huang-julien** [comment]
That's because the generate command only generate static files to be send on any hotsing environement. We leave the choice of hosting to users. 

At the end of the generate command, we also log `You can preview this build using npx serve .output/public` and `You can now deploy .output/public to any static hosting!`

**Comment by dahjson** [comment]
Yes, I know that. However, I use a combination of static files and server files. I prefer the static build because of speed, better SEO, and cheaper server costs. However, I still need to run the backend server, but only for API calls only. There is currently not a way to build for this type of setup with a single command.

**Comment by huang-julien** [comment]
Maybe are you looking for the `prerender` boolean in the `routeRules` config intead ?

**Comment by fanckush** [comment]
@huang-julien I have a nuxt app (with `ssr: false`) where I want to deploy the backend (nitro part aka: `server/`) separately.

For context, the frontend part of this nuxt project is an ionic mobile app which should not be hosted at all. is such a thing possible?
