### ISSUE TITLE
remove __NUXT_DATA__ with ssr true from html page 

### ISSUE THREAD

**Issue by basemwewebit** [nuxt/nuxt#28355]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.15.1
- Nuxt Version:     3.12.1
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  npm@10.7.0
- Builder:          -
- User Config:      devtools, ssr, telemetry, debug, runtimeConfig, modules, delayHydration, render, auth, sitemap, i18n, postcss, app, facebook, gtm, gtag, robots, routeRules, nitro
- Runtime Modules:  @vueuse/nuxt@10.11.0, @nuxt/image@1.7.0, nuxt-icon@0.6.10, @nuxtjs/i18n@8.3.1, nuxt-swiper@1.2.2, @pinia/nuxt@0.5.1, nuxt-anchorscroll@1.0.3, nuxt-jsonld@2.0.8, nuxt3-meta-pixel@1.0.9, nuxt-gtag@1.2.1, @zadigetvoltaire/nuxt-gtm@0.0.13, @nuxtjs/sitemap@5.2.0, @nuxtjs/robots@3.0.0, @sidebase/nuxt-auth@0.6.7, nuxt-delay-hydration@1.3.3
- Build Modules:    -
------------------------------

### Reproduction

When server-side rendering (SSR) is enabled, the __NUXT_DATA__ section in the HTML should be removed to reduce page size and potentially improve performance.

### Describe the bug

When server-side rendering (SSR) is enabled, the __NUXT_DATA__ section in the HTML should be removed to reduce page size and potentially improve performance.

**Comment by huang-julien** [comment]
Hello __NUXT_DATA__ is used to retrieve the nuxt payload, it is required for hydration step

**Comment by basemwewebit** [comment]
hi @huang-julien, How can I avoid duplicate content when using NUXT_DATA during crawling?

**Comment by tmotyl** [comment]
similar issue https://github.com/nuxt/nuxt/issues/24175
