### ISSUE TITLE
useStorage('assets:server') in Nuxt4

### ISSUE THREAD

**Issue by delta-mind-phofmann** [nuxt/nuxt#28369]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.11.0`
- Nuxt Version:     `3.12.4`
- CLI Version:      `3.12.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `pnpm@9.4.0`
- Builder:          `-`
- User Config:      `future`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Opt into Nuxt4

_/nuxt.config.ts_
```
// nuxt.config.ts
export default defineNuxtConfig({
  future: {
    compatibilityVersion: 4,
  },
})
```

move app.vue into new created app folder with the following contents
_/app/app.vue_
```
<template>
  <pre>
{{ halloFile }}
  </pre>
</template>

<script setup lang="ts">
import halloFile from '~/assets/hallo.json'
</script>
```

create an assets folder with hallo.json
_/app/assets/hallo.json_
```
{
  "hallo": "world client"
}
```

start dev server with

`pnpm run dev`

File is displayed correctly when calling http://localhost:3000

now create a server route

_/server/api/test.get.ts_
```
export default defineEventHandler(async (event) => {
  return await useStorage('assets:server').getItem('hello.json')
})
```

one would expect that the file now is displayed when accessing http://localhost:3000/api/test but it is not - because useStorage does not find the file.

 

### Describe the bug

create an assets folder in the server folder with hallo.json
_/server/assets/hallo.json_
```
{
  "hallo": "world server"
}
```

you can see that this file is displayed. Which makes sense because the server-directory is a nitro domain, but my expected behavior was to see the /app/assets/hallo.json

Thanks for your help!
Patrick

**Comment by fishDev94** [comment]
it doesn't work because you don't configure any key of storage by nuxt.conf:

```js
// nuxt.config.ts

export default defineNuxtConfig({
  nitro: {
    storage: {
      myFileSystem: {
        driver: 'fs',
        base: 'app/assets/',
      },
    },
  },
});
```

on your eventHandler:

```js
// server/api/test.ts

export default defineEventHandler(async (event) => {
    return await useStorage('myFileSystem').getItem('hello.json');
});
```

**Comment by manniL** [comment]
Server assets should be stored in `server/assets/...` and *not* in `app/assets`. As @fishDev94 said, you can use a custom driver if needed.
