### ISSUE TITLE
onMounted lifecycle Hook is broken by the library

### ISSUE THREAD

**Issue by mrc-bsllt** [nuxt/nuxt#28364]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v22.3.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  yarn@1.22.22
- Builder:          -
- User Config:      devtools, app, runtimeConfig, css, modules, eslint, i18n, primevue, image, nuxt-jsonld, mapbox, compatibilityDate
- Runtime Modules:  @nuxt/eslint@0.4.0, @nuxtjs/tailwindcss@6.12.1, @nuxtjs/i18n@8.3.3, @primevue/nuxt-module@4.0.3, @nuxt/image@1.7.0, @nuxtjs/strapi@1.12.0, nuxt-icons@3.2.1, @pinia/nuxt@0.5.2, nuxt-jsonld@2.0.8, nuxt-mapbox@1.6.0
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-csufwc?file=app.vue,pages%2Findex.vue,nuxt.config.ts

### Describe the bug

When nuxt-mapbox is not included within the modules in the nuxt.config.ts file, everything works normally, the onMounted hook is triggered every time I land on the page (or when a component is mounted). But, when I include it in the modules, the onMounted hook is only triggered the first time (it almost seems to be cached).

**Comment by mrc-bsllt** [comment]
Sorry, I made a mistake, I should have opened the issue in the nuxt-mapbox repository :/

**Comment by huang-julien** [comment]
Hello :) 

Could you open this issue in nuxt-mapbox ? 🙏

**Comment by mrc-bsllt** [comment]
> Hello :)
> 
> Could you open this issue in nuxt-mapbox ? 🙏

https://github.com/AlexLavoie42/Nuxt-Mapbox/issues/116
