### ISSUE TITLE
Allow providing custom enable/disable callbacks to `usePreviewMode`

### ISSUE THREAD

**Issue by adamdehaven** [nuxt/nuxt#28370]
### Describe the feature

The current implementation of `usePreviewMode` automatically calls `refreshNuxtData()` when enabling preview mode, as well as binding a `useRouter.afterEach(() => refreshNuxtData())` callback that fires on the next route change.

For apps that do not utilize SSG, or apps that desire custom enable/disable setup or cleanup tasks, the linked PR allows passing in two new callbacks to the composable's options.

I've submitted the functionality as a new PR: https://github.com/nuxt/nuxt/pull/28371

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by natamartinscodedev** [comment]
I'm a frontend but i would be help and learning more about nuxt

**Comment by danielroe** [comment]
resolved in https://github.com/nuxt/nuxt/pull/28371.
