### ISSUE TITLE
Property '$route' does not exist on type

### ISSUE THREAD

**Issue by pdsuwwz** [nuxt/nuxt#28373]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.12.1
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    -
- Package Manager:  pnpm@9.1.4
- Builder:          -
- User Config:      compatibilityDate, devServer, devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/pdsuwwz/nuxt3-minimal-reproduction

### Describe the bug

Within the template of a Vue component, using `$route`, `$router` will report a type error.

I tried restarting vscode and the extension and still got an error.

![image](https://github.com/user-attachments/assets/1832873a-96bf-48a0-8cbc-c9d343eb6129)

![image](https://github.com/user-attachments/assets/e2917e54-4181-4321-8d80-44c2191b990b)

**Comment by danielroe** [comment]
I think this is the same issue as https://github.com/nuxt/nuxt/issues/28218. A hotfix will be coming with next `vue-router` release but I think underlying issue is likely in `mlly`.

**Comment by huang-julien** [comment]
Just got the issue. @PerryProjects 's workaround is working. vue-router's version must be explicitly set (without `^`)

**Comment by posva** [comment]
I just released new version, I hope it helps 🙏

**Comment by PerryProjects** [comment]
I will test them tomorrow and provide feedback.

**Comment by jeffreytung7** [comment]
I'm getting a similar error:

 `Property X does not exist on type 'CreateComponentPublicInstance<Readonly<ExtractPropTypes<{}>>, { Menu: typeof Menu; MenuButton: typeof MenuButton; MenuItem: typeof MenuItem; MenuItems: typeof MenuItems; Popover: typeof Popover; ... 10 more ...; handleLinkClick: typeof handleLinkClick; }, ... 17 more ..., {}>'.ts-plugin(2339)`

Where `X` is any function or variable in the utils folder. The app works fine on live and dev mode so nuxt is auto-importing correctly, but I think vscode's "Vue - Official" extension isn't understanding that this is auto-imported.

This only happens in the `<template>` section, it doesn't error inside `<script>`.

The error wasn't here when I had Nuxt 3.11.2, but I recently upgraded to 3.12.4 and it showed up.

**Comment by PerryProjects** [comment]
> I'm getting a similar error:
> 
> `Property X does not exist on type 'CreateComponentPublicInstance<Readonly<ExtractPropTypes<{}>>, { Menu: typeof Menu; MenuButton: typeof MenuButton; MenuItem: typeof MenuItem; MenuItems: typeof MenuItems; Popover: typeof Popover; ... 10 more ...; handleLinkClick: typeof handleLinkClick; }, ... 17 more ..., {}>'.ts-plugin(2339)`
> 
> Where `X` is any function or variable in the utils folder. The app works fine on live and dev mode so nuxt is auto-importing correctly, but I think vscode's "Vue - Official" extension isn't understanding that this is auto-imported.
> 
> This only happens in the `<template>` section, it doesn't error inside `<script>`.
> 
> The error wasn't here when I had Nuxt 3.11.2, but I recently upgraded to 3.12.4 and it showed up. Is this happening for anyone else?


The issue occurs when updating from ```"vue": "3.4.35"``` to ```"vue": "^3.4.36"```. It is very likely that you have the ```^``` in your package.json ( ```"vue": "^3.4.35"``` ). As a workaround, you can remove the ```^``` for now.

**Comment by PerryProjects** [comment]
> I'm getting a similar error:
> 
> `Property X does not exist on type 'CreateComponentPublicInstance<Readonly<ExtractPropTypes<{}>>, { Menu: typeof Menu; MenuButton: typeof MenuButton; MenuItem: typeof MenuItem; MenuItems: typeof MenuItems; Popover: typeof Popover; ... 10 more ...; handleLinkClick: typeof handleLinkClick; }, ... 17 more ..., {}>'.ts-plugin(2339)`
> 
> Where `X` is any function or variable in the utils folder. The app works fine on live and dev mode so nuxt is auto-importing correctly, but I think vscode's "Vue - Official" extension isn't understanding that this is auto-imported.
> 
> This only happens in the `<template>` section, it doesn't error inside `<script>`.
> 
> The error wasn't here when I had Nuxt 3.11.2, but I recently upgraded to 3.12.4 and it showed up. Is this happening for anyone else?

The issue occurs when updating from "vue": "3.4.35" to "vue": "^3.4.36". It is very likely that you have the ^ in your package.json ( "vue": "^3.4.35" ). As a workaround, you can remove the ^ for now. There might be a dependency issue as well.

Additionally, specifying a resolution for vue-router has also helped with the vue version ```3.4.36```:

```json
"resolutions": {
    "vue-router": "4.4.0"
}
```

**Comment by PerryProjects** [comment]
> I just released new version, I hope it helps 🙏

Thank you for the try, but that does not fix the issue. Same error + [Issue](https://github.com/nuxt/nuxt/issues/28373#issuecomment-2272179792) from @jeffreytung7

**Comment by Kasopej** [comment]
This still seems to break once you use latest vue-router version, possibly some incorrect augmentation (just my guess)
pinning to 4.4.0 works tho

**Comment by dreamworks** [comment]
same here - seems not to be fixed yet

**Comment by gerardhoogland-united** [comment]
Still problem with 4.4.5. pinning to 4.4.0 is a workaround for now. It happens whem you add a shims file, for example  shims.vuex.d.ts:

`import { Store } from '@/services/store';// path to store file

declare module '@vue/runtime-core' {
  interface ComponentCustomProperties {
    $store: Store;
  }
}`

**Comment by danielroe** [comment]
@gerardhoogland-united  you need to augment vue, not @vue/runtime-core.

**Comment by gerardhoogland-united** [comment]
@danielroe Thanks, your the best! That fixed it.

My original code came from: https://vuex.vuejs.org/guide/typescript-support.html
That uses @vue/runtime-core.
I don't know why they did it like that...

The correct way is documented here:
https://vuejs.org/api/utility-types#componentcustomproperties

**Comment by jordin-marshall** [comment]
> [@gerardhoogland-united](https://github.com/gerardhoogland-united) you need to augment vue, not @vue/runtime-core.

@danielroe I'm not using nuxt, but coming here and seeing your comment, it just saved my life 😌

**Comment by mesqueeb** [comment]
Just for others coming here
adding something like this for projects you're still in the middle of moving away from vuex:
```ts
import type { TemporaryStoreType } from './store'

declare module 'vuex' {
  export function useStore(): TemporaryStoreType
}

declare module '@vue/runtime-core' {
  interface ComponentCustomProperties {
    $store: TemporaryStoreType
  }
}
```
will break other stuff like `$route` when doing `this.$route`

the fix is to change `@vue/runtime-core` with `vue` and both will work:
```ts
import type { TemporaryStoreType } from './store'

declare module 'vuex' {
  export function useStore(): TemporaryStoreType
}

declare module 'vue' {
  interface ComponentCustomProperties {
    $store: TemporaryStoreType
  }
}
```
