### ISSUE TITLE
Only executed on the client side useAsyncData returns null

### ISSUE THREAD

**Issue by linpengteng** [nuxt/nuxt#28385]
### Environment

- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-65dev6?file=pages%2Findex.vue

<img width="1486" alt="image" src="https://github.com/user-attachments/assets/43099949-fbc5-4b83-8c85-9efb29584fdf">

### Describe the bug

It always returns null only when useAsyncData is executed on the client. When a hot update is triggered during development, it returns the correct value. but when I write the same code in the app.vue entry file, it returns the correct value.
Why is this?

**Comment by manniL** [comment]
Try calling `useAsyncData` with the `{ server: false }` option. This should lead to the desired result and is the recommended way of using "client-only" `useAsyncData`.

**Comment by linpengteng** [comment]
@manniL 
I using useAsyncData with `server: false`, it not working. I need help.

<img width="1310" alt="image" src="https://github.com/user-attachments/assets/161f913d-a63d-47f8-b403-e557fb754ae4">

**Comment by manniL** [comment]
@linpengteng Now do it but not in `onMounted` 😋

**Comment by linpengteng** [comment]
ok, Thanks~
