### ISSUE TITLE
$route、$router and pageTransition is marked as an error in VSCode

### ISSUE THREAD

**Issue by quanzaiyu** [nuxt/nuxt#28387]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.15.1
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@8.14.3
- Builder:          -
- User Config:      app, compatibilityDate, devtools, css, vite
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Open VSCode and write code as follow

### Describe the bug

`$route` and `$router` does not exist in template block:

![PixPin_2024-08-02_17-57-34](https://github.com/user-attachments/assets/481d7760-1015-4462-b584-f794ae454a00)
![PixPin_2024-08-02_17-58-10](https://github.com/user-attachments/assets/674be1fa-23a4-4874-8973-589172514f94)

`pageTransition` can be undefined in middleware:

![PixPin_2024-08-02_18-04-58](https://github.com/user-attachments/assets/c6a62a4d-262b-4077-947e-9ee8df9213d0)
![PixPin_2024-08-02_18-05-11](https://github.com/user-attachments/assets/40d29002-62a0-49aa-8391-06fed012a37c)

**Comment by toyi** [comment]
Same here after updating `vue` and `vue-router`:

```
"vue": "^3.4.34" => "^3.4.35"
"vue-router": "^4.4.0" => "^4.4.2"
```

A coworker told me he just updated and got this problem I didn't have.

I just updated too, I can confirm only the `package.json` and lock file are modified (git status) and I now also have this error.

**Comment by huang-julien** [comment]
Closing as this is fixed by https://github.com/nuxt/nuxt/pull/28446
