### ISSUE TITLE
Nuxt 4 -  Component not loading - Failed to resolve component

### ISSUE THREAD

**Issue by dalisys** [nuxt/nuxt#28380]
### Environment

```
- Operating System: Windows_NT
- Node Version:     v20.16.0
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.4.0
- Builder:          -
- User Config:      compatibilityDate, devtools, future, app, vite, components, modules, primevue, tailwindcss, supabase
- Runtime Modules:  @primevue/nuxt-module@4.0.3, @nuxtjs/tailwindcss@6.12.1, nuxt-lucide-icons@1.0.5, @nuxthub/core@0.7.1, @nuxtjs/supabase@1.3.5
- Build Modules:    -
```

### Reproduction

After setting up the new folder structure of `Nuxt 4`. The components are not found in the `index.vue `

for example:
```
 app/components/landing/LandingHome.vue
```

`index.vue`
```vue
<template>
    <LandingHome />
</template>
```
```
 WARN  [Vue warn]: Failed to resolve component: LandingHome
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
 WARN  [Vue warn]: Component <Anonymous> is missing template or render function.
```

to fix it I had to add to the `nuxt.config.ts`
```ts
components: [
    {
      path: "~/components",
      pathPrefix: true,
    },
]
```

### Describe the bug

The component is not loading correctly with the new folder structure that includes nested directories.

**Comment by tobychidi** [comment]
I dont think you can reference `components/landing/LandingHome.vue` as `<LandingHome />`. It should be `<LandingLandingHome />`

**Comment by rafifn** [comment]
> I dont think you can reference `components/landing/LandingHome.vue` as `<LandingHome />`. It should be `<LandingLandingHome />`

agree with this,
and if you want to auto-import components based on only on it's name you need to set `pathPrefix` option to `false`

[docs](https://nuxt.com/docs/guide/directory-structure/components#component-names)

**Comment by dalisys** [comment]
@tobychidi , @rafifn  , based on Nuxt documentation you can reference `components/landing/LandingHome.vue` 
as `<LandingHome />`      
[https://nuxt.com/docs/guide/directory-structure/components#component-names](url)

![image](https://github.com/user-attachments/assets/c4d7991e-e405-48e4-920a-009d2bf34903)


I will try to provide a reproduction

**Comment by dalisys** [comment]
Since I encountered the problem, the project has evolved significantly, and I haven't been able to reproduce the issue for now.
I also removed 
```
components: [
    {
      path: "~/components",
      pathPrefix: true,
    },
]
```
and it worked fine.
