### ISSUE TITLE
Why are many hooks in the custom routing module in the nuxt official documentation not using arrow functions correctly

### ISSUE THREAD

**Issue by jiejie-color** [nuxt/nuxt#28395]
### Environment

https://nuxtjs.org.cn/docs/guide/going-further/custom-routing#using-approuteroptions

### Reproduction

https://nuxtjs.org.cn/docs/guide/going-further/custom-routing#using-approuteroptions

### Describe the bug

![WeChatd18b1692161ebaa668af9c8d87ff1bb8](https://github.com/user-attachments/assets/5518fbae-9e47-48ce-ad57-32792d9d018f)
![WeChat84fb44f859e25d314a2aec7ce17f2160](https://github.com/user-attachments/assets/c40ce1b7-658b-4b84-8051-54e60ace6af1)

```[tasklist]
### Tasks
```

**Comment by huang-julien** [comment]
Hello :wave: this may seems weird but it is a perfectly valid syntax. Theses are not arrow functions but normal function declaration with quotes due to `-`
