### ISSUE TITLE
Why does keepalive not work in NuxtLayout

### ISSUE THREAD

**Issue by qyn980427** [nuxt/nuxt#28393]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.18.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.4.0
- Builder:          -
- User Config:      ssr, devtools, devServer, modules, svgo, security, css, pinia, plugins, imports, postcss, compatibilityDate
- Runtime Modules:  dayjs-nuxt@2.1.9, @vant/nuxt@1.0.5, @unocss/nuxt@0.61.6, @nuxtjs/device@3.1.1, nuxt-radash@1.0.0, @vueuse/nuxt@10.11.0, @pinia/nuxt@0.5.2, @nuxtjs/color-mode@3.4.2, nuxt-svgo@4.0.2, nuxt-swiper@1.2.2, nuxt-security@2.0.0-rc.9, @nuxtjs/device@3.1.1
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-4czzp7?file=app.vue

1. Enter whatever you want in the input box
2. to page A
3. back index 

### Describe the bug

In NuxtLayout
When I use ( include: ['Index'] ) in this way, keepalive not work
When I use ( include: 'Index', ) in this way, keepalive work well

```[tasklist]
### Tasks
```

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/24570
