### ISSUE TITLE
How to define history in router.options.ts, it reports error 500

### ISSUE THREAD

**Issue by linpengteng** [nuxt/nuxt#28409]
### Environment

- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-xmwzyd?file=app%2Frouter.options.ts

<img width="1911" alt="image" src="https://github.com/user-attachments/assets/d2deb918-f111-4a37-8ebc-2cf97dc7b1e3">

### Describe the bug

I have such a business requirement. On the client side, different bases of vue-router are used according to different domain names. I originally wanted to implement it this way. The configuration in ~app/router.options.ts is as follows

eg:
```typescript
import type { RouterOptions } from '@nuxt/schema';
import { createWebHistory } from 'vue-router';

const routerOptions: RouterOptions = {
  history: (baseURL) => window.location.hostname === 'localhost' ?  createWebHistory(baseURL) : createWebHistory('/prefix' + baseURL),
  scrollBehavior(to, from, savedPosition) {
    if (savedPosition) {
      return savedPosition;
    } else {
      return { top: 0, left: 0 };
    }
  },
};

export default routerOptions;
```

But it reports error 500 when I use createWebHistory API

**Comment by huang-julien** [comment]
Hello that's because `route.options` is also used server side. 

You'd probably need to do `import.meta.client ? window.location.hostname === 'localhost' ?  createWebHistory(baseURL) : createWebHistory('/prefix' + baseURL) : createMemoryHistory(routerBase)`

**Comment by linpengteng** [comment]
thank you, it's working.
