### ISSUE TITLE
Why can't the search button be clicked in the Chinese version of the document, while it can be searched in the English version

### ISSUE THREAD

**Issue by jiejie-color** [nuxt/nuxt#28401]
### Environment

https://nuxt.com/docs/guide/recipes/custom-routing#using-approuteroptions
https://nuxtjs.org.cn/docs/guide/going-further/custom-routing#using-approuteroptions

### Reproduction

https://nuxt.com/docs/guide/recipes/custom-routing#using-approuteroptions
https://nuxtjs.org.cn/docs/guide/going-further/custom-routing#using-approuteroptions

### Describe the bug

![1](https://github.com/user-attachments/assets/7be35a50-eef2-4cf2-a43a-e7d47a8f2f20)
![2](https://github.com/user-attachments/assets/833a80c6-eb1e-4f0e-9eff-e1c5101d577d)
The English version can be searched, but clicking on the Chinese version has no effect
I hope Chinese documents can be searched for

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by ikxin** [comment]
Maybe you can try https://nuxt.zhcndoc.com/
