### ISSUE TITLE
useFetch not deduplicating requests that return an error like 404, 401 etc.

### ISSUE THREAD

**Issue by Jannick94** [nuxt/nuxt#28413]
### Environment

- Operating System: Linux
- Node Version:     v22.4.1
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.8.2
- Builder:          -
- User Config:      compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

I've setup a repository with the minimal code here:
https://github.com/Jannick94/nuxt-usefetch-dedupe/blob/main/app.vue

If StackBlitz is easier, I could also create a reproduction there but I thought it was easier to test in a 'real browser'.

### Describe the bug

I'm currently refactoring my code to correctly use the useFetch composable (according to the amazing video: https://www.youtube.com/watch?v=njsGVmcWviY). I discovered that performing a request to something like an profile/user API endpoint doesn't seem to correctly dedupe the request when this endpoint returns a erroneous status code like 404/401 etc.

In the reproduction's `app.vue` file I set up two tests, when using `useFetch` the correct way I see the api request in the browser networks tab. When I perform the request using `useFetch` the wrong way, I dont see the request in the network tab, as expected because it runs on the server and dedupes the response to the client.

Whenever the request doesn't return a erroneous status code, it does get deduped correctly. I tried setting various `useFetch`/`fetch` options like `retry/retryStatusCodes` but none seem to produce my expected result.

Thanks!

**Comment by fishDev94** [comment]
i don't get what is it `execute`,
the descructuring of useFetch should be like this no?
`
const { data, status, error, refresh, clear } = await useFetch('yourURL')
`

**Comment by Jannick94** [comment]
As far as I know, `execute` and `refresh` do the same and are just aliases of eachother.
https://nuxt.com/docs/api/composables/use-fetch#return-values

**Comment by Jannick94** [comment]
Let me try to explain the issue a bit more clear:

When I have the following code directly in a `script setup` context:

```js
const { data: user, execute: executeFetchUser } = useFetch('https://reqres.in/api/users/23', {
    immediate: false,
});

async function fetchUser() {
    await executeFetchUser();

    console.log('do some extra stuff after fetching user');
}

await fetchUser();
```

The browser console shows the following when reloading the page:
![image](https://github.com/user-attachments/assets/5861a15a-7cb5-4d00-a39b-f20b1ec94846)

It seems the request is done twice because it returns an erroneous status code. When the request is succesful (for instance, changing the id in the url from 23 to 1), I do get the expected result.

------

Now when I do the request like this, and I know this is the wrong way to use `useFetch`, but that's how I stumbled upon this issue:

```js
async function fetchUser() {
    const { data: user } = await useFetch('https://reqres.in/api/users/23');

    console.log('do some extra stuff after fetching user');
}

await fetchUser();
```

The browser console show this, it seems the request is then only done on the server, as I would have expected
![image](https://github.com/user-attachments/assets/336dbfca-4988-46be-ab8f-df03782455fa)


Adding a manual `key` to the request doesn't change the resulting behavior unfortunately.

**Comment by xjccc** [comment]
In client side, call `execute`, it will `refetch`.

https://github.com/nuxt/nuxt/blob/b161fb2c6471e7150c6e19deed3ae6f160a405c8/packages/nuxt/src/app/composables/asyncData.ts#L266

If only `await useFetch`, in server side fetch error, in client side, it will not `refetch`, it will return error.

https://github.com/nuxt/nuxt/blob/b161fb2c6471e7150c6e19deed3ae6f160a405c8/packages/nuxt/src/app/composables/asyncData.ts#L365

**Comment by danielroe** [comment]
Fetch will automatically retry if it receives an error. You can configure this by setting `retry` to `false` (or the number of retries you want) or by configuring `retryStatusCodes` (if you want to customise which codes will trigger a retry).
