### ISSUE TITLE
Some files in the pages folder do not need to be detected

### ISSUE THREAD

**Issue by SunjieZhu** [nuxt/nuxt#28410]
### Describe the feature

some js,ts files , we want them to work on certain pages or components , global import is not necessary for these files , we want to place these files in the directory where they work .

```
export interface layoutItemConfig {
    id: string
    type: string
    positionX: number
    positionY: number
    spanX: number
    spanY: number
    maxSpanX?: number
    maxSpanY?: number
}
```

when I put this file in `app/pages/gridLayout/types.ts`
It reminds me `The file app/pages/index/types.ts is not a valid page as it has no content.`

to make this ERROR not appear , I had to use `export default` or `definePageMeta` in this file
can we have a configuration item to turn off this check ?

There is the reproduction
https://stackblitz.com/edit/github-tu5vgq?file=pages%2Findex.vue

the error occurred when I started the project
![image](https://github.com/user-attachments/assets/19bf3396-9032-417e-950b-b3e526a42907)

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by fishDev94** [comment]
Hi! If you want your file to be ignored by the nuxt router you need to use `-` as a prefix, for example `-types.ts`

**Comment by SunjieZhu** [comment]
> Hi! If you want your file to be ignored by the nuxt router you need to use `-` as a prefix, for example `-types.ts`
> 
> another way could be creating `.nuxtignore` and adding `pages/*.ts` it will ignore all your *.ts files inside pages dir if you would like to avoid to use the prefix "-"

thanks bro , it works
find options:
