### ISSUE TITLE
Page Transition with javascript hooks not working properly

### ISSUE THREAD

**Issue by jules-contact** [nuxt/nuxt#28418]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.9.0`
- Nuxt Version:     `3.12.4`
- CLI Version:      `3.12.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `pnpm@9.4.0`
- Builder:          `-`
- User Config:      `app`, `devtools`, `css`, `components`, `modules`, `pinia`, `build`, `runtimeConfig`, `compatibilityDate`
- Runtime Modules:  `@pinia/nuxt@0.5.2`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-fjpcza?file=pages%2Fabout.vue,pages%2Findex.vue,layouts%2Fdefault.vue

### Describe the bug

When I use a javascript hook to trigger my transition page, before triggering the output transition, the page instantly scrolls upwards.

### Logs

```shell-script
No logs
```

**Comment by xjccc** [comment]
You could set this, have a try.

```
definePageMeta({
   scrollToTop: false
})
```

**Comment by jules-contact** [comment]
Any ideas on how to do this for each page without declaring it on each page?

**Comment by xjccc** [comment]
Excuse me. Is there need a global config like `app.scrollToTop` to control the all pages scrollBehavior? Thank you.
@danielroe

**Comment by jules-contact** [comment]
scrollToTop isn't quite what I need because when I return to the page, the scroll position remains where I left it. I just want to understand why the page scrolls to the top before the leave hook is triggered.

**Comment by bukandicki** [comment]
[localhost_3000_about.webm](https://github.com/user-attachments/assets/b4e614ff-9e47-43a8-9bf9-410ca7437098)

Is this still not fixed in Nuxt 3 @danielroe? I made a very simple transition between two pages, but they still overlap each other and don't wait for the animation to finish first.

**Comment by jules-contact** [comment]
Resolved, by adding 
`app: {
    pageTransition: true,
}` into the nuxt.config
