### ISSUE TITLE
Add back the default folder

### ISSUE THREAD

**Issue by rising-dot** [nuxt/nuxt#28429]
### Describe the feature

Add back the default folder components, assets, store, plugins, layouts as it was like before

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by huang-julien** [comment]
Hello :wave: the new directory structure is enabled with the `compatibilityV4` flag and will be default in Nuxt 4. If you wish to have the directory structure of Nuxt 3, you can take a look at the [doc](https://nuxt.com/docs/getting-started/upgrade#opting-in-to-nuxt-4) and change your nuxt config.
