### ISSUE TITLE
route.meta.name gives undefined

### ISSUE THREAD

**Issue by onkar-rentomojo** [nuxt/nuxt#28436]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.10.0`
- Nuxt Version:     `3.12.4`
- CLI Version:      `3.12.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `npm@10.2.3`
- Builder:          `-`
- User Config:      `app`, `devtools`, `runtimeConfig`, `modules`, `pinia`, `router`, `components`, `css`, `vite`, `nitro`, `webpack`, `hooks`
- Runtime Modules:  `@nuxtjs/eslint-module@4.1.0`, `@pinia/nuxt@0.5.3`, `@pinia-plugin-persistedstate/nuxt@1.2.1`
- Build Modules:    `-`

### Reproduction

Update Nuxt to latest version.

define route name using definePageMeta

Try accessing it with route.meta.name and it gives undefined.

### Describe the bug

Define route name using definePageMeta

Try accessing it with route.meta.name and it gives undefined.

When you directly try accessing it using route.name, it works.

This is really wierd behavior and it can break existing apps which are using route.meta.name in their legacy code

**Comment by xjccc** [comment]
Because it's scanPageMeta from `definePageMeta` and merge properties to routes, and some properties is not custom properties for meta.

You could look at this for some infomation: https://github.com/nuxt/nuxt/pull/25210

**Comment by onkar-rentomojo** [comment]
Okay, so scanPageMeta experimental feature is getting used now. Shouldn't there be backwards compatibility here? It would have broken our production if we did not have package-lock.json.

Also It should have been optional for us to opt for scanPageMeta, why is it enabled by default?

How could we possibly have known that suddenly you won't get route name now using route.meta.name?

One more thing -

for eg - 

```
definePageMeta({
  name: 'custom-name',
  someOtherKey: 'some-other-key-value'
});

```
 If the defined keys are >=2 in definePageMeta, then route.meta.name can be accessed.

Why this behavior?

**Comment by xjccc** [comment]
Oooo.. Its maybe a problem i think..

**Comment by danielroe** [comment]
I think these keys _should_ be accessed from `route.name` rather than `route.meta.name`. We might revert the change via the linked PR, but perhaps only for 3.x.
