### ISSUE TITLE
error with vue-tsc 2.0.29

### ISSUE THREAD

**Issue by angrymusic** [nuxt/nuxt#28440]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.17.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@9.6.6
- Builder:          -
- User Config:      devtools, typescript, vue, modules, i18n, quasar, site, nitro, routeRules, sitemap, runtimeConfig, css, security
- Runtime Modules:  @nuxtjs/i18n@8.3.1, @pinia/nuxt@0.5.1, @pinia-plugin-persistedstate/nuxt@1.2.0, @nuxtjs/seo@2.0.0-rc.10, nuxt-quasar-ui@2.1.2, nuxt-security@2.0.0-rc.9
- Build Modules:    -
------------------------------

### Reproduction

it looks like auto import is not working

### Describe the bug

if i upgrade vue-tsc version,

i can't npm run build or dev

because I encounter errors with composable... etc.

`components/recruit/Table.vue:29:11 - error TS2339: Property 'convertUnixtoYMD' does not exist on type 'CreateComponentPublicInstance<Readonly<ExtractPropTypes<__VLS_TypePropsToOption<{ searchStr: string; data: RecruitList[]; }>>>, {}, unknown, ... 16 more ..., {}>'.

29           convertUnixtoYMD(item.endTime)
             ~~~~~~~~~~~~~~~~
`
`components/solution/Intro.vue:40:21 - error TS2339: Property 'navigateTo' does not exist on type 'CreateComponentPublicInstance<Readonly<ExtractPropTypes<__VLS_TypePropsToOption<{ data: Res_Solution; }>>>, { t: ComposerTranslation<{ [x: string]: LocaleMessage<VueMessageType>; }, ... 4 more ..., string>; }, ... 17 more ..., {}>'.

40             @click="navigateTo({ path: '/customer/brochure' })"
                       ~~~~~~~~~~
`

it looks like auto import is not working


### Additional context

_No response_

### Logs

_No response_

**Comment by remiconnesson** [comment]
I have the same issues where two files failed to be detected as auto imports during type checks, the 10 other files work though

**Comment by Ambrise** [comment]
Sorry I didn't see that a correction was in progress. Thanks
