### ISSUE TITLE
how to compile code to commonjs?

### ISSUE THREAD

**Issue by yreenchan** [nuxt/nuxt#28459]
### Environment

nuxt 3.12.4

### Reproduction

```
export default defineNuxtConfig({
  compatibilityDate: '2024-04-03',
  devtools: { enabled: true },
  telemetry: false,
  vite: {
    build: {
      target: 'commonjs'
    }
  }
})
```

### Describe the bug

the code can't not build the commonjs code

**Comment by danielroe** [comment]
It's not possible to build to pure common JS, although it is possible to build to a common JS target that uses a dynamic import to import the Nitro ESM output.
