### ISSUE TITLE
Warning "No match found for path ..." when fetching server route

### ISSUE THREAD

**Issue by markbrockhoff** [nuxt/nuxt#28475]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.11.0`
- Nuxt Version:     `3.12.3`
- CLI Version:      `3.12.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `pnpm@9.6.0`
- Builder:          `-`
- User Config:      `compatibilityDate`, `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/markbrockhoff/nuxt-vite-types-bug-repro/tree/server-handler-router-bug

Steps to reproduce:
1. Clone the repo (Please use the branch "server-handler-router-bug")
2. Install the dependencies
3. Run `pnpm dev` and open the index page
4. The console running the nuxt server should show the following warning:
<img width="561" alt="image" src="https://github.com/user-attachments/assets/dce063a3-896b-4921-9c5b-68ac8584ae28">

### Describe the bug

Hi,

while working on a nuxt module I wanted to add a server handler for the path "GET /auth/session" which may return a 401 status code.
I noticed that calling this endpoint from within a middleware using `$fetch` a Vue Router warning is logged to the console in case a 401 is returned:
<img width="561" alt="image" src="https://github.com/user-attachments/assets/792da3e1-6926-47cb-a8fe-7701e174ab63">

It looks like nuxt / nitro is treating the route like a page instead of an api route. Moving it into the `server/api` folder and calling it with the `/api` prefix resolves the issue. However, as I have to add the handler from within a module using `addServerHandler` even setting the route to `/api/auth/session` doesnt seem to fix the issue.

I couldn't find any option or config to treat this path like if it originated from the `/api` folder, but please correct me if I overlooked something.
I think it would be great if `addServerHandler` provided an option to treat a server route as a pure api route, configuring the vue router like if it was placed inside the `/api` folder.

**Comment by Ripwords** [comment]
Try this, i also encountered this awhile, dug through some libraries and found this
```ts
await navigateTo("/auth/session", { external: true })
```

**Comment by markbrockhoff** [comment]
> Try this, i also encountered this awhile, dug through some libraries and found this
> 
> ```ts
> await navigateTo("/auth/session", { external: true })
> ```

Thanks for the reply

So you mean using `navigateTo` as a replacement for `$fetch`? I don't think that would work (at least in my case) as I want to get the data returned by the api call. To be more percise I'm calling my session endpoint within a middleware to check the users login status and triggering a login in case he's not authenticated / authorized.

**Comment by Ripwords** [comment]
ahh, you should look into [nuxt-auth-utils](https://github.com/atinux/nuxt-auth-utils), I've been doing something similar using this, since you can get the status using the global composable exposed you don't need to return anything from the middleware.

**Comment by markbrockhoff** [comment]
Ah, I see, that's interesting.

It looked into the implementation of `useUserSession()` and there are three differences from their call to the endpoint compared to mine:

nuxt-auth-utils:
```ts
await useRequestFetch()('/api/_auth/session', {
    headers: {
      Accept: 'text/json',
    },
    retry: false,
})
```

Me:
```ts
```

1. They use `useRequestFetch()` instead of `$fetch` (I had already thought of doing so too but held back as it's not documented yet). It automatically forewards the headers so they don't have to do it manually as I 
2. They

**Comment by Ripwords** [comment]
I actually had a different issue, going through all these might have just solved the issue i had yesterday as well

**Comment by markbrockhoff** [comment]
Resolved
