### ISSUE TITLE
Modifying static resources in the public directory after nuxt build does not take effect and must be rebuilt

### ISSUE THREAD

**Issue by shenxing09** [nuxt/nuxt#28476]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.14.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@8.15.3
- Builder:          -
- User Config:      compatibilityDate, devtools, modules, app, image, css, components, runtimeConfig, imports, primevue, unocss
- Runtime Modules:  @unocss/nuxt@0.61.5, @nuxt/image@1.7.0, @primevue/nuxt-module@4.0.1, nuxt-swiper@1.2.2
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-feikgn?file=package.json

### Describe the bug

Modifying static resources in the public directory after nuxt build does not take effect and must be rebuilt

**Comment by danielroe** [comment]
This is by design and is part of how Nitro works. We are able to do performance optimisations this way, and it means we don't have to scan the public directory when starting the server.
