### ISSUE TITLE
Empty nuxt project has high LCP and FCP value in lighthouse

### ISSUE THREAD

**Issue by siporoz** [nuxt/nuxt#28473]
### Discussed in https://github.com/nuxt/nuxt/discussions/28460

<div type='discussions-op-text'>

<sup>Originally posted by **siporoz** August  8, 2024</sup>
Hi,
I am faced with the problem that my project has high LCP and FCP values in lighthouse, even if there is a minimum number of elements on the page.
As an experiment, I decided to create a new empty project through the command:

`npx nuxi@latest init my-awsome-project`

Next, I built the project and launched it. 

And here are the values I got:

<img width="1202" alt="Снимок экрана 2024-08-08 в 10 58 23" src="https://github.com/user-attachments/assets/f4d06d7c-8d29-47f4-ac7a-fcd3ed2b8c0c">

Even if change `<NuxtWelcome />` e.g.` <h1>,` the values remain high for an empty page.

<img width="1391" alt="Снимок экрана 2024-08-08 в 11 01 19" src="https://github.com/user-attachments/assets/35eb83ad-453b-4c65-b5e7-413c3a606320">

### Environment

Operating System: mac os 14.4.1
Node Version: v22.1.0
Nuxt Version: 3.12.4

</div>

**Comment by danielroe** [comment]
The issues you're seeing are:

1. You need a `<title>`.  This isn't something Nuxt can provide for you.
1. You need a meta description. This isn't something Nuxt can provide for you.
1. You need a `lang` attribute for your `<html>` tag. We considered defaulting to English but felt this wouldn't be appropriate - it's a choice for you.
1. You need a `robots.txt` - I've added this for new starters https://github.com/nuxt/starter/commit/6a0abda7507f523ca009aeed549c2324a7a2e29a

Note that running Lighthouse tests against a local build isn't recommended as it's _highly_ dependent on your local server and doesn't include optimisations you'll get when deploying your site (like compressing assets, etc.).
