### ISSUE TITLE
Dynamic SSR/CSR Based on User State (e.g., Cookies)

### ISSUE THREAD

**Issue by censujiang** [nuxt/nuxt#28478]
### Describe the feature

Hi Nuxt Team,

I'm currently working on a Nuxt 3 project and have encountered a limitation regarding dynamic SSR/CSR based on user state, such as the presence of a specific cookie.

#### Use Case:

In my project, I need to dynamically disable SSR for users who have a specific cookie (token). This feature is crucial because:

Certain users should experience the application entirely as a CSR (Client-Side Rendered) app.
The decision to enable or disable SSR needs to happen at the request level based on the user's authentication state.
Attempts and Workarounds:
I've tried various approaches, such as using server-side middleware and hooks to manipulate the serverRendered flag in Nuxt 3, but it seems there's no straightforward or officially supported way to achieve this.

#### Feature Request:
It would be highly beneficial if Nuxt could support dynamic SSR/CSR toggling based on request-specific data, such as cookies, headers, or other context. This could be implemented as:

An official hook or middleware that allows for toggling SSR on or off per request.
A configuration option in nuxt.config.ts that can be dynamically set based on user-specific context.

#### Example:

A potential implementation could look like this:

```ts
// middleware/dynamic-ssr.server.ts
export default defineEventHandler((event) => {
  const isSign = getCookie(event, 'token');

  if (isSign) {
    // Disable SSR dynamically for this request
    event.context.ssr = false;
  } else {
    event.context.ssr = true;
  }
});

```
This would allow developers to fine-tune SSR behavior based on user-specific conditions, providing a more flexible and powerful framework.

#### Conclusion:
I hope the Nuxt team can consider adding this feature, as it would greatly enhance the flexibility of Nuxt in handling diverse user requirements.

Thank you for your time and consideration!

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
You can do this by setting `event.context.nuxt.noSSR`:

```ts
import { defineEventHandler, getRequestHeader } from 'h3'

export default defineEventHandler((event) => {
  if (/* some condition */) {
    event.context.nuxt = event.context.nuxt || {}
    event.context.nuxt.noSSR = true
  }
})
```

**Comment by art-kc** [comment]
this code doesn't work. there is no such thing as context in event. 
I've also tried it with  
`
const nuxtApp: NuxtApp = useNuxtApp();
 nuxtApp.ssrContext.noSSR = true;
`

Though noSSR is set to true, the page after loading still returns ssr version of the page

**Comment by danielroe** [comment]
Setting `event.context.nuxt.noSSR` does work.

If you are having trouble, feel free to provide a stackblitz and I'll happily have a look.
