### ISSUE TITLE
Hydration mismatch when using `Teleport` in combination with `useHead` scripts at `'bodyOpen'` position

### ISSUE THREAD

**Issue by CernyMatej** [nuxt/nuxt#28483]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-lkzbwy?file=components%2FModal.vue,app.vue

### Describe the bug

When adding elements like script tags using `useHead` with the `tagPosition: 'bodyOpen'` option, `<Teleport to="body">` results in a hydration mismatch.

<img width="379" alt="image" src="https://github.com/user-attachments/assets/bd4da22b-65d3-4e80-aa69-730df35d1c2a">

**Comment by danielroe** [comment]
We likely need to update the docs, but would you try now targeting it to `#teleports` and seeing if that works for you?

**Comment by CernyMatej** [comment]
@danielroe 
Thank you! Seems to have done the trick.

I made the following PRs to update the docs. Let me know if there's anything I need to fix:
https://github.com/nuxt/examples/pull/82
https://github.com/nuxt/nuxt/pull/28489
https://github.com/nuxt/nuxt/pull/28490
