### ISSUE TITLE
Package manager order in docs/getting-started/installation

### ISSUE THREAD

**Issue by gustavwilliam** [nuxt/nuxt#28499]
### Environment

Live website at https://nuxt.com/docs/getting-started/installation

The bug is present on all browsers I've tried, using macOS:
- Safari
- Google Chrome (dev)

### Reproduction

Check out https://nuxt.com/docs/getting-started/installation

### Describe the bug

The order of package managers in the instructions is different in different code blocks. This also means that the pre-selected package manager will be different for different, since the first option is always selected by default when loading the page.

I've added a red outline around the code blocks in question below, to clarify where they are on the page.

<img width="784" alt="356973548-c85f70ea-cadb-4331-ae10-bb6f0af67605" src="https://github.com/user-attachments/assets/4e3a35d9-34fb-4163-8729-213a84fe9450">

I'd love to make a PR for this, assuming it's not an intentional feature.

### Additional context

This seems to be as simple as the order of editors listed in  https://github.com/nuxt/nuxt/blob/main/docs/1.getting-started/2.installation.md not being the same for the code blocks. Should be a very straightforward fix.

**Comment by danielroe** [comment]
I'd welcome a PR updating the docs here, or (even better) a component in https://github.com/nuxt/nuxt.com that handles remembering your choice (and defaulting to that package manager).

**Comment by gustavwilliam** [comment]
Sounds good! I'll look into adding such a component and submitting a PR.
