### ISSUE TITLE
After importing the @ nuxtjs/i18n module, the automatically imported function cannot find the type declaration in the template

### ISSUE THREAD

**Issue by zhonguanping** [nuxt/nuxt#28512]
### Environment

nuxt v3.12.4

### Reproduction

This issue occurred in the newly created nuxt3 project without any other configuration made

### Describe the bug

<img width="417" alt="image1" src="https://github.com/user-attachments/assets/d5e14b7c-4297-4d17-9a1e-59164bd234d9">
<img width="780" alt="image2" src="https://github.com/user-attachments/assets/6b355c79-24b8-4d56-becd-34372ea6c3ef">
<img width="527" alt="image3" src="https://github.com/user-attachments/assets/995ba743-a67b-4ed7-bd84-76583595a208">
<img width="887" alt="image4" src="https://github.com/user-attachments/assets/01fded20-6346-4be3-9420-0ae6dcaf48fb">

When 'i18n' is not imported, there is no problem using the automatic import function of utilis in the Vue file, but after importing 'i18n', the type prompt becomes invalid.

**Comment by danielroe** [comment]
This should be resolved in the next release: https://github.com/nuxt/nuxt/pull/28466.
