### ISSUE TITLE
useSEOMeta or useHead,  og tag dynamic assigned by requests can't not be fetch by FB or LINE sharing 

### ISSUE THREAD

**Issue by withgogo** [nuxt/nuxt#28511]
### Environment

Operating System: Darwin
Node Version: v18.14.0
Nuxt Version: 3.11.2
CLI Version: 3.11.1
Nitro Version: 2.9.6
Package Manager: yarn@1.22.19
Builder: -
User Config: devServer, runtimeConfig, modules, gtag, pinia, piniaPersistedstate, i18n, elementPlus, vant, app, css, alias, vite, nitro, imports
Runtime Modules: @element-plus/nuxt@1.0.8, @vant/nuxt@1.0.4, @nuxtjs/i18n@8.3.0, @pinia/nuxt@0.5.1, @pinia-plugin-persistedstate/nuxt@1.2.0, nuxt-gtag@2.0.7, nuxt-meta-pixel@2.0.2
Build Modules: -

### Reproduction

http://ec-ssr-stage.pqhealthy.com/goods/goods-detail?id=212&goodsChoiceType=0
in LINE tool: https://poker.line.naver.jp/
in FB tool: https://developers.facebook.com/tools/debug/

Both of tools above can not get the ob:title, og:image for assigned value by useSeoMeta or useHead

reproduction code: https://github.com/withgogo/ec-ssr

### Describe the bug

http://ec-ssr-stage.pqhealthy.com/goods/goods-detail?id=212&goodsChoiceType=0
Above URL in LINE tool: "https://poker.line.naver.jp/" or in FB tool: "https://developers.facebook.com/tools/debug/" for sharing.

Both of tools above can not get the ob:title, og:image for assigned value by useSeoMeta or useHead
![image](https://github.com/user-attachments/assets/60ee906f-b505-4d20-889b-3c52ba6d7295)
![image](https://github.com/user-attachments/assets/3c83b46d-0b53-4bf8-b134-6803de5426f1)
![image](https://github.com/user-attachments/assets/faf492b3-698a-4571-8b30-a027c8130dbe)

**Comment by danielroe** [comment]
Would you raise this instead at https://github.com/nuxt-modules/og-image ? 🙏

**Comment by withgogo** [comment]
> Would you raise this instead at https://github.com/nuxt-modules/og-image ? 🙏
@danielroe 
Hi, 
It is not only about og-image, also og-title,og-description.  all dynamic assigned value can not be caught by FB or LINE.

**Comment by danielroe** [comment]
It is because you are only setting that data after the page is mounted (on the client):

https://github.com/withgogo/ec-ssr/blob/a9d2528c9b436845ecc157a0bc417225ca9bfc91/pages/goods/mb/goodsDetail.vue#L987

**Comment by withgogo** [comment]
> It is because you are only setting that data after the page is mounted (on the client):
> 
> https://github.com/withgogo/ec-ssr/blob/a9d2528c9b436845ecc157a0bc417225ca9bfc91/pages/goods/mb/goodsDetail.vue#L987

@danielroe Hi, thank you for your advice. I do that because I have to assign useSeoMeta() the value I got from onMounted functions such as goodsName,goodsImage, etc. 

Sure, I can make useSeoMeta() under <script setup>, but it will get nothing. Because the data was not retrieved by some functions in onMounted() yet.

So would please give me any solution?

**Comment by danielroe** [comment]
The solution is:
- seo crawlers need the tags to be rendered in the initial HTML
- the initial HTML is rendered before mounted event fires
- so you need to fetch the data before the mounted event fires

**Comment by withgogo** [comment]
> The solution is:
> 
> * seo crawlers need the tags to be rendered in the initial HTML
> * the initial HTML is rendered before mounted event fires
> * so you need to fetch the data before the mounted event fires

@danielroe Thank you very much, it helps a lot. It seems fine by using "useAsyncData". Please see code below. 
However when I  refresh the page, I met another problem with error "<RouterView name=undefined route=undefined >". 
I am sure it is caused by "useAsyncData", because if I delete the code below, it works fine.
Even if I add the "watch:[params],cache:false", it is not working as well.
So would you please provide any solution for this kind of error?


`const { data } = await useAsyncData(()=>{
	state.goodsChoiceType = route.query.goodsChoiceType
	console.log("goodsChoiceType",state.goodsChoiceType)
	if (state.goodsChoiceType == 7) {
		return packageItems(params).then(response=>{
			return response.data
		})
	}
	else{
		return goodsItems(params).then(response=>{
			return response.data.obj
		})
	}
},
{
    watch: [params],
	cache: false
  },
)

useSeoMeta({
	title:  data.value.goodsName,
	ogTitle:  data.value.goodsName,
	description:  data.value.seoDescription,
	ogDescription: data.value.seoDescription,
	ogImage:  data.value?.goodsMainPhoto?.fullPath,
	twitterCard: 'summary_large_image',
})`

**Comment by withgogo** [comment]
@danielroe I think dynamic seo tag,  which data is from api,  is a very common requirement. Is there any demo or simple way to achieve it?

**Comment by danielroe** [comment]
Here's a simple demo of the concept:

```ts
const { data } = await useAsyncData() // whatever async requests you have

useSeoMeta({
  title: data.value.title // or otherwise derive the seo metadat from the data you fetch
})
```
