### ISSUE TITLE
Nuxt $fetch throws exception when accessing API with subdomain

### ISSUE THREAD

**Issue by kevinlonigro** [nuxt/nuxt#28534]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-n6demm

### Describe the bug

In attempting to access an API with a subdomain from Ecowitt, $fetch throws an exception while axios handles the API appropriately.

Have reproduced the issue with a stackblitz project. However in the project I don't use the full API with specific keys in order to safeguard them. Using only a part of the API in order to force it to reply with a response. Ultimately it's the same result, $fetch throws an exception while axios is fine.

**Axios returns the following message**: {"code":40010,"msg":"Invalid application Key","time":"1723600494","data":[]}

**$fetch throws the following error**: [GET] "https://api.ecowitt.net/api/v3/device/real_time": <no response> fetch failed

  at async $fetchRaw2 (node_modules/ofetch/dist/shared/ofetch.37386b05.mjs:248:14)
  at async $fetch2 (node_modules/ofetch/dist/shared/ofetch.37386b05.mjs:285:15)
  at async Object.eval (.nuxt/dev/index.mjs:1066:12)
  at async eval (node_modules/h3/dist/index.mjs:2100:19)
  at async Object.callAsync (node_modules/unctx/dist/index.mjs:91:16)
  at async Server.toNodeHandle (node_modules/h3/dist/index.mjs:2391:7)

**Comment by manniL** [comment]
This seems to be a problem with the API when being called via Node.js (not in-browser). Same happens with plain fetch in node.

```ts
 const result = await fetch('https://api.ecowitt.net/api/v3/device/real_time')
    if(result.ok){
      return await result.json()
    }
    console.log(result)
    return 'error, resp not ok'
  ```

**Comment by kevinlonigro** [comment]
@manniL understand your comment but any thoughts why Axios succeeds?

**Comment by manniL** [comment]
Debugged it a bit but unsure. Maybe bc it relies on XMLHttpRequest and not fetch 🤷🏻‍♂️
