### ISSUE TITLE
[SSG] Implement Route-Based Dynamic SEO Meta Tags in SSG

### ISSUE THREAD

**Issue by mavyfaby** [nuxt/nuxt#28535]
### Implement Route-Based Dynamic SEO Meta Tags in SSG

With `SSG` some composables doesn't render on generate HTML pages, so SEO Meta tags doesn't work. There's somehow a way to set meta tags via `nuxt.config.ts` using `app.head.meta`. However, that only sets the default SEO meta tags on every page. So same meta tags on every pages.

It's better to set meta tags based on route in `nuxt.config.ts` like this:

```ts
export default defineNuxtConfig({
  ...
  app: {
    head: {
      meta: {
        '/': [
          { property: "og:title", content: "Home" }
        ],
        '/about': [
          { property: "og:title", content: "About Us" }
        ],
      }
    }
  }
  ...
});
```

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
> With SSG some composables doesn't render on generate HTML pages, so SEO Meta tags doesn't work.

Not sure what you mean by that, `useHead` and `useSeoMeta` should work as expected and show content on the server too when using SSG (without SSR false, so no plain SPA).

**Comment by mavyfaby** [comment]
Here's the repro link: https://stackblitz.com/edit/nuxt-seo-ssg-reproduction

`useSeoMeta` doesn't work on `ssr: false` and `preset: "static"`. The meta tags doesn't injected to the html output file. Here's the example index output of the reproduction link:

```html
<!DOCTYPE html><html  data-capo=""><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="modulepreload" as="script" crossorigin href="/_nuxt/Ctk-xaDv.js">
<link rel="prefetch" as="style" href="/_nuxt/error-404.CjGVuf6H.css">
<link rel="prefetch" as="script" crossorigin href="/_nuxt/CwzXEaub.js">
<link rel="prefetch" as="script" crossorigin href="/_nuxt/BvxebPls.js">
<link rel="prefetch" as="script" crossorigin href="/_nuxt/UZvjzESQ.js">
<link rel="prefetch" as="style" href="/_nuxt/error-500.DFBAsgKS.css">
<link rel="prefetch" as="script" crossorigin href="/_nuxt/wOpaheEI.js">
<script type="module" src="/_nuxt/Ctk-xaDv.js" crossorigin></script></head><body><div id="__nuxt"></div><div id="teleports"></div><script type="application/json" id="__NUXT_DATA__" data-ssr="false">[{"serverRendered":1},false]</script>
<script>window.__NUXT__={};window.__NUXT__.config={public:{},app:{baseURL:"/",buildId:"f397a246-5ef5-445f-a258-03f2fb0ef7d1",buildAssetsDir:"/_nuxt/",cdnURL:""}}</script></body></html>
```

where I use:

```ts
useSeoMeta({
  ogTitle: 'Home Page',
  ogDescription: 'Home page description',
});
```

and still doesn't injected in the html output file.

**Comment by manniL** [comment]
> useSeoMeta doesn't work on ssr: false and preset: "static". The meta tags wasn't injected to the html output file. Here's the example index output of the reproduction link:

That's what I just said above.

Are you planning on building an SPA only (so "no real SSG")? Then ssr: false is correct. Otherwise, enable it 😋

In all cases, you can still "manually" add SEO tags when rendering, e.g. via a nitro hook (renderHtml for example)

**Comment by mavyfaby** [comment]
I'm planning to host my frontend app on nginx, I guess it's an SPA and not SSG. @manniL
