### ISSUE TITLE
Creating new Nuxt 3 project results in multiple issues on Windows 10

### ISSUE THREAD

**Issue by lkrombeen** [nuxt/nuxt#28541]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.16.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.8.1
- Builder:          -
- User Config:      compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

1. Install Node v20.16.0
2. Run npx nuxi@latest init app and select npm
3. cd app
4. npm run dev
5. Change the app.vue as shown below

I also added it to this example: https://stackblitz.com/edit/github-c6grb6?file=app.vue
**Not a reproduction** since it does not run on Windows 10, so just the example of how it should look like.

```
<template>
  <div class="container">
    <h1>{{ count }}</h1>
    <button @click="increment">Increment</button>
  </div>
</template>

<script setup lang="ts">
const count = ref(0);
const increment = () => count.value++;
</script>
```

### Describe the bug

There are multiple problems:
1. When I click the button, count does not increment.
2. The Nuxt DevTools are not opening when I press Shift + Alt + D 
3. In the developer console I get the following error: `Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.` in entry.js:1
4. Additionally, if I setup pages and go to a page I created, I get the following error in my developer console: `No match found for location with path "/_nuxt/C:/Users/<user>/Projects/nuxt-test/app/node_modules/nuxt/dist/app/entry.js"`

### Additional context

Tested on Windows 10 on Chrome, Firefox and Edge and on multiple devices. They all present the same behaviour.

Tested on Ubuntu 24. No problems there. Specs:
- Operating System: Linux
- Node Version:     v20.16.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.8.1
- Builder:          -
- User Config:      compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -

edit: added a stackblitz example of what causes the problem if you run this on Windows 10.

**Comment by lkrombeen** [comment]
After having spent 1 day on multiple operating systems I noticed the following: if I run the create command in a directory and there is a space or number somewhere in there (e.g. `C:\Users\myuser\Projects\Project%20JNuxt` I get the errors). If I do not, it seems to work. This might be the issue instead of it being windows 10 specifically.

**Comment by danielroe** [comment]
@lkrombeen I wouldn't be surprised. Previously I debugged a range of issues including in nuxt, rollup + vite, associated with having a space in the folder on windows machines. In the end I think we decided it was an edge case, as even if we resolved the issues in Nuxt, there were still incompatibilities in other projects we use.
