### ISSUE TITLE
useSeoMeta does not work anymore on dynamic link once the project is generated

### ISSUE THREAD

**Issue by gerkereitz** [nuxt/nuxt#28548]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.16.0`
- Nuxt Version:     `3.12.4`
- CLI Version:      `3.12.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `npm@10.8.1`
- Builder:          `-`
- User Config:      `app`, `compatibilityDate`, `devtools`, `modules`, `robots`, `runtimeConfig`, `site`, `sitemap`
- Runtime Modules:  `@nuxt/eslint@0.3.13`, `@nuxtjs/robots@4.0.2`, `@nuxtjs/sitemap@5.3.5`, `@nuxtjs/tailwindcss@6.12.1`
- Build Modules:    `-`

### Reproduction

Let me know if the description is not enough

### Describe the bug

Hello,

I have created a URL shortener using a Laravel API backend and a Nuxt frontend.

I am currently implementing an update where the SEO of the original URL gets applied to the new shortened url. The backend gets this information and gets returned to the frontend when the frontend call the API endpoint.

I tested if this SEO get applied fast/early enough to be applied to Whatsapp, which it does. This all works perfect during development (npm run dev) and when I build the project using npm run build.

However, I use npm run generate to build and deploy my project. And after the generation the SEO of the dynamic page (where the code gets extracted from the route using useRoute), the SEO no longer gets applied.

I first thought this had something to do with the API or lifecycles, but after testing hardcoding the seo data it even then does not get applied.

Current testing SEO values:
<img width="291" alt="image" src="https://github.com/user-attachments/assets/8bcdef63-f34f-494b-985a-d138ca58bbe2">

Which is on page [code].vue:
<img width="243" alt="image" src="https://github.com/user-attachments/assets/3ee2b1d2-bcc3-4b76-ab77-14ed2a2d770c">

I tested if the SEO gets applied on-time on Whatsapp using ngrok.

The SEO while running npm run dev or when running node .output/server/index.mjs after running npm run build:
<img width="423" alt="image" src="https://github.com/user-attachments/assets/5e5e501a-487f-4bcf-bc35-d444601c1df3">

The (lack of) SEO when serving the project after npm run generate:
<img width="433" alt="image" src="https://github.com/user-attachments/assets/7ce18c51-a4eb-4326-b533-89a38ceffab0">

This issue does not have to do with ngrok or the npx serve, because this also happens when having actually deployed it.

My guess is that is has to do with the prerendering. I have tried serveral prerendering and crawling settings but have had no luck so far.

**Comment by danielroe** [comment]
This is likely because when you are deploying a static site, it's going to serve up a 'blank' page for all those dynamic links - it gets purely client-side rendered. That's fine, but it won't have SEO metadata for WhatsApp to display in the preview.

Instead, why not build a site + use a SWR/ISR strategy to ensure each page can be generated on demand?

**Comment by gerkereitz** [comment]
@danielroe thank you for your reply.

I have been looking into these strategies but do not yet understand how they would enable the SEO to be picked up by Whatsapp for example/how it needs to be implemented in Nuxt, while still being able to run nuxt generate.

I understand the fact that it gets generated on the client side, however is there not a way for it to be picked up by Whatsapp?

I host this project on Hostinger so it needs to be a static export.

Any tips/help will be greatly appreciated.
