### ISSUE TITLE
Route Groups not working

### ISSUE THREAD

**Issue by MrGllitch** [nuxt/nuxt#28544]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.11.1
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      compatibilityDate, devtools, modules, supabase, prisma, primevue
- Runtime Modules:  @prisma/nuxt@0.0.35, @nuxtjs/tailwindcss@6.12.1, @nuxtjs/supabase@1.3.5, @primevue/nuxt-module@4.0.4
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-knndh4?file=app.vue
But issue is obvious i think

### Describe the bug

created (bar) folder in pages folder... just like in the docs 
https://nuxt.com/docs/guide/directory-structure/pages#route-groups
url need that /(bar)/ section

I think problem is the feature is 2 days old but still reporting... https://github.com/nuxt/nuxt/issues/20641

**Comment by DamianGlowala** [comment]
This feature hasn't been released yet. You can opt in to the nightly release channel to try it out without having to wait for v3.13.0 release: https://nuxt.com/docs/guide/going-further/nightly-release-channel

**Comment by thomaslecoeur** [comment]
@DamianGlowala This could be an information to specify in the doc

**Comment by gspgsp** [comment]
also meet this problem, It turned out to be a version problem. thanks.
