### ISSUE TITLE
Scroll margin is ignored when navigating to anchors

### ISSUE THREAD

**Issue by AndronKarp** [nuxt/nuxt#28556]
### Environment

- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-f9qibb

### Describe the bug

Doesn't work if interacting with a link or opening the page URL with hash in a new tab either

**Comment by danielroe** [comment]
This is resolved in https://github.com/nuxt/nuxt/pull/28320 and will be included in v3.13.0
