### ISSUE TITLE
fetch data as meta tag

### ISSUE THREAD

**Issue by heygsc** [nuxt/nuxt#28566]
### Describe the feature

The data fetched by the server is used as meta tags, and returned together from the server with the page.

Does `nuxt` have a similar solution to `next`? Or as a feature?

https://nextjs.org/docs/app/api-reference/functions/generate-metadata

<img width="662" alt="image" src="https://github.com/user-attachments/assets/193d61b0-9059-4dc6-8c46-8db388b4dd12">

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by MikeBellika** [comment]
Have you looked at [definePageMeta](https://nuxt.com/docs/api/utils/define-page-meta) or [SEO and Meta](https://nuxt.com/docs/getting-started/seo-meta)?

**Comment by heygsc** [comment]
> Have you looked at [definePageMeta](https://nuxt.com/docs/api/utils/define-page-meta) or [SEO and Meta](https://nuxt.com/docs/getting-started/seo-meta)?

Yeah, I have read it before. 
But after experimentation, once the await function is added, it seems that the request will be initiated on the client side.

**Comment by manniL** [comment]
@heygsc you need to use useFetch/useAsyncData to avoid duplicate requests
