### ISSUE TITLE
Nuxt3 .server (island) components fail to render "Request Header Fields Too Large" if you pass a lot of data to props

### ISSUE THREAD

**Issue by yesworld** [nuxt/nuxt#28567]
### Environment

- Operating System: Darwin
- Node Version:     v20.11.1
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@8.15.4
- Builder:          -
- User Config:      vite, css, modules, $development, srcDir, serverDir, colorMode, app, runtimeConfig, components, compatibilityDate, hooks
- Runtime Modules:  @nuxt/image@1.7.0, @nuxt/eslint@0.3.13, @nuxtjs/tailwindcss@6.12.1, @nuxtjs/color-mode@3.4.2, nuxt-icon@0.6.10, @vueuse/nuxt@10.11.0, @nuxtjs/device@3.1.1, vue3-carousel-nuxt@1.1.2
- Build Modules:    -

### Reproduction

_/src/pages/news/[id].vue_
```vue
<script setup lang="ts">
import type { ArticleType } from '@/types/models'

const id = useRouteParam<string>('id')

// fetch returns an Article object with large text!!
const { data } = await useFetch<ArticleType>(`/api/news/${id.value}`)
if (!data.value) {
  throw createError({ statusCode: 404, statusMessage: 'Page Not Found' })
}
</script>

<template>
  <ContentView :text="data.text" />  <!-- it's server component: ContentView.server.vue -->
</template>

```

_/src/components/content/ContentView.server.vue_

```vue
<script setup lang="ts">
defineProps<{ text: string }>()
</script>

<template>
  <article class="content">
    <div v-html="text"></div>
  </article>
</template>

```

_server side: /server/api/news/[id].get.ts_

```ts
export default defineEventHandler(async (event) => {
  try {
    return {
      text: 'Lorem ipsum dolor sit amet......', // For simple reproduce, it's enough to pass a text of approximately 50k chars.      
      // ....other fields
    }
  } catch (error) {
    throw createError({ statusCode: 404, message: 'Material not found' })
  }
})

```

### Describe the bug

I've a ContentView component that accepts article content from the API server, which I pass to v-html. 
My task is to render ContentView **ONLY** on the server side. For this, I added the **server** suffix to component (ContentView.**server**.vue).

but the problem is that a lot of data is passed to the ContentView component into props. 
```vue
<ContentView v-bind="data" />  <!-- DATA with a large amount of data information -->
```
and that's why I get error "431 Request Header Fields Too Large".

My browser request:
```
Request URL: http://localhost:3000/__nuxt_island/ContentView_KqN6hVg9ec.json?props=%7B%22text%22:%22Lorem+ipsum+dolor+sit+amet...... 50k chars
Request Method: GET
Status Code:  431 Request Header Fields Too Large
Remote Address: [::1]:3000
```

This probably not be a bug, but I need to do the component render only on the server side. Please any solutions.

Or, so that the request to ISLAND is not GET.

Thank you!

**Comment by danielroe** [comment]
This is not a bug but a limitation of the fact that server component props need to be passed in the URL. But you should probably refactor so the large data payload is fetched _within_ the server component based on a smaller prop (e.g. an id), rather than fetching and sending a lot of data to the component.

**Comment by n0099** [comment]
#22786
