### ISSUE TITLE
Nuxt 3.12.4 with Tailwindcss Take too long in loading and HMR

### ISSUE THREAD

**Issue by aminshafieed** [nuxt/nuxt#28579]
### Environment

Nuxt project info:                                                                                                                                                          3:47:44 PM

------------------------------
- Operating System: Linux
- Node Version:     v18.20.4
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.6.0
- Builder:          -
- User Config:      typescript, extends, imports, modules, tailwindcss, pinia, app, css, experimental, runtimeConfig, nitro, pwa, build, devtools, vite, compatibilityDate
- Runtime Modules:  nuxt-swiper@1.2.2, @pinia/nuxt@0.5.1, @nuxtjs/tailwindcss@6.12.1, nuxt3-leaflet@1.0.13, nuxt-rating@0.0.15, @nuxtjs/device@3.1.1, @vite-pwa/nuxt@0.9.1, @nuxt/image@1.7.0, @nuxtjs/seo@2.0.0-rc.18
- Build Modules:    -

### Reproduction
https://stackblitz.com/edit/github-xazavh?file=app.vue
-

### Describe the bug

I have an issue with nuxt3(3.12.4) @nuxtjs/tailwindcss. it takes around 20 seconds to restart development server, and also when i change even a text in my project, tailwind hot reloaded too and it causes HMR take more than 15 seconds.
without tailwind everything is ok.

![Screenshot from 2024-08-16 16-55-41](https://github.com/user-attachments/assets/1bc8cc5e-3bd2-4c7b-b6bb-7f79fb60c935)

**Comment by aminshafieed** [comment]
I added reproduction. you can see that on every change on page tailwindcss.css hot reloaded too. and it causes hot reloaded take too long on projects with a large number of components. it doesn't take too long on fresh install.
The more number of components, the longer hot reload time.

**Comment by huang-julien** [comment]
cc @ineshbose

**Comment by ineshbose** [comment]
Thanks for the ping @huang-julien. @aminshafieed, I'm yet to triage https://github.com/nuxt-modules/tailwindcss/issues/890 and this issue would likely be better suited for that repo, let's close this issue and move there? (I'll be investigating your issue this weekend)

**Comment by huang-julien** [comment]
Thank you @ineshbose ❤️ . I can't transfer the issue so i'll close it and let you guys open it in the tailwind repo
