### ISSUE TITLE
Nuxt SSR cant resolve local domain

### ISSUE THREAD

**Issue by ejerskov** [nuxt/nuxt#28572]
### Environment

- Operating System: `Darwin`
- Node Version:     `v22.6.0`
- Nuxt Version:     `3.11.2`
- CLI Version:      `3.11.1`
- Nitro Version:    `2.9.6`
- Package Manager:  `pnpm@8.15.6`
- Builder:          `-`
- User Config:      `devtools`, `extends`, `routeRules`, `modules`, `delayHydration`, `css`, `devServer`, `runtimeConfig`, `features`, `experimental`, `nitro`, `vite`
- Runtime Modules:  `nuxt-delay-hydration@1.3.3`, `@pinia/nuxt@0.5.3`
- Build Modules:    `-`

### Reproduction

I've set up a API server locally through a local server environment, so that my API is available through api.localhost.
Im fetching data in my Nuxt app with useFetch.

### Describe the bug

When doing the fetch SSR, it doesnt seem to be able to resolve the domain, so it must be ignoring my local host, as I just get an error.
But when the same request is done through the client (Chrome), it's working fine.

**Comment by danielroe** [comment]
I'd guess that domain doesn't work within Node but works from your browser. It's unlikely to be a Nuxt issue.

Try running:

```bash
node -e "fetch('<your url>').then(res => res.json()).then(console.log).catch(console.error)"
```

**Comment by haiming236** [comment]
I have tried many methods but cannot proxy other backend ports, including Nitro
![PixPin_2024-08-16_22-09-09](https://github.com/user-attachments/assets/14921850-5233-45bb-a37a-fb8e214c5f20)

**Comment by ejerskov** [comment]
Thanks @danielroe, your suggestion lead me on the right path.
Running:
`node -e "fetch('<your url>').then(res => res.json()).then(console.log).catch(console.error)"`

Gave me an error I haven't been able to find when running my app:

`Error: unable to get local issuer certificate`

So for some reason node cant pass my local certificate that works fine in Chrome.
I've then found that adding the following to my local .env will allow node to bypass this error:

`NODE_TLS_REJECT_UNAUTHORIZED=0`

So now my local domain is also working SSR.
