### ISSUE TITLE
Github Pages preset does not run Sitemap Module

### ISSUE THREAD

**Issue by nekdolan** [nuxt/nuxt#28588]
### Environment

- Operating System: Darwin
- Node Version:     v18.20.2
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.5.0
- Builder:          -
- User Config:      compatibilityDate, site, devtools, modules
- Runtime Modules:  @nuxtjs/sitemap@6.0.0-beta.2
- Build Modules:    -

### Reproduction

https://github.com/nekdolan/nuxt-sitemap-github-preset-issue

Reproduction:
* install nuxt
* install @nuxtjs/sitemap
* run npx nuxt build --preset github_pages

### Describe the bug

The nuxt github pages preset does not generate the sitemap.xml of the nuxt sitemap module. Since nuxt generate does add the sitemap this is an issue with the preset and not the module (probably).

**Comment by danielroe** [comment]
Have you raised this in https://github.com/nuxt-modules/sitemap ?

**Comment by nekdolan** [comment]
> Have you raised this in https://github.com/nuxt-modules/sitemap ?

No. The sitemap script doesn't seem to start so I don't think they would be able to do anything about it. I think Nuxt generate and the github preset should be transparent as far as external modules are concerned.

**Comment by danielroe** [comment]
Having checked, this is likely an issue with the module.

It currently checks for `github-pages` preset but you are using `github_pages`.

https://github.com/nuxt-modules/sitemap/blob/main/src/prerender.ts#L40-L45

**Comment by nekdolan** [comment]
Running `npx nuxt build --preset github-pages` also does not produce a sitemap . @danielroe

**Comment by danielroe** [comment]
It's still an issue with the module.

**Comment by harlan-zw** [comment]
> Having checked, this is likely an issue with the module.
> 
> It currently checks for `github-pages` preset but you are using `github_pages`.
> 
> [nuxt-modules/sitemap@`main`/src/prerender.ts#L40-L45](https://github.com/nuxt-modules/sitemap/blob/main/src/prerender.ts?rgh-link-date=2024-08-21T11%3A43%3A11Z#L40-L45)

Actually it's because [I wasn't passing in the nitro config](https://github.com/nuxt-modules/sitemap/commit/2f6bca8f698faf7aa9d925d5eec1f99a7d754d45) 🙃
