### ISSUE TITLE
NuxtErrorBoundary is't working when refresh page

### ISSUE THREAD

**Issue by linpengteng** [nuxt/nuxt#28580]
### Environment

- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      compatibilityDate, devtools, ssr
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

The demo is as follows:
https://stackblitz.com/edit/github-y5mrbm?file=pages%2Fdemo.vue

### Describe the bug

NuxtErrorBoundary can only take effect during client-side routing navigation. When refreshing the page, the error slot content cannot be rendered in ssr mode.

- navigate from the `/` homepage to the `/demo` page, rendering is normal
  <img width="1671" alt="image" src="https://github.com/user-attachments/assets/f5b73d7f-2ecb-496a-b612-3f8b04be2fdb">
   
- in non-ssr mode, refresh the /demo page and it renders normally.
   <img width="1667" alt="image" src="https://github.com/user-attachments/assets/e9d2c9f9-08e2-4fc9-ae27-0014955cdf96">

- in `ssr` mode, refresh the `/demo` page and report an error
   <img width="1662" alt="image" src="https://github.com/user-attachments/assets/872e91c0-c412-4ab1-82df-4d55f0d769b3">
   
1. If the ssr mode needs to be compatible with both client-side routing navigation and page refresh exception handling, should I use NuxtErrorBoundary and NuxtClientFallback at the same time, and nested to handle child component exceptions?

2. Another question, I tried to customize the ErrorBoundary component to wrap the Child component to handle it, but useError() gets undefined. In what scenarios is useError used? Please tell me，I need help.

### Additional context

None

**Comment by huang-julien** [comment]
Hello :wave: 

`NuxtErrorBoundary` only handles errors client side. If you wish to handle errors in SSR, you need ot use `NuxtClientFallback` with `experimental.clientFallback` enabled in your config

**Comment by linpengteng** [comment]
@huang-julien  
hey, if it is compatible with client navigation and server rendering exception handling, is there any good way at present?

**Comment by linpengteng** [comment]
@huang-julien 
Excuse me, I have another question. I have searched and studied the Nuxt documentation, but there is no example of using `useError`. In what scenarios is `useError` applicable?
