### ISSUE TITLE
Clarify the naming conventions for hooks

### ISSUE THREAD

**Issue by typed-sigterm** [nuxt/nuxt#28581]
### Describe the feature

In Nuxt 3.12, hooks using kebab-case:

- `dev:ssr-logs`
- `page:view-transition:start`
- `nitro:build:public-assets`
- (nitro) `dev:ssr-logs`

Hooks using camelCase:

- `app:templatesGenerated`
- `builder:generateApp`
- `pages:routerOptions`
- `server:devHandler`
- `schema:beforeWrite`
- `vite:extendConfig`
- `vite:configResolved`
- `vite:serverCreated`
- `webpack:configResolved`
- (nitro) `beforeResponse`
- (nitro) `afterResponse`

Different naming styles may cause some confusion, but the existing hook naming styles seem to have some patterns - using camelCase only when the hook name is the same as the function/parameter name.

If there is a clear specification or a unified naming style in the contribution guidelines, it would be great :heart:

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
We're inclined to use kebab case for new hooks, but not make any kind of breaking change on existing hooks.
