### ISSUE TITLE
Unable to use fetch API on Azure Static web apps

### ISSUE THREAD

**Issue by censujiang** [nuxt/nuxt#28611]
### Environment

```console
------------------------------
- Operating System: Windows_NT
- Node Version:     v20.9.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  bun@1.1.23
- Builder:          -
- User Config:      compatibilityDate, devtools, nitro
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Reproduction

[https://github.com/censujiang/nuxt-azure-500-problem](https://github.com/censujiang/nuxt-azure-500-problem)

### Describe the bug

In this product environment of Azure, even if it is set to node:20, it still does not include the fetch api

### Additional context

A valid Azure subscription is required to test Static web apps. This error only occurs in the cloud, not in the local simulator.

### Logs

```shell-script
{
    "url": "/api/test",
    "statusCode": 500,
    "statusMessage": "",
    "message": "[GET] \"https://www.baidu.com\": <no response> _fetch1 is not a function",
    "stack": ""
}
```

**Comment by censujiang** [comment]
> Would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏

I will try it

**Comment by censujiang** [comment]
> > Would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏
> 
> I will try it

Is there: [https://github.com/unjs/nitro/issues/2676](https://github.com/unjs/nitro/issues/2676)

**Comment by danielroe** [comment]
Thank you - we'll track there ❤️
