### ISSUE TITLE
Host header for local api hits should match the domain from the original request

### ISSUE THREAD

**Issue by hecktarzuli** [nuxt/nuxt#28615]
### Environment

- Operating System: Linux
- Node Version:     v20.9.0
- Nuxt Version:     3.11.2 (I couldn't get latest to work in Codesandbox)
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

Create an api in your nuxt project.
Call that api from a page, server side.
https://codesandbox.io/p/devbox/nuxt3-api-localhost-k72dwg

### Describe the bug

When Nuxt talks to itself server-side, `event.node.req.header.host` is `localhost` .  The docs suggest the functions are called directly.

![image](https://github.com/user-attachments/assets/b55eb50e-a86b-4342-8cec-d43b6df9f113)

If Nuxt does just call the functions directly, then I would expect it to also spoof the host by passing it from the calling server-side context.

If Nuxt truly uses localhost, then the docs should be updated and I'd expect the original host to be in `x-forwarded-for`.

### Additional context

In our case, we're running Nuxt multi-tenant.  Each domain talks to the apis via the domain that's running.  We were leveraging the host throughout the app to know which data to return but in the case above, server-side api hits couldn't figure out the host (since it's always `localhost`) while client-side hits were fine.

**Comment by danielroe** [comment]
You need to use useRequedtFetch or event.$fetch to get a fetch that is bound to the event. Otherwise Nuxt has no way to know _what_ request the request belongs to.

**Comment by hecktarzuli** [comment]
I'm not sure how you'd get the host header from `event.$fetch`.  It seems to just be a function.

**Comment by danielroe** [comment]
Not entirely sure what you mean, but `event.$fetch` passes on the request headers. If you want to read the _response_ headers you can use `event.fetch` which returns them.
