### ISSUE TITLE
third-party module type hints  error

### ISSUE THREAD

**Issue by coderfreii** [nuxt/nuxt#28622]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.11.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.3.0
- Builder:          -
- User Config:      compatibilityDate, devtools, devServer, modules, primevue, sourcemap, nitro, robots, sitemap, schemaOrg
- Runtime Modules:  @primevue/nuxt-module@4.0.4, @nuxtjs/seo@2.0.0-rc.18
- Build Modules:    -
------------------------------

### Reproduction

First, I ran the command `npx nuxi@latest module add seo ` to add the SEO module to my Nuxt project. Then, I encountered an issue that the type hints for  `defineWebSite`  function are not functioning correctly.

### Describe the bug

https://github.com/unjs/unhead/blob/main/packages/schema-org/package.json

```typescript
  //file .nuxt\types\imports.d.ts

  const defineWebPage: typeof import('../../node_modules/.pnpm/@unhead+schema-org@1.9.16/node_modules/@unhead/schema-org/vue')['defineWebPage']
  const defineWebSite: typeof import('../../node_modules/.pnpm/@unhead+schema-org@1.9.16/node_modules/@unhead/schema-org/vue')['defineWebSite']
```

Because  `./vue` is a `Subpath Export` rather than a real path, the import function cannot correctly import it.

If it were changed to the following, the type hints would work correctly.
```typescript
  const defineWebPage: typeof import('../../node_modules/.pnpm/@unhead+schema- org@1.9.16/node_modules/@unhead/schema-org/dist/vue')['defineWebPage']
```

**Comment by harlan-zw** [comment]
Hi, please make an issue on https://github.com/unjs/unhead with a reproduction if you're still having issues.
