### ISSUE TITLE
Nuxt Layers are sharing their config

### ISSUE THREAD

**Issue by emirhanyagci** [nuxt/nuxt#28627]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.17.1
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@9.6.7
- Builder:          -
- User Config:      compatibilityDate, devtools, extends, runtimeConfig, modules, pinia, imports, app, css, postcss, image, basicAuth
- Runtime Modules:  @kgierke/nuxt-basic-auth@1.6.0, @nuxtjs/tailwindcss@6.12.1, @nuxt/content@2.13.2, @nuxt/image@1.7.0, @pinia/nuxt@0.5.3, nuxt-swiper@1.2.2
- Build Modules:    -

### Reproduction

workspace layer's `nuxt.config.ts` : 

```typescript
import Aura from '@primevue/themes/aura';

export default defineNuxtConfig({
  modules: ['@primevue/nuxt-module'],
  primevue: {
    autoImport: true,
    usePrimeVue: true,
    options: {
      theme: {
        preset: Aura,
        darkModeSelector: 'dark',
      },
      unstyled: false, // playground mode: true
    },
    components: {
      prefix: 'Prime',
      include: '*',
    },
  },
});
```
root `nuxt.config.ts` :

```typescript
export default defineNuxtConfig({
  compatibilityDate: '2024-04-03',
  devtools: { enabled: true },
  extends: ['./workspace'],
  runtimeConfig: {
    baseUrl: process.env.BASE_URL,
  },

  modules: [
    '@nuxtjs/tailwindcss',
    '@nuxt/content',
    '@nuxt/image',
    '@pinia/nuxt',
  ],

  pinia: {
    storesDirs: ['./stores/**'],
  },

  imports: {
    dirs: ['stores'],
  },

  app: {
    head: {
      meta: [
        {
          name: 'viewport',
          content: 'width=device-width, initial-scale=1.0',
        },
        { hid: 'robots', name: 'robots', content: 'noindex' },
      ],
    },
  },

  css: ['~/assets/css/main.css'],

  postcss: {
    plugins: {
      tailwindcss: {},
      autoprefixer: {},
    },
  },

  

  
});
```

### Describe the bug

I have a layer name of workspace i want use PrimeVue components in this layer but in root prime vue should not effect.

This is my workspace layer and inside of `/workspace/pages/workspace.vue` :
![image](https://github.com/user-attachments/assets/6bef4a44-ba4d-4dd5-86e6-4ccfe4f2eff2)

```typescript
<template>
  <PrimeTag severity="success" value="New"></PrimeTag>
</template>

<script>
export default {};
</script>

<style></style>
```
this is my `/pages/index.vue` :

```typescript
<template>
  
  <PrimeTag severity="success" value="New"></PrimeTag>
</template>

<script>
export default {
  mounted() {
    console.log(useAppConfig());
    console.log(useRuntimeConfig());
  },
};
</script>

<style></style>
```

In this case i don't want to be useable PrimeVue components expect workspace layer, the primevue css should not effect anything expect workspace layer but in the configs are merged , what can i do ?
I'm not strict to use layer system i explanation of my needs is that possible ?

**Comment by danielroe** [comment]
By default layers are meant to be merged into a single configuration for the 'final' Nuxt app. This is expected behaviour.

**Comment by emirhanyagci** [comment]
Do you have any advice , how can I find a solution ?

**Comment by danielroe** [comment]
Could you explain a bit more about what you want - and why?

**Comment by emirhanyagci** [comment]
Sure, I'm using PrimeVue at part of my app think like have 2 page  `/workspace` and `/playground` i have components in this workspace i can see my components think like storybook and i use PrimeVue for this layout for example SelectBox for listing my components after that i can see specific component in `playground` e.g `playground/Navbar`  at playground sometimes the primevue classes effect the my component . I don't want use PrimeVue components and classes in /playground route.
I hope I explained it well

**Comment by danielroe** [comment]
That would be a feature request for Primevue I think, and it's not a straightforward one.

**Comment by emirhanyagci** [comment]
Okay , thanks anyway
