### ISSUE TITLE
Prerendering fails when `viteCompression` plugin is used

### ISSUE THREAD

**Issue by hybridherbst** [nuxt/nuxt#28626]
### Environment

I ran into this because my previous vite config had the viteCompression plugin (for gzipping stuff during build).
Turns out this breaks `npm nuxi generate` with the error:
<img width="1128" alt="image" src="https://github.com/user-attachments/assets/5a129458-67f8-4d23-9049-38c28dd3ac32">

Looking into this directory, it seems that the file has already been gzipped at this point:
<img width="330" alt="image" src="https://github.com/user-attachments/assets/442a558d-ec43-4d47-bebb-9a15f4e65890">

### Reproduction

Add
```
import viteCompression from 'vite-plugin-compression';

...

vite: {
    viteCompression({
                deleteOriginFile: true,
            })
}
```

to nuxt.config.js.

### Describe the bug

This might just be a documentation issue for the migration path from vite + vue to nuxt. I'm not sure how I'd apply gzip after building at the moment.

**Comment by danielroe** [comment]
Yes, this is incompatible - we need to consume that file in the next build step (and will delete it too). If you want, you would need to apply the compression after nitro build, which you can do with `nitro.compressPublicAssets`.
