### ISSUE TITLE
Can't get relative builds to work: Building with `baseURL: "./"` doesn't result in relative paths, building with `baseURL: "."` breaks subpages

### ISSUE THREAD

**Issue by hybridherbst** [nuxt/nuxt#28624]
### Environment

Locally:
------------------------------
- Operating System: Darwin
- Node Version:     v20.9.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    -
- Package Manager:  npm@10.8.2
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

On StackBlitz:
------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      compatibilityDate, app, nitro, ssr, devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

For `./`: https://stackblitz.com/edit/nuxt-starter-qy4cwr
For `.`: https://stackblitz.com/edit/nuxt-starter-qum3vc

Run `npm run build` and note that the generated html files still contain absolute href="/_nuxt/..." paths.

Config:
```js
export default defineNuxtConfig({
  compatibilityDate: '2024-04-03',
  app: {
    baseURL: './',
  },
  nitro: {
    preset: 'static',
  },
  ssr: false,
  devtools: { enabled: false },
});
```

### Describe the bug

It seems that relative paths in baseURL are stripped out and the resulting built files always contain absolute paths. This breaks deployment for environments where the deployment path is not known in advance.

### Additional context

This advice from 2022 (for a prerelease of Nuxt3 I believe) doesn't seem to work anymore: 
https://github.com/nuxt/nuxt/issues/13780#issuecomment-1397314850

Another related question:  
https://github.com/nuxt/nuxt/discussions/25377

### Logs

Note absolute paths being served:

```shell-script
❯ npx serve .output/public

   ┌───────────────────────────────────────────┐
   │                                           │
   │   Serving!                                │
   │                                           │
   │   - Local:    http://localhost:3000       │
   │   - Network:  http://192.168.1.104:3000   │
   │                                           │
   └───────────────────────────────────────────┘

 HTTP  21/08/2024 12:48:49 unknown GET /
 HTTP  21/08/2024 12:48:49 unknown Returned 200 in 25 ms
 HTTP  21/08/2024 12:48:50 unknown GET /_nuxt/entry.ASuS4Yfc.css
 HTTP  21/08/2024 12:48:50 unknown GET /_nuxt/DBKEdZV3.js
 HTTP  21/08/2024 12:48:50 unknown GET /_nuxt/error-404.CjGVuf6H.css
 HTTP  21/08/2024 12:48:50 unknown GET /_nuxt/B2lq2bkl.js
 HTTP  21/08/2024 12:48:50 unknown GET /_nuxt/error-500.DFBAsgKS.css
 HTTP  21/08/2024 12:48:50 unknown GET /_nuxt/8NiZr2_d.js
 HTTP  21/08/2024 12:48:50 unknown Returned 200 in 28 ms
 HTTP  21/08/2024 12:48:50 unknown Returned 200 in 45 ms
 HTTP  21/08/2024 12:48:50 unknown Returned 200 in 25 ms
 HTTP  21/08/2024 12:48:50 unknown Returned 200 in 24 ms
```
```

**Comment by hybridherbst** [comment]
To me it looks like `./` is prevented here for some reason:

https://github.com/nuxt/nuxt/blob/161a1f10ee8646addad011cf1e6f8b6c1ed20a8d/packages/schema/src/config/nitro.ts#L18-L20

**Comment by hybridherbst** [comment]
I tried to roll with `baseURL: "."` to at least get things going for the main page.

1. There are warnings logged to the console that this is an invalid `baseURL`, so I'm again not sure what the correct approach to make relative builds is.
2. When deploying to an actual server in a subdirectory, the router seems to still assume absolute paths, so wherever I put the result besides a root URL, I always get "page not found: <insert subdirectory that should be irrelevant here>".

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/28474.

**Comment by hybridherbst** [comment]
Thank you for referencing those!
