### ISSUE TITLE
配置了i18n的baseUrl，locales，没有自动生成hreflang

### ISSUE THREAD

**Issue by xuzhihui123** [nuxt/nuxt#28623]
### Environment

{
		"nuxt": "3.12.2",
		"@nuxtjs/i18n": "8.3.1",
}

### Reproduction

我再nuxt.config.ts配置
  i18n: {
    baseUrl: envObj.Website_Url,
    locales,
    lazy: true,
    defaultLocale: defaultLocale,
    langDir: "lang/",
    strategy: i18nStrategy,
    detectBrowserLanguage: {
          useCookie: true,
          cookieKey: "language",
          redirectOn: "root", // recommended
          cookieCrossOrigin: false,
          cookieSecure: true,
          cookieDomain: null,
          alwaysRedirect: true
        }
  }
没有自动生成locales语言的hreflang

### Describe the bug

我再nuxt.config.ts配置
  i18n: {
    baseUrl: envObj.Website_Url,
    locales,
    lazy: true,
    defaultLocale: defaultLocale,
    langDir: "lang/",
    strategy: i18nStrategy,
    detectBrowserLanguage: {
          useCookie: true,
          cookieKey: "language",
          redirectOn: "root", // recommended
          cookieCrossOrigin: false,
          cookieSecure: true,
          cookieDomain: null,
          alwaysRedirect: true
        }
  }
没有自动生成locales语言的hreflang

**Comment by danielroe** [comment]
Would you raise this in https://github.com/nuxt-modules/i18n ? 🙏
