### ISSUE TITLE
Why are the bullet points hidden?

### ISSUE THREAD

**Issue by dncmaduro** [nuxt/nuxt#28636]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.11.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  yarn@1.22.22
- Builder:          -
- User Config:      modules, colorMode, devtools, srcDir,
 css, compatibilityDate
- Runtime Modules:  @nuxt/ui@2.18.4, @nuxtjs/google-fonts@3.2.0, @nuxt/eslint@0.4.0, @nuxt/image@1.7.0
- Build Modules:    -

### Reproduction

This is my MembersDetailInformation component
```vue
<template>
  <div class="flex flex-col gap-4">
    <div>
      <span class="text-lg font-bold">About this member</span>
      <ul>
        <li v-for="item in about" :key="item">{{ item }}</li>
      </ul>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { MembersDetailInformationProps } from '~/types/members'

defineProps<MembersDetailInformationProps>()
</script>
```

This is the props of above component
```ts
export type MembersDetailInformationProps = {
  about: string[]
  activites: string[]
  quote: string
}
```

And data for above component
```ts
{
  about: [
    'Lorem ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum',
    'Lorem ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum',
    'Lorem ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum'
  ],
  activites: [
    'Lorem ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum',
    'Lorem ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum',
    'Lorem ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum'
  ],
  quote: 'Lorem ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum',
}
```

### Describe the bug

I don't know why the bullet points of the ul tag disappeared.
![image](https://github.com/user-attachments/assets/b0419e3a-c04a-4087-897e-3becf433586d)

I think my issue is very easy to deal with, but I still cannot find the solution :((((

**Comment by danielroe** [comment]
As Nuxt UI uses tailwindcss, it adds a CSS reset that removes default styling of bullets.

See more: https://tailwindcss.com/docs/preflight#lists-are-unstyled
