### ISSUE TITLE
[SSR] Possible bug with Intl.DisplayNames of type region

### ISSUE THREAD

**Issue by Kheuval** [nuxt/nuxt#28644]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v22.6.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    -
- Package Manager:  pnpm@9.5.0
- Builder:          -
- User Config:      compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/Kheuval/intl-reproduction

### Describe the bug

Hello !

I face an issue with Intl on SSR.
When using `new Intl.DisplayNames("en", { type: "region" })` and then `console.log(regionNames.of("fr"))` in a vue component, I get a different result on the server comparing to the client : 

![image](https://github.com/user-attachments/assets/0a49c5ed-3bc0-48c2-8dc1-110d571f3f8f)

Note that it works as intended with the types `language` and `currency`.

You can test it yourself by cloning this repo : https://github.com/Kheuval/intl-reproduction

The issue doesn't seem to be on the Nitro side as I tested it here : https://stackblitz.com/edit/github-fo7zum?file=server%2Froutes%2Findex.ts but I might be wrong.

Thanks for your help :)

**Comment by danielroe** [comment]
This is likely a caveat with SSR.

`nuxt-time` exists to handle this: https://github.com/danielroe/nuxt-time.

I'd welcome an issue for adding Intl.DisplayNames to nuxt-time.

**Comment by Kheuval** [comment]
Thanks for your answer, will do !
