### ISSUE TITLE
`useRoute` params are stale in `asyncData` of `defineNuxtComponent`

### ISSUE THREAD

**Issue by spocock** [nuxt/nuxt#28650]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.10.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@8.19.2
- Builder:          -
- User Config:      compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

[https://stackblitz.com/edit/github-k2nryo?file=pages%2Fdetail%2F%5BitemSlug%5D.vue](https://stackblitz.com/edit/github-k2nryo?file=pages%2Fdetail%2F%5BitemSlug%5D.vue)

Navigate from this page to the linked pages and the route is stale

### Describe the bug

When accessing params inside a page which uses defineNuxtComponent() and asyncData() the 
useRoute() inside asyncData() is "stale", in that it describes the page from which arrived, not the page being loaded. So the param is not available in the page being loaded.

This happens on internal navigation using `<nuxt-link>`, though not on direct access via URL.

This has started since we upgraded from 3.2.x to 3.4.x 

We are using `<NuxtPage/>`

There is a workaround to use `useRouter().currentRoute.value` which we found in #20471

It seems similar to #20471 but different situation, so may be it is expected behaviour, however it has changed from past behaviour.

**Comment by JulianMar** [comment]
We face the same challenge while upgrading from 3.11.x to 3.12.4.
Thanks for the workaround!

**Comment by JulianMar** [comment]
After some investigation I think it's an Issue with Vue. After downgrading to Vue 3.4.36 it's working again (see reproduction).
The error seems to be caused by version 3.4.37. There are a few changes but I don't know yet which could be the cause of this behaviour.

Working reproduction: https://stackblitz.com/edit/github-k2nryo-xfnxkq?file=package.json

**Comment by tada5hi** [comment]
@JulianMar using `defineComponent` instead of `defineNuxtComponent` solved the issue for me.
