### ISSUE TITLE
routeRules proxy omits Content-Encoding header

### ISSUE THREAD

**Issue by ceigh** [nuxt/nuxt#28655]
### Environment

Working directory: /Users/hcg/src/eventico/frontend                        17:03:06
Nuxt project info: (copied to clipboard)                                   17:03:06

------------------------------
- Operating System: Darwin
- Node Version:     v20.15.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7

### Reproduction

https://stackblitz.com/edit/nuxt-routerules-proxy-headers?file=app.vue

### Describe the bug

It looks like the `proxy` in `routeRules` discards some of the original headers, for example `Content-Encoding`, which is why the browser cannot decode the response.

```sh
curl -I -H 'Accept-Encoding: zstd' https://jsonplaceholder.typicode.com/posts/1

HTTP/2 200
date: Thu, 22 Aug 2024 12:49:04 GMT
content-type: application/json; charset=utf-8
report-to: {"group":"heroku-nel","max_age":3600,"endpoints":[{"url":"https://nel.heroku.com/reports?ts=1711077658&sid=e11707d5-02a7-43ef-b45e-2cf4d2036f7d&s=ixZzjDc3xydb7LMRsUjuls3TRDxIflCoNWj%2FTgKJnX0%3D"}]}
reporting-endpoints: heroku-nel=https://nel.heroku.com/reports?ts=1711077658&sid=e11707d5-02a7-43ef-b45e-2cf4d2036f7d&s=ixZzjDc3xydb7LMRsUjuls3TRDxIflCoNWj%2FTgKJnX0%3D
nel: {"report_to":"heroku-nel","max_age":3600,"success_fraction":0.005,"failure_fraction":0.05,"response_headers":["Via"]}
x-powered-by: Express
x-ratelimit-limit: 1000
x-ratelimit-remaining: 999
x-ratelimit-reset: 1711077718
vary: Origin, Accept-Encoding
access-control-allow-credentials: true
cache-control: public, max-age=43200
pragma: no-cache
expires: Fri, 23 Aug 2024 00:49:04 GMT
x-content-type-options: nosniff
etag: W/"124-yiKdLzqO5gfBrJFrcdJ8Yq0LGnU"
via: 1.1 vegur
cf-cache-status: HIT
age: 27058
server: cloudflare
cf-ray: 8b72fb1498bc1ca2-AMS
content-encoding: zstd
alt-svc: h3=":443"; ma=86400
```

But in my [reproduction](https://stackblitz.com/edit/nuxt-routerules-proxy-headers?file=app.vue) with proxy just:

```js
{
  "cache-control": "public, max-age=43200",
  "connection": "close",
  "content-type": "application/json; charset=utf-8",
  "cross-origin-embedder-policy": "credentialless",
  "cross-origin-opener-policy": "same-origin",
  "cross-origin-resource-policy": "cross-origin",
  "date": "Thu, 22 Aug 2024 12:44:58 GMT",
  "expires": "Fri, 23 Aug 2024 00:44:58 GMT",
  "pragma": "no-cache",
  "transfer-encoding": "chunked"
}
```

What could this be related to?

Thanks for the help!

**Comment by danielroe** [comment]
Would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏

**Comment by ceigh** [comment]
Strangely, right while working on the reproduction, the Content-Encoding header disappeared from the original response, even more strangely, now everything is working well 🙂. Maybe there was some kind of local problem, I think the issue can be closed.

**Comment by MrEAlderson** [comment]
Possibly related: https://github.com/unjs/h3/issues/891

**Comment by Daluzz9** [comment]
same issue
