### ISSUE TITLE
Async/Await in router.options.ts with a nuxt composables breaks the app

### ISSUE THREAD

**Issue by SmootherSpike** [nuxt/nuxt#28661]
### Environment

- Operating System: `Darwin`
- Node Version:     `v22.2.0`
- Nuxt Version:     `3.13.0`
- CLI Version:      `3.12.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `yarn@1.22.19`
- Builder:          `-`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-i2zbwk?file=app%2Frouter.options.ts

### Describe the bug

Using a nuxt composables like useNuxtApp or useRuntimeConfig inside the routes function in the router.options.ts was and is still possible if the routes are NOT written as async/await. 

With the new possibility added in 3.13.0 to await an api call, it's breaks the application.

We are using the useNuxtApp() to retrieve some plugins which are `enforce: pre` to load pages of modules which can extend the router during runtime before the router is initialized.

Nevertheless the reproduction of this issues shows the principle idea. 

Thank you in advance to take a look at this
Mattias

### Additional context

This bug was introduced with the possibility of having routes method in router.options.ts to be async/await in https://github.com/nuxt/nuxt/pull/27644

### Logs

```shell-script
Error: [nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at https://nuxt.com/docs/guide/concepts/auto-imports#vue-and-nuxt-composables. error=Error: [nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at https://nuxt.com/docs/guide/concepts/auto-imports#vue-and-nuxt-composables.
    at Module.useNuxtApp (/Users/mhaberbusch/Dev/digital-tp/web-frontend-svc/node_modules/nuxt/dist/app/nuxt.js:252:13)
    at Object.routes (/Users/mhaberbusch/Dev/digital-tp/web-frontend-svc/app/router.options.ts:11:51)
```

**Comment by danielroe** [comment]
You should access the Nuxt context before the first await, and if necessary use nuxtApp.runWithContext to call subsequent composables.

**Comment by SmootherSpike** [comment]
Thanks for the fast answer and hint, but still if i move the useRuntimeConfig above the first await, it fails with another issue -> 
`[nuxt] error caught during app initialization TypeError: Cannot read properties of undefined (reading 'beforeEach')
    at setup (nuxt-root.vue:39:14)`
Although the routes are correctly logged to the console as an array. you can see the server error, i updated the stackblitz.
If the async/await code is removed, it works fine @danielroe

**Comment by danielroe** [comment]
That is because in your reproduction you are still using v3.12.4.

**Comment by SmootherSpike** [comment]
Sorry i just used the link from the reproduction issue. thanks for the hint and sorry for the troubles here :)

**Comment by danielroe** [comment]
No worries! I think the stackblitz hadn't yet updated with the new release.
