### ISSUE TITLE
Server side useCookie problem

### ISSUE THREAD

**Issue by halil-erbil** [nuxt/nuxt#28683]
### Environment

Development

### Reproduction

Reproduction

### Describe the bug

paymentId: string = "1234"
.
.
.
server/middleware/request-handler.ts
setCookie(event, "paymentId", paymentId, {})
.
.
.
pages/checkToken.vue
const paymentId = useCookie("paymentId", { default: () => "", watch: "shallow" })
.
.
.
paymentId is string but when get paymentId this value automatically convert to number

**Comment by danielroe** [comment]
by default string numbers deserialise into numbers but you can customise this behaviour by providing a custom `decode` function in the options to `useCookie`.
