### ISSUE TITLE
Deploy production without node_modules directory

### ISSUE THREAD

**Issue by kdivan** [nuxt/nuxt#28680]
### Describe the feature

Hi Nuxt team,

I didn't find it in the documentation so : As a feature request, we want the possibility to deploy Nuxt applications in production without including the node_modules directory. .nuxt currently has references to files located at ../../node_modules/… which causes deployment of an optimized build difficult as these third-party dependencies are still required even after building process. This will help reducing the size of the deployment package.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
You should deploy the .output directory, which is self contained, not the .nuxt directory which is an intermediate build artifact.

If .output has references to any files outside that directory, please provide a reproduction - that would be a bug.

**Comment by kdivan** [comment]
In fact it is ok with the .output and .output has not any references to any files outside that directory. Thanks for the answer
