### ISSUE TITLE
serverDir not being registered

### ISSUE THREAD

**Issue by nunonux** [nuxt/nuxt#28695]
### Environment

- Operating System: Linux
- Node Version:     v20.16.0
- Nuxt Version:     3.13.0
- CLI Version:      3.13.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.7.1
- Builder:          -
- User Config:      compatibilityDate, ssr, devtools, srcDir, serverDir, devServer, vue, build, imports, components, hooks, sourcemap
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

Github Repo: https://github.com/nunonux/nuxt-serverdir-issue
StackBlitz: https://stackblitz.com/edit/github-adnwzy?file=nuxt.config.ts

### Describe the bug

When I set the _**serverDir**_ property in nuxt.config.ts with the value _**'/src/server'**_, nuxt don't r**egister the routes** in the api folder. 
So, if I send an request for a route in the api folder, I get an 404 request error.

### Additional context

Normally I structure my nuxt app as:
src/
  app/
  server/
It has been working great until the nuxt version 1.12.4 and 1.13.0, that's were it breaks my current app.

**Comment by huang-julien** [comment]
Hey :wave: thanks for opening the issue ! It's indeed a bug; It should be relative to the root dir according to the docs. But it's currently relative to your srcDir rn without V4 compatibility.

@danielroe i'll open a PR to fix it. Let me know if we should just correct the doc instead
