### ISSUE TITLE
Potential Memory Leak

### ISSUE THREAD

**Issue by dissy123** [nuxt/nuxt#28690]
### Environment

- Operating System: `Darwin`
- Node Version:     `v22.7.0`
- Nuxt Version:     `3.13.0`
- CLI Version:      `3.13.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `pnpm@8.15.3`
- Builder:          `-`
- User Config:      `compatibilityDate`, `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Fresh nuxt 3.13.0 install via npx  i tried different node versions like all major version, it is literally happening on every node version. 
when running with node --inspect .output/server/index.mjs

### Describe the bug

Memory Leaking with SSR enabled when doing 

`ab -n 100 -c 50 "http://localhost:3000/"`

<img width="1502" alt="image" src="https://github.com/user-attachments/assets/7cc495b5-4af5-4576-ba90-dba4c87acd58">
<img width="642" alt="image" src="https://github.com/user-attachments/assets/7cf72439-6ec5-4432-8546-2f8173dcd02a">

**Comment by danielroe** [comment]
Is this new behaviour? Did you garbage collect before and after taking snapshots? And yes, I do need a reproduction. 🙏

**Comment by dissy123** [comment]
https://github.com/dissy123/nuxt-memory-leak
reproduction! :-)

I really don't know if it is new behaviour, because last weekend we fixed that memory leak in nuxt-booster https://github.com/basics/nuxt-booster/issues/1089, and afterwards i found another memory leak in my monorepository.
I uninstalled all modules and everything i coded on my self and it was also there. 

After that i then just checked out the bare actual version without everything and I also got a memory leak.

**Comment by dissy123** [comment]
And Yes i did garbage Collection before Tami g the snapshots :)

**Comment by danielroe** [comment]
I refreshed your lockfile + updated to Node v22 and could not reproduce.

![CleanShot 2024-08-28 at 14 37 29@2x](https://github.com/user-attachments/assets/fd5e34ca-e7bd-4441-ba38-e52aa6c7df42)

Between each snapshot I ran:

```bash
ab -n 1000 -c 50 "http://localhost:3000/"
```

I launched the server with:

```bash
pnpm nuxi build && NODE_ENV=production node --enable-source-maps --inspect .output/server/index.mjs
```

**Comment by Xenossolitarius** [comment]
Need to add to this thread. There seems to be a memory leak that has to do something with useHead. I am not sure when it started bcs we just started perf testing before the release. Seems the issue is reproducible when you crawl the site. Firing just one route will in most cases do nothing

**Comment by dissy123** [comment]
interesting just tried it again. 
Deleted the lockfile and executed the commands you provided.

<img width="1356" alt="image" src="https://github.com/user-attachments/assets/c67f2f53-b2c3-47d5-8bcd-5c28256c8e94">

Will check my system, again will have more time next week.

**Comment by Xenossolitarius** [comment]
![image](https://github.com/user-attachments/assets/a086a638-d454-4f19-8928-388c258c70db)
![image](https://github.com/user-attachments/assets/ca02cfbd-5f25-477d-a3ea-c3f99833ab46)

Hmm same stuff here. Is it the latest useHead update?

**Comment by dissy123** [comment]
@Xenossolitarius the reproduction is just an empty nuxt project without anything else.

**Comment by danielroe** [comment]
delighted to hear it! 🔥

**Comment by dissy123** [comment]
@danielroe but we found a memory leak with pinia 
the reproduction is in this ticket, should i make a new one here? 

https://github.com/vuejs/pinia/issues/2762

**Comment by manniL** [comment]
@dissy123 different dependenices/setup, so better create a new issue 👍
