### ISSUE TITLE
  future: { compatibilityVersion: 4 } Messes up some types

### ISSUE THREAD

**Issue by stephenjason89** [nuxt/nuxt#28694]
### Environment

Working directory: /Users/stephenjasonwang/Development/test123            
Nuxt project info: (copied to clipboard)                                                                                                     

------------------------------
- Operating System: Darwin
- Node Version:     v22.6.0
- Nuxt Version:     3.13.0
- CLI Version:      3.13.0
- Nitro Version:    2.9.7
- Package Manager:  bun@1.1.26
- Builder:          -
- User Config:      compatibilityDate, future, modules, devtools
- Runtime Modules:  @vueuse/nuxt@10.11.1
- Build Modules:    -
------------------------------

                                                                                                                                                     
👉 Report an issue: https://github.com/nuxt/nuxt/issues/new?template=bug-report.yml
👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new
👉 Read documentation: https://nuxt.com

### Reproduction

https://stackblitz.com/edit/nuxt-3-vueuse-motion-pmteh2?file=client%2Fapp.vue

### Describe the bug

Without compatibility 4
<img width="596" alt="image" src="https://github.com/user-attachments/assets/3c8ee497-4dca-46af-a410-47524d15b1f7">

With compatibility 4
<img width="1029" alt="image" src="https://github.com/user-attachments/assets/1110c9ec-0bf9-4b00-8cc4-893910db9bf3">

**Comment by danielroe** [comment]
With v4, the types are slightly stricter and you need to check that it exists before destructuring.
