### ISSUE TITLE
runtime config in `.env` is not loaded in production

### ISSUE THREAD

**Issue by kingyue737** [nuxt/nuxt#28698]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.13.0
- CLI Version:      3.13.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      compatibilityDate, devtools, runtimeConfig
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-p9jzzh

### Describe the bug

I added `NUXT_TEST=reproduction` in `.env` file. It works well in dev and the string `reproduction` is rendered in page.

But if I build it and preview with `node .output/server/index.mjs`, the config in `.env` does not take effect.

**Comment by danielroe** [comment]
This is documented behaviour: https://nuxt.com/docs/guide/directory-structure/env#production

**Comment by kingyue737** [comment]
Sorry for missing that part in the documentation. For those who want to load `.env` in production, we can use the built-in functionality since Node v20.6: https://nodejs.org/en/learn/command-line/how-to-read-environment-variables-from-nodejs

```
node --env-file=.env .output/server/index.mjs
```
