### ISSUE TITLE
Nuxt Plugin "provide" is not typed automatically since v3.13.0

### ISSUE THREAD

**Issue by Bombastickj** [nuxt/nuxt#28693]
### Environment

Nuxt project info: 

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.16.0
- Nuxt Version:     3.13.0
- CLI Version:      3.13.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.8.1
- Builder:          -
- User Config:      compatibilityDate, devtools, typescript
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-xwuwfy?file=app.vue

### Describe the bug

Hello, I have encountered an issue since updating to Nuxt v3.13.0 where data provided from a plugin is not automatically typed as indicated in the documentation: https://nuxt.com/docs/guide/directory-structure/plugins#typing-plugins

**Comment by danielroe** [comment]
This is an upstream issue in devtools that will be fixed in the next release with https://github.com/nuxt/devtools/pull/712.

**Comment by Bombastickj** [comment]
Hi @danielroe , I conducted further testing and discovered that disabling the devtools in the `nuxt.config.ts` file eliminated the error. However, it appears that all components are still being assigned `type: any` and are not highlighted in green. Notably, this issue is only observable locally and does not occur on StackBlitz.

I hope this helps!

**Comment by danielroe** [comment]
@Bombastickj  that sounds like an IDE extension issue. Check you have the latest version of Vue Language Tools. (Note that there was a VSCode bug stopping auto update and you may have to remove it and reinstall.)

**Comment by Bombastickj** [comment]
Thanks for the suggestion @danielroe! I updated Vue Language Tools and reinstalled it as you mentioned. The issue is now resolved. Appreciate your help!

**Comment by lud-hu** [comment]
@danielroe Thx for the insights! Any idea when the update of the devtools will be published or how I can already install the fix beforehand? Unfortunately it's currently blocking the update of our app to the 3.13.x version of nuxt.
