### ISSUE TITLE
Make server routes aware of page routes to avoid collisions

### ISSUE THREAD

**Issue by ChrisGV04** [nuxt/nuxt#28704]
### Describe the feature

It seems that when you create a dynamic server route like this one: `/server/routes/[slug].get.ts` it will override every single route of the application, even if you have other routes defined at `pages/**` or files at `public/**`.

I'm not sure if it is at all possible to make that the server routes and page routes are merged in a similar way as page routes do. For example:

```
-| pages
---| links
-----| [linkId].vue
-----| index.vue
-----| new.vue
---| login.vue
-| server
---| routes
-----| [slug].get.ts
```

With that file structure, I believe it would be ideal that navigating to `/links/new` matched the `pages/links/new.vue` page and the `server/routes/[slug].get.ts` only gets called when no other page/route matches (example: `/other-page`).

I thought that would be the actual behavior because pages do behave like that. Right now, `server/routes/[slug].get.ts` intercepts every single request to the app and every other path breaks.

## Why

I'm trying to build a very simple URL shortener app for my personal links and I would like that the redirection happens on the server side only, but keep the rest of the pages that are required for CRUD operations on my links.

Currently, the closest I've gotten has been with `pages/[slug].server.vue` but I don't actually want to render any Vue stuff. That's why I wanted it to be a server route that only responds with `sendRedirect`.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by Xenossolitarius** [comment]
These kind of changes are inbound in nuxt 4 fyi

**Comment by danielroe** [comment]
We won't be able to support the full breadth of `vue-router`'s pattern matching, but we should be able to do this for at least some route patterns, which could be a nice progressive enhancement.

What do you think @pi0?

**Comment by Gonzo17** [comment]
I think this is related to https://github.com/nuxt/nuxt/issues/25709

> It seems that when you create a dynamic server route like this one: `/server/routes/[slug].get.ts` it will override every single route of the application, even if you have other routes defined at `pages/**` or files at `public/**`.

`/server/routes/[slug].get.ts` will only override everything at the root of `pages` like `/pages/test.vue`.
`/server/routes/[...slug].get.ts` would theoretically override everything, but this doesn't work, which is probably good.
`/server/routes/test/[...slug].get.ts` in fact will override everything in `pages/test/**`.

If you start to use catch-all routes in your pages, it's getting tricky. Let's say you only have `pages/[...slug].vue` and no other pages. Every server middleware you will define will clash with that. In that case I don't want to prioritize the pages because I wouldn't be able to reach my middleware.

**Comment by pi0** [comment]
I would suggest follow-up via #25709 (https://github.com/nuxt/nuxt/issues/25709#issuecomment-2345577725https://github.com/nuxt/nuxt/issues/25709#issuecomment-2345577725), thanks for nice writeup dear @ChrisGV04.
