### ISSUE TITLE
Property X does not exist on type 'CreateComponentPublicInstance<Readonly<ExtractPropTypes<{}>>

### ISSUE THREAD

**Issue by J43fura** [nuxt/nuxt#28707]
I'm getting a similar error:

 `Property X does not exist on type 'CreateComponentPublicInstance<Readonly<ExtractPropTypes<{}>>, { Menu: typeof Menu; MenuButton: typeof MenuButton; MenuItem: typeof MenuItem; MenuItems: typeof MenuItems; Popover: typeof Popover; ... 10 more ...; handleLinkClick: typeof handleLinkClick; }, ... 17 more ..., {}>'.ts-plugin(2339)`

Where `X` is any function or variable in the utils folder. The app works fine on live and dev mode so nuxt is auto-importing correctly, but I think vscode's "Vue - Official" extension isn't understanding that this is auto-imported.

This only happens in the `<template>` section, it doesn't error inside `<script>`.

The error wasn't here when I had Nuxt 3.11.2, but I recently upgraded to 3.12.4 and it showed up. Is this happening for anyone else?

_Originally posted by @jeffreytung7 in https://github.com/nuxt/nuxt/issues/28373#issuecomment-2272179792_

**Comment by danielroe** [comment]
This is likely caused by a third-party library or module that hasn't yet updated to augment `vue` rather than `@vue/runtime-core`. If you can provide a reproduction I can likely fix upstream...

**Comment by reg0edit** [comment]
I have the same error with function from _utils_ folder and $t() function from @nuxtjs/i18n (v8.5.1). I'm using Nuxt 3.13.

**Comment by Henvy-Mango** [comment]
@danielroe Hey! This is a minimal  reproduction.
[reproduction.zip](https://github.com/user-attachments/files/16755912/reproduction.zip)

**Comment by maximilianmaihoefner** [comment]
In my case I also had @nuxtjs/i18n 8.5.1 but it still installs an old version of vue-i18n. Adding vue-i18n with version 9.14.0 explicitly to my package.json solved the issue for me. (Leaving this here just in case it helps anyone else)

**Comment by brambekkers** [comment]
For me also nuxtjs/i18n types, utils and for example navigateTo. I feel this is the same issue as the rest here. Everyhing is working but there are type error's everywhere.

**Comment by danielroe** [comment]
The issue here is that your package manager is pulling in the old version of `vue-i18n`. You can ask them to re-release a new version of `@nuxtjs/i18n` with updated version constraints, or perhaps you can manually install it in your `package.json`.

cc: @BobbieGoede.

**Comment by linspw** [comment]
Hi @danielroe , here I had a simillar error, with vue-i18n but also with global imports too:
![image](https://github.com/user-attachments/assets/bba23f50-5774-498e-8767-e1e44b6b09b7)

This capitalize comes from utils dir.

If I try to use in script, the type work correctly:
![image](https://github.com/user-attachments/assets/140cd273-f686-4a10-b058-a0d265265ee5)

I think it's not related with vue-i18n only, my versions are all updated:
![image](https://github.com/user-attachments/assets/2284ab87-9fcd-4fdf-bafa-2cb7c3bad8c4)

**Comment by nisegami** [comment]
I'm also experiencing the issue without even having vue-i18n or @nuxtjs/i18n installed. Anyone have tips on how I could go about tracking down the problematic package?

**Comment by danielroe** [comment]
If you can provide a reproduction I can probably find the issue quite quickly.

**Comment by danielroe** [comment]
Hopefully you also saw the workaround in the release notes 🙏

**Comment by reg0edit** [comment]
I tried to create reproduction, but I can't repeat error in new project.
I'm using vsCode with official Vue extension, which has been released today, and error disappeared.
![image](https://github.com/user-attachments/assets/67765134-c985-47ed-bb24-796eba63cc7d)

My package list: 
```json
{
        "@nuxt/eslint": "^0.5.2",
        "@nuxtjs/i18n": "^8.5.1",
        "@pinia/nuxt": "^0.5.4",
        "@vite-pwa/nuxt": "^0.10.1",
        "nuxt": "^3.13.0",
        "nuxt-tiptap-editor": "^1.2.1",
        "pinia": "^2.2.2",
        "vue": "latest",
        "vuetify-nuxt-module": "^0.17.1",
}
```

**Comment by danielroe** [comment]
@reg0edit Make sure all your dependencies/lockfile are updated.

For example, I believe I've had a report of this from `vuetify` but it should be resolved in latest vuetify version: https://github.com/vuetifyjs/vuetify/commit/7c8aeefdc097ff9b74a733ed17b6a8cd9e1f8575.

**Comment by Chocopieca** [comment]
Today I reinstalled  node_modules and package-lock.json and caught type errors in all my templates, $t, $router and all auto-import components. this.$t also catch type error. In localhost all autoimorted components are working good.
I'd tried update all my dependancy to last version but it did't halp.
I have been worked good with this depandacies for 2 mounth without reinstall node-modules.

Packages:
"nuxt": "^3.11.2",
"vue-router": "^4.3.2",
"vue-tsc": "^2.1.2",
"typescript": "^5.4.5",
"@nuxtjs/i18n": "^8.3.1",
"@nuxt/types": "^2.18.1",

![image](https://github.com/user-attachments/assets/4292f2b8-5441-4af4-8ad6-0dc2845930b8)

Also I caught problem with definePageMeta layout, it's set "defult" layout only and I can't use other laoyuts. I can set manualy by name attribute for NuxtLayout, but it's don't good solution for me.

**Comment by danielroe** [comment]
If someone is encountering this, please provide a reproduction. 🙏 

@Chocopieca you have a Nuxt v2 dependency in there. As well as some outdated versions of i18n/vue-router/nuxt...

**Comment by Chocopieca** [comment]
I tried to reproduce but caught other error, dependancy error. [https://github.com/nuxt/nuxt/issues/28755](url)
I will try to reproduce error with type again

**Comment by Chocopieca** [comment]
[nuxt-autocomplit-type-error.zip](https://github.com/user-attachments/files/16806503/nuxt-autocomplit-type-error.zip)
There is reprodus the proble with types and NuxtLayout

**Comment by Chocopieca** [comment]
I'v removed @vite-pwa/nuxt from modules in nuxt config in my reporuction project and problem with type disappeared.
But this removing didn't help in my main project.

**Comment by Chocopieca** [comment]
I also caught this error when add to nuxt.config.ts

```
typescript: {
    typeCheck: true,
  },
```

![image](https://github.com/user-attachments/assets/a016e3cf-34d6-4493-a10c-c3fa76d4970e)

**Comment by Chocopieca** [comment]
I added this code to **nuxt-shim.d.ts** file in my reproduction project and error showed again
```
declare module '@vue/runtime-core' {
  interface ComponentCustomProperties {
    $test: string;
  }
}
```
But in my main project removing this declare didn't halp

**Comment by Chocopieca** [comment]
I fined this declare in my main project and problem with typesce disappeared
```
declare module '@vue/runtime-core' {
  interface ComponentCustomProperties {
    $breakpoint: BreakpointI;
    $iMask: IMaskI;
  }
}
```

**Comment by Chocopieca** [comment]
@danielroe it looks like modifire of ComponentCustomProperties  in @vue/runtime-core is crashing types

**Comment by 94726** [comment]
@Chocopieca looks like it's neither a Vue nor a Nuxt problem. 
Try to always augment `vue` instead of `@vue/runtime-core`, as recommended here: https://vuejs.org/api/utility-types.html#componentcustomproperties.
e.g.
```ts
declare module 'vue' {
  interface ComponentCustomProperties {
    $breakpoint: BreakpointI;
    $iMask: IMaskI;
  }
}
```

If something augments `@vue/runtime`, all libraries that augment `vue` (which are most libs) will break.

**Comment by yeonjulee1005** [comment]
is there any update? 🥲

**Comment by danielroe** [comment]
you probably need a newer version of vue-i18n

https://github.com/nuxt/nuxt/pull/28446#issuecomment-2304235469

**Comment by luizzappa** [comment]
For those facing this issue and not using any of the above libraries, [this message](https://github.com/nuxt/nuxt/pull/28446#issuecomment-2304235469) (thanks @danielroe) helped me diagnose it. 

Here’s a summary below:

1) Search for `declare module .@vue.runtime-core` in all files within the `node_modules` folder. 

    You can do this on **Linux** or **Windows with Git Bash**: 
    `grep -RHl 'declare module .@vue.runtime-core' node_modules` 

    On **PowerShell**: 
    `findstr /s /m /i /c:"declare module '@vue/runtime-core'" node_modules\*.*`

2) The output of this command will indicate which libraries are using this problematic declaration style. 
    In my case, it was `primevue`:
    ![Image](https://github.com/user-attachments/assets/230442a7-25f4-4cf9-9661-2597e3881c3e)

3) For each of these libraries, check for the latest version where they have changed the way Vue is augmented. If none exists, you will need to submit a PR to modify how Vue is augmented. More details can be found [here](https://github.com/nuxt/nuxt/pull/28542).

4) Run the command from step 1 until only `@vue/runtime-core` and `runtime-dom` remain. After that, restart your VSCode window. It should return to normal functionality.

    ![Image](https://github.com/user-attachments/assets/0a4a7a44-b8e3-44ca-a3ce-edf99c4eed8e)

**Comment by ikukuler** [comment]
Having the same issue

```
<Button
     @click="window.open(thing.getExternalUrl())">
     Open
</Button>
```

`Property 'window' does not exist on type 'CreateComponentPublicInstance<ResolveProps...etc`

**Comment by slyduda** [comment]
if it helps for anyone else: i found myself here because i migrated my legacy nuxt code over to new nuxt and at some point TS now complains when there is a conflict in the name of a prop and a variable which is a good thing! it now requires that there are no collisions, but the type hint was not helpful in debugging this.

**Comment by DhivinX** [comment]
Temporary solution (if someone use nuxt i18n) based on https://nuxt.com/blog/v3-13#vue-typescript-changes

```ts
import type {
  ComponentCustomOptions as _ComponentCustomOptions,
  ComponentCustomProperties as _ComponentCustomProperties,
} from 'vue';

import type {
  ComposerTranslation,
  LocaleMessage,
  LocaleMessageValue,
  RemoveIndexSignature,
  VueMessageType,
} from 'vue-i18n';

declare module '@vue/runtime-core' {
  interface ComponentCustomProperties extends _ComponentCustomProperties {
    $t: ComposerTranslation<
      {
        [x: string]: LocaleMessage<VueMessageType>;
      },
      string,
      RemoveIndexSignature<{
        [x: string]: LocaleMessageValue<VueMessageType>;
      }>,
      never,
      string,
      string
    >;
  }
  interface ComponentCustomOptions extends _ComponentCustomOptions {}
}
```

**Comment by bonniegrubbs** [comment]
@luizzappa Thank you! I was able to find the library that was causing our issue using the grep you provided. Unfortunately [auth0-vue](https://github.com/auth0/auth0-vue/pull/433) hasn't released a fix yet but the [workaround](https://nuxt.com/blog/v3-13#vue-typescript-changes) mentioned in the release notes for 3.15 worked for us.
