### ISSUE TITLE
Vite SASS modern compiler causes missing sourcefiles issue

### ISSUE THREAD

**Issue by daniluk4000** [nuxt/nuxt#28723]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v22.1.0
- Nuxt Version:     3.13.0
- CLI Version:      3.13.0
- Nitro Version:    2.9.7
- Package Manager:  yarn@1.22.22
- Builder:          -
- User Config:      compatibilityDate, devtools, vite
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/daniluk4000/nuxt-sourcemap-bug

1. yarn && yarn dev
2. Open first page

I could reproduce this in dev env only

### Describe the bug

If you use new Vite's modern-compiler at the same time as global SCSS variables, Nuxt logs missing sourcemaps to your console.

### Additional context

This could be an upstream bug. Didn't notice this before updating to 3.13. 

### Logs

```shell-script
✔ Vite client built in 18ms                                                                                                                                                                                            5:21:58 PM
✔ Vite server built in 360ms                                                                                                                                                                                           5:21:58 PM
✔ Nuxt Nitro server built in 302 ms                                                                                                                                                                              nitro 5:21:59 PM
ℹ Vite client warmed up in 0ms                                                                                                                                                                                         5:21:59 PM   
ℹ Vite server warmed up in 325ms                                                                                                                                                                                       5:21:59 PM

 WARN  Sourcemap for "/WebstormProjects/sourcemap-bug/components/TestComponent.vue" points to missing source files                                                                                                      5:22:02 PM  


 WARN  Sourcemap for "/WebstormProjects/sourcemap-bug/components/TestComponent.vue" points to missing source files (x2)
```

**Comment by daniluk4000** [comment]
Will update & check as soon as all Vue 3.5.0 issues are resolved :D

**Comment by danielroe** [comment]
Can you reproduce with just Vite (without Nuxt)?

**Comment by hi-ogawa** [comment]
@daniluk4000 Thanks for the reproduction. I made a minimal repro on plain Vite and created an issue https://github.com/vitejs/vite/issues/18111

Vite doesn't enable `css.devSourcemap` by default, but Nuxt seems to enable it automatically. If you don't mind without sourcemap, then probably you can force turning it off from a plugin like:

```ts
export default defineNuxtConfig({
  compatibilityDate: '2024-04-03',
  devtools: { enabled: true },
  vite: {
    css: {
      // for some reason, disabling it here doesn't seem to work.
      // devSourcemap: false,
      preprocessorOptions: {
        scss: {
          api: 'modern-compiler',
          additionalData: '@use "~~/variables.scss" as *;'
        },
      },
    },
    plugins: [
      {
        name: "hack",
        config() {
          return {
            css: {
              devSourcemap: false,
            }
          }
        },
      }
    ]
  },
})

```

**Comment by daniluk4000** [comment]
@hi-ogawa hey, big thanks! Didn't have time to test it myself

**Comment by daniluk4000** [comment]
Fixed on Vite's side
