### ISSUE TITLE
$fetch cannot get data correctly within Alipay in IOS

### ISSUE THREAD

**Issue by xiaoyaoyaoGitHub** [nuxt/nuxt#28752]
### Environment

- Operating System: Darwin
- Node Version:     v20.13.1
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.5.2
- Builder:          -
- User Config:      extends, runtimeConfig, app, devtools, modules, imports, vant, generate, ssr, compatibilityDate, hooks
- Runtime Modules:  @vant/nuxt@1.0.5, nuxt-swiper@1.2.2
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-xaocez?file=app.vue

### Describe the bug

When the client initiates a web request, the interface returns the data normally, but there is no _body in the onResponse of $fetch, which is only the case within Alipay

![84EC756FC324720ABD45DFDD05E51E28](https://github.com/user-attachments/assets/832c3c74-cd77-4ce5-8a63-a0ef5811d1b0)
![BC2CBB12325BBE3BBC874B24B88DB509](https://github.com/user-attachments/assets/ff94213f-ee1f-4feb-a531-3ceb82356ca7)

**Comment by markthree** [comment]
You can try to fix the problem by installing [nuxt-fix-ofetch](https://github.com/markthree/nuxt-fix-ofetch)

@xiaoyaoyaoGitHub

**Comment by danielroe** [comment]
This sounds like a potential upstream issue in https://github.com/unjs/ofetch, particularly given the workaround module.

Would you be able to raise an issue there so we can track and potentially resolve at source? 🙏

**Comment by xiaoyaoyaoGitHub** [comment]
> You can try to fix the problem by installing [nuxt-fix-ofetch](https://github.com/markthree/nuxt-fix-ofetch)
> 
> @xiaoyaoyaoGitHub

Thinks I can try it

**Comment by xiaoyaoyaoGitHub** [comment]
> This sounds like a potential upstream issue in https://github.com/unjs/ofetch, particularly given the workaround module.
> 
> Would you be able to raise an issue there so we can track and potentially resolve at source? 🙏

ok
