### ISSUE TITLE
[Feature Request] A Hook 'beforeRenderPayloadJsonScript'

### ISSUE THREAD

**Issue by geminigeek** [nuxt/nuxt#28756]
### Describe the feature

hi,

requesting a `beforeRenderPayloadJsonScript`  hook here https://github.com/nuxt/nuxt/blob/77e36ee27497cb5b9765a0cdc61e11f810272e1a/packages/nuxt/src/core/runtime/nitro/renderer.ts#L594

this can be used along with app:beforeMount for custom handling of payload

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
I think you should be able to modify the payload in `app:rendered`.

**Comment by geminigeek** [comment]
hi, 

i am basically trying to , hook into this `contents` variable , encrypt it and decrypt it with js in frontend in "app:beforeMount" if its possible

```
 const contents = opts.data ? stringify(opts.data, opts.ssrContext._payloadReducers) : ''
```
https://github.com/nuxt/nuxt/blob/77e36ee27497cb5b9765a0cdc61e11f810272e1a/packages/nuxt/src/core/runtime/nitro/renderer.ts#L595
