### ISSUE TITLE
Big JSON Payloads - devalue slow performance

### ISSUE THREAD

**Issue by Xenossolitarius** [nuxt/nuxt#28766]
### Discussed in https://github.com/nuxt/nuxt/discussions/28764

<div type='discussions-op-text'>

<sup>Originally posted by **Xenossolitarius** August 30, 2024</sup>
In my project I stumbled on "needing" to have one giant JSON payload. Around 1.2 MB. I wanted to have it bolted in HTML, SSR'd. Let's just go with the flow and not debate if I should even send it to the frontend. Bad practice. But issue arises when it's smaller also of how complex it would be. The issue is with nuxt/devalue where its trying to transform the payload, ofc to stop us from getting attacked by the XSS, And it takes time. It takes 32ms for example which is almost as long as rendering time. This json payload is not static. Changes every couple of minutes.
I wanted to trick the nuxt/devalue with this code:
```
export default definePayloadPlugin((nuxt) => {
  definePayloadReducer('JSONPayload', (value) => {
    if (!(value instanceof JSONPayload)) return false
    return value.toString()
  })
  definePayloadReviver('JSONPayload', (value) => {
    return new JSONPayload().fromString(value)
  })
})
```
basically tricking it into a string, circumventing devalue slow performance. But then it took 66 ms. Twice as long. What's up? So it seems the devalue is extra careful around the strings, so the parsing lasts.

Eventually I settled on this code:

```
export default definePayloadPlugin((nuxt) => {
  definePayloadReducer('JSONPayload', (value) => {
    if (!(value instanceof JSONPayload)) return false

    nuxt.runWithContext(() => {
      useHead({
        script: [
          {
            tagPosition: 'bodyClose',
            innerHTML: 'window.__PLD__ =' + JSON.stringify(value.payload),
          },
        ],
      })
    })

    return 'pld'
  })
  definePayloadReviver('JSONPayload', (value) => {
    const pld= new JSONPayload()
    pld.payload = window.__PLD__
    return pld
  })
})
```
This brought down the payloadRendering time to a  staggering 7ms. Still quite long but this was managable.

So in general, couple of questions here:
Is there a cleaner way around this issue?
Does this feature exists or is it a good candidate for new feature?
What will be this feature? A boolean that skips the "stringify"? Virtual modules linking to external JSON's ? 
Does this incur any memory leaks (i checked it doesn't)?
This is definitely not safe but how bad is it ?</div>

**Comment by danielroe** [comment]
I would never suggest someone have 1.2Mb in their payload, as you recognise.

By default we now use not `@nuxt/devalue` but https://github.com/Rich-Harris/devalue which we initially tested as being faster than JSON.stringify - though it seems not when the payload is >1Mb...

I think your workaround is reasonable in your case, but if you're looking for other ideas, you could also use `render:html` hook and inject your own script tag.

**Comment by Xenossolitarius** [comment]
Thank you for the response and alternative strategies. 
Ok, let's close the issue. Ive patched the devalue to simulate and the speed is roughly the same for lower payloads. If someone ever has the same problem he can use the recepie from above.
