### ISSUE TITLE
Unexpected `compilerOptions.paths` change in tsconfig.server.json when `compatibilityVersion: 4` is set

### ISSUE THREAD

**Issue by hecateball** [nuxt/nuxt#28767]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.13.0
- CLI Version:      3.13.1
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      compatibilityDate, devtools, future
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-9ewqau?file=nuxt.config.ts

1. create new Nuxt project
1. create `app` directory
1. set `compatibilityVersion: 4` 
1. run `npx nuxi prepare`

### Describe the bug

When `compatibilityVersion: 4` is set and directory named `app` exists,  `compilerOptions.paths` for `~/*` and '@/*' in auto-generated tsconfig.server.json become `../app/*` (possibly because they follow Nuxt alias change).

In Nuxt v3, or when `app` directory does not exist, those paths are `../*`.

**Comment by danielroe** [comment]
This is expected - `~` points to your `srcDir`, which with the new directory structure, is `app/`. `~~` remains the alias for the `rootDir`.

**Comment by hecateball** [comment]
Is there any plan to add alias which points to `serverDir` or should we use `~~/server`?

(Our project uses `~/server` to import server things in v3 project and it does not work in v4...)
