### ISSUE TITLE
Same ssr data served to users as they access different pages at the same time

### ISSUE THREAD

**Issue by thibaut-boudier** [nuxt/nuxt#28786]
### Environment

- Operating System: Linux
- Node Version:     v20.15.0
- Nuxt Version:     3.10.3
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      app, components, css, nitro, vite, build, modules, i18n, gtm, router, debug, dev, experimental, vitalizer, features, logLevel, ssr, telemetry, runtimeConfig
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.2, @pinia/nuxt@0.5.1, @nuxtjs/leaflet@1.0.14, @pinia-plugin-persistedstate/nuxt@1.2.0, @zadigetvoltaire/nuxt-gtm@0.0.13, nuxt-vitalizer@0.10.0
- Build Modules:    -

### Reproduction

https://github.com/thibaut-boudier/nuxt_ssr_error

To reproduce with this minimal example, you will have to fetch a lot of different paths
Either open a lot of tabulations or use something like Siege (even if it will only help to see the problem on the body part)

### Describe the bug

We observed that multiple users could get the same ssr data if they were loaded from `ssrContext.payload` and set up inside it in a middleware or plugin

### Additional context

Hello,

Recently, me and my team moved a project from Nuxt 2.X to 3.X
It's a big project, so we took more than 6 months to make every changes (with the objective to take the less time possible and keep Option API for the majority)
At the end of this sub-project, we saw on production that sometimes, as a user asked for a specific page, they were getting not the correct one.

To give the correct data, we have a back-end API that we call a lot to get data for the user. Like what is the type of the page they are looking for, or the website and local that needs to be given
So we had a middleware that fetched through apollo graphql query the type of this path
As we looked more around it, we saw that if multiple users were asking for a page at the same time (and were on the same load balancer and the same pm2 cluster), only one result was shared to both users.
We used `ssrContext` from the nuxtApp data to share the element from the middleware to the component and it seems that at one point, the data in the payload could be overwritten as multiple users asked at the same time.

We fixed it by removing this middleware and set it up in the all-catch page that we used to redirect to the correct components.

The second issue that we had is from the fonction `useServerHead`
In a plugin to initialise pinia, we had multiple call to our back-end API and at the end set up through useServerHead the html attribute `lang`
For the same reason as previously, some times, we could get the wrong lang attribute.
To fix it, we removed it from the plugin step and used a `useHead` inside a layout to correctly set it

All of these problems took time to figure it out as we don't have a lot of knowledge on how nuxt server part works...
We understood the on components/pages/layout, the nuxt server and its data are correctly connected to the user
But on plugins or in the `ssrContext`, the data might be global for everyone at one point of time 

Is our investigation and deduction correct ? Or do we have only got lucky/unlucky ?
If this deduction is correct, could it be more explicitly defined in the documentation for futur people ?

We also saw that in Nuxt 2.X, something close to our problem could be seen : https://masteringnuxt.com/blog/problems-with-server-side-plugins-in-nuxtjs

**Comment by danielroe** [comment]
I can't reproduce with your reproduction.

I modified the middleware and `[...].vue` to throw errors if there were a mismatch, like this:

```ts
if (route.fullPath !== elem.value) {
  throw createError('Mismatch: ' + route.fullPath + ' and ' + elem.value);
}
```

```ts
if (ssrContext.payload.data.ssrPath && ssrContext.payload.data.ssrPath !== to.path) {
  throw createError('polluted server state');
}
```
