### ISSUE TITLE
Memory Leak when using Pinia

### ISSUE THREAD

**Issue by dissy123** [nuxt/nuxt#28798]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v22.7.0
- Nuxt Version:     3.13.0
- CLI Version:      3.13.1
- Nitro Version:    2.9.7
- Package Manager:  pnpm@8.15.3
- Builder:          -
- User Config:      compatibilityDate, devtools, modules
- Runtime Modules:  @pinia/nuxt@0.5.4
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/dissy123/nuxt-pinia-memory-leak

### Describe the bug

The Repository i posted is just a blank Nuxt3 Project, i have added a Pinia Store like in the Documentation here:
https://nuxt.com/docs/getting-started/state-management

Have i done something wrong? Or is this a memory leak?

The Strings from the json objects are stored each request in the HEAP but not deleted again.

I tried it without the Code of the Store and no memory leak happens.

```
pnpm i

pnpm build

node --inspect .output/server/index.mjs

ab -n 50 -c 10 "http://localhost:3000/"
```

Sorry i am a little bit confused already hunting this for a few weeks now.

When you comment out the line in app.vue

`await useAsyncData("todos", () => store.fetchIconsData());`

no memory leak is happening!

i also tried it with callOnce the leak is also there!

I also tried it with https://vueuse.org/shared/createGlobalState/ and it also didn't change.

I also tried useFetch when fetching and $fetch

### Additional context

https://github.com/vuejs/pinia/issues/2762

**Comment by danielroe** [comment]
can you reproduce without pinia? see my comment here: https://github.com/vuejs/pinia/issues/2762#issuecomment-2325901215

**Comment by danielroe** [comment]
This is reproducible without Nuxt: see https://github.com/vuejs/pinia/issues/2762#issuecomment-2326174565.
