### ISSUE TITLE
Possible issue with tree-shaking Vue during build

### ISSUE THREAD

**Issue by cjpearson** [nuxt/nuxt#28808]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.9.0`
- Nuxt Version:     `3.13.0`
- CLI Version:      `3.13.1`
- Nitro Version:    `2.9.7`
- Package Manager:  `yarn@1.22.19`
- Builder:          `-`
- User Config:      `compatibilityDate`, `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

* Create a new project like `npx nuxi init bundle-size-test`
* Run `nuxi analyze` inside the project
* Open the client bundle stats

### Describe the bug

The Vue packages are 32kb gzipped. 

![Screenshot 2024-09-03 at 15 48 05](https://github.com/user-attachments/assets/d2616e91-18d4-42cf-a557-077b22e01c16)

According to the [Vue docs](https://vuejs.org/about/faq#is-vue-lightweight), the maximum size of Vue should be around 27kb (brotli), but can be as low as 16kb depending on how many features are used. Since this is a minimal app, I would expect it to be on the lower side. Is it possible that tree-shaking is not working correctly?

### Additional context

Follow up from the discussion here: https://github.com/nuxt/nuxt/discussions/23729

**Comment by danielroe** [comment]
FWIW, an issue with tree-shaking was resolved in v3.5.1: see [changelog](https://github.com/vuejs/core/blob/main/CHANGELOG.md) and [commit](https://github.com/vuejs/core/commit/4eee630b3122a10d0baf9b91358cfffa92d6fd81).

The first thing you can do is use a custom `error.vue` + `app.vue`. Here's a minimal Nuxt project, which shows a smaller Vue bundle than you report (total bundle size including all other Nuxt dependencies, is 43Kb gzipped).

Beyond that, it's difficult to tree-shake Vue down as not many of its features are tree-shakeable, and those that are (Suspense, Transition) are built-in features of Nuxt and can't be excluded from the bundle. (Though I would like to allow disabling Transition.)

**Comment by cjpearson** [comment]
Thanks for info! Vue is far from the largest component in the bundle, I was just hoping their might be some quick wins if tree-shaking wasn't being applied

Could you share what the minimal project looks like?
