### ISSUE TITLE
nodejs 22: DeprecationWarning: The `punycode` module is deprecated.

### ISSUE THREAD

**Issue by cdwmhcc** [nuxt/nuxt#28819]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v22.8.0
- Nuxt Version:     3.13.0
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.9.0
- Builder:          -
- User Config:      compatibilityDate, routeRules, future, nitro, alias, runtimeConfig, vite, modules, devtools
- Runtime Modules:  @pinia/nuxt@0.5.4, @nuxtjs/mdc@0.8.3
- Build Modules:    -
------------------------------

### Reproduction

When I use pnpm workspace, it causes the global packages to trigger the issue.

- /apps/dashboard （nuxt-app）
- /packages/
  - test
- pnpm-workspace.yaml

### Describe the bug

```
(node:31328) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

`pnpm why punycode`

```
Legend: production dependency, optional only, dev only

nuxt-app E:\Work\Projects\apps\dashboard

dependencies:
nuxt 3.12.4
└─┬ @nuxt/vite-builder 3.12.4
  └─┬ vite-plugin-checker 0.7.2
    └─┬ eslint 9.9.0 peer
      ├─┬ @eslint/eslintrc 3.1.0
      │ └─┬ ajv 6.12.6
      │   └─┬ uri-js 4.4.1
      │     └── punycode 2.3.1
      └─┬ ajv 6.12.6
        └─┬ uri-js 4.4.1
          └── punycode 2.3.1

```

**Comment by danielroe** [comment]
This is already being worked on upstream and will eventually be resolved: https://github.com/ajv-validator/ajv/issues/2343#issuecomment-2170363487

**Comment by JenuelDev** [comment]
it seems this error is showing in most new projects now:
```json
"pnpm": {
    "overrides": {
      "ajv": "8.17.1"
    }
  }
```
tried adding this to my package.json, I am still getting the error:

![Image](https://github.com/user-attachments/assets/6c7e936f-0984-47aa-9a40-9d4316273b60)

**Comment by mmgolden** [comment]
I am getting the same warning.

**Comment by onurdumangoz** [comment]
```
"overrides": {
    "ajv": "^8.17.1",
    "whatwg-url": "^14.1.0"
}
```

This worked for me.

**Comment by JenuelDev** [comment]
@onurdumangoz this does not work for me

**Comment by mtzrmzia** [comment]
Same here ... no solution yet? @danielroe

**Comment by danielroe** [comment]
please read my comment above

https://github.com/nuxt/nuxt/issues/28819#issuecomment-2328270978

**Comment by acidjazz** [comment]
> please read my comment above
> 
> [#28819 (comment)](https://github.com/nuxt/nuxt/issues/28819#issuecomment-2328270978)

hmm - this PR was closed in June - is there another upstream PR we can follow?
