### ISSUE TITLE
reactive props destructure with default values doesn't work

### ISSUE THREAD

**Issue by ZTL-UwU** [nuxt/nuxt#28829]
### Environment

- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.13.1
- CLI Version:      3.13.1
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-t1vjvm?file=components%2Fcomp.vue,app.vue

### Describe the bug

Defining props with default value using the new vue 3.5 props destructure is compiled differently in nuxt.

In the [vue playground (vue3.5.1, SSR)](https://play.vuejs.org/#__SSR__eNp9Uk1Lw0AQ/SvjXmqhpEj1UpOKSkE9aFHBy4LEZBJTN7vL7qYWQv67sxtbU1BPycx7s+/NR8sutY42DbI5i21mKu3Aomv0gsuq1so4uFa1hsKoGkbR1AeePjrf4y0YLKD7pniMSy4zJa2D2paQePx4dINCKHhRRuRHozGX8bSXIyEKHNZapA4pAoi9yiIOYpSIpwOUTZiz9HhRldHaKkm+W1/DWUbsSqB50K4icc7mEBCPpaT9eRdyzjQ42eWzd8w+fsmv7dbnOFsZtGg2yNkec6kp0fXw8uket/S/B2uVN4LY/4CPaJVovMeedtXInGwPeMHtbZhuJctnu9w6lHbXlDfqmV3gc0YT94P6q/Ufu7PoNNRx2dEUd5v0iz+YfttCoRR0xDuYPIXDAwGRyjKh90mO0H7ffWkSPNJJJJBjUUlcGaVtHCwRfjGHN6UEppKOqFscj+kzuAby9rpB4/slb7PoLDph3RcS1OLs):

![image](https://github.com/user-attachments/assets/00712c97-7b4b-489e-b8a8-ba4d2f2ee8fc)

```js
/* Analyzed bindings: {
  "foo": "props"
} */
import { defineComponent as _defineComponent } from 'vue'

const __sfc__ = /*@__PURE__*/_defineComponent({
  __name: 'Comp',
  props: {
    foo: { type: Boolean, required: false, default: true }
  },
  setup(__props, { expose: __expose }) {
  __expose();



const __returned__ = {  }
Object.defineProperty(__returned__, '__isScriptSetup', { enumerable: false, value: true })
return __returned__
}

});
import { ssrInterpolate as _ssrInterpolate } from "vue/server-renderer"
function ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`${_ssrInterpolate($props.foo)}`)
}
__sfc__.ssrRender = ssrRender
__sfc__.__file = "src/Comp.vue"
export default __sfc__
```

In Nuxt:
![image](https://github.com/user-attachments/assets/7058e890-ea04-47a4-8526-08fae9013507)

```js
import { createHotContext as __vite__createHotContext } from "/_nuxt/@vite/client";import.meta.hot = __vite__createHotContext("/components/comp.vue");import { defineComponent as _defineComponent } from "/_nuxt/node_modules/vue/dist/vue.runtime.esm-bundler.js?v=8fea97c8";
const _sfc_main = /* @__PURE__ */ _defineComponent({
  __name: "comp",
  props: {
    foo: { type: Boolean, required: false }
  },
  setup(__props, { expose: __expose }) {
    __expose();
    const { foo = true } = __props;
    const __returned__ = { foo };
    Object.defineProperty(__returned__, "__isScriptSetup", { enumerable: false, value: true });
    return __returned__;
  }
});
import { toDisplayString as _toDisplayString } from "/_nuxt/node_modules/vue/dist/vue.runtime.esm-bundler.js?v=8fea97c8";
function _sfc_render(_ctx, _cache, $props, $setup, $data, $options) {
  return _toDisplayString($setup.foo);
}
_sfc_main.__hmrId = "ea5b442f";
typeof __VUE_HMR_RUNTIME__ !== "undefined" && __VUE_HMR_RUNTIME__.createRecord(_sfc_main.__hmrId, _sfc_main);
import.meta.hot.accept((mod) => {
  if (!mod) return;
  const { default: updated, _rerender_only } = mod;
  if (_rerender_only) {
    __VUE_HMR_RUNTIME__.rerender(updated.__hmrId, updated.render);
  } else {
    __VUE_HMR_RUNTIME__.reload(updated.__hmrId, updated);
  }
});
import _export_sfc from "/_nuxt/@id/__x00__plugin-vue:export-helper";
export default /* @__PURE__ */ _export_sfc(_sfc_main, [["render", _sfc_render], ["__file", "/home/projects/github-t1vjvm/components/comp.vue"]]);
```

**Comment by danielroe** [comment]
For now you can enable with:

```ts
export default defineNuxtConfig({
  vue: {
    propsDestructure: true
  },
})
```

**Comment by husayt** [comment]
wish, I checked this earlier.  spent hours trying to figure out what I was missing

Thank you

**Comment by danielroe** [comment]
Sorry about that!

**Comment by husayt** [comment]
There's nothing to be sorry about. You guys are doing an amazing job, taking into account the complexity you are trying to hide from users and features to uncover.

I am constantly assessing and switching between various UI frameworks for my clients, and the Vue/Nuxt ecosystem is a whole different level. 

That feature was just released in Vue, and same day, you made it available in nuxt. There must be some teething issues at that rate.

Thank you @danielroe and whole team once again

**Comment by avi-agg** [comment]
> For now you can enable with:
> 
> ```ts
> export default defineNuxtConfig({
>   vue: {
>     propsDestructure: true
>   },
> })
> ```

Thankyou sooooo much. I was struggling since past two days because many of my website functionality was depended on this.

**Comment by LePtiDev** [comment]
I stil have the error: pluginContext.vueCompilerOptions.plugins is not iterable

**Comment by joneath** [comment]
You might be missing the `feature` keys. I had to have the following to get it to work.

```ts
export default defineNuxtConfig({
  vue: {
    features: {
      propsDestructure: true,
    }
  }
})
```

**Comment by adamdehaven** [comment]
> > For now you can enable with:
> > ```ts
> > export default defineNuxtConfig({
> >   vue: {
> >     propsDestructure: true
> >   },
> > })
> > ```
> 
> @danielroe Thankyou sooooo much. I was struggling since past two days because many of my website functionality was depended on this.

I have this enabled and also still get the `pluginContext.vueCompilerOptions.plugins is not iterable` error with `vue@3.5.8`

- Operating System: `Darwin`
- Node Version:     `v20.17.0`
- Nuxt Version:     `3.13.1`
- CLI Version:      `3.13.2`
- Nitro Version:    `2.9.7`
- Package Manager:  `pnpm@9.10.0`

**Comment by danielroe** [comment]
@adamdehaven would you raise that as a separate issue? 🙏

**Comment by adamdehaven** [comment]
@danielroe https://github.com/nuxt/nuxt/issues/29144

Admittedly this is likely the most vague issue I've ever created 🫣 I wasn't sure what context to provide lol
