### ISSUE TITLE
Setting state used in layout from page component triggers mismatch

### ISSUE THREAD

**Issue by Jannick94** [nuxt/nuxt#28828]
### Environment

- Operating System: Linux
- Node Version:     v18.19.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      experimental, modules, tailwindcss, robots, runtimeConfig, postcss, css, components, imports, build, app, routeRules
- Runtime Modules:  @nuxt/eslint@0.3.13, @pinia/nuxt@0.5.1, @nuxtjs/robots@3.0.0, @nuxt/test-utils/module@3.12.1
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-v41cap?file=pages%2Findex.vue

### Describe the bug

I'm trying to populate some dynamic properties in a layout from within the page component that uses the layout, because I don't want to re-render the whole layout when I navigate between routes with the same layout, this way I can just transition the title between route changes.

However when I try to use a composable that uses `useState`, or some other implementation like a Pinia store or using provide/inject, this results in a hydration mismatch.

If this is possible in another way please let me know as well! Thanks! 🙏🏻

**Comment by danielroe** [comment]
This might explain why: https://www.youtube.com/watch?v=dZSNW07sO-A.
