### ISSUE TITLE
Hydration mismatch in production on a specific text

### ISSUE THREAD

**Issue by tilenpirih** [nuxt/nuxt#28838]
### Environment

 Operating System: Linux
- Node Version:     v21.7.3
- Nuxt Version:     3.13.1
- CLI Version:      3.13.1
- Nitro Version:    2.9.7
- Package Manager:  bun@1.1.26
- Builder:          -
- User Config:      compatibilityDate, devtools, runtimeConfig, build, css, modules, vite
- Runtime Modules:  nuxt-aos@1.2.5, @nuxt/scripts@0.8.3, nuxt-particles@0.3.0, ()
- Build Modules:    -

### Reproduction

The bug occurs only in production so I can't really send a reproduction link. If there will be problems with reproduction I will create an empty project and try all variables and edit the issue.

### Describe the bug

The bug occurs for me if I type a whole email anywhere on the page. On the development it works fine I only get error in the production

```html
<!-- layouts/default.vue-->
<template>
  <!--Throws a hydration mismatch error-->
  john.smith@gmail.com
</template>
```
![image](https://github.com/user-attachments/assets/9bfbd5f3-0859-479a-aea4-bedc0b5a55b6)

```html
<template>
  <!--Doesn't throw a mismatch error-->
  john.smith@gmail
</template>
```
![image](https://github.com/user-attachments/assets/2e3bcb7c-35b0-4215-b524-b8fefebc99d0)

### Additional context

For deployment I'm using `bun` and this is my dockerfile

```
FROM oven/bun:1.1.26 AS base

WORKDIR /usr/src/app

FROM base AS build

ENV NODE_ENV=production

COPY . /usr/src/app
WORKDIR /usr/src/app
RUN bun install
RUN bun run build

FROM base AS app

COPY --from=build /usr/src/app/.output /prod/app
WORKDIR /prod/app

EXPOSE 3000

CMD [ "bun", "run", "server/index.mjs" ]

```

**Comment by danielroe** [comment]
This is likely a browser extension modifying the HTML to make it clickable. IOS is also known to do the same with phone numbers.

Check in an incognito tab and if it still occurs, I'd appreciate a reproduction 🙏

**Comment by tilenpirih** [comment]
> This is likely a browser extension modifying the HTML to make it clickable. IOS is also known to do the same with phone numbers.
> 
> Check in an incognito tab and if it still occurs, I'd appreciate a reproduction 🙏

It's not a browser extension, I tried different browsers, incognito, my friend computer also had that so I doubt it's client problem. I'll try to make a reproduction link/code and will update the issue

**Comment by manniL** [comment]
Cloudflare or other email protection scripts maybe?

**Comment by tilenpirih** [comment]
> Cloudflare or other email protection scripts maybe?

yes I later found it was indeed cloudflare that was causing the issue.
![image](https://github.com/user-attachments/assets/a382c2be-afb1-4c7c-8396-207a2100642c)
