### ISSUE TITLE
useRuntimeConfig is returning a type unknown when multiple modules are enabled

### ISSUE THREAD

**Issue by ThibaultVlacich** [nuxt/nuxt#28831]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.13.1
- CLI Version:      3.13.1
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      compatibilityDate, devtools, typescript, modules, runtimeConfig
- Runtime Modules:  nuxt-security@1.4.3, @nuxtjs/i18n@8.5.1
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-unypdj?file=README.md

`npm run typecheck`:
![image](https://github.com/user-attachments/assets/b7866b15-9277-4cb2-aa21-a932f947e332)

Removes any of the two module in Nuxt config, and there is no more typechecking issues.

### Describe the bug

`useRuntimeConfig` is returning a type `unknown`, when multiple modules are enabled.

The bug doesn't seem to be related to the modules themselves, because individually they don't cause any issues, only when they are enabled simultaneously. Looking at the generated `.nuxt/types/schema.d.ts`, I don't see anything blatant that would explain the issue

### Additional context

The issue looks really similar to #28672, but for runtime configs instead of plugins.

**Comment by danielroe** [comment]
cc: @huang-julien - looks like more regexp fixes required for the bot?

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/28332.
