### ISSUE TITLE
Reactive Props Destructure from Vue 3.5.1 does not work with booleans

### ISSUE THREAD

**Issue by ClaudiaPascualGea** [nuxt/nuxt#28849]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.18.0
- Nuxt Version:     3.13.1
- CLI Version:      3.13.1
- Nitro Version:    2.9.7
- Package Manager:  yarn@1.22.22
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Reproduction link:

https://stackblitz.com/edit/github-c5jyyo

### Describe the bug

Reactive Props Destructure not working with booleans in Nuxt.

Create a simple component with:

```vue
<template>
  <p>My component with boolean value: {{ boolValue }}</p>
</template>

<script setup lang="ts">
const {
  boolValue = true,
} = defineProps<{
  boolValue?: boolean;
}>();
</script>
```

Use the component:
```vue
<template>
  <div class="my-page">
    <SimpleComponent />
  </div>
</template>
```

The expected result:

`My component with boolean value: true`

The component is not inferring the default value of the prop.

`My component with boolean value: false`

### Additional context

In Vue 3.5.1 is working:
https://play.vuejs.org/#eNp9UlFPwjAQ/iu1L9OEjBD0BceMGhI1UYkafVli5jjGsGubtgPMsv/uXYEJEX1q777r1+/uu5pfah0uKuADHjkotUgdxIlkLJr14rpmpc1Z00RdjHz2WpU6jrr+SGTU3XmDoc1MoR2z4CqCi1Ir41jNDExZw6ZGlSzAz4IWIp5NPuxmGCgJ0lnPT7KCc+LNlLTOSxkS1XFwA0Io9qaMmBwFJ6Rj/XPMO9xZLJ8WeTi3SmJbNelOOJEXAsyjdgXSJXzAPEJYimzLO59zpoLONp/NIPs8kJ/bFeUSPjZgwSwg4S3mUpODW8Oj5wdY4b0FSzWpBFb/Az6BVaIijeuyq0pOUPZOnVd76+dXyPzFjlYOpN02RUKpsvH1Ccch0jD/av1Hbj889e8S2eAUD3hBK7JrMBOpzIdIgYxo9tokT/yhlHhNRQXo12ZwDV4nMC0kjI3SNtqvuxj4O6QS/W7i4xM8Wk/9Zu3vpo7vv1grkS0LN9sSsAURYof1jgza4F/7il2+L8DQ5LC1fngW9njzDQjGCQ8=

**Comment by danielroe** [comment]
this is enabled by default in next nuxt release - for now, see https://github.com/nuxt/nuxt/issues/28829#issuecomment-2329411615.
