### ISSUE TITLE
Get dev server url in module

### ISSUE THREAD

**Issue by LittleSound** [nuxt/nuxt#28844]
### Describe the feature

I am developing a Nuxt Module. I want to print a URL for users to access the interface of my Module. It looks like the output of nuxt or unjs/listen.

Initially, I used `nuxt.options.devServer.url`. But since nuxt's port is obtained through `get-port-please`, the result is not accurate.
In the Vite plugin, I used the following method to get the current project's URL:

```typescript
function configureServer(server) {
  const _printUrls = server.printUrls
  server.printUrls = () => {
    _printUrls()
    const urls = server.resolvedUrls!
    for (const url of urls.local) {
      // eslint-disable-next-line no-console
      console.log(`➜  My Module: ${url}/__my_module_client/`)
    }
  }
}

```

I tried to find a way to achieve this effect in nuxt. But after reading a lot of source code, I am sure that nuxt does not export this data.
I want to know if nuxt can also provide the current `urls` in the module ctx?

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Thank you @OrbisK. Here's the code, for easier reference:

https://github.com/nuxt-modules/tailwindcss/blob/main/src/viewer.ts#L45-L48
