### ISSUE TITLE
Issues with prop reactivity & default values when using reactive props destructure

### ISSUE THREAD

**Issue by CernyMatej** [nuxt/nuxt#28845]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.9.0`
- Nuxt Version:     `3.13.1`
- CLI Version:      `3.13.1`
- Nitro Version:    `2.9.7`
- Package Manager:  `pnpm@9.3.0`
- Builder:          `-`
- User Config:      `compatibilityDate`, `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-yd89uq?file=app.vue,components%2FFoo.vue,components%2FBar.vue

### Describe the bug

I've noticed a few issues with component props after updating from Nuxt 3.12.3 to the latest version. I suspect it might be caused by enabling reactive props destructuring by default in Vue 3.5.

1. setting default values for `boolean` props doesn't work (though it does for `string` props, for example)
```ts
const {
    foo = true, // will be `false` if not provided
    bar = 'something', // will be `'something'` if not provided
} = defineProps<{
    foo?: boolean
    bar?: string
}>()
```
2. seemingly, all prop reactivity is lost when using reactive destructure (when changing the prop values, they do not update in the component)
```ts
// It works correctly if defined using the "old" way, though
const props = defineProps<{
    foo?: boolean
    bar?: string
}>()
```

---

The behaviour was the same whether or not I had `vite.vue.script.propsDestructure` set to `true` in `nuxt.config` (though it should not be relevant now that it should be enabled by default?)

### Additional context

I tested it in vue SFC playground and it worked correctly there, so that's why I assume this might be a Nuxt issue

https://play.vuejs.org/#eNqNUlFLwzAQ/ishLyqMFpm+zG6iMkEfdKiPAanttWamuZCkdTD6372kdA5x4tvd9313/fJdt/zKmKRrgc945gorjWcOfGsWQsvGoPXsBhvDKosNO0rS0AT50YXQQmfpMEJiajw0RuUeqGMsK2UXCyrjhnSA0wHP0j01n3DvCtSVrJO1Q01etkEseEGTUoF9NF6idoLPWGQClyuFn/cR87aFyYgX71B8/IKv3SZggq8sOLAdCL7jfG5r8AO9fH6ADdU7ssGyVaT+g3wCh6oNHgfZdatLsr2ni27vYqJS1y9uufGg3fioYDQo+6gXnBIOoR16+rfdaXIW54TuKcXxOj+PyVSu6znN0Zp4Kwrb+WFfhcjmY1I9lSVUUsPKonHZqLicsTdEBTnN9ovjk/8f/xaRjG/jZ3qyefgXeO3AhkDI/DQ5T055/wUEUtzf

**Comment by danielroe** [comment]
this is enabled by default in next nuxt release - for now, see https://github.com/nuxt/nuxt/issues/28829#issuecomment-2329411615.
