### ISSUE TITLE
RollupError: [plugin impound] This module cannot be imported in server runtime.

### ISSUE THREAD

**Issue by gloompiq** [nuxt/nuxt#28850]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.15.1`
- Nuxt Version:     `3.13.1`
- CLI Version:      `3.8.4`
- Nitro Version:    `2.9.7`
- Package Manager:  `pnpm@9.7.0`
- Builder:          `-`
- User Config:      `pinia`, `experimental`, `build`, `components`, `app`, `css`, `imports`, `modules`, `veeValidate`, `security`, `routeRules`, `nitro`, `sourcemap`, `vite`, `ssr`, `runtimeConfig`, `devtools`, `typescript`, `compatibilityDate`
- Runtime Modules:  `@pinia/nuxt@0.4.11`, `@nuxt/devtools@1.3.9`, `@nuxtjs/tailwindcss@6.10.3`, `@vee-validate/nuxt@4.11.6`, `nuxt-security@1.0.0-rc.3`, `@vueuse/nuxt@10.11.0`, `nuxt-typed-router@3.6.4`
- Build Modules:    `-`

### Reproduction

Upgrading nuxt version from 3.8.2 > 3.13.1

### Describe the bug

In our project we needed to upgrade our nuxt version, to be able to use new features, but after simple upgrade with `pnpm dlx nuxi upgrade --force` or just changing nuxt version in `package.json` and installing dependancies breaks our app. It shows one error in terminal and page doesn't open.

### Logs

```shell-script
[nitro 3:32:23 PM]  ERROR  RollupError: [plugin impound] This module cannot be imported in server runtime. [importing @nuxt/kit from ../../node_modules/.pnpm/nuxt-security@1.0.0-rc.3_esbuild@0.23.1_magicast@0.3.4_rollup@4.21.2_vite@5.4.3_@types+node@2_cei4idcc2lai7qg7frbhz37mpm/node_modules/nuxt-security/dist/runtime/nitro/plugins/02-cspSsg.mjs]


undefined

✔ Nuxt Nitro server built in 1220 ms  
ℹ Vite server warmed up in 3063ms
```

**Comment by gloompiq** [comment]
Upgrading `nuxt-security` helped

**Comment by ZhouYu2156** [comment]
this is my accident error: [nitro 11:59:21]  ERROR  RollupError: [plugin impound] Vue app aliases are not allowed in server runtime. [importing #build/app.config.mjs from node_modules/nuxt/dist/app/config.js].  So What's wrong?

**Comment by darylteo** [comment]
`npx nuxi@latest upgrade --force` solved for me (can't just upgrade using `npm-check-updates`)

**Comment by Tini79** [comment]
Same issue here, I've done @darylteo 's solution, but it seems not working to me

**Comment by johnnyicon** [comment]
This error is happening for me. Using the latest nuxt. Tried @darylteo's approach.

```
Node.js v18.20.6
ℹ Cleaning up generated Nuxt files and caches...                                                                                                                                                                                                                                                   nuxi 2:21:02 PM
ℹ Upgraded Nuxt version: 3.15.4                                                                                                                                                                                                                                                                    nuxi 2:21:02 PM
✔ You're already using the latest version of Nuxt. 
```

**Comment by snepsnepy** [comment]
Updating Nuxt version to 3.15.4 fixed the issue for me.

**Comment by salomonsanz** [comment]
It's still happening to me in version 3.16.0

**Comment by HenningGeorgi** [comment]
> Updating Nuxt version to 3.15.4 fixed the issue for me.

This worked for me too

**Comment by salomonsanz** [comment]
for me it's failing in 3.16.0, maybe a regression?

**Comment by HenningGeorgi** [comment]
3.16 is creating some other errors caused by my application specificly, so i´ll stay at 3.15.4 and adapt my application to 3.16.
But 3.15.4 works in dev in production environment
