### ISSUE TITLE
throwing error in API routes does not lead to error page

### ISSUE THREAD

**Issue by BBoehm** [nuxt/nuxt#28868]
### Environment

- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.13.1
- CLI Version:      3.13.1
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-teccg9

### Describe the bug

When throwing an error (using `createError`) from a server api called with `useFetch`, this does not lead to a full-screen error page as expected, but instead returns the error.

Documentation states:
When Nuxt encounters a fatal error (any unhandled error on the server, or an error created with fatal: true on the client) it will either render a JSON response (if requested with Accept: application/json header) or trigger a full-screen error page.

### Additional context

Also happens if we add `fatal: true`

**Comment by danielroe** [comment]
This is expected. No errors in fetching with `useFetch` will trigger any kind of error page. Instead, you need to handle them yourself with the `error` ref returned from it.

Directly visiting `/api/test` would be rendered with an error page.
