### ISSUE TITLE
Long loading time, issues with 'stalled' in the network tab

### ISSUE THREAD

**Issue by gitFoxCode** [nuxt/nuxt#28866]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.12.2
- Nuxt Version:     3.13.1
- CLI Version:      3.13.1
- Nitro Version:    2.9.7
- Package Manager:  npm@10.5.0
- Builder:          -
- User Config:      compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Frest nuxt project, 
```
npx nuxi@latest init test
HOST=127.0.0.1 PORT=7091 npm run dev
```

### Describe the bug

Using my VPS server on Linux, in a monorepo, I'm having issues loading any Nuxt project. When I checked the network tab, I noticed that everything is delayed as 'stalled' – I have no idea what might be causing this problem and what additional information would be needed for debugging

![image](https://github.com/user-attachments/assets/0399c44d-4bf2-44f9-a43d-e09b7ba318b2)
![image](https://github.com/user-attachments/assets/085f27cc-e49a-435d-b8f2-180b09aa6c9f)
![image](https://github.com/user-attachments/assets/8400d110-d04d-44fe-9682-c556a10f550a)
![image](https://github.com/user-attachments/assets/09062279-0242-43ef-84c9-2d7d9cb742b6)

```
> dev
> nuxt dev

Nuxt 3.13.1 with Nitro 2.9.7                                                                                                                                                                 12:27:14 PM
                                                                                                                                                                                             12:27:15 PM
  ➜ Local:    http://127.0.0.1:7091/
  ➜ Network:  use --host to expose

  ➜ DevTools: press Shift + Alt + D in the browser (v1.4.1)                                                                                                                                  12:27:21 PM

✔ Vite client built in 50ms                                                                                                                                                                 12:27:23 PM
✔ Vite server built in 590ms                                                                                                                                                                12:27:23 PM
✔ Nuxt Nitro server built in 741 ms                                                                                                                                                   nitro 12:27:24 PM
ℹ Vite client warmed up in 1ms                                                                                                                                                              12:27:24 PM
ℹ Vite server warmed up in 579ms 
```

**Comment by danielroe** [comment]
Vite advises against disabling the network cache for this very reason.

**Comment by gitFoxCode** [comment]
@danielroe With the network cache option or without, the website behaves the same on every browser – unless there's some other setting I don't know about
![image](https://github.com/user-attachments/assets/c7878ff6-3584-4095-84b2-759ff96e715d)

**Comment by gitFoxCode** [comment]
@danielroe In my real project where there is a lot of content, disabling the 'disable cache' option anyway causes the page to load 20+ seconds and most of the time it is stalled, I assume it's still a cache problem, but I'm not sure how I can fix it 
![image](https://github.com/user-attachments/assets/e4fffda9-70b2-43a9-bb14-0c9675a8ba0c)
![image](https://github.com/user-attachments/assets/4993abd3-7158-46b7-8b5a-1d048704e876)

**Comment by mmpneo** [comment]
@danielroe stalls have nothing to do with cache (?? what a weird statement)

i'm actually getting stalls with 3.13 too. but **only in chromium** browsers which is little weird.

**Comment by IvanRoslov** [comment]
I’ve also encountered this issue. If I clear the cache in the browser, the site loads fine, but as soon as I click on a link leading to another route, I get a large “stalled” delay.

I conducted load testing on the server, and the file is served very well, so I don’t understand where this “stalled” delay is coming from.
![Image](https://github.com/user-attachments/assets/bdf51c25-3a7f-4c67-bb38-e2d4f943b1ca)
