### ISSUE TITLE
Cannot read properties of undefined (reading 'innerWidth') 

### ISSUE THREAD

**Issue by Foddie2** [nuxt/nuxt#28889]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.11.1
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  @nuxtjs/tailwindcss@6.12.0, @vueuse/nuxt@11.0.3
- Build Modules:    -
------------------------------

### Reproduction

https://codesandbox.io/p/github/Foddie2/TechBytes254/main?import=true&workspaceId=fd7a4f18-b726-4bdb-bbee-a2bae581bfea

### Describe the bug

Getting the error below both in production and dev environment

> Cannot read properties of undefined (reading 'innerWidth')

**Comment by warflash** [comment]
innerWidth or window in general is not available during SSR so you need to make sure your plugin is only loaded on the client where those exist. e.g. https://stackblitz.com/edit/github-cm1lze?file=plugins%2Faos.client.js. There's also a dedicated AOS nuxt module in case that helps

**Comment by Foddie2** [comment]
Thanks @warflash, this works
