### ISSUE TITLE
Will Nuxt release an app router similar to Next in the future?

### ISSUE THREAD

**Issue by bbhxwl** [nuxt/nuxt#28904]
Now the page and the components it needs to use are separated into multiple directories, as well as APIs. This is difficult to manage

If the Vue component is written into pages, it will be treated as a page router.

**Comment by silvesterwali** [comment]
`If the Vue component is written into pages, it will be treated as a page router.`  already like that please check i guest. this https://nuxt.com/docs/guide/directory-structure/pages  will help you

**Comment by danielroe** [comment]
It's possible to use layers to separate bits of your app into self contained Nuxt projects (with components/pages directories of their own).

Or you can use an ignore prefix to ignore directories within pages/

See https://www.youtube.com/watch?v=fr5yo3aVkfA and https://deltener.com/blog/nuxt-enterprise-patterns-component-management/

**Comment by bbhxwl** [comment]
> It's possible to use layers to separate bits of your app into self contained Nuxt projects (with components/pages directories of their own).
> 
> Or you can use an ignore prefix to ignore directories within pages/
> 
> See https://www.youtube.com/watch?v=fr5yo3aVkfA and https://deltener.com/blog/nuxt-enterprise-patterns-component-management/
> 
> Beyond that, there doesn't currently seem a need for more, but please let me know if you have a need Nuxt isn't meeting for you 🙏

I want to write the components that only need to be used once near page. vue for easy code organization. It seems that layer cannot meet this requirement, right? Is layer used as a template to inherit the project?

**Comment by bbhxwl** [comment]
> `If the Vue component is written into pages, it will be treated as a page router.` 已经这样了，请查看文档 https://nuxt.com/docs/guide/directory-structure/pages 将帮助你

Are you referring to layers? Is that convenient for organizing multiple projects? But it is not convenient to organize the components used for individual pages.

**Comment by bbhxwl** [comment]
> It's possible to use layers to separate bits of your app into self contained Nuxt projects (with components/pages directories of their own).
> 
> Or you can use an ignore prefix to ignore directories within pages/
> 
> See https://www.youtube.com/watch?v=fr5yo3aVkfA and https://deltener.com/blog/nuxt-enterprise-patterns-component-management/
> 
> Beyond that, there doesn't currently seem a need for more, but please let me know if you have a need Nuxt isn't meeting for you 🙏


I can automatically import components, but I cannot delete this page.


<img width="1186" alt="image" src="https://github.com/user-attachments/assets/8a68e8f2-761c-4ae4-a7e6-3fcc33592ceb">
<img width="611" alt="image" src="https://github.com/user-attachments/assets/406fb024-ccab-4908-bf4e-21bcfd7e1ceb">

**Comment by danielroe** [comment]
Please read the second link I provided. I think it is exactly what you are asking for.

**Comment by bbhxwl** [comment]
> Please read the second link I provided. I think it is exactly what you are asking for.

See, will this increase the loss of operational performance? It would be even better if nuxt could provide a built-in feature.
