### ISSUE TITLE
addComponent(opts)  --- ERROR  unhandledRejection] Cannot read properties of undefined (reading 'match')

### ISSUE THREAD

**Issue by BananaAcid** [nuxt/nuxt#28900]
### Environment

- Operating System: Darwin
- Node Version:     v22.3.0
- Nuxt Version:     3.13.1
- CLI Version:      3.13.1
- Nitro Version:    2.9.7
- Package Manager:  npm@10.8.1
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

modules.ts
does not work:
```
async setup(_options, _nuxt) {
    const { resolve } = createResolver(import.meta.url);
    addComponent({
      name: 'AbcDef',
      filepath: resolve('./runtime/app/components/AbcDef.vue'),
    });
}
```

### Describe the bug

---> filePath would have been correct. My bad.

```
async function addComponent(opts) {
  const nuxt = useNuxt();
  await assertNuxtCompatibility({ nuxt: ">=2.13" }, nuxt);
  nuxt.options.components = nuxt.options.components || [];
  if (!opts.mode) {
    const [, mode = "all"] = opts.filePath.match(/\.(server|client)(\.\w+)*$/) || [];   <------- index.mjs:2922:44
    opts.mode = mode;
  }
```

### Additional context

`mode (optional)`

see: https://nuxt.com/docs/api/kit/components#options

### Logs

```shell-script
ERROR  [unhandledRejection] Cannot read properties of undefined (reading 'match')                                                          19:54:47

  at Object.addComponent [as key] (node_modules/@nuxt/kit/dist/index.mjs:2922:44)
```

**Comment by BananaAcid** [comment]
An assert or or any other option guard would have been nice ;)

@danielroe

**Comment by danielroe** [comment]
Did you get a TS error in your IDE?

**Comment by BananaAcid** [comment]
Yes, after manually restarting the TS server in VSCode I got the typical messy TS-Error when trying to use the options varisble as parameter.
