### ISSUE TITLE
Page Transitions not synchronized with useAsyncData

### ISSUE THREAD

**Issue by ilyamsts** [nuxt/nuxt#28913]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.10.0
- Nuxt Version:     3.12.3
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, compatibilityDate, app, dir, alias, modules, css, hooks, viewport, image, primevue, content, vite
- Runtime Modules:  @nuxt/eslint@0.3.13, @nuxt/image@1.7.0, nuxt-viewport@2.1.5, nuxt-primevue@3.0.0, @nuxt/content@2.13.2, @pinia/nuxt@0.5.3, @pinia-plugin-persistedstate/nuxt@1.2.1
- Build Modules:    -

### Reproduction

https://codesandbox.io/p/devbox/compassionate-sammet-n7qj63

### Describe the bug

Im using page transition and when navigate for example from **"user/1"** to **"user/2"** page, my in page useAsyncData load some data from API's and update it **before new page transition comes in**. So, first the user sees the updated data and then the animation transition. This behavior causes ugly data flashes. It is normal or how to deal with it?

**Comment by danielroe** [comment]
This is because your `key` in your `useAsyncData` does not include a reference to `page.value` - so it's shared between the two pages. Instead, make sure to reference the user value in the key.

```ts
const { data } = await useAsyncData("user", () =>
  $fetch(`https://jsonplaceholder.typicode.com/users/${page.value}`, {
    watch: false,
  })
);
```

**Comment by ilyamsts** [comment]
Many thanx @danielroe, work perfectly
