### ISSUE TITLE
npm audit fix --force instalss nuxt 1.4.5

### ISSUE THREAD

**Issue by Posoroko** [nuxt/nuxt#28935]
### Environment

I'm not a pro at all with nmp and dependencies, buther's what happened.

I modified the package.json file to update nuxt and other dependencies to their latest versions :
```
"dependencies": {
    "@directus/sdk": "^17.0.1",
    "@vueuse/core": "^11.0.3",
    "@vueuse/nuxt": "^10.0.3",
    "nuxt": "^3.13.1",
    "vue": "^3.5.4",
    "vue-router": "^4.4.4"
  },
```

after deleting the node_modules folder and running npm install, i got this message in the console:

```
5 moderate severity vulnerabilities
To address all issues (including breaking changes), run:
  npm audit fix --force
```

when running this command, it installed nuxt 1.4.5 and updated the package.json file:

```
"nuxt": "^1.4.5",
```

Is that normal ? 
Just thought I would let you know in case it's not.

### Reproduction

update dependencies in package.json
run the command  npm audit fix --force

### Describe the bug

After updating to nuxt 3.13.1, audit fix installs nuxt 1.4.5

**Comment by danielroe** [comment]
Thanks for alerting.

This is caused by nitropack relying on `serve-static`, which has an open vulnerability. However, this is only used in dev-mode and we do have plans to migrate away from it. You can safely ignore this report for now.

cc: @pi0

**Comment by Posoroko** [comment]
ok, cool  !  Thanks for you response !
