### ISSUE TITLE
Pages Ref doesn't work from nuxt documentation

### ISSUE THREAD

**Issue by JoniLieh** [nuxt/nuxt#28942]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.15.0
- Nuxt Version:     3.13.1
- CLI Version:      3.13.1
- Nitro Version:    2.9.7
- Package Manager:  bun@1.1.24
- Builder:          -
- User Config:      runtimeConfig, imports, css, build, pinia, experimental, $production, $development, app, modules, vite, security, csurf, routeRoules, nitro, pwa, compatibilityDate
- Runtime Modules:  @vueuse/nuxt@11.0.3, @pinia/nuxt@0.5.4, @vite-pwa/nuxt@0.10.5, nuxt-security@2.0.0-rc.9, ()
- Build Modules:    -
------------------------------

### Reproduction

Implement as described here: https://nuxt.com/docs/api/components/nuxt-page#pages-ref
stackblitz: https://stackblitz.com/edit/nuxt3-welcome-uf57hg?file=pages%2Fitems.vue,pages%2Fitems%2Findex.vue,app.vue

### Describe the bug

I was trying to call a function from a nuxtpage-child with the pageRef and defineExpose as documented, but the function exposed function is undefined in the pageRef

**Comment by huang-julien** [comment]
Hey :wave: can you try to install `ufo` in your dependencies ?

**Comment by JoniLieh** [comment]
I installed ufo in the given stackblitz, doesnt work, the button in the stackblitz should send an alert and log, but doesnt.

**Comment by danielroe** [comment]
this seems to work in the stackblitz.

https://github.com/user-attachments/assets/93935913-79fc-4892-93de-015d0b4fce1a

**Comment by danielroe** [comment]
I believe this is a limitation of template refs in Vue.

Let's track in https://github.com/vuejs/core/issues/4930

**Comment by JoniLieh** [comment]
Thank you very much, 
I made a workaround for anybody finding this:
```ts
const { data, error, status, refresh, execute } = useFetch(
  `https://jsonplaceholder.typicode.com/todos`,
  {
    immediate: false,
  }
);

const refreshItems = () => {
  console.log('refreshItems.... in items/index');
  alert('Working yo in items/index');
  refresh();
};

defineExpose({ refreshItems });

await execute();
```
_(Gosh, I love Nuxt)_
