### ISSUE TITLE
Autoimport useTemplateRef TS

### ISSUE THREAD

**Issue by tandler5** [nuxt/nuxt#28957]
### Environment

Nuxt 3.13.0 with Nitro 2.9.7  

### Reproduction

https://codesandbox.io/p/devbox/github/nuxt/starter/tree/v3?embed=1&file=%2Fapp.vue

### Describe the bug

useTemplateRef is imported but the editor does not know about it (types etc..)

**Comment by manniL** [comment]
Make sure you have the latest unimport version (3.12.0 or later). This was added @ https://github.com/unjs/unimport/pull/370

**Comment by danielroe** [comment]
You need to have Nuxt v3.13.1+.

The auto-import of `useTemplateRef` was added in that version via https://github.com/nuxt/nuxt/pull/28285.
