### ISSUE TITLE
Assets loading fails due to CORS error

### ISSUE THREAD

**Issue by aperpinal** [nuxt/nuxt#28953]
### Environment

Production

### Reproduction

-

### Describe the bug

I'm migrating from Nuxt 2 to 3. I'm moving the assets created in the output dir to a CDN i have (with another URL than the site). I that CDN i have this config:
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET",
            "HEAD",
            "DELETE",
            "PUT",
            "POST"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": [],
        "MaxAgeSeconds": 3000
    }
]
When the site gets deployed i get a CORS error for some files (not all of them). But the site doesn't work anyway.
The sec-fetch-mode in the request header of the assetsis cors (in nuxt 2 is no-cors) and almost all the link tags in the <head> have the crossorigin in it.
Is there a way to configure the site in a way that the js, css, json, etc. assets are requested with no cors?
It's being really hard to implement a CDN this way, and i need it.

**Comment by danielroe** [comment]
ESM scripts loaded in the browser must be loaded with CORS: see https://jakearchibald.com/2017/es-modules-in-browsers/#always-cors.

**Comment by danielroe** [comment]
CSS styles that are loaded on dynamic import (e.g. on page navigation) are injected by Vite using this code:

https://github.com/vitejs/vite/blob/11e844984b4465ba16ed2493d6bec2398fc11555/packages/vite/src/node/plugins/importAnalysisBuild.ts#L125-L135
