### ISSUE TITLE
Nuxt 4 beta Layers with Nuxt UI not working correctly.

### ISSUE THREAD

**Issue by sosensible** [nuxt/nuxt#28963]
### Environment

I used the Hello World template, works. 
Added the content, works. 
Added a layer... kinda works but that template has Nuxt UI Pro.

### Reproduction

Added the nested layer and created a component called <Bob />. I tried to put class="prose," and that changed the results, but it still did not work. Added the nested layer and created a component called <Bob />. The content isn't formatted correctly.

The I created a component in the non-layer called <Ralph /> and it has the same issue.

### Describe the bug

Without prose, it does what we expect with tailwind. The content is wrapped in a header tag. With prose on a dark screen, you don't see it because it fails to format correctly—the header text is dark.

It appears the issue is not with Layers, and perhaps this needs to go to Nuxt UI?

**Comment by danielroe** [comment]
This sounds like it might be a Nuxt-modules/tailwindcss issue. Would you see if you can reproduce with just that module? 🙏

**Comment by sosensible** [comment]
I replaced NuxtUI with DaisyUI, and things are working. I don't have an example, but my bias is that I wonder if the way NuxtUI works from one layer to the next needs some documentation. (at least for those using NuxtUI with a layer-based app)

**Comment by sosensible** [comment]
I redid the project after getting it working with Daisy, and now it is working with NuxtUI. Sadly, I did not commit the version that was failing earlier, but it is great. It looks like I will be moving to NuxtUI moving forward.
