### ISSUE TITLE
types: useError is not correctly typed as per documentation

### ISSUE THREAD

**Issue by josselinonduty** [nuxt/nuxt#28977]
### Environment

- Operating System: Linux
- Node Version:     v20.13.1
- Nuxt Version:     3.13.1
- CLI Version:      3.13.1
- Nitro Version:    2.9.7
- Package Manager:  npm@10.8.3
- Builder:          -
- User Config:      compatibilityDate, devtools, modules, routeRules, app, vite, runtimeConfig, ignore, tailwindcss, colorMode, prisma, veeValidate, pwa, i18n, csurf
- Runtime Modules:  @nuxtjs/tailwindcss@6.12.1, @vite-pwa/nuxt@0.10.5, @nuxtjs/color-mode@3.4.4, @nuxtjs/robots@4.1.6, nuxt-csurf@1.6.2, @nuxt/icon@1.5.1, @prisma/nuxt@0.0.35, @vee-validate/nuxt@4.13.2, @nuxt/test-utils/module@3.14.1, @nuxtjs/i18n@8.5.3
- Build Modules:    -

### Reproduction

1. npx nuxi init repro (npm, no git)

### Describe the bug

Inside `node_modules/nuxt/dist/app/composables/error`:

```ts
export declare const useError: () => any;
```

`useError` composable is not typed.

According to the [documentation](https://nuxt.com/docs/getting-started/error-handling#useerror), it should be:

```ts
function useError (): Ref<Error | { url, statusCode, statusMessage, message, description, data }>
```

**Comment by Twocram** [comment]
@josselinonduty @danielroe 

Hello guys! I made PR for this issue: https://github.com/nuxt/nuxt/pull/28996
