### ISSUE TITLE
Nuxt Layer isn't installing dev dependencies

### ISSUE THREAD

**Issue by jd-solanki** [nuxt/nuxt#28975]
### Environment

- Operating System: Linux
- Node Version:     v20.15.0
- Nuxt Version:     3.13.1
- CLI Version:      3.13.1
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.4.0
- Builder:          -
- User Config:      extends, compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

1. [Create](https://nuxt.com/docs/getting-started/installation#new-project) fresh nuxt project
2. Extend the nuxt content theme like below:
	```ts
	export default defineNuxtConfig({
	  extends: [
	    ['github:jd-solanki/nuxtpress', { install: true }]
	  ],
	  compatibilityDate: '2024-04-03',
	  devtools: { enabled: true }
	})
	```

### Describe the bug

Let's focus on one issue at a time.

**When I perform `ni` (`pnpm install`) it doesn't install dev deps like tailwind, sass, etc. I've to run command `NODE_ENV=development ni`**

> [!NOTE]
> Below is details of old issue 

Once we have above setup here's list of issues I'm running into:

- [ ] When I perform `ni` (`pnpm install`) it doesn't install dev deps like tailwind, sass, etc. I've to run command `NODE_ENV=development ni`
- [ ] After installing all deps when I run `pnpm run dev` it throws `[worker reload] [worker init] Cannot find package 'nitropack' imported from /home/tops/Projects/oss/nuxtpress-docs/.nuxt/dev/index.mjs`. Along with this I also get some error related to `sass-embed`.~~
	![image](https://github.com/user-attachments/assets/e4b4f586-e16c-487c-8713-c6a86df0e2ed)
- [ ] Also my nuxtpress repo is cached because when I already have a new push to the github but still it uses old commits so it'll be great if we can get docs on clearning layer cache if there's any
- [ ] I'm also getting other deps warns when I run `pnpm run dev`:

	<details>
	<summary>View warnings</summary>
	
	```shell
	 WARN  Failed to resolve dependency: @nuxt/content > slugify, present in 'optimizeDeps.include'                                                                                                                         
	 WARN  Failed to resolve dependency: @nuxt/content >remark-gfm, present in 'optimizeDeps.include'                                                                                                                       
	 WARN  Failed to resolve dependency: @nuxt/content >remark-emoji, present in 'optimizeDeps.include'                                                                                                                     
	 WARN  Failed to resolve dependency: @nuxt/content >remark-mdc, present in 'optimizeDeps.include'                                                                                                                       
	 WARN  Failed to resolve dependency: @nuxt/content >remark-rehype, present in 'optimizeDeps.include'                                                                                                                   
	 WARN  Failed to resolve dependency: @nuxt/content >rehype-raw, present in 'optimizeDeps.include'                                                                                                                      
	 WARN  Failed to resolve dependency: @nuxt/content >parse5, present in 'optimizeDeps.include'                                                                                                                          
	 WARN  Failed to resolve dependency: @nuxt/content >unist-util-visit, present in 'optimizeDeps.include' 
	 WARN  Failed to resolve dependency: @nuxt/content >unified, present in 'optimizeDeps.include'                                                                                                                        
	 WARN  Failed to resolve dependency: @nuxt/content >debug, present in 'optimizeDeps.include'
	```
	
	</details>

### Additional context

This is my development setup:
```ts
export default defineNuxtConfig({
  extends: [
    [process.env.NODE_ENV === "development" ? '../content-app/' : 'github:jd-solanki/nuxtpress', { install: true }]
  ],
  future: {
    compatibilityVersion: 4,
  },
  compatibilityDate: '2024-04-03',
  devtools: { enabled: true }
})
```

**Comment by danielroe** [comment]
> When I perform ni (pnpm install) it doesn't install dev deps

If dependencies are required for your Nuxt layer to work, they should not be in the `devDependencies` list but `dependencies`.

For the other issues, would you mind creating separate issues for each of them so we can track/resolve them separately? It will make it easier and be more helpful for other users who encounter one of them.

**Comment by jd-solanki** [comment]
Hi @danielroe 

I hope you enjoyed the holiday 🏖 

> If dependencies are required for your Nuxt layer to work, they should not be in the devDependencies list but dependencies.

However, deps like tailwindcss & sass are devDeps by nature so is it good idea to add them under dependencies?

> For the other issues, would you mind creating separate issues for each of them so we can track/resolve them separately? It will make it easier and be more helpful for other users who encounter one of them.

Sure.

**Comment by danielroe** [comment]
All dependencies needed by your nuxt layer to be _used_ should be in `dependencies`. devDependencies in the context of a layer should be things needed only when authoring the layer but not when it is consumed (like `eslint`, perhaps)
