### ISSUE TITLE
Add warning for @ prefix in build.transpile

### ISSUE THREAD

**Issue by MasterCarl** [nuxt/nuxt#28985]
## Summary
Warn users about incorrect `@scoped/package` usage instead of `scoped/package` in `build.transpile` array.

## Background
Following an upgrade from Nuxt 3.12.4 to 3.13.1, usage of the `@hyperdx/lucene` from another Nuxt layer suddenly threw an error:
```
The requested module '/_nuxt/@fs/.../monorepo/frontend/node_modules/@hyperdx/lucene/lib/lucene.js?v=7e5012eb' does not provide an export named 'toString'
```

This issue seems related to https://github.com/nuxt/nuxt/issues/28631

I was able to solve the problem by adding 
```ts
build: {
    transpile: [
      "hyperdx/lucene",
    ],
  },
```
to my `nuxt.config.ts`. As pointed out in https://github.com/nuxt/nuxt/issues/24064#issuecomment-1788740269, 
> Note in the transpile array there is no @ before typeform/embed,

the `@` scope prefix from the npm package name needed to be omitted.

It would be helpful to get a warning or error message about the (presumably) incorrect `@` prefixing of packages to be transpired.

## Alternatives and questions
- Could the implementation be changed to work correctly with `@scoped/package`s?
- Would this better be fixed in another package?

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
This is a bug - you should be able to add '@hyperdx/lucene`. Would you be able to provide a reproduction? 🙏
