### ISSUE TITLE
✨ Allow setting middleware & routeMeta through routeRules

### ISSUE THREAD

**Issue by jd-solanki** [nuxt/nuxt#28994]
### Describe the feature

Hi 👋🏻 

## Problem

I'm building app that uses hybrid rendering and I've my main app under `/app` URL and is set to `ssr: false` (SPA). Rest of the website is SSR enabled which includes landing page, docs, blog, login, etc. This SSR content is public where as everything inside `/app` route is private which requires authentication.

I created auth middleware that checks for authentication but it's not straight forward to add it to all routes under `/app`. There are three ways for me that I'm aware of:
1. Set `guestRoute` meta on all SSR page (Bad DX because we have to set this meta in all pages)
2. Set `authRequired` meta on all `/app` pages which is also same as above
3. [Settings middleware at build time](https://nuxt.com/docs/guide/directory-structure/middleware#setting-middleware-at-build-time) - This is fine but if possible adding directly to routeRules will match the DX of what nuxt provides
4. I don't know if it's possible but creating root `/app` route (/pages/app/index.vue) that renders all `/app` routes as nested routes. (Not sure about possibility & very hacky)

## Solution

1. For first two workarounds if we allow settings route meta in `routeRules` then we can modify the middleware to check for route meta and it will work fine
2. Another solution is to allow directly providing middleware in routeRules

```ts
export default defineNuxtConfig({
  routeRules: {
    '/app/*': {
		ssr: false,
		pageMeta: { authRequired: true }, // Via route meta
		middleware: ["auth"], // Directly specify middleware
	},
  },
})
```

---

Apart from this, I don't know if adding `pageMeta` & `middleware` is possible in `routeRules` if `routeRules` is from nitro.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
This is already possible - the key is called `appMiddleware`, and the PR implementing it was https://github.com/nuxt/nuxt/pull/25841.
