### ISSUE TITLE
useAsyncData use  $csrfFetch  

### ISSUE THREAD

**Issue by f754699** [nuxt/nuxt#29007]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.20.3
- Nuxt Version:     3.13.0
- CLI Version:      3.13.1
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.4.0
- Builder:          -
- User Config:      compatibilityDate, devtools, modules, eslint, pwa, csurf, vite, build, app, vueuse, devServer, hooks, pinia, css
- Runtime Modules:  @unocss/nuxt@0.62.3, @nuxtjs/device@3.2.2, @nuxt/eslint@0.5.5, @pinia/nuxt@0.5.4, @pinia-plugin-persistedstate/nuxt@1.2.1, @vueuse/nuxt@11.0.3, @vite-pwa/nu
xt@0.10.3, nuxt-csurf@1.6.2, nuxt-authorization@0.0.4, nuxt-icon@0.6.10, nuxtjs-naive-ui@1.0.2
- Build Modules:    -

### Reproduction

无

### Describe the bug

我使用useAsyncData在服务端获取数据，且引入了 'nuxt-csurf'。
如果我使用$fetch,就会触发403错误，
如果我使用$csrfFetch，就返回错误，空数据，无法解析。
-------------------------------------------------------------------------
I use 'useAsyncData' to retrieve data on the server and introduce 'nuxt csurf'.
If I use $fetch, it will trigger a 403 error,
If I use $csrfFetch, it returns an error, empty data, and cannot be parsed.

**Comment by danielroe** [comment]
This seems like it might be a bug with nuxt-csrf. Would you raise an issue against that repository? 🙏

**Comment by f754699** [comment]
nuxt-csurf里面有解决方法，我关闭了
