### ISSUE TITLE
`useFetch` twice "A composable that requires access to the Nuxt instance was called outside of a plugin..."

### ISSUE THREAD

**Issue by ElYaiko** [nuxt/nuxt#29003]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.15.1
- Nuxt Version:     3.13.1
- CLI Version:      3.13.1
- Nitro Version:    2.9.7
- Package Manager:  bun@1.1.28
- Builder:          -
- User Config:      compatibilityDate
ui, tailwindcss, css, vite, nitro, typescript
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-jdafkm?file=app.tsx

### Describe the bug

Calling `useFetch` / `useLazyFetch` with await returns:
`[nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at `https://nuxt.com/docs/guide/concepts/auto-imports#vue-and-nuxt-composables`.`

When I remove the `await` the page loads but I'm not sure is the correct way of using `useFetch`.

**Comment by huang-julien** [comment]
Hey :wave: when using non-sfc component, please prefer to wrap your component with `defineNuxtComponent` instead of `defineComponent` from `vue`

`defineNuxtComponent` wraps the setup function to correctly set the context when running it.
