### ISSUE TITLE
Vee validate auto imports no longer working

### ISSUE THREAD

**Issue by rocketiscool** [nuxt/nuxt#29024]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.14.0`
- Nuxt Version:     `3.13.2`
- CLI Version:      `3.13.2`
- Nitro Version:    `2.9.7`
- Package Manager:  `pnpm@9.10.0`
- Builder:          `-`
- User Config:      `runtimeConfig`, `modules`, `veeValidate`, `security`, `components`, `hooks`, `vite`, `build`, `future`, `devServer`, `extends`, `compatibilityDate`
- Runtime Modules:  `nuxt-csurf@1.6.2`, `@vee-validate/nuxt@4.13.2`
- Build Modules:    `-`

### Reproduction

None

### Describe the bug

The requested module '/node_modules/.pnpm/vee-validate@4.13.2_vue@3.5.6_typescript@5.6.2_/node_modules/vee-validate/dist/vee-validate.js?v=a5b22073' does not provide an export named 'Field'

After upgrading to Nuxt 3.12.2

```
modules: [
        'nuxt-csurf',
        '@vee-validate/nuxt'
    ],
    veeValidate: {
        autoImports: true,
        componentNames: {
            Form: 'VeeForm',
            Field: 'VeeField',
            FieldArray: 'VeeFieldArray',
            ErrorMessage: 'VeeErrorMessage'
        }
    },
```

**Comment by huang-julien** [comment]
Hello :wave: this is probably an issue in veevalidate. Can you open the issue in vee-validate repository ?

**Comment by rrubio** [comment]
+1
