### ISSUE TITLE
Plugin type `IsAny` check broken broken in Typescript 5.5 & above

### ISSUE THREAD

**Issue by Eazash** [nuxt/nuxt#29021]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.17.0`
- Nuxt Version:     `3.13.2`
- CLI Version:      `3.13.2`
- Nitro Version:    `-`
- Package Manager:  `pnpm@9.9.0`
- Builder:          `-`
- User Config:      `compatibilityDate`, `devtools`, `modules`, `scripts`
- Runtime Modules:  `@nuxt/scripts@0.8.5`
- Build Modules:    `-`

### Reproduction

[https://github.com/Eazash/nuxt-plugin-type-reproduction](https://github.com/Eazash/nuxt-plugin-type-reproduction)

### Describe the bug

In the event that a registry script is enabled from module config, nuxt scripts calls `extendTypes` to insert its plugin registration for registry scripts (https://github.com/nuxt/scripts/blob/84c6c4c039523485e84e058f50ef66272ecec45a/src/module.ts#L160). This adds `InjectionType<typeof import("../modules/@nuxt-scripts.js").default>`. 

The generated `.nuxt/modules/@nuxt-scripts.d.ts` file however does not have a default export & `IsAny<typeof import("../modules/@nuxt-scripts.js").default>` resolves to `any` as of typescript 5.5. This in turn means that `InjectionType<typeof import("../modules/@nuxt-scripts.js").default>` resolves to `any` and breaks plugin type injections for all plugins, including custom plugins. 

### Additional context

The above reproduction uses `@nuxt/scripts` to recreate the issue but I believe the bug is widespread. The root cause is that as of microsoft/typescript#58610, the "error" `any` behaves differently from regular `any`. This somehow causes `IsAny<typeof import("../modules/@nuxt-scripts.js").default>` to resolve to `any` instead of `true`

Related Issues
- microsoft/typescript#59981
- microsoft/typescript#58960

**Comment by danielroe** [comment]
We should probably hotfix in `@nuxt/scripts` as well as investigating `IsAny` usage here in nuxt/nuxt.

**Comment by harlan-zw** [comment]
Hm I think the issue relates to the fact that the I've named the type declaration file the same as the plugin name. I've pushed up a fix to use a unique name for the template.

This seems to stop the path from getting added to `NuxtAppInjections`.
