### ISSUE TITLE
Potential regression: notivue stopped working with nuxt v3.13.2

### ISSUE THREAD

**Issue by peralta** [nuxt/nuxt#29028]
### Environment

```
notivue v2.4.5
nuxt v3.13.2
```

### Reproduction

1. Use Notivue playground: https://stackblitz.com/edit/nuxt-starter-fnhcmx?file=pages%2Findex.vue
2. Upgrade nuxt to v3.13.2: `nuxi upgrade -f`
3. Run nuxt in **dev mode**. Example page breaks

### Describe the bug

Potential regression, as Notivue v2.4.5 used to work with Nuxt v3.13.1 without issues. Now `nuxt dev` breaks with:
```
Cannot destructure property 'isRunning' of 'useNotivueInstance(...)' as it is undefined.
```
I opened https://github.com/smastrom/notivue/issues/69 against Notivue just in case.

**Comment by Xseron** [comment]
Same issue
