### ISSUE TITLE
[Vue Router warn]: No match found for location with path "/notifications.js"

### ISSUE THREAD

**Issue by reazan** [nuxt/nuxt#29042]
### Environment

- Operating System: Windows 10
- Node Version: v20.15.0
- Nuxt Version: 3.13.2
- Nitro Version: 2.9.7
- Package Manager: bunjs
- IDE: Visual Studio Code (latest version)

### Reproduction

# Steps to reproduce (1)
https://github.com/reazan/nuxt3-route-warning

1. Clone the repo (main branch)
1. Install the dependencies "bun install"
1. Run "bun run dev" and open the index page (localhost:3000)
1. The console running the nuxt server should show the following warning:

![image](https://github.com/user-attachments/assets/a2a06022-c082-4f2f-9b0f-0fe75a79fbef)

# Steps to reproduce (2)
https://stackblitz.com/~/github.com/reazan/nuxt3-route-warning

Same repository but with stackbiltz. The error is different but still about the vue router

![image](https://github.com/user-attachments/assets/0bee0bd1-fc53-4dc3-b4da-8cce49c58b91)

### Describe the bug

Hi,

I just started a new project, I installed Nuxt via Bun and started dev: everything is fine.
I added the /page folder with a single file "index.vue" with only a <div>
I also changed the app.vue to use NuxtPage instead of NuxtWelcome etc

I run "bun run dev" and navigated to localhost:3000 where the basic page is displayed correctly but in the terminal a lot of warning came up:

![image](https://github.com/user-attachments/assets/09d0664a-0f3c-47cc-a158-885155868f7f)

All these warnings only to landing on the page.
I did not setup nothing with name "notifications" etc

Thanks for your works!

**Comment by danielroe** [comment]
It's not a bug. It's a 404 and Vue-router is telling you so. Something is requesting those paths. Maybe a service worker is requesting notifications.js.

**Comment by reazan** [comment]
> It's not a bug. It's a 404 and Vue-router is telling you so. Something is requesting those paths. Maybe a service worker is requesting notifications.js.

Thanks for your response, didn't notice and it was a service worker. My bad.

**Comment by coderlelouch** [comment]
However, including static resource paths that I previously referenced but deleted (even those developed locally for different nuxt projects but with the same address), this warning has been consistently generated

**Comment by danielroe** [comment]
this is because you have other tabs or service workers requesting those routes. the warning is simply telling you that vue router is returning a 404
