### ISSUE TITLE
404 error screen appears after navigating to a non-existing page even when there is a global middleware that redirects to an existing page

### ISSUE THREAD

**Issue by nicky1038** [nuxt/nuxt#29051]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.17.0
- Nuxt Version:     3.13.2
- CLI Version:      3.13.2
- Nitro Version:    2.9.7
- Package Manager:  npm@10.8.2
- Builder:          -
- User Config:      compatibilityDate, ssr
- Runtime Modules:  -
- Build Modules:    -
------------------------------
The bug does not depend on OS because it was reproduced in an app deployed via GitHub Actions

### Reproduction

Demo repo: https://github.com/nicky1038/nuxt-404-demo
The app is deployed via GitHub Actions: https://nicky1038.github.io/nuxt-404-demo

Reproduction is simple:
* go to https://nicky1038.github.io/nuxt-404-demo/non-existing (or http://localhost:3000/non-existing if you launched the dev server)

404 screen will appear but it shouldn't, since there should be a redirect to `/existing-page`

It is noteworthy that:
* nuxt 3.12.0 is the first version with this bug
* this bug appears only when `ssr: false` is set

### Describe the bug

Since nuxt 3.12, when using `ssr: false` option, there is a bug.

Before 3.12, a global middleware could be used to redirect users from non-existing pages to existing ones, without the need to create dummies for that non-existing pages.

Now, even if there is such a global middleware with redirects to existing pages, there is a 404 error, when the page that user visits at first does not exist.

**Comment by ThibaultVlacich** [comment]
I think this is the same issue as #27903
