### ISSUE TITLE
setting cache for SSG with ssr false

### ISSUE THREAD

**Issue by breizhwave** [nuxt/nuxt#29053]
### Describe the feature

Hi, can some one tell me how to specify cache (no-cache) headers in the case of static generation with ssr false (fails with ssr true)

I tried the   following config in nuxt.confi.gts, works on pnpm dev but not on generated files 
```
 nitro: {
        routeRules: {
            "/*": { headers: { 'cache-control': `no-cache` } }, //https://stackoverflow.com/questions/72977133/nuxt-3-how-to-add-cache-control-to-generated-static-files

        }
    },
```
 also tried this method using a plugin

https://stackoverflow.com/questions/72977133/nuxt-3-how-to-add-cache-control-to-generated-static-files

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
Where do you deploy to?

If you only have static files (`nuxt generate`), this routeRule might not do anything (except on platforms supporting setting headers like Netlify or Vercel for example).

**Comment by breizhwave** [comment]
@manniL thks for your answer, I deploy  to static host, with `pnpm generate`and I confirm the routeRoule only works on  `pnpm dev`, hence my question here :)

**Comment by breizhwave** [comment]
found the answer, thks CHATGPT, I did it via htaccess, example here for APACHE

```

<IfModule mod_headers.c>
        Header set Cache-Control "no-cache, no-store, must-revalidate"
</IfModule>
```
