### ISSUE TITLE
unocss cant transform less variable at build time

### ISSUE THREAD

**Issue by xjccc** [nuxt/nuxt#29066]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.10.0
- Nuxt Version:     3.13.2
- CLI Version:      3.13.2
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.5.0
------------------------------

### Reproduction

https://stackblitz.com/edit/github-e1dfk2?file=nuxt.config.ts,app.vue

### Describe the bug

1. npm run build
![image](https://github.com/user-attachments/assets/4d3fbd00-87ce-41b0-a78d-ec15df0b1795)

**Comment by danielroe** [comment]
this should probably be raised with `unocss` if you think it's a bug.

it's reproducible without nuxt: 

![CleanShot 2024-09-19 at 12 22 21@2x](https://github.com/user-attachments/assets/bd1a3bdc-22ac-4cfe-85de-49778ddbc83b)

https://stackblitz.com/edit/github-7qswuv
