### ISSUE TITLE
I encountered a problem when using nuxt3：[nuxt] Failed to stringify dev server logs. Received DevalueError: Cannot stringify arbitrary non-POJOs

### ISSUE THREAD

**Issue by jackQian666** [nuxt/nuxt#29075]
### Environment

nodejs: v18.18.0
npm: 9.8.1
"element-plus": "^2.8.3"
"nuxt": "^3.13.2"
"@element-plus/nuxt": "^1.0.10"

### Reproduction

import customPayload from "./plugins/customPayload";

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: '2024-09-18',
  modules: ['@element-plus/nuxt','@pinia/nuxt','@pinia-plugin-persistedstate/nuxt'],

  app:{
    head:{
      charset: 'utf-8',
      viewport: 'width=device-width, initial-scale=1',
      link:[
        {rel:'stylesheet',href:'https://at.alicdn.com/t/c/font_4479554_8o37mnh2iku.css'}
      ],
      script:[
        {type:'text/javascript', src:'https://at.alicdn.com/t/c/font_4479554_094y6wh4x0wv.js'}
      ],
      meta:[]
    },
   
  },

  devtools:{
    enabled:true
  },
 

  nitro:{
      // devProxy:{
      //   '/api':{
      //     target:'http://localhost:7001/api',
      //     changeOrigin:true
      //   }
      // } 
  },

  plugins:[],
  css:['@vuemap/vue-amap/dist/style.css'],

  elementPlus: {
    defaultLocale:'zh-cn',
  },

  vite:{
    css:{
      preprocessorOptions:{
        scss: {
          api: "modern-compiler" // or 'modern'
        }
      }
    }
  }

});

### Describe the bug

![image](https://github.com/user-attachments/assets/de80f66c-5a99-4b34-9f9b-f6fc576737ea)
look at this picture, i had defined a plugin and put it into ~/plugins directory , But still report error

### Additional context

I have read previous issues related to my problem, but still can't solve this error
My initial nuxt version was 3.5, and I upgraded to 3.1.2 a few days ago

**Comment by hi-reeve** [comment]
what is the update on this one? how do you fix it? @jackQian666

**Comment by jackQian666** [comment]
> what is the update on this one? how do you fix it? @jackQian666

just need to defined a customPayloads plugin like the one shown in picture above ine the vscode is fine, thanks @danielroe ,
I checked my code, find the problem is in my code, you should pay attention to the return values of your interface and make good judgments of non empty and undefined, otherwise the server-side rendering stage will report this error
