### ISSUE TITLE
The requested module 'node_modules/dayjs/plugin/weekOfYear.js?v=e2bd8455' doesn't provide an export named: 'default'

### ISSUE THREAD

**Issue by Ahmard** [nuxt/nuxt#29084]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.17.0
- Nuxt Version:     3.13.2
- CLI Version:      3.13.2
- Nitro Version:    2.9.7
- Package Manager:  yarn@1.22.22
- Builder:          -
- User Config:      ssr, devServer, app, plugins, runtimeConfig, modules, antd, eslint, css, imports, postcss, vite, auth, experimental, router, compatibilityDate
- Runtime Modules:  @nuxt/eslint@0.5.7, @nuxt-alt/auth@3.1.7, @ant-design-vue/nuxt@1.4.2, @pinia/nuxt@0.5.4
- Build Modules:    -
------------------------------

### Reproduction

upgrade to Nuxt 3.13.2 by running `npx nuxi@latest upgrade --force`

### Describe the bug

Hey guys, I upgraded to Nuxt 3.13.2 and I kept having below error. I tried reverting back to 3.13.1 and everything continue to works fine, please check.

[nuxt] error caught during app initialization Error: The requested module 'http://localhost:6100/_nuxt/node_modules/dayjs/plugin/weekOfYear.js?v=e2bd8455' doesn't provide an export named: 'default'

### Additional context

![Screenshot from 2024-09-19 23-49-58](https://github.com/user-attachments/assets/0e68b4f8-236a-40b9-aa64-791aaeea883f)

**Comment by yangyixuan** [comment]
[nuxt-antv.zip](https://github.com/user-attachments/files/17072483/nuxt-antv.zip)
类似问题：The requested module '/_nuxt/node_modules/dayjs/plugin/advancedFormat.js?v=eafb9efd' does not provide an export named 'default'

**Comment by MarkCalderon** [comment]
Hope this helps, 
I just tried this code given by [amihhs](https://github.com/amihhs)
https://github.com/nuxt/nuxt/issues/14716#issuecomment-1397364211

By adding this in your nuxt.config.ts
```
alias: {
    'dayjs': 'dayjs/esm/'
  },
```

Personally I used the code below, since the above mentioned will cause an error on yarn build which returns an errors mentioning that it will result in "duplicated modules".
```
alias: {
    'dayjs': 'dayjs'
  },
```
