### ISSUE TITLE
How to define global types in nuxt3? Don't import every file you use?

### ISSUE THREAD

**Issue by bbhxwl** [nuxt/nuxt#29102]
<img width="872" alt="image" src="https://github.com/user-attachments/assets/9e52e707-7a1b-4b94-8356-5cf4e8ac6da7">
<img width="546" alt="image" src="https://github.com/user-attachments/assets/cc064c9f-be68-4d68-9ed6-ddef2cacb210">
<img width="790" alt="image" src="https://github.com/user-attachments/assets/87cb5cc9-d0af-482b-a39b-7315f638cae8">

**Comment by frasza** [comment]
in `nuxt.config.ts` you could define custom dir imports like
```
imports: {
  dirs: ['types'],
},
```
and in that folder have exported types that are globally available

**Comment by bbhxwl** [comment]
> in `nuxt.config.ts` you could define custom dir imports like
> 
> ```
> imports: {
>   dirs: ['types'],
> },
> ```
> 
> and in that folder have exported types that are globally available

How do you know about imports?, I have tested it and it is indeed possible. Each type requires export, but I did not see the documentation in nuxt stating that it can be written like this?

**Comment by bbhxwl** [comment]
> in `nuxt.config.ts` you could define custom dir imports like
> 
> ```
> imports: {
>   dirs: ['types'],
> },
> ```
> 
> and in that folder have exported types that are globally available

As long as there is an export, it can be automatically imported, right?

**Comment by frasza** [comment]
> > in `nuxt.config.ts` you could define custom dir imports like
> > ```
> > imports: {
> >   dirs: ['types'],
> > },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and in that folder have exported types that are globally available
> 
> As long as there is an export, it can be automatically imported, right?

If you want auto import from folder like `types` you have to register it as it is not automatically included.

**Comment by bbhxwl** [comment]
> > > in `nuxt.config.ts` you could define custom dir imports like
> > > ```
> > > imports: {
> > >   dirs: ['types'],
> > > },
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > and in that folder have exported types that are globally available
> > 
> > 
> > As long as there is an export, it can be automatically imported, right?
> 
> If you want auto import from folder like `types` you have to register it as it is not automatically included.

I don't understand the principle of imports, can only automatically import types, or does it include components? Can it be automatically imported with anything else?

**Comment by frasza** [comment]
Nuxt only handles some predefined auto imports like components, pages, utilities and so on (check docs) but you can also define you own autoimports with example I provided above in config file.

**Comment by huang-julien** [comment]
Hello, naming your file global.ts does not make it "global". You still need to add it to the import config 

see: https://nuxt.com/docs/api/nuxt-config#imports
