### ISSUE TITLE
Some strange behavior

### ISSUE THREAD

**Issue by saturn4er** [nuxt/nuxt#29110]
### Environment

Any

### Reproduction

https://stackblitz.com/edit/nuxt-starter-apykxk?file=components%2Fdrawflow.vue

### Describe the bug

#menu-shouldnt-be-here populates with EditorMenu component

**Comment by huang-julien** [comment]
Hello that's because you have invalid html. `<p>` does not accept `<div>` as children.
see https://vuejs.org/guide/scaling-up/ssr.html#hydration-mismatch
