### ISSUE TITLE
Crossorigin attribute not set consistently on CSS link tags

### ISSUE THREAD

**Issue by ptdev** [nuxt/nuxt#29128]
### Environment

Nuxt v3.13.2

### Reproduction

https://stackblitz.com/edit/nuxt-starter-obx8cv?file=README.txt

Open the preview in a new tab.
Open browser devtools, inspect the markup and expand the `<head>` section, then:

1. Click the link to go to test page
   Note that two new `<link>` tags were added, a JS and a CSS, both with crossorigin parameters (correct)

2. Refresh the test page and expand the `<head>` section again.
   Note that now, all `<link>` tags have the crossorigin parameter, except for the CSS file (incorrect imho)

### Describe the bug

When running in production mode, navigating from one page to another that has some component with CSS, will dynamically add `<link>` tags inside the `<head>` with the `crossorigin` attribute set.

But when refreshing the page (i.e: accessing it directly), then the CSS `<link>` tags will not have the `crossorigin` attribute set.

This then causes issues with CDN servers, resource integrity CSP checks, etc.

### Additional context

If Nuxt's config setting `features.inlineStyles` is set to false (not the default), then the CSS files from the config and 404, 500 pages etc (that will now also be a link instead of inlined) also appear to experience this issue and not include the crossorigin parameter

### Logs

I initially posted about this issue on [nuxt-security](https://github.com/Baroshem/nuxt-security/issues/528), but it appears is this will most likely be a Nuxt or maybe Vite issue.

**Comment by vejja** [comment]
+1
Nuxt Security team here. Separate tests confirm that 
- JS static assets always have the `crossorigin`attribute
- CSS static assets do not always have it (unclear when/why)
This causes subresource integrity denial when CSS static asset is deployed on crossorigin. We would need to have `crossorigin` set on all CSS resources

**Comment by vejja** [comment]
Thanks @danielroe for extra-quick fix 💚
