### ISSUE TITLE
Nuxt build shows blank page on latest Chrome

### ISSUE THREAD

**Issue by MickWang** [nuxt/nuxt#29122]
### Environment

- Operating System: Darwin
- Node Version:     v22.4.0
- Nuxt Version:     3.13.2
- CLI Version:      3.13.2
- Nitro Version:    2.9.7
- Package Manager:  npm@10.8.1
- Builder:          -
- User Config:      app, plugins, modules, gtag, ssr, pwa, css, postcss, runtimeConfig, pinia, vite
- Runtime Modules:  @kevinmarrec/nuxt-pwa@0.0.2, @pinia/nuxt@0.4.11, nuxt-gtag@2.0.5
- Build Modules:    -

### Reproduction

github repo: https://github.com/zkLinkProtocol/dapp-portal
Build and serve the assets, the page shows blank on latest Chrome (129.0.6668.59) . No such issue on older version Chrome.
And when enter a wrong route ,it will shows "not found" page normally. 
Everything works fine on the Firefox and safari.

### Describe the bug

 Page shows blank on latest Chrome (129.0.6668.59)
Everything works fine on the Firefox and safari.

**Comment by danielzhang183** [comment]
I'm using this to work around

```ts
import LegacyPlugin from '@vitejs/plugin-legacy'
import TopLevelAwaitPlugin from 'vite-plugin-top-level-await'

vite: {
  plugins: [TopLevelAwaitPlugin(), LegacyPlugin()],
}
```

**Comment by MickWang** [comment]
> I'm using this to work around
> 
> modify `nuxt.config.ts`
> 
> ```ts
> import LegacyPlugin from '@vitejs/plugin-legacy'
> import TopLevelAwaitPlugin from 'vite-plugin-top-level-await'
> 
> vite: {
>   plugins: [TopLevelAwaitPlugin(), LegacyPlugin()],
> }
> ```

not working on my side.

**Comment by danielroe** [comment]
This is a very serious Chrome bug with top-level `await` and isn't a Nuxt issue. You can probably work around it by modifying your code, along the lines of https://github.com/elk-zone/elk/pull/2970.

https://x.com/antfu7/status/1836846357489012816
https://github.com/antfu/repro-chrome-v129

**Comment by MickWang** [comment]
> > I'm using this to work around
> > modify `nuxt.config.ts`
> > ```ts
> > import LegacyPlugin from '@vitejs/plugin-legacy'
> > import TopLevelAwaitPlugin from 'vite-plugin-top-level-await'
> > 
> > vite: {
> >   plugins: [TopLevelAwaitPlugin(), LegacyPlugin()],
> > }
> > ```
> 
> not working on my side.

solved by adding TopLevelAwaitPlugin in nuxt.config.js

**Comment by ra-dave** [comment]
I'm having a similar issue with my first ever Nuxt 3 deployment.  Works fine in dev mode but in production mode I just get blank pages with no errors or anything.  Happens in Firefox too though so may be a different issue.
