### ISSUE TITLE
refreshOnResize alternative

### ISSUE THREAD

**Issue by LeonardoRick** [nuxt/nuxt#29121]
### Describe the feature

[Docs](https://nuxt.com/modules/device#refreshonresize) says

> !WARNING This option is deprecated. It will be removed in the next major release.

How can I track the resize in the future supported way?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
Please raise this in https://github.com/nuxt-modules/device
