### ISSUE TITLE
head manipulation with islands after hydration

### ISSUE THREAD

**Issue by guy-confetti** [nuxt/nuxt#29148]
### Environment

- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.13.2
- CLI Version:      3.13.2
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      compatibilityDate
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-zsncjd-tp8wds

### Describe the bug

Server component loaded after hydration does not manipulate the head as expected.
this works in SSR (see https://github.com/nuxt/nuxt/pull/27987), but not otherwise.

### Additional context

the island payload contains the head data, but is not applied in the client.

**Comment by huang-julien** [comment]
@danielroe we did #27987 for island pages. 
Should island components be able to manipulate head ? We could either only allow islands pages to manipulate head or let island components do it too.
