### ISSUE TITLE
type does not exist in vs code

### ISSUE THREAD

**Issue by sajadhzj** [nuxt/nuxt#29152]
### Environment

- Operating System: Windows_NT
- Node Version:     v22.4.1
- Nuxt Version:     3.13.2
- CLI Version:      3.13.2
- Nitro Version:    2.9.7
- Package Manager:  yarn@1.22.22
- Builder:          -
- User Config:      runtimeConfig, app, css, devtools, modules, glorious, plugins, pwa
- Runtime Modules:  nuxt-glorious@1.1.4, @nuxtjs/tailwindcss@6.12.1, @nuxt/eslint@0.3.13, @nuxt/image@1.8.0, @vite-pwa/nuxt@0.8.1, nuxt-aos@1.2.5, @formkit/auto-animate/nuxt@0.8.2, nuxt-swiper@1.2.2
- Build Modules:    -

### Reproduction

no repo

### Describe the bug

hi , i upgrade nuxt app , then upgrade all function and plugin has error in vs code i use npx nuxi prepare and restart typescript server in vs code but error not fixed , i attached the error how fix this
![Screenshot 2024-09-25 095527](https://github.com/user-attachments/assets/c790da1f-b8ca-4914-b9d0-c883d6ea5318)

**Comment by aiqin-bao** [comment]
我正在使用 utils 文件夹中的常量，这些常量直接自动导入到模板中。但是，我收到以下 TypeScript 错误：
类型“CreateComponentPublicInstance<Readonly<ExtractPropTypes<{}>>, {}, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, ... 12 more ..., {}>”上不存在属性“constant”。

尽管存在此错误，代码在浏览器中仍能正常运行。   utils中定义的常量 自动导入的时候 vsCode中的插件没有设别回提示TS的错误 这应该是插件的问题还是说是nuxt中tsConfig的问题 ？

**Comment by aiqin-bao** [comment]
The problem has been solved. It is a dependency version issue. Check whether node_modules contains declare module "@vue/runtime-core" and update the dependencies in the project.
