### ISSUE TITLE
The cookie from some other request is return 

### ISSUE THREAD

**Issue by binjinbinjinlotus** [nuxt/nuxt#29150]
### Environment

NUXT: 3.6.5
DOCKER: node:18-alpine3.17 

### Reproduction

N/A

### Describe the bug

The cookie from some other requests is returned to the user. That issue happens to the high amount of requests in parallel.

That is a production issue for us; please advise us on how to fix it. 

middleware for the login page
<img width="1022" alt="image" src="https://github.com/user-attachments/assets/921d42cb-bb02-444b-a042-f93780ded274">
<img width="1097" alt="image" src="https://github.com/user-attachments/assets/02cc4b09-a16f-4a44-a83a-ec52d15734b1">
<img width="1112" alt="image" src="https://github.com/user-attachments/assets/e4c7d0ca-3fe9-4756-b9f4-c9f272d2aa2b">
<img width="978" alt="image" src="https://github.com/user-attachments/assets/d1508def-1b9d-4872-88b1-1db8209918d3">
<img width="1099" alt="image" src="https://github.com/user-attachments/assets/9dcece42-f87d-406d-bb5d-853bc2b48a7e">

Logs for the response cookie have been swapped
[59b49245-copy.txt](https://github.com/user-attachments/files/17122007/59b49245-copy.txt)
[0b186e39-copy.txt](https://github.com/user-attachments/files/17122008/0b186e39-copy.txt)

**Comment by binjinbinjinlotus** [comment]
I am unable to provide the code because it is our production code. 

I have attached the logs to the description for the code snippet that is attached in the description. 

Based on the logs, my assumption is the incorrect nuxt context is used in different places. 

For example, in log file "59b49245-copy.txt"

We get the 'uuid'  5151eca5-13e9-4dba-b89f-8f81396dd29a from the cookie.

<img width="796" alt="image" src="https://github.com/user-attachments/assets/32d147d3-bb6a-4ee6-9128-18b8459335c9">

"SWAP TEST::PROCESS: 59b49245-fde0-4e21-93b9-87b3879b9643 /n LOG::START_COOKIE_UUID_1: 5151eca5-13e9-4dba-b89f-8f81396dd29a"


Then we get 'uuid' d1bc5697-6e6a-4c50-a270-8c588749da7c from the cookie 
<img width="791" alt="image" src="https://github.com/user-attachments/assets/e92e0991-c0f6-48c7-a6e4-2f66ac921bfd">
SWAP TEST::PROCESS: 59b49245-fde0-4e21-93b9-87b3879b9643 /n LOG::SAVE_AUTH_DATA_FINAL_COOKIE_UUID: d1bc5697-6e6a-4c50-a270-8c588749da7c

Base on the source code of NUXT3.6.5 /app/composables/cookie
The cookie directly comes from the request header within the request context. From the log, I can see different values of the uuid is coming from the cookie. Which means different nuxt context is used. 
<img width="728" alt="image" src="https://github.com/user-attachments/assets/053ca399-d638-4958-8d9d-ec90532743b6">

**Comment by danielroe** [comment]
You should call composables at the top level of your plugin, not inside a method within it. If you must do so, use nuxtApp.runWithContext.

https://nuxt.com/docs/api/composables/use-nuxt-app#runwithcontext
