### ISSUE TITLE
‘useRuntimeConfig’ weird behavior

### ISSUE THREAD

**Issue by CorrM** [nuxt/nuxt#29158]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v22.9.0
- Nuxt Version:     3.13.2
- CLI Version:      3.13.2
- Nitro Version:    2.9.7
- Package Manager:  bun@1.1.24
- Builder:          -
- User Config:      compatibilityDate, devtools, srcDir, ssr, app, typescript, nitro, runtimeConfig, modules, eslint, i18n, security, tailwindcss
- Runtime Modules:  @nuxt/eslint@0.5.7, @nuxtjs/i18n@8.5.5, @nuxtjs/tailwindcss@6.12.1, nuxt-auth-utils@0.3.9, nuxt-mikro-orm-module@0.4.1, @nuxt/icon@1.5.1, @vueuse/nuxt@11.1.0
- Build Modules:    -
------------------------------

### Reproduction

```
// .env
NUXT_DB_PORT="5433"
NUXT_DB_PASSWORD="123456789"

// nuxt.config.ts
runtimeConfig: {
        dbPort: process.env["NUXT_DB_PORT"],
        dbPassword: process.env["NUXT_DB_PASSWORD"],
    },
```

```ts
// server/plugins/db.ts
const config: RuntimeConfig = useRuntimeConfig();

console.log("dbPort", typeof config.dbPort); // number
console.log("dbPassword", typeof config.dbPassword); // number
```

but in generated `RuntimeConfig` interface they are string!!
```ts
interface RuntimeConfig {
   dbPort: string,
   dbPassword: string,
}
```

### Describe the bug

`typeof config.dbPort` and `typeof config.dbPassword` return `number`!

**Comment by ndragun92** [comment]
@CorrM Hope it helps

![image](https://github.com/user-attachments/assets/d3b0155e-d16a-455c-bfa0-442589120eb2)

**Comment by CorrM** [comment]
If generated type is `string` then i dont think that the expected behavior for me.
why types are not generated correct.

should i get raid of using runtime config and replace it with `process.env`?
