### ISSUE TITLE
Recent changes cause issues with client side Vue libraries using refs in composables

### ISSUE THREAD

**Issue by nevil2** [nuxt/nuxt#29161]
### Environment

- Operating System: Linux
- Node Version:     v20.10.0
- Nuxt Version:     3.13.2
- CLI Version:      3.13.2
- Nitro Version:    2.9.7
- Package Manager:  npm@10.8.3
- Builder:          -
- User Config:      ssr, css, app, build, modules, nitro, runtimeConfig, serverHandlers, vite, devtools, postcss, compatibilityDate
- Runtime Modules:  @pinia/nuxt@0.5.4, @nuxt/eslint@0.5.7
- Build Modules:    -

### Reproduction

The private Vue library:
- works fine when used in a Vue SPA application, e.g. [https://topoeditor.com](https://topoeditor.com)
- works fine when used as a web component in a non Vue application, e.g. https://climbers-club.co.uk/climbing/submission
- no longer works when used in a Nuxt application (non-public) with SSR set as false.

### Describe the bug

The component loaded from the library works the first time the component is mounted, but on remounting the component, the refs and computed refs within composables in the library do not update correctly resulting in undesirable behaviour.

This may be intended Nuxt behaviour (as Nuxt does not support refs in composables for SSR), but making Nuxt incompatible with client-side Vue libraries is surely undesirable (and ultimately will result in my migrating away from Nuxt).

### Additional context

The TopoEditor library has:
 ~ 30 composables containing ~100 refs and similar number of computed refs
 ~ 30 components which use values from the composables (saves complex web of props)

**Comment by ndragun92** [comment]
If you are using library that only works on client side and doesnt support SSR yet why dont u load it as .client.vue file instead?
Would the same issue still appear?

**Comment by CommanderStorm** [comment]
> How do I load as `.client.vue`

define a page as [client only](https://nuxt.com/docs/guide/directory-structure/components#client-components) by giving it a 
´.client.vue´ suffix. None of the content of this page will be rendered on the server.

https://nuxt.com/docs/guide/directory-structure/pages#client-only-pages

**Comment by nevil2** [comment]
Thanks, but changing to .client.vue does not fix the issue.  I already have global setting `SSR: false`.

**Comment by danielroe** [comment]
Could this be related to Vue 3.5+? I'd appreciate a minimal reproduction - otherwise it will be almost impossible to investigate.

None of the behaviour you described is expected, FWIW.

**Comment by nevil2** [comment]
Thanks for looking at this Daniel.

Running Vue 3.5.8, but it works as independent Vue application - just not in Nuxt.

I do not have enough time to create a minimal reproduction before going to Nepal on Tuesday.  I am back on 29th October and can try to do that then.  Is that OK?

In mean time, I've moved a those refs founding not to be updating (on second load) from composables to components in the TopoEditor library.  This fixes known problems for my users, but there may be other situations were a ref still in a composable causes a problem.

**Comment by nevil2** [comment]
topo-editor is only once in package-lock.json
Library is ESM: `"type": "module"` and and loaded `import { DbEditor } from 'topo-editor'`

**Comment by danielroe** [comment]
Multiple versions of Vue, I mean.

**Comment by nevil2** [comment]
Only one version of Vue.

**Comment by danielroe** [comment]
Closing as there is no reproduction to investigate. Let me know if you can provide one and I'll happily reopen 🙏
