### ISSUE TITLE
feat: include ‘types’ in./.nuxt/tsconfig.json

### ISSUE THREAD

**Issue by trydofor** [nuxt/nuxt#29171]
### Describe the feature

because of this tsc error when using [layers](https://nuxt.com/docs/getting-started/layers) in monorepo.

>  ERROR(vue-tsc)  Cannot find module '~/assets/img/1x/home.png' or its corresponding type declarations.

after searching, i get 2 solutions to fix the type error. `@local/common` is a mono project.

opt1: consumer `front` override tsconfig.json

```diff
{
  "extends": "./.nuxt/tsconfig.json",
+  "include": [
+   "./.nuxt/tsconfig.json",
+   "@local/common/types/*.d.ts"
+ ],
}
```

opt2: provider `common` export types in package.json, and move `declare module '*.png'` to index.d.ts

```diff
{
  "name": "@local/common",
+ "types": "index.d.ts",
```

is there a better way to  reuse the `*.d.ts` globally, in `layers` or `devDependencies`, rather than copying the declaration here and there?

for now, i am thinking if Nuxt can auto import the`*.d.ts` in the some folder, e.g. `types` or `utils/types`.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
have you tried adding to typescript.tsConfig in your nuxt config?

**Comment by trydofor** [comment]
> have you tried adding to typescript.tsConfig in your nuxt config?

no `tsConfig` set, just a simple `typeCheck`, following the [doc](https://nuxt.com/docs/guide/concepts/typescript)

after adding `types/` to `include` of tsConfig, it works,
and auto add to `.nuxt/tsconfig.json` as well.

```diff
export default defineNuxtConfig({
  typescript: {
    typeCheck: true,
+   tsConfig: {
+     include: ['./types/*.d.ts'],
+   },
  },
});
```

thanks @danielroe
