### ISSUE TITLE
Usefetch has a serious bug, why does it delay receiving return messages?

### ISSUE THREAD

**Issue by bbhxwl** [nuxt/nuxt#29189]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.17.0
- Nuxt Version:     3.13.2
- CLI Version:      3.13.2
- Nitro Version:    2.9.7
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, devServer, css, extends, modules, runtimeConfig, compatibilityDate, hooks, components   
- Runtime Modules:  @nuxt/ui@2.18.4, @pinia/nuxt@0.5.4, @pi
nia-plugin-persistedstate/nuxt@1.2.1, dayjs-nuxt@2.1.11, @n
uxtjs/device@3.2.3, @nuxtjs/color-mode@3.5.1, @nuxtjs/tailwindcss@6.12.1, @vant/nuxt@1.0.6, @vueuse/nuxt@11.1.0       
- Build Modules:    -
------------------------------

### Reproduction

The returned data Code=0, but his judgment does not hold, it seems that the correct data will only be returned after judgment. I directly output the returned data, which is undefined.

### Describe the bug

Usefetch has a serious bug, why does it delay receiving return messages?
The returned data Code=0, but his judgment does not hold, it seems that the correct data will only be returned after judgment. I directly output the returned data, which is undefined.

![image](https://github.com/user-attachments/assets/2e3fd45a-1dbb-4996-bcc3-fcfd4e98860a)

**Comment by BoBo-Git** [comment]
> ### Environment
> * Operating System: Windows_NT
> * Node Version:     v20.17.0
> * Nuxt Version:     3.13.2
> * CLI Version:      3.13.2
> * Nitro Version:    2.9.7
> * Package Manager:  yarn@1.22.19
> * Builder:          -
> * User Config:      devtools, devServer, css, extends, modules, runtimeConfig, compatibilityDate, hooks, components
> * Runtime Modules:  @nuxt/ui@2.18.4, @pinia/nuxt@0.5.4, @pi
>   nia-plugin-persistedstate/nuxt@1.2.1, dayjs-nuxt@2.1.11, @n
>   uxtjs/device@3.2.3, @nuxtjs/color-mode@3.5.1, @nuxtjs/tailwindcss@6.12.1, @vant/nuxt@1.0.6, @vueuse/nuxt@11.1.0
> * Build Modules:    -
> 
> ### Reproduction
> The returned data Code=0, but his judgment does not hold, it seems that the correct data will only be returned after judgment. I directly output the returned data, which is undefined.
> 
> ### Describe the bug
> Usefetch has a serious bug, why does it delay receiving return messages? The returned data Code=0, but his judgment does not hold, it seems that the correct data will only be returned after judgment. I directly output the returned data, which is undefined.
> 
> ![image](https://private-user-images.githubusercontent.com/26525599/371374835-2e3fd45a-1dbb-4996-bcc3-fcfd4e98860a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MjcxMDcsIm5iZiI6MTcyNzQyNjgwNywicGF0aCI6Ii8yNjUyNTU5OS8zNzEzNzQ4MzUtMmUzZmQ0NWEtMWRiYi00OTk2LWJjYzMtZmNmZDRlOTg4NjBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDA4NDY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiZjI2Yzk0MWJmMzc0MWRlNTQwYzkyMjczNDlkNDk0NmM2ODczZmIzMzFkZDVlOWJmNGM0YWUzYjViNzlmN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0lr_alXmif2Xmq0kAryMAqBsCe3JrH3AhSK4Pz2CQ_Y)
> 
> ### Additional context
> _No response_
> 
> ### Logs
> _No response_

It looks like your request was encapsulated. I'm not sure of the context of your request for encapsulation, but I guess you can get `data`, `error`, `execute`, `refresh`, `status` in your `res`, like this:

```javascript
http.post('your_url', body: {})
  .then((res) => {
  const { data, error, execute, refresh, status } = res
  execute().then(() => {
    if (data.value.Code === 0) {
       // your logic here
     }
  })
})
```

**Comment by bbhxwl** [comment]
> > ### Environment
> > 
> > * Operating System: Windows_NT
> > * Node Version:     v20.17.0
> > * Nuxt Version:     3.13.2
> > * CLI Version:      3.13.2
> > * Nitro Version:    2.9.7
> > * Package Manager:  yarn@1.22.19
> > * Builder:          -
> > * User Config:      devtools, devServer, css, extends, modules, runtimeConfig, compatibilityDate, hooks, components
> > * Runtime Modules:  @nuxt/ui@2.18.4, @pinia/nuxt@0.5.4, @pi
> >   nia-plugin-persistedstate/nuxt@1.2.1, dayjs-nuxt@2.1.11, @n
> >   uxtjs/device@3.2.3, @nuxtjs/color-mode@3.5.1, @nuxtjs/tailwindcss@6.12.1, @vant/nuxt@1.0.6, @vueuse/nuxt@11.1.0
> > * Build Modules:    -
> > 
> > ### Reproduction
> > The returned data Code=0, but his judgment does not hold, it seems that the correct data will only be returned after judgment. I directly output the returned data, which is undefined.
> > ### Describe the bug
> > Usefetch has a serious bug, why does it delay receiving return messages? The returned data Code=0, but his judgment does not hold, it seems that the correct data will only be returned after judgment. I directly output the returned data, which is undefined.
> > ![image](https://private-user-images.githubusercontent.com/26525599/371374835-2e3fd45a-1dbb-4996-bcc3-fcfd4e98860a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MjcxMDcsIm5iZiI6MTcyNzQyNjgwNywicGF0aCI6Ii8yNjUyNTU5OS8zNzEzNzQ4MzUtMmUzZmQ0NWEtMWRiYi00OTk2LWJjYzMtZmNmZDRlOTg4NjBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDA4NDY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiZjI2Yzk0MWJmMzc0MWRlNTQwYzkyMjczNDlkNDk0NmM2ODczZmIzMzFkZDVlOWJmNGM0YWUzYjViNzlmN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0lr_alXmif2Xmq0kAryMAqBsCe3JrH3AhSK4Pz2CQ_Y)
> > ### Additional context
> > _No response_
> > ### Logs
> > _No response_
> 
> It looks like your request was encapsulated. I'm not sure of the context of your request for encapsulation, but I guess you can get `data`, `error`, `execute`, `refresh`, `status` in your `res`, like this:
> 
> ```js
> http.post('your_url', body: {})
>   .then((res) => {
>   const { data, error, execute, refresh, status } = res
>   execute().then(() => {
>     if (data.value.Code === 0) {
>        // your logic here
>      }
>   })
> })
> ```

Although it has been encapsulated, it contains only useFetch without any special code, except for the addition of a token. It's strange, the new version has bugs. I can only skip using SSR now, I have set SSR to false.

**Comment by warflash** [comment]
We'd need a reproduction as just the snippet you shared isn't enough to give much advice unfortunately

**Comment by bbhxwl** [comment]
> We'd need a reproduction as just the snippet you shared isn't enough to give much advice unfortunately

import type {UseFetchOptions} from "#app";
import type {Ref} from "vue";
import {type FetchOptions, type SearchParameters} from "ofetch";
import type {CommonResponse} from "~/types/CommonResponse";
import type {CommonResponseGetList} from "~/types/CommonResponseGetList";


const request = async <T = any>(url: any, options: any) => {
    let token = useCookie("newManageToken")
    const config = useRuntimeConfig();
    options.baseURL="/api/webApi/"
    let customHeaders: { "Content-Type": string, Authorization?: string } = {"Content-Type": "application/json"}
    const res=await useFetch<T>(url, {headers: customHeaders,...options})
    if(import.meta.client){
        if(res.error&&res.error.value){
            ElNotification({
                title: '系统错误提示',
                message: res.error.value.message,
                type: 'error',
                appendTo: document.body,
                zIndex: 9999
            })
        }
        else if (res.data.value&&(res.data.value as any).Msg) {
            if((res.data.value as any).Code===0){
                ElNotification({
                    title: '系统提示',
                    message: (res.data.value as any).Msg,
                    type: 'success',
                    appendTo: document.body,
                    zIndex: 9999
                })
            }
            else{
                ElNotification({
                    title: '错误提示',
                    message: (res.data.value as any).Msg,
                    type: 'error',
                    appendTo: document.body,
                    zIndex: 9999
                })
            }
        }
    }

    return res
};

type ResponseType<T = any> = T extends undefined ? CommonResponse<any> : CommonResponse<T>;

export const http = {
    get: <T = any>(url: Ref<string>|string, query?: SearchParameters, opts?: UseFetchOptions<T>) => {
        return request<T>(url, {...opts,...{method: 'GET', query}});
    },
    post: <T = undefined>(url: Ref<string>|string, body?: RequestInit["body"] | Record<string, any>, opts?: UseFetchOptions<ResponseType<T>>) => {
        return request<ResponseType<T>>(url, {...opts,...{method: 'POST', body}});
    }
}

**Comment by danielroe** [comment]
useFetch is a composable and shouldn't be used to perform programmatic fetching. 

for example, if data was not fetched on the server, it will wait until a component is mounted to avoid hydration mismatches.

instead, just use $fetch.

**Comment by bbhxwl** [comment]
> useFetch is a composable and shouldn't be used to perform programmatic fetching.
> 
> for example, if data was not fetched on the server, it will wait until a component is mounted to avoid hydration mismatches.
> 
> instead, just use $fetch.

Calling the request at the top, isn't it on the server?
