### ISSUE TITLE
useAsyncData | Dedupe requests on the the server and client (by caching the promises)

### ISSUE THREAD

**Issue by RodrigoProjects** [nuxt/nuxt#29196]
### Describe the feature

Currently when we have two components in the same page with something like this: 

```js
// Let's assume asyncFunction is a fetch request that works.

// component1.vue
const { data: data1 } = await useLazyAsyncData('bananas', asyncFunction)

// component2.vue
const { data: data2 } = await useLazyAsyncData('bananas', asyncFunction)
```
2 requests are fired instead of any other better alternative like the dedupe `defer` or `cancel`. This might be a bug or some bad interpretation but in my reproduction (https://stackblitz.com/edit/github-dcn4nk?file=components%2FFetchCatInfo.vue,app.vue) that's the behaviour I get.

There are solutions in the user land like Vue Query but I think this should work in the core framework too! :)

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
This behavior should be correct. The initial request (while running) is cancelled and the new one is initiated. If you want to re use the first one, use `'defer'` as value.

<img width="761" alt="image" src="https://github.com/user-attachments/assets/f2726d2a-6f4b-43bd-ad2b-e00a24c3ccd0">

First 2 are with `cancel`, then 1 with `defer`


```vue
<script setup>
function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

const { data } = await useLazyAsyncData(
  'bananas',
  async () => {
    await sleep(1000);
    const response = await fetch('https://catfact.ninja/fact');
    console.log('request fired') //<- ADDED HERE
    return response.json();
  },
  { dedupe: 'defer' }
);
</script>

<template>{{ data }} <br /></template>
```
