### ISSUE TITLE
Input v-model reset to default value after all browser resources loaded

### ISSUE THREAD

**Issue by anton-chernianu** [nuxt/nuxt#29206]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.9.0
- Nuxt Version:     3.13.2
- CLI Version:      3.14.0
- Nitro Version:    2.9.7
- Package Manager:  yarn@1.22.22
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/github/anton-chernianu/nuxt3-issue?file=app.vue

### Describe the bug

- user loads a page with a slow internet connection
- starts entering some values ​​into the input with v-model
- after all browser resources loaded - input v-model reset to default value

https://github.com/user-attachments/assets/04c31cfc-6c27-409c-8070-47470df0d9d6

**Comment by danielroe** [comment]
this is pure vue hydration behaviour

Would you see if you can reproduce this in pure Vue SSR without Nuxt ([reproduction sandbox](https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter)), and if so, raise [there](https://github.com/vuejs/core/issues/new/choose)? 🙏

**Comment by awacode21** [comment]
@anton-chernianu we are dealing with the same problem. Did you opened a bug on vue? can you reference it here? Did you find a way to fix it?
