### ISSUE TITLE
Utilizing sass-embedded alongside Vite's css + scss modern-compiler and nuxt generate produces an "empty error" and runs forever

### ISSUE THREAD

**Issue by adamdehaven** [nuxt/nuxt#29207]
### Environment

- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.13.2
- CLI Version:      3.14.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-ucmpnb

Run `npm run generate` in the terminal

### Describe the bug

When configuring Vite to utilize Sass's modern compiler alongside `sass-embedded` as recommended by the [Vite docs](https://vitejs.dev/config/shared-options.html#css-preprocessoroptions), running the `generate` command while utilizing the `cloudflare-pages-static` build preset results in an error:

```
transforming (27) node_modules/nuxt/dist/app/nuxt.jsWarning: Failed to detect linux-musl, fallback to linux-gnu: failed to read fd 30
transforming (70) node_modules/nuxt/dist/app/components/client-only.jsome/projects/github-ucmpnb/node_modules/sass-embedded-linux-x64/dart-sass/src/dart: line 1: a command can only contain words and redirects
[8:36:49 PM]  ERROR  x Build failed in 2.06s
[8:36:49 PM]  ERROR  Nuxt Build Error: Unexpected early exit. This happens when Promises returned by plugins cannot resolve. Unfinished hook action(s) on exit:
(vite:css) transform "/home/projects/github-ucmpnb/app.vue?vue&type=style&index=0&scoped=c3ca6520&lang.scss"
```

- When building on Cloudflare Pages, the build process simply hangs and does not exit until it times out or is cancelled
- In the [linked reproduction](https://stackblitz.com/edit/github-ucmpnb), simply run `npm run generate` and notice the error message in the console (screenshot below)

<img width="577" alt="error" src="https://github.com/user-attachments/assets/0951db85-e72c-4df0-9254-c4a9facaa810">

**Comment by adamdehaven** [comment]
Running `npx nuxi@latest upgrade --force` afterwards resolved; disregard as I can't reproduce consistently

**Comment by jeremyVignelles** [comment]
I have the issue on stackblitz, seems like it's the culprit. Did you report the bug there ? If so, do you have a link ?
I have also found this : https://github.com/vitejs/vite/issues/19968 but no issue yet on webcontainer-core

**Comment by Doogiemuc** [comment]
Same here:  See https://github.com/stackblitz/webcontainer-core/issues/1926

**Comment by jeremyVignelles** [comment]
@Doogiemuc : Since then, I've got an answer and forgot to post here.
See this post: https://github.com/quasarframework/quasar/pull/17522#issuecomment-3007589544
They have a workaround in place. Hope it helps :)

**Comment by serious-angel** [comment]
> [quasarframework/quasar#17522 (comment)](https://github.com/quasarframework/quasar/pull/17522#issuecomment-3007589544) They have a workaround in place.  

@jeremyVignelles , thank you, but it seems like the possible solution didn't resolve it: <https://stackblitz.com/edit/vitejs-vite-5fjohrmm>  

In the result, the main entrypoint script is not loaded, too.  
Did you have a similar setup with just Vite, as in the example, or Nuxt only?  

---

<img width="754" height="234" alt="Image" src="https://github.com/user-attachments/assets/d88bbdd1-1110-4932-80f1-ac49716ba391" />

**Comment by jeremyVignelles** [comment]
Sorry for the delay. It's been a while so my memory isn't as clear.
I remember having the same error message as this post, and that it was gone after the workaround.
I was using a quasar front-end app.
A lot has probably changed since then, I hope you found a workaround.
