### ISSUE TITLE
Markdown Vue Components

### ISSUE THREAD

**Issue by neneodonkor** [nuxt/nuxt#29210]
### Environment

Nuxt project info:                                                                                                          2:39:45 AM

------------------------------
- Operating System: Windows_NT
- Node Version:     v22.9.0
- Nuxt Version:     3.13.2
- CLI Version:      3.13.2
- Nitro Version:    2.9.7
- Package Manager:  npm@8.12.1
- Builder:          -
- User Config:      compatibilityDate, future, devtools, experimental, unhead, modules
- Runtime Modules:  @nuxt/image@1.8.0, @nuxt/content@2.13.2
- Build Modules:    -
------------------------------

### Reproduction

It's basically an issue of folder structure. 

### Describe the bug

 In Nuxt v3, we were to place Markdown Vue Components in the components/content folder. I switched to Nuxt v4, and it seems Nuxt is not able to load the component. I presume there is a different structure for that. Does any one know the new folder for Markdown Vue Components?

![image](https://github.com/user-attachments/assets/557c3e21-9268-4fc6-9215-6db47d329888)

**Comment by danielroe** [comment]
this seems likely to be an upstream bug in nuxt content. would you raise an issue there?

**Comment by neneodonkor** [comment]
> this seems likely to be an upstream bug in nuxt content. would you raise an issue there?

Okay I will do that.

**Comment by manniL** [comment]
Closing here so we can track in https://github.com/nuxt/content/issues/2800
