### ISSUE TITLE
definePageMeta not working

### ISSUE THREAD

**Issue by Pentadome** [nuxt/nuxt#29243]
### Environment

perating System: Windows_NT
- Node Version:     v22.6.0
- Nuxt Version:     3.13.2
- CLI Version:      3.13.2
- Nitro Version:    2.9.7
- Package Manager:  npm@10.8.1
- Builder:          -
- User Config:      compatibilityDate, ssr, devtools, experimental, css, components, postcss, modules, vite, vue, hooks, $development
- Runtime Modules:  @pinia/nuxt@0.5.4
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-fcje39?file=pages%2Findex.vue,nuxt.config.ts,app.vue

### Describe the bug

Both in the hook 'pages:extend` and in route middlewares is the meta object empty.

**Comment by xjccc** [comment]
`pages:extend` to add `meta`, and accessed meta in `middleware`

https://stackblitz.com/edit/github-fcje39-2t3joe?file=pages%2Findex.vue,middleware%2Froute.ts,nuxt.config.ts

**Comment by danielroe** [comment]
`pages:extend` only extracts certain key properties from `definePageMeta` but in the next release (v3.15), it will be possible to define `experimental.extraPageMetaExtractionKeys` via https://github.com/nuxt/nuxt/pull/30015.
