### ISSUE TITLE
Add option to turn off nuxt layers auto-registration

### ISSUE THREAD

**Issue by sshiling** [nuxt/nuxt#29242]
### Describe the feature

I am building the white-label solution and going to use Nuxt layers to manage app tenants. 
From the [documentation](https://nuxt.com/docs/getting-started/layers#usage) all layers are auto-registered. But I didn't find a way to turn off auto-registration. 

I want a different run command for different tenants, including only common + tenant-specific features but nothing from layers for other tenants. What is the best way to do it?

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by sshiling** [comment]
Resolve my question extending tenant nuxt config in the main nuxt.config but not main in the tenant.

**Comment by Anoesj** [comment]
Hi @sshiling, I didn't understand your last comment and I'm curious how you solved this problem. If you could explain a little more or make a StackBlitz example, that would be much appreciated! Maybe you'd help others running into this as well.

**Comment by sshiling** [comment]
@Anoesj sorry for the delayed response. I've just got back to this closed issue.

Here is the approach:
1. Put your layers into some directory (but not layers). 
2. Use ENV var (or any other logic you like) to define which layout to include. 

In my case I have an option in the `nuxt.config.ts`:
```
extends: process.env.NUXT_PUBLIC_TENANT
    ? [resolve(__dirname, `tenants/${process.env.NUXT_PUBLIC_TENANT}`)]
    : [],
```

**Comment by Anoesj** [comment]
Thanks @sshiling! I actually landed on this exact solution as well in an application I'm working on right now 😄
