### ISSUE TITLE
Google Chrome white blank page after deploying nuxt3 app

### ISSUE THREAD

**Issue by hoSaMShoukry** [nuxt/nuxt#29257]
### Environment

nuxt js 3 blank white page after deploying just in  chrome and edge browsers

### Reproduction

https://github.com/hoSaMShoukry/nuxt-router.aoptions-issue

### Describe the bug

when i deploy my nuxt3 app i just get blank white page without any errors in the console but when i remove router.options.ts from app folder the site work just in home page ofc without any routes (this issue happen just in chrome  and edge browsers)

**Comment by danielroe** [comment]
that reproduction link does not work
