### ISSUE TITLE
illegal character U+0040

### ISSUE THREAD

**Issue by CorrM** [nuxt/nuxt#29279]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v22.9.0
- Nuxt Version:     3.13.2
- CLI Version:      3.13.2
- Nitro Version:    2.9.7
- Package Manager:  bun@1.1.24
- Builder:          -
- User Config:      compatibilityDate, devtools, srcDir, ssr, typescript, modules, eslint, i18n, security, tailwindcss, app, vite, hooks, nitro, routeRules, runtimeConfig
- Runtime Modules:  @nuxt/eslint@0.5.7, @nuxtjs/i18n@8.5.5, @nuxtjs/tailwindcss@6.12.1, nuxt-auth-utils@0.4.2, nuxt-mikro-orm-module@0.4.1, @nuxt/icon@1.5.2, @vueuse/nuxt@11.1.0
- Build Modules:    -
------------------------------

### Reproduction

```ts
enum UserRole {
    ADMIN = "admin",
    MODERATOR = "moderator",
    SUPPORT = "support",
    USER = "user",
}

// users.vue
<script lang="ts" setup>
function getUserRoleCssClass(role: UserRole): string {
    switch (role) {
        case UserRole.ADMIN:
        case UserRole.MODERATOR:
            return "bg-error/10 text-error";
        case UserRole.SUPPORT:
            return "bg-warning/10 text-warning";
        case UserRole.USER:
        default:
            return "bg-info/10 text-info";
    }
}
</script>

<template>
<div :class="getUserRoleCssClass(userInfo.user.role)">
  {{ userInfo.user.role }}
</div>
</template>
```

### Describe the bug

That code throws this error `illegal character U+0040`
![Image](https://github.com/user-attachments/assets/e4b13cc9-1233-40a9-af4a-8c1518f4f0dd)

I know its not the best way to bind to `class` but i already tested `Binding to Objects` and `Binding to Arrays` syntax from [here](https://vuejs.org/guide/essentials/class-and-style)

the only change needed to workaround this issue is change the function to use string instead of enum items:
```ts
function getUserRoleCssClass(role: UserRole): string {
    switch (role) {
        case "admin":
        case "moderator":
            return "bg-error/10 text-error";
        case "support":
            return "bg-warning/10 text-warning";
        case "user":
        default:
            return "bg-info/10 text-info";
    }
}
```

also to make sure its not my code issue i used `console.log(typeof role)` and returns `string` which is correct.

**Comment by CorrM** [comment]
Here you go https://stackblitz.com/edit/github-a3cz37-zk17n9?file=app.vue
But for some reason doesn't give the same error

Mostly related to #14126

**Comment by danielroe** [comment]
You should not be importing code from your `~/server` directory in the Vue part of your app. Also, you should not add a separate plugin for typescript support in the nitro rollup config. (it's also not necessary in your repro)

However, as you are doing so in your example, you need to enable experimental decorator support for vite.

Once fixed, it works fine.

https://stackblitz.com/edit/github-a3cz37-ohzrf7?file=nuxt.config.ts

**Comment by CorrM** [comment]
> You should not be importing code from your `~/server` directory in the Vue part of your app
It was just fast example, i use `~/type` directory for that.

> you should not add a separate plugin for typescript support in the nitro rollup config. (it's also not necessary in your repro)
Got that error when get raid of rollup plugin (Even after vite `experimental decorator`):
```
Please provide either 'type' or 'entity' attribute in Settings.id. If you are using decorators, ensure you have 'emitDecoratorMetadata' enabled in your tsconfig.json.

  at ReflectMetadataProvider.initPropertyType (node_modules/@mikro-orm/core/metadata/ReflectMetadataProvider.js:30:19)
  at ReflectMetadataProvider.initProperties (node_modules/@mikro-orm/core/metadata/ReflectMetadataProvider.js:23:22)
  at ReflectMetadataProvider.loadEntityMetadata (node_modules/@mikro-orm/core/metadata/ReflectMetadataProvider.js:10:14)
  at MetadataDiscovery.discoverEntity (node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:294:31)
  at MetadataDiscovery.discoverReferences (node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:241:18)
  at MetadataDiscovery.findEntities (node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:147:14)
  at MetadataDiscovery.discover (node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:43:20)
  at MikroORM.discoverEntities (node_modules/@mikro-orm/core/MikroORM.js:172:46)
  at MikroORM.init (node_modules/@mikro-orm/core/MikroORM.js:44:19)
  at async initOrm (node_modules/nuxt-mikro-orm-module/dist/runtime/server/utils/orm.js:22:15)
```
That means it can't get the type of `id` field.

Here is my settings class:
```ts
import { Entity, PrimaryKey, Property } from "@mikro-orm/core";

@Entity({ tableName: "settings" })
export class Settings {
    @PrimaryKey({ autoincrement: true })
    public readonly id!: number;

    @Property()
    public userStartingBalance: number;
}
```

**Comment by CorrM** [comment]
@danielroe

**Comment by danielroe** [comment]
would you update the reproduction then?

the one i provided works fine

**Comment by mlhaufe** [comment]
@CorrM  from your last error it looks like the issue is related to your `mikro-orm.config` settings.

I'm guessing you'll want to use: `metadataProvider: TsMorphMetadataProvider`

In my nuxt.config I use the following:

![Image](https://github.com/user-attachments/assets/8b535820-c883-4b34-887e-8b7b303c3bbd)

which is the same as my tsconfig.json:

![Image](https://github.com/user-attachments/assets/b309ebf5-58d4-4685-8b1d-14900b6d079e)

With those settings and @danielroe's suggested changes I am able to build an application successfully with class decorators and the  `@mikro-orm` library

**Comment by CorrM** [comment]
Thanks for your interest, the problem was the file that hold that enum are importing some types that should not be in front-end code(from mikro-orm)
