### ISSUE TITLE
Project performance slowdown when running - Potential Optimization Needed

### ISSUE THREAD

**Issue by ElvinKyungu** [nuxt/nuxt#29278]
### Version
- Nuxt: 3.13.2

### Reproduction
- When running the project (`npm run dev` or `yarn dev`), the app feels slow and unresponsive, especially during development.
- No significant custom configurations have been added that could cause such slowdowns.
- I have tried different environments and machines, but the issue persists.

### Expected Behavior
- The project should run smoothly without noticeable performance drops when starting or navigating between pages.

### Current Behavior
- The app experiences sluggishness, especially during hot reloads and navigation.
- This is impacting the overall development experience, as it takes more time to perform even simple tasks.

### Steps to Reproduce
1. Set up a fresh Nuxt project with default settings.
2. Start the development server using `npm run dev` or `yarn dev`.
3. Navigate through pages and make small changes to observe performance issues.

### Possible Solution
- If there are areas for optimization in how the development server handles builds, caching, or hot reloads, these could be improved.
- A suggestion would be to look into optimizing the Webpack configuration, memory usage, or any performance bottlenecks.

### Additional Context
- Operating system: Linux (Ubuntu 22.4)

Thank you for your attention to this issue.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [x] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [x] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by shindodkar** [comment]
I face the same issue

**Comment by ElvinKyungu** [comment]
Tomorrow I do @danielroe

**Comment by danielroe** [comment]
Closing as there's no reproduction to investigate, but please feel free to provide one and I'll happily reopen. 🙏
