### ISSUE TITLE
Using layout on error page causes error info to not appear

### ISSUE THREAD

**Issue by kamran-12** [nuxt/nuxt#29284]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.17.0`
- Nuxt Version:     `3.13.2`
- CLI Version:      `3.14.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `npm@10.8.2`
- Builder:          `-`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Make a layout with noticeable parts (such as header). Add this to `error.vue`:
```
<script setup lang="ts">
import { useHead } from '#app'
import type { NuxtError } from '#app'

const props = defineProps<{
  error: NuxtError
}>()

useHead({
  title: `Error ${props.error.statusCode || 'Unknown'}`
})

const handleError = () => {
  clearError({ redirect: '/' })
}
</script>

<template>
  <NuxtLayout name="default">
    <div class="error-container">
      <h1>Error {{ props.error.statusCode || 'Unknown' }}</h1>
      <p>{{ props.error.message || 'An unexpected error occurred' }}</p>
      <button @click="handleError">Go back to homepage</button>
    </div>
  </NuxtLayout>
</template>
```
Cause a 404 error to happen by going to a non-existent route.

My `layouts/default.vue` file:
```
<template>
    <NuxtLoadingIndicator color="#FFBC59" />
    <Navbar :language="language" />
    <NuxtPage :language="language" />
    <Footer :language="language" />
</template>
// some other code
```

Reproduction as a project: https://stackblitz.com/edit/github-nprqx2?file=layouts%2Fdefault.vue,error.vue,app.vue,pages%2Findex.vue,.gitignore

### Describe the bug

The error message does not appear on the page unless I remove `<NuxtLayout name="default">` and `</NuxtLayout>` from error page. This is not what I want, I want error message inside the layout. I can achieve this by replacing `<NuxtPage>` with `<slot>`, but that causes other problems (probably because props don't pass into the slot – should I make another bug report for that too?).

### Additional context

Using a layout on an error page is supposed to work because documentation states:

> you can still use layouts in the error file, by utilizing the [NuxtLayout](https://nuxt.com/docs/api/components/nuxt-layout) component and specifying the name of the layout

But I haven't found an example of that working. I am not 100% sure it's a bug, maybe I missed something.

**Comment by danielroe** [comment]
Layouts should not have `<NuxtPage>` inside - instead you use `<slot />`
