### ISSUE TITLE
watching useState not triggering change

### ISSUE THREAD

**Issue by tkjaergaard** [nuxt/nuxt#29291]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.16.0`
- Nuxt Version:     `3.13.2`
- CLI Version:      `3.14.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `pnpm@9.8.0`
- Builder:          `-`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-39uh5t?file=app.vue

### Describe the bug

I recently came across a case where i wanted to watch a useState. But watch didn't trigger on updates.

But using watchEffect did indeed trigger on changes.

I'm not completely sure if it's caused by the implementation of watch in vue or of useState?

**Comment by manniL** [comment]
This happens with `ref` too, so not a Nuxt issue.

If you watch the exact property with watch or do a deep watch, it will be triggered.

```ts
watch(() => state.value.foo, () => {
  watchFired.value = true;
});
```

```ts
watch(state, () => {
  watchFired.value = true;
}, { deep: true});
```

**Comment by tkjaergaard** [comment]
TIL 

Thanks @manniL 🙌
