### ISSUE TITLE
The #build alias for import files in server handlers returns error Vue app aliases are not allowed in server runtime

### ISSUE THREAD

**Issue by serhii-chernenko** [nuxt/nuxt#29302]
### Environment

- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.13.2
- CLI Version:      3.14.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3

### Reproduction

https://stackblitz.com/edit/nuxt-starter-ra1h6e

### Describe the bug

I want to have an utility file to collect some functions that I can use in server endpoints.
Moreover, I wanted to move some functionality from the root `utils` directory to a module. I followed the [official documentation of module creation](https://nuxt.com/docs/guide/going-further/modules) with example of [`addTemplate`](https://nuxt.com/docs/guide/going-further/modules#adding-templatesvirtual-files) with virtual files. But when I moved the file from the `utils` directory to the same one in a created module and tried to use the utils file in server handlers, I got the error:
```
[nitro 15:07:04]  ERROR  RollupError: [plugin impound] Vue app aliases are not allowed in server runtime. [importing #build/utils/custom from server/api/builtin-utils.get.ts]
```
The main reason that the `#build` alias is not allowed in the server handlers and there's no way to import the dynamic built file even if the file content is absolutely the same. It doesn't make modules developments flexible enough honestly.

Do you have any advice to solve my issue?

### Additional context

Steps to reproduce

Open the [`app.vue` file](https://stackblitz.com/edit/nuxt-starter-ra1h6e?file=app.vue). There are 2 requests to endpoints via `useFetch`. I just wanted to check if there's any difference between built-in server handlers and dynamically created ones in a module.

The [`custom.ts` file](https://stackblitz.com/edit/nuxt-starter-ra1h6e?file=utils%2Fcustom.ts) is created in the root `utils` directory. And the file import `~/utils/custom` is used in the [`builtin-utils.get.ts` server handler](https://stackblitz.com/edit/nuxt-starter-ra1h6e?file=server%2Fapi%2Fbuiltin-utils.get.ts).
```js
import { customFunction as customFunctionBuiltinUtils } from '~/utils/custom';
```

Than I duplicated the [`custom.ts` file](https://stackblitz.com/edit/nuxt-starter-ra1h6e?file=modules%2Fcustom%2Fruntime%2Futils%2Fcustom.ts) to a new created module. That injected via the general [`index.ts`](https://stackblitz.com/edit/nuxt-starter-ra1h6e?file=modules%2Fcustom%2Findex.ts) of the module:
```js
addTemplate({
  filename: 'utils/custom',
  src: resolve('runtime/utils/custom.ts'),
});
```

Now we can jump back to the [`builtin-utils.get.ts` server handler](https://stackblitz.com/edit/nuxt-starter-ra1h6e?file=server%2Fapi%2Fbuiltin-utils.get.ts) file and replace import from
```js
import { customFunction as customFunctionBuiltinUtils } from '~/utils/custom';
```
to
```js
import { customFunction as customFunctionModuleUtils } from '#build/utils/custom';
```

When the import replaced, get the error in the terminal. Try to re-run `npm run dev` in some cases:
```
[nitro 15:07:04]  ERROR  RollupError: [plugin impound] Vue app aliases are not allowed in server runtime. [importing #build/utils/custom from server/api/builtin-utils.get.ts]
```

### Logs

[nitro 15:07:04]  ERROR  RollupError: [plugin impound] Vue app aliases are not allowed in server runtime. [importing #build/utils/custom from server/api/builtin-utils.get.ts]

**Comment by TomKriek** [comment]
I personally use 

```
addServerImports([
      {
        name: 'functionName',
        from: resolve('./runtime/utils/function-name'),
      },
]);
```

and then retrieve it from the `#imports`

Adding it this way you will also see it in the types/nitro-imports.d.ts

Stackblitz: https://stackblitz.com/edit/nuxt-starter-zgtbkd?file=modules%2Fcustom%2Findex.ts

**Comment by danielroe** [comment]
This is deliberate because they are two totally different build contexts - even if it worked it would result in two copies of the same code being bundled.

To create virtual files that can be accessed in Nitro, you can do something like this:

```ts
nitro.options.virtual['some-import'] = () => `export default 'some export'`
```

I think it would be useful to add a helper for this - `addServerTemplate`.
