### ISSUE TITLE
 Icons Not Rendering in Tool Panel After Update

### ISSUE THREAD

**Issue by luacooli** [nuxt/nuxt#29301]
After updating nuxtui to 2.18.6, the icons inside the tool panel of the AG Grid framework are no longer rendering as expected. Additionally, the following warning appears in the console:

>   NuxtIcon: setup function returned a promise, but no <Suspense> boundary was found in the parent component tree. A component with async setup() must be nested in a <Suspense> in order to be rendered.

_Originally posted by @luacooli in https://github.com/nuxt/ui/issues/1789#issuecomment-2396983971_

**Comment by manniL** [comment]
This should be raised in https://github.com/nuxt/ui instead! ☺️
