### ISSUE TITLE
Error upon extending multiple layers

### ISSUE THREAD

**Issue by cheesypeperoni** [nuxt/nuxt#29316]
Uncaught SyntaxError: The requested module '/_nuxt/@id/virtual:nuxt:/<projectpath>/.nuxt/nuxt.config.mjs' does not provide an export named 'chunkErrorEvent' (at nuxt.js?v=fbdc03a7:4:17)

Any idea what could this be about ? 

![Image](https://github.com/user-attachments/assets/5580bcbd-9927-4036-989a-ae34f47035b6)
![Image](https://github.com/user-attachments/assets/38410b99-2ce8-4a82-ab08-abd063f74053)

**Comment by danielroe** [comment]
I would guess this is an issue of mismatching nuxt versions between your layers?
