### ISSUE TITLE
the websocket's `peer.peers` is `undefined` on deno-deploy

### ISSUE THREAD

**Issue by dongwa** [nuxt/nuxt#29317]
### Environment

nuxt + deno-deploy

### Reproduction

repo:
https://github.com/dongwa/nuxt_minirepo

deno-deploy:
https://donglin-nuxt-minire-46.deno.dev/websocket

### Describe the bug

The bug only occurs in the Deno Deploy environment and not in the development environment.

`peer.peers` works well in the development environment, but it is undefined in the [Deno Deploy](https://dash.deno.com/) environment.

![Image](https://github.com/user-attachments/assets/9e95e261-37d7-4a69-94a8-278cf293b4f9)
![Image](https://github.com/user-attachments/assets/48ae1a16-5f72-40aa-a67a-1b019658c761)

**Comment by pi0** [comment]
Can you please report it upstream in [crossws](https://crossws.unjs.io) 🙏🏼

**Comment by dongwa** [comment]
> Can you please report it upstream in [crossws](https://crossws.unjs.io) 🙏🏼
> 
> PS: Please try [nuxt nightly channel](https://nuxt.com/docs/guide/going-further/nightly-release-channel) as it includes latest crossws 0.3

I am trying nuxt-nightly,but how to deal with this?:
```
Module @primevue/nuxt-module is disabled due to incompatibility issues:                                                                                   18:50:46
 - [nuxt] Nuxt version ^3.0.0 is required but currently using 4.0.0-28806290.e3caf0ff
```
![Image](https://github.com/user-attachments/assets/07f22615-dd96-4043-8372-dde6d0f45547)

**Comment by pi0** [comment]
Ah! There is a 3.x tag on npm i believe. 

Alternatively you can try Nitro nightly only it should be compatible. https://nitro.unjs.io/guide/nightly

**Comment by dongwa** [comment]
I found out that `peer.peers` is a new feature of `crossws` 0.3. I have resolved it with the following solution:

``` json
  "overrides": {
    "crossws": "^0.3.1"
  },
  "pnpm": {
    "overrides": {
      "crossws": "^0.3.1"
    }
  }
```
