### ISSUE TITLE
[Vue Router warn]: No match found for location with path (NuxtLink using prop to and external)

### ISSUE THREAD

**Issue by rriixx** [nuxt/nuxt#29313]
### Describe the feature

This seems not be fixed with by this [issue](https://github.com/nuxt/nuxt/issues/19259) for external paths which exist on the same domain but in a different project (not managed by the current Nuxt app’s routing). 
I tried replacing `to` with `href` to no avail.
My paths have no protocol. 

```html
<NuxtLink to="/app/de/foo" external>
  my link
</NuxtLink>
```

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [x] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [x] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
This is caused by prefetching behaviour, so you can workaround it for now by passing `no-prefetch` to the link.
