### ISSUE TITLE
NuxtIsland: Failed to locate Teleport target with selector

### ISSUE THREAD

**Issue by robert-hoffmann** [nuxt/nuxt#29345]
### Environment

Nuxt project info:                                                                                                                                                   10:52:59 AM

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.15.0
- Nuxt Version:     3.13.2
- CLI Version:      3.14.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.9.0
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-d9qil3

Be sure to open in full page, and open the dev console

### Describe the bug

`<SomeComponent>.server.vue` actually still works, but if it contains a **selectiveClient** / `nuxt-client` element, this part is now broken, until you refresh or navigate to another page, using links and not the browser buttons (well refresh does work)

Whether or not the server component contains a **selectiveClient** is irrelevant to the error message in the console, it will still throw that error

However if it does contain a **selectiveClient**, then that part of the server component, is now broken

### Additional context

When using normal links (either a href, or <NuxtLink>) this does not happen

It only happens when hitting the back button in the browser (or shortcut on mouse)

EDIT:
Actually it does happen with NuxtLink's, the href is simply reloading the whole page, that's why it's not happening there

### Logs

runtime-core.esm-bundler.js?v=c0e84aa4:50 [Vue warn]: Failed to locate Teleport target with selector "div[data-island-uid='1'][data-island-component="CounterButton-hb1RAsRv3M"]". Note the target element must exist before the component is mounted - i.e. the target cannot be rendered by the component itself, and ideally should be outside of the entire Vue component tree. 
  at <NuxtIsland name="HelloIsland" > 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) {__v_skip: true} > > 
  at <Anonymous key="/" vnode= {__v_isVNode: true, __v_skip: true, type: {…}, props: {…}, key: null, …} route= {fullPath: '/', path: '/', query: {…}, hash: '', name: 'index', …}  ... > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <SideMenu ref=Ref< Proxy(Object) {…} > > 
  at <LayoutLoader key="side-menu" layoutProps= {ref: RefImpl} name="side-menu" > 
  at <NuxtLayoutProvider layoutProps= {ref: RefImpl} key="side-menu" name="side-menu"  ... > 
  at <NuxtLayout> 
  at <App key=4 > 
  at <NuxtRoot>

**Comment by robert-hoffmann** [comment]
Ok, here is the reproduction, it's now producing the error

https://stackblitz.com/edit/nuxt-starter-d9qil3

Be sure to open in full page, and open the dev console

**Comment by robert-hoffmann** [comment]
So, i narrowed the error down a bit

As soon as the server component uses a <slot>, or includes another component with `nuxt-client`, it breaks

**Comment by bernhardberger** [comment]
I'm surprised your project even builds.

Could this be related: https://github.com/nuxt/nuxt/issues/29354

At a quick glance I don't see any major differences between our projects.

**Comment by robert-hoffmann** [comment]
@bernhardberger why are you surprised it even builds ?

Oh, probably because i have this enabled
https://github.com/nuxt/nuxt/issues/29354#issuecomment-2406364289

But the extra error is that adding a `nuxt-client`, will break it too

**Comment by bernhardberger** [comment]
> @bernhardberger why are you surprised it even builds ?
> 
> Oh, probably because i have this enabled
> https://github.com/nuxt/nuxt/issues/29354#issuecomment-2406364289
> 
> But the extra error is that adding a `nuxt-client`, will break it too

I don't think using `nuxt-client` actually makes a difference for the slot to be broken. It also breaks without it (slot from the server component is gone when navigating to the page client side until you hit reload).

**Comment by robert-hoffmann** [comment]
i removed the slot and only used the `nuxt-client`, it breaks too, if i remove both, it works (i do leave `selectiveClient: true` in my config though)
