### ISSUE TITLE
According to a demo from the nuxt document, binding click events in index.vue, why not trigger print logs in the 360 browser-compatible mode, and IE11l, is it a compatibility issue?

### ISSUE THREAD

**Issue by Thebrightmooncrisscross** [nuxt/nuxt#29360]
代码
![Image](https://github.com/user-attachments/assets/1019cff6-856f-4e0e-8d88-2f16e8fccd22)

package.json
{
  "name": "nuxt-app",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate"
  },
  "dependencies": {
    "babel-polyfill": "^6.26.0",
    "core-js": "^3.38.1",
    "element-ui": "^2.15.10",
    "nuxt": "^2.15.8",
    "vue": "^2.7.10",
    "vue-server-renderer": "^2.7.10",
    "vue-template-compiler": "^2.7.10"
  },
  "devDependencies": {
    "@babel/plugin-transform-runtime": "^7.25.7"
  }
}

**Comment by manniL** [comment]
I'm afraid Nuxt 2 is end of life and not supported anymore. It should work fine in IE11 though.
