### ISSUE TITLE
Page layout stopped working after upgrading nuxt from 3.11 to 3.13

### ISSUE THREAD

**Issue by despatates** [nuxt/nuxt#29361]
### Environment

```
------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.13.2
- CLI Version:      3.13.2
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      compatibilityDate, devtools, ssr, modules, auth
- Runtime Modules:  @pinia/nuxt@0.5.4, @trandaison/nuxt-3-auth@0.1.4
- Build Modules:    -
------------------------------
```

### Reproduction

With Nuxt 3.13 (not working): https://stackblitz.com/edit/nuxt-starter-gmwxix?file=nuxt.config.ts

With Nuxt 3.11 (working): https://stackblitz.com/edit/nuxt-starter-meyimq?file=nuxt.config.ts

### Describe the bug

I'm using a page with a `login` layout.
After upgrading the nuxt version from 3.11.2 to 3.13.2, the layout is no more used and the `default` one is used instead.

```vue
<script setup>
definePageMeta({
  auth: 'guest',
  layout: 'login',
});
</script>
```

### Additional context

This problem is reproducible when using the [`trandaison/nuxt-3-auth`](https://github.com/trandaison/nuxt-3-auth) plugin. When using Nuxt without it, layouts work fine.

**Comment by Gypsophyllite** [comment]
I tried **'working'** and **'not working'** reproductions, both of them are not working. Seems like it is caused by module **'@trandaison/nuxt-3-auth'**, the link **'Go back'** can't even click, and remove it, all good. Maybe you write wrong redirects or something?

**Comment by despatates** [comment]
The issue is not with the login form or the redirection link but with the page's layout.

My page `page/login.vue` is configured to use the `layout/login.vue` layout.
With the same code, the layout used by the page is different between Nuxt 3.11 and Nuxt 3.13.

The nuxt version on the _working_ reproduction was broken, I fixed it.


**With 3.13**, the page uses the wrong layout (should be `login`, not `default`)
![Image](https://github.com/user-attachments/assets/11697bbc-3856-4e40-950c-d648ee1aa013)


**With 3.11**, it works as expected.
![Image](https://github.com/user-attachments/assets/2c00b7ef-a8a3-4208-9176-32c571c6d348)

**Comment by danielroe** [comment]
For now you can resolve by setting `experimental.scanPageMeta` to false.

In the next release of Nuxt, you can change this to:

```ts
export default defineNuxtConfig({
  experimental: {
    scanPageMeta: 'after-resolve'
  },
})
```

(This will be the default in Nuxt v4.)
