### ISSUE TITLE
useFetch is caching API data despite using cache: 'no-store' or 'no-cache'

### ISSUE THREAD

**Issue by xushnudbek20** [nuxt/nuxt#29363]
### Describe the feature

1. I am using useFetch in my Nuxt 3 project to fetch API data, and I have set cache: 'no-store' for the request.
2. Despite this setting, the API data seems to be cached. On the first visit, it fetches fresh data from the API. However, on subsequent visits (like on the next day), it shows the data that was cached previously.
3. I expected cache: 'no-store' to prevent any caching, but it appears that it still returns cached data.

Here is a simplified version of my setup:
```
<script lang="ts" setup>
const runtimeConfig: any = useRuntimeConfig();
const smartphonesList = ref([]);

const fetchActionSmartphones = async () => {
  const filter = {
    per_page: 12,
    page: 1,
    parent0_category_id: 1,
    parent1_category_id: 2,
    parent2_category_ids: '683, 128, 127, 125, 3',
    sort_key: 'created_at',
    sort_type: 'desc',
  };

  const { data }: any = await useFetch(`${runtimeConfig.public.apiBaseUrl}/shop/models-with-parents`, {
    params: { ...filter, appends: 'main_photo|price|price_twelve_month' },
    cache: 'no-store',
    transform: (response: any) => response.data.data,
  });

  smartphonesList.value = data.value;
};
fetchActionSmartphones();
</script>

```
Questions:

1. Is this the expected behavior of useFetch with cache: 'no-store'?
2. Is there a recommended way to ensure that API responses are always fresh?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [x] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [x] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
https://github.com/nuxt/nuxt/issues/29364#issuecomment-2404754529
