### ISSUE TITLE
Title: useFetch is caching API data despite using cache: 'no-store'

### ISSUE THREAD

**Issue by xushnudbek20** [nuxt/nuxt#29364]
### Environment

Nuxt Version: ^3.9.1
Node Version: v18.19.0

### Reproduction

https://codesandbox.io/p/devbox/github/nuxt/starter/tree/v3

### Describe the bug

1. I am using useFetch in my Nuxt 3 project to fetch API data, and I have set cache: 'no-store' for the request.
2. Despite this setting, the API data seems to be cached. On the first visit, it fetches fresh data from the API. However, on subsequent visits (like on the next day), it shows the data that was cached previously.
3. I expected cache: 'no-store' to prevent any caching, but it appears that it still returns cached data.

Here is a simplified version of my setup:
```
<script lang="ts" setup>
const runtimeConfig: any = useRuntimeConfig();
const smartphonesList = ref([]);

const fetchActionSmartphones = async () => {
  const filter = {
    per_page: 12,
    page: 1,
    parent0_category_id: 1,
    parent1_category_id: 2,
    parent2_category_ids: '683, 128, 127, 125, 3',
    sort_key: 'created_at',
    sort_type: 'desc',
  };

  const { data }: any = await useFetch(`${runtimeConfig.public.apiBaseUrl}/shop/models-with-parents`, {
    params: { ...filter, appends: 'main_photo|price|price_twelve_month' },
    cache: 'no-store',
    transform: (response: any) => response.data.data,
  });

  smartphonesList.value = data.value;
};
fetchActionSmartphones();
</script>

```
Questions:

1. Is this the expected behavior of useFetch with cache: 'no-store'?
2. Is there a recommended way to ensure that API responses are always fresh?

### Additional context

I need fresh data on every visit

**Comment by danielroe** [comment]
cache: no store is an option passed to `fetch` and it affects the fetch request. it doesn't affect how nuxt subsequently stores the data.

**Comment by xushnudbek20** [comment]
then how to fix not cache for visit?

**Comment by danielroe** [comment]
in your case you should use $fetch and not useFetch as you are calling it in a function
