### ISSUE TITLE
nuxt vulnerable to Cross-site Scripting in navigateTo if used after SSR  v2.0

### ISSUE THREAD

**Issue by alongcai** [nuxt/nuxt#29379]
### Describe the feature

nuxt vulnerable to Cross-site Scripting in navigateTo if used after SSR 
v2.0 Can it be upgraded and repaired?

### Additional information

- [x] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [x] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [x] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
Nuxt 2 reached End of Life.

> On December 31st, 2023, Vue 2 will reach End of Life (EOL), and Nuxt 2 will follow on **June 30th, 2024.**

> After that date, Nuxt 2 will continue to be available on the NPM package manager, but will no longer receive updates, such as security and browser compatibility fixes. 

See more on https://v2.nuxt.com/lts
