### ISSUE TITLE
When the useFetch request is repeated, the data does not change

### ISSUE THREAD

**Issue by champ7champ** [nuxt/nuxt#29378]
### Environment

Nuxt 3 latest version

### Reproduction

this cannot be done because there is no open service that will provide such an api to reproduce it. Can you advise me? I need an error to arrive at the same url, and then a callback occurs, but only without an error if the headers are correct.

https://stackblitz.com/edit/nuxt-starter-74zqym?file=plugins%2Fapi.ts

![Image](https://github.com/user-attachments/assets/7cac11cc-9e02-4ad1-b77b-9264b2ebf889)
![Image](https://github.com/user-attachments/assets/15f35060-1246-4fd5-8914-dcd0d0ffea5a)
![Image](https://github.com/user-attachments/assets/ff499aff-aa14-4856-b968-4ded740a90b1)

When the useFetch request is repeated, the data does not change. The fact is that when I go to the page where the USEFETCH wrapper is used, the data is processed correctly, but if in case of a 401 authorization error I need to call an additional function, a token request, after which I return the original function, the data does not change. How do I return the current data to the template? Hint. If done in useApi

```
export async function useAPI<T>(url: string | (() => string), options?: UseFetchOptions<T>) {
  const response = await useFetch(url, {
    ...options,
    $fetch: useNuxtApp().$api,
    isUseFetch: true,
  })

  if (response.data.value.statusCode === 401) {
    await response.clear()
    await response.refresh()

    return response
  }

  return response
}
```

clear() and refresh() then everything works properly, but there is a problem of hydration. How can I make the data in the component reactive and get the values from the second request?

### Describe the bug

I have tried many different ways, but there is a feeling that the problem is in nuxt. 

https://nuxt.com/docs/guide/recipes/custom-usefetch

The problem occurs at the moment when you press f5 on the page itself, and it gives a 401 error on the ssr side, then calls the method to get new tokens, and should call that very first request and get the data, but I have an error in the variable from that first request

**Comment by champ7champ** [comment]
this cannot be done because there is no open service that will provide such an api to reproduce it. Can you advise me? I need an error to arrive at the same url, and then a callback occurs, but only without an error if the headers are correct.


https://stackblitz.com/edit/nuxt-starter-74zqym?file=plugins%2Fapi.ts

**Comment by champ7champ** [comment]
> this cannot be done because there is no open service that will provide such an api to reproduce it. Can you advise me? I need an error to arrive at the same url, and then a callback occurs, but only without an error if the headers are correct.
> 
> https://stackblitz.com/edit/nuxt-starter-74zqym?file=plugins%2Fapi.ts

up

**Comment by champ7champ** [comment]
> Would you be able to provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
> 
> More info

up

this cannot be done because there is no open service that will provide such an api to reproduce it. Can you advise me? I need an error to arrive at the same url, and then a callback occurs, but only without an error if the headers are correct.

https://stackblitz.com/edit/nuxt-starter-74zqym?file=plugins%2Fapi.ts

**Comment by champ7champ** [comment]
I found a solution, maybe it will be useful to someone, but a new problem has appeared) After I failed to call the first request (401), a refresh request is called and if it also returns 401 or some other error, then it is not possible to catch it

```
export async function useAPI<T>(url: string | (() => string), options?: UseFetchOptions<T>) {
  const nuxtApp = useNuxtApp()
  const user = useUser()
  const config = useRuntimeConfig()

  const rec = ref()

  const response = useFetch(url, {
    ...options,
    isUseFetch: true,
    baseURL: config.public.apiBase || '',
    credentials: 'include',
    watch: [rec],
    cache: 'no-cache',

    onRequest({ options }) {
      const accessToken = user.jwt.accessToken

      if (accessToken) {
        const headers = options.headers || {}

        if (Array.isArray(headers)) {
          headers.push(['Authorization', `Bearer ${accessToken}`])
        } else if (headers instanceof Headers) {
          headers.set('Authorization', `Bearer ${accessToken}`)
        } else {
          headers.Authorization = `Bearer ${accessToken}`
        }
      }
    },

    async onResponse({ response }) {
      if ([401, 403].includes(response.status)) {
        const { refreshToken } = getTokens(nuxtApp)

        if (!refreshToken) {
          await user.logout()
          return navigateTo('signin')
        }

        const refreshApi = `${config.public?.apiBase}/auth/login/access-token`

        const refreshResponse = await $fetch(refreshApi, {
          method: 'POST',
          body: JSON.stringify({ refreshToken }),
          headers: {
            'Content-Type': 'application/json',
          },
        })

        if (refreshResponse?.accessToken && refreshResponse?.refreshToken) {
          user.jwt.accessToken = refreshResponse.accessToken
          user.jwt.refreshToken = refreshResponse.refreshToken
          await user.syncCookie()

          rec.value += 1

          return
        } else {
          await user.logout()
          return navigateTo('signin')
        }
      }

      return response
    },
  })

  return response
}
```

**Comment by baba990aini** [comment]
Check the useFetch cache issue and try adding key: Date. now(). toString() to the second parameter object of useFetch
