### ISSUE TITLE
CLI Ability

### ISSUE THREAD

**Issue by kaaax0815** [nuxt/nuxt#29386]
### Describe the feature

I am using Nuxt and its integrated Server to do stuff on the Server.

I would like to be able to also call e.g. `node .output/server/cli.mjs run Something` that then calls some functions that are in the Server Bundle.

Maybe a workaround would be to create the CLI manually and bundle it with all the Stuff that it needs. I don't know how and it also would not be very efficient

### Additional information

- [ ] Would you be willing to help implement this feature?
- [x] Could this feature be implemented as a module?

### Final checks

- [x] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [x] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
you can already do this with a custom nitro preset

see https://github.com/unjs/nitro/blob/v2/src/presets/node/runtime/cli.ts and https://github.com/unjs/nitro/blob/v2/src/presets/node/preset.ts#L40-L52 for an example of how to do this.
