### ISSUE TITLE
The issue of incorrect class name rendering.

### ISSUE THREAD

**Issue by 1059431281** [nuxt/nuxt#29401]
### Environment

Operating System: Mac mini
Nuxt Version: 3.9.3
CLI Version: 3.14.0

### Reproduction

https://stackblitz.com/edit/nuxt-starter-nmbanj?file=app.vue

### Describe the bug

Hello, when I try to modify a value in a lifecycle hook on the client side before mounting, the page content changes accordingly, but the class name still corresponds to the value before the modification. Normally, the class name at this point should be "test1" instead of "test2".
Continuing from where we left off, please be sure to observe the state of the page during the initial load, as subsequent updates will trigger page rendering and everything will appear normal then.
I'm not sure if this is an intentional feature or a bug. Could you please clarify?

**Comment by 1059431281** [comment]
![Image](https://github.com/user-attachments/assets/9ef9a136-ee18-444b-a35a-3ee49606e75c)

**Comment by huang-julien** [comment]
HEllo you're modifying a ref before the end of the hydration step. Thus causing a hydration issue.

see https://vuejs.org/guide/scaling-up/ssr.html#client-hydration

**Comment by 1059431281** [comment]
thank
