### ISSUE TITLE
Option to delay URL change until data fetching is complete (like Nuxt 2 asyncData)

### ISSUE THREAD

**Issue by parigi-n** [nuxt/nuxt#29535]
## Description
In Nuxt 3, when navigating between pages, the URL changes before the data for the new page has finished fetching. This behavior differs from Nuxt 2, where the URL would only change after all data fetching was complete.

## Current Behavior
1. User clicks a link to navigate to a new page
2. The URL in the browser changes immediately
3. The new page's data starts fetching
4. The new page renders, potentially showing loading states

## Desired Behavior
An option to:
1. User clicks a link to navigate to a new page
2. The current page remains visible and the URL stays unchanged
3. The new page's data fetches in the background
4. Once data fetching is complete, the URL changes and the new page renders

## Motivation
This feature would be beneficial for several reasons:
1. It maintains consistency with the behavior many developers are accustomed to from Nuxt 2 with asyncData
2. It avoids potential issues when watching properties related to the "route" object

## Additional Context

The current behavior can cause problems when watching properties linked to the "route" object. Since the URL changes before data fetching is complete, watchers may trigger prematurely in the current page, leading to unexpected behavior or race conditions in the application logic.

## Reproduction
I've created a CodeSandbox to demonstrate the current behavior:
https://codesandbox.io/p/github/nuxt/starter/csb-s5wk54/draft/sleepy-dream

In this example, you can observe that the URL changes immediately upon navigation, before the data for the new page has finished loading.

### Additional information

- [x] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [x] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [x] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by mkierdev** [comment]
Wouldn't Suspense component solve your issue?

"It provides a more seamless user experience, especially for pages with significant data requirements" - isn't actually the opposite? Load the page client-side as fast as you can with placeholders, so user is not stuck on long loader while app being 'frozen' (as it was the case with async data in Nuxt 2)

**Comment by parigi-n** [comment]
> Wouldn't Suspense component solve your issue?
> 
> "It provides a more seamless user experience, especially for pages with significant data requirements" - isn't actually the opposite? Load the page client-side as fast as you can with placeholders, so user is not stuck on long loader while app being 'frozen' (as it was the case with async data in Nuxt 2).

You right. I shouldn't have gone into that - it's not the main problem, i will edit that ! :)
The issue was more to have a behavior similar to Nuxt 2/asyncData, and if you don't want placeholders
Note that this is also the normal behavior of the navigator with a “classic” html website.

**Comment by danielroe** [comment]
Currently, the URL might change before the page content changes. This is upstream `vue-router` behaviour with Suspense - please raise an issue there if you think this should be different.

Second, Nuxt _does_ block navigation until all pending async setups are resolved, as you can see in your reproduction. If that's not happening for you, please feel free to provide a reproduction and I'll happily investigate 🙏
