### ISSUE TITLE
Lazy loading components via `#components` import does not work

### ISSUE THREAD

**Issue by Mokkapps** [nuxt/nuxt#29563]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.13.2
- CLI Version:      3.14.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-wbt6nq?file=app.vue

### Describe the bug

This is a simple reproduction of a more complex rendering logic we use in one of my client's project. 

We define a list of components that should be lazy loaded via imports prefixed with `Lazy` from `#components`

```ts
import { LazyComp1, LazyComp2, LazyCompWrapper } from '#components';

export const LAZY_COMPONENTS = {
  KEY_1: LazyComp1,
  KEY_2: LazyComp2,
  WRAPPER: LazyCompWrapper,
};
```

Unfortunately, the components are always loaded even if they are not even used. 

In the linked Stackblitz reproduction, I only reference `LazyCompWrapper` in the `app.vue` but `Comp1` and `Comp2` are also loaded by the browser:

![Image](https://github.com/user-attachments/assets/861a5cfe-94ff-41be-a452-127b1e7bcee6)

Is this a bug, or are we doing something wrong?

Thanks in advance for your help!

**Comment by onmax** [comment]
If I am not wrong, you need to use [`defineAsyncComponent`](https://vuejs.org/guide/components/async#basic-usage) to import the components dynamically

Here's an example:

```ts
const loadComponent = (componentName) =>
  defineAsyncComponent(() => import('#components').then((cmps) => cmps[componentName]))

export const LAZY_COMPONENTS = {
  KEY_1: loadComponent('Comp1'),
  KEY_2: loadComponent('Comp2'),
  WRAPPER: loadComponent('CompWrapper'),
}
```

This way you're still using the `#components` alias, but only dynamically loading the component that matches the key when needed. This simplifies the code and avoids loading all components at once.

If you don't want to use all of the components and then select the component that you need, you can use a relative path such as:

```ts
export const LAZY_COMPONENTS = {
  KEY_1: loadComponent('./components/Comp1.vue'),
  KEY_2: loadComponent('../components/Comp2.vue'),
  WRAPPER: loadComponent('../components/CompWrapper.vue'),
}
```

Hope this helps!

**Comment by Mokkapps** [comment]
> If I am not wrong, you need to use [`defineAsyncComponent`](https://vuejs.org/guide/components/async#basic-usage) to import the components dynamically
> 
> Here's an example:
> 
> const loadComponent = (componentName) =>
>   defineAsyncComponent(() => import('#components').then((cmps) => cmps[componentName]))
> 
> export const LAZY_COMPONENTS = {
>   KEY_1: loadComponent('Comp1'),
>   KEY_2: loadComponent('Comp2'),
>   WRAPPER: loadComponent('CompWrapper'),
> }
> This way you're still using the `#components` alias, but only dynamically loading the component that matches the key when needed. This simplifies the code and avoids loading all components at once.
> 
> If you don't want to use all of the components and then select the component that you need, you can use a relative path such as:
> 
> export const LAZY_COMPONENTS = {
>   KEY_1: loadComponent('./components/Comp1.vue'),
>   KEY_2: loadComponent('../components/Comp2.vue'),
>   WRAPPER: loadComponent('../components/CompWrapper.vue'),
> }
> Hope this helps!

Thanks for the quick response. 

I tried your example but I get an error:

```
 ERROR  Internal server error: Failed to resolve import "#components" from "componentMap.ts". Does the file exist?                                      09:17:41
  Plugin: vite:import-analysis
  File: /home/projects/nuxt-starter-wbt6nq/componentMap.ts:3:11
  1  |  import { defineAsyncComponent } from 'vue';
  2  |  const loadComponent = (componentName) => defineAsyncComponent(
  3  |    () => import("#components").then((cmps) => cmps[componentName])
     |                 ^
  4  |  );
  5  |  export const LAZY_COMPONENTS = {
```

Available in this StackBlitz project: https://stackblitz.com/edit/nuxt-starter-dwb4mc?file=componentMap.ts

Will analyze if we could switch to relative paths, but would prefer to avoid them

**Comment by onmax** [comment]
Yeah, you are right. Sorry about that.

I am not sure if you can use `defineAsyncComponent` + `#components`, since I don't know if Vite has access to `#components`. Let's wait if anyone suggest another approach

**Comment by danielroe** [comment]
The `LazyComponent` form is an async component and you are likely seeing prefetching behaviour, where vite eagerly loads chunks that _might_ be needed (but with a lower priority than the rest of your JS).

You can use the `build:manifest` to turn off this preload behaviour.

We can follow improvements here in https://github.com/nuxt/nuxt/issues/14584.
