### ISSUE TITLE
bug: `process.stdout.isTTY` not set

### ISSUE THREAD

**Issue by juliusmarminge** [nuxt/nuxt#29573]
### Environment

- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.13.2
- CLI Version:      3.14.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-vbttq3?file=server%2Fapi%2Fhello.ts

### Describe the bug

Nuxt's' logging setup does not set `process.stdout.isTTY`.

This makes 3rd party logging libs like `effect/Logger` not work properly: https://github.com/Effect-TS/effect/blob/97cb0145114b2cd2f378e98f6c4ff5bf2c1865f5/packages/effect/src/internal/logger.ts#L438C78-L438C96

This is the result when running `node -e 'console.log(process.stdout.isTTY)'` in vanilla node:

![Image](https://github.com/user-attachments/assets/51442b84-fe3e-452c-8792-7344db439270)

Example diff between Nuxt and for example Next:

![Image](https://github.com/user-attachments/assets/fc110486-19d2-4338-b23b-68a26c0e8198)

**Comment by danielroe** [comment]
@juliusmarminge is the issue that it's `undefined` rather than `false`?

**Comment by juliusmarminge** [comment]
I'd probably expect it to be true when running the server in node?

**Comment by pi0** [comment]
`isTTY` in dev server (which is a Node.js worker) is undefined -- this is node.js behavior and actually correct indication that TTY is not available in worker isolate of dev server. When running output in production mode it is `true`

**Comment by datner** [comment]
@pi0, do you have a recommendation for a 'better method of detection' that could be used?

**Comment by pi0** [comment]
@datner i have two references we use:
- https://github.com/unjs/std-env/blob/a337aaba4577b9f23ce16e0e91eac106b03c5e73/src/flags.ts#L44
- https://github.com/unjs/consola/blob/1ac116a1c415fbfc1bab57cb0a0013ccc0bc3e2c/src/utils/color.ts
