### ISSUE TITLE
Scrol-to-top doesn't affect pages in nested layouts

### ISSUE THREAD

**Issue by KonradDRAST** [nuxt/nuxt#29587]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.10.0
- Nuxt Version:     3.13.2
- CLI Version:      3.13.2
- Nitro Version:    2.9.7
- Package Manager:  yarn@4.3.0
- Builder:          -
- User Config:      compatibilityDate, app, colorMode, devtools, extends, i18n
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

When the layout is full screen without global scrolling, nested pages do not respect routers' `scrollTo` position from the plugin.

### Describe the bug

How do you force scroll-to-top on nested pages?
Widely suggested an approach with a plugin affecting router configuration or the `page:finish` hook doesn't work if the page is nested in a static layout that covers the screen without scrolling. 
Soft navigation between two routes causes swap only part of this layout - nested page, and it always remembers the scroll position.
Is there a way to force nested pages to scroll-to-top without adding code `on Mounted` in each one?

### Additional context

![Image](https://github.com/user-attachments/assets/13bf38ee-683e-4c63-a2db-843e1ced3064)

### Reproduction

https://stackblitz.com/edit/github-zhdhqq

**Comment by danielroe** [comment]
Have you tried a custom `scrollBehavior` in a `~/app/router.options` file? It may be the default one is unable to know which _container_ to scroll for you.

**Comment by KonradDRAST** [comment]
> Have you tried a custom `scrollBehavior` in a `~/app/router.options` file? It may be the default one is unable to know which _container_ to scroll for you.

Yes. I've tried. Unfortunately without success.
```
export default <RouterConfig>{
  scrollBehavior(to, from, savedPosition) {
    return {
      el: '#main',
      top: 0,
    }
  },
}
```

But again. It looks like the router looks for the element mentioned in the options, and tries to scroll `window` until it reaches the mentioned element. As my layout is fixed, then `#main` is always visible and can't be scrolled to, and its content is replaced on navigation but not really affected by router options. 

I believe that some logic behind `NuxtPage` component is required in such a case.

**Comment by KonradDRAST** [comment]
I've added some basic reproduction to clarify further. Router options added there as well.

**Comment by KonradDRAST** [comment]
Uh. I've just realized that I can put any logic into scrollBehaviour, so after update, it works like a charm ;-)
```
export default <RouterConfig>{
  scrollBehavior(to, from, savedPosition) {
    const content = document.querySelector('#main')
    if (content) {
      content.scrollTop = 0
    }
  },
}
```
