### ISSUE TITLE
Potential regression: vuestic-ui loaded from two different files in nuxt v3.13.2

### ISSUE THREAD

**Issue by m0ksem** [nuxt/nuxt#29596]
### Environment

- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.13.2
- CLI Version:      3.14.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@8.6.12
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-poqjmh?file=package.json,nuxt.config.ts,app.vue

### Describe the bug

Now`addComponent` resolves full path to node module by default. But, when module is optimized with vite, this path is wrong.

In `vuestic/nuxt`, we use `import { createVuestic } from 'vuestic-ui'` to register runtime plugin. In plugin we use `provide` with Symbol. 
Path when `import from 'vuestic-ui'` is 
```
/_nuxt/node_modules/.cache/vite/client/deps/vuestic-ui.js?v=6d032d21
```

When using addComponent, mlly resolves path to node module, which is different file.
Path to component: 

```
/_nuxt/node_modules/.pnpm/vuestic-ui@1.10.3/node_modules/vuestic-ui/dist/es/main.js?v=0e702035
```

### Additional context

https://github.com/epicmaxco/vuestic-ui/issues/4403#issuecomment-2422373698

We can disable optimizeDeps for package or bundle es into one module, but would be nice to be able to disable force "resolvePath".

**Comment by rehaburakacar** [comment]
Hi,

So we want `addComponent` to resolve path as 

`/_nuxt/node_modules/.cache/vite/client/deps/vuestic-ui.js?v=6d032d21`

Right? Description is a bit complex so I want to make sure that what should be done to solve it.

Thanks.

**Comment by danielroe** [comment]
I believe this should be resolved via https://github.com/nuxt/nuxt/pull/29036.
