### ISSUE TITLE
Using Vite config inside of nuxt.config causes error

### ISSUE THREAD

**Issue by titusdecali** [nuxt/nuxt#29601]
### Environment

Not sure if this should be a `vite` or `nuxt` issue, but posting here for now as it only happens when using `nuxt.config.ts`

After seeing:
` WARN  Using vite.config.ts is not supported together with Nuxt. Use options.vite instead. You can read more in https://nuxt.com/docs/api/nuxt-config#vite.`

I moved my config into my `nuxt.config` file, however I am getting an error with `vite-plugin-vue-inspector` which doesn't occur when my vite config is in a separate file:

**ERROR:**
```
[오전 9:46:08]  ERROR  Pre-transform error: At least one <template> or <script> is required in a single file component. ~/node_modules/.pnpm/vite-plugin-vue-inspector@5.1.3_vite@5.4.9_@types+node@22.7.6_sass@1.80.3_terser@5.36.0_/node_modules/vite-plugin-vue-inspector/src/Overlay.vue
```

Am I setting this up incorrectly?

### Reproduction

https://stackblitz.com/edit/github-dy5mxd?file=nuxt.config.ts

### Describe the bug

When using `vite:` config within nuxt.config.ts, a pre-transform error on `Overlay.vue` template is seen

**Comment by HigherOrderLogic** [comment]
Why do you need to specify the Vue plugin? It should come bundled with Nuxt as default.

**Comment by titusdecali** [comment]
> Why do you need to specify the Vue plugin? It should come bundled with Nuxt as default.

Because I am compiling vue SFC files and Vite doesn't know (by default) how to handle them. If I remove it, I cannot use autoprefixer, and all my templates will be without style.
