### ISSUE TITLE
Custom useFetch SSR is not working after upgrading to 3.13

### ISSUE THREAD

**Issue by dany68** [nuxt/nuxt#29636]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.17.0`
- Nuxt Version:     `3.13.2`
- CLI Version:      `3.14.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `npm@10.8.3`
- Builder:          `-`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

--

### Describe the bug

Hi everyone,

I'm using a custom useFetch similar to the one from the given example: https://nuxt.com/docs/examples/advanced/use-custom-fetch-composable

After upgrading to nuxt 3.13 it seems to not work anymore when the page is fetch server side (client side there are no problems).
I get the following error:

```
Module.useNuxtApp (node_modules/nuxt/dist/app/nuxt.js:251:13)
  at Module.useRequestEvent (node_modules/nuxt/dist/app/composables/ssr.js:11:58)
  at readRawCookies (node_modules/nuxt/dist/app/composables/cookie.js:144:101)
  at Module.useCookie (node_modules/nuxt/dist/app/composables/cookie.js:29:19)
  at onRequest (plugins/apiFetch.ts:21:43)
  at callHooks (node_modules/ofetch/dist/shared/ofetch.03887fc3.mjs:134:13)
  at $fetchRaw2 (node_modules/ofetch/dist/shared/ofetch.03887fc3.mjs:207:13)
  at onError (node_modules/ofetch/dist/shared/ofetch.03887fc3.mjs:179:16)
  at $fetchRaw2 (node_modules/ofetch/dist/shared/ofetch.03887fc3.mjs:311:20)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at https://nuxt.com/docs/guide/concepts/auto-imports#vue-and-nuxt-composables.
```

Before upgrading everything worked fine. In a script setup i use the custom fetch as follows:
`const { data: posts, error } = await useApiFetch<Feed>('/posts')`

Any ideas? Can it be related to change of nuxt on useCookie() ?

Thank you very much for your help,

**Comment by ss0505** [comment]
hi @dany68 :)

I am a nuxt newbie, so I apologize if I am off the mark.

Is the target customFetch in a nested directory or something?
https://nuxt.com/docs/guide/directory-structure/composables#how-files-are-scanned

-| composables/
---| index.ts     // scanned
---| useFoo.ts    // scanned
---| nested/
-----| utils.ts   // not scanned

I remember stumbling on a similar error and I think I solved it by doing something like registering it in the config file.

ex) nuxt.config.ts

```
export default defineNuxtConfig({
  imports: {
    dirs: [
      // Scan top-level modules
      'composables',
      // ... or scan modules nested one level deep with a specific name and file extension
      'composables/*/index.{ts,js,mjs,mts}',
      // ... or scan all modules within given directory
      'composables/**'
    ]
  }
})
```

I hope this is helpful to you.

**Comment by dany68** [comment]
Thank you @ss0505 for your reply.
I have exactly as the official example in the nuxt doc:
- apiFetch.ts in the plugins directory
- useApiFetch in the composables directory:

As follows:
```
// plugins/apiFetch.ts

export default defineNuxtPlugin(() => {
    const auth = useCookie('auth')
    const config = useRuntimeConfig()

    const $apiFetch = $fetch.create({
        baseURL: config.public.API_URL,
        credentials: 'include',
        headers: {
            'Accept': 'application/json',
            'X-Requested-With': 'XMLHttpRequest',
            referer: config.public.APP_URL,
        },
        onRequest({ options }) {
            const token = useCookie('XSRF-TOKEN')
            if (token.value) {
                options.headers = {
                    ...options.headers,
                    ...useRequestHeaders(["cookie"]),
                    'X-XSRF-TOKEN': decodeURIComponent(token.value as string)
                }
            }
        },
        onResponseError({ response }) {
            if (response.status === 401) {
                auth.value = null
                return navigateTo('/login')
            }
        }
    })

    return {
        provide: {
            apiFetch: $apiFetch
        }
    }
})
```

```
// composables/useApiFetch.ts

import type { UseFetchOptions } from 'nuxt/app';

export function useApiFetch<T>(path: string | (() => string), options: UseFetchOptions<T> = {}) {
    return useFetch(path, {
        ...options,
        $fetch: useNuxtApp().$apiFetch,
    })
}
```

**Comment by dany68** [comment]
Hi,
Adding a reproduction would be difficult since it needs a backend service. I'm using laravel (with sanctum) for the authentication.

Then i simply did the files shown earlier and an useAuthStore which is a pinia store to handle the authentication.

Again everything was working fine before upgrading to 3.13, and everything still works fine while navigating client side. But refreshing the page forcing SSR i get the 500 error from the first post.

**Comment by dany68** [comment]
Hi, i succedded to make it work with the following updates:
- Using nuxtApp.runWithContext
- Copying the default options.headers is necessary (even though the ...options.headers spread operator should work). I don't know why. Any ideas ? When i console.log(options.headers) as the first line of nuxtApp.runWithContext i get the correct default options.

```
export default defineNuxtPlugin((nuxtApp) => {
    const config = useRuntimeConfig()

    const $apiFetch = $fetch.create({
        baseURL: config.public.API_URL,
        credentials: 'include',
        headers: {
            'Accept': 'application/json',
            'X-Requested-With': 'XMLHttpRequest',
            referer: config.public.APP_URL,
        },
        async onRequest({ options }) {
            await nuxtApp.runWithContext(() => {
                const token = useCookie('XSRF-TOKEN')
                if (token.value) {
                    options.headers = {
                        'Accept': 'application/json',
                        'X-Requested-With': 'XMLHttpRequest',
                        referer: config.public.APP_URL,

                        ...options.headers,
                        ...useRequestHeaders(["cookie"]),
                        'X-XSRF-TOKEN': decodeURIComponent(token.value as string),
                    }
                }
            })
        },
        async onResponseError({ response }) {
            await nuxtApp.runWithContext(() => {
                const auth = useCookie('auth')
                if (response.status === 401) {
                    auth.value = null
                    return navigateTo('/login')
                }
            })
        }
    })

    return {
        provide: {
            apiFetch: $apiFetch
        }
    }
})
```
