### ISSUE TITLE
Hydration errors on useId inside KeepAlive

### ISSUE THREAD

**Issue by Larsmyrup** [nuxt/nuxt#29656]
### Environment

Local:
------------------------------
- Operating System: Darwin
- Node Version:     v20.9.0
- Nuxt Version:     3.13.2
- CLI Version:      3.14.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.1.0
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

Stackblitz (reproduction link):
------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.13.2
- CLI Version:      3.15.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      default
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-ixfwit

Reproduction steps:

Run the project
See that there is no hydration mismatch issues on load (and reload if you wish).
Trigger a HMR update, by updating the script tag in MyComponent.vue (my go to is suffixing an 'a' to the console.log statement) and see the hydration mismatch warning, the `Hydration completed but contains mismatches`-error and notice that 'My component' is no longer visible.

Also notice you can trigger a HMR update in the `MyKeepAliveContainer.vue` component without getting the warning.

### Describe the bug

Getting a hydration error, when hot module reload reloads a component inside a component containing a slot in a <KeepAlive> tag.

### Logs

```
[Vue warn]: Hydration attribute mismatch on 
 
  - rendered on server: id="v-0"
  - expected on client: id="v-1"
  Note: this mismatch is check-only. The DOM will not be rectified in production due to performance overhead.
  You should fix the source of the mismatch. 
  at <MyComponent> 
  at <KeepAlive> 
  at <MyKeepAliveContainer> 
  at <App key=4 > 
  at <NuxtRoot>
warn$1	@	runtime-core.esm-bun…er.js?v=2c4df531:50
propHasMismatch	@	runtime-core.esm-bun….js?v=2c4df531:2170
hydrateElement	@	runtime-core.esm-bun….js?v=2c4df531:1906
hydrateNode	@	runtime-core.esm-bun….js?v=2c4df531:1747
hydrateSubTree	@	runtime-core.esm-bun….js?v=2c4df531:5279
componentUpdateFn	@	runtime-core.esm-bun….js?v=2c4df531:5297
run	@	reactivity.esm-bundler.js?v=2c4df531:195
setupRenderEffect	@	runtime-core.esm-bun….js?v=2c4df531:5441
mountComponent	@	runtime-core.esm-bun….js?v=2c4df531:5216
processComponent	@	runtime-core.esm-bun….js?v=2c4df531:5169
patch	@	runtime-core.esm-bun….js?v=2c4df531:4685
componentUpdateFn	@	runtime-core.esm-bun….js?v=2c4df531:5393
run	@	reactivity.esm-bundler.js?v=2c4df531:195
(anonymous)	@	runtime-core.esm-bun…r.js?v=2c4df531:525
callWithErrorHandling	@	runtime-core.esm-bun…r.js?v=2c4df531:197
flushJobs	@	runtime-core.esm-bun…r.js?v=2c4df531:405
Promise.then		
queueFlush	@	runtime-core.esm-bun…r.js?v=2c4df531:319
queueJob	@	runtime-core.esm-bun…r.js?v=2c4df531:314
reload	@	runtime-core.esm-bun…r.js?v=2c4df531:523
(anonymous)	@	runtime-core.esm-bun…r.js?v=2c4df531:557
(anonymous)	@	MyComponent.vue?t=1729691325127:28
(anonymous)	@	client:34
(anonymous)	@	client:218
(anonymous)	@	client:193
queueUpdate	@	client:193
await in queueUpdate		
(anonymous)	@	client:638
handleMessage	@	client:636
(anonymous)	@	client:546
dispatchEvent	@	.localservice@runtime.34c588ed.js:26
_handleMessage	@	.localservice@runtime.34c588ed.js:26
_0x578779	@	.localservice@runtime.34c588ed.js:26
Show less

.localservice@runtime.34c588ed.js:26 Hydration completed but contains mismatches.
console.error	@	.localservice@runtime.34c588ed.js:26
logMismatchError	@	runtime-core.esm-bun….js?v=2c4df531:1604
hydrateElement	@	runtime-core.esm-bun….js?v=2c4df531:1907
hydrateNode	@	runtime-core.esm-bun….js?v=2c4df531:1747
hydrateSubTree	@	runtime-core.esm-bun….js?v=2c4df531:5279
componentUpdateFn	@	runtime-core.esm-bun….js?v=2c4df531:5297
run	@	reactivity.esm-bundler.js?v=2c4df531:195
setupRenderEffect	@	runtime-core.esm-bun….js?v=2c4df531:5441
mountComponent	@	runtime-core.esm-bun….js?v=2c4df531:5216
processComponent	@	runtime-core.esm-bun….js?v=2c4df531:5169
patch	@	runtime-core.esm-bun….js?v=2c4df531:4685
componentUpdateFn	@	runtime-core.esm-bun….js?v=2c4df531:5393
run	@	reactivity.esm-bundler.js?v=2c4df531:195
(anonymous)	@	runtime-core.esm-bun…r.js?v=2c4df531:525
callWithErrorHandling	@	runtime-core.esm-bun…r.js?v=2c4df531:197
flushJobs	@	runtime-core.esm-bun…r.js?v=2c4df531:405
Promise.then		
queueFlush	@	runtime-core.esm-bun…r.js?v=2c4df531:319
queueJob	@	runtime-core.esm-bun…r.js?v=2c4df531:314
reload	@	runtime-core.esm-bun…r.js?v=2c4df531:523
(anonymous)	@	runtime-core.esm-bun…r.js?v=2c4df531:557
(anonymous)	@	MyComponent.vue?t=1729691325127:28
(anonymous)	@	client:34
(anonymous)	@	client:218
(anonymous)	@	client:193
queueUpdate	@	client:193
await in queueUpdate		
(anonymous)	@	client:638
handleMessage	@	client:636
(anonymous)	@	client:546
dispatchEvent	@	.localservice@runtime.34c588ed.js:26
_handleMessage	@	.localservice@runtime.34c588ed.js:26
_0x578779	@	.localservice@runtime.34c588ed.js:26
```

**Comment by danielroe** [comment]
Would you see if you can reproduce this in pure Vue SSR without Nuxt ([reproduction sandbox](https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter)), and if so, raise [there](https://github.com/vuejs/core/issues/new/choose)? 🙏

**Comment by Larsmyrup** [comment]
> Would you see if you can reproduce this in pure Vue SSR without Nuxt ([reproduction sandbox](https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter)), and if so, raise [there](https://github.com/vuejs/core/issues/new/choose)? 🙏

Yes i'll try that 👍 In my head SSR issues still equals Nuxt issues - but you're right the issue seems to be upstream. Thanks!

**Comment by danielroe** [comment]
Thank you for checking ❤
