### ISSUE TITLE
Layers are automatically extended without specifying the `extends` option

### ISSUE THREAD

**Issue by alexshink** [nuxt/nuxt#29664]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.12.0
- Nuxt Version:     3.13.2
- CLI Version:      3.14.0
- Nitro Version:    2.9.7
- Package Manager:  npm@8.15.0
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

[CodeSandbox](https://codesandbox.io/p/devbox/competent-hodgkin-mtn2mn)

1. Create an empty Nuxt project (`npx nuxi@latest init <project-name>`)
2. Inside the project, create a `layers` directory with the following structure:
```
- admin
  - nuxt.config.ts
  - components
    - AdminButton
      - AdminButton.vue
- catalog
  - nuxt.config.ts
  - pages
    - catalog
      - index.vue
```
3. Contents of the `layers/catalog/pages/catalog/index.vue` file:
```
<template>
  <AdminButton />
</template>
```
4. Contens of the `app.vue` file:
```
<template>
  <div>
    <NuxtPage />
  </div>
</template>
```
5. In the browser, go to the `/catalog` page
6. Firstly, the page will already be available, secondly, the component from the admin layer will be rendered on it. At the same time, I did not change the configs (global and in layers), accordingly, the `extends` option was not specified anywhere.

### Describe the bug

Hello! I just came to Nuxt, so I do not exclude that the problem may be in my understanding. But I studied many issues, discussions and articles, and, of course, first of all, all the documentation on `layers` and came to the conclusion that this is a bug. As far as I understood, layers should be extended with the extends option in the corresponding configs (layer config or root config), but my layers work automatically, I used many layers, and they have many pages and components - the app and all layers automatically work with each other's components and pages without explicitly specifying the `extends` option. Either I really screwed up and didn't understand something while studying the layers (for which I apologize in advance), or there is some kind of error here.

**Comment by xjccc** [comment]
[layers usage](https://nuxt.com/docs/getting-started/layers#usage)

![Image](https://github.com/user-attachments/assets/21a1ebe4-c167-41e9-a188-3e397ddf308b)

Is this description?

**Comment by alexshink** [comment]
> Is this description?

Ah, layers are automatically extended if they are in the `layers` directory, so I can put them in any other directory with a custom name and then manually extend the layers. Well, what can I say, my mistake, thanks for pointing that out, now everything is clear!

Then a purely technical question: does it affect performance in production/deployment if all layers are left in `layers` directory?

**Comment by xjccc** [comment]
> > Is this description?
> 
> Ah, layers are automatically extended if they are in the `layers` directory, so I can put them in any other directory with a custom name and then manually extend the layers. Well, what can I say, my mistake, thanks for pointing that out, now everything is clear!
> 
> Then a purely technical question: does it affect performance in production/deployment if all layers are left in `layers` directory?

emm.. I have no idea about this.. I have no this scene..

**Comment by alexshink** [comment]
> emm.. I have no idea about this.. I have no this scene..

Ok, thank you. Sorry for wasting your time.
