### ISSUE TITLE
puppeteer-extra not working

### ISSUE THREAD

**Issue by zukreindev** [nuxt/nuxt#29686]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.16.0
- Nuxt Version:     3.13.2
- CLI Version:      3.15.0
- Nitro Version:    2.9.7
- Package Manager:  yarn@1.22.22
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

import { resolve } from 'node:path';

import puppeteer from 'puppeteer-extra';
import StealthPlugin from 'puppeteer-extra-plugin-stealth';
import sharp from 'sharp';

const config = useRuntimeConfig();

export async function installChapterWithManga(
    mangatrLink: string,
    fansubId: string,
    slug: string,
    chapter: number,
) {
    if (!mangatrLink || !fansubId || !slug || !chapter) return;

    if (!mangatrLink.includes('***')) return;

    puppeteer.use(StealthPlugin());

    puppeteer
        .launch({
            headless: false,
        })
        .then(async (browser) => {
            const page = await browser.newPage();

            await page.goto(mangatrLink);
            await page.waitForNavigation();

            await new Promise((resolve) => setTimeout(resolve, 1000));

            const images = await page.$$eval('img', (elements: any) =>
                elements
                    .map((el: any) => el.src)
                    .filter((x: any) => x)
                    .filter((x: any) =>
                        x.startsWith('***'),
                    ),
            );
            for await (const [index, image] of images.entries()) {
                const filePath = resolve(
                    config.relativeCdnPath,
                    slug,
                    chapter.toString(),
                    index + 1 + '-' + fansubId + '.jpeg',
                );

                const response = await fetch(image);
                const blob = await response.arrayBuffer();

                await sharp(blob).jpeg({ quality: 75 }).toFile(filePath);
            }

            await browser.close();
        });
}

### Describe the bug

The project has a scrape function where I use puppeteer-extra and puppeteer-extra-plugin-stealth, but the scrape function throws the following error.

### Logs

 WARN 
          A plugin listed 'puppeteer-extra-plugin-stealth/evasions/chrome.app' as dependency,
          which is currently missing. Please install it:

          yarn add puppeteer-extra-plugin-stealth

          Note: You don't need to require the plugin yourself,
          unless you want to modify it's default settings.

 ERROR  [nitro] [unhandledRejection] Could not dynamically require "puppeteer-extra-plugin-stealth/evasions/chrome.app". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.

  at require (node_modules\nuxt\dist\core\runtime\nitro\error-dev.js:5:2)
  at PuppeteerExtra.resolvePluginDependencies (node_modules\puppeteer-extra\dist\index.cjs.js:299:23)
  at PuppeteerExtra.launch (node_modules\puppeteer-extra\dist\index.cjs.js:117:14)
  at installChapterWithMangatr (server\utils\scraper.ts:22:1)
  at async /C:/Users/zukreindev/Desktop/mangitto/node_modules/h3/dist/index.mjs:1978:19
  at async Object.callAsync (/C:/Users/zukreindev/Desktop/mangitto/node_modules/unctx/dist/index.mjs:72:16)
  at async Server.toNodeHandle (/C:/Users/zukreindev/Desktop/mangitto/node_modules/h3/dist/index.mjs:2270:7)

**Comment by IqroNegoro** [comment]
any update...?

**Comment by joris-gallot** [comment]
I made a reproduction: https://stackblitz.com/edit/github-n7cdeyej?file=server%2Fapi%2Fpuppeteer-test.ts

**Comment by jawa-the-hutt** [comment]
This is still an issue in 2026 but I'm not sure what Nuxt can do about it? FWIW, this is my workaround.  it's ugly, but it does get you most of what you want out of that Stealth plugin by adding each sub-plugin individually.  The UserAgent subplugin has another issue entirely, but you can use the regular non-Stealth UA plugin as a replacement more or less.

```
import vanillaPuppeteer from "puppeteer";
import { addExtra } from "puppeteer-extra"; // TODO: maybe change this after this issue is resolved: https://github.com/berstend/puppeteer-extra/issues/748
const puppeteer = addExtra(vanillaPuppeteer);

import anonymize from 'puppeteer-extra-plugin-anonymize-ua';
puppeteer.use(anonymize());

// @ts-ignore
import StealthPluginChromeApp from 'puppeteer-extra-plugin-stealth/evasions/chrome.app';
// @ts-ignore
import StealthPluginChromeCsi from 'puppeteer-extra-plugin-stealth/evasions/chrome.csi';
// @ts-ignore
import StealthPluginChromeLoadTimes from 'puppeteer-extra-plugin-stealth/evasions/chrome.loadTimes';
// @ts-ignore
import StealthPluginChromeRuntime from 'puppeteer-extra-plugin-stealth/evasions/chrome.runtime';
// @ts-ignore
import StealthPluginDefaultArgs from 'puppeteer-extra-plugin-stealth/evasions/defaultArgs';
// @ts-ignore
import StealthPluginIFrameContentWindow from 'puppeteer-extra-plugin-stealth/evasions/iframe.contentWindow';
// @ts-ignore
import StealthPluginMediaCodecs from 'puppeteer-extra-plugin-stealth/evasions/media.codecs';
// @ts-ignore
import StealthPluginNavigatorHardwareConcurrency from 'puppeteer-extra-plugin-stealth/evasions/navigator.hardwareConcurrency';
// @ts-ignore
import StealthPluginNavigatorLanguages from 'puppeteer-extra-plugin-stealth/evasions/navigator.languages';
// @ts-ignore
import StealthPluginNavigatorPermissions from 'puppeteer-extra-plugin-stealth/evasions/navigator.permissions';
// @ts-ignore
import StealthPluginNavigatorPlugins from 'puppeteer-extra-plugin-stealth/evasions/navigator.plugins';
// @ts-ignore
import StealthPluginNavigatorWebdriver from 'puppeteer-extra-plugin-stealth/evasions/navigator.webdriver';
// @ts-ignore
import StealthPluginSourceUrl from 'puppeteer-extra-plugin-stealth/evasions/sourceurl';
// // // @ts-ignore
// // import StealthPluginUserAgentOverride from 'puppeteer-extra-plugin-stealth/evasions/user-agent-override';
// @ts-ignore
import StealthPluginWebglVendor from 'puppeteer-extra-plugin-stealth/evasions/webgl.vendor';
// @ts-ignore
import StealthPluginWindowOuterdimensions from 'puppeteer-extra-plugin-stealth/evasions/window.outerdimensions'

puppeteer.use(StealthPluginChromeApp());
puppeteer.use(StealthPluginChromeCsi());
puppeteer.use(StealthPluginChromeLoadTimes());
puppeteer.use(StealthPluginChromeRuntime());
puppeteer.use(StealthPluginDefaultArgs());
puppeteer.use(StealthPluginIFrameContentWindow());
puppeteer.use(StealthPluginMediaCodecs());
puppeteer.use(StealthPluginNavigatorHardwareConcurrency());
puppeteer.use(StealthPluginNavigatorLanguages());
puppeteer.use(StealthPluginNavigatorPermissions());
puppeteer.use(StealthPluginNavigatorPlugins());
puppeteer.use(StealthPluginNavigatorWebdriver());
puppeteer.use(StealthPluginSourceUrl());
puppeteer.use(StealthPluginWebglVendor());
puppeteer.use(StealthPluginWindowOuterdimensions());
// puppeteer.use(StealthPluginUserAgentOverride());
```

**Comment by TheIdealMatrix** [comment]
This is my workaround and it seems to work on the server side (AI generated code):
```ts
import type { PuppeteerNode } from 'puppeteer'
import { createRequire } from 'module'

const require = createRequire(import.meta.url)

function usePuppeteer(): PuppeteerNode {
  const puppeteer = require('puppeteer-extra')
  const StealthPlugin = require('puppeteer-extra-plugin-stealth')

  puppeteer.use(StealthPlugin())

  return puppeteer
}
```
Then use it like:
```ts
const browser = await usePuppeteer().launch()
```
