### ISSUE TITLE
Nuxt 4 layers nested composables are not defined / auto imported

### ISSUE THREAD

**Issue by alexcroox** [nuxt/nuxt#29709]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.13.2
- CLI Version:      3.14.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-mag9gj-w7fy1u?file=layers%2Fauth%2Fapp%2Fcomposables%2Fservices%2FcomposableNested.ts,app%2Fcomponents%2Ftest-nesting%2FAppComponent.vue

### Describe the bug

If you have a composable in a nested folder inside layers in Nuxt 4 (and possibly earlier?) then it will not be auto imported.

![Image](https://github.com/user-attachments/assets/d2ac6745-af3a-467c-860a-2858089e3a10)

`500  useComposableNested is not defined`

See reproduction above, if you comment out this line then the non-nested layer composable will run fine.

_app/components/test-nesting/AppComponent.vue_
```
<script setup lang="ts">
// const { isComposableNestedWorking } = useComposableNested();
``` 

### Additional context

I have tried adding this to `layers/auth/nuxt.config.ts`

```
imports: {
  dirs: ['~~/layers/auth/app/composables/services/**']
}
```

My unit tests also indicate this might also be breaking `asyncContext` in those layer nested composables. e.g they are unable to call `useNuxtApp()`, I get [nuxt] instance unavailable

**Comment by dsvgl** [comment]
Maybe with resolve?

```ts
import { createResolver } from 'nuxt/kit';

const { resolve } = createResolver(import.meta.url);

export default defineNuxtConfig({
  imports: {
    autoImport: false,
    dirs: [resolve('./app/composables/services/**')],
  },
});
```

**Comment by alexcroox** [comment]
@dsvgl thank you resolve fixed it! 

https://stackblitz.com/edit/github-mag9gj-tnstob?file=layers%2Fauth%2Fapp%2Fcomposables%2Fservices%2FcomposableNested.ts,layers%2Fauth%2Fnuxt.config.ts
