### ISSUE TITLE
After upgrade nuxt to latest version(3.7.1 to 3.13.2), Nuxt SSG site on s3 hosting break open graph tag

### ISSUE THREAD

**Issue by ciao-chung** [nuxt/nuxt#29702]
### Environment

- Nuxt 3.13.2
- Node.js 20
- web(s3 website / ec2) 

### Reproduction

**URL**
 
- [http://nuxt3-demo.s3-website-ap-southeast-1.amazonaws.com/](http://nuxt3-demo.s3-website-ap-southeast-1.amazonaws.com/)
- [https://nuxt3-demo.ciao-chung.com/](https://nuxt3-demo.ciao-chung.com/)

**og debugger result**

- [og debugger - s3 site](https://developers.facebook.com/tools/debug/?q=http%3A%2F%2Fnuxt3-demo.s3-website-ap-southeast-1.amazonaws.com)
- [og debugger - ec2 site](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fnuxt3-demo.ciao-chung.com)

![](https://github.com/ciao-chung/nuxt3-s3-web-issue/blob/master/images/og-debugger-s3.png?raw=true)

![](https://github.com/ciao-chung/nuxt3-s3-web-issue/blob/master/images/og-debugger-ec2.png?raw=true)

### Describe the bug

My nuxt 3 SSG site had been run stability on s3 hosting, and og tags also can be detected by og debugger.

Afert upgrade nuxt version with [npx nuxi upgrade](https://nuxt.com/docs/api/commands/upgrade) command, og tags can’t be detected by og debugger.

Some og tag are missing, html content are incomplete.

But when I use browser view source code, og tags are all exist and correct.

And then I put same site artifacts to aws ec2, and try og debugger again, it work, I have no idea what happend on s3 website.

Below is my s3 website configuration

![https://raw.githubusercontent.com/ciao-chung/nuxt3-s3-web-issue/refs/heads/master/images/s3-web-configuration.png](https://raw.githubusercontent.com/ciao-chung/nuxt3-s3-web-issue/refs/heads/master/images/s3-web-configuration.png)

<hr>

I found og debugger and not get complete web content of s3 website([link](https://developers.facebook.com/tools/debug/echo/?q=http%3A%2F%2Fnuxt3-demo.s3-website-ap-southeast-1.amazonaws.com))

But result of ec2 is correct([link](https://developers.facebook.com/tools/debug/echo/?q=https%3A%2F%2Fnuxt3-demo.ciao-chung.com))

### Additional context

- [source code](https://github.com/ciao-chung/nuxt3-s3-web-issue/tree/master/nuxt3)
- [ec2 site artifact](https://github.com/ciao-chung/nuxt3-s3-web-issue/tree/master/ec2-site-artifact)
- [s3 web artifact](https://github.com/ciao-chung/nuxt3-s3-web-issue/tree/master/s3-site-artifact)
- In [app.vue](https://github.com/ciao-chung/nuxt3-s3-web-issue/blob/master/nuxt3/app.vue#L15-L26) I use `useSeoMeta` method to setup open graph tags

### Logs

No response

**Comment by ciao-chung** [comment]
BTW, I have try downgrade nuxt and dependencies package of nuxt. (Like `@unhead` / `@vue` / `@nuxt`)

But still can't not fix this problem, unless I use git rollback the upgrade commit history

![](https://raw.githubusercontent.com/ciao-chung/nuxt3-s3-web-issue/refs/heads/master/images/yarn.lock-diff.png)

**Comment by DrxcoDev** [comment]
Hello! After updating Nuxt 3, the OG tags are not detected on S3, even though they look fine in the source code. Check your Nuxt configuration to ensure the OG tags are generated correctly. Also, clear the S3 cache and verify the CORS settings. I hope this helps!

**Comment by ciao-chung** [comment]
Hi @DrxcoDev ,
Thanks for your response.
As shown in the picture below, I tried to set the s3 CORS settings.
But it's still not work

```json
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET",
            "POST",
            "PUT",
            "DELETE",
            "HEAD"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": []
    }
]
```

**Comment by fabianwohlfart** [comment]
Your https is not working.
The website loads infinite, yet the og:image and og:url point to the https version.

Timeout
`https://nuxt3-demo.s3-website-ap-southeast-1.amazonaws.com/`

Https content, yet the website is served only through http
`<meta property="og:url" content="https://nuxt3-demo.s3-website-ap-southeast-1.amazonaws.com">`
`<meta property="og:image" content="https://nuxt3-demo.s3-website-ap-southeast-1.amazonaws.com/_nuxt/banner.C1hfYEkf.webp">`

Fix this, clear cache and check again. I am certain this is not a Nuxt problem as the tags are generated correctly in the source code.

**Comment by ciao-chung** [comment]
Hi @fabianwohlfart ,
My s3 website don't setup https protocol.
So only can visit at [http://nuxt3-demo.s3-website-ap-southeast-1.amazonaws.com/](http://nuxt3-demo.s3-website-ap-southeast-1.amazonaws.com/)
And thank for your remind, my og:image use incorrect protocol https.
I fixed it and deploy on s3 again, but this issue still exist.

<hr> 

![Image](https://github.com/user-attachments/assets/7bfcb7e2-5fce-4376-976e-3b758884e1ff)

![Image](https://github.com/user-attachments/assets/bf3c3b58-3baf-4cfb-9cd6-75d5af085dc8)

**Comment by fabianwohlfart** [comment]
I think the 206 statuscode is worth investigating.
Look here: https://stackoverflow.com/questions/9807771/facebook-debugger-response-206
The debugger only gets the first 40kb of your page. But your og-tags are at line 481+.
Try to move the og-tags up. Or try a version without all this css in between.

**Comment by ciao-chung** [comment]
Hi @fabianwohlfart ,

I have try to deploy old version(nuxt 3.7) to s3.

[http://nuxt3.7-demo.s3-website-ap-southeast-1.amazonaws.com](http://nuxt3.7-demo.s3-website-ap-southeast-1.amazonaws.com)

As og debugger result, this old version nuxt site is resposne 206 status code too.

But it's work.

And I compare those two version(3.7.1 & 3.13.2) s3 site, their content and file size of index.html are similar.

![Image](https://github.com/user-attachments/assets/5fc5a381-ad6a-43ee-8fed-8e5f9c2af1e5)

Thanks for your suggestion, but I think http 206 status and size of page not root cause of this issue.

Because when I back old version nuxt 3.7, everything is work.

### Additional context

- [nuxt 3.7 s3 artifact](https://github.com/ciao-chung/nuxt3-s3-web-issue/tree/master/s3-site-nuxt3.7-artifact)
- [nuxt 3.7 source code](https://github.com/ciao-chung/nuxt3-s3-web-issue/tree/master/nuxt3.7)
- [nuxt 3.7 s3 website endpoint](http://nuxt3.7-demo.s3-website-ap-southeast-1.amazonaws.com)

**Comment by fabianwohlfart** [comment]
I still think that 206 is worth to look into.

This is what I think is the cause:
In Nuxt 3.7 your og images are on line ~446.
In Nuxt 3.13.2 your og-tags are on line ~481.
460 lines should roughly be 40kb.
So in Nuxt 3.7 your og-tags are within the scope of the og scraper, in Nuxt 3.13.2 they are outside.

`Nuxt 3.7`
![Image](https://github.com/user-attachments/assets/e1293f51-eed0-44e9-99a4-4cca26853c17)

`Nuxt 3.13.2`
![Image](https://github.com/user-attachments/assets/df2ca2b6-2b56-45eb-aeea-3f4d26eeebd3)

@manniL Do you know how @ciao-chung can move the og-tags added through `useSeoMeta` up?
It seems that `<style>` and `preloads` have priority to `useSeoMeta`, which causes the og-tags to appear too late in the DOM.

I would suggest to first validate my statement by removing the 
```
<style lang="sass">
@use 'assets/sass/base.sass'
@use 'vuetify/lib/styles/main.sass'
</style>
```
so your og-tags _jump up_ in the DOM, and test again.

**Comment by ciao-chung** [comment]
Hi @fabianwohlfart ,
After refer your suggestion.
I extract css in index.html to independent file, make index.html reduce size.
Then og debugger can detect og tags successfully.

Below is diff of my change.

![Image](https://github.com/user-attachments/assets/c8057adc-c5cd-4bb3-8cf7-107b8d8d49a8)

Although the problem is solved, I'm still confused.

What reason cause index.html file size increase after upgrade nuxt to latest version?

It doesn't make sense.

<hr>

I'll keep digging root cause of this issue, if I get any update, I'll love to share with you.

And thanks a lots for your help.

Have a nice day bro 🫡
