### ISSUE TITLE
Nuxt Context Contamination

### ISSUE THREAD

**Issue by mhdSid** [nuxt/nuxt#29718]
### Environment

I'm using the env within codesandbox cloud envrionnent but it can be reproduced on any environment.

### Reproduction

- Reproduction Code: https://codesandbox.io/p/devbox/nuxt-empty-pinia-state-race-condition-lv74z2?file=%2Fcomponents%2FMainContainer.vue%3A29%2C10-29%2C22

- Reproduction URL: 
     - [Unexpected behavior: with dangling store ref](https://lv74z2-3000.csb.app/WithDanglingStoreRef)
     - [Expected behavior: with accessing store ref from Nuxt plugin](https://lv74z2-3000.csb.app/WithStoreFromPlugin)

- Keep refreshing the page at a rate of 10 times per second until you see an empty store state where the elements are bordered in red.

### Describe the bug

We had this bug on production after releasing our first Nuxt3 APP. 

[Here's the target page with the deployed fix](https://gora.golf.rakuten.co.jp/lesson/school/guide/4685)

There is a page rendering a child component, both of them running in Nuxt 3 using the Composition API (or options API - it does not matter). The child component has a setup function that contains: `const store = usePostStore()` and other computed props used to display store state values on the UI.

The page component also has a setup function that contains: `const store = usePostStore()`. The page component also has an `onServerPrefetch` lifecycle hook that makes API calls on SSR. The API calls a function that goes like this:

1. Executes an async fetch operation.
2. References the store: `const store = usePostStore()`.
3. Patches the store.
4. Makes 2 other concurrent API calls async. Each call references the store after each async call is fulfilled, and then patches the store afterwards.

### More Theoretical Analysis on What's happing internally:

- [Mermaid Graphs with in-depth use case scenario trying to depict the root cause of the issue](https://mermaid-js.github.io/mermaid-live-editor/edit#pako:eNq1Wm1T2zgQ_is76dyVzKQcCfeamXamQHtwB5QSev0Q-sGRFaLBtnKSTOBK__utXvyWOLHjuP2QxvFqtS_PrlbP8LVDuE87w84PP8A04Asy84SCm5PbCH8AkPHkTnjzGVwJPgloOL7tuG8wIjTyBOO3nS9OGMBnghLFeAQ3R-mPb8dHgi8kFXBN_42pVF_g9es3cDS-jB8VjEbX2fp0O_wVt8JPePdAIwXnnM_zGwEcGSXHXy_pItELxzxS9FF9y4kdG7GT8VnEFPMC9h-FKxYxD0aKC_plRfLd-JiHcx7pTS94HCkW3eWlUgvfXp2hhfgJx14QyKJxACdG2_v-OJGAfqnAIBMYlAocZgKHRYH3fSPxZ3-sY2D8wUhMqaARoUuiAys6qCF6aEUPq0X_tAac9sdW7MpTZLYkYjc-HWwQsRueHq4ToZFfloB_YooJwE80z0PQPTD1tJyF0z682n_15vksIjySTCqd1k9z31NUPsNZLtcjhb8tLR5sXFyUPawve2b8fcYdAwonnvKe4a_xpzN0I_KpWOd59t18W67PEQ9iXXgYkjOfekH6Q2V5_l1enucV5TmoqM9zo-Wiqj4vjNjleIR1huHYgLdLI_mhRiVbnVdbVPJgUyl_MOo-ri9lJ7C-lJ3A-lL-2IcfUYH-OHTowD6cC8QzXBYW2GBcFypv2SwnUyi9ZcucTKH2isatr75BZflda7eutVvXzq3jkuoYbS7DkV15roWVq5ebpvVCAk_KEzqFuTvFpiwIhi-mU4L_elIJfk_14wH-c4-vFsxXs-Fg_tgjPOBi-ALfLauTrtqcPkK0xlTfwcHvW-pjGBChPIxIopD-Mp3mFB4cpI9rFOZVJsd34nbhXdIpUieKb0fXPcxyT0M3tWpZYqBFBlpmkBcyYlIXP0L4hHkInTBN0BwHDUbYXDv5CdtP6YsLj0WICXJf-tb0HtN6StcyIrjy5P3HmMa0VCRgk_ghDRUYO169eZPuOkxbVx9s3zGB2rth5B763XRdugAXp0YN4RJHK8CWS9kDlXB6c3OFT0ZfujKV1tsWDB7CFcdOsbfwmG5dMOUCzn76kNu0IF40-104x3KsMM8J1fIeAUSolNoQ6_2g3Pu8DY-UxFi0EHDPP8fFPNqrDJn2uVTGpGoIIo4-MzVzJ8neXhewOUwpti3dGfa62QZmQVlUBQ-ZpEAExZbigxf5mJU73ZUE9VeWu30vqVpwcQ98ToUFQch1UhUHNUNNPsw5D3LBXBOULKJv5VNEbMNzIT3s1spYERKp792GmIqsZ_VwpeOOTxLm2FW1hiSaU_w_s2VdFHMoyldD0ZFaiBxgPWLCRDzPVeTP3erwu2KMcCwpLchtcZlTPqI4_PkFuAM1RaBNnCDGIrkJ23pUSuOZj0iC1XVhPeJqljiCrvEFzLwHmuYoWsaurIFTj1CdbZ8Z40_oAw34PNRntI31L92a7aUElAka8jFdj5SJ9i7xIfFyO7S6qEoL00k-XOsMeM8EwsxJvZSrQQSp8GhOgrxOjcNEpidb7wWSZ8vrNo4B6GkpoDnY_9rdOsrLbWHFzFV3id1WB1GHplYCEjQLmg1IOgOpM1VeOxjgpumSl7JEbWVpmvEWoYCDCcl6v66y2rZYHXM9IuPSBZ5CBaP8Yuuq7P96oF3N5W-757IauVkq93waeE_U77aSzv726ew3SuexwLZE8JbLpNQuH5t82q4uTZpEcnPaIat9l1XYk_qu3q3OrvNkX1_xTAe1Sf19zbm0lLjVNu5OD2yCakaZyOuvlbCLOFAMUw1hIiThXy1moY81T2IhdFPPnw11ApbGV6LuR9Q3QZRRGpU06E1qwljZXYETbYp2lcdozhR9n1OiizS5QNzWqHJbU0tjwR_d2s0VMy6LrcKO79ouixG5FvKbCyc5zWy0ViFfM2DSuDjBdh2iKSxHN1WtN4OEsd1nU5O8tElgK5lS8kSCJJu5UF9y3A9HXZHp7eWvOI4kyvNAm5bmRp0lVggHBo-k-HctWoJnippYmf06uu1g_SEF9BBuZhSosS9A-_Ql2HUhz4hm2O_BYsbQCOJFEOihHsf7LFrOCGlqZ6nNyP2KmK0M4hl3BUcU5zXGxVYKLGOmEOVGSaLR2IWeaawkEujXBIvK9hCLoNCLvDsaWhAEDFegIgwMhiJzCsfIyA9Qy_52lpkdclQoQf2uSdt5dKVLayhLhrdlm5FpHBHbFvKZsJazot4eUImNgmFLfAI_Nh0E8bhtOv6J6UuZo7Jg9IQ7hFvpOKF6mkOznuBGoACakigWmWJpFINvhHNhR_OVW-VeWge3i70rJjh1mRvC5xmNVsOt8ZFMQSwqAXlPw6XE7pDdzRQeTmrJbNBnXmw5vZ5JmTm2TNbwAMKKyTcrc66aHK3QQ-Xc0AZiaAMrVEUJreWDGpFBDZmgpjRQTQ6oDgHUiP3ZnvqpvF83J312YXx2ont24HqaEz27sDytUTy78DsNyZ1mzM7WsNua02lO6LTF5uxK5VR3iY1X0kYMTjv0TRvczW7ETXPWpnZM2-BrWiBrWmFqdqZpdudodiRoGqetITXTAi_TCinTFiPTHh3TjItpmYj5PixMGxRM6_xLM_LlezEv7dAuO3EurREunV4npCL0mN8Zdr5qxbcdxFpIbztD_Op74v62cxt9QzkvVnyEA2VnqERMex3B47tZZzjFcwmf7B3MXacSEYqHPxcX9k_9zF_8ffsfkFVhxA)
- Please trying uncommenting some of the graphs and commenting the rest to check different perspectives.

### Here is the catch
Accessing the page shows the post data correctly from the store state in the child component template. Sometimes, though, after refreshing the page at a fast rate, the child component renders an empty/stale state of the store. I could reproduce this in two different apps by having this code flow and logic steps.

### How we quickly solved this?
In the async function that gets triggered in the `onServerPrefetch` of the page component, we moved the store ref to be hoisted at the root of the function.

### Other solutions:
- Seems to be that somehow the context is lost when this line is executed in the child component `const store = usePostStore()`, which can happen when the micro-task queue has unfulfilled requests.
- Delaying the rendering of the child component until the data is fully loaded from the page, can solve it, as it ensures that the `const store = usePostStore()` gets the resolved context that was updated from/after any async operation
- Accessing store reference through a plugin [like here](https://lv74z2-3000.csb.app/WithStoreFromPlugin):
```
import { defineNuxtPlugin } from "#app";
import { usePostStore } from "../store";

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.provide("store", usePostStore());
});
```
- On SSR, the flow is ok, but on the client the state is lost

### Additional context

Tried bumping version of the following dependencies but it did not solve the issue:
- Node
- Nuxt
- Vue
- Pinia

### Logs

- For SSR logs: please check the console here: https://codesandbox.io/p/devbox/nuxt-empty-pinia-state-race-condition-lv74z2?file=%2Fcomponents%2FMainContainer.vue%3A29%2C10-29%2C22

- For Client side logs: https://lv74z2-3000.csb.app/main

**Comment by mhdSid** [comment]
Another solution would be getting store instance wrapped around `runWithContext` within any async function that is invoked from within a `runWithContext` like this: `const store = await ctx.runWtihContext(() => useStore())`

**Comment by mhdSid** [comment]
After investigating and trying to wrap the usage of `usePostStore` around `runWithContext` in all async methods that get execute within a call to `runWithContext`, the store state seems to be working as expected and it solve the issue of pinia state being used from a different nuxt context.

Issue mentioned here: https://nuxt.com/docs/api/composables/use-nuxt-app#runwithcontext

Furthermore, I would like to ask if this can still be considered a bug? 

It seems that we are forced to wrap any async operation around `runWithContext` and this affects code cleanliness and readability. 

Why can't we just work with one `runWithContext` that's invoked from the component? 

Additionally, even if we invoke one `runWithContext` from the component, and if the corresponding async function contains other async operations that rely on the Nuxt context, somehow, they also need to be wrapped around `runWithContext`, which is undesirable.

**Comment by danielroe** [comment]
This is unfortunately not a bug and is a consequence of how pinia is implemented. I would like to see if pinia can implement some handling for this as it's a recurring issue with async server actions and not something Nuxt can solve on our end.

cc: @posva - maybe we can have a brainstorm about this.

**Comment by posva** [comment]
This is related to how `inject()` works and it's a design issue. If https://github.com/tc39/proposal-async-context moves forward it can be improved but I don't think this can be improved natively. Vue also needs a similar approach if you manually write a `setup()` function
Pinia already has docs for this (usage outside of components)
