### ISSUE TITLE
Pre-transform error: Failed to parse source for import analysis because the content contains invalid JS syntax

### ISSUE THREAD

**Issue by brokuka** [nuxt/nuxt#29733]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.11.0
- Nuxt Version:     3.13.2
- CLI Version:      3.15.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.12.2
- Builder:          -
- User Config:      default
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

nuxt cli (fresh build)

### Describe the bug

Recently I noticed that an error is displayed in a clean build, at the bottom I posted a screenshot of the spam error

### Additional context

![Image](https://github.com/user-attachments/assets/43159d8a-1f1a-4fc7-8313-b67baaaf3c43)

**Comment by brokuka** [comment]
same issue with clean cache, still can't imagine how to fix that

**Comment by brokuka** [comment]
don't know why buy seems problem about `pnpm`, change to yarn (for example) solves problem

**Comment by danielroe** [comment]
In that case you can try explicitly installing `vue` - but it's impossible to say for sure as there's no reproduction.

**Comment by brokuka** [comment]
![Image](https://github.com/user-attachments/assets/856255d1-b471-46a8-9d14-4a3436a3b1a5)

Maybe problem with vite, seems strange. Almost everywhere using `pnpm@9.12.3`. 😅

**Comment by brokuka** [comment]
In case anyone who reaches this problem, temporary "fix" is turn off vite server `preTransformRequests`.

**Comment by brokuka** [comment]
I do not know why, problem is solved.
