### ISSUE TITLE
The error occurs when trying to open a link with target="_blank" in the Telegram browser.

### ISSUE THREAD

**Issue by artem-kostylev** [nuxt/nuxt#29743]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.12.0
- Nuxt Version:     3.13.2
- CLI Version:      3.15.0
- Nitro Version:    2.9.7
- Package Manager:  bun@1.1.24
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxtjs/tailwindcss@6.12.2, shadcn-nuxt@0.10.4
- Build Modules:    -
------------------------------

### Reproduction

You can create an empty project with two pages, and on one of the pages, add a link to the other page with target="_blank". Then try clicking on it in Telegram web browser.

### Describe the bug

When clicking on a link with target="_blank", it returns raw HTML instead of the rendered page, as shown in the video.https://github.com/user-attachments/assets/09445558-0c7c-4209-adee-326d5ee18b7d

**Comment by danielroe** [comment]
I feel this is likely related to your deployment provider. Perhaps it is not returning the correct content-type header?

**Comment by artem-kostylev** [comment]
> I feel this is likely related to your deployment provider. Perhaps it is not returning the correct content-type header?

Thank you for your response. I'm running Nuxt locally with nuxt dev --host. I open a link from a Telegram chat to the site, then try to click on a link on the page with target="_blank", but it returns raw HTML.

video: https://github.com/user-attachments/assets/7111dba5-de5c-4170-a4b0-8d09edeca26b

project example: https://stackblitz.com/edit/github-qpi351

**Comment by alexgbirdie** [comment]
same problem

**Comment by danielroe** [comment]
let's track upstream in https://bugs.telegram.org/c/46110.

thank you for your investigation and report 🙏
