### ISSUE TITLE
Named layout if condition is always false in SSR when set

### ISSUE THREAD

**Issue by JPeer264** [nuxt/nuxt#29751]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.20.4`
- Nuxt Version:     `3.13.2`
- CLI Version:      `3.15.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `yarn@1.22.19`
- Builder:          `-`
- User Config:      `default`
- Runtime Modules:  `@nuxt/devtools@1.6.0`, `nuxt-windicss@2.6.1`, `@nuxtjs/i18n@8.5.5`
- Build Modules:    `-`

and
- Vue: `3.5.12`

### Reproduction

Codesandbox: https://codesandbox.io/p/sandbox/friendly-yonath-lxrd4y

In theory following lines are important (more specifically the addition of the `if`) while having a `/layouts/custom.vue` file:

```html
<NuxtLayout name="custom">
  <template v-if="true" #header>
  <!--      ^^^^^^^^^^       -->
    Header always shown, but still shows the default in SSR
  </template>
</NuxtLayout>
```

A video:
![Image](https://github.com/user-attachments/assets/7a0a1dbe-6d36-43c3-907f-666ff739ae29)

### Describe the bug

When having an `if` condition for a named layout, the `if` condition for this slot is basically set to false and shows the default value. As soon as the CSR hits and tries to hydrate, the `if` condition hits and renders the slot correctly. That of course triggers a hydration mismatch.

You can see the behavior in the video I posted above.

### Additional context

I was upgrading from Vue@3.3.4 and Nuxt@3.6.5, where it did work properly. I am also not sure if this is a Vue issue or Nuxt, but I decided to post it here, since I encountered it in the combination of the named layouts and the `if` condition.

maybe related: https://github.com/nuxt/nuxt/issues/14950

**Comment by danielroe** [comment]
This is likely a Vue bug. Would you see if you can reproduce this in pure Vue SSR without Nuxt ([reproduction sandbox](https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter)), and if so, raise [there](https://github.com/vuejs/core/issues/new/choose)? 🙏

**Comment by JPeer264** [comment]
Alright, I tried to [reproduce it with Vue](https://stackblitz.com/edit/github-bgizhu?file=src%2Fpages%2FHome.vue) and it did work with the latest version.  However, it is a little odd, that it is still bound to the Vue version, as it apparently stopped working with Vue `3.4.32` (so everything works fine when I set Vue to `3.4.31`). 

It is actually only related to the named layout (I assume this is a Nuxt feature, please correct me if I am wrong). Once I change the named layout to a normal component it does work again: 

![Image](https://github.com/user-attachments/assets/1db5566b-8c66-4dd5-b840-c7b507f1b227)

**Comment by danielroe** [comment]
Here's the Vue-only reproduction - thank you for investigating!

https://stackblitz.com/edit/github-bgizhu-bvt2ew?file=src/pages/Home.vue,src/components/Layout.vue

I raised an issue upstream - we can track in https://github.com/vuejs/core/issues/12438.

**Comment by JPeer264** [comment]
You are amazing. Thanks for the reproduction and the issue - I would have never caught that ;)
