### ISSUE TITLE
An error occurs when importing a service that calls useRuntimeConfig() within the server/plugins directory in Nuxt 3.13.2

### ISSUE THREAD

**Issue by svenit** [nuxt/nuxt#29760]
### Environment

- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.13.2
- CLI Version:      3.15.0
- Nitro Version:    2.10.0
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      default
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-evjdra?file=server%2Fplugins%2Fscheduler.ts

### Describe the bug

The TestService class is defined with a config property initialized by calling useRuntimeConfig() in the constructor. The getConfig() method returns this config.
The TestService instance (Test) is then exported.
The plugin in server/plugins imports this service (Test) and attempts to log Test.getConfig().

**Comment by j0rgedev** [comment]
Hello @svenit. Please try to downgrade to nitropack 2.9.7 as mentioned here: https://github.com/nuxt-hub/core/issues/363#issuecomment-2453086882

**Comment by j0rgedev** [comment]
It should be fixed with nitro 2.10.1 https://github.com/nitrojs/nitro/releases/tag/v2.10.1
