### ISSUE TITLE
GET http://localhost:3000/ 503 (Service Unavailable)

### ISSUE THREAD

**Issue by beierzhijin** [nuxt/nuxt#29771]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.18.0
- Nuxt Version:     3.13.2
- CLI Version:      3.15.0
- Nitro Version:    -
- Package Manager:  pnpm@9.12.3
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxtjs/tailwindcss@6.12.2, @nuxt/content@2.13.4, @nuxt/image@1.8.1
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/beierzhijin/nuxt-website

### Describe the bug

![Image](https://github.com/user-attachments/assets/d325882a-d336-4c5c-8e8b-d55162c3077c)

**Comment by luc122c** [comment]
This is normal behaviour when the dev server is loading. The issue with your project seems to be that `@nuxt/image` is not installed. Run `npx nuxi@latest module add image` to fix that.

**Comment by luc122c** [comment]
Yes, this is the intended behaviour while the dev server is starting up.

**Comment by lixiaofa** [comment]
Please tell me why it's so slow @luc122c
