### ISSUE TITLE
UnoCSS is not working properly with Nuxt 3.14

### ISSUE THREAD

**Issue by gxres042** [nuxt/nuxt#29797]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v22.11.0
- Nuxt Version:     3.13.2
- CLI Version:      3.15.0
- Nitro Version:    2.10.2
- Package Manager:  pnpm@9.12.3
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxt/image@1.8.1, nuxt-payload-analyzer@0.1.4, @nuxt/eslint@0.6.1, @nuxtjs/color-mode@3.5.2, @unocss/nuxt@0.64.0, @nuxtjs/critters@0.7.2, nuxt-umami@3.0.2, @nuxtjs/robots@4.1.11
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/s-complex/homepage

Fork / clone this repo and run `pnpm generate && pnpm preview`.

Run `pnpm add nuxt@3.13.2` and then generate can see the correct production.

### Describe the bug

After upgrading to Nuxt 3.14.0 my UnoCSS can't scan and correctly generate CSS rulesets. Downgrade to 3.13.2 can.

**Comment by danielroe** [comment]
cc: @antfu

**Comment by danielroe** [comment]
seems a regression from #29165 - investigating

**Comment by mklueh** [comment]
I have issues with **3.14.159** and UnoCSS.

Only custom classes declared in Vue component style tags work, but using global styles directly in components do not work.

```
<template>
<div>
   <div class="text-white bg-black h-32 w-32">Not working</div>
   <div class="my-working-style">Works</div>
</div>
</template>
<style scoped>
.my-working-style{
   @apply text-white bg-black h-32 w-32;
}
</style>
```

**Comment by danielroe** [comment]
my site uses unocss + 3.14.159 and I'm not facing this issue - can you reproduce minimally?

**Comment by gxres042** [comment]
Mine working after upgrading to 3.14.159.
I think u should give a reproduction?
