### ISSUE TITLE
Missing documentation for new shared folder

### ISSUE THREAD

**Issue by matt-clegg** [nuxt/nuxt#29798]
### Describe the feature

The Nuxt docs currently have no information on the new shared folder introduced in v3.14.0. The only reference to the shared folder is in the nuxt.config section [here](https://nuxt.com/docs/api/nuxt-config#shared).

Seeing as this feature is available for use and doesn't seem 'experimental', it could be handy to get some docs for it. Unless the plan is to hold off until Nuxt 4?

### Additional information

- [x] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [x] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [x] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by adamdehaven** [comment]
I’m also trying to debug at the moment but I can’t get the shared types folder to resolve in a monorepo with Layers. Still triaging to make sure it’s not just me

**Comment by adamdehaven** [comment]
Update: the `3.14.0` release doesn't mention that the new `shared` folder is behind the `compatibilityVersion: 4` flag, but it appears [this block](https://github.com/nuxt/nuxt/blob/506333ff18c36503a1d7b88a38db15df15b00c76/packages/nuxt/src/core/nitro.ts#L71-L76) from https://github.com/nuxt/nuxt/pull/28682 actually requires it in order to enable auto-imports. 

I was able to verify locally that the `compatibilityVersion: 4` flag is in fact required.

@danielroe is this a bug (meaning the `shared` folder should be available in `3.14` without the compatibility flag), or does the release + docs page related to the new `shared` directory need to be updated/created to indicate this is a `v4` feature?

**Comment by danielroe** [comment]
You are right that this is a v4 gesture feature as is could be a breaking change for users who already have a shared folder.

**Comment by mareszhar** [comment]
Does the new shared folder only work for some predefined nested folders? (like /types and /utils)

I created a file in `/shared/constants/index.ts` and none of its exports are being auto-imported anywhere, even though my files in `shared/types/index.ts` are.

**Comment by adamdehaven** [comment]
> Does the new shared folder only work for some predefined nested folders? (like /types and /utils)

Correct! Only `shared/utils` and `shared/types` are imported automatically ([reference](https://github.com/nuxt/nuxt/blob/9bf846580630a0f79050cb9d193288bd5917cf57/packages/nuxt/src/core/nitro.ts#L71-L76))

You can manually add additional auto import directories in your Nuxt config

**Comment by mareszhar** [comment]
> Correct! Currently, only the `shared/utils` and `shared/types` directories are imported automatically ([reference](https://github.com/nuxt/nuxt/blob/9bf846580630a0f79050cb9d193288bd5917cf57/packages/nuxt/src/core/nitro.ts#L71-L76))

Thank you for the clarification and pointers! ❤ 

I'm using the `imports` key and `nitro.imports` in `nuxt.config.ts` to configure auto-imports for other subfolders in my shared folder. 

But, it'd be clearer and more consistent if Nuxt also auto-imported the exports of any top-level files inside other direct subfolders of the root-level `shared` folder.

I know there are some special protections/type constraints for the `utils` and `types` subfolders, but it'd be nice if the exports of all other subfolders inside `shared` were also auto-imported, even if not with the same level of protections/constraints.
