### ISSUE TITLE
Could not compile template - Config option template not working anymore

### ISSUE THREAD

**Issue by guska8** [nuxt/nuxt#29800]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v22.6.0
- Nuxt Version:     3.14.0
- CLI Version:      3.15.0
- Nitro Version:    2.10.2
- Package Manager:  npm@10.8.2
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Reproduction of error with nuxt 3 https://stackblitz.com/edit/github-uuytf8-ff5rwk?file=comp%2Fc2.vue,comp%2Fc1.vue,app.vue,nuxt.config.ts,comp.js.template

![Image](https://github.com/user-attachments/assets/f837611c-3846-4c4f-88e8-cca98a271d91)

___

Example working correctly with nuxt 2 - https://stackblitz.com/edit/nuxt-starter-9qz2v9?file=nuxt.config.js,comp.js.template,pages%2Findex.vue

![Image](https://github.com/user-attachments/assets/8f5a0c2d-9198-4e7b-9a2b-7c2e56f0c330)

### Describe the bug

Nuxt 3 webpack alias is not working with templates option

![Image](https://github.com/user-attachments/assets/6e063367-2794-4cd3-ac98-5f3ec5ae2d5d)

### Additional context

- Full static build

- Both nuxt 2 and 3 have components auto import disabled with `dirs: []`

- Problem ocurrs with webpack and vite

- I use templates option to import all files inside a folder easily: `import components from '~comp';` imports both c1 and c2.

**Comment by guska8** [comment]
i found the solution for this, it's a change in the behavior of the lodash/template probably.

In my template file i had a literal interpolation with local variable *file*

```
  const file = key.replace('./', '')
  components[name] = () => import('<%= options.importPath %>/' + file)
```

Just had to change to concat with + to fix

```
  const file = key.replace('./', '')
  components[name] = () => import('<%= options.importPath %>/' + file)
```

**Comment by guska8** [comment]
Reopening because i fixed the problem in my code but the error still exists

**Comment by nurgeldiserikbay** [comment]
CustomSwiper.vue. Consider restricting the plugin to particular files via options.include
[plugin inject] shared/components/main/MainHeader.vue: rollup-plugin-inject: failed to parse /var/www/almatytourism.crocos.kz/shared/components/main/MainHeader.vue. Consider restricting the plugin to particular files via options.include
[plugin inject] shared/components/main/MainFooter.vue: rollup-plugin-inject: failed to parse /var/www/almatytourism.crocos.kz/shared/components/main/MainFooter.vue. Consider restricting the plugin to particular files via options.include
[nitro]  ERROR  RollupError: shared/components/ui/UiButton.vue (1:0): Expression expected (Note that you need plugins to import files that are not JavaScript)
1: <template>
   ^
2:   <component
3:     :is="COMPONENTS[tag]"
 ERROR  shared/components/ui/UiButton.vue (1:0): Expression expected (Note that you need plugins to import files that are not JavaScript)
  at getRollupError (node_modules/rollup/dist/es/shared/parseAst.js:396:41)
  at ParseError.initialise (node_modules/rollup/dist/es/shared/node-entry.js:13281:28)
  at convertNode (node_modules/rollup/dist/es/shared/node-entry.js:14992:10)
  at convertProgram (node_modules/rollup/dist/es/shared/node-entry.js:14235:12)
  at Module.setSource (node_modules/rollup/dist/es/shared/node-entry.js:15978:24)
  at async ModuleLoader.addModuleSource (node_modules/rollup/dist/es/shared/node-entry.js:[198](https://gitlab.com/crocos.kz/almatytourism-front/-/jobs/8303982059#L198)56:13) 
 ERROR  shared/components/ui/UiButton.vue (1:0): Expression expected (Note that you need plugins to import files that are not JavaScript)

I get same error when trrying to build for production.

**Comment by danielroe** [comment]
I've updated your code [here](https://stackblitz.com/edit/github-uuytf8-sb9a5e?file=comp/c2.vue,comp/c1.vue,app.vue,nuxt.config.ts,comp/.dist/index.js) to point to the correct path + write the file to disk - and indeed the template is being written correctly.

However, `require.context` isn't valid and is throwing an error, but that's an issue with your code or webpack. The options are working as expected.

Note that I would recommend instead using `addTemplate` within a module, as they are really meant for virtual files within the `.nuxt/` directory.

**Comment by guska8** [comment]
Thank you dainelroe for taking the time to look into my issue. I managed to fix my code adding defineAsyncComponent to the template

```
components[name] = defineAsyncComponent(() => import('<%= options.importPath %>/' + file))
```
and a combination of addTemplate and extendWebpackConfig

```
import { defineNuxtModule, addTemplate, extendWebpackConfig } from '@nuxt/kit'
import { readFileSync } from 'fs'

export default defineNuxtModule({
  setup () {
    const data = readFileSync('./lib/buildTemplates/pageComponents.includes.js.template', { encoding: 'utf8', flag: 'r' })
    let parsedContent = data.replaceAll('<%= options.importPath %>', '~/components/common')
    parsedContent = parsedContent.replaceAll('<%= options.recursive %>', 'false')

    addTemplate({
      dst: './components/common/.dist/index.js',
      filename: 'index.mjs',
      getContents: () => parsedContent,
      write: true
    })

    extendWebpackConfig((config) => {
      config.resolve.alias['~includes'] = '~/components/common/.dist'
    })
  }
})
```
