### ISSUE TITLE
$fetch cannot carry 'Authorization'

### ISSUE THREAD

**Issue by zoushusong** [nuxt/nuxt#29815]
### Environment

Nuxt project info:                                                                                                                                 17:38:58

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.16.0
- Nuxt Version:     3.14.0
- CLI Version:      3.15.0
- Nitro Version:    2.10.3
- Package Manager:  npm@10.9.0
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxt/image@1.8.1, @nuxtjs/tailwindcss@6.12.2, @vueuse/nuxt@11.2.0, @pinia/nuxt@0.5.5, @pinia-plugin-persistedstate/nuxt@1.2.1
- Build Modules:    -
------------------------------

```
{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "dependencies": {
    "@nuxt/image": "^1.8.1",
    "@pinia-plugin-persistedstate/nuxt": "^1.2.1",
    "@pinia/nuxt": "^0.5.0",
    "@vueuse/core": "^11.2.0",
    "@vueuse/nuxt": "^11.2.0",
    "crypto-js": "^4.2.0",
    "nuxt": "^3.14.0",
    "pinia": "^2.2.6",
    "vue": "latest"
  },
  "devDependencies": {
    "@nuxtjs/tailwindcss": "^6.12.2",
    "daisyui": "^4.12.14",
    "sass-embedded": "^1.80.4"
  }
}
```

### Reproduction

```
export default (params_object) => {
        const res = new Promise((resolve, reject) => {
                $fetch( params_object.url,  {
                method: params_object.method ?? "GET",  
                query: params_object?.query ?? null,    
                body: params_object?.body ?? null,      
                params: params_object?.params ?? null, 

                onRequest({ request, options }) {
                    options.headers = options.headers || {}                    
                    const loginStore = useLoginStore()
                    
                    options.headers.Authorization =  `Bearer ${loginStore.userInfo?.access_token ?? null}`
                    console.log('options.headers.Authorization',options.headers.Authorization);
                   
                },

                onRequestError({ request, options, error }) {
                    
                    console.log("服务器链接失败!",error)
                   
                    reject(error)
                    
                },
                onResponse({ request, response, options }) {
                    
                    resolve(response._data)
                },
                onResponseError({ request, response, options }) {
                    if(response.status === 401){
                      
                        const router = useRouter()
                        const loginStore = useLoginStore()
                        loginStore.setUserInfo({})
                        router.push('/login')
                    }
                    else if(response.status === 403){                        
                        const router = useRouter()
                        router.replace('/')
                    }
                    reject(response._data)
                }
            },

        ).catch(err=>{
           
            reject(err)
        })
    })
    return res;

}

```

### Describe the bug

Using  **$fetch** , via the options : **header.Authorization** carries the JWT access_token, but the Authorization is not carried properly.

![Image](https://github.com/user-attachments/assets/87e0a769-3e49-45e7-a8d4-43c29d7fa941)

### Additional context

I can use this ‘package-lock.json’ to carry Authorization normally, but I don't know which package caused it to not carry properly.
[https://github.com/zoushusong/somebugs/blob/main/package-lock.json](url)

![Image](https://github.com/user-attachments/assets/c475a5d5-1e35-446b-9e0a-a03e56a0bec5)

**Comment by pi0** [comment]
One issue spotted:  `options.headers` is a [Headers](https://developer.mozilla.org/en-US/docs/Web/API/Headers) instance. You should use `options.headers.set(...)` instead.

**Comment by zoushusong** [comment]
> One issue spotted: `options.headers` is a [Headers](https://developer.mozilla.org/en-US/docs/Web/API/Headers) instance. You should use `options.headers.set(...)` instead.

Thanks, it works

**Comment by pi0** [comment]
(np. feel free to close issue if fixed)
