### ISSUE TITLE
webpack is required for rspack builder

### ISSUE THREAD

**Issue by HigherOrderLogic** [nuxt/nuxt#29811]
### Environment

```bash
- Operating System: Windows_NT
- Node Version:     v22.7.0
- Nuxt Version:     3.14.0
- CLI Version:      3.15.0
- Nitro Version:    2.10.3
- Package Manager:  yarn@4.5.1
- Builder:          rspack
- User Config:      default
- Runtime Modules:  -
- Build Modules:    -
```

### Reproduction

A minimal Nuxt app is enough.

`package.json`:
```json
{
    "devDependencies": {
        "@nuxt/rspack-builder": "^3.12.2",
        "nuxt": "^3.14.0"
    },
    "scripts": {
        "build": "nuxt build"
    },
    "packageManager": "yarn@4.5.1"
}
```

`nuxt.config.ts`:
```ts
export default defineNuxtConfig({
    builder: 'rspack'
})
```

`app.vue`:
```vue
<template>
    <NuxtLayout>
        <NuxtPage />
    </NuxtLayout>
</template>
```

`pages/index.vue`:
```vue
<template>
    <div>
        Hello!
    </div>
</template>
```

Note that I dont have webpack installed on my machine.

### Describe the bug

When running `nuxt build`, the process throws error, say that it cant import webpack in webpackbar's file.

I have tried patching the import to `@rspack/core` but no luck.

### Additional context

N/A.

### Logs

```bash
Nuxt Build Error: Cannot find package 'webpack' imported from D:\[...]\node_modules\webpackbar\dist\index.mjs  

  at packageResolve (node:internal/modules/esm/resolve:839:9)
  at moduleResolve (node:internal/modules/esm/resolve:908:18)
  at defaultResolve (node:internal/modules/esm/resolve:1038:11)
  at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:554:12)
  at ModuleLoader.resolve (node:internal/modules/esm/loader:523:25)
  at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:246:38)
  at ModuleJob._link (node:internal/modules/esm/module_job:126:49)
```

**Comment by danielroe** [comment]
for now, you'll need to install webpack as well (it's a [peer dep of that library](https://github.com/unjs/webpackbar/blob/main/package.json#L57-L59)) and we'll look to resolve it upstream

**Comment by pi0** [comment]
webpack is needed for webpackbar as it extends `webpack.ProgressPlugin`. If rspack has similar one we can make it optional dep.

**Comment by HigherOrderLogic** [comment]
> If rspack has similar one we can make it optional dep.

Yes, it's [built-in](https://rspack.dev/plugins/webpack/progress-plugin).

**Comment by pi0** [comment]
Awesome! (do you mind to open an upstream issue? 🙏🏼 )

**Comment by pi0** [comment]
Basic support is available in [v7](https://github.com/unjs/webpackbar/releases/tag/v7.0.0)

**Comment by HigherOrderLogic** [comment]
> Basic support is available in [v7](https://github.com/unjs/webpackbar/releases/tag/v7.0.0)

Any chance you forgot to remove [the `plugin.ts` file](https://github.com/unjs/webpackbar/blob/main/src/plugin.ts)? From what I can see, that file doesn't have any use anymore.
