### ISSUE TITLE
Output Directory Content Deletion in Dev Mode

### ISSUE THREAD

**Issue by McSego1990** [nuxt/nuxt#29841]
### Environment

Nuxt project info:                                                                                    

------------------------------
- Operating System: Linux
- Node Version:     v20.18.0
- Nuxt Version:     3.14.159
- CLI Version:      3.15.0
- Nitro Version:    2.10.3
- Package Manager:  pnpm@9.12.3
- Builder:          -
- User Config:      default
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

1. Create a fresh Nuxt 3 project
2. Run pnpm build to generate the production build
3. Verify that the output directory is populated correctly
4. Run pnpm dev to start development server
5. Observe that the output directory content is deleted

This behavior can be reproduced consistently with Nuxt versions ≥3.14.0, while it works correctly with version 3.13.2.

### Describe the bug

When running the development server (pnpm dev) after a production build (pnpm build), the content of the output directory is unexpectedly deleted. This behavior prevents having both development and production versions running simultaneously, which was possible in previous versions (specifically worked in 3.13.2).

Expected behavior:
- The output directory content should persist after running pnpm dev
- Both development and production versions should be able to coexist

Actual behavior:
- Running pnpm dev deletes the content of the output directory
- Production build is lost when starting development server

Version Comparison
- Working version: "nuxt": "^3.13.2"
- Broken versions: "nuxt": ">=3.14.0"

### Additional context

- This issue appears even on fresh installations without any additional applications
- The problem is reproducible across different projects
- The build process itself works correctly; the issue only occurs when switching to development mode

Questions
- Are there any new configuration options in Nuxt 3.14.x that might affect this behavior?
- Is this a known issue or intended behavior change?
- Are there any workarounds available?

**Comment by danielroe** [comment]
This is likely a Nitro issue - would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏

**Comment by McSego1990** [comment]
> This is likely a Nitro issue - would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏
> 
> (You can also try to install a newer Nitro version on an older version of Nuxt to confirm.)


### Update: Workaround Found

After further investigation, we found that the issue can be temporarily worked around by separating development and production output directories in the Nuxt config:

```typescript
// nuxt.config.ts
export default defineNuxtConfig({
  nitro: {
    output: {
      dir: process.env.NODE_ENV === "development" ? ".output-dev" : ".output",
      serverDir: process.env.NODE_ENV === "development" 
        ? ".output-dev/server" 
        : ".output/server",
      publicDir: process.env.NODE_ENV === "development" 
        ? ".output-dev/public" 
        : ".output/public"
    }
  }
});
```

This workaround:
- Preserves the production build in `.output/` when running `pnpm dev`
- Creates a separate minimal `.output-dev/` directory for development
- Allows both production and development environments to run simultaneously

However, this seems more like a workaround than a proper solution, as:
1. The development environment shouldn't need to affect the production build output
2. Creating a separate output directory for development seems unnecessary
3. This behavior changed between Nuxt 3.13.2 (where it worked correctly) and 3.14.x

### Directory Structure Comparison

After `pnpm build`:
```
.output/
├── public/
│   └── [all production assets]
└── server/
    └── [all server files]
```

After `pnpm dev` (without workaround):
```
.output/
├── public/
└── server/
    ├── index.mjs
    └── index.mjs.map
```

After `pnpm dev` (with workaround):
- `.output/` remains intact with all production files
- `.output-dev/` contains minimal development files
