### ISSUE TITLE
Type error in custom named environment overrides in Nuxt config

### ISSUE THREAD

**Issue by benedictleejh** [nuxt/nuxt#29844]
### Environment

- Operating System: Windows 10
- Node Version:     v22.9.0
- Nuxt Version:     3.14.159
- CLI Version:      3.15.0
- Nitro Version:    2.10.3
- Package Manager:  pnpm@9.12.2
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxt/eslint@0.6.1, @nuxtjs/stylelint-module@5.2.0, @nuxt/fonts@0.10.2, @nuxt/test-utils/module@3.14.4
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-ryp8ak?file=nuxt.config.ts

### Describe the bug

When using the environment overrides in Nuxt config for custom environments (i.e. not `$development`, `$production`, or `$test`), there is a type error for the custom environment. For example, when trying to create overrides for an environment named preview, the following error appears on type checking:

```
error TS2353: Object literal may only specify known properties, and '$preview' does not exist in type 'InputConfig<NuxtConfig, ConfigLayerMeta>'.
```

There is no issue trying to use the overrides themselves, the error only appears during type checking.

### Additional context

This error also appears in the documentation for the environment overrides: https://nuxt.com/docs/getting-started/configuration#environment-overrides

**Comment by danielroe** [comment]
The example should be:

```ts
export default defineNuxtConfig({
  $production: {
    routeRules: {
      '/**': { isr: true }
    }
  },
  $development: {
    //
  },
  $env: {
    staging: {
      // 
    }
  },
})
```
