### ISSUE TITLE
vue component names are not normalised without `setup` function

### ISSUE THREAD

**Issue by MooseSaeed** [nuxt/nuxt#29843]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.12.0
- Nuxt Version:     3.14.159
- CLI Version:      3.15.0
- Nitro Version:    2.10.3
- Package Manager:  npm@10.5.0
- Builder:          -
- User Config:      default
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/MooseSaeed/upgrade-guide

### Describe the bug

In Nuxt 4, according to #28745, I believe that for the following component:
```
├─ components/
├─── ParentFolder/
├───── MyComponent.vue
```
Vue Devtools should show the component name as `ParentFolderMyComponent` instead of just `MyComponent`. 

But, the Vue Devtools always shows the component name as `MyComponent`.

**Comment by danielroe** [comment]
this seems to be the case for components which do not have a setup function.

should be a straightforward fix - thanks!
