### ISSUE TITLE
useAsyncData cannot be refreshed with ref-value in 'composables'

### ISSUE THREAD

**Issue by zoushusong** [nuxt/nuxt#29846]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.13.2
- CLI Version:      3.14.0
- Nitro Version:    -
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

[https://stackblitz.com/edit/nuxt-starter-bpyqqk?embed=1&file=pages%2Fbad.vue](url)

**good case**

```
const ss_sl = ref(0);
// useGoodSSRFetch defined in composables
const { data, error, refresh } = useGoodSSRFetch(
  'https://api.kuleu.com/api/suijimima',
  'GET',
  { ss_sl } // The parameter type is:  ref
);

const next = async () => {
  ss_sl.value++;
  console.log('count-->', ss_sl.value);

  refresh();
};
```

**bad case**
```
const ss_sl = ref(0);
// useBadSSRFetch defined in composables
const { data, error, refresh } = useBadSSRFetch(
  'https://api.kuleu.com/api/suijimima',
  'GET',
  { ss_sl: ss_sl.value } // The parameter type is:  value
);

const next = async () => {
  ss_sl.value++;
  console.log('count-->', ss_sl.value);

  refresh();
};
```

### Describe the bug

I encapsulated the useAsyncData function under ‘composables’, and the call in the vue file was successful and I got the first page data, but when I wanted to get the second page data via 'refresh', I found that if the 'page' parameter is of the value type, I can only get the first page forever, but if the input parameter is a ref, I can get the subsequent pages normally.

我在‘composables’目录下对‘useAsyncData’进行了封装，在vue文件中成功调用并得到了第1页数据，但当我想通过‘refresh’获取第2页数据时，我发现如果传入的'page'参数是值类型时，虽然我修改了'page'参数的值为2，但我仍然获取到第1页；但如果传入参数是ref类型则可以正常获取后续的页面。

**Comment by OrlS15** [comment]
This is not a bug, this is how Vue reactivity works. 
With ```ss_sl.value``` you are just passing a number not a reactive object, so you lose reactivity.
You can learn more [here](https://vuejs.org/guide/essentials/reactivity-fundamentals.html).

**Comment by zoushusong** [comment]
> This is not a bug, this is how Vue reactivity works. With `ss_sl.value` you are just passing a number not a reactive object, so you lose reactivity. You can learn more [here](https://vuejs.org/guide/essentials/reactivity-fundamentals.html).

I can understand. Actually my goodcase gets the data after passing the ref variable, but in fact I'm using useAsyncData outside of the vue file, in which case I prefer it to be handled automatically rather than passing the reactive variable to an external js.

[https://stackblitz.com/edit/nuxt-starter-bpyqqk?file=pages%2Fgood.vue](url)

**Comment by zoushusong** [comment]
> > This is not a bug, this is how Vue reactivity works. With `ss_sl.value` you are just passing a number not a reactive object, so you lose reactivity. You can learn more [here](https://vuejs.org/guide/essentials/reactivity-fundamentals.html).
> 
> I can understand. Actually my goodcase gets the data after passing the ref variable, but in fact I'm using useAsyncData outside of the vue file, in which case I prefer it to be handled automatically rather than passing the reactive variable to an external js.
> 
> [https://stackblitz.com/edit/nuxt-starter-bpyqqk?file=pages%2Fgood.vue](url)

And when I actually pass multiple parameters, I have to take out the value of refs again, just like that:
```
const format_ref_params_dic = (ref_dic)=>{
    let formated_dic = {}
    for (const key in ref_dic) {
        formated_dic[key] = ref_dic[key].value
    }
    return formated_dic

}

----

const {data, error, refresh} = await useAsyncData(()=>$fetch(url, {
        method, 
        params: format_ref_params_dic (params)   // eg: params = { page: ref<1> ,  size: ref<10>,  order: ref<'desc'> }
 })

```

 it's a bit redundant, isn't it?

**Comment by wattanx** [comment]
This is not a bug but the behavior of Vue's reactivity. The following article might be helpful:
https://antfu.me/posts/composable-vue-vueday-2021
