### ISSUE TITLE
Memory leak when using back button to switch between pages

### ISSUE THREAD

**Issue by nWacky** [nuxt/nuxt#29854]
### Environment

On stackblitz:

```
❯ npx nuxi info
[17:12:47] Working directory: /home/projects/nuxt-starter-g3rddq
[17:12:47] Nuxt project info: 

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.14.0
- CLI Version:      3.15.0
- Nitro Version:    2.10.2
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      default
- Runtime Modules:  -
- Build Modules:    -
------------------------------

[17:12:47] 
👉 Report an issue: https://github.com/nuxt/nuxt/issues/new?template=bug-report.yml
👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new
👉 Read documentation: https://nuxt.com
```

This issue is also reproducible when compiled with node `v20.18.0` and nuxt `3.14.0`

### Reproduction

Reproduction repository: https://stackblitz.com/edit/nuxt-starter-g3rddq?file=pages%2Findex.vue,pages%2Frecipes%2F[id].vue

Tested with chrome 130

#### Build the app and start it:

1. `npm run build`
2. `node .output/server/index.mjs`

The issue is reproducible in dev and production mode

#### Steps to reproduce:

Open DevTools &rarr; Memory

1. go to `/`
2. click on the first link 
  `Classic Margherita Pizza (#1)`
3. click back (browser button)

You should be on the home page

Click gc, and start profiling with _Allocations on the timeline_.

Then:

1. go to a recipe that wasn't visited before
2. go back (via a browser button)
3. repeat steps 1, 2 two-three times
4. go to `/`
5. go to page 3 (link at the top of the page)

Run garbage collection again. 
Then stop memory profiling

### Describe the bug

When navigating between home page (`/`) and recipe page (`/recipes/1`), about 1.4 MB of memory is allocated.

When clicking back (browser button), the memory is not cleared

_Allocations on the timeline_ screenshot:

<img 
  src="https://github.com/user-attachments/assets/e16e88dd-c047-47d2-9195-11a3684ee7b4" 
  title="When navigating from home page to '/recipe/id' page, about 1.4 MB of ram is allocated. 
  Then clicked back (browser button), and navigated to a recipe page and back to the home page. 
  Memory allocated for the first home page navigation is still retained. 
  For the second home page navigation new memory was allocated" />

### Additional context

On the recipe page (`/recipes/1`) data is loaded like this:

```ts
const { data: recipe, status } = await useAsyncData(
  `recipe${id}`,
  async () => {
    return await apiRecipeGetById({ id, router });
  }
  // adding lazy: true fixes the memory increase issue
  //  { lazy: true }
);
```

Adding `lazy: true` to `useAsyncData` mitigates the issue.

Removing `recipe${id}` key doesn't help in this case

---

On page 3 there is a back to main link:

```html
<NuxtLink to="/">Back to main</NuxtLink>
```

Using it clears memory allocated for the previous page

---

Adding  `pageTransition: false`, `layoutTransition: false` (as suggested [here (#15239/comment)](https://www.github.com/nuxt/nuxt/issues/15239#issuecomment-1397374756)) didn't help

**Comment by danielroe** [comment]
Would you see if you can reproduce this in pure Vue SSR without Nuxt ([reproduction sandbox](https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter)), and if so, raise [there](https://github.com/vuejs/core/issues/new/choose)? 🙏

**Comment by RokeAlvo** [comment]
> Adding `lazy: true` to `useAsyncData` mitigates the issue.

A small investigation: When first navigating to the page /recipes/:id, useAsyncData makes a request and stores the result in nuxtApp.payload.data[recipe${id}]. When going back, this data is not cleared and remains in memory. Upon revisiting the page, this data is used by the getCachedData function, which may not even exist. Indeed, it seems that if there is no getCachedData function, there’s no need to store the request results.

**Comment by nWacky** [comment]
Tried reproducing the issue without nuxt

I managed to reproduce it with vue + vue router. ([playground link](https://stackblitz.com/edit/vitejs-vite-mnz3ja?file=src%2FApp.vue))

Using `Suspense` inside `RouterView` seems to be causing the issue

This isn't an issue with nuxt then
