### ISSUE TITLE
Missing Nuxt instance when opening a page in new tab. Works with NuxtLink click.

### ISSUE THREAD

**Issue by martinszeltins** [nuxt/nuxt#29855]
### Environment

````
------------------------------
- Operating System: Linux (Ubuntu 24.04 LTS)
- Node Version:     v22
- Nuxt Version:     -
- CLI Version:      3.15.0
- Nitro Version:    -
- Package Manager:  npm@9.5.0
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------
````

### Reproduction

https://stackblitz.com/~/github.com/martinszeltins/nuxt-instance-test

### Describe the bug

I have a very simple setup with 2 pages. In my index page I have a NuxtLink to my settings page and in my settings page I have a `useSettings` composable that loads the settings for me. When I click the NuxtLink normally, the page loads fine. But when I open it in a new tab I get this error:

````
Error 500
A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug.

at Module.useAsyncData (./node_modules/.pnpm/nuxt@3.14.159_typescript@5.6.3_vite@5.4.10/node_modules/nuxt/dist/app/composables/asyncData.js:26:41)
at Module.useFetch (./node_modules/.pnpm/nuxt@3.14.159_typescript@5.6.3_vite@5.4.10/node_modules/nuxt/dist/app/composables/fetch.js:59:43)
at Module.useSettings (./composables/useSettings.ts:5:61)
at async setup (./pages/settings.js:15:180)
````

Screencast:
![Image](https://github.com/user-attachments/assets/f1b95288-fa43-432c-be12-3438b82181f5)

Turning on `experimental.asyncContext` does seem to make this error disappear but I cannot use experimental features in a large, production app. When I turn on asyncContext in my production app, then a bunch of other things seem to break.

Another way I was able to make this error go away was to remove the await before `useFetch` calls. But in that case the page opens and then data loads causing a flicker which is not what I want. On top of that, I actually DO need to wait for the data because I am working with that data when it is loaded.

I observed a similar issue in my production app but there the problem was when I would open a page twice in a new tab and sometimes it would end up without the Nuxt instance. It must be some kind of race condition or something where the Nuxt instance gets unset as it says in the docs. But turning on asyncContext is not a solution for me.

Please see the reproduction.

### Logs

```shell-script

```

**Comment by nWacky** [comment]
The Composition API and Nuxt Composables are only available during lifecycle and in same tick before any async operation.

Vue does some behind the scenes work when compiling application code to restore context after each call for `<script setup>`

More information: [runWithContext - nuxt.com](https://nuxt.com/docs/api/composables/use-nuxt-app#runwithcontext)

&ensp;

Try wrapping `useFetch` with `runWithContext` to save nuxt context between async calls:

```ts
export const useSettings = async () => {
  const nuxtApp = useNuxtApp();

  const { data: userSettings } = await nuxtApp.runWithContext(
    async () => await useFetch("/api/user/settings")
  );
  const { data: appSettings } = await nuxtApp.runWithContext(
    async () => await useFetch("/api/app/settings")
  );
  const { data: localizationSettings } = await nuxtApp.runWithContext(
    async () => useFetch("/api/localization/settings")
  );

  return {
    userSettings,
    appSettings,
    localizationSettings,
  };
};
```

`experimental.asyncContext` enables native async context to be accessible for nested composables in Nuxt and in Nitro. 

When `experimental.asyncContext` is enabled, `runWithContext` is not required

**Comment by martinszeltins** [comment]
@nWacky Thank you! This is exactly what I was looking for, it seems to have solved my problem. It's also nice because I can wrap individual calls with `runWithContext` instead of turning on `experimental.asyncContext` globally which would break my app. This is a nice workaround. 🙏🏻 

@danielroe Good point, I should definitely use `Promise.all`.
