### ISSUE TITLE
feat: Add Reactive Query Parameters in Nuxt with SSR Compatibility

### ISSUE THREAD

**Issue by OrlS15** [nuxt/nuxt#29861]
### Describe the feature

**Problem:** Nuxt currently lacks an integrated way to make query parameters reactive. Although useRoute().query provides access to query parameters, it is not reactive, which limits dynamic updates when the query parameter changes.
A common solution in Vue is to use useUrlSearchParams() from VueUse; however, this approach isn’t compatible with SSR, which is essential in many Nuxt applications.

**Proposed Solution:** Add a new composable which makes query parameters reactive without sacrificing SSR compatibility, like this:
```ts
function useRouteQuery(id: string) {
  const route = useRoute()
  const router = useRouter()
  return computed({
    get: () => route.query[id],
    set: (value) => {
      router.push({ query: { ...route.query, [id]: value } })
    },
  })
}
```

### Additional information

- [x] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [x] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [x] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by DamianGlowala** [comment]
Wondering whether you tried https://vueuse.org/router/useRouteQuery? Let us know whether this works for you.

**Comment by OrlS15** [comment]
> Have you tried https://vueuse.org/router/useRouteQuery? Let us know whether this works for you.

I didn't know it, thanks!

**Comment by matthew-dean** [comment]
I'm getting an issue where `useRouter()` is undefined sometimes in Nuxt production builds when using `useRouteQuery`

**Comment by matthew-dean** [comment]
Note to anyone else coming across this, I think you have to explicitly pass in Nuxt's route / router or you can eventually (but not always?) have issues. See: https://github.com/vueuse/vueuse/issues/4198
