### ISSUE TITLE
Hydration attribute mismatch when you use `useId` inside a component and the page contains a `useAsyncData`

### ISSUE THREAD

**Issue by JuanAndresAlborada** [nuxt/nuxt#29877]
### Environment

- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.14.159
- CLI Version:      3.15.0
- Nitro Version:    2.10.4
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      default
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-oqb1pt?file=app.vue

### Describe the bug

When you have a component that uses the `useId` hook, for example:

```vue
<template>
  <label :for="id"> Label </label>
  <input :id="id" />
</template>

<script lang="ts" setup>
const id = useId();
</script>
```

and you use this component inside a page or another component that uses the `useAsyncData` hook, for example:
```vue
<template>
  <div>
    <LabeledInput />
  </div>
</template>

<script setup>
const { data } = useAsyncData(async () => {
  return 1;
});
</script>
```

an `Hydration attribute mismatch` happens with the return of `useId`

### Additional context

This error started occurring when Nuxt starts using Vue's native `useId`.

### Logs

```shell-script

```

**Comment by mkierdev** [comment]
useId must be used in component with single-root element as stated here (blue box):
https://nuxt.com/docs/api/composables/use-id

**Comment by Perdolique** [comment]
Same in `v3.14.1592`. The component is a single-root component.

**Comment by Ark4ne** [comment]
I had the same issue with the FormGroup component from nuxt/ui.

**Comment by RokeAlvo** [comment]
The hydration error occurs only when using `useAsyncData` without `await`.

**Comment by Perdolique** [comment]
@RokeAlvo it also happens with `async` in my case.

**Comment by Perdolique** [comment]
@RokeAlvo @danielroe I investigated the issue because I don't have fetch calls w/o `await` and discovered an interesting bug using the `@nuxt/icon` module (nuxt/icon/310). So it's definitely not the Nuxt's issue.

**Comment by danielroe** [comment]
good investigation!

let's track there for now 

let me know if anything points back to nuxt at some point 🙏

**Comment by danielroe** [comment]
good investigation!

let's track there for now 

let me know if anything points back to nuxt at some point 🙏
