### ISSUE TITLE
Nuxt generate not fetching api client side

### ISSUE THREAD

**Issue by JarvisChao** [nuxt/nuxt#29878]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.17.1
- Nuxt Version:     3.14.159
- CLI Version:      3.15.0
- Nitro Version:    2.10.4
- Package Manager:  pnpm@9.10.0
- Builder:          -
- User Config:      default
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://codesandbox.io/p/devbox/rcx6q6

https://web547client.vermillion.com.tw/test/

### Describe the bug

When using "nuxt generate" to generate prerender pages, the api is not called between pages.

https://github.com/user-attachments/assets/27148279-51ee-4c41-abb7-ad05a1313fe1

**Comment by JarvisChao** [comment]
The following Reproduction uses the previously created 3.11.2 version project to modify it into the same program code structure as above. The generated file can fetch api data on the client side very well, but it will become invalid once nuxt update to the higher version.

https://codesandbox.io/p/devbox/3-11-2-worked-fine-nuxt-generate-not-fetching-api-client-side-kprlxx
https://web547client.vermillion.com.tw/test2/news

**Comment by boboldehampsink** [comment]
I have the same issue. Only 3.11 works. From 3.12 on this doesn't work anymore.

**Comment by danielroe** [comment]
This is a documented feature - and shouldn't have changed in in Nuxt v3.12 - data is not fetched when navigating to a page that was statically generated. Instead, the data that was present at generate time is used.

If you do not want this behaviour, you can set `experimental.payloadExtraction` to `false`.

**Comment by boboldehampsink** [comment]
> This is a documented feature - and shouldn't have changed in in Nuxt v3.12 - data is not fetched when navigating to a page that was statically generated. Instead, the data that was present at generate time is used.
> 
> If you do not want this behaviour, you can set `experimental.payloadExtraction` to `false`.

that worked for me, yes. But to me it wasn't clearly documented enough. I didn't understand what this feature really did. Your comment clarified this in a way that isn't in the docs.
