### ISSUE TITLE
Latest Nuxt Update Fails with Bun Package Manager and `wrangler` or `nitro-cloudflare-dev` dependencies

### ISSUE THREAD

**Issue by franklin-tina** [nuxt/nuxt#29884]
### Environment

```
------------------------------
- Operating System: Darwin
- Node Version:     v22.6.0
- Nuxt Version:     3.14.159
- CLI Version:      3.15.0
- Nitro Version:    2.10.4
- Package Manager:  bun@1.1.34
- Builder:          -
- User Config:      default
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Reproduction

_(I don't know if I can spin up a Codesandbox or Stackblitz with Bun as package manager)_

1. Create a brand new nuxt project
`npx nuxi@latest init -t v4-compat bugg`

2. Install `wrangler` and `nitro-cloudflare-dev` dependencies
`npx nypm@latest add -D wrangler nitro-cloudflare-dev`

3. Start the dev server
`bun run dev`
```bash
ERROR RollupError: [plugin impound] This module cannot be imported in server runtime. [importing node_modules/nitropack/node_modules/unenv/runtime/fetch/index.mjs from node_modules/nitropack/dist/runtime/internal/app.mjs]
```

4. To be sure, add the `nitro-cloudflare-dev` module to nuxt config and re-run `bun run dev`
```
export default defineNuxtConfig({
  compatibilityDate: '2024-04-03',
  devtools: { enabled: true },
  modules: ['nitro-cloudflare-dev'], 
  future: {
    compatibilityVersion: 4
  }
})
```

```bash
ERROR RollupError: [plugin impound] This module cannot be imported in server runtime. [importing node_modules/nitropack/node_modules/unenv/runtime/fetch/index.mjs from node_modules/nitropack/dist/runtime/internal/app.mjs]
```

### Describe the bug

After the latest Nuxt update, using Bun as package manager in a project that has `wrangler` or `nitro-cloudflare-dev` as dependencies fails with the following error:
```bash
ERROR RollupError: [plugin impound] This module cannot be imported in server runtime. [importing node_modules/nitropack/node_modules/unenv/runtime/fetch/index.mjs from node_modules/nitropack/dist/runtime/internal/app.mjs]
```

This was first reported in #29784, and I confirmed it with this [comment](https://github.com/nuxt/nuxt/issues/29784#issuecomment-2461054418).
Another user @philipp6690 also confirmed the same behavior.

>[!IMPORTANT]
>As per my testing/investigation, this only fails when using `Bun` as package manager.

Below is a video with the installation process, right up to when the error is encountered.

https://github.com/user-attachments/assets/a94531e6-cb5b-4181-90e4-70a2f62f9294

>[!NOTE]
>I omitted the `wrangler.toml` file in the video, but the issue persists with or without that file.

### Additional context

package.json
```json
{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "dependencies": {
    "nuxt": "^3.14.159",
    "vue": "latest"
  },
  "devDependencies": {
    "nitro-cloudflare-dev": "^0.2.1",
    "wrangler": "^3.86.1"
  }
}

```

nuxt.config.ts
```ts
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: '2024-04-03',
  devtools: { enabled: true },
  modules: ['nitro-cloudflare-dev'], // with or without this
  future: {
    compatibilityVersion: 4
  }
})

```

### Logs

```shell-script

```

**Comment by ItzExotical** [comment]
Can confirm.
![Image](https://github.com/user-attachments/assets/1e6e7364-e0f8-4553-a3a9-a9779c2734d9)

**Comment by philipp6690** [comment]
I have the same issue within a Turbo Monorepo using Bun as package manager. No special nitro config.
Switching from bun to pnpm & reinstalling all dependencies solved the issue for now.

**Comment by pi0** [comment]
this issue should be solved in the latest release of Nuxt. Please try to recreate your package manager lockfile.

**Comment by franklin-tina** [comment]
> this issue should be solved in the latest release of Nuxt. Please try to recreate your package manager lockfile.

@pi0  by "latest release of Nuxt", you mean **3.14.159?** 

Same issue
- `npm` and `pnpm` works well
- `bun` works, but if you install `wrangler` or `nitro-cloudflare-dev` (in my case), it fails.

https://github.com/user-attachments/assets/5507b5fa-aa5a-430a-b68b-fe60e271b78e

**Comment by philipp6690** [comment]
> I still get an error using Bun, even after upgrading to `Nuxt 3.14.159`, removing the lock file and the node_modules directory:
> 
> `RollupError: [plugin impound] This module cannot be imported in server runtime. [importing node_modules/nitropack/node_modules/unenv/runtime/fetch/index.mjs from node_modules/nitropack/dist/runtime/internal/app.mjs]`
> 
> Works fine when installing the dependencies with npm. Then I can even run the app with bun. The problem appears only when I install the dependencies with `bun install`

Exactly the same for me

**Comment by franklin-tina** [comment]
I can confirm the issue has been fixed!
Thank you 💚
