### ISSUE TITLE
Very slow dev server startup with typescript.typeCheck: true when debugger attached in VSCode

### ISSUE THREAD

**Issue by niddu85** [nuxt/nuxt#29903]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.18.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.8.2
- Builder:          -
- User Config:      routeRules, hooks, runtimeConfig, modules, delayHydration, sitemap, googleFonts, app, experimental, css, typescript, multiCache, nitro, vite, compatibilityDate
- Runtime Modules:  @nuxt/devtools@1.3.14, @nuxtjs/device@3.1.1, nuxt-multi-cache@3.1.1, @nuxtjs/google-fonts@3.2.0, nuxt-delay-hydration@1.3.6, @nuxtjs/sitemap@5.3.5
- Build Modules:    -

### Reproduction

When using 

### Describe the bug

When using

```
export default defineNuxtConfig({
  typescript: { strict: true, typeCheck: true }
})
```

on a Nuxt project with a large amount of files (~180 components and ~50 pages) the dev server launched by Visual Studio Code takes about 15 minutes to start.

Disabling typeCheck or launching "npm run dev" outside VSCode takes 30 seconds.

My launch.json file is as following:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node-terminal",
      "request": "launch",
      "name": "server: nuxt",
      "command": "npm run dev"
    },
    {
      "name": "client: chrome",
      "type": "chrome",
      "request": "launch",      
      "url": "http://127.0.0.1:3000",
      "webRoot": "${workspaceFolder}"    
    }
  ],
  "compounds": [ 
    {
      "name": "fullstack: nuxt",
      "configurations": ["server: nuxt", "client: chrome" ]
    }
  ]
}
```

### Logs

```shell-script

```

**Comment by Karthik0521** [comment]
Hi

**Comment by niddu85** [comment]
For anyone looking for a solution, I solved increasing the maximum memory for NodeJs in my launch command in package.json:
```

"scripts": {
    "build": "nuxt build",
    "dev": "cross-env NODE_OPTIONS=--max-old-space-size=4096 nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "analyze": "nuxt build --analyze",
  },
```

I added `cross-env NODE_OPTIONS=--max-old-space-size=4096` and now is lightning fast.

Since i'm on window i had to use cross-env so I had to install it with

`npm i -D cross-env`

**Comment by mikeswart** [comment]
@niddu85 I am experiencing the same slow behavior in startup. I tried your `launch.json` configuration, but noticed that I had lost the debugging experience running this way. Are you able to set breakpoints and step through code with this configuration?
