### ISSUE TITLE
Nitro 2.9.7 -> 2.10.4 breaks my Nuxt App with Route Roules behaviour

### ISSUE THREAD

**Issue by wug-ge** [nuxt/nuxt#29915]
### Environment

- Operating System: Linux
- Node Version:     v20.6.1
- Nuxt Version:     3.13.1
- CLI Version:      3.15.0
- Nitro Version:    -
- Package Manager:  npm@10.5.2
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxtjs/tailwindcss@6.12.2, @nuxtjs/google-fonts@3.2.0, @nuxtjs/i18n@8.5.6, @pinia/nuxt@0.5.5, @sentry/nuxt/module@8.38.0, nuxt-tiptap-editor@2.0.0, @nuxt/icon@1.7.4, maz-ui/nuxt

### Reproduction

Unfortunately, I can't reproduce it on Stackblitz cause the Proxy behavior in Webcontainers is strange. (or external requests are blocked maybe?)
If the issue isn't reproducible for you I'm happy to provide a Github Repository with the link or help finding the issue in Nitro, just tell me.

### Describe the bug

I have a nuxt app which makes requests like `fetch('/api/orders')` (native fetch)
The app runs on the baseUrl `/app`
After updating Nuxt (3.13 -> 3.14), the baseURL seems to be prefixed to the fetch request, could that be possible? 
I'm confused how Nuxt influences that, but if I call `fetch('/api/orders')` now my browser does a request to `fetch('/app/api/orders')`, is this intentional?

I tried changing my routeRules to proxy `/app/api/**`,  but the rewrites are not working anymore. Even though the proxy works, my backend receives the call with path `/app/api/orders` instead of `/orders` like before.

I tried downgrading Nuxt but had the same issue again.
Since nitro is doing the proxy stuff, I checked and I was using version 2.10.4.
Before, I was using 2.9.7. After forcing Nuxt to use version 2.9.7, everything works fine again though.

This seems to be a big breaking change for a minor version.

### Additional context

necessary changes in nuxt.config.ts:

`
baseURL: '/app',
routeRules: {
      "/api/**": {
        proxy: 'http://localhost:3000/**',
     }
}`

### Logs

```shell-script
There are no error logs, Nuxt is behaving like this is intentional.
```

**Comment by pi0** [comment]
Any chance you can share a github repository I can locally reproduce the issue?

**Comment by wug-ge** [comment]
@pi0 it's in dev mode, I haven't tested it deployed

**Comment by danielroe** [comment]
Let's track in https://github.com/nitrojs/nitro/issues/2881. 🙏
