### ISSUE TITLE
Style SCSS + module class names hydration mismatches

### ISSUE THREAD

**Issue by Gwynerva** [nuxt/nuxt#29917]
### Environment

Clean install with Nuxt v3.14.159 and `sass` or `sass-embedded` package installed.

### Reproduction

[Live Reproduction](https://codesandbox.io/p/devbox/practical-christian-xqjpsr?workspaceId=7adf4f3b-75da-4806-b636-6f41c56b2ba0)
 
Try to change `foo` mixin in `styles/default.scss` file: add or remove rules inside it.
On each change you will see that `app.vue` is not updated, page reload is not helping and it error hydration mismatches.

It works again if you manually change `.vue` file.
But it will break if you again change the `.scss` file.

### Describe the bug

Without `module` attribute on `<style>` Nuxt correctly handles updates to `.scss` files that are imported via `@use ...` at-rule.
However, with `module` attribte it fails to watch changes to style files or something else breaks with hydration mismatches related to hashed class names so only making manual changes to `.vue` file will re-sync the updates.

It is also not related to flexible path options when using `@use`. The bug occurs no matter how you use style files: with `.scss` extension and without it, omitting `_` at the beginning or not.

**Comment by Gwynerva** [comment]
Any comments on this one? It is really annoying to manually restart the whole Nuxt every time I change any heavily used `.scss` file...

**Comment by danielroe** [comment]
Would you see if you can reproduce this in pure Vue SSR without Nuxt ([reproduction sandbox](https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter)), and if so, raise [there](https://github.com/vuejs/core/issues/new/choose)? 🙏

**Comment by Gwynerva** [comment]
@danielroe No, on pure Vite + Vue `dev` it updates the preview on every external `.scss` file change as it should. Here is the [reproduction](https://codesandbox.io/p/devbox/nc564s) (Stackblitz for some reason can't use `sass` package and errors).

**Comment by Gwynerva** [comment]
@danielroe Yeah this happens on Vue SSR too. I created issue there. Hope it gets fixed.
Do you think switching to `rspack` which was introduced in last Nuxt update might fix that?

**Comment by danielroe** [comment]
thank you!

let's track there.
