### ISSUE TITLE
Documentation: Consistent examples for useFetchLazy

### ISSUE THREAD

**Issue by michastubi** [nuxt/nuxt#29931]
At the moment the documentation uses useLazyFetch (and useFetch with lazy option) without await (https://nuxt.com/docs/getting-started/data-fetching#lazy) as well as with await (https://nuxt.com/docs/api/composables/use-lazy-fetch). Which example is correct? Or is there any difference? But I think it would be good to agree on one way, to avoid confusion.

**Comment by ikxin** [comment]
Both examples are correct. As you said, useLazyFetch is just useFetch with the lazy option, and they are consistent with each other.

Using await will pause code execution until the fetch request is complete, which is suitable for situations where you need to handle data immediately before continuing with other operations. If you do not use await, the fetch request will be triggered, but the code will not wait for the result and will continue executing, with the component re-rendering when the data is available.

**Comment by danielroe** [comment]
`lazy` refers to client-side navigation behaviour. All useFetch and useAsyncData is awaited before sending a request. Adding an `await` in the setup function only affects whether the promise resolves before the next statement in the setup function. (In the case of lazy fetching, this does not mean the data will be present.)
