### ISSUE TITLE
Extremely slow due to the Nuxt Modules!!! I even can not bear that!

### ISSUE THREAD

**Issue by Eriktse** [nuxt/nuxt#29945]
### Environment

Nuxt project info:                                                                                                                                                                                             6:37:53 PM

------------------------------
- Operating System: Linux
- Node Version:     v20.15.1
- Nuxt Version:     3.14.159
- CLI Version:      3.15.0
- Nitro Version:    2.10.4
- Package Manager:  yarn@1.22.22
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxt/ui@2.19.2, nuxt-monaco-editor@1.3.1, @element-plus/nuxt@1.1.0
- Build Modules:    -
------------------------------

### Reproduction

This is my `nuxt.config.js`:

```js
export default defineNuxtConfig({
	devtools: { enabled: true },
	ssr:true,
	devServer:{
		host:"0.0.0.0",
		port:8001,
	},
	modules: ["@nuxt/ui", "nuxt-monaco-editor", '@element-plus/nuxt'],
	plugins:[{
		src:"~/plugins/router.js",
		ssr:false,
	}],
	alias: {
		'css':"/assets/css",
		'font':"/assets/font",
		"comps":"/components",
		"pages":"/pages"
	},
	css:["css/index.css"],
	compatibilityDate: "2024-08-05",
})
```

Very simple, but I found that in the DEV mode, devServer will load the modules' file (in the node_modules) for many times repeatly!

These 3 modules generated about 2k js files needing to load, which spend about 2minutes to load a page, but when I just modify a little bit part of my code(or just wait for some time without doing anything), the version of the js files changed, so I need to load them again!

![Image](https://github.com/user-attachments/assets/a9a33c01-f857-49ea-b173-251958af4243)

Only the js files for the 3 modules would be loaded for many times, others wouldn't.

### Describe the bug

Like the above, in the loading time, I could do nothing but waiting.There is no response after clicking the link, button or other item.

### Logs

```shell-script

```

**Comment by manniL** [comment]
Hey! This is normal in dev mode due to Vite serving everything unbundled.
It might be worth figuring out which module is causing issues you encounter (+ using Nuxt UI and Element Plus might not be the best idea) & check out https://github.com/nuxt/nuxt/issues/26211 as well.

As this is not a Nuxt issue per sé, I'll close this issue.
