### ISSUE TITLE
ERROR [worker reload] [worker init] /home/luckyloo/WebstormProjects/SurfMarket/.nuxt/dev/index.mjs failed                                     11:42:28 AM

### ISSUE THREAD

**Issue by luckyloo1730** [nuxt/nuxt#29943]
### Environment

- Operating System: Linux
- Node Version:     v18.1.0
- Nuxt Version:     3.14.159
- CLI Version:      3.15.0
- Nitro Version:    2.10.4
- Package Manager:  npm@8.8.0
- Builder:          -
- User Config:      default
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

```
import bcrypt from 'bcrypt';
import { pool } from '~/server/db';

export default defineEventHandler(async (event) => {
    const { username, password } = await readBody(event);

    // Validate input
    if (!username || !password) {
        throw createError({
            statusCode: 400,
            message: 'Username and password are required',
        });
    }

    try {
        // Check if the username already exists
        const [rows] = await pool.query('SELECT username FROM users WHERE username = ?', [username]);
        if (rows.length > 0) {
            throw createError({
                statusCode: 400,
                message: 'Username is already taken',
            });
        }

        // Hash the password
        const hashedPassword = await bcrypt.hash(password, 10);

        // Insert the new user into the database
        await pool.query('INSERT INTO users (username, password) VALUES (?, ?)', [username, hashedPassword]);

        return { message: 'User registered successfully!' };
    } catch (err) {
        throw createError({
            statusCode: 500,
            message: 'Database error: ' + err.message,
        });
    }
});
```

### Describe the bug

At one point, I just get an error message when I started Nuxt. I was working on adding a database to my website for an auth system.

` ERROR  [worker reload] [worker init] /home/luckyloo/WebstormProjects/SurfMarket/.nuxt/dev/index.mjs failed                                     11:42:28 AM`

### Additional context

I've tried to update npm, nuxt, reinstalling packages, recreating .nuxt directory. Didn't help, I still get this error.

### Logs

```shell-script

```

**Comment by moebiusmania** [comment]
+1 updating a project to `v3.14.159` gave the same error, reverted to `v3.13.2` and everything is back to normal

**Comment by luckyloo1730** [comment]
> +1 updating a project to `v3.14.159` gave the same error, reverted to `v3.13.2` and everything is back to normal

How to revert to an older version?

**Comment by moebiusmania** [comment]
@luckyloo1730 in my case I was upgrading an existing project so I just reverted the git changes, but I guess `npm i nuxt@3.13.2` to override your current version should do the trick

**Comment by yannhodiesne** [comment]
Potentially the same issue as mine here: https://github.com/nuxt/nuxt/issues/29929

**Comment by CedsTrash** [comment]
Same here, I had to revert to Nuxt 3.13.2 on all my apps to get them to work properly.

**Comment by veypi** [comment]
i got a same error.  https://stackblitz.com/edit/nuxt-starter-3dapj6?file=app.config.ts

**Comment by NaviSparrow** [comment]
I had the same issue recently. I fixed it after searching for cjs require imports in project, (like a require "fs", require "path" etc). 
I found a few, replaced them for ESM imports, then error was gone, even at the latest Nuxt and Nitro (Nuxt 3.14.1592 with Nitro 2.10.4)

Also I noticed that the error is gone after removing the field "type: module" in package.json. But this was not an option for me. 
Error occurred only in dev mode, build was fine all along.

**Comment by Tenrys** [comment]
I've commented on a different issue on another repo that was encountering the same type of error, over here:

**Comment by cernymatej** [comment]
I've created another reproduction with a very simple nitro plugin, which causes the dev server to crash with the same error message.

@pi0 could this be related to your fix here https://github.com/nuxt-hub/core/issues/363#issuecomment-2453225291 ?

It seems that whenever the value of `apiUrl` is an empty string, it crashes:
https://stackblitz.com/edit/github-mckj3fot?file=nuxt.config.ts,server%2Fplugins%2Fsetup.ts

**Comment by lpknv** [comment]
> I've created another reproduction with a very simple nitro plugin, which causes the dev server to crash with the same error message.
> 
> [@pi0](https://github.com/pi0) could this be related to your fix here [nuxt-hub/core#363 (comment)](https://github.com/nuxt-hub/core/issues/363#issuecomment-2453225291) ?
> 
> It seems that whenever the value of `apiUrl` is an empty string, it crashes: https://stackblitz.com/edit/github-mckj3fot?file=nuxt.config.ts,server%2Fplugins%2Fsetup.ts

You know that you have to provide an actual URL (e.g. new URL('http://example.com') in your example code, right?

**Comment by cernymatej** [comment]
> > I've created another reproduction with a very simple nitro plugin, which causes the dev server to crash with the same error message.
> > [@pi0](https://github.com/pi0) could this be related to your fix here [nuxt-hub/core#363 (comment)](https://github.com/nuxt-hub/core/issues/363#issuecomment-2453225291) ?
> > It seems that whenever the value of `apiUrl` is an empty string, it crashes: https://stackblitz.com/edit/github-mckj3fot?file=nuxt.config.ts,server%2Fplugins%2Fsetup.ts
> 
> You know that you have to provide an actual URL (e.g. new URL('http://example.com') in your example code, right?

Yes, I do. However, that should show a different error, shouldn't it? Something like "Invalid URL".
I think that this error is masking that one.

That wouldn't be a problem on its own, however, I am getting the `.nuxt/dev/index.mjs failed` error in one of my projects after updating too and I was hoping that by fixing it for the reproduction I provided would allow me to build the other project as well.

**Comment by lpknv** [comment]
> > > I've created another reproduction with a very simple nitro plugin, which causes the dev server to crash with the same error message.
> > > [@pi0](https://github.com/pi0) could this be related to your fix here [nuxt-hub/core#363 (comment)](https://github.com/nuxt-hub/core/issues/363#issuecomment-2453225291) ?
> > > It seems that whenever the value of `apiUrl` is an empty string, it crashes: https://stackblitz.com/edit/github-mckj3fot?file=nuxt.config.ts,server%2Fplugins%2Fsetup.ts
> > 
> > 
> > You know that you have to provide an actual URL (e.g. new URL('http://example.com') in your example code, right?
> 
> Yes, I do. However, that should show a different error, shouldn't it? Something like "Invalid URL". I think that this error is masking that one.
> 
> That wouldn't be a problem on its own, however, I am getting the `.nuxt/dev/index.mjs failed` error in one of my projects after updating too and I was hoping that by fixing it for the reproduction I provided would allow me to build the other project as well.

Now that you pointed that out, you are right, nuxt should show the actual error message.

**Comment by pi0** [comment]
I have made an upstream issue to improve debugging: https://github.com/nitrojs/nitro/issues/2927

**Comment by danielroe** [comment]
@pi0 is that something we can track there entirely, or is there something we can do within nuxt to improve this too?

**Comment by pi0** [comment]
For DX i think we can track upstream 👍🏼 

Not sure if there are known Nuxt modules that can cause the error in meanwhile worth keeping this issue open or not.
