### ISSUE TITLE
Use of eval in "xxx.vue" is strongly discouraged as it poses security risks

### ISSUE THREAD

**Issue by zoushusong** [nuxt/nuxt#29968]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.16.0
- Nuxt Version:     3.14.159
- CLI Version:      3.15.0
- Nitro Version:    2.10.3
- Package Manager:  npm@10.9.0
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxt/image@1.8.1, @nuxtjs/tailwindcss@6.12.2, @vueuse/nuxt@11.2.0, @pinia/nuxt@0.5.5, @pinia-plugin-persistedstate/nuxt@1.2.1
- Build Modules:    -
------------------------------

### Reproduction

```
if(!/^[0-9a-zA-Z\u4e00-\u9fa5]{3,30}$/.test(dat.name)){
    dat.verify_name_info = 'invalidate name'     

    eval(`${op}_name_input.value.focus()`)

    show_toast('error', 'invalidate name')
    return false
}
```

### Describe the bug

I use eval() in my code, and when I build, I get a warning message like this:
**Use of eval in "pages/manage/vedio.vue" is strongly discouraged as it poses security risks and may cause issues with minification.**

![Image](https://github.com/user-attachments/assets/3e61d864-ec0a-4095-b7a2-59837ac36add)

### Logs

```shell-script

```

**Comment by danielroe** [comment]
This isn't a bug - it's a valid warning and is coming from rollup - see https://rollupjs.org/troubleshooting/#avoiding-eval.
