### ISSUE TITLE
Shared folder - Nuxt Blog annoucement

### ISSUE THREAD

**Issue by BlueskyFR** [nuxt/nuxt#29960]
Hi!

It seems that the new **shared folder** feature annouced on the [Nuxt Blog](https://nuxt.com/blog/v3-14#shared-folder-for-code-and-types-shared-with-clientserver) requires Nuxt V4 although the post makes it seem like it is also available for V3.

Maybe either the feature should be backported to V4 or the blog post should be updated accordingly?

**Comment by manniL** [comment]
It should be available in both, V3 and V4 in "the same place".

**Comment by BlueskyFR** [comment]
Here it is.
This example runs on Nuxt V3 and the shared folder doesn't work.
https://stackblitz.com/edit/github-aasqgz-two1vs?file=app.vue
