### ISSUE TITLE
Issue with nuxi prepare: Imports work in the Playground but not in the Main Module

### ISSUE THREAD

**Issue by modigithub** [nuxt/nuxt#29979]
### Describe the bug

Hello Nuxt Team,

I am encountering an issue with nuxi prepare that affects TypeScript imports in a Nuxt module. While imports and TypeScript declarations are correctly generated and recognized in the Playground, they do not work in the main module. This leads to TypeScript errors, even though the code runs perfectly at runtime.

Problem Description:

Correct Imports in the Playground:
When using the module in the Playground, all composables and components are correctly registered in .nuxt/types/imports.d.ts. TypeScript recognizes them without any issues, and there are no error messages.

Broken Imports in the Main Module:
When using the same composables or modules in the main module, a TypeScript error occurs: "Cannot find name 'useExample'," even though the function exists and is correctly implemented. This issue happens even with proper tsconfig configuration and does not affect runtime behavior.

I added the test project.
[my-module.zip](https://github.com/user-attachments/files/17819639/my-module.zip)

Thank you for your support!

### Environment

Nuxt Version: [3.14.159]
Node Version: [v20.17.0]
Build Tool: Vite
IDE: WebStorm

### Reproduction

Steps to Reproduce:

Create a new Nuxt module:

```
npx nuxi init -t module my-module
cd my-module
npm install
```
Register a simple composable in the module, e.g., in src/runtime/composables/test.ts:

```
export const useExample = () => {
    return "This is an example composable.";
};
```
Configure the module in module.ts:

```
import { defineNuxtModule, addImportsDir, createResolver } from '@nuxt/kit';

export default defineNuxtModule({
    meta: {
        name: 'my-module',
        configKey: 'myModule',
    },
    async setup(_, nuxt) {
        const resolver = createResolver(import.meta.url);

        // Composables
        const composableDirs = [
            resolver.resolve('./runtime/composables'),
        ];
        addImportsDir(composableDirs);
    },
});
```
Use the composable inside a component within the module, e.g., in src/runtime/components/test2/index.vue:

```

<script setup lang="ts">
const example = useExample();
</script>
```
After running nuxi prepare, TypeScript in the IDE (e.g., WebStorm) shows the error:

Cannot find name 'useExample'.
Check the generated .nuxt/types/imports.d.ts file: The composable is not registered, even though it works correctly at runtime.
![Image](https://github.com/user-attachments/assets/f47a6fb4-0a65-428d-9f29-7301451fb41c)

Expected Behavior:

nuxi prepare should generate TypeScript declarations and auto-imports consistently for both the Playground and the main module.
Composables should be recognized by TypeScript without any errors.

### Additional context

Additional Context:
This issue is not limited to composables. It also affects other elements like Pinia stores, i18n functions, and any non-standard Nuxt features. These are also not correctly registered in the generated TypeScript declarations, causing errors in the development environment (IDE), even though everything works fine at runtime.
![Image](https://github.com/user-attachments/assets/9d49ab43-f95b-4f2f-b224-93f7763a0441)

### Logs

```shell-script

```

**Comment by danielroe** [comment]
The TypeScript error is correct and although it will work in your module repo, it will not work when you build + share your module. That is why we show the error.

**Comment by modigithub** [comment]
If this is not intended, could you please let me know what I need to do to make it work correctly? I can't seriously build a module with the compiler showing so many errors. How can I resolve these errors, or what exactly do I need to change? Is it really the case that Composables cannot be used within the src directory of a module?

**Comment by modigithub** [comment]
Okay, I understand. Could it be that this section in the documentation refers to this?
![Image](https://github.com/user-attachments/assets/1f26cba7-9f77-4146-a3f8-969c1ab49da1)
So, everything needs to be imported? Doesn't #build work either?
![Image](https://github.com/user-attachments/assets/1b5786a7-8a33-43aa-b4e9-f2831d7eab5a)
