### ISSUE TITLE
Custom logger function causes maximum callstack error

### ISSUE THREAD

**Issue by marr** [nuxt/nuxt#29998]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v23.1.0
- Nuxt Version:     3.14.1592
- CLI Version:      3.15.0
- Nitro Version:    -
- Package Manager:  pnpm@9.13.2
- Builder:          -
- User Config:      default
- Runtime Modules:  ()
- Build Modules:    -
------------------------------

### Reproduction

Clone https://github.com/marr/nuxt-logging-issue

Run `pnpm run build`. Quickly see logs balloon into a recursive blob of escaped `\`.

### Nuxt Logging Bug

When trying to add a custom reporter to nuxt, it appears the `args` that the logger sends into the `log` function are recursively appended to.

The custom reporter looks like this as seen in `nuxt.config.ts`:

```ts
const logger = useLogger();
logger.info('Hello from a module!');
logger.addReporter({
  log({ type, args, date }) {
    logger[type](date, JSON.stringify(args));
  }
})
```

The output quickly blows up when running `nuxt build`:

```
ℹ Building client...                                                                                                                                                           10:18:33 AM
ℹ 2024-11-20T15:18:33.287Z ["Building client..."]                                                                                                                              10:18:33 AM
ℹ 2024-11-20T15:18:33.288Z ["2024-11-20T15:18:33.287Z","[\"Building client...\"]"]                                                                                             10:18:33 AM
ℹ 2024-11-20T15:18:33.291Z ["2024-11-20T15:18:33.288Z","[\"2024-11-20T15:18:33.287Z\",\"[\\\"Building client...\\\"]\"]"]                                                      10:18:33 AM
ℹ 2024-11-20T15:18:33.291Z ["2024-11-20T15:18:33.291Z","[\"2024-11-20T15:18:33.288Z\",\"[\\\"2024-11-20T15:18:33.287Z\\\",\\\"[\\\\\\\"Building client...\\\\\\\"]\\\"]\"]"]   10:18:33 AM
[10:18:33 AM] ℹ 2024-11-20T15:18:33.291Z ["2024-11-20T15:18:33.291Z","[\"2024-11-20T15:18:33.291Z\",\"[\\\"2024-11-20T15:18:33.288Z\\\",\\\"[\\\\\\\"2024-11-20T15:18:33.287Z\\\\\\\",\\\\\\\"[\\\\\\\\\\\\\\\"Building client...\\\\\\\\\\\\\\\"]\\\\\\\"]\\\"]\"]"]
```

As show, the previous function call's arguments are appended to after each call and balloon into a max callstack error.

### Logs

```shell-script

```

**Comment by danielroe** [comment]
this is because by calling the logger for every log the logger receives, you are then triggering the reporter again, which calls the logger, etc.

this doesn't seem to be a bug within `consola` to me - you can early return if you can detect if a log has been generated from your own reporter
