### ISSUE TITLE
Custom useFetch gives warning "[useFetch] Component is already mounted, please use $fetch instead"

### ISSUE THREAD

**Issue by mklnz** [nuxt/nuxt#30000]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.15.1
- Nuxt Version:     3.13.0
- CLI Version:      3.13.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.7.0
- Builder:          -
- User Config:      compatibilityDate, devtools, modules
- Runtime Modules:  @nuxtjs/tailwindcss@6.12.1
- Build Modules:    -
------------------------------

### Reproduction

Using exact code from: https://nuxt.com/docs/guide/recipes/custom-usefetch, except no onRequest and no onResponseError handlers

### Describe the bug

I'm trying the custom useFetch example provided in the docs here: https://nuxt.com/docs/guide/recipes/custom-usefetch

```javascript
  export function useApi<T>(path: string, opts?: UseFetchOptions<T>) {
    return useFetch(path, {
      ...opts, $fetch: useNuxtApp().$api as typeof $fetch
    })
  }
```

and my api plugin is as follows:

```javascript
export default defineNuxtPlugin((nuxtApp) => {
  const api = $fetch.create({
    baseURL: 'http://localhost:3001',
  })

  return {
    provide: { api }
  }
})

```

However when I use it in call like so:
```javascript
const res = await useApi('plans')
```

I get the following in my browser console:

```
[nuxt] [useFetch] Component is already mounted, please use $fetch instead. See https://nuxt.com/docs/getting-started/data-fetching
```

### Logs

```shell-script

```

**Comment by huang-julien** [comment]
Hello we need to see at lease how you're calling useApi
