### ISSUE TITLE
Nuxt initialization npm failure

### ISSUE THREAD

**Issue by thespider911** [nuxt/nuxt#30021]
Ubuntu Linux 22
Node v22.11.0
npm 10.9.0

npx nuxi@latest init app-demo

✔ Which package manager would you like to use?
npm
◐ Installing dependencies...                                                                                                                                      9:25:33 a.m.
npm error code EAI_AGAIN
npm error syscall getaddrinfo
npm error errno EAI_AGAIN
npm error request to https://r.cnpmjs.org/@parcel/watcher-wasm/-/watcher-wasm-2.5.0.tgz failed, reason: getaddrinfo EAI_AGAIN r.cnpmjs.org

 ERROR  Error: Command failed with exit code 1: npm install                                                                                                      11:37:59 a.m.

Only with  npm, yarn works fine, also npm on any other project initialization  be it vite with vue, or anything else, all works fine only npm with nuxt. 
When installing a new package using npm on nuxt too, it keeps freezing and loading stops and never completes installation.

See also time from 9:25:33 a.m. to 11:37:59 a.m.

I have tried to  npm config set registry https://registry.npmjs.org/
npm config delete proxy and npm config delete https-proxy
but all to a deadend.

**Comment by huang-julien** [comment]
Haven't found a lot to help you. But this seems like rather a DNS issue than something related to nuxt ? 

https://stackoverflow.com/questions/63010779/npm-err-code-eai-again-error-when-trying-to-install-express
