### ISSUE TITLE
Unable to access config in plugins

### ISSUE THREAD

**Issue by hamonCordova** [nuxt/nuxt#30034]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.20.4
- Nuxt Version:     3.14.1592
- CLI Version:      3.15.0
- Nitro Version:    2.10.4
- Package Manager:  npm@10.7.0
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxt/ui@3.0.0-alpha.9, nuxt-vuefire@1.0.4
- Build Modules:    -

### Reproduction

Just create a new project and test it

### Describe the bug

I've just created a new Nuxt project, and I'm not able anyway to access public runtime configs in plugins! I have problem with manually creating firebase.client plugin (inside the app folder) and even using nuxt-vuefire

### Logs

```shell-script

```

**Comment by cernymatej** [comment]
Hi there, could you share the code that doesn't work for you?

**Comment by hamonCordova** [comment]
I don't what happend, I have never passed through that kind of error.
I've fixed that changing the port where Nuxt was running. Thanks
