### ISSUE TITLE
NuxtLink to non-existant page results in error 500

### ISSUE THREAD

**Issue by mrleblanc101** [nuxt/nuxt#30058]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.18.0
- Nuxt Version:     3.14.1592
- CLI Version:      3.15.0
- Nitro Version:    2.10.4
- Package Manager:  pnpm@9.14.2
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxtjs/tailwindcss@6.12.2, @nuxtjs/color-mode@3.5.2, @vueuse/nuxt@11.3.0, @pinia/nuxt@0.7.0, @nuxt/icon@1.8.2, @nuxt/fonts@0.10.2
- Build Modules:    -
------------------------------

### Reproduction
https://stackblitz.com/~/github.com/mrleblanc101/broken-nuxt-link-repro

### Describe the bug

If on my `index` page, I add a link to a non-existant `posts-id` page, the index page will crash with an error 500.
`<NuxtLink :to="{ name: 'posts-id', params: { id: 123 } }"> Post 123 </NuxtLink>`

I think this should lead to a 404 when clicking the link, and not outright crash the page that has this link.

![Image](https://github.com/user-attachments/assets/6378818d-7e72-4147-83a2-f65ef31bf1de)

At first, I thought this might be related to vue-router@4.5.0 which was released yesterday, but even with an override in my package.json, I still have the issue:
```
  "resolutions": {
    "vue-router": "4.4.0"
  },
```

### Logs

```shell-script

```

**Comment by mrleblanc101** [comment]
Also crash on prod
![Image](https://github.com/user-attachments/assets/ce4740c8-1779-46c7-94f2-1dc951d6932a)

**Comment by mrleblanc101** [comment]
I'll try using nuxi init, I wasn't able to reproduce using StackBlitz but I have barely anything in my current project (which can't be shared).

**Comment by mrleblanc101** [comment]
I was able to import a Github repro to StackBlitz: https://stackblitz.com/~/github.com/mrleblanc101/broken-nuxt-link-repro

**Comment by wattanx** [comment]
This is the expected behavior. 
https://router.vuejs.org/guide/migration/#Removal-of-router-match-and-changes-to-router-resolve

You can avoid it by using a template literal, just so you know.
`<NuxtLink :to="`/posts/${id}`">path</NuxtLink>`

**Comment by mrleblanc101** [comment]
I don't see anywhere in your link where it specify that it will create build time error instead of linking to a 404, also this seems like a terrible decision, why would they make such a change ?

**Comment by wattanx** [comment]
Sorry, I shared the wrong link
https://router.vuejs.org/guide/migration/#Non-existent-named-routes

**Comment by mrleblanc101** [comment]
@wattanx Ah, my first test didn't work in StackBlitz because I had no `pages` folder, so Nuxt wasn't import vue-router 🤦‍♂ 

It make some sense that it cannot generate a valid URL since the name won't resolve to anything.
I guess I'm just so used to the old behavior, I would've preferred if it still generated an href to `/` but went to a 404, or maybe if it generated an href directly to the Nuxt`/error` page instead of crashing the whole app.

Thanks

**Comment by mrleblanc101** [comment]
@wattanx oh now I realize that the error page is a Nuxt concept and this is a change in Vue-router, so they wouldn't be able to do this.

I much prefer the name syntax, because it's easier for params, query and i18n. But sometimes I create menu that link to inexistant pages because I create the after. I wish there was an option to go back to the old behavior, I'm going to open an issue in the Vue-router repo then.
