### ISSUE TITLE
`addServerTemplate` is missing in `@nuxt/kit`

### ISSUE THREAD

**Issue by who-jonson** [nuxt/nuxt#30062]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v22.11.0
- Nuxt Version:     3.14.1592
- CLI Version:      3.15.0
- Nitro Version:    2.10.4
- Package Manager:  pnpm@9.14.2
- Builder:          -
- User Config:      default
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-kttsu7?file=modules%2Fserver-template.ts

### Describe the bug

`addServerTemplate` is missing in `@nuxt/kit`, though `NuxtServerTemplate` is exported from `@nuxt/kit`

![Image](https://github.com/user-attachments/assets/46ec941f-ba56-4199-907f-af1e5716a71b)

### Logs

```shell-script

```

**Comment by danielroe** [comment]
Thank you for the issue! This has been resolved in https://github.com/nuxt/nuxt/commit/a0dcb64c7
