### ISSUE TITLE
`NuxtLink` is not drop-in replacement for `<a href="?query">` or `<a href="#hash">`

### ISSUE THREAD

**Issue by GrantGryczan** [nuxt/nuxt#30074]
### Environment

- Operating System: Windows_NT
- Node Version:     v22.10.0
- Nuxt Version:     3.14.159
- CLI Version:      3.15.0
- Nitro Version:    2.10.4
- Package Manager:  npm@10.9.0
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxt/eslint@0.6.1
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-zxu7oo?file=pages%2Findex.vue

### Describe the bug

When `NuxtLink`'s `href` is set to a string starting with `?` or `#`, the `a` tag's rendered `href` value will contain not only that string but also the current route's path prepended to it. This is contrary to the vanilla HTML behavior: `a` tags are allowed to have an `href` value starting with `?` or `#` with no path preceding.

In both cases, this can break CSS selectors that filter on the `href` attribute. In the case of `#`, prepending the path can break the link since it excludes the query. Simply rendering the `href` the way it was originally set, as expected, would fix this. In fact, when the `href` starts with `#`, it could be rendered as a vanilla `a` tag rather than a router link. No event handler is needed for that.

Reproduction steps:
1. Inspect the "Query" link. You'll find `href="/?query=1"`, and its text color is red.
2. Click the "Query" link. The current route changes to `/?query=1`.
3. Inspect the "Hash" link. You'll find `href="/#hash"`, and its text color is red.
4. Click the "Hash" link. The current route changes to `/#hash`.

Expected:
- All links should be colored blue, not red.
- Inspecting the "Query" link should show `href="?query=1"`, as expected from the source code.
- Inspecting the "Hash" link should show `href="#hash"`, as expected from the source code.
- Clicking "Query" and then "Hash" should result in the current route `/?query=1#hash`.

### Additional context

When `NuxtLink` is used in `app.vue` instead of in a page, it correctly mirrors the value set in the `href` rather than prepending a path. This issue only affects `NuxtLink`s used in pages.

**Comment by GrantGryczan** [comment]
Also, I would think this is a bug, not an enhancement. The functionality of hash links is completely broken as they don't preserve queries.

**Comment by vmrjnvc** [comment]
I would love to help with this issue if no one else has taken it yet.

**Comment by GrantGryczan** [comment]
How do I test if this is actually fixed on Stackblitz? I'm having trouble setting a git repository as a dependency. From the PR's description, I don't think this would fully fix the issue, as the path would still be prepended to query `href` values, so I'd like to test my minimal reproduction again.

**Comment by danielroe** [comment]
We only merged a change for `#`. As far as query strings go, that would probably be a feature request to https://github.com/vuejs/router.

**Comment by GrantGryczan** [comment]
It's the `NuxtLink`'s `href` that's incorrect, not the routing functionality, no?

**Comment by danielroe** [comment]
I believe this is behaviour that would occur in a RouterLink as well

**Comment by GrantGryczan** [comment]
Oh! I see, I didn't realize `NuxtLink` uses `RouterLink`. I might open an issue there later then, thanks for the info!
