### ISSUE TITLE
Nuxt Server Plugin not awaiting a promise

### ISSUE THREAD

**Issue by inthegreenwild** [nuxt/nuxt#30078]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.9.0
- Nuxt Version:     3.10.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.8.1
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://codesandbox.io/p/devbox/nr3fg4

### Describe the bug

I am using a server plugin which awaits a promise that requests a secret from AWS secret manager and uses that to set up a connection to a CMS. I then set the initialized CMS variable onto the event context with nitro request hook. The problem is, requests are processed before the plugin finishes fetching the promise even though the promise is awaited. And since the hook did not set the variable yet, the server returns a 500. I've created a simple example that replicates the behavior. Is this a bug with server plugins or is there a better approach to doing this? 

### Logs

```shell-script

```

**Comment by huang-julien** [comment]
Hello this is a nitro issue. What you're looking for is the Task API of nitro. For now it is not possible yet to have a startup task.

https://github.com/nitrojs/nitro/issues/2021

**Comment by danielroe** [comment]
(Nitro server plugins are synchronous - you can use the Task API or a Nitro hook to run async tasks...)

**Comment by canidam** [comment]
@danielroe if my Nitro server plugin is async, I see nitro triggers it and continue to the next before it finishes (which is good for me).

If I have a long running task, that needs to run on server startup and run in the background - is using Nitro server plugins a good approach?
