### ISSUE TITLE
Suspense updates page before all data is loaded using `useFetch`

### ISSUE THREAD

**Issue by martinszeltins** [nuxt/nuxt#30084]
### Environment

````
------------------------------
- Operating System: Linux (Ubuntu 24.04 LTS)
- Node Version:     v20.11.0
- Nuxt Version:     3.14.1592
- CLI Version:      3.15.0
- Nitro Version:    -
- Package Manager:  pnpm@8.1.0
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxtjs/tailwindcss@6.12.2, @vueuse/nuxt@12.0.0, @pinia/nuxt@0.8.0
- Build Modules:    -
------------------------------
````

### Reproduction

https://stackblitz.com/~/github.com/martinszeltins/nuxt-suspense-navigate-bug

### Describe the bug

I have 2 simples routes - `/` and `/:uuid`. The idea os that the `/` route is for creating something new and `/:uuid` is for loading an existing item. When I navigate to `/123`, it should wait until it fetches all data and then navigates to the new page. But what happens is that I see the data coming in and the current page being updated before the navigation finishes.

I expected it to "freeze" the current page until it finishes all `useFetch` calls and then shows the new page but that is not what happens.

Here is a screencast of what is happening, you can see that first `items` is loaded and shows up on screen, then `shipments` are loaded and appears and then finally it navigates to the new page. This is really strange. Maybe this is a Suspense bug?

I would expect such behavior if I used `$fetch` but I specifically used `await useFetch()` here because I don't want to see data being loaded bit by bit but I want it to navigate when **ALL** data has been loaded, _almost like a normal `<a href>` would do._

![Image](https://github.com/user-attachments/assets/ec5cdb65-ca42-4544-82e5-9e6c8605c9b5)

### Logs

```shell-script

```

**Comment by mrleblanc101** [comment]
I tihnk you need to put your 3 API call in the same useAsyncData call

**Comment by mrleblanc101** [comment]
`useAsyncData` accept a function which can be async:
Something like this:
```
const { data: postCard, error, execute, pending, refresh, status } = await useAsyncData('post-card', async () => {
    const posts = await $fetch('https://jsonplaceholder.typicode.com/posts'),
    const users = await $fetch('https://jsonplaceholder.typicode.com/users'),
    const comments = await $fetch('https://jsonplaceholder.typicode.com/comments')
  return { posts, users, comments }
})
```

**Comment by martinszeltins** [comment]
For anyone else having the same issue, here is how I solved it.

1. I fetched all the data and stored it in temporary variables but I did not set them in Pinia store YET
2. When I finished fetching ALL data then I took the data from my temporary variables and updated Pinia store, the form, UI etc.

This fixed my issue.

**Comment by danielroe** [comment]
This issue is related to using pinia, and the logic associated with it, I believe. I would recommend using `pinia-colada` in your situation.

Using `useFetch` on its own should also do what you wished.
