### ISSUE TITLE
Build error: RollupError  Expression expected

### ISSUE THREAD

**Issue by artokhotnikov** [nuxt/nuxt#30081]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v22.11.0
- Nuxt Version:     3.14.1592
- CLI Version:      3.15.0
- Nitro Version:    2.10.4
- Package Manager:  npm@10.9.0
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxtjs/eslint-module@4.1.0, @pinia/nuxt@0.7.0, @nuxt/image@1.8.1, @vueuse/nuxt@10.11.1
- Build Modules:    -
------------------------------

### Reproduction

nuxt.config.ts
![Image](https://github.com/user-attachments/assets/80ddc559-82d2-4211-8233-3c389521080a)

------------------------------

There are no problems when running npm run dev. But when I run npm run build I get an error
![Image](https://github.com/user-attachments/assets/225c7110-142e-475c-baf3-bbee802ebd0b)

------------------------------

### Describe the bug

After changing the folder structure of nuxt, the project is not going to production

 _RollupError: shared/UI/Icons/IconsMinus.vue (1:0): Expression expected (Note that you need plugins to import files that are not JavaScript)_

**Comment by artokhotnikov** [comment]
https://stackblitz.com/~/github.com/artokhotnikov/nuxt-fsd-bug

Try running npm run build to see the error

**Comment by danielroe** [comment]
`~/shared/` is a special directory meant for code shared between your vue + nitro apps and should not contain vue files.

If you rename it should work fine.
