### ISSUE TITLE
Nuxt Layers: `pathPrefix: false` prevents component imports when the application is extended

### ISSUE THREAD

**Issue by volkanakkus** [nuxt/nuxt#30099]
### Environment

2 Nuxt Applications with same Environment:

nuxt: 3.14.1592
nitro: 2.10.4

### Reproduction

Link: https://stackblitz.com/edit/nuxt-starter-tckmhw?file=base%2Fnuxt.config.ts

Steps: 

- `cd layer` 
- `yarn` or `npm i`  
- `yarn dev` or `npm run dev`

### Describe the bug

When working with two Nuxt applications, one as a base and the other as a layer, there is an issue with component exports from the base application to the layer.

**Here’s the scenario:**

- The base application contains components, which are intended to be imported and used in the layer application.
- In the layer application, the base application is extended using the `extend` property in `nuxt.config.ts`.
- The base application uses a nested component structure. To simplify usage, we disabled component name prefixes by setting `pathPrefix: false` in the `nuxt.config.ts` as per the [official documentation](https://nuxt.com/docs/guide/directory-structure/components).
- After doing this, components from the base application are no longer exported to the layer application, making them inaccessible.

**Conclusion:** This behavior breaks the expected functionality where components from the base application should be seamlessly available in the layer application. It appears that the configuration in the base application's nuxt.config.ts is interfering with the component export mechanism.

And also this issue might not be limited to the `pathPrefix` setting. It could also occur if the base application has custom `components` property and with related configurations in it's `nuxt.config.ts`. 

### Logs

```shell-script
WARN  [Vue warn]: Failed to resolve component: TestInner
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <App> 
  at <NuxtRoot>
```

**Comment by irm4nt45** [comment]
There is a concept of single-spa application (https://single-spa.js.org) that could be used to bundle the microservices. The reach of shared components is quite easy in this architecture as they serve as a microservice. On which nuxt version did the components from the base application still reach the layer application?

**Comment by danielroe** [comment]
The `~` refers to the final project's source directory - not the layer, in this case.

If you want custom configuration _only_ within the layer's components directories, you can do this by using an absolute path within the layer configuration file.

```ts
import { createResolver } from 'nuxt/kit'

const resolver = createResolver(import.meta.url)

export default defineNuxtConfig({
  components: [
    {
      path: resolver.resolve('./components'),
      pathPrefix: false,
    },
  ],
});
```
