### ISSUE TITLE
defineNuxtRouteMiddleware can not retrieve hashes the first time it enters

### ISSUE THREAD

**Issue by Soya-xy** [nuxt/nuxt#30100]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.17.0
- Nuxt Version:     3.14.1592
- CLI Version:      3.15.0
- Nitro Version:    2.10.4
- Package Manager:  pnpm@9.10.0
- Builder:          -
- User Config:      default
- Runtime Modules:  @vueuse/nuxt@11.3.0, @pinia/nuxt@0.7.0, @nuxtjs/color-mode@3.5.2, @vite-pwa/nuxt@0.10.6, @nuxt/eslint@0.7.2, @nuxtjs/tailwindcss@6.12.2, shadcn-nuxt@0.11.3, @vue-macros/nuxt@1.12.9, nuxt-svgo@4.0.9, @nuxt/image@1.8.1, @nuxtjs/i18n@9.1.0, @nuxtjs/google-fonts@3.2.0, nuxt-swiper@2.0.0
- Build Modules:    -
------------------------------

### Reproduction

git@github.com:Soya-xy/game-page.git

### Describe the bug

Hashe can be output normally in the browser, but can not be retrieved on the server side

Browser 

![Image](https://github.com/user-attachments/assets/6469989c-a03b-475c-a976-50610f43ad5d)

Server

![Image](https://github.com/user-attachments/assets/9d275a4a-2785-4c29-8704-1b6030da9f37)

### Logs

```shell-script

```

**Comment by manniL** [comment]
The fragment part (`#abc`) is not transferred to the server and thus can't be fetched. This is not a Nuxt issue but normal behavior from browsers!
