### ISSUE TITLE
Can't name folder "assets" in `public` without issues re-rendering components

### ISSUE THREAD

**Issue by GrantGryczan** [nuxt/nuxt#30107]
### Environment

- Operating System: Windows_NT
- Node Version:     v22.10.0
- Nuxt Version:     3.14.159
- CLI Version:      3.15.0
- Nitro Version:    2.10.4
- Package Manager:  npm@10.9.0
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxt/eslint@0.6.1
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-lbutem?file=pages%2Findex.vue

### Describe the bug

Links to files in Nuxt's `public` folder are sometimes broken if the path starts with `/assets/`, as it will be replaced with `/&/assets/`. It works fine on the initial render of an `img` element, but if a re-render updates that element, this issue occurs.

Reproduction steps:
1. Open the minimal reproduction link.
2. Click the link to page 2.
3. Notice the image is now broken because its `href` was jumbled.

### Additional context

I have only tested this for images (`<img src="/assets/..." />`). I don't know if it applies to other forms of references to static assets in the `public/assets` folder.

**Comment by danielroe** [comment]
This is likely an upstream vite HMR issue.

**Comment by danielroe** [comment]
tracking in https://github.com/nuxt/nuxt/issues/28555.
