### ISSUE TITLE
SSR in Netlify not workin after upgrading to v3.14.1592

### ISSUE THREAD

**Issue by teleskop150750** [nuxt/nuxt#30123]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.18.0
- Nuxt Version:     3.14.1592
- CLI Version:      3.16.0
- Nitro Version:    2.10.4
- Package Manager:  pnpm@9.12.3
- Builder:          -
- User Config:      default
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

[v3.14](https://github.com/teleskop150750/nuxt_netlify)

[v3.13](https://github.com/teleskop150750/nuxt_netlify/tree/3.13)

### Describe the bug

Server shows blank page after upgrading to nuxt 3.14

[v3.14](https://nuxt-netlify-3-14.netlify.app/)

[v3.13](https://3-13--nuxt-netlify-3-14.netlify.app/)

### Logs

```shell-script

```

**Comment by danielroe** [comment]
This sounds like it might be a nitro issue. Would you see if it reproduces with v3.13, if you manually upgrade nitropack to v2.10+?

**Comment by teleskop150750** [comment]
> This sounds like it might be a nitro issue. Would you see if it reproduces with v3.13, if you manually upgrade nitropack to v2.10+?

During the build, the latest version at the moment is displayed

Nitro v2.10.4

![Image](https://github.com/user-attachments/assets/4415c06f-29be-464a-a09f-07ecbea01910)


I also tried specifying nitropack in dependencies

```
"dependencies": {
    "nitropack": "^2.10.4",
    "nuxt": "^3.14.1592",
    "vue": "latest",
    "vue-router": "latest"
  },
```

**Comment by teleskop150750** [comment]
> This sounds like it might be a nitro issue. Would you see if it reproduces with v3.13, if you manually upgrade nitropack to v2.10+?

I specified the latest version of nitropack in the dependencies in both branches. The problem only exists on 3.14

![Image](https://github.com/user-attachments/assets/a908ff59-72f6-42ac-b963-cd705385d2ee)


[v3.14](https://github.com/teleskop150750/nuxt_netlify)

[v3.13](https://github.com/teleskop150750/nuxt_netlify/tree/3.13)

**Comment by rylanharper** [comment]
This also is occurring with all SSG Nuxt sites in Netlify (based on my own sites and other devs in my network):

```
2:23:21 PM: "build.command" failed                                        
2:23:21 PM: ​
2:23:21 PM:   Error message
2:23:21 PM:   Command failed with exit code 1: pnpm generate (https://ntl.fyi/exit-code-1)
2:23:21 PM: ​
2:23:21 PM:   Error location
2:23:21 PM:   In Build command from Netlify app:
2:23:21 PM:   pnpm generate
```

Surprised this not a more prevalent issue being reported on.

**Comment by blefevre** [comment]
We're having the same issue with SSR on `3.14.1592` in `aws-lambda`, `3.14.159` is fine however.

**Comment by teleskop150750** [comment]
Success [v3.14.0](https://3-14-0--nuxt-netlify-3-14.netlify.app/)

Success [v3.14.159](https://3-14-159--nuxt-netlify-3-14.netlify.app/)

Error [v3.14.1592](https://nuxt-netlify-3-14.netlify.app/)

**Comment by teleskop150750** [comment]
Success [v3.14.1592 no-layout](https://no-layout--nuxt-netlify-3-14.netlify.app/)

**Comment by danielroe** [comment]
That might be. Would you provide a reproduction? (Actual code I can inspect?)

**Comment by teleskop150750** [comment]
> That might be. Would you provide a reproduction? (Actual code I can inspect?)

I already left a link to the repository above.

it has different branches for different versions

[nuxt_netlify](https://github.com/teleskop150750/nuxt_netlify)

**Comment by danielroe** [comment]
I've just tried to reproduce on your `3.14.159` branch with:

```
NITRO_PRESET=netlify pnpm nuxi build
ntl deploy
```

and this works fine: https://6756c560c6db14e1e39a5086--vermillion-taiyaki-57c945.netlify.app.

Any other details about how you are deploying it? Maybe using an edge worker?

**Comment by teleskop150750** [comment]
> I've just tried to reproduce on your `3.14.159` branch with:
> 
> ```
> NITRO_PRESET=netlify pnpm nuxi build
> ntl deploy
> ```
> 
> and this works fine: https://6756c560c6db14e1e39a5086--vermillion-taiyaki-57c945.netlify.app.
> 
> Any other details about how you are deploying it? Maybe using an edge worker?

sorry. maybe I didn't describe the problem very clearly. in previous posts, I indicated that the error is reproducible only for version [v3.14.1592](https://nuxt-netlify-3-14.netlify.app/) (master branch)

**Comment by teleskop150750** [comment]
as you correctly pointed out, a similar problem is described here 

#30188

**Comment by danielroe** [comment]
can confirm resolved in https://github.com/nuxt/nuxt/pull/30203!

**Comment by CHEWX** [comment]
> This also is occurring with all SSG Nuxt sites in Netlify (based on my own sites and other devs in my network):
> 
> ```
> 2:23:21 PM: "build.command" failed                                        
> 2:23:21 PM: ​
> 2:23:21 PM:   Error message
> 2:23:21 PM:   Command failed with exit code 1: pnpm generate (https://ntl.fyi/exit-code-1)
> 2:23:21 PM: ​
> 2:23:21 PM:   Error location
> 2:23:21 PM:   In Build command from Netlify app:
> 2:23:21 PM:   pnpm generate
> ```
> 
> Surprised this not a more prevalent issue being reported on...
> 
> According to Netlify:
> 
> ```
> The specific error messages related to the failure are:
> 
> Line 368: ENOENT: no such file or directory, open '/opt/build/repo/web/.netlify/functions-internal/server/server.json'
> Line 369: ENOENT: no such file or directory, open '/opt/build/repo/web/.netlify/functions-internal/server/server.json'
> Line 370: �[41m�[30m ELIFECYCLE �[39m�[49m �[31mCommand failed with exit code 1.�[39m
> Line 376: Command failed with exit code 1: pnpm generate
> ```

I'm getting this issue...

`"nuxt": "3.14.159"`

Why is this closed? What's the resolution?

`nuxt generate` works fine locally, just not with Netlify?

**Comment by CHEWX** [comment]
Fixed by changing `compatibilityDate: '2024-04-03'` to `compatibilityDate: '2024-11-01'`

Completely finger in the air fix...

**Comment by danielroe** [comment]
> Why is this closed? What's the resolution? Any workaround?

@CHEWX see the comment just above yours: https://github.com/nuxt/nuxt/issues/30123#issuecomment-2529401490. It was resolved in https://github.com/nuxt/nuxt/pull/30203 and will be released in v3.15.

**Comment by richgcook** [comment]
I still get this error in 3.17.6

**Comment by richgcook** [comment]
> I still get this error in 3.17.6

This is to do without including a `compatibilityDate` in the config file. Added that and no longer had the issue. Same as @CHEWX's s fix.
