### ISSUE TITLE
Inconsistent if statement execution in global middleware

### ISSUE THREAD

**Issue by dhwid** [nuxt/nuxt#30138]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.14.1592
- CLI Version:      3.16.0
- Nitro Version:    2.10.4
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      default
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-9k4bmq?file=middleware%2Fmiddleware.global.ts

### Describe the bug

The condition in the if statement is skipped if the line of code is not wrapped with curly braces `{}`. The code snippet is part of a global middleware, and the invoked function is asynchronous:

```typescript
export default defineNuxtRouteMiddleware(async (to, from) => {
  const print = async (msg: string) => {
    console.log(msg);
  };

  if (false) await print('test without brackets'); //executes both on the server and the client
  if (false) {
    await print('test with brackets'); //does not execute on either the server or the client.
  }
});
```
This behavior leads to inconsistencies in execution depending on whether curly braces are used for single line.

### Logs

```shell-script

```

**Comment by huang-julien** [comment]
Hello, thanks for the issue ! 
Indeed, this is an unctx bug
