### ISSUE TITLE
SSR bug with v-show + inheritAttrs: false + v-bind="$attrs"

### ISSUE THREAD

**Issue by oom-** [nuxt/nuxt#30156]
### Environment

Nuxt project info:                                                                                           

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.14.1592
- CLI Version:      3.16.0
- Nitro Version:    2.10.4
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxtjs/tailwindcss@6.12.2
- Build Modules:    -
------------------------------

### Reproduction

[Playground with toogle not showing the second input on click ](https://stackblitz.com/edit/github-fcvwur?file=app.vue)

### Describe the bug

With `npm run dev`, using `v-show`  on an component with `defineOptions({ inheritAttrs: false });` and `v-bind="$attrs"` is resulting in `display:none;` applied on the root div of the subcomponent (good behavior)+ the binded `$attrs` div if the initial `v-show` value is `false` (not good behavior).

Considering the following tree of components:
```html
<script setup>const display = ref(false);</script>
<div>
    <div v-show="!display">
        <div>Normal component OK</div>
    </div>
    <div v-show="display"> <!--- Here is display:none --->
        <div>
            <div v-bind="$attrs"></div> <!--- Here the display: none of v-show is set as well but should stay on the root level --->
        </div>
    </div>
</div>
```` 
Even with using keys, if we put the sub component  `v-show` prop at `false`:
![Image](https://github.com/user-attachments/assets/85732ef5-4524-4b26-b5c5-40f98eeae75d)
Inside the component:
![Image](https://github.com/user-attachments/assets/5ebfc51d-eef7-4ca8-8573-602eb37eaeda)
The `label ` shows up but not the input with `v-bind="$attrs"`:
![Image](https://github.com/user-attachments/assets/36c55168-2ba4-4cdb-8e7d-4417cbbd4e47)
As you can see the `display:none;` prop was set to the input as well on first load but not removed when the toggle box was checked:
![Image](https://github.com/user-attachments/assets/a5601979-deb0-4b3b-a774-87ed02bc2145)
After checked:
![Image](https://github.com/user-attachments/assets/2e4e4e85-5130-4d20-ad6d-e2de79993d37)

I think the issue could be linked with: 
1. On SSR, Nuxt estimate that the `v-show` add the `display: none; ` style and figures out that the input has a `v-bind="$attrs"` attribute, so it clone the style attribute and add it to the input html element as well.
2. On Client side, the Vue app doesn't understand that the  `display: none; ` is related to the same `v-show` condition than the root div, and fail to toogle it on checked.

### Additional context

 There is no issues using only Vue in their playground: 
- [Example in vue official playground](https://play.vuejs.org/#eNrVVk1v2zgQ/StcYQFngdDuJu1htW6A7iKH7kdb7AbtISoKWRrZbGlSICnZhuH/3iEpSrSjJE1vvdjSvJnhm+E8UvvkVV1P2waSNJnrQrHaEA2mqclVJti6lsqQvYLqQCol1yRL0DVLfu+x16JuzAdmVq+MUWzRGNDBczobAe1So/HvlKzHQp19NOpGyiWHkxBv7P0zUUihDSlWUHyBkrwkWMtZlXMNvyDsQQNb81ZAB04mx8jNRh4h85lvE/ZnbmBd89wAPhMyL1lLCp5r/TJLavo8S5wZgZguzxfA0eENbAgIo3ZZQlq6lqWzdjzRNgvBcdaKw5bYH1pI3ucPK/TtCmZCvsAOw/6GHdaXJYO9pXolNwj91K8Yg4FO15kYDPz/sf9pjGAnClhJXoJC3DEiMg4OJcV8h8kYIY2tHyX9KOeTwKdxNnFwvw0z3Ae/zd3TfBbtfnKeGI0zU7Hl9LOWAtW0t87IVa5rxkG9rQ3DmcqSlDjEYjnncvOXsxnVwHmwu/pG7J/11tqy5J0CDarF3vaYydUSjIev/3+DTYhA7E3D0fsB8D/QkjeWo3f7oxEl0o78HNvXToBMLG/09daA0KEoS9R6Hpy/Oyf+fKD0ge7l9LmLy8QBu3gi4tNTCVvtldnmvLGKLaFiAv61e39m1enfnQrObidu4ycfB+B6zYwFmrrEjUvdzLy3qbxTpO0H1e10yBDXtEARgyLL/EjxbuGr/d6PHjkc5jNvivE+nQJchrVAmOBIkt6TnhSN0lLRWjJrjPXP/OTuagjyWEiclUgWrmFoCWtqRaXgO1KDzRRrEwsdBBLcN/Q3sqIvyGJJNyukRhZSoWi6P7rA5PTy2TOXjlayaHQqG+OqEXgIxHaF00Mv7lj6FEri6EFJq4Zz5+VdO9GneYW1p0blQtvNodvB8cRnlNuJSyjHv+Js4UwbejuZfOxM+cLpIngYWdPbi3obYA4VukcGzNgveERjqfLdHWv3clSyN61wv/3Tpn9yRTMrJopiPK4nWnc4va6GY8seXMMI3neI3XNj3/k44LlY2rMWRY2Bj4iu0//ZHud7BYoZm1ynxF3D5GAdH5P1k4QZLkinmotvF6UXUUjlN2hUQy1dMFGi4efcVtLL59Gu9h8z39HQczKJbivf3x+paWnE/skd/NSCslcN9u1y+mL662Vy+ArqKJrw)
- [Example vue + vite playground](https://stackblitz.com/edit/vitejs-vite-5yi8n7?file=src%2FApp.vue)

**Note:** after build with Nitro, the issue disappears.

### Logs

```shell-script
-
```

**Comment by danielroe** [comment]
this does seem to be [reproducible in the vue playground](https://play.vuejs.org/#__SSR__eNrVVk1v2zgQ/StcYQFngdDuJu1htW6A7iKH7kdb7AbtISoKWRrZbGlSICnZhuH/3iEpSrSjJE1vvdjSvJnhm+E8UvvkVV1P2waSNJnrQrHaEA2mqclVJti6lsqQvYLqQCol1yRL0DVLfu+x16JuzAdmVq+MUWzRGNDBczobAe1So/HvlKzHQp19NOpGyiWHkxBv7P0zUUihDSlWUHyBkrwkWMtZlXMNvyDsQQNb81ZAB04mx8jNRh4h85lvE/ZnbmBd89wAPhMyL1lLCp5r/TJLavo8S5wZgZguzxfA0eENbAgIo3ZZQlq6lqWzdjzRNgvBcdaKw5bYH1pI3ucPK/TtCmZCvsAOw/6GHdaXJYO9pXolNwj91K8Yg4FO15kYDPz/sf9pjGAnClhJXoJC3DEiMg4OJcV8h8kYIY2tHyX9KOeTwKdxNnFwvw0z3Ae/zd3TfBbtfnKeGI0zU7Hl9LOWAtW0t87IVa5rxkG9rQ3DmcqSlDjEYjnncvOXsxnVwHmwu/pG7J/11tqy5J0CDarF3vaYydUSjIev/3+DTYhA7E3D0fsB8D/QkjeWo3f7oxEl0o78HNvXToBMLG/09daA0KEoS9R6Hpy/Oyf+fKD0ge7l9LmLy8QBu3gi4tNTCVvtldnmvLGKLaFiAv61e39m1enfnQrObidu4ycfB+B6zYwFmrrEjUvdzLy3qbxTpO0H1e10yBDXtEARgyLL/EjxbuGr/d6PHjkc5jNvivE+nQJchrVAmOBIkt6TnhSN0lLRWjJrjPXP/OTuagjyWEiclUgWrmFoCWtqRaXgO1KDzRRrEwsdBBLcN/Q3sqIvyGJJNyukRhZSoWi6P7rA5PTy2TOXjlayaHQqG+OqEXgIxHaF00Mv7lj6FEri6EFJq4Zz5+VdO9GneYW1p0blQtvNodvB8cRnlNuJSyjHv+Js4UwbejuZfOxM+cLpIngYWdPbi3obYA4VukcGzNgveERjqfLdHWv3clSyN61wv/3Tpn9yRTMrJopiPK4nWnc4va6GY8seXMMI3neI3XNj3/k44LlY2rMWRY2Bj4iu0//ZHud7BYoZm1ynxF3D5GAdH5P1k4QZLkinmotvF6UXUUjlN2hUQy1dMFGi4efcVtLL59Gu9h8z39HQczKJbivf3x+paWnE/skd/NSCslcN9u1y+mL662Vy+ArqKJrw) when `ssr` is enabled.

would you be able to open an issue [there](https://github.com/vuejs/core/issues/new/choose)? 🙏
