### ISSUE TITLE
h3.d.ts existing without imports breaks api type inference

### ISSUE THREAD

**Issue by 5knnbdwm** [nuxt/nuxt#30153]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.18.0`
- Nuxt Version:     `3.14.1592`
- CLI Version:      `3.16.0`
- Nitro Version:    `-`
- Package Manager:  `pnpm@9.12.1`
- Builder:          `-`
- User Config:      `default`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Broken Version: [link](https://codesandbox.io/p/devbox/github/5knnbdwm/nuxt-H3EventContext-bug/tree/8384c02879016d153421679d657874b1a988fc07?file=%2Fpages%2Findex.vue%3A6%2C9)

Fixed Version: [link](https://codesandbox.io/p/devbox/github/5knnbdwm/nuxt-H3EventContext-bug/tree/d84cda28d784ebc4f67f3670b14394504656adf4?file=%2Fpages%2Findex.vue%3A13%2C35)

### Describe the bug

Hey, I encountered this last night and spend a few hours comparing old commits (from a few days ago) to see what was breaking my type inference in the frontend.

In the frontend I just have this
```ts
const data = await useFetch("/api/test");
```

Then having a `server/types/h3.d.ts` that  changes H3EventContext. Just having the following breaks things:
```ts
declare module 'h3' {
  interface H3EventContext {}
}
```
I encountered the problem with a single key inside the context, but not having any breaks things as well.

I had the `h3.d.ts` file for while but only a few days ago deleted something that imported another type.
And that ultimately fixes things again as well. Just having an import statement in the file, whether the imported type/function is actually being used doesnt matter.

   

### Additional context

Broken:
![Image](https://github.com/user-attachments/assets/ce586453-b527-4a98-af09-7966215d812c)

Fixed:
![Image](https://github.com/user-attachments/assets/4b82fe46-3d04-439c-8d60-a64d7ff175fe)

### Logs

```shell-script

```

**Comment by danielroe** [comment]
This is how typescript augmentation works. You need to add `export {}` at the bottom of that file to enable it to augment, rather than overwrite, the interface. (It turns it into a 'module' for the benefit of TS.)
