### ISSUE TITLE
Hydration useId mismatch for page with useAsyncData

### ISSUE THREAD

**Issue by wszerad** [nuxt/nuxt#30170]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.14.1592
- CLI Version:      3.16.0
- Nitro Version:    2.10.4
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      default
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-ae1orx?file=pages%2Fcat.vue

path: /cat

### Describe the bug

Adding useAsyncData to the page changes the generated useId

### Logs

```shell-script
[Vue warn]: Hydration attribute mismatch on 
<span id="v-0-0" data-v-inspector="components/Cat.vue:10:1"> 
  - rendered on server: id="v-0-0"
  - expected on client: id="v-0"
```

**Comment by huang-julien** [comment]
Hello, you forgot to await `useAsyncDFata`
