### ISSUE TITLE
Error Parsing .ogv Files in Video Tags

### ISSUE THREAD

**Issue by miketests** [nuxt/nuxt#30180]
### Environment

OS: Ubuntu 22.04.5 LTS
Node: v20.12.2
NPM: 10.6.0
Nuxt: ^3.13.0

### Reproduction

1) Create a new Nuxt project or use an existing one.
2) Add a video file with a .ogv extension to your assets folder (e.g., assets/video.ogv).
3) Use the `video` tag to include `.ogv` file as a source in your component:

```html
<video autoplay loop muted>
  <source src="~/assets/video.ogv" type="video/ogg" />
</video>
```

4) Run the development server using npm run dev or yarn dev.

### Describe the bug

During local development, when attempting to add a source with the `.ogv` file extension in the `video` tag, the application fails to parse the file and throws an error. The terminal also outputs binary-like data or other unreadable characters. The issue seems to stem from the Vite import-analysis plugin not handling `.ogv` files correctly.

The error:
![Image](https://github.com/user-attachments/assets/b1007f72-23e9-46b5-a696-586423f820af)

Terminal output:
![Image](https://github.com/user-attachments/assets/8d98d9bf-b4d8-46c6-b0f2-18558ea30666)

### Additional context

**Expected Behavior:**
The `.ogv` file should be correctly handled as an asset, and the video should render without issues in the browser.

**Actual Behavior:**
```
[plugin:vite:import-analysis] Failed to parse source for import analysis because the content contains invalid JS syntax. You may need to install appropriate plugins to handle the .ogv file format, or if it's an asset, add "**/*.ogv" to `assetsInclude` in your configuration.
```

Additionally, I could not find any documentation or guidance on how to properly handle `.ogv` files as assets in Nuxt. There are no available plugins or instructions for working with `.ogv` files, making it unclear how this use case should be supported.

**Comment by danielroe** [comment]
This is an upstream `vite` issue - would you be able to raise it there, instead?

Additionally, I would recommend not using `~/assets` as this will trigger the file to be part of the _build_. Instead, use `/video.ogv` and place it in `~/public` and it will bypass the build process.
