### ISSUE TITLE
nuxt swiper to be server side render as before

### ISSUE THREAD

**Issue by MahmoudAbdalrhmanMohamed** [nuxt/nuxt#30198]
### Describe the feature

https://nuxt.com/modules/swiper

i have issue with it i can't use in server side only in clintonly tag i swith to older version of it it was perfect but when try to download older version of it make issus with code and not working at all

### Additional information

- [x] Would you be willing to help implement this feature?
- [x] Could this feature be implemented as a module?

### Final checks

- [x] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [x] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by cernymatej** [comment]
Hi,
this is the framework repository, which has little to do with the swiper module. You report it in the repo of the module - https://github.com/cpreston321/nuxt-swiper

Also, please include a reproduction with the actual error messages you're getting.
