### ISSUE TITLE
Middleware: If statement without braces and await is evaluated with falsy condition

### ISSUE THREAD

**Issue by patrikwalker** [nuxt/nuxt#30191]
### Environment

- Operating System: Linux
- Node Version:     v22.12.0
- Nuxt Version:     3.14.1592
- CLI Version:      3.16.0
- Nitro Version:    2.10.4
- Package Manager:  pnpm@9.14.4
- Builder:          -
- User Config:      default
- Runtime Modules:  @unocss/nuxt@0.65.1, @vueuse/nuxt@12.0.0, @pinia/nuxt@0.9.0, @pinia/colada-nuxt@0.0.4
- Build Modules:    -

### Reproduction

Reproduction Repo: https://stackblitz.com/edit/github-rcx4zkbz

1. Create a new async middleware
2. Use an if statement with a falsy condition without braces and await an expression

### Describe the bug

An awaited expression in an if statement without braces get always evaluated in a middleware function, even if the condition is falsy. If the statement uses braces or if the expression is not awaited, it works fine.

### Logs

```shell-script

```

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/30138.
