### ISSUE TITLE
[BUG] i18n translation not working correctly after browser language detection and redirect

### ISSUE THREAD

**Issue by xdkaka** [nuxt/nuxt#30204]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.11.0
- Nuxt Version:     3.14.1592
- CLI Version:      3.16.0
- Nitro Version:    2.10.4
- Package Manager:  yarn@1.22.21
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxtjs/i18n@9.1.1
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/xdkaka/test-nuxt

## Description
After deploying to production, when detecting browser language and redirecting, some i18n translations don't update properly until page refresh.

### Steps to Reproduce
1. Visit `http://localhost`
2. Auto-redirects to `http://localhost/zh-CN` based on browser language
3. Some translations remain in initial language instead of target language
4. Refreshing page at `http://localhost/zh-CN` fixes the issue

### Expected Behavior
All translations should update to target language immediately after redirect.

### Actual Behavior
- **Working:**
  ```vue
  {{ $t('test') }}
  ```

- **Not Working:**
  ```vue
  <div v-text="$t('test')"></div>
  <div v-html="$t('test')"></div>
  <input :placeholder="$t('test')">
  ```

### Error Message
CG-eFvx0.js:14 Hydration completed but contains mismatches.

### Environment
- Nuxt 3
- @nuxtjs/i18n v9
- Production environment

### Quick Setup
```
yarn build-prod && docker-compose down && docker-compose up -d
```

### Additional Context
- Only occurs after language detection and redirect
- Works correctly after page refresh
- SSR hydration mismatch error present

### Logs

```shell-script
Hydration completed but contains mismatches
```

**Comment by danielroe** [comment]
it seems like this should probably better be reported to https://github.com/nuxt-modules/i18n.

**Comment by xdkaka** [comment]
> it seems like this should probably better be reported to https://github.com/nuxt-modules/i18n.

https://github.com/nuxt-modules/i18n/issues/3262#issuecomment-2562396469

**Comment by danielroe** [comment]
thank you - let's track there
