### ISSUE TITLE
Separation between `build` and `generate`

### ISSUE THREAD

**Issue by SoaresMG** [nuxt/nuxt#30209]
### Describe the feature

Is there an option in the roadmap that allows `build` and `generate` separately?

Imagining an image that contains a build (uses `nuxi build`) and the entrypoint only runs `nuxi generate` but reuses the previously generated build.

I was trying out the `buildCache` but unfortunately it always builds everything during `generate` even if the build was generated in the image itself.

I have been using 2 patches:
- Nuxi - Not cleaning buildDir when `generate` runs
- Nuxt - Not calling `bundle(nuxt)` when `generate` runs

And I'm using a fixed `buildId`.

This has allowed me to run both `build` and `generate` separately but with `future.compabilityVersion = 4` I can no longer work with it, which is fine since patches are always something that shouldn't be done and I can live without them.

I also checked for recent issues/PRs regarding similar situations and ended up reaching #8142, #14605, #28726.
As I understood by @danielroe comment, this is something that the team wants to implement and one of the first steps was #28726, will this expand? Since it doesn't cache the whole build, just the client.

With `buildCache` it could potentially implement the whole idea if it caches the entire build

### Additional information

- [x] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [x] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [x] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
This indeed should be possible already (as far as nuxt builds - the nitro build will still be called) and if it isn't, it's a bug. Would you provide a reproduction to show what you are trying?
