### ISSUE TITLE
`onMounted` hook triggered twice

### ISSUE THREAD

**Issue by azizramdan** [nuxt/nuxt#30200]
### Environment

Working directory: /project/workspace                                                                                                      6:05:31 PM
Nuxt project info:                                                                                                                         6:05:31 PM

------------------------------
- Operating System: Linux
- Node Version:     v20.9.0
- Nuxt Version:     3.14.1592
- CLI Version:      3.15.0
- Nitro Version:    2.10.4
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      default
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://codesandbox.io/p/devbox/adoring-lederberg-873hwm

1. Open the `/` page of the application.
2. You will be redirected to the `/hello` page.
3. Check the logs, and you will notice that the message `fire twice` is logged twice.

### Describe the bug

I have encountered a bug in my Nuxt application where the mounted hook on the /hello page is triggered twice under certain conditions.

1. In `nuxt.config.ts`, I have set `app.pageTransition` and `app.layoutTransition`.
2. On the `/` page, I am using a custom layout and triggering a redirect to the `/hello` page in the mounted hook.
3. On the `/hello` page, I am calling the `Foo` component with lazy loading `<LazyFoo />`.

These three factors seem to be causing the mounted hook in the `/hello` page to be triggered twice.

This issue does not occur if:

1. Either `app.pageTransition`, `app.layoutTransition`, or both are set to false, or
2. The `Foo` component is called without lazy loading `<Foo />`.

### Logs

```shell-script

```

**Comment by huang-julien** [comment]
I think this issue was already raised. It's probably due to page transition ?

**Comment by azizramdan** [comment]
> I think this issue was already raised. It's probably due to page transition ?

You're right, this is a duplicate. I'll close this issue to focus on the previous one. Thanks!

 I used `<Suspense>` component as a temporary solution for the page transition issue. It works for now.

Related issues:
- https://github.com/nuxt/nuxt/issues/27364
- https://github.com/nuxt/scripts/issues/297#issuecomment-2424864978
