### ISSUE TITLE
Nuxt silently renders incorrect <template> when using external Vue components

### ISSUE THREAD

**Issue by Gwynerva** [nuxt/nuxt#30202]
### Reproduction

See `Foo.vue` component in `foo` Nuxt module.
It renders incorrectly in `app.vue`.

https://stackblitz.com/edit/nuxt-starter-6aprd3bh

### Describe the bug

When using an external Vue components, not matter how they end up in Nuxt (via nuxt modules, or via direct export of external packages) it fails to render specific templates.

Consider the following example template code:

```vue
<template>
  <div>
    <div>This is visible</div>
    <component :is="'div'" v-html="'<strong>THIS IS NOT!</strong>'" />
  </div>
</template>
```

Nuxt renders this code to the following HTML:

```html
<div>
  <div>This is visible</div>
  <div></div>
</div>
```

So the Nuxt correctly receives tag name (`div`) but fails to set `innerHTML` property...
This can be a symptom of a more serious problem. If this silently does not work, what else could not work?

Once again, the problem occurs ONLY with external Vue components.
I tested it both in Nuxt module and completely external package.

Moreover, components that are bundled with Vite `lib` mode are working just fine, so there is something wrong happening with Nuxt only when it directly consumes `.vue` files.

**Comment by danielroe** [comment]
This is reproducible on Vue core (SSR), so I've raised an issue there to track: https://github.com/vuejs/core/issues/12520.

Thank you for reporting it! ❤

**Comment by Gwynerva** [comment]
@danielroe what is interesting is that when I use the example `<template>` directly inside some `.vue` components that are a part of Nuxt app itself, it works perfectly...
