### ISSUE TITLE
new nuxt project won't start

### ISSUE THREAD

**Issue by kav3** [nuxt/nuxt#30216]
### Environment

Operating System: Ubuntu
Node Version: v20.15.0
Nuxt Version: 3.14.1592
CLI Version: -
Nitro Version: 2.10.4
Package Manager: npm@10.7.0
Builder: -
User Config: default
Runtime Modules: -
Build Modules: -

### Reproduction

npx nuxi init test
npm run dev

### Describe the bug

got this:

[11:03:23 AM]  ERROR  [unhandledRejection] Cannot find module '****/test/node_modules/@jridgewell/gen-mapping/dist/gen-mapping.umd.js'

### Logs

```shell-script

```

**Comment by yeonjulee1005** [comment]
I also occur this!

```
------------------------------
- Operating System: Darwin
- Node Version:     v20.0.0
- Nuxt Version:     3.13.2
- CLI Version:      3.16.0
- Nitro Version:    2.10.4
- Package Manager:  bun@1.1.38
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxt/eslint@0.7.2, @nuxtjs/supabase@1.4.3, @nuxt/ui@3.0.0-alpha.9, @nuxt/content@2.13.4, @nuxt/image@1.8.1, @nuxt/devtools@1.6.3, @nuxtjs/device@3.2.4, @nuxtjs/seo@2.0.2, @nuxtjs/stylelint-module@5.2.0, @nuxtjs/i18n@9.1.1, nuxt-time@1.0.3, @vite-pwa/nuxt@0.10.6, @vueuse/nuxt@12.0.0, @pinia/nuxt@0.8.0, pinia-plugin-persistedstate/nuxt, dayjs-nuxt@2.1.11
- Build Modules:    -
------------------------------
```

![Image](https://github.com/user-attachments/assets/44a5087f-9cef-42fa-8516-b139d010d9d6)

**Comment by lixiao258** [comment]
[unhandledRejection] Cannot find module '***\.pnpm\@babel+generator@7.26.3\node_modules\@jridgewell\gen-mapping\dist\gen-mapping.umd.js'

**Comment by jaeyeong94** [comment]
me too

**Comment by alifnuryana** [comment]
I thought I was the only one experiencing this

**Comment by muneer-ahmed-khan** [comment]
![Image](https://github.com/user-attachments/assets/e303dcbd-c9cf-438c-974a-12829535f71c)
Newly Created Nuxt Project and countinously getting the error in the screenshot.

**Comment by HugoRCD** [comment]
Same 🖐️

**Comment by CharlesBT** [comment]
+1 the same here without any code change

**Comment by HugoRCD** [comment]
For the moment, you can use this workaround by overriding the package version:

```
"overrides": {
    "@jridgewell/gen-mapping": "0.3.5"
 }
```

**Comment by yeonjulee1005** [comment]
@HugoRCD  Thank you my friend!! :)

**Comment by muneer-ahmed-khan** [comment]
@HugoRCD , I have added the required changes to the package.json, but I am still encountering the same error. Could you kindly confirm if I may be missing any additional steps or if I am applying the changes incorrectly?

"overrides": {
    "@jridgewell/gen-mapping": "0.3.5"
 }

![Image](https://github.com/user-attachments/assets/d76f7c79-cc8c-4691-b1b8-fc484ee7cfd1)
![Image](https://github.com/user-attachments/assets/ff87aaf2-9248-46c8-b4ed-cfcd8f2cdb6e)

**Comment by danielroe** [comment]
This was a bug in publishing `@jridgewell/gen-mapping`: https://github.com/jridgewell/gen-mapping/issues/14.

It's now resolved.

You can use overrides/resolutions to force your package manager to pick up `0.3.5`.

**Comment by YuZih** [comment]
@danielroe Thanks! It works!
