### ISSUE TITLE
nuxt prepare fails during postinstall with "nuxt is not recognized as an internal or external command" after fresh install with npm install

### ISSUE THREAD

**Issue by ivanpuglia** [nuxt/nuxt#30210]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v22.12.0
- Nuxt Version:     ^3.13.0
- CLI Version:      3.16.0
- Nitro Version:    2.10.4
- Package Manager:  npm@10.9.0
- Builder:          -
- User Config:      default
- Runtime Modules:  nuxt-vuefire@1.0.4, @nuxtjs/i18n@^9.1.1, @pinia/nuxt@0.9.0, @vite-pwa/nuxt@^0.6.0, dayjs-nuxt@^2.1.11
- Build Modules:    -
------------------------------

### Reproduction

1. I cloned the repository.
2. I ran npm install to install all dependencies.
3. During the installation, the postinstall script fails when trying to execute nuxt prepare.
4. The following error message appears in the terminal:

npm warn cleanup Failed to remove some directories [
( a list of a lot of dirs)
and:
'nuxt' is not recognized as an internal or external command,
operable program or batch file.

### Describe the bug

Hi, after cloning the repository and performing a fresh installation with npm install, I encounter an issue during the postinstall phase when it tries to run nuxt prepare. The error message is:

'nuxt' is not recognized as an internal or external command, 
operable program or batch file.

Additionally, when running npm install, I get several deprecation warnings, including:

npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated npmlog@5.0.1: This package is no longer supported.
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported.
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported.
npm WARN deprecated are-we-there-yet@2.0.0: This package is no longer supported.
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead.
npm WARN deprecated gauge@3.0.2: This package is no longer supported.

I have tried deleting the node_modules folder and running npm install again, but the error persists.
I have tried clearing npm cache with npm cache clean --force, but that did not resolve the issue.
I have also tried running nuxt prepare manually after installation, but it fails with the same message.

### Additional context

[2024-12-09T16_23_30_826Z-debug-0.log](https://github.com/user-attachments/files/18064561/2024-12-09T16_23_30_826Z-debug-0.log)

### Logs

```shell-script

```

**Comment by ivanpuglia** [comment]
Important Note:
This issue started occurring in the last few days, and there have been no changes to the repository itself that could explain it. Additionally, I do not face any problems when deploying the project to production on DigitalOcean app platform.

**Comment by OskarLebuda** [comment]
I see that you are using Windows machine. The NPM executable is on the `C:\` disk but you repo is on `D:\`. Are you sure that NPM has proper access to `D:\` disk?

**Comment by OskarLebuda** [comment]
Can you share some reproducible repo? I think cannot help without that 😔 Or maybe the `nuxt.config.ts` and `package.json`?

**Comment by ivanpuglia** [comment]
yes!
package.json:
{
  "name": "ebooking-web",
  "private": true,
  "scripts": {
    "build:digitalocean": "node --max-old-space-size=8048 node_modules/nuxt/bin/nuxt.mjs build",
    "build": "node --max-old-space-size=8048 node_modules/nuxt/bin/nuxt.mjs build",
    "dev": "nuxt dev --dotenv dev.env",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare",
    "start": "node .output/server/index.mjs",
    "pwa": "nr dev:preview:build"
  },
  "engines": {
     "node": "22.5.1"
  },
  "devDependencies": {
    "@nuxtjs/i18n": "^8.0.0",
    "@vite-pwa/nuxt": "^0.6.0",
    "dayjs-nuxt": "^2.1.9",
    "material-design-icons-iconfont": "^6.7.0",
    "nuxt": "^3.14.1592",
    "vite-plugin-vuetify": "^2.0.3",
    "vue": "^3.4.21",
    "vue-router": "^4.2.5"
  },
  "dependencies": {
    "@aws-sdk/client-s3": "^3.686.0",
    "@devindex/vue-mask": "^2.0.3",
    "@firebase/app-types": "^0.9.1",
    "@mdi/font": "^7.1.96",
    "@nuxt/http": "^0.6.4",
    "@nuxtjs/axios": "^5.13.6",
    "@pinia/nuxt": "^0.5.1",
    "@vavt/cm-extension": "^1.5.0",
    "@vite-pwa/assets-generator": "^0.2.4",
    "@vuepic/vue-datepicker": "^8.8.1",
    "dayjs": "^1.11.10",
    "defu": "^6.1.4",
    "firebase": "^10.8.1",
    "firebase-admin": "^12.5.0",
    "firebase-functions": "^5.0.0",
    "md-editor-v3": "^4.21.0",
    "nuxt-vuefire": "^1.0.4",
    "pinia": "^2.2.2",
    "sass": "^1.57.1",
    "swiper": "^8.4.6",
    "v-phone-input": "^4.3.2",
    "vue-country-flag-next": "^2.3.2",
    "vue-paycard": "^0.7.0",
    "vue3-perfect-scrollbar": "^2.0.0",
    "vue3-toastify": "^0.2.2",
    "vuefire": "^3.2.0",
    "vuetify": "^3.7.2"
  }
}

nuxt.config.ts :
export default defineNuxtConfig({
  css: ['~/assets/scss/global.scss'],

  build: {
    transpile: ['vuetify'],
  },

  pages: true,

  app: {
    head: {
      charset: 'utf-8',
      viewport: 'width=device-width, initial-scale=1',
      title: process.env.SITE_NAME,
      meta: [
        // <meta name="description" content="My amazing site">
        { name: 'description', content: '' },
        { name: 'keywords', content: '' },
        {
          name: "og:image", content: '',
        },
      ],
      link: [{ rel: 'icon', type: 'image/png', href: '/img/favicon.png' }]
    },
    pageTransition: { name: 'page', mode: 'out-in' }
  },

  vite: {
    define: {
      'process.env.DEBUG': false,
    },
    ssr: {
      noExternal: ['vuetify', 'v-phone-input'],
    },
    optimizeDeps: {
      exclude: ['fsevents']
    },
    cacheDir: '.vite-cache',
  },

  modules: [
    'nuxt-vuefire',
    '@nuxtjs/i18n',
    '@pinia/nuxt',
    '@vite-pwa/nuxt',
    'dayjs-nuxt'
  ],

  devtools: { enabled: false },

  vuefire: {
    config: {
      apiKey: process.env.FIREBASE_API_KEY,
      authDomain: process.env.FIREBASE_AUTH_DOMAIN,
      projectId: process.env.FIREBASE_PROJECT_ID,
      storageBucket: process.env.FIREBASE_STORAGE_BUCKET,
      messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID,
      appId: process.env.FIREBASE_APP_ID,
      measurementId: process.env.FIREBASE_MEASUREMENT_ID,
      databaseURL: process.env.FIREBASE_DATABASE_URL
    }
  },

  dayjs: {
    locales: ['es','en'],
    plugins: ['relativeTime', 'utc', 'timezone','localizedFormat'],
    defaultLocale: 'es',
  },

  pwa: {
    manifest: {
      theme_color: "#F05C22",
      background_color: "#FFFFFF",
      display: "standalone",
      name: "ebooking",
      short_name: "ebooking",
      description: "ebooking App",
      icons: [
        {
          "src": "/icons/icon-192x192.png",
          "sizes": "192x192",
          "type": "image/png",
          "purpose": "any"
        },
        {
          "src": "/icons/icon-256x256.png",
          "sizes": "256x256",
          "type": "image/png"
        },
        {
          "src": "/icons/icon-384x384.png",
          "sizes": "384x384",
          "type": "image/png"
        },
        {
          "src": "/icons/icon-512x512.png",
          "sizes": "512x512",
          "type": "image/png"
        }
      ]
    },
    workbox: {
      navigateFallback: '/'
    },
    devOptions: {
      enabled: false,
      type: 'module'
    }
  },

  i18n: {
    vueI18n: './utils/nuxt-i18n.js'
  },

  runtimeConfig: {
    public: {
     HIDDEN DATA
    }
  },

  nitro: {
    compatibilityDate: '2024-12-01'
  }
})

**Comment by ivanpuglia** [comment]
I find a bug on a package version and now i can install and build sorry for the inconvenience, your comment gave me an idea! thanks

**Comment by alwaisy** [comment]
> I find a bug on a package version and now i can install and build sorry for the inconvenience, your comment gave me an idea! thanks

what was the bug. 
i am struggling for one hour. 
my old project is broken. 
new installed with bun and npm both facing exactly same issue. 

- ubuntu 24 lts
- npm or bun

**Comment by Saket6198** [comment]
Hey still facing the same issue. Getting

. postinstall$ nuxt prepare
│  ERROR  Cannot find native binding. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try npm i aga…  
│     at /D:/project/portfolio/saket-portfolio-nuxt/node_modules/.pnpm/oxc-parser@0.110.0/node_modules/oxc-parser/src-js/bindings.js:575:11
│     at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
│     at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
│     at async loadNuxt (/D:/project/portfolio/saket-portfolio-nuxt/node_modules/.pnpm/@nuxt+kit@4.3.0_magicast@0.5.1/node_modules/@nuxt/kit/dist/i…  
│     at async Object.run (/D:/project/portfolio/saket-portfolio-nuxt/node_modules/.pnpm/@nuxt+cli@3.32.0_cac@6.7.14_magicast@0.5.1/node_modules/@n…  
│     at async runCommand (/D:/project/portfolio/saket-portfolio-nuxt/node_modules/.pnpm/citty@0.1.6/node_modules/citty/dist/index.mjs:316:16)
│     at async runCommand (/D:/project/portfolio/saket-portfolio-nuxt/node_modules/.pnpm/citty@0.1.6/node_modules/citty/dist/index.mjs:307:11)
│     at async runMain (/D:/project/portfolio/saket-portfolio-nuxt/node_modules/.pnpm/citty@0.1.6/node_modules/citty/dist/index.mjs:445:7)
│   [cause]: Cannot find module '@oxc-parser/binding-win32-x64-msvc'
│ Require stack:
│ - D:\project\portfolio\saket-portfolio-nuxt\node_modules\.pnpm\oxc-parser@0.110.0\node_modules\oxc-parser\src-js\bindings.js
│       at Module._resolveFilename (node:internal/modules/cjs/loader:1142:15)
│       at Module._load (node:internal/modules/cjs/loader:983:27)
│       at Module.require (node:internal/modules/cjs/loader:1230:19)
│       at require (node:internal/modules/helpers:179:18)
│       at requireNative (/D:/project/portfolio/saket-portfolio-nuxt/node_modules/.pnpm/oxc-parser@0.110.0/node_modules/oxc-parser/src-js/bindings.…  
│       at /D:/project/portfolio/saket-portfolio-nuxt/node_modules/.pnpm/oxc-parser@0.110.0/node_modules/oxc-parser/src-js/bindings.js:530:17
│       at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
│       at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
│       at async loadNuxt (/D:/project/portfolio/saket-portfolio-nuxt/node_modules/.pnpm/@nuxt+kit@4.3.0_magicast@0.5.1/node_modules/@nuxt/kit/dist…  
│       at async Object.run (/D:/project/portfolio/saket-portfolio-nuxt/node_modules/.pnpm/@nuxt+cli@3.32.0_cac@6.7.14_magicast@0.5.1/node_modules/…  
│     [cause]: Cannot find module './parser.win32-x64-msvc.node'
│ Require stack:
│ - D:\project\portfolio\saket-portfolio-nuxt\node_modules\.pnpm\oxc-parser@0.110.0\node_modules\oxc-parser\src-js\bindings.js
│         at Module._resolveFilename (node:internal/modules/cjs/loader:1142:15)
│         at Module._load (node:internal/modules/cjs/loader:983:27)
│         at Module.require (node:internal/modules/cjs/loader:1230:19)
│         at require (node:internal/modules/helpers:179:18)
│         at requireNative (/D:/project/portfolio/saket-portfolio-nuxt/node_modules/.pnpm/oxc-parser@0.110.0/node_modules/oxc-parser/src-js/binding…  
│         at /D:/project/portfolio/saket-portfolio-nuxt/node_modules/.pnpm/oxc-parser@0.110.0/node_modules/oxc-parser/src-js/bindings.js:530:17       
│         at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
│         at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
│         at async loadNuxt (/D:/project/portfolio/saket-portfolio-nuxt/node_modules/.pnpm/@nuxt+kit@4.3.0_magicast@0.5.1/node_modules/@nuxt/kit/di…  
│         at async Object.run (/D:/project/portfolio/saket-portfolio-nuxt/node_modules/.pnpm/@nuxt+cli@3.32.0_cac@6.7.14_magicast@0.5.1/node_module…  
│  ERROR  Cannot find native binding. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try npm i aga…  
└─ Failed in 1.3s at D:\project\portfolio\saket-portfolio-nuxt
 ELIFECYCLE  Command failed with exit code 1.
