### ISSUE TITLE
Pages remount on browser back button

### ISSUE THREAD

**Issue by borghol** [nuxt/nuxt#30221]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.20.3`
- Nuxt Version:     `3.14.1592`
- CLI Version:      `3.16.0`
- Nitro Version:    `2.10.4`
- Package Manager:  `yarn@1.22.21`
- Builder:          `-`
- User Config:      `default`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

I created a default project with two pages:
- Home
- About

Where each one has a link to the other, and a log statement in the onMounted function. 

https://github.com/borghol/nuxt-mount-issue

### Describe the bug

Running the application (SSR or dev mode) and using the browser's back within the pages causes the page to remount.

Everywhere that I found says that this should not be the case.

The actual full application relies on page state when a browser goes back (i.e. infinite scroll).

### Logs

```shell-script

```

**Comment by fabianwohlfart** [comment]
There is no property `cache` in definePageMeta, it's `keepalive`.
For a direct ascendant of app.vue I think you have to do this `<NuxtPage keepalive />`, this works.
Yet it seems buggy as you cannot opt out from it.

test.vue
```
definePageMeta({
  keepalive: false
})
```
https://stackblitz.com/edit/github-2fqdfenu

***

defining `keepalive: true` in nuxt.config.js and opting out with definePageMeta seems to work though

nuxt.config.js
```
app: {
  keepalive: true
}
```
https://stackblitz.com/edit/github-2fqdfenu-pg9mmqwd

**Comment by borghol** [comment]
Amazing, this works so I'm closing the issue.

Is there a reason why keep alive is not the default? It seems weird that a browser back should cause all fetched data to refetch.
