### ISSUE TITLE
KeepAlive didn't work with NuxtLayout

### ISSUE THREAD

**Issue by machinesily** [nuxt/nuxt#30225]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.5.1
- Nuxt Version:     3.14.1592
- CLI Version:      3.16.0
- Nitro Version:    2.10.4
- Package Manager:  pnpm@9.0.4
- Builder:          -
- User Config:      default
- Runtime Modules:  @pinia/nuxt@0.5.5, pinia-plugin-persistedstate/nuxt, nuxt-swiper@1.2.2
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-pgnvdpnq-ltuq9zba?file=app.vue

### Describe the bug

When switching between cached and unCached pages, cache will loss

didn't use NuxtLayout switch to unCached pages
![Image](https://github.com/user-attachments/assets/663c6f76-3d01-4047-b037-8d55ec9578ab)

use NuxtLayout switch to unCached pages, missing index page cached
![Image](https://github.com/user-attachments/assets/10818744-38a2-4ba4-996e-1003c38c9639)

### Logs

```shell-script

```

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/27401.
