### ISSUE TITLE
Cloudflare pages build cache is not caching `.nuxt` folder

### ISSUE THREAD

**Issue by mathix420** [nuxt/nuxt#30242]
### Environment

Cloudflare pages (using nuxt hub)
```
16:38:47.701	Using v2 root directory strategy
16:38:47.723	Success: Finished cloning repository files
16:38:49.279	Checking for configuration in a Wrangler configuration file (BETA)
16:38:49.279	
16:38:49.419	No wrangler.toml file found. Continuing.
16:38:49.507	Restoring from dependencies cache
16:38:49.524	Restoring from build output cache
16:38:50.103	Success: Build output restored from build cache.
16:38:54.277	Success: Dependencies restored from build cache.
16:38:54.463	Detected the following tools from environment: bun@1.1.31, nodejs@18.17.1
```

### Reproduction

https://github.com/mathix420/free-the-web-apps

### Describe the bug

All assets seems to be regenerated on every deployment, at least IPX static assets.
```
16:50:29.290	[log] [nitro]   ├─ /_ipx/w_1280&f_png&q_100/screenshot/framer.png (41263ms)
16:50:29.290	[log] [nitro]   ├─ /_ipx/w_1024&f_png&q_100/screenshot/framer.png (44097ms)
16:50:29.291	[log] [nitro]   ├─ /_ipx/w_1536&f_png&q_100/screenshot/framer.png (45620ms)
16:50:29.291	[log] [nitro]   ├─ /_ipx/w_2048&f_avif&q_100/screenshot/framer.png (52516ms)
```

### Additional context

Cloudflare seems to have forgotten to cache the `.nuxt` folder https://developers.cloudflare.com/pages/configuration/build-caching/#frameworks

### Logs

```shell-script

```

**Comment by danielroe** [comment]
we do not yet cache `/_ipx` locally: https://github.com/nuxt/image/issues/795.

with `buildCache` (which is currently experimental) we cache Nuxt assets in `node_modules/.cache` which should be restored by Nuxt.

(Cloudflare and other providers shouldn't cache `.nuxt`.)
