### ISSUE TITLE
`app.vue` file is totally ignored

### ISSUE THREAD

**Issue by martinszeltins** [nuxt/nuxt#30265]
### Environment

````
------------------------------
- Operating System: Ubuntu 20.04 LTS Linux
- Node Version:     v20.12.2
- Nuxt Version:     3.14.1592
- CLI Version:      3.16.0
- Nitro Version:    2.10.4
- Package Manager:  pnpm@9.15.0
- Builder:          -
- User Config:      default
- Runtime Modules:  -
- Build Modules:    -
------------------------------
````

### Reproduction

https://stackblitz.com/~/github.com/martinszeltins/nuxt-app-vue-ignored

### Describe the bug

I am working with pages and layers and my `app.vue` file gets completely ignored.

**Screenshot:**
![Image](https://github.com/user-attachments/assets/323883d7-fc2c-4fe3-9a3f-ee084e1a6f91)

### Logs

```shell-script

```

**Comment by cernymatej** [comment]
It looks like you are using the version 4 directory structure without it being enabled, so Nuxt uses the default `app.vue`.
You need to either move the `app.vue` file to the root of the project, or enable `future.compatibilityVersion = 4` in your `nuxt.config.ts`.

Here is a working example:
https://stackblitz.com/~/github.com/martinszeltins/nuxt-app-vue-ignored?file=app.vue

**Comment by martinszeltins** [comment]
@cernymatej actually, I DO have `future.compatibilityVersion = 4` enabled, maybe the layers haven't merged properly.

https://github.com/martinszeltins/nuxt-app-vue-ignored/blob/master/app/common/nuxt.config.ts#L21

**Comment by cernymatej** [comment]
Oh, in layers, I see. Well, this is something that you have to configure per-project.

**Comment by manniL** [comment]
It needs to be defined per layer at the moment (see https://github.com/nuxt/nuxt/issues/27904#issuecomment-2198106225).

**Comment by martinszeltins** [comment]
> It needs to be defined per layer at the moment (see [#27904 (comment)](https://github.com/nuxt/nuxt/issues/27904#issuecomment-2198106225)).
> 
> This allows interop with layers that are still on v3 or deliberately don't want to opt into the v4 changes (yet).

@manniL I think the docs should mention something about this, otherwise it is confusing and undocumented behavior. From what I understand this is a temporary "bug"

**Comment by manniL** [comment]
@martinszeltins 100% PR welcome! (will reopen #27904 for that).

**Comment by martinszeltins** [comment]
> % PR welcome! (will reopen https://github.com/nuxt/nuxt/issues/27904 for that).

PR - https://github.com/nuxt/nuxt/pull/30274
