### ISSUE TITLE
render:html 钩子中如何获取页面中服务端已请求过的数据

### ISSUE THREAD

**Issue by wslxm** [nuxt/nuxt#30269]
### Describe the feature

问题描述： 我想在 render:html 修改响应内容，但需要依赖之前向服务器调用接口获取到的数据，我在钩子中没有找到获取数据的方法
希望行为： 我在 page/index 页面的服务端代码中已通过  useFetch 获取到的数据, 能在 render:html  hooks 中直接使用该数据来动态生成我想插入到 html 中的代码
```
/**
 * 响应处理器
 */
export default defineNitroPlugin((nitroApp) => {
    // 在构造 HTML 之前
    nitroApp.hooks.hook('render:html', (html, {event}) => {
        // 获取请求对象
        // const req = event.node.req;
        // 现在你可以使用 req 对象来访问请求信息了
        console.log('URI:', event.req.url);
        console.log('headers:', event.req.headers);
        console.log('headers.host:', event.req.headers.host);
        console.log('event.context :', event.context);
    })

    // 在发送响应之前调用
    // nitroApp.hooks.hook('render:response', (response, {event}) => {
    //     console.log('render:response', response)
    // })
})
```

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [x] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [x] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by wslxm** [comment]
> 您能否进一步解释一下您正在尝试什么以及什么不起作用，也许可以重现一下？您可以添加数据`event.context`，这似乎可以满足您的需求。



> Could you explain a bit more about what you're trying and what isn't working, perhaps with a reproduction? You can add data to `event.context` and this seems to meet your needs.


如:   pages/index.vue 中有一个 useFetch 的请求，它是在服务端发起的请求
```
//  pages/index.vue 
let  config = useFetch("/api/xxx/getConfig") 
```
我希望我在 render:html 钩子中能够读取 pages/index.vue 中 useFetch 请求到的  config 数据， 因为它已经在 pages/index.vue 的服务端代码中使用 useFetch  请求了一次数据了，我不想再  render:html 在发一次 http 请求
```
    nitroApp.hooks.hook('render:html', (html, {event}) => {
           //  event.context.config  
    })
```
我没有找到在  pages/index.vue  的服务端代码中将 config 数据写到 event.context 的方法， 我在 render:html 中读取不到这个数据

**Comment by danielroe** [comment]
You can use `useRequestEvent()` in `pages/index.vue` and write `event.context` there.

**Comment by wslxm** [comment]
问题已解决，感谢

**Comment by wslxm** [comment]
问题已解决，感谢

**Comment by w569638598** [comment]
你是要把后端请求回来的数据也显示在页面源码里面吗？我现在文章详情，请求回来数据，然后在浏览器点击查看网页源码的时候，也是不显示，你是咋处理的？

**Comment by wslxm** [comment]
> 你是要把后端请求回来的数据也显示在页面源码里面吗？我现在文章详情，请求回来数据，然后在浏览器点击查看网页源码的时候，也是不显示，你是咋处理的？

你这个和我的问题不一样，我的是后续处理页面 SEO 数据和matomo埋点/谷歌埋点等需要文章的数据和一些后台的系统配置数据，你这个问题应该关注请求是服务端发出的还是用户端发出的， useFetch 第一次是服务端发出的，那么html返回到浏览器就已经在服务端渲染好了html，源码里面就有文章详情数据了，你可以看看浏览器是否发出了请求，第一次访问浏览器发出了请求说明请求方式有问题

**Comment by w569638598** [comment]
我使用useFetch，浏览器只发出了一次请求。
[cid:47b94ee3-a23d-49ad-934b-6933a3209075]
[cid:755dcac6-2ab7-4e57-b52a-458424b5f7c9]
________________________________
发件人: 兮家小二 ***@***.***>
发送时间: 2024年12月17日 14:13
收件人: nuxt/nuxt ***@***.***>
抄送: w569638598 ***@***.***>; Comment ***@***.***>
主题: Re: [nuxt/nuxt] render:html 钩子中如何获取页面中服务端已请求过的数据 (Issue #30269)


你是要把后端请求回来的数据也显示在页面源码里面吗？我现在文章详情，请求回来数据，然后在浏览器点击查看网页源码的时候，也是不显示，你是咋处理的？

你这个和我的问题不一样，我的是后续处理页面 SEO 数据和matomo埋点/谷歌埋点等需要文章的数据和一些后台的系统配置数据，你这个问题应该关注请求是服务端发出的还是用户端发出的， useFetch 第一次是服务端发出的，那么html返回到浏览器就已经在服务端渲染好了html，源码里面就有文章详情数据了，你可以看看浏览器是否发出了请求，第一次访问浏览器发出了请求说明请求方式有问题

―

**Comment by wslxm** [comment]
> 我使用useFetch，浏览器只发出了一次请求。 [cid:47b94ee3-a23d-49ad-934b-6933a3209075] [cid:755dcac6-2ab7-4e57-b52a-458424b5f7c9]


第一次请求是服务端发出的，浏览器应该是一次请求也没有，浏览器发出的请求获取的数据，那就变成了vue3的逻辑的，变成客户端渲染了，源码里面肯定看不到文章数据

**Comment by wslxm** [comment]
> 大哥大哥大哥，那服务器发请求应该怎么写啊？或者我能学习一下你的nuxt项目吗？



你可以看看这视频里面的 14/15 + 24/25 部分, 详细说了服务端/客户端渲染流程和请求方法

[https://www.bilibili.com/video/BV1A8mUYeEgB/?spm_id_from=333.337.search-card.all.click&vd_source=015a78444c6f0ed13fb4174dcf3af5eb](https://www.bilibili.com/video/BV1A8mUYeEgB/?spm_id_from=333.337.search-card.all.click&vd_source=015a78444c6f0ed13fb4174dcf3af5eb)

**Comment by w569638598** [comment]
好的，感谢。

________________________________
发件人: 兮家小二 ***@***.***>
发送时间: 2024年12月18日 9:08
收件人: nuxt/nuxt ***@***.***>
抄送: w569638598 ***@***.***>; Comment ***@***.***>
主题: Re: [nuxt/nuxt] render:html 钩子中如何获取页面中服务端已请求过的数据 (Issue #30269)


大哥大哥大哥，那服务器发请求应该怎么写啊？或者我能学习一下你的nuxt项目吗？

你可以看看这视频里面的 14/15 + 24/25 部分, 详细说了服务端/客户端渲染流程和请求方法

https://www.bilibili.com/video/BV1A8mUYeEgB/?spm_id_from=333.337.search-card.all.click&vd_source=015a78444c6f0ed13fb4174dcf3af5eb

―
