### ISSUE TITLE
Using conditional component rendering, ClientOnly does not work.

### ISSUE THREAD

**Issue by snakysnake** [nuxt/nuxt#30295]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.17.0
- Nuxt Version:     3.12.3
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  yarn@1.22.22
- Builder:          -
- User Config:      runtimeConfig, app, modules, target, ssr, typescript, build, css, components, routeRules, hooks
- Runtime Modules:  xxxxxxxxxxxxx
- Build Modules:    -
------------------------------

### Reproduction

ClientOnly or client-only both don't work, when using <component :is=""... />
```
<template>
  <component
    :is="condition ? 'client-only' : 'div'"
    fallback-tag="span"
    fallback="Loading ..."
  >
    <p>hello world </p>
  </component>
</template>
```
It just renders \<client-only\> in the browser, which is not what should happen.
For comparison:
```
<template>
   <ClientOnly>
    <p>hello world </p>
   </ClientOnly>
<template>
```

### Describe the bug

I think it's pretty clear, just copy & paste the above code in your project and compare to the code below, and see for yourself.

### Logs

```shell-script

```

**Comment by cernymatej** [comment]
You need to import the component.
```ts
import { ClientOnly } from '#components'
```

```vue
<component :is="condition ? ClientOnly : 'div'">
```

**Comment by snakysnake** [comment]
Thanks for the quick help @cernymatej solution works!
