### ISSUE TITLE
SSR - Layout on Netlify

### ISSUE THREAD

**Issue by luca-smartpricing** [nuxt/nuxt#30320]
### Environment

- Operating System: Darwin
- Node Version:     v20.18.0
- Nuxt Version:     3.14.1592
- CLI Version:      3.17.0
- Nitro Version:    2.10.4
- Package Manager:  npm@10.8.2
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxt/eslint@0.5.7, @nuxtjs/tailwindcss@6.12.2, @vueuse/nuxt@10.11.1, @nuxtjs/prismic@3.4.6, @nuxtjs/i18n@8.5.6, @nuxtjs/seo@2.0.2, @nuxt/image@1.8.1, @nuxt/icon@1.10.3, @formkit/nuxt@1.6.9, @nuxt/fonts@0.7.2, @nuxt/scripts@0.9.5
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-8xwyudsu?file=app.vue

### Describe the bug

If you publish the reproduction on Netlify, SSR on the non prerender page doesn't work. It doesn't work only if you wrap <NuxtPage> with <NuxtLayout>. 
This broke the entire site. 
There's also an hydration warning: `Hydration completed but contains mismatches.`

### Additional context

On Netlify function log there's no SSR log. 

### Logs

```shell-script
Fetch data value: null
D_koGLRR.js:1 Fetch error value: null
D_koGLRR.js:1 Client - Fetch data value: null
D_koGLRR.js:1 Client - Fetch error value: null
D_koGLRR.js:1 On watchEffect Fetch data value: null
D_koGLRR.js:1 On watchEffect Fetch error value: null
D_koGLRR.js:1 On mounted Fetch data value: null
D_koGLRR.js:1 On mounted Fetch error value: null
D_koGLRR.js:1 On watchEffect Fetch data value: Proxy(Object) {status: 'ok', method: 'GET'}
D_koGLRR.js:1 On watchEffect Fetch error value: null
```

**Comment by danielroe** [comment]
It was resolved in https://github.com/nuxt/nuxt/pull/30203 and will be released in v3.15.
