### ISSUE TITLE
using the useHead API to set the page title, strangely, the titleTemplate attr returns titles that are automatically capitalized

### ISSUE THREAD

**Issue by sylic** [nuxt/nuxt#30327]
### Environment

- Operating System: Windows_NT
- Node Version:     v22.5.1
- Nuxt Version:     3.14.1592
- CLI Version:      3.17.1
- Nitro Version:    2.10.4
- Package Manager:  yarn@1.22.22
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxt/fonts@0.10.3, @nuxt/icon@1.10.3, @nuxtjs/color-mode@3.5.2, @nuxt/content@2.13.4
- Build Modules:    -

### Reproduction

https://github.com/user-attachments/assets/4d7adbd0-8fae-485e-bf53-de206f78740e

### Describe the bug

I created the ` middleware `folder in the root of the project and added the` router.global.ts` file. Here is the code to set the title of the page:    
// router.global.ts 
```
export default defineNuxtRouteMiddleware((to, _from) => {
   console.log(to.path); // here it prints: "/me" ,
   useHead(
    {

    title: to.path,

    titleTemplate: (titleChunk) => {

      console.log(titleChunk); // here it prints: "Me", It appears that titleChunk will incorrectly capitalize the first letter of the input path.

      const title = `${titleChunk?.replace(/^\/+/, '')}`

      console.log("⭐ ~ 当前打印的内容 ~ :", title); // here it prints: "Me";

      return title;

    }
  })})
```

As the video shows, the string returned by `titleTemplate `does not automatically capitalize when switching between other routes,  the related code is there: https://github.com/sylic/blog/blob/main/middleware/router.global.ts

### Logs

```shell-script

```

**Comment by danielroe** [comment]
This is likely to be an upstream issue in https://github.com/unjs/unhead.

cc: @harlan-zw

**Comment by harlan-zw** [comment]
The issue is due to Nuxt Content inserting the head tags for you within the `ContentDoc` component, see https://github.com/nuxt/content/blob/main/src/runtime/components/ContentDoc.vue#L102

Either disable the content head or set your own title within the markdown file (or modify your titleChunk code).

```yml
---
title: me
---
```
