### ISSUE TITLE
LayoutComponent: undefined is not an object (evaluating 'a.default') error.

### ISSUE THREAD

**Issue by hubfactory** [nuxt/nuxt#30338]
### Environment

- Operating System: Darwin
- Node Version:     v20.18.1
- Nuxt Version:     3.14.1592
- CLI Version:      3.17.0
- Nitro Version:    2.10.4
- Package Manager:  npm@10.8.2
- Builder:          -
- User Config:      default
- Runtime Modules:  @vueuse/nuxt@10.11.1, @vee-validate/nuxt@4.14.7, nuxt-lodash@2.5.3, ()
- Build Modules:    -

### Reproduction

I am using Nuxt 3 together with Vuetify.

There are several layout files, and the `app.vue` file looks like this:

```vue
<template>
  <div>
    <NuxtLayout>
      <NuxtPage />
    </NuxtLayout>
  </div>
</template>
```

Each layout file is structured like this:

```vue
<template>
  <v-app>
    <div class="wrapper">
      <main class="main">
        <slot />
      </main>
    </div>
  </v-app>
</template>
```

Basically, I use the `default` layout, but for pages that require a different layout, I specify it like this:

```vue
definePageMeta({
  layout: 'plain',
});
```

Additionally, SSR is not being used.

### Describe the bug

When viewing a page (transitioning), the following error sometimes occurs.

```
TypeError
undefined is not an object (evaluating 'a.default')
```

`node_modules/nuxt/dist/app/components/nuxt-layout.js`
```
  props: {
    name: String,
    layoutProps: Object
  },
  async setup(props, context) {
    const LayoutComponent = await layouts[props.name]().then((r) => r.default || r);
    return () => h(LayoutComponent, props.layoutProps, context.slots);
  }
});
export default defineComponent({
  name: "NuxtLayout",
```

`const LayoutComponent = await layouts[props.name]().then((r) => r.default || r);`

An error occurs at this point.

### Additional context

The error is especially occurring on iOS Safari.

### Logs

```shell-script

```

**Comment by VDidyk** [comment]
There is already opened issue
https://github.com/nuxt/nuxt/issues/29624

**Comment by danielroe** [comment]
This is resolved in https://github.com/nuxt/nuxt/pull/29957

**Comment by hubfactory** [comment]
@VDidyk @danielroe 

Thank you for the information. I will update nuxt to the latest version and try it.
