### ISSUE TITLE
`asyncContext` does not see the new route after navigation

### ISSUE THREAD

**Issue by martinszeltins** [nuxt/nuxt#30356]
### Environment

````
------------------------------
- Operating System: Linux (Ubuntu 24.04 LTS)
- Node Version:     v22
- Nuxt Version:     3.14.159
- CLI Version:      3.15.0
- Nitro Version:    -
- Package Manager:  npm@9.5.0
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------
````

### Reproduction

https://stackblitz.com/~/github.com/martinszeltins/async-context-test

### Describe the bug

I noticed that if I enable `experimental.asyncContext` and I navigate to a new route, then `useRoute()` still sees the old route. It seems to happen only when using layers (EDIT: As @cernymatej  pointed out in https://github.com/nuxt/nuxt/issues/30356#issuecomment-2561060219 it is reproducable also without layers). I have a simple app with a page and there is a component inside the page. This component uses a composable and the composable uses `useRoute()` to get the current route. When I navigate to a new route, the composable still sees the old route.

But it is also interesting that this happens only on client-side navigation. If I refresh the page, then the composable sees the correct route.

Please see the reproduction and I also made a screencast to make it easier to see the issue. As you can see, when I enter the `/offices/123` route, the `useRoute()` does not see the new route.

**Screencast**:
https://github.com/user-attachments/assets/9e82e0c5-24c6-4611-95e3-2311d628ef87

### Logs

```shell-script

```

**Comment by martinszeltins** [comment]
@danielroe I wanted to clarify what you said in this comment https://github.com/nuxt/nuxt/pull/30360#issuecomment-2561452617.

> Turning on asyncContext should not affect client side behaviour at all - perhaps that's something to investigate?

I made a quick screencast where you can see that if I have `asyncContext` turned on then it does not work but when I turn it off then client-side navigation works. _(note: server-side navigation works fine always)_

**screencast:**
https://github.com/user-attachments/assets/b2988e57-ceb9-4cce-8516-499f132b641f

**Comment by danielroe** [comment]
@martinszeltins I understand. I'm saying that the desired behaviour is that it doesn't change anything in the browser.
