### ISSUE TITLE
WARN  [nuxt] Expected @nuxt/kit @nuxt/schema

### ISSUE THREAD

**Issue by kurt-grung** [nuxt/nuxt#30362]
### Environment

Apple M3, macOS Sequoia, Homebrew, NPM   

### Reproduction

New install / upgrade - 
`npx nuxi@latest init <app>`

### Describe the bug

```
WARN  [nuxt] Expected @nuxt/kit to be at least 3.14.1592 but got 3.12.2. 
WARN  [nuxt] Expected @nuxt/schema to be at least 3.14.1592 but got 3.12.2. 

This might lead to unexpected behavior. Check your package.json or refresh your lockfile.
```

### Logs

```shell-script

```

**Comment by danielroe** [comment]
Do you have a globally installed kit/nuxi?

**Comment by typed-sigterm** [comment]
I solved this by removing lockfile and re-intsall

**Comment by martinszeltins** [comment]
Hmm, I also removed my lockfile and reinstalled but still see this warning:

> [nuxt] Expected @nuxt/kit to be at least 3.15.4 but got 3.15.3. This might lead to unexpected behavior. Check your package.json or refresh your lockfile.

**Comment by kurt-grung** [comment]
> Do you have a globally installed kit/nuxi?

This was the fix. Not lockfile / re-install

Thanks @danielroe 🚀

**Comment by martinszeltins** [comment]
@kurt-grung no, I don't think I have @nuxt/kit installed globally, at least when I list my globally installed packages, it is not there. I also don't recall installing it globally.

```sh
martins@martins-tuxedo ~ $ npm list -g --depth=0
├── pm2@5.3.1
└── pnpm@9.1.1

martins@martins-tuxedo ~ $ pnpm list -g
No global packages
````

**Comment by kurt-grung** [comment]
@martinszeltins not sure man, that's what fixed mine! 

Had the issue for ages was really annoying.. couldn't find anything to fix it. 

Try deleting your global `node_modules` folder & `package-lock.json`. 
Also delete the projects `node_modules` folder & `package-lock.json`. 

Run `npm I` & `nuxi dev` 
Or `nuxi upgrade`
