### ISSUE TITLE
Bun text-based lockfile format (`bun.lock`) is not supported by the `nuxi upgrade` command

### ISSUE THREAD

**Issue by mrauhu** [nuxt/nuxt#30372]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v22.12.0
- Nuxt Version:     3.15.0
- CLI Version:      3.17.2
- Nitro Version:    2.10.4
- Package Manager:  bun@1.1.42
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxt/eslint@0.7.4, @pinia/nuxt@0.9.0, @vueuse/nuxt@12.2.0, pinia-plugin-persistedstate/nuxt
- Build Modules:    -
------------------------------

### Reproduction

1. Init project using Bun:

```sh
bun x nuxi@latest init example
cd example
```

2. Change lockfile to text-based `bun.lock`:

```sh
bun i --save-text-lockfile
```

3. Remove old binary `bun.lockb`:

```sh
rm bun.lockb
```

4. Try to upgrade:

```
bun x nuxi upgrade
```

### Describe the bug

Instead of upgrade you got an error:

```
ERROR  Unable to determine the package manager used by this project.

No lock files found in ..., and no packageManager field specified in package.json.

Please either add the packageManager field to package.json or execute the installation command for your package manager. For example, you can use pnpm i, npm i, bun i, or yarn i, and then try again.
```

### Additional context

> In Bun v1.2.0 the default lockfile format will change to `bun.lock`
https://bun.sh/docs/runtime/bunfig#install-savetextlockfile

### Logs

```shell-script

```

**Comment by danielroe** [comment]
resolved in https://github.com/nuxt/cli/pull/614
