### ISSUE TITLE
Pre-transform error when pinia store used in inline middleware

### ISSUE THREAD

**Issue by pont1s** [nuxt/nuxt#30378]
### Environment

- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.15.0
- CLI Version:      3.17.2
- Nitro Version:    2.10.4
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      default
- Runtime Modules:  @pinia/nuxt@0.9.0
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-zvdjtwqu

1. Run project in dev mode

### Describe the bug

After upgrading to 3.15, we started getting errors when running the project in dev mode on pages where pinia is used in inline middleware.

### Additional context

This is not reproduced in version 3.14.1592

### Logs

```shell-script
ERROR Pre-transform error: Maximum call stack size exceeded
Plugin: nuxt:pages-macros-transform
File: /home/projects/nuxt-starter-zvdjtwqu/pages/index.vue?macro=true
```

**Comment by danielroe** [comment]
may be related to the scope tracking work done in https://github.com/nuxt/nuxt/pull/30241

**Comment by pont1s** [comment]
Reproduction can be simplified and dependence on pinia can be removed.

The error occurs if we name a variable the same as the field in the object that we assign to the variable.

This example will work:
```
<script setup lang="ts">
import { useFoo } from '~/composables/use-meta';

const fooComposable = useFoo();

const diffrentName = fooComposable.foo;

definePageMeta({
  middleware: [
    () => {
      const fooComposable = useFoo();

      const diffrentName = fooComposable.foo;
    },
  ],
});
</script>
```

Reproduction 2: https://stackblitz.com/edit/nuxt-starter-8tji6yob

**Comment by cernymatej** [comment]
I can have a look at it if you don't have a wip yet @danielroe
