### ISSUE TITLE
Server bug on production

### ISSUE THREAD

**Issue by brokuka** [nuxt/nuxt#30395]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v22.12.0
- Nuxt Version:     3.15.0
- CLI Version:      3.17.2
- Nitro Version:    2.10.4
- Package Manager:  pnpm@9.15.1
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxt/eslint@0.7.4, @unocss/nuxt@0.65.3, template-copyright@1.0.1, @nuxt/icon@1.10.2, nuxt-time@1.0.3, @nuxtjs/color-mode@3.5.2, @nuxtjs/i18n@9.1.1
- Build Modules:    -
------------------------------

### Reproduction

Src - https://github.com/brokuka/portfolio
Demo - https://portfolio-chi-one-99.vercel.app/

### Describe the bug

Server api strange behavior on production, can't get more info about problem to fix it. 

To recreate buggy situation you need to enter to the `projects` page and refresh page.

### Additional context

![Image](https://github.com/user-attachments/assets/3c6071d5-f5ed-4008-be8a-8f62ce6f5217)

### Logs

```shell-script

```

**Comment by cernymatej** [comment]
This is most likely not a Nuxt bug.
Could you please provide a [minimal reproduction](https://nuxt.com/docs/community/reporting-bugs#create-a-minimal-reproduction) ?

**Comment by brokuka** [comment]
> This is most likely not a Nuxt bug. Could you please provide a [minimal reproduction](https://nuxt.com/docs/community/reporting-bugs#create-a-minimal-reproduction) ?

Problem not with `Nuxt`, it's `radix-vue` or `shadcn-vue` issue.
