### ISSUE TITLE
Error when disabling ssr

### ISSUE THREAD

**Issue by XpPort** [nuxt/nuxt#30398]
### Environment

**Environment**
- Operating System: Windows_NT
- Node Version:     v20.15.0
- Nuxt Version:     3.15.0
- CLI Version:      3.17.2
- Nitro Version:    2.10.4
- Package Manager:  npm@10.7.0
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxt/ui@3.0.0-alpha.9, @nuxt/eslint@0.7.4
- Build Modules:    -

### Reproduction

src: https://github.com/[XpPort/dashboard](https://github.com/XpPort/dashboard)

### Describe the bug
After disabling scr, an error appears related to the Nuxt build file problem.
The error will be presented below.

### Additional context

Config nuxt

```typescript
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: ["@nuxt/ui", "@nuxt/eslint"],
  css: ['./assets/css/main.css'],

  future: {
    compatibilityVersion: 4
  },

  compatibilityDate: "2024-11-27",
  ssr: false,
  devServer: {
    host: '0.0.0.0',
    port: 3000
  },
  server: {
    host: "0.0.0.0",
    port: 3000,
  }
})
``` 

### Logs

```shell-script
i Nuxt Icon server bundle mode is set to local                                                                                                                                                                            06:08:04
i Running with compatibility version 4                                                                                                                                                                                    06:08:05
√ Vite client built in 75ms                                                                                                                                                                                               06:08:07
√ Vite server built in 22ms                                                                                                                                                                                               06:08:07

 ERROR  [worker reload] [worker init] C:/Users/Faint/WebstormProjects/dashboard/.nuxt/dev/index.mjs failed                                                                                                            06:08:07  



  [cause]: Cannot find module 'C:\Users\Faint\WebstormProjects\dashboard\.nuxt\dev\index.mjs'

      at Function._resolveFilename (node:internal/modules/cjs/loader:1145:15)
      at Function._load (node:internal/modules/cjs/loader:986:27)
      at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
      at MessagePort.<anonymous> (node:internal/main/worker_thread:186:26)
      at [nodejs.internal.kHybridDispatch] (node:internal/event_target:820:20)
      at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)

√ Nuxt Nitro server built in 1011 ms                                                                                                                                                                                nitro 06:08:08
i Vite client warmed up in 3536ms                                                                                                                                                                                         06:08:12
i nuxt.config.ts updated. Restarting Nuxt...
```

**Comment by cernymatej** [comment]
It works fine for me locally. I can't see the error message you mentioned. Could you have a look at the reproduction again, please? 🙏

**Comment by XpPort** [comment]
> Для меня это отлично работает локально. Я не вижу сообщение об ошибке, о котором вы упомянули. Не могли бы Вы еще раз посмотреть репродукцию? 🙏

Perhaps this problem is due to the fact that I moved the page files from the app folder to the root folder of the project.

But then the question is, is it possible to do this safely, and transfer the page files from the app folder without errors?

**Comment by cernymatej** [comment]
When you move the page files while the dev server is running, some errors may show up. I usually just restart it manually after moving pages, components, etc.
Is this what you mean?

I'm wondering if we could add an automatic restart, similar to what happens when you update the `nuxt.config`. 🤔

**Comment by XpPort** [comment]
> When you move the page files while the dev server is running, some errors may show up. I usually just restart it manually after moving pages, components, etc. Is this what you mean?
> 
> I'm wondering if we could add an automatic restart, similar to what happens when you update the . 🤔`nuxt.config`


I didn't really mean that.

When generating a nuxt project, then folders with pages and other stuff including the app.vue is generated in the root folder of the project.

If a nexus project (version 3) is being created, then the folders and files above are created in the app folder of the root folder, which is inconvenient for me, so when I moved them to the root folder and disabled ssr, this error appeared. 

I was looking through the configuration manual and found nothing with this file transfer from the app folder to the root folder, which is generated automatically

**Comment by cernymatej** [comment]
The `app/` folder is what the new directory structure in Nuxt will look like starting with Nuxt 4.
This allows for some performance improvements for the dev server & also semantically separates the Vue side of the project from the rest.

For the `app/` folder to work currently, you need to have `future.compatibilityVersion` set to `4` in your nuxt.config. You can read more about it [here](https://nuxt.com/docs/api/nuxt-config#compatibilityversion), and more about the reasoning behind this new directory structure [here](https://nuxt.com/docs/getting-started/upgrade#migrating-to-nuxt-4).

You can still keep the `pages/` directory in the root of the project, though.
Could you please share a reproduction, where you're getting the error?
