### ISSUE TITLE
Array type not correctly narrowed

### ISSUE THREAD

**Issue by benedictleejh** [nuxt/nuxt#30419]
### Environment

- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.15.0
- CLI Version:      3.17.2
- Nitro Version:    2.10.4
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      default
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-twb5fnyx

The files that fail to typecheck are:
- `server/utils/test.ts`
- `app/utils/test.ts`
- `app/components/TestComponent.ts`

### Describe the bug

Nuxt doesn't seem to correctly narrow arrays during typechecking. I was trying to `$fetch` an array from an API, but even after checking for an empty array, the code will still fail upon trying to index into the array and get the property of the first object. After simplifying the code as much as possible in trying to reproduce the error, it seems it affects any sort of array.

The following code will fail typechecking on `const b = a[0].length;` with the error `TS2532: Object is possibly 'undefined'.`
```
const a: string[] = [];

if (a.length === 0) {
  throw {};
}
const b = a[0].length;
```

### Additional context

I cannot reproduce this in a Vue TypeScript project (created from https://vite.new/vue-ts), or in a pure TS project, so it seems to be something on Nuxt's side causing the typechecking failure.

### Logs

```shell-script

```

**Comment by huang-julien** [comment]
Hi :wave: this is because we set `typescript.strict` to `true` by default in `nuxt.config.ts`. You can disable this behaviour by setting it to `false`
