### ISSUE TITLE
[Feature request]: Create nested Layouts

### ISSUE THREAD

**Issue by cawa-93** [nuxt/nuxt#3099]
It would be nice enough to be able to create layouts that would imitate other layouts. Let's say this:
```bash
/---layout
    |   default.vue
    |
    /---header
            index.vue
            full-width.vue
            sidebar.vue
```
In the `/layout/header/index.vue` we create the base with header:
```html
<template>
  <div class="header-template-root">
    <app-header></app-header>
    <main>
      <nuxt/>
    </main>
  </div>
</template>
```
Next, we complement this layout in an nested `/layout/header/sidebar.vue`:
```html
<template>
  <div class="sidebar-template-root">
    <aside>
      <!-- -->
    </aside>
    <article>
      <nuxt/>
    </article>
  </div>
</template>
```
Finally, we use this layout on the page
```html
<template>
  <p>Page content ...</p>
</template>

<script>
  export default {
    layout: 'header/sidebar'
  }
</script>
```
As a result, we will get a page with the following code:
```html
<div  class="header-template-root">
  <app-header></app-header>
  <main>
    <div class="sidebar-template-root">
      <aside>
        <!-- -->
      </aside>
      <article>
        <p>Page content ...</p>
      </article>
    </div>
  </main>
</div>
```

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2683">#c2683</a>)</em></sub></div>

**Comment by cawa-93** [comment]
Activity! Wait answer!

**Comment by visualfanatic** [comment]
@cawa-93 how about just importing the sidebar component and passing `<next />` in the default slot? Do you really need the sidebar to be a layout?
```vue
<template>
  <div class="header-template-root">
    <app-header></app-header>
    <main>
      <Sidebar><nuxt /></Sidebar>
    </main>
  </div>
</template>
<script>
import Sidebar from '~/components/Sidebar';

export default {
  components: {
    Sidebar,
  },
};
</script>
```

**Comment by cawa-93** [comment]
@visualfanatic I do not quite understand how your proposal solves this issue

**Comment by dugajean** [comment]
I second this request.

**Comment by kiuKisas** [comment]
With the profispojka solution, you seems to reload the `defaultLayout` when loading a page with `onboardingLayout`. I figure it out when I add animation to the Layout.
I find an other solutions, basted on parent and nuxt-child:
- working example there : https://github.com/dyanagi/nuxt-nested-routes-example
- doc here : https://nuxtjs.org/api/components-nuxt-child/

**Comment by danielroe** [comment]
This is now possible using the standalone `<NuxtLayout>` component in Nuxt 3 - you can use it even within another layout (e.g. `<NuxtLayout name="other-layout"><!-- content --></NuxtLayout>`).

**Comment by texastoland** [comment]
> * working example there : [dyanagi/nuxt-nested-routes-example](https://github.com/dyanagi/nuxt-nested-routes-example)
> * doc here : [nuxtjs.org/api/components-nuxt-child](https://nuxtjs.org/api/components-nuxt-child/)

@kiuKisas Thanks this was exactly what [I was looking for](https://twitter.com/texastoland/status/1665177545820499969)! So IIUC every nested `index.vue` is effectively a nested layout ([except](https://nuxt.com/docs/migration/pages-and-layouts#nested-routes) `<Nuxt/>` and `<NuxtChild/>` are now `<NuxtPage/>`) right?

@danielroe I struggled to discover this feature coming from [Next.js's version](https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts). I went to the [_Nested Routes_](https://nuxt.com/docs/guide/directory-structure/pages#nested-routes) section first. Maybe just a note about this specific use case 🙏🏼

**Comment by danielroe** [comment]
Great idea 👍
