### ISSUE TITLE
Access passed props from page component's asyncData method

### ISSUE THREAD

**Issue by bytesnz** [nuxt/nuxt#3201]
### What problem does this feature solve?

An inability to access the props passed to a page component from the asyncData function (now that you can pass props to child components [#1502/#1591]). The data that is downloaded can be dependent on the value of the props, but they are not able to be referenced at the moment from the asyncData function (and potentially the data function).

### What does the proposed changes look like?

Could add a props parameter to the asyncData function

```js
asyncData(context, props) {
  if (props.value === 'certainValue') {
    return context.store.dispatch('specialData')
  } else {
    return context.store.dispatch('normalData')
  }
}
```

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6861">#c6861</a>)</em></sub></div>

**Comment by cannap** [comment]
any news on this?

**Comment by fadonascimento** [comment]
I think the with the new fetch syntax, this problem can be fixed.
@cannap @bytesnz 
See more:
https://twitter.com/Atinux/status/1220402044374331394
https://github.com/nuxt/nuxt.js/pull/6880

**Comment by bytesnz** [comment]
Sorry for the delay. You can't use fetch if you are wanting to block the page load before the fetch is complete can you? I see `fetch(context)` has now been deprecated for `middleware(context)`, but don't see an example in the docs of passing the data from the (anon) middleware to the page apart from through the store...?

**Comment by cannap** [comment]
you can just <nuxt-child some-prop="Hello" /> access in the new fetch like this.someProp when you have prop : ['someProp']} defined in the child

**Comment by katerlouis** [comment]
It's probably a stretch, but any chance this feature will make it to Nuxt 2? @danielroe 

I'm building a custom error page with `layouts/error.vue` and want to access the `error`-prop in `asyncData()` to determine which content to load from our CMS.

**Comment by danielroe** [comment]
No, it's unlikely we'll build out this feature for Nuxt 2.

**Comment by danielroe** [comment]
Closing as this is already possible to do in Nuxt 3.
