### ISSUE TITLE
Display rerendering after router.push triggered

### ISSUE THREAD

**Issue by aldarund** [nuxt/nuxt#3376]
### Version

[v1.4.0](https://github.com/nuxt/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://glitch.com/edit/#!/coherent-wallet?path=pages/fetch.vue:4:10](https://glitch.com/edit/#!/coherent-wallet?path=pages/fetch.vue:4:10)

### Steps to reproduce

https://coherent-wallet.glitch.me/ - open it. Click "change local var to" button. See how local var changed from default to 11111111 even route is changing already and it shouldnt happen.
Transition doesnt matter for this, without them its just a bit harder to notice, but if strip all css it will still be same behaviour.
For first i though its not related to nuxt and tried to reproduce with router and vue itself.
https://codepen.io/aldarund/pen/NMZOBV -> click about button at the right corner. And its not happening. Nothing rerendering after router.push triggered without nuxt.

In firefox its most noticeable. Its like half second - second stay there.
If push goes to the page that was already visited in this session - this behaviour dont happen. E.g. if the example above click that button 3rd time it stop to happen (  its 3 page with / -> /mount -> /fetch -> / path)

### What is expected ?

local var not re rendering after router.push triggered

### What is actually happening?

local var re rendering after router.push triggered

### Additional comments?

Same behaviour for edge version. 

Any workaround for this?

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c7148">#c7148</a>)</em></sub></div>

**Comment by idegree** [comment]
Does it look like this? https://github.com/nuxt/nuxt.js/issues/1408

**Comment by aldarund** [comment]
@idegree similar yes, but there some specific case with childs while here its normal pathes with standard push

**Comment by galvez** [comment]
@aldarund still happening in nuxt-edge?

**Comment by aldarund** [comment]
@galvez i cant check right now, but it was behaving same on nuxt edge at the time of creating issue.  i will be able to check in like 10 days, but i believe it still will behave same. 
I also noticed that this happens only when the second page loaded first ( e.g. when a network call to  https://coherent-wallet.glitch.me/_nuxt/pages/mount.js happens in example), on subsequent calls this doesnt happen. You can see it if click left button several times, it just cycle pages

**Comment by johnRivs** [comment]
Don't know if this is a bug, unavoidable behavior or intended (able to be switched) behavior but I'd love if the changes to the state weren't applied until the next page component came in.

I have an app where I have to use separate keys in the store and make everything a bit more convoluted when it comes to accessing these keys for this very reason. If multiple pages share certain key in the store, you see the changes applied before the animation, which looks kinda bad.

Ideally, any state changes that happen during a page component's fetch method shouldn't be displayed until said page component comes in.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
