### ISSUE TITLE
Components are being instantiated twice if application creates a Vue instance in plugins

### ISSUE THREAD

**Issue by fogil** [nuxt/nuxt#3896]
### Version

[nuxt-edge](https://github.com/nuxt.js/releases/tag/nuxt-edge) and 1.4.2

### Reproduction link

[https://github.com/fogil/nuxt-edge-component-doubling-problem](https://github.com/fogil/nuxt-edge-component-doubling-problem)

### Steps to reproduce

To see the weird problem of components being instantiated and mounted
twice, do the following:

1.) npm i
2.) npm run dev
3.) Open localhost:3000 in Chrome
4.) Inspect client-side console after you refresh the page. You will
  notice MinimalComponent being mounted twice for unknown reason(s).

### What is expected ?

MinimalComponent should only mount once.

### What is actually happening?

MinimalComponent is mounted twice.

### Additional comments?

I believe this is because nuxt assumes itself to be the one and only Vue instance, so it references the first Vue instance in memory for operations.  However, if the application instantiates a Vue instance in a plugins file there will be two Vue instances and Nuxt would repeat operations and mess up references.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7750">#c7750</a>)</em></sub></div>

**Comment by zeltice** [comment]
My company prefers Vue over Vuex for state management, since Vue has the additional benefit of being used as an Event bus and it can also hold static functions.  Vuex is too limited.   That is why we instantiate a new Vue instance during startup -- the new Vue instance serves as the state and global static function references.

**Comment by aldarund** [comment]
Here more basic reproduction
https://gist.github.com/aldarund/8d555c3ddf11010579acda6aada81e5c

If remove {items: []} from fetch - it called only once.
If replace fetch with mounted - it called only once

**Comment by manniL** [comment]
Is this reproducible in nuxt 1.4.2 as well?

**Comment by fogil** [comment]
After using @aldarund 's gist in my nuxt 1.4.2 project, I can confirm the bug is also present there.

**Comment by nassosyian** [comment]
i'm using nuxt 2.3.4 and this still occurs. 
what is worse is that the 2nd time asyncData() is called, the context.route.params are undefined 
(they had proper values the 1st time)

has there been any progress on finding a solution to this?

**Comment by Dima000** [comment]
If using `asyncData` is applicable and you can avoid using the computed the bug will not manifest.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
