### ISSUE TITLE
Page dom refreshed Before transition

### ISSUE THREAD

**Issue by awronski** [nuxt/nuxt#4132]
### Version

[v2.3.4](https://github.com/nuxt/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://codesandbox.io/s/2j0y809j2p](https://codesandbox.io/s/2j0y809j2p)

### Steps to reproduce

I am not sure if it is a bug or just my mistake. The reproduction simulate chaining a state with fetch, like in a app with axios.

1. Run the example
2. Click `Start` <- transition is ok
3. Click `Next 1` <- starts blinking
etc

You will see a color blink. Because the store/page is refreshed before the transition starts.
So first the color is changing to new value, then the transition is starting.

Check the console output.

### What is expected ?

afterLeave... 
Before enter... 
store.mutations #a40c82
---mounted 
After enter... 

### What is actually happening?

store.mutations #a40c82 
afterLeave... 
Before enter... 
---mounted 
After enter... 

### Additional comments?

Thanks for help!

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7989">#c7989</a>)</em></sub></div>

**Comment by awronski** [comment]
@pi0 Could you look at it?

Because now you are closing the reports without even checking it :(

**Comment by thariddler** [comment]
Frustrating to see how bug reports are closing automatically.

**Comment by awronski** [comment]
Hi Guys, anyone can help with it? 

Is it a problem with a nuxt lifecycle or with the vue-router? Could we do something about it? Thanks!
Ping @clarkdo @pi0

**Comment by awronski** [comment]
bump

**Comment by manniL** [comment]
I think is is *somewhat* intended.

When the SSR request happens, `asyncData` and `fetch` are also executed *before* the lifecycle hooks. To keep it consistent, this is the case here as well (and makes sense for eg. loading data). Also it's unclear how long that request will take.

What you want is setting the color on the `beforeMount` hook ☺️ 
https://codesandbox.io/s/github/manniL/nuxt-4132

**Comment by awronski** [comment]
Hi @manniL 

I have a page with blog posts. Now when I click _next page_ I see:
- the new posts
- than the transition (blink)
-  than the new posts again

I store the posts in the store.

So the only workaround for this is to copy the posts reference from the store to new variable in the `beforeMount`?

It looks ugly :)

Thanks for clarification,

**Comment by bdrtsky** [comment]
@awronski hi! I also noticed this but. It happens only on dynamic routes, because for some reason in dynamic routes lifecycle order changes from

```
- beforeRouteLeave 
- middleware
- asyncData
- beforeLeave
- beforeDestroy
- afterLeave
- created
```
to 

```
- middleware
- asyncData
- beforeRouteUpdate
- beforeLeave
...
```

So, next route `asyncData` is fired **before** `beforeRouteUpdate`!!! Crazy, right? I wasted a lot of time to figure this out.

**Comment by awronski** [comment]
@bdrtsky So how do you handle it?

@manniL Could you comment the change of order?

Thanks!

**Comment by bdrtsky** [comment]
@awronski I decided to force usual flow, by committing a mutations in `computed` while in `process.browser` ¯\_(ツ)_/¯

**Comment by johnRivs** [comment]
@manniL Is [this](https://github.com/nuxt/nuxt.js/issues/4132#issuecomment-455132194) still your preferred way to go around this issue?

**Comment by manniL** [comment]
@johnRivs nothing changed so far, so yes 😌

**Comment by awronski** [comment]
@manniL For me this is inconsistent. Why the dynamic routes behave in a different way?
To make it works we have to use workaround like `setTimeout` or use `beforeMount`.

It should just work :)

**Comment by manniL** [comment]
@awronski I agree, but we can't change the behavior for Nuxt 2 as it'd result in breaking changes. We are keeping the problem in mind for Nuxt 3 :relaxed:

**Comment by CHEWX** [comment]
Had to use the `beforeRouteLeave` hack.

**Comment by SHxKM** [comment]
Anyone found an elegant way to achieve this? I'm also experiencing this flicker when navigating between `nuxt-child`ern: API items appear → transition ocurrs → same API items appear. I just don't know if I'm doing something wrong or not. Also, how can I access `store` in `beforeMount()`? if at all, I need to call an action.

**Comment by awronski** [comment]
Unfortunately not.

I use this hack:

```js
function commitTimeout (f) {
  if (process.client) {
    setTimeout(() => {
      f()
    }, 100)
  } else {
    f()
  }
}
```

and then in the store:
```js
   commitTimeout(() => {
      commit('changePostTo', { post, comments })
    })
```

**Comment by SHxKM** [comment]
@awronski - so in fetch() you’re not changing anything, but in your SetPosts method you’re calling

**Comment by SHxKM** [comment]
@awronski - your workaround works well, so thanks for sharing! (I'm putting both methods in `store/posts.js`). However, I can't understand the logic behind it. Furthermore, even a delay as little as `5ms` achieves the desired result for me. What's happening behind the scenes?

**Comment by awronski** [comment]
@SHxKM I do not retrieve data in the page. I call the `store.dispatch` in the fetch.

I am not sure why this is working :) I guess that the delay is enough to call `beforeRouteUpdate`.
Because of the delay the order is the same.

Maybe @manniL can explain it?

**Comment by SHxKM** [comment]
> I do not retrieve data in the page. I call the store.dispatch in the fetch.

Same here:

```
async fetch({ params, store, process }) {
        await store.dispatch('posts/getPosts', { page: params.page_num || 1 })
  },
```

> I am not sure why this is working :) I guess that the delay is enough to call beforeRouteUpdate.

This is a real mystery. I see the same order of events happening with or without your workaround. Even `1ms` is enough, which means that this isn't simply about the delay per-se.

**Comment by awronski** [comment]
@SHxKM yes, you see the same order.

But the commit in the store is delayed, so there is time to call `beforeRouteUpdate` by nuxt.

**Comment by SHxKM** [comment]
@awronski - I don’t think 1 millisecond would’ve made that much difference, but what do I know?

Anyway, thanks for sharing your solution.

**Comment by johnRivs** [comment]
Even 0ms will do the job. What's happening is similar to Vue's `nextTick`. By using `setTimeout`, you're putting things at later time in the stack, in the event loop.

So if what you want to call is X, then comes Y and finally Z, by using `setTimeout` for X you're putting it after Z.

**Comment by CHEWX** [comment]
This is a pretty horrible hack. How are you supposed to use `transition` correctly? Seems odd that I have to fire a method to change state to `leaving = true` so I pre-fade out content before transition does.

**Comment by raphaelpare** [comment]
Using `setTimeout` with 0ms does indeed solve the issue. Any update on a cleaner solution for this ?

**Comment by awronski** [comment]
**I do not recommend setTimeout** anymore.

This hack has serious problem. It can from time to time break your app.
For example the `head()` method will execute before committing the state.

**Comment by mrleblanc101** [comment]
I suppose this will never be fixed since Nuxt 3 is out, sad :(
![2023-02-28_10 59 53](https://user-images.githubusercontent.com/17392251/221916460-d14b7e51-9445-4e71-9cc4-ed293f9a76f5.gif)

**Comment by CHEWX** [comment]
I've seen plenty of apps in production using nuxt 2 without this issue though, so must be a better workaround.

**Comment by TinyLightBold** [comment]
I had a simulair issue with my query's on the [...uri].vue
I changed the query from _useFetch_ to **useLazyFetch**

I think the thing about it is that Fetch immediately takes the query up to the next frame, and with Lazy you have a well lazy moment.

Hope this fixes the stuff you all encounter

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

**Comment by mrleblanc101** [comment]
I still have this issue in Nuxt 3 :(
![Image](https://github.com/user-attachments/assets/f02557db-52ae-49dd-a2cc-cb8f076974d7)
