### ISSUE TITLE
[BREAKING] Error page should use empty layout by default

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt#4196]
### What problem does this feature solve?

There are several issues (eg https://github.com/nuxt/nuxt.js/issues/4191 or https://github.com/nuxt/nuxt.js/issues/2537#issuecomment-356340772) where people want the error page to have it's own "empty layout".

Maybe it wouldn't be bad to have an empty layout for the error page by default for Nuxt 3?

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8037">#c8037</a>)</em></sub></div>

**Comment by danielroe** [comment]
This is now implemented in nuxt 3.
