### ISSUE TITLE
feat: support http2 out of the box / with minimal configuration

### ISSUE THREAD

**Issue by aldarund** [nuxt/nuxt#4340]
### What problem does this feature solve?

Support http2 out of the box :)

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8145">#c8145</a>)</em></sub></div>

**Comment by manniL** [comment]
Will only work (natively) with Node 11.1++ (https://nodejs.org/api/http2.html#http2_core_api)

**Comment by nathanchase** [comment]
Well, we're well past Node 9.x now (12.16.3). I think it's worth considering making http2 the default protocol now.

**Comment by danielroe** [comment]
Let's track this in https://github.com/unjs/nitro/issues/258
