### ISSUE TITLE
New directory to errors

### ISSUE THREAD

**Issue by ricardogobbosouza** [nuxt/nuxt#4369]
### What problem does this feature solve?

1 - With this new feature, I believe that the structure of the app stay more organized.
2 - It is no longer necessary to contain the `error.vue` file inside` layouts`, because it is not a layout. (We could keep to not contain breaking change)
3 - We could customize each type of error in each corresponding file, without the need to create conditions.

### What does the proposed changes look like?

Create a new directory in root `errors` to work with errors.
Within this new directory contains the components (pages) for type of error.

Example structure:
```
- errors
    - 404.vue
    - 500.vue
    - ...
- layouts
- pages
- ...
```

What do you think? A PR would be welcome?

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8177">#c8177</a>)</em></sub></div>

**Comment by manniL** [comment]
Hey @ricardogobbosouza 

We are already thinking about how to avoid the quirky setup with the error-page.
Unfortunately, we can't introduce any breaking changes, so the default behavior will stay until Nuxt 3 as you already realized.

I think it'd be a nice addition! 👍

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
