### ISSUE TITLE
feat: downgrade SSR to SPA, when node server crashes

### ISSUE THREAD

**Issue by falstack** [nuxt/nuxt#4420]
### What problem does this feature solve?

when Node server is crashed, Nginx will send error page to client, i want custom the error page and use index.spa.html, how should i do?

### What does the proposed changes look like?

when Node server crashed, Nginx send **Project/.nuxt/dist/server/index.spa.html** to client

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8206">#c8206</a>)</em></sub></div>

**Comment by falstack** [comment]
@manniL Nuxt can build resource for SSR & SPA both, and use WebpackHtmlPlugin create spa.index.html for this（downgrade SSR to SPA），of course Nginx's error response template path should use nginx.conf to set

create another application is a wrong

**Comment by manniL** [comment]
Sorry, guess I misunderstood your description!

**Comment by LinXiShu** [comment]
oh fuck

**Comment by danielroe** [comment]
To do this in Nuxt 3, you can use this configuration:

```js
export default defineNuxtConfig({
  nitro: {
    prerender: {
      routes: ['/200.html']
    }
  }
})
```

The 200.html that will be generated alongside your server is the SPA fallback that you can have nginx serve up.
