### ISSUE TITLE
Multi-variant Nuxt App

### ISSUE THREAD

**Issue by justindasilva** [nuxt/nuxt#4430]
### What problem does this feature solve?

Currently, I have an application that can be viewed as a "core" product, but the application itself can be skinned/themed for different clients/organizations.

A new Nuxt module/plugin that would be able to help in a situation like this would be most ideal.

### What does the proposed changes look like?

So the "core" product has core templates (HTML), core styling (CSS/SASS), core assets (images, SVG's), perhaps even core components.

I've had some conversations with @pi0 about this feature. What he suggested sounded great.

In `nuxt.config.js`

```
modules: ['@nuxtjs/multi-variant'],
variant: process.env.NUXT_VARIANT || 'default'
```

You can set `variant` to `multi-variants/client1` for example in which case it would look in the `client1` folder for overrides.

Two possibilities for overriding:

1. Directory based:
```
pages/index.vue
pages/about.vue
assets/main.scss <-- this file requires assets/foo.scss
assets/foo.scss
org1/pages/about.vue <-- overrides pages/about.vue
org1/assets/foo.scss <-- overrids assets/foo.scss
```

2. File extensions:
```
pages/index.vue
pages/about.vue
pages/about.org1.vue <-- overrides about.vue
assets/main.scss
assets/foo.scss
assets/foo.org1.scss <-- overrids foo.scss
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8213">#c8213</a>)</em></sub></div>

**Comment by ricardogobbosouza** [comment]
Hi @justindasilva and @pi0 

I've created a module that you can configure for that need.
I also need to cover tests and improve documentation.

https://github.com/cknow/nuxt-modular

**Comment by justindasilva** [comment]
Hello @ricardogobbosouza, I just took a look at the link you posted and I am not sure your module is able to do what I explained in my post above. But then again, you mention that you need to improve the documentation. I'm going to provide a file structure example and let me know if your module would be able to support this:

File Structure (close to example you gave in your module README)
```
modular
    example1
        config
            config.json
        pages
            index.vue
        assets
            main.scss
pages
    index.vue
config
    config.json
assets
    main.scss
```

So let's say I run `npm run dev` and in my `nuxt.config.js`, I would have `variant: process.env.NUXT_VARIANT || 'default'`. When my application runs with `variant: default`, I expect it to use the default `pages` `config` and `assets` folder from root directory for all my imports. But if I were to run with `variant: 'example1'`, all my imports should reference that directory, so that when importing `config.json`, I would actually be importing `/modules/example1/config/config.json`.

My basic need here is an application that has a default look and behavior, but when running with a specified variant, the variant folder should be used. At the same time, it's not the case that an overriding variant file will even exist, so if I try to import `config/config.json` and the variant is specified, it should first look for the variant folder version, and if it does not exist, then revert to the default version.

It might not be the most clear, but let me know if there is a way we can talk in more of a real-time way. It would be great to bounce ideas off of each other.

**Comment by brophdawg11** [comment]
@justindasilva Did you have any luck finding a solution for this?  This is certainly a different use-case, but sounds somewhat similar to something I've been wondering.  My team has an manual SSR app  (not using Nuxt) at the moment, and it renders full layouts (header, page content, footer, etc.).  But we also have a requirement to be able to deliver the header/footer as exteranl standalone SSR'd components to other non-Vue applications.

There's a length explanation over on the Vue Forum (https://forum.vuejs.org/t/best-practice-for-sharing-an-external-web-delivered-component/60816) where I was chatting about this setup with someone I met at VueConf that has a similar requirement.  Our approach works for the tie being, but has a few rough edges.  

I am interested in moving away from our manual SSR stack and using Nuxt but I don't see any way to achieve this through Nuxt.  In the simplest case, there just needs to be a way to have two different `appTemplatePath`'s - one for a full `<html><body>...</body></html>` template, and one for an orchestrated `<div>...</div>` component template.

I tried experimenting with this with in a simple dummy Nuxt app and thought something like the following would do the trick, but there are issues with the build step - would require two webpack builds, two `dist/` folders, etc. sine it needs two instances of `html-webpack-plugin`

```
// server/index.js
async function start() {
  const orchestratedNuxt = new Nuxt(orchestratedConfig)
  await orchestratedNuxt.ready()
  app.use('/orchestrated/*', orchestratedNuxt.render)

  const nuxt = new Nuxt(config)
  await nuxt.ready()
  app.use(nuxt.render)

  const { host, port } = nuxt.options.server
  app.listen(port, host)
}
```

Curious if this is all feasible with Nuxt, or if we think what you were getting at here would be at all along those lines.  I think the main difference from what you are asking for above is that you are looking for a single-variant-at-a-time - where I'm at the moment hoping that a single Express server can server both my normal app and my orchestrated component apps.

**Comment by justindasilva** [comment]
Hi @brophdawg11, sorry for the late reply. I have not yet had any luck finding a solution for this. I talked to @pi0 a long time ago about it and I believe he might get to it some day, but it might not have much priority compared to other things.

I believe my request is quite unique compared to some of the other comments in this thread so far. What I basically need is a way to specify that I want to view my Nuxt app using a "variant", in which case it should look into a specific directory for application files, and fall back to default directory when these files don't exist.

As for your requirement, I do understand what you are going for, but I'm not at all familiar with how you might accomplish. Sounds very similar to something I had to do years ago, but that was with a PHP application, and it was just much easier to accomplish something like it at the time. I'm still learning the in's and out's of Nuxt, but the more I use it, the more I love it. Really hoping they might support the module I mentioned in this thread one day. I think it could benefit lots of people for many different cases.

**Comment by tupham9506** [comment]
Hi @ricardogobbosouza
Your 'nuxt-modular' repo is really helpful. I hope you will continue to develop your repo in the future. Thank you.

**Comment by danielroe** [comment]
This should be implemented (at least partially) via the nuxt extends feature in Nuxt 3. You can follow its progress in https://github.com/nuxt/nuxt/issues/13367, annd read the documentation at https://nuxt.com/docs/getting-started/layers.
