### ISSUE TITLE
Nuxt error() does not stop execution of previous component

### ISSUE THREAD

**Issue by jovanmaric** [nuxt/nuxt#4649]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://github.com/jovanmaric/nuxt-axios-error](https://github.com/jovanmaric/nuxt-axios-error)

### Steps to reproduce

The reproduction link contains a generated app with the latest Nuxt and the following setup:
- Custom error layout page
- axios module
- nuxt-i18n module 
- axios plugin which throws an error if 404 or 500 or higher error is returned.
- Express with /api proxy

To reproduce you should run `yarn dev` and open the console on chrome. 

### What is expected ?

That the error component is injected instead of the original component, removing all the semantics of the original component. 

### What is actually happening?

`Uncaught (in promise) TypeError: Cannot read property '_t' of null` while no code of the original component should be ran. 

### Additional comments?

The above error does not only apply to the `created()` method. Leading me to think that the re-render is retriggered on server side, while this shouldn't be when the error component injects itself instead of the original component. 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8377">#c8377</a>)</em></sub></div>

**Comment by hecktarzuli** [comment]
This would be pretty sweet, but pretty hard to actually pull off especially in all the places you can call error() .. like asyncData, fetch, created (via this.$nuxt.error) etc..

**Comment by jovanmaric** [comment]
However, calling error even within the places you summed up, would probably promote proper error handling flow. As currently everything below the error can cause unneeded side effects. I've updated my example with a `console.log` after the `error()` call in the axios middleware to show that it's still run. 

Maybe i'm biased by other languages (as javascript isn't my primary), but having a middleware be able to call error for instance, while components still are able to make state changes or else, feels like a smell to me.

**Comment by hecktarzuli** [comment]
If you were just showing a 'uh oh something sploded' message and sending a raw response to the browser, then I think that may be easier, but since Nuxt lets you show a pretty error message where other stuff really is rendered and code just doesn't early-out I think this is challenging.   I'm just guessing..  In the end, I want the same thing you do, as I too have to code against edge cases.  (Api returned 404, then return null to vuex, then in comps handle if computed prop is null within asyncData/fetch/router guards etc..  Having error messages being a 'full stop' would make thinks much easier.

**Comment by rchl** [comment]
I'm curious how the reproduction looked like for this because I've made some fix that might be relevant - https://github.com/nuxt/nuxt/pull/20719

Unfortunately the original repo is no longer present.

**Comment by jovanmaric** [comment]
@rchl Yeah after years of no response I deleted it, sorry.  From what I can remember:
* I created a http service for axios which exposes the get/post etc methods.
* The http service is injected into nuxt as $http (plugin).
* An interceptor in the http service calls the error method on 404 and 500.
* Nuxt properly swaps the layout to the error page, but still calls the `created()` method from the original for some reason.

Hope this helps in any way. Also keep in mind that this was quite an early version of nuxt 2. Your proposed implementation does looks like a way to fix the issue however.

**Comment by rchl** [comment]
And where was $http used from? Async data? created hook? Middleware?

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
