### ISSUE TITLE
call watchClient() without using a hook

### ISSUE THREAD

**Issue by volkovmqx** [nuxt/nuxt#4699]
### What problem does this feature solve?

i am changing the options.srcDir on build time, to include several files from other locations. in the builder.js watchClient() is being called on the build:done hook. i want this call to be without hooks and before build:done so i can change the srcDir to the appropriate folder.

### What does the proposed changes look like?

    if (this.options.dev) {
      // Start watching after initial render
      this.nuxt.hook('build:done', () => {
        consola.info('Waiting for file changes');
        this.watchClient();
      });

      // Stop watching on nuxt.close()
      this.nuxt.hook('close', () => this.unwatch());
    }

to 

    if (this.options.dev) {
      // Start watching after initial render
      consola.info('Waiting for file changes');
      this.watchClient();
      // Stop watching on nuxt.close()
      this.nuxt.hook('close', () => this.unwatch());
    }
    // Call done hook
    await this.nuxt.callHook('build:done', this);

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8416">#c8416</a>)</em></sub></div>

**Comment by danielroe** [comment]
Closing as we're not building new features for Nuxt 2, and this is quite specific to v2, but feel free to open a new feature request for Nuxt 3 if you would like to.
