### ISSUE TITLE
Middleware doesn't run at all in "layouts/error.vue" page

### ISSUE THREAD

**Issue by sam3d** [nuxt/nuxt#4745]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Steps to reproduce

1. Create a simple Nuxt app with only an `index.vue` page
2. Set the `nuxt.config.js` `mode` to `spa` (so the middleware can only get called on the client)
3. Create a `layouts/error.vue` page with the following content:

```vue
<template></template>

<script>
export default {
  middleware() {
    console.log("Called!");
  }
};
</script>
```

4. Navigate to _any_ page that isn't "/"

### What is expected ?

"Called!" will log to the browser console

### What is actually happening?

Nothing gets logged to the browser console

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8455">#c8455</a>)</em></sub></div>

**Comment by sam3d** [comment]
Also, if this is expected behaviour, please could this potentially be changed? There are many uses cases for wanting to apply middleware on the error page. Just one example I can think of is redirecting away from the page in the case of any error (without having to put it in the `created` hook):

```vue
<template></template>

<script>
export default {
  middleware({ redirect }) {
    redirect("/");
  }
};
</script>
```

**Comment by angus96** [comment]
where did you apply this error layout?

**Comment by sam3d** [comment]
@angus96  I'm not applying it anywhere. In nuxt, the error page is not meant to be applied.

https://nuxtjs.org/guide/views/#error-page

> The error page is a page component which is always displayed when an error occurs (that does not happen while server-side rendering). **Warning: Though this file is placed in the layouts folder, it should be treated as a page.** You can customize the error page by adding a layouts/error.vue file.

**Comment by sam3d** [comment]
This issue remains unresolved.

**Comment by sam3d** [comment]
Not stale, and the reproduction steps are noted in the original issue. This still occurs in the latest version.

**Comment by sam3d** [comment]
This issue is still occurring the latest version of Nuxt.js

**Comment by ParallelUniv3rse** [comment]
Bumped into the same issue, would be nice if middleware or asyncData worked.

**Comment by konsvasi** [comment]
I'm running into the same issue.  No middleware runs on 'layouts/error.vue'

**Comment by ParallelUniv3rse** [comment]
Bumping into this issue months later still. For the ones struggling - Last time around I've overcome the issue by:
1) Creating a catch all route with custom middleware meta: 
```
  {
      path: '*',
      meta: {
        middleware: myMiddlewareFunc,
      },
    },
```

2) Rergistered a beforeEach hook on the router: 

```
router.beforeEach((to, from, next) => {
    if (to.meta.middleware) {
      const middleware = [].concat(to.meta.middleware);

      // mock a fake context because the real one is not available
      const context = {
        from,
        redirect: (statusCode, url) => next(url),
        router,
        route: to,
        error: () => next(),
      };

      // support only single middleware function for now.
      return middleware[0](context);
    } else {
      next();
    }
  });
```

3) Used myMiddlewareFunc as normal (middleware/myMiddlewareFunc.js)
```
export default function ({ route, redirect, error }, message) {
  // do whatever
}
```

I haven't really given a thought to how this might work if you're using the built-in router based on filesystem and not an external one. This was enough to intercept the error render, redirect if there was a redirect defined for the url in the cms or fall through to the error page otherwise.

**Comment by justinwride** [comment]
I am also having this issue on the latest version. Neither `middleware` nor `asyncData` run in my file `layouts/error.vue`.
I would like to redirect depending on the error status code, and currently the only way I can figure out how is by using `beforeMount()` or `mounted()`.

**Comment by OMantel1** [comment]
same here, issue still in progress?

**Comment by Morzpx** [comment]
export default async function ({ store, route, error}) {
	const data = await store.dispatch('services/getByCode', route.params.detail)
	if(!data.code) {
		  error({ statusCode: 404, message: 'Post not found' })
	}
}

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️
