### ISSUE TITLE
是否能加一个可以设置自动生成路由树的"meta"对象的一个方法

### ISSUE THREAD

**Issue by langyuxiansheng** [nuxt/nuxt#4749]
### What problem does this feature solve?

这个可以解决许多不必要的麻烦

### What does the proposed changes look like?

官网的自定义路由也有不方便的地方,
设置路由树的 meta: { }
        

示例:
const routes = [
{
        path: '/dashboard',
        name: 'dashboard',
        meta: {
            requireAuth: false, //菜单权限
            title: '系统首页', //菜单名
            icon: 'fa fa-bar-chart', //菜单图标
        },
        component: Layout,
        children: [{
            path: 'welcome',
            meta: {
                title: '欢迎页',
                requireAuth: false
            },
            component: Welcome
        }]
    }]

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8457">#c8457</a>)</em></sub></div>

**Comment by langyuxiansheng** [comment]
用了一个笨方法解决了这个问题

routes.js 如下:

/**
 * nuxt的路由菜单配置
 * @description 仅仅只用于侧边栏的菜单显示和权限,其它的不做任何功能
 */
const menus = [{
        meta: {
            requireAuth: false, //菜单权限
            title: '系统首页', //菜单名
            icon: 'fa fa-bar-chart', //菜单图标
        },
        path: "/dashboard",
        name: "dashboard",
    },
    {
        meta: {
            requireAuth: false, //菜单权限
            title: '欢迎页', //菜单名
        },
        path: "Welcome",
        name: "dashboard-Welcome"
    },
    {
        meta: {
            requireAuth: false, //菜单权限
            title: '示例功能', //菜单名
            icon: 'fa fa-bar-chart', //菜单图标
        },
        path: "/demos",
        name: "demos",
    },
    {
        meta: {
            requireAuth: false, //菜单权限
            title: '列表Demo', //菜单名
        },
        path: "List",
        name: "demos-List"
    },
    {
        meta: {
            requireAuth: false, //菜单权限
            title: '列表详情', //菜单名
        },
        path: "List/Detail/:id?",
        name: "demos-List-Detail-id"
    },
    {
        meta: {
            requireAuth: false, //菜单权限
            title: '数据分析', //菜单名
            icon: 'fa fa-bar-chart', //菜单图标
        },
        path: "/datas/UserAnalysis",
        name: "datas-UserAnalysis"
    }
];

/**
 * 递归查询路由权限
 * @param {*} list
 * @param {*} menus
 */
const iterator = (list) => {
    for (let item in list) {
        for (const m in menus) {
            if ((list[item].name === menus[m].name) && (list[item].path === menus[m].path)) {
                console.log((list[item].name === menus[m].name) && (list[item].path === menus[m].path));
                list[item].meta = menus[m].meta;
                list[item].meta.requireAuth = true;
            }
        }
        if (list[item].children && list[item].children.length > 0) {
            iterator(list[item].children);
        } else {
            return list;
        };
    }
};

export default (routes, resolve) => {
    routes = iterator(routes);
    console.log(routes);
};

nuxt.config.js 配置如下:

 router: { //中间件允许您定义一个自定义函数运行在一个页面或一组页面渲染之前。
        middleware: ['authorities'],
        extendRoutes: routes
    },


![image](https://user-images.githubusercontent.com/29669030/51073094-0920ba00-16a7-11e9-913e-4f52ecccccb9.png)

**Comment by ranwawa** [comment]
> * */
>   const iterator = (list) => {
>   for (let item in list) {
>   for (const m in menus) {
>   if ((list[item].name === menus[m].name) && (list[item].path === menus[m].path)) {
>   console.log((list[item].name === menus[m].name) && (list[item].path === menus[m].path));
>   list[item].meta = menus[m].meta;
>   list[item].meta.requireAuth = true;
>   }
>   }
>   if (list[item].children && list[item].children.length > 0) {
>   iterator(list[item].children);
>   } else {
>   return list;
>   };

现在有更简单的方法了没

**Comment by georgezouq** [comment]
Same problem, any solution?

**Comment by langyuxiansheng** [comment]
目前可能还没有,看来遇到问题的还不止我一个呀............

**Comment by konglingwen94** [comment]
Same problem

**Comment by Klay-Clam** [comment]
> 用了一个笨方法解决了这个问题
> 
> routes.js 如下:
> 
> /**
> 
> * nuxt的路由菜单配置
> * @description 仅仅只用于侧边栏的菜单显示和权限,其它的不做任何功能
>   */
>   const menus = [{
>   meta: {
>   requireAuth: false, //菜单权限
>   title: '系统首页', //菜单名
>   icon: 'fa fa-bar-chart', //菜单图标
>   },
>   path: "/dashboard",
>   name: "dashboard",
>   },
>   {
>   meta: {
>   requireAuth: false, //菜单权限
>   title: '欢迎页', //菜单名
>   },
>   path: "Welcome",
>   name: "dashboard-Welcome"
>   },
>   {
>   meta: {
>   requireAuth: false, //菜单权限
>   title: '示例功能', //菜单名
>   icon: 'fa fa-bar-chart', //菜单图标
>   },
>   path: "/demos",
>   name: "demos",
>   },
>   {
>   meta: {
>   requireAuth: false, //菜单权限
>   title: '列表Demo', //菜单名
>   },
>   path: "List",
>   name: "demos-List"
>   },
>   {
>   meta: {
>   requireAuth: false, //菜单权限
>   title: '列表详情', //菜单名
>   },
>   path: "List/Detail/:id?",
>   name: "demos-List-Detail-id"
>   },
>   {
>   meta: {
>   requireAuth: false, //菜单权限
>   title: '数据分析', //菜单名
>   icon: 'fa fa-bar-chart', //菜单图标
>   },
>   path: "/datas/UserAnalysis",
>   name: "datas-UserAnalysis"
>   }
>   ];
> 
> /**
> 
> * 递归查询路由权限
> * @param {*} list
> * @param {*} menus
>   */
>   const iterator = (list) => {
>   for (let item in list) {
>   for (const m in menus) {
>   if ((list[item].name === menus[m].name) && (list[item].path === menus[m].path)) {
>   console.log((list[item].name === menus[m].name) && (list[item].path === menus[m].path));
>   list[item].meta = menus[m].meta;
>   list[item].meta.requireAuth = true;
>   }
>   }
>   if (list[item].children && list[item].children.length > 0) {
>   iterator(list[item].children);
>   } else {
>   return list;
>   };
>   }
>   };
> 
> export default (routes, resolve) => {
> routes = iterator(routes);
> console.log(routes);
> };
> 
> nuxt.config.js 配置如下:
> 
> router: { //中间件允许您定义一个自定义函数运行在一个页面或一组页面渲染之前。
> middleware: ['authorities'],
> extendRoutes: routes
> },
> 
> ![image](https://user-images.githubusercontent.com/29669030/51073094-0920ba00-16a7-11e9-913e-4f52ecccccb9.png)

您这边生成的routes是如何通过store管理，或者说如何将其在组件中使用呀

**Comment by langyuxiansheng** [comment]
目前已经放弃这种方法了.未解决

**Comment by Klay-Clam** [comment]
> 目前已经放弃这种方法了.未解决

请问现在有什么解决方案吗？
我尝试了 fs写入文件，本地storage，都不行

**Comment by Klay-Clam** [comment]
@langyuxiansheng 我现在想的是，是不是只有全部手动配置菜单了。。

**Comment by langyuxiansheng** [comment]
我目前的方案,菜单那些至今存入后台了,只要名称和路由与nuxt生成的一致就可以了

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
