### ISSUE TITLE
Give option to controll whether to clear .nuxt before build or not

### ISSUE THREAD

**Issue by Pingze-github** [nuxt/nuxt#4770]
### What problem does this feature solve?

When using the commands you give out to update an online server:
```
nuxt build
nuxt start
```
You know nuxt build costs a lot of time. Before building, the dist folder was removed,  that causes that user cannot get the resources in dist.

In other words, server can not supply good service when building.

### What does the proposed changes look like?

If user set to not clear .nuxt before build, all the build files will be saved. That means  server can supply good service when building.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8484">#c8484</a>)</em></sub></div>

**Comment by Pingze-github** [comment]
It's better if nuxt.js support to auto controll dist files. I mean remove dist files only when they are too old.

**Comment by manniL** [comment]
Ideally you should *cache* all static assets (JS/CSS/Images) properly, eg. via CDN, so that current users still can visit the page "as usual".

More info about that in https://github.com/nuxt/nuxt.js/issues/3389#issuecomment-410879779

**Comment by DJafari** [comment]
i think `nuxt build` must be changed
my idea
.nuxt
 -- r1
 -- r2
 -- r3
 -- current

that `current` is symlink of last release, all resources must be read from `.nuxt/current`

if we run nuxt build, nuxt must be create another release (for example r4) and when it's end, symlink `.nuxt/current` to `.nuxt/r4`

i think with this idea this problem solves

**Comment by DJafari** [comment]
@manniL if this feature disabled by default i think solved the breaking change problem

yeah i saw other ways, but i always love official way 😁

**Comment by aldarund** [comment]
@Pingze-github a way better practice would be that you dont build on your production server, but build on CI and deploy builded to your server. Its much saner approach than building at production server

**Comment by danielroe** [comment]
We now keep the build directory mostly in memory with VFS in nuxt 3, so I think we can close this issue.
