### ISSUE TITLE
Discussion: Removal of Vuex store "classic mode"

### ISSUE THREAD

**Issue by shven** [nuxt/nuxt#4912]
### Version

[v2.4.1](https://github.com/nuxt.js/releases/tag/v2.4.1)

### Reproduction link

[https://github.com/nuxt/nuxt.js/tree/dev/examples/vuex-store](https://github.com/nuxt/nuxt.js/tree/dev/examples/vuex-store)

### Steps to reproduce

1. Clone https://github.com/nuxt/nuxt.js/tree/dev/examples/vuex-store
2. Change dependency to "nuxt": "latest" instead of "nuxt-edge": "latest"
3. npm install && npm run dev
4. Visit http://localhost:3000/

### What is expected ?

A code sample should not return a deprecation warning

### What is actually happening?

The console outputs this warning: 
WARN  Classic mode for store/ is deprecated and will be removed in Nuxt 3.

### Additional comments?

Fix the Vuex Store example or remove this warning

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8581">#c8581</a>)</em></sub></div>

**Comment by cretueusebiu** [comment]
What is the alternative now if you want to create the store instance manually ?

**Comment by shven** [comment]
@manniL I don't get it :s

I tried this modules syntax and I still get this warning.

**store/index.js**
`
import settings from './modules/settings';

export default () => new Vuex.Store({
  actions: {    
    nuxtServerInit({dispatch}, {query}) {
		dispatch('loadEditMode', query);
    },
  },
  modules: {
    settings
  }
});
`

**store/modules/settings.js**
`
export default {
  state: {
    editMode: false,
  },
  mutations: {
    setEditMode(state, editMode) {
      state.editMode = editMode;
    },
  },
  actions: {
    loadEditMode({commit}, query) {
      let isEditMode = false;
	  
	  if(query['editMode']) {
        isEditMode = true;
      }
	  
      commit('setEditMode', isEditMode);
    },
  }
};
`

**Comment by manniL** [comment]
Your `index.js` is not in module form 🤔

**Comment by Krutie** [comment]
@shven - try the following convention - it should remove the warning message :slightly_smiling_face: Also do the fresh `npm start` or `npm run dev` after making the changes, otherwise you'll still see the message.

```
// store/index.js

export const state = () => ({
  leads: []
})

export const mutations = {
  SET_LEADS(state, leads) {
    state.leads = leads
  }
}

export const actions = {
  async nuxtServerInit ({ commit }, { $axios }) {
    const leads = await $axios.$get('http://localhost:3000/api/leads')
    commit('SET_LEADS', leads)
  }
}
```

**Comment by renspoesse** [comment]
@manniL I understand that modules syntax has the same power but what is wrong with preferring the original, documented Vuex syntax (ie., classic) that I also use in non-Nuxt projects, if there's no functional difference?

**Comment by homerjam** [comment]
> @manniL I understand that modules syntax has the same power but what is wrong with preferring the original, documented Vuex syntax (ie., classic) that I also use in non-Nuxt projects, if there's no functional difference?

@renspoesse one thing it does for me is make it more straightforward to include reusable store modules - it's now more inline with the way plugins work.

**Comment by manniL** [comment]
@renspoesse IMO it's way more "in line" with other areas of Nuxt. As @homerjam mentioned, things like plugins or routes are heavily utilizing the filesystem. Same should be for the store.

If the demand is high enough or somebody is willing to put in the time, the "classic" store might have a chance to exist as a community module but it will likely vanish from the core in the next major version.

**Comment by imns** [comment]
Why are you making me use vuex-store in a specific way?  If it's not a security risk, you shouldn't be forcing how to use anything on me.

**Comment by homerjam** [comment]
@imns Nuxt exists to streamline and simplify the development of complex applications. It does this by providing a framework which encompasses a set of "best practices". As such there's a trade-off with total developer freedom.

**Comment by manniL** [comment]
> Why are you making me use vuex-store in a specific way? If it's not a security risk, you shouldn't be forcing how to use anything on me.

We don't force you to do anything :man_shrugging: 
But removing the non-fs-based vuex store handling helps us to keep Nuxt lean in the core.

If you still want to use this mode, we'll probably release a community module that allows this behavior ;)

**Comment by MaxKostenko** [comment]
Proposal to use fs-based store sounds strange in case if I have several pages with tottaly different modules. Unless you will have possibility to register/unregister them automatically based on current page file.
Or may be is there any solution for it?

**Comment by manniL** [comment]
@MaxKostenko you can dynamically (un-)register store modules as usual, sure. But I wonder whether there is a situation where you need to do that. These modules don't add much to the bundle size :thinking:

**Comment by MaxKostenko** [comment]
@manniL
But for it I need to keep it in different dir (not store) for preventing autoimport? 

Problem about store not in bundle size. Problem in performance on old/budget mobile devices. It could be solved if I will reset state to initial. But if you are going to build big application it will be a mess in store. For example, if you open dev-tools, getters will not be grouped by modules its just a long list. 
Also I think current situation could provoke programmer to create bad architecture with a lot relations between store modules. Nuxt like framework should force you to do better architecture.

**Comment by manniL** [comment]
@MaxKostenko Thanks for the feedback so far :relaxed: 

You can ignore them with a `.nuxtignore`, so they won't be embedded automatically.
I'll get back to the rest of the @nuxt/core-team regarding the performance aspect.

> Also I think current situation could provoke programmer to create bad architecture [...].

Nuxt aims to do the opposite. :+1:

**Comment by berenicestr** [comment]
Good Morning. I have the same problem. I have included auth-external-jwt: https://nuxtjs.org/examples/auth-external-jwt/

But if you can see, in the editor, appears the same warning: "Classic mode for store/ is deprecated and will be removed in Nuxt 3."

Please, any help to solve it?
Regards

**Comment by ScrippsFEE** [comment]
@berenicestr change store/index.js to this:

`/* global require, process */
const cookieparser = process.server ? require("cookieparser") : undefined;

export const state = () => {
  return {
    auth: null
  };
};
export const mutations = {
  setAuth(state, auth) {
    state.auth = auth;
  }
};
export const actions = {
  nuxtServerInit({ commit }, { req }) {
    let auth = null;
    if (req.headers.cookie) {
      const parsed = cookieparser.parse(req.headers.cookie);
      try {
        auth = JSON.parse(parsed.auth);
      } catch (err) {
        // No valid cookie found
      }
    }
    commit("setAuth", auth);
  }
};
`

**Comment by John0x** [comment]
As far as I can see, this would mean that I won't be able to use vuex-module-decorators with Nuxt anymore?

That would suck pretty much for the typescript way of dealing with vuex.

**Comment by kevinmarrec** [comment]
@John0x 2 ways to have `vuex-module-decorators` when "classic mode" will be removed :
1. (Recommended) Don't pass your modules to the store with classic mode, you can just use this way : https://github.com/championswimmer/vuex-module-decorators#module-re-use-use-with-nuxtjs and just export the class, Nuxt will handle it :) (it needs to be `@Module({ stateFactory: true, namespace: true, name: 'someName' })` to suceffuly work if I remember)

2. We'll provide a external official Nuxt module to let people have the classic mode back

**Comment by yubing24** [comment]
How should I implement store with typescript then? My `index.ts` is below but I still receive this warning.
```typescript
import Vue from 'vue';
import Vuex, { StoreOptions } from 'vuex';
import { RootState } from './types';
import auth from './auth/index';
import organizer from './organizer/index';
import competitionConsole from './organizer/console/index';
import partnership from './partnership/index';
import reference from './reference/index';

Vue.use(Vuex);

const storeOptions: StoreOptions<RootState> = {
  state: {
    version: '2019.0313.2331'
  },
  modules: {
    auth,
    organizer,
    competitionConsole,
    partnership,
    reference
  }
};

const store = function() {
  return new Vuex.Store<RootState>(storeOptions);
};

export default store;
```

RootState definition:
```typescript
export interface RootState {
  version: string;
}

```

**Comment by zoztorun** [comment]
I have the same error, how can I fix this?

./store/index.js
```
import Vuex from 'vuex';
import Vue from 'vue';

import locales from '@/store/modules/locale';
import currentPage from '@/store/modules/currentPage';

Vue.use(Vuex);
const createStore = () => {
  return new Vuex.Store({
    modules: {
      locale,
      currentPage,
    },
    debug: true,
  });
}

export default createStore;
```
./store/modules/locale.js
```
const state = {
  locale: 'en',
  locales: ['en', 'tr'],
};
const getters = {};
const actions = {};
const mutations = {
  SET_LANG (state, locale) {
    if (state.locales.indexOf(locale) !== -1) {
      state.locale = locale
    }
  },
};

export default {
  namespaced: true,
  state,
  getters,
  actions,
  mutations,
};
```
./store/modules/currentPage.js

```
const state = {
  rootPath: '',
  lastUpdatedAt: 0,
};
const getters = {};
const actions = {};
const mutations = {
  setRootPath: (state, pathName) => {
    state.rootPath = pathName;
    state.lastUpdatedAt = (new Date()).getTime();
  },
};

export default {
  namespaced: true,
  state,
  getters,
  actions,
  mutations,
};
```

**Comment by hareku** [comment]
@kevinmarrec 
Would you add an example with `vuex-module-decorators` ?
I think that is what many developers want.

**Comment by kevinmarrec** [comment]
@John0x @hareku For Vuex with TypeScript I might suggest now [vuex-orm](https://github.com/vuex-orm/vuex-orm) which seems to fit better in TypeScript projects. I planned to do an example if you want to give it a try.

**Comment by hareku** [comment]
@kevinmarrec 
I want to try it!

**Comment by butaminas** [comment]
If someone still struggles with this, here is my approach:
**index.js file**
```
// Load store modules dynamically.
const requireContext = require.context('./modules', false, /.*\.js$/)

requireContext.keys()
    .map(file =>
        [file.replace(/(^.\/)|(\.js$)/g, ''), requireContext(file)]
    )
    .reduce((modules, [name, module]) => {
      if (module.namespaced === undefined) {
        module.namespaced = true
      }

      return { ...modules, [name]: module }
    }, {})
```

**modules/module1.js**
```
export const state = () => {
  return {
    // your state data
  }
}

export const getters = () => {
  return {
    // your getters
  }
}

export const mutations = () => {
  return {
    // your mutations
  }
}

export const actions = () => {
  return {
    // your actions
  }
}
```

**Comment by Akash187** [comment]
If you are still getting the annoying warning "Classic mode for store/ is deprecated and will be removed in Nuxt 3".

you should read this question on StackOverflow.
[Vuex Classic mode for store/ is deprecated and will be removed in Nuxt 3](https://stackoverflow.com/questions/57666738/vuex-classic-mode-for-store-is-deprecated-and-will-be-removed-in-nuxt-3/57680580#57680580)

**Comment by redLineColor** [comment]
so ugly to use this.$store.getters['fileName/getterName']

**Comment by mehul-dev** [comment]
I strongly feel that classic mode should be kept even though it's shipped with nuxt but having to choose between legacy and the **nuxt** way would be grateful. I recently started a project with nuxt and coming from the background where I have developed the project with vue-cli. I prefer the same development approach with nuxt, for instance even though nuxt provide an automated router configuration for you in the background which is great but personally, for me, I like the traditional approach where I can define custom routes and don't rely on the directory structure just to follow **nuxt** way. I certainly don't know whether classic mode causes any perfomance issue or overhead  in development but having to choose as per your prefernce is always great to have in a frame work

**Comment by Atinux** [comment]
With the latest Nuxt version (`v2.10.X`), you can directly create a `app/store.js` file to overwrites our module system:

`app/store.js`:
```js
import Vue from 'vue'
import Vuex from 'vuex'
​
Vue.use(Vuex)
​
export const createStore = () => {
  return new Vuex.Store({
    state: () => ({
      counter: 0
    }),
    mutations: {
      increment (state) {
        state.counter++
      }
    }
  })
}
```

You will also have to define `store: true` in your `nuxt.config.js`

**Comment by mgdodge** [comment]
@Atinux , when is this going to be documented on nuxtjs.org? In other words, is this just a clever workaround or an actual feature that will be supported going forward?

**Comment by syamkumarkk** [comment]
Is there any solutions for this message. i tried many ways to remove the message

**Comment by Atinux** [comment]
The new doc is being written with a new architecture to explain how the hidden power of Nuxt

**Comment by vintprox** [comment]
Such deprecation of classic store (which by all means is conventional enough) prevents usage of https://github.com/paleo/direct-vuex and such. Why do you enforce the single way? I think, it puts Nuxt users in disadvantage... 😕

**Comment by vesper8** [comment]
I use vuex-pathify and vuex-orm which is the main reason why I am using the "classic mode" because nowhere is it documented how to initialize vuex plugins in the "module convention"

This is what my `store/index.js` currently looks like

```
import Vue from 'vue';
import Vuex from 'vuex';
import pathify from 'vuex-pathify';

import axios from 'axios';
import VuexORM from '@vuex-orm/core';
import VuexORMAxios from '@vuex-orm/plugin-axios';

import VuexORMSearch from '@vuex-orm/plugin-search';
import database from './orm/database';

import modules from './modules';

Vue.use(Vuex);

VuexORM.use(VuexORMAxios, { axios });

VuexORM.use(VuexORMSearch);

const createStore = () => {
  return new Vuex.Store({

    plugins: [
      pathify.plugin,
      VuexORM.install(database),
    ],

    modules,

    actions: {
      nuxtServerInit(context, value) {
        console.log('NUXT_SERVER_INIT!');
      },
    },
  });
};

export default createStore;
```

Would be happy to use the new convention if someone explains how I can keep using my two vuex plugins

**Comment by vesper8** [comment]
> With the latest Nuxt version (`v2.10.X`), you can directly create a `app/store.js` file to overwrites our module system:

@Atinux Where should we create this `store.js` file? The default nuxt folders don't include an `app` folder, do you mean that `store.js` should be in the root of the project at the same level as the `package.json` ?

**Comment by danielroe** [comment]
We don't plan to remove any features from Nuxt 2 that currently exist. For Nuxt 3, this issue is no longer relevant as stores are implemented differently in Vue 3.
