### ISSUE TITLE
Weird mismatch between client and SSR

### ISSUE THREAD

**Issue by joelworsham** [nuxt/nuxt#4949]
### Version

[v2.4.0](https://github.com/nuxt.js/releases/tag/v2.4.0)

### Reproduction link

[https://codesandbox.io/s/rlmxx1p0m4](https://codesandbox.io/s/rlmxx1p0m4)

### Steps to reproduce

Let the sandbox load
Click the "refresh" button within the sandbox preview

### What is expected ?

Both loading spinners should be rendered properly, with a radial gradient, on both page loads.

### What is actually happening?

The spinners load properly the first time, but then every subsequent load they are broken.

### Additional comments?

So this is a weird one. I created 2 spinners to demonstrate the issue in 2 ways. The first spinner uses _uid to make a unique reference to the component. The second spinner uses Math.random() to generate random numbers in the data property.

If you inspect element when loading spinner appears broken (no radial gradient), you can see that the 2 places in each component the id is interpolated, the numbers don't match up. It appears that part of the component (the linearGradient element) is rendered AGAIN after page load on the SSR and then spit back out. It is insanely bizarre.

You can see in the browser console log and in the console on the server (in the sandbox) that the numbers output are different from each other, even within the same component.

This screenshot (which is kind of a mess) shows the console log on the server vs the browser and how they are output in the HTML: https://d.pr/i/dL7qtV

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8607">#c8607</a>)</em></sub></div>

**Comment by manniL** [comment]
That's indeed strange 🤔 
Not sure whether it's a Vue or a Nuxt issue.

**Comment by manniL** [comment]
@joelworsham Not necessarily. The "issue" appears because of hydration it seems. This can only happen after SSR *but* could be a bug in the `vue-server-renderer` instead of Nuxt itself.

**Comment by joelworsham** [comment]
Interesting. Well, I don't know enough about under the hood to figure out where it's coming from. The only reason I came here is because our project is using Nuxt, and I couldn't seem to reproduce the bug without Nuxt.

I'm really either hoping to A) Discover a bug that can be fixed or B) Have a workaround pointed out to me that we can use.

This one has me banging my head against the wall

**Comment by manniL** [comment]
This caught me right now on a client project because transitions will trigger on hydration when using dynamic components :see_no_evil:

**Comment by joelworsham** [comment]
bump :)

**Comment by danielroe** [comment]
This is an upstream Vue SSR bug; closing it here.
