### ISSUE TITLE
Dynamic component server side rendering doesn't work when used inside v-if and v-else

### ISSUE THREAD

**Issue by namu-theseed** [nuxt/nuxt#4960]
### Version

[v2.4.1](https://github.com/nuxt.js/releases/tag/v2.4.1)

### Reproduction link

[https://codesandbox.io/s/yn60n6p79](https://codesandbox.io/s/yn60n6p79)

### Steps to reproduce

```vue
<template>
	<div>
		<div v-if="error" v-text="error.msg" />
		<div v-else>
			<component v-bind:is="content" />
		</div>
	</div>
</template>

<script>
export default {
	data() {
		return {
			error: null,
			content: {
				render: (h) => h('span', {}, 'hello, world')
			}
		};
	}
}
</script>
```

### What is expected ?

```html
<div id="__layout">
    <div>
        <!---->
         <div>
             <span>hello, world</span>
        </div>
    </div>
</div>
```

### What is actually happening?

```html
<div id="__layout">
    <div>
        <div>
            <component></component>
        </div>
    </div>
</div>
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8610">#c8610</a>)</em></sub></div>

**Comment by Atinux** [comment]
It can be reproduce with `2.8.1`

**Comment by arnabrahman** [comment]
Any update on this?

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by namu-theseed** [comment]
still reproduced ```2.17.4```

**Comment by danielroe** [comment]
This is likely Vue 2 behaviour rather than Nuxt.

**Comment by tjdnf1** [comment]
But it only happens in SSR.

**Comment by namu-theseed** [comment]
But it only happens in SSR.

**Comment by danielroe** [comment]
A Vue 2 SSR behaviour.

**Comment by danielroe** [comment]
Here's a pure Vue 2 SSR reproduction: https://stackblitz.com/edit/vue-12523-jbdsnx.

Closing as it's not a Nuxt issue...
