### ISSUE TITLE
Introduce a serverless mode

### ISSUE THREAD

**Issue by dohomi** [nuxt/nuxt#5011]
### What problem does this feature solve?

Currently having Nuxt served via lambda is not an easy task. Especially to deploy with the awesome zeit.co/now platform it would be great if Nuxt could have a serverless mode similar to NextJS:
https://nextjs.org/blog/next-8/#serverless-nextjs

### What does the proposed changes look like?

It would be great if a mode:'serverless' would get implemented and all defined routes will have the smallest footprint possible. Currently a NuxtJS bundle is too big and thus slow for cold boot startups

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8644">#c8644</a>)</em></sub></div>

**Comment by manniL** [comment]
We've noticed the demand for that mode some time ago ☺️

**Comment by ais-one** [comment]
You know, whatever serverless solution that is being worked on also needs to take into account if the website has dynamic subdomain mechanism

e.g. login user can visit both aaa.test.com, bbb.test.com, etc. which is served from the same app :)

It is not just a simple matter of shoving it up to Lambda, you probably need to setup other services such as cloudfront, APIG, etc...

**Comment by Clonk-HTML5** [comment]
At the moment this would maybe a Solution: https://github.com/serverless/examples/tree/master/aws-node-vue-nuxt-ssr
didn't used it but looks promising.

**Comment by Linus-Boehm** [comment]
@Clonk-HTML5 The repository is for nuxt 1.4.2, couldn't get it to run on 2.x.

**Comment by williamchong007** [comment]
@dohomi FYI: [I wrote a guide ](https://medium.com/likecoin/quick-nuxt-js-ssr-prototyping-with-firebase-cloud-functions-5277553610a8)on how to use v2 in universal mode with firebase cloud function

**Comment by dohomi** [comment]
@williamchong007 nice write-up. I am using Now so I am using the official now builder: https://github.com/nuxt/now-builder

**Comment by EdisonHarada** [comment]
If someone still searching for this I created a guide explaning how to create a Nuxt application with Typescript + Koa + Serverless: https://github.com/EdisonHarada/nuxt-koa-serverless

**Comment by Anima-t3d** [comment]
Did anyone try: [A crash course on serverless-side rendering with Vue.js, Nuxt.js and AWS Lambda](https://dev.to/adnanrahic/a-crash-course-on-serverless-side-rendering-with-vuejs-nuxtjs-and-aws-lambda-1nk4)

**Comment by danielroe** [comment]
This is now implemented in Nuxt 3! 😊
