### ISSUE TITLE
vuex plugin is not executed during hot module reload (HMR)

### ISSUE THREAD

**Issue by ozum** [nuxt/nuxt#5014]
### Version

[v2.4.3](https://github.com/nuxt.js/releases/tag/v2.4.3)

### Reproduction link

[https://codesandbox.io/s/vyqwrl0895](https://codesandbox.io/s/vyqwrl0895)

### Steps to reproduce

* npx create-nuxt-app <project-name>
* Create a class including a static method which exports a vuex plugin and a method which depends on some work done in plugin method. i.e. **some-class.js**
```js
export default class SomeClass {
  status() {
    return this.constructor.store.state.status;
  }

  static plugin() {
    return store => {
      console.log("<<<< PLUGIN INITIALIZED >>>>");
      this.store = store;
    };
  }
}
```

* Register plugin in nuxt vuex store: `export const plugins = [SomeClass.plugin()];`
* Use class and method in a vue component.
* Start nuxt in dev mode: `npm run dev`
* Edit **some-class.js** file and see error caused by HMR `Cannot read property 'state' of undefined`. However it works when you refresh the page.

### What is expected ?

No errors.

### What is actually happening?

Error: Cannot read property 'state' of undefined

### Additional comments?

After **some-class.js** file is edited, HMR reloads **some-class** file. However, **store/index.js** is not reloaded, because it is not changed. This causes `plugin()` method is not executed during HMR and causes error thrown. Then after I refresh the page, it works as expected, because all files are reloaded.

This case may or may not be categorized a bug of `nuxt` or `create-nuxt-app`, but I hope it could be avoidable.

To see it in action edit **some-class.js** file in root of https://codesandbox.io/s/vyqwrl0895ç , see the error, then refresh browser of codesandbox.io to see it works as expected.

Many thanks,

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8646">#c8646</a>)</em></sub></div>

**Comment by manniL** [comment]
@ozum Thanks for the report! That means, applying HMR to the index.js would be "necessary" everytime to trigger the plugins? 🤔

**Comment by ozum** [comment]
@manniL It seems so, but I wonder (I'm not experienced on Nuxt), if there are any other places to define vuex plugins? If so, it needs more generalized solution than just applying HMR to store/index.js.

**Comment by manniL** [comment]
@ozum `export const plugins` or using a Nuxt plugin and use the VueX plugin there (as it's "just a function that has the store as first arg) are both valid approaches.

**Comment by ozum** [comment]
Thanks.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
