### ISSUE TITLE
Allow checking if current component is page

### ISSUE THREAD

**Issue by p1pchenk0** [nuxt/nuxt#5055]
### What problem does this feature solve?

During work on application we faced a need to use mixin for pages only. Right now we have two options:
1. check page inside mixnin
`const isPage = this.$options.name && this.$options.name.toLowerCase().endsWith('page')`, but this is very fragile
2. manually include required mixin everytime we create new page

### What does the proposed changes look like?

As an example it would be nice to have `this.$options.isPage` boolean

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8680">#c8680</a>)</em></sub></div>

**Comment by Atinux** [comment]
I would suggest to use directly a `PageComponent` that you create with the mixin inside and use it into your pages directly:

```js
import PageComponent from '~/components/Page.vue'

export default PageComponent.extend({
  // asyncData
  // ...
})
```

This will avoid to have any kind of global Mixin that has an impact on performances.

What is your mixin exactly and what are you trying to achieve with it that you can't do with another way?

This way we will be able to find the best solution :-)

**Comment by p1pchenk0** [comment]
@Atinux so, do I need to extend each page I have in my project?

**Comment by p1pchenk0** [comment]
@Atinux what I am trying to achieve is to add schema.org markup to each page using `head ()` function in mixin

**Comment by felixbuenemann** [comment]
I think an option to inject a mixin *only* into page components would be great, because it allows to keep .vue pages without script blocks.

**Comment by guidomodarelli** [comment]
```
this.$vnode?.data.nuxtChild
```

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
