### ISSUE TITLE
Make it possible to give page-based names to _slug variable files

### ISSUE THREAD

**Issue by audunmo** [nuxt/nuxt#5207]
### What problem does this feature solve?

I have a directory like 
```
--pages/
---userPaymentPage/
----_id
---shop/
----_id
---.../
----_id
...
```

This makes it painful to search through for the right file to edit, and there isn't always a natural way to rename the slugs because of how they affect the naming of the route param inside the file.

It's be great to have some way to enable naming that gives context to the slug, like `UserPaymentPage__id`. This would make it much easier to search for the relevant file

### What does the proposed changes look like?

Have both `_slug` and `SomeName__slug` be supported

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8810">#c8810</a>)</em></sub></div>

**Comment by danielroe** [comment]
It is now possible to customise the name and route fully with the `definePageMeta` macro in Nuxt 3.
