### ISSUE TITLE
Nuxt.js is initializing the routes before the store

### ISSUE THREAD

**Issue by arielnmz** [nuxt/nuxt#5405]
### Version

[v2.5.1](https://github.com/nuxt.js/releases/tag/v2.5.1)

### Reproduction link

[https://codesandbox.io/s/ojqkwonl7y](https://codesandbox.io/s/ojqkwonl7y)

### Steps to reproduce

1. Create a brand new universal nuxt app
2. Install `vuex-pathify`
3. Create a component that uses a wildcard path, i.e.: 

```
...
<script>
  import { sync } from 'vuex-pathify'

  export default {
    name: 'MyComponent',
    computed: {
      ...sync('state@object.*')
    }
  }
</script>
```

4. Insert the component in a layout

(Make sure the page is using the layout in which you inserted the component)

### What is expected ?

That the store gets initialized before the router

### What is actually happening?

At the time pathify needs to access the state to expand the getters/setters, the state is `null`

### Additional comments?

Thats it. Pathify needs the store to be initialized when expanding the paths because it will map each name to a getter/setter. It used to work with `nuxt@^1.4.0`.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8949">#c8949</a>)</em></sub></div>

**Comment by arielnmz** [comment]
Related bug report in pathify's github https://github.com/davestewart/vuex-pathify/issues/53

**Comment by chiboreache** [comment]
2.5.1 — buggy, you should use 2.4.5 version

btw it giving `Module not found: Error: Can't resolve 'vue-class-component'` and complaining about js@2/ js@3 *(which is installing is also bad idea)* but at least it works

**Comment by manniL** [comment]
> 2.5.1 — buggy, you should use 2.4.5 version instead

I'm not a huge fan of such statements, especially if you don't explain **why you think that's the case**.

**Comment by chiboreache** [comment]
2.5.1 — not working
2.4.5 — working

that's easy

nor Coffeescript, nor Pathify

**Comment by manniL** [comment]
@chiboreache `vuex-pathify` works in general, "only" the wildcard feature is broken as it seems.

So you say that `vuex-pathify` + wildcards work with `v2.4.5`? :relaxed:

**Comment by chiboreache** [comment]
Nice move ;)

I say [my project](https://github.com/chiboreache/vuex-pathify-coffeescript) works great at 2.4.5 at the same time giving me `*` error at 2.5.1

despite the fact that I have just a simplest hello world example there

**Comment by davestewart** [comment]
> btw it giving Module not found: Error: Can't resolve 'vue-class-component' and complaining about

Yes. That's an issue with the last PR. I haven't had time to fix it yet. Maybe this week.

**Comment by davestewart** [comment]
@manniL 

> @chiboreache vuex-pathify works in general, "only" the wildcard feature is broken as it seems.
> So you say that vuex-pathify + wildcards (the exact code above) works with v2.4.5? ☺️

Pathify's wildcard feature creates component computed property getters / setters for child properties of a store module, using `*` to indicate "get the keys for this property".

To do that, the store MUST be loaded before the router, because it's the router that instantiates the components, and the component definitions which say, via Pathify's computed property helpers "hey, scan the store for these properties and created named getters / setters".

So yes, "only" the wildcard feature is broken.

P.S. I'm Pathify's author.

**Comment by arielnmz** [comment]
Still present in [v2.6.3](https://github.com/nuxt.js/releases/tag/v2.6.3)

https://codesandbox.io/s/my5ox7lw8x

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
