### ISSUE TITLE
Move title above meta

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt#5433]
### What problem does this feature solve?

Originally requested by @NightDiRaven in #5279 that it would be better to move `<title>` above all `<meta>` tags for CEO.

As mentioned by @Atinux  `<meta charset="utf-8">` should be always BEFORE title and @visualfanatic added this reference for confirmation of this:

> https://code.google.com/archive/p/doctype-mirror/wikis/MetaCharsetAttribute.wiki

> In order for all browsers to recognize a `<meta charset>` declaration, it must be
> 
> - Within the `<head>` element,
> - **Before any elements that contain text, such as the `<title>` element,** AND
> - Within the first 512 bytes of your document, including DOCTYPE and whitespace

But also as of link shared by @pimlie  the [W3 spec](https://www.w3.org/TR/html5/document-metadata.html#specifying-the-documents-character-encoding) does not mention anything about ordering at all.

I've moved the PR to this issue for further discussion.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8970">#c8970</a>)</em></sub></div>

**Comment by pimlie** [comment]
I tested the following code with Browserstack on Windows 7 / IE 9 and the title displayed just normally

```html
  <head test="true" data-vue-meta="test">
    <title> В чащах юга жил бы цитрус? Да, но фальшивый экземпляр!</title>
    <meta charset="utf-8">
    <meta data-vue-meta="true" name="description" content="Hello" data-vmid="test">
```    

Unfortunately I cant upload the vide of the browserstack session here, please download it here: https://github.com/pimlie/nuxt-issues/blob/master/bs-video-logs-euw.mp4

**Comment by pi0** [comment]
@pimlie Maybe that's because default charset is `utf-8` no?

**Comment by pimlie** [comment]
@pi0 hmm yeah, might be. It seems I am unable to change the default setting through Selenium, will try  some other encoding (if you have a suggestion for one please let me know)

**Comment by pimlie** [comment]
Here is a video with Japanese encoding Shift_JIS, example text taken from: https://en.wikipedia.org/wiki/Shift_JIS

```html
  <head test="true" data-vue-meta="test">
    <title>ハローワールド¥n</title>
    <meta charset="Shift_JIS">
    <meta data-vue-meta="true" name="description" content="Hello" data-vmid="test">
```
https://github.com/pimlie/nuxt-issues/blob/master/bs-video-logs-euw-Shift_JIS.mp4

**Comment by pi0** [comment]
@pimlie Just tested for `windows-1256` encoding and i can confirm you, at least chrome (which is also being used by google crawlers) respects `<meta charset>` whether below or above of `<title>` tag.

Furthermore, I've also discovered that chrome _always_ ignores this meta tag when `Content-Type` is set with `charset`. For nuxt middleware we [always set it to `utf-8` ](https://github.com/nuxt/nuxt.js/blob/dev/packages/server/src/middleware/nuxt.js#L80). At least static hosting including surge and github-pages _always_ set content-type of `html` files to `text/html; charset=utf-8`.

So i think you are right. Ordering for charset is not important.

**Comment by pimlie** [comment]
Btw, we probably took the wrong angle with this issue. The reason why the `<meta charset>` should be in the top region is to make sure it is in the first tcp packet which is sent to the client. The order of tags doesnt matter, as long as its in the first tcp packet.

Saw this being mentioned somewhere, might be that HEAD repo mentioned in the VueMeta v3 rfc but not sure anymore unfortunately

**Comment by danielroe** [comment]
Tag priority is implemented now:

https://github.com/unjs/unhead/blob/1dd10d2edde46fa614250655669459741ad14486/packages/schema/src/tags.ts#L63-L76

@harlan-zw - do you think there is merit in giving `title` some priority too?

**Comment by harlan-zw** [comment]
> Tag priority is implemented now:
> 
> https://github.com/unjs/unhead/blob/1dd10d2edde46fa614250655669459741ad14486/packages/schema/src/tags.ts#L63-L76
> 
> @harlan-zw - do you think there is merit in giving `title` some priority too?

Already taken care of in nuxt 3 🙂

https://github.com/harlan-zw/zhead/blob/main/packages/zhead/src/sortTags.ts 

This has a 2.x tag though so I won't close?

**Comment by danielroe** [comment]
Excellent! Yes, despite the tag, I think we can close this now as it's a feature request that's now implemented.
