### ISSUE TITLE
Build-only development mode

### ISSUE THREAD

**Issue by floflock** [nuxt/nuxt#5448]
### What problem does this feature solve?

Think of developing nuxt application in a docker.

It is better to run build process on bare metal machine because of performance issues of webpack in a docker container.
This leads to splitting up nodemon and watch-mode.

nodemon should run in the docker container, watch-mode/webpack on local machine.

### What does the proposed changes look like?

Splitting up command 'nuxt' into 'nuxt build-dev' and 'nuxt server-dev' or something like this.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8981">#c8981</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. Splitting builder and server in different proces is a good idea and what we are currently working to bring into nuxt (nuxt workers)

But what's the point of partially running in docker container?

**Comment by floflock** [comment]
Great. To run the the dev server into a docker container while developing has the effect, that you have near-production environment, if you have a docker container in production. 

Webpack is doing a better job on local machine, has some performance issues compiling within a docker container. That‘s why compiling process should run locally while nodemon refrehes the app in the docker container.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
