### ISSUE TITLE
scroll position remain between muti-layouts

### ISSUE THREAD

**Issue by lianghx-319** [nuxt/nuxt#5480]
### What problem does this feature solve?

When there are muti layouts in my project, sometime I want to back with scroll position remain. In a same layout, nuxt components with keep-alive can solve. But if back to an other layout pages, keep-alive isn't work. Because it just work on the nuxt components. I think the keep-alive support for the layouts can solve my problem. Maybe I can code all layouts in one, but if i do this, what's the meaning of layouts? If i want totally keep-alive support, I must code in one layout.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9007">#c9007</a>)</em></sub></div>

**Comment by danielroe** [comment]
I think you can do this with a custom scrollBehavior. You can do that in https://nuxt.com/docs/guide/directory-structure/pages#router-options in Nuxt 3, or https://nuxtjs.org/docs/configuration-glossary/configuration-router/#scrollbehavior in Nuxt 2. I don't think it would make sense to have this be a general feature supported by the framework as I think it's quite specific to your setup.
