### ISSUE TITLE
Named route overrides

### ISSUE THREAD

**Issue by samturrell** [nuxt/nuxt#5531]
### What problem does this feature solve?

When linking to a route using nuxt-link you either need to specify the path or a route object with name and params. The route object should be the recommended way of linking to a route, but is currently flawed in the sense that they aren't a constant, they are made up of the file path + name. 

In other frameworks there is the concept of named routes, where the name retains the route reference, even if the file paths are changed.

Imagine a page located at `./pages/products/_category/_product.vue`, using the object notation you would link to the route like so:

```html
<nuxt-link 
    :to="{ 
        name: 'products-category-product`, 
        params: { 
            product: 1, 
        }, 
    }"
>Go to product 1</nuxt-link>
```

Now imagine that we decided not to nest under categories, and simply have `products/1` as the uri. We would need to update all instances of this reference for the new path.

### What does the proposed changes look like?

We could either leverage the current `name` parameter on a component and use this as the route name, or introduce an additional property of `routeName` which would function as an override to the automatically generated route name. 

```js
// ./pages/products/_category/_product.vue

export default {
    name: 'product',
    // or
    routeName: 'product',
}
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9043">#c9043</a>)</em></sub></div>

**Comment by DonNicoJs** [comment]
@samturrell I believe that this feature is already present with this module: https://www.npmjs.com/package/@nuxtjs/router-extras 
I am using it here: https://codesandbox.io/s/j3246j07kw

**Comment by danielroe** [comment]
This is now present in Nuxt 3. Names are generated automatically based on file names (and can be inspected at https://localhost:3000/_vfs) or can be set using `definePageMeta`.
