### ISSUE TITLE
Alternative to "as" in next.js Link component 

### ISSUE THREAD

**Issue by ahmedfaical** [nuxt/nuxt#5566]
Hello, after working with next.js i am really proud to use nuxt, personally i found nuxt much better than next and much complete and clean, I have juste one note, in next we can add a string that is shown on browser url like this : `<Link href="/about" as="about-us"><a>About US</a></Link>` So in browser it shown https://www.exemple.com/about-us to render about page. 
Can we do this with nuxt? 

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9083">#c9083</a>)</em></sub></div>

**Comment by kalinichenko88** [comment]
How it works, is it redirect? 
You can use middleware for redirects.

**Comment by ahmedfaical** [comment]
> How it works, is it redirect?
> You can use middleware for redirects.

No, it not redirects, the string of url shown on url is the content of "as" directive, So we can easly change the url string of the route on browser. 
as: is the path that will be rendered in the browser URL bar.

**Comment by asg5704** [comment]
In Nuxt.js, when you add a new .vue file to the `pages` directory, it automatically creates that slug from the new file's name. You can that direct to that new slug in a NuxtLink using the `to` attribute.
Example:
```
// about.vue in the pages directory
<NuxtLink to='/about'>About Page</NuxtLink>

// index.vue in the pages directory
<NuxtLink to='/'>Homepage</NuxtLink>
```

You can also look at the folder structure in this example from the Nuxt.js team
https://codesandbox.io/s/github/nuxt/nuxt.js/tree/dev/examples/meta-info?from-embed

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
