### ISSUE TITLE
Global server error handling

### ISSUE THREAD

**Issue by krukru** [nuxt/nuxt#5588]
### What problem does this feature solve?

Uncaught errors on the server side (for example, calling a function on undefined) will cause nuxt server to crash, denying all other clients until the server is restarted.
This feature request is for a global error handler that will catch all uncaught errors and allow the developer to process them accordingly.

### What does the proposed changes look like?

Some way to globally register an error handler that will catch any and all errors that may happen on the server-side without crashing or stopping the server for everyone.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9092">#c9092</a>)</em></sub></div>

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
