### ISSUE TITLE
Document in Readme or elsewhere what version of Vue Nuxt is using

### ISSUE THREAD

**Issue by sdras** [nuxt/nuxt#5596]
### What problem does this feature solve?

Thanks for reviewing this feature request! As Vue is getting ready for 3.0 release, it's going to be more and more common that people really need to know the which version of Vue they're using. This came up for me recently because I was unsure of which slot syntax I was able to use (no big deal to test), but good to be more explicit for userland. Thanks!

### What does the proposed changes look like?

Either document which version of Vue is being used in the Readme, or as some field generated by package.json. Those are the two places I would check first. I can find it in yarn.lock but I have to walk through 102 instances of "vue" in the file to find it.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9100">#c9100</a>)</em></sub></div>

**Comment by manniL** [comment]
Good point Sarah, thanks for addressing it 👍 
We will document it properly.

Usually, the latest Vue version is required when installing a fresh Nuxt project. In some rare cases, like a buggy release, we have to pin the Vue version (or any faulty dep in such a case) to the latest "working" version until the bug is fixed.

The current Vue version range expression that Nuxt uses can be found here:
https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/package.json#L17

**Comment by pimlie** [comment]
Please check: https://github.com/nuxt/nuxt.js/wiki/Dependencies

The md is generated by a script, will push a pr tomorrow after I cleaned it up to make sure it can be used on any monorepo. The wiki page should be updated once a new dependency is added. See [here](https://github.com/Decathlon/wiki-page-creator-action/blob/master/entrypoint.sh) for the implementation of a github action which could be used for that (but probably easier to implement it just as a release step).

**Comment by simplenotezy** [comment]
This would be helpful - also some documentation on how to use a different vue version.

**Comment by danielroe** [comment]
Sorry it has taken so long! This should be currently visible in the package description of https://github.com/nuxt/nuxt. `vue` is also now directly listed as a dependency of the `nuxt` package.

We still need to merge 2.x and 3.x documentation -> https://nuxt.com, which is planned shortly, but I think we can close this issue for now.
