### ISSUE TITLE
Plugins:done hook

### ISSUE THREAD

**Issue by hecktarzuli** [nuxt/nuxt#5722]
### What problem does this feature solve?

Sometimes plugins that get injected via modules need to talk to other plugins.  In such cases, it would be really nice to have a plugins:done event to let plugins know when it's ok to start talking to each other.

The plugins would be injected/registered as normal (in any order).

For example, our drift plugin relies on our uiEvent Bus plugin. We would just have code in the drift plugin that does something like:

[drift plugin]
app.hook('plugins:done', () => {
app.$uiEvents.$on('chat:clicked', () => { this.drift.open() }
})

[uiEvents bus plugin]
inject('uiEvents', { .... })

To me, this is much cleaner and easier to follow than than a hidden & magic priorities.

This is a spin off from the conversation in https://github.com/nuxt/nuxt.js/issues/5698

### What does the proposed changes look like?

a hook via app.hook (or something) in plugin-land that triggers when all plugins have been ran.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9209">#c9209</a>)</em></sub></div>

**Comment by hecktarzuli** [comment]
@pi0 let me know if I need more detail.

**Comment by pimlie** [comment]
Could this be solved with the new [`extendPlugins`](https://github.com/nuxt/nuxt.js/pull/6285) option?

The reasons for adding extendPlugins seems similar at least

**Comment by galvez** [comment]
@hecktarzuli I too wanted to avoid it, this was a _compromise_ solution. Your proposed solution is one amongst several other ideas we've discussed for addressing this. We'll revisit this soon.

**Comment by danielroe** [comment]
In Nuxt 3 we now have the `app:created` hook which runs immediately after plugins are done.
