### ISSUE TITLE
Add $router.resolve support in programmatic mode.

### ISSUE THREAD

**Issue by Fnxxxxo** [nuxt/nuxt#5781]
### What problem does this feature solve?

It would be helpful to access $router.resolve instance when using nuxt as a middleware. Check route existence before performing nuxt.render and do page redirect or pass to other routes like /api.

### What does the proposed changes look like?

let routeExist = nuxt.resolveRoute('/some-path')

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9248">#c9248</a>)</em></sub></div>

**Comment by ishpartko** [comment]
+1

**Comment by madebyfabian** [comment]
I guess this is still relevant today for Nuxt 3, as there is no way of doing a `useRouter().resolve` on server-side. (Or is it?)

**Comment by danielroe** [comment]
I think that should be possible!

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
