### ISSUE TITLE
Allow .nuxtignore files within folders

### ISSUE THREAD

**Issue by snapwich** [nuxt/nuxt#5871]
### What problem does this feature solve?

Currently the Nuxt documentation refers to .gitignore files for an example for how to use .nuxtignore.  However, .gitignore allows the files to be placed in various directories and ignore relative file paths from that directory.  I think this would be a convenient feature to mirror in Nuxt with .nuxtignore.

### What does the proposed changes look like?

example of how to ignore a file with existing functionality vs with multi-directory .nuxtignore

// /.nuxtignore
pages/blog/2019/01-01-some-blog-post/ignoredfile.js

// /pages/blog/2019/01-01-some-blog-post/.nuxtignore
./ignoredfile.js

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9309">#c9309</a>)</em></sub></div>

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
