### ISSUE TITLE
Add a hook to modify the rendered meta in the renderSPA proccess 

### ISSUE THREAD

**Issue by hectorqin** [nuxt/nuxt#5925]
### What problem does this feature solve?

Then we can change the preloadFiles or meta  according to the url, even insert some content 

### What does the proposed changes look like?

Just need a little change in the render method of the SPAMetaRenderer class.

```js
async render({ url = '/', req = {}, _generate }) {
    // ... 

    await this.renderer.context.nuxt.callHook('vue-renderer:spa:meta', {
        url,
        modern,
        meta
    })

    // Emulate getPreloadFiles from vue-server-renderer (works for JS chunks only)
    meta.getPreloadFiles = () => (meta.preloadFiles || []);
   // ...
}
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9354">#c9354</a>)</em></sub></div>

**Comment by danielroe** [comment]
This is possible in nuxt 3 via the `render:html` hook.
