### ISSUE TITLE
Bypassing global middleware

### ISSUE THREAD

**Issue by chadwtaylor** [nuxt/nuxt#5928]
### What problem does this feature solve?

In `nuxt.config.js`, the middleware is globally set like so `router: { middleware: ['mw1', 'mw2'] }`.

As far as I know, there is no way to bypass the global middleware in components.

To illustrate an example with Rails API, I am able to bypass the global action like so `skip_before_action :auth_user!`. 

### What does the proposed changes look like?

To bypass a global middleware in components, it could look like this:

```
<script>
bypass_middleware: ['mw1'] // the 'mw2' will still be evaulated
</script>
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9357">#c9357</a>)</em></sub></div>

**Comment by danielroe** [comment]
Is this still something you feel we need?

**Comment by danielroe** [comment]
I think the correct solution here is to add an additional meta property that your global middleware can handle.

So, for example, in your page:

```vue
<script setup>
definePageMeta({
  auth: false
})
</script>
```

and in your global middleware:

```ts
export default defineNuxtRouteMiddleware(to => {
  if (to.meta.auth === false) return // early return if middleware not enabled on page
})
```

Modules that add their own middleware can aslo define and document which meta property will exclude middleware running on that route.
