### ISSUE TITLE
Add support of watchQuery for nested objects

### ISSUE THREAD

**Issue by Koc** [nuxt/nuxt#5978]
### What problem does this feature solve?

I am building grid for orders list with some filters. Next code used for parse/stringify query:

```js
    router: {
        parseQuery(query) {
            const qs = require('qs');
            const options = {allowDots: true, comma: true};

            return qs.parse(query, options);
        },
        stringifyQuery(query) {
            const qs = require('qs');
            const options = {allowDots: true, arrayFormat: 'comma', skipNulls: true};

            return Object.keys(query).length > 0 ? ('?' + qs.stringify(query, options)) : '';
        },
    },
```

Each filter updates coresponding `filter` property, for example for filter by status next url generates: http://admin.test:3000/orders-list?filter.status=done . And for now there is no support define `watchQuery: ['page', 'filter.status']` or `watchQuery: ['page', 'filter']` to get `asyncData` executed when `filter.status` updated.

`watchQuery: true` could be used as workaround, but seems to be bad idea in terms of performance.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9406">#c9406</a>)</em></sub></div>

**Comment by danielroe** [comment]
Closing as we're not building new features for Nuxt 2, and this is quite specific to v2, but feel free to open a new feature request for Nuxt 3 if you would like to.
