### ISSUE TITLE
asyncData not updating correctly using watchQuery (HMR, dev mode)

### ISSUE THREAD

**Issue by Timkor** [nuxt/nuxt#6004]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://codesandbox.io/s/codesandbox-nuxt-lfoy3?fontsize=14](https://codesandbox.io/s/codesandbox-nuxt-lfoy3?fontsize=14)

### Steps to reproduce

Click the `Change query randomly` to see `asyncData` working. It will update the current route's query and display this value on the page.

1. Now change in `~/pages/index.vue`:
```javascript
await new Promise(resolve => setTimeout(resolve, 1000));
```
to 
```javascript
//await new Promise(resolve => setTimeout(resolve, 1000));
```
2. Press save.
3. Wait until compilation is done.
4. See that it is broken when clicking the link.
5. Remove the `//` comment, so that it's restored back to normal.
6. Press save.
7. See that it is still broken.

### What is expected ?

`asyncData` should be called. And the data should be updated with the return value.

### What is actually happening?

`asyncData` is being called. However, the return value is not updating the components data though.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9432">#c9432</a>)</em></sub></div>

**Comment by dr3tt** [comment]
I tried with a simple `console.log('foo')` (instead of Promise+setTimeout)  and the same issue occurred.
Only a fresh rebuild (i.e. without HMR) makes things work.

**Comment by Timkor** [comment]
Bump

**Comment by papakay** [comment]
Also experiencing this issue...

**Comment by xxRockOnxx** [comment]
Even if not using `asyncData` and just using `data` instead, it seems like `watchQuery` is not re-registered on hot reload.

**Comment by jmacmac** [comment]
Bump. What's the accepted (acceptable?) solution here?

**Comment by newxan** [comment]
Still present in 2.11 as far as I can tell.

**Comment by GMartigny** [comment]
I made a [minimal reproduction example](https://codesandbox.io/s/intelligent-satoshi-kxkqkh?file=/layouts/default.vue). In this example, a `NuxtChild` is mounted with the `keep-alive` property on the parent.

- Navigate to any post
- See that the right content is loaded (first good render)
- Go back using the "back" link
- Click on another post
- :warning: See that it's still the first loaded post
- You can see in the console that `AsyncData` is called, but the returned value is not used.

> I found I was getting this issue because I was using the `keep-alive` property on my `<nuxt />` element. Because of this the page data was cached and so when the query changed asyncData was fired but never updated the data. To resolve this I added a key on my page based on the route query and it worked! [How to use key](https://nuxtjs.org/api/pages-key/)
> 
> Hope this helps someone

For me, this is not a solution. Using a `:key` prop with `$route.fullPath` will render the page everytime. This kills the benefits of `keep-alive`.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
