### ISSUE TITLE
Switch templates based on router options

### ISSUE THREAD

**Issue by kirapwn** [nuxt/nuxt#6073]
### What problem does this feature solve?

Right now the default template can be overwritten by custom app.html or replaced using `build` from config. But there is no way to use different templates based on module / plugin / serverMiddleware or router itself. This makes it hard to build custom renditions (eg. amp which now is mostly done by ugly replacing the produced responses, other custom preview like partial views for divs only)

### What does the proposed changes look like?

Pass an option to template so it would use different template on run time from module / plugin / serverMiddleware or router itself.
For example in module changing the default path to 
```
this.options.appTemplatePath = 'customRendition.template.html`
```
With correct path.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9496">#c9496</a>)</em></sub></div>

**Comment by RavenNevermore** [comment]
+1 this very much.

I have been searching the api, the nuxt docs and the nuxt sources for two days now, to find a way to use a specific custom `app.html` template, based on a certain route or page.

The usecase for us is, that we du render some pages as partial html resources for other apps to be server-side included. For those pages we need to render only the nuxt `div` without html, head or body. Would I be able to switch `app.html`  templates, I could accomplish that easily.

Please Implement?

PS: Is there maybe a workaround way of doing that?

**Comment by kirapwn** [comment]
Ugly regex to replace what you do not need or a separate build with different `app.html` which is a no go for me for development purpose.
Sadly this is still not possible afaik :(

**Comment by RavenNevermore** [comment]
I did now accomplish what I wanted with a very crude RegEx in a `render:route` hook. For anyone searching for something similar, here is the module I created:

```javascript
export default function () {
  this.nuxt.hook('render:route', (url, result) => {
    if (url.startsWith('/search/ssi/')) {
      result.html = result.html.match(
        /<\s*body[^>]*>\s*(.*)\s*<\s*\/\s*body\s*>/ims
      )[1]
    }
  })
}
```

**However** I would very very very much like to get rid of this monstrosity. ;)

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
