### ISSUE TITLE
Async Loaded Components don't render Styles

### ISSUE THREAD

**Issue by blowsie** [nuxt/nuxt#6084]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://codesandbox.io/s/themeable-nuxt-v2-1pcyw](https://codesandbox.io/s/themeable-nuxt-v2-1pcyw)

### Steps to reproduce

- Vistit URL, take note of styling
- Click about
- Click back home
- You will see the client version renders correctly

### What is expected ?

Server version to render styles

### What is actually happening?

Server version skips styles

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9504">#c9504</a>)</em></sub></div>

**Comment by blowsie** [comment]
Related:
https://github.com/nuxt/nuxt.js/issues/2198
https://github.com/nuxt/nuxt.js/issues/2027

**Comment by blowsie** [comment]
FYI I have essentially followed the pattern found in the examples.

https://github.com/nuxt/nuxt.js/blob/dev/examples/async-component-injection/pages/_slug.vue

**Comment by blowsie** [comment]
Ok so I think this is due to `data-v` not pairing up on the client and server.

When removing the `scoped` attribute from the `<style>` tag the css is rendered.

**Comment by daspete** [comment]
You could also just create a plugin, which loads all components into a store object, and then dynamically importing all components which will be used by your page:

[https://codesandbox.io/embed/nuxtdynamicasynccomponents-mvv6b](https://codesandbox.io/embed/nuxtdynamicasynccomponents-mvv6b)

**Comment by blowsie** [comment]
@daspete interesting thanks but it doesnt change the fact there is a bug here.

**Comment by bdrtsky** [comment]
Might be related? Async + scoped slot completely breaks SSR - https://github.com/nuxt/nuxt.js/issues/6423

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
