### ISSUE TITLE
Ignore property deprecation

### ISSUE THREAD

**Issue by 1001v** [nuxt/nuxt#6090]
### What problem does this feature solve?

Hello. The doc says, that the ignore property will be deprecated in nuxt 3 in favor of the .nuxtignore file. I believe that's not a very good idea, since we can change the ignore property dynamically with environment variables. For example, i have a guide page, which is shown only in the development environment and i ignore it in the production. The .nuxtignore file doesn't allow me to ignore pages depending on environment. Thank you.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9508">#c9508</a>)</em></sub></div>

**Comment by manniL** [comment]
Would it help to introduce sth. like `.nuxtignore.dev`/ `.nuxtignore.prod`?

**Comment by pi0** [comment]
I was not aware of this decision. There are also programmatic reasons to keep supporting `ignore` property (For example a module that adds more to ignore patterns)

**Comment by 1001v** [comment]
@manniL wouldn't it be a huge overhead compared with property in nuxt.config.js?

**Comment by danielroe** [comment]
We have not removed `ignore` option, so I think we can close this.
