### ISSUE TITLE
Access to injected js / css files like HtmlWebpackPlugin in vue-cli

### ISSUE THREAD

**Issue by zxwild** [nuxt/nuxt#6098]
Hi, I'm trying to integrate the nuxt app to django templating system.
In general all works ok, but I need to be able to modify static files paths.

For example currently I have:
`<link rel="preload" href="/_nuxt/65145c9ec382088fb536.js" as="script">`

but I need:
`<link rel="preload" href="/static/_nuxt/65145c9ec382088fb536.js" as="script">`

I already solved this issue with vue-cli, and all work nice, there I had an access to HtmlWebpackPlugin so I disabled files default injecting and modified app template (it would be `app.html` in nuxt).

But in nuxt I have only `{{ APP }}` without any fine tuning.

Is there a way to access to each injected css / js file on app.html rendering?

Here is how it looks with vue-cli:
https://stackoverflow.com/a/57125804/1767341

**UPD 1**:  
I realized it's possible to add HtmlWebpackPlugin, now I have js / css files with right paths, but there are a lot of embedded styles and some hardcoded js, so for now the question is "Is it possible to disable js files injecting and leave all the rest as is?"

nuxt.config.js:
```javascript
  build: {
    extend(config, ctx) {},
    plugins: [
      new HtmlWebpackPlugin(),
    ]
  }
```
app.html:
```html
  <% htmlWebpackPlugin.files.js.forEach((fileName) => { %>
    <script src="{% static '<%= fileName %>' %}"></script>
  <% }) %>
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9516">#c9516</a>)</em></sub></div>

**Comment by pimlie** [comment]
Cant you just set https://nuxtjs.org/api/configuration-build#publicpath ?

Unfortunately I am not sure what you are requesting with _Is it possible to disable js files injecting and leave all the rest as is?_ when you mentioned just before you already have the right paths?

**Comment by zxwild** [comment]
@pimlie yes, thanks, it could be a solution, if I specify `publicPath: '/static/_nuxt/'`.

I have the right paths, but if I inject it I'll get duplicates cause I need other parts like embedded styles, {{ APP }} contains too much information.

It would be nice to split {{ APP }} to something like this:

```
APP = {
    'embedded_styles': '<style> ... </style>'
    'js': [{path: 'script1.js', rel: '...'}, ...],
    'css': [{path: 'style1.css', rel: '...'}, ...],
}
```

**Comment by pimlie** [comment]
At the moment I dont think thats easily possible. You could try to [hook into the renderer](https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-renderer/src/renderers/ssr.js#L77) and create your page from within the `vue-renderer:ssr:context` hook and then just ignore the page generated by nuxt. But not sure if that will work, never tried it ;)

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
