### ISSUE TITLE
Simplify Config for slots in view/layout files

### ISSUE THREAD

**Issue by connecteev** [nuxt/nuxt#6102]
### What problem does this feature solve?

Nuxt added support for named views / layouts a few months ago. See:
https://nuxtjs.org/examples/named-views
https://github.com/nuxt/nuxt.js/pull/4410/files
(As an aside, in the documentation, I would use the word "slots" and say something like "Named views and layouts" or "Named slots in views and layouts")

More importantly - Could this configuration get any more complicated?

In my view / layout file, I should just be able to use:
```
<Nuxt name="top" />
```

And Nuxt should be able to figure out which route I am using the "top" slot in. Why do I even need to tell Nuxt which route "top" applies to, let alone with such a complicated config that I can't seem to figure out how it works? I'm a huge fan of simplicity and sometimes Nuxt tries to make things less intuitive than they need to be.

Current config for "slots":
```
  router: {
    extendRoutes(routes, resolve) {
      let index = routes.findIndex(route => route.name === "main");
      routes[index] = {
        ...routes[index],
        components: {
          default: routes[index].component,
          top: resolve(__dirname, "components/mainTop.vue")
        },
        chunkNames: {
          top: "components/mainTop"
        }
      };
    }
  }
```

Proposed config for slots:
```
slots: {
    top: "components/mainTop",
    bottom: "components/mainBottom",
}
```

More history and background: 
https://github.com/nuxt/nuxt.js/issues/190
https://github.com/nuxt/nuxt.js/issues/1079

### What does the proposed changes look like?

SImplify config for slots to Nuxt layout files. See above.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9521">#c9521</a>)</em></sub></div>

**Comment by manniL** [comment]
Could you please elaborate? What kind of slots?

Does https://github.com/nuxt/nuxt.js/pull/4410/files already solve the need by supporting multiple `nuxt-child`s?

**Comment by connecteev** [comment]
Yes, thanks - it wasn't obvious that this was supported for layout files. But seriously could this configuration get any more complicated?

In my view / layout file, I should just be able to use:
```
<Nuxt name="top" />
```

And Nuxt should be able to figure out which route I am using the "top" slot in. Why do I even need to tell Nuxt which route "top" applies to, let alone with such a complicated config that I can't seem to figure out how it works? I'm a huge fan of simplicity and sometimes Nuxt tries to make things less intuitive than they need to be.

Current config for "slots":
```
  router: {
    extendRoutes(routes, resolve) {
      let index = routes.findIndex(route => route.name === "main");
      routes[index] = {
        ...routes[index],
        components: {
          default: routes[index].component,
          top: resolve(__dirname, "components/mainTop.vue")
        },
        chunkNames: {
          top: "components/mainTop"
        }
      };
    }
  }
```

Proposed config for slots:
```
slots: {
    top: "components/mainTop",
    bottom: "components/mainBottom",
}
```

**Comment by connecteev** [comment]
Updated the title and description to reflect the desired changes for slots config.

**Comment by danielroe** [comment]
We now have support for the standalone `<NuxtLayout>` component in Nuxt 3, which can be used within a page and allows using slots in the normal Vue way without the need for additional configuration.
