### ISSUE TITLE
Allow nuxt running from subfolder or `file://` protocol (like vue-cli 3 projects)

### ISSUE THREAD

**Issue by tiptronic** [nuxt/nuxt#6133]
### What problem does this feature solve?

Allow to run a compiled (pre-rendered) nuxt project from the `file://` protocol or from any subfolder (on the server) without modification.
Much like proposed here:
https://cli.vuejs.org/config/#publicpath

### What does the proposed changes look like?

Can't say, but in vue-cli 3 the trick is setting `publicPath` to the empty string ("")

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9558">#c9558</a>)</em></sub></div>

**Comment by manniL** [comment]
Vue CLI docs also state on the same page:

> Relative publicPath has some limitations and should be avoided when:
You are using HTML5 history.pushState routing;
You are using the pages option to build a multi-paged app.

Nuxt fulfills both points by default, so this might be a bit tricky.
Using `hash` router instead of the `history` one would solve the first point mentioned, not sure how to handle the second.

**Comment by tiptronic** [comment]
I don't understand these comments, because imo history.pushState routing is something which is not really a common use-case - and why sacrify something useful for something rare.

I don't know what the `pages option to build a multi-paged app` means. So - I for one - would rather refrain from using that feature in favor of relative paths... (which - again - imo is one of the most basic/common ways of navigation inside a multi-level html-installation)

**Comment by manniL** [comment]
> I don't understand these comments, because imo history.pushState routing is something which is not really a common use-case - and why sacrify something useful for something rare?

It's quite the opposite actually! 
Sure, you can run SPAs with the router hash mode and "no real URLs", but the [`history`](https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations) mode is the most common.

**Comment by tiptronic** [comment]
Just a bit, please... I am still talking about pre-rendered (static) sites - where there's no need for mod-rewrite and the likes 😋

**Comment by aldarund** [comment]
pre rendered static sites still use history mode when navigation on client after initial load

**Comment by tiptronic** [comment]
Isn't that an unnecessary restriction to the whole system?

If a site gets pre-rendered to its lowest common factor (html/css files), everything about the site's structure is known. And these static sites ought to run without javascript, because there's no need to **navigate** using Javascript, since all pages/files are known and statically available (at a known location). _(I'm not talking about dynamic enhancements)_

So, if a user switches off Javascript in the browser - the sites should still be useable.

If that's not the case - my understanding of `static sites` may be wrong ...

**Comment by manniL** [comment]
It will be usable, but not necessarily the whole page.
Plus, if JS is enabled, it will behave as an SPA nevertheless. The "traditional navigation" via `a` tags and full reloads is just a fallback.

**Comment by tiptronic** [comment]
For me it's not useable **at all** but the initial page (any links are pointing towards the root -> in case of the `file://` protocal it's e.g. `file:///docs`). In Vue, I can adjust `publicpath` to the empty string to allow for that. Using `nuxt.js` that doesn't work.

But maybe you can quickly folow the 'Setup' here:
https://github.com/nuxt/nuxtjs.org

```bash
git clone https://github.com/nuxt/nuxtjs.org.git
cd nuxtjs.org/
yarn install
git clone https://github.com/nuxt/docs
```

and let me know how to change `nuxt.config.js`, so I can run it from the file-system (using `file://`) inside any folder - or using 'traditional navigation' (which is no problem when using Vue.js )

**Comment by pimlie** [comment]
Try to set [`router.base`](https://nuxtjs.org/api/configuration-router#base) to `./`, that works for me to use a static generated website in an electron app without a webserver.

**Comment by tiptronic** [comment]
@pimlie Did you try double-lick from the file-system (without Electron)? Because that's what I was talking about...

**Comment by gonlyk** [comment]
same problem when use `nuxt3 ssg`+`electrion`,there is similar problem on `vite`+`mpa`.
[](https://github.com/IndexXuan/vite-plugin-mpa/tree/main/examples/vue3-mpa-app)

**Comment by AlansCodeLog** [comment]
:pray: This would make working with electron so much easier.

**Comment by danielroe** [comment]
I think this is a limitation as we use JS modules.

Here's an explanation: https://barker.codes/blog/javascript-modules-and-the-file-uri-scheme/

It may be possible to work around it by inlining all JS in the page, but I don't think that would solve the issue of developing with electron ...

I'm going to close this for the moment - please do comment if this is still relevant for you.

**Comment by AlansCodeLog** [comment]
To anyone still looking for a solution for electron, what I ended up doing was modifying how electron handles the file protocol using `win.webContents.session.protocol.handle` and resolving the requests myself so I didn't have to mess with baseUrl. Note that if using nuxt-electron, it changes this and some other route stuff unless you use disableDefaultOptions. Personally I ended up creating my own module for using electron since I ended up requiring quite a custom setup.

This requires creating the "basePath" used below somehow. What I did was I injected the public path using vite's define and created the path at runtime so it's relative to `app.getAppPath()`.

```ts
// const basePath = ...
win.webContents.session.protocol.handle("file", async request => {
	const url = decodeURIComponent(request.url.slice(7)) // slice off the protocol
	const newUrl = path.isAbsolute(url)
		? path.resolve(basePath, url.slice(1))
		: path.resolve(basePath, url)
        // you can further check newUrl here to make sure it's an allowed resource
	const res = await net.fetch(`file://${newUrl}`, {
		// avoid infinite loop
		bypassCustomProtocolHandlers: true,
	}).catch(err => new Response(err, { status: 404 }))
	return res
})
```

**Comment by pathnirvana** [comment]
Have the same issue when trying to create an android webview app using the static generated content from nuxt3. All the links generated are absolute and not relative

e.g. href="/_nuxt/entry.d39ff17b.js" instead of href="_nuxt/entry.d39ff17b.js" would have to ditch nuxt and back to plain vue

**Comment by manniL** [comment]
@pathnirvana best to raise a new issue IMO.
