### ISSUE TITLE
Add an option to nuxt generate to generate a single route

### ISSUE THREAD

**Issue by emiliobondioli** [nuxt/nuxt#6138]
### What problem does this feature solve?

Example use case:
A static generated app with thousands of routes, like an e-commerce having a route for each product. 
Apart from scheduling `nuxt generate` to run periodically and generate all static and dynamic routes, it would be nice to have the possibility to generate the static files for a single route, for example in a hook when the related backend item is updated. 

In a situation where there's a high frequency of updates, re-generating all the dynamic routes every time there's an update to a single one is not really efficient. This way, for every update, just the interested route is re-generated and replaces the previous one (if present).

### What does the proposed changes look like?

Update the  `nuxt generate` command to accept a -r or --routes option, for example:
`nuxt generate --no-build -r /products/42`

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9562">#c9562</a>)</em></sub></div>

**Comment by pimlie** [comment]
You could already implement this yourself in `nuxt.config.js` as follows:

```js
  generate: {
    routes() {
      const rIdx = process.argv.indexOf('-r')
      if (rIdx) { // it will never be 0 as that would be the node/nuxt command
        return [
          process.argv[rIdx + 1]
        ]
      }
      // return default / all routes
    }
}
```

**Comment by emiliobondioli** [comment]
Nice solution, thanks!
Do you think adding it to nuxt core would be out of scope, then?

**Comment by emiliobondioli** [comment]
Nice solution, thanks! But I tried it now and even using the `--no-build` flag this still removes all the other generated pages, leaving only the new one, is there any way to change this behavior?

**Comment by monisnap-julien** [comment]
Hi ! I'm also facing this issue right now while making a blog. I will have a growing number of pages and doing the `nuxt generate` will take more and more time. Hope to find a solution as soon as possible !

**Comment by pimlie** [comment]
Much easier to just manage your dist folder a bit, no need to change anything in nuxt for that:

```bash
$ yarn generate
$ rsync -auv dist/* production-build/
$ yarn generate --no-build -r /single/route
$ rsync -auv dist/* production-build/
```
and to start over:
```bash
$ rm production-build/* -Rf
```

**Comment by emiliobondioli** [comment]
Ok that seems like a good workaround! so you think having this built into nuxt would be useless/out of scope?

**Comment by manniL** [comment]
I think it'd be a good fit for static generation :relaxed:

**Comment by Atinux** [comment]
About full static mode, re-generating a single route might be difficult for the payload hash @manniL 🤔

**Comment by manniL** [comment]
@Atinux damn, thats right :see_no_evil:

**Comment by hesselberg** [comment]
@Atinux @manniL did you ever find a way of handling the payload hash? 🤔

**Comment by Atinux** [comment]
Yes, you want to look at the target PR :)

**Comment by simplenotezy** [comment]
Would love this as well. It doesn't work quite well now, as when people edit one page in the CMS whole site has to be regenerated which takes around 2000 seconds.

**Comment by jonalxh** [comment]
Having the same trouble with my project, I have a `products page` and a `details page` which is dynamic, If I access it by `products page` and then refresh, it throws `404` in production. I've done the process with `npm run generate`.

**Comment by wusongliang** [comment]
Is there a better solution

**Comment by ltroya-as** [comment]
What about the hashes? It is not clear for me how you guys handle the hashes generated on every build

**Comment by thomas4Bitcraft** [comment]
@ltroya-as with hashes you mean the payloads are not loaded like I have here -> https://github.com/nuxt/nuxt.js/discussions/10623 ?

**Comment by surgiie** [comment]
Anyone successfully doing this in nuxt 3? Looking for way to accomplish this in nuxt 3.

**Comment by danielroe** [comment]
This indeed is the plan. Let's track in https://github.com/nuxt/nuxt/issues/14605 for now.

**Comment by koko1928** [comment]
It's very good!

**Comment by surgiie** [comment]
Anyone have an example of doing this in nuxt 3?

**Comment by yvess** [comment]
This works for me to partial update generated pages with rsync

nuxt.config.ts, use same buildId for builds, to make them easier mergable. 

```
    runtimeConfig: {
      app: {
        buildId: 'prod'
      },
    ...
    }
```

merge old and new prerendered routes with jq, to always load the payload files, also for new generated pages

```
jq -s '{id: .[0].id, timestamp: (max_by(.timestamp) | .timestamp), matcher: .[0].matcher,
prerendered: (map(.prerendered // [])| add| unique)}' existing_full_build_dir/prod.json new_partial_build_dir/prod.json
```
