### ISSUE TITLE
Optimizing CSS delivery for better page speed performance

### ISSUE THREAD

**Issue by tarunmangukiya** [nuxt/nuxt#6144]
### What problem does this feature solve?

Currently, there are 2 ways to use css in Nuxtjs while in production `universal` mode.
1. Delivering CSS with Components
2. Using `extractCSS` which generates external CSS file for each component

Current methods have below drawbacks.
**1st method:**
This adds all the CSS in every SSR request and adds KBs (~100KB). Usually our 40-60% servers are being used due to bots which will be executed by SSR. This CSS includes the CSS we defined in `nuxt.config.js` in `css` block and the component `style` element.

**2nd method**
This creates tiny ~1-5kb CSS files and blocks the page load, as usually we have 10s of components in a page.
Even if we load them async then, it'll create ui flicker on first load (loads html first then loads css).

You can look at the issue on our site https://iconscout.com. There are ~9 css files in the header, which causes slow load time for first time users. And in 1st method, it compiles and adds it in `<head>`.

### What does the proposed changes look like?

Ideally we should have one/two master `css` file which loads with the page and the component CSS loads with the components itself.
For example,
- If we've defined `main.scss` in our `nuxt.config.js` then it'll add something like `https://example.com/_nuxt/main.css`.
- And all other component styles can be there in the `<style>` section in `<head>`.

Every site should have one important CSS framework, i.e. bootstrap, bulma, etc. This we'll define in our `nuxt.config.js`, and it'll be cached by CDNs as they usually don't change frequently.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9567">#c9567</a>)</em></sub></div>

**Comment by manniL** [comment]
You have the option to define global css via the `css` property in your `nuxt.config.js`. Does that already solve the issue? :thinking: 

---

PS:

Using `extractCSS` will have negative impact in case you have a lot of components with just a bit of CSS. Anyway, only files that are needed for the current components on the page will be loaded.

**Comment by tarunmangukiya** [comment]
It loads with the page itself as `<style>` element. Thus adds ~100kb with every page.
For example, our Nuxtjs site https://nuxtjs.org/. There is `<style>` which has all the `css` defined in `nuxt.config.js`. This is an issue for larger website having, lots of static pages, dynamic pages, dashboard, and even admin panel. Thus almost most of bootstrap css is utilised across the site.

![image](https://user-images.githubusercontent.com/12470086/62002595-f5114700-b124-11e9-94f1-830ed09b6e28.png)

**Comment by manniL** [comment]
> It loads with the page itself as <style> element. Thus adds ~100kb with every page.
For example, our Nuxtjs site nuxtjs.org. There is <style> which has all the css defined in nuxt.config.js

Correct. but as only the first request loads this style tag (for the global styles), further navigation won't load the styles "again" (except hard refreshes and so on). 
For crawlers, that'd be the case though as you said.

So what you suggest is basically add all global styles in (one or multiple) separate files that are loaded instead of inlining them?

**Comment by tarunmangukiya** [comment]
Correct, as you said it'll be there for the first request. But as I said earlier, our most of servers are being used by robots, which adds extra bandwidth.

Yes, adding them as `css` files instead of inlining them. This will make it faster for CDNs to cache and there will be 1-2 network request based on one's `nuxt.config.js`.

For example, if I've used `bootstrap.scss` in my `nuxt.config.js`, then we'll inject one common `css` link.

**Comment by manniL** [comment]
A few options for the current situation:

1. You could remove CSS and even JS via Nuxt hooks for crawlers and bots
2. You could use `static` to add your CSS in there

---

Yes, extracting global CSS into a single file would lead to fewer network requests but also to a delay in applying the styles.
Unfortunately there is only "all or nothing" at the moment as the css extract plugin doesn't support a threshold on when to extract and when to keep CSS inline.

**Comment by tarunmangukiya** [comment]
This thing will require manually compiling of the `scss` file and append them.

Isn't it possible to have this feature inbuild? May be more people can give detailed insights on this. 

As, being knowledge of basic SEO things, I can say this is good idea to have. As this gives control to developer on how many style rules they want in their global file and rest can keep with the component itself, which will be added as `<style>`.

**Comment by manniL** [comment]
> This thing will require manually compiling of the scss file and append them.

The second option would, the first not at all.

> Isn't it possible to have this feature inbuild? May be more people can give detailed insights on this.

Please refer to my previous answer.

> As, being knowledge of basic SEO things, I can say this is good idea to have. As this gives control to developer on how many style rules they want in their global file and rest can keep with the component itself, which will be added as <style>.

I'm afraid that this has nothing to do with SEO directly but with performance (and therefore indirectly with SEO, as faster pages rank better, ceteris paribus).

**Comment by Atinux** [comment]
Have you tried using [nuxt-purgecss](https://github.com/Developmint/nuxt-purgecss) to lower your CSS used? I know it's not the answer you are looking for but may at least save some bandwith to start :)

**Comment by simplenotezy** [comment]
I have the exact same issue.

All my pages, that are statically generated, is around 300kb. I think that is too much, and could be lowered a lot.

There should definelty be an option to define a "main" stylesheet, and then have other style loaded in external css files or perhaps just inlined (if size is small). This would also allow for browser caching of the stylesheet, which would make recurring visits load much faster.

Thanks @Atinux I'll have a look at purgecss.

**Comment by simplenotezy** [comment]
Did you find a workaround @tarunmangukiya?

**Comment by tarunmangukiya** [comment]
Nope. I'm using the way it is. Plus `purge-css` is removing important CSS too, so can't use them!

**Comment by sakandemir06** [comment]
I have some problems with my big project. When I use extractCSS my Pagespeed Insight performance is down 70 to 30, (I Use CDN) and my FCP (First contentful paint) duration is increase 1.5s to 5s. But I need to use extractCSS for separate CSS files and I need 70+ performance scores.

So, I use "nuxt-postcss" plugin and I'm not sure if this plugin is working properly. Because, Although I use postcss with this configs

`postcss: {
     plugins: [
	purgecss({
	   content: ['./pages/**/*.vue', './layouts/**/*.vue', './components/**/*.vue'],
		  whitelist: ['html', 'body'],
	    })
	]
}`

The page still have 82% unused CSS. See the screenshot;

![image](https://user-images.githubusercontent.com/41190380/81597984-41392980-93cf-11ea-902f-3a5cfdac443c.png)

A global main.scss file has in nuxt.config.js. This SCSS file contains bootstrap scss and other custom SCSS's I think this global SCSS file doesn't purge properly.


`css: [
		'~assets/scss/main.scss'
	],`

Can you tell me what is wrong here? Why purgecss doesn't work properly. And why When I add extractCSS to nuxt.config.js my performance score is down 40 points. This issue very important for me I wrote a lot of times on Discord channel but anyone didn't answer me. 
(Not native English)
@Atinux

**Comment by Khezcute** [comment]
> I have some problems with my big project. When I use extractCSS my Pagespeed Insight performance is down 70 to 30, (I Use CDN) and my FCP (First contentful paint) duration is increase 1.5s to 5s. But I need to use extractCSS for separate CSS files and I need 70+ performance scores.
> 
> So, I use "nuxt-postcss" plugin and I'm not sure if this plugin is working properly. Because, Although I use postcss with this configs
> 
> `postcss: { plugins: [ purgecss({ content: ['./pages/**/*.vue', './layouts/**/*.vue', './components/**/*.vue'], whitelist: ['html', 'body'], }) ] }`
> 
> The page still have 82% unused CSS. See the screenshot;
> 
> ![image](https://user-images.githubusercontent.com/41190380/81597984-41392980-93cf-11ea-902f-3a5cfdac443c.png)
> 
> A global main.scss file has in nuxt.config.js. This SCSS file contains bootstrap scss and other custom SCSS's I think this global SCSS file doesn't purge properly.
> 
> `css: [ '~assets/scss/main.scss' ],`
> 
> Can you tell me what is wrong here? Why purgecss doesn't work properly. And why When I add extractCSS to nuxt.config.js my performance score is down 40 points. This issue very important for me I wrote a lot of times on Discord channel but anyone didn't answer me. (Not native English) @Atinux

When u use purgeCss, build property clean all class of unused css, I have the same issue but I resolve this with change all to TailwindCss.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
