### ISSUE TITLE
Splitting CSS by Media queries

### ISSUE THREAD

**Issue by Jesus82** [nuxt/nuxt#6171]
### What problem does this feature solve?

Right now you cannot split the CSS by media queries, so you end up loading CSS that you won't need for your viewport

### What does the proposed changes look like?

It would be like this webpack plugin https://github.com/SassNinja/media-query-plugin
(copying from there)

So instead of forcing the user to load this

`.foo { color: red }
@media print, screen and (min-width: 75em) {
    .foo { color: blue }
}
.bar { font-size: 1rem }`

he only has to load this always

`.foo { color: red }
.bar { font-size: 1rem }`

and on desktop viewport size this in addition

`@media print, screen and (min-width: 75em) {
    .foo { color: blue }
}`

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9591">#c9591</a>)</em></sub></div>

**Comment by manniL** [comment]
This will be tricky as the viewport size is unknown on the server.

**Comment by Jesus82** [comment]
Wouldn't it be possible to split the CSS in the server, and then conditional load it in the client? (or at least split it in the server, and use preference high for the mobile).

Thanks!

**Comment by danielroe** [comment]
let's track this in https://github.com/nuxt/nuxt/issues/14681.
