### ISSUE TITLE
Custom srcDir and relate `dir.pages` don't harmonize together

### ISSUE THREAD

**Issue by zw1371** [nuxt/nuxt#6229]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://github.com/zw1371/nuxt-demo](https://github.com/zw1371/nuxt-demo)

### Steps to reproduce

![nuxt.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/ec0293f0-be6f-11e9-a06f-9dc6e7d3e46e.png)

### What is expected ?

when npm run dev,it can be work

### What is actually happening?

we can open http://localhost:3000, but three is a fail in that page

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9640">#c9640</a>)</em></sub></div>

**Comment by manniL** [comment]
Interesting. If I remove the `script` part of your `index.vue`, it shows the template. Otherwise, the error will be thrown.

**Comment by manniL** [comment]
Quick git diff that works for me:

```
diff --git a/nuxt.config.js b/nuxt.config.js
index f338a5f..48de368 100644
--- a/nuxt.config.js
+++ b/nuxt.config.js
@@ -1,11 +1,7 @@
 module.exports = {
-  dev: true,
-  rootDir: "./",
+  rootDir: './',
   srcDir: 'nuxt/',
   dir: {
-      pages: '../project'
-  },
-  server: {
-    port: 3000
+      pages: '../project/'
   }
-};
\ No newline at end of file
+};
diff --git a/nuxt/app.html b/nuxt/app.html
deleted file mode 100644
index 2ee2ded..0000000
--- a/nuxt/app.html
+++ /dev/null
@@ -1,11 +0,0 @@
-<!DOCTYPE html>
-<html {{ HTML_ATTRS }}>
-  <head {{ HEAD_ATTRS }}>
-    {{ HEAD }}
-    <meta http-equiv="pragma" content="no-cache">
-    <meta http-equiv="cache-control" content="no-store">
-  </head>
-  <body {{ BODY_ATTRS }}>
-    {{ APP }}
-  </body>
-</html>
\ No newline at end of file
diff --git a/package.json b/package.json
index fa177c7..ab3e3de 100644
--- a/package.json
+++ b/package.json
@@ -1,8 +1,6 @@
 {
   "name": "nuxt-test",
   "version": "1.0.0",
-  "description": "",
-  "main": "index.js",
   "scripts": {
     "dev": "nuxt"
   },
diff --git a/project/index.vue b/project/index.vue
index 903916c..30e0c96 100644
--- a/project/index.vue
+++ b/project/index.vue
@@ -3,13 +3,11 @@
     nuxt-test
   </div>
 </template>
+
 <script>
 export default {
-  name: "index",
-  methods: {
-  },
-  mounted() {
-    
-  }
-};
+ mounted () {
+  console.log('ok')
+ }
+}
 </script>
```

![image](https://user-images.githubusercontent.com/640208/63008954-e1374600-be83-11e9-8b4b-0b3a527540dc.png)


I've remove the `app.html`. You can add meta tags via `head` in your nuxt.config.js if you only need to do that.

**Comment by zw1371** [comment]
hi , thank you very much for your help, but sorry, i forget one point, that is nuxt.config.js must have dev:true , it mean i want to Running nuxt with Development mode. but it throw error when i try

**Comment by zw1371** [comment]
@manniL hi , thank you very much for your help, but sorry, i forget one point, that is nuxt.config.js must have dev:true , it mean i want to Running nuxt with Development mode. but it throw error when i try

**Comment by manniL** [comment]
Dev mode is automatically enabled when just running `nuxt`.

**Comment by zw1371** [comment]
@manniL i find the difference between your nuxt.config.js and my nuxt.config.js, your nuxt.config.js is pages: '../project/'. my nuxt.config.js is pages: '../project', this is the key to explain why nuxt not work.  i changed nuxt.config.js from pages: '../project' to pages: '../project/'. so it worked. but when i put main.vue in project directory. then i open http://localhost:3000/main.  it is failed

**Comment by zw1371** [comment]
@manniL 
![nuxt](https://user-images.githubusercontent.com/18106847/63018741-2e3f0a80-becc-11e9-9923-af3758239ef5.png)

**Comment by zw1371** [comment]
@manniL even i put a file in project directory，i can not open it, like this:
![nuxt](https://user-images.githubusercontent.com/18106847/63019403-d3a6ae00-becd-11e9-898d-b68950b3375c.png)

**Comment by GopherJ** [comment]
why it's closed even it doesn't seem to be working?

**Comment by danielroe** [comment]
This should work in the latest Nuxt 3.
