### ISSUE TITLE
global transition-duration causes route/title change delay

### ISSUE THREAD

**Issue by m4rvr** [nuxt/nuxt#6330]
### Version

[v2.9.2](https://github.com/nuxt.js/releases/tag/v2.9.2)

### Reproduction link

[https://codesandbox.io/s/codesandbox-nuxt-ipv9k?fontsize=14](https://codesandbox.io/s/codesandbox-nuxt-ipv9k?fontsize=14)

### Steps to reproduce

1. Navigate between the pages by pressing the button
2. After 2-3 times the title change in the tab is delayed
3. Continue navigating between the pages and keep focus on the tab

### What is expected ?

1. No route/title change delay
2. No fallback to default title

### What is actually happening?

1. Route/title change is affected by global `transition-duration`
2. Default title visible in tab between change

### Additional comments?

Caused by:
```
*, ::before, ::after {
  transition-duration: 250ms;
}
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9703">#c9703</a>)</em></sub></div>

**Comment by manniL** [comment]
The first aspect (the delay for the title change) is intentional and fits to the transition duration.

What really bugs me is the default title (`Transition Bug - Transition Bug`) being visible after a few changes :thinking: 	

![transition-bug](https://user-images.githubusercontent.com/640208/63888209-bd751380-c9de-11e9-80d7-3a405962e12c.gif)

cc @pimlie 	Any idea?

**Comment by pimlie** [comment]
Vue-meta will update the title whenever a change is detected, so I guess there is a measurable delay between the old page component being removed by nuxt and the new one being added. 

Normally I would recommend to set [`refreshOnceOnNavigation`](https://vue-meta.nuxtjs.org/api/#refreshonceonnavigation) in the vue-meta options, unfortunately I dont think you can do that with nuxt except for manually changing the `@nuxt/vue-app/template/index.js` file in node_modules.

**Comment by manniL** [comment]
@pimlie 	Do you think that'd be a nice addition/optional feature (to config vue meta settings for Nuxt.js via `nutx.config.js)?

**Comment by pimlie** [comment]
Maybe it would be better/easier/quicker if we change vue-meta that you toggle that option during runtime. Looking at the other options the refreshOnce is a bit of an odd-ball anyway.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
