### ISSUE TITLE
Allow a promise to be returned in the layout method

### ISSUE THREAD

**Issue by gijsroge** [nuxt/nuxt#6333]
### What problem does this feature solve?

Right now it's not possible to dynamically change the layout based on ajax call.

Let's say we have a route 'user/jhondoe' and based on a preference set by the user jhondoe we should be able to change the layout.

Another possible solution is to change the lifecycle so that the layout gets resolved after fetch/asyncData. But i'm not sure how feasible this is.

Related: #3510

### What does the proposed changes look like?

```js
async layout({ store, route }) {
  await store.dispatch('userModule/getUserPreferences', route);
  if (store.state.preference.lorem) {
  	return 'custom';
  }

  return 'default';
}
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9707">#c9707</a>)</em></sub></div>

**Comment by pimlie** [comment]
You could use a [middleware](https://nuxtjs.org/api/pages-middleware#the-middleware-property) for that, those can be async and are run before the layout is loaded/changed on navigation.

You just have to make sure to pass the layout from the middleware to the layout function using a context property like the store in your example

**Comment by gijsroge** [comment]
@pimlie Sorry for the late response.

This only works for client sided navigation because whenever I load the page first, the async middleware is loaded after the layout function has been called?

For example i have this middleware/layout.ts

``` javascript
import { Middleware } from '@nuxt/types';

const LayoutMiddleware: Middleware = async context => {
  context.layout = 'default';
  await context.store.dispatch('Module/Foo', context.route);

  if (context.store.state.Module.Foo.customLayout) {
    context.layout = 'customlayout';
  }
};

export default LayoutMiddleware;
```

And in the page component i register the middleware and call the layout method:
``` javascript
layout(context) {
    return context.layout; // <- undefined on ssr | defined and client sided navigation
  }
```

I hope I'm not missing something obvious here? 

I could setup a CodeSandbox if needed.

Thanks

**Comment by pimlie** [comment]
In universal mode Nuxt expects the layout to have been set server-side already, which means that middleware isnt run on hydration. There is a rfc to make it possible to configure this behaviour: https://github.com/nuxt/rfcs/issues/28

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
