### ISSUE TITLE
Client-mode builds should resolve the "pkg.module" field rather than "pkg.browser", for imported modules

### ISSUE THREAD

**Issue by morficus** [nuxt/nuxt#6361]
### What problem does this feature solve?

The mysterious and ever elusive [package.json file](https://docs.npmjs.com/files/package.json). For the context of this feature request there are three particular fields of interest
* `main`: the primary entry point to a NodeJS module/program. Expected to be in a CommonJS (CJS) format (aka: using `require()`) since that is what NodeJS handles natively 
* `browser`: similar to main, but meant to be used client-side and consumed directly in the browser (aka: using `<script>` tag)
* `module`: similar to the two above fields, but intended only to expose ESM (ECMAScript modules) rather than CJS (aka: using `import`)

While "module" is not part of the official NodeJS or npm spec, it is extremely widely used by package developers ([Vue](https://github.com/vuejs/vue/blob/dev/package.json#L6), [Vuex](https://github.com/vuejs/vuex/blob/dev/package.json#L6), [Angular](https://github.com/angular/angular/blob/master/packages/core/package.json#L6), [Vuetify](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/package.json#L23)) and is recognized by all major bundlers as part of their resolution algorithm ([webpack](https://webpack.js.org/configuration/resolve/#resolvemainfields), [Rollup](https://github.com/rollup/rollup/wiki/pkg.module))

Defaulting to the "browser" field seems incorrect, since every Nuxt project will have a build system and therefor be ESM aware. 

Similar to how the Nuxt [webpack server config](https://github.com/nuxt/nuxt.js/blob/dev/packages/webpack/src/config/server.js#L48) reprioritized modules, the same should be done for the [webpack client config](https://github.com/nuxt/nuxt.js/blob/dev/packages/webpack/src/config/client.js)

### What does the proposed changes look like?

/packages/webpack/src/config/server.js#L48
`resolveConfig.resolve.mainFields = ['module', 'browser', 'main']`

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9728">#c9728</a>)</em></sub></div>

**Comment by clarkdo** [comment]
Will look into this

**Comment by morficus** [comment]
> For the libs which have both browser and module bundle, if only difference between them is esm or commonjs
the more common scenario is that the `browser` bundle is not cjs but either (in webpack terms) "window" or "umd". if it was cjs it would just stick to using the regular "main" field.

> As a quick solution of your requirement, I suggest using build.extend of nuxt.config to override client side mainFileds

yup, that is exactly what I'm doing today

**Comment by danielroe** [comment]
This is now resolved in Nuxt 3.
