### ISSUE TITLE
Expose publicly internal scripts/package.js for Monorepo maintainers

### ISSUE THREAD

**Issue by renoirb** [nuxt/nuxt#6380]
### What problem does this feature solve?

As a monorepo maintainer, I want to normalize/synchronize fields in my packages’ *package.json*. **AND** Nuxt.js’ does it already. But it's hidden, and inaccessible for other monorepo maintainers. 

* This started [based on a twitter thread](https://twitter.com/shellscape/status/1169303684976697347)
* And also on [RushJS.io's](https://rushjs.io/) (a monorepo manager, like Lerna. But leveraging PNPM)  [Gitter (link to channel)](https://gitter.im/web-build-tools/web-build-tools?at=5d71af113b1e5e5df15d47bc)

### What does the proposed changes look like?

See [nuxt/nuxt.js#6373](https://github.com/nuxt/nuxt.js/pull/6373)

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9741">#c9741</a>)</em></sub></div>

**Comment by danielroe** [comment]
It may be worth checking https://github.com/danielroe/siroc. I think we'll close this as we have moved to a different monorepo setup and open-sourced https://github.com/unjs/unbuild instead.
