### ISSUE TITLE
Do not override config values in `nuxt.config.js` when using the Nuxt CLI tools

### ISSUE THREAD

**Issue by thuringia** [nuxt/nuxt#6386]
### What problem does this feature solve?

This allows us to use the `nuxt build` then `nuxt start` chain of commands to build and deploy development and production environments in the same way. It also allows us to provide a much better testing experience in development environment due to the much richer logging Nuxt provides in dev mode.

Concrete use case:
We're using separate Kubernetes clusters for development/integration and production. Both environments have an identical build and deployment setup with the same restriction: we do not run `nuxt build` in a pod due to its resource consumption. This rules out any usage of `nuxt dev`.

If `nuxt build` respects the the value of `NODE_ENV` and/or the value of `dev` in `nuxt.config.js` this scenario becomes possible. It also has the added benefit of providing symmetry to the tools nuxt is build on, e.g. webpack only forces production optimizations when using the `-p` flag or when setting it in the config file.

### What does the proposed changes look like?

The nuxt CLI no longer overrides the configuration file. The current behavior can remain the default, unless explicitly configured otherwise. That way it should not introduce braking behavior

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9747">#c9747</a>)</em></sub></div>

**Comment by pimlie** [comment]
Not sure I fully understand your use-case, but have a look at [NuxtCommands](https://nuxtjs.org/guide/modules#module-package-commands). You could just copy the existing commands and tweak them as you see fit. Even though you can already tweak almost everything using [hooks](https://nuxtjs.org/api/configuration-hooks#the-hooks-property)

**Comment by thuringia** [comment]
@pimlie None of these ideas prevent `nuxt build` from forcing `NODE_ENV=production` as well as other build time optimizations on me. 
Also the point of the feature request is to enable this type of behavior without resorting to hooks or any other low-level/Nuxt-as-a-library type of usage. What I'm proposing is, is that commands like `nuxt build` provide sane defaults, but obay the configuration files, regardless of any specific use case

As for the use-case:
In my case it is the desire to selectively run development or production build from our kubernetes deployments. These clusters are meant as runtime environments, i.e. pods are deployed with quite restrictive resource limits (0.2vCPUs / 75mb memory), precluding any usage of `nuxt build/nuxt dev` inside the cluster.
Though I can imagine other use-cases, like running webpack plugins to inspect a build for development and production in reproducible setups.

I can try phrasing the question differently:
Why does Nuxt behave this way in the first place? Next.js does not (especially in this case), Webpack doesn't and other tools also follow the logic of provide sane defaults but allow developers to overwrite them.

I thought this phrasing may come of as too argumentative though so I based it around the situation I identified this.

**Comment by danielroe** [comment]
We have a new programmatic API in Nuxt 3 which I think should handle your use case and will not override the defaults.

`build`/`dev` commands _do_ need to override `dev` and set `NODE_ENV` as otherwise the commands won't do what they say they are doing which would be a much more confusing situation (ie. it would be possible for `nuxt build` to start a dev server or `nuxt dev` to build the project).
