### ISSUE TITLE
Using Layouts across multiple (non-child) pages

### ISSUE THREAD

**Issue by connecteev** [nuxt/nuxt#6408]
### What problem does this feature solve?

Is there a way to use Layouts across multiple (non-child) pages?

This is a very common use-case: Multiple pages need to look the same (3-column layout). What is the best way to do this without duplicating the HTML markup all over the place?

Here's a real example from one of my sites right now:

Feed Page:
```
<template>
  <div class="container tw-px-1 md:tw-px-2">
    <div class="tw-mt-4">
      <div class="tw-flex tw-flex-wrap tw-mb-4">

        <div class="tw-flex-shrink-0 tw-hidden md:tw-block tw-w-full md:tw-w-4/12 lg:tw-w-3/12 md:tw-px-4">
            <div>
                CONTENT FOR THE FEED PAGE: LEFT SIDEBAR GETS ADDED HERE
            </div>

        <div class="tw-w-full md:tw-w-8/12 lg:tw-w-6/12 md:tw-px-0">
            <div>
                CONTENT FOR THE FEED PAGE: MIDDLE COLUMN GETS ADDED HERE
            </div>
        </div>
        
        <div class="tw-flex-shrink-0 tw-hidden lg:tw-block md:tw-w-4/12 lg:tw-w-3/12 lg:tw-px-4">
            <div>
                CONTENT FOR THE FEED PAGE: RIGHT SIDEBAR GETS ADDED HERE
            </div>
        </div>
      </div>
    </div>
  </div>
</template>
```

Tags Page:
```
<template>
  <div class="container tw-px-1 md:tw-px-2">
    <div class="tw-mt-4">
      <div class="tw-flex tw-flex-wrap tw-mb-4">

        <div class="tw-flex-shrink-0 tw-hidden md:tw-block tw-w-full md:tw-w-4/12 lg:tw-w-3/12 md:tw-px-4">
            <div>
                CONTENT FOR THE TAGS PAGE: LEFT SIDEBAR GETS ADDED HERE
            </div>

        <div class="tw-w-full md:tw-w-8/12 lg:tw-w-6/12 md:tw-px-0">
            <div>
                CONTENT FOR THE TAGS PAGE: MIDDLE COLUMN GETS ADDED HERE
            </div>
        </div>
        
        <div class="tw-flex-shrink-0 tw-hidden lg:tw-block md:tw-w-4/12 lg:tw-w-3/12 lg:tw-px-4">
            <div>
                CONTENT FOR THE TAGS PAGE: RIGHT SIDEBAR GETS ADDED HERE
            </div>
        </div>
      </div>
    </div>
  </div>
</template>

```
As you can see in the above (simplified) example, the Feed page and Tag page share the SAME HTML structure and have a 3-column layout, but their CONTENT is completely different. I couldn't find a way to include slots within layout files. Is this possible? 
This is a very common scenario where your entire site may want to use the same layout and you have to "inject" content into the right slots - how do you solve this problem? I am struggling to imagine how there isn't a solution to this problem in Nuxt.

Note:
These are NOT child-pages (or child routes) of each other, so using nuxt child pages isn't an option.
Selectively showing / hiding content with v-if is clunky and not an option.
Using [component slots](https://alligator.io/vuejs/component-slots/) isn't an option because the content that should go into these slots doesn't really fit the definition of a "component".

### What does the proposed changes look like?

Not sure if there's a way to use slots within layout files....but I need a solution to this.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9769">#c9769</a>)</em></sub></div>

**Comment by connecteev** [comment]
I would really appreciate thoughts from the nuxt core team on this problem

**Comment by pimlie** [comment]
You are aware you could / should use [`<nuxt />`](https://nuxtjs.org/guide/views#layouts) in layouts? The `nuxt` component is a wrapper around `router-view` to automatically support transitions.

There are probably exceptions, but a general rule of thumb is to use `<nuxt />` in layouts and use `<nuxt-child />` in page components.

**Comment by connecteev** [comment]
@pimlie Very much so, and I am using <nuxt /> like this:
```
<template>
  <div>
    <site-header></site-header>
    <nuxt />
    <site-footer></site-footer>    
  </div>
</template>

```
in my base layout file. This is a very rudimentary example though. The question is how to have 2 unrelated (non-child) pages share the same structure, where each page has different content to put into it's multiple "slots".

**Comment by pimlie** [comment]
Ah right, have you seen the [named-views](https://github.com/nuxt/nuxt.js/tree/dev/examples/named-views) example? You can use multiple keys for nuxt, but if you do that you need to extend the routes manually and add components for the named views.

Its also on csb for live trying: https://codesandbox.io/s/github/nuxt/nuxt.js/tree/dev/examples/named-views

**Comment by connecteev** [comment]
@pimlie thank you, I didn't know that named views were a thing, so this helps.
I created a slightly simplified example here for anyone else that has this need:
Demo: https://goo0w.sse.codesandbox.io/feed
Code: https://codesandbox.io/s/my-app-goo0w?fontsize=14

2 areas that I think this can be greatly improved to be cleaner. Hopefully these can both be addressed in a future version of Nuxt:

1. With this approach you still cant inject from a page into the parent layout. You have to break off anything you want to inject into a component (components/feedTop.vue, components/feedBottom.vue for example). This would make your components grow. Other templating languages like blade, for example, allow you to inject from the base page into the parent layout it inherits from.

2. This is the nuxt config I ended up with to extendRoutes. It would be great if in future version of Nuxt, extendRoutes was eliminated and this "just worked" without having to configure it this way. The only downside would be that the "chunkNames" and/or component names would need to be unique.

```
  router: {
    extendRoutes(routes, resolve) {
      let index = null;

      index = routes.findIndex(route => route.name === "feed");
      routes[index] = {
        ...routes[index],
        components: {
          default: routes[index].component,
          top: resolve(__dirname, "components/feedTop.vue"),
          bottom: resolve(__dirname, "components/feedBottom.vue")
        },
        chunkNames: {
          top: "components/feedTop",
          bottom: "components/feedBottom"
        }
      };

      index = routes.findIndex(route => route.name === "tag");
      routes[index] = {
        ...routes[index],
        components: {
          default: routes[index].component,
          top: resolve(__dirname, "components/tagTop.vue"),
          bottom: resolve(__dirname, "components/tagBottom.vue")
        },
        chunkNames: {
          top: "components/tagTop",
          bottom: "components/tagBottom"
        }
      };
    }
  }
```
Would love to leave this issue open to track these..but defer to you on this.

**Comment by pimlie** [comment]
Well, one of the issues is that other templating languages only have to care about the template but a SFC also contains javascript and styling.

If you want this _now_ you could have a look at [portal-vue](https://github.com/LinusBorg/portal-vue) but that doesnt support ssr. Portals should also be included by default in Vue 3, but nothing is sure about that (or when it does if it will support ssr).

**Comment by connecteev** [comment]
@pimlie interesting, look forward to this functionality in Vue 3 and future versions of Nuxt, ideally with SSR.

**Comment by danielroe** [comment]
This is now possible in nuxt 3 with the standalone `<NuxtLayout>` component. Layouts can have slots and be used in any page or component: https://nuxt.com/docs/guide/directory-structure/layouts#layouts-directory
