### ISSUE TITLE
Allow excluding files from the static folder on .nuxtignore

### ISSUE THREAD

**Issue by jaireina** [nuxt/nuxt#6424]
### What problem does this feature solve?

There are several cases where we need to include some test assets in the static folder so we can do development or run a mock version of an app. However those files are not needed for production, but they are bundled with everything within the static folder.
If we have a local folder inside of static where we put all of our test assets it would be great to have a way to tell webpack or the nuxt framework to ignore that local folder when we execute npm run build.

### What does the proposed changes look like?

In .nuxtignore I should be able to include something like
static/local

In order to exclude the local folder from the final build.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9785">#c9785</a>)</em></sub></div>

**Comment by Atinux** [comment]
I like this feature request, cc @clarkdo

**Comment by Hamid-Niakan** [comment]
I need this too! I have a situation where I can generate different builds from the code base using nuxt config and every time I have to delete the unnecessary static files for that specific build

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
