### ISSUE TITLE
Prevent re-render / re-paint of a page when you press the browser back button

### ISSUE THREAD

**Issue by connecteev** [nuxt/nuxt#6451]
### What problem does this feature solve?

I am trying to prevent the page from re-rendering when you press the browser back button in Nuxt in SSR mode. How can this be implemented, is there an example of this? 

To see this in action on dev.to:

* Go to https://dev.to/
* By default, the page should about 45 posts in the news feed.
* Scroll down on the infinite-loaded page so that new posts are loaded in the news feed.
* Click on the title of any post to go to that post view page.
* Click the browser's back button so you go back to https://dev.to/
* Notice that you are taken back to the news feed in the EXACT same state you left it in:
1. The page is NOT re-painted or re-rendered
2. All the posts that were loaded by scrolling down the page (part of the infinite scroll) are preserved.

I want to do the same in my app, and prevent the re-paint / re-render.
How can this be implemented in Nuxt.js in Universal (SSR) mode?

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9807">#c9807</a>)</em></sub></div>

**Comment by applecat** [comment]
> I solved this problem through other methods, but I don't think it's a fundamental solution.
What method did you use?
I'm working on the same problem, I think it's important for UX to have back button properly working.

**Comment by bysxx** [comment]
I solved it using Nuxt life cycle.
Nuxt project must run middleware every time it moves a page.
So when I closed the page, I saved the information on the current page with the expiration date.
And I deleted this information if the expiration period becomes zero by decreasing the expiration period one by one every time I moved the page.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
