### ISSUE TITLE
Close EventSource on not visible tabs

### ISSUE THREAD

**Issue by pimlie** [nuxt/nuxt#6462]
### What problem does this feature solve?

Try to mitigate the issue of the max active connections limit in a browser by actively closing the EventSource when the tab/page is not visible

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9820">#c9820</a>)</em></sub></div>

**Comment by danielroe** [comment]
I think we can close this as we now use vite by default in Nuxt 3. Happy to reopen if you still think this is relevant.
