### ISSUE TITLE
[Feature Request] node option can be specified around core cli

### ISSUE THREAD

**Issue by tanaka-yui** [nuxt/nuxt#6474]
### What problem does this feature solve?

sconfig-paths
I think that it is better to be able to specify the package that can be specified in the node option such as nuxt command or nuxt-ts command.

For example, when starting from ts-node with nuxt-ts command, paths cannot be used for ts-node. In order to be able to use, it is necessary to specify with --require options such as tsconfig-paths, but since node option can not be specified with current cli, when using --require,

"build": "node -r tsconfig-paths / register ./node_modules/@nuxt/typescript-runtime/bin/nuxt-ts.js build"

Should be run directly like

Node option can be specified via cli

"build": "nuxt-ts -r tsconfig-paths / register build"

I think that it is better to be able to execute like this.

I made a PR for nuxt / typescript once, but commented that the core cli is better, so I made a feature request here.

closed
https://github.com/nuxt/typescript/pull/81#event-2590393663

Corresponding part is
Make node option readable around core cli.
Even if nodo-option is specified in nuxt / typescript-runtime, I think that the cli itself will not pass through an error and the option will pass to the core cli.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxtjs.org/issues/c171">#c171</a>)</em></sub></div>

**Comment by pimlie** [comment]
You should already / also be able to pass options to node by using the env var [`NODE_OPTIONS`](https://nodejs.org/api/cli.html#cli_node_options_options)

**Comment by IlyaSemenov** [comment]
You can, but specifically `tsconfig-paths/register` will not work with `nuxt-ts`. I created a reproduction repo to demonstrate the problem: https://github.com/IlyaSemenov/nuxt-reproduction-6474

Note that it used to work with Nuxt 2.6 (before decoupling Typescript support).

**Comment by danielroe** [comment]
In Nuxt 3, the `nuxi` CLI is fully decoupled from Nuxt, with no dependencies, and can be run directly with `node` if needed. If there's still an issue here, please do let me know and we can revisit.
