### ISSUE TITLE
API Routes for serverMiddleware

### ISSUE THREAD

**Issue by ch99q** [nuxt/nuxt#6485]
### What problem does this feature solve?

Currently, the serverMiddleware is a fixed path to a javascript file, but it would be nice to have path-to-regex support like pages for API routes.
NextJS currently have it implemented in version 9.0 of NextJS. Take a look here https://nextjs.org/blog/next-9#api-routes

This would make making backend stuff as simple as adding a new page to your site.

### What does the proposed changes look like?

My propose for the API path would be adding an `api ` folder to the `pages` folder.

The js files would be found like the existing system used for pages, so the route would look like this.

I would have a javascript file at:
/pages/api/books/_category/find.js

and this file would respond to:
GET /api/books/mystery/find

My propose for the config would look something like this.
```javascript
export default {
  serverMiddleware: [
      // Will use route /api/* as a dynamic path for path-to-regex style routing.
      { path: '/api', folder: '/pages/api', dynamic: true }
  ]
}
```

Try to take a look at how NextJS implemented this feature, they came with some really good features such as JSON function to the response variable.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9837">#c9837</a>)</em></sub></div>

**Comment by mrcrille** [comment]
I'm sorry I forgot to mention how the config would look like.

My propose for the config would look something like this.
```javascript
export default {
  serverMiddleware: [
      // Will use route /api/* as a dynamic path for path-to-regex style routing.
      { path: '/api', folder: '/pages/api', dynamic: true }
  ]
}
```

**Comment by GeekBar-Boss** [comment]
Have you solved your question?
I noticed your issue just googling for the same need.
But I just handled it myself and here are my suggestions
You may print the object "req" in servermiddleware after accessing "/api/123" with your config above.
You will find that there are many properties in it you can use, such as req.url (it will be/123).
I hope it will help you and I am just using servermiddleware in nuxt as a reverse proxy server to access my api service instance on my server

**Comment by danielroe** [comment]
This is now implemented in Nuxt 3.
