### ISSUE TITLE
Preload async chunks on a specific route

### ISSUE THREAD

**Issue by jeanphilippeds** [nuxt/nuxt#6510]
### What problem does this feature solve?

Hello,

I wonder if it's possible to preload/prefetch async chunks for a specific route.
I tried to use bundleRenderer/shouldPreload but it's only available on nuxt.config.js, right?

Any hint about this?

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9860">#c9860</a>)</em></sub></div>

**Comment by pimlie** [comment]
Are you talking about doing this dynamically during runtime or you want a specific route to _always_ be preloaded?

**Comment by jeanphilippeds** [comment]
Let's consider I'm loading an async chunk xyz.js on route B, and not on route A. I'd like to be able to always preload xyz.js when I'm landing on route B.

**Comment by gangsthub** [comment]
You can already do this thanks to ["webpack magic comments"](https://webpack.js.org/api/module-methods/#magic-comments) (what a name 😅):

```js
// inside your component, or page or layout...

const MyPreloadedComponent = () =>
  import(
    /* webpackPreload: true */
    /* webpackChunkName: "MyPreloadedComponent" */ '~/components/MyPreloadedComponent'
  )

export default {
  components: {
    MyPreloadedComponent,
  },
  // ...
}
```

Dynamic import will make the chunk to be loaded asynchronously and the `/* webpackPreload: true */` will make a request with the preload option.

**Comment by danielroe** [comment]
This is now possible with the `preloadRouteComponents` composable in Nuxt 3.
