### ISSUE TITLE
extendRoutes: API vs Hook

### ISSUE THREAD

**Issue by farnabaz** [nuxt/nuxt#6516]
Currently, there is two way for a plugin to manipulate nuxt routes, first is `extendRoutes` function in `ModuleContainer` and the other is `extendRoutes` hook.
These two works perfectly on a single plugin, but when it comes to the combination of routes of two module this creates an issue.

Inside Nuxt builder hooks calls before API, so a plugin that uses hook cannot change routes of other plugin that uses API to extend routes
https://github.com/nuxt/nuxt.js/blob/92c7f4ed249466870a477798f910c84eb1fdd18d/packages/builder/src/builder.js#L397-L413

I wonder could we change implementation of `extendRoutes` function in `ModuleContainer` and implement it wi hook?
https://github.com/nuxt/nuxt.js/blob/560cb57443ada3f16a1073c22f616937f8b581f3/packages/core/src/module.js#L107-L112

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9864">#c9864</a>)</em></sub></div>

**Comment by farnabaz** [comment]
@pi0 @Atinux

**Comment by rchl** [comment]
I think having one consistent way would be nice but it wouldn't fix the main problem where multiple modules do route modifications and things are expected to happen in a certain order.

For example, if one is using `nuxt-i18n` to add locales to routes, one would expect that one to run after all other modules and this solution doesn't help with that. One can put modules in a certain order but that is both fragile and not guaranteed to work.

**Comment by danielroe** [comment]
This is now implemented with a hook in Nuxt 3, and `extendPages` is a shortcut to it. @rchl's comment is also helpful - we are discussing the concept of module and plugin dependencies: https://github.com/nuxt/nuxt/issues/14628.
