### ISSUE TITLE
[Proposal] Don't deprecate the ignore property in nuxt 3

### ISSUE THREAD

**Issue by dschox** [nuxt/nuxt#6547]
### What problem does this feature solve?

As stated here: https://github.com/nuxt/nuxt.js/issues/6090
I too would like to keep the ignore property in nuxt 3.
Our app is a whitelabel-app (1 app, n clients), which gets built with different colors, logos, pages, ... based on env vars.
We have some legal pages in our pages dir, but not every client needs that. With the ignore property, we can easily exclude pages from the build based on env var.

I managed to get my desired output too by using router.extendRoutes and create routes for the files needed. Like so:
```javascript
extendRoutes(routes, resolve) {
	routes.push({
		name: 'Test',
		path: '/test',
		component: resolve(__dirname, 'pages_extra/test.vue')
	})
}
```
But I think the ignore property is a better way and seems more natural.

### What does the proposed changes look like?

Don't deprecate it.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9887">#c9887</a>)</em></sub></div>

**Comment by danielroe** [comment]
Nuxt 3 does support `ignore` configuration, so I think we can safely close this issue.
