### ISSUE TITLE
Separate Directory for Static Files in main Directory after Build

### ISSUE THREAD

**Issue by ghost** [nuxt/nuxt#6558]
### What problem does this feature solve?

This  Feature will provide a Separate directory for static files in the Application like The Vue Config (assetsDir) in Vue CLI which allows user to create a Separate files for all The Static assets 

It Solves the issue for many Servers as It eases the Server to Send Static Files

For Eg: I am using Django at the Backend so i have to create a Separate Static dir relative to Templates dir . This would Be really easy if a Feature like this is Implemented

### What does the proposed changes look like?

/dist
--/index.html
--/static

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9899">#c9899</a>)</em></sub></div>

**Comment by danielroe** [comment]
This is now implemented in Nuxt 3 with the `public` directory. You can also add other directories with `nitro.publicAssets` and the `.output/public` folder is then the production public folder after build.
