### ISSUE TITLE
Issue with generating CSP policy meta tag for (static) SPAs

### ISSUE THREAD

**Issue by PedroD** [nuxt/nuxt#6592]
### Version

[v2.10.1](https://github.com/nuxt.js/releases/tag/v2.10.1)

### Reproduction link

[https://github.com/PedroD/nuxt-csp-test](https://github.com/PedroD/nuxt-csp-test)

### Steps to reproduce

The link presented is of a sample project created with Nuxt using `$ npx create-nuxt-app <project-name>`.

I made no changes to the source code, except for the `nuxt.config.js` file, where I added the `render:csp` property, and for the `package.json` I changed `nuxt` from 2.0.0 to 2.10.1.

In order to reproduce the error:

1. navigate to the project root folder in your terminal
2. run `npm run generate`
3. use `serve` to serve the `dist` folder (`npm i -g serve`, to install it) and then `serve dist/` to serve it)
4. open the page in the browser (usually served on `http://localhost:5000/` by default)

### What is expected ?

When you inspect the HTML, it is expected to see a meta tag in the `<head>` of the page containing the CSP policies defined, with hashes, and also all scripts and styles (incl.  inline) should have a hash referenced in their tags.

### What is actually happening?

No meta tag is created in `<head>`, and no hashes are being referenced in scripts and styles.

It is as if the `render:csp` property is not even set in `nuxt.config.js`.

### Additional Info

Here is the contents of the `nuxt.config.js` for this sample project:

```
const ALLOWED_HOSTS = ['*.google-analytics.com', '*.doubleclick.net', '*.googleusercontent.com']

export default {
  mode: 'spa',

  render: {
    csp: {
      reportOnly: false,
      addMeta: true,
      hashAlgorithm: 'sha256',
      unsafeInlineCompatiblity: true,
      policies: {
        'default-src': ["'self'", 'https:', ...ALLOWED_HOSTS],
        'script-src': ["'self'", "'strict-dynamic'", 'https:'],
        'style-src': ["'self'", "'strict-dynamic'", 'https:'],
        'frame-src': [],
        'object-src': ["'none'"],
        'base-uri': ["'self"]
      /* "report-uri": [
        "https://sentry.io/api/<project>/security/?sentry_key=<key>",
      ], */
      }
    }
  },

  /*
  ** Headers of the page
  */
  head: {
    title: process.env.npm_package_name || '',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: process.env.npm_package_description || '' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
    ]
  },
  /*
  ** Customize the progress-bar color
  */
  loading: { color: '#fff' },
  /*
  ** Global CSS
  */
  css: [
    'element-ui/lib/theme-chalk/index.css'
  ],
  /*
  ** Plugins to load before mounting the App
  */
  plugins: [
    '@/plugins/element-ui'
  ],
  /*
  ** Nuxt.js dev-modules
  */
  buildModules: [
    // Doc: https://github.com/nuxt-community/eslint-module
    '@nuxtjs/eslint-module'
  ],
  /*
  ** Nuxt.js modules
  */
  modules: [
    // Doc: https://axios.nuxtjs.org/usage
    '@nuxtjs/axios',
    '@nuxtjs/pwa'
  ],
  /*
  ** Axios module configuration
  ** See https://axios.nuxtjs.org/options
  */
  axios: {
  },
  /*
  ** Build configuration
  */
  build: {
    transpile: [/^element-ui/],
    /*
    ** You can extend webpack config here
    */
    extend (config, ctx) {
    }
  }
}
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9929">#c9929</a>)</em></sub></div>

**Comment by PedroD** [comment]
@manniL hello, can you confirm if this is a bug?

thanks!

**Comment by PedroD** [comment]
As of my current understanding, Nuxt **does not suuport** CSP for the `generate` goal.

**Comment by williamchong007** [comment]
Supporting generating CSP meta tags is very useful in generate mode though. What was the expected use case when this feature was added into server mode?

**Comment by malitta** [comment]
According to `@nuxt/vue-renderer/dist/vue-renderer.js`, CSP logic is included only in the `SSRRenderer` class, but not in `SPARenderer`.

**Comment by yoanntalagrand** [comment]
Can you try to set addMeta to false? It wasnt including my policies.

**Comment by monisnap-julien** [comment]
Any news on this topic ? It's still not working in generate mode...

**Comment by dominikbruechner** [comment]
I give this a small push, any news? We run into the same problem in our nuxtJs application

**Comment by PedroD** [comment]
Even on SSR mode this still forces me to use unsafe CSP options for CSS and scripts...

**Comment by TorbjornHoltmon** [comment]
Having issues with this too.
Trying to setup CSP with the new nuxt static generator. 
I do get a head meta tag, but it only contains "script-src" and nothing else. My settings are very similar to yours.

**Comment by sausin** [comment]
Really looking forward to getting support for this issue!

**Comment by josepjaume** [comment]
> Having issues with this too.
> Trying to setup CSP with the new nuxt static generator.
> I do get a head meta tag, but it only contains "script-src" and nothing else. My settings are very similar to yours.

Having the same issue on Nuxt 2.13.3 with the `static` target.

**Comment by koehn** [comment]
FYI, if you work around this issue like I have by setting the CSP header in your layout's `head()` method, you will *still* want to set the `csp` in `nuxt.config.js`, or you will end up generating unsafe `eval` statements because [this fix](https://github.com/nuxt/nuxt.js/pull/7306) will not work correctly.

**Comment by abernh** [comment]
@BenceSzalai thanks for the work. Unfortunate that you were not able to finalize it.
Is there someone in particular to get in contact with in order to determine if finalizing the PR would still be welcomed and has merge-potential?

**Comment by husseyd** [comment]
Any more love for this issue? Allowing inline scripts is far from idea. Using in SPA mode btw.

**Comment by schaeferCode** [comment]
For anyone that cares, I've cloned @BenceSzalai 's PR and am going to continue the good work. There are some decently large changes that need to be made, since the hash that's being generated is a little bit late in the chain of events. You'll see when I (hopefully) push a finished branch of my own.

**Comment by BenceSzalai** [comment]
Thanks! It was a long time ago, but as far as i can remember i was interested in the SPA mode, probably thus I was looking at the part that only handles the entry point html of an SPA. Never looked at parts that were supposed to generate multiple html files. I'd assume that may be substantially different to implement this for.

**Comment by sschaefer-rms** [comment]
@BenceSzalai Yes it will be substantially different, I believe. Your original code only produced a meta tag for the `200.html` file. Wouldn't the `index.html` technically be the "entry" point of the SPA? Or am I wrong to assume that?

**Comment by schaeferCode** [comment]
@BenceSzalai Yes it will be substantially different, I believe. Your original code only produced a meta tag for the `200.html` file. Wouldn't the `index.html` technically be the "entry" point of the SPA? Or am I wrong to assume that?

**Comment by BenceSzalai** [comment]
My code does not control the filenames. I think you can customize the entry point file name in `nuxt.config.js`. The [default](https://nuxtjs.org/docs/configuration-glossary/configuration-generate/#fallback) value is `200.html` for the entry point. Actually the filename is indifferent as we are taking about an SPA.

**Comment by schaeferCode** [comment]
After some time spent working on this problem, this is the best solution I can come up with for the time being. 

- Install the `csp-html-webpack-plugin` module
- add the following to your nuxt.config.js file:
```
export.default: {
  build: {
    plugins: [
      new HtmlWebpackPlugin(),
      new CspHtmlWebpackPlugin({
        'style-src': [`'self'`, `'unsafe-inline'`],
        'script-src': [`'self'`],
      }, {
        nonceEnabled: {
          'script-src': false,
          'style-src': false
        }
      })
    ]
  }
}
```
- yarn build && yarn start
- open browser to correct port and see the errors in your console. You'll likely see a couple of scripts that have been blocked (maybe 2), add those to your csp properly. Same with other random style issues. 

I do intend to talk some other devs who are more knowledgeable with webpack to handle this more completely. For now, I can see a way to get around including `unsafe-inline` for style policy. Hopefully in the future, this can be built into nuxt. I really don't think it would be difficult for someone who really understands the build process.

**Comment by shreyasshinde-exa** [comment]
About `unsafe-inline` for styles. Is there a workaround for that or a plan to support hashes for styles too same as scripts in SSR mode? Most of the discussion here seems about SPA mode but there is this issue with SSR as well.

**Comment by kleozzy** [comment]
any update on this?

**Comment by madhusnair340b** [comment]
any update on this pr?

**Comment by BenceSzalai** [comment]
I don't use nuxt.js any more and cannot spare time to update it. Probably files has changed a since this PR, so it is likely need to be reworked, also apparently there's lot of need for non-SPA files to be covered as well, which is a separate thing and need to be looked at independently.

If anyone has a nice project for me which includes nuxt.js and needs proper CSP I'd be happy to go through with this. I always try to contribute to things I use for projects, but sadly otherwise I cannot afford.

**Comment by ybabenkoJapp** [comment]
Hi to everyone! I use nuxt.js v2.15.8 with headless CMS Storyblok (not Storybook). I generate a static site and deploy it on Netlify. Some of the SEO staff told me to add security lines to the response headers and SCP was one of them. I've read a lot of resources and had a lot of trouble with it. Did anybody face such an issue? Or give me valuable tips. Thanks.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by sausin** [comment]
It seems like there are still [challenges](https://stackoverflow.com/questions/74862310/how-configure-csp-in-nuxt-3) with CSP in Nuxt 3. If the relevant tags could please be updated.

**Comment by danielroe** [comment]
We can track Nuxt 3 support in https://github.com/nuxt/nuxt/issues/11793.

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
