### ISSUE TITLE
Setup a module programmatically from the CLI

### ISSUE THREAD

**Issue by arnaudlewis** [nuxt/nuxt#6631]
### What problem does this feature solve?

I'm currently building a tool that will bootstrap a nuxt project from our CLI.
Our CLI will run `create-nuxt-app` to bootstrap the app but i'd like to setup a module right away in the newly generated project without having to manually edit the `nuxt.config.js` file.

### What does the proposed changes look like?

It's an ongoing discussion with @Atinux right now, maybe something on `create-nuxt-app` that would offer a way to do that.
Something like:
`npx create-nuxt-app <my_project> --useModule [ "myModuleName", { myConf: '' }]`
or
 `npx create-nuxt-app <my_project> --useModule ./myModuleConfig.js`

Or maybe we could consider having some kind of way to setup the module interactively.
It would be done on the module level and executed by the CLI.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9957">#c9957</a>)</em></sub></div>

**Comment by danielroe** [comment]
We are planning to implement this within `nuxi`. See https://github.com/nuxt/nuxt/issues/13552 and https://github.com/nuxt/nuxt/issues/13550.
