### ISSUE TITLE
Trackback for errors during SSR shows "Missing stack frames"

### ISSUE THREAD

**Issue by philipmountifield** [nuxt/nuxt#6640]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[https://codesandbox.io/s/ssr-error-uvu26](https://codesandbox.io/s/ssr-error-uvu26)

### Steps to reproduce

Just open the reproduction link...

OR

1. Cause an error in a component which means the SSR of a page will fail (see example)
2. Navigate to the dev server URL fresh (i.e. not open already)
3. You see the following error page, but the stack trace says "Missing stack frames" and some of the file names and line numbers are not showing correctly either
4. Looking at the terminal too, the information emitted does not give any reference to a line number either

![SSR Fail 2.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/26d5b370-fbc1-11e9-9dff-dfe3a12c4d7d.png)

![Terminal.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/65e81800-fbc1-11e9-9dff-dfe3a12c4d7d.png)

### What is expected ?

Accurate tracebacks with correct file names, line numbers and file contents.

### What is actually happening?

Missing tracebacks, confusing file names and line numbers.

### Additional comments?

I have experimented with various settings for build config.devtool and these do appear to affect what is shown in the traceback, but I couldn't find a value that actually made it work correctly.

If you happen to trigger the error while you have a live frontend open (of force it by setting mode: 'spa'), the browser dev tools are able to find the correct lines in the debugger.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9965">#c9965</a>)</em></sub></div>

**Comment by philipmountifield** [comment]
Still awaiting response.

**Comment by mkstix6** [comment]
I'm also interested in this. Line numbers for these errors would be mightily helpful.

**Comment by philipmountifield** [comment]
Still awaiting response.

**Comment by philipmountifield** [comment]
Given the bug report is provided with full details, and a clean reproduction link, it's quite disappointing that there has been absolutely no comment from the developers whatsoever.

**Comment by absalan** [comment]
Any update on this?

**Comment by jonalxh** [comment]
Very necessary, I'm very lost searching in all my files after a migration from Pure Vue to Nuxt.

**Comment by mkstix6** [comment]
Yes, just yesterday I guided someone new to the project through an error in `asyncData()`. They are an experienced developer but new to Nuxt. 

It was a simple enough error, an axios XHR request had 404’d, but they only had:

> NuxtServerError
> Request failed with status code 404. 
> Missing stack frames

…and a trace that only references files and line numbers from Nuxt internal processes. 

![9C0EB165-8115-484D-BCCF-100B631A5C4B](https://user-images.githubusercontent.com/1573136/83938220-841dcf80-a7ca-11ea-802b-bb96a1059402.jpeg)

Without a file and line number next to “Request failed with status code 404” they were understandably lost and frustrated.

_I love using Nuxt and what it gives me, thank you team, but it’s hard to defend it when developers run into this so early in their experience._ 

Using Nuxt v2.10.2

**Comment by pi0** [comment]
Hi all. I can understand how much frustration it sometimes brings when stack traces are not available. The first issue will be improved by #7463. @mkstix6 Axios HTTP request traces are unfortunately not traceable because of how it throws the error. I will try to find a solution for it meanwhile any contribution to improvement is more than welcome :)

**Comment by MacroMan** [comment]
Mid 2022 and I'm still experiencing this :shrug:

**Comment by Ghustavh97** [comment]
Trying to migrate one of our apps from `spa` to `ssr` and the errors are an absolute nightmare. You have to guess were something went wrong and if you don't know then tough luck. If it were not for the SEO benefits and fast loading speeds of `ssr` we would have gladly stuck with using `spa` mode.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
