### ISSUE TITLE
window.__nuxt__ is too huge, How can I move it to a js file?

### ISSUE THREAD

**Issue by bysir-zl** [nuxt/nuxt#6641]
### What problem does this feature solve?

window.__nuxt__ block is tooo huge, It's bad for SEO.

### What does the proposed changes look like?

put the "window.__nuxt__" to a js file.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9966">#c9966</a>)</em></sub></div>

**Comment by aldarund** [comment]
How its bad for seo? Size of nuxt block is totally depends on how much data you put there.

**Comment by Junwebnew** [comment]
I have the same question. I hope to answer it

**Comment by bysir-zl** [comment]
> How its bad for seo? Size of nuxt block is totally depends on how much data you put there.

My site's data and styles are all dynamically generated by service API. So that' it.  

Please see the website below : 

view-source:http://bysir.e.cn.vc/6

**Comment by bysir-zl** [comment]
If `window.__nuxt__` can be reduced, is can also alleviate my problem. As it says: https://github.com/nuxt/nuxt.js/issues/6609.

**Comment by rdiff** [comment]
I have same problem with SEO (dublicate content)

**Comment by manniL** [comment]
> I have same problem with SEO (dublicate content)

Duplicated content doesn't take your `script` resources into account.

> If `window.__nuxt__` can be reduced, is can also alleviate my problem. As it says: #6609.

It can be reduced by reducing the content that is serialized (passed) between server and client.

Extracting `window.__NUXT__` into a JS file might be a feature for `yarn generate` with full static mode in the future.

**Comment by pi0** [comment]
> Extracting window.__NUXT__ into a JS file might be a feature for yarn generate with full static mode in the future.

BTW it only covers generate not normal SSR

**Comment by gengchen528** [comment]
> > I have same problem with SEO (dublicate content)
> 
> Duplicated content doesn't take your `script` resources into account.
> 
> > If `window.__nuxt__` can be reduced, is can also alleviate my problem. As it says: #6609.
> 
> It can be reduced by reducing the content that is serialized (passed) between server and client.
> 
> Extracting `window.__NUXT__` into a JS file might be a feature for `yarn generate` with full static mode in the future.

when i use `nuxt start` can I move it to a js file. It too larger for me .And  I do not want show data structure in the source code. Is there any way to solve it？

**Comment by hecktarzuli** [comment]
Also, too huge in what way?  Assuming you are using standard HTTP compression this should compress to be a very small difference over the wire.

**Comment by danielroe** [comment]
This is possible with payload extraction in Nuxt 3.
