### ISSUE TITLE
Possible memory leak with nuxt-link and/or router-link

### ISSUE THREAD

**Issue by slidenerd** [nuxt/nuxt#6669]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[https://codesandbox.io/s/github/slidenerd/nuxt_child_slow_bug_demo](https://codesandbox.io/s/github/slidenerd/nuxt_child_slow_bug_demo)

### Steps to reproduce

Run the codesandbox demo
Click on an item in the list on the left pane
try scrolling down immediately, the browser has frozen
The url does not change immediately
try clicking multiple items and scroll up and down and you ll observe the LAG
![nuxt_bug.gif](https://cmty.s3.eu-west-1.amazonaws.com/71995937/2a4d6a60-022a-11ea-9ce2-67cf9edfbeef.gif)

### What is expected ?

The item gets selected immediately. The scroll does not lag, On selecting the child view the url changes rapidly. The app should not FREEZE.

### What is actually happening?

In the build version, the app freezes depending on how many items you have, on the dev version, it crashes the browser completely.

### Additional comments?

I am trying to build a list detail view with a very simple setup
I have a list on the left pane with 5000 items. Feel free to change the numbers up and down
Clicking on an item on the left side, changes the content of the nuxt-child on the right as per the nested routes demo by official nuxt repo
I am using a key on the child route and no-prefetch and it still lags like anything
The dev version is unrunnable , the build version freezes quite a bit
Some suggestions on how to fix this would be super appreciated

**Comment by slidenerd** [comment]
If I am not mistaken, I would need to use the vue-webpack setup via vue-cli to set the same example up, but that would be SPA would it not while this is SSR

**Comment by aldarund** [comment]
It doesnt matter about SSR, since your problem happens on client. And you dont really need even vue cli, you can use cdn version  or via vue-cli, it doesnt really matter.
Also, does it happen in production build or only in dev?

**Comment by slidenerd** [comment]
[Here is the plain Vue version](https://codesandbox.io/s/github/slidenerd/vue-list-detail-nested-route-test), it is also slow but the nuxt version literally crashes the browser, I have kept the same number of items 5000

**Comment by manniL** [comment]
The difference is definitely noticeable, yes.

**Comment by Alex1990** [comment]
I have a page which has many `<nuxt-link>`s,. The below is vue-tools performance data when I navigate  the router.

![image](https://user-images.githubusercontent.com/3141679/71544664-6a779100-29bd-11ea-9255-b120b80235c5.png)

And, if these `<nuxt-link>`s are removed from the page, the JS evaluation time will reduce distinctly. By the way, I use ssr mode.

**Comment by mstaack** [comment]
experienced the same as @Alex1990 ... is this being investigated?

**Comment by tmazza** [comment]
Em seg, 6 de jan de 2020 12:25, Max <notifications@github.com> escreveu:

**Comment by manniL** [comment]
First thing that comes to my mind is the intersection observer registered for each link that could influence the perf. But that's just an educated guess at the moment.

**Comment by jatarga** [comment]
This is a problem for me for a few months. Any workaround except switching to the good old <a>?

**Comment by tvld** [comment]
Here as well. In my case app becomes slower the longer you navigate. First notice after about twenty or so clicks on links.

**Comment by jatarga** [comment]
> First thing that comes to my mind is the intersection observer registered for each link that could influence the perf. But that's just an educated guess at the moment.

@manniL 

Its not because of IntersectionObserver, because both `nuxt-link` and `router-link` causes same problem in a nuxt application. (I created the same sandbox with router-link https://codesandbox.io/s/authdemo-l1cs4)

**Comment by tvld** [comment]
@jatarga maybe asking for the obvious, but with ``<a..>`` you don't experience performance regression?

**Comment by jatarga** [comment]
> @jatarga maybe asking for the obvious, but with `<a..>` you don't experience performance regression?

Obviously we are. Using `<a>` is even meaningless because we are sacrificing SPA.

**Comment by tvld** [comment]
It seems that for me freezing after some clicking, only happens with links that contain route.params ... The regular links don't build up delays... Still investigating...

**Comment by rainerCH** [comment]
hi
i have the same problems with ~100 links, with or without route.params. thanks for your effort :)

**Comment by tvld** [comment]
I think this is one of the most important show-stopping bugs in nuxt. I noticed that with each click on a link, the memory consumption shoots up with between 4-12MB on both chrome and FF. So, it's not the number of links but the memory it is building up. Over about 1GB junk, the browser crashes. It happens on each site, as far as I can tell...

@slidenerd could you change title of this issue. I get the idea that nuxt core devs don't know yet they have a "priority-one" bug on their hands that breaks deployment ...

**Comment by pimlie** [comment]
Have tested the linked codesandbox, can @slidenerd or anyone else please confirm the following findings?

1. The issue does not occur when using `<button @click="$router.push(...)">{{ i }}</button>` instead of router-link or derivative
2. The issue does not occur when using nuxt instead of nuxt-child. Eg move pages/index.vue to layouts/default.vue, rename nuxt-child to nuxt, add an empty index.vue sfc, rename the child routes from index/news to test/news to make sure its a top level route

Please note: it looks like Chrome only needs the first change to become mostly workable (there seems to be still a very slight delay between clicking the button and page load). Firefox rly needs both changes to become workable

**Comment by tvld** [comment]
@pimlie   I just tried __almost empty__ page, just with a few ``<button @click="$router.push(...)">{{ i }}</button>``. The memory build up after one click __going back and forth to same two pages__ is each time about 6MB. After about 20 clicks,I am already on 263MB  it really grows more quickly and gets really slow to load 8 seconds.. 

Garbage collection after some minutes brings it down to 261 MB, so that makes no difference. Again, with all same components.

![Screenshot from 2020-01-23 13-51-38](https://user-images.githubusercontent.com/986182/72982420-b3b5d780-3de7-11ea-90cb-52566392b250.png)

**Comment by pimlie** [comment]
Hmn, then its probably related to this issue: https://github.com/vuejs/vue-router/issues/3105

**Comment by tvld** [comment]
For comparison, tried same with vue __without nuxt and vue-router__:

![Screenshot from 2020-01-23 13-59-40](https://user-images.githubusercontent.com/986182/72982851-b06f1b80-3de8-11ea-834d-2a49bab6b983.png)

**Comment by Frozire** [comment]
I am experiencing the same with just ten links - could we change the title, so it isn't assumed to be an edge case?

**Comment by tvld** [comment]
@Frozire hence my suggestion to change the title. The "1000+" does not cover it. "10+" would have been better ;-)

**Comment by pimlie** [comment]
Title updated, does anyone has time to investigate the issue more deeply?
To check if its related to the vue-app you can create an `app` folder in the src root of any Nuxt project and eject any of the vue-app templates into that folder to override the default imports from node-modules/@nuxt/vue-app/template (https://github.com/nuxt/nuxt.js/tree/dev/packages/vue-app/template)

**Comment by Chrisimir** [comment]
Any update or is it confirmed to be a issue with any of the dependencies mentioned in this thread?

Also experiencing this issue and need urgent workaround.

![image](https://user-images.githubusercontent.com/16140625/75453335-131d7f00-5974-11ea-8c9e-3e7250555c37.png)

Performance test after navigating to 2 pages in my app.
Using 2.11.0 SSR

**Comment by tvld** [comment]
I am still having this breaking issue as well. I disabled SEO on i18n and that helped a bit, but still crashing out of memory after some time

**Comment by Chrisimir** [comment]
I guess it is an implementation issue and not a framework bug since it would be a major issue for everyone. 
Now I'm stuck with a giant Nuxt app with `<a>` tags :expressionless:

Any idea on how to troubleshoot this? @Atinux @pi0 @manniL

**Comment by tvld** [comment]
After several weeks into it, I am started to be convinced it _is a framework bug_, even though the implementation _setup might trigger_ it. 

Right now my biggest indication is that my ``npm run dev`` crashes every 10 minutes or so due to memory overload. If I open multiple browser tabs, the memory overload and resulting crash comes much more quickly. Do you see the same issue with multiple browser tabs to same app?

**Comment by pimlie** [comment]
Please run `yarn upgrade` to make sure vue-meta v2.3.3 is installed. Recently a memory leak was fixed in vue-meta, maybe thats related to this issue.

**Comment by tvld** [comment]
Just upgraded all packages ``npm update`` and again after 10 minutes the dev environment crashes with memory overload.

**Comment by Chrisimir** [comment]
> Just upgraded all packages `npm update` and again after 10 minutes the dev environment crashes with memory overload.

Have you seen if it updated vue-meta to v2.3.3 ? I tried an npm update and it didn't get the new version. I will try to force the version later and update this thread with my results.

**Comment by tvld** [comment]
@Chrisimir  good one! ``npm list | grep vue-meta`` gave me :
```bash
│ │ │ ├─┬ vue-meta@2.3.1
│ │ │ ├── vue-meta@2.3.1 deduped
```
So it indeed did not upgrade... So I will keep posted how you achieve ))

**Comment by Chrisimir** [comment]
It was vue-meta that was to blame in my case :tada:
After updating to 2.3.3, no crash and fast routing.

How I did it:
- Deleted node_modules folder
- Deleted package-lock.json
- `npm i`

I'm sure there is a better way of forcing an update, but this worked for me, my vue-meta would not update until I deleted the files. Hope this works for you @tvld !

**Comment by rainerCH** [comment]
Works in my case with vue-meta 2.3.3 again :) thanks!

**Comment by tvld** [comment]
Did not want to cheer too soon, but it seems it's solved for me as well, so far ``npm run dev`` did not crash again for me :tada:

**Comment by Frozire** [comment]
I've been running for a couple of hours too now - no crash.

**Comment by tvld** [comment]
Bummer... I got the same issue, crash on out of memory. But it's taking longer so at least some progress.... :thinking:

**Comment by Chrisimir** [comment]
@tvld Do you still experience it only has issues when you use `route.params` or does the memory consumption rise with every type of link? 

Have you played around with [link prefetching](https://nuxtjs.org/api/configuration-router#prefetchlinks) to see if there is an improvement?

**Comment by tvld** [comment]
@Chrisimir  I've just spent half an hour refreshing pages on our production (www.bligson.com), switching between pages. Before vue-meta 2.3.3 the memory size would grow with 5MB going back and forth between two pages. Now it stays about the same, if I let garbage collection do its work. So that's good.

What I still have though is that de development environment crashes with out of memory. I start to think it is is related to vue-i18n not cleaning up after each reloading of a language file but that's just a hunch  so far. If so, than the issues is not related to this one ...

**Comment by slidenerd** [comment]
Even with "nuxt": "^2.12.2" npm run build && npm run start somewhat runs decently (still slower than the plain vue version) but npm run dev completely crashes within seconds of trying to scroll up and down and open a few links

**Comment by tvld** [comment]
I upgraded my RAM from 12GB to 24GB, and since then I did not have this crash...yet at least...   could this be related?

**Comment by AregGhazaryan** [comment]
@tvld i checked the memory consumption yesterday, it was handling promises non stop in one file. I think its getting stuck in some sort of loop.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
