### ISSUE TITLE
repeat showing the default title when loading new pages

### ISSUE THREAD

**Issue by jhd4tmr** [nuxt/nuxt#6681]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[https://steamstats.cn](https://steamstats.cn)

### Steps to reproduce

Click the nav bar except 'home', you will always see the default title showed before the new page title. It seems the logic is to 'load the default title first, then replace it to the new page title' not to 'figure the new page title by the title template then replace the old title to it'.

### What is expected ?

The new page title should figured by the title template then replace the old title smoothly.

### What is actually happening?

It will cause a blink of the default title.

**Comment by manniL** [comment]
Could you provide a minimal reproduction?

**Comment by jhd4tmr** [comment]
https://52bin.sse.codesandbox.io/fr/
@manniL I find out the reason.
```
head () {
    return {
      meta: [
        { hid: 'og:locale', property: 'og:locale', content: this.$i18n.locale === 'en' ? 'en' : 'fr' },
      ]
    }
  }
```
If i put the code in the `layout.vue`, when the value of ` this.$i18n.locale` changes, the new page will show the default title in the` nuxt.config.js` first, then it will change to the new page title.
You can click the 'Version Anglaise' button to test. But it's not easy to show the case. You should type the button quick and rhythmically cause the speed of page load is too fast.

If i put the other variables in the head of the layout.vues, it will cause the same results. I hope you can have a good solution to make it available to have dynamic head in the layouts.

**Comment by manniL** [comment]
I'll take a look. You could give [nuxt-i18n](https://github.com/nuxt-community/nuxt-i18n/) a shot in the meantime.

**Comment by jhd4tmr** [comment]
@manniL
I will, i think it's not the problem of i18n, it's the variable in the head of layouts that matters.

**Comment by manniL** [comment]
Then this might be a `vue-meta` issue. :thinking: 

cc @pimlie

**Comment by harlan-zw** [comment]
This likely won't be fixed in Nuxt 2. You can track here just in case we decide to fix it: https://github.com/nuxt/nuxt/issues/10626
