### ISSUE TITLE
Can't transpile module which using .mjs extension

### ISSUE THREAD

**Issue by padinko** [nuxt/nuxt#6688]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[https://codesandbox.io/s/nuxt-mjs-transpile-problem-mo9to](https://codesandbox.io/s/nuxt-mjs-transpile-problem-mo9to)

### Steps to reproduce

If you import package, which is using `.mjs` extension, and add transpile to this module, imported code is not transpiled

for example:
1. `npm i rope-sequence`
1. import it somewhere `import 'rope-sequence'`
1. add transpile this module to nuxt.config.js `transpile: [({ isLegacy }) => isLegacy && "rope-sequence"]`
1. open in IE.. there is error in console

### What is expected ?

transpiled module - no `const`/`let` and arrow functions

### What is actually happening?

module has `const` and arrow functions

### Additional comments?

now I can update regex for babel-loader to `/\.m?jsx?$/i` and everythink works good in IE
reproduction link with workaround https://codesandbox.io/s/nuxt-mjs-transpile-problem-workaround-z1tme
see `nuxt.config.js -> build -> extend`

**Comment by pencilcheck** [comment]
Thanks for the use of transpile, this also solves @trpc/client and @trpc/server not working since they also uses mjs but I don't need to add the workaround which is nice

**Comment by rchl** [comment]
There was also a follow-up PR at https://github.com/nuxt/nuxt/pull/10340 so I would say that this can be closed.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
