### ISSUE TITLE
Add client option to not replace current page component with <NuxtError> component when there's an uncaught error

### ISSUE THREAD

**Issue by chriscalo** [nuxt/nuxt#6699]
### What problem does this feature solve?

Bugs happen, and despite our best efforts, they sometimes make it to production.

When there's a client-side error in a Nuxt app, the default behavior is to replace the current page component with the `<NuxtError>` component:

![Mounted &lt;NuxtError&gt; component](https://cmty.s3.eu-west-1.amazonaws.com/71995937/db991fc0-07b2-11ea-9e77-a7bdc4f8b775.png)

Unfortunately, this clears everything a user was doing and may result in lost user input, violating a fundamental principle of good interface design.

Example: Imagine a user filling out a long form, hitting **Submit**, and then seeing this error screen with no way of salvaging the lost work entered into the form. A most frustrating experience. Yes, the error is probably my fault as the application author, but this default behavior of clearing pages when an error happens actually makes things worse, not better.

What would enable me to deliver a better user experience is to either:
1. Disable the behavior of replacing the current page component with the `<NuxtError>` component, or
2. Allow me to override and control exactly how errors are displayed (for example, I would probably keep the current page in-tact and display the error as a non-modal overlay message)

### What does the proposed changes look like?

It's not clear to me where such an option belongs, but a few ideas in `nuxt.config.js`.

Does this belong with `router` options?

``` js
export default {
  router: {
    replacePageComponentOnError: false,
  },
};
```

Or in a separate `errors` option?

``` js
export default {
  errors: {
    replacePageComponent: false,
  },
};
```

Or, should it mirror the pattern for a custom loading component from [this sandbox][custom-loading-sandbox] found on [this example page][custom-loading-example]?

``` js
export default {
  error: "~/components/error.vue",
}
```

The idea would be to similarly append the custom error component to the page instead of replacing the page component. The `~/components/error.vue` could then have full control of how it is displayed regardless of the page it's on, with some means of dismissing the error:

``` vue
<template>
  <dialog class="ErrorDialog" :open="Boolean(error)">
    <p>{{ error.message }}</p>
    <button @click="$emit('error:dismiss')">Close</button>
  </dialog>
</template>

<script>
  export default {
    props: {
      error: Object,
    },
  };
</script>

<style scoped>
  .ErrorDialog {
    display: fixed;
    top: 64px;
    left: 64px;
  }
</style>
```

[custom-loading-sandbox]: https://codesandbox.io/s/github/nuxt/nuxt.js/tree/dev/examples/custom-loading?from-embed
[custom-loading-example]: https://nuxtjs.org/examples/custom-loading

**Comment by NVaissaud** [comment]
Indeed it would be awesome to make NuxtError component optional.

I would like to pop errors from backend (either it is a 500 / 401 / 422 ) to my frontend using Toast or Swal. I tried to implement it in my axios plugins using interceptor. My toast message do show up, but behind it i got the NuxtError component.

[Frontend when Backend got an error](https://monosnap.com/file/TnCtIgW2S6mVvK1XC6wst3be0Rcvwo)

```
export default function({ $axios, redirect, app }) {
  $axios.defaults.baseURL = process.env.API_BASE_URL
  $axios.setHeader('Content-Type', 'application/json')

  $axios.onRequest((config) => {
    console.log('Making request to ' + config.url)
  })

  $axios.onResponse((response) => {
    console.log('onResponse', response)
  })

  $axios.onResponseError((response) => {
    console.log('onResponseError', response)
  })


  $axios.onError((error) => {
    console.log('onError', error)
    if (error.response.status === 500) {
      console.log('ERROR 500', error.response.data.message)
      app.$toast.error(error.response.data.message)
    }

    if (error.response.status === 401) {
      console.log('ERROR 401', error.response.data)
      app.$toast.error(error.response.data.error)
    }

    if (error.response.status === 422) {
      console.log('ERROR 422', error.response.data.errors)
      app.$toast.error(error.response.data.errors)
    }
  })
}
```

Using axios promise catch avoid showing NuxtError component but i would like to implement it into my axios interceptor.

Any help ? :)

Thank you

**Comment by shredmaster** [comment]
agree with op, this is not the desired behavior at all. Has anyone figured out how to disable this error page?

**Comment by maratumba** [comment]
This is especially bothersome during development. Once you get redirected, you can't inspect the component data, props, etc.

**Comment by danielroe** [comment]
This is now implemented in Nuxt 3. You can use `<NuxtErrorBoundary>` to define specifically the fallback content when there's an error. And errors that aren't thrown with `fatal: true` will not invoke the error page.

**Comment by chriscalo** [comment]
Great news, thanks so much for the fix!
