### ISSUE TITLE
Nuxt generate --modern + `for await of` usage doesn't work in Microsoft Edge

### ISSUE THREAD

**Issue by achaphiv** [nuxt/nuxt#6701]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[https://github.com/achaphiv/nuxt-issue-edge-for-await-of](https://github.com/achaphiv/nuxt-issue-edge-for-await-of)

### Steps to reproduce

I used `yarn create nuxt-app` and added this code:

```javascript
export default {
  data() {
    return {
      values: []
    };
  },
  async created() {
    for await (const value of this.asyncIterable()) {
      this.values.push(value);
    }
  },
  methods: {
    async *asyncIterable() {
      for (let i = 0; i < 10; i++) {
        yield Promise.resolve(i);
      }
    }
  }
};
```

I built with/without modern flag and deployed to netlify:

`nuxt generate --modern` = https://competent-lumiere.netlify.com/
`nuxt generate` = https://deploy-preview-1--competent-lumiere.netlify.com/

Go to both sites in Microsoft Edge.

The first has a console error message:

```
Object is not async iterable
```

The second works fine in Microsoft Edge.

All other browsers (firefox, chrome, safari) work fine.

### What is expected ?

I expected Edge to fallback to the non-modern build.

I also don't want to have to manually configure babel.

### What is actually happening?

I'm guessing this is some kind of babel misconfiguration. Looks like a plugin is missing?

**Comment by pimlie** [comment]
This is probably because the plugin [`babel-plugin-proposal-async-generator-functions`](https://babeljs.io/docs/en/babel-plugin-proposal-async-generator-functions#installation`) is missing which is required to support for await of.

You should be able to manually add this in your nuxt.config trhough the option key [`build.babel.plugins`](https://nuxtjs.org/api/configuration-build/#babel)

**Comment by achaphiv** [comment]
Still doesn't work.

I could be adding it wrong:

```
    babel: {
      plugins: ['@babel/plugin-proposal-async-generator-functions']
    },
```

https://github.com/achaphiv/nuxt-issue-edge-for-await-of/pull/2

https://deploy-preview-2--competent-lumiere.netlify.com/

**Comment by achaphiv** [comment]
Still broken even when I switched to `nuxt-edge`.

https://github.com/achaphiv/nuxt-issue-edge-for-await-of/pull/4

https://deploy-preview-4--competent-lumiere.netlify.com/

**Comment by TheNoim** [comment]
Holy f**k, I can not find a solution for this simple problem. This just s***s. Why is edge so buggy and annoying to work with? I simply want to sue async generators with for await. But edge is like: No.

**Comment by npetkov** [comment]
@TheNoim As far as I can see, "legacy" Edge 18 does not support `Symbol.asyncIterator` at all. The solution for me was to use `@babel/runtime-corejs3` as described [here](https://babeljs.io/docs/en/babel-plugin-transform-runtime#corejs). I've used the following config (I'm using webpack, but this is babel configuration and it should be possible to pass it through in other environments as well):

``` javascript

use: {
    loader: 'babel-loader',
    options: {
        presets: ['@babel/preset-env'],
        plugins: [
            [
                '@babel/plugin-transform-runtime',
                {
                    "corejs": { version: 3, proposals: true }
                }
            ],
            '@babel/plugin-proposal-class-properties',
            '@babel/plugin-proposal-optional-chaining'
        ]
    }
}
```

Don't forget to add `core-js` and `@babel/runtime-corejs3` to your runtime dependencies.

A hint from the docs: 

> By default, @babel/plugin-transform-runtime doesn't polyfill proposals. If you are using corejs: 3, you can opt into this by enabling using the proposals: true option.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
