### ISSUE TITLE
transition(from, to) should be called after asyncData()

### ISSUE THREAD

**Issue by piotrjoniec** [nuxt/nuxt#6703]
### What problem does this feature solve?

When trying to build an online store demo with Nuxt.js, I've realized there are limitations when trying to define custom page transitions for dynamically matched routes.

What I mean by dynamically matched routes, is there is a _.vue page in my project, which sends a request to the API with the current route path. The API returns whether this path is a category page, a product page, or a 404. After that the appropriate component and its data is loaded, to display the page.

Now what if I want to have different transitions for the product and the category page? Because transition(from,to) is called before asyncData(), it's impossible for me to tell whether the TO route is a product page or a category page. It's still possible to achieve different transitions here, but it'd require ugly hacks like defining one transition for _.vue, and overwriting its CSS code after the page type has been detected.

If transition(from,to) gets called asyncData(), which shouldn't be a problem since the transition starts only after asyncData has been loaded. Then it'd be trivial to define those custom transitions. Or maybe there's something that I don't know which forces transition(from,to) to be called before asyncData. Either way, I thought this is something fairly easy to solve which could improve Nuxt.js

**Comment by pimlie** [comment]
You could probably resolve this by using a middleware instead, those are run before the transition is called. You then need to use the context to pass data from middleware to your component instance (ie asyncData). Eg this way you can also dynamically switch layouts.
