### ISSUE TITLE
Nuxt UI

### ISSUE THREAD

**Issue by nice9uy** [nuxt/nuxt#6707]
### What problem does this feature solve?

Hi...

Nuxt is very awsome vue framework that very easy to learn.
However, sometimes I have difficulty in setting modules that are quite complicated.
Can nuxt be made like vue ui?

why vue ui? because it is very easy to install modules and without configuration because it is automatic in the installation process, so that new programmers like me can be easy to use and easy to understand how this great nuxt works.

Many thanks a lot

### What does the proposed changes look like?

vue ui

**Comment by madebyfabian** [comment]
I see this is a 4 year old issue, nuxt has completely changed since then. It's super easy to install modules. I guess we can close this?

**Comment by danielroe** [comment]
Indeed we can close this. There's a new Nuxt DevTools coming ... very ... soon as well that will include some interesting features along these lines 👀

**Comment by madebyfabian** [comment]
> Indeed we can close this. There's a new Nuxt DevTools coming ... very ... soon as well that will include some interesting features along these lines 👀 

Now I'm hyped!
