### ISSUE TITLE
Allow helper files inside store without converting them to vuex modules

### ISSUE THREAD

**Issue by yazfield** [nuxt/nuxt#6710]
### What problem does this feature solve?

We have a lot of helper functions & type definitions inside our store modules, in an attempt to refactor things we wanted to have some `types.ts` and `helpers.ts` files inside vuex module folders. 

The folder structure we want looks like the image attached:
![store-folder-structure.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/5a09b640-0b95-11ea-8d5d-47d505b0c7c1.png)

The problem we faced is that nuxt builder considers the files `helpers.ts` and `types.ts` as vuex modules and loads them.
It would be nice to have a way to tell the builder to ignore some files.

### What does the proposed changes look like?

1. A simple solution would be introducing a new convention for naming files inside the store. Prefixing the filename with an underscore '_helpers.ts' and updating the resolveStore function with: 
    ```
    resolveStore ({ templateVars, templateFiles }) {
            // ... irrelevent  code

            templateVars.storeModules = (await this.resolveRelative(this.options.dir.store))
              .filter({src: p} => !p.split('/')[p.length -1].startsWith('_'))
              // ...  irrelevent  code
        } 
```

2. Another solution could be updating  the vue-app `store.js` template and check if the module exports a state object, and if missing the module will be ignored.

I'm willing to contribute and implement this feature if you find it interesting. I'm probably missing some things and will appreciate you pointing them out.

**Comment by pimlie** [comment]
You should already be able to do this by using the ignore properties: https://nuxtjs.org/api/configuration-ignore#the-ignore-property. Eg by default files starting with `-` are ignored

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
