### ISSUE TITLE
Add the ability to create a component outside the layout

### ISSUE THREAD

**Issue by RDMStreet** [nuxt/nuxt#6770]
### What problem does this feature solve?

For example, I would like to create a notifications component that would be displayed on any page. The declaration of this component in each layout is not suitable for me, since when switching between different layouts, it will be recreated and notifications that are currently open will be recreated.

### What does the proposed changes look like?

In an ideal situation, I would like to be able to customize the root component.

**Comment by Soviut** [comment]
First, do you need to switch layouts? Usually you'd only have one layout defining the page header and footer, which is where the notifications component could live. If you need certain pages to have a sidebar, you can created nested templates for your routes.

Second, if your notifications component relied on the Vuex store, it wouldn't matter if they got recreated. It would just listen to the state in the store and render itself accordingly (no `mounted()` hooks). Changes to the state of notifications would just be mutations on the store.

**Comment by RDMStreet** [comment]
> First, do you need to switch layouts? Usually you'd only have one layout defining the page header and footer, which is where the notifications component could live. If you need certain pages to have a sidebar, you can created nested templates for your routes.
> 
> Second, if your notifications component relied on the Vuex store, it wouldn't matter if they got recreated. It would just listen to the state in the store and render itself accordingly (no `mounted()` hooks). Changes to the state of notifications would just be mutations on the store.

Yes, I have several layouts. I can use nested routes, but its breakes layout concept. I couldn't use notifications in each layout, because I have notification animation, wich can breakes on layout change.

**Comment by Soviut** [comment]
Do you have a separate header and footer in each one of your layouts? Usually, a layout is a master template which acts as a parent to all the pages. The pages are usually the part that's different.

Some screenshots of how your different layouts look/behave would probably clarify a few things.

**Comment by RDMStreet** [comment]
> Do you have a separate header and footer in each one of your layouts? Usually, a layout is a master template which acts as a parent to all the pages. The pages are usually the part that's different.
> 
> Some screenshots of how your different layouts look/behave would probably clarify a few things.

I have at least 3 completely different layouts with different headers and footers.  The only common part is the notification component.

**Comment by wildan2711** [comment]
Hi, did you find any solution for this? I also need create a global component in the root instance, to be applied to all layouts, e.g: a global toaster.

I think this is related to #2603 which has no solution to this day.

**Comment by oziged** [comment]
> Hi, did you find any solution for this? I also need to create a global component in the root instance, to be applied to all layouts, e.g: a global toaster.
> 
> I think this is related to #2603 which has no solution to this day.

As an option, you can keep only one nuxt layout (default) in your layouts folder. 
Then create some "custom-layouts" folder, create there all needed layouts like :

`<div id="main-layout">
    <h1>It's main layout</h1>
    <slot/>
</div>`

And after this you can use "default" nuxt layout as a place to add notifications component. 
And for all pages you'll need to add layout component like :

`<div id="my-page">
  <main-layout>
    <h1>Here is going page content</h1>
  </main-layout>
  </div>`

**Comment by gerbenvandijk** [comment]
> Workaround:
> 
> ```js
> // module code
> export default function myModule (moduleOptions) {
>   this.nuxt.hook('build:templates', ({ templatesFiles }) => {
>     const appFile = templatesFiles.find(t => t.dst === 'App.js')
>     let source = fs.readFileSync(appFile.src, { encoding: 'utf8' })
>     source = source.replace(`const templateEl = h('div', {`, `const templateEl = h(require('~/components/LayoutBase.vue').default, {`)
>     fs.writeFileSync(appFile.src, source, { encoding: 'utf8' })
>   })
> }
> ```

@Akryum could you share the contents of the LayoutBase.vue file as well? Thanks!

**Comment by danielroe** [comment]
This is now possible in Nuxt 3 by adding global components to your `app.vue` file. Layouts/pages can also be added within this file alongside these global components.
