### ISSUE TITLE
Add page lifecycle states to $nuxt

### ISSUE THREAD

**Issue by chriscalo** [nuxt/nuxt#6827]
### What problem does this feature solve?

The [Page Lifecycle API](https://developers.google.com/web/updates/2018/07/page-lifecycle-api) is useful as a signal of user activity.

For example, I might want to use the page state to change how often I poll my API for fresh data. Most frequently when the page state is `Active`, less often when it is `Passive`, and off while it is `Hidden`.

There's an npm module named [page-lifecycle](https://www.npmjs.com/package/page-lifecycle) that simplifies . This feels like the kind of utility that would go well in [`$nuxt`](https://nuxtjs.org/api/$nuxt), the NuxtJS helper.

### What does the proposed changes look like?

Here's one idea for the API:

| Property | Values |
| ------------ |-----------|
| `$nuxt.pageState`  | `"active"` or `"passive"` or `"hidden"` |
| `$nuxt.isActive` | `true` or `false` |
| `$nuxt.isPassive` | `true` or `false` |
| `$nuxt.isHidden` | `true` or `false` |

**Comment by manniL** [comment]
A module for the API would be fitting 👍 

I wouldn't add it to the core itself to keep it as lean as possible ☺️
