### ISSUE TITLE
Progress bar which correctly shows the progress downloading async data

### ISSUE THREAD

**Issue by mitar** [nuxt/nuxt#6833]
### What problem does this feature solve?

Current progress bar is time based on not based on real amount of data which has been transferred. The only information provided in `asyncData` to nuxt.js is various forms of a promise, which only tells when transfer has finished. But for example, if one uses `fetch`, you can use `getReader` to read in chunks and know how much data has been transferred. Progress bar could then display this information.

### What does the proposed changes look like?

I think some best practices and patterns how to handle this should be provided. For example, one could set at the beginning of `asyncData` how much data there will be, and then regularly call some progress callback to update. Before the returned promise from `asyncData` resolves.

**Comment by pimlie** [comment]
For reference: https://github.com/nuxt-community/axios-module/issues/270

The lib used for retrieving data is responsible for reporting progress information to the nuxt progress bar. If this feature request is about nuxt/http, then probably we should move this to the nuxt/http repository

**Comment by mitar** [comment]
Is there an API how to report this to the nuxt progress bar? From what I have seen it is just start and end what is possible to report? You cannot influence how many steps does the progress bar has and then increase it? Or am I missing something? If so, I would suggest this is documented with some simple example in documentation.

**Comment by pimlie** [comment]
The progress bar is documented here, you need to call increase with a percentage: https://nuxtjs.org/api/configuration-loading#using-a-custom-loading-component

Otherwise have a look at the implementation of the nuxt-loading component here: https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/components/nuxt-loading.vue

**Comment by mitar** [comment]
> The progress bar is documented here, you need to call increase with a percentage

I mean, that describes how to implement a custom one. Not how should one call an official one, or even how one get access/reference to it, and even if you can call it? Can I call `increase` just so? Does this influence how other code calls it? How do I set the overall limit?

I think there is more to be hoped for here in terms of documentation, if this is already possible.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
