### ISSUE TITLE
Allow comma seperated route paths

### ISSUE THREAD

**Issue by drewbaker** [nuxt/nuxt#6890]
### What problem does this feature solve?

It's common for the sites we build to have region specific content, and then global content. Like:

```
/uk/videos
/asia/videos
/us/videos
/us/videos/_video-id.vue
/videos
/videos/_video-id.vue
/contact.vue
/news/
/news/_post-id.vue
```

So it would be great if we could have a directory structure using a comma separated list like this:

```
/_location:uk,asia,us/videos
/videos
/videos/_video-id.vue
/contact.vue
/news/
/news/_post-id.vue
```

This would make the router way easier to deal with for groups of paths that share a similar structure.

### What does the proposed changes look like?

This would be so useful!

```
/_location:uk,asia,us/videos
```

Would then give $router.params.location would be either asia, uk or us.

**Comment by danielroe** [comment]
Though it's not with the file name, this is now possible to implement with `definePageMeta` within Nuxt 3, which allows full customisation of the RegExp via `path`.
