### ISSUE TITLE
Testing cli command like VueCLI

### ISSUE THREAD

**Issue by StummeJ** [nuxt/nuxt#6893]
### What problem does this feature solve?

It is impossible to properly get unit tests working like they do with the vue-cli.  I would propose we setup a nuxt-cli command to do the same thing.  I'm using Mocha+Chai and although it works, VueCLI's implementation is 1000x better and actually allows me to watch vue files.

### What does the proposed changes look like?

Copy over the functionality from VueCLI for running unit tests instead of making it a bespoke configuration.

**Comment by pi0** [comment]
Hi @StummeJ. Thanks for your suggestion. Nuxt.js doesn't runs parallel services like Vue CLI does. ( A project is under progress to make it working somehow better ;) )

I think for now, it's better switching to Jest and then you can easily use `--watch` CLI option: 

> Watch files for changes and rerun tests related to changed files. If you want to re-run all tests when a file has changed, use the --watchAll option instead.

You can also use [concurrently](https://www.npmjs.com/package/concurrently) npm package to run `nuxt dev` and `jest --watch` in parallel.

**Comment by StummeJ** [comment]
Really the biggest issue for using mocha+chai is the lack of a way to get then generated webpack config.  If there was some way to tap into that then a mocha test runner would be pretty simple.  VueCLI is really not doing anything special other than generating a webpack and running the mocha command.

**Comment by danielroe** [comment]
This is now present in Nuxt 3 via the `nuxi test` command. We can track ongoing improvement to unit tests via https://github.com/nuxt/nuxt/issues/13077 and https://github.com/nuxt/nuxt/issues/14534.
