### ISSUE TITLE
Allow object when setting router.base for additional attributes

### ISSUE THREAD

**Issue by Soviut** [nuxt/nuxt#6913]
### What problem does this feature solve?

Currently, the `router.base` in the `nuxt.config.js` can only be set to a string which creates a `<base>` tag with an href attribute. The option to use an object would be useful so that additional arguments could be supplied such as a target. In my case, the entire site lives inside an iframe so all links need a `target="_parent"`. Setting this in `<base target="_parent">` is much more reliable than setting it in each link on the site.

### What does the proposed changes look like?

I would propose keeping the string, but also allowing an object to be set. This object would assign any keys as attributes on the base tag.

```javascript
router: {
  base: {
    href: '/',
    target='_parent'
  }
}
```

If an object is detected, it should be merged with a default object containing just the `href` attribute.

```javascript
  if (typeof router.base === 'object') {
    const base = {
      href: '/',
      ...router.base
    }
  }
```

**Comment by danielroe** [comment]
We have updated the router config in Nuxt 3 and this issue is no longer applicable. Nuxt now has a `<Base>` element which can be used directly within the template (or configured within `useHead` or in `app.head` in `nuxt.config`).
