### ISSUE TITLE
Static assets with url reference does not work with @ alias

### ISSUE THREAD

**Issue by onuriltan** [nuxt/nuxt#6920]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://codesandbox.io/s/nuxt-static-asset-issue-vpn8p](https://codesandbox.io/s/nuxt-static-asset-issue-vpn8p)

### Steps to reproduce

- Open code sandbox
- Try to change background-image of the div's by following official docs
   - https://nuxtjs.org/guide/assets#webpack

### What is expected ?

To see the image in assets folder as background-image of the div by applying the css below
   - background-image: url("@assets/dsotm.png")
    

### What is actually happening?

It cannot find it via `@` alias

### Additional comments?

However, this works
   - background-image: url("~@/assets/dsotm.png")

**Comment by christian-bravo7** [comment]
to reference assets and static files is used ~ alias

Reference: [https://nuxtjs.org/guide/directory-structure/#aliases](https://nuxtjs.org/guide/directory-structure/#aliases)

**Comment by manniL** [comment]
AFAIK it should also work with `@`

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
