### ISSUE TITLE
watchQuery fires twice on $router.push

### ISSUE THREAD

**Issue by dpmccabe** [nuxt/nuxt#6986]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://codesandbox.io/s/sparkling-platform-di095](https://codesandbox.io/s/sparkling-platform-di095)

### Steps to reproduce

Create a method that calls `$router.push` with a new query parameter value:

```js
<template>
  <div>
    <nuxt-link to="#" @click.native.prevent="incX">increment x</nuxt-link>
    <pre>{{x}}</pre>
  </div>
</template>

<script>
export default {
  data() {
    return {
      x: 0
    };
  },

  methods: {
    async incX() {
      console.log("incX:", this.x);
      this.x += 1;

      this.$router.push({ query: { x: this.x } });
    }
  },

  watch: {
    "$route.query": {
      handler(query) {
        console.log("$route.query:", query);
      }
    }
  },

  watchQuery(newQuery, oldQuery) {
    console.log("watchQuery", newQuery);
    return false;
  }
};
</script>
```

### What is expected ?

`watchQuery` should run once every time the link is clicked.

### What is actually happening?

Clicking the link to increment the value results in `watchQuery` getting called twice even though the `$route.query` watcher is only called once, e.g.:

```
current x: 4
new x: 5
watchQuery Object {x: 5}
watchQuery Object {x: 5}
$route.query: Object {x: 5}
```

**Comment by FiNGAHOLiC** [comment]
+1

**Comment by superMarijus** [comment]
Also having this issue.

**Comment by Jafarili** [comment]
is this solved? I still have the issue
