### ISSUE TITLE
Page scoped plugin

### ISSUE THREAD

**Issue by Fnxxxxo** [nuxt/nuxt#6995]
### What problem does this feature solve?

A page scoped plugin, which has the same function as the normal plugin, runs before specific route.
A [work around](https://github.com/nuxt/nuxt.js/issues/2727) can be used. But it runs multiple times and has not nuxt context support.

### What does the proposed changes look like?

The same as the original plugin setup. Config as the follow:
```
  // in nuxt.config.js
  plugins: [
    { src: '~/plugins/page-plugin.js', route: '/pages/some-page' }
  ],
```

**Comment by manniL** [comment]
What'd be a "real" use case for that feature?

**Comment by Fnxxxxo** [comment]
@manniL An IM init process is only required for partial route in our MPA project. But the original plugin waves all routes. It consumes additional resources.

**Comment by manniL** [comment]
@Fnxxxxo Plugins that only introduce components can be omitted in case you can directly import the component for the pages you want. For other case it'd possible but also introduce overhead to ensure plugins are only activated once.

Anyway, keeping that feature request open 👍🏻

**Comment by arily** [comment]
my use case is reducing bundle sizes for some vue plugins that requires 'Vue.use' but only used on certain routes. (for example some chart plugin).

I would suggest add a 'plugins' config in pages component, with same structure found in nuxt.config.js:

```vue
<script>
export default {
  plugins: [{ src: '~/plugins/page-plugin.js', route: '/pages/some-page' }]
}
</script>
```

**Comment by danielroe** [comment]
For this, I think an inline middleware would work in Nuxt 3:

```js
definePageMeta({
  middleware: () => {
    // do your setup
  }
})
```

It will only run before accessing the page, but it will run before the page is loaded.
