### ISSUE TITLE
Navigating to child route with query string refreshes parent route component

### ISSUE THREAD

**Issue by curtisburns** [nuxt/nuxt#6998]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://codesandbox.io/s/falling-wind-hipzh?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/falling-wind-hipzh?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

1. Create a parent route as described in the documentation.

2. Add a counter to parent page that increments on route change, init to 0, and render this in the template to monitor if the state refreshes.

3. When creating a link to the nested child route, add a query string to the url e.g ?day=1;

4. Navigate to and from the child route and note how the counter remains at 0. 

5. Do the same again but remove the query string, and we can see that the counter now increments as expected.

### What is expected ?

State should persist/not refresh when navigating to the child route, regardless of whether a query string is passed to the child route or not.

### What is actually happening?

The state of the parent is refreshing when attaching a query string to the url of the child and navigating to that route. This does not happen in a Vue CLI app and is therefore an issue related to Nuxt.

### Additional comments?

Spent a few hours looking into this and once I figured out the cause, I wasn't sure if it was intended behaviour. I tested it out with a standard Vue app, and this refreshing behaviour doesn't seem to happen when attaching a query string to the url.

**Comment by curtisburns** [comment]
Not stale. App is currently in production and need still to overcome this problem.

**Comment by dong-king** [comment]
yes, I have this problem also!

**Comment by kchjxxgh** [comment]
any progress? any workaround?

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
