### ISSUE TITLE
GetDefaultLayout function

### ISSUE THREAD

**Issue by flapili** [nuxt/nuxt#7031]
### What problem does this feature solve?

Provide a standard way to set the default layout to avoid extra logic in pages
current workarounds (I haven't tested all of them) :
•set the layout property in a page like `layout: condition ? "layoutA" ? "layoutB"` on every pages
•do the same as above but in one page and inherit it (mixin), still have to add extra part in every pages
•set the layout programmatically  `$nuxt.setLayout('layoutA')` in the page/in a middleware or in a router guards
•put the logic in the layout

set it in a router guards avoid extra part in pages, but not the ideal solution.

(I probably forgotsome workaround)

### What does the proposed changes look like?

in nuxt.config.js

```js
  getDefaultLayout(context) {
      if (context.app.isMobile)
          return "mobile_menu"

      if ()
          return "..."

      if ()
          return "..."

      if ()
         return "..."

      else
        return "default"
  },

```
optionnaly getDefaultLayout could be async

**Comment by danielroe** [comment]
This is now usable in Nuxt 3 in your `app.vue` with something like:

```vue
<template>
  <NuxtLayout :layout="$route.layout || getDefaultLayout()">
    <NuxtPage />
  </NuxtLayout>
</template>
```
