### ISSUE TITLE
layouts/error.vue should behave like any other page

### ISSUE THREAD

**Issue by kevinley** [nuxt/nuxt#7084]
### What problem does this feature solve?

IMHO it would be a very good idea to refactor how errors are handled in Nuxt.

The current structure: error.vue should be treated as a page but is located in /layouts is confusing and doesn't allow any serious custom functionality.

The error.vue page component should definitely be treated like any other page located in /pages, which would give it their own route name/path and enable us to use for instance middlewares, which has been mentioned in bug reports already.

My current situation: When using nuxt-i18n, specifically using switchLocalePath nothing happens.
That is because getRouteName returns null, because layouts/error.vue is not a real standard page.

I think lots of developers would be glad if the error.vue page were implemented and handled as any other page.

**Comment by Geminii** [comment]
Hi :) 
I think it’s a good idea to moove error.vue into pages and not into the layout. 
Could you add a reproduction of your context ? 
Then i will try to purpose a PR for this improvment. 

Thanks 😀

**Comment by danielroe** [comment]
We've taken a different approach for `error.vue` so I believe this issue can be closed. Any future suggestions would be welcome, however.
