### ISSUE TITLE
support demand page build like next.js

### ISSUE THREAD

**Issue by icai** [nuxt/nuxt#7104]
### What problem does this feature solve?

This feature is for dev mode.  if  the project has  a lot of  page,  the first open browser will wait for loading. 

### What does the proposed changes look like?

 In dev mode, support demand entry page build  firstly.

```
https://github.com/zeit/next.js/blob/master/packages/next/server/on-demand-entry-handler.ts
```

**Comment by danielroe** [comment]
This is now implemented in the latest Nuxt 3/Nitro with `routeRules`.
