### ISSUE TITLE
support babelrcRoots config

### ISSUE THREAD

**Issue by yoyo837** [nuxt/nuxt#7106]
### What problem does this feature solve?

Submodule compilation feature request

### What does the proposed changes look like?

      babelrcRoots: [resolveApp('.'), resolveApp('./pages'), resolveApp('./commons')],

**Comment by pi0** [comment]
Hi @yoyo837. Would you elaborate more on your idea?

**Comment by yoyo837** [comment]
Thanks for quick reply. I use nuxt to build my project with submodules, it will refer to the node_modules of the submodules.

**Comment by pi0** [comment]
So you want to, for example, Nuxt transpile `node_modules/@company/submodule/foo.js` with `node_modules/@company/submodule/.babelrc`?

**Comment by yoyo837** [comment]
```
|--- commons  // submodule
|--- pages  // submodule
|--- package.json
```

If node_modules exists in the submodule's folder, nuxt will pick something into bundles from it, and I want to avoid this, no babel configuration file currently exists.

**Comment by danielroe** [comment]
We no longer use Babel in the latest Nuxt 3, so closing this issue for now.
