### ISSUE TITLE
HTML minifier docs, options and results don't work as expected

### ISSUE THREAD

**Issue by davestewart** [nuxt/nuxt#7118]
### Version

[v2.12.0](https://github.com/nuxt.js/releases/tag/v2.12.0)

### Reproduction link

[https://codesandbox.io/s/nuxt-html-minify-w28si](https://codesandbox.io/s/nuxt-html-minify-w28si)

### Steps to reproduce

Following the setup in https://nuxtjs.org/api/configuration-build#html-minify I could not get HTML minifying to work.

I have added information here as to what happened and why:

- https://github.com/nuxt/docs/issues/1880

However, with help from @manniL it seems that perhaps the implementation is out of date, because actually the code needed to condense whitespace between nodes is not (as the docs rather vaguely suggest)...

```js
export default {
  build: {
    html: {
      minify: {
        // additional options
        collapseWhitespace: true,
        collapseInlineTagWhitespace: true,


        // nuxt defaults
        collapseBooleanAttributes: true,
        decodeEntities: true,
        minifyCSS: true,
        minifyJS: true,
        processConditionalComments: true,
        removeEmptyAttributes: true,
        removeRedundantAttributes: true,
        trimCustomFragments: true,
        useShortDoctype: true
      }
    },
  },
}
```

...but...

```js
export default {
  build: {
    loaders: {
      vue: {
        compilerOptions: {
          whitespace: 'condense'
        }
      }
    }
  }
}
```

See: https://twitter.com/dave_stewart/status/1241872610306260993

### What is expected ?

HTML output has whitespace stripped between tags

### What is actually happening?

Whitespace is not stripped

### Additional comments?

It's important to have whitespace stripping in place so it doesn't affect layout:

![whitespace](https://user-images.githubusercontent.com/132681/77270650-6ef1d400-6ca4-11ea-8c44-ce924b86c13d.gif)

**Comment by davestewart** [comment]
Yes, this is still an issue.

**Comment by davestewart** [comment]
Not stale

**Comment by deevanych** [comment]
@davestewart I came across the same thing. Have you solved this problem?

**Comment by davestewart** [comment]
Haven't thought about it since then!

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
