### ISSUE TITLE
Allow modules to differentiate between server starting or building

### ISSUE THREAD

**Issue by btkostner** [nuxt/nuxt#7164]
### What problem does this feature solve?

I'm working on implementing [a module](https://github.com/system76/nuxt-appsignal) similar to sentry error reporting, but for appsignal. I am using their nodejs package for server metrics, but it is running with `nuxt generate` and `nuxt build`. I'm trying to find a way for the module to know if we are actually starting the server, or if we are just generating files. 

Issue: https://github.com/system76/nuxt-appsignal/issues/5
Module code: https://github.com/system76/nuxt-appsignal/blob/master/src/index.js

### What does the proposed changes look like?

There should be a flag similar to `this.options.dev` but `this.options.serverRuntime` for modules. This should be set to true if nuxt is ran with `nuxt dev`, `nuxt start`, or if nuxt is used as middleware in a larger app.

**Comment by pi0** [comment]
Hi @BatuhanK. There are internal flags that you can safely use for Nuxt 2 at least. `this.options._build` and `this.options._start`.

The reason they are kept internal is that only when using standard cli (`nuxt *`) we set them. Programmatic usage (pre 2.12) users should manually specify these flags. Users using  `loadNuxt` (#6868) are safe as well.

**Comment by danielroe** [comment]
This is possible in Nuxt 3 as @pi0 explained. In Nuxt 3 all modules are build-time only. So I think we can safely close this issue.
