### ISSUE TITLE
Support of dynamic routes on client

### ISSUE THREAD

**Issue by ypetrych** [nuxt/nuxt#7186]
### What problem does this feature solve?

I'm working on project where few static pages are generated using `yarn generate`. Each page is served to different domain. I'm trying to figure out how to update the routes dynamically on client. 

For example there are 2 domains with same pathname `my/path`: 
`first.com/my/path
second.com/my/path
`

nuxt.config.js

`router: {
        extendRoutes(routes, resolve) {
            routes.length = 0
            routes.push({
                name: 'first',
                path: '/first/my/path',
                component: resolve(__dirname, 'pages/First.vue')
            })
            routes.push({
                name: 'Second',
                path: '/second/my/path',
                component: resolve(__dirname, 'pages/Second.vue')
            })
        },
    }
...`

In order to make such pages working I need to put corresponding path (`my/path`) to alias in routes. It should be added dynamically to corresponding route. For example. on `first.com/my/path` I need to put `my/path` alias to route with name `first`. 

### What does the proposed changes look like?

There should be additional route param or plugin which will allow dynamically change the route on client. If it's plugin - it should run before `createApp` in the code otherwise corresponding component won't be loaded on client.

**Comment by danielroe** [comment]
This is now possible in Nuxt 3 by creating a custom `~/app/router.options.ts`. An example of such an implementation for multi-tenant is explained at https://zernonia.keypress.blog/why-keypress. See also implementation at https://github.com/zernonia/keypress.
