### ISSUE TITLE
Throw warning on .vue files with a space after extension

### ISSUE THREAD

**Issue by kazazes** [nuxt/nuxt#7194]
### What problem does this feature solve?

While it may seem silly, a member of my team spent far too long working out why a new page wasn't being routed. Given that `ls`, VSCode et al. have no obvious mechanism of showing a sleeper space, perhaps the compiler should throw a warning while building the router.

### What does the proposed changes look like?

When building the router, check the fs for `/pages/**/*{.vue }`, throw warning.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
