### ISSUE TITLE
Add referrerpolicy="noreferrer" on built index

### ISSUE THREAD

**Issue by leolb-aphp** [nuxt/nuxt#7289]
### What problem does this feature solve?

In this issue: https://github.com/rancher/dashboard/issues/575 - they are importing external resources on what's usually deployed on internal infrastructure where leaking referrer is not a big deal but certainly unnecessary and a nuisance.

### What does the proposed changes look like?

Allow one to specify either abitrary attributes on the stylesheet and script elements or just set the referrerpolicy for these.

So that one can do, e.g.

./node_modules/.bin/nuxt build --referrerpolicy "noreferrer"

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10590">#c10590</a>)</em></sub></div>

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
