### ISSUE TITLE
Download & replace remote images for full static export

### ISSUE THREAD

**Issue by J05HI** [nuxt/nuxt#7389]
### Version

[nuxt-edge](https://github.com/nuxt.js/releases/tag/nuxt-edge)

### Reproduction link

[Any nuxt project](Any nuxt project)

### Steps to reproduce

- Switch to nuxt-edge on any nuxt project
- Enable target: static
- Build and export it

### What is expected ?

Remote images should be downloaded, too => we don't have to call the API/CMS for images. 

### What is actually happening?

Images don't get replaced with local ones.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10678">#c10678</a>)</em></sub></div>

**Comment by lihbr** [comment]
Hi @J05HI , this was discussed in the [Full static generated mode RFC](https://github.com/nuxt/rfcs/issues/22#issuecomment-623657000) and it looks like this won't be something enabled by default at best, I'll let you read that over there to help you with making up your mind about it :)

Nonetheless if you're willing to work on an option or a module to enable that properly feel free to submit a PR~

**Comment by J05HI** [comment]
@lihbr
Thank you for your reply!

**Comment by danielroe** [comment]
This is implemented in https://github.com/nuxt/image (https://image.nuxtjs.org/getting-started/static) and I think we can close it here.
