### ISSUE TITLE
Allow globalName include non english characters

### ISSUE THREAD

**Issue by Zekfad** [nuxt/nuxt#7406]
### What problem does this feature solve?

It will allow you to specify any name for app you want to.

### What does the proposed changes look like?

* Disable regex in https://github.com/nuxt/nuxt.js/blob/0bdc71c8d8c884a350c5b1b40fb74974a6b1d96a/packages/config/src/options.js#L64
* Replace templates from
```js
obj.<%= template %>
```
to
```js
obj["<%- template.replace(/"/g, '\\"') %>"]
```
* Need additional logic for HTML ID handling, e.g. replace any non-valid characters with their Unicode point (like u0000).

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10688">#c10688</a>)</em></sub></div>

**Comment by danielroe** [comment]
We do not plan to support this.
