### ISSUE TITLE
Custom html/template rendering on nuxt server error

### ISSUE THREAD

**Issue by proArtex** [nuxt/nuxt#7416]
### What problem does this feature solve?

If an unhandled Error occurs during ssr, an end user will see "Nuxt.js Internal Server Error" message. It would be great to have an ability to render layouts/error.vue template or at least custom html. It is not possible to catch all the application errors with context.error() func, moreover an error may occur right after that call or somewhere else. 

Why is it important? "Nuxt.js Internal Server Error" message means nothing to the end user, it is confusing, we could provide more detailed explanation. It is also inconvenient to wrap everything with try/catch block even though you know you cannot handle it, but show the error template.

### What does the proposed changes look like?

Why don't we use try/catch and error() call only when we want to handle it differently than showing the error template, and make a single point of catching errors from all the app at the top level to show that template.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10702">#c10702</a>)</em></sub></div>

**Comment by proArtex** [comment]
Hey @Atinux, any thoughts?

**Comment by proArtex** [comment]
Here is what I've figured out so far:
1. You need to create app/views/error.html file inside your base dir in order to override the default error template.
2. The "Nuxt.js Internal Server Error" message appears because app/views/error.html file is not copied into dist folder during build (I wonder why). So you HAVE TO manually copy .nuxt/views/error.html during build in addition to dist folder.
3. app/views/error.html isn't static html, it is template file, error object is passed into it.

Is there still a problem? Yes, the points is nuxt forces us to use error() func everywhere we can, even though we cannot catch everything, runtime errors are possible. In case of uncaught error spa and ssr act differently: spa shows layouts/error.vue, ssr shows app/views/error.html. It is inconsistent, we want to show the same layouts/error.vue when possible without having to wrap everything with try catch.

I don't have deep knowledge about nuxt.js, but I suppose there is a way or code point where we can still render ayouts/error.vue. Otherwise render app/views/error.html. This is how I would handle some "user endpoint" in asyncData, expecting error() func to be called somewhere in internals:

```
try {
    const user = await this.$userRepository.findById(params.userId);
    ...
} catch(e) {
    if (e.response && e.response.status === 404) {
        error({statusCode: 404, message: 'User not found'});
        return;
    }

    throw e;
}
```

Or event described this behaviour in one single place of catching exceptions.

**Comment by danielroe** [comment]
This is now possible in Nuxt 3 via `~/error.vue`. A second (internal) request is made to render an error page in the event of an error rendering the initially requested route.
