### ISSUE TITLE
Instantiating Vue Router everytime causes serious performance problem

### ISSUE THREAD

**Issue by asd123freedom** [nuxt/nuxt#7473]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://codesandbox.io/s/nuxt-middleware-rxzl4](https://codesandbox.io/s/nuxt-middleware-rxzl4)

### Steps to reproduce

1.use wrk to simulate large scale of requests
2.remove lots of files from pages folder and simualte again
3.compare QPS between two reports generated from wrk

### What is expected ?

The QPS numbers are close

### What is actually happening?

If I remove files from pages folder, QPS will increase a lot.

### Additional comments?

I looked into Server.js which is generated by nuxt-cli., and I found Vue Router is instanced every time. I assumed that it should be cached in case of performance problem 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10737">#c10737</a>)</em></sub></div>

**Comment by manniL** [comment]
Possibly related: https://github.com/nuxt-community/nuxt-i18n/issues/690#issuecomment-635131061

**Comment by asd123freedom** [comment]
Yes，it does. I guess it may be solved by using nuxt-community/router-module. With router-module I can make sure vue-router init only once.

**Comment by vodniciarv** [comment]
> Yes，it does. I guess it may be solved by using nuxt-community/router-module. With router-module I can make sure vue-router init only once.

can You show your solution with [router-module](https://github.com/nuxt-community/router-module)?

**Comment by asd123freedom** [comment]
I've tried this week and failed .  [Vue SSR Guide](https://ssr.vuejs.org/guide/routing.html) tells developers that **we also need a fresh router instance for each request**

**Comment by chenfengyanyu** [comment]
I ran into the same problem and located the Vue-Router section. 

First, through Clinic analysis, addRouteRecord causes CPU-intensive calculations, as shown below

![addRouterRecord](https://raw.githubusercontent.com/chenfengyanyu/my-web-accumulation/master/node-qps/router.png)

Secondly, the escapeString function will cause QPS loss, the data is as follows:

![escapeString](https://raw.githubusercontent.com/chenfengyanyu/my-web-accumulation/master/node-qps/before.png)


The source code of escapeString is as follows（**QPS=891**）：
 
```js
function escapeString (str) {

return str.replace(/([.+*?=^!:${}()[\]|\/\\])/g, '\\$1')

}

```

So, I tried as follows（**QPS=1524**）：

```js

function escapeString (str) {

return ''；

}

```

![escapeString](https://raw.githubusercontent.com/chenfengyanyu/my-web-accumulation/master/node-qps/after.png)

There is a lot of route matching here, is there a more efficient way to solve it？
Any help will be appreciated.

**Comment by pi0** [comment]
Thanks, @chenfengyanyu for the benchmarks. It makes quite a sense If the route registration part is CPU-intensive, finding a way to _cache/compute_ SSR routes once. But we cannot simply create a shared instance for SSR! So we probably need to see if there is a way in improving vue-router.

**Comment by asd123freedom** [comment]
@pi0  looing forward to your solution

**Comment by yaowei520** [comment]
@pi0
Is there any progress on this issue?

**Comment by stouch** [comment]
Any news about this ?

**Comment by danielroe** [comment]
It's been quite some time and there's a new major version of vue-router. If anyone is still experiencing a problem with this, would you please open an issue upstream at https://github.com/vuejs/router with a reproduction? Feel free to tag me; I'd be happy to help look into this if so.

**Comment by coremyslo** [comment]
About a year ago, I encountered the same issue.

My solution involved forking and rewriting the module so that it doesn't create a separate route for each locale. Instead, it allows setting up vars in the route for a single locale. Here's an example of the route configuration:

```
{
            name: `employer-childcare-sitter`,
            path: `/{category}`,
            ...,
            meta: {
                i18n: {
                    category: {
                        "da": "soeger-babysitter",
                        "de": "babysitters",
                        "en": "babysitter",
                        "es": "canguro",
                        "fi": "lastenhoitaja",
                        "fr": "baby-sitter",
                        "it": "baby-sitter",
                        "lt": "valandine-aukle",
                        "nl": "oppas",
                        "no": "barnevakt",
                        "pl": "niania-dorywczo",
                        "sv": "barnvakt",
                    },
                },
            },
        },
```

In the case of the da locale, the path is /{category}, so we search for the value in meta.i18n.category to replace it. I configured this directly in my routes.

I believe this module could be updated to support this route setup method through parameters or by manually parsing the routes as another option.
