### ISSUE TITLE
Allow middleware to run client-side only in SSR mode

### ISSUE THREAD

**Issue by Rfrixy** [nuxt/nuxt#7474]
### What problem does this feature solve?

Middleware frequently need to check state such as whether a user is logged in. 
If you want to redirect users to a login page based on their logged in status on every page, you cannot do this via a middleware in SSR mode.

Changing the whole app to SPA mode for this one feature will slow the entire app down.

### What does the proposed changes look like?

A flag in nuxt.config.json to run middlewares in client side only.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10739">#c10739</a>)</em></sub></div>

**Comment by hecktarzuli** [comment]
I would suggest the feature of using middleware.client.js and middleware.server.js vs this flag so it matches the same feature of plugins.  This would also eliminate a bunch of if(process.client) stuff as well.  I may be working on a pull on this at some point but currently don't have time.

**Comment by danielroe** [comment]
I think the right approach here is to early return if it's being run on the server side:

```js
export default defineNuxtRouteMiddleware(to => {
  if (process.server) return
  // client logic
})
```
