### ISSUE TITLE
Option to turn off HMR in non-production environments

### ISSUE THREAD

**Issue by jonthemiller** [nuxt/nuxt#7492]
### What problem does this feature solve?

We have pre-production, deployed (ie not localhost) environments that run in dev mode but do not need HMR to be enabled. Currently, there is not a feasible way to disable the Hot Middleware without running in prod mode.

### What does the proposed changes look like?

One should be able to supply a value of `false` to the `hotMiddleware` option within `build` to disable HMR.

https://nuxtjs.org/api/configuration-build#hotmiddleware

```javascript
module.exports = {
  build: {
    hotMiddleware: false
  }
}
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10754">#c10754</a>)</em></sub></div>

**Comment by lBaconDR** [comment]
HMR is not working in all context seamless for us (safari e.g.). Therefore we would also like to have the possibility to let dev run without HMR.

**Comment by padinko** [comment]
> None of the suggsested solutions found here and elsewhere have worked for me. Removing the HMR plugin leads to ` Invalid HMR message` errors in the frontend. The only thing that worked to disable the HMR requests was adding this setting to the nuxt build config:
> 
> ```js
>   build: {
>     hotMiddleware: {
>       client: {
>         autoConnect: false
>       }
>     }
>   }
> ```

you need to disable [HMR's build progress indicator](https://nuxtjs.org/docs/configuration-glossary/configuration-build#indicator) too, so for best result this config will disable HMR on browser:
```js
    build: {
        hotMiddleware: {
            client: {
                autoConnect: false,
            },
        },
        indicator: false,
    }
```

**Comment by pencilcheck** [comment]
thanks for the code to disable hmr,  I wonder if there are options to allow hmr but without having the limit in browser like chrome, everytime I enable hmr, I can only open 1 tab at a time as other new tabs will not work.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
