### ISSUE TITLE
Full-static mode querystring API

### ISSUE THREAD

**Issue by gnuletik** [nuxt/nuxt#7627]
### What problem does this feature solve?

Full-static mode is really useful !
However, when developing a list with query string like `/articles?page=2`, it is currently not possible to save one payload per page.

The only full-static solution that I found so far is to:
- fetch all articles in asyncData / fetch (so there is one payload with all articles).
- filter all articles in the `mounted` hook.

However, the page is re-rendered on page load.

### What does the proposed changes look like?

To work around this, Nuxt could expose a `payload` API to allow developers to save multiple payloads per page.

In the  `/articles?page=2` example, we could save one payload for one article page.
On page load, we would be able to choose the appropriate payload to load.

Or maybe Nuxt could expose an API to load a specific payload from the query strings values.

I looked into the [full-static PR](https://github.com/nuxt/nuxt.js/pull/6159) and did not find any way to do this. It seems that there is only one payload saved per page.
However, I found a [reference to this issue in the RFC](https://github.com/nuxt/rfcs/issues/22#issuecomment-454145917). @manniL commented about this issue but I'm not sure if a solution was found.

Thanks a lot for this great framework !

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10864">#c10864</a>)</em></sub></div>

**Comment by manniL** [comment]
I went with completely avoiding query strings wherever possible.
Instead of `/articles?page=2` I use sth like `/articles/page/2` because it is more SEO-friendly, easier to pick up for the user and works with static site generation easily as they can be treated as dynamic pages where `2` would be the dynamic part of the URL.

I think fully supporting query string parameters for static site generation would be quite tough.

**Comment by gnuletik** [comment]
Thanks for the feedback @manniL !

Using dynamic pages instead of query parameters would totally do the job for simple use cases but I can see several limitations:
- What if you want to have a structure with an `/articles` (list) page and `/articles/:slug` page ? You may have a route conflict if a slug is `page`.
- What if you want multiple query parameters like `?page=2&order=asc` or `?page=2&filter=category2` ? This seems like a common pattern. You could convert this to a custom slug format like `/articles/page/page-1-filter-category2` but it does not seems really convenient / common pattern.

Also, query parameters seems to be indexed by search engines (not an expert in this field, I may be wrong).

I guess you're right : supporting query string parameters may be quite a huge task for Nuxt !
Would it be easier to expose some `payload` API to let developers handle their own logic of "which payload is saved in static and which is not" ?

There's also another concern that I missed in the original issue : does the crawler handles query parameters ?
For example, if I have a `<router-link :to="{ query: { page: '2' } }" />`, will the crawler pre-render this page ?

Thanks :)

**Comment by manniL** [comment]
>     * What if you want to have a structure with an `/articles` (list) page and `/articles/:slug` page ? You may have a route conflict if a slug is `page`.

A very rare edge case but true, that'd be a problem here. 

>     * What if you want multiple query parameters like `?page=2&order=asc` or `?page=2&filter=category2` ? This seems like a common pattern. You could convert this to a custom slug format like `/articles/page/page-1-filter-category2` but it does not seems really convenient / common pattern.

There are a couple of options here: Either a custom slug format *or* still using query parameters for the order but sorting them on the front-end (decoupled from the API call).

> Also, query parameters seems to be indexed by search engines (not an expert in this field, I may be wrong).

"It depends". If they are important for the content, Search Engines usually take them into account. This doesn't mean it is good for SEO though (and good for the user).
 
> I guess you're right : supporting query string parameters may be quite a huge task for Nuxt !
> Would it be easier to expose some `payload` API to let developers handle their own logic of "which payload is saved in static and which is not" ?

Hard to judge from my perspective. Maybe @pi0 has an opinion here?

> There's also another concern that I missed in the original issue : does the crawler handles query parameters ?
> For example, if I have a `<router-link :to="{ query: { page: '2' } }" />`, will the crawler pre-render this page ?

No, query parameters will be ignored for rendering. You can't really "represent" them when generating pages.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉

**Comment by LeonardoRick** [comment]
I think would be really amazing (if possible) to support string parameters for SSG and SSR in nuxt 3

**Comment by manniL** [comment]
@LeonardoRick They are supported for SSR easily but not for full SSG/prerendering

**Comment by Ryanjso** [comment]
Hi @danielroe I believe this is still relevant in the latest version. 

Ideally we could SSG the page with no params, and SSR it if it does have params.

**Comment by danielroe** [comment]
@Ryanjso  ideally you should handle it in your page. it would be undesirable if you could bypass a static page by appending random numbers via query string.
