### ISSUE TITLE
Stringify static payload for better performance

### ISSUE THREAD

**Issue by kedrzu** [nuxt/nuxt#7645]
### Is your feature request related to a problem? Please describe.

In latest nuxt release there is a super cool feature of persisting page async data into a payload script for static deploys.
Thanks for that, it's more than fantastic! 

It uses `@nuxt/devalue` library for that. 

### Describe the solution you'd like

Standard Vue SSR however stringifies the payload and uses `JSON.parse` on client side to turn it back into POJO.

Whereas it seems to be weird at first, in fact it's much more performant than using a plain JS POJOs, as done in `devalue`/ That's because JS does not need to make a full tokenization of the object into AST, before running it. It should be especially true for bigger payloads.

Here is some video from Google on the topic:
https://www.youtube.com/watch?v=ff4fgQxPaO0

`devalue` additionally handles circular refererences and few others things, that are impossible for `JSON.stringify`.

### Describe alternatives you've considered

I thought about submitting a PR. I guess the best is to submit a PR to `devalue` itself, but that's not an easy stuff. However, maybe I'll do it in a meantime.

To preserve all the features, like circular refs, best way I guess is to make a hot path optimization.
This could be stringifying those parts of the object graph, that does not contain circular refs, `Map`, `undefined` or other non-JSON entities.

What'ya guys think?

**Comment by galvez** [comment]
See https://github.com/galvez/nuxt-json-data

**Comment by kedrzu** [comment]
Nice stuff 😀. Cool, that you also have some performance results 😀.

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/6168.
