### ISSUE TITLE
NuxtLink `inactive-class` attribute

### ISSUE THREAD

**Issue by Larsklopstra** [nuxt/nuxt#7666]
### Is your feature request related to a problem? Please describe.

See issue:

#7662 

### Describe the solution you'd like

I'd like `NuxtLink` to have an `inactive-class` attribute, it works as the opposite to the `active-class` attribute.

#### Why?

When using Tailwind CSS I usually split up my styling into multiple parts:

- `baseClasses` (fundamental) (flex, padding, etc.)
- `activeClasses` (selected or active links/navigation items) (text-primary, etc.)
- `inactiveClasses` (not selected or inactive links/navigation items) (text-gray-500, etc.)

### Describe alternatives you've considered

Merging my `baseClasses` with `inactiveClasses` but it ends up in a long string and sometimes the `activeClasses` don't overwrite the `baseClasses`.

### Additional context

None.

**Comment by posva** [comment]
I was talking about vue-router issues: https://github.com/vuejs/vue-router/issues/2648
Note you can achieve this custom behavior by creating custom NuxtLink component with the `v-slot` api that adds new props like `inactiveClass`

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
