### ISSUE TITLE
Authentified nuxtjs app - Redirect every client api request to serverMiddleware

### ISSUE THREAD

**Issue by syskin** [nuxt/nuxt#7681]
Hi,

It could be nice if we could add secure api key (signed by crypto) by redirecting all client side request to server side.

For example, if i want to sign my request from axios, i can't do it properly secured. 
If i use axios interceptor, the client can access my methods and can see my secret through browser.
If i use a proxy,  the client can use proxy endpoint and will be identified as my nuxt app.

**Comment by danielroe** [comment]
I think this is a great idea for a module, rather than implemented in Nuxt core - and I don't see any blockers to doing so if you're interested. In the mean time, we have 1st-class session support now in h3 which we'll be documenting soon for Nuxt 3.
