### ISSUE TITLE
Components into root element

### ISSUE THREAD

**Issue by Kolobok12309** [nuxt/nuxt#7753]
Initially, i just needed simple toast, i'm thinking how it would be working in another layouts. The first thing came up with the idea to use `Vuex` and place component(list with toasts) in all layout. The idea in itself is not very good, it was also aggravated by the fact that when changing the `layout`, a rerender takes place. After this i check `vue-toasted` source, [link](https://github.com/ankurk91/vue-toast-notification/blob/master/src/js/api.js#L16) nice idea, i try use it, but some components in my toast use `vuex` and i can`t remove it

After this attempts i found #2603 issue, this my problem yeah... without solution

Please add some api for use global(between layouts and outside router-view) components it be usefull for modals, toasts etc

![image](https://user-images.githubusercontent.com/32272181/88085900-2a614100-cb8f-11ea-81c2-863a0eb5f5d9.png)

P.S. Why `nuxt.config.js` `build.template` not mentioned anywhere?) Found it late, but it's too complicated for me)

**Comment by Kolobok12309** [comment]
Something like this in [that file](https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/App.js) can easy solve issue
```js
...
<% (nuxtOptions.globals || []).forEach((path, idx) => { %>
import GlobalComponent<%= idx %> from '<%= relativeToBuild(resolvePath(path)) %>'
<% }) %>
...
```
And in render function 
```js
<% (nuxtOptions.globals || []).forEach((v, idx) => { %>
  h(GlobalComponent<%= idx %>),
<% }) %>
```
`nuxtOptions.globals` it new field in `nuxt.config.js`, for example
```js
globals: [
  '@/components/myGlobal.vue'
]
```

**Comment by 9-lives** [comment]
i just mount manually that component in middleware once.

**Comment by Kolobok12309** [comment]
@9-lives, how you connect store and router to it?

**Comment by 9-lives** [comment]
> @9-lives, how you connect store and router to it?

like this

```javascript
  document.body.appendChild(
    (new (Vue.extend(ComponentOptions))({
      router,
      store,
    }))
      .$mount()
      .$el
  )
```

**Comment by lopugit** [comment]
Wait, are you telling me that nuxt re-renders all layout components on route change? Isn't that the whole point of layouts, that they don't re-render, only the route specific data in <nuxt> should re-render?

damn 😮

**Comment by danielroe** [comment]
This is now possible with `<Teleport to="body">` in Nuxt 3.
