### ISSUE TITLE
Asynchronously import / export server middleware

### ISSUE THREAD

**Issue by Nicklason** [nuxt/nuxt#7803]
### Is your feature request related to a problem? Please describe.

I just started using nuxt but I have a problem with not being able to asynchronously use server middleware. I am using the serverMiddleware option to make a backend server with TypeScript and ExpressJS, but I have an asynchronous function that needs to finish before the handler function can be used.

### Describe the solution you'd like

Being able to asynchronously import server middleware will make it a lot easier to use ExpressJS or any other http server / server middleware that has asynchronous tasks that need to be done so that the server middleware will work properly. Please look at my example below for a better understanding of the issue.

Say you want to add a server middleware to `/api` and it should be handled by express, then you could do this:

./nuxt.config.js:
```js
export default {
  serverMiddleware: [
    {
       path: '/api',
       handler: './api/app.ts'
    }
  ]
}
```

./api/app.ts:
```ts
import express from 'express';

const app = express();

app.use(function (req, res, next) {
  res.status(200).send('Hello');
});

export default app;
```

Now I propose adding the option to return a promise that resolves to a server middleware:

./api/app.ts
```ts
import express from 'express';
import { ServerHandle } from 'connect';

const app = express();

app.use(function (req, res, next) {
  res.status(200).send('Hello');
});

// A function that returns a promise which can resolve
// to a server middleware
function someAsyncFunction(): Promise<
  ServerHandle | { path: string; handler: ServerHandle }
> {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(app);
    }, 1000);
  });
}

// Export promise
export default someAsyncFunction();
```

### Describe alternatives you've considered

I have looked at using nuxt programatically but I think that using server middleware works better. Importing nuxt also doesn't work very nicely with TypeScript.

### Additional context

https://github.com/nuxt/nuxt.js/blob/4db7e432df6e0980f4f6324d374491323801c0c1/packages/server/src/server.js#L132-L134

It will require making the useMiddleware function support promises. It won't require much work to make the setupMiddleware function support it because it is already async.

https://github.com/nuxt/nuxt.js/blob/4db7e432df6e0980f4f6324d374491323801c0c1/packages/server/src/server.js#L71

The useMiddleware function should be able to resolve a promise because it is what adds the handler to the connect server:

https://github.com/nuxt/nuxt.js/blob/4db7e432df6e0980f4f6324d374491323801c0c1/packages/server/src/server.js#L274-L277

So if the server middleware is a promise, then it should wait for it to be resolved.

https://github.com/nuxt/nuxt.js/blob/4db7e432df6e0980f4f6324d374491323801c0c1/packages/server/src/server.js#L174-L183

It will require modifying the _normalizeMiddleware function to return a promise and await the middleware argument if it is a promise.

Could make just the server middleware support promises by adding a function called `useAsyncMiddleware`, that way it is clear that this function is intended to be used with a promise. If you want to programatically use nuxt to add a server middleware that returns a promise then you could use this function too.

Example modifying the Server class:

```ts
  // ...

  async setupMiddleware() {
    // ...

    for (const m of this.options.serverMiddleware) {
      await this.useAsyncMiddleware(m)
    }

    // ...
  }

  async useAsyncMiddleware (middleware) {
    const { route, handle } = async this.resolveAsyncMiddleware(middleware)
    this.app.use(route, handle)
  }

  async resolveAsyncMiddleware (middleware, fallbackRoute = '/') {
    // Ensure middleware is normalized
    middleware = await this._normalizeMiddleware(middleware)

    // Fallback route
    if (!middleware.route) {
      middleware.route = fallbackRoute
    }

    // Resolve final route
    middleware.route = (
      (middleware.prefix !== false ? this.options.router.base : '') +
      (typeof middleware.route === 'string' ? middleware.route : '')
    ).replace(/\/\//g, '/')

    // Strip trailing slash
    if (middleware.route.endsWith('/')) {
      middleware.route = middleware.route.slice(0, -1)
    }

    // Assign _middleware to handle to make accessible from app.stack
    middleware.handle._middleware = middleware

    return middleware
  }

  async _normalizeMiddleware (middleware) {
    // Resolve promise
    if (isPromise(middleware)) {
       middleware = await middleware;
    }

    // Normalize plain function
    if (typeof middleware === 'function') {
      middleware = { handle: middleware }
    }

    // If a plain string provided as path to middleware
    if (typeof middleware === 'string') {
      middleware = this._requireMiddleware(middleware)
    }

    // ...
  }

  // ...
```

This shouldn't break anything because it only adds extra functionality to the server middleware setup. Though functions that use the _normalizeMiddleware function should either return a promise, or an async variant of them should be made. Could even make a function called _normalizeAsyncMiddleware to not break other functions.

**Comment by danielroe** [comment]
This is now implemented with `defineLazyEventHandler` in Nuxt 3/Nitro.
