### ISSUE TITLE
Location template for page 

### ISSUE THREAD

**Issue by lwswnnscrm** [nuxt/nuxt#7818]
### Is your feature request related to a problem? Please describe.
Hi, i have 1 request, i need create locale template for difference location, as an example i have en, fe and cn locations user in my app and in home page i need have some difference block, but the whole page is the same, difference 2-3 block in every location. Are there any solutions for this now? v-if with locale($i18n) too hard to maintain we have 20 locale now. Custom routing create for me 1500-1600 routes. Maybe you can give advice something other?

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
