### ISSUE TITLE
ERROR  Cannot read property 'file' of undefined

### ISSUE THREAD

**Issue by hugo-lovighi** [nuxt/nuxt#7819]
- os: ubuntu 20.04
- nuxt: 2.14.0
- node: 12.18.3
- yarn: 1.22.4

With nuxt 2.14.0 I got an error with client manifest:

```
    if (this.clientManifest) {
        var r = this.preloadFiles.filter(function(e) {
            var t = e.file;
            return ao(t)
        }), n = (this.getUsedAsyncFiles(e) || []).filter(function(e) {
            var t = e.file;
            return ao(t)
        });
        return [r[0]].concat(n, r.slice(1)).map(function(e) {
           var r = e.file; //here
            return '<script src="' + t.publicPath + r + '" defer><\/script>'
        }).join('')
    }
```

It happens only after build & start not in dev mode.

I don't know how can I reproduce this error and I don't know where to start to investigate.
If you would have some leads or tips.

**Comment by clarkdo** [comment]
The attached code looks from vue, I’ll look into this, @kesm0 can you please double check with latest Nuxt and provide us a reproducible repo if possible?

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
