### ISSUE TITLE
confusion and inconsistency with config (mode+target) & cli flags

### ISSUE THREAD

**Issue by flapili** [nuxt/nuxt#7825]
### Is your feature request related to a problem? Please describe.
I, fist thanks for your awesome job
I would like to expose a comprehension problem I had with nuxt with the add of the target property
also according to the documention  build have a --spa flag but there is no ssr flag, it's inconsistent
the target only take effect on universal mode ( when I tested I in 2.13) because in spa mode even if you set the target to server nuxt will build spa with static target (that make sense)
but why add a new property to something which only take effect on 1 mode ? it should be more easy to add a new mode "static" ?

### Describe the solution you'd like
a good solution could be deprecated mode and target and use the cli, `nuxt [action] [mode]` or `nuxt [mode] [action]` depending on what makes the most sense to you and what is the most future-proof.

in parallel we could add a prefixe to dist / cache folders `dist/` -> `[mode]-dist/`, `.[mode]-nuxt/` or in the other way `.nuxt/` -> `.nuxt-[mode]/` one more time depending on what makes the most sense to you and what is the most future-proof.

I think the 2th proposition could help you in internal to serve the good build and it should also help a cache issue when we change for an another mode (delete dist / .nuxt is boring)

thanks for reading :)

**Comment by danielroe** [comment]
This is a helpful point to make, and we're working to improve things. For example: https://nuxt.com/docs/guide/concepts/rendering/. If you have any particular suggestions, we'd welcome ideas or PRs. ❤️
