### ISSUE TITLE
Add event hooks to nuxt-loading component

### ISSUE THREAD

**Issue by btkostner** [nuxt/nuxt#7893]
### Is your feature request related to a problem? Please describe.

I have some async data being loaded in `fetch`. I want to scroll on the page _after_ all content is loaded. The easiest way seemed to be something like `this.$loading.$once('finished')`.

### Describe the solution you'd like

I'd like some events added to the `nuxt-loading` component so people can use it as the source of truth if stuff is still being loaded. The only one I am concerned about is `finished`, but I could see some others added as well.

### Describe alternatives you've considered

Not using the component as the single source of truth. This can be more accurate, but also takes more work. Using the `nuxt-loading` component is fast, has good support with things like axios already, and is pretty simple to use.

**Comment by danielroe** [comment]
Let's track progress via https://github.com/nuxt/nuxt/issues/14221.
