### ISSUE TITLE
nuxtServerInit action for each module in the store

### ISSUE THREAD

**Issue by Soviut** [nuxt/nuxt#7924]
### Is your feature request related to a problem? Please describe.

Since the `this.$config` is not accessible from the `state` in the store, I have to use `nuxtServerInit()`. However, I have several store modules, each requiring some initialization. However, `nuxtServerInit` only works in the root store. This requires all initialization for all modules to be centralized in this single action.

Additionally, the documentation does not make it clear that the `nuxtServerInit` action only works in the root and no warnings are given when you create it in a module.

### Describe the solution you'd like

Each module in the store would be able to have its own `nuxtServerInit()` action defined in it. This would keep all the initialization close to the module and its state, making it easier for developers to reason what is initializing the module.

### Describe alternatives you've considered

Currently, I have my `nuxtServerInit` in the root dispatch init actions in all the other modules.

**/store/index.js**
```javascript
export const actions = {
  nuxtServerInit({ dispatch }) {
    dispatch('module-a/nuxtServerInit')
    dispatch('module-b/nuxtServerInit')
    // etc.
  }
}
```

**Comment by f3ltron** [comment]
Hello @Soviut  I did something similar by calling an init action in my substore and sending it as arguments.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
