### ISSUE TITLE
modern: 'server' without checking User Agent

### ISSUE THREAD

**Issue by nachogarcia** [nuxt/nuxt#7976]
### Is your feature request related to a problem? Please describe.

Right now we're using modern: 'client' to improve performance in our application. We cannot use modern: 'server' since it would get cached in our CDN and if someone visites the web using and old browser, the legacy build would get cached.

We're OK with ditching support for browsers that don't support modules, but in order to do that we would need a modern flag that doesn't take into account User Agent, but only returns the modern build from the server.

### Describe the solution you'd like

A new flag that doesn't check UA or reuse the 'true' one (breaking change).

### Describe alternatives you've considered

Handle this in a layer above the application, maybe cutting off access from the CDN to older browsers and enable modern: 'server'.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
