### ISSUE TITLE
Allow a different transition for each layout like the pages

### ISSUE THREAD

**Issue by romaric-g** [nuxt/nuxt#8049]
### Problem description

Transitions for layouts are always the same, whether it is from A to B or B to A.
It is easily possible to do this with pages by using the parent class of the page in the transition or by specifying a different transition name for each page with the "transition" property.

### Solutions I would like

It would be great to be able to specify a transition property of each layout like the pages .

```
//layouts/blog.vue

<template>
  <div class="blog">
      <nuxt />
  </div>
</template>

<script>
export default {
  transition: {
    name: 'transitionleft',
    mode: 'out-in'
  },
}
</script>
```

Another solution to identify each layout could be to have the possibility to add a class on each div "__layout". This would allow to create a different css transition depending on the incoming or outgoing layout.

```
//Elements rendered

<div id="__nuxt">
  <div id="__layout" class="transitionleft">
    ...
  </div>
  <div id="__layout" class="transitionright layout-enter-active layout-enter-to">
    ...
  </div>
</div>
```

**Comment by DarshGupta16** [comment]
@romaric-g Are you talking about something like a layout transition property? lf so, Nuxt JS already has that: https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-transition#the-layouttransition-property

**Comment by frdrk** [comment]
> @romaric-g Are you talking about something like a layout transition property? lf so, Nuxt JS already has that: https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-transition#the-layouttransition-property

Unless I'm mistaken the layout transition property is set in nuxtConfig and applies too all layouts? I'm too looking for a way to set a different transition for each of my layouts. For example 'fade' for default.vue and 'slide-up-down' for actionsheet.vue.
