### ISSUE TITLE
Allow a transition component to be passed into page.transition

### ISSUE THREAD

**Issue by privatenumber** [nuxt/nuxt#8054]
### Is your feature request related to a problem? Please describe.

I have a library of functional transition components that I can reuse. I'd like to use them for transitioning pages, but I am unable to pass in a transition component to the [page `transition` property](https://nuxtjs.org/api/pages-transition/).

Here's an example of a transition component I have called `FadeTransition.vue`:
```vue
<template functional>
	<transition
		:enter-active-class="$s.fading"
		:leave-active-class="$s.fading"
		:enter-class="$s.transparent"
		:leave-to-class="$s.transparent"
		v-bind="data.attrs"
	>
		<slot />
	</transition>
</template>

<style module="$s">
.fading {
	position: absolute;
	transition: opacity 0.2s ease-in;
}

.transparent {
	opacity: 0;
}
</style>
```

### Describe the solution you'd like
Possibly an `component` property on the `transition` hash to pass in the path to the transition component:
```js
{
    transition: {
        component: '~/components/FadeTransition.vue'
    }
}
```

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
