### ISSUE TITLE
`build.cache:true` does not work together with `build.extractCSS:true` in static mode

### ISSUE THREAD

**Issue by simplenotezy** [nuxt/nuxt#8061]
### Versions

- nuxt: v2.14.0
- node: v12.18.3

### Steps to reproduce
1. Set `cache:true` in `build` configuration
2. Set `extractCSS:true` in `build` configuration
3. Run `yarn nuxt generate`
4. First time it will work and look as it should
5. Run `yarn nuxt generate` again; it will work fine, still.
5. Go back and update your `nuxt.config.js` file (e.g. add a new line), so full rebuild will be made
6. Run `yarn nuxt generate`
7. Visit your site. No stylesheets have been injected, and Times New Roman font everywhere.
8. Set `cache:false` in `build` configuration
9. Run `yarn nuxt generate`
10. Visit your site - it works fine

### What is Expected?
Stylesheets should be loaded when `extractCSS:true` even though `cache:true` is also set

### What is actually happening?
It works the first time, but when you rebuild (e.g. made a change to nuxt.config.js) it generates your site without any stylesheets at all.

**Comment by Snack-X** [comment]
This is same issue as #7446, along with #8048.

**Comment by VRuzhentsov** [comment]
Still can reproduce

**Comment by clarkdo** [comment]
Hi, this issue is from https://github.com/nuxt/nuxt.js/pull/5004, the reason is that `extract-css-chunks-webpack-plugin` doesn't work well with `thread-loader` because `thread-loader` will create separate context which can't accessed by `extract-css-chunks-webpack-plugin`.

The issue has been a while, I'll look into in again to see if `thread-loader` has changed anything.

**Comment by clarkdo** [comment]
I just checked, looks `thread-loader` is still not working with `extract-css-chunks-webpack-plugin` and there has been an issue opened there https://github.com/webpack-contrib/thread-loader/issues/66, let's keep tracking that issue.

**Comment by Snack-X** [comment]
Yes, `parallel` and `extractCSS` does not work together, and it has already been addressed with linked PR. But is it really related with `cache` option?

If so, combination of `parallel` and `extractCSS` options can be disabled, just like #5004.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
