### ISSUE TITLE
Don't emit window.___NUXT___ if it is kind of empty

### ISSUE THREAD

**Issue by shrpne** [nuxt/nuxt#8109]
### Is your feature request related to a problem? Please describe.

Now I'm getting 
```html
<script>window.__NUXT__={config:{},staticAssetsBase:void 0}</script>
```
in my production SPA biuld. (Nuxt 2.14.6)

As you can see it doesn't contains any useful data.

### Describe the solution you'd like

I think it's better fully omit such `<script>` tag. And only let it out if there are really any useful data.

1. Less bytes to transfer over the network, less JS to execute.
2. One less script to generate inline CSP hash. (Honestly this one why i'm here. Browser warns me, that it refused to execute such script, until I add valid sha256 hash of it to the SCP directive)

**Comment by danielroe** [comment]
Closing as, in Nuxt 3, we always rely on this data (for example, it tells us whether the response was server rendered or not).
