### ISSUE TITLE
Preload resources set crossorigin separately between css and js.

### ISSUE THREAD

**Issue by HuberTRoy** [nuxt/nuxt#8113]
### Is your feature request related to a problem? Please describe.

On Chrome If I set the preload css resources crossorigin it will give an warning and load it twice.

https://developers.google.com/web/updates/2017/12/modulepreload#ok_so_why_doesnt_link_relpreload_work_for_modules 

### Describe the solution you'd like
```
crossorigin: {
    css: null,
    js: 'use-credentials'
}
```

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
