### ISSUE TITLE
Dynamic nuxt module supporting in static mode.

### ISSUE THREAD

**Issue by Fnxxxxo** [nuxt/nuxt#8119]
### Is your feature request related to a problem? Please describe.

I want to develop a portal app with dynamic menus to integrate other modules. Currently, all sub modules are added in nuxt.config and built to activated, which causes the whole to build and deploy when any module changes.
It will be great for nuxt to support dynamic loading modules. 

### Describe the solution you'd like

A register API like `this.$nuxt.registerModule(module)`. Partial functions like router, pages, layouts, stores, and middlewares are loaded and registered. I can load this module through async components or third-party CDN network.

### Describe alternatives you've considered

I tried requirejs. It load components I want, but lack the context of nuxt. I also dont know how to dynamic register middlewares and layouts.

### Additional context

Our applications built on yarn workspace. But package independently.

**Comment by danielroe** [comment]
Modules in Nuxt 3 are build-time only, so I don't think we can support this within Nuxt itself. But as for registering features, I think this should be very possible for any individual module to enable. So you would enable the module as normally but pass a configuration option to it, and it would inject a minimal function that you could call to lazy load further features.
