### ISSUE TITLE
warn if values from private `runtimeConfig` are rendered in HTML

### ISSUE THREAD

**Issue by hikaruworld** [nuxt/nuxt#8120]
### Versions

- nuxt: v2.14.6
- node: v14.6.0

### Reproduction

https://codesandbox.io/s/trusting-euclid-s9ls2

### Steps to reproduce
1. `yarn generate`
2. `grep secretKey dist/index.html`

### What is Expected?
`privateRuntimeConfig` does not appear on the source code.

### What is actually happening?

```
$ grep "secretKey" dist/index.html 
  "secretKey": "fizz"
```

html is...

```
<h2 class="subtitle" data-v-3ef5f348>{
  "publicKey": "buzz",
  "http": {
    "baseURL": "http://localhost:50417/"
  },
  "secretKey": "fizz"
}</h2>
```

<details open>
<summary>screenshot</summary>
<br>
<img width="783" src="https://user-images.githubusercontent.com/1309468/94359852-614e5880-00e4-11eb-9cde-3790cae1fc1c.png">
</details>

**Comment by manniL** [comment]
This is indeed an "expected" behavior!

`privateRuntimeConfig` values are only available on the server side. This does not mean that they can't be "leaked" somehow. When using SSR, the HTML will be generated on the server-side (hence the name). When you expose `$config` directly in your template, then the server-generated HTML will contain all `privateRuntimeConfig` values. Thus, it is still important to be careful with `$config`.

**Comment by hikaruworld** [comment]
Thank you for your response.
I recognized it as a specification. 😄 

If possible, it would be good if we could address the following

* Add to the documentation.
* Warn during development and build time (if you are using $config as is).

**Comment by manniL** [comment]
> Thank you for your response.

You are welcome! 😋
 
>     * Add to the documentation.

Great idea! PR welcome 👍🏻
 
>     * Warn during development and build time (if you are using $config as is).

This could be done by using an eslint rule maybe? 🤔

**Comment by pi0** [comment]
Nice idea @hikaruworld for warnings. Actually there is a prototype for `@nuxt/audit` when introduced runtimeConfig but it is not high priority

![image](https://user-images.githubusercontent.com/5158436/94683291-8f22df80-0326-11eb-8460-f791b717ae01.png)

**Comment by hikaruworld** [comment]
> Great idea! PR welcome 👍🏻

I'll try it!

>  introduced runtimeConfig but it is not high priority

This was exactly what I was hoping for.

I'm looking forward to it!

**Comment by MentalGear** [comment]
> Actually there is a prototype for `@nuxt/audit` when introduced runtimeConfig
I posted a similar issue #9087 regarding secruity. Could you point me to this package @pi0 ?

**Comment by MentalGear** [comment]
I might be able to help with this, but can't find @nuxt/audit. @pi0

**Comment by NIO-ADR** [comment]
MetalGear 


Sent from the all new AOL app for iOS


On Monday, April 5, 2021, 4:58 AM, MentalGear ***@***.***> wrote:




I might be able to help with this, but can't find @nuxt/audit. @pi0

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
