### ISSUE TITLE
Could generate take the build files of `nuxt build`?

### ISSUE THREAD

**Issue by VesterDe** [nuxt/nuxt#8142]
My problem are deployments. 

In order to generate, my backend already has to be running the new version of the code, so it returns some data from its API for the generation, so generation must be a post-deploy step. But generation takes several minutes because it usually includes a rebuild, since frontend code changes a lot. So for those few minutes, the old generated files are used, which may break if there were API changes for instance.

It would cut generate time in half if I were able to run `nuxt build` in my deployment build step, and then run `nuxt generate` post deploy, in a way that doesn't run `build` for the generate step.

Currently that isn't possible is it? Running `nuxt generate` will always also include `build` if the frontend files have changed, even if I run `nuxt build` immediately beforehand, right?

I find that a bit counter-intuitive, but would really benefit from an option to generate and force use existing build files, no matter what. I first thought `--no-build` does that, but it's different.

Thanks.

**Comment by danielroe** [comment]
@VesterDe You say that `--no-build` doesn't work for this. Can you clarify why this behaviour doesn't work for you, or give an example repo where `--no-build` doesn't produce the right behaviour?

**Comment by VesterDe** [comment]
Hm, sure, I'll see what I can wrangle up, but for now I leave you with some more info:

```
npx nuxt generate --dotenv ../.env --no-build

 ERROR  (node:362490) ExperimentalWarning: The fs.promises API is experimental

Parsed 4 files in 0,4 seconds
Doing webpack rebuild because assets/variables.scss modified
Production build
Bundling for server and client side
Target: full static

```

I had just run `nuxt generate`, and then all I did was change `variables.scss` a bit, and despite adding `--no-build` it decided it to rebuild.

Then, I deleted `node_modules/.cache` and ran `npx nuxt build --dotenv ../.env`. My expectation once that was finished was that, if I immediately ran `generate`, it would not build, because it just had. However, 

```
npx nuxt generate --dotenv ../.env --no-build

 ERROR  (node:373494) ExperimentalWarning: The fs.promises API is experimental

Parsed 4 files in 0,3 seconds
Production build
Bundling for server and client side
Target: full static

 WARN  Components directory not found: ~/components/global

✔ Builder initialized
✔ Nuxt files generated


✔ Client
  Compiled successfully in 34.27s

✔ Server
  Compiled successfully in 17.17s

```

It still rebuild the thing again? That's concretely what I'm after, skipping that build. And I know it is possible to skip it, because running `generate` twice in a row does that (provided there are not file changes).

Thanks.

**Comment by dario-valles** [comment]
Same happening to me,

Problem is on buid.js:
```
 if (nuxt.options.mode === MODES.spa && nuxt.options.target === TARGETS.server && cmd.argv.generate !== false) {
      // Build + Generate for static deployment
      const generator = await cmd.getGenerator(nuxt)
      await generator.generate({ build: true })
    } else {
      // Build only
      const builder = await cmd.getBuilder(nuxt)
      await builder.build()

      const nextCommand = nuxt.options.target === TARGETS.static ? 'nuxt generate' : 'nuxt start'
      consola.info('Ready to run `' + (nextCommand) + '`')
    }
```

It's allways pass build: true

**Comment by VesterDe** [comment]
Well, I won't go into making a reproducible example if the code doesn't even theoretically support that...

I hope one day it gets added. I think issue #8176 is asking the same thing.

**Comment by widmerin** [comment]
Is there a way to run `nuxt generate` without build for Nuxt 3?
We have the same idea that we want to run `nuxt build` only once during the deployment and then to save time run `nuxt generate` without a new nuxt build, with a cronjob. 
Is there an other way to only generate the sites in Nuxt 3?

**Comment by danielroe** [comment]
This indeed is the plan. Let's track in https://github.com/nuxt/nuxt/issues/14605 for now.
