### ISSUE TITLE
Incremental Static Generation on the horizon?

### ISSUE THREAD

**Issue by saturnonearth** [nuxt/nuxt#8176]
A way to be able to generate pages statically but also update them live without a rebuild would be amazing. Some similar to the Next.js solution in 9.4. You can use methods such as fetch but this requires data to be grabbed every time the page is loaded, slowing it down.

**Comment by w3b-dev** [comment]
I would also like to request this

**Comment by thomasjwalsh** [comment]
Would also like to request this

**Comment by danielroe** [comment]
This is now implemented in Nitro via `routeRules`: https://nitro.unjs.io/config#routerules.
