### ISSUE TITLE
Crawler should tell where it found link to 404 path

### ISSUE THREAD

**Issue by iBobik** [nuxt/nuxt#8184]
### Is your feature request related to a problem? Please describe.

In CMS there are broken links and Nuxt's crawler correctly fails when it tries to render it. But it does not tell where it found this link.

```
 ERROR  Error generating route "/todo": Page not found   
```

### Describe the solution you'd like

When there is non existing path it should print a path where it found it.

### Describe alternatives you've considered

Tester on a CMS side :-/

**Comment by aj-dev** [comment]
We also run into the same issue with Contentful when someone changes the link and route generation fails in Nuxt. It would be useful to get more info on where the link was found int the DOM, like DOM path from the document root. Maybe a Vue component name could also be included in the error message.

**Comment by iBobik** [comment]
@danielroe The same thing happens also on the 3.x.

**Comment by danielroe** [comment]
This should be resolved in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/), or in the next Nitro release.

Let me know if not and I'll reopen.
