### ISSUE TITLE
Add route/query info to $fetchState

### ISSUE THREAD

**Issue by enkot** [nuxt/nuxt#8202]
### Is your feature request related to a problem? Please describe.

I have keep-alived page (`/characters`) which uses query based filters. If apply the filter - `/characters?species=Alien`, then go to main page and then back to `/characters` - filtered (cached) results shown, not all. 

Example: https://codesandbox.io/s/morning-sun-zh98i?file=/pages/characters/index.vue

And that is the expected behavior 👍 . To fix that I save route query on the last fetch call and compare it with current route query in `activated` hook, if not the same - call `$fetch()` (you can see commented block in `pages/characters/index.vue`):

```js
data() {
  return {
    lastQuery: {},
  }
},
activated() {
  if (JSON.stringify(this.$route.query) !== JSON.stringify(this.lastQuery))
    this.$fetch();
},
async fetch() {
  // ...
  this.lastQuery = this.$route.query
},
watch: {
  '$route.query'() {
    if (!this._inactive) this.$fetch()
  }
},
```

### Describe the solution you'd like

Wouldn't it be a good idea to have route/query info (active on last `$fetch()` call) in `$fetchState` alongside current `pending`, `error`, `timestamp` fields? 

```js
activated() {
  if (JSON.stringify(this.$route.query) !== JSON.stringify(this.$fetchState.query))
    this.$fetch();
},
```

On the other hand it's also not good to keep in memory a lot of route data for every cached component.

 
### Describe alternatives you've considered

The other workaround what I see to make caching properly work with query filters is using `:key="$route.fullPath"` or something, but it feels like not the best solution. Maybe there is a better solution than a custom "lastQuery"?

**Comment by mahammad-sixberries** [comment]
any updates?

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
