### ISSUE TITLE
Option to generate route files without ".html"

### ISSUE THREAD

**Issue by camhart** [nuxt/nuxt#8212]
### Is your feature request related to a problem? Please describe.
If you attempt to deploy a nuxt static generated site to AWS s3 & Cloudfront, then Cloudfront *only* gets the correct prerendered page if the route in the URL matches the *exact* file name.

For example, stay I have a nuxt static generated site with the following routes:
* /
* /about
* /faq

If I have generate.subFolders set to true, then when using cloudfront, the follow URLs will load the prerendered page.
* mysite.com/index.html
* mysite.com/about/index.html
* mysite.com/faq/index.html

However when you hit those pages directly, the Vue/Nuxt app doesn't mount/hydrate properly..  There are no error messages--it simply just doesn't work.

However *if* you create a AWS Lambda Cloudfront Origin Request function, and have it redirect mysite.com/about to mysite.com/about/index.html, then the Vue/Nuxt app *does* mount/hydrate properly.  Here's an example of what that function looks like:

```
exports.handler = async (event, context) => {
    
    let request = event.Records[0].cf.request
    let olduri = request.uri
    
    let newuri = olduri.replace(/\/$/, '\/index.html')                  //redirect anything ending with /, to /index.html
    newuri = newuri.replace(/about$/, 'about/index.html')      //redirect /about to /about/index.html
    newuri = newuri.replace(/faq$/, 'faq/index.html')              //redirect /faq to /faq/index.html
    
    console.log(`old = ${olduri}, new = ${newuri}`)
    
    request.uri = newuri


    return request;
};
```

This resolves the issue and allows everything to work properly.  If you navigate to mysite.com/about everything works great.   **However it sucks to have to maintain that lambda function.** 

If you set generate.subFolders to false, the issue still exists.

### Describe the solution you'd like

Add a new generate property within nuxt.config.js, that allows you to specify the file extensions for the pages except for the root index.html.  That way you could do:

```
generate: {
  subFolders: false,
  nonRootPageExtension: '' //overrides from '.html' to nothing
}
```

Then when statically generated, the actual files would look like this
```
/index.html   -> cloudfront/s3 already has easy support for redirecting 403's to index.html.  Leave this as is since we can't have a file with no name for the root.
/about -> this about file would normally be "about.html", but because nonRootPageExtension is set to '', it's just "about"
/faq -> this about file would normally be "faq.html", but because nonRootPageExtension is set to '', it's just "faq"
```

### Describe alternatives you've considered

Well the lambda function works as is.  Alternatively you could do post processing and rename all the prerendered route pages to cut off the '.html'.

### Additional context

https://nuxtjs.org/faq/deployment-aws-s3-cloudfront/ needs to get updated, as it doesn't point out that navigating directly to your page will actually first load index.html then the clientside vue app switches to the page you intended to go to.  This results in:

- a flicker
- slower page loads
- worse SEO results
- etc

**Comment by lielfr** [comment]
Hi,
I'd like to work on that one if it's still available.

**Comment by clarkdo** [comment]
Regarding to change generated file extension https://github.com/nuxt/nuxt.js/pull/8222#discussion_r508541835:

> You can easily solve your problem by using hook `generate:page`:

```js
// nuxt.config.js
export default {
  hooks: {
    generate: {
      page(page) {
        page.path = page.path.replace(/html^/, '...')
      }
    }
  }
}
```

**Comment by riccardofuziercayla** [comment]
> Regarding to change generated file extension [#8222 (comment)](https://github.com/nuxt/nuxt.js/pull/8222#discussion_r508541835):
> 
> > You can easily solve your problem by using hook `generate:page`:
> > ```js
> > // nuxt.config.js
> > export default {
> >   hooks: {
> >     generate: {
> >       page(page) {
> >         page.path = page.path.replace(/html^/, '...')
> >       }
> >     }
> >   }
> > }
> > ```

This works for the purpose with a small difference in the regex. It should be `/html$/` instead of `/html^/`.

Unfortunately it does not solve the specific problem with AWS S3 for me..
If you upload file to S3 without extension it will not take te correct `Content-Type`, this is how I modified the gulpfile.js to make it work:

```js 
.pipe(
      rename(function (path) {
        if (path.basename !== 'index' && path.extname === '.html') {
          path.dirname = 'html'
          path.extname = ''
        }
      })
    )
    .pipe(
      awspublishRouter({
        routes: {
          '^html/(.*)': {
            key: '$1',
            headers: {
              'Content-Type': 'text/html; charset=utf-8',
            },
          },
          '^.+$': '$&',
        },
      })
    )
```

With `gulp-rename` I removed the .html extension and moved the file to a temp folder html/, which helps me to better identify the files in the next step. 
Then with `gulp-awspublish-router` I get the files inside html/ folder, add `Content-Type': 'text/html; charset=utf-8'` and then move them from html/ to root folder

Hope it helps

**Comment by xueyongg** [comment]
Any updates to this feature? (: Loving nuxt and hope to achieve good SEO with nuxt static mode with AWS S3 deployment

**Comment by ChristianGerdes** [comment]
Any progress on this issue?

**Comment by danielroe** [comment]
This is now possible in Nuxt 3/Nitro by customising the file name in the `prerender:generate` nitro hook.

We can also likely improve this further by creating a Nitro preset for deploying to S3 + Cloudfront. (Feel free to open a feature request in https://github.com/unjs/nitro.)

**Comment by pi0** [comment]
Tracker issue: https://github.com/unjs/nitro/issues/607
