### ISSUE TITLE
Can we export nuxt project as web components ?

### ISSUE THREAD

**Issue by bnping** [nuxt/nuxt#8227]
Hi, 
 In vue js, we can export the entire projet as web component and import it in other projets.

 Can we export nuxt project as web component ?

**Comment by b01110011** [comment]
As npm module?

**Comment by bnping** [comment]
@b01110011  yes. Do you know please

**Comment by b01110011** [comment]
If I understand your question correctly:
Registry your project in npm, then install it and run.
Something like
```
cd node_modules/project_name
npm run build
npm run start
```
above commands, may write in package.json as script

**Comment by bnping** [comment]
@b01110011 inside project_name, i put my nuxt project ?

**Comment by b01110011** [comment]
project_name is your name npm module

**Comment by bnping** [comment]
maybe my question not claire. I want to export my nuxt project  as npm module or web components.

**Comment by b01110011** [comment]
this module must run on localhost? as any other application, but only as npm dependency?

**Comment by bnping** [comment]
as npm dependency.

**Comment by b01110011** [comment]
then the instruction above
____________________________________
If your module has serverMiddleware you need rewrite it as cjs module (commonJs) or you catch fatal errors
