### ISSUE TITLE
Proper documentation or blog for Nuxt production level set up

### ISSUE THREAD

**Issue by ramsane** [nuxt/nuxt#8247]
I am trying to create a boilerplate for nuxt projects with e2e testing with cypress, and unit testing, tailwind etc. with all the things that are present in this repository.

https://github.com/debs-obrien/nuxt-boilerplate-project

But, there were few issues with the existing project and this is not working with the latest version of cypress and few other packages. But While doing so, I am facing few issues while writing unit tests with jest. Few of them are

- Unable to import dynamic imports of  nuxt components in the unit tests. It is saying like unknown component. 
- Variables like $router are not available. For example, I am  using this in my code to push some path to the router. 
```js
...
  mounted() {
    this.$router.push(this.tabs[0].path)
  },
...
```
But when I mount the component, it is giving me error saying that push is called on undefined variable. basically $router is undefined or not accessible.
I've tried importing components and using jest.setup.js file. But those are not working. I've tried for few days and gave up. If we can have clear documentation on how to setup jest with nuxt and use all the modules like Vuex store, nuxt modules etc.., it would be helpful.

Any help from the community is very much appreciated. I may not have proper knowledge on jest. give me resources where I can learn this from with the nuxt(not vue in general).

Thank you in advance.

I am using vue testing library instead of vue test utils to test the components.

**Comment by drewbaker** [comment]
What is `this.tabs[0].path`?

**Comment by ramsane** [comment]
I wrote a Tabs component where we can provide the path for each tab along with it's name. It is just a valid router path. I was trying to push that to that to the router to redirect the page. The error is that it is not able to get $router variable. 

Today morning, I just passed empty list ([]) as router to the options object. Now it is not giving any error. Still, a good documentation would always be helpful.

**Comment by msmsimondean** [comment]
Hi @ramsane, you can mock `$route` like this: 

```javascript
import { createLocalVue, mount } from '@vue/test-utils'
import VueMeta from 'vue-meta'
import Index from '@/pages/index.vue'

const localVue = createLocalVue()
localVue.use(VueMeta, { keyName: 'head' })

describe('Index', () => {
  const route = {
    params: {
      example: 'value',
    },
  }
  let wrapper
  const createWrapper = () => {
    wrapper = mount(Component, {
      localVue,
      mocks: {
        $route: route,
      },
    })
  }

  afterEach(() => {
    wrapper.destroy()
    wrapper = null
  })

  test('is a Vue instance', async () => {
    createWrapper()
    expect(wrapper.isVueInstance).toBeTruthy()
  })
```

**Comment by msmsimondean** [comment]
@ramsane you can also mock `fetch()` or `asyncData()`.  See https://github.com/testing-library/vue-testing-library/issues/92#issuecomment-732078213 as a `fetch()` example

**Comment by ramsane** [comment]
Thank you so much. So, we can mock anything and everything that is not part of the component but, which is required or accessed in the component. Got it. Thanks once again.

**Comment by danielroe** [comment]
I'm closing this as it seems the questions you had were answered. Please do feel free to open any new questions with GitHub Discussions or on the Nuxt Discord.
