### ISSUE TITLE
Re-generation for static site by overriding

### ISSUE THREAD

**Issue by nicolashmln** [nuxt/nuxt#8261]
### Is your feature request related to a problem? Please describe.

When nuxt generates a large static site, rebuilds can take a lot of time.

### Describe the solution you'd like

If nuxt don't have to rebuild the javascript and just generate some content, maybe all the routes passed in the `routes` parameter can be overriden without deleting the whole `dist` folder.

Maybe somehow, we can pass parameters to the `routes` function to select only the routes to be re-generated.

We could add another param to be sure we want to override the dist folder.

```js
import axios from 'axios'

export default {
  generate: {
    override: true,
    routes(params) {
      // We select only the routes to be re-generated
      return axios.get(`https://my-api/users?status=${params.status}`).then(res => {
        return res.data.map(user => {
          return '/users/' + user.id
        })
      })
    }
  }
}

```

That way we don't have downtimes and the generate is quicker

### Describe alternatives you've considered

Might be a solution in between those #7813 and #8176

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/6138.
