### ISSUE TITLE
Allow to use .babelrc along with auto injecting Nuxt setup (recently broken)

### ISSUE THREAD

**Issue by IlyaSemenov** [nuxt/nuxt#8268]
### Is your feature request related to a problem? Please describe.

I use a mono repo for frontend (with Nuxt) and backend. Both my frontend and backend use Babel to compile. I want to reuse `.babelrc` for both frontend and backend, in particular for common setup of Babel plugins such as `@babel/proposal-decorators` or `module-resolver`.

I only want Nuxt to inject its `@nuxt/babel-preset-app` on top of `.babelrc` so that, for instance, client code compiles to `{ ie: 9 }`.

This used to work just fine in Nuxt 2.11:

```ts
export default {
	build: {
		babel: {
			babelrc: true,
			presets({ isServer }) {
				const targets = isServer ? { node: 'current' } : { ie: 11 }
				return [[require.resolve('@nuxt/babel-preset-app'), { targets }]]
			},
```

After I upgraded to Nuxt 2.14, this setup broke with:

```
 ERROR  in ./.nuxt/client.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: .presets must be an array, or undefined
    at assertArray (/xxx/node_modules/@babel/core/lib/config/validation/option-assertions.js:150:11)
```

I've read the new documentation and updated my setup to:

```ts
	build: {
		babel: {
			babelrc: true,
			presets(_env, [preset, options]) {
				return [[preset, options]]
			},
```

which didn't make any difference.

I traced the problem to this recent PR: #7297 and in particular these lines:

https://github.com/nuxt/nuxt.js/blob/baf94d31f300b3fdeae1da12af7e944016fe99b3/packages/webpack/src/config/base.js#L106-L108

### Describe the solution you'd like

I'm not sure what would be the best. It could be an additional option like `config.build.babelrc = "merge"` (or `config.build.babel.babelrc = "merge"`), which would restore the old behaviour.

### Describe alternatives you've considered

At the moment, I can't come up with any.

### Additional context

I don't really think my scenario is an edge case. I think using the same repo for frontend and backend is a fairly popular setup. Using babel for backend is not yet very popular, however it's a trend in Typescript community, it's even suggested by Microsoft itself: https://www.typescriptlang.org/docs/handbook/babel-with-typescript.html

The new logic of `config.build.babel.babelrc = true` is basically useless because it will generate the same build for client & server, which no one needs. I understand that you had reasons for this change, however please also consider reasons for the old behaviour as well.

**Comment by IlyaSemenov** [comment]
FWIW, I ended up with converting my `.babelrc` to `babel.config.js`, and doing this in `nuxt.config.ts`:

```ts
import babelrc from '../../babel.config'

const config: NuxtConfig = {
  build: {
    babel: {
      // can't use babelrc: true, see https://github.com/nuxt/nuxt.js/issues/8268
      plugins() {
        // Must be a function. Simply doing plugins: babelrc.plugins leads to this error:
        // Maximum call stack size exceeded (While processing: "/xxx/node_modules/@nuxtjs/composition-api/lib/babel.js") (While processing: "/xxx/node_modules/@nuxtjs/composition-api/lib/babel.js") ...
        return babelrc.plugins
      },
    },
```

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
