### ISSUE TITLE
drop node@8.x support and update dependencies

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt#8327]
Currently, minimum supported node.js version for nuxt@2 is 8.x which EOL since Jan 2020 and not receiving any security updates. Since more and more dependencies are upgrading to minimum of 10.x it makes sense we upgrade minimum version support in a minor release for nuxt2. 

([here](https://github.com/nuxt/nuxt.js/blob/92a06615d01155b2db3abe5ea8629ae03ee3cb2a/renovate.json#L8) is full list of ignored dependencies:)

Below dependencies that need node@10 are listed. They have also other breaking changes so should check one by one to ensure nuxt breaking nuxt projects by upgrade.

- [x] execa (current: 3)
    - [https://github.com/sindresorhus/execa/releases/tag/v4.0.0](https://github.com/sindresorhus/execa/releases/tag/v4.0.0)
- [x] pify (current: 4)
    - https://github.com/sindresorhus/pify/releases/tag/v5.0.0
- [x] file-loader (current: 4)
    - [https://github.com/webpack-contrib/file-loader/releases/tag/v5.0.0](https://github.com/webpack-contrib/file-loader/releases/tag/v5.0.0)
    - https://github.com/webpack-contrib/file-loader/releases/tag/v6.0.0
- [x] url-loader (current: 2)
    - [https://github.com/webpack-contrib/url-loader/releases/tag/v3.0.0](https://github.com/webpack-contrib/url-loader/releases/tag/v3.0.0)
    - https://github.com/webpack-contrib/url-loader/releases/tag/v4.0.0
- [x] fs-extra (current: 8)
    - [https://github.com/jprichardson/node-fs-extra/blob/master/CHANGELOG.md#900--2020-03-19](https://github.com/jprichardson/node-fs-extra/blob/master/CHANGELOG.md#900--2020-03-19)
- [x] chalk (current: 3)
    - [https://github.com/chalk/chalk/releases/tag/v4.0.0](https://github.com/chalk/chalk/releases/tag/v4.0.0)
- [x] wrap-ansi (current: 6)
    - [https://github.com/chalk/wrap-ansi/releases/tag/v7.0.0](https://github.com/chalk/wrap-ansi/releases/tag/v7.0.0)
- [x] terser-webpack-plugin (current: 2)
    - [https://github.com/webpack-contrib/terser-webpack-plugin/releases/tag/v3.0.0](https://github.com/webpack-contrib/terser-webpack-plugin/releases/tag/v3.0.0)
    - https://github.com/webpack-contrib/terser-webpack-plugin/releases/tag/v4.0.0
    - ~~https://github.com/webpack-contrib/terser-webpack-plugin/releases/tag/v5.0.0~~ (wp@4 support dropped)
- [x] memory-fs@0.5.0 (deprecated - current: 0.4.x)
    - [https://github.com/webpack/memory-fs/releases/tag/v0.5.0](https://github.com/webpack/memory-fs/releases/tag/v0.5.0)
- [x] sass-loader (current: 8)
   - https://github.com/webpack-contrib/sass-loader/releases/tag/v9.0.0
   - https://github.com/webpack-contrib/sass-loader/releases/tag/v10.0.0-rc.0
- [ ] css-loader (current: 3)
   - [x] https://github.com/webpack-contrib/css-loader/releases/tag/v4.0.0
   - [ ] https://github.com/webpack-contrib/css-loader/releases/tag/v5.0.0
- [x] node-sass (current: 4)
   - https://github.com/sass/node-sass/releases/tag/v5.0.0
- [ ] postcss (current: 7)
  - https://github.com/postcss/postcss/releases/tag/8.0.0
- [ ] postcss-import (current: 12)
  - https://github.com/postcss/postcss-import/releases/tag/13.0.0
- [ ] postcss-loader (current: 3)
   -  https://github.com/webpack-contrib/postcss-loader/releases/tag/v4.0.0
- [ ] postcss-url (current: 8)
  -  https://github.com/postcss/postcss-url/releases/tag/v9.0.0
  - https://github.com/postcss/postcss-url/releases/tag/10.0.0
- [x] thread-loader (current: 2)
  - https://github.com/webpack-contrib/thread-loader/releases/tag/v3.0.0
- [x] webpack-dev-middleware (current: 3)
   - https://github.com/webpack/webpack-dev-middleware/blob/master/CHANGELOG.md#400-2020-10-28

**Comment by Tragio** [comment]
Hello 😄  I was wondering why to upgrade to Node 10 since it will not be longer supported in 5 months (2021-04-30). Node 12 will enter Maintenance LTS at the end of this month (2020-11-30). Just asking because I saw the Node schedule page a few days ago, I haven't checked the compatibility of the dependencies or the changes required to it. Good job in bringing this PR 🚀

**Comment by pi0** [comment]
Hey @Tragio. Actually it is a totally right point. Also dependencies like tailwind are requiring 12+. This issue tracker is only for core package and all dependencies above require 10+ so there is no point of forcing users by `engine` field (unless being necessary in the future). Environments like CSB may still use node 10 by default now.

**Comment by websitevirtuoso** [comment]
Waiting Upgrading. Tried to upgrade sass to 10 version got an error

**Comment by danielroe** [comment]
A bit in awe of the organisation of this issue here. Closing as we have raised minimum node version for Nuxt 2 to 14.18 in 2.16.
