### ISSUE TITLE
additional props for keep-alive to specify the pages

### ISSUE THREAD

**Issue by M-Barari** [nuxt/nuxt#8360]
### Featured

additional prop for keep-alive to specify pages that needs to be kept alive. as right now all pages get kept alive, but it is not needed (and cause problems) on some pages! for example on my search page my route query differ but still gets the previous result when come to page again from a different search!

### Solution

just like `:keep-alive-props="{max: 10, exclude: component}"` add exclude and include for pages too!

### Describe alternatives you've considered

i tried to use `v-if="myPageRoute"` on `<Nuxt />` to check if i'm on excluded page, no keep-alive, but didnt work.

i also moved all my codes to a component and excluded  that component, but as that had branched child components, didn't work either.

**Comment by carljustineoyales** [comment]
it also affects the savedposition on scrollbehavior

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
