### ISSUE TITLE
nuxt generate doesn't create .nuxt folder.

### ISSUE THREAD

**Issue by sugoidesune** [nuxt/nuxt#8365]
### Versions

- nuxt: ^2.14.6
- node: 12.14.1

### Reproduction
I think the case is very simple/

### Steps to reproduce
`nuxt generate`

### What is Expected?
nuxt generate creates the .nuxt folder before generating pages in dist

### What is actually happening?
nuxt generate keeps `.nuxt` in memory. and does not create the folder and files.

### Why is this important?
I think it would be nice to keep the behavior uniform. Since `nuxt generate` is clearly going through the build steps aswell, one would assume the `.nuxt` folder is created aswell.

#### Usecase:
I am reusing files created by modules in my `nuxt generate` script. 
The `.nuxt` folder is usually present because of `nuxt dev` but missing during `nuxt generate`
It took quite a while to debug why the deployment was failing remotely.

**Comment by sugoidesune** [comment]
I think this should be relabled to feature request. sry

**Comment by danielroe** [comment]
You can find the folder in Nuxt 2 in `node_modules/.cache/nuxt`. In Nuxt 3 it's not quite so relevant as most of the build dir is in memory.
