### ISSUE TITLE
[Feature-Request] Change Nuxt messages option during runtime (Especially 404 )

### ISSUE THREAD

**Issue by AbdallahAlhaddad** [nuxt/nuxt#8375]
### The problem is:
I have several `404 not found` custom errors I want them to be translated:
- blog not found
- page not found
- ...etc.

For **dynamic pages**, I'm using `asyncData` for my api calls, and passing translated errors from it like below:
```js
   // ~/pages/blogs/_slug.vue
  async asyncData({ ..., error }) {
    try {
       // get blogs here
    } catch (err) {
      error({ statusCode: 404, message: app.i18n.t('notFound.blog') })
    }
  }
```
And Displaying `message` & `status code` in `Error.vue`.
-  This works fine unless the route is a **static page**, as I didn't find a way to change the default `404` message except in `nuxt.config.js` message object (will be one language and don't fit my needs) as shown below:

```js
//nuxt.config.js
export default {
  messages: {
      loading: 'Loading...',
      error_404: 'This page could not be found',
      server_error: 'Server error',
      back_to_home: 'Back to the home page',
      server_error_details: 'An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.',
      client_error: 'Error',
      client_error_details: 'An error occurred while rendering the page. Check developer tools console for details.'
      //...
  }
}
```

As a workaround, I handled it in `Error.vue` **errorData computed property** below but its hacky and future bug prone:
```html
<template>
  <div>
    <span>{{ errorData.statusCode }}</span>
    <span>{{ errorData.message }}</span>
  </div>
</template>

<script>
export default {
  layout: 'empty',
  props: {
    error: {
      type: Object,
      default: null,
    },
  },
  computed: {
    errorData() {
      const message =
        this.error.message === 'This page could not be found' // hacky and bug prone if Nuxt change the message in the future.
          ? this.$t('notFound.page')
          : this.error.message
      return { message, statusCode: this.error.statusCode }
    },
  },
}
</script>
```

### Solution:
The ability to change nuxt messages options during runtime (At least `messages.error_404`)

**Comment by danielroe** [comment]
This makes a lot of sense. In Nuxt 3 we no longer have these default messages (or, rather, the error page can be completely replaced with `error.vue`) so I think we can close this as completed.
