### ISSUE TITLE
Merge page meta into $route.meta

### ISSUE THREAD

**Issue by ezequidias** [nuxt/nuxt#8377]
### Versions

- nuxt: 2.14.6
- node: 14.6.0

### What problem does this feature solve?

By merging:

```
export default {
    meta: {
        foo: 'bar'
    }
};
```

from pages only, into the $route.meta data, so that it is available as $route.meta.foo, it would solve many problems such as being able to use page level data, outside of the page scope. For example:

```
export default {
    meta: {
        theme: 'dark'
    }
};
```

The page layout could react to the $route.meta.theme value, and change the header and footer styles accordingly. This would also be useful for things like showing and hiding certain page elements such as footer menus, disclaimers etc etc.

### What does the proposed changes look like?

```
export default {
    meta: {
        ...
    }
};
```

being merged into the existing $route.meta property.

**Comment by ezequidias** [comment]
#3751
Solution not yet found

**Comment by sindrepm** [comment]
@Atinux can you please comment on the status of this feature? I thought it was already implemented as per your comment [here](https://github.com/nuxt/nuxt.js/issues/1687#issuecomment-331870619) but doesn't seem to work (2.14.12)?

**Comment by ezequidias** [comment]
At first I was a little confused.
By default in vue js I just needed to use this command below for me to get the goal of a route.
In other words, the return is an object

in vue.js: (Object) (Route current)
`this.$route.meta.breadcrumb`

in nuxt.js I used the method of @Atinux . ([comment here](https://github.com/nuxt/nuxt.js/issues/1687#issuecomment-331870619))

in nuxt.js: (Array)

middleware/routerMeta.js
```
export default ({ route, store }) => {
  store.commit('SET_ROUTE_META', route.meta.slice(-1).pop() || {})
}

```

store/index.js
` SET_ROUTE_META (state, routeMeta) { state.routeMeta = routeMeta }
`

(Route current)
`$store.state.routeMeta.breadcrumb`

This can help you @sindrepm !

**Comment by ezequidias** [comment]
### Vue.js return object
`this.$route.meta`

example: `

```
new Router({
  routes: [
  {
    path: 'teste1',    
    meta: {
      pageTitle: 'teste2'
    },
    children: [
      {
        path: '/teste2',
        meta: {
          pageTitle: 'teste2'
        }
      }
    ]  
  }  
 ]
})
```

return of `this.$route.meta` is: 
```
{
   pageTitle: 'teste2'
}
```

### Nuxt.js return array
`this.$route.meta`

return of `this.$route.meta` is: 
```
[
  {
    pageTitle: 'teste2'
  },
  {
    pageTitle: 'teste2'
  },
]
```

**Comment by szczynk** [comment]
is this still not implemented / fixed?
i tried on this [example](https://github.com/nuxt/nuxt.js/blob/2.x/examples/routes-meta/pages/about.vue) on my localhost and add
`created () {
    console.log(this.$route.meta)
 }` still give `{}` in the console

**Comment by ezequidias** [comment]
@Atinux ?

**Comment by ezequidias** [comment]
@Atinux 

https://codesandbox.io/s/cool-wozniak-tr771

### **layouts/default.vue**
![Screenshot_1292](https://user-images.githubusercontent.com/25870781/107388641-cecbb600-6ad4-11eb-9d54-80cd97d9446c.png)

### **pages/index.vue**
![Screenshot_1294](https://user-images.githubusercontent.com/25870781/107388719-ddb26880-6ad4-11eb-99d5-fd85f6f8742b.png)

### **pages/about.vue**
![Screenshot_1293](https://user-images.githubusercontent.com/25870781/107388701-dab77800-6ad4-11eb-8c8d-cd5914dfb895.png)

**Comment by fmgono** [comment]
> You cannot access the merge data inside the layout, you need to use a middleware for it.
> 
> Can I have a use case for it? So I better understand the missing feature or problem.

this feature request is a little bit important, because i wanna implement meta router to be consumed by another component outside pages folder
here is an example :

```js
// in pages/dashboard.vue
export default {
 meta: {
  pageTitle: 'Dashboard'
 }
}
```

```vue
// in components/layout/Navbar.vue template
<template>
 <h3 v-if="$route.meta.pageTitle">{{ $route.meta.pageTitle }}</h3>
</template>
```

how can i achive this in nuxt ? because this meta file could be help a lot for roles, route validations, etc

**Comment by danielroe** [comment]
This is now possible in Nuxt 3 using the `definePageMeta` compiler macro - meta defined in your component is automatically merged into the meta property of the route.
