### ISSUE TITLE
Functional components not worked if import dynamically with SSR context

### ISSUE THREAD

**Issue by altpoint** [nuxt/nuxt#8379]
### Versions

- nuxt: 2.14.7
- node: 14

### Reproduction
Import functional component dynamically on page

### Steps to reproduce
0) Create `functional` component like this:
`/components/UiPageTitle.vue`
```vue
<template lang="pug" functional>
  header.ui-page-title(
    v-bind="data.attrs",
    v-on="listeners",
    :ref="data.ref",
    :class="[data.staticClass, data.class]"
    )
    .ui-page-title__content
      .ui-page-title__prefix(v-if="!!(data.scopedSlots && data.scopedSlots.prefix)")
        slot(name="prefix")
      .ui-page-title__place
        slot
      .ui-page-title__tools(v-if="!!(data.scopedSlots && data.scopedSlots.tools)")
        slot(name="tools")
    .ui-page-title__footer(v-if="!!(data.scopedSlots && data.scopedSlots.footer)")
      slot(name="footer")
</template>
```

1) Import this component dynamically on the page:
`pages/index.vue`:

```vue
<template lang="pug">
  div
    ui-page-title
      h1 Heading 1
</template>
<script>
export default {
    name: 'IndexPage',
    components: {
        UiPageTitle: () => import('~/components/UiPageTitle')
    }
}
</script>
```

### What is Expected?
Everything works

### What is actually happening?

```code
TypeError
_vm._ssrNode is not a function
```

**Comment by danielroe** [comment]
**Minimal repro**: https://codesandbox.io/s/sweet-tharp-3surd?file=/pages/index.vue

**Comment by gibkigonzo** [comment]
@danielroe Did you found a solution? I have the same problem.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
