### ISSUE TITLE
Vue 3 support for Nuxt 2

### ISSUE THREAD

**Issue by Timkor** [nuxt/nuxt#8395]
### Is your feature request related to a problem? Please describe.

Google suggests it will count pagespeed as an significant impact factor from 2021. 

Since Vue 3 is significant faster than Vue 2 and they will release a Vue 2 API compatible build, this might be interesting to cooperate in Nuxt 2. So that migration to Nuxt 3 will not be mandatory in order to improve page speed.

### Describe the solution you'd like

Support for Vue 3 using the Vue 2 API compatible build of Vue 3 (to be released).

I understand that this might be a little far away since the Vue 2 API compatible build has not been released yet. But I would like to start the discussion of the possibility to add this feature.

**Comment by pi0** [comment]
Thanks for bringing it up. Actually not only vue-app but each core part of nuxt 2 is technically replaceable. This way we are already backporiting server from nuxt 3.

It might be matter of time until having release to investigate backport possibilities but:
- If possible, it will be with a community package for vue3
- There are no guarantees that it will be and optimized build as nuxt 3

**Comment by MarcGodard** [comment]
Is there a branch with progress on this?

**Comment by Rokuem** [comment]
the compatibility build released recently
https://github.com/vuejs/vue-next/tree/master/packages/vue-compat

**Comment by tobuf** [comment]
There is a project like nuxt, but support Vue 3. 
https://winixt.gitee.io/fesjs/guide/

Come on Nuxt 3! Some one has copied your idea.

**Comment by nothinginterested** [comment]
any news?

**Comment by ibrahimBeladi** [comment]
Years later, any news here?

**Comment by laurentfirdion** [comment]
Hey, any news on supporting @vue/compat ?

**Comment by danielroe** [comment]
We do not plan to add Vue 3 support to Nuxt 2, given that it will be EOL in June.
