### ISSUE TITLE
Support server side redirects in static mode

### ISSUE THREAD

**Issue by iBobik** [nuxt/nuxt#8448]
Currently Nuxt static mode redirects client side what is not recommanded in a SEO, better would be 301 redirects on a server.

### Describe the solution you'd like

Many static site hostings support redirects, but they have to be configured somehow. AWS S3 can be configured by [object meta data](https://docs.aws.amazon.com/AmazonS3/latest/dev/how-to-page-redirect.html). Firebase can be configured [by a json](https://firebase.google.com/docs/hosting/full-config#redirects).

We need at least some sort of hook what Nuxt will call for each redirect, so custom script can generate hosting configuration.

### Describe alternatives you've considered

Fetch redirects from CMS out of Nuxt, but this will not cover redirects initiated only in Nuxt.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
