### ISSUE TITLE
The build.extend option doesn't extend all webpack options

### ISSUE THREAD

**Issue by Perlover** [nuxt/nuxt#8454]
### Is your feature request related to a problem? Please describe.

Your [docs stands](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-build#extend) that I can extend `webpack` config through `build.extend` option. But I cannot change all options because later some from these are [rewritten by your here](https://github.com/nuxt/nuxt.js/blob/dev/packages/webpack/src/config/server.js#L110).

For example I want to turn off (`false` value) `node.__dirname` [option](https://webpack.js.org/configuration/node/#node__dirname) in webpack for my server code. Now server's code has as `undefined` `__dirname` constant under the Nuxt. I tried to change it by nuxt's config `build.extend` function but my changes are not affected (nothing happens - the `__dirname` stays as `undefined`). It's because after my `extend` function the Nuxt redefines `node` webpack's option to `false` ([the link to code line](https://github.com/nuxt/nuxt.js/blob/dev/packages/webpack/src/config/server.js#L112)). The `false` value for `node` webpack's option turn off the plugin [NodeStuffPlugin](https://webpack.js.org/configuration/node/#node) completely so node's constants will not be kept as node constants as expected and I cannot change it.

### Describe the solution you'd like

To allow to extend of all options and don't rewrite later by Nuxt.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
