### ISSUE TITLE
Multiline style string unescaped parsing

### ISSUE THREAD

**Issue by gsqrt2** [nuxt/nuxt#8536]
### Versions

- nuxt: v2.14.12
- node: v12.19.0

### Reproduction Repository

https://github.com/gsqrt2/nuxt-multiline-style

<details open>
<summary>Additional Details</summary>
<br>
minimal nuxt installation
</details>

### Steps to reproduce

Index page contains 3 nested divs with the same multiline style attribute.

On ssr load, inspect the nested divs and notice how only the parent div's style has been parsed correctly, while the nested children's style is broken by the \n character.

Use the links to navigate back and forth between index page and its copy, and you will notice that style is parsed correctly  when client side rendered.

Also notice that class attribute is parsed correctly every time.

### What is Expected?

Style attribute being parsed correctly regardless of the depth of the element.

### What is actually happening?

Nested divs' style is broken by unescaped \n character.

### Workaround

Making the style property reactive by either prepending :style="[]" or replacing the string (style="...") with a string template (:style="\`...\`") seems to bypass the problem.

**Comment by gsqrt2** [comment]
The behavior remains unchanged in nuxt-edge 2.15.0-26856070.8350560

The step to reproduce remain the change as described in the original report.

**Comment by gsqrt2** [comment]
Will try to do so (not very comfortable with testing webpack and loaders in isolation) and post the reference for future readers, thank you.

**Comment by gsqrt2** [comment]
Here is the reported vue-loader issue for reference: https://github.com/vuejs/vue-loader/issues/1793

One inconsistency with nuxt's behavior though, is that in the vue-loader example the issue appears only in ssr **and** hmr, whereas in nuxt the issue appears in ssr even in the production build.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
