### ISSUE TITLE
Set custom position for NuxtBuildIndicator

### ISSUE THREAD

**Issue by Rednas83** [nuxt/nuxt#8562]
### Problem

The indicator is not in the foreground
![image](https://user-images.githubusercontent.com/25219229/103214743-96e82500-4911-11eb-88e4-82f07767b3f0.png)

### Suggested solution
1. The indicator should be in the foreground
2. The position for the indicator should be configurable
3. The size for the indicator should be configurable

```
loadingIndicator: {
  name: 'circle',
  color: '#3B8070',
  background: 'white',
  position: 'BottomRight', // TopLeft(x1) ... BottomRight(x9) 
  size:  'small' // small || big
}
```

**Comment by danielroe** [comment]
We no longer use this loading indicator in Nuxt 3.
