### ISSUE TITLE
Ionic UI framework option

### ISSUE THREAD

**Issue by pnaylor** [nuxt/nuxt#8570]
### Is your feature request related to a problem? Please describe.

Trying to find the best way to start a Nuxt project with the Ionic Vue for UI components.

### Describe the solution you'd like

Option in create-nuxt-app for Ionic as the UI framework.

### Describe alternatives you've considered

Could try following the model of https://github.com/daggerok/ionic-nuxt-app but unclear if this is an optimal approach and presume it will not work with Ionic Vue > 1.0.

### Additional context

Ionic Vue beta was working with Vue 2 but 5.x (0.5 -> 5.4..) now only supports Vue 3. Would be great to see it working with Nuxt 3.

**Comment by danielroe** [comment]
We now have a Nuxt module for Ionic. Feature requests and bug reports are very welcome there: https://github.com/nuxt-modules/ionic
