### ISSUE TITLE
Different colors for the loading indicator when user has dark mode enabled

### ISSUE THREAD

**Issue by RubenVanEldik** [nuxt/nuxt#8580]
I am building a web page with a dark mode that automatically gets enabled when the user's CSS `prefers-color-scheme` is set as `dark`. The problem I face however is that there is still a white page flash if the user has dark mode enabled and goes to my site for the first time. 

My nuxt.config.js looks like this: 
```export default {
  loadingIndicator: {
    name: 'pulse',
    color: '#b91c1c',
    background: '#f6f6ef'
  },
  ...
}
```

The light background of my site is also #f6f6ef, so when the user does not have dark mode enabled the correct color is directly set, before the CSS and JS has been loaded. But when the user has dark mode enabled the site first becomes #f6f6ef before going to the darker gray when the CSS gets loaded. 

My proposed solution is to make an optional light/dark version of the loadingIndicator. This could look like this:
```export default {
  loadingIndicator: {
    name: 'pulse',
    color: {
      light:  '#b91c1c'
      dark: #7b7b77,
    },
    background: {
       light: '#f6f6ef',
       dark: #31312f
    }
  },
  ...
}
```

If the color or background is not an object but just a string, the same value will be used for both the light and dark setting, but otherwise the different colors will be used with the CSS prefers-color-scheme media query. (https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)

To see the problem in action, see https://hackerdaily.io.

I would love to hear what y'all think about this minor improvement. :)

**Comment by mjcadz** [comment]
Did you find any good solution for this? I noticed your pull request was closed :(

**Comment by RubenVanEldik** [comment]
The easiest way to do this in Nuxt.js 2.x is to use a custom loading screen. I think this issue will be addressed in version 3.x though.

**Comment by mjcadz** [comment]
I found a solution that works nicely for me. overriding the default html template, by adding `app.html` in the root directory, so that it applies a dark mode class on the html element as soon as it loads.

```
<!DOCTYPE html>
<html {{ HTML_ATTRS }}>
  <head {{ HEAD_ATTRS }}>
    <script>
      // set dark mode class here to avoid FOUC
      if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches === true) document.documentElement.classList.add('dark');
    </script>
    {{ HEAD }}
  </head>
  <body {{ BODY_ATTRS }}>
    {{ APP }}
  </body>
</html>
```

**Comment by danielroe** [comment]
This should be resolved in Nuxt 3. 👍
