### ISSUE TITLE
Add static assets after generate:page

### ISSUE THREAD

**Issue by Timkor** [nuxt/nuxt#8589]
### Is your feature request related to a problem? Please describe.

It would be nice to have the ability to add static assets on the `generate:page` hook. So there can be files created in the static assets folder using modules for further static optimization.

### Describe the solution you'd like

Currently they are being saved here: https://github.com/nuxt/nuxt.js/blob/9681a8937d0c973bc685b757faa686023a4536fc/packages/generator/src/generator.js#L344

It would be nice if they are being saved after the `generate:page` hook:
https://github.com/nuxt/nuxt.js/blob/9681a8937d0c973bc685b757faa686023a4536fc/packages/generator/src/generator.js#L400

And being included in the `page` object:
https://github.com/nuxt/nuxt.js/blob/9681a8937d0c973bc685b757faa686023a4536fc/packages/generator/src/generator.js#L392

### Describe alternatives you've considered
Manually resolving the static asset path and saving the files. But this seems redudant.

**Comment by Timkor** [comment]
Well I can think of many possibilities regarding optimization of assets per page. Which isn't possible in SSR mode due the performance impact. For instance we can "purge" the critical CSS using [uncss](https://github.com/uncss/uncss) (which really purges every unused style declaration). It would be nice in this case to save the rejected CSS into a file which will be loaded after TTI.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
