### ISSUE TITLE
Feature request: static nonce for script and style tags to avoid 'unsafe inline' CSP header field [aws Amplify use case]

### ISSUE THREAD

**Issue by rvaneijk** [nuxt/nuxt#8646]
**Context description**: I am using AWS Amplify to deploy my static website https://www.rvaneijk.io.

The custom security headers are applied in the deployment through a configuration file customHttp.yml ([https://docs.aws.amazon.com/amplify/latest/userguide/custom-headers.htm](https://docs.aws.amazon.com/amplify/latest/userguide/custom-headers.htm))

I include the customHttp.yml file in a .nuxtignore file to prevent triggering a rebuild of the webpack files if only the custom headers change. However, this only works locally, not on the server side in the deployment process.

**Problem description**: AWS Amplify does not use the .nuxtignore file in the deployment process. Therefore webpack files are rebuilt every time, resulting in a different hash value that I would need to include in the CSP header fields script-src and style-src. But since triggering a rebuild to apply a modification to customHttp.yml results in a new has value for the jetpack file(s), we never know the correct value upfront.

**Suggestion for solving the problem**: a static nonce would solve my use case. For example by defining the nonce in the nuxt.config.js file. By including the nonce in the webpack rebuild, I would be able to refer to the static nonce in the CSP header fields because the value would not change.

For example - nuxt.config.js:

```
generate: {
script-nonce: 'nonce-457bb2Bb06E44Ab5aa9996Ed1a34b26F',
style-nonce: 'nonce-[ ADD A VALUE HERE ]'
}
```

I realize that the Content Security Policy specification calls for a unique nonce value each time the server transmits a CSP-policy, But for this use case, a static nonce would be my preferred suggestion.

**Comment by rvaneijk** [comment]
^^ happy to discuss, expecially since webpack seems to supports nonce for script-src: [https://webpack.js.org/guides/csp/](https://webpack.js.org/guides/csp/)

**Comment by surgiie** [comment]
Did this ever get implemented in nuxt 3?

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
