### ISSUE TITLE
[Performance] Change smart prefetch strategy to use global IntersectionObserver

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt#8672]
Right now, every `<NuxtLink>` instantiates a new `IntersectionObserver` to enable smart prefetching for the linked page (unless disabled via `no-prefetch` or through the config).

https://github.com/nuxt/nuxt.js/blob/3bba4c6a7fd086aaa434e0abf92bdc9480fd3f4e/packages/vue-app/template/components/nuxt-link.client.js#L18

While this works well with a small to medium number of links, performance degrades on larger numbers (e.g. think of a page with a long table).

Sources: [[1]](https://www.bennadel.com/blog/3954-intersectionobserver-api-performance-many-vs-shared-in-angular-11-0-5.htm#main-content), [[2] (related to Mutation Observer + in german though but same principle)](https://twitter.com/sir_pepe/status/1348539744599363584)

Therefore I suggest to instantiate a global `IntersectionObserver`, e.g. accessible via `window.$nuxt.prefetchObserver` and observer all `NuxtLink`s through this single instance. This should improve performance, especially on sites with a huge number of links.

**Comment by pi0** [comment]
Fully agree to use single observer instance  (it was discussed in yesterdays meeting) 👍 For implementation, we might attach it to nuxt context instead of globalThis/window

**Comment by manniL** [comment]
> How do you feel to take up this challenge @manniL ? 😊

I'll give it a try! 👍🏻

**Comment by TrueCarry** [comment]
What do you think about flag like `prefetch: 'hover'`, which sets prefetching to when user hovering over the link, instead of just seeing it on the screen?

**Comment by manniL** [comment]
Could be a separate PR for sure 👍

**Comment by danielroe** [comment]
We now use a single observer in Nuxt 3. Let me know if you think we should reopen this or track any part of this issue.
