### ISSUE TITLE
hook on fetch errors

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt#8786]
Fetch errors do not bail rendering and are only available via `$fetchState.error`. This makes it hard when we want to report them to a logging system (nuxt-community/sentry-module#245) or having any global behavior like showing an alert or failing rendering. 

We can introduce a runtime hook like `fetchError` to allow this. It is possible to use vue events on `$root` instance to `$emit` and listen with `$on`. Only problem is that nuxt plugins are getting called before it creates so we need to introduce `ctx.$on` utility that gathers listeners and registers them when instance created.

Alternative approach: (#8475 / cc @Atinux) We can throw fetch errors. But this means introducing a breaking change (and not sure if it works universally same)

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
