### ISSUE TITLE
Add classes to loading to customize nuxt-progress bar

### ISSUE THREAD

**Issue by ManUtopiK** [nuxt/nuxt#8811]
### Is your feature request related to a problem? Please describe.

Cannot easily customize nuxt progress bar with classes.

### Describe the solution you'd like

We can customize almost everything with tailwindcss only to add classes.
I want to add classes to the `.nuxt-progress` element.

### Describe alternatives you've considered

In `nuxt.config.js`, something like:
```
export default {
loading: {
    classes: 'bg-gradient-to-r from-purple-600 via-blue-600 to-red-600',
},
...
```

**Comment by karngyan** [comment]
For any one who want's to just use a color from css variable: 

```js
  loading: {
    color: 'var(--color-600)',
    height: '3px',
  }
```

This hack worked for me. Although I'd like this feature. Also no docs for the `css` property in loading?

https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-loading#customizing-the-progress-bar

**Comment by danielroe** [comment]
It is now possible to customise `<NuxtLoadingIndicator>` in Nuxt 3 by adding classes to it. For example, in your `app.vue`:

```vue
<template>
  <NuxtLoadingIndicator class="some-class" />
  <NuxtPage />
</template>
```
