### ISSUE TITLE
Documentation request for a demo that uses auth0 to authenticate with a second provider (Firebase)

### ISSUE THREAD

**Issue by scottjehl** [nuxt/nuxt#8847]
Hi folks, 

I've been trying and failing for a few days to use Nuxt Auth to log into Firebase using a token from Auth0. I've gotten close to having it work, but it's never quite right. It would be so helpful if the docs could include an example of how you'd set up a login to authenticate with one provider and use that provider's token to sign into a second (Firebase, as one example).

I've been able to do this manually but I'd really like to use the Auth module for it if possible, to stay with the grain. Thanks for your consideration!

**Comment by danielroe** [comment]
If this is still relevant, would you raise it at https://github.com/nuxt-community/auth-module ? 🙏
