### ISSUE TITLE
Feature request | ScrollToTopInitial option in page scroll behavior

### ISSUE THREAD

**Issue by ghost** [nuxt/nuxt#8850]
### Is your feature request related to a problem? Please describe.

In our usecase, we have a page, say `/products/:filter`, which contains a filterable list of products. We want this filter as a url fragment so each of these pages is rendered separately. While you're in this page and click on a link that switches the filter to show different products in the listing, we want the scroll position to be kept as is, so we are using `ScrollToTop: false` in the page options. The problem is that setting this bool also doesn't scroll the page to the top when the user routes to this products page from a different page, keeping the scroll position the user had on the previous page.

### Describe the solution you'd like

I believe this mechanism requirement is common enough that it should be supported in Nuxt by default.

### Describe alternatives you've considered

We have extended the `app/router.scrollBehavior.js` script with custom behavior to add a page option called `ScrollToTopInitial`, which resets the scroll position to top only if the page is first visited, but keeps the scroll position when routing in the same parent page. Here is the piece of logic we are using atm:

```
// Scroll to the top of the page if...
  if (
    // One of the children set `scrollToTop`
    Pages.some(Page => Page.options.scrollToTop) ||
    // scrollToTop set in only page without children
    (Pages.length < 2 && Pages.every(Page => Page.options.scrollToTop !== false)) ||
    // CUSTOM: scrollToTop if scrollToTopInitial is set to true and we're not routing in the same template
    (Pages.some(Page => Page.options.scrollToTopInitial) && to.name !== from.name)
  ) {
    position = { x: 0, y: 0 }
  }
```

**Comment by summertzz** [comment]
Does your products page use nested sub-routes? I also encountered a similar application scenario, but if scrollToTop: false is set, the page will still scroll to the top. @mystrdat

**Comment by mystrdat** [comment]
@summertzz It doesn't, if the param is undefined I render a list of most recent products. I could probably separate it into a nested page structure but it would feature some unnecessary copypaste unless I'd abstract that away. All in all, I think Nuxt should expose these scrolling options instead of automating the behavior just for nested routes.
