### ISSUE TITLE
Accessing what middleware(s) took action from the context or component

### ISSUE THREAD

**Issue by mcanvar** [nuxt/nuxt#8862]
### Is your feature request related to a problem? Please describe.

Yes, recently I was working on a project that has a login form as an inline bootstrap CSS modal and I had no separate login/register pages. My auth check was in an auth middleware. In order to redirect or keep users on the same page, I needed to check the page's middleware. I could not find any way to check if the page loaded has the auth middleware or not.

My solution was keeping track of middleware actions in the vuex store which did not feel okay. 

### Describe the solution you'd like

That would be awesome to have something like `middleware` in the context object. So we can easily check what happened before the page loaded and take action.

Here is what I faced: https://stackoverflow.com/q/66251984/2873992

Note: Forgive me if it is not possible in the current position of nuxt.js this FR opened by someone who hasn't checked the codebase. Thank you all beautiful people to give us a chance to have this great tool.

**Comment by danielroe** [comment]
This would be a nice feature request for https://github.com/vuejs/router. If it's still relevant, would you raise an issue there? 🙏
