### ISSUE TITLE
Access runtime config in serverMiddleware

### ISSUE THREAD

**Issue by belgacea** [nuxt/nuxt#8897]
### Is your feature request related to a problem? Please describe.

> > Actually, is it possible to access privateRuntimeConfig in a custom serverMiddleware?
> 
> Not at the moment, no.

 https://github.com/nuxt/nuxt.js/issues/2033#issuecomment-773181809

### Describe the solution you'd like

Either the ability to access privateRuntimeConfig from Nuxt serverMiddleware, or [automatic injection of environment variables](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-env/#automatic-injection-of-environment-variables) within serverMiddleware.

### Describe alternatives you've considered

1. Using [built-in dotenv support](https://nuxtjs.org/docs/2.x/directory-structure/nuxt-config#runtimeconfig)

=> Do not work using Firebase Hosting / Functions deployment combo, without exposing .env vars.

2. Using [Firebase Functions Config](https://firebase.google.com/docs/functions/config-env)

=> Works, but much less convenient to use (need to import firebase lib and set env vars manually).

### Describe alternatives you've not considered

Creating an express API to access credentials (with some secure encryption or authentication in between)

=> Add a lot of complexity and cost to such a basic feature.

### Additional context

Althought [Nuxt runtime config is supposed to be a replacement to the dotenv module](https://nuxtjs.org/blog/moving-from-nuxtjs-dotenv-to-runtime-config), it does not offer most of its main features today.
Example : [Specifying a custom .env file path](https://stackoverflow.com/questions/65400022/how-to-set-a-env-file-path-in-nuxt-config)

**Comment by code-ape** [comment]
I also feel this pain. Had to wrap a super simple serverMiddle as a module because of it. Almost feels like it would be simpler to at least point people towards modules and explain how to do serverMiddleware that way. Since I'm almost always going to care about some config item for serverMiddleware.

**Comment by danielroe** [comment]
This is now possible in Nuxt 3 with `useRuntimeConfig()`.

**Comment by HenrikPilz** [comment]
Hi, is this fixed for Nuxt 2 as well?

**Comment by danielroe** [comment]
No, not unless you use Nuxt Bridge.

**Comment by HenrikPilz** [comment]
Thank you.
