### ISSUE TITLE
Spa dev server for integration with hot reload

### ISSUE THREAD

**Issue by rejexy** [nuxt/nuxt#8911]
### Is your feature request related to a problem? Please describe.

When using `webpack-dev-server`, entire vue project is generated in one script, which is conveniently integrated into html template. But in Nuxt.js I did not find such a convenient configuration, even if I connect several scripts, errors like: `GET file:///__webpack_hmr/client net::ERR_FAILED` are constantly detected.

### Describe the solution you'd like

It would be great if there was an opportunity to configure the destination for generating the html template file, which can be used to develop a web application with hot reload.

### Describe alternatives you've considered

it would be convenient to be able to include a parameter in the configuration file so that all paths have a full path in src, href and js scripts.
For example: instead of `src = "/_nuxt/some/"` generate `src = "http://localhost:PORT/_nuxt/some/"
`

**Comment by danielroe** [comment]
Closing as I don't think this is relevant for Nuxt 3 development but please feel free to open a new issue if it's still an issue for you in Nuxt 3.
