### ISSUE TITLE
nuxt build is interactive and making it non-interactive is not obviously documented

### ISSUE THREAD

**Issue by mattpr** [nuxt/nuxt#8915]
This is a problem for CI builds.

### Versions

```
$ node node_modules/nuxt/bin/nuxt.js build --version
@nuxt/cli v2.15.1
$ npx envinfo --binaries --system
npx: installed 1 in 1.435s

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
    Memory: 101.58 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.19.0 - ~/.nvm/versions/node/v12.19.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.19.0/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.19.0/bin/npm
```

### Reproduction

Running...
```
$ yarn install --frozen-lockfile --non-interactive --prefer-offline --no-progress
$ NODE_ENV=production NUXT_ENV_API_URI="/api"  node node_modules/nuxt/bin/nuxt.js build --quiet
```

Results in interactive prompt...
```
ℹ NuxtJS collects completely anonymous data about usage.                                                                                                                                            15:49:45
  This will help us improve Nuxt developer experience over time.
  Read more on https://git.io/nuxt-telemetry

? Are you interested in participating? (Y/n)
```

I tried using `--quiet` hoping it would stop being interactive but it didn't make any difference...and on the CI I would rather that it is NOT quiet but that it is non-interactive.

`nuxt build --help` doesn't reveal any options to answer these interactive questions or force non-interactive mode.
```
$ node node_modules/nuxt/bin/nuxt.js build --help
  Usage: nuxt build <dir> [options]

  Compiles the application for production deployment

  Options:

    --spa, -s          Launch in SPA mode
    --universal, -u    Launch in Universal mode (default)
    --config-file, -c  Path to Nuxt config file (default: nuxt.config)
    --modern, -m       Build/Start app for modern browsers, e.g. server, client and false
    --target, -t       Build/start app for a different target, e.g. server, serverless and static
    --no-force-exit    Whether Nuxt should force exit after the command has finished
    --version, -v      Display the Nuxt version
    --help, -h         Display this message
    --no-processenv    Disable reading from process.env and updating it with dotenv
    --dotenv           Specify path to dotenv file (default: .env). Use false to disable
    --no-lock          Do not set a lock on the project when building
    --analyze, -a      Launch webpack-bundle-analyzer to optimize your bundles
    --devtools         Enable Vue devtools
    --no-generate      Don't generate static version for SPA mode (useful for nuxt start)
    --quiet, -q        Disable output except for errors
    --standalone       Bundle all server dependencies (useful for nuxt-start)
```

### Steps to reproduce

Install nuxt, run build.

### What is Expected?

nuxt should have documented options to give mandatory inputs and/or non-interactive switch.  If non-interactive mode is set/implied by environment, then this should be documented.  

It is desirable to be able to force non-interactive mode in an interactive environment (e.g. for testing CI script on development machines before pushing to CI).

### What is actually happening?

`nuxt build` has interactive prompts.

**Comment by mattpr** [comment]
It looks like I can work around this specific interactive problem by adding this ENV to the build command: 
`NUXT_TELEMETRY_DISABLED=1`

But it would be nice in general if `nuxt build` had a way to NEVER prompt (e.g. `--non-interactive`). 
If required config is missing in non-interactive mode...then just error out with a message saying that.

**Comment by mattpr** [comment]
This is still reproducible.

```
$ git clone https://github.com/nuxt/nuxt.js.git
$ cd nuxt.js
$ git rev-parse --short HEAD
8e725d34
$ yarn install --frozen-lockfile --non-interactive --prefer-offline --no-progresse node_modules/nuxt/bin/nuxt.js build --quiet
    # ...
$ NODE_ENV=production NUXT_ENV_API_URI="/api"  node node_modules/nuxt/bin/nuxt.js build --quiet

? Are you interested in participating? (Y/n)
```

**Comment by Gredys** [comment]
Up (same problem)

**Comment by mattpr** [comment]
Still reproducible.  

```bash
git clone https://github.com/nuxt/nuxt.js.git
cd nuxt.js/
git rev-parse --short HEAD
# 777a4b7f
yarn install --frozen-lockfile --non-interactive --prefer-offline --no-progress
# ...
NODE_ENV=production NUXT_ENV_API_URI="/api"  node node_modules/nuxt/bin/nuxt.js build --quiet
# 
# ? Are you interested in participating? (Y/n)
# 
NUXT_TELEMETRY_DISABLED=1 NODE_ENV=production NUXT_ENV_API_URI="/api"  node node_modules/nuxt/bin/nuxt.js build --quiet
# (no output or interactive prompt)
```

`NUXT_TELEMETRY_DISABLED` works as a workaround, should be documented.  Would be nice if cli build command didn't default to interactive or had an obvious flag to turn it off.  I haven't checked if the CLI options or ENV documentation has been updated since reporting.

**Comment by tol64** [comment]
https://github.com/nuxt/telemetry/issues/30#issuecomment-1187729192

**Comment by danielroe** [comment]
This should not be reproducible in CI. Locally it will prompt event with `--quiet` (as that's not the same thing as non-interactive) unless you are running a test or don't have a TTY available, but we do test for CI ([these providers](https://github.com/unjs/std-env/blob/main/src/providers.ts) supported out of the box) and support setting `CI` variable as well to enable CI mode.

If you continue to experience this, would you provide some more info on your CI setup?
