### ISSUE TITLE
Support Analyze with development server

### ISSUE THREAD

**Issue by Jake13f** [nuxt/nuxt#8925]
### Is your feature request related to a problem? Please describe.

I need the ability to use the analyze property normally run with `nuxt build -a` on a development build of my application.  For some reason my app bundle sizes are astronomically larger in the development server than when built for production and need a way of investigating.

### Describe the solution you'd like

`nuxt -a` for an analysis of the development bundles.

**Comment by danielroe** [comment]
This is now possible with Nuxt 3 + latest devtools
