### ISSUE TITLE
Parameter with a slash renders page when loaded client-side but not server-side

### ISSUE THREAD

**Issue by silverbackdan** [nuxt/nuxt#8932]
### Versions

- nuxt: >2.15.3 (originally had said 2.15.2, but since realised 2.15.3 works fine)
- node: 15.5.1

### Reproduction

https://codesandbox.io/s/blue-tdd-iwi0s?file=/nuxt.config.js
But hosted here it does not seem to have the issue

### Steps to reproduce

When deployed on my computer, the setup above will load the URL http://192.168.1.15:3000/papers/saf%2Fsadf/authors client-side (using nuxt-link) but if I reload the page, the SSR will give me a page not found error. It's related to the %2F (slash) in the parameter that I want to work as ID.

### What is Expected?

Server-side should render the same as client-side.

### What is actually happening?

I get a page not found.

I have stripped my project right back and cannot see any differences in the code locally to what is in the reproduction link. Does anyone have any clues as to what could be causing this? It happens whether I run it from within a Docker container or not so I can't imagine it's any environment variables. This issue is really confusing me right now as to why it behaves differently in the codepen.

**Comment by silverbackdan** [comment]
Indeed I download that codepen and run on my machine and the issue happens. I'm using yarn 1.22.5 and node 15.5.1

It's possible that it's related to the node version? I see the container config for codepen uses 14.

**Comment by silverbackdan** [comment]
It looks to me as though the ufo package is being used to normalise the URL, but I'm not sure why. Client-side the URL would not render if I used unencoded slashes. So this could cause an inconsistency in route matching.

**Comment by silverbackdan** [comment]
Furthermore, I've discovered in the latest version, in middleware I get the `route` option in the context and the `matched` array is empty if the parameter has slashes in it, even though the correct route loads.

**Comment by silverbackdan** [comment]
So while I don't know why the SSR is not matching the front-end in some cases - in this one I am using an object to link in front-end router links, and the SSR side will just try and use the URL. Encoded or not, just using the URL seems to fail. Perhaps this is a Vue Router bug... but I see in the routes I could adapt a path to allow or slashes. e.g. `/_cwa/users/:iri(.*)` (adding the regex after the parameter)

Does Nuxt have an in-built way to do this for a route without having to use the `router.extendRoutes` method in the nuxt config?

**Comment by Nojusle** [comment]
I have same problem. When Nuxt do ssr it treats ```%2F``` as ```/```. It means all websites using dynamic routers have bug in them if slug contains ```/```. Escaping characters in standard way doesn't work. Anyone?

**Comment by silverbackdan** [comment]
This is a really big issue for me - it's been open without a reply since 3rd March, sorry to be a pain and ping @pi0

**Comment by silverbackdan** [comment]
I currently cannot use any version of Nuxt after 2.15.3 because of this issue.

**Comment by Whiled0S** [comment]
Same issue, for now it is hard for me to switch nuxt version before 2.15.3. I will discover possible solutions and hope it will be fixed soon. In my case it appears when I'm navigating to route like `/some-route/121%2F10401`, where `%2F` automatically transforms to `/` and I get `/some-route/121/10401` which is not found.

**Comment by Whiled0S** [comment]
I found the temporary solution, but it is a weird. For my case using `_.vue` file with `params.pathMatch` works right, but if you have more than one nested level – it is bad idea.

Now my code looks like:

```js
async asyncData({ params }) {
  const parameter = params.pathMatch
  
  // some code
}
```
