### ISSUE TITLE
Enable build modules per layouts

### ISSUE THREAD

**Issue by HUGE-D1CK-10-INCHES** [nuxt/nuxt#8943]
`
buildModules: [
    '@nuxtjs/buefy'
    '@nuxtjs/vuetify',
    '@some-other-module'
],
`
This may be already existing somewhere but I cannot find it.

Is there a way to have a layout that uses only vuetify module, and other where it uses only buefy module, as well as not using any of those?

To specify which module I want to be included in which layout?

**Comment by danielroe** [comment]
No, modules run in the entire Nuxt build context - this kind of feature would need to be supported by a particular module rather than by Nuxt..
