### ISSUE TITLE
is it possible to generate just one route without build and update data with the translation system

### ISSUE THREAD

**Issue by johan-Rm** [nuxt/nuxt#8969]
### Is your feature request related to a problem? Please describe.

Update the data (JSON files) and then run the "generate" process of a single route (for example) **without doing a build**

What I just described works fine, however when I use the translation (i18n.$t()), so when I want to update the data (**JSON files + LANG files**) this time **it doesn't work** because the translation strings are compiled by Webpack

### Describe the solution you'd like

so I would like to generate routes with the new translated data without doing the build

### Describe alternatives you've considered

one of the possible alternatives would be not to use i18n. $ t ()

**nuxt version : 2.15.2**
**node version: 13.11.0**

**Command generate**
yarn run v1.12.
$ nuxt generate --modern --no-lock --fail-on-error --slug=page2
✔ Skipping webpack build as no changes detected
ℹ Full static generation activated

**nuxt.config.js**
```
const args = require('yargs').argv
import pages from './data/web_pages.json'
...
generate: {
        dir: 'dist',
        // cache: false,
        cache:  {
            ignore: [
               'dist',
               'data',
               'lang'
            ]
        },
        crawler: false,
        routes: function (callback) {
            var routes = []
            console.log('slug : ' + args.slug)
            if (args.hasOwnProperty('slug')) { // for update one route only
                const result = pages.find(p => p.slug === args.slug)
                if(result) {
                    const route = {
                        "route": '/' + args.slug
                        , "payload": {
                            "page": result
                        }
                    }
                    routes.push(route)
                }
            } else {
                pages.forEach(function(page) {
                    const route = {
                        "route": '/' + page.slug
                        , "payload": {
                            "page": page
                        }
                    }
                    routes.push(route)
                })
            }
            callback(null, routes)
        }
    }
```

**_page.vue**
```
<template>
    <div class="page-content">
        <pre>{{ $t(page.headline, 'en') }}</pre>
    </div>
</template>
<script>
import { mapState } from 'vuex'
export default {
    name: 'TemplatePages',
    computed: {
        ...mapState({
            page: state =>  state.pages.item
        })
    }
}
</script>
```

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
