### ISSUE TITLE
Lots of files in the static folder causes long hot reload times

### ISSUE THREAD

**Issue by harrisKAsher** [nuxt/nuxt#8972]
### Lots of files in the static folder causes long hot reload times
Having lots of files in the static folder cause very long hot reload times. We have over 1,000 svg icons in our static folder; with them our hot reload times takes over of 5 seconds, without them under 1 second. 

### Possible solution
It would be nice if in the build property we could have it only worry about the files on the initial build and ignore them when hot reloading. It seems something like this already exists in the generate property for caching and this is what I imagine would be do able for the hot reloading.

What the generate property supports:
```
cache: {
  ignore: [
    '.nuxt', // buildDir
    'static', // dir.static
    'dist', // generate.dir
    'node_modules',
    '.**/*',
    '.*',
    'README.md'
  ]
}
```

### Possible work around
The only current viable work around I've found is hosting the files somewhere else. However, that isn't a great solution for us as this app is intended to be a PWA and needs to work offline.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
