### ISSUE TITLE
ssr: false doesn't support dynamic public path

### ISSUE THREAD

**Issue by danielroe** [nuxt/nuxt#8973]
https://github.com/nuxt/nuxt.js/issues/8863#issuecomment-796642432

**Comment by YutaMoriJP** [comment]
@danielroe Is there a workaround for this issue until a proper fix is implemented? Thanks!

**Comment by danielroe** [comment]
Dynamic public path is now supported with `ssr: false` in Nuxt 3.

**Comment by reitowo** [comment]
How? `<img class="" src="/icon/song.png" width="60" data-pc-section="image">` still tries to download from `file:///D:/icon/song.png`, if the page is loaded as file

**Comment by reitowo** [comment]
is it possible at runtime to automatically replace the src's prefix to ./ or simply remove the leading / ?
