### ISSUE TITLE
[BUG: 2.15.4] Breaking change: Route double slashes are redirected to single slashes in the latest minor release.

### ISSUE THREAD

**Issue by silverbackdan** [nuxt/nuxt#9095]
### Versions

- nuxt: 2.15.4
- node: 12.18

### Reproduction
Use a double forward slash in a route

### Steps to reproduce
I have been using a route parameter which starts with a forward slash, so I need there to be 2 forward slashes in a row. This was fine until 2.15.4 where the route is redirected and normalized to a single slash. Breaking change.

Thanks

### What is Expected?
The route stays the same as was requested, I am unsure why once a route is requested, Nuxt would be deciding to try and re-normalize it without intervention.

### What is actually happening?
`https://localhost:3000/_cwa/page//_/pages/5c9310cb-aed2-4a23-afff-fe2e5541b058` becomes 
`https://localhost:3000/_cwa/page/_/pages/5c9310cb-aed2-4a23-afff-fe2e5541b058` - `/_/pages/5c9310cb-aed2-4a23-afff-fe2e5541b058` is the route parameter I need and have configured my routes as such.

**Comment by silverbackdan** [comment]
In 2.15.3 my routes loaded as `%2F_%2Fpages%2F5c9310cb-aed2-4a23-afff-fe2e5541b058` which is fine as well. Have downgraded for now.

**Comment by silverbackdan** [comment]
Related: https://github.com/nuxt/nuxt.js/issues/9028

I feel that redirecting and normalizing routes that have been specifically requested does not seem expected behaviour.

**Comment by pi0** [comment]
Hi @silverbackdan. Can you please add a minimal reproduction for this?

**Comment by silverbackdan** [comment]
Will do, there's a reproduction of another normalization in the related issue already too

**Comment by silverbackdan** [comment]
Voila: https://codesandbox.io/s/intelligent-mcclintock-9olm0?file=/pages/something/_iri.vue

The link from the index page works client-side. You'll see like the related issue, on a server-side load it normalizes. :( I did look at the source, I fear it's not academic though.

**Comment by silverbackdan** [comment]
I think the sandbox isn't necessarily like-for-like with server-side loads. Try downloading to your computer I'd say. It was doing the exact same bug initially, now on a refresh it just says page not found. And in 2.15.3 too, but 2.15.3 is working at least for this slash issue.

**Comment by henk23** [comment]
There is a special case to maybe consider here, when the double slash is located at the beginning of the path:

OPs example: `http://localhost:3000/a//b redirects* to http://localhost:3000/a/b`
Beginning of path: `http://localhost:3000//a/b redirects* to http://localhost:3000/b`

* Putting the asterisk, because there is no explicit redirect (3xx response from the server), the URL just seems to get magically rewritten.

Minimal reproduction: https://github.com/henk23/nuxt-double-slash-bug (Standard "create-nuxt-app" with some added pages, middleware and server-middleware)

**Comment by silverbackdan** [comment]
Please continue to investigate this issue.
