### ISSUE TITLE
Keep Alive in Layout makes nested page using nuxt-child doesn't load correctly

### ISSUE THREAD

**Issue by alijaya** [nuxt/nuxt#9124]
### Versions

- nuxt: v2.15.4
- node: v14.14.0

### Reproduction

https://codesandbox.io/s/nuxt-keep-alive-bug-hoehj

1. Click `Nested` Button, should bring to `/parent`, and `parent/index.vue` should be loaded showing `Parent` in title
2. Click `Child 1` Button, should bring to `/parent/child1`, and `parent/child1.vue` should be loaded showing `Child 1` in title
3. Click `Index` Button, should bring to `/`, and `index.vue` should be loaded, and we go back to index page
4. Click `Nested` Button again, should bring to `/parent`, and `parent/index.vue` should be loaded but it's instead showing `parent/child1.vue` because the title shown is not `Parent` but `Child 1`

### Steps to reproduce

1. add `keep-alive` attribute in `nuxt` component in layout
2. has nested page with `nuxt-child`

### What is Expected?

It's expected that the route should be loaded as if the `keep-alive` is not there

### What is actually happening?

The last child page accessed is loaded instead of the correct one.

**Comment by Benjamin-Lee** [comment]
This issue persists into even the Nuxt 3 bridge.

**Comment by stonega** [comment]
The issue is still not fixed in latest nuxt 2 version. It need to be reopened.

**Comment by JeronimasDargis** [comment]
Having the same issue on nuxt: "2.15.8"

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
