### ISSUE TITLE
Extending scrollBehavior instead of overwriting

### ISSUE THREAD

**Issue by Yihao-G** [nuxt/nuxt#9142]
### Is your feature request related to a problem? Please describe.

Provide a mechanism to extend [`scrollBehavior`](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-router/#scrollbehavior) function rather than overwriting. 

In my case, I want the page to not scroll when updating the hash, but only in certain cases that I have specified programmatically. The only workaround I've found so far is creating a dummy param in the `params` object of the Router `replace`/`push` function object parameter, and check the param value in the `scrollBehavior` function. However, I also want to keep the default scroll behaviour in other cases. Overwriting the `scrollBehavior` function removes the default scroll behaviour. 

Copying the [Nuxt default `router.scrollBehavior.js`](https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/router.scrollBehavior.js) is difficult because it's a code template and contains external imports. Also, such a way sounds dirty and is not future-prone.

### Describe the solution you'd like

Rather than overwriting `scrollBehavior`, consider using the filter pattern. For example, in the `~/app/scrollBehavior` folder, the developer can create multiple `js` files (with a number as the filename to indicate the execution order) to create a chain of logic. Each file contains:

```js
export default function (to, from, savedPosition, next) {
  // do some logic here
  return next(to, from, savedPosition)
}
```

In my case, I would create a filter like this:

```js
export default function (to, from, savedPosition, next) {
  if(to.params.routerNoScroll) return // do not continue to the next filter if routerNoScroll param is truthy, this prevents scrolling
  return next(to, from, savedPosition)
}
```

Developer can also customise other parameter values passing to the next filter:

```js
export default function (to, from, savedPosition, next) {
  return next(to, from, { x: 0, y: 0 }) // do not use savedPosition, always scroll to the top
}
```

Or even more complex:
```js
export default function (to, from, savedPosition, next) {
  return next(to, from, to.path === '/foo' ? { x: 0, y: 0 } : savedPosition) // do not use savedPosition on path `/foo` only
}
```

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
