### ISSUE TITLE
Corrupted CSS animation keyframe values (opacity in %)

### ISSUE THREAD

**Issue by petrhdk** [nuxt/nuxt#9144]
### Versions

- nuxt: `2.15.4`
- node: `v14.15.4`

### Reproduction repo
+ https://github.com/pitizzzle/nuxt-bugreport-css-animation-opacity-percent

### Steps to reproduce

+ `nuxt.config.js`:
  ```js
  export default {
    target: 'static',
    head: {
      meta: [
        { charset: 'utf-8' },
        { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      ],
    },
  };
  ```
+ `layouts/default.vue`:
  ```vue
  <template>
    <div><Nuxt /></div>
  </template>
  ```

+ `pages/index.vue`:
  ```vue
    <template>
      <main>
        <div id="test" class="animation-active"></div>
      </main>
    </template>
    
    <style>
    #test {
      width: 100px;
      height: 100px;
      background: red;
    }
    #test.animation-active {
      animation: test-animation 2s;
    }
    
    @keyframes test-animation {
      from { opacity: 0%; }
      to { opacity: 95%; }
    }
    </style>
  ```

+ command:
  ```bash
  nuxt generate && nuxt start
  ```

### What is Expected?
+ ![chrome_phOeK4FcoF](https://user-images.githubusercontent.com/36761687/114428152-21504e00-9bbc-11eb-89bf-043eae940bee.png)

### What is actually happening?
+ ![chrome_AtIZWIv7Ye](https://user-images.githubusercontent.com/36761687/114428176-290ff280-9bbc-11eb-84c4-c34f15d85a83.png)
+ wtf?! xDD

**Comment by pitizzzle** [comment]
Any progress?
Please, this is a ridiculous bug, and it already is so isolated xD

**Comment by whoisjorge** [comment]
**This is not specifically a nuxt.js issue.** Please see: https://github.com/preactjs/preact-cli/issues/1190#issuecomment-634201910

Opacity with percentages as units might not be the best choice, although it is accepted. It works perfectly in production builds using a number [0, 1] as alpha value.

```css
@keyframes test-animation {
  from { opacity: 0; }
  to { opacity: 0.95; } /* same as 95% */
}
```

**Comment by pitizzzle** [comment]
Okay 👍
So let's wait for the new release of `cssnano` where the bug is fixed.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
