### ISSUE TITLE
Support runtime `router.base` and `publicPath` for STATIC sites

### ISSUE THREAD

**Issue by timelytree** [nuxt/nuxt#9170]
In order to host a website on IPFS, it must be `static` and all paths must be generated in a relative fashion. These paths should be applied to all assets, routes (including nested routes) and all internal Nuxt files such as the dynamically generated `/_nuxt/81e6be4.js` types of files and Nuxt's `payload.js`, `state.js`, etc files.

The reason for this is because IPFS makes a website available through 2 different URL structures that are made available following a **_single_** generate command. Build once → generate hash → deploy via both URLs. Therefore we basically have 1 generated application that is served at 2 different root directories.

1. Primary domain: `your-website.com`
2. IPFS hash: `gateway.ipfs.io/ipfs/<hash>`

Currently assets are generated like this:

`/_nuxt/static/1617154192/manifest.js`

which results in:

1. Primary domain: `your-website.com/_nuxt/static/1617154192/manifest.js` ← this works
2. IPFS hash: `gateway.ipfs.io/_nuxt/static/1617154192/manifest.js` ← **this does not work**

but what _should_ happen is:

1. Primary domain: `your-website.com/_nuxt/static/1617154192/manifest.js`
2. IPFS hash: `gateway.ipfs.io/ipfs/<hash>/_nuxt/static/1617154192/manifest.js`

—

One possible solution is to evaluate the `router.base` and `publicPath` at runtime. Passing a function to each of these could potentially do the trick, thus allowing all the paths to be updated based on `window.location`. An example of a similar implementation for VuePress can be seen [here](https://github.com/cwaring/vuepress-plugin-ipfs).

Please let me know if any more information is necessary 🙂 as this is all a little difficult to explain via text.

—

**Related issues**
- #8229 — this issue was closed but not actually truly resolved (it's identical to my own problem)
- #8509 — looks like this solved things but **_not for `static` sites_**. There's a [comment](https://github.com/nuxt/nuxt.js/issues/8509#issuecomment-747453947) inside this issue that points to the fact that this does not apply to static sites - does this mean it will never be possible to do in Nuxt?

**Comment by lewebsimple** [comment]
The same problem applies when using Nuxt for WordPress themes, i.e. where relative paths to `/wp-content/themes/example/dist/_nuxt/` should be present instead of `/_nuxt/`.

It used to work by setting `config.output.publicPath` in `build.extend`

**Comment by pi0** [comment]
Hi, @timelytree thanks for opening new issue. Somehow IPFS (#8229) was lost in the process. But don't worry we will properly support IPFs deployments soon :) 

The short answer for the plan I'm thinking, It seems the safest method would be using relative links to reference assets (js, css) and for links (similar to [all-relative](https://www.npmjs.com/package/all-relative) we might do with a plugin or module to hook). We might need additional steps for making use of [`<base>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) and a runtime script that detects IPFS root ([example](https://github.com/Velenir/nextjs-ipfs-example/blob/master/pages/_document.js#L4)).

Next step I will be trying to make a working demo with the current version of nuxt. If all goes fine, we may add `baseURL: relative` (or something similar) as a built-in option since after feedbacks on initial dynamic base support, seems a valid usecase for portable base URL.

**Comment by timelytree** [comment]
@pi0 that's amazing news, thanks to you as well for being so active and responsive!

A colleague of mine (a contributor to `all-relative` actually) has some thoughts on implementation as well, he'll jump in here sometime soon :)

Feel free to shoot me a link to a working demo when you have one up and running and I can help you test it under a production environment as I've got one almost ready to go 👌🏼

**Comment by orvn** [comment]
> If all goes fine, we may add `baseURL: relative` (or something similar) as a built-in option since after feedbacks on initial dynamic base support, seems a valid usecase for portable base URL. @pi0 

Thanks for considering this enhancement. It would be super useful re: IPFS-hosted static sites as well as other applications

**Comment by ferferga** [comment]
Hi @pi0, we're interested in this as well. It's going to be only in Nuxt 3 or will it be backported to Nuxt 2 as well?

**Comment by code-ape** [comment]
Jumping in there to say that we would benefit from this too. While we are not on IPFS, we are trying to run a site that does runtime `basePath` for a hybrid ssr/spa application which seems to have the same need. Would love to understand the timeline for this!

**Comment by ykzts** [comment]
This problem can be solved by specifying auto for `publicPath` in webpack, but in Nuxt `publicPath` does not interpret anything other than URL and path.

**Comment by YutaMoriJP** [comment]
@ykzts Mind clarifying this line "This problem can be solved by specifying auto for publicPath in webpack?" Ideally with an example 🙏  Thank you!

**Comment by ernaneluis** [comment]
Any updates on this?

**Comment by orvn** [comment]
@ernaneluis for nuxt3 it shouldn't be an issue. For nuxt2, you can use [this module](https://github.com/undone-labs/nuxt-module-ipfs).

**Comment by ernaneluis** [comment]
> have a nuxt module (`nuxt-module-ipfs`)

Can you be more clear how this can be solved on nuxt 3?
