### ISSUE TITLE
Request: Config property or build variable for debugging production builds (allowing console.log and enabling Vue devtools)

### ISSUE THREAD

**Issue by katerlouis** [nuxt/nuxt#9172]
Figuring out how to enable console.logs and Vue devtools in production build took me longer than I'd like to admit :X

As for the `dev`-property, I think the docs aren't clear enough of what this does.

How about a property like `debugProduction: true` in nuxt.config.js 
Or `npm run generate --debug` 

that set the following:

```js
  dev: true,

  vue: {
    config: {
      productionTip: true,
      devtools: true,
    },
  },
```

And add this to the docs on a new page, maybe "Debugging" or "Troubleshooting"

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
