### ISSUE TITLE
Duplicated URL on nuxt generate with non latin url encode

### ISSUE THREAD

**Issue by virtuallabdev** [nuxt/nuxt#9193]
### Versions

- nuxt: 2.15.4
- node: 12.16.1

### Reproduction

 https://github.com/rchl/nuxt-link-cyrillic-static

<details open>
<summary>Non latin URL duplicated on static page generation</summary>
<br>
nuxt-link-cyrillic-static/pages/index.vue
</details>

### Steps to reproduce

- generate the static site
- use "nuxt start" to navigate the full static site
- if you click on non latin link, you can see the log in browser developer  console (I'm using chrome) because you are landing to spa fallback page
- If you click on latin link, log are not show in console because you are using the static page
- If you add "/" at the end of non latin URL, page will be reload using the static page (no log in the console)

### What is Expected?
Nuxt should generate the language routes for non latin characters without duplicate the URL and without fallback to spa pages

### What is actually happening?
URL without the slash at the end fallback to the spa page only for non latin URL, instead the duplicated URL with "/" at the end is work properly

**Comment by virtuallabdev** [comment]
Hi, the problem persist so please when is possible fix this issue, thanks in advance

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
