### ISSUE TITLE
Webpack loader resolution breaks with yarn hoisting

### ISSUE THREAD

**Issue by guillaumeduliscouet** [nuxt/nuxt#9205]
### Versions

- nuxt: v2.15.4
- node: v14.16.1
- yarn: v1.22.10

### Reproduction

https://github.com/guillaumeduliscouet/nuxt-resolution

It is a simple yarn workspace monorepo with 2 apps:
- `packages/vue-app`: a vue2 app created with `vue create`
- `packages/nuxt-app`: a nuxt app created with `yarn create nuxt-app`

<details open>
<summary>Additional Details</summary>
<br>

`nuxt` build error:

```
Module build failed (from /home/gduliscouet/dev/nuxt-resolution/node_modules/css-loader/dist/cjs.js):
ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
 - options.modules has an unknown property 'compileType'. These properties are valid:
   object { auto?, mode?, exportGlobals?, localIdentName?, localIdentRegExp?, context?, hashPrefix?, getLocalIdent? }
    at validate (/home/gduliscouet/dev/nuxt-resolution/node_modules/css-loader/node_modules/schema-utils/dist/validate.js:98:11)
    at Object.loader (/home/gduliscouet/dev/nuxt-resolution/node_modules/css-loader/dist/index.js:36:28)
```

`yarn why css-loader`

```
=> Found "css-loader@3.6.0"
info Reasons this module exists
   - "_project_#vue-app#@vue#cli-service" depends on it
   - Hoisted from "_project_#vue-app#@vue#cli-service#css-loader"
info Disk size without dependencies: "352KB"
info Disk size with unique dependencies: "1.69MB"
info Disk size with transitive dependencies: "5.99MB"
info Number of shared dependencies: 30
=> Found "@nuxt/webpack#css-loader@4.3.0"
info This module exists because "_project_#nuxt-app#nuxt#@nuxt#webpack" depends on it.
info Disk size without dependencies: "272KB"
info Disk size with unique dependencies: "1.59MB"
info Disk size with transitive dependencies: "5.89MB"
info Number of shared dependencies: 29
```
</details>

### Steps to reproduce
As described in the repro readme:
- install dependencies 
- start the nuxt-app

### What is Expected?

Nuxt build should not fail when `yarn` decides to hoist a dependency.

`@nuxt/webpack` declares a dependency to a version of `css-loader`, it should follow the standard node resolution strategy (look first in its own `node_modules` before going up)

### What is actually happening?

Nuxt build fails because it uses the hoisted version of `css-loader` for the vue app

In a bit more details:
- `yarn` decides to hoist the `css-loader@3.6.0`  used by `@vue/cli-service` (verified with `yarn why css-loader`)
- yarn knows that `@nuxt/webpack` needs a version of `css-loader` matching `^4.3.0`, so it provides it in `@nuxt#webpack`'s own `node_modules` (which is fine)
- `@nuxt/webpack` uses the hoisted version (`css-loader@3.6.0`) (which is not fine)
- `css-loader` throws an error because `compileType` doesn't exists in `v3.6.0`

**Comment by EmeraldCoder** [comment]
Got the same issue on one of my projects.

The workaround that I used was to add `"css-loader": "^4.3.0"` to the `devDependencies` in the package.json of my Nuxt project.

**Comment by guillaumeduliscouet** [comment]
Indeed, we used the same workaround on our side, but it didn't work 100%. From what I understood, it brakes when yarn still decides to hoist `css-loader v3` and provide it at the root of the root's `node_modules`:
- `css-loader v4` is provided in `@nuxt/webpack`'s own `node_modules` AND `packages/nuxt-app`'s own `node_modules`
- `@nuxt/webpack` is provided in the root `node_modules`
- `css-loader v3` still had priority over `css-loader v4` when building the nuxt app (when resolving from `@nuxt/webpack` with a broken resolution strategy, probably)

=> adding depenedenies to `css-loader v4` encourages webpack to hoist it instead of `v3`, but if it is not enough it will still break

We now use [nohoist](https://classic.yarnpkg.com/blog/2018/02/15/nohoist/) as a workaround (only needs to be defined once).

In our root `package.json`:
```
    "workspaces": {
        "packages": [
           ...
        ],
        "nohoist": [
            "**/css-loader",
            "**/postcss-loader"
        ]
    },
```

**Comment by manniL** [comment]
As a workaround, you can use [`nohoist`](https://classic.yarnpkg.com/blog/2018/02/15/nohoist/) the css-loader package.

**Comment by guillaumeduliscouet** [comment]
I am still reproducing the issue as of today with `Nuxt @ v2.15.7` :/ And I think this package resolution error could produce even trickier problems.

Wouldń't it be possible to "follow the standard node resolution strategy" ? Would it break something else ?

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
