### ISSUE TITLE
Improve the way to pass options to plugin

### ISSUE THREAD

**Issue by daniluk4000** [nuxt/nuxt#9207]
### Is your feature request related to a problem? Please describe.

Current way to pass options to plugin (from example, from module) is unclear, undocumented and unusual. We have to use <% and %> to call for options, and serializeFunction to work with them.

### Describe the solution you'd like

For Nuxt 3/Nuxt 2.16:
- Implement options pass as third argument
- OR implement options pass as "this" inside plugin
- Migrate this to plain Javascript without any templates

### Describe alternatives you've considered

To deal with it

### Additional context

Here's function to register custom vuex module from plugin. Seems easy?

![изображение](https://user-images.githubusercontent.com/10450717/116442426-29b2b500-a85b-11eb-9c38-74470c546ff7.png)

**Comment by daniluk4000** [comment]
@pi0 sorry for pinging, is this still a thing in Nuxt 3?

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
