### ISSUE TITLE
NuxtChild on/off toggle

### ISSUE THREAD

**Issue by michaudhugo** [nuxt/nuxt#9215]
Hi, 

I was starting the implementation of my modals "system", and for it I followed the approach pathway leading to having my pages well organized with the parent one integrating a NuxtChild component.

So I end up having this directory structure:
- items/
    - _id/
        - edita.vue
        - editb.vue
    - _id.vue
- index.vue

I wished to open 2 possible modals, edita.vue and editb.vue as overlays of my _id.vue page.
It works.

Later, I was looking for a solution to replicated the behaviour to open a creation modal for my items, with the following route:
items/add/.

I wanted to have this modal on overlay of my items index page. So I followed up the same scenario and I ended up with having this directory structure:
- items/
    - _id/
        - edita.vue
        - editb.vue
    - _id.vue
    - add.vue
- items.vue

Which worked also. But then I started noticing the trouble here: items/:id/ was not anymore leading to a different page. My id pages were now showing on my index page, in the NuxtChild component.

**So, I was hoping for a solution to let say, turn off/on the NuxtChild component when calling NuxtLink.
A prop telling whethere it should open in a NuxtChild, if any, or not.**

I liked the way I can manage to have my routing system just with the directory structure for my pages. Someone suggested to me to play over nuxt.config.js and extendRoutes, but it splits a little bit too much things.

Maybe there is a way to do it. Let me know.

**Comment by drewbaker** [comment]
+1 to this. Would love a way to break out of Nuxt child for sub routes.

**Comment by danielroe** [comment]
Closing but I would consider reopening this if there's sufficient demand for it.
