### ISSUE TITLE
Support graceful shutdown - do not destroy existing connections

### ISSUE THREAD

**Issue by sreuss** [nuxt/nuxt#9219]
### Is your feature request related to a problem? Please describe.
We are running a Nuxt app on Kubernetes/EKS and are currently trying to figure out how to properly implement a graceful shutdown: By default Kubernetes will send a SIGTERM and wait for 30s before a SIGKILL is sent to forcefully kill the container. 

We are also running some NestJS services which have built-in signal handling to await `server.close`, waiting for open connections.

Consequently, our expectation was that the `close` method on the `nuxt` instance provided to the `ready` hook behaves the same way. However, it turns out that Nuxt employs the `server-destroy` package to forcefully destroy open connections if the Nuxt instance is closed. While sensible for local development, this sounds somewhat risky in production.

### Describe the solution you'd like

Do not forcefully close open connections in a production environment (`NODE_ENV=production`) if the Nuxt instance is closed, just await `server.close`.

### Describe alternatives you've considered

Allow the behavior to be configured via `nuxt.config.js`. For example with a `destroyOnClose: false` on the `server` property.

### Simplified Example

Create a basic universal Nuxt app with `yarn create nuxt-app` and extend `nuxt.config.js` with the following:

```js
  hooks: {
    ready(nuxt) {
      const signals = ['SIGINT', 'SIGTERM'];
      const handler = async (signal) => {
        try {
          signals.forEach(sig => process.removeListener(sig, handler));
          await nuxt.close();
          process.kill(process.pid, signal);
        } catch(error) {
          console.error('error during shutdown', error);
          process.exit(1);
        }
      };
      signals.forEach(signal => process.on(signal, handler));
    }
  }
```
* Run `yarn build` and `yarn start`. 
* Open a dummy connection via netcat: `nc localhost 3000`.
* Send a SIGKILL to the Nuxt process.

Expectation: The Nuxt process only closes once netcat is manually closed.
Actual: The Nuxt process exits immediately, closing the netcat connection.

**Comment by pkalisz** [comment]
+1

**Comment by wusongliang** [comment]
Currently, the close hook closes the Nuxt process without waiting for the callback function to execute. I want to wait for it to complete before closing the process

**Comment by liuzy0404** [comment]
"By default Kubernetes will send a SIGTERM and wait for 30s before a SIGKILL is sent to forcefully kill the container."
Perhaps you should add close hook, and wait 30s for nuxt.close() ?

**Comment by liuzy0404** [comment]
> Currently, the close hook closes the Nuxt process without waiting for the callback function to execute. I want to wait for it to complete before closing the process

In my case, i add a setTimeout 5s latency in close hook callback, and Nuxt process wait for 5s before closing.
```js
export default function () {
  this.nuxt.hook('ready', (nuxt) => {
    logger.info('nuxt ready hook');
    process.on('SIGTERM', async () => {
      logger.info('SIGTERM signal received.');
      await nuxt.close();
    });
    setTimeout(() => {
      kill(process.pid, 'SIGTERM');
    }, 10000);
  });

  this.nuxt.hook('close', async (nuxt) => {
    await setTimeout(() => {
      logger.info('closed hook');
    }, 5000);
  });
}
```

Console below: 
```js
[2022-09-28T11:33:29.331] [INFO] default - SIGTERM signal received.                                                                                                                                                                                                                                                                                                    11:33:29
[2022-09-28T11:33:34.333] [INFO] default - closed hook                                                                                                                                                                                                                                                                                                                 11:33:34
✨  Done in 15.88s.
```

**Comment by trylovetom** [comment]
@sreuss @pkalisz @wusongliang @liuzy0404 Hello there! I know this issue has been around for a while, I've managed to find a workaround using Nuxt 3 and Nitro. If you're still experiencing this problem, you might want to give it a try.

Also, please note that you might want to replace the `nc localhost 3000` command you mentioned with `curl localhost:3000`, as the former can be treated as an idle connection to the best of my knowledge.

The Nuxt team has done an amazing job and I believe this issue deserves some attention. You can check out the workaround here: https://github.com/nuxt/nuxt/issues/19888#issuecomment-1542111353. I hope this helps!

**Comment by GuillaumeAmat** [comment]
The issue seems to be fixed :rocket: :heart: 

Killing a Nuxt/Nitro server with `SIGTERM` or `SIGINT` signals works as expected:

1. Kill the process
2. Open requests still run
3. When all the requests are done, the server gracefully shuts down (i.e.: status `0`)

One can tweak the shutdown behavior using Nitro environment variables: https://nitro.unjs.io/deploy/runtimes/node#environment-variables

I think we can close this issue @danielroe @pi0 :hugs:
