### ISSUE TITLE
Enabling eslint-module fix to auto-fix linted js.

### ISSUE THREAD

**Issue by richardhuf84** [nuxt/nuxt#9220]
### Is your feature request related to a problem? Please describe.

When enabling eslint and prettier in the nuxt cli, eslint will warn of any linting errors it finds. Which is great. You can also enable some configuration to automatically fix these errors, but adding the following in nuxt.config.js

```
// nuxt.config.js
buildModules: [
    // https://go.nuxtjs.dev/eslint
    ['@nuxtjs/eslint-module', {
      fix: true
    }]
  ],
```

### Describe the solution you'd like

Could there either be:

a) this settings added by default. I think a lot of developers will get bogged down when they need to make every eslint suggested change manually, that can be fixed automatically. Or:

b) a setting in the cli that asks if you would like eslint auto-fix turned on in configuration. 

### Describe alternatives you've considered

The alternative is to just have this as configurable in the nuxt config, as it is currently. I just found it difficult to find information on how to configure this (needing some context around eslint-loader and prettier, so wondered if other devs would benefit from the assistance.

I'm sure there may be good reasons why this has been considered, and not added.

Thankyou.

**Comment by pi0** [comment]
Hi @richardhuf84. I would suggest creating default change proposal in eslint-module repository. Seems a good idea to me.
