### ISSUE TITLE
serverMiddleware hot reload `module.hot -> undefined`

### ISSUE THREAD

**Issue by liho00** [nuxt/nuxt#9269]
### Versions

- nuxt: v2.15.5
- node: v14.15.0

### Steps to reproduce
// nuxt.config.js
```
  serverMiddleware: [
    require('./api/db'),
    '~/graphql',
    { path: '/api/siteverify', handler: './api/recaptcha' },
  ],

```

// graphql/index.ts
``` 
import express from 'express';
import { ApolloServer } from 'apollo-server-express';
import schema from "./schema"

const PORT = 4000;

const server = new ApolloServer({
  schema,
});

if (module.hot) {
  module.hot.accept();
  module.hot.dispose(() => server.stop());
}

console.log("module.hot", module.hot); // undefined returned

const app = express();
server.applyMiddleware({ app });


app.listen({ port: PORT }, () => {
  console.log(`GraphQL Server ready at http://localhost:${PORT}${server.graphqlPath}`)
}
).on('error', (e: any) => {
  // if (e.code === 'EADDRINUSE') {
  //   console.log('Address in use, retrying...');
  // }
})


export default {
  path: '/graphql', handler: app
}
```

Why do i always get undefined when hot reload server middleware files?

### What is Expected?
When hot reload, update the schema of GraphQL.

### What is actually happening?
the hot reload isnt catching in the server middleware handler.

**Comment by pi0** [comment]
Since Server Middleware are not bundled, they do not support HMR API. Currently, you can attach `unload` callback to `app` (https://github.com/nuxt/nuxt.js/blob/2b1c685f2479ed76b552563930389ab5f2b1ff07/packages/server/src/server.js#L350)

**Comment by liho00** [comment]
> Also you should not start a new listener from middleware file. Instead you can use a nuxt module if listening to second port is needed.

Hi, thanks for reply. May i know how to listen to second port with nuxt module? Izit implement it in the export default function?

```
export default function (req: any, res: any, next: any) {
  // req is the Node.js http request object
  // console.log(req.url)

  // res is the Node.js http response object

  // next is a function to call to invoke the next middleware
  // Don't forget to call next at the end if your middleware is not an endpoint!
  next()
}
```
