### ISSUE TITLE
Improve ESM compatibility

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt#9302]
This is an umbrella issue to track compatibility improvements for nuxt and across ecosystems with esm modules as they are being widely used.

- Avoid depending on `require.main`
  - https://github.com/nodejs/node/issues/49440
  - https://github.com/nuxt/nuxt.js/issues/6718
  - https://github.com/nuxt/telemetry/issues/49
- Issues with externals plugin
  - https://github.com/nuxt/nuxt.js/issues/9223#issuecomment-840747064
- Rollup plugin to guarantee isomorphic builds without concerning module authors (with siroc and unbuild)
  - https://github.com/unjs/unbuild/issues/7
- Improvove isomorphic transforms in jiti
- Webpack4 `.mjs` handling
  - https://github.com/nuxt/nuxt.js/pull/9180
  
Having issues with esm support? Please use a new issue with reproduction 👍

**Comment by danielroe** [comment]
I think we can close this. wdyt @pi0?
