### ISSUE TITLE
RuntimeConfig is not reloaded on `watch`

### ISSUE THREAD

**Issue by tschni** [nuxt/nuxt#9312]
### Versions

- nuxt: v2.15.6
- node: v14.17.0

### Reproduction

https://codesandbox.io/s/nuxt-issue-watch-config-bpxsk

### Steps to reproduce

1. Open the codesandbox project
2. See that the current preview displays the text `Hello world, how is the weather today?`
3. Open the "config.json" file and edit the value in `exampleValue`
4. See in the terminal how the app is recompiled
5. Look at the preview again and you will see that the `this.$config` variable has not been updated

### What is Expected?

After the app has been recompiled, the `this.$config` variable should actually be up to date and contain the new config.

### What is actually happening?

`this.$config` always contains the state of the config when starting the development environment and is not updated when recompiling.

Only after the dev process (`yarn start`, CodeSandbox: `Restart Sandbox`) has been completely restarted, the new state is loaded into `this.$config`.

**Comment by AndrewBogdanovTSS** [comment]
I also get such behavior for .env file, although I'm adding it to **watch** inside nuxt.config and visually rebuild is taking place - no env variables are updated in the app unless I fully restart the process

**Comment by tschni** [comment]
> I also get such behavior for .env file, although I'm adding it to **watch** inside nuxt.config and visually rebuild is taking place - no env variables are updated in the app unless I fully restart the process

@AndrewBogdanovTSS Please let me know when you have found a way

**Comment by Bigdragon13th** [comment]
Having this issue with `.env` file as well. The runtime config is reload if I put the value directly into `nuxt.config.js` but not when trying to get the value using `process.env` from `.env` file.

**Comment by seuros** [comment]
This is not a bug, as nuxt is not watching environment variables. You can add a watcher for .env to re trigger the build.

**Comment by AndrewBogdanovTSS** [comment]
@seuros I tried that, but that didn't help, for some reason. although it's triggering a rebuild, ENVs are only updated after manual restart

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
