### ISSUE TITLE
Generate static files without random ids 

### ISSUE THREAD

**Issue by sebsonjura** [nuxt/nuxt#9334]
We have a s3 deploy running that simply syncs the contents of a build to the bucket. 

### Is your feature request related to a problem? Please describe.

With each build,  it leaves an old version in the static folder from a previous build. Over time we are accumulating a lot of folders with random ids in static. Depending on the amount of builds and page contents, this can be a great number of data. 

### Describe the solution you'd like

I would be able to host all new files under static directly or re build into the same id with every build, since we have very fine control over headers in our cdn

### Describe alternatives you've considered

An alternative would be a safe way to read out the latest random id and have a nightly build job delete old files from  our deploy S3 Bucket.

### Additional context

* we are using latest nuxt
* deploy is with AWS codebuild 
* deployed to a s3 bucket
* Files served via cloudfront

**Comment by andig89** [comment]
Hmmm... use CleanWebpackPlugin on one of hooks + https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-build#filenames?

**Comment by mdryden** [comment]
I found a way to make this number stay the same on each build....it seems to be undocumented, but the generator uses an injected configuration value called staticAssets.version for this number.   If the value is null, it results in a random number each time.

You can make it the same every time you generate by setting it in your nuxt.config.js:

```
  generate: {
    staticAssets: {
      version: "1",
    },
  }
```

In this case I used "1", but I assume that can be any valid path string.  With a value here, the number won't change from build to build.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉

**Comment by syedfaizan** [comment]
> I found a way to make this number stay the same on each build....it seems to be undocumented, but the generator uses an injected configuration value called staticAssets.version for this number. If the value is null, it results in a random number each time.
> 
> You can make it the same every time you generate by setting it in your nuxt.config.js:
> 
> ```
>   generate: {
>     staticAssets: {
>       version: "1",
>     },
>   }
> ```
> 
> In this case I used "1", but I assume that can be any valid path string. With a value here, the number won't change from build to build.

This works for me, but now the biggest concern is that if we make a change, how do browsers download updated assets? im unable to add "cache-control" headers to the static files (`.nuxt` folder). do you know how one would work around this ?
