### ISSUE TITLE
Can you enable the props option in the router.js file just like VueJS does?

### ISSUE THREAD

**Issue by patchthecode** [nuxt/nuxt#9339]
### Is your feature request related to a problem? Please describe.
As mention on the VueJs [website](https://router.vuejs.org/guide/essentials/passing-props.html#passing-props-to-route-components),
> Using $route in your component creates a tight coupling with the route which limits the flexibility of the component as it can only be used on certain URLs.
> To decouple this component from the router use option props

In Vuejs, we use this option by setting the props option in the `router.js` file.
This causes the page/component to not be tied to a route enabling it to be used any way (as also mentioned in the video on that link).

### Describe the solution you'd like

Nuxt auto-generates the router.js file but does not provide the option to set the props option. Therefore, i can only access the params passed to the page using `$route.params` thereby tightly coupling my component/page to routes.  If this option was enabled however, then my page/component will automatically receive those parameters in to `props` just like a regular component.  Therefore the same page component can be used else where into places where routes are not used.

### Describe alternatives you've considered

No alternatives. Since Nuxt is based on VueJS, i assume that just enabling the feature would make is work as expected without any major code change.

**Comment by danielroe** [comment]
It is now possible to fully configure the router in Nuxt 3 with `app/router.options.ts`: https://nuxt.com/docs/guide/directory-structure/pages#router-options
