### ISSUE TITLE
Nested functional components are broken in production builds

### ISSUE THREAD

**Issue by misterupkeep** [nuxt/nuxt#9366]
### Versions

- nuxt: v2.15.6
- node: v14.15.1

### Reproduction

https://github.com/misterupkeep/nuxt-functional

<details open>
<summary>Additional Details</summary>
<br>
<code>.nuxt.config.js</code> has:
<pre lang="js">
  components: true,
  ssr: false,
  target: 'static',
</pre>
</details>

### Steps to reproduce
Generating a production build will produce a broken output (i.e. `yarn generate && yarn start`)

### What is Expected?
`<dummy/>` is a functional component that contains another functional component, `<logo/>`.
`<dummy/>` passes props and fills the default slot in `<logo/>`, and `<dummy/>` itself is used in the index page.

The production build should work normally, correctly rendering all components on the page.

### What is actually happening?
The production build will error when rendering the functional component(s); I'm not exactly sure which.
The error will complain about something along the lines of `e._v is not a function`, in a section of code that looks like:
```js
var o = {
  name: "Dummy"
},
component = Object(l.a)(o, (function(t, e) {
  var n = e._c;
  return n("Logo", {
    attrs: {
      text: "functional component prop"
    }
  }, [n("span", [
        e._v("This is inside the <Logo/> default slot") // this line errors
     ])])
}
```
I've had similar things happen with not recognising `$options` (used in the repro repo, but does not error in it). It sounds like the production build disregards the inner nested components as functional, but the dev server correctly recognises this.

**Comment by toniengelhardt** [comment]
I had similar issues. Apparently functional components behave completely different in dev mode and in production build. E.g. @click.native events are fired in dev mode but not in production. The functional components should behave exactly the same in both modes, otherwise they are virtually not usable.

**Comment by mercs600** [comment]
This is only happens when you use auto-imports components by `components: true`.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
