### ISSUE TITLE
Option to have runtimeConfigs to be stored in a central file with nuxt generate?

### ISSUE THREAD

**Issue by kngai** [nuxt/nuxt#9409]
### Is your feature request related to a problem? Please describe.

When an application needs to be moved from one deployment server to another while maintaining the same build (ie. DEV, STAGE, BETA, OPS, etc..), it would be much easier to edit the runtimeConfigs for each deployment, without needing to run `nuxt generate`.

### Describe the solution you'd like

`nuxt generate` has the option to build the application with runtimeConfigs variables stored in single dedicated file, such as a `/dist/_nuxt/runtimeConfigs.js`

Something in as an option in the `nuxt.config.js` like:
```js
export default {
  generate: {
     singleFileRuntimeConfig: true
  }
}
```

### Describe alternatives you've considered

The current build with `nuxt generate` will store the runtimeConfigs in multiple/duplicate `state.js` files for each html page. It's possible to write a shell script that searches for those files that can replace the values of those runtimeConfig variables, but making edits over multiple duplicate files doesn't make sense and adds more work.

### Additional context

I created a discussion here but I haven't gotten a response from anyone: https://github.com/nuxt/nuxt.js/discussions/9346

I'm not using SSR due to requirements. NuxtJS `nuxt generate` is a great option that is SEO-friendly.

**Comment by MichealPearce** [comment]
Would a solution be to add this configuration to the static folder and import it via a plugin? Something like:

```javascript
import config from '@/static/config.js'

export default function(ctx, inject) {
	ctx.$config.options = config
}
```

Since it's in the static folder, it should be packaged inside of `dist`. Hope this helps @kngai

**Comment by kngai** [comment]
Thanks @MichealPearce for the suggestion. That is a definite possibility I didn't think of. 

I still use `.env` files to store and manage my different configs. So I think creating a `/static/runtimeConfigs.js` file with something like this would work:
```js
const config = {
  APP_UI_BASE_URL: process.env.APP_UI_BASE_URL,
  APP_UI_API_URL: process.env.APP_UI_API_URL
  // ...
}
export default config
```

And then importing it as needed in my `.vue` or plugin files:
```js
import config from '@/static/runtimeConfigs.js'
```

Of course, this really defeats the purpose of the setting up `publicRuntimeConfig` in `nuxt.config.js` and using `this.$config` though. 😄

**Comment by MichealPearce** [comment]
You could do something like this for the `publicRuntimeConfig` @kngai 

```javascript
// nuxt.config.js
import publicConfig from './static/runtimeConfigs'

export default {
   ....
   publicRuntimeConfig: publicConfig
   ....
}
```

This way you only have to set one place. Then the plugin will override whatever is set when it's loaded. Just be sure to add the plugin as early in the list as possible so it's the first to load

**Comment by kngai** [comment]
@MichealPearce I just tried experimenting with creating `/static/runtimeConfigs.js` with values as `process.env.*` and importing that into my `nuxt.config.js` `publicRuntimeConfig` as above.

```js
 // nuxt.config.js
import publicConfig from './static/runtimeConfigs'

export default {
   // ....
   publicRuntimeConfig: {
    ...publicConfig,
    otherConfigs: package.otherConfigs
  }
  // ....
}
```

Unfortunately after running `nuxt generate`, it doesn't output with the `process.env` values replaced.

Even if that somehow does work, the same `/dist/_nuxt/*/**/state.js` and `index.html` files contain the same original values and not as a reference to values in `/static/runtimeConfigs.js`.

**Comment by MichealPearce** [comment]
@kngai Yes, the config here should just be default values. I would add a plugin that replaces those values like so:
```javascript
// plugins/config.js
import publicConfig from '@/static/config.js'

export default function(ctx) {
   ctx.$config.public = publicConfig
}
```
Then add the plugin to the nuxt config
```javascript
export default {
  //....
  plugins: ['./plugins/config'],
  ///...
}
```

The plugin will run once on page load and should be listed first so the ones after it receive the proper config if they use it.

**Comment by lucasctd** [comment]
wish I could use this.$config or something like that in stores, but your solution worked like a charm, thank you :)
