### ISSUE TITLE
addLayout for custom error page is not providing the error props

### ISSUE THREAD

**Issue by fcieminski** [nuxt/nuxt#9418]
### Versions

- nuxt:  v2.15.6 
- node: v14.17.0

### Reproduction

Link to reproduce - https://github.com/fcieminski/nuxt-modules-bug

### Steps to reproduce

1. Start clear nuxt project
2. Add module.js with new error layout to nuxt.config.js
3. Visit not created page to see what's happening

### What is Expected?

The new registered error layout from module should mimic the way how normal error page is working, so extend the default layout with for example footer and header and also provide the `error` prop to manage errors.

### What is actually happening?

The error page is treated as independent and standalone layout, not respecting the nuxt components structure and not having the error prop.

Here's the structure with error layout inside layout folder
![obraz](https://user-images.githubusercontent.com/45480039/121346490-798a9e80-c926-11eb-8c13-d6dacbd685a8.png)

Here's the structure after creating custom error layout module
![obraz](https://user-images.githubusercontent.com/45480039/121346537-8909e780-c926-11eb-98b1-4783c0e03442.png)

Minimal code, it's also inside my repo:

Adding custom error page layout
![obraz](https://user-images.githubusercontent.com/45480039/121346921-f584e680-c926-11eb-84cd-8c92af5e56d7.png)

Error page itself:
![obraz](https://user-images.githubusercontent.com/45480039/121346758-cbcbbf80-c926-11eb-8279-7f59555650c1.png)

Empty error object:
![obraz](https://user-images.githubusercontent.com/45480039/121346836-e0a85300-c926-11eb-8025-b8c849404b67.png)

**Comment by fcieminski** [comment]
The issue is still valid.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
