### ISSUE TITLE
<Nuxt/> keep-alive props with Regex trigger warning

### ISSUE THREAD

**Issue by Kapcash** [nuxt/nuxt#9453]
### Versions

- nuxt: 2.14.12
- node: 15.3.0

### Reproduction

Reproduction Codesandbox: https://codesandbox.io/s/nuxt-keep-alive-warn-zz77x

### Steps to reproduce

1. Use `keep-alive` on `<Nuxt />` component.
2. Add an `include` or `exclude` props to `keep-alive-props` with a Regex parameter.
    `<Nuxt keep-alive :keep-alive-props="{ include: /.+Page/ }" />`
3. Open a page concerned by this `<Nuxt />`
4. See a Vue warning on the console

Note: Also happens with the `new RegExp()` constructor.

Note 2: I made the test with a classic `<component :is="name" keep-alive="{ include: /.+Page/ }" />` on a vanilla Vue app, and it worked as expected (i.e. no warning messsage).

### What is Expected?

No warning on the console since it's working fine and it's valid code.

### What is actually happening?

The include property works fine, but we have a Vue warning about a prop which should be a String, RegExp or Array, but is actually a RegExp (the irony haha)

>  ERROR  [Vue warn]: Invalid prop: type check failed for prop "include". Expected String, RegExp, Array, got RegExp

**Comment by Kapcash** [comment]
Reproduced on Nuxt 2.15.7 (cf original [codesandbox link](https://codesandbox.io/s/nuxt-keep-alive-warn-zz77x))

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
