### ISSUE TITLE
HTML attributes are not reactive when store is set through a client plugin

### ISSUE THREAD

**Issue by ronenteva** [nuxt/nuxt#9467]
_I'm new to Nuxt.js so I might be missing something basic here, but I've looked everywhere and I believe it's a bug._

```
// index.vue

<template>
  <p :title="name">{{ name }}</p>
</template>

<script>
export default {
  computed: {
    name() {
      return this.$store.state.user.name;
    }
  }
};
</script>
```
Title does not match the text:
![image](https://user-images.githubusercontent.com/2454954/122878745-4999bd00-d362-11eb-90c6-bacd02047290.png)

```
// store/index.js

export default {
  actions: {
    async nuxtClientInit({ commit }) {
      commit("user/set", { name: "Rick Sanchez" });
    }
  }
};
```
```
// store/user.js

export const state = () => ({
  name: "Morty Smith"
});

export const mutations = {
  set(state, user) {
    state.name = user.name;
  }
};

```

### Versions

- nuxt: v2.15.7
- node: v14.16.0

### Reproduction
Check out: [CodeSandbox](https://codesandbox.io/s/pensive-lake-q6yd8)

**Comment by reegodev** [comment]
Hi @ronenteva , this seems a problem related to Vue core. This issue might help you https://github.com/vuejs/vue/issues/7063

Basically the workaround is to put a ref on the element.

**Comment by manniL** [comment]
As @reegodev mentioned, putting `ref` on it works. Seems to be a Vue bug indeed and as Vue is going EOL in 7 days there is little chance it will be ever fixed.

Thus, closing here
