### ISSUE TITLE
Support Base dynamic function

### ISSUE THREAD

**Issue by wsh4089** [nuxt/nuxt#9468]
Our website will have different route.base for different countries. Considering the resource problem of the server, I hope to start only one nuxt instance.
I tried ctx.$config.app.basePath = '/us' ctx.app.router.base = '/us' in version 2.15.0 but it didn't work. It seems that different route.bases still need to start different nuxt instances.
Then I checked the code in @nuxt/server, and found that the code to start the server depends on options.route.base and cannot be truly dynamic.

Can you help me solve this problem?

**Comment by george-pogosyan** [comment]
@wsh4089  I think u can use [nuxt-i18n](https://i18n.nuxtjs.org/) project for solving your localization problem

**Comment by danielroe** [comment]
This can be configured in `app/router.options` in Nuxt 3: https://nuxt.com/docs/guide/going-further/custom-routing#router-options
