### ISSUE TITLE
Running Middleware client side on first page load when rendering statically

### ISSUE THREAD

**Issue by HMilbradt** [nuxt/nuxt#9473]
### Is your feature request related to a problem? Please describe.

We've been using SPA mode and middlewares to handle redirecting certain pages depending on if the user is logged in or not.  However, after switching to static mode, our middleware is no longer run on the client side on the first page load, and so we're having to rethink this strategy.

The middleware only kicks in when the user then navigates client side, and they are correctly sent to the auth pages to register or log in.  What we really need though is to have this middleware run client side instead of during the build.

### Describe the solution you'd like

I would really like to see an option to have middleware run client side only for static, similar to how plugins can be run in both client and server.  This seems like such a natural feature for the framework to support, I was surprised that it wasn't already there to begin with.

Plugins use the naming scheme, like `auth.client.js`, as well as `process.server`, which are both very handy.  I would love to see this same scheme applied to middleware as well.

### Describe alternatives you've considered

I realize that this has been brought up previously here: https://github.com/nuxt/nuxt.js/issues/2653.  Specifically, one of the suggestions is to use a combination of plugins and middleware.  This works for a lot of use cases (and we are in fact using this elsewhere), but it doesn't scale well at all for this use case.

For example, we might have 20 different page components (and 20 or more unique routes due to dynamic pages) with the middleware `middleware: ['requires-auth']`.  It's not clear how you would use this in conjunction with plugins, and whatever solution there might be certainly isn't simpler than just enabling middleware to run client side via an option.

I've also considered moving this entirely to a plugin, or using router metadata as well, but both of these solutions are really a lot worse than using middleware.  In this particular use case, you'd still need to either maintain a list of all the route path patterns you need protected, or you'd need to manually override the router metadata.  

### Additional context

I do want to point out that the official Nuxt docs have an example of exactly this use case, which of course doesn't work for static sites, [here](https://nuxtjs.org/docs/2.x/directory-structure/middleware#named-middleware).

Thanks

**Comment by danielroe** [comment]
Middleware now runs on client-side as well in Nuxt 3.
