### ISSUE TITLE
bug : nuxt config router redirect me to root path

### ISSUE THREAD

**Issue by noukaza** [nuxt/nuxt#9481]
- nuxt: v 2.14.5
- node: v14.13.0

### Reproduction

i have a problem with the base router 
when i configure it to redirect to '/app' or anything else the first call will redirect me to '/' root path

### Steps to reproduce

in my nuxt.config file I added 

  `router: { base: '/app' },`

### What is Expected?

Always be redirect to /app

### What is actually happening?
and this happened only that the first time when i opened the browser 

https://user-images.githubusercontent.com/1030561/123402274-daada580-d5a7-11eb-91b4-deabd93ea557.mov

**Comment by noukaza** [comment]
@danielroe i don’t know why but i can’t reproduce it in your codesandbox project. can you guide me to debug it this issue

**Comment by danielroe** [comment]
Closing as there's no reproduction. Feel free to provide a reproduction and I'll happily reopen.
