### ISSUE TITLE
Router is just resetting browser scroll behaviour everytime

### ISSUE THREAD

**Issue by TimSusa** [nuxt/nuxt#9483]
### Goal
We want to restore back to the scroll position when navigating back from a link to the origin. 

### Problem 
When navigating to another link and back, the scrollposition is lost. This is especially annoying users, scrolled down to very very long pages.

# My bad Hack I had to do
I had to build in a bad hack to circumvent the issue. So I had to put this lines to the mounted function in the layouts/default.vue

``` 

  mounted() {
      window.history.scrollRestoration = 'auto';
    }
``` 

### Approach
- Avoid using this bad hack
- Do not reset the natural browser behaviour for every case by not setting the browser scroll restauration to manual, like here: https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/router.scrollBehavior.js#L9
- Maybe have a separated solution for users, who do not need the router, having an own custom solution for navigation
- establishing a router configuration option to give your users more flexibility about this: disable manual browser scroll restauration option would be fantastic

### 

### Versions

- nuxt: 2.15.7 and below
- node: 14.17.1 and below

### Reproduction
When navigating to another link and back, the scrollposition is lost. This is especially annoying users, scrolled down to very very long pages.

Adding a nuxt config is not needed, because the problem lies in the nuxt code itself for this kind of issue, we have here: https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/router.scrollBehavior.js#L9

### Steps to reproduce
When navigating to another link and back, the scrollposition is lost. This is especially annoying users, scrolled down to very very long pages.

### What is Expected?
You want to be back on the scrollposition, where you have been before.

### What is actually happening?
Always you are jumping to the top of the page.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
