### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by janooosh** [nuxt/nuxt#9511]
Dear Community,

out of nowhere, the "RangeError Maximum call stack size exceeded" error came up when running yarn dev. I have spent hours on researching the issue but could not find a solution. It never happened before.

I double checked that I am not displaying or logging any large object. I am not using Axios (we use apollo, which worked perfectly fine), and also here I am not working with large objects.

Here is the stacktrace.
<img width="1680" alt="Bildschirmfoto 2021-07-02 um 20 41 05" src="https://user-images.githubusercontent.com/19406457/124316426-dff58c00-db75-11eb-9565-cd71751e8548.png">
<img width="1680" alt="Bildschirmfoto 2021-07-02 um 20 49 35" src="https://user-images.githubusercontent.com/19406457/124317173-0536ca00-db77-11eb-9dfb-af4d601924dd.png">

I have cleaned the Yarn cache (yarn clean cache --all), deleted the nodejs Modules Folder as well as the .nuxt Folder and the Yarn.lock file and I have re-installed it with just running "yarn" -> "yarn dev". The build succeeds, but the error persists. I have also restarted the machine and cleared the browser cache. I have also tried it on different routes, even on static pages.

<img width="1315" alt="Bildschirmfoto 2021-07-02 um 20 48 11" src="https://user-images.githubusercontent.com/19406457/124317063-d91b4900-db76-11eb-864f-5d8f35b69884.png">

Has anybody experienced this before and solved it?

Thank you!

**Comment by viryl15** [comment]
in my case, it was because i uase **setInterval** inside the nuxt method **async fetch()**
