### ISSUE TITLE
Not scrolling to top on navigation (Firefox, scroll-behavior: smooth)

### ISSUE THREAD

**Issue by petrhdk** [nuxt/nuxt#9515]
### Minimal reproducible code example

+ repository: https://github.com/pitizzzle/nuxt-bugreport-not-scrolling-to-top

<br>

+ `package.json`:
    ```json
    {
        "scripts": {
            "dev": "nuxt"
        },
        "dependencies": {
            "core-js": "3.15.2",
            "nuxt": "2.15.7"
        }
    }
    ```

<br>

+ `nuxt.config.js`:
    ```js
    export default {

        // Target: https://go.nuxtjs.dev/config-target
        target: 'static',

        // Auto import components: https://go.nuxtjs.dev/config-components
        components: true,

    }
    ```

<br>

+ `layouts/default.vue`:
    ```vue
    <template>
        <Nuxt />
    </template>

    <style>
    :root {
        scroll-behavior: smooth; /* <== IMPORTANT */
    }
    </style>
    ```

<br>

+ `pages/index.vue`:
    ```vue
    <template>
        <div>
            <MyComp></MyComp>
            <NuxtLink to="/other-page/">Other Page</NuxtLink>
        </div>
    </template>
    ```

<br>

+ `pages/other-page.vue`:
    ```vue
    <template>
        <MyComp></MyComp>
    </template>
    ```

<br>

+ `components/MyComp.vue`:
    ```vue
    <template>
        <div style="
            height: 150vh;
            background: repeating-linear-gradient(#163834, #629691 100px);
            border-top: 100px solid #ff0000;
            border-bottom: 100px solid #00ffe5;
        " />
    </template>
    ```

<br>

### Steps to reproduce
+ start dev server
    ```bash
    $ git clone https://github.com/pitizzzle/nuxt-bugreport-not-scrolling-to-top.git`
    $ cd nuxt-bugreport-not-scrolling-to-top
    $ npm install
    $ npm run dev
    ```
+ open the index page (eg. `http://localhost:3000/`) in Firefox
+ scroll to the bottom of the index page
+ click the navigation button (pointing to `/other-page/` route)

+ on the new route, **the page does not scroll to the top as expected**

### Versions

|||
| --- | --- |
| Nuxt | `v2.15.7` |
| Node | `v14.15.4` |
| Browser | `Firefox 89.0.2 (64-Bit)` |

+ hint: the bug is specific to Firefox and `scroll-behavior: smooth`

**Comment by whoisjorge** [comment]
I think `scroll-behavior` property must be attached to an element with `overflow` capabilities.

```css
html {
  scroll-behavior: smooth;
}
```

Worked as expected.

**Comment by pitizzzle** [comment]
The `:root` selector is identical to the `html` selector (see [here](https://developer.mozilla.org/en-US/docs/Web/CSS/:root#:~:text=In%20HTML,%20:root%20represents%20the%20%3Chtml%3E%20element%20and%20is%20identical%20to%20the%20selector%20html)).

If the `html` selector "worked" as expected, my original `:root` selector should "work" as well. Which means, you can't reproduce the issue in the first place.
Is this the case?

**Comment by pitizzzle** [comment]
As I expected, switching from `:root` to `html` selector **did not solve the issue**.

**Comment by narduin** [comment]
I can confirm this bug still occurs.

Tool | Version
-- | --
Nuxt | v2.15.7
Node | v16.14.0
Firefox dev | v100.0b9 (64-bit)

**Comment by Extarys** [comment]
I thought I was going crazy, Works on chrome.

Tool | Version
-- | --
Nuxt | v3.0.0
Node | v16.17.0
Firefox Nightly | v111.0a1 (64-bit)

**Comment by xfvelocity** [comment]
Still not working for me on Firefox. 

Tool | Version
-- | --
Nuxt | v3.5.0
Node | v16.13.0
Firefox | v113.0.1 (64-bit)

**Comment by dkosoko23** [comment]
Still not fixed in 2024

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

**Comment by danielroe** [comment]
@JovanaMatic Would you raise a new issue with a reproduction? 🙏

**Comment by JovanaMatic** [comment]
Hi @danielroe opened a new issue - https://github.com/nuxt/nuxt/issues/28227. Thanks!
