### ISSUE TITLE
Possibility to order fetches on parent and child pages

### ISSUE THREAD

**Issue by makkarpov** [nuxt/nuxt#9517]
This issue was discussed sometime ago (#2825, #2623), but all related issues were eventually closed by bot due to inactivity. 

The basic idea is simple: when you have a parent-child page relationship, child page may want to use some information from parent page (e.g. via store) on fetch. E.g. parent page can fetch some entity from server, and child page can the use entity data to make more server queries.

Personally, I would prefer `await $fetchContext.previousFetch` over configuration parameters like 'serialFetch: true' or something.

**Comment by danielroe** [comment]
This is now possible in Nuxt 3.
