### ISSUE TITLE
Dev server error when opening more than 3 tabs on chrome

### ISSUE THREAD

**Issue by bahung1221** [nuxt/nuxt#9521]
Hi,

Currently, when I open more than 3 tabs in development mode (SPA) on chrome, the `new opened tab` and the `hot-reload` will not working, the tabs were freezing a while and then showing the error below:

```
Uncaught (in promise) Error: Manifest request to /dashboard/_nuxt/2fab9335f71ae93c4c97.hot-update.json timed out.
    at XMLHttpRequest.request.onreadystatechange (runtime.js:92)
```

If I only open 3 tabs or less, everything worked fine. The error occurs even with the fresh created nuxt app.
It seems that the problem doesn't occur on Safari.

Recorded video:
https://user-images.githubusercontent.com/27690861/124388347-b91d8e00-dd0c-11eb-8c52-f240fdf8184f.mov

### Versions

- nuxt: 2.14.12 (I also tried the latest version - v2.15.7)
- node: 12.14.0

### Reproduction

- Repository: https://github.com/bahung1221/nuxt-dev-server-error-reproduce

Thanks a lot!

**Comment by bahung1221** [comment]
Okay I found something in https://github.com/nuxt/nuxt.js/issues/6007. 

It seems this is the problem of webpack dev server, it weird that I never faced this problem before (maybe the last time I working with nuxt is one year ago, I don't remember exactly the version).
The need to open multiple tabs is important because I need to compare and preview my GUI on multiple devices size (simulators). And our designer also needs to do that, too.

Is there any workaround for this problem on chrome?
Thanks a lot 🍺

**Comment by Tobeyforce** [comment]
I had this problem as well recently and got "chunkloaderror" and "failed to load component" due to it. I do wish the documentation would give a very explicit warning about this, as opening multiple tabs is a common task.

**Comment by bahung1221** [comment]
It seems that this issue doesn't occur on Nuxt SSR mode, only occurs on SPA mode.

**Comment by danielroe** [comment]
This is no longer reproducible in Nuxt 3.
