### ISSUE TITLE
nuxt-link-active is case sensitive 

### ISSUE THREAD

**Issue by RyanNorooz** [nuxt/nuxt#9527]
### Versions

- nuxt: 2.15.6
- node: 15.12.0

### Problem

<details>
<summary>Example code</summary>
<br>

```vue
<template>
  <div>
    <NuxtLink to="/">Home</NuxtLink>
    <NuxtLink to="/about">About</NuxtLink>
  </div>
</template>

<style>
.nuxt-link-active { color: #8a1ec9 }
.nuxt-link-exact-active {  color: #ddc77f }
</style>
```
</details>

the styles for `nuxt-link-active` will show if you go to this route: `/about`
but it won't work if you go to: `/About` or `/aBoUt`

### What is Expected?
links should get the `nuxt-link-active` class regardless of the word-casing of the route

### What is actually happening?
routes with different caseing will not activate the `nuxt-link-actice` styles

**Comment by RyanNorooz** [comment]
also apparently the `nuxt-link-active` class won't be added if there are any url queries in the web address

example for this link -> `/about`
will match: `/about` 
won't match: `/about?tab=1` 

**Note:** to make changes take place you need to refresh the page.

**Comment by danielroe** [comment]
This is an upstream issue in `vue-router`. If you're still experiencing this, please do file an issue in https://github.com/vuejs/router.
