### ISSUE TITLE
Saving tailwind css file several times leads to memory error

### ISSUE THREAD

**Issue by Dania99dev** [nuxt/nuxt#9528]
### Versions

- nuxt: v2.15.7
- node: v14.17.1

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
Just install tailwind and change its css file in assets a bunch of times

### What is Expected?
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

**Comment by Dania99dev** [comment]
> @Dania99dev Is this with the `@nuxtjs/tailwindcss` module?

Yes it is

**Comment by danielroe** [comment]
This doesn't sound like an issue with Nuxt. If you're still experiencing this, please raise it upstream at https://github.com/tailwindlabs/tailwindcss/.
