### ISSUE TITLE
Support loading scoped node_modules files in short format

### ISSUE THREAD

**Issue by Fnxxxxo** [nuxt/nuxt#9534]
### Is your feature request related to a problem? Please describe.

Currently, I am using Nuxt v2.14.12. Some properties in nuxt.config.ts only support node modules, like `@scoped/modules`, and files, like `~/some-files`. But it does not support using specific files in modules like `@scoped/modules/dist/some-file`

### Describe the solution you'd like

Just read files in node_modules when meets `@scoped/modules/dist/some-file` in css, plugins, modules and other properties.

### Describe alternatives you've considered

Currently, I use workaround like `'../../../node_modules/@scoped/modules/dist/some-plugin' to setup plugins. But it will falls when I use workspace since I dont know which node_modules folder should be read.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
