### ISSUE TITLE
Transitions: accessing this inside enter & leave functions

### ISSUE THREAD

**Issue by antinomy-studio** [nuxt/nuxt#9536]
### Is your feature request related to a problem? Please describe.

I've been working with Nuxt.js a lot, and always having issues with page transitions as `this` exposed is actually the `<Nuxt />` component, rather than the page component itself. This issue is pretty much a duplicate of https://github.com/nuxt/nuxt.js/issues/2374

### Describe the solution you'd like

It would be great to be able to access the current component instance in `beforeEnter`, `enter`, `beforeLeave` and `leave` methods.

I am currently able to get the reference of the component inside `enter` function by looking intro `this.$children`. However, when I am trying to do the same but in the `leave` function, the current component isn't in the `$children` array anymore.

### Describe alternatives you've considered

I'm really not sure if this would be possible and/or break the current design, but it would make sense to me if `this` would refer to the page component where the transition is applied.

### Additional context

Here's a repository: https://github.com/antinomy-studio/nuxt-transition
Here's a demo: https://nuxt-transition-demo.netlify.app

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
