### ISSUE TITLE
Using generate with more than one interval

### ISSUE THREAD

**Issue by siolfyr** [nuxt/nuxt#9537]
### Is your feature request related to a problem? Please describe.

I love Nuxt, Static site generation, and APIs. I have a site with dynamic routes which I use the nuxt.config.js **generate** option to pre-populate. But, I have 3 different types of routes: routes defined by a JSON file, routes that rely on a good API, and routes that rely on a bad API which needs a high interval in order to generate. There are a lot of them, and it leads to slow build times.

It would be amazing if I could use a small interval for things like loading from JSON files and hitting a strong API which can handle the requests, but use a large interval for the bad API which I am forced to use because of business reasons.

### Describe the solution you'd like

Do you think it would it be possible to make **generate** an array of objects, instead of an object? E.g.

```
  generate: [{
    interval: 100,
    async routes () {
      // JSON stuff, API stuff, etc
    }
  },
  {
    interval: 500,
    async routes () {
      // Frail API stuff
    }
  }],
```

Sorry if something like this already exists, but I couldn't find it if it does! Thanks for reading.

**Comment by simeon9696** [comment]
A quick work around I can think of would be to wrap all of your routes in a setTimeout and the timeout programmatically increases (each iteration of your route array) based on your requirements . Have each timeout return a promise and then await all your promises.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
