### ISSUE TITLE
Head property as function in config file prevents google fonts from loading

### ISSUE THREAD

**Issue by KaragiannidesAgapios** [nuxt/nuxt#9543]
### Versions

- nuxt: v2.15.0
- @nuxtjs/google-fonts: 1.3.0

### Reproduction
https://codesandbox.io/s/head-property-as-function-nliyb?file=/nuxt.config.js

<details open>
<summary>Additional Details</summary>
<br>
Using head property as function in nuxt.config file, which according to documentation is available as type,  prevents google fonts from loading.
</details>

### Steps to reproduce
1. Install nuxt project.
2. Install [@nuxtjs/google-fonts](https://google-fonts.nuxtjs.org/).
3. Follow the fonts setup as documentation instructs.
4. Make sure that you have the font you want (check `<head>` html element for the expected `<link>` to exist).
5. Now use `head` property as function and return an object with the same properties.
6. Make sure to restart your project with `npm run dev` so all changes to take place.

### What is Expected?
That the fonts will load normally

### What is actually happening?
Google Fonts are not loading.

##### Additional help
Please let me know if should I open a related issue in [@nuxtjs/google-fonts](https://github.com/nuxt-community/google-fonts-module) as a more appropriate place for this issue to be tackled.

**Comment by danielroe** [comment]
This is an upstream issue in the Google Fonts module. Would you raise the issue there if it's still relevant for you?
