### ISSUE TITLE
Support for the experimental syntax 'decorators-legacy' isn't currently enabled 

### ISSUE THREAD

**Issue by zaberz** [nuxt/nuxt#9551]
### Versions

- nuxt: v2.15.7
- node: v14.16.1

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

Can't use decorators in serverMiddleware by javascript
</details>

### Steps to reproduce
Add to any javascript in serverMiddleware the property decorator

### What is Expected?
It should work

### What is actually happening?
Displayed error during build:
 ERROR  ServerMiddleware Error: ParseError: Support for the experimental syntax 'decorators-legacy' isn't currently enabled

**Comment by zaberz** [comment]
> @zaberz Could you check what version of `jiti` you have installed? (You could run `yarn why jiti` or `npm ls jiti`). Would you also provide an example of the code that isn't working for you?

Thanks for your reply, the code just like this:
[https://codesandbox.io/s/red-sun-lsqi9?file=/serverMiddleware/index.js](https://codesandbox.io/s/red-sun-lsqi9?file=/serverMiddleware/index.js)

and in my project, `jiti` version is v1.10.1
```
└─┬ nuxt@2.15.7
  ├─┬ @nuxt/telemetry@1.3.6
  │ └── jiti@1.10.1 
  └─┬ @nuxt/utils@2.15.7
    └── jiti@1.10.1  deduped
```

**Comment by danielroe** [comment]
Closing as there is no longer a reproduction at that link. Let me know if this is something you are still experiencing.
