### ISSUE TITLE
publicPath no longer obeyed when modifying in build:before

### ISSUE THREAD

**Issue by hecktarzuli** [nuxt/nuxt#9554]
### Versions

- nuxt: 2.15.1
- node: v14

### Reproduction
**Works in 2.14.12**
https://codesandbox.io/s/nuxt-public-path-2-14-8koqf
Use a module to listen to build:before and then modify the passed buildOptions.publicPath
```
export default function () {
  this.nuxt.hook("build:before", (nuxt, buildOptions) => {    
    buildOptions.publicPath = "/my-prod-path/";    
  });
}
```
Notice the urls are rendered right, and serve the file contents.

![image](https://user-images.githubusercontent.com/2112282/125457837-55d54e9e-b99e-4a70-ba10-3fb06001d2ec.png)

**Doesn't work in 2.15.1**
Repeat the same steps using Nuxt 2.15+
https://codesandbox.io/s/nuxt-public-path-2-15-y0v1w

Now the rendered urls are the _nuxt default but 404
![image](https://user-images.githubusercontent.com/2112282/125459076-ab550a22-cd5f-44cb-8c40-4e9540abf5cb.png)
But they are actually being served from the publicPath we requested
![image](https://user-images.githubusercontent.com/2112282/125459192-4c8adf50-90aa-4ef2-bd63-d0ba70a9bc2b.png)

### What is Expected?
I would have expected the old way to continue to work and not break.

### What is actually happening?
Script paths are going back to their default of _nuxt, while the files themselves are being served with the requested publicPath.

Seems related to https://github.com/nuxt/nuxt.js/pull/8520/files

**Comment by danielroe** [comment]
The publicPath is now set with `app.publicPath` rather than directly in `build.publicPath`
