### ISSUE TITLE
Nuxt-child not waiting for parent asyncData to finish

### ISSUE THREAD

**Issue by justinwride** [nuxt/nuxt#9568]
### Versions

- nuxt: 2.15.7
- node: 12.20.1

### Reproduction

https://github.com/justinwride/nuxt-child-asyncdata-bug

### Steps to reproduce

Start the Nuxt project in included repo and navigate to http://localhost:3000/child

### What is Expected?

The NuxtChild page should show the correct data from the store inserted by the parent component in `asyncData`.

I expect that the `asyncData` in the parent component will finish and be available to `NuxtChild` before `NuxtChild` is rendered.

### What is actually happening?

> TypeError: Cannot read property 'id' of null

The NuxtChild component does not have access to the data in the store inserted by the parent component.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
