### ISSUE TITLE
Nuxt in production mode is not loading page function properly

### ISSUE THREAD

**Issue by shahriar350** [nuxt/nuxt#9575]
I use vuetify in nuxt ssr. In development mode, everything is good but when i move to production mode, it shows some problem of loading functionality. 
[https://vimeo.com/577099166](https://vimeo.com/577099166)
you can watch this video of mine.
why in initial loading nuxt page is not working properly. but after go back to another layout page (seller page is belongs to another layout page), all functionality works fine.
N.B: i use default settings of nuxt. i haven't add extra setting in nuxt.config
i have two layout -> default and seller (for seller only)

**Comment by danielroe** [comment]
There's not enough information here to investigate, and there is no reproduction. If you are able to provide one that shows that this is an issue with Nuxt, I'll happily reopen.
