### ISSUE TITLE
Nuxt fails to update newly added images when running yarn build and yarn generate

### ISSUE THREAD

**Issue by suit4** [nuxt/nuxt#9586]
I built a simple image viewer that reads a series of images from a folder in the static folder and displays them one after another.

When I change some of the images to include new ones and replace old ones, I can see them in the resulting image viewer when running `yarn dev` and visiting http://localhost:3000. 

However, when I run `yarn build && yarn generate`, the resulting _dist_ contains all new or changed images, whereas _dist/_nuxt_ contains some of the old image. Accessing the page on a server then shows the old images, not the new ones.
Those files seem to be serve _dist/_nuxt_. 

I tried to force a clean build by deleting _.nuxt_ and _dist_.
After running `yarn build && yarn generate `again, the same file structure was generated, with old images instead of new ones.

Examining further, I found the old files in _node_modules/.cache/nuxt/dist/client_. The build process seems to use these files to speed up the process.

Clearing the _.cache_ lead to a situation, where yarn generate failed with 
`Error: No build files found in /var/www/vhosts/domainname/subdomainname/node_modules/.cache/nuxt/dist/client.   │
   │   Please run `nuxt build` `

The only solution I found to trigger a complete new generation of all new image files was to make pseudo changes in _nuxt.config.js_.

My expectation is, that running `yarn build && yarn generate` always leads to a fresh build containing all new files and not containing old files.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
