### ISSUE TITLE
Unable to disable error page handling

### ISSUE THREAD

**Issue by alexcroox** [nuxt/nuxt#9612]
### Versions

- nuxt: v2.15.7
- node: v14.15.1

### Problem

I am trying to disable Nuxt's default error handling where it tries to redirect to the error page on any JS error.

I have a plugin to disable this behaviour:

```
// Stop Nuxt redirecting uncaught errors to the error page
export default function ({ app, $log }) {
  if (process.client) {
    app.nuxt.error = error => {
      console.error('Unhandled exception', error)
      $log.error('Unhandled exception', error)
    }
  }
}
```

However it does not stop Nuxt changing the Layout of the page being used, and I would like to keep the user on the same page and show an error. The switch of the active layout to the Error one causes display issues if I keep the user on the same page, how do I disable this additional Nuxt behaviour?

### Steps to reproduce
Trigger a JS error

### What is Expected?
Nuxt not to redirect to the error page or change the active Layout template.

### What is actually happening?
Nuxt doesn't redirect, but still changes the active Layout being used, breaking my site.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
