### ISSUE TITLE
`createNext` method ignores runtime `basePath` property

### ISSUE THREAD

**Issue by reinisp** [nuxt/nuxt#9625]
### Versions

- nuxt: v2.15.7
- node: v14.17.3

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

```
  const $config = ssrContext.runtimeConfig || {}
  const routerBase = ($config._app && $config._app.basePath) || '<%= router.base %>'
```

snippet from https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/server.js#L62 always fallback to `'<%= router.base %>'` as `$config._app` is always undefined. 
It could be accessed either from `$config.public._app.basePath ` or `$config.private._app.basePath `

</details>

### What is Expected?
When using `redirect('/some-path')` on server side it reads `basePath`  property from `runtimeConfig` if exists

### What is actually happening?
When using `redirect('/some-path')` on server side it always prepends `route.base` property defined un `build`

**Comment by reinisp** [comment]
Current workaround by adding hook: 
```
    'vue-renderer:ssr:prepareContext': (ssrContext) => {
      const { runtimeConfig } = ssrContext;

      if (runtimeConfig && !runtimeConfig._app && runtimeConfig.public?._app) {
        runtimeConfig._app = runtimeConfig.public._app;
      }
    },
```

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
