### ISSUE TITLE
router.mode hash conflicts overriden config.output.publicPath since Nuxt 2.15, works when rolling back to 2.14

### ISSUE THREAD

**Issue by eLvErDe** [nuxt/nuxt#9632]
Hello Nuxt team,

I use the following "hack" tu run NuxtJS app inside a dynamic context path by modifying nuxt.config.js like this:

```javascript
  // Build Configuration: https://go.nuxtjs.dev/config-build
  build: {
    extend(config, ctx) {
      //
      // LOCAL /!\ Load _nuxt folder from relative link so it can work in a dynamic context path
      // https://github.com/nuxt/nuxt.js/issues/2892
      //
      if (!ctx.isDev) {
        config.output.publicPath = './_nuxt/'
      }
    },
  },
  //
  // LOCAL /!\ Use hash router so it does not forget about context path
  // https://github.com/nuxt/nuxt.js/issues/3687#issuecomment-440129654
  //
  router: {
    mode: 'hash',
  },
```
I just started over a new project and it seems Nuxt 2.15 broke this setup, before adding router.mode hash it worked and I could see the Nuxt app loading when served from /whatyouneed/ using dist/ served with a webserver.

After enabling router.mode hash, it's not loading anymore and I can see the generated URLs being /_nuxt/ instead of /whatyouneed/_nuxt/.

Rolling back to 2.14.12 by doing:

```
yarn add nuxt@2.14.12
yarn add @babel/preset-env@7.12.17
```

And the project works as expected again.

Can you have a look and tell me if it's expected ? I really have the feeling that for some reason config.output.publicPath is not used anymore when selecting hash router.

Best regards, Adam.

**Comment by eLvErDe** [comment]
If I understand correctly, some stuff have been added in 2.15 to render publicPath configurable at runtime....

However, there's NO documentation about how to this so I have no idea how to do this. I tried to hack around using a plugin containing this:

```javascript
/*eslint-disable */

export default function({$config}) {
  const windowPath = window.location.pathname.split('/')[1].replace('/^\/+', '').replace('/^\/+$', '')
  const runtimeBasePath = windowPath ? `/${windowPath}/'` : '/'
  const runtimeAssetsPath = windowPath ? `/${windowPath}/_nuxt/'` : '/_nuxt/'
  console.log(`Overriding config._app.basePath from ${$config._app.basePath} to ${runtimeBasePath}`)
  console.log(`Overriding config._app.assetsPath from ${$config._app.assetsPath} to ${runtimeAssetsPath}`)
  $config._app.basePath = runtimeBasePath
  $config._app.assetsPath = runtimeAssetsPath
}
```

That seems to help, as the app loads but the router is confused and return 404 for index. Any hint would be greatly appreciated...

**Comment by eLvErDe** [comment]
```javascript
/*eslint-disable */


export default function(context, inject) {
  const windowPath = window.location.pathname.split('/')[1].replace(/\/+$/, '')
  const runtimeBasePath = windowPath ? `/${windowPath}/` : '/'
  const runtimeAssetsPath = windowPath ? `/${windowPath}/_nuxt/` : '/_nuxt/'
  console.log(`Overriding context.$config._app.basePath from ${context.$config._app.basePath} to ${runtimeBasePath}`)
  console.log(`Overriding context.$config._app.assetsPath from ${context.$config._app.assetsPath} to ${runtimeAssetsPath}`)
  console.log(`Overriding context.app.router.options.base from ${context.app.router.options.base} to ${runtimeBasePath}`)
  context.$config._app.basePath = runtimeBasePath
  context.$config._app.assetsPath = runtimeAssetsPath
  context.app.router.options.base = runtimeBasePath
  for (const route of context.app.router.options.routes) {
    console.log(route)
    const fixedRoute = (runtimeBasePath + route.path).replace(/\/+/g, '/')
    console.log(`Overriding context.app.router.options.routes entry from ${route.path} to ${fixedRoute}`)
    route.path = fixedRoute
  }
}
```

Also tried to add my prefix to routes entries inside router, not working either... Rolling back to Nuxt 2.14, seems that feature is really impossible to implement with 2.15.0+ :/

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
