### ISSUE TITLE
/nuxt.config.js is not in cwd 

### ISSUE THREAD

**Issue by dot357** [nuxt/nuxt#9640]
## Greetings,

While I am trying to generate the NUXT app I encountered an issue. 

### Steps to reproduce
>cd into the folder.
>npm run build
>npm run generate 

![bug](https://user-images.githubusercontent.com/15169968/128597123-728f8b5c-275b-4bfc-b9d1-cef13f882fa4.jpg)

### Versions
-nuxt : 2.15.7
-node : v14.17.1
-npm :  7.20.1

### What is Expected?
>I expected to get the dist folder. But didn't happened.

### What is actually happening?
>Giving "/nuxt.config.js is not in cwd "  error. When I try to run the same npm run generate command at Ubuntu or a Linux machine, it works flawlessly, but my Windows system gives an error mentioned above.

**Comment by manniL** [comment]
Pretty sure this is related to how windows treats paths vs. Unix (`/` vs. `\`).

Related: #7792, #7796

**Comment by 404NoSkill** [comment]
The error popped out today again , with fresh project and a project made yesterday

**Comment by ZTF666** [comment]
> 
> 
> The error popped out today again , with fresh project and a project made yesterday .
> But works flawlessly on linux

just normalized the path here as it's been suggested in one of the replies in the following file 
node_modules\@nuxt\cli\dist\cli-generate.js  as below : 

```javascript
  const files = await globby__default['default']('**/*.*', {
    ...globbyOptions,
    ignore,
    cwd: upath.normalize(rootDir),
    absolute: true
  });
```

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
