### ISSUE TITLE
Nuxt router breaks Google Crawler for my static site

### ISSUE THREAD

**Issue by bblay** [nuxt/nuxt#9656]
Hi, Nuxt routing seems to be unusable in my static site. It breaks SEO and I can't seem to find a good config solution to fix it.

### Versions
- nuxt: v2.15.7
- node: v14.0.0

### Reproduction
I'm not sure I can provide a minimal reproduction as it requires a sitemap being sent to the google search console.

### Steps to reproduce
Give a Nuxt site & sitemap to the google search console and wait for the crawl results.
No router config in _nuxt.config.js_.

### What is Expected?
Nuxt to work with Google Crawler.

### What is actually happening?
Google Crawler reports redirect error.

### Details
<details open>

Out of the box, with no router config in _nuxt.config.js_, Google Search's Coverage page reports a redirect error, [which means](https://support.google.com/webmasters/answer/7440203?hl=en) _"A redirect chain that was too long; a redirect loop; a redirect URL that eventually exceeded the max URL length; there was a bad or empty URL in the redirect chain."_ Surely I'm not the only person to hit this?

~Working locally, I tried setting `trailingSlash` to `true` but NuxtLink stopped working, causing a not found error~. I'd rather avoid trailing slashes, if possible, as they look weird.

~That seems to leave me with one more option,~ setting `trailingSlash` to `false`. I'll accept this if it works, but it **_adds_** a trailing slash to the url in the browser, which seems like a bug, so I'm reluctant to use that in case it's fixed with a breaking change in the near future.

In case it's relevant, this crawler error is happening on a dynamic route, but that could just be because it's the first page it found since I migrated to Nuxt and updated the sitemap.

I feel I must be doing something wrong. Surely it should work out-of-the-box with Google Crawler?

#### Secondary concern
A secondary concern is that the network tab always shows a redirect from the non trailing slash url to the trailing slash, regardless of the url shown in the browser and the `trailingSlash` config. Is this expected?

**Comment by bblay** [comment]
Previewing locally, I also noticed that without a router config, i.e the scenario which breaks the crawler, when I send the browser to the non-slash url a trailing slash quickly appears then disappears on the url bar.

**Comment by danielroe** [comment]
I would guess you might be deploying to netlify, which automatically adds trailing slashes to your urls. (Or it might be a similar issue on another provider.)

But it's not possible to investigate without a reproduction or more info. (You can ignore the trailing slash behaviour when previewing locally; it's a glitch caused by `serve-static`, not an issue with Nuxt.) For what it's worth, we have a different solution for trailing slashes in Nuxt 3 which is not prone to this issue.
