### ISSUE TITLE
publicPath not included first time when building for production

### ISSUE THREAD

**Issue by mrkazu** [nuxt/nuxt#9657]
Hello!
When building for production. SPA (not ssr) the buildpath is not included. that means nuxt is giving a "_nuxt" prefix to the manifest path. for example dist/index.html "href="https://domain.com/subpathToApp/_nuxt/manifest.d03e541b.json"

however. if i run the same command again "npm run build" the prefix "_nuxt" is removed and everything works great.
"href="https://domain.com/subpathToApp/manifest.d03e541b.json"

The manifest.json file is always located in the root folder of dist. so when adding "_nuxt" the manifest file wont be found.

this hapens everytime i make changes to any file in my vue project.
its no big issue since running the command two times resolves the issue. but its a bit enoying :)

#nuxt.config.js:
router: {
    middleware: ["auth", "vma", "weatherWarnings"],
    base: "/subpathToApp",
    mode: "history"
  },

  build: {
       publicPath: "https://domain.com/subpathToApp"
  }

### Versions

- nuxt: 2.15.7
- node: 14.16.1

### What is Expected?
Include publicPath at build. set the path in index.html to correct path for the manifest.json file

### What is actually happening?
Need to run "npm run build" two times to include the publicPath in nuxt.config.js

**Comment by danielroe** [comment]
This should now be resolved in Nuxt 3.
