### ISSUE TITLE
Relative URLs in CSS are converted to absolute even when build.publicPath is relative

### ISSUE THREAD

**Issue by euoia** [nuxt/nuxt#9664]
### Versions

- nuxt: 2.15.7
- node: v14.17.0

### Reproduction

1. Reference a resource, e.g. a font using a relative URL in your CSS, e.g.

```
@font-face {
  font-family: "Open Sans";
  font-style: normal;
  font-display: swap;
  font-weight: bold;
  src: url("./Open_Sans-700-latin20.woff2") format("woff2");
}
```

2. Set up your site for static hosting (i.e. nuxt.config `target: 'static'`)

3. Use a relative path in nuxt.config's build.publicPath:

```
  build: {
    publicPath: "./_nuxt"
  }
```

4. Run `nuxt generate`

5. Upload your `dist/` directory to a subdirectory in a web server, e.g. https://example.com/my/awesome/site

6. Observe the the font is not loaded (it will try to load from https://example.com/Open_Sans-700-latin20.woff2 instead of  https://example.com/my/awesome/site/Open_Sans-700-latin20.woff2)

### What is Expected?

There ought to be some way to generate a static site such that all resources are referenced relatively.

This issue is somewhat similar to some other issues including:
#9170 

### What is actually happening?

The font's path is being rewritten to be relative to the root.

### Demonstration Repository

I made a repository which demonstrates and explains this issue here:
https://github.com/euoia/nuxt-generate-url-bug

**Comment by orvn** [comment]
This issue still exists in the latest version of `nuxt-edge`, and therefore should not have the `stale` tag

**Comment by atipezda** [comment]
bump, same here

**Comment by YutaMoriJP** [comment]
@orvn Hi, did you find a solution or a workaround for this?

**Comment by orvn** [comment]
> @orvn Hi, did you find a solution or a workaround for this?

Yeah, we use this [Nuxt module](https://github.com/agency-undone/nuxt-module-ipfs) to allow relative paths. I don't know if this feature will be worked into Nuxt 2 at this point, but the module seems to work fine for our purposes (on multiple large-scale static site projects).

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
