### ISSUE TITLE
Define route with param in Nuxt's serverMiddleware?

### ISSUE THREAD

**Issue by marvelefe** [nuxt/nuxt#9673]
I'm trying to define a dynamic route param in Nuxt's serverMiddleware, but I'm not able to figure out how to achieve it because in the doc also there is no any mention about dynamic route.

I want to achieve something like this,

```
 //nuxt.config.js
export default {

    modules: [
      ..
    ],

  serverMiddleware: [
    '~/serverMiddleware/selectiveSSR.js', 
  ]

} 
```

And in the middleware file:

```
//selectiveSSR.js
export default function(req, res, next) {

    const paths = ['/', '/_id', '/:id']   
    
    if (!paths.includes(req.originalUrl)) { 
      res.spa = true
    } 

    next()
  }

```

**How do i match a dynamic route while on the server?**

Just to inform, I'm using Nuxtjs in Unviersal mode with Nodejs as a rendering server. And this is the link which I'm referring for using  [Nuxt serverMiddleware](https://nuxtjs.org/api/configuration-servermiddleware/#custom-server-middleware)

**Comment by wxhon** [comment]
+1

**Comment by lucpotage** [comment]
Hi @marvelefe,

There is no connection between the `serverMiddleware` and the file structure used by Nuxt for the route creation. It's done after the server middleware starts.

What you could eventually do is using a regex to match the `:id` (I use one that matches alphanumeric, underscore, and hyphen):

```js
export default (req, res, next) => {
  const regex = /\/[\w-]+$/g
  if (req.originalUrl.matches(regex) {
    res.spa = true
  }
  next()
}
```

Would this work for you?

**Comment by jgmdigital** [comment]
Hi @marvelefe,

In case anyone is having a similar issue, we have found a potential solution, here is a simple example of how to access a param:

User visits https://examplesite.co.uk/custom-path/247

// nuxt.config.js
serverMiddleware: [
   '~/server-middleware/custompath.js',
]

// ~/server-middleware/custompath.js

const express = require('express')
const app = express()

app.get('/:id', async (req, res, next) => {
    // req.params.id is now accessible ie. 247

    next()
})

module.exports = {
    path: '/custom-path',
    handler: app,
}

---

Hope this helps point you in the right direction.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
