### ISSUE TITLE
Cannot read property 'call' of undefined (2.15.7)

### ISSUE THREAD

**Issue by hecktarzuli** [nuxt/nuxt#9684]
There seems to be a problem with hot-reloading in dev when you use modern: client.
We randomly get the error.
```
Uncaught TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (runtime.js:854)
    at fn (runtime.js:151)
    at Object.0 (app.js:4343)
    at __webpack_require__ (runtime.js:854)
    at checkDeferredModules (runtime.js:46)
    at Array.webpackJsonpCallback [as push] (runtime.js:33)
    at app.js:1
```
When you dig into the error you see that webpack is trying to load the `client` instead of `modern`

moduleId that's passed to the function is 
`./node_modules/webpack-hot-middleware/client.js?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client`
instead of
`./node_modules/webpack-hot-middleware/client.js?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fmodern&name=modern`

![image](https://user-images.githubusercontent.com/2112282/129766438-8476d72d-adff-43dd-b8db-967374d9e23f.png)

### Versions

- nuxt: 2.15.7
- node: 14.17.3

### Reproduction

I'm not sure how to reproduce other than enable `modern:client` in a project and do some dev to trigger hot-reloading.  It happens randomly to us.

### What is Expected?
No critical error
### What is actually happening?
A critical error that bricks the dev env, even on refresh.

Related, but seems different: https://github.com/nuxt/nuxt.js/issues/7918

cc: @clarkdo @pi0 @danielroe

**Comment by danielroe** [comment]
Closing as there's no reproduction. Feel free to provide a reproduction and I'll happily reopen.
