### ISSUE TITLE
Delay Smart Prefetch until OnNuxtReady has been dispatched

### ISSUE THREAD

**Issue by gquinteros93** [nuxt/nuxt#9719]
### Is your feature request related to a problem? Please describe.

**It's not a problem**, it's an improvement request 😄 .

Smart Prefetch is amazing 🚀 , However, when the `NuxtLink` are visible in the viewport while the page is loading, those prefetches are being executed at the same time we are loading content that is necessary for our current page.

For example, let's say that the `NuxtJs` Logo and the `Introducing Smart Prefetching` are `NuxtLinks`, so the corresponding HTTP request for the prefetching will be executed at the same time we are loading content that we need for our current page, example, the image.

![image](https://user-images.githubusercontent.com/53574912/131147239-92cfc829-633c-45fb-9d74-4a6289d91289.png)

I believe it would be great to execute the prefetch after the current page has finished loading and it's ready to use.

### Describe the solution you'd like

Thanks to [window.onNuxtReady](https://nuxtjs.org/docs/2.x/concepts/context-helpers#onnuxtready-helper) we know when our Nuxt.js application has been loaded and is ready to use. 

So, I was thinking of adding an option for [SmartPrefetching](https://nuxtjs.org/blog/introducing-smart-prefetching) to wait until the `window.onNuxtReady` has been dispatch to executes the prefetch.

### Describe alternatives you've considered

I did a custom solution that consists of a [Nuxt Plugin ](https://nuxtjs.org/docs/2.x/directory-structure/plugins) that executes on the client, I named it: `plugins/prefetch-links.js`:

```
export default async function ({ app }, inject) {
  const prefetch = { value: false }
  inject('prefetchLinks', prefetch)
  window.onNuxtReady(() => {
    app.$prefetchLinks.value =  true
  })
}
```

It's a simple flag that is set on `true` after  `window.onNuxtReady` has been executed.

Later on my `NuxtLink` I set the [:prefech](https://nuxtjs.org/docs/2.x/features/nuxt-components#disable-prefetching-for-specific-links) property to be equal to my plugin value `$prefetchLinks?.value`:

```
<NuxtLink to="/about" :prefetch="$prefetchLinks?.value">About page not prefetched yet</NuxtLink>
```

This approach works. **However**, I believe this could be included in the [Smart Prefetch](https://nuxtjs.org/blog/introducing-smart-prefetching) config/approach.

### Additional context

Nothing else to add. Thanks for reviewing this ticket.

**Comment by danielroe** [comment]
We now do this in Nuxt 3: https://github.com/nuxt/framework/pull/9478
