### ISSUE TITLE
ie9 keep reloading

### ISSUE THREAD

**Issue by akan** [nuxt/nuxt#9730]
### Versions

- nuxt: ^v2.15.4
- node: ^v14.14.0

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>
 fix(vue-app): reload page once after loading chunk error #8978 

this bug fix is not compatible with ie9. Webpages keep reloading in ie9 browser. when change back to nuxt@2.15.3, it is ok.

### Steps to reproduce
make a nuxt app,
npm run build
npm start
use ie 11 emulator ie9

### What is Expected?
the website is normal viewed.

### What is actually happening?
each page is reloading endless. the most simple page is also keeping reload.

**Comment by salamAbbass** [comment]
salam20z

**Comment by vortesnail** [comment]
have the same problem.

**Comment by XzyZachary** [comment]
It still has issues, isn't it going to fix this?

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
