### ISSUE TITLE
extractCSS along with using aliases causing missing CSS chunks on SSR

### ISSUE THREAD

**Issue by daniluk4000** [nuxt/nuxt#9768]
### Versions

- nuxt: v2.15.7
- node: v14.15.1

Also tested in Nuxt Edge 2.16.0-27172816.2ef05373

### Reproduction

https://github.com/daniluk4000/nuxt-routes-bug

### Steps to reproduce
1. Turn off JS on localhost using some plugin (to prevent hydration)
2. Execute yarn install && yarn build && yarn start (only happens in Production mode because extractCSS were configured like that)
3. Open `http://localhost:3000/page/1`. Notice that some page chunks are missing on SSR (both JS and CSS) and being added after hybration starts working
4. Open `http://localhost:3000/page-alias/1`. Notice that `background: red` style is working just fine and all chunks are loaded
5. Reopen `http://localhost:3000/page/1`. Chunks are loaded again and working just fine. 

### What is Expected?
Alias doesn't affect my original page. All chunks, both CSS and JS are being added on SSR side and correctly being used on CSR.

### What is actually happening?
Alias affects it's original page and chunks for this page are missing until you open alias.

### But Dani, why you add alias like this?
This way was recommended by Nuxt co-author in #432

To be honest, I develop on Nuxt for 2+ years. This is most weird bug I've ever seen. If I did some stupid mistake please correct me (and is there any other way except using extendRoutes). 

Cheers!

**Comment by daniluk4000** [comment]
Workaround: use extendRoutes with alias property

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️
