### ISSUE TITLE
nuxt generate static calls asyncData with firebase serve

### ISSUE THREAD

**Issue by gabrielsze** [nuxt/nuxt#9774]
First off, thanks @danielroe for the PR to close issue #9734. 

I fired up the repro that I shared and it worked for the edge cases with "&", and while serving via `npx nuxt serve` works, but on using firebase on my main app to serve `firebase serve`, still calls asyncData after the pages are generated - same issue #9734 for brand names with "&". 

### Versions

- nuxt-edge: 2.16.0-27184333.6f94b1f9

### Reproduction

https://github.com/gabrielsze/nuxtStaticTest

### Steps to reproduce

- run `npm run generate`
- Instead of immediately serving via `npx nuxt serve`, do a `firebase init`, create a dummy firebase project, and once the firebase setup is done, run `firebase serve`
- fire up localhost:5000
- console log happens for **Mixed Grill & Greens** and **The Coffee Bean & Tea Leaf**

### What is Expected?
- asyncData should not be called on the client-side
- nuxt-edge should have fixed this case in PR #9739

### What is actually happening?
- asyncData is console logging on generated pages when using `firebase serve` for routes with "&".

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
