### ISSUE TITLE
Nuxt hooks not executed when redirection chain returns to the same page

### ISSUE THREAD

**Issue by Kelmatou** [nuxt/nuxt#9789]
Sometimes pages will navigate to a page that will redirect to another... and it may eventually return to the first page that initiated all this.

Each time there is a redirection, we navigate to this new page and therefore some Nuxt hooks will be called (middleware in particular). This allows the Nuxt app to perform any kind of operation/logic.

However it seems that all hooks are called, except if the redirection destination is the context.from page.
This breaks the logic that middleware should be called when navigating to another page.

Middleware (global or page) can modify the store state. Not having the possibility to modify it upon returning to the first page can put the app in a bad state.

Examples:

- Case described, B redirects to A:

> **Actual**
> A -> _global middleware_ -> _page B middleware_  -> A
> **Expected**
> A -> _global middleware_ -> _page B middleware_  -> _global middleware_ -> _page A middleware_ -> A

- If the redirection never goes back to the first page, we can create a redirection loop. This is fine, it's the developer's responsibility to prevent this. Here B redirects to C and C to B:

> A -> _global middleware_ -> _page B middleware_  -> _global middleware_ -> _page C middleware_ -> _global middleware_ -> _page B middleware_ ...(infinite loop)

### Versions

- nuxt: 2.15.x
- node: 14.16.0

### Reproduction

This code sandbox demonstrates the issue, see the Steps to reproduce.

https://codesandbox.io/s/relaxed-tereshkova-e450p?file=/README.md

### Steps to reproduce

- Go to **page A** at /A
- Check the console, global middleware runs, then middleware A
- Now click on the link to go to **page B** at /B

### What is Expected?

When clicking on the link to **page B**, global middleware runs.
Then page B middleware (because we navigate)
Then when middleware of **page B** decides to redirect to **page A**, global middleware and page A middleware should be executed, because we navigate again to **page A**. We can't consider we stayed on the same page, because then why did we run middlewares for page B, who potentially modified the vuex store

### What is actually happening?

When middleware of **page B** redirects to **page A**, global middleware and middleware of **page A** are not called.

**Comment by danielroe** [comment]
This is upstream `vue-router` behaviour. You are welcome to raise an issue there: https://github.com/vuejs/vue-router.
