### ISSUE TITLE
Adding a route in the nuxtServerInit hook.

### ISSUE THREAD

**Issue by n4ks** [nuxt/nuxt#9794]
### Versions

- nuxt: 2.15.7
- node: 14.17.3

### Reproduction
https://codesandbox.io/s/pedantic-voice-3syne?file=/store/index.js

### Steps to reproduce
I need to get an array of routes from the CMS and dynamically generate router (static won't work for me, I need to change routes dynamically and I use SSR).

I am using app.router.addRoute() in nuxtServerInit hook

### What is Expected?
The new route will be added and I can use it.

### What is actually happening?
New route isn't added

If there is no solution to this problem and this isn't a bug, then where can I use addRoute () to create dynamic routes on the server?

**Comment by n4ks** [comment]
> I would not recommend to add routes this way but instead use `pages/_.vue` to fetch the route from the CMS in it.

Thanks for the quick response! Could you describe in a little more detail why it is so bad to do it? I understood your advice with _.vue and will try to use it.

**Comment by danielroe** [comment]
This feature is now possible in Nuxt 3.
