### ISSUE TITLE
nuxt-link is not reactive for parameters.

### ISSUE THREAD

**Issue by patchthecode** [nuxt/nuxt#9809]
https://codesandbox.io/s/pensive-ellis-lguch?file=/pages/index.vue

### Steps to reproduce
Click on the login button in the example.

### What is Expected?
1) Page should navigate to **accountHandle** page
2) URL should say https://lguch.sse.codesandbox.io/valid

### What is actually happening?
1) Page accurately navigates to **accountHandle** page ✅
2) URL incorrectly say https://lguch.sse.codesandbox.io/invalid 🛑

Its almost as if the nuxt-link evaluates the link only once, but does not re-evaluate it again before actually navigating.

**Comment by manniL** [comment]
The issue is that you change the parameter and then call the navigate function which was already passed as callback.
Instead, `router.push` might be a better option 👍🏻

Also, this is not a Nuxt issue (as you used `router-link` in your repro)
