### ISSUE TITLE
nuxt ie下 报错 打不开项目

### ISSUE THREAD

**Issue by huxiangping** [nuxt/nuxt#9811]
![image](https://user-images.githubusercontent.com/29754783/133710244-ec5fe3e6-5102-4744-8fed-3bc6d617d9a4.png)

![image](https://user-images.githubusercontent.com/29754783/133710309-675a72ee-cd26-46ac-ae9c-b7a18ba30b35.png)
![image](https://user-images.githubusercontent.com/29754783/133710350-70b8e826-c65f-48cb-a8ff-a43e154d89ab.png)

代码设置了babel-ployFill也不行，

**Comment by huxiangping** [comment]
![image](https://user-images.githubusercontent.com/29754783/133710488-09c3ac5c-1c20-4880-9248-b27ebda71cec.png)
bendi本地代码设置babel-ployFill之后

**Comment by huxiangping** [comment]
![image](https://user-images.githubusercontent.com/29754783/133710635-110f49c4-cf7b-434c-a37c-f0925b74db85.png)
core 也试过，也是一样的报错
![image](https://user-images.githubusercontent.com/29754783/133710676-ea98bad6-1e5d-4667-a579-bfabd957d6b8.png)
第三方包代码不兼容也试过

**Comment by danielroe** [comment]
I think we can track in https://github.com/nuxt/nuxt/issues/9730.

**Comment by keminu** [comment]
一样的问题，老哥
