### ISSUE TITLE
Hot-reload not working after changes the nuxt.config.js

### ISSUE THREAD

**Issue by suguoyao** [nuxt/nuxt#9813]
### Versions

- nuxt: v2.8.1
- node: v14.17.4

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
Just modify the `nuxt.config.js` file and save it.

### What is Expected?
Render the html page normally.

### What is actually happening?
After my project is successfully started and then modify the content of nuxt.config.js. After recompilation, the client side often display a blank page with titled `Nuxt.js: loading app...`

Without any exceptions on the terminal:
```
...
ℹ Waiting for file changes                                            16:01:43
ℹ Memory usage: 461 MB (RSS: 634 MB)                                  16:01:43
```
Therefore, every time I encounter this problem, I need to end the terminal process and re execute run dev to start the project:(

**Comment by danielroe** [comment]
I can't replicate this; feel free to provide a reproduction and we can look at it afresh.
