### ISSUE TITLE
Using `context.error` method in `asyncData` should prevent execution of page template

### ISSUE THREAD

**Issue by aaronransley** [nuxt/nuxt#9835]
### Is your feature request related to a problem? Please describe.

Using the `context.error` method within `asyncData` does not stop the execution of a page's template. 
This only seems to occur after performing a SSG using `nuxt generate` and `target: 'static'` in my `~/nuxt.config.js` file.

### Describe the solution you'd like

Using the `context.error` method within `asyncData` should prevent execution of a page's template.

### Describe alternatives you've considered

Using `fetch`, but this does not provide a compatible UX; showing the standard error layout/page.

### Additional context

I'd prefer to handle 500s or 404s "gracefully", and am unsure why the page template is executing if I'm returning an error within `asyncData`. The continued execution of the template causes various errors to be logged to the browser console.

My asyncData function:
```
async asyncData({ $graphql, error, params }) {
  try {
    let req = await $graphql.default.request(someGqlHere, {
      slug: params.slug,
    })
    if (req.item) {
      return {
        item: req.item,
      }
    } else {
      return error({ statusCode: 404 })
      // Have also attempted without a return keyword to no avail:
      // error({ statusCode: 404 }}
    }
  } catch (err) {
    return error({ statusCode: 500, message: err })
    // Have also attempted without a return keyword to no avail:
    // error({ statusCode: 500, message: err })
  }
}
```

And the template that depends on item being present:
```
<div>
  {{ item.fullName }}
</div>
```

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
