### ISSUE TITLE
extractCSS removes Critical CSS in the latest Nuxt version (2.15.8)

### ISSUE THREAD

**Issue by fadamakis** [nuxt/nuxt#9859]
### Versions

- nuxt: v2.15.8
- node: v12.18.3
- vue: v2.6.14

### Reproduction

[codesandbox](https://codesandbox.io/s/sleepy-parm-rz5fx?file=/nuxt.config.js&resolutionWidth=320&resolutionHeight=675)
[codesandbox direct window](https://rz5fx.sse.codesandbox.io/)

<summary>Additional Details</summary>
<br>
Given the related note on the Nuxt  docs this was happening before and resurfaced now.  - https://nuxtjs.org/docs/configuration-glossary/configuration-build/#extractcss

### Steps to reproduce

1. Use Nuxt version 2.15.8
2. Use extractCSS build option
 
### What is Expected?
CSS to be extracted to separate files
Critical CSS to be injected in the Page

### What is actually happening?
CSS is extracted to separate files
Critical CSS is missing

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️
