### ISSUE TITLE
"modern: client" build sometimes breaks SSR

### ISSUE THREAD

**Issue by hamsterbacke23** [nuxt/nuxt#9860]
### Versions

- nuxt:  v2.15.8
- node: v14.16.0 

### Reproduction
I cannot reproduce it reliably it happens on some builds while others work fine:

This line breaks if `file` is undefined which sometimes happens, I don't know why exactly
https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-renderer/src/renderers/modern.js#L84

If I add a check similar to this line https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-renderer/src/renderers/modern.js#L109
it works!

What is going on?!
<details open>
<summary>Error message</summary>
<br>
The error:

```
ERROR  Cannot read property 'replace' of undefined

  at ModernRenderer.getModernFiles (node_modules/@nuxt/vue-renderer/dist/vue-renderer.js:644:44)
  at ModernRenderer.getPreloadFiles (node_modules/@nuxt/vue-renderer/dist/vue-renderer.js:655:52)
  at ModernRenderer.render (node_modules/@nuxt/vue-renderer/dist/vue-renderer.js:552:27)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at async nuxtMiddleware (node_modules/@nuxt/server/dist/server.js:161:20)
```

</details>

### Steps to reproduce

- Activate `modern: client` build in nuxt.config.js
- Run nuxt build
- Trigger SSR on some pages.

### What is Expected?
It should not break SSR.

### What is actually happening?
An error occurs on some builds, on others it works fine. I have no idea what's happening!

**Comment by hamsterbacke23** [comment]
Thanks, we did extend the webpack config, but not using `splitChunks` right now. Can't share our config because it's closed source, but I will try to deactivate some of the webpack settings to see if I can reproduce it.

**Comment by hamsterbacke23** [comment]
I still can't reproduce it in a fresh nuxt instance (it seems to happen just on one of our pages), but when I comment out this part in our config it seems to work again:
```
        http2: {
            push: true,
            pushAssets: (req, res, publicPath, preloadFiles) => preloadFiles
                .filter(f => f.asType === 'font' && criticalFonts.test(f.file))
                 // see https://github.com/Polymer/pwa-starter-kit/issues/254 about the crossorigin flag
                .map(f => `<${publicPath}${f.file}>; rel=preload; as=${f.asType}; crossorigin=anonymous`)
        }
```

**Comment by arikw** [comment]
I'm seeing similar behavior when `http2` push is enabled.

I added a `console.log(JSON.stringify(file), JSON.stringify(legacyJsFile));` line in `node_modules/@nuxt/vue-renderer/dist/vue-renderer.js:644` and I got the following output:

```
"c05b315.modern.js" {"file":"f2f1449.js","extension":"js","fileWithoutQuery":"f2f1449.js","asType":"script"}
"6307d74.modern.js" {"file":"7c79e7c.js","extension":"js","fileWithoutQuery":"7c79e7c.js","asType":"script"} 
"8e1394c.modern.js" {"file":"938b51d.js","extension":"js","fileWithoutQuery":"938b51d.js","asType":"script"} 
"627506e.modern.js" {"file":"b3e7d0e.js","extension":"js","fileWithoutQuery":"b3e7d0e.js","asType":"script"} 
"d827637.modern.js" {"file":"e4919c7.js","extension":"js","fileWithoutQuery":"e4919c7.js","asType":"script"} 
undefined {"file":"fdbae43.js","extension":"js","fileWithoutQuery":"fdbae43.js","asType":"script"}
```

Notice the last line - 
The `fdbae43.js` file that doesn't have a `*.modern.js` equivalent.
I saw that this file is a page component that imports another component dynamically using `import()`.
I replaced that import with a static one and the error was gone.
That trick didn't work on another faulty page, so I'm not sure what to make out of it...

**Comment by arikw** [comment]
Still no update from the team?
