### ISSUE TITLE
Selectively enable continuous loading at runtime

### ISSUE THREAD

**Issue by mrleblanc101** [nuxt/nuxt#9871]
### Is your feature request related to a problem? Please describe.

I'd like to be able to set `continuous: true` only on specific request. 
Currently it's only possible to enable it in `nuxt.config.js` which apply it every time.

### Describe the solution you'd like

`this.$nuxt.$loading.start({ continuous: true });`

### Describe alternatives you've considered

Create a custom loading component

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
