### ISSUE TITLE
fetch hook with optionMergeStrategies

### ISSUE THREAD

**Issue by hereiscasio** [nuxt/nuxt#9939]
### Is your feature request related to a problem? Please describe.

The main goal of mine is creating the way we (i mean, our team)  async load the store.

I've already design the best strategies to do that in Nuxt, 
BUT, I need to have the feature which 
makes `fetch`'s `optionMergeStrategies` just like `created`'s `optionMergeStrategies`

So, now i need to describe why this feature is very important for me 
( or for everyone, cuz i have seen other guys requested about this feature before )

The whole concept of strategies i've mentioned is too big
So to make things easier to understand, below i'll only point out the stuffs 
which directly related to this Feature request.

first of all, i have a mixin like
```js
//  ~/components/mixins/store/dynamic-registration/index.js
const loadStore = (...params) =>
{
  const [pathToStore, strategy] = params

  const strategies =
  {
    CSR: {
      async fetch () {
        await register.call(this, pathToStore)
      }
    },
    ... // ignore other strategies
  }
  return strategies[strategy]
}

export { loadStore }
```
Where `register` will do something relate to `registerModule` 
( i.e. async load store )
we don't need to know its implementation now

And the usage of "CSR" strategy above is like, 
for example, when user open up the modal, 
and that modal have corresponding store.

So i think u already understand why such store no need to be static registered
( i.e. manually put it into store/ folder )

Then, 
let me show you the pseudo code of "modal" component :

```js
// ~/components/path/to/certain/modal/container.vue
<template lang="pug">
  data-presenter(:loading='$fetchState', :data='someData')
</template>

<script>
import { mapState } from 'vuex'
import { loadStore } from '~/components/mixins/store/dynamic-registration/index.js'
// this is a presentation component(i.e. no dependencies such as store, route... )
import DataPresenter from '~/components/path/to/certain/modal/index.vue' 

export default {
  mixins: [
    // "system" is a special folder which stands for something like a "blueprint" for 
    //  our store development ( i.e. open a new store file, put some code into it ... )
    // and assuming that the modal corresponding store is in the certain page (i.e. route)  
    loadStore('~/system/pages/path/to/modal/index.js', 'CSR')
  ],
  async fetch() {
    // what `loadStore` will do is like it will dynamic register the store
    // into nuxt store/ folder    
    // so after the registration, the modal store will be located at 
    // "pages/path/to/modal/"
    // As i just mentioned that the stores putted into system/ folder are all 
    // like a blueprint; We need to use them, otherwise they're useless
    await this.$store.dispatch(`pages/path/to/modal/fetchSomeData`)
  },
  computed: {
    ...mapState({
      // after doing the action of `fetchSomeData`, we then get `someData`
      someData: state => state.pages?.path?.to?.modal?.someData
    }),
  },
  components: {
    DataPresenter
  }
}
</script>
```

BUT❗️
The `fetch` defined in mixin will be overlapped by container.vue above 
And this'll break my design ❗️

### Describe the solution you'd like

Just the same as merging strategy of normal life cycle hook ( e.g. created )
So, it'll work like below
```js
// certainMixin.js
export default {
   fetch() {
       console.log('fetching in mixin')      
   }
}

// CompA.vue
import certainMixin from 'path/to/certainMixin.js'
export default {
    mixins: [certainMixin],
    fetch() {
       console.log('fetching in component')
    }
}

// the log order will be like...
fetching in mixin     // this go first 
fetching in component // then this one
```

Above solution is making sense because `fetch` is also a lifecycle hook just like `created`, `mounted`, ...
I have no idea why it can't have the same `optionMergeStrategies` just like other hooks

### Describe alternatives you've considered

noon

### Additional context

I think the description of this Feature request is very long,
So forgive me that i then ignored my design decision＊ and other stuffs

＊how the strategies i've mentioned fits into some design principles ( e.g. SOLID )

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
