### ISSUE TITLE
Cannot add http headers to pages in development

### ISSUE THREAD

**Issue by hyperbotauthor** [nuxt/nuxt#9969]
My problem is that I have to add custom headers to my Nuxt page in order that `SharedArrayBuffer` may work.

I know how to add custom headers to assets served from the `static` folder and to the production server:

```javascript
render: {
    static: {
      setHeaders(res) {
        res.setHeader('Cross-Origin-Embedder-Policy', 'require-corp')
        res.setHeader('Cross-Origin-Opener-Policy', 'same-origin') 
      },
    },
    dist: {
      setHeaders(res) {
        res.setHeader('Cross-Origin-Embedder-Policy', 'require-corp')
        res.setHeader('Cross-Origin-Opener-Policy', 'same-origin') 
      }              
    }
  },
```

However in dev server these headers are not added to the Nuxt pages served from the `pages` folder.

If I hand write an HTML page in the `static` folder, then `SharedArrayBuffer` will work on that page. But not on the Nuxt page.

If I include the hand written, in separation working HTML in an `iframe` from the Vue page, then it again won't work.

my project:

https://github.com/hyperbotauthor/vue-chessground/tree/main/test

my related StackOverflow question:

https://stackoverflow.com/questions/69657677/how-can-one-add-custom-http-headers-to-nuxt-page-not-static-asset-in-n

**Comment by justinIs** [comment]
export default function({ res }) {
  return res?.setHeader('X-Hello', 'World')
}

`res` is not defined for when `ssr: false` is set in `nuxt.config.js`

I'm presuming we have to somehow hook into the webpack dev/hot reload server and set the headers.

I've tried

```javascript
build: {
    devMiddleware: {
      headers: { 'Cross-Origin-Embedder-Policy': 'require-corp', 'Cross-Origin-Opener-Policy': 'same-origin' }
    },
    hotMiddleware: {
      headers: { 'Cross-Origin-Embedder-Policy': 'require-corp', 'Cross-Origin-Opener-Policy': 'same-origin' }
    },
}
```

but no success.

**Comment by justinIs** [comment]
The `serverMiddleware` property did it for me. With ssr: false, some of the middleware functions are now called on the browser instead of the server. It's not overly clear which ones should get called in the dev server when `ssr: false`.

https://nuxtjs.org/docs/configuration-glossary/configuration-servermiddleware

I think the signature of the middleware callback posted above is incorrect. Here's what I did:

```typescript
// middleware/setSameOriginHeader.ts

export default function (req: any, res: any, next: any) {
     res?.setHeader('Cross-Origin-Embedder-Policy', 'require-corp')
     res?.setHeader('Cross-Origin-Opener-Policy', 'same-origin')
}
```
 
```typescript
// nuxt.config.ts

export default {
  ssr: false,
  ...
  // middleware to set headers on pages
  serverMiddleware: ['~/middleware/setSameOriginHeaders.ts'],
  // set headers on resources in static dir
  render: {
    static: {
      setHeaders(res: any) {
        res.setHeader('Cross-Origin-Embedder-Policy', 'require-corp')
        res.setHeader('Cross-Origin-Opener-Policy', 'same-origin')
      }
    }
  },
  ...
}
```

In case you run into it as well. You may have to host some static resources (extra .js library/wasm), and they'd need to come back with the headers as well.

**Comment by nkawarewebuy** [comment]
When I use the `serverMiddleware` and `render. static. setHeaders` together, it only adds the headers to the main pages, e.g /users but not on the any static assets like .js file, worker.js file

Anybody knows why does this happens? If I comment `serverMiddleware` then the other one works and vice-versa.

**Comment by polopopeye** [comment]
Thanks! I owe u my life

**Comment by carbdias** [comment]
Hello, thank you for the inputs
How would you do it for Nuxt 3 ?

**Comment by KenZync** [comment]
Please give solution for nuxt 3

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
