### ISSUE TITLE
isHMR is false during HMR

### ISSUE THREAD

**Issue by chrissyast** [nuxt/nuxt#9999]
#### MyComponent.vue
```js
...
<script>
  mounted() {
    console.log(this.$nuxt.context.isHMR)
  }
  methods: {
     // ....
  }
</script>
```

Make an edit to something within the script, forcing HMR. 

### Expected behaviour
Console logs `true` after reloading.

### Actual behaviour
```
[HMR] bundle rebuilding client.js?1b93:250 
[HMR] bundle 'client' rebuilt in 730ms client.js?1b93:195 
[HMR] bundle 'client' has 1 warnings client.js?1b93:196 
[HMR] Checking for updates on the server... process-update.js?e135:51 
false MyComponent.vue?0f54:273
```

### Environment info
Nuxt 2.15.7

**Comment by arikw** [comment]
Also on Nuxt `2.15.2` and `2.15.8`

**Comment by dzcpy** [comment]
Any solutions?

**Comment by danielroe** [comment]
I can't reproduce this. Would you provide a reproduction please? 🙏

**Comment by chrissyast** [comment]
> I can't reproduce this. Would you provide a reproduction please? 🙏

Sorry I have not gotten around to providing a repro repo yet, will do so ASAP

**Comment by chrissyast** [comment]
@danielroe I'm a bit confused by the bot's requirement to use `nuxt-edge`. Is nuxt-edge a replacement for nuxt or should it be added as a dependency in an existing nuxt project?

**Comment by danielroe** [comment]
It's an edge-release of the latest code in the nuxt repository, and is a drop-in replacement for `nuxt`:

```diff
- "nuxt": "2.15.8"
+ "nuxt-edge": "latest"
```

All the other nuxt dependencies also have `-edge` versions too, in case you have them installed explicitly.

However, in this case don't feel the need to use `nuxt-edge` - the main thing is that I can see your code + reproduce the issue.

**Comment by chrissyast** [comment]
@danielroe https://github.com/chrissyast/hmrtest

I noticed something which will help reproduce and hopefully narrow down the cause of the issue

After starting up the server etc...

1. Reload the page (both logs will be `false`)
2. Make a change to the code in the **page** and wait for HMR (both logs will be `true`)
3. Make a change to the code in the **component** and wait for HMR (log will be `true`)
  All expected behaviour so far...
4. Reload the page again (both logs will again be `false`, as expected)
5. Make a change to the code in the **component** and wait for HMR (log will be `false`, _not_ expected behaviour)

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
